### ISSUE TITLE
[bug] Tauri does not rexport certain implementation crates

### ISSUE THREAD

**Issue by prestomation** [tauri-apps/tauri#10006]
### Describe the bug

See the workaround in  #7418  as an example .

When implementing workarounds like this that interface with Tauri dependencies like webview2, the app must be sure to depend on the same version of these crates as tauri itself. There is no good way that I know of to depend on the right version except to use `cargo tree` or look at the version in the resulting error message to know which version to depend on.

Should tauri reexport these so they can be used directly?

### Expected behavior

Crates like `windows` aren't depended on directly by apps as they can use them from the tauri namespace

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 125.0.2535.85
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ Cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.15.0
    - npm: 9.5.0

[-] Packages
    - tauri [RUST]: 1.6.1
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.3.0 (outdated, latest: 1.5.6)
    - @tauri-apps/cli [NPM]: 1.3.1 (outdated, latest: 1.5.14)

[-] App
    - build-type: bundle
    - CSP: default-src 'self'; style-src 'self' 'unsafe-inline'; img-src data:; font-src data:
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by amrbashir** [comment]
I don't think we should re-export these because if you're reaching for these crates, you probably will also need to enable more features than what we enable internally, so you'll have to add it as a dependency in your `Cargo.toml` anyways.
