### ISSUE TITLE
[bug] not found processPrng ofbcryptprimitives.dll  .application is running in windows7.

### ISSUE THREAD

**Issue by thisuseryun** [tauri-apps/tauri#10008]
### Describe the bug

rustc version:1.7.8;
Cargo.toml:
```
[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1", features = [ "system-tray", "api-all", "windows7-compat" ] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
```
install app is error;
chagne rust version to 1.75:
install app is success,bug running is error:error sendding request for url;The certificate required for validation against the current system clock or timestamp in the signature file is out of validity

### Full `tauri info` output

```text
no info
```

**Comment by Legend-Master** [comment]
Rust 1.78 dropped Windows 7 support, you can downgrade to 1.77.2 if you need to support Windows 7

See https://blog.rust-lang.org/2024/05/02/Rust-1.78.0.html#compatibility-notes

**Comment by FabianLars** [comment]
Can you give a bit more context on the error you're seeing when you're using 1.75?
> chagne rust version to 1.75:
install app is success,bug running is error:error sendding request for url;The certificate required for validation against the current system clock or timestamp in the signature file is out of validity

When exactly does it happen? As soon as you start the app? Do you have any app logic that runs on app start (mostly in rust before tauri or in its setup hook but also in javascript)?

Is the windows 7 machine fully up to date? And Is it connected to the internet?

Is your app signed?

Is your project code public or do you think you can come up with a minimal reproduction example?

Sorry for all those random questions but i've not seen this error before...

**Comment by thisuseryun** [comment]
I'm so sorry,it's not tauri ission;just https sign is expired.this question is solve by change rustc version to 1.75
