### ISSUE TITLE
The system cannot find the file specified. (os error 2)

### ISSUE THREAD

**Issue by Runkang10** [tauri-apps/tauri#10029]
### Describe the bug

This error happens when I'm using CROSS compilation in Github Action during on generation of executable file and msi installer for Windows.

### Reproduction

[https://github.com/32-Project/TP32/actions/runs/9447445796/job/26019256353](https://github.com/32-Project/TP32/actions/runs/9447445796/job/26019256353)

### Expected behavior

[LOGS]
Built application at: D:\a\TP32\TP32\src-tauri\target\release\tp32.exe
Info Verifying wix package
Downloading https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
Info validating hash
Info extracting WIX
Info Target: x64
Error failed to bundle project: `The system cannot find the file specified. (os error 2)`

### Full `tauri info` output

```text
I haven't tauri info in Github Action.
```

**Comment by FabianLars** [comment]
Hmm, i _think_ it's this line: https://github.com/32-Project/TP32/blob/main/src-tauri/tauri.conf.json#L45 The file itself doesn't have the .md extension. If that doesn't help, try changing `args: ${{ matrix.args }}` to `args: ${{ matrix.args }} -vvv` to get more logs.

**Comment by Runkang10** [comment]
Thank you. 👍
