### ISSUE TITLE
[bug] Android app crashes on startup on tauri/tauri-build upgrade

### ISSUE THREAD

**Issue by BSteffaniak** [tauri-apps/tauri#10024]
### Discussed in https://github.com/tauri-apps/tauri/discussions/9927

<div type='discussions-op-text'>

<sup>Originally posted by **BSteffaniak** May 30, 2024</sup>
Hi, after upgrading from tauri 2.0.0-beta.20 to tauri 2.0.0-beta.21 and tauri-build 2.0.0-beta.16 to tauri-build 2.0.0-beta.17 I receive this error when starting the app and it crashes immediately:

```
...
Performing Streamed Install
Success
Starting: Intent { cmp=com.moosicbox_app/.MainActivity }
--------- beginning of main
05-30 15:38:36.843 22632 22632 I m.moosicbox_app: Late-enabling -Xcheck:jni
05-30 15:38:36.885 22632 22632 W m.moosicbox_app: Unexpected CPU variant for x86: x86_64.
05-30 15:38:36.885 22632 22632 W m.moosicbox_app: Known variants: atom, sandybridge, silvermont, kabylake, default
05-30 15:38:36.962 22632 22632 W ziparchive: Unable to open '/data/app/~~NKakGU_JYKht2BW4D-7BOA==/com.moosicbox_app-AcG2kaqCXxaxo0QLULrJyw==/base.dm': No such file or directory
05-30 15:38:36.962 22632 22632 W ziparchive: Unable to open '/data/app/~~NKakGU_JYKht2BW4D-7BOA==/com.moosicbox_app-AcG2kaqCXxaxo0QLULrJyw==/base.dm': No such file or directory
05-30 15:38:37.327 22632 22632 E m.moosicbox_app: No implementation found for void com.moosicbox_app.WryActivity.create(com.moosicbox_app.WryActivity) (tried Java_com_moosicbox_1app_WryActivity_create and Java_com_moosicbox_1app_WryActivity_create__Lcom_moosicbox_1app_WryActivity_2)
--------- beginning of crash
05-30 15:38:37.327 22632 22632 E AndroidRuntime: FATAL EXCEPTION: main
05-30 15:38:37.327 22632 22632 E AndroidRuntime: Process: com.moosicbox_app, PID: 22632
05-30 15:38:37.327 22632 22632 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for void com.moosicbox_app.WryActivity.create(com.moosicbox_app.WryActivity) (tried Java_com_moosicbox_1app_WryActivity_create and Java_com_moosicbox_1app_WryActivity_create__Lcom_moosicbox_1app_WryActivity_2)
05-30 15:38:37.327 22632 22632 E AndroidRuntime:        at com.moosicbox_app.WryActivity.create(Native Method)
05-30 15:38:37.327 22632 22632 E AndroidRuntime:        at com.moosicbox_app.WryActivity.onCreate(WryActivity.kt:62)
05-30 15:38:37.327 22632 22632 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8305)
05-30 15:38:37.327 22632 22632 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8284)
05-30 15:38:37.327 22632 22632 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
05-30 15:38:37.327 22632 22632 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
05-30 15:38:37.327 22632 22632 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
05-30 15:38:37.327 22632 22632 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
05-30 15:38:37.327 22632 22632 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-30 15:38:37.327 22632 22632 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-30 15:38:37.327 22632 22632 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
05-30 15:38:37.327 22632 22632 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
05-30 15:38:37.327 22632 22632 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
05-30 15:38:37.327 22632 22632 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
05-30 15:38:37.327 22632 22632 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7872)
05-30 15:38:37.327 22632 22632 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-30 15:38:37.327 22632 22632 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-30 15:38:37.327 22632 22632 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
        Info Watching C:\Users\Brade\GitHub\MoosicBoxApp\src-tauri for changes...
```

Maybe one of these PRs is causing this to now happen?

* https://github.com/tauri-apps/tauri/pull/9858
* https://github.com/tauri-apps/tauri/pull/9890

Am I missing an upgrade migration step?

Thanks!</div>

# Further details:

I have created a small reproduction of the issue on these two branches:

* Successful build and successful app run: https://github.com/MoosicBox/MoosicBoxApp/tree/tauri-android-crash-success
* Successful build and *crash* app run: https://github.com/MoosicBox/MoosicBoxApp/tree/tauri-android-crash-failure

And the diff between these two branches is strictly in the cargo.toml files:

https://github.com/MoosicBox/MoosicBoxApp/compare/tauri-android-crash-failure...tauri-android-crash-success

The diff is backwards because I first replicated the failure and then reverted the versions to fix it.

In order to run the app I did these steps:

1. `pnpm install`
2. `pnpm tauri android dev`

Please let me know if you need any more details.

Thanks!

**Comment by pewsheen** [comment]
Should be #9858. It's now using the `identifier` field in `tauri.conf.json` as your Android package name. In this case, your app's package name has changed from `com.moosicbox_app` to `com.moosicbox`

You'll need to change all `com.moosicbox_app` to `com.moosicbox` under your `src-tauri/gen/android` folder. Including the folder `src-tauri/gen/android/app/src/main/java/com/moosicbox_app` should change to `src-tauri/gen/android/app/src/main/java/com/moosicbox`.

Or you can backup your (in case something goes wrong) `src-tauri/gen/android/`, then remove it, and run `tauri android init` again to generate a new Android project.

**Comment by BSteffaniak** [comment]
As far as I can tell, when I delete my `gen` folder and rerun `tauri android init`, the name is still generated as `com.moosicbox_app`.

I also tried manually removing the `_app` portion to match the `tauri.conf.json > identifier` value, but then I get this error:

```
❯ pnpm tauri android dev

> MoosicBoxApp@0.0.0 tauri C:\Users\Brade\GitHub\MoosicBoxApp3
> tauri "android" "dev"

        Info Detected connected device: Pixel_7_Pro_API_33 (sdk_gphone64_x86_64) with target "x86_64-linux-android"
       Error Project directory C:\Users\Brade\GitHub\MoosicBoxApp3\src-tauri\gen/android\app/src/main\java/com/moosicbox_app does not exist. Did you update the package name in `Cargo.toml` or the bundle identifier in `tauri.conf.json > identifier`? Save your changes, delete the `gen/android` folder and run `tauri android init` to recreate the Android project.
 ELIFECYCLE  Command failed with exit code 1.
```

It seems like it's still trying to use com.moosicbox_app for some reason.

I tried these changes on the https://github.com/MoosicBox/MoosicBoxApp/tree/tauri-android-crash-failure branch, so you can see the Cargo.toml/lock versions there if that is of any help.

**Comment by pewsheen** [comment]
Seems you are using pnpm as well. Have you updated the node dependency: `@tauri-apps/cli` and `@tauri-apps/api`?

**Comment by BSteffaniak** [comment]
Ahhh... that is it. I have both my cargo dependencies and node dependencies set up to auto update the versions every night, but for some reason I had the @tauri-apps/cli and @tauri-apps/api versions pinned to an older beta version by accident. Updating those to the latest versions has fixed this issue for me. Thank you!

**Comment by thewh1teagle** [comment]
I experience the same issue when trying to build tauri app for android.
Did you found solution?
This is how my `lib.rs` looks like: [`lib.rs`](https://github.com/thewh1teagle/vibe/blob/feat/android-support/desktop/src-tauri/src/lib.rs#L24)

Related: https://github.com/tauri-apps/tauri/issues/10094

**Comment by thewh1teagle** [comment]
Fixed by

```console
cargo install tauri-cli --git https://github.com/tauri-apps/tauri
rm -rf src-tauri/gen/android
cargo tauri android init
bun run scripts/dev_sign.js # https://github.com/thewh1teagle/vibe/blob/feat/android-support/scripts/dev_sign.js
# Add `android.defaults.buildfeatures.buildconfig=true` to `gradle.properties`
# Uninstall old app
cargo tauri android dev
```

**Comment by ohaddahan** [comment]
> Fixed by
> 
> ```
> cargo install tauri-cli --git https://github.com/tauri-apps/tauri
> rm -rf src-tauri/gen/android
> cargo tauri android init
> bun run scripts/dev_sign.js # https://github.com/thewh1teagle/vibe/blob/feat/android-support/scripts/dev_sign.js
> # Add `android.defaults.buildfeatures.buildconfig=true` to `gradle.properties`
> # Uninstall old app
> cargo tauri android dev
> ```

Same issue, but this didn't help :(
