### ISSUE TITLE
Windows build doesn't work with custom dist dir

### ISSUE THREAD

**Issue by nklayman** [tauri-apps/tauri#1003]
**Describe the bug**
The Wix build script will look for the `src-tauri/icons` folder relative to the set cargo target dir. This means it won't find them if the target dir is changed, like what the vue cli plugin does.

**To Reproduce** (not tested, but I'm pretty sure this will fail it)
1. Create tauri project
2. On windows, run `$env:CARGO_TARGET_DIR = 'other_dist'` and `yarn tauri build`

Or use the [vue cli plugin](https://github.com/tauri-apps/vue-cli-plugin-tauri) to build an app.

**Expected behavior**
Build works

**Screenshots**

**Platform and Versions (please complete the following information):**

OS: Windows
Node: Any
NPM: Any
Yarn: Any
Rustc: Any

**Additional context**
https://github.com/tauri-apps/tauri/blob/3005204a314f52cafb1edae8f3a8a7d0fe863d8f/cli/tauri-bundler/src/bundle/wix.rs#L147-L165

Caused #992

**Comment by jbolda** [comment]
Confirmed:

```shell
❯ npx @vue/cli create test-vue-tauri-app && cd test-vue-tauri-app && npx @vue/cli add tauri && yarn tauri:build
[snip]
info: Target: x64
error: Path Error:`Path "C:\Users\Jacob\Documents\dev\tauri\test-vue-tauri-app\icons" does not exist or you don't have a
ccess!`

 app:spawn Command "cargo" failed with exit code: 1 +0ms

 app:tauri (runner) ⚠️  [FAIL] Cargo CLI has failed +0ms

 app:tauri Shutting down tauri process... +1ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nklayman** [comment]
@jbolda can you try with the non-vue reproduction instructions? I want to make sure those work as well.

**Comment by jbolda** [comment]
on git bash:
```shell
❯ CARGO_TARGET_DIR=other_dist yarn tauri build
[snip]
    Finished release [optimized] target(s) in 1m 31s
info: Target: x64
info: running candle for main.wxs
info: running candle.exe
info: running light to produce other_dist\release\bundle/msi/finatr_0.3.0_x64.msi
error: Shell Scripting Error:`error running light.exe, try running with --verbose to see command output`

 app:spawn Command "cargo" failed with exit code: 1 +0ms

 app:tauri (runner) ⚠️  [FAIL] Cargo CLI has failed +0ms

 app:tauri Shutting down tauri process... +1ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mdarrik** [comment]
Can also confirm that the repro step works on a base tauri project (tauri init + 1 html file). 
Here's a link to the project for reference. https://github.com/mdarrik/tauri-windows-custom-out-dir-repro
```bash
info: running candle for main.wxs
info: running candle.exe
info: running light to produce other_dist\release\bundle/msi/test-tauri_0.1.0_x64.msi
error: Shell Scripting Error:`error running light.exe, try running with --verbose to see command output`

 app:spawn Command "cargo" failed with exit code: 1 +13ms

 app:tauri (runner) ⚠️  [FAIL] Cargo CLI has failed +6ms

 app:tauri Shutting down tauri process... +4ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by taswyn** [comment]
So I think I have it all sorted out for just some modest changes to the vue cli plugin tauri that should keep everything cross-compatible/working with anything that doesn't use the dist directory, I just need to figure out if I've got the copying working properly

**Comment by sanket143** [comment]
I am also facing this issue when using it with Nuxt.js.
