### ISSUE TITLE
[bug]iOS packaging cannot package rust code

### ISSUE THREAD

**Issue by yIllusionSky** [tauri-apps/tauri#10032]
### Describe the bug

I used `cargo tauri ios build`, but the packaged file was only 4MB, and I did not see the packaging process of the rust code during the packaging process. The size should be at least 20 MB. I used `cargo tauri ios dev` and it was normal, and the following information was reported

2024-06-11 09:28:04.351 xcodebuild[31504:1829343] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot11/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-22267/IDEFoundation/Provisioning/Capabilities Infrastructure/IDECapabilityQuerySelection.swift:103
Details:  createItemModels creation requirements should not create capability item model for a capability item model that already exists.
Function: createItemModels(for:itemModelSource:)
Thread:   <_NSMainThread: 0x600002c5c080>{number = 1, name = main}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.

### Full `tauri info` output

```text
WARNING: Only one package manager should be used, but found npm and bun.
         Please remove unused package manager lock files, will use npm for now!

[✔] Environment
    - OS: Mac OS 14.0.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.0-nightly (9c9b56879 2024-05-05)
    ✔ cargo: 1.80.0-nightly (05364cb2f 2024-05-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: nightly-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 22.1.0
    - npm: 10.7.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.22
    - tauri-build [RUST]: 2.0.0-beta.17
    - wry [RUST]: 0.40.1
    - tao [RUST]: 0.28.0
    - tauri-cli [RUST]: 2.0.0-beta.20
    - @tauri-apps/api [NPM]: 2.0.0-beta.6
    - @tauri-apps/cli [NPM]: 2.0.0-beta.20

[-] App
    - build-type: bundle
    - CSP: default-src 'self'; img-src 'self' data:;; connect-src ipc: http://ipc.localhost
    - frontendDist: ../dist
    - devUrl: http://localhost:5173/
    - framework: Vue.js
    - bundler: Rollup

[-] iOS
    - Developer Teams: **
```

**Comment by pewsheen** [comment]
I can't reproduce this. Do you have a minimal reproducible repo?

**Comment by yIllusionSky** [comment]
> I can't reproduce this. Do you have a minimal reproducible repo?

I don’t know what happened, but I somehow solved it, thank you.
