### ISSUE TITLE
[feat] tauri.conf.json  how to config  additionalBrowserArgs 

### ISSUE THREAD

**Issue by chenlvzhou** [tauri-apps/tauri#10035]
### Describe the problem

How to configure browser parameters for automatic microphone authorization without popping up an authorization window

### Describe the solution you'd like

How to configure browser parameters for automatic microphone authorization in internal Windows desktop applications without the need for an authorization window to pop up

**Comment by FabianLars** [comment]
```json
"additionalBrowserArgs": "--disable-features=msWebOOUI,msPdfOOUI,msSmartScreenProtection --autoplay-policy=no-user-gesture-required --auto-accept-camera-and-microphone-capture"
```
This assumes `--auto-accept-camera-and-microphone-capture` is the cli flag you're asking for. I did not find another one. The other flags are the ones Tauri sets by default.

**Comment by chenlvzhou** [comment]
@FabianLars

**Comment by chenlvzhou** [comment]
@FabianLars
    "additionalBrowserArgs": "--disable-features=msWebOOUI,msPdfOOUI,msSmartScreenProtection --autoplay-policy=no-user-gesture-required --auto-accept-camera-and-microphone-capture"
    "additionalBrowserArgs": "--auto-accept-camera-and-microphone-capture"
  Both options are ineffective

**Comment by FabianLars** [comment]
Then i assume chromium, or at least edge/webview2, doesn't support this flag. Did you try any other flags? I assumed since you specifically asked for this feature you may have a flag in mind.

**Comment by chenlvzhou** [comment]
"additionalBrowserArgs": "--use-fake-ui-for-media-stream"   is ok
