### ISSUE TITLE
[feat] [macOS] event on the app become active

### ISSUE THREAD

**Issue by anatawa12** [tauri-apps/tauri#10043]
### Describe the problem

for macOS, It's common to not quit app when all windows are removed and show window again on app icon on deck clicked.

Tauri provides way to implement "quit app when all windows are removed" with `ExitRequested` event. (I feel this is not good name since it's not about cmd+q but it's out of this issue scope.)
However, the way to implement "show window again on app icon on deck clicked" is not there.

### Describe the solution you'd like

I want tauri to have RunEvent and global event on clicking app icon on deck

**Comment by FabianLars** [comment]
This is available in v2 https://docs.rs/tauri/2.0.0-beta/x86_64-apple-darwin/tauri/enum.RunEvent.html#variant.Reopen - afaik there are currently no plans to backport this to v1 (because it needs upstream changes, not just tauri).
