### ISSUE TITLE
[bug] `cargo tauri dev` not working with `tray-icon` field in `tauri.conf.json`

### ISSUE THREAD

**Issue by kkrime** [tauri-apps/tauri#10056]
### Describe the bug

When adding `tray-icon` to `tauri.conf.json` I get the following when running `cargo tauri dev`

```Error `tauri.conf.json` error on `app`: Additional properties are not allowed ('tray-icon' was unexpected)```

Same with `cargo tauri build` 

### Reproduction

`tauri.conf.json`:

`{
  "productName": "Tauri App",
  "version": "0.1.0",
  "identifier": "com.tauri.dev",
  "build": {
    "frontendDist": "../build",
    "devUrl": "http://localhost:5173",
    "beforeDevCommand": "npm run dev",
    "beforeBuildCommand": "npm run build"
  },
  "app": {
    "tray-icon": {
      "id": "id",
      "icon-path": "icons/icon.ico"
    },
    "windows": [
      {
        "title": "Tauri",
        "width": 800,
        "height": 600,
        "resizable": true,
        "fullscreen": false
      }
    ],
    "security": {
      "csp": null
    }
  },
  "bundle": {
    "macOS": {
      "entitlements": "./Info.plist",
      "exceptionDomain": "",
      "frameworks": [],
      "providerShortName": null,
      "signingIdentity": null
    },
    "active": true,
    "targets": "all",
    "icon": [
      "icons/32x32.png",
      "icons/128x128.png",
      "icons/128x128@2x.png",
      "icons/icon.icns",
      "icons/icon.ico"
    ]
  },
  "plugins": {}
}`

### Full `tauri info` output

```text
`Error `tauri.conf.json` error on `app`: Additional properties are not allowed ('tray-icon' was unexpected)`
```

### Additional context

I ran;
`cargo install tauri-cli --version "^2.0.0-beta"`
`cargo tauri migrate`

Before hand

`cargo run` does work, so I know it's not an issue with the `tauri.conf.json` formatting

**Comment by FabianLars** [comment]
It should be `trayIcon` not `tray-icon`. Can you check if that works fine?

**Comment by kkrime** [comment]
`trayIcon` gives me:

```Error `tauri.conf.json` error on `app > trayIcon`: {"id":"id","icon-path":"icons/icon.ico"} is not valid under any of the schemas listed in the 'anyOf' keyword```

**Comment by FabianLars** [comment]
same for iconPath then, as far as i know, there's not a single object key that uses a `-`, they should all be in `trayIcon` casing.

**Comment by kkrime** [comment]
That did the trick, thank you @FabianLars 🙏
