### ISSUE TITLE
[feat] Add mobile linux desktop entry config

### ISSUE THREAD

**Issue by RoseBlume** [tauri-apps/tauri#10052]
### Describe the problem

There is no way to modify the desktop entry for linux before the app has been bundled. This makes it annoying when developing packages for mobile linux because you must have this line in the desktop file in order to have it considered `mobile friendly` 
```sh
X-Purism-FormFactor=Workstation;Mobile;
```
Not having this line would mean that your app will not appear by default on phosh and other mobile desktop environments.

### Describe the solution you'd like

I would like something like this added to tauri.conf.json where each line is appended to the end of the desktop file and then bundled to create the deb or rpm
```json
{
  "deb": {
    "files": {},
    "desktop": [
          "X-Purism-FormFactor=Workstation;Mobile;", 
          "X-GNOME-UsesNotifications=true"
    ]
  },
  "rpm": {
    "epoch": 0,
    "files": {},
    "release": "1",
    "desktop": [
          "X-Purism-FormFactor=Workstation;Mobile;", 
          "X-GNOME-UsesNotifications=true"
    ]
  }
}
```

### Alternatives considered

Something like this
```
{
  "appimage": {
    "bundleMediaFramework": false,
    "files": {}
  },
  "deb": {
    "files": {},
    "mobile-friendly": true
  },
  "rpm": {
    "epoch": 0,
    "files": {},
    "release": "1",
    "mobile-friendly": true
  }
}
```

### Additional context
By allowing these to be configured within tauri.conf.json it will make it simpler for people who are new to mobile linux to create system and flathub packages.
_No response_

**Comment by FabianLars** [comment]
Both the deb and rpm packages have a `desktopTemplate` config you can use to well, overwrite the desktop template file the bundler uses.
https://v2.tauri.app/reference/config/#desktoptemplate
It's still missing from the Build docs but the default template is here for v2: https://github.com/tauri-apps/tauri/blob/dev/tooling/bundler/src/bundle/linux/templates/main.desktop

**Comment by RoseBlume** [comment]
It only allows a few options, none that will allow it to show up as a mobile friendly app

**Comment by FabianLars** [comment]
you can literally write anything you want in that file. The variables the docs mention are just what tauri can replace dynamically (see the `{{}}` syntax in the linked template file). What's not available as a variable needs to be hard coded.
