### ISSUE TITLE
[bug][ci] `cargo-platform` MSRV Bump Will Break CI Tests

### ISSUE THREAD

**Issue by tillmann-crabnebula** [tauri-apps/tauri#10050]
### Describe the bug

The current CI test suite runs on Rust 1.70 but a dependency `cargo-platform` bumped their MSRV on `0.1.8` (we currently have `0.1.7` in our lock file) to 1.73 which will break our test CI runs.

```
error: package `cargo-platform v0.1.8` cannot be built because it requires rustc 1.73 or newer, while the currently active rustc version is 1.70.0
Either upgrade to rustc 1.73 or newer, or use
cargo update -p cargo-platform@0.1.8 --precise ver
where `ver` is the latest version of `cargo-platform` supporting rustc 1.70.0
Error: Process completed with exit code 101.
```

So either we pin `cargo-platform` or upgrade our MSRV to 1.73 for all of our tests.

### Reproduction

https://github.com/tauri-apps/tauri/pull/10028

### Expected behavior

Tests run successfully

### Full `tauri info` output

```text
-
```

**Comment by amrbashir** [comment]
I think we can upgrade to 1.73, but let's pin cargo-platform to 0.1.7 for a little bit longer, in `dev` branch, we have it in lock file for the main workspace as `0.1.7`.

Also seems like this affects https://github.com/tauri-apps/tauri/pull/10028 only so I will push the above changes to your PR and close this issue.
