### ISSUE TITLE
Windows application shortcut abnormality.

### ISSUE THREAD

**Issue by kjxbyz** [tauri-apps/tauri#10071]
Windows application shortcut abnormality.

https://github.com/cyf/faforever/blob/main/src-tauri/tauri.conf.json

<img width="511" alt="2024-06-16 15 52 25" src="https://github.com/tauri-apps/tauri-action/assets/47768002/a065eb87-c97d-476b-a5a7-988aed2b9d38">

**Comment by FabianLars** [comment]
Hmm, i just installed your app and the icon showed up fine. This looks like another issue with Windows' icon cache to me 🤔 Try restarting explorer.exe or your whole PC maybe?

**Comment by kjxbyz** [comment]
Which installer did you install?

**Comment by FabianLars** [comment]
Both the setup.exe _and_ the msi - can't remember the order but I uninstalled the first one before installing the second one.

**Comment by kjxbyz** [comment]
It doesn't work for me. I installed it on a virtual machine running Windows 11. Maybe it's a problem with the virtual machine.

**Comment by kjxbyz** [comment]
@FabianLars When using the scoop to install, the generated shortcut has a issue. There may be a compatibility issue with scoop. How can I disable the creation of shortcuts during silent installation?

https://github.com/cyf/scoop-bucket/blob/d3b7ab66e10a9ea13d80474a81ed09e9779c8810/bucket/faforever.json#L20

After the installation is complete, regenerate a shortcut by configuring shortcuts in the scoop manifest.

https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests#required-properties

**Comment by FabianLars** [comment]
@kjxbyz call the nsis installer with the /NS flag (NoShortcut mode)

**Comment by kjxbyz** [comment]
Thank you
