### ISSUE TITLE
[bug] `plugin` command failing for mobile plugins

### ISSUE THREAD

**Issue by FabianLars** [tauri-apps/tauri#10082]
### Describe the bug

Mainly reporting this because i have no time to look into it right now.

`plugin new --mobile` (partially) fails with `failed to render plugin Android template: No such file or directory` - i don't see which file it's talking about.
`plugin new --ios` also fails(?) or at least complains about the Android template.
`plugin new` - so no mobile - still creates most mobile code, just without the ios and android folders, i get the idea behind it but it _looks_ like it can cause issues.

Edit: The iOS folder is always empty even if i just use the `--ios` flag (because of it failing on the android template i assume).

### Full `tauri info` output

```text
I'm not inside a tauri project but i'm on latest macos with the latest tauri cli, tried both the released version and from git after Tillmann told me that there were recent changes.
```

### Additional context

I assigned Amr for now (blame Tillmann lol) but i think i can take a look next week or the week after too.

**Comment by pyranota** [comment]
Have the same problem

**Comment by songjiachao** [comment]
Have the same problem

**Comment by amrbashir** [comment]
looks like an issue with iOS template as `plugin new --android` works just fine, will open a PR to fix this.
