### ISSUE TITLE
[bug] nsis deep link doesn't work

### ISSUE THREAD

**Issue by thewh1teagle** [tauri-apps/tauri#10095]
### Describe the bug

When using deep link plugin in v2 project and adding desktop deep link schemas in `tauri.conf.json` the deep link doesn't work with `nsis` target while with `msi` it work.

### Reproduction

1. Add deep link plugin and `single-instance` (I use both)
2. Add plugins config to tauri conf

```json
  "plugins": {
    "deep-link": {
      "mobilde": {},
      "desktop": {
        "schemas": ["deep"]
      }
    }
  },
```

3. Build the app and install nsis installer.
4. Paste in console in browser:

```
location.href = "deep://test"
```
Notice the error.
5. Install msi target and try again and see that it works. 

### Expected behavior

It should open the app with that schema for nsis  

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 126.0.2592.61
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.77.1 (7cf61ebde 2024-03-27)
    ✔ cargo: 1.77.1 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.12.0
    - npm: 10.5.0
    - bun: 1.1.10

[-] Packages
    - tauri [RUST]: 2.0.0-beta.22
    - tauri-build [RUST]: 2.0.0-beta.17
    - wry [RUST]: 0.40.1
    - tao [RUST]: 0.28.1
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-beta.20

[-] App
    - build-type: bundle
    - CSP: unset
```

### Additional context

I implemented it and register it in runtime with no admin rights and it works!
see [src-tauri/src/register_custom_protocol.rs](https://github.com/thewh1teagle/vibe/blob/main/desktop/src-tauri/src/register_custom_protocol.rs)

There's option to create runtime api in Windows
https://stackoverflow.com/questions/80650/how-do-i-register-a-custom-url-protocol-in-windows

https://stackoverflow.com/questions/45809064/registering-custom-protocol-at-installation-process-in-electron-app

After review cli code, looks like it simply doesn't implemented for nsis

**Comment by Legend-Master** [comment]
I can not reproduce this using API example in current head with this configuration

```json
"deep-link": {
  "desktop": {
    "schemes": ["my-tauri-app"]
  }
}
```

https://github.com/tauri-apps/tauri/assets/68118705/4bfa74fd-ccd6-4f03-86d5-1814adf98c23

But I found another bug, the current uninstaller can't remove the deep link it registered 😂 (just opened a PR for that #10103)

**Comment by amrbashir** [comment]
closing this as it can't be reproduced, if the issue still exists, please provide a minimal repro
