### ISSUE TITLE
GH scripts

### ISSUE THREAD

**Issue by Suya1671** [tauri-apps/tauri#1011]
**Is your feature request related to a problem? Please describe.**
In the docs there is no clear indication on what to do for app CI, aka installing rust tools and running `npm run tauri build` and how to do matrix builds for multiple platforms as each has their own dependencies

**Describe the solution you'd like**
A section in the docs on making a github actions script that downloads the code for your app, installs the rust and npm dependencies then does `npm run build` and then `npm run tauri build` which creates the builds

**Additional context**
Maybe add a section for other CI software?

**Comment by nklayman** [comment]
See https://github.com/tauri-apps/tauri-action. We are working on polishing this up and then will add it to the docs site.
