### ISSUE TITLE
[ Question ] Minimum Window Size: Enforce

### ISSUE THREAD

**Issue by dfirence** [tauri-apps/tauri#1013]
Hi Guys,

On Tauri.conf, we can set the window height and width, as well as, the resizable flag.

Is there any way to enforce a minimum Height & Width?

In my tests, I can minimize the window to a tiny dot, and I would like to enforce a minimum height and width.  This is achievable in Electron from the Window Object.

**Comment by nklayman** [comment]
This is added in the dev branch, and will available in the next release.

**Comment by luyangliuable** [comment]
hi is this avalaible?
