### ISSUE TITLE
[bug] animation freeze on the app but not the browser

### ISSUE THREAD

**Issue by Zweird-958** [tauri-apps/tauri#10140]
### Describe the bug

Hello 👋, I am developing an desktop app with Tauri and Next.js.
But animation freeze on the app.
On the browser it works, and I don't know how to fix it...

If someone can help me thank you 🙏 

https://github.com/tauri-apps/tauri/assets/83603824/19543094-69d4-40ac-acad-392dc02f534a

### Reproduction

Here is my repo https://github.com/Zweird-958/my-wishlist/tree/feature/desktop
Run desktop with `bun run desktop`

### Expected behavior

https://github.com/tauri-apps/tauri/assets/83603824/381b400c-838e-4f85-98ef-20e840fa8c11

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.9.0
    - pnpm: 8.15.3
    - npm: 10.1.0
    - bun: 1.1.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.22
    - tauri-build [RUST]: 2.0.0-beta.17
    - wry [RUST]: 0.40.1
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.13
    - @tauri-apps/cli [NPM]: 2.0.0-beta.20

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../out
    - devUrl: http://localhost:3003/
    - framework: React (Next.js)
    - bundler: Webpack
```

### Stack trace

```text
- Tauri: 2
- NextUI
- Framer
- NextJS
```

**Comment by FabianLars** [comment]
Which browser did you test this in? If it wasn't Safari, can you please test it in Safari too? Safari is basically the same as tauri's webview so we can check whether it's a webkit issue or really tauri-specific.

**Comment by Zweird-958** [comment]
> Which browser did you test this in? If it wasn't Safari, can you please test it in Safari too? Safari is basically the same as tauri's webview so we can check whether it's a webkit issue or really tauri-specific.

Right, It's lagging on safari too, thank you 🙏 
Honestly i don't know how to fix it, i will create an issue on next-ui
