### ISSUE TITLE
[bug] it is too easy to have a js plugin lib on one version and rust on another

### ISSUE THREAD

**Issue by jessfraz** [tauri-apps/tauri#10149]
### Describe the bug

It is too easy to have a  js plugin lib on one version and rust on another.

We literally just fixed a bug where the yarn.lock had a specific patch version of plugin-fs, and the rust crate had another and they were not compatible.

We could no longer export files. Now that i dont care about, break shit all you want, but you need to provide a `validate` cli command or something that we can throw in ci when this isnt compatible. We don't want to have to write some ci job scraping the yarn.lock and Cargo.lock for this when you all have all the context. 

Thank you! At this point every single time we have updated a dep something has broken. As a library you should want people to update and encourage them to, it makes your lives easier. So make it better for us to update and we will.

also why doesn't `yarn tauri info` give plugin information as well? it should.

### Full `tauri info` output

```text
$ yarn tauri info
yarn run v1.22.22
$ /Users/macinatormax/kittycad/modeling-app/node_modules/.bin/tauri info

[✔] Environment
    - OS: Mac OS 14.5.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 22.3.0
    - yarn: 1.22.22
    - npm: 10.8.1
    - bun: 1.0.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.17
    - tauri-build [RUST]: 2.0.0-beta.13
    - wry [RUST]: 0.39.3
    - tao [RUST]: 0.27.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.12
    - @tauri-apps/cli [NPM]: 2.0.0-beta.20

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:3000/
    - framework: React
    - bundler: Vite
✨  Done in 2.57s.
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by amrbashir** [comment]
I see you're using the beta versions and so it is normal that beta will contain breaking changes. However, once v2 hits stable, these packages will be stable and will be backwards compatible, i.e. will never break after an update, and if it does break, it is an unintentional bug, and we will fix it immediately. 

Sorry for the inconvenience, please bear with us as we push through the bugs and hit stable for v2.
