### ISSUE TITLE
Function to Load Binary Files as Base64

### ISSUE THREAD

**Issue by zicklag** [tauri-apps/tauri#1015]
**Is your feature request related to a problem? Please describe.**
I'm wanting to load images into a webpage from the filesystem ina Tauri app, but that requires base64 encoding them as a data URI and the browser built-in `btoa` doesn't work with the byte array returned by Tauri.

**Describe the solution you'd like**
I would like an option to the `readBinaryFile` function that would allow you to run `readBinaryFile('myfile.png', { base64: true })` and get a base64 encoded version of the file that could then easily be added to `data:image/png;base64,` in a string to create a data URI that could be used to display the image onthe page.

**Describe alternatives you've considered**
You could make it a separate function instead of adding it as an optino to `readBinaryFile`.

**Additional context:**
I currently have to add a dependency on a JS base64 encoder that supports bytes arrays as inputs in order to make this work so having this built-in would save me a dependency for my app.

**Comment by Grewer** [comment]
I happened to encounter this situation
```
const img = await readBinaryFile(path)
const base64 = Buffer.from(img).toString('base64')
```

**Comment by olegshilov** [comment]
Maybe this helps?
https://stackoverflow.com/questions/9267899/arraybuffer-to-base64-encoded-string

**Comment by lucasfernog** [comment]
@olegshilov is right, the API example uses that approach: https://github.com/tauri-apps/tauri/blob/6a95d7acc378b40230bab18d00ea32de40a5818c/examples/api/src/components/FileSystem.svelte#L13

**Comment by dmca-glasgow** [comment]
This solution is working for me in browser (tauri) and node (unit tests):

```ts
import { readBinaryFile } from '@tauri-apps/api/fs';

const img = await readBinaryFile(imagePath);
const base64 = btoa(String.fromCharCode(...img));
```
