### ISSUE TITLE
[bug] [v2] Drop Events are not window specific

### ISSUE THREAD

**Issue by jaydevelopsstuff** [tauri-apps/tauri#10169]
### Describe the bug

`tauri://drop-over` and `tauri://drop` events seem to propagate to all open windows. 

The events that are dispatched to unfocused window seem to use provide a cursor position relative to the focused window where the drop event originated from, and there is no data in the event that provides the window from which the event originated.

What I described above makes me think that this is indeed unintended behavior, which is quite concerning as Tauri v2 has been in beta for quite some time...

### Reproduction

Create 2 windows, each with a drop listener and observe that the event is dispatched to both even when just one is focused.

### Expected behavior

`tauri://drop-over` and `tauri://drop` events are only dispatched to the focused window.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.81.0-nightly (e9e6e2e44 2024-06-28)
    ✔ cargo: 1.81.0-nightly (4ed7bee47 2024-06-25)
    ✔ rustup: 1.27.1 (2024-04-24)
    ✔ Rust toolchain: nightly-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 22.1.0
    - pnpm: 9.1.0
    - npm: 10.7.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.22
    - tauri-build [RUST]: 2.0.0-beta.17
    - wry [RUST]: 0.40.1
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 2.0.0-beta.17
    - @tauri-apps/api [NPM]: 2.0.0-beta.11
    - @tauri-apps/cli [NPM]: 2.0.0-beta.17

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

**Comment by amrbashir** [comment]
I am not sure what you mean by events are propagated to all windows, how are you listening to the drag events?

> there is no data in the event that provides the window from which the event originated.

This could be easily fixed by adding the window label in the drag data

**Comment by jaydevelopsstuff** [comment]
> I am not sure what you mean by events are propagated to all windows, how are you listening to the drag events?

I apologize I should have made this clear before, I'm receiving these events via the Tauri's frontend `listen()` API (which is registered per window in my case). I have not looked into receiving events on the Rust side of things as it's not applicable in my app's case: I need to receive events per-window.

> > there is no data in the event that provides the window from which the event originated.
> 
> This could be easily fixed by adding the window label in the drag data

In terms of the frontend (I can't imagine a case where you would need drag events on the backend) the logical thing would be to only dispatch the event to frontend listeners in the currently focused webview window as after all that is what the user is dragging over (I'm not sure how it would be useful to know about in another window).

The solution you propose would offload that to the developer and be awfully annoying... (imagine having to use `getCurrent()` to check every time the event is received) but I can see it being a good solution if you're processing drag events on the backend for some reason.

**Comment by jaydevelopsstuff** [comment]
Could this be related to #10182?

**Comment by amrbashir** [comment]
> > I am not sure what you mean by events are propagated to all windows, how are you listening to the drag events?
> 
> I apologize I should have made this clear before, I'm receiving these events via the Tauri's frontend `listen()` API (which is registered per window in my case). I have not looked into receiving events on the Rust side of things as it's not applicable in my app's case: I need to receive events per-window.

`listen` by default will listen to any event sent anywhere. if you want to scope it, you will need to do something like this 
```ts
listen("event", () => {}, { target: getCurrent().label })
```
or (which is more concise)
```ts
getCurrent().listen("event", () => {})
```

> > > there is no data in the event that provides the window from which the event originated.
> > 
> > 
> > This could be easily fixed by adding the window label in the drag data
> 
> In terms of the frontend (I can't imagine a case where you would need drag events on the backend) the logical thing would be to only dispatch the event to frontend listeners in the currently focused webview window as after all that is what the user is dragging over (I'm not sure how it would be useful to know about in another window).
> 
> The solution you propose would offload that to the developer and be awfully annoying... (imagine having to use `getCurrent()` to check every time the event is received) but I can see it being a good solution if you're processing drag events on the backend for some reason.

That `label`, will be useful to distinguish events if using `listen` to listen on all events but let's not add it now and wait until someone needs it.

Anyways, you can just do which will be scoped by default and only listen to drag drop events on this window.
```ts
getCurrent().onDragDropEvent(() => {})
```
or the more verbose way:
```ts
listen("tauri://drag", () => {}, { target: getCurrent().label })
```

**Comment by jaydevelopsstuff** [comment]
> Anyways, you can just do which will be scoped by default and only listen to drag drop events on this window.
> 
> ```ts
> getCurrent().onDragDropEvent(() => {})
> ```

This works, but it is no replacement for `tauri://drop-over` as it is not repeatedly called when the user moves their cursor while dragging.

> or the more verbose way:
> 
> ```ts
> listen("tauri://drag", () => {}, { target: getCurrent().label })
> ```

This does not work. I suspect the reason is because all of these `tauri://` drag related events are all global and not targeted to the focused window that would be receiving them.

The Tauri drag and drop APIs have been nothing but a massive pain to work with, a well thought out rework might be a good idea.

**Comment by jaydevelopsstuff** [comment]
> > or the more verbose way:
> > ```ts
> > listen("tauri://drag", () => {}, { target: getCurrent().label })
> > ```
> 
> This does not work. I suspect the reason is because all of these `tauri://` drag related events are all global and not targeted to the focused window that would be receiving them.

After investigating a little bit more, if the current window is/has a webview these events will only be emitted to the webview target, not the window. In this case you must import `getCurrent` from `@tauri-apps/api/webviewWindow`, not `@tauri-apps/api/window`. When v2 goes stable, specific behavior like this should be documented to prevent confusion.

The current `getCurrent` naming schema is quite frustrating (and caused the misunderstanding above) so I opened a feature request requesting a refactor of these: #10193.
