### ISSUE TITLE
[bug] App crashes when I add something to the allowlist and compile it.

### ISSUE THREAD

**Issue by WhiteKSl** [tauri-apps/tauri#10168]
### Describe the bug

When I tried to allow the "dialog" module and then started my application I didn't get any errors while it downloaded and compiled or whatever but then it just crashed after it looked like it loaded normally with no errors returned. I found removing dialog from the allowList was the only way that it would start properly. This applies for any module 

### Reproduction

1. Added whatever module (in this case dialog same issue occured with another module) to the allowList it just has to not have been downloaded yet
2. Run the app
3. Loads like normal then just crashes (the UI doesn't even load for a frame)

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 126.0.2592.81
    ✔ MSVC: Visual Studio Professional 2022
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 22.3.0
    - npm: 10.8.1

[-] Packages
    - tauri [RUST]: 1.6.2
    - tauri-build [RUST]: 1.5.2
    - wry [RUST]: 0.24.8
    - tao [RUST]: 0.16.9
    - tauri-cli [RUST]: 1.5.14
    - @tauri-apps/api [NPM]: 1.5.6 (outdated, latest: 1.6.0)
    - @tauri-apps/cli [NPM]: 1.5.14 (outdated, latest: 1.6.0)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:3000/
    - framework: React
    - bundler: Vite
```

### Additional context

Terminal of when I tried running it 
```
PS E:\Coding\path1\path2> cargo tauri dev
     Running BeforeDevCommand (`npm run dev`)

    > xcel-loader@0.0.0 dev
    > vite
    
    
      VITE v5.3.1  ready in 120 ms
    
      ➜  Local:   http://localhost:3000/
      ➜  Network: use --host to expose
            Info Watching E:\Coding\Thugalicous\Xcel-Loader\src-tauri for changes...
        Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.32s
    ⠙
   PS E:\Coding\path1\path2>  // this is where it crashed 
 ```

**Comment by amrbashir** [comment]
Please provide a minimal reproduction, as I can't seem to be able to reproduce. Also make sure your JS packages are up to date.

**Comment by WhiteKSl** [comment]
So I tried updating JS packages and checked my Crates which didn't change a thing but updating my build.rs to not apply my windows attributes let it load. The new issue is that my app requires elevated permission to function.

Here is my build.rs

```rs
fn main() {
  let mut windows = tauri_build::WindowsAttributes::new();
  let manifest = include_str!("manifest.xml"); 

  windows = windows.app_manifest(
    manifest 
  );
  
  let attrs =  tauri_build::Attributes::new()
    .windows_attributes(windows);
  tauri_build::try_build(attrs).expect("failed to run build script");
}
```

And manifest.xml
```xml
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
    <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
        <security>
            <requestedPrivileges>
                <requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
            </requestedPrivileges>
        </security>
    </trustInfo>
</assembly>
```

Just by tinkering around with it only when I commented out the 
.windows_attributes() line from when I create the attributes fixed it which proves the issue is with either the manifest or how I am creating the attributes (although the manifest was straight from tauri docs)

**Comment by FabianLars** [comment]
Since you mentioned the dialog, it seems like you skipped over the warning here: https://docs.rs/tauri-build/latest/tauri_build/struct.WindowsAttributes.html#warning so your manifest should look more like this
```xml
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
 <dependency>
   <dependentAssembly>
     <assemblyIdentity
       type="win32"
       name="Microsoft.Windows.Common-Controls"
       version="6.0.0.0"
       processorArchitecture="*"
       publicKeyToken="6595b64144ccf1df"
       language="*"
     />
   </dependentAssembly>
 </dependency>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
      </requestedPrivileges>
    </security>
  </trustInfo>
</assembly>
```

If it's not that, then it probably doesn't like that it requires admin in dev mode - maybe try running `tauri dev` in an admin terminal then (not a general recommendation of course - running stuff in admin terminals is pretty _meh_)

**Comment by WhiteKSl** [comment]
> Since you mentioned the dialog, it seems like you skipped over the warning here: https://docs.rs/tauri-build/latest/tauri_build/struct.WindowsAttributes.html#warning so your manifest should look more like this
> 
> ```
> <assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
>  <dependency>
>    <dependentAssembly>
>      <assemblyIdentity
>        type="win32"
>        name="Microsoft.Windows.Common-Controls"
>        version="6.0.0.0"
>        processorArchitecture="*"
>        publicKeyToken="6595b64144ccf1df"
>        language="*"
>      />
>    </dependentAssembly>
>  </dependency>
>   <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
>     <security>
>       <requestedPrivileges>
>         <requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
>       </requestedPrivileges>
>     </security>
>   </trustInfo>
> </assembly>
> ```
> 
> If it's not that, then it probably doesn't like that it requires admin in dev mode - maybe try running `tauri dev` in an admin terminal then (not a general recommendation of course - running stuff in admin terminals is pretty _meh_)

Yeah that seemed to fix it, Thank you!
