### ISSUE TITLE
VSCode Dev Debug

### ISSUE THREAD

**Issue by bRRRITSCOLD** [tauri-apps/tauri#1017]
**Is your feature request related to a problem? Please describe.**
While developing within VSCode I can debug via chrome, but as soon as a tauri JS API function is used (ex: tauri/api/dialog) errors are thrown.

**Describe the solution you'd like**
recipe to attach vscode debugger to running app instance

**Additional context**
Is there a recipe for attaching to the running tauri dev script from npm scripts via vscode debugger?

A section in the documentation for a recipe over this would be awesome if already possible. If it is already there tell me to read closer :)

**Comment by zicklag** [comment]
This would actually be made much easier to do with a Chrome backend for Tauri: #981.

**Comment by lucasfernog** [comment]
This is now documented: https://tauri.app/v1/guides/debugging/application
