### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by cryarchy** [tauri-apps/tauri#10175]
### Describe the bug

Error in tauri-utils when building: function expects 3 arguments, but 2 supplied

When building a project with tauri 2.0.0-beta dependencies, I get an error that suggests that `generate_docs` now requires 3 arguments, but is being called with only 2. This appears to be an incompatibility between the tauri crate and its dependencies.

Cargo.toml dependencies:
tauri = "2.0.0-beta"
tauri-build = "2.0.0-beta"
tauri-plugin = "2.0.0-beta"
tauri-plugin-shell = "2.0.0-beta"

What am I missing?

### Full `tauri info` output

```text
[✔] Environment
    - OS: Linux Mint 21.3.0 X64
    ✔ webkit2gtk-4.1: 2.44.2
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.17.1
    - pnpm: 9.4.0
    - npm: 9.8.1

[-] Packages
    - tauri-cli [RUST]: 2.0.0-beta.21
    - @tauri-apps/api [NPM]: 2.0.0-beta.13
    - @tauri-apps/cli [NPM]: 2.0.0-beta.21

[-] App
```

### Stack trace

```text
error[E0061]: this function takes 3 arguments but 2 arguments were supplied
   --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-plugin-2.0.0-beta.17/src/build/mod.rs:124:7
    |
124 |       acl::build::generate_docs(&permissions, &autogenerated)?;
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^------------------------------ an argument of type `&str` is missing
    |
note: function defined here
   --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-utils-2.0.0-beta.18/src/acl/build.rs:240:8
    |
240 | pub fn generate_docs(
    |        ^^^^^^^^^^^^^
help: provide the argument
    |
124 |       acl::build::generate_docs(&permissions, &autogenerated, /* &str */)?;
    |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

For more information about this error, try `rustc --explain E0061`.
error: could not compile `tauri-plugin` (lib) due to 1 previous error
```

**Comment by FabianLars** [comment]
Can you run `cargo update` in the src-tauri dir and check if that fixes it? We're currently not setting minimum versions internally which can cause issues like these in new releases. We're reworking our CI a bit to handle this better in the future but that will take a bit more time.

**Comment by cryarchy** [comment]
Running `cargo-update` in the src-tauri directory does not solve the issue.

I have also tried deleting the Cargo.lock file and running `cargo tauri build --no-bundle --debug` but I still get the same error.

**Comment by FabianLars** [comment]
Can you try that again? We just published new versions of all plugins and since `tauri-plugin` (used by the plugins) is the issue this may fix it.

**Comment by cryarchy** [comment]
I tried running `cargo update` and still got the same error. To reproduce the bug, I have created a sample project [here](https://github.com/cryarchy/tauri-bug-test). The tauri-plugin-hello project is the project created by running `cargo tauri plugin new hello` with a few dependencies added and minimal code changes to reproduce the bug.

The issue, it seems, arises when authoring plugins. Running `cargo clippy` from the tauri-plugin-hello folder in the repository above fails with the error:

```
error[E0061]: this function takes 3 arguments but 2 arguments were supplied
   --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.22/build.rs:380:5
    |
380 |     tauri_utils::acl::build::generate_docs(&permissions, &docs_out_dir)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^----------------------------- an argument of type `&str` is missing
    |
note: function defined here
   --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-utils-2.0.0-beta.18/src/acl/build.rs:240:8
    |
240 | pub fn generate_docs(
    |        ^^^^^^^^^^^^^
help: provide the argument
    |
380 |     tauri_utils::acl::build::generate_docs(&permissions, &docs_out_dir, /* &str */)
    |                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

For more information about this error, try `rustc --explain E0061`.
error: could not compile `tauri` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by cryarchy** [comment]
I resolved the issue by configuring my dependencies as shown below:

```
tauri = {version = "2.0.0-beta.22"}
tauri-build = "2.0.0-beta.17"
tauri-plugin = "2.0.0-beta.17"
tauri-utils = "2.0.0-beta.17"

[patch.crates-io]
tauri = {git = "https://github.com/tauri-apps/tauri", rev = "tauri-v2.0.0-beta.22"}
tauri-build = {git = "https://github.com/tauri-apps/tauri", rev = "tauri-build-v2.0.0-beta.17"}
tauri-plugin = {git = "https://github.com/tauri-apps/tauri", rev = "tauri-plugin-v2.0.0-beta.17"}
```

**Comment by amrbashir** [comment]
I just tried a fresh project and it works without a problem, make sure to run `cargo update` inside `src-tauri` and if it doesn't work, please make a minimal repro of the project that failed.

**Comment by FabianLars** [comment]
Ahh nevermind, it's tauri-specta's "fault" by locking tauri to beta.22

**Comment by ElianMalessy** [comment]
@FabianLars how do you fix this issue with tauri-specta?

**Comment by FabianLars** [comment]
@ElianMalessy tauri-specta needs to be updated (<https://github.com/oscartbeaumont/tauri-specta/blob/main/Cargo.toml#L31>) or you'll have to stick with beta.22 (and beta.17 for the "inner" crates as shown above).
