### ISSUE TITLE
[bug] CSS randomly applied using Sveltekit + Tauri (v1 and v2)

### ISSUE THREAD

**Issue by ndelobel** [tauri-apps/tauri#10173]
### Describe the bug

When launching tauri in dev mode, some CSS is not applied, and it changes from one launch to another. It seems like the scoped CSS is randomly applied or not.

- launch 1 (css randomly applied)
![Screenshot_20240702_110829](https://github.com/tauri-apps/tauri/assets/119360710/415c84d8-299c-4d6d-b65d-431124677646)

- launch 2 (no code change but everything seem correct this time)
![Screenshot_20240702_104936](https://github.com/tauri-apps/tauri/assets/119360710/8f278569-2473-4635-aa12-1a5414f28d8d)

I cannot reproduce the same issue in browser and the only workaround I find for now is to reload all with ViteJs.
The issue does not happen in build.

### Full `tauri info` output

```text
/usr/bin/npm run tauri dev

> fusion-launcher@0.1.0 tauri
> tauri dev

    Running BeforeDevCommand (`npm run dev`)

> fusion-launcher@0.1.0 dev
> vite dev

Using existing cloned repo
ℹ [paraglide] Compiling Messages into ./src/lib/paraglide                                                                                                                                                                                          

  VITE v5.3.1  ready in 1070 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
    Info Watching /home/nathan/Documents/Projects/fusion-launcher/src-tauri for changes...
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.13s
alternate canonicalPath:  / currentLang:  en localized:  /
```

### Additional context

Tested with webkit2gtk-4.1 on Linux

**Comment by FabianLars** [comment]
> I cannot reproduce the same issue in browser and the only workaround I find for now is to reload all with ViteJs.

Can you test it in epiphany (also known as Gnome Web) too? It's a browser using webkitgtk like tauri. This way we can check whether it's an upstream issue or our fault.

**Comment by ndelobel** [comment]
Sorry to reply so late, I tested in epiphany and the issue is the same. So it's not a tauri issue but a webkitgtk issue.

**Comment by nickheyer** [comment]
Yep, also experiencing this in webkitgtk. I'm hoping there is a workaround. I wish there was any reasonable alternative on linux, webkitgtk has been the worst to work with.

**Comment by thurbridi** [comment]
I'm experiencing the same issue. But, contrary to OP, I do see it on my browser when running `pnpm tauri dev`. If I just run `pnpm dev` the css is always correctly applied.

image 1: `pnpm tauri dev` - css not applied correctly
![Image](https://github.com/user-attachments/assets/e48a2bad-ec7c-4d0d-b594-8f53dac68200)

image 2: `pnpm dev` - css applied correctly
![Image](https://github.com/user-attachments/assets/51cc69af-affb-486e-b6d8-e5b670187f47)
