### ISSUE TITLE
[feat] Distinct names for all the different `getCurrent` functions in the frontend API

### ISSUE THREAD

**Issue by jaydevelopsstuff** [tauri-apps/tauri#10193]
### Describe the problem

Having 3 different `getCurrent()` functions for 3 separate concepts (`window`, `webview`, and `webviewWindow`) with exactly the same function name is very confusing and means using `as` is often a requirement if you're using two at once in the same file.

### Describe the solution you'd like

In my opinion these functions should be refactored like so for the sake of clarity: `getCurrentWindow`, `getCurrentWebview`, and `getCurrentWebviewWindow`. It would certainly improve the DX for me.

**Comment by ahkohd** [comment]
I love this change!
