### ISSUE TITLE
Rust config parsing broken

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#102]
**Describe the bug**
```
  16: tauri::config::get
             at /[redacted]/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-0.1.1/src/config.rs:77
  17: tauri::app::runner::run
             at /[redacted]/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-0.1.1/src/app/runner.rs:11
  18: tauri::app::App::run
             at /[redacted]/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-0.1.1/src/app.rs:12
```

I published a new version based on the work at `feature/env` - but that does not resolve this issue.

**Comment by kastenbutt** [comment]
This might be a naive question, but why is the result of `is_err()` assigned to `tauri_config_dir` in line 77 of config.rs? The following code seems to expect this to be a String, so line 77 should use `unwrap()` (or handle possible errors properly) and not `is_err()`.

This might solve the bug...

**Comment by nothingismagick** [comment]
That might actually be my fault while I was trying to avoid having to add the ENV vars here for crate publishing / mocking - so my fix solved compilation but actually broke the distribution.  :(

**Comment by kastenbutt** [comment]
Also, line 77 is missing the `include_str!` macro.

**Comment by nothingismagick** [comment]
its probably best that you look at the `feature/env` branch btw.

**Comment by lucasfernog** [comment]
This issue is fixed on the `feature/env` branch.

**Comment by nothingismagick** [comment]
The point is that i might have "unfixed" it... :|

**Comment by nothingismagick** [comment]
I am putting your change back @lucasfernog
