### ISSUE TITLE
`bunde_dmg` script fails to remove mounted volume when user installs built app

### ISSUE THREAD

**Issue by tennety** [tauri-apps/tauri#1020]
I'm using a blank issue since I feel like this is more of a dev QOL thing than a bug, but here's the steps to what I encountered:

1. Run `yarn tauri build` in a Tauri app. The app is built successfully.
1. Find the `dmg` and install the app (found in `src-tauri/target/release/bundle/dmg`). This only happens when installing the dmg, not when manually running the built app from the `osx` directory.
1. Run `yarn tauri build` again
1. Build fails with this error (verbose flags added):
```shell
RUST_BACKTRACE=1 yarn tauri build --verbose
yarn run v1.21.1
warning package.json: No license field
$ /Users/chandutennety/projects/personal/tauri-build-test/node_modules/.bin/tauri build --verbose
[tauri]: running build
 app:spawn Running "cargo tauri-bundler --features embedded-server --release --verbose" +0ms

   Compiling test v0.1.0 (/Users/chandutennety/projects/personal/tauri-build-test/src-tauri)
   Compiling tauri-api v0.7.4
   Compiling tauri v0.9.2
    Finished release [optimized] target(s) in 15.05s
    Bundling test_0.1.0_x64.app
    Bundling "/Users/chandutennety/projects/personal/tauri-build-test/src-tauri/target/release/bundle/dmg/test_0.1.0_x64.dmg"
info: running bundle_dmg.sh
Creating disk image...
created: /Users/chandutennety/projects/personal/tauri-build-test/src-tauri/target/release/bundle/osx/rw.test_0.1.0_x64.dmg
Mounting disk image...
Mount directory: /Volumes/test_0.1.0_x64
Device name:     /dev/disk3
making link to Applications dir
Copying volume icon file '../../../../icons/icon.icns'...
error: Shell Scripting Error:`error running bundle_dmg.sh`

 app:spawn Command "cargo" failed with exit code: 1 +0ms

 app:tauri (runner) ⚠️  [FAIL] Cargo CLI has failed +0ms

 app:tauri Shutting down tauri process... +1ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

When I checked the `/Volumes` folder, it looked like this:
```shell
ls -al /Volumes/
total 0
drwxr-xr-x  29 root           wheel  928 Sep 12 23:46 .
drwxr-xr-x  23 root           wheel  736 Aug 28 14:43 ..
lrwxr-xr-x   1 root           wheel    1 Aug 28 16:35 Macintosh HD -> /
drwxr-xr-x@  3 root           wheel   96 Aug 28 14:45 Recovery
drwxr-xr-x@  6 chandutennety  staff  272 Sep 12 23:29 test_0.1.0_x64
drwxr-xr-x   4 chandutennety  staff  204 Sep 12 23:43 test_0.1.0_x64 1
drwxr-xr-x   4 chandutennety  staff  204 Sep 12 23:46 test_0.1.0_x64 2
```
So each volume Tauri was mounting was getting a new directory name, but the app _I installed_ had the target name Tauri was trying to mount, so the `bundle_dmg` script was failing when trying to copy the `icon.icns` file there. Since the script was erroring, it wasn't cleaning up the volume _it_ just created either. When I manually ejected those volumes, the next build succeeded.

What's interesting is that `bundle_dmg` seems to have a fix in place for this exact scenario [here](https://github.com/tauri-apps/tauri/blob/dev/cli/tauri-bundler/src/bundle/templates/dmg/bundle_dmg#L273), but the `if` condition wasn't being satisfied for some reason. I tried adding `echo`s around there, but the script is regenerated for every build so my statements were getting removed.

Huge thanks to @jbolda for talking me through this on the Discord channel, I'm opening this issue per their suggestion.

**Comment by nothingismagick** [comment]
Can you confirm that this is still an issue? If so, please feel free to reopen and we will dive back into it.

**Comment by dibadibadiudiu** [comment]
I had the same problem，I think it is necessary to open up this issue @nothingismagick 
MAC OS M1
bigsur 11.2.3

**Comment by nothingismagick** [comment]
This has been fixed and will be released today. Thanks for your involvement!
