### ISSUE TITLE
[feat] Enable `declarationMap` for API packages

### ISSUE THREAD

**Issue by HuakunShen** [tauri-apps/tauri#10203]
### Describe the problem

Jump to function definition nows navigate to `.d.ts` files with function declarations. 
Sometimes it helps if we can jump to the typescript source code to know the underlying code.

### Describe the solution you'd like

https://www.typescriptlang.org/tsconfig/#declarationMap

Enable `declarationMap` in build process for `@tauri-apps/api` and the plugin apis.

**Comment by amrbashir** [comment]
We don't distribute typescript source code in `@tauri-apps/api` package, only `.js` and `.d.ts` files.

You can Right Click, on the import and choose "Go to Source Definition" instead and it should work.
