### ISSUE TITLE
[bug] [macOS] [Updater]: v1Compatible does not create updater artifacts for macOS

### ISSUE THREAD

**Issue by amblamps** [tauri-apps/tauri#10217]
### Describe the bug

Setting    
 "createUpdaterArtifacts": "v1Compatible",
 does not create v1 compatible updater artifacts or signature files for macOS. Only for Windows.

### Full `tauri info` output

```text
❯ cargo tauri info
[✔] Environment
    - OS: Mac OS 14.4.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.77.2 (25ef9e3d8 2024-04-09)
    ✔ cargo: 1.77.2 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 21.6.1
    - pnpm: 8.15.2
    - npm: 10.2.4
    - bun: 1.0.26

[-] Packages
    - tauri [RUST]: 2.0.0-beta.23
    - tauri-build [RUST]: 2.0.0-beta.18
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 2.0.0-beta.21
    - @tauri-apps/api [NPM]: 2.0.0-beta.14
    - @tauri-apps/cli [NPM]: 2.0.0-beta.21

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Sounds like your tauri cli version is outdated.

Does it really complain about that when you run `cargo tauri info`? It's supposed to run regardless of tauri.conf.json errors :(

Anyway, you can check the cli version with `cargo tauri --version`, just make sure it's `2.0.0-beta.21`

**Comment by amblamps** [comment]
> Sounds like your tauri cli version is outdated.
> 
> Does it really complain about that when you run `cargo tauri info`? It's supposed to run regardless of tauri.conf.json errors :(
> 
> Anyway, you can check the cli version with `cargo tauri --version`, just make sure it's `2.0.0-beta.21`

Ah, thanks for the suggestion

Here's my tauri info.
After updating and running the build again. It's still not generating v1 compatible updater artifacts for macOS.
I also updated tauri-plugin-updater to version 2.0.0-beta.9

```
[✔] Environment
    - OS: Mac OS 14.4.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.77.2 (25ef9e3d8 2024-04-09)
    ✔ cargo: 1.77.2 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 21.6.1
    - pnpm: 8.15.2
    - npm: 10.2.4
    - bun: 1.0.26

[-] Packages
    - tauri [RUST]: 2.0.0-beta.23
    - tauri-build [RUST]: 2.0.0-beta.18
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 2.0.0-beta.21
    - @tauri-apps/api [NPM]: 2.0.0-beta.14
    - @tauri-apps/cli [NPM]: 2.0.0-beta.21

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment]
What's your `bundle.targets` config in tauri.conf.json? It now requires `"app"` in the array (if you don't have it set to `"all"`). We messed up the condition for the warning, but that's fixed for the next release.

**Comment by amblamps** [comment]
> What's your `bundle.targets` config in tauri.conf.json? It now requires `"app"` (we messed up the condition for the warning, but that's fixed for the next release).

Found the issue, I need to change the target to `app` from `dmg`. Thanks!!

**Comment by amblamps** [comment]
> What's your `bundle.targets` config in tauri.conf.json? It now requires `"app"` in the array (if you don't have it set to `"all"`). We messed up the condition for the warning, but that's fixed for the next release.

Saw this warning in my build as soon as I posted my build info reply

<img width="1019" alt="image" src="https://github.com/tauri-apps/tauri/assets/62811682/0db24ec6-780d-49ed-852c-9fd236f84364">

**Comment by FabianLars** [comment]
> Found the issue, I need to change the target to app from dmg. Thanks!!

Btw, you can have both enabled (does not apply to linux/windows). dmg is just a wrapper around the .app bundle so if you install your app via dmg it can be updated with the .app bundle just fine.
