### ISSUE TITLE
[bug] The `minWidth` of the window is invalid.

### ISSUE THREAD

**Issue by GuoJikun** [tauri-apps/tauri#10227]
### Describe the bug

The `minWidth` of the window is invalid.

### Reproduction

1. create a tauri project
2. set `minWidth` in `tauri.config.json`
3. run command `pnpm tauri dev`

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.26100 X64
    ✔ WebView2: 126.0.2592.87
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.15.0
    - pnpm: 9.4.0
    - yarn: 1.22.22
    - npm: 10.7.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.23
    - tauri-build [RUST]: 2.0.0-beta.18
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.14
    - @tauri-apps/cli [NPM]: 2.0.0-beta.21

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

### Additional context

![image](https://github.com/tauri-apps/tauri/assets/21582741/a6da6b55-fbb4-4253-b10a-14c2ad18cf1d)

**Comment by FabianLars** [comment]
Can you check if it works when you add a minHeight too? Maybe we re-introduced https://github.com/tauri-apps/tao/issues/138 at some point 🤔

**Comment by amrbashir** [comment]
Seems like we never adapted tauri APIs to https://github.com/tauri-apps/tao/pull/759

**Comment by GuoJikun** [comment]
> Can you check if it works when you add a minHeight too? Maybe we re-introduced [tauri-apps/tao#138](https://github.com/tauri-apps/tao/issues/138) at some point 🤔

After adding 'minHeight' is normal

**Comment by amrbashir** [comment]
I am working on a PR to fix this, will open tomorrow
