### ISSUE TITLE
[bug] Tauri v2 MacOS: Window Snapping Issue `tauri.conf.json` vs Custom Rust Windows

### ISSUE THREAD

**Issue by tance77** [tauri-apps/tauri#10225]
### Describe the bug

When creating your window in Tauri with the following code :

```rs
fn open_main_window(handle: &App) -> WebviewWindow {
        let main_window = WebviewWindowBuilder::new(handle, "main", WebviewUrl::App("index.html".into()))
            .title("test")
            .resizable(true)
            .fullscreen(false)
            .min_inner_size(650.00, 500.00)
            .decorations(true)
            .inner_size(1280.00, 800.00)
            .build()
            .expect("Error building main window.");

        main_window.open_devtools();
        return main_window;
}
```

When the app starts and the window appears, resizing the window to be taller than it is wide and snapping it to a section of the screen with the developer console taking up most of the height will cause the Webview to move off-screen. The issue persists until the app is terminated in the terminal.

However, this **does not** happen when the window is created in the `tauri.conf.js` file.

## Minimal reproduction repository
https://github.com/tance77/tauri-v2-mac-os-snap-bug

I also think this issue is related as well 

https://github.com/tauri-apps/tauri/issues/6927

## Demo Video

https://github.com/tauri-apps/tauri/assets/3421501/585a9736-193b-476a-a668-ad0b1e1ac347

### Full `tauri info` output

```text
- OS: Mac OS 14.5.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.10.0
    - pnpm: 8.10.2
    - npm: 10.2.3
    - bun: 1.0.11

[-] Packages
    - tauri [RUST]: 2.0.0-beta.14
    - tauri-build [RUST]: 2.0.0-beta.11
    - wry [RUST]: 0.39.0
    - tao [RUST]: 0.27.0
    - tauri-cli [RUST]: 1.2.3
    - @tauri-apps/api [NPM]: 2.0.0-beta.7
    - @tauri-apps/cli [NPM]: 2.0.0-beta.12

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by pewsheen** [comment]
Hi! I am able to fix the issue by setting `window_builder.title_bar_style(tauri::TitleBarStyle::Visible).build()`. Could you try this one with your `WebviewWindowBuilder`?

If this works, maybe we should set the value by default.

**Comment by tance77** [comment]
@pewsheen Yeah, that does seem to fix it. Why does that fix it? What does setting the title bar style to be visible do?

**Comment by pewsheen** [comment]
I don't actually know what happened 👀 . I found that's the difference when creating the window by config. It sometimes depends on how the OS manages the underlying logic, and it's usually a black box.
