### ISSUE TITLE
Unable to restrict `allowlist` because of missing features in Rust

### ISSUE THREAD

**Issue by crapStone** [tauri-apps/tauri#1023]
**Describe the bug**
I want to use the [Bridge-Pattern](https://tauri.studio/en/docs/guides/patterns/bridge) with a few more options enabled.

I enabled all options i wanted by reading the [documentation](https://tauri.studio/en/docs/api/config#tauri.allowlist):

```json
"allowlist": {
    "all": false,
    "event": true,
    "open": true,
    "openDialog": true
}
```

When i tried to use the [http](https://tauri.studio/en/docs/api/js#http) module from tauri this error was printed:

```
[ERROR] "httpRequest' not on the allowlist (https://tauri.studio/docs/api/config#tauri.allowlist)"
```

This option isn't in the docs but  tried anyway and now cargo printed the following error:

```
error: failed to select a version for `tauri`.
    ... required by package `<application_name> v0.1.0 (<application_path>/src-tauri)`
versions that meet the requirements `=0.9.2` are: 0.9.2

the package `<application_name>` depends on `tauri`, with features: `http-request` but `tauri` does not have these features.


failed to select a version for `tauri` which could resolve this conflict
```

**To Reproduce**
1. Go to `src-tauri/tauri.conf.json`
2. Add `"httpRequest": true,` to `tauri:allowlist`
3. Use for example:  
  ```ts
  import http from 'tauri/api/http'
  http.get('https://google.com')
  ```
4. Start tauri application
5. Look at the output of `tauri dev`

**Expected behavior**
When I add the `httpRequest` option to the allow list I want the application to compile and the ability to use the [`http`](https://tauri.studio/en/docs/api/js#http) module from JavaScript.

**Platform and Versions:**
OS: Linux(5.8.10-arch1-1) - linux/x64
Node: 14.11.0
NPM: 6.14.7
Yarn: 1.22.5
Rustc: 1.46.0

**Comment by u12206050** [comment]
Have you tried with `tiny_http`?

**Comment by crapStone** [comment]
I want to make requests in JavaScript with the builtin http api from tauri.

**Comment by lucasfernog** [comment]
I'll fix this tonight. For now you could use all: true
