### ISSUE TITLE
[bug] Plugin function not found, cannot call nsis_tauri_utils::download

### ISSUE THREAD

**Issue by khang3052002** [tauri-apps/tauri#10238]
### Describe the bug

Hi everyone, I have issue when build cross-platform. A few hours ago, it was able to build successfully, but now when trying again it has problems 

` Finished release profile [optimized] target(s) in 58.39s
        Warn Cross-platform compilation is experimental and does not support all features. Please use a matching host system for full compatibility.
        Warn ignoring msi
        Info Target: x64
        Info Code signing is currently only supported on Windows hosts, skipping...
     Running makensis.exe to produce 
path/Desktop App_0.1.0_x64-setup.exe
Plugin function not found, cannot call nsis_tauri_utils::download
Error in script "path/src-tauri/target/x86_64-pc-windows-msvc/release/nsis/x64/installer.nsi" on line 447 -- aborting creation process
       Error failed to bundle project: No such file or directory (os error 2)```

### Expected behavior

Build successfull

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.5.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.14.0
    - npm: 10.7.0

[-] Packages
    - tauri [RUST]: 1.6.8
    - tauri-build [RUST]: 1.5.2
    - wry [RUST]: 0.24.10
    - tao [RUST]: 0.16.9
    - @tauri-apps/api [NPM]: 1.5.1 (outdated, latest: 1.6.0)
    - @tauri-apps/cli [NPM]: 1.5.6 (outdated, latest: 1.6.0)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist/desktop-app
    - devPath: http://j317webapp.com:9000/
    - framework: Angular
    - bundler: Webpack
```

**Comment by amrbashir** [comment]
can you update the cli version to latest and try again?

**Comment by khang3052002** [comment]
Yes sir, it's working well after upgrade tauri-cli version

**Comment by ithustle** [comment]
@khang3052002, could you share your tauri.config.json, please?
