### ISSUE TITLE
[docs]  Will the Tauri2 compatible with the APIs of Tauri1?

### ISSUE THREAD

**Issue by gaomingzhao666** [tauri-apps/tauri#10239]
Hey Tauri team, how's going?

I am preparing to use Tauri to build my desktop application, and I found that Tauri2.0 is on the way already 2 years, it's probably will be release in 2024, right? So I am scared that something like compatibility, would you explain to me about deprecating features or APIs?

And I want to know, will Tauri2.0 have more performance than Tauri1.0? such as less bundle size or memory use.

I so appreciate the contribution to this open-source world by the Tauri team, thanks.

**Comment by FabianLars** [comment]
> it's probably will be release in 2024, right?

that's the plan yes

> would you explain to me about deprecating features or APIs?

https://v2.tauri.app/start/migrate/from-tauri-1/

At this point we typically recommend trying to start with v2 directly.

> And I want to know, will Tauri2.0 have more performance than Tauri1.0? such as less bundle size or memory use.

The only notable change here would be improved IPC performance, so communicating between js and rust will be faster (this includes all of tauri's prebuilt js apis). bundle size / memory use / general performance should be more or less the same.
