### ISSUE TITLE
[feat] Official wasm-bindgen bindings

### ISSUE THREAD

**Issue by osenvosem** [tauri-apps/tauri#10245]
### Describe the problem

Hello and thank you for your great work.

It would be incredibly useful if the Tauri team provided users with official wasm-bindgen bindings in order to have opportunity to write frontend part in Rust using frameworks like Leptos, Dioxus, etc...

### Describe the solution you'd like

Implementation of wasm-bindgen bindings for Tauri API.

### Alternatives considered

There are a couple of projects, [one is incomplete bindings for v1 ](https://github.com/JonasKruckenberg/tauri-sys) and the second is [**very** incomplete project for v2](https://github.com/bicarlsen/tauri-sys)

### Additional context

I'm currently writing cross-platform app with Tauri v2 and Leptos and the absent of the bindings really complicates the development process.

**Comment by FabianLars** [comment]
Thanks for the request! We already had one here though https://github.com/tauri-apps/tauri/issues/5354 so i'm closing this as a dupe :)
