### ISSUE TITLE
Android integrating with existing Desktop app isn't working

### ISSUE THREAD

**Issue by mohammadmansour200** [tauri-apps/tauri#10243]
### Describe the bug

So I finished all the prerequisites for running the app on Android, but when i run either 
```shell
npm run tauri android dev // returns nothing at all!!
```
```shell
npm run tauri android build
```
this returns:
> error: no library targets found in package `basset`
    Error `Failed to run `cargo build`: command ["cargo", "build", "--package", "basset", "--manifest-path", "/home/mohammad/Documents/basset/src-tauri/Cargo.toml", "--target", "aarch64-linux-android", "--features", "tauri/custom-protocol tauri/rustls-tls", "--lib", "--release"] exited with code 101

how can this be fixed?

### Expected behavior

just clone this repo: https://github.com/mohammadmansour200/basset
then run either 
`npm run tauri android dev`
or 
`npm run tauri android build`

### Full `tauri info` output

```text
[✔] Environment
    - OS: Ubuntu 24.04 X64
    ✔ webkit2gtk-4.1: 2.44.2
    ✔ rsvg2: 2.58.0
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 18.19.1
    - npm: 9.2.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.22
    - tauri-build [RUST]: 2.0.0-beta.17
    - wry [RUST]: 0.40.1
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.14
    - @tauri-apps/cli [NPM]: 2.0.0-beta.21

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Rollup
```

**Comment by FabianLars** [comment]
Enabling mobile support requires more than setting up your sytstem, check out this part <https://v2.tauri.app/start/migrate/from-tauri-1/#preparing-for-mobile> (should still apply, don't get confused by the "migrate from v1" stuff.

**Comment by mohammadmansour200** [comment]
@FabianLars 
I'm unsure if this is correct or not:
here is the lib.rs file:
```rust
// Learn more about Tauri commands at https://tauri.app/v1/guides/features/command
#[tauri::command]
fn greet(name: &str) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_fs::init())
        .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```
here is the main file:
```rust 
// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

fn main() {
    app_lib::run();
}
```

and to make it clear I am not that good in Rust, but tried my best to do what was stated here as you requested:
https://v2.tauri.app/start/migrate/from-tauri-1/

**Comment by FabianLars** [comment]
That looks correct to me. Does it still not work?

If not, did you also did the Cargo.toml changes?

**Comment by mohammadmansour200** [comment]
Yes, it works now
