### ISSUE TITLE
macos里想用chorme的内核，或者webkit的内核，不想用safri的内核有办法吗 真的很着急！watchout

### ISSUE THREAD

**Issue by bianbiandashen** [tauri-apps/tauri#10241]
### Describe the bug

macos里想用chorme的内核，或者webkit的内核，不想用safri的内核有办法吗 真的很着急！watchout

### Full `tauri info` output

```text
macos里想用chorme的内核，或者webkit的内核，不想用safri的内核有办法吗 真的很着急！watchout
```

**Comment by FabianLars** [comment]
Currently not possible. We do have plans to work on something for v3 or v4, see https://github.com/tauri-apps/tauri/issues/14963#issuecomment-2094904381
