### ISSUE TITLE
[bug] @tauri-apps/cli v2.0.0-beta.21 doesn't generate a signature (.sig) file

### ISSUE THREAD

**Issue by cs50victor** [tauri-apps/tauri#10240]
### Describe the bug

The tauri cli doesn't generate an updater signature file when trying to bundle an app. It works for `v2.0.0-beta.20` but not `v2.0.0-beta.21`. If a user installs "@tauri-apps/cli" using a caret i.e `@tauri-apps/cli@^v2.0.0-beta`. CI breaks and it's hard to debug

### Full `tauri info` output

```text

[✔] Environment
    - OS: Mac OS 14.6.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.81.0-nightly (6be96e386 2024-07-09)
    ✔ cargo: 1.81.0-nightly (154fdac39 2024-07-07)
    ✔ rustup: 1.27.1 (2024-04-24)
    ✔ Rust toolchain: nightly-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.10.0
    - pnpm: 9.5.0
    - yarn: 1.22.22
    - npm: 10.2.3
    - bun: 1.1.18

[-] Packages
    - tauri [RUST]: 2.0.0-beta.23
    - tauri-build [RUST]: 2.0.0-beta.18
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 2.0.0-beta.21
    - @tauri-apps/api [NPM]: 2.0.0-beta.14
    - @tauri-apps/cli [NPM]: 2.0.0-beta.21

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Rollup
```

**Comment by FabianLars** [comment]
You now have to enable `bundle.createUpdaterArtifacts` in tauri.conf.json. Setting it to `true` will generate .sig files for the installers/bundles directly. Setting it to `"v1Compatible"` will produce .zip and .zip.sig files (i assume that's what you need).
