### ISSUE TITLE
Javascript API: FileSystem operations over a FileDescriptor

### ISSUE THREAD

**Issue by tinchoz49** [tauri-apps/tauri#1025]
**Is your feature request related to a problem? Please describe.**
It could be nice to have an API to work with FileDescriptors like in Node.js. 

Just the principal operations: 

`fs.open(path, { flags, mode })`
`fs.read(fd, buffer, { offset, length, position })`
`fs.write(fd, buffer, { offset, length, position })`
`fs.close(fd)`

With this API we can create performant ways to operate with random data inside a file.

**Comment by lucasfernog** [comment]
We could use https://docs.rs/filedescriptor/0.8.0/filedescriptor/ here.

**Comment by amrbashir** [comment]
closing in favor of #2233
