### ISSUE TITLE
[bug] Can't run tauri app without display

### ISSUE THREAD

**Issue by thewh1teagle** [tauri-apps/tauri#10251]
### Describe the bug

I created the app [vibe](https://github.com/thewh1teagle/vibe) which provides GUI and CLI methods to run the app.
When running it on a Server without display server, it failed although I don't create any window, just start the CLI.

The error message is

```console
(vibe:2960): Gtk-WARNING **: 12:03:05.776: cannot open display:
```

Here is the source code and speficially [`setup.rs`](https://github.com/thewh1teagle/vibe/blob/main/desktop/src-tauri/src/setup.rs#L57)

### Reproduction

Download the app vibe from https://thewh1teagle.github.com/vibe to debian machine without display, install, run `vibe --help`

### Expected behavior

It should run. it's only cli

### Full `tauri info` output

```text
I don't have it, it's on production (though it will be nice to have the same function to fetch in prod)
[src-tauri/Cargo.toml](https://github.com/thewh1teagle/vibe/blob/main/desktop/src-tauri/Cargo.toml)
```

### Additional context

Related: https://github.com/thewh1teagle/vibe/issues/169

**Comment by FabianLars** [comment]
Did a tiny bit of research and it looks like gtk won't allow us to prevent that on our side 🤔 The only workarounds i found were user side like running a fake x server like Xvfb :/

Would it be possible to refactor your app to make the cli stuff all hapen before the tauri::Builder line?

**Comment by thewh1teagle** [comment]
> Would it be possible to refactor your app to make the cli stuff all hapen before the tauri::Builder line?

Yes, though I use command functions directly so it will require some work. is it a limit in wry?

**Comment by FabianLars** [comment]
No it's a limitation in gtk itself.
