### ISSUE TITLE
Webview/Frontend works, but Tauri's apis aren't on Android 

### ISSUE THREAD

**Issue by mohammadmansour200** [tauri-apps/tauri#10260]
### Describe the bug

So, basically what is happening is that the frontend is working, but there is no backend at all so I cant get the app version, open file dialog and many other API that are supposed to be working on Desktop version, Desktop version works like a charm, problem only happens on the Android version.

### Reproduction

here is my app's repo:
https://github.com/mohammadmansour200/basset

BTW, I am not using the emulator of Android studio because I find it to be laggy and instead I connected my Mobile and I am using it instead in Android studio

### Full `tauri info` output

```text
[✔] Environment
    - OS: Fedora 40.0.0 X64
    ✔ webkit2gtk-4.1: 2.44.1
    ✔ rsvg2: 2.57.1
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 20.12.2
    - npm: 10.8.1

[-] Packages
    - tauri [RUST]: 2.0.0-beta.22
    - tauri-build [RUST]: 2.0.0-beta.17
    - wry [RUST]: 0.40.1
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 1.5.14
    - @tauri-apps/api [NPM]: 2.0.0-beta.13
    - @tauri-apps/cli [NPM]: 2.0.0-beta.20

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Rollup
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by JonasKruckenberg** [comment]
What you are experiencing is the fact that many APIs are not yet supported on mobile. This is due to the fact that mobile platforms work quite differently under the hood than the desktop OSes we've targeted so far, which means implementation effort is non trivial.

**Comment by mohammadmansour200** [comment]
Can you give me a list for those unsupported APIs?
I just need those APIs:
- shell
- dialog
- filesystem
- path
are those still not supported?
BTW, I forgot to update that when I built the app for android some of those APIs worked

**Comment by mohammadmansour200** [comment]
+ how can I open devtools within the Android app like React-native and EXPO does?

**Comment by mohammadmansour200** [comment]
Update: I don't know how but suddenly APIs are working now
