### ISSUE TITLE
[bug] virustotal found 4 suspected vulnerabilities on fresh build on Windows

### ISSUE THREAD

**Issue by Razzwan** [tauri-apps/tauri#10284]
### Describe the bug

Following the documentation, I created a fresh .exe installer for Windows and [checked it on the website https://www.virustotal.com](https://www.virustotal.com/gui/file/f817dba58bcfcbbac46c0370f587a9b31f2960b5e4e6c9b7caa32639e140317d?nocache=1).  The `virustotal` found 4 suspected vulnerabilities. This looks quite strange since I haven't added any additional packages yet

### Reproduction

1. Following [this guide](https://tauri.app/v1/guides/building/cross-platform#experimental-build-windows-apps-on-linux-and-macos)
2. I checked it on `virustotal`

### Expected behavior

No vulnerabilities

### Full `tauri info` output

```text
[✔] Environment
     - OS: Debian 12.0.0 X64
     ✔ webkit2gtk-4.0: 2.44.2
     ✔ rsvg2: 2.54.7
     ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
     ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
     ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
     ✔ Rust toolchain: 1.79.0-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
     - node: 18.19.0
     - npm: 9.2.0
 
 [-] Packages
     - tauri [RUST]: 1 (no lockfile)
     - tauri-build [RUST]: no manifest (no lockfile)
     - wry [RUST]: no manifest (no lockfile)
     - tao [RUST]: no manifest (no lockfile)
     - tauri-cli [RUST]: 1.6.0
     - @tauri-apps/api : not installed!
     - @tauri-apps/cli [NPM]: 1.6.0
 
 [-] App
     - build-type: bundle
     - CSP: unset
     - distDir: ../src
     - devPath: ../src
```

### Additional context

Ok, You can say, that this is experimental features, but I created a new build using Windows OS and got a similar result - 

[installer report](https://www.virustotal.com/gui/file/c22ad3cac67cd4b26c2533252487a433cf1aa7f0b6fe4667ba5b06041b915dbb?nocache=1)
[installed app report](https://www.virustotal.com/gui/file/bc2bfe4a05629fb0059c23e9ff4513b91d4b093ba65ccbbe63abe00ae5c94c48?nocache=1)

**Comment by FabianLars** [comment]
Thanks for the report! We track false positives here https://github.com/tauri-apps/tauri/issues/2486 and on discord https://discord.com/channels/616186924390023171/1142423001002954854 (it says windows defender but really, it's for all)
