### ISSUE TITLE
[bug] [macos] [windows] [tauri v2] Failed to load resource: the server responded with a status of 400 (Bad Request) ipc://localhost/greet

### ISSUE THREAD

**Issue by rtmotiondev** [tauri-apps/tauri#10286]
### Describe the bug

Returning an error from a tauri command shows the following error in the console. Everything works but the message is strange. Is this expected behavior in tauri v2? 

```
Failed to load resource: the server responded with a status of 400 (Bad Request) ipc://localhost/greet
```

### Reproduction

sh <(curl https://create.tauri.app/sh) --beta

info: downloading create-tauri-app
✔ Project name · tauri-v2-bug
✔ Choose which language to use for your frontend · TypeScript / JavaScript - (pnpm, yarn, npm, bun)
✔ Choose your package manager · npm
✔ Choose your UI template · Vanilla
✔ Choose your UI flavor · TypeScript
✔ Would you like to setup the project for mobile as well? · yes

cd tauri-v2-bug
npm install

Modify greet command to return an error
```
#[tauri::command]
fn greet(name: &str) -> Result<String, String> {
    Err("Hello world!".into())
    //format!("Hello, {}! You've been greeted from Rust!", name)
}
```

Modify main.ts
```
window.addEventListener("DOMContentLoaded", () => {

  invoke("greet", {
    name: "hello",
  }).then(r => {
    console.log(r);
  }).catch(e => {
    console.log(e);
  });
});
```

npm run tauri dev

<img width="807" alt="Screenshot 2024-07-15 at 4 11 30 PM" src="https://github.com/user-attachments/assets/92ddba35-1e81-452f-9159-73a7dbb947a0">

### Expected behavior

No error message or at least something a bit more clear.

### Full `tauri info` output

```text
> tauri-v2-bug@0.0.0 tauri
> tauri info


[✔] Environment
    - OS: Mac OS 14.5.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.11.0
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.24
    - tauri-build [RUST]: 2.0.0-beta.19
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.15
    - @tauri-apps/cli [NPM]: 2.0.0-beta.22

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - bundler: Vite
```

**Comment by hermantolim** [comment]
also on windows os
![image](https://github.com/user-attachments/assets/16518af6-f68b-4f38-9ddc-26fd33c01007)

```js
{
    "eol": "\r\n",
    "os_type": "windows",
    "platform": "windows",
    "family": "windows",
    "version": "10.0.22631",
    "arch": "x86_64",
    "exe_extension": "exe"
}
```

```toml
[dependencies]
tauri = { version = "2.0.0-beta.24", features = [] }
tauri-plugin-shell = { version = "2.0.0-beta.9"}
tauri-plugin-os = { version = "2.0.0-beta.8" }
```

**Comment by dygy** [comment]
having the same issue after migration of the project from webpack to vite (project was previously migrated from v1 to v2, but had no issue with IPC, only after switching to vite IPC got down.

**Comment by dygy** [comment]
by removing "target" dir, "gen" dir, and stop using vite --force I was able to fix issue for myself

**Comment by rtmotiondev** [comment]
@tweidinger Was this fixed?

**Comment by FabianLars** [comment]
Oh, we mixed it up with dygy's comments and thought it's resolved. But yes, please try again in the rc versions.

We still need to improve the errors somehow but `400` should typically mean that it's missing capability permissions or has missing command args.

**Comment by rtmotiondev** [comment]
It still happens in the latest releases. You guys can easily test it out by creating a new app with [create-tauri-app](https://v2.tauri.app/start/create-project/#using-create-tauri-app). It's easy to replicate. Both in macOS and Windows and possibly in Linux too.

@FabianLars Can you add the labels back and reopen the ticket?

What capability could be missing? This is the capabilities from the greet app.

{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "default",
  "description": "Capability for the main window",
  "windows": ["main"],
  "permissions": [
    "core:path:default",
    "core:event:default",
    "core:window:default",
    "core:app:default",
    "core:image:default",
    "core:resources:default",
    "core:menu:default",
    "core:tray:default",
    "shell:allow-open"
  ]
}

**Comment by FabianLars** [comment]
Wait, i'm so sorry, i confused your issue with something else. I was looking for the issue where returning Errors is broken literally _everywhere_ and it was this one... Good thing i'll be on vacation the next few weeks, i'm really not on my game lately...

**Comment by dygy** [comment]
> Oh, we mixed it up with dygy's comments and thought it's resolved. But yes, please try again in the rc versions.
> 
> We still need to improve the errors somehow but `400` should typically mean that it's missing capability permissions or has missing command args.

i had it fixed for a few moments and now it's back. I tried to delete targets, creating new apps, creating new commands with different code, and other stuff, but it's not let me solve. I feel it could be some very very weird cache, but have zero understanding where I could clean it. Somehow once I was able, now I'm stuck on it again
<img width="1288" alt="Screenshot 2024-08-12 at 14 38 58" src="https://github.com/user-attachments/assets/88c1ed94-dae0-4970-88b9-1ecf05704125">

**Comment by dygy** [comment]
the problem of this permission error that most errors like those says "you need to enable foo:bar-foo", this one contains "" instead of name. I tried to pass "" to permission lists but it didn't helped :D

**Comment by dygy** [comment]
@lucasfernog are you sure we have to close the issue now? it seems your work will help people see better error descriptions, however it does not mean that there is no more error on tauri side, we just need to log our errors

**Comment by lucasfernog** [comment]
unless i missed something this issue isn't about errors on the tauri side, it's about the error output when a command returns an error, so the issue is resolved
