### ISSUE TITLE
[bug] Signature decoding error: Encoded text cannot have a 6-bit remainder

### ISSUE THREAD

**Issue by ankitvermaAT** [tauri-apps/tauri#10296]
### Describe the bug

My updater doesn't work. I generated keys as it was shown in [the updater guide](https://tauri.app/v1/guides/distribution/updater/#signing-updates), 
but instead on release builds it just gets stuck on installUpdate() phase and when I try to reproduce the issue in debug builds by reducing the version in tauri.conf.json I get this error in js console:
![image](https://github.com/user-attachments/assets/bc029570-93d1-46f4-b1d1-1659a09b3a37)

And please correct my steps if required,  how to generate public and private key and how to use for updater I am follow below steps...
1. run command: npm run tauri signer generate
2. after output put public key in tauri.config.json and private key put on environment variable
3. create build using command: npm run tauri build
4. upload .msi.zip and .msi.zip.sig on endpoint path
5. those file getting from path: src-tauri/target/release/bundle/msi/
6. from old version project run command: npm run tauri dev
7. Got the above error.

### Reproduction

Create new keypair
Use them in the updater

### Expected behavior

Updater works

### Full `tauri info` output

```text
Environment
› OS: Windows 10.0.22622 X64
› Webview2: 105.0.1343.27
› MSVC:
- Visual Studio Community 2022
- Visual Studio Build Tools 2019
› Node.js: 16.17.0
› npm: 8.16.0
› pnpm: 7.11.0
› yarn: Not installed!
› rustup: 1.25.1
› rustc: 1.63.0
› cargo: 1.63.0
› Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
› @tauri-apps/cli [NPM]: 1.0.5
› @tauri-apps/api [NPM]: 1.0.2
› tauri [RUST]: 1.0.5,
› tauri-build [RUST]: 1.0.4,
› tao [RUST]: 0.12.2,
› wry [RUST]: 0.19.0,

App
› build-type: bundle
› CSP: unset
› distDir: ../dist
› devPath: http://localhost:1420/
› framework: React

App directory structure
├─ .git
├─ .github
├─ .tauri
├─ .vscode
├─ dist
├─ node_modules
├─ public
├─ src
└─ src-tauri
```

**Comment by FabianLars** [comment]
I don't like the wording in step 4:
> upload .msi.zip and .msi.zip.sig on endpoint path

Generally you do not upload the .sig file as-is but instead open it, and copy the string inside into the json your server responds with. Of course, if your server reads that file content itself and builds the json response then, that would be fine too.

Do you have an example response of your server that's behind the configured endpoint?

**Comment by ankitvermaAT** [comment]
endpoint path json format retrun below:
{
  "version": "1.0.2",
  "url": "https://domain/windows/x86_64/1.0.1/myapp_1.0.2_x64_en-US.msi.zip",
  "signature": "https://domain/windows/x86_64/1.0.1/myapp_1.0.2_x64_en-US.msi.zip.sig"
}


-------------------
tauri.config.json:

"updater": {
"active": true,
"endpoints": [
"https://domain/windows/x86_64/1.0.1"
],
"dialog": true,
"pubkey": "dW50cnoil098IGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IDE4MzIxRjY0RUY5NjAzNTEKUldSUkE1YnZaQjh5R0J5ZmoxZVBhRyt2RjZtSlF2TG5XalhKQXpMcm5nZmEzcllLZnN3S879huyK",
"windows": {
"installMode": "passive"
}
}

**Comment by FabianLars** [comment]
Yeah, that's exactly the issue i and the others in the other github issues were talking about

The `"signature"` field **cannot** be a URL, it **must** be whatever is _inside_ the .sig file, see this file for reference https://github.com/simonhyll/tauri-by-simon/releases/latest/download/latest.json

**Comment by ankitvermaAT** [comment]
Thanks a lot @FabianLars , I am not to got that point from last 2 day's, Thanks again.

Could you please help me now I am getting the error: Verify signature error: UnexpectedKeyId

**Comment by FabianLars** [comment]
The last time(s) this was reported it meant that there was a mismatch between the private and public key. For example in one case the public key was old, and the private key was re-generated via `signer generate`.

To make sure that's not the case you can generate new keys, update the pubkey, update the private key env var, build your app again and replace the `signature` field with the new .sig file contents.

And just to be sure: The .sig file changes every time you build your app.

**Comment by ankitvermaAT** [comment]
@FabianLars I just follow below steps:
1. run : npm run tauri signer generate
  Got public and private keys
2. Put public key in tauri.config.json (pubkey) node
3. Put private key in env file
4. run : npm run tauri build
  Got update build (myapp_1.0.2_x64_en-US.msi.zip) and .mis.zip.sig files
5. Upload .mis.zip on server and update signature value in server json which is inside (.mis.zip.sig) file (As you suggested 👍 )
6. Now I have my old version build i.e. 1.0.1 run this app and got that error (Verify signature error: UnexpectedKeyId)
Now please suggest where I had done mistake in the process..

**Comment by FabianLars** [comment]
> Put private key in env file

The tauri cli does not read .env files, it must be a proper environment variable. Maybe you set up an env var before but now only updated an .env file?

**Comment by ankitvermaAT** [comment]
No I don't have any .env file.

I had removed **old system environment variables** and create new with updated input still the same error:
Verify signature error: UnexpectedKeyId

Variables name are below:
TAURI_PRIVATE_KEY
TAURI_KEY_PASSWORD

Is there any other way to debug that issue.

**Comment by FabianLars** [comment]
> Is there any other way to debug that issue.

Hmm, can't think of anything right now. One thing i just noticed is that your tauri packages are really old and it may be a bug we fixed since then 🤔 Your versions are 2 years old so i really can't remember anymore.

Maybe try a new `create-tauri-app` project and see if that works okay (if you can't upgrade your own app right now)

**Comment by ankitvermaAT** [comment]
I had used below packages:

"dependencies": {
    "@tauri-apps/api": "^1.5.2",
    "axios": "^1.6.7",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.22.1"
  },
  "devDependencies": {
    "@tauri-apps/cli": "^1.5.8",
    "@types/react": "^18.2.15",
    "@types/react-dom": "^18.2.7",
    "@vitejs/plugin-react": "^4.2.1",
    "typescript": "^5.0.2",
    "vite": "^5.0.0"
  }

**Comment by ankitvermaAT** [comment]
open new ticket : https://github.com/tauri-apps/tauri/issues/10316
