### ISSUE TITLE
Please add support/doc configuration for Vuetify 3.x

### ISSUE THREAD

**Issue by rgutierrez2004** [tauri-apps/tauri#10304]
### Describe the problem

Vuetify is probably the best frontend metaframework available in the market and I can't believe that Tauri creators hasn't added a config doc or official support for this tool yet, we can see support for new frameworrks like Nuxt, Svelkit but the big one Vuetify is mssing.

### Describe the solution you'd like

Please update the doc and add official support for Vuetify, so developers can create professional looking thick/desktop clients with Tauri.

**Comment by amrbashir** [comment]
Vuetify itself is not a frameowrk, it is a UI component for Vue so we don't need to have specific documentation for it. However, Tauri works with virtually any frontend framework configuration you might be using so you can just create your vuetify app as you normally do, then integrate tauri into it by:
1. adding the `@tauri-apps/cli` package as dev dependency
2. run `npm run tauri init` and answer the questions

More info can be found here https://tauri.app/v1/guides/getting-started/setup/integrate
