### ISSUE TITLE
[bug] [macos] Redraw when window background color is transparent

### ISSUE THREAD

**Issue by sdr0x07b6** [tauri-apps/tauri#10306]
### Describe the bug

I am trying to create an application for macOS using Tauri v1.
I set `tauri.windows.decorations` to `false` and give the whole window container `data-tauri-drag-region`.

https://github.com/user-attachments/assets/c2cbe15f-6149-468d-96cf-2124543a6f4d

The video shows a transparent PNG of the Tauri logo in this window. Then, the slider changes the CSS `transform: rotate` value in real time.

When the image is rotated, a “trace” is left where the non-transparent area originally was. Resizing the window will remove the traces, but if the image is rotated again, the traces will remain again.
In addition, the UI is displayed only when the mouse cursor is hovering over the window. When the cursor is moved away from the window, the UI is hidden, but a “trace” remains where the UI was at that time.

In the video, the window is translucent to make it easier to see.
If the window is made non-transparent, this phenomenon will not occur.
If you make it translucent or completely transparent, it will occur.
Also, even when fully transparent, the window is sometimes a light gray color, and when the window is resized, it becomes fully transparent.

Overall,
There seems to be a problem with redrawing when the background color of the window is transparent. Resizing the window resets it once, but when a subsequent redraw occurs, the “trace” problem returns.
Is this a bug?

### Full `tauri info` output

```text
% yarn tauri info
yarn run v1.22.22
$ tauri info

[✔] Environment
    - OS: Mac OS 14.5.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.26.0 (2023-04-05)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 20.12.1
    - pnpm: 9.4.0
    - yarn: 1.22.22
    - npm: 10.5.0


[-] Packages
    - tauri [RUST]: 1.6.7
    - tauri-build [RUST]: 1.5.2
    - wry [RUST]: 0.24.10
    - tao [RUST]: 0.16.9
    - @tauri-apps/api [NPM]: 1.6.0
    - @tauri-apps/cli [NPM]: 1.6.0

[-] App
    - build-type: bundle
    - CSP: default-src 'self' asset: data:; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline';
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
✨  Done in 6.67s.
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by FabianLars** [comment]
Thanks for the report! This issue is tracked collectively here: https://github.com/tauri-apps/tauri/issues/4243
