### ISSUE TITLE
[bug] When set `"transparent": true` on Windows 11, the background with the initial size will be white.

### ISSUE THREAD

**Issue by CakeAL** [tauri-apps/tauri#10318]
### Describe the bug

When set `"transparent": true`, the background with the initial size will be white.
And manually resize the window, the redraw part of the window will be transparent.
- the pard word should be part
![QQ_1721315427808](https://github.com/user-attachments/assets/59868547-326b-4fc6-bde9-4177d0c58377)

### Reproduction

set `"transparent": true`

### Expected behavior

The initial part window should be transparent.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 126.0.2592.102
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.12.0
    - pnpm: 9.1.1
    - npm: 10.5.0

[-] Packages
    - tauri [RUST]: 1.7.1
    - tauri-build [RUST]: 1.5.3
    - wry [RUST]: 0.24.10
    - tao [RUST]: 0.16.9
    - tauri-cli [RUST]: 1.5.14
    - @tauri-apps/api [NPM]: 1.5.6 (outdated, latest: 1.6.0)
    - @tauri-apps/cli [NPM]: 1.5.14 (outdated, latest: 1.6.0)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by FabianLars** [comment]
This is fixed in v2, for v1, try this workaround https://github.com/tauri-apps/tauri/issues/8632#issuecomment-1897656298
