### ISSUE TITLE
[bug] Tauri IPC not responding (eg. promise is not being fulfilled/not resolving) only when returning complex values

### ISSUE THREAD

**Issue by SpikeHD** [tauri-apps/tauri#10327]
### Describe the bug

In my project, there is a mix of simple Tauri commands (those that return bools or strings or numbers or whatever) and some that return serialize-able `struct`s or other "complex" data. In all cases that I've tested, commands that return simple values work fine, run fine, and the Promises fulfill just fine.

When returning complex objects (for example, a `HashMap`, or some custom struct), the Promise will indefinitely hang. This also includes the results from Tauri plugins, such as the HTTP plugin. I cannot for the life of me figure out why. Here is an example of some tests:
![image](https://github.com/user-attachments/assets/bf44231b-3e4a-44f9-95ef-c61e3cc7dddf)

Curiously, the CrabNebula Devtools shows the results of these commands just fine, so they aren't hanging at some point during their execution, which leads me to believe something is hanging in the serialization or IPC sending process? Some CN Devtools outputs:

<div width="100%">
  <img width="40%" src="https://github.com/user-attachments/assets/6618a030-cb7f-4680-8a86-f7b60638ecca"/>
  <img width="40%" src="https://github.com/user-attachments/assets/6b80d996-9d22-4ed8-bff3-3876df07bd40"/>
</div>

Some other information:

* My project falls back to the old IPC method automatically, and this is wanted/desired
* My project points to an external site, not one running locally
* Capabilities, enabled plugins, features, etc. can be found [here](https://github.com/SpikeHD/Dorion/tree/next/src-tauri)
* Let me know if you need anything else! :)

### Reproduction

1. Create a Tauri v2 application, and point it to an external site. In my case, https://discord.com/app. In case it's relevant, I [create the window builder manually](https://github.com/SpikeHD/Dorion/blob/fc91ddca20af5c1c5a51d4fdfd3fa20de8126f01/src-tauri/src/main.rs#L215). Ensure it is a site that forces Tauri to fall back to the old method of IPC.
2. Write two commands, one that returns a simple value and one that returns a struct, HashMap, or some other form of complex value
```rust
[#tauri::command]
pub fn test_one() -> bool {
  true
}

[#tauri::command]
pub fn test_two() -> MyStruct {
  MyStruct {
    value: 5
  }
}
```
3. Call both of those commands in the frontend via Javascript. One should resolve just fine, the other's promise should hang forever.

### Expected behavior

The promises do not hang forever.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.1.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.77.2 (25ef9e3d8 2024-04-09)
    ✔ cargo: 1.77.2 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 22.2.0
    - pnpm: 8.6.7
    - yarn: 3.6.0
    - npm: 10.7.0
    - bun: 1.1.12

[-] Packages
    - tauri [RUST]: 2.0.0-beta.24
    - tauri-build [RUST]: 2.0.0-beta.19
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 1.5.3 (outdated, latest: 1.6.0)
    - @tauri-apps/cli [NPM]: 2.0.0-beta.21

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: https://discord.com/app
    - devUrl: https://discord.com/app
    - bundler: Vite
```

### Stack trace

```text
N/A
```

### Additional context

I have tested this on MacOS, Windows, and Linux, and all have an identical problem. In v1 this used to work fine.

**Comment by SpikeHD** [comment]
Same behavior in `2.0.0-beta.25`

**Comment by SpikeHD** [comment]
Same behaviour in `2.0.0-rc.0` as well

**Comment by lucasfernog** [comment]
See the associated PR for more information on why this was happening.

Your app cannot use the new IPC for two reasons: a bug in the window.fetch proxy, and CORS issue (discord.app does not let you request to `ipc://`).
The proxy issue can be fixed with this patch:
```diff
diff --git a/src-tauri/injection/shared/recreate.ts b/src-tauri/injection/shared/recreate.ts
index cf70a58..b2e6f99 100644
--- a/src-tauri/injection/shared/recreate.ts
+++ b/src-tauri/injection/shared/recreate.ts
@@ -13,7 +13,7 @@ export function proxyFetch() {
     const scienceReg = /\/api\/v.*\/(science|track)/g
 
     // If it matches, just let it go through native OR its a relative URL
-    if (url.toString().match(discordReg) || url.toString().startsWith('/')) {
+    if (url.toString().match(discordReg) || url.toString().startsWith('ipc://') || url.toString().startsWith('/')) {
       // Block science though!
       if (url.toString().match(scienceReg)) {
         console.log(`[Fetch Proxy] Blocked URL: ${url}`)
@@ -23,12 +23,6 @@ export function proxyFetch() {
       return window.nativeFetch(url, options)
     }
 
-    // If there is an options.body, check if it's valid JSON. if so, set that up
-    if (options && options?.body) {
-      const bodyContent = isJson(String(options.body)) ? http.Body.json(options.body) : typeof options.body === 'string' ? http.Body.text(options.body) : http.Body.bytes(options.body)
-      options.body = bodyContent
-    }
-
     if (options && options?.headers) {
       // Check if header object, if so convert back to Record<String, any>
       if (options.headers instanceof Headers) {
@@ -44,7 +38,6 @@ export function proxyFetch() {
       }
     }
 
-    // TODO this seems to hang
     const response = await http.fetch(url, {
       responseType: 3,
       ...options
@@ -75,15 +68,15 @@ export function proxyFetch() {
 
 export function proxyXHR() {
   const open = XMLHttpRequest.prototype.open
-  
-  XMLHttpRequest.prototype.open = function(...args: any[]) {
+
+  XMLHttpRequest.prototype.open = function (...args: any[]) {
     // @ts-expect-error this is fine
     open.apply(this, args)
 
     const [_method, url] = args
     const send = this.send
 
-    this.send = function() {
+    this.send = function () {
       const rgx = /\/api\/v.*\/(science|track)/g
 
       if (!String(url).match(rgx)) {
@@ -114,4 +107,4 @@ export function badPostMessagePatch() {
   window.__TAURI_POST_MESSAGE__ = () => {
     return null
   }
-}
\ No newline at end of file
+}

```

**Comment by SpikeHD** [comment]
Thank you for taking the time to look into this, as well as taking the time to see specifically how it affects my project :)
