### ISSUE TITLE
macOS app window doesn't have drop shadow

### ISSUE THREAD

**Issue by dljsjr** [tauri-apps/tauri#1033]
**Describe the bug**
On macOS, windows by default typically have a drop shadow, especially the active window. The Tauri application window does not. It is easiest to see when you have a plain white background and drag a window over some other blank white content area.

**To Reproduce**
1. Build and launch a Tauri app on macOS (reproducible in both Dev and Bundled apps)

**Expected behavior**
App windows should have a drop shadow to be consistent/"feel" native on macOS

**Screenshots**
<img width="905" alt="Screen Shot 2020-10-01 at 9 18 31 AM" src="https://user-images.githubusercontent.com/444635/94821357-1cb60c00-03c7-11eb-8a50-98d788214593.png">

**Platform and Versions (please complete the following information):**
[tauri]: running info

Operating System - Darwin(19.6.0) - darwin/x64

Node.js environment
  Node.js - 12.14.1
  tauri.js - 0.12.0

Rust environment
  rustc - 1.46.0
  cargo - 1.46.0
  tauri-bundler - 0.9.3

Global packages
  NPM - 6.14.2
  yarn - 1.22.10

App directory structure
/.git
/.vscode
/dist
/node_modules
/src
/src-tauri

App
  tauri.rs - 0.9.2
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist
  devPath - http://localhost:3000

**Additional context**
You can very quickly repro this with this template: https://github.com/dljsjr/tauri-svite-app-template

Clone, -> `yarn`, -> `yarn dev`, -> `yarn tauri dev`

**Comment by nothingismagick** [comment]
This will be fixed with the next release using wry.
