### ISSUE TITLE
[bug] - v2 tauri::command unable to deserialize Vec<u8> from Uint8Array

### ISSUE THREAD

**Issue by jasonterando** [tauri-apps/tauri#10336]
### Describe the bug

When creating a command that accepts a structure containing a Vec\<u8\>, sourced from a TypeScript interface with a UInt8Array property, the error " invalid type: map, expected a sequence" is generated.  Replacing the TypeScript Uint8Array property with a number[] property works.  From what I understand, I should be able to use UInt8Array, not sure if I am missing a feature or something.  I tried to enable tracing but couldn't get that to work either, but that is for another day...

### Reproduction

Complete example:  [on GitHub](https://github.com/jasonterando/tauri-uint8array-cmd)

Excerpts:

**TypeScript**
```ts
import { invoke } from "@tauri-apps/api/core";

const runTest = async (useNumberArray: boolean, resultEl: HTMLElement) => {
  let value = useNumberArray ? {
    name: 'TestWithNumberArray',
    data: [1, 2, 3, 4, 5]
  } : {
    name: 'TestWithUIntArray',
    data: Uint8Array.from([1, 2, 3, 4, 5])
  }

  try {
    resultEl.textContent = 'Success: ' + await invoke("convert", { value })
  } catch (e) {
    resultEl.textContent = `${e}`
  }
}

window.addEventListener("DOMContentLoaded", () => {
  let resultEl = document.querySelector("#result") as HTMLElement;
  var btn1 = document.getElementById("perform-test-1");
  if (btn1 != null) btn1.onclick = (async () => await runTest(true, resultEl));
  var btn1 = document.getElementById("perform-test-2");
  if (btn1 != null) btn1.onclick = (async () => await runTest(false, resultEl));
});
```

Tauri Rust Main
```rs
// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use tracing::Level;

fn main() {
    tracing_subscriber::fmt()
        .with_max_level(Level::TRACE)
        .with_file(true)
        .with_line_number(true)
        .init();

    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(tauri::generate_handler![convert])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[derive(serde::Deserialize)]
pub struct Test {
    name: String,
    data: Vec<u8>
}

#[tauri::command]
fn convert(value: Test) -> String {
    format!("{} is {} byte(s) long", &value.name, value.data.len())
}
```

### Expected behavior

I would expect to be able to pass JS/TS objects with Uint8Array properties and have those map to Rust Vec<u8> properties.

### Full `tauri info` output

```text
[✘] Environment
    - OS: Linux Mint 21.3 X64
    ✔ webkit2gtk-4.1: 2.44.2
    ✘ rsvg2: not installed
      Visit https://tauri.app/v1/guides/getting-started/prerequisites to learn more about tauri prerequisites
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: 1.79.0-x86_64-unknown-linux-gnu (default)
    - node: 20.15.1
    - yarn: 1.22.22
    - npm: 10.8.2

[-] Packages
    - tauri [RUST]: 2.0.0-beta.24
    - tauri-build [RUST]: 2.0.0-beta.19
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.15
    - @tauri-apps/cli [NPM]: 2.0.0-beta.22

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../out
    - devUrl: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Webpack
```

### Stack trace

```text
N/A
```

### Additional context

https://github.com/tauri-apps/tauri/issues/9787 implies that I should be able to use Uint8Array

**Comment by FabianLars** [comment]
Please add the output of the `tauri info` command as required by the issue template. Thank you.

**Comment by jasonterando** [comment]
Whoops, copy/paste fail.  Fixed

**Comment by jasonterando** [comment]
Hi, just "bumping" this to see if this will make its way into QA.  For now, I'm passing around Base64 to move data between front and back end, but I suspect with the v2's improvements in IPC, not having to de/serialize via Base64 would be a bit faster.

**Comment by FabianLars** [comment]
Uint8array can't be sent over the ipc as-is because they get interpreted as a json object and not an array. Normally the `invoke` code automatically does the Array.from call but i assume it's missing logic for when the array is part of an object and is not the main argument.

**Comment by jasonterando** [comment]
Ok. For now I'll stuck with base64'ing data.  Thanks
