### ISSUE TITLE
essential wasm bindings 

### ISSUE THREAD

**Issue by mahmoud-eltahawy** [tauri-apps/tauri#10344]
### Describe the problem

using half maintained crates to just be able to invoke backend function or listen to backend event in wasm frontend does not feel right

### Describe the solution you'd like

a lot of this library users are using rust for backend and frontend
so they can do everything on the backend and invoke or listen to it in the frontend

so all we need is just two functions
invoke and listen

**Comment by FabianLars** [comment]
This is tracked here https://github.com/tauri-apps/tauri/issues/5354 already. Thanks for the request.
