### ISSUE TITLE
[bug] V2 invalid args `value` for command `set_size`: invalid value: map, expected map with a single key

### ISSUE THREAD

**Issue by heiyehk** [tauri-apps/tauri#10349]
### Describe the bug
![image](https://github.com/user-attachments/assets/4b7dfa76-3cdd-4dca-ba87-943f8028a668)

In the latest version, I used `setSize` and `setMinSize`, and passed in `new LogicalSize` and `new PhysicalSize` and it didn't work.

``` js
	const currentWindow = getCurrent();
	await currentWindow.setSize(new LogicalSize(400, 200));
	await currentWindow.setMinSize(new PhysicalSize(100, 100));
```
![image](https://github.com/user-attachments/assets/0176c0ad-3989-4d30-a4b0-7f93e9cb3b7c)

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 126.0.2592.113
    ✔ MSVC: Visual Studio 生成工具 2022
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.14.0
    - pnpm: 9.3.0
    - npm: 10.7.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.24
    - tauri-build [RUST]: 2.0.0-beta.19
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.6
    - @tauri-apps/cli [NPM]: 2.0.0-beta.10

[-] App
    - build-type: bundle
    - CSP: script-src 'self' 'unsafe-eval'; font-src https://fonts.gstatic.com http://tauri.localhost; img-src 'self' asset: http: https: data:; connect-src ipc: http://ipc.localhost ws: http://tauri.localhost; style-src 'unsafe-inline' 'self'; media-src 'self' asset: http: https: data:; default-src 'self' asset: http://asset.localhost https://www.google-analytics.com
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Please try updating `@tauri-apps/api` (and while you're at it `@tauri-apps/cli` too) to the latest version too. beta.6 is quite old and should be the reason for this error (it sends the old format to the new tauri version)

**Comment by heiyehk** [comment]
> Please try updating (and while you're at it too) to the latest version too. beta.6 is quite old and should be the reason for this error (it sends the old format to the new tauri version)`@tauri-apps/api``@tauri-apps/cli`

Is it the `cargo.toml` in the project? I am now
 `tauri = { version = "2.0.0-beta.24", features = [ "protocol-asset", "devtools"] }`

**Comment by heiyehk** [comment]
> Please try updating (and while you're at it too) to the latest version too. beta.6 is quite old and should be the reason for this error (it sends the old format to the new tauri version)`@tauri-apps/api``@tauri-apps/cli`

Thank you so much
