### ISSUE TITLE
https server

### ISSUE THREAD

**Issue by jswhisperer** [tauri-apps/tauri#1034]
**Is your feature request related to a problem? Please describe.**
Is it possible to run a https in dev mode? I've got it working with nuxt 
```
server: {
    https: {
      key: fs.readFileSync(path.resolve(__dirname, 'localhost.key')),
      cert: fs.readFileSync(path.resolve(__dirname, 'localhost.crt'))
    }
  },
```
and on a browser it works. but when tauri creates the webview window I get 
`Error performing TLS handshake: An unexpected TLS packet was received.`
do I need to do some proxy magic?

**Comment by matthewmullin01** [comment]
I am having the same issue too. Trying to load Google Analytics complains with a -
`Failed to load resource: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.`

Did you find a solution for this?

**Comment by jswhisperer** [comment]
https://github.com/tauri-apps/tauri/issues/1034#issuecomment-727261521 Are you specifically running a https server locally? if not you could try load google analytics without the protocol "http" "https" https://www.html5rocks.com/en/tutorials/speed/script-loading/ 
Just remove the http: and leave the `<script async src='//www.google-analytics.com/analytics.js'></script>
`

**Comment by matthewmullin01** [comment]
I was using Google Analytics vis Firebase with `firebase.analytics()` so I had no control of the URL.

I have switched to normal Google Analytics to resolve this and it is working now with https forced.

**Comment by nklayman** [comment]
In development, a localhost server is used which is considered a secure context even with just `http`, so that should be fine. With a built app, the next version of Tauri will use a custom protocol loader that is also a secure context, so an https server shouldn't be necessary. If someone finds a scenario where it is, then let me know and I'll reopen this.

**Comment by mxismean** [comment]
axios , http url 
then,
I got:
[Error] Failed to load resource: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.

**Comment by nothingismagick** [comment]
@mxismean - your comment is not relevant to the discussion, since you are trying to send a request to a remote server that does not use any encryption. See my comment on your other issue.
