### ISSUE TITLE
[bug] tauri on linux does not include `Content-Type` response header and this wil disable SPA in nextjs

### ISSUE THREAD

**Issue by anatawa12** [tauri-apps/tauri#10350]
### Describe the bug

tauri on linux does not include `Content-Type` response header and this wil disable SPA in nextjs (refreshes whole page every time)

### Reproduction

https://github.com/anatawa12/tauri-linux-content-type

This repository contains tauri app to check `Content-Type` header for file type and next.js app to show refresh happens

### Expected behavior

`Content-Type` header should be included in response header based on file extension

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.12.2
    - pnpm: 8.15.4
    - yarn: 1.22.19
    - npm: 10.8.1

[-] Packages
    - tauri [RUST]: 1.6.8
    - tauri-build [RUST]: 1.5.3
    - wry [RUST]: 0.24.10
    - tao [RUST]: 0.16.9
    - tauri-cli [RUST]: 1.5.14
    - @tauri-apps/api [NPM]: 1.6.0
    - @tauri-apps/cli [NPM]: 1.6.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: out
    - devPath: http://localhost:3030/
    - framework: React (Next.js)
    - bundler: Webpack
```

### Additional context

downstream issue: vrc-get/vrc-get#1213

**Comment by FabianLars** [comment]
Try adding the `linux-protocol-headers` feature flag to the tauri dependency in Cargo.toml.
This should hopefully set all headers correctly. It's not enabled by default in v1 because it raises the minimum webkitgtk version.

**Comment by anatawa12** [comment]
could you document that somewhere?
I think this fact must be documented somewhere in https://tauri.app/v1/guides/getting-started/setup/next-js
