### ISSUE TITLE
[feat] Tauri Core Plugin Namespace Prefix

### ISSUE THREAD

**Issue by tillmann-crabnebula** [tauri-apps/tauri#10359]
### Describe the problem

Currently all Tauri core APIs are pseudo plugins.

They implement the plugin trait but are not individual crates following the `tauri-plugin-` naming scheme, as this would cause circular dependencies for the code depending on tauri and the tauri code depending on the "plugin".

This means currently we:

* Need to reserve/block all tauri-plugin-<core plugin name> plugins

* Can not differentiate between core and external plugins

### Describe the solution you'd like

To mitigate some problems we propose a `core-` prefix for all core plugins and to document and enforce that the `core-` plugin "namespace"  is only able to be used from within the tauri core and not from any other plugin.

- [ ] All `tauri-plugin-core-*` crates should be blocked from being initialized outside of the Tauri core.
- [ ] No `tauri-plugin-core` crate should be valid. Maybe we reserve the crate name to avoid confusion?
- [ ] The core plugins should be renamed as `core-<core-plugin-name>` (e.g. `core-path`, `core-window`, `core-webview`, ...).

The documentation should be updated to reflect this behavior.

As this is a breaking change we need to test this explicitly and involve multiple people for a review.
This will add minimal boilerplate in the code and permission files but should be mostly mitigated by having a `core:default` permission set for all core plugins.

### Alternatives considered

We considered changing the architecture to be able to handle more than one namespace like `core:app:reload` instead of `app:reload` but this is also a breaking change involving a bigger refactor and we still have the `core` prefix/namespace to be reserved.

### Additional context

Was initially discussed with @chippers and @lucasfernog

**Comment by lucasfernog** [comment]
Turns out changing the architecture to allow `core:{plugin}:{permission}` is not too complicated, will open a PR soon
