### ISSUE TITLE
[bug] No errors info

### ISSUE THREAD

**Issue by thewh1teagle** [tauri-apps/tauri#10367]
### Describe the bug

When using Global Tauri in v2 projects and there's any error when calling command from js, it doesn't display the error, instead it display this:

![image](https://github.com/user-attachments/assets/1497832c-4ae1-4b34-b174-a7825326e1a0)

It happens on macOS / Windows. with multiple different tauri v2 projects.

### Reproduction

Create new project in v2 with `npx tauri init` and then call something from the API which you don't have permission for instance.

### Expected behavior

It should show the error info

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 126.0.2592.113
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.81.0-nightly (9057c3ffe 2024-07-19)
    ✔ cargo: 1.81.0-nightly (a2b58c3da 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: nightly-x86_64-pc-windows-msvc (default)
    - node: 20.12.0
    - npm: 10.5.0
    - bun: 1.1.10

[-] Packages
    - tauri [RUST]: 2.0.0-beta.24
    - tauri-build [RUST]: 2.0.0-beta.19
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-beta.22

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: dist
    - devUrl: http://google.com/
```

### Additional context

I create the window in setup. instead of from tauri config. maybe related?

**Comment by amrbashir** [comment]
I think this is solved by #10585
