### ISSUE TITLE
Electron to tauri system

### ISSUE THREAD

**Issue by Milo123459** [tauri-apps/tauri#1036]
**Is your feature request related to a problem? Please describe.**
N/A
**Describe the solution you'd like**
Not a solution, but simply a program that can convert electron apps to tauri systems.
**Describe alternatives you've considered**
N/A
**Additional context**
Not really, just maybe a cli that can convert electron apps into tauri code, would be useful for projects like VSCode, as it takes up quite a bit of memory and tauri could massively reduce that, but the devs over at VScode wouldn't be in the mood for rewriting everything again (I imagine

**Comment by nklayman** [comment]
A program that automatically converts an app would be extremely difficult, as the main process code would have to be converted from JS to Rust (at least until Tauri gets support for JS via Deno). However, we are planning on creating some tools to make the transition process easier. These will likely come after beta/stable, as they aren't of high priority yet.
