### ISSUE TITLE
[bug] multi window dont work alpha

### ISSUE THREAD

**Issue by P-Asta** [tauri-apps/tauri#10372]
### Describe the bug

2nd window dont work apply alpha

https://github.com/user-attachments/assets/b7bc2667-54d1-4047-b69c-8117a144bb91

### Reproduction

apply work alpha

### Full `tauri info` output

```text
yarn run v1.22.22
$ tauri info

[✔] Environment
    - OS: Mac OS 14.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 22.5.1
    - pnpm: 8.15.1
    - yarn: 1.22.22
    - npm: 10.8.2

[-] Packages
    - tauri [RUST]: 1.7.1
    - tauri-build [RUST]: 1.5.3
    - wry [RUST]: 0.24.10
    - tao [RUST]: 0.16.9
    - tauri-cli [RUST]: 1.6.0
    - @tauri-apps/api [NPM]: 1.6.0
    - @tauri-apps/cli [NPM]: 1.6.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
✨  Done in 29.57s.
```

**Comment by FabianLars** [comment]
Can you please provide a minimal reproduction repo/example we can try?

**Comment by P-Asta** [comment]
> Can you please provide a minimal reproduction repo/example we can try?

https://github.com/5-23/astai

**Comment by FabianLars** [comment]
If you remove `className="bg-red-400"` from the component it works for me.

**Comment by P-Asta** [comment]
> If you remove `className="bg-red-400"` from the component it works for me.
dont work alpha background
<img width="952" alt="image" src="https://github.com/user-attachments/assets/057ecb88-06b3-42f3-90b2-51805e9a7b7c">

**Comment by P-Asta** [comment]
<img width="306" alt="image" src="https://github.com/user-attachments/assets/991da21a-9b2c-4578-9184-1f7d64bec621">

**Comment by FabianLars** [comment]
Then there's something else in your window doing that. Did you try using the devtools inspector to check the elements background colors?

I can only go off the minimal repro here and in that, this was the issue.

**Comment by P-Asta** [comment]
> Then there's something else in your window doing that. Did you try using the devtools inspector to check the elements background colors?
> 
> I can only go off the minimal repro here and in that, this was the issue.

yea its not white(has a alpha)
<img width="841" alt="image" src="https://github.com/user-attachments/assets/33f9c075-3d09-4f5c-94f3-b5142c48bdee">

**Comment by FabianLars** [comment]
Ah sorry i got it. Your second window is missing `.transparent(true)` so change this:
```rs
            let setting_window = tauri::WindowBuilder::new(
                &app.handle(),
                "setting", /* the unique window label */
                tauri::WindowUrl::App("settings".into()),
            )
            .build()
            .unwrap();
```
to this
```rs
            let setting_window = tauri::WindowBuilder::new(
                &app.handle(),
                "setting", /* the unique window label */
                tauri::WindowUrl::App("settings".into()),
            )
            .transparent(true) // <--
            .build()
            .unwrap();
```
and it should work.

**Comment by P-Asta** [comment]
thx!
<img width="1183" alt="image" src="https://github.com/user-attachments/assets/3b44cf09-48c8-46d3-90ad-1a83e7117bdf">
