### ISSUE TITLE
[bug] [v2beta] `fullscreen` display bug. A white line on the top

### ISSUE THREAD

**Issue by will5933** [tauri-apps/tauri#10380]
### Describe the bug

`fullscreen` display bug. A white line on the top.
```
"app": {
    "withGlobalTauri": true,
    "windows": [
      {
        "label": "wallpaper_tauri_233",
        "title": "wallpaper tauri 233",
        "decorations": false,
        "fullscreen": true,
        "transparent": true,
        "resizable": false,
        "dragDropEnabled": false,
        "theme": "Dark"
      }
    ],
    "security": {
      "csp": null
    }
  },
```
<img width="1280" alt="PixPin_2024-07-25_07-23-48" src="https://github.com/user-attachments/assets/04f1ddb1-06b1-413b-9a5a-71d70a6dcc76">

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 126.0.2592.113
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)

[-] Packages
    - tauri-cli [RUST]: 2.0.0-beta.22

[-] App
```

### Additional context

```
OS: Windows 11 23H2
```

```
Internal Display
Display: Connected to AMD Radeon 780M Graphics

Desktop Mode: 2560 x 1600, 240 Hz
Active Signal Mode: 2560 x 1600, 240 Hz
Bit Depth: 10-bit
Color Format: RGB
Color Space: Standard Dynamic Range (SDR)
```

**Comment by will5933** [comment]
OS: Windows 11 23H2

**Comment by will5933** [comment]
👀

**Comment by will5933** [comment]
@FabianLars 
i solved it by adding `"shadow": false` in `tauri.conf.json`.
我在`tauri.conf.json`文件中添加了`"shadow": false`，然后问题解决了。

```
    "windows": [
      {
        "title": "Desutop",
        "label": "main",
        "alwaysOnTop": true,
        "decorations": false,
        "fullscreen": true,
        "focus": false,
        "closable": false,
        "shadow": false,
        "resizable": false,
        "visible": false
      }
    ],
```

**Comment by FabianLars** [comment]
Can someone confirm whether it's still an issue with the latest rc?

Edit: Specifically for fullscreen windows! I know that it's still a problem for "normal" windows.

Edit2: If it is still an issue, and your window is forced to be fullscreen, can you check its behavior with decorations: true (which shouldn't show up in fullscreen windows anyway)

**Comment by ZelCloud** [comment]
On windows if I have a default tauri application (floating window not fullscreen) with decorations set to false I get white lines on the right and bottom of the application window.

**Comment by CyanFroste** [comment]
> On windows if I have a default tauri application (floating window not fullscreen) with decorations set to false I get white lines on the right and bottom of the application window.

Hi @ZelCloud , did this get fixed?

One of my app users is still having this issue. Unfortunately I'm unable to replicate on my own machines.
