### ISSUE TITLE
[v2] No way to remove plugins

### ISSUE THREAD

**Issue by StepanZagray** [tauri-apps/tauri#10384]
I couldn't find anything in docs or with `cargo tauri --help` that is related to removing plugins from your project. 

I know that removing plugins from project is rare, but I still think it's a solid "nice to have".

**Comment by rulatir** [comment]
Workarounds? What if someone installed a wrong version of a plugin and ***MUST*** remove it, or the project is stalled and starvation looms?

**Comment by FabianLars** [comment]
I don't understand your comment. This issue was closed because it was resolved by adding a `tauri remove` command. What else would you like to see?
