### ISSUE TITLE
Calling API functions too many times causes 'TypeError: Unable to delete property.'

### ISSUE THREAD

**Issue by virtualgraham** [tauri-apps/tauri#1038]
After calling API functions too many times they will fail with `TypeError: Unable to delete property.`, but only when the Web Inspector is not open. When the Web Inspector is open, it works fine.

Minimal reproducible examples:
```
async function writeTooManyTextFiles() {
  for(let i=0; i<300; i++) {
    console.log("writeTooManyTextFiles", i)
    await writeFile({path: '/Users/racoon/test.txt', contents: 'Testing'})
  }
}

async function readTooManyTextFiles() {
  for(let i=0; i<300; i++) {
    console.log("readTooManyTextFiles", i)
    const text = await readTextFile('/Users/racoon/test.txt')
  }
}

async function readTooManyDirectories() {
  for(let i=0; i<300; i++) {
    console.log("readTooManyDirectories", i)
    const text = await readDir('/Users/racoon/')
  }
}
```
They fail consistently for me after 168 files with error `TypeError: Unable to delete property.`. 

This error is thrown by at `Reflect.deleteProperty(window, error)` at line 70 of `cli/tauri.js/api-src/tauri.ts`

This error is strange because I checked and the property does exist on the window object. It seems after calling readTextFile more than 168 times, all calls to `Reflect.deleteProperty` will fail with this error. 

I have reproduced this on Mac and Ubuntu

Here is the issue boiled down to just the combination of Promises and using `Reflect.deleteProperty()`. This shows the problem is the way `cli/tauri.js/api-src/tauri.ts` promisifies the api calls and not the API calls themselfs:
```
function bar() {
  return new Promise((resolve, reject) => {
    const p = Math.random().toString(36).substring(7);
    try {
      Object.defineProperty(window, p, {
        value: p
      });
    } catch (e) {
      reject(e)
    }
    setTimeout(() => {
      try {
        Reflect.deleteProperty(window, p)
        resolve()
      } catch (e) {
        reject(e)
      }
    }, 0);
  })
}

async function foo() {
  for(let i=0; i<3000; i++) {
    console.log("foo", i)
    await bar()
  }
}
```

Output:
```
...
[Log] foo – 132
[Log] foo – 133
[Log] foo – 134
[Log] foo – 135
[Log] foo – 136
[Log] foo – 137
[Log] foo – 138
[Error] error loading data – TypeError: Unable to delete property.
TypeError: Unable to delete property.
	_callee4$ (index.js:1126)
	tryCatch (runtime.js:63)
	invoke (runtime.js:293)
	asyncGeneratorStep (asyncToGenerator.js:9)
	_throw (asyncToGenerator.js:35)
	promiseReactionJob
```

**Comment by onsails** [comment]
we also experience this error when webapp makes a promisified call like ~150 times.

**Comment by typon** [comment]
I see this error too. any hints?

**Comment by virtualgraham** [comment]
It seems `Object.defineProperty` is the root of the problem. I found that the solution would be to change https://github.com/tauri-apps/tauri/blob/087c0e8cc983b72fbc41f64aedba34b5cabf6949/cli/tauri.js/api-src/tauri.ts#L45-L54 
to 
```javascript
window[identifier] = (result: any) => {
    if (once) {
        Reflect.deleteProperty(window, identifier)
    }

    return callback?.(result)
}
```

**Comment by nothingismagick** [comment]
Great find @virtualgraham - need to confirm with @lucasfernog though if this creates other unexpected side effects.

**Comment by lucasfernog** [comment]
I think this won't work on Windows. I'll investigate this.

**Comment by lucasfernog** [comment]
Hmm I can't reproduce this on my Linux. Will try on mac later.

**Comment by onsails** [comment]
Yep, I should have mentioned that this problem is happening on macOS

**Comment by lucasfernog** [comment]
I can't reproduce this on macOS. Can one of you see if adding `configurable: true` to the Object.defineProperty call fixes it? Like this:

```javascript
Object.defineProperty(window, identifier, { 
   value: (result: any) => { 
     if (once) { 
       Reflect.deleteProperty(window, identifier) 
     } 
  
     return callback?.(result) 
   }, 
   writable: false,
   configurable: true
 }) 
```

**Comment by virtualgraham** [comment]
Yes, it does work with `configurable: true`. That may be the solution. Why do you think this is happening? Also What code are you using to reproduce the problem? It happens for me on Ubuntu and Mac.

If I had to guess, with `configurable: false`, it is being optimized in js engine in such a way that does not expect the property to be deleted.

**Comment by lucasfernog** [comment]
I have no idea, seems like the problem only happens after some time? Maybe it's an invalid property name and it won't happen with me since it's random, i don't know. I was using the `bar` and `foo` function examples from above to try to reproduce it.

If configurable as true fix it, then we should just PR it and hope it doesn't happen anymore.

**Comment by typon** [comment]
How can i modify tauri locally to try this change? I can't get tauri to rebuild inside my node_modules :( 

Edit: I can do `npm run build:api` in `tauri` after trying the change and I can confirm the error goes way on MacOS. Thanks guys :)

**Comment by virtualgraham** [comment]
@lucasfernog with regard to the `bar` and `foo`, it failed for me in Mac Safari and Firefox Ubuntu as you see in the sample output only when executed in a Tauri bundled app. When I run the same `bar` and `foo` example just in plain javascript / html, Safari Mac did not error, but Firefox and Edge for Mac I get a similar but different error: 
```
foo 2461 index.html:34:17
foo 2462 index.html:34:17
foo 2463 index.html:34:17
TypeError: can't define elements on a Window object
    bar http://127.0.0.1:5500/index.html:15
    bar http://127.0.0.1:5500/index.html:12
    foo http://127.0.0.1:5500/index.html:35
```

I recommend you just try a `readDir` inside a loop to reproduce the bug:
```
async function readTooManyDirectories() {
  for(let i=0; i<300; i++) {
    console.log("readTooManyDirectories", i)
    const text = await readDir('/Users/racoon/')
  }
}
```

**Comment by lucasfernog** [comment]
I can reproduce it with the `readTooManyDirectories` call and it seems like `configurable: true` is the fix here. I'll PR it.

**Comment by drathier** [comment]
Just ran into this issue now too. Happy that it's already been fixed!
