### ISSUE TITLE
[bug] Corss compiling on 1.X  with cargo dev build does not work for any windows cross compile

### ISSUE THREAD

**Issue by OreoCookieRustDev** [tauri-apps/tauri#10389]
### Describe the bug

I can cross compile for release with no issues using:

`cargo tauri build --target x86_64-pc-windows-gnu`

The minute I try to use dev I get linking errors.

`cargo tauri dev --target x86_64-pc-windows-gnu`

`linking with x86_64-w64-mingw32-gcc failed: exit status: 1`

I am using a Rust + vanilla setup

### Reproduction

`cargo tauri dev --target x86_64-pc-windows-gnu`

### Expected behavior

A windows dev build to be created

### Full `tauri info` output

```text
[✔] Environment
    - OS: Ubuntu 22.4.0 X64
    ✔ webkit2gtk-4.0: 2.44.2
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.80.0 (051478957 2024-07-21)
    ✔ cargo: 1.80.0 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)

[-] Packages
    - tauri [RUST]: 1.7.1
    - tauri-build [RUST]: 1.5.3
    - wry [RUST]: 0.24.10
    - tao [RUST]: 0.16.9
    - tauri-cli [RUST]: 1.6.0
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 1.6.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../src
    - devPath: ../src
```

**Comment by FabianLars** [comment]
Are you maybe looking for `cargo tauri build --debug` ? `cargo tauri dev` is really not designed for cross compilation so it will likely have more issues besides yours. I think this counts as a `wontfix` for us but please post the _full_ error log anyway.

Also try `cargo build` (if your project is super old it'll be `cargo build --no-default-features`) directly. It should behave the same, just without running `beforeDevCommand`.

**Comment by OreoCookieRustDev** [comment]
It works on v2 no problem, but not on 1.6. 

I tend to develop on Linux through a VPS so it has no access to GUI, so I cross compile and test on a windows machine but compiling through production doesn't have all the same features as a dev compile. 

Sad it won't be planned to work in 1.6 but works fine on v2.
