### ISSUE TITLE
[feat] Support styling border-radius to frameless window

### ISSUE THREAD

**Issue by gaomingzhao666** [tauri-apps/tauri#10401]
### Describe the problem

Hey, I am trying to set the window border-radius on a frameless window that has set decorations as false on tauri.conf.json, but I found documentation there is only have method to customize Titlebar, and I tried to set CSS class on body tag on Html as following codes but it does not work.

```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" href="%sveltekit.assets%/favicon.png" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<style>
			 #app{
				border-radius: 90px !important;
			}
		</style>
		<title>Things</title>
		%sveltekit.head%
	</head>
	<body data-sveltekit-preload-data="hover" id="app" >
		<div style="display: contents" id="app" >%sveltekit.body%</div>
	</body>
</html>

```

I searched this question on Stackoverflow but the answer is [there is no option to customize the region](https://stackoverflow.com/questions/76180922/set-window-border-radius-in-tauri-apps)

### Describe the solution you'd like

Support styling border-radius or setting rounded-size window on tauri.conf.json or CSS.

**Comment by gaomingzhao666** [comment]
As expected I can use CSS to customize window's border-radius like electron.js in this [essay](https://bobby-valenzuela.medium.com/electron-js-how-to-create-a-beautiful-frameless-window-8ee9ef9d1280)

**Comment by gaomingzhao666** [comment]
> As expected I can use CSS to customize window's border-radius like electron.js in this [essay](https://bobby-valenzuela.medium.com/electron-js-how-to-create-a-beautiful-frameless-window-8ee9ef9d1280)

Sorry I was clumsy, I can apply this essay to the `Tauri app` by setting transparent as true and frame as false and then I can use a container HTML element such as div to wrap all of my content about this application.
 At last, I can visually see this container as the edge or border of this application, so this solution can result in overcoming this issue.

**Comment by xiaoyan2015** [comment]
![018360截图20240927070201328](https://github.com/user-attachments/assets/270d1276-0402-48c6-90ce-cc4689763e3a)
You can set `transparent: true`，`shadow: false` and then implement rounded shadow windows via css.

**Comment by gaomingzhao666** [comment]
> > As expected I can use CSS to customize window's border-radius like electron.js in this [essay](https://bobby-valenzuela.medium.com/electron-js-how-to-create-a-beautiful-frameless-window-8ee9ef9d1280)
> 
> Sorry I was clumsy, I can apply this essay to the `Tauri app` by setting transparent as true and frame as false and then I can use a container HTML element such as div to wrap all of my content about this application. At last, I can visually see this container as the edge or border of this application, so this solution can result in overcoming this issue.

@xiaoyan2015 非常感谢老哥的帮忙，不过这和我之前发的评论是相同的解决办法。我已经解决了，谢谢你啦！
