### ISSUE TITLE
[bug] When using cargo-xwin , setting the environment variable OPENSSL_DIR prompts a file not found error

### ISSUE THREAD

**Issue by RickSKy** [tauri-apps/tauri#10416]
### Describe the bug

```bash
OPENSSL_DIR=src-tauri/3p/openssl-win cargo tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc
```
And  src-tauri/3p/openssl-win store the openssl 's  lib, the error info 
```
OpenSSL library directory does not exist: src-tauri/3p/openssl-win/lib
```
then try the command below
```bash
OPENSSL_DIR=`pwd`/src-tauri/3p/openssl-win cargo tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc
```
it seemed found the openssl lib. the error info 
```
error: linking with `lld-link` failed: exit status: 1
...
= note: lld-link: error: could not open 'crypto.lib': No such file or directory
```
but the `pwd`/src-tauri/3p/openssl-win/lib/crypto.lib is correct

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.5.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.0 (051478957 2024-07-21)
    ✔ cargo: 1.80.0 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: 1.80-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 22.5.1
    - npm: 10.8.2

[-] Packages
    - tauri [RUST]: 1.7.1
    - tauri-build [RUST]: 1.5.3
    - wry [RUST]: 0.24.10
    - tao [RUST]: 0.16.9
    - tauri-cli [RUST]: 1.6.0
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 1.6.0

[-] App
    - build-type: build
    - CSP: unset
    - distDir: ../../../target/vcli/dist
    - devPath: http://localhost:5174/
    - bundler: Vite
```

**Comment by FabianLars** [comment]
This does not look Tauri specific to me so it may be more efficient if you could reach out to the cargo-xwin maintainers instead.

One pointer i can give though, is something i wrote on [discord](https://discord.com/channels/616186924390023171/1259851854704279584) in a similar context:
> First I downloaded the **zip** from here <https://kb.firedaemon.com/support/solutions/articles/4000121705> and extracted it somewhere easily accessible (in my case the home dir)
> Then i set some env vars:
> ```sh
> export X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR="/home/fabianlars/openssl-3/x64/lib/"
> export X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR="/home/fabianlars/openssl-3/x64/include/"
> export X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR="/home/fabianlars/openssl-3/x64/"
> ```
> And then the build command seemed to succeed, at least in a fairly simple app with way less dependencies.

The instructions were for Linux but iirc i tested it on macOS too.

----

If that doesn't help, and if the xwin people can't help either, please provide more exact steps you took, like where you got openssl from etc (maybe provide a minimal reproduction?)

**Comment by RickSKy** [comment]
it works! thanks so much!
