### ISSUE TITLE
[bug] Verify signature error: InvalidSignature 

### ISSUE THREAD

**Issue by anderoavv** [tauri-apps/tauri#10425]
### Describe the bug

Been trying to debug this `Verify signature error: InvalidSignature `for the past 2 days, without any luck..

Tried to generate new keys, with and without passwords.
From past issues that I've had with MacOS & Archives, tried restarting my computer, closing all Finder windows, while installing, compiling new versions - no luck.
Tried building locally & via github actions, same issue.

.key -> ENV
.key.pub -> Config
.sig -> release json

Compiles without any errors, if I try to use another key it says Warning that different key was used, which is nice that it does that but why am I still getting InvalidSignature, when I try to update the app and use correct keys..

Any suggestions..?

### Expected behavior

Application should update

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.1.2 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.0 (051478957 2024-07-21)
    ✔ cargo: 1.80.0 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.12.0
    - yarn: 1.22.21
    - npm: 10.5.0

[-] Packages
    - tauri [RUST]: 1.7.1
    - tauri-build [RUST]: 1.5.3
    - wry [RUST]: 0.24.10
    - tao [RUST]: 0.16.9
    - tauri-cli [RUST]: 1.6.0
    - @tauri-apps/api [NPM]: 1.6.0
    - @tauri-apps/cli [NPM]: 1.6.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../build
    - devPath: http://localhost:5173/home
    - framework: Svelte
    - bundler: Vite
```

### Additional context

Tried many versions of cli, build, rust etc none of them have been able to fix the issue.

**Comment by anderoavv** [comment]
SOLVED!

After about a month, I finally decided to move my update files to another server and **it started working**.

So heads up to everybody, for some reason - I was able to download update files nicely manually when I entered the URL to my browser, but Tauri got InvalidSignature error. I moved my update file to another server as I am not using Github to host the files and like magic, it started working. 

Releases.json I kept on the same server still, just some issues with the downloaded file...

**Comment by FabianLars** [comment]
Was it behind a private URL you were able to connect to in the browser because you were logged in? Since you mentioned GitHub using a GitHub release in a _private_ repo as a cdn could fit that issue.

Of course, this just shows that our error messages are messed up as it should be way clearer about connection issues...

**Comment by anderoavv** [comment]
No it was not private url, everybody could've connected and downloaded the file - I have no clue what the issue was. 
It was in a folder where my website images were served from, eg logo etc, but now I moved it to a S3 storage. 

If I am not mistaken I also tried Github Actions and those resulted in the same error.. - I might be wrong here but I am quite sure about that.
