### ISSUE TITLE
[bug] [v2] After upgrading, all permission configurations have become ineffective

### ISSUE THREAD

**Issue by bling-yshs** [tauri-apps/tauri#10424]
### Describe the bug

After upgrading tauri v2 beta 22 to beta 25, and updating various plugins to the latest version, all permission configurations have become ineffective, and I haven't made any changes to my code.
![image](https://github.com/user-attachments/assets/2decccae-424b-44c2-a17e-bd1c84fedcd0)
![image](https://github.com/user-attachments/assets/f0137f81-c4e8-4650-bbb3-364af4b6e75f)

### Reproduction

https://github.com/bling-yshs/code-merger-tauri/tree/dev-2

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 124.0.2478.80
    ✔ MSVC: Visual Studio 生成工具 2022
    ✔ rustc: 1.77.2 (25ef9e3d8 2024-04-09)
    ✔ cargo: 1.77.2 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.10.0
    - pnpm: 9.5.0
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 2.0.0-beta.25
    - tauri-build [RUST]: 2.0.0-beta.19
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.13
    - @tauri-apps/cli [NPM]: 2.0.0-beta.20

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:11420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by FabianLars** [comment]
I don't know what changed in tauri but testing your project it seems to work after removing the `"capabilities": []` line from capabilities/default.json, can you confirm that?

**Comment by bling-yshs** [comment]
> I don't know what changed in tauri but testing your project it seems to work after removing the `"capabilities": []` line from capabilities/default.json, can you confirm that?

After removing the `capabilities`, my issue was resolved. Thank you very much!
