### ISSUE TITLE
[Help]How to hide the sidecar console window?

### ISSUE THREAD

**Issue by Kukaina** [tauri-apps/tauri#10430]
I wrote and packaged a file in Python. When I double-clicked to open the file, no console window appeared. However, when I used the sidecar function to start the file,

 a console window appeared.s shown in my video

https://github.com/user-attachments/assets/3a326286-74bc-49f2-8db7-f72472bd2794

I use these codes to start this sidecar
``` JavaScript
import { Command } from "@tauri-apps/plugin-shell";
const sidecar_command = Command.sidecar("bin/MangovidAPI");
await sidecar_command.execute();
```
And this situation only occurs after packaging, it is normal during development, that is, when the yarn tauri dev command is running

**Comment by FabianLars** [comment]
Did you by any chance remove this line from your main.rs file? https://github.com/tauri-apps/tauri/blob/dev/examples/api/src-tauri/src/main.rs#L6

**Comment by Kukaina** [comment]
> Did you by any chance remove this line from your main.rs file? https://github.com/tauri-apps/tauri/blob/dev/examples/api/src-tauri/src/main.rs#L6

Thanks, I noticed I was missing one line of code`!`

**Comment by ikxin** [comment]
using `pnpm tauri build --debug` generated result seems to have the same issue.
