### ISSUE TITLE
[An error occurred during compilation] 

### ISSUE THREAD

**Issue by HugoQwQ** [tauri-apps/tauri#10454]
### Describe the bug

Error failed to bundle project: `https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314-binaries.zip: Connection Failed: tls connection init failed: invalid peer certificate: UnknownIssuer`

Full Version:
PS D:\*****\****> npm run tauri build

> ******@0.0.0 tauri
> tauri build

     Running beforeBuildCommand `npm run build`

> *****@0.0.0 build
> vite build

vite v5.3.5 building for production...
✓ 32 modules transformed.
dist/index.html                   0.48 kB │ gzip:  0.31 kB
dist/assets/index-QMUHOJWu.css    1.25 kB │ gzip:  0.61 kB
dist/assets/index-DRkWgN8I.js   143.58 kB │ gzip: 46.24 kB
✓ built in 911ms
   Compiling zhang-tauri v0.0.0 (D:\project\Zhang-tauri\src-tauri)
    Finished `release` profile [optimized] target(s) in 21.08s
        Info Verifying wix package
 Downloading https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314-binaries.zip
       Error failed to bundle project: `https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314-binaries.zip: Connection Failed: tls connection init failed: invalid peer certificate: UnknownIssuer`

### Full `tauri info` output

```text
PS D:\*****\****> npm run tauri info

> *****@0.0.0 tauri
> tauri info


[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 126.0.2592.113
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.80.0 (051478957 2024-07-21)
    ✔ cargo: 1.80.0 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.16.0
    - yarn: 1.22.22
    - npm: 10.8.1

[-] Packages
    - tauri [RUST]: 1.7.1
    - tauri-build [RUST]: 1.5.3
    - wry [RUST]: 0.24.10
    - tao [RUST]: 0.16.9
    - @tauri-apps/api [NPM]: 1.6.0
    - @tauri-apps/cli [NPM]: 1.6.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Do you have a system proxy that may not allow GitHub outside of the browser?

If so, try downloading it manually: https://github.com/tauri-apps/tauri/issues/7338#issuecomment-2213235410

**Comment by GuHugo95** [comment]
I tried that but it doesn't work

**Comment by HugoQwQ** [comment]
> Do you have a system proxy that may not allow GitHub outside of the browser?
> 
> If so, try downloading it manually: [#7338 (comment)](https://github.com/tauri-apps/tauri/issues/7338#issuecomment-2213235410)

Thanks, you are right, there is a problem with my system proxy
