### ISSUE TITLE
[bug] Cannot Create New rc-0 App With create-tauri-app

### ISSUE THREAD

**Issue by slimandslam** [tauri-apps/tauri#10458]
### Describe the bug

Following the directions here:  https://v2.tauri.app/start creates a Tauri v1 app instead of a Tauri v2 rc0 app

```
$ yarn create tauri-app --rc
yarn create v1.22.22
warning package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-tauri-app@4.0.3" with binaries:
      - create-tauri-app
[##########################################################################] 74/74? Choose which language to use
✔ Choose which language to use for your frontend · TypeScript / JavaScript - (pnpm, yarn, npm, bun)
✔ Choose your package manager · yarn
✔ Choose your UI template · React - (https://react.dev/)
✔ Choose your UI flavor · JavaScript

Template created! To get started run:
  cd --rc
  yarn
  yarn tauri dev

✨  Done in 11.57s.
$
```

### Reproduction

Follow the directions here:  https://v2.tauri.app/start  to create a new Tauri v2 rc0 app

### Expected behavior

It should create a new Tauri v2 rc0 app

### Full `tauri info` output

```text
$ yarn tauri info
yarn run v1.22.22
warning ../package.json: No license field
$ tauri info

[✔] Environment
    - OS: Mac OS 14.6.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.0 (051478957 2024-07-21)
    ✔ cargo: 1.80.0 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 18.18.0
    - pnpm: 9.0.5
    - yarn: 1.22.22
    - npm: 9.8.1
    - bun: 1.1.7

[-] Packages
    - tauri [RUST]: 1 (no lockfile)
    - tauri-build [RUST]: no manifest (no lockfile)
    - wry [RUST]: no manifest (no lockfile)
    - tao [RUST]: no manifest (no lockfile)
    - @tauri-apps/api [NPM]: 1.6.0
    - @tauri-apps/cli [NPM]: 1.6.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
✨  Done in 2.84s.
```

**Comment by tweidinger** [comment]
Are you on the latest version of `create-tauri-app`? https://github.com/tauri-apps/create-tauri-app/pull/747 `4.1` introduced the rc flag.

```
    - @tauri-apps/api [NPM]: 1.6.0
    - @tauri-apps/cli [NPM]: 1.6.0
```
Is this executed in the created application folder?

You don't have the tauri 2.x cli installed which is required for 2.0.rc, which should be installed to the project once you run the `yarn install` inside the generated project.

**Comment by slimandslam** [comment]
Are you saying that this is a documentation bug?  I followed the instructions provided. I have Rust and Node and Xcode installed.  Where does it say that I need create-tauri-app v4.1 ?

**Comment by tweidinger** [comment]
No, I was just asking if you have followed the instructions from the website recently or some days ago as a recent release introduced the rc flag and not sure how the behavior was before.

I just tested with a clean system to follow the start guide and it worked fine here. It installs the 2.0rc cli and works for me. So my guess was your local cta version is older, which does not support the `--rc` flag.


Just noticed my suspicion was correct: `success Installed "create-tauri-app@4.0.3" with binaries:`

Please either update `create-tauri-app` or re-follow the instructions from the website.

**Comment by slimandslam** [comment]
I followed the instructions in the documentation. I guess this is a documentation bug.  As you can see here (below), others are having the same problem. Merely adding a single sentence to this page:  https://v2.tauri.app/start/
that says something like:  "You need create-tauri-app v4.1 or newer," will save many people a lot of time. 

![Screenshot 2024-08-03 at 12 48 08 AM](https://github.com/user-attachments/assets/481e85a1-a506-4ad0-8a59-2ed2f7abfe38)

**Comment by tweidinger** [comment]
For people following the guide the first time there is no need to check the version.

I agree that it's not working if you have installed the tool before the latest release and do not update before usage. ~~Will change the packet manager instructions to update to the latest version.~~

**Comment by tweidinger** [comment]
Can't reproduce on my system with yarn, as it installs the latest version (4.1 automatically).
Have you retried in the last 7 hours?
There was a short time frame between the publication of 4.1 and the documentation update and I suspect that is the cause and why a few devs have this problem.

Yarn docs state the `create` subcommand will always update to latest first, so we don't need a documentation update from my perspective.

```
yarn create tauri-app --rc
yarn create v1.22.22
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-tauri-app@4.1.0" with binaries:
      - create-tauri-app
[####] 4/4name (tauri-app) ›
```

**Comment by trspro67** [comment]
I have tested with npm, bun, and yarn and it's working fine. 

However, for pnpm it's still currently not working. It does not ask for the project name and creates a '--rc' directory. 

<img width="1689" alt="tauri-rc-create-app-test" src="https://github.com/user-attachments/assets/1d3a1385-b75e-4940-9d6a-788cac03f859">

**Comment by trspro67** [comment]
No longer seeing issue with pnpm. 

![Screenshot 2024-08-04 at 10 18 43 AM](https://github.com/user-attachments/assets/e04d114a-ca6f-4907-b1b1-bfd972e18e04)
