### ISSUE TITLE
[bug] npm run tauri migrate will overwrite Tauri.toml with json

### ISSUE THREAD

**Issue by anatawa12** [tauri-apps/tauri#10461]
### Describe the bug

npm run tauri migrate will overwrite Tauri.toml with json.
If the configuration file is toml, should output json

### Reproduction

1. create Tauri v1 with `Tauri.toml` project
2. install tauri v2.0.0-rc.0 and run `npm run tauri migrate`

### Expected behavior

Tauri.toml should be migrated to toml format.

I think it's ok to change style in toml but it should be valid toml

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.81.0-beta.2 (08328a323 2024-07-25)
    ✔ cargo: 1.81.0-beta.2 (a2b58c3da 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: beta-aarch64-apple-darwin (default)
    - node: 20.12.2
    - pnpm: 8.15.4
    - yarn: 1.22.19
    - npm: 10.8.2

[-] Packages
    - tauri [RUST]: 1.7.1
    - tauri-build [RUST]: 1.5.3
    - wry [RUST]: 0.24.10
    - tao [RUST]: 0.16.9
    - tauri-cli [RUST]: 1.6.0
    - @tauri-apps/api [NPM]: 2.0.0-rc.0
    - @tauri-apps/cli [NPM]: 2.0.0-rc.0

[-] App
```

**Comment by lucasfernog** [comment]
closed by #10539
