### ISSUE TITLE
[bug] building tauri app with cache fails with `failed to read plugin permissions: failed to read file: The system cannot find the file specified. (os error 2)` on windows

### ISSUE THREAD

**Issue by anatawa12** [tauri-apps/tauri#10484]
### Describe the bug

building tauri app with cache fails with `failed to read plugin permissions: failed to read file: The system cannot find the file specified. (os error 2)` on windows.

This is because tauri uses `:` in permission file path, which will not be copied or archived in normal way.

### Reproduction

1. create tauri v2 app
2. `npm run tauri build`
3. archive target folder and restore
4. `npm run tauri build` again

### Expected behavior

it works

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 126.0.2592.113
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.80.0 (051478957 2024-07-21)
    ✔ cargo: 1.80.0 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.15.0
    - pnpm: 9.4.0
    - npm: 10.7.0

[-] Packages
    - tauri [RUST]: 2.0.0-rc.0
    - tauri-build [RUST]: 2.0.0-rc.0
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 1.5.14
    - @tauri-apps/api [NPM]: 2.0.0-rc.0
    - @tauri-apps/cli [NPM]: 2.0.0-rc.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: out
    - devUrl: http://localhost:3030/
    - framework: React (Next.js)
    - bundler: Webpack
```

### Additional context

Same issue as #9477 but with `tauri-core:webview-permission-files`

**Comment by CalebBassham** [comment]
Experienced this same thing after copying a Tauri project - quick fix was to delete `target/`.
