### ISSUE TITLE
[bug] 无法定位程序输入点ProcessPrng于动态链接库bcryptprimitives.dll 

### ISSUE THREAD

**Issue by 9mlcy7** [tauri-apps/tauri#10487]
### Describe the bug

![image](https://github.com/user-attachments/assets/1c61cc17-2bd6-4c66-a1ee-140a8da5c2b1)

I created a very simple demo, and after packaging it with `cargo tauri build`, the generated MSI and directly executable EXE can run on Windows 10 and Windows 11. However, on Windows 7, it prompts "The procedure entry point ProcessPrng could not be located in the dynamic link library bcryptprimitives.dll." I have tried the WebView2 Installation Options provided by Tauri, but both `downloadBootstrapper` and `embedBootstrapper` fail to install. I also tried the offline installer, but the result is the same.

### Full `tauri info` output

```text
N/A
```

**Comment by zcg** [comment]
Building the target
You can build Rust with support for the targets by adding it to the target list in config.toml:


[build]
build-stage = 1
target = [ "x86_64-win7-windows-msvc" ]

maybe help

**Comment by 9mlcy7** [comment]
> Building the target You can build Rust with support for the targets by adding it to the target list in config.toml:
> 
> [build] build-stage = 1 target = [ "x86_64-win7-windows-msvc" ]
> 
> maybe help
It doesn't do anything

**Comment by FabianLars** [comment]
If that ^ doesn't help you can downgrade rust to 1.75 (the last version that properly supports win7)

**Comment by loongloongw** [comment]
> If that ^ doesn't help you can downgrade rust to 1.75 (the last version that properly supports win7)如果那^没有帮助你可以将rust降级到1.75（正确支持win7的最后一个版本）

This doesn't work either. The error content becomes EventSetInformation.

**Comment by FabianLars** [comment]
> > If that ^ doesn't help you can downgrade rust to 1.75 (the last version that properly supports win7)如果那^没有帮助你可以将rust降级到1.75（正确支持win7的最后一个版本）
> 
> This doesn't work either. The error content becomes EventSetInformation.

https://github.com/tauri-apps/tauri/issues/5163

**Comment by 9mlcy7** [comment]
> > If that ^ doesn't help you can downgrade rust to 1.75 (the last version that properly supports win7)如果那^没有帮助你可以将rust降级到1.75（正确支持win7的最后一个版本）
> 
> This doesn't work either. The error content becomes EventSetInformation.

降低rust版本，然后使用静态链接打包

**Comment by Gofive** [comment]
> > > If that ^ doesn't help you can downgrade rust to 1.75 (the last version that properly supports win7)如果那^没有帮助你可以将rust降级到1.75（正确支持win7的最后一个版本）
> > 
> > 
> > This doesn't work either. The error content becomes EventSetInformation.
> 
> 降低rust版本，然后使用静态链接打包

使用静态链接打包怎么配置

**Comment by 9mlcy7** [comment]
> > > > If that ^ doesn't help you can downgrade rust to 1.75 (the last version that properly supports win7)如果那^没有帮助你可以将rust降级到1.75（正确支持win7的最后一个版本）
> > > 
> > > 
> > > This doesn't work either. The error content becomes EventSetInformation.
> > 
> > 
> > 降低rust版本，然后使用静态链接打包
> 
> 使用静态链接打包怎么配置

![image](https://github.com/user-attachments/assets/ccaed296-964b-4433-b728-d25f168ad530)

**Comment by jiangkaifree** [comment]
我也报了相同的问题， 但是是在windows7 x86 上面
