### ISSUE TITLE
environmental variables validation for updater?

### ISSUE THREAD

**Issue by leet4tari** [tauri-apps/tauri#10488]
Run into a problem where the updater is doing odd things in the github action.  
  
Looking through older issues, I see the suggestion to double check the tauri secrets for the updater, which I have done.  

But I am seeing different errors:
```Error incorrect updater private key password: Wrong password for that key``` - this one is obvious and was a testing run
```Error invalid utf-8 sequence of 1 bytes from index 28``` - is this the key or the password or something else?
```Error Invalid padding``` or ```Error [tauri_cli_node] Invalid padding``` - same question, where would the invalid padding be? 

```
/Users/runner/work/universe/universe/src-tauri/target/universal-apple-darwin/release/bundle/macos/tari-universe.app.tar.gz (updater)
       Error [tauri_cli_node] Invalid padding
```

Are there any suggestions or validations for the tauri updater envs? Length checks? base64 decoding and checking? Post job workflow signature verification? Offline manual verification of updater packages against posted signatures?

**Comment by mnardit** [comment]
If anyone is still hitting their head against the wall with Wrong password for that key in CI/CD environments, double-check your shell escaping!

I had a case where my password worked perfectly for 20 releases, then broke. The reason? A shell wrapper (specifically shell-quote) had silently inserted an invisible backslash \ before an exclamation mark ! when generating the key. If your CI environment passes variables through different shell layers, your password might be getting mutated silently.

I documented the whole debugging process and how to bypass interactive input corruption here:

https://max.nardit.com/articles/the-invisible-backslash
