### ISSUE TITLE
[feat] provide mirror option for download nsis and wix3

### ISSUE THREAD

**Issue by travisbikkle** [tauri-apps/tauri#10497]
### Describe the problem

github.com is blocked on our build servers. We managed to work around the nsis and wix download by providing our own mirror but there is no mirror option for them. It will be helpful if a similar option can be exposed for the same.

just like [ELECTRON_BUILDER_BINARIES_MIRROR](https://github.com/electron-userland/electron-builder/blob/f3404d32f029dfb63e83067012f15ef67838f326/packages/app-builder-lib/src/binDownload.ts#L21-L25)

### Describe the solution you'd like

```powershell
$env:TAURI_BUNDLER_NSIS_MIRROR="https://mirror.example.com/nsis.zip"
$env:TAURI_BUNDLER_NSIS_UTILS_MIRROR="https://mirror.example.com/nsis-utils.dll"
$env:TAURI_BUNDLER_WIX_MIRROR="https://mirror.example.com/wixxxx.zip"
```

**Comment by FabianLars** [comment]
Yeah, this is a good idea and something i had in the back of my mind for a long time now (mainly cause i get notifications for that one large gh issue about this lol).

While we're at it we should allow the same for the Linux tooling.

Also, what do you think about reducing this to a single env var for the root url and then solving the rest of the url via convention (== expected file names)? I don't know how common it is to have different root urls here but i would like to not add 10 different env vars tbh.

**Comment by travisbikkle** [comment]
I think it's a good idea to reduce these variables into one single env var for the root url.

We might need to install plugins or patches for nsis, or fix translation problems, or put linux and macos makensis executables in nsis packages for cross-compilation purposes, and therefore need to maintain a separate repository to make nsix(and other tools) to become manageable.

But this might be a bit too much work compared to the solution with separate variables.

Another problem is where to put these binaries.

I'm thinking about throwing them to npmjs.com.  `nsis.rs and wix.rs` download them from `mirror.example.com/tauri-bundler-binaries/${package_name}/${version}/${package_name}-${version}-<tripple>.7z|tgz|zip`.

like this:

```
https://mirrors.huaweicloud.com/electron-builder-binaries/
```
or this
```
https://npmmirror.com/mirrors/electron-builder-binaries/
```

But I don't think npmmirror.com and mirrors.huaweicloud.com will allow me to do that for now, it's not a standard npm package. This will take time.

So the option of separating the variables is still somewhat desirable at this stage.

**Comment by travisbikkle** [comment]
> Yeah, this is a good idea and something i had in the back of my mind for a long time now (mainly cause i get notifications for that one large gh issue about this lol).
> 
> While we're at it we should allow the same for the Linux tooling.
> 
> Also, what do you think about reducing this to a single env var for the root url and then solving the rest of the url via convention (== expected file names)? I don't know how common it is to have different root urls here but i would like to not add 10 different env vars tbh.

I think it's a good idea to reduce these variables into one single env var for the root url.

We might need to install plugins or patches for nsis, or fix translation problems, or put linux and macos makensis executables in nsis packages for cross-compilation purposes, and therefore need to maintain a separate repository to make nsix(and other tools) to become manageable.

But this might be a bit too much work compared to the solution with separate variables.

Another problem is where to put these binaries.

I'm thinking about throwing them to npmjs.com.  `nsis.rs and wix.rs` download them from `mirror.example.com/tauri-bundler-binaries/${package_name}/${version}/${package_name}-${version}-<tripple>.7z|tgz|zip`.

like this:

```
https://mirrors.huaweicloud.com/electron-builder-binaries/
```
or this
```
https://npmmirror.com/mirrors/electron-builder-binaries/
```

But I don't think npmmirror.com and mirrors.huaweicloud.com will allow me to do that for now, it's not a standard npm package. This will take time.

So the option of separating the variables is still somewhat desirable at this stage.
