### ISSUE TITLE
[docs] Readme feature clarification ("localhost free")

### ISSUE THREAD

**Issue by ConnorKrammer** [tauri-apps/tauri#10510]
I'm looking to use Tauri for my next desktop application. In the readme, under the list of features, is the following bullet point:
> - Localhost free (🔥)

The flame suggests this is a fairly notable point of differentiation, but I haven't been able to figure out what it means. I've searched through the issues on GitHub, read over the website, gone through the getting started guide, but still don't know. I actually even checked the blame to figure out when that line was added to the readme and then cross-referenced release notes from around that time, but no luck. Not to suggest that what's not obvious to me isn't obvious to everyone else, but maybe this should be phrased differently, or hyperlinked to something that explains it. I'm at a loss.

Hope this feedback is helpful.

**Comment by anatawa12** [comment]
I think "localhost free" means tauri doesn't create http(s) server for localhost to provide contents for webview.
(some webview-based ui framework depends on localhost http(s) sever launched internally, but tauri doesnt.)
It might be more obvious to use localhost sever free but this still is not obvious so I think it's better to explain with sentence somewhere.

**Comment by FabianLars** [comment]
The above is correct. Instead of relying on localhost server that expose your frontend to all other processes we use native webview apis to inject the assets right before the webview requests hit the network stack.

**Comment by ConnorKrammer** [comment]
Very helpful, thank you for the replies. Definitely didn't get that from the entry in the feature list; seems worth clarifying somehow.

**Comment by cryptoquick** [comment]
I'm not sure just linking to this issue is the proper fix for this, @amrbashir 

Perhaps the feature can be described as, "Uses native webview rendering"

Oh, and I guess you can keep the :fire: emoji.

**Comment by FridayCandour** [comment]
> The above is correct. Instead of relying on localhost server that expose your frontend to all other processes we use native webview apis to inject the assets right before the webview requests hit the network stack.

this is genius.

**Comment by tamadamas** [comment]
> > The above is correct. Instead of relying on localhost server that expose your frontend to all other processes we use native webview apis to inject the assets right before the webview requests hit the network stack.
> 
> Could we write any of this in README? @amrbashir
Cause I can't understand why do I need to go though github issue comment just to understand "localhost free fucking term". From README to comments, Karl?

Ok, I've just made it great again here https://github.com/tauri-apps/tauri/pull/12415 Could someone check it out?
