### ISSUE TITLE
[feat] set window background color

### ISSUE THREAD

**Issue by kanatapple** [tauri-apps/tauri#10519]
### Describe the problem

In the multiwebview example, the areas that are not drawn are filled with white.

<img width="600" alt="multiwebview" src="https://github.com/user-attachments/assets/a63b5d8b-4f48-4050-9e16-9c5200abf6cc">

### Describe the solution you'd like

Add `Window::set_background_color(&self, color: Color)` method

**Comment by FabianLars** [comment]
Somewhat related to https://github.com/tauri-apps/tauri/issues/1564 (will keep both open since we need to change the window color _and_ the webview color.

**Comment by kanatapple** [comment]
What is the status of this issue?
