### ISSUE TITLE
Adding import for api/window causes vite desktop app not to initialize

### ISSUE THREAD

**Issue by jasonterando** [tauri-apps/tauri#10526]
### Describe the bug

From a "clean" v2-qa Linux application using React and Vite, adding the following line to App.tsx:
```
import * as window from '@tauri-apps/api/window'
```

will cause the React application to not initialize with the following error in the Dev console:

> [Error] Error: @vitejs/plugin-react can't detect preamble. Something is wrong. See https://github.com/vitejs/vite-plugin-react/pull/11#discussion_r430879201 	Module Code (App.tsx:8:166)

Removing the import line will allow the React app to initialize normally.  Note that "window" doesn't even get used, the import itself is enough to break things.

### Reproduction

Repository to reproduce is here:
https://github.com/jasonterando/demo-tauri-v2-window-issue

### Expected behavior

App starts without error.

### Full `tauri info` output

```text
yarn run v1.22.22
$ tauri info

[✘] Environment
    - OS: Linux Mint 21.3 X64
    ✔ webkit2gtk-4.1: 2.44.2
    ✘ rsvg2: not installed
      Visit https://tauri.app/v1/guides/getting-started/prerequisites to learn more about tauri prerequisites
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: 1.79.0-x86_64-unknown-linux-gnu (default)
    - node: 20.16.0
    - pnpm: 9.5.0
    - yarn: 1.22.22
    - npm: 10.8.1

[-] Packages
    - tauri [RUST]: 2.0.0-rc.1
    - tauri-build [RUST]: 2.0.0-rc.1
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-rc.2

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
Done in 1.94s.
```

### Stack trace

```text
n/a
```

**Comment by FabianLars** [comment]
Looks like it's tripping over the exact `window` name, maybe because it's also a native global variable 🤔 If you rename it to anything else (for example `windowApi`) it works so i assume it's not our fault.
