### ISSUE TITLE
[bug] the message sent by channel can not be traced by vue

### ISSUE THREAD

**Issue by Sakameeee** [tauri-apps/tauri#10530]
### Describe the bug

when I was using the channel to send downloading progress message to the frontend from rust, i was sure that the message was sent successfully and the value of refs was changed indeed for that i could see it in the console. But nothing changed on the webview.I mean the refs are not reactive. I tried to solve this problem for a long time but failed, and finnally I found that if i used event system the data could be reactive. Therefore, I guess there might be some problem with the channel like thread issues that make the message it send can not be traced by vue refs

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 126.0.2592.113
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.16.0
    - pnpm: 9.6.0
    - yarn: 1.22.19
    - npm: 9.7.2

[-] Packages
    - tauri [RUST]: 2.0.0-beta.25
    - tauri-build [RUST]: 2.0.0-beta.19
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.16
    - @tauri-apps/cli [NPM]: 2.0.0-beta.23

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:7777/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by FabianLars** [comment]
1) can you try again with the latest rc versions?
2) do you think you can come up with a minimal reproduction example for us to try?

**Comment by Sakameeee** [comment]
sorry for the late replay.
I just noticed that my project was using the beta version. because I migrated directly from 1.0, so I didn't notice the latest RC version. After switching to the RC version, the issue was resolved. 
This was a bad issue report, sorry :(
