### ISSUE TITLE
Run Compiled windows Tauri app - on windows docker

### ISSUE THREAD

**Issue by AyalaGol** [tauri-apps/tauri#10538]
### Describe the problem

Hi, 
I need to run compiled windows tauri app on container, 
so I used windows server core container, 
but then need to install each ingredient by myself : .net runtime, webview2 runtime.

### Describe the solution you'd like

my question - does Tauri has any ready docker image to run compiled app of Windows?

thanks.

**Comment by amrbashir** [comment]
We don't have any docker images for that, unfortunately, you'll need to make one. 

If you endup making one, make sure to contribute it to https://github.com/tauri-apps/awesome-tauri
