### ISSUE TITLE
[bug] 'IosVersionInvalid' when running 'tauri ios init'

### ISSUE THREAD

**Issue by fnschmidt** [tauri-apps/tauri#10543]
### Describe the bug

```
> tauri ios init

thread '<unnamed>' panicked at src/mobile/ios/mod.rs:141:62:
called `Result::unwrap()` on an `Err` value: IosVersionInvalid(MajorInvalid { version: "", source: ParseIntError { kind: Empty } })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Xcode 15.4 (iOS 17.5 platform installed)

Troubleshooting steps:
- `pnpm run tauri dev` works fine
- connecting an iOS device over USB
- reinstalling iOS 17.5 tools in Xcode
- reinstalling rustup aarch64-apple-ios[-sim]
- `-v` only shows two lines about an apple team certificate being found

### Reproduction

- `sh <(curl https://create.tauri.app/sh) --rc` (selected options: TS/JS > pnpm > Svelte > TS)
- `pnpm install`
- `pnpm tauri ios init`

### Expected behavior

The panic should not occur

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.6.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.16.0
    - pnpm: 9.0.4
    - yarn: 1.22.22
    - npm: 10.8.1

[-] Packages
    - tauri [RUST]: 2.0.0-rc.1
    - tauri-build [RUST]: 2.0.0-rc.1
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 1.5.14
    - @tauri-apps/api [NPM]: 2.0.0-rc.0
    - @tauri-apps/cli [NPM]: 2.0.0-rc.2

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

### Additional context

I tried using both the bash script and cargo create-tauri-app, the same issue occurs

**Comment by FabianLars** [comment]
This was fixed in #10533

As a workaround until the next release you can add this to tauri.conf.json

```json
"bundle": {
  "iOS": {
    "minimumSystemVersion": "13.0"
  }
}
```
