### ISSUE TITLE
[feat] `tauri migrate` shoud migrate main bin name to product name

### ISSUE THREAD

**Issue by anatawa12** [tauri-apps/tauri#10548]
### Describe the problem

#9375 removed renaming binary to product name specified in `Tauri.toml`.

However, this is not migrated with `tauri migrate` and unexpectedly broke user installed shortcuts

### Describe the solution you'd like

I think it's much better to migrate main bin name to product name in `tauri migrate` command.

I'm going to create issue for documentation.

**Comment by amrbashir** [comment]
Can you explain how #9375 broke your user shortcut? did you update from a version that was using tauri@beta?

We have code specifically for updating the shortcut upon updates to use the new bin name.

**Comment by anatawa12** [comment]
> did you update from a version that was using tauri@beta?

No, I'm migrating from tauri v1 to v2 rc.

> We have code specifically for updating the shortcut upon updates to use the new bin name.

At least for my case, app pinned onto task bar is still refering old (ProductName-based) exe name after installing with nsis installer.

**Comment by krlvi** [comment]
Hey @anatawa12, we are running into the same issue, I'm gonna try adding an option to get the compatible v1 behavior here https://github.com/gitbutlerapp/tauri/pull/1

**Comment by amrbashir** [comment]
fixed in https://github.com/tauri-apps/tauri/pull/10977
