### ISSUE TITLE
[bug]  IO error: Incorrect function. (os error 1): Incorrect function. (os error 1)

### ISSUE THREAD

**Issue by asuheel** [tauri-apps/tauri#10568]
### Describe the bug

I was following below link to setup tauri usign nextJs

[https://tauri.app/v1/guides/getting-started/setup/next-js](url)

Got below error

![image](https://github.com/user-attachments/assets/905d00d2-77bd-46f3-baa1-d3b4efaf90fa)

### Full `tauri info` output

```text
$ npm run tauri info

> my-app@0.1.0 tauri
> tauri info


[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 126.0.2592.113
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.11.1
    - npm: 10.2.4

[-] Packages
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 1.6.0

[-] App
```

**Comment by asuheel** [comment]
Any update on this issue?

**Comment by FabianLars** [comment]
Try running it outside of git bash in powershell or cmd.exe. Reinstalling git bash with the "Enable experimental support for pseudo console" option checked should also make it work.
