### ISSUE TITLE
[bug] [v2beta] [android] On android, fail to invoke command with ArrayBuffer as arg. 

### ISSUE THREAD

**Issue by aiueo13** [tauri-apps/tauri#10573]
### Describe the bug

(I am not good at English, so my writing may be strange.)

On android.
If invoke command with ArrayBuffer as the argument and received as tauri::ipc::Request<'_> on the rust side, ~~it is passed as an empty json of tauri::ipc::InvokeBody::Json instead of tauri::ipc::InvokeBody::Raw.~~ it is passed as tauri::ipc::InvokeBody::Json instead of tauri::ipc::InvokeBody::Raw.

### Reproduction

Set the following commands in Rust.
```
#[tauri::command]
fn test(request: tauri::ipc::Request<'_>) -> String {
    match request.body() {
        tauri::ipc::InvokeBody::Json(json) => format!("err: {json}"),
        tauri::ipc::InvokeBody::Raw(_) => format!("ok"),
    }
}
```

Next, invoke it on frontend as follows.
```
invoke("test", new Uint8Array([0, 1, 2]))
    .then(console.log)
    .catch(console.log)
```

Then, on macos (at least), it return “ok”.
But, on android, it return ~~"err: {}"~~ 'err: {“0”:0,”1”:1,”2”:2}'.
~~So, this means that an empty json is passed.~~
So, this means that the ipc request is passed as unexpected format.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.10.0
    - pnpm: 8.15.6
    - yarn: 1.22.21
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 2.0.0-beta.22
    - tauri-build [RUST]: 2.0.0-beta.17
    - wry [RUST]: 0.40.1
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 2.0.0-beta.20
    - @tauri-apps/api [NPM]: 2.0.0-beta.13
    - @tauri-apps/cli [NPM]: 2.0.0-beta.20

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

**Comment by tweidinger** [comment]
Can you please try to reproduce with the latest `2.0.0-rc` package versions?
Can you provide us with a minimal reproduction repository so we can figure out possible causes?

Are you working with the emulator or a real device?

**Comment by aiueo13** [comment]
Sorry for the delay in replying.

- The latest 2.0.0-rc fails in the same way.
- Repository is https://github.com/aiueo13/Tauri-issue-10573
- It, which is not the repository above, also fails in both Real Device (ReleaseBuild) and Emulator (DevBuild).

**Comment by aiueo13** [comment]
When you open the repository app, you can do so with a single button on the screen with the text ‘Do test’. When this button is pressed, the command is invoked and the result, whether it failed or succeeded, is displayed below the button.

At least, on MacOs (devBuild) it succeeded  as ‘Success'.
Oon Android (Emulator, Pixel_6_API_34, DevBuild) it failed as 'Failure: {“0”:0,”1”:1,”2”:2}'.  So, I said it return an empty json, but it was incorrect.


tauri info
```
[✔] Environment
    - OS: Mac OS 14.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.10.0
    - pnpm: 8.15.6
    - yarn: 1.22.21
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 2.0.0-rc.2
    - tauri-build [RUST]: 2.0.0-rc.2
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 2.0.0-beta.20
    - @tauri-apps/api [NPM]: 2.0.0-rc.0
    - @tauri-apps/cli [NPM]: 2.0.0-rc.3

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - bundler: Vite
```

**Comment by tweidinger** [comment]
Thanks for providing us with a repo and more information 👍 . Will reach out for triage (@lucasfernog 😁 ).

**Comment by lucasfernog** [comment]
On Android we can't use the custom protocol IPC mechanism (which allows you to use InvokeBody::Raw) because the [WebResourceRequest](https://developer.android.com/reference/android/webkit/WebResourceRequest) class do not give us the request body.
Same limitation exists on Linux (unless the `linux-ipc-protocol` feature is enabled).
In these two platforms, we serialize payloads by default so you'll always get a InvokeBody::Json
