### ISSUE TITLE
[bug] cannot get os infomation by plugin-os

### ISSUE THREAD

**Issue by wangxg422** [tauri-apps/tauri#10574]
### Describe the bug

When I use plugin-os to get the operating system information, an error occurs in js: `Cannot read properties of undefined (reading 'platform')`. In Rust, using plugin-os can get it normally. The front-end framework I use is solidjs.
![1](https://github.com/user-attachments/assets/fc1a0571-633c-43d7-8ff2-9dfec45f5bfb)

### Full `tauri info` output

```text
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'platform')
    at platform (index.js:35:49)
    at App.tsx:11:30
    at untrack (dev.js:516:12)
    at Object.fn (dev.js:541:22)
    at runComputation (dev.js:800:22)
    at updateComputation (dev.js:778:3)
    at runTop (dev.js:895:7)
    at runUserEffects (dev.js:1008:36)
    at dev.js:964:34
    at runUpdates (dev.js:912:17)
```

**Comment by wangxg422** [comment]
I add `.plugin(tauri_plugin_os::init())` to Rust,it works.

**Comment by amrbashir** [comment]
tauri plugins consist of two parts, the JS API package and the rust crate which must be initialized like you did
