### ISSUE TITLE
[feat] manually specify signtool.exe used by tauri

### ISSUE THREAD

**Issue by anatawa12** [tauri-apps/tauri#10583]
### Describe the problem

With eSigner CKA by SSL.com, it may fails to sign exe with x64 version of signtool.exe.

### Describe the solution you'd like

Therefore, I want to manually specify path to signtool.exe with environment variable.

### Alternatives considered

Use custom sign command but it requires signing tool to not have whitespace, which is not true (program Files contains whitespace) for signtool.
In addition, location of signtool is relatively PC-specific so I think it's not good to specify in tauri.conf.json.

**Comment by FabianLars** [comment]
> Use custom sign command but it requires signing tool to not have whitespace, which is not true (program Files contains whitespace) for signtool.

Escaped quotes should work, so `"signCommand": "\"C:/path/to/Sign Tool.exe\" some commands %1"`

>  In addition, location of signtool is relatively PC-specific so I think it's not good to specify in tauri.conf.json.

Well, an option to specify which signtool exe to use would have the same problem.

---

I don't think is something we will explicitly support and instead leave that to the existing signCommand config. Please reach out again if you can't make it work (for example if the escaped quotes don't work)

**Comment by anatawa12** [comment]
>>  Use custom sign command but it requires signing tool to not have whitespace, which is not true (program Files contains whitespace) for signtool.
> 
> Escaped quotes should work, so "signCommand": "\"C:/path/to/Sign Tool.exe\" some commands %1"

https://github.com/tauri-apps/tauri/blob/20be073bc41f13bb72c442a4d789d481be6bc951/tooling/bundler/src/bundle/windows/sign.rs#L138

escaped quote looks not working

> Well, an option to specify which signtool exe to use would have the same problem.

with envronment variable , there's no such a problem.

Copied from issue:
> Therefore, I want to manually specify path to signtool.exe with **environment variable**.
