### ISSUE TITLE
[feat] Ability to hide title bar

### ISSUE THREAD

**Issue by timuric** [tauri-apps/tauri#10584]
### Describe the problem

Ability to hide window title bar to create apps that hide on click away, apps like spotlight on macos
<img width="712" alt="image" src="https://github.com/user-attachments/assets/2d6e46e4-52b8-4ae2-bf7d-8c83ceedebc2">

Related discussion
https://github.com/tauri-apps/tauri/discussions/7587

### Describe the solution you'd like

add config to window to hide titlebar

### Alternatives considered

Guide for window customization: https://v2.tauri.app/plugin/window-customization/

**Comment by amrbashir** [comment]
you can set `decorations: false` when creating the window in your `tauri.conf.json` or programatically in Rust or Js. As for hide on click away, you will need to listen for focus events, and then hide the window and (on macOS hide the app).

- https://docs.rs/tauri/latest/tauri/struct.Builder.html#method.on_window_event
- https://docs.rs/tauri/latest/tauri/window/struct.Window.html#method.hide
- https://docs.rs/tauri/latest/x86_64-apple-darwin/tauri/struct.AppHandle.html#method.hide

**Comment by timuric** [comment]
@amrbashir thank you for the tip! Is there a solution for round corners?

**Comment by amrbashir** [comment]
if you're on v1, you can try using https://github.com/tauri-apps/window-vibrancy, if on v2, you can use either https://docs.rs/tauri/2.0.0-rc.2/tauri/window/struct.WindowBuilder.html#method.effects or https://beta.tauri.app/reference/config/#windoweffects which can do the same thing also. 

Keep in mind that the corner radius thing is macOS only.

You can get rounded corners on Windows 11, if you enable the [shadow](https://beta.tauri.app/reference/config/#shadow) of the window.

On all other platforms, just use a transparent window and round the corners using CSS.
