### ISSUE TITLE
[bug] maximized: true isn't working

### ISSUE THREAD

**Issue by omarshehab221** [tauri-apps/tauri#10597]
### Describe the bug

When setting `maximized` to `true` in `tauri.conf.json` the window doesn't get maximized. Although, [this issue](https://github.com/tauri-apps/tauri/issues/3215) from 3 years ago claims that it has been fixed.

### Reproduction

Set `maximized` to `true`

### Expected behavior

The window is expected to be maximized on startup

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 127.0.2651.98
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)        
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.18.0
    - yarn: 1.22.22
    - npm: 10.5.0
    - bun: 1.1.15

[-] Packages
    - tauri [RUST]: 2.0.0-rc.2
    - tauri-build [RUST]: 2.0.0-rc.2
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 2.0.0-rc.0
    - @tauri-apps/cli [NPM]: 2.0.0-rc.3

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../out
    - devUrl: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Webpack
```

**Comment by amrbashir** [comment]
I couldn't reproduce this, please provide a minimal repro

**Comment by omarshehab221** [comment]
@amrbashir For some reason it just worked on my main project while I was testing the minimal repo, which also worked. I think I was doing something wrong. Sorry for the trouble.

**Comment by amrbashir** [comment]
No worries
