### ISSUE TITLE
[bug]  missing `cargo:dev` instruction, please update tauri to latest: NotPresent

### ISSUE THREAD

**Issue by songjiachao** [tauri-apps/tauri#10591]
### Describe the bug

 missing `cargo:dev` instruction, please update tauri to latest: NotPresent

error: failed to run custom build command for `funapp v0.6.12 (C:\code\fun-family\app\desktop\src-tauri)`

Caused by:
  process didn't exit successfully: `C:\code\fun-family\app\desktop\src-tauri\target\debug\build\funapp-d8c1117c47784374\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rerun-if-changed=tauri.conf.json5
  cargo:rustc-check-cfg=cfg(desktop)
  cargo:rustc-cfg=desktop
  cargo:rustc-check-cfg=cfg(mobile)
  cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_APP_NAME=dev
  cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_PREFIX=com_fun

  --- stderr
  thread 'main' panicked at C:\Users\11091628\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-build-2.0.0-rc.2\src/lib.rs:395:6:
  missing `cargo:dev` instruction, please update tauri to latest: NotPresent
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

### Full `tauri info` output

```text
PS C:\code\fun-family\app\desktop> cargo tauri info

[✔] Environment
    - OS: Windows 10.0.22000 X64
    ✔ WebView2: 126.0.2592.113
    ✔ MSVC: Visual Studio 生成工具 2022
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.10.0
    - pnpm: 9.1.2
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 2.0.0-rc.2
    - tauri-build [RUST]: 2.0.0-rc.2
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 2.0.0-rc.3
    - @tauri-apps/api [NPM]: 2.0.0-beta.13
    - @tauri-apps/cli [NPM]: 2.0.0-rc.3

[-] App
    - build-type: bundle
    - CSP: object-src 'self' asset: http://asset.localhost; connect-src ipc: tauri: http: ws: https:; style-src 'unsafe-inline' 'self' https://fonts.googleapis.com; img-src  'self' asset: http://asset.localhost blob: data: https: http://api.iconify.design http://fun.vmic.xyz; frame-src https: asset: http://asset.localhost; default-src 'self' customprotocol: asset:; font-src https://fonts.gstatic.com 'self' asset: http://asset.localhost; script-src 'unsafe-eval' 'self'; media-src https://h5-inside.vmic.xyz/fun/assets/why-fun.mp4
    - frontendDist: ../dist
    - devUrl: http://127.0.0.1:1420/
    - framework: React (Next.js)
    - bundler: Vite
```

**Comment by amrbashir** [comment]
try running `cargo update` inside `src-tauri`, if doesn't work, please make a minimal repro.
