### ISSUE TITLE
[bug] Tauri-cli does not generate .sig files.

### ISSUE THREAD

**Issue by gusxodnjs** [tauri-apps/tauri#10606]
### Describe the bug

I've been using the @tauri-app/cli@2.0.0-beta.10 version so far.

I recently updated it to version 2.0.0-rc, and the sig file and latest.json have not been created since then.

Am I missing something important corrections?

From what I checked, it seems to be generated well up to 2.0.0-beta.15.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 18.18.2
    - yarn: 1.22.19
    - npm: 9.8.1

[-] Packages
    - tauri [RUST]: 2.0.0-rc.2
    - tauri-build [RUST]: 2.0.0-rc.2
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 2.0.0-beta.9
    - @tauri-apps/api [NPM]: 2.0.0-rc.0
    - @tauri-apps/cli [NPM]: 2.0.0-beta.15

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
✨  Done in 13.95s.
```

**Comment by tweidinger** [comment]
Please see the relevant documentation. https://v2.tauri.app/plugin/updater/#tauri-configuration
You need to specify `createUpdaterArtifacts` as `true` in your configuration to generate signature files.

**Comment by gusxodnjs** [comment]
@tweidinger Thank you, I have checked the contents and I have a question.
In previous versions, the msi and nsis compressed files and signature files were created in Windows environment, but the latest version does not. Is it okay to specify the paths of the msi and nsis files instead of the compressed files when updating?
- 1.0 ~ 2.0.0-beta ?
![image](https://github.com/user-attachments/assets/9c861c49-4230-4ef5-86c2-f6d5bf00ad9f)

- 2.0.0-beta ?, rc
![image](https://github.com/user-attachments/assets/4987e0c0-0a2f-4d4e-b5d1-d80e76d4b7df)
