### ISSUE TITLE
VIRUS (Trojan) reported for tauri default app on Win10 - Trojan:Win32/CryptInject!ml

### ISSUE THREAD

**Issue by nokola** [tauri-apps/tauri#1060]
**Describe the bug**
Windows Defender reports severe threat in tauri's sample app .exe: Trojan:Win32/CryptInject!ml
This is a ransomware trojan. Hopefully it's a false alarm.

**To Reproduce**
1. Clone tauri main branch on Win10 machine
2. Follow instructions in examples\communication\readme.md to build and run example app:
```
yarn
yarn build
```
3. Run the app in ./src-tauri/target/release/app.exe

**Expected behavior**
All OK

**Observed behavior**
Windows defender reports a virus in app.exe
Trojan:Win32/CryptInject!ml
More info: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fCryptInject!ml&threatid=2147760506

**Screenshots**
![image](https://user-images.githubusercontent.com/6869225/96394060-ef62af80-1175-11eb-9192-f028ed0a7a22.png)

**Platform and Versions (please complete the following information):**

OS:Microsoft Windows [Version 10.0.19041.572]
Node:v12.16.2
NPM: 6.14.8
Yarn: 1.22.10
Rustc: rustc 1.47.0 (18bf6b4f0 2020-10-07)

**Comment by nothingismagick** [comment]
This is troubling. I did a quick search, and it seems like Tauri is not the only project hit with this recently:

https://github.com/symfony/symfony/issues/38457

We will need to replicate this and track it down, perhaps @lucasfernog & @tensor-programming can try this on their windows boxes.

Might it have to do with the way that webview/webview is packaging and distributing webview2 right now?

**Comment by nothingismagick** [comment]
@nokola - can you please paste the results of `tauri info` here?

**Comment by nklayman** [comment]
I tried it myself and didn't get the virus report. Here is my `tauri info`:
```$ tauri info
[tauri]: running info

Operating System - Windows_NT(10.0.19041) - win32/x64
Microsoft Edge - 44.19041.423.0_neutral__8wekyb3d8bbwe

Node.js environment
  Node.js - 14.4.0
  tauri.js - 0.12.0

Rust environment
  rustc - 1.47.0
  cargo - 1.47.0
  tauri-bundler - 0.9.3

Global packages
  NPM - 6.14.5
  yarn - 1.22.4

App directory structure
/dist
/node_modules
/src-tauri

App
  tauri.rs - 0.9.2
  mode - no-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist
  devPath - ../dist
```
However, I have disabled windows defender from checking the folder where I built the app. I installed the MSI and it still didn't get the error though so I assume the defender rules would have caught that if there was an issue.

**Comment by nokola** [comment]
@nklayman what happens when you enable windows defender to scan the .msi folder or copy the msi to another folder that is scanned, then double-click the msi? I had similar setup like yours and found the issue after copying the msi to a different folder and running it from there. I actually got the issue with app.exe first, but the msi can also reproduce it.

**Comment by nokola** [comment]
> @nokola - can you please paste the results of `tauri info` here?

Unfortunately not yet - I reinstalled the OS to avoid potentially being ransomwared because at first I ran app.exe from a folder that was not scanned by Windows Defender. I didn't run "tauri info" initially, assuming it may be compromised. That's why I pasted only the node/npm/yarn/OS versions in the report.

I'll setup a VM and try reproducing again.

**Comment by nokola** [comment]
I **cannot** reproduce the issue on a new blank VM. Before I reimaged my machine, I copied the contents of the `communication` folder as .zip. Will unzip and test with those.
```
PS C:\Users\User\Documents\GitHub\tauri\tauri\examples\communication> yarn tauri info
yarn run v1.22.10
$ tauri info
[tauri]: running info

Operating System - Windows_NT(10.0.19041) - win32/x64
Microsoft Edge - 44.19041.423.0_neutral__8wekyb3d8bbwe

Node.js environment
  Node.js - 12.19.0
  tauri.js - 0.12.0

Rust environment
  rustc - 1.42.0
  cargo - 1.42.0
  tauri-bundler - 0.9.3

Global packages
  NPM - 6.14.8
  yarn - 1.22.10

App directory structure
/dist
/node_modules
/src-tauri

App
  tauri.rs - 0.9.2
  mode - no-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist
  devPath - ../dist
Done in 2.14s.
PS C:\Users\User\Documents\GitHub\tauri\tauri\examples\communication>
```

**Comment by nokola** [comment]
I found a copy of the app.exe that was reported with trojan. Ran it after getting latest windows updates and no trojan reported. 

Closing this issue because I assume it was Windows Defender mis-labelling a file.
If anyone wants my "bad" `communication` folder, please ping me and I'll share - 300MB compressed.

**Comment by nothingismagick** [comment]
ok, glad you couldn't reproduce. thanks for having the diligence to see this through, its really much appreciate.
