### ISSUE TITLE
[bug] Cannot bundle x86 on Mac M1

### ISSUE THREAD

**Issue by ofekd** [tauri-apps/tauri#10601]
### Describe the bug

App is built fine, executable is present at the target_triple directory. Also fails on Github Actions.

```shel
$ pnpm tauri build -- --target x86_64-apple-darwin
# ... build output
Bundling tauri-app.app (/Users/user/tauri-app/src-tauri/target/release/bundle/macos/tauri-app.app)
Error failed to bundle project: Failed to copy binary from "/Users/user/tauri-app/src-tauri/target/release/tauri-app": `"/Users/user/tauri-app/src-tauri/target/release/tauri-app" does not exist`
```

### Reproduction

This is just off of `tauri create`.

### Expected behavior

Bundle successfully

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.0.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 22.4.1
    - pnpm: 9.5.0
    - npm: 10.8.1

[-] Packages
    - tauri [RUST]: 2.0.0-rc.2
    - tauri-build [RUST]: 2.0.0-rc.2
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 2.0.0-rc.0
    - @tauri-apps/cli [NPM]: 2.0.0-rc.3

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by ofekd** [comment]
Solved -- this happened because the `--` I've been using prevented the `--target` command from being passed.

If someone googled their way to this issue, note that this currently is present in the CrabNebula Cloud docks (https://docs.crabnebula.dev/cloud/continuous-integration/) so do double-check your Github Action workflows.

**Comment by FabianLars** [comment]
> If someone googled their way to this issue, note that this currently is present in the CrabNebula Cloud docks (https://docs.crabnebula.dev/cloud/continuous-integration/) so do double-check your Github Action workflows.

They are using `npm` which is the only package manager that requires the extra `--` to make it forward the args to tauri. So the docs are correct but it may be nice to show that pnpm/yarn behave differently.

**Comment by ofekd** [comment]
Yes, my bad. I am so used to seeing `pnpm` everywhere that I missed it. Hope they'll clarify though.

**Comment by PJUllrich** [comment]
@FabianLars would it be possible to add a `bun` tab to the `Continues Integration -> Tauri v2 -> macos` section here with the correct code example? https://docs.crabnebula.dev/cloud/ci/tauri-v2-workflow/#macos

I also fell into that mistake to add `--` before the `--target` flag :D 

I'd contribute a doc change, but I can't find a repo for these particular docs. I'd be happy to create a PR if the docs are open-source somewhere though!

---

So, just for future reference and folks who google this error. This is how the command should look like with `bun`:

```yml
      - name: Install x86_64-apple-darwin for mac and build Tauri binaries
        if: matrix.os == 'macos-latest'
        run: |
          rustup target add x86_64-apple-darwin
          bun install
          bun run tauri build --verbose --target x86_64-apple-darwin
          bun run tauri build --verbose --target aarch64-apple-darwin
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
```

And this is the error you might receive if you add a `--` before the `--verbose`:

```
     Finished `release` profile [optimized] target(s) in 4m 33s
       Built application at: /Users/runner/work/my_app/my_app/src-tauri/target/release/my-app
    Bundling App Agent.app (/Users/runner/work/my_app/my_app/src-tauri/target/release/bundle/macos/App Agent.app)
failed to bundle project: Failed to copy binary from "/Users/runner/work/my_app/my_app/src-tauri/target/release/my-app": `"/Users/runner/work/my_app/my_app/src-tauri/target/release/my-app" does not exist`
       Error failed to bundle project: Failed to copy binary from "/Users/runner/work/my_app/my_app/src-tauri/target/release/my-app": `"/Users/runner/work/my_app/my_app/src-tauri/target/release/my-app" does not exist`
error: script "tauri" exited with code 1
```

**Comment by FabianLars** [comment]
the docs are closed source (don't ask me why, idk). will update them to include bun :)
