### ISSUE TITLE
Headless Tauri

### ISSUE THREAD

**Issue by Wallacy** [tauri-apps/tauri#1061]
Hello,

So, i was reading the [feat(RFC): File RFC-0002 - deno](https://github.com/tauri-apps/rfcs/pull/3) and then i think that maybe a good opportunity to something I little bit more ambitious, and also more convenient to devs.

Basically, my idea is to make a Headless version of the Tauri, capable to run common javascript over webview, but without any GUI. I came across this idea last month, when i was making a build/install script for one of our company app. My first version was just a few small javascript code to understand the problem, but at end of the day I needed to create a bash script because portability and a small footprint. Also because make an install script dependent to another runtime like node is not a good idea.

The thing is: Tauri has a small footprint (600kb) and can do everything that we can do in bash (or pretty close of that). Javascript is more convenient than bash script, we can handle files and we can execute commands using Tauri-API only. We can even do a native httpRequest that bash cannot!

I think a headless version of the Tauri (a new config?) can help to make several CLIs and generals scripts. Also can be used to make very secure service-like app. (Tauri has a good security model)

The diference from the [RFC-0002](https://github.com/tauri-apps/rfcs/pull/3), is that we dont need the "full" Deno runtime, sometimes we just need to run some javascript code, and despite the fact that is not "portable" as bash, is more convenient, and the rust/native side can do some assistance to failback and tell the user that they need to use a Deno based cli or ask to download the tauri-deno binary like suggested on the RFC 0002.

The point is: We already have most of the tools do do a cli/script using javascript based on the current tauri-api, except the fact that current the executor always load a webview gui. And a Headless version should close that gap.

With that in mind: We will have a regular Tauri App for Desktop / Mobile Gui App [1.5+ MB ], a Tauri Deno for full applications without GUI,[ 12+ MB ] and a Headless Tauri [ < 1MB ], to basic scripting and cross-platform cli using javascript.

Todays, some devs uses python and perl to make a non-bash and cross-platform scripts, but in my experience thats is even less portable, and less convenient than the proposed solution.

Best,

**Comment by nothingismagick** [comment]
Really nice idea, and something I could see a lot of utility for. If you ditch css and js and html and images - as well as the webview backdrop in rust, and you are careful with the app icon and you do some compile flag optimization, I would venture that you can get to something closer to under 100 KB for the headless tauri.

**Comment by Wallacy** [comment]
FWIW: On the `tauri.conf.json` we can make a option `headless: true` to use default OS render engine and get a small footprint, and a `headless: quickjs` to support [quickjs](https://github.com/theduke/quickjs-rs) runtime and add ~800kb to the bundle! In this way, we get a truly cross-platform headless build that can run even in limited IoT devices and less than 1mb!

**Comment by nothingismagick** [comment]
yeah - the quickjs sounds awesome and Fabrice is a legend, but the compilation requirements for windows are a little iffy and tough to require: https://github.com/theduke/quickjs-rs#windows-support

And getting tauri to run on non-linux IoT is likely to be less than trivial. (I am looking at the esp32 here, and anything that won't support std::IO ...)

**Comment by nothingismagick** [comment]
@Wallacy - How would you feel about writing up an RFC for this new mode? If you like we could also write it together with you as author. Ping me on the discord server if you have some time and we can spec it out.

**Comment by virtualgraham** [comment]
I would be much happier seeing the current version of Tauri working production ready and bug free, which it is far from being the case, than seeing efforts being invested in endeavors such as these.

**Comment by Wallacy** [comment]
> yeah - the quickjs sounds awesome and Fabrice is a legend, but the compilation requirements for windows are a little iffy and tough to require: https://github.com/theduke/quickjs-rs#windows-support
> 
> And getting tauri to run on non-linux IoT is likely to be less than trivial. (I am looking at the esp32 here, and anything that won't support std::IO ...)

The quickjs only makes sense to linux btw; On OSX and Windows you will always have a webview support.

**Comment by Wallacy** [comment]
> @Wallacy - How would you feel about writing up an RFC for this new mode? If you like we could also write it together with you as author. Ping me on the discord server if you have some time and we can spec it out.

Okay, i will do that.

**Comment by nklayman** [comment]
Aren't there also plans to allow Deno apps to be packaged with the Tauri bundler? What would be the difference between that and 'headless Tauri'?

**Comment by nothingismagick** [comment]
@virtualgraham - you are very right, but just because there is an RFC or that someone from the community is interested in extending tauri does not mean that we are unconcerned about reaching feature parity across platforms with reliable stability.

**Comment by nothingismagick** [comment]
@nklayman - a headless tauri from my perspective would be a way to leverage our bundler to make daemon-type services and CLI applications.

**Comment by nklayman** [comment]
I still feel like that would be the same as packaging a Deno application. Am I missing something?

**Comment by Wallacy** [comment]
> I still feel like that would be the same as packaging a Deno application. Am I missing something?

Mostly bundle size. Theres a path to improve the security too, as Tauri plans to do a Frida-based harness for Post-Binary Analysis and already have other Security Features; Thats nice for services;

Deno is a much bigger runtime. And is not really stable.

**Comment by nklayman** [comment]
Ok so the main difference is you'd be using a system-provided runtime (or one of the custom ones mention) instead of shipping Deno? If so then I think I understand now.

**Comment by virtualgraham** [comment]
@Wallacy Using webview to achieve what node and deno already do would require a much more extensive API connecting the javascript runtime to system resources. For example listening to ports, file streaming, etc. These dont exist fully yet, so this puts Tauri in a position of being worse than "not really stable" since these parts havnt been developed and debugged yet.

**Comment by nklayman** [comment]
Ok we've kinda done this on accident by adding support for the window `visible` property (this will be available in the next release). If that is set to false, no window will show, but the webview will still execute any javascript you give it. Can this issue be closed now?

**Comment by nothingismagick** [comment]
Agreed, closing.

**Comment by Wallacy** [comment]
FWIW:
Before was just some curiosity, but today i try to that for real. On one product that we are building...

The problem is: If i install tauri on any VM ... now i need to install all X11 and other interface things... And at end of the day cannot work without display... So, no, theres no Headless Tauri, just some "windowless" Tauri...

**Comment by amrbashir** [comment]
@Wallacy checkout out the webdriver testing guide on our site https://tauri.studio/docs/testing/webdriver/introduction and you can find an example of settingup ci here https://tauri.studio/docs/testing/webdriver/ci

**Comment by Wallacy** [comment]
Thanks @amrbashir ,

Yes, its totally possible to run headless aplicativos using xvfb. I did that for chrome and others already. And just tested using tauri this morning and worked. I was not aware of this webdriver, but i will look anyway.

But my "problem" (its not really a big deal) is when i ship de .deb, he needs almost 1GiB of dependencies on Ubuntu 20.04 and 600MiB on Ubuntu 22.04 to run.... Thats "break" the idea to have a lightweight runtime to me. Okay, for distributions that already run desktop applications thats will not be a problem...

But thats okay, i can live with that...

**Comment by lucasfernog** [comment]
Our CI uses xvfb-run for benchmarks and Rust integration tests too :)
