### ISSUE TITLE
[bug] [windows] [Edge/WebView2] DevTools theme gets initialized incorrectly

### ISSUE THREAD

**Issue by hansSchall** [tauri-apps/tauri#10629]
### Describe the bug

Disclaimer: This is NOT an issue with system theme detection or theme preference storage. The theme selector correctly remembers the last selection and after clicking on any option everything works fine for the current session. 

When opening the DevTools, the theme used looks like this:

![Screenshot 2024-08-14 203154](https://github.com/user-attachments/assets/4bf1d3e7-208f-4e7c-ac51-ec0e1f9819c1)

The theme used looks like the default light at first, but as you can see in the screenshot, it contains some white-text-on-white-background issues.

Most parts of the UI use the default light theme, which is incorrect when set to `dark mode` or `system preference` (on dark mode systems). Only some parts (like the white text in the screenshot) use the correct colors.

The Edge browser DevTools are not affected.

The bug does not arrise from a specific tauri version, it even occurrs on binaries built ~half a year ago and back then there were no issues

### Expected behavior

Correct theme is used

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 127.0.2651.98
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.12.2
    - pnpm: 9.7.1
    - yarn: 1.22.22
    - npm: 10.5.0

[-] Packages
    - tauri [RUST]: 1.7.1
    - tauri-build [RUST]: 1.5.3
    - wry [RUST]: 0.24.10
    - tao [RUST]: 0.16.9
    - tauri-cli [RUST]: 1.6.0
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 1.6.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ./dist
    - devPath: http://localhost/
```

**Comment by ParkerTonra** [comment]
![image](https://github.com/user-attachments/assets/79f2020e-4d5c-44ec-89ca-be79a0750080)

I'm having the same issue as well.  The Theme is set to Dark+ but appears white.  I can set it to dark + again and this fixes the issue temporarily, but when I reopen the dev tools it appears white again.

**Comment by S1lander** [comment]
Having the same issue here (on Windows).

**Comment by june07** [comment]
See https://github.com/june07/nimv3/issues/10#issuecomment-2268321317 for a fix. I believe this is the same issue.

**Comment by S1lander** [comment]
Any updates on this? It's really annoying having to click through the settings to get the dark theme working.

**Comment by YossiCohen** [comment]
Found a workaround (in above closed bug):

1. Open Settings
2. Uncheck Match Microsoft Edge color scheme
3. Set Theme to Dark+ (Default)

**Comment by FabianLars** [comment]
I don't think we can do anything on our end here so please use the fix (or "workaround") above.

**Comment by S1lander** [comment]
> Found a workaround (in above closed bug):
> 
> 1. Open Settings
> 2. Uncheck Match Microsoft Edge color scheme
> 3. Set Theme to Dark+ (Default)

Yes this also fixed it for me. Here's a video tutorial btw:
https://youtu.be/jQGllcddnY4?si=yNrCwepkLFh_WSk2
