### ISSUE TITLE
【紧急‼️】启动win7 出现报错， [bug] 丢失 api-ms-win-core-winrt-l1-1-0.dll 文件通常与 Windows 系统文件损坏或缺失有关

### ISSUE THREAD

**Issue by bianbiandashen** [tauri-apps/tauri#10624]
### Describe the bug

启动win7 出现报错， [bug] 丢失 api-ms-win-core-winrt-l1-1-0.dll 文件通常与 Windows 系统文件损坏或缺失有关

### Expected behavior

启动win7 出现报错， [bug] 丢失 api-ms-win-core-winrt-l1-1-0.dll 文件通常与 Windows 系统文件损坏或缺失有关

### Full `tauri info` output

```text
启动win7 出现报错， [bug] 丢失 api-ms-win-core-winrt-l1-1-0.dll 文件通常与 Windows 系统文件损坏或缺失有关
```

### Stack trace

```text
启动win7 出现报错， [bug] 丢失 api-ms-win-core-winrt-l1-1-0.dll 文件通常与 Windows 系统文件损坏或缺失有关
```

### Additional context

启动win7 出现报错， [bug] 丢失 api-ms-win-core-winrt-l1-1-0.dll 文件通常与 Windows 系统文件损坏或缺失有关

**Comment by FabianLars** [comment]
Can you try building your app with Rust version 1.75 or below (the last version to properly support windows 7)?
If that doesn't help, please try this: https://github.com/tauri-apps/tauri/issues/6800#issuecomment-1675762905.
If that also doesn't help, please try your app on another windows 7 machine/VM to confirm whether it's a problem with the app or the specific system.

**Comment by bianbiandashen** [comment]
> Can you try building your app with Rust version 1.75 or below (the last version to properly support windows 7)? If that doesn't help, please try this: [#6800 (comment)](https://github.com/tauri-apps/tauri/issues/6800#issuecomment-1675762905). If that also doesn't help, please try your app on another windows 7 machine/VM to confirm whether it's a problem with the app or the specific system.





How to solve this problem On Win7 computers, we are now using dichotomy to find problems and hope to give some suggestions

**Comment by bianbiandashen** [comment]
How to solve this problem On Win7 computers, we are now using dichotomy to find problems and hope to give some suggestions

**Comment by bianbiandashen** [comment]
> ### Describe the bug
> 启动win7 出现报错， [bug] 丢失 api-ms-win-core-winrt-l1-1-0.dll 文件通常与 Windows 系统文件损坏或缺失有关
> 
> ### Reproduction
> _No response_
> 
> ### Expected behavior
> 启动win7 出现报错， [bug] 丢失 api-ms-win-core-winrt-l1-1-0.dll 文件通常与 Windows 系统文件损坏或缺失有关
> 
> ### Full `tauri info` output
> ```
> 启动win7 出现报错， [bug] 丢失 api-ms-win-core-winrt-l1-1-0.dll 文件通常与 Windows 系统文件损坏或缺失有关
> ```
> 
> ### Stack trace
> ```
> 启动win7 出现报错， [bug] 丢失 api-ms-win-core-winrt-l1-1-0.dll 文件通常与 Windows 系统文件损坏或缺失有关
> ```
> 
> ### Additional context
> 启动win7 出现报错， [bug] 丢失 api-ms-win-core-winrt-l1-1-0.dll 文件通常与 Windows 系统文件损坏或缺失有关

How to solve this problem On Win7 computers, we are now using dichotomy to find problems and hope to give some suggestions

**Comment by FabianLars** [comment]
Did you try my 2 suggestions (building with rust 1.75 and the linked comment)?

If both don't help, then _maybe_ it's something app specific in which case i'd like you to check if it happens with a new `create-tauri-app` project too.

**Comment by bianbiandashen** [comment]
[package]
name = "electronic-print"
version = "0.0.2"
edition = "2021"
rust-version = "1.60"

categories = [
    "os",
    "os::windows-apis"
]

[dependencies]
tauri = { version = "1.3", features = [ "window-data-url", "shell-all", "http-all", "window-all", "fs-all"] }
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.18"
tungstenite = "0.20"
reqwest = { version = "0.11", features = ["json"] }
futures-util = "0.3" 
base64 = "0.21.2"
log = "0.4"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simple_logger = "1.16"
parking_lot = "0.12"
open = "3.0"
[build-dependencies]
tauri-build = { version = "1.3", features = [] }

[features]
custom-protocol = ["tauri/custom-protocol"]

[package.metadata.bundle.macos]
universal = true

The problem was solved through the above tauri.config.json configuration (win7 packaging)
