### ISSUE TITLE
[bug] [tauri v2][iOS] Error sending request for url (http://127.0.0.1:1430). Can't start app on iOS Simulator

### ISSUE THREAD

**Issue by rtmotiondev** [tauri-apps/tauri#10635]
### Describe the bug

I'm no longer able to start the app on the iOS simulator after deploying it to a real device.  Starting the app shows:  **Error sending request for url (http://127.0.0.1:1430).** I tried to clean the build directory in xcode but no luck.  Also, tried to specify the host and port of the dev server and I get the same error. The app still deploys and starts fine on a real device.

npm run tauri ios dev -- --host 127.0.0.1 --port 1430

```
Deploying app to device...
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=4):
Simulator device failed to launch app.relativemotion.
Underlying error (domain=FBSOpenApplicationServiceErrorDomain, code=4):
	The request to open "app.relativemotion" failed.
    Error Failed to deploy app to simulator: command ["xcrun", "simctl", "launch", "50603FDD-6E20-483B-ACDA-6279C832CE04", "app.relativemotion"] exited with code 4
```

tauri.conf.json
```

  "build": {
    "beforeDevCommand": {
      "script": "npm run dev",
      "wait": true
    },
    "beforeBuildCommand": {
      "script": "npm run build",
      "wait": true
    },
    "beforeBundleCommand": "",
    "frontendDist": "../src"
  },
```

### Expected behavior

Able to start the app on the iOS Simulator.

### Full `tauri info` output

```text
> tauri info


[✔] Environment
    - OS: Mac OS 14.6.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.11.0
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-rc.2
    - tauri-build [RUST]: 2.0.0-rc.2
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 2.0.0-rc.0
    - @tauri-apps/cli [NPM]: 2.0.0-rc.3

[-] App
    - build-type: bundle
    - CSP:
    - frontendDist: ../src
    - bundler: Webpack

[-] iOS
    - Developer Teams: <Removed>
```

**Comment by rtmotiondev** [comment]
A little bit more context. For some reason as described above, the command **xcrun simctl launch 4D80B92E-787A-4EB4-BDB0-A088F9AD59DA app.relativemotion** fails which causes **npm run tauri ios dev** to exit but while that command runs I can see that the built-in dev server is started and listening on the correct host and port. The previous app built on the simulator now works at least until **ios dev** fails which closes the built-in dev server.

Not sure if this is a tauri issue or some weird thing on xcode/ios simulator. I've tried different suggestions but none worked so far.

- Closed and reopened simulator.
- Reset Simulator Device.
- Erased simulator contents.
- Rebooted macos

**Comment by rtmotiondev** [comment]
Clearing gen/apple and re-running **npm run tauri ios init** fixes the issue.

**Comment by kaidegit** [comment]
a `_` in package name(`identifier` in `tauri.conf.json`) may cause this problem?

On iOS side, `_` would be replaced by `-` in some place, for example, in `project.yml`. And app would be lanched via cmd that using `-`. But some place(`project.pbxproj`) may not be replaced, which cause the package name is using `_`, and cause lanuch failure?

**Comment by adamtmorgan** [comment]
@kaidegit Just wanted to say thanks for mentioning this here; I was using `_` in my package name and replacing it as you suggested fixed my issues.
