### ISSUE TITLE
[bug] flagged as viruses by Windows Defender.

### ISSUE THREAD

**Issue by will5933** [tauri-apps/tauri#10649]
### Describe the bug

Recently, the installation packages for my Tauri application have been consistently flagged as viruses by Windows Defender, but I'm certain there are no viruses in my application. So what's going on here?
最近构建的 tauri 应用安装包总是会被 Windows Defender 当作病毒，但我可以肯定我的应用中没有病毒？所有这到底怎么回事？😭

![图片](https://github.com/user-attachments/assets/24a9a8ff-788a-4963-93e8-132a1b96dfc8)

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 127.0.2651.98
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)

[-] Packages
    - tauri [RUST]: 2.0.0-rc.2
    - tauri-build [RUST]: 2.0.0-rc.2
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 2.0.0-rc.1
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-rc.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../src
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by will5933** [comment]
Not installation packages, but exe binary files.
不是安装包，是exe二进制文件，说错了

**Comment by FabianLars** [comment]
False positives are tracked here https://github.com/tauri-apps/tauri/issues/2486 (and on discord) - right now we can only ask you to submit your app as a false positive here https://www.microsoft.com/en-us/wdsi/filesubmission
