### ISSUE TITLE
[bug] `window.__TAURI_PLUGIN_CLIPBOARD_MANAGER__ ` Unedfined

### ISSUE THREAD

**Issue by will5933** [tauri-apps/tauri#10646]
### Describe the bug

Is this a documentation error? 😵
这是文档错误吗？😵

![图片](https://github.com/user-attachments/assets/68198786-fd20-4c32-9302-5f0c49ba03a8)

![图片](https://github.com/user-attachments/assets/978e7aa7-7038-40d9-a261-805b061ee54d)

### Full `tauri info` output

```
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 127.0.2651.98
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)

[-] Packages
    - tauri [RUST]: 2.0.0-rc.2
    - tauri-build [RUST]: 2.0.0-rc.2
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 2.0.0-rc.1
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-rc.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../src
```

**Comment by FabianLars** [comment]
Already fixed in https://github.com/tauri-apps/plugins-workspace/pull/1630 and will be released once https://github.com/tauri-apps/plugins-workspace/pull/1616 was merged. Thanks for the report.
