### ISSUE TITLE
[bug] Redo and undo menus do not work in a Windows 10

### ISSUE THREAD

**Issue by gusxodnjs** [tauri-apps/tauri#10694]
### Describe the bug

I created redo, undo with PredefinedMenuItem. It doesn't work when I click and run the generated menu.

- macos

https://github.com/user-attachments/assets/712919ef-afc5-4b76-88ae-7589fa059b72

- windows

https://github.com/user-attachments/assets/c1b2e5ee-6273-4050-8937-b274f32d5017

### Reproduction

https://github.com/gusxodnjs/tauri-issues/tree/bug/menu

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 127.0.2651.105
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.16.0
    - yarn: 1.22.22
    - npm: 10.8.1

[-] Packages
    - tauri [RUST]: 2.0.0-rc.3
    - tauri-build [RUST]: 2.0.0-rc.3
    - wry [RUST]: 0.42.0
    - tao [RUST]: 0.29.0
    - @tauri-apps/api [NPM]: 2.0.0-rc.0
    - @tauri-apps/cli [NPM]: 2.0.0-rc.3

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by amrbashir** [comment]
That is expected and documented https://docs.rs/tauri/2.0.0-rc.5/tauri/menu/struct.PredefinedMenuItem.html#platform-specific-1
