### ISSUE TITLE
[bug] event.payload is empty for "tauri://drag-leave"

### ISSUE THREAD

**Issue by lendle** [tauri-apps/tauri#10697]
### Describe the bug

When I have an event listener for tauri://drag-leave, event.payload is null, but I would expect it to be `{type: 'leave'}` based on the implementation of [DragDropEvent](https://github.com/tauri-apps/tauri/blob/086271b73e8d1b24de2aa478a1421924bfc1218b/tooling/api/src/webview.ts#L36).

### Reproduction

I'm in a sveltekit app, I have a component with 

```
	function handleDragEvent(event: Event<DragDropEvent>) {
		if (!event.payload) {
			console.log({ event });
		}
	}

	onMount(() => {
		const unlistenPromises = [
			TauriEvent.DRAG_DROP,
			TauriEvent.DRAG_ENTER,
			TauriEvent.DRAG_LEAVE,
			TauriEvent.DRAG_OVER
		].map((event) => listen<DragDropEvent>(event, handleDragEvent));

		return () => {
			Promise.allSettled(unlistenPromises.map((p) => p.then((f) => f())));
		};
	});
```

When I drag files over the tauri window and then out, I get logs showing event.payload is null: `{event: {event: "tauri://drag-leave", payload: null, id: 378}}`

### Expected behavior

[DragDropEvent](https://github.com/tauri-apps/tauri/blob/086271b73e8d1b24de2aa478a1421924bfc1218b/tooling/api/src/webview.ts#L36) is implemented as
```
type DragDropEvent = {
    type: 'enter';
    paths: string[];
    position: PhysicalPosition;
} | {
    type: 'over';
    position: PhysicalPosition;
} | {
    type: 'drop';
    paths: string[];
    position: PhysicalPosition;
} | {
    type: 'leave';
};
```

So I expected event.payload to be `{type: 'leave'}` rather than null.

### Full `tauri info` output

```text
> tauri info


[⚠] Environment
    - OS: Mac OS 14.3.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10) (Homebrew)
    ✔ cargo: 1.79.0
    ⚠ rustup: not installed!
      If you have rust installed some other way, we recommend uninstalling it
      then use rustup instead. Visit https://rustup.rs/
    ⚠ Rust toolchain: couldn't be detected!
      Maybe you don't have rustup installed? if so, Visit https://rustup.rs/
    - node: 22.5.1
    - npm: 10.8.2

[-] Packages
    - tauri [RUST]: 2.0.0-rc.4
    - tauri-build [RUST]: 2.0.0-rc.4
    - wry [RUST]: 0.42.0
    - tao [RUST]: 0.29.0
    - @tauri-apps/api [NPM]: 2.0.0-rc.2
    - @tauri-apps/cli [NPM]: 2.0.0-rc.5

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

**Comment by amrbashir** [comment]
`tauri://drag-leave` doesn't have any data included which is why it is empty, `{type: 'leave'}` is only emitted when using `WebviewWindow.onDragDropEvent`, see this implementation https://github.com/tauri-apps/tauri/blob/086271b73e8d1b24de2aa478a1421924bfc1218b/tooling/api/src/webview.ts#L593-L599
