### ISSUE TITLE
Tauri presents issues when searching in Google, and youtube

### ISSUE THREAD

**Issue by TheFern2** [tauri-apps/tauri#1070]
I realize this is an early project but searching on YouTube for `Tauri` by itself yields all kinds of results from Astronomy, World of Warcraft, Screen Protector, Animals.

Searching `tauri react` brings up a channel called tauri reacts.

I appreciate what the project is doing but having picked a name that is hard to search for might become a significant issue for new adoption. I like the name btw but is hard to search for information.

**Comment by nklayman** [comment]
There are few names that won't have existing results, and we don't plan on changing the name, it would be more work than it's worth. Eventually, we hope to be the number 1 result for `tauri`, which I believe is an attainable goal as there isn't any major competitor, just a few small things. For now, searching for `tauri apps` on Google or Youtube returns this project, so try using that.

**Comment by TheFern2** [comment]
I understand it isn't always easy to change names. I do agree is showing less because is new, will definitely change in the future if there is higher adoption. As I see it is on a good path to overtake electron easily.

**Comment by nothingismagick** [comment]
Thanks for the feedback. We have changed names several times, but are not going to change it again for better marketing opportunities. I wager, if you were to google `electron` - that you probably wouldn't find the web-app framework. And that is ok. I suppose, if we were a fortune 500 company, that it would be a different matter - but we are a niche product in the pure and open source industry. Maybe it is oversight, maybe it is wrong, but we are playing a different game and are not interested in the benefits that market adoption would bring us. Should you decide to drop 200 million euros on the Tauri project, then maybe we could reinvestigate the situation. But right now, the only thing I care about is that we get to a stable beta and can afford an external audit. Until that happens, google results are not only meaningless, but also contraproductive.

**Comment by TheFern2** [comment]
Thanks both for the response, I didn't think you'd change the name and that's cool, wasn't expecting a change. I wouldn't say Tauri is just a niche product only because is being marketed as foss. I say this because the other choice for cross platform bundler produces a huge binary + once installed it uses an incredible amount of system resources. So people will use it regardless if they care for purism or foss because is a better choice and smaller binary.

For electron searches, if you do `electron tutorial` you'll get a nice result though. And that's what most people trying to learn a new technology search for. 

Sorry you lost me at Euros, I only speak pesos or dollars. 😁 Looking forward to the beta version. I'm already impressed by the small binary sizes.
