### ISSUE TITLE
[bug] Tauri 2 on Android: "This app was build for an older version of Android"

### ISSUE THREAD

**Issue by louis993546** [tauri-apps/tauri#10712]
### Describe the bug

Installation of a fresh Tauri 2 template app, triggers this pop-up on modern Android devices:

<img src="https://github.com/user-attachments/assets/aa62a351-4ead-4feb-a11f-aae0c87bbf12" width="360" alt="Screenshot of an Android app, in which it has a pop-up titled 'tauri-app', and description of 'This app was build for an older version of Android. It might not work properly and doesn't include the latest security and privacy protections. Check for an update, or contact the app's developer.'" />

### Reproduction

1. Create a new Tauri 2 project
2. `${package manager} run tauri android dev`

### Expected behavior

There should not be an "older version of Android" popup

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.6.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.9.0
    - yarn: 1.22.19
    - npm: 10.1.0
    - bun: 1.1.25

[-] Packages
    - tauri [RUST]: 2.0.0-rc.5
    - tauri-build [RUST]: 2.0.0-rc.5
    - wry [RUST]: 0.42.0
    - tao [RUST]: 0.29.0
    - @tauri-apps/api [NPM]: 2.0.0-rc.2
    - @tauri-apps/cli [NPM]: 2.0.0-rc.6

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: SolidJS
    - bundler: Vite

[-] iOS
    - Developer Teams: (redacted)
```

### Additional context

Looks like https://github.com/tauri-apps/tauri/pull/10558 accidentally removed `targetSdk` for the Android Application.

See the 2nd part of this answer: https://stackoverflow.com/a/75280536

There should still be `targetSdk = 34` in the Android block
<img width="600" alt="Screenshot 2024-08-21 at 13 44 28" src="https://github.com/user-attachments/assets/9953d43c-e3f6-415c-8732-d0fd2bf8101b">

**Comment by ishaan26** [comment]
As mentioned, adding `targetSdk = 34` to `src-tauri/gen/android/app/build.gradle.kts` -> `android { defaultConfig { ... } }` fixes the issue for me.
