### ISSUE TITLE
[bug] can't connect to tauri.localhost

### ISSUE THREAD

**Issue by seven1986** [tauri-apps/tauri#10745]
### Describe the bug

![image](https://github.com/user-attachments/assets/17d25988-a527-4044-b072-a9815d2f8758)

When I exec **npm run tauri dev** it's fine , however, my angular project is mutil language version, so as the screenshot shows, it will build the mutile language folder, and the entry command is **node proxy-server.mjs**

how can I use Tauri build a release version work?

### Full `tauri info` output

```text
can't connect to tauri.localhost
```

**Comment by amrbashir** [comment]
I am not an Angular developer and I don't know much about its i18n solutios but the screenshot you posted, shows you are using `express` with Node.js, Tauri doesn't have include Node.js in your binary and so it can't run this express server. 

Think of tauri app as just a browser window that will be served HTML/CSS/JS files only without any Node.js files. 

You'll need to rethink how you want to make your app multi language. There is two ways I can recommend:
1. Move your language specifics strings out of your compiled HTML into a JSON file for example (or multiple JSON files) and switch between languages when loading your main `index.html` file. I am not sure about Angular but vue has a client-only i18n framework https://vue-i18n.intlify.dev that kinda handles this for your.
2. Compile a different version of your app for each language, pointing each app build at one the directories under `dist/app/browser`

**Comment by seven1986** [comment]
thanks for your solution, I will try
