### ISSUE TITLE
[feat] Add maintainer field to Tauri configuration

### ISSUE THREAD

**Issue by spacey-sooty** [tauri-apps/tauri#10777]
### Describe the problem

When installing debs build by Tauri I get a warning:
```
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 2365 package 'choreo':
 missing 'Maintainer' field
dpkg: warning: parsing file '/var/lib/dpkg/tmp.ci/control' near line 11 package 'choreo':
 missing 'Maintainer' field
```

### Describe the solution you'd like

A solution to this would be adding a maintainer field to the Tauri configuration which can then be used in the build to add a maintainer to the package.

**Comment by lucasfernog** [comment]
@spacey-sooty the Maintainer field comes from your Cargo.toml package > authors value: https://github.com/tauri-apps/tauri/blob/0d2efd9ff43b962f96950788b1461086302713b4/Cargo.toml#L38
can you double check if that's set? we should at least fallback to the "publisher" value

**Comment by spacey-sooty** [comment]
That value was not set, that would be the issue thanks! I couldn't find documentation for this at all? that might be nice to have.
