### ISSUE TITLE
[bug] Can't use Window.getByLabel() after migrating from tauri 2.0 beta

### ISSUE THREAD

**Issue by Omicrxn** [tauri-apps/tauri#10801]
### Describe the bug

After migrating from the beta i get the following error after reaching a point i call Window.getByLable('main')
<img width="794" alt="image" src="https://github.com/user-attachments/assets/da1e7e70-f91d-490a-9f60-88c5384f880f">

I also get this error in the terminal: `RemoteLayerTreeDrawingAreaProxyMac::scheduleDisplayLink(): page has no displayID` 

for reference here is how i use the `getByLabel()`
`const uWindow = await Webview.getByLabel('main');`

I also tried with window and webviewWindow just in case but didn't work. However it worked on the beta.

I followed the migration guide from beta to RC.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.5.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 22.5.1
    - pnpm: 8.15.1
    - yarn: 1.22.19
    - npm: 10.8.2

[-] Packages
    - tauri [RUST]: 2.0.0-rc.2
    - tauri-build [RUST]: 2.0.0-rc.2
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 1.6.1
    - @tauri-apps/api [NPM]: 2.0.0-rc.3
    - @tauri-apps/cli [NPM]: 2.0.0-rc.7

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: *private sorry*
    - devUrl: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Can you update `tauri` in cargo.toml to the latest available version? If you didn't lock the version with `=` running `cargo update tauri` should work for that.

**Comment by Omicrxn** [comment]
@FabianLars Thanks! updating to tauri-build rc.7 and tauri rc.8 did the job!
The message: `RemoteLayerTreeDrawingAreaProxyMac::scheduleDisplayLink(): page has no displayID` still shows up though.

**Comment by FabianLars** [comment]
Yeah, just ignore that one. It shows up all the time and did for a while (there may be some condition though since it doesn't show up for everyone). No idea where it comes from or even how to debug it.
