### ISSUE TITLE
[bug] buils ios fail with CODE_SIGN_STYLE = Manual

### ISSUE THREAD

**Issue by vfiee** [tauri-apps/tauri#10836]
### Describe the bug

Set CODE_SIGN_STYLE to Manual in xcode and manually set the certificate, but every time you run pnpm tauri ios build, CODE_SIGN_STYLE will be automatically corrected to Automatic.

`before run: pnpm tauri ios build`
<img width="725" alt="image" src="https://github.com/user-attachments/assets/da9008e4-026b-4cb2-b341-1fcb85803528">
<img width="879" alt="image" src="https://github.com/user-attachments/assets/73561cb8-eff1-4518-8c5e-d8574971fd7f">
`after run:pnpm tauri ios build`
<img width="716" alt="image" src="https://github.com/user-attachments/assets/561514ef-e4c2-4beb-a958-08ff048f3f0f">
<img width="842" alt="image" src="https://github.com/user-attachments/assets/ee1720fb-ef2a-4d99-bed2-f692287c1cd7">

### Reproduction

1. set CODE_SIGN_STYLE to Manual on xcode
2. run pnpm tauri ios build
3. check CODE_SIGN_STYLE on xcode

### Expected behavior

save CODE_SIGN_STYLE type on build

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.6.1 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 18.20.2
    - pnpm: 9.9.0
    - npm: 10.5.0
    - bun: 1.1.24

[-] Packages
    - tauri 🦀: 2.0.0-rc.5
    - tauri-build 🦀: 2.0.0-rc.5
    - wry 🦀: 0.42.0
    - tao 🦀: 0.29.0
    - @tauri-apps/api : 2.0.0-rc.4
    - @tauri-apps/cli : 2.0.0-rc.8

[-] Plugins
    - tauri-plugin-fs 🦀: 2.0.0-rc.0
    - @tauri-apps/plugin-fs : not installed!
    - tauri-plugin-shell 🦀: 2.0.0-rc.2
    - @tauri-apps/plugin-shell : 2.0.0-rc.0 (outdated, latest: 2.0.0-rc.1)
    - tauri-plugin-http 🦀: 2.0.0-rc.0
    - @tauri-apps/plugin-http : 2.0.0-rc.1 (outdated, latest: 2.0.0-rc.2)

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite

[-] iOS
    - Developer Teams:---
```

### Stack trace

```text
error: sun_iOS has conflicting provisioning settings. sun_iOS is automatically signed, but provisioning profile sun has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor, or switch to manual signing in the Signing & Capabilities editor. (in target 'sun_iOS' from project 'sun')
note: Run script build phase 'Build Rust Code' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'sun_iOS' from project 'sun')
```

**Comment by bradleat** [comment]
Are you trying to sign it manually so that you can distribute the app? If so I have a script that works.

```
#!/bin/bash
APP_NAME=ExampleApp
PROVISIONING_PROFILE_LOCATION="/path/to/ios/distribution/provisioning/profile"
DISTROBUTION_SIGNING_KEY_CERT="NAME OF SIGNING CERT"

# Change directory to the arm64 build folder
cd ./src-tauri/gen/apple/build/arm64

# Step 1: Copy the IPA and convert it to a ZIP file
cp $APP_NAME.ipa $APP_NAME.zip

# Step 2: Unzip the IPA to access the contents
unzip $APP_NAME.zip -d $APP_NAME

ENTITLEMENTS_PATH="../../app_iOS/app_iOS.entitlements"
if [ -f "$ENTITLEMENTS_PATH" ]; then
    echo "Entitlements found at $ENTITLEMENTS_PATH"
else
    echo "Entitlements file not found at $ENTITLEMENTS_PATH"
    exit 1
fi

# Step 3: Embed the Provisioning Profile
cp $PROVISIONING_PROFILE_LOCATION $APP_NAME/Payload/$APP_NAME.app/embedded.mobileprovision

# Step 4: Remove libapp_lib.a
rm $APP_NAME/Payload/$APP_NAME.app/libapp_lib.a

# Step 5: Sign the app with your Developer ID
codesign -f -s $DISTROBUTION_SIGNING_KEY_CERT --entitlements ../../app_iOS/app_iOS.entitlements $APP_NAME/Payload/$APP_NAME.app

# Step 6: Repackage the IPA
cd $APP_NAME
zip -r ../$APP_NAME-signed.ipa Payload

# Step 7: Verify the signature
codesign -v --deep Payload/$APP_NAME.app --verbose

# Return to the original directory
cd ../../../../..
```

That script runs on the built Tauri ios output. It resigns the app with whatever provisoning profile / key you want.

**Comment by vfiee** [comment]
> Are you trying to sign it manually so that you can distribute the app? If so I have a script that works.
> 
> ```
> #!/bin/bash
> APP_NAME=ExampleApp
> PROVISIONING_PROFILE_LOCATION="/path/to/ios/distribution/provisioning/profile"
> DISTROBUTION_SIGNING_KEY_CERT="NAME OF SIGNING CERT"
> 
> # Change directory to the arm64 build folder
> cd ./src-tauri/gen/apple/build/arm64
> 
> # Step 1: Copy the IPA and convert it to a ZIP file
> cp $APP_NAME.ipa $APP_NAME.zip
> 
> # Step 2: Unzip the IPA to access the contents
> unzip $APP_NAME.zip -d $APP_NAME
> 
> ENTITLEMENTS_PATH="../../app_iOS/app_iOS.entitlements"
> if [ -f "$ENTITLEMENTS_PATH" ]; then
>     echo "Entitlements found at $ENTITLEMENTS_PATH"
> else
>     echo "Entitlements file not found at $ENTITLEMENTS_PATH"
>     exit 1
> fi
> 
> # Step 3: Embed the Provisioning Profile
> cp $PROVISIONING_PROFILE_LOCATION $APP_NAME/Payload/$APP_NAME.app/embedded.mobileprovision
> 
> # Step 4: Remove libapp_lib.a
> rm $APP_NAME/Payload/$APP_NAME.app/libapp_lib.a
> 
> # Step 5: Sign the app with your Developer ID
> codesign -f -s $DISTROBUTION_SIGNING_KEY_CERT --entitlements ../../app_iOS/app_iOS.entitlements $APP_NAME/Payload/$APP_NAME.app
> 
> # Step 6: Repackage the IPA
> cd $APP_NAME
> zip -r ../$APP_NAME-signed.ipa Payload
> 
> # Step 7: Verify the signature
> codesign -v --deep Payload/$APP_NAME.app --verbose
> 
> # Return to the original directory
> cd ../../../../..
> ```
> 
> That script runs on the built Tauri ios output. It resigns the app with whatever provisoning profile / key you want.

Yes, try to sign it manually and build it, but it will be automatically adjusted to automatic signature every time, and the will  fail, so there is no way to get ipa through manually signatures.

**Comment by bradleat** [comment]
> > Are you trying to sign it manually so that you can distribute the app? If so I have a script that works.
> > ```
> > #!/bin/bash
> > APP_NAME=ExampleApp
> > PROVISIONING_PROFILE_LOCATION="/path/to/ios/distribution/provisioning/profile"
> > DISTROBUTION_SIGNING_KEY_CERT="NAME OF SIGNING CERT"
> > 
> > # Change directory to the arm64 build folder
> > cd ./src-tauri/gen/apple/build/arm64
> > 
> > # Step 1: Copy the IPA and convert it to a ZIP file
> > cp $APP_NAME.ipa $APP_NAME.zip
> > 
> > # Step 2: Unzip the IPA to access the contents
> > unzip $APP_NAME.zip -d $APP_NAME
> > 
> > ENTITLEMENTS_PATH="../../app_iOS/app_iOS.entitlements"
> > if [ -f "$ENTITLEMENTS_PATH" ]; then
> >     echo "Entitlements found at $ENTITLEMENTS_PATH"
> > else
> >     echo "Entitlements file not found at $ENTITLEMENTS_PATH"
> >     exit 1
> > fi
> > 
> > # Step 3: Embed the Provisioning Profile
> > cp $PROVISIONING_PROFILE_LOCATION $APP_NAME/Payload/$APP_NAME.app/embedded.mobileprovision
> > 
> > # Step 4: Remove libapp_lib.a
> > rm $APP_NAME/Payload/$APP_NAME.app/libapp_lib.a
> > 
> > # Step 5: Sign the app with your Developer ID
> > codesign -f -s $DISTROBUTION_SIGNING_KEY_CERT --entitlements ../../app_iOS/app_iOS.entitlements $APP_NAME/Payload/$APP_NAME.app
> > 
> > # Step 6: Repackage the IPA
> > cd $APP_NAME
> > zip -r ../$APP_NAME-signed.ipa Payload
> > 
> > # Step 7: Verify the signature
> > codesign -v --deep Payload/$APP_NAME.app --verbose
> > 
> > # Return to the original directory
> > cd ../../../../..
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That script runs on the built Tauri ios output. It resigns the app with whatever provisoning profile / key you want.
> 
> Yes, try to sign it manually and build it, but it will be automatically adjusted to automatic signature every time, and the will fail, so there is no way to get ipa through manually signatures.

This works.
I have my ios app in the AppStore.

You let Tauri build with xcode with the automatically chosen profile.

Then you use the script to resign the app with the provisioning profile and signing cert of your choice.

**Comment by vfiee** [comment]
OK, thank you. I'll try it later.

**Comment by vfiee** [comment]
[根据文档](https://beta.tauri.app/zh-cn/distribute/sign/ios/#automatic-signing)，使用自动签名的方式构建成功，期待后续在手动设置签名上也能成功

**Comment by vfiee** [comment]
Thanks to everyone who offered help. Thank you very much.

**Comment by rtmotiondev** [comment]
> Are you trying to sign it manually so that you can distribute the app? If so I have a script that works.
> 
> ```
> #!/bin/bash
> APP_NAME=ExampleApp
> PROVISIONING_PROFILE_LOCATION="/path/to/ios/distribution/provisioning/profile"
> DISTROBUTION_SIGNING_KEY_CERT="NAME OF SIGNING CERT"
> 
> # Change directory to the arm64 build folder
> cd ./src-tauri/gen/apple/build/arm64
> 
> # Step 1: Copy the IPA and convert it to a ZIP file
> cp $APP_NAME.ipa $APP_NAME.zip
> 
> # Step 2: Unzip the IPA to access the contents
> unzip $APP_NAME.zip -d $APP_NAME
> 
> ENTITLEMENTS_PATH="../../app_iOS/app_iOS.entitlements"
> if [ -f "$ENTITLEMENTS_PATH" ]; then
>     echo "Entitlements found at $ENTITLEMENTS_PATH"
> else
>     echo "Entitlements file not found at $ENTITLEMENTS_PATH"
>     exit 1
> fi
> 
> # Step 3: Embed the Provisioning Profile
> cp $PROVISIONING_PROFILE_LOCATION $APP_NAME/Payload/$APP_NAME.app/embedded.mobileprovision
> 
> # Step 4: Remove libapp_lib.a
> rm $APP_NAME/Payload/$APP_NAME.app/libapp_lib.a
> 
> # Step 5: Sign the app with your Developer ID
> codesign -f -s $DISTROBUTION_SIGNING_KEY_CERT --entitlements ../../app_iOS/app_iOS.entitlements $APP_NAME/Payload/$APP_NAME.app
> 
> # Step 6: Repackage the IPA
> cd $APP_NAME
> zip -r ../$APP_NAME-signed.ipa Payload
> 
> # Step 7: Verify the signature
> codesign -v --deep Payload/$APP_NAME.app --verbose
> 
> # Return to the original directory
> cd ../../../../..
> ```
> 
> That script runs on the built Tauri ios output. It resigns the app with whatever provisoning profile / key you want.

I'm having a similar problem with the entitlements not getting preserved.  https://github.com/tauri-apps/tauri/issues/11089. I might have to do the same thing that you are doing with your script.

**Comment by lucasfernog-crabnebula** [comment]
I believe #11101 fixed this, can you confirm?

**Comment by vfiee** [comment]
Thanks for the feedback, issue fixed, close issuse
