### ISSUE TITLE
[bug] Short and Long Version Strings out of Sync iOS

### ISSUE THREAD

**Issue by bradleat** [tauri-apps/tauri#10830]
### Describe the bug

The ios build step should update both version strings in the plist on ios. Currently it only updates one:

```
<key>CFBundleShortVersionString</key>
<string>0.1.0</string>
<key>CFBundleVersion</key>
<string>0.2.1</string>
```

Notice the `CFBundleShortVersionString` can get out of sync with `CFBundleVersion`

I'd like to make a fix (could be a first good issue), but I really can't tell when/where tauri is writing this during the build step.

What I can see is that is that this file: https://github.com/tauri-apps/tauri/blob/5ec74456b9ae45eaa63e225856de1b7eb83abe6f/crates/tauri-bundler/src/bundle/macos/app.rs#L227 appear to write both the short version string and the bundle version, but from different sources.

### Reproduction

1. Build an ios app with a tauri.conf.json version string that points to to the project.json.
2. Change the version.

3. Notice that the CFBundleVersion updates but not the CFBundleShortVersionString

### Expected behavior

Both version strings update, or the can be controlled seperately. Or perhaps the short version string is the x.y.z component of the bundle version which might include a canary.

### Full `tauri info` output

```text
N/A
```

**Comment by lucasfernog** [comment]
closed by #10944
