### ISSUE TITLE
Tauri render css not properly.

### ISSUE THREAD

**Issue by frangte** [tauri-apps/tauri#1084]
**Describe the bug**
I have electron app, recently i convert it to tauri, but i got some trouble with it. Maybe `tauri` render CSS not properly.

**Screenshots**
Left is `tauri`, right is `electron`
![image](https://user-images.githubusercontent.com/19859575/98967232-d8c63300-253e-11eb-9b8c-1584ac28bd7a.png)

As you can see on top of both apps,  `Name document` and button `Edit` of tauri not same with electron (electron is render correct).

**Platform and Versions (please complete the following information):**

OS: Ubuntu 20.04
Node: 14.2.0
NPM: 6.14.4
Yarn: 1.22.5
Rustc: 1.47

**Additional context**
- Code of this app is public.

**Stack Trace**

**Comment by Laegel** [comment]
Hey @frangte , how's your font family loaded? Where is the style definition located in your code?
May not be a bug but a misunderstanding about Tauri's behavior. :)

**Comment by MGlolenstine** [comment]
<details>
<summary>Nothing to see here, but nonsense</summary>

I do think that there's something there. 
I tried using this code for a website
```HTML
<html>

<head>
    <style>
        .ex5 .parent {
            display: grid;
            grid-template: auto 1fr auto / auto 1fr auto;
        }

        .ex5 header {
            padding: 2rem;
            grid-column: 1 / 4;
        }

        .ex5 .left-side {
            grid-column: 1 / 2;
        }

        .ex5 main {
            grid-column: 2 / 3;
        }

        .ex5 .right-side {
            grid-column: 3 / 4;
        }

        .ex5 footer {
            grid-column: 1 / 4;
        }
    </style>
</head>

<body>
    <div class="parent">
        <header class="pink section">Header</header>
        <div class="left-side blue section" contenteditable>Left Sidebar</div>
        <main class="section coral" contenteditable> Main Content</main>
        <div class="right-side yellow section" contenteditable>Right Sidebar</div>
        <footer class="green section">Footer</footer>
    </div>
</body>

</html>
```
but all I got was this:
![image](https://user-images.githubusercontent.com/9406770/99006191-59d2f980-2542-11eb-81f6-321310e55efe.png)
I am on Windows 10 and running with Edge (WebView2 installed).

Expected outcome:
![image](https://user-images.githubusercontent.com/9406770/99006298-86871100-2542-11eb-82f0-7e389198bfd0.png)

</details>

**Comment by Laegel** [comment]
@MGlolenstine Your styles don't match your content. 
To fix that, you may either remove `.ex5` selector in your styles or add a wrapper HTML element with `class="ex5"`.

**Comment by frangte** [comment]
Thank @Laegel for quickly response,

I used `vue` and `tailwind` for that.

```
    <div class="flex flex-wrap content-center h-12 sticky top-0 z-10">
      <div class="flex flex-wrap ml-2 content-center">Name document</div>
      <div class="flex flex-wrap ml-auto mr-2">
        <btn @click="changeEditable">
          <span v-if="editable">Save</span>
          <span v-else>Edit</span>
        </btn>
      </div>
    </div>
```
this is code of this component.

**Comment by MGlolenstine** [comment]
> @MGlolenstine Your styles don't match your content.
> To fix that, you may either remove `.ex5` selector in your styles or add a wrapper HTML element with `class="ex5"`.

Oooops :sweat_smile: I tried some of my own code, but apparently failed in setting CSS classes, so I went online and copied few snippets from a website and missed the `ex5` thingy...

And I made a fool of myself.

Thanks for the help!

**Comment by Laegel** [comment]
@MGlolenstine It's okay, this kind of things happen, haha. 

@frangte Yeah, I browsed your code . The thing is I didn't find any style declaration regarding the font family you're using.

**Comment by frangte** [comment]
@Laegel i use default of tailwind,
![image](https://user-images.githubusercontent.com/19859575/99078353-d7edd980-25f0-11eb-9e28-3462a8bf267b.png)

but it not about the font, it is position of element, maybe `align-content` doesn't effect on tauri. Bellow is sample code.

```
<template>
  <div class="demo">
    Must center
  </div>
</template>

<script>
export default {
  name: "Demo"
}
</script>

<style>
.demo {
  display: flex;
  flex-wrap: wrap;
  height: 100%;
  justify-content: center;
  align-content: center;
}
</style>
```

Result (left is tauri, right is electron)
![image](https://user-images.githubusercontent.com/19859575/99079484-9ceca580-25f2-11eb-939e-5fa972317650.png)

As you can see `Must center` does not center on tauri.

Btw thanks for your help.

**Comment by frangte** [comment]
@Laegel can you help me

**Comment by Laegel** [comment]
@frangte So, `align-content` property doesn't seem to work. 
I've tried [some of the examples from Mozilla](https://developer.mozilla.org/en-US/docs/Web/CSS/align-content) but didn't manage to make them work.
The good news is that you may use `align-items` instead:

![trai-debug](https://user-images.githubusercontent.com/3584791/99151920-c236ed80-269e-11eb-8c99-3522f59abc81.png)

**Comment by frangte** [comment]
@Laegel  Oh, okay i will try this. Btw thank you very much, and sorry for ping you on weekend
Have a good day

**Comment by Laegel** [comment]
@frangte Always happy to help. :)
This makes me think we still lack a nice guide for what web APIs/elements/styles are supported by Tauri (Webview) and would definitely deserve a bit of attention.

**Comment by frangte** [comment]
Yes, this docs really helpful for some one like me, who come from backend, haha :)
