### ISSUE TITLE
[feat] Should we do something to prevent decompile?

### ISSUE THREAD

**Issue by gusxodnjs** [tauri-apps/tauri#10859]
### Describe the problem

Hello, I already know that tauri app is safer than electron app. The instructions also show that decompiling is difficult. Nevertheless, when you open an app written in tauri with a debugger, you will be exposed to strings such as the system file path. Do I need to obfuscate with a tool like upx? Is there anything tauri can guide you through?
![image](https://github.com/user-attachments/assets/009e1a12-405a-4e90-b5f9-110e631613d0)

### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/fccc052a-9bb6-46cb-a9f3-53a6c7108434)

**Comment by amrbashir** [comment]
see this comment https://github.com/tauri-apps/tauri/issues/6538#issuecomment-1482634473

**Comment by Z1xus** [comment]
although decompilation is difficult, memory still can be dumped along with index.js; id suggest you to look into js obfuscation or consider writing anything sensitive on backend

**Comment by JaneX8** [comment]
I was thinking to convert most or at least the most important part of JavaScript into WebAssembly (WASM). And use the wasm file within Tauri. Any thoughts on this idea, in terms of potential decompilation or source code leakage/intellectual property protection?
