### ISSUE TITLE
[bug] Can't customize NSIS installer template

### ISSUE THREAD

**Issue by reken-rich** [tauri-apps/tauri#10850]
### Describe the bug

I am trying to simply add a shortcut to the StartUp folder for the current user.  

I have tried using a custom template by copying the default installer.nsi to a custom file then pointing to that file in tauri.conf.json.  
```
"windows": {
       "nsis": {
         "template": "./reken-installer.nsi"
       }
     }
```

This produces the following error (with no changes to the copied template):
`Error rendering "installer.nsi" line 554, col 36: Helper not found unescape-dollar-sign`

I have also tried using hooks:
```
!macro NSIS_HOOK_POSTINSTALL
    CreateShortcut "$SMSTARTUP\${MAINBINARYNAME}.lnk" "$INSTDIR\${MAINBINARYNAME}.exe"
!macroend

!macro NSIS_HOOK_POSTUNINSTALL
    Delete "$SMSTARTUP\${MAINBINARYNAME}.lnk"
!macroend
```
with
```
"windows": {
      "nsis": {
        "installerHooks": "./hooks.nsi"
      }
    }
```
In this case I get no error, but the shortcut is not created in the startup folder.

### Reproduction

See above

### Expected behavior

Expect to be able to create startup shortcut either via hooks or including those commands in the Install and Uninstall sections of the copied default template.

### Full `tauri info` output

```text
PS C:\Users\Rich\reken\prototyping\target\x86_64-pc-windows-msvc\release\bundle\nsis> cargo tauri info                  
[✔] Environment
    - OS: Windows 10.0.19045 x86_64 (X64)
    ✔ WebView2: 128.0.2739.54
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.82.0-nightly (41dd149fd 2024-08-11)
    ✔ cargo: 1.82.0-nightly (0d8d22f83 2024-08-08)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: nightly-2024-08-12-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)

[-] Packages
    - tauri-cli 🦀: 2.0.0-rc.8

[-] Plugins

[-] App
```

**Comment by Legend-Master** [comment]
I can't reproduce either of these, using a custom template didn't throw me any error, and the hook did create a new shortcut in my startup folder with the exact code you provided

![image](https://github.com/user-attachments/assets/e147a38b-beaa-4743-bc37-83649d20a958)

**Comment by reken-rich** [comment]
My apologies wrt the hooks.  I was on the wrong branch when trying to build
with the hooks and they did work.

However, I have checked and re-checked the custom template:

   - Create new file 'xxx-installer.nsi' in same directory as
   tauri.conf.json
   - Copy content from
   https://github.com/tauri-apps/tauri/blob/1.x/tooling/bundler/src/bundle/windows/templates/installer.nsi
   to xxx-installer.nsi
   - Add "template": "./xxx-installer.nsi" to tauri.bundle.windows.nsis

"bundle": {

    "active": true,

    "targets": "all",

    "icon": [

      "icons/32x32.png",

      "icons/128x128.png",

      ***@***.***",

      "icons/icon.icns",

      "icons/icon.ico"

    ],

    "resources": [

      "../reken-sentence/models/multilabel/run_e4d4bbef/config.json",


"../reken-sentence/models/multilabel/run_e4d4bbef/model_head.safetensors",

      "../reken-sentence/models/multilabel/run_e4d4bbef/model.safetensors",

      "../reken-sentence/models/multilabel/run_e4d4bbef/tokenizer.json"

    ],

    "windows": {

      "nsis": {

        "template": "./reken-installer.nsi"

      }

    }

  }


Get the 'Helper not found unescape-dollar-sign' error.  This seems like a
scope/include problem as this is not something that is defined in the
script.  For some reason when pointing to the custom template, it is not
finding this helper.  My repo does not follow default Tauri naming, but
don't know why that should matter with respect to the Handlebars expansion
of the template.

**Comment by Legend-Master** [comment]
I'm not sure why would you copy the template from 1.x when using tauri 2 rc, do you mind trying to copy from the dev branch instead?

**Comment by reken-rich** [comment]
Because I didn’t know where to find a v2 template.  V2 installer docs are
WIP and the link to the template in there returns a 404 (
https://github.com/tauri-apps/tauri/blob/dev/packages/tauri-bundler/src/bundle/windows/templates/installer.nsi).
All searches led me to the v1 template, so figured maybe the installer
hadn't changed for v2.

So, how do I find the v2 template?

**Comment by reken-rich** [comment]
Apologies for posting twice, but didn't Reply All with first response...

Because I didn’t know where to find a v2 template.  V2 installer docs are
WIP and the link to the template in there returns a 404 (
https://github.com/tauri-apps/tauri/blob/dev/packages/tauri-bundler/src/bundle/windows/templates/installer.nsi).
All searches led me to the v1 template, so figured maybe the installer
hadn't changed for v2.

So, how do I find the v2 template?

**Comment by Legend-Master** [comment]
Take a look at here: https://github.com/tauri-apps/tauri/blob/dev/crates/tauri-bundler/src/bundle/windows/templates/installer.nsi

There's a recent restructure so the docs are outdated
