### ISSUE TITLE
[feat] About getting the application installation directory

### ISSUE THREAD

**Issue by Hi-Mr-Wind** [tauri-apps/tauri#10862]
### Describe the problem

I don't see a way in the current documentation to get the installation directory and the location of the integrated binaries.
But in development these two locations are actually very important, can you get two apis in js and rust respectively to get the installation directory and the integrated binary directory

### Describe the solution you'd like

But in development these two locations are actually very important, can you get two apis in js and rust respectively to get the installation directory and the integrated binary directory

**Comment by charlesschaefer** [comment]
Maybe this helps? https://www.reddit.com/r/tauri/comments/11adbst/path_to_current_executables_directory/

**Comment by amrbashir** [comment]
Also checkout https://docs.rs/tauri/2.0.0-rc.15/tauri/process/fn.current_binary.html for v2 and for v1, see https://docs.rs/tauri/latest/tauri/api/process/fn.current_binary.html
