### ISSUE TITLE
[bug] [v2] IconMenuItem's icon overlap the adjacent menus on Linux.

### ISSUE THREAD

**Issue by mikoto2000** [tauri-apps/tauri#10867]
### Describe the bug

I implemented menu:

```rust
let menu = MenuBuilder::new(app)
    .text("open-url", "Open URL")
    .check("toggle", "Toggle")
    .icon(
        "show-app",
        "Show App",
        app.default_window_icon().cloned().unwrap(),
    )
    .build()?;

app.set_menu(menu.clone())?;
```

† from [Use tauri::menu::MenuBuilder](https://v2.tauri.app/start/migrate/from-tauri-1/#use-taurimenumenubuilder)

![tauri-dialog-plugin](https://github.com/user-attachments/assets/ab73487f-cd31-4c6d-8892-1130778ce56d)

### Reproduction

Clone https://github.com/mikoto2000/TIL.git, build and run `tauri/2.0.0-beta/Menu/firststep/menu-firststep`.

### Expected behavior

No overlap icon.

### Full `tauri info` output

```text
$ npm run tauri info

> menu-firststep@0.1.0 tauri
> tauri info


[✔ ] Environment
    - OS: Debian 12.0.0 X64
    ✔  webkit2gtk-4.1: 2.44.2
    ✔  rsvg2: 2.54.7
    ✔  rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔  cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔  rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔  Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 22.2.0
    - yarn: 1.22.19
    - npm: 10.7.0

[-] Packages
    - tauri [RUST]: 2.0.0-rc.6
    - tauri-build [RUST]: 2.0.0-rc.6
    - wry [RUST]: 0.42.0
    - tao [RUST]: 0.29.1
    - @tauri-apps/api [NPM]: 2.0.0-rc.3
    - @tauri-apps/cli [NPM]: 2.0.0-rc.7

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```
```


### Stack trace

```text
no stack trace
```

**Comment by amrbashir** [comment]
is this WSL or what distro are you using ?

**Comment by mikoto2000** [comment]
@amrbashir
Sorry, I fogot write context...
I run docker container(Debian12) on Ubuntu24.04 on WSL2.

I try Windows, Ubuntu24.04 on WSL2 and Ubuntu24.04 on VM.

**Comment by mikoto2000** [comment]
Windows: 
![image](https://github.com/user-attachments/assets/2a7dcc5d-6c01-4123-8ecc-55826ca42870)

Ubuntu24.04 on WSL2:
![image](https://github.com/user-attachments/assets/17f30aa4-f733-4775-af53-82be680bb4d5)

Debian12 on WSL2:
![image](https://github.com/user-attachments/assets/3455ebad-10a5-442b-b084-95f0e0a24017)

**Comment by amrbashir** [comment]
Thanks @mikoto2000 , I have an idea what might be causing this, but unfortunately my linux machine is busted and It will take some time to setup.
