### ISSUE TITLE
[feat] SytemTrayEvent::HoverItem

### ISSUE THREAD

**Issue by cpprian** [tauri-apps/tauri#10869]
### Describe the problem

Based on this discussion https://github.com/tauri-apps/tauri/discussions/9239 is there any possibility to add this option to enum `SystemTrayEvent`?

If there is an existing issue with the hover event, please close this issue.

### Describe the solution you'd like

I'm not sure it is possible, but this could be an awesome feature when you hover on `SystemTraySubmenu`. We can load/update the state of menu items (for example to-do list tasks, shopping list products) as a `CustomMenuItem` and skip this process in other Tauri commands.

**Comment by amrbashir** [comment]
This has been added in v2 https://docs.rs/tauri/2.0.0-rc.15/tauri/tray/enum.TrayIconEvent.html#variant.Move and there is no plans to backport in v1.
