### ISSUE TITLE
[bug] getUserMedia/getDisplayMedia does not show permissions prompt on MacOS 14.5

### ISSUE THREAD

**Issue by koerismo** [tauri-apps/tauri#10878]
### Describe the bug

I have seen multiple closed issues referencing this same problem, but it appears to have returned as of the latest Tauri release candidate. (rc8)
I followed the common advice on these issues and added an Info.plist and Release.entitlements, however that only changed the error from it being undefined to it being NotAllowed, despite no permission request dialog appearing. I saw that there was [a patch for this issue](https://github.com/tauri-apps/wry/pull/1111) on the wry repository at some point, though it was apparently reverted?

When `https://localhost:1420` is opened in Safari or Firefox, the permissions dialog functions as expected.

<img width="977" alt="Screenshot 2024-09-03 at 12 41 50 PM" src="https://github.com/user-attachments/assets/694927c9-50e6-4be6-9ae7-0e591e492a3c">

### Reproduction

- Create project with latest Tauri release candidate
- Attempt to access user/display media
- Dialog does not appear

### Expected behavior

The permissions prompt should appear after requesting user media instead of silently rejecting it.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.5.0 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 21.7.3
    - pnpm: 9.1.2
    - yarn: 1.22.19
    - npm: 10.5.0
    - bun: 1.1.3

[-] Packages
    - tauri 🦀: 2.0.0-rc.8
    - tauri-build 🦀: 2.0.0-rc.7
    - wry 🦀: 0.42.0
    - tao 🦀: 0.29.1
    - @tauri-apps/api : 2.0.0-rc.4
    - @tauri-apps/cli : 2.0.0-rc.10

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-shell : 2.0.0-rc.1
    - tauri-plugin-dialog 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-dialog : 2.0.0-rc.1
    - tauri-plugin-fs 🦀: 2.0.0-rc.1
    - @tauri-apps/plugin-fs : 2.0.0-rc.2

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

### Stack trace

```text
N/A
```

**Comment by FabianLars** [comment]
At first i thought it may be related to https://github.com/tauri-apps/wry/issues/1195 but this part
> When https://localhost:1420/ is opened in Safari or Firefox, the permissions dialog functions as expected.

makes me unsure. `Info.plist` files only properly work in actual app bundles so maybe try actually building the app and starting the `.app` bundle instead.

**Comment by koerismo** [comment]
Just built the app and tested it a couple times - `getUserMedia` functioned correctly when packaged, however `getDisplayMedia` did not.

It would be great if there was some sort of config property/capability to allow using these features when developing.

**Comment by FabianLars** [comment]
Giving your Terminal app (or vscode for example if you use its built-in terminal) permissions to use the camera _should_ make it work in development. Not sure whether we can auto-request the permissions for the process that `tauri dev` is running in but imo that doesn't sound like a good idea either way.

> however getDisplayMedia did not.

Which should be the issue i linked.
