### ISSUE TITLE
How to store user credentials

### ISSUE THREAD

**Issue by helghast79** [tauri-apps/tauri#1087]
Is there a way to store user's credentials or user sensitive data that should be persisted like login credentials? Local storage only saves data while the app is running and is lost once the app is closed. [Keytar](http://atom.github.io/node-keytar/) works in electron, is there a way to implemented it in Tauri?

**Comment by Kelerchian** [comment]
Keytar has a rust binding https://docs.rs/keytar/0.1.3/keytar/

I think what you can do now is to manually pass the credential to the rust-runtime and then use keytar in the rust side.
