### ISSUE TITLE
[bug] [v2]decorations=false边框显示问题

### ISSUE THREAD

**Issue by yuzw1007** [tauri-apps/tauri#10889]
### Describe the bug

设置 "decorations": false时，窗口顶部的边框显示一条黑线，下/左/右边框不存在这个问题。如下图：
![微信图片_20240904103459](https://github.com/user-attachments/assets/0e0bc1d5-4be4-4310-aa75-5408a70c7c3e)

###   tauri conf

```text
{
  "productName": "hello-tauriv2",
  "version": "0.0.0",
  "identifier": "com.tauri.dev",
  "build": {
    "beforeDevCommand": "npm run dev",
    "devUrl": "http://localhost:1420",
    "beforeBuildCommand": "npm run build",
    "frontendDist": "../dist"
  },
  "app": {
    "windows": [
      {
        "title": "hello-tauriv2",
        "width": 800,
        "height": 600,
        "decorations": false
      }
    ],
    "security": {
      "csp": null
    }
  },
  "bundle": {
    "active": true,
    "targets": "all",
    "icon": [
      "icons/32x32.png",
      "icons/128x128.png",
      "icons/128x128@2x.png",
      "icons/icon.icns",
      "icons/icon.ico"
    ]
  }
}
```

### Full `tauri info` output

```text
> hello-tauriv2@0.0.0 tauri
> tauri info


[✔] Environment
    - OS: Windows 10.0.19045 x86_64 (X64)
    ✔ WebView2: 128.0.2739.54
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.20.3
    - npm: 10.8.2

[-] Packages
    - tauri 🦀: 2.0.0-rc.8
    - tauri-build 🦀: 2.0.0-rc.7
    - wry 🦀: 0.42.0
    - tao 🦀: 0.29.1
    - tauri-cli 🦀: 1.6.0
    - @tauri-apps/api : 2.0.0-rc.4
    - @tauri-apps/cli : 2.0.0-rc.10

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-shell : 2.0.0-rc.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Can you please include the output of the `tauri info` command? (For example `npm run tauri info` if you use npm)

**Comment by yuzw1007** [comment]
> Can you please include the output of the `tauri info` command? (For example `npm run tauri info` if you use npm)

已更新上面的tauri info

直接使用：npm create tauri-app@latest -- --rc  创建的应用，把decorations配置成false，其它的未作改动直接运行，运行结果显示：窗口上面的边框有黑线，下边，左边，右边显示都没有黑线。

**Comment by FabianLars** [comment]
Ah okay, thanks. This a side-effect of the current `shadows` implementation. You need to set `"shadows": false` too for now. :/

For reference: https://github.com/rust-windowing/winit/commit/76f158d3102aeb54e6c1c2ce2fd34dbe6b0daab1#diff-bb05c5e1236bdaa7f268bcbbbb8cc9f378a48eb3ed480884f0c6471a9cc933edR979-R989

**Comment by yuzw1007** [comment]
> Ah okay, thanks. This a side-effect of the current `shadows` implementation. You need to set `"shadows": false` too for now. :/
> 
> For reference: [rust-windowing/winit@76f158d#diff-bb05c5e1236bdaa7f268bcbbbb8cc9f378a48eb3ed480884f0c6471a9cc933edR979-R989](https://github.com/rust-windowing/winit/commit/76f158d3102aeb54e6c1c2ce2fd34dbe6b0daab1#diff-bb05c5e1236bdaa7f268bcbbbb8cc9f378a48eb3ed480884f0c6471a9cc933edR979-R989)

非常感谢你的回答，如果设置了shadows: false 会导致整改窗口没有阴影，在白色背景下面使用无法区分窗口大小，这个不是我想要的结果。

有什么办法去掉顶部那个边框黑线同时保持有阴影？

**Comment by yuzw1007** [comment]
> Ah okay, thanks. This a side-effect of the current `shadows` implementation. You need to set `"shadows": false` too for now. :/
> 
> For reference: [rust-windowing/winit@76f158d#diff-bb05c5e1236bdaa7f268bcbbbb8cc9f378a48eb3ed480884f0c6471a9cc933edR979-R989](https://github.com/rust-windowing/winit/commit/76f158d3102aeb54e6c1c2ce2fd34dbe6b0daab1#diff-bb05c5e1236bdaa7f268bcbbbb8cc9f378a48eb3ed480884f0c6471a9cc933edR979-R989)

非常感谢你的回答，如果设置了shadows: false 会导致整改窗口没有阴影，在白色背景下面使用无法区分窗口大小，这个不是我想要的结果。

**Comment by yuzw1007** [comment]
> Ah okay, thanks. This a side-effect of the current `shadows` implementation. You need to set `"shadows": false` too for now. :/
> 
> For reference: [rust-windowing/winit@76f158d#diff-bb05c5e1236bdaa7f268bcbbbb8cc9f378a48eb3ed480884f0c6471a9cc933edR979-R989](https://github.com/rust-windowing/winit/commit/76f158d3102aeb54e6c1c2ce2fd34dbe6b0daab1#diff-bb05c5e1236bdaa7f268bcbbbb8cc9f378a48eb3ed480884f0c6471a9cc933edR979-R989)

非常感谢你的回答，如果设置了shadows: false 会导致整改窗口没有阴影，在白色背景下面使用无法区分窗口大小，这个不是我想要的结果。

**Comment by FabianLars** [comment]
> 有什么办法去掉顶部那个边框黑线同时保持有阴影？

According to the code documentation, no. But since i didn't see any problems in my own testing i'll talk with the team again to check what the actual issues were. Everyone is quite busy at the moment though, so don't expect quick updates (if any).

**Comment by readWithoutUnderstanding** [comment]
This issue will occur on Windows 10

**Comment by xhuajin** [comment]
I've run into this problem too.
