### ISSUE TITLE
[bug] How do I use the microphone

### ISSUE THREAD

**Issue by yanbowe** [tauri-apps/tauri#10898]
### Describe the bug

In the application using the navigator. MediaDevices. GetUserMedia cannot authorize the microphone。
navigator.mediaDevices is undefined
![image](https://github.com/user-attachments/assets/7d448623-5f54-4cf5-ac65-bcb0894e0706)

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 12.6.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 20.16.0
    - pnpm: 9.7.1
    - yarn: 1.22.18
    - npm: 10.8.1

[-] Packages
    - tauri [RUST]: 1.7.2
    - tauri-build [RUST]: 1.5.4
    - wry [RUST]: 0.24.11
    - tao [RUST]: 0.16.10
    - @tauri-apps/api [NPM]: 1.6.0
    - @tauri-apps/cli [NPM]: 1.6.1

[-] App
```

**Comment by amrbashir** [comment]
I think you need to have a `Info.plist` next to `tauri.conf.json` that includes the permission for microsoft
```
<key>NSMicrophoneUsageDescription</key>
<string>${PRODUCT_NAME} always location use</string>
```

cc @lucasfernog

**Comment by lucasfernog** [comment]
Amr is correct, you must include that in the Info.plist file
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>NSMicrophoneUsageDescription</key>
    <string>Request microphone access for WebRTC</string>
  </dict>
</plist>
```

**Comment by kamalkech** [comment]
@lucasfernog i guess that for mobile app, what about desktop ?

**Comment by FabianLars** [comment]
That's for macOS (though iirc iOS is the same or similar)

**Comment by kamalkech** [comment]
@FabianLars first with current version this not fixe the issue, second what about linux and windows ?

**Comment by rakeshdhote** [comment]
@lucasfernog would you provide an tauri2.0 demo project example for microphone access for different platforms? I would highly appreciate it

**Comment by FabianLars** [comment]
Well, once you added the Info.plist above all the standard web tutorials apply. Our example app has webrtc stuff too though https://github.com/tauri-apps/tauri/blob/dev/examples/api/src/views/WebRTC.svelte (same in the plugins-workspace repo if you want to see more mobile stuff).
It's missing the android stuff though, for that you need to modify `src-tauri/gen/android/app/src/main/AndroidManifest.xml` and add:
```xml
  <uses-permission android:name="android.permission.CAMERA" />
  <uses-permission android:name="android.permission.RECORD_AUDIO" />
  <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
```

**Comment by plog** [comment]
When 
1) Trying @yanbowe example above 
2) Simply running ```npm run tauri dev``` on Mac

I don't have _mediaDevices_ at all.. ?...? 😭 (SvelteKit)
Any idea ?

![image](https://github.com/user-attachments/assets/902710c2-555d-48f9-a303-0526ad878068)

```
[Log] navigator.mediaDevices – undefined (WebRTC.svelte, line 17)
[Log] TypeError: undefined is not an object (evaluating 'navigator.mediaDevices.getUserMedia') (WebRTC.svelte, line 21)
(anonymous function) — WebRTC.svelte:5
getMicrophonePermission — WebRTC.svelte:2
without_reactive_context — shared.js:44
```

## Tauri info
```
[✔] Environment
    - OS: Mac OS 14.6.1 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.83.0 (90b35a623 2024-11-26)
    ✔ cargo: 1.83.0 (5ffbef321 2024-10-29)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 22.12.0
    - npm: 10.9.0

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.2
    - tao 🦀: 0.30.8
    - @tauri-apps/api : 2.1.1
    - @tauri-apps/cli : 2.1.0

[-] Plugins

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

## Plist
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSCameraUsageDescription</key>
	<string>Request camera access for WebRTC</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>Request microphone access for WebRTC</string>
</dict>
</plist>
```

**Comment by plog** [comment]
## **Solved**
"csp" was "null" in tauri.conf.json

```
    "security": {
      "csp": "default-src 'self' blob: data: media:; script-src 'self' 'unsafe-eval';"
    }
```
Now, it's asking permissions.
<img src="https://github.com/user-attachments/assets/e3a78c82-f2ef-427f-867c-0170738c38b6" width="300" />
