### ISSUE TITLE
[bug] UI thread blocking

### ISSUE THREAD

**Issue by Fly-Potato** [tauri-apps/tauri#10893]
### Describe the bug

When clicking the button quickly, there is a probability that it will cause the program to crash

I only added one line of code after generating the code using the create-tauri-app

![image](https://github.com/user-attachments/assets/f87d1bdc-527a-4a3f-84ca-236f10c1513a)

![image](https://github.com/user-attachments/assets/3c25d7f8-21a3-47d9-9cc0-510bebb2ae56)

![QQ20240904-161752](https://github.com/user-attachments/assets/6e1ca8f9-6de3-40e2-81d0-036652a851d6)

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.26100 x86_64 (X64)
    ✔ WebView2: 128.0.2739.54
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.12.0
    - pnpm: 9.1.3
    - yarn: 1.22.22
    - npm: 10.8.2

[-] Packages
    - tauri 🦀: 2.0.0-rc.8
    - tauri-build 🦀: 2.0.0-rc.7
    - wry 🦀: 0.42.0
    - tao 🦀: 0.29.1
    - @tauri-apps/api : 2.0.0-rc.4
    - @tauri-apps/cli : 2.0.0-rc.10

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-shell : 2.0.0-rc.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by Fly-Potato** [comment]
This issue may cause occasional crashes while using the software

**Comment by amrbashir** [comment]
Closing in favor of #10546
