### ISSUE TITLE
[bug] Page pixel misalignment

### ISSUE THREAD

**Issue by OceanBelongsToMe** [tauri-apps/tauri#10891]
### Describe the bug

<img width="358" alt="image" src="https://github.com/user-attachments/assets/2a5edf21-19fc-4cce-b2bf-caf8f0e36d45">

As shown in the figure, all the content in the summary tag should be hidden, but there are always residues

### Full `tauri info` output

```text
Environment
    - OS: Mac OS 13.6.9 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.0 (051478957 2024-07-21)
    ✔ cargo: 1.80.0 (376290515 2024-07-16)
    ⚠ rustup: not installed!
      If you have rust installed some other way, we recommend uninstalling it
      then use rustup instead. Visit https://rustup.rs/
    ⚠ Rust toolchain: couldn't be detected!
      Maybe you don't have rustup installed? if so, Visit https://rustup.rs/
    - node: 20.16.0
    - pnpm: 9.9.0
    - npm: 10.8.1
```

**Comment by FabianLars** [comment]
We generally have no influence on the webview/renderer behavior. Does it work correctly in Safari? (Asking about Safari specifically because it uses webkit like the macos webview)

**Comment by ConnorKrammer** [comment]
What does your HTML and CSS look like to produce this, and if it looks fine in other browsers, which ones? Might be a known bug or difference in feature support between browsers (CSS in Tauri still needs to be written defensively like on the web, with e.g. polyfills or prefixed fallback properties when necessary, depending on what features are being used).

**Comment by OceanBelongsToMe** [comment]
Perhaps, it is due to the webview itself, and the same is true for using the canvas element in tauri app:
<img width="447" alt="image" src="https://github.com/user-attachments/assets/af61ce9c-93a6-4376-a7e7-eb8cfabf3993">
