### ISSUE TITLE
[bug]  I   can't believe   that   appear  this kind  problems    

### ISSUE THREAD

**Issue by Super1Windcloud** [tauri-apps/tauri#10904]
### Describe the bug

![image](https://github.com/user-attachments/assets/eee44f70-042e-4ca1-b98f-c48b3d488dc3)
 --- 

# *path Error*  
>  you should change to   relative path 

### Full `tauri info` output

```text
# *path Error*  
>  you should change to   relative path
```

**Comment by amrbashir** [comment]
Please explain your problem properly and follow the issue guidelines, instead of just attacking us for nothing because the above snippet works fine.
