### ISSUE TITLE
[bug] I  need  a  reply , why   html component can't     cover  all window view  

### ISSUE THREAD

**Issue by Super1Windcloud** [tauri-apps/tauri#10905]
### Describe the bug

![image](https://github.com/user-attachments/assets/285b73f6-4786-451f-b9ef-efa9587ef13f)

### Full `tauri info` output

```text
![image](https://github.com/user-attachments/assets/285b73f6-4786-451f-b9ef-efa9587ef13f)
```

**Comment by Super1Windcloud** [comment]
![image](https://github.com/user-attachments/assets/3db66699-c6cf-4bde-96e2-1fa402c062d5)

**Comment by Super1Windcloud** [comment]
this is  WIndows11   ,  tauri   latest,  what happen

**Comment by amrbashir** [comment]
There is no bug here. You just didn't set your html or body element to fill the available space. 

This is a CSS question, so please either use Discussions to find help or join our Discord or other CSS communities to help.
