### ISSUE TITLE
[bug] Two tray icons on macos

### ISSUE THREAD

**Issue by timuric** [tauri-apps/tauri#10912]
### Describe the bug

Tray icon appears twice
<img width="77" alt="image" src="https://github.com/user-attachments/assets/87622310-ccc3-4a2a-b081-c59c3956826a">

### Reproduction

Follow the guide:
https://v2.tauri.app/plugin/system-tray/

Add tray icon config:

```json
"app": {
    "trayIcon": {
      "iconPath": "icons/icon.png"
    },
}
```

### Expected behavior

Only one tray icon

### Full `tauri info` output

```text
(base) ~/code/tauri-tray-bug
npm run tauri info

> tauri-tray-bug@0.1.0 tauri
> tauri info


[✔] Environment
    - OS: Mac OS 14.5.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.12.1
    - pnpm: 9.6.0
    - yarn: 1.22.19
    - npm: 10.2.0
    - bun: 1.0.0

[-] Packages
    - tauri [RUST]: 2 (no lockfile)
    - tauri-build [RUST]: no manifest (no lockfile)
    - wry [RUST]: no manifest (no lockfile)
    - tao [RUST]: no manifest (no lockfile)
    - @tauri-apps/api [NPM]: 1.6.0
    - @tauri-apps/cli [NPM]: 1.6.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Additional context

Link to repo https://github.com/timuric/tray-bug

**Comment by FabianLars** [comment]
This change of behavior (compared to v1) is why we removed the tauri.conf.json config from the linked docs page. Unlike v1 the TrayIconBuilder in v2 will create a new icon. If you want to add items to the icon from the config you can get a handle to the tray via `app.tray_icon_by_id("main")` though at that point it probably makes sense to just remove it and create the whole tray in rust or js.
