### ISSUE TITLE
Do something before closing the window

### ISSUE THREAD

**Issue by McDull-GitHub** [tauri-apps/tauri#1091]
**Describe the bug**
`window.onunload` and `window.onbeforeunload` are not working when the app closes.

**To Reproduce**
1. Go to an empty folder
`cd workplace`

2. Add Tauri to my project
`yarn add tauri`
`yarn tauri init`
`mkdir dist && cd $_`
`touch index.html`

3. Edit the file index.html
```
<!DOCTYPE html>
<html>

<body>
  <h3>I wanna do something while closing me</h3>
  <script>
    window.onload = () => {
      alert("onload is running");
      return "onload is running"
    }
    window.onbeforeunload = () => {
      alert("onbeforeunload is running");
      return "onbeforeunload is running"
    }
    window.onunload = () => {
      alert("onunload is running");
      return "onunload is running"
    }
  </script>
</body>

</html>
```

4. Build and run
`cd .. && yarn tauri build -d`
`open src-tauri/target/debug/bundle/osx/*.app`

5. Close the app and nothing happens

**Expected behavior**
Ask if the user really wants to leave while closing the app ~and do something (eg. deleting temporary files) before leaving~.

**Platform and Versions**
OS:  Darwin(20.1.0) - darwin/x64
Node: 12.19.0
NPM: 6.14.8
Yarn: 1.22.10
Rustc: 1.47.0

**Comment by multiojuice** [comment]
Is this still an issue?

**Comment by nothingismagick** [comment]
This is now possible with wry I believe. Can you confirm @nklayman or @lucasfernog ?

**Comment by lucasfernog** [comment]
This is still an issue with wry, but it'll be fixed soon with the event system that @amrbashir is working on, which will be amazing.

**Comment by amrbashir** [comment]
If all goes well, It should be finished by tomorrow.

**Comment by lucasfernog** [comment]
We'll track this on #1523
