### ISSUE TITLE
[question] [V2] new WebviewWindow How do you use listening events.

### ISSUE THREAD

**Issue by StrawberryCake-Fish** [tauri-apps/tauri#10921]
### Describe the bug

I created a new child window, and then my child window needed to use the event listener method. When my child window was created, I got an error telling me that I could not use the event listener
![image](https://github.com/user-attachments/assets/c408056b-91d0-41f5-a592-7a27c871a578)

### Reproduction

This is the permission I set
```json
"permissions": [
    "core:default",
    "core:window:default",
    "core:window:allow-start-dragging",
    "core:window:allow-center",
    "core:window:allow-maximize",
    "core:window:allow-unmaximize",
    "core:window:allow-minimize",
    "core:window:allow-unminimize",
    "core:window:allow-show",
    "core:window:allow-hide",
    "core:window:allow-close",
    "core:window:allow-set-size",
    "core:window:allow-set-position",
    "core:window:allow-start-dragging",
    "core:window:allow-toggle-maximize",
    "core:window:allow-destroy",
    "core:event:default",
    "core:event:allow-emit",
    "core:event:allow-emit-to",
    "core:event:allow-listen",
    "core:event:allow-unlisten",
    "core:webview:allow-create-webview-window",
    "dialog:allow-open",
    "fs:default",
    "notification:default",
    "log:default",
    "http:default"
]
```

I'll create a new window on the main screen
```typescript
childWindow = new WebviewWindow(WindowLabelEnums.Screen, {
    title: "AIForge screen", width: 800, height: 600, center: true, url: '/screen',
    resizable: true, decorations: false, alwaysOnTop: true,
    dragDropEnabled: false
});

childWindow.once('tauri://created', function () {
    console.log("Create success.")
    childWindow.onCloseRequested(() => {
        console.log("ChildWindow close.")
        isScreen = false;
    });
    intervalId = setInterval(() => {
        childWindow.emit('message-to-webview', "asdasdasfasfasd");
    }, 1000)
})
```

This is screen page, That is, the page displayed by the child window.
```typescript
onMount(() => {
    listen<string>('message-to-webview', (event) => {
        console.log('Received:', event);
    });
})
```

An error is displayed when the child window is displayed
```text
Uncaught (in promise) event.listen not allowed on window "screen-label", webview "screen-label", URL: local

allowed on: [windows: "main", URL: local], [windows: "main", URL: local], [windows: "main", URL: local]

referenced by: capability: demo, permission: default || capability: demo, permission: allow-listen || capability: demo, permission: default
```
![image](https://github.com/user-attachments/assets/0a94a9c3-ea11-4874-a0e1-a709d18e3578)

### Expected behavior

I thought that since I enabled the permissions, then I should be able to use these functions, but in fact I can not use, someone can answer my doubts, thank you very much

### Full `tauri info` output

```text
Uncaught (in promise) event.listen not allowed on window "screen-label", webview "screen-label", URL: local

allowed on: [windows: "main", URL: local], [windows: "main", URL: local], [windows: "main", URL: local]

referenced by: capability: demo, permission: default || capability: demo, permission: allow-listen || capability: demo, permission: default
```

**Comment by StrawberryCake-Fish** [comment]
Ok, I understand, you need to create a new permissions related configuration file, and set the correct label

**Comment by CorMazz** [comment]
For anyone else wondering what this guy means, I got it to work on Windows by going in my src-tauri/capabilities folder, copying the default.json file and placing it in the same spot (`src-tauri/capabilities/whatever.json`) and putting the following information inside. 

```
{
    "$schema": "../gen/schemas/desktop-schema.json",
    "identifier": "plot-window",  
    "description": "Capability for the plot window",
    "windows": [
      "plot-window"
    ],
    "permissions": [
      "core:default"
    ]
  }
```


`"plot-window"` was the name of the identifier I used when creating the new window. I'll include that code for reference here too. 

```
const webview = new WebviewWindow('plot-window', {
      url: '/app-windows/plot-window.html'
    });
```

If anyone can direct me to where in the documentation this is listed, that'd be great. I took a wild stab at this and happened to get lucky, but on other things I've wasted a few hours on just scouring the documentation trying to find information on permissions and security policies, etc.

**Comment by BadMachine** [comment]
@CorMazz Thanks mate!
I kinda stuck with this message right now. When it uses external url - still throws

![Image](https://github.com/user-attachments/assets/2968bd08-9d31-4558-851f-5bdeae32c1d4)

**Comment by FabianLars** [comment]
@BadMachine https://v2.tauri.app/security/capabilities/#remote-api-access

**Comment by BadMachine** [comment]
@FabianLars saved my day, thanks.
