### ISSUE TITLE
Tauri doesn't provide cargo.lock files for Tauri cli (RUST)

### ISSUE THREAD

**Issue by Eveeifyeve** [tauri-apps/tauri#10923]
Tauri doesn't provide cargo.lock files for `cargo tauri` cli for rust.
This Rases a big issue for Nix/NixOS as nix doesn't know what dependancies/tested against and this makes reproducibility impossible. 

I will be able to make a pr in a week or two, but if someone has a crack at fixing this, then go ahead.

**Comment by amrbashir** [comment]
We have a `Cargo.lock` at the workspace root here https://github.com/tauri-apps/tauri/blob/dev/Cargo.lock and it is published with the CLI here https://docs.rs/crate/tauri-cli/2.0.0-rc.11/source/Cargo.lock
