### ISSUE TITLE
[bug] setFullscreen doesn't works with Nuxt 3

### ISSUE THREAD

**Issue by thiagovianav** [tauri-apps/tauri#10929]
### Describe the bug

The `appView.setFullscreen(true)` or `getCurrent().setFullscreen` and `.isFullscreen()` doesn't seem to be working, i tried changing the capabilities and nothing changed at all.

https://github.com/user-attachments/assets/a9498457-5b37-44fa-9453-70600e237e50

Sorry if I'm just being dumb but I thought in the start it would enter fullscreen with F11 without having to code it.

### Reproduction

Windows 11, Nuxt 3 with Tauri 2.

Just use setFullScreen.

The fullscreen property in tauri.conf.json do works, but i want to change on run.

### Expected behavior

entering fullscreen...

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22621 x86_64 (X64)
    ✔ WebView2: 128.0.2739.67
    ✔ MSVC:
        - Ferramentas de Build do Visual Studio 2022
        - Visual Studio Community 2022
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 22.3.0
    - yarn: 4.4.0
    - npm: 10.8.1
    - bun: 1.1.26

[-] Packages
    - tauri �: 2.0.0-rc.6
    - tauri-build �: 2.0.0-rc.6
    - wry �: 0.42.0
    - tao �: 0.29.1
    - @tauri-apps/api : 1.6.0
    - @tauri-apps/cli : 2.0.0-rc.12

[-] Plugins

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:3000/
    - framework: Vue.js (Nuxt)
    - bundler: Webpack
```

**Comment by FabianLars** [comment]
For issues like this, please always check the devtools console (right click on the app window -> Inspect). If there's no error/info, try adding a console.log to the function call.

In this case it will probablyyy complain about `window.__TAURI_IPC__` not being found which would be because your `@tauri-apps/api` package is still on v1 and not v2. If that's not it, please try the above suggestions and if that also doesn't work, try reproducing it in a fresh app and send it to us if you reproduced it (so we can take a closer look).

**Comment by thiagovianav** [comment]
> For issues like this, please always check the devtools console (right click on the app window -> Inspect). If there's no error/info, try adding a console.log to the function call.
> 
> In this case it will probablyyy complain about `window.__TAURI_IPC__` not being found which would be because your `@tauri-apps/api` package is still on v1 and not v2. If that's not it, please try the above suggestions and if that also doesn't work, try reproducing it in a fresh app and send it to us if you reproduced it (so we can take a closer look).

Wow. I'm really thankful. 
I don't know why the dependencies just can't solve itself, maybe i should start using Bun.

But yeah, thank you. Really. :) 👍
