### ISSUE TITLE
[bug] WindowBuilder is private struct, cannot create window

### ISSUE THREAD

**Issue by jasonhao518** [tauri-apps/tauri#10920]
### Describe the bug

follow the example described in WindowBuilder to create new window, it failed to start the application, due to the WindowBuilder is a private struct
https://docs.rs/tauri/2.0.0-rc.10/tauri/window/struct.WindowBuilder.html

let window = tauri::window::WindowBuilder::new(app, "editor")
    |                                         ^^^^^^^^^^^^^ private struct

### Reproduction

1. use the cli to create a new project
npm create tauri-app@latest -- --rc 
2. follow the example described https://docs.rs/tauri/2.0.0-rc.10/tauri/window/struct.WindowBuilder.html add a setup
3.  start the application using npm run tauri dev, build error will show up

### Expected behavior

a new window will be created

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.2.0 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06) (Homebrew)
    ✔ cargo: 1.80.1
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.16.0
    - yarn: 4.1.1
    - npm: 10.8.1
    - bun: 1.1.21

[-] Packages
    - tauri 🦀: 2.0.0-rc.10
    - tauri-build 🦀: 2.0.0-rc.9
    - wry 🦀: 0.43.1
    - tao 🦀: 0.30.0
    - tauri-cli 🦀: 1.6.1
    - @tauri-apps/api : 2.0.0-rc.4
    - @tauri-apps/cli : 2.0.0-rc.12

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-shell : 2.0.0-rc.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

### Stack trace

```text
error[E0603]: struct `WindowBuilder` is private
   --> src/lib.rs:13:41
    |
13  |             let window = tauri::window::WindowBuilder::new(app, "label")
    |                                         ^^^^^^^^^^^^^ private struct
    |
note: the struct `WindowBuilder` is defined here
   --> /Users/jasonhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-rc.10/src/window/mod.rs:113:1
    |
113 | / unstable_struct!(
114 | |   #[doc = "A builder for a window managed by Tauri."]
115 | |   struct WindowBuilder<'a, R: Runtime, M: Manager<R>> {
116 | |     manager: &'a M,
...   |
125 | |   }
126 | | );
    | |_^
    = note: this error originates in the macro `unstable_struct` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by FabianLars** [comment]
![{5A7D2242-7AA7-4C85-90DA-95F2C45CF25A}](https://github.com/user-attachments/assets/6d72d304-0995-43b6-8f40-c6a84e743e00)

If you want to use this API you need to add the `unstable` feature flag to the Tauri dependency in Cargo.toml

Are you perhaps looking for WebviewWindowBuilder instead? This is the "stable" API for usecases where you do not need multiwebview (in a single window) support.
