### ISSUE TITLE
[bug] Regression: iframes in windows causes `window.__TAURI_INVOKE__ is not a function` error in console

### ISSUE THREAD

**Issue by abose** [tauri-apps/tauri#10935]
### Describe the bug

If the loaded page has an iframe, then in the js console, an error message will be preinted in the console. 

#### Too many error logs printed to js console.

This may be likeley related to https://github.com/tauri-apps/tauri/pull/10300 ?
and  https://github.com/tauri-apps/tauri/issues/10934

### Reproduction

1. Open the tauri demo app and paste the below code for the main index.html
2. Run the app and see the js console.
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"><title>hello</title>
</head>
<body>
<iframe srcdoc="hello"></iframe>
hello world
</body>
</html>
```

### Expected behavior

No error logs in the console.

### Full `tauri info` output

```text
PS E:\code\tauri-test> npm run tauri info

> tauri-app@0.1.0 tauri
> tauri info


[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 128.0.2739.67
    ✔ MSVC:
        - Visual Studio Build Tools 2019
        - Visual Studio Build Tools 2022
    ✔ rustc: 1.71.0 (8ede3aae2 2023-07-12)
    ✔ cargo: 1.71.0 (cfd3bbd8f 2023-06-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.9.0
    - npm: 10.2.0

[-] Packages
    - tauri [RUST]: 1.7.2
    - tauri-build [RUST]: 1.5.4
    - wry [RUST]: 0.24.11
    - tao [RUST]: 0.16.10
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 1.6.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../src
    - devPath: ../src
```

### Stack trace

```text
VM89:632 
 Uncaught TypeError: window.__TAURI_INVOKE__ is not a function
    at <anonymous>:632:10
    at <anonymous>:633:3
(anonymous)	@	VM89:632
(anonymous)	@	VM89:633
```

### Additional context

More details can be found here:
https://discord.com/channels/616186924390023171/1258736272814374964

![image](https://github.com/user-attachments/assets/5d48d1b5-9234-456b-9a36-77b50cd1c66e)

**Comment by abose** [comment]
Our release is blocked due to this error. Can it be ignored for the release? will it cause any problems if we ship with the error?

**Comment by hmic** [comment]
Maybe this information helps:

The error only occurs when clicking *in* the iframe. It does not happen if I only move the mouse or don't interact with it. Maybe focus related.
I guess something thinks the iframe would/should be tauri enabled as well and fails?!

**Comment by muwoo** [comment]
@abose Have you used Tauri-related APIs in iframes? This is because Tauri does not inject JSAPI into pages within iframes.

**Comment by abose** [comment]
We dont use any tauri related apis in iframes. This just happens in the demo app in Windows. No interaction with theiframe is needed.

**Comment by hmic** [comment]
I can confirm, no tauri integration in the iframe used. Just <iframe></iframe> triggers the error, not even need to load a page.
