### ISSUE TITLE
JS Api : fs.writeBinaryFile output empty file

### ISSUE THREAD

**Issue by davidanquetin** [tauri-apps/tauri#1094]
Hello,
i use tauri with html2pdf.js, which creates a pdf file from which i get content as blob (`datauristring`, or `arraybuffer` are also possible, for example)

I try to write a binary file from this blob, but it outputs an empty file
````javascript

const blob = myPdfContent;

//first get path from dialog box
dialog.save()
    .then((path)=>{

               //then write file with fs
		fs.writeBinaryFile({
			path : path, 
			contents : blob
		})
	   })
````

Am I missing something ? I tried with arrayBuffer, with simple string, with base64 encoded string... always an empty file !
fs.writeFile() works, to create a simple text file..

Thanks.

**Comment by CharlieG42** [comment]
Hi David,

I have the same issue. Do you fixe this problem ?


Thank in advance.

**Comment by Horft** [comment]
I still do have the same problem, but did not find any solution.

**Comment by davidanquetin** [comment]
Hi @CharlieG42 , @Horft 
my solution was .. to change Tauri for Electron :) 
It's a shame , Tauri was easy to manipulate, but I need this fonctionnality.
Good Luck.

**Comment by nothingismagick** [comment]
@davidanquetin - hope to see you back someday. anyway, I believe this was fixed a week or two ago. Are you sure you are using the latest code @Horft ?

**Comment by nothingismagick** [comment]
Here is the PR: https://github.com/tauri-apps/tauri/pull/1136

**Comment by davidanquetin** [comment]
@nothingismagick i did not noticed that there wad a fix for this, great ! I will try Tauri again in another project so ! (it's too late for this one)

**Comment by CharlieG42** [comment]
@nothingismagick @davidanquetin 
Yes, I confirm : this fixed ;).

**Comment by nothingismagick** [comment]
Ok, Then I am closing this issue. Thanks for the report @CharlieG42

**Comment by Cap32** [comment]
Should convert blob to ArrayBuffer first.

```js
const path = await dialog.save();
const contents = await blob.arrayBuffer();
await fs.writeBinaryFile({ path, contents });
```
