### ISSUE TITLE
[bug] mobile_entry_point can not run async or aysnc_runtime,iOS

### ISSUE THREAD

**Issue by reformc** [tauri-apps/tauri#10942]
### Describe the bug

tauri2.0.0-rc
ios17.4

#[cfg_attr(mobile, tauri::mobile_entry_point)]
#[tokio::main]
pub async fn run(){
  let obj = function1().await;
  tauri::Builder::default()
        .manage(obj)
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(tauri::generate_handler![func])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

or

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run(){
  let obj = tauri::async_runtime::block_on(async{
        function1().await
    });
  tauri::Builder::default()
        .manage(obj)
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(tauri::generate_handler![func])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

Both error. But it's OK without async or async runtime

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.6.1 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)

[-] Packages
    - tauri 🦀: 2.0.0-rc.10
    - tauri-build 🦀: 2.0.0-rc.9
    - wry 🦀: 0.43.1
    - tao 🦀: 0.30.0
    - tauri-cli 🦀: 2.0.0-rc.9

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.0-rc.3

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../src

[-] iOS
    - Developer Teams: *
```

**Comment by FabianLars** [comment]
I think the tokio::main annotation there just can't work because the run() method is exposed as an FFI interface or something, so i ignore this part of the question.

What were the error messages for the second code block (the one with block_on)?

**Comment by reformc** [comment]
Sorry, I may not have been rigorously tested before, today the test block_on is working fine, the previous block_on error was caused by other reasons. But #[tokio::main] still doesn't work.

**Comment by laciferin2024** [comment]
Is there a fix for this issue?

**Comment by alballa3** [comment]
i fixed this issue when my identifier inside tauri.conf.json was like this "gym" i change it into com.example.gym then rm -rf src-tauri/gen/android then it worked fine
