### ISSUE TITLE
Is it possible to do cross compiling on WSL

### ISSUE THREAD

**Issue by masloord** [tauri-apps/tauri#1096]
installed toolchains
--------------------

stable-aarch64-unknown-linux-gnu
stable-x86_64-unknown-linux-gnu (default)

installed targets for active toolchain
--------------------------------------

aarch64-unknown-linux-gnu
x86_64-unknown-linux-gnu
x86_64-unknown-linux-musl

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.48.0 (7eac88abb 2020-11-16)

tried:
cargo tauri-bundler --target aarch64-unknown-linux-gnu                   in src-tauri folder 

got :
error: `Failed to read tauri config: Couldn't get tauri config; please specify the TAURI_CONFIG or TAURI_DIR environment variables`

Is it possible to choose the target available in the installed targets for active toolchain

**Comment by masloord** [comment]
Tried running it on rpi 4 to compile a aarch64 toolchain and target  and got the same issues as #941 

On rpi 4 i ran into the problem of when i tried npm i

optipng pre-build test failed 

Way to resolve 
https://github.com/imagemin/optipng-bin/issues/84

**Comment by lucasfernog** [comment]
You can't use the tauri-bundler directly without some environment variables.
I tried cross compiling a few months ago but wasn't successful, a lot of native dependencies goes into compiling the webview crate.

**Comment by nothingismagick** [comment]
I am going to close this issue, but if you want to discuss it further, please consider opening a discussion topic.
