### ISSUE TITLE
[feat] How to call Rust in front-end events to dynamically update Tray?

### ISSUE THREAD

**Issue by wuxiemian** [tauri-apps/tauri#10973]
### Describe the problem

I found that in v1 version I can use tray_handle to change the Tray item, but I can't find relevant documentation in v2 version. How can I achieve this?

### Describe the solution you'd like

I want to dynamically change the title of the Tray menu item

**Comment by amrbashir** [comment]
Use [`app.tray_by_id()`](https://docs.rs/tauri/2.0.0-rc.15/tauri/struct.AppHandle.html#method.tray_by_id) to get an instance of the tray icon and then use [`TrayIcon::set_menu`](https://docs.rs/tauri/2.0.0-rc.15/tauri/tray/struct.TrayIcon.html#method.set_menu) to set a menu
