### ISSUE TITLE
How open blob:http://file on MacOSX Big Sur

### ISSUE THREAD

**Issue by CharlieG42** [tauri-apps/tauri#1097]
Hi all,

I have created a little app for MacOSX Big Sur. My app need to have access at a filedialog when I create a pdf file. At this moment, I have an issue because my app can't find a good app (finder ???) to do this.

Maybe a "problem" with Webkit : https://github.com/tauri-apps/tauri/issues/196

For you is it the reason ? If yes, could you help me to resolve my problem, because I don't understand where do the modifications / configurations (sorry :()

Thank in advance.

Charlie.

**Comment by nothingismagick** [comment]
Please see https://tauri.studio/en/docs/api/js#dialog
