### ISSUE TITLE
[bug] localStorage not syncing between multiple webview windows on Linux

### ISSUE THREAD

**Issue by Ynng** [tauri-apps/tauri#10981]
### Describe the bug

`localStorage` is synced between multiple webview windows on Windows and macOS but not Linux.

On Linux, only 1 window's local storage gets saved when the tauri app exits. The rest of the windows' local storage is out of sync with each other and is disposed of when the tauri app exits.

In the example video below, the 2 windows on the left are running in Fedora 40, their counters are out of sync.
The 2 windows on the right are running in Windows 11, their counters are in sync.

https://github.com/user-attachments/assets/d1113ddc-5264-4426-b606-73cbe2e58f1b

### Reproduction

The counter example shown in the video: https://github.com/Ynng/tauri-localstorage-sync-test

OR:

Reproduce from scratch:
- Create a new Ubuntu LTS 24 virtual machine
- Install "Debian" dependencies from the [Tauri v2 setup guide](https://v2.tauri.app/start/prerequisites/#linux)
- Install Rust `curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh`
- Install nvm `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash`
- Install node `nvm install node`
- Enable pnpm `corepack enable pnpm`
- Create a new Tauri app `pnpm create tauri-app --rc` with React, TypeScript and pnpm
- Modify `tauri.conf.json` to create 2 windows with different labels
- Start the dev server
- Open devtools in both window, locater the "local storage" section
- Add a new key in one window's location storage, observe the local storage entries in the other window

### Expected behavior

The localStorage entries should be in sync between the two windows.
In the reproduction repo, the counter should stay in sync between the two windows.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Ubuntu 24.4.0 x86_64 (X64)
    ✔ webkit2gtk-4.1: 2.44.3
    ✔ rsvg2: 2.58.0
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 22.8.0
    - pnpm: 9.10.0
    - npm: 10.8.2

[-] Packages
    - tauri 🦀: 2.0.0-rc.11
    - tauri-build 🦀: 2.0.0-rc.10
    - wry 🦀: 0.43.1
    - tao 🦀: 0.30.0
    - tauri-cli 🦀: 2.0.0-rc.12
    - @tauri-apps/api : 2.0.0-rc.4
    - @tauri-apps/cli : 2.0.0-rc.13

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-shell : 2.0.0-rc.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Additional context

I get warnings like these sometimes on linux

```
(process:1737224): libsoup-WARNING **: 19:55:42.244: Failed to execute query: database is locked

(process:1737224): libsoup-WARNING **: 19:55:42.244: Failed to execute query: no such table: soup_hsts_policies
```

```
Failed to create hard link from /home/wenqi/.cache/tauri-app/WebKitCache/Version 16/Blobs/3DE2C89C97AF2523D1A566F90E64D1EB6FED08A2 to /home/wenqi/.cache/tauri-app/WebKitCache/Version 16/Records/2D857AF3C0D6CD0AE5639C83ED0E05BB5A00AEED/Resource/D36F616E0D261016A1484FD7FF748035207E4BBE-blob
```

The problem exists with both Tauri v1 and v2

**Comment by greenhat616** [comment]
Maybe you could checkout the plugin `tauri-plugin-store` for a workaround?
Most state managers such as `jotai`, receive a `Storage` interface, like:
```typescript
export interface AsyncStorage<Value> {
    getItem: (key: string, initialValue: Value) => PromiseLike<Value>;
    setItem: (key: string, newValue: Value) => PromiseLike<void>;
    removeItem: (key: string) => PromiseLike<void>;
    subscribe?: Subscribe<Value>;
}
export interface AsyncStringStorage {
    getItem: (key: string) => PromiseLike<string | null>;
    setItem: (key: string, newValue: string) => PromiseLike<void>;
    removeItem: (key: string) => PromiseLike<void>;
    subscribe?: StringSubscribe;
}
```

And `tauri-plugin-store` provide a `onKeyChange` fn to recevie value changed: https://github.com/tauri-apps/tauri-plugin-store/blob/96185a8aedb7a8658de7281cd8ac0149874de425/guest-js/index.ts#L181-L190

You could wrap it to a `Storage` impl to finish the cross platform usage.

**Comment by Ynng** [comment]
Thanks for the suggestion, I'm using tauri store as a work around for now

**Comment by The-Best-Codes** [comment]
I'm still experiencing this issue on Linux. In two different windows of the same application, whether via `npm run tauri dev` or the compiled binary, the `localStorage` is not synced.

<details><summary>tauri info output</summary>
<p>

```
[✔] Environment
    - OS: EndeavourOS Rolling Release x86_64 (X64) (KDE on wayland)
    ✔ webkit2gtk-4.1: 2.50.1
    ✔ rsvg2: 2.61.1
    ✔ rustc: 1.90.0 (1159e78c4 2025-09-14)
    ✔ cargo: 1.90.0 (840b83a10 2025-07-30)
    ✔ rustup: 1.28.2 (e4f3ad6f8 2025-04-28)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 22.19.0
    - pnpm: 10.19.0
    - yarn: 1.22.22
    - npm: 11.6.2
    - bun: 1.3.1

[-] Packages
    - tauri 🦀: 2.9.1
    - tauri-build 🦀: 2.5.1
    - wry 🦀: 0.53.5
    - tao 🦀: 0.34.5
    - @tauri-apps/api  ⱼₛ: 2.9.0
    - @tauri-apps/cli  ⱼₛ: 2.9.1

[-] Plugins
    - tauri-plugin-sql 🦀: 2.3.0
    - @tauri-apps/plugin-sql  ⱼₛ: 2.3.0
    - tauri-plugin-shell 🦀: 2.3.1
    - @tauri-apps/plugin-shell  ⱼₛ: 2.3.1
    - tauri-plugin-log 🦀: 2.7.0
    - @tauri-apps/plugin-log  ⱼₛ: 2.7.0
    - tauri-plugin-clipboard-manager 🦀: 2.3.0
    - @tauri-apps/plugin-clipboard-manager  ⱼₛ: 2.3.0
    - tauri-plugin-fs 🦀: 2.4.2
    - @tauri-apps/plugin-fs  ⱼₛ: 2.4.2
    - tauri-plugin-dialog 🦀: 2.4.0
    - @tauri-apps/plugin-dialog  ⱼₛ: 2.4.0
    - tauri-plugin-opener 🦀: 2.5.0
    - @tauri-apps/plugin-opener  ⱼₛ: 2.5.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Rollup
```

</p>
</details>
