### ISSUE TITLE
Icon for Windows apps is not working

### ISSUE THREAD

**Issue by TroodosCoder** [tauri-apps/tauri#1099]
**Describe the bug**
When Building  windows the windows exe does not get the window icon

**To Reproduce**
build any app from tauri cli

**Expected behavior**
When building the app the icon in the app icon (left top corner) should be visible, but defaults to the standard no icon.
However the icon is there for the actual exe as shown below

**Screenshots**
![image](https://user-images.githubusercontent.com/74708338/100142091-03e44700-2e9c-11eb-9e71-94916f91331d.png)
![image](https://user-images.githubusercontent.com/74708338/100142206-30985e80-2e9c-11eb-947d-5a73f87cbd62.png)

**Platform and Versions (please complete the following information):**

OS: Windows 10
Node: 12.19.0
NPM: 6.14.8
Yarn: N/A
Rustc: 1.47.0

**Additional context**

**Stack Trace**

**Comment by lucasfernog** [comment]
Found the issue. The default ID used by `winres` is wrong. To fix it, change your `src-tauri/src/build.rs`:

Old:
`res.set_icon("icons/icon.ico");`
New:
`res.set_icon_with_id("icons/icon.ico", "32512");`

**Comment by lucasfernog** [comment]
I'll change the default tauri template to include this. Thank you for the report :)
