### ISSUE TITLE
[bug][v2] tauri plugin new [name] creates examples folder

### ISSUE THREAD

**Issue by rtmotiondev** [tauri-apps/tauri#11009]
### Describe the bug

Running `npm run tauri plugin new [name]` creates an examples folder inside tauri-plugin-[name]. 

### Reproduction

npm run tauri plugin new [name]

### Expected behavior

No examples folder. Only required files.

### Full `tauri info` output

```text
tauri info


[✔] Environment
    - OS: Mac OS 14.6.1 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.17.0
    - npm: 10.8.2

[-] Packages
    - tauri 🦀: 2.0.0-rc.11
    - tauri-build 🦀: 2.0.0-rc.10
    - wry 🦀: 0.43.1
    - tao 🦀: 0.30.0
    - @tauri-apps/api : 2.0.0-rc.4
    - @tauri-apps/cli : 2.0.0-rc.13




[-] Plugins
    - tauri-plugin-fs 🦀: 2.0.0-rc.4
    - @tauri-apps/plugin-fs : not installed!
    - tauri-plugin-log 🦀: 2.0.0-rc.2
    - @tauri-apps/plugin-log : not installed!
    - tauri-plugin-notification 🦀: 2.0.0-rc.4
    - @tauri-apps/plugin-notification : not installed!
    - tauri-plugin-shell 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-shell : not installed!
    - tauri-plugin-window-state 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-window-state : not installed!
    - tauri-plugin-store 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-store : not installed!
    - tauri-plugin-dialog 🦀: 2.0.0-rc.6
    - @tauri-apps/plugin-dialog : not installed!
```

**Comment by amrbashir** [comment]
This is an intended behavior and not a bug, as it is meant to setup a project for you to test your plugin with. However I will open a PR to add `--no-example` flag to disable creating examples.

**Comment by rtmotiondev** [comment]
I would like to make the argument that the default setup should not include an examples folder, and the same goes for GitHub workflows. https://github.com/tauri-apps/tauri/issues/11092

The way I see it, if someone is developing a plugin, they likely already have a Tauri project where that plugin will be used or tested. The plugin project should contain only the required scaffolding.

In my case, I just developed my first Tauri plugin for v2 and noticed that there were several files that were not necessary for the plugin itself. These “extras” only add noise to the repository, making it harder to understand the core logic of the plugin and adding unnecessary clutter.

**Comment by amrbashir** [comment]
I agree on the `.github` thing but for the examples part, it is much better to be default since the intended usage is for plugins to be shared by the community and be its own repository.
