### ISSUE TITLE
[bug] Links are handled even with method preventDefault()

### ISSUE THREAD

**Issue by kfiven** [tauri-apps/tauri#11003]
### Describe the bug

When the method `preventDefault()` is explicitly set, the links are still handled and opened in default web browser.

### Reproduction

I noticed it in https://github.com/cinnyapp/cinny-desktop app where https://matrix.to links are internally used in for sharing and navigation. The web app successfully works with this using `preventDefault()` but tauri app don't.

### Full `tauri info` output

```text
N/A
```

**Comment by amrbashir** [comment]
could you try `event.stopPropagation` and `event.stopImmediatePropagation()`

**Comment by kfiven** [comment]
Thanks for the quick response, `event.stopPropagation` seems to fix it.
