### ISSUE TITLE
Events Error

### ISSUE THREAD

**Issue by ShaunSHamilton** [tauri-apps/tauri#1104]
**Describe the bug**
After webpacking the server and client, running `tauri dev` the app initialises, but displays a blank screen. In the dev console, the mentioned error is visible. I interpret this as being an bug related to the Rust api (of which I am using very little)

Here is the app layout:
1) Main Rust Packages:
```rust
use tauri::event::{listen, emit};
use tauri_api::dialog::{pick_folder};
use tauri_api::path::{resource_dir};
use tauri_api::dir::{read_dir};
use nfd::Response::{Okay, OkayMultiple, Cancel};
use cmd::{write_file,read_file};
```
2) Main Nodejs Packages
-- Express
-- node-pty
-- socket.io
-- os
-- http
3) Client is a fairly simple React app (not using CRA)

<details>
<summary>Dev Console Error</summary>

```text

Uncaught ReferenceError: require is not defined
    at eval (external_"events":1)
    at Object.events (bundle.js:34548)
    at __webpack_require__ (bundle.js:34767)
    at eval (index.js:12)
    at Object../node_modules/depd/lib/compat/index.js (bundle.js:371)
    at __webpack_require__ (bundle.js:34767)
    at eval (index.js:10)
    at Object../node_modules/depd/index.js (bundle.js:328)
    at __webpack_require__ (bundle.js:34767)
    at eval (index.js:12)

```
</details>

**Platform and Versions (please complete the following information):**

<details>
<summary>tauri info Output</summary>

```text

Operating System - Windows_NT(10.0.19042) - win32/x64
Microsoft Edge - 44.19041.423.0_neutral__8wekyb3d8bbwe

Node.js environment
  Node.js - 12.17.0
  tauri.js - 0.13.0

Rust environment
  rustc - 1.48.0
  cargo - 1.48.0
  tauri-bundler - 0.9.4

Global packages
  NPM - 6.14.8
  yarn - 1.22.5

App directory structure
/.git
/lesson_files
/node_modules
/public
/server
/src
/src-tauri

App
  tauri.rs - 0.10.0
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../public
  devPath - http://localhost:3000

```
</details>

Relevant lines in `bundle.js`:

```javascript
/***/ "events":
/*!*************************!*\
  !*** external "events" ***!
  \*************************/
/*! dynamic exports */
/*! exports [maybe provided (runtime-defined)] [no usage info] */
/*! runtime requirements: module */
/***/ ((module) => {

"use strict";
eval("module.exports = require(\"events\");;\n\n//# sourceURL=webpack://rustcoder/external_%22events%22?");

/***/ }),
```

I would appreciate any assistance.

On another, probably unrelated note: My server runs up a node process, on development/tauri-dev, but this process is not killed, when the app window is closed, and prevents the app from being re-run, until the process is manually killed in the terminal. Am I missing a `on-close` cmd I can invoke?

_PS: this is an excellent product_

**Comment by lucasfernog** [comment]
Can you give us a repo with a project to reproduce it?

**Comment by ShaunSHamilton** [comment]
@lucasfernog Thank you, for checking back. Here is the repo: https://github.com/Sky020/RustCoder

Although, I think I have determined that the bug is an issue with my webpack setup, and not the Tauri api; I am unable to get the development environment to run up in the browser without a similar error - instead of being an issue with the `"events"` module, it is the `"fs"` module.

Cheers
