### ISSUE TITLE
[bug][v1] Tray icon is blurry in windows

### ISSUE THREAD

**Issue by ayangweb** [tauri-apps/tauri#11067]
### Describe the bug

<img width="238" alt="image" src="https://github.com/user-attachments/assets/1ab81e61-48db-45fd-ad04-47b8ab226233">

Original image: https://raw.githubusercontent.com/EcoPasteHub/EcoPaste/refs/heads/master/src-tauri/assets/tray.ico

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 127.0.2651.105
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-pc-windows-msvc (default)
    - node: 20.14.0
    - pnpm: 9.6.0
    - npm: 10.7.0

[-] Packages
    - tauri [RUST]: 1.7.1
    - tauri-build [RUST]: 1.5.3
    - wry [RUST]: 0.24.10
    - tao [RUST]: 0.16.9
    - @tauri-apps/api [NPM]: 1.6.0
    - @tauri-apps/cli [NPM]: 1.6.0

[-] App
```

**Comment by amrbashir** [comment]
This should be fixed in v2, due to limitations in the tray implementation in v1, there is no plans to backport the fix.
