### ISSUE TITLE
[bug] fresh tauri-app@latest fails to start for libsoup3 and libsoup2 conflict in Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by ildella** [tauri-apps/tauri#11074]
### Describe the bug

A new app created with `npm create tauri-app@latest`, after installig and compiling everything, I get to this and I have not found a way around it. 

```shell
$ yarn tauri dev
     Running BeforeDevCommand (`yarn dev`)

  VITE v5.4.6  ready in 627 ms

  ➜  Local:   http://localhost:1420/
  ➜  Network: use --host to expose
        Info Watching /home/ildella/projects/experiments/tauri-app/src-tauri for changes...
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.12s

(process:1583335): libsoup-ERROR **: 13:06:25.497: libsoup3 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.
```

The system has both `libsoup-3.0-dev` and `libsoup2.4-dev`

### Full `tauri info` output

```text
[✔] Environment
    - OS: Ubuntu 24.4.0 X64
    ✔ webkit2gtk-4.0: 2.44.3
    ✔ rsvg2: 2.58.0
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 22.8.0
    - yarn: 4.5.0
    - npm: 10.8.3
    - bun: 1.1.10

[-] Packages
    - tauri [RUST]: 1.8.0
    - tauri-build [RUST]: 1.5.5
    - wry [RUST]: 0.24.11
    - tao [RUST]: 0.16.10
    - @tauri-apps/api [NPM]: 1.6.0
    - @tauri-apps/cli [NPM]: 1.6.2

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../build
    - devPath: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

### Additional context

The  problem seem related only to libsoup, but for completion I will add that as `libjavascriptcoregtk-4.0` is not available anymore in Ubuntu 24.04, so I did install via apt `libjavascriptcoregtk-4.1-dev` and made some symbolic link changes... Other than that I just follow instructions as they are.

**Comment by FabianLars** [comment]
> made some symbolic link changes

Yeah, and that's the issue probably. Either install webkitgtk 4.0 by enabling the 22.04 repos (https://github.com/tauri-apps/tauri/issues/9662) or just switch to tauri v2 to use webkitgtk 4.1 (`npm create tauri-app@latest -- --rc`). symlink experiments is in my eyes not a good approach and something we cannot offer help with.

**Comment by ildella** [comment]
Makes sense. The rc works out of the box indeed. 

I would consider adding that optional command for the RC in the README.. that would have saved me 2 hours of work this morning.

**Comment by FabianLars** [comment]
Not worth it anymore tbh, we plan to release v2 as stable _very_ soon. Btw, the --rc flag is documented in the [v2 website](https://v2.tauri.app/). All other places like v1 docs and readmes tend to target the latest stable, but yeah, feedback is noted, thanks.
