### ISSUE TITLE
Can't use async generators in javascript on mac Os 10.13.6

### ISSUE THREAD

**Issue by d--b** [tauri-apps/tauri#1108]
**Describe the bug**
Running on MacOs 10.13.6, the javascript engine within Tauri does not support async generators.
Safari, on the same machine does.

**To Reproduce**
1. On an updated MacOs 10.13.6, create a blank Tauri app
2. Go to the console
3. Type `var f = async function* () {}`
4. See error `Unexpected token '*'. Expected an opening '(' before a async function's parameter list.

**Platform and Versions (please complete the following information):**

[tauri]: running info

Operating System - Darwin(17.7.0) - darwin/x64

Node.js environment
  Node.js - 15.2.0
  tauri.js - 0.13.0

Rust environment
  rustc - 1.47.0
  cargo - 1.47.0
  tauri-bundler - 0.9.4

Global packages
  NPM - 7.0.8
  yarn - 1.22.10

App directory structure
/.git
/.idea
/build
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 0.10.0
  mode - no-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../build
  devPath - http://localhost:3000

**Comment by nothingismagick** [comment]
I think that this will be resolved with the next release. If it doesn't solve this problem for you, then another approach you can use is to actually transpile your source to CJS or something along those lines.
