### ISSUE TITLE
[bug] [v2] [ios] Build of iOS does not add the correct capabilities to entitlements

### ISSUE THREAD

**Issue by rtmotiondev** [tauri-apps/tauri#11089]
### Describe the bug

I added the “Sign in with Apple” capability to Xcode (for all targets - automatic signing), but this capability is not included in the entitlements of the final IPA.

For some reason, it works on the iOS Simulator but not on TestFlight. The device logs show: “Authorization failed: Error Domain=AKAuthenticationError Code=-7026 UserInfo={AKClientBundleID=}.”

I think the issue is due to the release build not having the correct capability in the entitlements, even though it’s clearly set in Xcode. I can provide images if that helps.

### Reproduction

Add a capability in Xcode and build an iOS App then verify the release IPA entitlements with:
Unzip the IPA file
codesign -d --entitlements :- Payload/Name of App.app

### Expected behavior

Expected the IPA entitlements to show the added capability. 

### Full `tauri info` output

```text
> tauri info


[✔] Environment
    - OS: Mac OS 14.7.0 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.17.0
    - npm: 10.8.2

[-] Packages
    - tauri 🦀: 2.0.0-rc.15
    - tauri-build 🦀: 2.0.0-rc.12
    - wry 🦀: 0.43.1
    - tao 🦀: 0.30.0
    - @tauri-apps/api : 2.0.0-rc.5
    - @tauri-apps/cli : 2.0.0-rc.16

[-] Plugins
    - tauri-plugin-window-state 🦀: 2.0.0-rc.5
    - @tauri-apps/plugin-window-state : not installed!
    - tauri-plugin-store 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-store : not installed!
    - tauri-plugin-log 🦀: 2.0.0-rc.2
    - @tauri-apps/plugin-log : not installed!
    - tauri-plugin-shell 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-shell : not installed!
    - tauri-plugin-dialog 🦀: 2.0.0-rc.7
    - @tauri-apps/plugin-dialog : not installed!
    - tauri-plugin-notification 🦀: 2.0.0-rc.5
    - @tauri-apps/plugin-notification : not installed!
    - tauri-plugin-fs 🦀: 2.0.0-rc.5
    - @tauri-apps/plugin-fs : not installed!

[-] App
    - build-type: bundle
    - frontendDist: ../src

[-] iOS
    - Developer Teams: <Redacted>
```

**Comment by lucasfernog** [comment]
looks like this is a regression from #10854 , investigating alternatives atm
