### ISSUE TITLE
[bug][v1] Re-granting macOS permissions after every app update

### ISSUE THREAD

**Issue by ayangweb** [tauri-apps/tauri#11085]
### Describe the bug

[EcoPaste](https://github.com/EcoPasteHub/EcoPaste/blob/master/src-tauri/src/plugins/macos_permissions.rs) needs `Accessibility Permissions` and `Full Disk Access Permissions` in macos, but I need to give the permissions again after every update of the app, how can I solve this problem? Thanks!

<img width="491" alt="iShot_2024-09-22_13 45 45" src="https://github.com/user-attachments/assets/69d4f039-4a72-4bc9-8791-e0ae899fbd37">

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.4.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 21.7.1
    - pnpm: 9.11.0
    - yarn: 1.22.22
    - npm: 10.5.0
    - bun: 1.1.26

[-] Packages
    - tauri [RUST]: git+https://github.com/EcoPasteHub/tauri?branch=1.x#d35d152e1c0e87ab42bdc54bdb8c9077c43960bc (1.7.2)
    - tauri-build [RUST]: 1.5.5
    - wry [RUST]: 0.24.11
    - tao [RUST]: git+https://github.com/EcoPasteHub/tao?branch=v0.16#ffadbcd445b633db687d8a5f055253ac8b26f642 (0.16.9)
    - tauri-cli [RUST]: 2.0.0-rc.7
    - @tauri-apps/api [NPM]: 1.6.0
    - @tauri-apps/cli [NPM]: 1.6.0 (outdated, latest: 1.6.2)

[-] App
```

**Comment by FabianLars** [comment]
Permissions on macOS are bound to the signing identity/certificate, so you have to properly sign your app (ad-hoc/self-signing is not enough afaik) for the permissions to persist.

**Comment by ayangweb** [comment]
Thanks, is there a way to get a free signature?

**Comment by FabianLars** [comment]
No, not in Apple-land :/
