### ISSUE TITLE
[feat] I hope to add file.path to obtain the real path of the file.

### ISSUE THREAD

**Issue by Pisceslili** [tauri-apps/tauri#11156]
### Describe the problem

I hope to add file.path to obtain the real path of the file.

### Describe the solution you'd like

I hope to add a property to `file` to obtain the file's path on disk, like in Electron.

**Comment by FabianLars** [comment]
this is not possible. the webviews do not allow us to modify the `file` object to add new properties to it. Only windows has something that's somewhat close to what you're asking https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/specs/WebMessageObjects.md but it would still require an additional function call.
