### ISSUE TITLE
[bug] Can't upgrade a Tauri v2 v2 app on Windows due to same ProductCode

### ISSUE THREAD

**Issue by goenning** [tauri-apps/tauri#11178]
### Describe the bug

It seems like this change ( https://github.com/tauri-apps/tauri/pull/10969/files ) broke our updates on Windows, even though the Upgrade Code remains the same (see table below)

I can go from 1.7.7 to 1.7.8, but it's not possible to go 1.7.8 to 1.7.9 due to the error below.

![image](https://github.com/user-attachments/assets/9c371efa-5170-4001-bd9f-c8ad07431ee1)

|Version|ProductName|ProductCode                                   |UpgradeCode                           |PackageCode                           |Tauri                                 |
|-------|-----------|----------------------------------------------|--------------------------------------|--------------------------------------|--------------------------------------|
|1.7.6  |Aptakube   |{03B0F069-1FA2-4A9B-BEF7-D05D11340D89}        |{9A01B1BB-D16F-5024-B6C4-49466D7730D8}|{AC7A72F1-864A-4555-BC9A-5EEA6900A135}|v1                                    |
|1.7.7  |Aptakube   |{5404D691-23AF-4004-B438-F78DEBC517AB}        |{9A01B1BB-D16F-5024-B6C4-49466D7730D8}|{68863FB5-9D23-4D22-A628-D7D160C66B2C}|v1                                    |
|1.7.8  |Aptakube   |{21050BE2-9EF1-5E08-A36F-45260B21F2C2}        |{9A01B1BB-D16F-5024-B6C4-49466D7730D8}|{DC54E05C-F647-49DF-B0DE-83597C298205}|v2                                    |
|1.7.9  |Aptakube   |{21050BE2-9EF1-5E08-A36F-45260B21F2C2}        |{9A01B1BB-D16F-5024-B6C4-49466D7730D8}|{7A066D33-48C8-4BD2-BB6A-56CFD3F07F5A}|v2                                    |

### Reproduction

The code is not open source, but the releases are available here ( https://github.com/aptakube/aptakube/tags ), if you install 1.7.8, you won't be able to upgrade to 1.7.9

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 x86_64 (X64)
    ✔ WebView2: 129.0.2792.65
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: 1.81-x86_64-pc-windows-msvc (default)
    - node: 22.9.0
    - npm: 10.7.0

[-] Packages
    - tauri 🦀: 2.0.0-rc.15
    - tauri-build 🦀: 2.0.0-rc.12
    - wry 🦀: 0.43.1
    - tao 🦀: 0.30.2
    - @tauri-apps/api : 2.0.0-rc.5
    - @tauri-apps/cli : 2.0.0-rc.16

[-] Plugins
    - tauri-plugin-updater 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-updater : 2.0.0-rc.2
    - tauri-plugin-fs 🦀: 2.0.0-rc.5
    - @tauri-apps/plugin-fs : 2.0.0-rc.2
    - tauri-plugin-window-state 🦀: 2.0.0-rc.5
    - @tauri-apps/plugin-window-state : not installed!
    - tauri-plugin-os 🦀: 2.0.0-rc.1
    - @tauri-apps/plugin-os : 2.0.0-rc.1
    - tauri-plugin-shell 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-shell : 2.0.0-rc.1
    - tauri-plugin-log 🦀: 2.0.0-rc.2
    - @tauri-apps/plugin-log : 2.0.0-rc.1
    - tauri-plugin-dialog 🦀: 2.0.0-rc.7
    - @tauri-apps/plugin-dialog : 2.0.0-rc.1

[-] App
    - build-type: bundle
    - CSP: default-src 'self' data:; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-eval';; connect-src ipc: http://ipc.localhost
    - frontendDist: ../dist
    - devUrl: http://localhost:5173/
    - framework: SolidJS
    - bundler: Vite
```

**Comment by goenning** [comment]
It seems like a temporary fix is to use a custom wix template and set `*` to generate random product code again, but I still don't understand why every guide on the internet says ProductCode should remain static for minor changes, but windows won't let you do an upgrade. @amrbashir You seen to have spent a lot of time on wix lately, any idea why?

**Comment by goenning** [comment]
More references here suggesting using a new productcode on each release
- https://stackoverflow.com/questions/74441310/wix-installer-error-another-version-of-this-product-is-already-installed-insta
- https://stackoverflow.com/questions/500703/how-to-get-wix-to-update-a-previously-installed-version-of-a-program

Another interesting one from ( https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios#identities-and-naming )

> Many of the MSI concepts are not very intuitive and over complicated. One of the the biggest MSI blunder is the deployment identities. For example, one would think that MSI identity ProductId uniquely identifies a product. And when you hear 'product' you may immediately think of Notepad++, Visual Studio 2015 or Windows 10... However in MSI domain ProductId is a unique identifier of a single msi file. Thus two msi for Notepad++ v6.7.4 and v6.7.5 have different ProductIds even if they are deploying the same product Notepad++.

What wixsharp does is:
```csharp
ProductId = CalculateProductId(guid.Value, Version);
```

Where guid.Value is a static string on their project setup, but Version changes on each build.

So maybe Tauri should do the same and generate the GUID based on ProductName+Version instead of just ProductName?

**Comment by amrbashir** [comment]
@goenning thanks for bringing this up and the extensive research, I will open a PR shortly to revert the PR and release a new version
