### ISSUE TITLE
drag and drop file and get full path

### ISSUE THREAD

**Issue by codelover2k** [tauri-apps/tauri#11177]
### Describe the problem

I am using react with react-dropzone. With that you can drag and drop files an get a File object.
Because of security reasons, you do not get the full path of the file, so you can not pass the pash to terminal programs.

### Describe the solution you'd like

I would like to have the full path of the file when I drag and drop the file.
In Electron it works. As far as I know they disabled the security option of the browser, so the File object contains the full path.

**Comment by amrbashir** [comment]
This is something the webview doesn't provide and we can't inject unfortunately as the webview doesn't provide an API for that. 

We have an alternative which is `window.onFileDropEvent` for v1 here https://tauri.app/v1/api/js/window/#onfiledropevent and `window.onDragDropEvent` https://beta.tauri.app/reference/javascript/api/namespacewindow/#ondragdropevent
