### ISSUE TITLE
Capture cmd/ctrl c + c

### ISSUE THREAD

**Issue by cannedconcept** [tauri-apps/tauri#11211]
Hi,

Not much of a developer, more a ux designer. Am trying to find out if tauri would allow me to capture key event whilst running in background: ctrl c + c

So ctrl press and hold and then twice c.

For example deepl translate desktop app uses this to capture a selected text in another program to OS clipboard and then insert it into the deepl app.

Would this be possible with tauri?

Many thnx!

**Comment by amrbashir** [comment]
Checkout the global shortcut plugin https://tauri.app/plugin/global-shortcut/

**Comment by cannedconcept** [comment]
Thank you, we did. Couldn't make it work. Can you share a light as on how to achieve it?

**Comment by cannedconcept** [comment]
> Checkout the global shortcut plugin https://tauri.app/plugin/global-shortcut/

Thank you, we did. Couldn't make it work. Can you share a light as on how to achieve it?
