### ISSUE TITLE
[bug] configuration not extended properly

### ISSUE THREAD

**Issue by aleixjf** [tauri-apps/tauri#11221]
### Describe the bug

Testing the new Tauri release, I've just realized that the option of extending the default tauri.conf.json doesn't seem to be working.

As explained in the [docs](https://v2.tauri.app/develop/configuration-files/#extending-the-configuration), one can extend the default tauri.conf.json with either a path pointing to another partial tauri.conf.json file or by providing the raw JSON string direclty.

### Reproduction

Just launch the Tauri app with the following command:

`npm run tauri dev -c '{ "productName": "My App Beta", "identifier": "com.myorg.myappbeta", "mainBinaryName": "BetaApp", "app": { "windows": [{ "title": "Beta app" }] } }'`

The app title should reflect the new app.windows.title, but it doesn't, it shows the default one. This is just one example to show it isn't working, but many other settings can be tested.

### Expected behavior

That it actually merges the conf files or the default tauri.conf.json with the provided one. In the above case, it should reflect the merged/provided window title, but it doesn't, as shown in the attached screenshot.
<img width="1268" alt="image" src="https://github.com/user-attachments/assets/d187a67b-cf0f-4c45-bd5a-9a0a1958619a">

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 15.0.0 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04) (Homebrew)
    ✔ cargo: 1.81.0
    ✔ rustup: 1.27.1 (2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.18.0
    - pnpm: 9.12.0
    - yarn: 1.22.22
    - npm: 10.1.0

[-] Packages
    - tauri 🦀: 2.0.1
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.44.1
    - tao 🦀: 0.30.3
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli : 2.0.1

[-] Plugins
    - tauri-plugin-log 🦀: 2.0.1
    - @tauri-apps/plugin-log : not installed!

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:4200/
    - framework: Angular
    - bundler: Vite
```

**Comment by aleixjf** [comment]
If pointing to another conf file it doesn't work either and shows an error in the console:
`unexpected argument 'src/assets/clients/chatprise/tauri.conf.json' found`
<img width="1268" alt="image" src="https://github.com/user-attachments/assets/f8feccc2-ced1-4af4-ab4a-8059b51560b8">

**Comment by FabianLars** [comment]
npm needs an extra `--` to forward the argument to tauri, so it's `npm run tauri dev -- -c '...'`
