### ISSUE TITLE
[feat] Make @tauri-apps/api available from WASM like web-sys

### ISSUE THREAD

**Issue by RagibHasin** [tauri-apps/tauri#11229]
### Describe the problem

It is frustrating having to create Rust bindings for Tauri APIs when using a Rust frontend framework.

### Describe the solution you'd like

Tauri should provide a Rust glue crate defining all built-in APIs like `web-sys`.

**Comment by FabianLars** [comment]
Duplicate of https://github.com/tauri-apps/tauri/issues/5354
