### ISSUE TITLE
[feat] Change initialization_script script on runtime

### ISSUE THREAD

**Issue by binbard** [tauri-apps/tauri#11226]
### Describe the problem

Currently it seems like we can't change initialization_script on runtime but with tauri::WindowBuilder only

### Describe the solution you'd like

I wish we could change initialization_script dynamically via window handle

**Comment by amrbashir** [comment]
I am not sure what you mean, initialization script as you see is a script that will be executed upon initialization. I think you're looking for "evaluating" a script at runtime, in this case you need https://docs.rs/tauri/latest/tauri/webview/struct.WebviewWindow.html#method.eval

**Comment by binbard** [comment]
I am talking about this: 

tauri::WindowBuilder::new(app, "main", tauri::WindowUrl::App("index.html".into())).initialization_script(INIT_SCRIPT)

Usecase: Suppose we have a variable x
If x is true, script1 should be executed else script2. Or we could just change this script.

**Comment by amrbashir** [comment]
something like this?
```rs
let mut builder = tauri::WindowBuilder::new(app, "main", tauri::WindowUrl::App("index.html".into()));
if x {
  builder = builder.initialization_script(INIT_SCRIPT);
} else {
  builder = builder.initialization_script(ANOTHER_INIT_SCRIPT)
}

```

**Comment by binbard** [comment]
How to set after the window is build.

let mut builder = tauri::WindowBuilder::new(app, "main", tauri::WindowUrl::App("index.html".into()));
if x {
  builder = builder.initialization_script(INIT_SCRIPT);
} else {
  builder = builder.initialization_script(ANOTHER_INIT_SCRIPT)
}

let window = builder.build()?;

// i will pass this to any function

change_script(window);

----------------------------

fn change_script(window: tauri:Window){
 window.set_initialization_script(NEW_SCRIPT);                 // there is nothing like this
}

**Comment by amrbashir** [comment]
As i explained earlier initialization scripts are scripts added when initializing the webview not after. What is your use case?
