### ISSUE TITLE
[feat] DeepSeek Platform support

### ISSUE THREAD

**Issue by petrusali** [tauri-apps/tauri#11232]
### Describe the problem

I'd like to have a support of DeepSeek platform

### Describe the solution you'd like

I'd like to have a support of DeepSeek platform

**Comment by chatterzhao** [comment]
The following seems to have a bit of an advertising purpose, but I haven't received any payment from them!

Is this referring to: https://www.deepseek.com? This is a very good model, especially with good coding abilities, and it's very cost-effective, about $0.14/M. In a comparative [evaluation](https://mp.weixin.qq.com/s/XMZyddlDbGpLA1YwXSETBw), the coding ability of o1-preview (planning) + deepseek (coding) is comparable to that of o1-preview (planning) + o1-mini (coding).

My understanding is that this is a large language model or API, and I don't see any purposefulness in the issues mentioned above. In my understanding, large language models supporting Tauri means they are trained on Tauri documentation or code from projects developed using Tauri during the training process, which is not within Tauri's control.

**Comment by FabianLars** [comment]
Closing as there seems to be no action for us to take. If we misunderstood you, please expand your feature request with more details.
