### ISSUE TITLE
[bug] Android development error: Execution failed for task ':buildSrc:compileKotlin'.

### ISSUE THREAD

**Issue by raisfeld-ori** [tauri-apps/tauri#11239]
### Describe the bug

I created a brand new android/tauri project in order to try out tauri with android, but after running ```npm create tauri-app@latest```, ```npm i```, ```npm run tauri android init```, ```npm run tauri android dev``` I got this error:

`
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileKotlin'.
> Could not resolve all files for configuration ':buildSrc:kotlinCompilerPluginClasspathMain'.
   > Could not resolve org.jetbrains.kotlin:kotlin-sam-with-receiver-compiler-plugin-embeddable:1.9.23.
     Required by:
         project :buildSrc
      > Could not resolve org.jetbrains.kotlin:kotlin-sam-with-receiver-compiler-plugin-embeddable:1.9.23.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-sam-with-receiver-compiler-plugin-embeddable/1.9.23/kotlin-sam-with-receiver-compiler-plugin-embeddable-1.9.23.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-sam-with-receiver-compiler-plugin-embeddable/1.9.23/kotlin-sam-with-receiver-compiler-plugin-embeddable-1.9.23.pom'.
               > repo.maven.apache.org

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 5s
\Failed to assemble APK: command ["C:\\Users\\raisf\\Desktop\\projects\\Hibori-v2\\src-tauri\\gen/android\\gradlew.bat", "--project-dir", "C:\\Users\\raisf\\Desktop\\projects\\Hibori-v2\\src-tauri\\gen/android"] exited with code 1: command ["C:\\Users\\raisf\\Desktop\\projects\\Hibori-v2\\src-tauri\\gen/android\\gradlew.bat", "--project-dir", "C:\\Users\\raisf\\Desktop\\projects\\Hibori-v2\\src-tauri\\gen/android"] exited with code 1
    Error Failed to assemble APK: command ["C:\\Users\\raisf\\Desktop\\projects\\Hibori-v2\\src-tauri\\gen/android\\gradlew.bat", "--project-dir", "C:\\Users\\raisf\\Desktop\\projects\\Hibori-v2\\src-tauri\\gen/android"] exited with code 1: command ["C:\\Users\\raisf\\Desktop\\projects\\Hibori-v2\\src-tauri\\gen/android\\gradlew.bat", "--project-dir", "C:\\Users\\raisf\\Desktop\\projects\\Hibori-v2\\src-tauri\\gen/android"] exited with code 1`
    
I know the error is a configuration error, and so it could be fixed manually, but I wanted to check if I missed any commands or packages that would help run the project autometically (since I work with multiple frontend devs, and I would need to fix it manually for every one of them)

### Reproduction

Like I said, this is on a brand new tauri project intended for android, so just run the following commands (assuming you call the project "project"):
```
npm create tauri-app@latest
cd project
npm i
npm run tauri android init
npm run tauri android dev
```
and you should get the error

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 x86_64 (X64)
    ✔ WebView2: 129.0.2792.79
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-gnu (default)
    - node: 20.9.0
    - pnpm: 9.4.0
    - yarn: 1.22.22
    - npm: 10.8.3
    - bun: 1.1.2

[-] Packages
    - tauri 🦀: 2.0.1
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.44.1
    - tao 🦀: 0.30.3
    - tauri-cli 🦀: 1.5.6
    - @tauri-apps/api : 2.0.1
    - @tauri-apps/cli : 2.0.1

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.1
    - @tauri-apps/plugin-shell : 2.0.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Stack trace

```text
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileKotlin'.
> Could not resolve all files for configuration ':buildSrc:kotlinCompilerPluginClasspathMain'.
   > Could not resolve org.jetbrains.kotlin:kotlin-sam-with-receiver-compiler-plugin-embeddable:1.9.23.
     Required by:
         project :buildSrc
      > Could not resolve org.jetbrains.kotlin:kotlin-sam-with-receiver-compiler-plugin-embeddable:1.9.23.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-sam-with-receiver-compiler-plugin-embeddable/1.9.23/kotlin-sam-with-receiver-compiler-plugin-embeddable-1.9.23.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-sam-with-receiver-compiler-plugin-embeddable/1.9.23/kotlin-sam-with-receiver-compiler-plugin-embeddable-1.9.23.pom'.
               > repo.maven.apache.org

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 5s
\Failed to assemble APK: command ["C:\\Users\\raisf\\Desktop\\projects\\Hibori-v2\\src-tauri\\gen/android\\gradlew.bat", "--project-dir", "C:\\Users\\raisf\\Desktop\\projects\\Hibori-v2\\src-tauri\\gen/android"] exited with code 1: command ["C:\\Users\\raisf\\Desktop\\projects\\Hibori-v2\\src-tauri\\gen/android\\gradlew.bat", "--project-dir", "C:\\Users\\raisf\\Desktop\\projects\\Hibori-v2\\src-tauri\\gen/android"] exited with code 1
    Error Failed to assemble APK: command ["C:\\Users\\raisf\\Desktop\\projects\\Hibori-v2\\src-tauri\\gen/android\\gradlew.bat", "--project-dir", "C:\\Users\\raisf\\Desktop\\projects\\Hibori-v2\\src-tauri\\gen/android"] exited with code 1: command ["C:\\Users\\raisf\\Desktop\\projects\\Hibori-v2\\src-tauri\\gen/android\\gradlew.bat", "--project-dir", "C:\\Users\\raisf\\Desktop\\projects\\Hibori-v2\\src-tauri\\gen/android"] exited with code 1`
```

### Additional context

I'm not sure how important this is, but I had low wifi when running the command, and it was under a proxy, so that might've affected the project

**Comment by FabianLars** [comment]
> I'm not sure how important this is, but I had low wifi when running the command, and it was under a proxy, so that might've affected the project

Very very likely related. The error suggests it wasn't able to download everything it needs and the URLs it reports are correct. Doesn't look like a timeout (slow internet) so make sure your proxy is configured correctly maybe? There should hopefully be many resources on how to do that for Android (Studio) development.

**Comment by raisfeld-ori** [comment]
yeah, I kind of forgot to update this (since I also stopped working on the project that required tauri) but after running the commands on a better pc without the proxy I was 100% able to run and build the project
