### ISSUE TITLE
Issue with WriteBinaryFile to create a PDF

### ISSUE THREAD

**Issue by CharlieG42** [tauri-apps/tauri#1125]
**Describe the bug**
WriteBinaryFile doesn't work to create a PDF

**To Reproduce**
Here a very simple example where I read a PDF and I want create a new PDF in a second step :

```javascript
import * as tauriDialog from "tauri/api/dialog";
import * as tauriFs from "tauri/api/fs";
let a = await tauriFs.readBinaryFile("./template/temp1.pdf")
await tauriDialog
    .save({})
    .then((data) => {this.pathTauri = data;})
    .catch((err) => console.log("Error:", err));
await tauriFs.writeBinaryFile({ path: this.pathTauri, contents: a });
```

The PDF create is corrupted and it can not be read.

**Expected behavior**
How create a correct PDF ?

**Platform and Versions (please complete the following information):**
tauri]: running info
Operating System - Darwin(20.1.0) - darwin/x64

Node.js environment
  Node.js - 14.15.0
  tauri.js - 0.13.0

Rust environment
  rustc - 1.48.0
  cargo - 1.48.0
  tauri-bundler - 0.9.4

Global packages
  NPM - 6.14.10
  yarn - 1.22.10

App
  tauri.rs - 0.10.0
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - unset
  devPath - unset

**Comment by copyandexecute** [comment]
same error

**Comment by nothingismagick** [comment]
Fix incoming.
https://github.com/tauri-apps/tauri/pull/1136
