### ISSUE TITLE
[feat] Allow MSI version overide

### ISSUE THREAD

**Issue by n1ght-hunter** [tauri-apps/tauri#11253]
### Describe the problem

When building a msi only version in the format of `major.minor.patch.build` numeric only.
this is pretty annoying as its not semvar and we use `major.minor.patch-hash` which doesn't work at all on with wix

### Describe the solution you'd like

add a env overide to manually set the version for msi.
something like `TAURI_MSI_VERSION`  this would allow people to not have to change there core version because of it

### Alternatives considered

having to change the version on windows or not use msi

### Additional context

https://github.com/tauri-apps/tauri/blob/a49a19ffa304f031fb1a04d31a567cc7f42a380a/crates/tauri-bundler/src/bundle/windows/msi/mod.rs#L435

**Comment by FabianLars** [comment]
Would a platform specific config (https://v2.tauri.app/reference/config/#platform-specific-configuration) be enough or does the inner tauri app itself need the correct "normal" (non wix) version?

Not disagreeing with the feature request, just looking for a workaround until something is implemented.

**Comment by n1ght-hunter** [comment]
i have setup a workaround for setting the version on windows but i do think it would make more sense to use a overide env since it is the only part of tauri that i know of that doesnt work with a semvar version
