### ISSUE TITLE
[bug] [Tauri V2] Why is it not automatically maximized when dragging the top toolbar to the top of windows in v2?

### ISSUE THREAD

**Issue by moom-en** [tauri-apps/tauri#11265]
### Describe the bug

In v1, you can use the mouse to drag the toolbar to the top of the windows, and the window will be automatically maximized, otherwise the window will be restored. However, this function seems to be gone in v2, but dragging the toolbar on the maximized form will restore this function.

### Full `tauri info` output

```text
Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 129.0.2792.79
    ✔ MSVC:
        - Visual Studio Enterprise 2022
        - Visual Studio ���ɹ��� 2022
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ Cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.17.0
    - yarn: 1.22.19
    - npm: 10.8.2
```

**Comment by amrbashir** [comment]
I can't reproduce, please provide full information requested in the issue, and a repro. 

If you are using `data-tauri-drag-region` make sure to enable `core:window:allow-start-dragging` permission in your capability.
