### ISSUE TITLE
cors problem

### ISSUE THREAD

**Issue by serdartaylan** [tauri-apps/tauri#11260]
I developed an application with angular v17 that I use only myself.
The application sends post requests to local addresses (192.168.1.x).
I started using the application by first building it with electron. i am still using it. but the build time takes too long. the size is too big. it opens too late. it is too cumbersome. all bad possible situations are unfortunately in electron. it shows the file by calling index.html, not like a web. i think it is not like http://localhost/index.html.

I met tauri. perfect. very light, very fast, builds very quickly. size is very small, very small (down from 150mb to 10mb - portable). in short tauri is perfect. 

Unfortunately when I try with both v1.6.1 and v2.0 I get a cors error when I send a request. the counter servers are electronic devices so I can't change any settings like header information. i can't interfere with the counter devices.

how can i solve this problem in tauride.

```
$ tauri info

[✔] Environment
    - OS: Mac OS 15.0.0 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.16.0
    - npm: 10.8.3

[-] Packages
    - tauri 🦀: 2.0.1
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.44.1
    - tao 🦀: 0.30.3
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli : 2.0.2

[-] Plugins
    - tauri-plugin-log 🦀: 2.0.1
    - @tauri-apps/plugin-log : not installed!

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:4200/
    - framework: Angular
    - bundler: Webpack
```

**Comment by FabianLars** [comment]
Do you have the full error message for us? If it's a `Access-Control-Allow-Origin` issue (i know you said cors, but i've seen that getting mixed up all the time) then this would indeed require server-side changes.

If it's really cors, it could only be disabled on Windows.

----

Depending on the actual issues (again, please show us error messages so we know what's actually going on), using Tauri's [http api](https://v2.tauri.app/plugin/http-client/) may help since its executed on the rust side where cors isn't a thing.

**Comment by serdartaylan** [comment]
hi @FabianLars,

Thank you for your answer.
I could not make a test due to the intensity of my work.

The answer I get now is as follows.

`Access to XMLHttpRequest at 'http://192.168.1.54/path' from origin 'http://tauri.localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Can we really solve this problem without interfering with the server (192.168.1.54) from which I make the request?

**Comment by FabianLars** [comment]
> Can we really solve this problem without interfering with the server (192.168.1.54) from which I make the request?

If you cannot modify the server and your app needs to run on platforms other than Windows then you must do one of the following:
- use tauri's http plugin
- make the requests on the rust side
- make the requests in a sidecar (imo overkill if just for this)

The webviews do not allow us to get around the acao check.

**Comment by lastlink** [comment]
cors issue appeared to me was when embedding resources and updating the resource format in `tauri.conf.json`. https://v2.tauri.app/develop/resources/

from 
* option 1
```json
{
  "bundle": {
    "resources": [
      "./path/to/some-file.txt",
      "/absolute/path/to/textfile.txt",
      "../relative/path/to/jsonfile.json",
      "some-folder/",
      "resources/**/*.md"
    ]
  }
}
```

to
* option 2
```json
{
  "bundle": {
    "resources": {
      "/absolute/path/to/textfile.txt": "resources/textfile.txt",
      "relative/path/to/jsonfile.json": "resources/jsonfile.json",
      "resources/": "",
      "docs/**/*md": "website-docs/"
    }
  }
}
```
ended up sticking with option 1 and doing some workarounds for specific paths since option 2 caused me to have those nasty cors issues.
