### ISSUE TITLE
[example-app] background-color for `<select>` is getting ignored on some systems

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#1126]
**Describe the bug**
`<select>` element is not fully customizable

**To Reproduce**
1. open example app in xfce, and, probably other less mainstreamy window managers

**Expected behavior**
dont expect `<select>` element to _ever_ be freely customizable – its the curse of the web since forever.
even across 3 major OSes on default installs might be unclear causes for this

**Platform and Versions (please complete the following information):**
OS: Ubuntu 20.04 with xfce + i3

**Screenshots**
![PrtScr--20201229@210314_20201229201614](https://user-images.githubusercontent.com/59403389/103311604-17467d00-4a1b-11eb-9c52-cffa59b5f17a.png)

**Comment by nothingismagick** [comment]
Yes, I am really not sure what we can do here. I would recommend using a component library to work around this and just not use `<select>`.

**Comment by ghost** [comment]
i mean, it is in the example app ( https://github.com/tauri-apps/tauri/blob/dev/tauri/examples/communication/dist/index.html#L237 )

should it be changed to some custom component there too?
