### ISSUE TITLE
[docs] How to change the protocol type of webview service

### ISSUE THREAD

**Issue by alindas** [tauri-apps/tauri#11271]
When I upgraded Tauri/api to 1.6.0, I found that the packaged program WebView was running on HTTPS, which blocked access to some of my internal resources. May I know what I can do to change the webview service protocol to HTTP?

This is the difference in webview service addresses between the two versions before and after the upgrade？

![image](https://github.com/user-attachments/assets/692ed742-4180-4159-aa29-53ae86c1d041)

![image](https://github.com/user-attachments/assets/79ece73a-9b81-49c2-b8ae-c1e416e0587a)

**Comment by FabianLars** [comment]
https://v1.tauri.app/v1/api/config/#securityconfig.dangeroususehttpscheme or upgrade to v2 where it's currently always http.
