### ISSUE TITLE
[feat] Is it possible to create a vpn using tun2socks

### ISSUE THREAD

**Issue by somnusx** [tauri-apps/tauri#11277]
### Describe the problem

I want to develop a VPN application. It would be better if I could use tauri to call tun2socks to create a VPN. It would be better if there is a better solution.

### Describe the solution you'd like

I want to develop a VPN application

**Comment by FabianLars** [comment]
Are we talking about https://github.com/xjasonlyu/tun2socks ? If so then i guess you'll need a go [sidecar](https://v2.tauri.app/develop/sidecar/)

**Comment by somnusx** [comment]
> Are we talking about https://github.com/xjasonlyu/tun2socks ? If so then i guess you'll need a go [sidecar](https://v2.tauri.app/develop/sidecar/)

Yes, but I want to develop a VPN application on the Android platform. Do I need to call VpnService? How to call it?

**Comment by xiongmao-f** [comment]
> > Are we talking about https://github.com/xjasonlyu/tun2socks ? If so then i guess you'll need a go [sidecar](https://v2.tauri.app/develop/sidecar/)
> 
> Yes, but I want to develop a VPN application on the Android platform. Do I need to call VpnService? How to call it?

Hello, I have the same need. How did you finally realize it?
