### ISSUE TITLE
[bug]  build `.exe` under windows, no icon

### ISSUE THREAD

**Issue by RSS1102** [tauri-apps/tauri#11299]
### Describe the bug

When I built tauri in Windows, it succeeded, but when I went to the nsis directory and found my `.exe` installer, I found that it had no icon.

When I found some exe programs built by tauri in the community, they still had no icon even if they were built through github action.

(tuari-v2) https://github.com/yaakapp/app/releases/tag/v2024.10.1
(tuari-v1) https://github.com/fivim/fivim/releases/tag/v2.4.3

![image](https://github.com/user-attachments/assets/a82470b9-6d84-459d-879f-18d6a765d7c5)

### Reproduction

 https://github.com/RSS1102/cherry-markdown-v2

### Full `tauri info` output

```text
`npm run tauri info`



[✔] Environment
    - OS: Windows 10.0.22621 x86_64 (X64)
    ✔ WebView2: 129.0.2792.52
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.2.0
    - pnpm: 9.10.0
    - yarn: 1.22.22
    - npm: 9.6.6

[-] Packages
    - tauri 🦀: 2.0.2
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.44.1
    - tao 🦀: 0.30.3
    - @tauri-apps/api : 2.0.2
    - @tauri-apps/cli : 2.0.2

[-] Plugins

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Additional context

Probably the same: https://github.com/tauri-apps/tauri/issues/11220

**Comment by FabianLars** [comment]
I think this requires setting https://v2.tauri.app/reference/config/#installericon, otherwise it will always use the NSIS icon.

> Probably the same: https://github.com/tauri-apps/tauri/issues/11220

Nope, your build isn't failing with an error like in 11220

**Comment by RSS1102** [comment]
> I think this requires setting https://v2.tauri.app/reference/config/#installericon, otherwise it will always use the NSIS icon.
> 
> > Probably the same: #11220
> 
> Nope, your build isn't failing with an error like in 11220

You are right, but why not default to NSIS, like the green part.
Perhaps a new discussion should be initiated?
![image](https://github.com/user-attachments/assets/4f97572e-42e9-480b-b50b-2465805754b5)
