### ISSUE TITLE
Compile It as a library to use with an api

### ISSUE THREAD

**Issue by lmtr0** [tauri-apps/tauri#1129]
good day, I am working on a project that needs a webview, but i am in a big trouble. I started looking to use Cef but it is very Large and make some parts of my project break. Then I looked into building an embeder for servo and / or netsurf and I also gived up because of the complexity.
Then I discovered that you guys, so my question is: Is it possible to build it as a shared library and then call it from c code?

My objectives are:
* Platform independent window with some events (resize, close, new document request (if possible) )
* open a specific url like (http) doens't need https but it would be good to have
* execute javascript and (if possible) webassembly
* Inter process communication if possible (I can use sockets if they are not possibe)

**Comment by nothingismagick** [comment]
@litch0 - please checkout https://github.com/webview/webview - that is the underlying lib that we wrote rust bindings for.

**Comment by lmtr0** [comment]
Thank you
