### ISSUE TITLE
[bug] Tauri migrate doesn't update use tauri::api::process::Command

### ISSUE THREAD

**Issue by ZelCloud** [tauri-apps/tauri#11301]
### Describe the bug

tauri::api::process::Command isn't updated with tauri migrate

### Reproduction

https://github.com/dieharders/example-tauri-python-server-sidecar

### Expected behavior

tauri::api::process::Command  is updated 

### Full `tauri info` output

```text
.
```

**Comment by amrbashir** [comment]
unfortunately our current migration tool can't handle migrating Rust files, you'll have to migrate manually, see

**Comment by ZelCloud** [comment]
I think the link you wanted to post after the see to the docs is missing?

**Comment by amrbashir** [comment]
apologies, here is the link https://docs.rs/tauri-plugin-shell/latest/tauri_plugin_shell/process/index.html
