### ISSUE TITLE
[feat] Is it possible to change scroll speed of the WebView?

### ISSUE THREAD

**Issue by CrendKing** [tauri-apps/tauri#11313]
### Describe the problem

The default scroll speed is too slow. The only way to change it is through Control Panel -> Mouse -> Vertical Scrolling -> Lines per page. However, it needs to be a very large number to be usable in the WebView, but then every native apps will be screwed. There needs to be a better scaling factor for the scrolling speed.

### Describe the solution you'd like

Ideally a config value for `tauri.config.json` to change the scroll speed scaling factor.

### Alternatives considered

With Edge itself, user could access the `edge://flags/` page and activate the `Windows Scrolling Personality` feature, which according to [Scrolling personality improvements in Microsoft Edge](https://blogs.windows.com/msedgedev/2020/04/02/scrolling-personality-improvements/) improves user experience, and seems to even have a percentage-based behavior, i.e. the taller the window is, the more vertical scroll speed it is. But I don't know a way to activate the feature for the main WebView window.

### Additional context

```
[✔] Environment
    - OS: Windows 10.0.22631 x86_64 (X64)
    ✔ WebView2: 129.0.2792.79
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 22.9.0
    - npm: 10.8.3
    - bun: 1.1.30

[-] Packages
    - tauri 🦀: 2.0.2
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.44.1
    - tao 🦀: 0.30.3
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli : 2.0.2

[-] App
    - build-type: build
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

**Comment by FabianLars** [comment]
afaik none of the webviews have explicit settings for this. The edge feature may be helpful if you find CLI argument versions for that which you could specify in tauri's additionalBrowserArgs config. Of course that'd be windows only so for cross platform support you may have to look into JS based solutions (idk but they are probably pretty bad).
