### ISSUE TITLE
[feat] Submenu for 18n

### ISSUE THREAD

**Issue by nyssance** [tauri-apps/tauri#11326]
### Describe the problem

Such as quit() about() should add a parameter for text.

### Describe the solution you'd like

```rs
  pub fn paste(mut self) -> Self {
    self
      .items
      .push(PredefinedMenuItem::paste(self.manager, None).map(|i| i.kind()));
    self
  }
```
PredefinedMenuItem have text parameter, but now always pass None. If user want to i18n, must rewrite all code.

**Comment by amrbashir** [comment]
for now, you can use `submenu.item(&PredefindeMenuItem::paste(&app, Some(text)))` https://docs.rs/tauri/latest/tauri/menu/struct.SubmenuBuilder.html#method.item
