### ISSUE TITLE
[feat] Be able to set default system tray item on Windows

### ISSUE THREAD

**Issue by lars-berger** [tauri-apps/tauri#11339]
### Describe the problem

Via [`SetMenuDefaultItem`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setmenudefaultitem?redirectedfrom=MSDN), an option in the system tray can be emphasized and marked as default. Like so:

![image](https://github.com/user-attachments/assets/b8c4b4f8-b537-4066-96d8-4c0252e0a7cf)
_`Show Bluetooth Devices` is the default item_

This requires the `HMENU` handle to the menu, which is currently inaccessible through the Tauri system tray API. It is, however, accessible through `hpopupmenu()` in the `tray_icon` crate.

### Describe the solution you'd like

Either:
1. Expose `hpopupmenu()` to get the `HMENU` handle as done in the `tray_icon` crate. Devs can then call `SetMenuDefaultItem` themselves.
2. Be able to pass a flag via the `MenuBuilder` API to mark an item as default.

**Comment by amrbashir** [comment]
I have exposed the API in https://github.com/tauri-apps/tauri/pull/11354, as I couldn't find an equivalent API for [SetMenuDefaultItem](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setmenudefaultitem?redirectedfrom=MSDN) on Linux and macOS.
