### ISSUE TITLE
[feat] `@tauri-apps/plugin-http` didn't fallback to browser fetch API

### ISSUE THREAD

**Issue by ngdangtu-vn** [tauri-apps/tauri#11347]
### Describe the problem

Since Tauri isn't meant for web platform so it is not a bug. But do you think it would be great to have a fallback config for api in case of dev want to make a pwa version?

```txt
Uncaught (in promise) TypeError: window.__TAURI_INTERNALS__ is undefined
```

![image](https://github.com/user-attachments/assets/c9ed0307-f92c-4fd2-b7c0-8ee95d7b177a)

### Describe the solution you'd like

Maybe a config file that use flowcontrol programming language (js, ts, rust) would be nice. We will only have to return the alternative api or custom function as fallback in case the native lib didn't support.

```ts
const frontend_web = {
   '@tauri-apps/plugin-http': '/* custom fn in rust can be passed through with invoke ? */'
}
export default { frontend: { web: frontend_web } }
```

### Alternatives considered

I haven't tried yet, but I think maybe I could write a wrapper for these API. But it would create greatly redundant code. Having an entry file seems more nested :?

### Additional context

At these early (not as early as beta but still), I think if we can have a fallback web version would be nice because not all tauri apps can run stable on linux wayland. Typically is mine where it will cause fake frozen for the whole system and make my pc become and an ideal heater for the european winter. On the other hand,

**Comment by amrbashir** [comment]
The `fetch` method from the plugin will not fallback to the browser's built-in as this is hidden behavior and not intended.

I would recommend doing this in your app instead:
```js
import { fetch as tauriFetch } from "@tauri-apps/http-plugin"

const fetch = async (...args) => {
  return window.isTauri
    ? await tauriFetch(args)
    : await fetch(args)
}
```
