### ISSUE TITLE
[bug] Incorrect @latest tag for @tauri-apps/cli@latest

### ISSUE THREAD

**Issue by on1force** [tauri-apps/tauri#11367]
### Describe the bug

I tried on a different project yesterday and the @latest tag is working fine which is v2.0.3, but somehow right now when using @latest it's installing v1.6.3

### Reproduction

(npm / pnpm) (install/add) -D @tauri-apps/cli@latest

### Expected behavior

add the latest v2.0.3

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 129.0.2792.89
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 22.4.1
    - pnpm: 9.5.0
    - npm: 10.8.2
    - bun: 1.1.30
    - deno: deno 2.0.0

[-] Packages
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 1.6.3

[-] App
```

### Stack trace

```text
=
```

### Additional context

![Screenshot 2024-10-15 094948](https://github.com/user-attachments/assets/0264533a-ad69-44c1-b0cd-059b148d9edb)

**Comment by Hassunaama** [comment]
Seems to be fixed now (see the [npm package page](https://www.npmjs.com/package/@tauri-apps/cli))
