### ISSUE TITLE
[feat] 现在双击边框会全屏，怎么把这个事件禁用

### ISSUE THREAD

**Issue by Sunrisies** [tauri-apps/tauri#11370]
### Describe the problem

现在双击边框会全屏，怎么把这个事件禁用

### Describe the solution you'd like

现在双击边框会全屏，怎么把这个事件禁用

**Comment by chrox** [comment]
Would you please paste the output of command `pnpm tauri info` or `npm tauri info` in your issue description? It's better to provide more info such as: what did you try to config and how did the way in [the documentation of the Window Customization](https://v2.tauri.app/plugin/window-customization/) not work.

**Comment by Sunrisies** [comment]
类似于，我双击中间这个区域就会全屏，怎么把这个事件禁用掉

![image](https://github.com/user-attachments/assets/cf7ff422-959d-4ee8-b61f-3c697c15c2dc)

**Comment by Sunrisies** [comment]
> Would you please paste the output of command `pnpm tauri info` or `npm tauri info` in your issue description? It's better to provide more info such as: what did you try to config and how did the way in [the documentation of the Window Customization](https://v2.tauri.app/plugin/window-customization/) not work.
类似于，我双击中间这个区域就会全屏，怎么把这个事件禁用掉

![image](https://github.com/user-attachments/assets/8705f68c-325e-4012-b99d-a2b51338c4b2)

**Comment by chrox** [comment]
Did you try setting the `maximizable: false` in the `tauri.conf.json`. See https://v2.tauri.app/reference/config/#windowconfig

**Comment by FabianLars** [comment]
Please post the output of the `tauri info` command and ideally also provide a minimal reproduction example we can try.

**Comment by Sunrisies** [comment]
> maximizable

使用这个可以禁用掉双击全屏的事件，谢谢
