### ISSUE TITLE
[bug] New window (target="_blank") does not get "withGlobalTauri" configuration

### ISSUE THREAD

**Issue by sheshadri** [tauri-apps/tauri#11378]
### Describe the bug

Any new window that open using  "target='_blank'"  link in the Tauri app does not acquire tauri.conf.json app settings .

### Reproduction

Add <a href="https://v2.tauri.app/" target="_blank">Go Tauri</a> in index.html and after the new windows opens it does not acquire tauri.conf.json app settings 

### Expected behavior

Any new window opened by clicking "href" should also load tauri.conf.json app settings 

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 x86_64 (X64)
    ✔ WebView2: 129.0.2792.89
    ✔ MSVC: 
        - Visual Studio Build Tools 2019
        - Visual Studio Build Tools 2022
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.8.0
    - npm: 10.8.2

[-] Packages
    - tauri 🦀: 2.0.4
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.46.1
    - tao 🦀: 0.30.3
    - tauri-cli 🦀: 1.5.9
    - @tauri-apps/api : 2.0.2
    - @tauri-apps/cli : 2.0.3

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.1
    - @tauri-apps/plugin-shell : 2.0.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - bundler: Vite
```

**Comment by amrbashir** [comment]
Can you explain a bit more, I don't understand what is the expected behavior. Also what  tauri.conf.json app settings it doesn't aquire?

**Comment by sheshadri** [comment]
Thanks for replying, I will explain in detail. 

I am using Tauri to load external link (something like https://example.com) .. and  tauri.conf.json has these settings(pasting minimal).

"app": {
    "**withGlobalTauri**": true,
    "windows": [
      {
        "title": "Example",
        "width": 800,
        "height": 600,
        "label": "example",
        "url": "https://example.com",
        "contentProtected": true
        
      }
    ],
    "security": {
      "csp": null
    }
  },

I have  withGlobalTauri (which basically gives me window.__TAURI__  as true  in my external website)  and if I click on any of the href links in my external website which has "target=_blank", it opens a new Tauri window and in that new window window.__TAURI__ is null where as the parent window  window.__TAURI__ is true, so the issue here is second window which has been opened does not get withGlobalTauri setting .

**Comment by amrbashir** [comment]
I think you need to configure your capability to allow remote url access, see https://tauri.app/security/capabilities/#remote-api-access
