### ISSUE TITLE
[bug] `fetch` and `XHR` response has no `content-range` header

### ISSUE THREAD

**Issue by chrox** [tauri-apps/tauri#11371]
### Describe the bug

I don't know if it is intended or not but in both `asset` protocol and the `http` protocol the `content-range` header is discarded in `fetch` response. Without the `content-range` header [successive range requests cannot be performed such as in pdf.js](https://github.com/mozilla/pdf.js/blob/master/src/display/network.js#L159-L160). 

This is a normal `fetch` in macOS Safari browser:
![image](https://github.com/user-attachments/assets/b4b11de1-8bf2-4a80-b7f7-33265d8305a6)

And this is a `fetch` in Tauri app in macOS:
![image](https://github.com/user-attachments/assets/392174b0-be49-4543-bbfb-e67204a5b7d4)

The static HTTP server `http://localhost:9000` is started with `http-server -p 9000 -d . --cors` for testing purpose.

****

And the `asset` protocol is also affected in Tauri app.

![image](https://github.com/user-attachments/assets/234e0c69-e0ce-455a-a388-71bff578ebb8)

Note that in the network inspector the `content-range` header is present but it's like being discarded somewhere in the `fetch` response.

![image](https://github.com/user-attachments/assets/b54d202f-7356-45ad-87cb-f29fef79020e)

---
I also try to figure out where the response headers are intercepted. At least the `wry` layer hold the intact headers:

```
[2024-10-15][14:44:11][wry::wkwebview::class::url_scheme_handler][INFO] wry::custom_protocol::handle; uri="asset://localhost/%2FUsers%2Fchrox%2FDocuments%2FReadest%2FBooks%2F3ec18259cf5e8a916a553f14ebf4f7d3%2Fl11manual_zh.pdf"
[2024-10-15][14:44:11][tracing::span][INFO] wry::custom_protocol::call_handler;
response headers: {
    "content-type": "application/pdf",
    "content-range": "bytes 0-65535/91848117",
    "accept-ranges": "bytes",
    "application/pdf": "content-type",
    "content-length": "65536",
    "65536": "content-length",
    "access-control-allow-origin": "http://localhost:3000",
}
```
Let's set aside for now these two malformed headers `"65536": "content-length" and "application/pdf": "content-type" ` that were introduced by [recent code refactoring of wry](https://github.com/tauri-apps/wry/pull/1316); the `wry` url_scheme_handler writes the correct `content-range` header. I tried to add `Access-Control-Allow-Headers: *` or `Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Range` in `tauri/src/protocol/asset.ts`  but it makes no difference on the response headers of `fetch` and `XHR`. I have no clue on how the response headers are sent to the Javascript world. Could someone give a hint?

### Full `tauri info` output

```text
> tauri "info"


[✔] Environment
    - OS: Mac OS 14.3.1 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 22.9.0
    - pnpm: 9.12.1
    - yarn: 1.22.22
    - npm: 10.8.3

[-] Packages
    - tauri 🦀: 2.0.3
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.46.1
    - tao 🦀: 0.30.3
    - @tauri-apps/api : 2.0.2
    - @tauri-apps/cli : 2.0.3

[-] Plugins
    - tauri-plugin-http 🦀: 2.0.1
    - @tauri-apps/plugin-http : 2.0.0
    - tauri-plugin-os 🦀: 2.0.1
    - @tauri-apps/plugin-os : 2.0.0
    - tauri-plugin-fs 🦀: 2.0.1
    - @tauri-apps/plugin-fs : 2.0.0
    - tauri-plugin-log 🦀: 2.0.1
    - @tauri-apps/plugin-log : 2.0.0
    - tauri-plugin-dialog 🦀: 2.0.1
    - @tauri-apps/plugin-dialog : 2.0.0

[-] App
    - build-type: bundle
    - CSP: style-src 'self' 'unsafe-inline' blob: asset: http://asset.localhost; default-src 'self' 'unsafe-inline' blob: customprotocol: asset: http://asset.localhost ipc: http://ipc.localhost; frame-src 'self' blob: asset: http://asset.localhost; img-src 'self' blob: data: asset: http://asset.localhost
    - frontendDist: ../out
    - devUrl: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Webpack
```

**Comment by chrox** [comment]
This is my `app.security` in `tauri.conf.json`:
```
    "security": {
      "csp": {
        "default-src": "'self' 'unsafe-inline' blob: customprotocol: asset: http://asset.localhost ipc: http://ipc.localhost",
        "img-src": "'self' blob: data: asset: http://asset.localhost",
        "style-src": "'self' 'unsafe-inline' blob: asset: http://asset.localhost",
        "frame-src": "'self' blob: asset: http://asset.localhost"
      },
      "assetProtocol": {
        "enable": true,
        "scope": {
          "allow": ["$RESOURCE/**", "$DOCUMENT/**/*", "$APPDATA/**/*", "$TEMP/**/*"],
          "deny": []
        }
      }
    }
```

And this is the capability config:
```
 {
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "default",
  "description": "enables the default permissions",
  "windows": ["main"],
  "permissions": [
    "core:default",
    "fs:default",
    {
      "identifier": "fs:scope-document-recursive",
      "allow": [
        {
          "path": "$DOCUMENT/**/*"
        }
      ],
      "deny": []
    },
    {
      "identifier": "fs:scope-appdata-recursive",
      "allow": [
        {
          "path": "$APPDATA/Readest/**/*"
        }
      ],
      "deny": []
    },
    {
      "identifier": "fs:allow-appdata-read",
      "allow": [
        {
          "path": "$APPDATA/settings.json"
        }
      ]
    },
    {
      "identifier": "fs:allow-appdata-write",
      "allow": [
        {
          "path": "$APPDATA/settings.json"
        }
      ]
    },
    "dialog:default",
    "os:default",
    "http:default"
  ]
}

```

**Comment by chrox** [comment]
This might be related to #10426.

**Comment by chrox** [comment]
UPDATE:
Adding a `access-control-expose-headers: content-range` solves this problem.
![image](https://github.com/user-attachments/assets/e5e107ab-e55b-4047-b345-aca2de2549bf)

If there is no security concern about this I will send a PR later after more testing.

**Comment by amrbashir** [comment]
@chrox feel free to open a PR and @tweidinger will take a look from security prespective.

**Comment by amrbashir** [comment]
> Let's set aside for now these two malformed headers `"65536": "content-length" and "application/pdf": "content-type" ` that were introduced by [recent code refactoring of wry](https://github.com/tauri-apps/wry/pull/1316);

Could you open an issue or better a PR if you have a fix?

**Comment by chrox** [comment]
Sure.

**Comment by chrox** [comment]
According to [MDN on Access-Control-Expose-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers), `content-range` is not a `simple response header` and not  exposed to client scripts by default in CORS response except that it's listed in the `Access-Control-Expose-Headers` header. The first example I provided above however is not a CORS request thus not affected. 

It sounds pretty safe to expose the `content-range` header in a `range` request in the `asset` protocol. I'm opening a PR to do this.

**Comment by eleroy** [comment]
Hello,

I feel like my problem is related to this issue but I'm not sure.

I try to set the currentTime video attribute to seek into a video that is bundled in my app. But the video keeps on going back to the start whenever I set currentTime.

If I override the content-range response header in the dev tools, it works but I'm not really sure how to do this. 

I've tried using convertToSrc but i get errors. (error 500). Whenever I set csp I get _Applying inline style violates the following Content Security Policy directive 'style-src 'self' 'unsafe-inline'_

How can I override this header ?

EDIT:

- The CSP problem is due to the fact I use Expo + react native web
- I did make it work by using the asset protocol but I wonder why this header is not present by default for local media.

**Comment by chrox** [comment]
> Hello,
> 
> I feel like my problem is related to this issue but I'm not sure.
> 
> I try to set the currentTime video attribute to seek into a video that is bundled in my app. But the video keeps on going back to the start whenever I set currentTime.
> 
> If I override the content-range response header in the dev tools, it works but I'm not really sure how to do this.
> 
> I've tried using convertToSrc but i get errors. (error 500). Whenever I set csp I get _Applying inline style violates the following Content Security Policy directive 'style-src 'self' 'unsafe-inline'_
> 
> How can I override this header ?
> 
> EDIT:
> 
> * The CSP problem is due to the fact I use Expo + react native web
> * I did make it work by using the asset protocol but I wonder why this header is not present by default for local media.

If you are on Android, it might be related to https://github.com/tauri-apps/tauri/issues/12019.
