### ISSUE TITLE
[bug] dialog function will be triggered twice when in a global shortcut callback function

### ISSUE THREAD

**Issue by littlepy** [tauri-apps/tauri#11394]
### Describe the bug

hey, I use tauri2 and vue3 to create a app, I wanna register a global shortcut, when the keys are pressed, a message box will be show, but the message box show twice. the code is as bellow.

`async function initApp() {
    const app = createApp(App)
    app.use(naive)
    app.use(createPinia())
    app.use(router)
    app.mount('#app')

    const registered = await isRegistered('ctrl+shift+y')
    if (!registered) {
        register('ctrl+shift+y', async ()=>{
            console.log("Shortcut triggered")
            router.push('/about')
            await message("short key pressed", "Message")
        })
    }
}

initApp()
`

### Expected behavior

the shortcut callback function should execute once.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 x86_64 (X64)
    ✔ WebView2: 129.0.2792.89
    ✔ MSVC: Visual Studio 生成工具 2022
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.15.1
    - pnpm: 9.12.1
    - npm: 10.7.0

[-] Packages
    - tauri 🦀: 2.0.2
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.44.1
    - tao 🦀: 0.30.3
    - @tauri-apps/api : 2.0.2
    - @tauri-apps/cli : 2.0.2 (outdated, latest: 2.0.3)

[-] Plugins
    - tauri-plugin-global-shortcut 🦀: 2.0.1
    - @tauri-apps/plugin-global-shortcut : 2.0.0
    - tauri-plugin-fs 🦀: 2.0.1
    - @tauri-apps/plugin-fs : 2.0.0
    - tauri-plugin-shell 🦀: 2.0.1
    - @tauri-apps/plugin-shell : 2.0.0
    - tauri-plugin-os 🦀: 2.0.1
    - @tauri-apps/plugin-os : 2.0.0
    - tauri-plugin-store 🦀: 2.0.1
    - @tauri-apps/plugin-store : 2.0.0
    - tauri-plugin-notification 🦀: 2.0.1
    - @tauri-apps/plugin-notification : 2.0.0
    - tauri-plugin-dialog 🦀: 2.0.1
    - @tauri-apps/plugin-dialog : 2.0.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by amrbashir** [comment]
This is because the handler for a shortcut is triggered once for pressing, and another time for releasing the shortcut, you need to check the event passed to the handler:
```ts
await register('CommandOrControl+Shift+C', (event) => {
  if (event.state === 'Pressed') {
    console.log('Shortcut triggered')
  }
})
```

**Comment by littlepy** [comment]
> This is because the handler for a shortcut is triggered once for pressing, and another time for releasing the shortcut, you need to check the event passed to the handler:
> 
> ```ts
> await register('CommandOrControl+Shift+C', (event) => {
>   if (event.state === 'Pressed') {
>     console.log('Shortcut triggered')
>   }
> })
> ```

It works, thank you very much 👍
