### ISSUE TITLE
[bug] White screen issue

### ISSUE THREAD

**Issue by App-developer-269** [tauri-apps/tauri#11397]
### Describe the bug

white screen after running npx tauri dev 
![Screenshot from 2024-10-17 15-54-11](https://github.com/user-attachments/assets/5fc8e6c5-972d-4c72-9efe-c9f239b759bc)

### Full `tauri info` output

```text
[✔] Environment
    - OS: Ubuntu 24.4.0 x86_64 (X64)
    ✔ webkit2gtk-4.1: 2.44.3
    ✔ rsvg2: 2.58.0
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 18.19.1
    - npm: 9.2.0

[-] Packages
    - tauri 🦀: 2.0.4
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.46.2
    - tao 🦀: 0.30.3
    - tauri-cli 🦀: 2.0.1
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli : 2.0.3

[-] Plugins
    - tauri-plugin-log 🦀: 2.0.1
    - @tauri-apps/plugin-log : not installed!

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:5173/
    - framework: React
    - bundler: Vite
```

### Additional context

I am using tauri v2, and followed this docs [https://v2.tauri.app/start/](url)
i am getting this in terminal 
```text
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/WebKitNetworkProcess: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/WebKitNetworkProcess: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE
```
 after running npx tauri dev 

Even if i use this workflow [https://v2.tauri.app/distribute/pipelines/github/#example-workflow]([https://v2.tauri.app/distribute/pipelines/github/#example-workflow](https://github.com/tauri-apps/tauri/issues/url)) still getting same white screen problem

**Comment by FabianLars** [comment]
This is an issue with vscode installed via snap. You have multiple workarounds:
1) Try executing `unset GTK_PATH` before running tauri (doesn't always work afaik)
2) Run tauri dev in a terminal outside of vscode
3) Re-install vscode via something else than snap

**Comment by App-developer-269** [comment]
Even if i use this workflow [https://v2.tauri.app/distribute/pipelines/github/#example-workflow](https://github.com/tauri-apps/tauri/issues/url) still getting same white screen problem

**Comment by App-developer-269** [comment]
This ```Run tauri dev in a terminal outside of vscode ``` is working but, when i build app it is still showing white blank screen
This is my tauri config json file
```text  {
  "$schema": "../node_modules/@tauri-apps/cli/config.schema.json",
  "productName": "Name",
  "version": "0.2.0",
  "identifier": "com.Name.app",
  "build": {
    "frontendDist": "../dist",
    "devUrl": "http://localhost:5173",
    "beforeDevCommand": "npm run dev",
    "beforeBuildCommand": "npm run build"
  },
  "app": {
    "windows": [
      {
        "title": "Name",
        "width": 800,
        "height": 600,
        "resizable": true,
        "fullscreen": false
      }
    ],
    "security": {
      "csp": null
    }
  },
  "bundle": {
    "active": true,
    "targets": "all",
    "icon": [
      "icons/32x32.png",
      "icons/128x128.png",
      "icons/128x128@2x.png",
      "icons/icon.icns",
      "icons/icon.ico"
    ]
  }
}
```

**Comment by FabianLars** [comment]
If you start the built app from inside a terminal session, do you see any errors?

Can you try running it with `WEBKIT_DISABLE_DMABUF_RENDERER=1` and/or `WEBKIT_DISABLE_COMPOSITING_MODE=1` env vars?

**Comment by App-developer-269** [comment]
If i build the code on windows os, using ```npx tauri build``` it is working fine.

but why on Ubuntu and this github workflow  [https://v2.tauri.app/distribute/pipelines/github/#example-workflow](url) are not building code correctly and resulting in white screen problem

**Comment by App-developer-269** [comment]
This is my workflow and i only build for windows
```name: "publish"

on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      contents: write

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm" # Cache set to npm.

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: install frontend dependencies
        # If you don't have `beforeBuildCommand` configured you may want to build your frontend here too.
        run: npm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces __VERSION__ with the app version.
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
```
This workflow runs perfectly fine without any error, and genrates exe file.
but when i install the app on windows using exe file,  it only shows white screen

**Comment by endepointe** [comment]
> If you start the built app from inside a terminal session, do you see any errors?
> 
> Can you try running it with `WEBKIT_DISABLE_DMABUF_RENDERER=1` and/or `WEBKIT_DISABLE_COMPOSITING_MODE=1` env vars?

Setting that env var also worked for AMD. Here is the tauri info:

```bash
tauri "info"


[✔] Environment
    - OS: Linux Mint 21.3.0 x86_64 (X64)
    ✔ webkit2gtk-4.1: 2.46.3
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.82.0 (f6e511eec 2024-10-15)
    ✔ cargo: 1.82.0 (8f40fc59f 2024-08-21)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 22.11.0
    - pnpm: 9.13.2
    - npm: 10.9.0

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.1
    - tao 🦀: 0.30.8
    - @tauri-apps/api : 2.1.1
    - @tauri-apps/cli : 2.1.0

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.2
    - @tauri-apps/plugin-shell : 2.0.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by Shay7sev** [comment]
maybe u used proxy,i got similar error.
after `DEBUG=* pnpm tauri dev`,i got
`next:router-server:main requestHandler! http://localhost:3153/ {
  matchedOutput: undefined,
  statusCode: 308,
  resHeaders: {},
  bodyStream: false,
  parsedUrl: { pathname: '/localhost:3153/', query: [Object: null prototype] {} },
  finished: true
}` cause to my http_proxy in my terminal
using `unset http_proxy` and `unset https_proxy` can handle this problem

**Comment by Xczer** [comment]
I tried changing the port it solved the issue temporarily but the permanent fix was

to move the react.svg from assests directory under src directory to /public directory
and changing the code in App.tsx/jsx to change the svg icon imports particularly the react one.

Afterwards it worked flawlessly... hope this helps.
