### ISSUE TITLE
Fullscreen is not work for me

### ISSUE THREAD

**Issue by aim-leo** [tauri-apps/tauri#1139]
**Describe the bug**
Hello, I'm try to move my project from electron-packager, and I'm trying to set my app auto fullscreen when it start. my project is generated by vue-cli, and add vue-cli-plugin-tauri.

The app can serve and build success, but can not auto fullscreen.

My system info:
- vue-cli-plugin-tauri v0.14.0
- tauri-api v0.7.5
- tauri v0.10.0
- rustc v.149.0
- tauri-bundler v0.9.4
- node.js v14.4.0
- npm v6.14.5

And my tauri.conf.json:
```
{
  "ctx": {},
  "tauri": {
    "embeddedServer": {
      "active": true
    },
    "bundle": {
      "active": true,
      "targets": ["appimage"],
      "identifier": "com.tauri.dev",
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "resources": [],
      "externalBin": [],
      "copyright": "",
      "category": "DeveloperTool",
      "shortDescription": "",
      "longDescription": "",
      "deb": {
        "depends": [],
        "useBootstrapper": false
      },
      "osx": {
        "frameworks": [],
        "minimumSystemVersion": "",
        "useBootstrapper": false
      },
      "exceptionDomain": ""
    },
    "allowlist": {
      "all": true
    },
    "window": {
      "title": "Tauri App",
      "resizable": true,
      "fullscreen": true
    },
    "security": {
      "csp": "default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'"
    },
    "inliner": {
      "active": true
    }
  }
}
```
Any response will be grateful.

**Comment by nklayman** [comment]
Currently fullscreen is not implemented. We are waiting on https://github.com/webview/webview/issues/458 to be resolved. The author of webview (the library Tauri uses under the hood) said that they will create an 'extension' that will add fullscreen support, but we haven't heard from them in a while. We should probably remove the `fullscreen` property from the default `tauri.conf.json` as it doesn't work yet.

**Comment by rx2347** [comment]
Any news on this one? Not having fullscreen support makes Tauri way less attractive for everyone building kiosk systems.

**Comment by nklayman** [comment]
We actually have it working in the dev branch of Tauri, just hang on till the next release 🙂

**Comment by lucasfernog** [comment]
I'll close this issue since this will be available on the next release :partying_face:

**Comment by dev-itzarun** [comment]
Hai @lucasfernog , @nklayman 


Setting this option to true `fullscreen": true` in **tauri.conf.json**  open the app in fullscreen

`
            "windows": [
      {
        "fullscreen": true,
        "height": 600,
        "resizable": true,
        "title": "Test App",
        "width": 800
      }
    ]
`

But when if Fullscreen is requested from JavaScript the title bar not getting hidden

![image](https://user-images.githubusercontent.com/109509109/180623287-64c4d060-d4d7-4fb5-ac6f-8a6336d2b29d.png)


Give a solution For this

**Comment by melMass** [comment]
> Setting this option to true `fullscreen": true` in **tauri.conf.json** open the app in fullscreen

That's exactly what you ask it to do...
I think you are looking for  `tauri.allowlist.window.setFullscreen`

**Comment by nikkxgod** [comment]
I don't know if it's actual or not, but I'll attach it nonetheless:

src-tauri/tauri.conf.json -> 
tauri{
    windows{
       "fullscreen" : true 
    }
}
