### ISSUE TITLE
[feat] tauri subcommand `add-plugin`

### ISSUE THREAD

**Issue by Goodjooy** [tauri-apps/tauri#11417]
### Describe the problem

When I migrated from V1 to V2, I had to add a lot of plugins to `package.json` and `Cargo.toml`, which was a bit tedious.

### Describe the solution you'd like

Is it possible to have an additional command that adds relevant dependencies to both `package.json` and `src-tauri/Cargo.toml`.

## Example 
For example, if you have the command `cargo tauri add` to add a plugin, and now I want to add the plugin `cli`, the command would be :
```bash
cargo tauri add cli@2
```
Then the command will perform the following actions:
- Add `@tauri-app/tauri-plugin-cli` to `package.json`.
- Add `tauri-plugin-cli` to `src-tauri/Cargo.toml`.

**Comment by FabianLars** [comment]
`cargo tauri add cli@2` - well, you should have tried running that one 😅 What you're asking for is implemented in the v2 cli and you even got the syntax right-ish (maybe omit the `@2` if npm complains).
