### ISSUE TITLE
window.tauri is undefined

### ISSUE THREAD

**Issue by JedimEmO** [tauri-apps/tauri#1142]
**Describe the bug**
I have set up a tauri app with a rust backend, and it seems to be working fine. I can use `window.__TAURI__.promisified` to communicate with the backend. However, `window.tauri` is undefined, and I can't seem to find a good reason why it should be this way

**Platform and Versions (please complete the following information):**
[tauri]: running info

Operating System - Linux(5.4.0-60-generic) - linux/x64

Node.js environment
  Node.js - 10.19.0
  tauri.js - 0.14.0

Rust environment
  rustc - 1.49.0-nightly
  cargo - 1.48.0-nightly
  tauri-bundler - 0.9.4

Global packages
  NPM - 6.14.4
  yarn - Not installed

App directory structure
/dist
/node_modules
/src
/src-tauri

App
  tauri.rs - 0.10 (no lockfile) (outdated, latest: 0.11.0)
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist/ui
  devPath - http://localhost:4000

**Comment by nothingismagick** [comment]
We just released new versions. Can you please update everything?

```
tauri.rs - 0.10 (no lockfile) (outdated, latest: 0.11.0)
```
Note the outdated bit there...

**Comment by JedimEmO** [comment]
updated to 0.11, same result

**Comment by JedimEmO** [comment]
I was probably being stupid, and should most likely be using `import { emit, listen } from 'tauri/api/event'` rather than the global object anyhow. Closing.

**Comment by dragonworx** [comment]
As of Jan 2022 the imports are now `import { app, fs} from "@tauri-apps/api"` etc. This got me too the first time 😊

**Comment by vasilvestre** [comment]
> 

How are we supposed to deal with this ? I'm use readDir and window is not defined while I do not use window there

**Comment by ralyodio** [comment]
So what's the fix?

**Comment by ralyodio** [comment]
> As of Jan 2022 the imports are now `import { app, fs} from "@tauri-apps/api"` etc. This got me too the first time 😊

How do you do this? Can yo give example?

**Comment by ralyodio** [comment]
```
    startBtn.onclick = () => {
      window.Tauri.invoke("start_tshark")
        .then((response) => {
          output.textContent = response;
        })
        .catch((error) => {
          output.textContent = error;
        });
    };
```

how do i fix `window.Tauri` not available in browser context?
