### ISSUE TITLE
[feat] Allow frontend `fetch` 

### ISSUE THREAD

**Issue by vangork** [tauri-apps/tauri#11438]
### Describe the problem

My app would communite with the web server with REST API calls. The `http` plugin works well until the web server is put behind the cloudflare CDN. After some debuging, I found the issue is releated with tls fingerprint. Then I tried to call `fetch` directly without http plugin considering that cloudflare won't block webview2 tls fingerprint, but it just reported CORS error. Tried to overwrite the `origin` as per https://github.com/tauri-apps/tauri/discussions/4912, but the CORS error persist. BTW, my app is built with tauri 2.0.4. 

### Describe the solution you'd like

Please give some hack guidence on how to call frontend `fetch` even though it might not be offically supported.

**Comment by FabianLars** [comment]
If you only need it to work on Windows you can add the `--disable-web-security` flag (of course never really recommended as its name suggests) in the additionalBrowserArgs config.

On all other platforms we cannot disable cors with the current webviews.

**Comment by vangork** [comment]
@FabianLars I also tried this arg, but all the ipc call would fail with error of "missing Origin header"
