### ISSUE TITLE
[bug] in JavaScript api: I can't create `IconMenuItem` and `CheckMenuItem`

### ISSUE THREAD

**Issue by RSS1102** [tauri-apps/tauri#11435]
### Describe the bug

1. When I tried to create CheckMenuItem, the child node CheckMenuItem could not be displayed, but there was no error in devtools.
![image](https://github.com/user-attachments/assets/26cc12ff-8d32-46ae-a0f0-8d88adcad11f)

2. When I tried to create IconMenuItem, IconMenuItem couldn't accept my custom pictures and convert them into icons.
![image](https://github.com/user-attachments/assets/0df2ca44-178a-417c-a145-ada806f17447)

### Reproduction

https://github.com/RSS1102/tauri-app/blob/main/src/App.vue#L8

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22621 x86_64 (X64)
    ✔ WebView2: 129.0.2792.52
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.2.0
    - pnpm: 9.10.0
    - yarn: 1.22.22
    - npm: 9.6.6

[-] Packages
    - tauri 🦀: 2.0.4
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.46.1
    - tao 🦀: 0.30.3
    - @tauri-apps/api : 2.0.3
    - @tauri-apps/cli : 2.0.3

[-] Plugins
    - tauri-plugin-fs 🦀: 2.0.1
    - @tauri-apps/plugin-fs : 2.0.1
    - tauri-plugin-shell 🦀: 2.0.1
    - @tauri-apps/plugin-shell : 2.0.1
    - tauri-plugin-dialog 🦀: 2.0.1
    - @tauri-apps/plugin-dialog : 2.0.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

### Additional context

possibly related https://github.com/tauri-apps/tauri/issues/10563

**Comment by FabianLars** [comment]
Can you show your code too? Did you register the icon(s) as top level items or inside submenus?

**Comment by RSS1102** [comment]
> Can you show your code too? Did you register the icon(s) as top level items or inside submenus?

Sorry, I accidentally deleted my repo link just now.
https://github.com/RSS1102/tauri-app/blob/main/src/App.vue#L8

**Comment by amrbashir** [comment]
For the icon menu item error, you are missing `image-ico` or `image-png` feature flag, I will update the documentation of the `icon` field. 

Also you don't need to call `transformImage` yourself, it will be called internally, just pass `./icon.png`.

As for the other issue where where the submenu is not created, I will open a PR to fix it

**Comment by RSS1102** [comment]
> For the icon menu item error, you are missing `image-ico` or `image-png` feature flag, I will update the documentation of the `icon` field.
> 
> Also you don't need to call `transformImage` yourself, it will be called internally, just pass `./icon.png`.
> 
> As for the other issue where where the submenu is not created, I will open a PR to fix it

Thank you for answering the question. This has been troubling me for two days. 

You have such a fast response and commit speed😀😀,
 but can you give me this simple pr opportunity to fix bugs next time and try to participate?🤔🤔

**Comment by amrbashir** [comment]
@RSS1102 definitely, that would be lovely. Just comment in your issues (or any other issue) that you want to work on the issue and I will assign it to you.
