### ISSUE TITLE
[docs] How do I add notification permissions?

### ISSUE THREAD

**Issue by changmen1** [tauri-apps/tauri#11433]
![image](https://github.com/user-attachments/assets/a6586828-ff53-4722-b73e-12fa558e6180)
![image](https://github.com/user-attachments/assets/d8f9b7f5-7742-4261-af5c-48b94e3f51cf)

**Comment by DINGDANGMAOUP** [comment]
if you are using tauri v2 ,mybe you can see [Capabilities | Tauri](https://v2.tauri.app/security/capabilities/)

**Comment by changmen1** [comment]
> if you are using tauri v2 ,mybe you can see [Capabilities | Tauri](https://v2.tauri.app/security/capabilities/)

thank you very much

**Comment by amrbashir** [comment]
check https://v2.tauri.app/plugin/notification/#permission-table for possible permissions

**Comment by changmen1** [comment]
> check https://v2.tauri.app/plugin/notification/#permission-table for possible permissions

Thank you
