### ISSUE TITLE
[docs] warning: spurious network error (3 tries remaining): [92] Stream error in the HTTP/2 framing layer (HTTP/2 stream 5 was not closed cleanly: PROTOCOL_ERROR (err 1))

### ISSUE THREAD

**Issue by changmen1** [tauri-apps/tauri#11437]
Can anyone help me?

![image](https://github.com/user-attachments/assets/cdd97381-c226-4711-93c5-1dd360808955)

**Comment by amrbashir** [comment]
That's just a warning from cargo, probably slow network. Nothing to worry about.

**Comment by changmen1** [comment]
> That's just a warning from cargo, probably slow network. Nothing to worry about.
Thank you very much for every answer. Thanks
