### ISSUE TITLE
[bug] Android built apk with Tauri is not installing on the device

### ISSUE THREAD

**Issue by tahadostifam** [tauri-apps/tauri#11453]
### Describe the bug

I created a sample project using by `cargo create-tauri-app` and the project successfully built to Desktop (Linux & Windows) and also Android. 

But installation on the android device failed with the error below :

```txt
The APK failed to install.   
Error: INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed collecting certificates for  
/data/app/vmdl1377986156.tmp/base.apk: Failed to collect certificates from /data/app/vmdl1377986156.tmp/base.apk: Attempt to get length of null array   
```

### Reproduction

```bash
cargo create-tauri-app
cargo tauri android init
cargo tauri android build

adb install ./app-universal-release-unsigned.apk
```

### Expected behavior

Thats right that our apk is not signed but we expect to be installed successfully in debug mode.

### Full `tauri info` output

```text
[✔] Environment
    - OS: openSUSE 20241007.0.0 x86_64 (X64)
    ✔ webkit2gtk-4.1: 2.44.4
    ✔ rsvg2: 2.59.1
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (2024-09-04)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 22.3.0
    - pnpm: 9.12.2
    - yarn: 1.22.22
    - npm: 10.9.0

[-] Packages
    - tauri 🦀: 2.0.6
    - tauri-build 🦀: 2.0.2
    - wry 🦀: 0.46.3
    - tao 🦀: 0.30.3
    - tauri-cli 🦀: 2.0.2
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli : 2.0.2

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.2
    - @tauri-apps/plugin-shell : not installed!

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../src
```

**Comment by ahqsoftwares** [comment]
```
cargo tauri android build
```

is not the command for debug mode, for a debug mode build use

```
cargo tauri android build --debug
```

**Comment by amrbashir** [comment]
@ahqsoftwares that's right, it should be `cargo tauri android build --debug` for debug builds.

**Comment by tahadostifam** [comment]
> @ahqsoftwares that's right, it should be `cargo tauri android build --debug` for debug builds.

You're right. I built with debug flag and installed successfully on my Android mobile.

But how should i build in release mode? when i built it with :

```bash
cargo tauri android build
```

it gives me the error i explained in the issue. I'm Back-End developer actually and I don't have deep knowledge about mobile development. so I don't understand what the problem is with the Tauri that does not installing on my mobile in release mode.

Help.🥲

**Comment by amrbashir** [comment]
Checkout https://tauri.app/distribute/sign/android/ on how to sign your apk so `tauri android build` would work correctly.
