### ISSUE TITLE
[bug] rpm bundling is stuck on Ubuntu 22.04

### ISSUE THREAD

**Issue by izderadicka** [tauri-apps/tauri#11478]
### Describe the bug

rpm bundling stucks

running `cargo tauri build`

Build is OK,  deb bundling takes like 10-15 secs,  but rpm bundling then runs forever (I stopped it after 10 minutes or so) -  in processes I see `cargo tauri build` running and taking 100% of one CPU/core.

### Reproduction

This happens for rqbit project on Ubuntu 22.04,  node and npm installed via nvm,  tauri dependencies installed as per docs
- https://github.com/ikatson/rqbit.git
- cd rqbit/desktop
- cargo tauri build

### Full `tauri info` output

```text
$ cargo tauri info

[✔] Environment
    - OS: Ubuntu 22.4.0 x86_64 (X64)
    ✔ webkit2gtk-4.1: 2.44.3
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.18.0
    - yarn: 1.22.11
    - npm: 10.8.2

[-] Packages
    - tauri 🦀: 2.0.0
    - tauri-build 🦀: 2.0.0
    - wry 🦀: 0.44.1
    - tao 🦀: 0.30.2
    - tauri-cli 🦀: 2.0.3
    - @tauri-apps/api : 2.0.1 (outdated, latest: 2.0.3)
    - @tauri-apps/cli : 2.0.3 (outdated, latest: 2.0.4)

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.0
    - @tauri-apps/plugin-shell : 2.0.0 (outdated, latest: 2.0.1)

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by livwvil** [comment]
I feced with the same issue.
Ubuntu 22.04
Build also stucks inside docker container
```
FROM rust:bookworm

ENV NODE_VERSION 18
ENV PNPM_VERSION 9.5.0
ENV DEBIAN_FRONTEND noninteractive

WORKDIR /home

RUN set -uex; \
    apt-get update; \
    apt-get install -y ca-certificates \
      gnupg \
      libwebkit2gtk-4.1-dev \
      build-essential \
      curl \
      wget \
      file \
      libxdo-dev \
      libssl-dev \
      libayatana-appindicator3-dev \
      librsvg2-dev; \
    mkdir -p /etc/apt/keyrings; \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
     | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg; \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_VERSION}.x nodistro main" \
     > /etc/apt/sources.list.d/nodesource.list; \
    apt-get -qy update; \
    apt-get -qy install nodejs; \
    rm -rf /tmp/* /var/tmp/*;

RUN npm i -g pnpm@${PNPM_VERSION}

RUN cargo install tauri-cli
```
Part of my tauri.conf.json
```
    "targets": ["deb", "rpm", "msi", "app"],
    "windows": {
      "webviewInstallMode": {
        "type": "offlineInstaller"
      },
      "wix": {
        "language": "ru-RU"
      }
    },
    "linux": {
      "deb": {
        "depends": []
      },
      "rpm": {
        "depends": []
      }
    }
```
I use resources and sidecars

**Comment by amrbashir** [comment]
this took me a while to debug but it seems to not be stuck or anything, it is just compressing a lot of data because @izderadicka you have debug symbols in your release profile here 
https://github.com/ikatson/rqbit/blob/fb6822ca41e5c14dde48d27e12b2308b949a44b1/Cargo.toml#L37 which resulted in around 254mb main binary instead of normal 24mb.

**Comment by amrbashir** [comment]
@livwvil make sure your resources and sidecars are on the smaller side otherwise it will just take a bit longer to finish.

**Comment by livwvil** [comment]
> @livwvil make sure your resources and sidecars are on the smaller side otherwise it will just take a bit longer to finish.

I waited for about 50 minutes. This is not normal, so I think it is stuck. My resources with sidecar take up about 1GB. Deb package is created in just a couple of minutes and it take up about 350MB.

**Comment by FabianLars** [comment]
If it's 1gb then i'm still not 100% convinced that it's stuck. For some reason the compression in the rpm-rs crate is much much slower than whatever the deb bundler is using.
This used to be even worse where people thought it was stuck for 100mb apps which made me do this https://github.com/tauri-apps/tauri/pull/9840 and of course it'll be amplified in CI etc

I can't test it myself until next week but maybe adding a setting for the compression level would be a good idea now idk

**Comment by livwvil** [comment]
> I can't test it myself until next week but maybe adding a setting for the compression level would be a good idea now idk

I created a repo (check README.md)

https://github.com/livwvil/tauri2-rpm-build-problem

**Comment by amrbashir** [comment]
opened https://github.com/tauri-apps/tauri/pull/11584 to add an option to control the compression algorithm and level.

**Comment by livwvil** [comment]
> opened #11584 to add an option to control the compression algorithm and level.

It gives no effect. Only 'none' mode works but it is not the best way to solve this problem. The issue is still actual.
Please test it on repo from my previous comment.

**Comment by livwvil** [comment]
I finally got the RPM package in tauri v1 after 36 minutes of waiting with default configuration. I thought it would take much longer because my previous run was not successful even after 50 minutes.
2.2 GB (1.2GB+900MB+rest) turned into 342 MB RPM
CI\CD will be dead :D

**Comment by jLynx** [comment]
Any updates around this? We should like to offer a `rpm` package for our users, but the builds just take so long

**Comment by FabianLars** [comment]
@jLynx the pr(s) were merged a while ago, you can configure the compression algorithm and level in tauri.conf.json https://v2.tauri.app/reference/config/#rpmcompression - alternatively you could try to figure out why https://github.com/rpm-rs/rpm is so god damn slow at compression.

**Comment by dralley** [comment]
Is there a particular reason Tauri is [using Bzip2 by default](https://github.com/tauri-apps/tauri/blob/dev/crates/tauri-bundler/Cargo.toml#L68), instead of the normal default, which is Zstd (which happens to be much faster and generally compresses better as well)?

**Comment by FabianLars** [comment]
The default is gzip https://v2.tauri.app/reference/config/#compression-1 and it's because it was rpm-rs' default when it was added https://docs.rs/rpm/0.13.0/rpm/struct.PackageBuilder.html#method.compression (still is in latest versions)
