### ISSUE TITLE
[bug] 内嵌的webview的a标签的跳转事件怎么监听？类似于electron webview里面的new-window事件，

### ISSUE THREAD

**Issue by jianghaitaoo** [tauri-apps/tauri#11479]
### Describe the bug

app.on('web-contents-created', (event, win) => {
  win.on(
    'new-window',
    (event, newURL, frameName, disposition, options, additionalFeatures) => {
      if (!options.webPreferences) options.webPreferences = {};
      options.webPreferences.nodeIntegration = false;
      options.webPreferences.nodeIntegrationInWorker = false;
      options.webPreferences.webviewTag = false;
      delete options.webPreferences.preload;
    }
  );
});
这个是electron的监听事件

### Full `tauri info` output

```text
shell.open not allowed on window "main", webview "main-333", URL: https://www.baidu.com/

allowed on: [windows: "main", "main-333", URL: local], [windows: "main", "main-333", URL: local]

referenced by: capability: default, permission: allow-open || capability: default, permission: allow-open
```

**Comment by wtto00** [comment]
Add `"shell:default"` in `permissions` of `src-tauri/capabilities/default.json`.

Refer to https://v2.tauri.app/plugin/shell/#permissions.

**Comment by jianghaitaoo** [comment]
1、create webview use initialization_script
2、in the initialization_script 
 const links = document.querySelectorAll('a[target="_blank"]');

        // 为每个链接添加 click 事件监听器
        links.forEach(link => {

            link.addEventListener('click', async function(event) {
                console.log('新标签页链接被点击:',event.target.tagName.toLowerCase(),event, event.currentTarget.href);
                invoke('want_open_new_tab', { url: event.currentTarget.href })
            });
        });

3、in rust
 fn want_open_new_tab<R: Runtime>(app: tauri::AppHandle<R>, url: &str) {
    println!("want_open_new_tab:{}", url);
}

that is my answer,just hock js in the webside,use the js listen event ,and send to rust
