### ISSUE TITLE
[bug] [vite] Internal server error: [postcss] .../+page.svelte?svelte&type=style&lang.css:1:1: Unknown word

### ISSUE THREAD

**Issue by yueduz** [tauri-apps/tauri#11482]
### Describe the bug

![image](https://github.com/user-attachments/assets/1f746aad-5515-472e-bc10-ee05a8f721b1)

When I open it from npm run tauri dev I have the problem as on the picture.
When I run npm run dev and open "http://localhost:1420/" from chrome there are no problems.

I created a repository for error examples
https://github.com/yueduz/TauriErrorDemonstration

### Full `tauri info` output

```text
$ npm run tauri info                                                                                             [20:43:12]

> bobo@0.1.0 tauri
> tauri info

WARNING: Only one package manager should be used, but found npm and pnpm.
         Please remove unused package manager lock files, will use npm for now!

[✔] Environment
    - OS: Arch Linux Unknown x86_64 (X64)
    ✔ webkit2gtk-4.1: 2.46.2
    ✔ rsvg2: 2.59.1
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (2024-05-07)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 22.10.0
    - pnpm: 9.12.2
    - npm: 10.9.0
    - bun: 1.1.32
    - deno: deno 1.46.3

[-] Packages
    - tauri 🦀: 2.0.6
    - tauri-build 🦀: 2.0.2
    - wry 🦀: 0.46.3
    - tao 🦀: 0.30.3
    - @tauri-apps/api : 2.0.3
    - @tauri-apps/cli : 2.0.5

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.2
    - @tauri-apps/plugin-shell : 2.0.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

**Comment by amrbashir** [comment]
please don't post a random zipped file in issues, create a repo so we can safely check it

**Comment by amrbashir** [comment]
This is either a vite error or SvelteKit + PostCSS issues, please consult their respective repos.

**Comment by JoaoLucasSR** [comment]
I have the same error

**Comment by amrbashir** [comment]
I wasn't able to reproduce with the provided repo, it works just fine for me on Arch + KDE
![image](https://github.com/user-attachments/assets/8124e8ca-e920-4988-ba7d-46093a6a47c9)
