### ISSUE TITLE
[feat] Add ability to use favicon of webpage as window and taskbar icon

### ISSUE THREAD

**Issue by akhileshshastri-bpi** [tauri-apps/tauri#11487]
### Describe the problem

If I make a new WebviewWindow and load a url:

```
const window = new WebviewWindow("goog", {
  url: "www.google.com"
});
```

There should be an option to use the webpage favicon as the window and taskbar icon. For example, in the above code snippet, the window icon should be the Google favicon.

### Describe the solution you'd like

I would like to have an option added to WebviewWindow options to be able to use the webpage favicon as the window and taskbar icon.

**Comment by ahqsoftwares** [comment]
Are you making a browser? That's the only *probable* reason I can guess for this feature.

**Comment by akhileshshastri-bpi** [comment]
@ahqsoftwares No, nothing that ambitious. Different sections of our website have different favicons. We want to wrap each section in a Tauri window. It seems redundant to have to store the icons both on the webserver (for the website) and locally on the user's machine (so that Tauri can access them).

**Comment by amrbashir** [comment]
This is not something we should support in tauri directly, and I think should be something that you should implement in your app, here is how you might want to implement this:
1. retrieve the favicon from the webview url, see https://stackoverflow.com/questions/5119041/how-can-i-get-a-web-sites-favicon
2. either use the returned PNG bytes or save the PNG to a local disk path (and cache it for later usage) and create a [`Image`](https://tauri.app/reference/javascript/api/namespaceimage/#frombytes)
3. call `WebviewWindow.setIcon` (or similar method on Rust) with the created [`Image`](https://tauri.app/reference/javascript/api/namespaceimage).

Note, if the favicon image is svg, you will have to convert it to .png or .ico first before using it with `Image` class.
