### ISSUE TITLE
[bug] Automatic migration does not update `@tauri-apps/api`

### ISSUE THREAD

**Issue by Wrench56** [tauri-apps/tauri#11495]
### Describe the bug

I recently migrated from Tauri v1 to v2. I used `yarn` and the automatic migration script offered. When I compiled my app, IPC did  not work at all. Turns out that `@tauri-apps/api` was not updated to version v2.

### Reproduction

1. `yarn up @tauri-apps/cli@latest `
2. `yarn tauri migrate `
3. `yarn tauri build`

### Expected behavior

I expected that the automatic migration script upgrades `@tauri-apps/api` to 2.0.3 (current latest).

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 x86_64 (X64)
    ✔ WebView2: 129.0.2792.89
    ✔ MSVC:
        - Visual Studio Build Tools 2019
        - Visual Studio Community 2022
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 22.4.1
    - yarn: 4.5.1
    - npm: 10.8.3

[-] Packages
    - tauri 🦀: 2.0.6
    - tauri-build 🦀: 2.0.2
    - wry 🦀: 0.46.3
    - tao 🦀: 0.30.3
    - @tauri-apps/api : 1.6.0 (outdated, latest: 2.0.3)
    - @tauri-apps/cli : 2.0.5


[-] Plugins

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:8080/
    - framework: Svelte
    - bundler: Vite
```

**Comment by Wrench56** [comment]
I guess based on `tauri info` one could resolve the issue by seeing how it is outdated, but it might be worth considering adding some warning or even enhancing the migration script. Or did I miss something from the docs that referred to this problem?

Cheers.

**Comment by amrbashir** [comment]
I wasn't able to reproduce, could you share the project that failed to migrate or a minimal repro?

**Comment by Wrench56** [comment]
The multirepo [here](https://github.com/Wrench56/Turbotrace) contains the client subproject that contains the codebase for Tauri. I had to manually bump the version of `@tauri-apps/api`. The `main` branch still has the old version if you want to test it on that. Again, just for clarity, I use yarn.

Edit: [Here](https://github.com/Wrench56/TurboTrace/commit/22c5983474c22821274123fedefebb6b8dcf37e7) is the exact commit that has Tauri v1.
