### ISSUE TITLE
How to listen for events on a remote page

### ISSUE THREAD

**Issue by Tenney95** [tauri-apps/tauri#11509]
### Describe the problem

```
const openComfyUi = async () => {
  const windowManager = new Window();
  await windowManager.createWin({
    label: 'ComfyUI',
    title: 'ComfyUI',
    url: 'http://127.0.0.1:8188/',
    width: 1200,
    height: 900,
    center: true,
    visible: true,
    resizable: true
  });

  const code = titlebar + setWindow;

  setTimeout(() => {
    invoke('evaluate_js_in_window', {
      windowLabel: 'ComfyUI',
      jsCode: code
    });
    windowManager.listen();
  }, 1000);
};

```

### Describe the solution you'd like

WebviewWindow creates a window with a remote url, how do I listen to various events on it, or listen to postMessage。The document went through for a long time

**Comment by amrbashir** [comment]
you'll have to add an initialization script that sets up your handlers (and possibly send them to either Rust or other tauri windows to be processed)
