### ISSUE TITLE
[bug] Can NOT use log

### ISSUE THREAD

**Issue by Shu-Ji** [tauri-apps/tauri#11519]
### Describe the bug

I'm using info!("test") directly in my Rust code, and it works without any issues.
However, when I try to configure the timezone:
```rust
// lib.rs
    tauri::Builder::default()
        .plugin(
            tauri_plugin_log::Builder::new()
            .timezone_strategy(tauri_plugin_log::TimezoneStrategy::UseLocal)
            .build()
        )
```
An error occurs on startup:
```
Failed to setup app: error encountered during setup hook: failed to initialize plugin `log`: attempted to set a logger after the logging system was already initialized
```
Even when I don't configure anything, I still get an error:

```rust
// lib.rs
    tauri::Builder::default()
        .plugin(tauri_plugin_log::Builder::new().build())
```

### Full `tauri info` output

```text
Failed to setup app: error encountered during setup hook: failed to initialize plugin `log`: attempted to set a logger after the logging system was already initialized
```

**Comment by cyear** [comment]
How did you solve this problem? I have also encountered this issue and according to the official documentation, it is reporting an error

**Comment by Shu-Ji** [comment]
> How did you solve this problem? I have also encountered this issue and according to the official documentation, it is reporting an error

I have switched to electron:('

**Comment by cyear** [comment]
> > How did you solve this problem? I have also encountered this issue and according to the official documentation, it is reporting an error
> 
> I have switched to electron:('

OK, I see，I may have found the problem，closing devtools may solve it

**Comment by ash-hashtag** [comment]
why is this issue closed? I am running into the same problem

**Comment by ochsnerd** [comment]
For me the problem was that `tauri init` already sets up some logging, which creates a conflict after adding the logging plugin.

This is how `lib.rs` looks after doing

```shell
tauri init
tauri add log
```

```rust
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
  tauri::Builder::default()
    .plugin(tauri_plugin_log::Builder::new().level(tauri_plugin_log::log::LevelFilter::Info).build())
    .setup(|app| {
      if cfg!(debug_assertions) {
        app.handle().plugin(
          tauri_plugin_log::Builder::default()
            .level(log::LevelFilter::Info)
            .build(),
        )?;
      }
      Ok(())
    })
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
```

The closure in the `setup`-call attempts to set up logging after the plugin has already initialized it. Removing the `setup`-call entirely fixed the issue for me.
