### ISSUE TITLE
[feat] raspberry pi gpio support

### ISSUE THREAD

**Issue by DanielTerletzkiy** [tauri-apps/tauri#11517]
### Describe the problem

i do not know if it already exists as i cannot find any official docs for this, but is there a way to gain access to raspberry pi gpio and use i2c for example?

### Describe the solution you'd like

get an example on how to do basic i2c in tauri backend and if you need to set any permissions to do this

**Comment by FabianLars** [comment]
There really isn't much Tauri specific to your question. Just search google / crates.io for gpio / pi stuff and you'll see multiple results, i think this one is the "largest" one: https://github.com/golemparts/rppal

If your desired result are JS bindings for Tauri then you can request a new plugin in https://github.com/tauri-apps/plugins-workspace/ to have it tracked at least, just know that no team member will work on this.
