### ISSUE TITLE
[bug] The window border is not displayed correctly

### ISSUE THREAD

**Issue by noy1993** [tauri-apps/tauri#11538]
### Describe the bug

I want to display a window without a title bar on Windows 10, but only the top border appears. Based on the documentation, there should be borders all around. Is this behavior correct, or is it supposed to be this way?
![E1D7BE8C-1D1D-49fa-BFA9-88158A881BDA](https://github.com/user-attachments/assets/a8994dd5-047b-4043-a4f4-be3057ef1121)

```
    "windows": [
      {
        "title": "test",
        "width": 800,
        "height": 600,
        "decorations": false
      }
    ],
```

### Expected behavior

I would like to have either all four borders appear or have an option for no borders at all.

### Full `tauri info` output

```text
Environment
    - OS: Windows 10.0.19045 x86_64 (X64)
    ✔ WebView2: 130.0.2849.56
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.82.0 (f6e511eec 2024-10-15)
    ✔ cargo: 1.82.0 (8f40fc59f 2024-08-21)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.13.1
    - pnpm: 9.12.2
    - yarn: 1.22.22
    - npm: 10.8.1

[-] Packages
    - tauri 🦀: 2.0.6
    - tauri-build 🦀: 2.0.2
    - wry 🦀: 0.46.3
    - tao 🦀: 0.30.5
    - tauri-cli 🦀: 2.0.2
    - @tauri-apps/api : 2.0.3
    - @tauri-apps/cli : 2.0.2 (outdated, latest: 2.0.4)

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.2
    - @tauri-apps/plugin-shell : 2.0.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

**Comment by amrbashir** [comment]
should be fixed by https://github.com/tauri-apps/tao/pull/993 and all side will have correct border (if you want them all removed, you will need to also disable shadows)
