### ISSUE TITLE
[bug] 'transparent: true' configured via the 'new WebviewWindow()' method is invalid

### ISSUE THREAD

**Issue by Alicehhhmm** [tauri-apps/tauri#11551]
### Describe the bug

1.Based on the WebviewWindow case（ [ WebviewWindow Example](https://tauri.app/reference/javascript/api/namespacewebviewwindow/#example-1) ）
![image](https://github.com/user-attachments/assets/b9cf9a49-995d-410f-9dcb-9486c1e24751)

2.On click the button ( create wind ) triggers the following method  
```javascript
const webview = new WebviewWindow(label, {
    title: title,
    url: '/exp',
    resizable: resizable,
    width: 600,
    height: 400,
    center: true,
    fullscreen: false,
    skipTaskbar: false,
    decorations: false,
    transparent: true, //! invalid
    dragDropEnabled: true,
})
```
3.Expected results:
![image](https://github.com/user-attachments/assets/2fae7873-b498-4244-b4c5-7955a7905f59)

4.The actual result:
![image](https://github.com/user-attachments/assets/e45c0bef-8737-4b17-8c9f-0c72ae068d3f)

### Reproduction

Case address [tauri-vue3-tmp](https://github.com/Alicehhhmm/tauri-vue3-tmp)

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19045 x86_64 (X64)
    ✔ WebView2: 129.0.2792.89
    ✔ MSVC: Visual Studio 生成工具 2022
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.20.4
    - pnpm: 9.10.0
    - yarn: 1.22.22
    - npm: 10.7.0

[-] Packages
    - tauri 🦀: 2.0.6
    - tauri-build 🦀: 2.0.2   
    - wry 🦀: 0.46.3
    - tao 🦀: 0.30.3
    - tauri-cli 🦀: 2.0.3     
    - @tauri-apps/api : 2.0.3
    - @tauri-apps/cli : 2.0.5

[-] Plugins
    - tauri-plugin-log 🦀: 2.0.1
    - @tauri-apps/plugin-log : not installed!

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ..
    - devUrl: http://localhost:5173/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by amrbashir** [comment]
your `html` and `body` elements are not transparent. tested with your repro by creating the window as you explained, then going into devtools and making these elements transparent.

**Comment by Alicehhhmm** [comment]
Thank you .  
I think I see what you mean, but I may have misunderstood. I thought that when I set the window transparent, the whole window would disappear, leaving only the CSS custom window displayed on the screen.  
![image](https://github.com/user-attachments/assets/323730da-cb6b-4f5f-8c1e-01c8748335bd)
Question:
Can the newly created window be set to rounded corners by `css ` ?

**Comment by amrbashir** [comment]
you can disable shadows and then round the corners as you please
