### ISSUE TITLE
[bug] Menubar Submenu Enabled state doesn't update automatically

### ISSUE THREAD

**Issue by Miniontoby** [tauri-apps/tauri#11556]
### Describe the bug

When you change the enabled state of the submenu items in the menubar (using code), the visible enabled/disabled state doesn't update.

The visible enabled state of the submenu items only updates when:
- the submenu is 'physicly' updated:
  - by mouse hover
  - by keyboard 'hover' (by pressing Alt and then use the arrow keys)
- the window loses it's focus:
  - By pressing Alt-Tab
  - By clicking into another window (make sure you can still see the tauri window!)

### Reproduction

The bare minimum that you need is in this repo: https://github.com/Miniontoby/tauri-menubar-bug

The steps are in the README over there, but I will put the actual reproduction steps (if you try with or without the given code):
1. Have an app with menubar with submenu items and have a way to toggle the menubar submenu items their enabled state.
2. Toggle the Enabled state of the items.
3. You will see the other submenu's don't update their visible enabled state.
4. Now use one of these methods:
   - Hover over one of the submenu's.
   - Press Alt and then use the arrow keys to navigate to the other submenu's. (They might all already update when pressing Alt, but not everytime)
   - Hold Alt and press Tab (you can hold Shift and press Tab to 'stay' on the window)
   - - If you have a second screen, just click on any window on your second screen.
     - If you don't have a second screen, then place any window next to the tauri window and do step 3 and then click into the other window.
5. That should have shown the bug

### Expected behavior

I was expecting the menubar submenu items to just visibly update their Enabled state when changing it with code.

#### PC Windows 11:

```text
[✔] Environment
    - OS: Windows 10.0.22631 x86_64 (X64)
    ✔ WebView2: 130.0.2849.56
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.82.0 (f6e511eec 2024-10-15)
    ✔ cargo: 1.82.0 (8f40fc59f 2024-08-21)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.11.0
    - npm: 10.2.4

[-] Packages
    - tauri 🦀: 2.0.6
    - tauri-build 🦀: 2.0.2
    - wry 🦀: 0.46.3
    - tao 🦀: 0.30.5
    - @tauri-apps/api : 2.0.3
    - @tauri-apps/cli : 2.0.5

[-] Plugins

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - bundler: Vite
```

#### Laptop windows 10

```text
[✔] Environment
    - OS: Windows 10.0.19045 x86_64 (X64)
    ✔ WebView2: 130.0.2849.56
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.77.2 (25ef9e3d8 2024-04-09)
    ✔ cargo: 1.77.2 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.19.0
    - pnpm: 7.25.0
    - npm: 10.9.0

[-] Packages
    - tauri 🦀: 2.0.6
    - tauri-build 🦀: 2.0.2
    - wry 🦀: 0.46.3
    - tao 🦀: 0.30.5
    - tauri-cli 🦀: 2.0.0-alpha.2
    - @tauri-apps/api : 2.0.3
    - @tauri-apps/cli : 2.0.5

[-] Plugins

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - bundler: Vite
```

### Additional context

I also got an pre-built .exe in the releases tab on the repo so you don't need to build the project

And here is a screen recording showing the behaviour:

https://github.com/user-attachments/assets/93bf7b5a-bfb3-42cb-857e-8d5b656281ec

**Comment by amrbashir** [comment]
run `cargo update -p muda` inside `src-tauri`, and the bug should be fixed

**Comment by Miniontoby** [comment]
Yeah that fixes it! Thanks!

I really don't get why no-one has found this before...
