### ISSUE TITLE
[feat] Wait for pre build command / cleanup command

### ISSUE THREAD

**Issue by ItsFelix5** [tauri-apps/tauri#11550]
### Describe the problem

I have a pretty weird setup as I have a system where my js get build to my 'plugin.js' and then injected into a website with tauri.
Now when I run tauri dev tauri compiles, then the js finishes building and then tauri has to restart or if this is the first build, tauri panics. Then when I am done i would like my plugin.js to be deleted.

### Describe the solution you'd like

I would like some sort of option that prevents starting tauri until the watcher updates it or the build command finishes.
For the second part of this issue I suggest a "afterDevCommand" option.

### Alternatives considered

A way to tell tauri to also watch .gitignored files.

**Comment by amrbashir** [comment]
This is a specific use case and I believe this should be a build script in your repo
