### ISSUE TITLE
Consult:  MultiWindow, NextJS, Open Link in Default Browser

### ISSUE THREAD

**Issue by dfirence** [tauri-apps/tauri#1160]
Hi Awesome Tauri Team

quick questions please

1.  What is the possible ETA of MultiWindow Support in Tauri? My use case is for multi-window support and I would want to avoid using Electron.

2. Does Tauri currently support NextJS or does it work with NextJS?

3. And lastly, do you have a code sample that shows how have a Tauri App coordinate a link being opened in the default browser of the machine?

**Comment by nothingismagick** [comment]
This is not an issue related to the codebase, so am closing it. Please use the [discussions](https://github.com/tauri-apps/tauri/discussions) or visit our discord.
