### ISSUE TITLE
[feat] 希望能拦截操作窗体的请求，并且可以操作当前窗体的缓存文件

### ISSUE THREAD

**Issue by 1937650094** [tauri-apps/tauri#11629]
### Describe the problem

希望能拦截操作窗体的请求，并且可以操作当前窗体的缓存文件

### Describe the solution you'd like

希望能拦截操作窗体的请求，并且可以操作当前窗体的缓存文件

**Comment by FabianLars** [comment]
On a native level i think this is a duplicate of https://github.com/tauri-apps/tauri/issues/11571 / https://github.com/tauri-apps/tauri/issues/4899
