### ISSUE TITLE
[feat] I want use sql on backend.how to do?

### ISSUE THREAD

**Issue by fate-zx** [tauri-apps/tauri#11623]
### Describe the problem

I use tauri 2.0 and want to use sqlite,but `tauri-sql-plugins` only use in react or other html.

### Describe the solution you'd like

first:this is plugins can use on backend?
second: if ok,how to do?
this is a idea for me,thanks

**Comment by FabianLars** [comment]
chose any existing rust crates like sqx, seaorm, diesel, rusqlite, whatever. If you choose sqlx you can re-use the plugin's connection pools by getting them via `app.state::<tauri_plugin_sql::DbInstances>();`
