### ISSUE TITLE
[bug] permissions:How http allows dynamic domain name access?

### ISSUE THREAD

**Issue by lhc122525** [tauri-apps/tauri#11665]
### Describe the bug

Domain name is returned through the interface，How can I allow http dynamic domain name access to the api?

{
"identifier": "http:default",
"allow": [
{
"url": "http://**"
}
]
},

### Full `tauri info` output

```text
Error: url not allowed on the configured scope
```

**Comment by FabianLars** [comment]
duplicate of https://github.com/tauri-apps/plugins-workspace/issues/2040
