### ISSUE TITLE
[feat] prevent talkback saying the webview element on android

### ISSUE THREAD

**Issue by Vexcited** [tauri-apps/tauri#11664]
### Describe the problem

Not sure if this is intended or not, when we enable TalkBack to test accessibility on Android, the WebView of the app is always said.

### Describe the solution you'd like

I'd like to not hear the WebView + name of my app everytime.

### Alternatives considered

None

### Additional context

See the following video for a better explanation of the "issue" :

https://github.com/user-attachments/assets/a6b8c8ab-7a93-4575-9556-2bd465a16630

**Comment by FabianLars** [comment]
if i look around on github and stackoverflow, for example https://stackoverflow.com/questions/68039308/android-skip-focus-of-webview-and-go-straight-to-content-with-talkback, everything looks like this can't be prevented.
