### ISSUE TITLE
[feat] Keep the App's function buttons and customize the toolbar

### ISSUE THREAD

**Issue by wangxg422** [tauri-apps/tauri#11672]
### Describe the problem

How to make the function buttons (maximize, minimize, close) on the toolbar keep the characteristics of their respective operating systems (windows on the right, macos on the left), while being able to customize the toolbar. Because when developing an APP, the layout of the APP sometimes has a menu bar on the left and display content on the right, without a toolbar, but the three buttons in the toolbar (maximize, minimize, close) need to be retained.

### Describe the solution you'd like

Refine the setting of "decorations: false". When it is currently set to false, the toolbar and function buttons disappear at the same time. It is expected to add a reserved operation button
![PixPin_2024-11-13_17-46-33](https://github.com/user-attachments/assets/f8835c42-f514-4414-9762-bc98b6c548b1)

**Comment by FabianLars** [comment]
On macOS you can use the titlebarStyle window config and for Windows we're waiting on an update from WebView2 tracked here https://github.com/tauri-apps/tauri/issues/4531 / https://github.com/MicrosoftEdge/WebView2Feedback/issues/4532

These configs will keep just the control buttons while removing the titlebar (so you can create your own if needed)
