### ISSUE TITLE
[feat] 

### ISSUE THREAD

**Issue by duhiqc37** [tauri-apps/tauri#11690]
### open the file with the context menu.
<img width="424" alt="image" src="https://github.com/user-attachments/assets/95f267c1-23c1-4b54-8eaf-073047e44130">

### Describe the solution you'd like

open the file with the context menu.

**Comment by FabianLars** [comment]
This is already supported: https://v2.tauri.app/reference/config/#fileassociations

The tracking issue for the missing guide is here https://github.com/tauri-apps/tauri-docs/issues/1526
