### ISSUE TITLE
[bug] failed to bundle project: error running appimage.sh

### ISSUE THREAD

**Issue by Z-xus** [tauri-apps/tauri#11701]
### Describe the bug

Same as mentioned in Issue #5781 . I am using Arch Linux and followed the hello world app instructions for vite with pnpm https://v2.tauri.app/start/create-project/ 

This is my first time using tauri and I have no experience in rust (also a noob). The app runs fine with `pnpm tauri dev` but build fails with same as issue above.

### Reproduction

Follow https://v2.tauri.app/start/prerequisites/
and run `pnpm tauri build`

### Expected behavior

Build suceeds

### Full `tauri info` output

```text
❯ pnpm tauri info

> desktop@0.1.0 tauri /home/neon/Projects/skadoosh/apps/desktop
> tauri "info"

WARNING: no lock files found, defaulting to npm

[✔] Environment
    - OS: Arch Linux Unknown x86_64 (X64)
    ✔ webkit2gtk-4.1: 2.46.3
    ✔ rsvg2: 2.59.2
    ✔ rustc: 1.82.0 (f6e511eec 2024-10-15)
    ✔ cargo: 1.82.0 (8f40fc59f 2024-08-21)
    ✔ rustup: 1.27.1 (2024-05-07)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 22.11.0
    - pnpm: 9.12.0
    - yarn: 3.8.5
    - npm: 10.9.0
    - deno: deno 1.46.3

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.0
    - tao 🦀: 0.30.8
    - @tauri-apps/api : 2.1.1
    - @tauri-apps/cli : 2.1.0

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.2
    - @tauri-apps/plugin-shell : 2.0.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Stack trace (pnpm tauri build --verbose)

```text
https://pastebin.com/ZCccpu8T
```

**Comment by FabianLars** [comment]
You need to run it with the `NO_STRIP=true` env var set, see https://github.com/tauri-apps/tauri/issues/8929

**Comment by Z-xus** [comment]
Thanks a bunch!
