### ISSUE TITLE
[feat] there are any chance to have the web platform supported?

### ISSUE THREAD

**Issue by Manuelito-Code** [tauri-apps/tauri#11704]
### Describe the problem

i wish that Tauri become the all in one tool for create software for all platform in one single codebase, it would be awesome and handy for developers and companies.

### Describe the solution you'd like

i dont know

**Comment by FabianLars** [comment]
Never say never, but there are no plans for the near future.

> all platform in one single codebase

which technically is already possible, you'd just need some logic that chooses between tauri apis and some web fallback. afaik there are already many apps doing exactly that.

Closing as a duplicate of https://github.com/tauri-apps/tauri/issues/8248

**Comment by Manuelito-Code** [comment]
Thank you for the help
