### ISSUE TITLE
Access Resources Add Referer Configuration

### ISSUE THREAD

**Issue by shiyanaaa** [tauri-apps/tauri#11728]
### Describe the problem

Due to security issues, "Referer" authentication is added to server resources. Currently, Tauri is used to develop windows applications, but there is no way to configure the Referer of the video IMG audio tag.

### Describe the solution you'd like

Be able to configure Referer, or give a solution

**Comment by amrbashir** [comment]
did you try adding `<meta name="referrer" content="always">` in your `<head>`?

**Comment by shiyanaaa** [comment]
> did you try adding `<meta name="referrer" content="always">` in your `<head>`?

Oh no, you don't understand what I mean, my resource policy is that the Referer must contain "aaa.bbb.com", but I can't do that in tarui's tag resource because the url is not "aaa.bbb.com"

**Comment by amrbashir** [comment]
Can you provide an example of what you mean, and an example server that I can test with?

**Comment by shiyanaaa** [comment]
I've solved the problem I need
