### ISSUE TITLE
[feat] add [Portuguese] language in NSIS available language

### ISSUE THREAD

**Issue by Kiyozz** [tauri-apps/tauri#11725]
### Describe the problem

![image](https://github.com/user-attachments/assets/4ad41cb8-2860-4c66-9a61-6f464a06ee5c)

This language is available in the specified url. This is the tauri.conf.json

```json
"windows": {
  "nsis": {
    "languages": ["French", "English", "Portuguese", "Spanish"]
  }
}
```

I only have the warning for Portuguese

### Describe the solution you'd like

Add this language to the available list removing the warning

**Comment by amrbashir** [comment]
we have `PortugeseBR`, but we didn't get any PRs for just `Portugese`, would you be willing to open a PR for it? it is a simple as translating this file https://github.com/tauri-apps/tauri/blob/dev/crates/tauri-bundler/src/bundle/windows/nsis/languages/English.nsh.

**Comment by Kiyozz** [comment]
I'm on it, PR is coming. Let me know if the PR follows the guidelines.

**Comment by amrbashir** [comment]
Thank you

**Comment by Kiyozz** [comment]
PR posted
