### ISSUE TITLE
[feat] Support for rendering browser bundles

### ISSUE THREAD

**Issue by 1057105012** [tauri-apps/tauri#11738]
### Describe the problem

I hope to support bundling with Google Chrome. This is not a step back to electron. Instead, make it an option.

Consider the following design options
1. The default strategy tests the specified versions of the three rendering engines, taking the lowest one that is compatible with the latest web standards as the benchmark. If not, use Google Chrome (the local version can be bundled, and the default is remote download)
2. Bundle local browser method

webviewBundler: 'auto' | 'local'

### Describe the solution you'd like

no thing

**Comment by FabianLars** [comment]
browsers are not webviews or can't be used as ones. There were projects like gluon but afaik they've all given up on it because it turned out not to be a good idea.

we still plan to offer different webviews than the current ones, see https://github.com/tauri-apps/tauri/issues/14963 for example.

**Comment by DASPRiD** [comment]
Another implementation seems to be this one:

https://github.com/mycrl/webview-rs/
