### ISSUE TITLE
[bug] android run in background

### ISSUE THREAD

**Issue by shiyanaaa** [tauri-apps/tauri#11743]
### Describe the bug

When the Android program is running and playing aduio, switch to another application and it will stop immediately，
How can I do it to run in the background

### Full `tauri info` output

```text
none
```

**Comment by ghost** [comment]
What was the issue? I have it the same.

**Comment by shiyanaaa** [comment]
> What was the issue? I have it the same.

can you show you code？

**Comment by phrynus** [comment]
> > 问题是什么？我也有同样的情况。
> 
> 你能展示一下你的代码吗？

Hello, how was this troublesome issue resolved

**Comment by shiyanaaa** [comment]
> > > 问题是什么？我也有同样的情况。
> > 
> > 
> > 你能展示一下你的代码吗？
> 
> Hello, how was this troublesome issue resolved

你检查一下你的音乐文件，换一个音乐文件试试，有可能你的音乐文件有视频流
