### ISSUE TITLE
[feat] It is recommended to add the configuration item whether to close the program after closing all Windows

### ISSUE THREAD

**Issue by GuoJikun** [tauri-apps/tauri#11759]
### Describe the problem

The program is closed after closing all Windows

### Describe the solution you'd like

It is recommended to add the configuration item whether to close the program after closing all Windows

**Comment by amrbashir** [comment]
you can do something like this 

```rs
    tauri::Builder::default()
        .build(tauri::generate_context!())
        .expect("error while running tauri application")
        .run(|app, event| {
            if let tauri::RunEvent::ExitRequested { api, code, .. } = event {
                if code.is_none() {
                    api.prevent_exit();
                }
            }
        });
  
```

**Comment by GuoJikun** [comment]
> you can do something like this
> 
> ```rust
>     tauri::Builder::default()
>         .build(tauri::generate_context!())
>         .expect("error while running tauri application")
>         .run(|app, event| {
>             if let tauri::RunEvent::ExitRequested { api, code, .. } = event {
>                 if code.is_none() {
>                     api.prevent_exit();
>                 }
>             }
>         });
>   
> ```

thanks
