### ISSUE TITLE
[feat] libwebkit2gtk-4.1 not available in Ubuntu22，How to specify the version to be used？

### ISSUE THREAD

**Issue by WillieMatthewLiu** [tauri-apps/tauri#11763]
### Describe the problem

I installed the Tauri 2.0 app on Ubuntu 22 and it prompted me to install  libwebkit2gtk-4.1

### Describe the solution you'd like

When compiling Tauri 2.0 APP, I can specify the libwebkit2gtk version that depends on running it

**Comment by FabianLars** [comment]
Which version are you talking about? 4.0 vs 4.1 ? That's not possible, see the discussion here https://github.com/tauri-apps/tauri/issues/9662 for example.

**Comment by WillieMatthewLiu** [comment]
My computer is version 4.0 and cannot be upgraded due to certain reasons. Therefore, we hope that Tauri 2.0 can run on version 4.0

**Comment by ahqsoftwares** [comment]
> My computer is version 4.0 and cannot be upgraded due to certain reasons. Therefore, we hope that Tauri 2.0 can run on version 4.0

Webkit v4.1 and v4.0 aren't really backwards compatible and therefore its just not possible to use both

**Comment by WillieMatthewLiu** [comment]
> > My computer is version 4.0 and cannot be upgraded due to certain reasons. Therefore, we hope that Tauri 2.0 can run on version 4.0
> 
> Webkit v4.1 and v4.0 aren't really backwards compatible and therefore its just not possible to use both

Therefore, Tauri 2.0 can only run on Webkit 4.1?

**Comment by FabianLars** [comment]
Yes. If you must use 4.0 you're stuck with tauri v1 if we ignore docker and vms and maybe flatpak (you can compile apps inside of the sdk env) for development of course.
