### ISSUE TITLE
[bug] `appWindow.onMoved` Returns `-32000`

### ISSUE THREAD

**Issue by ayangweb** [tauri-apps/tauri#11773]
### Describe the bug

I wrote this method: https://github.com/EcoPasteHub/EcoPaste/blob/master/src/hooks/useWindowState.ts

Many Windows users reported that they can't open the Preferences window. After getting the file, I found that the coordinates became "-32000".

<img width="383" alt="image" src="https://github.com/user-attachments/assets/a39de2f2-4891-4ee5-a567-21e4ac4bb145">

### Full `tauri info` output

```text
Feedback from Windows users, other platforms are not aware of this issue at this time!
```

**Comment by FabianLars** [comment]
-32000 is where windows moves minimized windows. (Hidden windows too maybe but I don't think so)
So it's not a bug per se if onMoved returns -32000

**Comment by ayangweb** [comment]
Ok, thanks, I'll take the minimized window into account
