### ISSUE TITLE
[feat] Allow docking of browser dev tools when launching tauri in dev mode.

### ISSUE THREAD

**Issue by delebash** [tauri-apps/tauri#11781]
### Describe the problem

Trying to debug the frontend using browser dev tools and the window is not docked

### Describe the solution you'd like

Be apple to specify that the debug tools are docked when running the app in dev mode.  Also be able to specify the position as in left bottom and so on.

Example:   `window.open_devtools('right'); ` This would open the dev tools on launch and dock to the right side of the window.

**Comment by FabianLars** [comment]
Thanks for the requst. Unfortunetly, none of the webviews have apis for this as far as i can see. They only have some for generic open/close :(
