### ISSUE TITLE
[feat] How can I implement the Ctrl+F function in the browser to perform page searches and highlight the matching text?

### ISSUE THREAD

**Issue by carly1987** [tauri-apps/tauri#11795]
### Describe the problem

<img width="833" alt="image" src="https://github.com/user-attachments/assets/a0e550d8-0a47-4481-b046-5744332714dc">

### Describe the solution you'd like

<img width="833" alt="image" src="https://github.com/user-attachments/assets/edead42a-033f-49eb-a79c-c733da0ffac2">

**Comment by FabianLars** [comment]
closing as duplicate of https://github.com/tauri-apps/tauri/issues/9385
