### ISSUE TITLE
[bug] Support aarch64 debain？

### ISSUE THREAD

**Issue by menode** [tauri-apps/tauri#11819]
### Describe the problem

System： ubuntu 24.02

Compile occurrence
![image](https://github.com/user-attachments/assets/6c30a2ac-5d21-4b00-bc76-1fbb423ed943)

![image](https://github.com/user-attachments/assets/a99ef277-ea1f-4c49-89d5-f575a22131cc)

### Describe the solution you'd like

Normal compilation success

### Alternatives considered

Multiple systems have been replaced
mac  ubuntu20.02 windows

**Comment by FabianLars** [comment]
can you try following https://deploy-preview-2981--tauri-v2.netlify.app/distribute/debian/#cross-compiling-for-arm-based-devices and see if that works? (rendered preview from https://github.com/tauri-apps/tauri-docs/pull/2981)
