### ISSUE TITLE
[bug] default.json capabilities doesnt accept the plugin's permissions when added by the tauri add plugin command

### ISSUE THREAD

**Issue by tomasben** [tauri-apps/tauri#11815]
### Describe the bug

When I run the "pnpm tauri add <plugin>" command, in this case for the store plugin, it adds the "store:default" capability to the default.json file as intended. This emits a warning on the same file saying that the value added is not accepted and proceed to list all the core default permissions (App, Event, Image, Menu, Path, Resources, Tray, Webview, Window), even though the permissions section of the store plugin does indicate us to adding the permissions in that file.  

![image](https://github.com/user-attachments/assets/3e4f0983-b2e1-410a-99cd-4bbd88e04384)

And also rust-analyzer emits an error on the tauri::generate_context macro saying that there is no OUT_DIR env var set.

![image](https://github.com/user-attachments/assets/52c4a13b-c9e2-4be2-b68d-d7e1d68df98d)

This all gets fixed by deleting the "store:default"  and adding the feature "store-api" on the plugin line of the build dependencies 

![image](https://github.com/user-attachments/assets/79a445f6-2375-4524-8583-e21c37855cca)

### Reproduction

-  Run the "pnpm tauri add store" command
- Go to /project/src-tauri/capabilities/default.json and the new added line at the end of the permissions array should have a warning/message 

### Expected behavior

Expected the default.json to accept the plugin default permissions since there is were we are indicated to declare them. 

### Full `tauri info` output

```text
[✔] Environment
    - OS: Fedora 41.0.0 x86_64 (X64)
    ✔ webkit2gtk-4.1: 2.46.3
    ✔ rsvg2: 2.59.1
    ✔ rustc: 1.82.0 (f6e511eec 2024-10-15)
    ✔ cargo: 1.82.0 (8f40fc59f 2024-08-21)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 22.11.0
    - pnpm: 9.14.2
    - npm: 10.9.0

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.2
    - tao 🦀: 0.30.8
    - @tauri-apps/api : 2.1.1
    - @tauri-apps/cli : 2.1.0

[-] Plugins
    - tauri-plugin-sql 🦀: 2.0.2
    - @tauri-apps/plugin-sql : 2.0.1
    - tauri-plugin-shell 🦀: 2.0.2
    - @tauri-apps/plugin-shell : 2.0.1
    - tauri-plugin-fs 🦀: 2.0.3
    - @tauri-apps/plugin-fs : 2.0.2
    - tauri-plugin-store 🦀: 2.1.0
    - @tauri-apps/plugin-store : 2.1.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Additional context

I'm not yet too knowledgeable on tauri app development so there may be something I'm doing wrong when adding the permissions.  I'm using Zed editor and, since rust-analyzer is the one emitting the error on the lib.rs file and the tauri build command runs just fine, I guess this must be an error on their side and not tauri, feel free to dismiss the bug report if any of the two is the case.

**Comment by FabianLars** [comment]
> This all gets fixed by deleting the "store:default" and adding the feature "store-api" on the plugin line of the build dependencies

There's no store-api feature in the store plugin (https://docs.rs/crate/tauri-plugin-store/latest/features), so that should make compilation fail 🤔 

> I'm using Zed editor and, since rust-analyzer is the one emitting the error on the lib.rs file and the tauri build command runs just fine, I guess this must be an error on their side and not tauri

yeah, it's rust-analyzer. case in point would be the out_dir error. does this still show if you simply reloasd RA/the editor?

**Comment by tomasben** [comment]
Yeah that's what I thought as well. I couldn't fix it so I asked the anthropic AI to do it  (shame on me, I know) and it added that feature flag. I then asked it where did it get that from and said that from tauri docs. I looked on the docs.rs but there weren't any feature flags, kinda strange. Worst part is that this actually fixes the errors on the generate context macro. Must be some configuration from my system or rust-analyzer, no idea.

> does this still show if you simply reloasd RA/the editor?

Yeah, I tried reloading the language server and zed multiple times but no case. Anyway, I'll just try to make sense of the state management with Rust and just use that. Thanks for the response 😃

**Comment by Stiff-Rock** [comment]
Old post but i'm getting the same problem with any plugin that i add. Did you find a solution?

**Comment by tomasben** [comment]
> Old post but i'm getting the same problem with any plugin that i add. Did you find a solution?

Hi! Not really, I stopped using most of tauri plugins and used my own implementations. If you are trying to use the store plugin then I'd recommend using the state management solution shown on the docs if you want to write Rust, or you can use a state library like zustand on the frontend and optionally save to disk. You can also use the webview storages for basic key value pairs. 

As for the error messages I just configurated rust-analyzer to stop warning on failed macros. Plugins should still be working though as the one giving errors is the analyzer.
