### ISSUE TITLE
[bug] webview render low fps on ubuntu22-lts with nvidia GPU only(no integrated gpu)

### ISSUE THREAD

**Issue by qyuzh** [tauri-apps/tauri#11818]
### Describe the bug

[bug] webview render low fps on ubuntu22-lts with nvidia GPU only(no integrated gpu)

### Reproduction

any simple React + Tauri2 app

### Full `tauri info` output

```text
No
```

**Comment by FabianLars** [comment]
nothing really we can do here as long as we're using webkitgtk https://github.com/tauri-apps/wry/issues/890 though you may wanna try running it with `WEBKIT_DISABLE_DMABUF_RENDERER=1` or `WEBKIT_DISABLE_COMPOSITING_MODE=1` env vars set.
