### ISSUE TITLE
Trojan reported on Windows 10 (Trojan:Win32/Wacatac.G!ml)

### ISSUE THREAD

**Issue by dav-fr** [tauri-apps/tauri#1182]
**Describe the bug**
Windows reports Tauri app .exe as a threat, detecting Trojan:Win32/Wacatac.G!ml

[More info](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fWacatac.G!ml&threatid=2147749376)

**To Reproduce**
Create a basic sample app with create-react-app and follow the tauri guide :
1. npx create-react-app myapp
2. cd myapp
3. yarn add tauri
4. add "tauri": "tauri" to package.json
5. yarn tauri init
6. yarn build
7. yarn tauri build
8. copy .exe file from target/release to another folder (without WebView2Loader.dll)

-> If I execute the app, I usually get an error because WebView2Loader.dll cannot be found, which is expected, but sometimes Windows Defender blocks and quarantines the app. I have not had this behaviour without moving the .exe file, but as it seems to happen randomly, I don't know if it related.

**Expected behavior**
No Trojan/virus warning

**Screenshots**
![error1](https://user-images.githubusercontent.com/78509726/106812964-b0972d80-6670-11eb-9690-a66eb1bc4518.jpg)
![error2](https://user-images.githubusercontent.com/78509726/106812967-b3921e00-6670-11eb-9774-eb6c51acbbfd.jpg)

**Platform and Versions (please complete the following information):**
OS: Windows_NT(10.0.18363) - win32/x64
Node: 14.15.4
NPM: 6.14.10
Yarn: 1.22.10
Rustc: 1.49.0 (e1884a8e3 2020-12-29)

**Additional context**
Similar to #1060

**Comment by nothingismagick** [comment]
hmm. It seems like this is a report from an atypical install approach. i would like to request that you build a proper MSI and install that. would you mind?

**Comment by dav-fr** [comment]
Hi, I rebuilt the app, installed it with msi, and run it with no warning.
As the problem seemed to happen randomly, I uninstalled it and tried again, with the exact same msi file.
When running the app after the second installation, Windows Defender blocked it, showing this treat: Behavior:Win32/Execution.IF!ml

![errorr3](https://user-images.githubusercontent.com/78509726/106873498-d0603d00-66d4-11eb-956a-a6d729ee9730.png)

**Comment by nothingismagick** [comment]
Hmm. I am wondering if we have to sign artefacts now for windows. I am not a windows expert, unfortunately. Perhaps you could attach the file here (or send it via wetransfer) and then we could run some analysis. I am a bit surprised though that we don't get this report all the time...

**Comment by nothingismagick** [comment]
Please join our discord and ping me there so we can triage properly

**Comment by nothingismagick** [comment]
Thanks, this is likely due to the DLL problems faced by webview/webview. Will be resolved when WRY lands with the next release.
