### ISSUE TITLE
[feat] Tauri's performance on macOS

### ISSUE THREAD

**Issue by readWithoutUnderstanding** [tauri-apps/tauri#11822]
### Describe the problem

"I wrote a note-taking app using Tauri, but the performance on macOS is worse than on Windows due to the WebView engine used on macOS. The experience is very fast, but it becomes very laggy when copying text or selecting text. I would like to ask if there is a version or way to optimize this?"

### Describe the solution you'd like

Or is there a way to choose the browser engine and install it locally on the user's machine?

### Alternatives considered

I haven't thought of a solution yet. The performance of Safari is indeed not as good as WebView2. If you think my idea is far-fetched, feel free to just take a look

**Comment by FabianLars** [comment]
> I would like to ask if there is a version or way to optimize this?

I don't know anything specific but you're basically targetting Safari. If you keep that in mind you usually find stuff easier on the internet.

> Or is there a way to choose the browser engine and install it locally on the user's machine?

No, we plan to have an alternative engine at some point but it's a lot of work to make that possible. We should have enough issues about that in our repos already so i'm closing this, thanks for the additional feedback tho
