### ISSUE TITLE
[bug] `sudo npm run tauri ios dev ` error , use `npm run tauri ios dev` has another fatal error

### ISSUE THREAD

**Issue by ximing-xu** [tauri-apps/tauri#11834]
### Describe the bug

when run `sudo npm run tauri ios dev` , it cause an error:
failed to get cargo metadata: cargo metadata command exited with a non zero exit code: error: rustup could not choose a version of cargo to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.

    Error failed to get cargo metadata: cargo metadata command exited with a non zero exit code: error: rustup could not choose a version of cargo to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.

note: Run script build phase 'Build Rust Code' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked.

when run `npm run tauri ios dev`, it has another error

Deploying app to device...
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):
Unable to lookup in current state: Shutdown
Failed to deploy app to simulator: command ["xcrun", "simctl", "install", "F75A360B-701E-4F46-B802-25D8FF6133D6"] exited with code 149
    Error Failed to deploy app to simulator: command ["xcrun", "simctl", "install", "F75A360B-701E-4F46-B802-25D8FF6133D6"] exited with code 149

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 15.1.1 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.83.0 (90b35a623 2024-11-26)
    ✔ cargo: 1.83.0 (5ffbef321 2024-10-29)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.11.0
    - npm: 10.2.4

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.2
    - tao 🦀: 0.30.8
    - @tauri-apps/api : 2.1.1
    - @tauri-apps/cli : 2.1.0

[-] Plugins
    - tauri-plugin-barcode-scanner 🦀: 2.0.1
    - @tauri-apps/plugin-barcode-scanner : not installed!
    - tauri-plugin-http 🦀: 2.0.3
    - @tauri-apps/plugin-http : 2.0.1
    - tauri-plugin-sql 🦀: 2.0.2
    - @tauri-apps/plugin-sql : not installed!
    - tauri-plugin-upload 🦀: 2.1.0
    - @tauri-apps/plugin-upload : not installed!
    - tauri-plugin-os 🦀: 2.0.1
    - @tauri-apps/plugin-os : 2.0.0
    - tauri-plugin-localhost 🦀: 2.0.1
    - @tauri-apps/plugin-localhost : not installed!
    - tauri-plugin-shell 🦀: 2.0.2
    - @tauri-apps/plugin-shell : 2.0.1
    - tauri-plugin-log 🦀: 2.0.2
    - @tauri-apps/plugin-log : 2.0.0
    - tauri-plugin-fs 🦀: 2.0.3
    - @tauri-apps/plugin-fs : 2.0.2
    - tauri-plugin-persisted-scope 🦀: 2.0.3
    - @tauri-apps/plugin-persisted-scope : not installed!
    - tauri-plugin-store 🦀: 2.1.0
    - @tauri-apps/plugin-store : 2.1.0

[-] App
    - build-type: bundle
    - CSP: default-src 'self' stream: http://stream.localhost asset: http://asset.localhost; 
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite

[-] iOS
```

### Stack trace

```text
Deploying app to device...
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):
Unable to lookup in current state: Shutdown
Failed to deploy app to simulator: command ["xcrun", "simctl", "install", "F75A360B-701E-4F46-B802-25D8FF6133D6"] exited with code 149
    Error Failed to deploy app to simulator: command ["xcrun", "simctl", "install", "F75A360B-701E-4F46-B802-25D8FF6133D6"] exited with code 149
```

**Comment by FabianLars** [comment]
1) Running `npm` in sudo is pretty much always a bad idea so i will skip this
2) `Unable to lookup in current state: Shutdown` this sounds like the simulator was shutting down while the app was being deployed. A system restart may be good, and after that please try `npm run tauri ios dev -- --open` and then start the emulator from inside xcode.

**Comment by ximing-xu** [comment]
@FabianLars Restart macOS it woks, but it hit another error, when I switch to use to iOS simulator and physical iOS device, the hot reload will not work,only after I restart MacOs, the error can fix temporary, but the same code the hot reload works normally on windows with android, is there any special setting on mac?

**Comment by FabianLars** [comment]
I'm not familiar enough with macOS to answer that, sorry. If it matters, i don't think i've heard about this before but that probably doesn't mean much.

Does using the `--host` cli flag help?

**Comment by ximing-xu** [comment]
@FabianLars I try so much times, after downgrade the simulater version from 18.1 to 16.0, all things works well, maybe this is the iOS 18.x simulater's bug.thanks for your help!!!
