### ISSUE TITLE
Labels on Inputs for Example App

### ISSUE THREAD

**Issue by jdgwf** [tauri-apps/tauri#1184]
**Is your feature request related to a problem? Please describe.**
This might be a problem for usability, but if anything it's good practice.

**Describe the solution you'd like**
Wrapping all inputs in `<label>` tags or setting `<label for="xxx">` for the inputs. It makes accessibility much easier (plus it's easier to toggle check-boxes)

**Describe alternatives you've considered**
Feel free to leave it as-is, for it's a demo app and you have  bigger "fish to fry". When I get the time I'll make a clone and make a PR if it's not handled by then. I know you folks are busy.

**Comment by nklayman** [comment]
We're replacing that app with a [new api demo](https://github.com/tauri-apps/tauri/tree/dev/tauri/examples/api), which has labels on all the inputs. Thanks for the suggestion :+1:
