### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by a937983423** [tauri-apps/tauri#11853]
### Describe the bug

cargo create-tauri-app
✔ Project name · test
✔ Identifier · com.test.app
✔ test directory is not empty, do you want to overwrite? · yes
✔ Choose which language to use for your frontend · Rust - (cargo)
✔ Choose your UI template · Dioxus - (https://dioxuslabs.com/)

Template created! To get started run:
  cd test
  cargo tauri android init

For Desktop development, run:
  cargo tauri dev

For Android development, run:
  cargo tauri android dev

[debian@windows TAURI]$ cd test
[debian@windows test]$ cargo tauri dev
    Running BeforeDevCommand (`dx serve --port 1420`)
    Warn Waiting for your frontend dev server to start on http://localhost:1420/...
    Warn Waiting for your frontend dev server to start on http://localhost:1420/...
\ 💼 Waiting to start building the project...                                                       error[E0463]: can't find crate for `core`
  |
  = note: the `wasm32-unknown-unknown` target may not be installed
  = help: consider downloading the target with `rustup target add wasm32-unknown-unknown`

For more information about this error, try `rustc --explain E0463`.
error[E0463]: can't find crate for `std`
  |
  = note: the `wasm32-unknown-unknown` target may not be installed
  = help: consider downloading the target with `rustup target add wasm32-unknown-unknown`

error: could not compile `cfg-if` (lib) due to 1 previous error
error: could not compile `once_cell` (lib) due to 1 previous error
  ❌ Build failed.                                                                                  Error: 🚫 Serving project failed:

Caused by:
    Build failed
    Error The "beforeDevCommand" terminated with a non-zero status code.
rustrp show
bash: rustrp: 未找到命令
[debian@windows test]$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/debian/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

aarch64-linux-android
armv7-linux-androideabi
i686-linux-android
wasm32-unknown-unknown
wasm32-wasi
x86_64-linux-android
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.83.0 (90b35a623 2024-11-26)
系统是archlinux

### Full `tauri info` output

```text
tauri info

[✔] Environment
    - OS: Arch Linux Rolling Release x86_64 (X64)
    ✔ webkit2gtk-4.1: 2.46.4
    ✔ rsvg2: 2.59.2
    ✔ rustc: 1.83.0 (90b35a623 2024-11-26) (Arch Linux rust 1:1.83.0-1)
    ✔ cargo: 1.83.0 (5ffbef321 2024-10-29)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 23.1.0
    - npm: 10.9.0
    - deno: deno 2.0.0

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.2
    - tao 🦀: 0.30.8
    - tauri-cli 🦀: 2.1.0

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.2

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
```

**Comment by FabianLars** [comment]
Can you do `which cargo` and check its path? This kinda looks like you have 2 rust installations on your system, with the rustup one being ignored.

If that's not the case, then maybe just reinstall rust / rustup? 🤔

**Comment by a937983423** [comment]
Thank you very much for your advice. After checking the package system according to the information you provided, I found the problem. The problem lies with the python-setuptools-rust package. This package will automatically install Rust packages, and it gets installed without notice. Thank you very much.

**Comment by a937983423** [comment]
cargo tauri dev
    Running BeforeDevCommand (`dx serve --port 1420`)
  👑 Build done.                                                                                        Warn Waiting for your frontend dev server to start on http://localhost:1420/...
thread 'main' panicked at /home/debian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/manganis-cli-support-0.2.4/src/manifest.rs:51:51:
called `Result::unwrap()` on an `Err` value: Parse("parse error: invalid Cargo.lock format version: `4`\n")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    Error The "beforeDevCommand" terminated with a non-zero status code.

**Comment by FabianLars** [comment]
`manganis-cli-support` is a dependency of dioxus-cli for which we cannot offer support here. Try deleting the Cargo.lock file(s) though, maybe that's still from the old rust version. If that doesn't help, please ask the dioxus community instead.

**Comment by a937983423** [comment]
Thank you very much for your help. I'll go to the Dioxus community to report the bug.

**Comment by yybawang** [comment]
When i add a $PATH on my macbook solve my issue, Hope help yours;

I add the `.carbo/bin` PATH in your .zshrc/.bashrc

#### Example
`export PATH="/Users/yourloginname/.cargo/bin:$PATH"`
