### ISSUE TITLE
Tauri + Vue.js - multiple dev servers running - HMR not working correctly

### ISSUE THREAD

**Issue by Horft** [tauri-apps/tauri#1187]
Currently I am facing the problem that there are multiple dev servers started when running tauri with vue.js.
I tried Windows and Linux (Ubuntu 18.04, 20.04 and Arch), but I do have the same problem independent from the operating system.

1. vue create <APP_NAME>
2. vue add tauri
3. npm run tauri:serve
4. tauri window opens with expected vue page, but no HMR working (best example is vue-i18n)

By using "npm run serve" vue just starts a single dev server on port 8080, nothing more. Running "npm run tauri:serve", there is at least another dev server running on port 8081, sometimes 8082, too.
Opening the urls in the browser is working fine, even mit HMR.

Manually adding tauri to any vue project results in the same problem.
- npm run serve (wait until dev server is up)
- npm run tauri dev => another dev server on port 8081

Even then the vue cli just reports to be running on port 8080.

Any idea of what I'm doing wrong?

**Comment by nklayman** [comment]
The Tauri cli intentionally starts a second dev server on the next port. It is just a proxy server that adds a few things Tauri needs to function properly. There shouldn't be a server on 8082, however. Did that happen often? In addition, HMR works just fine for me, not sure why it's broken for you. Can you run `./node_modules/.bin/tauri info` in your project directory and paste the output here? It might help me figure out what is wrong with your setup. If you could upload your repo to github and post a link to it that would help as well.

**Comment by lucasfernog** [comment]
We'll drop the proxy dev server when the custom protocol lands on [wry](https://github.com/tauri-apps/wry).

**Comment by Horft** [comment]
I just created a project with the example code: https://github.com/Horft/vue-tauri-example

Changing the 'welcomeMessage' in the i18n does not change anything in the tauri webview, although it seems to register a change but refers to an older state and instead loads that state instead.
- remove the 'TEST' from 'views/Home.vue' => works fine
- change the 'welcomeMessage' in i18n => tauri refreshes webview, 'TEST' is back and 'welcomeMessage' unchanged

In the browser this works absolutely fine.


> There shouldn't be a server on 8082, however. Did that happen often?

Could have been my fault, I wasn't able to reproduce that behavior.


> Can you run ./node_modules/.bin/tauri info in your project directory and paste the output here?

[tauri]: running info

Operating System - Linux(5.10.13-arch1-1) - linux/x64

Node.js environment
  Node.js - 15.8.0
  tauri.js - 0.14.1

Rust environment
  rustc - 1.49.0
  cargo - 1.49.0
  tauri-bundler - 0.9.4

Global packages
  NPM - 6.14.11
  yarn - Not installed

App directory structure
/.git
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 0.11.1
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - unset
  devPath - unset

**Comment by nklayman** [comment]
The HMR issue is with webkit2gtk, I tried loading the url in gnome web and it still didn't work. We don't really have any control over webkit, so I'm going to close this issue as it isn't really our fault. If you can find a solution, please let us know!
