### ISSUE TITLE
[bug] cargo install tauri-cli@2.0.4 error 

### ISSUE THREAD

**Issue by skydig** [tauri-apps/tauri#11874]
### Describe the bug

error[E0063]: missing field `recommends` in initializer of `DebianSettings`
    --> C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-cli-2.0.4\src\interface\rust.r
     |
1343 |     deb: DebianSettings {
     |          ^^^^^^^^^^^^^^ missing `recommends`

### Full `tauri info` output

```text
C:\Users\Administrator>cargo tauri info

[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 131.0.2903.70
    ✔ MSVC: Visual Studio Professional 2022
    ✔ rustc: 1.82.0 (f6e511eec 2024-10-15)
    ✔ cargo: 1.82.0 (8f40fc59f 2024-08-21)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.12.2
    - npm: 10.5.0

[-] Packages
    - tauri-cli [RUST]: 2.0.0-beta.20
```

**Comment by FabianLars** [comment]
Does `cargo install tauri-cli@2.0.4 --locked` work?
