### ISSUE TITLE
[feat] support Multi application 

### ISSUE THREAD

**Issue by songjiachao** [tauri-apps/tauri#11873]
### Describe the problem

I want to develop an application one is in the dock, the second is on back like mac spotlight.

can this support ? or has other way?

### Describe the solution you'd like

like this 
```
pub fn run() {
    let app = tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");

    let app2 = tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application2");
}

```

**Comment by FabianLars** [comment]
there can only be one NSApplication (macos api) in one binary, and therefore only one tauri::Builder in one project. Tauri supports multiple windows per app if that helps. If not, then you have to create 2 apps yourself and bundle them together (though afaik you can also only have one "real" app per app bundle 🤔 )
