### ISSUE TITLE
[feat] Why doesn’t TrayIcon have append_item or get methods?

### ISSUE THREAD

**Issue by tomoikey** [tauri-apps/tauri#11876]
### Describe the problem

Hi!

I’m currently using Tauri and trying to dynamically modify the items in the TrayIcon. However, it seems that the current API only provides the set_menu() method, which makes it difficult to flexibly add new items or append to a specific SubMenu.

It’s possible that I might have missed an existing way to achieve this. If there is already a method or approach for this use case, I’d appreciate it if you could point me in the right direction.

Thank you for your time and help! 😊

### Describe the solution you'd like

* Implement `get()` or `append_items()` and so on to TrayIcon

**Comment by amrbashir** [comment]
You should keep/store the menu you passed to the tray icon, and then you can manipulate that menu as you like.
