### ISSUE TITLE
[feat] C# .NET As Primary Language Support (Along Rust)

### ISSUE THREAD

**Issue by sangeethnandakumar** [tauri-apps/tauri#11889]
### Describe the problem

Due to learning curve for Rust, It's difficult for a lot of desktop developers to adopt Tauri. As a significant desktop devs comes from .NET ecosystem it's a great idea to support .NET as primary building language along Rust

### Describe the solution you'd like

Since Tauri is for cross platform desktop apps, A lot of adopters comes from good old .NET Framework ecosystem where we can create exceptional Windows WinForms or WPF apps.

.NET is modern, stable, evolved far better, cross platform with exceptional speed and security & open source.
Can we add .NET support to Tauri.

It can be side to side with Rust like selecting Javascript or Typescript when building a React app?

### Alternatives considered

Support .NET C# as primary language along Rust.

### Additional context

Microsoft is building MAUI for .NET devs to develop cross platform apps realizing this potential. I hope Tauri can adopt too as it's in an early v1 stage

**Comment by FabianLars** [comment]
Thanks for the request. We currently track all languages in one issue here https://github.com/tauri-apps/tauri/issues/4670
