### ISSUE TITLE
[bug] Missing readHtml function in plugin-clipboard-manager

### ISSUE THREAD

**Issue by wadamek65** [tauri-apps/tauri#11917]
### Describe the bug

Even though the documentation mentions it in an example, the function is nowhere in the source code and is not exported. Looks like an oversight because `writeHtml`, `readImage`, `writeImage`, `writeText`, and `readText` all exist. `readHtml` is the only one missing.

### Reproduction

Install `tauri-plugin-clipboard-manager = "=2.2.0"` and `"@tauri-apps/plugin-clipboard-manager": "2.2.0"` and see the function is not exported.

### Expected behavior

The function is exported.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 x86_64 (X64)
    ✔ WebView2: 131.0.2903.86
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.15.0
    - pnpm: 9.9.0
    - npm: 10.7.0
    - deno: deno 2.1.1

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.0
    - tao 🦀: 0.30.8
    - @tauri-apps/api : 2.0.0 (outdated, latest: 2.1.1)
    - @tauri-apps/cli : 2.1.0

[-] Plugins
    - tauri-plugin-single-instance 🦀: 2.0.1
    - @tauri-apps/plugin-single-instance : not installed!
    - tauri-plugin-http 🦀: 2.0.3
    - @tauri-apps/plugin-http : 2.0.1 (outdated, latest: 2.2.0)
    - tauri-plugin-process 🦀: 2.0.1
    - @tauri-apps/plugin-process : 2.0.0 (outdated, latest: 2.2.0)
    - tauri-plugin-window-state 🦀: 2.0.2
    - @tauri-apps/plugin-window-state : 2.0.0 (outdated, latest: 2.2.0)
    - tauri-plugin-localhost 🦀: 2.0.1
    - @tauri-apps/plugin-localhost : not installed!
    - tauri-plugin-updater 🦀: 2.0.2
    - @tauri-apps/plugin-updater : 2.0.0 (outdated, latest: 2.2.0)
    - tauri-plugin-global-shortcut 🦀: 2.0.1
    - @tauri-apps/plugin-global-shortcut : 2.0.0 (outdated, latest: 2.2.0)
    - tauri-plugin-deep-link 🦀: 2.0.1
    - @tauri-apps/plugin-deep-link : 2.0.0 (outdated, latest: 2.2.0)
    - tauri-plugin-shell 🦀: 2.0.2
    - @tauri-apps/plugin-shell : 2.0.1 (outdated, latest: 2.2.0)
    - tauri-plugin-fs 🦀: 2.0.3
    - @tauri-apps/plugin-fs : not installed!
    - tauri-plugin-autostart 🦀: 2.0.1
    - @tauri-apps/plugin-autostart : 2.0.0 (outdated, latest: 2.2.0)

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../../dist/apps/desktop-frontend
    - devUrl: http://localhost:4200/
    - framework: React (Next.js)
    - bundler: Vite
```

**Comment by FabianLars** [comment]
It's not really missing, it was intentionally removing in the PR that added html support https://github.com/tauri-apps/plugins-workspace/pull/977#discussion_r1499454259 - use readText instead (it would be the same output either way)

**Comment by wadamek65** [comment]
@FabianLars I see, thanks for the clarification. It would be nice if there was a mention of this in the docs and there wasn't a misleading example of `readHtml` being used though.

**Comment by FabianLars** [comment]
oh yeah, didn't see that readHtml usage. gonna fix it in a sec

**Comment by wadamek65** [comment]
@FabianLars by the way, is there a way for me to get the native HTML if it's stored in the clipboard? Similar to how I could extract it from the native navigator.clipboard? Do I need to add an RPC and a custom implementation in Rust?

```ts
async function getClipboardHTML() {
  try {
    const clipboardItems = await navigator.clipboard.read();
    for (const item of clipboardItems) {
      if (item.types.includes('text/html')) {
        const blob = await item.getType('text/html');
        const htmlText = await blob.text();
        console.log(htmlText);
        return htmlText;
      }
    }
    console.log('No HTML content found in clipboard.');
    return null;
  } catch (err) {
    console.error('Failed to read clipboard contents: ', err);
  }
}
```

**Comment by FabianLars** [comment]
in theory yes, but afaik there's no (cross-platform) rust crate that can read it as html, so you either need to read it as string like the plugin and then have some html parser check if it's html, or use the native OS bindings to read the clipboard yourself (please contribute that to `arboard` or something 😂 ), assuming the web api reads that from the os and doesn't do the parse check.

**Comment by wadamek65** [comment]
Understood, thanks for the explanation and your patience! That makes much more sense now.

**Comment by wadamek65** [comment]
@FabianLars I recently stumbled upon this https://github.com/CrossCopy/tauri-plugin-clipboard/tree/v2 which uses https://github.com/ChurchTao/clipboard-rs underneath. It seems to support all platforms (other than Wayland for certain features it seems like) so I just wanted to ask if you knew about this crate & plugin and if there is a reason it was not used here.

**Comment by FabianLars** [comment]
iirc this plugin is the reason ours is called clipboard-manager. i can't tell why there was no cooperation because i wasn't involved much in the plugin refactor (refactor == v1 core functionality being moved out into plugins).

the crate is newer than the plugin so back then there was no choice to make

**Comment by wadamek65** [comment]
Thanks @FabianLars, I'll check out the plugin then and if you're interested I can let you know how it compares to this one.
