### ISSUE TITLE
[bug] Invalid regular expression

### ISSUE THREAD

**Issue by mawnir** [tauri-apps/tauri#11954]
### Describe the bug

When I start the app, I see a blank screen, and the console displays the error: "SyntaxError: Invalid regular expression: invalid group specifier name."

<img width="897" alt="Screen Shot 2024-12-12 at 11 36 08" src="https://github.com/user-attachments/assets/5bd80b77-a460-4de9-94cd-41954fbfe2de" />

The issue appears to be within the `@tiptap/extension-code` extension, specifically in the `code.ts` file (located at https://github.com/ueberdosis/tiptap/blob/develop/packages/extension-code/src/code.ts).  The problematic line is:

```typescript
export const inputRegex = /(?<!`)`([^`]+)`(?!`)/
```

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 11.7.10 x86_64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.83.0 (90b35a623 2024-11-26)
    ✔ cargo: 1.83.0 (5ffbef321 2024-10-29)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 20.10.0
    - pnpm: 9.14.4
    - yarn: 1.22.17
    - npm: 10.2.3
    - bun: 1.0.22

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.2
    - tao 🦀: 0.30.8
    - @tauri-apps/api : 2.1.1
    - @tauri-apps/cli : 2.1.0

[-] Plugins
    - tauri-plugin-log 🦀: 2.2.0
    - @tauri-apps/plugin-log : not installed!

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:3000/
    - framework: React
    - bundler: Vite
```

**Comment by Legend-Master** [comment]
Tauri uses the webview provided by the OS, and in your case, Safari, and from your OS version it seems like you have an old version of Safari that doesn't support this regex yet, you can take a look at https://caniuse.com/js-regexp-lookbehind for which version is compatible with it

**Comment by mawnir** [comment]
@Legend-Master so is there any work around from Tauri's side (like downgrading...)

**Comment by Legend-Master** [comment]
No, at least nothing I could think of right now, you need to either upgrade your OS version or don't use a JavaScript feature that requires a recent version of Safari

**Comment by mawnir** [comment]
@Legend-Master thank you!
