### ISSUE TITLE
[feat] support importing dynamic css file

### ISSUE THREAD

**Issue by qzd1989** [tauri-apps/tauri#11966]
### Describe the problem

I'm frustrated that there is no way to import dynamic css file.
such as zoom in or zoom out the font-size when I press shortcut.
```javascript
//example 
async function zoomCss(version) {
    await import(`./css/${version}.css`);  //add and remove it
}
```
I searched the issues and it seems there has no issue about it.

### Describe the solution you'd like

maybe add js api to import dynamic css files?

**Comment by Legend-Master** [comment]
Closing this since I don't think this is related to Tauri

Just to answer your question, if you want to control styles dynamically, either add/remove classes or change the `style` attribute, e.g.

```js
window.addEventListener('keydown', () => document.documentElement.classList.toggle('dark'))
```

```css
:root {
    background-color: white;
}

:root.dark {
    background-color: black;
}
```

**Comment by qzd1989** [comment]
thankyou sir.
