### ISSUE TITLE
[bug] AppImages built on Linux Mint do not work for Fedora with Tauri 2.0

### ISSUE THREAD

**Issue by SpeeQz1** [tauri-apps/tauri#11988]
### Describe the bug

When building an AppImage on my Linux Mint 22 Cinnamon (Nvidia) machine with Tauri 2.0 and React, it would behave normally on any Linux Mint VM but when tried on Fedora all it showed was a white screen with the terminal error:
`Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...`

![image](https://github.com/user-attachments/assets/e8770c80-7d0b-40e6-b93d-5c2952ae9980)

### Reproduction

1. Make sure all the dependencies are installed
2. `npm create tauri-app@latest`
3. Set everything to default except choosing React near the end
4. Add the AppImage bundling options to `tauri.conf.json`
```json
    "linux": {
      "appimage": {
        "files": {}
      }
    }
```
5. `npm run tauri dev`
6. `npm run tauri build`
7. Try generated AppImage on Fedora

### Expected behavior

AppImage runs normally without problems.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Linux Mint 22.0.0 x86_64 (X64)
    ✔ webkit2gtk-4.1: 2.46.4
    ✔ rsvg2: 2.58.0
    ✔ rustc: 1.83.0 (90b35a623 2024-11-26)
    ✔ cargo: 1.83.0 (5ffbef321 2024-10-29)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 18.19.1
    - npm: 9.2.0

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.2
    - tao 🦀: 0.30.8
    - @tauri-apps/api : 2.1.1
    - @tauri-apps/cli : 2.1.0

[-] Plugins

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by ahqsoftwares** [comment]
Actually, setting `files: {}` seems to be the issue according to me.

**Comment by SpeeQz1** [comment]
This issue seems to be present even if you build the app itself on Fedora. #11994

**Comment by FabianLars** [comment]
Closing in favor of https://github.com/tauri-apps/tauri/issues/11994 then...
