### ISSUE TITLE
[feat] macOS adding extra files to DMG

### ISSUE THREAD

**Issue by ayangweb** [tauri-apps/tauri#11996]
### Describe the problem

The Generate DMG expects additional files to be added via configuration items, such as files for corrupted problem fixes.

<img width="290" alt="damaged-light en-US" src="https://github.com/user-attachments/assets/576a99e8-4302-4035-a30e-0de4eb30a4ff" />

<img width="1310" alt="image" src="https://github.com/user-attachments/assets/7166a314-561a-4039-ae2d-dad22e032437" />

### Describe the solution you'd like

If it is possible to add a binary to the DMG that fixes the corruption issue, it would be easy to fix it after installing the app.

**Comment by GillesPlatteeuw** [comment]
I believe this pop-up also occurs when the application and its contents aren't correctly signed and notarized. Did you verify that both of these steps have been done?

You can use `codesign -vvv --deep --strict <path_to_file>` to check the signature
`codesign -dvvvvv <path_to_file>` to get more information about the signature

**Comment by ayangweb** [comment]
@GillesPlatteeuw I don't have an Apple developer account, so I can't sign the app, so I have to fix the corruption by `sudo xattr -r -d com.apple.quarantine /Applications/EcoPaste.app`. But user input is cumbersome, and it's much easier to just double-click the file!

**Comment by FabianLars** [comment]
You can self-sign the app so right-click -> open works at least (add `"signingIdentity": "-"` to tauri.conf).

double clicking requires code signing & notarization, welcome in the world of macos app distribution.

Adding additional scripts that would execute xattr (does that make double clicking possible?) wouldn't work automatically in .dmg (meaning the user has to "drag" (or double click?) the script.

Anyway, the general files feature is being worked on here: https://github.com/tauri-apps/tauri/pull/11916

**Comment by ayangweb** [comment]
I'm already looking forward to it!
