### ISSUE TITLE
[bug] Android dev build error - Activity class does not exist

### ISSUE THREAD

**Issue by pianetarosso** [tauri-apps/tauri#12002]
### Describe the bug

I'm trying to integrate Android in my tauri existing app, but I've reproduced the issue with a clean project.
When running `npm run tauri android dev` at the end of the run process I'm getting this error:

```
Performing Streamed Install
Success
Starting: Intent { cmp=com.tauri_app.app/.MainActivity }
Error type 3
Error: Activity class {com.tauri_app.app/com.tauri_app.app.MainActivity} does not exist.
```

### Reproduction

Run this command:  to create a new project:  `irm https://create.tauri.app/ps | iex` and select these options:
- Project name: `tauri-app`
- Identifier: `com.tauri-app.app`
- Typescript / Javascript
- npm
- React (or another platform)
- Typescript
 
Then run these commands:
- `cd tauri-app`
- `npm install`
- `npm run tauri android init`
- `npm run tauri dev`

At the end of the build you'll get the error

```
...
Performing Streamed Install
Success
Starting: Intent { cmp=com.tauri_app.app/.MainActivity }
Error type 3
Error: Activity class {com.tauri_app.app/com.tauri_app.app.MainActivity} does not exist.
```

### Expected behavior

The apps installs and starts on the emulator

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.26100 x86_64 (X64)
    ✔ WebView2: 131.0.2903.99
    ✔ MSVC: 
        - Visual Studio Build Tools 2022
        - Visual Studio Community 2022
    ✔ rustc: 1.82.0 (f6e511eec 2024-10-15)
    ✔ cargo: 1.82.0 (8f40fc59f 2024-08-21)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.20.3
    - npm: 10.7.0

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.2
    - tao 🦀: 0.30.8
    - @tauri-apps/api : 2.1.1
    - @tauri-apps/cli : 2.1.0

[-] Plugins

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### JAVA 
openjdk version "21.0.5" 2024-10-15 LTS
OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode, sharing)

### Android

- SDK: Build-Tools 36-rc-1
- NDK: 28.0.126474087

**Comment by TogetherYear** [comment]
Is it the java version? This is my version that can run.
![Snipaste_2024-12-19_17-30-22](https://github.com/user-attachments/assets/ee13bca0-dca0-465c-984a-cbc9a78e8d3a)

**Comment by pianetarosso** [comment]
I've tested and it's working. Probably there was also an issue with the android emulator
