### ISSUE TITLE
[bug] pliug sql not found

### ISSUE THREAD

**Issue by ArbifyFun** [tauri-apps/tauri#12027]
### Describe the bug

I have setp by step with the offical doc install sql plugin.  but when run pnpm tauri dev I got an error 'plugin sql not found'

### Expected behavior

I want use sqlit in my desktop app.

### Full `tauri info` output

```text
pnpm tauri info:

➜  src-tauri git:(main) ✗ pnpm tauri info

[✔] Environment
    - OS: Mac OS 14.6.1 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.83.0 (90b35a623 2024-11-26) (Homebrew)
    ✔ cargo: 1.83.0
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: 
    - node: 18.19.0
    - pnpm: 9.6.0
    - yarn: 1.22.22
    - npm: 10.2.3

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.2
    - tao 🦀: 0.30.8
    - tauri-cli 🦀: 2.1.0
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli : 2.1.0

[-] Plugins
    - tauri-plugin-fs 🦀: 2.2.0
    - @tauri-apps/plugin-fs : not installed!
    - tauri-plugin-http 🦀: 2.2.0
    - @tauri-apps/plugin-http : 2.2.0
    - tauri-plugin-websocket 🦀: 2.2.0
    - @tauri-apps/plugin-websocket : 2.2.0
    - tauri-plugin-sql 🦀: 2.2.0
    - @tauri-apps/plugin-sql : 2.2.0
    - tauri-plugin-log 🦀: 2.2.0
    - @tauri-apps/plugin-log : not installed!

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../out
    - devUrl: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Webpack

cargo info :
[✔] Environment
    - OS: Mac OS 14.6.1 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.83.0 (90b35a623 2024-11-26) (Homebrew)
    ✔ cargo: 1.83.0
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: 
    - node: 18.19.0
    - pnpm: 9.6.0
    - yarn: 1.22.22
    - npm: 10.2.3

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.2
    - tao 🦀: 0.30.8
    - tauri-cli 🦀: 2.1.0

[-] Plugins
    - tauri-plugin-websocket 🦀: 2.2.0
    - tauri-plugin-log 🦀: 2.2.0
    - tauri-plugin-http 🦀: 2.2.0
    - tauri-plugin-sql 🦀: 2.2.0
    - tauri-plugin-fs 🦀: 2.2.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../out
    - devUrl: http://localhost:3000/
```

**Comment by FabianLars** [comment]
Can you share your main.rs and lib.rs files?

**Comment by ArbifyFun** [comment]
> Can you share your main.rs and lib.rs files?

main.rs:

fn main() {
    app_lib::run();
    tauri::Builder::default()
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_sql::Builder::default().build())
        .plugin(tauri_plugin_http::init())
        .plugin(tauri_plugin_websocket::init())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

lib.rs:

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_http::init())
        .plugin(tauri_plugin_websocket::init())
        .setup(|app| {
            if cfg!(debug_assertions) {
                app.handle().plugin(
                    tauri_plugin_log::Builder::default()
                        .level(log::LevelFilter::Info)
                        .build(),
                )?;
            }
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

**Comment by ArbifyFun** [comment]
thanks, i found build.rs not auto add the '.plugin(tauri_plugin_sql::Builder::default().build())'
now it works! thanks!!
