### ISSUE TITLE
[feat] If you register the Ctrl + c shortcut, the copy will not work.

### ISSUE THREAD

**Issue by gusxodnjs** [tauri-apps/tauri#12038]
### Describe the problem

It may seem obvious, but it's problematic. Applications like DeepL actually use the Ctrl + c + c shortcut to send text selected from the screen to the application. It's advantageous to use a clipboard because applications can be blocked from selecting text for a number of reasons. As soon as you press Ctrl + c, the data on the clipboard is sent to you so you can take advantage of it.
To implement ctrl + c + c in tauri, ctrl + c must be registered as a shortcut and then implemented by detecting the moment c is pressed within the set time.
However, as soon as you already use ctrl + c for shortcuts, the copy function is not running and the data cannot be utilized for the clipboard.
Can you give me an opinion on how I can implement it in this case?

### Describe the solution you'd like

Even if you register a shortcut such as Ctrl + c, the copy function must be performed. Alternatively, you must be able to register a Ctrl + c + c shortcut.

**Comment by FabianLars** [comment]
I assume you're talking about the Global Shortcut plugin here. This is simply how global shortcuts work, they take "ownership" of the key combination. So it sounds like you don't want global shortcuts here. Imo the best alternative in Tauri at the moment is using the JS built-in key events. If for any reason that won't work for you, you could use something like `rdev` in Rust.
