### ISSUE TITLE
[docs] Application startup fails without WebView2 runtime in Windows environment

### ISSUE THREAD

**Issue by YuHanHaHa** [tauri-apps/tauri#12030]
The first time I ran the Tauri Demo, I had a situation where the window appeared and then immediately closed.
After looking for information, I noticed WebView2 and suddenly recalled that I had previously uninstalled the Edge browser because it was lagging, and then also uninstalled the Microsoft Edge WebView2 Runtime because it had Edge in the name.
After re-downloading from the official website and re-installing the runtime , the Tauri app opens and runs normally.

**Comment by Legend-Master** [comment]
We have documented this: https://tauri.app/start/prerequisites/#webview2
