### ISSUE TITLE
Permissions request on mobile

### ISSUE THREAD

**Issue by c0st1nus** [tauri-apps/tauri#12041]
### Discussed in https://github.com/tauri-apps/tauri/discussions/12039

Hi everyone,  
Just for fun, I made a small project where I want to capture data from the camera, microphone, and geoposition. On desktop, requesting device access through the website was straightforward, and I used the following JavaScript code (Next.js):  
```javascript
useEffect(() => {
    async function getCameraStream() {
        try {
            const stream = await navigator.mediaDevices.getUserMedia({ video: true });
            videoRef.current.srcObject = stream;
            setPermissionGranted(true);
        } catch (err) {
            console.error("Error accessing camera: ", err);
            setError("Permission denied or no camera available.");
        }
    }
    getCameraStream();
}, []);
```
This worked fine on desktop. But, on mobile I get error catch with "No permission". I found an official "Barcode Scanner" plugin for mobile, but I didn’t fully understand how the permission request for the camera is implemented there.  
Could anyone guide me on how to request camera access permission on mobile devices when using Next.js? Are there best practices or specific examples I should follow?  
I have already read the issue #4434 . But... I got nothing from it. By that question it would excellent if someone could explain how to request permissions overall.
Thanks in advance!

**Comment by FabianLars** [comment]
https://github.com/tauri-apps/tauri/issues/10898#issuecomment-2525205514

**Comment by c0st1nus** [comment]
> [#10898 (comment)](https://github.com/tauri-apps/tauri/issues/10898#issuecomment-2525205514)

Thanks, that solved the most part of problem. However, I’d like to know how to implement the permission request. For example, how can I trigger a dialog to ask for camera permissions in Rust and/or JS?

**Comment by FabianLars** [comment]
In js you can just use the web apis == getUserMedia should open the permission requests.

No idea for rust, you'll probably have to dip into kotlin.

**Comment by one0oneChen** [comment]
> In js you can just use the web apis == getUserMedia should open the permission requests.在 js 中，你可以直接使用 Web API，==getUserMedia 可以打开权限请求。
> 
> No idea for rust, you'll probably have to dip into kotlin.没有 rust 的想法，你可能得转向 kotlin 了。

Hello, can you give an example of how to use it

**Comment by SleekGeek-254** [comment]
Those who are still have an issue with ` Camera & Microphone in Tauri v2 Android (getUserMedia / NotAllowedError / NotReadableError)` : You can check this out i also struggled with it but the fix was so simple. XD


[Fix: Camera & Microphone in Tauri v2 Android (getUserMedia / NotAllowedError / NotReadableError)](https://github.com/orgs/tauri-apps/discussions/12732#discussioncomment-16623745)
