### ISSUE TITLE
[bug] Tauri + React not showing image both path and base64 in release

### ISSUE THREAD

**Issue by Walker-00** [tauri-apps/tauri#12062]
### Describe the bug

I'm writing just a simple program to show user data from database, 
first I tried with file path which work in dev build ``` npx tauri dev ``` but it's not working in release build ``` npx tauri build ``` also configured the permission and all file path correctly as in config,
after long days of searching I just give up and test with base64 data of image which also work in dev build but not working in release build.

### Expected behavior

just show the image

![image](https://github.com/user-attachments/assets/142362f1-4553-4c74-b7f0-9a11852dc0f5)

### Full `tauri info` output

```text
[✔] Environment
    - OS: Arch Linux Unknown x86_64 (X64)
    ✔ webkit2gtk-4.1: 2.46.4
    ✔ rsvg2: 2.59.2
    ✔ rustc: 1.85.0-nightly (c94848c04 2024-12-05)
    ✔ cargo: 1.85.0-nightly (05f54fdc3 2024-12-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: nightly-x86_64-unknown-linux-gnu (default)
    - node: 23.5.0
    - yarn: 1.22.22
    - npm: 10.9.2

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.2
    - tao 🦀: 0.30.8
    - @tauri-apps/api : 2.1.1
    - @tauri-apps/cli : 2.1.0

[-] Plugins
    - tauri-plugin-dialog 🦀: 2.2.0
    - @tauri-apps/plugin-dialog : 2.2.0
    - tauri-plugin-fs 🦀: 2.2.0
    - @tauri-apps/plugin-fs : 2.2.0

[-] App
    - build-type: bundle
    - CSP: default-src 'self'; image-src 'self' 'data:' 'http://asset.localhost'
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment]
did you try a debug build via the --debug flag (output in target/debug/)? -> Alternatively you can add the `devtools` feature flag to the tauri dependency in cargo.toml to also enable them for release builds.

Wwith the devtools attached you can check its console and network tab for errors. I would suspect it to be a CSP misconfiguration but not sure.

If you don't see anything in the devtools console would it be possible to create a minimal reproduction for us to try? Alternatively you could also compare it with the default `create-tauri-app` templates which also use images.

**Comment by Walker-00** [comment]
Haven't tried with devtools but here is the repo for the project: https://github.com/ProductXx/Ough

**Comment by Walker-00** [comment]
it's a csp miss config I change it to 
``` 
""csp": {
  22   │         "default-src": "'self' customprotocol: asset:",
  23   │         "connect-src": "ipc: http://ipc.localhost",
  24   │         "font-src": ["https://fonts.gstatic.com"],
  25   │         "img-src": "'self' asset: http://asset.localhost blob: data:",
  26   │         "style-src": "'unsafe-inline' 'self' https://fonts.googleapis.com"
  27   │       }```

it work perfectly with both file path and base64 in dev and release. thanks.
