### ISSUE TITLE
[feat] cookie

### ISSUE THREAD

**Issue by 1937650094** [tauri-apps/tauri#12078]
### Describe the problem

When webview is embedded in the instagram website, how do I get all its cookies and set cookies to block all the requests and responses of the webview, just like capturing packets?

### Describe the solution you'd like

When webview is embedded in the instagram website, how do I get all its cookies and set cookies to block all the requests and responses of the webview, just like capturing packets?

### Alternatives considered

When webview is embedded in the instagram website, how do I get all its cookies and set cookies to block all the requests and responses of the webview, just like capturing packets?

### Additional context

When webview is embedded in the instagram website, how do I get all its cookies and set cookies to block all the requests and responses of the webview, just like capturing packets?

**Comment by FabianLars** [comment]
there's no api for this yet. Closing as a duplicate of #5823, #11691 and maybe #4899
