### ISSUE TITLE
Dir.App in JS API has no reference in MacOS Catalina

### ISSUE THREAD

**Issue by rx2347** [tauri-apps/tauri#1214]
**Describe the bug**
Dir.App in the JS API has no reference (?) / not working, when writing file.

**To Reproduce**
Write a file to Dir.App with writeFile({ path: 'tauritestfile.txt', contents: 'this is tauri' }, { dir: Dir.App })

**Expected behavior**
Create a file in App Directory / App Data Directory. Where exactly? I don't know, but it doesn't create a file anywhere (Dir.Data does) and it does not output any errors to console. I checked if this is due to using tauri:serve, but a build had the same problem.

**Platform and Versions (please complete the following information):**
Operating System - Darwin(19.6.0) - darwin/x64
Node.js environment
  Node.js - 12.16.2
  tauri.js - 0.14.1
Rust environment
  rustc - 1.49.0
  cargo - 1.49.0
  tauri-bundler - 0.9.4
Global packages
  NPM - 7.5.3
  yarn - 1.22.4

**Comment by lucasfernog** [comment]
I just tested this on macOS and it's working as expected: the file is written to `$HOME/Library/Application Support/your.app.id/tauritestfile.txt`, where `your.app.id` is the bundle identifier defined on the `tauri.conf.json > tauri > bundler > identifier` option.

The documentation was updated, you can see this on https://tauri.studio/en/docs/api/js/modules/path#appdir and https://tauri.studio/en/docs/api/js/modules/path#configdir
