### ISSUE TITLE
Spawned child standard stream access

### ISSUE THREAD

**Issue by kettek** [tauri-apps/tauri#1229]
**Is your feature request related to a problem? Please describe.**
I wanted to use this as the frontend to an IPC service. This service can connect through sockets or standard streams to transfer JSON messages. As far as I can tell, Tauri does not provide any way to set up bi-directional communication with a spawned process via stdout/stdin. The only available API is [execute](https://tauri.studio/en/docs/api/js#functions-5), however that is intended for simply spawning a process and retrieving its stdout once finished.

**Describe the solution you'd like**
I would like an API that would provide a way to set up bi-directional communication with the stdout/stdin/stderr of a spawned child process. This could be set up with EventEmitters, callbacks, or whatever the idiomatic Tauri-way is to handle the appropriate standard streams.

**Describe alternatives you've considered**
Ultimately switching to NW.js or Electron, as the target IPC service requires either sockets or standard stream usage.

**Additional context**
nada

**Comment by lucasfernog** [comment]
This is planned for the next release.

**Comment by kettek** [comment]
Glad to hear and I look forward to it!
