### ISSUE TITLE
External bins could be bundled without target in the name?

### ISSUE THREAD

**Issue by OJFord** [tauri-apps/tauri#1236]
**Is your feature request related to a problem? Please describe.**
`externalBin`s have to have the form `name-$TARGET` on the file system, where `name` is what's actually specified in the array. This much makes sense, but it's a slight pain to then use them from them main application which has to look for them in the bundle with that name.

**Describe the solution you'd like**
It would be convenient if `name-$TARGET` was bundled as simply `name`, since there would be no conflict once bundled.

**Describe alternatives you've considered**
Can look up the `uname` at runtime, or `name-*`, or whatever, to find the appropriate (and only) binary.

**Additional context**

**Comment by lucasfernog** [comment]
How would you differentiate the linux and macOS binaries then?
We do provide an API to find the binary path though (which will be improved on the next release).

**Comment by OJFord** [comment]
> How would you differentiate the linux and macOS binaries then?

I've only been using one machine so far, so I assumed only the relevant `name-$TARGET` binary was included in `$TARGET`'s build - `bundle/osx/app_1.2.3_x64.app` only needs the `x86_64-apple-darwin` variant, for example?

 > We do provide an API to find the binary path though
 
 Ah yes - `tauri_utils::platform::target_triple()` 👍🏻.
 
 This makes me realise another issue - the path would be `format!("{}/../Contents/{}-{}", resource_dir(), bin_name, target_triple())` on MacOS, but that `../Contents` is platform-specific. (I don't have my usual Linux machine to hand, but I assume it would be in `libexec` instead.) Perhaps that's what's known about and to be impoved in the next release? 🙂 
 
 (To circle back to the first point, I think it would be unusual to put `x86_64-linux-gnu` or whatever suffixes there on a system whereethat's necessarily the case for all (functional) binaries. Perhaps I've misunderstood?)

**Comment by OJFord** [comment]
At least, those are the paths mentioned in [the docs](https://tauri.studio/en/docs/api/rust/tauri_utils/platform/fn.resource_dir) - what I'm actually seeing is it returning the path to the parent directory of the main app, i.e. `src-tauri/target/debug`, or `src-tauri/target/debug/bundle/osx/app_version.app/Contents/MacOS`, et al. - not (as the docs say):
> `${exe_dir}../Resources` (inside .app).

(It's actually more convenient for this purpose as it is. Though maybe the name's confusing if you _did_ want icons or whatever from `Resources`.)

**Comment by lucasfernog** [comment]
> > How would you differentiate the linux and macOS binaries then?
> 
> I've only been using one machine so far, so I assumed only the relevant `name-$TARGET` binary was included in `$TARGET`'s build - `bundle/osx/app_1.2.3_x64.app` only needs the `x86_64-apple-darwin` variant, for example?
> 
> > We do provide an API to find the binary path though
> 
> Ah yes - `tauri_utils::platform::target_triple()` 👍🏻.
> 
> This makes me realise another issue - the path would be `format!("{}/../Contents/{}-{}", resource_dir(), bin_name, target_triple())` on MacOS, but that `../Contents` is platform-specific. (I don't have my usual Linux machine to hand, but I assume it would be in `libexec` instead.) Perhaps that's what's known about and to be impoved in the next release? 
> 
> (To circle back to the first point, I think it would be unusual to put `x86_64-linux-gnu` or whatever suffixes there on a system whereethat's necessarily the case for all (functional) binaries. Perhaps I've misunderstood?)

I meant [this API](https://docs.rs/tauri-api/0.7.5/tauri_api/command/fn.binary_command.html) (yeah it doesn't look so good or easy to understand, it'll be rewritten.

**Comment by OJFord** [comment]
Ah, thanks! `tauri_api::command::get_output("name".into(), args, std::process::Stdio::piped())` is just what I needed. 🙂

**Comment by lucasfernog** [comment]
I'm reopening this issue because I think we should support this.

**Comment by lucasfernog** [comment]
I've evaluated it and the change isn't worth the work IMO - convention over configuration. We can reevaluate if more people prefers this, but since Tauri is a cross platform framework, I think we should stick with the target triple solution.
