### ISSUE TITLE
Cli dependencies overridden by user project dependencies

### ISSUE THREAD

**Issue by zakpatterson** [tauri-apps/tauri#1250]
**Describe the bug**
If a user adds a current version of `ajv` as a dependency to their project, the tauri cli breaks.

**To Reproduce**
I created a minimal example that shows this, please see this commit: https://github.com/zakpatterson/tauri-broken/commit/d71ae44076f8732182ad9ce66cceeb4d456add42

I simply ran `yarn create react-app --template typescript .`, `yarn add tauri; yarn tauri init;` to create the project as usual, then the commit above shows the project breaking with the below error on `yarn install; yarn tauri dev`.

**Expected behavior**
The CLI should be using it's own dependency, not be overridden by the dependencies of the user's project. I think this is happening just because the scripts in bin are being run directly from the user's directory when calling `yarn tauri dev`, and somewhere requiring in the user's copy of ajv instead of the one compiled with tauri. [Version 6 `ValidateFunction`s return a promise](https://github.com/ajv-validator/ajv/blob/v6.12.6/lib/ajv.d.ts#L150) when called, but in [version 7 it is done synchronously](https://github.com/ajv-validator/ajv/blob/v7.1.1/lib/types/index.ts#L48). Links to relevant lines.

Of course the same error occurs if I run `node ./node_modules/tauri/bin/tauri.js dev`

**Screenshots**

**Platform and Versions (please complete the following information):**

➜  tauri-broken git:(master) yarn tauri info
yarn run v1.22.10
$ /home/projects/tauri-broken/node_modules/.bin/tauri info
[tauri]: running info

Operating System - Linux(5.8.0-7642-generic) - linux/x64

Node.js environment
  Node.js - 14.15.5
  tauri.js - 0.14.1

Rust environment
  rustc - 1.45.0
  cargo - 1.45.0
  tauri-bundler - 0.9.4

Global packages
  NPM - 6.14.11
  yarn - 1.22.10

App directory structure
/.git
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 0.11.1
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist
  devPath - http://localhost:3000
Done in 2.53s.

**Additional context**
Referencing another project I'm working on: https://github.com/thegrims/UsTaxes/issues/115

**Stack Trace**
```
➜  tauri-broken git:(master) ✗ yarn tauri dev
yarn run v1.22.10
$ /home/projects/tauri-broken/node_modules/.bin/tauri dev
[tauri]: running dev
NOT SUPPORTED: option format. `validateFormats: false` can be used instead.
NOT SUPPORTED: option nullable. "nullable" keyword is supported by default.
NOT SUPPORTED: option uniqueItems. "uniqueItems" keyword is always validated.
DEPRECATED: option unicode. "minLength"/"maxLength" account for unicode characters by default.
(node:63957) UnhandledPromiseRejectionWarning: Error: strict mode: unknown keyword: "defaultProperties"
    at Object.checkStrictMode (/home/projects/tauri-broken/node_modules/ajv/dist/compile/validate/index.js:183:15)
    at Object.checkUnknownRules (/home/projects/tauri-broken/node_modules/ajv/dist/compile/util.js:32:24)
    at checkKeywords (/home/projects/tauri-broken/node_modules/ajv/dist/compile/validate/index.js:118:12)
    at Object.validateFunctionCode (/home/projects/tauri-broken/node_modules/ajv/dist/compile/validate/index.js:14:9)
    at Ajv.compileSchema (/home/projects/tauri-broken/node_modules/ajv/dist/compile/index.js:78:20)
    at Ajv._compileSchemaEnv (/home/projects/tauri-broken/node_modules/ajv/dist/core.js:444:37)
    at Ajv.compile (/home/projects/tauri-broken/node_modules/ajv/dist/core.js:139:38)
    at Object../src/types/config.validator.ts (/home/projects/tauri-broken/node_modules/tauri/dist/api/dev.js:1665:37)
    at __webpack_require__ (/home/projects/tauri-broken/node_modules/tauri/dist/api/dev.js:1910:42)
    at Object../src/helpers/tauri-config.ts (/home/projects/tauri-broken/node_modules/tauri/dist/api/dev.js:446:26)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:63957) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:63957) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 0.91s.
```

**Comment by lucasfernog** [comment]
This will be fixed on the next release. (we're moving to a Rust-based CLI, with a Node.js wrapper)

**Comment by zakpatterson** [comment]
@lucasfernog Ah I didn't even see that the rust cli got merged. I'll definitely try that out. Thanks!

**Comment by readeral** [comment]
Keen for this, just started trying to use Tauri and have run up against this issue with a CRA project.

**Comment by nklayman** [comment]
Next release is scheduled for this month, we mostly just have documentation left. Until then, you should be able to fix this with [Yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/), which would allow you to force the proper version of ajv.

**Comment by readeral** [comment]
Thanks for pointing me in the right direction @nklayman

**Comment by zakpatterson** [comment]
@nklayman I tried this out for a while, but the issue I think is that the tauri dev script itself summons ajv using `require("ajv")`, so it tries to resolve exactly the same version of ajv that's used in the root project.

**Comment by zakpatterson** [comment]
@nklayman @readeral I just got past this, my solution was to add "ajv" as a dependency to my root project twice, as:

```
    "ajv": "^6.12.6",  // for tauri
    "ajv7": "npm:ajv@^7.1.1",  // for me
```
And then in my project I can just `import ajv from 'ajv7'`

So if resolutions doesn't work for you @readeral then try that!
