### ISSUE TITLE
Multiple FilePicker Dialogs

### ISSUE THREAD

**Issue by ArishSultan** [tauri-apps/tauri#1251]
So, i was just trying out `tauri` with `Vue.js`, i invoked the `open` method provided by the tauri package to open a file picker dialog. I added this functionality on a button click event.

-- First thing is that it do not behaves as a Modal Dialog, i was still able to interact with the application whereas the dialog was opened in the background.

-- If you again invoke the method than it will open a new dialog instead of giving a warning or something.

-- Now if you select the files from the newly opened dialog (not the one that's minimized). it will not get selected. instead you will have to select file from the dialog that was opened first.

**Platform and Versions (please complete the following information):**

OS: Ubuntu 20.04
Node: 14+
NPM: 6+
Rustc: 1.44.1

**Comment by lucasfernog** [comment]
Thanks for reporting it!
