### ISSUE TITLE
Notification's permission request should have i18n

### ISSUE THREAD

**Issue by lucasfernog** [tauri-apps/tauri#1252]
We ask for permissions before sending notifications, and the message is always in English. Should we implement i18n or remove that instead? 

https://github.com/tauri-apps/tauri/blob/4d56e5e6919f04e2889900957be02fef1dd8f59f/tauri/src/endpoints/notification.rs#L84

**Comment by amrbashir** [comment]
Adding i18n is definitely good but wouldn't it be better to let developers handle that on their own and maybe they would want to pass custom messages.

**Comment by nothingismagick** [comment]
I think @lucasfernog is right. At some point we will need to impl. i18n and permissions is SOOO important. Not sure what the right solution is, but we need to track it and find one.

**Comment by tensor-programming** [comment]
Intl is something we should look into (aka i18n).  For devs, they can specify what their tag should be from the config file and we can provide other solutions for things like permissions and message passing.  Also, we can create a list of locales that the dev wants to support and implement them from the installers/packages through the bundler.

**Comment by lucasfernog** [comment]
We also need i18n for the default updater dialog (or just drop it and let the user handle it).

**Comment by 9ParsonsB** [comment]
Related: #2317
