### ISSUE TITLE
Beta RC and Issues. Please read this before filing a new issue

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#1253]
We are working like monsters on the upcoming beta release candidate. This means that issues regarding the pre-beta state of Tauri are likely no longer relevant with the release and unlikely to be fixed in the current state of the libraries. To this end, we humbly request that you refrain from filing issues unless you are actually using the dev branch or involved in the massively awesome revisions.

Thank you for understanding

**Comment by nklayman** [comment]
Remember that if you have a question or need help with Tauri, our [discussions page](https://github.com/tauri-apps/tauri/discussions) is open and all are welcome to join our [Discord Server](https://discord.com/invite/SpmNs4S) :)
