### ISSUE TITLE
Github Actions Checks API

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#127]
**Is your feature request related to a problem? Please describe.**
It would be brilliant to have access to the Checks API in order to figure out what specific build pipelines (eg. MacOS NodeJS) are working on Master. We currently have a "workflow badge" -- but that is all or nothing:
`https://img.shields.io/github/workflow/status/tauri-apps/tauri/test%20library?label=test%20library`
![](https://img.shields.io/github/workflow/status/tauri-apps/tauri/test%20library?label=test%20library)

Here is a bit of a description:
https://github.com/badges/shields/issues/2574#issuecomment-522347747

https://api.github.com/repos/tauri-apps/tauri/commits/dev/check-runs

**Describe the solution you'd like**
Considering the API from Github is in beta - it would maybe make sense to setup our own service to produce these checks - perhaps self-hosted. But ideas are welcome!

**Describe alternatives you've considered**
Wait for someone else to solve it?

**Comment by nothingismagick** [comment]
@jbolda - is this something we can revisit?

**Comment by jbolda** [comment]
I think we are waiting on this one.
https://github.com/badges/shields/issues/4364
