### ISSUE TITLE
Link broken in Demo App after PR #1264

### ISSUE THREAD

**Issue by twick00** [tauri-apps/tauri#1274]
**Describe the bug**
The `Source for this App` link is broken (404) in demo app after PR #1264 was merged since it moved the file to a different path.

**To Reproduce**
1. Go to Demo App
2. Click on `Source for this App'
3. Observe Github 404

**Expected behavior**
It should link to a non-404 page. Maybe that page is just an empty repo saying that it was moved.

Suggested fixes:
1. Add a placeholder README.md to the path linked in the demo app 
(https://github.com/tauri-apps/tauri/tree/dev/tauri/examples/communication)
2. Revert PR #1264 (probably not going to happen)
3. Update the Demo App to point to the correct path:
 (https://github.com/tauri-apps/tauri/tree/dev/tauri/examples/api)

**Comment by twick00** [comment]
The `bug` label is wrong here but I can't update it. If someone with the authority to do so could update it I would appreciate it 🙇🏻

**Comment by lucasfernog** [comment]
We're aware of that and the demo app will be updated on the next release. Thanks for the report :)

**Comment by twick00** [comment]
Dang that was a fast response. Thanks for the super hard work you guys. ❤️
