### ISSUE TITLE
Unable to use devPath without port

### ISSUE THREAD

**Issue by Armaldio** [tauri-apps/tauri#1297]
**Describe the bug**
`tauri dev` output an error when using a devPath without a port

**To Reproduce**
1. Create a tauri app
2. Insert `devPath: https://google.com`
3. Run `tauri dev`

**Expected behavior**
I can run any URL

**Screenshots**
![image](https://user-images.githubusercontent.com/3089715/109190590-83343000-7795-11eb-9a5f-42b2144132d1.png)
![image](https://user-images.githubusercontent.com/3089715/109190620-8deec500-7795-11eb-8eca-5825785e3c47.png)

**Platform and Versions (please complete the following information):**

OS: Manjaro
Node: 14.15.4
NPM: 6.14.10
Yarn: 1.22.10
Rustc: 1.50.0

**Additional context**

**Stack Trace**
```
$ /tmp/cyn_tauri_app/node_modules/.bin/tauri dev --cwd=/tmp/cyn_tauri_app
[tauri]: running dev
(node:745959) UnhandledPromiseRejectionWarning: RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received NaN.
    at validatePort (internal/validators.js:211:11)
    at Server.listen (net.js:1444:5)
    at /tmp/cyn_tauri_app/node_modules/tauri/dist/api/dev.js:285:30
    at new Promise (<anonymous>)
    at /tmp/cyn_tauri_app/node_modules/tauri/dist/api/dev.js:261:46
    at step (/tmp/cyn_tauri_app/node_modules/tauri/dist/api/dev.js:225:23)
    at Object.next (/tmp/cyn_tauri_app/node_modules/tauri/dist/api/dev.js:206:53)
    at /tmp/cyn_tauri_app/node_modules/tauri/dist/api/dev.js:200:71
    at new Promise (<anonymous>)
    at __webpack_modules__../src/helpers/net.ts.__awaiter (/tmp/cyn_tauri_app/node_modules/tauri/dist/api/dev.js:196:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:745959) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:745959) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 2.78s.
```

**Comment by nklayman** [comment]
This is already fixed in the new Rust CLI that will come with the next release :tada:

**Comment by Armaldio** [comment]
When can I expect the new CLI release 😊?

**Comment by nklayman** [comment]
Probably in a few weeks. If you really want to use it now, you can see the [contributing guide](https://github.com/tauri-apps/tauri/blob/dev/.github/CONTRIBUTING.md) for instructions on using the dev branch code.
