### ISSUE TITLE
`externalBin` not copied in dev mode

### ISSUE THREAD

**Issue by gabcoh** [tauri-apps/tauri#1298]
**Describe the bug**
The primary issue is `tauri::api::command::command_path` does not give valid path when run in dev mode. However, it can also be viewed as `tauri dev` failing to copy `externalBins` to to target directory.

**To Reproduce**
1. Add `externalBin: ["localfile"]
2. In `main.rs` print `tauri::api::command::command_path`
3. run `tauri dev`
4. the printed file will not exist

**Expected behavior**
In dev mode tauri should either copy over the external bins to the target directory and `tauri::api::command::command_path` can remain unchanged or `tauri::api::command::command_path` should check if it is run in dev mode and if so directly return the path provided in `externalBin`

**Platform and Versions (please complete the following information):**

OS: Linux
Node: 15.8.0
NPM: 6.1.11
Yarn: 1.22.10
Rustc: 1.50.0

**Additional context**

**Stack Trace**

**Comment by ZelCloud** [comment]
This seems to be an issue in tauri v2 still.

Running 
```javascript 
import { Command } from '@tauri-apps/plugin-shell';
const command = Command.sidecar("bin/main");
```

Seems to generate a `Scoped command bin/main not found` error. Though the binary exists since `tauri dev` won't build and work unless the binary is found.

**Comment by FabianLars** [comment]
@ZelCloud This error sounds more like a config (==capabilities/permissions) issue.

**Comment by Stancobridge** [comment]
Am facing this issue currently, how can one resolve it
`Scoped command binaries/main not found`

**Comment by valentimcanejo** [comment]
> Am facing this issue currently, how can one resolve it `Scoped command binaries/main not found`

did you solve this? if yes, how?

**Comment by Stancobridge** [comment]
hi @valentimcanejo, I was able to fix this

here is how I was able to solve it.

```json
{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "default",
  "description": "Capability for the main window",
  "windows": ["main"],
  "permissions": [
    "core:path:default",
    "core:event:default",
    "core:window:default",
    "core:app:default",
    "core:resources:default",
    "core:menu:default",
    "core:tray:default",
    "store:default",
    {
      "identifier": "shell:allow-spawn",
      "allow": [
        {
          "name": "binaries/main",
          "sidecar": true
        }
      ]
    },
    "shell:allow-open"
  ]
}
```

this file is located in `src-tauri/capabilities/default.json`

I don't know why this is not mentioned in their documentation.

here is how I start the sidecar using spawn which is what I need for my usecase,

```js
const command = Command.sidecar("binaries/main");
const  childProcess = await command.spawn();
```

if u want to use `execute()` method, replace the `"shell:allow-spawn"` with `"shell:allow-execute"`

**Comment by FabianLars** [comment]
> I don't know why this is not mentioned in their documentation.

What exactly is not mentioned?

**Comment by Stancobridge** [comment]
> > I don't know why this is not mentioned in their documentation.
> 
> What exactly is not mentioned?

The documentation did not mention you need to add this to `src-tauri/capabilities/default.json` before the sidecar will work, it was only mentioned in the part where you need to add args to the sidecar, for someone that did not need to run the sidecar with args, you would think that this is not required.

I think adding this in the beginning setup guide for running the sidecar in JS is necessary.
```json
{
      "identifier": "shell:allow-spawn",
      "allow": [
        {
          "name": "binaries/main",
          "sidecar": true
        }
      ]
    },
    "shell:allow-open"
```

>> I would be contributing this to the guide by tomorrow.

**Comment by FabianLars** [comment]
> The documentation did not mention you need to add this to src-tauri/capabilities/default.json before the sidecar will work, it was only mentioned in the part where you need to add args to the sidecar, for someone that did not need to run the sidecar with args, you would think that this is not required.

Ahhh i see, you're right of course.
