### ISSUE TITLE
Provide a helpful error message if devPath is not specified

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#130]
**Describe the bug**
Provide a helpful error message if devPath is not specified

see #129 for a solution - but we would prefer to do the detection in `tauri-config.js`

**Comment by nklayman** [comment]
Maybe it is better to leave in the runner, as the Vue CLI Plugin sets the devPath after getting the config from `tauri-config.js`.

**Comment by rajivshah3** [comment]
@nklayman was this fixed in #599?

**Comment by nklayman** [comment]
Yep, it was. Thanks for noticing!
