### ISSUE TITLE
[Windows 10] Basic setup does not run throws error - exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN

### ISSUE THREAD

**Issue by geocine** [tauri-apps/tauri#1302]
**Describe the bug**
App does not run , exits right away and throws error - `exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN`

**To Reproduce**
1. Create react-ts app using vitejs
   ```shell
   yarn create @vitejs/app
   yarn
   yarn build
   ```
2. Add Tauri integration by following https://tauri.studio/en/docs/development/integration. Use `http://localhost:3000` for devPath
3. Run react-ts app
   ```shell
   yarn dev
   ```
3. Run tauri app  
   ```shell
   yarn tauri dev
   ```
4. Throws an error
   ```shell
    Running `target\debug\tauri-app.exe`
    Running Loopback command
    fatal runtime error: Rust cannot catch foreign exceptions
    error: process didn't exit successfully: `target\debug\tauri-app.exe` (exit code
    : 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
    
     app:spawn Command "cargo" failed with exit code: 3221226505 +0ms
    
     app:tauri (runner) ⚠️  [FAIL] Cargo CLI has failed +0ms
    
     app:tauri Shutting down tauri process... +2ms
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
    and.
    ```

**Expected behavior**
Shoud open the application

**Platform and Versions (please complete the following information):**
```shell
Operating System - Windows_NT(10.0.19041) - win32/x64
Microsoft Edge - 44.19041.1.0_neutral__8wekyb3d8bbwe

Node.js environment
  Node.js - 14.15.1
  tauri.js - 0.14.1

Rust environment
  rustc - 1.50.0
  cargo - 1.50.0
  tauri-bundler - 0.9.4

Global packages
  NPM - 6.14.8
  yarn - 1.22.5

App directory structure
/dist
/node_modules
/src
/src-tauri

App
  tauri.rs - 0.11.1
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsa
fe-inline'
  distDir - ../dist
  devPath - http://localhost:3000
```

**Additional context**
I tried the exact same steps on my macOS Mojave 10.14.6 , it was running fine

**Comment by nothingismagick** [comment]
Have you tried installing the Webview2 evergreen installer? 
https://developer.microsoft.com/en-us/microsoft-edge/webview2/

The numerous problems with windows are also why we are building our own rust-based interface to the webviews: 
https://github.com/tauri-apps/wry

Please don't take this the wrong way, but we are really focussed on getting the new version of Tauri ready, and there are lots of things that are changing all at once. If your problem persists, please feel free to visit our discord and we can try to help you there.

**Comment by nothingismagick** [comment]
And FYI: https://github.com/tauri-apps/tauri/issues/1253
