### ISSUE TITLE
error: failed to run custom build command for `tauri v0.11.1`

### ISSUE THREAD

**Issue by MonkeyInWind0** [tauri-apps/tauri#1305]
npm run tauri build

error: failed to run custom build command for `tauri v0.11.1`
...
  --- stderr
  Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
warning: build failed, waiting for other jobs to finish...
error: build failed
error: `Result of `cargo build` operation was unsuccessful: exit code: 101`

 app:spawn Command "cargo" failed with exit code: 1 +1ms

 app:tauri (runner) ⚠️  [FAIL] Cargo CLI has failed +0ms

 app:tauri Shutting down tauri process... +1ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tauri-app@0.1.0 build: `node scripts/build.js & tauri build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tauri-app@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

cargo tauri-bundler -v
0.9.4

OS:   macOs Big Sur
Node:   14.16.0
NPM:  6.14.11

**Comment by lucasfernog** [comment]
Did you install the tauri bundler? https://tauri.studio/en/docs/get-started/setup-linux#4-tauri-bundler

**Comment by lucasfernog** [comment]
I'm closing this since the bundler will be a library and you won't be needed to install it on the next release anyway. Let me know if this is still an issue for you.

**Comment by MonkeyInWind0** [comment]
> Did you install the tauri bundler? https://tauri.studio/en/docs/get-started/setup-linux#4-tauri-bundler

cargo tauri-bundler -v
0.9.4

**Comment by nklayman** [comment]
I think that error may be caused when Tauri can't find your web assets. Can you post the result of `tauri info`?

**Comment by MonkeyInWind0** [comment]
> I think that error may be caused when Tauri can't find your web assets. Can you post the result of `tauri info`?

![image](https://user-images.githubusercontent.com/34543887/109500848-bfd39480-7ad1-11eb-8f01-b453894ac418.png)

Looks no problem, but I can not build.

**Comment by MonkeyInWind0** [comment]
![image](https://user-images.githubusercontent.com/34543887/109501537-ae3ebc80-7ad2-11eb-8325-50c7ace856e3.png)
Look, my demo is very easy.
create-react-app + tauri

**Comment by nothingismagick** [comment]
are you building your react assets before you run `tauri build`

**Comment by MonkeyInWind0** [comment]
> are you building your react assets before you run `tauri build`

yes I did.

**Comment by nothingismagick** [comment]
do you have a github repo where i can clone and test it out locally?

**Comment by MonkeyInWind** [comment]
> do you have a github repo where i can clone and test it out locally?
[https://github.com/tauri-apps/tauri/issues/1305#issuecomment-787948350](https://github.com/tauri-apps/tauri/issues/1305#issuecomment-787948350)

**Comment by MonkeyInWind0** [comment]
> do you have a github repo where i can clone and test it out locally?

[https://github.com/MonkeyInWind/tauri-demo](https://github.com/MonkeyInWind/tauri-demo)

**Comment by nklayman** [comment]
@MonkeyInWind I tested your repo and it worked just fine for me, both build and dev. I did have to change the build script to have `&&` instead of `&`, but it didn't give me the same error you got. Unfortunately, I'm not sure what your issue is or what you can do to fix it. However, the next release of Tauri (coming this month hopefully) has a rewritten CLI that should fix your issue.

**Comment by MonkeyInWind0** [comment]
> @MonkeyInWind I tested your repo and it worked just fine for me, both build and dev. I did have to change the build script to have `&&` instead of `&`, but it didn't give me the same error you got. Unfortunately, I'm not sure what your issue is or what you can do to fix it. However, the next release of Tauri (coming this month hopefully) has a rewritten CLI that should fix your issue.

Ok, I will try to remove and reinstall, after the next version is released.
Thanks.
