### ISSUE TITLE
Icon on windows

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#133]
**Is your feature request related to a problem? Please describe.**
The icon in the webview frame of the built app in windows looks terrible. 

**Describe the solution you'd like**
https://github.com/mxre/winres

We are shipping the .ico file - I'm not sure why it isn't working...

**Comment by tensor-programming** [comment]
Ill take care of this.  I looked at Winres and also am looking at the Wix solutions.

**Comment by tensor-programming** [comment]
I think using winres might be a bad idea since it forces you to add a `build.rs` file.

**Comment by tensor-programming** [comment]
Closed via PR #211
