### ISSUE TITLE
The window title has character corruption contains Japanese string

### ISSUE THREAD

**Issue by nano-nano** [tauri-apps/tauri#1339]
**Describe the bug**
The window title has character corruption when use `setTitle(...)` with Japanese string.

**To Reproduce**
1. Create a new project.
2. Implement `setTitle('こんにちはTauri')` in JavaScript code. 
3. Start devserver and Tauri dev window.
4. See window title.

**Expected behavior**
The window title shown without character corruption.

**Screenshots**
![window](https://user-images.githubusercontent.com/29051777/110460615-c5545e80-8111-11eb-8066-170ce9266544.png)

**Platform and Versions (please complete the following information):**
OS: Windows_NT(10.0.19041) - win32/x64
Node: 14.15.3
NPM: 6.14.9
Yarn: 1.22.4
Rustc: 1.50.0

**Additional context**
When use `alert(...)` with Japanese string, the dialog message also has character corruption.

**Comment by nothingismagick** [comment]
This should be resolved in the forthcoming beta release with the switch to https://github.com/tauri-apps/wry
