### ISSUE TITLE
Support frameless windows

### ISSUE THREAD

**Issue by Milo123459** [tauri-apps/tauri#1340]
**Is your feature request related to a problem? Please describe.**
Yes, see [here](https://github.com/tonybaloney/vscode-pets/issues/4#issuecomment-792733140)
**Describe the solution you'd like**
Support for frameless windows
**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by nothingismagick** [comment]
This will be available in Beta. To see it working, please visit:
https://github.com/tauri-apps/wry/blob/master/examples/transparent.rs
