### ISSUE TITLE
WebView2 / Windows / User Privacy / SmartScreen

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#1345]
**Is your feature request related to a problem? Please describe.**
By default, WebView2 will ship with telemetry. Here is insight into how to turn off SmartScreen:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/834

**Would you assign yourself to implement this feature?**
- [x] No

**Additional context**
Should we do this here in the bundler or in WRY? 
If we do it here, how do we inform non-tauri consumers of WRY?

**Comment by nothingismagick** [comment]
There are many concerns with the dubious way in which webview2 has been licensed. Apparently the current evergreen license is a "stand-in" for something that will be way better, but I am concerned this is not being taken seriously. A very insightful issue was just filed about Privacy in commercial applications: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1059

And I filed an issue here about what seems to be WebView2 apps used as spyware:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/916

I think that it will all resolve before April 10th ([when WebView2 is unleashed](https://blogs.windows.com/msedgedev/2021/03/09/microsoft-edge-legacy-end-of-support/)), but this should serve as a reminder to everybody to read those EULAs!

**Comment by nothingismagick** [comment]
As a heads up, on of the licensing issues have been resolved (the one where it was impossible to use webview2 for any purposes)

**Comment by FabianLars** [comment]
>  ([when WebView2 is unleashed](https://blogs.windows.com/msedgedev/2021/03/09/microsoft-edge-legacy-end-of-support/))

Where/when did they actually say that?
Both blog posts i see you mentioning ([1](https://blogs.windows.com/msedgedev/2021/03/09/microsoft-edge-legacy-end-of-support/) / [2](https://techcommunity.microsoft.com/t5/microsoft-365-blog/new-microsoft-edge-to-replace-microsoft-edge-legacy-with-april-s/ba-p/2114224)) don't really mention WebView at all and Edge (at least the stable version) and WebView2 isn't the same.
Also (2) actually mentions EdgeHTML still being supported (that might be unrelated, but it's the closest mention we've got).
On top of that, there is no mention of a release or something in the WebView2 Repos (Announcements and Feedback) at all.

I might be missing something and I also want it to be true, but I can't find a more or less official source for this and want to keep our expecations realistic.

**Comment by amrbashir** [comment]
With the next release of wry, SmartScreen will be automatically disabled.
