### ISSUE TITLE
dev: Image not showing on Release build on Windows 

### ISSUE THREAD

**Issue by geocine** [tauri-apps/tauri#1349]
**Describe the bug**
Using `dev` branch on Windows , image is not showing on release build but shows on development mode

**To Reproduce**
1. Use tauri `dev` branch on your Windows machine.
2. Clone repository https://github.com/geocine/tauri-app . This repo is a minimal reproduction of this issue
3. Go to `tauri-app` directory
3. Install dependencies and build `yarn install && yarn build`
4. Build `tauri-app` by running `tauri build`
   > Note:  Before building you need to fix the `tauri` path on the `src-tauri\Cargo.toml` https://github.com/geocine/tauri-app/blob/main/src-tauri/Cargo.toml#L15
5. Run the executable from `tauri-app\src-tauri\target\release\tauri-app.exe`
6. Notice you see the following screen, the image is not displaying
![notworking](https://user-images.githubusercontent.com/507464/110750164-07e67a00-827d-11eb-9ed9-3c3de98dfb07.gif)

**Expected behavior**
You should see the following screen:
![working](https://user-images.githubusercontent.com/507464/110748958-63b00380-827b-11eb-9c28-7624ac4677fb.gif)

**Platform and Versions:**
```
Operating System - Windows_NT(10.0.19041) - win32/x64
Microsoft Edge - 44.19041.1.0_neutral__8wekyb3d8bbwe

Node.js environment
  Node.js - 14.15.1
  tauri.js - 0.14.1 (350ebb8) dev branch

Rust environment
  rustc - 1.50.0
  cargo - 1.50.0
  tauri-bundler - 0.9.4

Global packages
  NPM - 6.14.8
  yarn - 1.22.5

App directory structure
/.git
/dist
/node_modules
/src
/src-tauri

App
  tauri.rs - 0.11.1
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist
  devPath - http://localhost:3000
```

**Additional context**
This is properly working on the release builds of tauri

**Comment by lucasfernog** [comment]
@geocine there was an issue and on dev Tauri wasn't serving your app from the URL. Can you try again with latest commits?

**Comment by lucasfernog** [comment]
Please reopen if you are still facing this issue.

**Comment by geocine** [comment]
I have tried this on the tauri beta I still experience the issue

```
Operating System - Windows_NT(10.0.19041) - win32/x64
Microsoft Edge - 44.19041.1.0_neutral__8wekyb3d8bbwe

Node.js environment
  Node.js - 14.15.1
  tauri.js - 0.14.1

Rust environment
  rustc - 1.51.0
  cargo - 1.51.0
  tauri-bundler - 0.9.4

Global packages
  NPM - 6.14.8
  yarn - 1.22.5

App directory structure
/.git
/dist
/node_modules
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta-rc.4
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist
  devPath - http://localhost:3000/

```
I will try the dev branch

**Comment by lucasfernog** [comment]
Seems like you only updated the Rust core crate though - check out the migration guide: https://tauri.studio/en/docs/guides/migration (you shouldn't have tauri.js v0.14.1 for instance).

**Comment by Fredolx** [comment]
I'm having the same problem with my app for Windows only. The problem occurs with the setup too.

```
Node.js: v16.14.2
Tauri and tauri-build: 1.0.0-rc.5
rust-version: 1.60
rustc: 1.60.0
cargo: 1.60.0
```

package.json angular dependencies:
```
  "dependencies": {
    "@angular/animations": "~13.3.0",
    "@angular/common": "~13.3.0",
    "@angular/compiler": "~13.3.0",
    "@angular/core": "~13.3.0",
    "@angular/forms": "~13.3.0",
    "@angular/localize": "~13.3.0",
    "@angular/platform-browser": "~13.3.0",
    "@angular/platform-browser-dynamic": "~13.3.0",
    "@angular/router": "~13.3.0",
    "@ng-bootstrap/ng-bootstrap": "^12.0.1",
    "@popperjs/core": "^2.10.2",
    "@tauri-apps/api": "^1.0.0-rc.3",
    "bootstrap": "^5.1.3",
    "ngx-toastr": "^14.2.4",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.3.0",
    "@angular/cli": "~13.3.0",
    "@angular/compiler-cli": "~13.3.0",
    "@tauri-apps/cli": "^1.0.0-rc.8",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~4.0.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.5.2"
  }
```

**Comment by ZhelinCheng** [comment]
This is also the case on macOS.

**Comment by lucasfernog** [comment]
Any errors in the console @ZhelinCheng ? try building with --debug to see it.

**Comment by orangelckc** [comment]
> 
@lucasfernog 
I am facing the same issue to load an image url starts with `http` only. 
Console returns the error ` The resource could not be loaded because the App Transport Security policy requires the use of a secure connection`.
I have tried to  set`csp` in `tauri.conf.json` to `"csp": "default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'"`, but still not works.
Sry I am new into tauri and rust. Hope you can give me a solution in some easy way.
Btw, i am using macos 12.4.

**Comment by lucasfernog** [comment]
@orangelckc in this case you need to configure an [exceptionDomain](https://tauri.app/v1/api/config/#macconfig.exceptiondomain) in tauri.conf.json.

**Comment by orangelckc** [comment]
> @orangelckc in this case you need to configure an [exceptionDomain](https://tauri.app/v1/api/config/#macconfig.exceptiondomain) in tauri.conf.json.

Thanks, it works now.
