### ISSUE TITLE
Tauri init fails to run

### ISSUE THREAD

**Issue by Reidond** [tauri-apps/tauri#135]
**Describe the bug**
Running `tauri init` crashes with no result.

**To Reproduce**
1. Run `tauri init`

**Expected behavior**
Bootsrapped `src-tauri` and `tauri.conf.js`.

**Screenshots**
[Screenshot](https://media.discordapp.net/attachments/625037620996734986/651716804430921738/Annotation_2019-12-04_112926.png?width=959&height=560)

**Platform (please complete the following information):**
OS: Windows 10 Build 19025.1052
Node: v12.13.1
NPM: 6.12.1
Yarn: 1.19.1
Tauri Binding: I guess latest
Bundle Target: I guess latest

**Additional context**
It crashes in file `template.js` here:
```js
const tomlPath = join(__dirname, '../../tauri/Cargo.toml')
const tomlFile = readFileSync(tomlPath)
```
join goes to path were npm stores symlinks to bin files
so i tried to clone repo with Cargo.toml and that failed because of tauri symlink (or hardlink)
i deleted that, cloned tauri, moved folder with Cargo.toml
and init worked without failures
but `src-tauri` wasn't created, only `tauri.conf.js`

**Comment by nothingismagick** [comment]
Thanks for filing this issue @Reidond.

**Comment by nothingismagick** [comment]
Should be resolved. @Reidond can you validate that it works?

**Comment by nothingismagick** [comment]
just `npm install --global tauri@latest`

**Comment by Reidond** [comment]
It works now
