### ISSUE TITLE
windows no run

### ISSUE THREAD

**Issue by shijunti19** [tauri-apps/tauri#1367]
yarn add tauri
# OR
npm install tauri --save

PS F:\web\xiaolu\tauri\a031> npm install tauri --save

> optipng-bin@7.0.0 postinstall F:\web\xiaolu\tauri\a031\node_modules\optipng-bin
> node lib/install.js

  ‼ getaddrinfo ENOENT raw.githubusercontent.com
  ‼ optipng pre-build test failed
  i compiling from source
  × Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "./configure --with-system-zlib --prefix="F:\web\xiaolu\tauri\a031\node_modules\optipng-bin\vendor" --bindir="F:\web\xiaolu\tauri\a031\node_modules\optipng-bin\vendor""
'.' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at F:\web\xiaolu\tauri\a031\node_modules\execa\index.js:231:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Promise.all (index 0)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN a031@1.0.0 No description
npm WARN a031@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! optipng-bin@7.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the optipng-bin@7.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\52752\AppData\Roaming\npm-cache\_logs\2021-03-18T01_06_53_704Z-debug.log

**Comment by lucasfernog** [comment]
Seems like an issue with the optipng-bin package installation, please search for that error or try to get community help on Discord.
