### ISSUE TITLE
How to support Chinese

### ISSUE THREAD

**Issue by shijunti19** [tauri-apps/tauri#1369]
How to support Chinese

    },
    "window": {
      "title": "你好",
      "width": 800,
      "height": 600,
      "resizable": true,
      "fullscreen": false
    },

![QQ截图20210318091726](https://user-images.githubusercontent.com/5392211/111559159-fd6f3780-87ca-11eb-8556-0ac50eb3b5f2.jpg)

windows10 
![QQ截图20210318091726](https://user-images.githubusercontent.com/5392211/111559241-1d066000-87cb-11eb-80bd-43ff2a338090.jpg)

**Comment by amrbashir** [comment]
~~This doesn't seem like a language support issue. 
Did you start the dev server? provide `tauri - - info`.~~

Edit:  sorry didn't see the window image, I only looked at the console output

**Comment by nothingismagick** [comment]
I think this is a known problem at webview/webview

**Comment by shijunti19** [comment]
Operating System - Windows_NT(10.0.19043) - win32/x64

Node.js environment
  Node.js - 15.11.0
  tauri.js - 0.14.1

Rust environment
  rustc - 1.52.0-nightly
  cargo - 1.52.0-nightly
  tauri-bundler - 0.9.4

Global packages
  NPM - 6.14.8
  yarn - 1.23.0-20200224.1838

App directory structure
/.vscode
/node_modules
/src-tauri

App
  tauri.rs - 0.11.1
  mode - no-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist
  devPath - http://localhost:4000
Done in 10.24s.

**Comment by wusyong** [comment]
We have a new system library. This will be fixed in beta release I believe.
![圖片](https://user-images.githubusercontent.com/8409985/111621868-70a49800-8823-11eb-8e42-9bc5f21fd3a5.png)

**Comment by shijunti19** [comment]
@wusyong okay, thank you

Now windows can't be used because pngquant can't be installed

**Comment by nothingismagick** [comment]
ok, I am going to close this issue. If it persists after beta, please feel free to reopen. :)
