### ISSUE TITLE
Using Tauri/Wry with Fixed Version of Webview2

### ISSUE THREAD

**Issue by geolehmann** [tauri-apps/tauri#1378]
**Describe the bug**
For the webview runtime, there is generally the possbility to pack the application with a fixed version of the runtime (aka bring-your-own, see https://developer.microsoft.com/en-us/microsoft-edge/webview2/). This is needed when the target audience has no elevated rights in their platform to install the runtime by theirself. 

I couldn´t find a way to make wry work with the fixed version of the runtime (simply putting the app .exe in the unzipped runtime folder didn´t work). It seems, in C++ you can use the `CreateCoreWebView2EnvironmentWithOptions` function together with a `browserExecutableFolder` parameter to specifiy where the fixed version binaries are located. We need something similar for Wry.

**Steps To Reproduce**

**Expected behavior**

**Platform and Versions (please complete the following information):**
OS: Windows

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [ ] No

**Additional context**

**Comment by nothingismagick** [comment]
My justification here is that there may be situations where you cannot rely on the internet for your installation and need to ship a complete system (e.g. airgapped systems).

**Comment by Boscop** [comment]
@geolehmann Note: When [this](https://github.com/tauri-apps/wry/issues/265#issuecomment-841804226) is merged, you can print a user-friendly error if WebView2 is not installed, indicating that if the user doesn't have admin rights, their admin should install it for them.

**Comment by lucasfernog** [comment]
This will be available on the next release.
