### ISSUE TITLE
Async Executor

### ISSUE THREAD

**Issue by khionu** [tauri-apps/tauri#138]
Opening this thread to start the discussion for a custom Async Executor for Tauri.

### Why Async?
For Tauri, async means being able to continue core operations while user operations are still pending. This is a large boon to responsiveness in programs that have heavier background tasks.

### Why not Tokio or AsyncStd?
Two main reasons: bloat and tailoring. Both runtimes are fairly liberal in how much they import, which is both heavy and a potential security issue. Additionally, we can fine-tune our executor to do only what we need, how we need it.

### What do we need to do to get started?
First a few questions:
**Q:** What common tasks (ie Networking, any `thread::spawn(||loop {...})`s) will Tauri want to use threads to drive?
**Q:** What needs to be adjusted, internally and externally, to allow user code to propagate into our executor? Where should the executor sit in our design?

Once these questions are answered, we can start designing the executor. It can be broken up into the following design segments:
1) Relationship between the executor and the rest of the Tauri framework.
2) Design of the reactors (one general purpose and a variable number of specialized ones) and how they get work.
3) How the executor schedules work for the reactors.

**Comment by lucasfernog** [comment]
Right now we use async operations here:
https://github.com/tauri-apps/tauri/blob/dev/tauri/src/lib.rs
https://github.com/tauri-apps/tauri/blob/ae51d9573e2c1b19e8e6216cb9d870cabdce8af0/tauri/src/app/runner.rs#L17

The main one we should update is the `lib.rs` because that's where every Rust API call goes.

**Comment by tensor-programming** [comment]
Id also recommend that you look again at event.rs.  Got a `thread_local!` call in there. It may be worth implementing `task_local!` if we are going to go with Tokio.

**Comment by khionu** [comment]
As I mentioned, a custom executor would be a more sound decision for us, despite the work involved. An executor, generally speaking, is a way to centralize background work, so it makes sense that we'd want to keep that tailored to what we need. Tokio, while convenient for a lot of use cases, is a bit on the bloated side.

The event dispatcher is a prime candidate to be turned into a custom reactor. It would essentially get the Futures from the user code on each iteration and push them to the Futures reactor (which we would probably have 2-4 of, and could be a user configuration) to be handled as futures.

The update command could be done as a Future, but eventually that will need to be more complex for fancy update processes. Regardless of the complexity, we will be able to put that on a general purpose reactor.

This will definitely be a bigger-picture change, and I would like to encourage we think of this as a long-term project. Axiom's refactor took me over 150 hours of work (guesstimating), and it still needs adjustments.

**Comment by tensor-programming** [comment]
I did consider using Actix at one point for the entire platform but it would require a major rewrite.  Just implementing futures and green threads in the event manager is a good idea and definitely work looking into.  It would make the library much more preformant and help with distributing the tasks.

**Comment by khionu** [comment]
As discussed on Discord, we'll **not** be using Tokio.

**Comment by tensor-programming** [comment]
We could use something like fibers rather then writing an entire executor given how little async work we do in the project.  Native threading is fine but green threads might be better for our event system.

**Comment by khionu** [comment]
An option: https://github.com/dwango/fibers-rs

**Comment by nothingismagick** [comment]
Nice @khionu. Would you consider looking at: 
> https://github.com/tauri-apps/tauri/blob/feature/iframe/tauri/src/event.rs

and making a proposal implementation with fibers and futures?

**Comment by himself65** [comment]
What's the current state of this issue?

**Comment by nothingismagick** [comment]
I'm not sure at the moment. We just moved to the new webview bindings, and Khionu has left the project. @lucasfernog - is this something we can address or should it be closed?

**Comment by lucasfernog** [comment]
well we have that lib that allows tauri commands to be async, and Tensor had some ideas about moving it to core.

**Comment by lucasfernog** [comment]
I'm closing this issue since we started working on async support here: #1169
We're going to start with Tokio for simplicity but more async runtimes will be implemented in the future.
