### ISSUE TITLE
JS API: Expose app name, version & few useful functions.

### ISSUE THREAD

**Issue by lemarier** [tauri-apps/tauri#1387]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
Add new JS API to send: APP `name` and `version` from the newly added package_info in the tauri context.

We could also expose in this API some useful functions like: `relaunch` and `quit`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lemarier** [comment]
This should be done once the updater is merged.

**Comment by gluax** [comment]
@lemarier, is there any way to track when these features are going to be released?

**Comment by lucasfernog** [comment]
This one was released already, see https://tauri.studio/en/docs/api/js/modules/app and https://tauri.studio/en/docs/api/js/modules/process

**Comment by gluax** [comment]
Ah, it was moved from where this commit showed it, couldn't find it through any searching haha my bad.
