### ISSUE TITLE
Is there any api for removing listener?

### ISSUE THREAD

**Issue by zsmatrix62** [tauri-apps/tauri#1390]
I'm using js api `event.listen` for function callbacks, and I just found that when I refresh my page (in tour window) the listener repeats, is there an api for removing an event listener in js?

Thanks.

![image](https://user-images.githubusercontent.com/2951879/112468644-7c540980-8da3-11eb-8d9d-bd127e97082c.png)

**Comment by lucasfernog** [comment]
This is implemented on the dev branch and will be available on the next release.
