### ISSUE TITLE
cargo check, cargo build extremely slow even on development profile

### ISSUE THREAD

**Issue by WilliamVenner** [tauri-apps/tauri#1394]
**Describe the bug**
Building for development profile is extremely slow, sometimes taking up to 5 minutes long.

**To Reproduce**
1. Add some assets into the configured dist folder
2. Run cargo check
3. Wait forever

**Expected behavior**
cargo check and cargo build (_without_ --release) should be fast and snappy to aid the development process.

**Screenshots**
![](https://cdn.discordapp.com/attachments/731495047962558564/825453010766921728/unknown.png)

`cargo rustc --profile=check -- -Zunstable-options --pretty=expanded`

![](https://cdn.discordapp.com/attachments/731495047962558564/825456686382186506/unknown.png)

**Platform and Versions (please complete the following information):**

OS: Windows 10 64-bit
Node: 14.15.0
NPM: 6.14.8
Yarn: 2.0.0-rc.27
Rustc: 1.15.0

[cargo-timing-20210327T191032Z.zip](https://github.com/tauri-apps/tauri/files/6216390/cargo-timing-20210327T191032Z.zip)

**Comment by WilliamVenner** [comment]
It's back @chippers ?

**Comment by chippers** [comment]
> 
> 
> It's back @chippers ?

I think it got reverted because we weren't able to serve files in dev. the refactor needed to fix it properly just landed this weekend so i can get a similar fix in the next day or so
