### ISSUE TITLE
Meta: GitHub Actions for PRs always fail due to Clippy error

### ISSUE THREAD

**Issue by WilliamVenner** [tauri-apps/tauri#1403]
Example: https://github.com/tauri-apps/tauri/pull/1370/checks?check_run_id=2221789066

References: https://github.com/actions-rs/clippy-check/issues/2

```
Error: Unable to create clippy annotations! Reason: HttpError: Resource not accessible by integration
Warning: It seems that this Action is executed from the forked repository.
Warning: GitHub Actions are not allowed to create Check annotations, when executed for a forked repos. See https://github.com/actions-rs/clippy-check/issues/2 for details.
```

Specifically, these workflows fail:

- [ ] workspace_clippy_fmt_check
- [ ] core_clippy_check (api-all)

**Comment by nothingismagick** [comment]
You know, this is sort of out of our control. Closing because it should probably be filed at Clippy.
