### ISSUE TITLE
Allow passing arguments to application when running `yarn tauri dev`

### ISSUE THREAD

**Issue by yamgent** [tauri-apps/tauri#1406]
**Is your feature request related to a problem? Please describe.**
[Tauri supports CLI](https://tauri.studio/en/docs/usage/recipes/cli), but we don't have a way to pass any arguments to the CLI when using `yarn tauri dev`. 

**Describe the solution you'd like**
Support some way of passing in arguments, something like `yarn tauri dev <arg1> <arg2> ...`

**Describe alternatives you've considered**
Tried using the solution I mentioned above (`yarn tauri dev <arg1> <arg2> ...`) and it didn't work. I also tried just using `cargo run <arg1> <arg2>...`, which will pass in the arguments, but this is not workable because we need the wrapper provided by `yarn tauri dev`. So there's not really a feasible workaround for this.

**Additional context**
None

**Comment by lucasfernog** [comment]
I'll implement this, it'll be `yarn tauri dev -- <arg1> <arg2> ...`.

**Comment by Umenokin** [comment]
Hi folks,
I am still unable to make it work.

```
  "tauri": {
    "allowlist": {
      "all": true
    },
    "cli": {
      "description": "Test descript",
      "beforeHelp": "### BEFORE ###",
      "afterHelp": "### AFTER ###",
      "args": [{
        "name": "project",
        "short": "P",
        "takesValue": true,
        "multiple": false
      }]
    },
```

npm run tauri dev -- -- --project=test:
```
error: Found argument '--project' which wasn't expected, or isn't valid in this context
```

npm run tauri dev -- --project=test 
```
error: Found argument '--project' which wasn't expected, or isn't valid in this context
```
cargo tauri dev --project=test
```
error: Found argument '--project' which wasn't expected, or isn't valid in this context
```
cargo tauri dev -- --project=test
```
error: Found argument '--project' which wasn't expected, or isn't valid in this context
```

And `cargo tauri dev -- -- --project=test` opens some built-in `Welcome to Tauri!!!` without running my JavaScript.

**Comment by amrbashir** [comment]
I think `npm run` requires one moer `--` try `npm run tauri dev -- -- -- --project=test`

**Comment by Umenokin** [comment]
Already did. Same as `cargo tauri dev -- -- --project=test` which would produce: 😅
```
 opens some built-in Welcome to Tauri!!! without running my JavaScript.
```
Though, I do think you right, npm requires one additional `--` anyway

**Comment by amrbashir** [comment]
The first `--` allows you to pass to arguments to the runner (which is Cargo) and the second `--` allows you to pass args to your app so

```sh
cargo tauri dev -- --cargo-arg1 --cargo-arg2 -- --app-arg1 --app-arg2
```
npm:
```sh
npm run tauri dev -- -- --cargo-arg1 --cargo-arg2 -- --app-arg1 --app-arg2
```

**Comment by FabianLars** [comment]
> opens some built-in Welcome to Tauri!!! without running my JavaScript.

Completely unrelated to the args tho. `Welcome to Tauri` is part of the templates and your javascript not loading shouldn't be caused by the args (unless you only inject it if args are provided) - either way not related to this issue so please create a new one (or a discussion because this doesn't look like a Tauri bug) or join our discord where triaging is much easier for us :)

**Comment by justintaylor-dev** [comment]
Also still unable to get this to work in `tauri dev`, any updates here?

**Comment by FabianLars** [comment]
@justintaylor-dev We're not aware of any problems i think. Can you share examples of what exactly you're having problems with (example commands and how you try to read the args)

Edit: just saw your discord discussion

**Comment by justintaylor-dev** [comment]
@FabianLars triple separators ended up working for me, thanks:

e.g.

```
yarn tauri dev -- -- -- --custom
```

**Comment by rkuzlik** [comment]
@FabianLars
I tried using the args also in the build command, but it does not work for me.
`npm run tauri dev -- -- -- --mode x` - works fine (I got the value as expected without any error)
`npm run tauri build -- -- -- --mode x` - failed
`error: Found argument '--mode' which wasn't expected, or isn't valid in this context`

any idea what could be the difference?

**Comment by FabianLars** [comment]
That can't work because there is no application to forward the arguments to. Like in `tauri dev` tauri will forward the `--mode x` to the tauri app that's being opened, but in the build command the app won't be executed so tauri doesn't forward the arguments.

**Comment by rkuzlik** [comment]
We need to build the Tauri app twice in 2 modes, for each mode we need another implementation in the angular application.
(according to the provided mode we open another initialize route in the Angular app)
how can we implement it without arguments?

**Comment by FabianLars** [comment]
I'm a bit confused here to be honest. I guess this depends on how exactly you implemented the modes.

If it is some kind of build time flag like `ng build --configuration abc` for example then i _think_ you have to change the `beforeBuildCommand` (or don't use beforeBuildCommand at all and split it up into 2 steps 1) the frontend 2) the tauri app ). You can change the command by supplying a merge config with the `-c` / `--config` flag.

If the flag must be supplied when _running_ the app (on the user's system) then it again, depends on the implementation i guess? Generally i don't think this can work in the way you're trying to do it here.

Can you give some kind of example on what you have and what you're actually trying to do?

**Comment by rkuzlik** [comment]
Thanks for your quick reply, using a different configuration for these 2 different modes seems to be more suitable for our needs.
