### ISSUE TITLE
`#[tauri::command]` produces "dead code"

### ISSUE THREAD

**Issue by WilliamVenner** [tauri-apps/tauri#1418]
## Describe the bug
The compiler thinks that `#[tauri::command]` functions are dead code.

## To Reproduce

```rust
#[tauri::command]
fn anything() -> &'static str {
    "Test"
}
```

## Expected behavior
The compiler shouldn't report dead code for `[#tauri::command]`, as they will be called by the invoke handler when generated.

## Screenshots
![image](https://user-images.githubusercontent.com/14863743/113193761-4063ed00-9258-11eb-84d9-6cfb9ae866c2.png)
![image](https://user-images.githubusercontent.com/14863743/113193782-4528a100-9258-11eb-8586-dcb17b737536.png)

## Platform and Versions

OS: Windows 10 64-bit
Node: 14.15.0
NPM: 6.14.8
Yarn: 2.0.0-rc.27
Rustc: 1.15.0

**Comment by lucasfernog** [comment]
It is indeed dead code if you don't use the APIs with the tauri::generate_handler macro. So if you're not using that, you need to allow dead code on your end.

**Comment by WilliamVenner** [comment]
Damn I had a feeling I was overlooking something. Sorry 😄

**Comment by nklayman** [comment]
See the command guide for more details on the new command macros: https://github.com/tauri-apps/tauri-docs/blob/feat/beta-rc-update/docs/en/usage/howtos/command.md
