### ISSUE TITLE
Deep Link Action Handler

### ISSUE THREAD

**Issue by enijar** [tauri-apps/tauri#1421]
**Feature Description**
I'm unsure if the correct term is "deep link", but I've seen this on several website to desktop app links, where (for example) you click on a website link and that link opens the corresponding desktop app (if installed) and performs an action. An example of this is Discord invite links.

Here is a contrived example of a "deep link":

```text
appname://action/path?arg1=val1&arg2=val2
```

This would be linked to from a website, with a normal anchor tag:

```html
<a href="appname://action/path?arg1=val1&arg2=val2">Open appname</a>
```

I think this would be a nice featuer for Tauri to support, allowing developers to link to their desktop app and handle incomming actions.

**Comment by nothingismagick** [comment]
There is a VERY old issue about this, that we definitely want to resolve as soon as the beta-rc lands.
https://github.com/tauri-apps/tauri/issues/323

That said, there are very serious concerns about security of deeplinks, so I think that this should probably be a tauri plugin.

**Comment by enijar** [comment]
Thanks for linking for the issue. I did a search for issues with "deep link", didn't know it was called "URI scheme" 👍

**Comment by enijar** [comment]
Appologies for the ignorant question, but what exactly are the security concerns with URI schemes?

**Comment by nothingismagick** [comment]
Technically any application can register such an URI scheme with your host operating system. Furthermore, I consider this to be a type of "push message" that your application MUST parse even thought it has no way of authenticating the sender, since these deeplinks are generally (always?) intercepted by the browser.
