### ISSUE TITLE
Add custom files to deb packages

### ISSUE THREAD

**Issue by lights0123** [tauri-apps/tauri#1428]
**Is your feature request related to a problem? Please describe.**

I'd like to ship udev rules with my app. However, Tauri creates the .deb bundle before I can include them.

**Describe the solution you'd like**

An option to specify files that should be included in the final .deb bundle, similar to `externalBin`. However, they need to be able to be stored at any location. Also, there should be an option to include both architecture-specific and -generic files, as in my case, udev rules are the same on e.g. x86 and ARM.

**Describe alternatives you've considered**

Including as an `externalBin`, but that doesn't allow me to put files wherever I want on the filesystem.

**Additional context**

These files should probably not be included in the AppImage build.

**Comment by lucasfernog** [comment]
Let me know if I missed anything.
