### ISSUE TITLE
Archive deprecated crates/packages/repositories

### ISSUE THREAD

**Issue by lucasfernog** [tauri-apps/tauri#1456]
## NPM packages:
- [x] https://www.npmjs.com/package/@tauri-apps/tauri-inliner
- [x] https://www.npmjs.com/package/tauri

## Crates:
- [x] https://crates.io/crates/tauri-inliner
- [x] https://crates.io/crates/tauri_includedir
- [x] https://crates.io/crates/tauri_includedir_codegen
- [x] https://crates.io/crates/tauri-api
- [x] https://crates.io/crates/tauri-updater
- [x] https://crates.io/crates/tauri-dialog
- [x] https://crates.io/crates/tauri-dialog-sys

## Repositories:
- [x] https://github.com/tauri-apps/tauri-dialog-rs
- [x] https://github.com/tauri-apps/tauri-inliner-rs
- [x] https://github.com/tauri-apps/tauri-inliner
- [x] https://github.com/tauri-apps/tauri-includedir
- [x] https://github.com/tauri-apps/zserge-webview
- [x] https://github.com/tauri-apps/deno

**Comment by nothingismagick** [comment]
I archived all the repos listed above, not totally sure what we should do about the crates though. I could yank - but who knows if someone out there finds them useful... Thoughts?

**Comment by chippers** [comment]
> 
> 
> I archived all the repos listed above, not totally sure what we should do about the crates though. I could yank - but who knows if someone out there finds them useful... Thoughts?

Add in documentation to the readme and crate root docs that it is deprecated and point to the new way of doings things. Upload as a new patch version

**Comment by lucasfernog** [comment]
Finally done!
