### ISSUE TITLE
Can not build app

### ISSUE THREAD

**Issue by birdinforest** [tauri-apps/tauri#1458]
**Describe the bug**

Build app by command ` yarn tauri build` or by ` yarn tauri build --debug`, get error says file `.cargo-lock` is locked by another process. However I don't find any process is accessing to that file.

**`yarn tauri dev` works well. The built debug `.exe` file works as well.**

**To Reproduce**
1. Generate new tauri project following official instruction.
2. Build app by  ` yarn tauri build` or by ` yarn tauri build --debug`
3. See error as following

```
PS F:\forrrest-digital-garden-tiddlywiki> tauri build --verbose
[tauri]: running build
 app:spawn Running "cargo tauri-bundler --features embedded-server --release --verbose" +0ms

   Compiling tauri v0.11.1
   Compiling tiddlywiki-desktop-rs v0.1.0 (F:\forrrest-digital-garden-tiddlywiki\src-tauri)
error: couldn't read F:/forrrest-digital-garden-tiddlywiki/src-tauri/target/release/.cargo-lock: The process cannot access the file because another process has locked a portion of the file. (os error 33)
     --> F:\forrrest-digital-garden-tiddlywiki\src-tauri\target\release\build\tauri-5327b7eb78ed3479\out/data.rs:15185:128
      |
15185 | ...::Compression::None, include_bytes!("F:/forrrest-digital-garden-tiddlywiki/src-tauri/target/release/.cargo-lock") as &'static [u8])),
      |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |
      = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

error: could not compile `tauri`

To learn more, run the command again with --verbose.
error: `Result of `cargo build` operation was unsuccessful: exit code: 101`

 app:spawn Command "cargo" failed with exit code: 1 +0ms

 app:tauri (runner) ⚠️  [FAIL] Cargo CLI has failed +0ms

 app:tauri Shutting down tauri process... +1ms
```

**Expected behavior**
Build success.

**Platform and Versions (please complete the following information):**
Operating System - Windows_NT(10.0.19042) - win32/x64
Microsoft Edge - 44.19041.423.0_neutral__8wekyb3d8bbwe

Node.js environment
  Node.js - 15.14.0 ( Get the same error on 14.16.1)
  tauri.js - 0.14.1

Rust environment
  rustc - 1.51.0
  cargo - 1.51.0
  tauri-bundler - 0.9.4

Global packages
  NPM - 7.7.6
  yarn - 1.22.10

App directory structure
/.git
/.idea
/node_modules
/src-tauri
/tiddlers

App
  tauri.rs - 0.11.1
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../
  devPath - ../

**Additional context**
I tried to reinstall rust, yarn, and tauri. No luck.
Today I will try to re-install MSBuild and C++ tools. Will update later.

A closed issue https://github.com/tauri-apps/tauri/issues/932 encounters the same error.

**Comment by nothingismagick** [comment]
Since you are running the Alpha version, I am going to close this issue - the Beta.rc is literally in the process of being published and we will not support Alpha.

Please see:
https://github.com/tauri-apps/tauri/issues/1253
