### ISSUE TITLE
macOS window issues

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tauri#1464]
There are a few things that make Tauri windows a little weird on macOS:
1. The position of the window is not in the center by default, and it's not remembered. Every time Tauri starts, the window shows up in the bottom left corner
2. No window title
3. No border around the windows (especially noticeable in dark mode)
4. There's no drop shadow behind the windows, but this should be fixed already (https://github.com/tauri-apps/tauri/issues/1033)

**Comment by nothingismagick** [comment]
Are you using the dev branch? If so, please reopen this issue.

**Comment by probablykasper** [comment]
Assumed these still existed because I couldn't find any issues mentioning them, but looks like they are fixed 👌
