### ISSUE TITLE
CPU at 100% usage in `embeddedServer: false` mode

### ISSUE THREAD

**Issue by m-lima** [tauri-apps/tauri#1465]
**Describe the bug**
When using `embeddedServer: false` launching mode, if an image is not found, the cpu peaks and holds at 100%.

**To Reproduce**
1 - Setup the project
```bash
$ npx create-react-app my-test --template typescript  # Create a blank hello-world react app
$ cd my-test  # Enter the newly created project
$ npm i tauri --save  # Install tauri locally
$ vi package.json  # Edit package.json to add "tauri" as a script
$ npm run tauri init  # Init tauri. Make sure to point "distDir" to "../build" and "devPath" to "http://localhost:3000"
```
2 - Enable **no-server mode**
```bash
$ vi src-tauri/tauri.conf.json  # Edit "tauri.embeddedServer.active" to "false"
```
3 - Build the project in release mode
```bash
$ npm run build  # Build the HTML/JS/CSS
$ npm run tauri build  # Bundle it with tauri
```
4 - Execute the app
```bash
$ ./src-tauri/target/release/my-test  # For macOS, one can also open the .app bundle
```
5 - Observe that image is not loaded.
6 - Observe CPU pinned to the max.

**Expected behavior**
Ideally, the image should be rendered. But if not found, it is expected that the CPU doesn't get pinned at 100%.

Running with `embeddedServer: true`:
<img width="800" alt="Screen Shot 2021-04-12 at 19 19 05" src="https://user-images.githubusercontent.com/13945557/114436962-3fbb4700-9bc6-11eb-9ae7-8a2abea89798.png">
<img width="952" alt="Screen Shot 2021-04-12 at 19 35 20" src="https://user-images.githubusercontent.com/13945557/114436998-4b0e7280-9bc6-11eb-9f26-d35b743f4b74.png">

**Observed behavior**
Running with `embeddedServer: false`:
<img width="800" alt="Screen Shot 2021-04-12 at 19 21 07" src="https://user-images.githubusercontent.com/13945557/114437054-5a8dbb80-9bc6-11eb-982a-2393c74e2595.png">
<img width="952" alt="Screen Shot 2021-04-12 at 19 22 25" src="https://user-images.githubusercontent.com/13945557/114437070-5eb9d900-9bc6-11eb-96fc-193061925812.png">

**Platform and Versions (please complete the following information):**
```
Operating System - Darwin(19.6.0) - darwin/x64

Node.js environment
  Node.js - 15.11.0
  tauri.js - 0.14.1

Rust environment
  rustc - 1.49.0
  cargo - 1.49.0
  tauri-bundler - 0.9.4

Global packages
  NPM - 7.6.0
  yarn - Not installed

App directory structure
/.git
/build
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 0.11.1
  mode - no-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../build
  devPath - http://localhost:3000
```

**Comment by nothingismagick** [comment]
Thanks for the report, but the beta version does not use this logic or even this webview integration. If you have the same problems after refactoring to use the beta version, please reopen.

**Comment by m-lima** [comment]
> Thanks for the report, but the beta version does not use this logic or even this webview integration. If you have the same problems after refactoring to use the beta version, please reopen.

I apologize for the noise. I read the request to hold back on issues and was going to close this issue myself. I was setting up my project to use the `dev` branch to confirm if it is present there. But you have answered already.
Thanks
