### ISSUE TITLE
Hot Reloading not working in Mac OS. Always loading from cache...

### ISSUE THREAD

**Issue by Shanery** [tauri-apps/tauri#1480]
**Describe the bug**
Hot Reloading isn't working on Mac OS... This one might not be a plugin issue but any help would be appreciated.

So in the dev tools, as far as I can tell it's running safari, but my app.js and vendors.js are always using a cached version even when I have ignore cache, or hard refresh (option + command + r). It works correctly in safari so I'm not sure what the differences are... (hot-reloading doesn't work either)

**To Reproduce**

**Expected behavior**
Hot Reloading to Work

**Screenshots**
<img width="656" alt="image" src="https://user-images.githubusercontent.com/15805777/114726417-bb60f380-9d80-11eb-9507-07a36004ad71.png">

**Environment (please complete the following information):**
 - vue-cli-plugin-tauri version : 
 - other vue plugins used: 
 - (if possible) link to your repo: 
 - output from `npx tauri info`/`yarn tauri info`:
 
 "vue-cli-plugin-tauri": "~0.14.0"
 
Jest plugin
 
 ```
 Operating System - Darwin(19.6.0) - darwin/x64

Node.js environment
  Node.js - 12.16.1
  tauri.js - 0.14.1

Rust environment
  rustc - 1.51.0
  cargo - 1.51.0
  tauri-bundler - 0.9.4

Global packages
  NPM - 6.13.4
  yarn - 1.22.4

App directory structure
/.git
/dist
/node_modules
/public
/src
/src-tauri
/tests

App
  tauri.rs - 0.11.1
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist/spa
  devPath - http://localhost:8081
```

**Additional context**

**Comment by lemarier** [comment]
A new version will be released in the next hours and it should be fixed.

If it still happening, please reopen the issue with the new version details.

Thanks!
