### ISSUE TITLE
[Win] Modifiers keys make init script crash

### ISSUE THREAD

**Issue by Shotman** [tauri-apps/tauri#1492]
**Describe the bug**
On windows when using the command tauri init from the @tauri-apps/cli package if any of those keys, left or right, CTRL , ALT, AltGr, SHIFT and Caps Lock are pressed it makes the script crash

**To Reproduce**
In a new folder
1. yarn init
2. yarn add @tauri-apps/cli
3. At any prompt, press any of the key, the script will crash

**Expected behavior**
The script should take the input

**Platform and Versions (please complete the following information):**

OS: Windows 10
Node: 15.12.0
NPM: 7.9
Yarn: 1.22.5
Rustc: 1.51.0

It seems to be related to the crates dialoguer & console

**Comment by parker-codes** [comment]
I ran into this as well. Can't add a capitalized window title without shift! 😁

**Comment by Kethku** [comment]
I also encountered this on windows with powershell. However the problem didn't happen with cmd.

**Comment by lucasfernog** [comment]
This was supposed to be fixed by https://github.com/mitsuhiko/dialoguer/issues/110 :/

**Comment by amrbashir** [comment]
dialoguer depends on console and the actual fix https://github.com/mitsuhiko/console/pull/96 just got merged 12 days ago, so we still need console to publish a new release and use it as dependency patch.

**Comment by xxnuo** [comment]
Still happen on Windows Terminal after I press Caps lock button
![图片](https://user-images.githubusercontent.com/54252779/211188590-466ea67f-437c-4fe7-976a-f7a3fe281057.png)
