### ISSUE TITLE
make API a generic TS lib for both node and deno to consume

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#151]
**Is your feature request related to a problem? Please describe.**
We plan on making a DENO CLI, and to that end (and to reduce code repetition) we would like to turn the current node.js API into a standalone library for consumption in either NODE or DENO. 

**Describe alternatives you've considered**
- an API lib for each context - but that makes things more complex
- a complete DENO solution, which also makes things tricky

**Additional context**
@nklayman offered to work on the TS transition, and @rsp offered to help if possible.

**Comment by nothingismagick** [comment]
To be clear, I am talking about this folder:
https://github.com/tauri-apps/tauri/tree/dev/cli/tauri.js/api

I am pretty sure we will NOT be able to easily modify the tauricon.js for DENO, but would love to stand corrected.

**Comment by nklayman** [comment]
I'm going to wait till the iframe branch gets merged back in, but once it does I'll start on it.

**Comment by nothingismagick** [comment]
Just leaving a comment here: I don't know if we are tracking it, but we should polyfill web api where possible: see this

https://github.com/Boscop/web-view/issues/29
