### ISSUE TITLE
"Error: Not a terminal" when attempting to type capital letters in the CLI

### ISSUE THREAD

**Issue by alterae** [tauri-apps/tauri#1516]
**Describe the bug**
When using `tauri init`, attempting to type any letter while the shift key is held causes the CLI to fail with exit code 1 and the error "Not a terminal"

**To Reproduce**
1. Open a new directory and set up a node project following the steps in the [tutorial](https://tauri.studio/en/docs/usage/development/integration) in the docs, up to the point where you must run `tauri init`.
2. Run the CLI with `npm run tauri init`.
3. Hold the shift key, and then attempt to type anything (IE a capital letter, a colon, an underscore).

**Expected behavior**
The CLI allows me to type capital letters and other characters that require the shift key, and does not crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/27498421/115038296-a1143c00-9e8c-11eb-970a-400a9375eb1c.png)
Shown here in Git Bash, using Hyper as the terminal emulator.  The same error also occurs in Git Bash using Terminus, Powershell using Terminus, and Powershell using the default Powershell window (interestingly enough, in Powershell you do not actually have to *hold* the shift key or type anything to crash the CLI.  Simply pressing the shift key seems to be enough).

The `H` on the last line is the letter I was typing which crashed it.

**Platform and Versions (please complete the following information):**

OS: `Windows, version 10.0.19042 X64`
Node: `v14.16.0`
NPM: `.14.11`
Yarn: *(not installed)*
Rustc: `rustc 1.51.0 (2fd73fabe 2021-03-23)`

**Additional context**
As said under the screenshot, the behavior is slightly different in Powershell.  Rather than crashing when shift *and* another key are pressed, simply pressing the shift key will crash the CLI.

**Stack Trace**

**Comment by amrbashir** [comment]
It is already reported and tracked at #1492
