### ISSUE TITLE
lazy loaded images don't load

### ISSUE THREAD

**Issue by jbolda** [tauri-apps/tauri#152]
**Describe the bug**
Images loaded lazily do not load in Tauri. For example, the Gatsby-image component will lazy load images, and below the fold images do not load.

**To Reproduce**
Can be seen in the gatsby based smoke test. Download the artifacts and click around.

**Expected behavior**
Images load.

**Platform (please complete the following information):**
OS: all
Node: all

**Comment by nothingismagick** [comment]
Can you link to the docs page about the gatsby image component?

**Comment by nothingismagick** [comment]
We should also verify that the loading of assets from ~assets in quasar is not similarly broken.

**Comment by jbolda** [comment]
Docs can be found here: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-image

**Comment by nothingismagick** [comment]
Can you try this:
> Images marked as `critical` will start loading immediately as the DOM is parsed, but unless fadeIn is set to false, the transition from placeholder to final image will not occur until after the component is mounted.

This might also be an issue:
> Lazy loading behavior is dependent on IntersectionObserver which is not available in IE. A polyfill is recommended.

**Comment by nothingismagick** [comment]
Here are two other options:

Name | Type | Description
-- | -- | --
loading | string | Set the browser's native lazy loading attribute. One of lazy, eager or auto. Defaults to lazy.
critical | bool | Opt-out of lazy-loading behavior. Defaults to false. Deprecated, use loading instead.

**Comment by nothingismagick** [comment]
This should actually be resolved with latest dev branch.

**Comment by lucasfernog** [comment]
> This should actually be resolved with latest dev branch.

However, you may have to adjust your webpack's publicPath.

**Comment by nothingismagick** [comment]
We need some proper wording for the docs.

**Comment by lucasfernog** [comment]
@nothingismagick and I discussed some CSP changes that still needs to be done before this issue can be closed.

**Comment by nothingismagick** [comment]
We took care of this, didn't we?

**Comment by nklayman** [comment]
Yes, I haven't had any issues lately.

**Comment by nothingismagick** [comment]
Cool, was just double checking that our CSP fix did the trick.

**Comment by nklayman** [comment]
My bad, it still fails on build, tested with a fresh gridsome project. Fails with `embeddedServer` enabled or disabled.
![image](https://user-images.githubusercontent.com/12448243/71785390-bde87100-2fb3-11ea-9b29-7b9d0540669e.png)

**Comment by lucasfernog** [comment]
It's working with the embeddedServer enabled. It doesn't work with the no-server mode because of Gridsome's publicPath, which we can't change (they block it). It must be addressed by tauri-inliner.

![2020-01-10_946x431_screenshot](https://user-images.githubusercontent.com/20051258/72188030-12d31f80-33d8-11ea-9229-5bdda7ca6d26.png)
