### ISSUE TITLE
Re-export `tauri::runtime::manager::Args`

### ISSUE THREAD

**Issue by WilliamVenner** [tauri-apps/tauri#1524]
**Is your feature request related to a problem? Please describe.**
I cannot store a static reference to anything Tauri-related because the generic type bounds are private.

**Describe the solution you'd like**
Re-export `tauri::runtime::manager::Args`

**Describe alternatives you've considered**
Re-exporting it myself

**Additional context**
```rust
lazy_static! {
    pub static ref WEBVIEW: WrappedWebview<Args<String, String, tauri::api::assets::EmbeddedAssets, tauri::runtime::flavors::wry::Wry>> = WrappedWebview::pending();
}
```

**Comment by lucasfernog** [comment]
The public counterpart of `Args` is `Params`. With the upcoming beta-rc.5, you'll be able to store `window` instances using the `manage` API, see [calling manage to store a state type](https://github.com/tauri-apps/tauri/blob/935db26c0193211df1948f8ee01a996fede96328/examples/splashscreen/src-tauri/src/main.rs#L72) and [reading a state on a command handler](https://github.com/tauri-apps/tauri/blob/935db26c0193211df1948f8ee01a996fede96328/examples/splashscreen/src-tauri/src/main.rs#L57).

Please let me know if there's something missing for your use case.
