### ISSUE TITLE
SVG -> PNG Icon Generator

### ISSUE THREAD

**Issue by WilliamVenner** [tauri-apps/tauri#1525]
**Is your feature request related to a problem? Please describe.**
The current icon generator isn't great because it takes PNG as an input and naively scales them, usually resulting in some very sharp/low quality icons.

**Describe the solution you'd like**
An icon generator that renders & scales SVGs into the correctly sized PNG files.

**Describe alternatives you've considered**
Just generating them myself!

**Comment by nothingismagick** [comment]
I have fixed the quality issue, it was because of a misplaced desire to make apps smaller than 500KB. Now quality should be a lot better. SVG source is error prone, and not something we are likely to do in the next 6 months.

**Comment by RubenKelevra** [comment]
Actually fixed, as the icon generator is accepting SVG now :)

**Comment by ekwoka** [comment]
Is this no longer a thing?

**Comment by FabianLars** [comment]
@ekwoka Nope, it was removed when the cli was rewritten in Rust to get it up and running quicker, without adding new (huge) dependencies. The plan is to implement it again at some point.
