### ISSUE TITLE
Cursor not changing

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tauri#1526]
**Describe the bug**
For macOS, if I have an element that should show a different type of cursor, like a `<textarea>` or an element with `cursor: pointer`, the cursor just stays as the default macOS cursor.

Opening or closing devtools can cause the bug to go away, but then it comes back when you open the context menu, or switch to a different app.

**To Reproduce**
1. Install `tauri-cli`: `cargo install tauri-cli --version 1.0.0-beta-rc.1`
2. Run `cd src-tauri && cargo-tauri tauri dev` in a tauri app that has a `<textarea>` field or something equivalent

**Expected behavior**
For instance hovering over a `<textarea>` should switch to the text cursor.

**Screenshots**
https://user-images.githubusercontent.com/11315492/115131464-9e365a00-9ff8-11eb-82d7-8b508b41266a.mp4

**Platform and Versions (please complete the following information):**
OS: macOS 10.14.6
Node: 14.16.0
NPM: 6.14.11
Rustc: 1.50.0 (cb75ad5db 2021-02-10)

**Comment by lemarier** [comment]
Related to https://github.com/tauri-apps/wry/issues/175

**Comment by lemarier** [comment]
Fixed in https://github.com/tauri-apps/wry/pull/220

If you still have this problem with the next release, please open a new issue.

Thanks again for reporting!
