### ISSUE TITLE
Navigation between pages not working in Tauri-generated apps for PC and MAC

### ISSUE THREAD

**Issue by EkaterinaGorbunova** [tauri-apps/tauri#1527]
He everyone! 

**Issue:** navigation between pages not working in Tauri-generated apps for PC and MAC.

I am building an app using create-r3f-app and next.js with tailwind css. App does not have any 3D components yet. App has multiple pages and uses AWS backend services (like Cognito User Pool, DynamoDB, S3 etc).
When I run Tauri in dev environment - app works fine - I'm able to log in using AWS Cognito (all pages are protected by Aunthenticator), can jump between pages of the app, all contents are displayed properly.

**On PC:**
Whenever I generate Tauri bundle (yarn tauri build) - I'm able to log in using AWS Cognito, index.js page is displayed properly but navigation between pages doesn't work and i'm getting the following error:

![image](https://user-images.githubusercontent.com/61888654/115132071-ef2f5980-9fca-11eb-85b1-6ea31d7cf5bb.png)

![image](https://user-images.githubusercontent.com/61888654/115132096-0f5f1880-9fcb-11eb-932a-95a0e055cc4e.png)

If I right-click on "not found file/page" and hit ''Back'',  I go back to index.js page.

**On MAC:**
Everything works fine in the dev environment but when i try to run tauri-generated app (yarn tauri build) - navigation between pages doesn't work and there are no errors in the console. When debugging with 'cargo run tauri --verbose' - i'm getting the following error when trying to jump to another page:

```
Users-MacBook-Air:src-tauri user1$ cargo run tauri --verbose
   Compiling tauri v1.0.0-beta-rc.0
   Compiling app v0.1.0 (/Users/user1/company/workspace/launcher/src-tauri)
   Compiling tauri-macros v1.0.0-beta-rc.0
    Finished dev [unoptimized + debuginfo] target(s) in 24.98s
     Running target/debug/app tauri --verbose
AssetNotFound("PageName1")
AssetNotFound("PageName2")
AssetNotFound("PageName3")
AssetNotFound("PageName4")
Users-MacBook-Air:src-tauri user1$
```

**Expected behavior:**
Be able to jump between pages within Tauri app. Each .js page should display it's content

OS: Windows_NT(10.0.19042) - win32/x64
Node: 14.16.1
NPM: 7.10.0
Yarn: 1.22.10
Rustc: 1.51.0 (2fd73fabe 2021-03-23)

OS:  Mac Chip Apple M1
Node: 14.16.1
NPM: 7.10.0
Yarn: 1.22.10
Rustc: 1.51.0 (2fd73fabe 2021-03-23)

**Comment by mq1** [comment]
same affecting my app (ViteJS, VueJS, vue-router, vite-ssg)

**Comment by nothingismagick** [comment]
Are you using "history" or "hash" mode?

**Comment by mq1** [comment]
> 
> 
> Are you using "history" or "hash" mode?

I think hash, as it seems to be the default. If it helps I'm using https://github.com/antfu/vite-ssg, https://github.com/hannoeru/vite-plugin-pages and https://github.com/JohnCampionJr/vite-plugin-vue-layouts to manage the routes.

**Comment by mq1** [comment]
Ok, the default was History, hash mode doesn't have this problem

**Comment by nothingismagick** [comment]
FYI we are tracking this at wry:
https://github.com/tauri-apps/wry/issues/170#issuecomment-822904272

**Comment by lemarier** [comment]
Part of the bug should be resolved in [WRY](https://github.com/tauri-apps/wry/pull/173), now I need to check what's going on with `AWS Cognito` & `nextjs`

I'll invest and keep the thread updated.

**Comment by lemarier** [comment]
Fixed in https://github.com/tauri-apps/wry/pull/173

If you still have this problem with the next release, please open a new issue.

Thanks again for reporting!

**Comment by EkaterinaGorbunova** [comment]
Hi everyone, i checked it out. 
Multi-page links work great in Tauri v.1.0.0-beta.0
Thanks a lot!
