### ISSUE TITLE
API Example Revision

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#1535]
There's a few of things here that aren't really working and we need to iron out before we release the beta and put this example up on the docs site:

- generally: I think that the console display should have newest result at the top instead of the end.
- I get linker errors on a macOS M1, so need to comment out the .cargo/config setting to get it to even build
- CLI example makes no sense / needs information
- new Window panics
- http example should be populated with something
- shell example dies too soon
- should be resizeable / transparent 
- would like to have the sidebar links have the proper mouse pointer (the one that looks like a hand) on hover
- updater should never allow versions older than the "minted timestamp" of the current version to be installed
```
{"body":"This is the latest version! Once updated you shouldn't see this prompt."
,"date":"2020-06-25T14:14:19Z","version":"2.0.0"}
```

**Comment by nothingismagick** [comment]
Also, I am a bit confused about what this context-click means on macOS:
<img width="172" alt="image" src="https://user-images.githubusercontent.com/35242872/115221455-fb6e0080-a109-11eb-8791-fd2c1797770d.png">

**Comment by lemarier** [comment]
Following on `updater should never allow versions older than the "minted timestamp" of the current version to be installed`

Actually, the update server should determine whether an update is required based on the [update request](https://tauri.studio/en/docs/usage/howtos/updater#update-requests). This allows rollback or fine-grained updating sequence if required. (By example rollback to v1 only for win64) -- this append sometimes that you ship a bad update and you should be able to roll back till you burn a fix.

If you run version `1.2.3` and you check for a new update, and the last version is `1.2.3`, the server SHOULD announce `204` (no-content) -- [more details](https://tauri.studio/en/docs/usage/howtos/updater#server-support)

For the `minted timestamp` this is something we can implement but will remove rollback functionalities. 

Thanks!

Edit: Maybe we could implement it for [static JSON](https://tauri.studio/en/docs/usage/howtos/updater/#update-file-json-format) but will remove rollback so not ideal...

Edit 2: What we could do is add an optional `timestamp` field on the static and server support, and if provided, we make sure that the current binary timestamp is older than the announced timestamp. This makes the security check optional, so if you need rollback you can disable the timestamp check then announce the rollback.

**Comment by nothingismagick** [comment]
> Edit 2: What we could do is add an optional timestamp field on the static and server support, and if provided, we make sure that the current binary timestamp is older than the announced timestamp. This makes the security check optional, so if you need rollback you can disable the timestamp check then announce the rollback.

thats a great idea

**Comment by lucasfernog** [comment]
The API example also need to showcase the file dropping and window dragging functionality from WRY.
