### ISSUE TITLE
[Tauri beta rc.2] Cannot build a Svelte app with the Tauri API

### ISSUE THREAD

**Issue by Pierstoval** [tauri-apps/tauri#1546]
⚠ First, I am not sure whether this is a specific `svelte-kit build` issue or if the `@tauri-apps/api/index.js` file could fix this issue by changing the build process, so if this _actually_ comes from the Svelte lib, please tell me so I can create an issue on their side 😉 (The issue contains a very ugly hacky workaround that isn't suitable but may help the Tauri team know where to start to fix this issue)

**Describe the bug**
When running `yarn build`, I have an error coming from the built Tauri API

<details>
<summary>⬇Click to display terminal output and stack trace</summary>

```
$ yarn build
yarn run v1.22.10
  svelte-kit build
vite v2.2.1 building for production...
transforming (44) src/routes/$layout.svelte[vite-plugin-svelte] The following packages did not export their `package.json` file so we could not check the "svelte" field.If you had difficulties importing svelte components from a package, then please contact the author and ask them to export the package.json file.
- @tauri-apps/api
✓ 45 modules transformed.
[vite:esbuild-transpile] Transform failed with 1 error:
pages/index.svelte-750725d8.js:92:9: error: Expected identifier but found "("

Expected identifier but found "("
90 |  }
91 |
92 |  function (t) {
   |           ^
93 |      var r = function (t) {
94 |          var r, e = Object.prototype, n = e.hasOwnProperty, o = "function" == typeof Symbol ? Symbol : {},

> Transform failed with 1 error:
pages/index.svelte-750725d8.js:92:9: error: Expected identifier but found "("
Error: Transform failed with 1 error:
pages/index.svelte-750725d8.js:92:9: error: Expected identifier but found "("
    at failureErrorWithLog (/var/www/Compotes2/node_modules/esbuild/lib/main.js:1265:17)
    at /var/www/Compotes2/node_modules/esbuild/lib/main.js:1107:49
    at /var/www/Compotes2/node_modules/esbuild/lib/main.js:589:17
    at handleIncomingPacket (/var/www/Compotes2/node_modules/esbuild/lib/main.js:678:17)
    at Socket.readFromStdout (/var/www/Compotes2/node_modules/esbuild/lib/main.js:556:13)
    at Socket.emit (node:events:369:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Socket.Readable.push (node:internal/streams/readable:227:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

</details>

**To Reproduce**
1. Clone [this repository](https://github.com/Orbitale/Compotes/tree/rewrite) and checkout the `rewrite` branch.
2. Run `yarn install`
3. Run `yarn build`

**Expected behavior**
The app should be normally built into a bunch of HTML/CSS/JS files

**Platform and Versions (please complete the following information):**

<details>
<summary>⬇ Click to display output of the `yarn tauri info` command</summary>

```
$ yarn tauri info
yarn run v1.22.10
$ /var/www/Compotes2/node_modules/.bin/tauri info
 app:spawn Running "/var/www/Compotes2/node_modules/@tauri-apps/cli/bin/tauri-cli tauri info" +0ms


Operating System - Ubuntu, version 20.04 X64 (⚠⚠⚠ Pierstoval's note: this is under WSL 2 with a Windows 10 Pro setup)

Node.js environment
  Node.js - 15.14.0
  @tauri-apps/cli - 1.0.0-beta-rc.2
  @tauri-apps/api - 1.0.0   ( ⚠ Note: according to the "yarn.lock" file, the installed version is "1.0.0-beta-rc.2", I guess there's someting wrong in the published package with the version itself)

Global packages
  npm - 7.10.0
  yarn - 1.22.10

Rust environment
  rustc - 1.51.0
  cargo - 1.51.0

App directory structure
/.svelte
/node_modules
/src
/.idea
/.git
/src-tauri
/static

App
  tauri.rs - 1.0.0-beta-rc.2
build-type - bundle
CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
distDir - ../../frontend/build
devPath - http://127.0.0.1:3000
```

</details>

**Additional context**

I made a bunch of checks to know what was going on, so I went down in the stack trace to search for errors.

By going in `node_modules/esbuild/lib/main.js:1107:49` (the 3rd element in the stack trace), I saw some variables that I could debug, especially the `input` variable, that contains the resulted output from Svelte building the app `index.svelte` component.

Here's what I modified directly in the `esbuild` file:
![image](https://user-images.githubusercontent.com/3369266/115392793-4444b880-a1e1-11eb-9e2a-0d026b80a46e.png)

The most important part is this one: ![image](https://user-images.githubusercontent.com/3369266/115392925-66d6d180-a1e1-11eb-90bc-7e99cbf987ae.png)

I could then open this `test-output.js` file to see what's going on in it.

And here it is:

![image](https://user-images.githubusercontent.com/3369266/115393002-7eae5580-a1e1-11eb-9a5f-453d15a2dbe1.png)

It seems that at line 92 **the function lacks a name**.

So, in order to see where this function comes from, I made some research in the Tauri `api.js` file, and I saw this:

The code is minified and kinda obfuscated in the `index.mjs` file:
![image](https://user-images.githubusercontent.com/3369266/115393263-c634e180-a1e1-11eb-813b-6a856a6d0780.png)
But a simple "reformat code" in IntelliJ and I get this:
![image](https://user-images.githubusercontent.com/3369266/115393308-d482fd80-a1e1-11eb-9aa4-0239eced56ef.png)

We can see here that the statement at line 25 is `(function (r) {`, so again, anonymous function.

In the `@tauri-apps/api/index.js` built file I see that at line 17 the function is executed right after the `require()` statement, as you can see here:

![image](https://user-images.githubusercontent.com/3369266/115393457-02684200-a1e2-11eb-877e-a065634bc1f6.png)

I have not dug into Tauri API's build process, so I cannot tell for sure how to solve this, but I hope this saves some time to the team 👍

Just so you know, I could fix this issue and build the app by adding parentheses around the anonymous function in `@tauri-apps/api/index.js`:
![image](https://user-images.githubusercontent.com/3369266/115394041-aa7e0b00-a1e2-11eb-9d59-1a1d53a1e359.png)

**Comment by lucasfernog** [comment]
I can't reproduce this anymore so I think the latest @tauri-apps/api fixes solved this problem. Please reopen this issue if the version `1.0.0-beta-rc.3` still doesn't work on your app (it'll be released the next few days).

**Comment by Pierstoval** [comment]
I just used Tauri as submodule and built it, and the fact that the TS scripts are present is really useful I think, I have no other issue regarding the API itself 👍

**Comment by lucasfernog** [comment]
That's great, thanks for confirming it!

**Comment by Pierstoval** [comment]
Still, I'm using it as a submodule for now, so I'll check when the next release will be published to see if it still works for the "good way" of doing it 😄
