### ISSUE TITLE
Support typical system text-editing shortcuts

### ISSUE THREAD

**Issue by edbrannin** [tauri-apps/tauri#1549]
**Is your feature request related to a problem? Please describe.**

I keep trying to paste into an `<input>` with Command-V, but the only thing that works is "Right-click, select Paste".
Similar with Command-A to select all; presumably also Command-C to copy but I haven't tried it yet.

I did try Control-A for select-all, but ^A/^E seem to work like the rest of the OS (same as bash/readline).

**Describe the solution you'd like**
Make common Edit-menu shortcuts work in Tauri on MacOS

![image](https://user-images.githubusercontent.com/121909/115446097-b4a10900-a1e4-11eb-9be4-89a15adc5257.png)

**Describe alternatives you've considered**

I could keep using the right-click workaround forever, but that probably won't fly with arbitrary end-users.

Sorry if this falls under "Create native application menus and context menus" in #544

**Comment by nothingismagick** [comment]
I believe this has been fixed here https://github.com/tauri-apps/tauri/pull/1560

will be in the next release

**Comment by lucasfernog** [comment]
Indeed this falls under #544, and @lemarier is working on that.
