### ISSUE TITLE
Tray app

### ISSUE THREAD

**Issue by TheJaredWilcurt** [tauri-apps/tauri#157]
**Describe the solution you'd like**

An easy API to create a tray icon in the current os. So you can "minimize to tray", or even have the app be exclusively a tray app with a menu and no window. The right-click menu should be customizable and allow for common features like dividers and such (maybe checkboxes? maybe custom icons?).

**Comment by nothingismagick** [comment]
This is on our internal roadmap for 2020 already. Glad to see you are interested.

**Comment by tensor-programming** [comment]
I have a few things in mind for this already.  Will post more when we actually start the work on it.

**Comment by chiubaca** [comment]
Any updates on this? This is the feature I'm waiting for 🙏

**Comment by TheJaredWilcurt** [comment]
Since this was posted in 2019 and there's (seemingly) no movement, here is an alternative option:

* https://github.com/nwutils/nw-tray-example

**Comment by lucasfernog** [comment]
I believe we'll be able to implement this when [wry](https://github.com/tauri-apps/wry) lands. Current webview implementation has some issues, specially regarding the event loop and GTK.

cc @wusyong correct me if i'm wrong :P

**Comment by davidenke** [comment]
@lucasfernog Is there any progress on this?

**Comment by lucasfernog** [comment]
Not yet. We're focusing on shipping a beta release.

**Comment by Lucasmiguelmac** [comment]
Is there alreday a way to have a system-tray-only app? I see the [mentioned issue](https://github.com/tauri-apps/wry/pull/190) shows now that we can open and close a window from the system tray bar, yet I can't tell if we could already implement a tray-bar only app.

**Comment by amrbashir** [comment]
@Lucasmiguelmac yeah you can create a tray-bar only app, just don't add any windows inside your `tauri.conf.json` and create them programmatically when you want. you also need to prevent app exit when there is no windows open which you can do. Hope into our discord if you want some help setting it up.

**Comment by nathanredblur** [comment]
@Lucasmiguelmac did you do that? could you show me ? or @amrbashir do you have an example of that?

**Comment by amrbashir** [comment]
@nathanredblur here is how to prevent the app from exit when the last window is closed
https://github.com/tauri-apps/tauri/blob/956af4f30f665a1d059aad15d070b4bab9ca49b3/examples/api/src-tauri/src/main.rs#L220-L224
