### ISSUE TITLE
macOS(tauri): Inject plist in the runtime for webRTC & al.

### ISSUE THREAD

**Issue by lemarier** [tauri-apps/tauri#1570]
**Is your feature request related to a problem? Please describe.**
Yes. We should allow an option to inject a plist in the runtime to ask permissions.

**Describe the solution you'd like**
Add a new configuration field in `tauri.conf.json` for `macOS` to customize the plist.

### Option 1
We build a schema where they can define their own `dict` in `tauri.json.conf` (will require more works)

### Option 2
Ask for a path but the user should take care of all aspects of the plist (app name etc..)

Another field should allow enabling or disabling the plist injection at the runtime (in dev mode), in prod it should never be injected as we use the bundler plist.

Will require some update in the bundler as well to make sure dev and prod reflect the same.

**Describe alternatives you've considered**
N/A

**Additional context**
Refer to https://github.com/tauri-apps/wry/issues/85#issuecomment-823499749

**Comment by nothingismagick** [comment]
I am all for option #1 & #2

#1 we keep it REALLY simple
#2 is if they want to break it themselves

**Comment by lemarier** [comment]
@lucasfernog if you want i can do it, i would love to know how you see it and which option you prefer.

**Comment by lucasfernog** [comment]
I think we should go with #2, writing a plist in JSON must be weird (and prevents someone to just copy a file from stackoverflow lol).

**Comment by lemarier** [comment]
> I think we should go with #2, writing a plist in JSON must be weird (and prevents someone to just copy a file from stackoverflow lol).

make sense lol!

gonna draft that quickly
