### ISSUE TITLE
Frameless window

### ISSUE THREAD

**Issue by TheJaredWilcurt** [tauri-apps/tauri#158]
**Describe the solution you'd like**
An option to spawn a window without a frame or "chrome" border/title bar/window controls (min/max/restore/close), requiring the app to supply it's own window controls

**Additional context**

![borderlessresizablewithchild](https://user-images.githubusercontent.com/4629794/70757263-e3fc5780-1d0c-11ea-9153-60b4f7c4f849.png)

**Comment by nothingismagick** [comment]
This is on our internal roadmap for 2020 already. Glad to see you are interested.

**Comment by DrSensor** [comment]
Status: waiting for https://github.com/Boscop/web-view/pull/130 to be merged

**Comment by nklayman** [comment]
This is added in the dev branch, and will available in the next release :tada:.

**Comment by richardaum** [comment]
For those who want to know:

```js
// javascript
appWindow.setDecorations(false);
``` 
or via tauri.conf.json
```
tauri.windows.decorations: false
```

**Comment by Hotdogishot** [comment]
It is possible to only "hide" the frame (like electron) ?

**Comment by nothingismagick** [comment]
yes @Hotdogishot. see here: https://tauri.studio/docs/guides/window-customization

**Comment by ghost** [comment]
its supported here at https://github.com/pykeio/millennium which is a tauri fork

**Comment by mufeez-amjad** [comment]
Is it possible to hide the title bar but keep the window close/minimize/maximize buttons?

**Comment by FabianLars** [comment]
@mufeez-amjad https://github.com/tauri-apps/tauri/issues/2663

**Comment by microSoftware** [comment]
> Is it possible to hide the title bar but keep the window close/minimize/maximize buttons?

Have you figured it out? I'm also interested doing this
