### ISSUE TITLE
[gh actions] install webkit2gtk (ubuntu only) => fails

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#159]
It seems something is suddenly wrong with the `apt-get`... 
https://github.com/tauri-apps/tauri/runs/347043697

**Comment by jbolda** [comment]
This seems to be out of our hands. Looks like names were changed in Azure, and we caught then in the middle of a changeover?

**Comment by nothingismagick** [comment]
Ok - if the next run passes then we can close this.

**Comment by nothingismagick** [comment]
We've been passing now regularly. This seems resolved. @jbolda - what do you think?

**Comment by jbolda** [comment]
Agreed. 🎉
