### ISSUE TITLE
Reduce some of the non-generic aspects of the WIX template

### ISSUE THREAD

**Issue by Cupnfish** [tauri-apps/tauri#1606]
**Is your feature request related to a problem? Please describe.**
Reduce some of the non-generic aspects of the WIX template.

**Describe the solution you'd like**
The current WIX template is the default download edge webview, for other rust projects do not need this, packaging with this is very inconvenient, there is no way to solve this problem?

**Describe alternatives you've considered**
I can’t think of a more appropriate way to do this. My current project is to introduce a separate Wix template directly, but this will cause some confusion at the top of the Tauri.

**Additional context**
```
        <!-- WebView2 -->
        <Property Id="WVRTINSTALLED">
            <RegistrySearch Id="WVRTInstalled" Root="HKLM" Key="SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" Name="pv" Type="raw" Win64="no"/>
        </Property>
        <CustomAction Id='DownloadAndInvokeBootstrapper' Directory="INSTALLDIR" Execute="deferred" ExeCommand='powershell.exe -windowstyle hidden Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/p/?LinkId=2124703" -OutFile "$env:TEMP\MicrosoftEdgeWebview2Setup.exe" ; &amp; $env:TEMP\MicrosoftEdgeWebview2Setup.exe /install' Return='check'/>
        <InstallExecuteSequence>
            <Custom Action='DownloadAndInvokeBootstrapper' Before='InstallFinalize'>
                <![CDATA[NOT(REMOVE OR WVRTINSTALLED)]]>
            </Custom>
        </InstallExecuteSequence>

        <SetProperty Id="ARPINSTALLLOCATION" Value="[INSTALLDIR]" After="CostFinalize"/>      
```

**Comment by lucasfernog** [comment]
We'll need to add a flag to allow removing that step anyway :) so this is good

Btw how are you using the bundler? your own script?

**Comment by Cupnfish** [comment]
I use it directly as a lib, which is equivalent to using rust as a script.
My project is open source, you can view it [here](https://gitlab.com/localnative/localnative/-/merge_requests/6)

**Comment by nothingismagick** [comment]
Well, I am not sure I fully understand that scope of your question - but I believe we need to generally revisit the means by which people expect to ship WebView2. I see three options:

1. Trust that the user has WebView2 installed (do nothing - most fragile)
2. Use the Evergreen Distribution Model (rolling updates, most secure)
3. Ship a "frozen" binary version of WebView2 (largest, required on airgapped / no network devices)

But if you are asking us to refactor the Tauri Bundler for purposes not directly related to Tauri that may make our lives more complicated, challenging or introduce maintenance burden, then I will have a hard time supporting it.

**Comment by nothingismagick** [comment]
@Cupnfish - maybe if you showed me though where in your codebase you are using / planning to use the bundler, then I would understand your requirements better.

**Comment by Cupnfish** [comment]
https://gitlab.com/localnative/localnative/-/blob/ec5a4d4b10ac778a2c39009f7523ae0f984a6e1e/localnative-rs/localnative_bundle/src/main.rs
I used it here, and the main requirement is that WebView is not necessary in non-Tauri projects. I also feel that adding some flags to turn off this option will make Tauri's bundler difficult to maintain, so if there is no other better method, this issue will be close.

**Comment by nothingismagick** [comment]
Don't get me wrong, there are situations where you may not even want a webview at all (like a pure headless / or CLI app). So I understand what you are after, just don't know exactly WHAT approach we will take yet.
