### ISSUE TITLE
@tauri-apps/cli init --ci still asks questions

### ISSUE THREAD

**Issue by jbolda** [tauri-apps/tauri#1614]
**Describe the bug**
When specifying `--ci`, it will still prompt: `? [NPM]: "Do you want to install @tauri-apps/api ?" (y/N)`

We may also want to review all of our prompts and/or co-locate them to it is easier to track these considerations.

**To Reproduce**
![image](https://user-images.githubusercontent.com/2019387/115983671-3b990d00-a568-11eb-929a-a14a5aa142d0.png)

**Expected behavior**
No prompts with `--ci`.

**Screenshots**

**Platform and Versions (please complete the following information):**
(Screenshot above with the following, but likely not environment specific.
OS: W10
Node: v14.16.1
NPM: 7.10.0
Rustc: rustc 1.51.0 (2fd73fabe 2021-03-23)

**Comment by lucasfernog** [comment]
This was fixed on #1603

**Comment by lucasfernog** [comment]
Still good to reconsider about the prompts location though.
