### ISSUE TITLE
Feature: App name should be set automatically

### ISSUE THREAD

**Issue by nklayman** [tauri-apps/tauri#162]
The app's identifier, name, window title, and description should all be prompted for/taken from `package.json` and used, rather than just setting defaults.

**Comment by nothingismagick** [comment]
This has been resolved, hasn't it @nklayman ?

**Comment by nklayman** [comment]
No, I should be able to get to it this weekend though.

**Comment by nklayman** [comment]
https://github.com/tauri-apps/tauri/pull/472
