### ISSUE TITLE
[Beta] Tauri breaks when adding specific CSS properties [WSL 2 only]

### ISSUE THREAD

**Issue by Pierstoval** [tauri-apps/tauri#1621]
Prerequisites:

* Using Windows 10 pro and WSL 2
* Have an X server running on the Windows host (VcXsrv or GWSL)
* Setup your WSL environment with the DISPLAY env var pointing to your host machine (as [stated in Tauri docs](https://tauri.studio/en/docs/getting-started/setup-linux#4-for-windows-subsystem-for-linux-wsl-users))

Here's the scenario:

* Clone this repo: https://github.com/Orbitale/Compotes/tree/rewrite
* Check out the `rewrite` branch
* Run `yarn install && yarn tauri deps install`
* Run `yarn dev` in a console
* Open another console and run `yarn tauri dev`
* The console in which you ran `yarn tauri dev` should display this:
  ```
  $ yarn tauri dev
  yarn run v1.22.10
  $ /var/www/Compotes3/node_modules/.bin/tauri dev
   app:spawn Running "/var/www/Compotes3/node_modules/@tauri-apps/cli/bin/tauri-cli tauri dev" +0ms

    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/app`

  (WebKitWebProcess:6095): Gdk-ERROR **: 00:00:49.199: The program 'WebKitWebProcess' received an X Window System error.
  This probably reflects a bug in the program.
  The error was 'GLXBadFBConfig'.
    (Details: serial 172 error_code 163 request_code 149 (GLX) minor_code 21)
    (Note to programmers: normally, X errors are reported asynchronously;
     that is, you will receive the error a while after causing it.
     To debug your program, run it with the GDK_SYNCHRONIZE environment
     variable to change this behavior. You can then get a meaningful
     backtrace from your debugger if you break on the gdk_x_error() function.)
  ```

If you remove the `position: fixed` or the `animation-name: orbitale_logo_rotation;` CSS rules in the `public/index.html`, you'll see that everything now works, but indeed animation is disabled.

**Worth noting:**
* The animation that is bound to `#splash_screen.remove` works without any issue, it is related to the `opacity` property going from 1 to 0.
* I tested to remove the animation on the `#orbitale_logo` selector and instead just `transform: rotate(0deg);`, to see if the issue was coming from the `transform` property, and the error didn't show, the logo is properly rotated. Only animating the property triggers the error.

Tested in Ubuntu 20.04 under WSL 2, display has been tested with a plain VcXsrv setup and with GWSL with different configs that didn't change anything, the error still pops.

I tested on a native Ubuntu 20.04 machine, and I can confirm that the error does not appear, with any property, everything works.

I also tested on native Windows, and the error doesn't appear either, everything works.

So this is certainly a WSL-only issue 😕

**Comment by Pierstoval** [comment]
I tested on a native Ubuntu machine, and I can confirm that the error does **not** appear, with any property.

So this is certainly a WSL-only issue 😕

I didn't test on native Windows because I have another issue ("cannot create webview"), I don't know (yet?) if it's related to the same subject.

**Comment by Pierstoval** [comment]
Okay, I found a way to make it work!

Not sure it's a "definite" solution, but here is what I did:

* At first, I ran `export LIBGL_ALWAYS_INDIRECT=0` 
* I updated my `VcXsrv` command and replaced `-wgl` with `-nowgl`
* It now works

I honestly just jiggled with parameters after looking at bazillion posts and tutorials and stuff, and now it works...

I hope it will keep working 😅

**Comment by nothingismagick** [comment]
So you just turned off webgl? I doubt this is going to be a good solution for consumers of your application and sounds very hacky since it treats the problem instead of solves it.

**Comment by Pierstoval** [comment]
> So you just turned off webgl? I doubt this is going to be a good solution for consumers of your application and sounds very hacky since it treats the problem instead of solves it.

I agree, that's the reason why I think the "fix" isn't really a fix to me. WebGL seems to be mandatory for such app.

However, I think **running** this app on WSL isn't the purpose at all. I use WSL for development, but in the end, the linux version of it is supposed to be downloaded on linux platforms, not WSL.
Maybe I'm too skeptical to think that WSL is for development only, but I think that this isn't the "common" way of running apps 😅

**Comment by amrbashir** [comment]
closed it by accident 😅

**Comment by tensor-programming** [comment]
Think its probably a good idea to close this issue for now.  If you want to use `webkit-gtk` under WSL right now, then you need to use WSL 1 not WSL 2.  In the meantime, Microsoft is developing a method to use GUI apps under WSL 2 that uses the GPU called [WSLg](https://github.com/microsoft/wslg) which will resolve the issue.   Its in the dev branch of the insider build of windows right now though I don't recommend updating to it until its in the beta branch.
