### ISSUE TITLE
Invoking a missing custom Rust command should show a warning in JS console

### ISSUE THREAD

**Issue by yamgent** [tauri-apps/tauri#1624]
**Is your feature request related to a problem? Please describe.**
Sometimes the JS frontend may call a custom Rust command that may not exist (either due to a typo, a refactoring error, wrong usage of the Rust's API, etc.).

```ts
import { invoke } from "@tauri-apps/api/tauri";

export async function getSomeData(): unknown {
  // in tauri beta version, when command doesn't exist,
  // it fails silently.
  const result = await invoke('this_command_does_not_exist');
  return result;
}
```

It is hard to catch these errors since they fail silently.

**Describe the solution you'd like**
I think previously before the beta, there was a similar warning when calling a missing command. Maybe we can add that behaviour back in?

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by lucasfernog** [comment]
This was implemented on latest beta-rc.4 release. What version are you using?

**Comment by lucasfernog** [comment]
Please reopen if this is still happening on latest Tauri version.
