### ISSUE TITLE
Dangling dev server process

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tauri#1626]
**Describe the bug**
Sometimes when tauri exits, I'm left with the `beforeDevCommand` still running in the background (as a `node` process), which I notice because the port is still in use the next time I run `tauri dev`. I'm guessing this happens on some crashes or some other unusual situations.

**To Reproduce**
Haven't found a way to reproduce it reliably yet

**Platform and Versions (please complete the following information):**

OS: macOS 10.15.7
Node: 14.16.0
NPM: 6.14.11
Rustc: 1.51.0

**Comment by probablykasper** [comment]
Found two ways to reproduce:
- Quit the app itself by right-clicking it in the Dock.
- Call `app.exit()` in the webview

**Comment by probablykasper** [comment]
I think the issue could be that `kill_before_dev_process()` is not necessarily called depending on the if statements here: https://github.com/tauri-apps/tauri/blob/0f86bc4071635d142b54ae0abf5cf79694ec8ede/tooling/cli.rs/src/dev.rs#L171-L190

**Comment by lucasfernog** [comment]
What framework are you using? What's your beforeDevCommand?

**Comment by probablykasper** [comment]
I'm using vite/Svelte

**Comment by lucasfernog** [comment]
I can confirm this issue, it should affect all users. It happens because we're using `sh -c $beforeDevCommand` and it's not killing the child process.

**Comment by lucasfernog** [comment]
I've fixed it on the Tauri side, but Svelte still has an issue, the [server kill](https://github.com/sveltejs/template/blob/d80f6723b2b9e1fcc0a3214c28d6a3634cd9caf6/rollup.config.js#L14) isn't working for some reason.

**Comment by probablykasper** [comment]
@lucasfernog Hmm, a bit confused by that. Sending SIGINT to the `tauri dev` process works just fine, so wouldn't it be possible to handle this the same way?

**Comment by lucasfernog** [comment]
I think SIGINT is handled by `cargo`, not sure what kind of magic they're doing. But a simple `pkill -TERM -P pid` doesn't kill the Svelte subprocess :/ even though it receives the signal successfully. It works just fine on Vue.js.

**Comment by probablykasper** [comment]
Reproduced it with just the svelte template, so opened an issue there. Thanks for helping with this!
