### ISSUE TITLE
Cannot run tauri-cli behind corporate proxy

### ISSUE THREAD

**Issue by pulse0ne** [tauri-apps/tauri#1628]
**Describe the bug**
Tauri attempts to (and fails, due to `got` not handling proxies well) download an updated CLI, silently fails and exits before it is able to run the command. The cli update should either handle proxies properly, or be able to be toggled off with a flag. 

**To Reproduce**
1. Run any tauri command behind a corporate proxy

**Expected behavior**
The command to complete. Instead, the message "Downloading Tauri CLI" is displayed, then the process exits without executing the actual command.

**Screenshots**

**Platform and Versions (please complete the following information):**
(Can't run `yarn tauri info` because the download fails and kills the process before the actual command can execute)
OS: RHEL 8
Yarn: 1.22.10
Node: 14.16.0
Tauri: 1.0.0-beta-rc.4

**Additional context**
I know handling proxies is a pain, but developers behind corporate proxies don't have a choice. `got` has taken a particularly [unhelpful](https://github.com/sindresorhus/got/issues/79) stance on proxies, basically stating that `node` should fix it. At the very least, a proper error or stack trace when the download fails would be helpful. It would also be very helpful to have a flag that would turn off the download entirely, which would also enable developers behind corporate MITM proxies to use tauri!

**Stack Trace**
N/A, fails silently

**Comment by nothingismagick** [comment]
Well, the fun won't end for you here, especially because to the best of my knowledge RHEL uses a VERY outdated glibc. However, I do understand your pain.  

Now, I am not going to comment on Sindre's reasoning here other than to mention that this answer is from 6 years ago, and I am not sure why it should be considered his problem.

That said, we should absolutely offer an alternative approach - perhaps something mimicking an offline model. @nklayman - what are your thoughts here

**Comment by pulse0ne** [comment]
Yeah, luckily I've been able to solve the toolchain (super old gcc, glibc, etc) problems on other projects, so *hopefully* it won't be so painful if I can get this figured out. Then again, there always seems to be something with RHEL...

I understand it's an old issue and maintaining code related to proxies is...less than fun. I just haven't seen any recent movement or information on how to even use `got` effectively behind a MITM proxy. It doesn't appear that there's ANY way at all to use projects that depend on `got` behind a proxy if those projects aren't providing an http agent that's configured to use proxies. 

I just tried using RC.2 to run tauri-cli, and I was able to get a stacktrace from `got`, which basically boils down to `ENOTFOUND: github.com`, which confirms the theory that it's not making the request through my environment's proxy.

**Comment by nothingismagick** [comment]
Would downloading the binary with curl or directly from github releases work, in combination with some kind of configuration that allows you to manually point at its location?

Alternatively running directly from the dev branch?

**Comment by nklayman** [comment]
@pulse0ne You can manually download the CLI binary from [this page](https://github.com/tauri-apps/binary-releases/releases) and copy it to `node_modules/@tauri-apps/cli/bin/tauri-cli(.exe)`. Make sure to `chmod +x` it so that it is executable as well. Tauri CLI will use that binary instead of downloading an new one and it should work.

**Comment by nothingismagick** [comment]
This would be a good error message.

**Comment by nothingismagick** [comment]
another option is to use the rust CLI:
```
% cargo install tauri-cli --version ^1.0.0-beta
% cargo tauri --version
```

**Comment by rxliuli** [comment]
For any proxy-related issues, you can consider trying a transparent proxy tool like Proxifier, which can proxy all requests from the computer and forward them to the designated proxy server

---

If your company’s network configuration is whitelisted, you can only leave...

**Comment by pulse0ne** [comment]
It seems like there are some good workarounds here. Closing

**Comment by JohnCido** [comment]
> @pulse0ne You can manually download the CLI binary from [this page](https://github.com/tauri-apps/binary-releases/releases) and copy it to `node_modules/@tauri-apps/cli/bin/tauri-cli(.exe)`. Make sure to `chmod +x` it so that it is executable as well. Tauri CLI will use that binary instead of downloading an new one and it should work.

I downloaded the Windows version into the target folder you mentioned and ran the `yarn tauri info` again in **WSL**. The funny thing is I was not able to download the Rust CLI behind my proxy, but it succeeded after I paste the Windows binary. Not sure they're related. But anyway， I finally get the Tauri CLI tool to work properly.

**Comment by lucasfernog** [comment]
This will be supported on the next release, see #2381
