### ISSUE TITLE
Feature: Executables and installers output dir should be customizable

### ISSUE THREAD

**Issue by nklayman** [tauri-apps/tauri#164]
Currently, Tauri builds executables to `src-tauri/target/release/`. The output dir should be customizable. This will allow the vue cli plugin to output to `dist_tauri` along with the web code.

**Comment by tensor-programming** [comment]
This is possible, we would have to add a feature flag and a output directory environment variable.  I could cover the Rust side of things.  Just need someone to add the simple JS/JSON stuff.

**Comment by vhelke** [comment]
I hit this same problem since my target-path is different to default.

I have all the rust-targets at /rust/target/

Currently the tauri build fails for me with following info.

```
$ yarn tauri build
yarn run v1.22.4
$ /rust/tauri/node_modules/.bin/tauri build
[tauri]: running build
 app:spawn Running "cargo tauri-bundler --features embedded-server --release" +0ms

   Compiling app v0.1.0 (/rust/tauri/src-tauri)
   Compiling tauri v0.5.2
    Finished release [optimized] target(s) in 11.81s
    Bundling app_0.1.0_amd64.deb
error: Failed to build folders
  Caused by: Failed to copy binary file
  Caused by: "/rust/tauri/src-tauri/target/release/app" does not exist

 app:spawn Command "cargo" failed with exit code: 1 +0ms

 app:tauri (runner) ⚠️  [FAIL] Cargo CLI has failed +0ms

 app:tauri Shutting down tauri process... +0ms
error Command failed with exit code 1.
```

There should be a way in the tauri-config to set another target-dir.

**Comment by nothingismagick** [comment]
We should revisit this.

**Comment by lucasfernog** [comment]
Looks like an issue with the bundler, probably not following all of the Cargo output folder alternatives (env vars, config etc), so it's kind of unrelated to the original issue and should be tracked separately.

**Comment by lucasfernog** [comment]
@vhelke your use case will be supported on the next release, see https://github.com/tauri-apps/tauri/pull/895

Thank you for reporting it!
