### ISSUE TITLE
Allow child windows to be created from main app window

### ISSUE THREAD

**Issue by rodryquintero** [tauri-apps/tauri#1643]
**Is your feature request related to a problem? Please describe.**
Yes, currently, newly spawned windows behave like separate app windows, independent from the main app itself. If you close the main app window, the spawned windows remain open.

**Describe the solution you'd like**
Enhance the `WebviewWindow` or `appWindow` API so that child widnows can be spawned related to the main app window.

Using the `appWindow` object, a solution could look like this.

```javascript
import { appWindow } from "@tauri-apps/api/window";

const childwin = appWindow.open("child.html")
```
While the `WebviewWindow` api option would look like this:

```javascript
import { WebviewWindow, appWindow } from "@tauri-apps/api/window";

const parentWin = new WebviewWindow("parentwin.html", {parent: appWindow })
const childWin= new WebviewWindow("child.html", {parent: parentWin })
```
**Describe alternatives you've considered**
I suppose I can write Rust commands to manipulate windows.

**Additional context**
Electron JS supports this in its `BrowserWindow` api (https://www.electronjs.org/docs/api/browser-window).

```javascript
const { BrowserWindow } = require('electron')

const top = new BrowserWindow()
const child = new BrowserWindow({ parent: top })
child.show()
top.show()
```

**Comment by AnupamKris** [comment]
> 
> 
> **Is your feature request related to a problem? Please describe.**
> Yes, currently, newly spawned windows behave like separate app windows, independent from the main app itself. If you close the main app window, the spawned windows remain open.
> 
> **Describe the solution you'd like**
> Enhance the `WebviewWindow` or `appWindow` API so that child widnows can be spawned related to the main app window.
> 
> Using the `appWindow` object, a solution could look like this.
> 
> ```js
> import { appWindow } from "@tauri-apps/api/window";
> 
> const childwin = appWindow.open("child.html")
> ```
> 
> While the `WebviewWindow` api option would look like this:
> 
> ```js
> import { WebviewWindow, appWindow } from "@tauri-apps/api/window";
> 
> const parentWin = new WebviewWindow("parentwin.html", {parent: appWindow })
> const childWin= new WebviewWindow("child.html", {parent: parentWin })
> ```
> 
> **Describe alternatives you've considered**
> I suppose I can write Rust commands to manipulate windows.
> 
> **Additional context**
> Electron JS supports this in its `BrowserWindow` api (https://www.electronjs.org/docs/api/browser-window).
> 
> ```js
> const { BrowserWindow } = require('electron')
> 
> const top = new BrowserWindow()
> const child = new BrowserWindow({ parent: top })
> child.show()
> top.show()
> ```
This works perfectly but how to send and receive data or signals back and forth ie. from webview to app window and vice versa

**Comment by lucasfernog** [comment]
> > **Is your feature request related to a problem? Please describe.**
> > Yes, currently, newly spawned windows behave like separate app windows, independent from the main app itself. If you close the main app window, the spawned windows remain open.
> > **Describe the solution you'd like**
> > Enhance the `WebviewWindow` or `appWindow` API so that child widnows can be spawned related to the main app window.
> > Using the `appWindow` object, a solution could look like this.
> > ```js
> > import { appWindow } from "@tauri-apps/api/window";
> > 
> > const childwin = appWindow.open("child.html")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > While the `WebviewWindow` api option would look like this:
> > ```js
> > import { WebviewWindow, appWindow } from "@tauri-apps/api/window";
> > 
> > const parentWin = new WebviewWindow("parentwin.html", {parent: appWindow })
> > const childWin= new WebviewWindow("child.html", {parent: parentWin })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Describe alternatives you've considered**
> > I suppose I can write Rust commands to manipulate windows.
> > **Additional context**
> > Electron JS supports this in its `BrowserWindow` api ([electronjs.org/docs/api/browser-window](https://www.electronjs.org/docs/api/browser-window)).
> > ```js
> > const { BrowserWindow } = require('electron')
> > 
> > const top = new BrowserWindow()
> > const child = new BrowserWindow({ parent: top })
> > child.show()
> > top.show()
> > ```
> 
> This works perfectly but how to send and receive data or signals back and forth ie. from webview to app window and vice versa

https://tauri.studio/en/docs/guides/command

you should ask this kind of question on Discord though, it's not related with this issue :)

**Comment by AnupamKris** [comment]
Nobody answers in Tauri's discord..

**Comment by tufik2** [comment]
Any news about this issue?, this should be a hight priority implementation

**Comment by KiddoV** [comment]
Any updates on this, as it would be nice to have a custom dialog in HTML that match the app theme. We use all the fancy stuff in the frontend view, so having a native dialog looks... a bit ugly. 🤔

**Comment by drernie** [comment]
I would also be very interested in this.  I would love to see Tauri fully support some form of [document-based applications](https://developer.apple.com/document-based-apps/), where every document has its own window.

From what I can tell, this is [not trivial](https://stackoverflow.com/questions/76281050/cross-referencing-in-rust-implementing-mvc) to do correctly because the way Rust interacts with Model-View-Controller, so having a standard, shared implementation would be a huge win.

**Comment by amrbashir** [comment]
This is now supported in v2

**Comment by moom-en** [comment]
> This is now supported in v2

@amrbashir Does v1.6 support this feature?

**Comment by amrbashir** [comment]
no, only v2 and using `unstable` cargo feature flag
