### ISSUE TITLE
Background color not white on Vue cli builds

### ISSUE THREAD

**Issue by nklayman** [tauri-apps/tauri#165]
When using the Vue cli plugin, the app's background color isn't white, rather a dark grey. This makes the app look wierd and the text hard to read.

**Comment by lucasfernog** [comment]
What OS are you using? I'm sure that happens if you're using some kind of GTK theme, don't know if that's the case for you.

**Comment by nothingismagick** [comment]
And what happens if you set a non transparent background color in your CSS, like for example white?

**Comment by lucasfernog** [comment]
The original (I have the arc gtk theme, that's why it's kind of messed up):
![2019-12-16_816x848_screenshot](https://user-images.githubusercontent.com/20051258/70949079-b16b9b00-203b-11ea-8b22-54ffdbea71a7.png)

With `body{background:blue}` CSS
![2019-12-16_744x769_screenshot](https://user-images.githubusercontent.com/20051258/70949080-b16b9b00-203b-11ea-810c-468d79af2b11.png)

**Comment by nklayman** [comment]
Is there a way to override it? I don't think we should set color based on gtk theme.

**Comment by lucasfernog** [comment]
Well, we're using GTK's webview, so I think we can't do anything.

**Comment by nklayman** [comment]
Could we inject a stylesheet that sets it to white? I feel like your app should look the same as in a browser.

**Comment by jbolda** [comment]
I think each browser has their own base stylesheet, but they aren't perfectly consistent.

**Comment by tensor-programming** [comment]
This may have been resolved with some of the recent patches.  I've noticed that the old react apps had a sort of grey background.  Seems that they now are showing a white one instead.

**Comment by nothingismagick** [comment]
@nklayman - can you confirm that @tensor-programming is right about this?

**Comment by nklayman** [comment]
I still have the off-colored background.

**Comment by lucasfernog** [comment]
I think we should file an issue about this on Boscop/web-view, maybe there's a C API to disable the theme. You can see that it's a theming issue by starting the app with another theme:

`GTK_THEME=Adwaita:dark ./src-tauri/target/debug/app`

**Comment by nothingismagick** [comment]
have you tried with the latest 0.6 version of boscop - was just released a few days ago.

**Comment by nothingismagick** [comment]
https://github.com/Boscop/web-view/blob/0ef21b66820965e3da7f7343565978174176db6a/webview-sys/webview_gtk.c#L186-L192

**Comment by lucasfernog** [comment]
Same results with boscop/web-view 0.6.0

**Comment by lucasfernog** [comment]
Oh but I should call that function right

**Comment by nothingismagick** [comment]
but we should def release a new version with boscop 0.6

**Comment by lucasfernog** [comment]
set_color() works as expected (it sets the background color of the web-view) but GTK still uses the theme colors e.g. the font color is still the same obviously. So it doesn't help us much.

**Comment by lucasfernog** [comment]
Anyway we do need to bump boscop to 0.6.0, and put a `color` config under tauri.conf.json > tauri > window.

**Comment by nothingismagick** [comment]
you know, maybe this is known. i looked at the examples at boscop, and it seems that they all have a background color set. ;)

**Comment by lucasfernog** [comment]
IMO the GTK theme is the user's choice and we should leave it as is, if the app doesn't look good with the installed theme, he needs to set it manually.

**Comment by nothingismagick** [comment]
def something for the docs. filing an issue at tauri.studio

**Comment by nklayman** [comment]
Could we apply a default `background-color:white` to the `body` tag?

**Comment by lucasfernog** [comment]
That won't fix the problem because the font color would still be messed up, as I said.

**Comment by nklayman** [comment]
Ohh, my bad, didn't see that. I didn't have any font color issues so I thought it was just the background color.

**Comment by lucasfernog** [comment]
If you use another GTK theme, you'll see different behaviors.

**Comment by lucasfernog** [comment]
@nothingismagick the Windows theme also impacts the webview.

**Comment by nothingismagick** [comment]
# 🤦‍♂

**Comment by lucasfernog** [comment]
I'm not sure if this is good or bad news lol but we really need to look for a "disable theme" option upstream, if that's possible.

**Comment by nothingismagick** [comment]
I bet @zserge knows how we could go about doing blocking that kind of behavior.

**Comment by nothingismagick** [comment]
Isn't there or wasn't there a "color" flag?

**Comment by zserge** [comment]
There was a color setting in the earlier webview, it was able to only set the color of the background main window (the webview itself is transparent). Maybe it wouldn't be hard to bring it back to the current webview (but please, no transparent windows - they are not supported on all platforms very well and make things really confusing).
The primary use case for that originally was to initialize window with some color before webview content loads up (so that for dark content there was no white flickering). And the reason why it has been removed from the new webview is becuase on Windows for example that didn't help much.
In my mind, the content you are running inside the webview is responsible for the background color and the rest of the "look-and-feel" of the webview, which is transparent by default on most platforms I guess.

**Comment by nothingismagick** [comment]
@Laegel - this seems like something that we should address in the docs for now - that device themes can mess up if you don't explicitly declare a background color. 

I guess here: https://tauri.studio/docs/usage/identity

Then when we finally move to the official webview via our bindings, color is supported there and we've added the flag to the config we can add that to our documentation as well.

**Comment by Laegel** [comment]
Shouldn't we force it to white (the background color you can expect when you start working on a HTML app) and let users modify it optionally? Or is it going to be an issue even if we've defined an initial background color?

**Comment by nklayman** [comment]
For some reason this is no longer an issue with Vue cli.

**Comment by nothingismagick** [comment]
So close the issue?

**Comment by nklayman** [comment]
Yep, just confirmed that the background is white.
