### ISSUE TITLE
Refactor `<a target="_blank">` link usage

### ISSUE THREAD

**Issue by lucasfernog** [tauri-apps/tauri#1657]
Currently, Tauri opens `<a target="_blank">` links using the default browser.
We should use a new Tauri window by default, and allow changing that to use the default browser or even disabling it.
Additionally, we should allow users to define an allowlist for such link opening.

**Comment by kiehnek** [comment]
IMO links shouldn't be opened in a new tauri window by default. This suggests that the opened webpage is part of the application which is something I would try to avoid. With this enabled your application essentially becomes a browser.

I think adding an option to do this is a good idea, but opening the default browser should stay the default behaviour.

**Comment by OJFord** [comment]
`rel="noopener"` doesn't - it switches focus to the default browser, but the link opens in the Tauri window; the same one.

[MDN says](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noopener):
> Note that when noopener is used, nonempty target names other than _top, _self, and _parent are all treated like _blank in terms of deciding whether to open a new window/tab.

and:
> Setting target="_blank" on <a> elements now implicitly provides the same rel behavior as setting rel="noopener"

**Comment by vsnthdev** [comment]
I agree with @korki43 on the point that opening links in a new Tauri window would essentially turn Tauri into a web browser.

However, we should implement a way to open new windows right from the frontend, currently, I see no docs on opening a new window at https://tauri.studio/en/docs/api/js/modules/window.

Here's an example implementation:
```html
<a href="https://example.com" target="_tauri">Example link</a>
```

When target is set to `_tauri` instead of `_blank` we create a new window, else we open the link using the default web browser.

**Comment by lucasfernog** [comment]
> I agree with @korki43 on the point that opening links in a new Tauri window would essentially turn Tauri into a web browser.
> 
> However, we should implement a way to open new windows right from the frontend, currently, I see no docs on opening a new window at [tauri.studio/en/docs/api/js/modules/window](https://tauri.studio/en/docs/api/js/modules/window).
> 
> Here's an example implementation:
> 
> ```
> <a href="https://example.com" target="_tauri">Example link</a>
> ```
> 
> When target is set to `_tauri` instead of `_blank` we create a new window, else we open the link using the default web browser.

https://tauri.studio/en/docs/api/js/classes/window.webviewwindow

**Comment by vsnthdev** [comment]
Ah! Didn't check that. Thanks @lucasfernog

**Comment by joepio** [comment]
Just wanted to add that `event.preventDefault()` should prevent `target="blank"` anchors from opening in a new tab. This was the issue discussed in #2791.

**Comment by lucasfernog** [comment]
> #2791

See #3349

**Comment by lucasfernog** [comment]
I'll close this since we agreed on keeping the "open on default browser" behavior. If you want a `target="tauri"` implementation, please open a separate issue.
