### ISSUE TITLE
Access to Rust libraries, similar to `@electron/remote`

### ISSUE THREAD

**Issue by rodryquintero** [tauri-apps/tauri#1684]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Access to libraries that can work with the  underluying OS. Similar to the way Node interacts with Electron.

**Describe alternatives you've considered**
Using Electron.

**Additional context**
Electron is able to access the entire Node JS library by the use of `@electron/remote` feature. The *Tauri* project would benefit from something similar for Rust.

https://www.electronjs.org/docs/api/remote

**Comment by nothingismagick** [comment]
You can make custom commands and using our APIs have access to not only the shell, but also filesystem, network etc. You can even extend with plugins, to send a command to rust and get a response. I believe we already provide such functionality, especially considering that `remote` is deprecated and IPC also uses messaging.
