### ISSUE TITLE
File not found with app using react-router

### ISSUE THREAD

**Issue by vbornand** [tauri-apps/tauri#1714]
**Describe the bug**
When I try to navigate in a application using react-router, I get a "File not found" when I navigate,

When the app is in dev (with a local dev server), it works correctly, but when I used the bundled, when I navigate I get the error "File not found ERR_FILE_NOT_FOUND"

In the inspect window, I see a call to
file://custom-protocol-taurilocalhost/dashboard/products
with the result "(failed) net::ERR_FILE_NOT_FOUND"

**Expected behavior**
Access the page without any call in the inspect window.

**Platform and Versions (please complete the following information):**

OS: Windows, version 10.0.19042 x64
Node: 14.16.1
NPM: 7.11.2
Yarn: 1.15.2
Rustc: 1.51.0

**Additional context**
The application works correctly on Microsoft Edge.

**Comment by nothingismagick** [comment]
This is resolved in the next release.
