### ISSUE TITLE
open default browser 

### ISSUE THREAD

**Issue by Ludea** [tauri-apps/tauri#1727]
**Describe the bug**
open default browser from Tauri.

**To Reproduce**
Create a simple button
add `onClick={() => new Command("powershell", ["/C", "start https://google.com"]) }`
nothing happen

create a second button with 
`onClick={() => window.open("https://google.com") }`
a new window is created

**Expected behavior**
Open the default browser (Brave in my case).

**Screenshots**
![windows open](https://user-images.githubusercontent.com/2116692/117275036-ead5be00-ae5d-11eb-9745-1eca7bc080a8.png)

**Platform and Versions (please complete the following information):**

OS: Windows 10
Node: 14.12
NPM: 6.14.8
Yarn: 1.22 
Rustc: 1.51

**Comment by nothingismagick** [comment]
So, to be clear, you want to have this:

```
onClick={() => new Command("powershell", ["/C", "start https://google.com"]) }
```

use the app consumer's powershell to open the browser. (Just give a thumb's up if this is the case)

**Comment by nothingismagick** [comment]
The problem with the former (in my opinion) is that this will obviously ONLY work on Windows. I suppose if that is all that matters, then that's fine - but really, that is something you will be able to write yourself with a custom command.

**Comment by Ludea** [comment]
> So, to be clear, you want to have this:
> 
> ```
> onClick={() => new Command("powershell", ["/C", "start https://google.com"]) }
> ```
> 
> use the app consumer's powershell to open the browser. (Just give a thumb's up if this is the case)

I try to use powershell because `window.open ` is not working as expected (in my case).
I quickly try powershell, because I'm on Windows.
But It's not really a solution, I need it to be multi platform

**Comment by lucasfernog** [comment]
We have a dedicated API to open an URL on the default browser: https://tauri.studio/en/docs/api/js/modules/shell#open

And your command isn't doing anything because you didn't call SPAWN: https://tauri.studio/en/docs/api/js/classes/shell.command#spawn
(better docs with examples is coming on the next release).

We'll offer a way to make window.open use the default browser, see #1657

**Comment by zakhenry** [comment]
for anyone coming to this from a google search, the doc link is now https://v2.tauri.app/reference/javascript/shell/#open
