### ISSUE TITLE
`--quick` option for `cargo tauri build`

### ISSUE THREAD

**Issue by WilliamVenner** [tauri-apps/tauri#1732]
**Is your feature request related to a problem? Please describe.**
Build times are very long for Tauri apps.

My computer takes about 5 minutes to build my application. It doesn't sound like much, but when you're doing little changes or need to frequently build+test stuff in release mode, it can be very frustrating. Additionally, I have a very powerful system, so that build time is most likely much worse for more limited hardware.

**Describe the solution you'd like**
A `--quick` option for `cargo tauri build` that produces a release-built binary in the quickest time possible, sacrificing performance or convenience.

**Describe alternatives you've considered**
N/A

**Additional context**
I find myself wanting to test stuff such as build scripts, bundles and bugs in release mode frequently. However, I have to wait 5 minutes for my application to build in release mode, even with as many compilation speed optimizations in my Cargo.toml.

It would be great if whatever is slowing the build process down can be turned off using a command line option for `cargo tauri build` for quick testing.

**Comment by nothingismagick** [comment]
Once beta is no longer RC, then we should start investigating benchmarking on different systems. I am moving this issue to discussions so we can track it.
