### ISSUE TITLE
Expose `focus()` to Window

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tauri#1737]
**Is your feature request related to a problem? Please describe.**
Calling `win.show()` in the frontend does not bring the window (or at least not the app) to focus

**Describe the solution you'd like**
Electron handles this by having `win.show()` and `win.showInactive()`. I would personally prefer `win.show(focus: true)`

**Comment by lemarier** [comment]
Merged in https://github.com/tauri-apps/tao/pull/28
