### ISSUE TITLE
Error installing tauri CLI under Windows

### ISSUE THREAD

**Issue by houghtonap** [tauri-apps/tauri#1740]
**Describe the bug**

**To Reproduce**
1. Installed Windows prerequisites per [setup instrustions](https://tauri.studio/en/docs/getting-started/setup-windows)
2. cd project directory
3. `yarn init`
4. `yarn add @tauri-apps/cli`

**Expected behavior**
* installation of tauri cli

**Screenshots**
```txt
u:>yarn add @tauri-apps/cli
yarn add v1.22.10
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/4] ? optipng-bin
[2/4] ? pngquant-bin
[3/4] ? zopflipng-bin
error u:\Documents\Source\nodejs\tauri\node_modules\pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: u:\Documents\Source\nodejs\tauri\node_modules\pngquant-bin
Output:
‼ unable to get local issuer certificate
  ‼ pngquant pre-build test failed
  i compiling from source
  x Error: pngquant failed to build, make sure that libpng-dev is installed
    at u:\Documents\Source\nodejs\tauri\node_modules\execa\index.js:231:11
```

**Platform and Versions (please complete the following information):**

OS: Windows 7
Node: v13.14.0
NPM: 6.14.4
Yarn: 1.22.10
Rustc: 1.52.0 (88f19c6da 2021-05-03)

**Additional context**

**Stack Trace**

**Comment by lucasfernog** [comment]
pngquant will be removed on the next release, see https://github.com/tauri-apps/tauri/pull/1678

Please reopen if it still doesn't work.
