### ISSUE TITLE
tauri-cli fails if TAURI_PRIVATE_KEY is not set

### ISSUE THREAD

**Issue by danielvschoor** [tauri-apps/tauri#1791]
**Describe the bug**
If the pub key in tauri.conf.json is set, the tauri-cli fails with exit code 1 if the TAURI_PRIVATE_KEY is not set. This is different than how it used to work, where it would just skip signing the artifacts. This makes it difficult to run the testing workflow on tauri-action, since secrets are not passed to PRs from external forks.

**To Reproduce**
1. Set a pub key in tauri.conf.json under `updater`
2. Ensure you don't have the TAURI_PRIVATE_KEY env var set
3. Run `yarn tauri build`

**Expected behavior**
An error(maybe a warning?) message indicating that TAURI_PRIVATE_KEY is not set, but a 0 return code from the CLI

**Platform and Versions (please complete the following information):**

OS: Windows 10 (but fails on all OS'es)
Node: 14.16.1
NPM: 6.14.12
Yarn: 1.22.10
Rustc: 1.52.1

**Additional context**

**Stack Trace**
info: running light to produce C:\Users\path\aiarena-client-GUI\src-tauri\target\release\bundle/msi/aiarena-client-gui_0.2.3_x64.msi
    Bundling "C:\\Users\\path\\aiarena-client-GUI\\src-tauri\\target\\release\\bundle/msi/aiarena-client-gui_0.2.3_x64.msi.zip"
    Finished 2 bundles at:
        C:\Users\path\aiarena-client-GUI\src-tauri\target\release\bundle/msi/aiarena-client-gui_0.2.3_x64.msi
        C:\Users\path\aiarena-client-GUI\src-tauri\target\release\bundle/msi/aiarena-client-gui_0.2.3_x64.msi.zip (updater)
Error: A public key has been found, but no private key. Make sure to set `TAURI_PRIVATE_KEY` environment variable.

 app:spawn Command "C:\Users\path\aiarena-client-GUI\node_modules\@tauri-apps\cli\bin\tauri-cli.exe" failed with exit code: 1 +0ms
error Command failed with exit code 1.

**Comment by lemarier** [comment]
Thanks for reporting.

The bug comes from here: (Error should be catched)
https://github.com/tauri-apps/tauri/blob/fcee4c25fc2e83a587e096b26d9f7c374c3db057/tooling/cli.rs/src/helpers/updater_signature.rs#L172

I'll make a PR to fix it.

**Comment by lemarier** [comment]
See my comment here:
https://github.com/tauri-apps/tauri/pull/1797#issuecomment-839731469

Closing for now

Thanks for reporting tho!

**Comment by GeckoEidechse** [comment]
I have the same issue but in my case no `pubkey` is set, i.e.

```json
...
    "updater": {
      "active": true,
      "pubkey": "",
      "endpoints": [
        "<my URI>"
      ],
      "dialog": true
    },
...
```

see also

- https://github.com/GeckoEidechse/FlightCore/commit/6dab771e6109725045cbd81f840717b0a43a33c0
- https://github.com/GeckoEidechse/FlightCore/runs/8037880844?check_suite_focus=true#step:6:553

**Comment by FabianLars** [comment]
@GeckoEidechse The pubkey is required.

**Comment by GeckoEidechse** [comment]
> @GeckoEidechse The pubkey is required.

Hmm, this going off-topic now but is there actually a way then to use the built-in auto-updater without having to sign the binaries?

When developing a small open-source application for only a handful of users, investing into a code signing certificate is simply not feasible unfortunately :/

**Comment by FabianLars** [comment]
The updater signature is not related to code signing. You just need to set up a key via tauri's cli, see <https://tauri.app/v1/guides/distribution/updater#signing-updates> (it's free and built-in) and it will automatically sign the updater bundle on each build.
It's just to verify that the updater bundle the app downloaded is the same file announced by the updater json file.
Think of it as a similar mechanism to the sha256 checksum that some websites show on their download page that users can use to verify the file they downloaded from some CDN.
