### ISSUE TITLE
unresolved import `crate::api::PackageInfo`

### ISSUE THREAD

**Issue by dibadibadiudiu** [tauri-apps/tauri#1792]
**Describe the bug**
After upgrading to tauri-1.0.0-beta.0
error[E0432]: unresolved import `crate::api::PackageInfo`
--> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.0-beta.0/src/manager.rs:10:5

error[E0412]: cannot find type `PackageInfo` in module `crate::api`
no `PackageInfo` in `api`
fn package_info() -> crate::api::PackageInfo;
not found in `crate::api`

**To Reproduce**

cd src-tauri
cargo update -p tauri
yarn tarui dev

**Platform and Versions (please complete the following information):**

Operating System - Mac OS, version 11.2.3 X64 M1

Node.js environment
  Node.js - 15.8.0
  @tauri-apps/cli - 1.0.0-beta-rc.4
  @tauri-apps/api - 1.0.0-beta-rc.3

Global packages
  npm - 7.5.1
  yarn - 1.22.10

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

**Comment by dibadibadiudiu** [comment]
resolved
1.delete file src-tauri/cargo.lock
2. Run `yarn tauri dev`

**Comment by ThibsG** [comment]
Just had the same problem:
```
error[E0432]: unresolved import `tauri::Invoke`
 --> src/plugins/myplugin.rs:3:10
  |
3 |     App, Invoke, Params,
  |          ^^^^^^ no `Invoke` in the root
```
and your solution worked like a charm, thanks!
