### ISSUE TITLE
Tauri app using 100% CPU on ubuntu 20

### ISSUE THREAD

**Issue by olup** [tauri-apps/tauri#1813]
**Describe the bug**
The app in dev mode OR once built uses 100% of CPU on my ubuntu 20 machine

**To Reproduce**
I just started a new tauri project according to the docs, with version beta.1

**Expected behavior**
veru small cpu usage

**Screenshots**

**Platform and Versions (please complete the following information):**
```
Operating System - Ubuntu, version 20.10 X64

Node.js environment
  Node.js - 14.15.5
  @tauri-apps/cli - 1.0.0-beta.1
  @tauri-apps/api - 1.0.0-beta.1

Global packages
  npm - 6.14.11
  yarn - 1.22.10

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/public
/build
/node_modules
/.git
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.1
build-type - bundle
CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
distDir - ../build
devPath - http://localhost:4000
framework - React
```
**Additional context**
`libwebkit2gtk-4.0-dev is already the newest version (2.32.0-0ubuntu0.20.10.1)`

**Comment by nothingismagick** [comment]
this is quite strange, because it appears your dependencies are correct. can you clone the repo and run the API example?

**Comment by nklayman** [comment]
I just tested on my Ubuntu 20 machine with a fresh project and have no issues whatsoever.

**Comment by olup** [comment]
Installing the api examples throws after compiling tauri : 
```
Tauri Rust CLI installed. Run it with '$ cargo tauri [COMMAND]'.
Do you want to install the Node.js CLI?
.scripts/setup.sh: 18: Syntax error: "do" unexpected
```

Then `chalk` is not installed

**Comment by olup** [comment]
Ok, did what the script should have done, will revert with results.

**Comment by olup** [comment]
The API example app started building, downloading crates. then it failed on 
```
  --- stderr
  `"pkg-config" "--libs" "--cflags" "gtksourceview-3.0" "gtksourceview-3.0 >= 3.0"` did not exit successfully: exit code: 1
  --- stderr
  Package gtksourceview-3.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gtksourceview-3.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gtksourceview-3.0' found
  Package gtksourceview-3.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gtksourceview-3.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gtksourceview-3.0' found
```

Will try to fix an revert.

**Comment by olup** [comment]
Installed `libgtksourceview-3.0-1`, the build goes further, than ends up with no details `build failed`

**Comment by olup** [comment]
Fresh clean project - still running 100% cpu.
@nothingismagick Could start the api: example. Where should I find the build logs to get the error detail ?

**Comment by olup** [comment]
Ok, did finally build the API example. Example running at 100% CPU....

**Comment by olup** [comment]
@nklayman are you also running ubntu 20.10 ?

**Comment by nklayman** [comment]
Yep.

**Comment by yoroshikun** [comment]
I am also getting this bug running on 
```
Operating System: Garuda Linux
KDE Plasma Version: 5.21.5
KDE Frameworks Version: 5.82.0
Qt Version: 5.15.2
Kernel Version: 5.11.16-zen1-1-zen

Garuda is arch-based
```
is reproducible with just setting up new tauri app with [create-tauri-app](https://github.com/tauri-apps/tauri/tree/dev/tooling/create-tauri-app) I'm not sure if it matters but I am using the vite setup with preact-ts

It also seems to be hogging virtual memory below is example of htop
![image](https://user-images.githubusercontent.com/1892447/118224388-332a5700-b4c2-11eb-8d63-f9e6c6f83c55.png)


Let me know if there is any more information I can give to help with this bug

**Comment by lucasfernog** [comment]
@olup we made some changes that probably fixes this, can you try pulling latest `dev` changes and run the API example again?

**Comment by olup** [comment]
Sorry, yes indeed i haven't had the 100% cpu thing for a little while using the dev branch. I thought I notified it on discord, but I should have closed this issue.
