### ISSUE TITLE
Support system tray without menu

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tauri#1818]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to click the system tray icon without a menu showing up, and be able to react to that.

**Describe the solution you'd like**
`.system_tray(vec![])` could be used to show the system tray icon, and `.on_system_tray_click(|app| {})` could be used to react to the click

**Comment by lemarier** [comment]
It’s in the roadmap but we want to stabilize the tray api before.
It should be available within few weeks.
