### ISSUE TITLE
[docs] JS API WindowOptions `transparent` missing

### ISSUE THREAD

**Issue by halgorithm** [tauri-apps/tauri#1819]
Windows in `tauri.conf.json` can made transparent, and windows created through the JS API can be as well. However, `WindowOptions` does not mention a `transparent` option.
https://tauri.studio/en/docs/api/js/interfaces/window.windowoptions/

**Comment by lucasfernog** [comment]
Seems like the TS docs is really outdated, what happened @Laegel ?

**Comment by lucasfernog** [comment]
Docs was updated: https://tauri.studio/en/docs/api/js/interfaces/window.windowoptions/#transparent
