### ISSUE TITLE
Add a Window method to center the window

### ISSUE THREAD

**Issue by danielvschoor** [tauri-apps/tauri#1822]
**Is your feature request related to a problem? Please describe.**
My splash screen is not centered when my app launches. I’ve worked around it for now by hardcoding the position to the center of a 1920x1080 display. This will not be centered on 4K or other displays

**Describe the solution you'd like**
A method on the Window struct called ‘set_position_center()’ or ‘center()’ that centres the window based on the the actual screen size and the window size.

**Describe alternatives you've considered**

**Additional context**

I’m just creating this issue for tracking, I might even give this feature a go myself when I get some spare time

**Comment by nothingismagick** [comment]
Thanks @danielvschoor - technically this issue should probably be resolved at the https://github.com/tauri-apps/wry layer - but I will let @wusyong decide how he wants to handle that.
