### ISSUE TITLE
How can I get my splash screen to work in development mode?

### ISSUE THREAD

**Issue by happyshovels** [tauri-apps/tauri#1837]
Hi I am currently trying to get a splash screen for my application. 

So far I followed the docs https://tauri.studio/en/docs/guides/splashscreen. The splashscreen works as expected when I build the app for production, but when I start the app with tauri dev I get a segmentation fault (I think this happens when the close_splashscreen is invoked). Also I do not see the splash screen opening so I assume this is somehow related. my dev workflow is as follows:
 1) cd frontend && yarn serve -> to open a vue.js app on localhost:8080
2) cd src-tauri && yarn tauri dev -> to start the tauri app in development mode

is there I way i can have my splashscreen also in dev?

this is the code i am currently using: https://github.com/happyshovels/double-shovel/tree/c23208766f1a555d017635fc7f0f36943d4955d1

my tauri info:
```
Operating System - Mac OS, version 10.15.7 X64

Node.js environment
  Node.js - 16.1.0
  @tauri-apps/cli - 1.0.0-beta.1
  @tauri-apps/api - 1.0.0-beta-rc.3

Global packages
  npm - 7.11.2
  yarn - 1.22.10

Rust environment
  rustc - 1.52.0
  cargo - 1.52.0

App directory structure
/frontend
/node_modules
/output
/src-tauri
/.git

App
  tauri.rs - 1.0.0-beta.1
build-type - bundle
CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
distDir - ../frontend/dist
devPath - http://localhost:8080
```

thank you for your help :)

**Comment by happyshovels** [comment]
It works when I use `cargo run` in src-tauri instead of `yarn tauri dev`

**Comment by nothingismagick** [comment]
So a couple things i noticed:
Rustc should be at 1.52.1
Api should be beta.1

**Comment by happyshovels** [comment]
Hi, thanks for the review :) I updated rustc 1.52.1 and the api to beta.1. Unfortunately, the issue still persists...

**Comment by happyshovels** [comment]
Actually I only needed the splashscreen to come around the white background issue ().

I found another workaround for this 

```
.setup(|app| {

      let main_window = app.get_window("main").unwrap();
      // we perform the initialization code on a new task so the app doesn't freeze
      tauri::async_runtime::spawn(async move {
        sleep(Duration::from_millis(500));
        main_window.show().unwrap();
      });

      Ok(())
    })
```
and win the tauri.conf.json
```
"windows": [
  {
    ...
    "visible": false
  }
]
```

As this solved my original problem I will close this issue. thanks :)
