### ISSUE TITLE
failed to run custom build command for `glib-sys v0.10.1`

### ISSUE THREAD

**Issue by edu-live** [tauri-apps/tauri#1838]
error: failed to run custom build command for `glib-sys v0.10.1`

  --- stderr
  `"pkg-config" "--libs" "--cflags" "glib-2.0" "glib-2.0 >= 2.44"` did not exit successfully: exit code: 1
  --- stderr
  Package glib-2.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `glib-2.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'glib-2.0' found
  Package glib-2.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `glib-2.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'glib-2.0' found

**Comment by nothingismagick** [comment]
I hate to be a pedant, but would you mind please giving more information about your OS, etc.
We do have an issue template because it helps us understand exactly the scope of the issue.

**Comment by edu-live** [comment]
> I hate to be a pedant, but would you mind please giving more information about your OS, etc.
> We do have an issue template because it helps us understand exactly the scope of the issue.

thank you, I solve it: 
sudo add-apt-repository universe
do i have to install tauri-bundler ? 
it's not in  the doc .

**Comment by nothingismagick** [comment]
tauri-bundler is now a library and is managed via the CLI - you don't have to install it alone anymore.

**Comment by makorne** [comment]
@nothingismagick

Just installed all from  [tauri.studio/en/docs/get-started/setup-linux](url)
 and tried [https://github.com/tauri-apps/vue-cli-plugin-tauri/](url)
The same issue...

`error: failed to run custom build command for `glib-sys v0.10.1``

rustc 1.53.0 (53cb7b09b 2021-06-17)
fedora 34 xfce
tauri-bundler   0.9.4

**Comment by nothingismagick** [comment]
Your system is VERY out of date @makorne. Please update Rust and tauri-bundler (and i am assuming all of your other tauri deps). Please visit our discord for more information about how to do this.

**Comment by makorne** [comment]
I updated to the latest stable rust (from  a VERY old one, 1 month older :)
Now I have `stable-x86_64-unknown-linux-gnu updated - rustc 1.54.0 (a178d0322 2021-07-26)`
and did `cargo update, cargo install tauri-bundler --force`

But still the same tauri-bundler version and same issue.

Looks like ` tauri.studio/en/docs/getting-started/setup-linux` with 
```
rustc --version
latest update on 2019-12-19, rust version 1.40.0
```
should be updated and needs the right info about installation.

Ok, I will try discord. 
But the right info on setup page would be better for all users.

**Comment by FabianLars** [comment]
The problem is not the setup page (although 1.40 could actually be too old idk), but rather the instructions in the vue-cli-plugin-tauri readme or the plugin itself. Both are somewhat outdated.
- you don't need tauri-bundler anymore => uninstall it straight away, just in case
- if the plugin doesn't work without it (don't know how vue plugins work, but tauri-bundler is still mentioned in the generator file) i'd suggest to not use the plugin at all for now.

**Comment by nothingismagick** [comment]
@nklayman - can you take a look at your vue-cli-plugin documentation again and make sure its beta compatible?

**Comment by nklayman** [comment]
Sorry, forgot to update it. It should be all good now, I removed references to tauri-bundler and updated the tauri-cli version.
