### ISSUE TITLE
Error decoding response body

### ISSUE THREAD

**Issue by eneroth** [tauri-apps/tauri#1840]
I try to call an endpoint that produces a [Transit](https://github.com/cognitect/transit-format) response, so the encoding is `application/transit+json`. I use the `@tauri-apps/api/http` API.

To send the request, I serialize the payload into a string, set it as `Text`, and send it off. The full headers I use is:

```
{"Accept"          "application/transit+json"
 "Content-Type"    "application/transit+json"
 "Accept-Encoding" "gzip, deflate"}
```

I get the following error: `"failed to execute API: Network Error: error decoding response body: expected value at line 1 column 1"`

Switching `"Accept"` to receive `"application/json"` returns the result as expected, but is inadequate, as JSON supports a very limited range of types, and therefore type information is lost. I need to receive the Transit encoded response intact. 

This might be considered a bug if the middleware makes assumptions about the payload, a JSON decoder kicks in when it shouldn't (perhaps on account of `json` being present in the header value `"application/transit+json"`), or it might be that I'm not using the API appropriately.

**To Reproduce**
1. Use a `getClient` request to receive a `application/transit+json` encoded response.

**Expected behavior**
Tauri should not attempt to decode the response body for unknown content-types.

**Platform and Versions (please complete the following information):**
OS: MacOS (Big Sur, M1)
Node: 14.17.0
NPM: 6.14.13
Yarn: 1.22.10
Rustc: 1.52.1

**Comment by lucasfernog** [comment]
The response deserialization is defined by the [`ResponseType enum`](https://tauri.studio/en/docs/api/js/enums/http.responsetype), which defaults to JSON. As you can see we only support JSON, byte array and string, so you could either try parsing a byte array or writing your own API.

Maybe we could also add a feature flag for transit support.
