### ISSUE TITLE
Blank window on windows 10.

### ISSUE THREAD

**Issue by samirdjelal** [tauri-apps/tauri#1843]
**Describe the bug**
Blank window on windows 10.

**To Reproduce**
You can try a ready project if you want: https://github.com/samirdjelal/bidirectional
1. Build for Windows.
2. Copy the binary to a new **Windows 10** machine, (Windows Sandbox in my case)
3. Install **Visual C++ Redistributable Runtimes** as it is required by Tauri.
4. Launch the app, and see error.

**Expected behavior**
It should render the page in the WebView.

**Screenshots**
This screenshot is taken from a debug build.
![image](https://user-images.githubusercontent.com/25848885/118425467-2aec3a80-b6c1-11eb-89f5-5d7771d04fb0.png)

And this is the interface in the development machine.
![image](https://user-images.githubusercontent.com/25848885/118425556-52430780-b6c1-11eb-9b14-2b45662d1dac.png)

**Platform and Versions (please complete the following information):**

**_Note: this error has occurred in Windows Sandbox that is integrated with Windows 10 ( Windows_NT 10.0.19042 )_**

OS: Windows_NT(10.0.19042) - win32/x64
Node: 12.18.3
NPM: 6.14.6
Yarn: 1.22.10
Rustc: 1.47.0
tauri.js - 0.14.1
cargo - 1.47.0
tauri-bundler - 0.9.4

**Comment by nothingismagick** [comment]
you are way out of date @samirdjelal - we are running the beta version now, and this problem should no longer exist.
Please consult https://tauri.studio/en/docs/development/updating for help upgrading.

**Comment by samirdjelal** [comment]
It seems that the beta version required webview2 to be installed in the machine, that's additional 100MB to be downloaded!

**Comment by nothingismagick** [comment]
Yeah, its just once per device
