### ISSUE TITLE
Rename the processes in Taskmanager

### ISSUE THREAD

**Issue by NenoxAG** [tauri-apps/tauri#1849]
**Is your feature request related to a problem? Please describe.**
I would like to choose the process name ("A Tauri App" and "Tauri App", maybe also "Microsoft Edge WebView2") that is shown in Taskmanager to make the app look more "professional". If it is possible to rename the "Microsoft Edge WebView2" process, i would also like to change the icon of it.

**Describe the solution you'd like**
A setting called process name under the Windows specific settings.

**Describe alternatives you've considered**
Maybe just use the productName

**Additional context**
<img src="https://i.imgur.com/0eGMFeU.png">

**Comment by amrbashir** [comment]
1. we don't control `Microsoft Edge WebView2` so we can't change that.
2. `Tauri App` is just the window title, so you can change that either in your `tauri.conf.json` or programmatically through our api either from rust or js
3. `A Tauri App` is picked up from the `description` field in your `src-tauri/cargo.toml`, not sure if we are doing that intentionally or is it from `cargo`, so I will ping @lucasfernog

**Comment by lucasfernog** [comment]
I think cargo does that but we should see about overriding it with the config.

**Comment by lucasfernog** [comment]
[winres](https://docs.rs/winres/0.1.11/winres/struct.WindowsResource.html#method.new) is responsible for it. I'm making a PR to pull the info from `tauri.conf.json > package` instead, but we can also add setters to customize it if you need.

**Comment by NickyAlan** [comment]
You can change it by "shortDescription"
![image](https://github.com/tauri-apps/tauri/assets/97141979/ccd7e629-f4c5-443d-a5cf-3a904a9a908d)
![image](https://github.com/tauri-apps/tauri/assets/97141979/65aa548e-0811-4142-8742-487f62d9f83d)
