### ISSUE TITLE
The WebView wont start quick enough to display the splashscreen

### ISSUE THREAD

**Issue by NenoxAG** [tauri-apps/tauri#1850]
**Describe the bug**
When you start the app (one with a splashscreen) the splashscreen will just be white for some time and then the app will kick in.

**To Reproduce**
1. Create a app with splash screen using the tutorial
2. Open the app

**Expected behavior**
The splashscreen should be displayed from the beginning

**Visuals**

This is how the splashscreen should look like:
![Screenshot](https://user-images.githubusercontent.com/63405129/118535388-b231c080-b74a-11eb-860d-305763de0ad4.PNG)

And this is how it gets displayed:

https://user-images.githubusercontent.com/63405129/118535386-b1992a00-b74a-11eb-811c-1ca88303e1bd.mp4

**Platform and Versions (please complete the following information):**
OS: Windows 10, 10.0.19042 x64
Webview2: 90.0.818.62
Node: 16.0.0
NPM: 7.13.0
Rustc: 1.51

**Comment by nothingismagick** [comment]
Does the text just not render at all, or is it just not fast? Can you lengthen the timeout?

**Comment by nothingismagick** [comment]
On a side note, we have seen terrible performance on the latest evergreen versions of the WebView2 on very high performance devices.

**Comment by NenoxAG** [comment]
It renders, but it renders really late. Can anything be done about it?

**Comment by nothingismagick** [comment]
Try an image? Wait for MS to fix their mistake?

**Comment by NenoxAG** [comment]
Using an image makes no difference. I think I'll wait then
