### ISSUE TITLE
javascript: window.open()   Don't work

### ISSUE THREAD

**Issue by mxismean** [tauri-apps/tauri#1857]
"vue-cli-plugin-tauri": "~1.0.0-beta.2",
"@tauri-apps/cli": "^1.0.0-beta.2",

Tauri that I plugged into the Vue project,
The    @@@'window.open' method is executed in js, but does not work

**Comment by mxismean** [comment]
@zuckschwerdt @deftsp @liusong1111 @roryok  Please help me, thank you

**Comment by nothingismagick** [comment]
@mxismean - why did you ping these people? They are not (to the best of my knowledge) involved in tauri

**Comment by nothingismagick** [comment]
do you want to open a new tauri window?
look here: https://tauri.studio/en/docs/api/js/classes/window.webviewwindow

**Comment by mxismean** [comment]
> do you want to open a new tauri window?
> look here: https://tauri.studio/en/docs/api/js/classes/window.webviewwindow

I want to open it in a local browser. Can't I use window.open?

**Comment by mxismean** [comment]
> do you want to open a new tauri window?
> look here: https://tauri.studio/en/docs/api/js/classes/window.webviewwindow

I want to open it in a local browser. Can't I use window.open?

**Comment by lucasfernog** [comment]
Check the shell open API: https://tauri.studio/en/docs/api/js/modules/shell#open

Using `window.open` is being tracked on issue #1657

**Comment by mxismean** [comment]
Thanks
