### ISSUE TITLE
Making Tauri useable as GUI for VST plugins

### ISSUE THREAD

**Issue by Boscop** [tauri-apps/tauri#1872]
It would be great if Tauri could be used for making GUIs for VST plugins (at least on Windows).
1. This requires being able to create the WebView2 window [as a child window on the parent window](https://docs.rs/winit/0.25.0/i686-pc-windows-msvc/winit/platform/windows/trait.WindowBuilderExtWindows.html#tymethod.with_parent_window) whose handle the [VST host passes in](https://docs.rs/vst/0.2.1/vst/editor/trait.Editor.html#tymethod.open):

2. It also requires not taking control of the event loop but yielding control back to the host every frame:
In [`Editor::idle()`](https://docs.rs/vst/0.2.1/vst/editor/trait.Editor.html#method.idle), the VST would call [`run_return`](https://github.com/tauri-apps/tao/blob/c280f2b8a1d0eb6469660b5f86c594147ba2b23e/src/platform/run_return.rs#L38) (instead of calling `run` once and relinquishing control) and the host calls `Editor::idle()` every frame.

Links to (outdated) prior art:
https://github.com/vanderlokken/rust-vst-gui (uses IE's engine, so no Wasm, windows-only)
https://github.com/Boscop/winit (very outdated winit fork)
https://github.com/Boscop/glutin (even more outdated glutin fork, from before winit existed)
https://github.com/monomadic/dd-core (prototype for mac, also outdated)
(I think there was also a crate that did this for linux, but I don't remember the name.)

Currently there is no working & up-to-date cross-platform solution to create GUIs for VST plugins.
Tauri seems to be the most promising option :)

**Comment by schell** [comment]
So where did this net out? It looks like some work was done but it never got mainlined?

**Comment by toovy** [comment]
@Boscop did you look further into the VST plugin compatibility? I would also be interested in the other way around, not really knowing where to start.

**Comment by ricardomatias** [comment]
Is there any sample/example out there for using Tauri as VST GUI?

**Comment by stellanhaglund** [comment]
Also interested!

**Comment by AZProductions** [comment]
Any updates?

**Comment by Vestibule** [comment]
Interested in this!

**Comment by AZProductions** [comment]
> Is there any sample/example out there for using Tauri as VST GUI?

https://github.com/maxjvh/nih-plug-webview uses a fork of wry to build vst3 plugins with [nih-plug](https://github.com/robbert-vdh/nih-plug)

**Comment by Timtam** [comment]
I'll still have to test nih-plug-webview, but I want to follow here as having the entire Tauri stack at our disposal, including all plugins that already exist, would be amazing! Hope someone gets to do it at some point. Really looking forward to it.

**Comment by poucet** [comment]
What's the status of this? It's marked as closed but I don't see any resolution. I'd love to pick this up.

**Comment by Mixomo** [comment]
Any update? 👀

**Comment by poucet** [comment]
I just got it to work with wry: https://github.com/poucet/simply-vst/
