### ISSUE TITLE
MacOS Global Shortcut captures keyboard events even when Window is not focused

### ISSUE THREAD

**Issue by kestred** [tauri-apps/tauri#1873]
**Describe the bug**
On MacOS (11.13), when a Global Shortcut is registered, it continues to captures keyboard events even when the Tauri application window is not focused/active.

**To Reproduce**
1. Register a global shortcut using javascript; e.g.
    ```
    import { register} from '@tauri-apps/api/globalShortcut';
    register("Enter", function() { console.log('captured'); });
    ```
2. Run the tauri app with `yarn tauri dev`
2. Wait for the window to open.
3. Switch to a different application (e.g. `Safari` or `VSCode`).
4. Observe that pressing the registered keyboard shortcut isn't set to the other app.

**Expected behavior**
Keyboard shortcuts should only be captured when the application is focused.
(Alternatively, there should be a way to configure a keyboard shortcut to always trigger or only trigger when the app is focused).

**Platform and Versions (please complete the following information):**

OS: Mac OS, version 11.3.0 X64
Node: v14.16.1
NPM: 6.14.12
Yarn: 1.22.10
Rustc: 1.52.1
Tauri:
```
  tauri.rs - 1.0.0-beta.1
  @tauri-apps/cli - 1.0.0-beta.1
  @tauri-apps/api - 1.0.0-beta.1
```

**Comment by lucasfernog** [comment]
That's why it's called `global` shortcut :) if you want a shortcut trigger only when the window is focused, maybe you can use some JS library like this: https://github.com/jaywcjlove/hotkeys

**Comment by kestred** [comment]
😆, ok fair point.

@lucasfernog one reason I was trying to do so is that using keyboard input events in the web view triggers the system bell sound and the global shortcut would disable it.  Do you know if there is a better way to notify the system that the shortcut is being handled?

**Comment by lucasfernog** [comment]
I have no idea, maybe @lemarier can help

**Comment by lemarier** [comment]
We’ll work on this, next week;
https://github.com/tauri-apps/tao/issues/33

Please follow the issue, we may be able to bring something you could use.

**Comment by kitty-eu-org** [comment]
Is there any progress on this issue so far? I encountered the same problem. I am using tauri-v2. Currently, I have bound command + W to hide the main window (I only have this one window). However, when I use this shortcut key in other software, it should originally The closed tab is not closed because Tauri captures the global shortcut key.my system is macos

**Comment by FabianLars** [comment]
No progress as there's no issue left here. _global_ shortcuts are _global_.
It sounds like you just don't want a global shortcut, in which case the aforementioned js event listeners would work (now without the sound bug), or a window menu shortcut/accelerator (similar to the default cmd+w that closes the window).

**Comment by kitty-eu-org** [comment]
menu shortcut/accelerator doesn't work here，this is my code:
https://github.com/fagao-ai/kitty/blob/10a109b27a0aa0acaf3275c2b20acd5843a0c465/src-tauri/src/tray.rs#L17
Is my usage wrong?

**Comment by FabianLars** [comment]
That's a tray menu not a window/app menu. I don't know if they're supposed to work here myself to be honest.

**Comment by kitty-eu-org** [comment]
I saw this api，so i used it，but it didn't work，what is window accelerator？ How to use？

**Comment by FabianLars** [comment]
We didn't port the menu guides over to v2 yet but the v1 docs are here: https://tauri.app/v1/guides/features/menu and the migration guide is here: https://beta.tauri.app/guides/upgrade-migrate/from-tauri-1/#migrate-to-menu-module

**Comment by kitty-eu-org** [comment]
Oh，i will try，thank you
