### ISSUE TITLE
Dialog window doesn't take focus

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#1876]
**Describe the bug**
If I open a dialog it moves freely and the main window doesn't get blocked in any way.

**To Reproduce**
1. Open a Dialog

**Expected behavior**
The dialog should prevent access to the main window while open

**Platform and Versions (please complete the following information):**

OS: Windows, version 10.0.19042 X64
Node: 14.15.4
NPM: 6.14.10
Yarn: 1.22.10
Rustc: 1.51.0

**Minimal Example**
Using Svelte
```svelte
<script>
  import { open } from "@tauri-apps/api/dialog";
</script>

<button on:click={() => open()}>Test</button>
```

**Comment by lucasfernog** [comment]
Will be fixed when (and if) https://github.com/PolyMeilex/rfd/pull/14 is merged and published.

**Comment by ghost** [comment]
Out of curiosity, there is also a bug where the dialog window spawns below all other windows most of the time. Would this be fixed as well with this change?

**Comment by lucasfernog** [comment]
I hope it will, since we'll set the tauri window as parent of the dialog, I think Windows will handle that.
