### ISSUE TITLE
Poor interfacing performance - dev or build

### ISSUE THREAD

**Issue by olup** [tauri-apps/tauri#1877]
**Describe the bug**
Reading a simple txt file will take a mere ms for rust, but half a second of a full second to get the content in js - and the thrad is blocked, so UI becomes unresponsive and static.

This is worst in dev, but is also present in released builds.

Probably linked to https://github.com/tauri-apps/tauri/issues/1817

I have been advised on Discord that performances where no so good on Linux, however I think this deserves an issue. Serializing / deserializing shouldn't be much different on different platforms.

**To Reproduce**
**Expected behavior**
**Screenshots**
**Platform and Versions (please complete the following information):**
```
Operating System - Ubuntu, version 20.10 X64

Node.js environment
  Node.js - 14.15.5
  @tauri-apps/cli - 1.0.0-beta.1
  @tauri-apps/api - 1.0.0-beta.1

Global packages
  npm - 6.14.11
  yarn - 1.22.10

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/public
/build
/node_modules
/.git
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.1
build-type - bundle
CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
distDir - ../build
devPath - http://localhost:4000
framework - React
```

**Comment by lucasfernog** [comment]
We're tracking improvements [here](https://github.com/tauri-apps/wry/issues/253). Does it take 1 second to receive the data on a release build too?

**Comment by olup** [comment]
The poor performance seems unrelated to serializing - I get this whatever the form or size of what is returned.

Even if I don't return anything from the rust command, the js promise can still take a very long time to resolve.
In DEV mode or with the BUILT product It can go up to 6 seconds. And never less thant 600-ish miliseconds. The rust operations ends up under a milisecond, of course.

**Comment by olup** [comment]
Another one - fresh project.

Reading a text file using tauri api, again an again - the built app will tale anything from a few milliseconds to 4 or even 6 seconds !

I guess the weird factor is the large randomness of it. Is there any ways for me to log debugs info from rust to track the perf timings ?

To me this is a bug, not an improvement, don't you think ?
