### ISSUE TITLE
Can't load files with spaces in build

### ISSUE THREAD

**Issue by aleksanderkoder** [tauri-apps/tauri#1879]
Images referenced in Vue components do not show up in release build gotten by doing "yarn tauri:build". The images do show up in the dev build gotten with "yarn tauri:serve". 

Tauri info:
![tauri info](https://user-images.githubusercontent.com/49065176/118661055-1017e400-b7ef-11eb-9943-55cd5ce8cee7.JPG)

Dependencies:
![pak info](https://user-images.githubusercontent.com/49065176/118661354-52412580-b7ef-11eb-94fe-534519d1274b.JPG)

**Comment by aafnnp** [comment]
> It seems like the custom protocol doesn't support files with spaces in the names...we'll definitely need to fix this.

same problem
https://github.com/Manonicu/remix
branch dev
