### ISSUE TITLE
error: failed to run custom build command for `app v0.1.0 (C:\Users\BillionWeb\Desktop\web\w-pc-bb-nav\src-tauri)`

### ISSUE THREAD

**Issue by mxismean** [tauri-apps/tauri#1884]
DONE  Compiled successfully in 3438ms上午11:22:22
<s> [webpack.Progress] 100%
  App running at:
  - Local:   http://localhost:8081/
  - Network: http://192.168.6.154:8081/
  Note that the development build is not optimized.
  To create a production build, run yarn build.
 app:spawn Running "C:\Users\BillionWeb\Desktop\web\w-pc-bb-nav\node_modules\@tauri-apps\cli\bin\tauri-cli.exe tauri dev --config {"build":{"devPath":"http://localhost:8081/"}}" +0ms
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.26
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.72
   Compiling autocfg v1.0.1
   Compiling winapi v0.3.9
   Compiling libc v0.2.94
   Compiling serde_derive v1.0.126
   Compiling serde v1.0.126
   Compiling lazy_static v1.4.0
   Compiling log v0.4.14
   Compiling getrandom v0.1.16
   Compiling ppv-lite86 v0.2.10
   Compiling jobserver v0.1.22
   Compiling proc-macro-hack v0.5.19
   Compiling siphasher v0.3.5
   Compiling memchr v2.4.0
   Compiling itoa v0.4.7
   Compiling version_check v0.9.3
   Compiling matches v0.1.8
   Compiling scopeguard v1.1.0
   Compiling byteorder v1.4.3
   Compiling bitflags v1.2.1
   Compiling smallvec v1.6.1
   Compiling pin-project-lite v0.2.6
   Compiling getrandom v0.2.2
   Compiling rayon-core v1.9.0
   Compiling futures-core v0.3.15
   Compiling tinyvec_macros v0.1.0
   Compiling ryu v1.0.5
   Compiling new_debug_unreachable v1.0.4
   Compiling ntapi v0.3.6
   Compiling mac v0.1.1
   Compiling percent-encoding v2.1.0
   Compiling precomputed-hash v0.1.1
   Compiling dtoa v0.4.8
   Compiling serde_json v1.0.64
   Compiling utf-8 v0.7.6
   Compiling proc-macro-nested v0.1.7
   Compiling futures-sink v0.3.15
   Compiling futures-task v0.3.15
   Compiling futures-channel v0.3.15
   Compiling either v1.6.1
   Compiling typenum v1.13.0
   Compiling crc32fast v1.2.1
   Compiling convert_case v0.4.0
   Compiling zstd-safe v4.1.0+zstd.1.5.0
   Compiling nodrop v0.1.14
   Compiling fnv v1.0.7
   Compiling stable_deref_trait v1.2.0
   Compiling pin-utils v0.1.0
   Compiling adler v1.0.2
   Compiling slab v0.4.3
   Compiling thin-slice v0.1.1
   Compiling futures-io v0.3.15
   Compiling adler32 v1.2.0
   Compiling once_cell v1.7.2
   Compiling hashbrown v0.9.1
   Compiling pkg-config v0.3.19
   Compiling httparse v1.4.1
   Compiling weezl v0.1.5
   Compiling unicode-xid v0.0.4
   Compiling native-tls v0.2.7
   Compiling webview2-sys v0.1.0
   Compiling try-lock v0.2.3
   Compiling quote v0.3.15
   Compiling color_quant v1.1.0
   Compiling tao v0.2.6
   Compiling anyhow v1.0.40
   Compiling subtle v2.4.0
   Compiling regex-syntax v0.6.25
   Compiling arrayref v0.3.6
   Compiling widestring v0.4.3
   Compiling unicode-segmentation v1.7.1
   Compiling wry v0.9.4
   Compiling arrayvec v0.5.2
   Compiling bitflags v0.9.1
   Compiling tauri-hotkey-sys v0.1.2
   Compiling ucd-trie v0.1.3
   Compiling httpdate v1.0.0
   Compiling bytemuck v1.5.1
   Compiling tower-service v0.3.1
   Compiling constant_time_eq v0.1.5
   Compiling encoding_rs v0.8.28
   Compiling scoped_threadpool v0.1.9
   Compiling cfg-if v0.1.10
   Compiling strum v0.8.0
   Compiling cfg_aliases v0.1.1
   Compiling mime v0.3.16
   Compiling rfd v0.3.0
   Compiling strum v0.20.0
   Compiling ipnet v2.3.0
   Compiling base64 v0.13.0
   Compiling state v0.4.2
   Compiling minisign-verify v0.1.8
   Compiling instant v0.1.9
   Compiling crossbeam-utils v0.8.4
   Compiling memoffset v0.6.3
   Compiling rayon v1.5.0
   Compiling futures-macro v0.3.15
   Compiling miniz_oxide v0.4.4
   Compiling tokio v1.6.0
   Compiling futures-util v0.3.15
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling indexmap v1.6.2
   Compiling num-iter v0.1.42
   Compiling num-rational v0.3.2
   Compiling tracing-core v0.1.18
   Compiling cc v1.0.50
   Compiling phf_shared v0.8.0
   Compiling unicode-bidi v0.3.5
   Compiling lock_api v0.4.4
   Compiling fxhash v0.2.1
   Compiling generic-array v0.14.4
   Compiling unicase v2.6.0
   Compiling tinyvec v1.2.0
   Compiling futf v0.1.4
   Compiling form_urlencoded v1.0.1
   Compiling dtoa-short v0.3.3
   Compiling servo_arc v0.1.1
   Compiling deflate v0.8.6
   Compiling miniz_oxide v0.3.7
   Compiling thread_local v1.1.3
   Compiling synom v0.11.3
   Compiling gif v0.11.2
   Compiling heck v0.3.2
   Compiling xml-rs v0.6.1
   Compiling pest v2.1.3
   Compiling tauri v1.0.0-beta.1
   Compiling tracing v0.1.26
   Compiling zstd-sys v1.6.0+zstd.1.5.0
   Compiling blake3 v0.3.7
   Compiling bzip2-sys v0.1.10+1.0.8
   Compiling tinyfiledialogs v3.3.10
   Compiling tendril v0.4.2
   Compiling unicode-normalization v0.1.17
   Compiling syn v0.11.11
   Compiling semver-parser v0.10.2
   Compiling quote v1.0.9
   Compiling want v0.3.0
   Compiling num_cpus v1.13.0
   Compiling raw-window-handle v0.3.3
   Compiling rand_core v0.5.1
   Compiling aho-corasick v0.7.18
   Compiling bstr v0.2.16
   Compiling uuid v0.8.2
   Compiling rand_core v0.6.2
   Compiling png v0.16.8
   Compiling idna v0.2.3
   Compiling strum_macros v0.8.0
   Compiling semver v0.11.0
   Compiling miow v0.3.7
   Compiling winapi-util v0.1.5
   Compiling parking_lot_core v0.8.3
   Compiling schannel v0.1.19
   Compiling socket2 v0.4.0
   Compiling winrt v0.4.0
   Compiling filetime v0.2.14
   Compiling winreg v0.7.0
   Compiling remove_dir_all v0.5.3
   Compiling dirs-sys-next v0.1.2
   Compiling time v0.1.43
   Compiling os_pipe v0.9.2
   Compiling shared_child v0.3.5
   Compiling open v1.7.0
   Compiling crossbeam-epoch v0.9.4
   Compiling crossbeam-channel v0.5.1
   Compiling flate2 v1.0.20
   Compiling rand_chacha v0.2.2
   Compiling rand_pcg v0.2.1
   Compiling regex v1.5.4
   Compiling cfb v0.4.0
   Compiling rand_chacha v0.3.0
   Compiling mime_guess v2.0.3
   Compiling digest v0.9.0
   Compiling crypto-mac v0.8.0
   Compiling same-file v1.0.6
   Compiling parking_lot v0.11.1
   Compiling mio v0.7.11
   Compiling tar v0.4.33
   Compiling dirs-next v2.0.0
   Compiling crossbeam-deque v0.8.0
   Compiling rand v0.7.3
   Compiling globset v0.4.6
   Compiling infer v0.4.0
   Compiling winrt-notification v0.2.4
   Compiling com_macros_support v0.2.0
   Compiling rand v0.8.3
   Compiling walkdir v2.3.2
   Compiling phf_generator v0.8.0
   Compiling notify-rust v4.5.2
   Compiling tempfile v3.2.0
   Compiling ignore v0.4.17
   Compiling thiserror-impl v1.0.24
   Compiling cssparser v0.27.2
   Compiling html5ever v0.25.1
   Compiling cssparser-macros v0.6.0
   Compiling derive_more v0.99.14
   Compiling pin-project-internal v1.0.7
   Compiling strum_macros v0.20.1
   Compiling serde_repr v0.1.7
   Compiling phf_codegen v0.8.0
   Compiling string_cache_codegen v0.5.1
   Compiling phf_macros v0.8.0
   Compiling com_macros v0.2.0
   Compiling thiserror v1.0.24
   Compiling pin-project v1.0.7
   Compiling selectors v0.22.0
   Compiling markup5ever v0.10.1
   Compiling com v0.2.0
   Compiling phf v0.8.0
   Compiling jpeg-decoder v0.1.22
   Compiling futures-executor v0.3.15
   Compiling futures v0.3.15
   Compiling tiff v0.6.1
   Compiling bytes v1.0.1
   Compiling string_cache v0.8.1
   Compiling url v2.2.2
   Compiling toml v0.5.8
   Compiling serde_urlencoded v0.7.0
   Compiling tauri-hotkey v0.1.2
   Compiling bincode v1.3.3
   Compiling webview2 v0.1.0
   Compiling image v0.23.14
   Compiling http v0.2.4
   Compiling winres v0.1.11
   Compiling tokio-util v0.6.7
   Compiling tokio-native-tls v0.3.0
   Compiling http-body v0.4.2
   Compiling tauri-build v1.0.0-beta.0
   Compiling h2 v0.3.3
   Compiling kuchiki v0.8.1
   Compiling app v0.1.0 (C:\Users\BillionWeb\Desktop\web\w-pc-bb-nav\src-tauri)
error: failed to run custom build command for `app v0.1.0 (C:\Users\BillionWeb\Desktop\web\w-pc-bb-nav\src-tauri)`
Caused by:
  process didn't exit successfully: `C:\Users\BillionWeb\Desktop\web\w-pc-bb-nav\src-tauri\target\debug\build\app-d9478cc02d40b237\build-script-build` (exit code: 101)
  --- stdout
  package.metadata does not exist
  "C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.17763.0\\x64\\rc.exe"
  "C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\rc.exe"
  RC Output:
  Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
  Copyright (C) Microsoft Corporation.  All rights reserved.
  C:\Users\BillionWeb\Desktop\web\w-pc-bb-nav\src-tauri\target\debug\build\app-7ae7dc4c032cc829\out\resource.rc(25) : error RC2175 : resource file icons/icon.ico is not in 3.00 format
  ------
  RC Error:
  ------
  --- stderr
  thread 'main' panicked at 'error found during tauri-build: failed to compile `icons/icon.ico` into a Windows Resource file during tauri-build', C:\Users\BillionWeb\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-build-1.0.0-beta.0\src\lib.rs:86:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by mxismean** [comment]
$ yarn tauri info
yarn run v1.22.10
warning w-pc-bb-nav@0.1.3: The engine "pm2" appears to be invalid.
$ C:\Users\BillionWeb\Desktop\web\w-pc-bb-nav\node_modules\.bin\tauri info
 app:spawn Running "C:\Users\BillionWeb\Desktop\web\w-pc-bb-nav\node_modules\@tauri-apps\cli\bin\tauri-cli.exe tauri info" +0ms


Operating System - Windows, version 10.0.19042 X64
Webview2 - 90.0.818.62

Node.js environment
  Node.js - 14.17.0
  @tauri-apps/cli - 1.0.0-beta.1
  @tauri-apps/api - Not installed

Global packages
  npm - 6.14.13
  yarn - 1.22.10

Rust environment
  rustc - 1.54.0-nightly
  cargo - 1.54.0-nightly

App directory structure
/.git
/app
/internals
/node_modules
/public
/src-tauri

App
  tauri.rs - 1.0.0-beta.1
build-type - bundle
CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
distDir - target/webpack_dist
devPath - Set automatically by Vue CLI plugin
framework - Vue.js (Vue CLI)
bundler - Webpack

Done in 8.70s.

**Comment by mxismean** [comment]
@nothingismagick

**Comment by mxismean** [comment]
Cargo.toml

```
[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-beta.0" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-beta.1", features = ["api-all"] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]`
```

**Comment by amanu-nur** [comment]
have you solved the problem? how to solve it? please help me,
