### ISSUE TITLE
api example run failed

### ISSUE THREAD

**Issue by SOVLOOKUP** [tauri-apps/tauri#1894]
**Describe the bug**
api example run failed with compile error

**To Reproduce**
1. Go to `examples/api`
2. `npm i`
3. `tauri dev`

**Expected behavior**

```
Compiling api v0.1.0 (/home/sovlookup/桌面/tauri-dev/examples/api/src-tauri)
error[E0432]: unresolved imports `tauri::CustomMenuItem`, `tauri::Menu`, `tauri::MenuItem`
 --> examples/api/src-tauri/src/menu.rs:5:13
  |
5 | use tauri::{CustomMenuItem, Menu, MenuItem};
  |             ^^^^^^^^^^^^^^  ^^^^  ^^^^^^^^ no `MenuItem` in the root
  |             |               |
  |             |               no `Menu` in the root
  |             no `CustomMenuItem` in the root

error[E0432]: unresolved imports `tauri::CustomMenuItem`, `tauri::SystemTrayMenuItem`
  --> examples/api/src-tauri/src/main.rs:14:13
   |
14 | use tauri::{CustomMenuItem, Manager, SystemTrayMenuItem, WindowBuilder, WindowUrl};
   |             ^^^^^^^^^^^^^^           ^^^^^^^^^^^^^^^^^^ no `SystemTrayMenuItem` in the root
   |             |
   |             no `CustomMenuItem` in the root

error[E0599]: no method named `menu` found for struct `tauri::Builder<std::string::String, std::string::String, std::string::String, std::string::String, _, Wry>` in the current scope
  --> examples/api/src-tauri/src/main.rs:36:6
   |
36 |     .menu(menu::get_menu())
   |      ^^^^ method not found in `tauri::Builder<std::string::String, std::string::String, std::string::String, std::string::String, _, Wry>`

warning: unused import: `Manager`
  --> examples/api/src-tauri/src/main.rs:14:29
   |
14 | use tauri::{CustomMenuItem, Manager, SystemTrayMenuItem, WindowBuilder, WindowUrl};
   |                             ^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused import: `WindowBuilder`
  --> examples/api/src-tauri/src/main.rs:14:58
   |
14 | use tauri::{CustomMenuItem, Manager, SystemTrayMenuItem, WindowBuilder, WindowUrl};
   |                                                          ^^^^^^^^^^^^^

error: aborting due to 3 previous errors; 2 warnings emitted

Some errors have detailed explanations: E0432, E0599.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `api`

To learn more, run the command again with --verbose.
```

**Platform and Versions (please complete the following information):**

OS: Linux
Node: v16.1
NPM:npm@6.14.11
Yarn:1.22.10
Rustc:rustc 1.52.1 (9bc8c42bb 2021-05-09)

**Comment by lucasfernog** [comment]
Did you rebuild the `tooling/cli.js` package? Also check if there's any `tooling/cli.js/bin/tauri-cli` binary in there, if there is, delete it. I think your CLI is outdated so it removed the `menu` feature on `examples/api/src-tauri/Cargo.toml`.

**Comment by SOVLOOKUP** [comment]
thanks, after rebuilding `tooling/cli.js` it passed the compilation. 
But it's all blank, what's wrong with it ... 
![image](https://user-images.githubusercontent.com/53158137/120494573-81aa8180-c3ee-11eb-9573-93df725940eb.png)

Actually when I run `npm run dev`, svelte runs blank web page too.
![image](https://user-images.githubusercontent.com/53158137/120494704-9edf5000-c3ee-11eb-8a8f-50a2ef338b88.png)

**Comment by lucasfernog** [comment]
You also need to build tooling/api

**Comment by holmesadrianh** [comment]
How exactly does one rebuild the packages mentioned in this thread?

**Comment by FabianLars** [comment]
@holmesadrianh If you're in the project root you can run `.scripts/setup.sh` which should build all you need, but manually you can do:
1. `cd tooling/api && yarn && yarn build`
2. `cd tooling/cli/node && yarn && yarn build`

**Comment by holmesadrianh** [comment]
Thanks for the info!
