### ISSUE TITLE
webview.eval does not work on EDGE and IE

### ISSUE THREAD

**Issue by BenoitRanque** [tauri-apps/tauri#190]
Platform: Windows 10

Description: `webview.eval` does not work as expected. We use this to inject `tauri.js` into our applications during development.

When using Edge (configure `tauri.edge.active: true` in tauri.config.js), execution fails silently.
When using IE (configure `tauri.edge.active: false` in tauri.config.js), rust panics:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JsEvaluation', src\libcore\result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Ideally rust should execute tauri.js, making `window.tauri` available in the js part of the application.

The relevant file in tauri is [runner.js](https://github.com/tauri-apps/tauri/blob/dev/tauri/src/app/runner.rs#L50)

Note: the rust bindings should throw an error if eval fails (as they do when using IE).
The relevant code is [here](https://github.com/Boscop/web-view/blob/master/src/lib.rs#L356). No detailed information is thrown.

I've tried executing simple js code instead of `tauri.js`
I would expect the following snippet to turn the background red:
```rs
_webview.eval("document.body.style.background = 'red';")
```
Instead nothing happens. I'm told this snippet does work on other platforms.

I've been able to verify that rust does load the `tauri.js` file correcly, by using:
```rs
// this prints the tauri.js file to console as expected.
println!("{}", include_str!(concat!(env!("TAURI_DIR"), "/tauri.js")));
```
Note: last night I managed to get simple js code to add nodes to the DOM, but could not get that working again today. The computer I did this on also runs Windows 10

I've confirmed the bug when using both the quasar example and a new Vue Cli 3 project.
Adding tauri.js to a statics folder and then referencing it in a script tag works as expected.

Clone tauri-apps/tauri
```
cd tauri/cli/tauri.js
yarn
cd ../../examples/vue/quasar-app
yarn
quasar dev
yarn tauri:source:dev
```

My tauri.conf.js:
```js
const path = require('path')
const distDir = path.resolve(__dirname, './dist/spa')

module.exports = function () {
  return {
    build: {
      distDir: distDir,
      devPath: 'http://localhost:7334' // devServer URL or html dir
    },
    ctx: {},
    tauri: {
      embeddedServer: {
        active: false
      },
      bundle: {
        active: true
      },
      whitelist: {
        all: true
      },
      window: {
        title: 'Tauri App'
      },
      security: {
        csp: 'default-src data: filesystem: ws: http: https: \'unsafe-eval\' \'unsafe-inline\''
      },
      edge: {
        active: true // change this to false to have rust throw an error.
      }
    }
  }
}
```

OS: Windows 10
Node: v12.13.1
NPM: 6.12.1
Yarn: 1.19.2
Tauri Binding: latest (compiled from source)
Bundle Target: Windows

Possible solutions/workarounds: should we injecty tauri.js using the webpack loader?
Another posibility: adding tauri.js in a script tag dynamically (currenlyt we just execute it) might behave diferently. I've not gotten this to work.

**Comment by tensor-programming** [comment]
I shall look into this and see if I can come up with something.

**Comment by BenoitRanque** [comment]
This might soon no longer be relevant, since we are in the middle of a major refactor, but right now on my windows machine, I can get `tauri dev` to load the page if my devPath in tauri.conf.js is `http://127.0.0.1:7334` instead of `http://localhost:7344` 

Still no luck with eval, but waiting for refactor to resume testing.

**Comment by tensor-programming** [comment]
Which refactor are you referencing in this case?

**Comment by BenoitRanque** [comment]
I got this issue to reproduce with just webview. Here is the code I used:
```rs
use web_view::*;

fn main() {
    let webview = web_view::builder()
        .title("My Project")
        .content(Content::Html(HTML))
        .size(320, 480)
        .resizable(true)
        .debug(true)
        .user_data(())
        .invoke_handler(|_webview, _arg| Ok(()))
        .build()
        .unwrap();

    webview.handle()
        .dispatch(|_webview| _webview.eval(SCRIPT))
        .unwrap();

    webview.run().unwrap();
}

const HTML: &str = r#"
<!doctype html>
<html>
    <body>
        <h1>Hello, world</h1>
    </body>
</html>
"#;

const SCRIPT: &str = r#"
document.body.appendChild(document.createElement('p')).appendChild(document.createTextNode('Hello there!'));
"#;
```
Cargo.toml
```
[dependencies]
web-view = { version = "0.5.4", features = ["edge"] }
```
Note: removing the edge feature in Cargo.toml makes the window crash

**Comment by BenoitRanque** [comment]
update: adding `thread::sleep(Duration::from_secs(1))` just before `webview.eval` is a workaround.
It is possible the DOM is not ready at that point?

**Comment by BenoitRanque** [comment]
A quick workaround to this issue is not using `webview.handle().dispatch()`. We don't really need it

**Comment by nothingismagick** [comment]
Have you looked at the event.rs structure?

**Comment by BenoitRanque** [comment]
Closing in favor of #212, which is more detailed and specific, and offers a possible fix (for IE only)
