### ISSUE TITLE
Return of tauri command invoke hangs until mouse is moved

### ISSUE THREAD

**Issue by olup** [tauri-apps/tauri#1908]
**Describe the bug**
Resolution of js promise that call some tauri command hangs until the mouse moves - even a little bit - then it resolves.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform and Versions (please complete the following information):**
```
Operating System - Ubuntu, version 20.10 X64

Node.js environment
  Node.js - 14.15.5
  @tauri-apps/cli - 1.0.0-beta.1
  @tauri-apps/api - 1.0.0-beta.1

Global packages
  npm - 6.14.11
  yarn - 1.22.10

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/public
/build
/.github
/node_modules
/.git
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.1
build-type - bundle
CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
distDir - ../build
devPath - http://localhost:4000
framework - React
```

**Additional context**
From @lucasfernog on the discord channel:
>  the problem is that the invoke requires the event loop to run, which is sleeping until some window interaction happens

**Stack Trace**

**Comment by lucasfernog** [comment]
@olup do you have an example command/app to reproduce this? I'm not seeing this issue anymore.

**Comment by olup** [comment]
@lucasfernog this behavior is gone with latest tauri dev and latest tao dev - I just pulled that today. This works very well now.

**Comment by lucasfernog** [comment]
Thanks to the tao guys for magically fixing issues! @wusyong @lemarier @amrbashir
