### ISSUE TITLE
Bundler waits for macos notarization to finish even if it takes a long time

### ISSUE THREAD

**Issue by dardanbujupaj** [tauri-apps/tauri#1916]
**Describe the bug**
The notarization from Apple for macos apps is usually pretty fast, but sometimes it can take a very long time.
The tauri bundler waits for the notarization to finish no matter how long it takes.
In my case the github release action ran for about 3h before i cancled it manually. But I received the confirmation mail for the notarization about 5 hours later.

**To Reproduce**
1. Configure Apple Signing ID in tauri.conf.json
2. Setup credentials and private key  as environment variables (I did this in a github action)
3. Release a few times until the issue comes up (had it 1 out of approx. 10 times releasing)

**Expected behavior**
The bundler should start the notarization and also finish it if possible in a few seconds (or minutes?) but there should definitely be a timeout to cancel the operation to prevent excessive runtime in paid CI/CD environments (e.g. Github Actions).

I'm still new to the whole Apple signing/notarization thing. But if I understand correctly the notarization results in some sort of "ticket" that can be attached to the released application, to allow for the macos Gatekeeper to permit the app to run even when the host system is offline and can't check against the apple servers. 
I imagine this is the reason for the bundler to wait for the notarization to finish.
This should still be considered. But I hope someone has more expertise in this area to suggest how this can be done 🙄

**Platform and Versions (please complete the following information):**
OS: macos
Node: LTS (shouldn't matter though)
NPM: LTS (shouldn't matter though)
Yarn: - 
Rustc: 1.52.1

**Additional context**
@lemarier faced this issue as well, they might have additional information.

**Stack Trace**
Excerpt of the action log:
```
...
489 Finished release [optimized] target(s) in 7m 51s
490 Bundling tauri-test.app
491 info: setup keychain from environment variables...
492 info: signing with identity "Developer ID Application: Dardan Bujupaj (23WCX26HRU)"
493 info: signing with identity "Developer ID Application: Dardan Bujupaj (23WCX26HRU)"
494 info: notarizing app
495 info: notarization started; waiting for Apple response...
496 Error: The operation was canceled.
```

**Comment by dardanbujupaj** [comment]
I just had another look at it. The process I wasn't sure about is called stapling and is done here:
https://github.com/tauri-apps/tauri/blob/e85472b9e2a4fdf91c01ca51b7b740cf44d47380/tooling/bundler/src/bundle/macos/sign.rs#L306

Here is the description from apple:
> You should also attach the ticket to your software using the stapler tool, so that future distributions include the ticket. This ensures that Gatekeeper can find the ticket even when a network connection isn’t available.

https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow#3087720

This pretty much requires the notarization to be done beforehand.

**Comment by lucasfernog** [comment]
We discussed this and agreed that it's more complicated to allow skipping the notarization check (or settings a timeout), specially since you also need to make sure notarization succeeded before shipping your app.
