### ISSUE TITLE
[docs] Should @tauri-apps/cli be `devDependencies`?

### ISSUE THREAD

**Issue by MikeChongCan** [tauri-apps/tauri#1921]
In [the integration document](https://tauri.studio/en/docs/usage/development/integration#1-install-tauri-js-package-as-a-dependency), `@tauri-apps/cli` is installed as the `dependencies` instead of `devDependencies`.

```bash
cd project-folder

# Not required if you already have a package.json:
# yarn init
# OR
# npm init

yarn add @tauri-apps/cli
# OR
npm install @tauri-apps/cli
```

Does it make more sense to use `yarn add -D @tauri-apps/cli` instead?

**Comment by amrbashir** [comment]
yes you can add it as a dev-dependency and you should do so, I will update the docs to reflect that.
