### ISSUE TITLE
create-tauri-app Vite - not working by default

### ISSUE THREAD

**Issue by tcastelly** [tauri-apps/tauri#1924]
Hello,

I had little problems during the creation of a project with Vite + (React or Vue)

> npx create-tauri-app
```
Error: Cannot find module '/private/tmp/tauri-vite-vue/node_modules/esbuild/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

So, I installed the dependencies of my project and re-execute the initialisation of the project
> cd /tmp/tauri-vite-vue
> npm i
> cd ../ && npx create-tauri-app

Then when I run `npm run tauri dev` I had this error:
```
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
```

I add in the scripts section of my package.json:
> "start": "vite"

And it works :)

---

**Platform and Versions (please complete the following information):**

OS: OSX
Node: v14.17.0
NPM: 6.14.13
Yarn: 1.22.10
Rustc: rustc 1.52.1 (9bc8c42bb 2021-05-09)

**Comment by amrbashir** [comment]
what is the output of `npx create-tauri-app -v` and can you try creating a fresh project with `create-tauri-app` cause for some reason `npx` just pulled an old version of `create-tauri-app` and I had to run the command again for it to get the latest version, anyhow the `create-tauri-app` process was successful the second time.

**Comment by tcastelly** [comment]
The output


```
npx create-tauri-app -v
npx: installed 99 in 7.618s
1.0.0-beta.1
```

I installed globally `create-tauri-app`, I have the same version


```
create-tauri-app -v
1.0.0-beta.1
```

For both I have the same issue:
> Error: Cannot find module [...]/node_modules/esbuild/install.js'

**Comment by amrbashir** [comment]
I can reproduce it now with `node 14` and `npm 6`, `esbuild` has been giving us a hard time, will see if we can fix that.

**Comment by tcastelly** [comment]
ok :)

About the problem with the missing "start" in package.json. Are we agree I only need to add 
> "start": "vite"

?

**Comment by amrbashir** [comment]
<s>no, that's a mis-configuration on our end, will fix that too</s> fixed this one.

**Comment by amrbashir** [comment]
This should be fixed in the next release, please re-open if it still happens then.
