### ISSUE TITLE
Confused between commands and events; How to push data to frontend

### ISSUE THREAD

**Issue by ravern** [tauri-apps/tauri#1927]
I've run into two issues with Tauri after using it for a day or two. Do let me know if this is the wrong place to request for help.

1. Reading the documentation, I am thoroughly confused about the difference between commands and events. Are commands the high-level implementations of events? Or are they using separate methods of passing data around altogether?

2. Also, how would, for example, a chat app actively _push_ new messages to the frontend? According to the guides on the website, it seems that only _responding_ to commands from the frontend is possible. I did find `window.emit`, but `tauri::Builder` doesn't return a `tauri::App` or `tauri::Window` so there's really no way to access the window.

That being said, I'm really excited at what Tauri is shaping up to be :)

**Comment by Laegel** [comment]
Hey @ravern !
I guess this is what you're looking for: https://tauri.studio/en/docs/api/rust/tauri/window/struct.Window#pub-fn-emite-sized-sself-event-e-payload-s---result-where-pevent-borrowe-e-tagrefpevent-s-serialize

We've planned to improve both the search results (right now, only five in all docs, which is not enough) and the Rust docs layout so it becomes easier to understand.
Don't hesitate to join us in our [Discord server](https://discord.com/invite/tauri) if you need some more help. ;)

**Comment by lucasfernog** [comment]
`App` and `Window` implement the `Manager` trait: https://docs.rs/tauri/1.0.0-beta.1/tauri/trait.Manager.html#method.get_window

And on the next release you'll also be able to get an App handle: https://github.com/tauri-apps/tauri/blob/cb6c807ac8a28592b559e679157330580f970840/core/tauri/src/app.rs#L181

We'll improve docs on events, but your use case is exactly what the event system is designed for - actively pushing data.
