### ISSUE TITLE
Angular recipe for create-tauri-app

### ISSUE THREAD

**Issue by fkromer** [tauri-apps/tauri#1934]
**Is your feature request related to a problem? Please describe.**

For some complex apps it might be helpful to beeing able to use Angular.

**Describe the solution you'd like**

An entry for `Angular` (which is essentially `Angular with TypeScript`) in the interactive prompt of [`create-tauri-app`](https://github.com/tauri-apps/tauri/tree/21a971c3b76bf0c26d00b2520b4976fa526738f5/tooling/create-tauri-app):

![angular-missing](https://user-images.githubusercontent.com/10199742/120296129-19618000-c2c8-11eb-9d44-4b96322ca9e7.PNG)

**Describe alternatives you've considered**

**Additional context**

**Comment by nothingismagick** [comment]
To be fair, you can use angular with typescript today, you just have to bring it yourself. If you check out the way the create-tauri-app system works, it should be pretty trivial to add another UI recipe - and we would welcome such a PR.

https://github.com/tauri-apps/tauri/tree/dev/tooling/create-tauri-app/src/recipes

**Comment by fkromer** [comment]
I know. In general, I don't program anything for free if other programmers could potentially get paid to implement it. I'm sticking to this code of conduct for years now and won't change my mind. Sponsoring is no option as well cause we are a small startup. As long as there is no stable release of tauri the company I'm working for won't let me put time into this even if I'd like to. As soon as there's a stable release I'll probably get back to this.

**Comment by fanninpm** [comment]
> **Describe alternatives you've considered**

Have you considered learning Vue.js?

**Comment by fkromer** [comment]
@fanninpm I already do 🍡

**Comment by BenoitRanque** [comment]
I would like to propose the title of this issue be changed, or that it be closed.
The current title implies that tauri does not currently support angular, which is misleading.
While it is true that `create-tauri-app` does not currently support angular, it is currently possible to add tauri to almost any project provided an http endpoint is available.

IMHO most complex projects will not use `create-tauri-app` but instead add tauri to an already scaffolded project.

**Comment by nothingismagick** [comment]
You're right.

**Comment by nothingismagick** [comment]
Lucas beat me to it.

**Comment by fkromer** [comment]
From my side there is no need to keep this issue open as well. I like Vue.js 3 better than Angular for creating Tauri apps. And as @BenoitRanque said it's of course possible to add Tauri to an already existing Angular app.

**Comment by Epsilon02** [comment]
I will give it a try.
