### ISSUE TITLE
impossible to use dialog

### ISSUE THREAD

**Issue by tcastelly** [tauri-apps/tauri#1942]
I build with success the api example from the up-to-date dev branch. When I try to open a dialog:
- without moving the cursor nothing happen
- after moving the cursor the application is frozen
![image](https://user-images.githubusercontent.com/37597737/120469512-b8f34100-c3a2-11eb-8b08-141f173db6fe.png)

OS: Archlinux + i3wm
Node: 15.16.0
NPM: 6.14.11
Yarn: 1.22.10
Rustc: rustc 1.52.1 (9bc8c42bb 2021-05-09)

**Comment by lucasfernog** [comment]
I can confirm this issue, we'll investigate it and track it on https://github.com/tauri-apps/tao/issues/81
