### ISSUE TITLE
Unable to close Tauri app with Command+Q on MacOS

### ISSUE THREAD

**Issue by n8jadams** [tauri-apps/tauri#1948]
**Describe the bug**
I hear the bad sound (https://www.youtube.com/watch?v=8rz44o_gGpE&ab_channel=akashiluddi) when trying to close Tauri app on MacOS with Command+Q. I have to hit the red x in the top left corner to close it (or kill it in the command line in watch mode)

**To Reproduce**
1. [Clone my repo](https://github.com/n8jadams/tauri-typescript-react-boilerplate)
2. Run `$ yarn && yarn dev` or `$ yarn && yarn build` and run the app
3. Hit Command+Q
4. Hear the bad sound (https://www.youtube.com/watch?v=8rz44o_gGpE&ab_channel=akashiluddi)

**Expected behavior**
Hitting Command+Q should close the app.

**Platform and Versions (please complete the following information):**
Operating System - Mac OS, version 10.15.7 X64

Node.js environment
  Node.js - 14.15.5
  @tauri-apps/cli - 1.0.0-beta.1
  @tauri-apps/api - 1.0.0-beta.1

Global packages
  npm - 7.12.0
  yarn - 1.22.5

Rust environment
  rustc - 1.54.0-nightly
  cargo - 1.54.0-nightly

**Comment by lucasfernog** [comment]
You need to create a menu with a `MenuItem::Quit` entry.

```rust
use tauri::{CustomMenuItem, Menu, MenuItem};

fn main() {
  let menu = Menu::new().add_native_item(MenuItem::Quit);
  tauri::Builder::default()
    .menu(menu)
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
```

^ This is the next release syntax (the menu is getting a small breaking change).

Thanks to @lemarier for helping with this on Discord.

**Comment by vnen** [comment]
This doesn't work for me using Tauri v1.0.0-beta8. It doesn't add any items to the app menu. Did something change?

**Comment by schickling** [comment]
I experienced the same problems. @FabianLars helped me out with this snippet:

```rs
use tauri::{CustomMenuItem, Menu, MenuItem, Submenu};

fn main() {
  let menu = Menu::new().add_submenu(Submenu::new("appname", Menu::new().add_native_item(MenuItem::Quit));
  tauri::Builder::default()
    .menu(menu)
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
```

**Comment by elanzini** [comment]
I have tried all the solutions listed here but I am still experiencing the issue of not being able to close the application with Command+Q combination. Interestingly, the shortcut works when I run the application locally with `npm run tauri dev` but  doesn't work when I install the application on the device.

It works if I manually go to the menu on the top bar and click on Quit - but not with the keyboard shortcut.

**Comment by FabianLars** [comment]
@elanzini This is unrelated to this issue. It's a new bug we're working on https://github.com/tauri-apps/tauri/issues/5669 / https://github.com/tauri-apps/wry/issues/774
