### ISSUE TITLE
Reopening issue #1911

### ISSUE THREAD

**Issue by mq1** [tauri-apps/tauri#1953]
`<select>` elements open outside the application window. When opened a second time, they open in the correct position. The problem occurs again when moving the window to a new location.

Tauri info:
```
Operating System - Windows, version 10.0.19043 X64
Webview2 - 91.0.864.41

Node.js environment
  Node.js - 16.2.0 
  @tauri-apps/cli - 1.0.0-beta.1 (outdated, latest: 1.0.0-beta.2)
  @tauri-apps/api - Not installed

Global packages
  npm - 7.13.0
  yarn - Not installed

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0
```

**Comment by lucasfernog** [comment]
Why did you create another issue? You can just reopen the other one.

**Comment by mq1** [comment]
Sorry, I didn't know issues could be reopened
