### ISSUE TITLE
Cannot download blob:http://file

### ISSUE THREAD

**Issue by michi-zuri** [tauri-apps/tauri#196]
When trying to download a Eile from a tauri app I was shown a dialog by macOS that it doesn't know how to open blob:http:file 

See also:

https://github.com/iotaledger/spark-wallet/issues/89#issuecomment-568173121

(includes screenshot)

**To Reproduce**
1. Install iota-ledger/spark-wallet
2. Launch the app once built, and choose backup seedvault
3. Choose Password and attempt to download 

**Expected behavior**
The file should just download

**Platform (please complete the following information):**
OS: macOS 
Node: 13.1.0
NPM: 6.12.1
Yarn: 1.21.1
Tauri Binding: ? 
Bundle Target: ? 

Rust 1.40.0

**Comment by nothingismagick** [comment]
This is not a bug in tauri.

https://github.com/eligrey/FileSaver.js/pull/613

Thanks @rajivshah3 for cracking this.

**Comment by CharlieG42** [comment]
Hi @michi-zuri,

I have the same issue on MacOSX Big Sure. Have you find a solution ? If yes, could you help me ?

Thank in advance.
