### ISSUE TITLE
Crash on windows startup: The code execution cannot proceed because WebView2Loader.dll was not found.

### ISSUE THREAD

**Issue by n8jadams** [tauri-apps/tauri#1960]
**Describe the bug**
Crash on app startup on windows. 
The error message says:

**The code execution cannot proceed because WebView2Loader.dll was not found. Reinstalling the program may fix this problem.**

**To Reproduce**
1. Clone https://github.com/n8jadams/tauri-typescript-react-boilerplate
2. yarn install
3. yarn build
4. Open src-tauri\target\release\app.exe or go through the process of running src-tauri\target\release\bundle\msi\app_0.2.0_x64.msi and then running the installed app.exe.

**Expected behavior**
The app to start up normally.

**Platform and Versions (please complete the following information):**
Node.js environment
  Node.js - 14.15.3
  @tauri-apps/cli - 1.0.0-beta.1
  @tauri-apps/api - 1.0.0-beta.1

Global packages
  npm - 6.14.5
  yarn - 1.22.10

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

**Comment by nothingismagick** [comment]
Can you please update all dependencies and confirm that this issue has been fixed? Thanks @n8jadams

**Comment by n8jadams** [comment]
I went ahead and used `create-tauri-app` to just get things in my repo to a working state. Thanks :) Closing issue.
