### ISSUE TITLE
Don't expose phf

### ISSUE THREAD

**Issue by Kestrer** [tauri-apps/tauri#1961]
Tauri currently exposes phf in its public 1.0 API, but phf is not 1.0. This violates [C-STABLE](https://rust-lang.github.io/api-guidelines/necessities.html?highlight=1.#public-dependencies-of-a-stable-crate-are-stable-c-stable).

**Comment by lucasfernog** [comment]
`phf` is only exposed in [generated code](https://github.com/tauri-apps/tauri/blob/5cba6eb4d28d53f06855d60d4d0eae6b95233ccf/core/tauri-codegen/src/embedded_assets.rs#L255) on the user crate. It should not be used directly. We will document this.

**Comment by chippers** [comment]
we should probably mark it `#[doc(hidden)]` too since that's its only purpose.  I mistakenly didn't mark it when exposing it.  While it's "breaking" it's not really a big deal since it's straight up a re-export and we didn't plan to support the re-export explicitly
