### ISSUE TITLE
Scripts evaluation is blocked until a new event is handled

### ISSUE THREAD

**Issue by geieredgar** [tauri-apps/tauri#1962]
**Describe the bug**
When JavaScript code is dispatched for evaluation, e.g. as part of the response of a Rust command invoked from the JavaScript side, the execution does not start until a new event arrives.

**To Reproduce**
1. Call a rust command via `invoke` and print its output via `console.log`
2. The output only appears when a new event is handled, which we can trigger by e.g. moving the cursor.
3. If we don't trigger any event, the output will never be printed

**Expected behavior**
JavaScript code should be executed after dispatch without having to trigger a new event.

**Platform and Versions (please complete the following information):**

OS: Arch Linux, version Rolling Release X64
Node: 16.3.0
NPM: 7.16.0
Yarn: 1.22.10
Rustc: 1.52.1

**Additional context**
I have come up with three approaches to fix this behavior:
1. Set `control_flow` to `ControlFlow::Poll` after `dispatch_script` to `handle_event_loop` will be called again immediately.
2. Send a new Message to the event loop after `dispatch_script` to make sure `handle_event_loop` will be called again immediately.
3. Call `evaluate_script` immediately after `dispatch_script` in `handle_event_loop`.

Approach 1 did not work, but I did not investigate further why. Maybe I misunderstood the behavior of setting `control_flow` to `ControlFlow::Poll`?
Approach 2 requires adding some noop Message variant, which I think is a bit ugly.
Approach 3 did work, and is implemented in this PR: #1963

However I think it would be nicer, simpler and more efficient to immediately execute the script without the detour of calling both `dispatch_script` and `evaluate_script`, which uses a `mpsc::channel` under the hood. To be able to do that, I opened a PR for `wry` here: tauri-apps/wry#289

**Comment by lucasfernog** [comment]
Does it still happen on Tauri dev branch? Someone reported that it was fixed.

**Comment by geieredgar** [comment]
Unfortunately, the dev branch does not build on my local machine. The latest commit I can build is 7e160675d16b6240b1961169bd833475cb6679fd, and there it does still happen. I also couldn't find anything in the code of the current dev branch that would suggest otherwise.

**Comment by FabianLars** [comment]
Can you try it with this in your Cargo.toml? Some change in tao fixed this behaviour for me and others.
```
[patch.crates-io]
tao = { git = "https://github.com/tauri-apps/tao.git", branch = "dev" }
```

**Comment by geieredgar** [comment]
Yes, thank you, using the dev branch version of tao does indeed fix the issue, I assume because the MainEventsCleared event now makes sure that the event handler is run again after `dispatch_events`. I will close this issue and my PR, but I think it might be still worth to consider [tauri-apps/wry#289](https://github.com/tauri-apps/wry/pull/289), because using the `Dispatcher` of `wry` might cause issues when the event loop is not woken up separately.
