### ISSUE TITLE
Window Close Terminates Application

### ISSUE THREAD

**Issue by DBTaylor** [tauri-apps/tauri#1975]
When I close the application window, the application exits immediately: code after Builder::run() does not run, and managed state is not dropped.

I expect run() should complete and managed state should be dropped.

**Platform and Versions**
```Operating System - Windows, version 10.0.17763 X64
Webview2 - 91.0.864.41

Node.js environment
  Node.js - 14.8.0
  @tauri-apps/cli - 1.0.0-beta.1 (outdated, latest: 1.0.0-beta.2)
  @tauri-apps/api - 1.0.0-beta.1

Global packages
  npm - 6.14.7
  yarn - Not installed

Rust environment
  rustc - 1.51.0
  cargo - 1.51.0

App directory structure
/.vscode
/dist
/node_modules
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.1
build-type - bundle
CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self' img-src:
'self'
distDir - ../dist
devPath - http://localhost:8080/
framework - React
bundler - Webpack```

**Comment by lucasfernog** [comment]
.run() indeed exits the process; next release will include a run_return API.

**Comment by DBTaylor** [comment]
> 
> 
> .run() indeed exits the process; next release will include a run_return API.

Thanks! Until then is there a good way to drop managed state? I have some read-only state T. To get it to drop now, instead of using State<T>, I use State<RwLock<Option<T>>> and write None before exiting.
