### ISSUE TITLE
error running light.exe window

### ISSUE THREAD

**Issue by yang-dong-dong** [tauri-apps/tauri#1976]
yarn tauri build 

![image](https://user-images.githubusercontent.com/20069609/121650900-a24c9880-cacc-11eb-9e40-6a1f6fddfed6.png)

**Comment by lucasfernog** [comment]
With #1988 you can add this to your `tauri.conf.json` under the `bundle` object:

```json
"windows": {
  "wix": {
    "language": "zh-CN"
  }
}
```

Where the language can by any value from https://docs.microsoft.com/en-us/windows/win32/msi/localizing-the-error-and-actiontext-tables
