### ISSUE TITLE
Option to use external executor

### ISSUE THREAD

**Issue by DBTaylor** [tauri-apps/tauri#1977]
It would be nice if Builder had an run_async method that returned a future to be run on an executor and Tauri used that executor instead of its internal one. Like:
```rust
#[tokio::main]
async fn main() {
	tauri::Builder::default()
		.run_async(tauri::generate_context!())
		.await
		.expect("error while running tauri application");
}
```
I have some managed state that needs to be initialized in an async context. Right now I block_on in setup and use App::manage, but it would be nice if I had the option to initialize pre-Tauri, await, and use Builder::manage.

**Comment by ravern** [comment]
Same here. Trying to `manage` an `sqlx` connection pool but async is required to create the pool and start the connections.

I saw that in the past, `setup` actually took in an `async` closure? What changed?

**Comment by ravern** [comment]
I found this when looking through the examples. It's not exactly using an external executor, but at least it allows you to share the runtime with `tauri`. And I think it solves your problem for initialising async state as well.

https://github.com/tauri-apps/tauri/blob/c1f8e11342941b846479d73bf50cb0a328ac3574/examples/splashscreen/src-tauri/src/main.rs#L21-L39

Perhaps there could be a `tauri::async_runtime::handle` function that we could use to get a `tokio::runtime::Handler` out to use.

**Comment by lucasfernog** [comment]
Unfortunately this is not possible with the current tauri architecture. If you can find a way to implement this, we'd love to see it as a PR! For now you can use the `async_runtime` module.
