### ISSUE TITLE
could not execute process `target\debug\app.exe`

### ISSUE THREAD

**Issue by q32757468** [tauri-apps/tauri#1979]
**Describe the bug**
could not execute app whether dev or build

**To Reproduce**
PS E:\projects\tauri-projects\tray-test> npx tauri dev
 app:spawn Running "E:\projects\tauri-projects\tray-test\node_modules\@tauri-apps\cli\bin\tauri-cli.exe tauri dev" +0ms

   Compiling app v0.1.0 (E:\projects\tauri-projects\tray-test\src-tauri)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 35s
     Running `target\debug\app.exe`
error: could not execute process `target\debug\app.exe` (never executed)

Caused by:
  该版本的 %1 与你运行的 Windows 版本不兼容。请查看计算机的系统信息，然后联系软件发布者。 (os error 216)
  This version of% 1 is not compatible with the version of windows you are running. Check your computer's system information and contact the software publisher. (os error 216)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/43193877/121763941-64a24b00-cb72-11eb-9b2f-0c6d1039b06a.png)

**Platform and Versions (please complete the following information):**

Operating System - Windows, version 10.0.19042 X64
Webview2 - 91.0.864.41

Node.js environment
  Node.js - 12.18.4
  @tauri-apps/cli - 1.0.0-beta.1 (outdated, latest: 1.0.0-beta.2)
  @tauri-apps/api - 1.0.0-beta.1

Global packages
  npm - 6.14.6
  yarn - Not installed

Rust environment      
  rustc - 1.52.1
  cargo - 1.52.0

**Additional context**
I haven't had this problem with the version about two months ago

**Comment by FabianLars** [comment]
You need to have Microsoft Build Tools 2019 installed. iirc you also need to remove old versions (2015/2017) too (no side-by-side installs).

**Comment by q32757468** [comment]
> You need to have Microsoft Build Tools 2019 installed. iirc you also need to remove old versions (2015/2017) too (no side-by-side installs).

it's work ,great! thanks!

**Comment by q32757468** [comment]
@FabianLars it's work, great! thanks!
