### ISSUE TITLE
[Question] How can I use Rust commands in Vanilla JS?

### ISSUE THREAD

**Issue by dumrich** [tauri-apps/tauri#1984]
I've never used JS before, but I am familiar with Rust. How can I use the custom Rust commands in Vanilla Javascript? I am not using any Node JS framework, just HTML/CSS/JS. I can't import anything or invoke anything.

**Comment by lucasfernog** [comment]
`window.__TAURI__.invoke('your_command_name', thePayload)`.

**Comment by dumrich** [comment]
Yep, this works!
