### ISSUE TITLE
The cmd window appears when a command is ran

### ISSUE THREAD

**Issue by EduardoLopes** [tauri-apps/tauri#1987]
**Describe the bug**
When i build and run the app, the command window flashes in the screen (as shown in the GIF) every time a command is ran. This doesn't happen if i build the app flagged as debug.

**To Reproduce**
1. Setup a tauri command that run a cli command using rust `Command::new`
2. Invoke the command using `import { invoke } from '@tauri-apps/api/tauri`
3. The cmd window will flash in the screen 

**Expected behavior**
The cmd window should not appear

**Screenshots**
![GIF 15-06-2021 01-00-11](https://user-images.githubusercontent.com/1084297/122098945-d636ff00-cde7-11eb-8b0d-65f81d7c2466.gif)

$ npx tauri info

Operating System - Windows, version 10.0.19041 X64
Webview2 - 91.0.864.48

Node.js environment
  Node.js - 16.1.0 
  @tauri-apps/cli - 1.0.0-beta.0 (outdated, latest: 1.0.0-beta.2)
  @tauri-apps/api - 1.0.0-beta.0 (outdated, latest: 1.0.0-beta.1)

Global packages
  npm - 7.11.2
  yarn - 1.22.5

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/.git
/.svelte-kit
/.vscode
/build
/node_modules
/src
/src-tauri
/static

App
  tauri.rs - 1.0.0-beta.0
build-type - bundle
CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' img-src: 'self'
distDir - ../build
devPath - http://localhost:3000
framework - Svelte

---------------------
The project: https://github.com/eduardolopes/cut-branches

**Comment by lucasfernog** [comment]
I thought you were using the tauri Command API. To use the Rust command interface, you need to set a flag to hide the console window: https://github.com/tauri-apps/tauri/blob/463fd00d06241c734994fe8e1882788dc30cc993/core/tauri/src/api/process/command.rs#L82

**Comment by lucasfernog** [comment]
Alternatively, you can import `Command` from `tauri::api::process`, the API is similar to the `std` one.

**Comment by EduardoLopes** [comment]
I'm still learning Rust, so i didn't know that! And as it works as i wanted when making a debug build, i though it was related to tauri! 

Thank you ✨.
