### ISSUE TITLE
Detect idle time

### ISSUE THREAD

**Issue by rodrigomata** [tauri-apps/tauri#1994]
I want to know if there is a way to know if the user is afk. With electron I've used previously [Power Monitor](https://www.electronjs.org/docs/api/power-monitor), but I'm unable to see if this option exists within Tauri in the docs.

**Describe the solution you'd like**
A feature like the one provided by Electron would reach the only remaining functionality that I need to migrate from Electron to Tauri.

**Describe alternatives you've considered**
I can set the window on top and detect mouse movements and click on the app, but this is not ideal.

**Comment by lucasfernog** [comment]
Seems like it's quite easy to use https://crates.io/crates/user-idle/0.4.0

**Comment by nothingismagick** [comment]
yeah, i also think this is going to be a bring your own kind of solution. i don't see us adding this to core anytime soon. it could easily become a plugin though.
