### ISSUE TITLE
Add an example of how to use serialport [docs]

### ISSUE THREAD

**Issue by arnoson** [tauri-apps/tauri#1997]
I am trying to make the serial port accessible to javascript. So I need:
* a rust command that accepts a buffer or a string an sends it to the serial
* emit an event if rust recieves a serial input.

I'm using the [serialport-rs](https://gitlab.com/susurrus/serialport-rs) library but can't figure out how to make the port available in the tauri command.

I've been trying like this:
```rust
struct MyState {
  port: Box<dyn serialport::SerialPort>,
}

fn main() {
  let port = serialport::new("COM6", 9600)
    .timeout(Duration::from_millis(10))
    .open()
    .unwrap();

  let state = MyState { port };

  tauri::Builder::default()
    .manage(state)
    .invoke_handler(tauri::generate_handler![my_custom_command])
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
```
But I get the error `(dyn serialport::SerialPort + 'static) cannot be shared between threads safely`
I'm new to rust and can't figure out how to fix this. Maybe a more complex example for rust commands and events that rely on an external library, like serialport-rs in this case, would be great!

**Comment by Laegel** [comment]
Hey @arnoson !
I fear your need is a bit too specific for us and should be in a Github discussion or in our Discord, #help-triage channel, rather than in a Github issue. 
Why don't you come see us there? :)
https://discord.com/invite/tauri

**Comment by lucasfernog** [comment]
Try wrapping the serialport type in a Mutex. See https://doc.rust-lang.org/nomicon/send-and-sync.html and https://users.rust-lang.org/t/solved-how-to-move-non-send-between-threads-or-an-alternative/19928

**Comment by arnoson** [comment]
Thanks for your quick replies! I agree it is a bit too specific and I'll ask in your Discord channel next time (and learn a bit more rust ;)
