### ISSUE TITLE
Failed to load resource: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.

### ISSUE THREAD

**Issue by mxismean** [tauri-apps/tauri#2002]
Our project uses Vue + Vue CLI Plugin Tauri.
Server-side communication using Axios.
Because our project is used internally, all are deployed in an Intranet environment.
The interface is deployed on the Intranet.
The URL we request can only be HTTP, not HTTPS.
The development environment runs fine.
But the production environment is packaged and no data can be requested.
An error is as follows:
`Failed to load resource: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.`

**Comment by mxismean** [comment]
![image](https://user-images.githubusercontent.com/44690729/122354676-ce13c680-cf83-11eb-9cb5-2516ad6d9023.png)

**Comment by mxismean** [comment]
![image](https://user-images.githubusercontent.com/44690729/122355311-5f833880-cf84-11eb-8440-c5bd93266769.png)
The domain name is an Intranet domain, not accessible on the extranet

**Comment by mxismean** [comment]
![image](https://user-images.githubusercontent.com/44690729/122355963-ed5f2380-cf84-11eb-9493-14e09c4949ba.png)

**Comment by mxismean** [comment]
@lucasfernog

**Comment by nothingismagick** [comment]
In my opinion you shouldn't be doing any requests in the webview. You can use this JS API to do such things more safely:
https://tauri.studio/en/docs/api/js/modules/http

That said, internal networks are also prime territory for attacks, and you should always practice good hygiene and use https. Creating a self-renewing certificate with cert-bot and  let's encrypt is absolutely trivial for devs or ops.

**Comment by mxismean** [comment]
> 我认为你不应该在 webview 中做任何请求。你可以使用这个 JS API 来更安全地做这些事情：[https](https://tauri.studio/en/docs/api/js/modules/http) :
> [//tauri.studio/en/docs/api/js/modules/http](https://tauri.studio/en/docs/api/js/modules/http)
> 
> 也就是说，内部网络也是攻击的主要区域，您应该始终保持良好的卫生习惯并使用 https。使用 cert-bot 创建一个自我更新的证书并让我们加密对于开发人员或操作人员来说绝对是微不足道的。

Is it possible to add a configuration for the developer to choose

**Comment by nothingismagick** [comment]
What do you mean? certbot / let's encrypt is outside of the context of tauri entirely and is something you would install on the remote http server.

**Comment by mxismean** [comment]
Since our project needs to run both in the browser and on the desktop, it is not appropriate to change the current Web project

**Comment by mxismean** [comment]
> 你的意思是？certbot / let's encrypt 完全在 tauri 的上下文之外，您可以在远程 http 服务器上安装它。

Let the developer choose whether to allow HTTP requests

**Comment by nothingismagick** [comment]
> Since our project needs to run both in the browser and on the desktop, it is not appropriate to change the current Web project 

Adding a lets encrypt certificate is really trivial, and doesn't change the nature of a "Web project" - it merely adds proper security.

> Let the developer choose whether to allow HTTP requests

This is something that the rust http service (available via JS API) can do (did you look at the docs page i sent?). 

That said, I want it to be clear that I absolutely oppose the idea of sending any traffic across any network that is not encrypted. It is a lazy solution and as soon as you have an attacker on your network, sniffing unencrypted traffic is a very easy way to start moving laterally. But of course, feel free to ignore me - but don't claim that it is Tauri's fault when you get a security audit.

For anyone else reading this: please always use encryption.

**Comment by mxismean** [comment]
ok, thanks 🙏
