### ISSUE TITLE
Web Inspector can't capture http request

### ISSUE THREAD

**Issue by roojay** [tauri-apps/tauri#2003]
**Describe the bug**
I want to know specific details of a http request response, but `Web Inspector` can't capture it. I tried to use tools(charles, fiddle) to capture network traffic but also failed. How can I debug it?

console
![image](https://user-images.githubusercontent.com/11495164/122354985-16cb7f80-cf84-11eb-96ba-088892a2fe83.png)

netnetwork
![image](https://user-images.githubusercontent.com/11495164/122356239-2e573800-cf85-11eb-9b82-27a2e4199149.png)

**Platform and Versions (please complete the following information):**

OS: macos Moiave 10.14.6
Node: v14.17.0
Yarn: 1.22.10
Rustc: rustc 1.52.1 (9bc8c42bb 2021-05-09)

**Comment by nothingismagick** [comment]
We need more information to triage this. How are you making the request? What is the (sanitized) url? What kind of response are you expecting?

**Comment by shirakaba** [comment]
Just as a sanity check, as these things are true outside of the context of Tauri too:

I notice that you have some filters on in the web inspector. If the request is not of XHR type, then you won’t see it.

Also, if the request was fired before the Web Inspector was opened, then it’s likely that the request won’t be seen.

**Comment by lucasfernog** [comment]
You're using the Tauri HTTP API. That API call is not performed by the webview, but from the Rust code. Can I access that API so that we can return the proper error message?

**Comment by lucasfernog** [comment]
I've managed to reproduce the lack of error message with a 400 response I wrote. Gonna fix it.
