### ISSUE TITLE
Dynamic update of system tray items

### ISSUE THREAD

**Issue by guillemcordoba** [tauri-apps/tauri#2005]
**Is your feature request related to a problem? Please describe.**

The list of items in the system tray of my tauri app depend on actions that the users takes. Eg, if a user activates a module in the app, that module should appear in the systray as a new item. I think this is probably something that a lot of projects will need.

**Describe the solution you'd like**

It would be amazing to extend the SysTray API to let tauri devs add or update items in the systray. 

**Describe alternatives you've considered**

Maybe removing the full systray and replacing it with a whole new systray is a viable option? Although doesn't seem very elegant.

**Additional context**

I'm already pointing to the latest dev branch, which includes awesome sub-menus in the systray. Props for that!

**Comment by lemarier** [comment]
Thanks for reporting,

It’ll be available in the next release.

Have a great day.
