### ISSUE TITLE
Bug - On dev branch - ubuntu 20 - open / save file modal will freeze and crash app

### ISSUE THREAD

**Issue by olup** [tauri-apps/tauri#2013]
This is a bug

Using Tauri with patched Tao (latest dev branch) on ubuntu 20.10.

Trying to open a file modal (to open or save) will try to open something - it shows in the task bar - but no window is actually drawn to the screen. It hangs and eventually crash : "App is not responding / Force quit / Wait"

**Comment by lucasfernog** [comment]
We have a fix for this on the tauri repo. It will be available on the next release.

**Comment by olup** [comment]
Oh, great ! I'll try it from dev once the pr is merged, and report here

**Comment by olup** [comment]
Thanks a lot, working great on my end !
