### ISSUE TITLE
Frameless window and something like '-webkit-app-region:drag' for tauri

### ISSUE THREAD

**Issue by ilukinov** [tauri-apps/tauri#2017]
**Is your feature request related to a problem? Please describe.**
When building frameless window I need a way to give user ability to move and resize the window. Electron has style option that you can add to html tag to make it behave like window title bar in a sense that user can grab this element and drag the whole app window. Like so:
```html
<body style="-webkit-app-region: drag">
</body>
```

**Describe the solution you'd like**
Ideally I would like the same behavior as electron has.  Full description available https://www.electronjs.org/docs/api/frameless-window#draggable-region 
Or at least more control over title bar (make it slimmer or remove buttons) 

**Describe alternatives you've considered**
Using electron?)

**Additional context**
Thanks for awesome project.

**Comment by olup** [comment]
Hi, have you checked out https://tauri.studio/en/docs/guides/window-customization#html ?

**Comment by ilukinov** [comment]
I did not! Thank you very much, this will do the trick.

**Comment by KonradLinkowski** [comment]
@olup  I think the link is outdated

**Comment by ilukinov** [comment]
Hi this page describes it for electron https://www.electronjs.org/docs/latest/tutorial/window-customization#create-frameless-windows in 'Set custom draggable region' section

Here is tauri doc link https://v1.tauri.app/v1/guides/features/window-customization/
