### ISSUE TITLE
This version of %1 is not compatible with the version of Windows you're running.

### ISSUE THREAD

**Issue by elibenporat** [tauri-apps/tauri#2018]
**Describe the bug**
I get the following cryptic error message: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher. (os error 216)

I assume it's webview2, but I can't be sure? I didn't know how to fill out the other parts, however, I am quite stuck at this stage. I reinstalled webview2, both the x86 and the x64 versions, rebooted, but get the same error message.

**Platform and Versions (please complete the following information):**
Operating System - Windows, version 6.1.7601 X64
Webview2 - 91.0.864.54

Node.js environment
  Node.js - 12.19.0
  @tauri-apps/cli - 1.0.0-beta.1 (outdated, latest: 1.0.0-beta.2)
  @tauri-apps/api - 1.0.0-beta.1

Global packages
  npm - 6.14.8
  yarn - Not installed

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/dist
/node_modules
/src-tauri

App
  tauri.rs - 1.0.0-beta.1
build-type - bundle
CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
distDir - ../dist
devPath - ../dist

**Comment by FabianLars** [comment]
You need to have Microsoft Build Tools 2019 installed. You most likely also have to remove old versions (2015/2017) too (no side-by-side installs).

**Comment by nothingismagick** [comment]
Thanks Fabian, you're right.

**Comment by amrbashir** [comment]
This is a common question and should be added to the F.A.Q

**Comment by jacobq** [comment]
According to the [getting started guide](https://tauri.studio/v1/guides/getting-started/prerequisites#setting-up-windows) it's OK to use MSVC++ Build Tools 2022. Is that right? So I assume I should uninstall 2019? Is running `tauri info` the way to check what is being used? (In my case "Environment > MSVC" appears blank, which I assume is indicative of the problem).

![image](https://user-images.githubusercontent.com/1633459/170344807-b5ec88cd-5db0-4161-939c-e72baa693f18.png)

![image](https://user-images.githubusercontent.com/1633459/170345020-c46de9d5-6697-412c-8dae-b10e9a477875.png)

See also:

* https://github.com/tauri-apps/tauri/discussions/1608
* https://github.com/tauri-apps/wry/issues/410#issuecomment-1016119182

**Comment by FabianLars** [comment]
@jacobq Yes, 2019 and 2022 work fine. 2015 (the one you apparently have (version 14)) and 2017 _don't_ work! You don't _need_ to uninstall old versions tho as you can _somehow_ change the default (no idea how) or use the corresponding command prompt which should use the correct version (for example "x64 Native Tools Command Prompt for VS 2022")

**Comment by alexprabhatbara** [comment]
I have the same issue. I have VS 2022 Community Edition, still I am getting the same issue. Please guide me.
