### ISSUE TITLE
Open  / Close window through Rust API [docs]

### ISSUE THREAD

**Issue by poovarasanvasudevan** [tauri-apps/tauri#2019]
I registered two window

`
{
"windows": [
      {
        "title": "window1",
        "width": 280,
        "height": 600,
        "resizable": false,
        "fullscreen": false
      },
      {
        "title": "window2",
        "width": 350,
        "height": 350,
        "resizable": false,
        "fullscreen": false,
        "alwaysOnTop": true,
        "visible": false,
        "url": "http://localhost:8081/join"
      }
    ]
}
`

Now the question is how can i open window2 through Rust Command and similarly close window1 through rust command

**Comment by lucasfernog** [comment]
```rust
fn main() {
	tauri::Builder::default()
      .setup(|app| {
        let window1 = app.get_window("window1").unwrap();
        let window2 = app.get_window("window2").unwrap();
        window2.show();
	    window1.close(); // or window1.hide()
        Ok(())
      });
}
```

Note that you need to add `"label": "window1"` to the tauri.conf.json window object.
