### ISSUE TITLE
Tauri CLI does not handle promise rejections

### ISSUE THREAD

**Issue by BenoitRanque** [tauri-apps/tauri#202]
Currently, tauri.js cli does not handle promise rejections properly.
This can be seen if for example one attempts to run `tauri build` while build assets are not present.
The command line _will_ display the error, but as it is an unhandled promise rejection, the cli exits with a zero exit code. This could become a problem in the future, if we test the cli exit code.

Fixing this behavior requires multiple changes, and could be approached two ways:
Either we wrap all `await` expressions with `try {} catch (e) {}`, or we have a single `try {} catch (e) {}` at the root of the cli. I prefer this second approach.

Using this second approach will require refactor in multiple places. I believe a typescript version of the cli is in the works, so maybe we could wait for that to be done before tackling this problem.

**To Reproduce**
run `tauri build` while the assets (index.html) are not available.

**Explanation of JS's behavior**

Short version: await all promises

<details><summary>Long version</summary>

There are many [gotchas](https://jakearchibald.com/2017/await-vs-return-vs-return-await/) to async js and error handling. Here is a simple showcase of some of the gotchas of async JS.

```js
entry() // execute the entry function
async function entry () {
  try {
    a() // we are not awaiting this promise. mistake.
    b() // this function is the same as a. Async functions return promises
    await c() // this function does not await the promises inside
    await d() // this one finally does work as intended
  } catch (err) {
    // this will only catch d
    console.error('caught error', err)
  }
}
async function a () {
  throw new Error('Catch this!')
}
function b () {
  return new Promise((resolve, reject) => {
    reject(new Error('Catch that!'))
  })
}
async function c () {
  return a() // we should be awaiting this
}
async function d () {
  return await b() // finally the right signature!
}
```
</details>

**Changes that must be made**
1. Catch and handle all errors at cli root
2. All promises must be awaited.

I've not been able to come up with jest tests for this

**Comment by nothingismagick** [comment]
I believe that @nklayman's revision of the CLI to typescript addresses this - but mentioning him to make sure he is aware of this situation.

**Comment by Laegel** [comment]
Dunno how far we want to rework the files for the TS migration but I've seen some async/await stuff that could be improved. 
That's a nice list @BenoitRanque , thanks.
However, I think that the following example:
```javascript
async function c () {
  return a() // we should be awaiting this
}
```
would only be relevant if we were trying to try/catch the error from the "a" function in the "c" function (deeper explanation here: https://stackoverflow.com/questions/38708550/difference-between-return-await-promise-and-return-promise#answer-42750371).

I'd keep it as is or remove the `async` keyword instead (as its only usage is to explicitly notify readers thar "c" returns a promise because "a" returns a promise).

**Comment by BenoitRanque** [comment]
Agree, that one is actually fine. My bad.
Removing the async keyword is not an option, because further up in the function there are calls to async functions:

```js
async a () {
  await b()
  return c()
}
```

**Comment by nklayman** [comment]
There is a linter rule in the ts branch that requires every async function be handled properly with a .catch.

**Comment by nothingismagick** [comment]
I am going to close this issue then, because we will be merging the TS branch imminently. Thanks for reporting @BenoitRanque

**Comment by jbolda** [comment]
I would still advocate having tests to make sure we error out correctly, and not relying solely on the linter. If we don't throw properly, we get in this odd situation where green CI builds could actually be failing.
