### ISSUE TITLE
vue router does not work in tauri

### ISSUE THREAD

**Issue by ikey4u** [tauri-apps/tauri#2020]
**Describe the bug**
When using vue router in tauri, it works in `yarn tauri:serve` mode but not work in built production generated by `yarn tauri:build`.

**To Reproduce**

I created a simple and dirty demo here [https://github.com/ikey4u/tauri-vue](https://github.com/ikey4u/tauri-vue) to reproduce the problem

**Expected behavior**
The built binary generated by `yarn tauri:build` works as it does in `yarn tauri:serve`

**Screenshots**
When clicking vue router in built production, it shows as below
![image](https://user-images.githubusercontent.com/12681575/122671680-703ce400-d1fa-11eb-8737-15d85cf628f5.png)

**Platform and Versions (please complete the following information):**

OS: Arch
Node:  v16.3.0
NPM: 7.15.1
Yarn:  1.22.10
Rustc: 1.53.0

**Comment by Laegel** [comment]
Hey @ikey4u , thanks for the issue!
I see you're using the `history` mode that has some known problems with Tauri (I think the history API requires a polyfill), try to switch to the default `hash` mode.

**Comment by lucasfernog** [comment]
The wry team fixed the old history mode but now we need a fix for the custom protocol asset loading. For now the hash mode fixes it.

**Comment by ikey4u** [comment]
@lucasfernog @Laegel I have changed the mode to hash mode, but it still does not work in built production, see the demo repo.

**Comment by lucasfernog** [comment]
I'm checking it right now.

**Comment by vanminhquangtri** [comment]
change to hash mode not work for vue 3

**Comment by jianfei96** [comment]
> change to hash mode not work for vue 3更改为哈希模式不适用于 vue 3

Any workaround?

**Comment by Glass109** [comment]
No solution yet?

**Comment by FabianLars** [comment]
This should have worked for years now and I didn't get any reports in the last months/years either as far as I can remember.

If this is still an issue for you please open a new issue and fill out the bug report template (ideally including a reproduction project)
