### ISSUE TITLE
feature: request user attention

### ISSUE THREAD

**Issue by joaobsantos** [tauri-apps/tauri#2023]
Allow javascript to require focus to the window in the taskbar with blinking icon.

Ex:

![image](https://user-images.githubusercontent.com/14371776/122674919-17a42180-d1cf-11eb-94a8-27260916ada9.png)

**Comment by lemarier** [comment]
I think this should be handled at the window level, so the `tao` issue makes sense.

**Comment by amrbashir** [comment]
@lemarier we have it on `tao`, we just need to expose it on Tauri
