### ISSUE TITLE
Getting issue WebKit encountered an internal error when using Fetch API

### ISSUE THREAD

**Issue by dumrich** [tauri-apps/tauri#2025]
**Describe the bug**
When I use Fetch API to fetch data from my API, my app is giving an error that says, "Failed to load resource, WebKit encountered an internal error". Note that it works fine when doing anything else except fetch
**To Reproduce**
1. Try using fetch API.

**Expected behavior**
Get expected results.

**Screenshots**

**Platform and Versions (please complete the following information):**

OS: Gentoo GNU/Linux x86/64
Node:14.16.1
NPM: 6.14.12
Rustc:1.52.1

**Comment by nothingismagick** [comment]
Can you please share the csp value in your tauri.conf.json and also paste the results of `yarn tauri info`?

**Comment by lucasfernog** [comment]
I can use `fetch` normally on Linux. Check the console to see if it's not a CORS issue.

Here's an example API I used to test it:

```javascript
const express = require('express');
const cors = require('cors');

const app = express();
app.use(cors())

app.get('/', (req, res) => {
    res.json({
        message: 'Hello World'
    });
});

app.listen(2020, () => {
    console.log('server is listening on port 2020');
});
```

And this is how I called it:

```javascript
fetch('http://localhost:2020').then(r => r.json()).then(console.log).catch(console.error)
```

My CSP on tauri.conf.json is `default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'`.

Please reach us on Discord if it still doesn't work.
