### ISSUE TITLE
CTA fails in yarn monorepo

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri#2034]
**Describe the bug**
CTA doesn't set the name property in the generated package.json, this causes the subsequent `yarn install` command to fail in a yarn monorepo.

**To Reproduce**
1. create an empty folder
2. run `yarn init`, answer private? with true and add `  "workspaces": [ "packages/*" ]` to the generated package.json
3. create an empty folder `packages` and enter
4. run `yarn create tauri-app` and choose any recipe and preset.
5. The installation fails at the `yarn install` stage

**Expected behavior**
The installation should succeed

**Screenshots**

**Platform and Versions (please complete the following information):**

OS: Mac OS, version 11.4.0 x64
Node: 16.0.0
NPM: 7.10.0
Yarn: 1.22.10
Rustc: 1.51.0

**Additional context**
I'm pretty confident that this is a simple to fix issue and I'd be happy to volunteer a PR, but if maybe @lucasfernog can confirm my suspicion that'd be great!

**Comment by lucasfernog** [comment]
I just ran the steps you provided and this is the error: `Command failed with exit code 1: yarn add --dev --ignore-scripts @tauri-apps/cli@latest`. Running the command outputs this:

```
yarn add --dev --ignore-scripts @tauri-apps/cli@latest
yarn add v1.22.4
info No lockfile found.
error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Seems like create-tauri-app needs workspace support.

**Comment by amrbashir** [comment]
Are you sure it happens with all recipes and not only vanilla ?

CTA uses each recipe's official bootstrapping tool, for example, react recipe uses `create-react-app` and it should be responsible for creating the `package.json` and the `name` field

**Comment by lucasfernog** [comment]
Seems like it doesn't even reach the recipe side, just fails installing @tauri-apps/cli.

**Comment by JonasKruckenberg** [comment]
@amrbashir I've tried the vite recipe and vanilla so yeah

~But it has already set up the package.json right?~ Nevermind it has to to that if course

**Comment by amrbashir** [comment]
> Seems like it doesn't even reach the recipe side, just fails installing @tauri-apps/cli.

if it fails there then the recipe part is done and now is preparing to do `tauri init`.

**Comment by amrbashir** [comment]
@JonasKruckenberg I hate to keep asking but can you try a recipe other than vite because it is broken right now ?

**Comment by JonasKruckenberg** [comment]
Yes I did, sorry for the confusion, I tried the vite first but since I heard it had problems I also tried the vanilla recipe to make sure it's really a bug
> The vite recipe worked for me in a separate directory though so I don't know 🤷🏻‍♂️

**Comment by amrbashir** [comment]
We create package.json for vanilla and it is supposed to have the name field. 
I will look into it later (in a week probably)

**Comment by amrbashir** [comment]
This should be fixed in the next release, please re-open if it still happens then.
