### ISSUE TITLE
[Bug] Windows 10 Command Line opens with Production Apps

### ISSUE THREAD

**Issue by tensor-programming** [tauri-apps/tauri#204]
**Describe the bug**
Production windows binaries open up a terminal window while they are running.  

**To Reproduce**
1. Build a Tauri app on windows. 
2. Run the Executable
3. See error

**Expected behavior**
The terminal window should not open for a production application. 

**Screenshots**
![win-bug](https://user-images.githubusercontent.com/22513880/71341066-cd34dc80-2526-11ea-89ba-8a713ede8192.png)

**Platform (please complete the following information):**
OS: Windows 10
Tauri Binding: Latest Dev
Bundle Target: Windows 10 edge & mshtml

**Additional context**
Bug results also when building with Webview alone.  

Issue on webview: https://github.com/Boscop/web-view/issues/111#issue-541612055

**Comment by nothingismagick** [comment]
From @khionu 
```
#![windows_subsystem = "windows"]
```
at the top of main.rs - that will prevent the console from showing

@BenoitRanque - can you see if this resolves that issue for you?

**Comment by BenoitRanque** [comment]
@nothingismagick I can confirm this does fix the issue!
I built the app using `yarn tauri:source:build`

**Comment by nothingismagick** [comment]
great news.

we should probably add that to the base template then.

**Comment by nothingismagick** [comment]
That lives here, FYI:
https://github.com/tauri-apps/tauri/blob/dev/cli/tauri.js/templates/src-tauri/src/main.rs#L1

**Comment by BenoitRanque** [comment]
There is a difference between the template and the quasar example main.rs
The first calls `tauri::AppBuilder::new().setup()`
The second calls `tauri::AppBuilder::new().invoke_handler()`
The second one also swallows errors, maybe we could use `.unwrap` here:
```rs
      match serde_json::from_str(arg) {
        Err(_) => {} // do nothing on error?
        Ok(command) => {
          match command {
            // definitions for your custom commands from Cmd here
            MyCustomCommand { argument } => {
              //  your command code
              println!("{}", argument);
            }
          }
        }
      }
```

**Comment by nothingismagick** [comment]
The example in Quasar uses the event listener, its a different approach than the standard.
