### ISSUE TITLE
Can't build for target i686-pc-windows-msvc

### ISSUE THREAD

**Issue by dizda** [tauri-apps/tauri#2040]
**Describe the bug**
Hi there,

Checked out the branch `tauri-v1.0.0-beta.1`, I can build smoothly for the target `x86_64-pc-windows-msvc`, but not for `i686-pc-windows-msvc` (windows 32-bit).

**To Reproduce**
I'm using the helloworld example.

```bash
$ git checkout tauri-v1.0.0-beta.1
$ cd examples/helloworld
$ cargo tauri build --target i686-pc-windows-msvc --verbose
   Compiling helloworld v0.1.0 (C:\Users\john\www\tauri\examples\helloworld\src-tauri)
    Finished release [optimized] target(s) in 2m 01s
info: Target: x64
info: Wix settings not found. Using `en-US` as language.
info: running candle for "main.wxs"
info: running candle.exe
Windows Installer XML Toolset Compiler version 3.11.2.4516
Copyright (c) .NET Foundation and contributors. All rights reserved.

main.wxs
info: running light to produce C:\Users\john\www\tauri\target\release\bundle/msi/helloworld_0.1.0_x64.msi
Windows Installer XML Toolset Linker version 3.11.2.4516
Copyright (c) .NET Foundation and contributors. All rights reserved.

C:\Users\john\www\tauri\target\release\wix\x64\main.wxs(71) : error LGHT0103 : The system cannot find the file 'C:\Users\john\www\tauri\target\release\helloworld.exe'.
Error: failed to bundle project

Caused by:
    Shell Scripting Error:`error running light.exe`

```

**Expected behavior**

It shouldn't be `info: Target: x64` but x86

**Screenshots**
<img width="979" alt="Screen Shot 2021-06-22 at 17 48 35" src="https://user-images.githubusercontent.com/1245245/122911994-136c3580-d382-11eb-8e36-6b3bff06ba29.png">

**Platform and Versions (please complete the following information):**
$ cargo tauri info

Operating System - Windows, version 10.0.19041 X64
Webview2 - 91.0.864.54

Node.js environment
  Node.js - 16.3.0
  @tauri-apps/cli - 1.0.0-beta.2
  @tauri-apps/api - Not installed

Global packages
  npm - 7.15.1
  yarn - 1.22.10

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/public
/src-tauri

App
  tauri.rs - path:"../../../core/tauri" [1.0.0-beta.1] (no lockfile)
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self'
  distDir - ../public
  devPath - ../public

**Comment by dizda** [comment]
Hi @lucasfernog 

Thanks for the patch.
It seems that it didn't fix the issue though, I've pull to the latest commit which includes https://github.com/tauri-apps/tauri/commit/8e2387018940e9e1421948d74a82156661ce2e4b, and re-built cli.rs but it doesn't seem to change anything about it.

<img width="838" alt="Screen Shot 2021-06-28 at 10 12 45" src="https://user-images.githubusercontent.com/1245245/123574065-679b6d80-d7f9-11eb-9609-1f5498dd9660.png">

The target is still x64.

**Comment by lucasfernog** [comment]
Seems like that's a different issue now.

**Comment by lucasfernog** [comment]
Btw did you check the correct bundle path? it's printed on the stdout.

**Comment by dizda** [comment]
Yes, the path is correct and contains the bundle.

<img width="843" alt="Screen Shot 2021-06-28 at 10 40 01" src="https://user-images.githubusercontent.com/1245245/123577018-3d4baf00-d7fd-11eb-8379-25a530c4f75c.png">

**Comment by lucasfernog** [comment]
Something must be wrong with the wix code. I'll check it tomorrow.

**Comment by dizda** [comment]
Sure, could you reopen the issue in the meanwhile? 🙏

**Comment by dizda** [comment]
Good job mate, it works like a charm now!

<img width="978" alt="Screen Shot 2021-06-29 at 09 07 10" src="https://user-images.githubusercontent.com/1245245/123726261-df30d180-d8b9-11eb-9688-cd8e78c37976.png">
