### ISSUE TITLE
Tasks spawned with `async_runtime::spawn`  don't execute when 3 sidecar commands have been executed

### ISSUE THREAD

**Issue by guillemcordoba** [tauri-apps/tauri#2042]
**Describe the bug**

Tasks spawned with `async_runtime::spawn`  don't execute when 3 sidecar commands have been executed.

**To Reproduce**
1. Execute 3 `Command::new_sidecar` in the `setup` hook of the application, with an `tauri::async_runtime::block_on` wrapper.
2. Try to `async_runtime::spawn`, or anything that uses that (eg and async command).
3. The spawned task won't execute.

**Expected behavior**

Operating System - Ubuntu, version 20.04 X64

Node.js environment
  Node.js - 16.3.0
  @tauri-apps/cli - 1.0.0-beta.2
  @tauri-apps/api - 1.0.0-beta.1

Global packages
  npm - 7.15.1
  yarn - 1.22.5

Rust environment
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/node_modules
/.git
/.github
/public
/src
/tests
/src-tauri

App
  tauri.rs - 1.0.0-beta.1
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - Set automatically by Vue CLI plugin
  devPath - Set automatically by Vue CLI plugin
  framework - Vue.js (Vue CLI)
  bundler - Webpack
**Additional context**

**Stack Trace**

**Comment by lucasfernog** [comment]
Can you share the code you're trying to execute?

**Comment by guillemcordoba** [comment]
This is what my main looks like:

```rust

fn main() {

  let quit = CustomMenuItem::new("quit".to_string(), "Quit");
  let show_admin = CustomMenuItem::new("show_admin".to_string(), "Show Admin");
  let _show_logs = CustomMenuItem::new("show_logs".to_string(), "Show Logs");

  let sys_tray_menu = SystemTrayMenu::new()
    // TODO: uncomment when async runtime works well
    // .add_item(show_logs)
    .add_item(show_admin)
    .add_native_item(SystemTrayMenuItem::Separator)
    .add_item(quit);

  let sys_tray = SystemTray::new().with_menu(sys_tray_menu);

  tauri::Builder::default()
    .system_tray(sys_tray)
    .on_system_tray_event(|app, event| {
      match event {
        SystemTrayEvent::MenuItemClick { id, .. } => match id.as_str() {
          "quit" => {
            // Closing all the windows exits the app and kills all the children processes
            for window in app.windows().values() {
              let _r = window.close();
              log::info!("Closing window {} {:?}", window.label(), _r);
            }
          }
          "show_admin" => {
            let admin_window = app.get_window("admin");

            if let Some(window) = admin_window {
              window.show().unwrap();
              window.set_focus().unwrap();
            } else {
              // Window was closed: we need to recreate it
              let _r = app.create_window(
                "admin".into(),
                WindowUrl::App("index.html".into()),
                move |window_builder, webview_attributes| {
                  (window_builder.title("Holochain Admin"), webview_attributes)
                },
              );
              log::info!("Creating admin window {:?}", _r);
            }
          }
          "show_logs" => {
            // logs::open_logs();
          }
          _ => {}
        },
        _ => {}
      }
    })
    .setup(|_app| {
      tauri::async_runtime::block_on(async move {
        match launch_children_processes().await {
          Ok(()) => (),
          Err(err) => {
            log::error!("There was an error launching holochain: {:?}", err);
          }
        }
        log::info!("Launch setup successful")
      });
      Ok(())
    })
    .invoke_handler(tauri::generate_handler![
      open_app_ui,
      install_ui,
      deactivate_app_ui,
      activate_app_ui
    ])
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}

async fn launch_children_processes() -> Result<(), String> {
  config::create_initial_config_if_necessary();

  Command::new_sidecar("lair-keystore")
    .or(Err(String::from("Can't find holochain binary")))?
    .args(&[
    "-d",
    config::keystore_data_path()
      .into_os_string()
      .to_str()
      .unwrap(),
    ])
    .spawn()
    .map_err(|err| format!("Failed to execute lair-keystore: {:?}", err))?;

  log::info!("Launched lair-keystore");

  thread::sleep(Duration::from_millis(1000));

  Command::new_sidecar("holochain")
    .or(Err(String::from("Can't find holochain binary")))?
    .args(&[
      "-c",
      config::conductor_config_path()
        .into_os_string()
        .to_str()
        .unwrap(),
    ])
    .spawn()
    .map_err(|err| format!("Failed to execute holochain: {:?}", err))?;

  log::info!("Launched holochain");

  thread::sleep(Duration::from_millis(1000));

  setup_conductor().await?;


  Command::new_sidecar("caddy")
    .or(Err(String::from("Can't find holochain binary")))?
    .spawn()
    .map_err(|err| format!("Failed to execute caddy: {:?}", err))?;
  Ok(())
}
```

After this setup is done, no spawned task gets executed. Maybe I'm doing something wrong?

**Comment by lucasfernog** [comment]
And which task is not being executed? I can only see the setup hook on your code, and it runs ok. Maybe you could come up with an example app to reproduce it?

**Comment by guillemcordoba** [comment]
For example this is not executing after the setup:

```rust
#[tauri::command]
pub async fn install_ui(app_id: String, ui_bundle_path: String) -> Result<(), String> {
...
```

And also 

```rust
async_runtime::spawn(async move {
  println!("hi");
});
```

Does not execute as well. I have tested that it is at least 3 sidecars spawned that cause this, with 2 it works fine.

I can try to provide a reproduction, yes

**Comment by lucasfernog** [comment]
Alright I think I can reproduce it, going to see what's happening.

**Comment by guillemcordoba** [comment]
Okey in another computer it seems to be happening with just 2 sidecars executing... So not sure what is happening in the background. Maybe a tokio runtime configuration thing?

**Comment by lucasfernog** [comment]
The `hi` is printed if I force kill one of the sidecar processes, so I think this is some kind of limitation with the number of spawned tasks on `tokio`. There's not much I can do, except reduce the number of tasks spawned by the sidecar (currently 3 for each command).

**Comment by guillemcordoba** [comment]
Isn't there some configuration that can remove that limitation for tokio?

**Comment by lucasfernog** [comment]
I don't think so.

**Comment by lucasfernog** [comment]
I'll push a PR that reduces the spawn count from 3 to 1 on each sidecar. I don't see an alternative solution :/

**Comment by guillemcordoba** [comment]
Thanks :) I'm experimenting with this:

```rust


static RUNTIME: OnceCell<Runtime> = OnceCell::new();

fn create_runtime() -> Runtime {
  runtime::Builder::new_multi_thread()
    .worker_threads(20)
    .enable_all()
    .build()
    .unwrap()
}

/// Run a future to completion on runtime.
pub fn block_on<F: Future>(task: F) -> F::Output {
  let runtime = RUNTIME.get_or_init(|| create_runtime());
  runtime.block_on(task)
}

/// Spawn a future onto the runtime.
pub fn spawn<F>(task: F)
where
  F: Future + Send + 'static,
  F::Output: Send + 'static,
{
  let runtime = RUNTIME.get_or_init(|| create_runtime());
  runtime.spawn(task);
}
```

It seems the default spawn limit is the number of cores your CPU has.

**Comment by lucasfernog** [comment]
Yeah that's what I imagined.

**Comment by lucasfernog** [comment]
Hmm we could use this, but I'm not sure it's a good idea to increase the default value: https://docs.rs/tokio/1.7.1/tokio/runtime/struct.Builder.html#method.worker_threads

**Comment by guillemcordoba** [comment]
I understand... It does the trick though, I'm able to create 3 sidecars and spawn more things :)

**Comment by lucasfernog** [comment]
#2044 will also fix it for your use case.

**Comment by guillemcordoba** [comment]
Yeap just saw it, thanks!

Your real-time support is really appreciated.
