### ISSUE TITLE
multiwindow to side by side 

### ISSUE THREAD

**Issue by cheng990629** [tauri-apps/tauri#2076]
**Is your feature request related to a problem? Please describe.**
multiwindow to side by side 
or
create subWindow() 
or 
create Plugin html()

**Comment by nothingismagick** [comment]
This makes no sense to me, sorry.

**Comment by cheng990629** [comment]
> This makes no sense to me, sorry.

how to \<webview\>?

**Comment by nothingismagick** [comment]
I am sorry if it sounded rude, but I am still not sure what you want. Have you looked in the documentation, for example here:

https://tauri.studio/en/docs/guides/splashscreen

Alternatively, please write in your primary spoken language and I will try to translate.

**Comment by cheng990629** [comment]
非常感谢，最后问一下，怎样使用electron 中的\<webview\> tabs功能，独立并行两个app

**Comment by Laegel** [comment]
I guess they'd like to use a webview HTML element in a webview window, a bit like Electron does.

**Comment by cheng990629** [comment]
> I guess they'd like to use a webview HTML element in a webview window, a bit like Electron does.

YES

**Comment by wusyong** [comment]
[Webview tag](https://developer.chrome.com/docs/extensions/reference/webviewTag/) is already deprecated by Chrome which electron uses it.

**Comment by lysdexic-audio** [comment]
Being able to [do this ](https://www.electronjs.org/docs/latest/api/browser-view) would make me jump from Electron to Tauri immediately. 

I am assuming this what the original request was about. I can't see why this was closed, actually. Please consider reopening.

**Comment by FabianLars** [comment]
@lysdexic-audio Please take a look at #2709 which is explicitly about BrowserView.
