### ISSUE TITLE
Target triple mismatch

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri#2084]
### **Describe the bug**
The recently updated documentation provides a code snippet that automatically appends the target triple to a binary. I noticed, however that there is a mismatch between the llvm target triple and the rust target triple.
I suspect this mismatch is also present for different platforms, but in my case it is as follows:
LLVM target triple:
`x86_64-apple-macosx10.7.0`
rust target triple:
`x86_64-apple-darwin`

### **To Reproduce**
1. Use the script provided in the docs to rename you sidecar binary
2. Call it from rust using Command::new_sidecar
3. The thread panics

### **Expected behavior**
The generated sidecar name should match the one expected by Tauri at runtime.

### **Platform and Versions (required):**

```
Operating System - Mac OS, version 11.4.0 X64

Node.js environment
  Node.js - 16.0.0
  @tauri-apps/cli - 1.0.0-beta.1
  @tauri-apps/api - 1.0.0-beta.2

Global packages
  npm - 7.10.0
  yarn - 1.22.10

Rust environment
  rustc - 1.51.0
  cargo - 1.51.0

App directory structure
/dist
/node_modules
/src-tauri
/src

App
  tauri.rs - 1.0.0-beta.2
build-type - bundle
CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
distDir - ../dist
devPath - http://localhost:3000
framework - React
```

**Comment by nothingismagick** [comment]
I can confirm, this happened to me as well.

**Comment by lucasfernog** [comment]
Seems like we should use [`rustc -vV`](https://github.com/rust-lang/cargo/blob/1dae5acb7d27568ca30fe2da49b4a447d7b78e90/src/cargo/util/rustc.rs#L50-L68) instead.
