### ISSUE TITLE
Support for accessing files from local filesystem with in html 

### ISSUE THREAD

**Issue by shareejvk** [tauri-apps/tauri#2085]
As of now, I am not able to access files from the local file system within HTML.
Reading files as binary then converting to base64 cant be considered as a solution to this issue as this is super slow especially for video files.
I believe local file system access within the renderer is a very basic requirement.

**Comment by nothingismagick** [comment]
You don't need to file the same issue in 2 repos. Closing in favor of wry.

**Comment by reivilibre** [comment]
For those arriving from elsewhere: this was superseded by https://github.com/tauri-apps/tauri/issues/2103 AFAICT
