### ISSUE TITLE
[docs] Add ARCHITECTURE doc to update-docs workflow for website

### ISSUE THREAD

**Issue by thadguidry** [tauri-apps/tauri#2088]
> @Laegel ARCHITECTURE doc has been recently created, the idea was to copy it on the update-docs workflow so it appears in the website. Totally forgot that. :smile:

**Comment by facklambda** [comment]
Hey folks, 

I can probably grab this. Playing around with workflows currently for work and personal projects so this should be simple.

/claim

I'm going to just move the ARCHITECTURE.md doc to the /docs folder, so it gets copied over with all the others.

I'll also modify the link to the ARCHITECTURE.md file in the intro.md file to reflect the new filepath.
