### ISSUE TITLE
Built app window is missing styles

### ISSUE THREAD

**Issue by olup** [tauri-apps/tauri#2089]
### **Describe the bug**
My dev app looks like : 
![image](https://user-images.githubusercontent.com/13785588/123523386-80a20280-d6c3-11eb-90a0-beeb183acd6f.png)

But my built app looks like:
![image](https://user-images.githubusercontent.com/13785588/123523414-a8916600-d6c3-11eb-8f03-c5eefecc1e3e.png)

Notice the black line on top and the absence of shadows. Also - cursor never goes into "pointer" style in the built version.

### **Expected behavior**
Same window style in dev and build

### **Platform and Versions (required):**

```
Operating System - Ubuntu, version 21.04 X64

Node.js environment
  Node.js - 14.15.5
  @tauri-apps/cli - 1.0.0-beta.3
  @tauri-apps/api - 1.0.0-beta.2

Global packages
  npm - 6.14.11
  yarn - 1.22.10

Rust environment
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/public
/build
/.github
/node_modules
/.git
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.2
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:4000
  framework - React
```

**Comment by nothingismagick** [comment]
The only thing that pops out at me is that you are missing `tauri:` in your CSP

**Comment by olup** [comment]
Can I ask if and how I should add this ?

**Comment by nothingismagick** [comment]
Sure, edit the `CSP` value in `tauri.conf.json`:

```
"default-src blob: data: filesystem: ws: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'"
```

**Comment by olup** [comment]
Added tauri: - but no changes on the output.

**Comment by nothingismagick** [comment]
I didn't really expect it to change anything in this situation, just wanted to make you aware of it. Do you have a repo where we can try to reproduce?

**Comment by olup** [comment]
The project I am working on is public on github : https://github.com/olup/fragment-desk
It's just a sketch - no judgement :-) (plus rust is not my mother-tongue).

I should try to build a fresh project on my machine when I get the time and see if it get the same bug (but I don't have much time those days).

**Comment by amrbashir** [comment]
related to tauri-apps/tao#157

**Comment by amrbashir** [comment]
closing in favor of #3019
