### ISSUE TITLE
feature: change app name in toast notifications

### ISSUE THREAD

**Issue by joaobsantos** [tauri-apps/tauri#2092]
**Is your feature request related to a problem? Please describe.**
It was pointed to me that the notification crate uses windows powershell

**Describe the solution you'd like**
I'd like to have the name of my apllication instead of Windows PowerShell or even better, to edit the name, because I can have one exe, with multiple "apps".

Ex: 2 routes in the same exe.

Route 1:  /chat: notification toast says "CompanyName: Chat" 
Route 2:  /alerts: notification toast says "CompanyName: Alerts" 

**Additional context**
![image](https://user-images.githubusercontent.com/14371776/123538011-70713e00-d72a-11eb-9c30-0f07625bb087.png)

**Comment by joaobsantos** [comment]
@lucasfernog  can I help implement this? Need some pointers... thx

**Comment by lucasfernog** [comment]
That app name is for dev only. On build you should see your own app name.

**Comment by lucasfernog** [comment]
Not sure if you can change it dynamically, I think you can't.

**Comment by lucasfernog** [comment]
The app name is determined from the bundle id: https://allenbenz.github.io/winrt-notification/0_1_3/winrt_notification/struct.Toast.html
I don't think you can have multiple bundle ids on the same binary, so this is impossible to do.

**Comment by lucasfernog** [comment]
Please reopen if you find something that we can implement.

**Comment by joaobsantos** [comment]
Thanks Lucas I just figured this out and came here to tell, that if I do the msi setup the exe that he creates solves this problem, I thought that the exe in the release folder was the same... Next time I will check the issue first :) Thx

**Comment by amrbashir** [comment]
@joaobsantos that's my bad not yours, I checked the `notify-rust` crate code on a hurry and told you to open a false issue.

**Comment by joaobsantos** [comment]
No worries, it's the best way for me to learn is to talk to you guys :) thx
