### ISSUE TITLE
Warn about scoped names

### ISSUE THREAD

**Issue by balbatross** [tauri-apps/tauri#2099]
**Is your feature request related to a problem? Please describe.**
I'm building from a scope mono repo and when the package name starts with @ tauri build fails with little context and the following message (Error: No such file or directory (os error 2))

**Describe the solution you'd like**
Warn during init that scoped names are invalid or remove the scoping and snake case the result

**Comment by nothingismagick** [comment]
probably better for us to be smarter about that than to offer workarounds.

**Comment by lucasfernog** [comment]
I'm not sure the scoped name is the problem here. Can you create a repo with a project to reproduce it?

**Comment by lucasfernog** [comment]
I think #2114 fixes it and the problem is when the product name has slashes. Let me know if you still face any issues.
