### ISSUE TITLE
Provide access to the event loop

### ISSUE THREAD

**Issue by mjhouse** [tauri-apps/tauri#2127]
**Is your feature request related to a problem? Please describe.**
I am attempting to write a program that needs to poll a function on a regular basis.

**Describe the solution you'd like**
I would like to be able to provide a function to the tauri::Builder instance that will be called once-per-iteration inside the event loop.

**Describe alternatives you've considered**
I've considered and partially implemented a thread-based solution which will be much more complex and difficult to work with.

**Additional context**
The program in question is for p2p chat, but I think most large applications that communicate across a network would need similar functionality.

**Comment by tqwewe** [comment]
I see this was closed with a commit, but I'm not quite clear on how to get access to the event loop still. Any ideas?

**Comment by Xinyu-Li-123** [comment]
> I see this was closed with a commit, but I'm not quite clear on how to get access to the event loop still. Any ideas?

I think this is documented in the [Event feature](https://tauri.app/v1/guides/features/events/) on Tauri's official website. It allows you to `emit` an event with custom label and custom payload, and to `listen` to any event by its label.
