### ISSUE TITLE
After building on Mac M1 .app .dmg is not working on other M1 Mac

### ISSUE THREAD

**Issue by leimantas** [tauri-apps/tauri#2144]
### **Describe the bug**
After building app on my M1 MAC - app and dmg works fine on my laptop.
Tried to launch both on other M1 MAC - got error that files are damaged.

Also tried to sign app with custom self signed keychain cert. Not helped.

### **To Reproduce**
1. clone repo [https://github.com/leimantas/tauri-test](https://github.com/leimantas/tauri-test)
2. Build it on M1 Mac
3. Try to launch app on other M1 Mac

### **Screenshots**
![image](https://user-images.githubusercontent.com/46538777/124366760-57005280-dc52-11eb-9b46-0b32302478ce.png)

### **Platform and Versions (required):**
Operating System - Mac OS, version 11.4.0 X64

Node.js environment
  Node.js - 16.4.0
  @tauri-apps/cli - 1.0.0-beta.5
  @tauri-apps/api - Not installed

Global packages
  npm - 7.18.1
  yarn - 1.22.10

Rust environment
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/dist
/node_modules
/src-tauri
/.git
/src

App
  tauri.rs - 1.0.0-beta.4
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:3000
  framework - React

**Comment by leimantas** [comment]
After updates today - it works.

**Comment by tleyden** [comment]
Is this the same as https://github.com/tauri-apps/tauri/issues/5778?

**Comment by donkey-donkey** [comment]
is there a fix besides getting an Apple Dev account and signing it that way?
