### ISSUE TITLE
Dialog with custom buttons

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tauri#2147]
I'd like to have a dialog that asks if the user wants to save, with the buttons `Don't Save` (secondary highlight), `Cancel` and `Save` (primary highlight).

Right now, the only option seems to be to have a Yes/No dialog

**Comment by nothingismagick** [comment]
This is more customisation than we can offer, mostly because of decades old standards. I recommend you call a new tauri window, and if you need to trigger such a thing from JS land, then build a proper tauri plugin. When you succeed, please let us know so we can add your experience to the tutorial series.

**Comment by probablykasper** [comment]
@nothingismagick What exactly is blocking it? Why wouldn't it be possible if Electron is able to do it in [dialog.showMessageBox](https://www.electronjs.org/docs/api/dialog#dialogshowmessageboxbrowserwindow-options)?

**Comment by nothingismagick** [comment]
This is a `give-a-mouse-a-cookie` long-tail feature. Next I would want a data entry field. And then password injection / protection. And fully stylable for my app. Maybe without copy buffer access. And hey, while we're at it, lets rewrite copy buffer to make app specific encrypted buffers. And then cold fusion to kickstart antimatter entropy and non-temporal dimensional folding.

Ok, maybe that went a little far, but customization of that kind of feature will be brittle on all platforms if your thinking is limited to the classical browser prompt. I think it would be better to document a multi window approach where you are in absolute control and own your security posture. And heck, maybe even a non-webview password entry field. Lets see.

**Comment by probablykasper** [comment]
Sure, it's fair to say it's a slippery slope, but I don't quite see what makes that bad.

I'm clueless about this, but custom buttons sounds like something every major OS would support. Data entry and password protection might make sense to consider down the road. Anything beyond that seems to pretty clearly be off limits.

Would be simple enough to make a webiew dialog, but would be great to be able to have a native one.

**Comment by nothingismagick** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt

**Comment by nothingismagick** [comment]
I am not aware of a spec that would enable you to change the labels and number of interface buttons. Can you find one?

**Comment by nothingismagick** [comment]
Furthermore, any of the three (alert, prompt, confirm) will block media asset loading and for all intents and purposes are like a poor-man's breakpoint.

**Comment by nothingismagick** [comment]
Maybe I am overthinking this though, which is why I reopened the feature request.

**Comment by probablykasper** [comment]
Ah, I didn't think about the fact that browser dialog APIs exist. The idea would be for this to be an addition to [tauri::api::dialog](https://docs.rs/tauri/1.0.0-beta.4/tauri/api/dialog/index.html). I don't think the browser dialog APIs are too relevant here because those are for websites. Sorry if I confused you

**Comment by lucasfernog** [comment]
First we'd need custom buttons support on [rfd](https://github.com/PolyMeilex/rfd).

**Comment by lucasfernog** [comment]
We're getting closer with #4383

**Comment by amrbashir** [comment]
closed by https://github.com/tauri-apps/tauri/pull/4383
