### ISSUE TITLE
Clicking/focusing app does not reveal hidden windows

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tauri#2149]
### **Describe the bug**
If I call `window.hide()` and then click the app icon in the Dock or cmd+tab into the app, the hidden window does not reveal itself.

### **To Reproduce**
1. Reproduction branch: https://github.com/probablykasper/tauri-hide-reveal-bug
2. `npm install`
3. `npm run dev`
5. Click the `Hide window` button
6. Click the app

### **Expected behavior**
When an app window is hidden, clicking or cmd+tabbing into the app should reveal the hidden window. I'm not sure what the behavior should be when there are multiple windows, though I suspect it's to show em all.

### **Platform and Versions (required):**
```
Operating System - Mac OS, version 10.15.7 X64

Node.js environment
  Node.js - 14.16.0
  @tauri-apps/cli - 1.0.0-beta.5
  @tauri-apps/api - 1.0.0-beta.4

Global packages
  npm - 6.14.11
  yarn - 1.22.10

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/node_modules
/src-tauri
/build
/.git
/src

App
  tauri.rs - 1.0.0-beta.4
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:5000
  framework - Svelte
```

(ik rust isn't on 1.53, can update if needed)

**Comment by amrbashir** [comment]
I believe this is the expected behavior, hiding a window is not the same as minimizing it. If a window is hidden, you have to call `win.show()`.

**Comment by probablykasper** [comment]
You're absolutely right, I'm not thinking straight. Was trying to get the standard window closing behavior where the window is just hidden (like Activity Monitor, or default Electron behavior)

**Comment by amrbashir** [comment]
can you alt-tab into a hidden electron window? well @lemarier is the expert on macOS, lets hear what he thinks of this. 

Edit: electron has some interesting notes here https://www.electronjs.org/docs/api/browser-window#page-visibility

**Comment by probablykasper** [comment]
I tried Electron's `mainWindow.hide()`, tabbing into the app did not reveal the window.

If you close the window (clicking the red x or CMD+W or File > Close Window), tabbing into the app does reveal it.

Might be worth opening an issue to figure out how to go about that behavior

**Comment by lucasfernog** [comment]
AFAIK that's implemented on the app level using Electron's activate event.

**Comment by probablykasper** [comment]
@lucasfernog Ah you're right. Should I open an issue for supporting that?
