### ISSUE TITLE
Setting default headers such as User-Agent and Accept-Language

### ISSUE THREAD

**Issue by Verequies** [tauri-apps/tauri#2156]
I'm not sure if its possible as I have not figured out how to set the default headers yet, but it would be great if there were settings exposed that could be configured before building to set the default header values.

**Comment by flydev-fr** [comment]
I dont know how you are using the http client inside your app, this is what I am doing to get an http client, with default custom headers:

in `https.ts`

```ts
export const defaultHeaders = {
  'User-Agent': 'Tauri Client Fetch',
  'X-Requested-With': 'XMLHttpRequest',
  'x-api-key': siteConfig.currentApiKey,
}

export const http = function<T>(url: string | URL) {
  if(url instanceof URL)
    url = url.href

  return fetch(url, { headers: defaultHeaders, method: 'GET' })
    .then(response => {
      if (!response.ok) {
        throw new Error(response.statusText)
      }
      return response.json() as Promise<{ data: T }>
    })
    .then(data => {
        return data.data
    })
}
```

**Comment by Verequies** [comment]
Thanks for the suggestion, however I'm not sure if that will work here. I need to be able to set the default Tauri User-Agent and other headers as making the requests are a bit out of my control in my application.

**Comment by nothingismagick** [comment]
Which side is making the request? The Webview side (likely more dangerous) - or the Rust side (potentially more complicated)?

**Comment by Verequies** [comment]
The frontend (browser/web side). The requests are running in an IFrame of which I have no control over.

**Comment by nothingismagick** [comment]
Do you know how the requests' headers are appearing at the remote endpoints?

**Comment by Verequies** [comment]
I am not in control of the remote server, so no. But I know how they should appear. Hence the need to modify the headers by default.

**Comment by nothingismagick** [comment]
So how should they appear, exactly?

**Comment by Verequies** [comment]
The User-Agent should appear as a custom set agent instead of the default Tauri Agent. And Accept-Language should appear as a custom set value instead of the default Tauri value also.

**Comment by nothingismagick** [comment]
Well, here is how I see it:

This is not within the scope of Tauri Best Practice, and even if it were possible (I am not saying it isn't) this is likely to stay a very low priority for us. There are already 2 existing and functional ways to do what you are requesting (the fetch approach outlined above by @flydev-fr ) and using the rust side of the http API provided by Tauri. I am not going to judge you for wanting to spoof your agent to sites you don't control (heck, maybe there is a really valid reason for this) - but its not within current scope.

That said, if you are interested in providing a PR that can do this efficiently on macOS, Linux and Windows (and iOS too) then the right place to file a new feature request would be at https://github.com/tauri-apps/wry

**Comment by Verequies** [comment]
Okay, I'll give it a go. There is a valid reason for this. I cannot speak much about it as it is an in house application from another organisational unit that I am collaborating with, on strict guidelines.
