### ISSUE TITLE
Message loop on Windows

### ISSUE THREAD

**Issue by flydev-fr** [tauri-apps/tauri#2157]
Not an issue - It is possible to send and receive messages from a Tauri app between process ?

I am talking about `PostMessage()` and `SendMessage()` on Windows.

**Comment by amrbashir** [comment]
well, This is out of tauri scope. However you can get the window handle by calling `window.hwnd()` and use that with `winapi` or `windows-rs` crates as you like.

**Comment by flydev-fr** [comment]
Thanks, just for myself, why it is out of scope of Tauri ?

**Comment by amrbashir** [comment]
Communicating with other processes is a rare use case and it would be really hard to provide a unified interface across all the platforms we support.

**Comment by amrbashir** [comment]
We can only provide you with the means to help you achieve this as you see fit. For Windows we provide `win.hwnd()` and for Linux `win.gtk_window()`.
If you need access to other low level handles, you should open a feature request and we will try to provide it if we can.

**Comment by flydev-fr** [comment]
Ok thanks for the explanation. The project I am developping might be a good use case for Tauri and theses sort of informations could give hints to others devs.

I am using Tauri to embbed a ViteJS/Vue frontend app to get a really nice user interface (UI) which need to communicate with a custom server written in Pascal hosted on the same plateform. This plateform is a custom made terminal deployed inside hospital's halls (like terminals found on Airports).

This (ORM) server (can) could serve data from an API endpoint, but some others native applications have to get thoses messages, that's why I asked how to send and receive theses messages.

I will jump on discord next time 🤙

**Comment by amrbashir** [comment]
In that case you don't even need `win.hwnd()` you can just `SendMessage` with the targeted window handle, however you'd need `win.hwnd()` if you want to receive messages (attach a subclass procedure). I'd be happy to discuss it more on discord if you want.

**Comment by flydev-fr** [comment]
Ok thanks @amrbashir I will give a try this afternoon and will jump on discord to discuss it 👍

**Comment by AmyrAhmady** [comment]
Hi there.
Have you ever managed to get this working? @flydev-fr 
I've been spending the entire day and can't get it to work. no matter what I do it just doesn't receive it
I'm basically trying to emulate mouse movement from another app, into my Tauri's.

**Comment by flydev-fr** [comment]
Hi @AmyrAhmady no sorry and got away from Tauri years ago. There are opened issues asking for this feature and the answer seem to be `window.hwnd()` which still look limited nowadays #11650.

I don't know which sort of application you are building, the only suggestion I can give you is to give a try to CEF (chromium embedded) - bindings can be found [there](https://github.com/tauri-apps/cef-rs/tree/dev), dealing with [windows messages](https://github.com/tauri-apps/cef-rs/blob/48968d48d444223a0d8699448ef84ea9c5699f5c/sys/src/bindings/x86_64_pc_windows_msvc.rs#L926-L933) is easy with cef. I can't affirm it will work, you might have to spend another day trying to figure it 😆

**Comment by AmyrAhmady** [comment]
@flydev-fr @amrbashir Welp
Another day went by, and I made it possible, finally! 😵
The problem with CEF and other libraries are they're "big" in size for my users to download. They're part of a community of the old game GTA San Andreas and the multiplayer mod for it. The Tauri app here is a game launcher that has a server browser in it as well, and I wanted to have it integrated built into the game too, without bare minimum effort without recreating everything or moving to a new project. And here is the result

### What's happening here:
I'm creating a child window which loads the same "web page" from the original Tauri app window, but the position is set to somewhere offscreen and I'm manually capturing the window into bitmap and then create a DirectX9 texture for it to render in the game. I wanted to forward every input when texture is shown, from game to the off-screen Tauri window. And here is the result:

https://github.com/user-attachments/assets/92c4063d-4c73-44d6-ae5b-336ded430db6

(Window is only shown for demonstration and testing purposes, in production it should be far from display boundaries)

And the trick is... sending WndProc messages using `PostMessage` or `SendMessage` from anywhere you want to **a child window of your Tauri app, with class name as `Chrome_RenderWidgetHostHWND`.**
Just a snippet:
```cpp
HWND FindWebView2Child(HWND tauriWnd)
{
	HWND found = nullptr;
	EnumChildWindows(tauriWnd, [](HWND hwnd, LPARAM lParam) -> BOOL
		{
			char className[256];
			GetClassNameA(hwnd, className, sizeof(className));
			if (std::string(className) == "Chrome_RenderWidgetHostHWND")
			{
				*(HWND*)lParam = hwnd;
				return FALSE; // stop enumeration
			}
			return TRUE; // continue
		},
		(LPARAM)&found);
	return found;
}
```
And the returned window handle is what you should use for sending messages to.

Hope this helps people now and in future when they come across it. ❤️
