### ISSUE TITLE
Allow for devtools to be disabled

### ISSUE THREAD

**Issue by AsyncBanana** [tauri-apps/tauri#2158]
**Is your feature request related to a problem? Please describe.**
Since Tauri is security-focused, it would make sense to give an option to disable devtools for the webview in production, to prevent users from viewing the source.

**Describe the solution you'd like**
The ability to add an option in tauri.conf.json that disables devtools.

**Describe alternatives you've considered**
Using hacks like disabling the right-click menu and keyboard shortcuts.

**Comment by lucasfernog** [comment]
Which platform are you seeing the devtools on production build? It should be disabled by default.

**Comment by AsyncBanana** [comment]
Webview2, although I just realized it might be a problem on my end. Sorry for taking your time, and I will check more thoroughly next time

**Comment by alfons** [comment]
I also have this problem. I'm completely new to Tauri. Everything went super smooth with the setup and release build (npx tauri build) but I've now spent 3+ hours trying to get rid of "Inspect Element" from the right-click context menu, and to try to disable devtools in production, but for the life of me can't disable devtools. MacOS. I've searched the internet for 1 hour and for 2 hours did everything Grok and ChatGPT suggested but to no avail. Is there any undocumented switch or flag or setting to hide "Inspect Element" and prevent devtools from opening?
./src-tauri/target/release/bundle/macos/myapp.app

**Comment by FabianLars** [comment]
@alfons Make sure there is no "devtools" feature flag in the features array of the tauri dependency in Cargo.toml and recompile the app. that's the only toggle there is so if this doesn't help then maybe another rust dependency of yours enabled that feature.

**Comment by alfons** [comment]
@FabianLars thank you for your swift reply! Unfortunately, that is not the case (at least for me, or I missed a setting I need to adjust?) Anyone can open developer tools in the final build. Just right click and choose "Inspect Element" and the full developer tool is available on the production Tauri app. How to reproduce with a clean install:

sh <(curl https://create.tauri.app/sh)
cd tauri-app
npm install
npm run tauri build
/Users/alfons/Projekte/my-tauri-app/tauri-app/src-tauri/target/release/bundle/macos/tauri-app.app 

![Image](https://github.com/user-attachments/assets/c16230bd-0843-4f7e-a33c-f5431b58e8ca)
![Image](https://github.com/user-attachments/assets/6501bd8c-b4ac-4777-b795-77ea7ea84a48)

How can I turn devtools off in the final, production app?

**Comment by FabianLars** [comment]
Which macOS version are you using?

**Comment by alfons** [comment]
@FabianLars Sequoia 15.4.1, all pretty out of the box, except that I had x-code downloaded and standard installed as well.

**Comment by grad44** [comment]
Any updates on this topic? I have the same issue as @alfons on macOS Sequoia 15.6.1

**Comment by alfons** [comment]
@grad44 as far as I could figure it out, there's no way to switch of devtools, which can expose all your code. Instead, we need to completely remove the right click context menu, to close this road for a user simply opening devtools via right click. I did it like this:

``` rs
// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

fn main() {
    tauri::Builder::default()
        .setup(|app| {
            // Load the window config from tauri.conf.json
            let window_config = app.config()
                .app
                .windows
                .first()
                .cloned()
                .ok_or_else(|| "No window config found")?;

            let window = tauri::WebviewWindowBuilder::from_config(app, &window_config)?
                .initialization_script(r#"
                    document.addEventListener('contextmenu', (e) => {
                        e.preventDefault();
                    });
                "#)  // Early context menu block
                .build()?;

            // Optional: Show the window after setup
            window.show()?;

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

Of course this also makes the MacOS built in "Translate" and "Look Up" features inaccessible, which troubles me because I would have liked to use those. But better than exposing all of my code via a simple right click.
