### ISSUE TITLE
Apostrophes in App Window Title Breaks Build

### ISSUE THREAD

**Issue by e-l-i-j-a-h** [tauri-apps/tauri#2159]
### **Describe the bug**
When I add an apostrophe in the default window title in `tauri.conf.json` and build my app, I am met with an "custom.protocol.taurilocalhost’s server IP address could not be found." screen in the webview upon running. 

### **To Reproduce**
1. Open `tauri.config.json`
2. Find the default window object under the `"windows"` array and add an apostrophe to the `"title"` property's value.
3. Save the file and run `yarn tauri build` to build the app.
4. Run the compiled executable under `src-tauri/target/release`.

### **Expected behavior**
The app should open normally and run as expected.

### **Screenshots**
<img width=600 src="https://user-images.githubusercontent.com/13988479/124535387-03257300-dde4-11eb-84b4-0ffd4e53d702.png">

### **Platform and Versions (required):**

```
Operating System - Windows, version 10.0.19041 X64
Webview2 - 91.0.864.64

Node.js environment
  Node.js - 14.15.5
  @tauri-apps/cli - 1.0.0-beta.5
  @tauri-apps/api - 1.0.0-beta.4

Global packages
  npm - 6.14.11
  yarn - 1.22.10

Rust environment
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/node_modules
/src-tauri

App
  tauri.rs - 1.0.0-beta.4
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - html5
  devPath - http://localhost:5500
```

### **Additional context**
I have not tested this particular app on Linux or any other operating systems.

**Comment by lucasfernog** [comment]
This is not related to the apostrophe. It has been fixed on wry and will be released soon.

**Comment by e-l-i-j-a-h** [comment]
Just found your bug fix in the wry repo. I somehow didn't see the original  "ERR_NAME_NOT_RESOLVED" bug report here before I submitted this issue. I also tried adding and removing the apostrophe enough times before building that I thought it was the real culprit. Anyways, thank you for your bug fix.
