### ISSUE TITLE
minHeight and maxWidth used together causes fixed window height on macOS

### ISSUE THREAD

**Issue by scrmea** [tauri-apps/tauri#2163]
### **Describe the bug**
Tauri docs mention the following configuration options:

```
minWidth
minHeight
maxWidth
maxHeight
resizable**?**
```

Those options do not work as expected on macOS. 

Setting both minHeight and maxWidth cause the window to be of fixed height (minHeight) and it can only be resized in width hereafter.

### **To Reproduce**
Add the following to tauri.conf.json:

```
"windows": [
      {
        "title": "Tauri App",
        "minHeight": 100,
        "maxWidth": 1200,
        "resizable": true
      }
```
open on macOS 11.4.

### **Expected behavior**
The window opens at a default height/width and the window can be resized to 100 <= height, width <= 1200. 

### **Platform and Versions (required):**
```
Operating System - Mac OS, version 11.4.0 X64

Node.js environment
  Node.js - 16.2.0
  @tauri-apps/cli - 1.0.0-beta.3 (outdated, latest: 1.0.0-beta.5)
  @tauri-apps/api - Not installed

Global packages
  npm - 7.19.1
  yarn - 1.22.10

Rust environment
  rustc - 1.55.0-nightly
  cargo - 1.54.0-nightly

App directory structure
/dist
/node_modules
/public
/src-tauri
/.vscode
/src

App
  tauri.rs - 1.0.0-beta.2
  framework - Svelte
```
same result with
```
tauri = { git="https://github.com/tauri-apps/tauri", branch = "dev", features = ["fs-create-dir", "fs-read-text-file", "fs-write-file", "menu"] }

Node.js environment
  @tauri-apps/cli - 1.0.0-beta.5
  @tauri-apps/api - 1.0.0-beta.4

App
  tauri.rs - 1.0.0-beta.4
```

**Comment by amrbashir** [comment]
this is [fixed](https://github.com/tauri-apps/tauri/pull/2247) in the dev branch and will be available in the next release.
