### ISSUE TITLE
API call fails in Vue + Node App

### ISSUE THREAD

**Issue by NitinRamnani** [tauri-apps/tauri#2168]
### **Describe the bug**

Hi, I'm trying to create an app for Mac OS with Vue on frontend and Node on backend. I created a binary of my Node app using pkg npm package and have added it in externalBin also configured it in sidecar but the issue is that when I make an API call it gives below error.

"Failed to load resource: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection."

### **Platform and Versions (required):**

```
Operating System - Mac OS, version 10.15.7 X64

Node.js environment
  Node.js - 12.22.2
  @tauri-apps/cli - 1.0.0-beta.3
  @tauri-apps/api - Not installed

Global packages
  npm - 6.14.13
  yarn - 1.22.10

Rust environment
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/test
/dist
/.metadata
/target
/src-tauri-org
/node_modules
/server
/static
/scripts
/src-tauri
/dist_electron
/build
/.git
/.vscode
/electron
/src

App
  tauri.rs - 1.0.0-beta.4
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist/
  devPath - https://localhost:8080
  framework - React
```

**Comment by nothingismagick** [comment]
You don't need to file an issue and start a discussion.

**Comment by NitinRamnani** [comment]
Adding plist to the project solves the issue.

**Comment by saikiran-chatti** [comment]
Hi @NitinRamnani, I am new to Tauri and trying to convert the MERN stack web app to a desktop app. But I couldn't connect front end to backend in tauri.  Can you provide any resources to solve the problem?

**Comment by nothingismagick** [comment]
@jayanthsaikiran - please visit our Discord and ask your question there in #help-triage. Without more insight into your exact situation, we can't help you. Also, please don't comment on closed issues - there is no guarantee you will get a response.
