### ISSUE TITLE
feat: hot reload dev for static files

### ISSUE THREAD

**Issue by SOVLOOKUP** [tauri-apps/tauri#2173]
When I modify the front static file, I hope `tauri dev` can automatically hot reload.

**Comment by Laegel** [comment]
Hey @SOVLOOKUP ! 
Thanks for this suggestion. We've been talking about it and came to the conclusion we could work on such feature, probably once we've passed the security audit. :smile:

**Comment by vsnthdev** [comment]
I use [Live server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) in VSCode to and configure `tauri.conf.json` to point to the default port of Live server like so 👇

```json
{
    "build": {
        "devPath": "https://localhost:5500"
    }
}
```
and I don't think `tauri` should implement a custom live server, almost all programming languages and development environments have their own live server/dev server so it would be pointless to re-implement the same thing again.

**Comment by lucasfernog** [comment]
Yeah Tauri would probably just leverage one of the existing dev servers libraries and expose it to the users. `Live server` is a very good idea, I think we can close this and reopen if more people request this feature.

**Comment by rajbits** [comment]
More people requesting this feature :)

**Comment by arnaudambro** [comment]
> I use [Live server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) in VSCode to and configure `tauri.conf.json` to point to the default port of Live server 

I use `create-react-app` which already has it's fast reload - I guess it's the same principle as Live server (is it ?) and still my app is not reloading - do you have a trick for me @vsnthdev ? 😬

**Comment by vsnthdev** [comment]
@arnaudambro Unless manually disabled, `create-react-app` uses a technology called HMR (Hot module reloading) where only that particular component/function/element is resent through a websocket...

With the Live server VSCode extension, a JavaScript full-page refresh is triggered. Have your tried visiting http://localhost:5500 in your browser to check if reloading is working there?

**Comment by arnaudambro** [comment]
actually it works good now ! I tried a few times before sending this message, not working, but today everything works like a charm... thanks !

**Comment by azwc** [comment]
I am working on vscode, and live server is running, but the window can't move by drag. btw, the titlebar has "data-tauri-drag-region", it works well while 'devPath: "../dist"'.

**Comment by azwc** [comment]
I am working on vscode, and live server is running, but the window can't move by drag. btw, the titlebar has "data-tauri-drag-region", it works well while 'devPath: "../dist"'.

**Comment by sl0burn** [comment]
Just wanted to add, I am using sveltekit for my web framework. It uses Vite to package up the JS and Vite also has HMR which seems to work as long as you point tauri.conf.json at the right devPath as was mentioned for live server.

**Comment by ItsCubeTime** [comment]
I also think there should be an out-of-the-box solution that doesn't require additional setup from the user - at least for vanilla html documents.

Perhaps the VS Code extension can provide some interoperability?

**Comment by fny** [comment]
This is an incredibly painful workflow. I'm trying to use vanilla js with the new import maps feature, and the build times are incredibly slow since I have to touch build.rs every time.
