### ISSUE TITLE
Allow replacement of banner artwork in Windows installer dialog

### ISSUE THREAD

**Issue by scrmea** [tauri-apps/tauri#2175]
The windows installer shows a distorted graphic, consisting of an overstretched icon.ico:

<img width="498" alt="screenshottauriinstaller" src="https://user-images.githubusercontent.com/50693365/124716285-e05ba180-df3e-11eb-8d05-7c4f5a4d38a7.png">

It would be much nicer if one could add a bmp of corresponding size to the src-tauri/icons folder. 
The required dimensions are 493px × 58px. 

A separate banner variable must link to the corresponding file here:
https://github.com/tauri-apps/tauri/blob/3e6f34160deab4f774d90aba28122e5b6b6f9db2/tooling/bundler/src/bundle/windows/templates/main.wxs#L35

**Comment by nothingismagick** [comment]
@lucasfernog - are we tracking this for the next release?

**Comment by lucasfernog** [comment]
> @lucasfernog - are we tracking this for the next release?

Yeah I'll do it this morning.
