### ISSUE TITLE
Taskbar hides on maximize when decorations set to false

### ISSUE THREAD

**Issue by akzhy** [tauri-apps/tauri#2180]
### **Describe the bug**

I am trying to customize the title bar and followed this tutorial https://tauri.studio/en/docs/guides/window-customization/. And I disabled the default title bar by setting `decorations:false` in `tauri.conf.json`, however once the default title was removed, the maximize button also hid the taskbar. So the app appears to be in full screen situation. The issue does not appear if I set the decorations to true.

### **To Reproduce**
1. Add a custom title bar as shown in the link above
2. Set decorations to false in `tauri.conf.json`
3. Click the maximize button

### **Expected behavior**

The app goes into maximized state

### **Platform and Versions (required):**

```
Operating System - Windows, version 10.0.19042 X64
Webview2 - 91.0.864.64

Node.js environment
  Node.js - 14.17.3
  @tauri-apps/cli - 1.0.0-beta.5
  @tauri-apps/api - Not installed

Global packages
  npm - 6.14.2
  yarn - 1.22.10

Rust environment
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/.git
/node_modules
/src-tauri
/ui

App
  tauri.rs - 1.0.0-beta.4
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self' 
  distDir - ../ui/public
  devPath - http://localhost:3000
```

### **Additional context**

`@tauri-apps/api` installed inside `ui` `"@tauri-apps/api": "^1.0.0-beta.4",`

**Comment by amrbashir** [comment]
The bug is resolved recently in https://github.com/tauri-apps/tao , it should be available in the next release.
