### ISSUE TITLE
Ubuntu installation from web docs, needs sudo?

### ISSUE THREAD

**Issue by 0o-de-lally** [tauri-apps/tauri#2182]
Can't quite express my excitement to start playing with Tauri. Getting stuck with silent errors on `yarn tauri info`.

### **Describe the bug**
Using Ubuntu 20.4, I'm following the instructions with a user that has sudo.

I do a fair amount of rust development, so `rustup` and `cargo` are already there.

Using the website's instructions (which are excellent BTW): https://tauri.studio/en/docs/development/integration
I'm not able to get  `yarn tauri init` nor `yarn tauri info` to work, unless I use `sudo`.

Evidently this may be my local configuration, but I don't see anything out of the ordinary.

See below my installation steps and results. I do successfully get at `src-tauri` at the end of it. But not without first adding the web source.

### **Expected behvior**

`yarn tauri info` should display something or an error. Instead it seems to fail silently.
 
### **To Reproduce**

```
> apt get [..]

0 upgraded, 0 newly installed, 0 to remove and 132 not upgraded.

> node -v
v16.4.2

> rustc --version
rustc 1.52.1 (9bc8c42bb 2021-05-09)

> yarn init
success Saved package.json
Done in 3.39s.


> yarn tauri init

yarn run v1.22.10
$ /root/tauri/node_modules/.bin/tauri init
Done in 0.22s.



> yarn tauri info
yarn run v1.22.10
$ /root/tauri/node_modules/.bin/tauri info
Done in 0.26s.


> sudo yarn tauri info
yarn run v1.22.10

$ /root/tauri/node_modules/.bin/tauri info
 app:spawn Running "/root/tauri/node_modules/@tauri-apps/cli/bin/tauri-cli tauri info" +0ms


Operating System - Ubuntu, version 20.04 X64

Node.js environment
  Node.js - 10.19.0 (outdated, latest: 12.13.0)
  @tauri-apps/cli - 1.0.0-beta.5
  @tauri-apps/api - Not installed

Global packages
  npm - 7.9.0
  yarn - 1.22.10

Rust environment
  rustc - Not installed
  cargo - Not installed

App directory structure
/node_modules
/.git
/src-tauri

App
  tauri.rs - 1.0.0-beta.4 (no lockfile)
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - web
  devPath - localhost:1234

Done in 10.49s.
```

Then it proceeds to try to install rustup again.

```
1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
>3

info: aborting installation
 app:spawn [sync] Running "cargo generate-lockfile" +1m


 app:spawn ⚠️  Command "cargo" failed with exit code: null +0ms
 app:spawn ⚠️  Please globally install "cargo" +1ms
error Command failed with exit code 1.
```

**Comment by nothingismagick** [comment]
Try this:

```
% cargo install tauri-cli --version ^1.0.0-beta
% cargo tauri info
```

**Comment by nothingismagick** [comment]
You should never have to run sudo for yarn / npm / node. That died out years ago. I guess what you need to install is a proper version of `nvm` - node version manager. But thats only if you need node, which you don't necessarily need.

**Comment by 0o-de-lally** [comment]
yes that works nicely, thanks. And then I'm guessing `cargo tauri dev` is next.

IMO the web documentation should reflect this to be the default way of using the tauri tools, instead of yarn. Thanks again!

**Comment by FabianLars** [comment]
i think the docs are fine in that regard. It looks like a misconfiguration on your end tbh. But I have to admit that not getting any error either from tauri or yarn is kinda weird.

**Comment by 0o-de-lally** [comment]
Ok, I'm running through the directions on OSX now (different machine) and I'm getting the same issue with `yarn tauri info` providing no output. Am I missing something?

**Comment by FabianLars** [comment]
Welp, no idea about macos. But it works fine for me on linux & windows. Are you on the [tauri discord server](https://discord.gg/SpmNs4S)? Would make it easier to debug, afterwards we could post the results here.

Did you try it with npm to see if it throws an actual error?
Also, why does your log shows the /root/ path even on non sudo commands?
