### ISSUE TITLE
macOS resize event does not update dimensions of resized window

### ISSUE THREAD

**Issue by scrmea** [tauri-apps/tauri#2187]
On macOS, tauri reports the initial screen dimensions to a resizable window while adjusting its dimensions. Every event fired while dragging contains the dimensions that the window had when launching the app, instead of the current window dimensions.

### **To Reproduce**
`listen("tauri://resize", ({ event: _, payload }) => console.log(payload))`

### **Expected behavior**
console logs an object with current window dimensions.

### **Platform and Versions (required):**
```
Operating System - Mac OS, version 11.4.0 X64
Operating System - Mac OS, version 10.15 X64

Node.js environment
  Node.js - 16.2.0
  @tauri-apps/cli - 1.0.0-beta.5
  @tauri-apps/api - 1.0.0-beta.4

Global packages
  npm - 7.19.1
  yarn - 1.22.10

Rust environment
  rustc - 1.55.0-nightly
  cargo - 1.54.0-nightly
```

**Comment by smolck** [comment]
Also experiencing this on macOS. ~~Using `document.body.getBoundingClientRect()` seems to be okay as a workaround (even if it isn't perfect?).~~ EDIT: Actually, that doesn't seem to really work? Not sure.

**Comment by scrmea** [comment]
AFAIK it only gives you the dimensions of the (inner) browser window. It does not account for any frame/menubar etc.. Since those vary by OS version, you'd always be off. In my case, I just want to store window size and position in order to recall it when re-opening the Tauri app. document.body.getBoundingClientRect() would result in the window shrinking each time I open the app. Not a good workaround ;-).

**Comment by smolck** [comment]
Oh whoops, I was conflating two issues; `inner_size()` on `window` doesn't update _either_, and I was thinking of `document.body.getBoundingClientRect()` as a workaround for that. You're right that it definitely wouldn't solve the issue with `outer_size()` not updating 😅

**Comment by amrbashir** [comment]
Can you guys clone https://github.com/tauri-apps/tao and: 
1. Run `cargo run --example window`
2. Start resizing the window
3. look for resize events in the terminal output and see if it changes or not ?

**Comment by smolck** [comment]
@amrbashir Followed your directions after applying this diff to get the resize output (and not spam stdout with the other events so I could see the resize events):
```diff
diff --git a/examples/window.rs b/examples/window.rs
index 572380b6..92c87e91 100644
--- a/examples/window.rs
+++ b/examples/window.rs
@@ -21,8 +21,15 @@ fn main() {
 
   event_loop.run(move |event, _, control_flow| {
     *control_flow = ControlFlow::Wait;
-    println!("{:?}", event);
+    // println!("{:?}", event);
 
+    if let Event::WindowEvent {
+      event: WindowEvent::Resized(size),
+      ..
+    } = event
+    {
+      println!("new size: {:?}", size);
+    }
     match event {
       Event::WindowEvent {
         event: WindowEvent::CloseRequested,
```

And yes, the width and height values do change.

**Comment by amrbashir** [comment]
Thanks, this confirms it is an issue in Tauri and not Tao.

**Comment by lucasfernog** [comment]
@lemarier seems like it's an issue with tao when wry is used, the `inner_size` always returns the same value but `outer_size` shows the correct values. Can you help?

**Comment by wusyong** [comment]
`inner_size` method on webview is pushed. Tauri can use it to reflect the correct webview size.
