### ISSUE TITLE
input tag's cursor does not blinks when the data-tauri-drag-region attribute is set

### ISSUE THREAD

**Issue by SOVLOOKUP** [tauri-apps/tauri#2189]
### **Describe the bug**
When the data-tauri-drag-region attribute is set, the input tag's cursor does not blinks.

### **To Reproduce**

```
<input
	data-tauri-drag-region
	class="searchInput"
	type="text"
	placeholder={placeHolder}
	bind:value={inputValue}
/>
```

https://github.com/SOVLOOKUP/starries-tauri/blob/master/src/routes/_component/searchBar.svelte#L15

### **Expected behavior**
text cursor blink blink blink...

### **Screenshots**
![image](https://user-images.githubusercontent.com/53158137/125081730-e85f4100-e0f8-11eb-8224-1dd0cd2481b6.png)

### **Platform and Versions (required):**

```
❯ tauri info

Operating System - Manjaro, version 21.0.7 X64

Node.js environment
  Node.js - 15.14.0
  @tauri-apps/cli - 1.0.0-beta.5

Global packages
  npm - 7.7.6
  yarn - 1.22.10

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0
```

**Comment by nothingismagick** [comment]
Please try putting the `data-tauri-drag-region` in the `<div>` surrounding the `<input>`.

**Comment by SOVLOOKUP** [comment]
> Please try putting the `data-tauri-drag-region` in the `<div>` surrounding the `<input>`.

I have tried, but the "input" event will replace the "drag" event, causing the drag action to fail in the input area. That's why here is another `data-tauri-drag-region`.

**Comment by nothingismagick** [comment]
Yeah, this seems to me like you need to rethink your interaction model. I mean, if I click in the "omnibar" in Chrome, it focusses and won't let me drag. This is why normal UI allows for other logical drag regions. Looking at your screenshot I would assume I could then click and drag on the circular avatar icon you have. I am closing this issue as won't fix.

Although we all really love the:

<img width="208" alt="image" src="https://user-images.githubusercontent.com/35242872/125088200-8210f900-e0cd-11eb-9ff0-40a61adae9b4.png">
