### ISSUE TITLE
Unhandled Promise Rejection: ReferenceError: Can't find variable: __TAURI_INVOKE_KEY__

### ISSUE THREAD

**Issue by SOVLOOKUP** [tauri-apps/tauri#2193]
### **Describe the bug**
when using `window.appWindow` api, error: `Can't find variable: __TAURI_INVOKE_KEY__`

### **To Reproduce**
https://github.com/SOVLOOKUP/starries-tauri/blob/master/src/lib/component/magnet/index.svelte#L49

### **Expected behavior**
resizable can be properly set

### **Screenshots**
I![image](https://user-images.githubusercontent.com/53158137/125198025-c26da400-e292-11eb-94ab-0a8f22a21660.png)

### **Platform and Versions (required):**

```
Operating System - Manjaro, version 21.0.7 X64

Node.js environment
  Node.js - 15.14.0


  @tauri-apps/cli - 1.0.0-beta.5
  @tauri-apps/api - 1.0.0-beta.4

Global packages
  npm - 7.7.6
  yarn - 1.22.10

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/.github
/.husky
/static
/.git
/.svelte-kit
/src
/build
/src-tauri
/node_modules

App
  tauri.rs - 1.0.0-beta.1
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - ../build
  framework - Svelte
```

### **Stack Trace**

![image](https://user-images.githubusercontent.com/53158137/125198070-ea5d0780-e292-11eb-8fd6-b2f6bee3734b.png)

**Comment by amrbashir** [comment]
Your tauri version is outdated, it should be `1.0.0-beta.4`, change it in `src-tauri/Cargo.toml`
