### ISSUE TITLE
"custom.protocol.taurilocalhost’s server IP address could not be found" on first startup

### ISSUE THREAD

**Issue by stefnotch** [tauri-apps/tauri#2201]
### **Describe the bug**

Sometimes, when starting a Tauri application for the first time on Windows 10, one will be faced with a `custom.protocol.taurilocalhost’s server IP address could not be found` error. When closing and quickly restarting the application, the error usually goes away.

Screenshot of the error
![image](https://user-images.githubusercontent.com/10220080/125290598-c8aa6180-e320-11eb-8c17-a025516fccc7.png)

Reloading the webview does not help.
![image](https://user-images.githubusercontent.com/10220080/125291342-91888000-e321-11eb-936d-d39c6542e477.png)

### **To Reproduce**
1. Clone https://github.com/stefnotch/downline/
2. Run `npm run build:debug` to build a debugging application
3. Start `src-tauri\target\debug\downline.exe`
5. Otherwise, close the application and start it again until you see the error

### **Expected behavior**
I expected to see the `index.html` file.

### **Platform and Versions (required):**
`npm run tauri info`
```
> downline@3.0.0 tauri
> tauri "info"

 app:spawn Running "C:\Users\Stefnotch\Documents\GitHub\Tools\downline\node_modules\@tauri-apps\cli\bin\tauri-cli.exe tauri info" +0ms


Operating System - Windows, version 10.0.19043 X64
Webview2 - 91.0.864.67

Node.js environment
  Node.js - 16.4.2
  @tauri-apps/cli - 1.0.0-beta.5
  @tauri-apps/api - 1.0.0-beta.4

Global packages
  npm - 7.11.2
  yarn - Not installed

Rust environment      
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/.git
/.github
/dist
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.4
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:8080/
  framework - Vue.js
```

### **Additional context**

A copy of the application can be found here https://github.com/stefnotch/downline/releases/tag/v3.0.0-alpha

**Comment by FabianLars** [comment]
That should be fixed (unreleased). See https://github.com/tauri-apps/tauri/issues/2124#issuecomment-872392287
