### ISSUE TITLE
Comms Broken in beta.4

### ISSUE THREAD

**Issue by DBTaylor** [tauri-apps/tauri#2204]
Using tauri 1.0.0-beta.4 (or beta.3), commands that I attempt to send from the frontend are not making it to the backend, and events triggered in the backend are not being emitted in the frontend. I've had to revert to beta.1 to get everything to work (couldn't seem to get beta.2 to build).

The issue doesn't occur when I run ```tauri dev```, only in the release build.

window.emit is returning Ok() and no exception is being thrown by invoke.
```
Operating System - Windows, version 10.0.17763 X64
Webview2 - 91.0.864.67

Node.js environment
  Node.js - 14.8.0
  @tauri-apps/cli - 1.0.0-beta.5
  @tauri-apps/api - 1.0.0-beta.4

Global packages
  npm - 6.14.7
  yarn - Not installed

Rust environment
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/.git
/.vscode
/node_modules
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.4
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ./dist
  devPath - http://localhost:8081/
  framework - React
  bundler - Webpack
```

**Comment by amrbashir** [comment]
We released a new version yesterday, update your deps and re-open if the issue still exists
