### ISSUE TITLE
Cannot bind to Windows Key in globalShortcuts

### ISSUE THREAD

**Issue by jquesada2016** [tauri-apps/tauri#2218]
### **Describe the bug**
First of all, amazing project. Really is! Has made desktop development super fun and easy with Rust. Second of all, I am sorry if this is actually not a bug, I tried searching for the docs to the shortcut key names, but could not for the life of me find it.

I am not able to register to a shortcut that contains the `windows key`.

### **To Reproduce**
1. Start a new project and add a basic JS file.
2. Add the following to the file:
```javascript
import { globalShortcut } from "@tauri-apps/api";

globalShortcut.register("Control+Windows+J", () => {
    alert("Hello?");
  });
```
4. Run `npx tauri dev`, and try running the shortcut, with and without the `windows key`.

### **Expected behavior**
I expect the handler to be invoked when I press `Ctr+Win+J`, however, it does not. It is invoked, however, when I press just `Ctrl+J`, even though there's an extra key there, I do not think this should happen.

I also believe it would be a verry good idea to let the user know if the shortcut they provided includes a key which does not exist, as most probable in my case. Perhaps as a promise rejection.

### **What I've tried**
I have also tried:
```
"CmdOrControl+Windows+J";
"Control+Win+J";
"Control+Super+J";
```
All of which work when I just press `Ctrl+J`...

Any help or pointers to the docs would be much appreciated!

### **Tauri Info**
```
Operating System - Windows, version 10.0.21390 X64
Webview2 - 91.0.864.67

Node.js environment
  Node.js - 15.12.0
  @tauri-apps/cli - 1.0.0-beta.5
  @tauri-apps/api - 1.0.0-beta.4

Global packages
  npm - 7.6.3
  yarn - Not installed

Rust environment
  rustc - 1.55.0-nightly
  cargo - 1.55.0-nightly

App directory structure
/.git
/build
/node_modules
/public
/src
/src-tauri
/types

App
  tauri.rs - 1.0.0-beta.4
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:8080
  framework - Svelte
```

**Comment by amrbashir** [comment]
As I answered in discrod, you should use `Super`. 
This will be documented better.

**Comment by jquesada2016** [comment]
I am not 100% sure if the issue should be closed, or perhaps consider creating a new issue for the second half of this one?

The other half of the issue being `Control+Windows+<some key>` still works, and registers fine, even though it only works with `Control+<some key>`, without the `Windows`. Not sure if this behavior extends to other keys, as well.

**Comment by amrbashir** [comment]
Open a new issue at https://github.com/tauri-apps/tao and we will fix this. I think we should throw an error if there is a wrong key there.
