### ISSUE TITLE
Updater refactor w/ async?

### ISSUE THREAD

**Issue by lemarier** [tauri-apps/tauri#2223]
**Is your feature request related to a problem? Please describe.**

With the latest changes to our Linux implementations, it gets harder to spawn a thread, especially for dialogs.

In https://github.com/tauri-apps/tauri/pull/2222 we fixed with the `glib::MainContext` 

The big drawback with that is it runs on the main GtkThread, which means it locks the app run.

Having slow updater endpoints will cause the app to be slower to open (on Linux)

**Describe the solution you'd like**
I'm not sure?

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by lucasfernog** [comment]
@lemarier shouldn't the glib::MainContext be used only to render the dialog? that would keep the API call on a separate task.

**Comment by lucasfernog** [comment]
I'll see if I can move the context usage to the dialog API itself.
