### ISSUE TITLE
feat(@tauri-apps/api): `path` module similar to nodejs

### ISSUE THREAD

**Issue by KaKi87** [tauri-apps/tauri#2228]
**Is your feature request related to a problem? Please describe.**
Windows & Unix-based operating systems doesn't use the same syntax for file paths.

**Describe the solution you'd like**
A [`path.join`](https://nodejs.org/api/path.html#path_path_join_paths) method for Tauri like there is for Node that returns correct paths no matter what OS is running.

**Describe alternatives you've considered**
None

**Additional context**
None

---
Thanks

**Comment by amrbashir** [comment]
This comment will keep track of methods that needs to be added, people are welcome to suggest more methods and I will add them to the list.

- [ ] `path.join()`
- [ ] `path.relative()`
- [ ] `path.sep`

**Comment by amrbashir** [comment]
This comment will keep track of methods that needs to be added, people are welcome to suggest more methods and I will add them to the list.

- [ ] `path.join()`
- [ ] `path.resolve()`
- [ ] `path.relative()`
- [ ] `path.sep`

**Comment by amrbashir** [comment]
closed in favor of #2233
