### ISSUE TITLE
feat(@tauri-apps/api): `os` module similar to nodejs

### ISSUE THREAD

**Issue by KaKi87** [tauri-apps/tauri#2229]
**Is your feature request related to a problem? Please describe.**
It is sometimes required for an app to behave differently depending on which operating system it is running.

**Describe the solution you'd like**
A [`process.platform`](https://nodejs.org/api/process.html#process_process_platform) property for Tauri like there is for Node that returns current operating system.

**Describe alternatives you've considered**
None

**Additional context**
None

---
Thanks

**Comment by lemarier** [comment]
A wrapper around `std::env::consts::OS` could do the trick (suggestion from Short@Discord)

**Comment by amrbashir** [comment]
This comment will keep track of methods that needs to be added, people are welcome to suggest more methods and I will add them to the list.

- [ ] `os.platform()`
- [ ] `os.version()`

**Comment by amrbashir** [comment]
closed in favor of #2233
