### ISSUE TITLE
Unable to uninstall when using Skip UAC Task

### ISSUE THREAD

**Issue by euphbriggs** [tauri-apps/tauri#2230]
### **Describe the bug**

When the new `enableElevatedUpdateTask` is set to `true` the user is unable to uninstall the application because the uninstaller isn't able to successfully remove the Windows Task that is used to skip the UAC prompt.

### **To Reproduce**
1. In the tauri.conf.json file, set the "tauri" -> "windows" -> "wix" -> "enableElevatedUpdateTask" to `true`
2. Run `npm run tauri build` to generate an installer
3. Install the application
4. Try to uninstall the application - It will fail

### **Expected behavior**
The uninstall process is successful and the Windows Task for updating the application has been removed.

### **Platform and Versions (required):**
```
Operating System - Windows, version 10.0.19043 X64
Webview2 - 91.0.864.67

Node.js environment
  Node.js - 14.17.3
  @tauri-apps/cli - 1.0.0-beta.6
  @tauri-apps/api - 1.0.0-beta.5

Global packages
  npm - 7.16.0
  yarn - 1.22.10

Rust environment
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/.git
/.svelte-kit
/.vscode
/build
/node_modules
/src
/src-sems
/src-tauri
/static
/target

App
  tauri.rs - 1.0.0-beta.5
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:3000
  framework - Svelte
```

### **Additional context**
I created this issue.

**Comment by euphbriggs** [comment]
@lemarier When I wrote the original PR, I tested uninstalling, but evidently, somewhere along the way, I broke it.

This PR includes the resolution: https://github.com/tauri-apps/tauri/pull/2231

I apologize for the inconvenience.

**Comment by lemarier** [comment]
Thanks, @euphbriggs we do appreciate your contribution!
And thanks for catching it up!
