### ISSUE TITLE
set default file name in save dialog

### ISSUE THREAD

**Issue by bdjnk** [tauri-apps/tauri#2232]
### **Is your feature request related to a problem? Please describe.**
When I attempt to save some data using `dialog.save` I am missing the ability to set a default file name. This is feature is present in other applications.

### **Describe the solution you'd like**
The ability to set a default file name, presumably as part of the `dialog.savedialogoptions`.

### **Describe alternatives you've considered**
Using an `a` tag with the `download` attribute set and the `href` attribute pointing to a `blob:` URL. However this doesn't work currently, as detailed [here](https://github.com/tauri-apps/wry/issues/349).

### **Additional context**
As an example, in Chrome, when attempting to "Save link as..." the dialog.ts:61 link, I get the following.

![2021-07-16-123031_1144x598_scrot](https://user-images.githubusercontent.com/620722/126018462-cb3df56e-893c-4159-8fb0-a5e4ed6f6923.png)

I first posted this as a discussion question (#2226) but it seems to be actually a feature request.

**Comment by lucasfernog** [comment]
This feature requires a change on the great RFD library: https://github.com/PolyMeilex/rfd/issues/18
