### ISSUE TITLE
[docs] Documentation has no mention of @tauri-apps/api

### ISSUE THREAD

**Issue by sophon-aniketos** [tauri-apps/tauri#2235]
I was trying out Tauri on Windows following these intructions: https://tauri.studio/en/docs/get-started/setup-windows  and https://tauri.studio/en/docs/development/integration , but neither of these pages mention anything about needing to install @tauri-apps/api . Also create-tauri-app didn't ask me about installing @tauri-apps/api either. The issue only came to light after I ask about it on Discord on how to use the JS API.

**Comment by amrbashir** [comment]
after #2251 is merged and new version is released, `create-tauri-app` will prompt your to install the api.
