### ISSUE TITLE
CLI does not download with `HTTPS_PROXY`.

### ISSUE THREAD

**Issue by chippers** [tauri-apps/tauri#2237]
### **Describe the bug**
When `HTTPS_PROXY` is set, `tauri init` does not successfully use the value. This can make the download of the Rust CLI fail, and therefore the entire `tauri init` fails.

### **To Reproduce**
1. Have a `HTTPS_PROXY`
2. Download the Rust CLI through `tauri init`
3. Notice that the Rust CLI fails to download through `tauri init` when needing to use `HTTPS_PROXY`
4. `tauri init` hangs :(

### **Expected behavior**
The CLI sucessfully downloads and installs like typical usages of `tauri init`.

### **Screenshots**
![image](https://user-images.githubusercontent.com/3301043/126039586-3330b392-a189-4d4b-9ea7-65ed9e3ed19f.png)

### **Platform and Versions (required):**

```
Operating System - Windows, version 10.0.22000 X64
Webview2 - 91.0.864.70

Node.js environment
  Node.js - 14.17.3
  @tauri-apps/cli - 1.0.0-beta.6
  @tauri-apps/api - Not installed

Global packages
  npm - 7.19.1
  yarn - 1.22.10

Rust environment
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.5
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - src
  devPath - src
package.json not found
```

### **Additional context**
This is a common problem in countries where a proxy is needed to access common resources. The screenshot and info comes from a chinese user that found this issue.

It seems that we do not pass the proxy information to dep `got`. https://github.com/tauri-apps/tauri/blob/e48bb3edff145018a88217432e21e4a7846fdf0e/tooling/cli.js/src/helpers/download-binary.ts#L42

The user says:
> Got may need to be like the following:
got('https://sindresorhus.com',{agent:{https:tunnel.httpsOverHttp({proxy:{host:'localhost'}}))}))

**Comment by Tim-Paik** [comment]
I am the Chinese user mentioned above, and I think the following link may be helpful:https://github.com/sindresorhus/got/blob/main/documentation/tips.md#proxying
I think it is better to use global-agent

**Comment by rkedward** [comment]
I'm seeing what I believe is the same issue working behind a corporate firewall.  npm is able to download the packages successfully but the Rust CLI script fails to download.  

```bash
> tauri "init"

Downloading Rust CLI...
(node:2211) UnhandledPromiseRejectionWarning: RequestError: connect ETIMEDOUT 192.30.255.112:443
    at ClientRequest.<anonymous> (/.../node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:326:22)
    at ClientRequest.origin.emit (/.../node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (_http_client.js:427:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
(node:2211) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2211) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
