### ISSUE TITLE
feature-flag: menu & system tray

### ISSUE THREAD

**Issue by lemarier** [tauri-apps/tauri#2248]
**Is your feature request related to a problem? Please describe.**

Since we can have a `system_tray` without a menu. 
I think it would be better to have 3 different feature flags. 
1. `menu` for all menu creation whether it is with a `menu_bar` or a `system_tray`
2. `menu_bar` for the menu_bar itself and would include the `menu` feature flag
3. `system_tray` for the tray itself

So if users just want a `system_tray` without a menu, they won't have to bundle the extra code for menu

_Originally posted by @amrbashir in https://github.com/tauri-apps/tauri/issues/2240#issuecomment-882653512_

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by wusyong** [comment]
We have an alternative PR for system tray on tao.
And I'm going to remove the dependency of libappindicator on lunix.
So perhaps we won't need these feature flag in the future.
