### ISSUE TITLE
TypeScript compilation errors when using @tauri-apps/api@1.0.0-beta.5

### ISSUE THREAD

**Issue by Dragoteryx** [tauri-apps/tauri#2249]
### **Describe the bug**
Currently working on an app using Tauri and Angular, I noticed that I get TypeScript compilation errors when using the latest version of Tauri. This doesn't happen when using `@tauri-apps/api@1.0.0-beta.4`.

### **To Reproduce**
Create a new Angular project, then use `tauri init`.
Once that's done, use `@tauri-apps/api` in your project, then try compiling it.
I've only tested this issue using Angular, but someone on Discord said they encountered the same issue using Vue and TypeScript, so this doesn't seem to be Angular related.

### **Expected behavior**
No compilation errors.

### **Screenshots**
![image](https://user-images.githubusercontent.com/33252782/126195145-66b1ba5d-2c3b-4537-9ec0-ead8e3f620b4.png)

### **Platform and Versions (required):**

```
Operating System - Windows, version 10.0.19042 X64
Webview2 - 91.0.864.70

Node.js environment
  Node.js - 16.5.0
  @tauri-apps/cli - 1.0.0-beta.6
  @tauri-apps/api - 1.0.0-beta.5

Global packages
  npm - 7.19.1
  yarn - Not installed

Rust environment      
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/.git
/dist
/node_modules
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.5
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:4200
  framework - Angular
  bundler - Webpack
```

**Comment by scarmuega** [comment]
I'm experiencing the exact same behaviour. Would you kindly elaborate on how to fix or why the issue was closed? Thanks!

**Comment by amrbashir** [comment]
@scarmuega this issue has been fixed in the dev branch, and will be available in the next release.

**Comment by 8** [comment]
While waiting for the next release, I fixed it locally for me by moving the two lines with `// @ts-expect-error` one line down, so that the end result looks like:

```ts
/**
 * Get an instance of `WebviewWindow` for the current webview window.
 *
 * @return The current WebviewWindow.
 */
function getCurrent(): WebviewWindow {
  return new WebviewWindow(window.__TAURI__.__currentWindow.label, {
    // @ts-expect-error
    skip: true
  })
}

/**
 * Gets an instance of `WebviewWindow` for all available webview windows.
 *
 * @return The list of WebviewWindow.
 */
function getAll(): WebviewWindow[] {
  return window.__TAURI__.__windows.map(
    // @ts-expect-error
    (w) => new WebviewWindow(w, { skip: true })
  )
}
```

Take care,
Martin
