### ISSUE TITLE
[docs] Cloudbridge pattern

### ISSUE THREAD

**Issue by stefnotch** [tauri-apps/tauri#2254]
Since Webview2 doesn't ship with Windows 10 by default, I decided to let the user use whichever browser they want to use.

This means that I would use the [Cloudbridge pattern](https://tauri.studio/en/docs/guides/patterns/cloudbridge), start the default browser and navigate to `localhost:...`.

This works until I try to access an API like
```js
import { app } from "@tauri-apps/api";
app.getVersion().then((version) => console.log(version));
```

If I do so, a `Uncaught (in promise) TypeError: window.rpc is undefined` shows up. Is there a way around this?

**Comment by FabianLars** [comment]
That's not what the Cloudbridge pattern is about or tauri as a whole for that matter.  
You can't use tauri without a webview == in a browser (at least as long as tauri can't be compiled to wasm), as it isn't a frontend framework or something...  
What you want is something like a classic PWA i guess? And that would be more or less a normal website and not a whole program like tauri apps.

**Comment by stefnotch** [comment]
I see, reading through the documentation, I was under the impression that that should work. 

> It uses a localhost server, which means that your app will technically be available to other processes, like browsers and potentially other devices on the network
> -- https://tauri.studio/en/docs/guides/patterns/cloudish

So, using a Tauri application as a localhost web server and then showing the UI in a browser. I do need access to native functions for https://github.com/stefnotch/downline/ though.

**Comment by FabianLars** [comment]
Ohh, that part is still from the alpha version where tauri had a builtin server.
The beta version uses a "custom protocol" instead and the server got removed.

**Comment by stefnotch** [comment]
Oh, I was a bit surprised at the fact that that was pretty much the only place in the documentation which referenced that. I guess it makes sense.

So, since this is something that Tauri doesn't support by design, I can close this issue? 
(Too bad, I had hoped that I could use that as a very low effort alternative to shipping Webview2 with my application)

**Comment by nothingismagick** [comment]
yes - its something that has been on my backlog for far too long. really need to totally revamp that entire section...
