### ISSUE TITLE
Global events hooks not working

### ISSUE THREAD

**Issue by ya55en** [tauri-apps/tauri#2270]
### **Describe the bug**
A global event emitted on the front-end side via `emit()` [[1]] does not seem to get propagated to the back-end but is instead propagated to a front-end listener setup via `listen()` [[2]].

### **To Reproduce**

NOTE: The sample code shown below is available in [this repository] created to showcase the issue.)

1. Create a new tauri project (vanilla HTML/CSS/JS front-end)
2. Provide global event hooks on the front-end side following the [Events guide], like:

```javascript
var sendEvent = null;
import('/modules/@tauri-apps/api/event.js').then((eventMod) => {
  const onUserClick = eventMod.listen('user-click', (event) => {
    // event.event is the event name (useful if you want to use a single callback fn for multiple event types)
    // event.payload is the payload object
    console.log('onUserClick() called');
    console.log(event.event);
    console.log(event.payload);
  });

  sendEvent = () => {
    console.log('sendEvent() called');
    eventMod.emit('user-click', '{"message": "Tauri looks good! (coming from front-end)"}');
  };
});
```

3. Provide event hooks on the back-end side following the [Events guide], like:

```rust
use tauri::Manager;

#[derive(Clone, serde::Serialize)]
struct Payload {
   message: String,
}

fn main() {
   println!("** Tauri app about to start");
   tauri::Builder::default()
      .setup(|app| {
         // listen to the `event-name` (emitted on any window)
         let id = app.listen_global("user-click", |event| {
            println!("got event with payload {:?}", event.payload());
         });
         // unlisten to the event using the `id` returned on the `listen_global` function
         // an `once_global` API is also exposed on the `App` struct
         app.unlisten(id);

         // emit the `event-name` event to all webview windows on the frontend
         app.emit_all(
            "user-click",
            Payload {
               message: "Tauri is awesome! (coming from back-end)".into(),
            },
         )
         .unwrap();
         Ok(())
      })
      .run(tauri::generate_context!())
      .expect("error while running tauri application");
}
```

4. Run the application and open the webview JS console to monitor the execution.
5. Trigger the front-end `sendEvent()` function call and observe the console output and the back-end stdout.
6. The JS console output looks like

```
sendEvent() called
onUserClick() called
user-click
{"message": "Tauri looks good! (coming from front-end)"}
```
and there is nothing of the relevant rust `println!()` calls, which speaks for the event being received directly by the front-end listener without being propagated to the back-end.

### **Expected behavior**
The event should propagate to the rust back-end and trigger

```rust
println!("got event with payload {:?}", event.payload());
```

which should show up on the back-end stdout.

Then the back-end `app.emit_all()` call should send an event back to the front-end, which should be received by `listen()` [[1]] and the JS console should show

```
onUserClick() called
user-click
{"message": "Tauri is awesome! (coming from back-end)"}
```

### **Platform and Versions (required):**

```
Operating System - Linux Mint, version 20.2 X64

Node.js environment
  Node.js - 14.17.3
  @tauri-apps/cli - 1.0.0-beta.6
  @tauri-apps/api - 1.0.0-beta.5

Global packages
  npm - 7.19.1
  yarn - 1.22.10

Rust environment
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/www
/node_modules
/.git
/src-tauri

App
  tauri.rs - 1.0.0-beta.5
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../www
  devPath - http://localhost:8000
```

### **Additional context**
Hit this in an attempt to setup a minimal Tauri application with event-based communication via global events, following the [Events guide].

[1]: https://tauri.studio/en/docs/api/js/modules/event/#emit
[2]: https://tauri.studio/en/docs/api/js/modules/event/#listen
[Events guide]: https://tauri.studio/en/docs/usage/guides/events
[this repository]: https://github.com/yassen-damyanov/tauri-events-minimal/

**Comment by shanshouchen** [comment]
I have the same problem and look forward to solving it
