### ISSUE TITLE
Compatability with OpenUI5 JS framework

### ISSUE THREAD

**Issue by blekman995** [tauri-apps/tauri#2273]
SAP openUI5 has awesome controls and a solid frontend framework , will compensate tauri nicely. is it possible to initialise tauri via npm in an openUI5 project? in the present release will the Rust bindings work on initialisation?

openUI5 framework link: https://openui5.org/

**Comment by amrbashir** [comment]
As long as your front-end compiles to html/css/js, it will work

**Comment by Laegel** [comment]
Hey @subralog !
**Any** web framework can be used with Tauri. 
To add Tauri to an existing project, follow this guide: https://tauri.studio/en/docs/development/integration

**Comment by blekman995** [comment]
Thanks so much folks!
