### ISSUE TITLE
Net API

### ISSUE THREAD

**Issue by Verequies** [tauri-apps/tauri#2274]
It would be great if Tauri had the Node.JS [Net](https://nodejs.org/api/net.html) API or similar such as the Electron.JS [Net](https://www.electronjs.org/docs/api/net) API.

For example I am trying to create a Discord Rich Presence using discord-rpc but am unable to do so easily as the function 'net.createConnection' does not exist.

**Comment by amrbashir** [comment]
Recently, I had the idea to make our api similar to nodejs and introduce new functions from Nodejs standard library, you can suggest which methods you want in #2233
