### ISSUE TITLE
Flex elements not behaving as expected, to fill page or overflow scroll

### ISSUE THREAD

**Issue by OJFord** [tauri-apps/tauri#2275]
### **Describe the bug**
Flex elements do not behave as expected, or as seen in the browser. In particular, [this example](https://www.codeply.com/go/ouc3hddx5i) is intended to show a fixed 'frame' consisting of header, footer, and sidebar; with two independently scrollable columns. In Tauri, the footer floats up to meet column content height if less than viewport, and the full page scrolls rather than just whichever one of the columns if the content overflows.

### **To Reproduce**

1. 
<details>
<summary>code</summary>

```html
<div class="container-fluid h-100 d-flex flex-column">
    <div class="row flex-shrink-0">
        <div class="col-12 border">Navbar </div>
    </div>
    <div class="row flex-fill" style="min-height:0">
        <div class="col-2 border mh-100" style="overflow-y: scroll;">Sidebar </div>
        <div class="col-4 border mh-100" style="overflow-y: scroll;">
            Article list
            <p>Sriracha biodiesel taxidermy organic post-ironic, Intelligentsia salvia mustache 90's code editing brunch. Butcher polaroid VHS art party, hashtag Brooklyn deep v PBR narwhal sustainable mixtape swag wolf squid tote bag. Tote bag cronut semiotics,
                raw denim deep v taxidermy messenger bag. Tofu YOLO Etsy, direct trade ethical Odd Future jean shorts paleo. Forage Shoreditch tousled aesthetic irony, street art organic Bushwick artisan cliche semiotics ugh synth chillwave meditation.
                Shabby chic lomo plaid vinyl chambray Vice. Vice sustainable cardigan, Williamsburg master cleanse hella DIY 90's blog.</p>

            <p>Ethical Kickstarter PBR asymmetrical lo-fi. Dreamcatcher street art Carles, stumptown gluten-free Kickstarter artisan Wes Anderson wolf pug. Godard sustainable you probably haven't heard of them, vegan farm-to-table Williamsburg slow-carb
                readymade disrupt deep v. Meggings seitan Wes Anderson semiotics, cliche American Apparel whatever. Helvetica cray plaid, vegan brunch Banksy leggings +1 direct trade. Wayfarers codeply PBR selfies. Banh mi McSweeney's Shoreditch selfies,
                forage fingerstache food truck occupy YOLO Pitchfork fixie iPhone fanny pack art party Portland.</p>

        </div>
        <div class="col-6 border mh-100" style="overflow-y: scroll;">Article content 
        
                    <p>Sriracha biodiesel taxidermy organic post-ironic, Intelligentsia salvia mustache 90's code editing brunch. Butcher polaroid VHS art party, hashtag Brooklyn deep v PBR narwhal sustainable mixtape swag wolf squid tote bag. Tote bag cronut semiotics,
                raw denim deep v taxidermy messenger bag. Tofu YOLO Etsy, direct trade ethical Odd Future jean shorts paleo. Forage Shoreditch tousled aesthetic irony, street art organic Bushwick artisan cliche semiotics ugh synth chillwave meditation.
                Shabby chic lomo plaid vinyl chambray Vice. Vice sustainable cardigan, Williamsburg master cleanse hella DIY 90's blog.</p>

            <p>Ethical Kickstarter PBR asymmetrical lo-fi. Dreamcatcher street art Carles, stumptown gluten-free Kickstarter artisan Wes Anderson wolf pug. Godard sustainable you probably haven't heard of them, vegan farm-to-table Williamsburg slow-carb
                readymade disrupt deep v. Meggings seitan Wes Anderson semiotics, cliche American Apparel whatever. Helvetica cray plaid, vegan brunch Banksy leggings +1 direct trade. Wayfarers codeply PBR selfies. Banh mi McSweeney's Shoreditch selfies,
                forage fingerstache food truck occupy YOLO Pitchfork fixie iPhone fanny pack art party Portland.</p>
            <p>Sriracha biodiesel taxidermy organic post-ironic, Intelligentsia salvia mustache 90's code editing brunch. Butcher polaroid VHS art party, hashtag Brooklyn deep v PBR narwhal sustainable mixtape swag wolf squid tote bag. Tote bag cronut semiotics,
                raw denim deep v taxidermy messenger bag. Tofu YOLO Etsy, direct trade ethical Odd Future jean shorts paleo. Forage Shoreditch tousled aesthetic irony, street art organic Bushwick artisan cliche semiotics ugh synth chillwave meditation.
                Shabby chic lomo plaid vinyl chambray Vice. Vice sustainable cardigan, Williamsburg master cleanse hella DIY 90's blog.</p>

            <p>Ethical Kickstarter PBR asymmetrical lo-fi. Dreamcatcher street art Carles, stumptown gluten-free Kickstarter artisan Wes Anderson wolf pug. Godard sustainable you probably haven't heard of them, vegan farm-to-table Williamsburg slow-carb
                readymade disrupt deep v. Meggings seitan Wes Anderson semiotics, cliche American Apparel whatever. Helvetica cray plaid, vegan brunch Banksy leggings +1 direct trade. Wayfarers codeply PBR selfies. Banh mi McSweeney's Shoreditch selfies,
                forage fingerstache food truck occupy YOLO Pitchfork fixie iPhone fanny pack art party Portland.</p>

        </div>
    </div>
    <div class="row flex-shrink-0">
        <div class="col-12 border">Footer </div>
    </div>
</div>
```

```css
html,body {
    height: 100%;
}
```
</details>

2. Bootstrap 5 CSS
3. Test with sufficient window height that the content doesn't overflow, and smaller so that it does. (I find the 'inspect' console a convenient way to change that.)

I can look at getting a minimal reproduction in a repo if necessary.

### **Expected behavior**
As shown in this demo:
https://www.codeply.com/go/ouc3hddx5i

Overflow scroll:
![image](https://user-images.githubusercontent.com/3946014/126568371-859f5df4-7cab-4b8e-8481-34de44b55b90.png)

No overflow 'frame' (Bootstrap's flex-fill in the content row)
![image](https://user-images.githubusercontent.com/3946014/126568422-37b45432-13f7-49ce-b8fc-750c23a64808.png)

### **Screenshots**

(of actual behaviour)

Overflow scrolled up (footer overflown):
![image](https://user-images.githubusercontent.com/3946014/126568533-338488ac-d1be-4492-8db8-3636495cb2d7.png)

Overflow scrolled down (header off page, sidebar scrolled together with both columns:
![image](https://user-images.githubusercontent.com/3946014/126568568-06bf4327-a7bb-4056-8e31-12501dd7c2f4.png)

No overflow, 'frame' collapses:
![image](https://user-images.githubusercontent.com/3946014/126568491-22471b0b-7e76-4139-97bd-b7d028f1d138.png)

https://user-images.githubusercontent.com/3946014/126569514-330ebd5f-4523-43f4-b04b-f4b1b1f478fc.mp4

### **Platform and Versions (required):**

```
Operating System - Arch Linux, version Unknown [ed: it's 5.12.15] X64

Node.js environment
  Node.js - 16.5.0
  @tauri-apps/cli - 1.0.0-beta.5
  @tauri-apps/api - 1.0.0-beta.4

Global packages
  npm - 7.17.0
  yarn - 1.22.10

Rust environment
  rustc - 1.51.0
  cargo - 1.51.0

App directory structure
/node_modules
/src-tauri
/components
/dist
```

### **Additional context**
https://discord.com/channels/616186924390023171/625037620996734986/867509094951419945

### **Stack Trace**
N/A

**Comment by OJFord** [comment]
Same behaviour on macOS (Darwin 20.5.0) - thought worth a test as @amrbashir mentioned in Discord a different webkit renderer is used there.

**Comment by amrbashir** [comment]
alright, can you provide a minimal repo ?

**Comment by OJFord** [comment]
How's that ^? `yarn && yarn dev` to run.

**Comment by amrbashir** [comment]
@OJFord 
I built your repo and served with [http-server](https://www.npmjs.com/package/http-server) in a chromium-based browser (vivaldi) and the footer is not fixed, same as tauri. 

Vivaldi: 
![vivaldi-chromium-based](https://user-images.githubusercontent.com/48618675/126625448-f12742b4-619a-4111-9202-310bd82b1ec3.png)

Looks to me that this is how it supposed to work, so I will close the issue. 

if you can make another minimal repo with only css (no bootstrap or any css framework) that works perfectly in a browser, I will take another look.

**Comment by OJFord** [comment]
Ah, I missed the `html, body { height: 100%; }`.

...but with that Tauri has the fixed footer too; works as expected. 🤦🏻 There isn't much more to the app I pulled it from (I'm using Svelte, but did try this plain HTML in the root component) but it's clearly my fault on my end somehow. Sorry about that.
