### ISSUE TITLE
Add Svelte to create-tauri-app

### ISSUE THREAD

**Issue by krscott** [tauri-apps/tauri#2276]
**Is your feature request related to a problem? Please describe.**
There is no [Svelte](https://svelte.dev/) option in create-tauri-app.

**Describe the solution you'd like**
Add a Svelte recipe to create-tauri-app to install the [official template](https://github.com/sveltejs/template).

**Describe alternatives you've considered**
Although it is relatively straight-forward to get Tauri and Svelte working together manually, it is tedious.

**Additional context**
N/A

**Comment by krscott** [comment]
I'm willing to work on a PR for this if greenlit.

**Comment by amrbashir** [comment]
> I'm willing to work on a PR for this if greenlit.

That would be awesome
