### ISSUE TITLE
[binary-releases] macos aarch64 (m1) support

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri#2286]
### **Describe the bug**
The bundler fails to include a sidecar on apple silicon machines. It is expecting to find a binary named: `${name}-x86_64-apple-darwin` even though the correct thing to do is to look for a binary with the name `${name}-aarch64-apple-darwin`.

### **Platform and Versions (required):**

```
Operating System - Mac OS, version 11.3.1 X64

Node.js environment
  Node.js - 16.5.0
  @tauri-apps/cli - 1.0.0-beta.6
  @tauri-apps/api - 1.0.0-beta.5

Global packages
  npm - 7.19.1
  yarn - 1.22.10

Rust environment
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/dist
/node_modules
/.github
/src-tauri
/.git
/src

App
  tauri.rs - 1.0.0-beta.4
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:3000
  framework - React
```

### **Workaround**

you can specify the target explicitly by running `yarn tauri build --target aarch64-apple-darwin`.

**Comment by lemarier** [comment]
Nice catch! Thanks
As we are there we should do a full round of checkups for `aarch64 ` support.
The updater should add `aarch64 ` as a supported platform as well.

**Comment by JonasKruckenberg** [comment]
I just noticed ^^the target triple is `aarch64-apple-darwin` not `arch64-apple-darwin`. Something that my autocorrection doesn't like

**Comment by lemarier** [comment]
@JonasKruckenberg could you make `rustup default` and paste me the result please

Thanks

**Comment by JonasKruckenberg** [comment]
Sorry for the delay,  here you go!
`rustup default` gives me:
```
stable-aarch64-apple-darwin (default)
```

**Comment by lemarier** [comment]
@JonasKruckenberg could you try without `node cli` ?

```bash
cargo install tauri-cli --version 1.0.0-beta.5
```

then `cargo tauri build` should do the trick in the `src-tauri`

Let me know if it works

**Comment by JonasKruckenberg** [comment]
It works! 🥳👍🏻

**Comment by lemarier** [comment]
@nklayman looks like this is coming from the [binary releases](https://github.com/tauri-apps/binary-releases) as the built-in `target_arch` is wrong

Maybe we could build a CI version with `--target aarch64-apple-darwin`?

Thanks

**Comment by nklayman** [comment]
I don't think we can cross compile, so we'd have to wait for https://github.com/actions/virtual-environments/issues/2187. We could work around this by checking the arch at runtime instead of build time.
