### ISSUE TITLE
tauri-runtime-wry still used win32 feature flag

### ISSUE THREAD

**Issue by domiSchenk** [tauri-apps/tauri#2296]
Wry did remove support for winrt: https://github.com/tauri-apps/wry/commit/c37973e47318e9cff2712eb4a394c07734f58d54
and there fore the flagh win32 was removed.

tauri-runtime-wry still uses this flag:
https://github.com/tauri-apps/tauri/blob/70a1941468f55f0dc09ac2e13802945891d766f4/core/tauri-runtime-wry/Cargo.toml#L15

**Comment by lemarier** [comment]
Hi there,

It'll be fixed on the next `wry` release.  Hopefully in the next day(s)...
Actually, the tauri `dev` branch is locked to wry `0.11` and still has the `win32` flag.

Thanks for pointing it up!

**Comment by domiSchenk** [comment]
i do use a wry patch on my end (fixing the flicker https://github.com/tauri-apps/wry/commit/e28bcce0884937365013fda3098f64f9956d569f)
but changed to dev branch because the PR was completed.

But i change to rev patch instead!
