### ISSUE TITLE
System tray events does not trigger when there is no window

### ISSUE THREAD

**Issue by lemarier** [tauri-apps/tauri#2298]
### **Describe the bug**
When all Windows are closed, the system tray menu events is not triggered.

### **To Reproduce**
`cargo run --bin api`

1. Click `New window` in tray menu (window is opening)
2. Close all windows.
3. Click again on `New window` in tray menu (window is NOT opening)

### **Expected behavior**
On `3` the Window should open. I've tried to make a simple tray application and I got the same behavior.

### **Screenshots**
N/A

### **Platform and Versions (required):**

```
Operating System - Mac OS, version 12.0.0 X64

Node.js environment
  Node.js - 14.17.3
  @tauri-apps/cli - 1.0.0-beta.6

Global packages
  npm - 6.14.13
  yarn - 1.22.10

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0
```

**Comment by wusyong** [comment]
This also happens on linux. So users will need to click the tray twice to exit.

**Comment by lucasfernog** [comment]
How are you guys testing this? With the new `ExitRequested` API? because closing all windows just exits the app.

**Comment by lemarier** [comment]
@lucasfernog run the `api` example

- close the window, say `yes` the window is closed, but the tray is still there,
- Click on the tray and click any menu of the tray. 

None of the events are triggered.

**Comment by lemarier** [comment]
Ok looks like its coming from there;
The event is sent but dropped here. Not sure why, but when there is no window, the `ControlFlow` is set to exit.

https://github.com/tauri-apps/tauri/blob/102895fa0c47a11b45f06bc79c3addbf3cd84f31/core/tauri-runtime-wry/src/lib.rs#L1776-L1780

**Comment by lucasfernog** [comment]
that's the default behavior but we added an API to prevent that (ExitRequested event). On macOS the app is still opened even with ControlFlow::Exit (tao behavior), so that's why the tray icon is still there.

**Comment by lemarier** [comment]
Perfect thanks!
