### ISSUE TITLE
Multi window freeze

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tauri#2311]
### **Describe the bug**
Creating a new window like this makes the app unresponsive on macOS:
```rust
#[command]
pub fn new_window(app_handle: AppHandle) -> Result<(), String> {
  println!("new w");
  app_handle
    .create_window("main2".to_string(), WindowUrl::default(), |win, webview| {
      let win = win
        .title("Main 2")
        .resizable(true)
        .transparent(false)
        .decorations(true)
        .always_on_top(false)
        .inner_size(800.0, 600.0)
        .min_inner_size(300.0, 150.0)
        .fullscreen(false);
      println!("- struct created");
      return (win, webview);
    })
    .expect("Error creating window");
  println!("- done");
  Ok(())
}
```

### **To Reproduce**
Repo: https://github.com/probablykasper/tauri-multiwindow-freeze-bug

### **Platform and Versions (required):**

```
Operating System - Mac OS, version 10.15.7 X64

Node.js environment
  Node.js - 14.16.0
  @tauri-apps/cli - 1.0.0-beta.6
  @tauri-apps/api - 1.0.0-beta.5

Global packages
  npm - 6.14.11
  yarn - 1.22.10

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/node_modules
/src-tauri
/build
/.git
/src

App
  tauri.rs - 1.0.0-beta.5
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:4000
  framework - Svelte
```

**Comment by amrbashir** [comment]
I can reproduce this issue on windows with your repo but can't reproduce it with our multiwindow example.

**Comment by probablykasper** [comment]
@amrbashir I think the multiwindow example only creates windows from `tauri.conf.json` and/or `tauri::Builder`

**Comment by amrbashir** [comment]
~~No, it creates from commands too.~~
Edit: it creates it from the js side.

**Comment by probablykasper** [comment]
@amrbashir Ah, so then it calls this internal command: https://github.com/tauri-apps/tauri/blob/fd8fab507c8fa1b113b841af14c6693eb3955f6b/core/tauri/src/endpoints/window.rs#L115-L128

**Comment by amrbashir** [comment]
> @amrbashir Ah, so then it calls this internal command:

yeah but we still need to figure out why it doesn't work from commands, doesn't matter which attributes you set too

```rs
#[command]
pub fn new_window(app_handle: AppHandle) -> Result<(), String> {
  println!("new w");
  app_handle
    .create_window("main2".to_string(), WindowUrl::default(), |win, webview| (win, webview))
    .expect("Error creating window");
  println!("- done");
  Ok(())
}
```

**Comment by lucasfernog** [comment]
It doesn't work because the command is not async, which means it is ran on the main thread and it's preventing the event loop from receiving the message.

Changing the `#[command] pub fn` to `#[command] pub async fn` will make it work.
