### ISSUE TITLE
Dev tools crashes using WSL2 + VcXsrv

### ISSUE THREAD

**Issue by pbondoer** [tauri-apps/tauri#2313]
### **Describe the bug**
Opening the dev tools under WSL2 + VcXsrv crashes the process.

### **To Reproduce**
* Create a new Tauri project
* Run `tauri dev`
* Right click -> Developer Tools

### **Expected behavior**
The dev tools should show up and not crash.

### **Screenshots**
<img src="https://user-images.githubusercontent.com/1671753/127378666-f5818c7b-c7a6-41b0-8bb8-9323f5709612.png" width="300">

### **Platform and Versions (required):**
```
Operating System - Ubuntu, version 20.04 X64

Node.js environment
  Node.js - 16.5.0
  @tauri-apps/cli - 1.0.0-beta.6
  @tauri-apps/api - 1.0.0-beta.5

Global packages
  npm - 7.19.1
  yarn - 1.22.11

Rust environment
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/node_modules
/src
/dist
/src-tauri
/.parcel-cache

App
  tauri.rs - 1.0.0-beta.5
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../src
  devPath - http://localhost:1234
```

### **Additional context**
Using WSL2 and the latest version of VcXsrc (1.20.9.0)

### **Stack Trace**
This is the output I get, let me know if there's any additional info I can provide.
```
(WebKitWebProcess:17007): Gdk-ERROR **: 20:35:54.395: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadFBConfig'.
  (Details: serial 180 error_code 163 request_code 149 (GLX) minor_code 21)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by amrbashir** [comment]
Running GUIs on WSL is not officially supported by Microsoft (not yet) so it is expected that some gui apps won't run properly.

With that noted and since devtools work properly in a real linux environmeny, I am afraid it is beyond our control.

**Comment by pbondoer** [comment]
That kinda sucks. The [docs have instructions for WSL](https://tauri.studio/en/docs/getting-started/setup-linux#4-for-windows-subsystem-for-linux-wsl-users), so I thought it was supported, but if it isn't then fair enough. Though I would suggest adding a mention somewhere that it's likely not gonna work for actual dev. I'll have to switch to dev on native Windows for now I suppose, and maybe in the future with `wslg` we'll have more luck 😄

**Comment by amrbashir** [comment]
well, we do support building on WSL but this crash is far beyond our control, It might be a bug in `VcXsrv` or something else, I don't know. With GUI on WSL there is a lot of different emulation layers and we don't control any of them so I hope `wslg` will fix this.

**Comment by JYInMyHeart** [comment]
> That kinda sucks. The [docs have instructions for WSL](https://tauri.studio/en/docs/getting-started/setup-linux#4-for-windows-subsystem-for-linux-wsl-users), so I thought it was supported, but if it isn't then fair enough. Though I would suggest adding a mention somewhere that it's likely not gonna work for actual dev. I'll have to switch to dev on native Windows for now I suppose, and maybe in the future with `wslg` we'll have more luck 😄

wslg can't display any dom elements.

**Comment by FabianLars** [comment]
@JYInMyHeart Can you explain what you mean? We didn't receive any complains about Windows11+wslg so far; and i did test it myself too a few weeks ago.

Edit: Just to be clear, this still doesn't mean the we actually "support" it.

**Comment by JYInMyHeart** [comment]
> @JYInMyHeart Can you explain what you mean? We didn't receive any complains about Windows11+wslg so far; and i did test it myself too a few weeks ago.
> 
> Edit: Just to be clear, this still doesn't mean the we actually "support" it.

After I run `yarn serve:tauri` in terminal. It gived me this result.
![image](https://user-images.githubusercontent.com/26308552/176200158-0cdb7407-0ade-4bd2-a2dc-95d9fe4e32a7.png)
There is no menu when I click right mouse button.
This is my opengl info.
![image](https://user-images.githubusercontent.com/26308552/176200646-3f8f7743-2832-44d0-8db6-15ef44f8bbf8.png)
It's okay when I run this project on m1 mac. I don't know how to debug this.
