### ISSUE TITLE
Failed to download webview2

### ISSUE THREAD

**Issue by jzyzxx** [tauri-apps/tauri#2325]
### **Describe the bug**
```
error: failed to download `webview2 v0.1.1`

Caused by:
  unable to get packages from source

Caused by:
  failed to download replaced source registry `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to parse manifest at `C:\Users\DELL\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\webview2-0.1.1\Cargo.toml`

Caused by:
  feature `resolver` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["resolver"]` to enable this feature
```

1. vue create my-tauri-app
2. cd my-tauri-app
3. vue add tauri
4. npm run tauri:serve

Operating System
win10
Node.js environment
v14.15.4
Global packages
npm 
6.14.10

Rust environment
rustc 
rustc 1.49.0 (e1884a8e3 2020-12-29)
cargo 
cargo 1.49.0 (d00d64df9 2020-12-05)

**Comment by FabianLars** [comment]
Try upgrading your rust toolchain (`rustup update`). The resolver stuff got added in 1.51 (latest version is 1.54, you're at 1.49)
