### ISSUE TITLE
Allow href without .html extension for links between app's pages

### ISSUE THREAD

**Issue by gereleth** [tauri-apps/tauri#2328]
**Is your feature request related to a problem? Please describe.**

I want to have several pages in my app with links between them.
Suppose my distDir contains two files: `index.html` and `about.html`.
My index page has a link to the About page:
`<a href="about"> About </a>`
On the web this link opens the `about.html` file. 
But in Tauri this link doesn't work unless I put `href="about.html"` there.

**Describe the solution you'd like**
The link should work even if I don't add the `.html` part.

**Describe alternatives you've considered**
_

**Additional context**
_

**Comment by amrbashir** [comment]
as discussed on [discord](https://discord.com/channels/616186924390023171/625037620996734986/871057572399046677) 
given this directory structure , if you want `about.html` then you need to explicitly set your `<a>` tag to link to `about.html`
ex: `<a href="about.html">About</a>`
```
|_ index.html
|_ about.html
``` 
if you want  `<a href="about">About</a>` to work then your folder structure should be like this
```
|_ index.html
|_ about
	|_ index.html
```

**Comment by gereleth** [comment]
Thanks. I realised after looking into this that I had a setting called [`clean_urls`](https://vercel.com/docs/configuration#project/clean-urls) enabled in a Vercel-hosted app which made my links work that way.
What you described about folder structure makes total sense. :+1:
