### ISSUE TITLE
[docs] examples in CLI guide are outdated 

### ISSUE THREAD

**Issue by MikeTheSnowman** [tauri-apps/tauri#2332]
Hello. I'm new to Tauri and Rust, so apologies if this is the wrong place to post this.

The documentation on at this [page](https://tauri.studio/en/docs/usage/guides/cli#rust) for the rust code for creating a custom CLI using Tauri does not appear to work. 

I tried to place this code in my main.rs file to test, but I keep getting errors that "tauri::cli::get_matches" does not exist.

```
use tauri::cli::get_matches;

fn main() {
  match get_matches() {
    Some(matches) => {
      println!(matches)
    }
  }
...
}
```

Also in my cargo.toml file, I've got the cli feature enabled:
`tauri = { version = "1.0.0-beta.5", features = ["api-all", "cli"] }`

If the documentation is correct, but I'm doing something wrong, can I please ask for some guidance? Thanks!

**Comment by FabianLars** [comment]
Looks like there is a re-export missing (or it's intentional and the docs are outdated lol).
In the meantime you can access it via `tauri::api::cli` instead of `tauri::cli`.

**Comment by MikeTheSnowman** [comment]
> Looks like there is a re-export missing (or it's intentional and the docs are outdated lol).
> In the meantime you can access it via `tauri::api::cli` instead of `tauri::cli`.

Hello @FabianLars thanks for the advice. I've tried giving that a shot, but still run in to issues (mostly due to my lack of knowledge of Rust).
![image](https://user-images.githubusercontent.com/5297545/127793566-e670b39f-36ef-438a-bfe8-d0e8a327efbd.png)
![image](https://user-images.githubusercontent.com/5297545/127793579-5325abeb-3bad-4ebf-bc40-b46450242042.png)
![image](https://user-images.githubusercontent.com/5297545/127795926-2e31e14c-5469-4711-af77-7f4aba0c3ca7.png)


Any advice or maybe an example code snippet of how to use `tauri::api::cli::get_matches()`? Sorry, I'm just a bit lost.

**Comment by amrbashir** [comment]
try this 

```rs
fn main() {
  let context = tauri::generate_context!();
  let cli_config = context.config().tauri.cli.clone().unwrap();
  match get_matches(&cli_config) {
    Ok(matches) => {}
    Err(_) => {}
  };
  
  tauri::Builder::default()
  	.run(context);
}
```

**Comment by MikeTheSnowman** [comment]
> try this
> 
> ```rust
> fn main() {
>   let context = tauri::generate_context!();
>   let cli_config = context.config().tauri.cli.clone().unwrap();
>   match get_matches(&cli_config) {
>     Ok(matches) => {}
>     Err(_) => {}
>   };
>   
>   tauri::Builder::default()
>   	.run(context);
> }
> ```

@amrbashir , Thank you very much. This works perfectly!
![image](https://user-images.githubusercontent.com/5297545/127858769-62a011a8-7279-4d1e-81fa-4aef6489abbe.png)

**Comment by amrbashir** [comment]
Good to know, Idk why I closed this, the docs still are not up to date.

**Comment by MikeTheSnowman** [comment]
> Good to know, Idk why I closed this, the docs still are not up to date.

Just as a heads up, I created a [PR](https://github.com/tauri-apps/tauri/pull/2337) with the example code that you provided to update that specific portion of the docs. Thanks again!
