### ISSUE TITLE
[docs] cargo-tauri does not explain to use `cargo tauri`

### ISSUE THREAD

**Issue by canadaduane** [tauri-apps/tauri#2335]
I installed `tauri-cli` via cargo:

```
cargo install tauri-cli --version 1.0.0-beta.5
```

The last line of the install reads as follows:
```
Installed package `tauri-cli v1.0.0-beta.5` (executable `cargo-tauri`)
```

Naturally, I tried this new executable, but was left scratching my head:
```
$ cargo-tauri --help
cargo-tauri 1.0.0-beta.5
Lucas Nogueira <lucas@tauri.studio>
The Tauri command line interface.

USAGE:
    cargo <SUBCOMMAND>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

SUBCOMMANDS:
    help     Prints this message or the help of the given subcommand(s)
    tauri    Tauri CLI
```

I didn't think `tauri` was the subcommand I was looking for, because I wanted to `init` a new project. lol.

Anyway, I think the `cargo-tauri` command should self-document that its intended usage is through `cargo tauri`:

```
$ cargo tauri help
cargo-tauri 1.0.0-beta.5
Tauri CLI

USAGE:
    cargo tauri [SUBCOMMAND]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

SUBCOMMANDS:
    build    Tauri build.
    dev      Tauri dev.
    help     Prints this message or the help of the given subcommand(s)
    info     Shows information about Tauri dependencies
    init     Initializes a Tauri project
    sign     Tauri updates signer.
```

Much better! :)

**Comment by nothingismagick** [comment]
Great idea, not sure how we missed that!

**Comment by lucasfernog** [comment]
When you use `cargo install`, you're installing a cargo subcommand, see [this](https://github.com/rust-lang/cargo/wiki/Third-party-cargo-subcommands) and [this](https://doc.rust-lang.org/book/ch14-05-extending-cargo.html). So it doesn't make much sense to run it directly like you did (`$ cargo-tauri --help`). I'll add this to the help output.

**Comment by lucasfernog** [comment]
Take a look at #2370. I don't love it, but it's better than what we have right now.

**Comment by wusyong** [comment]
cli.rs uses clap right? I believe it's able to doc those subcommands with method it has.
Let me explore a bit and see how to fix this
