### ISSUE TITLE
Cursor flickers its state

### ISSUE THREAD

**Issue by thaumictom** [tauri-apps/tauri#2349]
### **Describe the bug**
If [decorations](https://tauri.studio/en/docs/api/config/#tauri.windows.decorations) is set to false, the cursor is flickering when hovering over text or elements that have a non-default CSS cursor property set. This behavior only happens in frameless mode and I could only reporduce this on Windows.

### **To Reproduce**
1. Create a new Tauri app using `create-tauri-app`
2. Set [decorations](https://tauri.studio/en/docs/api/config/#tauri.windows.decorations) to false in `tauri.conf.json`
3. Run the app with `npm run tauri dev`
4. Hover over text
5. See the cursor having weird behavior

### **Expected behavior**
The text cursor should be applied permanently when hovering over text

### **Screenshots**
https://user-images.githubusercontent.com/15818698/128110525-86c6224c-da0c-4de0-b17b-5544ea053a3c.mp4

### **Platform and Versions (required):**

```
Operating System - Windows, version 10.0.19042 X64
Webview2 - 92.0.902.62

Node.js environment
  Node.js - 14.17.3
  @tauri-apps/cli - 1.0.0-beta.6
  @tauri-apps/api - 1.0.0-beta.5

Global packages
  npm - 6.14.13
  yarn - 1.22.11

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/.git
/build
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.5
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:3000
  framework - React
```

### **Additional context**
I am using the React template of `create-tauri-app`, however I believe that it applies to any template.

**Comment by amrbashir** [comment]
> Set decorations to true in tauri.conf.json

I think you meant `decorations: false`
This is has been fixed in tauri-apps/wry#350 and will be available in the next release.

**Comment by thaumictom** [comment]
Yes, I indeed meant false. Thank you that you have already made a PR and fixed the issue. I unfortunately couldn't find it before making this.

**Comment by amrbashir** [comment]
No worries, the bug was reported on discord and I fixed it without making an issue about it so it was kinda hidden.
