### ISSUE TITLE
Ability to disable minimize/maximize/close

### ISSUE THREAD

**Issue by DBTaylor** [tauri-apps/tauri#2353]
It would be nice to have the ability to disable windows' minimize, maximize/restore, and close buttons. They can be removed entirely with ```decorations: false```, but the close functionality remains when right clicking the app in the taskbar.

I'm on Windows, I don't know what behaviors other platforms have.

**Comment by amrbashir** [comment]
related to tauri-apps/tao#116

**Comment by shenghan97** [comment]
Also on macOS, it would be nice if we can disable full screen button (green traffic light button)!

**Comment by ChurchTao** [comment]
> related to [tauri-apps/tao#116](https://github.com/tauri-apps/tao/issues/116)

This code is in tao, but how I use it in ```tauri::window::WindowBuilder``` like ```minimizable```.
I could not find ```pub fn minimizable(mut self, minimizable: bool) -> Self``` in ```tauri>src>window.rs```

**Comment by FabianLars** [comment]
It needs to be explicitly exposed first, similar to this PR for example https://github.com/tauri-apps/tauri/pull/5317
