### ISSUE TITLE
window.start_resizing(direction)

### ISSUE THREAD

**Issue by DBTaylor** [tauri-apps/tauri#2354]
It would be nice to have Window methods like start_dragging, but for resizing the window. This would be useful for frameless apps. I imagine you would pass as an argument what side of the window you're resizing from (top, topright, right, bottomright, bottom, bottomleft, left, or topleft).

**Comment by amrbashir** [comment]
Frameless windows support resizing by default and we already use similar methods internally to do so, so it is possible to expose this method for windows and linux.
@lemarier can confirm if it is possible or not on macos.

**Comment by lemarier** [comment]
In macos we do have https://developer.apple.com/documentation/appkit/nswindowdelegate/1419292-windowwillresize?language=objc

But it doesnt tell us the resizing from. Probably some hacking could be done, but dont seems to have any native function available.

**Comment by amrbashir** [comment]
> In macos we do have https://developer.apple.com/documentation/appkit/nswindowdelegate/1419292-windowwillresize?language=objc
> 
> But it doesnt tell us the resizing from. Probably some hacking could be done, but dont seems to have any native function available.

Seems like this is some sort of an event and we don't want that, we want to start the resizing itself not to listen to the resizing event.

**Comment by lemarier** [comment]
Sorry misunderstood!

I need to make more research for this.

Edit we can do it with;
https://developer.apple.com/documentation/appkit/nswindow/1419519-setframe

**Comment by amrbashir** [comment]
> Edit we can do it with;
> https://developer.apple.com/documentation/appkit/nswindow/1419519-setframe
> 
>  

This is not quite what we want too, we want something similar to https://developer.apple.com/documentation/appkit/nswindow/1419386-performwindowdragwithevent but for resizing.

Looks like macOS doesn't support this, should we just close this issue @lemarier ?

**Comment by amrbashir** [comment]
closing this as macOS doesn't seem to support something like that.
