### ISSUE TITLE
the js api should probably be compiled for a target higher than ES3

### ISSUE THREAD

**Issue by feeddageek** [tauri-apps/tauri#2360]
**Is your feature request related to a problem? Please describe.**
Despite my app targeting a recent ES version, I noticed that my bundle was full of shim and that a copyright notice from Microsoft was attached to it because of said shim.
The shims and copyright notices came from importing @tauri-apps/api because `tooling/api/tsconfig.json` do not have a `target` set and the default value is `"ES3"`

**Describe the solution you'd like**
Since this js will be run inside WRY, it seems safe to assume that ES6 is supported and `"target" : "ES6"` should be added to `tooling/api/tsconfig.json`

**Comment by nothingismagick** [comment]
You are absolutely right! Nice catch. We technically support (to the best of my knowledge) all the way up to ecma2018.

**Comment by harshkhandeparkar** [comment]
Isn't babel responsible for this?

**Comment by harshkhandeparkar** [comment]
I tried this locally and changing the target does not affect the bundle size whereas removing babel does (although I don't know what consequences that would have).

**Comment by nothingismagick** [comment]
babel transpiles EVERYTHING. so removing babel would just leave your ECMASCRIPT as is.

**Comment by nothingismagick** [comment]
however, the question here is about our API, not userland, so maybe @harshkhandeparkar we are having a misunderstanding. Did you do this in the API folder of this repo?

**Comment by nothingismagick** [comment]
Because if so, you just found a GREAT win for final bundle size and probably saved the planet terabytes (if not more) of annual traffic once Tauri becomes mainstream.

**Comment by harshkhandeparkar** [comment]
> however, the question here is about our API, not userland, so maybe @harshkhandeparkar we are having a misunderstanding. Did you do this in the API folder of this repo?

Yes, the API folder and I compared the `api/dist` and `core/[something i forgot]/bundle.js` next to `core.js`

**Comment by feeddageek** [comment]
@harshkhandeparkar  I did not consider the `bundle.js` next to `core.js` because it is only use when withGlobalTauri is set to true (which is don't use).
It is build from the same sources as the API, but it does not read the `tsconfig.json` file.
I don't know why it is build that way, so I can't make an informed recommendation on how to reduce the size of this file.
_(but adding `targets: "> 0.25%, not dead, not ie 11"` to `getBabelOutputPlugin`options reduce the `bundle.js` size considerably)_

Back to the API, building it after adding the target in tsconfig.json give me a `dist` folder that is 20k smaller and then reduce the side of my app's bundle by almost 5k (and remove Microsoft's copyright notice).

(On a side note, I don't believe this change will cause a measurable reduction in traffic, we are talking about text files that are heavily compressed in transit ; the 20k difference in the size of `dist` becomes a 1k one after compression.
However the difference in size of the uncompressed front-end code bundle can impact performance and start time of applications especially on low-end/old machine).

**Comment by harshkhandeparkar** [comment]
> _(but adding `targets: "> 0.25%, not dead, not ie 11"` to `getBabelOutputPlugin`options reduce the `bundle.js` size considerably)_

Yes, definitely. 
 
> Back to the API, building it after adding the target in tsconfig.json give me a `dist` folder that is 20k smaller and then reduce the side of my app's bundle by almost 5k (and remove Microsoft's copyright notice).

I had tried this but it kind of gave me a difference initially when it reduced but I tried again and it didn't really make a difference, perhaps this needs to be measured again.

**Comment by lucasfernog** [comment]
Unfortunately we had to revert the change because Webpack and CRA didn't like it. We're still interested in this change, but we'd need an approach that works on all targets.
