### ISSUE TITLE
Inclusive Branch Names

### ISSUE THREAD

**Issue by harshkhandeparkar** [tauri-apps/tauri#2363]
I opened this issue as requested by Denjell on Discord.

I was just looking through the `tauri-apps` org repos and found that the following repos still use `master` branch:
1. (org repos) `rustdocusaurus`, `tauri-dialog-rs` (archived), `governance-and-guidance`, `rfcs`, `.github`.
2. (forks) `winit`, `create-pull-request`, `web-view` (archived), `zserge-webview` (archived), `tauri-inliner` (archived), `gh-tangle-release`, `deno`.

Perhaps you would like to consider renaming these to something like `main` or `dev` :)

**Comment by nothingismagick** [comment]
Thanks, we are not going to modify archived repos - because they are archived. WIll find some time to do the others that you mentioned. Thanks again!

**Comment by lucasfernog** [comment]
I just went through it. Thanks for the request!

**Comment by lucasfernog** [comment]
I just left some gtk repos untouched to not mess with forks.
