### ISSUE TITLE
CSP: request a server api was failed

### ISSUE THREAD

**Issue by fundon** [tauri-apps/tauri#2366]
I have a backend server, the HTTP address is `http://localhost`.

### **Platform and Versions (required):**
```
λ yarn tauri info
yarn run v1.22.10
$ cargo-tauri tauri info

Operating System - Mac OS, version 11.4.0 X64

Node.js environment
  Node.js - 15.14.0
  @tauri-apps/cli - 1.0.0-beta.6
  @tauri-apps/api - 1.0.0-beta.5

Global packages
  npm - 7.15.0
  yarn - 1.22.10

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/.husky
/mock
/node_modules
/public
/src-tauri
/build
/.git
/src

App
  tauri.rs - 1.0.0-beta.5
  build-type - bundle
  CSP - default-src 'unsafe-inline' 'self' http://localhost
  distDir - ../build
  devPath - http://localhost
  framework - Vue.js (Vue CLI)
  bundler - Webpack
✨  Done in 15.39s.
```

### **Additional context**
<img width="729" alt="Screen Shot 2021-08-09 at 01 05 33" src="https://user-images.githubusercontent.com/27926/128639745-7e7132e4-0e17-42f1-a0ff-ac853f7fdfcc.png">

**Comment by lucasfernog** [comment]
Try setting the `exceptionDomain` configuration to `localhost`: https://tauri.studio/en/docs/api/config#tauri.bundle.macOS.exceptionDomain

Please reopen if it still doesn't work.

**Comment by fundon** [comment]
Still failed.

**Comment by conanchen** [comment]
it works with tauri@next
