### ISSUE TITLE
Infinite loading during first window spawn, no errors.

### ISSUE THREAD

**Issue by jdheeter** [tauri-apps/tauri#2367]
### **Describe the issue**
I'm having an issue with Tauri where the app starts without error and spawns the first window, which then seems to be loading and freezes, never finishes loading and just is stuck on the initial white screen. The issue is present in dev and after build. In dev mode I tried with and without the dev frontend server and I found the same result. I created a fresh tauri project with tauri init and was able to reproduce the issue on my machine.

### **To Reproduce**
1. Yarn tauri init
2. Yarn tauri dev
3. Tauri launches and spawns first window (blank white), window never displays page (stays white) and shows system busy (loading cursor) when interacting with window.

### **Expected behavior**
Tauri window should spawn, render html and be interactive.

### **Platform and Versions (required):**
```
Operating System - Mac OS, version 11.4.0 X64

Node.js environment
  Node.js - 14.16.0
  @tauri-apps/cli - 1.0.0-beta.6
  @tauri-apps/api - 1.0.0-beta.5

Global packages
  npm - 7.6.3
  yarn - 1.22.10

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/node_modules
/src-tauri

App
  tauri.rs - 1.0.0-beta.5
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ./frontend
  devPath - http://localhost:8000
```

### **Additional context**
was working without issue a few days ago, maybe a full reinstall of tauri would help.

**Comment by lucasfernog** [comment]
Can you create a repo that we can use to reproduce it? This depends on your front end.

**Comment by jdheeter** [comment]
I was unable to repro the issue on another machine even with a minimalist repo. I did a fresh install of rust/tauri, latest macos updates and a reboot and now Tauri is working again. Issue could have been related to M1 Mac hardware emulation layer. Will update here if I see the issue again.

**Comment by xuchaoqian** [comment]
The same bug here. 
Tauri is not working on M1 Mac 11.3, but works well on M1 Mac 11.6

see the minimal repo: [https://github.com/xuchaoqian/tauri-examples.git](https://github.com/xuchaoqian/tauri-examples.git)

@lucasfernog @jdheeter

**Comment by Naoto-Yamaguchi** [comment]
I basically had the same issue. I updated M1 macOS Big Sur 11.4 to 11.7.6 and the problem was solved.
