### ISSUE TITLE
Support file permissions when writing a file

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#2374]
**Is your feature request related to a problem? Please describe.**
I'm unable to set permissions on sensitive files to 600

**Describe the solution you'd like**
Similar to node fs, the javascript api should allow file permissions and would be nice to have read/write flags as well, so that file writing looks like node fs:
```javascript
fs.writeFile(filePath, data, {encoding: 'utf8', flag: 'w', mode: 0o600});
```

**Describe alternatives you've considered**
I've posted in help-triage chat room, I'm unsure how to implement a work around other than including node fs in my bundle

**Additional context**

**Comment by amrbashir** [comment]
Closing in favor of #2233.
