### ISSUE TITLE
Remove NodeJS as a requirement

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#2375]
**Is your feature request related to a problem? Please describe.**
NodeJS is a requirement. I'm frustrated because I only need Rust and HTML,CSS,JS in my apps. usually with webpack or other bundlers like esbuild.

**Describe the solution you'd like**
Make it optional.

**Describe alternatives you've considered**
Remove it completely.

**Comment by nothingismagick** [comment]
Nodejs is not a hard requirement. You can do everything with cargo:

```
> cargo install tauri-cli --version ^1.0.0-beta.5
> cargo tauri dev
```

**Comment by ghost** [comment]
Oh, okay. Thanks. You should clarify that in the docs! How can I contribute to the docs?

**Comment by nothingismagick** [comment]
You could file an issue at the docs repo, or dive in and make a PR

**Comment by amrbashir** [comment]
Docs are now hosted in this repo, you can contribute and make PRs here to `docs` folder in the repo root.

**Comment by ghost** [comment]
> Nodejs is not a hard requirement. You can do everything with cargo:
> 
> ```
> > cargo install tauri-cli --version ^1.0.0-beta.5
> > cargo tauri dev
> ```

I am getting this error:
thread 'main' panicked at 'Couldn't recognize the current folder as a Tauri project.', /home/dragon/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-cli-1.0.0-beta.5/src/helpers/app_paths.rs:29:3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I did: cargo new MY_PROJECT

cd MY_PROJECT
cargo tauri dev

**Comment by nothingismagick** [comment]
Without running `cargo tauri init` first, there is no project rigged. Please visit our discord for help
