### ISSUE TITLE
Error codes still reference tauri.config.js

### ISSUE THREAD

**Issue by tensor-programming** [tauri-apps/tauri#238]
**Describe the bug**
Running tauri build with an incorrect directory structure results in this error: `Did you forget to build your web code or update the build.distDir in tauri.conf.js?`

**To Reproduce**
1. Create a tauri project
2. initialize the tauri project
3. point the distDir towards an incorrect path
4. see error

**Expected behavior**
Should reference the new `tauri.config.json`.

**Comment by nothingismagick** [comment]
Please confirm you are using the dev branch. We haven't published the newest versions of everything yet, as far as I know.

**Comment by tensor-programming** [comment]
Yes, its the dev branch on the latest commit.

**Comment by lucasfernog** [comment]
This is fixed on one of my open PRs.

**Comment by lucasfernog** [comment]
#235 actually
