### ISSUE TITLE
window.__TAURI_INVOKE_KEY__ missing after navigation to remote URL

### ISSUE THREAD

**Issue by pzeinlinger** [tauri-apps/tauri#2383]
### **Describe the bug**

window.\_\_TAURI_INVOKE_KEY\_\_ is missing after navigating to a remote URL by setting window.location.href. This is only happening in production builds, not in development ones.

### **To Reproduce**
1. open some index.html after **building** the application
2. navigate to another page (window.location.href = "example.com")
3. check insepctor
4. window.\_\_TAURI\_\_ is still there
5. window.\_\_TAURI_INVOKE_KEY\_\_ is not

### **Expected behavior**
I'd like to load the application UI only after the user has authenticated through the UI shipped with Tauri and have the full UI still be able to access invoke through Tauri's js api. 

### **Platform and Versions (required):**

```
Operating System - Fedora, version 34.0.0 X64

Node.js environment
  Node.js - 14.17.0
  @tauri-apps/cli - 1.0.0-beta.6
  @tauri-apps/api - 1.0.0-beta.5

Global packages
  npm - 6.14.13
  yarn - 1.22.10

Rust environment
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/node_modules
/public
/src
/src-tauri
/.git
/.github
/dist

App
  tauri.rs - 1.0.0-beta.5
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: tauri: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist
  devPath - http://localhost.medicloud.one:4800
  framework - Svelte
```
Tested on Linux and Windows.

**Comment by nothingismagick** [comment]
Yeah, this is actually expected behaviour at the moment. The invoke key exists to prevent remote and untrustable code from accessing the Tauri API.

**Comment by pzeinlinger** [comment]
Is there a way to get around this or disable this?

**Comment by pzeinlinger** [comment]
invoking through the global tauri object still works. but it'd rather be using the api.

**Comment by nothingismagick** [comment]
Yes, the global object is the only workaround at the moment AFAIK. But that has severe security issues.

**Comment by lucasfernog** [comment]
> I'd like to load the application UI only after the user has authenticated through the UI shipped with Tauri and have the full UI still be able to access invoke through Tauri's js api.

Can you also ship the "authenticated" UI with the tauri app, instead of hosting it and redirecting on the app? That's also helpful if you want your app to be accessed offline.

**Comment by pzeinlinger** [comment]
I don't think so. The actual application is updated quite frequently (at least daily) which is unfeasible to do with tauri (builds take long, no cross compilation). Apart from that there is issue #2327 which makes CORS requests with credentials impossible. 

I'm really out of ideas. I could expose the global tauri object and call it a day, but that's just a last resort "solution".

**Comment by Archieeeeee** [comment]
> I don't think so. The actual application is updated quite frequently (at least daily) which is unfeasible to do with tauri (builds take long, no cross compilation). Apart from that there is issue #2327 which makes CORS requests with credentials impossible.
> 
> I'm really out of ideas. I could expose the global tauri object and call it a day, but that's just a last resort "solution".

Hello, may I ask how to use the global tauri object to quick fix it, I have the same problem and I'm stuck here.
