### ISSUE TITLE
Copy/Paste and Other Keyboard Shortcuts Do Not Work on MacOS

### ISSUE THREAD

**Issue by arpan-dhatt** [tauri-apps/tauri#2397]
### **Describe the bug**
Keyboard shortcuts on MacOS such as `cmd/a`, `cmd/c`, `cmd/v`, `cmd/x`, `cmd/z`, and others do not work in the Tauri window. Right-click context menus do behave correctly, but using the keyboard shortcuts for equivalent actions create the system error sound.

### **To Reproduce**
`npm run tauri dev` and attempt to use keyboard shortcuts to manipulate the field.

### **Expected behavior**
The respective keyboard shortcut to do its default function.

### **Platform and Versions (required):**

```
Operating System - Mac OS, version 12.0.0 X64

Node.js environment
  Node.js - 16.1.0
  @tauri-apps/cli - 1.0.0-beta.6
  @tauri-apps/api - Not installed

Global packages
  npm - 7.11.2
  yarn - Not installed

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/node_modules
/public
/src-tauri

App
  tauri.rs - 1.0.0-beta.5
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../public
  devPath - http://localhost:8080
```

### **Additional context**
Currently running on a MacOS 12.0.0 Public Beta, but this keyboard shortcut error doesn't appear in any other application. Some others were reporting this problem on #1055.

Edit: HTML markup
```
<html>
	<head>
		<title>Tauri Issue</title>
	</head>
	<body>
		<input type="text">
	</body>
</html>
```

**Comment by probablykasper** [comment]
You can fix this by adding a [menu](https://tauri.studio/en/docs/usage/guides/visual/menu)

**Comment by fk1blow** [comment]
sorry to resurrect this but i m having the same issues(macos as well), even after following the [Creating a menu](https://tauri.studio/en/docs/usage/guides/visual/menu/#creating-a-menu) instructions to the letter.

Cannot use cmd+c nor cmd+v which is killing my mojo b/c this is a text editing app.

Edit: followed both [1055](https://github.com/tauri-apps/tauri/issues/1055) and [2398](https://github.com/tauri-apps/tauri/issues/2398) but couldn't understand if this should already work or not.

Edit 2: i'm a bit embarrassed but browsing through the [examples/api](https://github.com/tauri-apps/tauri/blob/dev/examples/api/src-tauri/src/menu.rs) manage to point me into the right direction; copy/paste actually works :D.

Would really appreciated any advice,
Thanks!

**Comment by sunhao8** [comment]
> Edit: followed both [1055](https://github.com/tauri-apps/tauri/issues/1055) and [2398](https://github.com/tauri-apps/tauri/issues/2398) but couldn't understand if this should already work or not.
> 
> Edit 2: i'm a bit embarrassed but browsing through the [examples/api](https://github.com/tauri-apps/tauri/blob/dev/examples/api/src-tauri/src/menu.rs) manage to point me into the right direction; copy/paste actually works :D.
> 
I try the solution you have mentioned, but cmd+c and cmd+v still do not work. Can you tell me the Edit 2?

**Comment by sunhao8** [comment]
> > Edit: followed both [1055](https://github.com/tauri-apps/tauri/issues/1055) and [2398](https://github.com/tauri-apps/tauri/issues/2398) but couldn't understand if this should already work or not.
> > Edit 2: i'm a bit embarrassed but browsing through the [examples/api](https://github.com/tauri-apps/tauri/blob/dev/examples/api/src-tauri/src/menu.rs) manage to point me into the right direction; copy/paste actually works :D.
> 
> I try the solution you have mentioned, but cmd+c and cmd+v still do not work. Can you tell me the Edit 2?

I've read [examples/api](https://github.com/tauri-apps/tauri/blob/dev/examples/api/src-tauri/src/menu.rs) carefully . you are right !
If others have the same problem！you just add 'Menu::new().add_native_item(MenuItem::Copy)' , cmd+c do its default function。

**Comment by serkandemirel0420** [comment]
nope, still not working. Any update?

**Comment by amrbashir** [comment]
@serkandemirel0420 it does work, join our discord and we will help you triage it.

**Comment by nihilok** [comment]
Think the API has changed now, as none of the docs are the same and links in this thread are broken. For anyone trying to maintain an app on the old API I was able to fix this by having a dedicated Edit menu:

```rust
    let file_menu = Submenu::new("File", Menu::new().add_item(new_thread).add_item(history).add_item(quit));
    let edit_menu = Submenu::new("Edit", Menu::new().add_native_item(MenuItem::Copy).add_native_item(MenuItem::Paste).add_native_item(MenuItem::SelectAll));
    Menu::new().add_submenu(file_menu).add_submenu(edit_menu)
```

**Comment by SeanPedersen** [comment]
Still having the same issue with Tauri V2 on Mac... any solution?

**Comment by codesoda** [comment]
> Still having the same issue with Tauri V2 on Mac... any solution?

@SeanPedersen, unfortunately, the only answer I could find was to add an Edit menu with the standard text editing keyboard shortcuts.

e.g.

``` rust
    let main_submenu = SubmenuBuilder ...

    let edit_submenu = SubmenuBuilder::new(&app_handle, "Edit")
        .undo()
        .redo()
        .separator()
        .cut()
        .copy()
        .paste()
        .separator()
        .select_all()
        .build()?;
    // ... any other submenus

    let menu = MenuBuilder::new(&app_handle)
        .items(&[
            &main_submenu,
            &edit_submenu,
        ])
        .build()?;
```

**Comment by SeanPedersen** [comment]
Yes similar solution (not ideal...):
```
fn setup_menu(app: &mut tauri::App) -> Result<(), Box<dyn std::error::Error>> {
    // Create the Edit submenu
    let edit_submenu = SubmenuBuilder::new(app, "Edit")
        .item(
            &MenuItemBuilder::new("Undo")
                .id("undo")
                .accelerator("CmdOrCtrl+Z")
                .build(app)?,
        )
        .separator()
        .item(
            &MenuItemBuilder::new("Cut")
                .id("cut")
                .accelerator("CmdOrCtrl+X")
                .build(app)?,
        )
        .item(
            &MenuItemBuilder::new("Copy")
                .id("copy")
                .accelerator("CmdOrCtrl+C")
                .build(app)?,
        )
        .item(
            &MenuItemBuilder::new("Paste")
                .id("paste")
                .accelerator("CmdOrCtrl+V")
                .build(app)?,
        )
        .separator()
        .item(
            &MenuItemBuilder::new("Select All")
                .id("select_all")
                .accelerator("CmdOrCtrl+A")
                .build(app)?,
        )
        .build()?;

    // Get existing app submenu
    let app_submenu = SubmenuBuilder::new(app, "App")
        .item(
            &MenuItemBuilder::new("Import Directory")
                .id("import_directory")
                .accelerator("CmdOrCtrl+Shift+I")
                .build(app)?,
        )
        .build()?;

    // Create the menu with both submenus
    let menu = MenuBuilder::new(app)
        .item(&app_submenu)
        .item(&edit_submenu)
        .build()?;
    app.set_menu(menu)?;

    // Handle edit menu events
    app.on_menu_event(|app_handle, event| {
        if let Some(window) = app_handle.get_webview_window("main") {
            let js_command = match event.id.0.as_str() {
                "undo" => "document.execCommand('undo')",
                "cut" => "document.execCommand('cut')",
                "copy" => "document.execCommand('copy')",
                "paste" => "document.execCommand('paste')",
                "select_all" => "document.execCommand('selectAll')",
                _ => return,
            };

            let _ = window.eval(js_command);
        }
    });

    Ok(())
}
```
