### ISSUE TITLE
Examples in doc comments

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tauri#2423]
Low priority, but wanted to put it out there.

In a lot of cases, I'd be able to figure out how to use a function by reading the doc comment tooltip, but especially with functions that take traits, it's not easy to tell:
![image](https://user-images.githubusercontent.com/11315492/129415915-8e969818-b4ba-4537-900a-68610cecd4cb.png)

Putting examples in doc comments would help with that.

**Comment by probablykasper** [comment]
How `std::fs::File::open` does it:

![image](https://user-images.githubusercontent.com/11315492/129415870-aad6c9d6-b2da-4aa6-b723-5b95d6c6cf72.png)
```rust
/// Attempts to open a file in read-only mode.
///
/// See the [`OpenOptions::open`] method for more details.
///
/// # Errors
///
/// This function will return an error if `path` does not already exist.
/// Other errors may also be returned according to [`OpenOptions::open`].
///
/// # Examples
///
/// ```no_run
/// use std::fs::File;
///
/// fn main() -> std::io::Result<()> {
///     let mut f = File::open("foo.txt")?;
///     Ok(())
/// }
/// ```
```

**Comment by lucasfernog** [comment]
Can you help us collect a list of methods we should improve first? We're about to really start improving our documentation (next few weeks).

**Comment by probablykasper** [comment]
🤔 I suppose most could be improved? Hard to pick which ones to include and which not to include.

**Comment by lucasfernog** [comment]
Yeah for sure.

**Comment by amrbashir** [comment]
I think there is enough code examples now in the doc comments. Let us know if there is some thing missing an example when it should have one.
