### ISSUE TITLE
Windows: Integrate WebView2 installation into .msi installer

### ISSUE THREAD

**Issue by lumenian** [tauri-apps/tauri#2452]
**Is your feature request related to a problem? Please describe.**
Installation process of a Tauri application on Windows can cause confusion among the end users. At the moment the .msi installer triggers a UAC warning pop-up, that asks the user for the installation of Webview2.

The pop-up asks permission to install a "Windows Edge Update", which might scare users, who don't use Edge the browser and do not understand the need for this dependency.

When the pop-up is closed, permission denied or in an offline environment, we have an awkward situation: the app has been successfully installed, but the user can't launch it. It also does not prompt the Webview2 installation again, nor produce any error messages, that might help the user investigate the issue.

**Describe the solution you'd like**
Installing missing Webview2 dependency should be a part of the .msi installation process itself. This way the app installation becomes an "atomic" procedure: either it successfully installs the app (with all needed dependencies) and it works, or it fails, but the user knows why and does not expect the app to run.

**Additional context**
Useful Discord message by @amrbashir regarding this issue: https://discord.com/channels/616186924390023171/731495028677148753/876757798195716096

**Comment by amrbashir** [comment]
Ideally we want to:
- Check if webview2 is installed
- If webview2 is not installed, Prompt users to install Webview2 after the license screen and let them know the app won't work without it.
- If they said yes, then we use wix to download and install webview2 using [`ExePackage`](https://wixtoolset.org/documentation/manual/v3/xsd/wix/exepackage.html) element.

I don't know if this will bypass the UAC but at least users will know it is for downloading webview2.

**Comment by amrbashir** [comment]
This [webview2 wix sample](https://www.github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps%2FWV2DeploymentWiXBurnBundleSample%2FREADME.md) might be useful.

**Comment by TapGhoul** [comment]
One thing that works for now - if you replace the CustomAction in main.wxs for installing Webview2 with
```
<CustomAction Impersonate='no' Id='DownloadAndInvokeBootstrapper' Directory="INSTALLDIR" Execute="deferred" ExeCommand='powershell.exe -NoProfile -windowstyle hidden Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/p/?LinkId=2124703" -OutFile "$env:TEMP\MicrosoftEdgeWebview2Setup.exe" ; Start-Process -FilePath "$env:TEMP\MicrosoftEdgeWebview2Setup.exe" -ArgumentList (&apos;/silent&apos;, &apos;/install&apos;) -Wait' Return='check'/>
```

This silently installs Webview2 in an elevated context, and keeps the installer on the given step until it's done, rather than deferring it until after the installation has completed and giving a popup.
This hasn't been thoroughly tested, but it works on my machine under a clean environment.

This lacks a step name for the progress bar, but I'm not sure how to get one to display. Would be a nice addition, rather than a blank section during the install progress.
