### ISSUE TITLE
Routing does not work with Vue Router in multiwin mode

### ISSUE THREAD

**Issue by elvinaspredkelis** [tauri-apps/tauri#2453]
**Describe the bug**
I creating two separate windows with separate views for them. 
In order to do that, I'm just trying to route the second window to a path. However, the routing doesn't really work in this case and just defaults to the `/` path.

**To Reproduce**
- Clone and run the following repo: https://github.com/elvinaspredkelis/multiwin-routing-tauri

**Expected behavior**
Once the app starts, the second window should navigate to the `/about` page.

**Environment (please complete the following information):**
 - vue-cli-plugin-tauri version : 1.0.0-beta.6
 - other vue plugins used: N/A
 - (if possible) link to your repo: https://github.com/elvinaspredkelis/multiwin-routing-tauri
 - output from `npx tauri info`/`yarn tauri info`:
 ```
 Operating System - Mac OS, version 11.2.3 X64

Node.js environment
  Node.js - 15.2.0
  @tauri-apps/cli - 1.0.0-beta.6
  @tauri-apps/api - Not installed

Global packages
  npm - 6.14.9
  yarn - 1.22.10

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/node_modules
/public
/src-tauri
/.git
/src

App
  tauri.rs - 1.0.0-beta.5
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - Set automatically by Vue CLI plugin
  devPath - Set automatically by Vue CLI plugin
  framework - Vue.js (Vue CLI)
  bundler - Webpack
  ```

**Additional context**
I've tried different ways to describe the URL in `tauri.conf.json` for the second window: `about`, `/about`, `http://localhost:8081/about` and it still does not navigate to the desired route.

It does navigate to the correct page if I create an about.html page in `/public` directory and then add the URL as `about.html`. However, that is not the desired behaviour and/or Vue doesn't mount on that HTML file.

**Comment by lucasfernog** [comment]
You're using Vue Router's hash mode, so instead of `"url": "about"` you need to use `"url": "#/about"`.
