### ISSUE TITLE
Ability to add widget in Gnome panel

### ISSUE THREAD

**Issue by mushtaqx** [tauri-apps/tauri#2456]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to add widget of my app in Gnome panel/bar.

**Describe alternatives you've considered**
I have checked the docs and couldn't find anything clear.

**Additional context**
See the attachment, i would like to add the widget in those red squares.

![widget-area](https://user-images.githubusercontent.com/45162430/129635943-8df73ba7-ec98-4243-a682-66035c4dc76d.png)

**Comment by amrbashir** [comment]
This is out of tauri scope.

However you could call native apis with rust, and you probably will need to use [gtk-rs](https://gtk-rs.org).
