### ISSUE TITLE
import @tauri-apps/api@1.0.0-beta.6，use method in windo.js ,it happened this!!!

### ISSUE THREAD

**Issue by OceanBelongsToMe** [tauri-apps/tauri#2473]
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file
![image](https://user-images.githubusercontent.com/22573382/129763625-43eb8533-7bd5-4a7d-be5a-c09b2a261fdd.png)

### **To Reproduce**
1. vue create my_project
2. cd my_project and choose vue3、router..
3. yarn add @tauri-apps/api, then import  api/window in vue file 
4. yarn tauri:serve

### **Platform and Versions (required):**

```
Operating System

Node.js environment
Node.js 
@tauri-apps/cli 
@tauri-apps/api 

Global packages
npm 
yarn 

Rust environment
rustc 
cargo 

App directory structure


App
tauri.rs 
build-type 
CSP 
```

**Comment by lucasfernog** [comment]
seems like adding a 
```js
module.exports = {
  transpileDependencies: ['@tauri-apps/api']
}
```
vue.config.js fixes it. I think vue didn't like our ES2021 target :(

**Comment by lucasfernog** [comment]
It also works if you create a Vue CLI project with Typescript support (since I think Vue starts pulling our TS files instead of the ones that are transpiled to ES2021).

**Comment by OceanBelongsToMe** [comment]
@lucasfernog Thanks!  it's works !!

**Comment by nothingismagick** [comment]
Please when you file issues fill out the report. Don't pack everything into the issue title. We can't help you if you don't explain in detail what OS and versions you are running.

**Comment by stevebauman** [comment]
Thank you @lucasfernog! ❤️ 

For devs on Nuxt v2, I had to add this to my `build` property in my `nuxt.config.js` file:

```js
// nuxt.config.js

module.exports = {
    // ...
    
    // Build Configuration: https://go.nuxtjs.dev/config-build
    build: {
        transpile: ['@tauri-apps/api'],
    }
}
```

Started compiling normally after that entry 👍
