### ISSUE TITLE
I tried to get clientX through mouse movement events, but it seems to be inconsistent and intermittent

### ISSUE THREAD

**Issue by OceanBelongsToMe** [tauri-apps/tauri#2474]
### **Platform and Versions (required):**

```
Operating System

Node.js environment
Node.js 
@tauri-apps/cli 
@tauri-apps/api 

Global packages
npm 
yarn 

Rust environment
rustc 
cargo 

App directory structure


App
tauri.rs 
build-type 
CSP 
```

**Comment by OceanBelongsToMe** [comment]
Need to press the mouse and then slide to trigger continuously

**Comment by nothingismagick** [comment]
Please when you file issues fill out the report. Don't pack everything into the issue title. We can't help you if you don't explain in detail what OS and versions you are running.
