### ISSUE TITLE
How to clear Tauri window cache?

### ISSUE THREAD

**Issue by 11reed** [tauri-apps/tauri#2475]
On my localhost web page, the cache is cleared and I see my changes, however my changes are not shown in the Tauri window. I tried to build my project with npm, and no change either.

**Comment by 11reed** [comment]
Accidently closed

**Comment by nothingismagick** [comment]
@11reed - we have an issue template. In the future, please fill out the entire issue template, because otherwise there is generally speaking no way for us to triage or help you. This is why no one responded.
