### ISSUE TITLE
Module '"@tauri-apps/api"' has no exported member 'os'

### ISSUE THREAD

**Issue by Diomas** [tauri-apps/tauri#2476]
### **Describe the bug**
I'm trying to import bunch of tauri modules into a typescript file. But `os` module seems to be not exported.

### **To Reproduce**
1. type `import { fs, path, os } from '@tauri-apps/api';` into your ts/js file
2. see IDE or compiler error: `export 'os' was not found in '@tauri-apps/api'`

### **Expected behavior**
I expect `os` module to be one of exported from @tauri-apps/api

### **Screenshots**
![image](https://user-images.githubusercontent.com/856038/129788732-fa738346-c3d4-42c0-a57a-a7cdee4d0858.png)

### **Platform and Versions (required):**
```
Operating System - Windows, version 10.0.14393 X64
Webview2 - 92.0.902.73

Node.js environment
  Node.js - 14.17.5
  @tauri-apps/cli - 1.0.0-beta.5
  @tauri-apps/api - 1.0.0-beta.4

Global packages
  npm - 6.14.14
  yarn - 1.22.10

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/.git
/build
/node_modules
/src
/src-tauri
/tests

App
  tauri.rs - 1.0.0-beta.4
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:8080
  framework - React
```

**Comment by FabianLars** [comment]
The os module got added in @tauri-apps/api@1.0.0-beta.6, you're using beta.4. Please update your dependencies and try again :)

Edit: As of today, the current versions are:
- @tauri-apps/cli: `1.0.0-beta.8`
- @tauri-apps/api: `1.0.0-beta.6`
- tauri (rust): `1.0.0-beta.7`

Edit2: while you're at it, your rust version is outdated too

**Comment by nothingismagick** [comment]
Thanks @FabianLars - you are absolutely right. :)
