### ISSUE TITLE
Window focus and blur events are not being emitted on macOS and Linux

### ISSUE THREAD

**Issue by elvinaspredkelis** [tauri-apps/tauri#2485]
### **Describe the bug**
`tauri://focus` and `tauri://blur` are not being emitted on macOS (and on Linux it seems). 

Other events are working just fine.

### **To Reproduce**
Add window event listeners:

```
appWindow.listen("tauri://focus", ({event, payload}) => {
  console.log(event)
  console.log(payload)
})
appWindow.listen("tauri://blur", ({event, payload}) => {
  console.log(event)
  console.log(payload)
})
```

### **Expected behavior**
Events being emitted.

### **Platform and Versions (required):**

```
Operating System - Mac OS, version 11.2.3 X64

Node.js environment
  Node.js - 16.6.2
  @tauri-apps/cli - 1.0.0-beta.7
  @tauri-apps/api - 1.0.0-beta.6

Global packages
  npm - 7.20.3
  yarn - 1.22.11

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/node_modules
/public
/src-tauri
/lib
/.git
/src

App
  tauri.rs - 1.0.0-beta.7
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - Set automatically by Vue CLI plugin
  devPath - Set automatically by Vue CLI plugin
  framework - Vue.js (Vue CLI)
  bundler - Webpack
```

**Comment by amrbashir** [comment]
This is a regression of this commit https://github.com/tauri-apps/tauri/commit/d832d575d9b03a0ff78accabe4631cc638c08c3b#diff-3ea5d010cd769e8868d63bbc0cdea941abc3a3c4a9bc48af6668d22471224ad4L284

Instead of removing Line 284 completely, it should be behind a compilation flag for linux and macos.
