### ISSUE TITLE
Potential black screen on Windows

### ISSUE THREAD

**Issue by wusyong** [tauri-apps/tauri#2496]
### **Describe the bug**
Some users reported that when unminimizing a window after hours, it has a rare chance to turn black.

### **To Reproduce**
**Unkown. We need a reproducible minimum example.**

### **Expected behavior**
The window behaves as usual.

### **Platform and Versions (required):**
OS: Windows
Rustc: Stable

### **Additional context**
There is a section of [tao](https://docs.rs/tao/0.5.2/tao/#drawing-on-the-window) document that mentions about drawing.
Sometimes if the window is not drawn, it might show garbage data (which is black screen in this case).
So to properly solve this we might want to send `request_redraw` when showing the window again.

**Comment by nothingismagick** [comment]
If it's only sometimes, maybe it has to do with a security setting or a screensaver?

**Comment by lucasfernog** [comment]
I'll close this since we changed a lot since this issue and no one reported it anymore.

**Comment by Bwc9876** [comment]
Sorry for the necro, but this exact situation seems to have happened for one of the people using my app.
![image](https://github.com/tauri-apps/tauri/assets/25644444/7bdf09c5-bac9-4302-878f-dad08204dd7f)
*(After a few hours)*

![image](https://github.com/tauri-apps/tauri/assets/25644444/e2c17e46-136b-4ac4-a03b-5b51c6457951)
*(Task manager, is it normal for there to be no Webview instances?)*

Something that may be important to note is that a command *has* been active for those hours, as the black window uses a command to start a TcpListener on a socket. I don't know if that's relevant but might as well mention it.

Relevant tauri info:
```
[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.1
    - @tauri-apps/api [NPM]: 1.3.0
    - @tauri-apps/cli [NPM]: 1.3.1

[-] App
    - build-type: bundle
    - CSP: default-src 'self'
    - distDir: ../dist
    - devPath: http://localhost:5173/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment]
@Bwc9876 
> (Task manager, is it normal for there to be no Webview instances?)

That depends. the task manager is indeed pretty bad at grouping the processes. That said, if there are no webview2 processes in the whole list, and not just in that group then this is not normal and something i've not seen so far.

**Comment by Bwc9876** [comment]
> That depends. the task manager is indeed pretty bad at grouping the processes. That said, if there are no webview2 processes in the whole list, and not just in that group then this is not normal and something I've not seen so far.

Ah, the processes were probably elsewhere then, the person got this bug again a bit later and they were listed under the main task properly.
