### ISSUE TITLE
2

### ISSUE THREAD

**Issue by cannotbegin** [tauri-apps/tauri#2501]
Hi everyone. I encountered a problem when using ‘Rust Commands’. 
The problem is that I pass a parameter from js to rust and return a result. The code is as follows:
function rustwebapi() {
        invoke('jstorustwebapi', {invokeMessage:'https://jsonplaceholder.typicode.com/posts/2' })
        .then((message) => {
            let textId = document.getElementById('#rustwebapi');
            textId.val(JSON.stringify(message));
        })
    }

My rust code is as follows：

async fn get_post_as_string2(url: String) -> Result<String, Box> {
    println!("get_post_as_string2:{}", url);
    let s = reqwest::get(&url).await?.text().await?;
    println!("get_post_as_string2:{}", s);
    Ok(s)
}

async fn some_other_function(invoke_message: String) -> Option {
    let webapistr = get_post_as_string2(invoke_message).await.unwrap();
    Some(webapistr.into())
}

#[tauri::command]
async fn jstorustwebapi(invoke_message: String) -> Result<String, String> {
    let result: Option = some_other_function(invoke_message).await;
    if let Some(message) = result {
        Ok(message.into())
    } else {
        Err("No result".into())
    }
}

But when calling, the following error is returned:
thread'tokio-runtime-worker' panicked at'not currently running on a Tokio 0.2.x runtime.', C:\Users\hanxi\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\ src\runtime\handle.rs:118:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

How to solve the problems? Thank you.

_Originally posted by @hanxiaohuivc in https://github.com/tauri-apps/tauri/discussions/2495_

**Comment by lemarier** [comment]
Please refer to the original thread for the answer.
