### ISSUE TITLE
Tauri HTTP Fetch not working with large files

### ISSUE THREAD

**Issue by Penca53** [tauri-apps/tauri#2518]
### Tauri HTTP Fetch not working with large files
I'm trying to fetch some release assets from GitHub APIs (format `octet-stream`). If the size of the file is small (I tried with ~7MB), everything works fine. If the size of the file is large (I tried with ~70MB), the request won't succeed (no .then or .catch). I can see from the network manager that it is downloading it, but after it finishes, the app freezes, and after some seconds (~20-30s), it unfreezes and shows a white screen.

### To Reproduce
1. Fetch a file using a GET request.
2. Wait for the response.

### Expected behavior
The fetch operation succeeds and returns the correct data, even with large files.

### My Code
```ts
getReleaseAsset(url: string): void {
  http
    .fetch<ArrayBuffer>(url, {
      method: 'GET',
      headers: { Accept: 'application/octet-stream' },
      responseType: http.ResponseType.Binary,
    })
    .then((res: http.Response<ArrayBuffer>) => {
      console.log(res.status);
    })
    .catch((err: any) => console.log(err));
}
```

### Platform and Versions:

```
Operating System - Windows, version 10.0.19042 X64
Webview2 - 92.0.902.78

Node.js environment
  Node.js - 15.8.0
  @tauri-apps/cli - 1.0.0-beta.7 (outdated, latest: 1.0.0-beta.9)
  @tauri-apps/api - 1.0.0-beta.6

Global packages
  npm - 7.14.0
  yarn - 1.22.10

Rust environment
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/dist
/node_modules
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.7
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:4200
  framework - Angular
  bundler - Webpack
```

### Stack Trace
No errors.

**Comment by jloiola** [comment]
Getting no love. Can we get a comment on this one?

**Comment by Penca53** [comment]
My solution to this "bug" (not sure if it is actually one, probably yes) was to write a custom Tauri command in Rust (I apologize if my Rust code is _not_ rusty):
```rust
#[tauri::command]
async fn download_file(url: String, path: String) -> Result<(), String> {
  let client = reqwest::Client::new();

  // Reqwest setup
  let res = client
    .get(&url)
    .header(
      USER_AGENT,
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0",
    )
    .header(ACCEPT, "application/octet-stream")
    .send()
    .await
    .or(Err(format!("Failed to GET from '{}'", &url)))?;
  let total_size = res
    .content_length()
    .ok_or(format!("Failed to get content length from '{}'", &url))?;

  // Download chunks
  let mut file = File::create(&path).or(Err(format!("Failed to create file '{}'", &path)))?;
  let mut downloaded: u64 = 0;
  let mut stream = res.bytes_stream();

  while let Some(item) = stream.next().await {
    let chunk = item.or(Err(format!("Error while downloading file")))?;
    file
      .write(&chunk)
      .or(Err(format!("Error while writing to file")))?;
    let new = min(downloaded + (chunk.len() as u64), total_size);
    downloaded = new;
  }

  return Ok(());
}
```
Any suggestion / feedback is appreciated 😃 .

**Comment by lucasfernog** [comment]
Sorry guys, I'll take a look at this one.

**Comment by lucasfernog** [comment]
Unfortunately our IPC isn't recommended for large binary payloads. You can take a look at [tauri-invoke-http](https://github.com/tauri-apps/tauri-invoke-http) as an alternative implementation. We will investigate core solutions for tauri v2.
