### ISSUE TITLE
Compile error after update to wry@0.12.2 with `tauri deps update`

### ISSUE THREAD

**Issue by fengkx** [tauri-apps/tauri#2519]
### **Describe the bug**
After update to latest wry 0.12.2
npx tauri build produce a compile time error.

### **To Reproduce**
1. git clone https://github.com/fengkx/plastic-editor-react
2. setup dependencies both pnpm, rust and node_modules
3. run `tauri build`

### **Platform and Versions (required):**
Operating System - Arch Linux, version Rolling Release X64

Node.js environment
  Node.js - 15.12.0
  @tauri-apps/cli - 1.0.0-beta.10
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected character 't' while parsing major version number")', src/info.rs:323:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  @tauri-apps/api - tauri-apps
 app:spawn Command "/home/fengkx/project/plastic-editor-react/node_modules/.pnpm/@tauri-apps+cli@1.0.0-beta.10/node_modules/@tauri-apps/cli/bin/tauri-cli" failed with exit code: 101 +0ms

### **Stack Trace**
```plain
error[E0308]: mismatched types
    --> /home/fengkx/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/tauri-runtime-wry-0.2.0/src/lib.rs:2380:16
     |
2380 |       protocol(url)
     |                ^^^ expected `str`, found struct `Request`
     |
     = note: expected reference `&str`
                found reference `&Request`

error[E0308]: mismatched types
    --> /home/fengkx/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/tauri-runtime-wry-0.2.0/src/lib.rs:2382:50
     |
2382 |           let mime_type = MimeType::parse(&data, url);
     |                                                  ^^^ expected `str`, found struct `Request`
     |
     = note: expected reference `&str`
                found reference `&Request`

error[E0308]: mismatched types
    --> /home/fengkx/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/tauri-runtime-wry-0.2.0/src/lib.rs:2380:7
     |
2380 | /       protocol(url)
2381 | |         .map(|data| {
2382 | |           let mime_type = MimeType::parse(&data, url);
2383 | |           (data, mime_type)
2384 | |         })
2385 | |         .map_err(|_| wry::Error::InitScriptError)
     | |_________________________________________________^ expected struct `Response`, found tuple
     |
     = note: expected enum `Result<Response, _>`
                found enum `Result<(Vec<u8>, std::string::String), _>`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `tauri-runtime-wry`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: failed to build app
```

You can also see the error in https://github.com/fengkx/plastic-editor-react/runs/3401647880?check_suite_focus=true#step:8:487

**Comment by lucasfernog** [comment]
you need to update to the latest tauri beta. Please reopen if it still fails.
