### ISSUE TITLE
[docs] Save window size/position between app launches

### ISSUE THREAD

**Issue by Akryum** [tauri-apps/tauri#2521]
Is there a recommended way of saving and restoring windows positions/sizes? This is a *very* common use case and should probably be documented.

**Comment by lemarier** [comment]
> Is there a recommended way of saving and restoring windows positions/sizes? This is a _very_ common use case and should probably be documented.

You have an OS in mind? I know with OSX its a matter of naming convention when we create the NSWindow but its not implemented yet.

For other OS not sure if the underlying api’ can handle it.

**Comment by Akryum** [comment]
I guess for all supported OSes

**Comment by amrbashir** [comment]
Until we write a proper guide, here is an summary of how it might be done:
1. Remove the window from tauri.conf.json as it will be created programmatically in rust.
2. Before the Tauri app closes, you save width, height , x and y position in a json file or any other format, somewhere on the user filesystem.
3. Before the Tauri app starts, right before the `tauri::Builder` code in `main.rs`, you read the json file and use the saved values when creating the window `app.create_window()` inside `.setup()` hook on the `tauri::Builder`

**Comment by Akryum** [comment]
> Remove the window from tauri.conf.json as it will be created programmatically in rust.

Could Tauri handle it automatically for the default window? That would be a very nice DX

**Comment by amrbashir** [comment]
I guess that decision should be made by @lucasfernog

**Comment by lemarier** [comment]
In macOS, we can use https://developer.apple.com/documentation/appkit/nswindow/1419509-setframeautosavename who saves automatically the window position.

**Comment by lucasfernog** [comment]
If we can let the OS handle it, that would be great. Otherwise I think it should be handled on the user side (maybe a plugin).

**Comment by amrbashir** [comment]
It is not possible on Windows and Linux unfortunately.

**Comment by Akryum** [comment]
> If we can let the OS handle it, that would be great. Otherwise I think it should be handled on the user side (maybe a plugin).

Well the OS doesn't handle it on Windows and Linux. :(

**Comment by amrbashir** [comment]
> If we can let the OS handle it, that would be great. Otherwise I think it should be handled on the user side (maybe a plugin).

Then I think we need to add `on_app_exit()` and `on_window_close()` hook to the plugin system, don't you think ?

**Comment by lucasfernog** [comment]
https://github.com/tauri-apps/tauri-plugin-window-state
