### ISSUE TITLE
High CPU and blank screen on virtual Windows

### ISSUE THREAD

**Issue by beka** [tauri-apps/tauri#2530]
First of all, kudos to all developers of Tauri, incredible technology for creating small and fast desktop applications!
### **Describe the bug**
The bug occurs only on Windows virtual instances (both QEMU and VirtualBox tested). Running **any** tauri compiled binary only shows a white window, and the process causing 100% CPU usage. The bug occurred first when I tried to run a real project with bunch of code on ReactJS, which was ideally running and compiling on Linux and MacOS machines. In order to identify the cause of the bug I created a static html file without any JavaScript code included and tried to compile and run on Windows machine. The result was the same - The application was running on Linux, MacOS and it was compiling but not running properly on a virtual Windows machine.  

### **To Reproduce**
Run any tauri compiled binary file on a Windows virtual instance. 

### **Expected behavior**
I expected the app to render the static HTML

### **Screenshots**
![Screenshot from 2021-08-25 16-09-44](https://user-images.githubusercontent.com/644909/130788332-645dff43-b818-4b04-9edf-9da760701cc6.png)
Screenshot 1. Simple app that runs on a non-virtaul Windows machine. (Screnshot done via gnome-screenshot on Linux machine connected to Windows via RDP). In this scenario app runs as expected.

![Screenshot from 2021-08-25 15-50-37](https://user-images.githubusercontent.com/644909/130788398-4429c463-9e3f-4c99-b91b-49723fb42dfa.png)
Screenshot 2. The same app running on virtual Windows machine. The application windows is always blank and the app is causing 100% CPU. (Screnshot done via gnome-screenshot on Linux machine connected to virtual Windows via VNC)

### **Platform and Versions (required):**
This information comes from virtual Windows machine where the final app is causing 100% CPU load

```
yarn run v1.22.11
warning package.json: No license field
$ tauri info
 app:spawn Running "C:\Users\user\Desktop\internal\x\tauri-app\node_modules\@tauri-apps\cli\bin\tauri-cli.exe tauri info" +0ms


Operating System - Windows, version 10.0.19043 X64
Webview2 - 92.0.902.78

Node.js environment
  Node.js - 14.17.5
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.20.6
  yarn - 1.22.11

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/dist
/node_modules
/src-tauri

App
  tauri.rs - 1.0.0-beta.8 (no lockfile)
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - ../dist

Done in 16.66s.
```

### **Additional context**
There are no errors on console shown in the debug mode. First I thought that it was WebView2-related issue, but I managed to compile and run C#/WebView2 sample from official Microsoft repo on the same virtual instance that fails to launch tauri built project.

**Comment by nothingismagick** [comment]
Thankyou for the bug report! Is it possible that there is no webview2 in the VM and there is no outbound networking enabled? Just guessing though

**Comment by beka** [comment]
> Thankyou for the bug report! Is it possible that there is no webview2 in the VM and there is no outbound networking enabled? Just guessing though

**As for the webview:**
tauri info says that there is "Webview2 - 92.0.902.78" on Windows virtual machine installed. And if I'm not mistaken "msedgewebview2.exe" on the second screenshot is launched by the binary, so I'm pretty sure that webview2 is installed on the VM

As for the **outbound networking enabled*:
For React debugging purposes, I'm running local web server via Node on the Windows virtual instance and  I can connect to the local server as 127.0.0.1 and localhost. Is it enough or should I check additional Windows Firewall rules?

**Comment by nothingismagick** [comment]
Hmm. ok - then I am out of ideas for the moment. We're going to have to dig into this then.

**Comment by beka** [comment]
For testing purporses, I have downloaded and installed the software listed on Tauri Studio website's Showcase page. The applications that were released in 2020 (For example, GUIJS and LuckyYou) are running pretty well and the above-mentioned bug is not reproduced. But **Mail-Dev** application that was released July, 2021 is causing the same High CPU and the window is blank. It looks like the problem originated in the last versions of tauri.

**Comment by fogine** [comment]
I also experience blank application window and immediate crash in Windows VM.. 
It crashes immediately only when I try to run build release binary.. `development` mode with `npm run tauri:serve` (`tauri dev`) works as expected.. thus its hard to debug. I have only Windows in VM so cant test on real machine..

This is output of `tauri info` :
```
Operating System - Windows, version 10.0.17763 X64
Webview2 - 93.0.961.38

Node.js environment
  Node.js - 16.7.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.20.3
  yarn - 1.22.11

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/bds
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - Set automatically by Vue CLI plugin
  devPath - Set automatically by Vue CLI plugin
  framework - Vue.js (Vue CLI)
  bundler - Webpack
```

**Comment by FabianLars** [comment]
@fogine Sounds more like https://github.com/tauri-apps/tauri/issues/2570 to me 🤔

**Comment by amrbashir** [comment]
Do you still experience this issue?

**Comment by lucasfernog** [comment]
I've switched to QEMU recently for all my Windows usage and Tauri is running fine (I use both the Tauri examples and a more complex app I'm working on), maybe you could share your configuration? We can reopen if the issue is still happening.
