### ISSUE TITLE
@tauri-apps/cli > 1.0.0.6-beta.6 increase AppImage size

### ISSUE THREAD

**Issue by tcastelly** [tauri-apps/tauri#2539]
### **Describe the bug**
Hello,

I'm using Tauri with VueJS + Vite with Tauri Github Action.
By simply upgrade `@tauri-apps/cli` to > `1.0.0-beta.6` the size of my AppImage build increase from 6mB to 67mB. (Not the .deb). 

### **To Reproduce**
It's difficult to reproduce because I have the problem only with Github Action.
But this is my repo:
https://github.com/tcastelly/vue-tauri-vite

### **Platform and Versions (required):**

I use https://github.com/tauri-apps/tauri-action with `ubunntu-latest`

### **Additional context**
The .deb release does not have the issue

**Comment by lucasfernog** [comment]
Previously the AppImage didn't include all the shared library referenced by the binary. Now it does, so the size is larger. This is a limitation of these packages, there's nothing we can do AFAIK.

**Comment by tcastelly** [comment]
OK, thank you for your answer.
