### ISSUE TITLE
Unknown variant `resolvePath`

### ISSUE THREAD

**Issue by tdelabro** [tauri-apps/tauri#2542]
Hey, I just updated tauri from beta.5 to beta.8 and a new error pop out.

I'm trying to use
```js
import { videoDir } from "@tauri-apps/api/path";
await videoDir().catch(console.log);   
```
And the call to `videoDir` fail with:
```
unknown variant `resolvePath`, expected one of `readTextFile`, `readBinaryFile`, `writeFile`, `writeBinaryFile`, `readDir`, `copyFile`, `createDir`, `removeDir`, `removeFile`, `renameFile`
```

My guess is that it does not recognise anymore the command `resolvePath`, which is internaly called by `videoDir`:
```rust
async function videoDir(): Promise<string> {
  return invokeTauriCommand<string>({
    __tauriModule: 'Fs',
    message: {
      cmd: 'resolvePath',
      path: '',
      directory: BaseDirectory.Video
    }
  })
```

**Comment by FabianLars** [comment]
What is your tauri version in Cargo.toml? Please update it to beta.8 (maybe run `cargo update` afterwards just to be safe) and try again.
Edit: nvm i think it's the api package that's the wrong version. Update it to beta.8 too (maybe delete the lock file and the node_modules/ folder afterwards 🤷 )

If this doesn't fix the problem please post the output of `tauri info`.

Edit2: For issues like this, please fill out the stuff that's marked with `required` in the Issue Template (in this case, the output of `tauri info`). Makes it easier for others to help you.

**Comment by tdelabro** [comment]
Hi Fabian.
So I edited my project package.json to use:
```json
  "devDependencies": {
    "@tauri-apps/cli": "^1.0.0-beta.8"
  },
  "dependencies": {
    "@tauri-apps/api": "^1.0.0-beta.8"
  ```
  
  But I'm stuck in cargo.toml
  ```rust
  [build-dependencies]
tauri-build = "1.0.0-beta"
```

If I try to use `tauri-build = "1.0.0-beta.8"`, I get an error whil running `yarn tauri dev`
```
 app:spawn Running "/Users/timothee/Documents/tdelabro/unrush/node_modules/@tauri-apps/cli/bin/tauri-cli tauri dev" +0ms

    Updating crates.io index
error: failed to select a version for the requirement `tauri-build = "^1.0.0-beta.8"`
candidate versions found which didn't match: 0.0.0
location searched: crates.io index
required by package `app v0.1.0 (/Users/timothee/Documents/tdelabro/unrush/src-tauri)`
```

**Comment by tdelabro** [comment]
```
timothee@Timothees-MacBook-Pro ~/D/t/unrush [101]> tauri info
[tauri]: running info

Operating System - Darwin(20.4.0) - darwin/x64

Node.js environment
  Node.js - 16.5.0
  tauri.js - 0.14.1

Rust environment
  rustc - 1.53.0
  cargo - 1.53.0
  tauri-bundlerNot installed

Global packages
  NPM - 7.19.1
  yarn - 1.22.10

App directory structure
/front
/node_modules
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  mode - unset
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../front
  devPath - http://localhost:5000
  ```

**Comment by FabianLars** [comment]
So, the latest versions are:
`"@tauri-apps/cli": "^1.0.0-beta.10"`
`"@tauri-apps/api": "^1.0.0-beta.8"`
`tauri-build = "1.0.0-beta.4"`
`tauri = "1.0.0-beta.8"`

tauri info also shows that you have tauri.js installed, so if you have a package that''s called just `tauri` in your `package.json`(!), remove that too.  
(also make sure to delete the yarn.lock file and node_modules folder before running `yarn install`, just to be safe :P )

Edit: I also suggest upgrading rust to 1.54, because it enabled `Incremental Compilation` again 🥳

**Comment by tdelabro** [comment]
Thank a lot it fixed it.
Sorry I though naively that all package were moving together at the same path. Obviously they don't !

I also upgraded rust to 1.54, thanks for the tip.

Is there a way to make this process upgrading the different moving part smoother ? Or should I just go check manually what is the latest version for each package ?

```
tauri info also shows that you have tauri.js installed, so if you have a package that''s called just tauri in your package.json(!), remove that too.
```
No such a package in package.json
```
{
  "name": "unrush",
  "version": "1.0.0",
  "main": "index.js",
  "repository": "",
  "author": "you",
  "license": "MIT",
  "devDependencies": {
    "@tauri-apps/cli": "^1.0.0-beta.10"
  },
  "dependencies": {
    "@tauri-apps/api": "^1.0.0-beta.8"
  }
```
Is having tauri.js installed a problem ?

Thanks a lot for the help again !

**Comment by FabianLars** [comment]
> Is there a way to make this process upgrading the different moving part smoother ? Or should I just go check manually what is the latest version for each package ?  

There's also `tauri deps update` to update tauri related dependencies (doesn't update other dependencies iirc).  
Personally i prefer something like [ncu](https://www.npmjs.com/package/npm-check-updates).

> Is having tauri.js installed a problem ?  

Generally it shouldn't as long as you don't reference it in your code. But maybe it was just a false positive anyway 🤷 

  
  
Don't forget to close the issue if it's resolved :)
