### ISSUE TITLE
App periodically freezes

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tauri#2543]
### **Describe the bug**

I've noticed Tauri sometimes freezing, for several seconds. It's not super frequent, but if I'm working on an app for several hours, there's a good chance it'll happen. I don't know if it happens in production.

Sometimes, I'll just focus the app, click a button and nothing happens for a few seconds. Other times, I'm changing something and the HMR update won't show, then I click the app and then they suddenly show.

### **To Reproduce**
Haven't found any reliable way to reproduce it, it might take 1-3 hours before the freeze reveals itself. Sounds painful to debug :(

### **Platform and Versions**

<details>
<summary>Details</summary>

```
Operating System - Mac OS, version 10.15.7 X64

Node.js environment
  Node.js - 14.16.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.11
  yarn - 1.22.10

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/node_modules
/src-tauri
/build
/.git
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:8000
  framework - Svelte
```

</details>

**Comment by loucass003** [comment]
Can confirm this is a thing. happened to me several times. especially since i disabled the decorations on the app

**Comment by LoonyRules** [comment]
I know this has been open for a while but just want to chime in to mention this happens frequently for our project too :(

**Comment by koriwi** [comment]
Same here

**Comment by ThatXliner** [comment]
Sometimes happens on Tauri dev

**Comment by probablykasper** [comment]
Closing because I haven't noticed this one in a very long time
