### ISSUE TITLE
[Question] How many time does release build needed on MacOs?

### ISSUE THREAD

**Issue by bigdogs** [tauri-apps/tauri#2554]
Hi, 
 `cargo tauri build`  was hang for about 4 hours for my empty demo(crated by `cargo tauri init`),  Not sure if this is a normal case. 
![image](https://user-images.githubusercontent.com/20614926/131336891-9b29b33a-1605-473d-a3e7-642c00219a41.png)
I notice that `rustc` is still working 
![image](https://user-images.githubusercontent.com/20614926/131337009-9d103d58-bb66-4fed-95a5-da89d5305588.png)

**Comment by bigdogs** [comment]
Compiled failed finally...  :(

(signal: 9, SIGKILL: kill)
Error: failed to build app

**Comment by seryj** [comment]
Same or similar issue here on Ubuntu 21.04. Building in release mode hangs in the building step for a undefinite period of time. 

I'm using latest beta.10 version. No web frameworks (so no Vue, Angular or similar) are used but part of the code uses WASM (if this is somehow relevant).

Any ideas what could be the reason?

**Comment by lucasfernog** [comment]
Can you guys share your `tauri info` output? Specifically I'd like to know the `distDir` on your tauri.conf.json file.

**Comment by seryj** [comment]
Hi Lucas, 

after your comment, I was able to fix the issue. In my case, I was executing the `npm run tauri build` command from parent directory of `src-tauri` (in which index.html is located). But it looks like that `distDir` was looking for `index.html` not relative to `src-tauri` but relative to my current directory. After changing `distDir` to `./`, everything started working. 

Not sure if I was using `tauri` wrong - if yes sorry for confusion!

Sergej

**Comment by lucasfernog** [comment]
distDir is relative to src-tauri, but you can't use `./` since that'll increase your bundle size (including target folder etc).

**Comment by seryj** [comment]
Hi, thanks for your hint. I was misunderstanding what I was doing. Setting distDir to correct folder (dist) folder, solved the issue with compilation time. The error sat in front of the screen all the time. :)
