### ISSUE TITLE
Level circles that are not filled need a better colour.

### ISSUE THREAD

**Issue by NullzInc** [tauri-apps/tauri#2556]
The level circles are very hard to visually tell if they are applicable or not. 

Changing the colour of non-applicable circles to an alternative colour like a light grey, or simply removing them altogether if they don't apply, would make this much easier.

![Screenshot from 2021-08-30 08-34-41](https://user-images.githubusercontent.com/19176620/131365158-31d9bea6-cb6e-476f-9996-b16c76a5d905.png)

**Comment by nothingismagick** [comment]
Thanks for the insight, will be resolved when I finally buckle down and revise all those patterns.
