### ISSUE TITLE
Cannot import tauri::api::process::Command

### ISSUE THREAD

**Issue by tdelabro** [tauri-apps/tauri#2565]
I'm trying to use a sidecar binary in a Rust command.
I want to proceed as mention on the doc:
<img width="1020" alt="Screenshot 2021-09-01 at 19 46 05" src="https://user-images.githubusercontent.com/34384633/131719276-c58db846-5c52-454d-9cb3-29406c8282c1.png">

It's also used in this repo examples: https://github.com/tauri-apps/tauri/blob/aecdfaf76fcf0d2820d6ce6eb7590ebe399bfa04/examples/sidecar/src-tauri/src/main.rs#L10-L13

But the `Command` struct is simply not there to be imported.
<img width="440" alt="Screenshot 2021-09-01 at 19 49 48" src="https://user-images.githubusercontent.com/34384633/131719420-fc62ff78-89ee-4aca-8905-1762e4a19fce.png">

Neither while compiling with `yarn tauri dev`:
```
error[E0432]: unresolved import `tauri::api::process::Command`
 --> src/project/import_files.rs:8:5
  |
8 | use tauri::api::process::Command;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `Command` in `api::process`

```

```
timothee@Timothees-MacBook-Pro ~/D/t/unrush (working-files)> yarn tauri info
yarn run v1.22.11
$ /Users/timothee/Documents/tdelabro/unrush/node_modules/.bin/tauri info
 app:spawn Running "/Users/timothee/Documents/tdelabro/unrush/node_modules/@tauri-apps/cli/bin/tauri-cli tauri info" +0ms


Operating System - Mac OS, version 11.3.1 X64

Node.js environment
  Node.js - 16.8.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.21.0
  yarn - 1.22.11

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/node_modules
/src-tauri
/.git
/front

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../front
  devPath - http://localhost:5000

✨  Done in 3.53s.
```

**Comment by FabianLars** [comment]
Do you have `shell.execute` enabled in your tauri.conf.json? For example like this:
```json
"allowlist": {
  "all": false,
  "shell": {
    "all": false,
    "execute": true
  }
},
```

**Comment by tdelabro** [comment]
That was it.
I had understand before that I had to enable module in the allow list in order to use some js api, but I didn't though it was required for rust calls too.
The doc is maybe a bit ambiguous too:
`On the JavaScript code, import the Command class on the shell module and use the sidecar static method:`
vs
`On the Rust code, import the Command struct from the tauri::api::process module:`

There is no more mention to the module.

Thank you for the help !
