### ISSUE TITLE
[docs] Need to document that env var CI=true should be set on Mac for bundling

### ISSUE THREAD

**Issue by jamesej** [tauri-apps/tauri#2567]
I ran into a problem bundling a Tauri app on Mac:
```
+ /usr/bin/osascript /var/folders/wz/d59snkqj349_kclbk14gnnz80000gn/T/createdmg.tmp.XXXXXXXXXX.oQd7STqX lock
/var/folders/wz/d59snkqj349_kclbk14gnnz80000gn/T/createdmg.tmp.XXXXXXXXXX.oQd7STqX:85:89: execution error: An error of type -10826 has occurred. (-10826)
+ echo 'Failed running AppleScript'
Final error is: Shell Scripting Error:error running bundle_dmg.sh
```
@lemarier advised me to set then env variable CI=true and this then worked fine. This should be reflected in the docs somewhere appropriate.

**Comment by facklambda** [comment]
Looks like the OSX bundling documentation guides you to use the GitHub Actions Worfklow: https://tauri.studio/en/docs/guides/bundler/sign-osx

GitHub Actions always sets the env var `CI=true`. https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables 

Depending on how extensively Tauri uses GitHub Actions, bundling for OSX locally may require more masquerading as the GitHub Action default environment.

**Comment by facklambda** [comment]
I'll draft up some clarifications for this document.

**Comment by facklambda** [comment]
Looks like I may have jumped to a conclusion too quickly based on the CI env var:

As per https://github.com/tauri-apps/tauri/issues/592:

https://github.com/tauri-apps/tauri/blob/71ea86a443f2585fa98edd79f2361bd85b380f0c/tooling/bundler/src/bundle/macos/dmg.rs#L124-L130

Setting an env var of `CI=true` prompts `bundle_dmg.sh` to pass the `--skip-jenkins` flag.

Either way setting this env var to true is needed if you're creating bundles locally.

**Comment by facklambda** [comment]
I will update some docs to include references to this env var, and I will additionally try my hand at writing a patch for the MacOS bundler.

**Comment by lucasfernog** [comment]
> Looks like I may have jumped to a conclusion too quickly based on the CI env var:
> 
> As per #592:
> 
> https://github.com/tauri-apps/tauri/blob/71ea86a443f2585fa98edd79f2361bd85b380f0c/tooling/bundler/src/bundle/macos/dmg.rs#L124-L130
> 
> Setting an env var of `CI=true` prompts `bundle_dmg.sh` to pass the `--skip-jenkins` flag.
> 
> Either way setting this env var to true is needed if you're creating bundles locally.

Setting the env var `CI=true` is only needed on machines where you don't have a display, like CI. We enforce that because the DMG bundle script uses AppleScript to prettify the DMG window, and it needs to connect with Finder. See https://github.com/create-dmg/create-dmg/issues/72

**Comment by facklambda** [comment]
I was reading that yesterday and and fallen down a trail with people saying it would crash if the Mac's Photos app wasn't activated. And the workaround was either to run applescript that activated the photos app or to pass the undocumented `--skip-jenkins` flag.

My proposed change may not be relevant.
