### ISSUE TITLE
When the app is full screen, the mouse moves to the top without feedback

### ISSUE THREAD

**Issue by RedTrait** [tauri-apps/tauri#2568]
### **Describe the bug**
When the app is full screen on my mac, the mouse moves to the top without feedback 

### **To Reproduce**
1. Click the full screen button
2. Move the mouse to the top of the screen

### **Expected behavior**

https://user-images.githubusercontent.com/45113206/132062041-6cd76710-18b9-490c-8654-ea82fd8123cf.mov

### **Screenshots**

https://user-images.githubusercontent.com/45113206/132062197-82be8dec-960b-4a4e-909f-7e51beec2eaf.mov

### **Platform and Versions (required):**

```
Operating System - Mac OS, version 10.15.7 X64

Node.js environment
  Node.js - 14.17.3
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.21.1
  yarn - Not installed

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/node_modules
/public
/src-tauri
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../public
  devPath - ../public
```

**Comment by amrbashir** [comment]
related to tauri-apps/tao#188

**Comment by amrbashir** [comment]
fixed in tao's `next` branch and will be available in the next release.
