### ISSUE TITLE
Tauri: From Theory to Practice ebook availability [docs]

### ISSUE THREAD

**Issue by blekman995** [tauri-apps/tauri#2569]
we find it somewhat difficult to get started with docs and example projects. Is the ebook Tauri: From Theory to Practice available now? if not when can we expect. would be very useful to get started for beginners like us.

**Comment by lemarier** [comment]
Hi there,

We do work on the new documentation, better quick start guide and a complete book is being written.

For the book we have no official ETA yet.
The new documentation should be available soon. (tm)
