### ISSUE TITLE
Release builds fail to run in Win 10 (including fresh app)

### ISSUE THREAD

**Issue by will-hart** [tauri-apps/tauri#2570]
### **Describe the bug**

On my windows 10 app, `dev` builds work fine but for `release` builds the application flashes up a white screen for about a second and then disappears. There is no application logging or console output. The event viewer shows

```
Faulting application name: myapp.exe, version: 0.1.0.0, time stamp: 0x6134591e
Faulting module name: myapp.exe, version: 0.1.0.0, time stamp: 0x6134591e
Exception code: 0xc0000005
Fault offset: 0x00000000003b2d27
Faulting process id: 0x4efc
Faulting application start time: 0x01d7a2190a7b8aac
Faulting application path: G:\code\myapp\src-tauri\target\release\myapp.exe
Faulting module path: G:\code\myapp\src-tauri\target\release\myapp.exe
Report Id: 653df468-63af-4801-abee-158935a8da9d
Faulting package full name: 
Faulting package-relative application ID: 
```

### **To Reproduce**

- `yarn tauri build`
- double click `src-tauri/target/release/myapp.exe`

### **Expected behavior**

The app doesn't crash, or displays errors in the console / custom log file.

### **Screenshots**

N/A 

### **Platform and Versions (required):**

```
Operating System - Windows, version 10.0.19043 X64
Webview2 - 93.0.961.38

Node.js environment
  Node.js - 14.15.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.8
  yarn - 1.22.5

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/.git
/.vscode
/build
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://127.0.0.1:3000/
  framework - React
```

### **Additional context**

Dev builds work as expected. Release builds have previously worked. Since the last known good version I've added a menu and some rust event emitting code triggered by menus, but commenting these out doesn't fix the issue. 

I've tried a few other things, without any success:

1. delete `node_modules` and reinstall
2. delete `src_tauri/target` / `cargo clean`
3. restart PC
4. uninstall/reinstall WebView2
5. create a brand new vanilla JS app from `create-tauri-app` 

Similar issues:

- https://github.com/tauri-apps/tauri/issues/2188
- maybe https://github.com/tauri-apps/tauri/issues/1101

I recognise there probably isn't enough info here to debug. Is there anything else I can try to get more info?

### **Stack Trace**

N/A - nothing is logged

**Comment by HarunOr** [comment]
Same issue here. The weird thing is that the executable built with --debug works and shows no errors.
I only get some warnings when I enable verbose logging during build:

`light.exe : warning LGHT1076 : ICE03: String overflow (greater than length permitted in column); Table: Component, Column: Component, Key(s): msvcp140_atomic_wait.dll_system_amd64.DFEFC2FE_EEE6_424C_841B_D4E66F0C84A3`

**Comment by l1xnan** [comment]
I had the same problem, Webview2 revert to an older version (92.0.902.67), problem is solved.

**Comment by lemarier** [comment]
@wusyong probably related to sopium binding

**Comment by HarunOr** [comment]
> I had the same problem, Webview2 revert to an older version (92.0.902.67), problem is solved.

This fixed it for me, thanks!

**Comment by l1xnan** [comment]
Before the issue is fixed, how to lock the webview2 version?

**Comment by winDCz** [comment]
After this weekend ,same issue happened.😂Last Friday all is well

**Comment by monsterboom** [comment]
@l1xnan how to revert to an older version (92.0.902.67)

**Comment by l1xnan** [comment]
@monsterboom Offline installation package:
https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/455fca72-907d-487c-a4bd-e4f76eb91b1a/MicrosoftEdgeWebView2RuntimeInstallerX64.exe

**Comment by monsterboom** [comment]
@l1xnan thx，it is solved in my local . However, i send .msi or app.exe to my enthor windows, had the same problem ...

**Comment by l1xnan** [comment]
@monsterboom It should need to be modified here:

https://github.com/tauri-apps/tauri/blob/9bfdeb42effeeec27aa15bbc5b05040eadfda5ba/tooling/bundler/src/bundle/windows/templates/main.wxs#L216

**Comment by wusyong** [comment]
I couldn't reproduce in wry and webview2 crate but can do it on api examples.
I'll look into it and see which part goes wrong.

Edit: Examples built under tauri workspace work fine. But if it's a individual project, it will crash.

**Comment by wusyong** [comment]
There is some weird null pointer detection on the new version of new webview runtime I guess.
I opened a [PR](https://github.com/sopium/webview2/pull/17) to fix this on upstream crate.
I'll make a soft fork if the crate isn't active.

**Comment by will-hart** [comment]
Fixed for me after the upstream update to `wry`. I ran:

```bash
cd src-tauri
cargo update
```

Thanks for looking into this 😁

**Comment by lemarier** [comment]
A new webview2 binding as been released.

A `cargo update` should fix it as @will-hart said.

Thanks everyone involved in the fix.
