### ISSUE TITLE
Command `tauri dev` fail，fresh app.exe

### ISSUE THREAD

**Issue by monsterboom** [tauri-apps/tauri#2573]
### Describe the bug

Follow the document `Setup for windows` and `Tauri Integration`. All steps have been successful.
But when I run the command `yarn tauri dev`，throw an error：

 **`thread 'main' panicked at 'error while running tauri application: Runtime(CreateWebview(WebView2Error(webview2 error, HRESULT 0x80070002)))', src\main.rs:9:6`** 
error: process didn't exit successfully: `target\debug\app.exe` (exit code: 101)

And the App fresh. (./src-tauri/target/debug/app.exe)

### Platform and Versions (required):

```
Operating System - Windows, version 10.0.19042 X64
Webview2 - 93.0.961.38

Node.js environment
  Node.js - 14.17.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.13
  yarn - 1.22.10

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/.git
/dist
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:8080
  framework - Vue.js (Vue CLI)
  bundler - Webpack
```

**Comment by monsterboom** [comment]
resolved . my edge version is not Compatible with runtime version .

**Comment by lucky2046** [comment]
怎么解决的，我也遇到这个问题了

**Comment by nothingismagick** [comment]
@lucky2046 - Du kannst einfach downgraden oder wenns Dir lieber ist, kommst unser Discord besuchen. Da wirst Du hilfe bekommen.

**Comment by ducklin5** [comment]
https://github.com/tauri-apps/wry/issues/410
