### ISSUE TITLE
Delay when showing dialog

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tauri#2577]
### **Describe the bug**
I'm getting a delay when showing file selection dialogs on macOS. Usually the the delay is around 490ms the first time, and 160ms the second time. It always happens for me, both on the JS and Rust APIs.

### **To Reproduce**
Svelte example:
```svelte
<script>
import { open } from '@tauri-apps/api/dialog'
</script>
<button on:click={open}>Open</button>
```

### **Platform and Versions (required):**
```
Operating System - Mac OS, version 10.15.7 X64

Node.js environment
  Node.js - 14.16.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.11
  yarn - 1.22.10

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/node_modules
/src-tauri
/build
/.git
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:5000
  framework - Svelte
```

**Comment by amrbashir** [comment]
do you still experience this delay ? Also I think that's the normal behavior, can you confirm if any other app have a better dialog startup time ?

**Comment by probablykasper** [comment]
It's slow in other apps too, so you're probably right. Guessing it stuck out to me because I kept testing it over and over. Weird it's that slow tho, maybe there's something bad with my OS.
