### ISSUE TITLE
macOS cursor weirdness

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tauri#2588]
### **Describe the bug**
For some reason, the cursor looks like this when I set `line-height: 50px` on an `<input/>`:
![unknown](https://user-images.githubusercontent.com/11315492/132726452-6c368670-004f-4a7c-9816-9011e86ae52e.png)

On a side-note, I sometimes get this glitchiness with `outline: none` which might be related, but not able to reproduce this consistently:

https://user-images.githubusercontent.com/11315492/132728109-dbb3c31d-e6c7-466e-a011-9a805e94741d.mp4

### **To Reproduce**
Go to https://blueprintjs.com/docs/#datetime/dateinput in Tauri and focus the date input field, and you'll see the same effect

### **Expected behavior**
This is how it looks in Safari and Chrome:
![image](https://user-images.githubusercontent.com/11315492/132726839-30adb680-6a02-4e78-8c16-aff53b537325.png)

### **Platform and Versions:**

<details>
<summary>Details</summary>

```
Operating System - Mac OS, version 10.15.7 X64

Node.js environment
  Node.js - 14.16.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.11
  yarn - 1.22.10

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/node_modules
/src-tauri
/build
/.git
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:5000
  framework - Svelte
```

</details>

**Comment by amrbashir** [comment]
Since we don't control the rendering in the webview. I am going to close this as an upstream issue. Feel free to report it in webkit repo.
