### ISSUE TITLE
Different update channels

### ISSUE THREAD

**Issue by mainrs** [tauri-apps/tauri#2595]
**Is your feature request related to a problem? Please describe.**
In the case that an application has multiple different versions (development and stable) it would be nice to have the ability to change the update url that the app uses.

**Describe the solution you'd like**
I think (for most use-cases) a simple hash that maps from `channel-name` to `url` would be enough. An acompanied API on both sides that returns those names and urls would be great so that the dev/user can select which channel to use for updates. This means that there also needs to be a way to change it during runtime/next start of the application.

**Describe alternatives you've considered**
I don't think that there are really any alternatives. One might be to have releases be taggable als pre-release inside the json update manifest. And that users can select to ignore those or not.

**Comment by FabianLars** [comment]
I could have sworn that we already have an open issue for this, but i can't find it 🤔 
I guess it was just the discord convo: https://discord.com/channels/616186924390023171/731495064508825731/875087928144052276  
Btw, below that it's said that this is a planned feature, so good news! 😅

**Comment by lucasfernog** [comment]
We don't have a built-in solution for this, but you can change the URL right after generating the context:

```rust
fn main() {
  let mut context = tauri::generate_context!();
  let new_updater_url = env!("UPDATER_URL");
  let updater = &mut context.config_mut().tauri.updater;
  let urls = vec![tauri::utils::config::UpdaterEndpoint(
    new_updater_url.parse().expect("invalid updater URL"),
  )];
  updater.endpoints.replace(urls);
```

Then you just need to set the UPDATER_URL env var depending on your build channel.

**Comment by Raicuparta** [comment]
> We don't have a built-in solution for this, but you can change the URL right after generating the context:

How could the same be accomplished in Tauri 2? I think since the updater is a separate plugin, it's no longer as easy to access from the context. From digging around, it seems to be somewhat accessible as raw json via `context.config)mut.plugins`, but that's less than ideal, and I'm not even sure if it would work.

**Comment by FabianLars** [comment]
@Raicuparta there are rust apis to set the endpoints now, for example https://docs.rs/tauri-plugin-updater/2.0.0-beta.8/tauri_plugin_updater/struct.UpdaterBuilder.html#method.endpoints
