### ISSUE TITLE
Expose platform-dependant window handle

### ISSUE THREAD

**Issue by mainrs** [tauri-apps/tauri#2597]
**Is your feature request related to a problem? Please describe.**
Windows provides an extension layer for their `File Explorer` so that applications can register components that provide previews of the files that they can work with. For example most image editors have one installed, showing all visible layers of the image at once in the `File Explorer` (as the file's preview image).

These work by having an application pass them a handle to the window to render to as well as the coordinates and size of the rectangle to render into.

Tauri apps that might want to take advantage of that already existing feature do not have a way to do so currently.

**Describe the solution you'd like**
Maybe a field or method (could even be unsafe if needed) that provides the raw window handle. Commands can already receive a `Window` instance. So it makes sense to have that field be part of that struct.

**Describe alternatives you've considered**
It should be possible to retrieve the handle on most platforms by calling into native APIs and relying on window titles for example. This is suboptimal though.

**Additional context**
`Wry` already has to know the handle of a window IIRC, so it shouldn't be much of a problem to expose it.

**Comment by FabianLars** [comment]
We have:
window.hwnd() for windows
window.ns_window() for mac
window.gtk_window() for linux
-> https://github.com/tauri-apps/tauri/blob/dev/core/tauri/src/window.rs#L503-L545

Do you mean this or something else?

**Comment by mainrs** [comment]
Ah, I didn't see them, thanks!
