### ISSUE TITLE
Javascript API types incorrect when reading physical size

### ISSUE THREAD

**Issue by TomzBench** [tauri-apps/tauri#2599]
When using the Tauri API in typescript, the intellisense is not correct, (and therefore the typescript declarations are wrong?)  Specifically the API I notice this issue is when reading the physical size.

```typescript
const size = await api.window.appWindow.innerSize(); // { height: yyy, width: xxx}
size.toLogical(...); // <--- [Error] toLogical does not exist on size
```

My guess is that when sending the rust props over to javascript, the prototypes or methods are lost and only the values are passed. However the typescript typings are assuming you have a constructed object.

**Comment by amrbashir** [comment]
`toLogical` doesn't communicate with rust at all, what is the type of `size`

**Comment by TomzBench** [comment]
> `toLogical` doesn't communicate with rust at all, what is the type of `size`

The actual type returned by `innerSize()` is a plain object with keys `height` and `width`. However, typescript thinks the object returned from `innerSize()` is a`PhysicalSize` object which is a class with methods that has  a`toLogical` method. So i think the mapping between Tauri backend and the javascript frontend types is off.

**Comment by amrbashir** [comment]
if typescript thinks the object is `PhysicalSize` and it has `toLogical()` method, then I see no problem as this is the intended behavior.

Tauri's backend and Rust has no role in this as `toLogical()` is purely executed in js only.

**Comment by FabianLars** [comment]
No, the problem is, the function is defined as `async innerPosition(): Promise<PhysicalPosition>`, but instead of an instance of the PhysicalSize class ([window.ts#L116-130](https://github.com/tauri-apps/tauri/blob/dev/tooling/api/src/window.ts#L116-L130)) it returns a plain `{width: a, height: b}`

**Comment by TomzBench** [comment]
> if typescript thinks the object is `PhysicalSize` and it has `toLogical()` method, then I see no problem as this is the intended behavior.
> 
> Tauri's backend and Rust has no role in this as `toLogical()` is purely executed in js only.

The return type is wrong in the javascript function.  You can either make the javascript create a new instance of a PhysicalSize and return this. Or change the return type.

**Comment by amrbashir** [comment]
Ah yes, I see the problem now, we are indeed just returning a plain object instead of an instance of a class.

Should've read your words more carefully, apologies.

**Comment by sirgallifrey** [comment]
If there isn't anyone already working on it, I'll give it a shot as my first contribution

**Comment by lemarier** [comment]
> If there isn't anyone already working on it, I'll give it a shot as my first contribution

It's all yours! Do not hesitate if you have any questions! You can reach us on discord as well.
