### ISSUE TITLE
__TAURI_INVOKE_KEY__ injection breaks code splitting

### ISSUE THREAD

**Issue by victorhqc** [tauri-apps/tauri#2603]
### **Describe the bug**

Chunks generated by Webpack fail to execute due to the injection of

```ts
const __TAURI_INVOKE_KEY__ = 12345;
```

A project built with

### **To Reproduce**
https://github.com/victorhqc/tauri-split-error

### **Expected behavior**
Production build works with code splitting

### **Screenshots**
![Screenshot 2021-09-14 123409](https://user-images.githubusercontent.com/726113/133250352-c85330f0-9684-4780-bc1e-36ce3fc880e9.png)

### **Platform and Versions (required):**

```

Operating System - Windows, version 10.0.19043 X64
Webview2 - 93.0.961.47

Node.js environment
  Node.js - 14.16.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.12
  yarn - Not installed

Rust environment
  rustc - 1.55.0
  cargo - 1.55.0

App directory structure
/.git
/build
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:3000
  framework - React
  bundler - Webpack
```

**Comment by victorhqc** [comment]
**Update:** To fix, simply enable minification:

`webpack.config.js`
```js
{
  optimization: {
    minimize: true
  }
}
```

**Comment by FabianLars** [comment]
Just to clear things up a little bit, webpack 5 added comments to the file, some of them containing module keywords which triggered tauri to think that the file is a es6 module.
Therefore it didn't wrap the file in an IIFE which messed up the scope of the const variable.
