### ISSUE TITLE
Tauri with Rust Application Backend

### ISSUE THREAD

**Issue by theduke** [tauri-apps/tauri#2605]
It's unclear to me how Tauri should be used with the application logic driven by Rust code instead of Javascript running in node.

As in, I would want to:

* Not have a node dependency
* Write a Rust binary that has all the application logic
* A message channel so the UI can communicate with Rust code
* still take advantage of the nice packaging tooling

Is this currently possible or just not documented?
Otherwise, is it planned?

**Comment by FabianLars** [comment]
Well except for the channel API, which doesn't exist yet, this is basically the best practice for tauri apps. (-> js only for the UI and everything else in rust)

You'd do this via commands and events, see https://tauri.studio/en/docs/guides/command and https://tauri.studio/en/docs/guides/events for a start, also take a look at the repo examples.

Node isn't bundled in tauri by default (you'd have to explicitly sidecar it), so you don't have to do something extra to get rid of it.

**Comment by theduke** [comment]
Ah, good to hear, perfect. 

And sorry for the noise...
