### ISSUE TITLE
Windows WebView2 Error (after closing a window)

### ISSUE THREAD

**Issue by brsmsg** [tauri-apps/tauri#2607]
### **Describe the bug**
On the release version of our app (on Windows 10 with the latest Webview2 Runtime version), every time a new window is opened and then closed, our app has no response and turns to a white screen.

the window is created through : `new WebviewWindow()`

I've checked https://github.com/tauri-apps/tauri/issues/2570 and reverted webview2 to an old version https://github.com/tauri-apps/tauri/issues/2570#issuecomment-913466578 , the problem got solved. However, I noticed that you guys have released a new webview2 binding and I updated Tauri, the problem still exists.

### **To Reproduce**
1. `pnpm build` 
2. run the generated .msi file and install the app on Windows.
4. call `new WebviewWindow()` to create a new window and then close it.

### **Expected behavior**
The app can respond, or display errors in the console/custom log file.

### **Screenshots**
I tried `tauri build -d`, the terminal shows
![image](https://user-images.githubusercontent.com/45126366/133414540-b57b8901-b135-4e0c-8f33-8542477b535d.png)

### **Platform and Versions (required):**

```
Operating System - Windows version 10.0.18363.535  X64

Node.js environment
Node.js - 14.16.0
@tauri-apps/cli - 1.0.0-beta.10
@tauri-apps/api - 1.0.0-beta.8

Global packages
npm - 6.14.11
pnpm - 6.0.2

Rust environment
rustc - 1.54.0
cargo - 1.54.0

App directory structure
/.git
/.vscode
/dist
/node_modules
/public
/release
/src
/src-tauri

App
tauri.rs - 1.0.0-beta.8
build-type - bundle
CSP - default-src blob: data: filesystem: ws: wss: asset: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
distDir - ../dist
```

**Comment by myWsq** [comment]
Same error

**Comment by amrbashir** [comment]
I can't replicate this error on `next` branch, please reopen this issue if the issue persists in the next release.

**Comment by Dan86de** [comment]
Same here for me.
