### ISSUE TITLE
`--target` option for cli is not optional

### ISSUE THREAD

**Issue by jgeluk** [tauri-apps/tauri#2611]
### **Describe the bug**
`tauri build` without the `--target` option fails when it tries to rename the generated binary to
the specified product name because it assumes the wrong release directory (missing target path):

```
Error: failed to rename `<project-dir>/src-tauri/target/debug/<tauri cargo toml name>` to `<project-dir>/src-tauri/target/debug/<product name>`

Caused by:
    No such file or directory (os error 2)
```

When `--target <target>` is specified, it correctly finds the binary in `./src-tauri/target/<target>/debug` 

### **Platform and Versions (required):**

```
Operating System - Mac OS, version 11.5.2 X64

Node.js environment
  Node.js - 16.9.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - Not installed

Global packages
  npm - 7.21.1
  yarn - 1.22.11

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/dist
/.cargo
/src-tauri
/assets
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:8080
```

### **Stack Trace**

Btw I ran the cli from the `dev` branch of a local git clone of the tauri repo but the same error also appears with the latest stable or beta releases.

**Comment by lucasfernog** [comment]
I tried the CLI from dev, next and the published one and couldn't reproduce it. Please reopen if you can provide more details like the output folder structure or whether the actual binary exists on that path or not.
