### ISSUE TITLE
`cargo install tauri-cli` does not work on windows runner on Github Actions

### ISSUE THREAD

**Issue by jgeluk** [tauri-apps/tauri#2612]
### **Describe the bug**

In a Github Actions workflow running on `windows-latest` having a step like this fails:

```
      - name: Install Rust Dependencies & Tools
        run: |
          cargo install trunk wasm-bindgen-cli tauri-cli
```

Error:

```
error: could not find `tauri-cli` in registry `crates-io` with version `*`
     Summary Successfully installed trunk, wasm-bindgen-cli! Failed to install tauri-cli (see error(s) above).
```

### **Expected behavior**
Should work, only workaround seems to be to run Tauri via `npm` but that would require a whole different Github Actions workflow than you would use for `macos-latest` and `ubuntu-latest` (where `npm` or `node` is not required at all).

### **Platform and Versions (required):**
N/A

**Comment by FabianLars** [comment]
you need to explicitley specify the version, because cargo kinda ignores beta versions otherwise (that's not a gh action specific thing): `cargo install tauri-cli --version 1.0.0-beta.7`

**Comment by jgeluk** [comment]
What if you don't want to install a beta version? Or is there no non-beta version out there yet?

**Comment by FabianLars** [comment]
There are only beta versions https://crates.io/crates/tauri-cli/versions .
Kinda like rest of tauri. (Well technically the other stuff has non beta versions but they aren't really usable anymore, cause they represented tauris alpha stage)
