### ISSUE TITLE
[MacOs] Tauri app crashes on MacOs v10.12.6: `Library missing: image not found`

### ISSUE THREAD

**Issue by guillemcordoba** [tauri-apps/tauri#2617]
### **Describe the bug**

Tauri app crashes on MacOs v10.12.6 with this error:

![image](https://user-images.githubusercontent.com/2046932/134013998-929d5099-a997-4579-9d20-20fefd88cca6.png)

### **To Reproduce**
1. Build a Tauri app targeting MacOs.
2. Execute it in a MacOs  v10.12.6.

### **Expected behavior**
The application should not crash and work properly

### Environment

This is the output of `tauri info`:

```


Operating System - Mac OS, version 10.15.7 X64

Node.js environment
  Node.js - 12.22.6
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.6

Global packages
  npm - 6.14.15
  yarn - 1.22.5

Rust environment
  rustc - 1.55.0
  cargo - 1.55.0

App directory structure
/node_modules
/tests
/public
/scripts
/.github
/src-tauri
/.git
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - target/webpack_dist
  devPath - target/webpack_dist
  framework - Vue.js (Vue CLI)
  bundler - Webpack

```

**Comment by nothingismagick** [comment]
Please supply the results of your `tauri info` command on the build machine.

**Comment by guillemcordoba** [comment]
@nothingismagick updated the issue.

**Comment by nothingismagick** [comment]
Cheers, for sure your CSP is wrong, it looks like this is an old project. Today we need to add `tauri:` to the mix.
```
  CSP - default-src blob: data: filesystem: ws: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
```

But I am not sure this is really the problem, your API is also our of date (should be beta.8). Did you change the icons?

**Comment by guillemcordoba** [comment]
Oh okey thanks...

Not sure what you mean exactly about the icons... I created them using `tauri icon`, is that what you mean?

**Comment by lucasfernog** [comment]
We won't support macOS 10.12. By default the minimum supported macOS version is 10.15, though we tested it on 10.13 and it works (but it's not recommended since it doesn't have security patches anymore).
