### ISSUE TITLE
List Partitions and HardDrives in fs/path

### ISSUE THREAD

**Issue by AnupamKris** [tauri-apps/tauri#2642]
Hi, I am trying to get the available Partitions in my hardrive in vue.. I am using the cli plugin and everything works as expected.. But I can figure out how to get all Avaiable Partitions or Drive letters.

**Comment by FabianLars** [comment]
There is no built-in way to do that and i'm not sure if this will be integrated tbh (for what it's worth, node doesn't provide this either iirc).
But anyway, for the time being you could use the [sysinfo](https://crates.io/crates/sysinfo) crate for example, if you know rust.
Or you could spawn [child processes](https://tauri.studio/en/docs/api/js/classes/shell.Command) and use OS commands, for example `wmic logicaldisk get name` on Windows.

**Comment by amrbashir** [comment]
This is won't be integrated in Tauri's api, because it is only specific to Windows so you should implement it on your own. 

@FabianLars suggestions are a good way to start about this prpblem.
