### ISSUE TITLE
[docs] libappindicator3-dev not available in Bullseye

### ISSUE THREAD

**Issue by michaelmcandrew** [tauri-apps/tauri#2647]
Hey there,

https://tauri.studio/en/docs/get-started/setup-linux#1-system-dependencies suggests that libappindicator3-dev is a dependency on Debian but that package isn't available in Debian Bullseye.

**Comment by lucasfernog** [comment]
Maybe we should expose https://github.com/tauri-apps/tao/blob/9da2f1592dd32000e2612a688385c3141dce01ff/Cargo.toml#L31 what do you think @lemarier @wusyong

**Comment by wusyong** [comment]
Oh no! I didn't expect this day to come so soon.
Yes we should expose it. But I haven't tested it for a while.

**Comment by volgar1x** [comment]
Is there a workaround in the mean time, please?

**Comment by FabianLars** [comment]
@volgar1x As a workaround you can enable the buster repos in sources.list to get access to libappindicator3-dev (i'm not a debian user so please ask a search engine of your choice for guidance 🙏)

**Comment by snowfluke** [comment]
This fixed me in debian 11, thank you

1. Add debian 10 (buster) repository to sources list

`sudo nano /etc/apt/sources.list`

2. Add this line

`deb http://deb.debian.org/debian buster main contrib non-free`

3. Run

`sudo apt-get update && apt-get install libappindicator3-dev`
`sudo apt --fix-broken install`

**Comment by lucasfernog** [comment]
We support libayatana-appindicator now. Just install it and Tauri will use it automatically.
