### ISSUE TITLE
create-tauri-app creates not working tauri.conf.json with the svelte template

### ISSUE THREAD

**Issue by bckmnn** [tauri-apps/tauri#2658]
### **Describe the bug**
Using `npx create-tauri-app` creates a not working project when used with the svelte option.

### **To Reproduce**
1. Run 'npx create-tauri-app' and choose `svelte` as js framework.
2. Run 'npm install' 
4. Run 'npm run tauri dev'
4. See error in console:
```
> tauri "dev"

 app:spawn Running "D:\bckmnn\Documents\repos\image-show\image-show\nod +0ms

[tauri:dev] Running `npm dev`
    Updating crates.io index
Unknown command: "dev"

Did you mean this?
    npm run dev # run the "dev" package script****
``` 
5. app will build and launch but will not load the html page.

This is due to the follwoing lines in `src-tauri/tauri.conf.json`: 
```
  ...
  "build": {
    "beforeDevCommand": "npm dev",
    "beforeBuildCommand": "npm build"
  },
  ...
```

### **Expected behavior**
I think `src-tauri/tauri.conf.json` should be including **run** in the `beforeDevCommand` and `beforeBuildCommand`:
```
  ...
  "build": {
    "beforeDevCommand": "npm run dev",
    "beforeBuildCommand": "npm run build"
  },
  ...
```

### **Platform and Versions (required):**

```
Operating System - Windows, version 10.0.19042 X64
Webview2 - 94.0.992.31

Node.js environment
  Node.js - 16.8.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.21.1
  yarn - Not installed

Rust environment
  rustc - 1.55.0
  cargo - 1.55.0

App directory structure
/node_modules
/public
/scripts
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../public
  devPath - http://localhost:5000
  framework - Svelte
  bundler - Rollup
```

### **Additional context**
I also tried that on mac os, same issue there.

I had a look at the source code, and i am pretty sure the issue is in [tooling/create-tauri-app/src/recipes/svelte.ts](https://github.com/tauri-apps/tauri/blob/48f3768c41a2c68e2e097fcc1ef50e549c1dfb78/tooling/create-tauri-app/src/recipes/svelte.ts#L34). It seems to check only for *yarn* and not for *npm* like in line 63. 

Since I am not using *yarn* i am not sure if maybe the condition is just backwards, or if *npm* needs to be added.

**Comment by amrbashir** [comment]
This has been fixed and will be available in the next release.
