### ISSUE TITLE
[docs] The meaning of window setSize

### ISSUE THREAD

**Issue by seasonyuu** [tauri-apps/tauri#2660]
I'm trying to change window width by TypeScript. But there is a few docs about these case. I have some question.

* what type is `setSize`  using? inner or outter?
* why I have to do `height - 20` if I don't want to change window height? Is it title bar height? How can I get the height value of title bar?

```typescript
      const size = await appWindow.innerSize();
      console.log('innerSize', await appWindow.innerSize());
      console.log('outerSize', await appWindow.outerSize());
      const newSize = new window.PhysicalSize(size.width + 200, size.height - 20);
      await appWindow.setSize(newSize);
      console.log('innerSize', await appWindow.innerSize());
      console.log('outerSize', await appWindow.outerSize());
```

**Comment by FabianLars** [comment]
> what type is setSize using? inner or outter?

inner size

> why I have to do height - 20

That's a bug, see https://github.com/tauri-apps/tao/issues/194
Also it's not always 20px, iirc it changes with the dpi. On default dpi it seems to be the same size as the missing menubar.

**Comment by seasonyuu** [comment]
> > what type is setSize using? inner or outter?
> 
> inner size
> 
> > why I have to do height - 20
> 
> That's a bug, see [tauri-apps/tao#194](https://github.com/tauri-apps/tao/issues/194)
> Also it's not always 20px, iirc it changes with the dpi. On default dpi it seems to be the same size as the missing menubar.

Ok I got it. Do you know is there any fix plan or workaround?
