### ISSUE TITLE
[docs] How to use web workers?

### ISSUE THREAD

**Issue by jotyy** [tauri-apps/tauri#2671]
When I migrating my electorn app to tauri, I got this error on my worker thread.

```ReferenceError: Buffer is not defined```

I want to know how to make my worker running or if there has some other multi-thread implementation in tauri?

ps: specific configuration in electorn is `nodeIntegrationInWorker`.

**Comment by lucasfernog** [comment]
`Buffer is not defined` seems like you ended up using some Node.js API on the service worker. We don't have node integration.
