### ISSUE TITLE
I find the error when I am trying to build the client  apk on linux environment, how to solve it ?

### ISSUE THREAD

**Issue by chengzeyuan** [tauri-apps/tauri#2672]
**I had installed the  llvm and clang ,but still get the error after running command "cargo xtask build-client --oculus-quest"**

error: failed to run custom build command for `alvr_client v16.0.0-rc2 (/home/yvr/workspace/ALVR/alvr/client)`

Caused by:
  process didn't exit successfully: `/home/yvr/workspace/ALVR/target/release/build/alvr_client-a6329f581eed6d56/build-script-build` (exit status: 101)
  --- stdout
  product_name =######################################### YVR_SDK
  TARGET = Some("aarch64-linux-android")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-unknown-linux-gnu")
  CXX_aarch64-linux-android = Some("/home/yvr/workspace/sdk/android-sdk-linux/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang++")
  CXXFLAGS_aarch64-linux-android = None
  CXXFLAGS_aarch64_linux_android = None
  TARGET_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
.
.
.
 --- stderr
  thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at /usr/local/llvm/lib/libclang.so.12 could not be opened: libtinfo.so.6: cannot open shared object file: No such file or directory"', /home/yvr/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.1/src/lib.rs:2117:31
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
     1: core::panicking::panic_fmt
               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
     2: core::result::unwrap_failed
               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
     3: core::result::Result<T,E>::expect
     4: core::ops::function::FnOnce::call_once
     5: lazy_static::lazy::Lazy<T>::get::{{closure}}
     6: std::sync::once::Once::call_once::{{closure}}
     7: std::sync::once::Once::call_inner
               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sync/once.rs:418:21
     8: std::sync::once::Once::call_once
     9: <bindgen::ensure_libclang_is_loaded::LIBCLANG as core::ops::deref::Deref>::deref
    10: bindgen::ensure_libclang_is_loaded
    11: bindgen::Bindings::generate
    12: bindgen::Builder::generate
    13: build_script_build::main
    14: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
warning: `alvr_session` (lib) generated 1 warning
error: build failed

**Comment by amrbashir** [comment]
Is this a tauri app ? it doesn't seem so also are you trying to build apk for android ?

**Comment by chengzeyuan** [comment]
> Is this a tauri app ? it doesn't seem so also are you trying to build apk for android ?

I'm sorry I mentioned the wrong place，I’ll close it .
