### ISSUE TITLE
`symbol lookup error` with the `.AppImage` on Ubuntu 19.04

### ISSUE THREAD

**Issue by guillemcordoba** [tauri-apps/tauri#2689]
### **Describe the bug**

When executing the `.AppImage` compiled with Tauri on an Ubuntu 19.40, I get this error:

```
guillem@guillem:~/Baixades$ ./holochain-launcher_0.3.2_amd64.AppImage 
Gtk-Message: 00:03:55.561: Failed to load module "canberra-gtk-module"
Gtk-Message: 00:03:55.567: Failed to load module "canberra-gtk-module"
  /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: undefined symbol: NetworkProcessMainUnix
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: undefined symbol: WebProcessMainUnix
```

And I get a blank window.

Error doesn't show up if I use a `.deb` package, so I assume it's related to the bundling process.

### **To Reproduce**
1. Create a Tauri app.
2. Compile it inside an Ubuntu 18.04.
3. Try to execute the `.AppImage` in an Ubuntu 19.04.

### **Expected behavior**

The error doesn't happen.

### **Screenshots**
![Captura de pantalla de 2021-09-30 00-11-01](https://user-images.githubusercontent.com/2046932/135355773-fea9d323-1fe3-481d-94a9-f24a0b5578d1.png)

### Tauri info
```


Operating System - Ubuntu, version 18.04 X64

Node.js environment
  Node.js - 12.22.6
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.15
  yarn - 1.22.11

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/public
/tests
/.git
/.github
/node_modules
/src-tauri
/src
/scripts

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - target/webpack_dist
  devPath - target/webpack_dist
  framework - Vue.js (Vue CLI)
  bundler - Webpack
```

**Comment by nothingismagick** [comment]
Just for clarity sake, can you please share the data provided by `tauri info`

**Comment by guillemcordoba** [comment]
Yes yes sorry, was unclear if they were needed here, I updated the issue.

**Comment by amrbashir** [comment]
try this solution https://askubuntu.com/a/872397

**Comment by nothingismagick** [comment]
also, as an FYI - your rust is out of date. (pretty sure its not the problem here though)

```
> rustc --version
rust version 1.55.0 (c8dfcfe04 2021-09-06)
```

just run `rustup update`

**Comment by guillemcordoba** [comment]
Well I can't yet, there is a problem with some dependencies of the `holochain` crate that make it not compile in 1.55. But I have that noted down. @amrbashir I'll try it, thanks :D

**Comment by guillemcordoba** [comment]
@amrbashir doesn't solve the problem, although the initial warnings are not present anymore. Now what I get is:

```
guillem@guillem:~/Baixades$ ./holochain-launcher_0.3.3_amd64.AppImage 
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess: undefined symbol: NetworkProcessMainUnix
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: symbol lookup error: /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess: undefined symbol: WebProcessMainUnix
```

**Comment by evbo** [comment]
I had the exact same error message as OP, but interestingly I received that error when building in a `Centos 7.3.1611` docker image and deploying to the same OS version (not a container though).

This PR did fix it for me though (thanks @FabianLars !):
https://github.com/tauri-apps/tauri/pull/2940

**Comment by thewh1teagle** [comment]
I experience the same error `cargo tauri dev`. when using the compiled appImage it works.
