### ISSUE TITLE
Tray icon empty on windows 10

### ISSUE THREAD

**Issue by kubijo** [tauri-apps/tauri#2692]
### **Describe the bug**
The windows build of my app does have a tray entry, and its menu items seem to work, but there is no icon, only an invisible rectangle.

I've made built the icons resources through you `icon` command, so as far as I know, I am fulfilling the requirements outlined in the docs (that is that there needs to exist an `*ico` file)

Also note the screenshot showing that desktop & title-bar icons work fine & try icon works too in linux

### **To Reproduce**
I'd give more info if I'd know what would help, but at this point I haven't got a clue, but will cooperate if you have an idea what I should try & report back.
I did try a debug built that gave a console window in addition to the app window, but nothing happened there.

### **Expected behaviour**
The tray icon should be visible

### **Screenshots**
![empty-tray](https://user-images.githubusercontent.com/11244314/135467823-be5b7872-c0e2-47cc-ae5e-d77b81aafcf6.png)
![desktop-and-titlebar-icons-fine](https://user-images.githubusercontent.com/11244314/135468229-919203bb-21e6-4a91-9f3e-64b4531b7821.png)

### **Platform and Versions (required):**
```
Operating System - Windows, version 10.0.19043 X64
Webview2 - 94.0.992.31

Node.js environment
  Node.js - 14.17.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.13
  yarn - 1.22.11

Rust environment
  rustc - 1.57.0-nightly
  cargo - 1.57.0-nightly

App directory structure
/src-tauri
/.yarn
/node_modules

App
  tauri.rs - 1.0.0-beta.5
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
```

### **Additional context**
**tauri.conf**
```json
{
  "package": {
    "productName": "Braiins OS Toolbox",
    "version": "0.1.0"
  },
  "build": {
    "distDir": "../../../web-ui/build/js/bundle/toolbox-tauri",
    "devPath": "http://localhost:3001",
    "withGlobalTauri": false
  },
  "tauri": {
    "bundle": {
      "active": true,
      "targets": "all",
      "identifier": "com.tauri.dev",
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "resources": [],
      "externalBin": [],
      "copyright": "",
      "category": "Utility",
      "shortDescription": "",
      "longDescription": "",
      "deb": {
        "depends": [],
        "useBootstrapper": false
      },
      "macOS": {
        "frameworks": [],
        "minimumSystemVersion": "",
        "useBootstrapper": false,
        "exceptionDomain": "",
        "signingIdentity": null,
        "entitlements": null
      },
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "updater": {
      "active": false
    },
    "systemTray": {
      "iconPath": "icons/icon.png",
      "iconAsTemplate": false
    },
    "allowlist": {
      "all": true,
      "notification": {
        "all": true
      }
    },
    "windows": [
      {
        "title": "Braiins OS Toolbox",
        "resizable": true,
        "fullscreen": false
      }
    ],
    "security": {
      "csp": "default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'"
    }
  }
}

```

### **Stack Trace**
None seen anywhere

**Comment by FabianLars** [comment]
Is this still an issue if you upgrade to tauri.rs - beta.8 or the next branch?

**Comment by kubijo** [comment]
Yep, just tried it with a release build (no `--debug` flag) on `next`.

----------------------------
Also, as a sidenote: notifications still have the `Windows Powershell` title…

**Comment by FabianLars** [comment]
> Yep, just tried it with a release build (no --debug flag) on next.

hmm, imo it looks like something specific to your icon tbh. (the `tauri icon` command is a little unfriendly at times :/ )
Can you try other icons/image editors/export methods? No idea otherwise, sorry.

> Also, as a sidenote: notifications still have the Windows Powershell title…

Whoops my bad. Looks like it's tied to the msi installation (So if you distribute your app via the msi, it should be fine)

**Comment by kubijo** [comment]
> hmm, imo it looks like something specific to your icon tbh. (the tauri icon command is a little unfriendly at times :/ )
Can you try other icons/image editors/export methods? No idea otherwise, sorry.

OK, I'll try a random different file. It is pretty strange though that it works in every other place except this one.

> Whoops my bad. Looks like it's tied to the msi installation (So if you distribute your app via the msi, it should be fine)

I see, it indeed is, and it also has an icon of the app

**Comment by kubijo** [comment]
So, I've tried
- a different PNG, converted it by the `tauri icon` tool & got the same thing ... it worked everywhere except try area
- downloaded a random `ico` file from the internet and replaced the generated one, and now it works in the tray area too (albeit a bit rough around the edges, but that is not the point for now)

-------------------------------------

- `ico` is from here: https://findicons.com/icon/64873/download
- this is the second `png` I've tried: [icon](https://user-images.githubusercontent.com/11244314/135503247-bd024cd9-5e17-42aa-b20f-7158ec216697.png)

-------------------------------------

Now, as far as I can tell just by hindsight, the difference seems to be that the `ico` you are generating is compressed.
Might that be the core of the problem?

**Comment by kubijo** [comment]
I have just tried both compression algorithms you declare as supported and the result is the same.

Can the compression be disabled and left to users to [`pngcrush`](https://en.wikipedia.org/wiki/Pngcrush) the `png` images?

**Comment by lucasfernog** [comment]
I tested a lot of PNG->ICO libraries and methods (one online conversion site worked, one didn't) and png2icons is definitely not working so well here. I tried https://github.com/steambap/png-to-ico and it works nice, so I made a PR to use that instead.

Can you test that @kubijo ?

**Comment by kubijo** [comment]
Sure thing, first thing in the morning... What do I do? `cargo update`, build and see?

**Comment by lucasfernog** [comment]
You'll need to clone the repo, build the tooling/CLI.js package and run the icon command from it.

**Comment by kubijo** [comment]
Sorry for the delay… slow day both for me and for the computer it seems…

Anyway, the update seems to have worked nicely! :+1: 
![image](https://user-images.githubusercontent.com/11244314/135607267-63fa8b37-4207-4d31-b214-dd11a11c3a91.png)

------------------------------------------

If this was an application to be deployed, my next effort in this regard would be to solve the icon quality in these small dimensions.

It is tangential to this issue, but it would be interesting to known if you plan to address that in some way as well, or if that is to be solved by users themselves.

The only way to solve this I see would be to generate an `ico` file with hand-designed sizes because scaling can only do so much…

**Comment by kubijo** [comment]
It seems that this might also be accomplished by `ImageMagick` (available cross-platform): https://superuser.com/a/683203

**Comment by lucasfernog** [comment]
I think I can skip resizing if the image is squared. Otherwise there's not much to do.

**Comment by kubijo** [comment]
That is not the whole story though ... the point is to have an `ico` file with multiple sizes where potentially any of them can be custom designed because you can't use a design for 256×256 scaled down 16×16 and expect it to look nice

**Comment by kubijo** [comment]
It would, however, be understandable if this was considered out of the scope for that script since there is potentially a lot of complexity that you might not want to tackle...

… so I'm basically just saying that this is an issue that needs to be addressed in one way or another if Tauri user wants nice looking windows icons & it's a question if you want to address that in your tooling and/or documentation
