### ISSUE TITLE
feat: menu item get title

### ISSUE THREAD

**Issue by jbolda** [tauri-apps/tauri#2696]
**Describe the solution you'd like**

In the tray, the tray_handle.get_item() would be great to have the title (as well as the id). It would be nice to have it for a "light state" like Show/Hide buttons.

**Comment by amrbashir** [comment]
@tauri-bot upstream tao

**Comment by amrbashir** [comment]
@tauri-bot upstream tao

**Comment by amrbashir** [comment]
@tauri-bot upstream tao

**Comment by amrbashir** [comment]
@tauri-bot upstream tao

**Comment by amrbashir** [comment]
@tauri-bot upstream tao

**Comment by amrbashir** [comment]
@tauri-bot upstream tao

**Comment by amrbashir** [comment]
@tauri-bot upstream tao

**Comment by amrbashir** [comment]
@tauri-bot upstream tao

**Comment by keiya01** [comment]
Could I resolve this issue by using implemented features in Tao?

**Comment by lucasfernog** [comment]
@keiya01 yeah but in the current plan it'll only be available in v2.

**Comment by elibroftw** [comment]
How do you do this in v2?
