### ISSUE TITLE
"windows" not "win32" for Windows in os.platform() possible values

### ISSUE THREAD

**Issue by boan-anbo** [tauri-apps/tauri#2698]
It's `windows` not `win32` as in the doc.

https://github.com/tauri-apps/tauri/blob/40d08a60fe44fda034a2d3f014fad7cd7a18df1c/tooling/api/src/os.ts#L38

**Comment by amrbashir** [comment]
Thanks for catching this, PR'd a fix now, it will return win32 as stated in the docs.
