### ISSUE TITLE
Notification Permission Error Crash

### ISSUE THREAD

**Issue by lynxionxs** [tauri-apps/tauri#2712]
When asking for notification permission, 
Error is: "Gtk-Message: 19:55:22.642: GtkDialog mapped without a transient parent. This is discouraged"
Then app freezes. Have to force Quit. 
When restart the app it crashes immediately.

```javascript
window.Notification.requestPermission().then((status) => {
    console.log(status); 
});

/*
// tauri.conf.json
"build": {
    "withGlobalTauri": true
 }

"allowlist": {
    "notification": {
      "all": true
    }
}
*/
```
**ERRORS:**
Gtk-Message: 19:55:22.642: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 20:01:05.826: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 20:02:08.820: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 20:02:26.537: GtkDialog mapped without a transient parent. This is discouraged.

```
Operating System - Ubuntu, version 18.04 X64

Node.js environment
  Node.js - 15.14.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.7.6
  yarn - 1.22.5

Rust environment
  rustc - 1.55.0
  cargo - 1.55.0

App directory structure
/node_modules
/src-tauri
/dist
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:4500

```

**Comment by mzy2240** [comment]
requestPermission also crashes in Windows. Verified with all latest tauri components.

**Comment by FabianLars** [comment]
@mzy2240 the crashes on Windows should be fixed on the `next` branch iirc

**Comment by aimerib** [comment]
I can confirm that the `next` branch also fixes this issue for gtk.

**Comment by amrbashir** [comment]
Alright, I will close this but feel free to reopen if it still happens when the next version is released.

**Comment by uwohlfeil** [comment]
I can reproduce this problem on Manjaro (KDE).
I'm not sure if I'm already on `next` branch. If not, how can I switch to `next` via Cargo?

### HTML Code:
```html
<!DOCTYPE html>
<html>
  <body>
    <button onclick="notifyMe()">Notify me!</button>
  </body>

  <script>
    function notifyMe() {
      Notification.requestPermission(function (permission) {
        console.log(Notification.permission);
        if (permission === "granted") {
          var notification = new Notification("Hi there!");
        }
      });
    }
  </script>
</html>
```
### Tauri Info:
```
Operating System - Manjaro, version 21.2.2 X64

Node.js environment
  Node.js - 17.3.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.3.1
  yarn - 1.22.17

Rust environment
  rustc - 1.58.0
  cargo - 1.58.0

App directory structure
/src-tauri
/node_modules
/dist

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - ../dist
```
### Versions

* gtk2 2.24.33-2
* gtk3 1:3.24.31-1

**Comment by amrbashir** [comment]
@uwohlfeil 
1. change `tauri` and `tauri-build` versions in `src-tauri/Cargo.toml`.
```
tauri = { git = "https://github.com/tauri-apps/tauri", features = [..] }
tauri-build = { git = "https://github.com/tauri-apps/tauri" }
```
2. run `cargo update` inside `src-tauri`
3. install the git version of the cli
```
cargo install tauri-cli --git https://github.com/tauri-apps/tauri
```
4. run the app
```
cargo tauri dev
```

**Comment by uwohlfeil** [comment]
@amrbashir
Thank you for your impressive fast answer  and helpful answer.
I can confirm it works with this version with Manjaro and KDE. 

Thank you very much
