### ISSUE TITLE
`postMessage` not injected by webview when loading svelte applcation with `bind:clientHeight`

### ISSUE THREAD

**Issue by 9ParsonsB** [tauri-apps/tauri#2716]
### **Describe the bug**
When loading a svelte application with `bind:clientHeight` or `bind:clientWidth` on one of the elements on the page, `window.chrome.webview.postMessage()` is undefined due to delayed firing of `DOMContentLoaded` event

### **To Reproduce**
1. Clone [this](https://github.com/9ParsonsB/svelte-check-bug) repo (or use `bind:clientWidth` on any component)
2. `yarn tauri dev && yarn dev`
3. Open Browser DevTools

### **Expected behavior**
No Error

### **Platform and Versions:**
```
Operating System - Windows, version 10.0.22458 X64
Webview2 - 94.0.992.31

Node.js environment
  Node.js - 16.10.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.22.0
  yarn - 1.22.11

Rust environment
  rustc - 1.57.0-nightly
  cargo - 1.57.0-nightly

App directory structure
/.git
/.vscode
/node_modules
/src
/src-tauri
/wwwroot

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../wwwroot
  devPath - http://localhost:5000
  framework - Svelte
  bundler - Rollup
```

### **Additional Information**:
[Discord support conversion](https://discord.com/channels/616186924390023171/625037620996734986/893378312334901288)

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'postMessage')
    at Object.invoke (<anonymous>:2:62)
    at Rpc.notify (<anonymous>:41:41)
    at <anonymous>:121:20
    at new Promise (<anonymous>)
    at invoke (<anonymous>:102:12)
    at <anonymous>:396:18
    at append (index.mjs:309)
    at add_resize_listener (index.mjs:712)
    at Object.m (App.svelte:5)
    at mount_component (index.mjs:1727)
```

**Comment by Archieeeeee** [comment]
I still have this error : first start app, change location to a new page which uses vue, and error happens when the vue app tries to mount web element.

![image](https://user-images.githubusercontent.com/730816/146273408-5cf6e529-7a39-42ef-abaa-8638cb5ee3fe.png)

![image](https://user-images.githubusercontent.com/730816/146273379-0752c9f0-3e5c-48c8-bb9f-e9e65ad16dad.png)


```
2VM234:2 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'postMessage')
    at Object.invoke (<anonymous>:2:62)
    at Rpc.notify (<anonymous>:41:41)
    at <anonymous>:134:22
    at insert (runtime-dom.esm-bundler.js:10)
    at mountElement (runtime-core.esm-bundler.js:3948)
    at processElement (runtime-core.esm-bundler.js:3868)
    at patch (runtime-core.esm-bundler.js:3788)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:4339)
    at ReactiveEffect.run (reactivity.esm-bundler.js:160)
    at setupRenderEffect (runtime-core.esm-bundler.js:4458)
```

**Comment by lucasfernog** [comment]
@Archieeeeee can you share an app we can use to reproduce it?
