### ISSUE TITLE
copy_binaries fails if source is readonly

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri#2728]
### **Describe the bug**
When running tauri through the cli, resources and binaries are coping into the target directory to provide access consistent to the final bundle. The function used is `std::fs::copy` which keeps file flags when copying, **but fails if the target is not writeable**. This means that if a file is not writeable to begin with (as is commonplace with binaries) re-running `tauri dev`/`tauri build` will crash.
3 Solutions come to mind:
1. require all binaries and resources be writeable and possibly check that before copying. (This is basically make it a feature not a bug, it leaks internals)
2. Set write flag after copying
3. Unlink "old" binaries and resources before copying

### **To Reproduce**
1. Specify a sidecar binary
2. make that binary read only
3. run `tauri dev` **two times**
4. the second time crashes with a permission error

### **Platform and Versions (required):**

This was checked on macos, but applies to all unix systems (and possibly win too?)
```
Operating System - Mac OS, version 12.0.0 X64
WARNING: no lock files found, defaulting to npm

Node.js environment
  Node.js - 16.9.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - Not installed

Global packages
  npm - 7.21.1
  pnpm - Not installed
  yarn - 1.22.11

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/dist
/node_modules
/.storybook
/public
/src-tauri
/coverage
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist/static
  devPath - http://localhost:3000
  framework - React
```

**Comment by lucasfernog** [comment]
Couldn't reproduce it, @JonasKruckenberg can you check this again?

**Comment by JonasKruckenberg** [comment]
I think this is fixed, will reopen if I encounter it again
