### ISSUE TITLE
Snowpack with Tauri doesn't work

### ISSUE THREAD

**Issue by Gabriel-Alves-Cunha** [tauri-apps/tauri#2755]
### **Describe the bug**
I was starting to build this app with snowpack, yarn v3.0.2, react and typescript and successfully integrated Tauri, however, when I do `yarn tauri dev`, it builds but the window simply doesnt respond. It does nothing. I had tried to build first with ViteJS and had the same problem. Thought it was a matter of incompatibility, but this new one I believe it should work because there is not a lot of fancy things going on and everything on 'package.json' is at the latest version. Can someone help me?

Also, as you can see on the `yarn tauri info` below, it shows that the ''@tauri-apps/api" is not installed even though I did installed it when tauri itself asked me if I wanted, and even though it is on 'package.json'.

### **To Reproduce**
1. Download this repo: ''https://github.com/Gabriel-Alves-Cunha/dora.git"
2. Install yarn dependencies with yarn berry:
```bash
yarn set version berry
yarn dlx @yarnpkg/sdks vscode # if using vscode, if not, search yarnpkg.com for your text editor
yarn plugin import typescript
yarn
# You must run VS Code, open any TypeScript file and in the bottom right side of the window click on TypeScript version. Select Use Workspace Version from dropdown menu to actually use Workspace Compiler.
```  
3. run `yarn dev` to concurrently compile tauri and run the snowpack server (wich will also open a tab on your browser)
4. See that when the compilation finishes, the app does not work, the 'Inspect Element' also does not work because the app appears to be frozen.

### **Expected behavior**
The Tauri window should work as a tab on a browser. 

### **Platform and Versions (required):**
```
 app:spawn Running "/home/gabriel/Documents/VSCode/dora/node_modules/@tauri-apps/cli/bin/tauri-cli tauri info" +0ms


Operating System - Fedora, version 34.0.0 X64

Node.js environment
  Node.js - 14.18.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - Not installed

Global packages
  npm - 6.14.15
  yarn - 3.0.2

Rust environment
  rustc - 1.55.0
  cargo - 1.55.0

App directory structure
/.git
/.vscode
/.yarn
/plugins
/node_modules
/src
/src-tauri
/dist

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist/web
  devPath - http://localhost:3000
  framework - React
```

### **Stack Trace**
There are no errors shown, even though I run it with ''RUST_DEBUG=1 RUST_BACKTRACE=1"

**Comment by Ripwords** [comment]
I can't provide much help as to why snowpack isn't working for you, however using [vite-plugin-tauri](https://www.npmjs.com/package/vite-plugin-tauri) I was able to get vite working with tauri, you might wanna give it a go. [Here](https://github.com/Ripwords/unicorn) is the repo i am working on

**Comment by nothingismagick** [comment]
@Gabriel-Alves-Cunha - can you please edit the title of your issue to reflect the actual problem. "Tauri doesn't work" is not helpful.

**Comment by Gabriel-Alves-Cunha** [comment]
> @Gabriel-Alves-Cunha - can you please edit the title of your issue to reflect the actual problem. "Tauri doesn't work" is not helpful.

yep, sorry...

**Comment by amrbashir** [comment]
your app had problems with it and I don't want to waste my time trying to fix it so instead I created a new snowpack project using `create-snowpack-app` and add tauri to it `yarn add -D @tauri-apps/cli && yarn tauri init` and made necessary changes to `tauri.conf.json` and it works fine so Snowpack works with Tauri without any problems and I am gonna close this issue as invalid.
