### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'window.rpc.notify')  Object Prototype

### ISSUE THREAD

**Issue by sunhao8** [tauri-apps/tauri#2767]
### **Describe the bug**
I used the js api to create the new webview windows, but It was fail when I want to create the second window in the first new webview window
```
 const time = new Date().getTime();
 const webview = new WebviewWindow(`${time}`, {url,});
 webview.once('tauri://created', () => {console.log('success');});
 webview.once('tauri://error', (e) => {console.log('defeat', e);});
```

### **To Reproduce**
1. create the first new webview window(It was success)
2. create the next new window in the firs window(defeat)
3. the error was  that:
event: "tauri://error"
id: -1
payload: TypeError: undefined is not an object (evaluating 'window.rpc.notify')

### **Expected behavior**
create the second window in the first webview window successfully

### **Screenshots**
<img width="863" alt="screenshort2021-10-19 下午2 58 34" src="https://user-images.githubusercontent.com/80802170/137859476-301c9364-ec0d-44f4-8e2a-56b6639d26c7.png">

### **Platform and Versions (required):**

```
Operating System - Mac OS, version 11.6.0 X64

Node.js environment
  Node.js - 14.18.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.0
  yarn - 1.22.10

Rust environment
  rustc - 1.55.0
  cargo - 1.55.0

App directory structure
/node_modules
/webpack
/public
/src-tauri
/build
/.git
/.vscode
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:8081
  framework - React
  bundler - Webpack
```

**Comment by FabianLars** [comment]
It's somewhat a guess, but i think the issue is related to the url here. If the window url is external (or something not similar to `index.html`/`splashscreen.html`) the tauri code isn't injected into the window (by design, not a bug).
If you need to workaround that, instead of creating the window with the external url, you point it to an "empty" html file and then use sth lik `window.location.replace('url here' )` to navigate to the wanted url.
