### ISSUE TITLE
[docs] Note about Cargo.toml should mention Cargo.lock

### ISSUE THREAD

**Issue by ChrisGreenaway** [tauri-apps/tauri#2781]
On https://tauri.studio/en/docs/development/, in the "A note about Cargo.toml and Source Control" section, it says that Cargo.toml should be committed, but does not mention that Cargo.lock should be committed too.

The note says "because you want it to be deterministic" - but that's not the reason to commit a Cargo.toml - that's the reason to commit a Cargo.lock.

**Comment by nothingismagick** [comment]
Absolutely right. This is why we don't commit a `Cargo.lock` on the library / framework - but you should for your app!

Great catch

**Comment by facklambda** [comment]
Hey folks,

I'm on a bit of a roll with regards to documentation stuff right now. I can submit a PR with these changes.

I'll add some information otherwise found from here: https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

**Comment by ChrisGreenaway** [comment]
Thanks. :-)
