### ISSUE TITLE
All functions from the JS dialog module do nothing and then resolve with null

### ISSUE THREAD

**Issue by Xavier-Maruff** [tauri-apps/tauri#2792]
### **All functions from the JS `dialog` module do nothing and then resolve with null**
When calling either `save` or `open` from the `dialog` JS module, the file dialog does not show up, and the returned promise immediately resolves with a null value.  The dialog module is allowlisted in the tauri config file, and other modules are working as expected without issue, so I have no idea what the source of this problem could be.
The following code is the context in which the `dialog` module's `open()` function is called:
```ts
import { Options, Vue } from "vue-class-component";
import { open as openDialog } from "@tauri-apps/api/dialog";


@Options({
  components: {
    ... some vue components ...
  },
})
export default class Freeze extends Vue {
  selectedFilepaths: string[] = [];

  async selectFile(){
    const pathNames: string = await openDialog({
      defaultPath: ".",
      multiple: false
    }) as string;
    this.selectedFilepaths.push(pathNames);
    console.log(this.selectedFilepaths);
  }
}
```

### **To Reproduce**
1. Clone [https://github.com/Xavier-Maruff/tauri_test](https://github.com/Xavier-Maruff/tauri_test)
2. Run `yarn install` and then `yarn tauri:serve`
3. Navigate to the `freeze` tab on the webview
4. When the directory-shaped button is clicked, the function `selectFile()` is called, which in turn awaits the `dialog` module's `open()` function. However, no file dialog opens, and the promise resolves with `null`

### **Expected behavior**
The file dialog opens, and the promise resolves with the selected file path.

### **Platform and Versions (required):**

```
Operating System - Windows, version 10.0.19043 X64
Webview2 - 95.0.1020.30

Node.js environment
  Node.js - 14.16.0
  @tauri-apps/cli - 1.0.0-beta.6
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.7.5
  yarn - 1.22.4

Rust environment
  rustc - 1.55.0
  cargo - 1.55.0

App directory structure
/.git
/node_modules
/public
/src
/src-tauri
/tests

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - Set automatically by Vue CLI plugin
  devPath - Set automatically by Vue CLI plugin
  framework - Vue.js (Vue CLI)
  bundler - Webpack

```

**Comment by amrbashir** [comment]
I couldn't run your app but I know for a fact that the dialog works as expected using our `next` branch. Please try again with our `next` branch or wait for the next release.

**Comment by OrIOg** [comment]
I had the same problem. I solved it by using a valid path for 'defaultPath' or not using it.

Don't know if it is the expected behaviour, maybe it should be preferable to notify the user/use default directory ?

**Comment by amrbashir** [comment]
@OrlOg, indeed you need to pass a valid path or just pass `null` and it will use the os default folder or pass `.` for current directory. OP's example is using `.` which I tested on my Windows and it is working fine.

**Comment by Xavier-Maruff** [comment]
> I had the same problem. I solved it by using a valid path for 'defaultPath' or not using it.
> 
> Don't know if it is the expected behaviour, maybe it should be preferable to notify the user/use default directory ?

Awesome, thank you so much, this works if I don't set "defaultPath". It's quite odd that it didn't work when I was using "." as the defaultPath though? Anyway, thanks for your response.
