### ISSUE TITLE
Compatibility testing

### ISSUE THREAD

**Issue by xxSkyy** [tauri-apps/tauri#2796]
As Tauri bases on system webview we need to check frontend compatibility with different envitonments - windows, linux, mac. 
Sure I can connect to dev server on mac then check on windows then linux manually but it's very inefficient for debugging and sometimes needs to reboot machine or having virtual machine installed.
Are there other good method/tool to check frontend behaviour in a different environment (best) from macOS?

**Comment by amrbashir** [comment]
If you want to test how your app will look on different webviews then you can test on:
- For how your app will look on Windows, any chromium based browser like Chrome, Edge or Brave.
- For macOS, Safari.
- For Linux, Epiphany or any webkit based browser (Safari might do the trick too).

I'd recommend using [normalize.css](https://necolas.github.io/normalize.css/) and postcss [autoprefixer](https://github.com/postcss/autoprefixer) or something similar.

Also note that any Tauri related api won't work in the browser, so you should just be mainly testing the look of your app.

**Comment by xxSkyy** [comment]
> If you want to test how your app will look on different webviews then you can test on:
> 
>     * For how your app will look on Windows, any chromium based browser like Chrome, Edge or Brave.
> 
>     * For macOS, Safari.
> 
>     * For Linux, Epiphany or any webkit based browser (safari might do the trick too).
> 
> 
> I'd recommend using [normalize.css](https://necolas.github.io/normalize.css/) and postcss [autoprefixer](https://github.com/postcss/autoprefixer) or something similar.
> 
> Also note that any Tauri related api won't work in the browser, so you should just be mainly testing the look of your app.

Thanks for tips, especially about linux, this one I have less experience in. 

Yea I just meant frontend,I'm not concerned about rust backend .I'm using autoprefixer and normalizecss with tailwindcss / windicss. But sometimes I still had things that worked i.e. only in firefox for now. Sometimes it can be missed doing custom css properties.
