### ISSUE TITLE
[docs] node v17 may not be supported

### ISSUE THREAD

**Issue by murrayju** [tauri-apps/tauri#2797]
Following the setup instructions to use `nvm`, you will now end up with node v17. This seems to fail when you get to trying `npm run tauri dev`:

```
<snip>/tauri-app/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/<snip>/tauri-app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (<snip>/tauri-app/node_modules/webpack/lib/NormalModule.js:417:16)
    at <snip>/tauri-app/node_modules/webpack/lib/NormalModule.js:452:10
    at<snip>/tauri-app/node_modules/webpack/lib/NormalModule.js:323:13
    at <snip>/tauri-app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at <snip>/tauri-app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (<snip>/tauri-app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at<snip>/tauri-app/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

This may be limited to just the `create-react-app` option, or any others that use webpack.

### Solution
Use an older version of node, e.g.

```
nvm install --lts --latest-npm
```

**Comment by amrbashir** [comment]
I thought this was an error in our js cli but looking at the stack trace, it is a problem in `create-react-app`, specifically the `babel-loader` used in their `webpack` config.

With that said, it is not an issue in Tauri so I will close this.

**Comment by murrayju** [comment]
Agreed, but I'd suggest mentioning this in the docs so everyone (trying with react) doesn't run into this.

**Comment by amrbashir** [comment]
I don't think that's a good idea. if they used `create-react-app` in node v17 in a project without Tauri, it will still crash, so it shouldn't be our responsibility to warn users about this.

Also note that Tauri is framework agnostic, and maintaining fixes for one framework is not what Tauri is about.

**Comment by TheMaverickProgrammer** [comment]
This happens following your setup guide on the website.
https://tauri.studio/docs/getting-started/beginning-tutorial/

I am using node v17.9.0 and selected vue-cli as the front-end.

UPDATE:
This isn't a tauri thing because the vue-cli project setup step is not maintained by tauri team. It's whoever contributed that configuration. Also, the solutions are downgrading node to 16 or using `--openssl-legacy-provider` instead of openssl 3.0 which isn't advised. Use another project setup like vite.
