### ISSUE TITLE
Can't install .deb in Kali Linux, libappindicator deprecated

### ISSUE THREAD

**Issue by guillemcordoba** [tauri-apps/tauri#2799]
### **Describe the bug**

When trying to install a .deb package in Kali Linux, the error `Package libappindicator3-1 is not installed` shows up.

It seems libappindicator [has been deprecated in those systems](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037)? Not sure what is the issue or whether this should go upstream to linuxdeploy. It seems to me [this is the code that should potentially change](https://github.com/tauri-apps/tauri/blob/8d630bc8c494cba6ac1604b7777b89b763044471/tooling/cli.rs/src/interface/rust.rs#L405).

### **To Reproduce**
1. Build a tauri app in Ubuntu.
2. Try to install the resulting .deb in Kali Linux 2021.3.

### **Expected behavior**

Installing the package install the necessary dependencies.

### **Platform and Versions (required):**
```
Operating System - Ubuntu, version 18.04 X64

Node.js environment
  Node.js - 12.22.6
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.15
  yarn - 1.22.15

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/src
/public
/node_modules
/.git
/.github
/scripts
/src-tauri
/tests

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - target/webpack_dist
  devPath - target/webpack_dist
  framework - Vue.js (Vue CLI)
  bundler - Webpack
```

**Comment by lucasfernog** [comment]
We're using libayatana-appindicator by default now, though you can configure it to use libappindicator-gtk3 to ship .deb bundles for older systems.
