### ISSUE TITLE
Unable to install @tauri-apps/cli or @tauri-apps/api using yarn

### ISSUE THREAD

**Issue by p32929** [tauri-apps/tauri#2800]
### **Describe the bug**
Unable to install @tauri-apps/cli or @tauri-apps/api using yarn. it shows this:
![image](https://user-images.githubusercontent.com/6418354/138740370-2457d98e-1504-46ac-8466-60ef1b13fdba.png)

I don't wanna install pnpm just for one project

### **To Reproduce**
1. Open any web project
2. `yarn add -D @tauri-apps/cli`
3. or `yarn add @tauri-apps/api`
4. shows the error in the screenshot

### **Expected behavior**
Expected to get the dependencies installed

### **Platform and Versions (required):**

can't do `yarn tauri info` as its not getting installed
but,
Operating System: Windows 10
Node.js: v14.17.1

**Comment by amrbashir** [comment]
This is not an issue with our packages, your project seems to have a `preinstall` script that only allows pnpm to be used for the project. more info https://pnpm.io/only-allow-pnpm

**Comment by p32929** [comment]
Oops! Sorry about that & thanks
