### ISSUE TITLE
Items automatically added to `View` menu on macOS

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tauri#2804]
### **Describe the bug**
When you have a `View` menu, these items are automatically added:

![image](https://user-images.githubusercontent.com/11315492/138804187-30c7e96d-e327-4ad1-92ee-eba8f26dc27f.png)

I initially thought macOS did this automatically (it does for `Edit > Start Dictation` and `Edit > Emoji & Symbols`), but apps like Discord don't have it.

### **To Reproduce**
Create a menu called `View`:
```rust
.add_submenu(Submenu::new(
    "View",
    Menu::new(), // can be empty or not
  ));
```

### **Expected behavior**
Either don't auto-add them, or provide a way to not auto-add them

### **Platform and Versions (required):**
<details>
<summary>Details</summary>

```
Operating System - Mac OS, version 10.15.7 X64

Node.js environment
  Node.js - 14.18.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.15
  yarn - 1.22.17

Rust environment
  rustc - 1.56.0
  cargo - 1.56.0

App directory structure
/node_modules
/.github
/src-tauri
/build
/.git
/assets
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:8000
  framework - Svelte
```

</details>

**Comment by lucasfernog** [comment]
Seems like macOS does it automatically, I've been searching for a solution but couldn't find one. As a workaround you can set the submenu title to `View ` with the trailing space.

Ref: https://stackoverflow.com/questions/64220162/how-to-enable-auto-generation-of-window-menuitems-e-g-tile-window-to-left-righ

**Comment by probablykasper** [comment]
Maybe it's the [`allowsAutomaticWindowTabbing`](https://developer.apple.com/documentation/appkit/nswindow/1646657-allowsautomaticwindowtabbing) option as suggested here:
https://stackoverflow.com/a/65282964/6553404

**Comment by martpie** [comment]
Mmmh, I'll try to look at how Electron is trying to avoid it because it's not happening there

**Comment by lucasfernog** [comment]
Tabbing is also related to #3912
