### ISSUE TITLE
Github Action AppImage build only works on Ubuntu

### ISSUE THREAD

**Issue by xyzshantaram** [tauri-apps/tauri#2805]
### **Description**
The current AppImage build (using the GitHub Action) only works on Ubuntu. It seems to be looking for WebKit-related binaries in `/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/`, which only exists on Ubuntu.

This defeats the point of an AppImage, and in the nominal case it shouldn't be looking for any dependencies at all.

Attempting to launch it on Arch Linux fails with:
```
Gtk-Message: 20:10:51.793: Failed to load module "xapp-gtk3-module"
Gtk-Message: 20:10:51.793: Failed to load module "appmenu-gtk-module"
Gtk-Message: 20:10:51.850: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:10:51.851: Failed to load module "canberra-gtk-module"

** (rite:400327): ERROR **: 20:10:52.013: Unable to fork a new child process: Failed to execute child process “/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess” (No such file or directory)
```

### **Steps to reproduce**
1. Build an AppImage with the Tauri GitHub Action. [Sample AppImage](https://github.com/xyzshantaram/rite/releases/download/rite-v0.2.11/rite_0.2.11_amd64.AppImage).
2. Try to run it on a non-Ubuntu distro. I've tested on Arch and Fedora, it doesn't work on either.

### **Expected behavior**
App launches and works normally.

### **Output of `cargo tauri info`**
```
Operating System - Arch Linux, version Unknown X64

Node.js environment
  Node.js - 14.18.1
  @tauri-apps/cli - 1.0.0-beta.10

Global packages
  npm - 8.1.0
  yarn - 1.22.17

Rust environment
  rustc - 1.55.0
  cargo - 1.55.0
```

Others on the Discord (`KaKi87#2368`, `Karar#0413`) have reported this too.

Possibly related to #2689.

**Comment by sujaldev** [comment]
I am still getting the exact same issue
```
Gtk-Message: 20:13:32.162: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:13:32.163: Failed to load module "pk-gtk-module"
Gtk-Message: 20:13:32.163: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:13:32.164: Failed to load module "pk-gtk-module"

** (mr-tagger:63147): ERROR **: 20:13:32.259: Unable to spawn a new child process: Failed to execute child process “/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess” (No such file or directory)
Trace/breakpoint trap (core dumped)
```


> - OS: Fedora 35
> - node - 18.0.0
> - npm - 8.6.0
> - rustc - 1.60.0
> - cargo - 1.60.0

**Comment by FabianLars** [comment]
@sujaldev Your log shows 2 different bugs, one with the "failed to load module" stuff and the one below that (that's the one that actually causes the crash). Both things got fixed in different versions and it's not really possible anymore to have both issues unless you built your app with a really old cli version.
So please check if you built your app with 1.0.0-rc.8 and if not try it again after upgrading it.

**Comment by sujaldev** [comment]
You're right, it had to do with the version.
