### ISSUE TITLE
HTML buttons cannot be focused on in Tauri window

### ISSUE THREAD

**Issue by aaronleopold** [tauri-apps/tauri#2808]
### **Describe the bug**
I cannot focus on HTML button elements in the Tauri window. If I set the button to autofocus then on initial render it will be focused as expected, however it will not be focusable again. I haven't tried every other focusable element, but I did try inputs and they seemed to focus as expected.

### **To Reproduce**
Render two buttons to the screen, set the first one to auto focus. Try clicking tab to move between them, it will not work.

### **Expected behavior**
Clicking tab should move to the next focusable element, clicking the button itself should focus it

### **Screenshots**
I recorded a quick demo of the issue. In the browser, you can see I can focus back and forth between the elements as expected. When I try to do the same in the tauri window, only the inputs can be focused on.

https://user-images.githubusercontent.com/36278431/138989574-67a8cbdc-76e4-42fa-9112-6b5fdbda965e.mov

### **Platform and Versions (required):**
```
Operating System - Mac OS, version 11.6.0 X64

Node.js environment
  Node.js - 16.11.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.0.0
  yarn - 1.22.15

Rust environment
  rustc - 1.56.0
  cargo - 1.56.0

App directory structure
/node_modules
/public
/src-tauri
/.git
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:3000
  framework - React
```

### **Additional context**
For this example, I am using the base  react-tauri template only adding what I needed for tailwind. I have tested using webpack (craco) and React, as well as using Vite and React, and both have the issue. I did also confirm the issue occurs when using Vue. I have also tried removing tailwind completely, and yet it still was an issue. I wanted to make sure this issue persisted across frameworks before submitting this issue.

**Comment by FabianLars** [comment]
Looks like this one https://github.com/tauri-apps/wry/issues/406.
Does it behave for you the same way in Safari as in the issue i linked?
Also, do you use `tabindex`?

**Comment by aaronleopold** [comment]
> Looks like this one [tauri-apps/wry#406](https://github.com/tauri-apps/wry/issues/406). Does it behave for you the same way in Safari as in the issue i linked? Also, do you use `tabindex`?

Ah, it totally looks like the same issue! I didn't think the check upstream. I don't use tabindex, but trying it out is still no go for me. I also just tried safari and the issue persisted. I did find something interesting though, I've been pasting in some generic tailwind components just to see what works and what doesn't and found that tabbing while inside of a modal actually works

https://user-images.githubusercontent.com/36278431/139100489-eaac195b-8e0b-484c-9f62-d27b3c147d01.mov

**Comment by FabianLars** [comment]
I guess that's because of the modal implementation. Instead of letting the browser handle it, it probably handles the tab key event manually to keep it inside the modal.

**Comment by aaronleopold** [comment]
Most likely, that would make sense. Since this is pretty much a duplicate should I just go ahead and close this issue?

**Comment by FabianLars** [comment]
Yeah, i'd say so. core team can reopen it if needed, soooo 🤷

**Comment by m3h0w** [comment]
Any prospects on asking WRY to resolve this? We've been using Tauri to develop an app that relies on keyboard navigation without realizing it might be a problem to get that to work in Tauri on Mac.
