### ISSUE TITLE
More devserver options

### ISSUE THREAD

**Issue by rondonjon** [tauri-apps/tauri#2813]
Please add the following development config options:

- option to pause the Tauri build (or at least its console output) while the dev server is spinning up; both are writing to the console while building, and I am often missing the dev server's error in the Tauri log.

- option to terminate the Tauri build if a devserver command was configured and if that command fails with a non-zero exit code; current behavior is that Tauri keeps building and displays a blank page

- option to force-terminate the devserver when Tauri is terminated (related: #2794)

**Comment by amrbashir** [comment]
1. we can't know when the devServer is finished, in fact we don't know if it is a server or not, we are only executing the `beforeDevCommamd` you specified in `tauri.conf.json`. The solution is to run your devServer in a separate terminal.

2. Good suggestion, we will definitely consider that.

3. This issue has been brought up alot but there is not much that we can do tbh, we are only spawning a process for `beforeDevCommand` and that command can other processes that we can't control nor can we even know about them and it is the job of the process who spawned them to clean them as it exists. We will definitely look into improving it but no guarantees.

**Comment by amrbashir** [comment]
I am gonna go ahead and close this but feel free to open another issue for No.2
