### ISSUE TITLE
Frame-less window

### ISSUE THREAD

**Issue by rdwnali** [tauri-apps/tauri#2816]
Hi!
How can I make my app window frame-less?
I saw this feature was added to tauri in Feb 12 but I don't know how to set it in my app.
thank you!

**Comment by FabianLars** [comment]
you need to disable `decorations`, for example in your tauri.conf.json [>docs<](https://tauri.studio/en/docs/api/config/#tauri.windows.decorations),
alternatively the window objects provide a function too if you're using that to create windows (`setDecorations()`).

This also removes the native titlebar, so in case you need one we have an example [here](https://tauri.studio/en/docs/usage/guides/visual/window-customization)
