### ISSUE TITLE
bug: CLI not working

### ISSUE THREAD

**Issue by kimlimjustin** [tauri-apps/tauri#2821]
### **Describe the bug**
I wanted to create a CLI that allow multiple arguments without any flags similar to VSCode's and I tried the following configuration:

```json
"cli": {
    "description": "Open Xplorer and open the specified directory.",
    "args": [
            {
          "name": "dir",
          "index": 1,
          "multiple": true
        }
    ]
}
```
and it gives me the following error 
![image](https://user-images.githubusercontent.com/61906684/139410775-4b0ee018-c1bb-4a1e-a4cd-72d1e8d7c704.png) 
and I head on the [docs](https://tauri.studio/en/docs/guides/cli/#positional-arguments) and copied the example and also the similar error occurs:
![image](https://user-images.githubusercontent.com/61906684/139411429-a155c42e-fb44-4d4b-9271-376102b98f5f.png)

I have also tried to pass `--` but still the same error

### **To Reproduce**
1. Go to the [docs](https://tauri.studio/en/docs/usage/guides/cli/#positional-arguments)
2. Copy the example
3. Read the match on JavaScript (https://tauri.studio/en/docs/guides/cli/#javascript)
4. See the console, there's an error

### **Expected behavior**
CLI works fine and I could able to create a VSCode's similar CLI.

### **Screenshots**
See above.

### **Platform and Versions (required):**

```
Operating System - Windows, version 10.0.22000 X64
Webview2 - 95.0.1020.30

Node.js environment
  Node.js - 16.0.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.10.0
  yarn - 1.22.11

Rust environment
  rustc - 1.56.0
  cargo - 1.56.0

App directory structure
/.git
/.github
/.husky
/.vs
/.vscode
/build
/coverage
/dist
/docs
/node_modules
/out
/packages
/patches
/scripts
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src asset: blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../out/src
  devPath - http://localhost:8080
  bundler - Webpack
```

### **Additional context**
More info: https://discord.com/channels/616186924390023171/625037620996734986/903540306304196618

**Comment by lucasfernog** [comment]
Fix will be available on the next release. Btw if you're only using one positional argument, you might as well just go with https://doc.rust-lang.org/stable/std/env/fn.args.html
