### ISSUE TITLE
backdrop-filter not working!

### ISSUE THREAD

**Issue by rdwnali** [tauri-apps/tauri#2826]
Hi!
css backdrop-filter not working, while it works at chrome at same time.

**Comment by amrbashir** [comment]
Please don't ignore the issue template and provide the necessary info.

**Comment by rdwnali** [comment]
OK.
backdrop-filter does not supported?

**Comment by amrbashir** [comment]
`backdrop-filter` is supported but we still need more context, code snippet, `tauri info` output, minimal reproduction repo or at least steps to produce. 

If these info isn't provided, I will close the issue as we can't help without it.

**Comment by rdwnali** [comment]
```
Operating System - Ubuntu, version 20.04 X64

Node.js environment
  Node.js - 14.18.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.15
  yarn - 1.22.17

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/dist
/src-tauri
/node_modules

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - ../dist

```

**Comment by amrbashir** [comment]
Code snippet? minimal repro or steps to reproduce ? screenshots ?!!

**Comment by rdwnali** [comment]
I don't have any code snippet yet. I tried it before and it doesn't work and I changed my code.

**Comment by amrbashir** [comment]
Alright, I re-opened this until I get time to confirm.

**Comment by amrbashir** [comment]
Closing this as it is invalid, `backdrop-filter` works on linux, see #2827
