### ISSUE TITLE
Cannot listen to resize event

### ISSUE THREAD

**Issue by Gabriel-Alves-Cunha** [tauri-apps/tauri#2829]
### **Describe the bug**
I listen to resize event once the app is mounted with react, but an error appears on the console (see image below).

### **To Reproduce**
1. Clone the repo 'https://github.com/Gabriel-Alves-Cunha/muse';
2. Do `yarn` to install everything (I'm assuming you followed the steps to be able to build Tauri in your pc);
3. Do `yarn dev`;
4. Open the DevTools and see error

### **Expected behavior**
I expected to be able to listen to events without any errors. Am I doing something wrong?

### **Screenshots**
![Screenshot from 2021-11-02 08-56-34](https://user-images.githubusercontent.com/52057747/139843682-5480a85a-e0cd-4b0f-847c-90092a6f2d68.png)

### **Platform and Versions (required):**

```
yarn run v1.22.15
$ /home/gabriel/Documents/VSCode/muse/node_modules/.bin/tauri info
 app:spawn Running "/home/gabriel/Documents/VSCode/muse/node_modules/@tauri-apps/cli/bin/tauri-cli tauri info" +0ms


Operating System - Fedora, version 34.0.0 X64

Node.js environment
  Node.js - 14.18.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.15
  yarn - 1.22.15

Rust environment
  rustc - 1.55.0
  cargo - 1.55.0

App directory structure
/node_modules
/src
/src-tauri
/build
/.git
/plugins
/.vscode
/.parcel-cache
/dist
/assets

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build/web
  devPath - http://localhost:1234
  framework - React

Done in 13.64s.
```

**Comment by FabianLars** [comment]
The problem is not the listening to the resize event, otherwise you wouldn't even get the errors.
The problem seems to be this line: `const { isDecorated, isFullscreen } = appWindow;`, because doing it this way makes `this` inaccessible(undefined), but it's needed/used by those functions.
Probably the (easiest) way to go is to just do `appWindow.isDecorated()` everywhere 🤷

**Comment by Gabriel-Alves-Cunha** [comment]
Yeah, it was it. Thanks for helping! :D
