### ISSUE TITLE
http.fetch always expects a reponse body

### ISSUE THREAD

**Issue by KaKi87** [tauri-apps/tauri#2831]
### **Describe the bug**

`http.fetch` always expects a reponse body, therefore throws an error when there is none.

### **To Reproduce**

1. Run an `http.fetch` request that will return no response body and without defining `responseType` ;
2. See the following error : `Failed to parse response as JSON: SyntaxError: JSON Parse error: Unexpected EOF; try setting the responseType option to ResponseType.Text or ResponseType.Binary if the API does not return a JSON response`.

### **Expected behavior**

The request succeeds.

### **Platform and Versions (required):**

```
Operating System - Linux, version 19.3 X64

Node.js environment
  Node.js - 14.18.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.0
  yarn - 1.22.15

Rust environment
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/dist
/node_modules
/.idea
/src
/src-tauri
/.git
/.parcel-cache

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:1234
```

### **Additional context**

This error was spotted during the development of [`axios-tauri-adapter-test`](https://git.kaki87.net/KaKi87/axios-tauri-adapter-test), the unit test project for [`axios-tauri-adapter`](https://git.kaki87.net/KaKi87/axios-tauri-adapter).

### **Stack Trace**

Not applicable

**Comment by lucasfernog** [comment]
By default Tauri assumes a JSON response. It should work with [`ResponseType.Binary`](https://tauri.studio/en/docs/api/js/enums/http.ResponseType#binary).

**Comment by KaKi87** [comment]
Perhaps, although this is only a workaround, but not a fix.

**Comment by lucasfernog** [comment]
Why is it a workaround if it's the API design? It might be a wrong design (we could argue that it should default to a binary response), but it's still the current design.

**Comment by KaKi87** [comment]
Axios, for example, also uses `json` as default value for `responseType` ([source](https://github.com/axios/axios#request-config)) :
```js
// `responseType` indicates the type of data that the server will respond with
// options are: 'arraybuffer', 'document', 'json', 'text', 'stream'
//   browser only: 'blob'
responseType: 'json', // default
```
Yet, it won't throw an error when there is no response body, because there is no obligation for it to exist.

Additionally, setting any value (like `ResponseType.Binary`)  for `responseType` implies that a response body is expected, which is not the case, so it would be confusing.

But, I must also agree that Axios' behavior does not follow what I just said, as it ignores the lack of response body when one is expected, therefore, I alternatively suggest accepting `null` and/or something like `ResponseType.None` as a value for `responseType` that will prevent throwing an error when a request returns no response body.

**Comment by lucasfernog** [comment]
I see your point now, and I agree with you.

**Comment by KaKi87** [comment]
What about a step further : `ResponseType.Any`, which would follow Axios' behavior ? 🙃
