### ISSUE TITLE
no `SystemTrayMenu` in the root

### ISSUE THREAD

**Issue by RuralDependencies** [tauri-apps/tauri#2832]
Hi,

New to Tauri, when attempting to start with a Tray, I get 1 
```
| use tauri::{CustomMenuItem, SystemTray, SystemTrayMenu};
  |                             ^^^^^^^^^^  ^^^^^^^^^^^^^^ no `SystemTrayMenu` in the root
  |                             |
  |                             no `SystemTray` in the root
```

Here is my code:

```
use tauri::{CustomMenuItem, SystemTray, SystemTrayMenu};
use tauri::Manager;

fn main() {

  let tray_menu = SystemTrayMenu::new(); // insert the menu items here
  tauri::Builder::default()
    .system_tray(SystemTray::new().with_menu(tray_menu))
    .on_system_tray_event(|app, event| match event {
      SystemTrayEvent::LeftClick {
        position: _,
        size: _,
        ..
      } => {
        println!("system tray received a left click");
      }
      SystemTrayEvent::RightClick {
        position: _,
        size: _,
        ..
      } => {
        println!("system tray received a right click");
      }
      SystemTrayEvent::DoubleClick {
        position: _,
        size: _,
        ..
      } => {
        println!("system tray received a double click");
      }
      SystemTrayEvent::MenuItemClick { id, .. } => {
        match id.as_str() {
          "quit" => {
            std::process::exit(0);
          }
          "hide" => {
            let window = app.get_window("main").unwrap();
            window.hide().unwrap();
          }
          _ => {}
        }
      }
      _ => {}
    })
    .run(tauri::generate_context!())
    .expect("error while running tauri application");



}



```

I'm not understanding what to do to make the process start with the tray.
Thank you for the help

EDIT: This was due to tauri.config.json not being updated when starting, make sure you start with: npm run tauri dev

**Comment by FabianLars** [comment]
Please fill out the provided template when creating issues. The output of `tauri info` (annotated with **required**...) would be helpful here to make sure it's not version related. I can't even count the number of times this was the issue.

Anyway, make sure to add the `systemTray` property in your tauri.conf.json ([example](https://tauri.studio/en/docs/guides/system-tray#setup)), this automatically enables/disables the system-tray feature  in Cargo.toml

**Comment by RuralDependencies** [comment]
Hmmm actually the problem was with the official Tauri example not being done properly, it's lacking:
SystemTrayEvent in the imports.

This specific part: https://tauri.studio/en/docs/guides/system-tray/#listening-to-system-tray-events

Thank you for the help :)

**Comment by FabianLars** [comment]
I don't see how that is related to the error message you posted, but apart from that you're right about SystemTrayEvent missing.

**Comment by RuralDependencies** [comment]
Yeah you are right, I've eventually found a way, tauri config was already modified but it was apparently not being "updated" when starting tauri, I was starting it from a hello-tauri simple example, I've redone everything and it worked (except for the last part).

I think it would actually be awesome to add a lot of working ready-made examples (to download that runs out of the box, with a working Tray, custom titlebar...) similar to Electron for beginners to understand better (especially the ones that have never touched Rust in their life).

Thanks for the help @FabianLars!

**Comment by FabianLars** [comment]
Yeah, more examples are always better 👍 
Keep in mind that we have the repo [examples](https://github.com/tauri-apps/tauri/tree/next/examples) and iirc there's another big one (as a seperate repo i think) in the pipeline.

On top of that you can always check out the didathing-examples channel on our discord or githubs auto generated [list](https://github.com/tauri-apps/tauri/network/dependents?package_id=UGFja2FnZS0yMTE5ODkxMDAy).
But i agree that "official" ones are generally better/more accessibile, tutorial-wise.
