### ISSUE TITLE
[docs] window-customization#js

### ISSUE THREAD

**Issue by RuralDependencies** [tauri-apps/tauri#2839]
Hi,

For newcomers, it's quite problematic to understand this part:
https://tauri.studio/en/docs/guides/window-customization#js

```
import { appWindow } from '@tauri-apps/api/window'
document
  .getElementById('titlebar-minimize')
  .addEventListener('click', () => appWindow.minimize())
document
  .getElementById('titlebar-maximize')
  .addEventListener('click', () => appWindow.toggleMaximize())
document
  .getElementById('titlebar-close')
  .addEventListener('click', () => appWindow.close())

```
Here adding that code to index.html (in Dist) will not work, even after modifying tauri.conf.json:    
```
 "allowlist": {
      "all": true
    }, 

```
I'm trying to find a workaround but...
Where is this code has to be added? The titlebar shows, but when clicking on any (minimize, close...) it doesn't work.

In devtools, the error is: Unexpected token '{'. import call expects exactly one argument
![image](https://user-images.githubusercontent.com/55824167/140199507-f6061114-8b43-458a-9a94-6c187aefac47.png)

> [tauri]: running info
> 
> Operating System - Linux(5.4.0-73-generic) - linux/x64
> 
> Node.js environment
>   Node.js - 16.1.0
>   tauri.js - 0.14.1
> 
> Rust environment
>   rustc - 1.56.1
>   cargo - 1.56.0
>   tauri-bundler - 0.9.4
> 
> Global packages
>   NPM - 7.11.2
>   yarn - Not installed
> 
> App directory structure
> /assets
> /dist
> /node_modules
> /src-tauri
> 
> App
>   tauri.rs - 1.0.0-beta.8
>   mode - unset
>   build-type - bundle
>   CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
>   distDir - ../dist
>   devPath - ../dist
>

**Comment by FabianLars** [comment]
The code snippets expect you to use some kind of frontend bundler (which make this kind of imports work), otherwise using npm packages isn't really an option anyway. (check out [vite](vitejs.dev/) if you're looking for something)
Alternatively you can enable the global tauri object in your tauri.conf (considered less safe) and use `window.__TAURI__.window.appWindow.minimize()`.

**Comment by RuralDependencies** [comment]
Oh I see, thanks I'm gonna try that out now. Hmm yeah I would really think those would have to be stated, the doc is assuming that developers in general are actually any good :D

**Comment by RuralDependencies** [comment]
It works! Thank you so much FabianLars.
