### ISSUE TITLE
[docs] How to use gRPC natively (not grpc-web)

### ISSUE THREAD

**Issue by tiero** [tauri-apps/tauri#2841]
I have a web application that now uses grpc-web to call a gRPC backend service, now that I am bundling and shipping it as desktop app, does not makes sense to use it, better to use native gRPC taking full advantage of HTTP/2 transport and binary encoding.

I would want to use [@grpc/grpc-js](https://www.npmjs.com/package/@grpc/grpc-js) (ie. the NodeJS library) instead of need to use the browser implementation (grpc-web), not sure how I can override this under the hood when I am going to compile/bundle for dekstop fopr tauri (ofc grpc-js the nodejs version will not work on browser in development, but that's ok)

**Comment by FabianLars** [comment]
> ofc grpc-js the nodejs version will not work on browser in development, but that's ok

And it won't work in production either, there is no nodejs runtime in tauri apps, so packages that depend on nodejs runtime/modules won't work.
Basically the options you have are:
- keep using grpc-web
- sidecar a nodejs app compiled with pkg that uses the wanted grpc package. With that approach you also have to figure out a way to communicate with your frontend
  - is stdout enough? - nice!
  - localhost server? - lol, don't do it
  - grpc? - needs grpc-web again...
- use a rust crate for the communication - probably the most secure way and in theory the best practice, but the communication between rust and the frontend would somewhat bottleneck here, resulting in slower comms than using grpc-web directly. Also there are ideas to replace or give an alternative to the current approach with grpc.

**Comment by tiero** [comment]
My problem with using grpc-web, is that if the backend is using self signed TLS, it assumes that it will be installed system wide in the keychain/certificate store of the computer. (this becauase how browser works with https)

In the case of normal gRPC clients, I can pass the TLS certificate programmatically to the grpc client as parameter, hiding this complexity for the end-user.

It seems to me that would be best to use rust for the grpc client stubs, but not clear how to interface from JavaScript with the underlying rust code/binary.

If this is not possible and I am forced into using grpc-web, will tauri app requires the TLS self signed cert to be installed system wide like browsers do?

**Comment by FabianLars** [comment]
> It seems to me that would be best to use rust for the grpc client stubs, but not clear how to interface from JavaScript with the underlying rust code/binary.

probably with tauri [commands](https://tauri.studio/en/docs/usage/guides/command) and [events](https://tauri.studio/en/docs/usage/guides/events).

> will tauri app requires the TLS self signed cert to be installed system wide like browsers do?

Most likely yes, the WebView behaves just like a browser in 99% of the time.
