### ISSUE TITLE
CLI arg to point at Tauri project dir

### ISSUE THREAD

**Issue by OJFord** [tauri-apps/tauri#2844]
**Is your feature request related to a problem? Please describe.**
I have a main project dir with a `[workspace]` `Cargo.toml`, and a sub-directory which is one of the workspace members, and the Tauri project. I'm usually in the main dir, and can `cargo build` (all members including the Tauri project) from there, but if I want to `cargo tauri dev` I get:
> thread 'main' panicked at 'Couldn't recognize the current folder as a Tauri project.', /.../tauri-cli-1.0.0-beta.7/src/helpers/app_paths.rs:29:

**Describe the solution you'd like**
1. Perhaps ideally, `tauri-cli` could run against any/all workspace members (iff `$PWD` is a workspace) that are detected as being tauri projects;
2. a global CLI argument that allows me to specify where the project is if not `$PWD`

**Describe alternatives you've considered**
I was using a `package.json` script (which included a call to `tauri dev`) which I could run as `yarn --cwd=subdir dev`. I decided I wanted to use `build.rs` and `tauri.conf.json`'s `beforeDevCommand` as the entrypoints instead, but then found I couldn't do the same.

(Aside, I wouldn't suggest copying 'cwd' - perhaps it's meant to be '**c**hange **w**orking **d**irectory' (though why not `cd` then 🤔 ) but I can't help but read it as '**c**urrent', which then just seems awkward and doesn't really make sense.)

**Additional context**

**Comment by amrbashir** [comment]
possibly duplicate of #2752 and discussion at its PR #2765

**Comment by OJFord** [comment]
Blimey that was fast. Indeed yes, pretty much, especially with your comment on its PR, sorry I didn't find that.

In my case though `tauri --dir=subdir info` would still be able to read `package.json` as normal, because I don't have an 'unusual structure' - I'm just trying to run `tauri` from a level up from where is.. 'usual' 😉.

i.e. in bash `(cd subdir && tauri build/dev/info)` would do what I need, a tauri-cli arg would just be more convenient. (Especially since I don't use bash, and this sent me down a rabbit hole opening a fish issue too 😄.)

**Comment by amrbashir** [comment]
would love to hear more of your suggestions over at the PR.
