### ISSUE TITLE
Open new window from inside my app

### ISSUE THREAD

**Issue by rdwnsjjd** [tauri-apps/tauri#2846]
Hi
How can I open a new window from my application?
For example, I want to click on a button and then opens a new window with its configuration in size and ...

How it is possible?

**Comment by FabianLars** [comment]
in javascript: <https://tauri.studio/en/docs/api/js/classes/window.webviewwindow/> -> use the mentioned `WindowOptions` object for initial configuration.
in rust: https://docs.rs/tauri/1.0.0-beta.8/tauri/struct.AppHandle.html#method.create_window (`App` and `Window` provide the same method).

Also a more real-world-ish example: https://github.com/tauri-apps/tauri/tree/next/examples/multiwindow

**Comment by aleksanderjessitm** [comment]
Hello, 

In my code I have 

`@click="() => { return new WebviewWindow(((Math.random() + 1) * 10000).toString(), {
            url: 'https://somelink.com'
        })}"`
        
 ... and then nothing happens... I tried calling `show`, and it shows me that either the label is invalid or "it was closed". I tried adding a legit label; a unique one for sure, and nothing. 
 
 Do I need to go and write some Rust code to open a new window this way?

**Comment by FabianLars** [comment]
@aleksanderjessitm Try logging creation errors like shown here: https://tauri.studio/v1/api/js/classes/window.WebviewWindow and also check the console for errors. I suspect that it fails because of the `.` which Math.random returns, which is not allowed in labels (as mentioned in the linked docs).

**Comment by aleksanderjessitm** [comment]
Yup, that turned out to be the issue. The dot was the culprit, thanks!
