### ISSUE TITLE
Microsoft Edge WebView2 Runtime

### ISSUE THREAD

**Issue by rdwnsjjd** [tauri-apps/tauri#2847]
Why Microsoft edge webview2 runtime is required in windows to run my application??

is there a way to I don't have need to it when running my app?
If not, what does tauri use from Microsoft webview?

**Comment by FabianLars** [comment]
> is there a way to I don't have need to it when running my app?

No.

> If not, what does tauri use from Microsoft webview?

The WebView is basically the frontend rendering engine. for example, see https://docs.microsoft.com/en-us/microsoft-edge/webview2/ for an introduction.
So in short, no webview = no html/css/js.

**Comment by rdwnsjjd** [comment]
OK I got it. but I want to know which libraries is used by tauri in webview. so I want to determine which one is required by my app and I go and use it separately. because it's definitely not all of them required by my application.

**Comment by FabianLars** [comment]
@rdwnsjjd Sorry for the long delay.
I really have no idea how to answer this. The WebView2 _runtime_ is **not** a library (nor a collection of libraries).
It's kinda like asking "The website i visit doesn't use every feature my internet browser has, how do i install only the parts of Firefox that are used by that website?"

I hope this analogy helps.
