### ISSUE TITLE
api proxy pass

### ISSUE THREAD

**Issue by mgedgaudas** [tauri-apps/tauri#2853]
**Is your feature request related to a problem? Please describe.**
A lot of people building are used to web development and use the browsers fetch or other ja library (e.g. axios) to make api requests. So it would useful if people could simply reuse their code using fetch and have a proxy pass for the api (so we could avoid CORS) issues. 
At the moment I have a codebase that uses js fetch in electron but I cannot use it in tauri due to CORS (with auth).

**Describe the solution you'd like**
It would similiar to webpack api proxy [link](https://webpack.js.org/configuration/dev-server/#devserverproxy). I guess an alternative could be the ability to remove CORS restrictions in the webview like you can do it in electron (set websecurity to false).

**Describe alternatives you've considered**
I guess this could a plugin that runs a proxy server. Maybe some rust library exists for this and is easy to implement.

**Additional context**
tauri http is still not a full alternative as it doesn't support multipart forms and the file upload plugin only supports uploading files from path but not js File objects.

**Comment by lucasfernog** [comment]
The recommended way to bypass CORS is to use our HTTP API that goes through Rust. See [fetch](https://tauri.app/v1/api/js/modules/http#fetch).
