### ISSUE TITLE
Videos with small file size won't load from local file system

### ISSUE THREAD

**Issue by rafma0** [tauri-apps/tauri#2854]
### **Describe the bug**
Videos with small file size won't load from local file system

### **To Reproduce**
I encoded the same video with different sizes from 18mb to 75kb and the two smallest ones won't load with the html5 video player
https://drive.google.com/u/0/uc?id=1DooRCgDgyFh45kbfl0XohAcErNVfwQ6r&export=download

It seems to be related to the headers from the local assets server

When I try to load for example the file '5.mp4' (74kb) from the local disk, using something like
```
<video>
  <source src="https://asset.localhost/e:/my/video/5.mp4" type="video/mp4" />
</video>
```
the server replies with
```
content-length: 409600
content-range: bytes 0-409599/75990
Content-Type: video/mp4
```
and the video gets stuck

but when I load the same file from a nginx server to the same tauri app the reply is
```
Content-Length: 75990
Content-Range: bytes 0-75989/75990
Content-Type: video/mp4
```
and everything works fine

### **Platform and Versions (required):**

```
Operating System - Windows, version 10.0.22000 X64
Webview2 - 95.0.1020.44

Node.js environment
  Node.js - 16.4.2
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.18.1
  yarn - 1.22.10

Rust environment
  rustc - 1.56.1
  cargo - 1.56.0

App directory structure
/build
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self' asset:
  distDir - ../build
  devPath - http://localhost:3000
  framework - React
```

**Comment by kimlimjustin** [comment]
Can confirm this bug here, the `4.mp4` and `5.mp4` don't want to load and the `preview` tab of the `network` tab on devtools say 
` Failed to load response data: No data found for resource with given identifier`.

![image](https://user-images.githubusercontent.com/61906684/142983058-f4d1c45e-87a2-4c90-8c1c-5fc8e518cdf2.png)


Should be something wrong with the encoding and decoding....

**Comment by lucasfernog** [comment]
It works on macOS. Can you try without the driver name (`e:/`)? for instance `https://asset.localhost//Users/you/5.mp4`.

**Comment by rafma0** [comment]
To add a little more info on the issue.. seems like the assets server is assuming 400kb is the minimum size for a video file or something, and thats whats causing the problems

Looking at the source I see 2 files with
```js
 if range.length > file_size / 3 {
  // max size sent (400ko / request)
  // as it's local file system we can afford to read more often
  real_length = 1024 * 400;
}
```

file 5.mp4 contains 75990 bytes and the server is replying on first request
```js
Content-Length: 409600 // 400kb?
Content-Range: bytes 0-409599/75990 // 0 to 400kb? - 1 / 74kb (file size)
Content-Type: video/mp4
```

**Comment by michelvocks** [comment]
I have the same issue but also noticed that even longer videos (e.g. ~2 minutes long) suddenly stop loading at 9-10 seconds. The video progress bar shows that there is more but the player is unable to play the video after ~9 seconds.

**Comment by lucasfernog** [comment]
@michelvocks if #3039 doesn't fix it, please open another issue.

**Comment by michelvocks** [comment]
@lucasfernog #3039 fixed it. Thanks a lot!
