### ISSUE TITLE
Running tauri application on windows 7

### ISSUE THREAD

**Issue by rdwnsjjd** [tauri-apps/tauri#2863]
I built my tauri app on windows 10 and now trying to run its exe on window 7. but it fails. just running a hanged empty window.
my development system info is :
```
yarn run v1.22.17
warning package.json: No license field
$ tauri info
 app:spawn Running "C:\Users\User\Desktop\EPP\EPP\node_modules\@tauri-apps\cli\bin\tauri-cli.exe tauri info" +0ms


Operating System - Windows, version 10.0.19041 X64
Webview2 - Not installed

Node.js environment
  Node.js - 16.13.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.0
  yarn - 1.22.17

Rust environment
  rustc - 1.56.1
  cargo - 1.56.0

App directory structure
/dist
/node_modules
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - ../dist

Done in 32.17s.
```

my windows 7 isn't development system and does not have nodejs and tauri and rust and etc. it's raw and I just install webview2 runtime and microsoft edge on it. when I run my exe just shows a transparent window.

**Comment by amrbashir** [comment]
Can you provide a minimal repro ? unresponsive window can have lots of reasons.

**Comment by uuxii** [comment]
webview2 .win7 not support transparent window.give it up.

**Comment by rdwnsjjd** [comment]
It fixed!
the problem was in transparent supporting in win7.

is there a solution for it? how can I have transparent window in win7?

**Comment by amrbashir** [comment]
are you running in win7 VM or actuall win7 machine ? 
Also try running Tao's transparent example on win7
```
git clone https://github.com/tauri-apps/tao
cd tao
cargo run --example transparent
```

**Comment by rdwnsjjd** [comment]
ok i will try it.
I use vm
question: what is different between tao and tauri and tao could be used singly?

**Comment by FabianLars** [comment]
@rdwnsjjd I'm gonna be lazy and just [quote](https://discord.com/channels/616186924390023171/807549941936816148/908460037389824050) Denjell from Discord:
> TAO is for making the window, menus, accelerators. WRY injects a webview into the TAO window. TAURI provides API, macros, bundler, updater and all the glue to make a final binary.

For more see here: https://github.com/tauri-apps/tauri/blob/next/ARCHITECTURE.md

**Comment by amrbashir** [comment]
Since webview2 doesn't support transparency on Windows 7, we automatically turned off transparency on Windows 7. You shouldn't get unresponsive windows anymore but your window won't be transparent on Windows 7.
