### ISSUE TITLE
[docs] How to properly target elements without using selectors, since the selectors will be minimized in production build.

### ISSUE THREAD

**Issue by frnco** [tauri-apps/tauri#2874]
When running tauri in Dev mode the console outputs a considerably flashy warning explaining that selectors should not be used, with the message:

> !!!DO NOT TARGET ELEMENTS WITH SELECTORS BECAUSE THE SELECTORS WILL BE MINIMIZED IN THE PRODUCTION BUILD!!!

I believe this helps new users with onboarding and definitely makes it a lot easier to figure out what caused problems when selectors are involved. I also think it's really nice that Tauri minifies the code BTW.

However, the message doesn't give any alternatives to selectors, and even after looking for more information about this in the docs I couldn't find any information about targeting elements, what works, what doesn't work, possible workarounds etc. Much to my relief, I haven't had any problems with that, but at first I was a bit worried that code written in https://www.mint-lang.com/ might not work in Tauri, and quite often I find myself unsure about how something should be coded since I don't have any information about how the minification of selectors is done and what is or isn't affected by that minification.

I believe it would be nice to add some info regarding this in either the Docs, the message that is displayed in the console, or both. Everything I've tried actually worked without any issues, to the point I started wondering if this only applied to very specific circumstances, but the fact that I didn't have any problems doesn't mean I wasn't worried about the message and confused by the lack of information. Any comments on the issue, even if incomplete, are welcome, as this issue is, in itself, and attempt to have more information about this in an easily accessible place, with a clear title, and including the full message, which I was quite careful about after spending quite a while using many possible words to search the issues and checking each and every result to make sure there wasn't any issue related to this.

**Comment by amrbashir** [comment]
what's your `tauri info`? I think you're using an old version.

**Comment by FabianLars** [comment]
Yeah, this has nothing to do with tauri. tauri doesn't minimize your frontend code at all. The message comes from mint: [source](https://github.com/mint-lang/mint/blob/master/src/compilers/top_level.cr#L227)

**Comment by frnco** [comment]
> Yeah, this has nothing to do with tauri. tauri doesn't minimize your frontend code at all. The message comes from mint: [source](https://github.com/mint-lang/mint/blob/master/src/compilers/top_level.cr#L227)
Seems it was my mistake. I did a lot of searching around in Tauri, but it never occurred to me that Mint might be the source of that message. Though in Mint's case there is more than enough information about how elements should be referenced so that pretty much solves it.

> what's your `tauri info`? I think you're using an old version.
Just for completeness though, and I believe I'm keeping myself updated:
```
Operating System - Arch Linux, version Rolling Release X64

Node.js environment
  Node.js - 16.8.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - Not installed

Global packages
  npm - 7.21.0
  yarn - 1.22.17

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/src-tauri
/tests
/i18n
/source
/FeatherIcons
/The Father (2020) [1080p] [BluRay] [5.1] [YTS.MX]
/assets
/dist

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist/
  devPath - http://localhost:3000/
package.json not found
```

Also, I'm fairly surprised at how fast this was answered. Good job!
