### ISSUE TITLE
Using await inside async command

### ISSUE THREAD

**Issue by The-Mr-L** [tauri-apps/tauri#2891]
hi, I am trying to use the async command but i cant make it work sadly, any tips? thank you
the DB struct  is sync
```
#[command]
pub async fn get_chart_data(inst: Instrument) -> Option<String> {
  DB.data.get_chart_as_string(inst).await // <- returns Option<String> and it takes self by ref
}
```
result 

   #[command]
   |   ^^^^^^^^^^ `*mut ()` cannot be sent between threads safely

It works if I do
```
#[command]
pub fn get_chart_data(inst: Instrument) -> Option<String> {
  tauri::async_runtime::block_on(DB.data.get_chart_as_string(inst))
}
```
but not ideal

**Comment by FabianLars** [comment]
Hmm more context and the whole compiler error message or better yet a minimal reproduction would be nice, especially since this isn't a tauri issue or bug, just normal rust 🤷 
You probably end up with the need for a Mutex (and most likely the one provided by tokio)

But again, this is a general rust question, so you might have a easier time (faster solution) by asking google. (Unless someone else here had the same "issue" recently and remembers what they had to change)

**Comment by lucasfernog** [comment]
it works with `block_on` because that runs your code on the current thread, while Tauri uses `async_runtime::spawn`, so your item must be `Send`.

**Comment by The-Mr-L** [comment]
Thank you guys, turns out that I had a Arc I forgot to clone, sorry :s but the error message was the whole thing I got. but good to know that async tauri::command might spawn a thread, since it uses tokio spawn internal or what?  and one more thing can you please in a couple of words tell me how doss tauri commands/emit work between js and rust, is it tcp ,ipc etc .

btw thanks for taking your time to put this project together, it is great..

**Comment by lucasfernog** [comment]
The async command uses `tauri::async_runtime::spawn`, which uses Tokio.
Tauri commands uses the webview's communication system, see [Linux](https://github.com/tauri-apps/wry/blob/3a6eefae66c41da0f09293911675cb3c094e58b5/src/webview/webkitgtk/mod.rs#L83), [Windows](https://github.com/tauri-apps/wry/blob/3a6eefae66c41da0f09293911675cb3c094e58b5/src/webview/webview2/mod.rs#L127) and [macOS](https://github.com/tauri-apps/wry/blob/3a6eefae66c41da0f09293911675cb3c094e58b5/src/webview/wkwebview/mod.rs#L275) source codes.
It has some limitations, forcing JSON serialization and deserialization, but we're working on alternatives (first one is [the HTTP interface](https://github.com/tauri-apps/tauri-invoke-http)).
