### ISSUE TITLE
System Tray dependency resolution?

### ISSUE THREAD

**Issue by jswhisperer** [tauri-apps/tauri#2892]
Hitting the same or similar issue when trying to use the system tray
`error: failed to run custom build command for `tauri-libappindicator-sys v0.1.2`

I read it might be a stale version of the beta so I tried upgrading my cargo.toml and borrowed some deps from Wry for good measure, it is like
```
[dependencies]
libc = "0.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "0.11.1", features = ["api-all", "system-tray"] }
cairo-rs = "0.14"
gio = "0.14"
glib = "0.14"
glib-sys = "0.14"
gtk = { version = "0.14", features = ["v3_22"] }
gdk = { version = "0.14", features = ["v3_22"] }
gdk-sys = "0.14"
gdk-pixbuf = { version = "0.14", features = ["v2_36_8"] }
tauri-libappindicator = { version = "0.1.2", optional = false }
x11-dl = "2.18"
libayatana-appindicator = { version = "0.1.6", optional = true }


[features]
default = ["tray", "custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
tray = ["tauri-libappindicator"]
ayatana = ["libayatana-appindicator"]
dox = ["gtk/dox"]

```

Caused by:
  process didn't exit successfully: `/home/ziggy/Sites/my-tauri-app/src-tauri/target/debug/build/tauri-libappindicator-sys-8d66f8fa8dba885f/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=appindicator3
  cargo:rerun-if-env-changed=APPINDICATOR3_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=APPINDICATOR3_STATIC
  cargo:rerun-if-env-changed=APPINDICATOR3_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=APPINDICATOR3_0.1_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=APPINDICATOR3_0.1_STATIC
  cargo:rerun-if-env-changed=APPINDICATOR3_0.1_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'libappindicator3 library not found!', /home/ziggy/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-libappindicator-sys-0.1.2/build.rs:6:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
`
Similar to https://githubmemory.com/repo/qdot/systray-rs/issues/47

I think my PKG_CONFIG is set correctly, but even after installing libappindicator-gtk3-devel the .pc file is not created,

I'm using Pop_os instead of vanilla Ubuntu

_Originally posted by @gregpalaci in https://github.com/tauri-apps/tauri/issues/928#issuecomment-968926635_

**Comment by FabianLars** [comment]
are these your actual project dependencies? Because if so your tauri version is almost a year old. So try upgrading your app to `1.0.0-beta.8` and see if that already fixes it.

**Comment by jswhisperer** [comment]
@FabianLars I actually had that as my dependency before but my editor gave me an X so I thought I'd also try what it suggested 
![image](https://user-images.githubusercontent.com/1177690/141850299-219ce155-fd9f-479f-a81a-327d34aaccd5.png)

**Comment by nothingismagick** [comment]
`1.0.0-beta.8` is the right one, @FabianLars is correct.

**Comment by FabianLars** [comment]
Yeah that's the crates.io extension ignoring beta versions

**Comment by lucasfernog** [comment]
Nothing we can do here, we'll release 1.0.0 soon though.
