### ISSUE TITLE
window config in rust

### ISSUE THREAD

**Issue by rdwnsjjd** [tauri-apps/tauri#2898]
I am trying to set window configuration from rust in tauri. 
I saw in your website [Through the Window in Rust](https://tauri.studio/en/docs/api/rust/tauri/window/struct.window/) but cannot understand what I must to do.

I cannot find any `.with_title` or `.with_decoration` in my rust source.

```
Operating System - Ubuntu, version 20.04 X64

Node.js environment
  Node.js - 14.18.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.15
  yarn - 1.22.17

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/dist
/src-tauri
/.vscode
/node_modules

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - ../dist
```

**Comment by FabianLars** [comment]
Where did you see the `.with_X` methods in the docs? Those are `tao` methods which are not exposed in `tauri`.
You need to use [Window](https://docs.rs/tauri/1.0.0-beta.8/tauri/window/struct.Window.html) or [WindowBuilder](https://docs.rs/tauri/1.0.0-beta.8/tauri/trait.WindowBuilder.html) and the methods they provide.

Example of WindowBuilder usage with `.create_window`: <https://github.com/tauri-apps/tauri/blob/next/examples/api/src-tauri/src/main.rs#L126-L134>

Edit: I'm gonna close this for now, feel free to reopen if you still need help (or ask away without reopening :D )
