### ISSUE TITLE
How to capture the click events on the context menu?

### ISSUE THREAD

**Issue by xuchaoqian** [tauri-apps/tauri#2918]
**Is your feature request related to a problem? Please describe.**
 It shows a context menu, when I right-click on a link element. And then I want to capture the click events on the context menu, but how to get this?

**Describe the solution you'd like**
It would be nice that tauri will emit some events if we click the items on the context menu.

**Additional context**
![image](https://user-images.githubusercontent.com/1064052/142230582-8ec4c50a-f032-42d3-9a5d-d04e80201c06.png)

**Comment by xuchaoqian** [comment]
We can get this by adding a "contextmenu" event listener on the document as following:

```
  document.addEventListener(
    "contextmenu",
    function (event) {
      alert("You've tried to open context menu"); //here you draw your own menu
      event.preventDefault();
      return false;
    },
    { capture: true }
  );
```

But it seems very inconvenient...

**Comment by amrbashir** [comment]
yeah the only way currently is to disable the context menu and make a custom one in HTML.

In the future we will add support for making native context menus.

**Comment by xuchaoqian** [comment]
Thank you for your quick response. Looking forward to the new feature.

BTW. how to show the Dev Tool programmatically if we custom the context menu now? It seems there is no such API to activate Dev Tool panel.

> yeah the only way currently is to disable the context menu and make a custom one in HTML.
> 
> In the future we will add support for making native context menus.

**Comment by amrbashir** [comment]
You can't show dev tools programmatically unfortunately (check tauri-apps/wry#287), However, you can still access it by pressing F12.

**Comment by xuchaoqian** [comment]
It does not work by pressing F12 unfortunately. // Run app by: cargo tauri dev

> You can't show dev tools programmatically unfortunately (check [tauri-apps/wry#287](https://github.com/tauri-apps/wry/issues/287)), However, you can still access it by pressing F12.

***cargo tauri info***
Operating System - Mac OS, version 11.6.0 X64

Node.js environment
  Node.js - 14.18.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.15
  pnpm - Not installed
  yarn - 1.22.17

Rust environment
  rustc - 1.56.0
  cargo - 1.56.0

App directory structure
/bin
/node_modules
/webpack
/public
/.git
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:9091
  framework - React
  bundler - Webpack

**Comment by amrbashir** [comment]
I think macOS has a different shortcut, maybe `Cmd + Option + C` or `Cmd + Option + I`

**Comment by xuchaoqian** [comment]
It still does not work. Anyway, thank you so much. 
I'll do some research for this later.

> I think macOS has a different shortcut, maybe `Cmd + Option + C` or `Cmd + Option + I`
