### ISSUE TITLE
Splashscreen fails to supprt angular

### ISSUE THREAD

**Issue by wanpeng2008** [tauri-apps/tauri#2930]
Sorry for the misleading title. I just checked my project and found it's not due to the external js. It may be related to the Angular support.
Below is a simple repo.
https://github.com/wanpeng2008/tauri-bug-2930
In this demo,
dist/main_window is a simple main window.
dist/splash_screen is a simple splashscreen.
dist/splash_screen_ng is built by angular. 
splash_screen_ng works well. You can check with a static web server, for example `npx http-server dist/splash_screen_ng`.

### **To Reproduce**
1. `cargo tauri build.` 
2. You can see the main window and splash screen are shown as expected. The js with type=module is OK
3. Modify tauri.conf.json, set splashscreen url to  dist/splash_screen_cn
"url": "splash_screen/index.html", => "url": "splash_screen_cn/index.html",
4. you can see the splash screen is blank.

### **Platform and Versions (required):**

```

Operating System - Mac OS, version 12.0.1 X64

Node.js environment
  Node.js - 17.1.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.2
  yarn - 1.22.5

Rust environment
  rustc - 1.56.1
  cargo - 1.56.0

App directory structure
/dist
/node_modules
/src-tauri
/.git

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - localhost:4200
```
```
Angular CLI: 13.0.2
Node: 17.1.0 (Unsupported)
Package Manager: npm 8.1.2
OS: darwin x64

Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1300.2 (cli-only)
@angular-devkit/core         13.0.2 (cli-only)
@angular-devkit/schematics   13.0.2 (cli-only)
@schematics/angular          13.0.2 (cli-only)
```

**Comment by xuchaoqian** [comment]
Would you like to create a minimal repo to reproduce this bug?

**Comment by amrbashir** [comment]
...and please fill out the issue template properly.

**Comment by FabianLars** [comment]
The problem is `<base href="/" />` in the ng index.html.
This breaks the imports of the scripts as it's not actually the base.
For example run `window.location.href` in the js console -> `"https://tauri.localhost/splash_screen_ng/index.html"` (or `"tauri://localhost/splash_screen_ng/index.html"` since you're not on Windows).

Removing the mentioned part makes the relative imports work again.

**Comment by wanpeng2008** [comment]
Great! It works for me. Should it be mentioned in the doc?

**Comment by wanpeng2008** [comment]
Further question: is it possible to set base href dynamically? 
I add the following scripts to the index.html:
```
  <base href="/">
  <script>
    var baseEle = document.getElementsByTagName('base');
    var baseHref = window.location.href.slice(0, -10); // remove 'index.html'
    baseEle.setAttribute('href', baseHref);
  </script>
```
Unfortunately, it doesn't work because the js code is not executed. 
In order to change the base, I should set the base href correctly at the beginning. :(
So what can I do to make it work?

**Comment by FabianLars** [comment]
> Should it be mentioned in the doc?

No, i don't think that's needed.

> So what can I do to make it work?

Don't use `base` at all lol or set it to the actual base href (/splash_screen_ng/).
But because this is not a tauri _issue_, the tauri-discord or actually the docs/discord of your frontend framework will be a better place for this (especially since i don't really know/understand your use case).
