### ISSUE TITLE
Tauri CLI wrapper (cli.js) does not work on Alpine Linux

### ISSUE THREAD

**Issue by torkleyy** [tauri-apps/tauri#2939]
### **Describe the bug**

The JS wrapper for the Tauri CLI downloads a prebuilt binary which does not work on Alpine Linux.

### **To Reproduce**

1. Set up an Alpine Linux Docker image with all build dependencies for Tauri ([example](https://github.com/torkleyy/crust-template/blob/a31e1948c577ae42b01c2d6f51a53c22218e0bcf/docker/tauri.dockerfile))
2. Use `@tauri-apps/cli` via `yarn tauri build`
3. The command fails without any error message - just exit code 1 returned

### **Expected behavior**

Any of the following would be fine:

* error with message "Tauri JS CLI does not work on Alpine - please use the `cargo tauri` command"
* build it from source on Alpine
* provide binaries for Alpine

### **Screenshots**

![image](https://user-images.githubusercontent.com/23152057/142924195-1d487c96-94f7-4435-95d5-68a5414550c8.png)

### **Platform and Versions (required):**

(`yarn tauri info` also fails, so here the output of `cargo tauri info`)

```
Operating System - Alpine Linux, version 3.14.3 X64

Node.js environment
  Node.js - 14.18.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.17.0
  yarn - 1.22.17

Rust environment
  rustc - 1.56.1
  cargo - 1.56.0

App directory structure
/public
/src
/src-tauri
/node_modules

App
  tauri.rs - 1.0.0-beta.8 (no lockfile)
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../public
  devPath - http://localhost:41471
  framework - Svelte
  bundler - Rollup

```

**Comment by FabianLars** [comment]
related "feature" request: #2421

**Comment by amrbashir** [comment]
The issue is that AlpineLinux uses musl and not gnu so our `cli.js` won't work because it is not build for musl target. your only option right now, is to build our `cli.rs` yourself and use it as `cargo tauri dev` instead of `yarn tauri dev`.

I am gonna mark this as duplicate and further discussion should be at #2421
