### ISSUE TITLE
[docs] How to sign Windows builds?

### ISSUE THREAD

**Issue by gardc** [tauri-apps/tauri#2943]
There is nothing in the docs about signing Windows builds even though Tauri configuration includes the following options:
`digestAlgorithm`?: string
_Specifies the file digest algorithm to use for creating file signatures. Required for code signing. SHA-256 is recommended._
`certificateThumbprint`?: string[] 
_Specifies the SHA1 hash of the signing certificate._
`timestampUrl`?: string[]
_Server to use during timestamping._

Documentation on signing Windows builds will be a must sooner or later if Tauri is to compete with other frameworks like Electron on production grade software. It would also be nice to get an explanation here in the comments if anyone knows how to set this up, as I could use the help.

**Comment by antoniotorres** [comment]
I'm also interested on this documentation. @gardc do you know if there is way to do it?

 I read it is possible using this tool from Microsoft: https://docs.microsoft.com/en-us/windows/win32/appxpkg/how-to-sign-a-package-using-signtool

**Comment by gardc** [comment]
@antoniotorres no, unfortunately, I haven't looked into it as I'll most likely be replacing Tauri since it isn't quite mature enough with features like this one.

**Comment by FabianLars** [comment]
Thanks to @ImmaZoni we now have that guide in place! <https://tauri.studio/docs/guides/bundler/sign-windows>

**Comment by mauroporras** [comment]
This is the most recent link: https://tauri.app/v1/guides/distribution/sign-windows
