### ISSUE TITLE
Pressing a html button causes app to reload

### ISSUE THREAD

**Issue by A1ex-N** [tauri-apps/tauri#2944]
I've created a form with a button, but when i press the button the whole app reloads. When i press the button i want Rust to read a file and return it's string content back to the JS side, but i get 
`` [TAURI] Couldn't find callback id 1291043842396012063135210161762121461161601721131711671145207208018476107 in window. This happens when the app is reloaded while Rust is running an asynchronous operation.``, but if i put the code to return the string in a DOMContentLoaded it works. How can i stop the app from reloading when i press a button?

**Comment by FabianLars** [comment]
Try setting the type of the button to "button" -> `<button type="button"></button>`.
Btw this is not a Tauri "issue", but a general html thing.

**Comment by A1ex-N** [comment]
> Try setting the type of the button to "button" -> `<button type="button"></button>`. Btw this is not a Tauri "issue", but a general html thing.

changing the button type to button didn't make any difference 😢

EDIT: I just noticed i can just add a click handler to a H1 (or any other element) and have it function perfectly fine. Weird how the button doesn't work the way a button should work. Oh well i'm not too worried about it.

**Comment by FabianLars** [comment]
~~Okay, then either provide a minimal reproducible example please or ask google yourself with the additional context/code you have (again this is no tauri issue so you should find stuff quite easily).~~ edit: GitHub mobile app is trash :)

**Comment by A1ex-N** [comment]
> Okay, then either provide a minimal reproducible example please or ask google yourself with the additional context/code you have (again this is no tauri issue so you should find stuff quite easily).

``<button type="button"></button>`` is actually working. I had another button with the same ID that was without type="button". Sorry for being dumb
