### ISSUE TITLE
Discord Invite link

### ISSUE THREAD

**Issue by jeff-hykin** [tauri-apps/tauri#2957]
Just a quick ping since I didn't see any issues about it.

Looks like the Readme and website link to the discord invite is broken.

**Comment by FabianLars** [comment]
They seem to work fine for me 🤔

**Comment by jeff-hykin** [comment]
Well now I'm able to both get the error and get the invite. Looks a Discord + FireFox issue.

From the docs online it takes me to
https://discord.com/invite/tauri

From the readme in the browser (FireFox mobile) it takes me to
https://discord.com/invite/SpmNs4S

Both of those result in this screen:
![Screenshot_20211125-085440__01.jpg](https://user-images.githubusercontent.com/17692058/143464022-e7367313-2459-46b1-99a7-1be72a3a462d.jpg)

Faking a desktop environment doesn't change either of them.

However, if I use Chrome, or if I open up the GitHub app, go to the readme from there, and select it then it opens up the Discord App and works 🤔

![Screenshot_20211125-085752__01.jpg](https://user-images.githubusercontent.com/17692058/143464051-6b0d50d9-47f7-4143-8c27-04409c73b6ec.jpg)
