### ISSUE TITLE
Error using playwright in Tauri

### ISSUE THREAD

**Issue by yizhiyan** [tauri-apps/tauri#2958]
Error using playwright for Tauri.
I only created the basic Tauri program, which cannot be compiled after import.

I first used playwright with Tauri for development, but unfortunately there was an error when I first introduced the package

https://tauri.studio/en/

```
const {webkit}=require("@playwright/test")
console.log(webkit)
```
The following is the error message
```
 ERROR  Failed to compile with 5 errors                                                                      下午2:12:48

These dependencies were not found:

* electron/index.js in ./node_modules/playwright-core/lib/server/electron/electron.js
* module in ./node_modules/pirates/lib/index.js, ./node_modules/stack-utils/index.js
* readline in ./node_modules/playwright-core/lib/server/electron/electron.js, ./node_modules/playwright-core/lib/utils/processLauncher.js

To install them, you can run: npm install --save electron/index.js module readline
Error from chokidar (D:\): Error: EBUSY: resource busy or locked, lstat 'D:\pagefile.sys'
```

**Comment by amrbashir** [comment]
The error seems to be something wrong with your bundling configuration and not Tauri related.

Anyhow Playwright is a Node.js library and Tauri doesn't use or ship a Node.js runtime so you can't use it with Tauri.

We have our pre-alpha tauri-driver to be used for e2e testing. check it here https://tauri.studio/en/docs/guides/webdriver/introduction .
