### ISSUE TITLE
Use version property from package.json instead of tauri.conf.json

### ISSUE THREAD

**Issue by TomTomB** [tauri-apps/tauri#2967]
**Is your feature request related to a problem? Please describe.**
Is there a way to use the version property inside the package,json instead of tauri.conf.json? I'm using [Changesets](https://github.com/atlassian/changesets) for versioning my packages in CI. And of cause changesets has no idea that there is an other version property to update during release inside tauri.conf.json. This should also apply to similar packages like Semantic Release. 

**Describe the solution you'd like**
The version number should be used from the package.json file, or at least there should be an option to do so (to make this a non breaking change). 

**Describe alternatives you've considered**
Manually updating this property isn't that great of an experience. Using a custom action to copy the version from package.json to tauri.conf.json and commiting that neither. That would lead to the version bump being made after the git tag.

**Comment by lucasfernog** [comment]
I'll implement this. I think it is a good addition.
