### ISSUE TITLE
fix(api.js): expose `fileDropEnabled` in `WebviewWindow` constructor

### ISSUE THREAD

**Issue by wesin** [tauri-apps/tauri#2968]
when i create a new WebviewWindow. the h5 drag & drop is not supported
```
    const webview = new WebviewWindow(e.id, {
      url: '/#/expDesign',
      center: true,
      title: e.name,
    });
    webview.once('tauri://created', function () {
      console.log('new window');
    });
```

but if i use navigate the page it works. 
```
  const openWebUrl = () => {
    navigate('/expDesign');
  };
```
so maybe thie fileDropEnabled is not suppert the multiwindos.

but my destination is to create a new WebviewWindow.
i have set the *fileDropEnabled:fase* in the *tauri.conf.json*

my enviroment is 
- win10
- "react": "^17.0.2",
- "@tauri-apps/api": "^1.0.0-beta.8",

**Comment by FabianLars** [comment]
> i have set the fileDropEnabled:fase in the tauri.conf.json

Actually, no you didn't. This property is set on a per-window basis, which means you'd have to set it inside the WebviewWindow constructor, but this property is indeed not exposed in JavaScript at the moment.
A workaround would be to create the window in rust where `file_drop_enabled` is available on the WebviewAttributes struct.
But it's a good idea to make this possible in JavaScript too, so I guess we'll change that (if possible).
