### ISSUE TITLE
Add overlay icon for applications and ability to change it programmatically. 

### ISSUE THREAD

**Issue by brys0** [tauri-apps/tauri#2969]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It would be nice to have an overlay icon that can be changed programmatically, such as discords ping overlay.  

**Describe alternatives you've considered**
There doesn't seem to be a way to live update the icon and have the OS reflect changes without using an overlay that supports it. 

**Additional context**
![image](https://user-images.githubusercontent.com/35676267/143593799-000de1e7-e5d0-4ec9-81ae-57ca7714210f.png)
https://docs.microsoft.com/en-us/windows/win32/shell/how-to-implement-icon-overlay-handlers

It appears both Windows and Linux support overlay icons, although I could only find docs relating to a Windows implementation.

**Comment by nothingismagick** [comment]
If you must ignore our template, please delete it. Or, better, close this issue and create a discussion

**Comment by amrbashir** [comment]
Just wanna confirm that overlay icons are little icons laid on top of the window icon in the taskbar, right ?

if so it should be an easy task. but it will only be for Windows, Linux or macOS won't be supported.

**Comment by FabianLars** [comment]
Yeah that's what we were talking about. Just like discord does if you get mentioned. (I don't know if it actually uses this or just has multiple icons, but yeah)

**Comment by amrbashir** [comment]
There is 2 possible ways to do this:

1. like @FabianLars mentioned is to have two Icons, normal and normal+overlay and switch between them using `window.set_icon`. This is the most simple way and only way to do so in Tauri v1 and personally I prefer this.

2. Implement Windows' native overlay icons but to be completely honest with you I **don't** want to do it for two reasons:
    1. It is not cross-platform while the other way is.
    2. if we even implement it, it won't be shipped until Tauri v2.

**Comment by xuchaoqian** [comment]
BTW, I found some useful libraries for this task(to generate the normal+overlay icon):
1) parse the icon file:  [https://docs.rs/ico/0.1.0/ico/](https://docs.rs/ico/0.1.0/ico/) or [https://docs.rs/icns/0.3.1/icns/](https://docs.rs/icns/0.3.1/icns/)
2) process the imgs in it: [https://github.com/image-rs/imageproc](https://github.com/image-rs/imageproc)

**Comment by amrbashir** [comment]
Alright, gonna go ahead and close this as it is possible to mimic it with `window.set_icon()`
