### ISSUE TITLE
Child webviews

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#2972]
**Is your feature request related to a problem? Please describe.**
I'm trying to create a browser. Tauri fits all my needs except that it hasn't support for webviews in windows. See for example [Electron's BrowserView](https://www.electronjs.org/docs/latest/api/browser-view).

**Describe the solution you'd like**
Webview support.

**Comment by FabianLars** [comment]
Duplicate of #2709.

**Comment by ghost** [comment]
Oh! Sorry. Forgot to check for duplicates.
