### ISSUE TITLE
`yarn tauri info` and `cargo tauri info` do not match when installing on an existing Yarn 3 repo

### ISSUE THREAD

**Issue by Jengamon** [tauri-apps/tauri#2977]
### **Describe the bug**
`yarn tauri info` and `cargo tauri info` give different information.

### **To Reproduce**
1. Create a new project with `yarn init -2`.
2. Install both the Cargo tauri crate and Yarn tauri CLI packaage.
3. Run `cargo tauri info`, then `yarn tauri info`.

### **Expected behavior**
I expected them to have the same behavior.

### **Screenshots**
`yarn tauri info` output on my machine:
```
Operating System - Windows, version 10.0.19043 X64

  Node.js - 16.13.0
  @tauri-apps/cli - 1.0.0-beta-rc.4

Global packages
  npm - 8.1.4
  yarn - 3.2.0-rc.6

Rust environment
  rustc - 1.56.1
  cargo - 1.56.0

App directory structure
*DIRECTORIES*

App
  tauri.rs - 1.0.0-beta.4 (no lockfile)
build-type - bundle
CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
distDir - ../dist
devPath - localhost:1234
```

`cargo tauri info` output on my machine:
```
Operating System - Windows, version 10.0.19043 X64
Webview2 - 96.0.1054.34

Node.js environment
  Node.js - 16.13.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - Not installed

Global packages
  npm - 8.1.4
  yarn - 3.2.0-rc.6

Rust environment
  rustc - 1.56.1
  cargo - 1.56.0

App directory structure
*DIRECTORIES*

App
  tauri.rs - 1.0.0-beta.4 (no lockfile)
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist
  devPath - localhost:1234
```

### **Platform and Versions (required):**

Using the `cargo tauri info` one, as it more closely reflects my package.json (although it's still wrong, b/c I *do* have @tauri-apps/api as a dependency)
```
Operating System - Windows, version 10.0.19043 X64
Webview2 - 96.0.1054.34

Node.js environment
  Node.js - 16.13.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - Not installed

Global packages
  npm - 8.1.4
  yarn - 3.2.0-rc.6

Rust environment
  rustc - 1.56.1
  cargo - 1.56.0

App directory structure
/.git
/.parcel-cache
/.vscode
/.yarn
/dist
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.4 (no lockfile)
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
```

### **Additional context**
None

### **Stack Trace**
N/A

**Comment by FabianLars** [comment]
This thing drives me crazy lol.
How exactly did you install the clis in step 2?

I really don't get why it happens btw.
So if you have cli@beta.10 in your package.json, yarn 1 is able to resolve that correctly and yarn 3 isn't, like wtf.
The only thing we can do that i know of is to unpublish the beta-rc packages from npm, but for that we don't meet the requirements...
Btw, the workaround for that is to specify the package version with an equal sign: `"@tauri-apps/cli": "=1.0.0-beta.10"` and run `yarn install` again

Edit: Also, this kind of errors (or most of them) should kinda fix themselves (hopefully) once the stable release is out.

**Comment by Jengamon** [comment]
oooh ok.

I worked around it by just using the cargo version.

I installed the clis the standard way, so
```sh
yarn add -D @tauri-apps/cli
cargo install tauri --version ^1.0.0-beta
```

**Comment by amrbashir** [comment]
It will be automatically fixed once the stable release is out. Please re-open if the issue persists then.
