### ISSUE TITLE
Invoke isn't working, with a "JSON error: missing field `__invokeKey`"

### ISSUE THREAD

**Issue by Jengamon** [tauri-apps/tauri#2980]
### **Describe the bug**
`invoke` is not working.

### **To Reproduce**
1. Create a command on Tauri, even an empty one.
2. Attempt to call that command, and open the console.
3. You should see 
```
JSON error: missing field `__invokeKey\`
```

### **Expected behavior**
I expected `invoke` to Just Work :tm:

### **Screenshots**
![image](https://user-images.githubusercontent.com/1479994/143819979-847367ac-0444-4da2-88f0-073f14c0993b.png)

### **Platform and Versions (required):**

```
Operating System - Windows, version 10.0.19043 X64
Webview2 - 96.0.1054.34

Node.js environment
  Node.js - 16.13.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - Not installed

Global packages
  npm - 8.1.4
  yarn - 3.2.0-rc.6

Rust environment
  rustc - 1.56.1
  cargo - 1.56.0

App directory structure
/.git
/.parcel-cache
/.vscode
/.yarn
/art
/dist
/music
/src
/src-tauri
/types

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
```

### **Additional context**
It might possibly have to do with parcel v2 and its tree shaking? but probably not idk. Because I'm using Parcel v2 and Yarn 3.

### **Stack Trace**
N/A

**Comment by FabianLars** [comment]
Yarn 3 doesn't like our beta/beta-rc versions (funnily enough, yarn 1 doesn't have that problem). You need to declare them with an equal sign,  like `"@tauri-apps/api": "=1.0.0-beta.8"` and `"@tauri-apps/cli": "=1.0.0-beta.10"` and then run `yarn install` again.

(iirc that error message indicates a version mismatch)

**Comment by Jengamon** [comment]
Now it spits out
```
(node:42068) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Downloading Rust CLI...
```
then stops whenever I run `yarn tauri *` where * is {dev, build, info} (surprisingly not deps)

**Comment by Jengamon** [comment]
Somewhere in my mad clean/install cycling, it updated and it works now! Can't use the yarn CLI for now, but that's a different issue. Thanks!

**Comment by FabianLars** [comment]
Yeah we have trouble downloading the rust based cli with yarn 2/3 with pnp, and i think that's not fixed on `next` branch either idk. Btw the deps and icon commands work because they don't invoke the rust cli (==still written in js).
