### ISSUE TITLE
Window option "center" puts the Window in between 2 Screens 

### ISSUE THREAD

**Issue by TomTomB** [tauri-apps/tauri#2981]
### **Describe the bug**
Using `"center": true` for my window inside tauri.conf.json does not respect if there are multiple screens (2 in my case). The window gets centered between the 2 screens at the bottom.  

### **To Reproduce**
1. Connect 2 screens
2. Set the "center": true property on your window config
3. Prob. use Mac OS (cant confirm on Windows)

### **Expected behavior**
Well, it should be centered on the primary display, not across all. 

### **Platform and Versions (required):**

```
Operating System - Mac OS, version 11.2.3 X64

Node.js environment
Node.js - 14.17.1
@tauri-apps/cli - 1.0.0-beta.10

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected character 't' while parsing major version number")', src/info.rs:323:53

I guess thats an other error running pnpm tauri info. 
I've just installed rust so that should be on latest.

pnpm 6.16.1 
```

**Comment by lucasfernog** [comment]
Closed by #4166, thanks for the report!
