### ISSUE TITLE
Tauri apps don't start on Windows 

### ISSUE THREAD

**Issue by nokola** [tauri-apps/tauri#2991]
### **Describe the bug**
1. I followed the instructions for Windows 10 to add tauri to existing project: https://tauri.studio/en/docs/development/integration#1-add-tauri-to-existing-project
2. I ran `yarn tauri dev` and could see my app working.
3. Per instructions above, ran `yarn tauri build`
4. Installed .msi 
5. Ran app and got error.

### **To Reproduce**
Steps to reproduce the behavior on Win10:
1. Add tauri to existing project
2. Make sure `yarn tauri dev` is working
3. Run `yarn tauri build`
4. Install .msi on windows
5. Run app

### **Expected behavior**
App shows up

### **Screenshots**
![image](https://user-images.githubusercontent.com/6869225/144123805-884271e8-5dd4-4341-9338-3c51df3ae16d.png)

### **Platform and Versions (required):**
```
PS D:\Repos\GitHub\scribefu> yarn tauri info
 app:spawn Running "D:\Repos\GitHub\scribefu\node_modules\@tauri-apps\cli\bin\tauri-cli.exe tauri info" +0ms


Operating System - Windows, version 10.0.19043 X64

Node.js environment
  Node.js - 14.16.0
  @tauri-apps/cli - 1.0.0-beta-rc.4
  @tauri-apps/api Not installed

Global packages
  npm - 6.14.11
  yarn - 3.0.2

Rust environment
  rustc - 1.56.1
  cargo - 1.56.0

App directory structure
/.firebase
/.git
/.vscode
/.yarn
/build
/dist
/docs
/node_modules
/scripts
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
build-type - bundle
CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
distDir - ../dist/web
devPath - http://localhost:8000/
```

Note: I have this in my package.json:
```
  "devDependencies": {
    "@tauri-apps/cli": "^1.0.0-beta.10",
    "chalk": "^4.1.2",
    "electron": "^16.0.2",
    "electron-builder": "^22.14.8",
    "listr": "^0.14.3",
    "vite": "^2.6.14"
  },
  "dependencies": {
    "@tauri-apps/api": "^1.0.0-beta.8"
  }
```

**Comment by FabianLars** [comment]
Hmm, tricky.
1) make sure the distDir is correct and there's an index.html file inside.
2) Specify the versions for tauri's api and cli with an equal sign (fe: `"@tauri-apps/cli": "=1.0.0-beta.10",`) and run `yarn install` again. I don't know why, but yarn 3 doesn't like our beta versions (yarn 1 did resolve it fine...). Also you prob need to manually unplug the cli if you're using pnp, otherwise it can't download the actual cli binary as of this release.

If this doesn't change anything i think we'll need a minimal reproduction repo.

**Comment by nokola** [comment]
It was my bug! Sorry for the hassle and thanks for helping so quickly! I renamed `index.html` to `index1.html` in my `../dist/web` folder by accident - typo. Would be nice to show the error message e.g. "index.html not found" instead of "cannot connect to tauri.localhost", but low pri issue. Closing this bug.

Making sure my start file is `index.html` not `index1.html` fixed this.
