### ISSUE TITLE
Cant't listen event 'tauri://close-requested' or 'tauri://destroyed'

### ISSUE THREAD

**Issue by lity** [tauri-apps/tauri#2996]
![1](https://user-images.githubusercontent.com/3319045/144173208-033c260d-f645-46aa-9831-656e744298d6.jpg)

![2](https://user-images.githubusercontent.com/3319045/144173224-d31ce748-ce7d-40f4-a36a-c287b3b93e92.jpg)

I follow the guide of window.WebviewWindow ( https://tauri.studio/en/docs/api/js/classes/window.WebviewWindow ), everything is OK.
But if I change the event from 'tauri://created' to 'tauri://close-requested' (or tauri://destroyed), the event handler won't be invoked.

What I want to do is to save working data and close other hidden windows after user click 'close' button of the main window.
I have tried listen 'tauri://close-requested' , ' tauri://destroyed' and set window.onbeforeunload, none of them works.

Please help.

**Comment by lity** [comment]
![1](https://user-images.githubusercontent.com/3319045/144174446-ef0ef116-abc2-4683-a19d-983fcfa4563e.jpg)

Listening events in setup method in Rust layer is OK, but I just wanna make it simple in Javascript layer.

**Comment by lity** [comment]
looking forward to next version

**Comment by barbalex** [comment]
me too (somehow these words sound inapropriate lately...)

**Comment by ghost** [comment]
For those who still struggle
```ts
import { window } from "@tauri-apps/api"
import { TauriEvent } from "@tauri-apps/api/event"

window.getCurrent().listen(TauriEvent.WINDOW_CLOSE_REQUESTED, () => {
  alert("Closing window and maybe saving some data :)")
})
```

**Comment by gugiserman** [comment]
> For those who still struggle
> 
> ```ts
> import { window } from "@tauri-apps/api"
> 
> window.getCurrent().listen(TauriEvent.WINDOW_CLOSE_REQUESTED, () => {
>   alert("Closing window and maybe saving some data :)")
> })
> ```

Unfortunately this is also not working for me. I have tried pretty much everything I could find in any of the docs and examples 😢 

I don't get any `WINDOW_CLOSE_REQUESTED`, `WINDOW_DESTROYED` or `beforeunload` when I run my app in fullscreen, for some reason.

If I make it windowed, it will trigger both from Cmd+W or by clicking at the red X button just fine.

I'm testing it fullscreen on macOS Big Sur. Any ideas?

**Comment by ghost** [comment]
> > For those who still struggle
> > ```ts
> > import { window } from "@tauri-apps/api"
> > 
> > window.getCurrent().listen(TauriEvent.WINDOW_CLOSE_REQUESTED, () => {
> >   alert("Closing window and maybe saving some data :)")
> > })
> > ```
> 
> Unfortunately this is also not working for me. I have tried pretty much everything I could find in any of the docs and examples cry
> 
> I don't get any `WINDOW_CLOSE_REQUESTED`, `WINDOW_DESTROYED` or `beforeunload` when I run my app in fullscreen, for some reason.
> 
> If I make it windowed, it will trigger both from Cmd+W or by clicking at the red X button just fine.
> 
> I'm testing it fullscreen on macOS Big Sur. Any ideas?

I'm on linux. Most likely you are listening to wrong window

**Comment by achamas-playco** [comment]
I'm using tauri 1.x and could not get the close request event to fire using any of the tauri api, so I found a work around:

Add this to your javascript side (mac):

```js
 window.addEventListener('keydown', (e) => {
    if (e.key === 'q' && e.metaKey) {
      e.preventDefault();
      // do some pre-closing stuff...
    }
  });
```

Works on the main window, should work on dynamically created ones too. The browser is good at interrupting keys if you let it.

**Comment by maverickchangithub** [comment]
**Tauri 2.0**
for those who encounter the similar problem:
1. check your permission, make sure you can destroy and close
```
{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "default",
  "description": "Capability for the main window",
  "windows": ["main"],
  "permissions": [
    "core:default",
    "opener:default",
    "core:window:allow-close",
    "core:window:allow-show",
    "core:window:allow-hide",
    "core:window:allow-destroy" // must-have, or onCloseRequested will not close the window
  ]
}
```
2. import the right function, all AI helper such as chagpt, deepseek or gemini are wrong.
```
import { Window } from '@tauri-apps/api/window';//attention captital W
const appWindow = new Window('main'); // you can specify the window by label , setting in tauri.conf.json
appWindow.onCloseRequested((event) => {
   //do your stuff such as clear data before close window or destroy window
});
```

took me 2 days ( i am new to Tauri, i love it
