### ISSUE TITLE
Build to other platform feature available?? Or only build on local system?

### ISSUE THREAD

**Issue by spirityy** [tauri-apps/tauri#3011]
**Is your feature request related to a problem? Please describe.**

My platform is MacOS, i wanna build app for windows. But i can not find msi/exe in target/bundle folder. I believe that was a common requirement.

**Comment by FabianLars** [comment]
Duplicate of #1334, #1114, #279 and probably more.
Short answer: Not really possible in the foreseeable future, you have to use something like GitHub Action or VMs for this.

**Comment by amrbashir** [comment]
cross-platform compilation is not possible atm but you can use docker, VMs or Github actions, checkout https://github.com/tauri-apps/tauri-action
