### ISSUE TITLE
Tauri not support `<input type='file'>` element ?

### ISSUE THREAD

**Issue by xxxNull** [tauri-apps/tauri#3014]
Hi,there.
I found html element **`<input type='file'>`** can't open select file dialog
Now time, i must use @tauri-apps/api dialog api manual open file dialog

Tauri can support this element ? or i must write Javascript code manual open ?

Thanks !

This is my env information:
---
Operating System - Mac OS, version 10.15.7 X64

Node.js environment
  Node.js - 17.0.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.0
  yarn - 1.22.17

Rust environment
  rustc - 1.56.1
  cargo - 1.56.0

**Comment by amrbashir** [comment]
refer to https://github.com/tauri-apps/wry/issues/305 once it is solved , it will be automatically available to tauri, hopefully
