### ISSUE TITLE
Expose config for enable/disable window shadow

### ISSUE THREAD

**Issue by sooxt98** [tauri-apps/tauri#3019]
Tauri window is casting extra ugly black shadow on text, its bad for widget developer and backdrop blur

![image](https://user-images.githubusercontent.com/13378059/144717664-2bbd474c-7e23-49f7-aec3-9c3776fd54aa.png)

![image](https://user-images.githubusercontent.com/13378059/144717698-8200d11c-dfb4-499c-b6dc-213a3f6a0396.png)

**Comment by amrbashir** [comment]
related to tauri-apps/tao#157

**Comment by amrbashir** [comment]
> Tauri window is casting extra ugly black shadow on text, its bad for widget developer and backdrop blur

~~As I explained on Discord, this is not something we control. This text and `backdrop-filter: blur` is controlled by the webview itself. If you can't disable this shadow using html/css, I doubt we have anything to do there.~~ I was wrong, disabling shadows on the window fixes this.

**Comment by amrbashir** [comment]
I made  https://github.com/tauri-apps/tauri-plugin-shadows to add shadows on Windows and macOS, until we implement it directly in the core codebase.

**Comment by lucasfernog** [comment]
I'm closing this issue since you can use the plugin from Amr now. Hopefully it will land into tauri core v2 :)
