### ISSUE TITLE
Again hang!

### ISSUE THREAD

**Issue by rdwnsjjd** [tauri-apps/tauri#3023]
duo to [this](https://github.com/tauri-apps/tauri/issues/3021#issue-1071389513) issue that closed, I tried the solution (using `useEffect` once) and it still hang. I even commented all other listeners for the best result but still have the problem. the window content still hangs.

this is code: 

```js
useEffect(() => {

        const new_log = listen('new_log', event => {
            let tmpData = {
                "step": currentStep,
                "allFilesCount": filesCount,
                "currentFileCount": count,
                "error": err,
                "warn": warn,
                "log": data.log
            }
            tmpData.log.push(event.payload.log);
            setData(tmpData);
        })

        return () => {
            new_log.then(() => "");
        };
        
    }, [])

```

and even remove all state updates: 

```js
useEffect(() => {

        const new_log = listen('new_log', event => {})

        return () => {
            new_log.then(() => "");
        };
        
    }, [])

```

in the best case, it has a lot of lags.
I don't think the problem be from code.

**Comment by rdwnsjjd** [comment]
I think the problem is when I update states and the component is rerendered.

**Comment by nothingismagick** [comment]
Please visit our discord to see if someone can help you there. As explained in the other issue this does NOT seem to be a tauri API issue.
