### ISSUE TITLE
Following Symlinks

### ISSUE THREAD

**Issue by emdax** [tauri-apps/tauri#3032]
Tauri seems to throw "error: failed to walk directory" when using symlinks 

To reproduce 
1. rm dist 
2. ln -s /my/app/somwhere/ dist
3. run Tauri
4. error: failed to walk directory

**Comment by medmin** [comment]
same here

**Comment by medmin** [comment]
I upgraded my rust version from 1.5.0 to 1.5.9 and it works now.

**Comment by amrbashir** [comment]
@medmin were you using a symlink for `distDir`? just wanna make sure before I close this issue.

**Comment by amrbashir** [comment]
It is probably better for you to just point to the real path of the symlink.
