### ISSUE TITLE
ReferenceError: Can't find variable: process

### ISSUE THREAD

**Issue by serkandemirel0420** [tauri-apps/tauri#3033]
Any import or require a library, like db,sqlite,etc results in error.

`import sqlite3 from 'sqlite3'` result : ReferenceError: Can't find variable: process

--------------------------

cargo tauri info

Operating System - Mac OS, version 12.0.1 X64

Node.js environment
  Node.js - 15.12.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.6.3
  yarn - 1.22.17

Rust environment
  rustc - 1.58.0-nightly
  cargo - 1.58.0-nightly

App directory structure
/dist
/node_modules
/public
/src-tauri
/.git
/.vscode
/data
/.idea
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:3000
  framework - Vue.js

**Comment by lucasfernog** [comment]
`sqlite3` is a Node.js module, so it tries to access the Node's `process` global variable. You could try our plugin instead: https://github.com/tauri-apps/tauri-plugin-sql

Any Node.js module won't work, you have to find a browser solution or try to use the native layer (either writing Rust code yourself or using our plugins).
