### ISSUE TITLE
The window title should be automatically modified according to document.Title.

### ISSUE THREAD

**Issue by qt06** [tauri-apps/tauri#3037]
I am a visually impaired person using screen reader.
Usually, I judge the application I am working on or the page I am viewing by viewing the window title of the application.
However, Tauri can't change the window title of the application at any time.
For example, if a new page is opened after clicking a link, Tauri will not automatically change the title of the application window to the title of the newly opened web page.
This is inconsistent with the behavior of ordinary browsers.
After the page of an ordinary browser changes, the window title will automatically change.
On the other hand, in ordinary applications, when a new window is opened or the contents of the window are all changed, the window title will also change.
Therefore, I suggest that Tauri can also change the window title automatically.
Although I know that Tauri can change the window title programmatically, not all developers will consider this problem.

**Comment by nothingismagick** [comment]
This is exactly the kind of use case that the tauri plugin architecture is there for. Tauri is not a browser, even if it does use webtech. I am on the exact other side of the boat here, I never want the route to change my window decoration...
