### ISSUE TITLE
Unable to build on macOS

### ISSUE THREAD

**Issue by Verequies** [tauri-apps/tauri#3038]
I am having issues building an app on macOS that builds perfectly fine on both Linux and Windows. I am compiling with the 'next' branch. It seems it is a dependency issue as I am receiving the following:
```
error: failed to select a version for the requirement `attohttpc = "=0.18.0"`
candidate versions found which didn't match: 0.17.0, 0.16.3, 0.16.2, ...
location searched: crates.io index
required by package `tauri v1.0.0-beta.8 (https://github.com/tauri-apps/tauri?branch=next#7b81e5b8)`
    ... which satisfies git dependency `tauri` of package `app v1.0.0 (/Users/verequies/Documents/test/src-tauri)`
Error: failed to build app
```
I've tried cleaning the build environment but nothing seems to work. Fresh builds on Linux and Windows work perfectly fine.

```
Operating System - Mac OS, version 11.5.2 X64

Node.js environment
  Node.js - 16.6.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.20.3
  yarn - 1.22.10

Rust environment
  rustc - 1.56.1
  cargo - 1.56.0

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - unset
  distDir - Set automatically by Vue CLI plugin
  devPath - Set automatically by Vue CLI plugin
  framework - Vue.js (Vue CLI)
  bundler - Webpack
```

**Comment by FabianLars** [comment]
Did you try running `cargo update` already? Also for things like this (or in general) don't ignore the issue template please...

**Comment by Verequies** [comment]
Ah didn't know you had to do a ```cargo update``` in the ```src-tauri``` directory.
Good to know, added to my build script. Thanks :)
Seems to work now, ended up deleting ```~/.cargo``` in my home directory to be sure.

**Comment by FabianLars** [comment]
Glad it worked!
`cargo update` is especially important if you switch from a released version to a git dependency (maybe the other way around too), because cargo doesn't update the git dependency and stuff automatically.

**Comment by Verequies** [comment]
Right yeah, I've used it for other projects, but just not with Vue CLI before.
Thanks again for the information :)
