### ISSUE TITLE
Resizing frameless windows is difficult on high-DPI displays due to very small click targets

### ISSUE THREAD

**Issue by dannymcgee** [tauri-apps/tauri#3040]
### **Describe the bug**
Resize targets are extremely small and difficult to hit on high-DPI screens with `decorations: false`. This issue does not occur with `decorations: true`, nor on a typical 1080p display.

### **To Reproduce**
1. Bootstrap a minimal Tauri app with these window settings:
    ```json
    "windows": [
      {
        "decorations": false,
        "resizable": true,
        ...
      }
    ]
    ```
2. Start the app on a high-DPI display (e.g., 4k resolution)
3. Attempt to resize the window, observe the difficulty in "finding" the window edges with your mouse cursor

### **Expected behavior**
Resizing behavior should be roughly similar to the native OS behavior — i.e., there should be some wiggle room in where you may place the mouse cursor to initiate a window resize

### **Screenshots**
I don't have any desktop recording software installed currently, but let me know if this would be helpful.

### **Platform and Versions (required):**

```
# NOTE: I'm on Windows 11 -- not sure if this version info is wrong
# or if that's just the internal Microsoft representation of Windows 11 versions

Operating System - Windows, version 10.0.22000 X64
Webview2 - 96.0.1054.43

Node.js environment
  Node.js - 14.17.0
  @tauri-apps/cli - 1.0.0-beta.10

Global packages
  npm - 6.14.13
  yarn - 1.22.5

Rust environment
  rustc - 1.56.1
  cargo - 1.56.0
```

### **Additional context**
It feels like the resize handles are set to one physical device pixel instead of one logical/scaled pixel (though with the native decorations, the resize handles are even more forgiving — maybe 3 or 4 logical pixels).

I'm also seeing some flickering of the cursor graphic when I do hit the target — it rapidly alternates between the standard pointer and the resize pointer when I slide the cursor along a resizable edge — but it's still fairly obvious when I'm in the correct "zone" and I haven't been able to initiate a resize when the standard pointer is displayed, so I don't think this is just an issue with the cursor graphic.

**Comment by amrbashir** [comment]
I have increased the resizing border in https://github.com/tauri-apps/tao next branch, it will be available in the next release. it went from 3px to 5px, Once the release is out, please test it and if that's no enough, please re-open this issue.

**Comment by idlist** [comment]
It is still very small in my opinion... As I'm using a '13 Windows laptop with 4k resolution (3840*2400 in detail), I currently set the DPI scaling to 250%, and current room for resizing is like only half or even 1/3 of a framed window.

I feel like that simply increasing the resizing border in pixel does not solve the problem. I agree it would be better if the room could be variable according to the DPI scaling factor.

**Comment by amrbashir** [comment]
good idea, please open an issue at tao
