### ISSUE TITLE
GPU APIs

### ISSUE THREAD

**Issue by aleksey-hoffman** [tauri-apps/tauri#3042]
Hey guys, Is it possible to add APIs for the following:

- Get the list of GPUs
- Get specified GPU info
- Set active GPU for the app

The ability to **set active GPU** would be useful in many use cases, one of which is to reduce RAM usage when displaying large images and especially high res videos, which takes a lot of RAM when the app is running on the integrated GPU.

I'm in the process of choosing the framework for my next big app and I'm trying to figure out if Tauri is a good candidate for it.

**Comment by FabianLars** [comment]
1\. and 2. sound more like a feature (request) for https://github.com/GuillaumeGomez/sysinfo 🤔 

(No idea about 3. but sounds like somewhat out of scope _imo_)

**Comment by aleksey-hoffman** [comment]
@FabianLars thanks for the link, though it seems like this particular module doesn't provide GPU info.

Electron.js provides Chromium flags that allow you to specify active GPU, however they are not supported on Windows and cannot be used to change active GPU on the fly without reloading the app

**Comment by FabianLars** [comment]
> it seems like this particular module doesn't provide GPU info

Yes exactly, i meant that it'd be a nice feature to add in that project instead (because it fits in there better).

If it doesn't work in electron on windows then we're probably out of luck here anyway, because windows is the only platform where we run on chromium. I doubt that webkit supports this kind of stuff.

**Comment by JonasKruckenberg** [comment]
> If it doesn't work in electron on windows then we're probably out of luck here anyway, because windows is the only platform where we run on chromium. I doubt that webkit supports this kind of stuff.

I have no experience with separate gpus on macos, but from my research you can on toggle it system-wide?
Anyway, I see a neat tauri plugin for 1. and 2. 😉, but let's close this for now.
