### ISSUE TITLE
Nuxt SPA build issue

### ISSUE THREAD

**Issue by thetre97** [tauri-apps/tauri#305]
When using a SPA built with Nuxt, the site does not load correctly - it just shows a loading/error page, and a couple of errors appear in the console.
This happens using both `embeddedServer.active` `true` and `false`, as well as running the tauri app in dev mode, and ensuring the `build.devPath` points to a local server (I.e. [npm.im/serve](https://npm.im/serve)) running the exact same `dist` folder (although @nklayman said that [was not the case for him](https://discordapp.com/channels/616186924390023171/625037620996734986)).

The logs that appear are as follows:

`embeddedServer.active: true`
`SCRIPT5022: SCRIPT5022: Expected identifier, string or number`

`embeddedServer.active: false`
`HTML1507: Unexpected character: U+0000 NULL. Null characters should not be used.`

**To Reproduce**
1. Create a new project with NuxtJS, and make sure to select `spa` mode.
2. Build the project with `yarn build`, and either init tauri, or copy the dist folder to a tauri project.
3. Configure `tauri.conf.json` to use the `dist` folder as `distDir`.
4. Build the tauri project, and run it.

**Expected behavior**
The SPA site should load correctly inside the app, as happens with a usual VueJS app.

**Screenshots**
Loading/Error screen:
![image](https://user-images.githubusercontent.com/12587127/72166213-bd3f4880-33c0-11ea-9e77-8ef288239506.png)

**Platform and Versions:**

**Operating System** - Windows_NT(10.0.19541) - win32/x64   

**Node.js environment**
    Node.js - 13.5.0
    tauri.js - 0.3.1

**Rust environment**
  rustc - 1.40.0
  cargo - 1.40.0
  tauri-cli - 0.1.2

**Global packages**
  NPM - 6.13.4
  yarn - 1.21.1

**App directory structure**
/src-tauri

**App**
  tauri - 0.3.1
  mode - no-server
  build-type - bundle
  CSP - default-src res: blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  Windows - Edge
  distDir - dist
  devPath - http://localhost:5000

**Comment by nothingismagick** [comment]
we released v0.3.2 of tauri at crates yesterday - however that treated a different problem of the event API being improperly addressed in rust - so that probably won't have an impact here. I know @lucasfernog was going to look into a `basePath` issue. Maybe he has some more insight.

**Comment by lucasfernog** [comment]
I'm checking it tonight, I don't know how Nuxt dist works.

**Comment by lucasfernog** [comment]
Adding this to the `nuxt.config.js` file, it "works":

```js
build: {
    /*
    ** You can extend webpack config here
    */
    extend (config, ctx) {
      if (!ctx.isDev && ctx.isClient) {
        const tauriConfig = require('./src-tauri/tauri.conf.json')
        if (!tauriConfig.tauri.embeddedServer.active) {
          const TauriRequirePlugin = require('@tauri-apps/tauri-webpack/plugins/tauri-require').plugin
          config.plugins.push(new TauriRequirePlugin())
          console.log(config)
          config.output.publicPath = '_nuxt/'
        }
      }
    }
  }
```

now, it starts on a 404 page, but I can click on "Back to home page" and then it goes to the right page. Can you give me a hint on how can that happen? Maybe I didn't load the routes before Nuxt kicks in?

**Comment by lucasfernog** [comment]
Here's my work so far: #306

**Comment by nothingismagick** [comment]
@thetre97 - did you have a chance to circle back to this issue?

**Comment by thetre97** [comment]
@nothingismagick Just checking it out this evening, and I get the same as @lucasfernog.

Incidentally, if I leave `whitelist.all: true`, then clicking on a nuxt link (i.e. an `<a>` tag) the app navigates to the page, but also tries to open that same link in a browser (or opens the Windows 'how do you want to open this link' modal)... but everything seems to work if I change it to false. I'm guessing that is the `open` API?

![image](https://user-images.githubusercontent.com/12587127/72842152-b3a2c400-3c8f-11ea-8ee5-9e4556e051d3.png)

**Comment by thetre97** [comment]
Also just a note that using `build: { extractCSS: true }` does not work - the app loads, but has no styles.

**Comment by nothingismagick** [comment]
I'm closing this issue as stale, we've moved a lot recently. Please feel free to open a new issue if the problem persists.

**Comment by jswhisperer** [comment]
Did you have luck getting nuxt going with tauri @thetre97  ?
I was thinking of trying the nuxt generate, for the static mode maybe

**Comment by travis-r6s** [comment]
@gregbenner I haven't had reason to try it recently - but as said above, a lot has changed since.
Their discord is super helpful if you have any issues...
