### ISSUE TITLE
Error while installing tauri cli via cargo

### ISSUE THREAD

**Issue by mtvbrianking** [tauri-apps/tauri#3050]
### **Describe the bug**

I faced with the following error(s) when installing `tauri/cli` via Cargo.

- unresolved import `clap::crate_version`
- no `crate_version` in the root
- expected struct `App`, found `&yaml_rust::yaml::Yaml`

### **To Reproduce**

Steps to reproduce the behaviour:

```
cargo install tauri-cli --version ^1.0.0-beta
```

### **Expected behavior**

It should install successfully...

### **Screenshots**

![image_2021-12-09_12-01-05](https://user-images.githubusercontent.com/5412360/145367831-1204cf41-0027-494e-b3fb-45bce48da60a.png)

### **Platform and Versions (required):**

```
Operating System: Ubuntu 20.04

Node.js environment
Node.js: v14.18.2
@tauri-apps/cli: ___________
@tauri-apps/api: ___________

Global packages
npm: 6.14.15 
yarn: 1.22.17

Rust environment
rustc: 1.59.0-nightly (e6b883c74 2021-12-08)
cargo: 1.58.0-nightly (40dc28175 2021-12-06)
```

### **Additional context**

I'm trying to build [Graviton App](https://github.com/Graviton-Code-Editor/Graviton-App)

### **Stack Trace**

```
bmatovu@home-pc:graviton$ cargo install tauri-cli --version ^1.0.0-beta
    Updating crates.io index
  Installing tauri-cli v1.0.0-beta.7
  .
  .
  .
   Compiling tauri-cli v1.0.0-beta.7
error[E0432]: unresolved import `clap::crate_version`
 --> /home/bmatovu/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-cli-1.0.0-beta.7/src/main.rs:6:12
  |
6 | use clap::{crate_version, load_yaml, App, AppSettings, ArgMatches};
  |            ^^^^^^^^^^^^^ no `crate_version` in the root

error: cannot determine resolution for the macro `crate_version`
   --> /home/bmatovu/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-cli-1.0.0-beta.7/src/main.rs:265:14
    |
265 |     .version(crate_version!())
    |              ^^^^^^^^^^^^^
    |
    = note: import resolution is stuck, try simplifying macro imports

error[E0308]: mismatched types
   --> /home/bmatovu/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-cli-1.0.0-beta.7/src/main.rs:264:23
    |
264 |   let app = App::from(yaml)
    |                       ^^^^ expected struct `App`, found `&yaml_rust::yaml::Yaml`

Some errors have detailed explanations: E0308, E0432.
For more information about an error, try `rustc --explain E0308`.
error: failed to compile `tauri-cli v1.0.0-beta.7`, intermediate artifacts can be found at `/tmp/cargo-installsXqrl8`

Caused by:
  could not compile `tauri-cli` due to 3 previous errors
```

**Comment by FabianLars** [comment]
wtf cargooooo, don't do this to us.
For an explanation, clap released a new version yesterday (`3.0.0-rc.0`), which ~~removed~~ deprecated the yaml stuff and it looks like cargo selects that version instead of the specified `3.0.0-beta.2` (or beta.5 on `next` branch). Whyyy tho 😢
It doesn't to that for the beta versions btw (so beta.2 actually resolved to beta.2 instead of beta.5).

**Comment by FabianLars** [comment]
For now you can install the cli from a temporary branch like this: `cargo install tauri-cli --git https://github.com/tauri-apps/tauri --branch tmp/pin-clap`

**Comment by mtvbrianking** [comment]
@FabianLars the `tmp/pin-clap` has worked. Thanks a lot

**Comment by lucasfernog** [comment]
You can use `next` branch instead of `tmp/pin-clap` once we merge #2928.

**Comment by tylerchambers** [comment]
Just a heads up for future readers, `tmp/pin-clap` is now gone, use `next`.
