### ISSUE TITLE
println! now shows buffer instead of utf8

### ISSUE THREAD

**Issue by The-Mr-L** [tauri-apps/tauri#3056]
Hi, well now all my prints from rust is 
like <Buffer ... 24 more bytes>

and it is only when I am running the tauri app, I wonder if this is a problem in the Tauri frontend lib parsing the stdout ? 
I am using the latest version of all Tauri related crates/libs. and btw the dbg! macro works as expected. 
ofc I could try downgrade and I will if it is necessary. 

sorry if this is not a problem within Tauri , any suggestions are greatly appreciated. Thanks you

**Comment by amrbashir** [comment]
Can you show a code snippet? because your question is a bit confusing, what does rust println! and dbg! have to do with the frontend

Please don't ignore the issue template! It really makes it harder for us to help you out.

**Comment by The-Mr-L** [comment]
hey,  okay so println!  writes string to the stdout and I just dont know what else could be the issue other than some where tauri captures the stdout and shows it. since it only happens when the tauri app is running and it is all prints effected even prints from external crates .
this is the main fn

```
tauri::Builder::default()
    .setup(|app| {
      println!("running backend setup");
      Ok(())
    })
    .on_page_load(move |window, _| {
      println!("page loaded!");
    })
    .run(generate_context!())
    .expect("error while running tauri application");
```
I am on windows 10 and latest version of rust

**Comment by The-Mr-L** [comment]
now I tried letting the ui run for some time and I get this error, dont know if it is related. But it is the first time I see it as well.
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', C:\Users\xxxx\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-runtime-wry-0.2.1\src\lib.rs:1092:8

**Comment by lucasfernog** [comment]
What command are you running? `yarn tauri dev`? `<Buffer ...` sounds like Node.js to me, so that's where the issue might be.
Also, what's the output of `tauri info`?

**Comment by The-Mr-L** [comment]
hey amusing the vite-tauri-plugin which uses the cli vbeta.7  and  the tauri info returns

Node.js environment
Node.js - 14.18.1
tauri.js - 0.14.1

Rust environment
rustc - 1.57.0
cargo - 1.57.0
(node:4712) UnhandledPromiseRejectionWarning: TypeError: Invalid Version: latest.0.0
at new SemVer (C:\Users\xxxx\AppData\Roaming\npm\pnpm-global\5\node_modules\.pnpm\semver@7.3.4\node_modules\semver\classes\semver.js:38:13)
at compare (C:\Users\xxxx\AppData\Roaming\npm\pnpm-global\5\node_modules\.pnpm\semver@7.3.4\node_modules\semver\functions\compare.js:3:32)
at Object.lt (C:\Users\xxxx\AppData\Roaming\npm\pnpm-global\5\node_modules\.pnpm\semver@7.3.4\node_modules\semver\functions\lt.js:2:29)
at Object.semverLt (C:\Users\xxxx\AppData\Roaming\npm\pnpm-global\5\node_modules\.pnpm\tauri@0.14.1\node_modules\tauri\dist\api\info.js:223:29)
at printVersion (C:\Users\xxxx\AppData\Roaming\npm\pnpm-global\5\node_modules\.pnpm\tauri@0.14.1\node_modules\tauri\dist\api\info.js:343:16)
at C:\Users\xxxx\AppData\Roaming\npm\pnpm-global\5\node_modules\.pnpm\tauri@0.14.1\node_modules\tauri\dist\api\info.js:533:20
at step (C:\Users\xxxx\AppData\Roaming\npm\pnpm-global\5\node_modules\.pnpm\tauri@0.14.1\node_modules\tauri\dist\api\info.js:268:23)
at Object.next (C:\Users\xxxx\AppData\Roaming\npm\pnpm-global\5\node_modules\.pnpm\tauri@0.14.1\node_modules\tauri\dist\api\info.js:249:53)
at fulfilled (C:\Users\xxxx\AppData\Roaming\npm\pnpm-global\5\node_modules\.pnpm\tauri@0.14.1\node_modules\tauri\dist\api\info.js:240:58)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4712) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode).
(rejection id: 1)
(node:4712) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

**Comment by lucasfernog** [comment]
Hmm this CLI is super outdated.

**Comment by The-Mr-L** [comment]
ah okay so I guess @tauri-apps/cli is the one  I should use instead?

**Comment by The-Mr-L** [comment]
now I got this
Operating System - Windows, version 10.0.19044 X64
Webview2 - 96.0.1054.43

Node.js environment
Node.js - 14.18.1
@tauri-apps/cli - 1.0.0-beta.10
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected character 't' while parsing major version number")', src\info.rs:323:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
@tauri-apps/api - tauri-apps
app:spawn Command "C:\Users\xxxx\app\my_app\node_modules\.pnpm\@tauri-apps+cli@1.0.0-beta.10\node_modules\@tauri-apps\cli\bin\tauri-cli.exe" failed with exit code: 101 +0ms


but as I said, I use the tauri vite plugin which has a cli.exe shipped

**Comment by amrbashir** [comment]
@LambdaMan2K

1.  About `<Buffer>`, I believe it is because of my recent update to `vite-plugin-tauri`, so please open an issue there instead.
2. About `info` command failing the first time, I believe you have a very old alpha tauri cli installed globally and you used `pnpm tauri info` instead of `vite-tauri info`, you should uninstall the global cli `pnpm rm -g tauri`.
3. the second time `info` command failed with `@tauri-/cli` is because you used `pnpm` which have issues in the published version of the cli but is fixed in our `next` branch and will be available in the next release.
