### ISSUE TITLE
[feat] `Monitor::from_point` and `Monitor::cursor_position`

### ISSUE THREAD

**Issue by OceanBelongsToMe** [tauri-apps/tauri#3057]
### **Describe the bug**
I have two available monitor, and  I want to display the window on the current display，but the window.current_monitor() method does not seem to return the display screen where the mouse is located
It seems that the form always appears in the main display！
this is my code：
```
#[tauri::command]
fn register(app_handle: AppHandle, window: Window) {
  app_handle
    .global_shortcut_manager()
    .register("CTRL + U", move || {
      if window.is_visible().unwrap() {
        window.hide().unwrap();
      } else {
        println!("New version available: {:?}", window.available_monitors());
        window.center().unwrap();
        window.show().unwrap();
        window.set_focus().unwrap();
      }
    })
    .unwrap();
}
```
### **Platform and Versions (required):**

```
➜  power-clip git:(master) ✗ tauri info
 app:spawn Running "/Users/ocean/Documents/workplace/mystudywork/rust/github/tauri/tooling/cli.js/bin/tauri-cli tauri info" +0ms


Operating System - Mac OS, version 11.6.1 X64

Node.js environment
  Node.js - 16.13.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.0
  yarn - 1.22.17

Rust environment
  rustc - 1.57.0
  cargo - 1.57.0

App directory structure
/dist
/target
/node_modules
/src-tauri
/.git
/.idea
/src

App

  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:10001/
  bundler - Rollup
```

### **Additional context**
this is my monitors
```
Ok([Monitor { name: Some("Monitor #41012"), size: PhysicalSize { width: 2880, height: 1800 }, position: PhysicalPosition { x: 0, y: 0 }, scale_factor: 2.0 }, Monitor { name: Some("Monitor #30471"), size: PhysicalSize { width: 3840, height: 2160 }, position: PhysicalPosition { x: 0, y: -2160 }, scale_factor: 2.0 }])
```

**Comment by lucasfernog** [comment]
The [`current_monitor`](https://docs.rs/tauri/1.0.0-beta.8/tauri/window/struct.Window.html#method.current_monitor) API returns the monitor on which the window currently resides. It has nothing to do with where the mouse is located.

**Comment by OceanBelongsToMe** [comment]
Yeah, I looked at the api again, it is indeed the monitor where the form is returned, so there is no api that can return the position of the mouse?

**Comment by lucasfernog** [comment]
We do have it on `tao` and we could expose it here, but it wouldn't solve your problem since it doesn't give any information about the monitor of the mouse position.

**Comment by OceanBelongsToMe** [comment]
Can you expose that? Maybe I can calculate the relevant information from the mouse position and monitor coordinates :)

**Comment by amrbashir** [comment]
needs tauri-apps/tao#186 and tauri-apps/tao#187
