### ISSUE TITLE
File drop on specific HTML elements

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tauri#3063]
**Is your feature request related to a problem? Please describe.**
There's no easy way to handle file drops on specific elements yet. When you're dragging a file, JS events like `mousemove` stop emitting, so you can't tell where the cursor is (at least for me on macOS).

**Describe the solution you'd like**
The best solution would be for the native drag-and-drop API to work. Not sure what was preventing that from working?

Alternatively, `tauri://file-drop-hover` can include the mouse position and be spammed whenever the mouse moves. In JS, you could handle it like this:
```js
import { event } from '@tauri-apps/api';

const dropzoneElement = document.querySelector(/* ... */);

event.listen('tauri://file-drop-hover', (e) => {
  const hoveredElement = document.elementFromPoint(e.x, e.y);

  if (dropzoneElement.contains(hoveredElement)) {
    // ...
  }
});
```

**Comment by probablykasper** [comment]
Wry's FileDropEvent does include position: https://docs.rs/wry/latest/wry/webview/enum.FileDropEvent.html

**Comment by FabianLars** [comment]
Which means we can use it in tauri v2, or back port it to an older wry version for a possible future 1.X release.

**Comment by fanchenio** [comment]
Need mouse coordinates very much.
