### ISSUE TITLE
window.print() not working

### ISSUE THREAD

**Issue by ozws** [tauri-apps/tauri#3066]
### **Describe the bug**
window.print() not working

### **To Reproduce**
Click button that runs method that calls `window.print()`. Produces in terminal (iTerm2):
```
2021-12-14 13:59:05.771 app[97478:5179032] -[WryWebView printOperationWithPrintInfo:]: unrecognized selector sent to instance 0x7ff828e6cb40
fatal runtime error: Rust cannot catch foreign exceptions
```
Window immediately disappears and have to manually quit process in terminal.

### **Expected behavior**
Open print dialog to...

### **Platform and Versions (required):**
```
Operating System - Mac OS, version 10.14.6 X64

Node.js environment
  Node.js - 16.3.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.0
  yarn - 1.22.10

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/.git
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - Set automatically by Vue CLI plugin
  devPath - Set automatically by Vue CLI plugin
  framework - Vue.js (Vue CLI)
  bundler - Webpack
```

### **Additional context**
i see that printing is checked on issue [#544](https://github.com/tauri-apps/tauri/issues/544#issuecomment-607717471). Does that mean this feature is supposed to work?
[Amr sent me](https://discord.com/channels/616186924390023171/731495028677148753/920411904277610608)

i am not emotionally attached to `window.print()`, might there be alternatives?

**Comment by lucasfernog** [comment]
The API we use is only supported on macOS 11+, see https://developer.apple.com/documentation/webkit/wkwebview/3516861-printoperationwithprintinfo?language=objc

**Comment by ozws** [comment]
Ouch! Looks like i will never be able to print anything from a Tauri app on this computer then (running Mohave, can only go up one more to Catalina). 

Are there any known workarounds for older macOS versions?

My short term target is Windows 10. i DO get the print dialog there, so i am good for this immediate project. Sucks about macOS though.

Thanks Lucas

**Comment by Pierstoval** [comment]
Hey folks, having the same problem here on linux, but it's working on Windows, all with the latest (to date) version of tauri

<details><summary>Output of `yarn tauri:info` on windows:</summary>

```pre
yarn run v1.22.17
$ C:\dev\cacs-rg\node_modules\.bin\tauri info

Operating System - Windows, version 10.0.19044 X64
Webview2 - 99.0.1150.52
Visual Studio Build Tools:
   - Visual Studio Community�2019

Node.js environment
  Node.js - 16.14.0
  @tauri-apps/cli - 1.0.0-rc.6
  @tauri-apps/api - 1.0.0-rc.2

Global packages
  npm - 8.5.1
  pnpm - Not installed
  yarn - 1.22.17

Rust environment
  rustup - 1.24.3
  rustc - 1.59.0
  cargo - 1.59.0
  toolchain - stable-x86_64-pc-windows-msvc

App directory structure
/.git
/.github
/.idea
/bin
/docker
/node_modules
/public
/sample_data
/src
/src-tauri
/unit-test
/webdriver

App
  tauri - 1.0.0-rc.4
  tauri-build - 1.0.0-rc.4
  tao - 0.6.4
  wry - 0.13.3
  build-type - bundle
  CSP - default-src 'self' blob: data: filesystem: https: tauri: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist
  devPath - http://127.0.0.1:8080/
  framework - Vue.js (Vue CLI)
  bundler - Webpack
Done in 9.21s.
```
</details>

**Comment by lucasfernog** [comment]
@Pierstoval please file a separate issue with details on how it isn't working and what error are you seeing. This one is related to macOS only.

**Comment by lucasfernog** [comment]
@ozws there's no alternative for macOS unfortunately, only 11+ will have the window.print implementation.
