### ISSUE TITLE
JavaScript Examples

### ISSUE THREAD

**Issue by Antix-Development** [tauri-apps/tauri#3068]
Maybe I'm stupid, but I cannot seem to find any JavaScript tutorials for Tauri.

I'd really like to give it a try because electron is cumbersome to say the least but I'm not the worlds best coder so some tutorials would be fantastic :)

**Comment by amrbashir** [comment]
you can check the examples in the `examples` directory in the root of this repo. Once we release Tauri v1 stable we will be making Tutorials.

**Comment by Antix-Development** [comment]
Thanks, but there are no JavaScript examples from what I can see. Neutralino looks more promising at this point in time, thanks.

**Comment by amrbashir** [comment]
if by javascript examples, you mean javascript in the backend (main process) then no that's not possible currently, only Rust. In the future we will add support for many different bindings.

**Comment by Antix-Development** [comment]
Thanks for clearing that up for me. I'm already up and running with Neutralino now.
