### ISSUE TITLE
Bundling failed on Windows when the package product name contains Chinese characters

### ISSUE THREAD

**Issue by shenghan97** [tauri-apps/tauri#3081]
### **Describe the bug**
Bundling failed on Windows when the package product name contains Chinese characters. Building process was okay and binary was produced at target folder. The error was only at the bundling stage. 

### **To Reproduce**
1. Change package.productName in tauri.config.json to contain Chinese characters.
2. Build the app
3. See error

### **Screenshots**

![Screenshot 2021-12-16 020117](https://user-images.githubusercontent.com/8342250/146324441-03470927-3067-49b2-85db-a44cc360fff6.jpg)

### **Platform and Versions (required):**

```

Operating System - Windows, version 10.0.19042 X64
Webview2 - 96.0.1054.53
Visual Studio Build Tools - Not installed

Node.js environment
  Node.js - 16.13.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - Not installed

Global packages
  npm - 8.1.2
  pnpm - Not installed
  yarn - 1.22.17

Rust environment
  rustc - 1.57.0
  cargo - 1.57.0

Rust environment
  rustup - 1.24.3
  rustc - 1.57.0
  cargo - 1.57.0
  toolchain - stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)

App directory structure
/bin
/src
/test
/types

App
  tauri.rs - no manifest (no lockfile)
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../public
  devPath - http://localhost:5000/
  bundler - Rollup
```

### **Additional context**
tauri info says I don't have c++ build tools installed but in fact I do have them but the version is 2022. Not sure if it matters.

**Comment by FabianLars** [comment]
As far as I know, this is a wix limitation we can do nothing about.

**Comment by lucasfernog** [comment]
I think you need to change the Wix language: https://tauri.studio/en/docs/api/config#tauri.bundle.windows.wix.language

**Comment by xuchaoqian** [comment]
1）As @lucasfernog said,  set wix language: tauri > bundle > windows > wix >  "language": "zh-CN"
2)  Tauri uses Product Name as the Bundle Name. It will cause some weird problems in the not-ascii-characters-only case. We should rename the generated bundle name to an ascii-characters-only bundle name.

**Comment by shenghan97** [comment]
Thank you all!! Good to know where the problem is! I’ll try change wix language or avoiding non-ascii characters.
