### ISSUE TITLE
`Asset 'index.html' not found` error.

### ISSUE THREAD

**Issue by rdwnsjjd** [tauri-apps/tauri#3082]
Hi. I put my Tauri in my main app. I should say my tauri app is a GUI for my main app and it goes in a deployment folder inside my main app. there is a cargo.toml file in my project root that has member item and my deployment folder path is maintained there. as usual, it must be started when run cargo builds on project root and it did, but I got Asset 'index.html' not found; fallback to index.html error. what the wrong?

while I can run it without any error when I execute yarn Tauri dev in the deployment folder itself.

```
Operating System - Ubuntu, version 20.04 X64

Node.js environment
  Node.js - 14.18.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.3
  yarn - 1.22.17

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/src-tauri
/.vscode
/src
/node_modules
/.git
/public

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../src
  devPath - http://localhost:3000
  framework - React

```

**Comment by rdwnsjjd** [comment]
In fact, I can run app with `yarn tauri dev` but, cannot run it with `cargo run`

**Comment by FabianLars** [comment]
Copy from my discord message: you need to disable/remove the **default** feature for the custom protocol. Either by removing the `default = ...` line in cargo.toml or via `cargo run --no-default-features` or whatever else you can think of.

**Comment by Jampard** [comment]
Hello @FabianLars,
Thank you for your answer.
I get the same issue, as I am i'm trying to run a sidecar node app, that works as standalone.
 Removing the default line doesn't fix the issue, but removing the custom-protocol = [ "tauri/custom-protocol" ] line does make `cargo run` succesful. But I cannot build that way as i get an error.
Any ideas?
Many thanks!

**Comment by FabianLars** [comment]
@Jampard If you don't manually run it in a terminal, make sure you don't run it as `cargo run --all-features` (for example vscode/rust-analyzer has an option for this).
Otherwise check your configuration (devPath, distDir, window url).
If this doesn't help then i probably need more info or better yet a minimal reproduction.

**Comment by Farnsi** [comment]
Is it possible to disable the fallback?
I create a loader, that loads an URL, if not found, it loads another URL (theming, if file not found in theme dir, it uses default).
The fallback to .html make this not possible. Browser did not use a fallback.

**Comment by FabianLars** [comment]
> Is it possible to disable the fallback?

Nope, but feel free to open a feature request for this.

**Comment by fralonra** [comment]
Same issue, but with a different cause.

In my case, the `distDir` in `tauri.conf.json` was wrong. Corrected by changing `distDir` to where `index.html` actually locates.

For other's reference.

**Comment by SamMakesThings** [comment]
^ this fixed my issue 🙂 Thanks fralonra
