### ISSUE TITLE
icon is blurred

### ISSUE THREAD

**Issue by Archieeeeee** [tauri-apps/tauri#3085]
App icon is blurred on Windows for tauri.

The same icon file is used to attach:  tauri(left) , c#(right)
![image](https://user-images.githubusercontent.com/730816/146425212-d75e2533-92b6-45a4-8981-972fb5544e4f.png)

**Comment by amrbashir** [comment]
can you test it with tao ?
```sh
git clone https://github.com/tauri-apps/tao
cd tao
cargo r --example window_icon
```

**Comment by Archieeeeee** [comment]
> can you test it with tao ?
> 
> ```shell
> git clone https://github.com/tauri-apps/tao
> cd tao
> cargo r --example window_icon
> ```

I use the .ico file to test for tao:
the icon on the taskbar works well, but the icon on the titlebar seems using a bigger res and got downscaled

![image](https://user-images.githubusercontent.com/730816/146437322-bf2e68c2-2c96-4b0d-a866-c81682ec95c6.png)

I have uploaded the icon here:  https://drive.google.com/file/d/1iynr2UR208cBo-8eb0GYGRy6QQd8JMrx/view?usp=sharing

**Comment by amrbashir** [comment]
thanks for the detailed comparison, I will take a look at this as soon as I can.

**Comment by amrbashir** [comment]
Sorry to take this long, can you share your c# project? or at least tell me what is the dimensions you are using? or is visual studio handling this for you? are you using wpf, winforms, or uwp?

**Comment by lucasfernog** [comment]
I'm changing tauricon to output 32x32 ICO and I got much better results with your image.
[icon.zip](https://github.com/tauri-apps/tauri/files/9055258/icon.zip)

**Comment by lucasfernog** [comment]
Fix published in tauricon 1.0.3. Let me know if you still see any blurred icon.

**Comment by itsOdell** [comment]
still having blurred icons issue

**Comment by mitsukuri** [comment]
Make sure your icon is a multi-resolution .ico ideally containing 16x16, 20x20, 24x24, 32x32, 40x40, 48x48, 64x64, 96x96, 128x128 and 256x256 images (or at least 16×16, 32×32, 48×48, 256×256 if you don't strive for pixel perfection for every possible use case). You can create one using a very nice free utility, [Pixelformer](https://www.qualibyte.com/pixelformer/)
