### ISSUE TITLE
Uncaught (in promise) ReferenceError: __TAURI_INVOKE_KEY__ is not defined

### ISSUE THREAD

**Issue by Archieeeeee** [tauri-apps/tauri#3086]
### **Describe the bug**
this error only happens on build/build debug, it works fine on dev mode

### **To Reproduce**

start app, load a remote url, invoke command via tauri on web, the rust app does receive the command , but then webview can not get event 
data emitted from rust app

### **Screenshots**
![image](https://user-images.githubusercontent.com/730816/146609790-6f3a5ab7-7b88-42c3-9cb6-d596ebc49867.png)
![image](https://user-images.githubusercontent.com/730816/146621709-86400e08-586c-43ae-97f4-e8ddf15d8ea7.png)

### Platform
Windows
latest nodejs, tauri

### **Stack Trace**
```
Uncaught (in promise) ReferenceError: __TAURI_INVOKE_KEY__ is not defined
    at tauri-3147d768.js:15
    at new Promise (<anonymous>)
    at tauri-3147d768.js:15
    at tauri-3147d768.js:15
    at Object.next (tauri-3147d768.js:15)
    at tauri-3147d768.js:15
    at new Promise (<anonymous>)
    at r (tauri-3147d768.js:15)
    at i (tauri-3147d768.js:15)
    at tauri-fe7c6694.js:1
```

**Comment by amrbashir** [comment]
Can you make a minimal repro ? Also post full `tauri info` please.

**Comment by Archieeeeee** [comment]
Hello,
I have created a demo repo here:  https://github.com/Archieeeeee/tauridemo211218.git

tauri info
```

Operating System - Windows, version 10.0.22523 X64
Webview2 - 96.0.1054.57

Node.js environment
  Node.js - 16.13.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.2
  yarn - 1.22.15

Rust environment
  rustc - 1.59.0-nightly
  cargo - 1.58.0-nightly

App directory structure
/.git
/.vs
/dist
/icons
/node_modules
/server
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:3000
  framework - Vue.js

Done in 21.10s.
```

**Comment by amrbashir** [comment]
you have a weird project setup tbh and this is far from a minimal repro. If you can, please reduce this repro to bare minimum? Otherwise this gonna have to wait a bit.

**Comment by lucasfernog** [comment]
The `__TAURI_INVOKE_KEY__` is getting dropped on the next release.

**Comment by Archieeeeee** [comment]
quick fix for this: use ``window.__TAURI__.event.listen`` instead of calling `listen` directly

https://github.com/tauri-apps/tauri/issues/2383#issuecomment-896196627
