### ISSUE TITLE
build should exit if icons not found

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#309]
**Describe the bug**
If the icons can't be found (as described in `src-tauri/Cargo.toml` then the build should fail and explain why it failed.

**Comment by tensor-programming** [comment]
Some weird behavior with the bundler and how it handles mangled directories. Its something that I will need to look into further.  As it is now, if the cargo.toml doesn't have anything in the icon key and/or the icons folder is empty then the bundler fails to compile.
