### ISSUE TITLE
Auto updater dialog doesn't look good when the text is too long and the close button on the top right does not work

### ISSUE THREAD

**Issue by kimlimjustin** [tauri-apps/tauri#3099]
### **Describe the bug**
When running the auto-updater and if the text(description) is too long, the dialog doesn't look good and the close button on the top right does not work. In addition, right-clicking on the menu to close the app does not work, making the only way to close it is by killing via task manager.

### **To Reproduce**
1. Make a release which contains long text
2. Try the auto updater
3. Enjoy the bug :)

### **Expected behavior**
The ideal way is to make it scrollable

### **Screenshots**
![image](https://user-images.githubusercontent.com/61906684/147038609-f2c24f3f-729a-4b5d-b554-a226c7d6c209.png)

### **Platform and Versions (required):**

```
Operating System - Windows, version 10.0.22000 X64
Webview2 - 96.0.1054.62

Node.js environment
  Node.js - 16.0.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.4
  yarn - 1.22.17

Rust environment
  rustc - 1.56.0
  cargo - 1.56.0

App directory structure
/.git
/.github
/.husky
/.vscode
/api
/docs
/example
/lib
/node_modules
/out
/packages
/scripts
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src asset: blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../out/src
  devPath - http://localhost:8080
  bundler - Webpack
```

### **Additional context**
Already opened an issue on [rfd](https://github.com/PolyMeilex/rfd/issues/34)

**Comment by amrbashir** [comment]
`rfd` uses the win32 API `MessageBox` for its dialog and this type of dialog is meant for short messages. You probably better implement your own HTML dialog or just add a link to the full changelog.
