### ISSUE TITLE
[feat] Portable app release?

### ISSUE THREAD

**Issue by vanowm** [tauri-apps/tauri#3109]
### Describe the problem

Run application without installing

### Describe the solution you'd like

Is there a way create an app that doesn't require installation and can be run from a removable storage on any computer (assuming the same OS). On top of that any settings stored in the same directory as the executable?

For now I'm only interested in Windows OS.

**Comment by Archieeeeee** [comment]
Same question here, is it possible to use cargo build to release and it will be great if theres a guide to do so

**Comment by lucasfernog** [comment]
You could just ship the `.exe` file if you don't use resources or sidecars. But the user will need to have the Webview runtime installed, since our installer is responsible for managing it.

**Comment by vanowm** [comment]
And the settings?

**Comment by lucasfernog** [comment]
The only settings stored are the Webview ones, which can be customized with the [data directory](https://docs.rs/tauri/1.0.0-beta.8/tauri/struct.WebviewAttributes.html#method.data_directory).
