### ISSUE TITLE
[bug] Always on top not working on Wayland

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#3117]
### Describe the bug

When setting the window to be always on top, it's expected to never be behind any window. The same way browsers implement the behaviour of "Picture in Picture".

![a picture shown "always on top" failing](https://user-images.githubusercontent.com/23178554/147412853-dbef6d23-2f51-48e4-b430-0a501923a8ea.png)

Here we can see that the property is set to true **and** it stays behind the terminal. The same thing is true if I was to use `appWindow.setAlwaysOnTop(true)`.

### Reproduction

1. From a script in the main view invoke `WebviewWindow` with `alwaysOnTop` set to `true`;
2. Change focus to another window;
3. See the previous `WebviewWindow` not on top.

### Expected behavior

When setting the window to be always on top, it's expected to never be behind any window.

### Platform and versions

```shell
Operating System - Manjaro, version 21.2.0 X64
DE: GNOME 41.2 on Wayland
Kernel: 5.15.7-1-MANJARO
Node.js - 17.1.0
@tauri-apps/cli - 1.0.0-beta.10
@tauri-apps/api - 1.0.0-beta.8
vite - 2.7.7
```

**Comment by ghost** [comment]
When running `tauri info`, it panics:
```
➜  grudento git:(master) ✗ pnpm run tauri info

> grudento@ tauri /mnt/spare/dev/web/grudento
> tauri "info"

 app:spawn Running "/mnt/spare/dev/web/grudento/node_modules/.pnpm/@tauri-apps+cli@1.0.0-beta.10/node_modules/@tauri-apps/cli/bin/tauri-cli tauri info" +0ms


Operating System - Manjaro, version 21.2.0 X64

Node.js environment
  Node.js - 17.1.0
  @tauri-apps/cli - 1.0.0-beta.10
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected character 't' while parsing major version number")', src/info.rs:323:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  @tauri-apps/api - tauri-apps
 app:spawn Command "/mnt/spare/dev/web/grudento/node_modules/.pnpm/@tauri-apps+cli@1.0.0-beta.10/node_modules/@tauri-apps/cli/bin/tauri-cli" failed with exit code: 101 +0ms
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by ghost** [comment]
May be of interest:

There's this thing on Wayland:
![grafik](https://user-images.githubusercontent.com/23178554/147413067-260efcaf-6aaa-4dfe-8e2a-c7e7e04e9653.png)

"Immer in Vordergrund" -> "Always on top"

Firefox had an issue with PiP a while ago, but now it's fixed. Now, when the user activates PiP, it starts with "Always on top" active, like so:
![grafik](https://user-images.githubusercontent.com/23178554/147413131-e3628fb1-adeb-4c7d-a072-792104f2532f.png)

**Comment by amrbashir** [comment]
After a bit of research, a lot of resources seems to indicate that Wayland doesn't have an api for setting `alwayOnTop` so we don't have much choice but to wait for Wayland to add an api for it. 

Tauri uses gtk under the hood for Linux and gtk has a unified interface to interact with X11 and Wayland and currently we are calling [`gdk_set_keep_above`](https://gtk-rs.org/gtk3-rs/stable/latest/docs/gdk/struct.Window.html#method.set_keep_above) so once Wayland adds an api for `alwaysOnTop`, gtk will implement for the forementioned function and it will be automatically fix in tauri. 

Firefox workaround for PIP was to make the PIP window of type `dialog` which can't be used as a fix for Tauri.

**Comment by amrbashir** [comment]
I'll close this because there is nothing we can do about it. Once `wayland `adds an API to set `alwaysOnTop`, it will be automatically fixed on our end.
