### ISSUE TITLE
[bug] loading local assets which include url query strings via `tauri.convertFileSrc` fail to load

### ISSUE THREAD

**Issue by christian-schulze** [tauri-apps/tauri#3137]
### Describe the bug

The `asset` custom protocol implementation appears to treat URL query strings as part of the literal file path, so fails to load the asset.

I've tracked this down to [`core/tauri/src/manager.rs#323`](https://github.com/tauri-apps/tauri/blob/next/core/tauri/src/manager.rs#L322):
```rust
pending.register_uri_scheme_protocol("asset", move |request| {
  #[cfg(target_os = "windows")]
  let path = request.uri().replace("asset://localhost/", "");
  #[cfg(not(target_os = "windows"))]
  let path = request.uri().replace("asset://", "");
  let path = percent_encoding::percent_decode(path.as_bytes())
    .decode_utf8_lossy()
    .to_string();
  let path_for_data = path.clone();
 ...
```
I've been able to hack a temporary solution by using a regex to filter out the query string, the new code looks like this:
```rust
pending.register_uri_scheme_protocol("asset", move |request| {
  #[cfg(target_os = "windows")]
  let path = request.uri().replace("asset://localhost/", "");
  #[cfg(not(target_os = "windows"))]
  let path = request.uri().replace("asset://", "");
  let re = Regex::new(r"\?.*").unwrap();
  let path = re.replace_all(&path, "");
  let path = percent_encoding::percent_decode(path.as_bytes())
    .decode_utf8_lossy()
    .to_string();
  let path_for_data = path.clone();
```

### Reproduction

1. Use `yarn create tauri-app` to create a React app using Vite.
2. Create a local `index.html` file and `code.js` file.
3. Modify the `index.html` file to load the `code.js` file via a `script` tag, but append `?asdf` to the `src` attribute.
4. Modify the `code.js` file to log a message using `console.log`.
5. Modify the `App` react component to render an iframe which points to the `index.html` file, passing the path through `tauri.convertFileSrc`.

You *should* see the console.log message you added, but instead there is an error.

### Expected behavior

Files loaded into an iframe via `tauri.convertFileSrc` should be able to load their own assets which include url query strings.

### Platform and versions

```shell
Operating System - Arch Linux, version Unknown X64

Node.js environment
  Node.js - 16.11.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.3
  yarn - 1.22.17

Rust environment
  rustc - 1.57.0
  cargo - 1.57.0

App directory structure
/src
/node_modules
/src-tauri
/dist
/.idea

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:3000
  framework - React
```

**Comment by amrbashir** [comment]
why would you need to pass a url query to `convertFileSrc` ?

**Comment by christian-schulze** [comment]
@amrbashir I'm not doing it directly myself. I'm rendering an iframe using a url passed through `convertFileSrc`, its the contents of the iframe which contains other references to scripts which have query strings. Its those scripts within the iframe that are failing to load.

For more context, I am loading docset's normally used with [Dash](https://kapeli.com/dash) and [Zeal](https://zealdocs.org/).

**Comment by amrbashir** [comment]
I see, would you like to PR your solution ?

**Comment by christian-schulze** [comment]
Yes absolutely, will create a PR soon.
