### ISSUE TITLE
[feat] Auto-update from Github releases.

### ISSUE THREAD

**Issue by MaKleSoft** [tauri-apps/tauri#3139]
### Describe the problem

We're publishing all our builds to Github releases, so it would be great if the auto updater supported pulling updates through the Github api directly, without the need of a server component. [electron-builder](https://www.electron.build/auto-update) supports this out of the box and it's been incredibly useful.

### Describe the solution you'd like

Here is how electron builder does it: https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/providers/GitHubProvider.ts

Here the basic outline:

1. Get the [latest release](https://docs.github.com/en/rest/reference/releases#get-a-release-asset)
2. Get the list of attached [release assets](https://docs.github.com/en/rest/reference/releases#list-release-assets)
3. Look for a config file with a specific name. (i.e. update.json), which contains versions and urls to all download files. E.g.:
```json
{
    "version": "1.0.0",
    "windows": {
        "url": "[url to windows update file]",
        "checksum": "[checksum of windows update file]"
    },
    "macos": {...},
    "linux": {...} 
}
```
4. Check if the provided version is newer than the current version.
5. If version is newer, download appropriate update file for given platform.
6. Check checksum
7. Install update

**Comment by amrbashir** [comment]
We already support this, with and without a server. Check https://tauri.studio/en/docs/guides/updater#update-file-json-format

**Comment by MaKleSoft** [comment]
That's embarrassing... I guess next time I should read the docs more carefully. Thanks for the quick response!
