### ISSUE TITLE
[bug] macOS Fullscreen Menubar not appearing

### ISSUE THREAD

**Issue by lorenzolewis** [tauri-apps/tauri#3153]
### Describe the bug

When running a Tauri application in fullscreen on macOS, the top menu bar does not appear when moving the mouse to the top of the screen. In any application I'd expect it to "pull down" the menubar from the top of the screen.

### Reproduction

1. Create any app with Tauri
2. Run in fullscreen mode on macOS
3. Try to get the menubar to appear by moving the mouse to the very top of the screen (keep dragging up and "beyond" the screen for good measure)

### Expected behavior

The menubar should appear

### Platform and versions

```shell
Operating System - Mac OS, version 12.1.0 X64

Node.js environment
  Node.js - 16.13.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.0
  pnpm - Not installed
  yarn - 1.22.17

Rust environment
  rustc - 1.57.0
  cargo - 1.57.0

App directory structure
/test
/node_modules
/public
/src-tauri
/.git
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../public/
  devPath - INVALID DIR
  framework - Vue.js (Vue CLI)
  bundler - Webpack
```

### Additional context

This may be an issue with Tao instead of Tauri. I imagine there is some sort of gesture recogniser that is running and intercepting any mouse movements at the top of the screen. I don't think that macOS requires any custom implementation to handle this behaviour in an application, but can always do some research on the side.

**Comment by amrbashir** [comment]
Fixed in Tao's next branch. Use Tauri from git if you want that fix.
