### ISSUE TITLE
[feat] pnpm

### ISSUE THREAD

**Issue by Decodetalkers** [tauri-apps/tauri#3193]
### Describe the problem

when use create-tauri-app
pnpm create tauri-app, It use npm to install depencence

### Describe the solution you'd like

I hope it will use pnpm

**Comment by lucasfernog** [comment]
You can use pnpm using the `--manager` CLI option, e.g. `yarn create tauri-app --manager pnpm`.

**Comment by Decodetalkers** [comment]
> You can use pnpm using the `--manager` CLI option, e.g. `yarn create tauri-app --manager pnpm`.

```pnpm create tauri-app```
When I use this command, can it be default pnpm?

**Comment by amrbashir** [comment]
> ```pnpm create tauri-app```
> When I use this command, can it be default pnpm?

Next release of `create-tauri-app` will auto detect the package manager by checking an env var set by the package manager, but there is a bug in pnpm itself where it doesn't set that env var when using `pnpm create`.

For now and until pnpm fixes the bug, it is recommended to use `--manager` or `-m` flag

**Comment by vhscom** [comment]
Curious if there's a ticket PNPM is tracking so we can as well. Anway, there's some discussion about using NPM as a Node version manager so that seems potentially related. Here's the link: https://github.com/pnpm/pnpm/discussions/3434

**Comment by vhscom** [comment]
Curious if there's a ticket PNPM is tracking that bug. On a related note there's some discussion about using PNPM as a version manager for Node.js so that seems potentially related so I'll drop the link here for those looking to optimze DX around tooling integration: https://github.com/pnpm/pnpm/discussions/3434

**Comment by vhscom** [comment]
Curious if there's a ticket PNPM is using to track that bug. On a related note there's some discussion about using PNPM as a version manager for Node.js so that seems potentially related so I'll drop the link here for those looking to optimze DX around tooling integration: https://github.com/pnpm/pnpm/discussions/3434

**Comment by amrbashir** [comment]
here is the relevant pnpm issue https://github.com/pnpm/pnpm/issues/3985

**Comment by vhscom** [comment]
believe the blocking pnpm issue was just fixed. hopefully that means the env var will be available soon in `pnpm`? is there a good place to request an enhancement to drop the need for `-m` flag. i'll start poking around...

**Comment by vhscom** [comment]
believe the blocking pnpm issue was just fixed. hopefully that means the env var will be available soon in `pnpm`. is there a good place to request an enhancement to drop the need for `-m` flag for scaffolding with pnpm? i'll start poking around a little. ☺️

EDIT: it appears as if this gh tooling integration workflow might be a good entrypoint assuming i found a good spot for the work and a tdd workflow is desirable. not totally sure though i'm new to tauri. https://github.com/tauri-apps/tauri/blob/dev/.github/workflows/test-cta.yml

**Comment by amrbashir** [comment]
@vhscom yeah it is fixed in pnpm so users that use recent pnpm version will have the fix automatically, no need for more configuration or removal of `-m` flag.

By default, it will recognize the used package manager and can be overridden by `--manager` or `-m` flag.

**Comment by vhscom** [comment]
> By default, it will recognize the used package manager and can be overridden by `--manager` or `-m` flag.

It's a small but nice user affordance. And I appreciate it as PNPM is becoming my goto package manager for post-React apps built with Svelte. Thank you.

**Comment by FabianLars** [comment]
Yeah, many team members (myself included) are using pnpm as their main package manager already too!
