### ISSUE TITLE
[bug] `__cmd__perform_request` is defined multiple times

### ISSUE THREAD

**Issue by Borber** [tauri-apps/tauri#3198]
### Describe the bug

the name `__cmd__perform_request` is defined multiple times `__cmd__perform_request` must be defined only once in the macro namespace of this  with `#[tauri::command]`

### Reproduction

![image](https://user-images.githubusercontent.com/30563826/149076878-11e37809-c9fd-4033-9940-554da9b23ad9.png)

```rust
#![cfg_attr(
  all(not(debug_assertions), target_os = "windows"),
  windows_subsystem = "windows"
)]

use serde::Deserialize;

#[derive(Debug, Deserialize)]
pub struct RequestBody {
  id: i32,
  name: String,
}

#[tauri::command]
pub fn perform_request(endpoint: String, body: RequestBody) -> String {
  println!("{} {:?}", endpoint, body);
  "message response".into()
}

fn main() {
  tauri::Builder::default()
    .invoke_handler(tauri::generate_handler![
      perform_request
    ])
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}

```

### Platform and versions

```shell
Operating System - Windows, version 10.0.19044 X64
Webview2 - 97.0.1072.55
Visual Studio Build Tools - Not installed

Node.js environment
  Node.js - 17.3.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.3.0
  pnpm - 6.11.0
  yarn - 1.22.15

Rust environment
  rustc - 1.57.0
  cargo - 1.57.0

Rust environment
  rustup - 1.24.3
  rustc - 1.57.0
  cargo - 1.57.0
  toolchain - stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)

App directory structure
/.vscode
/dist
/node_modules
/public
/src
/src-tauri
```

**Comment by FabianLars** [comment]
I guess you figured it out because you closed it. But if someone else has a similar issue i'll answer anyway.
The problem here is the "pub" keyword on the command. Removing that will fix it. This is only a problem if the command and the `tauri::Builder` are in the same file.
For example, commands in a seperate file can be `pub` (with `pub(crate)` probably being a better choice)

**Comment by Borber** [comment]
> I guess you figured it out because you closed it. But if someone else has a similar issue i'll answer anyway. The problem here is the "pub" keyword on the command. Removing that will fix it. This is only a problem if the command and the `tauri::Builder` are in the same file. For example, commands in a seperate file can be `pub` (with `pub(crate)` probably being a better choice)

Yes, you are right

**Comment by dassio** [comment]
when I put the commands in  `lib.rs` with  `pub`, I got the same error.
> For example, commands in a seperate file can be pub (with pub(crate) probably being a better choice) 


how can I do this ? @Borber

**Comment by FabianLars** [comment]
@dassio the lib.rs and main.rs files are in the same scope, which is why you didn't need to manually import the commands from lib.rs. Anz other filename would work as expected (or don't make the command public if you just need it in tauri's Builder).

**Comment by anwarhahjjeffersongeorge** [comment]
> I guess you figured it out because you closed it. But if someone else has a similar issue i'll answer anyway. The problem here is the "pub" keyword on the command. Removing that will fix it. This is only a problem if the command and the `tauri::Builder` are in the same file. For example, commands in a seperate file can be `pub` (with `pub(crate)` probably being a better choice)

FYI This also seems to happen when with commands defined in the root `lib.rs` of a completely separate crate — *independently* of the presence of `tauri::Builder` in said crate. But the error resolves when the commands are defined in a sub-module of the separate crate.

**Comment by dassio** [comment]
>the lib.rs and main.rs files are in the same scope, which is why you didn't need to manually import the commands from lib.rs.

I got the private error with following code:
```
warning: `app` (lib) generated 1 warning
error: cannot find macro `__cmd__greet` in this scope
 --> src\main.rs:7:44
  |
7 |   .invoke_handler(tauri::generate_handler![greet])
  |                                            ^^^^^
```

main.rs
```
fn create_app<R: tauri::Runtime>(builder: tauri::Builder<R>) -> tauri::App<R> {
  builder
  .invoke_handler(tauri::generate_handler![greet])
  .build(tauri::generate_context!())
  .expect("error while running tauri application")
}

fn main() {  
    create_app(tauri::Builder::default())
    .run(|_app_handle, event| match event {
      tauri::RunEvent::ExitRequested { api, .. } => {
        api.prevent_exit();
      }
      _ => {}
    });
  }
```

lib.rs
```
#[tauri::command]
fn greet(name: &str) -> String {
    if name.len() == 0 || name.trim().len() == 0{
        return "please input your name".to_string();
    }
   format!("Hello, {}!", name)
}
```

**Comment by anwarhahjjeffersongeorge** [comment]
@dassio Maybe try modifying your lib.rs to have a separate module and add `pub` visibility to the command. I don't know if this is how it's meant to be done, but it worked for me:

lib.rs
```rust
pub mod commands;
pub use commands::*;
```

commands.rs
```rust
#[tauri::command]
pub fn greet(name: &str) -> String {
    if name.len() == 0 || name.trim().len() == 0{
        return "please input your name".to_string();
    }
   format!("Hello, {}!", name)
}
```

**Comment by kanyesthaker** [comment]
> FYI This also seems to happen when with commands defined in the root lib.rs of a completely separate crate — independently of the presence of tauri::Builder in said crate. But the error resolves when the commands are defined in a sub-module of the separate crate.

Any updates on this? it feels a bit silly to have a workspace crate with a empty lib.rs (sans re-exports) and a single module file that only exists because of this issue
