### ISSUE TITLE
[bug] create-tauri-app, svelte, default port 5000 unmatch with the rollup default 8080

### ISSUE THREAD

**Issue by Mr-Milk** [tauri-apps/tauri#3210]
### Describe the bug

When I run `yarn tauri dev`, the default port is running on 8080

<img width="248" alt="image" src="https://user-images.githubusercontent.com/23433306/149325147-a4fa94f9-bc43-40b8-8872-de9a67888ec2.png">

Which will give following result

<img width="597" alt="image" src="https://user-images.githubusercontent.com/23433306/149325292-67ca94a6-2f08-4815-a4aa-ff9395a25fe9.png">

At `tauri.conf.json`,
```json
{
  "build": {
    "devPath": "http://localhost:5000",
  },
}
```

When I change it to `http://localhost:8080`. Everything works as expected.

### Platform and versions

```shell
Operating System - Windows, version 10.0.22000 X64
Webview2 - 97.0.1072.55

Node.js environment
  Node.js - 16.13.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.0
  yarn - 1.22.15

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/.vscode
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../public
  devPath - http://localhost:5000
  framework - Svelte
  bundler - Rollup
```

**Comment by amrbashir** [comment]
Looks like the template is updated to use latest `sirv-cli` which is now defaulting to 8080, thanks for reporting this, it should be an easy fix.
