### ISSUE TITLE
[bug] The system cannot find the file specified.

### ISSUE THREAD

**Issue by iAkashPattnaik** [tauri-apps/tauri#3214]
### Describe the bug

I just installed tauri and created a new project with `npx create-tauri-app`.
I also have `Windows 11 SDK` and `C++ build tools (latest)` installed. (Only Node.JS, no Rust)
I don't know why, but whenever i run `npm run dev` which is "`tauri dev`", it show's me this -

```
Error: failed to build bundler settings

Caused by:
    0: `The system cannot find the file specified. (os error 2)`
    1: The system cannot find the file specified. (os error 2)
```

### Reproduction

1. Create a new project
2. `cd projectName`
3. Run `npm run dev` [`tauri dev`]

### Expected behavior

It should run the app according to the docs...

### Platform and versions

```shell
Operating System - Windows, version 10.0.22000 X64
Webview2 - 97.0.1072.55

Node.js environment
  Node.js - 16.13.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.4
  yarn - 1.22.17

Rust environment
  rustc - Not installed
  cargo - Not installed

App directory structure
/dist
/node_modules
/src-tauri

App
  tauri.rs - 1.0.0-beta.8 (no lockfile)
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - ../dist
```

**Comment by amrbashir** [comment]
You need to install rust, please follow the instructions on https://tauri.studio/en/docs/get-started/intro

**Comment by iAkashPattnaik** [comment]
> You need to install rust, please follow the instructions on https://tauri.studio/en/docs/get-started/intro

But it does state that installing Rust is completely optional !

**Comment by amrbashir** [comment]
where did you see that? please provide a link.

Rust is absolutely necessary atm. In the future, when we make bindings to other languages, it will be optional.

**Comment by iAkashPattnaik** [comment]
Ok, this made me a little confused...
[![image](https://user-images.githubusercontent.com/55914808/149471092-5c0cb9e5-a7df-46ea-9643-32713ba0b1d6.png)](https://tauri.studio/en/docs/get-started/setup-windows)
> It will be better if you use `&` instead of `/`.
<br>
<br>
<br>
<br>

## btw, I get this...
![image](https://user-images.githubusercontent.com/55914808/149471269-77176e45-0aaf-46f6-8643-1a2a74eb9843.png)
### but i do have these installed - 
![image](https://user-images.githubusercontent.com/55914808/149471322-8356e6a5-c11a-44e4-91e3-349088559cd3.png)

**Comment by amrbashir** [comment]
> Ok, this made me a little confused...
> [![image](https://user-images.githubusercontent.com/55914808/149471092-5c0cb9e5-a7df-46ea-9643-32713ba0b1d6.png)](https://tauri.studio/en/docs/get-started/setup-windows)
> > It will be better if you use `&` instead of `/`.

I guess we could just remove the words between the brackets. They are useless IMO. @lorenzolewis do you mind taking care of this ?

> ## btw, I get this...
> ![image](https://user-images.githubusercontent.com/55914808/149471269-77176e45-0aaf-46f6-8643-1a2a74eb9843.png)
> ### but i do have these installed - 
> ![image](https://user-images.githubusercontent.com/55914808/149471322-8356e6a5-c11a-44e4-91e3-349088559cd3.png)
> 

you need to install the `Desktop Development with c++` workload. I don't remember what exactly the individual components needed by rust but it is recommended to install the whole workload.
