### ISSUE TITLE
[bug] yarn tauri build : endless process

### ISSUE THREAD

**Issue by stloc** [tauri-apps/tauri#3216]
### Describe the bug

it gets stuck at this stage (no error) during hours

![image](https://user-images.githubusercontent.com/4832070/149480769-491fab35-7401-4884-9d09-c01419a23733.png)

### Reproduction

`yarn tauri build`

### Expected behavior

that building let it end !

### Platform and versions

```shell
On Windows 10

Operating System - Windows, version 10.0.19041 X64
Webview2 - 97.0.1072.55

Node.js environment
  Node.js - 17.0.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - Not installed

Global packages
  npm - 8.1.0
  yarn - 1.22.5

Rust environment
  rustc - 1.57.0
  cargo - 1.57.0

App directory structure
/node_modules
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../..
  devPath - http://xxxx
```
```

**Comment by FabianLars** [comment]
On first glance i'd say your distDir is the problem. `../..` has a really high chance that it includes source files, the node_modules dir and/or the target dir, which the bundler will all include into the binary. This will take a long time and depending on the size of these files might crash your system at some point.
The distDir is supposed to only include your dist files from your frontend (aka the build output if you have a bundler or just the plain html/js files if you go the vanilla route).

**Comment by stloc** [comment]
Thanks
