### ISSUE TITLE
[bug] Double-click data-tauri-drag-region to toggle "maximize" status of windows without decorations not working correctly

### ISSUE THREAD

**Issue by xuchaoqian** [tauri-apps/tauri#3220]
### Describe the bug

https://user-images.githubusercontent.com/1064052/149616848-202a63ab-2daf-4a1c-92b4-397aa580da9c.mov

### Reproduction

1. Checkout next brunch of tauri
2. Run API example
3. Click "Window" on the left sidebar
4. Uncheck "Has decorations" option
5. Double-click data-tauri-drag-region

### Platform and versions

```shell
Operating System - Mac OS, version 11.6.1 X64

Node.js environment
  Node.js - 14.18.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.15
  pnpm - Not installed
  yarn - 1.22.17

Rust environment
  rustc - 1.56.1
  cargo - 1.56.0

Rust environment
  rustup - 1.24.3
  rustc - 1.56.1
  cargo - 1.56.0
  toolchain - stable-x86_64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)

App directory structure
/dist
/node_modules
/public
/src-tauri
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: asset: customprotocol: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:5000/
  framework - Svelte
```

**Comment by amrbashir** [comment]
It should be working, can you try a simple app instead of the api example? it might be broken only in the api example.

**Comment by xuchaoqian** [comment]
> It should be working, can you try a simple app instead of the api example? it might be broken only in the api example.

[see this repo](https://github.com/xuchaoqian/tauri-examples/tree/main/create-webview-window)

### with decorations
https://user-images.githubusercontent.com/1064052/149647674-672d0b23-e000-4f40-bc4c-ee86ceb1a046.mov

### without decorations
https://user-images.githubusercontent.com/1064052/149647693-8ba61892-1262-4715-8d5d-946388286f9d.mov

**Comment by amrbashir** [comment]
thanks. we will look into this. might be an issue at Tao.

**Comment by lucasfernog** [comment]
@amrbashir can you check this one again or can I help somehow? I've seen this issue too.
