### ISSUE TITLE
Error when compiling with TS 4.5 and preserveValueImports enabled

### ISSUE THREAD

**Issue by max24192** [tauri-apps/tauri#3230]
When compiling my project with `"@tauri-apps/api": "^1.0.0-beta.8",`, webpack throws  three errors when compiling modules:

```
ERROR in /Users/m/Development/m2l_tina/node_modules/@tauri-apps/api/window.ts
88:9-18
[tsl] ERROR in /Users/m/Development/m2l_tina/node_modules/@tauri-apps/api/window.ts(88,10)
      TS1444: 'EventName' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.

ERROR in /Users/m/Development/m2l_tina/node_modules/@tauri-apps/api/window.ts
88:20-33
[tsl] ERROR in /Users/m/Development/m2l_tina/node_modules/@tauri-apps/api/window.ts(88,21)
      TS1444: 'EventCallback' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.

ERROR in /Users/m/Development/m2l_tina/node_modules/@tauri-apps/api/window.ts
88:35-45
[tsl] ERROR in /Users/m/Development/m2l_tina/node_modules/@tauri-apps/api/window.ts(88,36)
      TS1444: 'UnlistenFn' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.

3 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
```

The solution seems an easy fix, just separate 

https://github.com/tauri-apps/tauri/blob/c4bb305daeecaf4425eb63559a0ec85e0afd9a64/tooling/api/src/window.ts#L88

to

```
import { listen, once } from './event'
import type { EventName, EventCallback, UnlistenFn } from './event'
```

or the alternative version 

`import { type EventName, type EventCallback, type UnlistenFn, listen, once } from './event'`

**Comment by amrbashir** [comment]
this has been fixed and the next release won't ship ts files anymore.

**Comment by amrbashir** [comment]
Friendly reminder, use a proper issue template next time so we can have the needed information.

**Comment by max24192** [comment]
Where can I find the next release? In the `next` branch, the `window.ts` is still there as part of `api` and shows the same mixture of imports.

**Comment by amrbashir** [comment]
> Where can I find the next release? 

hasn't been published yet.

> In the `next` branch, the `window.ts` is still there as part of `api` and shows the same mixture of imports.

Our tsconfig is different than yours, so it compiles fine for us. In the next release, we will stop shipping ts files along the js files and this error will be gone on your end.
