### ISSUE TITLE
[feat] cli.js is out of date

### ISSUE THREAD

**Issue by chhpt** [tauri-apps/tauri#3231]
### Describe the problem

I install @tauri-apps/cli  v1.0.0-beta.10, but found that the dist is different with the content on github. Could you publish a new version of the cli.

### Describe the solution you'd like

Publish a new version of cli

**Comment by FabianLars** [comment]
Not until our feature freeze is over: #2060 / https://dev.to/tauri/tauri-feature-freeze-and-security-audit-1ml1
We will make some announcements about this and other stuff very soon. :eyes:

**Comment by amrbashir** [comment]
A new version will be published when it iis ready.
