### ISSUE TITLE
[feat] Setting title for dialog options

### ISSUE THREAD

**Issue by barbalex** [tauri-apps/tauri#3232]
### Describe the problem

I built an app that on startup connects to a database file (sqlite) on the internal network.

Without this database the app makes no sense.

The app knows the usual path to the database. Also, the user can choose an appropriate database file.

When the app starts up it looks for the last choosen database file. If it does not find it, it opens a dialog to let the user choose one.

As I can't set the title of the open dialog it is titled `Open`. This is not informative. The user is left to wonder what the app wants him/her to open. I want it to say `Choose the database file`.

The app was migrated from electron where the title of an open and save dialog can be set.

This feature would be useful in tauri too.

### Describe the solution you'd like

Add the ability to set a title in [the dialog options](https://tauri.studio/en/docs/api/js/interfaces/dialog.opendialogoptions/).

### Alternatives considered

I will probably have to open a ui dialog in the app that tells the user that after closing it he/she will be presented with a dialog to choose the appropriate database file.

This seems clunky. And is more work.

**Comment by JonasKruckenberg** [comment]
For file dialogs we use the [rfd crate](https://docs.rs/rfd/latest/rfd/index.html) but it seems like we just don't expose it yet. 
@lucasfernog any reason why we're using the blocking API here and not [`rfd::AsyncFileDialog`](https://docs.rs/rfd/latest/rfd/struct.AsyncFileDialog.html)? If not I'll tackle this while I'm at it.

**Comment by FabianLars** [comment]
@JonasKruckenberg We have to be careful about which thread we spawn the dialog from/on and using the async version may make this harder (or impossible)? idk. Also with that [thread stuff] i think the async version doesn't add much value here anyway.

**Comment by JonasKruckenberg** [comment]
> @JonasKruckenberg We have to be careful about which thread we spawn the dialog from/on and using the async version may make this harder (or impossible)? idk. Also with that [thread stuff] i think the async version doesn't add much value here anyway.

Yeah whatever, a question for another day 😄 I thought that the whole separate thread thing was just about not blocking the main thread, which the async api would solve. But you're right, maybe there are other reasons too.

**Comment by FabianLars** [comment]
yeah at least one OS needs it on the main thread or whatever, it's really weird and i'd had to dig up the convos from "back then" to get it right 😅

**Comment by JonasKruckenberg** [comment]
Yeah I can imagine that...
Anyway, the PR is ready for review! It has a bunch of failing tests that I can't reproduce though.

**Comment by barbalex** [comment]
You guys rock

**Comment by lucasfernog** [comment]
> For file dialogs we use the [rfd crate](https://docs.rs/rfd/latest/rfd/index.html) but it seems like we just don't expose it yet. @lucasfernog any reason why we're using the blocking API here and not [`rfd::AsyncFileDialog`](https://docs.rs/rfd/latest/rfd/struct.AsyncFileDialog.html)? If not I'll tackle this while I'm at it.

@JonasKruckenberg previously rfd had an issue with winit on macOS, I checked their README and it seems like that is fixed, so maybe we can use the async one now. Still, threading is really complicated when using native windows, as Fabian said, so I wouldn't touch it now.
