### ISSUE TITLE
[feat] mobile support ETA

### ISSUE THREAD

**Issue by Mohsen7s** [tauri-apps/tauri#3237]
### Describe the problem

Hello,
We have choose to develop our next project with tauri but currently it lacks support for mobile.
Is there any ETA for android support ? 

### Describe the solution you'd like

Even a unprecise ETA can help us to decide to start developing our projects with tauri or electron.

**Comment by lucasfernog** [comment]
We don't have an ETA yet, our current focus is on the first stable release. The Android implementation is still on the research phase, hopefully we can launch it this year though. Tag us on Discord if you think you can help :)
