### ISSUE TITLE
[docs] Link for State/StateManager is broken

### ISSUE THREAD

**Issue by despreston** [tauri-apps/tauri#3238]
I get a 404 when searching for state and clicking on the first result. This is the broken link:

https://tauri.studio/docs/usage/guides/command#accessing-managed-state

**Comment by amrbashir** [comment]
We did a bit of docs restructure recently. here is the correct link https://tauri.studio/docs/guides/command/#accessing-managed-state.

~~Where did you see this broken link?~~

Edit: oh just read your issue again, the search index will be updated soon.
