### ISSUE TITLE
[bug] Share and QRcode button Show tauri.localhost as a link - Will Not Work For Others

### ISSUE THREAD

**Issue by mucookul** [tauri-apps/tauri#3239]
### Describe the bug

Share and QRcode button Show tauri.localhost as a link you can copy but link will not work for other people

Fix 1: Make Share Text Update Link And Remove QRcode Button.
Fix 2: Remove both Share and QRcode button.

### Reproduction

1. Open Any Tauri App
2. Click Either Share Or QRcode Button.
3. In The Only Text Box Is "tauri.localhost"

### Expected behavior

Text Box Doesn't Have "tauri.localhost"

### Platform and versions

```shell
Operating System - Windows, version 10.0.19044 X64
Webview2 - 97.0.1072.62

Node.js environment
  Node.js - 17.3.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - Not installed

Global packages
  npm - 8.3.0
  yarn - Not installed

Rust environment
  rustc - 1.58.0
  cargo - 1.58.0

App directory structure
/App
/node_modules
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../App
  devPath - ../App
```

**Comment by nothingismagick** [comment]
Yeah, I guess I need more information and context about what it is that you are really trying to do. You want another device to connect to your app's host? Then you should probably ship a server with your app, figure out its IP address, and share that with the device. Is it on the same network? If so its easier. If not, then you'll have to figure out hole-punching via a relay service. This is all entirely out of scope of Tauri core, and potentially something that you could build with a plugin architecture.

**Comment by mucookul** [comment]
I mean that the tauri shoudn't show tauri.locahost by default for the links
