### ISSUE TITLE
[feat] Dark Right Click menus

### ISSUE THREAD

**Issue by mucookul** [tauri-apps/tauri#3240]
### Describe the problem

Make Right Click Menus Blend In With Dark Mode App

### Describe the solution you'd like

Make A Setting For Light or Dark Right Click Menus

### Alternatives considered

IDK

**Comment by probablykasper** [comment]
They're dark for me in macOS dark mode. What OS are you on?

**Comment by ar6104ra** [comment]
> They're dark for me in macOS dark mode. What OS are you on?

A custom 9
One
.

**Comment by mucookul** [comment]
> They're dark for me in macOS dark mode. What OS are you on?

Windows 10 and also I want this because Win 10 Dark Mode is Trash
