### ISSUE TITLE
[feat] Printing Clap Help 

### ISSUE THREAD

**Issue by onetonfoot** [tauri-apps/tauri#3250]
### Describe the problem

When my application is run with an incorrect subcommand I'm trying to print the help message, however, I can't find a simple way to do this.

### Describe the solution you'd like

The simplest thing would be something like `print_help(cli: &CliConfig)`  function. Something more flexible could be a way to get access to the underlying clap::App.

### Alternatives considered

I copied some code from `tauri::api::clap` to get access to the underlying `clap::App` object and then call the `print_help` method directly when a given subcommand doesn't match.

**Comment by amrbashir** [comment]
The error variant of `get_matches()` contains an error message along with the help message, so you can do something like this
```rs
match get_matches(&context, &package_info) {
	Some(matches) => {},
	Err(e) => println!("{}", e)
}
``` 
otherwise the `Some` variant will have the help message, just call `matches.get("help")`
