### ISSUE TITLE
[bug] `tauri build` doesn't create updater artifacts if bundle.targets is not set to `"all"`

### ISSUE THREAD

**Issue by Ludea** [tauri-apps/tauri#3251]
### Describe the bug

I would like to use updater, with dmg and msi and don't want Appimage binaries.
If I provided dmg and msi as target, with updater enable, updater assets are not created (archive and sig) 

### Reproduction

Enable updater
Provide target (dmg, msi)
Enable ci to build assets
Do a release
Look at release assets 

### Expected behavior

Platform binaries with their update assets
.msi, .msi.zip and sig for Windows target 

### Platform and versions

```shell
Operating System - Windows, version 10.0.22000 X64
Webview2 - 97.0.1072.62

Node.js environment
  Node.js - 16.7.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.20.3
  yarn - 1.22.5

Rust environment
  rustc - 1.56.0
  cargo - 1.56.0

App directory structure
/.git
/.github
/dist
/key
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist
  devPath - http://localhost:3000
  framework - React
```

**Comment by lucasfernog** [comment]
You need to add "updater" to the targets list. We'll document this.

**Comment by betamos** [comment]
Could be worth adding to https://tauri.app/v1/guides/distribution/updater/ as well. This one tripped me up.

**Comment by doroved** [comment]
> You need to add "updater" to the targets list. We'll document this.

```bash
Warning [tauri_bundler::bundle] The bundle was configured to create update artifacts, but no update-enabled targets were created. Please include one of these targets: app, appimage, msi, nsis
```

Tauri 2 installation `[“dmg”, “updater”]` does not work, error on startup.
```bash
Error [tauri_cli::helpers::config] `tauri.conf.json` error on `bundle > targets`: [“dmg”, “updater”] is not valid in any of the schemas listed in the 'anyOf' keyword
```
Do I have to use target - app even if I only need .dmg?

**Comment by FabianLars** [comment]
yes

**Comment by doroved** [comment]
> yes

If the `updater` option is obsolete, it might be worth removing here. Thank you.

```bash
bun tauri build -h 
```
<img width="917" alt="Image" src="https://github.com/user-attachments/assets/11847a2e-e92f-4397-85fb-4b489d56a74d" />
