### ISSUE TITLE
[bug] mktemp: too few X's in template

### ISSUE THREAD

**Issue by reggermont** [tauri-apps/tauri#3254]
Sorry if the issue is dumb, but I couldn't find another topic on it 

### Describe the bug

After building an AppImage and running it with `./tauri-test_0.1.0_amd64.AppImage`, I directly have a `mktemp: too few X's in template` error with a default tauri + react setup

### Reproduction

Run `tauri init` with a simple setup with React

Here's a custom Dockerfile I use to build the app
```
FROM debian:bullseye-slim

# Dev tools
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    libayatana-appindicator3-dev \
    libgtk-3-dev \
    librsvg2-dev \
    libssl-dev \
    libwebkit2gtk-4.0-dev \
    patchelf \
    wget

# Node
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get -y install nodejs

# Yarn
RUN npm install -g yarn

# Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Tauri
RUN cargo install tauri-bundler --force
RUN cargo install tauri-cli --git https://github.com/tauri-apps/tauri

RUN npm install --unsafe-perm -g @tauri-apps/cli

WORKDIR /root/app
```

And then running `docker run --privileged -it --rm -v $(pwd):/root/app tauri-test tauri build` to build the Tauri app

### Platform and versions

```shell
Operating System - Debian, version 11 X64

Node.js environment
  Node.js - 16.13.2
  @tauri-apps/cli - 1.0.0-beta.10

Global packages
  npm - 8.1.2
  yarn - 1.22.17

Rust environment
  rustc - 1.58.1
  cargo - 1.58.0
```

**Comment by FabianLars** [comment]
Yep, that's known. Well, at least to me so it's good that we have a reference issue for it now.
Anyway, the guys over at the linuxdeploy gtk plugin did an oopsie a few days ago. Luckily we switched over to our own fork on the `next` branch, which you want to use anyway if your aim is to _distribute_ the AppImages (appimages are pretty broken in general on the latest published cli version).
You're already installing it in your docker file so might as well use it via `cargo tauri build`. With that you can omit the global `@tauri-apps/cli` installation too 🤷 

Btw, don't install `tauri-bundler`, that's from alpha times :)

**Comment by reggermont** [comment]
Thank you for all your clarifications and advices. Still discovering the tool and I'm mixing a lot of documentation to make it work :smile: 

Will use the `next` branch and improve the Dockerfile, thanks!
