### ISSUE TITLE
Add support for `Window::set_icon()` on MacOS

### ISSUE THREAD

**Issue by GaiBrutman** [tauri-apps/tauri#3260]
### Describe the problem

When trying to change the app's window icon with `window.set_icon()`, I get the following error:
`image `` extension not supported; please file a Tauri feature request` (on 'png', 'jpg' and 'ico')

It looks like when compiled on MacOs, the extension option always panics:
https://github.com/tauri-apps/tauri/blob/28dd9adb266b97db0bf7179268269f8614ce78e8/core/tauri-runtime-wry/src/lib.rs#L533-L536

### Describe the solution you'd like

Support for MacOS icon extensions needs to be added.

**Comment by GaiBrutman** [comment]
After looking into it, it seems like `tau` (as for 0.5.2) has no support for MacOS icons:
https://docs.rs/tao/0.5.2/tao/window/struct.Window.html#method.set_window_icon

**Comment by amrbashir** [comment]
indeed, setting an icon for a window on macos is not possible. however we can set the icon for the dock when we add dock management api. check #2358
