### ISSUE TITLE
[feat]: add `build > beforeCompileCommand`

### ISSUE THREAD

**Issue by Snazzie** [tauri-apps/tauri#3267]
### Describe the problem

I'm always frustrated when i make changes to my type definitions and forget to run my rust code generator manually so that my rust struct artifacts are up to date. And i sit there wondering why the hell my change isnt working because rust compiler isnt showing any errors.

### Describe the solution you'd like

add a `beforeCompileCommand` to `tauri.conf.json` so that before rust compiles/recompiles it will run my command to run the code generator and therefore the struct artifacts are always up to date.

Additionally, a feature that allows us to specify files to watch, in this case, a single or multiple definition files, that auto trigger recompile if any of the files have been changed. then i dont have to remember to trigger a recompile after i edit the definitions.

### Additional context

I use https://github.com/quicktype/quicktype to turn Typescript DTOs thats been generated from C# into rust structs so types are always in sync across the board. If any of the files are out of sync, my app visibly or unvisibly will fail and might make it into production.

**Comment by FabianLars** [comment]
Can't you use the [`build.rs`](https://doc.rust-lang.org/cargo/reference/build-scripts.html) file for this? Sounds pretty much like _the_ use case for this.

I totally second the file watcher stuff tho, would be helpful for my project setups too.

**Comment by lucasfernog** [comment]
I agree with the `build.rs` script suggestion. And if we're going with this approach, might aswell just use [rerun-if-changed](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-changed).

**Comment by FabianLars** [comment]
i don't think rerun-if-changed works for this/like this. Or at least, i wasn't able to make it work 🤔

**Comment by Snazzie** [comment]
ahh, I wasn't aware of what `build.rs` purpose was, good to know.
