### ISSUE TITLE
npm run tauri dev calls "npm dev" not "npm run dev" [bug] 

### ISSUE THREAD

**Issue by alexander-beaver** [tauri-apps/tauri#3280]
### Describe the bug

On a new configuration installed through npx (svelte), the command run by tauri to start up the node server is `npm dev` when it should be `npm run dev`. As a result, the server does not start
![Screenshot 2022-01-25 150301](https://user-images.githubusercontent.com/48573460/151050919-bf8bdba2-2807-40f0-a722-ff02c4cfff31.png)
.

### Reproduction

1. Create a new application using `npx create-tauri-app`
2. Cd into directory
3. Run `npm install`
4. Run  `npm run tauri dev`

### Expected behavior

It should call `npm run dev` and start up the node server.

### Platform and versions

```shell
Operating System - Windows, version 10.0.22000 X64
Webview2 - 97.0.1072.69

Node.js environment
  Node.js - 16.2.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.3.0
  yarn - Not installed

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/.vscode
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../public
  devPath - http://localhost:5000
  framework - Svelte
  bundler - Rollup
```

**Comment by amrbashir** [comment]
This has been fixed in the next branch and will be released soon.

For now, open `src-tauri/tauri.conf.json` and edit the `beforeDevCommand`
