### ISSUE TITLE
[bug] Downloading Rust CLI..

### ISSUE THREAD

**Issue by jahnli** [tauri-apps/tauri#3287]
### Describe the bug

Downloading Rust CLI..   It takes too long. It never works  

### Platform and versions

```shell
windows
```

**Comment by nothingismagick** [comment]
We are evaluating this approach that we have been doing, and are considering ditching the RUST CLI binary entirely. This is in active triage. Thankyou for reporting it!

**Comment by jahnli** [comment]
It takes too long. I spend 5-6 hours on it

**Comment by nothingismagick** [comment]
Yes, we are trying to find an alternative right now, because this is obviously terrible DX.

**Comment by jahnli** [comment]
thank you

**Comment by jahnli** [comment]
I don't know rust, I only know node, can I use Tauri @nothingismagick

**Comment by nothingismagick** [comment]
Yes, yes! That is the whole idea here. I am so sorry you're having trouble, and we're going to find an alternative to this current problem!

**Comment by nothingismagick** [comment]
so the alternative solution is to use `cargo` directly:

```
cargo install tauri-cli --git https://github.com/tauri-apps/tauri
cargo tauri dev
```

**Comment by nothingismagick** [comment]
this will take some time to build, but it will work

**Comment by jahnli** [comment]
Whether Windows is available

**Comment by nothingismagick** [comment]
yes, this will work on windows, assuming you have installed the rustlang dependencies.

see: https://tauri.studio/docs/get-started/setup-windows

**Comment by jbolda** [comment]
@jahnli I am curious if downloading it directly makes a difference? That seems like something going wrong rather than a connection issue.
https://github.com/tauri-apps/binary-releases/releases

**Comment by jbolda** [comment]
Also, what package manager and version are you using?

**Comment by jahnli** [comment]
yarn  v1.22.17    I am from China,  But after I used the proxy, it still didn't work

**Comment by lqd1434** [comment]
@jahnli I am too, but I try again, it worked, that is a little strange.

**Comment by zhanglun** [comment]
I think the biggest problem is that it needs to be downloaded every time you run `yarn tauri dev`. even though you have downloaded it before. Is is to check the version or something?

**Comment by markstien** [comment]
use `cargo tauri dev`

**Comment by FabianLars** [comment]
> Is is to check the version or something?

No this is not intended, it's a bug and if it's not covered by the changes already part of the `next` branch then we have no idea what causes it, especially since we can't reproduce this behavior.
This is one of the reasons why we're looking into rewriting the js cli _right now_, before the 1.0 release (potentially delaying the release if needed).

**Comment by lin-yf** [comment]
i have the same issue,after i read the source code, i found that `tauri-cli` is missing in the `@tauri-apps/cli`, so i copy it from other project.  i think download it directly from ` https://github.com/tauri-apps/binary-releases/` may be a temporary fix.
![image](https://user-images.githubusercontent.com/36855589/152830356-c3c5afed-d776-4a6e-9869-68ce7e401fa1.png)

**Comment by kitepad** [comment]
In https://github.com/tauri-apps/binary-releases/, latest version is beta.7, no beta.8.

**Comment by FabianLars** [comment]
@kitepad That's correct. Not every package's version get bumped every time.
So `tauri-cli@beta.7` = `tauri@beta.8` = `@tauri-apps/cli@beta.10`, but one cli version is often compatible with a **range** of tauri releases.
