### ISSUE TITLE
[feat] Support copy content to `<app>/Contents/Library` folder for Mac app

### ISSUE THREAD

**Issue by zhuhaow** [tauri-apps/tauri#3290]
### Describe the problem

I can't find a solution for it yet (maybe I missed something).

It is very useful since this is very widely used by Apple to support certain features.

[Auto start](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLoginItems.html)

> Applications can contain a helper application as a full application bundle, stored inside the main application bundle in the `Contents/Library/LoginItems` directory. 
> ...
> 
> Use the `SMLoginItemSetEnabled` function (available in OS X v10.6.6 and later) to enable a helper application.

Or [get privilege permission securely](https://developer.apple.com/documentation/servicemanagement/1431078-smjobbless?language=objc), 

### Describe the solution you'd like

Add support to copy files or directories to `Library` just like `resources` in [`bundler`](https://github.com/tauri-apps/tauri/tree/dev/tooling/bundler) but only for macOS.

I'm not sure if bundler is used when running `tauri dev`, if it's not, then we may need to find another way to make the content available in dev.

**Comment by hankbao** [comment]
This would definitely be a handy feature. Both `LoginItems` & `LaunchServices` depend on bundling within the app in the `Contents/Library` folder.

**Comment by pi-ka-qiu** [comment]
Support copy content to <app>/Contents/Plugins folder for Mac app ?
