### ISSUE TITLE
[bug] getAll() doesn't include windows created in JavaScript.

### ISSUE THREAD

**Issue by XuluWarrior** [tauri-apps/tauri#3297]
### Describe the bug

If I create a new window in the main WebView, the array returned by`getAll()` doesn't include the new window.

### Reproduction

1. Include the following code in the WebView
```
  import { window as tauriWindow } from '@tauri-apps/api';
  
  const w = new tauriWindow.WebviewWindow('child', {
    title: 'Child',
    resizable: true,
    width: 700,
    height: 600,
    url: "child.html"
  });
  setTimeout(() => console.log('all', tauriWindow.getAll()), 2000); // Wait a bit in case it takes time for windows to be created/updated
  console.log(tauriWindow.getAll());
```
2. The output to console only includes the `main` window.

### Expected behavior

I would expect the array returned by `getAll()` to contain both the `main` and `child` windows.

### Platform and versions

```shell
Operating System - Mac OS, version 11.6.2 X64

Node.js environment
  Node.js - 14.18.2
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.15
  yarn - 1.22.17

Rust environment
  rustc - 1.57.0
  cargo - 1.57.0

App directory structure
/node_modules
/public
/src-tauri
/.git
/.idea
/src

App
  tauri.rs - 1.0.0-beta.8 (I am actually running { git = "https://github.com/tauri-apps/tauri", branch = "next" } )
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:3000
  framework - React
```

**Comment by lucasfernog** [comment]
I couldn't reproduce it on the API example. Did you try increasing the timeout value?

**Comment by XuluWarrior** [comment]
I have tried it manually in the console and never see `child` in the returned values.

What do you mean by the API example?  I can try that too?

**Comment by lucasfernog** [comment]
The API example is located here https://github.com/tauri-apps/tauri/tree/next/examples/api but you need to setup the repo in order to use it.

**Comment by XuluWarrior** [comment]
This is the branch I'm using that reproduces the issue.  Based off a project generated using `create-tauri-app`

https://github.com/tallarium/tauri-experiments/tree/next/get-all

**Comment by lucasfernog** [comment]
I see that. Let me see what is the problem.

**Comment by lucasfernog** [comment]
You're creating the window before the Tauri event system is ready and the `tauri://window-created` event (which is used to update the windows array) is lost. If I change `setup()` to `setTimeout(setup, 2000)` it works. I'll see what I can do to fix this, we had a queue for this purpose but IIRC it wasn't needed anymore.

**Comment by XuluWarrior** [comment]
Adding the timeout does work 👍🏾

If an event queue isn't an option would it be sensible to have an `app.isReady` promise/callback?
Somewhere to put calls that require the necessary plumbing is in place before running.

**Comment by XuluWarrior** [comment]
Alternatively, maybe windows creation should be blocked/queued until the event system is ready.

**Comment by iSplasher** [comment]
> Adding the timeout does work 👍🏾
> 
> If an event queue isn't an option would it be sensible to have an `app.isReady` promise/callback? Somewhere to put calls that require the necessary plumbing is in place before running.

Something like `app.isReady` would be great.
