### ISSUE TITLE
[docs] Command `tauri init plugin --name` does not exist

### ISSUE THREAD

**Issue by JohannesKlauss** [tauri-apps/tauri#3304]
The [documentation](https://tauri.studio/docs/guides/plugin) states that you can use `tauri init plugin --name plugin-name` to bootstrap a custom plugin, but this command fails with:

```
error: Found argument 'plugin' which wasn't expected, or isn't valid in this context

USAGE:
    cargo tauri init [FLAGS] [OPTIONS]

For more information try --help
```

Going through the cmd it doesn't seem like there is an actual command for that.

**Comment by FabianLars** [comment]
Urgh, i went through the docs three times and still missed it.
This command is only available in the git version of the cli (cargo install tauri-cli --git https://github.com/tauri-apps/tauri` -> `cargo tauri x`). Furthermore it was renamed to tauri plugin init.

I'll remove it from the docs for now, thanks for reporting it.

**Comment by FabianLars** [comment]
removed in https://github.com/tauri-apps/tauri-docs/pull/387
