### ISSUE TITLE
[bug]: Allowlist/Cargo features de-sync

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri#3311]
Apparently sometimes changes in the allowlist will not update the cargo features. This is of course bad for DX, security and app size.

**Comment by FabianLars** [comment]
Ayyy i totally forgot about #3300. Sorry for the false alarm, i blame the sleepy Sunday haha

**Comment by JonasKruckenberg** [comment]
No worries 😂

**Comment by lucasfernog** [comment]
Fixed as part of the isolation feature refactor.
