### ISSUE TITLE
[bug] `FileDialogBuilder::set_parent` not working on macOS

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tauri#3312]
### Describe the bug

`set_parent` does not seem to work on macOS. When it's used, the file dialog should be attached to the window, like in the [rfd winit example](https://github.com/PolyMeilex/rfd/blob/6ca088a376a03372f8019440640fe84476d5ee26/examples/winit-example/src/main.rs#L56):
<img width="471" alt="Screenshot 2022-01-31 at 1 14 59 AM" src="https://user-images.githubusercontent.com/11315492/151723929-df61510a-e9f0-4d96-92b4-267958e07916.png">

### Reproduction

```rust
#[tauri::command]
pub async fn open(win: tauri::Window) -> Result<(), String> {
  let mut d =  tauri::api::dialog::FileDialogBuilder::new().set_parent(&win);
  let (sender, receiver) = std::sync::mpsc::channel();
  d.pick_file(move |p| {
    sender.send(p).unwrap();
  });
  let file_path = match receiver.recv().unwrap_or_default() {
    Some(p) => p,
    None => return Ok(()),
  };
  println!("file_path {:?}", file_path);
  Ok(())
}
```

### Platform and versions

```shell
Operating System - Mac OS, version 10.15.7 X64

Node.js environment
  Node.js - 16.13.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.2
  yarn - 1.22.17

Rust environment
  rustc - 1.58.0
  cargo - 1.58.0

App directory structure
/node_modules
/public
/src-tauri
/build
/.git
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:5000
  framework - Svelte
```

**Comment by probablykasper** [comment]
Seems like it works in rfd for `AsyncFileDialog`, but not for `FileDialog` which Tauri uses

**Comment by probablykasper** [comment]
Opened https://github.com/PolyMeilex/rfd/issues/53

Is there any reason why Tauri isn't using `AsyncFileDialog`?

**Comment by m11m** [comment]
It kind of looks like you'd need to use AsyncFileDialog to get "sheet" behavior...

or maybe rfd would have to handle the async stuff in some sync wrapper?

The AsyncFileDialog uses https://developer.apple.com/documentation/appkit/nssavepanel/1535870-beginsheetmodalforwindow/ which seems async to me (takes completion handler parameter) ?
