### ISSUE TITLE
[feat] execute a command synchronously

### ISSUE THREAD

**Issue by adminy** [tauri-apps/tauri#3316]
### Describe the problem

In nodejs a lot of num modules use `execSync` or `spawnSync`. Some of these libs need complete re architecture just because there is no synchronous executor.

Would be nice to have it.

### Describe the solution you'd like

Synchronous executor / command handler without async await.

### Alternatives considered

N/A

**Comment by lucasfernog** [comment]
This issue is being tracked here: https://github.com/tauri-apps/wry/issues/454
