### ISSUE TITLE
[feat] Build universal binaries for MacOS

### ISSUE THREAD

**Issue by betamos** [tauri-apps/tauri#3317]
### Describe the problem

By default, binaries are built for a single CPU architecture, either x86_64 or aarch64. MacOS supports [Universal Binaries](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary). that allow a single binary (and hence package & dmg) which contains both. This is recommended by Apple because it simplifies application distribution.

### Describe the solution you'd like

I'd like to be able to build a universal dmg that can be distributed to any MacOS user, directly from `tauri build`.

I suggest adding a pseudo-target `universal-darwin-macos` for this purpose, which invokes the [`lipo`](https://ss64.com/osx/lipo.html) command to combine two arch-specific binaries into a universal one. I've tried it out and it works for me.

Given such a feature, we also need a way to deal with external binaries:

- Either Tauri requires a universal binary be present at build-time
- Or we find the arch-specific binaries and combine them at bundle-time (see below).

#### Use an external build script

A custom build script would work, but it would require quite a bit of redundant and custom tooling. This is because the `lipo` invocation needs to happen _between_ `cargo build` and dmg packaging.

#### Use cargo [blocked]

Cargo [does not support](https://github.com/rust-lang/cargo/issues/8875) universal binaries at this time.

#### Use cargo-lipo

[`cargo-lipo`](https://github.com/TimNN/cargo-lipo) is a tool that uses `lipo` under the hood. Not investigated.

#### Use a Rust-lib instead of lipo

`lipo` is included in MacOS (perhaps with XCode?) but it may be harder to access it from Windows or Linux for cross-platform building. If that's hard to get lipo working, it may be worth looking into using a rust lib that does the same thing, to avoid external dependencies.

### Additional context

It's an open question what exactly universal binaries mean for build systems. Should it be part of the arch triple (`universal-darwin-macos`) or should it be considered separate platform-specific config? I haven't seen best practices on this yet, feedback welcome.

**Comment by nothingismagick** [comment]
I would venture the guess that Apple prefers universal binaries not just because of Intel and Arm architectures, but also because of the subtle and sometimes massive differences between their M-series architectures. Nevertheless, this is a great topic and thankyou for filing the issue.

I almost feel like we need insight from the `cargo` engineering team here tbh.

**Comment by betamos** [comment]
> the subtle and sometimes massive differences between their M-series architectures

_(Obligatory thisisfine.gif)_

Can you provide some more context?

**Comment by bluebreadhead** [comment]
@betamos how to mention this using .toml or config file?

**Comment by betamos** [comment]
Not sure what you mean by "mention". To my knowledge you can only manually set the target with the `--target` build flag. See https://tauri.app/v1/guides/building/macos/#binary-targets
