### ISSUE TITLE
[feat] Tray add set_title API

### ISSUE THREAD

**Issue by awkj** [tauri-apps/tauri#3322]
### Describe the problem

I use tauri build menubar application ,but I found tauri rust api not have set_title to set title
only have set_icon and set_icon_as_template

```
impl<R: Runtime> SystemTrayHandle<R> {
  /// Gets a handle to the menu item that has the specified `id`.
  pub fn get_item(&self, id: MenuIdRef<'_>) -> SystemTrayMenuItemHandle<R> {
    for (raw, item_id) in self.ids.iter() {
      if item_id == id {
        return SystemTrayMenuItemHandle {
          id: *raw,
          tray_handler: self.inner.clone(),
        };
      }
    }
    panic!("item id not found")
  }

  /// Updates the tray icon. Must be a [`Icon::File`] on Linux and a [`Icon::Raw`] on Windows and macOS.
  pub fn set_icon(&self, icon: Icon) -> crate::Result<()> {
    self.inner.set_icon(icon).map_err(Into::into)
  }

  /// Support [macOS tray icon template](https://developer.apple.com/documentation/appkit/nsimage/1520017-template?language=objc) to adjust automatically based on taskbar color.
  #[cfg(target_os = "macos")]
  pub fn set_icon_as_template(&self, is_template: bool) -> crate::Result<()> {
    self
      .inner
      .set_icon_as_template(is_template)
      .map_err(Into::into)
  }
}
```

### Describe the solution you'd like

add API set_title like

**Comment by amrbashir** [comment]
do you mean system tray tooltip or change a menu item's title in the system tray menu? because the code you posted is for SystemTray

**Comment by awkj** [comment]
> do you mean system tray tooltip or change a menu item's title in the system tray menu? because the code you posted is for SystemTray

![image](https://user-images.githubusercontent.com/9017743/152181250-2e47ff4b-da91-433c-9c19-d0b592ae4521.png)

I mean system tary menu, API document on https://tauri.studio/docs/guides/system-tray

I want use tauri make a tool for display network speed on mac（previoue version is use electron write) , electron have API  tray.setTitle(title[, options]) (https://www.electronjs.org/docs/latest/api/tray)

I try use a canvas to instead of text, but icon should have limit on width（ only have icon width). 

This is a comparison of electron and tauri, electron setImage API can show any pictures size

![image](https://user-images.githubusercontent.com/9017743/152181464-79a1e816-185b-4a62-9c77-5c28f4dd82fc.png)

**Comment by amrbashir** [comment]
oh my bad, this is a macOS specific thing, I will upstream it to Tao.

**Comment by awkj** [comment]
> oh my bad, this is a macOS specific thing, I will upstream it to Tao.

you will add two API, one is set_title , and other is set_image(allow set canvas/other image) ? 

or only keep set_image API , set_icon is image's special case?( electron is do it)

**Comment by amrbashir** [comment]
upstream issue https://github.com/tauri-apps/tao/issues/65

> or only keep set_image API , set_icon is image's special case?( electron is do it)

These apis won't be implemented for Tauri v1 and will wait until v2, I have upstreamed `set_title` and once we do it, we can surely add `set_image`

**Comment by probablykasper** [comment]
I think this was added in v1.2
