### ISSUE TITLE
[bug] cli.rs > dev command failing with clap short option duplicates

### ISSUE THREAD

**Issue by betamos** [tauri-apps/tauri#3324]
### Describe the bug

The cargo-tauri dev command fails at runtime with a clap assertion failure due to a name collision with two flags.

### Reproduction

```
git clone https://github.com/tauri-apps/tauri.git
cd tauri/tooling/cli.rs
cargo run dev foo
```

### Expected behavior

Dev command does not panic.

### Platform and versions

```shell
Manual checkout of tauri-apps/tauri/next
```

### Stack trace

```shell
Compiling tauri-cli v1.0.0-beta.7 (/Users/-/Code/tauri/tooling/cli.rs)
    Finished dev [unoptimized + debuginfo] target(s) in 2.56s
     Running `target/debug/cargo-tauri dev .`
thread 'main' panicked at 'App dev: Short option names must be unique for each argument, but '-r' is in use by both 'runner' and 'release-mode'', /Users/-/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.6/src/build/app/debug_asserts.rs:99:17
```

### Additional context

Might want CI support for CLI invocations of dev command?

**Comment by betamos** [comment]
Just realized this is not reproducible in release mode, since it's a debug assertion, so it's less of an urgent issue. That's probably why it remained undiscovered too.

In either case, the short name collision is still there. Happy to send a PR, if someone suggests which short name should be kept for -r, runner or release-mode?

**Comment by amrbashir** [comment]
I think `release` should not have a short name, at least I prefer to use the full flag `--release`, lets see what @lucasfernog thinks.
