### ISSUE TITLE
Formatting and Clippy on CI

### ISSUE THREAD

**Issue by khionu** [tauri-apps/tauri#333]
I'd like to make three changes to the project, for the sake of project cleanliness:
1) Change our formatting configuration to use Unix EOLs globally.
2) Add `cargo fmt --check` to our CI
3) Configure Clippy in our CI

These changes will have the following dev flow impositions:
- PRs will not be able to be merged until `cargo fmt` is ran.
- PRs will not be able to be merged until `cargo clippy` returns clean.

If we're fine with these changes, I can go ahead an implement them.

### Further reading
Clippy - https://github.com/rust-lang/rust-clippy/blob/master/README.md
Rustfmt - https://github.com/rust-lang/rustfmt/blob/master/README.md

**Comment by nothingismagick** [comment]
@jbolda - what do you think? I'm cool with it. :)

**Comment by jbolda** [comment]
We are getting to that point where ours tests will be run instead of smoke tests. I will never say no to valid consistency, and this feels a great time to add this.

**Comment by rajivshah3** [comment]
﻿
Maybe it would be good to run ESLint (for TS/JS) on PRs as well?

**Comment by nothingismagick** [comment]
Absolutely! We do have it installed and rigged, so it would just be a matter of running it.

**Comment by khionu** [comment]
I would be happy to have it in the same PR/branch, but someone else will have to champion the TS specific work.

**Comment by nothingismagick** [comment]
@khionu - did you get started on this by the way?

**Comment by nothingismagick** [comment]
Can we close this issue @khionu ?

**Comment by khionu** [comment]
Yup!
