### ISSUE TITLE
[bug] unable to parse inline JSON TAURI_CONFIG env var: unknown field `readTextFile`,

### ISSUE THREAD

**Issue by speroleague** [tauri-apps/tauri#3331]
### Describe the bug

error: unable to parse inline JSON TAURI_CONFIG env var: unknown field `readTextFile`, expected one of `scope`, `all`, `readFile`, `writeFile`, `readDir`, `copyFile`, `createDir`, `removeDir`, `removeFile`, `renameFile` at line 1 column 960
  --> src/main.rs:13:10
   |
13 |     .run(tauri::generate_context!())
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `tauri::generate_context` (in Nightly builds, run with -Z macro-backtrace for more info)

I am seeing this error when I am trying to run tauri dev. I am using the https://github.com/tauri-apps/vue-cli-plugin-tauri package, and am not sure yet if the problem is in there. I didn't encounter this problem until I implemented both the SQL and Log plugins, and added the following into my Cargo.toml file:

```
[patch.crates-io]
tauri = { git = "https://github.com/tauri-apps/tauri", branch = "next" }
```

I have gone through my tauri.conf.json file and everything looks right:

https://gist.github.com/justinwerner/eb7b608c3eacea504002d26f7bef2c86

I am just really new to Tauri and any help would be appreciated.

Thanks so much for anything!

### Platform and versions

```shell
Operating System - Ubuntu, version 21.10 X64

Node.js environment
  Node.js - 16.13.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.2
  yarn - 1.22.17

Rust environment
  rustc - 1.58.1
  cargo - 1.58.0

App directory structure
/public
/node_modules
/tests
/src
/.git
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - Set automatically by Vue CLI plugin
  devPath - Set automatically by Vue CLI plugin
  framework - Vue.js (Vue CLI)
  bundler - Webpack

Done in 3.40s.
```

### Stack trace

```shell
error: unable to parse inline JSON TAURI_CONFIG env var: unknown field `readTextFile`, expected one of `scope`, `all`, `readFile`, `writeFile`, `readDir`, `copyFile`, `createDir`, `removeDir`, `removeFile`, `renameFile` at line 1 column 960
  --> src/main.rs:13:10
   |
13 |     .run(tauri::generate_context!())
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `tauri::generate_context` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by lucasfernog** [comment]
To use the `tauri` dependency from git you also need to use the latest CLI.

```
cargo install --git https://github.com/tauri-apps/tauri/
# use `cargo tauri` instead of `yarn tauri`
cargo tauri dev
cargo tauri build
```

Also remove the `readTextFile` from `tauri.conf.json`. It was replaced by `readFile`. Documentation will be updated next week.
