### ISSUE TITLE
[feat] Update request support include CPU info

### ISSUE THREAD

**Issue by aiyanbo** [tauri-apps/tauri#3359]
### Describe the problem

My app is built on the arm and x86 architectures of macOS, and I would like the application updates to return different download links based on CPU information.

### Describe the solution you'd like

The CPU information can be passed through the request path or the headers.

It might be supported in https://github.com/tauri-apps/tauri/blob/next/core/tauri/src/updater/core.rs#L287

**Comment by lucasfernog** [comment]
We could change the `target` option to allow a target triple, idk if that needs any change.

**Comment by lucasfernog** [comment]
I'll be implementing this today.

**Comment by aiyanbo** [comment]
@lucasfernog 

And `download_url` can be an array?

https://github.com/tauri-apps/tauri/blob/next/core/tauri/src/updater/core.rs#L43

**Comment by lucasfernog** [comment]
@aiyanbo Why do you need the download url to be an array?

**Comment by aiyanbo** [comment]
@lucasfernog 

My app is distributed in different parts of the world and I want to use an effective CDN failback to resolve a single network failure.

**Comment by lucasfernog** [comment]
That is already handled, the tauri.conf.json updater config is an array of urls

**Comment by lucasfernog** [comment]
Though I can see a case where you might want to return a list of URLs on the updater JSON file format if that's what you're using. Can you file a separate feature request?

**Comment by aiyanbo** [comment]
@lucasfernog OK
