### ISSUE TITLE
p5js app window does not show canvas animation

### ISSUE THREAD

**Issue by rjpgt** [tauri-apps/tauri#337]
**Describe the bug**
Simple html file with p5js animation does not show the canvas animation.

**To Reproduce**
I have a simple static app with an html file showing a p5js animation. In my dist/spa folder I have an index.html file that refers to a p5.min.js and a sketch.js file, both of which are present in the folder. There is also a css file.

When running tauri dev it asked for a package.json. I created a default package.json with npm init -y and removed the 'main' line from it.

Since I am not using any UI framework I set both distDir and devPath to point to "../dist/spa" .

**Expected behavior**
I should see the canvas animation.

**Screenshots**

**Platform and Versions (please complete the following information):**

Operating System - Linux(5.3.0-26-generic) - linux/x64

Node.js environment
  Node.js - 12.14.1
  tauri.js - 0.3.1

Rust environment
  rustc - 1.40.0
  cargo - 1.40.0
  tauri-cli - 0.1.2

Global packages
  NPM - 6.13.4
  yarn - 1.21.1

App directory structure
/dist
/src-tauri

App
  tauri - 0.3.1
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  Windows - Edge
  distDir - ../dist/spa
  devPath - ../dist/spa

**Additional context**

**Stack Trace**

**Comment by rjpgt** [comment]
If instead of the minimized version, p5.min.js, I use the full version, p5.js, the animation is working. The script sketch.js is what creates the canvas element in the page. Earlier, with p5.min.js, no canvas element was being created. There were no errors in the console though.

**Comment by tensor-programming** [comment]
Could I see some code; specifically the index.html and javascript of the p5.min.js version of the application?

**Comment by rjpgt** [comment]
index.html:
```
<!DOCTYPE html>
 <html>
 <head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width,initial-scale=1.0">
   <link rel="stylesheet" href="main.css">
 </head>
 
 <body>
 <div id="top_labels"></div>
 <div id="top_sliders"></div>
 <div id="canvas_container"></div>
 <div id="botm_slider"></div>
 <div id="botm_label"></div>
 <footer>
     <p>Made with <a href="http://p5js.org/">p5js</a></p>
 </footer>
 <script type="text/javascript" src="p5.js"></script>
 <script type="text/javascript" src="sketch.js"></script>
 </body>
```

p5.min.js is too big to be pasted here. It is available [here](https://p5js.org/download/).

**Comment by Laegel** [comment]
I see in your index.html that your script element is `<script type="text/javascript" src="p5.js"></script>` and "I use the full version, p5.js, the animation is working". But aren't you saying you're using a file called p5.min.js when minified? If so, just change the src for ` <script type="text/javascript" src="p5.min.js"></script>`. That seems quite obvious, though, I'm not sure this would help.

**Comment by rjpgt** [comment]
> I see in your index.html that your script element is `<script type="text/javascript" src="p5.js"></script>` and "I use the full version, p5.js, the animation is working". But aren't you saying you're using a file called p5.min.js when minified? If so, just change the src for ` <script type="text/javascript" src="p5.min.js"></script>`. That seems quite obvious, though, I'm not sure this would help.

This is the working version. If I use p5.min.js instead of p5.js nothing happens which is what i had reported. As you can see, the html is a bunch of empty divs. sketch.js populates the divs using p5.js. Here is the (source)[view-source:http://amrtam.in/sims/jsapps/mechanics/lissajous/sketch.js] of sketch.js. And (here)[http://amrtam.in/sims/mechanics/lissajous.html] is the simple animation.

**Comment by Laegel** [comment]
I've tried to run it with `dev` but neither the uncompressed nor the minified versions are working, it's just not loading the scripts at all without any warning/error from the console.
Both run well with `build`, though. 
@rjpgt what's your OS?

**Comment by rjpgt** [comment]
> I've tried to run it with `dev` but neither the uncompressed nor the minified versions are working, it's just not loading the scripts at all without any warning/error from the console.
> Both run well with `build`, though.
> @rjpgt what's your OS?

As I had said, `tauri dev` works for me with the uncompressed version of p5.js. I haven't tried with `build`. My OS is  Linux(5.3.0-26-generic) - linux/x64. For more details please see first comment

**Comment by nothingismagick** [comment]
Would like to know how things work these days with canvas animations, tauri has grown a lot since this issue was filed. If you can confirm that this is still an issue with latest tauri and approach, please reopen.
