### ISSUE TITLE
[bug] tsc reported error in `@tauri-apps/api/window.ts`

### ISSUE THREAD

**Issue by kubijo** [tauri-apps/tauri#3385]
### Describe the bug

Running `tsc` in my project produces the following errors in my project when I update to the latest version of the API package.
This might for sure be caused by a stricter ts config in my project over yours.

That said, I didn't encounter such errors with other packages yet, and I do have a `compilerOptions.skipLibCheck = true` in my `tsconfig.json` so I'm pretty much stumped as to what could be done…

It does seem to me in the end that the code is suboptimally annotated because in the given case, the `requestType_` variable can only be guessed to be `null` at the point of re-assignment…

```typescript
let requestType_ = null
if (requestType) {
  if (requestType === UserAttentionType.Critical) {
    requestType_ = { type: 'Critical' }
  } else {
    requestType_ = { type: 'Informational' }
  }
}
```

```
➤ YN0000: [toolbox]: .yarn/cache/@tauri-apps-api-npm-1.0.0-beta.8-432c2e967c-c8e4fbe6ed.zip/node_modules/@tauri-apps/api/window.ts:525:9 - error TS2322: Type '{ type: string; }' is not assignable to type 'null'.
➤ YN0000: [toolbox]: 
➤ YN0000: [toolbox]: 525         requestType_ = { type: 'Critical' }
➤ YN0000: [toolbox]:             ~~~~~~~~~~~~
➤ YN0000: [toolbox]: 
➤ YN0000: [toolbox]: .yarn/cache/@tauri-apps-api-npm-1.0.0-beta.8-432c2e967c-c8e4fbe6ed.zip/node_modules/@tauri-apps/api/window.ts:527:9 - error TS2322: Type '{ type: string; }' is not assignable to type 'null'.
➤ YN0000: [toolbox]: 
➤ YN0000: [toolbox]: 527         requestType_ = { type: 'Informational' }
```

### Platform and versions

I'm not using `npm` & the tauri CLI is installed in a different directory because it didn't work with yarn berry & PNP resolution mode… so here is the version of API I have… it should be the only info relevant to this topic

```shell
web-ui/packages/toolbox ❯ yarn info @tauri-apps/api
└─ @tauri-apps/api@npm:1.0.0-beta.8
   └─ Version: 1.0.0-beta.8
```

**Comment by amrbashir** [comment]
we won't be shipping ts files in the soon to be released version so this error won't happen again.

**Comment by kubijo** [comment]
I see ... what do I need to read-up on to see how you intend to support the TS annotations in user land, then?

**Comment by FabianLars** [comment]
We will ship type declaration files (d.ts) instead of the source files. This is pretty much the standard method in the ecosystem so you shouldn't have to do anything special to make it work.

**Comment by kubijo** [comment]
Yep, that indeed seems to be the way the industry goes.
Thank you for the info then, and I'm looking forward to the aforementioned release :+1:
