### ISSUE TITLE
[docs] Need clarity on memory requrement for tauri

### ISSUE THREAD

**Issue by shrkamat** [tauri-apps/tauri#3387]
Documentation currently reads memory usage on Linux to be [180MB](https://github.com/tauri-apps/tauri/blob/next/README.md?plain=1#L79). Not very clear on how this 180MB reading was arrived at ?

I ran tauri hello world application and used procrank (it probably uses pmap / proc entries) to measure the memory. Surprisingly it is reported to be very low. About 23600KB for react hello world app i,e 23.04MB to be precise. RSS reading is 79668KB, it's inline with 0.5% memory as reported by top.

![see](https://i.imgur.com/7nLVW2t.png)

I am specifically interested to check feasibility to use tauri for applications on embedded Linux systems based on Aarch64 platforms. On desktop Ubuntu systems results look promising, but it deviates by far from documented 180MB. 

P.S. for measuring this memory swap is turned off.

**Comment by amrbashir** [comment]
You also need to measure the webkit2gtk process. try using `memory-profiler`, it is a python cli.
