### ISSUE TITLE
[bug] Macos10.15.7 cannot listen for system tray click events

### ISSUE THREAD

**Issue by Lction** [tauri-apps/tauri#3391]
### Describe the bug

According to the document write listen system tray function, can listen the click of the tray context content, but can not listen the left button、right button、double click events of the tray icon。I don't know if it's my code because I'm not good at Rust, thank you very much!
My code:
![image](https://user-images.githubusercontent.com/40019242/153525015-5f0ea6e5-3678-4997-8af8-e5716c7c8197.png)

`#![cfg_attr(
all(not(debug_assertions), target_os = "windows"),
windows_subsystem = "windows"
)]

use tauri::{CustomMenuItem, SystemTray, SystemTrayMenu, SystemTrayMenuItem, SystemTrayEvent};
use tauri::Manager;

fn main() {
    let quit = CustomMenuItem::new("quit".to_string(), "Quit");
    let hide = CustomMenuItem::new("hide".to_string(), "Hide");
    let tray_menu = SystemTrayMenu::new()
        .add_item(quit)
        .add_native_item(SystemTrayMenuItem::Separator)
        .add_item(hide);
    let system_tray = SystemTray::new()
        .with_menu(tray_menu);
    tauri::Builder::default()
        .system_tray(system_tray)
        .on_system_tray_event(|app, event| match event {
            SystemTrayEvent::LeftClick {
                position: _,
                size: _,
                ..
            } => {
                println!("system tray received a left click");
            }
            SystemTrayEvent::RightClick {
                position: _,
                size: _,
                ..
            } => {
                println!("system tray received a right click");
            }
            SystemTrayEvent::DoubleClick {
                position: _,
                size: _,
                ..
            } => {
                println!("system tray received a double click");
            }
            SystemTrayEvent::MenuItemClick { id, .. } => {
                match id.as_str() {
                    "quit" => {
                        std::process::exit(0);
                    }
                    "hide" => {
                        let window = app.get_window("main").unwrap();
                        window.hide().unwrap();
                    }
                    _ => {}
                }
            }
            _ => {}
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
`

### Platform and versions

```shell
Operating System - Mac OS, version 10.15.7 X64

Node.js environment
  Node.js - 16.13.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - Not installed

Global packages
  npm - 8.1.2
  yarn - 1.22.10

Rust environment
  rustc - 1.58.1
  cargo - 1.58.0

App directory structure
/node_modules
/public
/src-tauri
/.git
/.idea
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:8080
  framework - Vue.js (Vue CLI)
  bundler - Webpack
```

**Comment by amrbashir** [comment]
this has been fixed, please update to latest tauri
