### ISSUE TITLE
[feat] allow passing arguments to cargo build

### ISSUE THREAD

**Issue by Themayu** [tauri-apps/tauri#3398]
### Describe the problem

I am trying to debug an issue with my project setup that causes tauri's `cargo build` invocation to fully rebuild the entire project, plus dependencies after rust-analyzer has finished checking the project source. According to comments on rust-lang/cargo#4961 I need the output of invoking `cargo build` with the flag `-vvvv` to do this, but the problem only appears when `cargo` is invoked through `tauri dev` and doesn't show up on a manual `cargo build` invocation.

### Describe the solution you'd like

I would like a way to pass arguments directly to the underlying `cargo build` calls performed by `tauri build` and `tauri dev`. This would allow me to pass the flag `-vvvv` directly and get fully verbose output from the build process.

### Alternatives considered

An alternative solution would be a separate flag under `tauri build`/`tauri dev` to directly set the verbosity level that will be requested from the build process, but if more flags are required in the future then supporting each one separately can be harder to maintain than simply allowing users to pass them directly to the toolchain.

### Additional context

I have asked on the Tauri Discord server about existing ways to get this output, and have been told that it is currently not yet possible to pass the flag I require. I have been asked to open this feature request, as it sounds like a useful feature to have. According to rust-lang/cargo#4961 directly passing the verbose flag to `cargo build` is needed to get the information, and therefore an alternative solution cannot be found.

**Comment by amrbashir** [comment]
for now you can enable verbosity or any other cargo option using the cargo configuration file https://doc.rust-lang.org/cargo/reference/config.html#termverbose

**Comment by Themayu** [comment]
> for now you can enable verbosity or any other cargo option using the cargo configuration file https://doc.rust-lang.org/cargo/reference/config.html#term

Unfortunately setting this in `.cargo/config.toml` appears to have no effect at all on `cargo`'s output, even when I manually run `cargo build`.

**Comment by amrbashir** [comment]
> for now you can enable verbosity or any other cargo option using the cargo configuration file https://doc.rust-lang.org/cargo/reference/config.html#termverbose

**Comment by samw3** [comment]
Can someone give an example of how this is used?

**Comment by FabianLars** [comment]
@samw3
```
pnpm tauri build -- --ignore-rust-version
npm tauri build -- -- --ignore-rust-version // npm needs an extra --
```
