### ISSUE TITLE
[bug] `tauri deps update` not working in release candidate

### ISSUE THREAD

**Issue by srg-kostyrko** [tauri-apps/tauri#3418]
### Describe the bug

After update to release candidate `tauri deps update` command is no longer working - I get following error in console
```
error: Found argument 'deps' which wasn't expected, or isn't valid in this context
```
Not sure if this was intentional but I failed to find anything about removing this command in release notes.

### Reproduction

run `npx tauri deps update` in console

### Expected behavior

tauri updates its dependencies

### Platform and versions

```shell
Operating System - Windows, version 10.0.19042 X64
Webview2 - 98.0.1108.43
Visual Studio Build Tools:
   - Visual Studio Community 2019
   - Visual Studio Build Tools 2017

Node.js environment
  Node.js - 14.17.0
  @tauri-apps/cli - 1.0.0-rc.2
  @tauri-apps/api - 1.0.0-rc.0

Global packages
  npm - 6.14.13
  pnpm - Not installed
  yarn - 1.22.11

Rust environment
  rustc - 1.58.1
  cargo - 1.58.0

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-pc-windows-msvc 

App directory structure
/.git
/.github
/.husky
/.vscode
/apps
/demo
/dist
/game
/libs
/node_modules
/qspider-assets
/src-tauri
/tools

App
  tauri.rs - 1.0.0-rc.0
  framework - React
```

**Comment by FabianLars** [comment]
Yes we (temporarily?) removed it with the cli rewrite. Personally I'm leaning into generally dropping it.
Either way we should add a note about it in the docs for now, thanks for reporting it.

The release notes for the js cli need to be reworked too because all the listed changes were about the old cli that was dropped last minute.

**Comment by Levminer** [comment]
> Yes we (temporarily?) removed it with the cli rewrite. Personally I'm leaning into generally dropping it.

How should I update Tauri if the command is removed?

**Comment by lucasfernog** [comment]
change all `beta.X` references to `rc.0` for now. NPM and Cargo will take care of the rest. We're working on a tool for better installation and updating management for each system.
