### ISSUE TITLE
Updater endpoint url placeholder not replaced

### ISSUE THREAD

**Issue by FabianLars** [tauri-apps/tauri#3428]
### Describe the bug

The target and current_version placeholders aren't replaced by the actual values, therefore the updater request always ends up in a 404.
Furthermore the url is logged like this: `https://example.com/v1/update/%7B%7Btarget%7D%7D/%7B%7Bcurrent_version%7D%7D`
Same for atto and request btw.

### Platform and versions

```shell
I'm on my phone right now so I'll fill this out tomorrow. But everything is on the latest rc versions on Windows 10.
```

**Comment by JonasKruckenberg** [comment]
```
I'm on my phone right now so I'll fill this out tomorrow. But everything is on the latest rc versions on Windows 10.
```

This is an interesting error message from the cli 🤔 never seen it before 😉
