### ISSUE TITLE
[bug] tauri dev opens distDir

### ISSUE THREAD

**Issue by Chaostheorie** [tauri-apps/tauri#3440]
### Describe the bug

When using `tauri dev` the webview tries to access the location specified in `build.distDir` (tauri.conf.json) instead of the location from `build.devPath`.  Placing a link to the URL of `build.devPath` in an `index.html` at `build.distDir` will take you to the `build.devPath` location.

Strangely, if the folder at dev path doesn't exist or a server isn't available at the specified port, tauri will wait until something is available.

### Reproduction

1. Start a dev server at the `build.devPath` with any content
2. Place a blank `index.html` file at the folder specified in `build.distDir`
3. Start Tauri in development mode: `cargo tauri dev`
4. See the content of the blank index.html (a lot of nothing) – You can alternatively play around with the index.html and see it being loaded on application restart.

### Expected behavior

Go to `build.devPath`

### Platform and versions

```shell
Operating System - EndeavourOS, version Rolling Release X64

Node.js environment
  Node.js - 16.13.2
  @tauri-apps/cli - 1.0.0-rc.-1 (from `next` branch #43348652)
  @tauri-apps/api - Not installed (specific package for next version)

Global packages
  npm - 8.4.1
  pnpm - 6.30.1

Rust environment
  rustc - 1.58.1
  cargo - 1.58.0

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-unknown-linux-gnu 

App directory structure
/public
/.vscode
/src-tauri
/static
/build
/.svelte-kit
/bundled
/.git
/node_modules
/src

App
  tauri.rs - git+https://github.com/tauri-apps/tauri.git?branch=next#43348652662fad65914959829073e6ba08cc412d (1.0.0-beta.8)
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:3000/
  framework - Svelte
```

### Stack trace

```shell
/
```

**Comment by Chaostheorie** [comment]
Problem was reproducable on dev branch

**Comment by Chaostheorie** [comment]
It was an issue with the `custom-protocol` feature. See https://discord.com/channels/616186924390023171/625037620996734986/942457994900291695

**Comment by lucasfernog** [comment]
Documentation added to Cargo.toml: #3441

**Comment by ColonelThirtyTwo** [comment]
That feature is badly named. I assumed that `custom-protocol` activates the `Builder::register_uri_scheme_protocol` method and related infrastructure, but apparently it only controls distDir vs devDir.
