### ISSUE TITLE
[bug] sidecar example app creates empty screen app from windows msi

### ISSUE THREAD

**Issue by jmw992** [tauri-apps/tauri#3446]
### Describe the bug

I built the sidecar example on windows with `yarn tauri build`, it installs fine, but the app operation is a blank screen which doesn't output messages like it does with `yarn tauri dev`.
![image](https://user-images.githubusercontent.com/15371018/153770220-0933e76c-2160-4041-bc2a-bd46fb4afaeb.png)

I checked on my and the app from installer does produce messages, so this issue is probably only on windows.

### Reproduction

1. On Windows machine build `yarn tauri build`
2. Install the sidecar app from `.msi` 
3. Run it and see empty screen

### Expected behavior

App works the same as `yarn tauri dev` and as mac

### Platform and versions

```shell
PS C:\Users\jmw99\OneDrive\Documents\BayswaterPC\monorepo-with-tauri-client\tauri-sidecar> cargo tauri info

Operating System - Windows, version 10.0.19043 X64
Webview2 - 98.0.1108.50
Visual Studio Build Tools:
   - Visual Studio Build Tools 2022

Node.js environment
  Node.js - 16.14.0
  @tauri-apps/cli - 1.0.0-rc.3
  @tauri-apps/api - Not installed

Global packages
  npm - 8.3.1
  pnpm - Not installed
  yarn - 1.22.11

Rust environment
  rustc - 1.58.1
  cargo - 1.58.0

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-pc-windows-msvc 

App directory structure
/node_modules
/scripts
/src
/src-tauri

App
  tauri.rs - 1.0.0-rc.1
  build-type - bundle
  CSP - default-src 'self'
  distDir - ["../index.html"]
  devPath - ["../index.html"]
PS C:\Users\jmw99\OneDrive\Documents\BayswaterPC\monorepo-with-tauri-client\tauri-sidecar>
```

### Stack trace

```shell
n/a
```

**Comment by JonasKruckenberg** [comment]
You can build your app in debug mode by running `cargo tauri build --debug` or `npm tauri build --debug` (or whatever package manager you use). That way the browser console is enabled for the bundled app and you can see what the issue is

**Comment by lucasfernog** [comment]
I couldn't reproduce this one. Try with --debug and let me know if there's any crash happening.

**Comment by jmw992** [comment]
Thanks @lucasfernog  for taking a stab at this, unfortunately I'm still getting this error.  I reran with debug and I'm getting the following
![image](https://user-images.githubusercontent.com/15371018/154101330-9313d824-07fa-41d4-825e-01cc9a7c4c54.png)
<details>
<summary>Searchable text error message</summary>


```bash
thread 'tokio-runtime-worker' panicked at 'Failed to spawn packaged node: Io(Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." })', src\main.rs:23:12
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Asset `favicon.ico` not found; fallback to index.html
```

</details>

I checked out the program folder and the icon is missing
![image](https://user-images.githubusercontent.com/15371018/154102293-5a414e5c-e59f-4c66-93a3-8364fc44a7f5.png)

I compared that to the mac where it is working and there is a resources folder with the icon
<img width="1125" alt="image (2)" src="https://user-images.githubusercontent.com/15371018/154102848-fba73768-77f0-4b73-8502-905f84bfafec.png">
 
I'm guessing there is an issue with the bundling.

**Comment by lucasfernog** [comment]
The install files look right, the problem might be the path resolution, it might be using a wrong target string like -gnu instead of -msvc suffix. I can push something so you can try later

**Comment by jmw992** [comment]
Thanks, and I'm happy to give anything a try and help where I can.

**Comment by enedrio** [comment]
Hello I just ran into this. On Windows the sidecar path is not correctly created. Currently the bundler/installer leaves the target suffix on the binary file. I think it used to remove it in previous versions of tauri (not sure).
The function that creates the path to the sidecar binary does not add the target triple to the name, therefore it can not find it after installation.
So in code you would create your sidecar Command with  Command::new_sidecar("my-sidecar") and it looks for "my-sidecar.exe", which does not exist.
Creating the sidecar command with `Command::new_sidecar("my-sidecar-x86_64-pc-windows-msvc")` should work on windows. But that's just a hack. 😅
I think the installer or bundler needs a fix.

**Comment by lucasfernog** [comment]
I'm working on it right now to fix it.

**Comment by lucasfernog** [comment]
We forgot to change the MSI bundler, fix coming up soon. I'm not sure how it was working on my end :|

**Comment by jmw992** [comment]
I checked out your branch and it is working on my end.  Thanks @lucasfernog!
