### ISSUE TITLE
[bug] `tauri init` generates non-existent version for tauri dependency

### ISSUE THREAD

**Issue by GiantappMan** [tauri-apps/tauri#3453]
### Describe the bug

```
error: failed to select a version for the requirement `tauri = "^1.0.0-rc.2"`
candidate versions found which didn't match: 0.11.1, 0.11.0, 0.10.0, ...
```

### Reproduction

`npm run tauri dev`

### Platform and versions

```shell
npm run tauri info

> mouse_simulator@0.0.0 tauri
> tauri "info"


Operating System - Windows, version 10.0.19043 X64
Webview2 - 98.0.1108.50
Visual Studio Build Tools:
   - Visual Studio Community 2022
   - Visual Studio ���ɹ��� 2019
   - Visual Studio Professional 2019

Node.js environment
  Node.js - 17.5.0
  @tauri-apps/cli - 1.0.0-rc.4
  @tauri-apps/api - 1.0.0-rc.1

Global packages
  npm - 8.4.1
  pnpm - 6.11.0
  yarn - 1.22.15

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-pc-windows-msvc

App directory structure
/.vscode
/dist
/node_modules
/public
/src
/src-tauri

App
  tauri - 1.0.0-rc.2 (no lockfile)
  tauri-build - no manifest (no lockfile)
  tao - no manifest (no lockfile)
  wry - no manifest (no lockfile)
  build-type - bundle
  CSP - unset
  distDir - ../dist
  devPath - http://localhost:3000/
  framework - Svelte
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by FabianLars** [comment]
The latest tauri version is rc 1: https://crates.io/crates/tauri/versions

**Comment by joshua7v** [comment]
yes, change `tauri = "^1.0.0-rc.2"` to rc.1 will work
but I run into the same issue as well
I literally just followed the instructions on docs
and I have no idea why it generates rc.2 for me.

**Comment by FabianLars** [comment]
Shit you're right, it does generate rc.2

**Comment by JonasKruckenberg** [comment]
Yeah somehow the metadata syncing got a bit over enthusiastic 😉

https://github.com/tauri-apps/tauri/blob/dev/tooling/cli/metadata.json

**Comment by GiantappMan** [comment]
Said what I wanted to say, cause My English is broken and I think maybe the team is ready for the next version. so I didn't say haha.

> yes, change `tauri = "^1.0.0-rc.2"` to rc.1 will work but I run into the same issue as well I literally just followed the instructions on docs and I have no idea why it generates rc.2 for me.

**Comment by lucasfernog** [comment]
The publish pipeline failed, we're running it again. It'll work on rc.2 soon.

**Comment by lucasfernog** [comment]
Released.
