### ISSUE TITLE
[feat] Allow custom dialog boxes

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#3455]
### Describe the problem

There is only (Yes, No) and (Ok, Cancel) dialog boxes.

### Describe the solution you'd like

There should be an API to make custom dialog boxes, with progress bars, custom buttons, icons, etc.

**Comment by nothingismagick** [comment]
Yes, this is a limitation of the html spec, unfortunately. The only thing you can do is spawn a new window and then style as usual. Could be a nice official plugin.

**Comment by ghost** [comment]
How is this a limitation of the HTML spec if it opens a native window?

**Comment by JonasKruckenberg** [comment]
You have several options to create dialogs, the `alert` and `confirm` functions or the `dialog` element is what @nothingismagick meant, those are part of the html spec and nothing we can change.

If you meant the tauri provide dialog functions the answer is still no however. This would be massive feature creep as we would have to implement handles to all sorts of native control elements and native styling and native positioning in tauri.
(basically reinventing flutter in the process)

The best approach here is to open a new webview that you have full control over.
