### ISSUE TITLE
[feat] Allow $schema field in tauri.conf.json

### ISSUE THREAD

**Issue by kt215** [tauri-apps/tauri#3464]
Having a schema for `tauri.conf.json` would be very helpful.

I made my own schema file based on your documentation and I reference that schema using the $schema field. But your parser doesn't accept the field. As a workaround, I customized the CLI in `config.rs` and removed `deny_unknown_fields` to make it work.

I later found out that you do generate a `schema.json` file from `config.rs` code automatically. It doesn't have very good enum support right now IMO, but I recommend you make that schema file available and use it in the code examples.

**Comment by lucasfernog** [comment]
We validate the schema on our CLI. Why do you need the $schema field? Are you performing the validation on your end?

**Comment by kt215** [comment]
My IDE (Webstorm) uses it, so I get intellisense/code-completion. I'm also used to these features when editing `angular.json` which is the main configuration file in Angular. At the top of the `angular.json` file we have this:

```json
"$schema": "./node_modules/@angular/cli/lib/config/schema.json",
```

**Comment by lucasfernog** [comment]
Ahh makes sense, we'll implement this :)

**Comment by JonasKruckenberg** [comment]
I think pointing to an URL would work too 🤔 having the schema locally would be nicer, but only helps people who use the cli from npm

**Comment by angelxmoreno** [comment]
so like, where is the url? lol

**Comment by amrbashir** [comment]
schema is released to GitHub releases on each release of `tauri-build` crate, here is one of them https://github.com/tauri-apps/tauri/releases/download/tauri-build-v2.0.0-beta.13/schema.json

schema is also distributed with the NPM cli package so you can use a local path to it.

**Comment by angelxmoreno** [comment]
Nice. Thanks!
