### ISSUE TITLE
[bug] You have macOS 10.14.6. The application requires macOS 10.13 or later.

### ISSUE THREAD

**Issue by ForgQi** [tauri-apps/tauri#3469]
### Describe the bug

![bug](https://user-images.githubusercontent.com/34411314/154093172-0733ee09-af81-4876-a649-c7ecc41b5cb7.jpg)

### Reproduction

I refered https://github.com/tauri-apps/tauri/issues/2732#issuecomment-980473934 to set minimum version .
I builds this application with [tauri-action](https://github.com/tauri-apps/tauri-action)

### Expected behavior

I'm confused，10.14 greater than 10.13. Why is this happening

### Platform and versions

```shell
Operating System - Windows, version 10.0.22000 X64
Webview2 - 98.0.1108.50
Visual Studio Build Tools:
   - Visual Studio ���ɹ��� 2019
WARNING: no lock files found, defaulting to npm

Node.js environment
  Node.js - 14.18.1
  @tauri-apps/cli - 1.0.0-rc.3 (outdated, latest: 1.0.0-rc.4)
  @tauri-apps/api - 1.0.0-rc.0 (outdated, latest: 1.0.0-rc.1)

Global packages
  npm - 8.0.0
  pnpm - Not installed
  yarn - Not installed

Rust environment
  rustc - 1.58.1
  cargo - 1.58.0

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-pc-windows-msvc

App directory structure
/.git
/.github
/.idea
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-rc.2
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../public
  devPath - http://localhost:5000/
  framework - Svelte
  bundler - Rollup
```

**Comment by JonasKruckenberg** [comment]
Can you run `tauri info` on the device you were running the app on?

**Comment by nothingismagick** [comment]
This is so weird, but you should definitely update (probably not the real cause though).

```
  @tauri-apps/cli - 1.0.0-rc.3 (outdated, latest: 1.0.0-rc.4)
  @tauri-apps/api - 1.0.0-rc.0 (outdated, latest: 1.0.0-rc.1)
  ```

**Comment by ForgQi** [comment]
I contacted the user. This is he sent
![tauri_info](https://user-images.githubusercontent.com/34411314/154116007-e180ffff-a0b6-4d4e-966e-2bae989019e6.png)

**Comment by ForgQi** [comment]
> This is so weird, but you should definitely update (probably not the real cause though).
> 
> ```
>   @tauri-apps/cli - 1.0.0-rc.3 (outdated, latest: 1.0.0-rc.4)
>   @tauri-apps/api - 1.0.0-rc.0 (outdated, latest: 1.0.0-rc.1)
> ```

The .app builds with [tauri-action](https://github.com/tauri-apps/tauri-action)，The tools should be up to date

**Comment by JonasKruckenberg** [comment]
> I contacted the user. This is he sent
> ![tauri_info](https://user-images.githubusercontent.com/34411314/154116007-e180ffff-a0b6-4d4e-966e-2bae989019e6.png)

Alright, there's nothing here that strikes me as particularly off... Do we handle the version Requirement or is this something in the .plist file?

**Comment by ForgQi** [comment]
I refered https://github.com/tauri-apps/tauri/issues/2732#issuecomment-980473934 no other handle.
.plist file:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>English</string>
  <key>CFBundleDisplayName</key>
  <string>biliup-app</string>
  <key>CFBundleExecutable</key>
  <string>biliup-app</string>
  <key>CFBundleIconFile</key>
  <string>icon.icns</string>
  <key>CFBundleIdentifier</key>
  <string>com.tauri.dev</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>biliup-app</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleShortVersionString</key>
  <string>0.1.1</string>
  <key>CFBundleVersion</key>
  <string>20220213.124853</string>
  <key>CSResourcesFileMapped</key>
  <true/>
  <key>LSApplicationCategoryType</key>
  <string>public.app-category.developer-tools</string>
  <key>LSMinimumSystemVersion</key>
  <string>10.13</string>
  <key>LSRequiresCarbon</key>
  <true/>
  <key>NSHighResolutionCapable</key>
  <true/>
  <key>NSHumanReadableCopyright</key>
  <string></string>
  <key>NSAppTransportSecurity</key>
  <dict>
  <key>NSExceptionDomains</key>
  <dict>
  <key></key>
  <dict>
  <key>NSExceptionAllowsInsecureHTTPLoads</key>
  <true/>
  <key>NSIncludesSubdomains</key>
  <true/>
  </dict>
  </dict>
  </dict></dict>
</plist>
```

**Comment by lucasfernog** [comment]
Did you also set the minimum version on your build.rs file (we'll do that for you after #3496 )?

**Comment by ForgQi** [comment]
Thank you for your help. I just realized I made a mistake,  I wrote the code to set the minimum version, but in the wrong places.

**Comment by lucasfernog** [comment]
Thank for the response @ForgQi , that's why we added some checks and we'll set everything for you regarding the minimum macOS version. Check out the latest release :)
