### ISSUE TITLE
[bug] UI doesn't render in 1.0.0-rc.2 with Yew

### ISSUE THREAD

**Issue by gondolyr** [tauri-apps/tauri#3472]
### With `tauri = "1.0.0-beta.8"` and `tauri-build = "1.0.0-beta.4"`

I built the release binary using `cargo tauri build` and ran the executable at `src-tauri/target/release/tauri-yew-demo`.

I am able to see the "Hello, World" text in the window. I can also see the text using `cargo tauri dev`.

![image](https://user-images.githubusercontent.com/57526088/154090529-5e273601-a292-4482-b13f-1fbea40ac0d7.png)

### With `tauri = "1.0.0-rc.2"` and `tauri-build = "1.0.0-rc.2"`

I updated the Tauri dependency using `cd src-tauri && cargo update -p tauri`, following this: https://tauri.studio/docs/development/updating-dependencies.

Building release artifacts with `cargo tauri build` doesn't produce any errors, however, I cannot see the text in the window when I run the new release executable at `src-tauri/target/release/tauri-yew-demo`. However, with `cargo tauri dev`, the text appears. 

![image](https://user-images.githubusercontent.com/57526088/154091480-6cfc6369-7e79-428d-ab95-9b4daa2f4462.png)

### Reproduction

1. Clone the tauri-yew-demo project (https://github.com/stevepryde/tauri-yew-demo) and ensure the HEAD commit is at [25c5183](https://github.com/stevepryde/tauri-yew-demo/commit/25c51831eeca67f01939f4b3a46aca252e70620a).
2. Build the project using `cargo tauri build` and run the built executable at `src-tauri/target/release/tauri-yew-demo`. Verify that the window displays the "Hello, World" text.
3. Run the project in development with `cargo tauri dev` and verify that the window displays the "Hello, World" text.
4. Update the Tauri dependency to `1.0.0-rc.2` following the steps outlined in https://tauri.studio/docs/development/updating-dependencies.
    ```
    cd src-tauri && cargo update -p tauri
    ```
5. Build the project using `cargo tauri build` and run the built executable at `src-tauri/target/release/tauri-yew-demo`. Observe the window does not display the "Hello, World" text.
6. Run the project in development with `cargo tauri dev` and verify that the window displays the "Hello, World" text.

### Expected behavior

I expect the latest version of Tauri, `1.0.0-rc.2` to build release executables that displays content from Yew, not just dev builds.

### Platform and versions

```shell
Operating System - Pop!_OS, version 21.10 X64
WARNING: no lock files found, defaulting to npm

Node.js environment
  Node.js - 17.4.0
  @tauri-apps/cli - 1.0.0-rc.4
  @tauri-apps/api - Not installed

Global packages
  npm - 8.4.0
  pnpm - Not installed
  yarn - Not installed

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-unknown-linux-gnu

App directory structure
/.git
/frontend
/src-tauri

App
  tauri - 1.0.0-rc.2
  tauri-build - 1.0.0-rc.2
  tao - 0.6.1
  wry - 0.13.1
  build-type - bundle
  CSP - default-src 'self'
  distDir - ../frontend/dist
  devPath - http://localhost:8080/
package.json not found
```

### Additional context

There are no errors during compilation.

**Comment by FabianLars** [comment]
A couple things you can try:
- Make sure the cli for `cargo tauri build` is up to date too (you didn't talk about it, but the tauri info output comes from the current cli so you should be good).
- run `cargo update` (without the package specifier) in your src-tauri dir.
- set CSP to null (you want to fill that with the correct values once you distribute your app).
- Build a debug build `cargo tauri build --debug` -> Output in target/debug. Look in the devtools console if it logs something.
- Make sure you build your frontend too (or specify this step as a beforeBuildCommand).

**Comment by gondolyr** [comment]
Setting the CSP to `null` rendered the UI as expected. I'll have to review this config setting to understand what it's doing.

Mine was set to this before, which was the default from `cargo tauri init`:
```json
"security": {
  "csp": "default-src 'self'"
}
```

**Comment by nothingismagick** [comment]
I expect this has to do with `yew` creating WASM that needs `unsafe-eval` to properly execute.

**Comment by gondolyr** [comment]
I wonder what changed between the beta version and the RC version that caused this.

**Comment by junderw** [comment]
Chromium recently added `wasm-unsafe-eval` to allow only WASM (and not eval)... but other browsers do not have it.

You need unsafe-eval for non-chromium browsers to allow WASM.
