### ISSUE TITLE
[bug] Events from Rust are lost to JS

### ISSUE THREAD

**Issue by victorhqc** [tauri-apps/tauri#3484]
### Describe the bug

When an event is emitted from Rust, it's lost to JS, as it loads before JS is ready to start listening for any event. The following code highlights the issue

_Backend_
```rust
tauri::Builder::default() .on_page_load(move |window, _| {
    let bootstrap = Bootstrap {}; 
    window.emit("bootstrap", bootstrap.clone()).unwrap();
})
```

_Frontend_
```ts
import { listen } from '@tauri-apps/api/event';

listen('bootstrap', () => {
  console.log('Hello World');
})
```

### Reproduction

1. Clone [repository](https://github.com/victorhqc/tauri_event_issue) that reproduces the issue
1. Follow instructions to start the App
1. Note that JS never starts, as it waits for an event to happen.

### Expected behavior

JS should load Application. Edit the `main.rs` file and uncomment the commented code to show how it works by adding a timeout.

### Platform and versions

```shell
Operating System - Windows, version 10.0.22000 X64
Webview2 - 98.0.1108.50
Visual Studio Build Tools:
   - Visual Studio Community 2019
   - Visual Studio Build Tools 2017

Node.js environment
  Node.js - 16.13.0
  @tauri-apps/cli - 1.0.0-rc.4
  @tauri-apps/api - 1.0.0-rc.1

Global packages
  npm - 8.5.0
  pnpm - Not installed
  yarn - Not installed

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-pc-windows-msvc

App directory structure
/.git
/node_modules
/public
/src
/src-tauri

App
  tauri - 1.0.0-rc.2
  tauri-build - 1.0.0-rc.2
  tao - 0.6.2
  wry - 0.13.1
  build-type - bundle
  CSP - unset
  distDir - ../build
  devPath - http://localhost:3000/
  framework - React
```

**Comment by lucasfernog** [comment]
Previously we had an event cache to mitigate this, but it causes issues, see #2323
So the event system isn't ideal for your use case, I'd probably write a function in your case:

Backend
```rust
tauri::Builder::default() .on_page_load(move |window, _| {
    window.eval("window.__BOOTSTRAP__ ()").unwrap();
})
```

Frontend
```ts
window.__BOOTSTRAP__ = () => {
  console.log('Hello World');
  delete window.__BOOTSTRAP__;
})
```

`on_page_load` is executed when `DOMContentLoaded` is fired, so you might need to check if the function exists and delay if it doesn't.

You can also emit an event or send a command from the frontend to notify when your listener is ready.

**Comment by victorhqc** [comment]
I ended up calling the backend with the frontend as soon as JS is ready, however I still need to apply the delay at 50ms or so. Not ideal still, but I guess will be ok. I may end up making a Tauri plugin 🤷‍♂️ thank you for looking at the issue though
