### ISSUE TITLE
TypeError: window.__TAURI_IPC__ is not a function

### ISSUE THREAD

**Issue by mxismean** [tauri-apps/tauri#3487]
### Describe the bug

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/44690729/154452518-93c93d48-5c01-4edf-8097-fa5bf0facd78.png">
The version used when creating the project is:
"@tauri-apps/cli": "^1.0.0-beta.10",
 "@tauri-apps/api": "~1.0.0-beta.8",
tauri-build = { version = "1.0.0-beta.4" }

Everything is ok with this version.

Today I upgraded the version to:
"@tauri-apps/cli": "^1.0.0-rc.4",
"@tauri-apps/api": "^1.0.0-rc.1",
tauri-build = {version = "1.0.0-rc.2", features = [] }

An error will be reported when use the JS API.

### Platform and versions

```shell
👉 yarn tauri info
yarn run v1.22.17
warning package.json: No license field
$ tauri info

Operating System - Mac OS, version 12.2.0 X64

Node.js environment
  Node.js - 14.19.0
  @tauri-apps/cli - 1.0.0-rc.4
  @tauri-apps/api - 1.0.0-rc.1

Global packages
  npm - 6.14.16
  pnpm - Not installed
  yarn - 1.22.17

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-apple-darwin

App directory structure
/.gitlab
/dist
/node_modules
/internals
/public
/src-tauri
/templates
/.git
/src

App
  tauri - 1.0.0-rc.2
  tauri-build - 1.0.0-rc.2
  tao - 0.6.2
  wry - 0.13.1
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:3000/index.html
  framework - Vue.js
✨  Done in 22.51s.
```

**Comment by mxismean** [comment]
<img width="691" alt="image" src="https://user-images.githubusercontent.com/44690729/154455171-6e534124-17fd-4c79-aeb3-98ddac48410e.png">
Upgrade as provided in the document

**Comment by FabianLars** [comment]
I really can't believe i say that, but removing the trailing `index.html` in your devPath fixes this. No idea how that went under the radar, so thanks a bunch for reporting this issue!

**Comment by mxismean** [comment]
Thank you. The problem is solved！ 🙏🏻

**Comment by nothingismagick** [comment]
Great job @FabianLars !
