### ISSUE TITLE
[bug] `Waiting for your dev server to start...` error message can be clearer

### ISSUE THREAD

**Issue by joepio** [tauri-apps/tauri#3491]
### Describe the bug

Since upgrading from, there is a check if the dev server is running, which is great. But in my case, the error message was a little confusing:

`Waiting for your dev server to start...`

I thought this referred to my tauri server, but in my project, this referred to my front-end server (because I have both).

I think this error message can be clearer if it includes the dev server address, like so:

`Waiting for your dev server to start on {address}`

Permalink to source: https://github.com/tauri-apps/tauri/blob/759d1afb86f3657f6071a2ae39c9be21e20ed22c/tooling/cli/src/dev.rs#L213

A small, really unimportant request, though :)

### Platform and versions

```shell
1.0-rc.2
```

**Comment by nothingismagick** [comment]
That's a great idea.

**Comment by nothingismagick** [comment]
And would be an easy Pull Request! ;)

**Comment by lucasfernog** [comment]
I'll push a commit because we're releasing today.

**Comment by Cuuss** [comment]
Change port to 3000
