### ISSUE TITLE
[feat] Explicitly specify systray Windows icon

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tauri#3500]
### Describe the problem

To use a system tray icon, you need to specify the path to the `.png` icon, then have an `.ico` version for Windows with the same name. This behavior might be confusing, and not obvious enough to trust or understand without checking the docs

### Describe the solution you'd like

```json
"systemTray": {
  "iconPath": ["icons/icon.png", "icons/icon.ico"]
}
```

**Comment by p0ryae** [comment]
^ This would be just perfect. Just like the way you can specify different formats for the icon of Tauri app (normal icon. Not tray)

**Comment by amrbashir** [comment]
There is no need for this, we can use the same icon for all platforms even Windows.

I just need to make some changes at tao which I planned to include in tauri-apps/tao#297 but I might open a separate PR for it. It is one of the things I want to do before v1 stable.
