### ISSUE TITLE
Unhandled Promise Rejection: cannot traverse directory

### ISSUE THREAD

**Issue by mxismean** [tauri-apps/tauri#3501]
### Describe the bug

<img width="519" alt="image" src="https://user-images.githubusercontent.com/44690729/154642996-46d7b609-c9ad-477e-8762-6cab34edd225.png">

<img width="800" alt="image" src="https://user-images.githubusercontent.com/44690729/154643164-08129c11-5063-481a-b459-986f7ec3c5e4.png">

`dialog.open()`  is going well, The path was obtained successfully.

then  use `fs.readDir()` to read the path, got  `cannot traverse directory`

### Platform and versions

```shell
yarn tauri info
yarn run v1.22.17
warning package.json: No license field
$ tauri info

Operating System - Mac OS, version 12.2.1 X64

Node.js environment
  Node.js - 14.19.0
  @tauri-apps/cli - 1.0.0-rc.4
  @tauri-apps/api - 1.0.0-rc.1

Global packages
  npm - 6.14.16
  pnpm - Not installed
  yarn - 1.22.17

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-apple-darwin

App directory structure
/dist
/node_modules
/public
/src-tauri
/.vscode
/src

App
  tauri - 1.0.0-rc.2
  tauri-build - 1.0.0-rc.2
  tao - 0.6.2
  wry - 0.13.2
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:3000/
  framework - Vue.js
✨  Done in 37.36s.

```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by mxismean** [comment]
tauri.conf.json:

```
{
  "tauri": {
    "allowlist": {
        "all": true
  }
}
```

**Comment by nothingismagick** [comment]
While that would work, what @mxismean is suggesting will bloat your final binary and potentially expose your app to unneeded attack surface. Please consult this page: https://tauri.studio/docs/api/config and determine what it is EXACTLY that you need to enable. (If that really is the underlying problem here...)

**Comment by mxismean** [comment]
I know. I mean, I turned on API permissions.

The current problem is：

`fs.readDir()` to read the path, got   `❌ cannot traverse directory`

**Comment by mxismean** [comment]
The version used when creating the project is: 

"@tauri-apps/cli": "^1.0.0-beta.10", 

"@tauri-apps/api": "~1.0.0-beta.8", 

tauri-build = { version = "1.0.0-beta.4" }

Everything is ok with this version.✅

Yestoday,  I upgraded the version to:
"@tauri-apps/cli": "^1.0.0-rc.4",

"@tauri-apps/api": "^1.0.0-rc.1",

tauri-build = {version = "1.0.0-rc.2", features = [] }

`fs.readDir()` api   began to report errors

**Comment by nothingismagick** [comment]
Sorry, I misread the second comment and didn't realise it came from OP.

**Comment by nothingismagick** [comment]
Please see this section:
https://tauri.studio/docs/api/js/modules/fs#security

**Comment by nothingismagick** [comment]
The reason for scoping the API, is because otherwise the UI could theoretically access anything the user has access to, which while it sounds contradictory, is a very real security concern.

**Comment by mxismean** [comment]
I read the documents you provided, and this design is really good at the security level.

However, if my application does need to access any file directory, can it only be satisfied by customizing Rust？

**Comment by FabianLars** [comment]
> However, if my application does need to access any file directory, can it only be satisfied by customizing Rust

Yes.

In regards to your initial question however, we're looking into some kind of whitelist system to allow _user-selected paths_ (dialog/file-drop) to bypass this limitation.

**Comment by mxismean** [comment]
Okay, really looking forward to it.😄

**Comment by nothingismagick** [comment]
in the meantime, try this:
```
      "fs": {
        "scope": ["$USER/*"]
      }
```

**Comment by FabianLars** [comment]
That would require them to edit the paths returned from the dialog to not contain the `/home/username/` path _and_ use the BaseDirectory enum on the readDir api.
Let's just say that we really didn't think that one through 😅 but that's what pre-release versions are for and luckily we have enough users trying out these versions and report stuff we missed💪

**Comment by mxismean** [comment]
> in the meantime, try this:
> 
> ```
>       "fs": {
>         "scope": ["$USER/*"]
>       }
> ```

ok 👌🏻

**Comment by mxismean** [comment]
> 这将要求他们编辑从对话框返回的路径以不包含该`/home/username/`路径_并_在 readDir api 上使用 BaseDirectory 枚举。 让我们说我们真的没想到😅但这就是预发布版本的用途，幸运的是，我们有足够多的用户试用这些版本并报告我们错过的内容💪

**Comment by mxismean** [comment]
> That would require them to edit the paths returned from the dialog to not contain the `/home/username/` path _and_ use the BaseDirectory enum on the readDir api. Let's just say that we really didn't think that one through 😅 but that's what pre-release versions are for and luckily we have enough users trying out these versions and report stuff we missed💪

haha，yes 💪🏻

**Comment by cuizhijun** [comment]
On windows, I tried a lot and failed, Always cannot traverse directory
`const b = await fs.readDir('E:\\code\\tauri\\')`
`    "allowlist": {
      "all": true,
      "fs": {
        "scope": ["E:\\code\\*"]
      }
    }`

**Comment by tweidinger** [comment]
@cuizhijun Your issue seems not completely related to OPs issue. Did you try  `"scope": ["E:\\code\\**"]`? Iirc the single `*` allows for files and `**` allows for sub directories and their files.  Does reading `"E:\\code\\test.txt` work with your current allowlist?

**Comment by cuizhijun** [comment]
> @cuizhijun您的问题似乎与 OPs 问题并不完全相关。你试过了 `"scope": ["E:\\code\\**"]`吗？Iirc 单`*`允许文件并`**`允许子目录及其文件。阅读`"E:\\code\\test.txt`适用于您当前的许可名单吗？

Yes, I've tried a lot, and will my program continue to have this problem when the user installs the software elsewhere, because he can't find the specific directory I specified

**Comment by FabianLars** [comment]
@cuizhijun Please take a look at the page `@nothingismagick` sent a couple of days ago: <https://tauri.studio/docs/api/js/modules/fs/#security>.
Absolute paths (in this case paths starting with `E:`) are not allowed on the javascript side! Also keep in mind that this most likely won't work on any system other than your own.

If you absolutely need to do stuff like this you have to do it in rust (be careful with paths coming from the js side).

**Comment by Weiyi-Feng** [comment]
> Tauri is a framework for building tiny, blazing-fast binaries for all major desktop platforms. 

The whitelisting system sounds great, if the user can't use their directory/file selected in the dialog in the desktop application, they will get confused about it.
With the best wishes awaiting the whitelisting system.

**Comment by spirityy** [comment]
always Unhandled Promise Rejection: cannot traverse directory

"allowlist": {
      "all":true,
      "fs": {
        "scope": ["$USER/**"]
      }
    },

window.__TAURI__.fs.writeFile({ path: `/Users/xxxxxx/Downloads/aa.txt` }, {})

**Comment by FabianLars** [comment]
@spirityy As said before absolute paths are currently not allowed. WIth https://github.com/tauri-apps/tauri/pull/3595 being merged this will change in the next release.

Until then you could try it like this
```ts
fs.writeFile({path: 'aa.txt'}, {dir: fs.BaseDirectory.Download})
```

**Comment by spirityy** [comment]
@FabianLars  But the base directory was created by Dialog.open , there wan't a particular path before writeFIle

**Comment by vdvman1** [comment]
The PR that Fabian linked too fixes exactly that issue, `Dialog.open` returns an absolute path, so wasn't usable, the PR fixes that by adding the returned path to the allowed scope automatically for you
