### ISSUE TITLE
[bug] FS throws "cannot traverse directory" error despite scope settings

### ISSUE THREAD

**Issue by logchan** [tauri-apps/tauri#3506]
### Describe the bug

I created an app with `create-tauri-app`, but the `tauri.fs` apis throws "cannot traverse directory" despite scope settings. I tried on both Windows and macOS.

### Reproduction

1. `npx create-tauri-app` and use Vanilla.js
2. In `tauri.conf.json`, add `"withGlobalTauri": true` to `build`, and set `tauri.allowlist` as follows:
```
    "allowlist": {
      "all": true,
      "fs": {
        "all": true,
        "scope": ["$HOME/**"]
      }
    },
```
3. Replace the content of `index.html` as follows:
```
<!DOCTYPE html>
<html>
  <body>
    <script>
      function test() {
        const func = async () => {
          const tauri = window.__TAURI__;
          const root = await tauri.path.homeDir();
          console.log(root);
          try {
            console.log(await tauri.fs.readDir(root));
          }
          catch (e) {
            console.error(e);
          }
        }
        func();
      }
      test();
    </script>
  </body>
</html>
```
4. `npm run tauri dev`

<img width="199" alt="2022-02-18 11_36_35-Test FS" src="https://user-images.githubusercontent.com/6621738/154724355-9e1a83a0-0897-402f-aa54-4485adf8f37e.png">

### Platform and versions

```shell
Operating System - Windows, version 10.0.19042 X64
Webview2 - 98.0.1108.55
Visual Studio Build Tools:
   - Visual Studio Community 2019

Node.js environment
  Node.js - 14.15.4
  @tauri-apps/cli - 1.0.0-rc.5
  @tauri-apps/api - 1.0.0-rc.1

Global packages
  npm - 6.14.10
  pnpm - Not installed
  yarn - 1.22.15

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-pc-windows-msvc

App directory structure
/dist
/node_modules
/src-tauri

App
  tauri - 1.0.0-rc.3
  tauri-build - 1.0.0-rc.3
  tao - 0.6.2
  wry - 0.13.2
  build-type - bundle
  CSP - unset
  distDir - ../dist
  devPath - ../dist
```

### Additional context

I also tried `fs.readTextFile` which throws the same error. For scope I tried `$HOME`, `$HOME/*`, `$HOME/**`.

**Comment by FabianLars** [comment]
You need to use [BaseDirectory](https://tauri.studio/docs/api/js/enums/fs.BaseDirectory)(re-exported as `Dir` in the fs module) in readDir/readTextFile and make the path relative to that.
"Cannot traverse directory" basically means that absolute paths and parent path fragments (`/../ `) are not allowed.

Also, just in case if that would be a follow-up question, we are working on some kind of whitelist system for user selected paths (dialog/file-drop), because they are kinda unusable without rust right now.

**Comment by logchan** [comment]
> You need to use [BaseDirectory](https://tauri.studio/docs/api/js/enums/fs.BaseDirectory)(re-exported as `Dir` in the fs module) in readDir/readTextFile and make the path relative to that. "Cannot traverse directory" basically means that absolute paths and parent path fragments (`/../ `) are not allowed.

~Could you give an example of "using BaseDirectory and make the path relative to that"? I'm confused about how to list the home directory in JavaScript.~

Ok, I see that the base directory is part of FsDirOptions now. Thanks.
