### ISSUE TITLE
[bug] Global shortcuts - inconsistent behaviour: hide and show window

### ISSUE THREAD

**Issue by AlexMikhalev** [tauri-apps/tauri#3522]
### Describe the bug

Hello all, I am trying to create a simple search app using Tauri - think quicksilver/alfred/raycast, but I can't get consistent behaviour of show and hide window on shortcuts, the code is copy-paste from example API: 
```  
app.run(|app_handle, e| match e {
    // Application is ready (triggered only once)
    RunEvent::Ready => {
      let app_handle = app_handle.clone();
      let window = app_handle.get_window("main").unwrap();
      window.hide().unwrap();
      app_handle
        .global_shortcut_manager()
        .register("CmdOrCtrl+X", move || {

          if window.is_visible().unwrap() {
            window.hide().unwrap();
          } else {
            window.show().unwrap();
          }
        })
        .unwrap();
    }
```
 it hides consistently on CTRL+X but is never shown on the same combination. The app stays in the system tray as expected, but the "toggle" button menu isn't consistent either - shows "hide" title when the window is hidden. I tried global shortcuts from both JS and Rust API. From calling global shortcuts from JS is more inconsistent - while console reports triggered shortcuts, windows only hidden ones per 3 triggering. Global shortcuts behaviour is more consistent from Rust - consistently hides window, but never shows, hence I suspect the issue is with ` window.show().unwrap()` call.
I am on Linux pop os 21.04 ubuntu derivative and ctrl+x isn't captured by desktop shortcuts. 

### Reproduction

To replicate for Rust modify [API example](https://github.com/tauri-apps/tauri/blob/080755b5377a3c0a17adf1d03e63555350422f0a/examples/api/src-tauri/src/main.rs#L226) with code above. 
To replicate for JS modify [JS API example ](https://github.com/tauri-apps/tauri/blob/080755b5377a3c0a17adf1d03e63555350422f0a/examples/api/src/components/Shortcuts.svelte#L15):

```
    registerShortcut(shortcut_, () => {
      if (isvisible) {
        appWindow.hide();
        isvisible = false;
      } else {
        appWindow.show();
        isvisible = true;
      }
      onMessage(`Shortcut ${shortcut_} triggered`);
      
    })
```

### Expected behavior

Window show/hide works on registered global shortcut and tray item created by example code:
```
              let new_title = if window.is_visible().unwrap() {
                window.hide().unwrap();
                "Show"
              } else {
                window.show().unwrap();
                "Hide"
              };
```
displays Show when window is hidden and "Hide" when window is present.

### Platform and versions

```shell
yarn tauri info
yarn run v1.22.17
warning ../../../package.json: No license field
$ tauri info

Operating System - Pop!_OS, version 21.10 X64

Node.js environment
  Node.js - 14.17.0
  @tauri-apps/cli - 1.0.0-rc.4
  @tauri-apps/api - 1.0.0-rc.1

Global packages
  npm - 8.3.1
  pnpm - 6.24.4
  yarn - 1.22.17

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-unknown-linux-gnu 

App directory structure
/src
/.vscode
/node_modules
/src-tauri
/dist
/public

App
  tauri - 1.0.0-rc.2
  tauri-build - 1.0.0-rc.2
  tao - 0.6.2
  wry - 0.13.1
  build-type - bundle
  CSP - unset
  distDir - ../dist
  devPath - http://localhost:3000/
  framework - Svelte
Done in 7.25s.
```

**Comment by lucasfernog** [comment]
Thanks for the report, we'll look into it.

**Comment by lucasfernog** [comment]
This is a regression from https://github.com/tauri-apps/tao/pull/308 :( I'll take a look with the tao guys.

**Comment by AlexMikhalev** [comment]
Thank you @lucasfernog. Is it Linux specific or is it the same behaviour on all platforms?

**Comment by FabianLars** [comment]
@AlexMikhalev It's specific to Linux.

**Comment by wusyong** [comment]
So GAction for GtkApplication won't triggered if none of its windows is focused.
I think we'll have to roll back to x11's implementation.
This means global shortcut won't be supported on wayland again.
And it's also not defined in wayland-protocols yet.
Please let me know if there's any way to do it on wayland.
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/56

**Comment by AlexMikhalev** [comment]
Is it possible to create workaround- for example configure global shortcut in GNOME and capture it using tauri?

**Comment by HASTAG-CHANICHARUANGSUK899** [comment]
https://upload.wikimedia.org/wikipedia/commons/b/b1/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF.jpg

iFAN AUSTRALIA F. A. N. Assembly64.ASM AUTOMAKE AUTORUN AUTOTUNE
MISS CHANICHA RUANGSUK 
189 LEICHHARDT STREET 
SPRING HILL CITY OF BRISBANE 
QUEENSLAND AUSTRALIA 4000
Tel.0459298073

**Comment by lucasfernog** [comment]
Fixed by https://github.com/tauri-apps/tao/pull/330 (only works on x11 again :( )

Run `cargo update` on the `src-tauri` folder to get the new tao release.
