### ISSUE TITLE
[bug] build fails due to missing files

### ISSUE THREAD

**Issue by grctest** [tauri-apps/tauri#3528]
### Describe the bug

When I run `npm run-script tauri dev` the script fails with the following output:

   Compiling app v0.1.0 (C:\TAURI\nft\src-tauri)
error: failed to run custom build command for `app v0.1.0 (C:\TAURI\nft\src-tauri)`

Caused by:
  process didn't exit successfully: `C:\TAURI\nft\src-tauri\target\release\build\app-0a1d54cd509d9df1\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=tauri.conf.json

  --- stderr
  thread 'main' panicked at 'error found during tauri-build: path matching buffer-x86_64-pc-windows-msvc.exe not found.', C:\Users\username\\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-build-1.0.0-rc.3\src\lib.rs:146:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error running CLI: failed to build app: Result of `cargo build` operation was unsuccessful: exit code: 101

### Reproduction

run `npm run-script tauri dev` with avast antivirus running (always warns about new exe's being built)

### Expected behavior

app is built without error

### Platform and versions

```shell
Operating System - Windows, version 10.0.19042 X64
Webview2 - 98.0.1108.56
Visual Studio Build Tools:
   - Visual Studio Community 2022

Node.js environment
  Node.js - 16.14.0
  @tauri-apps/cli - 1.0.0-rc.5
  @tauri-apps/api - Not installed

Global packages
  npm - 8.5.0
  pnpm - Not installed
  yarn - 1.22.17

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-pc-windows-msvc

App directory structure
/.git
/build
/node_modules
/public
/src
/src-tauri

App
  tauri - 1.0.0-rc.3
  tauri-build - 1.0.0-rc.3
  tao - 0.6.2
  wry - 0.13.2
  build-type - bundle
  CSP - unset
  distDir - ../build
  devPath - http://localhost:3000/
  framework - React
```

**Comment by lucasfernog** [comment]
Seems like you defined a `buffer` sidecar. In this case, you need to compile this binary for the `x86_64-pc-windows-msvc` target (your current architecture, you probably have that already) and rename it to `buffer-x86_64-pc-windows-msvc.exe` moving it to the `src-tauri` folder. Check out the [sidecar guide](https://tauri.studio/docs/building/sidecar).

**Comment by grctest** [comment]
You're right, I removed the externalBin values and it built again, thanks :)
