### ISSUE TITLE
move examples out of main repo

### ISSUE THREAD

**Issue by jbolda** [tauri-apps/tauri#353]
With the introduction of Github Actions [checkout@v2](https://github.com/actions/checkout), it makes sense to move our examples into the [other repo](https://github.com/tauri-apps/examples). We can still [run the tests here](https://github.com/actions/checkout#checkout-multiple-repos-side-by-side), but don't have the noise of the Renovate bot and package updates.

I think it makes sense to keep things structured similar to this repo with an examples folder in the root. The first step would be to add all of the existing examples to the example repo. I believe there are [ways to import these](https://github.com/lerna/lerna/tree/master/commands/import) to retain the git history. Next we can do the same with the Github Actions that run the smoke tests on PR. And finally we can adjust the Github Actions in the main Tauri repo to point at the new examples repo.

**Comment by jbolda** [comment]
This is also noted here: https://github.com/tauri-apps/examples/issues/3

**Comment by jswhisperer** [comment]
Was really hard to find the examples repo... maybe it should be on https://tauri.studio/

**Comment by jbolda** [comment]
@gregbenner the plan is to use those examples more for internal testing. We have started and are working on adding a `create-tauri-app` that will let one spin up an app much quicker. I don't think we have opened an issue for it yet, but it will show up in https://github.com/tauri-apps/tauri/discussions/1032 likely.
/cc @nklayman
