### ISSUE TITLE
[feat] Specify resource file target path

### ISSUE THREAD

**Issue by J-F-Liu** [tauri-apps/tauri#3539]
### Describe the problem

The resource files in `tauri.conf.json` bundle config go to separate folders when the package is installed.
For example,
```
  "resources": [
    "system.ini",
    "config.ron"
  ],
```
Run the bundled MSI file and get the following result:
<img width="128" alt="image" src="https://user-images.githubusercontent.com/1472963/155271642-ff1472b9-871c-4f86-a86a-1b56ed3f94de.png">
This is a strange behavior.

### Describe the solution you'd like

My expection is to put the resources files in the same folder as the executable file.

To be more flexible, should use the same relative path as it is in the "resources" config.
For example, "conf/system.ini" is installed as "%Program Files%/%ProgramName%/conf/system.ini".

**Comment by lucasfernog** [comment]
We do install it on the same dir as the executable on Windows, and use the same relative path. This sounds like an issue when checking if the resource is a file or directory. I can investigate tomorrow.
