### ISSUE TITLE
[bug] unresolved macro

### ISSUE THREAD

**Issue by theo-coder** [tauri-apps/tauri#3542]
### Describe the bug

![image](https://user-images.githubusercontent.com/57922624/155336775-6671fd3d-3c6c-4154-af7d-42095df5d02c.png)
My code editor do not like this...

### Reproduction

Just start a new tauri project

### Platform and versions

```shell
Operating System - Arch Linux, version Rolling Release X64

Node.js environment
  Node.js - 17.4.0
  @tauri-apps/cli - 1.0.0-rc.5
  @tauri-apps/api - 1.0.0-rc.1

Global packages
  npm - 8.3.1
  pnpm - 6.28.0
  yarn - 1.22.17

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-unknown-linux-gnu 

App directory structure
/src
/dist
/node_modules
/src-tauri

App
  tauri - 1.0.0-rc.3
  tauri-build - 1.0.0-rc.3
  tao - 0.6.2
  wry - 0.13.2
  build-type - bundle
  CSP - unset
  distDir - ../dist
  devPath - http://localhost:3000/
  framework - React
```

**Comment by FabianLars** [comment]
That's not a tauri bug. It's rust-analyzer's macro support not being perfect (yet). Enabling one or both of these settings should fix it tho:
```json
"rust-analyzer.procMacro.enable": true,
"rust-analyzer.experimental.procAttrMacros": true,
```
Even if it doesn't it's not really important as it still compiles fine (but i get that it's annoying to have an open error in your editor all the time).

**Comment by SeedyROM** [comment]
@FabianLars Changing those settings does not remove the error. but it does compile so whatever for now.

**Comment by naca-nyan** [comment]
```json
  "rust-analyzer.procMacro.enable": false
```

works for me.
