### ISSUE TITLE
[bug] custom scheme protocol not allowed to load js script file in iframe

### ISSUE THREAD

**Issue by l1xnan** [tauri-apps/tauri#3543]
### Describe the bug

Custom scheme protocol not allowed to load js script file in iframe. DevTools console error:
```
GET https://test.localhost/hello.js net::ERR_CONNECTION_REFUSED
```

### Reproduction

code snippet:
```rs
fn handle_register_uri_scheme_protocol(
  _app: &AppHandle,
  request: &Request,
) -> Result<Response, Box<dyn Error>> {
  let mut path = request.uri().replace("https://test.localhost/", "");
  println!("path: {}", path);
  let content = read(canonicalize(&path)?)?;
  let (data, meta) = if path.ends_with(".html") {
    (content, "text/html")
  } else if path.ends_with(".js") {
    (content, "text/javascript")
  } else if path.ends_with(".png") {
    (content, "image/png")
  } else {
    unimplemented!();
  };
  ResponseBuilder::new().mimetype(meta).body(data)
}

fn main() {
  tauri::Builder::default()
    .register_uri_scheme_protocol("test", handle_register_uri_scheme_protocol)
    .invoke_handler(tauri::generate_handler![])
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
```

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
  <h1>Welcome to WRY!</h1>
  <a href="/hello.html">Link</a>
  <script type="text/javascript" src="/hello.js"></script>
  <img src="/icon.png" />
</body>
</html>
```
Similar wry example: https://github.com/tauri-apps/wry/blob/dev/examples/custom_protocol.rs

### Expected behavior

Js files can be loaded by `script` tag. Need to configure `csp`?

### Platform and versions

```shell
Operating System - Windows, version 10.0.22000 X64
Webview2 - 98.0.1108.56
Visual Studio Build Tools:
   - Visual Studio 2022

Node.js environment
  Node.js - 16.13.0
  @tauri-apps/cli - 1.0.0-rc.5
  @tauri-apps/api - 1.0.0-rc.1

Global packages
  npm - 8.1.0
  pnpm - Not installed
  yarn - 1.22.17

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-pc-windows-msvc 

App directory structure
/.git
/.vscode
/dist
/node_modules
/src
/src-tauri

App
  tauri - 1.0.0-rc.3
  tauri-build - 1.0.0-rc.3
  tao - 0.6.2
  wry - 0.13.2
  build-type - bundle
  CSP - unset
  distDir - ../dist
  devPath - http://localhost:3000/
  framework - React
```

**Comment by lucasfernog** [comment]
You need to set the `Access-Control-Allow-Origin` header to the iframe origin, like `ResponseBuilder::new().header("Access-Control-Allow-Origin", "https://test.localhost")`. We automatically do that for the tauri and asset protocols (your test one looks really similar to the asset one, though you'll need to setup the asset scope).
Let me know if you face any problems.

**Comment by maxiloEmmmm** [comment]
@lucasfernog hello, same question, resource load failed in iframe
![image](https://user-images.githubusercontent.com/16779121/224316738-6a85838e-4e6a-441a-a59c-2d759b621726.png)
![image](https://user-images.githubusercontent.com/16779121/224316586-177f0fed-ad07-4b63-936f-1050f225a9f3.png)
![image](https://user-images.githubusercontent.com/16779121/224317439-d5b44317-3f09-41ec-ae94-83cb082e4cea.png)
note: `src` is the same for both iframe's
### front
```jsx
render() {
    return <>
        <iframe src={convertFileSrc(this.test, "dic")}/>
    </>
}
```

### end
```rust
.register_uri_scheme_protocol("dic", |ah, req| {
  let data = read("d:\\text.html");
  ResponseBuilder::new().header("Access-Control-Allow-Origin", "https://dic.localhost").body(data.unwrap())
})
```

**Comment by ezewu** [comment]
Is this problem solved? I also encountered that js cannot be loaded inside the iframe

**Comment by l1xnan** [comment]
> Is this problem solved? I also encountered that js cannot be loaded inside the iframe

Guess it needs [`CustomSchemeRegistrations`](https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/specs/WebResourceRequested-CustomScheme.md) API, The current [`webview2-com`](https://docs.rs/webview2-com/latest/webview2_com/) version of Tauri is not supported.

**Comment by ezewu** [comment]
Upgrading webview2-com can solve it, right?
