### ISSUE TITLE
[bug] Wix installer > Launch process points to wrong path

### ISSUE THREAD

**Issue by Snazzie** [tauri-apps/tauri#3547]
### Describe the bug

The wix installer's final step where you can check `Launch Process` actually launches the executable in /target/release (dev environment build output) instead of the one located in the production install folder from wix.

![image](https://user-images.githubusercontent.com/19627023/155442353-f306b8f7-c35b-4b77-b002-b2392e051884.png)
![image](https://user-images.githubusercontent.com/19627023/155442668-17b93028-1f20-4d74-9130-f4143f1142bd.png)

### Reproduction

1. tauri build
2. execute installer msi
3. tick Launch process now and press finish
4. check running process Properties > Security > Object Name  or open file file location

### Expected behavior

`Launch process` should launch the executable in the install folder not dev environment build output folder

### Platform and versions

```shell
PS D:\Repo\Affinity\Source\ClientApp> npm run tauri info

> Vital Utilities@0.0.1 tauri
> tauri "info"


Operating System - Windows, version 10.0.22000 X64
Webview2 - 98.0.1108.56
Visual Studio Build Tools:
   - Visual Studio Community 2022

Node.js environment
  Node.js - 17.4.0
  @tauri-apps/cli - 1.0.0-rc.5
  @tauri-apps/api - 1.0.0-beta.8 (outdated, latest: 1.0.0-rc.1)

Global packages
  npm - 8.4.1
  pnpm - 6.30.0
  yarn - 1.22.10

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-pc-windows-msvc 

App directory structure
/.vscode
/bin
/build
/buildtemp
/config
/node_modules
/public
/src
/src-tauri

App
  tauri - 1.0.0-rc.3
  tauri-build - 1.0.0-rc.3
  tao - 0.6.2
  wry - 0.13.2
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:3000/
  framework - React
```

### Additional context

i have following in my cargo toml 
```
[profile.release.package.wry]
debug = true
debug-assertions = true

[profile.dev.package.wry]
debug = true
debug-assertions = true
```
Additionally, i build my msi without specifying the --release in tauri build. this is intentional to enable dev tools in the production environment, due to you guys choosing to disable it for release builds.

**Comment by xuchaoqian** [comment]
Maybe not related to the bug, but it's useful for your use case.

Put "devtools" flag to Cargo.toml to enable "devtools" feature in release build.  Just like ths:
`tauri = { git = "https://github.com/tauri-apps/tauri.git", branch = "dev", features = ["devtools", "dialog-all", "macos-private-api", "path-all", "process-exit", "process-relaunch", "shell-open", "window-all"] }`

**Comment by Snazzie** [comment]
> Maybe not related to the bug, but it's useful for your use case.
> 
> Put "devtools" flag to Cargo.toml to enable "devtools" feature in release build. Just like ths: `tauri = { git = "https://github.com/tauri-apps/tauri.git", branch = "dev", features = ["devtools", "dialog-all", "macos-private-api", "path-all", "process-exit", "process-relaunch", "shell-open", "window-all"] }`

Awesome! is this only available on dev branch atm?

**Comment by nothingismagick** [comment]
https://docs.rs/tauri/1.0.0-rc.3/tauri/index.html#cargo-features

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/35242872/155507945-c6af9668-63d4-43b6-8297-2d18bca4d1a8.png">
