### ISSUE TITLE
drag & drop : event.dataTransfer.files  always [ ], empty

### ISSUE THREAD

**Issue by mxismean** [tauri-apps/tauri#3558]
### Describe the bug

I want to develop an application that drags and drogs local images to compress.

<img width="296" alt="image" src="https://user-images.githubusercontent.com/44690729/155690802-df3a469f-ae75-4b51-a916-3070a10ab968.png">

<img width="313" alt="image" src="https://user-images.githubusercontent.com/44690729/155691446-0454c43d-247a-4c8f-b09a-1cfacb6a93e7.png">

I used webView `drag` and `drop` events, but the `drop` event kept failing. I can only go to the `dragenter` event and get the `event` object and get the `files`, but `event.datatransfer.files` always returns an empty array. How do I get the file?

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/44690729/155693330-463237a3-cd43-4617-a5ee-c6e043d3bbcb.png">

Total exposure to deal with these problems：

1. The `drop` event cannot be triggered.
2. `event.datatransfer.files` always returns an [].

I tried to use `"tauri://file-drop"` to listen for dragging files to get the `file path`, but due to tauri limitations, `readBinaryFile` api cannot get the file contents from the file path.

How do I drag and drop images to upload and get the content？

### Platform and versions

```shell
yarn tauri info
yarn run v1.22.17
$ tauri info

Operating System - Mac OS, version 12.2.1 X64

Node.js environment
  Node.js - 14.19.0
  @tauri-apps/cli - 1.0.0-rc.5
  @tauri-apps/api - 1.0.0-rc.1

Global packages
  npm - 6.14.16
  pnpm - Not installed
  yarn - 1.22.17

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-apple-darwin

App directory structure
/dist
/node_modules
/public
/src-tauri
/.vscode
/src

App
  tauri - 1.0.0-rc.3
  tauri-build - 1.0.0-rc.3
  tao - 0.6.2
  wry - 0.13.2
  build-type - bundle
  CSP - unset
  distDir - ../dist
  devPath - http://localhost:3000/
  framework - Vue.js
✨  Done in 23.54s.
```

**Comment by FabianLars** [comment]
This is exactly why we have the `tauri://file-drop` events.
(Unfortunately?) you need to read the files in rust until we have the whitelist for user-selected paths in place.

**Comment by mxismean** [comment]
Roughly which version can publish whitelist functionality？

**Comment by FabianLars** [comment]
We don't know this yet, especially since it's something the auditors most likely need to take a look at too.

**Comment by mxismean** [comment]
😂 Looking forward to it!

**Comment by hooperdev** [comment]
I found that mine does work, and it is just a bug in the console. See https://stackoverflow.com/a/11573873/9462397.
BTW, it is probably still better and more reliable to use tauri://file-drop, but if you can't because of pre-existing libraries needing HTML5 drag + drop (see #5567), this way does actually work.
