### ISSUE TITLE
Use strip functionality in rustc and cargo

### ISSUE THREAD

**Issue by JamesYeoman** [tauri-apps/tauri#3559]
As [this todo](https://github.com/tauri-apps/tauri/blob/8d699283a4741c83b476fb079dc0333c7bf4f919/tooling/cli/src/build.rs#L368) mentions, strip functionality wasn't stable at the time of writing.

However, the rustc issue mentioned (rust-lang/rust#72110) has been closed since 16th november 2021, and the release that contains the strip functionality is 1.58, which is already out by now.

As for Cargo, their corresponding issue (rust-lang/cargo#10088) has been addressed, and while I can't seem to find a changelog for cargo, [the docs](https://doc.rust-lang.org/cargo/reference/profiles.html#strip) seem to indicate that there's a release out that introduced the stablised option

I'd say that satisfies the requirements for the todo to be put in motion.

**Comment by FabianLars** [comment]
The release of cargo that added this functionality came out literally _yesterday_: https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md

**Comment by JonasKruckenberg** [comment]
> I'd say that satisfies the requirements for the todo to be put in motion.

Absolutely, I was planning to write that section even before 1.59, but I won't get to it before Monday.
If you have the time feel free to open a PR against tauri-apps/tauri-docs!
