### ISSUE TITLE
Running out of memory with `tauri dev`

### ISSUE THREAD

**Issue by 3rd** [tauri-apps/tauri#356]
**Describe the bug**
Running `tauri dev` keeps eating memory until cargo gets killed.
[Screen recording of what happens](https://u.gist.ro/selif/c4o3bp3s.webm)

**To Reproduce**
`tauri dev`

```
➜ tauri dev
[tauri]: running dev
 app:spawn Running "cargo run --features dev-server" +0ms
warning: unused manifest key: package.author
   Compiling app v0.1.0 (/home/rabbit/brain/projects/_samples/tauri/simple/src-tauri)
   Compiling tauri v0.3.2
 app:tauri (template) Cargo process was killed. Exiting... +0ms
 app:tauri Shutting down tauri process... +4ms
```

**Expected behavior**
No error.

**Screenshots**

**Platform and Versions (please complete the following information):**

OS: Linux(5.4.15-arch1-1) - linux/x64
Node: 12.14.1
NPM: 6.13.4
Yarn: 1.21.1
Rustc: 1.42.0-nightly

**Additional context**
Let me know if there's anything I can do to help. I'm going to investigate further and report back.
Thank you!

**Comment by 3rd** [comment]
Hey, it was a simple parcel/typescript/react setup. I managed to trigger the issue while working on a project with `futures`, seems like there was some memory leak.
Running `rustup update` fixed the issue for me, sorry for the wasted time!

![happy tauri](https://i.imgur.com/Gc3JrT4.png)

**Comment by nothingismagick** [comment]
A yes, the problem of uncertain futures. Well, glad you got it sorted!
