### ISSUE TITLE
[feat] Add option to disable window show/hide transitions

### ISSUE THREAD

**Issue by moxaj** [tauri-apps/tauri#3565]
### Describe the problem

Currently, on windows, showing / hiding a window isn't instantenious, there's a short fade-in / fade-out transition. This is very slightly inconvenient for my current use case (an always-on-top pseudo-fullscreen overlay window, toggled by global hotkeys).

### Describe the solution you'd like

I'd like both the window builder and the window API to include an additional method to enable / disable such transitions.

### Alternatives considered

none

### Additional context

FWIW (and forgive my terrible rust), I was able to achieve this by directly calling the windows API:

```
#[cfg(target_os = "windows")]
use windows::Win32::{
    Foundation::{BOOL, HWND},
    Graphics::Dwm::{DwmSetWindowAttribute, DWMWA_TRANSITIONS_FORCEDISABLED},
};

...

if cfg!(target_os = "windows") {
    if let Ok(hwnd) = window.hwnd() {
        unsafe {
            let _ = DwmSetWindowAttribute(
                std::mem::transmute::<*mut c_void, HWND>(hwnd),
                DWMWA_TRANSITIONS_FORCEDISABLED,
                &mut BOOL::from(true) as *mut _ as *mut c_void,
                std::mem::size_of::<BOOL>() as u32,
            );
        }
    }
}
```

**Comment by amrbashir** [comment]
I don't think this should be provided directly by us. This is a rare case and I think it makes sense that you do it in your code instead.
