### ISSUE TITLE
[bug]  fs.readDir() throw `cannot traverse directory`

### ISSUE THREAD

**Issue by Janaka-Steph** [tauri-apps/tauri#3573]
### Describe the bug

`await fs.readDir()` throw with "cannot traverse directory".
It happens only with `cargo tauri dev`, but not `cargo tauri build --debug`.

I tried `await tauriAPIs.fs?.readDir('tdex-dashboard', { dir: tauriAPIs.fs?.Dir.App }); `
and `await tauriAPIs.fs?.readDir('tdex-dashboard');`

Config
```
 "tauri": {
    "allowlist": {
      "all": true,
      "fs": {
        "all": true,
        "scope": ["$APP/tdex-dashboard"]
      }
    },
```

### Platform and versions

```shell
▶ cargo tauri info

Operating System - Mac OS, version 12.2.1 X64

Node.js environment
  Node.js - 16.14.0
  @tauri-apps/cli - 1.0.0-rc.5
  @tauri-apps/api - 1.0.0-rc.1

Global packages
  npm - 8.1.4
  pnpm - Not installed
  yarn - 1.22.17

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-aarch64-apple-darwin 

App directory structure
/node_modules
/public
/scripts
/.github
/src-tauri
/build
/.git
/.idea
/src

App
  tauri - 1.0.0-rc.3
  tauri-build - 1.0.0-rc.3
  tao - 0.6.2
  wry - 0.13.2
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:3003/
  framework - React
  bundler - Webpack
```

**Comment by lucasfernog** [comment]
Tried this with the example API (scope: `"scope": ["$APP/tdex-dashboard"]`, call: `readDir('tdex-dashboard', { dir: Dir.App }).then(console.log).catch(console.error)` and it worked. I'll need an example to reproduce this :/

**Comment by Janaka-Steph** [comment]
I tried on my app like you did
```
 tauriAPIs.fs
        ?.readDir('tdex-dashboard', { dir: tauriAPIs.fs?.Dir.App })
        .then(console.log)
        .catch(console.error);
```
And got an interesting error: path: `/Users/stephane/Library/Application Support/tdex-dashboard/tdex-dashboard: No such file or directory (os error 2)`
"tdex-dashboard" is twice in the path
