### ISSUE TITLE
Expose `TAURI_CSP` to before*Command

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri#3581]
### Describe the problem

CSPs don’t work with development servers. This causes confusion with many users as they suddenly face a broken app when building for production.

### Describe the solution you'd like

Expose a `TAURI_CSP` environment variable to the `beforeDevCommand` and `beforeBuildCommand` to allow users to programmatically inject the CSP in development.

**Comment by lucasfernog** [comment]
We inject the CSP at runtime, reading all assets to hash JS and CSS files, and nonce other inline usages such as external scripts. So this is not really possible unless we create a Webpack/Rollup/Vite plugin.

**Comment by JonasKruckenberg** [comment]
Yeah true, forgot about that nonce thingy. nvm
