### ISSUE TITLE
[feat] Tauri should provide the power of unsafe inline javascript 

### ISSUE THREAD

**Issue by ikey4u** [tauri-apps/tauri#3583]
### Describe the problem

Tauri has introduced CSP (Content Security Policy) to make tauri app more security. Take an example html  below

```
  <!DOCTYPE html>
  <html>
    <head>
      <meta charset="UTF-8" />
      <meta http-equiv="Content-Security-Policy" content="
        default-src blob: data: filesystem: ws: wss: http: https: tauri: 'self' img-src: 'unsafe-inline';
        script-src http: https: 'self' 'unsafe-inline';
      ">
      
  <script>
      function testme() {
        console.log("inline click");
      }
  </script>

    </head>
    <body>
      <div>
        <button onclick="testme()">click me inline</button>
      </div>
    </body>
  </html>
```
with security section of  `tauri.conf.json` as
```
  "security": {
    "csp": "default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-inline' 'self' img-src:; script-src http: https: 'unsafe-inline';"
  }
```

I have declared `unsafe-infline` both in tauri's configuration and meta in the html, it works in modern browser (let's say chrome), but it does not work in tauri with the reason `Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.`.

Thanks the kind answer from @FabianLars who told me that it works as intended.  And the reason why `unsafe-inline` does not work is that `unsafe-inline has no effect because the inline script tags are hashed in tauri apps`.

I know the intent is good, of course, for security. But this really limits the power of web development (for example, we can not do  dynamic js loading, inline click event and so on). Like `unsafe` related concepts in Rust, mostly of the time, you do not need them, but if you want, you can.  I hope Tauri can provide developers with this power.

### Describe the solution you'd like

1) Give developer the ability to enable unsafe-inline javascript in configuration `tauri.config.json`. If he does declare `unsafe-inline` for script, tauri should ensure we can do `unsafe-line` rather than hash the script tag that make the unsafe-inline not work.

2) Provide CSP related options to the  developer, the developer in turn can ask and warn the user the dangerous, and let the user make choice.

### Additional context

Related issue #3543

**Comment by nothingismagick** [comment]
Are you sure this isn't a typo?
```
    "csp": "default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-inline' 'self' img-src:; script-src http: https: 'unsafe-inline';"
```

the `img-src:;` bothers me

I would expect something like:
`img-src data: 'self';` perhaps.

`unsafe-inline` SHOULD work but maybe I am missing a nuance here.

**Comment by nothingismagick** [comment]
I know this, because WASM injection requires `unsafe-inline`...

**Comment by FabianLars** [comment]
It seems to be the specific combination of the inline `onclick` and the hashing of the inline script tags that we do.

For example, it works fine if you remove the onclick and register the listener in the inline script tag instead.

Edit: Furthermore this seems to be something we can't change without disabling the hashing.

**Comment by ikey4u** [comment]
@nothingismagick 
Both 
```
I would expect something like:
img-src data: 'self'; perhaps.
```
and
```
img-src: 'self';
```
are correct. But they are not related with the script CSP and do not solve the problem. Maybe the idea mentioned by @FabianLars is a solution.

**Comment by pwespi** [comment]
> It seems to be the specific combination of the inline `onclick` and the hashing of the inline script tags that we do.
> 
> For example, it works fine if you remove the onclick and register the listener in the inline script tag instead.
> 
> Edit: Furthermore this seems to be something we can't change without disabling the hashing.

I think you are right.

This CSP:
```html
<meta
  http-equiv="Content-Security-Policy"
  content="default-src 'self'; script-src 'self' 'unsafe-inline' 'sha256-UwOUi0kvnOGujbF8Ra44WrjWv/rqLkiQTxq+1b+/k7w='; style-src 'self' 'unsafe-inline';"
/>

```
results in the following error in Edge:

```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'sha256-UwOUi0kvnOGujbF8Ra44WrjWv/rqLkiQTxq+1b+/k7w='".
Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.
```

So `unsafe-inline` is ignored if you add a hash value (which is done by Tauri as far as I understand).

**Comment by nothingismagick** [comment]
this is interesting:
https://stackoverflow.com/a/67602355

**Comment by lucasfernog** [comment]
Now it's possible to disable the Tauri CSP injection, so you'll have full control over it if it's messing with your app. See #3775 and #4021
