### ISSUE TITLE
[feat] support disabled CORS

### ISSUE THREAD

**Issue by zenghongtu** [tauri-apps/tauri#3604]
### Describe the problem

I was migrating an electron project to tauri, which used a third-party API that does not support cross-domain requests, and i can be disabled using websecurity in electron, but I didn't find a configuration in tauri.

### Describe the solution you'd like

websecurity:false

**Comment by lucasfernog** [comment]
CORS can't be bypassed on the webviews. You can use the Rust APIs to make HTTP requests: https://tauri.studio/docs/api/js/modules/http
