### ISSUE TITLE
[feat] More event or api for updater

### ISSUE THREAD

**Issue by zzzgydi** [tauri-apps/tauri#3605]
### Describe the problem

I want to kill the sidecar when the app has been downloaded and is going to be installed. Because I noticed that the sidecar does not quit when the app exit.

If I write my code below. I should restart my sidecar when the installer failed. Not only that, when my sidecar is providing some kind of service, and the service has to be stopped during the app update.

```javascript
await killSidecars();
await installUpdate();
await relaunch();
```

If I do this like below. The sidecar does not be killed... 

```javascript
await installUpdate();
await killSidecars();
await relaunch();
```

### Describe the solution you'd like

I see a todo tag in the code [here](https://github.com/tauri-apps/tauri/blob/0f1558980a0fb1d6c042988e173047f0590b6574/core/tauri/src/updater/core.rs#L418). It will be helpful for me if done.

Or if there is a event like `tauri://update-download`, maybe this will work too. (But this may have a problem)

Further considerations, will it support to get the download progress, it only support the `update-status: [ERROR/PENDING/DONE]` right now.

**Comment by lucasfernog** [comment]
Let's fix the cleanup issue first :)

**Comment by lucasfernog** [comment]
Changing how the update is download and installed is more complicated, we'll have to do it on another time. It'll also need to be audited again since the updater is one of the major security risks. But at least we can fix your issue.

**Comment by zzzgydi** [comment]
Thanks for your help!!!
