### ISSUE TITLE
[bug] Window Size Increases When Dragging Across Monitors Of Different DPI Scale

### ISSUE THREAD

**Issue by zacbre** [tauri-apps/tauri#3610]
### Describe the bug

Window size increases when dragged between 2 monitors with different DPI settings...This does not happen when window decorations are enabled, so I'm suspecting it has something to do with compensating for the height of the titlebar in the window.

When I first startup my app, here's what it looks like (started on a 150% dpi scaled monitor):
![image](https://user-images.githubusercontent.com/5459179/156654722-9a1f6f02-7df6-43a6-854b-95901f168280.png)

After dragging to a 100% scaled monitor and back, it looks like this:
![image](https://user-images.githubusercontent.com/5459179/156654796-b7cf90ce-30a9-40ef-867f-2ee8a98b7fca.png)

After 4 or 5 times it looks like this:
![image](https://user-images.githubusercontent.com/5459179/156654845-39549eac-6681-4681-ae3e-5837ac6916eb.png)

### Reproduction

Have more than one monitor and set one to a different DPI scale than the other. Start up window on the DPI scaled monitor.
Create a basic tauri project, can be empty. Set window decorations to false in config for your default window. Make sure to have a `data-tauri-drag-region` to be able to drag.

Drag window back and forth and watch the size increase.

### Expected behavior

Dragging back and forth between two monitors that have different DPI scaling should not increase the window size.

### Platform and versions

```shell
System - Windows, version 10.0.22000 X64
Webview2 - 98.0.1108.62
Visual Studio Build Tools:
   - Visual Studio Community 2019

Rust environment
  rustup - 1.24.3
  rustc - 1.60.0-nightly
  cargo - 1.60.0-nightly
  toolchain - nightly-x86_64-pc-windows-msvc
```

**Comment by maoly1012** [comment]
Is there a solution?

**Comment by amrbashir** [comment]
related to tauri-apps/tao#194

**Comment by amrbashir** [comment]
can you guys add this in your `Cargo.toml` and see if the issue is fixed? 
```toml
[patch-crates-io]
tao = { git = "https://github.com/tauri-apps/tao", branch = "fix/windows/set-size-overflow }
```
