### ISSUE TITLE
^1.0.0-rc.1 writeBinaryFile still writes empty file

### ISSUE THREAD

**Issue by simmslabs** [tauri-apps/tauri#3614]
### Describe the bug

writeBinaryFile still writes empty file with ArrayBuffer or Blob in this version ^1.0.0-rc.1 

### Reproduction
```
for (let i = 0; i < fileList.length; i++) {
    const content = await getFileContent(fileList[i].url) // return e.g {ext: "png", arrayBuffer: ArrayBuffer};
    const fname = getRandomFilename(content.ext) // return e.g `${new Date().getTime()}.${ext}`;
    const fPath = `simmslabs${path.sep}gensys${path.sep}images${path.sep}${fname}` // resides in the user's dir;
    await fs.writeBinaryFile({ contents: content.arrayBuffer, path: fPath }, { dir: Dir.Home });
}

```
_No response_

### Platform and versions

```shell
Operating System - Mac OS, version 11.4.0 X64

Node.js environment
  Node.js - 14.17.0
  @tauri-apps/cli - 1.0.0-rc.5
  @tauri-apps/api - 1.0.0-rc.1

Global packages
  npm - 8.4.1
  pnpm - Not installed
  yarn - 1.22.10

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-apple-darwin 

App directory structure
/dist
/node_modules
/src-tauri
/.git
/src

App
  tauri - 1.0.0-rc.3
  tauri-build - 1.0.0-rc.3
  tao - 0.6.2
  wry - 0.13.2
  build-type - bundle
  CSP - default-src 'self'; img-src 'self' asset: https://asset.localhost
  distDir - ../dist
  devPath - http://localhost:3000/
  framework - React
```

**Comment by JonasKruckenberg** [comment]
Can you provide code samples and steps to reproduce this bug?

**Comment by simmslabs** [comment]
@[JonasKruckenberg](https://github.com/JonasKruckenberg), Kindly check Reproduction for sample code

**Comment by lucasfernog** [comment]
You need to convert it to `Uint8Array` using `new Uint8Array(arraybuffer)` before sending it to the API. If you used typescript you'd catch this as our API typings does not allow ArrayBuffer to be passed to `writeBinaryFile`.

**Comment by simmslabs** [comment]
Thank you @[lucasfernog](https://github.com/lucasfernog) i will try that on my next project. I rather created a custom_command to handle that. Hope your answer helps another newbie.

**Comment by gdotdesign** [comment]
I just run into this issue and can confirm that converting to `Uint8Array` works. Was this in the changelog somewhere?

**Comment by t3touch** [comment]
@gdotdesign Hi, how do I convert a PDF, which comes as string from an PHP script via file_get_contents() into Uint8Array ?

I tried this:

```
const content = Uint8Array.from(data.split('').map(letter => letter.charCodeAt(0)));
console.log('content', content)

const path = await save()
    .then(async (path) => {
        console.log('path', path)
        await writeBinaryFile({path, contents: content});
    }).catch((error) => {
        console.log('error', error)
    });
```

data is the string from API and looks like:

```
%PDF-1.7 %���� 5 0 obj << /Type /Page /Parent 1 0 R /LastModified (D:20230118201531+00'00') /Resources 2 0 R /MediaBox [0.000000 0.000000 595.276000 841.890000] /CropBox [0.000000 0.000000 595.276000 841.890000] /BleedBox [0.000000 0.000000 595.276000 841.890000] /TrimBox [0.000000 0.000000 595.276000 841.890000] /ArtBox [0.000000 0.000000 595.276000 841.890000] /Contents 6 0 R /Rotate 0 /Group << /Type /Group /S /Transparency /CS /DeviceRGB >> /PZ 1 >> endobj 6 0 obj <> stream x��Z[s�F~�W���.......
```
But the saved PDF has no content. The size of 8kb is the same as the original pdf size.

**Comment by gdotdesign** [comment]
I think I got it working like this (for reading):

```
const contents =
  await Tauri.fs.readBinaryFile(path)

const bytes =
  new Uint8Array(contents.length);

for (let i = 0; i < contents.length; i++) {
  bytes[i] = contents[i]
}

new File([bytes], "some_file.pdf", { type: 'application/pdf' })
```

for writing:
```
let reader = new FileReader();

reader.addEventListener('load', (event) => {
  Tauri.fs.writeBinaryFile({
    contents: new Uint8Array(reader.result),
    path: path
  })
})

reader.readAsArrayBuffer(file)
```

**Comment by t3touch** [comment]
@gdotdesign Thanks for your hint. In my case the `axios responseType blob `was missing. After adding I got instead the String an Blob. And I can now this Blob with `data.arrayBuffer()` in a Uint8Array converting. 

BTW: arrayBuffer() is in older Safari not available. But there is an package `file2arraybuffer` available, which converts in older versions properly.
