### ISSUE TITLE
[feat] set_visible for tauri::SystemTrayHandle

### ISSUE THREAD

**Issue by zsmatrix62** [tauri-apps/tauri#3615]
### Describe the problem

the need is to show/hide system tray on the fly by user's configuration for example, i just checked the doc that this feature is not implemented yet.

https://docs.rs/tauri/1.0.0-rc.3/tauri/struct.SystemTrayHandle.html

### Describe the solution you'd like

implement `set_visible` function to `tauri::SystemTrayHandle`, signature would be like:

pub fn set_visible(&self, visible: bool) -> Result<()>

**Comment by dfaust** [comment]
This has been implemented. The issue can be closed.
