### ISSUE TITLE
[bug] can't open when i use macos installer

### ISSUE THREAD

**Issue by naaive** [tauri-apps/tauri#3626]
### Describe the bug

<img width="299" alt="image" src="https://user-images.githubusercontent.com/73341653/156961006-11126321-b150-426b-b583-b87902baf2ce.png">

i can open app via terminal, but when i open it from spotlight, it issue a dialog as above.

i guess the reason is that the permission issue. it will travel the filesystem.

here is my tauri config
https://github.com/naaive/orange/blob/master/src-tauri/tauri.conf.json

### Reproduction

1.download https://github.com/naaive/orange
2.build it from source
3.install with bundle Orange_0.0.4_aarch64
4.open it from spotlight

### Platform and versions

```shell
Operating System - Mac OS, version 11.3.1 X64

Node.js environment
  Node.js - 14.17.6
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.15
  yarn - 1.22.11

Rust environment
  rustc - 1.57.0
  cargo - 1.57.0

App directory structure
/screenshot
/node_modules
/public
/src-tauri
/doc
/build
/.git
/.idea
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src asset: blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:3000
  framework - React

```

**Comment by nothingismagick** [comment]
Please update to the latest tauri RC.

**Comment by lucasfernog** [comment]
Try using the PathResolver an app_dir APIs instead of relying on the CWD, that might be the issue too.

**Comment by nothingismagick** [comment]
Rustc is also out of date.

**Comment by naaive** [comment]
> Try using the PathResolver an app_dir APIs instead of relying on the CWD, that might be the issue too.

CWD is the root path (`/`) when open app from spotlight.
I resolve this issue by set app data path, use lib https://crates.io/crates/directories

very thanks!

**Comment by naaive** [comment]
> Please update to the latest tauri RC.

thanks for your response!
