### ISSUE TITLE
[feat] Add start and terminate lifecycle hooks

### ISSUE THREAD

**Issue by red010182** [tauri-apps/tauri#3627]
### Describe the problem

Just like setup, it is very common to do some things before app quit (like clean up or save config or kill child process).

In iOS development, Apple's framework offers a bunch of application level lifecycle hooks like: `application(_:didFinishLaunchingWithOptions:)` or `applicationWillTerminate`, which is very easy to work with.

### Describe the solution you'd like

It would be wonderful if we could have something like this:

```rust
#[
  tauri::app_will_terminate, // automatically invoked before termination
  tauri::shortcut("CMD+Q"),  // automatically register shortcut to this fn
  tauri::menu("quit_app") // automatically register menu item action  to this fn
]
fn app_will_terminate(app: &tauri::App) {
  ...
}

// since we have terminate hook, it's also convenience to have a setup hook
#[tauri::app_did_launch] // automatically invoked right after app launched
fn app_did_launch(app: &tauri::App) {
  ...
}
```

**Comment by amrbashir** [comment]
We already have that, check it in our example/api here https://github.com/tauri-apps/tauri/blob/5293445f08f1484639ad9f56c45aad53039ba579/examples/api/src-tauri/src/main.rs#L215-L257 .

**Comment by red010182** [comment]
@amrbashir Thanks for that. Didn't see this on doc.
