### ISSUE TITLE
Additional Build Configurations

### ISSUE THREAD

**Issue by alvaroblanco1** [tauri-apps/tauri#3632]
### Describe the problem

Hi,

I just recently started learning about Tauri in general. I have an angular app that I localize to both Spanish and English and build them both at the same time in angular. However, I have not yet seen a way to configure Tauri to allow me to build a windows version from each localized version. 

Currently I have to build the html, js, css bundle of one language then build the tauri version of that. Then I have to build the spanish version and change my tauri.conf.json to create another windows version. 

### Describe the solution you'd like

My idea is to allow for either multiple build configs in the tauri.conf.json page.

Alternatively, though far more complicated, is a way to route different app version in the Tauri build. For example, I use Google Firebase and I am able to rewrite location rules in Firebase so that people can choose the US version or Colombia Version on the web.

**Comment by JonasKruckenberg** [comment]
From a UX point of view I strongly dislike applications that force you into a specific language.
So I tend towards something like your second alternative, letting the frontend dynamically change the language.

In general it's important to note we have this on our radar, but it'll be most likely implemented in a plugin, not the core itself.

**Comment by alvaroblanco1** [comment]
I would agree. Then the most likely option would be to have the program somehow read the locale version of the computer it is installed on and display that app version. I would just then need to figure out how to load both localized versions into Tauri due to the fact that each localized version has its own index.html.

I am unfortunately just not super familiar with Rust and would love to get into it but before I spend time and effort on it would something like this hypothetically possible in a plug in? (the having two index.html files and have an initial program read the computer locale version and decide which index.html to present?)

**Comment by nothingismagick** [comment]
This is something that you can do with CI. You can even merge tauri config files to point at different dist folders etc.

**Comment by alvaroblanco1** [comment]
> This is something that you can do with CI. You can even merge tauri config files to point at different dist folders etc.

Interesting. Because when I have angular compile the localized versions Tauri compiles but the program never starts.

  "build": {
    "distDir": "../dist/my-app/en",
    "devPath": "http://localhost:4200",
    "beforeDevCommand": "npm run serve",
    "beforeBuildCommand": "npm run build",
    "withGlobalTauri": true
  },

With this configuration the index.html for the US localized version is in the en folder but when Tauri builds it does not start the program. It remains a white screen. Inside my-app is an en folder and an es folder, each with an index.html page, representing the localized version of the app.

However, when I do not compile my angular app into the localized versions I have it set to this. And the app does work.
  "build": {
    "distDir": "../dist/my-app",
    "devPath": "http://localhost:4200",
    "beforeDevCommand": "npm run serve",
    "beforeBuildCommand": "npm run build",
    "withGlobalTauri": true
  },

So I am thinking that even if I make another conf.json, the app still won't work.

**Comment by lucasfernog** [comment]
Can you share a minimal repro to this issue? I'd like to see what the dist dir looks like and what's the problem.

**Comment by alvaroblanco1** [comment]
I made this repo here.

https://github.com/alvaroblanco1/localized-angular-sample

if you build the localized version with two languages in the folder en and es the tauri build does not work but not localized it does. At least on windows when I was testing.

**Comment by lucasfernog** [comment]
Since your `distDir` is `../dist/app/en`, all paths must be relative to `/` instead of `en` (e.g. `assets/style.css` instead of `en/assets/style.css`. Angular controls this via the `baseHref` property, which translates into `<base href="$baseHref">` in the HTML. This configuration fixed it:

```json
{
  "i18n": {
    "locales": {
      "en": {
        "translation": "src/locale/en.json",
        "baseHref": "/"
      },
      "es": {
        "translation": "src/locale/es.json",
        "baseHref": "/"
      }
    }
  }
}
```
