### ISSUE TITLE
[bug] (node:41354) UnhandledPromiseRejectionWarning: Error: failed to run cargo: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by LQS5858** [tauri-apps/tauri#3639]
### Describe the bug

When I add vue-cli-plugin-tauri to an existing vue project and run npm run tauri:serve throws an error (node:41354) UnhandledPromiseRejectionWarning: Error: failed to run cargo: No such file or directory (os error 2)

### Reproduction

First:vue add tauri
Second:npm run tauri:serve

### Platform and versions

```shell
Version:
    "vue-cli-plugin-tauri": "~1.0.0-rc.1"
    "vue": "^3.2.31",
```

**Comment by FabianLars** [comment]
Did you follow the [installation instructions](https://tauri.studio/docs/getting-started/prerequisites) for your OS?

**Comment by nothingismagick** [comment]
You still have to follow all the setup steps for your development platform. Please see this page:

https://tauri.studio/docs/getting-started/prerequisites/
