### ISSUE TITLE
[bug] `create_window` panics with `RecvError`

### ISSUE THREAD

**Issue by moxaj** [tauri-apps/tauri#3645]
### Describe the bug

The exact message I see in the logs:

`thread 'main' panicked at 'called Result::unwrap() on an Err value: RecvError': [...]\tauri-runtime-wry-0.3.2\src\lib.rs:1548`

which is [here](https://github.com/tauri-apps/tauri/blob/tauri-runtime-wry-v0.3.2/core/tauri-runtime-wry/src/lib.rs#L1548). The line is: `let window_id = rx.recv().unwrap();`.

The problem is, I cannot reproduce this on my system, the issue was reported by end users. FWIW, I call `create_window` on the main thread (from inside `Builder::setup`), but I was told that this should be fine.

### Platform and versions

```shell
Operating System - Windows, version 10.0.19043 X64
Webview2 - 99.0.1150.30
Visual Studio Build Tools:
   - Visual Studio Build Tools 2019

Node.js environment
  Node.js - 16.13.2
  @tauri-apps/cli - 1.0.0-rc.5 (outdated, latest: 1.0.0-rc.7)
  @tauri-apps/api - 1.0.0-rc.1 (outdated, latest: 1.0.0-rc.2)

Global packages
  npm - 8.5.1
  pnpm - Not installed
  yarn - Not installed

Rust environment      
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-pc-windows-msvc 

App directory structure
/.git
/.github
/build
/node_modules
/opencv
/public
/src
/src-tauri

App
  tauri - 1.0.0-rc.3
  tauri-build - 1.0.0-rc.3
  tao - 0.6.2
  wry - 0.13.2
  build-type - bundle
  CSP - unset
  distDir - ../build
  devPath - http://localhost:3000/
  framework - React
```

**Comment by lucasfernog** [comment]
PR fixing this: #3684
