### ISSUE TITLE
[feat] Clean up CLI

### ISSUE THREAD

**Issue by red010182** [tauri-apps/tauri#3661]
### Describe the problem

Is there any command that could clean up like `make clean`? The `src-tauri` takes 2.75GB in my small project. It would be better if the disk usage is small until next time I develope on it. Because you know, Macbook's disk space is always small.

### Describe the solution you'd like

```bash
pnpm tauri clean
# or
npm run tauri clean
```

**Comment by JonasKruckenberg** [comment]
Your problem is certainly valid, I just don't know if it warrants it's own subcommand.
The only action that command would perform is `rm -r src-tauri/target` something that you can do equally fast by hand.

Edit: Or if you're on windows, whatever removes the `target` directory in `src-tauri`

**Comment by FabianLars** [comment]
shameless plug for the built-in `cargo clean` command, which does exactly the same (although you can optionally specify profile & target)
