### ISSUE TITLE
[bug] Spawning an app via sidecar when using angular causes many multiple web windows and app instances to launch

### ISSUE THREAD

**Issue by heniu75** [tauri-apps/tauri#3663]
### Describe the bug

Setup a project to target angular using the tauri cli. Then use the Tauri sidecar example to spawn an app in main.rs. When running 'npm run tauri dev' numerous web windows are launched and it also looks like numerous app instances are launched. The behaviour seems very similar on Mac-OS. The release build on both platforms seem unaffected by this issue. 
I've create a repo to reproduce here - https://github.com/heniu75/tauri-issues/tree/main/ng-multiple-windows-issue

### Reproduction

1. Create a new Tauri cli app and choose angular
2. Migrate side-car app example main.rs to main.rs
3. Run 'npm run tauri dev'

### Expected behavior

A single web window and side car app instance should be launched, as per the release build

### Platform and versions

```shell
npm run tauri info:


> example-app@0.0.0 tauri C:\code\gh\tauri-issues\ng-multiple-windows-issue
> tauri "info"


Operating System - Windows, version 10.0.19044 X64
Webview2 - 99.0.1150.36
Visual Studio Build Tools:
   - Visual Studio Professional 2019
   - Visual Studio Professional 2022

Node.js environment
  Node.js - 14.18.3
  @tauri-apps/cli - 1.0.0-rc.6 (outdated, latest: 1.0.0-rc.7)
  @tauri-apps/api - 1.0.0-rc.2

Global packages
  npm - 6.14.15
  pnpm - Not installed
  yarn - Not installed

Rust environment
  rustup - 1.24.3
  rustc - 1.59.0
  cargo - 1.59.0
  toolchain - stable-x86_64-pc-windows-msvc 

App directory structure
/.angular
/.idea
/.vscode
/dist
/node_modules
/scripts
/src
/src-node
/src-tauri

App
  tauri - 1.0.0-rc.4
  tauri-build - 1.0.0-rc.4
  tao - 0.6.4
  wry - 0.13.3
  build-type - bundle
  CSP - unset
  distDir - ../dist/example-app
  devPath - http://localhost:4200/
  framework - Angular
  bundler - Webpack
```

### Additional context

The behaviour of the stock standard side-car example on my windows and Mac-os devices are fine - i.e. only a single web and app instance are launched.
I narrowed the code down to where my main fn is effectively:

fn main() {
  tauri::Builder::default()
    .setup(|app| {
      tauri::async_runtime::spawn(async move {
        let (receiver, child) = Command::new_sidecar("app")
          .expect("failed to setup `app` sidecar")
          .spawn()
          .expect("Failed to spawn packaged node app");
      });
      Ok(())
    })
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}

**Comment by heniu75** [comment]
I think I may have found a way to resolve this by renaming the node app named 'app' to something other than 'app' as this seems to have a clash with the tauri default app name ('app'). Solution -

1.  Change main.rs to reference node-app i.e. `Command::new_sidecar("node-app")`
2. Change tauri.conf.json i.e. `externalBin": ["binaries/node-app"]`
3. Change scripts/move-binary.js line 22 i.e. `src-tauri/binaries/node-app${extension}` and 23  `src-tauri/binaries/node-app-${targetTriple}${extension}`
4. Change package.json line 12 - i.e. `"package": "pkg src-node/index.js --output src-tauri/binaries/node-app && node scripts/move-binary.js"`

**Comment by amrbashir** [comment]
Yeah, don't use 'app' as that what tauri cli uses to trigger hot reload when rust code changes.
