### ISSUE TITLE
[bug] Shortcuts don't play well with HMR

### ISSUE THREAD

**Issue by ndarilek** [tauri-apps/tauri#3665]
### Describe the bug

Shortcuts don't seem to update on hot module reloading, and I'm not sure if there's some recommended pattern that I'm missing. Maybe I'm supposed to manually unregister them when components recreate, but that doesn't make a lot of sense given that other state is refreshed just fine.

### Reproduction

1. Create a Svelte app (or maybe any template works but I went with Svelte) with the following somewhere:
```
  shortcut.register("CmdOrControl+T", () => {
    console.log("Triggered");
  });
```
2. Launch the app, and run the shortcut to see the log message.
3. Change the console message (I.e. `console.log("Triggered again")`).
4. Save.
5. Note that Ctrl+T still prints the initial message.

### Expected behavior

Ideally Tauri would just reregister the binding here, but maybe there's something I'm missing.

### Platform and versions

```shell
yarn run v1.22.15
$ tauri info

Operating System - Windows, version 10.0.19044 X64
Webview2 - 99.0.1150.36
Visual Studio Build Tools:
   - Visual Studio Community 2019

Node.js environment
  Node.js - 17.1.0
  @tauri-apps/cli - 1.0.0-rc.6
  @tauri-apps/api - 1.0.0-rc.2

Global packages
  npm - 8.1.2
  pnpm - Not installed
  yarn - 1.22.15

Rust environment
  rustup - 1.24.3
  rustc - 1.59.0
  cargo - 1.59.0
  toolchain - stable-x86_64-pc-windows-msvc 

App directory structure
/.git
/.vscode
/dist
/node_modules
/public
/src
/src-tauri

App
  tauri - 1.0.0-rc.4
  tauri-build - 1.0.0-rc.4
  tao - 0.6.4
  wry - 0.13.3
  build-type - bundle
  CSP - unset
  distDir - ../dist
  devPath - http://localhost:3000/
  framework - Svelte
Done in 8.53s.
```

### Stack trace

```shell
Not a stacktrace exactly, but here's what I get in the console on HMR:

hotkey already registered: Accelerator { id: Some(AcceleratorId(34063)), mods: CONTROL, key: KeyT }
```

### Additional context

Ideally Tauri would just reregister the binding here, but maybe there's something I'm missing.

Is there a temporary workaround? I'm working on a hotkey-heavy app, so it wouldn't be much trouble for me to just put everything in a keymap store and unregister/reregister everything on HMR. It'd still be nice if the handler just reregistered last-one-wins, though.

Thanks!

**Comment by amrbashir** [comment]
> It'd still be nice if the handler just reregistered last-one-wins, though.

That's not a good idea and since we can't detect HMR on the cli, I don't think we should put any efforts into this.

You should deal with this on your end. Maybe hook into your build tool HMR cycle and call unregister.

**Comment by ndarilek** [comment]
> You should deal with this on your end. Maybe hook into your build tool HMR cycle and call unregister.

I'd appreciate an example of how to do this. I'm using the default 
vite-svelte template, so presumably it's something Tauri ships.

Thanks.

**Comment by amrbashir** [comment]
```js
if (import.meta.hot) {
  import.meta.on("vite:beforeUpdate", (e) => {
    // call unregister here
  }
}
```

See https://vitejs.dev/guide/api-hmr.html#hot-on-event-cb for more info.

**Comment by ndarilek** [comment]
Awesome, looks easy enough. Thanks!

**Comment by amrbashir** [comment]
```js
if (import.meta.hot) {
  import.meta.on("vite:beforeUpdate",  (e) => {
  // call unregister here
  }
}
```

See https://vitejs.dev/guide/api-hmr.html#hot-on-event-cb for more info.
Also above snippet should be automatically tree-shaked and removed in production build.

**Comment by amrbashir** [comment]
Note that vite will automatically tree-shake and remove this code in production builds.

**Comment by kareemmahlees** [comment]
>   import.meta.on("vite:beforeUpdate", (e) => {
>     // call unregister here
>   }

This should be:
```js
import.meta.hot.on("vite:beforeUpdate", (e) => {
// call unregister here
}
```
