### ISSUE TITLE
[bug] ClipboardManager goes out of sync in some situations

### ISSUE THREAD

**Issue by rscarson** [tauri-apps/tauri#3666]
### Describe the bug

When attempting the following workflow:
1- read the contents of the clipboard
2- send the key combination CTRL-C
3- read the contents of the clipboard

For all windows, the 2nd read contains the new text - UNLESS the current window belongs to the running tauri app. In that case, the clipboard contents get updated, but further clipboard reads still contain the same text as the first read.

Waiting several seconds, reading in a separate thread, or using emitting and responding to an event do not change the result.

When the active window belongs to tauri - the clipboard manager never updates with the new text

For context, I am doing all of this in a callback through the global_shortcut_manager

### Reproduction

let s1 = app_handle.clipboard_manager().read_text().ok()?;

// Send copy
KeybdKey::LControlKey.press(); KeybdKey::CKey.press();
sleep(Duration::from_millis(100));
KeybdKey::LControlKey.release(); KeybdKey::CKey.release();

let s2 = app_handle.clipboard_manager().read_text().ok()?;

### Expected behavior

s2 should contain the highlighted text in the active window

### Platform and versions

```shell
Operating System - Windows, version 10.0.19042 X64
Webview2 - 99.0.1150.30
Visual Studio Build Tools:
   - Visual Studio Community 2022
   - Visual Studio Enterprise 2019

Node.js environment
  Node.js - 16.13.0
  @tauri-apps/cli - 1.0.0-rc.5 (outdated, latest: 1.0.0-rc.7)
  @tauri-apps/api - 1.0.0-rc.1 (outdated, latest: 1.0.0-rc.2)

Global packages
  npm - 8.1.0
  pnpm - Not installed
  yarn - Not installed

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-pc-windows-msvc

App directory structure
/.git
/.vscode
/build
/node_modules
/public
/src
/src-tauri

App
  tauri - 1.0.0-rc.3
  tauri-build - 1.0.0-rc.3
  tao - 0.6.3
  wry - 0.13.3
  build-type - bundle
  CSP - unset
  distDir - ../build
  devPath - http://localhost:3000/
  framework - React
```

**Comment by nothingismagick** [comment]
That's juicy

**Comment by rscarson** [comment]
@nothingismagick maybe a little overly specific

If I run it more than once, the clipboard manager always contains the intended result from last time
The clipboard actually does update, I did confirm that - but clipboard reads always give answer over and over again

**Comment by nothingismagick** [comment]
It reminds me of a discussion I had with @rootmos about clipboard encryption. We would probably have to deal with it on the tao layer though...

**Comment by rscarson** [comment]
It seems to come down to the clipboard manager not detecting changes to the clipboard that occur within the lifetime of a global shortcut handler.

It updates fine between shortcut events

This only occurs while tauri is the active window

**Comment by rscarson** [comment]
I won't pretend I understand why this worked but
Wrapping the whole handler in a thread works:
``` rust
gsm.register(shortcut, move || {
        let app_handle = _app_handle.clone();
        thread::spawn(move || {
            handler(app_handle);
        });
});
```

Wrapping the actual reads inside the handler in threads does not help - but this way seems to work fine!
