### ISSUE TITLE
[bug] shell.Command: in JS it's "bin/sidecar" and in rust "sidecar"

### ISSUE THREAD

**Issue by benrogmans** [tauri-apps/tauri#3668]
### Describe the bug

When using a sidecar in JS, you have to prefix the binary path with the directory:
```
const command = new Command('bin/sidecar');
```

While in Rust:
```
let command = Command::new_sidecar("sidecar").expect("failed to setup sidecar");
```

The expectation is that referring to sidecar binaries is be consistent. Created for @lucasfernog and @FabianLars.

### Platform and versions

```shell
$ npm run tauri info

> my-app@0.0.0 tauri
> tauri "info"

Operating System - Pop!_OS, version 21.10 X64

Node.js environment
  Node.js - 17.4.0
  @tauri-apps/cli - 1.0.0-rc.6 (outdated, latest: 1.0.0-rc.7)
  @tauri-apps/api - 1.0.0-rc.2

Global packages
  npm - 8.3.1
  pnpm - Not installed
  yarn - 1.22.17

Rust environment
  rustup - 1.24.3
  rustc - 1.59.0
  cargo - 1.59.0
  toolchain - stable-x86_64-unknown-linux-gnu 

App
  tauri - 1.0.0-rc.4
  tauri-build - 1.0.0-rc.4
  tao - 0.6.4
  wry - 0.13.3
  build-type - bundle
  CSP - unset
  distDir - ../dist
  devPath - http://localhost:3000/
  framework - Svelte
```

### Additional context

Discovery and context can be read on Discord chat:
https://discord.com/channels/616186924390023171/731495028677148753/951567792958750774

**Comment by lucasfernog** [comment]
After checking the codebase, I don't think we have a fix for this right now. We can't validate the configured sidecars on `tauri::api::process::Command::new_sidecar`, and changing how the JS API validates it really makes the configuration weaker.
