### ISSUE TITLE
Failing to build Mac universal

### ISSUE THREAD

**Issue by albingroen** [tauri-apps/tauri#3669]
### Describe the bug

When I try to build a Tauri app for Mac OS Universal, I get a bunch of Rust errors in these shapes.

<img width="1493" alt="image" src="https://user-images.githubusercontent.com/19674362/157754079-0bfb3b7c-2940-4654-b23d-e8cfcbc43c34.png">

### Reproduction

```
tauri build --target universal-apple-darwin
```

### Expected behavior

The command will produce a successful build.

### Platform and versions

```shell
> coiner@0.0.1 tauri
> tauri "info"


Operating System - Mac OS, version 12.0.1 X64

Node.js environment
  Node.js - 16.14.0
  @tauri-apps/cli - 1.0.0-rc.5 (outdated, latest: 1.0.0-rc.7)
  @tauri-apps/api - 1.0.0-rc.1 (outdated, latest: 1.0.0-rc.2)

Global packages
  npm - 8.3.1
  pnpm - 6.27.0
  yarn - Not installed

Rust environment
  rustup - 1.24.3
  rustc - 1.59.0
  cargo - 1.59.0
  toolchain - stable-aarch64-apple-darwin 

App directory structure
/dist
/node_modules
/src-tauri
/.git
/src

App
  tauri - 1.0.0-rc.3
  tauri-build - 1.0.0-rc.3
  tao - 0.6.3
  wry - 0.13.3
  build-type - bundle
  CSP - unset
  distDir - ../dist
  devPath - http://localhost:3000/
```

**Comment by barrenechea** [comment]
Try updating the tauri dependencies? I see a mismatch on a few, and they usually should be "all in-sync".

On your package.json, you could bump those:
```
  @tauri-apps/cli - 1.0.0-rc.5 (outdated, latest: 1.0.0-rc.7)
  @tauri-apps/api - 1.0.0-rc.1 (outdated, latest: 1.0.0-rc.2)
```

And on your cargo.toml, you could bump both  `tauri-build` and `tauri` from `1.0.0-rc.3` to `1.0.0-rc.4`

Give those changes a try (make sure to install the new dependencies) and retry!

**Comment by lucasfernog** [comment]
Wow seems like your rust is completely messed up, if nothing works you could `rustup self uninstall` and reinstall it again.

**Comment by albingroen** [comment]
@SebastianBar @lucasfernog I've now tried both your suggestions, but to no success. I get the same errors. After updating the dependencies do I have to run a specific command for installing the Rust ones. I ran npm install to install the new js deps.

**Comment by albingroen** [comment]
But also, even though I updated the cli dep, it still says it's outdated?
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/19674362/157767207-51df1f2d-dae5-4a0e-bddf-52d5debdaf54.png">

**Comment by lucasfernog** [comment]
I think the problem here is trying to cross compile a M1 build on Intel mac. Might need a change on our script.

**Comment by albingroen** [comment]
> I think the problem here is trying to cross compile a M1 build on Intel mac. Might need a change on our script.

I'm on a M1 Mac though..?

**Comment by lucasfernog** [comment]
Ahh I was confused by the OS line. Did you run `rustup target add x86_64-apple-darwin`?

**Comment by albingroen** [comment]
> Ahh I was confused by the OS line. Did you run `rustup target add x86_64-apple-darwin`?

Oh okay, no I haven't run that?

**Comment by ttfkam** [comment]
I'm on a Macbook Pro (M1 Max) and am seeing the same thing. I've got `^1.0.0-rc.7` for `@tauri-apps/cli` in `package.json` but it won't update past `-rc.6`. I've tried deleting the `package-lock.json` file and `node_modules` (at the same time) and re-running `npm install` but it keeps coming back as `-rc.6`. I don't have anything tauri-related installed globally except for `create-tauri-app`.

**Comment by ttfkam** [comment]
Never mind. I see this message in the npm install logs.
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @tauri-apps/cli-darwin-arm64@1.0.0-rc.7 (node_modules/@tauri-apps/cli-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @tauri-apps/cli-darwin-arm64@1.0.0-rc.7: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @tauri-apps/cli-linux-arm-gnueabihf@1.0.0-rc.7 (node_modules/@tauri-apps/cli-linux-arm-gnueabihf):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @tauri-apps/cli-linux-arm-gnueabihf@1.0.0-rc.7: wanted {"os":"linux","arch":"arm"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @tauri-apps/cli-linux-arm64-gnu@1.0.0-rc.7 (node_modules/@tauri-apps/cli-linux-arm64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @tauri-apps/cli-linux-arm64-gnu@1.0.0-rc.7: wanted {"os":"linux","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @tauri-apps/cli-linux-arm64-musl@1.0.0-rc.7 (node_modules/@tauri-apps/cli-linux-arm64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @tauri-apps/cli-linux-arm64-musl@1.0.0-rc.7: wanted {"os":"linux","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @tauri-apps/cli-linux-x64-musl@1.0.0-rc.7 (node_modules/@tauri-apps/cli-linux-x64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @tauri-apps/cli-linux-x64-musl@1.0.0-rc.7: wanted {"os":"linux","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @tauri-apps/cli-linux-x64-gnu@1.0.0-rc.7 (node_modules/@tauri-apps/cli-linux-x64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @tauri-apps/cli-linux-x64-gnu@1.0.0-rc.7: wanted {"os":"linux","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @tauri-apps/cli-win32-x64-msvc@1.0.0-rc.7 (node_modules/@tauri-apps/cli-win32-x64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @tauri-apps/cli-win32-x64-msvc@1.0.0-rc.7: wanted {"os":"win32","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @tauri-apps/cli-win32-ia32-msvc@1.0.0-rc.7 (node_modules/@tauri-apps/cli-win32-ia32-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @tauri-apps/cli-win32-ia32-msvc@1.0.0-rc.7: wanted {"os":"win32","arch":"ia32"} (current: {"os":"darwin","arch":"x64"})
```

**Comment by lucasfernog** [comment]
Weird that you're running on M1 Max but yhe NPM logs show this: `(current: {"os":"darwin","arch":"x64"})` @ttfkam 

@albingroen Does the build work if you run `rustup target add x86_64-apple-darwin`?

**Comment by lucasfernog** [comment]
Can you guys share the output of `rustup target list`?

**Comment by ttfkam** [comment]
Thanks for pointing that out. Running the following fixed the architecture issue.
```sh
arch -arm64 zsh
```
Still can't build the universal binary though. Same error as before.
```
% npm run tauri build --target universal-apple-darwin

> po-app@1.0.0 tauri
> tauri "build" "universal-apple-darwin"

[tauri:build] Running `npm run build`

> po-app@1.0.0 build
> rollup -c


src/main.ts → public/build/bundle.js...
(!) Plugin typescript: @rollup/plugin-typescript: Typescript 'sourceMap' compiler option must be set to generate source maps.
created public/build/bundle.js in 779ms
error: Found argument 'universal-apple-darwin' which wasn't expected, or isn't valid in this context

USAGE:
    cargo build --features <FEATURES>...

For more information try --help
Error running CLI: failed to build app: Result of `cargo build` operation was unsuccessful: exit status: 1
```
> Can you guys share the output of `rustup target list`?

**aarch64-apple-darwin (installed)**
aarch64-apple-ios
aarch64-apple-ios-sim
aarch64-fuchsia
aarch64-linux-android
aarch64-pc-windows-msvc
aarch64-unknown-linux-gnu
aarch64-unknown-linux-musl
aarch64-unknown-none
aarch64-unknown-none-softfloat
arm-linux-androideabi
arm-unknown-linux-gnueabi
arm-unknown-linux-gnueabihf
arm-unknown-linux-musleabi
arm-unknown-linux-musleabihf
armebv7r-none-eabi
armebv7r-none-eabihf
armv5te-unknown-linux-gnueabi
armv5te-unknown-linux-musleabi
armv7-linux-androideabi
armv7-unknown-linux-gnueabi
armv7-unknown-linux-gnueabihf
armv7-unknown-linux-musleabi
armv7-unknown-linux-musleabihf
armv7a-none-eabi
armv7r-none-eabi
armv7r-none-eabihf
asmjs-unknown-emscripten
i586-pc-windows-msvc
i586-unknown-linux-gnu
i586-unknown-linux-musl
i686-linux-android
i686-pc-windows-gnu
i686-pc-windows-msvc
i686-unknown-freebsd
i686-unknown-linux-gnu
i686-unknown-linux-musl
mips-unknown-linux-gnu
mips-unknown-linux-musl
mips64-unknown-linux-gnuabi64
mips64-unknown-linux-muslabi64
mips64el-unknown-linux-gnuabi64
mips64el-unknown-linux-muslabi64
mipsel-unknown-linux-gnu
mipsel-unknown-linux-musl
nvptx64-nvidia-cuda
powerpc-unknown-linux-gnu
powerpc64-unknown-linux-gnu
powerpc64le-unknown-linux-gnu
riscv32i-unknown-none-elf
riscv32imac-unknown-none-elf
riscv32imc-unknown-none-elf
riscv64gc-unknown-linux-gnu
riscv64gc-unknown-none-elf
riscv64imac-unknown-none-elf
s390x-unknown-linux-gnu
sparc64-unknown-linux-gnu
sparcv9-sun-solaris
thumbv6m-none-eabi
thumbv7em-none-eabi
thumbv7em-none-eabihf
thumbv7m-none-eabi
thumbv7neon-linux-androideabi
thumbv7neon-unknown-linux-gnueabihf
thumbv8m.base-none-eabi
thumbv8m.main-none-eabi
thumbv8m.main-none-eabihf
wasm32-unknown-emscripten
wasm32-unknown-unknown
wasm32-wasi
**x86_64-apple-darwin (installed)**
x86_64-apple-ios
x86_64-fortanix-unknown-sgx
x86_64-fuchsia
x86_64-linux-android
x86_64-pc-solaris
x86_64-pc-windows-gnu
x86_64-pc-windows-msvc
x86_64-sun-solaris
x86_64-unknown-freebsd
x86_64-unknown-illumos
x86_64-unknown-linux-gnu
x86_64-unknown-linux-gnux32
x86_64-unknown-linux-musl
x86_64-unknown-netbsd
x86_64-unknown-redox

**Comment by lucasfernog** [comment]
@ttfkam can you share the output of `tauri info`? Seems like the version you're running does not support the universal-apple-darwin virtual target.

**Comment by ttfkam** [comment]
I take it back. Looks like it's still stuck on `rc6`. package.json and package-lock.json both have `rc7` listed. 🤷 
```
% npm run tauri info 

> po-app@1.0.0 tauri
> tauri "info"


Operating System - Mac OS, version 12.2.1 X64

Node.js environment
  Node.js - 16.14.2
  @tauri-apps/cli - 1.0.0-rc.6 (outdated, latest: 1.0.0-rc.7)
  @tauri-apps/api - 1.0.0-rc.2

Global packages
  npm - 8.5.0
  pnpm - 6.32.3
  yarn - Not installed

Rust environment
  rustup - 1.24.3
  rustc - 1.59.0
  cargo - 1.59.0
  toolchain - stable-aarch64-apple-darwin 

App directory structure
/node_modules
/public
/src-tauri
/.vscode
/src

App
  tauri - 1.0.0-rc.4
  tauri-build - 1.0.0-rc.4
  tao - 0.6.4
  wry - 0.13.3
  build-type - bundle
  CSP - unset
  distDir - ../public
  devPath - http://localhost:8080/
  framework - Svelte
  bundler - Rollup
```

**Comment by lucasfernog** [comment]
Does it update to rc.8? @ttfkam

**Comment by ttfkam** [comment]
I updated package.json to have -rc.8 for cli and -rc.3 for api. Output is definitely more colorful, but cli only updated to -rc.7? (I tried deleting node_modules and package-lock.json. Same result with npm install.) The notice about api being outdated on the latest version is puzzling to say the least.
```
> po-app@1.0.0 tauri
> tauri "info"


Environment
  › OS: Mac OS 12.2.1 X64
  › Node.js: 16.14.2
  › npm: 8.5.0
  › pnpm: 6.32.3
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.59.0
  › cargo: 1.59.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.7(outdated, latest: 1.0.0-rc.8)
  › @tauri-apps/api [NPM]: 1.0.0-rc.3(outdated, latest: 1.0.0-rc.3)
  › tauri [RUST]: 1.0.0-rc.4,
  › tauri-build [RUST]: 1.0.0-rc.4,
  › tao [RUST]: 0.6.4,
  › wry [RUST]: 0.13.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../public
  › devPath: http://localhost:8080/
  › framework: Svelte
  › bundler: Rollup

App directory structure
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .vscode
  └─ src
```
The relevant parts of package.json are unremarkable.
```json
  "devDependencies": {
    "@rollup/plugin-commonjs": "^17.0.0",
    "@rollup/plugin-node-resolve": "^11.0.0",
    "@rollup/plugin-typescript": "^8.0.0",
    "@tauri-apps/cli": "^1.0.0-rc.8",
    "@tsconfig/svelte": "^2.0.0",
    "rollup": "^2.3.4",
    "rollup-plugin-css-only": "^3.1.0",
    "rollup-plugin-livereload": "^2.0.0",
    "rollup-plugin-svelte": "^7.0.0",
    "rollup-plugin-terser": "^7.0.0",
    "svelte": "^3.0.0",
    "svelte-check": "^2.0.0",
    "svelte-preprocess": "^4.0.0",
    "tslib": "^2.0.0",
    "typescript": "^4.0.0"
  },
  "dependencies": {
    "@tauri-apps/api": "^1.0.0-rc.3",
    "sirv-cli": "^2.0.0"
  }
```

**Comment by lucasfernog** [comment]
Ahh I just found the issue of the info command showing rc.7 instead of rc.8, will push a fix.

Can you share the full error message when building the universal target?

**Comment by ttfkam** [comment]
No change. Same error as before.

https://github.com/tauri-apps/tauri/issues/3669#issuecomment-1080096363

**Comment by FabianLars** [comment]
@ttfkam to tell npm to correctly forward arguments to the tauri cli you need to prepend an extra `--` like so: `npm run tauri build -- --target universal-apple-darwin`

**Comment by ttfkam** [comment]
Yep @FabianLars, that almost fixed the build issue. Thank you. FYI: someone might want to update the command I basically copy-pasted from the Tauri docs. I think my CLI goof may be a common mistake worth documenting proactively.
https://tauri.studio/docs/distribution/macos#binary-targets

**Comment by ttfkam** [comment]
tauri info results are unchanged from before
```
% npm run tauri build -- --target universal-apple-darwin

> po-app@1.0.0 tauri
> tauri "build" "--target" "universal-apple-darwin"

[tauri:build] Running `npm run build`

> po-app@1.0.0 build
> rollup -c


src/main.ts → public/build/bundle.js...
(!) Plugin typescript: @rollup/plugin-typescript: Typescript 'sourceMap' compiler option must be set to generate source maps.
created public/build/bundle.js in 805ms
   Compiling cfg-if v1.0.0
   Compiling lazy_static v1.4.0
   
   ...trimmed for clarity in a GitHub issue comment...
   
   Compiling attohttpc v0.18.0
   Compiling futures v0.3.21
   Compiling json-patch v0.2.6
   Compiling potable v0.1.0 (/Users/mileselam/dev/test/tauri-ui/tauri-app/src-tauri)
error: failed to run custom build command for `potable v0.1.0 (/Users/mileselam/dev/test/tauri-ui/tauri-app/src-tauri)`

Caused by:
  process didn't exit successfully: `/Users/mileselam/dev/test/tauri-ui/tauri-app/src-tauri/target/release/build/potable-a546a4d5edc1a508/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=tauri.conf.json

  --- stderr
  thread 'main' panicked at 'error found during tauri-build: unknown field `allowDowngrades`, expected one of `digestAlgorithm`, `certificateThumbprint`, `timestampUrl`, `tsp`, `webviewFixedRuntimePath`, `wix` at line 1 column 1009', /Users/mileselam/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-build-1.0.0-rc.4/src/lib.rs:146:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
Error running CLI: failed to build aarch64-apple-darwin binary: Result of `cargo build` operation was unsuccessful: exit status: 101
```

**Comment by FabianLars** [comment]
Try upgrading tauri-build (in Cargo.toml) to `1.0.0-rc.5`
Edit: tauri may need to be updated to `1.0.0-rc.6`, otherwise there might be version mismatches. But either way tauri-build needs to be updated to work with the latest cli versions.
Edit2: If you can't upgrade tauri because of the breaking changes yet, you can try to carefully downgrade the cli version again in the meantime.

**Comment by ttfkam** [comment]
Success! Updating to `-rc.5` was the last missing piece. Universal binary built and running now. Thank you. 👍

**Comment by ttfkam** [comment]
`-rc.6` appears to work as well. 👍

**Comment by FabianLars** [comment]
Nice!

With that resolved i'm gonna close this issue since the OP doesn't respond and it looked like an issue with the missing target (feel free to comment here again and we will re-open it)

**Comment by JSoon** [comment]
> I think the problem here is trying to cross compile a M1 build on Intel mac. Might need a change on our script.

Does this mean that I can not compile A [Universal macOS Binary](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary) on the Intel-based computer? If it does, could you please add a note on the docs maybe?

@lucasfernog

**Comment by lucasfernog** [comment]
We did see some issues but nothing conclusive yet, we need to investigate it further.
