### ISSUE TITLE
[feat] Is it possible to implement something like System.Clipboard.SetDataObject in windows' c# api?

### ISSUE THREAD

**Issue by cangSDARM** [tauri-apps/tauri#3671]
### Describe the problem

https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.clipboard.setdataobject?view=windowsdesktop-6.0

This api allow u to clears the Clipboard and then places nonpersistent data on it.

### Describe the solution you'd like

`app_handle.clipboard_manager().replace_clipboard_contents()` or some else

**Comment by amrbashir** [comment]
AFAIK This is not possible because `SetDataObject` is a .Net API, and we are only using win32.

Just curios What is exactly is your use-case.
