### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by albingroen** [tauri-apps/tauri#3678]
### Describe the bug

I'm trying to set up the updater to work correctly. I've gotten to the point where I get this popup once there is a new update available. But clicking the blue button doesn't actually do anything after that.

<img width="393" alt="image" src="https://user-images.githubusercontent.com/19674362/157826970-413ae53e-4392-4aa8-ae32-d989254667a6.png">

Is there any way I can debug this?

My updater config looks like this:

```
    "updater": {
      "active": true,
      "endpoints": [
        "https://api.getcoiner.app/api/{{target}}/{{current_version}}"
      ],
      "dialog": true,
      "pubkey": "dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IEYzRkYxNDBGMDhFQzJEQTgKUldTb0xld0lEeFQvOCsvVDlsSkxONG9Mc1N6YS90cGlLMGdRbVF1K3NzTTYrQ3Z6ZjRMdTVoNVIK"
    },

```

### Expected behavior

I expect the new version to be downloaded and installed, and for the app to restart.

### Platform and versions

```shell
> coiner@0.0.2 tauri
> tauri "info"


Operating System - Mac OS, version 12.0.1 X64

Node.js environment
  Node.js - 16.14.0
  @tauri-apps/cli - 1.0.0-rc.5 (outdated, latest: 1.0.0-rc.7)
  @tauri-apps/api - 1.0.0-rc.1 (outdated, latest: 1.0.0-rc.2)

Global packages
  npm - 8.3.1
  pnpm - 6.27.0
  yarn - Not installed

Rust environment
  rustup - 1.24.3
  rustc - 1.59.0
  cargo - 1.59.0
  toolchain - stable-aarch64-apple-darwin 

App directory structure
/dist
/node_modules
/src-tauri
/.git
/src

App
  tauri - 1.0.0-rc.3
  tauri-build - 1.0.0-rc.3
  tao - 0.6.3
  wry - 0.13.3
  build-type - bundle
  CSP - unset
  distDir - ../dist
  devPath - http://localhost:3000/
```

**Comment by lucasfernog** [comment]
I'll test using your updater server if it's still running :)

**Comment by lucasfernog** [comment]
It's returning a `MissingUpdaterSignature` error. When you bundle your application, a `Coiner.app.tar.gz.sig` file is saved next to the `Coiner.app.tar.gz`, containing the signature of that file. You need to return that on the `https://api.getcoiner.app/api/darwin/0.0.1` response JSON on the `signature` field.

You can check updater errors by listening to the `tauri://update-status` event on the frontend.

Note that on the next release we'll introduce a breaking change on the updater, the `{{target}}` will no longer be `darwin`, but `darwin-x86_64` or `darwin-aarch64` by default, so you can check if the update is for Apple Silicon or Intel.

**Comment by yonathan06** [comment]
@lucasfernog should the `signature` field contain the URL to the `.sig` file, or the content of the `.sig` file (the signature it self)?

**Comment by FabianLars** [comment]
@yonathan06 The content

**Comment by HoaX7** [comment]
Im having the same issue and im passing the correct contents as the json specific on the docs

**Comment by HoaX7** [comment]
Its like stuck in a loop, I have the auto updater on and it keeps asking if i want to download and install the update and then when i click yes it relaunches and does the same thing again

**Comment by FabianLars** [comment]
@HoaX7 Did you perhaps install the initial app via the nsis setup.exe and use the .msi for the updater artifact? Or maybe not have it installed at all?

For the updater the app has to be installed and the package formats must match.
