### ISSUE TITLE
[bug] Can't build project

### ISSUE THREAD

**Issue by Septias** [tauri-apps/tauri#3690]
### Describe the bug

I can't build my tauri project.
I used the tauri-vite template, but switched the vue-project with `vitesse` template from antfu.

### Reproduction
`git clone https://github.com/Septias/reddit_wallpapers.git`
`pnpm i`
`cargo tauri build`

### Expected behavior
It should build without errors 

### Platform and versions
```shell
Manjaro Linux
Tauri cli: ^1.0.0-rc.7 
Tauri: "1.0.0-rc.4"
Tauri-build: "1.0.0-rc.4"
```

### Stack trace

```shell
❯ cargo tauri build
[tauri:build] Running `pnpm build`

> @ build /home/septias/coding/reddit_wallpapers
> vite build

vite v2.8.6 building for production...
✓ 38 modules transformed.
dist/index.html                     0.48 KiB
dist/assets/index.b3558abe.js       3.55 KiB / gzip: 1.79 KiB
dist/assets/_...all_.d5595864.js    0.23 KiB / gzip: 0.19 KiB
dist/assets/_...all_.0e6ec599.css   0.00 KiB / gzip: 0.02 KiB
dist/assets/index.9b74596e.css      7.49 KiB / gzip: 2.58 KiB
dist/assets/vendor.29e77d0d.js      80.47 KiB / gzip: 31.93 KiB
   Compiling app v0.1.0 (/home/septias/coding/reddit_wallpapers/src-tauri)
    Finished release [optimized] target(s) in 13.67s
[tauri:build] Binary stripped, size reduced by 7.22 MB
Error: failed to build bundler settings

Caused by:
    invalid category
```

**Comment by FabianLars** [comment]
You need to set `category` in tauri.conf,json to a _valid_ value or null ("App" is not a valid one). We used to list them in a tooltip and in the docs, but i guess they got lost in the audit pr file conflicts.

Here is what the tooltip showed before: <https://github.com/tauri-apps/tauri/commit/62182383de59a6ead275ba8e85f010b2a0704832>

I'll leave this issue open until we re-add that comment.

**Comment by Septias** [comment]
Ah nice, thank you :)
