### ISSUE TITLE
[bug] I Can't use my App vuejs in Windows 7

### ISSUE THREAD

**Issue by Ahm3dksa** [tauri-apps/tauri#3693]
### Describe the bug

![‏‏لقطة الشاشة (131)](https://user-images.githubusercontent.com/14205849/158083517-f34774ca-a584-417a-8e0a-73d01bb95187.png)

I Can't use my App vuejs in Windows 7 86x

### Platform and versions

```shell
C:\Users\Ahmed Magdy\ahmedelgamalfi\src-tauri>yarn run tauri info
yarn run v1.22.17
$ "C:\Users\Ahmed Magdy\ahmedelgamalfi\node_modules\.bin\tauri" info

Operating System - Windows, version 10.0.22000 X64
Webview2 - 99.0.1150.39
Visual Studio Build Tools:
   - Visual Studio Community 2022
   - Visual Studio Build Tools 2019

Node.js environment
  Node.js - 17.6.0
  @tauri-apps/cli - 1.0.0-rc.4 (outdated, latest: 1.0.0-rc.7)
  @tauri-apps/api - Not installed

Global packages
  npm - 8.1.1
  pnpm - Not installed
  yarn - 1.22.17

Rust environment
  rustup - 1.24.3
  rustc - 1.59.0
  cargo - 1.59.0
  toolchain - stable-x86_64-pc-windows-msvc

App directory structure
/.git
/cv
/dist
/node_modules
/public
/src
/src-tauri
/tao

App
  tauri - 1.0.0-rc.4
  tauri-build - 1.0.0-rc.4
  tao - 0.6.4
  wry - 0.13.3
  build-type - bundle
  CSP - unset
  distDir - ../dist
  devPath - http://localhost:8080/
  framework - Vue.js (Vue CLI)
  bundler - Webpack
Done in 27.92s.
```

**Comment by amrbashir** [comment]
Did you build the binary for x86? try 
```
rustup target add i686-pc-windows-msvc
tauri build --target i686-pc-windows-msvc
```

**Comment by Ahm3dksa** [comment]
> Did you build the binary for x86? try 
> ```
> rustup target add i686-pc-windows-msvc
> tauri build --target i686-pc-windows-msvc

 I do not know what the exact problem is, I installed the program but it does not open and the previous message appears
Is it because Windows?

**Comment by Ahm3dksa** [comment]
If you have a copy of an application that works in a new way on Windows 7, please upload it

**Comment by Ahm3dksa** [comment]
If you have a copy of an application that works in a new way on Windows 7, please upload it

**Comment by amrbashir** [comment]
This is a problem in your windows 7 installation. It is missing an update, this one specifically
https://support.microsoft.com/en-us/topic/update-for-customer-experience-and-diagnostic-telemetry-0b4f29c3-8361-b748-f862-7ecedbc57cbf. You may encounter other errors and missing system dlls afterwards, all of which are not related to Tauri but to Windows in general.
