### ISSUE TITLE
[bug] Slow &:active compared to browser

### ISSUE THREAD

**Issue by elibroftw** [tauri-apps/tauri#3694]
### Describe the bug

Tauri window lags when elements that have an `:hover:active` style,

### Reproduction

Even though I am using React, this is a major performance bug. I think you can reproduce the issue with plain html/css though.
Suppose an element has the following style.
```
.el:hover:active {
        transform: translateY(2px);
},
```
This means that when the users presses their mouse on the element, the element will go a bit down. When the user moves their mouse off, it'll still be pressed, but when released, it won't result in a click. 

Clicking different elements in Tauri, even without spamming, results in lag. When the styling is removed, Tauri behaves normally without lag.

This could be an underlying webview2 or wry problem. 

Rename the following to html to use for testing. Click the navigation elements to see what I am talking about.
[R2-T2 by LeNerva.txt](https://github.com/tauri-apps/tauri/files/8241746/R2-T2.by.LeNerva.txt)

### Expected behavior

I can spam elements without Tauri lagging. When I have the app open in Firefox, I can spam all I want, and there's absolutely no lag.

This issue is not present in Edge, so there is something really wrong going on!

### Platform and versions

```shell
Windows 10, tauri 1.0.0-rc.4
```

### Additional context

<details>
<summary markdown="span">Tauri Info</summary>

```

Operating System - Windows, version 10.0.19044 X64
Webview2 - 99.0.1150.39
Visual Studio Build Tools:
   - Visual Studio Community 2022

Node.js environment
  Node.js - 17.3.1
  @tauri-apps/cli - 1.0.0-rc.6
  @tauri-apps/api - 1.0.0-rc.2

Global packages
  npm - 8.3.0
  pnpm - Not installed
  yarn - 1.22.11

Rust environment
  rustup - 1.24.3
  rustc - 1.57.0
  cargo - 1.57.0
  toolchain - stable-x86_64-pc-windows-msvc 

App directory structure
/.git
/assets
/build
/dist
/node_modules
/public
/pyi-specs
/src
/src-tauri
/__pycache__

App
  tauri - 1.0.0-rc.4
  tauri-build - 1.0.0-rc.4
  tao - 0.6.4
  wry - 0.13.3
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://127.0.0.1:3000/
  framework - React
Done in 7.74s.
```
</details>

**Comment by JonasKruckenberg** [comment]
Can you paste the full `tauri info` output?

**Comment by elibroftw** [comment]
<details>
<summary markdown="span">Tauri Info</summary>

```

Operating System - Windows, version 10.0.19044 X64
Webview2 - 99.0.1150.39
Visual Studio Build Tools:
   - Visual Studio Community 2022

Node.js environment
  Node.js - 17.3.1
  @tauri-apps/cli - 1.0.0-rc.6
  @tauri-apps/api - 1.0.0-rc.2

Global packages
  npm - 8.3.0
  pnpm - Not installed
  yarn - 1.22.11

Rust environment
  rustup - 1.24.3
  rustc - 1.57.0
  cargo - 1.57.0
  toolchain - stable-x86_64-pc-windows-msvc 

App directory structure
/.git
/assets
/build
/dist
/node_modules
/public
/pyi-specs
/src
/src-tauri
/__pycache__

App
  tauri - 1.0.0-rc.4
  tauri-build - 1.0.0-rc.4
  tao - 0.6.4
  wry - 0.13.3
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://127.0.0.1:3000/
  framework - React
Done in 7.74s.
```
</details>

**Comment by elibroftw** [comment]
This issue is not present when using pywebview which uses .NET's webview bindings.

**Comment by elibroftw** [comment]
Fortunately, this bug is barely noticeable in a release build.

**Comment by amrbashir** [comment]
I can't reproduce this in debug builds at all but since it is not noticeable for your in a release build I am not gonna consider this as a bug. Let me know if you encounter it in a release build and probably.

**Comment by elibroftw** [comment]
Is it noticeable to me in production builds since I'm looking for it. If you don't encounter the problem then that's good.

**Comment by amrbashir** [comment]
I think this is the same as #3691

**Comment by elibroftw** [comment]
Makes sense
