### ISSUE TITLE
[bug] Notification uses Windows Powershell 

### ISSUE THREAD

**Issue by elibroftw** [tauri-apps/tauri#3700]
### Describe the bug

![image](https://user-images.githubusercontent.com/21298211/158195927-143dfcaf-0545-4fff-9574-09f78a43a8f2.png)

### Reproduction

```js
new Notification('Title', {body: "This is the notification body"});
```

### Expected behavior

The app's icon and app's name instead of Windows Powershell. I shouldn't need to provide that myself.

### Platform and versions

```shell
PS C:\Users\maste\Documents\GitHub\r2-t2> yarn tauri info 
yarn run v1.22.11
$ C:\Users\maste\Documents\GitHub\r2-t2\node_modules\.bin\tauri info

Operating System - Windows, version 10.0.19044 X64
Webview2 - 99.0.1150.39
Visual Studio Build Tools:
   - Visual Studio Community 2022

Node.js environment
  Node.js - 17.3.1
  @tauri-apps/cli - 1.0.0-rc.6
  @tauri-apps/api - 1.0.0-rc.2

Global packages
  npm - 8.3.0
  pnpm - Not installed
  yarn - 1.22.11

Rust environment
  rustup - 1.24.3
  rustc - 1.57.0
  cargo - 1.57.0
  toolchain - stable-x86_64-pc-windows-msvc 

App directory structure
/.git
/assets
/build
/dist
/node_modules
/public
/pyi-specs
/src
/src-tauri
/__pycache__

App
  tauri - 1.0.0-rc.4
  tauri-build - 1.0.0-rc.4
  tao - 0.6.4
  wry - 0.13.3
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://127.0.0.1:3000/
  framework - React
Done in 7.98s.
PS C:\Users\maste\Documents\GitHub\r2-t2>
```

**Comment by lucasfernog** [comment]
It only uses Powershell on dev (Windows limitation, needs an actual installed bundle id to work). It will use your app name and icon on the built application.

**Comment by elibroftw** [comment]
No it doesn't.
![image](https://user-images.githubusercontent.com/21298211/158197873-2fb1dbe1-b1c5-4404-81b8-0d1bb0e24778.png)

**Comment by FabianLars** [comment]
You need to install it via the .msi so that it "installs" the bundle id

**Comment by danielbkang** [comment]
I installed it using both .msi and nsis, but it still did not work. Do I need to setup for certificateThumbprint as well? or is changing bundle identifier enough?

**Comment by danielbkang** [comment]
I used [winrt_notification](https://allenbenz.github.io/winrt-notification/0_5_0/winrt_notification/index.html) instead of [notify-rust](https://github.com/hoodie/notify-rust), and it worked.

Apparently, notify-rust is designed primarily for XDG, and there are many features in notify-rust that does not work in Windows or Mac.

If you are trying to show a notification on Windows and if you do not want to see Windows Powershell as a notification generator, 
(both dev and build)

1. Set proper name for tauri.bundle.identifier in tauri.conf.json. 
```
{
   "tauri": {
       "bundle": {
           "identifier": "com.condoso.my-projectname.whatever"
       }
   }
}
```
2. Instead of Toast::POWERSHELL_APP_ID, put the identifier on step 1. 

```
Toast::new("com.condoso.my-projectname.whatever")
        .title(title)
        .text1(body)
        .sound(Some(Sound::SMS))
        .duration(Duration::Long)
        .show()
        .expect("unable to toast");
```

Then Windows notification (toast) will know which program is a generator for the toast.

**Comment by ChaserZ98** [comment]
FYI: No need for other notification package. I can confirm installation solves this issue on win10.
![1725541723433](https://github.com/user-attachments/assets/643aa67f-21c7-40eb-a511-2bd983154ae5)
