### ISSUE TITLE
[bug] Rust package build failing when trying "tauri dev"

### ISSUE THREAD

**Issue by danimesq** [tauri-apps/tauri#3701]
### Describe the bug

Output:

```shell
  --- stderr
  Package javascriptcoregtk-4.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `javascriptcoregtk-4.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'javascriptcoregtk-4.0' found
  Package javascriptcoregtk-4.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `javascriptcoregtk-4.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'javascriptcoregtk-4.0' found
```

Even more details:

```shell
   Compiling zvariant v3.1.2
The following warnings were emitted during compilation:

warning: `"pkg-config" "--libs" "--cflags" "javascriptcoregtk-4.0" "javascriptcoregtk-4.0 >= 2.24"` did not exit successfully: exit status: 1

error: failed to run custom build command for `javascriptcore-rs-sys v0.4.0`

Caused by:
  process didn't exit successfully: `/home/daniell/Desktop/test/frameworkjs/src-tauri/target/debug/build/javascriptcore-rs-sys-e4d503634ed33e5f/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=JAVASCRIPTCOREGTK_4.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:warning=`"pkg-config" "--libs" "--cflags" "javascriptcoregtk-4.0" "javascriptcoregtk-4.0 >= 2.24"` did not exit successfully: exit status: 1
  error: could not find system library 'javascriptcoregtk-4.0' required by the 'javascriptcore-rs-sys' crate

  --- stderr
  Package javascriptcoregtk-4.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `javascriptcoregtk-4.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'javascriptcoregtk-4.0' found
  Package javascriptcoregtk-4.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `javascriptcoregtk-4.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'javascriptcoregtk-4.0' found

warning: build failed, waiting for other jobs to finish...
error: build failed
    Blocking waiting for file lock on build directory
   Compiling zstd-safe v4.1.4+zstd.1.5.2
   Compiling javascriptcore-rs-sys v0.4.0
   Compiling gobject-sys v0.15.9
   Compiling cairo-sys-rs v0.15.1
   Compiling gio-sys v0.14.0
   Compiling gtk v0.15.4
   Compiling rfd v0.7.0
   Compiling gobject-sys v0.14.0
   Compiling zbus v2.1.1
The following warnings were emitted during compilation:

warning: `"pkg-config" "--libs" "--cflags" "javascriptcoregtk-4.0" "javascriptcoregtk-4.0 >= 2.24"` did not exit successfully: exit status: 1

error: failed to run custom build command for `javascriptcore-rs-sys v0.4.0`

Caused by:
  process didn't exit successfully: `/home/daniell/Desktop/test/frameworkjs/src-tauri/target/debug/build/javascriptcore-rs-sys-e4d503634ed33e5f/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=JAVASCRIPTCOREGTK_4.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:warning=`"pkg-config" "--libs" "--cflags" "javascriptcoregtk-4.0" "javascriptcoregtk-4.0 >= 2.24"` did not exit successfully: exit status: 1
  error: could not find system library 'javascriptcoregtk-4.0' required by the 'javascriptcore-rs-sys' crate
```

### Platform and versions

```shell
❯ cargo tauri info

Operating System - Ubuntu, version 20.04 X64

Node.js environment
  Node.js - 14.17.3
  @tauri-apps/cli - 1.0.0-rc.6
  @tauri-apps/api - 1.0.0-rc.2

Global packages
  npm - 7.19.1
  pnpm - Not installed
  yarn - 1.22.10

Rust environment
  rustup - 1.24.3
  rustc - 1.59.0
  cargo - 1.59.0
  toolchain - stable-x86_64-unknown-linux-gnu 

App directory structure
/node_modules
/dist
/src-tauri

App
  tauri - 1.0.0-rc.4
  tauri-build - 1.0.0-rc.4
  tao - 0.6.4
  wry - 0.13.3
  build-type - bundle
  CSP - unset
  distDir - ../dist
  devPath - ../dist
```

**Comment by lucasfernog** [comment]
You need to install the system dependencies listed [here](https://tauri.studio/docs/getting-started/setting-up-linux/#1-system-dependencies).

**Comment by danimesq** [comment]
> You need to install the system dependencies listed [here](https://tauri.studio/docs/getting-started/setting-up-linux/#1-system-dependencies).

Have installed `libwebkit2gtk-4.0-dev`, `build-essential`, `curl`, `wget`, `libssl-dev`, `libgtk-3-dev`, `libappindicator3-dev`, `librsvg2-dev`.
Have NOT installed `libappindicator` nor `librsvg` as they're marked as optional.

Already have NodeJS installed (although not sure if installed from official NodeJS or from nvm).

Have upgraded my old (but already installed) Rustc and Cargo.

`rustc --version` outputs `rustc 1.59.0 (9d1b2106e 2022-02-23)`.
`npm -v` outputs `7.19.1`.

And done.

I have all of the required system dependencies installed.

@lucasfernog, I suggested that instead of assuming I'm an newbie who don't read docs and haven't installed the dependencies then closing the issue - which is still valid - you could ask if I have installed the dependencies.

So its true: I have all of the required environment and I still believe its a bug (as happened before [here](https://github.com/wealdtech/ethereal/issues/37#issuecomment-1048114428)) that could be fixed so, please, could you re-open the issue?

**Comment by danimesq** [comment]
> You need to install the system dependencies listed [here](https://tauri.studio/docs/getting-started/setting-up-linux/#1-system-dependencies).

Have installed `libwebkit2gtk-4.0-dev`, `build-essential`, `curl`, `wget`, `libssl-dev`, `libgtk-3-dev`, `libappindicator3-dev`, `librsvg2-dev`.
Have NOT installed `libappindicator` nor `librsvg` as they're marked as optional.

Already have NodeJS installed (although not sure if installed from official NodeJS or from nvm).

Have upgraded my old (but already installed) Rustc and Cargo.

`rustc --version` outputs `rustc 1.59.0 (9d1b2106e 2022-02-23)`.
`npm -v` outputs `7.19.1`.

This isn't a issue in the repo, but in the docs; specifically [this part](https://tauri.studio/docs/getting-started/setting-up-linux/#1-system-dependencies):

> sudo apt update && sudo apt install libwebkit2gtk-4.0-dev \
>     build-essential \
>     curl \
>     wget \
>     libssl-dev \
>     libgtk-3-dev \
>     libappindicator3-dev \
>     librsvg2-dev

I copied it and pasted, but Bash have read only `sudo apt update` and the other lines were missed.

`libssl-dev` wasn't installed.
`libappindicator3-dev` wasn't installed. `librsvg2-dev` wasn't installed. (why optional packages were added in the required quote?)

When trying `sudo apt install libwebkit2gtk-4.0-dev`, got this output:

> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  libwebkit2gtk-4.0-dev : Depends: libsoup2.4-dev (>= 2.40) but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.

How to fix the `libsoup2.4-dev` issue?

**Comment by jaques-sam** [comment]
On debian11 the package `libappindicator3-dev` cannot be found any more.

**Comment by lucasfernog** [comment]
We're currently working to expose the Ayatana appindicator in tauri.

**Comment by lucasfernog** [comment]
@jaques-sam you can add Debian 10 to your source list, see #2647

**Comment by thy-jumrylsolivio** [comment]
to fix the libsoup2.4-dev issue try this " sudo apt install libsoup2.4-dev

**Comment by Type1J** [comment]
> You need to install the system dependencies listed [here](https://tauri.studio/docs/getting-started/setting-up-linux/#1-system-dependencies).

Did you mean https://tauri.app/v1/guides/getting-started/prerequisites ?

**Comment by FabianLars** [comment]
that's the new location of the docs Lucas linked back then, correct.

**Comment by Kennytian** [comment]
`sudo apt-get install javascriptcoregtk-4.1 libsoup-3.0 webkit2gtk-4.1 -y`

It's worked for me

Edit by @FabianLars: These are the requirements for tauri v2! For v1 see the other comments above.

**Comment by FreeWebber** [comment]
> You need to install the system dependencies listed [here](https://tauri.studio/docs/getting-started/setting-up-linux/#1-system-dependencies).

Link is broken, now it's [here](https://tauri.app/v1/guides/getting-started/prerequisites)

**Comment by ShaneEverittM** [comment]
> `sudo apt-get install javascriptcoregtk-4.1 libsoup-3.0 webkit2gtk-4.1 -y`
> 
> It's worked for me
> 
> Edit by @FabianLars: These are the requirements for tauri v2! For v1 see the other comments above.

I'm getting the same bug but on Windows?

**Comment by ZoeLeee** [comment]
> `sudo apt-get install javascriptcoregtk-4.1 libsoup-3.0 webkit2gtk-4.1 -y`
> 
> It's worked for me
> 
> Edit by @FabianLars: These are the requirements for tauri v2! For v1 see the other comments above.

It's worked for me

**Comment by OJFord** [comment]
Note on ubuntu (at least, GH Actions' `ubuntu-latest`) it's:
- **lib**javascriptcoregtk-4.1 **-0**
- libsoup-3.0 **-0**
- **lib**webkitgtk-4.1 **-0**

Then it still doesn't work because:
```
 error: failed to run custom build command for `gdk-sys v0.18.0`
[...]
  --- stderr
  `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" "pkg-config" "--libs" "--cflags" "gdk-3.0" "gdk-3.0 >= 3.22"` did not exit successfully: exit status: 1
  error: could not find system library 'gdk-3.0' required by the 'gdk-sys' crate
  --- stderr
  Package gdk-3.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gdk-3.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gdk-3.0' found
  Package gdk-3.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gdk-3.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'gdk-3.0' found
```

`libgdk3.0-cil` doesn't fix it; leaving it there for now.

**Comment by FabianLars** [comment]
If you append -0 it will install the runtime package but to build the app you will need the development packages that have the -dev suffix instead of -0.

The `lib` in front while technically correct is not reallyyy required since apt-get interprets it as a pattern and will add the lib prefix itself. Same for -dev as long as you do not append the -0.

To be extra clear, the most correct name on ubuntu is `libwebkit2gtk-4.1-dev`. This will also include libsoup and libjavascriptcore so in theory you can remove the other 2.

**Comment by kleenkanteen** [comment]
I am using github codspaces that uses Ubuntu 20 LTS and am getting this error:

```
@kleenkanteen ➜ /workspaces/speak-together (main) $ sudo apt install libwebkit2gtk-4.1-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libwebkit2gtk-4.1-dev
E: Couldn't find any package by glob 'libwebkit2gtk-4.1-dev'
```

Any ideas? What a pain

**Comment by kleenkanteen** [comment]
I am using github codspaces that uses Ubuntu 20 LTS for tauri v1 and am getting this error:
```
@kleenkanteen ➜ /workspaces/speak-together (main) $ sudo apt install libwebkit2gtk-4.1-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libwebkit2gtk-4.1-dev
E: Couldn't find any package by glob 'libwebkit2gtk-4.1-dev'
```
Similar error if I do `sudo apt-get install javascriptcoregtk-4.1 libsoup-3.0 webkit2gtk-4.1 -y`:
```
@kleenkanteen ➜ /workspaces/speak-together (main) $ sudo apt-get install javascriptcoregtk-4.1 libsoup-3.0 webkit2gtk-4.1 -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package javascriptcoregtk-4.1
E: Couldn't find any package by glob 'javascriptcoregtk-4.1'
E: Couldn't find any package by regex 'javascriptcoregtk-4.1'
E: Unable to locate package libsoup-3.0
E: Couldn't find any package by glob 'libsoup-3.0'
E: Couldn't find any package by regex 'libsoup-3.0'
E: Unable to locate package webkit2gtk-4.1
E: Couldn't find any package by glob 'webkit2gtk-4.1'
E: Couldn't find any package by regex 'webkit2gtk-4.1'
```
I did `sudo apt update` and `sudo apt update` before all this.

Any ideas? What a pain

**Comment by FabianLars** [comment]
If you want to develop for tauri v1 (which you said) then you want to install webkitgtk 4.0 not 4.1

If you want to develop for v2 then you need Ubuntu 22.04 or above for 4.1

**Comment by kleenkanteen** [comment]
That fixed the erorr, I installed webgitktk 4 with `sudo apt install libwebkit2gtk-4.0-dev`. 

Now I get the error `(speak-together:28859): Gtk-WARNING **: 19:14:44.440: cannot open display:`. I think since I am connected over ssh. I tried following https://stackoverflow.com/questions/76961661/how-to-open-the-tauri-application-located-on-the-server, no banana.

Is it feasible to do tauri developement over ssh?

**Comment by hellojason3** [comment]
If you meet this in Ubuntu24, unfortunately, it does not have the libwebkit2gtk-4.0-dev package yet, see this link in the official repository.
[ubuntu official package search](https://packages.ubuntu.com/search?suite=noble&section=all&arch=any&keywords=libwebkit2gtk&searchon=names )
I haven't found a solution yet and gave up on tauri for now.

**Comment by AndreRojasMartinsson** [comment]
Workaround in this issue tauri-apps/tauri#9662

> I worked around this by adding the following line to /etc/apt/sources.list:
> 
> deb http://gb.archive.ubuntu.com/ubuntu jammy main
> 
> Then doing:
> 
> sudo apt update
> sudo apt install libwebkit2gtk-4.0-dev
> 
> IMPORTANT: it was recommended in this https://github.com/tauri-apps/tauri/issues/9662#issuecomment-2133959550 to undo the change to sources.list after installing to prevent problems with dependencies being deleted.

**Comment by ashishk15678** [comment]
> `sudo apt-get install javascriptcoregtk-4.1 libsoup-3.0 webkit2gtk-4.1 -y`
> 
> It's worked for me
> 
> Edit by [@FabianLars](https://github.com/FabianLars): These are the requirements for tauri v2! For v1 see the other comments above.

I did what above suggested , and it worked but then when i try to run into the same issue , even if the package is installed yet shows the same issue , attaching images as well

<img width="1292" height="509" alt="Image" src="https://github.com/user-attachments/assets/52a12bb6-0a17-4262-b91b-ff153868326a" />

<img width="1328" height="574" alt="Image" src="https://github.com/user-attachments/assets/70a1f8f0-14f6-49bd-90e1-99445b483c2a" />

to reproduce , try this repo  https://github.com/tomheaton/tauri-rspc-prisma , (i am trying to get rspc and prisma initialiser at one place since installing them seperately sends back lots of configuration issues. )

**Comment by FabianLars** [comment]
@ashishk15678 That's what the last line of the message you quoted meant. The error is complaining about not finding webkitgtk 4.0 (tauri v1). On your first screenshot you only installed webkitgtk 4.1 (tauri v2). Note that depending on your OS 4.0 may not be available anymore https://github.com/tauri-apps/tauri/issues/9662

**Comment by ashishk15678** [comment]
thanks @FabianLars , but i dont think i should update it to v2 , because the command that i am trying to use now `create-rspc-app` , is providing only with tauri v1 (1.2.1) , do you have any other such tools which may help me to get around it , or any other installer as well will work . I just want to work with rspc , prisma and tauri.

Also yes the webkitgtk~4.0 is not available .

**Comment by FabianLars** [comment]
I probably wouldn't recommend rpsc at all at the moment, at least for tauri apps: https://github.com/specta-rs/rspc/discussions/351 / https://github.com/specta-rs/rspc/issues/356 / https://github.com/specta-rs/rspc/issues/341

**Comment by ashishk15678** [comment]
alright thank-you man !!!
