### ISSUE TITLE
[feat] Support non-semver for auto-updater with static JSON

### ISSUE THREAD

**Issue by burdiyan** [tauri-apps/tauri#3714]
### Describe the problem

After reading the docs and the code, it seems like Tauri requires to use SemVer for auto-updater (at least with the static JSON file).

It would be great if it could support other versioning schemes or be totally agnostic to it. We'd like to use some [date-based versioning scheme](https://calver.org). I believe you could still do that with server-side updated (is that true?), but it would be nice to be able to do that with static JSON file too.

### Describe the solution you'd like

Add a configuration option (or maybe even make it a default) to compare `pub_date` instead of `version` or `name`. Tauri requires dates to be formatted as ISO 8601, which has a nice property of being sortable (at least when using the same time zone). So Tauri could just even compare versions lexicographically, without parsing the string.

One caveat with this approach is that the release process should be reproducible, e.g. use commit date instead of the build job date. I strongly believe a sane release process should do that anyway though :)

### Alternatives considered

Try to parse `version` | `name` as SemVer first, but fallback to lexicographical string comparison.

**Comment by FabianLars** [comment]
The main drawback here is that the app itself _needs_ to be major.minor.patch, numeric only, mainly (or only) because of wix. And last time I checked the msi skips the installation if the same version is already installed (did you try that already yourself? I may very well be wrong here).

**Comment by burdiyan** [comment]
I haven't touched windows in more than 10 years, and know nothing about it to be honest. I just read some docs on MSI and WIX and apparently you're right:

> ProductVersion Property is defined as [0-255].[0-255].[0-65535] ( 8,8,16 signed bit respectively)

🤦‍♂️

I also read that apparently what is important for MSI to determine if it needs to update is FileVersion not so much ProductVersion. But anyway it needs to be a number as far as I understand.

Closing this, as looks like it's not possible to use any less rigid versioning scheme for Windows MSI 😢
