### ISSUE TITLE
[bug] `file-drop` event fires with the same payload 

### ISSUE THREAD

**Issue by gdotdesign** [tauri-apps/tauri#3718]
### Describe the bug

I've implemented the `file-drop` event like this (`Tauri` is `@tauri-apps/api` exposed):

```
Tauri.event.listen('tauri://file-drop', (e) => {
  console.log(e)
})
```

The first time, it shows the path of the dragged file, but subsequent times it shows the path of the first dragged file.

### Expected behavior

The event should show the path of the most recent dropped file(s).

### Platform and versions

```shell
Operating System - Linux, version 6.1 X64

Node.js environment
  Node.js - 16.13.1
  @tauri-apps/cli - 1.0.0-rc.6
  @tauri-apps/api - 1.0.0-rc.2

Global packages
  npm - 8.1.2
  pnpm - Not installed
  yarn - 1.22.17

Rust environment
  rustup - 1.24.3
  rustc - 1.57.0
  cargo - 1.57.0
  toolchain - stable-x86_64-unknown-linux-gnu 

App directory structure
/core
/app-public
/app-private
/.git
/node_modules
/.github
/src-tauri
/screenshotter
/notarize
/app
/app-desktop
/app-extension
/website
/redirect-app
/assets
/extensions

App
  tauri - 1.0.0-rc.4
  tauri-build - 1.0.0-rc.4
  tao - 0.6.4
  wry - 0.13.3
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../app-desktop/dist
  devPath - http://localhost:3000/
```

**Comment by lucasfernog** [comment]
I can't reproduce this. Can you write a minimal example @gdotdesign ?

**Comment by gdotdesign** [comment]
@lucasfernog here it is: https://github.com/gdotdesign/tauri-issue-371

https://user-images.githubusercontent.com/302692/160232295-9be3cd9e-0b31-4a18-b65b-6545ff8faee9.mp4

**Comment by gdotdesign** [comment]
:thinking: maybe it's a wierd interaction between the file browser in Elementary OS https://github.com/elementary/files/ and Tauri, since it works with Nautilus.

Let me know if I should keep this issue open.

**Comment by lucasfernog** [comment]
I can reproduce it using the Elementary file explorer. Will check on `wry` now.

**Comment by lucasfernog** [comment]
This is definitely something with the Elementary file explorer. When you drag and drop a file to a Tauri window, the file explorer keeps the file selected. You can see that even the app preview image is not updated (if you try to drop two files of different extension).

You can also see the problem if you drag and drop the file to a tauri window, and after that you drop a different file to the file explorer window (results in the first selected file getting copied to the folder opened on the explorer). After that, dropping another file on the Tauri window shows the correct path, suggesting that the selected file was cleared on the explorer side.

**Comment by dwhyte19** [comment]
I had the same issue, sometimes the file drop event shows up a dozen times as duplicates

**Comment by Dan86de** [comment]
Same here for me on macOS

**Comment by dwhyte19** [comment]
Try this. I was able to fix the duplicate drag drop triggering:
```typescript
import { listen } from '@tauri-apps/api/event';

listen('tauri://file-drop', async ({ event, payload }) => {
    console.log("Drag Drop was triggered");
});
``` 

Make sure you only set the listener once, so there's not multiple instances.
So you could do the following in your React component:
```typescript
import { listen } from '@tauri-apps/api/event';

function App() {
 //init listener for windows drag-drop init once
  useEffect(() => {
    listen('tauri://file-drop', async ({ event, payload }) => {
        console.log("Drag Drop was triggered");
    });
  }, []);
}
```

**Comment by Dan86de** [comment]
I'm using solution with `triggered:boolean` variable for now.
```ts
// outside of the component 
let triggered = false

useEffect(() => {
    if (window.__TAURI__ && !triggered) {
      triggered = true
      listen<TauriEvent.WINDOW_FILE_DROP>(
        'tauri://file-drop',
        async (event: any) => {
          const firstFilePath = (event.payload as any)[0]
          // make anything with event
        }
      )

      setTimeout(() => {
        triggered = false
      }, 3000)
    }
  }, [])
  ```
