### ISSUE TITLE
[bug] Setup error

### ISSUE THREAD

**Issue by Egeye** [tauri-apps/tauri#3720]
### Describe the bug

There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.

### Reproduction

1. A demo from 【npx create-tauri-app】
2. npm run tauri:build
3. Copy 【\target\release\bundle\msi\tauri-app_0.1.0_x64_en-US.msi】 to another PC
4. Click tauri-app_0.1.0_x64_en-US.msi and try to install it
5. Wait a minute，See error 【There is a problem with this Windows Installer package. Aproblem run as part of the setup did not finish as excepted. Contact your support personnel or package vendor.】

### Expected behavior

Install Successfully in any PC

### Platform and versions

```shell
PS E:\vue-workbench\Demo\tauri\tauri-app> npm run tauri:build

> tauri-app@0.1.0 tauri:build E:\vue-workbench\Demo\tauri\tauri-app
> vue-cli-service tauri:build


⠧  Building legacy bundle for production...

 DONE  Compiled successfully in 5026ms                                                                                                              下午9:56:48

  File                                                                 Size                                       Gzipped  

  src-tauri\target\webpack_dist\js\chunk-vendors-legacy.0528ff92.js    128.02 KiB                                 46.03 KiB
  src-tauri\target\webpack_dist\js\app-legacy.ffe86ff1.js              1.78 KiB                                   0.95 KiB 

  Images and other types of assets omitted.
  Build at: 2022-03-17T13:56:48.228Z - Hash: 970fa7a36fc8700a - Time: 5026ms


⠏  Building module bundle for production...

 DONE  Compiled successfully in 3313ms                                                                                                              下午9:56:54
  File                                 Size                                                       Gzipped

  dist\js\chunk-vendors.3268bb91.js    78.68 KiB                                                  28.07 KiB
  dist\js\app.fe6adf07.js              1.85 KiB                                                   0.97 KiB

  Images and other types of assets omitted.
  Build at: 2022-03-17T13:56:54.264Z - Hash: a75f9d547eab5478 - Time: 3313ms

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html

   Compiling app v0.1.0 (E:\vue-workbench\Demo\tauri\tauri-app\src-tauri)
    Finished release [optimized] target(s) in 41.28s                                                                                                           
info: Target: x64
info: trying to sign app
info: running candle for "main.wxs"
info: running candle.exe
info: running light to produce E:\vue-workbench\Demo\tauri\tauri-app\src-tauri\target\release\bundle/msi/tauri-app_0.1.0_x64_en-US.msi
    Finished 1 bundle at:
        E:\vue-workbench\Demo\tauri\tauri-app\src-tauri\target\release\bundle/msi/tauri-app_0.1.0_x64_en-US.msi
PS E:\vue-workbench\Demo\tauri\tauri-app>

PS E:\vue-workbench\Demo\tauri\tauri-app> node -v
v14.15.4
PS E:\vue-workbench\Demo\tauri\tauri-app> npm -v
6.14.10
PS E:\vue-workbench\Demo\tauri\tauri-app> rustup -V
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.59.0 (9d1b2106e 2022-02-23)`
PS E:\vue-workbench\Demo\tauri\tauri-app>
```

**Comment by amrbashir** [comment]
What version of Windows are you running the installer on? Is it Windows 7?

**Comment by MuLoo** [comment]
> 

i have the same error on win7. Any help please ?

**Comment by MuLoo** [comment]
My guess is that when the msi package is installed, it will download some webview related stuff, and if at that point, your network is bad or limited, then this will happen.
so, you need to go to this [site](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) and download the WebView2 Runtime first. chose **Evergreen Bootstrapper** and install. After you finish installing it, then install your msi package and should be ok.
At least it works for me. 
good luck.

**Comment by Egeye** [comment]
> What version of Windows are you running the installer on? Is it Windows 7?

Windows 10

**Comment by amrbashir** [comment]
do you have a slow internet connection or using a proxy or something? did you follow the suggestion in the [comment](https://github.com/tauri-apps/tauri/issues/3720#issuecomment-1092645090) above?

**Comment by marcokernler** [comment]
Hi there,
same problem for me, but the hints in the comment above have resolved the issue. Generally there should be no Problems with network connection or proxy settings on the machine.

But will/can this be fixed in the future, as requiring the user to download further packages are not really an option imo?

**Comment by lucasfernog** [comment]
Downloading the webview2 bootstrapper as part of the installation is the recommendation from Microsoft. If you can't really rely on that, you can change the webview2 install option in the config file: https://tauri.app/v1/guides/building/windows#webview2-installation-options
