### ISSUE TITLE
[bug] drag content, but failed drop in rich-text editor

### ISSUE THREAD

**Issue by percy507** [tauri-apps/tauri#3722]
### Describe the bug

Hi, 

> Test url: https://prosemirror.net/examples/basic/

In this page, there is a basic editor based on ProseMirror. 

When I select some text or img node, I want to drag it into the position where I want to.

On safari browser or chrome browser, it works as expected.

But when I open it in tauri's webview, the drag not works. It can be drag, but it can't be drop.

> And.. There is no any error log in console or terminal.

![2022-03-17 23 02 20](https://user-images.githubusercontent.com/18365078/158832577-4cc04def-269f-47e3-bf07-3301c713bca6.gif)

### Platform and versions

```shell
npx tauri info

Operating System - Mac OS, version 11.6.0 X64

Node.js environment
  Node.js - 16.10.0
  @tauri-apps/cli - 1.0.0-rc.5 (outdated, latest: 1.0.0-rc.7)
  @tauri-apps/api - 1.0.0-rc.1 (outdated, latest: 1.0.0-rc.2)

Global packages
  npm - 7.24.0
  pnpm - 6.16.0
  yarn - 1.22.15

Rust environment
  rustup - 1.24.3
  rustc - 1.59.0
  cargo - 1.59.0
  toolchain - stable-x86_64-apple-darwin 

App directory structure
/.husky
/node_modules
/public
/scripts
/src-tauri
/.git
/.vscode
/src

App
  tauri - 1.0.0-rc.3
  tauri-build - 1.0.0-rc.3
  tao - 0.6.2
  wry - 0.13.3
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - https://prosemirror.net/examples/basic/
  framework - React
  bundler - Rollup
```

**Comment by percy507** [comment]
Ah. It seems if I disable the `fileDropEnabled` config in `tauri.conf.json` , then the rich-text can be drag and drop.

I find the doc of the [`fileDropEnabled` config](https://github.com/tauri-apps/tauri/blob/393f4b3d79b77efa388d604d5308efa67b2c9c9d/tooling/api/src/window.ts#L1247). 

<img width="759" alt="image" src="https://user-images.githubusercontent.com/18365078/159172296-6e94cb49-9a49-43d9-b0b4-792d91c94ff1.png">

After some test, I am confused. I have disable this config, but I still can drag external file inside it. 

Emmm, am I wrong or is it really a bug?

**Comment by nothingismagick** [comment]
Can you share a minimal reproduction repo please?

**Comment by percy507** [comment]
Hi @nothingismagick ,

I made a test just now. And I use a fresh tauri project created by `npx create-tauri-app`.

I don't change anything but the config file `tauri.conf.json`.

- The changes:
  - set the `devPath` with value `"https://prosemirror.net/examples/basic/"`
  - set the `fileDropEnabled` with value `false`

Then you can see what I said above.

> Well, I try to drag file into the app when the `fileDropEnabled` config is true or unset, the file can't drop into the app.
>
> It seems the `fileDropEnabled` should be named `fileDropDisabled`. Haha.
>
> Ps: the files which I test include image, pdf and markdown file.

**Comment by dennis84** [comment]
I have the same problem. It seems that the dropped event is fired when you move text in a contenteditable using a Mac and then it's blocked [here](https://github.com/tauri-apps/tauri/blob/822b038c3ee96ad54974a8cbfd240a000b9b451b/core/tauri-runtime-wry/src/lib.rs#L2861). I could figure out that the paths are an empty Vec in this case: [here](https://github.com/tauri-apps/wry/blob/1c5d77a8ce79e75705a71c659af86541d50c5007/src/webview/wkwebview/file_drop.rs#L122). The same with ubuntu returns a None: [here](https://github.com/tauri-apps/wry/blob/1c5d77a8ce79e75705a71c659af86541d50c5007/src/webview/webkitgtk/file_drop.rs#L42) and doesn't fire the event.

I tested it in wry by modifying the dragndrop example:

```
diff --git a/examples/dragndrop.rs b/examples/dragndrop.rs
index 5ff3231..405262b 100644
--- a/examples/dragndrop.rs
+++ b/examples/dragndrop.rs
@@ -6,6 +6,7 @@ static HTML: &str = r#"data:text/html,
 Drop files onto the window and read the console!<br>
 Dropping files onto the following form is also possible:<br><br>
 <input type="file"/>
+<div contenteditable="true">213454567567678</div>
 "#;
 
 fn main() -> wry::Result<()> {
```

**Comment by rming** [comment]
same problem. 
ondrop event not fired

**Comment by FabianLars** [comment]
@dennis84 @Rming Did you disable "fileDropEnabled" in your window config? <https://tauri.studio/docs/api/config/#tauri.windows.fileDropEnabled>
There is currently no way to have both, file-drop and html5 drag-and-drop in the same window.

**Comment by rming** [comment]
> @dennis84 @Rming Did you disable "fileDropEnabled" in your window config? https://tauri.studio/docs/api/config/#tauri.windows.fileDropEnabled There is currently no way to have both, file-drop and html5 drag-and-drop in the same window.

Tried it, the ondrop event is not fired whether it is disabled or not

**Comment by FabianLars** [comment]
@Rming Are you on macOS too?

**Comment by rming** [comment]
Problem solved, ondrop event fired successfully.

The problem is because I misconfigured the file, I created the window programmatically, so I misunderstood when I read the documentation.

WRONG EXAMPLE
```
{
  "tauri": {
    "windows": {
      "fileDropEnabled":false
    }
}
```

Disable programmatically：
```
  builder.create_window("test window", quick_url, |win, webview| {
    let win = win.title("test").visible(false);

    let webview = webview.disable_file_drop_handler();

    return (win, webview);
  }).expect("error build test window")
```

**Comment by dennis84** [comment]
@FabianLars Yes it was enabled. I have now disabled it and when i drag a file into the window, a new tab opens, like a regular browser. Is that normal, can I stop this? (Tested with a macOS in tauri helloworld example)

**Comment by rming** [comment]
@dennis84  Make sure you have added the listener correctly and prevent the default behavior of drag events.

**Comment by josmanvis** [comment]
is there anyway to detect a link dragged in? i am trying to build a Tauri + Solidjs app that can take receive dropped links (anchor tags on websites in another browser). Is this possible?
