### ISSUE TITLE
[bug] Trying to create a window with a `.` in the label will not create the window neither throw an error.

### ISSUE THREAD

**Issue by firstdorsal** [tauri-apps/tauri#3726]
### Describe the bug

Trying to create a window with a `.` in the label will not create the window neither throw an error.

```ts
const webview = new WebviewWindow("hello.test", {
                            url: "/"
});
```
This is okay but at least not stated in the docs:
https://tauri.studio/docs/api/js/classes/window.WebviewWindow#constructor

### Platform and versions

```shell
Operating System - Arch Linux, version Rolling Release X64

Node.js environment
  Node.js - 17.7.1
  @tauri-apps/cli - 1.0.0-rc.6
  @tauri-apps/api - 1.0.0-rc.2

Global packages
  npm - 8.5.4
  pnpm - Not installed
  yarn - 1.22.18

Rust environment
  rustup - 1.24.3
  rustc - 1.59.0
  cargo - 1.59.0
  toolchain - stable-x86_64-unknown-linux-gnu 

App directory structure
/dist
/node_modules
/src-tauri
/src
/.git
/public

App
  tauri - 1.0.0-rc.4
  tauri-build - 1.0.0-rc.4
  tao - 0.6.4
  wry - 0.13.3
  build-type - build
  CSP - default-src tauri: asset: https://asset.localhost
  distDir - ../dist
  devPath - http://localhost:3000/
  framework - React
```

**Comment by FabianLars** [comment]
> This is okay but at least not stated in the docs

It does mention that it requires the label to be alphanumeric. (Tbf alphanumeric can _optionally_ include additional characters like punctuation in some definitions). This still needs to be adjusted since it's alphanumeric plus `-`, `/`, `:` and `_`.

But you're right about the error, it's supposed to throw one, just like it does in rust. #3544

**Comment by firstdorsal** [comment]
Oh yes you are right it is stated below but when trying to get it working everyone will read the example (like me) and try it out not reading what is stated half a page down beneath the fold.
![image](https://user-images.githubusercontent.com/10563452/158996819-bdf3e4a8-b1f2-41a7-ae9b-ba277ce03987.png)

So maybe something like this?
```ts
// the label may only contain alphanumeric characters: a-zA-Z-/:_
const webview = new WebviewWindow('theUniqueAlphaNumericLabel', {
  url: 'path/to/page.html'
})
```

Thank you!

**Comment by FabianLars** [comment]
@JonasKruckenberg What do you think?
Also, i'm gonna re-add the bug label since this issue describes 2 issues (the doc and the function not returning an error)

**Comment by JonasKruckenberg** [comment]
I prefer documenting the type (class) not methods associated to it, especially for something as important as the window label it should be documented in the comment for `WebviewWindow` not it's constructor IMO.
The best example of this is wasmtime: https://docs.rs/wasmtime/latest/wasmtime/struct.Store.html where they have extensive documentation for each type and limited documentation for each method. 

But let's do both! Let's mention this in the WebiewWindows doc comment and add an example too. 

Edit: created PR #3730

**Comment by JonasKruckenberg** [comment]
@lucasfernog

**Comment by JonasKruckenberg** [comment]
As the [documentation](https://tauri.studio/docs/api/js/classes/window.WebviewWindow) mentions, errors are emitted as the `tauri://error` event and I can confirm it actually returns the proper error there.

**Comment by FabianLars** [comment]
Honestly don't know how to feel about that 🤔

**Comment by lucasfernog** [comment]
It uses the event because we use the constructor of the WebviewWindow class, which cannot return a promise obviously.

We could either use a static method instead of the constructor:

```typescript
const w = await WebviewWindow.create(...options)
```

or assign the promise on the WebviewWindow constructor to let the user await it:
```typescript
const w = new WebviewWindow(...options)
await w.promise;
```

First one is better but I really like the constructor usage, it makes more sense and it feels natural to JS developers. Note that on normal circustances the window creation shouldn't fail.

**Comment by FabianLars** [comment]
Ahh oh my god I forgot that we're talking about a constructor, nvm then...

Edit: therefore I prefer the current way too

**Comment by JonasKruckenberg** [comment]
> First one is better but I really like the constructor usage, it makes more sense and it feels natural to JS developers.

Tbh I think the constructor + events approach makes a lot of sense to JS folks. 
The events should just not be prefixed 🤔

**Comment by liesauer** [comment]
> > This is okay but at least not stated in the docs
> 
> It does mention that it requires the label to be alphanumeric. (Tbf alphanumeric can _optionally_ include additional characters like punctuation in some definitions). This still needs to be adjusted since it's alphanumeric plus `-`, `/`, `:` and `_`.
> 
> But you're right about the error, it's supposed to throw one, just like it does in rust. #3544

hi, is that ok to add `.` as valid character? i personally think having `com.company.app-name` as window label(identifier) is a good choice and it's a little danger to use `/` and `:` since they are invalid path character, it may cause potential unauthorized access.

**Comment by FabianLars** [comment]
> hi, is that ok to add . as valid character?

Nope. Check the [audit report](https://github.com/tauri-apps/tauri/tree/dev/audits) for the reasoning.

**Comment by liesauer** [comment]
after reading the report and tauri source code, `.` should not be a problem sinces all the special symbols are not allowed, `'` `"` `\` etc. there is no js injection problem any more.

https://github.com/tauri-apps/tauri/blob/e4292ce7be198f6265dde9b6ae54e73b7c41e7da/core/tauri-runtime/src/window.rs#L237-L241

https://github.com/tauri-apps/tauri/blob/e4292ce7be198f6265dde9b6ae54e73b7c41e7da/core/tauri/src/manager.rs#L1343-L1354
