### ISSUE TITLE
[feat] Do not query when field isNull

### ISSUE THREAD

**Issue by cuizhijun** [tauri-apps/tauri#3727]
### Describe the problem

`select * from project where type= '${type}' and status = '0'`

Do not query when type isNull

### Describe the solution you'd like

Do not query when type isNull

**Comment by JonasKruckenberg** [comment]
I'm rather confused by this issue, did you mean do open an issue for https://github.com/tauri-apps/tauri-plugin-sql instead?
Tauri is not a SQL engine but a desktop app framework.
