### ISSUE TITLE
[feat] Browser extension

### ISSUE THREAD

**Issue by Zhiqiang-Wu** [tauri-apps/tauri#3729]
### Describe the problem

Redux DevTools
React Developer Tools
........

### Describe the solution you'd like

....

**Comment by FabianLars** [comment]
This is nothing we can control. This needs to be implemented in the webview itself, this already rules out macos and linux and last time i checked Microsoft is either working on it or only considering it.

For now you have to use the standalone dev tools. I don't know about redux, but react offers a standalone version.
