### ISSUE TITLE
[feat] File drop event enum

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri#3732]
### Describe the problem

I noticed file drop events:

- `tauri://file-drop`
- `tauri://file-drop-hover` 
- `tauri://file-drop-cancelled`

are only exposed to rust via the string ids. 

### Describe the solution you'd like

In the same spirit of other events we should expose these to Rust in a structured format (enum).

**Comment by FabianLars** [comment]
#3686

**Comment by JonasKruckenberg** [comment]
oops, my bad! Thanks for the reminder!
