### ISSUE TITLE
How to play video file selected by user on webview?

### ISSUE THREAD

**Issue by red010182** [tauri-apps/tauri#3735]
### Describe the bug

From https://tauri.studio/docs/api/js/modules/tauri/ there's `convertFileSrc` to convert file system location to url which can be used in the webview. But did `convertFileSrc` work for arbitary file system location? Or just for files allowed in `tauri.conf.json`?

### Platform and versions

```shell
.
```

**Comment by red010182** [comment]
```
"allowlist": {
      ...
      "protocol": {
        "asset": true,
        "assetScope": ["**"]
      }
    },
    "security": {
      "csp": "default-src 'self'; img-src 'self' asset: https://asset.localhost; media-src 'self' asset: https://asset.localhost"
    }
```

**Comment by FabianLars** [comment]
Yeah, you really shouldn't do this. This gives javascript access to the whole filesystem. We are already working on a fix for this btw so this "solution" will break on the next release.

On your actual question: The asset scope gets automatically expanded with **user-selected** paths (dialog & file-drop) so you shouldn't run into problems if the paths are indeed selected by the user. Alternatively you can expand the scope in rust at runtime too (be careful with that!)

**Comment by red010182** [comment]
Thanks a lot. I didn't know asset scope gets automatically expanded with user-selected paths.

**Comment by hjmallon** [comment]
@FabianLars : What is the correct way to expand the scope at runtime in Rust?

**Comment by FabianLars** [comment]
Using this: https://docs.rs/tauri/latest/tauri/scope/struct.FsScope.html which you can get from an AppHandle. could look something like this if used in a command
```rs
use tauri::Manager;

#[tauri::command]
fn extend_scope(handle: tauri::AppHandle, path: std::path::PathBuf) {
  let asset_scope = handle.asset_protocol_scope();
  let fs_scope = handle.fs_scope();

  // ideally you don't apply a path sent from the frontend or at least not without some validation
  asset_scope.allow_file(&path);
}
```
