### ISSUE TITLE
[feat] Adding file association functionality.

### ISSUE THREAD

**Issue by sprout2000** [tauri-apps/tauri#3736]
### Describe the problem

At this time, I can't double-click or right-click on a file to launch an app.

### Describe the solution you'd like

I would like to be able to configure file associations via `tauri.config.json`.

**Comment by FabianLars** [comment]
For reference and some hints: #918.

Edit: You can keep this issue open since the other one's closed without being generally resolved.

**Comment by mantou132** [comment]
Some simple research:

Window: [registry](http://woshub.com/managing-default-file-associations-in-windows-10/) + [launch args](https://doc.rust-lang.org/std/process/struct.Command.html#method.args)
macOS: [info.plist](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundledocumenttypes) + [callback](https://developer.apple.com/documentation/appkit/nsapplicationdelegate/1428742-application)

**Comment by MunsMan** [comment]
Are there any updates? I'm currently pretty new to tauri and still learning a lot, but I can't figure out how to open files with my app selected for opening it. I added a CLI which opens the first parsed file and I have a button to open files. But when I open a document with macOS, I get the error that my app doesn't support PDF. Sadly, displaying PDF is its only purpose. I would love some help or a hind in the right direction.

**Comment by jzillmann** [comment]
I asked for a related feature here: https://discord.com/channels/616186924390023171/1110215400047784058 and got forwarded to this ticket. 

In my case I want to open files with my tauri app (text editor) through the terminal. E.g. with `open -a /Users/jz/MyProject.app ~/Desktop/sidebar.svg`, but got the same `no supported` message.

<img width="292" alt="Screen Shot 2023-05-22 at 16 38 37" src="https://github.com/tauri-apps/tauri/assets/148472/abe36fb5-3ddd-4554-8037-dcfa39c482eb">

**Comment by billyjacoby** [comment]
Hmm I'm running into this exact issue now and can't seem to figure out how to get around it. I was hoping that one of the args passed in to the application when opened would be the file path, but that doesn't seem to be the case.

Any thoughts on how to get the file path for the file that was clicked to open the Tauri app?

I've tried using `env::args_os()` and ` env::args()` but neither of them seem to include any relevant information.

**Comment by qu1ck** [comment]
Windows can have file associations through wix/nsis templates.
Linux can have them through deb.desktopTemplate.
Should MacOS bundle support injecting custom plist file?

**Comment by SFCMN** [comment]
Hope to support this feature soon, it's a very common requirement for most file-viewing programs

**Comment by tnrich** [comment]
@lucasfernog I'm not seeing file associations within the tauri docs. Should this issue actually be closed yet? Seems like it hasn't fully made it in?

**Comment by lucasfernog** [comment]
It's a v2 feature and it isn't documented yet @tnrich.

@lorenzolewis do we have a place we're tracking pending features to be documented?

**Comment by lorenzolewis** [comment]
Thanks @lucasfernog and @tnrich ! I've created an issue to track here: https://github.com/tauri-apps/tauri-docs/issues/1526

For anything else that we need to track to be documented feel free to add an issue in that repo and link any respective PRs.

@lucasfernog I use https://github.com/tauri-apps/tauri-docs/milestone/4 as the to-do list so if you can just make sure any issues are added to that milestone that gets it on the official™️ list.

**Comment by eugenehp** [comment]
Just adding this here as a reference: https://github.com/tauri-apps/tauri/tree/dev/examples/file-associations (windows and linux)


for Mac – use [tauri-plugin-deep-link](https://crates.io/crates/tauri-plugin-deep-link/)

**Comment by ryusei-48** [comment]
I realize that this approach is a good way to get the TAURI program started for the first time, but is there a sample like Electron's `open-file` event that would allow a running TAURI program to receive notification and get the file path when the associated file is double-clicked while the TAURI program is running?

**Comment by martpie** [comment]
To double down on what @ryusei-48 said, it seems this peculiar behavior works well on macOS thanks to the Opened event, but I cannot manage to make things work the same for Linux/Windows.

Combining things with the single-instance plugin makes things even more cryptic.

**Comment by qu1ck** [comment]
@martpie The way this is usually implemented is to open a pipe/socket on the first instance of the app and when OS launches another instance because user double clicked a file in explorer then the new instance tries to open the same pipe/socket, fails, sends the path to the first instance that is listening on the pipe/socket and then exits.

That's how I did it in my tauri app too.

**Comment by stevietelly** [comment]
So far I have seen file association working in terms of launching the app, but i cant seem to find anywhere about receiving that file path in the frontend, the example provided by @eugenehp  has this 

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>File Associations</title>
  </head>

  <body>
    <h1>File Associations</h1>
    <pre id="files"></pre>

    <script>
      const filesView = document.getElementById('files')
      filesView.textContent = window.openedFiles.join('\n')
    </script>
  </body>
</html>
```

The project i am working on uses react with typescript, so this is out of limits for me

**Comment by eugenehp** [comment]
Have you looked into the [main.rs](https://github.com/tauri-apps/tauri/blob/dev/examples/file-associations/src-tauri/src/main.rs#L25-L48) code where the `files` are being injected into the JavaScript context?

**Comment by stevietelly** [comment]
make me  think of this `(window as any).openedFiles`. is there a way to test this in development?

**Comment by martpie** [comment]
This adds basically the files opened as part of an initialization script (from there, the UI can pick them up), but that specific code does not solve telling your app about new files opened if the app is already running (which is an issue for single instances apps).

macOS has an event you can listen to for this specific case, but Windows/Linux did not have it last time I checked.

**Comment by stevietelly** [comment]
okay so i get that and i have been playing around with [main.rs](https://github.com/tauri-apps/tauri/blob/dev/examples/file-associations/src-tauri/src/main.rs) as @eugenehp  proposed which seems to implement something for windows and i hit this section inside the `handle_file_associations` function. 
```rust
 tauri::WebviewWindowBuilder::new(&app, "main", Default::default())
    .initialization_script(format!("window.openedFiles = [{files}]"))
    .build()
    .unwrap();
```
unfortunately in my implementation, rust complains that the window "main" already exists, which means somewhere in code there is another similar build command. I initialized the project based off [Manual setup](tauri.app/start/create-project/) and i got three rust files in `src-tauri`

![Image](https://github.com/user-attachments/assets/75733059-5fa3-4dd5-b997-31fe5ca5ee4b)

so i am pretty sure this will work for windows but my rust is terrible and i am also using alot of other plugins so if someone could help me figure out where i should add the file-association main.rs code in the following

**build.rs**
```rust
fn main() {
  tauri_build::build()
}

```
**lib.rs**
```rust
use tauri_plugin_deep_link::DeepLinkExt;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
  tauri::Builder::default()
    .setup(|app| {
      if cfg!(debug_assertions) {
        app.handle().plugin(
          tauri_plugin_log::Builder::default()
            .level(log::LevelFilter::Info)
            .build(),
        )?;
      }
      Ok(())
    })
    .plugin(tauri_plugin_deep_link::init())
    .setup(|app| {
      #[cfg(desktop)]
      app.deep_link().register_all()?;
      Ok(())
    })
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}

```
**main.rs**
```rust
// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

fn main() {
  tauri::Builder::default()
    .plugin(tauri_plugin_single_instance::init(|_app, _argv, _cwd|{}))
    .plugin(tauri_plugin_deep_link::init())
    .plugin(tauri_plugin_shell::init())
    .plugin(tauri_plugin_printer::init())
    .plugin(tauri_plugin_prevent_default::init())
    .plugin(tauri_plugin_store::Builder::new().build())
    .plugin(tauri_plugin_dialog::init())
    .plugin(tauri_plugin_process::init())
    .plugin(tauri_plugin_fs::init())
    .plugin(tauri_plugin_os::init())
    .plugin(tauri_plugin_updater::Builder::new().build())
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
  app_lib::run();
}

```

**Comment by FabianLars** [comment]
> unfortunately in my implementation, rust complains that the window "main" already exists, which means somewhere in code there is another similar build command. I initialized the project based off [Manual setup](https://github.com/tauri-apps/tauri/issues/tauri.app/start/create-project/) and i got three rust files in src-tauri

The one window defined in tauri.conf.json also has the `main` label by default.

> lib.rs

Having 2 setup hooks is problematic. Merge them into one.

> main.rs

If you want to support mobile as well you should revert the main.rs file to the default and move all the plugins into lib.rs. If you only want to support desktop, you may as well remove the lib.rs file.

Assuming a default layout of main.rs + lib.rs your full example could look more like the following. This also assumes that you want to keep the window creation in tauri.conf.json and that injecting the files once at the start is enough.

> main.rs

```rs
// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

fn main() {
  app_lib::run();
}
```

> lib.rs

```rs
use tauri_plugin_deep_link::DeepLinkExt;

fn handle_file_associations(app: AppHandle, files: Vec<PathBuf>) {
  // -- Scope handling start --

  // You can remove this block if you only want to know about the paths, but not actually "use" them in the frontend.

  // This requires the `fs` tauri plugin and is required to make the plugin's frontend work:
  use tauri_plugin_fs::FsExt;
  let fs_scope = app.fs_scope();

  // This is for the `asset:` protocol to work:
  let asset_protocol_scope = app.asset_protocol_scope();

  for file in &files {
    // This requires the `fs` plugin:
    let _ = fs_scope.allow_file(file);

    // This is for the `asset:` protocol:
    let _ = asset_protocol_scope.allow_file(file);
  }

  // -- Scope handling end --

  let files = files
    .into_iter()
    .map(|f| {
      let file = f.to_string_lossy().replace('\\', "\\\\"); // escape backslash
      format!("\"{file}\"",) // wrap in quotes for JS array
    })
    .collect::<Vec<_>>()
    .join(",");

// this is the only change
  let main_win = app.get_webview_window("main").unwrap();
  let _ = main_win.eval(format!("window.openedFiles=[{files}]"));
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
  tauri::Builder::default()
    .plugin(tauri_plugin_single_instance::init(|_app, _argv, _cwd|{}))
    .plugin(tauri_plugin_deep_link::init())
    .plugin(tauri_plugin_shell::init())
    .plugin(tauri_plugin_printer::init())
    .plugin(tauri_plugin_prevent_default::init())
    .plugin(tauri_plugin_store::Builder::new().build())
    .plugin(tauri_plugin_dialog::init())
    .plugin(tauri_plugin_process::init())
    .plugin(tauri_plugin_fs::init())
    .plugin(tauri_plugin_os::init())
    .setup(|app| {
      if cfg!(debug_assertions) {
        app.handle().plugin(
          tauri_plugin_log::Builder::default()
            .level(log::LevelFilter::Info)
            .build(),
        )?;
      }

      #[cfg(desktop)]
      app.deep_link().register_all()?;

     #[cfg(any(windows, target_os = "linux"))]
      {
        let mut files = Vec::new();

        // NOTICE: `args` may include URL protocol (`your-app-protocol://`)
        // or arguments (`--`) if your app supports them.
        // files may aslo be passed as `file://path/to/file`
        for maybe_file in std::env::args().skip(1) {
          // skip flags like -f or --flag
          if maybe_file.starts_with('-') {
            continue;
          }

          // handle `file://` path urls and skip other urls
          if let Ok(url) = url::Url::parse(&maybe_file) {
            if let Ok(path) = url.to_file_path() {
              files.push(path);
            }
          } else {
            files.push(PathBuf::from(maybe_file))
          }
        }

        handle_file_associations(app.handle().clone(), files);
      }

      Ok(())
    })
   // you can replace the following for the default stuff if you don't need macos/ios support
    .build(tauri::generate_context!())
    .expect("error building tauri application")
    .run(
      #[allow(unused_variables)]
      |app, event| {
        #[cfg(any(target_os = "macos", target_os = "ios"))]
        if let tauri::RunEvent::Opened { urls } = event {
          let files = urls
            .into_iter()
            .filter_map(|url| url.to_file_path().ok())
            .collect::<Vec<_>>();

          handle_file_associations(app.clone(), files);
        }
      },
    );
}
```

Note that this may not be 100% correct. To save time i simply copy pasted everything lol

**Comment by stevietelly** [comment]
![Image](https://github.com/user-attachments/assets/3ac41027-83b7-4eca-9cb0-2a7c645cacfd)

> Note that this may not be 100% correct. To save time i simply copy pasted everything lol

Thanks @FabianLars  that works quite well

NB: vscode cant seem to recognise `let asset_protocol_scope = app.asset_protocol_scope();` so i commented out that and ` let _ = asset_protocol_scope.allow_file(file);`

**Comment by FabianLars** [comment]
yeah, that only works if you enabled the asset procotol in tauri.conf.json (don't if you don't need it).
