### ISSUE TITLE
[bug] `--debug` not passed to vite config

### ISSUE THREAD

**Issue by farfromrefug** [tauri-apps/tauri#3737]
### Describe the bug

right now if you build with `tauri build --debug` there is no way to know on the vite config side.
This is very important because you would want to have sourcemap enable in debug production builds when you could not want then in a normal release production build

### Reproduction

run `tauri build --debug`

### Expected behavior

There should be a way to know the `--debug` option was passed

### Platform and versions

```shell
> com.akylas.mbview@1.1.0 tauri
> tauri "info"


Operating System - Mac OS, version 11.6.0 X64

Node.js environment
  Node.js - 17.6.0
  @tauri-apps/cli - 1.0.0-rc.6 (outdated, latest: 1.0.0-rc.7)
  @tauri-apps/api - 1.0.0-rc.2

Global packages
  npm - 8.5.1
  pnpm - 6.32.3
  yarn - Not installed

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-apple-darwin 

App directory structure
/resources
/node_modules
/.history
/.github
/src-tauri
/build
/.git
/.vscode
/src

App
  tauri - 1.0.0-rc.4
  tauri-build - 1.0.0-rc.4
  tao - 0.6.4
  wry - 0.13.3
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: asset: mbtiles: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:3000/
  framework - Svelte
```

**Comment by FabianLars** [comment]
before(Dev|Build)Commands inject multiple env vars, one of them `TAURI_DEBUG` which should be set to true in `build --debug` too: <https://tauri.studio/docs/api/config#build.beforeBuildCommand>

**Comment by farfromrefug** [comment]
@FabianLars awesome ! sorry for not finding this is the docs.
i ll close as soon as it tested this to work

**Comment by JonasKruckenberg** [comment]
> i ll close as soon as it tested this to work 

Yes please test it on your end too, but it should work. I added it specifically for conditional compilation using vite at work. We've been using it to great success ever since.

Edit: Note that for best results you need to adapt your vite config somewhat. Here's the recommended one from the upcoming new docs:
```js

{
  // prevent vite from obscuring rust errors
  clearScreen: false,
  // tauri expects a fixed port, fail if that port is not available
  server: {
    port: 3000,
    strictPort: true,
  },
  // to make use of `TAURI_PLATFORM`, `TAURI_ARCH`, `TAURI_FAMILY`, `TAURI_PLATFORM_VERSION`, `TAURI_PLATFORM_TYPE` and `TAURI_DEBUG` env variables
  envPrefix: ['VITE_', 'TAURI_'],
  build: {
    // tauri supports es2021
    target: ['es2021', 'chrome97', 'safari13'],
    // don't minify for debug builds
    minify: !process.env.TAURI_DEBUG && 'esbuild',
    // produce sourcemaps for debug builds
    sourcemap: !!process.env.TAURI_DEBUG,
  },
}

```

**Comment by farfromrefug** [comment]
@JonasKruckenberg awesome! thanks for config. i upgraded mine with your changes!
And i confirm it works :D
