### ISSUE TITLE
[bug] fullscreen true in tauri.conf.json does not work on Ubuntu

### ISSUE THREAD

**Issue by pwespi** [tauri-apps/tauri#3738]
### Describe the bug

I created a new app with `npx create-tauri-app` and only changed `fullscreen` to `true` in `tauri.conf.json`. The app opens in fullscreen on Windows and macOS, but it does not open in fullscreen on Ubuntu.

### Reproduction

1. npx create-tauri-app
2. change `fullscreen` to `true` in `tauri.conf.json`
3. npm run tauri dev
4. app opens in normal window

### Expected behavior

App should open in fullscreen window.

### Platform and versions

```shell
Operating System - Ubuntu, version 20.04 X64

Node.js environment
  Node.js - 16.14.2
  @tauri-apps/cli - 1.0.0-rc.6 (outdated, latest: 1.0.0-rc.7)
  @tauri-apps/api - 1.0.0-rc.2

Global packages
  npm - 8.5.0
  pnpm - Not installed
  yarn - Not installed

Rust environment
  rustup - 1.24.3
  rustc - 1.59.0
  cargo - 1.59.0
  toolchain - stable-x86_64-unknown-linux-gnu 

App directory structure
/src-tauri
/public
/node_modules
/.vscode
/dist
/.git
/src

App
  tauri - 1.0.0-rc.4
  tauri-build - 1.0.0-rc.4
  tao - 0.6.4
  wry - 0.13.3
  build-type - bundle
  CSP - unset
  distDir - ../dist
  devPath - http://localhost:3000/
  framework - Svelte
```

### Additional context
```shell
$ echo $XDG_SESSION_TYPE
x11
```

*Edit:* 
* I also tested with wayland and it's the same, the app does not open in fullscreen. 
* Using `setFullscreen(true)` of the tauri JS window API works as expected.

**Comment by joshhansen** [comment]
I'm getting this, on Fedora 35

**Comment by lucasfernog** [comment]
This is a `tao` issue, the patch is here: https://github.com/tauri-apps/tao/pull/348
It will be part of the next release. Thanks for the report!

**Comment by meridbt** [comment]
Hi, @pwespi 
I'm facing the same issue on Lubuntu 22.04.2

I've tried the workaround with appWindow you mention, but it doesn't help.
Could you please suggest?
