### ISSUE TITLE
[feat] Remember Window Position and Size

### ISSUE THREAD

**Issue by elibroftw** [tauri-apps/tauri#3740]
### Describe the problem

I open the app, maximize it, close it, and when I re-open the app, it does not remember that it was maximized.

I open the app, resize it, close it, and when I re-open the app, it does not remember the size I set.

I open the app, move the window around, close it, and when I re-open the app, the position is as if its the Windows File Explorer.

### Describe the solution you'd like

1. Add an option to remember window position between sessions 
2. If `width` and `height` are not defined, then the window size should also be remember. If the window is maximized, then the window should be maximized in the next session. If minWidth and minHeight are set, Tauri shouldn't treat it as width and height.

### Alternatives considered

I'm pretty sure it's possible to do this all with the APIs given, but this should baked in because users shouldn't have to consider race conditions such as closing the app with it in the second monitor and opening the app when the second monitor is disconnected. I don't know if Windows prevents that sort of race condition or if it needs to be handled by whatever api calls the OS' set position.

### Additional context

```
"windows": [
      {
        "title": "ADJASJD",
        "minWidth": 1000,
        "minHeight": 600,
        "resizable": true,
        "fullscreen": false,
        "visible": true,
        "decorations": true,
        "alwaysOnTop": true
      }
    ],
```

**Comment by amrbashir** [comment]
use https://github.com/tauri-apps/tauri-plugin-window-state

**Comment by elibroftw** [comment]
@amrbashir does not work. see https://github.com/tauri-apps/plugins-workspace/issues/250
