### ISSUE TITLE
[feat] Pickup environment variables from repository

### ISSUE THREAD

**Issue by elvinaspredkelis** [tauri-apps/tauri#3745]
### Describe the problem

Adding multiple environment variables can be a hassle and/or not that portable.

For example, Signing and notarizing the app for macOS requires to set quite a bit of environment variables. Can be done by setting all of it in `.zshrc`, for example, but it doesn't seem like an ideal approach. Especially when working with multiple projects with multiple people.

### Describe the solution you'd like

I'm not sure how feasible it is to do, but it would be amazing to be able to pick up environment variables from the repository (e.g. `.env`). Especially if there will be more available environment variables added to Tauri in the future.

Alongside that, since there's a `TAURI_PRIVATE_KEY`, maybe it'd be possible to make a credentials file that is encoded using that key. In that case, the project would be even cleaner and more portable. 

For the encodable file solution, Rails' credentials could be used for inspiration: https://guides.rubyonrails.org/security.html#custom-credentials

**Comment by lucasfernog** [comment]
I think it's a little bit dangerous for us to implement this. You can load the `.env` file manually in your shell instead.
Note that you should never commit your environment variables.
