### ISSUE TITLE
[feat] how to utilize current angular component with tauri on read/write files on local system?

### ISSUE THREAD

**Issue by aohan237** [tauri-apps/tauri#3759]
### Describe the problem

i use this component for image upload.

https://ng.ant.design/components/upload/en#api

and have config tauri fs  like https://tauri.studio/docs/api/js/modules/fs config said.

but when click to upload files, nothing happens. (but it works fine in browser)

when i check with developer tools, nothing error or tips shows.

how to make this happen?

### Describe the solution you'd like

as above

**Comment by lucasfernog** [comment]
Linux and Windows already works, and macOS was implemented here: https://github.com/tauri-apps/wry/pull/545 so this issue is resolved!
