### ISSUE TITLE
[feat] Pressing `Cmd + Option + i` should open dev tools during development

### ISSUE THREAD

**Issue by schickling** [tauri-apps/tauri#3776]
### Describe the problem

During development I frequently need access to the devtools. This should be made easier via the common browser keyboard shortcut `Cmd + Option + i`.

### Describe the solution you'd like

Pressing `Cmd + Option + i` should open dev tools during development

### Additional context

https://github.com/tauri-apps/tauri/issues/1213

**Comment by schickling** [comment]
@lucasfernog excited to see this being addressed! Does this also include **closing** the dev tools again (i.e. toggling)?

**Comment by nothingismagick** [comment]
https://github.com/tauri-apps/tauri/commit/ab92492418820dd7ec4638b00a8ad38e00c47b34#diff-cf8ee419c6e85fa83601b86b02c9ed9e32de84c9a3b962287bf0aa2255a3a312R5

```
Toggle devtools when `Ctrl + Shift + I` or `Command + Option + I` is pressed.
```

**Comment by lucasfernog** [comment]
Yeah, toggling will work on Linux and macOS (webview2 doesn't have an API to close the devtools yet :( )
