### ISSUE TITLE
[feat] Keybindings For Inspect Element Console.

### ISSUE THREAD

**Issue by Labham-Jain** [tauri-apps/tauri#3788]
### Describe the problem

I'm building an app which has custom `contextmenu` so in order to create it, we need to disable the default browser behaviour. And  as tauri doesn't have keybinding for inspect element it's hard to open it.

### Describe the solution you'd like

Adding support of keybinding for like reload and inspect element options

**Comment by amrbashir** [comment]
You should set up the keybindings yourself and call the [`open_devtools`](https://docs.rs/tauri/1.0.0-rc.4/tauri/window/struct.Window.html#method.open_devtools) method.

You can add another entry in your custom menu that is only available in development and it invokes a tauri command to open the devtools.

Here is the command:
```rs
#[tauri::command]
fn open_devtools(window: Window) {
  window.open_devtools();
}
```

**Comment by lucasfernog** [comment]
I think we should implement this on tauri since it's a super common functionality.

**Comment by lucasfernog** [comment]
But this is duplicate, see #3776
