### ISSUE TITLE
WSL Unable to init server

### ISSUE THREAD

**Issue by google-mac** [tauri-apps/tauri#380]
`yarn tauri dev` fails when trying to start.

**To Reproduce**
1. Follow steps for Linux setup and install Tauri node package globally
2. Also enable Windows loopback (I did this just in case because I'm on WSL 2)
3. Create a new project (I'm using Svelte) and add node package locally
4. Edit `tauri.conf.json`
```
  "build": {
    "distDir": "../public",
    "devPath": "http://127.0.0.1:5000"
  },
```
5. Run `yarn dev` to start up Svelte dev server
5. Run `yarn tauri dev` in a different terminal tab

**Expected behavior**
I expect the Tauri dev environment to start up.

**Platform and Versions:**

OS:  Linux(4.19.84-microsoft-standard) - linux/x64
Node:  13.6.0
NPM:  6.13.4
Yarn:  1.21.1
Rustc:  1.42.0-nightly

**Additional context**
Note that this is my first time trying out Tauri, but as a JS/Rust user I'm very excited!

**Stack Trace**
```
➜  tauri-counter RUST_BACKTRACE=1 yarn tauri dev
yarn run v1.21.1
warning package.json: No license field
$ /home/googlemac/Code/rust/tauri-counter/node_modules/.bin/tauri dev
[tauri]: running dev
 app:spawn Running "cargo run --features dev-server" +0ms

warning: unused manifest key: package.author
   Compiling app v0.1.0 (/home/googlemac/Code/rust/tauri-counter/src-tauri)
   Compiling tauri v0.3.2
    Finished dev [unoptimized + debuginfo] target(s) in 2.30s
     Running `target/debug/app`
Unable to init server: Could not connect: Connection refused
thread 'main' panicked at 'Failed to build webview: Initialization', /home/googlemac/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-0.3.2/src/app.rs:14:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66  
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1428
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1199
  14: core::result::Result<T,E>::expect
             at /rustc/8417d68de5e063426ab6bb7f383df6117d1beeed/src/libcore/result.rs:991
  15: tauri::app::App::run
             at /home/googlemac/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-0.3.2/src/app.rs:14 
  16: app::main
             at src/main.rs:13
  17: std::rt::lang_start::{{closure}}
             at /rustc/8417d68de5e063426ab6bb7f383df6117d1beeed/src/libstd/rt.rs:67
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  21: std::panicking::try
             at src/libstd/panicking.rs:281
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  24: std::rt::lang_start
             at /rustc/8417d68de5e063426ab6bb7f383df6117d1beeed/src/libstd/rt.rs:67
  25: main
  26: __libc_start_main
  27: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

 app:spawn Command "cargo" failed with exit code: 101 +0ms

 app:tauri (template) ⚠️  [FAIL] Cargo CLI has failed +0ms

 app:tauri Shutting down tauri process... +1ms
error Command failed with exit code 1.
```

**Comment by nothingismagick** [comment]
Hi @google-mac - yeah I've seen that before. Maybe you need to use 0.0.0.0 as your localhost

```
Unable to init server: Could not connect: Connection refused
```

**Comment by nothingismagick** [comment]
Also (just mentioning it because it trips people up sometimes):

https://github.com/tauri-apps/tauri/wiki/04.-MS-Windows-Setup

I have never used WSL - but I am totally skeptical to be honest. :)

**Comment by google-mac** [comment]
@nothingismagick I had actually followed the MS build to a degree - since I'm not actually developing on Windows, I did not download the Windows packages. WSL has been really great and I've run into minimal issues. I'm running the latest Ubuntu.

I had tried both suggested localhost replacements, which did not work.

**Comment by nothingismagick** [comment]
Are u sure your devserver is really up? We have to have that started and running first.

**Comment by google-mac** [comment]
Yes - you mean for Svelte? It shows that it is running, and I can interact with the app on `localhost:5000`.

**Comment by nothingismagick** [comment]
so try switching your 127.0.0.1 to localhost:5000 and really wait until the svelte devserver has started before you start tauri

**Comment by google-mac** [comment]
I did wait until it was running and even interactive before starting Tauri. And yes, I tried it with `localhost:5000`.

**Comment by nothingismagick** [comment]
ok this is a bit strange - do you care to jump over to our discord for triage?

https://discord.gg/Z7KXJUp

**Comment by google-mac** [comment]
So I tried the official Svelte example and couldn't get it to work (following the README). It's the same error as above. 

I also tried running `yarn tauri:source:dev` in order to use the tauri code from source and I got a different error: 

```
yarn tauri:source dev
$ node ../../../cli/tauri.js/bin/tauri dev
[tauri]: running dev
internal/modules/cjs/loader.js:976
  throw err;
  ^

Error: Cannot find module 'minimist'
Require stack:
- /home/googlemac/Code/rust/tauri/cli/tauri.js/bin/tauri-dev.js
- /home/googlemac/Code/rust/tauri/cli/tauri.js/bin/tauri.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:973:15)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/googlemac/Code/rust/tauri/cli/tauri.js/bin/tauri-dev.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/googlemac/Code/rust/tauri/cli/tauri.js/bin/tauri-dev.js',
    '/home/googlemac/Code/rust/tauri/cli/tauri.js/bin/tauri.js'
  ]
}
error Command failed with exit code 1.
```

**Comment by lucasfernog** [comment]
Did you install the CLI deps? `cd cli/tauri.js && yarn`

**Comment by google-mac** [comment]
@lucasfernog I had not before, but I did that with no different result.

**Comment by tensor-programming** [comment]
Ill take a look myself, I've been able to get Tauri running on WSL but part of the problem has to do with how the webkit-gtk needs to have a UI.  So you will need to have an XServer running to be able to see the GUI.

**Comment by google-mac** [comment]
@tensor-programming This makes sense - I don't have any interface client attached. I think I've read through a tutorial on getting this set up in the past.

**Comment by tensor-programming** [comment]
Its not all that difficult @google-mac.  You just need to download one of these popular X servers: Xming, Cygwin X, and vcXsrv. I personally recommend vcXsrv.  Then on wsl version 1 you run `export DISPLAY=:0` in the terminal and try to open a graphical based application.  You can get some of those via `sudo apt-get install x11-apps` and run `xeyes` for instance.  On WSL version 2, you need to run a command that is slightly more complex: `export DISPLAY=$(/etc/resolv.conf < awk '/nameserver/ {print $2}'):0` and you need to add -ac to the Xserver as an argument.

**Comment by nothingismagick** [comment]
@Laegel - good tips above from Tensor for the DOCS

**Comment by google-mac** [comment]
@tensor-programming Thanks for the concise yet good details. I think the WSL2 command should be `export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0` instead.

**Comment by google-mac** [comment]
@nothingismagick The line above should be used in the docs instead (the current one is expecting awk to be a filename). I just got everything working great today!
