### ISSUE TITLE
[bug] Hello world app, title bar problem (macOS)

### ISSUE THREAD

**Issue by vtu-dog** [tauri-apps/tauri#3801]
### Describe the bug

Hello,
When I focus a hello world app and mouse over the title bar, the bar expands downwards by a very slight margin and changes in colour. I [recorded](https://github.com/vtu-dog/tauri-bugtest/blob/master/title-bar.mov) the issue using QuickTime. When the window is out of focus, mousing over it does nothing out of the ordinary.

### Reproduction

1. Create a new hello world app with default settings using `yarn create tauri-app`.
2. Run `cargo tauri dev` and focus the window.
3. Move the mouse onto the title bar. It should expand and change in colour. When you move the mouse anywhere else, the bug disappears until you move the mouse back onto the bar.

### Expected behavior

The title bar should neither expand nor change in colour.

### Platform and versions

```shell
Operating System - Mac OS, version 12.3.0 X64

Node.js environment
  Node.js - 17.7.1
  @tauri-apps/cli - 1.0.0-rc.6
  @tauri-apps/api - 1.0.0-rc.2

Global packages
  npm - 8.5.2
  pnpm - 6.11.0
  yarn - 1.22.17

Rust environment
  rustup - 1.24.3
  rustc - 1.59.0
  cargo - 1.59.0
  toolchain - stable-aarch64-apple-darwin

App directory structure
/dist
/src-tauri
/.git

App
  tauri - 1.0.0-rc.4
  tauri-build - 1.0.0-rc.4
  tao - 0.6.4
  wry - 0.13.3
  build-type - bundle
  CSP - unset
  distDir - ../dist
  devPath - ../dist
```

**Comment by probablykasper** [comment]
Uploaded the video:

https://user-images.githubusercontent.com/11315492/162288406-75870144-8775-427f-98a3-0b9a72f31436.mov

Not seeing this bug in my apps on macOS 10.15, so I assume this bug is specific to macOS 11+.

**Comment by lucasfernog** [comment]
Can't believe you noticed this lol good eyes. Opened a PR in `wry`. Thanks for the detailed report!
