### ISSUE TITLE
[feat] Remove items from native context menus that represent browser-specific functionality

### ISSUE THREAD

**Issue by ritsuke** [tauri-apps/tauri#3805]
### Describe the problem

The context menu displays items that represent browser-specific functionality.

For example, on Windows, the context menu has the `Share` item. When clicking this item, a dialog displays with the favicon and title of `index.html`. The link to be shared is `https://tauri.localhost/`

This doesn't appear to be useful.

### Describe the solution you'd like

Though native, custom context menus will be awesome, it would be great to remove items from the menu that represent browser-specific functionality.

Retain sensible defaults like cut/copy/paste and spellcheck. 

### Additional context

Related: https://github.com/tauri-apps/tauri/issues/2918#issuecomment-971800553

**Comment by amrbashir** [comment]
Unfortunately, it isn't possible. However, in the future, we will allow you to make your own native context menu.

**Comment by lokimckay** [comment]
> Unfortunately, it isn't possible. However, in the future, we will allow you to make your own native context menu.

@amrbashir is this functionality being tracked somewhere? I would like to subscribe to it to get a notification when it's added

**Comment by amrbashir** [comment]
There isn't one atm. Feel free to open one.
