### ISSUE TITLE
[bug] Resize window with devtool opened make the screen jump

### ISSUE THREAD

**Issue by Janaka-Steph** [tauri-apps/tauri#3814]
### Describe the bug

It's easier to explain with images.

Here I run the app (in dev or build debug) with devtool opened.
<img width="1179" alt="Screenshot 2022-03-30 at 16 20 06" src="https://user-images.githubusercontent.com/4022128/160871037-0d6b28f7-a1d3-4d0e-9d57-8ead118caee3.png">

Here I resized the window just a bit. The view "jumped" and is locked like this.
<img width="1177" alt="Screenshot 2022-03-30 at 16 20 24" src="https://user-images.githubusercontent.com/4022128/160871011-8fe2fcca-6108-4611-9baa-2aafa1f129c6.png">

### Platform and versions

```shell
▶ cargo tauri info           


Environment
  › OS: Mac OS 12.3.0 X64
  › Node.js: 16.14.2
  › npm: 8.1.4
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.24.3
  › rustc: 1.59.0
  › cargo: 1.59.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.7
  › @tauri-apps/api [NPM]: 1.0.0-rc.3
  › tauri [RUST]: 1.0.0-rc.6,
  › tauri-build [RUST]: 1.0.0-rc.5,
  › tao [RUST]: 0.7.0,
  › wry [RUST]: 0.14.0,

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  › distDir: ../build
  › devPath: http://localhost:3003/
  › framework: React
  › bundler: Webpack

App directory structure
  ├─ tdexd
  ├─ node_modules
  ├─ public
  ├─ scripts
  ├─ .github
  ├─ src-tauri
  ├─ build
  ├─ .git
  ├─ .idea
  └─ src
```

**Comment by amrbashir** [comment]
subscribe to https://github.com/tauri-apps/wry/issues/297 see when it gets fixed.
