### ISSUE TITLE
[feat] Better error message when using the updater on Linux

### ISSUE THREAD

**Issue by corentinguilloteau** [tauri-apps/tauri#3817]
### Describe the problem

When trying to use the updater on Linux, I encountered the error `Unsupported operating system or platform`. The problem was that I ran my application after installing it with the `.deb` package and not directly from the `AppImage`.

I spent some time figuring out where the problem was from because this error message is the same as the error message used if `target_arch` or `target_os` is unsupported.

### Describe the solution you'd like

I think using a different error message for those two cases would be really helpful.

Also, it could be profitable to add a note in the documentation to inform developers that a user on Linux need to run the AppImage if he wants to use the updater.

**Comment by JonasKruckenberg** [comment]
I see this as a documentation issue, not something addressable through code, but yes you are correct we should be more forthcoming about which packaging formats support updating and which do not.

**Comment by corentinguilloteau** [comment]
Wouldn't it also be possible to add a new `Error` [here](https://github.com/tauri-apps/tauri/blob/50d135b20fff1b6997241bdaf60a910811522cee/core/tauri/src/updater/error.rs) and use it [here](https://github.com/tauri-apps/tauri/blob/50d135b20fff1b6997241bdaf60a910811522cee/core/tauri/src/updater/core.rs#L491) instead of the `Error::UnsupportedPlatform` ?

**Comment by FabianLars** [comment]
Ideally the app wouldn't even include the updater code for non appimage bundles, but that would mean that we'd have to build the binary twice :((
