### ISSUE TITLE
How to execute complex shell script？

### ISSUE THREAD

**Issue by mojizo** [tauri-apps/tauri#3821]
I didn't see the doc about how to execute complex shell script like `cd path/to/folder && node scripts/build.js`, I want to use Command JavaScript API to execute it.
Can anyone post examples? I'll be very grateful for any help.

**Comment by JonasKruckenberg** [comment]
Have you tried just executing that command using the API? 
If that doesn't work, a few options come to mind:
1. Simulate `&&` in code. You can just execute the first command, await it's success and then dispatch the second command.
2. Call the shell with the string as an argument. You can call the shell binary passing it the command string as an argument. Depending on the OS, you might need to specify different binaries here.

**Comment by mojizo** [comment]
>

**Comment by mojizo** [comment]
> Have you tried just executing that command using the API? If that doesn't work, a few options come to mind:
> 
> 1. Simulate `&&` in code. You can just execute the first command, await it's success and then dispatch the second command.
> 2. Call the shell with the string as an argument. You can call the shell binary passing it the command string as an argument. Depending on the OS, you might need to specify different binaries here.

Thanks for your reply ^^. I have tried the 1st option:
My shell scope config as follow:
`
    "allowlist": {
      "all": true,
      "shell": {
        "all": true,
        "execute": true,
        "sidecar": true,
        "open": true,
        "scope": [
          {
            "name": "node",
            "cmd": "node",
            "args": ["scripts/build.js"]
          },
          {
            "name": "cd",
            "cmd": "cd",
            "args": ["/path/to/folder/"]
          }
        ]
      }
    }
`
I try to separate the command.
1. `const cmd1 = new Command("cd");`
2. `cmd1.spawn();`
3. `const cmd2 = new Command("node");`
4. `cmd2.spawn();`

It doesn't work. Because `cmd1` change the directory but `cmd2` still base on current folder.

**Comment by FabianLars** [comment]
@mojizo If it's really just about `cd` it would be easier to just set the working dir like so:
```ts
const cmd2 = new Command("node", null, { cwd: '/path/to/folder' });
```
If you need other commands than just `cd` you probably need to execute them as scripts, so something like this i think
```ts
const cmd2 = new Command("sh", ['-c', '"cd /path/to/folder/ && node scripts/build.js"']); // May be easier to have an actual script file to execute here
```
Note that this has to be adapted per OS of course.

**Comment by mojizo** [comment]
> ```ts
> { cwd: '/path/to/folder' }
> ```

Your suggestions work well. 
That blame my lack of knowledge. 
Thanks above guys a lot~
