### ISSUE TITLE
Plugin workflow builds crate twice

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri#3823]
### Describe the bug

The covector config generated by `tauri plugin init` builds the crate twice on publish. Once through `cargo package` and a second time through `cargo publish`.

I guess the intent was to show a summary of the crate/check the status before actually publishing the crate, but with compile times being the way they are this is really suboptimal.
Shall we just remove the `cargo package` command?

### Platform and versions

```shell
N/A
```

**Comment by lucasfernog** [comment]
The main Tauri workflow also uses both commands. @jbolda I believe you wrote that, any reason for it?
