### ISSUE TITLE
[feat] How to listen for web events  when loading a remote url?

### ISSUE THREAD

**Issue by 34205037** [tauri-apps/tauri#3824]
### Describe the problem

How to listen for web events when loading a remote url?

### Describe the solution you'd like

For example, in electronjs:
```
win.webContents.session.webRequest.onBeforeRequest((details, callback) => {
    console.log(details.url)
    if  (details.url.endsWith('.js')) {
        // do something
    }
    
    callback({})
})

win.webContents.on('dom-ready', () => {
// ...
})

// did-start-loading/did-finish-load/...

win.loadURL('https://github.com')
```
I didn't find anything in Tauri doc. Did I miss anything?

**Comment by lucasfernog** [comment]
We do not have this kind of API yet, we've only focused on local apps so far.

**Comment by 34205037** [comment]
@lucasfernog  Thanks for your reply.
Is it possible to include it in the dev plan?
It is useful when implementing some apps, such as monitoring resources and auto creating download tasks.
I hope my English is very good...

**Comment by PuffMeow** [comment]
I meet the same question, I want to create a markdown app. There are some links in the markdown statement. When I click the link, is there any way to open it in the default browser?

**Comment by lucasfernog** [comment]
> I meet the same question, I want to create a markdown app. There are some links in the markdown statement. When I click the link, is there any way to open it in the default browser?

@FacesPass you can set `target="_blank"` in the link and it'll open in the default browser if you have shell > open enabled in the allowlist. Otherwise you can use the [open](https://tauri.app/v1/api/js/modules/shell#open) API directly.

**Comment by lucasfernog** [comment]
Remote URLs aren't in the roadmap for now. If we have more interest from the community we could discuss it for v3+ since v2 main goal is some missing desktop APIs and mobile support.
