### ISSUE TITLE
[feat] intercept window open

### ISSUE THREAD

**Issue by cjdxhjj** [tauri-apps/tauri#3826]
### Describe the problem

i have few site online, it is build on vue, it's package to the tauri is very simply,
but when i open a new window, from a link or window.open method, i found it sometimes open the system browser, then the user session is not managed.

### Describe the solution you'd like

tauri provider the pre open method, to open in the webview2 browser or prevent it. then the window can open custom, for example open in a new tab or open a webview2 browser.

**Comment by JonasKruckenberg** [comment]
Even with a way to intercept these kinds of requests (which is already possible using the isolation pattern) you would not be able to share login sessions with the browser that is opened. This is just down to the fact that both are separate programs, with separate processes, separate contexts and unique file system structures. Sharing a session with the newly opened tab is only possible by putting the auth token in the URL, which is a bad idead for rather obvious reasons.

Edit: If this is not what you originally meant please feel free t o reopen.
