### ISSUE TITLE
[bug] Spawning an async task prevents clean exit

### ISSUE THREAD

**Issue by 0rvar** [tauri-apps/tauri#3835]
### Describe the bug

When a long running async task is spawned with `async_runtime::spawn`, the app cannot be exited with ctrl+c.

### Reproduction

Minimal reproduction: https://github.com/0rvar/tauri-async-issue

### Expected behavior

Spawned async tasks should be aborted when the program receives an interrupt

### Platform and versions

<details><summary>Expand</summary>

```shell
Operating System - Mac OS, version 12.0.1 X64

Node.js environment
  Node.js - 16.14.0
  @tauri-apps/cli - 1.0.0-rc.6
  @tauri-apps/api - 1.0.0-rc.2

Global packages
  npm - 8.3.1
  pnpm - 6.11.0
  yarn - 1.22.17

Rust environment
  rustup - 1.24.3
  rustc - 1.60.0-nightly
  cargo - 1.60.0-nightly
  toolchain - nightly-aarch64-apple-darwin

App directory structure
/native
/node_modules
/public
/src-tauri
/build
/.git
/.vscode
/src

App
  tauri - 1.0.0-rc.6
  tauri-build - 1.0.0-rc.4
  tao - 0.7.0
  wry - 0.14.0
  build-type - bundle
  CSP - unset
  distDir - ../build
  devPath - http://localhost:3333/
  framework - React
```

</details>

**Comment by lucasfernog** [comment]
This is a problem with actix-web, not Tauri, see https://github.com/actix/actix-web/issues/1098#issuecomment-533961494 and https://docs.rs/actix-web/latest/actix_web/struct.HttpServer.html#method.disable_signals

actix-web uses tokio's ctrl_c to handle the signal: https://docs.rs/tokio/latest/tokio/signal/fn.ctrl_c.html
