### ISSUE TITLE
[bug] Global shortcuts are never triggered on Linux

### ISSUE THREAD

**Issue by rscarson** [tauri-apps/tauri#3838]
### Describe the bug

Similar to [Tao issue #307](https://github.com/tauri-apps/tao/issues/307), global shortcuts never trigger on the Linux platform

Perhaps a requirement that isn't specified somewhere?

Tested on 2 fresh installs of Ubuntu 20.04 running on the vmware, and VirtualBox platforms, and also tested through WSL2

### Reproduction

```
let mut gsm = app_handle.global_shortcut_manager();
gsm.register("CmdOrCtrl+1", || {
    println!("here");
});
```

### Expected behavior

Registered handler should be triggered, printing to the console

### Platform and versions

```shell
cargo tauri info

Operating System - Ubuntu, version 20.04 X64

Node.js environment
  Node.js - 17.8.0
  @tauri-apps/cli - 1.0.0-rc.6 (outdated, latest: 1.0.0-rc.7)
  @tauri-apps/api - 1.0.0-rc.1 (outdated, latest: 1.0.0-rc.2)

Global packages
  npm - 8.5.5
  pnpm - Not installed
  yarn - Not installed

Rust environment
  rustup - 1.24.3
  rustc - 1.59.0
  cargo - 1.59.0
  toolchain - stable-x86_64-unknown-linux-gnu 

App directory structure
/node_modules
/src-tauri
/src
/.git
/public
/.vscode

App
  tauri - 1.0.0-rc.4
  tauri-build - 1.0.0-rc.4
  tao - 0.6.4
  wry - 0.13.3
  build-type - bundle
  CSP - unset
  distDir - ../build
  devPath - http://localhost:3000/
  framework - React
```

**Comment by amrbashir** [comment]
Once the upstream issue is resolved in `tao`, it will be automatically available to `tauri`. There is no need to keep this issue open so subscribe to the other issue instead.

**Comment by rscarson** [comment]
Was not aware it had not made it to the RC builds

Thanks - any timeline on it?

**Comment by amrbashir** [comment]
The progress has halted for now but we sure need to fix it before the `tauri` v1 stable release.

**Comment by rscarson** [comment]
Thanks
