### ISSUE TITLE
[bug] (macOS) cargo tauri build produces a malformed Mach-o file

### ISSUE THREAD

**Issue by AOx0** [tauri-apps/tauri#3851]
### Describe the bug

When building using `cargo tauri build` (without `--debug`) the resulting binary does not execute.

When launching from Finder I get the pop-up : 
<img width="372" alt="Screen Shot 2022-04-03 at 3 33 32 p m" src="https://user-images.githubusercontent.com/50227494/161447384-bd1aca2e-c858-4b75-9ac5-94cc31110d56.png">

When launching from the Terminal I get the message:

    zsh: killed

When trying `sudo dtruss ./path/MacOS/Test` I get the error message:

    dtrace: failed to execute /Users/Alejandro/test/src-tauri/target/release/bundle/macos/Test.app/Contents/MacOS/Test: Malformed Mach-o file

Building the application with the `--debug` flag increases size from `~6 MB` to `~32 MB`. The resulting bundled app does work perfectly, tho.

### Reproduction

1. Init a new project : `mkdir test && cd test && cargo tauri init`
2. Build without the `--debug` flag : `cargo tour build`
3. Try open the app with Finder/Terminal

### Platform and versions

```shell
Intel MacBook Air (Retina, 13-inch, 2019), macOS 12.3 

alejandro@Mac test % cargo tauri info

Environment
  › OS: Mac OS 12.3.0 X64
  › Node.js: 17.8.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: 3.1.1
  › rustup: 1.24.3
  › rustc: 1.59.0
  › cargo: 1.59.0
  › Rust toolchain: stable-x86_64-apple-darwin

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.0.0-rc.7(outdated, latest: 1.0.0-rc.8)
  › @tauri-apps/api [NPM]: 1.0.0-rc.3(outdated, latest: 1.0.0-rc.3)
  › tauri [RUST]: 1.0.0-rc.6,
  › tauri-build [RUST]: 1.0.0-rc.5,
  › tao [RUST]: 0.7.0,
  › wry [RUST]: 0.14.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../front
  › devPath: ../front
package.json not found

App directory structure
  ├─ src-tauri
  └─ front
```

### Stack trace

```shell
dtrace: failed to execute /Users/Alejandro/test/src-tauri/target/release/bundle/macos/Test.app/Contents/MacOS/Test: Malformed Mach-o file

dtrace: failed to execute /Users/Alejandro/test/src-tauri/target/release/Test: Malformed Mach-o file
```

### Additional context

Already tried reinstalling `tauri-cli`, re-building from the ground, creating new projects. I hope it's not a just a thing of mine.

**Comment by lucasfernog** [comment]
Hey is this issue still happening? Do you think you could share one of the bundles with us?

**Comment by AOx0** [comment]
Just tried building in release mode today with cargo-tauri 1.0.0-rc.10, tauri-build 1.0.0-rc.8 and tauri 1.0.0-rc.9 and everything works fine! Thanks

**Comment by shivam-jainn** [comment]
Hey this is still happening , what was the solution for this?
