### ISSUE TITLE
Http scope match error

### ISSUE THREAD

**Issue by peterroe** [tauri-apps/tauri#3858]
### Describe the bug

hello, I meet a error because of `glob match`.

example:

```json
"http": {
        "all": true,
        "request": true,
        "scope": ["https://**","http://**"]
},
```
I found that the above can only match the first-level route，such as `https://xxx.xxx/xxx` (normal)

it can't match the second-level route or more, such as `https://xxx.xxx/xxx/xxx` or `https://xxx.xxx/xxx/xxx/xxx`(timeout)

such as: 

```ts
import { fetch } from '@tauri-apps/api/http';

// or https://rsshub.app/allpoetry/newest
// or https://feedx.net/rss/shanghaishuping.xml
// As long as it a  multilevel route, it can be sent unsuccessfully.
fetch('https://feedx.net/rss/huanqiukexue.xml', { //NetWork Error: Io Error
  responseType: 2,
  method: 'GET',
}).then(value => {
  console.log(value);
}).catch(err => {
  console.log(err);
});

//or https://www.gcores.com/rss
//or https://www.designernews.co/?format=rss
//or https://www.gcores.com/rss
// As long as it is a one-level route, it can be sent successfully
fetch('https://antfu.me/feed.xml', {  //effective
  responseType: 2,
  method: 'GET',
}).then(value => {
  console.log(value);
}).catch(err => {
  console.log(err);
});
```

### Platform and versions

```shell
Operating System - Windows, version 10.0.19044 X64
Webview2 - 100.0.1185.29
Visual Studio Build Tools:
   - Visual Studio 15 ���ɹ��� 2017
   - Visual Studio Community 2022
   - Visual Studio Community 2017

Node.js environment
  Node.js - 16.13.1
  @tauri-apps/cli - 1.0.0-rc.4
  @tauri-apps/api - 1.0.0-rc.2

Global packages
  npm - 8.5.5
  pnpm - 6.32.3
  yarn - 1.22.17

Rust environment
  rustup - 1.24.3
  rustc - 1.57.0
  cargo - 1.57.0
  toolchain - stable-x86_64-pc-windows-msvc 

App directory structure
/.git
/.github
/dist
/img
/node_modules
/public
/release
/src
/src-tauri

App
  tauri - 1.0.0-rc.6
  tauri-build - 1.0.0-rc.5
  tao - 0.7.0
  wry - 0.14.0
  build-type - bundle
  CSP - unset
  distDir - Set automatically by Vue CLI plugin
  devPath - Set automatically by Vue CLI plugin
  framework - Vue.js (Vue CLI)
  bundler - Webpack
```

**Comment by FabianLars** [comment]
Hello. First of all please don't answer questions that are marked with "**required**" as "no need". In this case it may would've have shown that your project uses an older tauri version than required for the PR you commented on (for reference: https://github.com/peterroe/Rss-Reader/blob/master/src-tauri/Cargo.toml#L20).
So please try upgrading your dependencies (also run `cargo update` in your src-tauri folder) and test again.
Furthermore please test other URLs or provide us some example URLs here because i can't reproduce this issue.

**Comment by peterroe** [comment]
My bad！I had modified the issue contents.

**Comment by peterroe** [comment]
Can you help me? because of this problem, I can's develop my application continue :(

**Comment by FabianLars** [comment]
I couldn't reproduce this issue myself (it works fine for me). I can take another look in the evening, if nobody else beats me to it.

Edit: I didn't test it with your urls yet tho. Do they work fine in a browser? Because a _timout_ doesn't sound like a scope error.

**Comment by peterroe** [comment]
I found that I only have this problem when requesting XML files for multi-level routing
The strangest thing is that the first-level routing is OK, but the multi-level routing is not.

**Comment by nothingismagick** [comment]
Please try updating rust with `rustup` and install the latest `@tauri-apps/api` and `@tauri-apps/cli` versions

**Comment by peterroe** [comment]
I had upgrade my `rust env`, but I can't solve problem, too.
and find a ` warning` during `fetch xml file`:

```shell
[TAURI] Couldn't find callback id 4213420197 in window. This happens when the app is reloaded while Rust is running an asynchronous operation
```

**Comment by nothingismagick** [comment]
Did you update the node modules? Please share the results of `tauri info`

**Comment by peterroe** [comment]
Yes, I‘ve rebuild node_modules and this is my tauri message:

```shell
Operating System - Windows, version 10.0.19044 X64
Webview2 - 100.0.1185.29
Visual Studio Build Tools:
   - Visual Studio 15 ���ɹ��� 2017
   - Visual Studio Community 2022
   - Visual Studio Community 2017

Node.js environment
  Node.js - 16.13.1
  @tauri-apps/cli - 1.0.0-rc.4
  @tauri-apps/api - 1.0.0-rc.2

Global packages
  npm - 8.5.5
  pnpm - 6.32.3
  yarn - 1.22.17

Rust environment
  rustup - 1.24.3
  rustc - 1.60.0
  cargo - 1.60.0
  toolchain - stable-x86_64-pc-windows-msvc 

App directory structure
/.git
/.github
/dist
/img
/node_modules
/public
/release
/src
/src-tauri

App
  tauri - 1.0.0-rc.6
  tauri-build - 1.0.0-rc.5
  tao - 0.7.0
  wry - 0.14.0
  build-type - bundle
  CSP - unset
  distDir - Set automatically by Vue CLI plugin
  devPath - Set automatically by Vue CLI plugin
  framework - Vue.js (Vue CLI)
  bundler - Webpack
```

**Comment by peterroe** [comment]
Even if I restart to create a new tauri project, it still has that problem, too. What a pity to can't continue... :(
I'll try again when I get a chance to switch to another computer😳，Thanks your help again.

**Comment by lucasfernog** [comment]
I cannot reproduce this issue.
I see you have this comment in your code: `//NetWork Error: Io Error`. If what you saw was a network error, this error is not related to the scope; when the URL is rejected by the configured scope, you'll get a different error message (`url not allowed on the configured scope: ${URL}`).

If you still face this issue, please give me an app to reproduce it.
