### ISSUE TITLE
[feat] Auto-detect appindicator library during runtime

### ISSUE THREAD

**Issue by wusyong** [tauri-apps/tauri#3859]
### Describe the problem

Right now there's two libraries being used for system tray on Linux: libappindicator and libayatana-appindicator. ayatana is former's fork since the old one is unmaintained. This becomes an issue because different distros might use different one. I would say the ratio is around 50:50.
Decide one during compile time means the other half won't work.

### Describe the solution you'd like

Add a feature or default to auto detect the library. We can use pkg_config crate to probe if the library is exist on the end user device.

**Comment by peterroe** [comment]
Hello, We need more information about your system, Maybe you can run `npm run tauri info ` or `cargo tauri info` to get it.
