### ISSUE TITLE
[bug] data-tauri-drag-region attribute cannot work in pure HTML page

### ISSUE THREAD

**Issue by AaronW-BE** [tauri-apps/tauri#3867]
### Describe the bug

I used `data-tauri-drag-region`  in a normal html splashscreen page, it doesn't work as other react rendered page well 

### Platform and versions

```shell
* windows 11
* "@tauri-apps/cli": "^1.0.0-rc.8",
* "tauri": "1.0.0-rc.6"
```

**Comment by amrbashir** [comment]
Please include the full `tauri info` output and a minimal reproduction repo or at least steps to produce.

Splash windows are not different than any other windows. Just make sure that you have `tauri > allowlist > window > startDragging` enabled in your `tauri.conf.json`

**Comment by AaronW-BE** [comment]
> Please include the full `tauri info` output and a minimal reproduction repo or at least steps to produce.
> 
> Splash windows are not different than any other windows. Just make sure that you have `tauri > allowlist > window > startDragging` enabled in your `tauri.conf.json`

Thanks for your answer, its a mistake, I used an absoulte path on the disk for splashscreen file path, now I drop the `splashscreen.html` file to public dir in react project, it works well! 
Thanks agian, hahaha
