### ISSUE TITLE
[bug] TypeError: undefined is not an object (evaluating 'window.rpc.notify')

### ISSUE THREAD

**Issue by Tixwell** [tauri-apps/tauri#3869]
### Describe the bug

I'm trying to run a command like this : https://tauri.studio/docs/guides/command/

But I face this error:

<img width="1399" alt="Capture d’écran 2022-04-07 à 14 36 32" src="https://user-images.githubusercontent.com/59584617/162200030-0f1c7c26-8dcc-425e-8ae2-7d1ec48bfe57.png">
 

```
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'window.rpc.notify')
```

### Platform and versions

```shell
Environment
  › OS: Mac OS 12.2.1 X64
  › Node.js: 17.6.0
  › npm: 8.5.1
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.24.3
  › rustc: 1.58.1
  › cargo: 1.58.0
  › Rust toolchain: stable-x86_64-apple-darwin 


Im using : tauri = { version = "1.0.0-rc.6", features = ["api-all"] }
```

**Comment by Tixwell** [comment]
@azerpas

**Comment by FabianLars** [comment]
Please include the _whole_ output of `tauri info`...
This looks like an outdated `@tauri-apps/api` package at first glance.

**Comment by Tixwell** [comment]
> Please include the _whole_ output of `tauri info`... This looks like an outdated `@tauri-apps/api` package at first glance.

Hey here is the tauri info:

Environment
  › OS: Mac OS 12.2.1 X64
  › Node.js: 17.6.0
  › npm: 8.5.1
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.24.3
  › rustc: 1.58.1
  › cargo: 1.58.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.7
  › @tauri-apps/api [NPM]: 1.0.0-beta.8
  › tauri [RUST]: 1.0.0-rc.6,
  › tauri-build [RUST]: 1.0.0-rc.5,
  › tao [RUST]: 0.7.0,
  › wry [RUST]: 0.14.0,

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ node_modules
  ├─ public
  ├─ .github
  ├─ src-tauri
  ├─ build
  ├─ .git
  ├─ .idea
  └─ src
  
  Thanks for helping me :)

**Comment by nothingismagick** [comment]
> › @tauri-apps/api [NPM]: 1.0.0-beta.8

Is outdated.

**Comment by Tixwell** [comment]
> > › @tauri-apps/api [NPM]: 1.0.0-beta.8
> 
> Is outdated.

I just updated it but the error is still there.

**Comment by nothingismagick** [comment]
did you update the acceptlist?

**Comment by FabianLars** [comment]
Honestly, if you updated the package, you can't get that exact error, because the code it comes from doesn't exist anymore.

So make sure your api npm package is at rc.3 (also check the lockfile and "tauri info"
