### ISSUE TITLE
not allowed by Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by meanbeanmachine** [tauri-apps/tauri#3874]
### Describe the bug

 I am experiencing the same issue as #2965.  However, that issue has been marked as closed with a commit.

When attempting to load an image from an asset, I receive the CORS error:

![cors](https://user-images.githubusercontent.com/29932473/162462046-189b4de4-1be6-41fc-8dfc-18d8c3f70e09.jpg)

The path and asset seem to be OK, because you can open the image by clicking the link in the above console error.

I am using PhaserJS, but I have also tried PixiJS with the same result.

I made a barebones Phaser/Webpack/Tauri repo [here.](https://github.com/meanbeanmachine/phaser-tauri-test)

I am using cli 1.0.0-rc.8 despite tauri info displaying 1.0.0-rc.7.
Oddly, tauri info even says my api is outdated although 1.0.0-rc.3 is listed as installed.

### Reproduction

1. Download and install package
2. npm run tauri dev
3. Image is broken and doesn't load
4. Open console to see error
5. Open asset link to see it load successfully

### Expected behavior

Asset to load properly

### Platform and versions

```shell
Environment
  › OS: Pop!_OS 21.10 X64
  › Node.js: 16.13.2
  › npm: 8.5.2
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.7(outdated, latest: 1.0.0-rc.8)
  › @tauri-apps/api [NPM]: 1.0.0-rc.3(outdated, latest: 1.0.0-rc.3)
  › tauri [RUST]: 1.0.0-rc.6,
  › tauri-build [RUST]: 1.0.0-rc.5,
  › tao [RUST]: 0.7.0,
  › wry [RUST]: 0.14.0,

App
  › build-type: bundle
  › CSP: default-src 'self'; img-src 'self' asset: https://asset.localhost; media-src 'self' asset: https://asset.localhost
  › distDir: ../dist
  › devPath: http://localhost:8080/
  › bundler: Webpack

App directory structure
  ├─ src
  ├─ .git
  ├─ static
  ├─ src-tauri
  ├─ node_modules
  └─ types
```

**Comment by probablykasper** [comment]
Have you tried troubleshooting the CSP? This doesn't seem like a bug

**Comment by meanbeanmachine** [comment]
My CSP is posted; I have asset listed for img-src.  I've also tried csp as "" which I assume is wide open.  This was a bug in #2965 that seems to be back (CORS issue with asset protocol).

**Comment by probablykasper** [comment]
I'm not sure if "" is the least restrictive

**Comment by lucasfernog** [comment]
Unfortunately this is blocked by https://github.com/tauri-apps/wry/issues/422 :( we can't set the CORS header in Linux. You can use the asset in img and video tags though.

Seems like you're trying to read a resource, maybe use the FS API instead (though it'll be slower :( nothing we can do here until webkit2gtk 2.36 lands in most distros).
