### ISSUE TITLE
[feat] Add chrome devtools support

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#3876]
### Describe the problem

Safari devtools is far behind chrome's imo.
<img width="912" alt="Screen Shot 2022-04-09 at 1 18 08 PM" src="https://user-images.githubusercontent.com/91611516/162561879-8e1734b7-31be-4f53-a507-caa3956a14a7.png">

### Describe the solution you'd like

Is it possible to use chrome's devtools instead?

**Comment by pickfire** [comment]
I wish there is firefox devtools.

**Comment by FabianLars** [comment]
@pickfire Well i wish for the same, but it's simply not possible 😅

Oh and to be clear, we have no control over the devtools in general, they belong to the webview itself 🤷

**Comment by pickfire** [comment]
IIRC they are all web apps.

Falkon is using qtwebkit but it uses firefox devtools by default instead of webkit or blink devtools, which I think maybe could be possible.

**Comment by FabianLars** [comment]
Falkon's devtools are the default chromium ones (which makes sense since qtwebengine is based on chromium):

![grafik](https://user-images.githubusercontent.com/30730186/177211913-dc2f0013-43e9-45bc-9c69-49d86c852f51.png)

**Comment by nothingismagick** [comment]
Maybe there's a way to hook into them though... with some kind of websocket relay application. Vue devtools offers (use to offer?) an electron app where you forwarded the devtool data... Maybe this is worth reopenening
