### ISSUE TITLE
[bug] App crashes on Ubuntu due to grayscale PNG icon

### ISSUE THREAD

**Issue by nazar-pc** [tauri-apps/tauri#3877]
### Describe the bug

We have an app built with Tauri and we're using custom icons. Unexpected error happened when we updated those icons, app on Ubuntu (not on macOS or Windows) started crashing like this:
```
thread 'main' panicked at 'data.len() must fit the width, height, and row_stride', /home/nazar-pc/.cargo/registry/src/github.com-1ecc6299db9ec823/gdk-pixbuf-0.15.10/src/pixbuf.rs:52:13
```

I traced it to PNG icon 32x32.png being grayscale instead of sRGB.

### Reproduction

1. replace `src/icons/32x32.png` with grayscale PNG icon
2. build an app
3. run
4. observe panic

### Expected behavior

Greyscale images are perfectly valid and should be supported

### Platform and versions

```shell
Operating System - Ubuntu, version 21.10 X64

Node.js environment
  Node.js - 16.14.2
  @tauri-apps/cli - 1.0.0-rc.6
  @tauri-apps/api - 1.0.0-rc.2

Global packages
  npm - 7.24.2
  pnpm - Not installed
  yarn - 1.22.4

Rust environment
  rustup - 1.24.3
  rustc - 1.59.0
  cargo - 1.59.0
  toolchain - stable-x86_64-unknown-linux-gnu 

App directory structure
/.git
/.github
/.vscode
/public
/src-pwa
/src-tauri
/src
/.idea
/node_modules
/docs
/.quasar
/dist

App
  tauri - 1.0.0-rc.4
  tauri-build - 1.0.0-rc.4
  tao - 0.6.4
  wry - 0.13.3
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist/pwa
  devPath - http://localhost:8080/
  framework - Vue.js (Quasar)
  bundler - Webpack
```

### Additional context

Unfortunate thing that broken icon was generated by tauricon. Attaching example of good and bad icon examples.

Discovered in https://github.com/subspace/subspace-desktop/issues/149 if you're ready to build a huge project just to test this.

![bad-32x32](https://user-images.githubusercontent.com/928965/162585260-680ff083-cc8d-4044-a08f-7065e1c8a753.png)
![good-32x32](https://user-images.githubusercontent.com/928965/162585262-d008b7d3-6f5a-4d1f-9ddb-d04b32390fed.png)

**Comment by lucasfernog** [comment]
I've opened https://github.com/tauri-apps/tauricon/pull/33 to fix this issue.

**Comment by lucasfernog** [comment]
Fix has been merged. tauricon will be released soon.
