### ISSUE TITLE
[feat] Add window.is_minimized()

### ISSUE THREAD

**Issue by sprout2000** [tauri-apps/tauri#3878]
### Describe the problem

Since macOS always displays a menu when an application is active, selecting the minimize menu when the window is already minimized will always cause a panic.

### Describe the solution you'd like

I want to cancel some menu events (e.g. [`set_fullscreen()`](https://docs.rs/tauri/1.0.0-rc.6/tauri/window/struct.Window.html#method.set_fullscreen)) if the window is minimized.

**Comment by amrbashir** [comment]
tauri-apps/tao#257
