### ISSUE TITLE
[bug] Backend server fails to start on Windows, but only on production builds

### ISSUE THREAD

**Issue by rscarson** [tauri-apps/tauri#3885]
### Describe the bug

On Windows, backend fails to start, only showing 'tauri.localhost refused to connect.' in the main window.

Building and then running the backend service in production mode using `serve -s build` works fine in the browser

`cargo tauri dev` works fine as well. But `cargo tauri build` results in a version that does not work, with no way to discover the error causing the issue.

This issue began suddenly after an update to react-router-dom from 5.3.0 to 6.3.0 - I am unsure why it does not work in production when run by Tauri

### Reproduction

Build with `cargo tauri build`, then start the resulting executable

Something with the backend npm service is causing this but I have no way to find out what or how

### Platform and versions

```shell
Operating System - Windows, version 10.0.19042 X64
Webview2 - 100.0.1185.36
Visual Studio Build Tools:
   - Visual Studio Community 2022
   - Visual Studio Enterprise 2019

Node.js environment
  Node.js - 16.13.0
  @tauri-apps/cli - 1.0.0-rc.5 (outdated, latest: 1.0.0-rc.8)
  @tauri-apps/api - 1.0.0-rc.3

Global packages
  npm - 8.1.0
  pnpm - Not installed
  yarn - Not installed

Rust environment
  rustup - 1.24.3
  rustc - 1.59.0
  cargo - 1.59.0
  toolchain - stable-x86_64-pc-windows-msvc

App directory structure
/.git
/.github
/.vscode
/build
/node_modules
/public
/src
/src-tauri
/tmp

App
  tauri - 1.0.0-rc.4
  tauri-build - 1.0.0-rc.5
  tao - 0.6.4
  wry - 0.13.3
  build-type - bundle
  CSP - unset
  distDir - ../build
  devPath - http://localhost:3000/
  framework - React
```

**Comment by CEbbinghaus** [comment]
How was this resolved?

**Comment by rscarson** [comment]
It wasn't - I came back to it sometime later and updated tauri, and it worked
