### ISSUE TITLE
[bug] Build on Archlinux

### ISSUE THREAD

**Issue by tcastelly** [tauri-apps/tauri#3894]
### Describe the bug

Hello,

I have difficulties to build a Tauri application on Archlinux.

Here the build works but I can't launch the application
![image](https://user-images.githubusercontent.com/37597737/163137161-d1dd5720-ff60-4d97-81c3-339da90fd36b.png)

I guessed [webkit2gtk](https://archlinux.org/packages/extra/x86_64/webkit2gtk/) has to be updated. But the [last version](https://archlinux.org/packages/extra/x86_64/webkit2gtk-4.1/) seams to not be compatible either. 

The build is broken because webkit2gtk-4.1 is used instead of webkit2gtk-4.0.
```
/usr/bin/ld: cannot find -lwebkit2gtk-4.0: No such file or directory
/usr/bin/ld: cannot find -ljavascriptcoregtk-4.0: No such file or directory
/usr/bin/ld: cannot find -ljavascriptcoregtk-4.0: No such file or directory
collect2: error: ld returned 1 exit status
```

I don't know if it's a bug or a mismatch of my installed dependencies.

### Reproduction

1. Checkout https://github.com/tcastelly/vue-tauri-vite
2. > npm run tauri:build
3. > sudo dpkg -i src-tauri/target/release/bundle/deb/vite-vue_0.1.0_amd64.deb

### Platform and versions

```shell
##  npm run tauri info

Environment
  › OS: Arch Linux Unknown X64
  › Node.js: 16.14.0
  › npm: 8.3.1
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.24.3
  › rustc: 1.59.0
  › cargo: 1.59.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.7(outdated, latest: 1.0.0-rc.8)
  › @tauri-apps/api [NPM]: 1.0.0-rc.3(outdated, latest: 1.0.0-rc.3)
  › tauri [RUST]: 1.0.0-rc.6,
  › tauri-build [RUST]: 1.0.0-rc.5,
  › tao [RUST]: 0.7.0,
  › wry [RUST]: 0.14.0,

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  › distDir: ../dist
  › devPath: http://localhost:3222/
  › framework: Vue.js (Vue CLI)
  › bundler: Webpack

App directory structure
  ├─ .git
  ├─ src-tauri
  ├─ .github
  ├─ src-go
  ├─ public
  ├─ src-wasm
  ├─ dist
  ├─ node_modules
```

### Additional context
I can launch in dev mode

> npm run tauri:dev

**Comment by FabianLars** [comment]
The _Build_ was successful, what's failing here is the installation of the .deb file, which makes sense because it's a package format for debian-based distros (debian, ubuntu, etc). You can't install .deb files like that on arch & arch derivates.

**Comment by tcastelly** [comment]
Thank you for this quick answer!
Usually I can install my Tauri `.deb` files with the `dpkg` command. But even if I try to launch the built binary available in the target:
```
ls ./src-tauri/target/release/vite-vue
```

It's not working, I've a blank application.

I'm just wondering how can I launch my application :), btw `npm run tauri:dev` works.

**Comment by tcastelly** [comment]
My bad, I tried with a fresh new application and it works. I guess there is something else not linked to tauri. Sorry about that.

edit:
iIt was linked to policy security during wasm loading. Only in the release build: https://github.com/tauri-apps/tauri/issues/3897
