### ISSUE TITLE
Is there a way to create and parse desktop shortcuts

### ISSUE THREAD

**Issue by maoly1012** [tauri-apps/tauri#3895]
### Describe the problem

Is there a way to create and parse desktop shortcuts

### Describe the solution you'd like

create and parse desktop shortcuts

**Comment by amrbashir** [comment]
I assume you mean Windows desktop shortcuts? In this case, you need to use win32 api using `windows-rs` crate or `winapi` crate. There is also some crates made specially for manipulating them too like [`parselnk`](https://crates.io/crates/parselnk) or [`lnk`](https://crates.io/crates/lnk) crate.
