### ISSUE TITLE
[feat] Able to set request headers for tauri downloader

### ISSUE THREAD

**Issue by ghostdevv** [tauri-apps/tauri#3896]
### Describe the problem

Currently I am using [this cloudflare worker](https://github.com/KilleenCode/tauri-update-cloudflare) to do the uploader endpoint, and it works perfectly. However tauri won't be able to actually download the files as they are on a private github repo

### Describe the solution you'd like

Be able to provide custom headers into the tauri uploader config

### Alternatives considered

Adding a proxy on that cloudflare worker

**Comment by ghostdevv** [comment]
Amazing thank you sm @lucasfernog :sparkles:

Is there any documentation on how to use this?

**Comment by lucasfernog** [comment]
@ghostdevv add this to your Cargo.toml:

```
[patch.crates-io]
tauri = { git = "https://github.com/tauri-apps/tauri" }
tauri-build = { git = "https://github.com/tauri-apps/tauri" }
```

You'll need to remove `useBootstrapper` field from your tauri.conf.json as the next release will remove that.

If you're using the Tauri CLI, you need to either build it from source or use Cargo directly.

- Using the Rust CLI it from source

```sh
cargo install --git https://github.com/tauri-apps/tauri tauri-cli

cargo tauri dev
cargo tauri build
```

- Using the Node.js CLI from source
```sh
git clone https://github.com/tauri-apps/tauri
cd tauri/tooling/cli/node
yarn
yarn build

node /path/to/tauri/tooling/cli/node/tauri.js dev
node /path/to/tauri/tooling/cli/node/tauri.js build
```

- Using Cargo directly

```
cd src-tauri

cargo run --no-default-features # instead of tauri dev
cargo build # instead of tauri build - won't bundle your app though
```

If you're using the Tauri API, you might need to use the next version.

```
git clone https://github.com/tauri-apps/tauri
cd tauri/tooling/api
yarn
yarn build
```

- Linking using yarn link:

```
cd dist
yarn link
cd /path/to/your/project
yarn link @tauri-apps/api
```


- Alternatively, you can change your package.json to use the folder as a dependency:

```json
{
  "dependencies": {
    "@tauri-apps/api": "/path/to/tauri/tooling/api/dist"
  }
}
```

**Comment by ghostdevv** [comment]
Awesome, but how do I use this new feature? :thinking:

**Comment by lucasfernog** [comment]
You'll need to manually run the updater:

```rust
fn main() {
  tauri::Builder::default().setup(|app| {
    let handle = app.handle();
    tauri::async_runtime::spawn(async move {
      match handle
        .updater()
        .header("your-header", "value")
        .unwrap()
        .check()
        .await
      {
        Ok(update) => {
          update.download_and_install().await; // TODO: handle possible error
        }
        Err(e) => {
          println!("ERROR: {}", e);
        }
      }
    });
    Ok(())
  });
}
```
