### ISSUE TITLE
[bug] impossible anymore to load wasm in release build

### ISSUE THREAD

**Issue by tcastelly** [tauri-apps/tauri#3897]
### Describe the bug

Hello,

I'm not sure it's a Tauri issue, will see ...
I'm playing with Tauri and wasm, I noticed now I can't anymore load wasm file in the build release.

I noticed a "security policy" that why I thought maybe it's linked

### Reproduction

1. checkout https://github.com/tcastelly/vue-tauri-vite
2. allow devtool by adding these lines to the Carto.toml
3. npm run tauri build --debug

### Platform and versions

```shell
› OS: Arch Linux Unknown X64
  › Node.js: 16.14.0
  › npm: 8.3.1
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.24.3
  › rustc: 1.59.0
  › cargo: 1.59.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.7(outdated, latest: 1.0.0-rc.8)
  › @tauri-apps/api [NPM]: 1.0.0-rc.3(outdated, latest: 1.0.0-rc.3)
  › tauri [RUST]: 1.0.0-rc.6,
  › tauri-build [RUST]: 1.0.0-rc.5,
  › tao [RUST]: 0.7.0,
  › wry [RUST]: 0.14.0,

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  › distDir: ../dist
  › devPath: http://localhost:3222/
  › framework: Vue.js (Vue CLI)
  › bundler: Webpack

App directory structure
  ├─ .git
  ├─ src-tauri
  ├─ .github
  ├─ src-go
  ├─ public
  ├─ src-wasm
  ├─ dist
  ├─ node_modules
  ├─ .rsw
  ├─ .idea
  └─ src
```

### Stack trace
```
Unhandled Promise Rejection: CompileError: Refused to create a WebAssembly object because 'unsafe-eval' or 'wasm-unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'sel...
```

### Additional context

- The development mode still works
- If I build and launch only the client part it works too (`npm run build && ./node_modules/.bin/vite preview`)

**Comment by nothingismagick** [comment]
add the following to your CSP in the `tauri.conf.json`
```
script-src 'wasm-unsafe-eval'
```

**Comment by nothingismagick** [comment]
Didn't mean to close that quickly, sorry

**Comment by tcastelly** [comment]
Thank you so much! Yes it works.

**Comment by ystyle** [comment]
It is recommended to add this to the document

**Comment by nothingismagick** [comment]
We probably should! care to make a PR to the docs?

**Comment by chenming0v0** [comment]
我也建议因为 You’re not alone in this
