### ISSUE TITLE
[feat] Custom userAgent

### ISSUE THREAD

**Issue by sukechris** [tauri-apps/tauri#3904]
### Describe the problem

Hi, Thank you for your great work! I encountered a problem, inside some JavaScript library, they use `navigator.userAgent` to detect device, like this:
```javascript
// "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"
/Version\/[\d\.]+.*Safari/.test(navigator.userAgent)
```
Howerver, `navigator.userAgent` in Tauri webkit, like this:
```javascript
// navigator.userAgent
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)"
```
The expected device is not matched by `navigator.userAgent`.

### Describe the solution you'd like

I didn't find the relevant documentation about how to custom userAgent, Tauri is supported?

**Comment by amrbashir** [comment]
This is supported in `wry`, we just need to expose it in `tauri`.

**Comment by sukechris** [comment]
@amrbashir Thank you for your answer

**Comment by emhagman** [comment]
Hi! I took a crack at this for Hacktoberfest here https://github.com/tauri-apps/tauri/pull/5317

Let me know if there is anything else to do here! This is my first "major" Rust contribution.
