### ISSUE TITLE
[feat] titlebar work's like browser tab.

### ISSUE THREAD

**Issue by cqh963852** [tauri-apps/tauri#3906]
### Describe the problem

I want develop a editor, that has multiple window. Like visual studio.
For now I have a library That I can popout window by click a button.
But If Drag a tab out of window can be support, That would be perfect.

### Describe the solution you'd like

While drag a html element. I can change the cursor.
For now, While dragging in browser, the cursor can't be change. I don't know If tauri can support it?

### Alternatives considered

Support a special props like `data-tauri-drag-region`, So that drag cursor can be customize.

### Additional context

IDE has this behavior：visual studio，unreal engine4.

My library online example : https://codesandbox.io/s/grape-layout-example-irh1p5

**Comment by amrbashir** [comment]
I don't quite understand what you want actually. Do you want to drag a tab from one window to another window? Do you want to change the cursor icon while dragging?

**Comment by lucasfernog** [comment]
I think he wants to create a new window while dragging a tab (like the browser does) and move that tab contents to that window.

**Comment by cqh963852** [comment]
> I don't quite understand what you want actually. Do you want to drag a tab from one window to another window? Do you want to change the cursor icon while dragging?

I have use browser drag drop API implementation drag window from one to another.
But while Drag a tab out of a window, the cursor will be disable drop icon.


> I think he wants to create a new window while dragging a tab (like the browser does) and move that tab contents to that window.

I wang drag a tab like a browser.

![a08ae8cf3f43bbedaafd4060598c207](https://user-images.githubusercontent.com/17702287/163696686-75ed56ce-2aaa-49ac-b31a-f66eb9777a87.jpg)

![dff47dce61112f975a30963126e8036](https://user-images.githubusercontent.com/17702287/163696691-84c0484d-cd8c-4e6e-b533-0c18630c9b97.jpg)

I haven't adapted tauri window yet.

I want find a solution of change drag cursor first.

**Comment by amrbashir** [comment]
> I haven't adapted tauri window yet.

Then please open issues only if you're using tauri.

> I want find a solution of change drag cursor first.

We can provide a `window.set_cursor_icon` method but you should probably look into [css cursors](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor) instead.

**Comment by cqh963852** [comment]
> > I haven't adapted tauri window yet.
> 
> Then please open issues only if you're using tauri.
> 
> > I want find a solution of change drag cursor first.
> 
> We can provide a `window.set_cursor_icon` method but you should probably look into [css cursors](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor) instead.

sadlly, the cursor can't be change while dragging in browser. While drag out of a webView, It always show disable icon.

I am find a platform that can change the cursor while dragging.

And I found tauri can add a flag `data-tauri-drag-region` to titlebar.

Can I change cursor with add a flag `data-tauri-drag-region` while dragging some thing.

**Comment by cqh963852** [comment]
> > I haven't adapted tauri window yet.
> 
> Then please open issues only if you're using tauri.

I am using tauri. Just not adapted tauri's webWindow

An online example would better illustrate what I'm doing.

**Comment by moom-en** [comment]
Hello, how to solve this problem finally?

**Comment by cqh963852** [comment]
> Hello, how to solve this problem finally?

You can try this solution

> We can provide a window.set_cursor_icon method but you should probably look into [css cursors](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor) instead.

**Comment by moom-en** [comment]
> > Hello, how to solve this problem finally?
> 
> You can try this solution
> 
> > We can provide a window.set_cursor_icon method but you should probably look into [css cursors](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor) instead.

Thank you. I also develop multiple windows, but I don't know how to manage each window through tabs. It looks like Google Chrome
