### ISSUE TITLE
[bug] webview content disappears when resizing window with devtools open

### ISSUE THREAD

**Issue by ottosson** [tauri-apps/tauri#3914]
### Describe the bug

When I have an application with any content and open the devtools, then resize the window, the content will be shifted upwards out of the view. Never to be able to scroll it in to view again until I restart the application:

![disappearing content](https://user-images.githubusercontent.com/3355320/163880286-da413fc2-46ce-4d0f-89ca-6e1a3c3119ad.gif)

### Reproduction

start application with any content
open devtools
resize window

### Expected behavior

The content should not disappear upwards

### Platform and versions

```shell
Environment
  › OS: Mac OS 12.3.1 X64
  › Node.js: 15.11.0
  › npm: 7.6.0
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.24.3
  › rustc: 1.59.0
  › cargo: 1.59.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.7(outdated, latest: 1.0.0-rc.8)
  › @tauri-apps/api [NPM]: 1.0.0-rc.3(outdated, latest: 1.0.0-rc.3)
  › tauri [RUST]: 1.0.0-rc.6,
  › tauri-build [RUST]: 1.0.0-rc.5,
  › tao [RUST]: 0.7.0,
  › wry [RUST]: 0.14.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ Res
  ├─ dist
  ├─ node_modules
  ├─ src-tauri
  └─ src
```

**Comment by lucasfernog** [comment]
Related to https://github.com/tauri-apps/wry/issues/297 looks like we know how to fix it.

**Comment by ottosson** [comment]
Awesome! I close this since it's already a known issue
