### ISSUE TITLE
[bug] when i use command, then WebKitWebProcess memory leak.

### ISSUE THREAD

**Issue by zzyandzzy** [tauri-apps/tauri#3921]
### Describe the bug

test commamd code:
```rust
#[tauri::command]
pub fn test_mem_command() -> Result<Vec<u8>, String> {
    debug!("test_mem_command");
    let v = vec![0xff; 1024 * 1024];
    Ok(v)
}
```

js code:
```js
setInterval(() => {
    invoke('test_mem_command');
}, 1000)
```

### Reproduction

This demo demonstrates the memory leak.

1. clone
```bash
git clone https://github.com/zzyandzzy/tauri-memory-leak.git
```

2. run
```bash
cargo run
```

3. top
```bash
# get pid
ps -ef | grep WebKitWebProcess
top
```

screenshot:
![memory leak](https://raw.githubusercontent.com/zzyandzzy/tauri-memory-leak/main/2022-04-20_15-21.png)

### Platform and versions

```shell
Environment
  › OS: Linux 2.8 X64
  › Node.js: 14.17.6
  › npm: 7.21.1
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.8
```

**Comment by lucasfernog** [comment]
I can reproduce this issue :( seems like the eval function is leaking the memory.

**Comment by lucasfernog** [comment]
An example only using window.eval to demonstrate the issue:

```rust
use tauri::Manager;

fn main() {
  tauri::Builder::default()
    .setup(|app| {
      let w = app.get_window("main").unwrap();
      std::thread::spawn(move || loop {
        std::thread::sleep_ms(500);
        let v = vec![0xff; 1024 * 1024 * 2];
        w.eval(&format!("{:?}", v)).unwrap();
      });
      Ok(())
    })
    .run(tauri::generate_context!(
      "../../examples/helloworld/tauri.conf.json"
    ))
    .expect("error while running tauri application");
}
```

**Comment by lucasfernog** [comment]
I checked with @wusyong and there's nothing we can do here, the leak is from webkit2gtk process itself (and that's not the only one).

**Comment by lucasfernog** [comment]
If your command uses a lot of memory, try using a custom protocol instead to see if webkit can handle that.

**Comment by lucasfernog** [comment]
[tauri-invoke-http](https://github.com/tauri-apps/tauri-invoke-http) is also an alternative, which leverages a localhost server (yikes) instead of our current IPC implementation.

**Comment by ahkohd** [comment]
> If your command uses a lot of memory, try using a custom protocol instead to see if webkit can handle that.

I have tried using a custom  protocol, two things:
1. It freezes the UI when you make a request.
2. The memory still leaks.

**Comment by ahkohd** [comment]
Also, a memory leak happens when you emit an event to a window in a loop. 

During my investigation, I  found out that if you emit an event to the window but on the window, there is no listener registered there will be no memory leak. But if a listener is registered,  a memory leak occurs.
