### ISSUE TITLE
[feat] Old version of Cargo fails silently

### ISSUE THREAD

**Issue by TomByrne** [tauri-apps/tauri#3930]
### Describe the problem

I'm new to Tauri and was attempting to run the template (yarn + react).
Because I was running an older version of Cargo, the build failed, but because the rust build output gets replaced by the yarn build, the issue wasn't easy to work out.

### Describe the solution you'd like

Ideally, if the 'edition' in Cargo.toml is too new, the yarn build wouldn't get run, so that you could see the error in the output.

**Comment by lucasfernog** [comment]
What do you mean with `gets replaced by the yarn build`? Can you give us an example?

**Comment by TomByrne** [comment]
I'm on Windows, in vscode (so a Powershell console), and immediately after this issue happens, the yarn/react build starts, which clears the cargo build output, including the error message. If I kill the build at just the right time I can read the message, but it's like a 0.3s window or something.

So this is the important output that gets cleared:
```sh
error: failed to parse manifest at `C:\_projects\Lab\storage-view\src-tauri\Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
```

And this is what replaces it:
```sh
Compiled successfully!

You can now view storage-view in the browser.    

  http://localhost:3000

Note that the development build is not optimized.
To create a production build, use yarn build.    

webpack compiled successfully
Files successfully emitted, waiting for typecheck results...
Issues checking in progress...
No issues found.
```

**Comment by lucasfernog** [comment]
Thanks for the report. Also you should update your Rust :)
