### ISSUE TITLE
Tauri build fails on Arch Linux while attempting to build AppImage. [bug] 

### ISSUE THREAD

**Issue by james-d-hasselman** [tauri-apps/tauri#3946]
### Describe the bug

After a recent Arch Linux update, the tauri build no longer completes successfully. I have run it successfully as recently as last week. To eliminate the possibility that the error is specific to my system configuration I have also tried in a vanilla Arch installation in VirtualBox with nothing installed except the bare minimum required to run tauri build and I still get the same error.

### Reproduction

- mkdir test
- cd test
- npx create-tauri-app
- accept all defaults, Vanilla.js for UI
- cd tauri-app
- npm run tauri build -- --verbose

### Expected behavior

Build should produce AppImage without failing.

### Platform and versions

```shell
Environment
  › OS: Arch Linux Unknown X64
  › Node.js: 17.9.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.57.0
  › cargo: 1.57.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.7(outdated, latest: 1.0.0-rc.8)
  › @tauri-apps/api [NPM]: 1.0.0-rc.3(outdated, latest: 1.0.0-rc.3)
  › tauri [RUST]: 1.0.0-rc.6,
  › tauri-build [RUST]: 1.0.0-rc.5,
  › tao [RUST]: 0.7.0,
  › wry [RUST]: 0.14.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: ../dist

App directory structure
  ├─ src-tauri
  ├─ node_modules
  └─ dist
```

### Stack trace

```shell
-- Running input plugin: gtk -- 
[gtk/stdout] Installing AppRun hook
[gtk/stdout] Installing GLib schemas
[gtk/stderr] chmod: cannot access 'tauri-app.AppDir/usr/lib64': No such file or directory
[gtk/stderr] cp: ‘usr/share/glib-2.0’: No such file or directory
ERROR: Failed to run plugin: gtk (exit code: 1) 
Error running CLI: failed to bundle project: Shell Scripting Error:`error running appimage.sh`
```

### Additional context

npm list
tauri-app@ /home/james/software-projects/test/tauri-app
├── @tauri-apps/api@1.0.0-rc.3
└── @tauri-apps/cli@1.0.0-rc.8

**Comment by Christofon** [comment]
I have the same problem, also running arch.

**Comment by lucasfernog** [comment]
I can reproduce this. I'll see if I can fix it.

**Comment by lucasfernog** [comment]
I couldn't find the issue. `app.AppDir/usr/lib64` indeed doesn't exist, but `app.AppDir/usr/share/glib-2.0` does.

**Comment by CaptainTux** [comment]
can confirm, seeing the same issue.
However, building both debug and release with cargo `cargo build` and `cargo build --release` in `src-tauri` works just fine.
I think I'm frying my laptop on this train trip, building tauri so often :/

**Comment by james-d-hasselman** [comment]
The problem does indeed exist in the AppImage step of the build process. I have a new process for reproducing the issue which avoids having to rebuild the entire app every time.

- Run the reproduction steps above exactly once
- cd src-tauri/target/release/bundle/appimage
- rm -rf tauri-app.AppDir
- ./build_appimage.sh

This process only attempts to build the AppImage which is a much faster process. Additionally, if you open `build_appimage.sh` and comment out line 30 you can "debug" `linuxdeploy-plugin-gtk.sh` using echo for lack of any better ideas on my part.

**Comment by james-d-hasselman** [comment]
I have fixed the problem.

The following function in `linuxdeploy-plugin-gtk.sh`:
```
copy_tree() {
    local src=("${@:1:$#-1}")
    local dst="${*:$#}"

    for elem in "${src[@]}"; do
        cp "$elem" --archive --parents --target-directory="$dst" $verbose
    done
}
```
Should instead be:
```
copy_tree() {
    local src=("${@:1:$#-1}")
    local dst="${*:$#}"

    for elem in "${src[@]}"; do
        mkdir -p "${dst::-1}$elem"
        cp "$elem" --archive --parents --target-directory="$dst" $verbose
    done
}
```

So the full workaround is the following:
- Run `npm run tauri build` or `cargo tauri build` and allow it to fail at the AppImage step
- `cd src-tauri/target/release/bundle/appimage`
- `rm -rf tauri-app.AppDir`
- Comment out line 30 of `build_appimage.sh`
- Open `linuxdeploy-plugin-gtk.sh` and go to the `copy_tree` function
- Above the cp line add the following `mkdir -p "${dst::-1}$elem"`
- Run `./build_appimage.sh`
- The AppImage step will now complete successfully

**Comment by lucasfernog** [comment]
cc @FabianLars

**Comment by FabianLars** [comment]
Hmm, i wonder what changed in arch that made this fix necessary :thinking:

**Comment by james-d-hasselman** [comment]
Opened corresponding issue on linuxdeploy-plugin-gtk.
https://github.com/linuxdeploy/linuxdeploy-plugin-gtk/issues/31

**Comment by james-d-hasselman** [comment]
https://github.com/linuxdeploy/linuxdeploy-plugin-gtk/pull/32 Pull request created.

**Comment by weisbrja** [comment]
The pull request was created and merged into linuxdeploy, but since tauri uses a fork, it has not yet been merged into tauri itself. I am still experiencing this issue. Could someone please update tauri's fork?

**Comment by FabianLars** [comment]
The change made it into our fork too (https://github.com/tauri-apps/linuxdeploy-plugin-gtk/blob/master/linuxdeploy-plugin-gtk.sh#L60). Whatever issue you're having should be unrelated to this one.

**Comment by weisbrja** [comment]
Oh, well. The issue seemed very similar, guess I'll open a new issue then. Thanks.
