### ISSUE TITLE
[feat] Silent (or quieter) Windows updater

### ISSUE THREAD

**Issue by dceddia** [tauri-apps/tauri#3951]
### Describe the problem

The Windows updater currently just re-runs the installer at update time, which gets the job done, but the UX could be better if it was more hands-off.

### Describe the solution you'd like

The MSI installers support a few flags to make the installation less interactive. There's a [fully silent mode](https://stackoverflow.com/questions/8560166/silent-installation-of-a-msi-package) where it shows nothing onscreen, and a [passive mode](https://stackoverflow.com/questions/33484750/msiexec-difference-between-quiet-and-passive) where it only shows a progress bar. Chatting with Fabian in Discord it seems like the "passive" mode might be a good middle ground - an automatic installation, but with some feedback so the user knows what's going on.

### Additional context

I'd be happy to take a stab at implementing it - just grepping around for `msiexec` I see it's referenced in `core/tauri/src/updater/core.rs` and also `tauri/tooling/bundler/src/bundle/windows/templates/update-task.xml`. I think this would only require changing the `/qb+` to `/passive` in those two spots.

**Comment by lucasfernog** [comment]
Really good idea, I don't like how agressive the update process is with the installer popping up all the time.
