### ISSUE TITLE
Merge Title and Menu Bar

### ISSUE THREAD

**Issue by oyym** [tauri-apps/tauri#3964]
### Describe the problem

Merge Title and Menu Bar

### Describe the solution you'd like

Merging Menu Bar with Title Bar will free some room which can be very handy on small screen systems like laptops.

Like Visual Studio Code:
![image](https://user-images.githubusercontent.com/3069819/165148653-1fd3eafd-ac8c-4c9b-bd45-8cc10143d089.png)

**Comment by amrbashir** [comment]
That's probably not possible on all platforms, at least I am certain it is not possible on Windows. You'd better disable decorations and make a custom titlebar and custom menu in HTML.
