### ISSUE TITLE
[bug] The size of the window is bigger than what I set via setSize

### ISSUE THREAD

**Issue by cangSDARM** [tauri-apps/tauri#3970]
### Describe the bug

I like to dynamically set the size of a floating window (about 200x200 or less) through `setSize`, but the set size is always larger than I want.

for example:

```js
appWindow.setMinSize(new PhysicalSize(10, 10)).then(appWindow.outerSize()).then(console.log); 
// { height: 44, type: "Physical", width: 46 }

appWindow.setMinSize(new PhysicalSize(55, 55)).then(appWindow.outerSize()).then(console.log); 
// { height: 94, type: "Physical", width: 96 }
```

### Reproduction

Create a window like this:

```rust
#[derive(Deserialize)]
pub struct CreateWindowPayload {
  pub label: String,
  pub transparent: bool, 
}

#[tauri::command]
async fn create_new_window(payload: CreateWindowPayload, app_handle: tauri::AppHandle) -> Result<bool> {
  match WindowBuilder::new(
      &app_handle,
      payload.label.as_str(),
      WindowUrl::App((payload.label.clone() + ".html").into()),
    )
    .decorations(false)
    .transparent(payload.transparent)
    .title(payload.label.clone())
    .min_inner_size(10f64, 10f64)
    .build() {
      Ok(_) => Ok(true),
      Err(_) => Ok(false),
  }
}
```

Init it with:
```ts
appWindow.setAlwaysOnTop(true);
appWindow.setMinSize(new PhysicalSize(10, 10));
```

Set some little size like: 40x40, 50x50 etc.

### Expected behavior

normal size

### Platform and versions

```shell
Operating System - Windows, version 10.0.19044 X64
Webview2 - 100.0.1185.50
Visual Studio Build Tools:
   - Visual Studio Community 2019

Node.js environment
  Node.js - 14.17.6
  @tauri-apps/cli - 1.0.0-rc.5 (outdated, latest: 1.0.0-rc.8)
  @tauri-apps/api - 1.0.0-rc.3

Global packages
  npm - 6.14.11
  pnpm - 6.23.6
  yarn - 1.22.17

Rust environment
  rustup - 1.24.3
  rustc - 1.59.0
  cargo - 1.59.0
  toolchain - stable-x86_64-pc-windows-msvc 

App directory structure
/.parcel-cache
/client
/dist
/node_modules
/server

App
  tauri - 1.0.0-rc.6
  tauri-build - 1.0.0-rc.5
  tao - 0.7.0
  wry - 0.14.0
  build-type - bundle
  CSP - default-src 'self'
  distDir - ../dist
  devPath - http://localhost:3000/
  framework - React
```

**Comment by amrbashir** [comment]
This is fixed and will be released soon.

**Comment by NMTuan** [comment]
> This is fixed and will be released soon.

is fixed?
I want create a new window with only 1px or 2px height, but it looks like 40px height. 


code:

		const webview = new WebviewWindow('theUniqueLabel', {
			url: '/about',
			decorations: false,
			x: 0,
			y: screen.availHeight - 1,
			width: screen.availWidth,
			transparent: true,
			height: 1,
			alwaysOnTop: true
		});

--------------
Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 101.0.1210.53
  › MSVC:
      - Visual Studio ���ɹ��� 2019
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.16
  › @tauri-apps/api [NPM]: 1.0.0-rc.7
  › tauri [RUST]: 1.0.0-rc.17,
  › tauri-build [RUST]: 1.0.0-rc.15,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: Svelte

App directory structure
  ├─ .svelte-kit
  ├─ .vscode
  ├─ build
  ├─ node_modules
  ├─ src
  ├─ src-tauri
  └─ static
