### ISSUE TITLE
[bug] Questions about plugins

### ISSUE THREAD

**Issue by 57321** [tauri-apps/tauri#3972]
### Describe the bug

I want to write a plugin.
Following the documentation is fine, but as soon as I want to use the window parameter I get an error.

simple example

![image](https://user-images.githubusercontent.com/38900476/165322671-bf50d757-ba77-4142-8c76-7e404f3513a9.png)

Added window parameter

![image](https://user-images.githubusercontent.com/38900476/165323213-45ab262e-5231-4198-a0f8-b2a2d7bec249.png)

If used alone as a command instead of a plugin, window can be used as a parameter.

So, I am very confused, how should I be able to use the window parameter. because i need to listen to the event after calling the command.

like this

![image](https://user-images.githubusercontent.com/38900476/165324287-d54c8c59-e893-4181-9eb9-41431f6705d1.png)

I'm not quite sure the way I'm using it right?

### Platform and versions

```shell
Operating System - Windows, version 10.0.18362 X64
Webview2 - 100.0.1185.50
Visual Studio Build Tools - Not installed

Node.js environment
  Node.js - 17.9.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-rc.3

Global packages
  npm - 8.5.5
  pnpm - Not installed
  yarn - 1.22.10

Rust environment
  rustc - 1.60.0
  cargo - 1.60.0

Rust environment
  rustup - 1.24.3
  rustc - 1.60.0
  cargo - 1.60.0
  toolchain - stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)

App directory structure
/dist
/node_modules
/plugins
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-rc.6
`tauri.conf.json` error on `tauri > bundle > macOS`: Additional property 'providerShortName' is not allowed
```

**Comment by lucasfernog** [comment]
Try changing `fn hello(window: Window)` to `fn hello<R: Runtime>(window: Window<R>)` just like you did in the `init` function.

**Comment by lucasfernog** [comment]
The reason is that `Window` is using the default Runtime (tauri::Wry) but the plugin is generic over it so you need to use `Window<R>` where `R: tauri::Runtime`.

**Comment by 57321** [comment]
thanks
