### ISSUE TITLE
How to preload a script with electron injection

### ISSUE THREAD

**Issue by itisl2220** [tauri-apps/tauri#3989]
### Describe the problem

How to preload a script with electron injection
![image](https://user-images.githubusercontent.com/32608524/165621293-c02ef2aa-d980-45e1-9afd-d2ec062a5263.png)

### Describe the solution you'd like

Inject the script when the WebView loads the web page

**Comment by heyikang** [comment]
https://www.electronjs.org/docs/latest/api/webview-tag#preload

**Comment by itisl2220** [comment]
I'm sorry!  My question is how do I inject a script when loading a web page like Electron

**Comment by itisl2220** [comment]
> 见https://www.electronjs.org/docs/latest/api/webview-tag#preload

I'm sorry!  My question is how do I inject a script when loading a web page like Electron

**Comment by amrbashir** [comment]
you can use https://docs.rs/tauri/1.0.0-rc.8/tauri/window/struct.WindowBuilder.html#method.initialization_script when creating your window from rust

**Comment by itisl2220** [comment]
Ok! thank you

**Comment by itisl2220** [comment]
> 从 rust 创建窗口时，您可以使用https://docs.rs/tauri/1.0.0-rc.8/tauri/window/struct.WindowBuilder.html#method.initialization_script

Ok! thank you
