### ISSUE TITLE
TypeError: window.__TAURI_IPC__ is not a function

### ISSUE THREAD

**Issue by itisl2220** [tauri-apps/tauri#3998]
### Describe the bug

不能在使用WindowBuilder创建的Windows中使用Emit
![image](https://user-images.githubusercontent.com/32608524/165944191-fc280fd1-47ac-4e76-85f7-ded44c200a9c.png)

### Platform and versions

```shell
> tauri "info"


  › yarn: 1.22.17
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.9
  › @tauri-apps/api [NPM]: 1.0.0-rc.4
  › tauri [RUST]: 1.0.0-rc.8,
  › tauri-build [RUST]: 1.0.0-rc.7,
  › tao [RUST]: 0.8.3,
  › wry [RUST]: 0.15.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: Vue.js

App directory structure
  ├─ .vscode
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

**Comment by itisl2220** [comment]
Emit cannot be used in Windows created using WindowBuilder

**Comment by FabianLars** [comment]
Tauri's scripts (including the IPC) aren't injected into windows with external-ish urls (like `https://google.com`). So in the context of WindowBuilder it only works if you use `AppUrl` urls like `WindowUrl::App("index.html".into())`.

This is not a bug, but expected behavior for now.

**Comment by itisl2220** [comment]
Ipc. postMessage Whether rust can receive it

**Comment by FabianLars** [comment]
No, without the IPC or tauri's scripts you **can't** communicate with the rust backend.

**Comment by itisl2220** [comment]
An earlier attempt to create a window with WRY using IPC to communicate with Rust was feasible

**Comment by FabianLars** [comment]
Ah that's what you meant, yes the underlying postMessage should keep working as far as i know. Handling it on the rust side can be tricky tho, especially since we don't offer access to the webview controller.

**Comment by itisl2220** [comment]
Because I want two Windows to communicate with each other, and the other window is loaded with HTTPS

**Comment by luucasrb** [comment]
Hi @FabianLars! 
I'm having the same error here. My context is:

- My `main_window` is created in the Rust backend with: `let main_window = app.get_window("main").unwrap();`. It renders some `index.html` that is at `/renderers` folder. So my `tauri.config` is set with:

```json
...
"build": {
    "distDir": "./renderers/",
    "devPath": "./renderers/",
    "withGlobalTauri": true
  },
...
```

and 

```json
...
  "tauri": {
    "allowlist": {
      "window": {
        "all": true,
      },
...
```

After some user input in the `index.html`, is called `window.location.href = user_input_url;`. Where `user_input_url` is another isolated Vue App address with `@tauri-apps/api` installed. However, in the Rust side I have a `Multiwindow` button that is a `CustomMenuItem` that creates new windows with:

```rust
tauri::WindowBuilder::new(
    &app_handle,
    monitor.name().unwrap().replace(&['\\', '(', ')', ',', '\"', '.', ';', ':', '\''][..], ""),
    tauri::WindowUrl::App("/".into())
    ).build();
```

**and** emits an event with:

 ```rust
event.window().emit("multi_window_native", Payload { code: "001".into(), message: "Application is now in multiwindow mode".into() });
```

So, in the Vue side, I want to listen this event to notify the user that he is now in Multiwindow mode, with:

```ts
import { appWindow } from '@tauri-apps/api/window';

await appWindow.listen("multi_window_native", ({ event, payload }: any) => {
  notify()
}).catch((err) => { console.log(err) });
```

But my Tauri "main" window keeps falling in the `catch` with: `TypeError: window.__TAURI_IPC__ is not a function. (In 'window.__TAURI_IPC__({ cmd: r, callback: o2, error: a2, ...n })', 'window.__TAURI_IPC__' is undefined)`

Could you please give me some advice on how to approach this scenario?

## Platform and version
```bash
$ RUST_LOG='info' RUST_BACKTRACE='full' tauri info

Environment
  › OS: Ubuntu 20.04 X64
  › Node.js: 16.17.0
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.1
  › @tauri-apps/api [NPM]: 2.0.0-alpha.0
  › tauri [RUST]: 2.0.0-alpha.1,
  › tauri-build [RUST]: 2.0.0-alpha.0,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ./renderers/
  › devPath: ./renderers/

App directory structure
  ├─ node_modules
  ├─ icon.png
  ├─ src-tauri
  └─ .git
```

**Comment by luucasrb** [comment]
> But my Tauri "main" window keeps falling in the `catch` with: `TypeError: window.__TAURI_IPC__ is not a function. (In 'window.__TAURI_IPC__({ cmd: r, callback: o2, error: a2, ...n })', 'window.__TAURI_IPC__' is undefined)`


Any help guys? =/
