### ISSUE TITLE
[bug] The tray menu should not pop up when the left mouse button is clicked (macOS)

### ISSUE THREAD

**Issue by rming** [tauri-apps/tauri#4002]
### Describe the bug

The tray menu pops up when you right-click on both Windows and macOS.
But left-clicking on a mac will also pop up the tray menu, whereas Windows does not.

### Reproduction

1. run app with tray menu
2. left click on macOS will pop menu and trigger left click event

### Expected behavior

Same  behavior on macOS and Windows, pop menu only right clicked, so we can custom left click behavior.

### Platform and versions

```shell
Environment
  › OS: Mac OS 12.3.1 X64
  › Node.js: 16.14.0
  › npm: 8.3.1
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.24.3
  › rustc: 1.59.0
  › cargo: 1.59.0
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.9
  › @tauri-apps/api [NPM]: 1.0.0-rc.4
  › tauri [RUST]: 1.0.0-rc.8,
  › tauri-build [RUST]: 1.0.0-rc.7,
  › tao [RUST]: 0.8.3,
  › wry [RUST]: 0.15.1,

App
  › build-type: bundle
  › CSP: script-src 'unsafe-eval' 'self'; default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self'; img-src 'self' data: http: https:;
  › distDir: ../dist
  › devPath: http://127.0.0.1:8080/
  › framework: Vue.js (Vue CLI)
  › bundler: Webpack

App directory structure
  ├─ dist
  ├─ patches
  ├─ node_modules
  ├─ public
  ├─ scripts
  ├─ .github
  ├─ src-tauri
  ├─ .git
  └─ src
✨  Done in 6.70s.
```

**Comment by amrbashir** [comment]
related: https://github.com/tauri-apps/tao/issues/317

**Comment by rming** [comment]
https://user-images.githubusercontent.com/1621419/165970692-3fdb3309-b045-473b-abd2-f8f43bba2af1.mov

For some tray applications, it is convenient to pop up a quick action window or pop up the main window.

**Comment by amrbashir** [comment]
Subscribe to https://github.com/tauri-apps/tao/issues/317 for more info, I just reopened it along with its PR https://github.com/tauri-apps/tao/pull/329. Once upstream is fixed it will automatically land in tauri.
