### ISSUE TITLE
[bug] Clicking on the tray icon sometimes does not response (macOS)

### ISSUE THREAD

**Issue by rming** [tauri-apps/tauri#4003]
### Describe the bug

right click examples, sometimes no event and no response

https://user-images.githubusercontent.com/1621419/165968794-dce51009-215e-4b44-91a2-8c62a474ef41.mov

### Reproduction

1. run app with try menu on macOS
2. right click try icon

### Platform and versions

```shell
Environment
  › OS: Mac OS 12.3.1 X64
  › Node.js: 16.14.0
  › npm: 8.3.1
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.24.3
  › rustc: 1.59.0
  › cargo: 1.59.0
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.9
  › @tauri-apps/api [NPM]: 1.0.0-rc.4
  › tauri [RUST]: 1.0.0-rc.8,
  › tauri-build [RUST]: 1.0.0-rc.7,
  › tao [RUST]: 0.8.3,
  › wry [RUST]: 0.15.1,

App
  › build-type: bundle
  › CSP: script-src 'unsafe-eval' 'self'; default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self'; img-src 'self' data: http: https:;
  › distDir: ../dist
  › devPath: http://127.0.0.1:8080/
  › framework: Vue.js (Vue CLI)
  › bundler: Webpack

App directory structure
  ├─ dist
  ├─ patches
  ├─ node_modules
  ├─ public
  ├─ scripts
  ├─ .github
  ├─ src-tauri
  ├─ .git
  └─ src
✨  Done in 6.70s.
```

### Additional context

Is it possible that the icon size is causing the problem?
![icon_tray_tpl](https://user-images.githubusercontent.com/1621419/165968426-13de1415-c529-4e0d-b372-c12e7f29c072.png)
<img width="415" alt="image" src="https://user-images.githubusercontent.com/1621419/165968643-1de75a0c-c2bf-4fda-9f29-eec10eda10c8.png">

**Comment by lucasfernog** [comment]
This is not related to the icon, I'll open an issue in the tao repo.

**Comment by amrbashir** [comment]
a fix will land in v2
