### ISSUE TITLE
[bug] iframe is too many nested with isolation pattern

### ISSUE THREAD

**Issue by keiya01** [tauri-apps/tauri#4015]
### Describe the bug

I found the iframe element is too many nested with isolation pattern.
Is this behavior expected?

<img width="817" alt="Screen Shot 2022-05-01 at 0 18 16" src="https://user-images.githubusercontent.com/34934510/166111649-154df6d0-18a7-4b88-8adf-92bb46eb8311.png">

### Reproduction

1. go to tauri repository
2. run `cargo run --example isolation --features isolation`
3. show inspector
4. see elements tab

### Expected behavior

I think we should insert the only one iframe element.

### Platform and versions

```shell
Environment
  › OS: Mac OS 12.3.1 X64
  › Node.js: 16.14.0
  › npm: 8.3.1
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.24.3
  › rustc: 1.59.0
  › cargo: 1.59.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.9
  › @tauri-apps/api [NPM]: 1.0.0-rc.4
  › tauri [RUST]: 1.0.0-rc.8,
  › tauri-build [RUST]: 1.0.0-rc.7,
  › tao [RUST]: 0.8.2,
  › wry [RUST]: 0.15.0,

App
  › build-type: bundle
  › CSP: default-src 'self' customprotocol: asset:; font-src https://fonts.gstatic.com; img-src 'self' asset: https://asset.localhost blob: data:; style-src 'unsafe-inline' 'self' https://fonts.googleapis.com
  › distDir: ../dist
  › devPath: http://localhost:5000/
  › framework: Svelte

App directory structure
  ├─ isolation-dist
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  └─ src

```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by keiya01** [comment]
https://github.com/tauri-apps/wry/blob/fd1dcc3cc5a290bfe4ae8de04064074109902432/src/webview/wkwebview/mod.rs#L498-L500

I understand that this issue will be fixed when `forMainFrameOnly` is changed to `true`.

**Comment by keiya01** [comment]
I find the same issue in windows.
<img width="655" alt="Screen Shot 2022-05-02 at 1 39 59" src="https://user-images.githubusercontent.com/34934510/166155583-40f576aa-cc25-4626-ac6e-2dd7ac4d5ae9.png">

But linux seems to be working.
<img width="729" alt="Screen Shot 2022-05-02 at 1 44 26" src="https://user-images.githubusercontent.com/34934510/166155717-cf3c94b9-bd39-4055-80e6-0a3131218e80.png">

**Comment by lucasfernog** [comment]
I'm fixing it. Thanks for the report!
