### ISSUE TITLE
[feat] `check` command for tauri-cli

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#4016]
### Describe the problem

It is too slow to wait for a build. I think we can add a `check` command that checks if program doesn't have any compile errors without building it. It will useful for workflows

### Describe the solution you'd like

Cargo has a built-in feature that supports this (`cargo check`). We can wrap this command to tauri-cli to solve this problem.

**Comment by FabianLars** [comment]
you can use `cargo check` in your src-tauri directory (or wherever your tauri core is located) just like in any normal rust project (otherwise stuff like rust-analyzer wouldn't work either).
imo it's not worth the hassle to add it to the tauri cli 🤔

**Comment by lucasfernog** [comment]
If we add `check`, we might end up needing to add `test`, `fmt`, `clippy` etc. And the CLI will be agnostic in the future. Maybe we can reconsider when we have more languages to offer.
