### ISSUE TITLE
Verifying Tauri signed release assets doesn't work

### ISSUE THREAD

**Issue by kfiven** [tauri-apps/tauri#4023]
### Describe the bug

When verifying tauri signed release assets with Minisign tool, it throws an error: `base64 conversion failed - was an actual public key given?`

I have downloaded https://github.com/zzzgydi/clash-verge/releases/tag/v1.0.0 assets (.msi.zip, .msi.zip.sig and public keys form tauri.conf.json) and tried to verify with Minisign tool and it doesn't work throwing the above error. I have tested it with more than projects release assets to eliminate any error by my side and it ends with same result.

I have also tried to use keys generated by Minisign into Tauri action but action fails in such cases with error: `Error running CLI: invalid utf-8 sequence of 1 bytes from index 91`

In the end, looks like there is no way of verifying Tauri release assets if build process use keys generated by `tauri signer generate` and 
if keys are generated with Minisign then Tauri release process doesn't work with them.

### Platform and versions

```shell
not required.
```

**Comment by lucasfernog** [comment]
Note that the Tauri private key, public key and signatures are all base64 encoded. If you want to verify a signature using something like [rsign2](https://github.com/jedisct1/rsign2), you need to base64 decode both the public key and the signature key. To use a manually-minisign-generated keypair in Tauri, you need to base64 encode the private key and public key.

The encode logic can be found here:
https://github.com/tauri-apps/tauri/blob/5666c0bce8386982cce64de23270d7120ab29fa1/tooling/cli/src/helpers/updater_signature.rs#L39
https://github.com/tauri-apps/tauri/blob/5666c0bce8386982cce64de23270d7120ab29fa1/tooling/cli/src/helpers/updater_signature.rs#L141

any base64 encoder/decoder should work.

I tested your signatures and they are working fine.

**Comment by kfiven** [comment]
Hi @lucasfernog , thanks for the quick response,

However when I am trying rsign2, I am getting `base64 conversion failed - was an actual public key given?`
The command I used is `rsign verify myfile.txt -P [PUBLIC KEY STRING] -x mysignature.file`

**Comment by lucasfernog** [comment]
Did you decode the public key string? The command that worked on my end was:
`rsign verify Clash.Verge_1.0.0_x64_en-US.msi.zip -x Clash.Verge_1.0.0_x64_en-US.msi.zip.sig -P RWTlqsR6CqVaETI3nMKsdHYETIqRCY36zlu0ERcoawjRWW4Zx7Ri06af`

where the .sig contents is:
```
untrusted comment: signature from tauri secret key
RUTlqsR6CqVaEasIe5mh+f58Rjdw/TXTBKxPhWhnoliDSdB7fVk4b4Qao3lNNbToHyT/L1pQfYvliK2y7hVtkOK8Jl+xwa1w+QQ=
trusted comment: timestamp:1650906809	file:D:\a\clash-verge\clash-verge\src-tauri\target\release\bundle/msi/Clash Verge_1.0.0_x64_en-US.msi.zip
OIbcaoB6gTc/GWf5lKFShuhvq4tNO7EYkhEpnYReQykWK4etJMsZo1zfBmirFQfPkrPNcvNyBPKqvd28s2jmAQ==
```

You can also use the full decoded public key content in a file with the `-p` option instead of `-P`.

**Comment by kfiven** [comment]
ah, I was missing the decoding part. It works now thanks! :)

**Comment by kandyjam** [comment]
> ah, I was missing the decoding part. It works now thanks! :)

would you tell me the detail about decoding part? there is a error 'Signature decoding error' return by update-status event

**Comment by kfiven** [comment]
@kandyjam I just used https://www.base64decode.org/ to decode public key and signature. Then the verification works fine.

**Comment by kandyjam** [comment]
> @kandyjam I just used https://www.base64decode.org/ to decode public key and signature. Then the verification works fine.

thanks your anwser,it works after regenerate the key

**Comment by yassinevic** [comment]
Hello
can any one share with us the step by step to sign the updates.
i do not understand the decoding part.

[Error from the update server]
'Signature decoding error: Invalid byte 58, offset 4.'
