### ISSUE TITLE
[bug] Tauri app fails to launch in release mode on Mac OS

### ISSUE THREAD

**Issue by Markos-Th09** [tauri-apps/tauri#4024]
### Describe the bug

Some kind of failed memory allocation causes the app to not launch when built in release mode. When tauri tries to free that memory it fails

### Reproduction

1. Create a new tauri app
2. Run tauri build
3. Launch the app
4. The app should immediately quit

### Expected behavior

The app should launch as it does in development mode

### Platform and versions

```shell
Environment
  › OS: Mac OS 12.3.1 X64
  › Node.js: 16.13.2
  › npm: 8.1.2
  › pnpm: Not installed!
  › yarn: 3.2.0
  › rustup: 1.24.3
  › rustc: 1.59.0
  › cargo: 1.59.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.9
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.0.0-rc.8,
  › tauri-build [RUST]: 1.0.0-rc.7,
  › tao [RUST]: 0.8.3,
  › wry [RUST]: 0.15.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../out
  › devPath: http://localhost:3000/
  › framework: React (Next.js)
  › bundler: Webpack

App directory structure
  ├─ .yarn
  ├─ out
  ├─ node_modules
  ├─ .next
  ├─ styles
  ├─ public
  ├─ src-tauri
  ├─ .git
  └─ pages
```

### Stack trace

```shell
tauri-app(68865,0x10148d600) malloc: *** error for object 0x1: pointer being freed was not allocated
tauri-app(68865,0x10148d600) malloc: *** set a breakpoint in malloc_error_break to debug
```

### Additional context

This problem randomly happened one day without changing anything in the app.

**Comment by JonasKruckenberg** [comment]
Can you provide a minimal repo that re-creates this bug? Because on it's on the steps are fine, I run these steps almost daily and they work on my macos machine.

**Comment by lucasfernog** [comment]
I believe this was fixed here: https://github.com/tauri-apps/wry/pull/567
A patch will be published soon. I can confirm if you send us a minimal repo to reproduce this (from my tests it happens when the response is empty e.g. an empty file).
