### ISSUE TITLE
[bug] Open dialog does not set title via JS API

### ISSUE THREAD

**Issue by keraf** [tauri-apps/tauri#4029]
### Describe the bug

When opening a dialog using the JS API, setting the `title` property inside the dialog options will has no effect.

### Reproduction

With the following code:

```
import { open } from '@tauri-apps/api/dialog';
open({ title: 'Testing' });
```

Observe the title of the dialog window (should be set to "Open" instead of "Testing").

### Expected behavior

Dialog title should be set when specifying the property. Looking at the [open_dialog function](https://github.com/tauri-apps/tauri/blob/dev/core/tauri/src/endpoints/dialog.rs#L89,L133), it does not seem like the `set_title` method has been called on the dialog builder. 

### Platform and versions

```shell
> tauri "info"


Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 101.0.1210.32
  › MSVC: 
      - Visual Studio Community 2022
  › Node.js: 18.0.0
  › npm: 8.6.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.9
  › @tauri-apps/api [NPM]: 1.0.0-rc.4
  › tauri [RUST]: 1.0.0-rc.8,
  › tauri-build [RUST]: 1.0.0-rc.7,
  › tao [RUST]: 0.8.3,
  › wry [RUST]: 0.15.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:8000/
  › framework: React

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ build
  ├─ node_modules
  ├─ src-app
  └─ src-ui
```

### Additional context
Seems like the exact same issue affects `save_dialog` as well.

**Comment by lucasfernog** [comment]
Thanks for the report!
