### ISSUE TITLE
[bug] `on_page_load` not triggered for remote page

### ISSUE THREAD

**Issue by lsdsjy** [tauri-apps/tauri#4037]
### Describe the bug

If I set the `tauri.windows.url` to some remote page, e.g. "https://google.com", in `tauri.conf.json`, the `on_page_load` hook of the app won't be triggered. 

```json
    "windows": [
      {
        "title": "Tauri App",
        "url": "https://google.com",
        "width": 800,
        "height": 600,
        "resizable": true,
        "fullscreen": false
      }
    ],
```

```rust
  tauri::Builder::default()
    .on_page_load(|window, payload| {
      println!("page loaded");
    })
    .run(tauri::generate_context!());
```

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 101.0.1210.32
  › MSVC: 
      - Visual Studio Community 2022 
      - Visual Studio 15 ���ɹ��� 2017
      - Visual Studio ���ɹ��� 2019   
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: 1.22.10
  › rustup: 1.24.3
  › rustc: 1.62.0-nightly
  › cargo: 1.62.0-nightly
  › Rust toolchain: nightly-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.9
  › @tauri-apps/api [NPM]: 1.0.0-rc.4
  › tauri [RUST]: 1.0.0-rc.8,
  › tauri-build [RUST]: 1.0.0-rc.7,
  › tao [RUST]: 0.8.3,
  › wry [RUST]: 0.15.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: ../dist

App directory structure
  ├─ dist
  ├─ node_modules
  └─ src-tauri
```

**Comment by FabianLars** [comment]
This is not really a "bug", we just don't inject _any_ tauri scripts into external urls (by design for now) and on_page_load depends on the DOMContentLoaded js event.

**Comment by lsdsjy** [comment]
So how can I open a remote page and execute some code when the page is loaded? I want to achieve some kind of automation like puppeteer, for example, click a button on the page.

**Comment by lucasfernog** [comment]
You can run window.eval in the rust code. That's the only way, we won't run code in remote pages for security reasons.

**Comment by henriquelbsouza** [comment]
Hi @lucasfernog, sorry for reviving this issue. 
I just started playing around with Tauri, and that is something I wanted to do. I don't know where to execute this window.eval so I can inject some scripts into a remote web page (I tried on on_page_load, setup). 

I am working on a concept that might be a project in the future, but I want to modify the remote page to be more friendly in some aspects. Can you assist?

**Comment by lucasfernog** [comment]
you should eval it directly after creating the window with the WindowBuilder (https://docs.rs/tauri/1.0.0-rc.14/tauri/window/struct.WindowBuilder.html).

**Comment by henriquelbsouza** [comment]
Thanks @lucasfernog
I think I will need much more knowledge on rust than I thought 😄 

I will do some tests this weekend and see what can I do :)
