### ISSUE TITLE
[feat] ignore ssl certificate errors

### ISSUE THREAD

**Issue by cars10** [tauri-apps/tauri#4039]
### Describe the problem

My app lets users connect to self-hosted services that often use self-signed or otherwise untrusted ssl certificates. I cannot access these services with tauri because of certificate errors.

### Describe the solution you'd like

Ideal solution would be a prompt that lets users chose to trust the certificate. Another way would be how electron handles it, you can hook to a `certificate-error` event and ignore the errors, something like this:

```
// SSL/TSL: this is the self signed certificate support
app.on('certificate-error', (event, webContents, url, error, certificate, callback) => {
    // On certificate error we disable default behaviour (stop loading the page)
    // and we then say "it is all fine - true" to the callback
    event.preventDefault();
    callback(true);
});
```
[source](https://stackoverflow.com/questions/38986692/how-do-i-trust-a-self-signed-certificate-from-an-electron-app)

### Alternatives considered

Even a command line flag like chromiums `--ignore-certificate-errors` would be helpful.

**Comment by FabianLars** [comment]
idk about webkit*, but WebView2 literally just added an experimental api for this in a recent pre-release SDK so we would have to wait for that to stabilize first :/

\* afaik webkitgtk has an api for that too, but i didn't find anything for macOS.

**Comment by cars10** [comment]
Oh wow, i did not expect missing support in the underlying frameworks. Guess i have to use electron for now.. Thanks!

**Comment by JonasKruckenberg** [comment]
I would consider using a rust http client, like `reqwest` if you can. This would allow you to, instead of ignoring ssl errors, provide a custom root certificate that would be compatible with the self signed certs. So you're significantly reducing the attack surface with self signed certificates.

**Comment by cars10** [comment]
I currently use vuejs and make requests via browser fetch. So just to make sure, you are basically thinking about:

* write a rust component that exposes a fetch-like interface and uses (for example) reqwest under the hood. this component should ignore/handle ssl errors
* use this component in my vuejs app to make requests when packaging for tauri. rust/js communication could work like this: https://tauri.studio/docs/guides/command
* this would result in http requests being sent from the rust side (tauri process) and only the response getting passed to the frontend

Or did i misunderstand something?

**Comment by JonasKruckenberg** [comment]
You got that right yeah! You can write some nicer JS abstraction on top of `invoke` that replicates the same interface `fetch` has, so you wouldn't even have to change your current code much

**Comment by lucasfernog** [comment]
That is one of the disable-security requests we get oftenly but aren't planning on implementing anytime soon. Maybe we reconsider when we have more control over the webview.

**Comment by cars10** [comment]
Yea i get that, no worries :)
Just for future readers, the idea proposed by @JonasKruckenberg works as expected. Thanks!

**Comment by feb-ri** [comment]
> Yea i get that, no worries :) Just for future readers, the idea proposed by @JonasKruckenberg works as expected. Thanks!

Can you please share the example code?

**Comment by BigBaBei** [comment]
I want same feature, but for now i have to use electron. Is there any progress?

**Comment by liudonghua123** [comment]
Maybe the http client used in tauri is [attohttpc](https://github.com/sbstp/attohttpc) and [reqwest](https://github.com/seanmonstar/reqwest).

https://github.com/tauri-apps/tauri/blob/dev/core/tauri/src/api/http.rs#L136

And `.danger_accept_invalid_certs(true)` can use to bypass attohttpc/reqwest tls verfification.

https://github.com/sbstp/attohttpc/blob/3fe9967ee83258c8a5012736f07c8111e642ee69/tests/test_invalid_certs.rs#L12-L26

https://github.com/seanmonstar/reqwest/issues/182#issuecomment-469997565

https://github.com/seanmonstar/reqwest/issues/1210#issuecomment-827538842

**Comment by andrewpedia** [comment]
> Maybe the http client used in tauri is [attohttpc](https://github.com/sbstp/attohttpc) and [reqwest](https://github.com/seanmonstar/reqwest).
> 
> https://github.com/tauri-apps/tauri/blob/dev/core/tauri/src/api/http.rs#L136
> 
> And `.danger_accept_invalid_certs(true)` can use to bypass attohttpc/reqwest tls verfification.
> 
> https://github.com/sbstp/attohttpc/blob/3fe9967ee83258c8a5012736f07c8111e642ee69/tests/test_invalid_certs.rs#L12-L26
> 
> [seanmonstar/reqwest#182 (comment)](https://github.com/seanmonstar/reqwest/issues/182#issuecomment-469997565)
> 
> [seanmonstar/reqwest#1210 (comment)](https://github.com/seanmonstar/reqwest/issues/1210#issuecomment-827538842)

have you tried this

**Comment by igdswzcd** [comment]
> > Maybe the http client used in tauri is [attohttpc](https://github.com/sbstp/attohttpc) and [reqwest](https://github.com/seanmonstar/reqwest).
> > https://github.com/tauri-apps/tauri/blob/dev/core/tauri/src/api/http.rs#L136
> > And `.danger_accept_invalid_certs(true)` can use to bypass attohttpc/reqwest tls verfification.
> > https://github.com/sbstp/attohttpc/blob/3fe9967ee83258c8a5012736f07c8111e642ee69/tests/test_invalid_certs.rs#L12-L26
> > [seanmonstar/reqwest#182 (comment)](https://github.com/seanmonstar/reqwest/issues/182#issuecomment-469997565)
> > [seanmonstar/reqwest#1210 (comment)](https://github.com/seanmonstar/reqwest/issues/1210#issuecomment-827538842)
> 
> have you tried this

Windows 10 + tauri 1.3.0
I have already tried and it works! My Steps:
- Modify tauri's `http.rs` in .cargo (`C:/Users/**/.cargo/registry/src/**/tauri-1.3.0/src/api/http.rs`), add one line just under line:136
```
// line:136
let mut request_builder = attohttpc::RequestBuilder::try_new(method, &request.url)?;
// after change
let mut request_builder = attohttpc::RequestBuilder::try_new(method, &request.url)?;
request_builder = request_builder.danger_accept_invalid_certs(true);
```
- Delete `target/*` in your project to recompile changes
- ReBuild your project

Finally you will find that you can use ClientBuilder and HttpRequestBuilder to access https apis under a self-signed certificate.

**Comment by liudonghua123** [comment]
> > > Maybe the http client used in tauri is [attohttpc](https://github.com/sbstp/attohttpc) and [reqwest](https://github.com/seanmonstar/reqwest).
> > > https://github.com/tauri-apps/tauri/blob/dev/core/tauri/src/api/http.rs#L136
> > > And `.danger_accept_invalid_certs(true)` can use to bypass attohttpc/reqwest tls verfification.
> > > https://github.com/sbstp/attohttpc/blob/3fe9967ee83258c8a5012736f07c8111e642ee69/tests/test_invalid_certs.rs#L12-L26
> > > [seanmonstar/reqwest#182 (comment)](https://github.com/seanmonstar/reqwest/issues/182#issuecomment-469997565)
> > > [seanmonstar/reqwest#1210 (comment)](https://github.com/seanmonstar/reqwest/issues/1210#issuecomment-827538842)
> > 
> > 
> > have you tried this
> 
> Windows 10 + tauri 1.3.0 I have already tried and it works! My Steps:
> 
> * Modify tauri's `http.rs` in .cargo (`C:/Users/**/.cargo/registry/src/**/tauri-1.3.0/src/api/http.rs`), add one line just under line:136
> 
> ```
> // line:136
> let mut request_builder = attohttpc::RequestBuilder::try_new(method, &request.url)?;
> // after change
> let mut request_builder = attohttpc::RequestBuilder::try_new(method, &request.url)?;
> request_builder = request_builder.danger_accept_invalid_certs(true);
> ```
> 
> * Delete `target/*` in your project to recompile changes
> * ReBuild your project
> 
> Finally you will find that you can use ClientBuilder and HttpRequestBuilder to access https apis under a self-signed certificate.

It seems the `request_builder` has changed in new version, for 1.x, it use `reqwest::Client` instead of `attohttpc::RequestBuilder`.

https://github.com/tauri-apps/tauri/blob/cc3d8e77313672f25520e278bbe8fae1b275a735/core/tauri/src/api/http.rs#L103

https://github.com/tauri-apps/tauri/blob/7fd4ca0aefa8b9bb032ef5abcaa57f296b738f14/core/tauri/src/api/http.rs#L136

And for dev/2.x, the code may migrated to new repo which use `reqwest::ClientBuilder`. See also https://tauri.app/v1/api/js/http/, https://beta.tauri.app/features/http-client/.

https://github.com/tauri-apps/tauri-plugin-http/blob/abeeedc1b24dd456a76aae6bc4f33d2ef3f72bbf/src/commands.rs#L152

So maybe we should search similar solution like [`attohttpc::RequestBuilder.danger_accept_invalid_certs`](https://docs.rs/attohttpc/latest/attohttpc/struct.RequestBuilder.html#method.danger_accept_invalid_certs) for reqwest.

And I also found `reqwest` also provide [danger_accept_invalid_certs](https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.danger_accept_invalid_certs). See also https://github.com/seanmonstar/reqwest/issues/182#issuecomment-469997565.

**Comment by realtebo** [comment]
Under the hood, chromium allows flag to disable verification of certificates and also to allow fetching http resoureces.

We are in the main and vital need to connect to a local odata provider using http and we are stalled

**Comment by FabianLars** [comment]
@realtebo Just to be sure, are you really talking about `http` or do you mean `https`? For `http` certificates should not matter, no?

If it's http, you're using tauri v1, and you're dealing with mixed-content errors (windows only) then try this setting https://v1.tauri.app/v1/api/config/#securityconfig.dangeroususehttpscheme - if not then we'll need more info.

**Comment by RainyNight9** [comment]
Tauri V2 ？ignore ssl certificate errors

**Comment by gknapp** [comment]
I've seen recommendations to fetch HTTPS assets via the rust backend using reqwest, to relax certificate verification. This path would be complex, if even possible, as within my app resources are fetched in an iframe within my webview2 front-end UI.

I'm using Tauri V2. I haven't seen mention in the docs of there being a capability / permission setting to relax the webview2's verification or to specify a CA certificate.

My use case is accessing internal corporate infrastructure during the QA cycle, where certificates are self-signed. In production the certificate chain is trusted and not a problem. The webview refuses to fetch assets with the error: `net:ERR_CERT_AUTHORITY_INVALID`

Any plans on the Tauri roadmap to expose webview options so these settings can be adjusted?

Sorry for commenting on a closed feature request, I couldn't find a related open one.
