### ISSUE TITLE
Tauri is using existing app running on port 8080 and showing it on the Desktop APP [bug] 

### ISSUE THREAD

**Issue by jaldaadithya** [tauri-apps/tauri#4040]
Team, I'm using MacBook Air M1, I tried installing Tauri.
I have a Svelte App which is running on port 8080.
Then I ran the Tauri app(Svelte) using npm run tauri dev, Now Tauri is using an existing app on 8080 and showing it under the Tauri desktop instead of using a brand new Svelte app(Hello World)

During Tauri startup it is shown as **Port 8080 is taken; using 52272 instead.**
So it should use 52272 port instead of 8080

Please look into it Thank you for the support.

![image](https://user-images.githubusercontent.com/19626378/166432622-9b03948a-acf6-4c88-a831-41cb31bc014a.png)
![image](https://user-images.githubusercontent.com/19626378/166432793-5272f0a2-f9a9-4647-adfa-43dcf29db25c.png)

### Reproduction

1) Install svelte and run the svelte app by making some changes in the svelte app instead of hello world (8080 port)
2) Install the Tauri app by choosing Svelte framework and run it 

Tauri is taking the UI from 8080 port instead of brand new Hello World Svelte app

### Expected behavior

It should run the Svelte Hello world app when launched for the first time

### Platform and versions

```shell
> graviton@1.0.0 tauri /Users/ovaledge/Documents/tutorials/graviton
> tauri "info"


Environment
  › OS: Mac OS 12.3.1 X64
  › Node.js: 14.19.0
  › npm: 6.14.16
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.9
  › @tauri-apps/api [NPM]: 1.0.0-rc.4
  › tauri [RUST]: 1.0.0-rc.8,
  › tauri-build [RUST]: 1.0.0-rc.7,
  › tao [RUST]: 0.8.3,
  › wry [RUST]: 0.15.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../public
  › devPath: http://localhost:8080/
  › framework: Svelte
  › bundler: Rollup

App directory structure
  ├─ node_modules
  ├─ public
  ├─ scripts
  ├─ src-tauri
  └─ src
```

**Comment by FabianLars** [comment]
Tauri doesn't actually know about the port of your server and can't get it by itself either (especially if you wouldn't use beforeDevCommand).

So there's really nothing we can do other than asking you to configure your devPath correctly :/

**Comment by lucasfernog** [comment]
You need to kill the process running on port 8080 or change your dev server default port along with the value defined in tauri.conf.json. Tauri can only know about this if the JS framework has plugin capabilities e.g. Vue CLI, Quasar. You could write a rollup or webpack plugin to handle this too.

**Comment by jaldaadithya** [comment]
Thank you, It worked when I changed **"devPath": "http://localhost:8083" in tauri.conf.json and  "start": "sirv public --no-clear --port=8083" in package.json**
