### ISSUE TITLE
[bug] Single quotes are ignored in updater's release notes

### ISSUE THREAD

**Issue by dceddia** [tauri-apps/tauri#4043]
### Describe the bug

When including single quotes inside the `notes` field of the updater JSON, they get stripped out of the displayed string, so words like `don't` are missing the apostrophe. I tried escaping the quotes like `"notes": "Escaped \'quotes\' test"` and that caused the updater to not display the update popup at all.

### Reproduction

Make a JSON file for the updater like this, with single quotes inside the `notes` string:

```
{
    "name": "v0.2.0",
    "notes": "This 'word' won't display with quotes around it",
    "pub_date": "2022-05-03T04:02:57Z",
    "platforms": {
        "win64": {
            "signature":"...",
            "url":"..."
        }
    }
}
```
 
Or, if the quotes are escaped, the updater won't work:

```
{
    "name": "v0.2.0",
    "notes": "This \'word\' won't display with quotes around it",
    "pub_date": "2022-05-03T04:02:57Z",
    "platforms": {
        "win64": {
            "signature":"...",
            "url":"..."
        }
    }
}
```

### Expected behavior

I figured single quotes inside double quotes would work fine as-is, and when they didn't appear, I tried escaping them. 

### Platform and versions

```shell
$ yarn tauri info
yarn run v1.22.17
$ tauri info

Operating System - Windows, version 10.0.19044 X64
Webview2 - 101.0.1210.32
Visual Studio Build Tools:
   - Visual Studio Build Tools 2019
   - Visual Studio Community 2019

Node.js environment
  Node.js - 16.9.0
  @tauri-apps/cli - 1.0.0-rc.6
  @tauri-apps/api - 1.0.0-rc.3

Global packages
  npm - 7.22.0
  pnpm - Not installed
  yarn - 1.22.17

Rust environment
  rustup - 1.24.3
  rustc - 1.60.0
  cargo - 1.60.0
  toolchain - stable-x86_64-pc-windows-msvc

App directory structure
/.vscode
/build
/node_modules
/public
/scripts
/src
/src-tauri

App
  tauri - 1.0.0-rc.4
  tauri-build - 1.0.0-rc.4
  tao - 0.6.4
  wry - 0.13.3
  build-type - bundle
  CSP - unset
  distDir - ../build
  devPath - http://localhost:3000/
  framework - Svelte
  bundler - Rollup
```

**Comment by amrbashir** [comment]
Looks like we are escaping single and double quotes but I don't know why https://github.com/tauri-apps/tauri/blob/715cbde3842a916c4ebeab2cab348e1774b5c192/core/tauri/src/updater/mod.rs#L851-L852

**Comment by lemarier** [comment]
> Looks like we are escaping single and double quotes but I don't know why
> 
> https://github.com/tauri-apps/tauri/blob/715cbde3842a916c4ebeab2cab348e1774b5c192/core/tauri/src/updater/mod.rs#L851-L852

Would worth testing the alert dialog to see if it works with the `'`, IIRC they were issues, but it was 2 years ago, lot of stuff changed since

**Comment by amrbashir** [comment]
on Windows, it is possible to use `'` and `"`, just tested and didn't encounter any issue.
