### ISSUE TITLE
[bug] http api timeout doesn't work

### ISSUE THREAD

**Issue by qu1ck** [tauri-apps/tauri#4050]
### Describe the bug

Timeout value passed as parameter in HttpOptions has no effect.

### Reproduction

```js
    var client = await http.getClient(
        { connectTimeout: 2, maxRedirections: 3 });
    var response = await client.get(
        "https://httpstat.us/200?sleep=9000",
        {responseType: ResponseType.Text, timeout: 2});
```

### Expected behavior

The request times out

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 101.0.1210.32
  › MSVC:
      - Visual Studio Community 2019
  › Node.js: 16.14.2
  › npm: 8.5.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.59.0
  › cargo: 1.59.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.9
  › @tauri-apps/api [NPM]: 1.0.0-rc.4
  › tauri [RUST]: git+https://github.com/tauri-apps/tauri.git?rev=eaf9e5a#eaf9e5a9a6c0959be46d2969a423ef7689ea9225 (1.0.0-rc.8),
  › tauri-build [RUST]: 1.0.0-rc.7,
  › tao [RUST]: 0.8.3,
  › wry [RUST]: 0.15.1,
```

**Comment by lucasfernog** [comment]
I just tested with both client options and it worked fine:
`Network Error: error sending request for url (https://httpstat.us/200?sleep=9000): operation timed out: error sending request for url (https://httpstat.us/200?sleep=9000): operation timed out: operation timed out`
`Network Error: Io Error: timed out: Io Error: timed out`

Did you configure httpstat's URL in your HTTP scope? I can reopen this issue if you can provide a minimal repro for this.

**Comment by qu1ck** [comment]
Yes, I have all urls allowed and I get a 200 response after 9 seconds, no errors at all.
Let me try to put together minimal repro.

**Comment by qu1ck** [comment]
[httptimeoutrepro.zip](https://github.com/tauri-apps/tauri/files/8628445/httptimeoutrepro.zip)
@lucasfernog Here is minimal repro.

**Comment by lucasfernog** [comment]
This is what I see in the inspector on macOS:
`Unhandled Promise Rejection: Network Error: Io Error: timed out: Io Error: timed out`.

**Comment by lucasfernog** [comment]
If this is a windows-only issue i'll remove the http api entirely 😂

**Comment by qu1ck** [comment]
I see a 200 response :|

**Comment by lucasfernog** [comment]
Can you try with enabling the `reqwest-client` feature?

```toml
# src-tauri/Cargo.toml
[dependencies]
tauri = { git = "...", features = ["reqwest-client", "..."] }
```

**Comment by qu1ck** [comment]
`Network Error: error sending request for url (https://httpstat.us/200?sleep=9000): operation timed out`
That works.

**Comment by lucasfernog** [comment]
I can confirm attohttpc timeout isn't working on Windows omg 😂

**Comment by lucasfernog** [comment]
https://github.com/sbstp/attohttpc/issues/118

**Comment by lucasfernog** [comment]
attohttpc is still fixing the issue, so i'll just make a change to set `read_timeout` to fix this on Windows.
