### ISSUE TITLE
[bug] new WebviewWindow(xxx) return invalid window

### ISSUE THREAD

**Issue by cjdxhjj** [tauri-apps/tauri#4066]
### Describe the bug

my link component is 
![image](https://user-images.githubusercontent.com/5616997/167139414-ab057b41-b89b-4e70-b8b1-64cb80ca92c2.png)
i want open the link maximized
new WebviewWindow(this.label, {maximized: true, title: this.title, url: this.href });
i found the window at normal size at first, and then the window maximized, that cause splash screen
i adjust the api to
`
let wnd = new WebviewWindow(this.label, {maximized: true, title: this.title, url: this.href, visible: false });
wnd.show();
`
when i click the a link, the windows dosn't appear, and the console log a error

### Reproduction

click the link, the console log a error, the click the link again, the window appear maximized when click once

### Expected behavior

the window appear maximized only click once

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 101.0.1210.32
  › MSVC:
      - Visual Studio Professional 2022
  › Node.js: 14.18.2
  › npm: 6.14.15
  › pnpm: Not installed!
  › yarn: 1.22.15
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.9
  › @tauri-apps/api [NPM]: 1.0.0-rc.3

App
  › framework: Vue.js (Vue CLI)
  › bundler: Webpack

App directory structure
  ├─ .git
  ├─ dist
  ├─ node_modules
  ├─ public
  └─ src
```

**Comment by cjdxhjj** [comment]
i have to rewrite my code to

![image](https://user-images.githubusercontent.com/5616997/167139276-9b7b3e84-74b0-41f6-94bb-b05341c41898.png)

**Comment by cjdxhjj** [comment]
i guess the js api call to new window have a delay when the window actual created, the window have to registed to the window manager, but the js immediate returned, the show method find the window by label and then show it, i decide to write a command to open the window, that may solve my problem, but i dosn't find a way to get the app instance the create window api need.
![image](https://user-images.githubusercontent.com/5616997/167140559-c44d50aa-3e17-455b-af27-bc03cb0d170d.png)
![image](https://user-images.githubusercontent.com/5616997/167140856-cd68d30d-cc00-4057-b608-be8d01310643.png)

**Comment by lucasfernog** [comment]
This is by design, all API interactions are async and the WebviewWindow constructor is not. You can use the events to show the webiew when it is ready:

```javascript
    var webviewWindow = new WebviewWindow(Math.random().toString().replace('.', ''))
      webviewWindow.once('tauri://created', function () {
        webviewWindow.show()
      })
      webviewWindow.once('tauri://error', function (e) {
        console.error(e)
      })
 ```

**Comment by cjdxhjj** [comment]
is there any way to access the app instance in the command?
