### ISSUE TITLE
[bug] unable to install tauri-cli

### ISSUE THREAD

**Issue by s4093120** [tauri-apps/tauri#4068]
### Describe the bug

Im trying to install Tauri-CLI via cargo and get this error
![image](https://user-images.githubusercontent.com/62601155/167231562-bc75e0cc-a12b-48cc-90be-04cbda0df9c8.png)

### Platform and versions

```shell
Can't run this cause i can't install it
```

**Comment by lucasfernog** [comment]
Can you try it this way? `cargo install tauri-cli --locked --version "^1.0.0-rc"`

**Comment by s4093120** [comment]
Thank you it worked
