### ISSUE TITLE
open the window with initial maximized appear splash screen

### ISSUE THREAD

**Issue by cjdxhjj** [tauri-apps/tauri#4071]
This is by design, all API interactions are async and the WebviewWindow constructor is not. You can use the events to show the webiew when it is ready:

```javascript
    var webviewWindow = new WebviewWindow(Math.random().toString().replace('.', ''))
      webviewWindow.once('tauri://created', function () {
        webviewWindow.show()
      })
      webviewWindow.once('tauri://error', function (e) {
        console.error(e)
      })
 ```

_Originally posted by @lucasfernog in https://github.com/tauri-apps/tauri/issues/4066#issuecomment-1119629802_

**Comment by cjdxhjj** [comment]
i have modify my code to the above, the splash screen appear again.
when i delay a short time, the splash screen disappear.
![image](https://user-images.githubusercontent.com/5616997/167246189-50530c58-2c9c-471d-9f9f-b08240c89417.png)
i'm consider open the window by custom command, how to access the app instance in the command handler?

**Comment by lucasfernog** [comment]
I couldn't really understand the issue here, maybe you could include a minimal repro for us.

You can access the app instance in the command handler by adding an `app: tauri::AppHandle` argument to the command function. It will be injected by Tauri for you.

**Comment by cjdxhjj** [comment]
thanks very much. my problem is the window maximized when window created, but the content is a small rectangle at first, and then it maximized , that cause the splash screen

**Comment by cjdxhjj** [comment]
![cccvv](https://user-images.githubusercontent.com/5616997/167325231-5263c890-6454-4e6a-9f7e-75e78bbc964d.gif)
