### ISSUE TITLE
[bug] Unable to install System Dependencies

### ISSUE THREAD

**Issue by AshutoshSajan** [tauri-apps/tauri#4076]
### Describe the bug

Unable to install System Dependencies

### Reproduction

`sudo apt update && sudo apt install libwebkit2gtk-4.0-dev \
    build-essential \
    curl \
    wget \
    libssl-dev \
    libgtk-3-dev \
    libappindicator3-dev \
    librsvg2-dev
`

_**Error message**_

The following packages have unmet dependencies:
 libgtk-3-dev : Depends: libpango1.0-dev (>= 1.41) but it is not going to be installed
 libwebkit2gtk-4.0-dev : Depends: libwebkit2gtk-4.0-37 (= 2.32.4-0ubuntu0.20.04.1) but 2.34.1-0ubuntu0.20.04.1 is to be installed
                         Depends: gir1.2-webkit2-4.0 (= 2.32.4-0ubuntu0.20.04.1) but 2.34.1-0ubuntu0.20.04.1 is to be installed
                         Depends: libsoup2.4-dev (>= 2.40) but it is not going to be installed
                         Depends: libjavascriptcoregtk-4.0-dev (= 2.32.4-0ubuntu0.20.04.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

### Expected behavior

System Dependencies should get installed

### Platform and versions

```shell
.-/+oossssoo+/-.               ashu@Ashu 
        `:+ssssssssssssssssss+:`           --------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.3 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: TUF Gaming FX505DT_FX505DT 1.0 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.11.0-41-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 2 hours, 25 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2723 (dpkg) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: zsh 5.8 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: Plasma 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: KWin 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: McMojave 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: McMojave [Plasma], Breeze [GTK3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: McMojave-circle-dark [Plasma], McMojave-circle-dark [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: konsole 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      Terminal Font: DroidSansMono Nerd Font 14 
    .ossssssssssssssssssdMMMNysssso.       CPU: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx (8) @ 2.100GHz 
      -+sssssssssssssssssyyyssss+-         GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q 
        `:+ssssssssssssssssss+:`           GPU: AMD ATI 05:00.0 Picasso 
            .-/+oossssoo+/-.               Memory: 5361MiB / 15435MiB
```

**Comment by FabianLars** [comment]
Well, this looks like a problem with your (specific) system. No idea how to help you here 🤔

**Comment by AshutoshSajan** [comment]
`sudo aptitude install <packagename>`
This fixed it for me by downgrading the versions of the packages. find more details [here](https://askubuntu.com/questions/223237/unable-to-correct-problems-you-have-held-broken-packages)

**Comment by cosmic-zip** [comment]
> `sudo aptitude install <packagename>` This fixed it for me by downgrading the versions of the packages. find more details [here](https://askubuntu.com/questions/223237/unable-to-correct-problems-you-have-held-broken-packages)

This solve my problem, I'm also using ubuntu 22.04.
