### ISSUE TITLE
[docs] Update the Code of Conduct version

### ISSUE THREAD

**Issue by FahimFBA** [tauri-apps/tauri#4081]
The project is currently using the Code of Conduct adapted from [Contributor Covenant](http://contributor-covenant.org/), version 1.0.0 which is outdated. The latest one is [v2.1](https://www.contributor-covenant.org/). 

Please let me know whether you want to update to the latest version as I might be able to add a PR for that.

**Comment by nothingismagick** [comment]
That would be fabulous, looking forward to the PR
