### ISSUE TITLE
[bug] Submenu accelerators nonfunctional

### ISSUE THREAD

**Issue by kotx** [tauri-apps/tauri#4085]
### Describe the bug

Not sure if this was an intended feature. If it wasn't, we might want to move it to a feature request.
But essentially:
Currently, prefixing a menu item with `&` should/will create a mnemonic/accelerator for it similar to [how Electron does it](https://github.com/electron/electron/blob/main/docs/api/menu.md#menusetapplicationmenumenu). It looks like this:
![image](https://user-images.githubusercontent.com/33439542/167323128-1526e324-a428-49ef-b0fb-abd404d7a929.png)

However, with Tauri, although this underline appears, pressing the buttons (Alt+F) doesn't actually open the submenu. It could be that this is unimplemented, or a bug.

### Reproduction

Create a menu like:
```rs
let menu = Menu::with_items([
        Submenu::new("&File".to_string(), file_menu).into(),
]);
tauri::Builder::default()
        .menu(menu)
        // ...
```
Open it (on Windows) and try to press `Alt+F`. Notice the underline but failure to open the submenu. 

### Expected behavior

In this example, the keyboard combination Alt+F should open the File submenu.

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.22610 X64
  › Webview2: 101.0.1210.39
  › MSVC: 
      - Visual Studio Build Tools 2017
      - Visual Studio Community 2022
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: 7.0.1
  › yarn: 1.22.15
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.10
  › @tauri-apps/api [NPM]: 1.0.0-rc.5
  › tauri [RUST]: 1.0.0-rc.9,
  › tauri-build [RUST]: 1.0.0-rc.8,
  › tao [RUST]: 0.8.4,
  › wry [RUST]: 0.16.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/

App directory structure
  ├─ .git
  ├─ node_modules
  ├─ src
  └─ src-tauri
```

**Comment by lucasfernog** [comment]
We don't have accelerators for menus, only for items (see https://docs.rs/tauri/1.0.0-rc.10/tauri/struct.CustomMenuItem.html#method.accelerator).

**Comment by amrbashir** [comment]
This doesn't need any special handling on our side. Top-level menus that have `&` should automatically have an accelerator of `Alt+<Char after &>` just like Electron. It is not documented though.

Why doesn't it work for you? because of this https://github.com/tauri-apps/wry/issues/451, it is a bug in Webview2 and we are waiting for microsoft to fix it. Subscribe to the wry issue to get notified of any progress.

**Comment by nanodeath** [comment]
@amrbashir btw this seems to also not be working in Linux:

![image](https://user-images.githubusercontent.com/10625/206233630-d68dd8b8-d99f-4082-99fe-be31605746c3.png)

**Comment by amrbashir** [comment]
@nanodeath thanks for the report, this will be fixed in the next release

**Comment by nanodeath** [comment]
Hm, just updated to [1.2.2](https://github.com/tauri-apps/tauri/releases/tag/tauri-v1.2.2), which just dropped:

```
Updating tauri v1.2.1 -> v1.2.2
Updating tauri-runtime-wry v0.12.1 -> v0.12.2
Updating wry v0.22.6 -> v0.23.1
```

and still seeing

![image](https://user-images.githubusercontent.com/10625/206493727-9085158a-81a4-43e3-9886-3b39bca3cb09.png)

Code:

```rust
    let file_menu = Submenu::new("&File", Menu::new()
```

I'm on Zorin OS 16.2 (an Ubuntu derivative).

Going to assume you meant "next next release" for now :slightly_smiling_face:

**Comment by FabianLars** [comment]
It will be available in the next [tao](https://github.com/tauri-apps/tao) version which should hopefully be available via `cargo update` once it's released without a new tauri version.

**Comment by nanodeath** [comment]
Thanks @FabianLars (and @amrbashir). Helps to know which repo to look at, for sure. For cross-referencing purposes, the relevant commit appears to be this: https://github.com/tauri-apps/tao/commit/86a439edc5da2bd1baa1067831dde2408fd14fbf.

**Comment by nanodeath** [comment]
Still broken even with tao 0.15.8.

![image](https://user-images.githubusercontent.com/10625/208136492-209ab75c-631e-40a5-b52a-f957c16ac3cd.png)

**Comment by amrbashir** [comment]
@nanodeath thanks for reporting back, I seem to have missed fixing submenus in the previous fix. Opened a PR https://github.com/tauri-apps/tao/pull/650 so expect a new patch soon.

**Comment by blindwiz** [comment]
so this is 2025, I'm running tauri v2.8.5.  has this been fixed? I still can't get my menus to activate by using a alt + <letter> shortcut like for file alt+f.

**Comment by YurikoDX** [comment]
> so this is 2025, I'm running tauri v2.8.5. has this been fixed? I still can't get my menus to activate by using a alt + shortcut like for file alt+f.

My code: [https://github.com/YurikoDX/listen-to-events-in-leptos/blob/efb2f38eaf476cb7ef6de7fd72eafda50e3e5445/src-tauri/src/lib.rs](url)
I found that it works on Arch Linux. I can press `Alt+F` to open the File menu and then press `O` to trigger Open. I can also use `Alt+C/P` to trigger the predefined shortcuts.
However, on Windows 11 24H2, I can only see an underline appear under `F` and `E` when I press `Alt`, but I can't perform any further actions. `Alt+C/P` also don't work.
By the way this tauri_plugin_global_shortcut [https://github.com/YurikoDX/local-manga-reader/blob/3f842cc296980c7365f1dfe01b70e9876fd20b4b/src-tauri/src/lib.rs#L323-L347](url) works on both windows and arch linux.

Updata:
In fact, it does work on Windows, but you need to press `Alt` and then release it immediately, and then press `F` and then `O`. Even the `Alt+C/P` that I set up requires opening the dropdown menu first. I don't know why this is the case. (The cursor only supports holding down `Alt`, but VSCode supports both operations.)
