### ISSUE TITLE
How to listen the native quit event?

### ISSUE THREAD

**Issue by PuffMeow** [tauri-apps/tauri#4086]
### Describe the bug

I can't find any related introduction in the document.
What I want to do is when the user click the native quit button on the right top, I can listen the event to do something.

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 101.0.1210.39
  › MSVC: 
      - Visual Studio ���ɹ��� 2019
      - Visual Studio 15 ���ɹ��� 2017
  › Node.js: 16.13.0
  › npm: 8.6.0
  › pnpm: 7.0.0
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.9(outdated, latest: 1.0.0-rc.10)
  › @tauri-apps/api [NPM]: 1.0.0-rc.4(outdated, latest: 1.0.0-rc.5)
  › tauri [RUST]: 1.0.0-rc.8,
  › tauri-build [RUST]: 1.0.0-rc.7,
  › tao [RUST]: 0.8.4,
  › wry [RUST]: 0.15.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: React
```

**Comment by FabianLars** [comment]
In javascript you can listen to the `tauri://close-requested` event. Listening to it should automatically prevent the window from closing.
In rust you need to use `RunEvent`, example: https://github.com/tauri-apps/tauri/blob/dev/examples/api/src-tauri/src/main.rs#L225-L254

(Note that some interactions like CMD+Q on macOS may not trigger the close-requested event, not sure right now)

**Comment by PuffMeow** [comment]
> In javascript you can listen to the `tauri://close-requested` event. Listening to it should automatically prevent the window from closing. In rust you need to use `RunEvent`, example: https://github.com/tauri-apps/tauri/blob/dev/examples/api/src-tauri/src/main.rs#L225-L254
> 
> (Note that some interactions like CMD+Q on macOS may not trigger the close-requested event, not sure right now)

Thanks. It can help.
