### ISSUE TITLE
[bug] dialog.open + multiple + directory can only return one directory

### ISSUE THREAD

**Issue by martpie** [tauri-apps/tauri#4091]
### Describe the bug

```
const selectedFolders = await dialog.open({
    directory: true,
    multiple: true,
});
```

only allows you to select a single directory.

https://user-images.githubusercontent.com/1311607/167462124-40b208e7-a73c-4b11-99d2-c1913a30c259.mov

### Reproduction

1. Create a tauri app with create react-app
2. Enable `dialog` in tauri config
3. Use the following code as component:

```tsx
import React, { useCallback, useState } from 'react';
import * as dialog from '@tauri-apps/api/dialog';

const Root: React.FC = () => {
  const [folders, setFolders] = useState<string[]>([]);

  const onOpen = useCallback(async () => {
    const selectedFolders = await dialog.open({
      directory: true,
      multiple: true,
    });

    if (selectedFolders === null) {
      setFolders([]);
    } else if (typeof selectedFolders === 'string') {
      setFolders([selectedFolders]);
    } else {
      setFolders(selectedFolders);
    }
  }, []);

  return (
    <>
      <button onClick={onOpen}>Open folder</button>
      <br />
      {folders.join(',')}
    </>
  );
};

export default Root;
```

4. Launch app, click on button, try to to open multiple directories

### Expected behavior

It should allow the user to select multiple directories at once :] 

### Platform and versions

```shell
Environment
  › OS: Mac OS 12.3.1 X64
  › Node.js: 18.0.0
  › npm: 8.6.0
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: Not installed!
  › rustc: 1.59.0
  › cargo: 1.59.0
  › Rust toolchain:

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.10
  › @tauri-apps/api [NPM]: 1.0.0-rc.5
  › tauri [RUST]: 1.0.0-rc.9,
  › tauri-build [RUST]: 1.0.0-rc.8,
  › tao [RUST]: 0.8.4,
  › wry [RUST]: 0.16.0,

App
  › build-type: bundle
  › CSP: default-src 'none'; img-src 'self' data:; media-src 'self'; child-src 'self'; object-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://api.github.com; font-src 'self' data:
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ build
  ├─ .git
  └─ src
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by FabianLars** [comment]
The [dialog upstream crate](https://docs.rs/rfd/latest/rfd/) doesn't support this.
But honestly, i've never seen a file picker that allows picking multiple directories (at least on Windows&Linux, never used macOS) 🤔

**Comment by martpie** [comment]
I come from Electron, and their their `dialog` module supports it, but I will double check on Windows and Linux.

Opening a feature request upstream should probably be the best then, thanks for the pointer!

**Comment by martpie** [comment]
@FabianLars `rfd` implemented it upstream (https://github.com/PolyMeilex/rfd/commit/ac1217a92ed1e518759f8787c36a02b110289fb2), I'll keep this open until a new `rfd` release is released.

This should hopefully work out of the box without any change to Tauri!

**Comment by betamos** [comment]
Unfortunately it won't work out of the box -- the API is designed with fn names, not boolean params. I'm working on a PR.
