### ISSUE TITLE
[docs] Add some mentions about the build script that package the icons.

### ISSUE THREAD

**Issue by langyo** [tauri-apps/tauri#4097]
Reference on #3941 

I tried to remove and rename the default icons from Tauri's application creator(`tauri-app`), but then the compiler throw an exception about the icon.

I've tried to rewrite the build script in `build.rs`, then make a new icon in a new dictionary `res`, and it looks well.

```rust
use tauri_build::{try_build, Attributes, WindowsAttributes};

fn main() {
  if let Err(error) = try_build(
    Attributes::new()
      .windows_attributes(WindowsAttributes::new().window_icon_path("res/icon.ico")),
  ) {
    panic!("Error: {}", error);
  }
}
```

We usually need to provide an icon to compiler to build the program, but Tauri's document didn't give the information about it. I think it should be mentioned in the document.

**Comment by lucasfernog** [comment]
This was improved in #4115 but we could improve documentation for tauri-build indeed. can you file an issue in the tauri-docs repo? Thanks!

**Comment by hrenx** [comment]
command `pnpm tauri dev`

```--- stderr
  thread 'main' panicked at 'Error: `res/icon.ico` not found; required for generating a Windows Resource file during tauri-build', build.rs:8:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by langyo** [comment]
> command `pnpm tauri dev`
> 
> ```
>   thread 'main' panicked at 'Error: `res/icon.ico` not found; required for generating a Windows Resource file during tauri-build', build.rs:8:9
>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

你是否有遗漏在对应的位置添加图标文件？由于打包器的接口要求，目前图标仍然是是不能缺的，必须好歹有个占位的图标放着

**Comment by 107295472** [comment]
stable-x86_64-pc-windows-gnu  Does it have to be msvc?

**Comment by Eric-Arz** [comment]
> stable-x86_64-pc-windows-gnu Does it have to be msvc?

This is the wrong question. Should a framework like Trauri  that aims to be a cross platform solution for desktop development fail to build with msvc?

**Comment by daguanren21** [comment]
> > command `pnpm tauri dev`
> > ```
> >   thread 'main' panicked at 'Error: `res/icon.ico` not found; required for generating a Windows Resource file during tauri-build', build.rs:8:9
> >   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > ```
> 
> 你是否有遗漏在对应的位置添加图标文件？由于打包器的接口要求，目前图标仍然是是不能缺的，必须好歹有个占位的图标放着
![image](https://user-images.githubusercontent.com/56297137/229325676-59763257-2ee0-4966-8005-5cddf352072e.png)
 still exist error ,why? node version :16.11.0

**Comment by langyo** [comment]
> > > command `pnpm tauri dev`
> > > ```
> > >   thread 'main' panicked at 'Error: `res/icon.ico` not found; required for generating a Windows Resource file during tauri-build', build.rs:8:9
> > >   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > > ```
> > 
> > 
> > 你是否有遗漏在对应的位置添加图标文件？由于打包器的接口要求，目前图标仍然是是不能缺的，必须好歹有个占位的图标放着
> > ![image](https://user-images.githubusercontent.com/56297137/229325676-59763257-2ee0-4966-8005-5cddf352072e.png)
> > still exist error ,why? node version :16.11.0

首先这与 NodeJS 没有任何关系，所有打包行为均在纯粹由 Rust 构建的工具链进行

把路径改为`src-tauri/res/icon.ico`试试

或者确保你在命令行的工作目录为`chat-app/src-tauri`而非项目根目录`chat-app`，打包器似乎会直接通过 cargo 命令执行时所在的工作目录搜寻图标文件
