### ISSUE TITLE
Does the WebView runtime use js?

### ISSUE THREAD

**Issue by d1y** [tauri-apps/tauri#41]
What I want to know is that if you use `webview` , it's actually a browser, just a smaller shell (compared with `electron'), then I'll build a `html `file + `js` file for interaction (`rust' interface).

Or `rs` to build the logical layer

Chestnut

```html
<html>
<body>
<button id="btn"> </button>
</body>
</html>
```

```js
document. getByElementById ('btn'). onClick ('alert ('xx'))
```

Is that so? So `rust` just means that interfaces like operating file systems are provided at the bottom?

**Comment by tensor-programming** [comment]
You can build anything you want with HTML/JS/CSS and deploy it with Tauri/Webview.  Like you said, its mainly just a browser with a smaller shell then Electron.  The Rust code in Tauri acts kind of like a JavaScript bridge between the webview and the application.  You can see examples over at this repo: https://github.com/tauri-apps/smoke-tests

You could also in use Rust to build your application if you wanted to use Web Assembly though that feature is experimental.  Ideally, we will eventually have some kind of modular setup that will allow the user to chose which modules they want to use for their application.

**Comment by d1y** [comment]
> You can build anything you want with HTML/JS/CSS and deploy it with Tauri/Webview. Like you said, its mainly just a browser with a smaller shell then Electron. The Rust code in Tauri acts kind of like a JavaScript bridge between the webview and the application. You can see examples over at this repo: https://github.com/tauri-apps/smoke-tests
> 
> You could also in use Rust to build your application if you wanted to use Web Assembly though that feature is experimental. Ideally, we will eventually have some kind of modular setup that will allow the user to chose which modules they want to use for their application.

Aesome, My understanding is that in the future it may be nesting `rs'files in `html' files.



```html

<script src="fs.rs" type="rust-lang"> </script>

```

Is it?

**Comment by d1y** [comment]
> You can build anything you want with HTML/JS/CSS and deploy it with Tauri/Webview. Like you said, its mainly just a browser with a smaller shell then Electron. The Rust code in Tauri acts kind of like a JavaScript bridge between the webview and the application. You can see examples over at this repo: https://github.com/tauri-apps/smoke-tests
> 
> You could also in use Rust to build your application if you wanted to use Web Assembly though that feature is experimental. Ideally, we will eventually have some kind of modular setup that will allow the user to chose which modules they want to use for their application.


Personally, I feel that it's contrary to what I feel. Can I have a new file suffix name (i.e. `rust'back-end to compile): .rtml

And hopefully it's a template form, like EJS

**Comment by nothingismagick** [comment]
`<script src="fs.rs" type="rust-lang"> </script>` => that will probably never be a thing - and perhaps your confusion has a little bit to do with the fact that we haven't released the documentation yet. From the forthcoming docs:

> Tauri is a polyglot system for building apps. It uses NodeJS to scaffold an HTML/JS rendering Window as a User Interface that is bootstrapped and managed by Rust. The final product is a monolithic binary that can be distributed as common file-types for Windows (exe/msi), Linux (deb/appimage) and Macintosh (app/dmg).

You can write the html/js/css in whatever templating language or flavour you want, as long as its transpiled down to HTML/JS/CSS before shipping. We are trying to stay agnostic. If you want to actually write your interface and everything in rust, then Tauri probably isn't for you. You should check out Yew, for example.

Hope that answers your question.

**Comment by nothingismagick** [comment]
And just to help you understand with regard to your initial question:

You can send a message to Rust like this:
```js
    pingToRust () {
      tauri.invoke({ cmd: 'myCustomCommand', argument: 'thing' })
    },
```

Which, in this contrived example will then write `thing` on the Rust CLI (because at the moment there is a command called "MyCustomCommand" that Tauri is shipping with, all it does is write what it is passed to STDOUT.)

You can also promisify the response in order to get a callback from Rust - and you can use Rust to direct the WebView - even injecting code that nulls itself upon promise resolution. Here is a screenshot from the docs (coming soon, I promise!)

![Screen Shot 2019-10-05 at 20 51 04](https://user-images.githubusercontent.com/35242872/66267572-b12c7380-e832-11e9-9d4e-b3f01354f28b.png)
