### ISSUE TITLE
[bug] youtube -> test drive download -> woah that is out of date

### ISSUE THREAD

**Issue by llaenowyd** [tauri-apps/tauri#4105]
### Describe the bug

Hi I was watching this Youtube vid - https://www.youtube.com/watch?v=UxTJeEbZX-0&ab_channel=TauriApps

There is a link in the description, it says:
> If you just want to take Tauri for a test-drive, we've uploaded a sample app for MacOS, Linux and Windows that you can download from Github here:
[https://github.com/tauri-apps/tauri/r...](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqblh6TnJENnp0dDZRTjQ1cDZPVFo2T2xKUC1Rd3xBQ3Jtc0tuR01wU3RuYTFLSjk5NERTaHgwSTcwSEt3YWxTVU51S2VwV1QzMm00ZC1GZ3l0MlNDU1pyWWdaMjdCVllaZ3NTbVlyQ2pIUkY0N1BTLWRMZFM3elR2U1FjRDVsem5fNFByclVKSlhheGhlcEZPN0JHaw&q=https%3A%2F%2Fgithub.com%2Ftauri-apps%2Ftauri%2Freleases%2Ftag%2F0.5.2-binaries&v=UxTJeEbZX-0)

Now that was a mistake from me, is I didn't notice at that link it says 

> @[nothingismagick](https://github.com/nothingismagick) nothingismagick released this May 21, 2020
 · [2047 commits(
https://github.com/tauri-apps/tauri/compare/0.5.2-binaries...dev)to dev since this release

Right so that's from 2 years ago. I continued being stupid by installing the Windows MSI.  It's pretty cool.  It seems to work fine.
 
![image](https://user-images.githubusercontent.com/41239783/167925856-4e463cb6-05a6-41f3-9559-259e4cbb0b51.png)

Trouble is it can't be uninstalled by the Windows add/remove apps in the control panel.

![image](https://user-images.githubusercontent.com/41239783/167926173-ff202241-2244-4b10-bb76-e53a7e957212.png)

I understand if somehow this can be interpreted as Windows fault. Perhaps one of the devs on the project had this exact same problem 2 years ago and could offer some advice how to uninstall this program.

Secondly I recommend if you feel inclined, perhaps change the link in the Youtube video description to a more updated release.

### Platform and versions

```shell
n/a, repro is self contained in `msi` file available via link above
```

**Comment by llaenowyd** [comment]
I found I can click "Ignore" to proceed past the dialog and then it does appear uninstalled.

Closing this but still the link in the Youtube vid could be updated - perhaps showcase some newer features!

**Comment by nothingismagick** [comment]
And this is why we stopped making tutorials until we land the stable 1.0 version. Sorry about that!!!
