### ISSUE TITLE
Encountered "due to access control checks." error when requesting on macos

### ISSUE THREAD

**Issue by CarbonPool** [tauri-apps/tauri#4113]
Works fine on windows, on macos I get this error:

`XMLHttpRequest cannot load https://xxxxxx due to access control checks.`

**Comment by lucasfernog** [comment]
Please do not delete the issue template, we need more information. Is this on dev or production? Did you try the same environment on both platforms? Ideally we need a minimal repro to check this, but it's probably a CORS issue or a wrong CSP.

**Comment by lucasfernog** [comment]
Closing due to lack of response. To bypass CORS we recommend our [http](https://tauri.app/v1/api/js/modules/http) API.

**Comment by primeagen-rustaceans** [comment]
@lucasfernog Facing the same issue in dev.
OS : Ubuntu 22.04
when making api call to http://127.0.0.1:3301/endpoint : it is giving 
XMLHttpRequest cannot load http://127.0.0.1:3301/endpoint due to access control checks.

I have the below http conf
"tauri": {
    "allowlist": {
      "all": false,
      "http": {
        "all": true, 
        "request": true
      }
    },
    "bundle": {
      "active": true,
      "category": "DeveloperTool",
      "copyright": "",
      "deb": {
        "depends": []
      },
      "externalBin": [],
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "identifier": "com.tauri.dev",
      "longDescription": "",
      "macOS": {
        "entitlements": null,
        "exceptionDomain": "",
        "frameworks": [],
        "providerShortName": null,
        "signingIdentity": null
      },
      "resources": [],
      "shortDescription": "",
      "targets": "all",
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "security": {
      "csp": null
    },
    "updater": {
      "active": false
    },
    "windows": [
      {
        "fullscreen": false,
        "height": 600,
        "resizable": true,
        "title": "project-name",
        "width": 800
      }
    ]
  }

**Comment by FabianLars** [comment]
@primeagen-rustaceans 
These kind of errors are typically caused by a server-side misconfiguration. Most of the time it's caused by the server not setting the `Access-Control-Allow-Origin` header (but a google/SO search will have a few more, less common? suggestions too).
If you can't modify the server you will have to use Tauri's http module as Lucas said.

**Comment by primeagen-rustaceans** [comment]
@FabianLars
Thanks, indeed the issue was at server end (`Access-Control-Allow-Origin` header was only getting set for pre-flight responses)

**Comment by kaush-13** [comment]
So i used the http api to bypass CORs and got my call to a http endpoint to work when running tauri dev. However as soon as i run tauri build and use that version, the calls no longer work. Any ideas what i need to do? @FabianLars @lucasfernog

**Comment by lucasfernog** [comment]
what's the error? try a debug build `tauri build --debug` to be able to see the web inspector, maybe that helps you visualize issues

**Comment by kaush-13** [comment]
I am getting 403 errors. My theory is that the remote server is expecting some headers that are being set by the browser while in dev but when run in production they aren't being set, is there a way to set headers using the http api in tauri v2? I tried setting them but when i look at the debug console i don't see them being set on the request @lucasfernog

**Comment by FabianLars** [comment]
the http plugin sets the Origin header to the webview's origin by default (can be disabled by setting it to an empty string iirc), and the origin is different in dev (whatever's in devUrl) and build (`tauri://localhost` / `http://tauri.localhost`). The other headers (if any) should be the same in both modes 🤔
