### ISSUE TITLE
Flutter [feat] 

### ISSUE THREAD

**Issue by dolphin54** [tauri-apps/tauri#4119]
### Describe the problem

Instead of react etc..., would love to have a flutter UI which i could use instead and package the whole lot as one exe.

### Describe the solution you'd like

Instead of react etc..., would love to have a flutter UI which i could use instead and package the whole lot as one exe.

### Alternatives considered

nativescript, but all the resources are still not packaged inside the exe.

**Comment by amrbashir** [comment]
Flutter has its own Desktop Application framework so you can use that directly, you don't need tauri.
