### ISSUE TITLE
[bug]  Hangs when native file opener is used

### ISSUE THREAD

**Issue by shirshak55** [tauri-apps/tauri#4120]
### Describe the bug

Tauri Hangs when we try to use native dailogs etc. I opened folder chooser to pick folder so that I can send path to renderer process. But Tauri hangs when we do so.

### Reproduction
```rs
#![cfg_attr(
    all(not(debug_assertions), target_os = "windows"),
    windows_subsystem = "windows"
)]

fn main() {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![get_user_folder_path])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[tauri::command]
fn get_user_folder_path() -> String {
    use native_dialog::FileDialog;
    println!("Show dialog");
    let path = FileDialog::new().show_open_single_dir();

    if let Ok(path_opt) = path {
        if let Some(path) = path_opt {
            let pth = path.to_string_lossy().into_owned();

            return pth;
        }
    }

    String::new()
}
```

On Js side call 
```js
  let a = await invoke("get_user_folder_path")
```

Tauri Hangs.

Also, the program run from CLI without any issue.

### Expected behavior

Tauri must not hang. And, even if it hangs it should clearly display the error. I don't even know how to debug such issue.

### Platform and versions

```shell
Windows

Tauri       "@tauri-apps/api": "^1.0.0-rc.5",


I did everything on March 13 so it must be the latest.
```

### Stack trace

```shell
There is no stack trace. It hangs...
```

### Additional context

Initially I had used windows crate from Microsoft directly. It hanged on this ` windows::Win32::UI::Shell::SHBrowseForFolderW(&lpbi);`

```rs
fn aaa() -> String {
    println!("Choosing folder");
    unsafe {
        let a = IFileDialog
        //let path_param = LPARAM(100);
        let lpbi = BROWSEINFOW {
            // lpszTitle: pcwstr_from("Pleasexxx choosexx folder"),
            ulFlags: BIF_RETURNONLYFSDIRS | BIF_NEWDIALOGSTYLE,
            // lParam: path_param,
            ..Default::default()
        };
        println!("ccc");
        dbg!(&lpbi);
        println!("ddd");
        let pidl = windows::Win32::UI::Shell::SHBrowseForFolderW(&lpbi);
        println!("aaaa");
        if pidl as isize == 0 {
            println!("bbb");
            return String::new();
        }
        let mut buf = [0 as u16; 260];
        SHGetPathFromIDListW(pidl, &mut buf);

        let a = String::from_utf16_lossy(&buf);
        println!("Sending string to tauri {}", a);
        a.trim_matches(char::from(0)).to_string()
    }
}
// fn pcwstr_from<'a>(t: impl IntoParam<'a, PCWSTR>) -> PCWSTR {
//     unsafe { t.into_param().abi() }
// }
```

I got up to ddd and it crashed.

**Comment by shirshak55** [comment]
I noticed that I am also unable to debug from windbg. If someone is having a similar issue let me know.  Tauri hangs when I try to hook process from windbg.

**Comment by lucasfernog** [comment]
You can open a file dialog using our API instead: https://tauri.studio/v1/api/js/modules/dialog

I tried your command on Windows and it worked. If you still have problems, please share a repository I can use to reproduce the issue.

**Comment by shirshak55** [comment]
@lucasfernog  the error is very spurious I guess. Maybe you were lucky?

I have uploaded a video to prove my point.

https://youtu.be/2MVNNGIGNug

**Comment by lucasfernog** [comment]
I tried it 10 times and it still didn't freeze (using the helloworld example). I'll need to see a full app for this. (also it'll just work if you use our API instead).

**Comment by shirshak55** [comment]
Closing this as tauri api is  workin perfectly.
