### ISSUE TITLE
Page control dragging fails

### ISSUE THREAD

**Issue by TheBlindM** [tauri-apps/tauri#4127]
### Describe the bug

The page control dragging fails, but it is possible to use it in the browser

https://user-images.githubusercontent.com/48701152/168418910-f5e15772-9412-42b4-a438-e1aabf549014.mp4

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.19043 X64
  › Webview2: 101.0.1210.39
  › MSVC:
      - Visual Studio ���ɹ��� 2019
  › Node.js: 16.13.2
  › npm: 8.1.2
  › pnpm: 6.32.4
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.10
  › @tauri-apps/api [NPM]: 1.0.0-rc.5
  › tauri [RUST]: 1.0.0-rc.10,
  › tauri-build [RUST]: 1.0.0-rc.8,
  › tao [RUST]: 0.8.4,
  › wry [RUST]: 0.16.2,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:8001/
  › framework: Vue.js

App directory structure
  ├─ .git
  ├─ .idea
  ├─ build
  ├─ mock
  ├─ node_modules
  ├─ public
  ├─ src
  ├─ src-tauri
  └─ types
```

**Comment by TheBlindM** [comment]
https://user-images.githubusercontent.com/48701152/168467288-4ad5132f-ef7e-46f0-8885-44fd1892a5b0.mp4

**Comment by TheBlindM** [comment]
Has no one encountered it?I'm using naive-ui (Vue) and the controls all work fine in the browser, but in
The drag property of the control in tauri is invalid

**Comment by TheBlindM** [comment]
NaiveUi and element-plus have tested the drag property in the component is not working

**Comment by FabianLars** [comment]
I think the problem here is that we don't really understand what you're talking about and the videos don't work either (for me).

But since you're talking about some kind of dragging. HTML5 Drag&Drop doesn't work if you have tauri's file drop enabled. So try disabling it via `"fileDropEnabled": false` in your window config in tauri.conf.json <https://tauri.studio/v1/api/config/#tauri.windows.fileDropEnabled>

**Comment by TheBlindM** [comment]
Yes, the video doesn't work, so I uploaded it twice, but it doesn't work either, you can download the video and you can play it。
I added FileDropenabled properties. The page control can already be dragged for thanks, but my control is not the File control is a tree -shaped control. If you are interested, you can take the video down. You happy
