### ISSUE TITLE
[docs] Improve `schema.json`

### ISSUE THREAD

**Issue by lorenzolewis** [tauri-apps/tauri#4139]
There are a few things in the schema that could be updated (based on https://github.com/tauri-apps/tauri-docs/pull/604). File for reference: https://github.com/tauri-apps/tauri/blob/dev/tooling/cli/schema.json

We should also be aware of any down-stream impacts and keep in mind increasing quality there (such as the VS Code extension). I'm willing to do this myself once I have some spare time 

- [x] "HttpAllowlistScope" description
- [x] Fix link in ShellAllowlistConfig.sidecar description
- [x] This should be marked as optional, not an array of types https://github.com/tauri-apps/tauri/blob/3e702cf8b15762cdca43c8d7ff6f6e8ee9670244/tooling/cli/schema.json#L409-L411
- [x] Escape brackets in description https://github.com/tauri-apps/tauri/blob/3e702cf8b15762cdca43c8d7ff6f6e8ee9670244/tooling/cli/schema.json#L653
- [x] These newlines cause an issue when rendering in a table, should be a break instead https://github.com/tauri-apps/tauri/blob/3e702cf8b15762cdca43c8d7ff6f6e8ee9670244/tooling/cli/schema.json#L408
- [x] This link is broken https://github.com/tauri-apps/tauri/blob/3e702cf8b15762cdca43c8d7ff6f6e8ee9670244/tooling/cli/schema.json#L1361

**Comment by lorenzolewis** [comment]
If someone could give me a bit of context in the meantime it would help (pointing me in the direction of how/where this is generated and any other downstream impacts such as the VS Code extension I should test out)

**Comment by lucasfernog** [comment]
The schema is generated using [schemars](https://docs.rs/schemars/latest/schemars/), you can see the usage in the structs on the [config source code](https://github.com/tauri-apps/tauri/blob/3e702cf8b15762cdca43c8d7ff6f6e8ee9670244/core/tauri-utils/src/config.rs#L1877). @lorenzolewis

**Comment by lucasfernog** [comment]
You can regenerate the schema by running `cargo build` in the `tooling/cli` folder. Just make any changes you wish, and you can verify how it looks on VS Code by opening `examples/api/src-tauri/tauri.conf.json` and hovering any of the fields.

**Comment by lucasfernog** [comment]
Since the schema is automated, we should probably do a post processing here for newlines and etc.
