### ISSUE TITLE
[feat] How to restore window in tauri?

### ISSUE THREAD

**Issue by halo-apps** [tauri-apps/tauri#4143]
### Describe the problem

How to restore window in tauri?

### Describe the solution you'd like

window.restore() is very useful when click SystemTray icon while the window is minimized.

**Comment by lucasfernog** [comment]
You can use the unminimize function: https://tauri.studio/v1/api/js/classes/window.WindowManager#unminimize
```typescript
import { appWindow } from '@tauri-apps/api/window'
appWindow.unminimize()
```

**Comment by halo-apps** [comment]
![image](https://user-images.githubusercontent.com/71301497/168708990-73d2be0e-39e3-4522-845b-a7549bb729d0.png)

I have already tried this, but it didn't work for me.
