### ISSUE TITLE
[bug] Missing script: "tauri"

### ISSUE THREAD

**Issue by haasal** [tauri-apps/tauri#4148]
### Describe the bug

When trying to use `npm run tauri info` I get:

```
npm ERR! Missing script: "tauri"
```

With `cargo tauri info` similar issue

`error: no such subcommand: tauri`

## Following [these](https://tauri.studio/v1/guides/getting-started/beginning-tutorial#1-start-a-new-tauri-project) instructions:

1. `npx create-tauri-app`
2. choose vue as frontend framework
3. select all default settings
4. `cd PROJECT_NAME`
5. `npm run tauri info`
6. get error

### Expected behavior

See regular *tauri info* output

### Platform and versions

```shell
Arch Linux: 5.17.5-arch1-1
rustup --version: 1.24.3
cargo.toml

[build-dependencies]
tauri-build = { version = "1.0.0-rc.6", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-rc.7", features = ["api-all"] }

As I can't run `tauri info` this is the best I can do
```

**Comment by amrbashir** [comment]
I guess you chose the vuecli recipe in `create-react-app` so you need to use `npm run tauri:serve` for development and `npm run tauri:build` for release build. 

For `tauri info`, you need to add a script in your package.json

```json
"scripts": {
  "tauri": "tauri"
}
```
then you can do `npm run tauri info`

**Comment by haasal** [comment]
Alright it worked thanks. It was a little confusing because[ in the manual ](https://tauri.studio/v1/guides/getting-started/beginning-tutorial) it said that you can skip everything until chapter 2 if you set up a new tauri project
