### ISSUE TITLE
[bug] cargo tauri segfault

### ISSUE THREAD

**Issue by sbeckeriv** [tauri-apps/tauri#4152]
### Describe the bug

No command works with cargo install. 

```
cargo tauri
Segmentation fault (core dumped)
```

### Reproduction

1 cargo install tauri-cli --locked --version "^1.0.0-rc"
2 cargo tauri

### Expected behavior

No segment fault

### Platform and versions

```shell
cargo tauri info

Environment
  › OS: Ubuntu 21.04 X64
  › Node.js: 16.10.0
  › npm: 7.24.0
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: 1.60.0-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.10
```

### Additional context

Wait! how did i run the info command if it doesnt work? 

I checked out the code and built it. the head didnt work however I randomly picked commit sha 353650ccd23d9437ce15c7c43732e1a0dc36a650  and build it with debug. I copied that to the cargo folder where cargo installed the other file.

I just checked the head commit d965b92174a1e6a01fc1a080254402d52145af1e 

tauri/tooling/cli$ cargo build
works

tauri/tooling/cli$ cargo run --release  
does not

**Comment by lucasfernog** [comment]
Any chance you could debug to see where the segfault is happening? I can't help since I don't see this on my Linux machine :/

**Comment by sbeckeriv** [comment]
Very sorry I did not see the reply. The build command has changed over the last few days. cargo run --release doesnt just run anymore. 

Good news is that the v1.0 release appears to work now.
