### ISSUE TITLE
[bug] `UpdateBuilder::target` weird behavior when specifying target

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri#4161]
### Describe the bug

These are the lines in question:
https://github.com/tauri-apps/tauri/blob/393c774dfd0d523bf10ceef2a03393640bf0f44d/core/tauri/src/updater/core.rs#L330-L340

Aside from being weird and hard to understand the section has a logic issue, that would potentially prevent the updater from finding the correct platform entry.

### Reproduction

Let's make an example to illustrate this:

I'm setting `UpdateBuilder::target` to `darwin-x86_64` even though my machines arch is `aarch64`.
This will cause the updater to fill out the url `https://example.com/{{target}}/{{arch}}` like so `https://example.com/darwin-x86_64/aarch64` which is absolutely not what I intended. 

It gets weirder though:
Let's also say I'm using the url parameters only for statistics and always return the `static JSON format`. 
In this situation the updater would download the `x86_64` artifact (like intended) **even though** it clearly announced to the update server that it's arch is `aarch64`.

### Expected behavior

given the target `darwin-x86_64`
`{{target}}` would get replaced with `darwin` and `{{arch}}` would be replaced by `x86_64`.

### Platform and versions

```shell
N/A
```

### Stack trace

```shell
N/A
```

**Comment by lucasfernog** [comment]
Tbh I think if you use the custom target option, you don't need the `{{arch}}`. Also I couldn't reproduce the issue where the updater looks for the wrong value in the JSON, since if a custom target is set we always use it:
```rust
let json_target = if has_custom_target { 
   target.clone() 
} ...
```
