### ISSUE TITLE
[bug] Failed build on arch: missing dependencies

### ISSUE THREAD

**Issue by good-praxis** [tauri-apps/tauri#4163]
Some packages might be present on the machine that pollute the `PATH` and which linuxdeploy picks over saver, and more importantly, present libraries, which might cause issues during the built of AppImage. Here is a collections of identified apps that might cause this behavior, and which packages need to be explicitly installed alongside them to make your builds pass on your dev machine.

### vmware
Requires:

- [libffi6](https://aur.archlinux.org/packages/libffi6) AUR 
- [libcroco](https://archlinux.org/packages/extra/x86_64/libcroco/) extra

### insync
Requires:

- [libffi6](https://aur.archlinux.org/packages/libffi6) AUR 
- [libselinux](https://aur.archlinux.org/packages/libselinux) AUR

---
I was running into some issues while building a default project, all relating to missing dependencies required by gtk on arch.

For context:
```
$ uname --all                                                                                                                                                        
Linux archlinux 5.17.8-arch1-1 #1 SMP PREEMPT Mon, 16 May 2022 20:45:27 +0000 x86_64 GNU/Linux
```

and my specific tauri info would be
``` 
yarn run v1.22.19
$ tauri info

Environment
  › OS: Arch Linux Rolling Release X64
  › Node.js: 18.2.0
  › npm: 8.9.0
  › pnpm: 6.11.0
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.10
  › @tauri-apps/api [NPM]: 1.0.0-rc.5
  › tauri [RUST]: 1.0.0-rc.10,
  › tauri-build [RUST]: 1.0.0-rc.8,
  › tao [RUST]: 0.8.4,
  › wry [RUST]: 0.16.2,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../public
  › devPath: http://localhost:8080/
  › framework: Svelte
  › bundler: Rollup

App directory structure
  ├─ public
  ├─ src
  ├─ .vscode
  ├─ src-tauri
  └─ node_modules

```

The built would fail during the run of `build_appimage.sh`

The missing packages were:
`libffi.so.6`, which had to be installed through AUR as `libffi6` as identified here: https://github.com/beeware/briefcase/issues/427 (the default `libffi` from the `core` repo is `libffi.so.8`)
`libcroco-0.6.so.3` was missing, which could be installed from `extra` as  `libcroco`

This was of course on top of the listed dependencies in the Arch tab at https://tauri.studio/v1/guides/getting-started/prerequisites

**Comment by good-praxis** [comment]
As you can see, I've opened a PR for the dependency in `extra`, but relying on an AUR dependency might be problematic and can't be done through `pacman` anyhow. thoughts?

**Comment by FabianLars** [comment]
I don't see why libcroco would be required at all and if so, why it wouldn't be installed by the other dependencies. We don't depend on it ourselves at all.
Something similar is true for libffi, nothing should require an older version of it than what's in the repos.

Apart from the quite big arch userbase, the team itself basically builds on arch daily and we never saw this issue once (i actually just tested a clean arch install last weekend while debugging a completely unrelated appimage issue).

So the only 2 things i can think of is a) _something_ about your system is/was broken or b) you're using some rust crate or whatever in your project that needs this. (or c) some package broke in the last 3 days 🤷)

**Comment by good-praxis** [comment]
Unless it's a system-wide crate,  I think it's safe to eliminate b) as I've also had the same error trying to build #2731

As for a) if anything, it might be my gtk, as that was the module it was at when it failed. And I will admit that I do get some minor warnings with gtk apps on my system, but that's just theme related: `(WebKitWebProcess:135134): Gtk-WARNING **: 20:46:08.976: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()`

I haven't customized this project and included external dependencies either, this is just the output of `yarn create tauri-app` with svelte

**Comment by good-praxis** [comment]
Here is the output of `yarn tauri build --verbose` without the dependencies above

```
[gtk/stdout] -- Deploying shared libraries -- 
[gtk/stdout] Deploying shared library /usr/lib/libgdk_pixbuf-2.0.so.0.4200.8
[gtk/stdout] Deploying dependencies for ELF file /usr/lib/libgdk_pixbuf-2.0.so.0.4200.8 
[gtk/stdout] Deploying shared library /usr/lib/libgdk_pixbuf-2.0.so
[gtk/stdout] Deploying dependencies for ELF file /usr/lib/libgdk_pixbuf-2.0.so 
[gtk/stdout] Deploying shared library /usr/lib/vmware/lib/libgdk_pixbuf-2.0.so.0/libgdk_pixbuf-2.0.so.0
[gtk/stdout] Deploying dependencies for ELF file /usr/lib/vmware/lib/libgdk_pixbuf-2.0.so.0/libgdk_pixbuf-2.0.so.0 
[gtk/stdout] Deploying shared library /usr/lib/vmware-installer/3.0.0/cdsHelper/lib/libgdk_pixbuf-2.0.so.0/libgdk_pixbuf-2.0.so.0
[gtk/stdout] Deploying dependencies for ELF file /usr/lib/vmware-installer/3.0.0/cdsHelper/lib/libgdk_pixbuf-2.0.so.0/libgdk_pixbuf-2.0.so.0 
[gtk/stdout] Deploying shared library /usr/lib/libgdk_pixbuf-2.0.so.0
[gtk/stdout] Deploying dependencies for ELF file /usr/lib/libgdk_pixbuf-2.0.so.0 
[gtk/stdout] Deploying shared library /usr/lib/vmware/lib/libgobject-2.0.so.0/libgobject-2.0.so.0
[gtk/stdout] Deploying dependencies for ELF file /usr/lib/vmware/lib/libgobject-2.0.so.0/libgobject-2.0.so.0 
[gtk/stdout] ERROR: Could not find dependency: libffi.so.6 
[gtk/stdout] ERROR: Failed to deploy library:  /usr/lib/vmware/lib/libgobject-2.0.so.0/libgobject-2.0.so.0 
ERROR: Failed to run plugin: gtk (exit code: 1) 
```

After installing `libffi6` from AUR this turns into
```
[gtk/stdout] Deploying shared library /usr/lib/vmware/lib/libgobject-2.0.so.0/libgobject-2.0.so.0
[gtk/stdout] Deploying dependencies for ELF file /usr/lib/vmware/lib/libgobject-2.0.so.0/libgobject-2.0.so.0 
[gtk/stdout] Deploying shared library /usr/lib/libffi.so.6
[gtk/stdout] Deploying shared library /usr/lib/libgobject-2.0.so.0.7200.1
[gtk/stdout] Deploying dependencies for ELF file /usr/lib/libgobject-2.0.so.0.7200.1 
[gtk/stdout] Deploying shared library /usr/lib/vmware-installer/3.0.0/cdsHelper/lib/libgobject-2.0.so.0/libgobject-2.0.so.0
[gtk/stdout] Deploying dependencies for ELF file /usr/lib/vmware-installer/3.0.0/cdsHelper/lib/libgobject-2.0.so.0/libgobject-2.0.so.0 
[gtk/stdout] Deploying shared library /usr/lib/libgobject-2.0.so
[gtk/stdout] Deploying dependencies for ELF file /usr/lib/libgobject-2.0.so 
[gtk/stdout] Deploying shared library /usr/lib/libgobject-2.0.so.0
[gtk/stdout] Deploying dependencies for ELF file /usr/lib/libgobject-2.0.so.0 
[gtk/stdout] Deploying shared library /usr/lib/libgio-2.0.so
[gtk/stdout] Deploying dependencies for ELF file /usr/lib/libgio-2.0.so 
[gtk/stdout] Deploying shared library /usr/lib/libgio-2.0.so.0
[gtk/stdout] Deploying dependencies for ELF file /usr/lib/libgio-2.0.so.0 
[gtk/stdout] Deploying shared library /usr/lib/vmware/lib/libgio-2.0.so.0/libgio-2.0.so.0
[gtk/stdout] Deploying dependencies for ELF file /usr/lib/vmware/lib/libgio-2.0.so.0/libgio-2.0.so.0 
[gtk/stdout] Deploying shared library /usr/lib/vmware-installer/3.0.0/cdsHelper/lib/libgio-2.0.so.0/libgio-2.0.so.0
[gtk/stdout] Deploying dependencies for ELF file /usr/lib/vmware-installer/3.0.0/cdsHelper/lib/libgio-2.0.so.0/libgio-2.0.so.0 
[gtk/stdout] Deploying shared library /usr/lib/libgio-2.0.so.0.7200.1
[gtk/stdout] Deploying dependencies for ELF file /usr/lib/libgio-2.0.so.0.7200.1 
[gtk/stdout] Deploying shared library /usr/lib/librsvg-2.so.2
[gtk/stdout] Deploying dependencies for ELF file /usr/lib/librsvg-2.so.2 
[gtk/stdout] Deploying shared library /usr/lib/librsvg-2.so.2.48.0
[gtk/stdout] Deploying dependencies for ELF file /usr/lib/librsvg-2.so.2.48.0 
[gtk/stdout] Deploying shared library /usr/lib/vmware/lib/librsvg-2.so.2/librsvg-2.so.2
[gtk/stdout] Deploying dependencies for ELF file /usr/lib/vmware/lib/librsvg-2.so.2/librsvg-2.so.2 
[gtk/stdout] ERROR: Could not find dependency: libcroco-0.6.so.3 
[gtk/stdout] ERROR: Failed to deploy library:  /usr/lib/vmware/lib/librsvg-2.so.2/librsvg-2.so.2 
ERROR: Failed to run plugin: gtk (exit code: 1) 
```

**Comment by good-praxis** [comment]
alright, so it appears that an orphaned `vmware` installation might pollute the build in a way that fails without the aforementioned dependencies. Just removing the `vmware` directories from `/usr/lib/vmware` made the build successful.

I don't think there is any way Tauri could account for that, right? I am just concerned because if I would have had any less experience, I'd have given up on Tauri on the failed build

**Comment by FabianLars** [comment]
> I don't think there is any way Tauri could account for that, right?

Nope and i don't think linuxdeploy / the gtk plugin can really do something here either (but then again, idk how that could happen in the first place so take that with a grain of salt).

Just another reason to drop appimages asap :/

**Comment by FabianLars** [comment]
Also i don't think this is tooo much of a problem because a) it seems to be a really rare thing and b) most users will probably build for linux on CI or VMs or something because of the "You need to build your app on the oldest system you want to support" thingy.

(Of course it's still bad if it fails in dev envs, i get that)

**Comment by good-praxis** [comment]
Then I can only hope this issue will be enough of a pointer for someone running into this until appimages are dropped :)

**Comment by lucasfernog** [comment]
Is this also the answer to #2731 ?

**Comment by good-praxis** [comment]
Not definitively, the logs provided there don't prove that that's the cause, and the error there is distinctly not "missing dependency" but "permission denied".

**Comment by Testare** [comment]
I have a similar bug occurring, apparently it is trying to copy the libraries from my insync package. I still use that program, so I don't think it's orphaned, or that I can just remove that directory? Is there a way to work around without deleting it?

**Comment by good-praxis** [comment]
I was able to reproduce that quickly, although I guess the only way to accommodate for that is to install the dependencies explicitly, `libffi.so.6` is available on AUR as [`libffi6`](https://aur.archlinux.org/packages/libffi6), after  which you will be missing `libsellinux.so.1` available as [`libselinux`](https://aur.archlinux.org/packages/libselinux) after which it will build.

I'll add this and the dependencies that might be needed when vmware is installed to the first post, and I encourage users who run into other instances of this to tell us about it and optimally also which extra dependencies are required.

We could raise this to linuxdeploy, _but I honestly don't know where that is_

**Comment by good-praxis** [comment]
Since we are keeping track of #2731 for troubleshoot guides, this one might also be a candidate? https://github.com/tauri-apps/tauri/issues/2731#issuecomment-1131635887

**Comment by Raduc4** [comment]
Has anyone solved this error on Arch Linux?
`ERROR: Could not find dependency: libicui18n.so.72`
```
pacman -Qi icu
Name            : icu
Version         : 73.2-2
```
