### ISSUE TITLE
H5 drag and drop is not supported in new webviewwindow

### ISSUE THREAD

**Issue by wesin** [tauri-apps/tauri#4168]
### Describe the bug

when i open a new webviewwindow in the main window. 
`const webview = new WebviewWindow(e.id, {
      url,
      center: true,
      width: 800,
      height: 600,
      title: e.name + '-实验设计',
      fileDropEnabled: false,
    });`

the webview cannot use h5 drag and drop.
the log in console "WARN wry::webview::webview2::file_drop: Error occured while processing dropped/hovered item: item is not a file.    "

the url in react code 
`
import React from 'react';
import { useState } from 'react';

const allModels = [
  {
    name: '哈哈',
  },
  {
    name: '呼呼',
  },
];

const sweets: string[] = [];
const App = () => {
  const [showSweets, setSweets] = useState<string[]>(sweets);
  // drag
  const onDragStart = (e: any) => {
    console.log('drag started', e);
    e.dataTransfer.setData('source', e.target.textContent);
  };

  const onDrop = async (e: any) => {
    console.log('drag drop', e);
    sweets.push(e.dataTransfer.getData('source'));
    setSweets([...sweets]);
  };

  const onDragOver = (e: any) => {
    e.preventDefault();
  };

  return (
    <div className="flex flex-row">
      <div
        className="flex flex-row flex-wrap content-start overflow-auto"
        style={{ height: 'calc(100vh - 64px)', flex: '0 0 160px' }}
      >
        {allModels.map((m) => {
          return (
            <div
              key={m.name}
              className="w-16 h-16 p-1 "
              draggable
              onDragStart={onDragStart}
            >
              <div className=" w-full h-full flex items-center justify-center rounded-xl  bg-yellow-500">
                {m.name}
              </div>
            </div>
          );
        })}
      </div>
      <div
        className="flex-auto bg-gray-400 flex flex-row flex-wrap justify-start items-start"
        onDragOver={onDragOver}
        onDrop={onDrop}
      >
        {sweets.map((s, index) => (
          <div key={index} className="m-5 w-20 h-20 bg-red-500">
            {s}
          </div>
        ))}
      </div>
    </div>
  );
};

export default App;
`

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 101.0.1210.47
  › MSVC: 
      - Visual Studio ���ɹ��� 2019
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.10
  › @tauri-apps/api [NPM]: 1.0.0-rc.5
  › tauri [RUST]: 1.0.0-rc.10,
  › tauri-build [RUST]: 1.0.0-rc.8,
  › tao [RUST]: 0.8.4,
  › wry [RUST]: 0.16.2,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:8080/
  › framework: React
  › bundler: Webpack

App directory structure
  ├─ .git
  ├─ .idea
  ├─ .vscode
  ├─ dist
  ├─ doc
  ├─ node_modules
  ├─ resources
  ├─ src
  └─ src-tauri
```

**Comment by rming** [comment]
maybe related https://github.com/tauri-apps/tauri/pull/4146

try rc11

**Comment by lucasfernog** [comment]
Fixed in rc.11. Let me know if you still have issues.

**Comment by AlexanderYW** [comment]
~~Was this one solved?, If so how was it done?~~

~~Cause I can't seem to get the string i'm trying to transfer~~

~~On drag start i do `event.dataTransfer.setData('application/item', 1)`~~
~~On drop is not triggered so instead i try as suggested with `listen` from `@tauri-apps/api/event`, but payload is empty and dataTransfer is undefined~~

 ~~I'm trying to move a html element into another box and then create an element based on the transfered information~~
 
 Nvm about the original question, i found the documentation saying i had to disable `fileDropEnabled`. Now my question is, how can it be achieved so both file drag n drop and html drag n drop events are supported in the same window?, can it be controlled somehow from javascript when what is enabled?

**Comment by FabianLars** [comment]
> can it be controlled somehow from javascript when what is enabled?

No, it needs to be set when building the window and can't be changed at runtime. i don't think we can change anything about that.
