### ISSUE TITLE
[feat] add way to increase version

### ISSUE THREAD

**Issue by laurin** [tauri-apps/tauri#4180]
### Describe the problem

When using tauri with a frontend that uses npm (in my case angular), I could not find a way to simultaneously increase the version in the `package.json` and in the `tauri.conf.json` file.

### Describe the solution you'd like

With npm, you normally use the `npm version (major|minor|patch)` command. It will increase the package version by one major, minor or patch version.  
Ideally, a new `tauri version` command would be add to the tauri npm cli. It should update the version in the `tauri.conf.json` like described above and also update the version inside the `/package.json`-file accordingly, if there is such a file.  
Maybe this feature should be opt-in via a property of the `tauri.conf.json`-file.

**Comment by lucasfernog** [comment]
You can make tauri.conf.json point to the version from package.json: https://github.com/tauri-apps/tauri/blob/356b3e1c467d5120f7600717dfff08d8dbedcc04/examples/api/src-tauri/tauri.conf.json#L11

**Comment by laurin** [comment]
Awesome, thanks. I probably should have found this in the docs myself 😅
