### ISSUE TITLE
[feat] Dialog types, dialog titles

### ISSUE THREAD

**Issue by Levminer** [tauri-apps/tauri#4183]
### Describe the problem

[Electron](https://www.electronjs.org/docs/latest/api/dialog#dialogshowmessageboxbrowserwindow-options) has this option.

And there is currently no way to change the icon of the dialog.

Also currently the dialog title is very inconsistant (ask and confirm has title option, but message don't.)

### Describe the solution you'd like

This would be an optional property, example: 
```
import { dialog } from "@tauri-apps/api"

dialog.message("message", {type: "info", title: "test"})

```

Types should be: "info", "error", "warning"

### Alternatives considered

I'm currently using a cargo package [native-dialog](https://crates.io/crates/native-dialog)

**Comment by Levminer** [comment]
Wow, that was fast. Thank you!

**Comment by amrbashir** [comment]
Lucas is The Flash disguised in a Super Man suit.
