### ISSUE TITLE
So I want to know the tauri. How to support the mobile app ??? Also webview???

### ISSUE THREAD

**Issue by shijianzhong** [tauri-apps/tauri#4196]
### Describe the problem

I have something not understand

I want to know  what the relation tauri and tao and flutter;

The tauri how to support mobile app；

I know the tao depends on the winit，and the winit depends on the native  like  the flutter;

But the tauri depends on the webview, play with js,css,html;

So I want to know the tauri. How to support the mobile app ??? Also webview???

### Describe the solution you'd like

I have something not understand

I want to know  what the relation tauri and tao and flutter;

The tauri how to support mobile app；

I know the tao depends on the winit，and the winit depends on the native  like  the flutter;

But the tauri depends on the webview, play with js,css,html;

So I want to know the tauri. How to support the mobile app ??? Also webview???

### Alternatives considered

I have something not understand

I want to know  what the relation tauri and tao and flutter;

The tauri how to support mobile app；

I know the tao depends on the winit，and the winit depends on the native  like  the flutter;

But the tauri depends on the webview, play with js,css,html;

So I want to know the tauri. How to support the mobile app ??? Also webview???

### Additional context

I have something not understand

I want to know  what the relation tauri and tao and flutter;

The tauri how to support mobile app；

I know the tao depends on the winit，and the winit depends on the native  like  the flutter;

But the tauri depends on the webview, play with js,css,html;

So I want to know the tauri. How to support the mobile app ??? Also webview???

**Comment by amrbashir** [comment]
Please don't open the same issue across multiple repos. 

The answer is the same as https://github.com/tauri-apps/tao/issues/403
