### ISSUE TITLE
[bug] Windows 10, WindowAlwaysOnTop is set to true freezes when dragged

### ISSUE THREAD

**Issue by aleksasdev** [tauri-apps/tauri#4200]
### Describe the bug

1) In tauri.conf.json, the option "alwaysOnTop" is set to true in 'windows' section.

2) I have removed the titlebar with "decorations" set to false in 'windows' section, again in tauri config.

3) I've made an invisible rectangle in JSX:

```
<div data-tauri-drag-region
        className="RectangleDragWindow"/>
```

Which is Tauri's in built dragging API.

4) And this is where the issue lies, in 'yarn tauri dev' mode, for some reason I have to deal with constant freezing of the window whenever I Ctrl+S in my code and go straight to the window and try to drag it.

### Reproduction

I just easily reproduced the bug by adding a few lines of code, Ctrl+S, then removed it, Ctrl+S, and rinse and repeat, and eventually frame freezed for a little bit when dragged.

### Expected behavior

I mean it shouldn't be freezing

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 101.0.1210.53
  › MSVC: 
      - Visual Studio Community 2022
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc
```

### Additional context

I don't know if this happens on build version, it shouldn't, but it's hella annoying to have to deal with when you're developing, if the window isn't set to always on top, it seems to be fine. I understand if it can't be solved, I'll just have to adapt, but ima try my luck anyways

**Comment by aleksasdev** [comment]
Seems it occasionally happens on "alwaysOnTop" set to false as well, but less frequently

**Comment by lucasfernog** [comment]
Please paste the entire `tauri info` output. Can you share the app you're using to test it? I couldn't reproduce it on my test.

**Comment by aleksasdev** [comment]
I really don't know how to use gitbuh xd I don't think it's gonna be fixed, it has too much variables at play, and we'll be wasting time, I'll work on my code more and see if it's NOT my own caused behaviour, if it's not and whenever I'll collect more data on this, I'll reopen this issue
