### ISSUE TITLE
[bug] Tauri App not running on Windows 11

### ISSUE THREAD

**Issue by jquesada2016** [tauri-apps/tauri#4203]
### Describe the bug

When creating a new `tauri` app, running `npx tauri dev` builds and opens a window, but does not show anything and displays an error in the console. The error can be found in the `Stack Trace` section of this report.

### Reproduction

1. On Windows 11, create a new `tauri` project however one wishes
2. run `npx tauri dev` or with the rust cli
3. wait for the window to open and watch the ensuing blank screen and errors

### Expected behavior

I expect `tauri` to open the window as normal with no errors and display the web app's contents.

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 101.0.1210.53
  › MSVC: 
      - Visual Studio Build Tools 2022
  › Node.js: 17.7.1
  › npm: 8.5.2
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.11
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.0.0-rc.11,
  › tauri-build [RUST]: 1.0.0-rc.9,
  › tao [RUST]: 0.8.5,
  › wry [RUST]: 0.16.2,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: Svelte

App directory structure
  ├─ .svelte-kit
  ├─ node_modules
  ├─ src
  ├─ src-tauri
  ├─ static
  └─ tests
```

### Stack trace

```shell
Compiling app v0.1.0 (C:\Dev\Commercial\manteados-grecia\sistema-procesos\src-tauri)
    Finished dev [unoptimized + debuginfo] target(s) in 4.52s
     Running `target\debug\app.exe`
[0524/105510.088:ERROR:validation_errors.cc(106)] Invalid message: VALIDATION_ERROR_UNEXPECTED_NULL_POINTER ([0524/105510.088:ERROR:interface_endpoint_client.cc(665)] Message 1283517667 rejected by interface embedded_browser.mojom.EmbeddedBrowser
```
```


### Additional context

I came across this error when I was teaching a friend how to use Tauri. They were on Windows 10, and did not have any issues. I, however did, as stated above.

**Comment by amrbashir** [comment]
Do you still have this issue? Can't reproduce it. Please post a minimal repro if you still encounter this.

**Comment by lucasfernog** [comment]
Looks similar to https://github.com/MicrosoftEdge/WebView2Feedback/issues/1207 and #4181

**Comment by jquesada2016** [comment]
I took a look at #4181 and it is definitely related. Here's a bit more context:

I made a sort of screen reader app for myself that is always running in the background. This project where the error occurs, or any other project I try to run with Tauri while that accessibility app is running in the background causes the above error. All apps have a different package name. But only if there is one tauri app running will that app run.

@amrbashir I could try to make a repro, but there wouldn't really be anything to repro, as this happens with just running the exacts steps above for me, with the simple addition of already having an installed Tauri app running in the background.

**Comment by jquesada2016** [comment]
I misread this [comment](https://github.com/tauri-apps/tauri/issues/4181#issuecomment-1133758920). When I changed the package identifier (not the package name), then the app successfully launched.

Is it possible to add a warning note in the documentation that states that if two different Tauri apps are running, and have the same identifier, than the second app will not work?

As these were personal projects and were not expected to be published anywhere, I never considered the uniqueness requirement of the package identifier.

**Comment by lucasfernog** [comment]
@jquesada2016 can you give us more details on how you're running these apps? I tried again installing two MSI for different projects with the same bundle identifier and running both at the same time, but I still cannot reproduce the issue.

**Comment by jquesada2016** [comment]
Sure!

First I generated the `msi` installer with `npx tauri build` for the first app. I installed this app and started it.
After this, I create a new `tauri` project, you can generate it any way you'd like, they all result in the same error.
Then, while the first installed app is still running, run `npx tauri dev`, which does open a window, tough blank and the above error message logged in the terminal.

If I quit out of the first app which is running in the background, and try `npx tauri dev` on the second app, then that second app works.

**Comment by jquesada2016** [comment]
If you'd like, I can put the project for the first app as-is up on GitHub and link it here if it might help. That app isn't doing anything particularly fancy, however.

**Comment by lucasfernog** [comment]
I still can't reproduce it, but I assume this happens because both applications are using the same data directory. I'll add this to the documentation, though the CLI already shows a useful error if you use the default identifier.

**Comment by kimlimjustin** [comment]
I can reproduce this by having old-version of tauri installed and opened while running dev process of the newest version of tauri installed

**Comment by jquesada2016** [comment]
Yes! the app I have running in the background was produced by an older version of Tauri.

**Comment by SeaIsCoder** [comment]
did have one solution ? i meet the same thing in windows 11

**Comment by maxt41** [comment]
Same here, installs fine, but then won't run.

**Comment by zmooky** [comment]
Same here. Building the end result of the tauri-app created template results in having an exe  file that does run on Windows. 

Choose: pnpm + rust + react + typescript :
```sh
pnpm create tauri-app@latest
cd tauri-app/
pnpm install
pnpm tauri build
```

**Comment by maxt41** [comment]
Turns out my issue was due to secrets not being registered at build time causing the app to instantly crash. Using procmon you can see the crash and error messages.

**Comment by altunenes** [comment]
I have the same problem. last night it worked without any problem but now it compiles everything but it's not opening the app.

**Comment by maxt41** [comment]
@altunenes would recommend running "procmon" it will show you some helpful log messages.

**Comment by altunenes** [comment]
> @altunenes would recommend running "procmon" it will show you some helpful log messages.

thanks! I'm trying this now!

**Comment by altunenes** [comment]
`    Error A public key has been found, but no private key. Make sure to set `TAURI_SIGNING_PRIVATE_KEY` environment variable.`

:D

**Comment by maxt41** [comment]
I think that way nearly word for word the error I had too lol

**Comment by altunenes** [comment]
I'm sending this msg to the future:

My problem was solved after I copied and pasted `onnxruntime.dll` into the system32 folder in Windows. 

I've been dealing with this problem all day, so don't ask me how I came up with such a solution :D, I've tried everything you can imagine haha.

In short, if your app is dependent on something (like gst, ffmpeg, cuda, or onnx like me) and it's crashing silently, make sure that these kinds of Path operations are somehow working in your app.

**Comment by ahmadwali-mohammadi** [comment]
Thank you for providing detailed information about the issue you're experiencing with Tauri on Windows 11. It appears that the problem is related to having multiple Tauri apps running with the same package identifier, which causes the second app to fail to launch. This has been observed by other users as well, and it seems to be a known issue, especially when running different versions of Tauri concurrently.

To resolve this, ensure that each Tauri app has a unique package identifier. If you have already published your apps and they were not expected to coexist, you might consider updating their package identifiers. For future projects, keep in mind this important consideration to avoid similar issues.

Additionally, as suggested by other community members, using tools like `procmon` can help diagnose crashes and errors more effectively. If you continue to face issues, please share more specific details or a minimal reproducible example, especially if the problem is related to dependencies or path operations.

Best regards,
Ahmd wali
