### ISSUE TITLE
[feat] Window Progress Bar

### ISSUE THREAD

**Issue by KernelFreeze** [tauri-apps/tauri#4208]
### Describe the problem

It's a shame that Tauri doesn't have an API similar to [Electron's Progress Bar](https://www.electronjs.org/docs/latest/tutorial/progress-bar), it's very useful for showing progress in minimized windows.

### Describe the solution you'd like

An API similar to the Electron one, or even a Tao method that we could invoke in Rust code to set the progress quickly.

**Comment by amrbashir** [comment]
This is now supported starting v2-beta
