### ISSUE TITLE
[bug] Large images not accessible in built product

### ISSUE THREAD

**Issue by stephenlrandall** [tauri-apps/tauri#4216]
### Describe the bug

Including large images in my Tauri application works fine locally but not in the release product. I had a 1.9MB PNG file that failed to load in the built application, so I compressed it to a ~0.5MB JPG and it rendered correctly.

### Expected behavior

I expect the local and release versions of the product to match in terms of rendered images regardless of file size.

### Platform and versions

```shell
Environment
  › OS: Mac OS 12.3.1 X64
  › Node.js: 18.2.0
  › npm: 8.9.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.12
  › @tauri-apps/api [NPM]: 1.0.0-rc.6
  › tauri [RUST]: 1.0.0-rc.8,
  › tauri-build [RUST]: 1.0.0-rc.7,
  › tao [RUST]: 0.8.4,
  › wry [RUST]: 0.15.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: Svelte

App directory structure
  ├─ tauri
  ├─ node_modules
  ├─ static
  ├─ .svelte-kit
  ├─ build
  ├─ .git
  └─ src
```

**Comment by lucasfernog** [comment]
Can you share a repo to reproduce it?

**Comment by stephenlrandall** [comment]
Doesn't seem like I'm able to reproduce the issue anymore, so I'll close until I can.
