### ISSUE TITLE
Tauri init and first time use

### ISSUE THREAD

**Issue by jbolda** [tauri-apps/tauri#422]
**Is your feature request related to a problem? Please describe.**
When first installing and running tauri init, we should provide an input for a few of the major required settings specifically the path settings and app name. At the completion of the init script, we can note where these config options were stored to make it easier for the user to find them.

Additionally, we can add a `readme.md` in `src-tauri` with the simple instructions for running and point them to our docs for further help. This will give a helping hand to anyone using tauri "indirectly".

**Comment by nklayman** [comment]
https://github.com/tauri-apps/tauri/pull/472
