### ISSUE TITLE
[bug] updater cannot launch app after installation

### ISSUE THREAD

**Issue by joshua7v** [tauri-apps/tauri#4220]
### Describe the bug

App is able to detect a new version is available,  and gets exited immediately after calling `installUpdate()`, also brings up the installer.
however, app does not get relaunched after installation finished somehow.

I was following the instructions on the doc that said I should call `1. installUpdate` then `2. relaunch`.
But app immediately exited after calling `installUpdate` and `relaunch` never have a chance to run.
I've also tried `emit('tauri://update-install')`, it has the same result which exits the app, and never bring it back.

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 101.0.1210.53
  › MSVC:
      - Visual Studio Community 2022
      - Visual Studio Build Tools 2017
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.12
  › @tauri-apps/api [NPM]: 1.0.0-rc.6
  › tauri [RUST]: 1.0.0-rc.12,
  › tauri-build [RUST]: 1.0.0-rc.10,
  › tao [RUST]: 0.9.1,
  › wry [RUST]: 0.17.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../webapp
  › devPath: http://127.0.0.1:3000/

App directory structure
  ├─ .git
  ├─ dist
  ├─ node_modules
  ├─ src
  ├─ src-tauri
  └─ webapp
```

### Additional context

https://discord.com/channels/616186924390023171/731495028677148753/979313103902765066

**Comment by lucasfernog** [comment]
Maybe we can force the `launch [App Name]` option from the CLI, i'm not sure. Because currently we force exit after running msiexec and leave the restart to the UI.

**Comment by joshua7v** [comment]
@lucasfernog 

> leave the restart to the UI

So, to be more precise, does it mean we need to manually open the app after updating? at least for now?

**Comment by rming** [comment]
> @lucasfernog
> 
> > leave the restart to the UI
> 
> So, to be more precise, does it mean we need to manually open the app after updating? at least for now?

same issue
