### ISSUE TITLE
[bug] updater does not actually update the app with `installMode: quiet`

### ISSUE THREAD

**Issue by joshua7v** [tauri-apps/tauri#4221]
### Describe the bug

I was hoping to achieve quieter install. So I found the config somewhere in recent issues.
But quiet option does not actually install the new version. It seems that the installation just failed silently.
`passive/basicUi` do install the new version.

with passive/basicUi, windows will prompt UAC confirmation dialog, but not with quiet.
Is that causing quiet installation failed? This would be my guess.

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 101.0.1210.53
  › MSVC:
      - Visual Studio Community 2022
      - Visual Studio Build Tools 2017
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.12
  › @tauri-apps/api [NPM]: 1.0.0-rc.6
  › tauri [RUST]: 1.0.0-rc.12,
  › tauri-build [RUST]: 1.0.0-rc.10,
  › tao [RUST]: 0.9.1,
  › wry [RUST]: 0.17.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../webapp
  › devPath: http://127.0.0.1:3000/

App directory structure
  ├─ .git
  ├─ dist
  ├─ node_modules
  ├─ src
  ├─ src-tauri
  └─ webapp
```

### Additional context

https://discord.com/channels/616186924390023171/731495028677148753/979320538889605122

**Comment by lucasfernog** [comment]
Yeah with `quiet` you need admin privileges. The default mode is now `passive`, which only prompts for admin access and shows a progress bar.
