### ISSUE TITLE
[feat] Add Watch Files

### ISSUE THREAD

**Issue by kdumontnu** [tauri-apps/tauri#4222]
### Describe the problem

I'm setting up Tauri as a front-end for my Rust library. In my `src-tauri/Cargo.toml`:

```
[dependencies]
...
parser = { path = "../core/my-library" }
```

### Describe the solution you'd like

Ideally, tauri config would provide the ability to specify watch glob patterns to automatically rebuild like it does for changes in `src-tauri/`. 

Even better would be if tauri used the top level `cargo.toml` or `src-tauri/cargo.tom` to automatically add files to watch.

**Comment by JonasKruckenberg** [comment]
You can archive this by editing your `build.rs` file and adding your crate paths to the change detection list: https://doc.rust-lang.org/cargo/reference/build-scripts.html#change-detection

**Comment by FabianLars** [comment]
Nope, using the build script doesn't work, at least not with virtual workspaces.

**Comment by JonasKruckenberg** [comment]
Really? That's weird 🤔

**Comment by FabianLars** [comment]
Yeah i expected(/hoped) it to work too, but the last time we had this topic i asked other people to test it too, to make sure it's not just me doing it wrong (well, that's still a possibility) 🤷

**Comment by lucasfernog** [comment]
Our watcher has nothing to do with the build script. But we're not watching every package in a workspace, only tauri folders.

**Comment by kdumontnu** [comment]
Looks like the ability to watch a folder recursively was only [added in the latest](https://github.com/rust-lang/cargo/commit/cee088b0db01076deb11c037fe8b64b238b005a2) Rust version. 

I’ll give it a shot.

**Update**: I tried using [`rerun-if-changed`](https://doc.rust-lang.org/cargo/reference/build-scripts.html#build-scripts) from build scripts, but I could not get it to work like I wanted. It actually appears it's not intended to do what we're looking for. It seems `rerun-if-changed` is meant to tell cargo whether or not to (re)run the build script on build (vs using cached builds), NOT whether it should run watch the file/directory while running to rebuild. 

Instead, [`cargo-watch`](https://crates.io/crates/cargo-watch) seems to be the tool for this job. I have no idea if this is what Tauri is using to watch directories though. 

I apologize if I misunderstand something here, as I'm pretty new to Rust.

> Our watcher has nothing to do with the build script. But we're not watching every package in a workspace, only tauri folders.

My goal with this feature request is to add the ability to customize files/directories in the tauri watcher and/or have tauri follow my local cargo dependencies by default.
