### ISSUE TITLE
[bug] Plugin webview does not work on first run

### ISSUE THREAD

**Issue by zbouslikhin** [tauri-apps/tauri#4240]
### Describe the bug

I created a tauri plugin that gets correctly built. However, when first starting tauri (`yarn tauri dev`), an error is returned on first run saying:
```
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/tauri-plugin-zaid-plugin.js?v=2a118ae6' does not provide an export named 'test' (at App.tsx:5:1)
```
But if one comments out lines 11-19 in `App.tsx`, reload the page, uncomment them and reload the page, everything works as expected.

### Reproduction

1. clone [this repo to reproduce the bug](https://github.com/zbouslikhin/tauri-possible-bug)
2. yarn install
3. yarn tauri dev

### Expected behavior

Plugin to work on first run

### Platform and versions

```shell
$ tauri info

Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 101.0.1210.53
  › MSVC:
      - Visual Studio Build Tools 2019
  › Node.js: 16.14.1
  › npm: 8.5.0
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-gnu

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.13
  › @tauri-apps/api [NPM]: 1.0.0-rc.6
  › tauri [RUST]: 1.0.0-rc.14,
  › tauri-build [RUST]: 1.0.0-rc.12,
  › tao [RUST]: 0.9.1,
  › wry [RUST]: 0.17.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ node_modules
  ├─ src
  └─ src-tauri
```

**Comment by zbouslikhin** [comment]
Tried running it on MacOS, works flawlessly, but not on Windows.

**Comment by lucasfernog** [comment]
I couldn't reproduce this. Also it's not a Tauri issue but a possible configuration issue on your React app or the plugin build.
