### ISSUE TITLE
[bug]  Drag and Drop does not add payload to scope

### ISSUE THREAD

**Issue by SincerityJayce** [tauri-apps/tauri#4241]
### Describe the bug

Bug report recommended by one of the core devs in the discord.

So I want users to drag and drop files into the app.
With scope "*" I can do this, but thats disrespectful to their security.
Drop event payloads a path -> the path needs to be fetched by fs.readFile :. scope needs to be open for that to happen. 

### Expected behavior

The payload path would be added to the scope automatically

### Platform and versions

```shell
"@testing-library/user-event": "^13.5.0",
```

**Comment by lucasfernog** [comment]
Closed by #3595
