### ISSUE TITLE
[bug] Duplicate permission prompt for notifications on MacOS

### ISSUE THREAD

**Issue by betamos** [tauri-apps/tauri#4244]
### Describe the bug

Using the `notification.sendNotification` API, on first use I'm observing on MacOS Monterey 12.3.1 I'm getting duplicate permission prompts.

First the "soft prompt" from Tauri and then the native one "AppX want's to send you notifications" in the upper right corner.

### Reproduction

1. Use the notification API as per the above instructions.
2. Bundle the app and move it to the applications directory (i.e. don't run in dev mode).
3. Make sure to clear any pre-existing `.tauri-settings` files
4. Approve notifications in the first (Tauri's) dialog
5. Observe the second, native, permission dialog

### Expected behavior

On MacOS, the native dialog and permission system should probably be used, since it allows a lot of fine-grained control and users are expecting it. I don't think one can/should bypass this from Tauri's end.

### Platform and versions

```shell
> tauri
> ./bin/cargo-tauri "info"


Environment
  › OS: Mac OS 12.3.1 X64
  › Node.js: 17.3.0
  › npm: 8.3.0
  › pnpm: Not installed!
  › yarn: 1.22.10
  › rustup: 1.24.3
  › rustc: 1.59.0
  › cargo: 1.59.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.7(outdated, latest: 1.0.0-rc.13)
  › @tauri-apps/api [NPM]: 1.0.0-rc.6
  › tauri [RUST]: git+https://github.com/betamos/tauri?branch=betamos-head#99f5919ff2008e82d273b99200b60fbc9ff6d6d3 (1.0.0-rc.8),
  › tauri-build [RUST]: git+https://github.com/betamos/tauri?branch=betamos-head#99f5919ff2008e82d273b99200b60fbc9ff6d6d3 (1.0.0-rc.7),
  › tao [RUST]: 0.8.4,
  › wry [RUST]: 0.16.0,

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  › distDir: ../ui/public
  › devPath: ../ui/public

App directory structure
  ├─ ui
  ├─ app
  ├─ bin
  ├─ node_modules
  ├─ agent
  ├─ scripts
  ├─ .git
  └─ .vscode
```

### Additional context

See also https://github.com/tauri-apps/tauri/issues/2317

**Comment by FabianLars** [comment]
I thought we had that dialog because the native one _doesn't_ show 🤔 Maybe this changed in a recent macos version?
If every macos version (>= 10.15) does show the native one, i personally would vote for completely removing our dialog (for all platforms) 🤷

**Comment by betamos** [comment]
> Maybe this changed in a recent macos version?

I can't answer this, but I definitely saw a first-use prompt and I haven't customized any preferences on that machine, to my knowledge.

> i personally would vote for completely removing our dialog (for all platforms)

Yeah, I'm not entirely sold on the soft prompt. It seems all major platforms (MacOS, Windows 10+ and Linux+Gnome) have system-wide and per-app toggles for notifications these days.  Note that MacOS *additionally* has a first-use prompt (it wouldn't surprise me if others will follow in due time - Apple's UX tend to be copied).

Anyway, there are now two sources of preferences that live in two independent places, which gets complicated. If a user wants to, say, turn on notifications after declining the soft-prompt, the app developer needs to expose UI for that, as well as document the interactions between the Tauri and OS settings.

Personally, I'm gonna remove the soft prompt for my app (easy for me since I maintain a fork anyway). All my notifications are urgent and rare, and the users who care can always disable them.

There could of course be apps that need different behavior, such as an opt-in flow or finer granularity. However, it's difficult to design for that upfront and is likely to vary on a case-by-case basis.
