### ISSUE TITLE
Rust Version Expectation

### ISSUE THREAD

**Issue by jbolda** [tauri-apps/tauri#425]
**Is your feature request related to a problem? Please describe.**
If you are using an old version of Rust, it would be great to throw an error as Tauri will likely stay on near stable versions.

**Describe the solution you'd like**
This is more of a tracking issue as we need the functionality upstream. See https://github.com/rust-lang/rust/issues/65262.

**Comment by JustinR93** [comment]
Should it be an error or just warning letting the user know that results may be unexpected?

**Comment by jbolda** [comment]
Assuming we could get granular with it, I can see a use case for both. If we are using a newer feature, I can assume we want to throw an error instead of letting a nondescript error bubble up.

**Comment by JustinR93** [comment]
Been thinking about this and looking at the whole picture it may be better to dedicate a release when you update Rust version on the project as dependencies would also need to be checked if they work in the version the user would want. It'd make more sense that if they had a use case a outdated version of Rust that they could check the releases to see what was the the latest release of that version.

**Comment by JustinR93** [comment]
So with that said I think you are right to throw an error instead of my idea of just warning them

**Comment by khionu** [comment]
There's only really one use case for an outdated version of Rust and that's if their infrastructure would need to be updated. Rust is still a growing technology, infrastructure should be updating it at least a couple times a year.

**Comment by nothingismagick** [comment]
Closing as resolved.
