### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by mxismean** [tauri-apps/tauri#4250]
### Describe the bug

Has a  .wasm file in project.

<img width="1138" alt="企业微信截图_c698603d-7ed5-42e5-acb9-5f50051c27f6" src="https://user-images.githubusercontent.com/44690729/171350889-52b65c29-57ce-4258-9dc8-a2831f907ae9.png">

yarn tauri dev   or    yarn tauri  build,  got error:

<img width="600" alt="企业微信截图_7a6fdac0-78a1-46c0-984e-239a936b8ca1" src="https://user-images.githubusercontent.com/44690729/171351239-485f5a0e-f740-435e-8ef8-a2adb03b25db.png">

What to do with .wasm files and load it ?

### Platform and versions

```shell
Operating System - Mac OS, version 12.3.1 X64

Node.js environment
  Node.js - 14.19.3
  @tauri-apps/cli - 1.0.0-rc.4
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.17
  pnpm - Not installed
  yarn - 1.22.18

Rust environment
  rustup - 1.24.3
  rustc - 1.61.0
  cargo - 1.61.0
  toolchain - stable-x86_64-apple-darwin

App directory structure
/dist
/node_modules
/public
/src-tauri
/.git
/.vscode
/src

App
  tauri - 1.0.0-beta.8
  tauri-build - 1.0.0-beta.4
  tao - 0.5.2
  wry - 0.12.2
  build-type - bundle
  CSP - default-src https: tauri: 'self'; img-src: 'self'; script-src 'wasm-unsafe-eval' 'unsafe-eval' 'self'
  distDir - ../dist
  devPath - http://localhost:3000/
  framework - Vue.js
  bundler - Rollup
```

**Comment by FabianLars** [comment]
Hmm, this does look like an issue with your wasm file 🤷
Shouldn't be a tauri specific problem (you should see the same error in your browser or at least in safari)).

Also your tauri dependencies are really old and we don't support them anymore.

Closing this for now.
