### ISSUE TITLE
[bug] hanging when showing window in windows

### ISSUE THREAD

**Issue by Sheap** [tauri-apps/tauri#4251]
### Describe the bug

When calling `window.show()` the app becomes non responsive. I have an example showing the issue here: https://github.com/Sheap/tauri-window-test

This only occurs on my windows machine. I have tested it on both linux and mac, and have no issues.

Curiously, in my application I have a splash screen set up as per the documentation, which includes calling `.show()` on the main window, which works without issue on all OSs, suggesting the issue is specific to secondary windows.

### Reproduction

1. clone https://github.com/Sheap/tauri-window-test on windows
2. `pnpm tauri dev`
3. press the "Toggle Popout" button
4. The popout window _will_ appear, but then the app will freeze (both windows)
5. console will show the print statements from before the `show` call, and none after it.

### Expected behavior

The app to remain responsive

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 101.0.1210.53
  › MSVC:
      - Visual Studio Community 2019
  › Node.js: 16.9.1
  › npm: 7.21.1
  › pnpm: 6.32.19
  › yarn: 1.22.11
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.13
  › @tauri-apps/api [NPM]: 1.0.0-rc.6
  › tauri [RUST]: 1.0.0-rc.14,
  › tauri-build [RUST]: 1.0.0-rc.12,
  › tao [RUST]: 0.9.1,
  › wry [RUST]: 0.17.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../public
  › devPath: http://localhost:8080/
  › framework: Svelte
  › bundler: Rollup

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

**Comment by lucasfernog** [comment]
Closed by #4392. Will be available in tauri v1.0.1.
