### ISSUE TITLE
[feat] Adobe Flash Player Support

### ISSUE THREAD

**Issue by kairusds** [tauri-apps/tauri#4253]
### Describe the problem

I'm always frustrated when certain sites that require Flash to run games or others aren't available because the backend doesn't have support for it.

### Describe the solution you'd like

Add an API to set the Pepper Flash Player's path or something similar to enable it.

**Comment by nothingismagick** [comment]
https://wiki.debian.org/PepperFlashPlayer

PepperFlashPlayer only worked in a chromium context, and was discontinued in 2020.
