### ISSUE TITLE
[docs] Clarification on "category": "DeveloperTool"

### ISSUE THREAD

**Issue by aronedwards91** [tauri-apps/tauri#4257]
In short I changed the value on my tauri.conf.json from
`"category": "DeveloperTool",` to `"category": "Creative Tool",` thinking this was a general string but received an error
`Error running CLI: failed to build bundler settings: invalid category`

I assume this is more likely a cargo error, but in case someone makes a similar error, may be worth having some clarification as to the allowed values, which despite some research i have not found a clear answer to.
Cargo suggests using a value from a predefined list
https://doc.rust-lang.org/cargo/reference/manifest.html?highlight=category#the-categories-field
However the value DeveloperTool isn't present? so I'm hesitant to list this as a solution and was hoping someone a bit more seasoned with rust/cargo/app dev might have some further insight, apologies i can't offer more.

**Comment by FabianLars** [comment]
The allowed categories are listed here: <https://tauri.studio/v1/api/config#bundleconfig.category>. (And another related thing is here: <https://tauri.studio/v1/guides/building/macos#application-bundle-customization>)

Furthermore it's not a cargo error, we handle this completely ourselves and the binary itself doesn't even know about this. It's only relevant for .deb (linux) and .app (macos) bundles (mainly for the appstore(s) i think?)
