### ISSUE TITLE
http.fetch cannot be viewed in devtool

### ISSUE THREAD

**Issue by MellowCo** [tauri-apps/tauri#4258]
* Use http.fetch send a network request and cannot be debugged in devtool
* How to debug http.fetch

![image](https://user-images.githubusercontent.com/47939250/171651044-1eee4d10-31cc-4df6-b338-07a3f0eda174.png)

**Comment by FabianLars** [comment]
I don't think we can inject any info into this window 🤔 

You can do a little debugging by adding a logger facility to your app. Either by using something like `pretty_env_logger` in rust or our [log-plugin](https://github.com/FabianLars/tauri-plugin-log) which afaik should pick them up too.
p.s. set the log level to `debug`.
