### ISSUE TITLE
[feat] Add a function to tauri::api::file that can write to a file.

### ISSUE THREAD

**Issue by ShungJung** [tauri-apps/tauri#4259]
### Describe the problem

Because tauri::api::file only provides the read function, we're having difficulty writing files in rust code. Since our logic is written in rust, I'd want to be able to create files using the tauri api in Rust. 

### Describe the solution you'd like

Most of the functions in @tauri-apps/api/fs should be available in tauri::api::file. 

### Alternatives considered

Simply leave logic to the frontend rather than the rust backend.

**Comment by KielKing** [comment]
I think this would be a great feature to add, I also have troubles with writing files with Tauri in Rust. +1

**Comment by FabianLars** [comment]
While i agree that it weird that it's missing while a read function exists, all the write function (which is used when called from js) does really is a 2-liner:
```rs
use std::{fs::File, io::Write};

let file = File::open(&file_path);
file.write_all(&contents);
```

Although in a command you may want to use tokio's async equivalent 🤷

**Comment by ShungJung** [comment]
> While i agree that it weird that it's missing while a read function exists, all the write function (which is used when called from js) does really is a 2-liner:
> 
> ```rust
> use std::{fs::File, io::Write};
> 
> let file = File::open(&file_path);
> file.write_all(&contents);
> ```
> 
> Although in a command you may want to use tokio's async equivalent 🤷

I use the fs::write function to write into files but when build it, I have to run the app as admin so that it can write the file. It won't work if I don't run it as admin. Is there a way to fix that?

```
"allowlist": {
      "all": false,
      "fs": {
        "all": true,
        "scope": ["$APP/*"]
      },
      "window": {
        "setTitle": true
      }
    },

```

**Comment by FabianLars** [comment]
> I use the fs::write function to write into files but when build it, I have to run the app as admin so that it can write the file. It won't work if I don't run it as admin. Is there a way to fix that?

You're probably trying to write to the wrong folder? The _install_ dir is is read-only. Make sure you write in a user-data folder, like the path returned by the `app_dir()` function. Also try deleting the file manually, maybe it got created with the wrong permissions.

Also, the allowlist has no effect on rust's std functions.

**Comment by ShungJung** [comment]
> > I use the fs::write function to write into files but when build it, I have to run the app as admin so that it can write the file. It won't work if I don't run it as admin. Is there a way to fix that?
> 
> You're probably trying to write to the wrong folder? The _install_ dir is is read-only. Make sure you write in a user-data folder, like the path returned by the `app_dir()` function. Also try deleting the file manually, maybe it got created with the wrong permissions.
> 
> Also, the allowlist has no effect on rust's std functions.

Thanks bro the app_dir() worked well!

**Comment by KielKing** [comment]
It's also working for me and my project, thank you very much @ShungJung @FabianLars 👍
