### ISSUE TITLE
[feat] Display window behind desktop icons

### ISSUE THREAD

**Issue by gBasil** [tauri-apps/tauri#4261]
### Describe the problem

Electron has a feature (at least on MacOS and Linux) to allow the window to appear behind the desktop icons and any windows, but in front of the wallpaper. In order to achieve the same effect for Windows, you have to use an npm package that uses C++ bindings to Windows APIs, such as [electron-wallpaper](https://www.npmjs.com/package/electron-wallpaper) or the more recent [electron-as-wallpaper](https://www.npmjs.com/package/electron-as-wallpaper).

The Electron settings in question:
<img width="784" alt="image" src="https://user-images.githubusercontent.com/57513430/171708987-abe9b07f-010f-409d-abb6-b855dead9bb3.png">

### Describe the solution you'd like

It would be neat to have an option in `tauri.conf.json` to choose whether windows appear behind the icons by default, as well as API functions for both the WebView and the Rust runtime (pardon me if I get my terminology wrong, I'm quite new to Tauri 😅).

### Additional context

Thank you for all the hard work and care you've put into Tauri!

**Comment by amrbashir** [comment]
Leaving these here for future reference because this can't be included in tauri until v2: 
- Linux(gtk): https://gtk-rs.org/gtk3-rs/stable/latest/docs/gdk/enum.WindowTypeHint.html#variant.Desktop
- macOS: https://stackoverflow.com/a/4987525
- Windows: https://github.com/meslzy/electron-as-wallpaper/blob/2eed5a3af132040c1c4a17442905706fc3352d97/source/binding/index.cpp
- Windows (simplified):
	```cpp
  // Message to `Progman` to spawn a `WorkerW`
  int WM_SPAWN_WORKER = 0x052C;

  void Attach(HWND win) {
    // find `Progman`
    HWND hProgman= FindWindow("Progman", nullptr);

    // instruct program to create a `WorkerW` between wallpaper and icons
    SendMessageTimeout(
      hProgman,
      WM_SPAWN_WORKER,
      NULL,
      NULL,
      SMTO_NORMAL,
      1000,
      NULL);

    // find the newly created `WorkerW`
    static HWND hWorkerW = nullptr;
    EnumWindows([](HWND topHandle, LPARAM topParamHandle) {
      HWND shellDllDefView = FindWindowEx(topHandle, nullptr, "SHELLDLL_DefView", nullptr);
      if (shellDllDefView != nullptr) {
        hWorkerW = FindWindowEx(nullptr, topHandle, "WorkerW", nullptr);
      }
      return TRUE;
    }, NULL);

    // set our window as the child of the newly created `WorkerW`
    SetParent(win, hWorkerW );
  }

  void Detach(HWND win) {
    // remove the parent from our window
    SetParent(win, 0);
  }

	```

It seems possible overall and could be done as a tauri plugin too:
- Linux: call `window.gtk_window` to obtain the gtk handle and then call `set_type_hint` on it.
- macOS: call `window.ns_window` and use `objc` crate to `setLevel` as the SO answer suggests.
- Windows: call `window.hwnd` and use `windows-rs` crate and translate the c++ code linked above.

**Comment by JonasKruckenberg** [comment]
I'm going to vote "plugin", this feels like a rather niche feature that would only increase complexity and bloat in core while serving a very small number of users. 
It's also not included in electron core for the same reason I'd imagine.
And don't forget that every feature implemented in core will have to be audited.

But this would make for a neat little plugin!

**Comment by amrbashir** [comment]
Agreed

**Comment by gBasil** [comment]
> I'm going to vote "plugin", this feels like a rather niche feature that would only increase complexity and bloat in core while serving a very small number of users.

That makes sense to me. Thank you for your time!

**Comment by meslzy** [comment]
Hey, im the creator of [electron-as-wallpaper](https://www.npmjs.com/package/electron-as-wallpaper), I have converted to tauri lately and want to rebuild my wallpaper app with it. so I have made [tauri-plugin-wallpaper](https://github.com/meslzy/tauri-plugin-wallpaper) I'm really new to `rust` and `tauri` so u may see slow improvement on the plugin.
