### ISSUE TITLE
[feat] How to set proxy settings for the webview

### ISSUE THREAD

**Issue by hsj1606** [tauri-apps/tauri#4263]
### Describe the problem

Try to find a way to apply network proxy settings for macOS webview, seems wry has not implemented yet

### Describe the solution you'd like

Support passing the proxy setting in the tauri main entry

**Comment by FabianLars** [comment]
https://github.com/tauri-apps/wry/issues/588

Last time i checked, it seemed like this is not supported on macOS (WKWebView).

**Comment by czxichen** [comment]
Is there a support plan for proxy setup?

**Comment by arslanmughal99** [comment]
Is this feature coming anytime soon ?
waiting for this feature from long time so that i can migrate app from electron to tauri .

**Comment by xsa-dev** [comment]
Could you please tell me if the proxy webview can work on macOS?
