### ISSUE TITLE
[bug] AppImage: error while loading shared libraries: libwebkit2gtk

### ISSUE THREAD

**Issue by probonopd** [tauri-apps/tauri#4278]
### Describe the bug

When trying to run some AppImages made with tauri, I get

> error while loading shared libraries: libwebkit2gtk-4.0.so.XX: cannot open shared object file: No such file or directory

This libary and its dependencies need to be bundled inside the AppImage because it cannot reasonably be expected to come with all Linux distributions by default.

### Reproduction

1. Run a non-Gnome Linux distribution (e.g., Kubuntu)
2. Download the AppImage from https://github.com/lights0123/n-link/ (made with tauri)
3. See the error: `n-link: error while loading shared libraries: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory`

### Expected behavior

Application runs

### Platform and versions

```shell
I don't have these installed on my system, as I am just trying to run the AppImage.
```

### Additional context

libwebkit2gtk and its dependencies would need to be deployed (privately bundled) with the application.

**Comment by FabianLars** [comment]
This project was built over a year ago (with tauri's _alpha_ version) when our appimage builder was completely broken (that's why it's ~5MB), we fixed most of the issues in a later beta versionn back in August when we switched to linuxdeploy (with followup fixes in December)

**Comment by probonopd** [comment]
Thanks for the clarification; glad it got fixed.
