### ISSUE TITLE
Infinity becomes `null` when returned to the frontend by a command  [bug] 

### ISSUE THREAD

**Issue by JosephChotard** [tauri-apps/tauri#4279]
### Describe the bug

When a tauri command returns a value with `std::f64::INFINITY`, the infinity gets converted to a javascript `null` in the response.

### Reproduction

Create a command such as:

```
#[tauri::command]
pub fn get_inf() -> f64 {
  std::f64::INFINITY
}
```

and call this from the front-end:

```
tauri.invoke('get_inf').then(res => {
      console.log(res)
})
```

### Expected behavior

In the above scenario, we would expect `res` to be [infinity](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity) however it is `null`

### Platform and versions

```shell
Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 14.17.0
  › npm: 8.1.4
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.12
  › @tauri-apps/api [NPM]: 1.0.0-rc.6
  › tauri [RUST]: 1.0.0-rc.14,
  › tauri-build [RUST]: 1.0.0-rc.10,
  › tao [RUST]: 0.9.1,
  › wry [RUST]: 0.17.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ src-tauri
  ├─ .git
  └─ src
```

### Additional context

Happy to make a PR to fix this issue if someone can point me in the right direction.

**Comment by JonasKruckenberg** [comment]
The issue here that Infinity (same as NaN) cannot be represented in JSON, and since our IPC channel serializes payloads to JSON, there is technically no way to send Infinity across the channel. [See this stackoverflow question for why Infinity and NaN aren't valid JSON](https://stackoverflow.com/questions/1423081/json-left-out-infinity-and-nan-json-status-in-ecmascript)

**Comment by JosephChotard** [comment]
Ok, that makes sense thank you. The way the developer chooses to handle infinity should be on a case per case basis then.
