### ISSUE TITLE
[feat] Synchronous variants to `path` functions

### ISSUE THREAD

**Issue by ClementNerma** [tauri-apps/tauri#4288]
### Describe the problem

All dir functions in `path` (`homeDir`, `configDir`, etc.) are asynchronous. This is great as a default behaviour, but sometimes it's extremely inconvenient.

I'm currently building an app where I define the application's path based on the user's configuration directory and then use it in many different functions, including some synchronous ones. With the current library, this is completely impossible as getting the user's config. directory results in a `Promise`. So I'm forced to make all these functions asynchronous just because of that.

```typescript
// This is a Promise<string>, I'd like a string.
export const DATA_DIR = path
  .configDir()
  .then((configDir) => path.join(configDir, 'Writer'))
```

### Describe the solution you'd like

Would it be possible to make synchronous counterparts of these methods? This would be quite useful in this scenario, and fetching these directory's path is extremely fast so it wouldn't make the app unresponsive.

**Comment by amrbashir** [comment]
this is not possible currently due to some limitation, subscribe to https://github.com/tauri-apps/wry/issues/454 for when it is resolved.
