### ISSUE TITLE
[feat] `fs.exists`

### ISSUE THREAD

**Issue by ClementNerma** [tauri-apps/tauri#4289]
### Describe the problem

Currently, there doesn't seem to be an API method to check if a file exists, which is problematic for obvious reasons.

### Describe the solution you'd like

Add a new method to check if a filesystem item exists. Signature could be something like:

```typescript
declare async function exists(path: string): Promise<boolean>;
```

It would behave like Rust's own `exists` method does.

**Comment by lucasfernog** [comment]
We will implement this on v2. For now you can use the fs-extra plugin: https://github.com/tauri-apps/tauri-plugin-fs-extra
