### ISSUE TITLE
[bug] Path Error: unable to determine base dir path

### ISSUE THREAD

**Issue by ClementNerma** [tauri-apps/tauri#4290]
### Describe the bug

The following code throws on my computer:

```typescript
import { path } from '@tauri-apps/api'
path.documentDir() // Path Error: unable to determine base dir path
```

### Reproduction

Run `path.documentDir()`

### Expected behavior

Should work properly.

### Platform and versions

```shell
Using WSL 2 on Windows 11, Ubuntu 20.04 LTS, Rust 1.61.0 stable.

Output of `pnpm tauri info`:


  › OS: Ubuntu 20.04 X64
  › Node.js: 18.3.0
  › npm: 8.11.0
  › pnpm: 7.1.9
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.13
  › @tauri-apps/api [NPM]: 1.0.0-rc.6
  › tauri [RUST]: 1.0.0-rc.14,
  › tauri-build [RUST]: 1.0.0-rc.12,
  › tao [RUST]: 0.9.1,
  › wry [RUST]: 0.17.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../public
  › devPath: http://localhost:8080/
  › framework: Svelte
  › bundler: Rollup

App directory structure
  ├─ node_modules
  ├─ src
  ├─ .git
  ├─ src-tauri
  ├─ .vscode
  └─ public
```

**Comment by lucasfernog** [comment]
On Linux the `documentDir` function uses `xdg-user-dirs`, so you need a `$HOME/.config/user-dirs.dirs` file to map well known dirs with their paths. You can read [this page](https://wiki.archlinux.org/title/XDG_user_directories) for more information. A good approach would be to fallback to some path relative to `path.homeDir` which should be available anyway.

**Comment by ClementNerma** [comment]
That's weird, the `dirs` crate correctly determines the config dir path on my system. Isn't that the library used in Tauri? (I may have misread)

**Comment by maubut** [comment]
How did you finally fix this?

**Comment by ClementNerma** [comment]
I never did unfortunately, but I didn't retry since then.

**Comment by Animeshz** [comment]
Any resolution? I'm facing the same while trying to run [en-croissant](https://github.com/franciscoBSalgueiro/en-croissant) chess database.

**Comment by Animeshz** [comment]
Nvm I use a base linux distro and no usual xdg dirs, and that app was trying to use `~/Documents`, ignore my previous comment. Thanks!
