### ISSUE TITLE
[feat] Give control back to calling application after exit

### ISSUE THREAD

**Issue by arturh85** [tauri-apps/tauri#4299]
### Describe the problem

I'm currently writing a REPL application which has the ability to launch the gui. But when the window is closed my application is exited instead of returning control to my REPL.

I tried preventing the exit using RunEvent::ExitRequested api.prevent_exit() - but the tauri event loop keep running, which of course makes sense for tray applications.

Could you please extend the API to allow my use case too?

### Describe the solution you'd like

Extend the ExitRequestedEventAction enum with f.e. "Allow" in Addition to "Prevent".
Then ExitRequestApi could be extended with allow_exit() in addition to prevent_exit().

**Comment by lucasfernog** [comment]
You can use [run_iteration](https://docs.rs/tauri/1.0.0/x86_64-apple-darwin/tauri/struct.App.html#method.run_iteration).
