### ISSUE TITLE
JS doesn't work with edge and no-server

### ISSUE THREAD

**Issue by mosheduminer** [tauri-apps/tauri#430]
**Describe the bug**
It appears that javascript does not work when the embedded server option is set to false, at least with edge. The edge dev tools also show `SCRIPT5007: SCRIPT5007: Unable to get property 'messageHandlers' of undefined or null reference` in this case, and I assume that the two are related.

**To Reproduce**
Build the vanillajs monolith app from the examples, the app behaves normally. However, if embedded server is set to false, and the app is rebuilt, the app loses all functionality (other than the input field, which is not JS based).

**Expected behavior**
Javascript based behavior should work. It does not.

**Platform and Versions (please complete the following information):**

OS: Windows 10 home
Node: 13.7.0
NPM: 6.13.6
Yarn: Not installed
Rustc: 1.41.0

**Additional context**
I first experienced this behavior with https://github.com/sirixdb/sirix-svelte-front-end, you can simply clone the repo, run `npm run export` (set embedded server to false) and run `npm run install`. The app will not work, and dev tools shows the above error.
Also, it was mentioned in the discord chat that someone else had the same problem, and since the app was entirely JS based (svelte), the screen remained blank. I believe that I have not experienced the same, as the above project uses SSR (sapper).

**Comment by nothingismagick** [comment]
Is this still happening with latest tauri @mosheduminer ?

**Comment by mosheduminer** [comment]
I just updated to the latest tauri, and the previous error no longer shows in devtools, which is good. However, my app still won't work, with the following errors in the console:

> CONSOLE21301: serviceWorker.register is rejected due to unsecure context or host restriction in about:blank.

> CSP14312: Resource violated directive 'default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'' in <meta http-equiv="Content-Security-Policy">: res://ieframe.dll/navcancl.htm#about:./client/shimport@1.0.1.js. Resource will be blocked.

> CSP14312: Resource violated directive 'default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'' in <meta http-equiv="Content-Security-Policy">: about:./client/client.d398a736.js. Resource will be blocked.

I removed the csp line from the tauri config, which removed the last two errors, but did not remove the first error (and I am pretty sure that sapper depends on the service worker, which would explain why the app still won't work. But I am not sure).

**Comment by nothingismagick** [comment]
Yeah - it's the service worker. I am not exactly sure how to address this, because service workers (like most of the WEB API) require a secure context.

I'll have a think about this.

**Comment by lucasfernog** [comment]
Closing it since the original problem has been fixed. Not sure if we have a tracking issue for service workers though (I think we do).
