### ISSUE TITLE
[bug] window.fetch do not work in release edition application

### ISSUE THREAD

**Issue by Nightwalk2001** [tauri-apps/tauri#4306]
### **It looks like this in development**
![image](https://user-images.githubusercontent.com/88429645/172826167-42ba2f32-0637-43d4-9a23-0b41b06e982b.png)

### **but below in release edition**

![image](https://user-images.githubusercontent.com/88429645/172825947-89f99376-9dc5-4c7e-a1ad-c5803cccbef3.png)

nothing is rendered, maybe the request does not executed

### Platform and versions

```shell
Environment
    › OS: Windows 10.0.19044 X64
    › rustc: 1.61.0
    › cargo: 1.61.0
    › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
    › @tauri-apps/cli [NPM]: 1.0.0-rc.13
    › @tauri-apps/api [NPM]: 1.0.0-rc.6
    › tauri [RUST]: 1.0.0-rc.14,
    › tauri-build [RUST]: 1.0.0-rc.12,
    › tao [RUST]: 0.9.1,
    › wry [RUST]: 0.17.0,

App

App directory structure
    ├─ .git
    ├─ .idea
    ├─ dist
    ├─ node_modules
    ├─ public
    ├─ src
    └─ src-tauri
```

### Additional context

additionally, i use **vercel's SWR** to manage request

my request FN is below:

![image](https://user-images.githubusercontent.com/88429645/172826830-832e4539-90f5-4adf-89c2-30449386cafa.png)

I use **cross-fetch** to polyfill

![image](https://user-images.githubusercontent.com/88429645/172826933-20800a1a-969a-4479-ade0-78c700c70652.png)

**Comment by FabianLars** [comment]
Enable the devtools (add the "devtools" feature flag to the tauri dependency in Cargo.toml) and see if it logs any errors into the devtools console.

A popular issue is cors (that's pretty much why the tauri http api exists).

**Comment by Nightwalk2001** [comment]
> Enable the devtools (add the "devtools" feature flag to the tauri dependency in Cargo.toml) and see if it logs any errors into the devtools console.
> 
> A popular issue is cors (that's pretty much why the tauri http api exists).

**wow! thanks very much, it's because cors!**
