### ISSUE TITLE
[feat] [MacOS] Disabled scroll rubber banding

### ISSUE THREAD

**Issue by mantou132** [tauri-apps/tauri#4309]
### Describe the problem

while preserving smooth scrolling, disabled scroll rubber banding, like native app

### Describe the solution you'd like

Whether cocoa has related API, I don't know

**Comment by lorenzolewis** [comment]
This is most likely something you'd achieve through CSS. Take a look at https://www.bram.us/2016/05/02/prevent-overscroll-bounce-in-ios-mobilesafari-pure-css/.

Since this is essentially a web view being rendered by Tauri, most of this logic you'd handle at the web layer.

**Comment by trevorparscal** [comment]
This can be fixed in CSS using something like this:

```
body {
	position: fixed;
	width: 100%;
	height: 100%;
	overflow: hidden;
}
```

**Comment by wusyong** [comment]
I would like to give a summary that macOS doesn't have scrollView. It's [only supported on iOS](https://developer.apple.com/documentation/webkit/wkwebview/1614784-scrollview?language=objc).
There is also a StackOverflow [issue](https://stackoverflow.com/questions/39929552/disable-bounce-scrolling-for-wkwebview-in-macos) mentioned about this.
So on macOS, we can only use workaround above.
For iOS, we could add it once it has alpha release on tauri.

**Comment by finnnnnnnnnnnnnnnnn** [comment]
I can't seem to get the the css from trevorparscal to work. I'm using Sycamore and Tailwind. Does anyone have any suggestions?
```    
view! { cx,
        body(class="bg-gray-500 fixed w-full h-full overflow-hidden"){
        }   
    }
```

**Comment by 0cch0** [comment]
simple way
```
html {
  overscroll-behavior: none;
}
```
