### ISSUE TITLE
Create public GitHub Action for building simple Tauri apps

### ISSUE THREAD

**Issue by khionu** [tauri-apps/tauri#431]
For simple use cases where all that is needed is rendering a webpage, it would be very easy to provide, at no expense to ourselves, a GitHub Action that builds the webpage as a Tauri App, making the artifacts ready to push into a GitHub Release. This would provide a route for app developers to not install any of our Rust components for simpler projects.

Further reading:
https://help.github.com/en/actions/building-actions/publishing-actions-in-github-marketplace

**Comment by lucasfernog** [comment]
https://github.com/tauri-apps/tauri-action
