### ISSUE TITLE
Events dont work after Update on Windows

### ISSUE THREAD

**Issue by PeShor** [tauri-apps/tauri#433]
**Describe the bug**
The events no longer work after the update. I took the old code from version 0.3.1 and it still worked there but not on 0.4.

**To Reproduce**
Update to 0.4

**Expected behavior**
That the Events work.

**Platform and Versions (please complete the following information):**

Operating System - Windows_NT(10.0.17763) - win32/x64
Node.js environment
  Node.js - 12.14.0
  tauri.js - 0.4.1
Rust environment
  rustc - 1.41.0
  cargo - 1.41.0
  tauri-bundler - 0.4.0
Global packages
  NPM - 6.13.4
  yarn - Not installed
App
  tauri - 0.4
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  Windows - Edge
  distDir - ../dist
  devPath - http://localhost:8080
JS Framework
  VueJS - vue@2.6.11

**Additional context**
JS file
```
tauri.emit('hello', `Number of times called: ${this.count}`)
```
and
```
tauri.setup();
tauri.listen('reply', res => {this.msg = res.payload.msg}, false);
```

RUST file
```
tauri::AppBuilder::new()
        .setup(|_webview, arg|{
            let handle = _webview.handle();
            tauri::event::listen(String::from("hello"), move |msg| {
                #[derive(Serialize)]
                pub struct Reply {
                    pub msg: String,
                    pub rep: String,
                }

                let reply = Reply {
                    msg: format!("{}", msg).to_string(),
                    rep: "something else".to_string(),
                };

                tauri::event::emit(
                    &handle,
                    String::from("reply"),
                    serde_json::to_string(&reply).unwrap(),
                );

                println!("Message from emit:hello => {}", msg);
            });
        })
        .build()
        .run();
```

**Comment by nothingismagick** [comment]
Will look into this. Thanks!

**Comment by nothingismagick** [comment]
Can you see if the latest version resolves this for you @PeShor ?

**Comment by PeShor** [comment]
unfortunately, it's still not working.

**Comment by jbolda** [comment]
We actually _just_ released another new version with Windows related fixes.

**Comment by PeShor** [comment]
Now the CLI to Rust works, but i dont get an answer :( Maybe Somting wrong?
```
 tauri.setup();
 tauri.listen('reply', res => {this.msg = res.payload.msg}, false);
```
or changed anything?

**Comment by lucasfernog** [comment]
tauri.setup() isn't really a function, so it'll crash, not sure how you're running it.
