### ISSUE TITLE
[bug]  Uncaught (in promise) TypeError: window.__TAURI_IPC__ is not a function

### ISSUE THREAD

**Issue by wychl** [tauri-apps/tauri#4332]
### Describe the bug

<img width="684" alt="image" src="https://user-images.githubusercontent.com/9290630/173465234-5140b859-48f4-4b3a-a5e6-05a55d0dcc0f.png">

<img width="684" alt="image" src="https://user-images.githubusercontent.com/9290630/173465276-3264bfc6-6669-466b-85a0-9345c60476c5.png">

### Platform and versions

```shell
yarn run v1.22.18
$ tauri info

Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 16.10.0
  › npm: 7.24.0
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.13
  › @tauri-apps/api [NPM]: 1.0.0-rc.6
  › tauri [RUST]: 1.0.0-rc.14,
  › tauri-build [RUST]: 1.0.0-rc.12,
  › tao [RUST]: 0.9.1,
  › wry [RUST]: 0.17.0,

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  › distDir: 
  › devPath: http://127.0.0.1:8080/
  › framework: Vue.js (Vue CLI)
  › bundler: Webpack

App directory structure
  ├─ isolation-dist
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .git
  └─ src
✨  Done in 15.37s.
```

**Comment by lucasfernog** [comment]
Does it still happen if you change `"devPath": "http://127.0.0.1:8080/"` to `"devPath": "http://localhost:8080/"`? If so, can you share a repo we can use to reproduce it?

**Comment by wychl** [comment]
@lucasfernog https://github.com/wychl/devutil

**Comment by lucasfernog** [comment]
@wychl I couldn't reproduce the issue. I executed `yarn` and `yarn serve` in a terminal window, then `yauri tauri dev` in a separate terminal, all in the same machine. Can you check what's the value of `window.location.origin`?

**Comment by wychl** [comment]
@lucasfernog  `window.location.origin` is  http://localhost:8080, my computer is darwin system

**Comment by lucasfernog** [comment]
So it should be working. How are you running the app? I can't reproduce it.

**Comment by amrbashir** [comment]
are you running the app in firefox? because the screenshots show the devtools of firefox. Tauri APIs doesn't work there, you need to run `tauri dev`.

**Comment by wychl** [comment]
@amrbashir @lucasfernog run `yarn run serve`, `yarn tauri dev` , chrome or firefox  have same problem problem.i use `vue-cli-plugin-tauri` plugin

starting in terminal 
<img width="953" alt="截屏2022-06-16 07 15 16" src="https://user-images.githubusercontent.com/9290630/173957865-218491fb-4d56-4de2-9222-577f92b6d676.png">
<img width="953" alt="截屏2022-06-16 07 13 20" src="https://user-images.githubusercontent.com/9290630/173957873-7459b5ef-c74e-41ec-892f-5793f26a5e09.png">

https://user-images.githubusercontent.com/9290630/173957885-fb107fdb-d5ce-46c8-8ceb-e71b82be6b28.mov

**Comment by lucasfernog** [comment]
You can't open the app url in the browser, it must be in the Tauri window unless you use the tauri-invoke-http crate.
