### ISSUE TITLE
1.0.0RC15 Reports as RC 14 in npm

### ISSUE THREAD

**Issue by nmthastings** [tauri-apps/tauri#4334]
I just so happened to be making a fresh tauri app when RC15 was pushed out. It reports as RC14 in npm at the moment. Not sure if this is npm just being slow or not, but figured I'd point it out.
![rc14_bug](https://user-images.githubusercontent.com/58537830/173488735-29765c52-b352-4a50-86b6-f81d880cc024.png)

**Comment by lucasfernog** [comment]
`@tauri-apps/cli` is still on `1.0.0-rc.13` because the CI failed, I'm fixing it right now and it should be released soon. Thanks for the report!

**Comment by lucasfernog** [comment]
Btw `rc.15` is the version of the core crate, and the latest CLI will be rc.14 indeed. Just waiting on the CI.

**Comment by lucasfernog** [comment]
Done.
