### ISSUE TITLE
[docs]  Application Debugging

### ISSUE THREAD

**Issue by adminSxs** [tauri-apps/tauri#4340]
https://tauri.studio/v1/guides/debugging/application
i use 
```rust
   let menu = Menu::new();
    tauri::Builder::default()
        .setup(|app| {
            #[cfg(debug_assertions)]
            {
                let window = app.get_window("main").unwrap();
                window.open_devtools();
                window.close_devtools();
                Ok(())
            }
        })
        .menu(menu)
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
```
![image](https://user-images.githubusercontent.com/15902505/173621544-e27d4e2d-6db8-4e01-a191-9894821eb1e9.png)

this devTools, in console will show use `@tauri-apps/api/http` fetch response data,but in network no any network request infomartion?

**Comment by lucasfernog** [comment]
When you use `@tauri-apps/api/http` the requests goes through the Rust layer instead of the webview, so it won't show up in the devtools network tab. You can see some log information if you enable log in the Rust side, for instance using https://github.com/tauri-apps/tauri-plugin-log/
