### ISSUE TITLE
[feat] Allow disabling build types

### ISSUE THREAD

**Issue by VirxEC** [tauri-apps/tauri#4341]
### Describe the problem

Appimage is far from perfect. Some applications don't work with it - so it would be nice if a project could disable building appimages. Some apps might not work on Debian-based systems, etc. Having to spend that extra time waiting for the thing you know won't work to build just so another thing can build is kinda dumb, in my opinion.

### Describe the solution you'd like

In `tauri.conf.json`, I would like there to be an option that allows for the enabling/disabled of building these things. Disabling both would essentially disable building on Linux, at least until potentially more formats (like flatpak or snap) get supported. 

### Additional context

I know this is a minor thing, but as a Linux dev, this would be a nice QOL feature that shouldn't be too hard to implement as it's just adding a switch. I might be interested in looking into adding it myself, but I'm only semi-familiar with using Tauri and the Tauri CLI, not so much with how it works under the hood. Much love :heart: to all the devs that might read this.

**Comment by amrbashir** [comment]
did you configure the targets in your tauri.conf.json ? https://tauri.studio/v1/api/config#bundleconfig.targets

**Comment by VirxEC** [comment]
That's embarrassing, but thanks lol
