### ISSUE TITLE
[bug] $platform-$arch id inconsistency

### ISSUE THREAD

**Issue by LukerBV** [tauri-apps/tauri#4350]
### Describe the bug

The platform id is inconsistent between the JS api and the launcher update json (and possibly elsewhere?)

For example as stated here: https://tauri.studio/v1/api/js/modules/os/  
the platform for windows, x86-64 should be `win32-x86_64`

But the platform id in the json of the tauri updater becomes `windows-x86_64`  
darwin/x86-64 also becomes an even weirder `darwin-intel`
https://docs.rs/tauri/1.0.0-rc.16/tauri/updater/index.html#update-file-json-format

Can we make this two consistent, to avoid confusion and manual translation between the two?

### Platform and versions

```shell
1.0 rc16
```

**Comment by amrbashir** [comment]
this will be fixed in v2, see https://github.com/tauri-apps/plugins-workspace/pull/419
