### ISSUE TITLE
[bug] how to creat mini window?

### ISSUE THREAD

**Issue by NMTuan** [tauri-apps/tauri#4360]
### Describe the bug

I want create a new window with only 1px or 2px height, but it looks like 40px height.

same issue:  https://github.com/tauri-apps/tauri/issues/3970

### Reproduction

	const webview = new WebviewWindow('theUniqueLabel', {
		url: '/about',
		decorations: false,
		x: 0,
		y: screen.availHeight - 1,
		width: screen.availWidth,
		transparent: true,
		height: 1,
		alwaysOnTop: true
	});

### Expected behavior

I want create mini window.  1px height, full width, 
looks link the progress bar

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 101.0.1210.53
  › MSVC:
      - Visual Studio ���ɹ��� 2019
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: 1.0.0
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: Svelte

App directory structure
  ├─ .svelte-kit
  ├─ .vscode
  ├─ build
  ├─ node_modules
  ├─ src
  ├─ src-tauri
  └─ static
```

**Comment by amrbashir** [comment]
Can you post some screenshots? 

Edit:
I can reproduce it, the extra size is for the titlebar even if the decorations are disabled they are kinda still there but hidden (because that's the only way we can get aero-snap to work). What you want is a window of type `popup`, and we don't have an api for that yet (feel free to open another issue for it). 

What you need to do atm, is make the window transparent and only show the progress bar.

**Comment by NMTuan** [comment]
> Can you post some screenshots?
> 
> Edit: I can reproduce it, the extra size is for the titlebar even if the decorations are disabled they are kinda still there but hidden (because that's the only way we can get aero-snap to work). What you want is a window of type `popup`, and we don't have an api for that yet (feel free to open another issue for it).
> 
> What you need to do atm, is make the window transparent and only show the progress bar.

I want create a Countdown timer in a new window: no frame, always ontop, no interactive events, just show current progress.
so it looks like a line, full width, 1px height.
