### ISSUE TITLE
[docs] Directory selection dialog filter array

### ISSUE THREAD

**Issue by Ketho22** [tauri-apps/tauri#4367]
https://github.com/tauri-apps/tauri/blob/13c2fc1ffe93163ec5ab0521fffe936e4f2b8077/tooling/api/src/dialog.ts#L45-L75
Hi all,
Both line 49 and 68 use the DialogFilter as an **array** property. Is this intended? If so, the example given in the [documentation](https://tauri.studio/v1/api/js/modules/dialog#open) is incorrect.

**Comment by FabianLars** [comment]
Yes they both use `DialogFilter[]` and yes the examples are therefore wrong (missing array). Thanks!

**Comment by vedant-z** [comment]
@Ketho22 What changes should be made in documentation to correct it?
If I want to work on it..

**Comment by lucasfernog** [comment]
@vedant-z the documentation is automatically generated, see #4424 for the fix for this particular case.

Thanks guys for reporting it!
