### ISSUE TITLE
[bug] In multiwindow app, second window loads html of "main" window when compile with "npm run tauri build"

### ISSUE THREAD

**Issue by Starolats** [tauri-apps/tauri#4372]
### Describe the bug

Create second window using Javascript API with separate html file. When compile with "npm run tauri dev" it works fine. See screenshot.
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/68425029/174145215-7a798e8e-441a-4b55-859d-1f02bcc038ae.png">

But when compile with "npm run tauri build", second window loads html file of "main" window. see screenshot
<img width="986" alt="image" src="https://user-images.githubusercontent.com/68425029/174146024-3d31369c-606f-4ad7-83d8-59dd5de1131a.png">

### Reproduction

1. Create Tauri project with vite+svelte using create-tauri-app.
2. Create new html file "index2.html"
3. Add to App.svelte script 
import { WebviewWindow } from "@tauri-apps/api/window";
  function newWindow() {
    const wnd = new WebviewWindow("label", {
      title: "Second window",
      url: "index2.html",
    });
    return wnd;
  }
4. Add button element
<button on:click={newWindow}>Create second window</button>
5. compile with "npm run tauri build"

### Expected behavior

Second window should load index2.html

### Platform and versions

```shell
> tauri "info"


Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 101.0.1210.53
  › MSVC:
      - Visual Studio Build Tools 2022
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: 1.0.0 (outdated, latest: 1.0.1)
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: Svelte

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

**Comment by FabianLars** [comment]
Is that index2.html file in the distDir when you build your app? If not tauri will always fall back to `index.html` (for spa compatibility or whatever)

**Comment by Starolats** [comment]
it is in the same folder as original index.html generated by vite+svelte template.

**Comment by lucasfernog** [comment]
By default your index2.html file is just ignored by vite when bundling. So you need a router or follow the [official vite multi-page app guide](https://vitejs.dev/guide/build.html#multi-page-app) where it states this difference between dev/build and how to configure vite to actually use your other html files.
