### ISSUE TITLE
[bug]  Failed to run custom build command for `rfd v0.9.0`

### ISSUE THREAD

**Issue by This-Is-Prince** [tauri-apps/tauri#4374]
### Describe the bug

![tauri1](https://user-images.githubusercontent.com/89686019/174229508-9bac0854-9d1d-4564-8802-b53e3574ec85.jpg)
![tauri2](https://user-images.githubusercontent.com/89686019/174229541-2ec3432b-d01a-4426-8242-b84c4d01f74f.jpg)
![tauri3](https://user-images.githubusercontent.com/89686019/174229547-c4939a1b-0402-4a60-bc4d-e9e713a833c2.jpg)

### Reproduction

run -> yarn create tauri-app
cd first/
run -> yarn tauri dev

### Expected behavior

![tauri4](https://user-images.githubusercontent.com/89686019/174229741-e8b10a9d-ef65-4023-9ac9-5349cd4d268d.jpg)

### Platform and versions

```shell
Environment
  > OS: Windows 10.0.22000 X64
  › Webview2: 102.0.1245.41
  › MSVC: 
      - Visual Studio Build Tools 2022
      - Visual Studio Community 2022
  › Node.js: 16.15.0
  › npm: 8.8.0
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ node_modules
  ├─ src
  └─ src-tauri
```

**Comment by betamos** [comment]
Looks like https://github.com/PolyMeilex/rfd/issues/75

Possible workaround: If you don't need dialogs, you could turn them off in tauri.conf.json, and only include the modules you need.

**Comment by PolyMeilex** [comment]
0.9.1 released, with the problematic feature disabled (`common-controls-v6`), at least for now. We'll decide what to do next once we gather more info about the problem.

**Comment by This-Is-Prince** [comment]
Now there is another error
![tauri6](https://user-images.githubusercontent.com/89686019/174352931-cf2b8651-7ca5-4978-a35e-0463994cd66e.jpg)

**Comment by lucasfernog** [comment]
@This-Is-Prince that looks unrelated to the rfd issue; are you using gnu or msvc toolchain?

**Comment by lucasfernog** [comment]
Ahh it's gnu. Looks like your PATH environment variable is wrong? it's trying to run `C:\Program` instead of the full path to windres.exe, unless you're using [sdk_dir](https://docs.rs/tauri-build/latest/tauri_build/struct.WindowsAttributes.html#method.sdk_dir).
Using the msvc toolchain is easier btw :D

**Comment by This-Is-Prince** [comment]
Thank you so much, sir
Now, I am using msvc toolchain, and it is working fine.
