### ISSUE TITLE
[bug] `cargo install tauri-bundler --force` throws an error about there being no binaries

### ISSUE THREAD

**Issue by BrunoBernardino** [tauri-apps/tauri#4377]
### Describe the bug

`cargo install tauri-bundler --force` throws an error about there being no binaries:

```
cargo install tauri-bundler --force
  shell: /usr/bin/bash -e {0}
  env:
    RELEASE_ID: 69703181
    PL_VENDOR_VERSION: 4.0.0
    Updating crates.io index
 Downloading crates ...
  Downloaded tauri-bundler v1.0.0
error: there is nothing to install in `tauri-bundler v1.0.0`, because it has no binaries
`cargo install` is only for installing programs, and can't be used with libraries.
To use a library crate, add it as a dependency in a Cargo project instead.
```

### Reproduction

You can see a GH action run at https://github.com/padloc/padloc/runs/6934254025?check_suite_focus=true below and the code for it is https://github.com/padloc/padloc/blob/01359835a03578e1dd02ceb85c9321d30e0df2fb/.github/workflows/publish-release.yml#L153-L164
![Screenshot from 2022-06-17 11-43-40](https://user-images.githubusercontent.com/1239616/174283569-ddb7f584-8053-426e-9a41-5930ddfd7bf6.png)

And here is the dependency/rust install step output:
![Screenshot from 2022-06-17 11-45-35](https://user-images.githubusercontent.com/1239616/174283833-e1b7d5a3-140a-4df2-9fff-6d940cbe502e.png)

### Expected behavior

It should install without problems.

### Platform and versions

```shell
This happens _before_ tauri is installed, and here is rust's versions:


  /home/runner/.cargo/bin/rustc -V
  rustc 1.61.0 (fe5b13d68 2022-05-18)
  /home/runner/.cargo/bin/cargo -V
  cargo 1.61.0 (a028ae4 2022-04-29)
  /home/runner/.cargo/bin/rustup -V
  rustup 1.24.3 (ce5817a94 2021-05-31)
  info: This is the version for the rustup toolchain manager, not the rustc compiler.
  info: The currently active `rustc` version is `rustc 1.61.0 (fe5b13d68 2022-05-18)`
``'
```

### Additional context

This was working fine a couple of days ago with the same code, with the same versions and code/commands: https://github.com/padloc/padloc/actions/runs/2501602319

**Comment by amrbashir** [comment]
tauri-bundler has been deprecated for a long time now, and has been part of the tauri-cli. please follow the guide on our website https://tauri.app/v1/guides/getting-started/prerequisites.

Edit: just saw you're still on a very very old version of alpha tauri and we stopped supporting that a while back. Please update to latest stable version `1.0.0`

**Comment by BrunoBernardino** [comment]
Thanks @amrbashir I'll try that and update here if that works, plus link the PR in case it helps others.

You might've looked at the `master` branch which is very out of date. On `v4` and the branch I linked above, we're using `"@tauri-apps/cli": "1.0.0-rc.10"` which should be fairly recent.

**Comment by amrbashir** [comment]
in that case, you still don't need `tauri-bundler`, just remove it and you should be fine.

**Comment by BrunoBernardino** [comment]
Thanks @amrbashir that was enough indeed!
