### ISSUE TITLE
[bug] `tray_handle.set_icon()`  slow and not working in loop(macOS)

### ISSUE THREAD

**Issue by rming** [tauri-apps/tauri#4388]
### Describe the bug

I want to set icon in loop for animation.
It worked at 50 ms intervals in previous rc.14, but it doesn't work in 1.0.0, I think it's because the `set_icon()` method is too slow.
It needs more intervals (200+ ms) in 1.0.0 to work properly.

In my app the user triggers an action via a keyboard hotkey and the app needs to show a loading animation on the tray icon to indicate the processing state

Not yet tested on Windows.

### Expected behavior

works with less intervals like previous rc.14, or some other method to animate a  tray icon?

### Platform and versions

```shell
yarn run v1.22.17
$ /Users/afa/git/repo/node_modules/.bin/tauri info

Environment
  › OS: Mac OS 12.3.1 X64
  › Node.js: 16.14.0
  › npm: 8.3.1
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: tauri: 'unsafe-eval' 'unsafe-inline' 'self'; script-src 'unsafe-eval' 'self'; img-src 'self' data: https:
  › distDir: ../dist
  › devPath: http://127.0.0.1:8080/
  › framework: Vue.js (Vue CLI)
  › bundler: Webpack

App directory structure
  ├─ dist
  ├─ patches
  ├─ node_modules
  ├─ updater
  ├─ public
  ├─ scripts
  ├─ .github
  ├─ src-tauri
  ├─ .git
  ├─ tmp
  └─ src
```

**Comment by rming** [comment]
a minimal example: https://github.com/Rming/tauri-tray-icon-animation

**Comment by rming** [comment]
Tested on Windows,  50 ms intervals  works well with "ico" icons.

**Comment by rming** [comment]
I tried changing the icon image size from 512x512 to 64x64.
And it worked ! 50 ms interval !
Performance regression does exist after 1.0.0, but it's enough for me now.

**Comment by amrbashir** [comment]
I think the bottle neck is that we encode the rgba back into png format, so ofc the bigger the icon gets the slower it will be. 
The ideal size for tray icons are 18x18 on macOS and 16x16 on Linux and windows.
The regression is definitely there but It is not worth to break the API again for it, especially since this can be avoided by using the ideal size for the icons.
