### ISSUE TITLE
[bug] Cannot hide title bar completely【windows】

### ISSUE THREAD

**Issue by mokeyish** [tauri-apps/tauri#4396]
### Describe the bug

I set `windows.decorations:false` and `windows.transparent:true` , There is still a  title-bar .

![image](https://user-images.githubusercontent.com/16131917/174463713-3c6e4370-8304-4b4a-9713-5df9d22a4eb5.png)

### Reproduction

1.  set  `windows.decorations:false` and `windows.transparent:true`
2.  css 
    ```css
    * {
        background: transparent;
    }
    ```
3.  title bar appears.
   
![image](https://user-images.githubusercontent.com/16131917/174463949-030d7554-4a72-4e10-8d06-5a5685aa5e5a.png)

### Expected behavior

hide title bar completely

### Platform and versions

```shell
windows 11
```

**Comment by amrbashir** [comment]
That's the menu bar, unfortunately on Windows, the menu bar can't play nicely with decorations disabled so if you want to remove the decorations, you should hide the menu bar.

**Comment by mokeyish** [comment]
thanks
