### ISSUE TITLE
[solve] How to use HTTP to request other API interfaces

### ISSUE THREAD

**Issue by Jzow** [tauri-apps/tauri#4399]
### Describe the bug

Every time I run and debug, I see yes tarui://localhost, However, my interface is cross domain. I tried to add a configuration, but it still doesn't take effect. I've seen the official HTTP support plug-in. Its version is different from the one I'm building now. It's old

### Platform and versions

```shell
Environment
  › OS: Mac OS 12.2.1 X64
  › Node.js: 16.13.1
  › npm: 8.1.2
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ app
  ├─ node_modules
  ├─ public
  ├─ build
  └─ src
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by Richyeoh** [comment]
你好，这个问题你解决了吗，我也遇到了类似的问题，release 之后 就成了 https://tauri.localhost 然后，然后我用的websocket是ws的所以无法使用。

**Comment by Jzow** [comment]
@Richyeoh  HI，这个问题已经解决，可以参考 [tauri-plugin-localhost](https://github.com/tauri-apps/tauri-plugin-localhost)，引用这个插件就可以，如若有plugin使用问题，可以在plugin提交issue

**Comment by Houiin** [comment]
> @Richyeoh HI，这个问题已经解决，可以参考 [tauri-plugin-localhost](https://github.com/tauri-apps/tauri-plugin-localhost)，引用这个插件就可以，如若有plugin使用问题，可以在plugin提交issue

[tauri-plugin-localhost](https://github.com/tauri-apps/tauri-plugin-localhost)这个插件好像目前无法查看issue了。 

按照readme.md配置后，tauri生成的exe直接闪退。 

我是在html里面加了个`<iframe src="http://mydomain.local">`，而tauri release出来的exe访问的是`https://tauri.local`，因此没法正常访问嵌入的http页面。 看起来这个插件能行，但是目前还不知道怎么使用
