### ISSUE TITLE
integrated dev server

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#44]
@lucasfernog and I talked about this, and we see two options for the integrated devserver for html/js/css assets:

1. Use our tiny_http server that we ship in bundles that use the cloud* pattern
2. Construct a `webpack-dev-server` with babel for transpilation

This is needed when people don't use the devserver from their front-end framework. The positive part about using webpack is that we can then reuse some of the logic for running our specific dechunking / anti-dynamic imports etc.

**Comment by doni7724** [comment]
webpack-dev-server

**Comment by nothingismagick** [comment]
# Good 🤖

**Comment by saucesaft** [comment]
I had this idea recently, wouldn't it be better for the user to supply the frontend's devserver command into tauri's config file and when yarn tauri dev is runned, it will launched the dev server and then the tauri app?

**Comment by lucasfernog** [comment]
@saucesaft That was implemented on #500
