### ISSUE TITLE
[feat] Bundle Tauri apps as RPM

### ISSUE THREAD

**Issue by DoodlesEpic** [tauri-apps/tauri#4402]
### Describe the problem

It would be nice to have rpm packages for Tauri apps as there is no Flatpak support yet and alien does not manage to convert the deb packages (at least in my personal attempts).

### Describe the solution you'd like

Bundling the application to an rpm package just like the deb packaging is done right now.

### Alternatives considered

Flatpaks are somewhat of an alternative, but I believe actual rpm packages would be great, especially because we get the advantage of the really small bundle size of Tauri apps, unlike AppImages and Flatpak alike.

**Comment by FabianLars** [comment]
Yep that's on my personal todo (if someone else wants to take a stab at it instead that's fine too) and i'm really surprised we seemingly didn't have a feature request for that already since i talked about it a few times in other issues already 🤔 

But yea, now with v1 out of the way work on it should start fairlyyy soon :v:

**Comment by DoodlesEpic** [comment]
> should start fairlyyy soon

Mandatory: _soon_ ™️

**Comment by FabianLars** [comment]
Exactly! 😂 But honestly this is fairly high on my list and shouldn't be too hard (hopefully), i'm just waiting for us to finish our organizational/planning talks and stuff 🤷

**Comment by zigazajc007** [comment]
When I'm donating to Tauri, the money will just go for the security audit. So I'm willing to donate straight to the person that will implement any feature from this list:
- rpm support ($50) https://github.com/tauri-apps/tauri/issues/4402
- flatpak support ($50) #3619 
- snap support ($50)
- saveDialog that would open when JS wants to download a text / file ("download" attribute) ($50) https://github.com/tauri-apps/wry/pull/530

I know that those prices are really low, but I bet a lot of people are waiting for those features to be added before they can switch to Tauri. So if we can find some more people to donate for those features to be added, it can become profitable for a programmer to start working on them.

**Comment by DoodlesEpic** [comment]
@zigazajc007 You should also send this bounty to the people over at cargo-bundle since implementing it there would make it pretty easy to bring it to Tauri (since the Tauri bundler is just a fork of cargo-bundle). https://github.com/burtonageo/cargo-bundle/issues/115

**Comment by zigazajc007** [comment]
> @zigazajc007 You should also send this bounty to the people over at cargo-bundle since implementing it there would make it pretty easy to bring it to Tauri (since the Tauri bundler is just a fork of cargo-bundle). [burtonageo/cargo-bundle#115](https://github.com/burtonageo/cargo-bundle/issues/115)

You have just "pinged" / mention them, so most likelly they will see that now. Thanks.

**Comment by nothingismagick** [comment]
A couple comments: we have adapted cargo-bundle to a great extent and diverged to the point that mere updates to that project won't affect us here.

Secondly, I generally have concerns with bounty systems, especially when they are not organised by the people responsible for the project. We have never discussed bounties in the team, and I am not sure how everyone else sees them. Ultimately, buried in an issue is not the right place to communicate such a thing, and 50$ bounties probably wouldn't motivate anyone anyway.  Finally, there is work being done on the bundler in the working group, so this kind of wild bounty approach is likely to collide with that work.

That all said, its wonderfully kind of you to offer it.

**Comment by zigazajc007** [comment]
> A couple comments: we have adapted cargo-bundle to a great extent and diverged to the point that mere updates to that project won't affect us here.

Awesome, thanks.

> Secondly, I generally have concerns with bounty systems, especially when they are not organised by the people responsible for the project. We have never discussed bounties in the team, and I am not sure how everyone else sees them.

Do you think bountly system will be ever implemented in the future?

> and 50$ bounties probably wouldn't motivate anyone anyway

A lot of programmers in the Tauri project seems to work for free. So $50 will give some developers a bit more motivation. Expecially to those who lives in poorer countries like me. So $50 can sustain them for days.

> Finally, there is work being done on the bundler in the working group, so this kind of wild bounty approach is likely to collide with that work.

So, if I donate to Tauri project on opencollective.com, is it possible for your to give this money to developers that have worked on those issues / features?

Currenly I have only donated $200 to Tauri Project and at the end of the month I can do $300. So total would be $500.

**Comment by zyppe** [comment]
Is it possible to just generate binary file such as .so or executable file so I could just write my own spec to generate needed rpm?

**Comment by FabianLars** [comment]
@210hcl The `tauri build` command always creates a plain executable (`target/release/appname`). This executable is the same Tauri's bundler copies into the .deb and appimage bundles.

**Comment by fetzsav** [comment]
> When I'm donating to Tauri, the money will just go for the security audit. So I'm willing to donate straight to the person that will implement any feature from this list:
> 
>     * rpm support ($50) [[feat] Bundle Tauri apps as RPM #4402](https://github.com/tauri-apps/tauri/issues/4402)
> 
>     * flatpak support ($50) [[feat] Bundle Tauri apps as Flatpak #3619](https://github.com/tauri-apps/tauri/issues/3619)
> 
>     * snap support ($50)
> 
>     * saveDialog that would open when JS wants to download a text / file ("download" attribute) ($50) [feat: Add download started and download completed callbacks wry#530](https://github.com/tauri-apps/wry/pull/530)
> 
> 
> I know that those prices are really low, but I bet a lot of people are waiting for those features to be added before they can switch to Tauri. So if we can find some more people to donate for those features to be added, it can become profitable for a programmer to start working on them.

Hey, I am wondering if you are still offering this bounty?
https://github.com/tauri-apps/tauri/pull/6532

**Comment by zigazajc007** [comment]
> > When I'm donating to Tauri, the money will just go for the security audit. So I'm willing to donate straight to the person that will implement any feature from this list:
> > ```
> > * rpm support ($50) [[feat] Bundle Tauri apps as RPM #4402](https://github.com/tauri-apps/tauri/issues/4402)
> > 
> > * flatpak support ($50) [[feat] Bundle Tauri apps as Flatpak #3619](https://github.com/tauri-apps/tauri/issues/3619)
> > 
> > * snap support ($50)
> > 
> > * saveDialog that would open when JS wants to download a text / file ("download" attribute) ($50) [feat: Add download started and download completed callbacks wry#530](https://github.com/tauri-apps/wry/pull/530)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I know that those prices are really low, but I bet a lot of people are waiting for those features to be added before they can switch to Tauri. So if we can find some more people to donate for those features to be added, it can become profitable for a programmer to start working on them.
> 
> Hey, I am wondering if you are still offering this bounty? #6532

Yes

**Comment by saolof** [comment]
As a Silverblue user, I might be willing to duplicate the bounty for Flatpak support specifically.

**Comment by 0-don** [comment]
I  added support for arch and rpm via github actions

https://github.com/0-don/clippy/blob/master/.github/workflows/release.yml
