### ISSUE TITLE
[feat] Running certain folders externally without code change

### ISSUE THREAD

**Issue by erikpa1** [tauri-apps/tauri#4404]
### Describe the problem

Hi, I'm trying to compile project in tauri, which has 2GB (its 360 tour made with three js and react). I have tour on web which is perfectly working, but I want to deploy desktop app for my client (which one I want to lock on 1 year license) without code rewriting (ideally). But I can't compile so big project because of: STATUS_STACK_BUFFER_OVERRUN.

### Describe the solution you'd like

The best thing for me is to define in tauri.conf.json something like: 

"public": "{myfoldername}"

or maybe some native behaviour when tauri will search for fetch commands in "public" folder near the exe file.

**Comment by lucasfernog** [comment]
We embed the dist assets in the binary, and we really do not recommend embedding a 2GB file anyway. You should use a resource instead, or download the file at startup.

Reference for resource usage:
https://github.com/tauri-apps/tauri/blob/1a2e141badd5f18bd99b83c3be95ad288fda8650/examples/resources/src-tauri/tauri.conf.json#L22
https://github.com/tauri-apps/tauri/blob/1a2e141badd5f18bd99b83c3be95ad288fda8650/examples/resources/src-tauri/src/main.rs#L22

https://tauri.app/v1/api/js/modules/path#resolveresource
https://tauri.app/v1/api/js/modules/tauri#convertfilesrc
