### ISSUE TITLE
[bug] build error

### ISSUE THREAD

**Issue by lhf6623** [tauri-apps/tauri#4408]
### Describe the bug

 cargo tauri build
Error: Try running with --verbose to see command output

Caused by:
    0: failed to bundle project
    1: error running candle.exe
    2: error running candle.exe
    3: `系统找不到指定的文件。 (os error 2)`
    4: 系统找不到指定的文件。 (os error 2)

cargo tauri --verbose
error: 'cargo tauri' requires a subcommand but one was not provided

USAGE:
    cargo tauri [OPTIONS] <SUBCOMMAND>

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 102.0.1245.44
  › MSVC: 
      - Visual Studio Community 2022
  › Node.js: 16.15.0
  › npm: 8.11.0
  › pnpm: 7.2.1
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: Vue.js

App directory structure
  ├─ .vscode
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

**Comment by lhf6623** [comment]
Running [tauri_bundler::bundle::windows::msi::wix] candle for "main.wxs"
     Running [tauri_bundler::bundle::common] Command `C:\Users\lhf6623\AppData\Local\tauri/WixTools\candle.exe  -arch x64 main.wxs -dSourceDir=D:\project\tauri-app\src-tauri\target\release\tauri-app.exe`
     
     That's the problem. The program finds wixtools under the global directory, which is an empty directory

**Comment by amrbashir** [comment]
can you try deleting `C:\Users\lhf6623\AppData\Local\tauri\WixTools` directory and try again?

**Comment by lhf6623** [comment]
> 您可以尝试删除目录并重试吗？`C:\Users\lhf6623\AppData\Local\tauri\WixTools`

![image](https://user-images.githubusercontent.com/29174474/174698938-c2a2339e-ef74-468a-8f4c-24bb37b95926.png)

**Comment by lhf6623** [comment]
The directory is automatically generated

**Comment by amrbashir** [comment]
yeah that's fine, these are tools needed for building the msi and since the build is now successful, I suspect, the download of these files were interrupted somehow and got corrupt.
