### ISSUE TITLE
[bug] window.__TAURI__ doesn't get injected if the Entry Url (devPath/distPath) is not an origin url (ie: entry url is a subpage)

### ISSUE THREAD

**Issue by imadbz** [tauri-apps/tauri#4414]
### Describe the bug

if we specify the url to be an origin (ex: http://localhost:3000), global tauri gets injected in the window.
![image](https://user-images.githubusercontent.com/3145272/174723951-7994b3ff-83dc-4889-9303-a6d4eddb0be2.png)

if we specify the url to be an inner page (ex: http://localhost:3000/about), global tauri doesn't get injected.
![image](https://user-images.githubusercontent.com/3145272/174724015-04162c6f-cd60-4433-bb33-f2eb3157a5a5.png)

### Reproduction

specify devPath to an inner page. (ex: http://localhost:3000/about)
run the app
inspect and check for window.__TAURI vars 

### Platform and versions

```shell
Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 16.15.0
  › npm: 8.10.0
  › pnpm: 6.11.0
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
Error running CLI: only one package mangager should be used, but found npm and yarn
please remove unused package manager lock files
➜  devutil git:(master) ✗ npm run tauri info

> devutil@0.0.0 tauri
> tauri "info"


Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 16.15.0
  › npm: 8.10.0
  › pnpm: 6.11.0
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/about
  › framework: Vue.js

App directory structure
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .git
  └─ src
```

**Comment by imadbz** [comment]
would write a fix for it if the core team agrees that it is a bug and not an intended behaviour

**Comment by lucasfernog** [comment]
Thanks for the report! I just fixed the issue while checking the problem, but will love to see your PR next time :heart: 

Fix will be available soon in v1.0.1.

**Comment by imadbz** [comment]
awesome. you are amzing

**Comment by Soya-xy** [comment]
When I use `tauri::Windows::WindowBuilder` create a new window to the URL is not the current devPath (eg: http://localhost:3000), but another project (eg: http://localhost:3333), the other items `window.__TAURI__` is undefined if you want to use the tauri API.

Is this currently supported?

All projects run in the same Tauri app, but there are 2 different project addresses

**Comment by lucasfernog** [comment]
You'll need to merge both somehow. For instance you can use Webpack dev proxy in development mode, and move all assets to the same folder for production. We don't support multiple dev URLs currently.

**Comment by imadbz** [comment]
sorry to comment on a closed issue again, but the fix worked for localhost but not if you use an external url (or maybe because of https://, couldn't confirm).

@lucasfernog issue should be reopened?

**Comment by FabianLars** [comment]
@imadbz Tauri's apis are intentionally not injected into windows with external urls.

**Comment by jswhisperer** [comment]
Would be a nice optional setting.

As a lot of browser APIs are missing or not functional, it can be an easy workaround to shell execute open "url" do the operation for example WebAutn createCredentials then `store` the result. or websocket etc.
