### ISSUE TITLE
build error[bug] 

### ISSUE THREAD

**Issue by Zhiqiang-Wu** [tauri-apps/tauri#4422]
### Describe the bug

package.json "version": "2.0.0" ， build no problem.
package.json "version": "2.0.0-alpha"，build error
![image](https://user-images.githubusercontent.com/56793420/174829733-37ed7d0e-ed1e-4455-8cb9-16cac7ea649a.png)

### Platform and versions

```shell
windows 10 x64
node 16
pnpm 7
tauri 1.0.0
```

**Comment by FabianLars** [comment]
wix only works with numeric versions (major.minor.patch), there's nothing we can do about it.
