### ISSUE TITLE
[feat] Extract contents for archives which contains a single directory

### ISSUE THREAD

**Issue by haptiq-sondre** [tauri-apps/tauri#4425]
### Describe the problem

When an archive contains a single directory, the desired behavior on extraction is often that only the directory's contents should be extracted.

### Describe the solution you'd like

I've currently used a third-party crate [zip-extract](https://crates.io/crates/zip-extract) with their example code which do exactly what I need:
```
let archive: Vec<u8> = download_my_archive()?;
let target_dir = PathBuf::from("my_target_dir"); // Doesn't need to exist

// The third parameter allows you to strip away toplevel directories.
// If `archive` contained a single directory, its contents would be extracted instead.
zip_extract::extract(Cursor::new(archive), &target_dir, true)?;
```

It would be nice have this functionality directly in Tauri, possibly by introducing a `strip_toplevel` argument to the `extract_into` function.

### Alternatives considered

Suggested alternative from @lucasfernog in Discord thread:
Use `with_files` (https://docs.rs/tauri/1.0.0/tauri/api/file/struct.Extract.html#method.with_files) as done here: https://github.com/tauri-apps/tauri/blob/45981851e35119266c1a079e1ff27a39f1fdfaed/core/tauri/src/updater/core.rs#L815

**Comment by canhkieu** [comment]
I'm trying to make an #[tauri::command] to unzip file. Do you have any example about this feature. Thanks

**Comment by amrbashir** [comment]
extract api will be removed in v2 so I am gonna close this issue. Use `zip-extract` or similar crates

**Comment by 0xDevrim** [comment]
> I'm trying to make an #[tauri::command] to unzip file. Do you have any example about this feature. Thanks

For future visitors, I've just used `Xplorer` app to strip out the unzipping section (https://github.com/kimlimjustin/xplorer)

```
[dependencies]
tokio = { version = "^1", features = ["macros", "parking_lot", "rt"] }
zip = "0.6.2"
```

`main.rs`
```
...
use std::fs;
use std::fs::File;
...
#[tauri::command]
async fn decompress_from_zip(zip_path: String, target_dir: String){
    let mut zip = zip::ZipArchive::new(File::open(zip_path).unwrap()).unwrap();
    fs::create_dir_all(target_dir.clone()).unwrap();
    for i in 0..zip.len() {
        let mut file = zip.by_index(i).unwrap();
        let file_outpath = match file.enclosed_name(){
            Some(name) => target_dir.clone() + "/" + &name.to_str().unwrap(),
            None => continue,
        };
        let file_name = file.name();
        if file_name.ends_with('/') {
            fs::create_dir_all(&file_outpath).unwrap();
        } else {
            let mut outfile  = File::create(file_outpath).unwrap();
            std::io::copy(&mut file, &mut outfile).unwrap();
        }
    }
}

#[tokio::main]
async fn main() {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![
            ...
            decompress_from_zip
        ])
        ...
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

`js`
```
invoke('decompress_from_zip', { zipPath: `${appDataDirPath}/example.zip`, targetDir: appDataDirPath });
```
