### ISSUE TITLE
[bug] Error running CLI: failed to run cargo: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by tnrich** [tauri-apps/tauri#4428]
### Describe the bug

```
$ tauri init --app-name tauri-ove --window-title 'Open Vector Editor' --dist-dir ../dist --dev-path ../dist
✨  Done in 0.24s.
>> Updating "tauri.conf.json"
>> Running final command(s)

    Your installation completed.

    $ cd tauri-ove
    $ yarn install
    $ yarn tauri dev
    
✨  Done in 19.70s.
tnrich@Thomass-MBP Sites % cd tauri-ove 
tnrich@Thomass-MBP tauri-ove % yarn install
yarn tauri dev
yarn run v1.22.18
warning package.json: No license field
$ tauri dev
Error running CLI: failed to run cargo: No such file or directory (os error 2)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Platform and versions

```shell
tnrich@Thomass-MBP tauri-ove % npm run tauri info

> tauri
> tauri "info"


Environment
  › OS: Mac OS 11.6.0 X64
  › Node.js: 16.13.0
  › npm: 8.1.0
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: Not installed!
  › rustc: Not installed!
  › cargo: Not installed!
  › Rust toolchain: 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.0 (no lockfile),
  › tauri-build [RUST]: no manifest (no lockfile),
  › tao [RUST]: no manifest (no lockfile),
  › wry [RUST]: no manifest (no lockfile),

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: ../dist

App directory structure
  ├─ dist
  ├─ node_modules
  └─ src-tauri
```

### Additional context

It seems like I need to have these packages installed for tauri to work? 
```
  › pnpm: Not installed!
  › rustup: Not installed!
  › rustc: Not installed!
  › cargo: Not installed!
```

Not sure why they didn't get installed when running the tauri installer. At the very least there should be a check for them and a warning message emitted with instructions on how to install those various packages. 

Thanks!

**Comment by lucasfernog** [comment]
You need to follow our setup guide: https://tauri.app/v1/guides/getting-started/prerequisites

**Comment by lucasfernog** [comment]
I'll add a check for this in the CLI.

**Comment by tgaeta** [comment]
> You need to follow our setup guide: https://tauri.app/v1/guides/getting-started/prerequisites

For the lot of us who learned of Tauri from [ProductHunt](https://www.producthunt.com/posts/tauri-2), and then being routed to the homepage where the quickstart says: `pnpm create tauri-app`, nowhere am I led to believe that there are prerequisites. Nevertheless, I get 
~~~shell
Error `cargo` command not found. Please follow the Tauri setup guide: https://tauri.app/v1/guides/getting-started/prerequisites
~~~
So I follow the link and low and behold, I need Rust. So I install Rust and try `pnpm tauri dev` again. 
~~~shell
Error `cargo` command not found
~~~
So I look through `tauri/issues` and come across this page where it's closed with a link to the setup guide https://tauri.app/v1/guides/getting-started/prerequisites

So the next set of commands was my natural response.
~~~shell
cd ..
rm -rf tauri-test
~~~

**Comment by SteveMitto** [comment]
I encountered the same error and all I did was install cargo and all went well

`sudo apt  install cargo`

**Comment by gabrielccarvalho** [comment]
For me was a combo of not having rust installed, fixed by running this command:
`curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh`

And add `rustup` to your path manually. In my case, for the fish terminal is:

`set -Ua fish_user_paths $HOME/.cargo/bin`

**Comment by ThijsZijdel** [comment]
(Re-)Install Rust _(which includes Cargo)_ via homebrew


```bash
brew install rust
```
