### ISSUE TITLE
[feat] Change first menu content in macos

### ISSUE THREAD

**Issue by richerfu** [tauri-apps/tauri#4433]
### Describe the problem

<img width="445" alt="image" src="https://user-images.githubusercontent.com/32590310/174937519-ae864340-657d-4157-aaf3-8d780f192635.png">

Just like it. The first menu content can't be changed which named `app`.

### Describe the solution you'd like

It should can be changed by `configuration` or `func`？

**Comment by amrbashir** [comment]
This only exists in development and once you build the app it will be the correct name. And in the next release, the correct name will be used in development too.

note: on macOS, the first menu is always the app menu.
