### ISSUE TITLE
media permission denied [bug] 

### ISSUE THREAD

**Issue by Zhiqiang-Wu** [tauri-apps/tauri#4434]
### Describe the bug

Unable to call camera，unauthorized.
No related items found in devtools.

### Platform and versions

```shell
window10 x64
pnpm 7
nodejs 16
tauri 1.0.0
```

**Comment by amrbashir** [comment]
please share the full `tauri info` and if possible a minimal repro.

**Comment by Zhiqiang-Wu** [comment]
[demo.zip](https://github.com/tauri-apps/tauri/files/8963710/demo.zip)

start script:

```
umi dev
```

```
tauri dev
```

---

1、open media -> select reject -> console.log(err);

2、open media -> console.log(err); Immediate failure.

Unable to reacquire permissions.

Permission can be reset in the edge browser.

But webview2 can`t.

---

Reset site permissions in edge browser.

![img](https://user-images.githubusercontent.com/56793420/175207510-3ce8e38e-24cb-4177-981e-7e6b4e4bd89c.png)

**Comment by amrbashir** [comment]
users can delete `C:\Users\<user-name>\AppData\Local\<your-app-bundle-identifieer>\EBWebView` directory and it will reset the permissions state, so you can prompt them for it again.

**Comment by Interpause** [comment]
I don't think that is a proper solution, it certainly isn't user-friendly to request the user to do the above to reset permission state.

**Comment by FabianLars** [comment]
@Interpause You can handle that for your users in rust too.
And i know that's not what you were aiming at, the problem here is that actual solutions are blocked by https://github.com/MicrosoftEdge/WebView2Feedback/issues/2427 :/

Edit: Since this issue was just linked to from a really extensive issue a short additional note: In case someone wonders why we don't work around the missing permissions api by hooking into the PermissionRequested event (which by itself would be kinda annoying imo), the reason is: it doesn't work, see https://github.com/MicrosoftEdge/WebView2Feedback/issues/2672

**Comment by nishitha-burman** [comment]
Hello, we recently added the new experimental [Permission Management APIs](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#experimental-features). Can you check if this meets your needs?  https://github.com/MicrosoftEdge/WebView2Feedback/issues/2427#issuecomment-1399097515 Thanks!

**Comment by fortserious** [comment]
Hi @FabianLars , now that both of those WebView2Feedback issues have been resolved and the Permission Management APIs have been released, is it possible to hook into these APIs to reset permission state while the WebView2 app is open? The Rust solution won't work for us, as we can't expect our users to close down the app and delete the EBWebView directory themselves.

**Comment by FabianLars** [comment]
if you're using v2, yes (in v1 the webview bindings are too old). Then you can use the mentioned [SetPermissionState](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2profile4?view=webview2-1.0.1661.34&preserve-view=true#setpermissionstate) in [with_webview](https://docs.rs/tauri/2.0.0-beta.7/tauri/webview/struct.WebviewWindow.html#method.with_webview) (via the [bindings](https://docs.rs/webview2-com/latest/webview2_com/Microsoft/Web/WebView2/Win32/struct.ICoreWebView2Profile4.html#method.SetPermissionState)). If all this is new to you, it would look something like [this](https://github.com/tauri-apps/tauri/discussions/4912#discussioncomment-8358167), just to get a feel for it.

**Comment by WeiChens** [comment]
I also have OCD, it took me several days to find it

tauri version v2
 dependencies：
 webview2-com = "0.31.0"
 windows = "0.57.0"
```rust
use webview2_com::Microsoft::Web::WebView2::Win32::{
    ICoreWebView2Profile4, ICoreWebView2_13, COREWEBVIEW2_PERMISSION_KIND_MICROPHONE,
    COREWEBVIEW2_PERMISSION_STATE_DEFAULT,
};
use windows::core::{Interface, PCWSTR};

/**
 *
 * Reset microphone permissions
 */
#[tauri::command]
fn reset_permission(origin: &str, app: AppHandle) {
    let webview = app.get_webview_window("main").unwrap();
    let mut origin = origin.to_string();
    origin.push('\0');
    let origin = origin.encode_utf16().collect::<Vec<u16>>();
    webview
        .with_webview(move |webview| unsafe {
            let core = webview.controller().CoreWebView2().unwrap();
            let core = Interface::cast::<ICoreWebView2_13>(&core).unwrap();
            let profile = core.Profile().unwrap();
            let profile = Interface::cast::<ICoreWebView2Profile4>(&profile).unwrap();
            let origin = PCWSTR::from_raw(origin.as_ptr());
            profile
                .SetPermissionState(
                    COREWEBVIEW2_PERMISSION_KIND_MICROPHONE,
                    origin,
                    COREWEBVIEW2_PERMISSION_STATE_DEFAULT,
                    None,
                )
                .unwrap();
        })
        .unwrap();
}
```

**Comment by rasteiner** [comment]
@WeiChens Thank you very much 😊

In my case I used `COREWEBVIEW2_PERMISSION_STATE_ALLOW`. 

For completeness sake:
```ts
await invoke('reset_permission', { origin: window.origin });
const devices = await navigator.mediaDevices.enumerateDevices();
console.log('Weeeee', devices);
```

**Comment by kamalkech** [comment]
@WeiChens cannot find type `AppHandle` in this scope not found in this scope

**Comment by FabianLars** [comment]
Import it then, your code editor should hopefully do it for you.
If not, simply add `use tauri::AppHandle;`

**Comment by kamalkech** [comment]
@FabianLars thank u for response, i already fix this yesterday using Info.plist params without code rust

**Comment by sagarpadia17** [comment]
> [@FabianLars](https://github.com/FabianLars) thank u for response, i already fix this yesterday using Info.plist params without code rust

Can you tell how you have done this using Info.plist?

**Comment by FabianLars** [comment]
@sagarpadia17 https://github.com/tauri-apps/tauri/blob/dev/examples/api/src-tauri/Info.plist (info.plist is for macos btw)

**Comment by sagarpadia17** [comment]
> @sagarpadia17 https://github.com/tauri-apps/tauri/blob/dev/examples/api/src-tauri/Info.plist (info.plist is for macos btw)

Okay but I am not getting where I should put the above code to make it work

**Comment by sagarpadia17** [comment]
> > @sagarpadia17 https://github.com/tauri-apps/tauri/blob/dev/examples/api/src-tauri/Info.plist (info.plist is for macos btw)
> 
> Okay but I am not getting where I should put the above code to make it work

Not the info.plist but what Weichens posted

**Comment by FabianLars** [comment]
Weichens code is just a normal command https://v2.tauri.app/develop/calling-rust/#commands (the code they showed is windows only btw), so it probably belongs in your src-tauri/src/lib.rs file.

**Comment by maksiksq** [comment]
Also, if you're deleting the `C:\Users\<user-name>\AppData\Local\<your-app-bundle-identifieer>\EBWebView` folder you have to restart your pc.

**Comment by chnkarl** [comment]
users can delete C:\Users\<user-name>\AppData\Local\<your-app-bundle-identifieer>\EBWebView directory and it will reset the permissions state, so you can prompt them for it again.

This works for me. I'm windows11 OS.
