### ISSUE TITLE
[bug] wrong language code in allowlist for msi bundle

### ISSUE THREAD

**Issue by dolsup** [tauri-apps/tauri#4437]
### Describe the bug

Legitimate BCP 47 Code for Korean is `ko-KR`.
but `ko-KO` is specified in the file which is used as allowlist.
https://github.com/tauri-apps/tauri/blob/6650e5d6720c215530ca1fdccd19bd2948dd6ca3/tooling/bundler/src/bundle/windows/msi/languages.json#L70

So, bundling Windows msi fails when `tauri.bundle.windows.wix.language` in `tauri.conf.json` is `ko-KR`.
```
thread '<unnamed>' panicked at 'Language ko-KR not found. It must be one of et-EE, he-IL, hr-HR, tr-TR, de-DE, pl-PL, sr-Latn-CS, it-IT, eu-ES, da-DK, hu-HU, jp-JP, fi-FI, en-US, es-ES, ca-ES, sk-SK, ro-RO, zh-TW, lt-LT, ru-RU, sv-SE, th-TH, ar-SA, uk-UA, nb-NO, zh-CN, bg-BG, nl-NL, ko-KO, el-GR, sl-SI, vi-VN, lv-LV, cs-CZ, pt-PT, fr-FR, pt-BR', D:\a\tauri\tauri\tooling\bundler\src\bundle\windows\msi\wix.rs:636:7
```

### Expected behavior

`ko-KR` should be valid language code for the config

### Platform and versions

```shell
GitHub Actions
```

**Comment by dolsup** [comment]
I want to fix it and make a PR and It will be a breaking change. But I have no idea that it is okay or not.

**Comment by amrbashir** [comment]
thank you, and since it never worked in the first place, it is a bugfix and not a breaking change, so I'd love to see a PR
