### ISSUE TITLE
[bug] When running cargo tauri dev, The App started, Try to change file content in the source code folder, such as  log/errors.log, it quit and rebuild again and again forever

### ISSUE THREAD

**Issue by WilliamPang112** [tauri-apps/tauri#4448]
### Describe the bug

[bug] When running cargo tauri dev, The App started, Try to change file content in the source code folder, such as  log/errors.log, it quit and rebuild again and again forever

### Reproduction

1. run cargo tauri dev
2. in the program, change file content at the source code folder, such as  log/errors.log
3. the program quit
4. it restarted forever

### Expected behavior

should have set types of ignore files or folder

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 102.0.1245.44
  › MSVC:
      - Visual Studio 15 2017
      - Visual Studio Community 2019
  › Node.js: 14.17.0
  › npm: 8.9.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc
```

**Comment by lucasfernog** [comment]
We watch the source code folder for changes for a HMR-like experience. You can git ignore the log files so it gets skipped by our watcher. In the next release you'll also be able to specify a custom file to apply ignore rules in case you don't want to gitignore your log file, see #4406.

**Comment by WilliamPang112** [comment]
Thanks, I worked!

**Comment by lucasfernog** [comment]
Btw you should avoid writing files to CWD, it won't work in production. You can get some known paths using our [path](https://tauri.app/v1/api/js/modules/path) module. Check out appDir and logDir :)

**Comment by WilliamPang112** [comment]
Thanks, I will try the appDir.
