### ISSUE TITLE
[feat] Add NSIS support

### ISSUE THREAD

**Issue by sFireFrog** [tauri-apps/tauri#4450]
### Describe the problem

Wix toolset, a bit difficult to use, ugly interface, maybe I'm not using it properly. 

### Describe the solution you'd like

Can you provide more packaged installation tools? such as NSIS,Squirrel.Windows

**Comment by lucasfernog** [comment]
NSIS will be investigated in the future. Currently you'll have to get along with Wix :) at least you don't have to write the XML directly :D

**Comment by seahindeniz** [comment]
I'm assuming this will affect this documentation as well
https://tauri.app/v1/guides/building/windows/#replacing-the-installer-code-with-a-custom-wix-file

---

@amrbashir I'm not familiar with NSIS nor how the implementation and configuration will be. Do you think it would be possible to add options to the installer to install the app for current user only or all users option?
Some apps may need to restrict the installation for current user only on Windows too (I personally interested in this)

Something like this, perhaps
![image](https://user-images.githubusercontent.com/5789670/206906202-3ecae0af-bf8e-4100-bb82-ac8b7947ad28.png)

However, I'm not sure about the installation path for the current user. I'm assuming if it's possible, it'll install the app on `AppData` directory, where we can also use `AppData/Roaming` for sharing resources. Installing the app on the same directory or `AppData/Local` could also work I guess.

Found this links 
https://nsis.sourceforge.io/Docs/MultiUser/Readme.html
http://nsis-dev.github.io/NSIS-Forums/html/t-254878.html

**Comment by amrbashir** [comment]
@seahindeniz In the linked PR, I have implemented an option in tauri.conf.json that determines whether your installer will be built to be installed system-wide or for current userbut not both at the same time
