### ISSUE TITLE
[bug] Building/bundling doesn't seem to work in Rust workspace/monorepo

### ISSUE THREAD

**Issue by schickling** [tauri-apps/tauri#4453]
### Describe the bug

When trying to run `yarn tauri dev` in a sub package of a Rust workspace/monorepo I'm getting the following error:

![CleanShot 2022-06-23 at 20 11 07](https://user-images.githubusercontent.com/1567498/175454675-63765357-67b1-467f-85b1-ea7f2f6c3f6d.png)

### Reproduction

The project structure roughly looks like this

```
apps/desktop/
  Cargo.toml
  src-tauri/...
rust-libs/
  some-lib/
    Cargo.toml
Cargo.toml # root Cargo file
```

Go to `apps/desktop` and run `yarn tauri dev`

### Platform and versions

```shell
Environment
  › OS: Mac OS 12.3.1 X64
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: 3.2.0
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.0.0-rc.16 (outdated, latest: 1.0.0)
  › @tauri-apps/api [NPM]: 1.0.0-rc.3 (outdated, latest: 1.0.1)
  › tauri [RUST]: 1.0.0-rc.16 (no lockfile),
  › tauri-build [RUST]: no manifest (no lockfile),
  › tao [RUST]: no manifest (no lockfile),
  › wry [RUST]: no manifest (no lockfile),

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  › distDir: ../dist
  › devPath: http://localhost:8080/
  › framework: React

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ .storybook
  ├─ public
  ├─ scripts
  ├─ src-tauri
  └─ src
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by lucasfernog** [comment]
@schickling I couldn't reproduce this, can you share a repo with a minimal folder structure with this issue?

**Comment by schickling** [comment]
I've looked into it a bit more. It turned out to not be a problem with the Rust workspace/monorepo setup but rather another problem (it seems that the VSC Rust plugin seems to interfere with the `yarn tauri build` command).
