### ISSUE TITLE
[bug] Right mouse button menu

### ISSUE THREAD

**Issue by Zhiqiang-Wu** [tauri-apps/tauri#4454]
### Describe the bug

Should the right mouse button menu be disabled?

![QQ截图20220624130946](https://user-images.githubusercontent.com/56793420/175466776-fc45efd0-f793-48b8-8e69-80c8290ad54a.png)

### Platform and versions

```shell
win 64
tauri 1.0.0
```

**Comment by mantou132** [comment]
dup: https://github.com/tauri-apps/tauri/issues/4338

You can use the `contextmenu` [event](https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event) disable default context menu
