### ISSUE TITLE
[bug][macos] Can't persist in storage data to `localStorage`

### ISSUE THREAD

**Issue by mantou132** [tauri-apps/tauri#4455]
### Describe the bug

When the APP is closed, the localStorage does not work:

```js
  document.body.firstElementChild.innerHTML = `localStorage.data: ${localStorage.data}`;
  window.__TAURI__?.window.getCurrent().listen('tauri://close-requested', () => {
    localStorage.data = 1;
    window.__TAURI__?.window.getCurrent().close();
  });
```

### Reproduction

https://github.com/mantou132/tauri-app-test

### Expected behavior

The content of the page is `localstorage.data: 1`

### Platform and versions

```shell
Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 18.3.0
  › npm: 8.11.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.63.0-nightly
  › cargo: 1.63.0-nightly
  › Rust toolchain: nightly-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: ../dist

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ src-tauri
  └─ .git
```

### Additional context

Working normally when the delay is closed

```js
    setTimeout(() => {
      window.__TAURI__?.window.getCurrent().close();
    }, 1000)
```

**Comment by dsseng** [comment]
From the code you provided it looks like you are writing to the object, not the storage. To access local storage and persist data you should use `localStorage.setItem('key', 'value')` and `localStorage.getItem('key')` methods.

**Comment by mantou132** [comment]
https://html.spec.whatwg.org/multipage/webstorage.html#the-storage-interface

property assign is equivalent to the `setItem`,  and I have said that if there is a delay, there will be no problems.

**Comment by lucasfernog** [comment]
The webview probably needs a little time to persist the storage - maybe we need to manually trigger it on window close.

**Comment by lucasfernog** [comment]
@wusyong any ideas on which API we need to call?

**Comment by mantou132** [comment]
Didn't find apple related documentation, I'm using [filesystem](https://github.com/mantou132/nesbox/blob/master/packages/tauriapp/src/preload.rs#L38-L58) right now to clear the differences between platforms, if anyone has a better way please let me know.
