### ISSUE TITLE
[bug] Failed to execute the binary program after packaging 

### ISSUE THREAD

**Issue by xiaoxin-sky** [tauri-apps/tauri#4456]
### Describe the bug

When I use `pnpm tauri build`, I can use this command normally. But once packaged and started from the application, the `Command::new ("sslocal")` command cannot be used. Then I run binary directly in `/ Users/skymac/workplace/preemptive_app/src-tauri/target/release/bundle/macos/preempt ive_app.app/Contents/MacOS/preemptive_app`, which can also be used normally. I suspect that the parameter path in `Command::new ()` is inconsistent?

### Reproduction

1. pnpm tauri build 
2. start-up  /Users/skymac/workplace/preemptive_app/src-tauri/target/release/bundle/macos/preemptive_app.app 
![image](https://user-images.githubusercontent.com/42181585/175474297-bc621efd-d802-490c-abc0-6cf18ccd0f2b.png)
3. Command::new("sslocal") It didn't work.
![image](https://user-images.githubusercontent.com/42181585/175474890-f2d067b4-9b7e-4f8b-b00c-c4284d43cd66.png)
4. start-up /Users/skymac/workplace/preemptive_app/src-tauri/target/release/bundle/macos/preemptive_app.app/**Contents/MacOS/preemptive_app** 
5. Command::new("sslocal") It can work properly.
![image](https://user-images.githubusercontent.com/42181585/175474761-62e17dee-2c5f-4a89-90ba-9ca91294961f.png)

### Expected behavior

start up `/Users/skymac/workplace/preemptive_app/src-tauri/target/release/bundle/macos/preempt ive_app.app/Contents/MacOS/preemptive_app` can also start Command::new("sslocal") well

### Platform and versions

```shell
Environment
  › OS: Mac OS 11.5.2 X64
  › Node.js: 14.19.2
  › npm: 6.14.17
  › pnpm: 7.1.0
  › yarn: 1.22.5
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:33331/
  › framework: Vue.js

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  └─ src
```

**Comment by xiaoxin-sky** [comment]
![image](https://user-images.githubusercontent.com/42181585/175475661-6e51a1f1-d9d5-4e61-a12d-1e0edc2d61fb.png)
I use this command to start the binary.

**Comment by FabianLars** [comment]
if it's a bundled _sidecar_ you need to use the sidecar api instead of a normal command: https://docs.rs/tauri/latest/tauri/api/process/struct.Command.html#method.new_sidecar

```rs
let (mut rx, child) = Command::new_sidecar("sslocal") ...
```
