### ISSUE TITLE
[feat] Proposal on web style

### ISSUE THREAD

**Issue by gtoxlili** [tauri-apps/tauri#4460]
### Describe the problem

In the process of using it, I found many css default settings that are different from Chromium.

For example, the `:focus` property `outline` is not defaulted to none in tauri, which causes some controls like buttons to appear as a dotted line when clicked.

This made it difficult for me to migrate my software from electron to tari (after all, I don't know the difference between the web kernel used by tari and Chromium in terms of css defaults)

### Describe the solution you'd like

This will be fixed in subsequent releases

**Comment by amrbashir** [comment]
This is normal web dev issue that is not specific to tauri. You can use a css reset like Eric Myer's reset or normalize.css and use tools like auto-prefixer.
