### ISSUE TITLE
[bug] Cannot find the `favicon.ico` assets.

### ISSUE THREAD

**Issue by Jerrody** [tauri-apps/tauri#4463]
### Describe the bug

I get this error when I launch an app.

```
Asset `favicon.ico` not found; fallback to favicon.ico.html
Asset `favicon.ico` not found; fallback to favicon.ico/index.html
Asset `favicon.ico` not found; fallback to index.html
```
Everything works fine, but I don't understand the reason.

### Reproduction

1) `cargo tauri init`
2) At this step I created an `index` folder where I placed an HTML template code into the `index.html`.
3) `cargo tauri 

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.19043 X64
  › Webview2: 102.0.1245.44
  › MSVC: 
      - Visual Studio Community 2022
  › Node.js: 16.5.0
  › npm: 7.19.1
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.24.3
  › rustc: 1.63.0-nightly
  › cargo: 1.63.0-nightly
  › Rust toolchain: nightly-x86_64-pc-windows-msvc
```

### Additional context

rustc metadata:
```
rustc 1.63.0-nightly (ec55c6130 2022-06-10)
binary: rustc
commit-hash: ec55c61305eaf385fc1b93ac9a78284b4d887fe5
commit-date: 2022-06-10
host: x86_64-pc-windows-msvc
release: 1.63.0-nightly
LLVM version: 14.0.5
```

**Comment by amrbashir** [comment]
you jave 3 options:
- add a `favicon.ico` in your front-end public files
- just remove it from `index.html`, but on some platforms, it might not be enough and you'd have to go back two option 1
- ignore the error, it is harmless

**Comment by Jerrody** [comment]
> you jave 3 options:
> 
> * add a `favicon.ico` in your front-end public files
> * just remove it from `index.html`, but on some platforms, it might not be enough and you'd have to go back two option 1
> * ignore the error, it is harmless

Thanks!
