### ISSUE TITLE
[feat] WindowBuilder.with_default_config()?

### ISSUE THREAD

**Issue by itekhi** [tauri-apps/tauri#4464]
I'm trying to create a window in rust with the same configuration as in `tauri.conf.json`, but can't find anything how can I use values from it for `WindowBuilder`, am I missing something? I know that I can just create a `WindowConfig` and use it with `.with_config()`, but I think it would be nice to have everything in one place...

**Comment by amrbashir** [comment]
you should just create all your windows from rust if you want to reuse the properties.
