### ISSUE TITLE
[feat] File path in Tauri Updater Signature Format 

### ISSUE THREAD

**Issue by LoonyRules** [tauri-apps/tauri#4467]
### Describe the problem

The Tauri Updater `.msi.zip.sig` file format contains the file path of the release build's `.msi.zip` on disk when being built.

```
untrusted comment: signature from tauri secret key
<some base64 that isn't easily decoded>
trusted comment: timestamp:1656152579	file:{{PATH_TO_PROJECT_AND_TARGET_RELEASE_BUNDLE_MSI_FILE}}_x64_en-US.msi.zip
+<another base64 that isn't easily decoded>
```

My question is: why? I do not want the path to my tauri project to be part of the signature at all, even if we did compile releases via CI/CD, of which is the ultimate goal.

Another question that is related to the format, why the `untrusted comment: signature from tauri secret key`?

### Describe the solution you'd like

Remove the `file` path data if it's not directly required. If it is, figure out why and a replacement.

### Additional context

Initial conversation was made over on the [Tauri Discord](https://discord.com/channels/616186924390023171/731495028677148753/990198747709460571). This was then moved from [Discord to GitHub](https://discord.com/channels/616186924390023171/731495028677148753/990203537894043658) to get more important from a Core Member.

**Comment by lucasfernog** [comment]
The .sig contents should be the base64 encoded signature (I just double checked it). Can you share the `tauri info` output?

**Comment by LoonyRules** [comment]
> The .sig contents should be the base64 encoded signature (I just double checked it). Can you share the `tauri info` output?

Yes the .sig is base64 the data in my initial post is the base64 decoded contents.

**Comment by FabianLars** [comment]
Btw here's where it comes from: https://github.com/tauri-apps/tauri/blob/17f17a80f818bcc20c387583a6ff00a8e07ec533/tooling/cli/src/helpers/updater_signature.rs#L128

**Comment by lucasfernog** [comment]
I'll check with the author but I think we can remove that.

**Comment by LoonyRules** [comment]
It feels like it's more for randomness but if that's the case a unique app id could just be generated instead and used.

**Comment by FabianLars** [comment]
i mean, having the file name itself is probably a good idea (edit: This is really common btw) and could be used to "confirm" the file is correct or whatever, but the whole path of the build system is a bit much 😅

**Comment by lucasfernog** [comment]
I'll submit a PR with the change. Thanks for finding this, I never realized it :D
