### ISSUE TITLE
[bug]  Uncaught (in promise) invalid type: map, expected a sequence

### ISSUE THREAD

**Issue by ggssh** [tauri-apps/tauri#4468]
### Describe the bug

When I run this exemple code.
~~~javascript
import { open } from '@tauri-apps/api/dialog';
const selected = await open({
  multiple: true,
  filters: {
    name: 'Image',
    extensions: ['png', 'jpeg']
  }
});
if (Array.isArray(selected)) {
  // user selected multiple files
} else if (selected === null) {
  // user cancelled the selection
} else {
  // user selected a single file
}
~~~
I got this error:
~~~shell
Uncaught (in promise) invalid type: map, expected a sequence
Promise.catch(异步)
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:166
invoker @ runtime-dom.esm-bundler.js:369
~~~

### Platform and versions

```shell
Windows11 22000.739
```

**Comment by FabianLars** [comment]
filters, needs to be an array, see https://github.com/tauri-apps/tauri-docs/pull/705.
I didn't merge this PR, because the js api docs are generated from this repo on each release.

**Comment by ggssh** [comment]
> filters, needs to be an array, see [tauri-apps/tauri-docs#705](https://github.com/tauri-apps/tauri-docs/pull/705). I didn't merge this PR, because the js api docs are generated from this repo on each release.

thank u😊
