### ISSUE TITLE
[bug] Some Linux gives `Failed to load resources: Unacceptable TLS certificate`

### ISSUE THREAD

**Issue by kfiven** [tauri-apps/tauri#4472]
### Describe the bug

Running appimage on Gentoo and Solus Linux gives `Failed to load resources: Unacceptable TLS certificate` and the user tried reinstalling the ca-certificates but it just doesn't work. Btw my app makes http calls and that what failing because of this.

### Platform and versions

```shell
Environment
  › OS: Ubuntu 20.04.4 LTS
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.13
  › @tauri-apps/api [NPM]: 1.0.0-rc.6
  › tauri [RUST]: 1.0.0-rc.14
  › tauri-build [RUST]: 1.0.0-rc.12
  › tao [RUST]: 0.9.1
  › wry [RUST]: 0.17.0

App
  › build-type: bundle
  › CSP: script-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  › distDir: ../cinny/dist
  › devPath: http://localhost:8080/

App directory structure
  ├─ .git
  ├─ .github
  ├─ cinny
  ├─ node_modules
  ├─ resources
  ├─ scripts
  └─ src-tauri
```

**Comment by FabianLars** [comment]
I don't have much time right now, so i'm just gonna copy-paste my [discord messages](https://discord.com/channels/616186924390023171/990248372420104192/990251670929821786) for now (for extra context):
> i invested sooo many hours into trying to fix it, but something is up with the ssl libs and they don't pick up any settings that are supposed to help here 
> (at least if the app is built on (older) ubuntu versions)
> so the only real fix as of now is to create a redirect from /etc/ssl/certs/ca-certificates.crt to wherever the distro stores it
> fun fact that's exactly what fedora did with the release of fedora36

So unless i missed something super stupid (which i don't expect at this point, i really tried sooo much) i don't think we can fix this. Luckily our lord and savior flatpak is on its way 👀 
P.S. this may only be a problem with the libs on ubuntu or ubuntu1804 in particular, maybe something's up with the libs or they were build in a weird way idk.

**Comment by kfiven** [comment]
FTR [build logs](https://github.com/cinnyapp/cinny-desktop/runs/6641484826?check_suite_focus=true). ([If the action logs expires](https://pastebin.com/R6FdRRBt))

**Comment by kfiven** [comment]
Update: updating `app-misc/ca-certificates` made it work on Gentoo Linux.

**Comment by kfiven** [comment]
@lucasfernog Hi, which Tauri version included this fix?

**Comment by agfp** [comment]
Error persists on OpenSuse Tumbleweed, brand new install.

**Comment by shamblesides** [comment]
For anyone googling this, I had this issue because I was pointing Tauri at an HTTPS server whose certificate chain was incomplete. After I fixed that by including the ca-bundle in my server's .crt file, everything worked.

**Comment by tomasarad** [comment]
Hi! UnlimCloud Desktop app (appimage) built using Tauri, give 'Unacceptable TLS certificate' on opensuse tumbleweed - can I do something?

**Comment by dwosk** [comment]
I guess this is the same as what @FabianLars said already, but in my case I got this error when running the AppImage on RHEL 9. I build the app on Debian 10 and noticed my frontend HTTPS calls would fail.

On the RHEL 9 machine, I ran:
```
$ ln -s /etc/pki/tls/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt
```

which fixed the issue.

**Comment by elbaih101** [comment]
com.vysp3r.ProtonPlus:2): GLib-Net-WARNING **: 23:54:07.482: Failed to load TLS database: System trust contains zero trusted certificates; please investigate your GnuTLS configuration
** Message: 23:54:07.546: web.vala:18: Unacceptable TLS certificate



i have a similar issue but iam a noob in linux can some one help me
