### ISSUE TITLE
[bug] configDir and dataDir resolves both to C:\Users\username\AppData\Roaming\ (windows 11)

### ISSUE THREAD

**Issue by lorenzocorallo** [tauri-apps/tauri#4473]
### Describe the bug

`configDir` and `dataDir` from `@tauri-apps/api/path` package resolves both to `C:\Users\username\AppData\Roaming\`.
This reflects also on `appDir` which refers to  `C:\Users\username\AppData\Roaming\${bundleIdentifier}`,
Tested with `yarn create tauri-app` with `create-vite-app` (react-ts) and `create-react-app` templates.

### Reproduction

1. create tauri app with `yarn create tauri-app` with `create-react-app` template
2. in App.js create a function test to check the two paths and execute it:
```
  const test = async () => {
    const config = await configDir();
    const data = await dataDir();
    console.log(config, data);
  };

  test();
```
3. check the console in devtools: the two paths are the same

### Expected behavior

`configDir` should refers to `C:\Users\username\AppData\Local` as described in the [doc](https://tauri.app/v1/api/js/modules/path#configdir):

> Windows: Resolves to {FOLDERID_LocalAppData}.

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 102.0.1245.44
  › MSVC: 
      - Visual Studio Build Tools 2022
      - Visual Studio Build Tools 2019
  › Node.js: 16.15.1
  › npm: 8.13.1
  › pnpm: 6.11.0
  › yarn: 3.2.1
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ .git
  ├─ .yarn
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

### Additional context

I don't know why `tauri info` says I'm on Windows 10 while I am on Windows 11

**Comment by FabianLars** [comment]
Roaming is the correct folder. But yes, the docs are incorrect (most likely a copy-paste mistake)

**Comment by lorenzocorallo** [comment]
If it's a documentation mistake, why are there two variables with the same value? Isn't it useless?

**Comment by FabianLars** [comment]
Because these functions are cross-platform and Windows doesn't have specific folders, unlike Linux: <https://github.com/xdg-rs/dirs/tree/master/dirs#features>

**Comment by lorenzocorallo** [comment]
Got it. Probably a PR is needed for the docs mistake, but the problem itself doesn't exist anymore. Thank you. I'm going to close this issue.
