### ISSUE TITLE
When I use `tauri::Windows::WindowBuilder` create a new window to the URL is not the current devPath (eg: http://localhost:3000), but another project (eg: http://localhost:3333), the other items `window.__TAURI__` is undefined if you want to use the tauri API.

### ISSUE THREAD

**Issue by Soya-xy** [tauri-apps/tauri#4479]
When I use `tauri::Windows::WindowBuilder` create a new window to the URL is not the current devPath (eg: http://localhost:3000), but another project (eg: http://localhost:3333), the other items `window.__TAURI__` is undefined if you want to use the tauri API.

Is this currently supported?

All projects run in the same Tauri app, but there are 2 different project addresses

_Originally posted by @Soya-xy in https://github.com/tauri-apps/tauri/issues/4414#issuecomment-1166744121_

**Comment by lucasfernog** [comment]
You'll need to merge both somehow. For instance you can use Webpack dev proxy in development mode, and move all assets to the same folder for production. We don't support multiple dev URLs currently.
