### ISSUE TITLE
Blank Screen when running examples/svelte

### ISSUE THREAD

**Issue by mosheduminer** [tauri-apps/tauri#448]
**Describe the bug**
I cloned the svelte app from the examples repo, installed dependencies (removed the relative path in Cargo.toml), and ran the tauri:prod:build script. Running the resulting binary only showed a white window, the app did not appear to be running.

**To Reproduce**

**Expected behavior**
I expected the svelte app to show.

**Platform and Versions (please complete the following information):**

Operating System - Windows_NT(10.0.18363) - win32/x64

Node.js environment
  Node.js - 13.7.0
  tauri.js - 0.4.3

Rust environment
  rustc - 1.41.0
  cargo - 1.41.0
  tauri-bundler - 0.4.0

Global packages
  NPM - 6.13.6
  yarn - 1.22.0

**Comment by Reidond** [comment]
Did you enabled loopback interface?
Like this:
`CheckNetIsolation.exe LoopbackExempt -a -n="Microsoft.Win32WebViewHost_cw5n1h2txyewy"`

**Comment by mosheduminer** [comment]
Yes. Just to make sure I just ran that command again (as administrator, in powershell), there is no change.

**Comment by tensor-programming** [comment]
Are you using the edge feature flag or IE?  Ill take a look at it tomorrow.

**Comment by mosheduminer** [comment]
@tensor-programming I had this issue with edge, as I left tauri.config.json as it was when I cloned it. However, I just tried building with the edge flag set to false, and I got the following error:
![Screenshot (17)](https://user-images.githubusercontent.com/47164590/75444836-30315e00-5932-11ea-8210-a555409d85a7.png)
 I clicked yes, however the screen remained blank nevertheless.

**Comment by lucasfernog** [comment]
We had some ES6 syntax on our codebase, and also Svelte was crashing IE because it has a function with a default parameter specified, so I had to change the example to transpile it using Babel. This will be ready on the next deploy, and you can check it out right now by building from source.
