### ISSUE TITLE
[bug] How can I  kill the one in state  child created by Command::new_sidecar()?

### ISSUE THREAD

**Issue by xiaoxin-sky** [tauri-apps/tauri#4481]
### Describe the bug

![image](https://user-images.githubusercontent.com/42181585/175872042-30c4bd6d-be1f-45f6-8203-0f9b697b7c1b.png)
![image](https://user-images.githubusercontent.com/42181585/175872124-4e388a6e-0b16-45e3-a3b2-6d9f8fe1cfcb.png)

I can't use child's kill method in state, but I can use child's pid method. Is there a better way to write it? Now I can only use `tauri::api::process::kill_children();` to kill all child processes.

### Platform and versions

```shell
Environment
  › OS: Mac OS 11.5.2 X64
  › Node.js: 14.19.2
  › npm: 6.14.17
  › pnpm: 7.1.0
  › yarn: 1.22.5
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: default-src 'self'
  › distDir: ../dist
  › devPath: http://localhost:33331/
  › framework: Vue.js
App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  └─ src
```

### Stack trace

```shell
error[E0507]: cannot move out of a shared reference
   --> src/main.rs:52:5
    |
52  |     state.0.lock().unwrap().as_ref().unwrap().kill();
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^------
    |     |                                         |
    |     |                                         value moved due to this method call
    |     move occurs because value has type `CommandChild`, which does not implement the `Copy` trait
    |
note: this function takes ownership of the receiver `self`, which moves value
   --> /Users/skymac/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/tauri-1.0.0/src/api/process/command.rs:115:15
    |
115 |   pub fn kill(self) -> crate::api::Result<()> {
    |               ^^^^

For more information about this error, try `rustc --explain E0507`.
warning: `preemptive_app` (bin "preemptive_app") generated 21 warnings
error: could not compile `preemptive_app` due to previous error; 21 warnings emitted
```

**Comment by FabianLars** [comment]
Since `kill` takes ownership, you need to move the child out of the Mutex/Option, you're probably looking for https://doc.rust-lang.org/std/option/enum.Option.html#method.take instead of as_ref.
Keep in mind that after this function the Child in the state is replaced with `None`.

**Comment by xiaoxin-sky** [comment]
> Since `kill` takes ownership, you need to move the child out of the Mutex/Option, you're probably looking for https://doc.rust-lang.org/std/option/enum.Option.html#method.take instead of as_ref. Keep in mind that after this function the Child in the state is replaced with `None`.

Thank you vary much! This is very useful for me.
