### ISSUE TITLE
Allow unnamed / unexpected arguments - letting files to be opened with app

### ISSUE THREAD

**Issue by ANFADEV** [tauri-apps/tauri#4488]
Following Tauri's guide [here ](https://tauri.app/v1/api/config#cliconfig) arguments have to be named, this doesn't allow to open a file directly with a tauri application

Example:

I want to open myfile.txt directly with tauri, or after binding its filetype to open with my tauri app by default:
![screen open with tauri](https://user-images.githubusercontent.com/32341740/175985290-13359307-8e11-45e6-b6cf-e1085cd5bb09.jpg)

this produces an error after trying to get the args list with:
`getMatches().then(val => console.log('getMatches: ' + JSON.stringify(val)));`

![screen open with tauri2](https://user-images.githubusercontent.com/32341740/175985338-a9b00984-0fcb-4f96-8322-5ecd5780d81a.jpg)

I have to resort to using the "file" argument like this:

opening the file with my tauri app by running `app.exe -f myfile.txt` in the terminal produces:
![screen open with tauri3](https://user-images.githubusercontent.com/32341740/175985400-cc726f11-96bd-4713-896c-21a5c96baf8a.jpg)

but that means ⚠**losing**⚠ the ability to directly open a file with tauri's app, and by consequence i can't set the app as as default app for certain filetypes in the system settings

### Describe the solution you'd like

Allow unexpected args when the user puts an arg definition with name "" in the tauri config
Like this
```json
"tauri":{
  "cli":{
      "args":[
        {
          "name":"",
          "description": "the file to open with this program",
          "takesValue": false
        },
      ],
    },
}
```
The takesValue param should take false by default, as the argument can be anything (unexpected)

### Alternatives considered

As a minimum, let getMatches() still return the object with what it could parse from cli arguments, ignoring unexpected args
in the current state having an unexpected arg doesn't let you work with any other arg

### Additional context

my tauri config:
```json
"tauri":{
  "cli":{
      "description": "cli commands",
      "args":[
        {
          "name":"",
          "description": "the file to open with this program",
          "takesValue": false
        },
        {
          "name":"file",
          "short": "f",
          "description": "the file to open with this program",
          "takesValue": true
        }
      ],
      "subcommands": null
    },
}
```

**Comment by FabianLars** [comment]
Did you see this: https://tauri.app/v1/guides/features/cli#positional-arguments ?
Basically adding index: 1 should fix it.

**Comment by ANFADEV** [comment]
I confirm that putting index:1 works, thanks a lot
