### ISSUE TITLE
Consistent access to $PATH in tauri sidecars

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#449]
**Describe the bug**
There are a number of reports about the node binary not being found, and I expect other binaries might have the same problem. This seems to be a problem on Mac, Lin and probably Win.

This is a tracking issue, please feel free to link to your repo issue.

**Comment by nothingismagick** [comment]
https://github.com/Akryum/guijs/issues/19

**Comment by nothingismagick** [comment]
I am going to revise our bootloaders.

**Comment by lucasfernog** [comment]
We need to revisit this. Maybe tell users to go with `sh -c "script"`.

**Comment by lucasfernog** [comment]
We have a new crate for this: https://github.com/tauri-apps/fix-path-env-rs
