### ISSUE TITLE
[feat] round corners support plugin

### ISSUE THREAD

**Issue by Luciennnnnnn** [tauri-apps/tauri#4497]
### Describe the problem

request a round corner plugin to simulate the natural behavior of app on macOS.

### Describe the solution you'd like

a plugin like https://github.com/tauri-apps/window-shadows

**Comment by JonasKruckenberg** [comment]
Couple questions:
1. What would your usecase for this be exactly? 
2. Why not use css to round the corners of undecorated windows?

My guess is you're trying to hide the ugly default titlebar on macOS, but if that's the case you need to think about this problem differently. On macOS you shouldn't use `decoration: false` but rather make the titlebar transparent. Support for this (if you're not comfortable with implementing it yourself) is coming with this pr: https://github.com/tauri-apps/tauri/pull/3965

**Comment by Luciennnnnnn** [comment]
yeah. I want to customize titlebar to get a consistent visual experiment between Windows and macOS.

I have forgotten the details of why I need a plug-in, I have a discussion on #app-devs channel of discord with @FabianLars (and this channel now is closed, I can't search our past discussion) . The conclusion is that we need native round-corner support other than implementing it by CSS.
The reason may be that we need to set [tauri.macOSPrivateApi] to true to enable transparent window on macOS, and this prevent app be accepted by apple as I remembered. see https://github.com/tauri-apps/tauri/issues/3481

**Comment by FabianLars** [comment]
@JonasKruckenberg This is the convo: https://discord.com/channels/616186924390023171/622768087183130673/974651874441572363
Btw we need to make the archive public again (read-only ofc), there is much lost info rn.

And yes, you're essentially looking for #3965 like Jonas said (note that the transparency he mentions is not the private api stuff)

**Comment by Luciennnnnnn** [comment]
> @JonasKruckenberg This is the convo: https://discord.com/channels/616186924390023171/622768087183130673/974651874441572363 Btw we need to make the archive public again (read-only ofc), there is much lost info rn.
> 
> And yes, you're essentially looking for #3965 like Jonas said (note that the transparency he mentions is not the private api stuff)

Do you mean that we no longer need a rounded plug-in with #3965 ?

**Comment by FabianLars** [comment]
Yes, same for the shadows plugin (_on macOS_)

**Comment by Luciennnnnnn** [comment]
> Yes, same for the shadows plugin (_on macOS_)

That's great. I'm looking forward to using this feature.

**Comment by JonasKruckenberg** [comment]
I will close this issue then 👍
