### ISSUE TITLE
[bug] I copied your splashscreen example code, but can't colse splashscreen window

### ISSUE THREAD

**Issue by Virgil-N** [tauri-apps/tauri#4499]
### Describe the bug

I copied your splashscreen example code, but can't colse splashscreen window. And new window show 'no response'.
I only changed url to '/xx/splashscreen.html'.
How to solve it?

### Platform and versions

```shell
window 10
rust v1.57
tauri v1.0.0
```

**Comment by lucasfernog** [comment]
Can you share your project? I can't help you without more information, you probably missed something. There's also a guide in the [docs](https://tauri.app/v1/guides/features/splashscreen).

**Comment by nothingismagick** [comment]
I think the rust is too old. Please update.

**Comment by Virgil-N** [comment]
> I think the rust is too old. Please update.

I had updated rust version to 1.61. Still not working.

**Comment by Virgil-N** [comment]
> Can you share your project? I can't help you without more information, you probably missed something. There's also a guide in the [docs](https://tauri.app/v1/guides/features/splashscreen).

Hey, my code is here: https://github.com/Virgil-N/test-app.git

**Comment by FabianLars** [comment]
@Virgil-N Your close_splashscreen function was _sync_, the [example](https://tauri.app/v1/guides/features/splashscreen#waiting-for-webpage) shows you that it _needs_ to be asnyc.
-> change the function signature to `async fn close_splashscreen(window: tauri::Window) {}`

**Comment by Virgil-N** [comment]
> @Virgil-N Your close_splashscreen function was _sync_, the [example](https://tauri.app/v1/guides/features/splashscreen#waiting-for-webpage) shows you that it _needs_ to be asnyc. -> change the function signature to `async fn close_splashscreen(window: tauri::Window) {}`

Problem solved. Thanks!

**Comment by aqdd** [comment]
Hello, my english is not good.
```
windows 10
tauri and rust both latest.
```
 tauri dev is ok.
```
splashscreen show -> close when domcontentloaded -> main show.
```
but after build, splashscreen show forever, and no main window.

![App vue](https://github.com/tauri-apps/tauri/assets/128227371/9630bf65-db18-4aaa-aec4-c99de8aff03d)
![main rs](https://github.com/tauri-apps/tauri/assets/128227371/5eb1cf91-fa52-4ac0-aff7-2bbb9913acea)
![tauri config json](https://github.com/tauri-apps/tauri/assets/128227371/1715c509-5736-4ca4-8c7a-bc2516d80cfd)

**Comment by aqdd** [comment]
> Hello, my english is not good.
> 
> ```
> windows 10
> tauri and rust both latest.
> ```
> 
> tauri dev is ok.
> 
> ```
> splashscreen show -> close when domcontentloaded -> main show.
> ```
> 
> but after build, splashscreen show forever, and no main window.
> 
> ![App vue](https://private-user-images.githubusercontent.com/128227371/304451451-9630bf65-db18-4aaa-aec4-c99de8aff03d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MzY0NDIsIm5iZiI6MTcwNzgzNjE0MiwicGF0aCI6Ii8xMjgyMjczNzEvMzA0NDUxNDUxLTk2MzBiZjY1LWRiMTgtNGFhYS1hZWM0LWM5OWRlOGFmZjAzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxNDU1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzE1ZGExZjA2YWVjMmU3ZGI1ZDFjM2Y1OTBmYjBkYjY3Njg0NTdmZTllYTM0YTkyMzE1ZDA0M2Y1NDAwZDQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QC1bkuZJn4kSoAgQlYfTqUFk8pfDNVboCeEIaE1ywr8) ![main rs](https://private-user-images.githubusercontent.com/128227371/304451469-5eb1cf91-fa52-4ac0-aff7-2bbb9913acea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MzY0NDIsIm5iZiI6MTcwNzgzNjE0MiwicGF0aCI6Ii8xMjgyMjczNzEvMzA0NDUxNDY5LTVlYjFjZjkxLWZhNTItNGFjMC1hZmY3LTJiYmI5OTEzYWNlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxNDU1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmI3MmI3YmZiNTA4YjBmMWQ2MzZlNGU1MjBlZDhmNmU0NmQwMzA0NTE5ZTczZjYzZjk5OGI1ZTQ2NjdlYzdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Zh9ymEuJWkesHMLg1_Bm32_OxaaR0Ap-hsWACN9KX_Y) ![tauri config json](https://private-user-images.githubusercontent.com/128227371/304451479-1715c509-5736-4ca4-8c7a-bc2516d80cfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MzY0NDIsIm5iZiI6MTcwNzgzNjE0MiwicGF0aCI6Ii8xMjgyMjczNzEvMzA0NDUxNDc5LTE3MTVjNTA5LTU3MzYtNGNhNC04YzdhLWJjMjUxNmQ4MGNmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxNDU1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTdiMTEzM2FmZmRhYzczNjllNjhjODc4OTFhM2ZlNmIxZTkzMmUzY2ZkNDE5NTQ0NzJiZTQ3ZWNkMTA3ZTdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ee_orPdB5xoJvtorIqB4JlDyPE5oOsWa0_gDv5vRfE0)

Sorry, code work fine. because i didn't write `Waiting for rust` in my code. sorry again.
