### ISSUE TITLE
[bug] Updater - Tauri API error: Invalid cross-device link (os error 18)

### ISSUE THREAD

**Issue by nabware** [tauri-apps/tauri#4500]
### Describe the bug

During the installUpdate() call, I receive the error "Tauri API error: Invalid cross-device link (os error 18)". I'm using a statically hosted update file following the [Update File JSON Format](https://tauri.app/v1/guides/distribution/updater/#update-file-json-format). I have the updater dialog set to false. I'm trying to update an AppImage.

I found another "Invalid cross-device link" [error](https://github.com/core-api/python-client/issues/176) in an unrelated python project.

![2022-06-27_22-51_1](https://user-images.githubusercontent.com/59323662/176104407-2e80266f-f990-47a0-b917-6d129bd19f88.png)

![2022-06-27_22-50](https://user-images.githubusercontent.com/59323662/176104454-79ffb321-f2ea-4bf1-8357-2fd977c0862c.png)

### Platform and versions

```shell
Environment
  › OS: Manjaro 21.3.1 X64
  › Node.js: 16.15.1
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../public
  › devPath: http://localhost:8080/
  › framework: Svelte
  › bundler: Rollup

App directory structure
  ├─ .git
  ├─ src-tauri
  ├─ public
  ├─ scripts
  ├─ .github
  ├─ .aws-sam
  ├─ src
  └─ node_modules
```

**Comment by lucasfernog** [comment]
Arch Linux uses [tmpfs](https://wiki.archlinux.org/title/tmpfs) for the default tmp dir (`/tmp`). Currently you need to check this manually and set the `TMPDIR` environment variable to `/var/tmp`.

**Comment by lucasfernog** [comment]
@lemarier I reported this a couple months ago, do you think we can catch this error and change the temp dir?

**Comment by lucasfernog** [comment]
The error happens when we use [rename](https://doc.rust-lang.org/std/fs/fn.rename.html).
> This will not work if the new name is on a different mount point.

**Comment by nabware** [comment]
Thanks @lucasfernog. Looking forward to seeing this reflected in the npm package.

**Comment by cosi-conda** [comment]
This is occurring for macos with tauri v1.2.1
