### ISSUE TITLE
[bug] Command not found

### ISSUE THREAD

**Issue by Virgil-N** [tauri-apps/tauri#4501]
### Describe the bug

There is two files in my src folder.

command.rs
```
#[tauri::command]
pub async fn disk_free_size(path: String) -> u64 {
  let sys = System::new_all();
  for disk in sys.disks() {
    if Path::new(&path).starts_with(disk.mount_point()) {
      return disk.available_space();
    }
  }
  0
}
```

main.rs
```
mod command;
.invoke_handler(tauri::generate_handler![
      command::show,
      command::exists,
      command::disk_free_size,
    ])
```

Codes in my frontend files.
```
const showFreeSpace = async () => {
const freeSpace = await invoke('disk_free_size', {path: currentPath}) as SetStateAction<number>
console.log(freeSpace)
setAvailableSpace(freeSpace)
}

useEffect(() => {
    if (isMountedRef.current) {
      showFreeSpace()
    }
  }, [
    isMountedRef
  ])
```

And I get error message: Uncaught (in promise) command disk_free_size not found.

How to solve it?

### Platform and versions

```shell
window 11
rust v1.61
tauri v1.0.0
```

**Comment by FabianLars** [comment]
You're overwriting the invoke_handler here: https://github.com/Virgil-N/test-app/blob/1b0998abdef49c3165428d3bf58bbd7a8e5ae640/src-tauri/src/main.rs#L65

This method is supposed to be called _only once_

**Comment by Virgil-N** [comment]
> You're overwriting the invoke_handler here: https://github.com/Virgil-N/test-app/blob/1b0998abdef49c3165428d3bf58bbd7a8e5ae640/src-tauri/src/main.rs#L65
> 
> This method is supposed to be called _only once_

Thanks for your help.
