### ISSUE TITLE
[bug] Trouble in Windows Code Signing

### ISSUE THREAD

**Issue by JSoon** [tauri-apps/tauri#4511]
### Describe the bug

I use EV certificate to sign the app bundled by tauri, which is a token-based USB-Key (provided by GlobalSign).
However, after entering the password of private key, the code signing failed then the build process just exited with a meaningless yarn error.

### Reproduction

1. Plug in the USB dongle

2. Config tauri.conf.json
```json
"windows": {
        "certificateThumbprint": "xxx",
        "digestAlgorithm": "sha256",
        "timestampUrl": "http://timestamp.comodoca.com/"
}
```
`windows.certificateThumbprint` is copied from the certificate details:

![certificateThumbprint](https://user-images.githubusercontent.com/7589350/176186708-6d6d1298-907e-4a62-ae27-e018d6ef4e40.PNG)

> BTW, "指纹" means thumbprint in Hanzi.

3. Run `yarn tauri build

During the build process, there is a prompt for private-key password, see screenshot below:

![password enter prompt](https://user-images.githubusercontent.com/7589350/176187072-6e1b7c16-18c5-4b39-845c-288755f5f517.PNG)

After I entered the correct password, the build process resumed then failed in the end.

![code-signing failed](https://user-images.githubusercontent.com/7589350/176187633-f7bdcaae-c34e-4b58-96c5-5a84dae6e726.PNG)

### Expected behavior

Code signing on Windows succeed with EV certificate of token-based USB-Key. At least there are clues I could track.

### Platform and versions

```shell
PS D:\projects\tauri-app> cargo tauri info

Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 103.0.1264.37
  › MSVC:
      - Visual Studio ���ɹ��� 2019
  › Node.js: 16.15.1
  › npm: 8.11.0
  › pnpm: 6.11.0
  › yarn: 1.22.15
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: Vue.js

App directory structure
  ├─ .vscode
  ├─ dist
  ├─ dist-isolation
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

### Stack trace

```shell
PS D:\projects\tauri-app> yarn tauri build
yarn run v1.22.15
$ tauri build
     Running beforeBuildCommand `yarn build`
$ vue-tsc --noEmit && vite build
vite v2.9.12 building for production...
✓ 35 modules transformed.
dist/assets/logo.03d6d6da.png    6.69 KiB
dist/index.html                  0.42 KiB
dist/assets/index.f0ced7b7.css   0.34 KiB / gzip: 0.24 KiB
dist/assets/index.bf2bf7d8.js    96.37 KiB / gzip: 30.15 KiB
   Compiling app v0.1.0 (D:\projects\tauri-app\src-tauri)
    Finished release [optimized] target(s) in 31.32s
        Info Target: x64
     Signing D:\projects\tauri-app\src-tauri\target\release\tauri-app.exe
     Signing D:\projects\tauri-app\src-tauri\target\release\tauri-app.exe with identity "b7870cd0512ad7cfcb3043b5122b1b4fde7db87a"
Error running CLI: failed to bundle project: `failed to run C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\signtool.exe`
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Additional context

Current docs on Windows - Code signing guide are insufficient somewhat. Could you please provide some support for the EV certificate?

**Comment by lucasfernog** [comment]
Can you try running with `tauri build --verbose` to see if there's an useful output from the signtool command?

**Comment by JSoon** [comment]
Thanks for the hint! @lucasfernog 

I got this solved from the verbose info:
```bash
        Info [tauri_bundler::bundle::windows::msi::wix] Target: x64
     Signing [tauri_bundler::bundle::windows::msi::wix] D:\projects\tauri-app\src-tauri\target\release\tauri-app.exe
     Signing [tauri_bundler::bundle::windows::sign] D:\projects\tauri-app\src-tauri\target\release\tauri-app.exe with identity "b7870cd0512ad7cfcb3043b5122b1b4fde7db87a"
       Debug [tauri_bundler::bundle::windows::sign] Running signtool "C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\signtool.exe"
     Running [tauri_bundler::bundle::common] Command `C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\signtool.exe  sign /fd sha256 /sha1 b7870cd0512ad7cfcb3043b5122b1b4fde7db87a /d tauri-app /t http://timestamp.comodoca.com D:\projects\tauri-app\src-tauri\target\release\tauri-app.exe`
Done Adding Additional Store

Number of errors: 1
SignTool Error: The specified timestamp server either could not be reached or
returned an invalid response.
SignTool Error: An error occurred while attempting to sign: D:\projects\tauri-app\src-tauri\target\release\tauri-app.exe
Error running CLI: failed to bundle project: `failed to run C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\signtool.exe`
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It looks like the timestamp server somehow could not be accessed back then, but everything's fine now!

Besides, I still think that we should add a chapter for code signing using USB-key EV certificate, in that in fact I do not need to convert `.cer` to `.pfx` and other procedures(the `.pfx` has already in the USB-key). All we need to do is entering the private key password and everything will be done!

**Comment by lucasfernog** [comment]
I still need to get one of those certs in order to see what we could improve in the CLI, but would love to see a PR to the docs!

**Comment by 0xDevrim** [comment]
How do you get the `pbx` from and `certificateThumbprint` from SafeNet lol ? I'm lost with the process
