### ISSUE TITLE
[bug] tauri vue can't load html in wslg.

### ISSUE THREAD

**Issue by JYInMyHeart** [tauri-apps/tauri#4513]
### Describe the bug

tauri vue can't load html in wslg.
![image](https://user-images.githubusercontent.com/26308552/176394319-682a4a3d-7f49-43a2-b71a-990a2ade8589.png)

### Reproduction

1.run `yarn create tauri-app` and choose vue to create a simple project.
2.run `yarn tauri:serve` to start debug mode.
3. wslg can't display anything.

### Expected behavior

wslg can work as a real linux desktop environment.

### Platform and versions

```shell
> ➜  appimage git:(master) ✗ cargo tauri info

Environment
  › OS: Manjaro 21.3.1 X64
  › Node.js: 16.15.1
  › npm: 8.12.2
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu

Packages
  › @tauri-apps/cli [NPM]: 1.0.0

> ➜  appimage git:(master) ✗ cat /mnt/wslg/versions.txt
WSLg ( x86_64 ): 1.0.39+Branch.main.Sha.cdbed82a21d382b5c74367c48a32ef4736cc8735
Mariner: VERSION="2.0.20220426"
mesa:
mesa:
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
FreeRDP: c574044a10003e50453acb4cf42801c5833fb572
weston: 4e99bb16dd44fc6daf4a45c46ba3e053c0637afa
```

### Stack trace

```shell
no error messages.
```

### Additional context

It works fine on mac and linux desktop. But it stucks in wslg on windows11. It doesn't print any error messages.

**Comment by SeaIsCoder** [comment]
i meet the same thing on windows11,

**Comment by amrbashir** [comment]
seems like you have a misconfigured app, if you used `create-tauri-app` the port should be `1420`, not `8080`, could you show your vite.conf.json and tauri.conf.json
