### ISSUE TITLE
[feat] Add hostname support in OS api

### ISSUE THREAD

**Issue by AlexanderYW** [tauri-apps/tauri#4517]
### Describe the problem

I'm facing an issue where I would like to be able to get the hostname to be able to identify users.

The purpose of this is not to track users, but to be able to get them to interact with each other without creating an account.

### Describe the solution you'd like

I would like to be able to fetch the hostname of the computer who is opening the application. NodeJS documentation for reference https://nodejs.org/api/os.html#oshostname

Ideally the solution would look something like
```typescript
  import { os } from '@tauri-apps/api';
  const computerHostname = await os.hostname();
```
and
```typescript
  import { hostname } from '@tauri-apps/api/os';
  const computerHostname = await hostname();
```

**Comment by amrbashir** [comment]
will be tracked in #2233

**Comment by AlexanderYW** [comment]
My bad @amrbashir, Thanks!

I totally overlooked that one, when i looked for an issue containing it 😵
