### ISSUE TITLE
[bug] I watching this repository release event, but every release new version, github send me some emails

### ISSUE THREAD

**Issue by tu6ge** [tauri-apps/tauri#4524]
### Describe the bug

about github

### Reproduction

no

### Expected behavior

no

### Platform and versions

```shell
unwanted
```

### Stack trace

```shell
unwanted
```

### Additional context

I watching this repository release event, but every release new version, github send me some emails, Can it send me only one email ?

**Comment by amrbashir** [comment]
Please modify that in your github account settings, we don't control that.
