### ISSUE TITLE
[feat] Load plugin from dynamic link libraries

### ISSUE THREAD

**Issue by SOVLOOKUP** [tauri-apps/tauri#4525]
### Describe the problem

I want to load plugin from dynamic link libraries while the app is running

### Describe the solution you'd like

Provides a way to compile plugins into dynamic link libraries. And an API to load plugins from dll while app is running.

**Comment by amrbashir** [comment]
Use [libloading](https://docs.rs/libloading/latest/libloading/) crate to dynamically load libraries.
