### ISSUE TITLE
[feat] Support using a .wixproj file

### ISSUE THREAD

**Issue by stephenlrandall** [tauri-apps/tauri#4541]
### Describe the problem

This issue arose for me when trying to add a `FipsCompliant` property to the Tauri WiX configuration (using the answer to this question: https://stackoverflow.com/questions/56467603/how-to-enforce-candle-exe-fips-with-fips-or-fipscomplianttrue-fipscompliant)

In the Tauri Discord, it was mentioned that Tauri does not currently support using a .wixproj.

### Describe the solution you'd like

I would like to be able to use a .wixproj file to add the properties I need on Windows.

### Alternatives considered

Because this issue is Windows-exclusive, I'm currently working around it by using the [run-script-os](https://www.npmjs.com/package/run-script-os) package with the `package.json` scripts:

```
...
"tauri-build": "run-script-os",
"tauri-build:win32": "tauri build -b none",
"tauri-build:default": "tauri build",
...
```

This will bypass the bundler on Windows entirely.

**Comment by lucasfernog** [comment]
We can't really use a wixproj :( It would mean a massive refactor at least - and we'll focus on NSIS now. I can add a config option for this though.
