### ISSUE TITLE
[docs] Request a tutorial of bundling different window customization on different platform.

### ISSUE THREAD

**Issue by Luciennnnnnn** [tauri-apps/tauri#4547]
Since window customization is popular on desktop apps, there is a style difference between different platforms, e.g. Windows app has its close button on the right-top corner, but macOS prefer a left-top style, window on Windows 10 has no round-corner but macOS always uses a round style.

I have no idea how to implement this customization elegantly, a clear tutorial is needed.

**Comment by amrbashir** [comment]
use `platform` from https://tauri.app/api/js/modules/os to determine the os currently running and change the titlebar behavior accordingly.
