### ISSUE TITLE
[bug]  thread 'main' has overflowed its stack

### ISSUE THREAD

**Issue by adminSxs** [tauri-apps/tauri#4548]
### Describe the bug

i use invoke_handler create new handler method 
start will fail: show message `thread 'main' has overflowed its stack`

i use unit test to execute is no problems

i integrate tokio async runtime

when i use `for x in xx`  or `iter` will occur the problem

### Platform and versions

```shell
› OS: Windows 10.0.19044 X64
  › Webview2: 103.0.1264.37
  › MSVC: 
      - Visual Studio Community 2022
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: 1.22.19       
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc
```

**Comment by lucasfernog** [comment]
I've seen this issue too, it only happens on Windows. Can you share the command you're using?

**Comment by lucasfernog** [comment]
I think I found a workaround for this. The problem is in the usage of the tokio runtime.

**Comment by adminSxs** [comment]
> I think I found a workaround for this. The problem is in the usage of the tokio runtime.

I need to upgrade the tauri version

> I've seen this issue too, it only happens on Windows. Can you share the command you're using?

run: cargo tauri dev

#[tokio::main]
async fn main(){}

**Comment by adminSxs** [comment]
> I think I found a workaround for this. The problem is in the usage of the tokio runtime.

what i need to do

**Comment by lucasfernog** [comment]
Either wait for the next release or follow https://tauri.app/v1/guides/faq#how-can-i-use-unpublished-tauri-changes

**Comment by adminSxs** [comment]
> Either wait for the next release or follow https://tauri.app/v1/guides/faq#how-can-i-use-unpublished-tauri-changes

thanks
