### ISSUE TITLE
[feat] Configurable `manufacturer` value

### ISSUE THREAD

**Issue by LoonyRules** [tauri-apps/tauri#4552]
### Describe the problem

The [current code](https://github.com/tauri-apps/tauri/blob/35b53784ee392dfca1b4e1633397ba8064139028/tooling/bundler/src/bundle/windows/msi/wix.rs#L576) forces a manufacturer without letting us override the value.

### Describe the solution you'd like

Expose a `manufacturer` variable in the `tauri.conf.json` either under the `package.manufacturer` key (or similar).

**Comment by amrbashir** [comment]
this has been implemented in #5283
