### ISSUE TITLE
[bug] Blank screen on starting tauri app (web version works just fine)

### ISSUE THREAD

**Issue by Blonteractor** [tauri-apps/tauri#4553]
### Describe the bug

After running `npm run tauri dev` on my project, the app window opens but I get a blank screen, if I open the web version at localhost:3000 it works just fine.

![image](https://user-images.githubusercontent.com/48821041/176876795-267fd778-3e36-44af-8930-ab737aa3302d.png)

![image](https://user-images.githubusercontent.com/48821041/176876938-2bc4d87b-37f2-4875-a962-7090a1f337d9.png)

### Expected behavior

I get the same output in the app as I do on localhost:3000

### Platform and versions

```shell
Environment
  › OS: Arch Linux Unknown X64
  › Node.js: 18.4.0
  › npm: 8.9.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.62.0
  › cargo: 1.62.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.2
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.2,
  › tauri-build [RUST]: 1.0.2,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: Vue.js

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ public
  ├─ src-tauri
  ├─ src
  ├─ dist
  └─ node_modules
```

### Stack trace

```shell
N/A
```

### Additional context

Same project works fine on my windows machine and even in Windows Subsystem for Linux running the same OS as this machine

**Comment by FabianLars** [comment]
Your frontend runs on the wrong port, take a look at the console output, it says 'localhost:3002'. Looks like there are orphaned processes still occupying port 3000.
And it works in the browser because you navigated to the correct port while tauri is still configured (devPath) to use port 3000
