### ISSUE TITLE
[bug] Using the splashscreen breaks sizing on the main window if resizable is false

### ISSUE THREAD

**Issue by Mar0xy** [tauri-apps/tauri#4558]
### Describe the bug

I played around with the splashscreen example code in the Guide and set my main window's size to something else while having resizable set to false.

The splashscreen opened as expected but when it switched over to the main window it always had some weird size set after playing around I figured out that by toggling resizable to true it would fix the weird sizing issue

How the window shows up after splashscreen with resizable set to false:
![image](https://user-images.githubusercontent.com/8841466/176934488-36627811-8dda-479c-9fa4-0684f34cd7ac.png)

### Reproduction

1. Configure Splashscreen
2. Set resizable to false on main window
3. Change width and height on main window

### Expected behavior

It is suppose to show the main window with the proper height and width set without having to turn on resizable

How it's suppose to look like(this was taken with resizable enabled on the same setup):
![image](https://user-images.githubusercontent.com/8841466/176934676-18ed8d80-6f7e-4403-9351-4c2e1534772f.png)

### Platform and versions

```shell
Environment
  › OS: EndeavourOS Rolling Release X64
  › Node.js: 16.14.0
  › npm: 8.5.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.2
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.2,
  › tauri-build [RUST]: 1.0.2,
  › tao [RUST]: 0.12.0,
  › wry [RUST]: 0.19.0,

App
  › build-type: build
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: Svelte

App directory structure
  ├─ .vscode
  ├─ public
  ├─ src
  ├─ node_modules
  ├─ src-tauri
  ├─ .git
  └─ dist
```

### Additional context

I have a second monitor above my first one so I don't know if this could be somehow related since it seems like the window decoration goes into the GNOME top bar trying to escape to the second monitor

**Comment by amrbashir** [comment]
Can you check if  this issue still persists with latest tauri?
