### ISSUE TITLE
[bug] Updater for Windows rebooting without prompt (rare)

### ISSUE THREAD

**Issue by betamos** [tauri-apps/tauri#4563]
### Describe the bug

If the install wizard thinks we're using some shared resource, and tauri is installing the update (passive mode), a reboot gets triggered automatically. This doesn't repro for me anymore, but still if there are other cases it may be worth fixing due to the invasiveness of rebooting. Perhaps check `msiexec /norestart` option or similar to figure out whether we can suppress this.

I ran into this due with `msvcp140.dll` which was in use by Firefox and several other apps. In my case it was a leftover from a previous tauri version. If you run into this issue, please clear your target dir first and make a fresh build.

### Reproduction

No repro atm.

### Expected behavior

Do not reboot.

### Platform and versions

```shell
Windows
```

**Comment by dceddia** [comment]
I had a user who was pretty sure that the updater forced an automatic reboot (!) too, which sounds like what you're seeing.

I've also seen dialogs after install that say a reboot is required, but I've only seen it once or twice. I'm not sure what triggers them, and the times I've seen it, my app is able to launch fine without a reboot.

**Comment by wcrd** [comment]
### Description
I am experiencing this issue on a simple Vue/Tauri app I have built. I am using the standard updater configuration with the built-in dialogue and a static update file JSON format ([docs](https://tauri.app/v1/guides/distribution/updater/#update-file-json-format)).

On release of a new version of my app updater runs successfully and then reboots the Windows 10 machine without warning. 

I have tried to include any relevant info I could think of, including the Windows 10 reboot Event details. Please let me know what else would help here...

### Platform and versions
Windows 10
```
"vue-cli-plugin-tauri": "^1.0.0-rc.3" 
"@tauri-apps/api": "^1.0.1"
"@tauri-apps/cli": "^1.0.2"
"@tauri-apps/tauri-forage": "^1.0.0-beta.2"
```

### Additional context
**Tauri.conf updater & access**
```
"updater": {
      "active": true,
      "endpoints": [
        "https://gist.githubusercontent.com/wcrd/129adc10c53a1d5b03e686d215598554/raw"
      ],
      "dialog": true,
      "pubkey": "<KEY>"
    },
"allowlist": {
      "all": false,
      "fs": {
        "readFile": true
      },
      "dialog": {
        "open": true
      },
      "http": {
        "all": true,
        "scope": [
          "<STORE_URL>"
        ]
      }
    }
```

**Windows 10 Event Log**
Note I have replaced some user ids with "_removed_"
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name="User32" Guid="{b0aa8734-56f7-41cc-b2f4-de228e98b946}" EventSourceName="User32" /> 
  <EventID Qualifiers="32768">1074</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8080000000000000</Keywords> 
  <TimeCreated SystemTime="2022-08-13T13:46:20.3528952Z" /> 
  <EventRecordID>141707</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="952" ThreadID="5140" /> 
  <Channel>System</Channel> 
  <Computer>_removed_</Computer> 
  <Security UserID="_removed_" /> 
  </System>
<EventData>
  <Data Name="param1">msiexec.exe</Data> 
  <Data Name="param2">_removed_</Data> 
  <Data Name="param3">No title for this reason could be found</Data> 
  <Data Name="param4">0x80030002</Data> 
  <Data Name="param5">restart</Data> 
  <Data Name="param6">The Windows Installer initiated a system restart to complete or continue the configuration of 'build-point-validator'.</Data> 
  <Data Name="param7">NT AUTHORITY\SYSTEM</Data> 
  </EventData>
  </Event>
```

**Comment by lucasfernog** [comment]
@wcrd you're using the RC version of vue-cli-plugin-tauri, try updating to 1.0.0.

**Comment by lucasfernog** [comment]
Also clear the src-tauri/target folder before recompiling.

**Comment by wcrd** [comment]
Thanks @lucasfernog. Since updating and clearing the src/target folder the updater is no longer rebooting the machine in my testing. Added bonus of my installer file size being ~20% smaller. Will update this thread if I catch the issue again. 

Thanks for your help!

**Comment by lucasfernog** [comment]
Thanks for the feedback. I believe you had the same issue as @betamos so i'll close this one since there shouldn't be another case of this.
