### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by buahaha** [tauri-apps/tauri#4567]
### Describe the bug

```shell
error: failed to parse manifest at `/Users/neosb/hax/app/app-app/app/src-tauri/Cargo.toml`

Caused by:
  library target names cannot contain hyphens: lib-lib
```

when fiddling with `Cargo.toml` making lib name with hyphen `-` crash the dev server run with `cargo-tauri dev`

### Reproduction

1. Create app
2. Make a lib in `Cargo.toml`
3. Change lib name to use hyphen and save.

### Expected behavior

Still run dev server or fail gracefully.

### Platform and versions

```shell
Environment
  › OS: Mac OS 11.6.7 X64
  › Node.js: 14.19.3
  › npm: 6.14.17
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.2
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.2,
  › tauri-build [RUST]: 1.0.2,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist/nutek
  › devPath: http://localhost:4200/
  › framework: Angular
  › bundler: Webpack

App directory structure
  ├─ dist
  ├─ .angular
  ├─ node_modules
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  └─ src
```

### Stack trace

```shell
error: failed to parse manifest at `/Users/neosb/hax/app/app-app/app/src-tauri/Cargo.toml`

Caused by:
  library target names cannot contain hyphens: lib-lib
```

### Additional context

Nothing I can think of that could be relevant.

I hope it can help.

Pozdrawiam :)

**Comment by amrbashir** [comment]
lib names (different from package name) can't have hyphens, only underscores
ref: https://doc.rust-lang.org/cargo/reference/cargo-targets.html#the-name-field

**Comment by buahaha** [comment]
I'm not specialized in Internet trolling, but the dev server is crashing due to this _the-name-filed_

**Comment by amrbashir** [comment]
please share a minimal repro

**Comment by buahaha** [comment]
thank you for the very quick reply, but I can't reproduce the issue. I get halted few times from dev server, but that's probably my stack and some really specific setup (I use Angular, but I have tried this time with Vanilla JS/HTML/CSS). If I get to the point where I know where it is, I will answer with a full bug report. No luck this time. Happy coding @amrbashir :)
