### ISSUE TITLE
[feature-request] Shell scope feature broke compatibility as its not possible to allow execution of arbitrary command through webview access

### ISSUE THREAD

**Issue by fogine** [tauri-apps/tauri#4575]
### Describe the bug

With the following shell allowlist config in `tauri.conf.json` it should be possible to execute any arbitrary shell command through webview access:

```json
"allowlist": {
          "shell": {
              "execute": true,
              "all": true,
              "open": "^.*$"
      }

}
```
Currently, after [shell scope feature](https://github.com/tauri-apps/tauri/commit/10314cd5cfe956fe5b3ae10acf551a92bdc366d3#diff-56223350b3043f0e5dd34402ce2fe0f870954ea360aeac525d420d2f38fc68c3R1452) was implemented, it requires `scope` array with white list of allowed commands..  

Use case is that we are developing internal tool for developers where the user is able to configure any shell command to be executed.. 

### Expected behavior

Instead of getting `program not allowed on the configured shell scope` error, it should allow to execute any command

### Platform and versions

```shell
Environment
  › OS: Arch Linux Unknown X64
  › Node.js: 14.16.1
  › npm: 6.14.12
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.7
  › @tauri-apps/api [NPM]: 1.0.0-rc.3
  › tauri [RUST]: 1.0.0-rc.6,
  › tauri-build [RUST]: 1.0.0-rc.5,
  › tao [RUST]: 0.7.0,
  › wry [RUST]: 0.14.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: Set automatically by Vue CLI plugin
  › devPath: Set automatically by Vue CLI plugin
  › framework: Vue.js (Vue CLI)
  › bundler: Webpack
```

**Comment by nothingismagick** [comment]
Please see `3.9 TRI-022` in the audit for an explanation of the reasoning behind this. 
https://github.com/tauri-apps/tauri/blob/dev/audits/Radically_Open_Security-v1-report.pdf

Also note, everything from Tauri is out of date, since we are now using stable 1.0 versions.

**Comment by lucasfernog** [comment]
You should write your own Tauri command to spawn child processes and validate it against the allowed shell commands.

Something like this:

```rust
#[derive(serde::Serialize)]
struct Output {
  stdout: String,
  stderr: String,
  status: i32,
}

#[command]
async fn run_command(command: String, args: Vec<String>) -> Output {
  // validate the command first
  // then run it
  let output = tauri::api::process::Command::new(command)
    .args(args)
    .output()
    // TODO: handle error
    .unwrap();
  Output {
    stdout: output.stdout,
    stderr: output.stderr,
    status: output.status.code().unwrap_or_default(),
  }
}
```

**Comment by ghalestrilo** [comment]
@lucasfernog Do commands spawned within rust need to be declared in the `tauri.conf.json` allowlist?

**Comment by FabianLars** [comment]
@ghalestrilo Nope.
