### ISSUE TITLE
[docs] link of webviews not exist

### ISSUE THREAD

**Issue by parrotdance** [tauri-apps/tauri#4576]
I'am exploring the API document ([version 1.0.2](https://docs.rs/tauri/1.0.2/tauri/index.html)) and I found these link is dead:

https://github.com/tauri-apps/tauri/blob/573b4c0b3cb7b1c46bea51911a0d86c7ec6a491f/core/tauri/src/window.rs#L651
https://github.com/tauri-apps/tauri/blob/573b4c0b3cb7b1c46bea51911a0d86c7ec6a491f/core/tauri/src/window.rs#L658

So where should I find document of webviews which Tauri used?

**Comment by lucasfernog** [comment]
I can load the first one https://docs.rs/webkit2gtk/latest/webkit2gtk/trait.WebViewExt.html
I'll fix the webview controller link.

**Comment by lucasfernog** [comment]
The correct link for now is https://docs.rs/webview2-com/0.17.0/webview2_com/Microsoft/Web/WebView2/Win32/struct.ICoreWebView2Controller.html.

@wravery can you check why the docs.rs build for webview2-com failed?

**Comment by wravery** [comment]
I'm not sure, it looks like it tried to build `x86_64-pc-windows-msvc`, but it was running on Linux and linking `x86_64-unknown-linux-gnu`. I think maybe this was a bug in docs.rs.

**Comment by wravery** [comment]
Actually, it looks like maybe the latest version of `windows-rs` may have broken cross-compilation. I tried building the latest version from WSL and I got the same error as docs.rs.
