### ISSUE TITLE
[feat] Devtools can install other plugin such as `Redux Devtools`

### ISSUE THREAD

**Issue by adminSxs** [tauri-apps/tauri#4582]
### Describe the problem

can install other plugin 

### Describe the solution you'd like

  › Node.js: 16.15.1
  › npm: 8.13.2
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.62.0
  › cargo: 1.62.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

**Comment by amrbashir** [comment]
None of the webviews we use has support for extensions and probably will never do.

**Comment by amrbashir** [comment]
You need to use the standalone version of the devtool if it exists.
