### ISSUE TITLE
Only GET and no headers/body on custom protocol on linux

### ISSUE THREAD

**Issue by mlthlschr** [tauri-apps/tauri#4595]
### Describe the bug

I am writing an App with a lightweight HTML frontend, only using HTMX as way to replace parts of the DOM. Thus the UI logic happens mostly in the rust part.

For that, I implemented an own URI scheme protocol via `register_uri_scheme_protocol`. Actually it is no own protocol, but I hijacked the `tauri` scheme.

Now the problem: It appears to me that all requests only reach tauri as `GET`.
Also, they always come without any headers or body.

### Reproduction

```rs
fn main()
  let context = tauri::generate_context!();
  tauri::Builder::default().register_uri_scheme_protocol("tauri", |_app, req| {
    println("{:?}", req);
    ... // custom handling
  })
  .run(context)
  .expect("kaput")
}
```

when running, I receive the following output

```js
Request { method: GET, uri: "tauri://localhost/create", headers: {}, body: [] }
Request { method: GET, uri: "tauri://localhost/create/person", headers: {}, body: [] }
```

### Expected behavior

This is the behaviour of my app on a mac, which is what I expect:

```js
Request { method: GET, uri: "tauri://localhost/create", headers: {"user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)", "hx-target": "modal", "accept": "*/*", "hx-request": "true", "hx-current-url": "tauri://localhost"}, body: [] }
Request { method: POST, uri: "tauri://localhost/create/person", headers: {"user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)", "accept": "*/*", "hx-request": "true", "content-type": "application/x-www-form-urlencoded", "content-length": "30", "hx-current-url": "tauri://localhost"}, body: [102, ...] }
```

### Platform and versions

```shell

Environment
  › OS: Arch Linux Unknown X64
  › Node.js: 18.4.0
  › npm: 8.9.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: Not installed!
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.0.0 (outdated, latest: 1.0.2)
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.0.1,
  › tauri-build [RUST]: 1.0.1,
  › tao [RUST]: 0.12.0,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../static
  › devPath: ../static
package.json not found

App directory structure
  ├─ src-tauri
  ├─ static
  └─ .git
```

### Additional context

Also, if I reply from tauri with a status code != 200, the webview still receives only 200 OK responses.

**Comment by mlthlschr** [comment]
[Found it](https://github.com/tauri-apps/wry/blob/c7987004eaaf5cb7da830d574d81bd96dace0112/src/webview/webkitgtk/web_context.rs#L227)/[Wry Issue](https://github.com/tauri-apps/wry/issues/614)

**Comment by huangjj27** [comment]
Hi, @mlthlschr, How did you send the request to your tauri app? invoke `tauri://` protocol from browsers with your app installed?
