### ISSUE TITLE
Do not share session between windows (Multiwindow)

### ISSUE THREAD

**Issue by slzno** [tauri-apps/tauri#4604]
I am working with several windows but I cannot find an option where session cannot be shared between windows. I would like each window to be independent.

**Comment by JonasKruckenberg** [comment]
What do you mean by "session"? The state? Events? Commands?

**Comment by slzno** [comment]
Hello @JonasKruckenberg, I mean that I want to have 3 GitLab windows each a different session, currently when creating the 3 windows it is always taking the first session of the first window.  it would be great if it had a partition option like electron https://www.electronjs.org/es/docs/latest/api/webview-tag#partition

**Comment by JonasKruckenberg** [comment]
Hmm okay, have you tried setting a different data directory for each window? https://docs.rs/tauri/1.0.2/tauri/window/struct.WindowBuilder.html#method.data_directory

**Comment by lucasfernog** [comment]
A custom data directory for each window does the trick (tested on Linux).
