### ISSUE TITLE
[bug] tauri req localhost:9001 in release bundle

### ISSUE THREAD

**Issue by IAIAE** [tauri-apps/tauri#4606]
### Describe the bug

dev version is ok. 

then i run `cargo tauri build`, then found  `/target/release/bundle/macos/xxx(my-app)`.  it render a  whole white page.   

then i try `/target/debug/xxxx(the shell)`, and inspect the devtool. seems tauri req the localhost:9001 in its release mode. why?

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/11187162/177549372-1c40709c-f9e0-4bde-aa13-4af776b53eba.png">

the little repo git :   https://github.com/IAIAE/yew-tauri-demo

and the env is:
- maos: 11.6.7
- rustc:  1.61.0 (fe5b13d68 2022-05-18)
- tauri: 1.0.2
- tauri-build: 1.0.2 

### Reproduction

1. clone my git 
2. cargo tauri dev (is ok)
3. cargo tauri build (build ok, but app run error)

### Platform and versions

```shell
Environment
  › OS: Mac OS 11.6.7 X64
  › Node.js: 12.19.0
  › npm: 6.14.8
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-apple-darwin
```

**Comment by lucasfernog** [comment]
You tried `/target/debug/xxxx(the shell)`, which is the dev app you were running when you executed `tauri dev`. To run the production build, you need to run `/target/release/xxxx(the shell)` (release folder).

**Comment by IAIAE** [comment]
/target/release/bundle/macos/xxx(my-app) and  /target/release/xxxx(the shell). both render a whole white page! where to find the log?  @lucasfernog

**Comment by lucasfernog** [comment]
You can run `cargo tauri build --debug` and it'll produce a debug production build on `/target/debug/bundle/macos/xxx(my-app)`. That way you can check the console for errors.

**Comment by IAIAE** [comment]
thx a lot
