### ISSUE TITLE
[bug] Verify signature error: InvalidSignature

### ISSUE THREAD

**Issue by JSoon** [tauri-apps/tauri#4610]
### Describe the bug

I have two versions of the test app. One is v1.0.0, and another is v1.0.1. 
I use a plain JSON file put on the gist as the [update file](https://tauri.app/v1/guides/distribution/updater/#update-file-json-format).
I put the updates on the github release.

When I opened v1.0.0 the updater dialog shows as expect, but there was no response after clicking on the `Yes` button.

![image](https://user-images.githubusercontent.com/7589350/177674186-c6a9aa64-f2af-4668-b897-8b29dcbddace.png)

I have listened the `tauri://update-status` event, and it gave out an error message bellow:

![image](https://user-images.githubusercontent.com/7589350/177671007-799fbb94-6b93-461e-91c5-2a977d9ac124.png)

I am pretty sure that I have generated the update signing key pairs as the [docs](https://tauri.app/v1/guides/distribution/updater/#signing-updates) said. And the update signing is success without errors(pls check the Stack trace).

I will attach some key fragments in the Additional context section.

### Expected behavior

Install the update and relaunch app successfully.

### Platform and versions

```shell
Environment
  › OS: Mac OS 10.13.6 X64
  › Node.js: 14.18.0
  › npm: 6.14.15
  › pnpm: 7.2.1
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.2
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.2,
  › tauri-build [RUST]: 1.0.2,
  › tao [RUST]: 0.12.0,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: Vue.js

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ dist-isolation
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  └─ src
```

### Stack trace

```shell
Bundling tauri-app_1.0.0_x64.dmg (/Users/soon/projects/tauri-app/src-tauri/target/release/bundle/dmg/tauri-app_1.0.0_x64.dmg)
     Running bundle_dmg.sh
     Signing /Users/soon/projects/tauri-app/src-tauri/target/release/bundle/dmg/tauri-app_1.0.1_x64.dmg with identity "Developer ID Application: xxx"
        Info using entitlements file at entitlements.mac.plist
    Bundling /Users/soon/projects/tauri-app/src-tauri/target/release/bundle/macos/tauri-app.app.tar.gz (/Users/soon/projects/tauri-app/src-tauri/target/release/bundle/macos/tauri-app.app.tar.gz)
    Finished 3 bundles at:
        /Users/soon/projects/tauri-app/src-tauri/target/release/bundle/macos/tauri-app.app
        /Users/soon/projects/tauri-app/src-tauri/target/release/bundle/dmg/tauri-app_1.0.1_x64.dmg
        /Users/soon/projects/tauri-app/src-tauri/target/release/bundle/macos/tauri-app.app.tar.gz (updater)

        Info 1 updater archive at:
        Info         /Users/soon/projects/tauri-app/src-tauri/target/release/bundle/macos/tauri-app.app.tar.gz.sig
```

### tauri.conf.json
```json
"updater": {
  "active": true,
  "endpoints": [
      "https://gist.githubusercontent.com/JSoon/2831042583d566c7772bf2a534a41805/raw/f87327ac6ad30252ec09215567937576ff24faf5/tauri-update-file.json"
  ],
  "dialog": true,
  "pubkey": "dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IDk3MkVBQkY1NDM3NjVEMUEKUldRYVhYWkQ5YXN1bDY1bnY4d1NPM2FLUkhxZ3V1OVFsRExuT2lsUzdVTkxBUGNnRVpRUmNMZTcK"
},
```

### tauri-update-file.json
```json
{
  "version": "v1.0.1",
  "notes": "Test version",
  "pub_date": "2022-07-01T11:25:57Z",
  "platforms": {
    "darwin-x86_64": {
      "signature": "dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVRYVhYWkQ5YXN1bHhQRmlFbDgyWDVNZ1JRMmNLaGtoSmtLNmE4aHJYMjYyV3o4U3FlbE10TnlxZGI5ZElRZCs0alY5K2RVb1dDRzAzckxpQmwxMUdQNmpYbURBK2NBSlFZPQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNjU3MTAwMzU3CWZpbGU6dGF1cmktYXBwLmFwcC50YXIuZ3oKcVFBYkZGRnJFbnQ3MW5QV25adEtBUXJzMmRPRUlPVVNteUROYWFpUU9KSVl2VW9CS3crOUtJbTIwMnRPUkhXeTM1eW1maExZTTdhUWVtWFg5SGhHRFE9PQo=",
      "url": "https://github.com/JSoon/tauri-app-updates/releases/download/t1.0.1-001/tauri-app.app.tar.gz"
    }
  }
}
```

### Updates assets
https://github.com/JSoon/tauri-app-updates/releases/tag/t1.0.1-001

**Comment by JonasKruckenberg** [comment]
How do you generate the `tauri-update-file.json?

**Comment by JSoon** [comment]
I create the `tauri-update-file.json` in the gist. It is just a plain JSON file, does it matter how I generate it?

**Comment by JSoon** [comment]
Just tested the same code on my Windows computer, and it worked as expected.

**Comment by JSoon** [comment]
Same code works on my Windows 10 computer, which reminds me that maybe it's the update signing keys generated on the Windows. I am going to try to regenerate the keys on the macOS to see if it will work.

**Comment by JSoon** [comment]
Tried regenerate keys using `tauri signer generate -w ~/.tauri/myapp.mac.key`.

1. Build v1.0.0
2. Build v1.0.1
3. Upload v1.0.1 update package
4. Update signature on the [tauri-update-file.json](https://gist.github.com/JSoon/2831042583d566c7772bf2a534a41805#file-tauri-update-file-json)
5. Install v1.0.0 and open it, I got the following error from console:

![image](https://user-images.githubusercontent.com/7589350/177745310-ac8501a8-e261-4dfa-b128-dcb4468d700f.png)

Any ideas?

**Comment by lucasfernog** [comment]
I think either the signature or the pubkey in tauri.conf.json are wrong.

**Comment by JSoon** [comment]
I'll check again tomorrow.

**Comment by JSoon** [comment]
Hi @lucasfernog , I have tested again for updater on my macOS. It failed again of error `Verify signature error: InvalidSignature`. Are there any details we can get in the log, such as sign private key and public key content used in the update signing, which could be useful for further debugging?

**Comment by lucasfernog** [comment]
Not really. Can you share which value from "tauri signer sign" you used as pubkey? We can enhance docs if you made a mistake with it.

**Comment by JSoon** [comment]
Thank you, @lucasfernog. I believe the docs has been written clear enough on **Updater** feature.

This issue has being ganked by creating all updates assets, including update JSON file and update packages, on my own HTTPS server. 

Finally it works just fine on both Windows and macOS.

**Comment by Tragio** [comment]
@JSoon I'm having the same problem. Did you solve this by moving from GitHub to your own server? 🤔

**Comment by AndonMitev** [comment]
Hey, I'm hitting same issue, generated keypair using `tauri signer generate` and updated pop up on the screen but when user accept the update then this error is thrown `Verify signature error: InvalidSignature` any ideas @lucasfernog

**Comment by RobZuazua** [comment]
fwiw, I was running into this issue recently with macOS and discovered that the reason was:

- I was running DMG and then trying to call updater for tar.gz 
and/or
- I was running the macOS/app and then trying to call updater for tar.gz 

What I had to do was:
1. unzip the original tar.gz and run that app 

then it worked and was able to get the next tar.gz version.

**Comment by thewh1teagle** [comment]
I experience the same issue in [Vibe](https://github.com/thewh1teagle/vibe) although I didn't changed anything special in the app and the updater worked for many previous versions.
Do you have idea why it happens?

<details>
<summary>screenshot</summary>
<img width=600 src="https://github.com/tauri-apps/tauri/assets/61390950/ed7d6eff-57e3-4861-8eb5-533a87ef863f">

</details>

[`tauri.conf.json`](https://github.com/thewh1teagle/vibe/blob/main/desktop/src-tauri/tauri.conf.json)

**Comment by ankitvermaAT** [comment]
> t a plain JSON file, does it matter how I genera

How its work because at my end it seems error:
Failed to check for update: JSON error: the `url` field was not set on the updater response

server json format:
{
  "version": "1.0.2",
  "windows-x86_64": {
    "signature": "dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVTMFBhQ2FaK2hSbWpsbVJ5d0JlWGtseEhFeTdpWndRK1c1NEhhTjZBaVFvcmNoSU5laHlYcFRQeG1ORVNXWG9zT3lmZElsdTY0eHFzVjNIQmI5ajNra56bjg45tyjnbgyuikbfrt0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzIxMTk1NTgyCWZpbGU6SW5kaWFfVG9kYXlfVFZfRW5nbGlzaF9OZXdzXzEuMC4yX3g2NF9lbi1VUy5tc2kuemlwCjZGWGZiT1BHaG1mcDhzdkR4RzhBa04veWlVNGJSZVZQOUMrTXNQT0FwbnAvQWxsMmY0NDNDVmxQeWJ6L2pIdlZTNmVUUjBqRjdDanBvbnJZZGVhSkN3PT0K",
    "url": "https://domain/windows/x86_64/1.0.1/myapp_1.0.2_x64_en-US.msi.zip"
  },
  "darwin-x86_64": {
    "signature": "dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVTMFBhQ2FaK2hSbWpsbVJ5d0JlWGtseEhFeTdpWndRK1c1NEhhTjZBaVFvcmNoSU5laHlYcFRQeG1ORVNXWG9zT3lmZElsdTY0eHFzVjNIQmI5ajNra56bjg45tyjnbgyuikbfrt0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzIxMTk1NTgyCWZpbGU6SW5kaWFfVG9kYXlfVFZfRW5nbGlzaF9OZXdzXzEuMC4yX3g2NF9lbi1VUy5tc2kuemlwCjZGWGZiT1BHaG1mcDhzdkR4RzhBa04veWlVNGJSZVZQOUMrTXNQT0FwbnAvQWxsMmY0NDNDVmxQeWJ6L2pIdlZTNmVUUjBqRjdDanBvbnJZZGVhSkN3PT0K",
    "url": "https://domain/windows/x86_64/1.0.1/myapp_1.0.2_x64_en-US.msi.zip"
  },
  "darwin-aarch64": {
    "signature": "dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVTMFBhQ2FaK2hSbWpsbVJ5d0JlWGtseEhFeTdpWndRK1c1NEhhTjZBaVFvcmNoSU5laHlYcFRQeG1ORVNXWG9zT3lmZElsdTY0eHFzVjNIQmI5ajNra56bjg45tyjnbgyuikbfrt0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzIxMTk1NTgyCWZpbGU6SW5kaWFfVG9kYXlfVFZfRW5nbGlzaF9OZXdzXzEuMC4yX3g2NF9lbi1VUy5tc2kuemlwCjZGWGZiT1BHaG1mcDhzdkR4RzhBa04veWlVNGJSZVZQOUMrTXNQT0FwbnAvQWxsMmY0NDNDVmxQeWJ6L2pIdlZTNmVUUjBqRjdDanBvbnJZZGVhSkN3PT0K",
    "url": "https://domain/windows/x86_64/1.0.1/myapp_1.0.2_x64_en-US.msi.zip"
  },
  "linux-x86_64": {
    "signature": "dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVTMFBhQ2FaK2hSbWpsbVJ5d0JlWGtseEhFeTdpWndRK1c1NEhhTjZBaVFvcmNoSU5laHlYcFRQeG1ORVNXWG9zT3lmZElsdTY0eHFzVjNIQmI5ajNra56bjg45tyjnbgyuikbfrt0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzIxMTk1NTgyCWZpbGU6SW5kaWFfVG9kYXlfVFZfRW5nbGlzaF9OZXdzXzEuMC4yX3g2NF9lbi1VUy5tc2kuemlwCjZGWGZiT1BHaG1mcDhzdkR4RzhBa04veWlVNGJSZVZQOUMrTXNQT0FwbnAvQWxsMmY0NDNDVmxQeWJ6L2pIdlZTNmVUUjBqRjdDanBvbnJZZGVhSkN3PT0K",
    "url": "https://domain/windows/x86_64/1.0.1/myapp_1.0.2_x64_en-US.msi.zip"
  }
}

**Comment by ankitvermaAT** [comment]
could you please help me I am getting error:
Verify signature error: UnexpectedKeyId
while update our app

**Comment by anderoavv** [comment]
Been trying to debug this `Verify signature error: InvalidSignature` for the past 2 days, without any luck..

1. Tried to generate new keys, with and without passwords.
2. From past issues that I've had with MacOS & Archives, tried restarting my computer, closing all Finder windows, while installing, compiling new versions - no luck

.key -> ENV
.key.pub -> Config
.sig -> release json

Compiles without any errors, if I try to use another key it says Warning that different key was used, which is nice that it does that but why am I still getting InvalidSignature, when I try to update the app and use correct keys..

Any suggestions..?

**Comment by thewh1teagle** [comment]
Check the files in the release in Github and try to reupload them

**Comment by anderoavv** [comment]
@thewh1teagle which files do you mean exactly? I'm running the build locally and I've tried to update every dependency etc.

**Comment by arminghm** [comment]
Is there any chance that you guys put the uncompressed file on server as your update bundle?
Consider your update bundle is `myapp.AppImage.tar.gz`, file `myapp.AppImage.tar.gz.sig` has the signature of the update bundle not the file inside id. 
The signature of the file inside `myapp.AppImage.tar.gz` is different.

**Comment by anderoavv** [comment]
Im pretty sure I did just that.

My release json looks like this:
`..{"signature":"dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVUUlNFZU9KV0Z3Qy9oWjVjc0JzOGMrKzk2ZnpZbWJ2dGxuclRsYU1sZmJrUzlPd2U4bm1ydGNGTWN2b3N4bk1zT24yL1ZVaXlCQTE5UTF3OG5ZcmFHY2puLytxZzR2UFE4PQp0cnVzdGVkIGNvbW1lpbWVzdGFtcDoxNzIzMTkyNjc4CWZpbGU6VGFpbS5hcHAudGFyLmd6ClhOV29kanRVMmJPQmMvVTVyWXlQMGFJODdtQjlYdVFNYllaanZobnltdXcwNTk2N1dVM1NTejQ2WTR2UEx6bFMvdEg3ZUpLNy9vNzhMMUpBRU1SL0JR","url":"https://xxxx.io/releases/download/0.1.14/xxx.app.tar.gz"}}} `

I uploaded tar.gz to the server and the contents of tar.gz.sig is the signature, but still no luck.

**Comment by isaac-svg** [comment]
For me this error occurred because I have my source code and releases in a private repo and and i get a 404 error during an update so i decided to change the url in the latest.json by hosting the binary on a public github repo.

**Comment by Fruup** [comment]
> For me this error occurred because I have my source code and releases in a private repo and and i get a 404 error during an update so i decided to change the url in the latest.json by hosting the binary on a public github repo.

@isaac-svg I have the same situation. Did you manage to solve the issue?

Is the file `latest.json` somehow included in the signature and changing the URLs inside it invalidates the signature?
