### ISSUE TITLE
[bug] splashscreen is not effective

### ISSUE THREAD

**Issue by Zhiqiang-Wu** [tauri-apps/tauri#4611]
### Describe the bug

splashscreen is not effective

![QQ截图20220707134913](https://user-images.githubusercontent.com/56793420/177702029-3141d753-6a27-4b97-a679-e5bf154adca2.png)

![QQ截图20220707134930](https://user-images.githubusercontent.com/56793420/177702036-a9bdf215-62cb-4470-980f-c844d7115221.png)

![QQ截图20220707135004](https://user-images.githubusercontent.com/56793420/177702042-848ea4c5-4652-4300-8cec-a8021454b3fa.png)

### Platform and versions

```shell
tauri 1.0.3
win x64
```

**Comment by JonasKruckenberg** [comment]
This sounds to me like an issue with your frontend routing setup, rather than an issue with Tauri itself. Have you tried the splashscreen example?

**Comment by Zhiqiang-Wu** [comment]
Calling the main method is valid, but tauri dev is invalid.

![QQ截图20220707173234](https://user-images.githubusercontent.com/56793420/177742556-0093e28b-d03d-47a3-8798-9ec3507e6c97.png)

![QQ截图20220707173610](https://user-images.githubusercontent.com/56793420/177742705-eb5f6531-39e5-4e31-804b-1e060abf9413.png)

**Comment by FabianLars** [comment]
Yeah this makes sense, because in a built app, it uses distDir, but in `tauri dev` your devserver doesn't serve files from the distDir

**Comment by Zhiqiang-Wu** [comment]
√

**Comment by vexxvakan** [comment]
I played around with the splashscreen example but as soon as I run yarn tauri build, my splashscreen.html is removed from the dist folder. Any ideas?

**Comment by FabianLars** [comment]
@vexxvakan This is your frontend bundler empying its output dir before building. Depending on your bundler, you can create a [multi-page app](https://vitejs.dev/guide/build.html#multi-page-app), or use a `public/` folder where you store files that you want to get copied unmodified into the build dir.

**Comment by chenthamizh** [comment]
> ### Describe the bug
> splashscreen is not effective
> 
> ![QQ截图20220707134913](https://user-images.githubusercontent.com/56793420/177702029-3141d753-6a27-4b97-a679-e5bf154adca2.png)
> 
> ![QQ截图20220707134930](https://user-images.githubusercontent.com/56793420/177702036-a9bdf215-62cb-4470-980f-c844d7115221.png)
> 
> ![QQ截图20220707135004](https://user-images.githubusercontent.com/56793420/177702042-848ea4c5-4652-4300-8cec-a8021454b3fa.png)
> 
> ### Reproduction
> _No response_
> 
> ### Expected behavior
> _No response_
> 
> ### Platform and versions
> ```shell
> tauri 1.0.3
> win x64
> ```
> 
> ### Stack trace
> _No response_
> 
> ### Additional context
> _No response_

You may write a route like "/splashscreen" in your react app. and add modify your tauri config values like the following
`
      {
        "width": 800,
        "height": 600,
        "decorations": false,
        "url": "/splashscreen",
        "label": "splashscreen"
      }
`
It will start to work
