### ISSUE TITLE
[bug] Auto Updater breaks app icon

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri#4613]
### Describe the bug

After an app configured to use auto updating is updated. It looses it's icon in the macOS "Applications" view in the Finder. This is only a temporary bug and the icon can be fixed be either restarting the machine or selecting "Show Package Contents".
Note that simply closing the Finder window or navigating to a different folder does not help.

<img width="285" alt="Screenshot 2022-07-07 at 10 14 32" src="https://user-images.githubusercontent.com/25329995/177728253-d26395da-edd2-4487-b6a0-6d3761ae6949.png">
 

### Reproduction

This is a bit hard to reproduce since the app I encountered this with is not yet open source, but here are the steps to follow along:
1. Have an app configured to use auto updater
2. download an older version
3. move the app to the "Applications" folder (to avoid the Read-only file system error)
4. open the app and let the updater run it's course
5. restart the app
6. the icon is replaced by the placeholder icon

### Expected behavior

The icon should continue to be displayed and not need a machine restart to show up.

### Platform and versions

```shell
Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: 7.5.0
  › yarn: 3.2.1
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.3
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.0.3,
  › tauri-build [RUST]: 1.0.3,
  › tao [RUST]: 0.12.0,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: connect-src http://localhost:55001; media-src https://*; style-src 'self' 'unsafe-inline'; frame-src https://*; image-src https://*; default-src 'self'
  › distDir: ../../plz-out/gen/frontend/dist/client
  › devPath: http://localhost:3000/
  › bundler: Rollup

App directory structure
  ├─ .config
  ├─ .husky
  ├─ .yarn
  ├─ infra
  ├─ frontend
  ├─ proto
  ├─ plz-out
  ├─ target
  ├─ node_modules
  ├─ desktop
  ├─ backend
  ├─ docs
  ├─ third_party
  ├─ graphql
  ├─ scripts
  ├─ .github
  ├─ .plz-cache
  ├─ build
  ├─ .git
  └─ .vscode
```

**Comment by nothingismagick** [comment]
I can confirm this. The only workaround I found was to click the `Get Info` from the context dropdown.

**Comment by lucasfernog** [comment]
I've seen this some times too. Maybe we need to update a DS_Store file?

**Comment by nothingismagick** [comment]
or `touch` the file?

**Comment by lucasfernog** [comment]
Seems like touch works @nothingismagick I'm making some tests in tauri now.
