### ISSUE TITLE
[bug] Unknown terminal window after app being opened

### ISSUE THREAD

**Issue by JSoon** [tauri-apps/tauri#4614]
### Describe the bug

Under development mode, there is no additional terminal window but the main window.

Under production mode(installed via .msi), there is always a terminal window opened with the main window.

![捕获](https://user-images.githubusercontent.com/7589350/177738780-077b4114-db0f-49eb-900c-8c603fb97ec1.PNG)

Any ideas why this happens?

### Expected behavior

There will not be the appearance of extra terminal window.

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 103.0.1264.49
  › MSVC:
      - Visual Studio ???? 2019
  › Node.js: 16.15.1
  › npm: 8.11.0
  › pnpm: 6.11.0
  › yarn: 1.22.15
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.3,
  › tauri-build [RUST]: 1.0.3,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: Vue.js

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ dist
  ├─ dist-isolation
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

**Comment by FabianLars** [comment]
This is what this
```rs
#![cfg_attr(
    all(not(debug_assertions), target_os = "windows"),
    windows_subsystem = "windows"
)]
```
at the top of the generated main.rs file is for. Just re-add it to get rid of the terminal (the terminal will still show if you build your app with `tauri build --debug`, it only has effect in `tauri build`
