### ISSUE TITLE
[feat] Add dylib support to `tauri.bundle.macOS.frameworks`

### ISSUE THREAD

**Issue by zengxs** [tauri-apps/tauri#4615]
### Describe the problem

When I set a dylib file path in `tauri.conf.json: tauri.bundle.macOS.frameworks`:
```json5
{
  "tauri": {
    "bundle": {
      "macOS": {
        "frameworks": [
          "../libs/libmsodbcsql.18.dylib"
        ]
```

An error occurs when packaging:
```log
Error failed to bundle project: Failed to bundle frameworks: Failed to bundle frameworks: `Framework path should have .framework extension: ../libs/libmsodbcsql.18.dylib`
```

### Describe the solution you'd like

As Apple's official documentation (ref [this](), see table 2-5) states:

The purpose of the `Contents/Frameworks` directory is 
> Contains any private <ins>shared libraries</ins> and <ins>frameworks</ins> used by the executable.

`dylib` files should also be a legal file type that can be copy to the `Contents/Frameworks` directory.

I think we can support both `*.dylib` file and `*.framework` bundle in `tauri.bundle.macOS.frameworks`.

### Alternatives considered

Considering that developers usually need to customize the content in the app bundle.

Is it possible to use a <ins>post-script stage</ins> for users to use custom scripts to process the content in the app bundle, this stage should be after the tauri bundle is completed, and before the codesign.

**Comment by codesoda** [comment]
@zengxs I see this was added in [tauri-v2.0.0-alpha.4](https://github.com/tauri-apps/tauri/releases/tag/tauri-v2.0.0-alpha.4). Are you using that version now, or did you find another work around?

**Comment by 0o-de-lally** [comment]
@FabianLars I get an error which I traced to here. Though the error message seems incomplete, suppressing upstream errors.  I get `Failed to bundle frameworks` without any of the error context.
```
Error failed to bundle project: Failed to bundle frameworks
error Command failed with exit code 1.
```
Using 1.5 (latest)

<img width="428" alt="Screenshot 2023-10-28 at 3 03 03 PM" src="https://github.com/tauri-apps/tauri/assets/1364012/07dd050c-4735-499b-9587-f7979c11752e">

**Comment by FabianLars** [comment]
@0o-de-lally Can you try it with the `--verbose` flag (if you use npm you may have to specify it as `-- --verbose` to forward it)

**Comment by 0o-de-lally** [comment]
Thanks @FabianLars 
I've done so, and I see more debug logs up top, but on bundling step I'm not getting any more info:

```
   >yarn build --verbose
    [...]
    Finished release [optimized] target(s) in 1m 39s
    Bundling [tauri_bundler::bundle::macos::app] [...]
    Error [tauri_cli_node] failed to bundle project: Failed to bundle frameworks
 ```
 and to to be sure I have forced these versions in package.json:
 ```
"@tauri-apps/api": "^1.5.1",
"@tauri-apps/cli": "^1.5.6",
```

Any other ideas for debugging?

**Comment by 0o-de-lally** [comment]
@FabianLars I think I found the issue from some brute forcing. Two cases produce that error:
1. If there is any other type of file besides .dylib or .framework, you'll get that error.
2. I was assuming that the root of relative path was from project/ but it was instead project/src-tauri.

So when I only included  `./whatver.dylib` I got beyond the error.
