### ISSUE TITLE
[bug] no sound on Windows (Angular)

### ISSUE THREAD

**Issue by boan-anbo** [tauri-apps/tauri#4624]
### Describe the bug

JS audio doesn't work with Tauri, either via library such as Howler or plain html audio `<audio>`. 

No errors thrown to the console of the main Tauri window. Just no sound.

The sound is activated through a button, so it is not an issue with user activation requirement.

**If serving Angular without Tauri via `ng serve`, and opened in browser (Chrome), the audio works OK.**

Howler example:
```
background = new Howl({
    src: ['/assets/audio/eponge.mp3'],
    preload: true,
    autoplay: true,
    html5: true,
    volume: 1,
  });

this.background.play()
 ```

### Reproduction

1. Create new tauri app with Angular on Windows
2. Use this simple example: https://stackblitz.com/edit/ng-audio?file=src%2Fapp%2Fapp.component.html

### Expected behavior

To hear the audio

### Platform and versions

```shell
Tauri: 1.0.3
Environment
  › OS: Windows 10.0.19043 X64
  › Webview2: 103.0.1264.44
  › MSVC: 
      - Visual Studio Community 2022
      - Visual Studio Build Tools 2019
  › Node.js: 16.14.2
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: 1.22.15
  › rustup: 1.24.3
  › rustc: 1.62.0
  › cargo: 1.62.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc
```

### Additional context

1. Checked my own system audio output; it's working fine.
2. Checked static audio file path for angular, the file is loaded without problem and Howler audio state says `playing`; 
3. Tried audio file of different sizes, super large and super small, none works in Tauri.
4. Tried  https://stackblitz.com/edit/ng-audio?file=src%2Fapp%2Fapp.component.html in browser, can hear it no problem.

**Comment by boan-anbo** [comment]
The sound suddenly worked somehow after another compilation. I don't know how and will report if this problem persists.

**Comment by amrbashir** [comment]
Let us know if it happens again.

**Comment by boan-anbo** [comment]
Hi there, unfortunately it's happening again.

I have been developing the same app for two weeks now. The sound had been working until another compilation just now and hasn't come back even after computer restart. 

# What I have checked

1. The output devices are all working outside Tauri.

2. No code changes regarding the sound compared to when the sound was working
 
3. The sound, whether the Wed Speech API or howler.js library, works perfectly in browser (via `ng service`).
 
4. I checked `navigator.mediaDevices.enumerateDevices()` in both Tauri and in browser (Chrome and Firefox). They are all properly listing audio devices, but their results are different:

## Tauri (no sound):
![image](https://user-images.githubusercontent.com/7269717/179370917-bbcff54c-5589-42bc-afbc-bf3aab519cd2.png)

- Note that even though Tauri's results of the `enumerateDevices` api are different, it shows correctly the default output device.

## Browser (sound works):
![image](https://user-images.githubusercontent.com/7269717/179370942-be2cb96f-4c43-4f65-986c-b02df23435f2.png)

5. Another observation is that even back when Tauri sound was working, I had a bluetooth earphone and a earphone plugged into the audio card. Only the connected earphone worked in Tauri but not the bluetooth earphone, while both bluetooth and the connected earphone work in browser.

6. Let me try Mac version later to see if it's Windows specific.

**Comment by amrbashir** [comment]
I launched a tauri window and pointed it out to https://ng-audio.stackblitz.io and the audio worked fine. Please provide a minimal repro with a tauri app.

**Comment by boan-anbo** [comment]
Thanks for the reply and replicating! Mine also returned normal and I still don't know why. But I assume it's something with my computer. Let me close this now until I have a reproduced repo.
