### ISSUE TITLE
[bug] Verify signature error: InvalidEncoding

### ISSUE THREAD

**Issue by drwhorx** [tauri-apps/tauri#4628]
### Describe the bug

Very similar to #4610, I'm trying to use a static JSON located in my github repo as an updater, but when I attempt an update I get `Verify signature error: InvalidEncoding`.

### Reproduction

1. Generate public and private keys with `tauri signer generate`
2. Populate tauri.conf.json pubkey with contents of .key.pub and updater endpoint with raw github link of updater JSON
3. Build and sign release
4. Upload .msi.zip to github as a release
5. Populate updater JSON with new version number, signature from contents of .msi.zip.sig, and url from from github release
6. Push JSON to github
7. Open older version of application and attempt update

### Expected behavior

It should pull the data from the raw JSON on github and update. Instead, checkUpdate succeeds and gets the proper info, but installUpdate returns `Verify signature error: InvalidEncoding`

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.18363 X64
  › Webview2: 103.0.1264.44
  › MSVC: 
      - Visual Studio Community 2019
  › Node.js: 16.14.0
  › npm: 8.13.2
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.62.0
  › cargo: 1.62.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.3
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.0.3,
  › tauri-build [RUST]: 1.0.3,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../content
  › devPath: ../content

App directory structure
  ├─ .git
  ├─ content
  ├─ node_modules
  └─ src-tauri
```

### Additional context

I'm opening this because #4610 was closed, but OP just changed strategies and used an updater server and the issue was never solved. It'd be a lot simpler to use a static JSON in my use case, so I'd like to get this working.

**Comment by lucasfernog** [comment]
@drwhorx can you share the project you're using? Also did you set `TAURI_PRIVATE_KEY` and `TAURI_KEY_PASSWORD` to the right values?

**Comment by drwhorx** [comment]
Sure; what all should I send and where? And yes, I believe so.

**Comment by lucasfernog** [comment]
I need an app repo with private key + pubkey + signature that I can use to see if you configure everything properly.

**Comment by drwhorx** [comment]
i ended up abandoning this since my clients don't have internet access anyways; but now i'm stuck in a corner since updater endpoints have to be https and i really don't want to (nor know how) to set up a certificate for just a local nodejs express server. i've moved this to a new feature request #4687, since this isn't really a bug but is more just a frustrating quirk.
