### ISSUE TITLE
[bug] Events not reaching front-end

### ISSUE THREAD

**Issue by AugustSaintFreytag** [tauri-apps/tauri#4630]
### Describe the bug

Neither events emitted via `&mut App`, `AppHandle`, nor the main `Window` ever arrive at the front-end using any methods `emit` (on window), `emit_to`, `emit_all`.

### Reproduction

Inside the set-up action of Tauri’s `main` function:

```rust
let window = app.get_window("main").unwrap();
let window_reference = window.clone();
let app_reference = app.handle();

window.on_menu_event(move |event| {
	println!("Hit menu event, dispatching event to front-end.");

	app_reference.emit_all("menu", "Test payload (emit all app) from Tauri.").unwrap();
	app_reference.emit_to("main", "menu", "Test payload (emit all app) from Tauri.").unwrap();
	window_reference.emit_all("menu", "Test payload (emit all) from Tauri.").unwrap();
	window_reference.emit("menu", "Test payload (emit) from Tauri.").unwrap();
});

println!("Set up window menu event listener and dispatch to front-end.");
Ok(())
```

Writing a custom asynchronous React hook to allow notification of window-related events:

```ts
export function useWindowEvent(callback: (event: Event<WindowEventPayload>) => void) {
	const [removeListenerBlock, setRemoveListenerBlock] = useState<Block | undefined>()

	useAsyncEffect(
		async () => {
			const removeListener = await listen("menu", event => {
				debugger
				callback(event as Event<WindowEventPayload>)
			})

			setRemoveListenerBlock(removeListener)
			console.log(`Registered async event listener for 'menu' event.`)
		},
		() => {
			removeListenerBlock?.()
		},
		[]
	)
}
```

All log messages are sent as expected, the debugger statement is never reached, no events are caught.

### Expected behavior

I’d expect all log messages to be sent as expected, all four events or at least the two global `app` events are caught in the listener, and the debugger statement is reached. 

### Platform and versions

```shell
Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 17.9.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: Not installed!
  › rustc: 1.59.0
  › cargo: 1.59.0
  › Rust toolchain:

Packages
  › @tauri-apps/cli [NPM]: 1.0.3
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.3,
  › tauri-build [RUST]: 1.0.3,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ node_modules
  ├─ docs
  ├─ public
  ├─ src-tauri
  ├─ build
  ├─ .git
  └─ src
```

### Additional context

The other event-handling method `appWindow.onMenuClicked` *does work* but if the more general-purpose approach does not, it’s a dreadful sign for the rest of this application.

**Comment by lucasfernog** [comment]
Tested this on a vanilla project and it works ok. Can you share a React project with your hook setup so I can check it?

**Comment by AugustSaintFreytag** [comment]
![Screenshot 2022-07-09 at 22 37 50@2x](https://user-images.githubusercontent.com/7656669/178121849-48a7953a-d134-4a68-8896-67337f519fa6.jpg)

Thanks, Lucas, I’ve investigated closer on the React side and just plainly setting up a listener in the `App.tsx` works.

I thought it might be the tear-down (clean-up) of the async effect hook running prematurely and thereby deleting the listener before it can ever be used but it just seems like the `useAsyncEffect` hook in general (which is an external module) somehow prevents the whole thing from working. It’s easy to whip your own async effect hook, so my rewritten generic hook for all kind of events on the window is now:

```ts
type RemoveListenerBlock = () => void

export function useWindowEvent<Payload>(name: string, callback: (event: Event<Payload>) => void) {
	return useEffect(() => {
		let removeListener: RemoveListenerBlock | undefined

		const setUpListener = async () => {
			removeListener = await appWindow.listen(name, event => {
				callback(event as Event<Payload>)
			})
		}

		setUpListener().catch(error => {
			console.error(`Could not set up window event listener. ${error}`)
		})

		return () => {
			removeListener?.()
		}
	}, [name, callback])
}
```

Used as:

```ts
interface MyCustomEventPayload {}

useWindowEvent<MyCustomEventPayload>("menu", event => {
	// Handle event here.
})
```

This now works, all four events I’m sending are caught equally.

**Comment by lucasfernog** [comment]
Damn React seems complicated :D good work on fixing it!

**Comment by M1cha** [comment]
This is much easier actually:
```js
useEffect(() => {
  const promise = listen("menu", event => {
    console.log(event);
  });

  return () => promise.then(remove => remove());
});
```

**Comment by elibroftw** [comment]
Even better way (note that we only need to run the hook once with [] )
```js
useEffect(() => {
  const promise = tauriEvent.listen('eventName', ({ payload, ...evventObj }) => {
    console.log('got payload:', payload);
  });
  return () => promise.then(unlisten => unlisten());
}, []);
```
