### ISSUE TITLE
[bug] Many tauri app start Xwayland even if they don't use it

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#4635]
### Describe the bug

When i start some tauri app Xwayland is launched even it's not used, and it's drawing battery.

### Reproduction

Start tauri app
Try to mitigate by blocking flatpak X11 access
Tauri app do not run anymore

### Expected behavior

Taury app start since it work on wayland

### Platform and versions

```shell
Report it myself since it's a bug on many tauri app (one is cinny).
```
See their issue : https://github.com/cinnyapp/cinny/issues/582

**Comment by Beanow** [comment]
Right now X11 _is being used_ and a dependency for Tauri. Using Xwayland is expected to work (with exception of [global shortcuts](https://github.com/tauri-apps/tauri/issues/3578)), but wayland-only will not work until the sections needing X11have been rewritten.

That said, I daily drive a Wayland desktop so it's also on my wishlist to look into this.

**Comment by amrbashir** [comment]
This has been fixed in https://github.com/tauri-apps/tao/commit/27ab6f4dcef19c052b0434873e34b54447b70860
