### ISSUE TITLE
[feat] Use Tauri app icon for development

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tauri#4637]
### Describe the problem

During development (at least on macOS), the app icon seems to be used for apps now. That looks great, but it means it's impossible to tell if you're using your production app, or running in development:
![image](https://user-images.githubusercontent.com/11315492/178119811-69f45736-2fbb-46f0-9c4e-05584d4556ac.png)

This could lead people to use the production app thinking it's the development one, and for example delete something important.

### Describe the solution you'd like

Use the Tauri app icon during development

**Comment by lucasfernog** [comment]
If we start using the Tauri icon, we'll get a feature request to get back to use the actual user icon. And soon we'll add a config option for development icons. Yikes.

It's your responsability as a developer to manage this. If your production app manages stuff that can't be deleted, then you must use a separate API endpoint or database for development or staging. If you can't do that, then add a banner on your UI saying **THIS IS THE DEVELOPMENT APP** or even add confirmation prompts before deleting something on dev.

Note that by changing the icon someone can still do mistakes, or are you checking the macOS dock before clicking the delete button? If you do, add a separate tauri config file and use it on dev: `tauri dev --config tauri.dev.conf.json` setting the icons array to something else.

**Comment by probablykasper** [comment]
That's fair, though I appreciated when it was easy to tell if Tauri was in dev mode by looking at the app icon, just like with Electron (or even with websites where you can check if the domain is `localhost`)

> If your production app manages stuff that can't be deleted, then you must use a separate API endpoint or database for development or staging.

Presumably they would already have separate api/db, otherwise it wouldn't matter since you'd be interacting with the same stuff anyway right? Maybe I'm misunderstanding what you mean
