### ISSUE TITLE
[bug] Blank screen when starting app

### ISSUE THREAD

**Issue by martinmr** [tauri-apps/tauri#4638]
### Describe the bug

App starts but window is blank.

### Reproduction

Follow the guide here: https://tauri.app/v1/guides/getting-started/setup/vite (same issue with the html/css guide as well).
When running `yarn tauri dev` I get a window but it's blank.

The development server is working and set to the correct port (port 3000) and I can access it on my browser but the window is blank.

### Expected behavior

Content appears in window.

### Platform and versions

```shell
Environment
  › OS: Debian unstable X64
  › Node.js: 16.15.1
  › npm: 8.13.2
  › pnpm: Not installed!
  › yarn: 1.22.19       
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.3
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.3,
  › tauri-build [RUST]: 1.0.3,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: Svelte

App directory structure
  ├─ node_modules
  ├─ src
  ├─ src-tauri
  ├─ .vscode
  └─ public
```
```


### Stack trace

_No response_

### Additional context

I am using WSL with XcSrvr as the X server. Other applications are running fine, so I am not sure why this is the case.

**Comment by martinmr** [comment]
My tauri config

```
{
  "$schema": "../node_modules/@tauri-apps/cli/schema.json",
  "build": {
    "beforeBuildCommand": "npm run build",
    "beforeDevCommand": "npm run dev",
    "devPath": "http://localhost:3000",
    "distDir": "../dist"
  },
  "package": {
    "productName": "trane-app",
    "version": "0.1.0"
  },
  "tauri": {
    "allowlist": {
      "all": true
    },
    "bundle": {
      "active": true,
      "category": "DeveloperTool",
      "copyright": "",
      "deb": {
        "depends": []
      },
      "externalBin": [],
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "identifier": "com.tauri.dev",
      "longDescription": "",
      "macOS": {
        "entitlements": null,
        "exceptionDomain": "",
        "frameworks": [],
        "providerShortName": null,
        "signingIdentity": null
      },
      "resources": [],
      "shortDescription": "",
      "targets": "all",
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "security": {
      "csp": null
    },
    "updater": {
      "active": false
    },
    "windows": [
      {
        "fullscreen": false,
        "height": 600,
        "resizable": true,
        "title": "Trane",
        "width": 800
      }
    ]
  }
}
```

**Comment by FabianLars** [comment]
Does it print ny errors in the terminal?
We don't support wsl in gui mode (other than wslg on win11 i guess), because webkit crashes on most configurations.
2 things you can try tho:
1) try the epiphany browser, it uses webkitgtk2 too
2) run vcxsrv in "One large window" mode (and start a DE session, like `$ xfce4-session` or whatever you have installed.

**Comment by martinmr** [comment]
@FabianLars Thanks. I just wanted to know if WSL was supported before deciding to either install linux in a separate partition or VM. I do get errors regarding the accessibility bus or something.

Are you saying that I should be able to run Tauri in WSL if I start it inside a DE session or will it also fail?

**Comment by FabianLars** [comment]
> Are you saying that I should be able to run Tauri in WSL if I start it inside a DE session or will it also fail?

Well, what i'm trying to say is that the chances are higher, not that it will definitely work. (Again, it's different for everyone, so it's hard to predict)

**Comment by martinmr** [comment]
Thanks. I'll try that.

EDIT: for future reference, I wasn't able to make it work inside a DE session. I ended up having to install linux in a separate partition, and it works now.
