### ISSUE TITLE
[feat] CLI command for versioning

### ISSUE THREAD

**Issue by RyKilleen** [tauri-apps/tauri#4643]
### Describe the problem

We use the very useful Tauri github action to auto build and draft release using semantic versioning.

It's really easy for me to forget a step when manually bumping versions. A normal flow looks lile

- `npm version (major | minor | patch)`
- `cd src-tauri`
- `cargo bump (major | minor | patch)`
- manually edit `tauri.config.json`
- `git commit --amend`

### Describe the solution you'd like

It'd be very nice to run `npm run tauri version (major | minor | patch)` and have the desired results!

### Alternatives considered

It's quite possible I'm over-complicating things and half of this is no longer necessary in post `v1.x.x` world

**Comment by FabianLars** [comment]
This would be a fun feature, but what's the use case for having 3 versions? Like do you _need_ the all 3? If so, for what?

**Comment by RyKilleen** [comment]
I guess I just like keeping all the numbers in the configs in sync 😄 In my mind I guess it could be misleading to see different numbers in different configs.

`tauri.config.json` is the only one with any real effect here, so I suppose if the Tauri CLI handles just that then it's a great step!

**Comment by vdvman1** [comment]
`tauri.config.json` already supports specifying a path to a `package.json` file as the version, and it will get the version number from the `package.json`

**Comment by sinistersnare** [comment]
Could `tauri.config.json` also read from a Cargo.toml? That would be great

**Comment by FabianLars** [comment]
@sinistersnare If you don't set any version (or path) in tauri.conf.json it will fall back to the version in Cargo.toml. Same for the name btw.

**Comment by sinistersnare** [comment]
Oh nice! This behavior isnt mentioned in [the docs](https://tauri.app/v1/api/config#packageconfig). Thanks for saying!

**Comment by Zercerium** [comment]
Hi, are you happy with the mentioned behaviour for your use case or do you think a version command would be helpful?

**Comment by gorentbarak** [comment]
Can you assign me to this?

**Comment by ahadley1124** [comment]
@gorentbarak, you can work on something for this and then mention this issue in a draft pr.

**Comment by s3xysteak** [comment]
I made a tool to achieve that , see [tauri-version](https://github.com/s3xysteak/tauri-version).
And I have used it to release a version of my own tauri-app, see example in [lethal-company-mods-copier v0.0.5 release](https://github.com/s3xysteak/lethal-company-mods-copier/tree/v0.0.5)

**Comment by s3xysteak** [comment]
> I made a tool to achieve that , see [tauri-version](https://github.com/s3xysteak/tauri-version). And I have used it to release a version of my own tauri-app, see example in [lethal-company-mods-copier v0.0.5 release](https://github.com/s3xysteak/lethal-company-mods-copier/tree/v0.0.5)

> tauri.conf.json + Cargo.toml + package.json
`npx tauri-version patch` : `0.0.2` -> `0.0.3`
`npx tauri-version patch -m release: v%s` : commit with message "release: v0.0.3" which default if "0.0.3"

**Comment by RyKilleen** [comment]
I'm closing this issue to avoid noise because:

> @sinistersnare If you don't set any version (or path) in tauri.conf.json it will fall back to the version in Cargo.toml. Same for the name btw.


This fits my use case. Thanks!
