### ISSUE TITLE
[bug] @tauri-apps/api/shell exists utf8 parsing error on window

### ISSUE THREAD

**Issue by horochx** [tauri-apps/tauri#4644]
### Describe the bug

When I use the simplified Chinese version of window, the console will return GBK encoded data and an `invalid utf-8 sequence of 1 bytes from index 0` error will occur. I think all non-English versions of window may have that problem.

### Reproduction

1. `import { Command } from '@tauri-apps/api/shell';`
2. `new Command('cmd', ['/C','echo 你好，世界']).execute();`

After that, you will get the error.

### Expected behavior

No string parsing errors.

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 103.0.1264.49
  › MSVC: 
      - Visual Studio ���ɹ��� 2019
  › Node.js: 16.15.1
  › npm: 8.11.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.62.0
  › cargo: 1.62.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0 (outdated, latest: 1.0.3)
  › @tauri-apps/api [NPM]: 1.0.1 (outdated, latest: 1.0.2)
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ build
  ├─ node_modules
  ├─ public
  ├─ rumqtt
  ├─ scripts
  ├─ src
  └─ src-tauri
```

### Additional context

In fact, I think the error comes from [this line](https://github.com/tauri-apps/tauri/blob/dev/core/tauri/src/api/process/command.rs#L395)，and I'd be happy to submit a PR in a few days to allow the user to specify the encoding (default utf-8) if you agree.

**Comment by mfts2048** [comment]
By the way, has the problem been solved

**Comment by horochx** [comment]
> By the way, has the problem been solved

Sorry, I've been busy with work lately and I probably won't have time to address this issue until this weekend.

**Comment by mfts2048** [comment]
Thank you very much
May I ask what your test case is?
![image](https://user-images.githubusercontent.com/44958959/181194919-9b942590-1e72-4be8-95cc-0eafcef2f142.png)
![image](https://user-images.githubusercontent.com/44958959/181195046-576aac67-eb15-478b-8710-a620a4d9995c.png)
![image](https://user-images.githubusercontent.com/44958959/181195086-b9449367-fccc-4894-8106-9956e4d132e0.png)

It's like powershell

I don't know if I was wrong

**Comment by mfts2048** [comment]
I am Windows

**Comment by horochx** [comment]
> Thank you very much May I ask what your test case is? ![image](https://user-images.githubusercontent.com/44958959/181194919-9b942590-1e72-4be8-95cc-0eafcef2f142.png) ![image](https://user-images.githubusercontent.com/44958959/181195046-576aac67-eb15-478b-8710-a620a4d9995c.png) ![image](https://user-images.githubusercontent.com/44958959/181195086-b9449367-fccc-4894-8106-9956e4d132e0.png)
> 
> It's like powershell
> 
> I don't know if I was wrong

use Encoding `gbk` instead of `utf-8`, it'll work :D

**Comment by mfts2048** [comment]
Thank you for helping me with the coding problem
In fact，Its a problem, I needed it to run on CMD instead of Powershell

**Comment by mfts2048** [comment]
![image](https://user-images.githubusercontent.com/44958959/181198845-1a6844bc-b36c-49b1-82ff-502095443b51.png)
![image](https://user-images.githubusercontent.com/44958959/181199489-8243c8d6-e0ee-4c89-ab25-77532c96aa47.png)

**Comment by horochx** [comment]
> ![image](https://user-images.githubusercontent.com/44958959/181198845-1a6844bc-b36c-49b1-82ff-502095443b51.png) ![image](https://user-images.githubusercontent.com/44958959/181199489-8243c8d6-e0ee-4c89-ab25-77532c96aa47.png)

This issue is not related to tauri. I guess it should work like this in PowerShell: `get-wmiobject -query "select * from win32_process where name='QQMusic.exe'"`. For more details, please refer to the [relevant official documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_wmi_cmdlets?view=powershell-5.1).

**Comment by mfts2048** [comment]
good, Thank you for your great help
