### ISSUE TITLE
[feat] Support run with administrator default.

### ISSUE THREAD

**Issue by Reknij** [tauri-apps/tauri#4645]
### Describe the problem

i want run my app with administrator default but i no found documment how to do it.

### Describe the solution you'd like

add config to setup requestedExecutionLevel.

**Comment by amrbashir** [comment]
do you mean the installer or the app itself?

if you mean the installer, it already runs with highest possible permissions for `perMachine` installation (we will offer a `perUser` option, see #2319). 

if you mean the app itself, you can't force it (at least not that I know of), the user has to run it as admin themselves. What you can do instead is instruct your users in README.md or similar to run as admin, maybe detect if the app is not admin and show them a dialog to with a button restart as admin using win32 API [`ShellExecuteW` with `runas`](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecutea#runas) as the operation or use powershell cmdlet [`Start-Process` with `-Verb runas`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/start-process?view=powershell-7.2#example-5-start-powershell-as-an-administrator).

**Comment by MoonWX** [comment]
Anyone who encounters this problem, and if u mean the app itself, check this out: #7173
