### ISSUE TITLE
[bug] WebView not consistent with that in Safari in MacOS

### ISSUE THREAD

**Issue by hgl** [tauri-apps/tauri#4667]
### Describe the bug

The webview in tauri doesn't support nullish coalescing operator (`?.`), yet my Safari browser supports it.

This is from the dev tool of latest Tauri:
![Screen Shot 2022-07-14 at 11 29 04 AM](https://user-images.githubusercontent.com/7038035/178891997-83335f0f-60e9-48f7-a5d6-6f005b00d8cc.png)

This is from the dev tool of Safari:
 
![Screen Shot 2022-07-14 at 11 30 12 AM](https://user-images.githubusercontent.com/7038035/178892108-f3f31f17-a682-4d2a-bb0e-64ce8c53e7fb.png)

The syntax error is from svelte (https://github.com/sveltejs/kit/issues/5130), which made it impossible to use the dev mode in tauri.

### Reproduction

1. Install tauri
2. Choose vite + svelte
3. Run tauri dev

### Expected behavior

The web page is displayed.

### Platform and versions

```
Environment
  › OS: Mac OS 10.13.6 X64
  › Node.js: 16.15.1
  › npm: 8.11.0
  › pnpm: 7.5.1
  › yarn: 1.22.15
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.0.0 (outdated, latest: 1.0.3)
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.3,
  › tauri-build [RUST]: 1.0.3,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › framework: Svelte

App directory structure
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .vscode
  └─ src
```

### Additional context

I wonder if it's an intrinsic limit of the webview or some of its flags need to be switched on in order for it to support new JS features?

**Comment by JonasKruckenberg** [comment]
Contrary to Safari, which has auto updating capabilities effectively back porting newer versions to older macOS releases, WKWebView is an OS component and updates to it are therefore tied to OS updates. [Our version testing](https://jonaskruckenberg.github.io/tauri-docs-wip/appendix/version-tables.html) indicates your Webview corresponds to Safari 11.1.2, so has not been updated since July 9, 2018. You should update your macOS version 😄

**Comment by t3touch** [comment]
I ran into same issue

**Comment by congtailai** [comment]
Is there a way for us to upgrade the webview (not OS) for the end user to ensure compatibility?

**Comment by FabianLars** [comment]
Nope
