### ISSUE TITLE
[feat] Background image needed for DMG distribution file for OSX

### ISSUE THREAD

**Issue by alfreddagenais** [tauri-apps/tauri#4669]
### Describe the problem

I search into the documentation for the background image for a .DMG file and I not found it. I need this image when I build for MacOs.

Have a solution now or it will came soon?

### Describe the solution you'd like

I just saw examples like this : 
![687474703a2f2f692e696d6775722e636f6d2f6c6153423432782e706e67](https://user-images.githubusercontent.com/5769264/178905226-cd3595ed-fb27-43c5-8228-e9d74f053262.png)

![38463339-8e93445e-3ac6-11e8-82f8-58e6cd789077](https://user-images.githubusercontent.com/5769264/178905447-7fa75f31-7047-4f8e-ad23-6cd003ecb7d5.png)

![38463360-f9bb695a-3ac6-11e8-87af-e56fbce03da9](https://user-images.githubusercontent.com/5769264/178905461-99a08993-30f6-493f-9998-38ff86edbeb5.png)

![38463361-ff0480f4-3ac6-11e8-8256-1962981b7f71](https://user-images.githubusercontent.com/5769264/178905484-4849c0a8-6f2d-45b4-9f1b-b937df5efd51.png)

### Alternatives considered

I saw the file `bundle_dmg.sh` from the build folder `src-tauri/target/release/bundle/dmg/bundle_dmg.sh` and into this file i have an option for the background

![Capture-2022-07-14_01-24-03-000321](https://user-images.githubusercontent.com/5769264/178905897-cede411b-9db2-435e-9923-0dd5257cdaa5.png)

But I have no idea where I can find this file.

![Capture-2022-07-14_01-25-44-000323](https://user-images.githubusercontent.com/5769264/178906035-4e858eab-cbc5-4d4d-b3c9-348916d8bcf3.png)

**Comment by Blatman** [comment]
Also looking at this part of the bundling process. The basic DMG bundling works very well but I'm at a loss at how to customise certain parts. I would at least like to use a custom background and a volume icon for the DMG itself. At the moment the first icns file found in the icons folder appears to be used (icon.icns) which is the app icon itself and unable to find a way to link a background image. The bundle_dmg.sh can't be edited as all the files appear to be regenerated on each build (both the Vol_Name and Vol_Icon in the generated .sh file just point to $2). Unable to find where the .sh script is generated from. Unable to find any sample apps with customised DMG's. Hate to think that this rudimentary customisation may involve a GitHub fork of Tauri.

**Comment by ahkohd** [comment]
I was able to make this work for my Tauri app DMG. I had to do it manually using [create-dmg.](https://github.com/create-dmg/create-dmg) 

Build your Tauri app. Get the path to the `YourApp.app`.

Install create-dmg:
```bash
$ brew install create-dmg
```
Build the DMG from the YourApp.app, pass the installer background option:
```bash
$ create-dmg
    --volname "YourAppName" \
    --volicon "path/to/your/icon.icns" \
    --background "path/to/your/background/image.png" \
    --window-pos 200 120 \
    --window-size 835 600 \
    --icon-size 128 \
    --icon "YourApp.app" 230 295 \
    --hide-extension "YouApp.app" \
    --app-drop-link 593 295 \
    "path/where/your/dmg/will/be/generated.dmg" \
     "path/to/YourApp.app"
```
You can find the reference on how to use [`create-dmg` here](https://github.com/create-dmg/create-dmg#usage).

An example of how I used the create-dmg for my [app](https://usezap.sh):
```bash
$ create-dmg \
    --volname "Zap" \
    --volicon "./src-tauri/icons/icon.icns" \
    --background "./src/assets/installer-background.png" \
    --window-pos 200 120 \
    --window-size 835 600 \
    --icon-size 128 \
    --icon "Zap.app" 230 295 \
    --hide-extension "Zap.app" \
    --app-drop-link 593 295 \
    "./src-tauri/target/aarch64-apple-darwin/release/bundle/macos/Zap.dmg" \
    "./src-tauri/target/aarch64-apple-darwin/release/bundle/macos/Zap.app"
```
Result:
![image](https://user-images.githubusercontent.com/13041443/189504068-adfe89d1-dc64-43e2-aaea-7246948bae70.png)

**Comment by alfreddagenais** [comment]
@ahkohd thank you for the hint! I will try this tool to see it!

**Comment by ahkohd** [comment]
> @ahkohd thank you for the hint! I will try this tool to see it!

You're welcome. Keep in mind that you will have to tweak the icon position and design your installer background to match the configuration you provide to the create-dmg tool. 

I can share my app's installer background design on Figma so that you can have a head start.

**Comment by muryoh** [comment]
fyi, if you only need to set the background, you can get away with setting some env variables because of the way the create-dmg script was written: https://github.com/create-dmg/create-dmg/blob/412e99352bacef0f05f9abe6cc4348a627b7ac56/create-dmg#L139

Setting BACKGROUND_FILE, BACKGROUND_FILE_NAME and BACKGROUND_CLAUSE in the context of the tauri build command will result in your background file being used
