### ISSUE TITLE
[bug] undefined is not an object (evaluating 'navigator.mediaDevices.enumerateDevices')

### ISSUE THREAD

**Issue by Jinx-1120** [tauri-apps/tauri#4677]
### Describe the bug

hi,  When I use navigator to get devices, I get some errors

![image](https://user-images.githubusercontent.com/26374251/179142323-3939dbe1-a67d-45ef-ad71-ee0b0c960092.png)

This is sample code：
```jsx
import logo from './logo.svg';
import './App.css';

function App() {
  const handelUseCamera = () => {
    navigator.mediaDevices.enumerateDevices().then((devices) => {
      console.log(devices);
    });
  };

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>Hello Vite + React!</p>
        <button onClick={handelUseCamera}>Use Camera</button>
      </header>
    </div>
  );
}

export default App;

```

### Reproduction

The project I used to initialize the PNPM

### Expected behavior

I hope to use navigator.mediadevices.enumeratedevices ()

### Platform and versions

```shell
> tauri "info"


Environment
  › OS: Mac OS 12.2.1 X64
  › Node.js: 14.18.2
  › npm: 6.14.15
  › pnpm: 7.1.9
  › yarn: 1.22.17
  › rustup: 1.25.0
  › rustc: 1.62.0
  › cargo: 1.62.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.3 (outdated, latest: 1.0.4)
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.3,
  › tauri-build [RUST]: 1.0.3,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ .husky
  ├─ dist
  ├─ node_modules
  ├─ src-tauri
  ├─ .git
  └─ src
```

**Comment by JonasKruckenberg** [comment]
This is a macOS sandboxing restriction, you need to declare your usage of these APIs in an `Info.plist` file. See this guide from apple for details: https://developer.apple.com/documentation/avfoundation/capture_setup/requesting_authorization_for_media_capture_on_macos?language=objc

example: 

src-tauri/Info.plist
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSCameraUsageDescription</key>
	<string>This app requires camera access to capture your dog photos.</string>
        <key>NSMicrophoneUsageDescription</key>
	<string>This app requires microphone access to record your greeting.</string>
</dict>
</plist>
```

**Comment by learncodingforweb** [comment]
i am getting same issue in raspberry pi 4 OS. How can i solve this?

**Comment by FabianLars** [comment]
@learncodingforweb webkitgtk (the webview used on Linux) does not support webrtc yet. Not much one can do here except for waiting.

**Comment by felri** [comment]
@FabianLars so accessing media devices like webcam is not possible in linux right now?

**Comment by FabianLars** [comment]
correct!

Edit: Unless you wanna deep dive into Rust, then there should be ways to do so outside of the webview.
