### ISSUE TITLE
[bug] Cannot run API Example on Mac due to `Cannot find module '@tauri-apps/cli-darwin-arm64'` error

### ISSUE THREAD

**Issue by Gumichocopengin8** [tauri-apps/tauri#4705]
### Describe the bug

In order to run API example, I followed https://github.com/tauri-apps/tauri/tree/dev/examples/api. However, I got the following error.

```
>> yarn
yarn install v1.22.19
warning package.json: No license field
warning svelte-app@1.0.0: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 2.10s.
~/D/s/t/e/api ❯❯❯ yarn tauri dev
yarn run v1.22.19
warning package.json: No license field
$ node ../../tooling/cli/node/tauri.js dev
/tauri/tooling/cli/node/index.js:234
    throw loadError
    ^

Error: Cannot find module '@tauri-apps/cli-darwin-arm64'
Require stack:
- /tauri/tooling/cli/node/index.js
- /tauri/tooling/cli/node/main.js
- /tauri/tooling/cli/node/tauri.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/tauri/tooling/cli/node/index.js:125:29)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tauri/tooling/cli/node/index.js',
    '/tauri/tooling/cli/node/main.js',
    '/tauri/tooling/cli/node/tauri.js'
  ]
}

Node.js v18.3.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Platform and versions

```shell
I cannot use `npm run tauri` or `yarn tauri`. so cannot show tauri info


- Mac 12.4 M1
- Rust 1.62.0
- Node v18.3.0
```

**Comment by amrbashir** [comment]
do `cd tooling/cli/node && yarn && yarn build` first
or run `.scripts/setup.sh`

**Comment by Gumichocopengin8** [comment]
I followed the instruction and tried both `cd tooling/cli/node && yarn && yarn build` and `.scripts/setup.sh`, but I doesn't work.

**Comment by amrbashir** [comment]
just noticed u are on mac M1, pinging @lucasfernog

for the moment, you can just
```sh
cd tooling/cli
cargo install --path . # will install tauri-cli globally as a cargo subcommand
cd ../../examples/api
cargo tauri dev
```

**Comment by Gumichocopengin8** [comment]
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/34010665/179664872-f435132c-9756-4f8f-835a-3a3deaf0ec59.png">
Thank you for the suggestion, but I cannot see anything on the window.

**Comment by amrbashir** [comment]
Right click and open the dev tools to see if there is any erros? Also in the console do you see the vite serve runnning?

**Comment by Gumichocopengin8** [comment]
I don't see any errors in the browser console. Vite is running well.
After running `yarn upgrade --latest` it works properly. However, notification API doesn't work.
Anyways, it works good now. Thank you for your help.

**Comment by maxruizg** [comment]
running :
$ pnpm install
$ pnpm upgrade --latest

it worked for me

**Comment by MichaelVoelkel** [comment]
> just noticed u are on mac M1, pinging @lucasfernog
> 
> for the moment, you can just
> 
> ```shell
> cd tooling/cli
> cargo install --path . # will install tauri-cli globally as a cargo subcommand
> cd ../../examples/api
> cargo tauri dev
> ```

[plugin:vite:import-analysis] Failed to resolve import "@tauri-apps/api/shell" from "src/App.svelte". Does the file exist?

Is my error then

**Comment by lucasfernog** [comment]
You also need to run `yarn && yarn build` on `tooling/api`. Then go back to `examples/api` and `rm -rf node_modules && yarn`.

**Comment by MichaelVoelkel** [comment]
This indeed works... could you explain why all these steps are needed in this order? It seems overly complicated

**Comment by andrewschreiber** [comment]
In my case I had to make sure to approve the Node CLI as well as following the above steps.
