### ISSUE TITLE
[bug] /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found"

### ISSUE THREAD

**Issue by spirityy** [tauri-apps/tauri#4707]
### Describe the bug

![Hi ECARX20220718-173002](https://user-images.githubusercontent.com/424997/179483436-9c8686c4-7c2e-472f-a2e1-5e1a0ed26e94.jpg)

### Platform and versions

```shell
ubuntu 20 build, ubantu 16 run app.
```

**Comment by Beanow** [comment]
Hi, this is a known limitation explained here: https://tauri.app/v1/guides/distribution/linux#limitations
You have to build on the oldest system you want to support.
