### ISSUE TITLE
[feat] WebViewWindow should provide access to the `document` property

### ISSUE THREAD

**Issue by miniBill** [tauri-apps/tauri#4710]
### Describe the problem

Elm uses `window.open` for its debugger. Critically, I cannot simply replace the call to `window.open` with the `WebviewWindow` API because it doesn't allow access to the `document` property of the opened windows.

### Describe the solution you'd like

Either
a. `WebviewWindow` provides a `document` property compatible with what browsers offer or, even better,
b. the `window.open` API is implemented exposing types compatible with browser ones.

### Alternatives considered

I've considered mocking all the properties and calls using a `Proxy`, but it's actually calling nontrivial JS functions on the document itself, and I think it would be a huge undertaking for something that can be done more efficiently by tauri.

**Comment by lucasfernog** [comment]
We can't expose `window` properties in WebviewWindow, the webview wouldn't allow it and it would be a security nightmare without the browser sandbox and same-origin policy enforced.

**Comment by amrbashir** [comment]
You should just use events to manipulate other windows.

**Comment by miniBill** [comment]
@lucasfernog Browsers do allow you to manipulate the `window` you get from `window.open` so they apparently have a way to do that safely

@amrbashir The code that opens the window and manipulates it is in a library, I'd use events if it was my code

**Comment by lucasfernog** [comment]
Yeah but then we'd need to implement window.open for all webviews, which i'm not sure is possible. You could open an issue at the wry repo so they can check that.

**Comment by miniBill** [comment]
@lucasfernog thanks for you time 💜 will try opening an issue in the wry repo

**Comment by miniBill** [comment]
Opened as https://github.com/tauri-apps/wry/issues/649

**Comment by nothingismagick** [comment]
Just my two cents, maybe this is something that could be patched at the elm
level.

The reasoning, is that elm was designed for the browser sandbox, and as
Lucas said we don't have that kind of safety in the webview ecosystem. As
more people start using elm + tauri, it could become a valid concern.
Another thought is to actually build a tauri app that could serve as the
target for the debugger...
