### ISSUE TITLE
[doc] Comments in tauri.conf.json

### ISSUE THREAD

**Issue by melMass** [tauri-apps/tauri#4711]
### Describe the problem

AFAIK tauri.conf.json used to be parsed similarly to jsonc, ie. compatible with comments.
Since a recent update it fails.

### Describe the solution you'd like

I had to choose a section so I choose feat, but I don't really need it, I just wanted clarifications on the change :)

**Comment by FabianLars** [comment]
you can enable the `config-json5` feature on the tauri dependency in Cargo.toml and rename the config file to `tauri.conf.json5`. for a list of features of json5 see here: https://json5.org/

**Comment by nothingismagick** [comment]
We should document this better, for sure. I can't even find it in the rustdocs and would expect to at least find it mentioned here:

https://docs.rs/tauri/1.0.4/tauri/struct.Config.html

**Comment by melMass** [comment]
Wow nice, I didn't even know about JSON5, thanks for the clarifications and I agree, it might be documented better, especially since early tauri.conf.json in the docs had comments 😄

**Comment by lucasfernog** [comment]
I added the relevant documentation in #4813
