### ISSUE TITLE
Cannot bundle the executable when target is fed to extra options [bug] 

### ISSUE THREAD

**Issue by ozgunozerk** [tauri-apps/tauri#4720]
### Describe the bug

When I run the command `yarn tauri build -- -- -Z build-std --target aarch64-apple-darwin`, the bundler looks for the executable under `release` folder, instead of `aarch64-apple-darwin` folder. Here is the error:
```
    Finished release [optimized] target(s) in 6m 15s
    Bundling subspace-desktop.app (/Users/ozgunozerk/Developer/subspace-desktop/src-tauri/target/release/bundle/macos/subspace-desktop.app)
       Error failed to bundle project: Failed to copy binary from "/Users/ozgunozerk/Developer/subspace-desktop/src-tauri/target/release/subspace-desktop": Failed to copy binary from "/Users/ozgunozerk/Developer/subspace-desktop/src-tauri/target/release/subspace-desktop": `"/Users/ozgunozerk/Developer/subspace-desktop/src-tauri/target/release/subspace-desktop" does not exist`
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I tried with `cargo tauri build ...` and `yarn tauri build ...` did not make a difference. 

It works when: `yarn tauri build --target aarch64-apple-darwin`. Means, the bundler looks for the correct folder instead of `release` folder. 

Here are the both commands (not working, then working) to compare them more easily:
`cargo tauri build -- -Z build-std --target aarch64-apple-darwin`
`cargo tauri build --target aarch64-apple-darwin`

When the `--target` flag is supplied as a `tauri` argument, it works. When it is supplied as an extra option, it does not. 

You might say: *then use the working version?? What is the issue here?*. 
The issue is, `-Z build-std` requires a target near itself, so in this case, I'm unable to use `-Z build-std`. 

### Expected behavior

Bundler should work when `--target` flag is supplied as an extra option as well.

### Platform and versions

```shell
yarn tauri info
yarn run v1.22.19
$ tauri info

Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 16.14.2
  › npm: 8.5.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.63.0-nightly
  › cargo: 1.63.0-nightly
  › Rust toolchain: nightly-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.0.4
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.4,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: default-src tauri 'self'; img-src 'self'; object-src 'none'; connect-src ws://localhost:9947/; script-src 'wasm-unsafe-eval' 'unsafe-eval' 'self'
  › distDir: ../dist/pwa
  › devPath: http://localhost:3009/
  › framework: Vue.js (Quasar)
  › bundler: Webpack

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ .quasar
  ├─ src-pwa
  ├─ docs
  ├─ public
  ├─ .github
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  └─ src
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by FabianLars** [comment]
Just for reference, the last time we talked about it, this worked fine for me (but not for you iirc):
`yarn tauri build --target aarch64-apple-darwin -- -Z build-std`

**Comment by ozgunozerk** [comment]
Correct, and the exact error I'm getting when trying that is:
```
$ yarn tauri build --target aarch64-apple-darwin -- -Z build-std                                                                                          ─╯
yarn run v1.22.19
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ tauri build -Z build-std
error: Found argument '-Z' which wasn't expected, or isn't valid in this context

        If you tried to supply `-Z` as a value rather than a flag, use `-- -Z`

USAGE:
    yarn run tauri build [OPTIONS] [ARGS]...

For more information try --help
error Command failed with exit code 2.
```

**Comment by nazar-pc** [comment]
What about `yarn tauri build -- --target aarch64-apple-darwin -- -Z build-std`?

**Comment by ozgunozerk** [comment]
That worked!

**Comment by nazar-pc** [comment]
Works on Linux and macOS, fails on Windows with
```
error: Found argument '-Z' which wasn't expected, or isn't valid in this context
	If you tried to supply `-Z` as a value rather than a flag, use `-- -Z`
```

https://github.com/subspace/subspace-desktop/runs/7463242051?check_suite_focus=true
