### ISSUE TITLE
[bug] tauri app does not rendering properly

### ISSUE THREAD

**Issue by zw201913** [tauri-apps/tauri#4727]
### Describe the bug

I created a app via command line about `npm create tauri-app `, but after running it doesn't render properly.

The console reports an error：
<img width="800" alt="image" src="https://user-images.githubusercontent.com/16849315/180174237-14010186-1128-4276-a1a7-5539ad5cf6d2.png">

Below is resources page：
<img width="800" alt="image" src="https://user-images.githubusercontent.com/16849315/180176145-614a6891-d9ab-4e53-8289-63be85dea6fb.png">

### Reproduction

1.      npm create tauri-app
<img width="549" alt="image" src="https://user-images.githubusercontent.com/16849315/180133181-429ef6b5-3ea5-441c-b72c-fcae3825d0c1.png">
2.    Then I start the project through the command about `npm run tauri dev`, but it gives an error when rendering。
<img width="800" alt="image" src="https://user-images.githubusercontent.com/16849315/180133902-39f7bfbd-0294-4b1b-9d51-a199e1ce3e6e.png">

### Platform and versions

```shell
Environment
  › OS: Mac OS 10.13.6 X64
  › Node.js: 16.16.0
  › npm: 8.11.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.4
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.4,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://127.0.0.1:5173/

App directory structure
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .idea
  └─ src
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by amrbashir** [comment]
don't post the same issue across different repos. closing in favor of tauri-apps/create-tauri-app#87
