### ISSUE TITLE
[bug] It won't be radius frame when `decoration` sets `false` in Windows 11

### ISSUE THREAD

**Issue by 7086cmd** [tauri-apps/tauri#4733]
### Describe the bug

![image](https://user-images.githubusercontent.com/54303040/180338423-a4b147a1-9ab5-435a-84e6-3be85b7e0730.png)
This is the frame without `decorations`, and it have no animation, radius border, and shadow.
![image](https://user-images.githubusercontent.com/54303040/180338553-8f8264a2-291d-41fe-90d5-9d2cc5322399.png)
This is the frame that `decorations` sets to `true`, and it directly shows the frame, shadow, border, and radius.

> In **Electron**, when `frame` sets to `false`, it won't show decorations, but it will also show the radius and shadow.

### Reproduction

1. Simply create a blank project.
2. Add `decorations: false` to the config part of the window
3. run.

### Expected behavior

Provide a `titlebar` options, in order to hide titlebar, while use `decorations` to hide them all; Or let `decorations` just hide title bar, and create a options `transparent` to hide them all.

### Platform and versions

```shell
PS J:\zhihui\desktop> tauri info

Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 103.0.1264.62
  › MSVC: 
      - Visual Studio 2019
  › Node.js: 18.4.0
  › npm: 8.12.1
  › pnpm: 7.5.0
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.3 (outdated, latest: 1.0.4)
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.3,
  › tauri-build [RUST]: 1.0.3,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/config
  › framework: Vue.js

App directory structure
  ├─ .rsw
  ├─ .vscode
  ├─ cypress
  ├─ dist
  ├─ node_modules
  ├─ plugins
  ├─ public
  ├─ src
  ├─ src-rsw
  └─ src-tauri
```

**Comment by amrbashir** [comment]
That's expected, radius is part of the decorations and removing decorations will remove radius, border, shadows etc.
If you want rounded corners on Win11, use https://github.com/tauri-apps/window-shadows which will make your window has shadows on win <= 11 and rounded on Win11 while still removing the titlebar

**Comment by WuYunlong** [comment]
The same problem exists under Mac

**Comment by FabianLars** [comment]
@WuYunlong If you wanna keep the native window controls (the colored buttons), see this issue: <https://github.com/tauri-apps/tauri/issues/2663#issuecomment-1123208310>

For actually undecorated windows it's a little tricky. There was a [PR](https://togithub.com/tauri-apps/window-vibrancy/pull/26/files) to window-vibrancy which added this and there was someone on the discord i think, trying to make it a standalone crate, but it didn't work iirc, like it just crashed the app or something.

**Comment by sohaha** [comment]
Same needs.

**Comment by nianyi778** [comment]
The same goes for the mac.
