### ISSUE TITLE
FullScreen element.requestFullscreen() Not Working

### ISSUE THREAD

**Issue by dev-itzarun** [tauri-apps/tauri#4748]
Hai @lucasfernog , @nklayman 

Setting this option to true `fullscreen": true` in **tauri.conf.json**  open the app in fullscreen

`
            "windows": [
      {
        "fullscreen": true,
        "height": 600,
        "resizable": true,
        "title": "Test App",
        "width": 800
      }
    ]
`

But when if Fullscreen is requested from JavaScript the title bar not getting hidden

![image](https://user-images.githubusercontent.com/109509109/180623287-64c4d060-d4d7-4fb5-ac6f-8a6336d2b29d.png)

Give a solution For this

_Originally posted by @dev-itsarun in https://github.com/tauri-apps/tauri/issues/1139#issuecomment-1193190621_

**Comment by horochx** [comment]
I think you can solve the problem by listening to the DOM's `fullscreenchange` event and calling tauri's `setFullscreen` API when entering and exiting fullscreen. However, it should be a good idea to automatically implement the same `element.requestFullscreen()` behavior as the browser. @lucasfernog do you think this is reasonable? If so, I think I'll submit a PR to fix it~

**Comment by amrbashir** [comment]
tauri shouldn't behave strictly the same as a browser, and in this case, it should be up to users whether to call `setFullscreen` or not and when to call it.

**Comment by dev-itzarun** [comment]
@amrbashir , @horochx can you guys guide me where i can listen for `fullscreenchange` event and can you please share some code snippets using `tauri-api`.

**Comment by horochx** [comment]
> @amrbashir , @horochx can you guys guide me where i can listen for `fullscreenchange` event and can you please share some code snippets using `tauri-api`.

[Document: fullscreenchange event](https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreenchange_event)

```js
function fullscreenchanged(event) {
  // document.fullscreenElement will point to the element that
  // is in fullscreen mode if there is one. If there isn't one,
  // the value of the property is null.
  if (document.fullscreenElement) {
    console.log(
      `Element: ${document.fullscreenElement.id} entered fullscreen mode.`
    );
  } else {
    console.log("Leaving fullscreen mode.");
  }
}

document.addEventListener("fullscreenchange", fullscreenchanged);
// or
document.onfullscreenchange = fullscreenchanged;
```

**Comment by dev-itzarun** [comment]
@horochx @amrbashir 

Is it possible to set `setFullscreen` after listening for the `fullscreenchange` event on `main.rs` ?

Can some one help me with this 

I've read the [docs](https://tauri.app/v1/guides/features/events#backend), but my code isn't working.

**Comment by horochx** [comment]
> @horochx @amrbashir
> 
> Is it possible to set `setFullscreen` after listening for the `fullscreenchange` event on `main.rs` ?
> 
> Can some one help me with this
> 
> I've read the [docs](https://tauri.app/v1/guides/features/events#backend), but my code isn't working.

In your entry js file:

```js
import { appWindow } from "@tauri-apps/api/window";

document.addEventListener("fullscreenchange", () => {
  if (document.fullscreenElement) {
    appWindow.setFullscreen(true);
  } else {
    appWindow.setFullscreen(false);
  }
});
```

[docs to read](https://tauri.app/v1/api/js/window/#setfullscreen)

**Comment by dev-itzarun** [comment]
i know i can do it with `tauri-api` npm package

iam asking for the help with listners in main.rs
