### ISSUE TITLE
[bug] MSI and <app>.exe false positives on anti-virus apps

### ISSUE THREAD

**Issue by betamos** [tauri-apps/tauri#4749]
### Describe the bug

Here's an example submission from my app Payload:

https://www.virustotal.com/gui/file/269db7da1cd0d259c4eb20e0ac1eea3490c023debc7651ec85b595c5ec0b0036

There are several anti-virus vendors that likely share the same detection mechanism, that report Trojan.Heur.LShot.1 .

The .msi, main exe and my sidecar exe are all affected, but the worst and scariest warnings are in the .msi.

### Reproduction

Build a tauri app?
Submit to virustotal.
Watch several reports of trojans and scary things.

### Expected behavior

Ideally, no false positives.

### Platform and versions

```shell
Windows/ tauri 1.0.4 (custom fork)
```

### Additional context

- I have a wix customization that adds firewall rules, but I don't think this is the root cause.
- I also verified that I wasn't subject to a supply-chain attack on my build system, by building in a separate isolated environment - same result.
- Obviously reproduction is tricky, but I encourage every tauri dev to submit their installers/exes to virustotal in order to narrow down what could be triggering these issues.

**Comment by goenning** [comment]
I scanned my MSI built with Tauri 1.0.4 and it didn't find anything.

**Comment by JonasKruckenberg** [comment]
I too scanned my work app with virustotal (it uses p2p stuff even) but it didn't get flagged by any vendor on none of the OSes. Have you customized your windows installer?

**Comment by lucasfernog** [comment]
Can you try with a base app, without any firewall rules or sidecars?

**Comment by betamos** [comment]
Thank you for the data points, that's promising! I'll have to binary search removal of features (again, sigh) and hope that the detection algorithm is deterministic w.r.t. a signature in one of these features/binaries. All I can say at the moment is that code signing did not have an effect. Please leave this issue open, I'll try to get to it in the next week.

> Have you customized your windows installer?

Yes, I added two firewall rules for UDP & TCP - which is perhaps the most likely explanation. Also note I have a sidecar and a custom crate clipboard-files for pasting files directly into the app.

**Comment by JonasKruckenberg** [comment]
You can most likely exclude sidecars as a source of this, my app included an ipfs-like daemon as a sidecar (so if anything in the world could trigger a false positive it'd be that) but virustotal was fine with it.

I would guess the firewall rules are be the issue

**Comment by betamos** [comment]
Thanks Jonas for adding more data points!

It seems like my false positive report to BitDefender has worked. The exact same .msi [now passes all but one antivirus](https://www.virustotal.com/gui/url/40e78f2fd2d8ff1c2ee785f8e255ad79f4e7d690840f965f8d1b273da3704327/detection). I just filed a false positive report with "SecLookup", which is the last one remaining.

My sidecar still has [a false positive with  MaxSecure](https://www.virustotal.com/gui/file/1c3f5d597ceeb172c2d6154c062cb1c2ed8542b813d5283979d7277f2dda408f). "Trojan.Malware.300983.susgen" seems to be a common problem with Go binaries, [see this issue](https://github.com/lian/msfs2020-go/issues/14). I just submitted a false positive report with them as well.

As far as I'm concerned, you can close this issue, but it doesn't hurt to gather more data to narrow down what makes these detectors antsy. Thanks all.
