### ISSUE TITLE
[bug] Soft Prompts on launch

### ISSUE THREAD

**Issue by akshatjain777** [tauri-apps/tauri#4750]
### Describe the bug

I am soft prompts asking microphone permission whenever I open Tauri app on macOS
![Screenshot 2022-07-24 at 11 35 33 AM](https://user-images.githubusercontent.com/51501166/180634645-8804dac2-e4ba-4925-86d2-288911347aff.png)
.

Please check the attached image.

### Platform and versions

```shell
Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 16.13.2
  › npm: 8.9.0
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.25.1
  › rustc: 1.62.0
  › cargo: 1.62.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.4,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › framework: React

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ private
  ├─ .github
  ├─ src-tauri
  ├─ .git
  └─ src
```

**Comment by lucasfernog** [comment]
Can you share a minimal reproducible example?

**Comment by akshatjain777** [comment]
I am using a library which asks for microphone permission using navigator.mediaDevices.getUserMedia function, I think this is what causing  soft prompts to appear when app launches. 

You can reproduce the same error by adding the javascript code attached below.

```
navigator.mediaDevices.getUserMedia({
      audio: true,
});
```

**Comment by kamilernerd** [comment]
I had the same issue. The prompt opens up when navigation.mediaDevices.getUserMedia is called with constraints. When I added Info.plist file with following content to the src-tauri directory then I got prompted twice. Once with tauri's permission prompt and then second time with the os prompt requesting mic and camera permissions.

```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSCameraUsageDescription</key>
	<string>Request camera access</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>Request microphone access</string>
</dict>
</plist>
```
Now the second os prompt has disappeared and I can't seem to get it to show again which makes me confused.

**Comment by FabianLars** [comment]
@kamilernerd Are you using stable Tauri versions? Because we removed our custom permission prompts in later release-candidate versions. (you can check via `npm run tauri info`)

**Comment by kamilernerd** [comment]
> @kamilernerd Are you using stable Tauri versions? Because we removed our custom permission prompts in later release-candidate versions. (you can check via `npm run tauri info`)

The output is following.

```
$ tauri info

Environment
  › OS: Mac OS 12.3.1 X64
  › Node.js: 16.13.1
  › npm: 8.1.2
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-x86_64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › framework: React

App directory structure
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  └─ src
✨  Done in 8.79s.
```

## Update
Somehow I managed to break everything just by deleting the Info.plist file and starting the app, then adding it back and starting the app again. Now I don't get any prompts and the permission request gets disallowed automatically. This behaviour seems very inconsistent.

**Comment by morajabi** [comment]
@FabianLars I looked at the history and didn't find where the prompts were removed for microphone. If you are referring to this PR: #4302 it only removes it for the notification permissions.

**Comment by FabianLars** [comment]
> If you are referring to this PR: https://github.com/tauri-apps/tauri/pull/4302 it only removes it for the notification permissions.

At this point i don't even know what i'm referring to myself every time it's about macos :( But anyway, you're right, thanks! and sorry for the confusion i may have caused :v:

**Comment by morajabi** [comment]
Oh no worries! It's just the soft prompt that always appears is so annoying and practically doesn't work for a real world voice chat application. How can we disable it? Or point me to where I should change and I'll happily make a PR.

Normal behavior is to only show a native macOS permission dialog (requested upon using `getUserMedia`) and afterwards no additional dialog should appear, even on subsequent app launches.

However, currently every time you reload the app/or relaunch it, asks for microphone permissions using a custom Safari / or Tauri built dialog.

**Comment by FabianLars** [comment]
Thank you @github for timing me out all the time... The lost comment from 3 days ago mentioned that i found an api for this, but it's macos 12+ and ios 15+ and there seems to be no alternative for older versions.

https://developer.apple.com/documentation/webkit/wkuidelegate/3763087-webview
example impl: [react-native-webview#2257](https://togithub.com/react-native-webview/react-native-webview/pull/2257)

**Comment by lecepin** [comment]
What's next?

**Comment by FabianLars** [comment]
@lecepin Once we have the capacity, we'll review the wry PR. Depending on how the implementation ends up working, there won't be any changes necessary in Tauri so once it's part of a new wry release you should see it in Tauri shortly after.

**Comment by iceener** [comment]
Do you guys have any ideas? 

<img width="845" alt="Screenshot 2023-11-01 at 16 07 21" src="https://github.com/tauri-apps/tauri/assets/29215115/07cd4f9b-4e00-4f5d-b45f-d29442a5c740">

macOS Sonoma 14.1 (the same was on Ventura) 

my src-tauri/Plist.info:

```
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSCameraUsageDescription</key>
	<string>Request camera access</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>Request microphone access</string>
</dict>
</plist>
```
