### ISSUE TITLE
http interceptors

### ISSUE THREAD

**Issue by pansusu** [tauri-apps/tauri#4758]
### Describe the problem

 The http module in which can not support request interceptor and response interceptor
i want to sign parameters before fetching datas

### Describe the solution you'd like

i want the http module to support interceptors

**Comment by persiliao** [comment]
If you are trying to call http in your front-end code, maybe you can try axios, I wrote an axios tauri http adapter that can easily do what you need

[axios-tauri-api-adapter](https://github.com/persiliao/axios-tauri-api-adapter)

**Comment by KaKi87** [comment]
I created an [`axios-tauri-adapter`](https://git.kaki87.net/KaKi87/axios-tauri-adapter) module as well, covering all [`axios`](https://github.com/axios/axios) features, including [interceptors](https://github.com/axios/axios#interceptors).

**Comment by pansusu** [comment]
[axios-tauri-api-adapter](https://github.com/persiliao/axios-tauri-api-adapter)  solved my problem

> I created an [`axios-tauri-adapter`](https://git.kaki87.net/KaKi87/axios-tauri-adapter) module as well, covering all [`axios`](https://github.com/axios/axios) features, including [interceptors](https://github.com/axios/axios#interceptors).
