### ISSUE TITLE
[bug] When using Tauri plugin localhost in windows, you can't use Tauri fs to write files. Is this a Tauri plugin localhost compatibility problem

### ISSUE THREAD

**Issue by xiaowang-web** [tauri-apps/tauri#4759]
### Describe the bug

[](url)When using Tauri plugin localhost in windows, you can't use Tauri fs to write files. Is this a Tauri plugin localhost compatibility problem

### Reproduction

Step 1: use Tauri plugin localhost
Step 2：  const write = async (res) => {
        await writeTextFile('/Users/xiang.wang/Desktop/data/wyx.txt', ["123", "4444"], { dir: BaseDirectory.App });
    }
Step 3： "tauri": {
    "allowlist": {
      "all": true,
      "fs": {
        "scope": ["**"]
      }
    },
Step 4：cargo tauri build --debug

### Expected behavior

If you do not use Tauri plugin localhost, you can write files on Windows disk, and an error will be reported if you use it

### Platform and versions

```shell
one："@tauri-apps/api": "^1.0.2",
two：name = "tauri-plugin-localhost"，version = "0.1.0"
```

### Stack trace

```shell
Uncaught (in promise) TypeError: window.__TAURI_IPC__ is not a function
    at tauri-fa8f44bd.js:1:617
    at new Promise (<anonymous>)
    at tauri-fa8f44bd.js:1:433
    at tslib.es6-9bc0804d.js:1:2234
    at Object.next (tslib.es6-9bc0804d.js:1:1550)
    at tslib.es6-9bc0804d.js:1:1276
    at new Promise (<anonymous>)
    at i (tslib.es6-9bc0804d.js:1:1021)
    at s (tauri-fa8f44bd.js:1:364)
    at tauri-7cafdaf8.js:1:182
```

### Additional context

Uncaught (in promise) TypeError: window.__TAURI_IPC__ is not a function
    at tauri-fa8f44bd.js:1:617
    at new Promise (<anonymous>)
    at tauri-fa8f44bd.js:1:433
    at tslib.es6-9bc0804d.js:1:2234
    at Object.next (tslib.es6-9bc0804d.js:1:1550)
    at tslib.es6-9bc0804d.js:1:1276
    at new Promise (<anonymous>)
    at i (tslib.es6-9bc0804d.js:1:1021)
    at s (tauri-fa8f44bd.js:1:364)
    at tauri-7cafdaf8.js:1:182

**Comment by FabianLars** [comment]
Did you try combining it with https://github.com/tauri-apps/tauri-invoke-http already? The localhost plugin is only for serving files, and doesn't handle the IPC.
The issue itself makes sense (kinda) because we don't inject the necessary APIs into windows with external-ish URLs (includes localhost).

**Comment by wangyuxiangloveyou** [comment]
> Did you try combining it with https://github.com/tauri-apps/tauri-invoke-http already? The localhost plugin is only for serving files, and doesn't handle the IPC. The issue itself makes sense (kinda) because we don't inject the necessary APIs into windows with external-ish URLs (includes localhost).

tauri_ plugin_ Localhost and Tauri invoke HTTP are used together, but FS cannot write files, as shown in my configuration

![image](https://user-images.githubusercontent.com/22915319/181203504-26664732-747e-4227-af6a-5a4491017d74.png)
![image](https://user-images.githubusercontent.com/22915319/181202366-77633104-3061-4e1e-be8b-519c00d29e88.png)
![image](https://user-images.githubusercontent.com/22915319/181202527-5d5dd4f8-b11c-4ab6-93e0-c51935961f3f.png)

**Comment by wangyuxiangloveyou** [comment]
> Did you try combining it with https://github.com/tauri-apps/tauri-invoke-http already? The localhost plugin is only for serving files, and doesn't handle the IPC. The issue itself makes sense (kinda) because we don't inject the necessary APIs into windows with external-ish URLs (includes localhost).

tauri_ plugin_ Localhost and Tauri invoke HTTP are used together, but FS cannot write files, as shown in my configuration
![image](https://user-images.githubusercontent.com/22915319/181204133-7bdacc10-66b9-4aef-8c72-6ad669b019cd.png)
![image](https://user-images.githubusercontent.com/22915319/181204294-57466818-6b9f-49bf-9131-9272358db888.png)
![image](https://user-images.githubusercontent.com/22915319/181204435-d84b275d-ceb8-4f64-ab8d-be55e51957e3.png)

**Comment by wangyuxiangloveyou** [comment]
> Did you try combining it with https://github.com/tauri-apps/tauri-invoke-http already? The localhost plugin is only for serving files, and doesn't handle the IPC.
> The issue itself makes sense (kinda) because we don't inject the necessary APIs into windows with external-ish URLs (includes localhost).

When I use Tauri invoke HTTP and Tauri plugin localhost together, I still report an IPC problem and cannot call fs to write files in windows。The following figure shows whether the two plug-ins are used together. Is the configuration I wrote wrong?
![image](https://user-images.githubusercontent.com/22915319/181450743-28ddba82-04a0-4073-88a2-580b149c2f7b.png)
![image](https://user-images.githubusercontent.com/22915319/181450797-f77701ea-5fd9-4173-a3b9-0b3cade7b0ec.png)
![image](https://user-images.githubusercontent.com/22915319/181450864-03a3bdc1-492c-4c86-95ee-ddc1be5543f4.png)

**Comment by xiaowang-web** [comment]
> Did you try combining it with https://github.com/tauri-apps/tauri-invoke-http already? The localhost plugin is only for serving files, and doesn't handle the IPC. The issue itself makes sense (kinda) because we don't inject the necessary APIs into windows with external-ish URLs (includes localhost).

When I use Tauri invoke HTTP and Tauri plugin localhost together, I still report an IPC problem and cannot call fs to write files in windows。The following figure shows whether the two plug-ins are used together. Is the configuration I wrote wrong?
![image](https://user-images.githubusercontent.com/22915319/181456393-05b78681-616a-44dd-859c-ce173d34c1f7.png)
![image](https://user-images.githubusercontent.com/22915319/181451732-f63d3f56-b96f-48a4-8b80-3dd89a098f11.png)
![image](https://user-images.githubusercontent.com/22915319/181451811-d5751d3a-c2bd-452f-8421-b22d1d8b5102.png)
![image](https://user-images.githubusercontent.com/22915319/181452045-1cc0f7f3-3613-4a1a-bbf7-fc96fb85dcdc.png)

**Comment by lucasfernog** [comment]
I think there's a way around it if you change the config's distDir from `tauri::generate_context!()`'s config(). But I'm busy right now and can't implement it.

**Comment by xiaowang-web** [comment]
> I think there's a way around it if you change the config's distDir from `tauri::generate_context!()`'s config(). But I'm busy right now and can't implement it.

Is config's distdir the configuration item in the figure
![image](https://user-images.githubusercontent.com/22915319/181744314-425f87e3-bc6d-4ca5-9a4c-af74a1087cf0.png)

tauri::generate_ context! ()'s config() refers to what configuration item

**Comment by lucasfernog** [comment]
I just updated the example with a workaround for it. Check it out in the repo or the [commit](https://github.com/tauri-apps/tauri-plugin-localhost/commit/4126a4346b07f273b330e44bfe00af434d3f2cb2).
