### ISSUE TITLE
[feat] From path to file URL string 

### ISSUE THREAD

**Issue by yonathan06** [tauri-apps/tauri#4762]
### Describe the problem

I needed a simple rust function to be called for getting the file URL for a certain path
In Node.js I'm used to [url.pathToFileURL(path)](https://nodejs.org/dist/latest-v16.x/docs/api/url.html#urlpathtofileurlpath)
But this can not be called from the browser

### Describe the solution you'd like

I created a small rust function that is called through the `invoke` function

```rust
#[tauri::command]
fn path_to_file_url(file_path: &str) -> Result<String, &str> {
    let url = Url::from_file_path(file_path).unwrap();
    Ok(url.to_string())
}
```

and then
```javascript
await invoke<string>('plugin:my_plugin|path_to_file_url', { filePath });
```

### Alternatives considered

Running Node.js in the backend, and calling the Node.js function directly. But until having it built in Tauri, it needs a sidecar which was an overkill for this simple use case

**Comment by amrbashir** [comment]
Seems like you already found a solution, does it not work? or do you want it to be included in tauri core?

**Comment by yonathan06** [comment]
It works, I suggest adding it to tauri core (api). I can open a PR for it

**Comment by amrbashir** [comment]
I am bit hesitant to include in tauri API tbh but I will add it to the list here https://github.com/tauri-apps/tauri/issues/2233 for now
