### ISSUE TITLE
Big integer literals are not available in the configured target environment

### ISSUE THREAD

**Issue by Teeoo** [tauri-apps/tauri#4766]
### Discussed in https://github.com/tauri-apps/tauri/discussions/4765

<div type='discussions-op-text'>

<sup>Originally posted by **Teeoo** July 26, 2022</sup>
```js
{
      detail: undefined,
      id: '',
      location: {
        column: 24,
        file: 'node_modules/oicq/lib/message/message.js',
        length: 3,
        line: 28,
        lineText: '    return 16777216n << 32n | BigInt(rand);',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)'    
    }
```
</div>

**Comment by JonasKruckenberg** [comment]
Without any further info on your system or setup this error is pretty meaningless. Please fill out the [bug report template](https://github.com/tauri-apps/tauri/blob/dev/.github/ISSUE_TEMPLATE/bug_report.yml) we have for these situations.

I will also close the original discussion, please don't spam us with these things next time.

**Comment by FabianLars** [comment]
While i never saw that type of output, BigInt support was added in Safari v14, while you target v13. Raising this requirement would mean that your app could only run on macOS >= v11
