### ISSUE TITLE
How to check if a directory exists

### ISSUE THREAD

**Issue by dydhyhwu** [tauri-apps/tauri#4767]
When I use readDir, it prompts that the directory does not exist. 
`C:\Users\dev\AppData\Roaming\com.tauri.dev\: 系统找不到指定的路径。 (os error 3)`

How should I detect whether the directory exists?

**Comment by dydhyhwu** [comment]
I didn't find the relevant api in the `@tauri-apps/api` package

My solution was to add a command：
```rust
use std::path::Path;

#[tauri::command]
pub fn dir_existed(path: String) -> bool {
    return Path::new(&path).exists();
}
```

**Comment by FabianLars** [comment]
You could simplify it to this
```rs
use std::path::PathBuf;

#[command]
fn exists(path: PathBuf) -> bool {
  path.exists()
}
```

And yes this will make it into our api
