### ISSUE TITLE
[feat] systemTray custom title

### ISSUE THREAD

**Issue by RustLoverTheCoder** [tauri-apps/tauri#4768]
### Describe the problem

![图片](https://user-images.githubusercontent.com/71162666/180945094-3c9cf5e2-132e-4b20-aca4-aa2fe680a880.png)
systemTray custom title

### Describe the solution you'd like
let tray = SystemTray::new();
tray.set_title("123")

**Comment by amrbashir** [comment]
do you mean tooltip? the text that appears when hovering the icon?

**Comment by RustLoverTheCoder** [comment]
> do you mean tooltip? the text that appears when hovering the icon?

![image](https://user-images.githubusercontent.com/71162666/181037531-680dbcfd-0358-43cf-8657-ddd1dab6e87c.png)

**Comment by RustLoverTheCoder** [comment]
> do you mean tooltip? the text that appears when hovering the icon?

I'm working on a chat app and want to add unreads next to the icon

**Comment by amrbashir** [comment]
upstream issue https://github.com/tauri-apps/tao/issues/65

**Comment by amrbashir** [comment]
closing as dupicate of https://github.com/tauri-apps/tauri/issues/3322
