### ISSUE TITLE
[docs] Following MS Windows Setup tutorial leaves user without functioning NPM

### ISSUE THREAD

**Issue by BenoitRanque** [tauri-apps/tauri#478]
I've been following the MS Windows setup step by step, and ran into this issue.
I was not using `nvm` before
Apparently nvm installs node and npm in `C:/Program Files/nodejs`
Running powershell as admin, npm is available, but if not in and administrative shell, using npm will cause errors like this:

```
PS C:\Users\BENOIT\Dev\rust\tauri-test> npm -v
internal/modules/cjs/loader.js:984
  throw err;
  ^
Error: Cannot find module 'C:\Users\BENOIT\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)
    at Function.Module._load (internal/modules/cjs/loader.js:863:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

For some reason it looks for npm-cli in `AppData`, `instead of C:/Program Files/nodejs`

This can easily be solved by running the following command:
```
yarn global add npm
```
This has little to nothing to do with tauri, but I wanted to document it here in case new users face this issue in the future.

**Comment by nothingismagick** [comment]
@BenoitRanque - would you consider please adding this info to the wiki?

**Comment by BenoitRanque** [comment]
[Done!](https://github.com/tauri-apps/tauri/wiki/04.-MS-Windows-Setup/1a78f182be4beae7afb70c8e2e6056f2c414e4fd)
Closing issue
