### ISSUE TITLE
[bug] sidecar: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by trevorparscal** [tauri-apps/tauri#4780]
### Describe the bug

Appears to be similar to issue [#3612](https://github.com/tauri-apps/tauri/issues/3612).

Works in build, but not in dev.

Moving app-* (app-aarch64-apple-darwin in this case) to the src-tauri directory and changing "bin/app" to "app" did not work.

### Reproduction

1. Add a sidecar app

Relevant sections of my tauri.conf.json
```json
{
    "tauri": {
        "allowlist": {
            "shell": {
                "sidecar": true,
                "scope": [
                    {
                        "name": "bin/app",
                        "sidecar": true
                    }
                ]
            },
            ...
        },
        "bundle": {
            "externalBin": [
                "bin/app"
            ],
            ...
        }
        ...
    }
}
```

And of the JavaScript...
```javascript
const command = Command.sidecar( 'bin/app' );
console.log( await command.execute() );
```

2. Use tauri dev
3. See "No such file or directory (os error 2)" error in console when running command
4. See that it works with tauri build

### Expected behavior

Dev and build should behave the same.

### Platform and versions

macOS 12.4 (21F79), M1 chip

tauri = { version = "1.0.5", features = ["api-all"] }

tauri-build = { version = "1.0.4", features = [] }

### Additional context

The example sidecar app only has one line, logging a string to the console.

**Comment by trevorparscal** [comment]
I solved this by changing the name of the sidecar to something other than app, something I discovered as a possible fix by finding [3663](https://github.com/tauri-apps/tauri/issues/3663) was resolved this way as well.

However, even though the documentation uses an example of "my_sidecar", the [example](https://github.com/tauri-apps/tauri/tree/dev/examples/sidecar) uses "app", which is how I found my way down this path.

Maybe there could be some sort of error message forbidding this, or some fix to ensure tauri isn't confused by it?

**Comment by trevorparscal** [comment]
Perhaps I should leave this open, assuming this is a bug in tauri.

**Comment by FabianLars** [comment]
i thought that this is a known _limitation_, in which case we'd need to change the example, but maybe it indeed is just a bug 🤔

**Comment by lucasfernog** [comment]
Happens because the CLI renames the `app` executable (from `Cargo.toml` to the product name defined in the config file), so you lose the sidecar binary in that process. I'll add a validation for it.

**Comment by HerrHansen** [comment]
> i thought that this is a known limitation, in which case we'd need to change the example, but maybe it indeed is just a bug 🤔

+1 For changing the example. Spent hours until I found my way to this thread 🙃.
