### ISSUE TITLE
[feat] Allow custom names for commands

### ISSUE THREAD

**Issue by d3rpp** [tauri-apps/tauri#4782]
### Describe the problem

When trying to create a project that has quite a few commands, it is nice to be able to make the code more maintainable by including module names in the names of the commands.

### Describe the solution you'd like

for example, if I had a set of commands for making a CRUD operation for MPRIS, on the JS side, it'd be nice to be able to say `invoke("mpris::push", {...song_data})`

### Alternatives considered

It is not a breaking feature change, though, more of a QoL feature since I could name the rust functions with `mpris_push`, for example relating to the idea above.

**Comment by FabianLars** [comment]
If this: `invoke("mpris::push", {...song_data})` is your goal, you can use plugins: https://tauri.app/v1/guides/features/plugin

**Comment by vladfaust** [comment]
Due to increasing complexity of my project, I'd like to give custom names to generated commands to override the annotated function's name, for example:

```rs
// In commands/gpt/commit.rs
#[tauri::command(name = "gpt_commit")]
pub async fn commit(
```

Is it possible now?

**Comment by anuradhawick** [comment]
@vladfaust were you able to achieve this?
