### ISSUE TITLE
[feat] Tauri on Embedded Linux + WPE WebKit?

### ISSUE THREAD

**Issue by huming2207** [tauri-apps/tauri#4784]
### Describe the problem

I'm trying to build a full-screen display app for a kiosk machine in our factory for internal production testing. I'm thinking is it possible to get Tauri working with [WPE WebKit](https://wpewebkit.org/) and render stuff to Linux DRM directly? This is quite useful as I can re-use some native Rust bindings I've implemented earlier, while I also don't need to rely on GTK and window managers so that the overhead on RAM and storage.

### Describe the solution you'd like

Not sure... Maybe I need to implement the IPC stuff specifically for WPE: https://github.com/tauri-apps/tao/tree/dev/src/platform_impl/linux

Also, I would like to know is there any alternative way to modify the current code and get it working without GTK and X11/Wayland?

### Alternatives considered

Another similar thing is MiniGBM for Chromium, but I'd prefer not to use Chromium for low-RAM platforms.

**Comment by lucasfernog** [comment]
Unfortunately this is not something we plan on implementing, it would require a massive overhaul for a feature that most of the community won't use.

You could try implementing it directly in the [wry repo](https://github.com/tauri-apps/wry) or if you want to use Tauri, you'd need to implement a custom [tauri Runtime](https://docs.rs/tauri-runtime/latest/tauri_runtime/trait.Runtime.html).

**Comment by goggle555** [comment]
If Tauri can incorporate Servo in the future, you may be able to target embedded Linux.
[This month in Servo: CSS filters, testing changes, Tauri, and more!](https://servo.org/blog/2023/10/26/css-filters-testing-tauri/)

**Comment by theoparis** [comment]
> If Tauri can incorporate Servo in the future, you may be able to target embedded Linux. [This month in Servo: CSS filters, testing changes, Tauri, and more!](https://servo.org/blog/2023/10/26/css-filters-testing-tauri/)

Unfortunately Servo still requires X11 so I don't think it'd work just yet.

**Comment by huming2207** [comment]
> Unfortunately Servo still requires X11 so I don't think it'd work just yet.

Indeed, I think [WPE](https://github.com/WebPlatformForEmbedded/WPEWebKit) may be a good option. But then in that case there's probably no much benefit to port a Tauri runtime on WPE because there's no window/system tray/clipboard. I'd rather just run my frontend app on WPE and connect a local backend server for low-level stuff.
