### ISSUE TITLE
[feat] set window theme color

### ISSUE THREAD

**Issue by RustLoverTheCoder** [tauri-apps/tauri#4787]
### Describe the problem

How to customize the theme color of window

### Describe the solution you'd like

theme:[
  mytheme:{
    xx:"#121212"
  }
],
windows:[
  {
    theme:'mytheme'
  }
]

**Comment by amrbashir** [comment]
what do you mean by setting the window theme color? on what OS? do you know of another project that provides a similar functionality?

**Comment by RustLoverTheCoder** [comment]
I want to set the color of titlebar in dark mode

**Comment by amrbashir** [comment]
This is not possible. You need to turn off decorations and make a custom titlebar.
