### ISSUE TITLE
[bug] Build error `tauri-macros`

### ISSUE THREAD

**Issue by xiaomin1123** [tauri-apps/tauri#4794]
### Describe the bug

In command "Cargo tauri dev", it failed at compiling tauri-macros
error: export ordinal too large: 68600
          collect2.exe: error: ld returned 1 exit status

error: could not compile `tauri-macros` due to previous error

After changed the "Cargo.toml" with 
[profile.dev.build-override]
opt-level = 2

It can solve this issue in "dev". But it will happen again in releasing with command "Cargo tauri build"

### Platform and versions

Environment
  › OS: Windows 10.0.19042 X64
  › Webview2: 103.0.1264.71
  › MSVC: 
  › Node.js: Not installed!
  › npm: Not installed!
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: Not installed!
  › rustc: 1.62.0
  › cargo: 1.62.0
  › Rust toolchain: 

I don't know why here doesn't show the rust toolchain. The toolchain I used is x86-64-windows-gnu. The GCC is installed through msys2.

**Comment by xiaomin1123** [comment]
version of tauri

  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

**Comment by FabianLars** [comment]
we officially only support the msvc toolchain (you probably will run into other errors with gnu after this one), so if it's possible for you to use that, i'd suggest using that instead. It's generally considered the better one in the rust world anyway 🤷

Apart from this, the _whole_ output of tauri info (as requested) may be helpful to double check your config. A common issue is a misconfigured devPath/distDir which can make it copy too many unwanted files into the binary, but normally the error for that would look different.
Other than this i don't think we can help you without a reproduction example, because you're the first one reporting this issue.

> I don't know why here doesn't show the rust toolchain

Because it wasn't installed via rustup which we use to identify it iirc.

**Comment by xiaomin1123** [comment]
> we officially only support the msvc toolchain (you probably will run into other errors with gnu after this one), so if it's possible for you to use that, i'd suggest using that instead. It's generally considered the better one in the rust world anyway 🤷
> 
> Apart from this, the _whole_ output of tauri info (as requested) may be helpful to double check your config. A common issue is a misconfigured devPath/distDir which can make it copy too many unwanted files into the binary, but normally the error for that would look different. Other than this i don't think we can help you without a reproduction example, because you're the first one reporting this issue.
> 
> > I don't know why here doesn't show the rust toolchain
> 
> Because it wasn't installed via rustup which we use to identify it iirc.

Hello FabianLars,

Thank you for the reply. It can be reproduced by below steps,

- Install msys2
- Install GCC via pacman, pacman -S --needed base-devel mingw-w64-x86_64-toolchain
- Install rust via pacman, pacman -S mingw-w64-x86_64-rust
Be careful with the Path, if rustc works correctly, then,
- In a IDE, like vs code, run "cargo install tauri-cli"
- if successfully, run a simple project
=> cargo tauri init
=>cargo tauri dev
Here you'll find the compiler failed in compiling tauri-macros, due to the link table too long, over 2*16 -1
Change the optimatization level in cargo.toml
 [profile.dev.build-override]
opt-level = 2
=> run cargo build dev again
Then it can compile successfully and pop up the widget.  But if continue to build it by "cargo tauri build", it will fail again with the same link issue.

--------------

I hope this issue can be solved for GCC toolchain. 😊 I don't have an access to MSVC. 

Regards,
Xiaomin

**Comment by FabianLars** [comment]
> Install rust via pacman, pacman -S mingw-w64-x86_64-rust

Can you try installing rust via rustup instead? Because i can't reproduce your issue right now with that (= it compiles fine for me with the gnu toolchain installed via rustup).
I can try installing rust via pacman later today, to see if i can repro it with that.

**Comment by FabianLars** [comment]
Someone else reported the issue in #4798 too, but it looks like they use the gnu toolchain installed via rustup. There goes my theory then 😢 
Still no idea how to reproduce this on my end (i did everything as described).

**Comment by xiaomin1123** [comment]
I used a new enviroment and reproduced it with rustup toolchain. it failed at compiling tauris-macros also
` error: export ordinal too large: 66355
          collect2.exe: error: ld returned 1 exit status


error: could not compile `tauri-macros` due to previous error`

Here's the enviroment
`Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 103.0.1264.71
  › MSVC: 
  › Node.js: Not installed!
  › npm: Not installed!
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-x86_64-pc-windows-gnu 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,`

It looks like to be a comman issue I think. @FabianLars Could you please show me your enviroment when you running it with gnu toolchain?

**Comment by FabianLars** [comment]
I just tested it on a completely different computer, and here's the env from that one
```
Environment
  › OS: Windows 10.0.19043 X64
  › Webview2: 103.0.1264.77
  › MSVC:
  › Node.js: 16.16.0
  › npm: 8.11.0
  › pnpm: 7.7.1
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-x86_64-pc-windows-gnu

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: ../dist

App directory structure
  ├─ dist
  ├─ node_modules
  └─ src-tauri
```

**Comment by xiaomin1123** [comment]
emm, I have no idea. What's the gcc version then? Here's my,
gcc (Rev3, Built by MSYS2 project) 12.1.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by FabianLars** [comment]
I have the same version. I just installed it on that system so everything should be at the latest version.

**Comment by soda92** [comment]
# One workaround
 ## Go to this file: 
![image](https://github.com/user-attachments/assets/84c7a271-8fbb-470e-8910-16489938c5c4)
## Go to build->try_build:
![image](https://github.com/user-attachments/assets/912837f0-149a-4c0b-8600-6d43c9bc63f5)
## add this line:
![image](https://github.com/user-attachments/assets/6c1f34aa-92f5-4d95-9d66-9723ff4e29a2)
```
println!("cargo::rustc-link-arg=-Wl,--exclude-libs=ALL");
```
## Then run:
```
cargo clean
cargo build
```

**Comment by soda92** [comment]
The explanation: https://stackoverflow.com/a/77212421/12291425
Solution: https://stackoverflow.com/a/77223190/12291425

**Comment by soda92** [comment]
BTW this is how I get rust-analyzer work with MSYS2: https://gist.github.com/soda92/b7c394b0db0dadf33a433858d2881728

**Comment by xiaomin1123** [comment]
@soda92 , thank you for the kindly support.
This issue was solved in tauri 1.x (I don't know the exactly version) but happened again with tauri 2.0. I followed your suggestions and built tauri2 successfully.

BTW, do you know how to link libraries when use lld as linker? If here we use Clang lld in cargo profile,
[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "linker=clang", "-C", "link-arg=-fuse-ld=lld"]

Tauri2 will fail in compiling with error as below,
lld: error: unknown argument: --exclude-libs=ALL

**Comment by soda92** [comment]
@xiaomin1123 Which file did you add this to? There are many `cargo.toml` in the `tauri` repo.

For created applications via `npm` 
![create tauri app](https://github.com/user-attachments/assets/e3f85860-a923-4b7e-b36c-b2902021711b),
I think the building steps of it is mainly controlled by `build.rs`, so configured flags in `cargo.toml` is ignored.

**Comment by xiaomin1123** [comment]
I mean the file in CARGO_HOME, it's installed by rustup. The path is .cargo/config.toml. Nevertheless, tauri2 can work with original rustc link :).

**Comment by soda92** [comment]
Then it will be fine right. This is just a convenience for people who don't want to install Visual Studio. For release we should still use VS since it is what officially supported

**Comment by Magniveo** [comment]
Still not work, mingw64(14.2) set clang not helped too.

**Comment by moc67331** [comment]
> Still doesn't work. Setting clang in mingw64 (14.2) didn’t help either.

Same here.  
I tried adding the `--exclude-all-symbols` flag to the linker arguments in `build.rs`, and that resolved the issue in the same environment.

```rs
println!("cargo::rustc-link-arg=-Wl,--exclude-libs=ALL,--exclude-all-symbols");
```
I think this option makes the symbol table behavior closer to how link.exe works on MSVC. (Reference: https://reviews.llvm.org/D58380?id=187323)
But I might be wrong about that.
