### ISSUE TITLE
[bug] Unable to install Tauri application（msi） to windows7 OS.

### ISSUE THREAD

**Issue by geeklibin** [tauri-apps/tauri#4797]
### Describe the bug

![lQLPJxaFlB3kobfNATvNAcawESB8ThvHgzkC2-vkK0AGAA_454_315](https://user-images.githubusercontent.com/9034445/181865697-a790eff8-8787-4c7a-b462-0d5763d4aff8.png)
我在使用win7操作系统时，无法安装tauri应用（msi），我查看了 windows error events，似乎是在下载webview2时出现的错误。
![image](https://user-images.githubusercontent.com/9034445/181865861-29b9ac54-fcd5-4556-a4d0-bfc4ec5540c7.png)
我看了一下里面的command，powershell3.x以上才会支持Invoke-WebRequest command.

现在我只能先去手动去安装webview2，再去安装tauri应用才能成功。

希望可以解决这个BUG。

### Platform and versions

Develop Environment:
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 103.0.1264.71
  › MSVC:
      - Visual Studio ���ɹ��� 2019
  › Node.js: 14.18.0
  › npm: 6.14.15
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

**Comment by FabianLars** [comment]
This is the webview2 installation failing. Please choose a different webview2 install mode, for windows 7 support, see here: https://tauri.app/v1/guides/building/windows#webview2-installation-options. If the machine has an active internet connection i'd suggest `embeddedBoostrapper`

**Comment by ekaterina-o** [comment]
I'm not a programmer. What should I do to make this work?
