### ISSUE TITLE
GitHub Actions for Builds

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#48]
**Is your feature request related to a problem? Please describe.**
We need some build pipelines.

**Describe the solution you'd like**
Have a discussion about using github actions

**Comment by jbolda** [comment]
I am familiar with Github Actions, but would need some guidance on the build process (and expectations there). I expect there would be two main steps for each platform, a test and then a build, with a future third+ step of publishing the binaries and doing releases.

**Comment by nothingismagick** [comment]
I think there are two needs:
1. A need for us to validate the code itself with automated testing
2. A need for endusers to build their apps

**Comment by nothingismagick** [comment]
Along the lines of (2) I've also been thinking about integration with sentry because that is such a helpful little gremlin.

**Comment by jbolda** [comment]
I have opened a PR, but many of the Rust builds are failing. All it currently does it run through and build anything with a cargo.toml.

**Comment by nothingismagick** [comment]
I’m going to close this because we’re moving forward quite well.
