### ISSUE TITLE
[bug] windows package not allow http?

### ISSUE THREAD

**Issue by UvDream** [tauri-apps/tauri#4824]
### Describe the bug

After the application is packaged, it is found that apis that do not allow HTTP requests are not allowed. Why? I won't configure https for the background when I make a desktop application, but the mac side is fine. This should be given a configuration, otherwise it is too unreasonable.

### Platform and versions

Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 16.13.0
  › npm: 8.15.0
  › pnpm: 6.32.4
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.60.0-nightly
  › cargo: 1.60.0-nightly
  › Rust toolchain: nightly-aarch64-apple-darwin

Packages
       Error only one package mangager should be used, but found npm and pnpm
please remove unused package manager lock files

**Comment by lucasfernog** [comment]
To allow insecure connections in a bundled macOS application you need to configure the [exceptionDomain](NSExceptionDomains), which adds a [NSExceptionDomain](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsexceptiondomains) with `NSExceptionAllowsInsecureHTTPLoads` set to true. Example configuration:

```json
{
  "tauri": {
    "bundle": {
      "macOS": {
        "frameworks": [],
        "exceptionDomain": "api.myproject.com"
      }
    }
}
```

**Comment by UvDream** [comment]
> 

macos is ok,window can not run

**Comment by orangelckc** [comment]
> To allow insecure connections in a bundled macOS application you need to configure the [exceptionDomain](NSExceptionDomains), which adds a [NSExceptionDomain](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsexceptiondomains) with `NSExceptionAllowsInsecureHTTPLoads` set to true. Example configuration:
> 
> ```json
> {
>   "tauri": {
>     "bundle": {
>       "macOS": {
>         "frameworks": [],
>         "exceptionDomain": "api.myproject.com"
>       }
>     }
> }
> ```

@lucasfernog can you give an example how to set multi domains for `exceptionDomain `, I have more than one third-patry apis with  `http` protocol

**Comment by lucasfernog** [comment]
@orangelckc theres no way to do that yet, either file an issue or configure that via an Info.plist file in the src-tauri folder.

**Comment by yuanming-cienet** [comment]
Have you fixed this issue? Encounter the same problem.
