### ISSUE TITLE
How can I monitor the operation completed by startDragging and dragging over?

### ISSUE THREAD

**Issue by dydhyhwu** [tauri-apps/tauri#4825]
How can I monitor the operation completed by startDragging and dragging over?
I want to do something after dragging is over

**Comment by lucasfernog** [comment]
We don't have that yet :(

**Comment by amrbashir** [comment]
if you mean the window dragging, then you should listen to the move event

**Comment by dydhyhwu** [comment]
> if you mean the window dragging, then you should listen to the move event

I want to do something when the window drag ends, something like HTML's mouseup event

**Comment by lucasfernog** [comment]
You could debounce the [move event listener](https://tauri.app/v1/api/js/classes/window.WebviewWindow#onmoved) to know when the user stops moving it.

**Comment by dydhyhwu** [comment]
> You could debounce the [move event listener](https://tauri.app/v1/api/js/classes/window.WebviewWindow#onmoved) to know when the user stops moving it.

It's a great idea!!! I'll try, thanks.

**Comment by dydhyhwu** [comment]
Found a scene, what should I do if I keep dragging but not moving?
My solution is to add the detection of whether the left mouse button is pressed to determine whether it is in a dragging state, but I don't know if there is such an API

**Comment by amrbashir** [comment]
The OS doesn't give us enough information to know when the window dragging ends. As we suggested earlier, you should listen to the move event and debounce it.

**Comment by x93008** [comment]
I have a window that needs to maintain a fixed y-axis position. My initial approach was to listen for mouse moves in the frontend and call setPosition, but it proved very unresponsive. So I started window movement using startDragging when the mouse button was pressed, then adjusted the position after mouseup—but the mouseup event gets swallowed. Is the reason you're unwilling to add this feature that you consider this scenario too rare?

**Comment by FabianLars** [comment]
> Is the reason you're unwilling to add this feature that you consider this scenario too rare?

Please re-read Amr's last comment. It's not like we're unwilling, there's just no reasonable way to implement this. Also see https://github.com/tauri-apps/tauri/pull/14503 and https://github.com/orgs/tauri-apps/discussions/14446
