### ISSUE TITLE
How can I get access to the system's current active window and application?

### ISSUE THREAD

**Issue by omerdn1** [tauri-apps/tauri#4827]
Hello!
Is there a way currently to be able to monitor the current active application in the OS?
For example if I'm focused on chrome I want my tauri app to be able to pick that up.

Electron has an API that's able to give that information for programs that have a GUI window, called: [desktopCapturer](https://www.electronjs.org/docs/latest/api/desktop-capturer)

**Comment by lucasfernog** [comment]
There isn't a way to do that yet. Maybe you can find a Rust crate that exposes that?

**Comment by omerdn1** [comment]
For anyone wondering - I've been using https://github.com/dimusic/active-win-pos-rs to get information of the active window.

Would be cool to maybe see tauri incorporate it in some way in the future
