### ISSUE TITLE
[bug] initialization_script fires more than once

### ISSUE THREAD

**Issue by MrAmericanMike** [tauri-apps/tauri#4831]
### Describe the bug

Launching a 2nd window to open an external site from the "backend" side while injecting a script on it with initialization_script result in "at random" the script running 2 or 3 times on the page.

### Reproduction

Client side I have a function that invokes the command to open a new window.

```js
function doOpen() {
	invoke("open_gg");
}
```

That triggers:

```rust
#[tauri::command]
async fn open_gg(app: tauri::AppHandle) {
  println!("Open Google!");
  let common = include_str!("./common.js");
  tauri::WindowBuilder::new(
    &app,
    "exGoggle",
    tauri::WindowUrl::External("https://google.com/".parse().unwrap())
  )
  .title("Google")
  .initialization_script(common)
  .build()
  .unwrap();
}
```

All that works ok, but when clicking "Inspect" on the newly created window the script sometimes runs twice.

The injected script is:

```js
document.addEventListener("DOMContentLoaded", main);

let RUN = true;

async function main() {
	if (!RUN) { return; }
	console.log("HELLO Google");
	console.log(window.name);
	console.log(window);
	window.KOALA = {};
	RUN = false;
}
```

One thing I noticed is that sometimes on the 2nd time it runs the "Window" element has it's property "name" changes from an empty string to "app" whatever that could mean.

![tauri](https://user-images.githubusercontent.com/8037559/182396873-9a013819-1994-4d34-83c3-9251a7aa5c38.JPG)

### Expected behavior

Script should trigger only once.

### Platform and versions

Environment
  › OS: Windows 6.1.7601 X64
  › Webview2: 100.0.1185.39
  › MSVC:
      - Visual Studio Build Tools 2022
  › Node.js: 16.15.0
  › npm: 8.12.2
  › pnpm: 7.5.2
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.62.0
  › cargo: 1.62.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.4,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../public
  › devPath: http://localhost:3000/
  › framework: Svelte

App directory structure
  ├─ .vscode
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri

**Comment by lucasfernog** [comment]
You'll need to check if `window.location.href` is actually `https://www.google.com/` since in this case the script is also injected to `https://ogs.google.com/widget/callout?prid=19015398&pgid=19011583&puid=e6f105c653347d7a&cce=1&dc=1&origin=https%3A%2F%2Fwww.google.com&cn=callout&pid=1&spid=538&hl=pt-BR` (this is an implementation on [Webview2 side](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.1264.42#addscripttoexecuteondocumentcreated) we can't control it :( ) 

I'll update the documentation.

**Comment by MrAmericanMike** [comment]
Adding extra information. When testing on another website that more consistently results in the log showing 3 times, I noticed I end up with:

window.name > An empty string
window[0].name > "__tcfapiLocator"
window[1].name > "__uspapiLocator"

This happens on https://www.geoguessr.com Hopefully this helps investigate what's going on.

PS: A temporal solution seams to be `if (window.name !== "") { return; }`

Hacky but does the trick apparently.

**Comment by MrAmericanMike** [comment]
> You'll need to check if `window.location.href` is actually `https://www.google.com/` since in this case the script is also injected to `https://ogs.google.com/widget/callout?prid=19015398&pgid=19011583&puid=e6f105c653347d7a&cce=1&dc=1&origin=https%3A%2F%2Fwww.google.com&cn=callout&pid=1&spid=538&hl=pt-BR` (this is an implementation on [Webview2 side](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.1264.42#addscripttoexecuteondocumentcreated) we can't control it :( )
> 
> I'll update the documentation.

Thanks, will do that. Yes, on the other example I mention window.location.href results in "about:blank" and that also triggers the script.

Thanks for the feedback.
