### ISSUE TITLE
[bug] cant use `window.__TAURI__` with remote url

### ISSUE THREAD

**Issue by amaury-tobias** [tauri-apps/tauri#4837]
### Describe the bug

I'm trying to use `window.__TAURI__.event` to communicate events to tauri backend on an application wrapper for remote url.
This works in dev mode (`cargo tauri dev`) but no on build (`cargo tauri build --debug`) 

![image](https://user-images.githubusercontent.com/37311888/182465084-426a5cfd-e928-4d87-b943-e152d62f87e3.png)

![image](https://user-images.githubusercontent.com/37311888/182464627-38fec94f-9705-4eeb-84e8-f6b81761bf0f.png)

### Reproduction

On `tauri.config.json`
```json
 "build": {
    "beforeBuildCommand": "",
    "beforeDevCommand": "",
    "devPath": "https://www.google.com",
    "distDir": "../dist",
    "withGlobalTauri": true
  },
...
"windows": [
      {
        "url": "https://www.google.com",
        "width": 800,
        "height": 600,
        "resizable": true,
      }
    ]
```
build application on debug mode  `cargo tauri build --debug`, open devtools > Console, try to access to `window.__TAURI__`

### Expected behavior

__TAURI__ can be accessed with remote url

### Platform and versions

Environment
  › OS: Ubuntu 22.04 X64
  › Node.js: 16.16.0
  › npm: 8.11.0
  › pnpm: 7.8.0
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: https://www.google.com/
package.json not found

App directory structure
  ├─ dist
  ├─ .github
  ├─ src-tauri
  └─ .git

**Comment by lucasfernog** [comment]
This is by design, we do not inject our APIs on external URLs by default. You can get around that by setting `distDir` to the remote URL if you don't have local assets, or use a workaround like [this](https://github.com/tauri-apps/tauri-plugin-localhost/commit/4126a4346b07f273b330e44bfe00af434d3f2cb2#diff-07aba1df28891af8108090f8fb0b27dd253b2601454d76e14c00e15307f0e879) to change it at runtime - though in this case only one external URL will be able to access the tauri API.

**Comment by lucasfernog** [comment]
Though for the google URL you need to use `https://www.google.com` since it gets redirected to that URL before we check the origin - @FabianLars you're super weird for finding that out.
