### ISSUE TITLE
[bug] App doesn't show, and throws connection refused to tauri.localhost

### ISSUE THREAD

**Issue by GamingInfinite** [tauri-apps/tauri#4838]
### Describe the bug

I'm using sveltekit to create the app, and the dev side works great.  And it builds just fine, no errors.  However when I run the built executable, its white for a bit, then shows a screen saying that tauri.localhost was refused.

### Reproduction

1. clone https://github.com/GamingInfinite/TableTalk
2. yarn tauri init
3. yarn tauri build
4. build works fine
5. the .exe runs, but doesn't show the website, and refuses tauri.localhost

### Expected behavior

I want it to actually show the webapp.

### Platform and versions

Environment
  › OS: Windows 10.0.19042 X64
  › Webview2: 103.0.1264.77
  › MSVC: 
      - Visual Studio Build Tools 2022
  › Node.js: 16.15.1
  › npm: 8.13.2
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../src
  › devPath: http://localhost:3000/
  › framework: Svelte

App directory structure
  ├─ .git
  ├─ .netlify
  ├─ .svelte-kit
  ├─ node_modules
  ├─ src
  ├─ src-tauri
  └─ static

### Additional context

You can view the working (albeit not complete) webapp at https://tabletalkx.netlify.app

**Comment by lucasfernog** [comment]
To use SvelteKit in Tauri you need to use the static adapter (@sveltejs/adapter-static package) and also define a `src/hooks.ts` file to disable SSR:

```typescript
/** @type {import('@sveltejs/kit').Handle} */
export async function handle({ event, resolve }) {
  const response = await resolve(event, {
    ssr: false,
  });

  return response;
}
```
