### ISSUE TITLE
[bug] `fs` scope doesn't work with network drives

### ISSUE THREAD

**Issue by Phippe** [tauri-apps/tauri#4851]
### Describe the bug

I'm trying to access a file on a network drive `Z` on Windows at location `Z:\test_files\test.xlsx`. Usually, I'd simply add `"Z:/*"` to the scope array in `tauri > allowlist > fs > scope`, which will indeed work if `Z` is a local, normal drive. However, this fails and I'm getting the error `path not allowed on the configured scope: Z:\test_files\test.xlsx`.

Additionally, the path is created by first asking the user for the parent directory using Tauri's `dialog.open` and then `path.join`ing it with the predefined file name. Usually, the open dialog would extend the scope for the remaing time of the current session and therefore allow any parent directory the user has chosen. However, this also does not work when the user selects a network directory.

Neither `"Z:/*"` nor `"Z:\\*"` nor `"\\\\?\\Z:\\*"` does the trick. The only scope that does work is `"*"`, which kinda defeats the purpose of having scoped access in the first place.

### Reproduction

1. Make sure to have a network drive with some files on it.
2. Create a file with the following content:
```typescript
import { dialog, fs, path } from "@tauri-apps/api";

export async function loadFile() {
    const fileName = "test.xlsx";
    const selectedDir = await dialog.open({
        directory: true
    });
    if (typeof selectedDir === "string") {
        const filePath = await path.join(selectedDir, fileName);
        const file = await fs.readBinaryFile(filePath);
        return file;
    }
}
```
3. Define the scope in `tauri > allowlist > fs` as follows:
```json
"scope": [
  "\\\\?\\Z:\\*",
  "Z:\\*",
  "Z:/*"
]
```
4. Try to import and call this function (or call it in the same file).

### Expected behavior

Function returns a promise with the file that has been read

### Platform and versions
```sh
Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 103.0.1264.77
  › MSVC: 
      - Visual Studio Build Tools 2019
      - Visual Studio Community 2022
  › Node.js: 16.16.0
  › npm: 8.0.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0 (outdated, latest: 1.0.5)
  › @tauri-apps/api [NPM]: 1.0.1 (outdated, latest: 1.0.2)
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: Vue.js

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```
### Stack trace

```shell
Uncaught (in promise) path not allowed on the configured scope: Z:\test_files\test.xlsx (scope-bug.ts:13)
```

**Comment by lucasfernog** [comment]
In this case you need to enable the `recursive` option so the dialog will allow the entire folder to be read:

```javascript
const selectedDir = await dialog.open({
        directory: true,
		recursive: true,
    });
```
