### ISSUE TITLE
[bug] hide taskbar icon on macos side is not working

### ISSUE THREAD

**Issue by ayangweb** [tauri-apps/tauri#4852]
### Describe the bug

Hello developers, the property (skipTaskbar) and method (setSkipTaskbar) for hiding the taskbar icon in macos system are invalid when passed to true or false, and the corresponding method (set_skip_taskbar) is also invalid when written in rust. I don't know if windows is working because there is no windows available for testing! I hope you guys can solve the problem!

### Reproduction

If the value of the skipTaskbar property of the windows configuration window in tauri.conf.json is true or false, the effect of hiding is not achieved, and then calling the setSkipTaskbar method of the api will not help either

### Expected behavior

I want to hide the icons in the macos dock bar, and of course the same effect for windows

### Platform and versions

Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 16.14.1
  › npm: 8.5.0
  › pnpm: 7.7.1
  › yarn: 1.22.17
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

**Comment by FabianLars** [comment]
`skip_taskbar` does not work on macos, not a bug, but "expected" behavior. Also, skip_taskbar is window-specific which wouldn't have an effect on macos, since the dock icon is app-specific (i don't know how to explain it, so just ignore that if you don't understand me)

See https://github.com/tauri-apps/tauri/issues/2358 and https://github.com/tauri-apps/tao/issues/105 for the relevant macos feature requests.

**Comment by PhotonQuantum** [comment]
For anyone who comes to this issue through googling, Tauri has already implemented this feature:

See https://github.com/tauri-apps/tauri/blob/8fd79b8fc0b1dc66a06af3b7131ae895808f8ea4/core/tauri/src/app.rs#L731

**Comment by franciscop** [comment]
To clarify, after few trial/error (I'm not familiar with Rust at all) I found this way to hide the default Docker icon and only show the one on the system tray (top nav):

```rs
fn main() {
  let tray_menu = SystemTrayMenu::new(); // insert the menu items here
  let system_tray = SystemTray::new().with_menu(tray_menu);
  tauri::Builder::default()
    .setup(|app| {
      // Make the docker NOT to have an active app when started
      app.set_activation_policy(tauri::ActivationPolicy::Accessory);
      Ok(())
    })
    .system_tray(system_tray)
  // ...
```

**Comment by ayangweb** [comment]
> To clarify, after few trial/error (I'm not familiar with Rust at all) I found this way to hide the default Docker icon and only show the one on the system tray (top nav):
> 
> ```rust
> fn main() {
>   let tray_menu = SystemTrayMenu::new(); // insert the menu items here
>   let system_tray = SystemTray::new().with_menu(tray_menu);
>   tauri::Builder::default()
>     .setup(|app| {
>       // Make the docker NOT to have an active app when started
>       app.set_activation_policy(tauri::ActivationPolicy::Accessory);
>       Ok(())
>     })
>     .system_tray(system_tray)
>   // ...
> ```

I apologize for getting back to you so late, it does work, thanks!

**Comment by ayangweb** [comment]
> For anyone who comes to this issue through googling, Tauri has already implemented this feature:
> 
> See
> 
> https://github.com/tauri-apps/tauri/blob/8fd79b8fc0b1dc66a06af3b7131ae895808f8ea4/core/tauri/src/app.rs#L731

Thank you. Indeed.

**Comment by franciscop** [comment]
Edit: nevermind, thought that was new content but you were replying to the older comment :)
