### ISSUE TITLE
[feat] Add .tar.zst support for Linux bulilds

### ISSUE THREAD

**Issue by p0ryae** [tauri-apps/tauri#4857]
### Describe the problem

Currently on linux tauri builds `appimage` and `.deb`
It would be great to also have `tar.zst` compiled after the .deb and then finally the appimage.

### Describe the solution you'd like

Build a `.tar.zst `

### Alternatives considered

I use debtap to convert `.deb` into `tar.zst` each time building the app.

### Additional context

None.

**Comment by FabianLars** [comment]
Sounds like https://github.com/tauri-apps/tauri/pull/4301 (and therefore https://github.com/tauri-apps/tauri/issues/3728), right?

**Comment by p0ryae** [comment]
Correct. So it's in progress I believe?

**Comment by lucasfernog** [comment]
Yeah it'll be available as soon as it's audited.
