### ISSUE TITLE
[bug] appWindow.isDecorated() always true

### ISSUE THREAD

**Issue by pansusu** [tauri-apps/tauri#4859]
### Describe the bug

import { appWindow } from "@tauri-apps/api/window";
import { ref } from "@vue/reactivity";

let isDecoration = ref();

const getSysInfo = async () => {
	appWindow.setDecorations(false);
	isDecoration.value = await appWindow.isDecorated();  //always true
};

### Platform and versions

Environment
  › OS: Mac OS 11.6.0 X64
  › Node.js: 14.19.3
  › npm: 8.14.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-x86_64-apple-darwin

**Comment by nothingismagick** [comment]
Please provide the results of `yarn tauri info`. Thankyou

**Comment by lucasfernog** [comment]
Thanks for reporting. Fix will be available soon.

**Comment by lucasfernog** [comment]
Fix will be available when https://github.com/tauri-apps/tao/pull/508 gets merged and tao 0.13.2 gets released (at this point all you'll need to do is run `cargo update -p tao` in the src-tauri folder). Thanks for the report!

**Comment by pansusu** [comment]
> Fix will be available when [tauri-apps/tao#508](https://github.com/tauri-apps/tao/pull/508) gets merged and tao 0.13.2 gets released (at this point all you'll need to do is run `cargo update -p tao` in the src-tauri folder). Thanks for the report!

$ cargo update -p tao
    Updating `ustc` index

**Comment by pansusu** [comment]
> Fix will be available when [tauri-apps/tao#508](https://github.com/tauri-apps/tao/pull/508) gets merged and tao 0.13.2 gets released (at this point all you'll need to do is run `cargo update -p tao` in the src-tauri folder). Thanks for the report!

$ cargo update -p tao
    Updating `ustc` index

**Comment by pansusu** [comment]
> Fix will be available when [tauri-apps/tao#508](https://github.com/tauri-apps/tao/pull/508) gets merged and tao 0.13.2 gets released (at this point all you'll need to do is run `cargo update -p tao` in the src-tauri folder). Thanks for the report!

$ cargo update -p tao
    Updating `ustc` index

clean & build  --> 
Compiling tao v0.12.2         the version of tao not  be changed
