### ISSUE TITLE
[bug] Using navigator.appVersion for OS type is not reliable enough

### ISSUE THREAD

**Issue by snnsnn** [tauri-apps/tauri#4868]
### Describe the bug

I see you use ` navigator.appVersion.includes` function to get the operating system type but `navigator.appVersion` returns `"5.0 (X11)"` on Firefox 103.0.1 on Linux Mint.

https://github.com/tauri-apps/tauri/blob/679abc6a9a662a10a1c8f358364fdcb9d288f020/tooling/api/src/helpers/os-check.ts#L8

### Expected behavior

Linux Mint, Firefox 103.0.1

### Platform and versions

Linux Mint

**Comment by FabianLars** [comment]
I don't really understand? Firefox is irrelevant for Tauri apps. And this code seems to work alright in (webkitgtk) Tauri windows themselves
