### ISSUE TITLE
[bug] Window freeze when focusing in and out

### ISSUE THREAD

**Issue by loucass003** [tauri-apps/tauri#4870]
### Describe the bug

The Window freeze when focusing in and out, multiple times in a row. It is pretty random, it can happen after 5 times or 50
https://i.imgur.com/WbfqqD5.gif
![This is an image](https://i.imgur.com/WbfqqD5.gif)
![kOA5HaE6kU](https://user-images.githubusercontent.com/3948904/182947764-bc148b2b-fd0d-40d9-9a8d-b9279cd30481.gif)
### Reproduction

Focus back and force on the window by clicking on the grabable reagion `data-tauri-drag-region` (in red on the gif). it will eventually froze.

it looks like it is only happening when focusing back on a dragable region

### Expected behavior

Not freezing

### Platform and versions

```
PS C:\Users\louca\Documents\Slimevr\tauri-freeze-test> npm run tauri info

> tauri-freeze-test@0.1.0 tauri
> tauri "info"


Environment
  › OS: Windows 10.0.22000 X64
  › Webview 2: 103.0.1264.77
  › MSVC:
      - Visual Studio Community 2019
  › Node.js: 16.13.0
  › npm: 8.1.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ .git
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

### Stack trace

```shell
No stack trace
```

### Additional context

The app where i recorded the bug from is an empty tauri app created from the cli configured with react
I tried with or without decorations on, it does the same behaviour.
it also happened on window 11 and 10 on different computers.

i can upload the code if needed

Thanks in advance

**Comment by loucass003** [comment]
Here is the test code https://github.com/loucass003/tauri-freeze-bug

**Comment by mrjvs** [comment]
able to reproduce on windows 11 with just html/css:
```html
<!DOCTYPE html>
<html>
  <body>
    <style>
      html, div, body {
        margin: 0;
        padding: 0;
        width: 100%;
        height: 100%;
        display: flex;
        text-align: center;
      }
      .wrap {
        align-items: center;
        justify-content: center;
        background: #0c0614;
        font-family: Arial, Helvetica, sans-serif;
        color: white;
      }
      .wrap > * {
        pointer-events: none;
      }
    </style>
    <div class="wrap" data-tauri-drag-region>
      <h1>drag me</h1>
    </div>
  </body>
</html>
```
```json
{
  "$schema": "../node_modules/@tauri-apps/cli/schema.json",
  "build": {
    "beforeBuildCommand": "",
    "beforeDevCommand": "",
    "devPath": "../dist",
    "distDir": "../dist"
  },
  "tauri": {
    "allowlist": {
      "all": true
    },
    "bundle": {
      "externalBin": [],
      "identifier": "com.tauri.dev",
      "targets": "all"
    },
    "windows": [
      {
        "height": 400,
        "width": 400
      }
    ]
  }
}
```
<img src="https://camo.githubusercontent.com/2cf3fd17995229b7027ee5084e68d4121036777e244aa358a3be7890c88185c0/68747470733a2f2f692e696d6775722e636f6d2f334633646345502e676966" alt="gif showcasing freeze" />

**Comment by amrbashir** [comment]
I can reproduce this bug with Tauri but not with WRY custom_titlebar example. Can you guys also confirm that the the bug doesn't happen on wry?

```sh
git clone https://github.com/tauri-apps/wry
cd wry
cargo r --example custom_titlebar
```

**Comment by mrjvs** [comment]
> I can reproduce this bug with Tauri but not with WRY custom_titlebar example. Can you guys also confirm that the the bug doesn't happen on wry?
> 
> ```shell
> git clone https://github.com/tauri-apps/wry
> cd wry
> cargo r --example custom_titlebar
> ```

can confirm, on WRY I wasn't able to get the same freezing bug (using the example)

**Comment by amrbashir** [comment]
Thank you, this means there is probably a mutex lock in tauri or something that isn't being dropped fast enough.

**Comment by lucasfernog** [comment]
I couldn't really reproduce it, though I expect #4909 to fix it.

**Comment by amrbashir** [comment]
can't seem to reproduce it with the fix from #4909

**Comment by Moon1102** [comment]
@amrbashir excuse me, there still seems to be a problem with data-tauri-drag-region in my test.

https://user-images.githubusercontent.com/15380331/187820446-721f8517-622c-470a-b5e5-6106541049b6.mov

but I can bypass it by
<img width="673" alt="图片" src="https://user-images.githubusercontent.com/15380331/187820623-981ef3dd-222c-4526-900b-8c58eaa987f1.png">

****
EDIT：

https://user-images.githubusercontent.com/15380331/187822354-19a1879c-7300-4dc9-baa9-2dba0f18ce52.mov

**Comment by FabianLars** [comment]
@Moon1102 The drag attribute works only on the actual click target, which most of the times is the most inner element. This is by design because otherwise it would cause problems with buttons or other interact-able elements inside the drag area. You can confirm that this is the issue by trying to drag the window when it already has focus.

If it's the issue you basically just have to try adding the attribute to other elements and see what works for you, _or_ keep using the js api if it doesn't cause any problems :)
