### ISSUE TITLE
Expose window properties to the configuration file

### ISSUE THREAD

**Issue by Armaldio** [tauri-apps/tauri#488]
**Is your feature request related to a problem? Please describe.**
It could be great to be able to configure our window directly from the config file (like starting fullscreen, specifying width, height, etc.)

**Describe alternatives you've considered**
My original need was to start a window fullscreen and I used this code:
```rust
tauri::AppBuilder::new()
    .setup(|_webview, arg| {
      _webview.set_fullscreen(true)
    })
```

**Additional context**
Link to the discord discussion: https://discordapp.com/channels/616186924390023171/625037620996734986/685178556107587626

**Comment by lucasfernog** [comment]
Width and height are already implemented, if someone wants to PR this to get a feeling of what is tauri, check out the runner.rs file and look for the config object.
