### ISSUE TITLE
[bug] Transparency issue on windows

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#4881]
### Describe the bug

Settings `"transparent": true` to the `WindowConfig` object still creates a white background. You need to resize the screen in order to crop and remove it.

Resizing the screen outwards leaves the fixed white background and reveals the transparent one.

https://user-images.githubusercontent.com/60566421/183296733-0b31b31f-56f9-42db-8e3b-22544b9e4822.mp4

### Reproduction

1. Create a new app `npm create tauri-app`
2. Set `"transparent": true` in the windows array object.
3. Run the app

This is tested on a new ` tauri-app` with the default `Vanilla.js (html, css, and js without the bundlers)` UI recipe.

**tauri.config.json**

```
...
"windows": [
      {
        "fullscreen": false,
        "height": 600,
        "resizable": true,
        "title": "Tauri App",
        "width": 800,
        "transparent": true <-- only change
      }
    ]
...
```

### Expected behavior

The app background should be transparent on initialization.

### Platform and versions

```
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 104.0.1293.47
  › MSVC: 
      - Visual Studio Build Tools 2022
      - Visual Studio Build Tools 2017
  › Node.js: 14.18.3
  › npm: 6.14.15
  › pnpm: Not installed!
  › yarn: 1.15.2
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: ../dist

App directory structure
  ├─ dist
  ├─ node_modules
  └─ src-tauri
```

**Comment by amrbashir** [comment]
upstream issue https://github.com/tauri-apps/tauri/issues/8632, once it is fixed, it will land in tauri atuomatically

**Comment by AmazingRise** [comment]
Temporary workaround: https://github.com/tauri-apps/tauri/issues/8632

> Just found a workaround, set your decorations to false in tauri.conf, then when your app is loaded use the Javascript API to reset it to true. Worked for me

Here is a more detailed guide:

In `tauri.conf.json`, set the target window's `decorations` to `false`.
```json
{
    "......(Some other configurations)"
    "windows": [
      {
        "......"
        "transparent": true,
        "decorations": false
      }
    ]
}
```

And then the window should be transparent.

**NOTE**: If you need `decorations` to be true, you may set it later in frontend.

![image](https://user-images.githubusercontent.com/8315221/222961466-1bc0c0af-4342-4236-87ba-72e3ca70c260.png)

**Comment by tomasvilio** [comment]
hey this didnt work for me, i have decorations off and there seems to be no tranparent effect

**Comment by FabianLars** [comment]
nowadays you also need to disable shadows

**Comment by tomasvilio** [comment]
ohh ok tank you so much
it worked
