### ISSUE TITLE
indexedDB tab is not showing in devtools

### ISSUE THREAD

**Issue by noor-tg** [tauri-apps/tauri#4885]
hi, 

IndexedDB tab is not showing in devtools when there is no db.

dev env: linux
 
_Originally posted by @nour-dev in https://github.com/tauri-apps/tauri/discussions/4876_

**Comment by FabianLars** [comment]
Looks like this is just how WebKit behaves, nothing we can do here afaik

**Comment by noor-tg** [comment]
ok
