### ISSUE TITLE
[bug] WebView2 requirement is very recent and Tauri has no fallback

### ISSUE THREAD

**Issue by LoganDark** [tauri-apps/tauri#4886]
### Describe the bug

Tauri fails to start if the version of WebView2 installed is not fully up-to-date. I had version 91 of the evergreen runtime installed and Tauri failed with this error message:

```
Error: Runtime(CreateWebview(WebView2Error(WindowsError(Error { code: 0x80004002, message: No such interface supported
 }))))
```

It's possible Tauri is trying to access an API (COM interface?) that is only present in newer versions of WebView2, and simply bailing out if it's not present. If this interface is not strictly needed for Tauri's operation then it should be optional.

### Reproduction

1. Have an outdated WebView2
2. Try to run Tauri with the system WebView2 (i.e. run `cargo tauri dev`)

### Expected behavior

Tauri should have graceful fallbacks for newer features that aren't supported by all WebView2 runtimes. Microsoft documentation says that you cannot always rely on the latest version being installed. They say this in relation to web platform features (i.e. JS APIs, CSS properties) but I would think it applies just as well to the webview interface.

Additionally it should be possible to run `cargo tauri dev` with a fixed WebView2 version in case it's not possible to update the system installation. (but that should probably be a separate feature request)

### Platform and versions

```
Environment
  › OS: Windows 10.0.19041 X64
  › Webview2: 91.0.864.67
  › MSVC: 
      - Visual Studio Community 2019
      - Visual Studio Build Tools 2019
      - Visual Studio Build Tools 2017
  › Node.js: 16.10.0
  › npm: 7.24.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: build
  › CSP: unset
  › distDir: html
  › devPath: html
package.json not found
```

Tauri works after I updated to WebView2 104.0.1293.47, which is the latest offline installer available from Microsoft.

**Comment by thewh1teagle** [comment]
I experience the same error on fresh install of Windows 11.

**Comment by amrbashir** [comment]
fixed by https://github.com/tauri-apps/wry/pull/1306
