### ISSUE TITLE
[bug]  V-model doesn't work on Vue3

### ISSUE THREAD

**Issue by TomDoFuture** [tauri-apps/tauri#4896]
### Describe the bug

```
<template>
    <div class="w-full bg-primarybackground">
        {{testvmodel}}
        <input v-model="testvmodel" />
    </div>
</template>

<script lang="ts">
export default {
    data() {
        return {
            testvmodel : 0,
        }
    },
}
</script>

```

Build it in debug mode : npm run tauri build -- --debug

Type anything in input, you will see that in the dev console the program cant find testvmodel

### Reproduction

Build it in debug mode : npm run tauri build -- --debug

Type anything in input, you will see that in the dev console the program cant find testvmodel

### Expected behavior

V-model works like in regular vue3

### Platform and versions

  Model Name:	Mac mini
  Model Identifier:	Macmini8,1
  Processor Name:	Quad-Core Intel Core i3
  Processor Speed:	3.6 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB

**Comment by nothingismagick** [comment]
Thanks for the report, but this is definitely not a problem with Tauri, as I am personally aware of several other projects that use `v-model` and Vue3 and TS.

Maybe we can help you triage, but that would require you sharing a repo.

**Comment by TomDoFuture** [comment]
> Thanks for the report, but this is definitely not a problem with Tauri, as I am personally aware of several other projects that use `v-model` and Vue3 and TS.
> 
> Maybe we can help you triage, but that would require you sharing a repo.

Please link these repos to me, I wish to see how they got it working.

Regardless, this can easily be replicated. Simply initiate a tauri project with vue-ts

Then copy and paste my code up there, or create a vue component with that code up there copy and pasted and display it. You will see the console in inspect will give you an error.

**Comment by lucasfernog** [comment]
@TomDoFuture I couldn't replicate it. Can you upload a repo so I can try?

**Comment by masterjanic** [comment]
If you are using lang="ts" you will need to use defineComponent or use refs.
