### ISSUE TITLE
[feat] Sharable client-server IPC API types (100% Rust, no JS)

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#4898]
## Code structure

Idea: Rust types that are sharable between the Wasm client and the Tauri server, without a manual JS bridge.

```rust
//! ipc_api/lib.rs

use wasm_bindgen::prelude::*;

#[wasm_bindgen(getter_with_clone)]
pub struct GreetSomeoneArgs {
    first_name: String,
    last_name: String,
}
```

```rust
//! client-side Wasm

use wasm_bindgen::prelude::*;
use ipc_api::GreetSomeoneArgs;

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = ["window", "__TAURI__"], js_name = "invoke")]
    fn greet_someone_js(s: &str, args: GreetSomeoneArgs);
}

fn greet_someone(args: GreetSomeoneArgs) {
    greet_someone_js("greet_someone", args.into());
}

#[wasm_bindgen(start)]
fn main() -> Result<(), JsValue> {
    // ...
    greet_someone(GreetSomeoneArgs { first_name: "Joe", last_name: "Shmoe" });
    // ...
}
```

```rust
//! Tauri server

use tauri::{command, generate_context, generate_handler, Builder};
use ipc_api::GreetSomeoneArgs;

fn main() {
    Builder::default()
        .invoke_handler(generate_handler![greet_someone])
        .run(generate_context!())
        .expect("error while running tauri application");
}

#[command]
fn greet_someone(args: GreetSomeoneArgs) {
    // TODO: greet.
}
```

## Problem 1: forced case conversion

All fields' keys get converted to `camelCase`. This results in incorrect key access with Rust fields that contain underscores. AFAIK, this currently can't be disabled.

## Problem 2: unnecessary nesting

Error:
```
Unhandled Promise Rejection: invalid args `args` for command `greet_someone`: command greet_someone missing required key args
```

I.e. Tauri, with the code structure above, seems to expect:
```json
{
    "args": {
        "firstName": "Joe",
        "lastName": "Shmoe"
    }
}
```

Instead of just:
```json
{
    "firstName": "Joe",
    "lastName": "Shmoe"
}
```

Which seems unnecessary and results in incorrect key access.

## Problem 1 solution:

Add a config entry in `tauri.conf.json` to disable automatic `camelCase` conversion. `snake_case` keys should always be valid Json, too.

## Problem 2 solution:

No idea. Not familiar enough with Tauri to see why this would happen or how this could be fixed.

### Alternatives considered

I don't want to have JS/TS code, so that's not a viable alternative for me.

**Comment by ColonelThirtyTwo** [comment]
Tauri uses serde to convert rust objects to JavaScript, so you'll need to use its mechanisms to rename fields.

I believe there are ways to convert JS objects to Rust ones using serde as well. You can extract the object definitions into a separate crate and share that crate between the server and client page.

**Comment by amrbashir** [comment]
for problem 2:
the second argument for `invoke()` is an object where keys are the rust command argument and values are the value for that argument, so for example:
```rs
#[command]
fn greet(args1: GreetArgs, args2: GreetArgs){
}
```
should be invoked using js like this:
```rs
invoke("greet", {
	args1: {
		firstName: "Joe",
	},
	args2: {
		firstName: "Doe",
	}
})
```
and the rust equivalent would be (needs serde for serialization):
```rs
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = ["window", "__TAURI__"], js_name = "invoke")]
    fn invoke(cmd: &str, args: JsValue);
}

#[derive(Serialize)]
struct GreetInvokeArgs {
	args1: GreetArgs,
	args2: GreetArgs,
}

invoke("greet", JsValue::from_serde(&GreetInvokeArgs { 
    args1: GreetInvokeArgs { first_name: "Joe" },
	args2: GreetInvokeArgs { first_name: "Doe" }, 
  }).unwrap())

```

There is a bit of boiler-plate, and I am not a rust or wasm expert but I think it could be cleaned up a little bit.
