### ISSUE TITLE
[feat] Add a way to launch app in wayland window or improve documentation for doing so

### ISSUE THREAD

**Issue by skewballfox** [tauri-apps/tauri#4915]
### Describe the problem

There should be some way for a user to launch an application in a wayland window, something similar to electron's `--enable-features=UseOzonePlatform --ozone-platform=wayland`. 

it seems it used to be doable via `--WINIT_UNIX_BACKEND=wayland` but, at least according to one of the developers using tauri [that was removed](https://github.com/a5huynh/spyglass/issues/135). 

This may be something that is currently possible in tauri, but when I was looking a few days ago (both in documentation and issues in tauri apps) I couldn't find any reference to how. 

### Describe the solution you'd like

A command line flag to explicitly launch a tauri application as a wayland session, or add a section or subsection to the documentation for it.

### Alternatives considered

I mean there isn't one really, you can try to autodetect a running wayland session, but I can almost guarantee it will likely fail in some situation (probably on some users custom sway setup) and there will need to be some way to override the autodetection.

### Additional context

While I understand that certain things might be broken on wayland such as [global shortcuts](https://github.com/tauri-apps/tauri/issues/3578)(though that's broken regardless of the window type), it should be up to the user whether or not to embrace the suck. believe it or not, it's still the [less sucky option](https://wiki.gentoo.org/wiki/User:Sakaki/Sakaki%27s_EFI_Install_Guide/Sandboxing_the_Firefox_Browser_with_Firejail#Demonstrating_the_X11_Vulnerability)

**Comment by amrbashir** [comment]
the globalShortcuts has been disabled on wayland in https://github.com/tauri-apps/tao/pull/543, so once that PR lands in tauri, there shouldn't be a problem to run on wayland.

**Comment by skewballfox** [comment]
This isn't actually an issue with running on wayland, I was more hoping for something similar to what is provided with electron with the flags  `--enabledfeatures=UseOzonePlatform --ozone-platform=wayland`, though a config option or an env variable would work. It may already exist, and just needs to be documented. Often x apps are broken on wlroots (at least with Nvidia), and Some applications will refuse to work if these aren't supplied (discord, at one point signal).
