### ISSUE TITLE
[feat] How can I trigger keyTap in Tauri?

### ISSUE THREAD

**Issue by zh-lx** [tauri-apps/tauri#4916]
### Describe the problem

I want to get the content of mouse Selection. There is a npm package named [robotjs](https://github.com/octalmage/robotjs) that supports to trigger KeyTap such as "command + c", but it only can be used in Electron. How can I trigger keyTap in Tauri?

### Describe the solution you'd like

I hope tauri can support to trigger KeyTap.

**Comment by amrbashir** [comment]
use a crate like https://github.com/enigo-rs/enigo or https://github.com/obv-mikhail/inputbot
