### ISSUE TITLE
[bug] the trait `Deserialize<'_>` is not implemented for `AppHandle`

### ISSUE THREAD

**Issue by schmaenjael** [tauri-apps/tauri#4919]
### Error

I was trying to move the `generate_handler!` to an external init function. 

However, an error is being thrown by the #[tauri::command] macro for the following function:

Function:
```rs
#[tauri::command]
pub fn add_profile(
    app_handle: tauri::AppHandle,
    storage: State<Mutex<AppConfig>>,
    profile: Profile,
) {}
```

Error:
```sh
error: the trait bound `AppHandle: Deserialize<'_>` is not satisfied
label: the trait `Deserialize<'_>` is not implemented for `AppHandle`
```

Oddly enough, I can access the `State<>` but not the `AppHandle`.

The init function looks like this:

```rs
pub fn init<R: Runtime>() -> impl Fn(Invoke<R>) + Send + Sync + 'static {
    generate_handler![
        get_app_config,
        get_datatype,
        get_object,
        create_object_store,
        add_profile // this function is the only one that doesnt work
    ]
}
```

This is the complete error:
```rs
error[E0277]: the trait bound `AppHandle: Deserialize<'_>` is not satisfied
   --> src\commands\command_handler.rs:58:1
    |
58  |   #[tauri::command]
    |   ^^^^^^^^^^^^^^^^^ the trait `Deserialize<'_>` is not implemented for `AppHandle`
...
96  | /     generate_handler![
97  | |         get_app_config,
98  | |         get_datatype,
99  | |         get_object,
100 | |         create_object_store,
101 | |         add_profile
102 | |     ]
    | |_____- in this macro invocation
    |
    = note: required because of the requirements on the impl of `CommandArg<'_, R>` for `AppHandle`
    = note: this error originates in the macro `__cmd__add_profile` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
warning: `app` (bin "app") generated 1 warning
error: could not compile `app` due to previous error; 1 warning emitted
```

### Reproduction

1. Copy the following function into your rust file:

```rs
pub fn init<R: Runtime>() -> impl Fn(Invoke<R>) + Send + Sync + 'static {
    generate_handler![
        /*  your commands that access AppHandle */
    ]
}
```

2. Call the function in the `invoke_handler()`

```rs
    tauri::Builder::default()
       // [...]
        .invoke_handler(command_handler::init())
       // [...]
```

### Expected behavior

I expected it to work like the solution provided below:

### Solution (thanks to @FabianLars#6748 on discord)

This error can be fixed by chaning the function signature of the `init` function to this

```rs
pub fn init() -> impl Fn(Invoke<Wry>) + Send + Sync + 'static {}
```

### Platform and versions

Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 104.0.1293.47
  › MSVC:
      - Visual Studio Community 2022
      - Visual Studio Build Tools 2017
  › Node.js: 16.13.0
  › npm: 8.1.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.0 (outdated, latest: 1.0.5)
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.4,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist/
  › devPath: http://localhost:5173/
  › framework: React

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ dist
  ├─ gen
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri

### Additional context

The link to FabianLars's response on discord and my inital question:

https://discord.com/channels/616186924390023171/731495028677148753/1007558501893148682

**Comment by amrbashir** [comment]
you can just add a generic for `AppHandle`
```
#[tauri::command]
pub fn add_profile<R: Runtime>(
    app_handle: tauri::AppHandle<R>,
    storage: State<Mutex<AppConfig>>,
    profile: Profile,
) {}
```
