### ISSUE TITLE
CWE-820 9.8/10

### ISSUE THREAD

**Issue by Coronon** [tauri-apps/tauri#4925]
### Describe the bug

The upstream crate [`winrt-notification`](https://crates.io/crates/winrt-notification) uses the crate [`windows`](https://crates.io/crates/windows) in version `0.24.0`.

GitHub dependabot alerts everyone that uses Tauri of a critical vulnerability in that windows version:

[Delegate functions are missing `Send` bound ](https://github.com/advisories/GHSA-x4mq-m75f-mx8m)

### Reproduction

n.a.

### Expected behavior

n.a.

### Platform and versions

Windows (but GitHub will always report as long as `tauri` is included in `Cargo.toml`)

### Stack trace

```shell
n.a.
```

### Additional context

n.a.

**Comment by lucasfernog** [comment]
We're considering forking winrt-notification to mitigate this. Let's see if the notify-rust maintainer accepts it https://github.com/hoodie/notify-rust/issues/148

**Comment by amrbashir** [comment]
this has been fixed in the last couple of releases of notify-rust
