### ISSUE TITLE
[problems] about how picture-in-picture works

### ISSUE THREAD

**Issue by wabi-habi** [tauri-apps/tauri#4927]
### Describe the bug

Hi developer, I've recently seen an upload about macos updating the picture-in-picture feature, but I really don't understand how it works, so I hope you can help me out!

### Platform and versions

› OS: Mac OS 12.5.0 X64
› Node.js: 16.14.1
› npm: 8.5.0
› pnpm: 7.7.1
› yarn: 1.22.17
› rustup: 1.25.1
› rustc: 1.62.1
› cargo: 1.62.1
› Rust toolchain: stable-aarch64-apple-darwin

Packages
› @tauri-apps/cli [NPM]: 1.0.5
› @tauri-apps/api [NPM]: 1.0.2
› tauri [RUST]: 1.0.5,
› tauri-build [RUST]: 1.0.4,
› tao [RUST]: 0.12.2,
› wry [RUST]: 0.19.0,

**Comment by amrbashir** [comment]
PIP support on macOS hasn't been released yet, watch out for the next release.

**Comment by wabi-habi** [comment]
> PIP support on macOS hasn't been released yet, watch out for the next release.

thank you, I'm looking forward to it!
