### ISSUE TITLE
[bug] Incorrect tray position, monitor size

### ISSUE THREAD

**Issue by seahindeniz** [tauri-apps/tauri#4931]
### Describe the bug

The position and size argument provides an incorrect position value. This issue happens for `current_window` as well.

https://user-images.githubusercontent.com/5789670/184507948-0d787ee4-35ee-40dc-90ce-7864fe12560d.mp4

### Reproduction

1. Clone the minimal repro repo https://github.com/seahindeniz/tauri-position-issue-1
2. Run `npm run tauri dev`
3. Click on tray icon and observe details on terminal

### Expected behavior

Since I have a 1440 x 900 pixels monitor resolution, I would like to see get the correct values from the API as well.

### Platform and versions

Macbook M1
```bash
Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 16.15.0
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  └─ .git
```

**Comment by seahindeniz** [comment]
Been trying to handle this for hours and right after posting this issue, I just noticed `current_monitor.scale_factor()` which returns the scale value 🤦🏻 
I wasn't aware that the primary monitor was getting scaled, unlike an external monitor.

**Comment by FabianLars** [comment]
The reported values seem to be correct. Keep in mind that the struct they return is called **Physical**Size/Position, so they return the actual hardware specs. These structs do have a `to_logical` method if you prefer to work with these numbers; this method takes the scale_factor you mentioned as an argument.

(Also you really confused me by calling the _monitor_ size, _window_ size in the console output :D )
