### ISSUE TITLE
[feat] Add Javascript/Wasm benchmark to the mix

### ISSUE THREAD

**Issue by RubenKelevra** [tauri-apps/tauri#4933]
### Describe the problem

I've seen that you're using a benchmark already. I was wondering if you're interested to expand it:

### Describe the solution you'd like

There's [wasmboy](https://github.com/torch2424/wasmboy) which allows running a gameboy color game to be rendered in a browser as wasm or as javascript.

As it's easy to compare between different platforms (just open the browser on this test and load the same carriage) it could be a good benchmark. :)

**Comment by FabianLars** [comment]
This is probably less interesting than one would think. Well, the memory/cpu usage may be somewhat interesting, but is probably already covered by the cpu_intensive benchmark.
The wasmboy performance itself should be roughly the same as in their readme after taking hardware differences into account.

i'll close this issue on that note, but feel free to reach out if you disagree (same for the other team members if they think it'd be valuable)
