### ISSUE TITLE
[docs] Awesome Tauri - addon?

### ISSUE THREAD

**Issue by RubenKelevra** [tauri-apps/tauri#4934]
Online Websites were often just packaged into pseudo applications by stripping the the GUI around the browser and make a desktop icon for it.

This was not only bloated but also not portable.

For example there are tools to do this like [nativefier](https://github.com/nativefier/nativefier) and [pyqtws](https://github.com/intersimone999/pyqtws) / [qtws](https://github.com/intersimone999/qtws).

I like to create a collection of simple web-apps based on Tauri for the most common websites out there, doing the same but with less bloat and as portable as possbile.

Feel free to join and work on that together. :)

/cc @intersimone999 because I linked your work.

**Comment by RubenKelevra** [comment]
Link to the org: https://github.com/tauri-webapps

**Comment by amrbashir** [comment]
There is https://github.com/tauri-apps/awesome-tauri
