### ISSUE TITLE
[bug] Cannot deploy non-existing library file: `linux-vdso.so.1`

### ISSUE THREAD

**Issue by eliaperantoni** [tauri-apps/tauri#4936]
### Describe the bug

After following the tutorial on creating a Tauri app with vanilla JS, I tried building it with `cargo tauri build` but I get an error on the AppImage step. Using the `--verbose` flag uncovers the issue which seems to be:

```
-- Deploying dependencies for existing files in AppDir -- 
Deploying dependencies for ELF file blossom.AppDir/usr/bin/blossom 
ERROR: Cannot deploy non-existing library file: /home/elia/dump/tauritest/src-tauri/target/release/bundle/appimage/linux-vdso.so.1 
ERROR: Failed to deploy dependencies for existing files 
       Error [tauri_cli] failed to bundle project: error running appimage.sh: error running appimage.sh: `failed to run /home/elia/dump/tauritest/src-tauri/target/release/bundle/appimage/build_appimage.sh`
```

### Platform and versions

Environment
  › OS: Arch Linux Unknown X64
  › Node.js: 18.6.0
  › npm: 8.13.2
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.64.0-beta.1
  › cargo: 1.64.0-beta.1
  › Rust toolchain: beta-x86_64-unknown-linux-gnu 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../ui
  › devPath: ../ui
package.json not found

App directory structure
  ├─ src-tauri
  └─ ui

### Additional context

I have installed all the required software as explained in:
https://tauri.app/v1/guides/getting-started/prerequisites#setting-up-linux

**Comment by eliaperantoni** [comment]
Seems to be related to https://github.com/linuxdeploy/linuxdeploy/issues/210 as I am, in fact, running glibc 2.36. Not Tauri's fault, closing.

**Comment by FabianLars** [comment]
Thanks for finding/linking the upstream issue! ❤️
