### ISSUE TITLE
[bug] server never receives the file

### ISSUE THREAD

**Issue by moxun33** [tauri-apps/tauri#4941]
### Describe the bug

I use multipart/form-data to send the file to the backend, but the server never receives the file

- request body
```js
Body.form({
    "file": {
        "file": ArrayBuffer(753910),
        "mime": "image/jpeg",
        "fileName": "0001.jpg"
    }
})
```
- headers received by the server
![shot_2022-08-14_17-52-16](https://user-images.githubusercontent.com/5940883/184614984-4c908f50-fdd2-4a9d-8ed4-9842bf73ba8b.png)

- responses from server
```json
{
  "detail": [
    {
      "loc": [
        "body",
        "file"
      ],
      "msg": "field required",
      "type": "value_error.missing"
    }
  ]
}
```

### Reproduction

1、choose a file from input element
2、convert file into arraybuffer
3、initial form data with Body.form()
4、send the request with tauri fetch api

### Expected behavior

 server can receive the file

### Platform and versions

```js
> tauri "info"


Environment
  › OS: Windows 10.0.19042 X64
  › Webview2: 101.0.1210.53
  › MSVC: 
      - Visual Studio Community 2022
      - Visual Studio ???? 2019
  › Node.js: 18.4.0
  › npm: 6.14.0
  › pnpm: 7.5.0
  › yarn: 1.22.10
  › rustup: 1.24.3
  › rustc: 1.62.0
  › cargo: 1.62.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › framework: React

App directory structure
  ├─ .git
  ├─ .husky
  ├─ .idea
  ├─ .scannerwork
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ scripts
  ├─ src
  ├─ src-tauri
  └─ tests

```

### Additional context

When i send the file with Postman the server can receive.

tauri feature flags ``tauri = { version = "1.0.5", features = ["api-all", "devtools", "http-multipart", "reqwest-client", "system-tray"] }``

**Comment by raunakdoesdev** [comment]
Am having the same issue.

**Comment by amrbashir** [comment]
Please provide a minimal repro so we can triage and fix the issue

**Comment by raunakdoesdev** [comment]
I just switched to native JavaScript fetch for this request and added the endpoint to the security exceptions list.
