### ISSUE TITLE
[docs] Unclear instructions for updating a menu

### ISSUE THREAD

**Issue by cafca** [tauri-apps/tauri#4945]
I am trying to add items to the "File" submenu of a `Menu` that was created using `Menu::os_default`.

The documentation has a section ["Updating menu items"](https://tauri.app/v1/guides/features/menu/#updating-menu-items) that seems relevant. However, `main_window.menu_handle()` doesn't return a menu handle containing the default menu items created by `Menu::os_default()` when running the following snippet.

How do I insert additional menu items into the default menu?

```rust
tauri::Builder::default()
    .menu(tauri::Menu::os_default(&context.package_info().name))
    .setup(|app| {
        let main_window = app.get_window("main").unwrap();
        let menu_handle = main_window.menu_handle();
        std::thread::spawn(move || {
            // `menu_handle` is empty at this point and doesn't contain any items as can be seen
            // in a debugger. This panics!
            menu_handle.get_item("File")

            // How would I add menu items at this point?
        });
        Ok(())
        })
    .run(context)
    .expect("error while running tauri application");
```

**Comment by khrykin** [comment]
Also quite unclear how to edit submenus at runtime (for e.g. implementing a list of recently opened files).
