### ISSUE TITLE
[bug] create-tauri-app sometimes ships with deprecated npm versions of tauri 

### ISSUE THREAD

**Issue by Robinerra** [tauri-apps/tauri#4950]
### Describe the bug

_This issue is mostly to make it googlable and to help others who run into it._

Running create-tauri-app will sometimes ship with the deprecated npm alpha version of tauri (0.14.1)

This is a very rare problem but still happens (@FabianLars has seen it several times)

Attempting to build with this broken install gives this error: 
```
[tauri]: running build
 ERROR: tauri.conf.json has unknown property $schema +0ms
 ERROR: tauri.conf.json has unknown property package +0ms
 ERROR: tauri.conf.json > tauri has unknown property updater +0ms
 ERROR: tauri.conf.json > tauri has unknown property windows +0ms
 ERROR: tauri.conf.json > tauri > bundle has unknown property macOS +0ms
 ERROR: tauri.conf.json > tauri > bundle has unknown property windows +0ms
 ERROR: tauri.conf.json > tauri > security > csp should be string +0ms
```

This broken install seems to not install the rest of the dependencies correctly, for example in ``tauri.conf.json``, it throws a warning about ``../node_modules/@tauri-apps/cli/schema.json`` not existing (because it doesn't)

A github repo of the broken version can be found [here](https://github.com/Robinerra/flac-player/tree/d54321eeaf6dcacf80b4adc66a8e14ad01c153e1)

The easiest way to resolve this issue is just to recreate the app with npx.

### Reproduction

1. Run ``npx create-tauri-app`` and select react, then typescript
2. Get unlucky

### Expected behavior

create-tauri-app ships with the correct version and gives no problems.

### Platform and versions

```
[tauri]: running info

Operating System - Linux(5.15.0-46-generic) - linux/x64

Node.js environment
  Node.js - 16.13.1
  tauri.js - 0.14.1

Rust environment
  rustc - 1.61.0
  cargo - 1.61.0
  tauri-bundlerNot installed

Global packages
  NPM - 8.1.2
  yarn - 1.22.18

App directory structure
/.git
/node_modules
/public
/src
/src-tauri

App
/home/<Redacted for privacy>/tauri-app/node_modules/tauri/node_modules/semver/classes/semver.js:38
      throw new TypeError(`Invalid Version: ${version}`)
            ^
```

**Comment by amrbashir** [comment]
Idk what's going on but I won't waste time on it since we are gonna introduce new templates in tauri-apps/create-tauri-app#90 that should be up to date and better than the current ones.
if you want the, PR has instructions on how you might wanna test it out before it is released.
