### ISSUE TITLE
[docs] tauri how to generate windows minidump?

### ISSUE THREAD

**Issue by RAVER0306** [tauri-apps/tauri#4953]
tauri how to generate windows minidump?

**Comment by amrbashir** [comment]
call [`MiniDumpWriteDump`](https://docs.microsoft.com/en-us/windows/win32/api/minidumpapiset/nf-minidumpapiset-minidumpwritedump?redirectedfrom=MSDN) upon panics using [`catch_window`](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html)
