### ISSUE TITLE
[bug] external binaries using Command::sidecar takes the app in an infinite loop

### ISSUE THREAD

**Issue by fayeed** [tauri-apps/tauri#4954]
### Describe the bug

On windows running external binaries using `Command::sidecar` takes the app in an infinite loop where it keeps creating new processes.

### Platform and versions

Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 104.0.1293.54
  › MSVC: 
      - Visual Studio Build Tools 2019
      - Visual Studio Build Tools 2017
  › Node.js: 16.13.2
  › npm: 8.13.1
  › pnpm: Not installed!
  › yarn: 1.22.15
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ .git
  ├─ .github
  ├─ build
  ├─ node_modules
  ├─ public
  ├─ scripts
  ├─ src
  └─ src-tauri

**Comment by FabianLars** [comment]
This sounds like your sidecar is writing files in the src-tauri dir, which triggers the file watcher to restart `tauri dev`.

**Comment by fayeed** [comment]
We recently updated to the new tauri version `1.0.5` from `1.0.0-rc.11` and started encountering this problem on Windows, I have also tested this on MacOS and this doesn't happen

**Comment by FabianLars** [comment]
The file watcher was upgraded to also watch for changes in (cargo) workspace members, maybe that's the problem here?

You can add an ignore file for paths the watcher should ignore by using the `TAURI_DEV_WATCHER_IGNORE_FILE` env var (a file path to a custom ignore file). The next cli version will automatically read `.taurignore` files for this too.

If the sidecar is 100% not writing to other dirs that the watcher picks up either, we'll need a reproduction example to help you.

**Comment by mrceperka** [comment]
I've encountered similar issue where invoking sidecar (`node`, bundled with `pkg`) command freezes whole app (running as `yarn tauri dev`).

No idea what's going on (or how to debug this), sidecar is not touching anything inside `src-tauri`.
Note: I am passing some input argumets to the sidecar.

`yarn tauri build` works as expected (testing on linux, .deb)

I've updated tauri to the latest version and now I have this issue :D

JS
```
"@tauri-apps/api": "1.0.0-beta.8" -> "1.0.2",
"@tauri-apps/cli": "1.0.0-beta.10" -> "1.0.5"
```

Rust
```
tauri-build = { version = "1.0.0-beta.4", features = [] } -> { version = "1.0.4", features = [] }
tauri = { version = "1.0.0-beta.8", features = ["api-all"] } -> { version = "1.0.5", features = ["api-all"] }
```

**Comment by FabianLars** [comment]
@mrceperka Do you have a reproduction example by any chance?

**Comment by mrceperka** [comment]
@FabianLars I will try to prepare example (can't use the actual app sadly). I will try to break existing example with sidecar :D Don't know when, but I will try.

**Comment by mrceperka** [comment]
@FabianLars I am unable to reproduce :( It might be caused by "old" react-cra starter. I will try to upgrade to the new one.

**Comment by mrceperka** [comment]
@FabianLars upgrading to react-ts starter (one with vite) solved the issue.

**Comment by lucasfernog** [comment]
@fayeed can you share a reproduction example?

**Comment by fayeed** [comment]
@lucasfernog when I tried reproducing this in a fresh project I didn't see the same error so it seems like what @mrceperka said about the old react-cra being the problem seems like cause.

**Comment by pascalbreuninger** [comment]
maybe this helps someone in the future:
Make sure your sidecar binary name is not the same as your application 😄🤦

**Comment by trymbill** [comment]
> maybe this helps someone in the future: Make sure your sidecar binary name is not the same as your application 😄🤦

Well, you just saved me a few more hours of banging my head on the table trying to figure this out. Thank you! 😅
