### ISSUE TITLE
[bug] unexpected title when use set_title on Windows 7

### ISSUE THREAD

**Issue by rming** [tauri-apps/tauri#4966]
### Describe the bug

![tray_menu](https://user-images.githubusercontent.com/1621419/185102169-421266e1-2d1d-4141-b73d-70cea0935418.PNG)

```
capture.set_title("Screenshot").unwrap();
choose_file.set_title("Select file").unwrap();
show_main_window.set_title("Show main window").unwrap();
show_quick_window.set_title("Show quick window").unwrap();
settings.set_title("Settings").unwrap();
quit.set_title("Quit").unwrap();

```
### Reproduction

Run production on Windows 7, set_title via command in js, maybe related https://github.com/tauri-apps/tauri/issues/3642

### Platform and versions

Environment
  › OS: Mac OS 12.3.1 X64
  › Node.js: 16.14.0
  › npm: 8.13.2
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.0,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: img-src 'self' data: https:; default-src blob: data: filesystem: tauri: 'unsafe-eval' 'unsafe-inline' 'self'; script-src 'unsafe-eval' 'self' blob:
  › distDir: ../dist
  › devPath: http://127.0.0.1:8080/
  › framework: Vue.js (Vue CLI)
  › bundler: Webpack

App directory structure
  ├─ patches
  ├─ node_modules
  ├─ updater
  ├─ public
  ├─ scripts
  ├─ .github
  ├─ src-tauri
  ├─ .git
  ├─ tmp
  └─ src
✨  Done in 8.12s.

**Comment by amrbashir** [comment]
It souldn't be related to https://github.com/tauri-apps/tauri/issues/3642 since that was about missing null character at the end so Windows reached out to some memory beyond expected.

can you provide a minimal repro? I need to test with the same repo that had the issue.

**Comment by rming** [comment]
@amrbashir  try [rming/tauri-tray-menu](https://github.com/rming/tauri-tray-menu) or download msi from [release]( https://github.com/rming/tauri-tray-menu/releases/tag/1.0)

**Comment by amrbashir** [comment]
does this bug only happens on win7? or on win 8 and higher too?

**Comment by rming** [comment]
> does this bug only happens on win7? or on win 8 and higher too?

Only win7, it's normal on win10, not test on win8.

**Comment by rming** [comment]
Confirmed no problem on win8.1

**Comment by amrbashir** [comment]
Same results as my testings, I tried different variations and different win32 APIs to see if any of them would work but they all failed. At this point, I think I would be wasting my time trying to fix it, since I can't find anything related to this in MSDN and Microsoft has ended Win 7 support for 3 years now.

I will leave this issue open in case someone is able to fix it.
