### ISSUE TITLE
[bug] can't run shell/Command Api, it's program not found

### ISSUE THREAD

**Issue by codingJJJ** [tauri-apps/tauri#4969]
### Describe the bug

i can't resove my bug when i'm getting start a tauri app and useing shell api.
this is my tauri config info
![image](https://user-images.githubusercontent.com/81680241/185238367-59099013-0ba7-499e-be95-c6118e73c52f.png)

my code here
![image](https://user-images.githubusercontent.com/81680241/185238491-d21e521b-d375-419f-bcdb-59250b07aa13.png)

i found this error in devTool when i run tauri dev
![image](https://user-images.githubusercontent.com/81680241/185238682-01841e34-3c40-4a68-860a-d5dfd109d3be.png)

thanks
I think this may be a very simple bug, but I haven't solved it for a long time. I hope handsome brother can help me!

### Expected behavior

![image](https://user-images.githubusercontent.com/81680241/185237861-b7384c1f-cdaf-4c9a-b7db-3ed0bf675450.png)

### Platform and versions

Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 104.0.1293.54
  › MSVC:
  › Node.js: 16.13.1
  › npm: 8.1.2
  › pnpm: 7.3.0
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.62.0
  › cargo: 1.62.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,

**Comment by FabianLars** [comment]
Unlike on Unix systems, on Windows "commands" like `echo` are no separate programs/binaries and only work inside a terminal. (they do have a special name, but i can't remember it)

In other words, instead of `Command::new("echo")`, you'll need `Command::new("cmd").args(["/C", "echo hello"])` _on windows_ (works on linux too, with `sh -c` instead of `cmd /C`, but there it's not needed) and of course you need to adapt the allowlist accordingly.

**Comment by codingJJJ** [comment]
> 
thanks,this requst maybe windows styterm environment, I'm try to resolve again with your method,but found the Encode Error like this.
![image](https://user-images.githubusercontent.com/81680241/185284668-8b4b2f4e-3966-4d8c-a04c-34e9b9fafc88.png)

![image](https://user-images.githubusercontent.com/81680241/185283296-a8c36e4a-e78a-4b2d-b5a5-75f4070c5e04.png)

However, this question makes me as a developer very confused, can @tauri/apps/shell Command API be compatible with windows at the framework level, makes the Command  makes the Command  API called easy,this is just my little suggestion, but thanks very much for your answer!

**Comment by zjprie094** [comment]
你的写法可能有问题，改成这样试试
```
{
   "scope": [
        {
            "name": "cmd",
            "cmd": "cmd",
            "args": true
          }
      ]
}
```
