### ISSUE TITLE
[feat] Option for native titlebar buttons

### ISSUE THREAD

**Issue by Jasenkoo** [tauri-apps/tauri#4973]
### Describe the problem

It would be really nice to have an option like [`titlebarOverlay`](https://www.electronjs.org/docs/latest/tutorial/window-customization#window-controls-overlay-macos-windows) option in electron. 

While we can create a custom titlebar, since win 11, there is an option for a quick snap layout as described [here](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/apply-snap-layout-menu).

This way we can still make a custom titlebar while keeping the native buttons.

### Describe the solution you'd like

Either via plugin, or `window` configuration.

### Alternatives considered

None

### Additional context

None

**Comment by FabianLars** [comment]
This is covered by #2663, even though the discussion was primarily about macos, but that's only because it's much more of a problem there.

Though i _think_ we'll introduce Windows support slightly different, at least in the first iteration. So instead of a whole titlebar we'll just offer a way to make an element by choice react to this https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/apply-snap-layout-menu#how-do-i-fix-it, but we'll see 🤷 

Thanks for the FR!

**Comment by Jasenkoo** [comment]
>  So instead of a whole titlebar we'll just offer a way to make an element by choice react to this

Even better

**Comment by MulverineX** [comment]
@FabianLars ideally Windows would get better support than that, as building your own **accurate** titlebar is difficult. Themeable and/or button overlay would be ideal.

**Comment by FabianLars** [comment]
@MulverineX It's not like we don't want to, the problem is that Windows doesn't have similar APIs (to our knowledge at least - i'd love to be proven wrong here).

**Comment by MulverineX** [comment]
@FabianLars https://github.com/electron/electron/pull/33066 .  I had commented this on #2663

**Comment by FabianLars** [comment]
@MulverineX Yep i saw that, but if we take a look at the PR where WOC itself was implemented: https://github.com/electron/electron/pull/29600/files it shows that it's insanely complicated as it's draws the controls completely manually. The main problem with that is that we don't draw _anything_ manually in our libraries so we don't have anything we could build upon, therefore i think this way is not feasible for us.

p.s. i know that chromium itself implemented WCO recently (v102 or something?), but i don't see any way to activate or control it in WebView2 :/

**Comment by MulverineX** [comment]
@FabianLars damn, I thought the Electron team had found a proper system API for it :/. Guess that doesn't really exist, that's disappointing. Well, hopefully, it roles out to webview2 eventually. Thanks for elaborating.
