### ISSUE TITLE
Backend async/await event support. 

### ISSUE THREAD

**Issue by SuanCaiYv** [tauri-apps/tauri#4977]
### Describe the problem

when use window.emit()/listen() to interact with my async api, I had to rewrite my whole api to fit the block event.

### Describe the solution you'd like

So it's the anyway to call xxx().await in window.emit()/listen()? And use async runtime such as Tokio?

**Comment by FabianLars** [comment]
You can use the functions provided by [`tauri::async_runtime`](https://docs.rs/tauri/latest/tauri/async_runtime/index.html), example:
```rs
window.listen("my-event", |event| {
  tauri::async_runtime::block_on(reqwest::get("https://google.com"));

  tauri::async_runtime::block_on(async move { reqwest::get("https://google.com").await; });
})
```

**Comment by SuanCaiYv** [comment]
O, thanks you! I will try it 😃

**Comment by cadomani** [comment]
> You can use the functions provided by [`tauri::async_runtime`](https://docs.rs/tauri/latest/tauri/async_runtime/index.html), example:
> 
> ```rust
> window.listen("my-event", |event| {
>   tauri::async_runtime::block_on(reqwest::get("https://google.com"));
> 
>   tauri::async_runtime::block_on(async move { reqwest::get("https://google.com").await; });
> })
> ```

When trying to use the async_runtime::block_on method in my run method on the builder, I get an error (tauri v2):
```rust
#[tokio::main]
async fn main() {
    tauri::async_runtime::set(tokio::runtime::Handle::current());
    tauri::Builder::default()
        // Typical stuff here
        .build(tauri::generate_context!())
        .expect("error while running tauri application")
        .run(|app, event| match event {
            tauri::RunEvent::WindowEvent {
                event: tauri::WindowEvent::CloseRequested { .. },
                ..
            } => {
                println!("Received exit signal. Killing all processes...");
                tauri::async_runtime::block_on(async {
                    handle_exit(app).await;
                });
            }
            _ => {}
        });
    Ok(())
}
```

This is the error I get:
```bash
Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.
```

I've seen places where you say to take off the tokio main bit, but I am doing some stuff in this main method that are async I need to leave but can't show because this is a work project. So, removing the tokio::main from the main method is not possible for me. I thought setting the runtime was a viable alternative to this.

Is there anything I can do to fix this?

**Comment by FabianLars** [comment]
@cadomani 

> So, removing the tokio::main from the main method is not possible for me

Technically it's still possible because you can use tauri's block_on and spawn where you currently use `.await`.

Alternatively i think you can wrap `block_on` in `tokio::task::block_in_place`
