### ISSUE TITLE
[bug] Event Listener's "event.repeat" doesn't work

### ISSUE THREAD

**Issue by Allofron-Mastiga** [tauri-apps/tauri#4978]
### Describe the bug

"event.repeat" never triggers on "keydown" event listener. The listener has been added to the window and the code has been tested on multiple browsers and works reliably. Repeated keydown events seem to act exactly like initial keypress and aren't filtered out.

### Reproduction

1. do ".addEventListener("keydown", (event) => {})" on any element where applicable
2. check for "event.repeat" status either by logging it or using it in an if statement

### Expected behavior

The repeated key triggers should toggle event.repeat to true, allowing them to be treated differently.

### Platform and versions

$ tauri info

Environment
  › OS: Manjaro 21.3.7 X64
  › Node.js: 18.7.0
  › npm: Not installed!
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: ../dist

App directory structure
  ├─ dist
  ├─ src-tauri
  └─ node_modules

**Comment by Moon1102** [comment]
When I test with the input or button element, I can see `event.repeat  === true`

env:
```
Environment
  › OS: Mac OS 11.4.0 X64
  › Node.js: 17.0.1
  › npm: 8.1.0
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-aarch64-apple-darwin 
```

section of code: 
```
<script setup lang="ts">
onMounted(() => {
  const element = document.getElementById('test');
  //if you test with button element, focus it at first, you can see the same output 
  //element?.focus()
  element?.addEventListener("keydown", (event) => {
    console.error(event , `event.repeat: ${event.repeat}`);
  })
})
</script>

<template>
 <input id="test" />
 //<button id="test"><button>
</template>
```

result:
<img width="797" alt="图片" src="https://user-images.githubusercontent.com/15380331/186077750-b84aa11a-831a-473d-afc9-0fd1b94f6056.png">

**Comment by JonasKruckenberg** [comment]
@Allofron-Mastiga Does this work in Epiphany? Or any other browser like Firefox or Brave?

This feature is supported in webkit forever now, so shouldn't really be a problem with Tauri, but maybe the keyboard events on your Linux distro maybe?

**Comment by Allofron-Mastiga** [comment]
@JonasKruckenberg I've tested on Firefox and Chromium with no issues. The problem only ever occurred in Tauri. Might be the distro but not sure why it would behave inconsistently like that between webapp and browser. Unfortunately can't test on Windows or mac and have abandoned Tauri due to some other details.

I guess for anyone else encountering this it's an easy fix to store first key press manually and check against that, that's gonna behave as expected anywhere.

**Comment by FabianLars** [comment]
On my Linux machine this doesn't work in Firefox nor epiphany (=webkitgtk, therefore Tauri), only in Chrome :thinking:
