### ISSUE TITLE
Event API - Nothing

### ISSUE THREAD

**Issue by tcastelly** [tauri-apps/tauri#498]
I'm looking to catch an event on rust [using the API](https://github.com/tauri-apps/tauri/wiki/11.-API), no error, nothing

I emit an event when I click on a link (eventToRust)
![image](https://user-images.githubusercontent.com/37597737/76169980-0112bc00-617e-11ea-82b2-5a884e92a3c5.png)

OS: Darwin(19.3.0) - darwin/x64
Node: 12.16.1
tauri.js - 0.4.3
Rustc: 1.39.0

**Comment by nothingismagick** [comment]
If you don't attach a value to the JS emit, it won't work. Try this:
```
      tauri.emit('hello', 'A message');
```

But you're right, we should be better about propagating errors - and documenting this.

**Comment by lucasfernog** [comment]
I'm planning on fixing this on my API PR.

**Comment by tcastelly** [comment]
Thanks for your help.
Unfortunately I have the same behaviour with or without attached value. I can print something in the setup (main.rs). But no events are catch.

**Comment by tcastelly** [comment]
Sorry, maybe I let you close if you want update the documentation.

**Comment by lucasfernog** [comment]
@tcastelly Can you paste here your JS/Rust code? I'd like to try it, because it should work even without the parameter (because we're changing it to an empty string).

**Comment by tcastelly** [comment]
Finally I can reproduce.
Everything works with or without arguments. But If I reload the application with a right click > reload. It's broken.

**Comment by lucasfernog** [comment]
I assume that's when you're running `tauri dev` right? We rely on dropping a `tauri.js` script when the app launches, and right now we can't know when the webview is reloaded.

**Comment by tcastelly** [comment]
I use `yarn run tauri:serve` from vue-cli-plugin-tauri. So yes I guess it's `tauri dev`.
So there si no problem :), thank you for your help!
