### ISSUE TITLE
[feat] Is it possible to conditionally open dev-tools in production mode

### ISSUE THREAD

**Issue by Moon1102** [tauri-apps/tauri#4981]
### Describe the problem

Some problems are too difficult to locate without dev-tools. 

For example but not limited to:
1. The pictures are not displayed because of the wrong path is dynamically set in the production mode.

2. When the map is introduced,it is displayed in development mode but not displayed in production mode (very confused😢. google map is ok but baidumap fail. I'll try amap later)

3. CSP is configured incorrectly (didn't realize this at beginning but It is also one of the possible reasons why the picture is not displayed)

### Describe the solution you'd like

By adding startup parameters or startup password, or simply let the developer be responsible for whether to open dev tools

**Comment by amrbashir** [comment]
yes, add `devtools` feature flag in your `Cargo.toml` and call `window.open_devtools` whenever you want

**Comment by amrbashir** [comment]
you can also build a debug version of you app `tauri build --debug` which will builds your app in production mode but keeps access to some debug features including devtools
