### ISSUE TITLE
[feat] Custom URL Scheme

### ISSUE THREAD

**Issue by loicortola** [tauri-apps/tauri#5001]
### Describe the problem

Hello everyone,

first, thanks for the great product. Tauri might still be fresh-paint, but the product is beautiful and I can't wait to move away from Electron. Great job!

Right now, we are working on an app using Firebase and OAuth, and are obviously experiencing problems with Authentication flows. Another of our needs for the same app is to pass context between a website and the desktop app.

For the latter, the dream is to click on a button on the website which would open (or reuse existing window) the app and pass on the context in a callback dedicated to receiving such context info.

I see Custom URL Scheme registration as the unique possibility of doing this, and I dug a little in the issue history and found I wasn't alone:

https://github.com/tauri-apps/tauri/issues/323

https://github.com/tauri-apps/tauri/issues/1421

I see you guys were hoping to implement this by RC, and I just wanted to ask if you had any updates regarding this?

As for the use-case, consider that it's a big +1 on "I'd love this built into the product".

Let me know if I can provide you with any more details regarding the use-case.

Best,

Loïc

### Describe the solution you'd like

 * A way to declare in the configuration a custom url scheme which would be registered within the OS, associating the url scheme with the app
 * An API to declare a callback able to handle any external request coming from a browser for instance 

### Alternatives considered

Copy-paste of contextual data (which is the only way of doing so right now)

**Comment by amrbashir** [comment]
please follow https://github.com/tauri-apps/tauri/issues/323 for updates, no need to have duplicates
