### ISSUE TITLE
[feat] Creating a new empty file

### ISSUE THREAD

**Issue by seahindeniz** [tauri-apps/tauri#5006]
### Describe the problem

I'm using `writeTextFile` to write a content into a file, but it doesn't create a new file when the targeted file doesn't exist, and it returns `No such file or directory (os error 2)`

```ts
await writeTextFile('~/test.txt', newContent);
```

### Describe the solution you'd like

I would like to be able to pass a new option to the third argument of `writeTextFile` and expect it to create a new file when it doesn't exist instead of throwing an error

### Alternatives considered

I have considered using a shell command to create a new file but as you know, there's OS differences

**Comment by FabianLars** [comment]
I think the actual problem here is the `~` which tauri can't convert to the actual path. You can use BaseDirectory.Home instead like this
```ts
await writeTextFile('test.txt', newContent, {dir: BaseDirectory.Home});
```

**Comment by ManeraKai** [comment]
I have it just like this and it's not working:
`Unhandled Promise Rejection: path: /home/esmail/.config/com.tauri.dev/logs/test.txt: No such file or directory (os error 2)`
```js
const fs = window.__TAURI__.fs;
await fs.writeTextFile(`test.txt`, 'some words', { dir: fs.BaseDirectory.Log })
```
I'm using Linux Kubuntu LTS
