### ISSUE TITLE
[bug] CSS: `user-select` not work

### ISSUE THREAD

**Issue by zyxkad** [tauri-apps/tauri#5016]
### Describe the bug

I have this code below:
```html
<div class="logo">
 <img src="/logo.png"/>
</div>
```
```css
.logo img{
  user-select: none;
}
```

I try to use `user-select` to avoid user select the logo images, but it's not work on both debug and release mode.  
It works fine on another web browsers.

### Platform and versions

Environment
  › OS: Mac OS 12.1.0 X64
  › Node.js: 18.7.0
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ./omm-front/dist/
  › devPath: http://127.0.0.1:13280/
  › framework: Vue.js

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ .git
  └─ src

**Comment by Moon1102** [comment]
@zyxkad 

It's not Tauri's bug. 👀 You should add ```-webkit-user-select: none``` under MacOS. 
BTW, to support Firefox and IE / edge, maybe you need add them too.
```
 -moz-user-select: none;
 -ms-user-select: none;
```
