### ISSUE TITLE
[feat] Add an option for run `bundle_dmg.sh`

### ISSUE THREAD

**Issue by zyxkad** [tauri-apps/tauri#5017]
### Describe the problem

I'm using tauri on MacOS, when I do `cargo tauri build` or `cargo-tauri build`, it will output an `.app` and a `.dmg`.  
But this command always open the `.dmg` file after build, it's not good for auto build, then I need a flag to disable it.

### Describe the solution you'd like

Add an option flag `-N` _(or any other flag)_ to disable open `dmg` file at the end

### Alternatives considered

Do **not** always open the `dmg` file after build, use a flag _(like `--run` or `--open`)_ to explicitly open the `dmg`

**Comment by lucasfernog** [comment]
It does not open the DMG automatically, though it uses applescript so a window pops up. To disable it, you can set the `CI` environment variable to `true`.
