### ISSUE TITLE
[Help] Sidecar command.stdout.on('data', () => {...}) not working

### ISSUE THREAD

**Issue by pickaxe828** [tauri-apps/tauri#5022]
## Problem:
I have a Python application built to an .exe (pyinstaller)
It `print` json as `string`s to the terminal when done processing an image ([here](https://github.com/pickaxe828/rmbg/blob/8670b02b4b8f7d8cc2977316e96dc2b806dca732/py-src/_rembg.py#L49))
It works fine in the terminal, prints one line of `json` as string when one image is done processing

But when it works as a sidecar, and when I use `command.stdout.on('data', line => console.log)` ([here](https://github.com/pickaxe828/rmbg/blob/8670b02b4b8f7d8cc2977316e96dc2b806dca732/src/main.ts#L35))
It logs nothing to the console when it is running
And when the `.exe` process ends
The tauri app suddenly logs all the json strings that should be logged before, to the console all at once

When it's running: Not logging the things I want
![](https://cdn.discordapp.com/attachments/1011697717875069050/1011699058232000582/unknown.png)

Done running: (suddenly logging all the things I want)
![](https://cdn.discordapp.com/attachments/1011697717875069050/1011699132529901629/unknown.png)

## Info: `tauri info`:
```powershell
Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 104.0.1293.63
  › MSVC: 
      - Visual Studio Build Tools 2019
      - Visual Studio Build Tools 2022
  › Node.js: 18.7.0
  › npm: 8.15.0
  › pnpm: 6.11.5
  › yarn: 1.22.18
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/

App directory structure
  ├─ .git
  ├─ build
  ├─ node_modules
  ├─ public
  ├─ py-src
  ├─ src
  ├─ src-tauri
  └─ test_set
```

**Comment by lucasfernog** [comment]
In my tests I had the same problem when running directly in the terminal. You need to flush the stdout buffer when printing, so instead of `print(message)` you call `print(message, flush = True)`.

**Comment by pickaxe828** [comment]
> In my tests I had the same problem when running directly in the terminal. You need to flush the stdout buffer when printing, so instead of `print(message)` you call `print(message, flush = True)`.

I added it to all of my prints and the strange behaviour is still there.
I even tried changing all the `print` to `sys.stdout.write` then `flush`
Rebuilt and it's still the same
