### ISSUE TITLE
[feat] Make Window Title Available in appWindow Instance

### ISSUE THREAD

**Issue by samconran** [tauri-apps/tauri#5023]
### Describe the problem

It's tricky when making custom title bars for a window—or trying to update the window title with something based on the current title—to actually pin down in code what the current title is.

### Describe the solution you'd like

On the `appWindow` level, we have the ability to call `appWindow.setTitle("...")`. It would be good if we could get a reference to the current title here as well. A property of `appWindow.title` would probably be best, but exposing it through `appWindow.getTitle()` would also work fine.

**Comment by elibroftw** [comment]
Is this in the latest version of tauri? I'm getting a `Uncaught TypeError: appWindow.title is not a function`

**Comment by elibroftw** [comment]
The latest https://www.npmjs.com/package/@tauri-apps/api, is not 1.2.3 :(, it's been 3 months.

**Comment by FabianLars** [comment]
1.3 is currently in internal audit so it hopefully shouldn't take _much_ longer to get your hands on it.
