### ISSUE TITLE
[bug] Memory usage and binary size (Linux)

### ISSUE THREAD

**Issue by RubenKelevra** [tauri-apps/tauri#5031]
### Describe the bug

The current two methods of bundling: AppImage and Deb, both produce a binary size of around **18 MB**. (That's a multiple of the size claimed in the Readme of **"3.1 MB"**)

If I run a tauri instance which shows a simple webview of an https website it will use a considerable amount of memory: Used memory increases (just as an example) from 7.8 GB to 8.3 GB – so around **500 MB**. That's considerable more than the claimed **"180 MB"** in the Readme.

Starting the same tauri app twice will consume twice the amount of memory – so there are no shared libraries in use which would reduce the amount of used memory on more than one tauri app.

### Reproduction

1. Create a webapp
2. Bundle it
3. observe a large binary size

1. Start the binary
2. observe a large memory consumption

### Expected behavior

The quoted numbers in the Readme should be met or changed.

### Platform and versions

```console
$ cargo tauri info

Environment
  › OS: EndeavourOS Rolling Release X64
  › Node.js: 16.16.0
  › npm: 8.18.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: Not installed!
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
```

**Comment by amrbashir** [comment]
The comparison table has been now removed.
