### ISSUE TITLE
[bug] GPU No hardware acceleration for canvas

### ISSUE THREAD

**Issue by Jinx-1120** [tauri-apps/tauri#5037]
### Describe the bug

I use Canvas to show a video, but the actual effect is not smooth, but it works normally under the Web;

I saw [4891](https://github.com/tauri-apps/tauri/issues/4891) and configured it according to the solution, but it doesn't seem to work for me. I don't know whether there is a problem with my configuration;

### Platform and versions

Environment
  › OS: Mac OS 12.5.0 X64
  › Node.js: 14.18.2
  › npm: 6.14.15
  › pnpm: 7.1.9
  › yarn: 1.22.17
  › rustup: 1.25.0
  › rustc: 1.62.0
  › cargo: 1.62.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › framework: React

App directory structure
  ├─ .husky
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  └─ src

**Comment by Jinx-1120** [comment]
Would anyone like to help me with this question? 👀

**Comment by FabianLars** [comment]
Can/Did you try it in Safari?

p.s. the issue&solution from 4891 is windows-only

**Comment by Jinx-1120** [comment]
It's the same thing in Safari

**Comment by Jinx-1120** [comment]
This seems to be Safari's problem. Is there a way to solve this problem?

**Comment by FabianLars** [comment]
> Is there a way to solve this problem?

Not really. Unless there is a different approach you can use than the video-in-canvas thing you're doing right now :/
Other than that it's on apple (or the webkit/safari devs) to improve this :(

**Comment by nothingismagick** [comment]
The only thing I can think of is that your GPU is generally off:

https://support.apple.com/en-us/HT202043

**Comment by nothingismagick** [comment]
Or potentially this:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/35242872/187185015-e2b5bd6d-f6a6-4672-9356-616b095517a1.png">

**Comment by Jinx-1120** [comment]
Thank you very much for @Nothingismagick @Fabianlars to reply. I checked the settings of Safari and the graphic card settings in the battery.They look correct, but my project is still not smooth

I tried to run this project on the M1Max machine yesterday, which can work normally.And web can run smoothly under Safari.

It seems to be an Apple problem

I will try to run this project under other MACs to view the effect
