### ISSUE TITLE
[bug][macOS] `getUserMedia` not work on release mode

### ISSUE THREAD

**Issue by mantou132** [tauri-apps/tauri#5039]
### Describe the bug

`getUserMedia` no permission prompt will pop up, promise will not succeed or fail

### Reproduction

1. clone https://github.com/mantou132/tauri-app-test
2. checkout branch to `get-user-media`
3. cargo tauri build
4. run app
5. click get user media button

### Expected behavior

Get user media succee

### Platform and versions

Environment
  › OS: Mac OS 12.5.1 X64
  › Node.js: 18.3.0
  › npm: 8.11.0
  › pnpm: 6.11.0
  › yarn: 1.22.15
  › rustup: 1.24.3
  › rustc: 1.64.0-nightly
  › cargo: 1.64.0-nightly
  › Rust toolchain: nightly-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: ../dist

App directory structure
  ├─ dist
  ├─ src-tauri
  └─ .git

tauri updating to the latest version doesn't help either

### Additional context

<img width="912" alt="Screen Shot 2022-08-25 at 21 06 33" src="https://user-images.githubusercontent.com/3841872/186672910-45991d10-7022-4983-9efd-c686396365a3.png">

**Comment by mantou132** [comment]
The code behind `getUserMedia` will not execute

**Comment by FabianLars** [comment]
Did you add a `Info.plist` file with these contents? https://github.com/tauri-apps/tauri/blob/dev/examples/api/src-tauri/Info.plist

Edit: whoops didn't see that you linked a repo, sorry! And yes, you're missing this file, so please try it again after adding it.

**Comment by mantou132** [comment]
I tried it, but there will be two permissions requests. If this meets expectations, I will close the issue
