### ISSUE TITLE
[bug] How to use websocket ws protocol in release mode?

### ISSUE THREAD

**Issue by Richyeoh** [tauri-apps/tauri#5040]
### Describe the bug

Mixed Content: The page at 'https://tauri.localhost/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://test.emqx.io:8083/mqtt'. This request has been blocked; this endpoint must be available over WSS.

### Platform and versions

Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 104.0.1293.63
  › MSVC: 
      - Visual Studio ���ɹ��� 2022
  › Node.js: 16.15.1
  › npm: 8.15.1
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  › distDir: ../dist
  › devPath: http://127.0.0.1:1420/
  › framework: Vue.js

App directory structure
  ├─ .vscode
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri

### Stack trace

```shell
Mixed Content: The page at 'https://tauri.localhost/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://test.emqx.io:8083/mqtt'. This request has been blocked; this endpoint must be available over WSS.
```

**Comment by TooYoungTooSimp** [comment]
Related to #3007 ,current solution is to make use of tauri-apps/tauri-plugin-localhost .
If your window is loading in HTTP, then it can make `ws://` requests.
