### ISSUE TITLE
$APP base directory does not exists.

### ISSUE THREAD

**Issue by EnrickyHip** [tauri-apps/tauri#5048]
I'm trying to read and write files in the $APP base directory (appDir), but the specified directory "C:\Users\<user>\AppData\Roaming\<identifier>" does not exists on my system (windows). Should Tauri have auto generate it or I have to create it manually?

**Comment by FabianLars** [comment]
You have to create it yourself :)

**Comment by amrbashir** [comment]
You should generate

**Comment by EnrickyHip** [comment]
alright, thanks!
