### ISSUE TITLE
[bug] Tauri only open a default port in development

### ISSUE THREAD

**Issue by AsaoluElijah** [tauri-apps/tauri#5049]
### Describe the bug

I created a new Tauri app, using create-react-app(JavaScript) as my preferred recipe, and additionally, i have one react app already running before [on http://localhost:3000/]. So, when i run the `npm run tauri dev` comman for my new project. Tauri opens my previous app that's running on port _3000_, and not the intended app.

I suppose this is because the default `devPath` in the tauri.config.json file is set to this url.

### Reproduction

1. Have an existing app running on http://localhost:3000/
2. Create new tauri app, choosing create-react-app(JavaScript) as preferred recipe.
3. Run new tauri app

### Expected behavior

Tauri should run app on expected port.

### Platform and versions

* OS - MacOs Montery v12.2.1
* Tauri version:
```json
  "dependencies": {
    "@tauri-apps/api": "^1.0.2",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^13.5.0",
    . . .
```

**Comment by amrbashir** [comment]
`create-tauri-app` has new templates now with different ports. This is not considered a bug and you can just change `devPath` in tauri.conf.json to the url you want.
