### ISSUE TITLE
[feat] Allow building of MacOS apps without installing .dmg

### ISSUE THREAD

**Issue by vivekagate** [tauri-apps/tauri#5062]
### Describe the problem

Currently, when I build the macos app using `yarn tauri build`, it completes the build by installing the .dmg
This works well when I have sudo access.

I am trying to build the macos for Apple Silicon M1 using macincloud.com where I do not have sudo access. The builds fail in these boxes.

### Describe the solution you'd like

Allow a flag that allows skipping the "installation of .dmg".

### Alternatives considered

Alternative is to buy next plan of macincloud.com that gives sudo access which I would like to avoid if possible.
The other alternative is to buy a macmini for my mac builds.

**Comment by glen0125** [comment]
I have the same problem. How to fix this?

**Comment by lockieluke** [comment]
Is there a flag to skip DMG building

**Comment by FabianLars** [comment]
To set it permanently specify the targets you _do_ want here: https://tauri.app/v1/api/config#bundleconfig.targets
Or temporarily via the cli: `tauri build -b app` (this tells tauri to only build the app bundle) - note that it needs an extra -- if you use npm: `npm run tauri build -- -b app`

**Comment by lockieluke** [comment]
Bun >>

**Comment by FabianLars** [comment]
Apart from skipping the .dmg completely, can you also try the `CI: true` env var? This will make the dmg "ugly" like in https://github.com/tauri-apps/tauri-action/issues/740 but at least it should build fine.
