### ISSUE TITLE
[bug] thread 'tokio-runtime-worker' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.

### ISSUE THREAD

**Issue by AHGFI** [tauri-apps/tauri#5068]
### Describe the bug

async main invoke_handler  use async fn   thread 'tokio-runtime-worker' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.

![image](https://user-images.githubusercontent.com/112101787/187033934-a1883422-2e57-4ce2-b791-7d2258964ef5.png)
![image](https://user-images.githubusercontent.com/112101787/187033956-fd3a6737-3b16-4e00-978a-b9cbc85f5f93.png)
![image](https://user-images.githubusercontent.com/112101787/187034105-b80cca5d-db56-4e5b-a0c9-094eb2958cc3.png)

### Platform and versions

› OS: Windows 10.0.22000 X64
  › Webview2: 104.0.1293.70
  › MSVC:
  › Node.js: 16.17.0
  › npm: 8.18.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

**Comment by FabianLars** [comment]
The problem should be _inside_ the async command, not the command itself. Can you share more of your code?
Also it's _supposed_ to tell you the exact line where the issue comes from too (sometimes behind the `RUST_BACKTRACE=1` env var), but errors/panics in async rust can get quite weird. Anyway, we need more code (of the get_survival_addr command) to help you.

**Comment by AHGFI** [comment]
Thank you. It should be the following line of code
![image](https://user-images.githubusercontent.com/112101787/187070996-56ddb489-df15-4a65-ae78-f56638af6068.png)
![image](https://user-images.githubusercontent.com/112101787/187071008-70bce198-1400-4b96-a03e-f46b86a4c6fc.png)

**Comment by AHGFI** [comment]
trust-dns-resolver = "0.21.2"

**Comment by AHGFI** [comment]
trust-dns-resolver
