### ISSUE TITLE
Public folder

### ISSUE THREAD

**Issue by erikpa1** [tauri-apps/tauri#5074]
### Describe the problem

Hi, I have  static web app, which can have more than 20 GB (its deployed on azure storage which enables to create web static web apps of 5TB size, so yes, its possible, its panorama photos viewer, where panoramas has 20GB), which I would like to deploy as desktop app with tauri, but it could be nice to not rewrite whole application for tauri fs.

### Describe the solution you'd like

It could be nice to have public folder, like react has, just by .exe file and when I fetch something and its not packed in binary app should search in this folder.

It could be really nice feature which **don't require rewrite my existing app** and create some magic class which will switch between tauri and web integration.

**Comment by JonasKruckenberg** [comment]
See my latest commit on your question [here](https://github.com/tauri-apps/tauri/discussions/5045#discussioncomment-3498499). We will not add this as an explicit feature, but the assets protocol can do what you want.
