### ISSUE TITLE
[bug] passing command-line arguments to `yarn tauri dev` are passed to cargo, not the application

### ISSUE THREAD

**Issue by Sergix** [tauri-apps/tauri#5079]
### Describe the bug

https://github.com/tauri-apps/tauri/issues/1406 describes how to pass command-line arguments to your application in a development environment for testing using `yarn tauri dev -- [args]`. However, when attempting to pass command line arguments to `yarn tauri dev`, `cargo build` captures the arguments and terminates the environment launch.

### Reproduction

1. `yarn tauri dev -- test123` or `cargo-tauri dev -- test123` or `cargo tauri dev -- test123`
2. `cargo build` incorrectly captures the arguments

### Expected behavior

The arguments should be passed to the Tauri application and not captured by cargo.

### OS
- Windows
- Linux-based distros

### Command line environments
- PowerShell
- cmd.exe
- git-bash
- bash

### Commands
- `yarn tauri dev -- test123`
- `cargo-tauri dev -- test123`
- `cargo tauri dev -- test123`

### Versions
yarn 1.22.19
yarn-run-tauri 1.0.5
tauri-cli 1.0.5
cargo-tauri 1.0.5
rustc 1.63.0 (4b91a6ea7 2022-08-08)

### Stack trace

```shell
PS C:\Users\sergix\dev\cps310\cps310-simulator-Sergix> yarn tauri dev -- test123
yarn run v1.22.19
$ [redacted]\node_modules\.bin\tauri dev test123
     Running BeforeDevCommand (`yarn start`)
        Info Watching [redacted]\src-tauri for changes...
error: Found argument 'test123' which wasn't expected, or isn't valid in this context

USAGE:
    cargo.exe build [OPTIONS]  

For more information try --help
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Additional context

It would be helpful for the Tauri docs to be more clear on this behavior since nothing about passing arguments is listed on [the CLI docs page.](https://tauri.app/v1/api/cli#dev)

**Comment by lucasfernog** [comment]
This was changed this year, the arguments after the first `--` are passed to `cargo build`, and to pass it to the application you must add a second `--`, like this:

`yarn tauri dev -- -- test123`

This was introduced #3431 but I agree the documentation isn't clear, I'll update it.
