### ISSUE TITLE
[bug] web view not launched in Ubuntu

### ISSUE THREAD

**Issue by guyutongxue** [tauri-apps/tauri#5085]
### Describe the bug

While launching the app, a `Gdk-ERROR` occurred:
```
(WebKitWebProcess:119326): Gdk-ERROR **: 16:41:25.523: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 219 error_code 2 request_code 152 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

### Reproduction

1. Create a new tauri app with `pnpm create tauri-app`, choosing `pnpm` as pm and `vanilla` as ui.
2. `cd tauri-app && pnpm install`
3. `pnpm tauri dev`, and the error occured.

### Platform and versions

`pnpm tauri info`:
```
Environment
  › OS: Ubuntu 22.04 X64
  › Node.js: 16.13.1
  › npm: 8.8.0
  › pnpm: 7.1.2
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
```

(I don't know why it stuck here.) Additional version info:
- Cargo `tauri`: 1.0.5
- Cargo `tauri-build`: 1.0.4
- Cargo `tao`: 0.12.2
- Cargo `wry`: 0.19.0

**Comment by FabianLars** [comment]
Errors like this are basically impossible to debug (for us/me) tbh, but a few questions anyway:
- WSL or an actual Linux installation?
- What GPU are you using?
- If AMD: Are you using the open-source drivers (that are part of the kernel) or amdgpu-pro?
- Are all your system dependencies up-to-date?

_Edit:_ Another thing i saw on the internet, can you try setting this env var: `WEBKIT_FORCE_SANDBOX=0` ? Probably doesn't work but worth a try :/

**Comment by guyutongxue** [comment]
> Errors like this are basically impossible to debug (for us/me) tbh, but a few questions anyway:
> 
> * WSL or an actual Linux installation?
> * What GPU are you using?
> * If AMD: Are you using the open-source drivers (that are part of the kernel) or amdgpu-pro?
> * Are all your system dependencies up-to-date?
> 
> _Edit:_ Another thing i saw on the internet, can you try setting this env var: `WEBKIT_FORCE_SANDBOX=0` ? Probably doesn't work but worth a try :/

Oops, after some `apt update` and reboot, it works now.

Anyway, the detailed info are:
- Actual Linux in physical machine
- Nvidia w/ driver 510.85.02
- Not up-to-date at that moment
