### ISSUE TITLE
[feat] beforeBuildCommand/beforeDevCommand needs a target triple environment variable

### ISSUE THREAD

**Issue by WilliamVenner** [tauri-apps/tauri#5091]
### Describe the problem

beforeBuildCommand and beforeDevCommand claim to be for conditional compilation, yet offer no way of getting the target triple for building

### Describe the solution you'd like

Expose the target triple as an environment variable

**Comment by amrbashir** [comment]
did you check https://tauri.app/v1/api/config#buildconfig.beforedevcommand there is env vars for arch, platform, ..etc

**Comment by WilliamVenner** [comment]
Yes, they can't be used to build a target triple

**Comment by FabianLars** [comment]
Why not? you only need `arch` and `os` to figure out your target triple. That's of course not nearly as comfortable to use, but still not impossible.

**Comment by WilliamVenner** [comment]
`x86_64-windows-pc-msvc`

[arch] [os] [???] [toolchain]

the last two are missing

**Comment by FabianLars** [comment]
Yes they are missing, but _in the context of tauri apps_, predictable.
- windows? arch + `pc-windows-msvc`
- linux? arch + `unknown-linux-gnu`
- macos? arch + `apple-darwin`

**Comment by WilliamVenner** [comment]
But then there's the issue of concatenating these strings in a cross-platform way. Now I have to resort to a scripting language or something just to concatenate these parts into a target triple.

**Comment by FabianLars** [comment]
Yep, that's why i said it's "not _nearly_ as comfortable to use". it's a workaround not a solution, which is why this issue is still open. In other words, we/i agree that this would be a nice addition 👍
