### ISSUE TITLE
[feat] beforeBundleCommand

### ISSUE THREAD

**Issue by WilliamVenner** [tauri-apps/tauri#5092]
### Describe the problem

`tauri.bundle.externalBin` has limited usefulness in the context of Rust because there is no way to create those binaries without awful cargo hacks or nightly features

### Describe the solution you'd like

I should be able to run a command before bundle creation which will allow me to sort these things out

**Comment by lucasfernog** [comment]
Implemented in #4893, will be available in 1.1.0.
`beforeBuildCommand` can be used for this too btw.
