### ISSUE TITLE
[bug] can not access $TEMP in macOS

### ISSUE THREAD

**Issue by ruoxiaomo** [tauri-apps/tauri#5107]
### Describe the bug

<img width="874" alt="mmexport1661912248139" src="https://user-images.githubusercontent.com/44762964/187585720-d296f19f-b2d1-4793-af87-bd3c716b535e.png">

![mmexport1661912253250](https://user-images.githubusercontent.com/44762964/187585725-aa01daa0-70c9-4267-87c7-ffd08a151214.jpg)

<img width="1478" alt="mmexport1661912250899" src="https://user-images.githubusercontent.com/44762964/187585731-f604a5be-75d0-4725-ba3d-c4513910ad3c.png">

what could go wrong in this method?

### Platform and versions

Environment
  › OS: Mac OS 12.3.1 X64
  › Node.js: 14.18.0
  › npm: 6.14.15
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.3
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.3,
  › tauri-build [RUST]: 1.0.3,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: default-src 'self'; img-src 'self' asset: https://asset.localhost
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › framework: Vue.js

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  ├─ .idea
  └─ src

**Comment by amrbashir** [comment]
did you try with `$TEMP/**`?

**Comment by timleg002** [comment]
> did you try with `$TEMP/**`?

That doesn't work either
