### ISSUE TITLE
[bug] window display abnormally when the frontend dynamically changes decorations from true to false if use 'window.open_devtools()' at 'main.rs' in MacOS

### ISSUE THREAD

**Issue by Moon1102** [tauri-apps/tauri#5113]
### Describe the bug

https://user-images.githubusercontent.com/15380331/187812807-67c5e170-02c4-4eb3-b573-037b524ed410.mov

### Reproduction

[reproduction](https://github.com/Moon1102/tauri-test.git) code  is here.

run the app to see the effect.

block this code and run again is fine.
```
#[cfg(any(debug_assertions, feature = "devtools"))]
window.open_devtools();
```

### Platform and versions

MacOS v11.4 (M1)

****

Environment
  › OS: Mac OS 11.4.0 X64
  › Node.js: 17.0.1
  › npm: 8.1.0
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
       Error only one package mangager should be used, but found npm and yarn

****
Cargo.tmol

[build-dependencies]
tauri-build = { version = "1.0.4", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.5", features = ["api-all"] }

**Comment by amrbashir** [comment]
upstream issue https://github.com/tauri-apps/wry/issues/297
