### ISSUE TITLE
[bug]  requestPointerLock() is not work

### ISSUE THREAD

**Issue by XueMoMo** [tauri-apps/tauri#5118]
### Describe the bug

```` 
element.requestPointerLock()
 ````
Is not work.

### Platform and versions

Environment
  › OS: Mac OS 12.5.0 X64
  › Node.js: 16.16.0
  › npm: 8.11.0
  › pnpm: 6.12.1
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.0.4
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.4,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:33333/
  › framework: React

App directory structure
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .git
  ├─ .idea
  └─ src

**Comment by amrbashir** [comment]
upstream issue https://github.com/tauri-apps/wry/issues/445 , once it is fixed, it will land in tauri automatically
