### ISSUE TITLE
[bug] set_actionvation_policy() breaks window.show()

### ISSUE THREAD

**Issue by astoilkov** [tauri-apps/tauri#5122]
### Describe the bug

Making an app use the Accessory activation policy (`app.set_activation_policy(tauri::ActivationPolicy::Accessory);`) makes the `window.show()` method not work.

P.S. I wrote in the Discord forums and they asked me to log the issue here.

### Reproduction

main.rs:
```
fn main() {
    tauri::Builder::default()
        .setup(|app| {
            app.set_activation_policy(tauri::ActivationPolicy::Accessory);
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

tauric.conf.json:
```
"windows": [
  { "visible": false }
]
```

App.tsx (you can do it in global shortcut handler):
```
getCurrent().show();
```

### Expected behavior

The window to show.

### Platform and versions

Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 16.15.1
  › npm: 8.11.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React

App directory structure
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .vscode
  └─ src

**Comment by gaoDean** [comment]
Hello, my app uses vanilla js but calling `appWindow.show()` works fine on accessory. Perhaps it's just typescript?
