### ISSUE TITLE
macos titlebar transparent,but unmoved window

### ISSUE THREAD

**Issue by njfanxun** [tauri-apps/tauri#5125]
### Describe the bug

i want macos app titilebar and contentview mix together.like 
![image](https://user-images.githubusercontent.com/1555047/188110724-5b86723c-0025-4396-bce3-7551e1065373.png)
but this time ,window can't  drag and move.
add div with "data-tauri-drag-region",  also have a bar in my window?
how to solve this problem?

### Platform and versions

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0", features = ["api-all", "macos-private-api"] }
window-vibrancy = { version = "=0.1.3" }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24.0"
objc = "0.2.7"

**Comment by JonasKruckenberg** [comment]
Have you enabled `window > startDragging`, `window > maximize` and `window > unmaximize` in your allowlist?

**Comment by njfanxun** [comment]
> Have you enabled `window > startDragging`, `window > maximize` and `window > unmaximize` in your allowlist?

allowlist set all：true

**Comment by amrbashir** [comment]
seems like you just want https://github.com/tauri-apps/tauri/issues/2663 so I am closing this as duplicate
