### ISSUE TITLE
[bug] wrong version

### ISSUE THREAD

**Issue by liesauer** [tauri-apps/tauri#5129]
### Describe the bug

tauri doesn't read the correct version which is in `package.json`
![image](https://user-images.githubusercontent.com/8676741/188254470-dcc99308-42e6-4ba7-a6bd-50e171dcf587.png)

### Reproduction

1. `tauri.conf.json`
```json
{
  "package": {
    "version": "../package.json"
  }
}
```

2. `package.json`
```json
{
  "version": "0.1.0"
}
```

3. `yarn tauri build`
4. ![image](https://user-images.githubusercontent.com/8676741/188254470-dcc99308-42e6-4ba7-a6bd-50e171dcf587.png)

### Platform and versions

Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 104.0.1293.70
  › MSVC:
      - Visual Studio Community 2019
  › Node.js: 14.16.0
  › npm: 8.18.0
  › pnpm: 6.25.0-3
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › bundler: Webpack

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ build
  ├─ dist
  ├─ dist-build
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri

**Comment by Levminer** [comment]
That version is from src-tauri/cargo.toml version field.

**Comment by FabianLars** [comment]
Yep it is from cargo.toml and it's just cargo's build log and we can't do anything about that. As long as the app itself (the bundle file names and what the `getVersion` api returns) is correct everything works as expected.

**Comment by liesauer** [comment]
i see.
