### ISSUE TITLE
[bug] The drop-down menu of "select" item does not change the position as the application window moves

### ISSUE THREAD

**Issue by Arkinux** [tauri-apps/tauri#5135]
### Describe the bug

I run the 'Navigation' example and click “select” item to bring up the drop-down menu：
![图片](https://user-images.githubusercontent.com/12135850/188387559-041f3b31-46df-44ba-a7b5-4ce784a04ba3.png)

however, after I moved the application window, the drop-down menu remained in its original position:
![图片](https://user-images.githubusercontent.com/12135850/188388082-880b27bc-2492-40e5-a09f-e54a056ca09d.png)

### Reproduction

1、run the 'Navigation' example and click “select” item to bring up the drop-down menu：
![图片](https://user-images.githubusercontent.com/12135850/188387559-041f3b31-46df-44ba-a7b5-4ce784a04ba3.png)

2、after I moved the application window, the drop-down menu remained in its original position:
![图片](https://user-images.githubusercontent.com/12135850/188388082-880b27bc-2492-40e5-a09f-e54a056ca09d.png)

### Platform and versions

Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 105.0.1343.25
  › MSVC:
      - Visual Studio Community 2022
  › Node.js: 16.14.0
  › npm: 8.3.1
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.3
  › @tauri-apps/api [NPM]: 1.0.1 (outdated, latest: 1.0.2)
  › tauri [RUST]: 1.0.2,
  › tauri-build [RUST]: 1.0.2,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: ../dist

App directory structure
  ├─ dist
  ├─ node_modules
  └─ src-tauri

**Comment by FabianLars** [comment]
This is a upstream bug in WebView2. The only official-ish workaround (on our side) is to focus the webview when the window moves but for whatever reason that didn't work for us.
So the only thing left until it's fixed upstream (it was reported 2 years ago btw) it to manually `blur` the element when the window moves. Here's a React example, i hope it's translatable to vanillajs: <https://github.com/FabianLars/mw-toolbox/blob/main/gui/src/components/forms/Select/Select.tsx#L33>.
