### ISSUE TITLE
Globe.GL component not rendering in Tauri WebView

### ISSUE THREAD

**Issue by miniponz** [tauri-apps/tauri#5138]
### Describe the bug

WebGL/Globe.GL not working properly in Tauri WebView

### Reproduction

1. Create Tauri/React app with `yarn create tauri-app`, selecting React/Typescript scaffolding.

2. In `Your-App/src/App.tsx`, add `<World>` component shown in the [react-globegl example here](https://github.com/vasturiano/react-globe.gl/blob/master/example/hexed-polygons/index.html).

3. Install any missing dependencies. 

4. Start app in dev mode using `yarn tauri dev`.

### Expected behavior
View globe like the example [provided by globeGL here](https://globe.gl/example/hexed-polygons/).

### Actual behavior
- Blank white canvas where react globe.gl glove should appear in Tauri App. 
- localhost:3000 shows globe as expected. 

### Platform and versions

```
Environment
  › OS: Mac OS 12.2.1 X64
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.63.0-nightly
  › cargo: 1.63.0-nightly
  › Rust toolchain: nightly-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ build
  └─ src
```

### Additional context

- When running the Tauri App in dev mode, the Globe.GL component occasionally renders after I make changes to the react code and the UI re-renders.
- No other enlightening console messages/errors.

**Comment by Moon1102** [comment]
<img width="793" alt="图片" src="https://user-images.githubusercontent.com/15380331/188525677-448a76ee-1e63-4deb-b36f-2366c1133253.png">
Works fine under Mac OS 11.4.0 X64

****
EDIT：
[reproduction](https://github.com/Moon1102/tauri-app-gl.git) if it can help

**Comment by JonasKruckenberg** [comment]
<img width="912" alt="Screenshot 2022-09-06 at 11 06 10" src="https://user-images.githubusercontent.com/25329995/188594837-309747d1-ffbc-4fe4-abf3-b40c2d4d4e66.png">

works fine on my machine (macOS 12.5 aarch64) maybe you can try cleaning caches, rebuilding the app etc. or if nothing helps you might try updating your OS or testing in a VM with an up-to-date version

**Comment by miniponz** [comment]
Thanks for responding - and apologies for not being more specific. If I take the World component wrapping the Globe and extract it to its own file, then include it in `App.tsx`,  it does not render in Tauri or Safari, but does show up in Chrome on localhost:3000. 

![image](https://user-images.githubusercontent.com/43192303/188717945-b63503dc-1a2a-4f74-b1e2-ac687b86a531.png)

![image](https://user-images.githubusercontent.com/43192303/188718056-c9e2d704-2a3e-4f99-b3a2-3c4ffd0b9f38.png)

[example here](https://github.com/miniponz/tauri-app-gl)

**Comment by Moon1102** [comment]
@miniponz @JonasKruckenberg  Tried and found that <React.StrictMode> restricts some functions, the specific reason is because I don't know `React`, so I can't help further. So if you comment out this tag and you will get a pretty earth.

<img width="800" alt="图片" src="https://user-images.githubusercontent.com/15380331/188765028-41ff9483-a775-49f9-ae4b-fc22594f1b4f.png">

**Comment by amrbashir** [comment]
If this issue happens with Safari too, then there is nothing we can do and FWIW I've seen a lot of people complain about `React.StrictMode` outside of tauri context. Thanks you @Moon1102 for triaging this issue.
