### ISSUE TITLE
[bug] aarch64-apple-darwin not found in the binaries

### ISSUE THREAD

**Issue by data987** [tauri-apps/tauri#5140]
### Describe the bug

I'm trying to use the `sidecar` command but I received this message ` path matching binaries/python-app-aarch64-apple-darwin not found.`

This is my folder structure

<img width="356" alt="Screen Shot 2022-09-05 at 11 21 04 PM" src="https://user-images.githubusercontent.com/8518699/188546224-0dfe9791-aa9b-421b-914c-5cb8bf6ec245.png">

this is my `tauri.conf.json`:

``` rust
"allowlist": {
      "all": true,
      "shell": {
        "all": false,
        "execute": true,
        "open": false,
        "sidecar": true,
        "scope": [
          {
            "name": "python-app",
            "sidecar": true
          }
        ]
      }
    },
    "bundle": {
      "active": true,
      "category": "DeveloperTool",
      "copyright": "",
      "deb": {
        "depends": []
      },
      "externalBin": [
        "binaries/python-app"
      ],
```

I don't know what am I doing wrong? this is in dev

### Platform and versions

```rust
Environment
  › OS: Mac OS 12.3.1 X64
  › Node.js: 18.1.0
  › npm: 8.8.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-aarch64-apple-darwin
```

**Comment by amrbashir** [comment]
This is probably because the `.py` at the end. `externalBin` is meant for binary files (executables) not scripts. You can use [`resources`](https://tauri.app/v1/api/config#bundleconfig.resources) instead. If you really want to use `externalBin`, you can just omit the `.py` from the file name.
