### ISSUE TITLE
Extending FS library

### ISSUE THREAD

**Issue by erikpa1** [tauri-apps/tauri#5159]
### Describe the problem

Hi guys, I'm having a little bit fun with tauri and I found that in FS there is no function for  **checkFileExistence** (only try catch option).

Yeah I know there is plugin for it, but, I think, this one should be basic functionality. (Like common, everyone has this functionality, python, c++,....)

### Describe the solution you'd like

Implement fileExists to fs.

**Comment by FabianLars** [comment]
As i said on discord, there is an open pr for this: https://github.com/tauri-apps/tauri/pull/5060
