### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by mrquantumoff** [tauri-apps/tauri#5162]
I've always wanted to make native cross-platform apps easily. But setting up and updating electron is real pain in the ass, other frameworks either require to learn some programming language that is not used anywhere outside the framework (e.g flutter requires dart) either they are hard to setup (electron) or they're just microsoft (.NET MAUI). Tauri's API is incredibly easy to use, performance is good and it doesn't package chromium. Thank you.

**Comment by nothingismagick** [comment]
you're welcome. :)
