### ISSUE TITLE
[bug] Drop not running on managed state

### ISSUE THREAD

**Issue by jquesada2016** [tauri-apps/tauri#5167]
### Describe the bug

Currently, when the app is terminated via the last window being closed, data stored within managed state never gets dropped, and thus cleanup code can never run.

### Reproduction

1. Create a new Tauri project
2. Implement Drop for any struct
3. Add that struct to the app
4. Run Tauri
5. Close the window
6. Notice the drop not running

### Expected behavior

I expect managed data to be properly disposed of on app termination, or a succinct mechanism for hooking into the termination/cleanup sequence.

### Platform and versions

Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 105.0.1343.27
  › MSVC: 
      - Visual Studio Build Tools 2022
  › Node.js: 17.7.1
  › npm: 8.19.1
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.65.0-nightly
  › cargo: 1.65.0-nightly
  › Rust toolchain: nightly-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: https://grupoqueara.web.app/
  › devPath: http://localhost:5173/
  › framework: Svelte

App directory structure
  ├─ .firebase
  ├─ .github
  ├─ .svelte-kit
  ├─ build
  ├─ functions
  ├─ node_modules
  ├─ src
  ├─ src-tauri
  ├─ static
  └─ tests

**Comment by FabianLars** [comment]
Basically no `Drop` implementations are executed because the app gets closed via [`std::process::exit`](https://doc.rust-lang.org/std/process/fn.exit.html).
> or a succinct mechanism for hooking into the termination/cleanup sequence.

You can listen to window close and app exit events: <https://github.com/tauri-apps/tauri/blob/b02fc90f450ff9e9d8a35ee55dc1beced4957869/examples/api/src-tauri/src/main.rs#L211-L244>

**Comment by jquesada2016** [comment]
Thank for the snippet, although it seems to be outdated. I do see in the docs the `RunEvent` enum, but can't find where to hook it. The `run` menthod, as above, only accepts a `Context` struct.

**Comment by FabianLars** [comment]
It's not outdated, there are 2 different run methods, one on the `Builder` (wrong), and one on the `App`. You can convert the Builder to an App by changing the default `.run(tauri::generate_context!())` line to `.build(tauri::generate_context!())`.
