### ISSUE TITLE
[bug] Long project launch (over 5min)

### ISSUE THREAD

**Issue by LIMPIX31** [tauri-apps/tauri#5168]
### Describe the bug

The project takes a very long time to start, sometimes more than 5 minutes, and if dependencies are updated, 10 - 15 minutes

### Project start log
```

        Warn Waiting for your frontend dev server to start on http://localhost:3000/...
        Warn Waiting for your frontend dev server to start on http://localhost:3000/...
        Warn Waiting for your frontend dev server to start on http://localhost:3000/...
        Warn Waiting for your frontend dev server to start on http://localhost:3000/...
        Warn Waiting for your frontend dev server to start on http://localhost:3000/...

  VITE v3.1.0  ready in 83455 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
        Info Watching D:\Projects\nodium-launcher\src-tauri for changes...
   Compiling app v0.1.0 (D:\Projects\nodium-launcher\src-tauri)n 7ms
    Finished dev [unoptimized + debuginfo] target(s) in 3m 01sin 7ms
[..................] / : timing config:load:flatten Completed in 7ms

```

### Reproduction

```toml
[build-dependencies]
tauri-build = { version = "1.0.4", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.5", features = ["fs-all", "http-all", "path-all", "protocol-all", "shell-all", "updater", "window-all"] }
zip = "0.6.2"
reqwest = { version = "0.11.11", features = [ "stream" ] }
tokio = { version = "1", features = ["full"] }
futures-util = "0.3.24"
thiserror = "1.0.34"
blake3 = "1.3.1"
sysinfo = "0.26.2"

[dependencies.tauri-plugin-fs-watch]
git = "https://github.com/tauri-apps/tauri-plugin-fs-watch"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
```

### Expected behavior

I think it should be faster.

### Platform and versions

Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 105.0.1343.27
  › MSVC: 
      - Visual Studio Build Tools 2017
      - Visual Studio Community�2019
  › Node.js: 18.7.0
  › npm: 8.17.0
  › pnpm: 7.8.0
  › yarn: 1.23.0-20220130.1630
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: default-src 'self'; img-src 'self' asset: https://asset.localhost
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ .git
  ├─ .idea
  ├─ .tauri
  ├─ node_modules
  ├─ src
  └─ src-tauri

### Additional context

I'm assuming this is normal or a duplicate, but please don't kick me, I just haven't found a coherent explanation.

**Comment by FabianLars** [comment]
Well, your frontend already took 84 seconds (???) and then 3 minutes on top for rust, is still pretty slow, but somewhat _alright_ if your system is old/slow or the project is stored on a hard-drive instead of a SSD.

For reference, on my system (ryzen 9 3900x + ssd on Windows) a _clean_ debug build (`tauri dev`) takes ~1 minute.

You can also check out cargo's `--timings` option (https://doc.rust-lang.org/cargo/reference/timings.html) to see where it gets stuck compiling.

**Comment by LIMPIX31** [comment]
> Well, your frontend already took 84 seconds (???) and then 3 minutes on top for rust, is still pretty slow, but somewhat _alright_ if your system is old/slow or the project is stored on a hard-drive instead of a SSD.
> 
> For reference, on my system (ryzen 9 3900x + ssd on Windows) a _clean_ debug build (`tauri dev`) takes ~1 minute.
> 
> You can also check out cargo's `--timings` option (https://doc.rust-lang.org/cargo/reference/timings.html) to see where it gets stuck compiling.

It seems my computer is now not only inadequate for gaming, but also for Rust development.

 I moved it to SSD and now it starts for 1 - 1.5 minutes instead of 3 - 4. In addition, I was surprised to see that the `target` directory weighs more than 26 Gb.


CPU: Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz   2.67 GHz
RAM: 8,00 Gb

Timings:
![изображение](https://user-images.githubusercontent.com/81296950/189474034-ad78c3fb-e36b-4ec0-85a7-6975a2c0aac9.png)
![изображение](https://user-images.githubusercontent.com/81296950/189474050-1ffb8bd5-b1da-4ada-bf1b-743254b5d8b8.png)

P.S. It is almost impossible to use the computer during the startup of the project. The CPU is 100% loaded.

P.S.S Why does it compile every time it starts up if the source code on rust has not been changed?

**Comment by FabianLars** [comment]
> the target directory weighs more than 26 Gb

That shouldn't reallyyy happen. After a first run it should be around 2 gb. It can increase on dependency updates and will increase heavily on Rust updates, but not to 26gb that quickly 🤔 

> P.S. It is almost impossible to use the computer during the startup of the project. The CPU is 100% loaded.

Yeah that's unfortunate. But really not much you can do here, you _could_ try playing around with the [build.jobs](https://doc.rust-lang.org/cargo/reference/config.html#buildjobs) cargo setting, but that probably won't get you far either. And ofc it would increase your build times.

> P.S.S Why does it compile every time it starts up if the source code on rust has not been changed?

ideally this shouldn't happen but we're aware that it does :( it's not just you

**Comment by LIMPIX31** [comment]
By deleting the `target` directory and moving the project to an SSD, it now takes 35-40s to start
Frontend started up in 2s instead of 15-20s
