### ISSUE TITLE
[bug] Blank white screen on load

### ISSUE THREAD

**Issue by justintaylor-dev** [tauri-apps/tauri#5170]
### Describe the bug

Small question / possible bug report, There's a blank white screen on load in dev and after build / install. I'm guessing this is just the Webview taking 600-800ms to load up, but if so, is there a way to either set the background color or hide the window until it's fully loaded so we don't get the blank white screen?

![tauri load](https://user-images.githubusercontent.com/10479769/189506011-97155bea-8da7-4d74-b70f-46e83e487fb4.gif)

Tauri is insanely awesome, keep up the great work! 👏

### Reproduction

Build app
Launch App

### Platform and versions

Environment
  › OS: Windows 10.0.19043 X64
  › Webview2: 105.0.1343.27
  › MSVC:
      - Visual Studio Community 2019
  › Node.js: 16.13.2
  › npm: 8.1.2
  › pnpm: Not installed!
  › yarn: 1.22.5
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React

App directory structure
  ├─ .vscode
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri

**Comment by FabianLars** [comment]
WebView2 indeed has a known bug which causes the initial load to be a little slow and flashing a white window, not sure if changing the background color made that go away _completely_.

Anyway, background color support was just merged in wry so that will still take a while until it's available in Tauri.

You can hide the window by setting `"visible": false` in your tauri.conf window config (if that's how you spawn the window) and then call `appWindow.show()` in your js code once it's loaded.

**Comment by GiantappMan** [comment]
> 
Hi @FabianLars 

I want to create a window in the rs file without tauri.conf
How should I deal with it?

```rust
  let main_window =
            tauri::WindowBuilder::new(handle, "main", tauri::WindowUrl::App(url.into()))
                .visible(false)
                .build()
                .expect("failed to create main window");
        main_window.set_title("title").unwrap();    
        main_window.center().unwrap();
        main_window.show().unwrap();
```

**Comment by GiantappMan** [comment]
> > 
> 
> Hi @FabianLars
> 
> I want to create a window in the rs file without tauri.conf How should I deal with it?
> 
> ```rust
>   let main_window =
>             tauri::WindowBuilder::new(handle, "main", tauri::WindowUrl::App(url.into()))
>                 .visible(false)
>                 .build()
>                 .expect("failed to create main window");
>         main_window.set_title("title").unwrap();    
>         main_window.center().unwrap();
>         main_window.show().unwrap();
> ```

For anyone having a similar problem:

**rust :**
```rust
  let main_window =
            tauri::WindowBuilder::new(handle, "main", tauri::WindowUrl::App(url.into()))
                .visible(false)
                .build()
                .expect("failed to create main window");
        main_window.set_title("title").unwrap();
        main_window.center().unwrap();
```
**frontend:**
```react
  async function setupAppWindow() {
    const appWindow = (await import('@tauri-apps/api/window')).appWindow
    appWindow.show();
  }

  useEffect(() => {
    setupAppWindow()
  }, [])
```

**tauri.conf.json:**
```json
    "allowlist": {   
      "window": {
        "show": true
      }
    },
```

**Comment by badalya1** [comment]
> You can hide the window by setting `"visible": false` in your tauri.conf window config (if that's how you spawn the window) and then call `appWindow.show()` in your js code once it's loaded.

`appWindow.show()` still will produce the same outcome. I don't think there is a programmatic way to show the window and make everything smooth. 

Where is this known bug being tracker? is there a link?

**Comment by Borber** [comment]
> > You can hide the window by setting  in your tauri.conf window config (if that's how you spawn the window) and then call  in your js code once it's loaded.`"visible": false``appWindow.show()`
> 
> `appWindow.show()` still will produce the same outcome. I don't think there is a programmatic way to show the window and make everything smooth.
> 
> Where is this known bug being tracker? is there a link?

You may need to wait a while before `appWindow.show()` , I'm also curious why this bug hasn't been fixed after so long, no matter whose problem it is

```ts
onMount(async () => {
    setTimeout(() => {
      setupWindow();
    }, 300);
  });

  async function setupWindow() {
    const appWindow = (await import('@tauri-apps/api/window')).appWindow
    appWindow.show();
  }
```

**Comment by Alaricus** [comment]
Seeing this over a year later. I tried bypassing it by using a splash screen, but that one turned out to have the same exact problem, although the time until render is shorter (either because the window is smaller or because the html page has no JS and is lighter.)

**Comment by nikolaeu** [comment]
slight delay works fine in my case, though may need more comprehensive testing on other devices

```
window.addEventListener("load", (event) => {
	setTimeout(() => {
		appWindow.show();
	}, 100);
});
```

@FabianLars I see it marked as completed without PR/commint reference. Maybe we should reopen, as the initial experience looks quite annoying with such flickering.

**Comment by Borber** [comment]
> slight delay works fine in my case, though may need more comprehensive testing on other devices
> 
> ```
> window.addEventListener("load", (event) => {
> 	setTimeout(() => {
> 		appWindow.show();
> 	}, 100);
> });
> ```
> 
> @FabianLars I see it marked as completed without PR/commint reference. Maybe we should reopen, as the initial experience looks quite annoying with such flickering.

https://github.com/tauri-apps/tauri/issues/5170#issuecomment-1242989732  It's because this bug can only be fixed by WebView2 itself and provides a solution.

**Comment by rcsaquino** [comment]
If I recall correctly wails, (Tauri but for Go), use webview2 as well but it doesn't seem have this issue.

**Comment by AuracleTech** [comment]
This issue is closed yet issue persist in 2024 in version 2

**Comment by 5vx** [comment]
issue still persists, using windows x64 build profile

**Comment by doaortu** [comment]
here's workaround that I use: set the window to transparent to avoid blank white screen

**Comment by AuracleTech** [comment]
> here's workaround that I use: set the window to transparent to avoid blank white screen

How, I tried `"transparent": true` and `* { background: transparent !important; }`
But at loading its still white, so let me know if you really did this

**Comment by AuracleTech** [comment]
Issue is still tracked, but here https://github.com/tauri-apps/tauri/issues/1564

**Comment by bukowa** [comment]
For these that are too lazy to read here's my workaround commit that fixes this issue https://github.com/bukowa/ck3oop/commit/918ca33b147c9ba270f99e4babadacb2d90826fc?diff=unified&w=0#diff-d596678ffe2aad0b27a0502bc4ff850f36245dead171df58232ebfeafef8779d

**Comment by ScepticDope** [comment]
Issue still persists on Windows 10, non of the proposed workarounds work.
Adding a `backgroundColor` to the window also does nothing for this sadly. As mentioned here: https://github.com/tauri-apps/tauri/issues/1564

Also on resizing the window you can see the white background flashing, you'd think at least that would be fixed by adding a `backgroundColor`?

Can this issue please be opened again?

**Comment by 8-prime** [comment]
Agree this issue should be reopened. 
To add to what @ScepticDope noted regarding the resizing, I have also had instances where specific window sizes will just always display a 1px wide white border. I have only observed this on Windows 10 though.

**Comment by MC-XiaoHei** [comment]
>  I have also had instances where specific window sizes will just always display a 1px wide white border. I have only observed this on Windows 10 though.

+1. i noticed when use `win.set_shadow(false).unwrap();`, the white border will not appear

**Comment by Daydreamer-riri** [comment]
Hi everyone, if the above method still doesn't work for you, please check if you are using `tauri-plugin-window-state`. It remembers the `visible` property, causing your `visible(false)` setting to be ineffective.

You need to configure `tauri-plugin-window-state` like this:

```rust
use tauri_plugin_window_state::StateFlags;
tauri::Builder::default()
		.plugin(tauri_plugin_window_state::Builder::default().with_state_flags(StateFlags::all() & !StateFlags::VISIBLE).build())
        .run(tauri::generate_context!())
        .expect("error while running tauri application")
```

This allows `window-state` to ignore the `visible` property, making your `visible(false)` effective.

**Comment by plitarko** [comment]
I have tried everything in this thread and none of it works for me. Please reopen this. There is no case where anyone wants a white flash when the app launches, this shouldn't even be an option.

**Comment by FabianLars** [comment]
i won't reopen every gh issue about this. head over to #1564

**Comment by kirill18734** [comment]
@plitarko  нашел решение для tauri v2 : 
1. В файле tauri.conf.json проставляем "visible": false   , пример: 
```
"app": {
    "withGlobalTauri": true,
    "windows": [
      {
        "title": "Печать ячеек",
        "fullscreen": false,
        "resizable": false,
        "maximizable": false,
        "decorations": false,
        "visible": false,
        "width": 460,
        "height": 260
      }
    ], ...
```
2. Разрешить использование команды show в файле capabilities/default.json  - "core:window:allow-show" , пример: 
```
{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "default",
  "description": "Capability for the main window",
  "windows": ["main"],
  "permissions": [
    "core:default",
    "opener:default",
    "core:window:allow-show"]
}
```
3. В JS в нужном вам месте проставляем "await getCurrentWindow().show()", пример в REACT: 
```

import React from "react";
import ReactDOM from "react-dom/client";
import { Command } from "@tauri-apps/plugin-shell";
import "./index.css";
import App from "./App/App";
import { getCurrentWindow } from "@tauri-apps/api/window";

// // ---------- Запуск backend ----------
Command.create("start_backend").execute();
await getCurrentWindow().show();

const container: any = document.querySelector("#container");
ReactDOM.createRoot(container).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

```

**Comment by xxshady** [comment]
if you just want to change starting background to black color using vanilla js/ts:
```html
<head>
  <!-- has to be inlined right here -->
  <!-- otherwise it won't work in dev mode (npm run tauri dev) -->
  <!-- this won't work: <link rel="stylesheet" href="/styles.css" /> -->
  <style>
    html,
    body {
      background-color: #000 !important;
    }
  </style>
</head>

<body>
  <script>
    // or import { getCurrentWindow } from "@tauri-apps/api/window";
    const { getCurrentWebviewWindow } = window.__TAURI__.webviewWindow;
    getCurrentWebviewWindow().show();
  </script>
</body>
```

and also set `visible: false` + `backgroundColor: #000000` in `tauri.conf.json`

```json
"app": {
  "withGlobalTauri": true,
  "windows": [
    {
      "title": "test",
      "width": 1280,
      "height": 720,
      "visible": false,
      "backgroundColor": "#000000"
    }
  ]
}
```

tested it on my mid-range non-gaming laptop:

<details>
  <summary>Click to view video</summary>
  
  [video](https://github.com/user-attachments/assets/12d4f8d6-3aaf-49b1-8412-b5bf255c7c71)
  
</details>
