### ISSUE TITLE
[bug] tauri build errors out at bundling step

### ISSUE THREAD

**Issue by OzymandiasTheGreat** [tauri-apps/tauri#5175]
### Describe the bug

When running `tauri build` the binary builds fine but then immediately errors out with
```
thread '<unnamed>' panicked at 'Can't detect any appindicator library', src/build.rs:326:17
```
`tauri dev` works as expected.

I suspect this might be caused by `libayatana-appindicator3-1-dev` being newer than expected,
I had jammy-proposed enabled by mistake for a while. I have no clue how to downgrade tho.

Everything else is pretty standard and minimal, I'm running on Ubuntu 22.04.

Here's the full repo, https://github.com/OzymandiasTheGreat/emoji-keyboard
src-tauri is minimal so you might check it out if needed.

### Reproduction

1. Run `tauri build`
2. See error once the binary is built.

### Expected behavior

`tauri build` finishes without errors and I get an AppImage.

### Platform and versions

Environment
  › OS: Ubuntu 22.04 X64
  › Node.js: 16.14.2
  › npm: 8.7.0
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../web-build
  › devPath: http://localhost:19006/
  › framework: React
  › bundler: Webpack

App directory structure
  ├─ src-tauri
  ├─ .expo-shared
  ├─ node_modules
  ├─ src
  ├─ assets
  ├─ web-build
  ├─ .git
  └─ .expo

### Additional context

Not really context, I migrated my most popular app to tauri for many reasons, like the fact that Ubuntu 22.04 broke electron version, and it works much more reliably now, but I can't release it without building the bundles.

**Comment by beyondlov1** [comment]
I have this problem on ubuntu 22.04 too, and ``` sudo apt install libayatana-appindicator3-dev``` may help.

**Comment by tymmesyde** [comment]
Had this issue on fedora 37, after installing `libappindicator-gtk3-devel` the error message was gone

**Comment by NYBACHOK** [comment]
openSUSE Tumbleweed - resolved with installation of `libayatana-indicator3-devel`
