### ISSUE TITLE
[feat] custom .desktop file template

### ISSUE THREAD

**Issue by snorkysnark** [tauri-apps/tauri#5176]
### Describe the problem

I'm trying to implement a custom URL scheme in my app, and as demonstrated by https://github.com/tauri-apps/tauri/issues/323#issuecomment-920928947 this is already possible on Windows using a custom wix template.
It would be pretty easy to do on Linux as well, but it requires some changes to the .desktop file: namely adding a MimeType field and appending `%u` after Exec:
```
[Desktop Entry]
Categories=Development;
Exec=app-name %u
Icon=app-name
Name=app-name
Terminal=false
Type=Application
MimeType=x-scheme-handler/customprotocol
```

### Describe the solution you'd like

Use a handlebars template for .desktop file generation, the same way it works for wix:
```json
"deb": {
    "depends": [],
    "desktopTemplate": ""
},
```
```
[Desktop Entry]
Categories={{{categories}}}
Exec={{{exec}}}
Icon={{{icon}}}
Name={{{name}}}
Terminal=false
Type=Application
```
I can make a PR later if you aggree on this change

**Comment by amrbashir** [comment]
A PR would be greatly appreciated, thanks.
