### ISSUE TITLE
App loses hover while moving mouse along top and left edges

### ISSUE THREAD

**Issue by jonrouleau** [tauri-apps/tauri#5179]
When a tauri app is in fullscreen mode (or otherwise positioned at 0,0) moving the cursor along the top or left edges results in flickering hover state.

OS: Linux

E.g.
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <style>
      html {
        height: 100%;
        background-color: black;
      }
      html:hover {
        background-color: white;
      }
    </style>
  </head>
</html>
```

```json
"windows": [
  {
    ...
    "fullscreen": true
  }
]
```

Demo `seizure warning!`: https://user-images.githubusercontent.com/11533746/189830715-c6c036f8-0300-4318-8d49-fea0998401c3.mp4

**Comment by amrbashir** [comment]
After testing, I wouldn't consider this as a bug, since the cursor on most Operating Systems can move to a position outside of the monitor bounds and thus won't be hovering over the fullscreen window.
