### ISSUE TITLE
How to monitor program exit？

### ISSUE THREAD

**Issue by TheBlindM** [tauri-apps/tauri#5185]
### Describe the bug

I start an exe when the program starts, but kill doesn't seem to be executed when the program ends

![image](https://user-images.githubusercontent.com/48701152/190060669-b1de8076-c099-47cf-92a7-2beefa751708.png)

### Platform and versions

 › OS: Windows 10.0.19044 X64
  › Webview2: 105.0.1343.33
  › MSVC:
      - Visual Studio Community 2019
  › Node.js: 16.13.2
  › npm: 8.1.2
  › pnpm: 7.9.5
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3200/
  › framework: Vue.js
  › bundler: Rollup

App directory structure
  ├─ .husky
  ├─ .idea
  ├─ build
  ├─ dist
  ├─ mock
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri

**Comment by amrbashir** [comment]
listen to `Exit` and `ExitRequested` event https://docs.rs/tauri/latest/tauri/enum.RunEvent.html
