### ISSUE TITLE
normalize path like python?

### ISSUE THREAD

**Issue by erikpa1** [tauri-apps/tauri#5188]
### Describe the problem

In python (or c++ qt,...) you can write  os.path.normalize("my/path/file.txt") which also fix OS  so result for windows is "my\\path\\file.txt").

Could this maybe be native tauri behaviour? I'm for example migrating a lot of web code to tauri and in web you mostly use  /somepath/somepath/ ,.... but for tauri app version I have to create wrappers and platform switchers,...

No big deal, just suggestion :) 

### Describe the solution you'd like

It could be nice to tauri auto switch OS and convert it instead of me,... or normPath by default,...

**Comment by amrbashir** [comment]
did you try using https://tauri.app/v1/api/js/path#normalize  ?

**Comment by FabianLars** [comment]
Also most of our apis should accept both separators no matter the platform just fine 🤔

**Comment by erikpa1** [comment]
@amrbashir @FabianLars 

I cant use normalize, because my path conversion of three 3d libraries has to be sync, not async,.... (its incredibly hard to work with three JS/fiber 3d meshes, in async way, beause of react hooks,...).

Yes libraries works with // and \ but 

`import {convertFileSrc} from "@tauri-apps/api/tauri";` which is alpha, omega of my app don't normalize and  on windows I have  myPath**%5**anotherPath**%5** and on mac I have %2  and javascript fetch is not working....

**Comment by amrbashir** [comment]
`convertFileSrc` is not meant for this use-case. Also we can't give you a sync version of `join`, because of limitations of webkit2gtk on Linux.

**Comment by amrbashir** [comment]
use https://github.com/browserify/path-browserify instead
