### ISSUE TITLE
[feat] Update based on static-file feed

### ISSUE THREAD

**Issue by kornelski** [tauri-apps/tauri#5199]
### Describe the problem

As far as I understand, Tauri's updater [requires server-side support](https://tauri.app/v1/guides/distribution/updater/#server-support) to check if the version is current and return 204, or an appropriate update information JSON to make the app update itself. This requires having some sort of server-side logic for serving appropriate update responses, and is incompatible with static-file hosting.

### Describe the solution you'd like

I would prefer to handle updates with purely static files, the same way [Sparkle](https://sparkle-project.org/) does it. Sparkle client fetches a single feed file that passively declares all available app versions and their download urls. The client searches the feed file for a newer version. A special 204 from the server isn't needed to save bandwidth, because static files can be revalidated with if-modified-since or etags and return 304 instead.

This way updates could be handled without any server-side logic. An update feed could be uploaded alongside new archive files. Sparkle also has a `generate-appcast` tool that automatically builds the feed based on bundles already built. 

The Tauri equivalent would be `tauri build` generating something like `update-downloads.json` with all the versions and URLs clients need to update themselves if needed.

**Comment by FabianLars** [comment]
The second format described in our docs is what you're looking for https://tauri.app/v1/guides/distribution/updater/#update-file-json-format
It's compatible with static file hosting just fine, for example many people host it as a gist on github.

> The Tauri equivalent would be tauri build generating something like update-downloads.json

This is the only thing that doesn't exist yet (= you need to create the file yourself).

**Comment by kornelski** [comment]
Oh, I missed the bit that it's an alternative, and thought the JSON documentation is for the server logic.

**Comment by HoaX7** [comment]
how do i use github gist?? im not able to get it to work
