### ISSUE TITLE
css properties won't affect elements.

### ISSUE THREAD

**Issue by Sombian** [tauri-apps/tauri#520]
**Describe the bug**
meanwhile the app should looks like this
![image](https://user-images.githubusercontent.com/23397550/76934050-c35a2400-6931-11ea-94fe-5f65bdd8c817.png)
the app looks like this
![image](https://user-images.githubusercontent.com/23397550/76934083-cead4f80-6931-11ea-89a9-e60fb9ffa6c2.png)
as you can see, there are large noticeable drops of quality in app.

**To Reproduce**
1. apply scss properties on ``.vue`` project.

**Expected behavior**
app should reflects all (s)css properties just as browser do.

**Platform and Versions (please complete the following information):**
```
Operating System - Windows_NT(10.0.18362) - win32/x64

Node.js environment
  Node.js - 13.11.0
  tauri.js - 0.4.5

Rust environment
  rustc - 1.40.0
  cargo - 1.40.0
  tauri-bundler - 0.4.4

Global packages
  NPM - 6.13.7
  yarn - 1.22.4

App directory structure
/.git
/dist_tauri
/node_modules
/public
/src
/src-tauri

App
  tauri - 0.4
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  Windows - Edge
  distDir - ../dist
  devPath - http://localhost:8080
```

**Comment by nothingismagick** [comment]
This is totally new for me, but if I were to venture a guess it looks like your font isn't getting shipped. One way around this is to inline the font in your SCSS as base64. (I use to have to do that in the past when I was working on some specific types of electron projects.)

@Laegel - this might be another one of those tips for the docs.

**Comment by Sombian** [comment]
> This is totally new for me, but if I were to venture a guess it looks like your font isn't getting shipped. One way around this is to inline the font in your SCSS as base64. (I use to have to do that in the past when I was working on some specific types of electron projects.)
> 
> @Laegel - this might be another one of those tips for the docs.

interestingly, i can reproduce this even on browser through microsoft edge.
it seems like edge is lacking in terms of CSS support.

**Comment by nothingismagick** [comment]
Hmm - are you using CSS variables?

https://stackoverflow.com/questions/39596531/css-variables-dont-work-in-microsoft-edge

**Comment by Sombian** [comment]
> Hmm - are you using CSS variables?
> 
> https://stackoverflow.com/questions/39596531/css-variables-dont-work-in-microsoft-edge

i do, but that orange? colour and black-ish theme is also done by variables.
its a wonder why only certain properties are not working.

**Comment by nothingismagick** [comment]
Dunno, but it seems that this isn't about tauri, so perhaps close this issue and ask at the discord channel. maybe somebody has a tip for you?

**Comment by Sombian** [comment]
> Dunno, but it seems that this isn't about tauri, so perhaps close this issue and ask at the discord channel. maybe somebody has a tip for you?

will do.
