### ISSUE TITLE
[bug] audio tag using a asset resource file as the source, the asset server returns wrong content-type of text/html

### ISSUE THREAD

**Issue by nathanfaucett** [tauri-apps/tauri#5203]
### Describe the bug

audio tag using a asset resource file as the source, the asset server returns wrong content-type of text/html

### Reproduction

create project with audio files in bundle.resources create a filepath using something like 
```ts
const filePath = convertFileSrc(
	await normalize(
		await resolveResource('name_of_audio_file.mp3')
	)
)
```
use in audio tag `<audio controls><source src="{filePath}" type="audio/mpeg" /></audio>`

![Screen Shot 2022-09-15 at 16 53 31](https://user-images.githubusercontent.com/1843186/190506776-3685ff1c-1c7e-41d6-88ab-48da40efb9b2.png)

### Expected behavior

the content type to be audio/mpeg

### Platform and versions

Environment
  › OS: Mac OS 12.2.1 X64
  › Node.js: 16.15.0
  › npm: 8.8.0
  › pnpm: 7.0.0
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.1.0
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.0,
  › tauri-build [RUST]: 1.1.0,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.0,

App
  › build-type: bundle
  › CSP: default-src 'self'; img-src 'self' asset: https://asset.localhost; media-src 'self' asset: https://asset.localhost;
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: Svelte

App directory structure
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  └─ src

**Comment by Moon1102** [comment]
Maybe the good news is that it doesn't affect playback :) (yes! also can work in production mode)

<img width="556" alt="图片" src="https://user-images.githubusercontent.com/15380331/190540297-de9cd142-1fb1-4435-8f94-580b8c6e13e0.png">


The code is not complicated in Vue3.
<img width="508" alt="图片" src="https://user-images.githubusercontent.com/15380331/190539989-88986d57-6f6a-4f52-908b-a7acd0e7372a.png">

**Comment by amrbashir** [comment]
This only affects requests with `range` header. Initial request seems fine, only subsequent requests are affected.

This is probably because in the initial request we are reading the first bytes of the file where it usually contains the magic number to identify the file while subsequent requests might not have the magic number inside it and so `infer` crate will fail to parse the correct mimetype.

@lucasfernog should we use https://docs.rs/infer/0.9.0/infer/fn.get_from_path.html instead?

**Comment by lucasfernog** [comment]
We shouldn't infer the mime type from the path, that's a security vulnerability. We could instead cache the mime type on range requests or maybe always read the first bytes.

**Comment by amrbashir** [comment]
`get_from_path` does read the first bytes, it doesn't rely on file extension. https://docs.rs/infer/0.9.0/src/infer/lib.rs.html#240-251

**Comment by amrbashir** [comment]
although I think caching might be better for performance?
