### ISSUE TITLE
[feat] Help for debugging updater JSON errors

### ISSUE THREAD

**Issue by kornelski** [tauri-apps/tauri#5204]
### Describe the problem

When update process fails, Tauri's updater only fires an event, but doesn't log the error anywhere. I've used `"dialog": true` option to rely on the build-in UI for updates, so I did not build any event handling. I didn't even know that's a thing. As a result, I had no way of knowing why my updates aren't working. The built-in UI failed silently without reporting any errors anywhere.

I had to modify tauri itself to sprinkle `eprintln!` all over updater's code to discover the problem.

### Describe the solution you'd like

I'd expect it to print errors to stderr. Possibly if launched with `--verbose` or via `RUST_LOG=debug cargo run`.

### Alternatives considered

Having to build a custom error-reporting UI based on JS events is more work than I expected, especially given that no-code `dialog:true` option exists.

### Additional context

BTW, my problem with the update JSON was 

```text
SerdeJson(Error("invalid value for `pub_date`: a character literal was not valid", line: 0, column: 0))
```

which didn't like: `"pub_date": "2022-09-15T23:54:33+0100"`.

**Comment by FabianLars** [comment]
The library itself currently does almost no logging at all, only the cli.
We consider changing that tho, see #5200 (cross linking it so we see a reference to this issue in that pr)

> The built-in UI failed silently without reporting any errors anywhere.

That's not the case if we're counting events, the build-in dialog still reports them. You can use `RunEvent` in rust just fine, but the js events are a bit tricky because the update-check on start is too early for the js listeners, so you'd have to trigger the event manually again after the listeners were registered (the default dialog still listens to the `tauri://update` event).

**Comment by kornelski** [comment]
I've meant the built-in UI did not report the error in the UI anywhere. It let the events go to /dev/null, rather than the screen.

Tracing will be very helpful.

**Comment by RouHim** [comment]
@kornelski 
Just to be clear, the date must be in a special format? If so, in what format? I can't find any information about this in the documentation.
(I'm having the same issues)

**Comment by FabianLars** [comment]
@RouHim It must be formatted according to [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.8) - it's documented here: <https://tauri.app/v1/guides/distribution/updater#update-server-json-format>, but i'm working on a rewrite of the updater docs and will try to make it more obvious, thanks for the feedback.

**Comment by RouHim** [comment]
Good thing, I was skipping the "Update Server JSON Format" section because I'm not using this. Would be awesome to mention the date format also in the "Update File JSON Format" section or going for a more abstract description.

**Comment by kornelski** [comment]
For the record, this is still hard to diagnose and no errors are logged anywhere by default. I had to copy-paste manual check code from here:

https://docs.rs/tauri/latest/tauri/updater/struct.UpdateBuilder.html#method.check

The date format that worked for me is `"2023-01-18T00:00:00Z"`
