### ISSUE TITLE
[bug] cargo tauri dev build error

### ISSUE THREAD

**Issue by seyoatda** [tauri-apps/tauri#5209]
### Describe the bug

```
error[E0405]: cannot find trait `Clone` in this scope
    --> C:\Users\54367\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\hashbrown-0.12.3\src\set.rs:2318:39
     |
2318 |     fn union<'a, 'new, A: Allocator + Clone>(
     |                                       ^^^^^ not found in this scope

error[E0405]: cannot find trait `Clone` in this scope
    --> C:\Users\54367\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\hashbrown-0.12.3\src\set.rs:2323:35
     |
2323 |     fn drain<'new, A: Allocator + Clone>(
     |                                   ^^^^^ not found in this scope

Some errors have detailed explanations: E0405, E0412, E0425, E0433, E0463, E0531.
error: could not compile `hashbrown` due to 1369 previous errors
2022-09-16T12:15:30.069463Z ERROR ❌ error
error from HTML pipeline

Caused by:
    0: error from asset pipeline
    1: error during cargo build execution
    2: cargo call returned a bad status
2022-09-16T12:15:30.128846Z  INFO 📦 starting build
2022-09-16T12:15:30.130640Z  INFO spawning asset pipelines
```

### Reproduction

1. `cargo install create-tauri-app`
2. `cargo create-tauri-app`
3. cd to the project folder, and run ·cargo tauri dev`

### Expected behavior

no errors was throw

### Platform and versions

```
Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 105.0.1343.33
  › MSVC:
      - Visual Studio ���ɹ��� 2022
  › Node.js: 15.6.0
  › npm: 7.4.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.1.5
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.1.0,
  › tauri-build [RUST]: 1.1.0,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
package.json not found

App directory structure
  ├─ .vscode
  ├─ dist
  ├─ public
  ├─ src
  ├─ src-tauri
  └─ target
```

### Additional context

not sure if it is a bug. after the error msg, the tauri app window was popup.

**Comment by amrbashir** [comment]
This is an issue with the frontend, I am assuming you're using `yew`, so make sure you installed the `wasm32-unknown-unknown` target

**Comment by seyoatda** [comment]
> This is an issue with the frontend, I am assuming you're using `yew`, so make sure you installed the `wasm32-unknown-unknown` target

yes, you're right. I'm using `yew`. I'm just following the guides from official website, which doesn't mention about this dependency. 😂😂😂

Thanks for your help, otherwise I'll be stuck here for days.

**Comment by amrbashir** [comment]
which guide? I don't think we have a guide for yew yet

**Comment by seyoatda** [comment]
> which guide? I don't think we have a guide for yew yet

here: https://tauri.app/v1/guides/getting-started/setup
I'm using `create-tauri-app` to create a new project. And it gives a choice between `vanilla` and `yew`. I didn't know the difference at that time yet. Now I realize it's a frontend framework. I'm a backend developer so I'm not familiar with these frontend stuffs. Sorry~

**Comment by amrbashir** [comment]
no worries, I will add a note about the target in `create-tauri-app`
