### ISSUE TITLE
[bug] setFocus not unminimizing the window

### ISSUE THREAD

**Issue by Levminer** [tauri-apps/tauri#5212]
### Describe the bug

If I call `window.appWindow.setFocus()` and the window was minimized to the tray the focus doesn't work. I have to manually call `window.appWindow.unminimize()` which is sometimes works sometimes not.

In Electron for example `window.focus()` unminimizes the window by default.

### Platform and versions

Environment
  › OS: Windows 10.0.22622 X64
  › Webview2: 105.0.1343.33
  › MSVC: 
      - Visual Studio Build Tools 2022
  › Node.js: 18.7.0
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.1.0
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.0,
  › tauri-build [RUST]: 1.1.0,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.0,

**Comment by amrbashir** [comment]
yes that is expected, you should unminimized the window before focusing it

**Comment by Levminer** [comment]
> yes that is expected, you should unminimized the window before focusing it

Thanks, the order fixed it.
