### ISSUE TITLE
[bug] SystemTray doesn't add system tray icon in Debian+Xfce

### ISSUE THREAD

**Issue by malaire** [tauri-apps/tauri#5215]
### Describe the bug

When running this app which uses `SystemTray`, there is no app icon in system tray.

### Reproduction

1. clone [tauri-systemtray-test](https://github.com/malaire/tauri-systemtray-test)
2. run with `cargo tauri dev`

### Expected behavior

App starts and there is app icon in system tray.

### Platform and versions

Environment
  › OS: Debian 11 X64
  › Node.js: 12.22.12
  › npm: Not installed!
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.1.5
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.1.0,
  › tauri-build [RUST]: 1.1.0,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../ui
  › devPath: ../ui
package.json not found

App directory structure
  ├─ src-tauri
  ├─ .git
  └─ ui

**Comment by FabianLars** [comment]
I don't know if this is intended or a bug, but it needs a menu to work. For the icon to show up, an empty menu is enough, but that'd be kinda useless on Linux since there are no onclick events for tray icons.

**Comment by malaire** [comment]
ok, it works when I added a menu.

My intention is to create an app which can be minimized to system tray and then shown with global shortcut, so system tray icon is just to show that app is running and it doesn't actually need to have any other functionality.

**Comment by amrbashir** [comment]
is this will `libappindicator` or `libayayatan-appindicator`? does it work for any other system tray provider other than xfce?

As a final workaround, we could append an empty menu if none was provided but I would like to see first if it is specific to xfce or not.

**Comment by malaire** [comment]
With `libayatana-appindicator` (Debian 11 doesn't have `libappindicator`). I don't have time to test others than Xfce.

**Comment by amrbashir** [comment]
Just tested on my custom linux machine with polybar and it works fine without menu so it seems like a bug in xfce. It also looks like xfce doesn't support having multiple system trays from the same application. 

As a workaround for you, you could use an empty menu for the tray.
