### ISSUE TITLE
[bug] failed to get project out directory: failed to get cargo metadata: program not found error Command failed with exit code 1.

### ISSUE THREAD

**Issue by josuenm** [tauri-apps/tauri#5223]
### Describe the bug

Tauri project created with `package manager: yarn` and `UI template: react-ts`
I already installed all the requirements.
This is what I see in my terminal when I try to run the command `yarn tauri dev` to start the project.
![image](https://user-images.githubusercontent.com/83486074/190885990-a24555e1-d41b-4a4e-b0b6-11763c5dec5d.png)

### Reproduction

1. Generate project using `create tauri-app`
2. Choose `yarn package manager`
3. Use `react-ts` UI template
4. Run using `yarn tauri dev`

### Platform and versions

yarn: 1.22.17

**Comment by FabianLars** [comment]
Please include the whole output of `yarn tauri info` as required by the issue template.

It sounds like you don't have rust/cargo installed btw.

**Comment by josuenm** [comment]
@FabianLars I ran `yarn tauri info` and got the following error: 

> error: Found argument 'info' which wasn't expected, or isn't valid in this context
> USAGE:
>    cargo.exe build [OPTIONS]

**Comment by FabianLars** [comment]
Since the project was just created(?), can you upload it somewhere so we can check it out? Or did you change anything in the files after you created it (Especially the `scripts` in package.json)? Do you maybe have a leftover global tauri installation from alpha times?

It's not supposed to invoke `cargo build` at all here 🤔

**Comment by josuenm** [comment]
This is the [repository link](https://github.com/josuenm/tauri-bug). I didn't change anything after the project was created. It's my first time using tauri, so I don't know anything, I just installed the requirements

**Comment by FabianLars** [comment]
_No_ changes? Because the `"tauri"` script in package.json was changed to `"tauri dev"` which is not part of create-tauri-app

**Comment by josuenm** [comment]
It wasn't working when I just used `tauri`, but I tried it right now with `tauri` it worked, it was because I installed the requirements and forgot to change and test `tauri`. Sorry for the inconvenience.

**Comment by realav** [comment]
I am getting the same error with **yarn** and **next** template

> `yarn tauri dev`

`ready - started server on 0.0.0.0:1420, url: http://localhost:1420
Error failed to get project out directory: failed to get cargo metadata: No such file or directory (os error 2)
error Command failed with exit code 1.`

output of 

> `yarn tauri info`

`thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected end of input while parsing minor version number")', src/info.rs:507:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by FabianLars** [comment]
@amanvermah Can you share the output of these commands please:
- `rustup toolchain list`
- `cargo --version`
- `yarn list --pattern @tauri-apps/cli`

Also OS + version would be cool, but not required if you followed the setup guides for your OS here: https://tauri.app/v1/guides/getting-started/prerequisites

**Comment by realav** [comment]
Thanks. Forgot to install **rust** `curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh`. **Works now.**

**Comment by thangnqs** [comment]
Just install Rust, follow on https://tauri.app/v1/guides/getting-started/prerequisites

**Comment by roscoevanderboom** [comment]
An important note for MacOS users. You probably have to restart or log out before rust installation will take effect. That was the case for me on Mojave 10.14.6.

**Comment by gaowanlu** [comment]
to install Rusr env https://www.rust-lang.org/

**Comment by sartaj-sphp** [comment]
Check do you have cargo installed on your system

**Comment by serg06** [comment]
I just followed the QuickStart guide, it didn't say anything about prerequisites. 

It should link to the prerequisites page.

**Comment by FabianLars** [comment]
@serg06 All quick start guides have a note at the top:
![grafik](https://user-images.githubusercontent.com/30730186/213119029-7c6228d9-86c0-4cdf-87cb-c6d20a09a7ff.png)

And create-tauri-app also prints a warning after running it:
![grafik](https://user-images.githubusercontent.com/30730186/213119199-f202f9a3-e801-4b75-b45f-6d31394ef63d.png)

Where else could we add a warning, or how should the existing ones look like to avoid this confusion? Feedback is always much appreciated 🙏

**Comment by serg06** [comment]
@FabianLars Ahh I see. Let me explain how I missed it:

- I clicked QuickStart on the left sidebar and it brought me [here](https://tauri.app/v1/guides/getting-started/setup/) -- there is no mention of prerequisites
- I followed the instructions and ran `yarn create tauri-app` to create an app
- I tried to run the app and ran into this error

It would be great if it could be added to that page!

**Comment by FabianLars** [comment]
Ahh i see, you're totally right! thank you!

**Comment by TomasDePomas** [comment]
If there is any other first-timers (like me) getting stuck on this issue, I skipped over the line "Note that you have to restart your terminal, and in some cases, Windows itself, for the changes to take effect."

Stupid, I know, don't be like me.

**Comment by pferreira8** [comment]
I have the same issue on Windows, ridiculous how it is some kind of linking issue with Windows, even after restarting, obviously have rust and cargo installed.

**Comment by pwejar** [comment]
if it is your first time you install you will need to restart the shell as recommended. I restarted my visual studio code and it worked

**Comment by justingolden21** [comment]
I know I'm a dumb dumb for not installing rust first, but it would help if instead of giving the error: ` Error failed to get cargo metadata: program not found`, when running `npm run tauri dev`, it was somehow able to detect Rust isn't installed and said `Error: Rust is not installed` or something similar.

When I google "tauri" and click "quick start" on the first result, I get to https://tauri.app/v1/guides/getting-started/setup/ and the top says "The easiest way to scaffold a new project is the [create-tauri-app](https://github.com/tauri-apps/create-tauri-app)" which links (of course) here and a tthe top of the readme, I see `npm create tauri-app@latest` under "npm" (of course) and then run it and got this far. Again, I know I'm a dumb dumb, but I think this would be a very common path that people trying tauri for the first time would follow (somehow landing on the quick start page and/or this repo and then running create tauri-app@latest). Just my two cents. Thanks!

**Comment by justingolden21** [comment]
I actually still get this issue in vs code, even after installing Rust and running it just fine in command prompt, but command prompt in vs code still errors

![image](https://github.com/tauri-apps/tauri/assets/30274440/6990cdc4-1578-449d-9966-1a0bfa4bd814)

![image](https://github.com/tauri-apps/tauri/assets/30274440/3015e1d5-00a4-4ed8-8d86-1de3849aa64e)

EDIT: `echo %PATH%` has cargo in command prompt but not vs code

**Comment by AlexFilipovici** [comment]
Restart of VSCode did the job for me.

**Comment by ezecodes** [comment]
I fixed this by restarting the terminal

**Comment by Timsword** [comment]
I think rust doesn't append the env variables correctly. I just made a fresh install and i can access to rustup and cargo from powershell correctly while i cant from the intellij (it's the same powershell and restarted both C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe)

But, when I check the environment variables from both instances there is no cargo nor rustup in both.

**Comment by cretucosmin3** [comment]
I just ran against this, the only thing that worked was using powershell in windows

**Comment by kybercore** [comment]
> An important note for MacOS users. You probably have to restart or log out before rust installation will take effect. That was the case for me on Mojave 10.14.6.

This applies to Windows too. You need to reboot after installing rust.
