### ISSUE TITLE
[bug] (macOS) reset size when move cross monitor that has different scale factor

### ISSUE THREAD

**Issue by BillGoldenWater** [tauri-apps/tauri#5229]
### Describe the bug

when use Window::set_position to set to a position that have a different monitor than last position, the window's size will reset to default.

### Reproduction

1. set window size to non default size
2. set position to another monitor
3. the size will reset to default size

### Expected behavior

the size still be the same size before set pos

### Platform and versions

Environment
  › OS: Mac OS 12.6.0 X64
  › Node.js: 18.7.0
  › npm: 8.15.0
  › pnpm: 6.11.0
  › yarn: 1.22.18
  › rustup: 1.25.1
  › rustc: 1.62.0
  › cargo: 1.62.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.1.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › framework: React

App directory structure
  ├─ original
  ├─ dist
  ├─ node_modules
  ├─ script
  ├─ public
  ├─ .github
  ├─ src-tauri
  ├─ .git
  ├─ .idea
  └─ src

### Additional context

apple silicon, 2nd monitor has scaled

**Comment by Lpmvb** [comment]
I have the same problem, is there a solution?

**Comment by BillGoldenWater** [comment]
this issue is because the `suggest_size` of `scale_factor_change` event is get from a cached ns_view
and the actual ns_view is replaced by the wry

[suggest_size](https://github.com/tauri-apps/tao/blob/dev/src/platform_impl/macos/window_delegate.rs#L102) [view_size](https://github.com/tauri-apps/tao/blob/dev/src/platform_impl/macos/window_delegate.rs#L134) [ns_view](https://github.com/tauri-apps/tao/blob/dev/src/platform_impl/macos/window_delegate.rs#L64)
[wry replacing ns_view](https://github.com/tauri-apps/wry/blob/dev/src/webview/wkwebview/mod.rs#L812)

change the get method to dynamically get is fixing this issue
also fix this: [resize event in tauri](https://github.com/tauri-apps/tauri/blob/dev/core/tauri-runtime-wry/src/lib.rs#L479)

and seems the latest winit is dynamically get the ns_view by contentView [winit's impl](https://github.com/rust-windowing/winit/blob/master/src/platform_impl/macos/window_delegate.rs#L476)

@wusyong
