### ISSUE TITLE
package.metadata.bundle icon in Cargo.toml not generated/documented, clicking app.app doesn't start app.

### ISSUE THREAD

**Issue by n8jadams** [tauri-apps/tauri#523]
**Describe the bug** 
Just following the wiki (using NPM over yarn), but the need for having a `package.metadata.bundle` in `Cargo.toml` is never generated, or documented. I just added it thanks to prompts in error messages. Also, after building, (`tauri build`), opening the generated `app.app` does nothing, I have to use the terminal and run the executable (`$ PATH_TO_THE APP/app.app/Contents/MacOS/app`) to start up the app.

**Expected behavior**
I expected the generated `tauri init` script to include the following in the generated `Cargo.toml`:

```
[package.metadata.bundle]
icon = [ "icons/icon.png" ]
```

Also, I expect the app to start when I click on the built `app.app`.

**Platform and Versions (please complete the following information):**

OS: MacBook Pro (15-inch, 2019) 10.14.6 32 GB RAM
Node: v12.15.0
NPM: 6.14.3
Rustc: 1.43.0-nightly (6d69caba1 2020-02-27)

And from `tauri info`:

```
[tauri]: running info

Operating System - Darwin(18.7.0) - darwin/x64

Node.js environment
  Node.js - 12.15.0
  tauri.js - 0.4.5

Rust environment
  rustc - 1.43.0-nightly
  cargo - 1.43.0-nightly
  tauri-bundler - 0.4.4

Global packages
  NPM - 6.14.3
  yarn - 1.19.1

App directory structure
/.git
/dist
/node_modules
/src
/src-tauri

App
  tauri - 0.4
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  Windows - Edge
  distDir - ../dist
  devPath - http://localhost:4000
```

**Comment by n8jadams** [comment]
This is probably actually two separate bugs...

I can see why the app isn't opening when I open through the terminal.

```
$ /MY_PATH/src-tauri/target/release/bundle/osx/app.app
open LSOpenURLsWithRole() failed with error -10810 for the file /MY_PATH/src-tauri/target/release/bundle/osx/app.app
```

I'm going to create another issue for this. I'll leave this info here and make it more focused on the documentation/Cargo.toml generation aspect.

**Comment by nothingismagick** [comment]
@lucasfernog - this has been sorted, no?

**Comment by lucasfernog** [comment]
Yeah the open issue will be available on Tauri's next release.
