### ISSUE TITLE
[feat] Expecting an ease-to-use and out-of-the-box Wasm-aimed invoke methods.

### ISSUE THREAD

**Issue by wangxiaochuTHU** [tauri-apps/tauri#5232]
### Describe the problem

I'm always frustrated when attempting to invoke Wasm functions. The proceeding is difficult.

Besides, the proceeding varies with different frameworks (Vue, React, Next.js) and programming languages (JS, TS). It is hard to investigate.

### Describe the solution you'd like

I expect an ease-to-use and out-of-the-box Wasm-aimed invoke methods.

Tauri knows and handles the frustrating proceeding. Users can focus on functional coding only.

For example, invoking function `fn start() {};` in `my.wasm` could look like
```Typescript
const path-to-wasm-file = '../a/b/c/my.wasm';
const on_client_or_server = IS_CLIENT;
var my_wasm = load(path-to-wasm-file, on_client_or_server);
my_wasm.start();
```

**Comment by amrbashir** [comment]
tauri doesn't care about what frontend tech you're using be it vanilla javascript, framework or wasm and we don't have control over how the webview loads your wasm. We also don't want to diverge from the web conventions so you can use your app for both web and tauri with minimal changes.

If you are frustrated with the sate of loading/invoking wasm in the web, then you should open an issue in its repo
