### ISSUE TITLE
[bug] vue router does not work in tauri

### ISSUE THREAD

**Issue by Sfawn** [tauri-apps/tauri#5236]
### Describe the bug

The vue its not displaying for me

### Reproduction

npm create tauri-app
npm run tauri init
npm run tauri dev

### Expected behavior

show the vue 

### Platform and versions

> jota@0.0.0 tauri
> tauri

Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 105.0.1343.42
  › MSVC:
      - Visual Studio Community 2022
  › Node.js: 16.17.0
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../ui
  › devPath: ../ui
  › framework: Vue.js

App directory structure
  ├─ .vscode
  ├─ node_modules
  ├─ src
  ├─ src-tauri
  └─ ui

### Additional context

the original html https://codepen.io/mevdschee/pen/eYrvoGZ

![image](https://user-images.githubusercontent.com/113914035/191030555-0bc22287-95e8-4d4e-81c6-b58e048e098b.png)

**Comment by amrbashir** [comment]
can you please provide a minimal repro because your reproduction steps don't show anything related to vue-router? code snippets? have you checked for errors in the console?

**Comment by Sfawn** [comment]
i just created the project normally here https://tauri.app/v1/guides/getting-started/setup and has no error the router-view just does not appear

![image](https://user-images.githubusercontent.com/113914035/191033214-324f111e-ef01-4f50-adc3-ff0f613d0991.png)
![image](https://user-images.githubusercontent.com/113914035/191033310-4d547998-b0bc-4e94-806c-b6e244aa0469.png)
![image](https://user-images.githubusercontent.com/113914035/191033356-2dc9286b-b4ad-4757-a6d5-784f4ca4974a.png)

this is the correct form
![image](https://user-images.githubusercontent.com/113914035/191033516-1e515d91-90ab-474c-965d-616dd4f73647.png)

**Comment by amrbashir** [comment]
please share your repo, because `tauri info` shows you have a different project structure than normal tauri-app

**Comment by amrbashir** [comment]
Also I meant to check the webview dev console (right click, inspect)

**Comment by Sfawn** [comment]
jota@0.0.0 tauri
tauri

Environment
› OS: Windows 10.0.19044 X64
› Webview2: 105.0.1343.42
› MSVC:
- Visual Studio Community 2022
› Node.js: 16.17.0
› npm: 8.15.0
› pnpm: Not installed!
› yarn: Not installed!
› rustup: 1.25.1
› rustc: 1.63.0
› cargo: 1.63.0
› Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
› @tauri-apps/cli [NPM]: 1.1.1
› @tauri-apps/api [NPM]: Not installed!
› tauri [RUST]: 1.1.1,
› tauri-build [RUST]: 1.1.1,
› tao [RUST]: 0.14.0,
› wry [RUST]: 0.21.1,

App
› build-type: bundle
› CSP: unset
› distDir: ../ui
› devPath: ../ui
› framework: Vue.js

App directory structure
├─ .vscode
├─ node_modules
├─ src
├─ src-tauri
└─ ui

**Comment by Sfawn** [comment]
> Also I meant to check the webview dev console (right click, inspect)
![image](https://user-images.githubusercontent.com/113914035/191037759-80e887c7-967a-4ee2-a929-ac098dfc4676.png)
![image](https://user-images.githubusercontent.com/113914035/191037893-20a47134-04c8-4eac-a694-bdaca0a5159e.png)

**Comment by amrbashir** [comment]
> App directory structure
> ├─ .vscode
> ├─ node_modules
> ├─ src
> ├─ src-tauri
> └─ ui

This project structure looks wrong, please share your repo. I can't help otherwise, or join our discord channel where we can help you track this issue faster.

**Comment by Sfawn** [comment]
here https://github.com/Sfawn/ttauri

**Comment by Sfawn** [comment]
idk how to make a repository so [redacted]

**Comment by FabianLars** [comment]
i'm not sure what _exactly_ the problem was, but they figured it out on discord :)

**Comment by Moon1102** [comment]
@FabianLars @Sfawn  Sorry to bother you all.
<img width="1365" alt="图片" src="https://user-images.githubusercontent.com/15380331/191408179-86cd8f73-1f39-44f6-b085-d96dc96eb7e2.png">
Probably because `<template>` is not recognized as a real dom under the direct loading method of html file, which leads to a problem with vue mounting?
I think it must be a problem with the mounted element but I haven't researched too deeply either, but in my opinion this is not a recommended way to use `vue-router`, as [yarn dependecy](https://router.vuejs.org/installation.html#yarn) is better way and less error.

**Comment by FabianLars** [comment]
> Probably because <template\> is not recognized as a real dom under the direct loading method of html file, which leads to a problem with vue mounting?

Yep, and therefore a duplicate of #https://github.com/tauri-apps/tauri/issues/4410 

> but in my opinion this is not a recommended way to use vue-router

I think so too, but templates are part of the HTML spec and therefore we must support it if possible - p.s. it is possible, see #5247
