### ISSUE TITLE
app-listeners

### ISSUE THREAD

**Issue by Sombian** [tauri-apps/tauri#525]
**Is your feature request related to a problem? Please describe.**
there're so much thing you could done with such events like, on full screen, on fade and so on.

**Describe the solution you'd like**
provides event listeners.
```
fullscreen,
restore,
close,
fade,
focus,
maximize,
minimize,
resize,
move,
```

**Comment by lucasfernog** [comment]
This should be possible once we move the Rust binding to https://github.com/webview/webview, but native window management/listeners is going to take a while.

**Comment by lucasfernog** [comment]
Closing it to track it on #837
