### ISSUE TITLE
[docs] WebView Tag like electron to make new web browser

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#5260]
Is there a tag to make WebView?
Is there a special tag at all?
Why is there nothing in the guide?

**Comment by JonasKruckenberg** [comment]
As previously stated [here](https://github.com/tauri-apps/tauri/issues/2975#issuecomment-1019945044) and [here](https://github.com/tauri-apps/tauri/issues/2709) building browsers is something we don't support and we don't plan on supporting anytime soon. It just requires exorbitant amounts of engineering time to built something like this and have it be secure. https://byte.how/posts/webview-androids-most-convenient-footgun/ is an interesting article about why embedded webviews/iframes in webviews are a dangerous idea to begin with.

I would also like to point out that there is a reason why electrons `WebView` is deprecated for years now. It should not be used in electron either.

**Comment by ghost** [comment]
I want to use tauri as somthing like desktop environment for linux and i need to open websites inside tauri how most do that
