### ISSUE TITLE
[bug] Drag sort does not respond

### ISSUE THREAD

**Issue by 204065248** [tauri-apps/tauri#5261]
### Describe the bug

Hello, my English is not very good, please forgive me. I use https://github.com/SortableJS/vue.draggable.next to drag and drop the sort elements, it is the normal work in the browser. But it doesn't work in Tauri. I also want to ask why I set "transparent": true. But the window is still opaque.

### Platform and versions

yarn run v1.22.17
$ tauri info

Environment
  › OS: Windows 10.0.19042 X64
  › Webview2: Not installed!
  › MSVC: 
      - Visual Studio Community 2022
  › Node.js: 14.16.1
  › npm: 6.14.12
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Vue.js

App directory structure
  ├─ .vscode
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri

**Comment by 204065248** [comment]
https://user-images.githubusercontent.com/17307843/191705207-455cf66f-3a1e-4c08-9ab8-55ea77fca8d0.mp4

**Comment by liesauer** [comment]
same here, did you solve this? @204065248

**Comment by liesauer** [comment]
i am trying this svelte [demo](https://svelte.dev/repl/bb527bb8a2f849e19cd5956fc76bb668?version=3.32.2)

this is expected behavior and works in both chrome and edge browser.

https://user-images.githubusercontent.com/8676741/196714480-815798ee-cf26-4376-a900-dc9c93da55e3.mp4

but didn't work in tauri.

https://user-images.githubusercontent.com/8676741/196714494-eec44306-c561-4949-93b9-396c041993f6.mp4

have no clues at all.

@FabianLars

**Comment by FabianLars** [comment]
You need to disable Tauri's file drop feature by setting `"fileDropEnabled": false` in your window config

**Comment by liesauer** [comment]
> You need to disable Tauri's file drop feature by setting `"fileDropEnabled": false` in your window config

it works now! thanks for the quick response! btw, disabling this feature will still support receiving file drop for uploading?

**Comment by FabianLars** [comment]
The webviews native file drop which you know from normal browsers like chrome etc will work. Just the "tauri://file-drop" event will stop working

**Comment by liesauer** [comment]
i see, thanks!
