### ISSUE TITLE
[feat] Include the Tao `set_ignore_cursor_events` function into Tauri

### ISSUE THREAD

**Issue by guillerp8** [tauri-apps/tauri#5265]
### Describe the problem

Hello, I wrote on Discord that would be cool to have the abbility to make windows not clickable, just working as transparent ones.

### Describe the solution you'd like

 I saw that Tao included the function `set_ignore_cursor_events`  so probably would be easier to include into Tauri.
 Ref: https://github.com/tauri-apps/tao/commit/4fa8761776d546ee3b1b0bb1a02a31d72eedfa80

### Alternatives considered

- 

### Additional context

Example: 
![image](https://user-images.githubusercontent.com/72713057/191828646-99f8d8c8-1549-4833-98b0-22809493603a.png)
Thank you guys you are doing an amazing job ♥

**Comment by emhagman** [comment]
I'd love to give this a try if that's cool. Been working on my Rust lately.

```
.on_page_load(|window, _payload| {
      window.set_ignore_cursor_events(true);
})
```

Is a solution that required no extra code but I was thinking of adding this to the `windows` object on `tauri.conf.json`.

Any thoughts? It seems like this might require editing `tao`, specifically the `WindowBuilder`

**Comment by FabianLars** [comment]
Ayy the PR didn't follow our pr title guidelines (including the issue it will close in its title), so this issue wasn't closed automatically. Anyway, here it is: #5032

**Comment by emhagman** [comment]
All good, the PR is useful for me to learn :)
