### ISSUE TITLE
Can't Open App: LSOpenURLsWithRole() failed with error -10810 for the file src-tauri/target/release/bundle/osx/app.app

### ISSUE THREAD

**Issue by n8jadams** [tauri-apps/tauri#527]
**Describe the bug**
Cannot open the app due to the following bug: 
```
LSOpenURLsWithRole() failed with error -10810 for the file /absolute-path-to/src-tauri/target/release/bundle/osx/app.app.
```

If I run the binary within the `app.app/Contents` like so:
```
$ ./src-tauri/target/release/bundle/osx/app.app/Contents/MacOS/app
```
the app runs as expected.

**To Reproduce**
1. Follow the wiki steps for Mac, `$ tauri init` and all that
2. Create the following `dist/index.html`:

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<h1>Hello World From Tauri!</h1>
</body>
```

3. `$ tauri build`
4. `$ open ./src-tauri/target/release/bundle/osx/app.app`
5. Then the error message shows

**Expected behavior**
App should open normally from opening the .app file.

**Platform and Versions (please complete the following information):**
```
Operating System - Darwin(18.7.0) - darwin/x64

Node.js environment
  Node.js - 12.15.0
  tauri.js - 0.4.5

Rust environment
  rustc - 1.43.0-nightly
  cargo - 1.43.0-nightly
  tauri-bundler - 0.4.4

Global packages
  NPM - 6.14.3
  yarn - 1.19.1

App directory structure
/.git
/dist
/node_modules
/src
/src-tauri

App
  tauri - 0.4
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  Windows - Edge
  distDir - ../dist
  devPath - http://localhost:4000
```

**Comment by Reidond** [comment]
Try to `chmod +x` output binary and the open again

**Comment by n8jadams** [comment]
@Reidond Unfortunately I got the same error message. :/

**Comment by nothingismagick** [comment]
@n8jadams - can you try to create a new project with `tauri init` and make sure to transfer the new fields from the tauri.conf.json to the new one?

**Comment by Grewer** [comment]
My APP also cannot be opened, and I cannot find the error message
### tauri info:
```
Operating System - Darwin(19.3.0) - darwin/x64

Node.js environment
  Node.js - 12.16.2
  tauri.js - 0.5.2

Rust environment
  rustc - 1.42.0
  cargo - 1.42.0
  tauri-bundler - 0.5.0

Global packages
  NPM - 6.14.4
  yarn - 1.13.0

App directory structure
/.git
/.idea
/build
/config
/node_modules
/public
/scripts
/src
/src-tauri

App
  tauri - 0.5
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  Windows - Edge
  distDir - ../build
  devPath - http://localhost:8080

```

and run
```
$ ./src-tauri/target/release/bundle/osx/app.app/Contents/MacOS/app
```
the app runs

### APP opening case:
![QQ20200423-215500](https://user-images.githubusercontent.com/21995246/80107158-53346300-85ad-11ea-8b19-1724a2d70536.gif)

### example
https://github.com/Grewer/tauri-example

**Comment by nothingismagick** [comment]
can you let me know which major OSX version this is - is this 10.15?

And can you try opening from the cli?

**Comment by n8jadams** [comment]
I was using 10.14.6.

**Comment by Grewer** [comment]
my version is `macOS  Catalina 10.15.3`
and how can I open by cli ?
`./src-tauri/target/release/bundle/osx/app.app/Contents/MacOS/app` 
Using this sentence, my APP  is running normally

in the case of dev, loading via http is also normal

**Comment by n8jadams** [comment]
@Grewer you can open it with the open command

```
$ open ./src-tauri/target/release/bundle/osx/app.app
```

**Comment by nothingismagick** [comment]
So my suspicion is that our bootloader is potentially coming into conflict here.
you can test this for me by editing your `src-tauri/target/release/bundle/osx/app.app/Contents/Info.plist`

and look for this word: `__bootstrapper` and replace it with `app`

**Comment by Grewer** [comment]
@nothingismagick  This works for me

**Comment by nothingismagick** [comment]
@Grewer - the process of filing issues and working together with the community means that the bug is being fixed. Thanks to your contribution (and support in debugging) we can now consider how best to fix it. Please remember, Tauri is still alpha, so bugs are literally everywhere.

@lucasfernog - I think we need to add a configure hook in `tauri.conf.json` here for our bootstrapper. It should really be optional (only if they need to get access to the `$PATH`). That will resolve this particular issue. What do you think?

https://github.com/tauri-apps/tauri/blob/79e6f7f3f0e17f80552f047f89158f830c6f0bba/cli/tauri-bundler/src/bundle/osx_bundle.rs#L92
