### ISSUE TITLE
[feat] Windows MSI "Publisher" field?

### ISSUE THREAD

**Issue by WilliamVenner** [tauri-apps/tauri#5273]
### Describe the problem

I don't see any way to change the "Publisher" field for my application, this doesn't look very professional:

![image](https://user-images.githubusercontent.com/14863743/192049166-c9ff116c-0be6-4553-b55c-5897a2d8b2fc.png)

I assume it grabs it from the `identifier`?

### Describe the solution you'd like

I should be able to put in my actual name or company name

### Additional context

This is probably not Windows/MSI specific

**Comment by amrbashir** [comment]
We could uppercase it or do you want to explicitly set in in tauri config?

**Comment by WilliamVenner** [comment]
You should be able to actually set it. You should never assume what the user wants to put there
