### ISSUE TITLE
[feat] run embedding external binaries requires root

### ISSUE THREAD

**Issue by TonyLuo** [tauri-apps/tauri#5274]
### Describe the problem

I tried to run external binary with sidecar in macbook, stdout said tailscaled requires root, use sudo tailscaled.
```
const command = Command.sidecar("bin/tailscaled");
command.execute()
```

### Describe the solution you'd like

Is any solution to run external binary which requires root in macos (admin right in Windows) ?

**Comment by xueyc1f** [comment]
Looking forward to a good solution

**Comment by xueyc1f** [comment]
If use `pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY` the sidecar will NotFound

**Comment by amrbashir** [comment]
did you try to run your tauri app as sudo?

**Comment by xueyc1f** [comment]
> did you try to run your tauri app as sudo?

sudo is ok，but only sidecar need root permission not ok

**Comment by amrbashir** [comment]
A non-sudo app can't start another app as sudo, even if there are maybe are some workarounds, it is highly discouraged to do so and you should just ask your users to run your app as sudo.

**Comment by BranLiang** [comment]
How can we let user to run the macos app as sudo?

**Comment by archiewx** [comment]
> 

Do you have a solution?

**Comment by BranLiang** [comment]
Didn't find a good solution yet. So basically for installed app, you need to setuid for the binary. And for local testing, you need to do the same for the binary, but not for the binary in your sidecar folder, but for the binary in the `debug` folder.
