### ISSUE TITLE
[feat] updater features

### ISSUE THREAD

**Issue by BillGoldenWater** [tauri-apps/tauri#5278]
### Describe the problem

1. split updater's download and install steps
  - when download in background(in bad network condition or check and download silently), the user is still using the app, after download, need to ask user for the install, before start modify things
2. api to set arch of check
 - when running under arm64 translation(like Rosetta or WoW) need manually set to native arch
 - and universal-er way to handle universal builds

### Describe the solution you'd like

```rust
let updater_builder = app.updater()

if cfg!(target_arch = "x86_64") 
  && /* check is running under arm64 translation */
  && /* ask for switch to native arm build */ {
  updater_builder.arch("aarch64")
}

let result = updater_builder.check().await

let update = result.unwrap()

if update.is_update_available() {
  update.download(
    || {/* progress */},
    |update| { // on downloaded
      if /* user permit */ {
        update.install(|app| { // on applied
          if /* ask for restart */ {
            app.restart()
          }
        })
      }
    }
  )
}

```

### Additional context

https://github.com/tauri-apps/tauri/blob/013fb354d948fd498156c8eff12b24dd0a36b63a/core/tauri/src/updater/core.rs#L512

**Comment by FabianLars** [comment]
1) is possible in v2
2) is kinda supported via `target` in both v1 and v2

> when running under arm64 translation(like Rosetta or WoW) need manually set to native arch

that's fair i guess but imo not really something that the updater should worry about. you can do it yourself with the sysctl crate (ref https://gist.github.com/steipete/e15b1fabffc7da7d49c92e3fbd06971a)

> and universal-er way to handle universal builds

that's tricky, i don't think there's an alternative to the `file` cli command to detect the binary type. But all i can think of is already possible:
- You only ship universal apps, including the updater artifact -> set `target` to `darwin-universal`, or have the json endpoint point to the universal binary for both archs.
- You ship universal apps initially, but want to update to non-universal -> nothing to do, just have both archs in the updater endpoint
