### ISSUE TITLE
[feat] How do I know if a window is hidden or shown

### ISSUE THREAD

**Issue by DWHengr** [tauri-apps/tauri#5284]
### Describe the problem

How do I know if a window is hidden or shown

### Describe the solution you'd like

I want to change the window state through the shortcut key.

like:
```
  short_cut.register("alt+space", move || {
    let window = app_handler.get_window("main").unwrap();
    match window.get_status() {
      HIDE=>{ window.show().unwrap(); }
      SHOW=>{ window.hide().unwrap(); }
      _ => {}
    }
  });
```

**Comment by JonasKruckenberg** [comment]
Unless I'm missing something about your request, [`Window.is_visible()`](https://docs.rs/tauri/1.1.1/tauri/window/struct.Window.html#method.is_visible) (or `Window.isVisible()` from the JS API) is exactly the method you are looking for
