### ISSUE TITLE
[bug] The icon resolution is too low

### ISSUE THREAD

**Issue by DWHengr** [tauri-apps/tauri#5287]
### Describe the bug

The resolution of the icon after the build is too low. Icon indicates the icon picture, and flash indicates the application icon after the build.

![image](https://user-images.githubusercontent.com/55067857/192538272-d81a4847-cd46-40a1-a432-83fd4ba15c34.png)

### Platform and versions

Environment
  › OS: Windows 10.0.19043 X64
  › Webview2: 105.0.1343.50
  › MSVC:
      - Visual Studio Community 2022
  › Node.js: 14.15.4
  › npm: 6.14.10
  › pnpm: 7.9.5
  › yarn: 1.22.17
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React

App directory structure
  ├─ .git
  ├─ .idea
  ├─ .vscode
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri

**Comment by FabianLars** [comment]
Which tauricon did you use to generate the icon? The old `@tauri-apps/tauricon` npm package or the icon command that's built into the main cli?

Is `icon.png` a generated icon or the _input_ image?

**Comment by DWHengr** [comment]
Icon is completed by PS and replaced with the original icon.
