### ISSUE TITLE
[bug] Unable to run `yarn tauri dev`

### ISSUE THREAD

**Issue by AdnaneSaber** [tauri-apps/tauri#5294]
### Describe the bug
using tauri with next app typescript when I run `yarn tauri dev` i get this after the next server finishes compiling
`Finished dev [unoptimized + debuginfo] target(s) in 6m 58s`
```thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 216, kind: Uncategorized, message: "This version of %1 is not compatible with the version of Windows currently running. Check in your computer's system information, then contact the software publisher." }', src\interface\rust\desktop.rs:46:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

### Reproduction

`yarn tauri dev`

### Platform and versions

Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 105.0.1343.53
  › MSVC:
      - Visual Studio Build Tools 2017
  › Node.js: 16.17.0
  › npm: 8.18.0
  › pnpm: Not installed!
  › yarn: 1.22.11
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React (Next.js)
  › bundler: Webpack

App directory structure
  ├─ .next
  ├─ .vscode
  ├─ node_modules
  ├─ src
  └─ src-tauri
Done in 9.76s.

### Additional context

The server runs fine on the web

**Comment by FabianLars** [comment]
You need at least version 2019 of the VS Build Tools because some of our dependencies (most importantly the webview bindings) require it.

(p.s. we know that the error message is not clear enough)

**Comment by AdnaneSaber** [comment]
@FabianLars I have upgraded VS Build tools to 2022 as show in the [prerequisites tutorial](https://tauri.app/v1/guides/getting-started/prerequisites/) everything seems to be the same still
yarn run v1.22.11
$ tauri info

Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 103.0.1264.37
  › MSVC:
      - Visual Studio Build Tools 2022
  › Node.js: 16.17.0
  › npm: 8.18.0
  › pnpm: Not installed!
  › yarn: 1.22.11
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React (Next.js)
  › bundler: Webpack

App directory structure
  ├─ .next
  ├─ .vscode
  ├─ node_modules
  ├─ src
  └─ src-tauri
Done in 24.93s.

**Comment by FabianLars** [comment]
Can you try deleting the `target/` directory? After that there shouldn't be any reason for it to print that exact error message anymore 🤔

**Comment by AdnaneSaber** [comment]
I removed and restarted the whole project since it's a new project, it worked just fine after a fresh start.
Thank you @FabianLars 😄

**Comment by Gcalolin** [comment]
I finally run success after update VS Build Tools version and remove the ` target` directory
