### ISSUE TITLE
[bug] Js file apis, do not work in production on Ubuntu 22.04.

### ISSUE THREAD

**Issue by skopz356** [tauri-apps/tauri#5304]
### Describe the bug

Js file apis, dont work on Ubuntu 22.04.1 LTS in production. The app directory is not created. I have built the app on debian and test it on ubuntu. On debian it work smothly.

### Reproduction

1. Create new tauri app 
2. Enable all apis in tauri.conf.json.
3. Use `writeTextFile`, `readTextFile` of @tauri-apps/api. with `{dir: BaseDirectory.App}`.
4. Create production build. 
5. After installing the production app, the app directory with identifier is not created. 

### Expected behavior

The api should create app directory. 

### Platform and versions

Environment
  › OS: Debian 11 X64
  › Node.js: 16.17.0
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: default-src 'self'; img-src 'self' asset: https://asset.localhost; media-src 'self' asset: https://asset.localhost; style-src 'nonce-vuetify-csp-nonce';
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: Vue.js

App directory structure
  ├─ public
  ├─ node_modules
  ├─ src-tauri
  ├─ dist
  ├─ .idea
  ├─ src
  └─ .git

### Additional context

![image](https://user-images.githubusercontent.com/36794259/193040913-b3a5dbf5-ccd7-49d4-8231-6005020583bc.png)
I have built the app on Debian and the tested it on Ubuntu 22.04.1 LTS.

**Comment by amrbashir** [comment]
We can't guarantee that the parent directory will always exists so you have to account for that in your logic. You can use [`createDir`](https://tauri.app/v1/api/js/fs/#createdir) or [`exists`](https://tauri.app/v1/api/js/fs/#exists) to ensure the path you want exists and valid

**Comment by skopz356** [comment]
Yeah, I undestand that subdirectories may not exists. But I am talking about the $APP directory. The $APP directory should always exists right?

**Comment by FabianLars** [comment]
Nope. It's just a path we recommend for app configs etc.
