### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by qyvip** [tauri-apps/tauri#5307]
### Describe the bug

![image](https://user-images.githubusercontent.com/7900119/193177307-7a531f11-4f49-41d6-9b58-bc576ea07b7b.png)

I compiled and ran the official example - vue todos under Ubuntu 22.04. After the first run, I found that the toolbar displayed in a transparent color and the file name behind it. After switching the activation status of the window, the toolbar displayed normally

### Platform and versions

> tauri "info"

Environment
  › OS: Ubuntu 22.04 X64
  › Node.js: 16.17.0
  › npm: 8.15.0
  › pnpm: 7.12.2
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: Vue.js

App directory structure
  ├─ src-tauri
  ├─ docs
  ├─ public
  ├─ dist
  ├─ src
  └─ node_modules

**Comment by FabianLars** [comment]
Fixed in https://github.com/tauri-apps/tao/issues/567
