### ISSUE TITLE
Resource file (python) can not access to another resource file (.png) [bug] 

### ISSUE THREAD

**Issue by data987** [tauri-apps/tauri#5310]
### Describe the bug

I'm using the `resource` to trigger a python file and it works but the python file needs to access to multiple images

### tauri.conf

```json
"tauri": {
    "allowlist": {
      "all": true,
      "shell": {
        "all": false,
        "execute": true,
        "open": false,
        "sidecar": true,
        "scope": [
          {
            "name": "opencv",
            "cmd": "python",
            "args": [
              "assets/opencv.py"
            ]
          }
        ]
      }
    },
    "bundle": {
      ...,
      "resources": [
        "assets/*",
        "assets/images/img_two/*.png"
      ],
``` 

### resources

![Screen Shot 2022-09-30 at 7 13 04 AM](https://user-images.githubusercontent.com/8518699/193267050-10410c7a-026e-4c51-84c4-1f0ab6def9ad.png)

### python file (opencv.py)

```python
find_objects = MultipleVision("images/img_two/*.png") # images path

self.needle_imgs = [cv.imread(file, cv.IMREAD_UNCHANGED) for file in glob.glob(needle_img_path)]
self.needle_imgs_text = [str(file).split('.')[0] for file in glob.glob(needle_img_path)]
print(self.needle_imgs) # here I try to print the images
```
I try to print the images, if I run the command in the console (python opencv.py) it works but in tauri It can not get the images

![Screen Shot 2022-09-30 at 7 11 55 AM](https://user-images.githubusercontent.com/8518699/193266884-bb13e800-0023-41ab-9a4d-c6e15a8bc74f.png)

### Reproduction

1. Trigger the command
2. The python file is executed
3. The python file can not get the images

### Platform and versions

```terminal
➜ yarn tauri info
yarn run v1.22.19

Environment
  › OS: Mac OS 12.3.1 X64
  › Node.js: 18.1.0
  › npm: 8.8.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ build
  ├─ .git
  └─ src
✨  Done in 10.00s.
```

**Comment by amrbashir** [comment]
try printing the working directory from the python script and see if it matches the app directory where the resources located, if not, then you need to spawn the sidecar there or modify the path you're reading in the python script.

**Comment by data987** [comment]
well, your comment gave me a solution and now it worked! I used this path for getting the images, thank you so much!!

`custom_path = f'{os.getcwd()}/assets/images/img_two/*.png'`
