### ISSUE TITLE
[bug] Windows 11 - Bundle identifier folder not being created in `configDir` or `appDir` 

### ISSUE THREAD

**Issue by rajatkulkarni95** [tauri-apps/tauri#5326]
### Describe the bug

As per the docs the [appDir should open](https://tauri.app/v1/api/js/path/#appdir) `configDir/bundleIdentifier`, however it just opens `User/AppData/Roaming` with no sign of the bundle identifier named folder being visible.

Use case is that I want to store some config related data (folder paths/directories and names) related to my App in this easily accessible place. If this isn't it, where should it be placed? If `appDir` is the place, how do I bring my folder to be present there

`tauri.conf.json`
```
{
  "$schema": "../node_modules/@tauri-apps/cli/schema.json",
  "build": {
    "beforeBuildCommand": "yarn build",
    "beforeDevCommand": "yarn dev",
    "devPath": "http://localhost:1420",
    "distDir": "../dist",
    "withGlobalTauri": false
  },
  "package": {
    "productName": "Drafts",
    "version": "0.1.0"
  },
  "tauri": {
    "allowlist": {
      "fs": {
        "all": true,
        "scope": [
          "**"
        ]
      },
      "path": {
        "all": true
      },
      "dialog": {
        "all": true
      }
    },
    "bundle": {
      "active": true,
      "category": "Productivity",
      "copyright": "",
      "deb": {
        "depends": []
      },
      "externalBin": [],
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "identifier": "dev.drafts.ink",
      "longDescription": "",
      "macOS": {
        "entitlements": null,
        "exceptionDomain": "",
        "frameworks": [],
        "providerShortName": null,
        "signingIdentity": null
      },
      "resources": [],
      "shortDescription": "",
      "targets": "all",
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "security": {
      "csp": null
    },
    "updater": {
      "active": false
    },
    "windows": [
      {
        "fullscreen": false,
        "height": 768,
        "resizable": true,
        "title": "Drafts",
        "width": 1280
      }
    ]
  }
}
```

Tried installing the `.msi` file from the `yarn tauri build` script, thinking the folder doesn't get created in `dev` but didn't work.

Awesome framework btw! Just need to get over this small hill :)

### Expected behavior

Should see the bundle identifier named folder in the `appDir` (per the docs)

### Platform and versions

```
Environment
  › OS: Windows 10.0.22622 X64
  › Webview2: 105.0.1343.53
  › MSVC: 
      - Visual Studio Build Tools 2022
  › Node.js: 16.13.1
  › npm: 6.14.9
  › pnpm: Not installed!
  › yarn: 1.22.10
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React (Next.js)
  › bundler: Webpack

App directory structure
  ├─ .git
  ├─ .next
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

**Comment by FabianLars** [comment]
appDir only returns the path to the suggested directory, but Tauri does _not_ create the folder for you! You need to use `createDir` to create it yourself.

**Comment by rajatkulkarni95** [comment]
@FabianLars Thanks for the quick response.
So the ideal flow would be,
1. Mount app
2. Check if `appDir/${myAppName}` folder exists
3. Create if it doesn't.
4. Store all my configs there?

Or is there a different documented approach to how best to handle this?

**Comment by rajatkulkarni95** [comment]
Also, since the docs are then misleading, mind if I open a PR for it? Since the `configDir/${bundleIdentifier}` doesn't actually happen?

**Comment by FabianLars** [comment]
> So the ideal flow would be, ...

Yes but the `exists` check is optional because `createDir` shouldn't overwrite the folder if it exists already.

> Also, since the docs are then misleading, mind if I open a PR for it? Since the configDir/${bundleIdentifier} doesn't actually happen?

What do you suggest changing it to? The docs doesn't mention that the dir will be created for you or am i missing something?

**Comment by rajatkulkarni95** [comment]
> What do you suggest changing it to? The docs doesn't mention that the dir will be created for you or am i missing something?

Specifically this line indicates that the folder with the name `bundleIdentifier` will be resolved back. Kinda reads like I'd get the entire path with the bundle name also attached to it

```
Returns the path to the suggested directory for your app config files. Resolves to ${configDir}/${bundleIdentifier}, where bundleIdentifier is the value [tauri.bundle.identifier](https://tauri.app/v1/api/config/#bundleconfig.identifier) is configured in tauri.conf.json.
```

Maybe remove the `bundleIdentifier` related lines and just state
```Returns the path to the suggested directory for your app config files. Resolves to `configDir` ```

**Comment by rajatkulkarni95** [comment]
The reason this ticket was created is because the `bundleIdentifier` line caused confusion when I couldn't see it! Removing it since it adds no value (my assumption) would make it simpler to understand. Optionally add a disclaimer that `you can create a folder here to store app related config using the createDir function`

**Comment by FabianLars** [comment]
> Kinda reads like I'd get the entire path with the bundle name also attached to it

But that's exactly what it does, it returns the _path_, like `C:\Users\username\AppData\Roaming\com.bundle.identifier`. But it's only the path, and it doesn't create the folder for you

**Comment by rajatkulkarni95** [comment]
Oh! Got it! Okay maybe last edit?

Returns the path to the suggested directory for your app config files. Resolves to ${configDir}/${bundleIdentifier}, where bundleIdentifier is the value [tauri.bundle.identifier](https://tauri.app/v1/api/config/#bundleconfig.identifier) is configured in tauri.conf.json. `Tauri does not create the bundleIdentifier folder for you here, but rather just returns the path if it exists. You can if you wish to, create the folder using createDir function`

Does this make it better?

**Comment by FabianLars** [comment]
Hmm idk, in theory we'd need to add that warning to all other methods too then because you can never expect the paths to actually exist on the file system (at least on Linux, on Windows it's basically impossible to not have the AppData folder).

**Comment by rajatkulkarni95** [comment]
Okay! Atleast we'd have this issue present if someone fumbles like I did!

Appreciate you helping me out on a weekend! Cheers!
