### ISSUE TITLE
[bug] Alt key event

### ISSUE THREAD

**Issue by wahur666** [tauri-apps/tauri#5327]
### Describe the bug

Canvas will not get event after ALT is pressed.

### Reproduction

1. Create a view with canvas (example is react)
```html
<canvas id={"cv1"} ref={this.canvas}/>
```
2. Add event listener
```js
this.canvas.current?.addEventListener("mousemove", (ev) => {
    console.log(ev)
})
```
3. Check dev console output, and press ALT
4. No mousemove is emitted until clicked back

### Expected behavior

Pressing ALT emits event? or the canvas still gets events? Unclear

### Platform and versions

Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 105.0.1343.53
  › MSVC: 
      - Visual Studio Build Tools 2022
  › Node.js: 16.14.0
  › npm: 8.3.1
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React

### Additional context

The app I'm building, is capturing the cursor, and want to release it when the app loses focus, but when ALT is pressed, the canvas no longer receives events, neither the blur event fired, to release the cursor.

**Comment by amrbashir** [comment]
On Windows, the `Alt` key is used for system commands such as `Alt+F4`, `Alt+Space`...etc so when pressing `Alt`, the webview loses input momentarily until the combination ends.

**Comment by Arxoto** [comment]
> On Windows, the `Alt` key is used for system commands such as `Alt+F4`, `Alt+Space`...etc so when pressing `Alt`, the webview loses input momentarily until the combination ends.

Is there a way to let the webview do not lose the input ?

**Comment by edelvarden** [comment]
> Is there a way to let the webview do not lose the input ?

@Arxoto, you can use `e.preventDefault()` with the `'keyup'` event and block it `if e.key === 'Alt'`. However, this completely blocks the Alt key as a modifier, which is not ideal for apps with hotkeys.

How I block Alt key to prevent lose inputs and allow it with modifiers:

```typescript
  const [isModifier, setIsModifier] = useState(false);

  const handleKeyDown = (e) => {
    if (e.key !== 'Alt') setIsModifier(true);
  };

  const handleKeyUp = (e) => {
    if (e.key === 'Alt' && !isModifier) {
      e.preventDefault(); // Prevent default if no other key is pressed
    }
    setIsModifier(false);
  };

  useEffect(() => {
    window.addEventListener('keydown', handleKeyDown);
    window.addEventListener('keyup', handleKeyUp);

    return () => {
      window.removeEventListener('keydown', handleKeyDown);
      window.removeEventListener('keyup', handleKeyUp);
    };
  }, [isModifier]);
```
1. `handleKeyDown` checks if the pressed key is not Alt, setting a flag when any other key is pressed.
2. `handleKeyUp` checks if Alt was released without any other key being pressed. If so, it prevents the default behavior (which might cause input loss).
