### ISSUE TITLE
Window size become 0 after scale factor change[bug] 

### ISSUE THREAD

**Issue by ysinsane** [tauri-apps/tauri#5328]
### Describe the bug

WIndow almost disapper when changing the scale factor 

### Reproduction

Replay steps:

1. Set the windows.width to 1280(800 works fine)
2. change the scale factor from 1.5 to 1
3. tauri hello world window almost disapper

As you can see, window almost disapper
![image](https://user-images.githubusercontent.com/22684009/193466105-02953e75-0c08-4a9e-8774-b8c97505cb7e.png)

### Expected behavior

Window zoom with the scale factor.

### Platform and versions

Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 105.0.1343.53
  › MSVC: 
      - Visual Studio Enterprise 2022
  › Node.js: 16.17.0
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: []
  › devPath: []

App directory structure
  ├─ .changes
  ├─ .devcontainer
  ├─ .docker
  ├─ .git
  ├─ .github
  ├─ .husky
  ├─ .scripts
  ├─ .vscode
  ├─ audits
  ├─ core
  ├─ examples
  ├─ target
  └─ tooling

**Comment by amrbashir** [comment]
Can't reproduce, please provide a minimal repro.

**Comment by EntenKoeniq** [comment]
Same issue in development mode.

Screen resolution > 1080P > Change resolution to 2160P and zoom 100% > bug.

OS: Windows 11 (latest update)
Driver: AMD Adrenalin 22.11.2
