### ISSUE TITLE
[bug] Custom protocols with names beside default name "asset" don't work.

### ISSUE THREAD

**Issue by DhansAL** [tauri-apps/tauri#5333]
### Describe the bug

Function `convertFileSrc` from `@tauri-apps/api/tauri` does not works with custom named protocols.

For example , 

```typescript
import { convertFileSrc} from "@tauri-apps/api/tauri";
import { downloadDir } from '@tauri-apps/api/path';
const imagePath = await downloadDir();

function App() {
  return (
    <div>
          <img src={convertFileSrc(`${imagePath}testing.jpg`, "customprotocol")}  alt="sample image" />
      </div>
  );
}

export default App;
```
As mentioned in function description, fn `convertFileSrc` resolves the path and takes a second argument in case we need a different name besides the default **asset** name for our protocol. the argument **customprotocol** is used above.

the path resolved by the function is
`https://customprotocol.localhost/C%3A%5CUsers%5CMYUSERNAME%5CDownloads%5Ctesting.jpg`

**THIS WORKS FINE IF NO ARGUMENT IS PASSED FOR CUSTOM PROTOCOL NAME.** i.e it works for **asset**: protocol name

I have taken all the steps mentioned in docs for applying custom protocol.

Tauri.conf.json
```json  {
  "build": {
    "beforeDevCommand": "yarn dev",
    "beforeBuildCommand": "yarn build",
    "devPath": "http://localhost:1420",
    "distDir": "../dist",
    "withGlobalTauri": false
  },
  "package": {
    "productName": "myapp",
    "version": "0.0.0"
  },
  "tauri": {
    "allowlist": {
      "all": true,
      "protocol": {
        "all": true,
        "asset": true,
        "assetScope": ["**"]
      }
    },
    "bundle": {
      "active": true,
      "category": "DeveloperTool",
      "copyright": "",
      "deb": {
        "depends": []
      },
      "externalBin": [],
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "identifier": "com.tauri.dev",
      "longDescription": "",
      "macOS": {
        "entitlements": null,
        "exceptionDomain": "",
        "frameworks": [],
        "providerShortName": null,
        "signingIdentity": null
      },
      "resources": [],
      "shortDescription": "",
      "targets": "all",
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "security": {
      "csp": "default-src 'self'; img-src 'self' asset: customprotocol: https://asset.localhost https://customprotocol.localhost"
    },
    "updater": {
      "active": false
    },
    "windows": [
      {
        "fullscreen": false,
        "height": 600,
        "resizable": true,
        "title": "myapp",
        "width": 800
      }
    ]
  }
}
```

error in console (webview)

```  
GET https://customprotocol.localhost/C%3A%5CUsers%5CMYUSERNAME%5CDownloads%5Ctesting.jpg net::ERR_CONNECTION_REFUSED
```

Network Request made
```
Request URL: https://customprotocol.localhost/C%3A%5CUsers%5CMYUSERNAME%5CDownloads%5Ctesting.jpg
Referrer Policy: strict-origin-when-cross-origin
Provisional headers are shown
Learn more
Referer: http://localhost:1420/
sec-ch-ua: "Microsoft Edge";v="105", "Not)A;Brand";v="8", "Chromium";v="105", "Microsoft Edge WebView2";v="105"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.53
```

### Reproduction

Mentioned above.

### Expected behavior

File should be loading for protocol names beside `asset://`. 

### Platform and versions

Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 105.0.1343.53
  › MSVC: 
      - Visual Studio Build Tools 2022
  › Node.js: 16.17.1
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: default-src 'self'; img-src 'self' asset: customprotocol: https://asset.localhost https://customprotocol.localhost
  › distDir: ../dist
  › devPath: http://localhost:1420/

App directory structure
  ├─ .vscode
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri

**Comment by amrbashir** [comment]
did you register the custom protocol in rust?

**Comment by DhansAL** [comment]
No, is that something i missed? can you please provide more info on this?

**Comment by FabianLars** [comment]
@DhansAL <https://docs.rs/tauri/latest/tauri/struct.Builder.html#method.register_uri_scheme_protocol> that's what handles the requests to custom schemes.

Also, the url is correct. On Windows it's `https://(scheme).localhost/` instead of `(scheme)://`

**Comment by DhansAL** [comment]
thanks. can you give me an example rust function for the same? there is no example for this in docs 
@FabianLars

**Comment by NaokiM03** [comment]
It seems that some people have arrived at this page from articles and search results regarding custom protocols.

With the following pull request, it is now `http://(scheme).localhost/` instead of `https://(scheme).localhost/` on Windows.
https://github.com/tauri-apps/wry/pull/994
