### ISSUE TITLE
Error after 30 seconds of fetch execution.

### ISSUE THREAD

**Issue by roiiiu** [tauri-apps/tauri#5344]
### Describe the bug

I have a long executing request on my Go backend and once the fetch request takes more than 30 seconds, I get this error. With axios everything works fine.
<img width="987" alt="image" src="https://user-images.githubusercontent.com/11494827/193809166-f12eeb01-62b5-4557-9819-db4604164477.png">

```ts
await fetch('http://localhost:8080/g4', {
    method: 'POST',
  })
```
```go
r := gin.Default()
r.POST("/g4", func(c *gin.Context) {
    time.Sleep(40 * time.Second)
}
```

### Platform and versions

Environment
  › OS: Mac OS 12.6.0 X64
  › Node.js: 18.10.0
  › npm: 8.19.2
  › pnpm: 7.13.0
  › yarn: 1.22.19
  › rustup: Not installed!
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Vue.js

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  └─ src

**Comment by FabianLars** [comment]
As far as i know `attohttpc` (the http client our fetch implementation uses by default) has a default timeout of 30 seconds. You could try changing the request timeout to a higher number or to 0 which _should_ disable it:
```ts
await fetch('http://localhost:8080/g4', {
    method: 'POST',
    timeout: 60
  })
```

**Comment by roiiiu** [comment]
> 
I have tried but this doesn't work and the error report for timeout is not the same.
<img width="521" alt="image" src="https://user-images.githubusercontent.com/11494827/193813997-a8e21ad1-9a3c-497e-b676-fd5b1fde5d3f.png">

**Comment by FabianLars** [comment]
Can you try the reqwest client then to check if it's not related to [attohttpc#118](https://togithub.com/sbstp/attohttpc/issues/118#issuecomment-1120271936). You can switch the client by adding the `"reqwest-client"` feature flag to the tauri dependency in Cargp.toml

**Comment by roiiiu** [comment]
> Can you try the reqwest client then to check if it's not related to [attohttpc#118](https://togithub.com/sbstp/attohttpc/issues/118#issuecomment-1120271936). You can switch the client by adding the `"reqwest-client"` feature flag to the tauri dependency in Cargp.toml

Yes,it worked now,Thanks!

**Comment by FabianLars** [comment]
attohttpc will be removed in tauri v2: https://github.com/tauri-apps/tauri/pull/6468
