### ISSUE TITLE
[feat] [macOS] Add an option to configure `acceptsFirstMouse`

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tauri#5347]
### Describe the problem

Add a way to pass `acceptsFirstMouse` to macOS windows

### Describe the solution you'd like

Expose https://github.com/tauri-apps/wry/issues/714

**Comment by adityanain29** [comment]
Hi, I would like to work on this.
Since I am a beginner i have very little idea about what to do.
Could you guide me on this.
I would learn all the necessities to solve this issue!

**Comment by amrbashir** [comment]
@adityanain29 thanks for wanting to contribute, this issue should wait until a new WRY version is published. However you can work on it and change the `wry` dependency here https://github.com/tauri-apps/tauri/blob/dev/core/tauri-runtime-wry/Cargo.toml to point to the WRY git repo and make your changes. You can also take this PR https://github.com/tauri-apps/tauri/pull/5317 as inspiration on how to do it

**Comment by adityanain29** [comment]
thanks for the info.
I would try to work accordingly

**Comment by lucasfernog** [comment]
@adityanain29 sorry I didn't see your message and pushed a PR for this: #5374 :(

**Comment by adityanain29** [comment]
Np. I would try to contribute in some other way to this project.
