### ISSUE TITLE
[docs] Clarify package list for debian/ubuntu

### ISSUE THREAD

**Issue by smj-edison** [tauri-apps/tauri#5349]
Hi! I recently started using Tauri, and installing the packages listed under Debian verbatim didn't work for me. Adding the postfix `-dev` fixed it for me, but I could see that potentially being a stumbling block for someone creating their first project. Would it be possible to update the documentation?

**Comment by amrbashir** [comment]
Not sure where you got the instructions without `-dev` but out official docs use it. see https://tauri.app/v1/guides/getting-started/prerequisites#setting-up-linux
