### ISSUE TITLE
[bug] cargo run --example streaming isn't working on linux (tested on ubuntu, archlinux)

### ISSUE THREAD

**Issue by WuuBoLin** [tauri-apps/tauri#5352]
### Describe the bug

I am interested in the Tauri streaming feature; I run the `cargo run --example streaming`. The window with the video player opened, but no video is shown. It was downloaded, and the mp4 file is working (verified in another video player), but playback/streaming in the Tauri example seems not to work. 

I tried in macOS and Windows and it all works, but in Linux(Arch vanilla, Manjaro, Ubuntu22.04) won't work.

### Platform and versions

**Environment**
  › OS: Arch Linux Rolling Release X64
  › Node.js: 16.13.2
  › npm: 8.15.1
  › pnpm: 6.32.3
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

**Packages**
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

**App**
  › build-type: bundle
  › CSP: unset
  › distDir: []
  › devPath: []

**App directory structure**
  ├─ target
  ├─ .docker
  ├─ .vscode
  ├─ .changes
  ├─ .devcontainer
  ├─ .github
  ├─ core
  ├─ .git
  ├─ .husky
  ├─ .scripts
  ├─ audits
  ├─ examples
  └─ tooling

**Comment by amrbashir** [comment]
Streaming doesn't work on Linux because it doesn't have headers support see https://github.com/tauri-apps/wry/issues/422

**Comment by WuuBoLin** [comment]
Yes, I just found out this is the reason.
But maybe notice this in the readme section of the example? Cause I only see a little comment on line 87 of the source code.

> // Actually only macOS and Windows are supported. Linux will ALWAYS return empty headers.

**Comment by amrbashir** [comment]
yeah sure, feel free to PR it

**Comment by FabianLars** [comment]
I think it's actually https://github.com/tauri-apps/tauri/issues/3725
the streaming example used to work on Linux too, it just didn't stream the file but pushed the whole file at once instead.

**Comment by WuuBoLin** [comment]
Yeah, that's what I thought at first, on line 109 it read the whole file to buffer and sent status code 200 to the front end.
But what I got in the network tab is the same as [#3725](https://github.com/tauri-apps/tauri/issues/3725).
