### ISSUE TITLE
Identifier not carried over to Wix installer

### ISSUE THREAD

**Issue by nblackburn** [tauri-apps/tauri#536]
**Describe the bug**
On Windows the identifier defined in `tauri.conf.json` is not carried over to the Wix installer causing it to fail when building.

```
warning: MSI bundle support is still experimental.
info: Verifying wix package
info: Downloading https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
info: validating hash
info: extracting WIX
info: Target: x64
info: running candle for main.wxs
info: Windows Installer XML Toolset Compiler version 3.11.2.4516
info: Copyright (c) .NET Foundation and contributors. All rights reserved.
info:
info: main.wxs
info: C:\Users\[user]\Desktop\tauri-svelte\src-tauri\target\release\wix\x64\main.wxs(12) : error CNDL0006 : The Product/@Manufacturer attribute's value cannot be an empty string. If a value is not required, simply remove the entire attribute.
error: error running candle.exe

 app:spawn Command "cargo" failed with exit code: 1 +1ms

 app:tauri (template) ⚠️  [FAIL] Cargo CLI has failed +1ms
```

**Expected behavior**
The identifier should be used for the `Manufacturer` field as intended.

**Platform and Versions (please complete the following information):**

OS: Windows 10
Node: 12.16.0
NPM: 6.14.4
Yarn: 1.22.4
Rustc: rustc 1.42.0 (b8cedc004 2020-03-09)

**Additional context**
Can be fixed by specifying the identifier in `Cargo.toml`.

```toml
[package.metadata.bundle]
identifier = "com.example.app"
```

**Comment by lucasfernog** [comment]
I believe this was fixed. Here's the code:

https://github.com/tauri-apps/tauri/blob/46ea86b63afcd86f02c3d8a70642c543634f606a/cli/tauri-bundler/src/bundle/wix.rs#L415

https://github.com/tauri-apps/tauri/blob/46ea86b63afcd86f02c3d8a70642c543634f606a/cli/tauri-bundler/src/bundle/templates/main.wxs#L18
