### ISSUE TITLE
[bug] Selecting SystemTrayItem Not Working If Not Defined As Selected

### ISSUE THREAD

**Issue by Arian94** [tauri-apps/tauri#5360]
### Describe the bug

On Ubuntu 22, If a systemTray item is not defined as `selected`, it cannot not be set to `selected` on Click Event using the `set_selected(true)` method.

### Reproduction

```rust
let show_hide = CustomMenuItem::new("show_hide", "Hide");

//...building tauri
    .on_system_tray_event(move |app, event| match event {
            SystemTrayEvent::MenuItemClick { id, .. } => {
                let item_handle = app.tray_handle().get_item(&id);
                let window = app.get_window("main").unwrap();

                match id.as_str() {
                    "show_hide" => {
                        item_handle.set_title("Show").unwrap();
                        item_handle.set_selected(true).unwrap();    //* This will not set it to selected (no tick icon before the title)
                    }
                   // ...
                }
           }
    }
```

### Expected behavior

If a tray item is not defined as selected, a tick icon should be shown before its title when using `set_selected(true)`.
**NOTE:** If the item is `SELECTED` when defiend (ie. 
```rust
let show_hide = CustomMenuItem::new("show_hide", "Hide").selected();
```
),
it will correctly select and unselect regardless of using  `set_selected(true)` or  `set_selected(false)` on each click event.

### Platform and versions

yarn run v1.22.19
warning ../../package.json: No license field
$ tauri info

Environment
  › OS: Ubuntu 22.04 X64
  › Node.js: 14.17.0
  › npm: 8.1.1
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ["../dist","../preview.html","../icon.png"]
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ dist
  ├─ .git
  ├─ src-tauri
  ├─ node_modules
  └─ src

**Comment by amrbashir** [comment]
That's a known limitation of our current API and we are working on an improved menus API where there is a distinction between normal `TextMenuItem` and `CheckMenuItem`. It is however planned for tauri@v2 because we can't break the existing API for v1.
