### ISSUE TITLE
[bug] refactor the repo based tauri + yew created by create-tauri-app to workspace repo can not run

### ISSUE THREAD

**Issue by jaylenchen** [tauri-apps/tauri#5375]
### Describe the bug

Hi, I'm developing a  tool based tauri+yew which created by create-tauri-app cli.
I refactored it into a workspace repo，but when I run `cargo tauri dev`，the terminal will always show the info
`Waiting for your frontend dev server to start on http://localhost:1420/`.
I checked all of the packages of the repo, but can not find anything wrong, can you help me to solve the problem ?

### Platform and versions

Environment
  › OS: Mac OS 12.1.0 X64
  › Node.js: 14.18.1
  › npm: 6.14.15
  › pnpm: 7.4.0
  › yarn: 1.22.18
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-apple-darwin

App directory structure
  ├─ target
  ├─ switch-env-tauri
  ├─ switch-env-ui
  ├─ switch-env-cli
  ├─ .git
  └─ .vscode

### Additional context

this is the workspace repo：
<img width="796" alt="截屏2022-10-09 上午10 33 50" src="https://user-images.githubusercontent.com/72691225/194734899-3dbe5f58-9e4b-4f0b-b001-6c307936f45e.png">

this is the switch-env-cli package:
<img width="796" alt="截屏2022-10-09 上午10 35 18" src="https://user-images.githubusercontent.com/72691225/194734935-018cf29d-e83a-4e18-ad15-79b50041b2ce.png">

this is the switch-env-tauri package and the tauri.config.json(tauri) :
<img width="980" alt="截屏2022-10-09 上午10 35 59" src="https://user-images.githubusercontent.com/72691225/194734952-b006b737-7554-4b97-8fe0-9d1cc47f2a22.png">

this is the switch-env-ui package(yew):
<img width="980" alt="截屏2022-10-09 上午10 36 40" src="https://user-images.githubusercontent.com/72691225/194734965-3b15c213-4bfd-4b3d-82f2-6498d154d83b.png">

in my repo, I want to run `cargo tauri dev`, it will run package switch-env-cli first, then run `trunk serve switch-env-ui/index.html`, but when I finish it， the terminal will always show the info `Waiting for your frontend dev server to start on http://localhost:1420/`

I also see another [issue](https://github.com/tauri-apps/tauri/issues/3491), but it not work on me. 

this is my .taurignore:
<img width="980" alt="截屏2022-10-09 上午10 40 50" src="https://user-images.githubusercontent.com/72691225/194735132-dc7b3aa9-d2be-41d5-b132-b1cebaf26975.png">

**Comment by jaylenchen** [comment]
my repo address: https://github.com/jaylenchan/switchenv, you can run `cargo tauri dev` to reproduce the issue

**Comment by simonhyll** [comment]
As far as I can tell the problem is that your frontend indeed isn't starting at port 1420, but at port 8080, because you're using `Trunk.toml` to configure it but it's not being read when using `trunk serve switch-env-ui/index.html`. Running `trunk serve` when inside the correct directory however does seem to work.

I got it to work by changing `beforeDevCommand` to the following: `"beforeDevCommand": "cargo run -p switch-env-cli && cd switch-env-ui && trunk serve",`

**Comment by simonhyll** [comment]
Here's your app running on my computer 🙂 

![image](https://user-images.githubusercontent.com/79983560/194737219-020dfe54-8f97-4251-8b0b-4deab57106c8.png)

**Comment by jaylenchen** [comment]
Thank you very much for your help. After your guidance, I successfully ran the application again！
