### ISSUE TITLE
[bug] how to start a exe with a space path by shell Command?

### ISSUE THREAD

**Issue by happymingjieli** [tauri-apps/tauri#5386]
### Describe the bug

 (on Windows) I am trying to use run to execute programs that have spaces in the pathname and take command line arguments. Something like the following example:

   const child = await new Command('cmd', [
      '/C',
      `start C:/Program Files/path/FaBuTing_Btest.exe -arg`,
    ]).spawn();

but it doesnt work because of the space in the path (Program Files), so what is the correct way to deal with it?

### Platform and versions

![image](https://user-images.githubusercontent.com/49396751/195076611-d17c448a-fbfa-49ec-ac79-b45090038afd.png)

**Comment by amrbashir** [comment]
this is not a bug in the API but just a mis-use, so with this type of questions, please open a Discussion or ask in our discord. 

I will convert this into a discussions.
