### ISSUE TITLE
Min height and min width not working as expected

### ISSUE THREAD

**Issue by kingsleyh** [tauri-apps/tauri#539]
Hi
This is not working as I expected:

in tauri.conf.json

```json
 "window": {
      "title": "SushiChain Wallet",
      "resizable": true,
      "min-width": 200,
      "min-height": 200
    },
```

min width and min height are not respected and I can resize the window to a tiny tiny size. Please would you be able to fix this in a future release.

**Comment by lucasfernog** [comment]
Hey @kingsleyh , can you tell us where did you see this config option? We only have "width" and "height" as setting, so if you saw this somewhere, it's probably an issue with our docs.

**Comment by kingsleyh** [comment]
sorry - I got confused with electron settings. Is it possible to add the minHeight and minWidth to the configuration?

**Comment by khionu** [comment]
While we're on Boscop's WebView, no, but we have plans to switch to zsurge's, which would give us a bit more control.

**Comment by thienpow** [comment]
it would be good to have 
min-width, max-width <-- this 2 is good for PWA, if user resized it too small, it would become ugly.
maximized <-- this would be maximized on first load.

another thing would be, try delay webview resize when the host window resize, like how all the browser did, this would make sure PWA reflective size won't response immediately... current resize is seriously lagging for PWA but it was smooth in browser.

**Comment by lucasfernog** [comment]
We can't implement it yet because we didn't move our webview implementation to the official one, we're still using Boscop/web-view and that doesn't give us much access to the window.

**Comment by lucasfernog** [comment]
Closing it to track it on #837

**Comment by DominiquePaul** [comment]
Hey,
has there been an update on this by any chance? Being able to set a min-width would be very cool! :)

**Comment by FabianLars** [comment]
Yes, min size settings were added years ago.
