### ISSUE TITLE
[bug] webview can not render

### ISSUE THREAD

**Issue by zcyc** [tauri-apps/tauri#5402]
### Describe the bug

Same code with different url gives different results in WebViewBuilder.
At first I thought it was a certificate issue, but it wasn't, the following is a test case.

#### Can render in dev mode and build app
- https://www.taobao.com/  
- http://tv.cctv.com/lm/jdft/jd/index.shtml

#### Can render in dev mode but can not render in build app
- http://news.cntv.cn/special/shzyhxjzg/ 

#### Can not render in dev mode and build app
- https://www.baidu.com/

### Reproduction

1. write test code
```
    let _webview = WebViewBuilder::new(window)?
        .with_url("test-url")?
        // .with_devtools(true)
        .with_initialization_script(script)
        .with_ipc_handler(handler)
        .build()?;
```
2. replace test-url with cases:

- https://www.taobao.com/
- http://tv.cctv.com/lm/jdft/jd/index.shtml
- http://news.cntv.cn/special/shzyhxjzg/
- https://www.baidu.com/

3. run dev and build to see results

### Expected behavior

I can see website in dev mode and build apps.

### Platform and versions

Environment
  › OS: Mac OS 12.6.0 X64
  › Node.js: 18.10.0
  › npm: 8.19.2
  › pnpm: 7.13.4
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-x86_64-apple-darwin

**Comment by amrbashir** [comment]
All urls worked fine for me on Windows. maybe macos is different or maybe some urls are blocked for you? Could you try a vpn or use a proxy?

**Comment by zcyc** [comment]
> All urls worked fine for me on Windows. maybe macos is different or maybe some urls are blocked for you? Could you try a vpn or use a proxy?

I will try it as you said.
