### ISSUE TITLE
popups are blocked in tauir. [feat] 

### ISSUE THREAD

**Issue by aliscie** [tauri-apps/tauri#5410]
### Describe the problem

basically I had google 0auth button when you click it should shows a popup when you can login then back to tauri app.

### Describe the solution you'd like

support popups pls

**Comment by amrbashir** [comment]
Google oauth doesn't work in webviews. https://developers.googleblog.com/2021/06/upcoming-security-changes-to-googles-oauth-2.0-authorization-endpoint.html

**Comment by amrbashir** [comment]
An alternative solution would be to open an auth link in the browser and redirect back to your app using deep-links (not yet implemented, see #323  )

**Comment by igorjacauna** [comment]
Hi folks, just came here to say that I created [this](https://github.com/igorjacauna/tauri-firebase-login) simple project that makes login on Firebase through Google OAuth 2.0. Using [OAuth Tauri Plugin](https://github.com/FabianLars/tauri-plugin-oauth) to help the process
