### ISSUE TITLE
[bug] exists does not return a boolean typed promise

### ISSUE THREAD

**Issue by BarFoo** [tauri-apps/tauri#5416]
### Describe the bug

See the code in reproduction

### Reproduction

```
import { exists } from '@tauri-apps/api/path

await exists(somePath)
```

### Expected behavior

For exists to return a boolean based promise

### Platform and versions

Windows using Tauri 1.1.1

**Comment by FabianLars** [comment]
See https://github.com/tauri-apps/tauri/pull/5252. Thanks for the report.
