### ISSUE TITLE
[bug] `yarn tauri dev` window crashes and restart with no any error message printed.

### ISSUE THREAD

**Issue by Tnze** [tauri-apps/tauri#5417]
### Describe the bug

1. When using `yarn tauri dev`, the window closes after executing a `tauri::command` and automatically reopen. **With no any panic message**.
2. When `yarn build` and then using `cargo run`, the program works just fine, no any error occurs. Which is wired.

I guess this is a bug of `@tauri/cli`.

### Reproduction

1. `git clone https://github.com/Tnze/ffxiv-best-craft.git`
2. `git checkout e804ed40496595fb3143f38bf641b2f62c15dc07`
3. `yarn install`
4. `yarn tauri dev`
5. Click the second button 
![image](https://user-images.githubusercontent.com/19628575/196083254-a459d5cb-58e6-4053-83e1-5386d9c3e010.png)

### Expected behavior

Expecte the cli doesn't close and reopen my window.

### Platform and versions

```ps
yarn-run-tauri 1.1.1
  › Node.js: 18.10.0
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: 3.2.1
  › rustup: 1.25.1
  › rustc: 1.66.0-nightly
  › cargo: 1.66.0-nightly
  › Rust toolchain: nightly-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › framework: Vue.js

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ .yarn
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

### Stack trace

```shell
DOESN'T EXIST
```

### Additional context

The `tauri::command` executed is this one:

https://github.com/Tnze/ffxiv-best-craft/blob/e804ed40496595fb3143f38bf641b2f62c15dc07/src-tauri/src/main.rs#L107-L111

The defining of app_state is `tauri::State<'_, AppState>` which has to write a `'_` lifetime for pass the compiling. That is different from other commands. Is that expected?

**Comment by FabianLars** [comment]
The file watcher watches the whole src-tauri dir so i guess the changes to the db file triggers it. You could try adding a `.taurignore` file next to `tauri.conf.json` where you ignore the assets folder 🤔

**Comment by Tnze** [comment]
I connect the db file in read-only mode: `sqlite:./assets/xiv.db?mode=ro`. Is sqlite still writing that file?

**Comment by Tnze** [comment]
Seems like `.taurignore` doesn't fix the problem, am I do someting wrong?

**Comment by Tnze** [comment]
Adding the `.taurignore` file fixes the problem.
```
assets/
```

But is it possible to only ignore the single `.db` file?

**Comment by FabianLars** [comment]
> I connect the db file in read-only mode: sqlite:./assets/xiv.db?mode=ro. Is sqlite still writing that file?

Not sure how sqlite databases work, maybe it still creates a lockfile or something?

> But is it possible to only ignore the single .db file?

If `assets/` works `/assets/dbname.db` or `/assets/*.db` should work too, _if_ the .db file is the problem

**Comment by Tnze** [comment]
Thank you, I think we absolutely need to let cli print some information when detecting file changes. It's so wired.

**Comment by Tnze** [comment]
By using #5428, I find out the changed file is
```
        Info File C:\....\ffxiv-crafting-assistant\src-tauri\assets\xiv.db-shm changed!
```

But for `.taurignore` file, `assets/`, `/assets/` works, but `assets/*`, `/assets/*`,  `/assets/xiv.db-shm` doesn't.
