### ISSUE TITLE
[bug] Macos missing splashscreen after build

### ISSUE THREAD

**Issue by Hellager** [tauri-apps/tauri#5423]
### Describe the bug

After building a tauri app on macos, if the app has the splashscreen feature, it will not show the splashscreen page when run it. The terminal will show such message below.
```shell
Asset `splashscreen.html` not found; fallback to splashscreen.html.html
```

### Reproduction

1. Follow official guidence [Splashscreen | Waiting for Webpage](https://tauri.app/v1/guides/features/splashscreen#waiting-for-webpage), add splashscreen to a tauri template app.
2. run **pnpm tauri build** and install the app
3. right click on the tauri-app, chooose **Show Package Content** -> **Contents** -> **Macos** -> double click to run tauri-app, then you will find that error message

### Expected behavior

It shouldn't missing the splascreen file

### Platform and versions

Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: 7.13.2
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-x86_64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Vue.js

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .vscode
  └─ src

**Comment by FabianLars** [comment]
If you're using frontend bundlers (which you do if you use vue) means that you can't just place the file into the distDir because the frontend build command will overwrite it. Instead most bundlers (whatever powers the vue-cli probably has one too) provide some kind of `public` folder mechanism - try moving the `splashscreen.html` file into a `public/` folder next to your package.json file and try it again

**Comment by Hellager** [comment]
> If you're using frontend bundlers (which you do if you use vue) means that you can't just place the file into the distDir because the frontend build command will overwrite it. Instead most bundlers (whatever powers the vue-cli probably has one too) provide some kind of `public` folder mechanism - try moving the `splashscreen.html` file into a `public/` folder next to your package.json file and try it again

That's it! Greet thanks for your help!
