### ISSUE TITLE
"Text size" in Win11 does not affect LogicalSize[bug] 

### ISSUE THREAD

**Issue by YYMMYB** [tauri-apps/tauri#5437]
### Describe the bug

![image](https://user-images.githubusercontent.com/26425590/196667269-44a128e4-296b-4a41-b960-13111a33b4cb.png)
![image](https://user-images.githubusercontent.com/26425590/196664018-a16bbfed-74f8-420b-9701-c845a77c298a.png)
When I use `LogicalSize` and `LogicalPosition`, the parameter in Windows 11 `Settings > Accessibility > Text size` have no effect.

### Test code and result
index.html:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body style="margin: 0;">
    <div id="Right" style="background-color: green;">Right</div>
    <div id="Wrong" style="background-color: red;">Wrong</div>
    <script src="script.js"></script>
  </body>
</html>
```

script.js (I set `build.withGlobalTauri` to `true` in tauri.conf.json)
```javascript
const appWindow = window.__TAURI__.window.appWindow;
const LogicalSize = window.__TAURI__.window.LogicalSize;

const w = 500;
const text_scale = 1.35; // parameter in windows setting

document.getElementById("Right").style.width = w + "px";
document.getElementById("Right").style.height = "50px";

document.getElementById("Wrong").style.width = w / text_scale + "px";
document.getElementById("Wrong").style.height = "50px";

(async () => {
  // !!!Note here!!! You need to multiply this parameter manually
  let size = new LogicalSize(w * text_scale, 100 * text_scale);
  await appWindow.setSize(size);
})();
```

result:
![image](https://user-images.githubusercontent.com/26425590/196669854-933823e0-af5d-4e70-85d2-6a4c9278d008.png)

If I use the following code at !!!Note here!!!, the result will not be correct:
script.js
```javascript
(async () => {
  // !!!Note here!!! I don't multiply the parameter
  let size = new LogicalSize(w, 100);
  await appWindow.setSize(size);
})();
```

result:
![image](https://user-images.githubusercontent.com/26425590/196674360-09c16c92-45c3-4776-909a-3a2834897a8c.png)

### Platform and versions

Environment
  › OS: Windows 10.0.22623 X64
  › Webview2: 106.0.1370.47
  › MSVC:
      - Visual Studio Community 2022
  › Node.js: 16.16.0
  › npm: 8.19.2
  › pnpm: 6.11.0
  › yarn: 1.22.15
  › rustup: 1.25.1
  › rustc: 1.66.0-nightly
  › cargo: 1.66.0-nightly
  › Rust toolchain: nightly-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../ui
  › devPath: ../ui

App directory structure
  ├─ node_modules
  ├─ src-tauri
  └─ ui

**Comment by amrbashir** [comment]
Text Size has no effect on Window scaling, it only affects font. When your overall Windows scale changes, the window and LogicalSize will change accordingly. I mean the `System > Display > Scale` option in Windows.
