### ISSUE TITLE
[WIP] Electron Feature Parity

### ISSUE THREAD

**Issue by BenoitRanque** [tauri-apps/tauri#544]
This issue will be used for tracking feature parity with electron.
The first step is establishing a list of electron features, and determining which of those we wish to eventually implement in tauri

The feature list will be sourced from the [electron website](https://www.electronjs.org/docs/api)

[Auto updates](https://www.electronjs.org/docs/api/auto-updater)
[Crash Reporting](https://www.electronjs.org/docs/api/crash-reporter)
[Debugging and Profiling](https://www.electronjs.org/docs/api/content-tracing)
[Windows Intaller](https://www.electronjs.org/docs/api/auto-updater#windows)
[Session, Local Storage, Cookies](https://www.electronjs.org/docs/api/session)
[Define keyboard shortcuts.](https://www.electronjs.org/docs/api/accelerator)
[Make HTTP/HTTPS requests.](https://www.electronjs.org/docs/api/client-request)
[Perform copy and paste operations on the system clipboard.](https://www.electronjs.org/docs/api/clipboard)
[Manipulate the command line arguments for your app that Chromium reads](https://www.electronjs.org/docs/api/command-line)
[Collect tracing data from Chromium to find performance bottlenecks and slow operations.](https://www.electronjs.org/docs/api/content-tracing)
[Create a safe, bi-directional, synchronous bridge across isolated contexts](https://www.electronjs.org/docs/api/context-bridge)
[Access information about media sources that can be used to capture audio and video from the desktop using the navigator.mediaDevices.getUserMedia API.](https://www.electronjs.org/docs/api/desktop-capturer)
[Display native system dialogs for opening and saving files, alerting, etc.](https://www.electronjs.org/docs/api/dialog)
[Control your app in the macOS dock](https://www.electronjs.org/docs/api/dock)
[Control file downloads from remote sources.](https://www.electronjs.org/docs/api/download-item)
[Control application configuration and behavior without changing code.](https://www.electronjs.org/docs/api/environment-variables)
[Use the HTML5 File API to work natively with files on the filesystem.](https://www.electronjs.org/docs/api/file-object)
[Open a window without toolbars, borders, or other graphical &quot;chrome&quot;.](https://www.electronjs.org/docs/api/frameless-window)
[Detect keyboard events when the application does not have keyboard focus.](https://www.electronjs.org/docs/api/global-shortcut)
[In-app purchases on Mac App Store.](https://www.electronjs.org/docs/api/in-app-purchase)
[Handle responses to HTTP/HTTPS requests.](https://www.electronjs.org/docs/api/incoming-message)
[Locale values returned by app.getLocale().](https://www.electronjs.org/docs/api/locales)
[Create native notifications, application menus and context menus.](https://www.electronjs.org/docs/api/menu)
[Add items to native application menus and context menus.](https://www.electronjs.org/docs/api/menu-item)
[Create tray, dock, and application icons using PNG or JPG files.](https://www.electronjs.org/docs/api/native-image)
[Read and respond to changes in Chromium&#x27;s native color theme.](https://www.electronjs.org/docs/api/native-theme)
[Issue HTTP/HTTPS requests using Chromium&#x27;s native networking library](https://www.electronjs.org/docs/api/net)
[Logging network events for a session.](https://www.electronjs.org/docs/api/net-log)
[Create OS desktop notifications](https://www.electronjs.org/docs/api/notification)
[Monitor power state changes.](https://www.electronjs.org/docs/api/power-monitor)
[Block the system from entering low-power (sleep) mode.](https://www.electronjs.org/docs/api/power-save-blocker)
[Extensions to process object.](https://www.electronjs.org/docs/api/process)
[Register a custom protocol and intercept existing protocol requests.](https://www.electronjs.org/docs/api/protocol)
[Register a custom protocol and intercept existing protocol requests.](https://www.electronjs.org/docs/api/protocol-ns)
[Create a browser window with a sandboxed renderer. With this option enabled, the renderer must communicate via IPC to the main process in order to access node APIs.](https://www.electronjs.org/docs/api/sandbox-option)
[Retrieve information about screen size, displays, cursor position, etc.](https://www.electronjs.org/docs/api/screen)
[Manage browser sessions, cookies, cache, proxy settings, etc.](https://www.electronjs.org/docs/api/session)
[Manage files and URLs using their default applications.](https://www.electronjs.org/docs/api/shell)
[Get system preferences.](https://www.electronjs.org/docs/api/system-preferences)
[Create TouchBar layouts for native macOS applications](https://www.electronjs.org/docs/api/touch-bar)
[Create a button in the touch bar for native macOS applications](https://www.electronjs.org/docs/api/touch-bar-button)
[Create a color picker in the touch bar for native macOS applications](https://www.electronjs.org/docs/api/touch-bar-color-picker)
[Create a group in the touch bar for native macOS applications](https://www.electronjs.org/docs/api/touch-bar-group)
[Create a label in the touch bar for native macOS applications](https://www.electronjs.org/docs/api/touch-bar-label)
[Create a popover in the touch bar for native macOS applications](https://www.electronjs.org/docs/api/touch-bar-popover)
[Create a scrubber (a scrollable selector)](https://www.electronjs.org/docs/api/touch-bar-scrubber)
[Create a segmented control (a button group) where one button has a selected state](https://www.electronjs.org/docs/api/touch-bar-segmented-control)
[Create a slider in the touch bar for native macOS applications](https://www.electronjs.org/docs/api/touch-bar-slider)
[Create a spacer between two items in the touch bar for native macOS applications](https://www.electronjs.org/docs/api/touch-bar-spacer)
[Add icons and context menus to the system&#x27;s notification area.](https://www.electronjs.org/docs/api/tray)
[Render and control web pages.](https://www.electronjs.org/docs/api/web-contents)
[Customize the rendering of the current web page.](https://www.electronjs.org/docs/api/web-frame)
[Intercept and modify the contents of a request at various stages of its lifetime.](https://www.electronjs.org/docs/api/web-request)
[Display external web content in an isolated frame and process.](https://www.electronjs.org/docs/api/webview-tag)
[Open a new window and load a URL.](https://www.electronjs.org/docs/api/window-open)
[Print to Printer and related options](https://www.electronjs.org/docs/api/web-contents#contentsgetprinters)

**Comment by nklayman** [comment]
I think we should split these up into a few groups to make it more clear which features we are implementing, which ones we have no plans to implement, and which ones are somewhere in between. A suggestion for the groups to use are: `must have for beta/v1`, `high priority post-v1`, `low priority post-v1`, `no plan to implement`, and `will not implement`.

**Comment by BenoitRanque** [comment]
I like your idea for the ranking, but I don't feel confident making the call on what is needed and what is not. Here is my own ranking, obviously this is subjective and will change.

#### Primary
- [x] [Auto updates](https://www.electronjs.org/docs/api/auto-updater)
- [ ] [Crash Reporting](https://www.electronjs.org/docs/api/crash-reporter)
- [ ] [Debugging and Profiling](https://www.electronjs.org/docs/api/content-tracing)
- [x] [Windows Intaller](https://www.electronjs.org/docs/api/auto-updater#windows)
- [ ] [Session, Local Storage, Cookies](https://www.electronjs.org/docs/api/session)
- [x] [Make HTTP/HTTPS requests.](https://www.electronjs.org/docs/api/client-request)
- [ ] [Handle responses to HTTP/HTTPS requests.](https://www.electronjs.org/docs/api/incoming-message)
- [ ] [Create a safe, bi-directional, synchronous bridge across isolated contexts](https://www.electronjs.org/docs/api/context-bridge)
- [ ] [Manage browser sessions, cookies, cache, proxy settings, etc.](https://www.electronjs.org/docs/api/session)
- [x] [Create native application menus and context menus.](https://www.electronjs.org/docs/api/menu)

#### Secondary
- [x] [Define keyboard shortcuts.](https://www.electronjs.org/docs/api/accelerator)
- [ ] [Perform copy and paste operations on the system clipboard.](https://www.electronjs.org/docs/api/clipboard)
- [ ] [Collect tracing data from Chromium to find performance bottlenecks and slow operations.](https://www.electronjs.org/docs/api/content-tracing)
- [ ] [Access information about media sources that can be used to capture audio and video from the desktop using the navigator.mediaDevices.getUserMedia API.](https://www.electronjs.org/docs/api/desktop-capturer)
- [x] [Display native system dialogs for opening and saving files, alerting, etc.](https://www.electronjs.org/docs/api/dialog)
- [ ] [Control file downloads from remote sources.](https://www.electronjs.org/docs/api/download-item)
- [ ] [Use the HTML5 File API to work natively with files on the filesystem.](https://www.electronjs.org/docs/api/file-object)
- [ ] [Add icons and context menus to the system&#x27;s notification area.](https://www.electronjs.org/docs/api/tray)
- [x] [Create OS desktop notifications](https://www.electronjs.org/docs/api/notification)
- [ ] [Get system preferences.](https://www.electronjs.org/docs/api/system-preferences)
- [x] [Manage files and URLs using their default applications.](https://www.electronjs.org/docs/api/shell)
- [ ] [Render and control web pages.](https://www.electronjs.org/docs/api/web-contents)
- [x] [Print to Printer and related options](https://www.electronjs.org/docs/api/web-contents#contentsgetprinters)

#### Tertiary
- [x] [Open a window without toolbars, borders, or other graphical &quot;chrome&quot;.](https://www.electronjs.org/docs/api/frameless-window)
- [x] [Create tray, dock, and application icons using PNG or JPG files.](https://www.electronjs.org/docs/api/native-image)
- [ ] [Control application configuration and behavior without changing code.](https://www.electronjs.org/docs/api/environment-variables)
- [ ] [Detect keyboard events when the application does not have keyboard focus.](https://www.electronjs.org/docs/api/global-shortcut)
- [ ] [Locale values returned by app.getLocale().](https://www.electronjs.org/docs/api/locales)
- [ ] [Logging network events for a session.](https://www.electronjs.org/docs/api/net-log)
- [ ] [Monitor power state changes.](https://www.electronjs.org/docs/api/power-monitor)
- [ ] [Block the system from entering low-power (sleep) mode.](https://www.electronjs.org/docs/api/power-save-blocker)
- [ ] [Register a custom protocol and intercept existing protocol requests.](https://www.electronjs.org/docs/api/protocol)
- [ ] [Retrieve information about screen size, displays, cursor position, etc.](https://www.electronjs.org/docs/api/screen)
- [ ] [Customize the rendering of the current web page.](https://www.electronjs.org/docs/api/web-frame)
- [ ] [Display external web content in an isolated frame and process.](https://www.electronjs.org/docs/api/webview-tag)
- [x] [Open a new window and load a URL.](https://www.electronjs.org/docs/api/window-open)

#### MacOS Specific
- [ ] [In-app purchases on Mac App Store.](https://www.electronjs.org/docs/api/in-app-purchase)
- [ ] [Control your app in the macOS dock](https://www.electronjs.org/docs/api/dock)
- [ ] [Create TouchBar layouts for native macOS applications](https://www.electronjs.org/docs/api/touch-bar)
- [ ] [Create a button in the touch bar for native macOS applications](https://www.electronjs.org/docs/api/touch-bar-button)
- [ ] [Create a color picker in the touch bar for native macOS applications](https://www.electronjs.org/docs/api/touch-bar-color-picker)
- [ ] [Create a group in the touch bar for native macOS applications](https://www.electronjs.org/docs/api/touch-bar-group)
- [ ] [Create a label in the touch bar for native macOS applications](https://www.electronjs.org/docs/api/touch-bar-label)
- [ ] [Create a popover in the touch bar for native macOS applications](https://www.electronjs.org/docs/api/touch-bar-popover)
- [ ] [Create a scrubber (a scrollable selector)](https://www.electronjs.org/docs/api/touch-bar-scrubber)
- [ ] [Create a segmented control (a button group) where one button has a selected state](https://www.electronjs.org/docs/api/touch-bar-segmented-control)
- [ ] [Create a slider in the touch bar for native macOS applications](https://www.electronjs.org/docs/api/touch-bar-slider)
- [ ] [Create a spacer between two items in the touch bar for native macOS applications](https://www.electronjs.org/docs/api/touch-bar-spacer)
- [ ] [Intercept and modify the contents of a request at various stages of its lifetime.](https://www.electronjs.org/docs/api/web-request)

EDIT (by @nklayman): Added checkboxes

**Comment by khionu** [comment]
I like this sorting. There's a few things I think should be switched around, but this is a great start. Thank you very much!

**Comment by nothingismagick** [comment]
@nklayman - are you tracking this? would be good to group them into things we can get in before beta / etc. in line with your comment above

**Comment by nklayman** [comment]
I'm not sure that I'm the right person to do the grouping as I have so little knowledge of the core rust part. This might be a good thing to put on the tech talk schedule.

**Comment by lucasfernog** [comment]
Global shortcut coming up #644

**Comment by ljfreelancer88** [comment]
I really need this feature too [https://www.electronjs.org/docs/api/screen](url) in Tauri. I'm trying to create an app like minimal "MS Power Point" for our Churches. The output will sending out to HDMI.

**Comment by ohmree** [comment]
> I like your idea for the ranking, but I don't feel confident making the call on what is needed and what is not. Here is my own ranking, obviously this is subjective and will change.
> #### Primary
> 
>     * [x]  [Auto updates](https://www.electronjs.org/docs/api/auto-updater)
> 
>     * [ ]  [Crash Reporting](https://www.electronjs.org/docs/api/crash-reporter)
> 
>     * [ ]  [Debugging and Profiling](https://www.electronjs.org/docs/api/content-tracing)
> 
>     * [x]  [Windows Intaller](https://www.electronjs.org/docs/api/auto-updater#windows)
> 
>     * [ ]  [Session, Local Storage, Cookies](https://www.electronjs.org/docs/api/session)
> 
>     * [x]  [Make HTTP/HTTPS requests.](https://www.electronjs.org/docs/api/client-request)
> 
>     * [ ]  [Handle responses to HTTP/HTTPS requests.](https://www.electronjs.org/docs/api/incoming-message)
> 
>     * [ ]  [Create a safe, bi-directional, synchronous bridge across isolated contexts](https://www.electronjs.org/docs/api/context-bridge)
> 
>     * [ ]  [Manage browser sessions, cookies, cache, proxy settings, etc.](https://www.electronjs.org/docs/api/session)
> 
>     * [x]  [Create native application menus and context menus.](https://www.electronjs.org/docs/api/menu)
> 
> 
> #### Secondary
> 
>     * [x]  [Define keyboard shortcuts.](https://www.electronjs.org/docs/api/accelerator)
> 
>     * [ ]  [Perform copy and paste operations on the system clipboard.](https://www.electronjs.org/docs/api/clipboard)
> 
>     * [ ]  [Collect tracing data from Chromium to find performance bottlenecks and slow operations.](https://www.electronjs.org/docs/api/content-tracing)
> 
>     * [ ]  [Access information about media sources that can be used to capture audio and video from the desktop using the navigator.mediaDevices.getUserMedia API.](https://www.electronjs.org/docs/api/desktop-capturer)
> 
>     * [x]  [Display native system dialogs for opening and saving files, alerting, etc.](https://www.electronjs.org/docs/api/dialog)
> 
>     * [ ]  [Control file downloads from remote sources.](https://www.electronjs.org/docs/api/download-item)
> 
>     * [ ]  [Use the HTML5 File API to work natively with files on the filesystem.](https://www.electronjs.org/docs/api/file-object)
> 
>     * [ ]  [Add icons and context menus to the system's notification area.](https://www.electronjs.org/docs/api/tray)
> 
>     * [x]  [Create OS desktop notifications](https://www.electronjs.org/docs/api/notification)
> 
>     * [ ]  [Get system preferences.](https://www.electronjs.org/docs/api/system-preferences)
> 
>     * [x]  [Manage files and URLs using their default applications.](https://www.electronjs.org/docs/api/shell)
> 
>     * [ ]  [Render and control web pages.](https://www.electronjs.org/docs/api/web-contents)
> 
>     * [x]  [Print to Printer and related options](https://www.electronjs.org/docs/api/web-contents#contentsgetprinters)
> 
> 
> #### Tertiary
> 
>     * [x]  [Open a window without toolbars, borders, or other graphical "chrome".](https://www.electronjs.org/docs/api/frameless-window)
> 
>     * [x]  [Create tray, dock, and application icons using PNG or JPG files.](https://www.electronjs.org/docs/api/native-image)
> 
>     * [ ]  [Control application configuration and behavior without changing code.](https://www.electronjs.org/docs/api/environment-variables)
> 
>     * [ ]  [Detect keyboard events when the application does not have keyboard focus.](https://www.electronjs.org/docs/api/global-shortcut)
> 
>     * [ ]  [Locale values returned by app.getLocale().](https://www.electronjs.org/docs/api/locales)
> 
>     * [ ]  [Logging network events for a session.](https://www.electronjs.org/docs/api/net-log)
> 
>     * [ ]  [Monitor power state changes.](https://www.electronjs.org/docs/api/power-monitor)
> 
>     * [ ]  [Block the system from entering low-power (sleep) mode.](https://www.electronjs.org/docs/api/power-save-blocker)
> 
>     * [ ]  [Register a custom protocol and intercept existing protocol requests.](https://www.electronjs.org/docs/api/protocol)
> 
>     * [ ]  [Retrieve information about screen size, displays, cursor position, etc.](https://www.electronjs.org/docs/api/screen)
> 
>     * [ ]  [Customize the rendering of the current web page.](https://www.electronjs.org/docs/api/web-frame)
> 
>     * [ ]  [Display external web content in an isolated frame and process.](https://www.electronjs.org/docs/api/webview-tag)
> 
>     * [x]  [Open a new window and load a URL.](https://www.electronjs.org/docs/api/window-open)
> 
> 
> #### MacOS Specific
> 
>     * [ ]  [In-app purchases on Mac App Store.](https://www.electronjs.org/docs/api/in-app-purchase)
> 
>     * [ ]  [Control your app in the macOS dock](https://www.electronjs.org/docs/api/dock)
> 
>     * [ ]  [Create TouchBar layouts for native macOS applications](https://www.electronjs.org/docs/api/touch-bar)
> 
>     * [ ]  [Create a button in the touch bar for native macOS applications](https://www.electronjs.org/docs/api/touch-bar-button)
> 
>     * [ ]  [Create a color picker in the touch bar for native macOS applications](https://www.electronjs.org/docs/api/touch-bar-color-picker)
> 
>     * [ ]  [Create a group in the touch bar for native macOS applications](https://www.electronjs.org/docs/api/touch-bar-group)
> 
>     * [ ]  [Create a label in the touch bar for native macOS applications](https://www.electronjs.org/docs/api/touch-bar-label)
> 
>     * [ ]  [Create a popover in the touch bar for native macOS applications](https://www.electronjs.org/docs/api/touch-bar-popover)
> 
>     * [ ]  [Create a scrubber (a scrollable selector)](https://www.electronjs.org/docs/api/touch-bar-scrubber)
> 
>     * [ ]  [Create a segmented control (a button group) where one button has a selected state](https://www.electronjs.org/docs/api/touch-bar-segmented-control)
> 
>     * [ ]  [Create a slider in the touch bar for native macOS applications](https://www.electronjs.org/docs/api/touch-bar-slider)
> 
>     * [ ]  [Create a spacer between two items in the touch bar for native macOS applications](https://www.electronjs.org/docs/api/touch-bar-spacer)
> 
>     * [ ]  [Intercept and modify the contents of a request at various stages of its lifetime.](https://www.electronjs.org/docs/api/web-request)

Why is "intercept and modify the contents of a request at various stages of its lifetime" macOS-specific?
I'd like to implement an approach similar to the one taken in [twurple's auth-electron](https://github.com/twurple/twurple/tree/main/packages/auth-electron), where the request to the oauth redirect uri is intercepted and the url query params are accessed and processed, and it seems like the only way to do it would be with an api similar to [`WebRequest`](https://www.electronjs.org/docs/api/web-request).

**Comment by dannymcgee** [comment]
> Open a window without toolbars, borders, or other graphical "chrome".

I think this Electron feature has not been fully understood wrt the Tauri implementation, unless you've deliberately chosen to implement it differently/with less granularity. In Electron, if you create a window with `frame: false, transparent: false`, you get a window that still has all of the native window chrome, with _only_ the titlebar removed. Setting `frame: false, transparent: true` removes the rest of the chrome (border, shadow, etc.). The first option is generally what you would want to do if you just need to implement a custom titlebar, but it doesn't seem to be possible in Tauri currently, as `decorations: false` removes _all_ of the native window chrome.

MS Teams in Windows 11 uses a custom titlebar with the rest of the native window chrome preserved, so I assume WebView2 exposes this as an option somehow, but I could be wrong:

![ms-teams-webview2](https://user-images.githubusercontent.com/13191586/145064216-1312df53-1306-4af7-89fd-f487aeca9818.png)

(Let me know if this is the wrong place to bring this up — I searched "border" and this seemed to be the most relevant existing issue)

**Comment by amrbashir** [comment]
@dannymcgee for shadows, take a look at https://github.com/tauri-apps/tao/issues/157#issuecomment-892088091

**Comment by FabianLars** [comment]
@dannymcgee about ms teams, afaik they still use the same approach for the titlebar as in their electron based client (html based).
This of course doesn't really matter in the context of the request, but anyway

**Comment by amrbashir** [comment]
I think this issue is not needed anymore. We are still missing some features but those are better be tracked in their own issues.
