### ISSUE TITLE
[bug] extremely slow :hover effects

### ISSUE THREAD

**Issue by danielpoliakov** [tauri-apps/tauri#5446]
### Describe the bug

Experiencing same bug as in: #3691 and #3694 (but both of those issues are already closed). App works fine in browser but in both dev and prod build I experience 1 second+ wait time before hover effect.

### Reproduction

```
button:hover {
  background-color: red;
}
```

### Expected behavior

Button changes color immediately as in browser.

### Platform and versions

```
Environment
  › OS: Debian 11 X64
  › Node.js: 16.18.0
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Svelte

App directory structure
  ├─ public
  ├─ src
  ├─ node_modules
  ├─ .vscode
  ├─ src-tauri
  └─ dist
```

**Comment by FabianLars** [comment]
3691 and 3694 were about a windows specific bug which was resolved.

Can you try the same code in epiphany (also known as Gnome web) which is a browser using webkitgtk - just to check if it's a general webkitgtk thing or Tauri specific.

p.s. it seems to work absolutely find on my fedora 36 system and ubuntu 22.04 vm 🤔

**Comment by danielpoliakov** [comment]
In epiphany:
```
Package: epiphany-browser
Version: 3.38.2-1+deb11u3
```
it works as expected.

**Comment by danielpoliakov** [comment]
I'm running i3wm and I looked at other issues - it seems my issue is related to #4077.

I found out everything works as expected when tauri runs in tiling mode.
Once I set the window to floating mode - my interactions (e.g. :hover) is delayed up to 8 seconds.

Epiphany works as expected even in floating mode.
