### ISSUE TITLE
[bug] Types for FS/exists function wrong in shipped d.ts files

### ISSUE THREAD

**Issue by jhechtf** [tauri-apps/tauri#5447]
### Describe the bug

Pulling in `exists` from `@tauri-apps/api/fs` shows this call signature

```ts
declare function exists(path: string, options?: FsOptions): Promise<void>;
```

While [the code](https://github.com/tauri-apps/tauri/blob/dev/tooling/api/src/fs.ts#L572) shows that the value should be 

```ts
declare function exists(path: string, options: FsOptions = {}): Promise<boolean>;
```

![image](https://user-images.githubusercontent.com/8152471/196828183-e35d1416-7165-4259-926d-82c116b6b65a.png)

### Reproduction

1. In a Tauri app import `exists` from `@tauri-app/api/fs`
2. Use the function on a file, e.g. `const settingsExisted = await exists('settings.json', { dir: BaseDirectory.Config })`
3. Check the return value for `settingsExisted` is typed as `void` because the declaration is dictates an empty value.

### Expected behavior

The `exists` function should return a `Promise<boolean>` in its type definitions.

### Platform and versions

```
> tauri "info"


Environment
  › OS: Windows 10.0.19043 X64
  › Webview2: 106.0.1370.47
  › MSVC: 
      - Visual Studio Build Tools 2019
  › Node.js: 16.9.0
  › npm: 8.1.2
  › pnpm: 7.3.0
  › yarn: 1.22.5
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Svelte

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
  ```

### Stack trace

```shell
N/A
```

### Additional context

N/A

**Comment by amrbashir** [comment]
this has been fixed already and will be available in the next release.

**Comment by jhechtf** [comment]
When will that be exactly?

**Comment by amrbashir** [comment]
I can't give an ETA unfortunately but maybe at the end of the month.

**Comment by zhan3333** [comment]
same problem
