### ISSUE TITLE
后端接口不响应 造成前端界面卡死 请问这种要怎么解决？

### ISSUE THREAD

**Issue by YDHCUI** [tauri-apps/tauri#5448]
### Describe the bug

后端接口不响应 造成前端界面卡死 请问这种要怎么解决？

### Platform and versions

我前端调的也是异步的 但是好像并没有生效
`    async ClickSend(){
      const res = await invoke('repeater_send', {
      })
      this.res_body = res
    }`

**Comment by FabianLars** [comment]
Is your `repeater_send` tauri command async? If not, try converting it to an `async fn` or a fn marked with `#[tauri::command(async)]` so that they don't block the main thread.

Keep in mind that large payloads (in this case `res_body`) will block the UI too.
