### ISSUE TITLE
[feat] Is it possible to generate only projects for Xcode and Visual Studio?

### ISSUE THREAD

**Issue by SF-Simon** [tauri-apps/tauri#5455]
### Describe the problem

When we are developing macOS, we need to modify some content in AppDelegate.swift, such as configuring subscription information and event notifications, etc.
I noticed that most of the current configuration items are for the configuration of the Info.plist file.
There are no relevant guidelines and methods for the introduction and use of more flexible third-party plug-ins.

### Describe the solution you'd like

Hope to be able to generate an independent project, so that we can edit the code inside and increase the interaction.

**Comment by amrbashir** [comment]
We don't use swift, we are using appkit and cocoa APIs through objc
