### ISSUE TITLE
How to run tauri app as Windows shell aka explorer.exe ? [docs] [platform: Windows]

### ISSUE THREAD

**Issue by luvor** [tauri-apps/tauri#5459]
Hi!
I'm developing my own shell that replaces explorer.exe for my university project.
At the moment having problems with launching WebView2 after **userinit**.

My question is: how I can make tauri launch WebView2 when it launches an myapp.exe(my app build from tauri), which I put at
```
HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Winlogon" /v Userinit /d "C:\Windows\system32\userinit.exe, C:\Program Files (x86)\Microsoft\EdgeWebView\Application\106.0.1370.47\msedgewebview2.exe"
```
And as shell I put
```
"HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon" /v Shell /d "C:\Program Files\myapp\myapp.exe"
```
So, due to manual execution of WebView2 at **tauri.conf.json** I have this option
```
"webviewInstallMode": {"type": "skip"},
```

It worked for a while, but now it is crashing after userinit.
Thank you, for you time!

**Comment by amrbashir** [comment]
This feels like it should be an issue or a discussion at https://github.com/MicrosoftEdge/WebView2Feedback repo as it is not specific to tauri.
