### ISSUE TITLE
[feat] Support sending byte data to the "data" event for child command's stdout and stderr

### ISSUE THREAD

**Issue by GCRev** [tauri-apps/tauri#5465]
### Describe the problem

See related issue: https://github.com/tauri-apps/tauri/issues/5309

Currently we receive type `string` for the the "data" event listener of `child.stdout.on("data" ....)` and `child.stderr.on("data" ....)`. This is suitable for the vast majority of simple communication, but challenging to work-around for the cases in which binary data must be fed directly through for applications that use more complex communication formats.

In my specific case, I'm trying to read `msgpack` messages via the command output of a child process, and currently that is impossible without writing a workaround solution for several reasons:

1. The default operation if no encoding specified is to attempt a conversion to utf_8 using rust's built-in decoder, executed [here](https://github.com/tauri-apps/tauri/blob/dev/core/tauri/src/api/process/command.rs#L411)
2. If there is an encoding, then it uses `encoding_rs` which **correctly** replaces invalid utf-8 with replacement characters.

In scenario 1, we observe the symptoms of https://github.com/tauri-apps/tauri/issues/5309, which is correct behavior. In scenario 2, encoding_rs eliminates unrecognized or invalid utf8 sequences entirely, which is also correct behavior.

### Describe the solution you'd like

I would like a flag in `SpawnOptions` that allows for the output of the process to be sent directly to the front end, either as an array of numbers resembling a `Uint8Array` or an escaped string with control characters like `\x...` or `\u...`.

### Alternatives considered

I'm going to have to work around this for now by implementing a shim executable that can perform this translation beforehand, and then use that as my sidecar. I cannot change the message format of my current sidecar, so a work-around is required to get communication working properly.

### Additional context

If you're interested, the sidecar application is neovim, and I'm trying to communicate with it using RPC directly. I have previously implemented this in Node and Electron. This is currently blocking development while I hack a solution into existence.

**Comment by cymruu** [comment]
I tried to implement it. I got working prototype, however it doubt it can be merged as it is right now 😅. [Here is](https://github.com/cymruu/tauri/tree/cymruu/command-byte-data) my tarui branch with implementation and [here is example app](https://github.com/cymruu/tauri-raw-command-data) to show how it works. 
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/2981598/203359250-b368754e-9573-4e71-900b-963c531b6460.png">

**Comment by GCRev** [comment]
@cymruu great work! I've worked around this myself by just replacing the code directly inside the existing read function, rather than attempting to switch between logic -- mostly because I'm still learning rust and because I don't ever need to be concerned with encodings in my current project. My workaround isn't a good one, so I'm glad you've gotten a prototype working with a proper switch between raw and encoded bytes, and proper updates to the typescript interface.

Hopefully this gets some official traction because, in my opinion, it's quite important to be able to read binary directly from the stdout of a process.

**Comment by amrbashir** [comment]
@cymruu really good work, looking forward to the PR unfortunately since it is a breaking change, it will be scheduled for tauri@v2
