### ISSUE TITLE
How to monitor program startup and shutdown

### ISSUE THREAD

**Issue by TheBlindM** [tauri-apps/tauri#5467]
### Describe the bug

I don't know rust, is there a ready-made code? grateful
```
  tauri::Builder::default()
		.on_window_event( match event{
			tauri::RunEvent::Ready => {
        println!("程序启动")
			}
			tauri::RunEvent::Exit=>{
				//child.kill().expect("!kill");
				println!("程序退出")
			}
		})
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
```

err

error[E0277]: expected a `Fn<(GlobalWindowEvent,)>` closure, found `()`
    --> src\main.rs:27:21
     |
27   |           .on_window_event( match event{
     |  __________---------------__^
     | |          |
     | |          required by a bound introduced by this call
28   | |             tauri::RunEvent::Ready => {
29   | |         println!("程序启动")
30   | |             }
     |
1240 |   pub fn on_window_event<F: Fn(GlobalWindowEvent<R>) + Send + Sync + 'static>(
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `tauri::Builder::<R>::on_window_event`

### Platform and versions

1.0.1

**Comment by FabianLars** [comment]
The RunEvent match belongs to the [`run` function](https://docs.rs/tauri/latest/tauri/struct.App.html#method.run) not the on_window_even hook:
```rs
  tauri::Builder::default()
    .build(tauri::generate_context!())
    .expect("error building tauri app")
    .run(|handle, event| match event{
      tauri::RunEvent::Ready => {
        println!("程序启动")
      }
      tauri::RunEvent::Exit=>{
        println!("程序退出")
      }
      _ => ()
    })
    .expect("error while running tauri application");
```

**Comment by TheBlindM** [comment]
> ```rust
> , event| match event{
>       tauri::RunEvent::Ready => {
>         println!("程序启动")
>       }
>       tauri::RunEvent::Exit=>{
>         println!("程序退出")
>       }
>     }
> ```



error[E0593]: function is expected to take 2 arguments, but it takes 0 arguments
   --> src\main.rs:29:10
    |
29  |     .run(handle, event| match event{
    |      --- ^^^^^^ expected function that takes 2 arguments
    |      |
    |      required by a bound introduced by this call
    |
note: required by a bound in `tauri::App::<R>::run`
   --> C:\Users\10431\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-1.0.5\src\app.rs:729:17
    |
729 |   pub fn run<F: FnMut(&AppHandle<R>, RunEvent) + 'static>(mut self, mut callback: F) {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `tauri::App::<R>::run`

error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> src\main.rs:29:6
    |
29  |       .run(handle, event| match event{
    |  ______^^^_________-
30  | |             tauri::RunEvent::Ready => {
31  | |                 println!("程序启动")
32  | |             }
...   |
35  | |             }
36  | |         })
    | |_________- argument unexpected
    |
note: associated function defined here
   --> C:\Users\10431\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-1.0.5\src\app.rs:729:10
    |
729 |   pub fn run<F: FnMut(&AppHandle<R>, RunEvent) + 'static>(mut self, mut callback: F) {
    |          ^^^
help: remove the extra argument
    |

**Comment by FabianLars** [comment]
You didn't post the full code but according to the issue you're missing the `|` in front of `handle`: `.run(|handle, event| match event{`

**Comment by TheBlindM** [comment]
> ```rust
> _ => ()
> ```

OK, thank you
