### ISSUE TITLE
Startup program crashes after packaging

### ISSUE THREAD

**Issue by TheBlindM** [tauri-apps/tauri#5470]
### Describe the bug

```
#![cfg_attr(
all(not(debug_assertions), target_os = "windows"),
windows_subsystem = "windows"
)]

use std::io::stdout;
use std::process::Command;

use std::{process, thread};
use std::os::windows::process::CommandExt;
use tauri::async_runtime::handle;
use tauri::{Manager, RunEvent};

fn main() {
	let mut child = Command::new("./src/server.exe").creation_flags(0x08000000)
		.spawn().expect("cmd exec error!");
	tauri::Builder::default()
		.plugin(tauri_plugin_single_instance::init(|app, _argv, _cwd| { //设置插件
			let window = app.get_window("main").unwrap(); //二次打开软件时，显示已打开窗口，单例运行app
			window.set_focus().unwrap();
			window.show().unwrap();
		}))
		.build(tauri::generate_context!())
		.expect("err building")
		.run(move |handle, event| match event {
			tauri::RunEvent::Ready => {
				println!("程序启动")
			}
			tauri::RunEvent::Exit => {
				child.kill().expect("!kill");
				println!("程序退出")
			}
			_ => ()
		});
}
```

When this code is commented out, it works fine
```
let mut child = Command::new("./src/server.exe").creation_flags(0x08000000)
		.spawn().expect("cmd exec error!");

```

### Platform and versions

1.0.1

**Comment by FabianLars** [comment]
For future issues please add a proper description of the issue, and any errors you see. Also include the _full_ output of `tauri info` as required in the issue templte.

The issue you're seeing here is most likely that the exe is missing afterwards. `Command::new("./src/server.exe")` this will always look for the file in a `src/` folder relative to the main app which doesn't exist after bundling.

Take a look at this guide <https://tauri.app/v1/guides/building/sidecar/> which automatically bundles the exe in your app bundle, it also sets the same creation flag.

**Comment by TheBlindM** [comment]
> For future issues please add a proper description of the issue, and any errors you see. Also include the _full_ output of `tauri info` as required in the issue templte.
> 
> The issue you're seeing here is most likely that the exe is missing afterwards. `Command::new("./src/server.exe")` this will always look for the file in a `src/` folder relative to the main app which doesn't exist after bundling.
> 
> Take a look at this guide https://tauri.app/v1/guides/building/sidecar/ which automatically bundles the exe in your app bundle, it also sets the same creation flag.

I followed the documentation but it fails to compile

```
use std::io::stdout;
use std::process::Command;

use std::{thread};
use std::os::windows::process::CommandExt;
use tauri::async_runtime::handle;
use tauri::{Manager, RunEvent};
use tauri::api::process::Command as tauriCommand;

fn main() {
	/*let mut child = Command::new("server/server-x86_64-pc-windows-msvc.exe").creation_flags(0x08000000)
		.spawn().expect("cmd exec error!");*/

	let (mut rx, mut child) = tauriCommand::new_sidecar("server/server")
		.expect("failed to create `my-sidecar` binary command")
		.spawn()
		.expect("Failed to spawn sidecar");


	tauri::Builder::default()
		.plugin(tauri_plugin_single_instance::init(|app, _argv, _cwd| { //设置插件
			let window = app.get_window("main").unwrap(); //二次打开软件时，显示已打开窗口，单例运行app
			window.set_focus().unwrap();
			window.show().unwrap();
		}))
		.build(tauri::generate_context!())
		.expect("err building")
		.run(move |handle, event| match event {
			tauri::RunEvent::Ready => {
				println!("程序启动")
			}
			tauri::RunEvent::Exit => {
				child.kill().expect("!kill");
				println!("程序退出")
			}
			_ => ()
		});
}
```

![image](https://user-images.githubusercontent.com/48701152/197431416-a619d5b5-0bca-4e26-9cc8-8d7f178ea22f.png)

**Comment by FabianLars** [comment]
Again, if you report errors please include the error messages in your comment, otherwise it makes it harder for us to help you because we (or i) don't always have access to a compiler.

Btw, you can remove the `child.kill().expect()` line since Tauri does this on Exit.
