### ISSUE TITLE
Documentation link to a config option on Hover

### ISSUE THREAD

**Issue by Viijay-Kr** [tauri-apps/tauri#5479]
Love the extension so far. Although I find one thing annoying. 
I m not a huge fan of scanning the entire project documentation before hacking it out myslef. 
I start coding from the get-go and gather knowledge about the underlying stack using VS code intellisense.

In the Tauri config file I get nice information about a certain config option but, what I'd love along with it is the ability to go to the documentation section from VS code using hyperlinks
<img width="433" alt="Screenshot 2022-10-24 at 21 09 49" src="https://user-images.githubusercontent.com/8697234/197606482-6f9f1b98-d27f-4c4f-b83b-ada341715644.png">

I love tsconfig for this reason
<img width="433" alt="Screenshot 2022-10-24 at 21 08 43" src="https://user-images.githubusercontent.com/8697234/197606539-0e754313-9519-445a-bd9d-c95b7d085f49.png">

I would be more than happy to help out with a PR here unless I'm missing something

**Comment by amrbashir** [comment]
This is a good idea but the extension merely provides a JSON schema to VSCode, so this need to be implemented in the schema itself which is auto-generated from this file https://github.com/tauri-apps/tauri/blob/dev/core/tauri-utils/src/config.rs
