### ISSUE TITLE
[feat] will-navigate and did-get-redirect-request

### ISSUE THREAD

**Issue by 204065248** [tauri-apps/tauri#5485]
### Describe the problem

Sorry, my English is not very good. Does tauri have `will-navigate` and `did-get-redirect-request` events similar to electron? I want to use github for third-party login, electron's sample code https://www.manos.im/blog/ electron-oauth-with-github/

### Describe the solution you'd like

https://www.manos.im/blog/ electron-oauth-with-github/

**Comment by FabianLars** [comment]
https://docs.rs/tauri/2.0.0/tauri/plugin/struct.Builder.html#method.on_navigation
