### ISSUE TITLE
[feat] refactor tray.get_item(id) to return Option<T>

### ISSUE THREAD

**Issue by mrjackwills** [tauri-apps/tauri#5491]
### Describe the problem

Currently, when trying to use an unknown system tray menu item, the get_item function panics

`window.app_handle().tray_handle().get_item("unknown_id")` => `panic!("item id not found")`

### Describe the solution you'd like

Ideally the get_item should return an `Option<SystemTrayMenuItemHandle<R>>`

Should also apply to the `menu.get_item(id)` function as well?

That way the user can execute, without fear of a panic
```rust
if Some(tray_entry) = window.app_handle().tray_handle().get_item("known_id") {
    tray_entry.set_title("It works!").unwrap();
}

// or

window.app_handle().tray_handle().get_item("known_id").map(|i|i.set_title("It works!").unwrap());

```

At first glance to me - I haven't tested this fully yet, but on my basic app it's working - it looks like the get_item function could be changed to 

```rust
impl<R: Runtime> SystemTrayHandle<R> {
   /// Gets an Option<handle> to the menu item that has the specified `id`.
   pub fn get_item(&self, id: MenuIdRef<'_>) -> Option<SystemTrayMenuItemHandle<R>> {
     self.ids.lock().unwrap().iter().find(|i|i.1 == id).and_then(|i| Some(SystemTrayMenuItemHandle {
         id: *i.0,
         tray_handler: self.inner.clone(),
        })
     )
  }
```

Or am I missing something really obvious /  completely misunderstanding the component model?

**Comment by ahqsoftwares** [comment]
Shall I give it a try? I think I can do it.

**Comment by lucasfernog** [comment]
@ahqsoftwares I would love to see a PR. But since we're on v1 and we can't introduce any breaking changes, you could add a new `try_get_item` function.

**Comment by ahqsoftwares** [comment]
I see
