### ISSUE TITLE
[feat] `InvokeError` `new` method.

### ISSUE THREAD

**Issue by bicarlsen** [tauri-apps/tauri#5497]
### Describe the problem

It would be nice to be able to initialize an [`InvokeError`](https://github.com/tauri-apps/tauri/blob/6ca8a056e8680464e64f0e8cf6c0765641f1687d/core/tauri/src/hooks.rs#L90) manually so we can `impl`ement `Into<InvokeError>` for our own error types without having to delegate through [`anyhow`](https://docs.rs/anyhow/latest/anyhow/) or [`serde_json`](https://docs.rs/serde_json/latest/serde_json/).

This delegation is currently required because `InvokeError` has a private field, so the only public way to initialize one is through the [`from_anyhow`](https://github.com/tauri-apps/tauri/blob/6ca8a056e8680464e64f0e8cf6c0765641f1687d/core/tauri/src/hooks.rs#L101) or [`from_serde_json`](https://github.com/tauri-apps/tauri/blob/6ca8a056e8680464e64f0e8cf6c0765641f1687d/core/tauri/src/hooks.rs#L95) methods.

### Describe the solution you'd like

Add a `new` method to `InvokeError`, e.g.
```rust
use serde_json::Value as JsonValue;
// ...
impl InvokeError {
  pub fn new(error: JsonValue) -> Self {
    InvokeError(error)
  }
  // ...
}

or make the wrapped field of `InvokeError` public, e.g.
```rust
pub struct InvokeError(pub JsonValue);
```

### Alternatives considered

It seems that adding a `new` mehtod would be preferred over making the interior field `pub`lic.

**Comment by FabianLars** [comment]
what's the use case here? I can't think of an occurrence where Tauri _users_ would/should use `InvokeError`

**Comment by lucasfernog** [comment]
Also you could use the `impl<T: Serialize> From<T> for InvokeError`.

**Comment by bicarlsen** [comment]
> what's the use case here? I can't think of an occurrence where Tauri _users_ would/should use `InvokeError`

I ran into it because I want to return my own error type from a `tauri::command`. e.g.
```rust
enum MyError {
  // ...
}

fn foo() -> Result<(), MyError> {
  // ...
}

fn bar() -> Result<(), MyError> {
  foo()?;
  // ...
  Ok(())
}
```

**Comment by FabianLars** [comment]
As long as your error implements serde::Serialize you're good to go. Here's the relevant part from our wip docs https://jonaskruckenberg.github.io/tauri-docs-wip/development/inter-process-communication.html#error-handling i try to finally integrate that into the live docs this weekend...
