### ISSUE TITLE
[bug] Prevent exit and then try to get main window crashed?

### ISSUE THREAD

**Issue by richerfu** [tauri-apps/tauri#5500]
### Describe the bug

```rust
.run(|app, event| match event {
            tauri::RunEvent::ExitRequested { api, .. } => {
                let win = app.get_window("main").unwrap();
                let visible = win.is_visible().unwrap();
                println!("{}",visible);
                api.prevent_exit();
            }
            _ => {}
 });
```

I set `prevent_exit()` and then try to get window,but crashed.
<img width="808" alt="图片" src="https://user-images.githubusercontent.com/32590310/198447621-05bdeed9-9133-469f-b8cd-872e8f94505d.png">

### Platform and versions

Environment
  › OS: Mac OS 12.5.1 X64
  › Node.js: 16.7.0
  › npm: 7.20.3
  › pnpm: 7.13.2
  › yarn: 1.22.18
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  ├─ .idea
  └─ src

**Comment by amrbashir** [comment]
`ExitRequested` is meant to stop the app from closing not the window, I think you are looking for [`CloseRequested`](https://docs.rs/tauri/latest/tauri/enum.WindowEvent.html#variant.CloseRequested) event instead.

The crash happens because you called `.unwrap()` and you can never be sure that `get_window()` will return a `Window` because the label could be wrong or the window doesn't exist anymore.

**Comment by richerfu** [comment]
Thanks, i fixed it.

**Comment by shanu-mol** [comment]
@southorange1228 Getting same issue, plz provide the fix ?

**Comment by richerfu** [comment]
Using `WindowEvent` like this.
```rust
run(|app, event| match event {
            tauri::RunEvent::WindowEvent {
                label,
                event: win_event,
                ..
            } => match win_event {
                tauri::WindowEvent::CloseRequested { api, .. } => {
                    let win = app.get_window(label.as_str()).unwrap();
                    win.hide().unwrap();
                    api.prevent_close();
                }
                _ => {}
            },
            _ => {}
 })
```

@shanu-mol

**Comment by shanu-mol** [comment]
@southorange1228 Thanks, It helped.

![fix](https://user-images.githubusercontent.com/91492374/199487484-b1b8765d-3701-4c50-a446-ec7aae5670e7.png)

**Comment by luoxmc** [comment]
Thanks, this worked for me
