### ISSUE TITLE
[bug] pnpm tauri dev fails for new project

### ISSUE THREAD

**Issue by NoelJacob** [tauri-apps/tauri#5507]
### Describe the bug

Created a fresh project of sveltekit and ran dev but it fails.

### Reproduction

1. `pnpm create tauri-app`
```
.../share/pnpm/store/v3/tmp/dlx-9069     |   +3 +
Packages are cloned from the content-addressable store to the virtual store.
Content-addressable store is at: /home/john/.local/share/pnpm/store/v3
Virtual store is at:             ../.local/share/pnpm/store/v3/tmp/dlx-9069/node_modules/.pnpm
.../share/pnpm/store/v3/tmp/dlx-9069     | Progress: resolved 10, reused 3, downloaded 0, added 3, done

✔ Project name · debug
✔ Choose your package manager · pnpm
✔ Choose your UI template · svelte-kit

Please follow https://tauri.app/v1/guides/getting-started/prerequisites to install the needed prerequisites, if you haven't already.

Done, Now run:
cd debug
pnpm install
pnpm tauri dev
```
2. `cd debug && pnpm install && pnpm tauri dev`

### Expected behavior

Run as expected

### Platform and versions

```
pnpm run tauri info

> algorand-desktop@0.0.0 tauri /home/john/Desktop/algo-tauri/Algorand Desktop
> tauri "info"


Environment
› OS: Garuda Linux Soaring X64
› Node.js: 18.10.0
› npm: 8.19.2
› pnpm: 7.13.2
› yarn: Not installed!
› rustup: 1.25.1
› rustc: 1.66.0-nightly
› cargo: 1.66.0-nightly
› Rust toolchain: nightly-x86_64-unknown-linux-gnu
```

### Stack trace
https://gist.github.com/NoelJacob/921edaf3c2a571851aa88eabf7dcba3d

### Additional context

My distro is Arch

**Comment by FabianLars** [comment]
Did you install all the system dependencies? https://tauri.app/v1/guides/getting-started/prerequisites/#setting-up-linux

If so, can you try re-installing webkit2gtk? (because the missing dependency is a direct dependency of webkitgtk).
If that doesn't work you could try installing the missing dep directly via something like `sudo pacman -S icu`

**Comment by NoelJacob** [comment]
Thanks!
