### ISSUE TITLE
[feat] Have shadows even when disabling title bar on windows.

### ISSUE THREAD

**Issue by VIEWVIEWVIEW** [tauri-apps/tauri#5509]
### Describe the problem

I have implemented my own title bar, with maximizing, minimizing and close buttons. However, to disable the original buttons, I must pass 
```
    "windows": [
      {
        "decorations": false,
      }
``` 
in the config. This disables all decorations, including the shadows. I only want to disable the title bar, but keep the shadows.

### Describe the solution you'd like

I would like to have a setting to only disable the title bar, but keep the shadows (and maybe even the rounded corners on win11).

### Additional context

Title bar disabled but shadows missing:
![image](https://user-images.githubusercontent.com/39219018/198843249-dbedce8f-1f4e-40e4-858d-563c79b54556.png)

Title bar enabled, but shadows are here:
![image](https://user-images.githubusercontent.com/39219018/198843224-4411c70c-7ec5-4b9c-9dab-0b0ff3a547c8.png)

**Comment by amrbashir** [comment]
use https://github.com/tauri-apps/window-shadows
