### ISSUE TITLE
Tauri App skips a Keyboard input while writing on an Editor using Draft.js [bug] 

### ISSUE THREAD

**Issue by appidemic-studio** [tauri-apps/tauri#5512]
### Describe the bug

I was creating this Tauri app with React as the Frontend. I imported the Editor module from Draft.js and while typing on it I found that the 2nd alphabet for each word doe not show up on the editor.

Example --> Hlp  ///Missed the e
Pease ///Missed the l

But on checking this in the browser, I found that it works okay in Chrome or Firefox.

Does anybody know a suitable workaround?
Here's the code for the Editor Window -

```
import React from 'react';
import {Editor, EditorState} from 'draft-js';
import 'draft-js/dist/Draft.css';

function MyEditor() {
  const [editorState, setEditorState] = React.useState(
    () => EditorState.createEmpty(),
  );

  return <Editor editorState={editorState} onChange={setEditorState} />;
}
```

### Reproduction

1. Install and run tauri app
2. Install React and Draft.js
3. Copy paste the code above in App.js

### Expected behavior

Expected to write each alphabet in the words.

### Platform and versions

Environment
  › OS: Pop!_OS 22.04 X64
  › Node.js: 18.10.0
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.66.0-nightly
  › cargo: 1.66.0-nightly
  › Rust toolchain: nightly-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React

App directory structure
  ├─ public
  ├─ src-tauri
  ├─ src
  ├─ node_modules
  └─ dist

**Comment by amrbashir** [comment]
Please provide a minimal repro
