### ISSUE TITLE
[bug] invalid accelerator: AcceleratorParseError("Couldn't identify \"ARROWUP\" as a valid `KeyCode`")

### ISSUE THREAD

**Issue by lencx** [tauri-apps/tauri#5516]
### Describe the bug

```rs
Menu::new()
  .add_item(CustomMenuItem::new("scroll_top".to_string(), "Scroll to Top of Screen")
  .accelerator("CmdOrCtrl+ArrowUp"))
```

output:

```bash
❯ yarn tauri dev
yarn run v1.22.19
$ tauri dev
     Running BeforeDevCommand (`npm run dev`)

> wa@0.1.5 dev
> vite


  VITE v3.1.8  ready in 596 ms

  ➜  Local:   http://localhost:3681/
  ➜  Network: use --host to expose
        Info Watching /Users/lencx/github/lencx/WA/src-tauri for changes...
   Compiling mac-notification-sys v0.5.6
   Compiling notify-rust v4.5.10
   Compiling tauri v1.1.1
   Compiling wa v0.0.0 (/Users/lencx/github/lencx/WA/src-tauri)
    Finished dev [unoptimized + debuginfo] target(s) in 13.12s
thread 'main' panicked at 'invalid accelerator: AcceleratorParseError("Couldn't identify \"ARROWUP\" as a valid `KeyCode`")', /Users/lencx/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-runtime-wry-0.11.1/src/lib.rs:348:70
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error Command failed with exit code 101.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Platform and versions

Environment
  › OS: Mac OS 12.6.0 X64
  › Node.js: 18.7.0
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.59.0
  › cargo: 1.59.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › framework: React

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ dist-isolation
  ├─ scripts
  ├─ .github
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  ├─ assets
  └─ src

**Comment by amrbashir** [comment]
You can use `Up` for now, I will add suppport for `ArrowUp` for next version.
