### ISSUE TITLE
[feat] Theme setter

### ISSUE THREAD

**Issue by nikosszzz** [tauri-apps/tauri#5517]
### Describe the problem

since Tauri offers you the current system theme using ``appWindow.theme()``, we should have a Theme setter so that we can easily make Theme systems in our apps and especially ones that are adapting to Tauri from example Electron.

### Describe the solution you'd like

Add a theme setter on ``appWindow``, for example: ``appWindow.theme = "light"``.

### Alternatives considered

Currently only HTML/CSS based ones.

**Comment by amrbashir** [comment]
duplicate of https://github.com/tauri-apps/tauri/issues/5279
