### ISSUE TITLE
[bug] `navigator is not defined` when importing anything from @tauri-apps/api/path in SvelteKit

### ISSUE THREAD

**Issue by aintDatCap** [tauri-apps/tauri#5518]
### Describe the bug

Importing anything from the **path** api via js/ts on a **SvelteKit** project returns  `navigator is not defined` with a `500 - Internal Error` error code.
This probably happens because the **path** module calls the `isWindows()` method too early.

![image](https://user-images.githubusercontent.com/89939707/199093013-d69cb554-3663-4c1f-9d6d-95707a5d53cd.png)

### Reproduction

1. Use the `create-tauri app` command to generate a SvelteKit project.
2. Add in any +page.svelte file `import {dirname} from "@tauri-apps/api/path"` where `dirname` can be exchanged with anything in the **path** api.
3. Now you can both use `tauri dev` or `tauri build` command, it should return `navigator is not defined` error.

### Expected behavior

Expected to import `dirname` without any error

### Platform and versions

Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 107.0.1418.24
  › MSVC:
      - Visual Studio Community 2022
  › Node.js: 16.15.0
  › npm: 8.19.2
  › pnpm: 7.1.9
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:1420/
  › framework: Svelte

App directory structure
  ├─ .git
  ├─ .svelte-kit
  ├─ .vscode
  ├─ build
  ├─ node_modules
  ├─ src
  ├─ src-tauri
  └─ static

**Comment by FabianLars** [comment]
Try using dynamic imports instead. this thingy -> `await import()`

> This probably happens because the path module calls the isWindows() method too early.

Indeed. The sep and delimiter variable declaration break the import in SSR environments :/
