### ISSUE TITLE
Cannot open mailto links[bug] 

### ISSUE THREAD

**Issue by anterpin** [tauri-apps/tauri#5521]
### Describe the bug

Tauri cannot open mailto links

![image](https://user-images.githubusercontent.com/44070188/199342418-fc8c06fd-9956-44c1-9ab5-fa0184dc9324.png)

### Reproduction

-- `tauri.conf.json`
```
"allowlist": {
	"all": true,
	"shell": {
		"open": true
	}
},
```
-- javascript
```
<a href="mailto:user@mail.com"> test </a>
```

### Expected behavior

It should open the default mail application

### Platform and versions

```
Environment
  › OS: Manjaro 22.0.0 X64
  › Node.js: 16.16.0
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../public
  › devPath: http://localhost:8082/
  › framework: Svelte

App directory structure
  ├─ node_modules
  ├─ src
  ├─ .svelte-kit
  ├─ src-tauri
  └─ static
```

**Comment by yokljo** [comment]
@lucasfernog Hi, I believe this bug is back in Tauri 2, as I get exactly the same page as in the above screenshot when I click a mailto: link (in version 2.0.6 of Tauri).

**Comment by FabianLars** [comment]
@yokljo do you have the shell plugin installed?

**Comment by gottlike** [comment]
@FabianLars 

I did add the shell plugin and have these permissions:

```
  "permissions": [
    "core:default",
    "shell:allow-open",
    "shell:default"
  ]
```

And my mailto links won't open (nothing happens on macOS).

**Comment by FabianLars** [comment]
Any errors in the dev tools console? What about your `tauri info` output?

I'll try it out again once I'm back home but I don't see anything wrong in the plugin's code right now.

**Comment by FabianLars** [comment]
Using OP's example `<a href="mailto:user@mail.com"> test </a>`:
- Windows: works
- macOS: requires `target="_blank"`

The reason for that is that on Windows the os/webview handles those links already but on macOS it relies on the shell plugin which only reacts to `a` elements with the _blank target.

For me the current behavior is good enough, but feel free to open an issue here https://github.com/tauri-apps/plugins-workspace if you disagree.

**Comment by gottlike** [comment]
Thanks, @FabianLars. With "_blank" it works as expected and this is good enough for me, too! 👍

**Comment by curry-battle** [comment]
Might be helpful to someone, currently, this plugin seems to be a right choice. 🥇 
https://v2.tauri.app/ja/plugin/opener/
