### ISSUE TITLE
[bug] cannot download tauri-cli because of cargo dependency error when using cargo below 1.60

### ISSUE THREAD

**Issue by Toasterson** [tauri-apps/tauri#5522]
### Describe the bug

When I want to install `tauri-cli` on my installation where I have rust 1.59. I get the following error from cargo
```
    Updating crates.io index
  Installing tauri-cli v1.1.1
error: failed to compile `tauri-cli v1.1.1`, intermediate artifacts can be found at `/Users/toasty/.cargo-target`

Caused by:
  failed to select a version for the requirement `serde_with = "^2.0"`
  candidate versions found which didn't match: 1.14.0, 1.13.0, 1.12.1, ...
  location searched: crates.io index
  required by package `tauri-cli v1.1.1`
```

The same command works fine on linux. Also serde_with has a version 2.0.1 published on crates.io so this may be a cargo bug. https://crates.io/crates/serde_with
I have tried removing the index directory manually but that did not help.

### Reproduction

1. Have rust 1.59
2. run `cargo install tauri-cli`

### Expected behavior

Cargo installs tauri-cli

### Platform and versions

macOS Monterey 12.6
rustc 1.59.0 (9d1b2106e 2022-02-23)

### Stack trace

```shell
None
```

### Additional context

updating to 1.64 fixed the issue

We should update rust version for cli to 1.60 as this is what serde_with uses.

**Comment by lucasfernog** [comment]
You're right, we forgot to update the MSRV for the CLI. I'll fix it for v1.2.
