### ISSUE TITLE
[bug] `tauri dev` removes `devtools` cargo feature

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tauri#5525]
### Describe the bug

Running `tauri dev` seems to remove the `devtools` cargo feature

### Platform and versions

Environment
  › OS: Mac OS 10.15.7 X64
  › Node.js: 16.15.0
  › npm: 8.12.1
  › pnpm: 6.11.0
  › yarn: 1.22.15
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: Svelte

App directory structure
  ├─ node_modules
  ├─ .github
  ├─ src-tauri
  ├─ build
  ├─ .git
  ├─ assets
  └─ src

**Comment by FabianLars** [comment]
I can't reproduce this. It only re-orders it, in my case to the front of the list.

**Comment by probablykasper** [comment]
Weird, for me it gets removed. It's on this repo that I noticed it: https://github.com/probablykasper/remind-me-again

**Comment by FabianLars** [comment]
It does indeed remove _one_ of the _two_ `devtools` flags for me (you have one in front and one in the back)

**Comment by probablykasper** [comment]
🤦‍♂️
