### ISSUE TITLE
JS Api fs import

### ISSUE THREAD

**Issue by arkhenstone** [tauri-apps/tauri#553]
File system part of JS API Documentation is outdated (https://github.com/tauri-apps/tauri/wiki/11.-API#file-system) 

It should be
```
import {
  Dir,
  copyFile,
  createDir,
  readBinaryFile,
  readDir,
  readTextFile,
  removeDir,
  removeFile,
  renameFile,
  writeFile
}  from 'tauri/api/fs' 
```

Also when I tried that, I got an error importing the module because it searches for tauri.js in current directory, while it should be in the parent.

**Comment by Laegel** [comment]
You're right, bad copy/paste, here. :|
Fixed!
