### ISSUE TITLE
Cannot find module '@tauri-apps/cli-darwin-x64'

### ISSUE THREAD

**Issue by edimoldovan** [tauri-apps/tauri#5531]
HI!

I tried running the examples/aåpi the way the documention says to. I am getting this

`yarn tauri dev
yarn run v1.22.19
warning package.json: No license field
warning ../../../../../package.json: No license field
$ node ../../tooling/cli/node/tauri.js dev
/Users/ed/dev/rust/tauri/tooling/cli/node/index.js:234
    throw loadError
    ^

Error: Cannot find module '@tauri-apps/cli-darwin-x64'
Require stack:
- /Users/ed/dev/rust/tauri/tooling/cli/node/index.js
- /Users/ed/dev/rust/tauri/tooling/cli/node/main.js
- /Users/ed/dev/rust/tauri/tooling/cli/node/tauri.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/ed/dev/rust/tauri/tooling/cli/node/index.js:111:29)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ed/dev/rust/tauri/tooling/cli/node/index.js',
    '/Users/ed/dev/rust/tauri/tooling/cli/node/main.js',
    '/Users/ed/dev/rust/tauri/tooling/cli/node/tauri.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

I'm on a Mac M1 Pro, latest MacOS Ventura.

**Comment by edimoldovan** [comment]
Checking further, I think none of the examples that need `yarn` or `node` to run are working.

**Comment by FabianLars** [comment]
Did you say `yes` when the script asked if you want to install the node cli? (We should change it up a bit since it's required now)

**Comment by edimoldovan** [comment]
Yes, I did.

**Comment by lucasfernog** [comment]
Kinda weird that it's trying to find `@tauri-apps/cli-darwin-x64` instead of `@tauri-apps/cli-darwin-arm64` (or `./cli.darwin-arm64.node` when you build it locally).

What is the output of `$ node -p "process.arch"`? From the error message it'll print `x64`, which is not your actual architecture (should actually print `arm64`). Maybe you're running a Rosetta Node.js? Try reinstalling Node.

**Comment by Michael-Reich** [comment]
I have the same issue and I'm on a Intel CPU

**Comment by robertlagrant** [comment]
I hit this but on Linux, in a CI build:
```bash
$ npm i
added 848 packages in 19s
146 packages are looking for funding
  run `npm fund` for details
$ npm run tauri.build
> gourami-frontend@0.0.0 tauri.build
> tauri build
/builds/...../node_modules/@tauri-apps/cli/index.js:234
    throw loadError
    ^
Error: Cannot find module '@tauri-apps/cli-linux-x64-gnu'
```

The `npm run tauri.build` command is defined as `tauri build` in my package.json.

**Comment by robertlagrant** [comment]
I hit this but on Linux, in a CI build:
```bash
$ npm i
added 848 packages in 19s
146 packages are looking for funding
  run `npm fund` for details
$ npm run tauri.build
> our-package@0.0.0 tauri.build
> tauri build
/builds/...../our-package/node_modules/@tauri-apps/cli/index.js:234
    throw loadError
    ^
Error: Cannot find module '@tauri-apps/cli-linux-x64-gnu'
```

The `npm run tauri.build` command is defined as `tauri build` in my package.json.

**Comment by NiklasEi** [comment]
I had the same issue on Linux and seem to have fixed it by deleting the `package-lock.json` file, removing `node_modules` and running `npm i` again.

**Comment by zhanglun** [comment]
I also encountered this problem on Mac M1 Pro after upgrade OS version to Ventura.

**Comment by KStephening** [comment]
you can install higher version of node .
I use nvm manage node. By use higher version of node ,I can BUILD .
@edimoldovan @zhanglun 
![image](https://user-images.githubusercontent.com/23191186/210679213-626e0248-8956-452b-a423-30761a5fcd6f.png)

**Comment by KStephening** [comment]
> you can install higher version of node . I use nvm manage node. By use higher version of node ,I can BUILD . @edimoldovan @zhanglun ![image](https://user-images.githubusercontent.com/23191186/210679213-626e0248-8956-452b-a423-30761a5fcd6f.png)

the image from nvm.  https://github.com/nvm-sh/nvm

**Comment by zhanglun** [comment]
> you can install higher version of node . I use nvm manage node. By use higher version of node ,I can BUILD . @edimoldovan @zhanglun ![image](https://user-images.githubusercontent.com/23191186/210679213-626e0248-8956-452b-a423-30761a5fcd6f.png)

still not work for me. But I solved it with:

```
cd src-tauri
cargo clean
cargo build
```

**Comment by bkrmendy** [comment]
Upgrading to node v16.17.0 (`lts/gallium`) from node v14.20.0 (`lts/fermium`) fixed it for me.

**Comment by JPAGhosn** [comment]
If you are migrating from Mac M1 to x86 device, you'll need to delete the package-lock.json and node_modules then run npm i again to reinstall all the dependencies.

**Comment by deid84** [comment]
hello, i have the same problem, if i try to install on windows works smoothly but on a x86 mac it installs api and cli but not find cli-darwin-x64. Even if i copy the folder from another project it works until the next npm install

**Comment by Kottakji** [comment]
I've had this problem in CI, and added the following to fix it:

```yml
      - name: Install frontend dependencies
        run: npm install
        
      - name: Install Tauri cli
        run: npm install --save-dev @tauri-apps/cli

```

**Comment by kjxbyz** [comment]
same issue.

[link](https://github.com/cyf/faforever/actions/runs/8832495024/job/24249917351)

**Comment by gaki2** [comment]
Hello, I solved same problem by **downgrading node version from 20.14.0 to 18.17.0**.

**Comment by bmsimo** [comment]
I'm on Node v20.18.0 and i was trying to run the tauri examples, precisely the api example, none of the above solutions worked.

What i did was delete the references to the @tauri-apps/cli and @tauri-apps/api and just added them with `pnpm i @tauri-apps/api` `pnpm i -D @tauri-apps/cli` The newer version takes care of using the corresponding architechture
