### ISSUE TITLE
JS api - Error importing module tauri.js

### ISSUE THREAD

**Issue by arkhenstone** [tauri-apps/tauri#554]
**Describe the bug**
Can't build JS app (quasar build) due to error in https://github.com/tauri-apps/tauri/blob/dev/cli/tauri.js/api/fs/index.js when importing fs.

ERROR in ./node_modules/tauri/api/fs/index.js
Module not found: Error: Can't resolve './tauri' in '-project-path-/node_modules/tauri/api/fs'

**Expected behavior**
Correcting script with ../tauri.js let the build works. (See screenshots below)

![image](https://user-images.githubusercontent.com/17592744/78571868-03bd0b80-7827-11ea-9a4e-06bb08305b2c.png)

![image](https://user-images.githubusercontent.com/17592744/78572030-3b2bb800-7827-11ea-8b90-7ebd82aef9a7.png)

**Comment by Laegel** [comment]
Did you install the tauri JS package globally or locally? If globally, please also install it locally; if locally, this might be a bug.

**Comment by arkhenstone** [comment]
Locally, with yarn. It doesn't work both on my work machine and for the deployment machine. Correcting the package both makes it functional and makes the build succeed.

**Comment by nothingismagick** [comment]
Accepted will fix and release a new version. Thanks for the report!

**Comment by nothingismagick** [comment]
See #555

**Comment by nothingismagick** [comment]
@arkhenstone - v0.5.2 has been released.
