### ISSUE TITLE
[feat] http.fetch may be support formData

### ISSUE THREAD

**Issue by Sneaken** [tauri-apps/tauri#5545]
### Describe the problem

i need use FormData in CORS fetch

### Describe the solution you'd like

rust can parse my FormData and request again

**Comment by FabianLars** [comment]
If you add the `"http-multipart"` feature flag to the tauri dependency in Cargo.toml it _should_ work. If not please provide a code example of what you're trying to do.

Edit: I think you have to set the `Content-Type` header yourself on request 🤔

**Comment by Sneaken** [comment]
> 

i add the http-multipart and then how to use ? 

for example:

import { http } from '@tauri-apps/api';

const formData = new FormData();
formData.append('msg', 'test_message');

await http
      .fetch('some_url', {
        method: 'POST',
        headers: {
          'content-type': 'multipart/form-data',
        },
        body: http.Body.form(formData) // how can i do ?
      })

**Comment by Sneaken** [comment]
> If you add the `"http-multipart"` feature flag to the tauri dependency in Cargo.toml it _should_ work. If not please provide a code example of what you're trying to do.
> 
> Edit: I think you have to set the `Content-Type` header yourself on request 🤔


i add the http-multipart and then how to use ? 

for example:

```js
import { http } from '@tauri-apps/api';

const formData = new FormData();
formData.append('msg', 'test_message');

await http
      .fetch('some_url', {
        method: 'POST',
        headers: {
          'content-type': 'multipart/form-data',
        },
        body: http.Body.form(formData) // how can i do ?
      })


```

**Comment by lucasfernog** [comment]
That's right @Sneaken though i'm not sure if it supports a FormData object, let me check. Any regular JS object should work.
