### ISSUE TITLE
[feat] New API for SSH (client)

### ISSUE THREAD

**Issue by seahindeniz** [tauri-apps/tauri#5548]
### Describe the problem

Creating an SSH connection to execute command on a remote server is not easy. I have search crates and tried to implement a solution but I'm actually not an expert in Rust and couldn't implement a solution.

### Describe the solution you'd like

If Tauri could provide an API, it'll be much easier to implement solutions. 
An API that could create a live connection with password/private key credentials and sends command and collect responses from the SSH server. Frontend could also terminate and create a new connection on demand.

**Comment by amrbashir** [comment]
I don't think we will ever add such api. It is a huge amount of work and outside of tauri scope. You should probably look into using https://docs.rs/ssh2/0.9.3/ssh2/

**Comment by nothingismagick** [comment]
Totally agree with Amr. There are sooooooo many use cases for Tauri apps, that we could never do justice to them all in core. This is why we built the plugin system (and in some cases even the sidecar approach would make sense.) But thankyou anyway for the proposal!

**Comment by Byron** [comment]
Sorry @amrbashir for warming this up again. If someone wanted to implement such a feature, i.e. from the frontend of a normal tauri application, make it possible for that webview to connect to a different tauri backend? Maybe one that was launched on a remote machine and thus uses `stdin/stdout over SSH` as communication channel?
This question was sparked by https://github.com/gitbutlerapp/gitbutler/issues/5941 .
Maybe there is also related information, i.e. what it would take to host the frontend in a standard web-browser but let it connect to a backend in the cloud.
Also apologies if this is obvious, I am still pretty new to `tauri`.

Thanks for sharing your knowledge on this one.

**Comment by amrbashir** [comment]
@Byron for hosting the application frontend on a remote website, there is a few ways you can do:

1. you can configure your [`frontendDist`](https://tauri.app/reference/config/#frontenddist) config option to use the remote URL as you like, but you will need to also configure your capability's [`remote`](https://tauri.app/reference/acl/capability/#remote) option to allow remote URLs to have access to Tauri APIs.
2. For more advanced usage and custom authentication purposes, you can [register a custom protocol](https://docs.rs/tauri/latest/tauri/struct.Builder.html#method.register_uri_scheme_protocol) in the Rust side, and set your [`frontendDist`](https://tauri.app/reference/config/#frontenddist) to this custom protocol.
In your custom protocol handler, you will do the authentication or whatever you need to fetch the assets from a remote server, do any processing you need then return them as a `Response` to the custom protocol.

I think the second solution (and maybe the first one too) can cover the SSH part of your question as well? Let me know
