### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by obrhaberer** [tauri-apps/tauri#5549]
### Describe the bug

white window after I changed the identifier from com.tauri.dev to something else

### Reproduction

changed the identifier com.tauri.dev to something else

### Expected behavior

work properly

### Platform and versions

both snippets not working on OSX Ventura

**Comment by Bukmopbl4** [comment]
I think more information is needed, since on Ventura 13.0 everything works in the initial application. Check this [Start Guide](https://tauri.app/v1/guides/getting-started/prerequisites)
