### ISSUE TITLE
[feat] expose tao's system tray tooltip apis 

### ISSUE THREAD

**Issue by ahqsoftwares** [tauri-apps/tauri#5558]
### Describe the problem

Currently, when making a tray we can't set the tray tooltip

This tray tooltip
![image](https://user-images.githubusercontent.com/84524025/200152804-34130fa5-e974-40fe-8367-7aa5984ef4ad.png)

### Describe the solution you'd like

As the upstream crate (tao) supports with_tooltip. So, is it possible to add such a function on the tauri tray builder.

**Comment by callum-gander** [comment]
I'll take this and try and do it over the next few days if that's okay? Are there any additional considerations I'd need to take into account? @amrbashir

**Comment by amrbashir** [comment]
thanks @callum-gander for your effort. It should be straightforward. let me know if you have any questions.

**Comment by cameronadams777** [comment]
@callum-gander Are you still working on this?

**Comment by callum-gander** [comment]
Sorry, this completely fell off my radar, I'm going to have a look at it again this weekend. Sorry again for the delay

**Comment by IllustrisJack** [comment]
still would be a good feature ;)

**Comment by IllustrisJack** [comment]
Would be a nice feature!

**Comment by ahqsoftwares** [comment]
Shall I try making a PR regarding this?

**Comment by cameronadams777** [comment]
@ahqsoftwares Yeah I would say go ahead if you have bandwidth 🙂

**Comment by ahqsoftwares** [comment]
> @ahqsoftwares Yeah I would say go ahead if you have bandwidth 🙂

✅

**Comment by QuietDevASMR** [comment]
@ahqsoftwares Any update on this? If not, I can take a crack at it 😄

**Comment by cameronadams777** [comment]
@ahqsoftwares Any update on this? If not, I can take a crack at it 😄

**Comment by ahqsoftwares** [comment]
> @ahqsoftwares Any update on this? If not, I can take a crack at it 😄

✅ There is an update, I think I have added the feature will check if that works pretty quick once my pc boot up problems gets fixed

**Comment by ahqsoftwares** [comment]
![image](https://github.com/tauri-apps/tauri/assets/84524025/3b6ff2ef-09d7-4da5-a7e5-98ea87e69a1f)
Well, That did work, making a PR to v 1.3

**Comment by ahqsoftwares** [comment]
It has already been added to tauri 1.3.0 
PR: https://github.com/tauri-apps/tauri/pull/5938

So, I think it's already closed?
