### ISSUE TITLE
Use of media devices and desktop sharing.

### ISSUE THREAD

**Issue by rdwnsjjd** [tauri-apps/tauri#5570]
It is possible to use  `navigator.mediaDevices.getUserMedia` as we use it in browser to get camera-microphone or desktop sharing in tauri?
I printed my navigator on console and it doesn't have any `mediaDevice` method or value. how can I do this in tauri?

**Comment by armand-colin** [comment]
Yes it is possible. Are you using macOS? If so, you will need an `Info.plist` file to give os accesses to your program.
Check out this issue https://github.com/tauri-apps/tauri/issues/2600. The guy has written down his plist file and it seems correct.
Concerning screen sharing, it works on windows and it just became available with the latest version of macOS (Ventura 13).
