### ISSUE TITLE
[bug] non-exhaustive patterns: `&PatternKind::Isolation { .. }` not covered

### ISSUE THREAD

**Issue by Nuli-byte** [tauri-apps/tauri#5575]
### Describe the bug

Error while compiling using "npm run tauri dev" with "sveltekit-ts" after "npm create tauri-app" script.

### Reproduction

1. Install Rust and Cargo
2. npm create tauri-app
3. select npm > sveltekit-ts
4. Execute printed commands `cd tauri-app
  npm install
  npm run tauri dev`

### Expected behavior

To be able to compile and see application.

### Platform and versions

npm run tauri info

> configuration-generator@0.0.0 tauri
> tauri

Environment
  › OS: Windows 10.0.19042 X64
  › Webview2: 107.0.1418.35
  › MSVC: 
  › Node.js: 18.7.0
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: 1.22.10
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:1420/
  › framework: Svelte

App directory structure
  ├─ .svelte-kit
  ├─ .vscode
  ├─ build
  ├─ node_modules
  ├─ src
  ├─ src-tauri
  └─ static

### Stack trace

```shell
error[E0004]: non-exhaustive patterns: `&PatternKind::Isolation { .. }` not covered
    --> C:\Users\U176884\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-codegen-1.1.1\src\context.rs:361:23
     |
361  |   let pattern = match &options.pattern {
     |                       ^^^^^^^^^^^^^^^^ pattern `&PatternKind::Isolation { .. }` not covered
     |
note: `PatternKind` defined here
    --> C:\Users\U176884\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-utils-1.2.0\src\config.rs:2164:3
     |
2160 | pub enum PatternKind {
     | --------------------
...
2164 |   Isolation {
     |   ^^^^^^^^^ not covered
     = note: the matched value is of type `&PatternKind`
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
     |
362  ~     PatternKind::Brownfield => quote!(#root::Pattern::Brownfield(std::marker::PhantomData)),
363  ~     &PatternKind::Isolation { .. } => todo!(),
     |

For more information about this error, try `rustc --explain E0004`.
error: could not compile `tauri-codegen` due to previous error
```

**Comment by lucasfernog** [comment]
Please run `cargo update` in the src-tauri folder and try again. I think your tauri-utils has been updated to 1.2.0.

**Comment by Nuli-byte** [comment]
My bad. I recreated an app with "npm create tauri-app" and it works now.
