### ISSUE TITLE
[bug] Can't use headless browser in backend code

### ISSUE THREAD

**Issue by Septias** [tauri-apps/tauri#5578]
### Describe the bug

I added [this](https://github.com/Septias/better-ilias/blob/6daf145c3ab3e0796a8413b1fe1de4e32a5f7bd1/src-tauri/src/client.rs#L85-L114) code to my project and when it is executed, the tauri window crashes and reboots.
The browser beeing used is 
```
headless_chrome = {git = " https://github.com/atroche/rust-headless-chrome "}
```

### Reproduction
If you want to reproduce this, contact me on Discord Septias#1614, because you need my valid credentials.
### Platform and versions
Environment
  › OS: Manjaro 22.0.0 X64
  › Node.js: 17.3.0
  › npm: 8.3.0
  › pnpm: 7.13.4
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.66.0-nightly
  › cargo: 1.66.0-nightly
  › Rust toolchain: nightly-x86_64-unknown-linux-gnu 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.1.1 (outdated, latest: 1.2.0)
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: default-src 'self'; img-src * asset: https://asset.localhost; font-src *
  › distDir: ../frontend/dist
  › devPath: http://localhost:3333/
package.json not found

### Stack trace

```shell
warning: the following packages contain code that will be rejected by a future version of Rust: traitobject v0.1.0
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 86`
```
This error originates from chrome-headless code, but it works normally, so I guess it's not the cause.

### Furthermore
The token is produced without an error and everything else is fine. Thats why my first guess is that the shutdown process of the headless browsers somehow also triggers shutdown of the taur browser instance.

**Comment by FabianLars** [comment]
I think the problem is save_creds - if you write to a file in src-tauri it will trigger the dev watcher and restart the app. You can check that by running tauri dev with the `--no-watch` flag.

btw this will also be an issue in production because the location of the executable is read-only

**Comment by Septias** [comment]
Aaahhhh, I had that in my mind for a sec, but kind of lost it again. Gonna do that, I will also move the file to the config folder. (tauri::api::fs::get_onfig()) or so
