### ISSUE TITLE
[docs] Want to use tilde to refer to the src folder

### ISSUE THREAD

**Issue by KeithMHughesRoteraAI** [tauri-apps/tauri#5585]
I am using Tauri 1.2.0

My app is written in React. I want to be able to use ~ to refer to the root src folder. I added a webpack.config.ts file with an alias to resolve ~ properly.

The webpack file is not using used, or it is being ignored. Is it possible in the documentation for Tauri to say how to be able to have ~ in my frontend files refer to the src foulder?

**Comment by amrbashir** [comment]
Tauri doesn't care how you set up your front-end as long as it outputs html/css/js at the end, so please consult the webpack community. Or reach to our discord community, they may be able to help.
