### ISSUE TITLE
[bug] CORS regression when tauri.conf.json > build > devPath points to a directory.

### ISSUE THREAD

**Issue by iohzrd** [tauri-apps/tauri#5587]
### Describe the bug

I updated to v1.2.0 and now I'm getting this CORS error (js console).
```
[Error] Origin http://127.0.0.1:1430 is not allowed by Access-Control-Allow-Origin. Status code: 403
[Error] Fetch API cannot load http://127.0.0.1:5001/api/v0/id due to access control checks.
[Error] Failed to load resource: Origin http://127.0.0.1:1430 is not allowed by Access-Control-Allow-Origin. Status code: 403 (id, line 0)
[Error] Unhandled Promise Rejection: TypeError: Load failed
	(anonymous function) (index.d004a4cf.js:39453)
	(anonymous function)
```
The app is connecting to a local go-ipfs daemon on port 5001 using [ipfs-http-client](https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs-http-client) and it worked fine in previous versions.
I've had [devPath pointed to a directory](https://github.com/iohzrd/identia/blob/master/src-tauri/tauri.conf.json) for a long time, since I was never able to get past CORS serving on localhost.

I tried various things in tauri.conf.json > tauri.allowlist.http and security.csp but nothing helped. Maybe I just didn't find the magic combo? If there's come combination of things I could do to get it working via dev server, that would be cool too.

### Reproduction

```
git clone https://github.com/iohzrd/identia.git
npm run update
npm start
```

### Expected behavior

no error

### Platform and versions

```
> tauri info

Environment
  › OS: Manjaro 22.0.0 X64
  › Node.js: 16.18.0
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.0
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.0,
  › tauri-build [RUST]: 1.2.0,
  › tao [RUST]: 0.15.2,
  › wry [RUST]: 0.22.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: ../dist
  › framework: Svelte

App directory structure
  ├─ src
  ├─ node_modules
  ├─ dist
  ├─ src-tauri
  ├─ scripts
  ├─ public
  ├─ .vscode
  └─ .git

```

### Additional context

I also tried tweaking the IPFS CORS config, but I don't think that's the problem, since it worked before.
My app [automatically configures](https://github.com/iohzrd/identia/blob/master/src-tauri/src/main.rs#L188) the IPFS daemons "Access-Control-Allow-Origin" and "Access-Control-Allow-Methods" , so that _shouldn't_ be the issue. See resulting config below.
```
  "API": {
    "HTTPHeaders": {
      "Access-Control-Allow-Methods": [
        "GET",
        "POST",
        "PUT"
      ],
      "Access-Control-Allow-Origin": [
        "http://127.0.0.1:5001",
        "tauri://localhost",
        "https://tauri.localhost"
      ]
    }
  },
...
```

**Comment by lucasfernog** [comment]
You'll need to add `http://127.0.0.1:1430` to the `Access-Control-Allow-Origin` array since that's the URL we use now when the devPath is pointed to a local directory. We added this to add HMR support in this case.

**Comment by iohzrd** [comment]
That was the first thing I tried, but it didn't work, so I tried a bunch of things and was pulling my hair out. Turns out there was an orphan/rogue IPFS process that was getting in the way. Sorry for the erroneous report.
