### ISSUE TITLE
[bug] Accelerators with single character in CustomMenuItem won't work

### ISSUE THREAD

**Issue by sprout2000** [tauri-apps/tauri#5592]
### Describe the bug

After update to v1.2, Accelerators with single character in CustomMenuItem won't work.

## Scaffolding

```sh
npm create tauri-app
cd tauri-app
npm run tauri dev
```

## Create a menu

<img width="572" alt="2022-11-09-133745" src="https://user-images.githubusercontent.com/52094761/200739890-bc576af3-da6a-4c02-b240-0e5edf888ab0.png">

```rust
use tauri::{CustomMenuItem, Menu, Submenu};

fn main() {
    tauri::Builder::default()
        .menu(
            Menu::new().add_submenu(Submenu::new(
                "Tauri App",
                Menu::new()
                    // "J" won't work.
                    .add_item(CustomMenuItem::new("close", "Close").accelerator("J"))
                    // "Cmd+foo_bar" works, though.
                    .add_item(CustomMenuItem::new("quit", "Close").accelerator("Cmd+W")),
            )),
        )
        .on_menu_event(|event| match event.menu_item_id() {
            "close" => std::process::exit(0),
            "quit" => std::process::exit(0),
            _ => {}
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

### Expected behavior

Works as it did up to v1.1.

### Platform and versions

% npm run tauri info  

> tauri-app@0.0.0 tauri
> tauri info

Environment
  › OS: Mac OS 13.0.0 X64
  › Node.js: 18.12.1
  › npm: 8.19.3
  › pnpm: 7.14.2
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.2.0
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.0,
  › tauri-build [RUST]: 1.2.0,
  › tao [RUST]: 0.15.3,
  › wry [RUST]: 0.22.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../src
  › devPath: ../src

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ src-tauri
  ├─ .vscode
  └─ src

### Additional context

I've not tried it on other platforms.

**Comment by amrbashir** [comment]
If it worked before 1.2, Can you try running `cargo update` in `src-tauri` and try again? There was an issue with accelerators weren't working and we published a fix.

**Comment by sprout2000** [comment]
> There was an issue with accelerators weren't working and we published a fix.

You mean #5589 ? That issue was also made by me. That [fix](https://github.com/tauri-apps/tao/releases/tag/tao-v0.15.3) cured the accelerators in combination with the cmd key, but this issue is a different matter.

Could you try my reproduction above that was executed with [tao-v0.15.3](https://github.com/tauri-apps/tao/releases/tag/tao-v0.15.3)?
Here's an [example](https://github.com/sprout2000/leafview-tauri/releases/tag/v0.7.5) of it working before v1.2.

**Comment by amrbashir** [comment]
cc @wusyong

**Comment by wusyong** [comment]
I've tried tao v0.15, 14, 13. But if the accelerator is only one character, all versions seem don't work.
I think this is also because we choose to add webview as subview again.
keyDown method from TaoView seems to block the accelerator.
