### ISSUE TITLE
[bug] appWindow.isMaximized() returns false when minimized

### ISSUE THREAD

**Issue by elibroftw** [tauri-apps/tauri#5596]
### Describe the bug

There's no clear way to check if a window was in a maximized state before being minimized. Technically it is not maximized, but practically speaking, the window is maximized in the background/ minimized state. This is also causing issues when unminimize is called on a window that was previously maximized. https://github.com/tauri-apps/tao/issues/622

### Reproduction

1. Run any app in development
2. Open devtools
3. Maximize app
4. Minimize app
5. in devtools use `window.__TAURI__.isMaximized().then(x => console.log(x))`

### Expected behavior

`true`

### Platform and versions

```
$ tauri info

Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 107.0.1418.35
  › MSVC: 
      - Visual Studio Community 2022
  › Node.js: 17.3.1
  › npm: 8.3.0
  › pnpm: Not installed!
  › yarn: 1.22.11       
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.0
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.0,
  › tauri-build [RUST]: 1.2.0,
  › tao [RUST]: 0.15.1,
  › wry [RUST]: 0.22.0,

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  › distDir: ../build
  › devPath: http://localhost:1420/      
  › framework: React
  › bundler: Rollup

App directory structure
  ├─ .git
  ├─ .github
  ├─ .idea
  ├─ assets
  ├─ build
  ├─ node_modules
  ├─ public
  ├─ src
  ├─ src-tauri
  └─ utils
Done in 8.10s.
```

### Additional context

maximized and unminize assume different things.

**Comment by elibroftw** [comment]
Also, when using https://github.com/tauri-apps/tauri-plugin-window-state, if I maximize a window, minimize it and close it while it is minimized, on the next open, the window is resized to its size and position before being maximized.

**Comment by amrbashir** [comment]
A window can be minimized or maximized; it can't be in both states.

> Also, when using [tauri-apps/tauri-plugin-window-state](https://github.com/tauri-apps/tauri-plugin-window-state), if I maximize a window, minimize it and close it while it is minimized, on the next open, the window is resized to its size and position before being maximized.

I think we have an open issue for that in the tauri-plugin-window-state repo

**Comment by elibroftw** [comment]
That's fine

**Comment by elibroftw** [comment]
Someone deleted my other issue :(

**Comment by amrbashir** [comment]
What other issue? can you re-create it?

**Comment by elibroftw** [comment]
No I found out you just transferred it but github did not notify me that you transferred the issue.
