### ISSUE TITLE
[docs] skipTaskbar not clear and not working as expected

### ISSUE THREAD

**Issue by boguz** [tauri-apps/tauri#5598]
While trying to figure out how to hide the dock icon on a small app i am creating for myself, i found something in the docs which i find a bit confusing ((https://tauri.app/v1/api/config/#windowconfig.skiptaskbar)):

The property name is `skipTaskbar`
The description is _"Whether or not the window icon should be added to the taskbar"_.

So setting it to true true will
- skip the taskbar (no icon on the taskbar)
- will the icon be added to the taskbar (like it says on the description)?
🤔

I think the sentence could be better formulated, maybe something like "Wether or not the window icon should be hidden from the topbar".
Some one who is a native speaker can probably find a better sentence...

Also, it is not clear what a taskbar is.
- Is it the dock (on mac)?
- Is it the app's bar at the top of the window?
- Is it the bar at the top of the screen where the tray icons are placed (on mac)?

**Comment by FabianLars** [comment]
> Also, it is not clear what a taskbar is. [...]

This setting has no effect on macOS.

About the issue itself, i agree that it needs a better wording and i actually thought we changed it for 1.2 😅

**Comment by boguz** [comment]
> This setting has no effect on macOS.

Oh, that should probably also be in the documentation. Not sure where, but maybe even on the table itself, like:

| Name | Type | Default | Description | Platforms |
|:---------:|:-------:|:-----:|:-------------:|:-----------:|
|skipTaskbar| boolean | false | Hide the icon on the taskbar | 🪟🐧 |

(maybe with icons for the different platforms, like my window and penguin! 😝
