### ISSUE TITLE
[bug] pick_file crashed in macos

### ISSUE THREAD

**Issue by richerfu** [tauri-apps/tauri#5607]
### Describe the bug

```rust
#[tauri::command]
pub fn import_data() {
    let file_path_buf = dialog::blocking::FileDialogBuilder::new()
        .add_filter("JSON", &["json"])
        .pick_file()
        .unwrap();
    let file_path = file_path_buf.as_path().to_str().unwrap();
    println!("{}", file_path);
}
```

when i invoke this command,main thread is blocking,and can't find any dialog.
And if using `dialog::FileDialogBuilder` worked,but i just want to use `sync` method.

### Platform and versions

Environment
  › OS: Mac OS 12.5.1 X64
  › Node.js: 16.7.0
  › npm: 7.20.3
  › pnpm: 7.13.2
  › yarn: 1.22.18
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.2.0
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.0,
  › tauri-build [RUST]: 1.2.0,
  › tao [RUST]: 0.15.3,
  › wry [RUST]: 0.22.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  ├─ .idea
  └─ src

**Comment by FabianLars** [comment]
You must make the command async (`pub async fn` or `#[command(async)]`) to make the blocking dialog work.
We probably should make the wording in the docs a bit more aggressive since we're dealing with platform limitations here.

**Comment by richerfu** [comment]
I think exmaple code should be updated. Thanks
<img width="620" alt="图片" src="https://user-images.githubusercontent.com/32590310/201287353-0f3a2104-ba81-403c-8fe0-8978b14a742b.png">

**Comment by FabianLars** [comment]
Oh yeah, good call!
