### ISSUE TITLE
[bug] Closing the window does not kill the process on Windows

### ISSUE THREAD

**Issue by Sytten** [tauri-apps/tauri#5611]
### Describe the bug

This might be the same issue as https://github.com/tauri-apps/tauri/issues/5397, but we do it differently.
When our application starts, we have a first webview to connect. Closing this windows correctly kills the application.
![Capture](https://user-images.githubusercontent.com/2366731/201390550-e3932d6f-74dd-443e-942a-98fd2a2e11b7.PNG)

When then open a second webview from rust when the user connects to an instance:
![Capture](https://user-images.githubusercontent.com/2366731/201390827-8e895dbe-335d-4d15-901c-31262bf57352.PNG)

At that point, closing the window will not kill the application, just the webview processes will be killed.
![Capture](https://user-images.githubusercontent.com/2366731/201391048-0f50aa2f-1117-4d91-b475-09c82e675936.PNG)

The sidecar process and the main application remain zombie processes in the `Background processes` section of the Task manager.

### Reproduction

1. Start a tauri application
2. Create a new window from rust using the `WindowBuilder`
3. Try to close this new window
4. Observe that the application is still alive

### Platform and versions

```
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 107.0.1418.35
  › MSVC:
  › Node.js: 16.17.1
  › npm: 8.15.0
  › pnpm: 7.12.2
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.2.0
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: git+https://github.com/caido/dependency-tauri?branch=caido#f73dc6487fa9e5ca8f60b092d31ea7f5d8a7a24b (1.2.0),
  › tauri-build [RUST]: git+https://github.com/caido/dependency-tauri?branch=caido#f73dc6487fa9e5ca8f60b092d31ea7f5d8a7a24b (1.2.0),
  › tao [RUST]: 0.15.3,
  › wry [RUST]: 0.22.0,

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  › distDir: ../caido-ui/dist
  › devPath: http://localhost:10000/
package.json not found

App directory structure
  ├─ .git
  ├─ .github
  ├─ caido-tauri
  └─ caido-ui
```

**Comment by amrbashir** [comment]
Can you provide a minimal reproduction repo please?

**Comment by Sytten** [comment]
For now I patched it with:
```rust
RunEvent::WindowEvent { label, event, .. } => {
            // PATCH: Until https://github.com/tauri-apps/tauri/issues/5611
            match event {
                WindowEvent::Destroyed => {
                    if label == MainWindow::label() {
                        #[cfg(target_os = "windows")]
                        app_handle.exit(0);
                    }
                }
                _ => (),
            }
        }
```

It looks like the event `ExitRequested` is just never triggered.

**Comment by amrbashir** [comment]
All works fine for me, that's why I need a reproduction so I can investigate further.

**Comment by Sytten** [comment]
Working on it, will push it today!

**Comment by Sytten** [comment]
@amrbashir Here it is https://github.com/caido/repro-tauri, it is only a problem on windows. Let me know if you have trouble with it :)
I know that in theory the first window is still alive, just hidden but on other platforms it still closes the application.
So it might be a won't fix, but it should be documented somewhere if that is the case.

**Comment by amrbashir** [comment]
This is the expected behavior, if there is at least one window open even if it is hidden, the app won't close.

You say that the app does close on other platforms even there is a hidden window open, which platforms? does it happen with this same reproduction?

**Comment by Sytten** [comment]
Make sense, I realized we didnt close the window while doing the repro.
Yeah on macos and linux (need to double check) it still closes the application correctly. Same reproduction

**Comment by amrbashir** [comment]
I won't be able to test on macOS but I will test it on Linux in 2~3 days if you haven't gotten to it.

**Comment by amrbashir** [comment]
Finally managed to revive my linux installation and tested out the repro and it works exactly the same as Windows (the expected behaviour). Let me know if you still have the issue on macOS.

**Comment by Sytten** [comment]
All good, we also tested on Linux and it was the same as windows. It looks like only macos worked correctly because of the cmd+q. But we fixed it by properly closing windows. Moral of the story is close windows dont hide them.
