### ISSUE TITLE
[feat] add ability to use specific path APIs in allowlist 

### ISSUE THREAD

**Issue by ParthJadhav** [tauri-apps/tauri#5613]
```json
"allowlist": {
      "path": {
        "appDataDir": true,
        "join": true,
        "resolveResource": true
      }
}
```

doing this gives warning saying `property _ is not allowed` for all of them.

```json
"allowlist": {
      "fs": {
        "all": true, // enable all FS APIs
        "readFile": true,
        "writeFile": true,
        "readDir": true,
        "copyFile": true,
        "createDir": true,
        "removeDir": true,
        "removeFile": true,
        "renameFile": true,
        "exists": true
      }
    }
```

But this works with `fs` ...

**Comment by amrbashir** [comment]
the `path` allow list can either be [enabled or disabled](https://tauri.app/v1/api/config#pathallowlistconfig.all), it doesn't have an option for each function. Is there a reason why you want this?

**Comment by ParthJadhav** [comment]
Just for optimisation purposes and reducing bundle size. Ik it won't matter much but having

`"all": true`

might signify that there is a option to set specific API's to be enabled when In fact there is not.
