### ISSUE TITLE
[bug] Vue JS | Settings component on create new WebviewWindow shows the component as Text

### ISSUE THREAD

**Issue by sbesic-starke** [tauri-apps/tauri#5614]
### Describe the bug

When I try to set the window directly on creation to a component from the directory, it returns text instead.

`const webview = new WebviewWindow('app-window', {
      url: '/src/components/Sections.vue'
    });`

`./` loads the App.vue fine...

![example err](https://user-images.githubusercontent.com/85228620/201468463-3884c71a-3428-4842-bb36-7e355912da7e.PNG)

### Expected behavior

A component from the app directory should get loaded into the WebView window at creation correctly.

### Platform and versions

No errors given.

**Comment by amrbashir** [comment]
You need to use a router like `vue-router` and point the new window to the route path not the component.
