### ISSUE TITLE
[docs] Feedback for Updater (UNDOCUMENTED BEHAVIOUR)

### ISSUE THREAD

**Issue by elibroftw** [tauri-apps/tauri#5616]
I've spent probably 6+ hours just to implement the updater feature....on localhost. When providing a domain link, it does not work!
It's not straight forward at all and it's impossible to debug given the docs. Here are some improvements the [Updater page](https://tauri.app/v1/guides/distribution/updater) requires.

- Move private-public key generation under Configuration
- GitHub action example should include commented out code which sets the environment variables for the updater from secrets 
- Tell developers if any APIs under the allowlist need to be enabled if the updater dialog is true in the tauri config file
- Explain or give sample values for `{{target}}` and `{{current_version}}` as well as what other variables can be interpolated
- What is the pre-defined timeout?
- "It may also include other identifying criteria, such as operating system version, to allow the server to deliver as fine-grained an update as you would like." Are these just suggestions for raw string, or is this eluding that there are other {{ DYNAMIC VARIABLES }}
- "Your update request must at least include a version identifier so that the server can determine whether an update for this specific version is required." Include in the docs that this requirement is not enforced in case someone wants to hard code the version
- Under server support, docs should tell developer why to return 204 if no update is available, short-circuit?
  - Currently it is ambiguous and someone like me can assume Tauri does not do a version comparison
  - Update file JSON Format
    - Will tauri try parsing in this format if the previous format fails? Answer: yes
    - Is it necessary for this format to be a file or is a json response fine (response to previous question should answer this one too). Answer: a json response works here
    - Version in this format starts with a v, let users know the v prefix is optional.

Include server-side example/boilerplate on how to create release/update responses automatically.
I have an example here: https://github.com/elibroftw/website/blob/master/blueprints/tauri_releases.py.

It would also be informative to developers on why signing is required, how it works, and what signing can guarantee against. It is my opinion that without a private key, any third party cannot

**Comment by sinistersnare** [comment]
Along with this, it would be great to have an accompanying `{{ arch }}` to `{{ target }}`, such that `{{ target }}-{{ arch }}` would mirror the requested double. Right now, theres no way to tell if the `darwin` being requested is for `aarch64` or for `x86_64`.

edit: There actually _is_ `{{ arch }}` its just not documented on that page... Its [here on the configuration docs](https://tauri.app/v1/api/config/#updaterconfig.endpoints)
