### ISSUE TITLE
[feat]  remove localStorage and network cache directory, how to delete them

### ISSUE THREAD

**Issue by cheng990629** [tauri-apps/tauri#5617]
### Describe the problem

where is localStorage and network cache directory, how to delete them

### Describe the solution you'd like

remove localStorage and network cache directory, how to delete them

**Comment by amrbashir** [comment]
Webview data is usually stored in https://tauri.app/v1/api/js/path/#applocaldatadir

**Comment by cheng990629** [comment]
no such file or directory, woking for “dev “
<img width="741" alt="image" src="https://user-images.githubusercontent.com/40415260/201998385-672a76f9-b9ae-4aab-8f99-b9dc5f714c11.png">

<img width="522" alt="image" src="https://user-images.githubusercontent.com/40415260/201998473-2f99fda6-7284-4b8c-a2a8-c5ebe81dfc45.png">

> Webview data is usually stored in https://tauri.app/v1/api/js/path/#applocaldatadir

**Comment by amrbashir** [comment]
I see you're on macOS so it will probably be stored in `/Users/your-username/Library/WebKit/your.package.id`

**Comment by cheng990629** [comment]
> I see you're on macOS so it will probably be stored in `/Users/your-username/Library/WebKit/your.package.id`

thanks , windows or linux?

**Comment by amrbashir** [comment]
on Windows and Linux, it will be in [tauri.app/v1/api/js/path/#applocaldatadir](https://tauri.app/v1/api/js/path/#applocaldatadir) and macOS should be in `/Users/your-username/Library/WebKit/your.package.id` but I don't have a macOS so I can't confirm

**Comment by cheng990629** [comment]
thx

> on Windows and Linux, it will be in [tauri.app/v1/api/js/path/#applocaldatadir](https://tauri.app/v1/api/js/path/#applocaldatadir) and macOS should be in `/Users/your-username/Library/WebKit/your.package.id` but I don't have a macOS so I can't confirm

**Comment by cheng990629** [comment]
> applocaldatadir

on Windows  runtime, can't remove “applocaldatadir”,how to remove cache?

**Comment by FabianLars** [comment]
> on Windows runtime, can't remove “applocaldatadir”,how to remove cache?

The full path is `appLocalDataDir/bundle-identifier/EBWebView/`, so for example it could look like this: `C:/Users/FabianLars/AppData/Local/de.fabianlars.appname/EBWebView/`

**Comment by cayweb778** [comment]
i found them,but Window is Running,They cannot be deleted

**Comment by cheng990629** [comment]
> > on Windows runtime, can't remove “applocaldatadir”,how to remove cache?
> 
> The full path is `appLocalDataDir/bundle-identifier/EBWebView/`, so for example it could look like this: `C:/Users/FabianLars/AppData/Local/de.fabianlars.appname/EBWebView/`

i found them,but Window is Running,They cannot be deleted
