### ISSUE TITLE
[bug] appWindow.setFocus not working

### ISSUE THREAD

**Issue by guilhermeg2k** [tauri-apps/tauri#5620]
### Describe the bug

I'm very new to tauri hope i'm not doing something dumb, but basically appWindow.setFocus is not working.
I have a very simple function `toggleWindow` that is registered to run when i press a shortcut, but the window doesn't not even get bringed to the front and if i use appWindow.setAlwaysOnTop(true) the window doesn't get focus.

```jsx
import {
  isRegistered,
  register,
  unregister,
} from '@tauri-apps/api/globalShortcut';
import { open } from '@tauri-apps/api/shell';
import { appWindow, LogicalSize } from '@tauri-apps/api/window';
import { useRef, useState } from 'react';
import './App.css';

const toggleWindow = async () => {
  const isWindowOpen = await appWindow.isVisible();
  if (isWindowOpen) {
    await appWindow.hide();
  } else {
    await appWindow.show();
    await appWindow.setFocus();
  }
};

const init = async () => {
  await appWindow.setSize(new LogicalSize(800, 200));
  await unregister('CmdOrControl+Shift+Space');
  try {
    const isShortkeyAlreadyRegistered = await isRegistered(
      'CmdOrControl+Shift+Space'
    );
    if (!isShortkeyAlreadyRegistered) {
      await register('CmdOrControl+Shift+Space', () => toggleWindow());
    }
  } catch (error) {
    console.log(error);
  }
};

init();

function App() {
  const [searchText, setSearchText] = useState('');
  const input = useRef(null);

  return (
    <form className="container">
      <input
        type="text"
        name="teste"
        ref={input}
        id="teste"
        onChange={(event) => setSearchText(event.target.value)}
        autoFocus
      />
      <button
        onClick={async () => {
          await open(`https://www.google.com/search?q=${searchText}`);
        }}
      >
        Search on google
      </button>
    </form>
  );
}

export default App;
```
![Peek 2022-11-14 01-34](https://user-images.githubusercontent.com/42427831/201576233-72ee94e3-63aa-4690-b21a-66b038d8ab8d.gif)

### Platform and versions

Environment
  › OS: Fedora 36.0.0 X64
  ›Window System: X11
  › Node.js: 16.14.0
  › npm: 8.11.0
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.0
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.0,
  › tauri-build [RUST]: 1.2.0,
  › tao [RUST]: 0.15.3,
  › wry [RUST]: 0.22.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React

App directory structure
  ├─ node_modules
  ├─ src-tauri
  ├─ public
  ├─ dist
  ├─ .vscode
  └─ src

### Additional context

The app was created using `npm create tauri-app` for vite.

**Comment by amrbashir** [comment]
On linux, there is no guarantee that focusing will work because the window manager could simply choose to ignore the focus request.

**Comment by amrbashir** [comment]
adding this here for reference: https://developer.pidgin.im/ticket/5521

**Comment by boguszj** [comment]
In case someone stumbles across this looking for a solution: a VERY hacky way to go around that might be to use for example `wmctrl`:
```
if env::consts::OS == "linux" {
   Command::new("/bin/wmctrl")
      .args(["-a", "<sth>"])
      .output()
      .expect("Failed to set focus");
}
```
This a bad way to solve this problem, but for my use case it is good enough for now, and maybe that will be the case for someone else.

**Comment by sec-researcher** [comment]
You can hide the window and then show it to bring the window on screen. I test it on Ubuntu 22.02:
```
window.hide().unwrap();
window.show().unwrap();
```

**Comment by yuezk** [comment]
> You can hide the window and then show it to bring the window on screen. I test it on Ubuntu 22.02:
> 
> ```
> window.hide().unwrap();
> window.show().unwrap();
> ```

This does the magic on Ubuntu Gnome. I used `wmctrl` as the workaround on KDE with X11
