### ISSUE TITLE
[bug] There will be a warning when the installation package is installed on win11, but it does not affect the use

### ISSUE THREAD

**Issue by TheBlindM** [tauri-apps/tauri#5621]
### Describe the bug

![image](https://user-images.githubusercontent.com/48701152/201612919-c7bc5ad3-dfb3-4e3d-9de7-20d7b42e6fcd.png)

### Platform and versions

Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 107.0.1418.42
  › MSVC:
      - Visual Studio Community 2019
  › Node.js: 16.13.2
  › npm: 8.1.2
  › pnpm: 7.9.5
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.5 (outdated, latest: 1.2.0)
  › @tauri-apps/api [NPM]: 1.1.0 (outdated, latest: 1.2.0)
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App                                
  › build-type: bundle             
  › CSP: unset                     
  › distDir: ../dist               
  › devPath: http://localhost:3200/
  › framework: Vue.js              
  › bundler: Rollup                
                                   
App directory structure            
  ├─ .husky                        
  ├─ .idea
  ├─ build
  ├─ dist                          
  ├─ mock                          
  ├─ node_modules                  
  ├─ public                        
  ├─ src                           
  ├─ src-tauri                     
  └─ ~

**Comment by amrbashir** [comment]
Can you upload this installer, and a minimal repro if possible.

**Comment by FabianLars** [comment]
Looks like the bundle identifier was used for multiple apps?

**Comment by TheBlindM** [comment]
> Looks like the bundle identifier was used for multiple apps?



> Can you upload this installer, and a minimal repro if possible.

https://github.com/TheBlindM/T-Shell

```
{
  "$schema": "../node_modules/@tauri-apps/cli/schema.json",
  "build": {
    "beforeBuildCommand": "",
    "beforeDevCommand": "cross-env VITE_SERVICE_ENV=dev vite",
    "devPath": "http://localhost:3200",
    "distDir": "../dist"
  },
  "package": {
    "productName": "T-Shell",
    "version": "0.3.0"
  },
  "tauri": {
    "allowlist": {
      "all": true,
			"shell": {
				"all": false,
				"execute": true,
				"sidecar": true,
				"scope": [
					{ "name": "server", "sidecar": true }
				]
			}
		},
    "bundle": {
      "active": true,
      "category": "DeveloperTool",
      "copyright": "",
      "deb": {
        "depends": []
      },
      "externalBin": ["server"],
      "icon": [
        "icons/shell32x32.png",
        "icons/shell128x128.png",
        "icons/shell-icon.icns",
        "icons/shell-icon.ico"
      ],
      "identifier": "TheBlind",
      "longDescription": "T-Shell",
      "macOS": {
        "entitlements": null,
        "exceptionDomain": "",
        "frameworks": [],
        "providerShortName": null,
        "signingIdentity": null
      },
      "resources": [],
      "shortDescription": "",
      "targets": "all",
      "windows": {
				"webviewInstallMode": {
					"type": "downloadBootstrapper"
				},
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "security": {
      "csp": null
    },
    "updater": {
      "active": true,
			"dialog": true,
			"endpoints": [
				"https://raw.githubusercontent.com/TheBlindM/tshell-update-info/main/update.json"
			],
			"pubkey": "dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IDU3MjMwOEZGN0MyRTlEREMKUldUY25TNTgvd2dqVitsR0NPK2p5U0hKYmJTRk5JUmQ1aENuYjVNN2poTGpNWDVOSjJiQ1BEeHEK"
    },
    "windows": [
      {
        "fullscreen": false,
        "height": 700,
        "resizable": true,
        "title": "T-Shell",
        "width": 1200,
				"minWidth": 1000,
				"minHeight": 700
			}
    ]
  }
}

```

**Comment by amrbashir** [comment]
Works fine for me but looking at your tauri.conf.json, I think @FabianLars is right, you maybe using the same identifier for multiple apps.

>      "identifier": "TheBlind",

you should probably change that to `     "identifier": "com.TheBlind.tshell"`
