### ISSUE TITLE
[bug] Tauri not building an app on Linux Ubuntu 18.04 due to dependency mismatch

### ISSUE THREAD

**Issue by spector32** [tauri-apps/tauri#5625]
### Describe the bug

I am using Ubuntu version 18.04 which has `libwebkit2gtk-4.0` version 2.32.4 and there's no way to securely update that. Only newer versions of Ubuntu have the required `webkit2gtk-4.0 >= 2.36`.

### Reproduction

1.Try building app on Linux Ubuntu version 18.04

### Expected behavior

I expect it to build without any errors. 

### Platform and versions

yarn tauri info                                                                                                                                                      (101) (*main+1) 13:48:09 
yarn run v1.22.19
$ tauri info

Environment
  › OS: Ubuntu 18.04 X64
  › Node.js: 16.17.0
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.2.0
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.0,
  › tauri-build [RUST]: 1.2.0,
  › tao [RUST]: 0.15.3,
  › wry [RUST]: 0.22.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React (Next.js)
  › bundler: Webpack

App directory structure
  ├─ .vscode
  ├─ .next
  ├─ src
  ├─ node_modules
  └─ src-tauri
Done in 10.37s.

### Stack trace

```shell
$ yarn tauri dev                                                                                                                                                       (130) (*main+1) 13:47:57 
yarn run v1.22.19
$ tauri dev
     Running BeforeDevCommand (`yarn dev`)
$ next dev -p 1420
ready - started server on 0.0.0.0:1420, url: http://localhost:1420
        Info Watching /var/apps/desktop/src-tauri for changes...
   Compiling webkit2gtk-sys v0.18.0
   Compiling tao v0.15.3
   Compiling tauri-runtime v0.12.0
   Compiling thread_local v1.1.4
   Compiling pathdiff v0.2.1
   Compiling fastrand v1.8.0
   Compiling remove_dir_all v0.5.3
   Compiling tar v0.4.38
The following warnings were emitted during compilation:

warning: `"pkg-config" "--libs" "--cflags" "webkit2gtk-4.0" "webkit2gtk-4.0 >= 2.36"` did not exit successfully: exit status: 1

error: failed to run custom build command for `webkit2gtk-sys v0.18.0`

Caused by:
  process didn't exit successfully: `/var/apps/desktop/src-tauri/target/debug/build/webkit2gtk-sys-de24a0cc7120fb4a/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=WEBKIT2GTK_4.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:warning=`"pkg-config" "--libs" "--cflags" "webkit2gtk-4.0" "webkit2gtk-4.0 >= 2.36"` did not exit successfully: exit status: 1
  error: could not find system library 'webkit2gtk-4.0' required by the 'webkit2gtk-sys' crate

  --- stderr
  Requested 'webkit2gtk-4.0 >= 2.36' but version of WebKitGTK is 2.32.4
  You may find new versions of WebKitGTK at https://webkitgtk.org

warning: build failed, waiting for other jobs to finish...
event - compiled client and server successfully in 800 ms (176 modules)nd, thread_local, tar, pathdiff, tao, remove_dir_all                                                                                      

error Command failed with exit code 101.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by FabianLars** [comment]
Ah damn, that was meant to be behind a feature flag and not enabled for all (even though 2.36 is more than just nice to have)

**Comment by spector32** [comment]
Alright, so I've upgraded to Ubuntu version 22.04. I can't tell that after that it went all smoothly. I had to hold about 10 packages to a certain version with hope that it won't cause me any trouble with some other packages in the future. Anyhow it is now building without any problems. I am somewhat advanced Linux user and with some Googling could resolve all the issues, but I imagine that it could be a showstopper for less advanced Linux users.

I am new to Rust and I've been doing some work on Electron, but I see a great potential in Tauri. You guys are doing a great job bringing this to developers. Hopefully these issues can be easily resolved. I, like many other users, am using Linux on a daily basis as my main operating system. Let me know if I can somehow help with this. Cheers!

**Comment by xueweiwujxw** [comment]
This problem still exists.
I am using Ubuntu 18.04 and tauri-cli version is 1.2.1

**Comment by FabianLars** [comment]
@xueweiwujxw Fixed in <https://github.com/tauri-apps/tauri/pull/5697>, will be available in 1.2.2

**Comment by xueweiwujxw** [comment]
Is there any method that I can do to fix for building now? I need to deploy my app on an Ubuntu 18.04 machine.

> @xueweiwujxw Fixed in #5697, will be available in 1.2.2

**Comment by FabianLars** [comment]
You can use Tauri from git: https://tauri.app/v1/guides/faq#how-can-i-use-unpublished-tauri-changesm or wait a few more hours for us to release the next patch.

**Comment by xueweiwujxw** [comment]
> You can use Tauri from git: https://tauri.app/v1/guides/faq#how-can-i-use-unpublished-tauri-changesm or wait a few more hours for us to release the next patch.

Ok, Thanks a lot.

**Comment by xueweiwujxw** [comment]
I tried this commit https://github.com/tauri-apps/tauri/commit/b490308c8897b893292951754607c2253abbc6e1. and the latest commit.
It still did not work.

**Comment by FabianLars** [comment]
Did you run `cargo update` in your src-tauri dir after changing it to the git dependency?

**Comment by xueweiwujxw** [comment]
I run it directly with `node` at first.
```shell
node /path/to/tauri/tooling/cli/node/tauri.js dev
node /path/to/tauri/tooling/cli/node/tauri.js build
```
Then I try to add `[patch.crates-io]` in Cargo.toml and run `cargo build`. It seems to be right.
