### ISSUE TITLE
[feat] electron-is-dev alternative or workaround

### ISSUE THREAD

**Issue by 2gn** [tauri-apps/tauri#5626]
### Describe the problem

I want to execute `tauri::window::Window::open_devtools()` only when the app is on development ( executed by `yarn tauri dev` or so).

### Describe the solution you'd like

workarounds or similar library for [electron-is-dev](https://www.npmjs.com/package/electron-is-dev)

**Comment by FabianLars** [comment]
On the Rust side you can use Rust's built-in cfg flags, for example like this
```rs
#[cfg(dev)]
window.open_devtools();
```

**Comment by 2gn** [comment]
> On the Rust side you can use Rust's built-in cfg flags, for example like this
> 
> ```rust
> #[cfg(dev)]
> window.open_devtools();
> ```

Thank you! I'll try this

P.S. It worked! tysm!
