### ISSUE TITLE
Webview data is usually stored in https://tauri.app/v1/api/js/path/#applocaldatadir

### ISSUE THREAD

**Issue by cheng990629** [tauri-apps/tauri#5629]
Webview data is usually stored in https://tauri.app/v1/api/js/path/#applocaldatadir

_Originally posted by @amrbashir in https://github.com/tauri-apps/tauri/issues/5617#issuecomment-1313747119_
      
no such file or directory

**Comment by amrbashir** [comment]
Please keep the discussion in the original issue. No need to open a new one.
