### ISSUE TITLE
[feat] MSI Should have an option to add icon to desktop

### ISSUE THREAD

**Issue by elibroftw** [tauri-apps/tauri#5630]
### Describe the problem

Currently, the MSI always adds the icon to the users' desktop without their consent. Whenever I update an app, I do not want their icon re-emerging on my desktop for me to have to obliterate the next time I notice it which is on login the next day.

### Describe the solution you'd like

Like other setups, the default setup that is created should also include an option for if the user really wants an icon to be added to their desktop. The updater Tauri uses is one that simply runs the installer requiring Admin privileges so it's annoying.

### Alternatives considered

Trying to figure out custom WIX my self. It's not worth my priority at the moment since its when my app will be ready for production. Better to create an issue now and if the issue is not resolved by the time I need it fixed, I'll do it myself with a custom integration.

**Comment by amrbashir** [comment]
This is already implemented in the NSIS installer in #4674 but not released yet. We don't have plans to add this in the WiX installer.
