### ISSUE TITLE
[bug] Windows Updated Installer Does not Use Same GUID

### ISSUE THREAD

**Issue by elibroftw** [tauri-apps/tauri#5631]
### Describe the bug

After updating an app, either manually or by using the Tauri Updater, the icon for the app on the Windows taskbar shows up as blank. The icon will always display correctly for the Start Menu shortcut but takes a couple of days to show correctly in the install location (irrelevant as this is based on my memory not hard proof). **FYI, the icon in the taskbar was pinned from the start menu and not the app install location.**

![image](https://user-images.githubusercontent.com/21298211/202012019-c4fc41e9-4e77-4a24-9a09-0ab8791c8c68.png)
![image](https://user-images.githubusercontent.com/21298211/202012130-0ce7accd-a299-40c0-ac3b-3726f210707d.png)

After a couple days, the icon in the install location shows properly (irrelevant):

![image](https://user-images.githubusercontent.com/21298211/202012178-3af3d7cf-45ae-498f-9e77-4412e6eaf603.png)

But the icon of the app pinned to the taskbar remains blank:
![image](https://user-images.githubusercontent.com/21298211/202012261-671c0636-e01a-4aca-ae12-d370333a547e.png)

If I downgrade my app, the icon shows up fine in the taskbar:
![image](https://user-images.githubusercontent.com/21298211/202012753-6f5c1651-7624-4f9a-a309-dfe70e8fce15.png)

After unpinning the app, and pinning it from the app source, the issue is not present

I did some digging; I looked at the icon path for the Start Menu shortcut and the GUID changed after the update!

### Expected behavior

Shortcut icon path should not change between installs which necessitates that the GUID should not change between installs which necessitates that the GUID should not be changed for each installer or version of the app built.

### Platform and versions

Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 107.0.1418.42
  › MSVC: 
      - Visual Studio Community 2022
  › Node.js: 18.12.1
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: 1.22.11       
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.0
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.0,
  › tauri-build [RUST]: 1.2.0,
  › tao [RUST]: 0.15.3,
  › wry [RUST]: 0.22.0,

App
  › framework: React   
  › bundler: Rollup    

App directory structure
  ├─ .git        
  ├─ .github     
  ├─ .idea       
  ├─ assets      
  ├─ build       
  ├─ node_modules
  ├─ public      
  ├─ src
  ├─ src-tauri   
  └─ utils   

### Additional context

This is a double issue. The top level issue is that the shortcut icon pinned to the taskbar is different after installing an update. The root problem is the GUID is changing for each installer built. This is not mentioned under https://tauri.app/v1/guides/building/cross-platform nor is it mentioned at the top of https://tauri.app/v1/guides/building/windows nor does it show up under search 
![image](https://user-images.githubusercontent.com/21298211/202014317-a18f862f-20f9-4629-8a97-882167407b74.png)

Under https://stackoverflow.com/questions/1405100/change-my-component-guid-in-wix/1422121,

> Your updated MSI delivers a new version of MyFile.exe. The location is the same as before, this means the component GUID should not change. It is the same file (identity), just in a different version.

https://stackoverflow.com/a/5834288/7732434

More info if you need it.

**Comment by lucasfernog** [comment]
I'm not sure if a consistent GUID has other implications, but it did not fix the issue to me. A good resource on this was [this issue comment](https://github.com/adobe/brackets/issues/6297#issuecomment-52378526). I'll open a PR changing the RemoveExistingProducts scheduling, which did fix the problem. I also tested to see if resources are kept across updates, which is the case (that can be problematic if we schedule it too late).

**Comment by ChinkyPrinceCarey** [comment]
When using the Tauri inbuilt updater to perform the update, the problem still persists. Specifically, after the update via Tauri, the pinned taskbar icon appears blank

**Comment by rockfactory** [comment]
Hello, I can confirm this is still happening for some of my users with the Updater. 
I'd like to know if it's possible to reopen this issue, or if right now the suggested solution is to change the wix installer like in the linked commits.
Thanks in advanced for the awesome work here!

**Comment by chirok11** [comment]
The icon keeps disappearing after updating the application if the user has pinned the application to the taskbar. Please open and investigate, or give advice.
