### ISSUE TITLE
tauri dev Or tauri build Failed[bug] 

### ISSUE THREAD

**Issue by happymingjieli** [tauri-apps/tauri#5636]
### Describe the bug

After I switch my code branch, I find I cannot run my project. The output as bekow:

![image](https://user-images.githubusercontent.com/49396751/202388532-1d71d167-e780-49a9-81aa-d11517136f1d.png)

### Platform and versions

![image](https://user-images.githubusercontent.com/49396751/202388660-5838c30f-47f6-4e1d-9b0f-23aaa8dc750b.png)

**Comment by FabianLars** [comment]
Looks like you configured `resources` in tauri.conf but something's wrong with the path. Can you share relevant parts of tauri.conf.json and your folder layout? (or your whole project if it's open source)

**Comment by happymingjieli** [comment]
> Looks like you configured `resources` in tauri.conf but something's wrong with the path. Can you share relevant parts of tauri.conf.json and your folder layout? (or your whole project if it's open source)

thanks for your reply so much, it  is solved. The failture reason is that I configured resources in tauri.conf ,but src-tauri/resources is empty. Thank you!
