### ISSUE TITLE
[question] Tauri on Windows,  alwaysOnTop , I hope the window to always be at the top (z-index=0), have set alwaysOnTop to true, it works but window not always at the top, is there a way to do it always at the top?

### ISSUE THREAD

**Issue by larryteal** [tauri-apps/tauri#5638]
A Microsoft inspect tool (inspect.exe) is always at the top, and I want the tauri window to be on top of the inspect window.
Thanks!

**Comment by amrbashir** [comment]
Unfortunately, there is no API to control which window takes precedence over the other. We just tell windows to make this window on top of other Normal windows.
