### ISSUE TITLE
[docs] Legacy Examples Code

### ISSUE THREAD

**Issue by lukethacoder** [tauri-apps/tauri#564]
**Hands On** section on [page 14](https://github.com/tauri-apps/tauri/wiki/14.-Contributor-Introduction) of the repo wiki could be removed or replaced with a link to the new [examples](https://github.com/tauri-apps/examples) repo.

**Comment by Laegel** [comment]
In fact, this page is dedicated to users willing to contribute to Tauri code, not to consumers.
The goal is to use Tauri code (from the repository) in order to dev concurrently with a demo project.
This page may need to be refreshed, though.

**Comment by nothingismagick** [comment]
I think we need to up our game for contributors, generally speaking.

**Comment by lukethacoder** [comment]
@Laegel after looking more into getting up and running with Tauri I understand why the example has been left here in the main repo. Was a tad confusing trying to get the examples [repo](https://github.com/tauri-apps/examples) up and running, but got there eventually.

https://github.com/tauri-apps/examples/issues/5#issuecomment-614686300_
