### ISSUE TITLE
[bug] MenuHandle `get_item` causes locked up app if not spawned on a thread

### ISSUE THREAD

**Issue by tr3ysmith** [tauri-apps/tauri#5645]
### Describe the bug

When trying to get a menu item to modify from the `Window` it causes the window to completely lock up

### Reproduction

Calling the following code causes the WebView Window to lock up and become unresponsive

```rust
let menu = window.menu_handle();
let item = menu.get_item("custom_item"); // Hangs here....
```

Calling the following code works fine

```rust
let menu = window.menu_handle();
std::thread::spawn(move {
    let item = menu.get_item("custom_item"); 
});
```

### Expected behavior

Calling `get_item()` should work without having to spawn it on a thread.

### Platform and versions

Environment
  › OS: Mac OS 12.5.0 X64
  › Node.js: 16.16.0
  › npm: 8.11.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.0.3,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3010/
  › framework: React

App directory structure
  ├─ .config
  ├─ dist
  ├─ node_modules
  ├─ oci
  ├─ samples
  ├─ public
  ├─ .webpack
  ├─ .github
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  ├─ assets
  └─ src

**Comment by amrbashir** [comment]
Can you give a bit more context, where do you call this function, inside a command or an event? provide a minimal repro if possible.
