### ISSUE TITLE
[bug] Calling file dialog from backend

### ISSUE THREAD

**Issue by XWHtorrentx** [tauri-apps/tauri#5647]
### Describe the bug

I wanted to open a file dialog with then pass a string of path from rust backend to frontend. It worked on Windows but crashed on macOS. I tried some workarounds but they didn't work.  

### Reproduction

1. spawn a new thread
```rs
use tauri::api::dialog::blocking::FileDialogBuilder;
#[tauri::command]
fn select_folder()->String{
    let folder_path = FileDialogBuilder::new().pick_folder();
    folder_path.unwrap().to_string_lossy().to_string()
}
```
This works perfect on windows platform, but crashed right before the file dialog shows up on macOS
.

2.on main thread
```rs
use std::sync::{Arc, Mutex};
use tauri::api::dialog::FileDialogBuilder;
#[tauri::command]
fn select_folder()->String{
    let path_string=Arc::new(Mutex::new(String::new()));
    let cloned_path_string = path_string.clone();
    let dialog = FileDialogBuilder::new();
    let get_path = move |path:Option<PathBuf>| {
        *cloned_path_string.lock().unwrap() = path.unwrap().to_string_lossy().to_string().clone();
    };
    dialog.pick_folder(get_path);
    let x=path_string.lock().unwrap().to_string();
    x
}
```
This works on both platform but I cannot pass string to the frontend.

### Platform and versions

My test platforms are Windows 11 and macOS 13(M1 chip)

**Comment by amrbashir** [comment]
This should work
```rs
use tauri::api::dialog::blocking::FileDialogBuilder;

#[tauri::command]
fn select_folder() -> String{
    let folder_path = FileDialogBuilder::new().pick_folder();
    folder_path.unwrap().to_string_lossy().to_string()
}
```

**Comment by geocine** [comment]
I tried this but I get , any ideas?
```
  |
6 | use tauri::api::dialog::blocking::FileDialogBuilder;
  |                 ^^^^^^ could not find `dialog` in `api`
```

**Comment by FabianLars** [comment]
@geocine you need to configure the allowlist to enable the dialog apis: <https://tauri.app/v1/api/js/dialog> (only the allowlist example is relevant on that page, the rest is JavaScript)

**Comment by geocine** [comment]
Thanks , its working now @FabianLars
