### ISSUE TITLE
[bug] sveltekit-ts doesnj't work

### ISSUE THREAD

**Issue by ralyodio** [tauri-apps/tauri#5648]
### Describe the bug

Uncaught (in promise) TypeError: window.__TAURI_IPC__ is not a function

### Reproduction

npm run dev

just choose npm and sveltekit-ts

### Expected behavior

should greet you.

### Platform and versions

linux, kde 

### Stack trace

```shell
Uncaught (in promise) TypeError: window.__TAURI_IPC__ is not a function
```

**Comment by amrbashir** [comment]
Please provide a minimal repro. `sveltekite-ts` template from create-tauri-app works fine out of the box. The error you have is probably because you are using tauri APIs in Node.js contenxt instead of Client (Browser) context

**Comment by ralyodio** [comment]
I don't know. i just followed the hello worl and it no workie.

**Comment by amrbashir** [comment]
What guide did you follow?

**Comment by ralyodio** [comment]
`sh <(curl https://create.tauri.app/sh)`

**Comment by amrbashir** [comment]
That is `create-tauri-app` and it works fine for me, please provide the repo that has this issue

**Comment by FabianLars** [comment]
You're using the wrong command. `npm run dev` only starts the frontend, to start the tauri app use `npm run tauri dev`

P.S. Tauris apis don't work in the browser which is why you're seeing that error.

**Comment by ralyodio** [comment]
I get the same error with `npm run tauri dev`

```
[vite] connected. [client.ts:134:14](http://localhost:1420/src/client/client.ts)
Uncaught (in promise) TypeError: window.__TAURI_IPC__ is not a function
    c chunk-RCPA6UVN.js:1
    c chunk-RCPA6UVN.js:1
    greet Greet.svelte:9
```

**Comment by ralyodio** [comment]
Actually nevermind it was still building.

Is there a way with tauri to run on a web server? It seems like desktop only right now.
