### ISSUE TITLE
Unable to preserve login data under Ubuntu

### ISSUE THREAD

**Issue by Tlntin** [tauri-apps/tauri#5655]
### Describe the bug

I made a web application with tauri, when I opened the application and logged into the account, I closed the application. When I open the app again, the data is gone and it says login required.
This didn't happen on Windows nor Mac, only on Ubuntu.

### Reproduction

1. compile and install app,[url](https://github.com/Tlntin/Pake)
2.  open app.
3. login account.
4. close app.
5. open app.
6. need login again.

### Platform and versions

$ npm run tauri info

> tauri
> tauri info

Environment
  › OS: Ubuntu 22.04 X64
  › Node.js: 18.12.1
  › npm: 9.1.2
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: Not installed!
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: 

Packages
  › @tauri-apps/cli [NPM]: 1.2.0
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.0,
  › tauri-build [RUST]: 1.2.0,
  › tao [RUST]: no manifest (0.14.0, 0.15.2),
  › wry [RUST]: 0.21.1 (0.21.1, 0.22.0),

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: ../dist

App directory structure
  ├─ node_modules
  ├─ output
  ├─ src-tauri
  ├─ .github
  ├─ .vscode
  ├─ dist
  └─ .git

**Comment by amrbashir** [comment]
Can't reproduce, can you make a minimal repro (not a full app)?

**Comment by Tlntin** [comment]
> Can't reproduce, can you make a minimal repro (not a full app)?

yuque:  https://www.yuque.com/
[com-tw93-yuque.zip](https://github.com/tauri-apps/tauri/files/10084409/com-tw93-yuque.zip)

twitter https://twitter.com/
[com-tw93-twitter.zip](https://github.com/tauri-apps/tauri/files/10084412/com-tw93-twitter.zip)

youtube https://youtube.com
[com-tw93-youtube.zip](https://github.com/tauri-apps/tauri/files/10084418/com-tw93-youtube.zip)

**Comment by amrbashir** [comment]
I just took a look at your repo and apparently you have a tauri app structure but you're using WRY directly and not tauri and in that case you need create a web context https://docs.rs/wry/latest/wry/webview/struct.WebContext.html#method.new and pass it to the `wry::WebviewBuilder`. If you are using Tauri, this is automatically handled for you.

**Comment by Tlntin** [comment]
Thank you, I will try it.

**Comment by amrbashir** [comment]
I forgot to mention that you need to specify a directory when creating the context, otherwise won't work.

**Comment by Tlntin** [comment]
OK.

**Comment by Tlntin** [comment]
> I forgot to mention that you need to specify a directory when creating the context, otherwise won't work.

Thank you again. It work well !
