### ISSUE TITLE
[feat] Events. Window Z order change event is needed. 

### ISSUE THREAD

**Issue by larryteal** [tauri-apps/tauri#5656]
### Describe the problem

1. Scene 1, a screenshot tool. There is a mask window, and it needs to be on top as much as possible, the "alwaysOnTop" setting works, but it's not enough, because I came across a microsoft tool software "inspect.exe", which also set "alwaysOnTop", And it will always occupy the top layer without releasing it. I hope to achieve such an effect, let my mask window occupy the top layer and not release it.
I found some information. To achieve this effect, it may be necessary to monitor the Z order change message after "alwaysOnTop" obtains the top position. When other windows are activated to occupy the top window position, discard that message and keep your own Z order unchanged. .

2, scene two, a dynamic desktop background. It is necessary to set the window at the bottom, and then play a dynamic video in a loop.

Maybe there is a better way of doing it, I would appreciate some help, I am new to Tauri, thanks a lot!

win32 API:
The message "WM_WINDOWPOSCHANGING" when the Z order is about to change;
The "SetWindowPos" function can modify the Z order of the window;

https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowpos
https://learn.microsoft.com/en-us/windows/win32/winmsg/wm-windowposchanging?source=recommendations

### Describe the solution you'd like

Add a callback function for window event messages, like WindowProc in Win32 api.

https://learn.microsoft.com/en-us/windows/win32/api/winuser/nc-winuser-wndproc

**Comment by amrbashir** [comment]
This is going to be hard to pull-off in a cross-platform way and it seems a pretty rare-case so what you can do is, [subclass the Window](https://learn.microsoft.com/en-us/windows/win32/api/commctrl/nf-commctrl-setwindowsubclass) and in the subclass procedure, listen to `WM_WINDOWPOSCHANGING` and modify `hwndInsertAfter` of the `WINDOWPOS` which the `wparam` points to.
