### ISSUE TITLE
tauri dev layout != tauri build layout (windows build)

### ISSUE THREAD

**Issue by sweatben** [tauri-apps/tauri#5671]
### Describe the bug

Hi there.

first tauri seems to me a great and powerful tool, thank you in advance for your help.

I have an expo project for which I added tauri.

I get a layout mismatch when building.

Do you have any idea how to quickly solve this annoying problem?

-1-tauri dev
-2-tauri build
![tauri_dev](https://user-images.githubusercontent.com/49415544/203311923-69639e92-ee1f-433a-98e9-06e0aefb6a39.png)

![tauri_build](https://user-images.githubusercontent.com/49415544/203311919-d86366f1-8a41-4c0e-a3c4-014b1b800368.png)

### Reproduction

project expo + tauri + background image + any stylized form (react native style)

When initiating an expo -tauri project redefining the style as follows works:

react native style app.js:
```
flex: 1,
backgroundColor: '#ffff'',
overflow: 'hidden',
justifyContent:'center',
alignItems:'center'
```
add style for tauri :
```
display: 'flex',
flexDirection: 'column',
width: '100vw',
height: '100vh'
```

but with nested components it's another story.

Am I doing something wrong  ? or is there a faster and less difficult way than redoing all the styles for each component

knowing that the only way to know if the style applied gives the right result is to rebuild systematically.

### Expected behavior

I expect to have tauri dev layout = tauri build layout
or
be able to redo styles without having to constantly build.

### Platform and versions

Environment
  › OS: Windows 10.0.19045 X64
  › Webview2: 107.0.1418.52
  › MSVC: 
      - Visual Studio Build Tools 2022
  › Node.js: 16.15.0
  › npm: 8.11.0
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.0
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.0,
  › tauri-build [RUST]: 1.2.0,
  › tao [RUST]: 0.15.6,
  › wry [RUST]: 0.22.3,

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  › devPath: http://localhost:19006/
  › framework: React
  › bundler: Webpack

App directory structure
  ├─ .expo-shared
  ├─ .git
  ├─ .vscode
  ├─ assets
  ├─ node_modules
  ├─ src
  ├─ src-tauri
  └─ web-build

      @expo/webpack-config: ^0.16.25 => 0.16.27
      expo: ^45.0.6 => 45.0.6
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7

**Comment by FabianLars** [comment]
The problem is likely your CSP which is not loaded on development. It probably prevents some script from loading.

You can try building a debug build `npm run tauri build -- --debug` (output in `target/debug/` ! ) or enable the devtools for release builds by adding the `"devtools"` feature flag to the tauri dependency in Cargo.toml. Then you can check the devtools console and network tab for errors

**Comment by sweatben** [comment]
thx 👍 

change csp to null solve problem

tauri.config.json

```
  "tauri": {
    "security": {
      "csp": null
    }
```
