### ISSUE TITLE
[bug] Appimage seems have permission problem

### ISSUE THREAD

**Issue by Hellager** [tauri-apps/tauri#5672]
### Describe the bug

Build an tauri app on Ubuntu 20.04, perfectly run with .deb file or in dev mode.
However when it comes to the .appimage, if there's some code try create a file will lead to this error
 `Os {code: 30, kind: ReadOnlyFilesystem, message: "Read-only file system"}`
Even using root permission to run it,  will still have the same error.

### Reproduction

1. create a template with `pnpm create tauri-app`
2. add some test code to main.rs
```
use std::fs::File;
use std::io::prelude::*;

fn main() {
  let mut file = File::create("config.ini").unwrap();
  file.write_all(b"Hello, world!").unwrap();

  tauri::Builder........
}
```
3. build and run .AppImage file

### Expected behavior

Should be ok like what .deb file does.

### Platform and versions

Environment
  › OS: Ubuntu 20.04 X64
  › Node.js: 18.12.1
  › npm: 8.19.2
  › pnpm: 7.16.1
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.0
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.0,
  › tauri-build [RUST]: 1.2.0,
  › tao [RUST]: 0.15.6,
  › wry [RUST]: 0.22.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Vue.js

App directory structure
  ├─ src-tauri
  ├─ node_modules
  ├─ .vscode
  ├─ src
  ├─ public
  └─ dist

**Comment by lucasfernog** [comment]
What's the path of the file you're trying to write? If it's relative to the binary, I believe it won't work since the binary is mounted to a read-only filesystem. So you'd need to use the [path APIs](https://tauri.app/v1/api/js/path) or the [BaseDirectory](https://tauri.app/v1/api/js/fs#basedirectory).

EDIT: ah I just see you shared the code, so yes you need to use the [Rust path module](https://docs.rs/tauri/latest/tauri/api/path/index.html).

**Comment by FabianLars** [comment]
There's also a `OWD` env var set (only in appimages) which contains the path of the `.AppImage` file (not the mounted location) - but be careful with that because it could be in a read-only location too, depending on where the user saved it.

**Comment by Hellager** [comment]
> What's the path of the file you're trying to write? If it's relative to the binary, I believe it won't work since the binary is mounted to a read-only filesystem. So you'd need to use the [path APIs](https://tauri.app/v1/api/js/path) or the [BaseDirectory](https://tauri.app/v1/api/js/fs#basedirectory).
> 
> EDIT: ah I just see you shared the code, so yes you need to use the [Rust path module](https://docs.rs/tauri/latest/tauri/api/path/index.html).

Do you mean that for AppImage, all given path should be in absolute format?
Because this is not a problem for .deb, win and mac.

**Comment by FabianLars** [comment]
> Do you mean that for AppImage, all given path should be in absolute format?

Yes

> Because this is not a problem for .deb, win and mac.

It actually is! Both .deb (linux) and .msi (windows) install the app to read-only locations. I think it was similar on macOS, not sure.

**Comment by Hellager** [comment]
Got it. Thanks for your help!
