### ISSUE TITLE
[bug] Sidecar command works when referenced directly but not through Sidecar itself

### ISSUE THREAD

**Issue by kennethnym** [tauri-apps/tauri#5674]
### Describe the bug

I am trying to integrate `esbuild` binary into my app, and I ran into this weird issue that prevents me from executing the binary through Sidecar. When trying to run the Sidecar command using the following snippet:

```json
{
  "shell": {
    "sidecar": true,
    "scope": [
      {
        "name": "bin/esbuild",
        "sidecar": true
      }
    ]
  },
  "bundle": {
    "externalBin": [
      "bin/esbuild"
    ]
  }
}
```

```js
// main.js is some script that I wish to bundle through esbuild
const cmd = Command.sidecar("bin/esbuild", ["main.js"], {
  cwd: await join(await tempdir(), "sidecar-bug-123456")
});
const output = await cmd.execute()
console.log('output', output)
```

The output will never get logged, presumably because the `Promise` returned from `execute` never resolves. If I try to call `spawn` instead of `execute`, `stdout` and `stderr` will returning nothing, and the `"close"` event never happens.

However, if I try to run the binary directly by registering the absolute path of the binary in `tauri.conf.json` as such:

```json
{
  "name": "not-sidecar",
  "cmd": "/absolute/path/project/src-tauri/bin/esbuild-aarch64-apple-darwin",
  "args": [
    "main.js"
  ]
}
```

and calling the command as such:

```js
const cmd = new Command("not-sidecar", [], {
  cwd: await join(await tempdir(), "sidecar-bug-123456")
})
const output = await cmd.execute()
console.log('output', output)
```

the output gets logged appropriately in the browser console.

The binary is downloaded directly from [esbuild's website](https://esbuild.github.io/getting-started/#download-a-build). I have verified that the binary is working correctly by:

1. running the command directly in the terminal; and
2. running the command through Nodejs.

This is the code snippet I used to test the esbuild binary in Node.js:

```js
// cwd is the same as above
exec('/absolute/path/project/src-tauri/bin/esbuild-aarch64-apple-darwin main.js', {
  cwd
}, (err, stdout, stderr) => {
  console.log(err, stdout, stderr)
})
```

As I expected, `err` is null, `stderr` is empty, and `stdout` is the outpu of building `main.js`.

### Reproduction

1. Clone [this repo](https://github.com/kennethnym/sidecar-bug)
2. Download the appropriate esbuild binary [here](https://esbuild.github.io/getting-started/#download-a-build)
3. Move the binary to `sidecar-bug/src-tauri/bin`
4. Rename binary to `esbuild-aarch64-apple-darwin`, or the appropriate triple for your setup.
5. `pnpm i`
6. `pnpm run tauri dev`
7. Click on the greet button
8. Nothing happens
9. Now uncomment the working code
10. Output gets logged correctly

### Expected behavior

I should be able to run the esbuild binary through Sidecar and get the correct build output from it through the `stdout` property of the object returned by `execute`

### Platform and versions

```
Environment
  › OS: Mac OS 12.6.0 X64
  › Node.js: 18.7.0
  › npm: 8.15.0
  › pnpm: 7.13.4
  › yarn: 1.22.15
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.2.0
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.0,
  › tauri-build [RUST]: 1.2.0,
  › tao [RUST]: 0.15.6,
  › wry [RUST]: 0.22.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../src
  › devPath: ../src

App directory structure
  ├─ node_modules
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  ├─ .idea
  └─ src
```

### Stack trace

```shell
No error message whatsoever is returned from either Tauri or esbuild
```

### Additional context

I originally posted this [disussion](https://github.com/tauri-apps/tauri/discussions/5666) here, expecting that I have probably done something wrong. But upon further investigation, I began to suspect that it is a Tauri specific issue since the binary works in the command line and in Node, and I have registered the external binary in `tauri.conf.json` accordingly.

**Comment by amrbashir** [comment]
you're missing the `args` field, it should be:
```json
{
  "shell": {
    "sidecar": true,
    "scope": [
      {
        "name": "bin/esbuild",
        "sidecar": true,
		"args": [
    	  "main.js"
  		]
      }
    ]
  },
  "bundle": {
    "externalBin": [
      "bin/esbuild"
    ]
  }
}
```

Here is the output without `args` defined:
![image](https://user-images.githubusercontent.com/48618675/203768101-b31fd79a-e941-40b7-a737-5fbf2932eadc.png)


and here it is with `args` defined:
![image](https://user-images.githubusercontent.com/48618675/203768421-33fc3792-1d83-413c-aa09-a18ae65dbbd1.png)

**Comment by kennethnym** [comment]
Ahh right! That makes sense. I think it would be helpful to provide an example in the sidecar docs for calling sidecar commands with arguments. Would you mind if I create a PR for it?

**Comment by amrbashir** [comment]
that would be perfect, thanks
