### ISSUE TITLE
Listen for Mouse Back/Forward buttons

### ISSUE THREAD

**Issue by goenning** [tauri-apps/tauri#5677]
### Describe the problem

it’s not possible to capture the mouse back/forward buttons using event listeners in DOM API. Many people use 5+ button mouse and back/forward is a very popular one.

### Describe the solution you'd like

Electron has support for it, but apparently only Windows and Linux: https://www.electronjs.org/docs/latest/api/browser-window#event-app-command-windows-linux

Would be great to have feature parity with Electron this regard too. Support for macOS would be awesome too.

### Alternatives considered

There’s the rdev crate, but this should be a built-in feature in Tauri for better developer experience.

**Comment by balthild** [comment]
As well as the two finger swipe of touchpad. I want to disable these and force users to stay at the current page unless I redirect them.

**Comment by jclaessens97** [comment]
I would also like to block the two-finger gesture on windows but I don't know how. Someone any idea for a workaround (if it's not already built in?)



edit: found it.

Adding 
```
{
 "additionalBrowserArgs": "--disable-features=msWebOOUI,msPdfOOUI,msSmartScreenProtection,OverscrollHistoryNavigation,msExperimentalScrollin --disable-pinch"
}       
```
 to WindowConfig disables it.

**Comment by amrbashir** [comment]
This is now be implemented in v2-alpha. You can listen for these buttons on JS side and call `event.preventDefault()` if need to block the navigation
