### ISSUE TITLE
How to execute preload script with webview in frontend [feat] 

### ISSUE THREAD

**Issue by Zerounary** [tauri-apps/tauri#5682]
### Describe the problem

I create a runtime window like this
```rust
  let docs_window = tauri::WindowBuilder::new(
    &handle,
    "external", /* the unique window label */
    tauri::WindowUrl::External("https://tauri.app/".parse().unwrap())
  )
  .initialization_script(include_str!("./preload.js"))
  .build().unwrap();
```
Defined a function in `preload.js`
```js
function onPageLaunch(cb) {
  console.log('onPageLaunch');
  cb();
}
``` 
Now I want to call this preload-function in my main window.

```rust
const callWebview = () => {
  let webview = WebviewWindow.getByLabel('external');
  webview?.emit('onPageLaunch', () => {
    console.log('cb');
  });
};
```

but it not work :(

### Describe the solution you'd like

A waring in the console

tauri.app/:1 
        
       The resource https://tauri.app/assets/js/main.a13da785.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
tauri.app/:1 
        
       The resource https://tauri.app/assets/js/runtime~main.6cdae8d1.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally

**Comment by amrbashir** [comment]
the preload script is not listening to the events, so it won't be triggered. Also, you can't send callbacks through events, events are just used to send data.

I am not sure what you want that callback to do tbh but what you need to do instead, is something like this:
`preload.js`:
```js
function onPageLaunch(eventPayload) {
  console.log('onPageLaunch');
  
  // do stuff
  
  // trigger a callback in the main window
  emit("invokeMainCallback")
}

listen('onPageLaunch', (e) => onPageLaunch(e.payload));
```

and you can call this like this: 
```js

listen("invokeMainCallback", (e) => {
	// run callback logic here
});

const callWebview = () => {
  let webview = WebviewWindow.getByLabel('external');
  webview?.emit('onPageLaunch');
};
```

**Comment by Zerounary** [comment]
Thanks. How can I execute some javascript code in a website webview ? For example I create a window with `https://tauri.app/`, then I want to extract dom data from the page.

**Comment by carmel** [comment]
I want to extract dom too, any help?

**Comment by amrbashir** [comment]
@carmel  you can get the dom representation as HTML from `document.outerHTML` and send it to Rust. Actual dom manipulation has to be done through JS.

**Comment by carmel** [comment]
Sounds simple enough, I'll give it a try, thanks!
