### ISSUE TITLE
[bug] invalid characters appearing on the screen when pressing arrow right

### ISSUE THREAD

**Issue by paprikka** [tauri-apps/tauri#5685]
### Describe the bug

Pressing arrow right in an autofocused `<textarea>` will result in adding invalid characters to its content (``)
This happens only initially. If I focus on a different element or window and come back, the `<textarea>` element works as intended. 

### Reproduction

1. on Mac (Ventura) clone the project from this repo: https://github.com/paprikka/tauri-keypress-bug
2. `npm run tauri dev`
3. start typing and press _right_
4. If the caret is at the end of the typed text `` gets appended to it (left, down, up don't cause this issue)
5. change focus to a different window or DOM element
6. change focus back to the texarea
7. type and press _right_
8. now the behaviour is correct

### Expected behavior

Pressing right arrow on the keyboard, when the caret is at the end of the typed text should result in no action.

### Platform and versions

Environment
  › OS: Mac OS 13.0.0 X64
  › Node.js: 18.9.0
  › npm: 8.19.1
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.2.0
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.0,
  › tauri-build [RUST]: 1.2.0,
  › tao [RUST]: 0.15.6,
  › wry [RUST]: 0.22.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../src
  › devPath: ../src

App directory structure
  ├─ node_modules
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  └─ src

### Additional context

I've created a repo demonstrating the issue: https://github.com/paprikka/tauri-keypress-bug
And a video: https://drive.google.com/file/d/1ezFteEHw7TAZc-fpXiXOjh2VArkJJHyA/view?usp=sharing

(Thanks for great work! I've been using hybrid frameworks for +11 years, and I'm enjoying Tauri way more than anything else I've worked on 👌🏼)

**Comment by wusyong** [comment]
Thanks for the report! I think I'll open a patch to fix this real quick.
