### ISSUE TITLE
[bug] Setting tauri.bundle.macOS.entitlements value causes dataDirPath、configDirPath Changed

### ISSUE THREAD

**Issue by BingKui** [tauri-apps/tauri#5688]
### Describe the bug

When I not set `tauri.bundle.macOS.entitlements` value, I run `yarn tauri build` generate app, I get this values;
![image](https://user-images.githubusercontent.com/6781005/203920828-3a3d1f61-8973-4b06-a09a-79fee66c7650.png)

When I set `tauri.bundle.macOS.entitlements` value, I run `yarn tauri build` generate app, I get this values;
![image](https://user-images.githubusercontent.com/6781005/203920925-fb587ae0-da74-4b95-b430-d8008a9db6ca.png)

Why are the paths of generated applications inconsistent

### Platform and versions

> iPluginTest@0.0.1 tauri
> tauri info

Environment
  › OS: Mac OS 13.0.1 X64
  › Node.js: 18.12.1
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.2.0
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.0,
  › tauri-build [RUST]: 1.2.0,
  › tao [RUST]: 0.15.5,
  › wry [RUST]: 0.22.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Vue.js

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .vscode
  └─ src

**Comment by FabianLars** [comment]
I guess your entitlement file enabled the sandbox mode? In this case this path change is expected and necessary.
`~/Library/Containers` is the location of data directories for sandboxed apps (that's just how macos works) and as far as i know, sandboxed apps can't even write to `~/Library/Application Support/`.
