### ISSUE TITLE
[feat] Global float window on top of full-screened apps.

### ISSUE THREAD

**Issue by mozhou-tech** [tauri-apps/tauri#5699]
### Describe the problem

In my senario, the window need to show what ever current window is fullscreen or not.

### Describe the solution you'd like

Global float window on top of full-screened apps, just like sportlight search on macos.

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/14063414/204067668-96e8bbec-3697-4d5b-8720-84914d984788.png">

**Comment by amrbashir** [comment]
see #2801
