### ISSUE TITLE
[bug] This version of %1 is not compatible with the version of Windows you're running

### ISSUE THREAD

**Issue by Pequiz** [tauri-apps/tauri#5702]
### Describe the bug

Hi, I got the error "This version of %1 is not compatible with the version of Windows you're running. The installation was done through create-tauri-app, I didn't do anything in the project myself.

Full Error: `thread '<unnamed>' panicked at called 'Result::unwrap()' on an 'Err' value: Os { code: 216, kind: Uncategorized, message: "This version of %1 is not compatible with the version of Windows you're running." }', src\interface\rust\desktop.rs:47:63`

### Reproduction

1. Created a project via create-tauri-app
2. Run the tauri script with the dev argument
3. After the build, I got an error.

### Platform and versions

Environment
  › OS: Windows 10.0.18362 X64
  › Webview2: 107.0.1418.35
  › MSVC: Visual Studio Build Tools 2022
  › Node.js: 16.17.0
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: 1.22.4
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.1
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.1,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.6,
  › wry [RUST]: 0.22.5,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React

App directory structure
  ├─ .vscode
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri

**Comment by amrbashir** [comment]
did you follow this guide https://tauri.app/v1/guides/getting-started/prerequisites#1-microsoft-visual-studio-c-build-tools ?

**Comment by Pequiz** [comment]
> did you follow this guide https://tauri.app/v1/guides/getting-started/prerequisites#1-microsoft-visual-studio-c-build-tools ?

Yes

**Comment by amrbashir** [comment]
For a good measure try uninstalling webview2 and build tools and reinstall them again. Also make sure to restart Windows afterwards.

**Comment by FabianLars** [comment]
hmm, i wonder if it's related to the old windows 10 version (talking about 18362 not win10 in general)

**Comment by Pequiz** [comment]
> For a good measure try uninstalling webview2 and build tools and reinstall them again. Also make sure to restart Windows afterwards.

Thank you very much! I updated WebView2 and everything worked!

**Comment by Pequiz** [comment]
> hmm, i wonder if it's related to the old windows 10 version (talking about 18362 not win10 in general)

Fortunately no, I just had an old version of WebView2, thank you very much!

**Comment by Fozei** [comment]
> > For a good measure try uninstalling webview2 and build tools and reinstall them again. Also make sure to restart Windows afterwards.
> 
> Thank you very much! I updated WebView2 and everything worked!

I am facing the same problem, I install WebView2 fallowing the instructions from https://tauri.app/v1/guides/getting-started/prerequisites. Now sames I have the latest version of WebView2, but my project not work. In fact, my project works fine in Linux OS.
So what I can do next ? Thanks so much.
```
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 112.0.1722.58
  › MSVC: 
      - Visual Studio 15 ���ɹ��� 2017
  › Node.js: 14.19.3
  › npm: 6.14.17
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.2
  › rustc: 1.69.0
  › cargo: 1.69.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Vue.js
  › bundler: Vite

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ dist
  ├─ docs
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

**Comment by FabianLars** [comment]
@Fozei You must update Visual Studio to 2019 or 2022. 2017 will _not_ work. That's what the error in the issue's title generally means (no idea why OP saw it with the webview2 runtime, that error _should_ look a bit different).

**Comment by Fozei** [comment]
> 

Thanks a lot ! I upgrade to vs2022, restart os, now it works well. Any how, the error message is really confusing. Thanks again.
