### ISSUE TITLE
App only works when running as administrator on Windows 11

### ISSUE THREAD

**Issue by Archieeeeee** [tauri-apps/tauri#5703]
### Describe the bug

I find my app won't start if I do not run it as administrator, but it will work if I choose to install the app to a non system folder (i.e, not c:\Program files or d:\Program files),  this issue only happens recently, probably after an update of Windows 11, I do not know how to fix it

### Platform and versions

Windows 11 version: 22623.891
Windows Feature Experience Pack 1000.22637.1000.0

tauri 1.0.0-beta.8

**Comment by amrbashir** [comment]
Do you see any errors? Are your writing/modifying files under `C:/Program Files` which needs your app to run as administrator to work?

**Comment by Archieeeeee** [comment]
> Do you see any errors? Are your writing/modifying files under `C:/Program Files` which needs your app to run as administrator to work?

Yes the app will write log files to the instllation dir. And after my test, the app works if I do not do that.  I write files to system APPDATA dir instead, thank you.
