### ISSUE TITLE
[bug] PointerLockControls API Compatibility?

### ISSUE THREAD

**Issue by jowi-dev** [tauri-apps/tauri#5707]
### Describe the bug

PointerLockControls seems to throw a pretty straightforward error about the usage of PointerLock with the Tauri ecosystem. I have confirmed this code does work in the chrome browser as well as in an electron app, but would love to switch this engine to Tauri to have a smaller footprint when running. Is there any plans to include the PointerLock API in Tauri? Is this something that would be beneficial if it were added? I have not worked in this repo yet, but would be happy to help contribute to help get this API usable! Any further context I would be happy to add. Thank you for taking the time to review this.

- This is on the latest stable Tauri, installed and run on the latest stable node/npm, on MacOS.

<img width="801" alt="Screen Shot 2022-11-27 at 7 11 06 PM" src="https://user-images.githubusercontent.com/10256122/204167444-95d8c62a-a35e-4b23-8d0a-d6096dc08a23.png">

### Expected behavior

The user's pointer is locked to the current window and the [PointerLock API](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API) is fully functional.
### Platform and versions

<img width="508" alt="Screen Shot 2022-11-27 at 7 15 54 PM" src="https://user-images.githubusercontent.com/10256122/204167695-18e94a2f-39b2-4505-9c78-22ef4ec3aae1.png">

**Comment by keiya01** [comment]
This is caused by https://github.com/tauri-apps/wry/issues/445
