### ISSUE TITLE
[bug] on_web_resource_request not working in dev mode

### ISSUE THREAD

**Issue by matthme** [tauri-apps/tauri#5708]
### Describe the bug

In dev mode, i.e. when running `npm run tauri dev` the method `on_web_resource_request` of the `WundowBuilder` seems to be ignored.

### Reproduction

1. Run `sh <(curl https://create.tauri.app/sh)` on linux.
2. Choose npm as the package manager and `Vue-ts` as the frontend framework.
3. Add the following setup hook to `src-tauri/src/main.rs`:
```
        .setup(|app| {
            use tauri::WindowBuilder;
            use tauri::WindowUrl;
            let _window = WindowBuilder::new(
                &app.handle(),
                String::from("some_label"),
                WindowUrl::App("index.html".into()),
            ).on_web_resource_request(move |request, response| {
              println!("Received request: {:?}", request);
            }).build();

            Ok(())
        })

```
4. Run `npm run tauri dev` and see that the print statement is not being triggered.
5. Build the app via `npm run tauri build` and see that the print statement is being triggered when running the AppImage.

### Expected behavior

I expect `.on_web_resource_request()` to also work in dev mode.

### Platform and versions

Environment
  › OS: Ubuntu 22.04 X64
  › Node.js: 16.11.1
  › npm: 8.0.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.1
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.1,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.6,
  › wry [RUST]: 0.22.5,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Vue.js

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ src-tauri
  ├─ src
  ├─ .vscode
  └─ public

**Comment by FabianLars** [comment]
This is expected and documented:
![grafik](https://user-images.githubusercontent.com/30730186/204272526-4d0d4968-7be0-4a35-a44f-fdd25bfd2e99.png)

Thank you for your report.

**Comment by matthme** [comment]
Oh that's a big pitty. It was working before I updated to tauri 1.2.0 so I didn't really think about looking into the docs. I guess something changed under the hood when running `npm run tauri dev`.

**Comment by FabianLars** [comment]
The only change to `tauri dev` was that it now serves the frontend files, if your devPath is a file path and not a url, via an internal dev server to enable hot reloading.

**Comment by matthme** [comment]
Yes, that's probably it. I had a file path and it was working before at least without hot-reloading (if I needed hot-reloading I took care of it myself by running my own dev server and then on_web_resource_request was indeed not working). Now my iteration frequency has just dropped a lot :/ Is there a way to disable hot-reloading?

**Comment by FabianLars** [comment]
No, i think it's hard coded. idk if that works but you could try setting `tauri://localhost` as the devPath.

If that doesn't work i'd suggest using `tauri build --debug --b none`, preferably in a script which can stops/start the app too (the script would need to take care of a potential beforeDevCommand too).
`cargo run` or `cargo run --features custom-protocol`  in your src-tauri dir should work too.

p.s. feel free to open a feature request asking for a built-in way to disable it (no promises).

**Comment by matthme** [comment]
Thank you! `tauri://localhost` alone didn't work, because it seems to expect a port number. But `cargo run`  in src-tauri did :)

I think a feature request would be overkill in this case, especially since `on_web_resource_request` may at some be supported in dev mode anyway.

**Comment by amrbashir** [comment]
@matthme next version will have `--no-dev-server` option to disable the dev server for static files.
