### ISSUE TITLE
[bug] tauri-cli crate name discrepancy 

### ISSUE THREAD

**Issue by lookbusy1344** [tauri-apps/tauri#5715]
### Describe the bug

Trying to update to tauri cli 1.2.1 (from 1.2.0) I ran:

`cargo install tauri-cli`

but I get a build error. A crate is named ‘sha-1’ but seems to be referred to as ‘sha_1’ with an underscore not a dash.

### Reproduction

`cargo install tauri-cli`

and it goes bang on my system. Around 300 crates in. (Windows 10, latest version of rust).

### Platform and versions

Windows 10
Rust 1.65
Previous version of Tauri is 1.2.0

**Comment by FabianLars** [comment]
I can't reproduce this.

Can you try installing it like this please? `cargo install tauri-cli --locked`

**Comment by lookbusy1344** [comment]
That has fixed it, thanks a lot for your help!
