### ISSUE TITLE
[feat] Add `window.navigate_to_url`

### ISSUE THREAD

**Issue by takkuumi** [tauri-apps/tauri#5716]
### Describe the problem

Now, We change the window url in a clumsy way.

The solution comes from  #5377
```rust

main_window.eval(&format!("window.location.replace('http://localhost:{}')", "1234"));
```

### Describe the solution you'd like

I think we can provide a new mod named `location` under window instance, The function of location can be partially similar to [Window.location](https://developer.mozilla.org/en-US/docs/Web/API/Window/location)

**Comment by jhutchins** [comment]
I believe this was resolved with https://github.com/tauri-apps/tauri/pull/7235
