### ISSUE TITLE
[docs]  How to run a executable file as a tauri subprocess in its own resource folder?

### ISSUE THREAD

**Issue by Daic115** [tauri-apps/tauri#5719]
Appreciate for your great work! I have a problem while using `tauri`.

I've used `python` + `nuitika` + `fastapi` to build a executable backend service that works well on windows, the backend service folder structure is as follows:
```tree
./server
|   main-x86_64-pc-windows-msvc.exe     # main process (start a server)
|   python38.dll                        # python dll
|   select.pyd
|   ...                                 # pyd/py files
|   six.py
+---pandas
    |   ...
+---numpy
    |   ...
+---...                                 # python packages
```
`main-x86_64-pc-windows-msvc.exe` can run correctly in this folder:
```
> .\main-x86_64-pc-windows-msvc.exe
INFO:     Started server process [27756]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8847 (Press CTRL+C to quit)
```

I tried using `sidebar` to make it as a subprocess of `Tauri`, guided by the [doc](https://tauri.app/zh/v1/guides/building/sidecar) (In order for the server to follow the main program to start and stop); I put backend server folder at `./src-tauri/server`, and run tauri with:

```json
// tauri.conf.json
"tauri": {
"allowlist": {
    "all": true,
    "shell": {
    "sidecar": true,
    "scope": [
        {
        "name": "server/main",
        "sidecar": true
        }
    ]
    }
},
"bundle": {
    "externalBin": ["server/main"],
},
...
}
```

```rust
// main.rs
fn main() {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![greet])
        .setup(|app| {
            let window = app.get_window("main").unwrap();
            tauri::async_runtime::spawn(async move {
                let (mut rx, mut child) = Command::new_sidecar("main")
                    .expect("failed to setup `app` sidecar")
                    .spawn()
                    .expect("Failed to spawn packaged node");

                let mut i = 0;
                while let Some(event) = rx.recv().await {
                    if let CommandEvent::Stdout(line) = event {
                        window
                            .emit("message", Some(format!("'{}'", line)))
                            .expect("failed to emit event");
                        i += 1;
                        if i == 4 {
                            child.write("message from Rust\n".as_bytes()).unwrap();
                            i = 0;
                        }
                    }
                }
            });

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

Run `pnpm tauri dev` it can show the tauri window, but the `server` process is not started.
Then, I build the tauri app, found it only packed `main.exe` in `./src-tauri/target/release` folder.

I also added `resources` in `tauri.conf.json`:
```json
...
      "resources": [
        "server/*"
      ],
...
```

```rust
let resource_path = app
    .path_resolver()
    .resolve_resource("server/main-x86_64-pc-windows-msvc.exe")
    // also tried 'server/main-x86_64-pc-windows-msvc' and 'server/main'
    .expect("failed to resolve resource");
let pathstr: String = resource_path.to_str().unwrap().to_string();
...
    tauri::async_runtime::spawn(async move {
                let (mut rx1, mut child1) = Command::new_sidecar(pathstr)
                    .expect("failed to setup `app` sidecar")
                    .spawn()
                    .expect("Failed to spawn packaged node");
...
```
I got panicked log:
```
thread 'tokio-runtime-worker' panicked at 'Failed to spawn packaged node: Io(Os { code: 123, kind: InvalidFilename, message: "文件名、目录名或卷标语法不正确。(The file name, directory name, or volume label syntax is incorrect.)" })', src\main.rs:125:22
```
So, how to run a executable file as a tauri subprocess in its own resource folder? Thanks!

**Comment by FabianLars** [comment]
Is it possible to compile that app with pyinstaller or pyoxidizer to a single file executable? That would make it much easier to bundle with your Tauri app than trying to bundle the whole folder as a resource.

The first example may only work if you put all the files from the server dir right next to the tauri.conf file so they all end up next to each other after building (this will only work on windows).

The last example should work if you use a normal command (`Command::new` either from tauri or std) instead of a sidecar.

**Comment by Daic115** [comment]
> Is it possible to compile that app with pyinstaller or pyoxidizer to a single file executable? That would make it much easier to bundle with your Tauri app than trying to bundle the whole folder as a resource.
> 
> The first example may only work if you put all the files from the server dir right next to the tauri.conf file so they all end up next to each other after building (this will only work on windows).
> 
> The last example should work if you use a normal command (`Command::new` either from tauri or std) instead of a sidecar.

Thank you for your answer! I have considered this solution, but some custom python packages need to be updated from time to time, it will be too large if package the entire exe for updating.

I tried  the method with `Command::new()`, it will open a independen program, not a subprocess (I need the server to follow the main program to start and stop).

**Comment by FabianLars** [comment]
> it will open a independen program, not a subprocess

the sidecar api actually does the exact same thing (using normal Commands). The difference is that Tauri keeps track of the sidecars and cleans them up. So in your case you could just clean it up manually on `Exit` or `ExitRequested` https://docs.rs/tauri/latest/tauri/struct.App.html#method.run
On that note i also suggest looking into https://crates.io/crates/command-group to make sure _all_ processes of the python app gets killed.

**Comment by Daic115** [comment]
Thank you for taking time to answer my questions,  I will try it with your anwser! @FabianLars

**Comment by giiyms** [comment]
@FabianLars is there any example of command-group with tauri?

I am trying to add the Tauri Command to a command group but get compilation errors saying 
```
the trait bound `std::process::Command: From<(tauri::async_runtime::Receiver<CommandEvent>, CommandChild)>` is not satisfied
the trait `From<tauri::api::process::Command>` is implemented for `std::process::Command`rustcClick for full compiler diagnostic
```

This is the code:
```rust
// let t = TCommand::new(resource_path.as_path().to_str().unwrap())
//     .args(&["rest"])
//     .spawn()
//     .expect("Failed to spawn server");

let t = TCommand::new_sidecar("trame")
    .expect("failed to create sidecar")
    .args(["--server", "--port", "0", "--timeout", "30"])
    .spawn()
    .expect("Failed to spawn server");

// Add TCommand to Group spawn

let mut group = Command::from(t)
    .group_spawn()
    .expect("Failed to start the API");
```


or full script:

```rust
#![cfg_attr(
    all(not(debug_assertions), target_os = "windows"),
    windows_subsystem = "windows"
)]

use command_group::CommandGroup;
use std::sync::mpsc::{sync_channel, Receiver};
use std::thread;
// use sysinfo::{Pid, ProcessExt, Signal, System, SystemExt};

use async_std::task;

use std::time::Duration;
use tauri::api::process::Command as TCommand;
use tauri::api::process::CommandEvent as TCommandEvent;
use tauri::Manager;
use tauri::WindowEvent;

use std::process::Command;

// use command_group::AsyncCommandGroup as CommandGroup;
// use tokio::process::Command;

fn start_backend(receiver: Receiver<i32>, app: &mut tauri::App) {
    let resource_path = app
        .path_resolver()
        .resolve_resource("resources/server/server")
        .expect("failed to resolve resource dir");
    println!("{}", resource_path.display());
    let splashscreen_window = app.get_window("splashscreen").unwrap();
    let main_window = app.get_window("main").unwrap();

    // print message to string
    println!("hello world");

    // let t = TCommand::new(resource_path.as_path().to_str().unwrap())
    //     .args(&["rest"])
    //     .spawn()
    //     .expect("Failed to spawn server");

    let t = TCommand::new_sidecar("trame")
        .expect("failed to create sidecar")
        .args(["--server", "--port", "0", "--timeout", "30"])
        .spawn()
        .expect("Failed to spawn server");

    // Add TCommand to Group spawn

    let mut group = Command::from(t)
        .group_spawn()
        .expect("Failed to start the API");
    thread::spawn(move || loop {
        let mut s = receiver.recv();
        if s.unwrap() == -1 {
            group.kill().expect("Failed to close API");
        }
    });

    tauri::async_runtime::spawn(async move {
        while let Some(event) = t.0.recv().await {
            if let TCommandEvent::Stdout(line) = event {
                // write to stdin
                println!("Message from server: {}", line);
                // let mut lock2 = stdout().lock();
                // writeln!(lock2, "Message from server: {}", line).unwrap();
                if line.contains("tauri-server-port=") {
                    let tokens: Vec<&str> = line.split("=").collect();
                    println!("Connect to port {}", tokens[1]);
                    main_window.eval(&format!(
                        "window.location.replace('http://localhost:{}')",
                        tokens[1]
                    ));
                    task::sleep(Duration::from_secs(2)).await;
                    splashscreen_window.close().unwrap();
                    main_window.show().unwrap();
                }
            }
        }
    });
}

fn main() {
    let (tx, rx) = sync_channel(1);
    tauri::Builder::default()
        .setup(|app| {
            start_backend(rx, app);
            Ok(())
        })
        .on_window_event(move |event| match event.event() {
            WindowEvent::Destroyed => {
                println!("Prepare to close the background API");
                tx.send(-1).expect("Failed to send close signal");
                println!("Background API is closed");
            }
            _ => {}
        })
        // .invoke_handler(tauri::generate_handler![start_backend,terminate_backend,terminate_pid])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}


```

Any help is appreciated.

**Comment by FabianLars** [comment]
You're not allowed to spawn the TCommand. You only create the tauri command, then convert it to a std command, and then spawn it with command_group.
So in this case change this
```rs
let t = TCommand::new_sidecar("trame")
        .expect("failed to create sidecar")
        .args(["--server", "--port", "0", "--timeout", "30"])
        .spawn()
        .expect("Failed to spawn server");
```
to this
```rs
let t = TCommand::new_sidecar("trame")
        .expect("failed to create sidecar")
        .args(["--server", "--port", "0", "--timeout", "30"]);
```
and go from there

**Comment by AyalaGol** [comment]
Hi, 

I have an issue in this context:
I have a folder that contains EXE file with dependencies (dlls), 
I should run the EXE file by tauri.
Because the EXE file is not self-contained I cannot use the SideCar feature but command.new().

The folder with the files are located in src-tauri/target/debug/playerLogic.
I declared a command in tauri.conf.json:
  {
    "name": "PlayerLogic",
    "cmd": "$RESOURCE/playerLogic/Player.exe"
   },

and finally, run the command via the angular code:

 let command = new Command( 'PlayerLogic');
 let output = await command.execute();
 console.log(output);

the Player.exe is starting to run but I get an exception that the DLLs are not found although they are located in the same folder.

If I run the EXE file manually from the folder - it runs successfully.

what could be the issue?

thanks!

**Comment by giiyms** [comment]
@panayaui I added the folder to the resources in tauri.conf.json. For my case I had a server.exe inside a "server" folder, so my conf.json resources looked like this:

```json
"resources": [
        "server"
      ],
```

This copied the folder and all .dlls across to base directory in target/debug or target/release

I didn't use sidecars at all but instead just called the exe directly inside the tauri::Builder using:

```rust
            let (mut rx, child) = Command::new(".\\server\\server.exe")
                .args(["--server", "--port", "1234", "--timeout", "30"])
                .spawn()
                .expect("Failed to spawn server");
            println!("Started process: {}", child.pid());
```

**Comment by AyalaGol** [comment]
I did the same but call the command API via the js, not Rust.
` let command = new Command( 'PlayerLogic');
        let output = await command.execute();
        console.log(output);`

and get exception of :
System.IO.FileNotFoundException: Could not load file or assembly 'GalaSoft.MvvmLight, Version=5.4.1.0, Culture=neutral, PublicKeyToken=bb738e8c4ab8c76c' or one of its dependencies. The system cannot find the file specified.
   at Player.main.Main(String[] args)

**Comment by giiyms** [comment]
if you change it to 
```js
let command = new Command( '.\\playerLogic\\Player.exe')
```

Does that work?

**Comment by AyalaGol** [comment]
the program is running but the dependencies are not included or recognized.
