### ISSUE TITLE
[feat] Specify the tauri configuration file

### ISSUE THREAD

**Issue by Archieeeeee** [tauri-apps/tauri#5720]
### Describe the problem

I want to build multi bundles from different configuration files instead of using tauri.conf.json

### Describe the solution you'd like

Add a parameter to tauri build command to specify which configuration file or configuration name to use

**Comment by FabianLars** [comment]
There already is a `--config`/`-c` option which you can use to add new (partial) configs which will be merged into the main tauri.conf.json file. You'll still need to have a main config, but depending on your merge configs it can be fairly small.

And then there are platform specific conf files that are read automatically: tauri.linux.conf.json, tauri.windows.conf.json, and tauri.macos.conf.json
