### ISSUE TITLE
[bug] build failed when the **renamed** output is running

### ISSUE THREAD

**Issue by ryanroe** [tauri-apps/tauri#5726]
### Describe the bug

this is the reproduction gif image

the question is 

i have renamed the output binary to some other name, why tauri still failed to build?

![index html - empty-app - Visual Studio Code 2022-11-30 10-46-29](https://user-images.githubusercontent.com/20389952/204696201-af6224c2-11ab-4303-a93f-c1e232c577b1.gif)

### Reproduction

# Step to reproduce
1. create an empty app named `empty-app` via guide
```shell
npx create-tauri-app
```
2. build app (don't bundle)
```shell
npx tauri build -b none
```
3. rename output binary name in `target/release` directory ( empty-app.exe -> some-other-name.exe)
4. execute `some-other-name.exe`  and keep running
5. run `npx tauri build -b none` again

### Expected behavior

command execute successfully

### Platform and versions

Environment
  › OS: Windows 10.0.22623 X64
  › Webview2: 107.0.1418.56
  › MSVC: 
      - Visual Studio Community 2022
  › Node.js: 16.17.0
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.0 (outdated, latest: 1.2.1)
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.1,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.6,
  › wry [RUST]: 0.22.5,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../src
  › devPath: ../src

App directory structure
  ├─ .vscode
  ├─ node_modules
  ├─ src
  └─ src-tauri

### Additional context

content of tauri.config.json 
```json
{
  "build": {
    "beforeDevCommand": "",
    "beforeBuildCommand": "",
    "devPath": "../src",
    "distDir": "../src",
    "withGlobalTauri": true
  },
  "package": {
    "productName": "empty-app",
    "version": "0.0.0"
  },
  "tauri": {
    "allowlist": {
      "all": true
    },
    "bundle": {
      "active": true,
      "category": "DeveloperTool",
      "copyright": "",
      "deb": {
        "depends": []
      },
      "externalBin": [],
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "identifier": "com.tauri.dev1",
      "longDescription": "",
      "macOS": {
        "entitlements": null,
        "exceptionDomain": "",
        "frameworks": [],
        "providerShortName": null,
        "signingIdentity": null
      },
      "resources": [],
      "shortDescription": "",
      "targets": "all",
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "security": {
      "csp": null
    },
    "updater": {
      "active": false
    },
    "windows": [
      {
        "fullscreen": false,
        "height": 600,
        "resizable": true,
        "title": "empty-app",
        "width": 800
      }
    ]
  }
}

```

**Comment by amrbashir** [comment]
Well, it works on my end so please post the full error here. Also note that this is not tauri's fault, it is the linker used by rust to link your binary.

**Comment by ryanroe** [comment]
i created an issue on https://github.com/rust-lang/cargo/issues/11446 , and it was fixed, so closing the issue
