### ISSUE TITLE
How to execute javascript by webview[feat] 

### ISSUE THREAD

**Issue by Zerounary** [tauri-apps/tauri#5728]
### Describe the problem

I wanna to create a browser crawler app。I need to execute some javascript code in some sites window content. How can I execute javascript by webview.

### Describe the solution you'd like

Add some function in webview to execute javascript.

**Comment by JonasKruckenberg** [comment]
See this API: https://docs.rs/tauri/1.2.1/tauri/window/struct.Window.html#method.eval

**Comment by Zerounary** [comment]
Thanks. :)

**Comment by zheng12dfdfsdfsd** [comment]
can you sharing your code for me?thank agent
