### ISSUE TITLE
[bug] Not able to stdin a shell script by using a spawned process with Tauri's Command API

### ISSUE THREAD

**Issue by mauriver21** [tauri-apps/tauri#5736]
### Describe the bug

I have defined a child process from the Tauri Command's API that reads a shell script as follows:
```typescript
const cmd = new Command('run-script', ['myScript.sh']);
cmd.stdout.on('data', (data) => console.log(data));
cmd.stderr.on('data', (data) => console.log(data));
const child = cmd.spawn();
await child.write('Hello World!');
```

On the .sh file I have the following:
```bash
echo "Input something:"
READ=$(cat)
echo "I have read from $READ"
```

I've spawned the command, but only echoes line 1 with `Input something:`. `child.write` is not passing the `stdin` for continuing the bash script execution.

### Expected behavior

It must echo `I have read from Hello World!` and then end the shell script.

### Additional context

Note: the `run-script` command was registered at `tauri.conf.json` as follows:

```json
"shell": {
  "all": true,
  "scope": [
    {
      "name": "run-script",
      "cmd": "sh",
      "args": [{ "validator": "-c" }, { "validator": "(.*?)" }]
    }
  ]
}
```

### Platform and versions

Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 16.13.1
  › npm: 8.1.2
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.2.1
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.0,
  › tauri-build [RUST]: 1.2.0,
  › tao [RUST]: 0.15.3,
  › wry [RUST]: 0.22.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/

App directory structure
  ├─ node_modules
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  └─ src

**Comment by amrbashir** [comment]
executing `cat` without any arguments will redirect input to output indefinitely until it is manually interrupted using `Ctrl+C`. I am not sure what you want to do but try using [`read`](https://ss64.com/bash/read.html) instead.

I am gonna go ahead and close this but feel free to provide a minimal repro and I will take another look.

**Comment by mauriver21** [comment]
> executing `cat` without any arguments will redirect input to output indefinitely until it is manually interrupted using `Ctrl+C`. I am not sure what you want to do but try using [`read`](https://ss64.com/bash/read.html) instead.
> 
> I am gonna go ahead and close this but feel free to provide a minimal repro and I will take another look.

With only read, also it doesn't work. However, I've figured out how to make it work. At the write command, you need to add at the end a linebreak `\n` to make `stdin` process end for continuing the script execution. Here is the solution:

```typescript
    const cmd = new Command('run-script', ['myScript.sh']);
    cmd.stdout.on('data', (data) => console.log(data));
    cmd.stderr.on('data', (data) => console.log(data));
    const child = cmd.spawn();
    await child.write('Hello World!\n');
```
 I've changed the script with the following, using the keyword `REPLY` that captures the result from `read`

```bash
echo "Input something:"
read
TEXT=$REPLY
echo "I have read from $TEXT"
```

It took me a couple of days to figure out that the problem was the linebreak `\n`, Why the write command doesn't take care of that automatically?

**Comment by amrbashir** [comment]
> It took me a couple of days to figure out that the problem was the linebreak `\n`, Why the write command doesn't take care of that automatically?

because you might want to write multiple times without passing `\n`

**Comment by mauriver21** [comment]
> > It took me a couple of days to figure out that the problem was the linebreak `\n`, Why the write command doesn't take care of that automatically?
> 
> because you might want to write multiple times without passing `\n`

Maybe another suggestion is to add a method to end the writing process, for example
```
cmd.write("My line 1")
cmd.write("My line 2")
cmd.write("My line 3")
cmd.writeEnd()
```
It would be more clear when `stdin` needs to be sent. NeutralinoJS has something similar, you can check [here](https://neutralino.js.org/docs/api/os), at `os.updateSpawnedProcess(id, action, data)`
