### ISSUE TITLE
[docs] exists from "@tauri-apps/api/fs" has bad return type

### ISSUE THREAD

**Issue by erikpa1** [tauri-apps/tauri#5740]
Hi I switched my project to typescript and found this there should be Promise<bool> instead of void:

![image](https://user-images.githubusercontent.com/19526670/205027343-dc461379-8608-4332-bdb9-a55dae571963.png)

**Comment by FabianLars** [comment]
This was fixed already. Please update your `@tauri-apps/api` package (and re-install your npm packages) and check again.
