### ISSUE TITLE
[bug] Keydown event trigger twice

### ISSUE THREAD

**Issue by vicanso** [tauri-apps/tauri#5741]
### Describe the bug

I found that if the command key is pressed, the keydown event triggered twice. The log:

<img width="788" alt="image" src="https://user-images.githubusercontent.com/437351/205049213-1f69076c-d780-4199-ae0a-ecffd775e1c3.png">

### Reproduction

1. pnpm create tauri-app
2. cd tauri-app
3. add this code to main.js
```js
document.addEventListener("keydown", (e) => {
  console.dir(`metaKey:${e.metaKey} key:${e.key}`);
});
```
4. pnpm install
5. pnpm tauri dev
6. press command and n

### Platform and versions

Environment
  › OS: Mac OS 13.0.1 X64
  › Node.js: 18.6.0
  › npm: 8.13.2
  › pnpm: 7.17.1
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.2.1
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.1,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.6,
  › wry [RUST]: 0.22.5,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../src
  › devPath: ../src

**Comment by wusyong** [comment]
Closed by https://github.com/tauri-apps/wry/pull/782

**Comment by vicanso** [comment]
@wusyong  The `Esc` key doesn't trigger keydown event in 1.2.2 version.

**Comment by wusyong** [comment]
I'm fixing it in https://github.com/tauri-apps/wry/pull/798
