### ISSUE TITLE
[feat] How an application injects a rust plugin from the outside

### ISSUE THREAD

**Issue by lencx** [tauri-apps/tauri#5745]
### Describe the problem

After the application is built, I want to extend it. tauri currently seems to be able to register plugins only via `tauri::Builder::default().plugin()`, and cannot load external binaries.

### Describe the solution you'd like

```bash
~/Applications/TauriApp ←───────┐─┐─┐
~/User                          │ │ │ 
├── [plugin]                    │ │ │ 
│   ├── plugin1 ───── inject ───┘ │ │ 
│   ├── plugin2 ───── inject ─────┘ │ 
│   └── plugin... ─── inject ───────┘
└── ...
```

`plugin1`, `plugin2` and `plugin...` are plugin functions implemented using `tauri::command` and then compiled into binaries to provide to the `TauriApp`.

```rust
fn main() {
    tauri::Builder::default()
        .load_plugin(tauri::api::path::plugin_dir()) // ✅ new add
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

**Comment by amrbashir** [comment]
I don't think this is something that we will ever consider. A few reasons are, It is insecure, unsafe and will require using FFI types which won't work with the normal Plugin types.

However, a plugin system like this, can be built by you specifically for your app where you can harden its security as you see fit and use a type that can be used through FFI.
