### ISSUE TITLE
[ASK] How to listen `on clipboard copy` in tauri ?

### ISSUE THREAD

**Issue by Mitoax** [tauri-apps/tauri#5746]
I'm trying to read images from clipboard, and the current solution is using `arboard` crate.

Also any time a new image being `copied`, a update is expected. using a timer seems really slow (when image.width > 800)

SO: is there any event related solution to reduce the cost?

**Comment by FabianLars** [comment]
Tauri itself does not have any clipboard events.

There is this crate https://github.com/DoumanAsh/clipboard-master which implements this, but i don't know how usable it is.

**Comment by Mitoax** [comment]
Thanks a lot, by refactor and reuse part of its core lines, now it's working

Sample codes looks like this:

```rust
use objc::runtime::{Class, Object};
use objc_id::Id;

#[link(name = "AppKit", kind = "framework")]
extern "C" {}

// read the core [clipboard-change-count] which can be used as a state
pub fn clipboard_change_count() -> i64 {
    use objc::{msg_send, sel, sel_impl};

    let cls = match Class::get("NSPasteboard") {
        Some(cls) => cls,
        None => return -1,
    };
    let pasteboard: *mut Object = unsafe { msg_send![cls, generalPasteboard] };

    if pasteboard.is_null() {
        return -1;
    }

    let pasteboard: Id<Object> = unsafe { Id::from_ptr(pasteboard) };

    let change_count = unsafe { msg_send![pasteboard, changeCount] };
    change_count
}
```

**Comment by HuakunShen** [comment]
I made a tauri plugin that support both text and image. You could simply import the API methods in JavaScript or TypeScript.

- https://github.com/CrossCopy/tauri-plugin-clipboard
- Crate: https://crates.io/crates/tauri-plugin-clipboard
- NPM Package: https://www.npmjs.com/package/tauri-plugin-clipboard-api?activeTab=readme

A demo app also included in the repo.
