### ISSUE TITLE
[bug] App flickers when started in dark mode

### ISSUE THREAD

**Issue by cnshenj** [tauri-apps/tauri#5747]
### Describe the bug

A bare minimum Tauri app starts with a white background, then changes to a dark background in a split second, causing flickering effect.

Note: VSCode which uses Electron, doesn't have this problem. 

### Reproduction

1. Build a bare minimum Tauri app
2. Start the app in dark mode

### Expected behavior

The app starts with a dark background directly.

### Platform and versions

Windows 11, color mode set to dark mode.

**Comment by amrbashir** [comment]
See #1564
