### ISSUE TITLE
[bug] incorrect mime type for wasm when using tauri build

### ISSUE THREAD

**Issue by TrueDoctor** [tauri-apps/tauri#5749]
### Describe the bug

When building my vue app using `cargo tauri build`, I recive this error upon startup of the app: 
```
Unhandled Promise Rejection: TypeError: Unexpected response MIME type. Expected 'application/wasm'
```
It seems like the the `.wasm` file is served with the wrong mime type. (It dev mode, everything works fine)
I tried to poke around the codebase and added the wasm type to mime_types in tauri utils, but I couldn't seem to be able to find 
where the bundled files are loaded in tauri. Any help would be appreciated

Also I'm not a web dev so please excuse if did something stupid.

### Reproduction

clone "https://github.com/graphiteEditor/Graphite/tree/tauri"
(or some other vue app that uses wasm)
execute `cargo tauri build`
execute resulting appimage

### Expected behavior

The loaded wasm file should have the correct mime type (`application/wasm`) set and the app should load

### Platform and versions

Environment
  › OS: Arch Linux Rolling Release X64
  › Node.js: 16.13.1
  › npm: 8.13.2
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.66.0-nightly
  › cargo: 1.66.0-nightly
  › Rust toolchain: nightly-2022-10-01-x86_64-unknown-linux-gnu

Packages
  › @tauri-apps/cli [NPM]: 1.2.1
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.1,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.6,
  › wry [RUST]: 0.22.5,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://127.0.0.1:8080/
  › framework: Vue.js (Vue CLI)
  › bundler: Webpack

App directory structure
  ├─ src
  ├─ public
  ├─ graphite-tauri.AppDir
  ├─ assets
  ├─ src-tauri
  ├─ dist
  ├─ wasm
  └─ node_modules

**Comment by amrbashir** [comment]
Please create a minimal repro, the linked repro is not by all means "minimal".

**Comment by amrbashir** [comment]
I have tried the `yew` template from `create-tauri-app` which uses wasm and it worked fine.

**Comment by TrueDoctor** [comment]
> I have tried the `yew` template from `create-tauri-app` which uses wasm and it worked fine.

Alright, that's probably a good start to look into this then, yeah, I know, I'll provide a smaller example if that does not yield anything

**Comment by TrueDoctor** [comment]
I think it works in the yew case because when building the yew app the bundle is created with wasm-bindgen which adds a fallback for when the correct mime type is not set https://github.com/rustwasm/wasm-bindgen/blob/b584407a46a1b9f517d0f606fff954aaa079fa6b/crates/cli-support/src/js/mod.rs#L684-L710
But this still does not resolve the issue of the incorrect mime type.
I started to look into this and try to trace where the mime type is set in the tauri asset system (and where it is ultimately lost) and will update you as I make progress

**Comment by amrbashir** [comment]
Seems like somewhat a common issue https://stackoverflow.com/a/52732108

**Comment by amrbashir** [comment]
Alright I found the issue, so tauri v1 is locked to using an old version of webkit2gtk which doesn't support setting the headers on the custom protocol. `wry` recently implemented this but behind a feature flag in https://github.com/tauri-apps/wry/commit/cf447f64451fd8345f21440df31601265e0fde86 so in tauri v2, this should be fixed

**Comment by amrbashir** [comment]
For now please use the workaround I linked in the issue above or the one from wasm-bindgen.
