### ISSUE TITLE
[bug] Unable to access HTTP mjpg servers

### ISSUE THREAD

**Issue by noamzaks** [tauri-apps/tauri#5757]
### Describe the bug

Unable to access local network MJPG servers with unsecure HTTP

### Reproduction

Use an `<img src="http://192.168.1.1">` somewhere in your webview.

### Platform and versions

Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 107.0.1418.62
  › MSVC:
      - Visual Studio Community 2022
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.2.1
  › @tauri-apps/api [NPM]: 1.1.0 (outdated, latest: 1.2.0)
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › framework: React

App directory structure
  ├─ .git
  ├─ .github
  ├─ .webpack
  ├─ dist
  ├─ node_modules
  ├─ out
  ├─ src
  └─ src-tauri

### Additional context

![devtools console](https://user-images.githubusercontent.com/63877260/205490538-331ebd60-7f80-40c2-a674-aa181934fe85.png)

While this may be on the verge of security/insecurity, I think for some use cases like robotics it makes sense to enable this.

[discord thread](https://discord.com/channels/616186924390023171/1048227579066331216)

**Comment by ayelsew** [comment]
@noamzaks  do you have any screenshots or output messages related to the error?

**Comment by noamzaks** [comment]
> @noamzaks  do you have any screenshots or output messages related to the error?

In the DevTools console it showed the Mixed Content warning (The page at .. was loaded over HTTPS but requested an insecure image .. this was automatically upgraded to HTTPS). Then a bunch of net errors and failing requests, because the HTTP server did not support SSL.

Unfortunately I don't have access right now to the computer and robot I was working with, but I will try to get it ASAP (also for the required platform info - apologize for the delay)
