### ISSUE TITLE
[feat] Async handlers for custom protocols

### ISSUE THREAD

**Issue by Frando** [tauri-apps/tauri#5759]
### Describe the problem

Tauri lets you register custom protocol handler for uri schemes. These handlers are registered with [register_uri_scheme_protocol](https://docs.rs/tauri/latest/tauri/struct.Builder.html#method.register_uri_scheme_protocol). This function takes a synchronous closure `Fn(&AppHandle<R>, &HttpRequest) -> Result<HttpResponse, Box<dyn std::error::Error>>`. 

This means that the protocol handler cannot perform async IO without blocking the main thread.

 

### Describe the solution you'd like

The obvious solution would be to allow to register an protocol handler that takes a closure which returns a (usually boxed) future. So the register function could have the form 
```rust
pub fn register_uri_scheme_protocol<N,H,F>(self, uri_scheme: N, protocol: H) -> Self
where
    N: Into<String>,
    H: Fn(&AppHandle<R>, &HttpRequest) -> F, 
    F: Future<Output = Result<HttpResponse, Box<dyn std::error::Error>>>
```

Additionaly, ideally the `body` of the `HttpResponse` could be an async iterator (`dyn Stream<Item = Vec<u8>>`) as an alternative to the current `Vec<u8>`. Maybe it might make sense to reuse the [`Body`](https://docs.rs/hyper/latest/hyper/struct.Body.html) trait from the hyper ecosystem.

### Alternatives considered

Right now I am resorting to calling   `tauri::async_runtime::block_on(async move { my_async_handler().await })`. However, I would think that this blocks the main thread and therefore is not a viable way to perform potentially slow async I/O.

**Comment by JonasKruckenberg** [comment]
@tauri-bot upstream wry

**Comment by FabianLars** [comment]
https://github.com/tauri-apps/wry/issues/420

**Comment by JonasKruckenberg** [comment]
Damn, well close as duplicate?
PS: What a shame, now that I finally figured out how to use the bot 😂

**Comment by amrbashir** [comment]
I think at some point I need to implement a bot command to link to existing issues

`/link-upstream tauri-apps/wry#124`
