### ISSUE TITLE
[feat] Windows software update using unzipped msi files

### ISSUE THREAD

**Issue by kornelski** [tauri-apps/tauri#5760]
### Describe the problem

tauri-updater generates .msi, .msi.zip, and .msi.zip.sig. The problem is that the ZIP file is **larger** than the bare .msi file. The installer file is already compressed, and extra zipping is counter-productive. 

### Describe the solution you'd like

I'd prefer to just use the bare .msi file, because that's compressed enough, and it would allow me to upload and store only one file for both auto-update as well as initial download for users.

Can you make the Windows updater stop zipping msi installers, and instead sign the .msi file? (so there's app.msi.sig, not app.msi.zip.sig).

**Comment by amrbashir** [comment]
@lemarier was there a specific reason to use `.zip` or would this be a simple change (for v2 ofc)?
