### ISSUE TITLE
[bug] Canvas HTML slow render on Linux

### ISSUE THREAD

**Issue by ayelsew** [tauri-apps/tauri#5761]
### Describe the bug

I noticed that HTML Canvas has a bad performance on Linux. I tried to make an animation inside a canvas that runs when the user moves the mouse, and the FPS had rude falls close to 5 FPS.
But I tested the same code in the Brave and Chromium browsers and the FPS kept between 17 and 30.

Screenshot of Tauri app
![image](https://user-images.githubusercontent.com/33585141/205474458-0cddd9f0-cfaa-4c9e-9519-41a83bdb2830.png)

Screenshot of Brave browser
![image](https://user-images.githubusercontent.com/33585141/205474468-a59ecf69-f7cf-4ab0-9b9a-1219a84e214f.png)

Screenshot about performance render on the Tauri app
![image](https://user-images.githubusercontent.com/33585141/205474494-e355252b-ae00-4472-9edf-d6b89af116df.png)

This is the code that I used to build that canvas, is just this code. 
https://codepen.io/ayeslew-sh/pen/wvXQmNP

I had read https://github.com/tauri-apps/tauri/issues/4891 and https://github.com/tauri-apps/tauri/issues/5037 but I didn't see anything helpful for Linux, so I decide to open this issue.

### Reproduction

Any animations using HTML Canvas had a bad performance

### Expected behavior

Running animations with more FPS

### Platform and versions

```log
yarn run v1.22.19
$ tauri info

Environment
  › OS: Ubuntu 22.04 X64
  › Node.js: 18.12.0
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.1
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.1,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.6,
  › wry [RUST]: 0.22.5,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React

App directory structure
  ├─ .vscode
  ├─ public
  ├─ node_modules
  ├─ src-tauri
  ├─ src
  └─ dist
Done in 10.97s.
```

```
Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
Graphics: UHD Graphics 620 and GM108M [GeForce MX110]
RAM: 20 GB
```

### Additional context

The issue occurs in dev as much as in build production

Below has the source project to test

[tauri-app.zip](https://github.com/tauri-apps/tauri/files/10147884/tauri-app.zip)

**Comment by FabianLars** [comment]
Can you try it in epiphany (Gnome web) too? It's a browser based on webkitgtk which is the webview we use on Linux.

**Comment by ayelsew** [comment]
@FabianLars It has same behavior

Low FPS

![image](https://user-images.githubusercontent.com/33585141/205488193-5ae1637c-5e76-4ab8-8092-134bedd9b6e7.png)

![image](https://user-images.githubusercontent.com/33585141/205488219-76ecd050-aaf5-480b-82db-fce0fdbacea8.png)

**Comment by ayelsew** [comment]
I noticed that when I try to run the Epiphany browser with a dedicated graphic card, it throws the following error

```log
(epiphany:123359): epiphany-WARNING **: 08:50:29.185: Web process crashed

(WebKitWebProcess:2): Gdk-ERROR **: 08:50:29.448: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadFBConfig'.
  (Details: serial 218 error_code 167 request_code 152 (GLX) minor_code 21)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```
The window opens but in this case, it doesn`t render anything
![image](https://user-images.githubusercontent.com/33585141/205488953-4ad396c7-52b5-4ac2-afe8-899f4173b52a.png)

**Comment by ayelsew** [comment]
An alternative solution that I made for my specific case was caching the result of the heavy calculation. Because I don`t need to perform it again since the pixels of the wheel color don't change.

But FYI it doesn't fix the bug.

![image](https://user-images.githubusercontent.com/33585141/205521149-4dd7b6c2-9b03-42bd-b7e3-37bcd221416b.png)
I don't know why, it shows me now up to 60 FPS (my computer doesn't support this frame rate, maybe I make some mistake in the code). But now the animation runs softer. :smiley:

**Comment by amrbashir** [comment]
Seems like webkit2gtk 2.36 switch the `hardware-activation-policy` to `always` but that didn't make any difference from my testings

**Comment by amrbashir** [comment]
I think that's because webkit2gtk published on almost all distros don't enable WebGL 2.0 and it fallsback to WebGL 1.0 and so we are stuck with that for now.

**Comment by amrbashir** [comment]
Closing, since there is nothing we can do.

**Comment by FabianLars** [comment]
no promises but it looks like webgl2 support will be enabled in webkitgtk 2.40
