### ISSUE TITLE
[bug] Minimum window dimesions only apply sometimes

### ISSUE THREAD

**Issue by gorfxx** [tauri-apps/tauri#5762]
### Describe the bug

Intermittently the minimum window dimensions are not applied.
Bug occurs at least with "tauri dev" and AppImages (cant check .deb).
When the window is resized quickly the minimum window dimensions are not applied sometimes. The bug is more consistent when resizing the window quickly.

Im on Arch linux with bspwm and picom, tauri is v1.2.1 to date and rustc is v1.67.0-nightly
![bug](https://user-images.githubusercontent.com/95705408/205474782-bcaec2d7-3a94-4e97-a458-e51084c24e78.GIF)

### Reproduction

1. set a min width and height.
2. build the app.
3. resize the window.
4. bug occurs.

### Expected behavior

Window stops shrinking and stays at a constant size.

### Platform and versions

~/documents/projects/ritter/ cargo tauri info

Environment
  › OS: Arch Linux Rolling Release X64
  › Node.js: 16.18.1
  › npm: 8.19.2
  › pnpm: 7.9.3
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.67.0-nightly
  › cargo: 1.67.0-nightly
  › Rust toolchain: nightly-x86_64-unknown-linux-gnu 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.2.1
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.1,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.6,
  › wry [RUST]: 0.22.5,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
package.json not found

App directory structure
  ├─ target
  ├─ src
  ├─ public
  ├─ src-tauri
  ├─ .vscode
  └─ dist

### Additional context

bug occurs with any app i build with tauri.
this is my first bug report ever :^)

**Comment by amrbashir** [comment]
This seems like a bug in bspwm, so please try on another window manager, maybe KDE or Gnome, 

Generally on Linux, window management is done by applying hints to the window and window managers can choose to ignore that if they want.
