### ISSUE TITLE
Tauri app labeled as "damaged" on macos when installing

### ISSUE THREAD

**Issue by fardeem** [tauri-apps/tauri#5778]
### Describe the bug

I was playing around with Tauri and made a sample hello world app. When I bundled it, it was installable on my computer. However, when I tried installing on another m1 mac, it said the app was damaged and could not be opened. Running `xattr -cr /Applications/my-app.app` removed the issue. 

![IMG_5903](https://user-images.githubusercontent.com/2018374/206303204-bfd253c2-98a5-41f8-b14c-d83645b041b6.jpeg)

### Reproduction

1. Create a new tauri project using the cli
2. Build it using `tauri build` on a M1
3. Try installing on another M1 machine

### Expected behavior

I expect the app to be installable.

### Platform and versions

Environment
  › OS: Mac OS 13.0.1 X64
  › Node.js: 16.14.0
  › npm: 8.3.1
  › pnpm: 6.11.0
  › yarn: 1.22.15
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.2.1
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.1,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.6,
  › wry [RUST]: 0.22.5,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  └─ src

**Comment by FabianLars** [comment]
This is macOS' gatekeeper (no idea why apple thought it's a good idea to show such a misleading error). It blocks all downloaded apps which are not signed, so the only real solution is to give Apple 100$ to buy "trust" :(
