### ISSUE TITLE
[bug] lose focus when drag title bar on windows11

### ISSUE THREAD

**Issue by ZingerLittleBee** [tauri-apps/tauri#5782]
### Describe the bug

lose focus when drag title bar on windows11

### Reproduction

1. `pnpm tauri dev`
2. `pnpm i`
3. new project from cli, just listen `on_window_event`
```rust
fn main() {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![greet])
        // just listen on_window_event
        .on_window_event(|event| match event.event() {
            tauri::WindowEvent::CloseRequested { api, .. } => {
                event.window().hide().unwrap();
                api.prevent_close();
            }
            tauri::WindowEvent::Focused(false) => {
                println!("Window lost focus");
                event.window().hide().unwrap();
            }
            _ => {}
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

### Platform and versions

Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 107.0.1418.62
  › MSVC: 
  › Node.js: 16.17.1
  › npm: 8.15.0
  › pnpm: 7.18.1
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.1
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.1,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.6,
  › wry [RUST]: 0.22.6,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Vue.js

App directory structure
  ├─ .history
  ├─ .vscode
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri

**Comment by amrbashir** [comment]
This is unfortunately a limitation of the webview2 because the webview and the underlying window are separate from each other, and both has a different focus state and when you start dragging, you are clicking the window and so the webview loses focus.
