### ISSUE TITLE
[bug] `Escape` key undetectable in frontend

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tauri#5790]
### Describe the bug

As of Tauri `v1.2.1`, `keydown` events are no longer emitted for the `Escape` key on macOS.

In `v1.2.0`, menubar shortcuts didn't work. `v1.2.1` fixed that issue, which might be related (though can't see any changelog entry for it?).

### Reproduction

https://github.com/probablykasper/tauri-escape-bug

### Platform and versions

```
Environment
  › OS: Mac OS 10.15.7 X64
  › Node.js: 18.12.1
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.2.2
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.1,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.2,
  › wry [RUST]: 0.23.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:5179/
  › framework: Svelte
  › bundler: Vite

App directory structure
  ├─ node_modules
  ├─ src-tauri
  ├─ build
  ├─ .git
  └─ src
```

**Comment by FabianLars** [comment]
can you run `cargo update` to update your tao version? Hopefully this was fixed already 😅

**Comment by probablykasper** [comment]
It's still there on the latest tao version

**Comment by probablykasper** [comment]
Pinning tao to `=0.15.0` doesn't seem to revert to the old behavior. Maybe it's wry v0.23

**Comment by probablykasper** [comment]
Narrowed it down, these updates are causing the issue to appear:
```
tauri-runtime-wry v0.12.1 -> v0.12.2
wry v0.22.6 -> v0.23.1
```

**Comment by wusyong** [comment]
I can bring it back but the beep error sound will remain.

**Comment by probablykasper** [comment]
I'd say that's worth, since losing `Escape` support probably has a pretty big impact, and the beep can be worked around. Hopefully some magical solution is found in the future

**Comment by wusyong** [comment]
I also start another issue to discuss how do we disable the sound afterwards.
https://github.com/tauri-apps/wry/issues/799
Will appreciate any feedback.
