### ISSUE TITLE
[feat] show window on top of full-screen app

### ISSUE THREAD

**Issue by seahindeniz** [tauri-apps/tauri#5793]
### Describe the problem

I have a widget-looking window and I can't show it on top of a window in full-screen.

https://user-images.githubusercontent.com/5789670/206115866-0cc4b0ce-387f-4aaa-a0df-a92a1a8cfdc4.mp4

### Describe the solution you'd like

Ability to make a window visible on top of everything. Maybe by force, I'm not sure.

### Alternatives considered

There's an app called CopyQ (built with QT) and it can show its main window on top of any other window

### Additional context

I have only reproduced this issue on macOS Ventura. macOS Monterey works as expected, and I'm not sure about other platforms.

**Comment by amrbashir** [comment]
See https://github.com/tauri-apps/tauri/issues/2801 and https://github.com/tauri-apps/tao/issues/189
