### ISSUE TITLE
[feat] Remove focus from the application

### ISSUE THREAD

**Issue by elanzini** [tauri-apps/tauri#5794]
### Describe the problem

I expected the focus to be removed from the application when calling `appWindow.hide()` using the `window` module - but that is not the case (at least on MacOS).
 I tried the following homemade solution:
```rust
#[tauri::command]
fn blur(window: tauri::Window) {
  use raw_window_handle::HasRawWindowHandle;

  match window.raw_window_handle() {
    raw_window_handle::RawWindowHandle::AppKit(handle) => {
      // macOS
      use cocoa::appkit::NSWindow;

      let ns_window = handle.ns_window as cocoa::base::id;

      unsafe {
        ns_window.orderBack_(cocoa::base::nil);
        ns_window.orderOut_(cocoa::base::nil);
      }
    }
    _ => println!("blur operation: unsupported OS"),
  }
}
```
Inspired by [Electron](https://github.com/electron/electron/blob/main/shell/browser/native_window_mac.mm#L416) but unfortunately, that is not working as expected.

### Describe the solution you'd like

I would like a `focus(boolean)` method as part of the `window` module to remove focus from the application.

**Comment by amrbashir** [comment]
maybe try switching the order, the electron source code has different order than yours.

Also, un-focusing a window is not something we will add an API for since it is only supported on macOS.
