### ISSUE TITLE
Get list of connected printer with systems cross platforms and print command

### ISSUE THREAD

**Issue by meet-rizwan** [tauri-apps/tauri#5795]
### Describe the problem

I tried rust it is a very fast and smooth development experience, the only thing keeping me away from switching my software from electron to Tauri is managing printers. there are many rust packages available for thermal printer but they are not well maintained 

### Describe the solution you'd like

please provide printer API  in tauri/api to manage directly from the js side 

get a list of printers
select default printer
get default printers
print  invoke command
multiple print command
configure printers
active printers
fonts style 
page margin 

### Alternatives considered

no alternative I have tried a lot with different native rust packages and already communicated in community already many times

**Comment by amrbashir** [comment]
closing in favor of #4917
