### ISSUE TITLE
[bug] Obscure issue with conic gradient and zero values

### ISSUE THREAD

**Issue by Soremwar** [tauri-apps/tauri#5801]
### Describe the bug

When using values to tell conic gradient color position at 0%, the app freezes completely

### Reproduction

1. Initialize a vanilla project
1. Use the following code on `index.html`
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <style>
      #bug {
        width: 300px;
        height: 300px;
        background: conic-gradient(red 0%, transparent 0% 100%);
      }
    </style>
  </head>
  <body>
    <div id="bug"></div>
  </body>
</html>
```

### Expected behavior

For it to work

### Platform and versions

Environment
  › OS: EndeavourOS Rolling Release X64
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.2.2
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.2,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.6,
  › wry [RUST]: 0.23.2,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../src
  › devPath: ../src
package.json not found

App directory structure
  ├─ src
  ├─ .vscode
  └─ src-tauri

### Stack trace

```shell
None, just freezes
```

### Additional context

- This only happens on 0% position, any other position the issue. Other browsers have no problem with this
- This can also be reproduced with degrees like `conic-gradient(red 0deg, blue 0deg 360deg)`

**Comment by FabianLars** [comment]
Can you try it in epiphany / gnome web too please? Just wanna double check if it's a webkitgtk problem or something specific to tauri/wry

**Comment by Soremwar** [comment]
Can reproduce on Epiphany Web 43.0+
