### ISSUE TITLE
[bug] The symlink source is [...]libtauri_app.so, but nothing exists there

### ISSUE THREAD

**Issue by g123k** [tauri-apps/tauri#5831]
### Describe the bug

Hi everyone,

I try to run the android project, with the following command on a Mac Intel: `cargo tauri android dev`
But it fails at the end with the following error:

```
Compiling tauri-utils v2.0.0-alpha.0
    Finished dev [unoptimized + debuginfo] target(s) in 41.83s
        Info symlinking lib "/Users/g123k/Documents/tauri-app/src-tauri/target/x86_64-linux-android/debug/libtauri_app.so" in jniLibs dir "/Users/g123k/Documents/tauri-app/src-tauri/gen/android/tauri-app/app/src/main/jniLibs/x86_64"
       Error The symlink source is /Users/g123k/Documents/tauri-app/src-tauri/target/x86_64-linux-android/debug/libtauri_app.so, but nothing exists there
```

### Reproduction

1. Create an empty tauri app
2. Launch `cargo tauri android dev`

### Platform and versions

Environment
  › OS: Mac OS 13.0.1 X64
  › Node.js: Not installed!
  › npm: Not installed!
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.0
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 2.0.0-alpha.0,
  › tauri-build [RUST]: 2.0.0-alpha.0,
  › tao [RUST]: 0.15.7,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../src
  › devPath: ../src
package.json not found

App directory structure
  ├─ src-tauri
  ├─ .vscode
  └─ src

**Comment by FabianLars** [comment]
Did you add this to your Cargo.toml file?
```toml
[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
```
Did you also run `tauri android init` ?

**Comment by g123k** [comment]
Ooops you're totally right.
After applying everything explained on the doc, it's still not compiling:

```
cargo tauri android dev
        Info detected host target triple "x86_64-apple-darwin"
Detected connected device: Pixel_2_API_33 (sdk_gphone64_x86_64) with target "x86_64-linux-android"
<-------------> 0% EXECUTING [669ms]
   Compiling tauri-app v0.0.0 (/Users/g123k/Documents/tauri-app/src-tauri)
error: custom attribute panicked]tion 1/100
 --> src/mobile.rs:1:1Debug
  |
1 | #[tauri::mobile_entry_point]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: message: `"tauri-app"` is not a valid identifier

error: could not compile `tauri-app` due to previous error
       Error `Failed to run `cargo build`: Command "cargo build --package tauri-app --manifest-path /Users/g123k/Documents/tauri-app/src-tauri/Cargo.toml --target x86_64-linux-android --no-default-features --color always" didn't complete successfully, exiting with code 101.
```

**Comment by FabianLars** [comment]
iirc the app name currently can't contain a `-` for whatever reason. so if you rename tauri-app to tauriapp for example that error should be gone too.

**Comment by g123k** [comment]
Perfect, everything seems to works fine now. Thanks a lot!

(Just a suggestion: add the "-" character issue in the doc)
