### ISSUE TITLE
[bug] navigator.clipboard is undefined on Ubuntu 22.04

### ISSUE THREAD

**Issue by matthme** [tauri-apps/tauri#5835]
### Describe the bug

`navigator.clipboard` is undefined in tauri windows on Ubuntu 22.04, although:

* `enable_clipboard_access()` is used on the `WindowBuilder`
* It should be supported comparing [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard#browser_compatibility) and the list of [tauri webview versions for Linux](https://tauri.app/v1/references/webview-versions/#linux)

### Reproduction

Call `navigator.clipboard` in any console of a tauri window, built with or without `enable_clipboard_access()`.

### Expected behavior

`navigator.clipboard` is available, at least in windows built with `enable_clipboard_access()`.

### Platform and versions

```
Environment
  › OS: Ubuntu 22.04 X64
  › Node.js: 16.11.1
  › npm: 8.0.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.2
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.1,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.6,
  › wry [RUST]: 0.22.5,

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self'
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Vue.js
  › bundler: Vite

App directory structure
  ├─ scripts
  ├─ tests
  ├─ .git
  ├─ crates
  ├─ target
  ├─ docs
  ├─ dist
  ├─ node_modules
  ├─ src-tauri
  ├─ src
  ├─ .github
  ├─ .vscode
  └─ public
```

### Additional context

I intended to file this issue a while ago but didn't find it anymore (neither under "open" nor "closed") so I may have forgotten to file it after all. Apologies if it is in fact a duplicate.

**Comment by FabianLars** [comment]
> I intended to file this issue a while ago but didn't find it anymore

It was moved to wry: https://github.com/tauri-apps/wry/issues/719
