### ISSUE TITLE
[feat] Different handling for `input[type="number"]`

### ISSUE THREAD

**Issue by bicarlsen** [tauri-apps/tauri#5838]
### Describe the problem

Currently `<input type="number" />` elements with a  return `true` for [`is_empty()`](https://doc.rust-lang.org/nightly/alloc/string/struct.String.html#method.is_empty) on [`value()`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.HtmlInputElement.html#method.value) and `true` for [`is_nan()`](https://doc.rust-lang.org/nightly/std/primitive.f64.html#method.is_nan) on [`value_as_number()`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.HtmlInputElement.html#method.value_as_number)  if the field is left blank or a value that is not parsable as a number is entered. This can lead to an unintuitive experience for the user if they are allowed to leave the field blank, but should not be able to enter a value that can not be parsed as a number (e.g. `test`), as there is no way for the developer to distinguish between the two situations.

### Describe the solution you'd like

Either do not allow non-numeric input in `<input type="number" />` elements or return the raw input value of the field, even if it is not parsable as a number, when calling `value()` to allow the two situations (either an empty field, or unparsable input) to be distinguished and handled by the developer.

### Alternatives considered

One could verify user input using the [`input`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event) event, but this feels less ergonomic than having it handled natively.

### Additional context

I have only tested this in Tauri using Yew, and am not sure if this was a design decision to stay consistent with how other browsers handle the situation.

**Comment by amrbashir** [comment]
This is not something we control; It is just the HTML spec. Also note that custom validations for `<input>` should be done in your app using your favorite framework or manually and not inside tauri.
