### ISSUE TITLE
Tauri production build does not make http calls

### ISSUE THREAD

**Issue by UmashankarRahangdale** [tauri-apps/tauri#5849]
My tauri production build is unable to make normal http calls. getting following error when making a rest call over http.
Mixed Content: The page at 'https://tauri.localhost/login' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://xyz.com/login'. 
This request has been blocked; the content must be served over HTTPS.

I dont want my node server to be on https and other applications consume it and i dont want them to change anything.

**Comment by FabianLars** [comment]
Duplicate of #3007. Thanks for the report.

**Comment by prayag17** [comment]
Did you ever find aa fix for this issue?

**Comment by Valentim-Gab** [comment]
A client application using https cannot consume an api in http.

**Comment by Ghadi00** [comment]
Hello, I am having the same issue here on production did anyone find any solution?

**Comment by prayag17** [comment]
Use the http plugin for Tauri to make request

**Comment by JoseRupallan** [comment]
@prayag17 what do i do if i need to use src for an image tag

**Comment by prayag17** [comment]
@JoseRupallan you just need to import the image in your js/ts file like

`import imageName as 'path/to/image';`

And then use the imageName variable as the value for your source, this is not really dependent on the http plugin
