### ISSUE TITLE
Support writing binary file to local disk

### ISSUE THREAD

**Issue by rnons** [tauri-apps/tauri#585]
**Is your feature request related to a problem? Please describe.**
I want to write an image file to local disk. Currently tauri only provides a `writeFile` api for text file, also see [this comment](https://github.com/tauri-apps/tauri/pull/513#discussion_r392956379).

**Describe the solution you'd like**
There should be a `writeBinaryFile` api.

**Describe alternatives you've considered**

**Additional context**
I made PR #580 for this, @khionu [suggested](https://github.com/tauri-apps/tauri/pull/580#issuecomment-625372762) opening an issue for discussion. Because JSON is used to send data from JavaScript to Rust, I can think of two options:

1. JS ArrayBuffer -> JS base64 string -> JSON string -> Rust string -> Rust Vec[u8]
1. JS ArrayBuffer -> JS byte string -> JSON string -> Rust byte string -> Rust Vec[u8]

#580 currently uses the base64 approach, but since base64 uses more memory, we may want to look into the byte string approach. To do that, we need to introduce a new Rust dependency that supports byte string.

I don't have much experience with Rust, so it's very likely there are other approaches I'm not aware of.

**Comment by khionu** [comment]
I'm thinking that we should look into how we can get a Rust channel to be usable from JS land, so we could have a JS stream that feeds into a Rust BufReader that can then be used to write to a Rust File. This could be done two ways to help facilitate better APIs, and would prevent the need to serialize the file before writing. The command would then return a JS stream that is ready to write to a file.

**Comment by rnons** [comment]
Fixed by #580. Thanks.
