### ISSUE TITLE
[bug] App crashes when running standalone but doesn't when running from terminal

### ISSUE THREAD

**Issue by fardeem** [tauri-apps/tauri#5852]
### Describe the bug

I'm using the [rust-macios package](https://github.com/a-isaiahharvey/rust-macios) to access the users contacts list for my app. I have a button in the frontend that requests permission to access the contacts. When I build the app and run it, it crashes. But if I open it from the terminal it works. 

This is the error log. The full log is here: https://gist.github.com/fardeem/91564f69ff41fe8a77e61ccce1cdac87

I'm not sure how to fix this. Even when I add a `Info.plist` with the contact key, it still causes the app to crash.

```
Crashed Thread:        8  Dispatch queue: com.apple.root.default-qos

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000ff6df40be60
Exception Codes:       0x0000000000000001, 0x00000ff6df40be60

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [28319]

```

### Reproduction

1. Clone https://github.com/fardeem/crash-when-accessing-contacts
2. run `yarn tauri dev`
3. Confirm you can access contacts and the terminal outputs `access granted`
4. Build the app using `yarn tauri build`
5. Run the app standalone.
6. Notice that clicking the button crashes the app.

### Expected behavior

It wouldn't crash the app.

### Platform and versions

Environment
  › OS: Mac OS 13.0.1 X64
  › Node.js: 16.14.0
  › npm: 8.3.1
  › pnpm: 6.11.0
  › yarn: 1.22.15
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.2.2
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.2,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › bundler: Vite

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  └─ src

### Stack trace

```shell
https://gist.github.com/fardeem/91564f69ff41fe8a77e61ccce1cdac87
```

**Comment by fardeem** [comment]
Turns out I just needed to add a custom `info.plist` and some entitlements.plist. All working now!

**Comment by dukeeagle** [comment]
Hey there! Could you speak more to what you changed about `Info.plist` and `entitlements.plist` ? Thanks!

**Comment by fardeem** [comment]
Hi, i wrote about it here: https://www.fardeem.com/notes/accessing-macos-native-apis-for-tauri-apps
