### ISSUE TITLE
[bug] The program is still the old version after the automatic update is completed(only windows)

### ISSUE THREAD

**Issue by ppbl** [tauri-apps/tauri#5861]
### Describe the bug

On Windows, The program is still the old version after the automatic update is completed

### Reproduction

First, I set dialog to false

Then

Version release process
1. Github actions auto build
2. Manually download the installation package and upload it to my own server
3. Manual update latest.json(uplaod file)
4. Open app, click update button to trigger the update operation
frontend code
```tsx
await installUpdate()
await relaunch()
```
5. After the installation of the new version is completed, the application will restart automatically. It is still the old version

The same application macos is the same process, no problem
The package downloaded and installed manually by github actions is the correct version

### Expected behavior

After the automatic update is completed, the program should be a new version

### Platform and versions

windows10
windows11
rust 1.66
tauri 1.2.2

### Additional context

I'm sorry I didn't identify a specific problem, but it really affected me😅

But I have a guess. I don't know if it will help（Just a guess）

Is it possible that when the application is restarted, the new version has been downloaded but has not been replaced for some reasons?

（There is also a small problem. When the download is completed and restarted, a terminal window will pop up，only windows）

**Comment by ppbl** [comment]
The reason is found, because the windows.installMode is set to quiet, and then the installation fails silently without permission, but the subsequent restart logic executes normally

The terminal window will still appear (I saw that the script code set the windowstyle to hidden, and it still pops up. It's strange)

**Comment by FabianLars** [comment]
This is a drawback of the `quiet` option. For whatever reason it can't request elevated permission itself automatically in quiet mode. The docs are indeed not clear enough here: "Requires admin privileges if the installer does." does not clearly say that it can't request it itself.

In other words, the `quiet` mode can only really be used with per-user install modes (which is currently not supported, but will be in 1.3 with the new nsis target), or maybe if your app always runs in admin mode 🤔 

Edit: As far as i know this is a Windows or WiX limitation, not Tauri. i don't want to rule out the possibility that we could implement a workaround in Tauri tho.

**Comment by ppbl** [comment]
Thank you for your answer and the team's built-in updater👍, I have switched to `passive` now, Looking forward to future updates.

**Comment by Tdaine** [comment]
I ran into the same problem, can I stop it by catching an installUpdate() exception?
