### ISSUE TITLE
[bug] MIME type is conflated with Content-Type

### ISSUE THREAD

**Issue by matthme** [tauri-apps/tauri#5878]
### Describe the bug

If I intend to set the MIME type of an HTTP response via `.set_mimetype()` (https://docs.rs/tauri/latest/tauri/http/struct.Response.html#method.set_mimetype) it actually sets its full [*Content-Type*](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type): https://github.com/tauri-apps/tauri/blob/3dc38b150ea8c59c8ba67fd586f921016928f47c/core/tauri-runtime-wry/src/lib.rs#L297
where the MIME type is only part of, amongst charset and boundary.
This is mainly an issue of naming I think but one that leads to unexpected behavior.

### Expected behavior

If I use the `.set_mimetype` method it sets only the MIME type.
If a method is intended to set the content type it should be called `set_content_type`.

### Platform and versions

-

**Comment by amrbashir** [comment]
In 2.0, we will remove our custom http types and use http types from `http` crate

**Comment by lucasfernog** [comment]
Closed by #7754 where we removed our custom http types as Amr suggested.
