### ISSUE TITLE
[feat] How to integrate external binaries that include dependent libraries, how to add exclusion library scans to appimage or exclude paths that do not analyze dependent libraries

### ISSUE THREAD

**Issue by cosoc** [tauri-apps/tauri#5891]
### Describe the problem

How to integrate the jre runtime environment, I see that the document has an integrated executable binary, but jre has multiple dependent directories, how to integrate it. If you put the folder into the resource, the subsequent appimage will analyze the java dependency library. In fact, these jre folders come with them, which will cause packaging errors. The problem is that there is no library option to exclude appimage in the configuration file! In fact, the dependency analysis program document used can specify the options that are not excluded, but I don’t know how to solve this situation if the default generated file of the tauri configuration file appimage is changed ? The integrated external executable program should not be just a binary, it may have other directories! How to deal with this situation?

### Describe the solution you'd like

Provide appimage exclude library option Can copy entire directories when integrating executables to ensure dependencies are included instead of just the executable

**Comment by amrbashir** [comment]
> I see that the document has an integrated executable binary, but jre has multiple dependent directories

Can you give me the expected structure of the final binary folder?

Currently all resources are copied over to the root of the installed app. I already have plans to improve the resources system to allow copying over the resources to other places than the root of the app which may solve your issue but I need more info, for example:
```json
{
	"resources": {
		"path/to/original/resources": "path/in/the/final/binary/folder/relative/to/the/main/binary",
	}
}
```

**Comment by cosoc** [comment]
> 



> > 我看到文件有一个集合成的可执行二次制作文件，但是有多个依赖目录
> 
> 你能给我最终二次制作文件夹的预期结果吗？
> 
> 所有资源复制到安装应用应用的根目录中。已经计划计划改进改进改进资源资源资源系统以以允许允许将将资源资源资源复制复制到到到到应用应用程序根程序根目录目录位置位置位置位置位置位置位置信息，例如：
> 
> ```json
> {
> 	"resources": {
> 		"path/to/original/resources": "path/in/the/final/binary/folder/relative/to/the/main/binary",
> 	}
> }
> ```



The java runtime environment has multiple directories

![image](https://user-images.githubusercontent.com/19447682/209286806-cdcc2c4f-a08e-4cc7-b118-2fdfaf8124da.png)


I think externalBin should copy all the files in the specified directory, and should not require that binaries need to distinguish the names at the end of the platform to be legal. This request should be customized. Developers should know that they write their own scripts to copy binaries of different platforms during compilation. The tauri framework should not have name requirements, because it may rely on a third-party running environment, such as Java, Or customized software that contains its own dependent directory


My business requirement is that tauri is the main program, other functions are provided in the form of plug-ins, and plug-ins interact with the body in the form of ipc. Plug ins do not specify the specified development language. As long as users implement the agreed rpc interaction method, they can access the main program, and the development quality of peripheral plug-in services will not affect the state of the main program. This will involve integrating various operating environments, For example, Java's jre node and other external plug-in applications that rely on the jvm. I think tauri can load customized plug-ins, but I think this design improves the threshold for users to develop extensions. If tarui can copy all the folders and exclude the dependency of these peripheral applications when packaging the appimage in the next step, the whole design pattern will be able to run.

**Comment by FabianLars** [comment]
Sounds a bit like you're looking for the resources feature: https://tauri.app/v1/guides/building/resources it will not modify the files in any way and the appimage bundler should ignore it too.

**Comment by amrbashir** [comment]
Yeah, sounds like resources is a good fit for this.
