### ISSUE TITLE
Can frameless window be "Moveable"?

### ISSUE THREAD

**Issue by Agoldstein1** [tauri-apps/tauri#5909]
Hi, 
I create a frameless window by setting decorations=false and transparent=true in tauri.conf.json.
I need the window to be moveable.
the user should have the ability to move the window to any position.
How can I do it?

thanks!

**Comment by metkm** [comment]
You can do it from frontend. https://tauri.app/v1/guides/features/window-customization#creating-a-custom-titlebar
