### ISSUE TITLE
[feat] Disable mouse event when building windows on Linux

### ISSUE THREAD

**Issue by wusyong** [tauri-apps/tauri#5913]
### Describe the problem

On linux, there might have burst mouse events periodically and this could block gtk's main eventloop.
For more information, please see https://github.com/tauri-apps/tao/issues/635

### Describe the solution you'd like

With latest tao patch, we can call [with_cursor_moved_event](https://docs.rs/tao/latest/tao/platform/unix/trait.WindowBuilderExtUnix.html#tymethod.with_cursor_moved_event) and set it to false as workaround. Mouse event isn't useful since webview itself can already detect such event.

### Alternatives considered

Other alternatives are described in https://github.com/tauri-apps/tao/issues/635.
Please comment there if you have more ideas.

**Comment by shogohida** [comment]
Hi @wusyong, can I work on this? I'd like to contribute but I will need some help because I'm new to Tauri

**Comment by wusyong** [comment]
@shogohida I'm glad you are interested. You'll need to add a method for [WindowBuilderWrapper](https://github.com/tauri-apps/tauri/blob/dev/core/tauri-runtime-wry/src/lib.rs#L708) specific to linux (and other unix except macos). And then call it during `with_config` call.

**Comment by shogohida** [comment]
@wusyong 
Thanks for your comment! I created a pull request according to your advice. Please check it

https://github.com/tauri-apps/tauri/pull/6025
