### ISSUE TITLE
[bug] cant run command: npm run tauri dev

### ISSUE THREAD

**Issue by unnaturalistic** [tauri-apps/tauri#5916]
### Describe the bug

cant use `npm run tauri dev` 
returns with error:

> **thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', src\interface\rust.rs:762:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace**

### Expected behavior

after created application and using
`npm run tauri dev`
supposed to open the application.

### Platform and versions

> Environment
  › OS: Windows 10.0.19042 X64
  › Webview2: 108.0.1462.54
  › MSVC: 
  › Node.js: 18.12.1
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: Not installed!
  › rustc: Not installed!
  › cargo: Not installed!
  › Rust toolchain: 

Packages
  › @tauri-apps/cli [NPM]: 1.2.2
  › @tauri-apps/api [NPM]: 1.2.0
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected end of input while parsing minor 
version number")', src\info.rs:502:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Additional context

after using `npm run tauri info` after script output it returns with the same error at the end

> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected end of input while parsing minor 
version number")', src\info.rs:502:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by FabianLars** [comment]
You don't have rust installed, did you follow the setup guides? https://tauri.app/v1/guides/getting-started/prerequisites
If you did all this then you may have to restart your system.
