### ISSUE TITLE
npm run tauri dev issue

### ISSUE THREAD

**Issue by Capta1nCool** [tauri-apps/tauri#5920]
### Describe the bug

hello there,
Whenever I'm trying to run the command "npm run tauri dev" after setting up the project with "npx create-tauri-app" its throwing this error. 
![image](https://user-images.githubusercontent.com/69457423/209606739-7283feb5-d96a-4ed0-b9c9-20effc64c981.png)

### Reproduction

1. npx create-tauri-app
2. cd .\folder\
3. npm install
4. npm run tauri dev

### Platform and versions

› OS: Windows 10.0.19045 X64
  › Webview2: 108.0.1462.54
  › MSVC: 
      - Visual Studio Build Tools 2022
  › Node.js: 16.15.1
  › npm: 8.11.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: Not installed!
  › cargo: Not installed!
  › Rust toolchain:

**Comment by FabianLars** [comment]
Looks like it can't find your Rust installation (it says "not installed!" for rustc and cargo). You can double check that with `rustup show`. In case it's not installed you can do it for example with `rustup toolchain install stable-msvc`. You may also have to restart your system for all changes to take effect.

**Comment by Capta1nCool** [comment]
`info: syncing channel updates for 'stable-x86_64-pc-windows-msvc
info: latest update on 2022-12-15, rust version 1.66.0 (69f9c33d7 2022-12-12)
stable-x86_64-pc-windows-msvc (default)
**(rustc does not exist)**`


this is what rustup show says everything seems fine but what that rustc doesn't exist means?

**Comment by FabianLars** [comment]
> but what that rustc doesn't exist means?

I never saw it in this context, but rustc is the rust compiler and therefore the most important part.

Maybe try uninstall the toolchain first via `rustup uninstall stable-x86_64-pc-windows-msvc` and then installing it again (maybe with the --force flag)
If that doesn't work try re-installing rustup itself, by running `rustup self uninstall` and then re-running the setup.
