### ISSUE TITLE
[widnow10]yarn tauri build error

### ISSUE THREAD

**Issue by wwmmzz** [tauri-apps/tauri#5925]
### Describe the bug
```
     Running [tauri_bundler::bundle::windows::msi::wix] candle for "main.wxs"
     Running [tauri_bundler::bundle::common] Command `C:\Users\a\AppData\Local\tauri/WixTools\candle.exe  -arch x64 main.wxs -dSourceDir=C:\Users\a\Desktop\tauri-app\src-tauri\target\release\tauri-app.exe`
Windows Installer XML Toolset Compiler version 3.11.2.4516
Copyright (c) .NET Foundation and contributors. All rights reserved.

main.wxs
     Running [tauri_bundler::bundle::windows::msi::wix] light to produce C:\Users\a\Desktop\tauri-app\src-tauri\target\release\bundle/msi/tauri-app_0.0.0_x64_en-US.msi
     Running [tauri_bundler::bundle::common] Command `C:\Users\a\AppData\Local\tauri/WixTools\light.exe  -ext WixUIExtension -ext WixUtilExtension -o C:\Users\a\Desktop\tauri-app\src-tauri\target\release\wix\x64\output.msi -cultures:en-us -loc C:\Users\a\Desktop\tauri-app\src-tauri\target\release\wix\x64\locale.wxl *.wixobj`
Windows Installer XML Toolset Linker version 3.11.2.4516
Copyright (c) .NET Foundation and contributors. All rights reserved.

C:\Users\a\Desktop\tauri-app\src-tauri\target\release\wix\x64\main.wxs(179) : warning LGHT1076 : ICE03: String overflow (greater than length permitted in column); Table: CustomAction, Column: Target, Key(s): DownloadAndInvokeBootstrapper
C:\Users\a\AppData\Local\Temp\pvk51i2d\output.msi : error LGHT0204 : ICE39: Bad Type in Summary Information Stream for PID_AUTHOR.
C:\Users\a\Desktop\tauri-app\src-tauri\target\release\wix\x64\main.wxs(30) : warning LGHT1076 : ICE40: REINSTALLMODE is defined in the Property table. This may cause difficulties.
C:\Users\a\Desktop\tauri-app\src-tauri\target\release\wix\x64\main.wxs(103) : warning LGHT1076 : ICE57: Component 'CMP_UninstallShortcut' has both per-user and per-machine data with an HKCU Registry KeyPath.
C:\Users\a\Desktop\tauri-app\src-tauri\target\release\wix\x64\main.wxs(32) : warning LGHT1076 : ICE61: This product should remove only older versions of itself. No Maximum version was detected for the current product. (WIX_UPGRADE_DETECTED)
       Error [tauri_cli_node] failed to bundle project: error running light.exe: error running light.exe: `failed to run C:\Users\a\AppData\Local\tauri/WixTools\light.exe`
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
### Reproduction

yarn tauri build

### Platform and versions

➜ tauri-app  yarn tauri info
yarn run v1.22.10
$ tauri info

Environment
  › OS: Windows 10.0.19045 X64
  › Webview2: 108.0.1462.54
  › MSVC:
      - Visual Studio 15 ???? 2017
      - Visual Studio Community 2019
      - Visual Studio ???? 2019
  › Node.js: 16.15.1
  › npm: 8.12.2
  › pnpm: 6.26.1
  › yarn: 1.22.10
  › rustup: 1.25.1
  › rustc: 1.66.0
  › cargo: 1.66.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.2.2
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.3,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React
  › bundler: Vite

App directory structure
  ├─ .vscode
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
Done in 126.97s.

### Additional context

Tried the following steps, but it still doesn't work

1. cargo install tauri-cli --git https://github.com/tauri-apps/tauri --branch dev
   cargo tauri build

2.  add "windows": {
  "wix": {
    "language": "zh-CN"
  }
}

**Comment by FabianLars** [comment]
Did you run it with the verbose flag like `yarn tauri build --verbose`? If not, please do so and provide the logs you get.

Also the only potentially interesting line from the logs you posted is about `PID_AUTHOR`, what is your `bundle.identifier` and `bundle.publisher` set to in `tauri.conf.json`?

**Comment by wwmmzz** [comment]
Thanks Reply, the log I post  is log of yarn tauri build --verbose.

follow your prompts, I change the identifier in tauri.conf.json, not set publisher. it work now.

but still dont understand why identifier like  www.111.com not working. mybe some tips?

**Comment by FabianLars** [comment]
> but still dont understand why identifier like [www.111.com](http://www.111.com/) not working. mybe some tips?

The first thing i found was this: <https://github.com/oleg-shilo/wixsharp/issues/95#issuecomment-311182859> which make it sound like numeric authors/publishers are not allowed in msi installer.

Tauri will use the middle part of your bundle id as the author if bundle.publisher is not set.

**Comment by wwmmzz** [comment]
thank you so much ,  it help a lot.
