### ISSUE TITLE
[feat] How to modify the right-click menu style of system tray

### ISSUE THREAD

**Issue by DWHengr** [tauri-apps/tauri#5926]
### Describe the problem

Modify the style of the tray menu, such as the background color of the tray menu, the icon of the tray menu item, etc

### Describe the solution you'd like

```
SystemTrayMenu.set_bg_color() or SystemTrayMenu.set_css({backgroundColor:""})
CustomMenuItem.set_icon()
etc...
```
Hope to provide a universal solution. Or similar implementation scheme.

**Comment by amrbashir** [comment]
This is not possible, it is a native OS menu. If you're targeting macOS and Windows without Linux, you can listen to the tray click event and show a small window without decorations where you can build your menu using HTML/CSS/JS. 

As for the icons, it will be added in v2.
