### ISSUE TITLE
[bug] <a> tag with taget="_blank" no reaction in WebviewWindow 

### ISSUE THREAD

**Issue by puqiulin** [tauri-apps/tauri#5931]
### Describe the bug

Click \<a\> tag like \<a href="xxx" target="_blank"\> did not open in default browser in window which create by @tauri-apps/api/window WebviewWindow, but it work in main window, im confusing...

### Reproduction

1. Create a tauri app
2. Create a new WebviewWindow which contain \<a href="xxx" target="_blank"\>
3. Click the \<a\>

### Expected behavior

The url in \<a\> tag open in default browser

### Platform and versions

npm run tauri info:

Environment
  › OS: Mac OS 13.0.0 X64
  › Node.js: 18.0.0
  › npm: 9.1.3
  › pnpm: 7.8.0
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.66.0
  › cargo: 1.66.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.2.2
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.1,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.6,
  › wry [RUST]: 0.22.5,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React
  › bundler: Vite

App directory structure
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .vscode
  ├─ .idea
  └─ src

### Additional context

https://user-images.githubusercontent.com/30133768/209786026-6ff91d29-7f96-4772-83b2-d3dd9d5eb45b.mov

Pseudocode like:
```html
import { WebviewWindow} from "@tauri-apps/api/window";
<div className="container">
    <h1>Welcome to Tauri!</h1>

    &lt;a&gt; tag with target="blank" in main window ⬇️
    <a href="https://tauri.app/v1/api/config/#allowlistconfig.window" target="_blank">
        <code>tauri.allowlist.window</code>
    </a>

    <button type="button" onClick={() => {
        new WebviewWindow("test", {
            url: "https://tauri.app/v1/api/js/window",
        });
    }}>
        New Window
    </button>
</div>
```
tauri.conf.json:
```json
{
  "build": {
    "beforeDevCommand": "yarn dev",
    "beforeBuildCommand": "yarn build",
    "devPath": "http://localhost:1420",
    "distDir": "../dist"
  },
  "package": {
    "productName": "tauri-test",
    "version": "0.0.0"
  },
  "tauri": {
    "allowlist": {
      "all": true
    },
    "bundle": {
      "active": true,
      "category": "DeveloperTool",
      "copyright": "",
      "deb": {
        "depends": []
      },
      "externalBin": [],
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "identifier": "com.tauri.dev",
      "longDescription": "",
      "macOS": {
        "entitlements": null,
        "exceptionDomain": "",
        "frameworks": [],
        "providerShortName": null,
        "signingIdentity": null
      },
      "resources": [],
      "shortDescription": "",
      "targets": "all",
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "security": {
      "csp": null
    },
    "updater": {
      "active": false
    },
    "windows": [
      {
        "fullscreen": false,
        "height": 600,
        "resizable": true,
        "title": "tauri-test",
        "width": 800
      }
    ]
  }
}
```

**Comment by amrbashir** [comment]
You are opening a remote URL and tauri APIs are not injected into remote URLs.

**Comment by puqiulin** [comment]
> You are opening a remote URL and tauri APIs are not injected into remote URLs.

Thanks for the explanation ! I got it 😃

**Comment by puqiulin** [comment]
> 
The problem fixed with inject js which hook onclick event to get the href, But recently i run this code on windows with no change and no inject ,it works...maby the webview perform different on windows and macos?

**Comment by ElectronMB** [comment]
Hi @one0day You said that you fix the issue with inject js which hook onclick event to get the href, so can you please share more detail about that how to integrate it because I facing the same issue I load the remote URL on the tauri app, In this URL have open popup window functionality but that functionality not work in macos but it works in windows without any change in code. so can you please provide a reference on how to fix that?

**Comment by puqiulin** [comment]
> 

@ElectronMB 
On macos,if you whant click a tag with "__blank" props in new windows, you should injecte js which hook all a tag with "__blank", change it behavior.

The js code roughly like:
```js
function transformCallback(callback = () => {
}, once = false) {
    const identifier = uid();
    const prop = `_${identifier}`;
    Object.defineProperty(window, prop, {
        value: (result) => {
            if (once) {
                Reflect.deleteProperty(window, prop);
            }
            return callback(result)
        },
        writable: false,
        configurable: true,
    })
    return identifier;
}

async function invoke(cmd, args) {
    return new Promise((resolve, reject) => {
        if (!window.__TAURI_POST_MESSAGE__) reject('window.__TAURI_POST_MESSAGE__ does not exist!');
        const callback = transformCallback((e) => {
            resolve(e);
            Reflect.deleteProperty(window, `_${error}`);
        }, true)
        const error = transformCallback((e) => {
            reject(e);
            Reflect.deleteProperty(window, `_${callback}`);
        }, true)
        window.__TAURI_POST_MESSAGE__({
            cmd,
            callback,
            error,
            ...args
        });
    });
}

window.invoke = invoke;
window.transformCallback = transformCallback;

if (document.readyState === "complete" || document.readyState === "interactive") {
  const hookClick = (e) => {
      const origin = e.target.closest("a");
      if (origin && origin.href && origin.target === '_blank') {
          let param = {url: origin.href}}
          invoke('new_window', param);
      }
  }
  document.addEventListener("click", hookClick);
}
````


And in rust code, when you create new window, use `initialization_script` to injecte js 
```rust
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Payload {
    pub url: String,
}
#[command]
pub async fn new_window(payload:Payload)->Result<Window<Wry>>{
  Ok(WindowBuilder::new(
      &Handler::app_handle(),
      "label",
      WindowUrl::App(payload.url.into())
  )
  .title("xxx")
  .initialization_script(include_str!("test.js"))
  .build()?)
}
```
In this way, click the a tag with "__blank" will open new window, maby there is a concise way, if yours found one, please let me know 😄

**Comment by ElectronMB** [comment]
Hello, @one0day Thanks for the quick reply, Actually I don't have the code for that remote URL so unable to apply your solution in code do you have any other ideas to do with the main.rs file?
actually, I created the tauri project with vanilla JS and include it below code into the main.rs file 
```
fn main() {
  use tauri::Manager;
  tauri::Builder::default()

    .setup(|app| {
      app.get_window("main").unwrap().eval("window.location.replace('https://www.dropbox.com/login')").unwrap();
      Ok(())
    }).run(tauri::generate_context!())
    .expect("error running tauri app");
}
```

It is just an example when this URL is open in some browser and then you see the apple login option and click on it it's open a popup window but when you load this URL into the tauri app like the above code and click on the apple login button then it's not open popup window in macOS.
That's the issue I am facing in macOS if you have any solution let me know.

**Comment by puqiulin** [comment]
> Hello, @one0day Thanks for the quick reply, Actually I don't have the code for that remote URL so unable to apply your solution in code do you have any other ideas to do with the main.rs file? actually, I created the tauri project with vanilla JS and include it below code into the main.rs file
> 
> ```
> fn main() {
>   use tauri::Manager;
>   tauri::Builder::default()
> 
>     .setup(|app| {
>       app.get_window("main").unwrap().eval("window.location.replace('https://www.dropbox.com/login')").unwrap();
>       Ok(())
>     }).run(tauri::generate_context!())
>     .expect("error running tauri app");
> }
> ```
> 
> It is just an example when this URL is open in some browser and then you see the apple login option and click on it it's open a popup window but when you load this URL into the tauri app like the above code and click on the apple login button then it's not open popup window in macOS. That's the issue I am facing in macOS if you have any solution let me know.

its looks like you want set default index url when tauri app start, if so, you can set [window.url](https://tauri.app/v1/api/config#windowconfig.url) , or you just init main window in setup function, and inject the js when create it
```rust 
fn main() {
  use tauri::Manager;
  tauri::Builder::default()
    .setup(|app| {
      WindowBuilder::new(
       &app.handle(),
        "label",
        WindowUrl::App("https://www.dropbox.com/login".into())
      )
      .title("xxx")
      .initialization_script(include_str!("test.js"))
      .build()?;
      Ok(())
    }).run(tauri::generate_context!())
    .expect("error running tauri app");
}
```
