### ISSUE TITLE
[feat] Get preferred language

### ISSUE THREAD

**Issue by John0x** [tauri-apps/tauri#5939]
### Describe the problem

I need to able to get the os preferred language in my web application.
From what I've read the typical navigator.language doesn't work.

### Describe the solution you'd like

Make navigator.language work or provide a js API call

**Comment by yunylz** [comment]
any updates?

**Comment by RobertBorg** [comment]
> any updates?

doesn't https://v2.tauri.app/reference/javascript/os/#locale work for you?
