### ISSUE TITLE
Catch-22 with dropping filepaths into specific HTML Input elements on Windows

### ISSUE THREAD

**Issue by MauricePasternak** [tauri-apps/tauri#5941]
### Describe the bug

I am aware of [previous discussions and findings](https://github.com/tauri-apps/tauri/issues/2768#issuecomment-997169108) surrounding this issue. The behavior of the API on Windows prevents stable drag & drop of files on Windows in particular.

The following observations are made on Windows:

- If `tauri.conf.json` features: `tauri.windows.fileDropEnabled` as being `true`. Then: 
    - window-wide events like 'tauri://file-drop' can be responded to. 
    - onDragEnter and onDragLeave become unresponsive. This prevents accurate detection of which HTML element the aforementioned window-wide event corresponds to
    - onMouseEnter and onMouseLeave are, as expected, not available backups during a drag operation
    - Therefore, although users are provided with filepath data upon a drop event, they cannot accurately detect which element this data should interact with

- If `tauri.conf.json` features: `tauri.windows.fileDropEnabled` as being `false`. Then: 
    - onDragEnter and onDragLeave become responsive. Great, it is now easy to know which element should receive the data.
    - the aforementioned window-wide events cannot be responded to.
    - onDrop obviously does not have the filepath data
    - Therefore, the inverse of the previous scenario occurs: users know where data should be deposited to, but can't access the data.

I am certain hacks exist to circumvent this issue. For example, in a React project, it is possible to:
- use a useRef set to a boolean value as a variable for answering the question "does the drop event apply to me?"
- use the onMouseLeave event to set the value above to false
- use the onMouseEnter event which should trigger "very quickly" upon letting the mouse button go during a drop event to set the value to true
- to minimize the chances of a race condition occurring between onMouseEnter and the callback of 'tauri://file-drop', use a setTimeout on the latter for a value of, say, 50ms. Too short and the race condition risk increases. Too long and the user can technically move the mouse out of the element before the callback starts.

However, a more stable approach is necessary by, for example, introducing additional data into  'tauri://file-drop' et al. or allowing for onDragEnter/Leave to be active when  `tauri.windows.fileDropEnabled` is `true`.

### Reproduction

1. Create a project on Windows.
2. Ensure `tauri.windows.fileDropEnabled` is specified in `tauri.conf.json`
3. Make a couple of InputHTML elements
4. For each element, register for "tauri://file-drop" events.
5. Implement your framework's preferred logic for tracking elements (i.e. useRef hook in a React setup).
6. Drag a folder from FileExplorer to any of the input elements and drop it. Only that input element should take on the value of the filepath dropped in.

### Platform and versions

Environment
  › OS: Windows 10.0.19045 X64
  › Webview2: 108.0.1462.54
  › MSVC: 
      - Visual Studio Build Tools 2019
  › Node.js: 16.16.0
  › npm: 8.13.2
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.66.0
  › cargo: 1.66.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.2
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.3,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React
  › bundler: Vite

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ dist
  ├─ node_modules
  ├─ src
  └─ src-tauri

**Comment by amrbashir** [comment]
> However, a more stable approach is necessary by, for example, introducing additional data into 'tauri://file-drop' et al.

I think this might be possible, maybe the event can have the mouse position so you can call `document.elementFromPoint`

> allowing for onDragEnter/Leave to be active when `tauri.windows.fileDropEnabled` is `true`.

Unfortunately, the webview on all platforms has the same limitation and we can't have both.

**Comment by JokerQyou** [comment]
If I understand it correctly, this issue is the same as #3063.

**Comment by amrbashir** [comment]
yeah, thanks, I will close in favor of #3063 then
