### ISSUE TITLE
Let tauri::api::process::Command upgrade the operation permission

### ISSUE THREAD

**Issue by Sparkel-wsl** [tauri-apps/tauri#5943]
### Describe the problem

When I use the tauri::api::process::Command::new("sc.exe").args(["create MyService binpath= D:\\MyService.exe"]) command in windows system, the feedback is [SC] OpenSCManager fails. 5 Access is denied.

### Describe the solution you'd like

Let tauri::api::process::Command upgrade the operation permission

### Additional context

tauri::api::process::Command::new("sc.exe").args(["create","MyService","binpath= E:\\MyService.exe"]) 
[SC] OpenSCManager fails. 5 Access is denied.

**Comment by amrbashir** [comment]
you need to either start your app in Admin mode or use `cmd` or `powershell` to ask the user to give admin permissions:
```rs
Command::new("powershell").args(["-Command","Start-Process sc.exe -Verb runas -ArgumentList @('create', 'MyService', 'binpath= E:\MyService.exe'"])
```

**Comment by Sparkel-wsl** [comment]
> 您需要以管理员模式启动您的应用程序或使用`cmd`或`powershell`要求用户授予管理员权限：
> 
> ```rust
> Command::new("powershell").args(["-Command","Start-Process sc.exe -Verb runas -ArgumentList @('create', 'MyService', 'binpath= E:\MyService.exe'"])
> ```

Thank you for your reply. I am still learning
