### ISSUE TITLE
[feat] Shift click on taskbar icon to create new window

### ISSUE THREAD

**Issue by abose** [tauri-apps/tauri#5951]
### Describe the problem

In Windows, shift-clicking on a taskbar icon will launch another instance of the app. Is there a way to do that in a Tauri window?  I couldn't find it in the docs/search.

Attached screen recording below:

![shift click](https://user-images.githubusercontent.com/5336369/210153557-a4535fbc-b67e-409b-8ca3-917ebbeeaadb.gif)

### steps:
1. Open  a Tauri demo app in windows.
2. Press `Shift` key and click on the taskbar icon.
3. Observer that nothing happens

### Expected behavior:
Another window/app instance should be opened (Or an API to control this behavior).
### Describe the solution you'd like

Shift-Click on taskbar APIs in Tauri.

**Comment by amrbashir** [comment]
Shift click your app icon in the taskbar is the same as opening your app second time. If you want to change the behavior to spawn a new window, then use a single-instance plugin like [`tauri-plugin-single-instance`](https://github.com/tauri-apps/tauri-plugin-single-instance/) or [`tauri-plugin-highlander`](https://github.com/ioneyed/tauri-plugin-highlander).

**Comment by FabianLars** [comment]
@amrbashir the problem is that shift click or middle mouse click has no effect in tauri apps. It does not spawn a new instance, which is the wanted behavior here.

p.s. i tested this locally when we talked about it on discord, both tauri dev and tauri build, the latter before and after installing the msi

**Comment by amrbashir** [comment]
@FabianLars Can you please try again, I just tried it, and it just works and There is no special handling for this as far as I researched. 
Here is what I tested using `examples/api`: 
1. Running the app from `target/release` -> Doesn't work
2. Create a shortcut for the `target/release` app and run the shortcut -> Works
3. Install the app and run the exe directly from the installation directory -> Works
4. Install the app and run the shortcut in the start menu -> Works

**Comment by abose** [comment]
@amrbashir The problem is that pressing shift-click on the taskbar icon should open another instance of the app. follow these ### steps:
1. Open  a Tauri demo app in windows.
2. Press `Shift` key and click on the taskbar icon.
3. Observer that nothing happens

### Expected behavior:
Another window/app instance should be opened (Or an API to control this behavior).

**Comment by FabianLars** [comment]
@amrbashir you're right, it works sorry. I think i only tested debug builds (tauri build --debug) which don't work. (probably because of some identifier mismatch because of the terminal wrapper?)
