### ISSUE TITLE
[bug] fs scope not working with LTO-tape

### ISSUE THREAD

**Issue by Sozialarchiv** [tauri-apps/tauri#5954]
### Describe the bug

I am using a LTO-tape library from HP. On windows I can map the tape library to a drive letter (like an usb disk).

Even I am using the fs scope ["**"], I get always the warning that the path (F:\data) is not in the scope, if I try to access the files on the tape. With all other file locations (computer Hd, usb disks, ...) everything works fine.

The problem is definitely on the tauri side. I create my own Invoke commands (e.g. to rename a file) and with this ones i can access the files on the tape.

I known the hardware setting is quite rare. But maybe it would be alreadya solution to give a possibility to deactivate the fs scope test.

### Expected behavior

Files should be accessible.

### Platform and versions

Windows Server 2019
Tauri: 1.2.2

### Additional context

tauri config :

```
"allowlist": {
      "all": true,
      "fs": {
        "scope": ["**"]
      },
      ...
}
```

**Comment by amrbashir** [comment]
Can you give me the output of the `fs::canonicalize` on a path on the LTO-tape?

**Comment by Sozialarchiv** [comment]
After an update to 1.4 I can not reproduce the issue anymore.
