### ISSUE TITLE
[bug] Auto-reload / hot-reload moves focus away from the code editor

### ISSUE THREAD

**Issue by chuanqisun** [tauri-apps/tauri#5956]
### Describe the bug

Coming to Tauri as web dev, I really enjoyed the ergonomics from auto-reload. I'm filing this bug in the hope that it can become more seamless.

Currently, it is causing some friction because whenever I save a cargo-managed file in my editor, cargo would re-compile and a few seconds later, the web view would reload and moves the focus from the code editor to the web view. Because the re-compile time is unpredictable, I would lose focus after an unpredictable interval, which is quite annoying.

EDIT: additional info
- vite hot-reload does not disrupt the focus. The issue can be narrowed down to cargo.
- I just tried using vscode and its built-in terminal. Same issue. So we can rule out Windows Terminal/tmux/neovim. It's most likely an OS level window management issue
- I noticed that as soon as I save the file, the WebView is killed while cargo is recompiling. I'm not sure if that is by-design. I'd expect the WebView to remain open until it can be replaced by the new one. I imagine the focus problem can be solved if the WebView can preserve its identity instead of being closed and reopened. But I might be asking for too much :)

EDIT 2: additional info about my `main.rs`. There is no focus manipulation logic
```rs

fn main() {
    cfg::init().unwrap();
    db::init().unwrap();

    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![
            cmd::add_bookmark,
            cmd::create_index,
            cmd::list_bookmarks,
            cmd::patch_index
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

```

### Reproduction

My setup
- OS: gWSL inside Windows 11 
- IDE: Windows terminal + tmux + neovim
- Renderer: webkitgtk inside gWSL
- I'm using vite to handle the javascript bundling

Repro steps
- Open any project file in neovim, `:w` to write to disk
  - To eliminate vite as the cause, do not touch vite managed content. Consider write to `main.rs`.
  - Observe: WebView is closed immediately
- Wait for cargo to recompile
- Observe: WebView is opened
- Observe: **The WebView will move focus away from neovim**

### Expected behavior

The auto-reload should happen in the background. I'd expect the same dev experience as a vite developer

### Platform and versions

<details>
<summary>View platform info dump</summary>
<pre>
<code>Environment
  › OS: Ubuntu 22.04 X64
  › Node.js: 18.12.1
  › npm: 9.1.2
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.66.0
  › cargo: 1.66.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu

Packages
  › @tauri-apps/cli [NPM]: 1.2.2
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.3,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › bundler: Vite

App directory structure
  ├─ node_modules
  ├─ src
  ├─ .git
  ├─ dist
  ├─ .github
  ├─ src-tauri
  └─ public
</code>
</pre>
</details>

**Comment by amrbashir** [comment]
This seems to be just the normal/intended behavior. When a rust related file changes, the app needs to be recompiled and we can't keep the old app alive because it will hold a lock on the file and then the new app won't be able to compile. 

I know where the frustration comes from but unfortunately it is something that all compiled languages suffer of, there is no fine-grained reloading like web development HMR.

As for the focus stealing, you can set `focus: false` in tauri.conf.json while developing or if you are creating the window programmatically, you can disable the focus in development/debug builds like this:
```rs
let builder = tauri::WindowBuilder::new(app, "label", tauri::WindowUrl::App("index.html".into()));
#[cfg(debug_assertions)]
builder = builder.focus(false);
let window = builder.build()?;
```

**Comment by chuanqisun** [comment]
Thanks @amrbashir. Totally understand the constraints here. I'm trying your suggested workaround but it's still stealing focus. Instead of `focus(false)`, I used `focused(false)`, which I believe is the function you are referring to.

```rs
    tauri::Builder::default()
        .setup(|app| {
            let mut builder =
                tauri::WindowBuilder::new(app, "local", tauri::WindowUrl::App("index.html".into()));

            // Do not auto-focus during development
            #[cfg(debug_assertions)]
            {
                builder = builder.focused(false);
            }

            builder.build()?;

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");

```

**Comment by amrbashir** [comment]
@chuanqisun yeah, I meant `focused`, I forgot that `focus` is deprecated and is just there so we don't break existing code.

**Comment by chuanqisun** [comment]
Thank you @amrbashir. Would you consider reopen this issue or maybe suggest some other workaround? The `fn focused()` did not prevent focus stealing. The code I pasted above had no effect.
