### ISSUE TITLE
[docs] missing source code of `tauri_runtime_wry::Window` and `tauri_runtime_wry::WindowId`

### ISSUE THREAD

**Issue by CGQAQ** [tauri-apps/tauri#5965]
![image](https://user-images.githubusercontent.com/15936231/210295146-5b3fb682-2774-4c40-8169-1c54b500e8e2.png)
![image](https://user-images.githubusercontent.com/15936231/210295174-e6ff097a-ca2f-42df-bb63-bf29758cae71.png)

Where is the `tauri_runtime_wry::Window` and `tauri_runtime_wry::WindowId`'s source code? did I miss something?

![image](https://user-images.githubusercontent.com/15936231/210295317-5bb72b5a-2321-41dc-9021-67a142a1eed8.png)
I need the WindowId, but could not find a way to get it from `tauri::Window`, which was on_window_event provided. And then I tried to see the source code, but couldn't find any

**Comment by CGQAQ** [comment]
Basically, I want to try to solving the #2549 by sending redraw event after `resize`, don't know if it will work

**Comment by amrbashir** [comment]
`tauri_runtime_wry::Window` and `tauri_runtime_wry::WindowId` are re-exports of `wry::application::Window` and `wry::application::WindowId` which are re-exports of `tao::window::Window` and `tao::window::WindowId`
