### ISSUE TITLE
[bug] IME window is not positioning correctly on tauri

### ISSUE THREAD

**Issue by glyh** [tauri-apps/tauri#5986]
### Describe the bug

![image](https://user-images.githubusercontent.com/12870742/210628314-321349dc-95e0-4078-90c3-61eefec6ea70.png)

### Reproduction

1. use sway on linux
2. install fcitx5
3. create-tauri-app with cljs template
4. run tauri
5. type anything that requires IME in the box

### Expected behavior

the selection window should be positioned at the input area

### Platform and versions

> ed@0.0.0 tauri
> tauri info

Environment
  › OS: Arch Linux Rolling Release X64
  › Node.js: 19.3.0
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.66.0
  › cargo: 1.66.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.2
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.3,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../public
  › devPath: http://localhost:1420/
  › framework: React

App directory structure
  ├─ src-tauri
  ├─ .vscode
  ├─ public
  ├─ src
  ├─ node_modules
  └─ .shadow-cljs

### Stack trace

```shell
None
```

### Additional context

None

**Comment by heddxh** [comment]
Same here, every tauri program will happen.

**Comment by krokosik** [comment]
I see that a fix was release with WRY 0.29.0. Is it possible to use that version without upgrading Tauri to v2?

**Comment by FabianLars** [comment]
No, the fix would have to be backported to 0.24 to be able to use it in tauri v1.
