### ISSUE TITLE
[bug] Invalid value for `invoke` with enum that contains `Option` | Yew

### ISSUE THREAD

**Issue by bicarlsen** [tauri-apps/tauri#5993]
### Describe the bug

When passing an `enum` that can take an `Option` value to `invoke` I receive the error
> unexpected exception: JsValue("invalid args `greeting` for command `greet`: invalid value: map, expected map with a single key"

if the value is `None`. Everything works if the value is a `Some` variant.

### Reproduction

MRE at [https://github.com/bicarlsen/tauri-invalid-args-mre](https://github.com/bicarlsen/tauri-invalid-args-mre). Relevant code located in `src/app.rs`.

### Expected behavior

Should be able to pass an `enum` with an `Option` value as an argument for an `invoke` command.

### Platform and versions

Environment
  › OS: Pop!_OS 22.04 X64
  › Node.js: 19.3.0
  › npm: 9.2.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.66.0
  › cargo: 1.66.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.2.2
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.3,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
package.json not found

App directory structure
  ├─ .vscode
  ├─ src-tauri
  ├─ target
  ├─ dist
  ├─ public
  └─ src

### Additional context

Using Yew v 0.20.0.

**Comment by bicarlsen** [comment]
Upon further investigation,this may be an issue with [`serde`](https://crates.io/crates/serde), but I'll leave the issue open for now in case somebody can provide feedback.

**Comment by amrbashir** [comment]
Seems like a problem with `wasm-bindgen` implementation for converting `Option<T>` to `JsValue`. 
They are converting `None` to `undefined` instead of `null` and that will result in `JSON.stringify` skiping it in. I will close this since we can't do anything about it but will raise the issue upstream.

**Comment by bicarlsen** [comment]
I ran across this problem again and created an [MRE](https://github.com/bicarlsen/tauri-command-enum-option-mre), if it's useful in the future.
