### ISSUE TITLE
Check before compile on cargo publish [feat] 

### ISSUE THREAD

**Issue by miguelgargallo** [tauri-apps/tauri#5994]
### Describe the problem

I want to publish on crates.io, I need to wait like for 11 libraries, then an error on my .json, so basic... but I forgot...it says to me to change, so I change
![It would be better to check all before](https://user-images.githubusercontent.com/5947268/211088692-8a2ad792-3ff8-4a4c-9a51-7597ae1d786e.png)

### Describe the solution you'd like

I would like to do not allow me to compile if my basic info staff is not okay

**Comment by FabianLars** [comment]
I don't think there's anything we can do here. There is no way to hook into `cargo publish` and run something before the cargo command runs, right?

To me it sounds more like a responsibility for the build/publishing pipeline, as-in adding a `cargo check` and/or `cargo publish --dry-run` step.
