### ISSUE TITLE
Bundled AppImage does not execute

### ISSUE THREAD

**Issue by alvarohm** [tauri-apps/tauri#601]
**Describe the bug**
The AppImage generated by the bundler does not run. In particular, it yields the error "cannot execute binary file: Exec format error".

I have managed to fix this by changing the `build_appimage` script in `src-tauri/target/release/bundle/appimage` to download an AppImage runtime and appending it to the image. In this case, the AppImage bundle successfully executes, but in the next execution of 
`yarn tauri:build ` the script `build_appimage` is overwritten.

**To Reproduce**
(This is based on a project created using `vue-cli-plugin-tauri`)
Steps to reproduce the behaviour:
1. Create new project using
```
vue create my-tauri-app
cd my-tauri-app
vue add tauri
```
2. Run `yarn tauri:build`
3. Go to `src-tauri/target/release/bundle/appimage`
4. Run `./app.AppImage

**Expected behavior**
Running the AppImage should create a window with the default vue application.

**Platform and Versions (please complete the following information):**
OS:Linux(5.6.12-1-MANJARO) - linux/x64
Node:14.1.0
NPM:6.14.4
Yarn:1.22.4
Rustc:1.43.1

**Additional context**
The appimage runtime I have used is https://github.com/AppImage/AppImageKit/releases/download/continuous/runtime-x86_64

**Comment by lucaheise** [comment]
I run into the same problem on Fedora and a fresh Ubuntu-VM

I couldn't follow your suggestions with appending the runtime. I just uncommented the existing cat command in `build_appimage` and made sure the runtime-File is in that folder beforehand. 

`wget -q -O runtime https://github.com/AppImage/AppImageKit/releases/download/continuous/runtime-x86_64`
`cat runtime >> app.AppImage`

But I then get `execv error: No such file or directory` when trying to run the AppImage

Could you explain your solution a bit more precisely?

**Comment by alvarohm** [comment]
Hi. There were a few more problems in the script `build_appimage` that I had forgotten to mention in my post. I fixed them first and then started focusing on the AppImage runtime, so I forgot about the other problems. Apologies for the omission. Here's a rundown of the issue I have found and a version of the script that works for me. I hope this helps.

1) The script is in the `appimage` folder, so the `deb` folder is below `appimage`, not inside `bundle`.
2) Before copying `app` and the icon to `app.AppDir`, we need to `cd` into `app.AppDir` as the folder `usr` has already been copied.
3) The path to the icon has a type in `256x265`, it should be `256x256`.
4) We need to `cd` back to `appimage` before creating and copying the `.desktop` file to created it in appimage. 
5) The appimage should not be redirected into `app.AppImage` not appended. Appending it only works if the file was empty or did not exist before.

With this changes (including the download of the runtime), the script builds an AppImage that works for me. Note that if you run `yarn tauri:build`, the script is reverted back. 

Here's the full script that worked for me:

```
#!/bin/bash

mkdir -p app.AppDir
cp -r ../deb/app_0.1.0_amd64/data/usr app.AppDir

cd app.AppDir

cp usr/bin/app AppRun
cp usr/share/icons/hicolor/256x256/apps/app.png app.png

cd ..

echo '[Desktop Entry]' > app.desktop
echo 'Version=1.0' >> app.desktop
echo 'Comment=A Tauri App' >> app.desktop
echo 'Exec=app' >> app.desktop
echo 'Icon=app' >> app.desktop
echo 'Name=APP' >> app.desktop
echo 'Terminal=false' >> app.desktop
echo 'Type=Application' >> app.desktop
echo 'Categories=X-Web;' >> app.desktop

cp app.desktop app.AppDir/usr/share/applications/app.desktop


mksquashfs app.AppDir app.squashfs -root-owned -noappend

wget -q -O runtime https://github.com/AppImage/AppImageKit/releases/download/continuous/runtime-x86_64
cat runtime > app.AppImage
# cat runtime >> app.AppImage
cat app.squashfs >> app.AppImage
chmod a+x app.AppImage
```

**Comment by nothingismagick** [comment]
Thanks @alvarohm !

**Comment by nothingismagick** [comment]
We're going to cut a new release today or tomorrow. This should be resolve. Please feel free to reopen if its still not working.

**Comment by lucaheise** [comment]
I've got the new script and think everythings updated.
The Build AppImage throws:

> This doesn't look like a squashfs image.
> 
> Cannot mount AppImage, please check your FUSE setup.
> You might still be able to extract the contents of this AppImage 
> if you run it with the --appimage-extract option. 
> See https://github.com/AppImage/AppImageKit/wiki/FUSE 
> for more information
> open dir error: No such file or directory

after manually rerunning `build_appimage` everything is fine

**Comment by lucasfernog** [comment]
@lucaheise I'm fixing the appimage here #682
