### ISSUE TITLE
[bug] the window show noting but can visit web with web browser

### ISSUE THREAD

**Issue by BingCoke** [tauri-apps/tauri#6011]
### Describe the bug

when i first use tauri run command 'npm run tauri dev' and then there is noting but white!
No error report.
![image](https://user-images.githubusercontent.com/81607010/211198610-a6a089a6-9100-44af-97c2-0c8f8d63b695.png)
but when i use web browse to visit localhost:1420, everything is fine.
![image](https://user-images.githubusercontent.com/81607010/211198839-e0187c1e-067f-4f56-b963-b07a3fea1ba4.png)

### Platform and versions

![image](https://user-images.githubusercontent.com/81607010/211198657-8554bd30-a31d-4fdb-9caf-9db2e81d4ab7.png)

**Comment by BingCoke** [comment]
well , i found the reason.Mybe webkit doesn't  support for the proxy very well?Just say it i know about it very little.
I find that app which use proxy can't get resouces from localhost:1240.when i close proxy , everything goes well! 
![image](https://user-images.githubusercontent.com/81607010/211791284-da17f2fd-add2-4674-a5c5-95d319bb7115.png)
I read the introduce about configuration and get noting about proxy.So how can i fix it in addition to close proxy?

**Comment by amrbashir** [comment]
It is not something we control unfortunately, so you need to close the proxy while developing.
