### ISSUE TITLE
[feat] Dynamically control whether Menu, SystemMenu is displayed or not.

### ISSUE THREAD

**Issue by lencx** [tauri-apps/tauri#6015]
### Describe the problem

Because the application needs to read from the configuration file whether the menu is displayed or not, but currently tauri does not control the parameters of menu by code, it needs to save them to variables and process them several times.

```rust
fn main() {
	// config file
	let has_menu = true;
	let has_tray_menu = true;
	let mut builder = tauri::Builder::default();
	if has_menu {
		builder = builder.menu(Menu::new());
	}
	if has_tray_menu {
		builder = builder.system_tray(SystemTray::new());
	}
	builder
		.run(tauri::generate_context!())
		.expect("error while running tauri application");
}
```

### Describe the solution you'd like

Is it possible to provide a way to set whether to show them or not without modifying the original api, for example by adding `show_menu` and `show_system_tray`.

```rust
fn main() {
	// config file
	let has_menu = true;
	let has_tray_menu = true;
	let mut builder = tauri::Builder::default()
		.menu(Menu::new())
		.system_tray(SystemTray::new())
		.show_menu(has_menu)
		.show_system_tray(has_tray_menu)
		.run(tauri::generate_context!())
		.expect("error while running tauri application");
}
```

**Comment by tk103331** [comment]
Maybe it would be better to provide a method like this, **menu_if** for example


``` rust
    pub fn menu_if<F: Fn() -> Menu + Send + Sync + 'static>(mut self, show: bool, menu_init: F) -> Self {
        if show {
            let menu = menu_init();
            self.menu.replace(menu);
        }
        self
    }
```

This can control whether to initialize the menu, because if you don't want to display it, you don't need to initialize it.

And then call like this:

``` rust
    let show_menu = true; // condition
    Builder::default()
        .menu_if(show_menu, || Menu::new())
        .build();
```

**Comment by amrbashir** [comment]
@tk103331 sounds good, feel free to open a PR for this
