### ISSUE TITLE
[feat] Feature Based Update Channels

### ISSUE THREAD

**Issue by bencevans** [tauri-apps/tauri#6019]
### Describe the problem

Working on [CamTrap Detector](https://github.com/bencevans/camtrap-detector), we're wanting to add in the updater but have separate builds based on cargo feature flags. By default model execution on CPU, and another with GPU support. With the updater, we'd like to ensure that the user receives the correct build in line with what they originally downloaded. I think this would follow the pattern of separate release channels (`latest-cpu` and `latest-gpu`).

### Describe the solution you'd like

A method for the updater to identify a release channel, so that builds with differing functionality get updated to newer builds with the same feature flags or within the same "release channel".

### Alternatives considered

Making changes to the Tauri Config file before each build changing the URL "manually".

**Comment by FabianLars** [comment]
You can also change the endpoint url directly in the code: https://github.com/tauri-apps/tauri/issues/2595#issuecomment-1160772317 (just need to change the example to take the feature flags into account).

The only alternative that comes it mind is using <https://docs.rs/tauri/latest/tauri/updater/struct.UpdateBuilder.html#method.header> when you're using an actual update server and not just static files.

**Comment by bencevans** [comment]
Thanks! Sorry I'd not spotted that thread when searching.
