### ISSUE TITLE
[bug] Visual bug of the maximize window button

### ISSUE THREAD

**Issue by Sketnext** [tauri-apps/tauri#6024]
### Describe the bug

When hovering the mouse over the maximize window button, the background color of the button changes but does not appear to have the correct proportions (The minimize and close buttons are displayed correctly).

(Screenshot taken using windows 11's default screenshot tool)
![imagen](https://user-images.githubusercontent.com/69060929/211484279-e805344c-bae4-4c67-ae48-3502d84443b9.png)

I also tried to record my screen to show the problem, but for some reason it worked correctly while recording, when I stop recording the problem reappears. 

After that I restarted the application and the problem persisted.

(Screenshot made using ScreenToGif, free software)
![Gif (3)](https://user-images.githubusercontent.com/69060929/211487221-d2cb994d-8cf4-4ae0-8c34-9dc3dfa7946b.gif)

Here is a mobile phone recording of my screen showing the problem:
https://user-images.githubusercontent.com/69060929/211492157-e636613f-cb0e-4268-bed6-70f0978e3b12.mp4

### Reproduction

Basically I followed the tutorial at https://tauri.app/v1/guides/getting-started/setup/html-css-js

Using powershell I entered the commands:
`cargo install create-tauri-app`
`cargo create-tauri-app`
`cargo install tauri-cli`
`cargo tauri dev`

### Expected behavior

![imagen](https://user-images.githubusercontent.com/69060929/211486507-f71c4bab-bdda-47f1-8011-d4cd066cd43c.png)

### Platform and versions

Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 108.0.1462.76
  › MSVC:
      - Visual Studio Community 2022
  › Node.js: 18.12.1
  › npm: 8.19.3
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.66.0
  › cargo: 1.66.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.2.2
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.3,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../src
  › devPath: ../src
package.json not found

App directory structure
  ├─ .vscode
  ├─ src
  └─ src-tauri

**Comment by amrbashir** [comment]
this is an issue with Windows 11 itself and should be fixed in an upcoming release of Windows.
