### ISSUE TITLE
[bug] Auto rebuild didn't generate_handler for new function

### ISSUE THREAD

**Issue by kingwingfly** [tauri-apps/tauri#6026]
### Describe the bug

I create a new function in `main.rs`, then generate_handler, after saving, it naturally began to build.  
After that, the new function can not be called in xxx.vue through `invoke`. I asked the ChatGPT, and she said it should just goes OK.  
I took nearly two hours to find manually running `cargo tauri dev` to solve the problem.  That's sad.

### Reproduction

1. Create a new function in `main.rs`
2. generate_handler
3. waiting for the auto build
4. finally find the new function can't be `invoke`d.

### Expected behavior

After the auto build, the new function can be invoked correctly. 

### Platform and versions

Environment
  › OS: Mac OS 13.2.0 X64
  › Node.js: 19.4.0
  › npm: 9.2.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.66.0
  › cargo: 1.66.0
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.2.2
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.3,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Vue.js
  › bundler: Vite

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .vscode
  └─ src

**Comment by kingwingfly** [comment]
Maybe this should be in new feature suggestion.

**Comment by lucasfernog** [comment]
I could not reproduce this (tried on Linux).

**Comment by kingwingfly** [comment]
> I could not reproduce this (tried on Linux).

I can not now, either... Maybe that's because I'm too unlucky today. And thank you for your test, maybe I should learn to test more by myself before putting up an issue.
