### ISSUE TITLE
[bug] Icon of the App.exe and the Destop Icon are wrong

### ISSUE THREAD

**Issue by Winnetoe24** [tauri-apps/tauri#6040]
### Describe the bug

When changing the Icon not all Icons of the Application change.
The Icon when using windows search changed correctly, but the Icon on the Destop created by the installer and the Icon of the generated executable don't.
I have a repo where that is the case: https://github.com/Winnetoe24/SimpleCounter

### Reproduction

1. Create Tauri Project (i my case svelte-preset with npm)
2. Create a new Icon
3. Change the Icon of the App with tauri icon
4. build the App on Windows for release
5. install the Software with the msi-file
6. Inspect Destop and Program Folder

### Expected behavior

The Icon should be the one tauri icon generated.

### Platform and versions

SimpleCounter@0.0.0 tauri
tauri info

Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 108.0.1462.76
  › MSVC:
      - Visual Studio Community 2019
      - Visual Studio Community 2022
  › Node.js: 18.12.1
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.2.2
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.3,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Svelte
  › bundler: Vite

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri

**Comment by amrbashir** [comment]
Your project works fine, and all icons are changed. Probably a caching issue from Windows, maybe a restart will fix it?

**Comment by Winnetoe24** [comment]
I tested and found that restarting was not the solution. I had to clean my target directory.
I think tauri should clean the parts needed.
You could implement an option in "tauri icon" that does it for you or "tauri build" should detect the icon change at the files.
