### ISSUE TITLE
Move `init_logging` to `tauri-plugin-log`

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri#6049]
https://github.com/tauri-apps/tauri/blob/50f6dd87b1ac2c99f8794b055f1acba4ef7d34d3/core/tauri/src/lib.rs#L281-L331

This does not belong here

**Comment by lucasfernog** [comment]
I'll take care of this. I need some time to cleanup the tags though.

**Comment by JonasKruckenberg** [comment]
> I'll take care of this. I need some time to cleanup the tags though.

Great! If you want me to jump into anything and help let me know

**Comment by lucasfernog** [comment]
See https://github.com/tauri-apps/plugins-workspace/pull/96 and #6081
