### ISSUE TITLE
[bug] before*Command env vars use host triple for mobile

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri#6051]
### Describe the bug

When building for mobile, the provided environment variables will reflect the host OS, not the target OS (e.g. on macOS build for iOS `TAURI_PLATFORM` will be `macos` and not `ios`)

### Reproduction

1. Create a mobile setup
2. Log the `TAURI_TARGET_TRIPLE` env var from the vite build config

### Platform and versions

Environment
  › OS: Mac OS 13.1.0 X64
  › Node.js: 18.12.1
  › npm: 8.19.2
  › pnpm: 7.24.3
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.66.0
  › cargo: 1.66.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.1
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected character 't' while parsing major version number")', src/info.rs:566:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  › @tauri-apps/api [NPM]: tauri-apps

**Comment by lucasfernog** [comment]
Fixed by #6116
