### ISSUE TITLE
[bug] No Tauri globals get injected in android webview

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri#6053]
### Describe the bug

When invoking commands inside an android emulator, it appears that none of the globals `__TAURI_IPC__` and `__TAURI_METADATA__` are injected into the web view

### Reproduction

1. Create a new Tauri android project
2. invoke a command

### Expected behavior

Variables should be injected into the webview

### Platform and versions

Environment
  › OS: Mac OS 13.1.0 X64
  › Node.js: 18.12.1
  › npm: 8.19.2
  › pnpm: 7.24.3
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.66.0
  › cargo: 1.66.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.1
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected character 't' while parsing major version number")', src/info.rs:566:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  › @tauri-apps/api [NPM]: tauri-app

### Stack trace

```shell
In my case this is:
01-13 20:54:28.646  9065  9065 E Tauri/Console: File: https://tauri.localhost/_nuxt/node_modules/.vite/deps/tauri-plugin-log-api.js?v=e89ac832 - Line 25 - Msg: Uncaught (in promise) TypeError: window.TAURI_IPC is not a function
```

### Additional context

I can confirm this is not an issue on iOS

**Comment by doums** [comment]
Hi, I have the same issue. Hey there is a way to benefit from this fix as there is no release yet?
