### ISSUE TITLE
[bug] Android proxy mixed content warning

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri#6055]
### Describe the bug

When configuring an Android+Tauri project the following settings for Vite's HMR are recommended:
```js
hmr: {
        protocol: 'ws',
        host, // this will be 192.168.x.x
        port: 5183,
      },
```

but the web content itself is loaded with the `https://tauri.localhost` origin in the android webview. This causes the webview to block the HMR connection (and all other connections to the development server) as it's mixed origin content now.

### Reproduction

1. Tauri+Android app
2. configure Vite's HMR as stated in the v2 docs
3. open the webview debugger in a chromium browser

### Expected behavior

I guess the reason for loading content via https is that it enables more API and is closer to development, but this should definitely not break HMR.

### Platform and versions

Environment
  › OS: Mac OS 13.1.0 X64
  › Node.js: 18.12.1
  › npm: 8.19.2
  › pnpm: 7.24.3
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.66.0
  › cargo: 1.66.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.1
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected character 't' while parsing major version number")', src/info.rs:566:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  › @tauri-apps/api [NPM]: tauri-apps

### Stack trace

```shell
Mixed Content: The page at 'https://tauri.localhost/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://192.168.178.20:5183/_nuxt/'. This endpoint should be available via WSS. Insecure access is deprecated.
```

**Comment by clep64** [comment]
Hi,
I am facing the same issue and it is not clear to me what the solution or the workaround is if any.
Thanks

**Comment by amrbashir** [comment]
Using the templates from `create-tauri-app --alpha --mobile`, The HMR should be working fine, there is warnings in the dev console but HMR still works.

**Comment by amrbashir** [comment]
Let me know if you still facing the same issue with any template in CTA
