### ISSUE TITLE
[bug] Next: WebSocket error when using local files

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri#6058]
### Describe the bug

When running a Tauri app *without* development server (e.g. the `developmentPath` is `../dist`) then the app throws websocket related errors in the console. See below

### Reproduction

1. Scaffold a new project using the `2.0.0-alpha.2` CLI
2. Add a static html file as the frontend
3. run the app and watch the console

### Expected behavior

Idk why the static file mode would need to connect to a websocket server, but either the server should be successfully connected to or the connection should not be attempted to begin with

### Platform and versions

Environment
  › OS: Mac OS 13.1.0 X64
  › Node.js: 18.12.1
  › npm: 8.19.2
  › pnpm: 7.24.3
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.66.0
  › cargo: 1.66.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.1 // note that this is actually also not correct, I have no NPM CLI installed
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: git+https://github.com/tauri-apps/tauri?branch=next#50f6dd87b1ac2c99f8794b055f1acba4ef7d34d3 (2.0.0-alpha.2),
  › tauri-build [RUST]: git+https://github.com/tauri-apps/tauri?branch=next#50f6dd87b1ac2c99f8794b055f1acba4ef7d34d3 (2.0.0-alpha.0),
  › tao [RUST]: 0.16.0,
  › wry [RUST]: git+https://github.com/tauri-apps/wry?branch=dev#da55344dd8fec127882dd6b9ffe14b49522f928c (0.24.1),

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: ../dist
package.json not found

App directory structure
  ├─ dist
  └─ src-tauri

### Stack trace

```shell
WebSocket connection to 'ws://localhost/_tauri-cli/ws' failed: Could not connect to the server.
```

**Comment by amrbashir** [comment]
this is related to https://github.com/tauri-apps/tauri/issues/6055 so let's keep all the discussion there
