### ISSUE TITLE
[bug] android WRY_ANDROID_REVERSED_DOMAIN is not set

### ISSUE THREAD

**Issue by AlbanMinassian** [tauri-apps/tauri#6061]
### Describe the bug

fresh install, android dev error "WRY_ANDROID_REVERSED_DOMAIN` is not set"

### Reproduction

❯ cargo create-tauri-app

✔ Project name · tauri-app
✔ Choose your package manager · cargo
✔ Choose your UI template · vanilla

❯ cd tauri-app/src-tauri
❯ cargo tauri android init

Installing Android toolchains...
info: component 'rust-std' for target 'aarch64-linux-android' is up to date
info: component 'rust-std' for target 'armv7-linux-androideabi' is up to date
info: component 'rust-std' for target 'i686-linux-android' is up to date
info: component 'rust-std' for target 'x86_64-linux-android' is up to date
Generating Android Studio project...
        Info "/home/aminassian/programs/tauri-app/src-tauri" relative to "/home/aminassian/programs/tauri-app/src-tauri/gen/android/tauri_app/tauri_app" is "../../../../"
        Info detected host target triple "x86_64-unknown-linux-gnu"
victory: Project generated successfully!
    Make cool apps! 🌻 🐕 🎉

❯ cargo tauri android dev

   Compiling num_enum v0.5.7 [41s]
error: failed to run custom build command for `wry v0.23.4`

Caused by:
  process didn't exit successfully: `/home/aminassian/programs/tauri-app/src-tauri/target/debug/build/wry-3c0c9f18658876a0/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=WRY_ANDROID_REVERSED_DOMAIN
  cargo:rerun-if-env-changed=WRY_ANDROID_APP_NAME_SNAKE_CASE
  cargo:rerun-if-env-changed=WRY_ANDROID_KOTLIN_FILES_OUT_DIR

  --- stderr
  thread 'main' panicked at '`WRY_ANDROID_REVERSED_DOMAIN` is not set, which is needed to generate the kotlin files for android.', /home/aminassian/.cargo/registry/src/github.com-1ecc6299db9ec823/wry-0.23.4/build.rs:19:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
       Error `Failed to run `cargo build`: Command "cargo build --package tauri-app --manifest-path /home/aminassian/programs/tauri-app/src-tauri/Cargo.toml --target x86_64-linux-android --no-default-features --color always" didn't complete successfully, exiting with code 101.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:rustBuildX86_64Debug'.
> Process 'command '/home/aminassian/.cargo/bin/cargo-tauri'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 46s
       Error Failed to assemble APK: Command "/home/aminassian/programs/tauri-app/src-tauri/gen/android/tauri_app/gradlew --project-dir /home/aminassian/programs/tauri-app/src-tauri/gen/android/tauri_app assembleX86_64Debug --warn" didn't complete successfully, exiting with code 1.

### Platform and versions

Ubuntu 22

### Additional context

seem relative to https://github.com/tauri-apps/wry/issues/843

**Comment by JonasKruckenberg** [comment]
Welcome to Tauri, please next time fill out `Platform and versions` with the proper output returned by running `tauri info`. Just Ubuntu 22 isn't helpful in this context. 

That said, it's likely a version mismatch between the `tauri` crate and the CLI. If you're using the CLI from crates.io or npm you must also use `tauri` from crates.io, if you use the CLI from git then you must also use `tauri` from git.
