### ISSUE TITLE
[feat] Easy way to create menu bar applications

### ISSUE THREAD

**Issue by grapesalt** [tauri-apps/tauri#6064]
### Describe the problem

Tauri doesn't seem to have any native solution to building menu bar only applications like this:
![Like this](https://user-images.githubusercontent.com/121238054/212493946-aac28d87-b67b-46ba-a976-8b983f9f7f76.png)

### Describe the solution you'd like

I would like to have a native solution for building native menu only apps.

### Alternatives considered

There's a library for electron for creating menubar applications.
https://github.com/maxogden/menubar

**Comment by amrbashir** [comment]
This is out of `tauri` scope, please take a look at https://github.com/tauri-apps/tauri-plugin-positioner
