### ISSUE TITLE
[bug] tauri-cli not installing on Mac M1

### ISSUE THREAD

**Issue by Connoropolous** [tauri-apps/tauri#6065]
### Describe the bug

Trying to install tauri-cli version 2.0.0-alpha stream on a Mac Studio, which is an M1 type.
Compile is failing. 

### Reproduction

Run:
`cargo install tauri-cli --version "2.0.0-alpha.0"`

### Expected behavior

It compiles and installs

### Platform and versions

<img width="227" alt="Screenshot 2023-01-14 at 3 55 58 PM" src="https://user-images.githubusercontent.com/1409121/212502266-31bedaa4-a818-42d5-8b3d-01837d10c490.png">

### Stack trace

```shell
error[E0063]: missing field `lib_name` in initializer of `tauri_mobile::config::app::Raw`
   --> /Users/connor/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-cli-2.0.0-alpha.0/src/mobile/mod.rs:237:13
    |
237 |   let raw = RawAppConfig {
    |             ^^^^^^^^^^^^ missing `lib_name`
```

### Additional context

<img width="829" alt="Screenshot 2023-01-14 at 3 57 28 PM" src="https://user-images.githubusercontent.com/1409121/212502294-4ac4a336-0edc-42fe-b0d1-d478defa4250.png">

**Comment by amrbashir** [comment]
try with `cargo install tauri-cli --version "2.0.0-alpha.0 --locked` for now, will fix it soon.

**Comment by Connoropolous** [comment]
oo, thank you. I should have thought to try that.

**Comment by amrbashir** [comment]
Problematic version of `tauri-mobile` has been yanked, normal command should work now.
