### ISSUE TITLE
 window is not defined in mock example [bug] 

### ISSUE THREAD

**Issue by Cedu1402** [tauri-apps/tauri#6076]
### Describe the bug

When i try to run the mock example i get the error  window is not defined. 

### Reproduction

1. Create new Tauri Project react-ts
2. Add vitest and try to run the Mock example: https://tauri.app/v1/guides/testing/mocking

### Expected behavior

Test to run without error

### Platform and versions

npm run tauri info

> TestVitest@0.0.0 tauri
> tauri info

Environment
  › OS: Linux Mint 21 X64
  › Node.js: 18.12.0
  › npm: 8.19.2
  › pnpm: 7.25.0
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.2
  › @tauri-apps/api [NPM]: 1.2.0
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected end of input while parsing minor version number")', src/info.rs:502:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Stack trace

```shell
ReferenceError: window is not defined
    at /media/cedu/Main/Projects/TestVitest/src/Test/example.spec.ts:10:5
    at /media/cedu/Main/Projects/TestVitest/node_modules/vitest/dist/chunk-runtime-chain.4e2aa823.js:2336:26
    at /media/cedu/Main/Projects/TestVitest/node_modules/vitest/dist/chunk-runtime-setup.56d71d30.js:286:59
    at Array.map (<anonymous>)
    at callSuiteHook (/media/cedu/Main/Projects/TestVitest/node_modules/vitest/dist/chunk-runtime-setup.56d71d30.js:286:47)
    at runSuite (/media/cedu/Main/Projects/TestVitest/node_modules/vitest/dist/chunk-runtime-setup.56d71d30.js:454:39)
    at runFiles (/media/cedu/Main/Projects/TestVitest/node_modules/vitest/dist/chunk-runtime-setup.56d71d30.js:613:11)
    at startTestsNode (/media/cedu/Main/Projects/TestVitest/node_modules/vitest/dist/chunk-runtime-setup.56d71d30.js:631:9)
    at /media/cedu/Main/Projects/TestVitest/node_modules/vitest/dist/entry.js:103:11
    at Module.withEnv (/media/cedu/Main/Projects/TestVitest/node_modules/vitest/dist/chunk-runtime-setup.56d71d30.js:168:5)
```

**Comment by FabianLars** [comment]
by default vite's test runs in a nodejs environment which doesn't have access to window/navigator. You need to set `environment` to `jsdom` (or maybe happy-dom if that works for your frontend) <https://vitest.dev/config/#environment> - iirc you also need to install the `jsdom` package for that to work.

afaik the configuration of test frameworks is out of scope for our guide

**Comment by Cedu1402** [comment]
Ahh thanks a lot. Totally missed that.
