### ISSUE TITLE
[bug] tauri mobile iOS Xcode: build script fails to run

### ISSUE THREAD

**Issue by Connoropolous** [tauri-apps/tauri#6077]
### Describe the bug

It is this line of code that panics:
https://github.com/tauri-apps/tauri/blob/7945e549b73ca104290d7568559635f2d53e0eed/tooling/cli/src/mobile/mod.rs#L184

### Reproduction

I followed the instructions here:
https://next--tauri.netlify.app/next/mobile/development/mobile_workflow
and integrated it into an existing project. 

Specifically, I did run:
`cargo tauri ios init`

### Expected behavior

The app to build

### Platform and versions

<img width="796" alt="Screenshot 2023-01-16 at 12 03 23 PM" src="https://user-images.githubusercontent.com/1409121/212757795-f0410401-9aa4-41c1-b398-23d77973670b.png">

Mac Studio. M1 Processor.

### Stack trace

```shell
/bin/sh -c /Users/connor/Library/Developer/Xcode/DerivedData/app-bjdpzyedsplvnlbnaoyjdwicevvq/Build/Intermediates.noindex/app.build/debug-iphoneos/app_iOS.build/Script-E028F843270D8815FCE2B491.sh
       Debug [globset] built glob set; 0 literals, 2 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 0 regexes
       Debug [globset] built glob set; 1 literals, 1 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 0 regexes
       Debug [globset] built glob set; 1 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 0 regexes
thread 'main' panicked at 'missing addr environment variable: NotPresent', /Users/connor/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-cli-2.0.0-alpha.1/src/mobile/mod.rs:184:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Command PhaseScriptExecution failed with a nonzero exit code

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Build\ Rust\ Code /Users/connor/Library/Developer/Xcode/DerivedData/app-bjdpzyedsplvnlbnaoyjdwicevvq/Build/Intermediates.noindex/app.build/debug-iphoneos/app_iOS.build/Script-E028F843270D8815FCE2B491.sh (in target 'app_iOS' from project 'app')
(1 failure)
```

### Additional context

<img width="1036" alt="Screenshot 2023-01-16 at 12 00 29 PM" src="https://user-images.githubusercontent.com/1409121/212757652-112c6145-2fa4-4eea-9c8c-acbeab53fb36.png">

**Comment by Connoropolous** [comment]
irrelevant, overcame this.

**Comment by sploders101** [comment]
@Connoropolous Would you mind specifying how you overcame this? I'm experiencing the same issue now. The docs say Xcode 14 isn't supported, but I can't downgrade, so even a workaround would help for me and other future readers who find this.

**Comment by Connoropolous** [comment]
Yeah sure
Kk well, don’t try and build from within Xcode I learned. Do it from the CLI, and when you do, **be SURE to run the command from the src-tauri folder**. I was running the command from the CLI in a parent directory and that was causing an issue.


cargo tauri ios build

**Comment by Connoropolous** [comment]
Which docs mention Xcode 14?

**Comment by Connoropolous** [comment]
I am using and I did manage to make it work. I also had an issue with GCC_PREPROCESSOR_DEFINITIONS so let me know if you hit against that

**Comment by sploders101** [comment]
Awesome! I'll give that a shot, thanks!

This is where I found that. It could be outdated:
https://tauri.app/blog/2022/12/09/tauri-mobile-alpha/
> Known issues:
> Currently running on a device is not supported when using Xcode 14.

I am actually not using their standard directory structure; It didn't really work with my project, but I split it all up and restructured so I think I can go back to it now.

**Comment by sploders101** [comment]
That seems to have worked, thanks! Now I just need to figure out why my async runtime is causing segfaults (probably has something to do with the fact that I'm using async_std for the backend but Tauri is using Tokio).

EDIT:
For anyone else trying out the mobile builds, it may be worthwhile to generate a fresh project after installing the updated CLI and move your logic into it. For me, I built the majority of the backend logic and APIs long before I knew about Tauri, so I made Tauri fit into *my* structure instead of the other way around. It seems the cli and mobile builds don't like that.

Also, Xcode 14 *does* seem to work, as long as you build from the CLI, not from Xcode (it uses the Xcode compilers and such underneath).

**Comment by sploders101** [comment]
I just ran into the preprocessor options issue, and found this issue while looking for this one since I remembered you said you fixed it. Would you mind shedding some light on the issue here?

https://github.com/tauri-apps/tauri/issues/5811

Thanks again for your help!

**Comment by Connoropolous** [comment]
Aha. Let me answer there, and please see my response!

**Comment by Connoropolous** [comment]
> Also, Xcode 14 _does_ seem to work, as long as you build from the CLI, not from Xcode (it uses the Xcode compilers and such underneath).

Yes agreed, found the exact same

**Comment by Connoropolous** [comment]
Here's another tip that I had to work too hard to find out:

For detailed logging on the build process, use:
`cargo tauri ios build -vvv`
