### ISSUE TITLE
[feat] Support for ubuntu touch

### ISSUE THREAD

**Issue by nanu-c** [tauri-apps/tauri#6084]
### Describe the problem

Ubuntu touch is an mobile friendly os that is build with qt and has no gtk. Never the less there are some rust-qt bindings and examples that can use a webengine view to show webapps.

### Describe the solution you'd like

A QT based webview/webengineview rendering backend for tauri.

### Alternatives considered

Don't use tauri, but instead detect Ubuntu touch and use a dirty hack with a small qml file that is run via qmlscene that opens the webapp provided by a small file server in rust.

### Additional context

The rootfs is write protected and ubuntu touch doesn't ship gtk, so in order to make tauri run gtk has to be shipped with the package. This is even more overhead than using electron.

**Comment by amrbashir** [comment]
next0@

**Comment by Fuseteam** [comment]
If i'm reading this correctly this needs to be implemented in https://github.com/tauri-apps/wry which needs to utilize qtwebengine rather than webkitgtk while https://github.com/tauri-apps/tao would use qt 🤔

**Comment by amrbashir** [comment]
There is currently no plans on supporting ubuntu touch

**Comment by klauss194** [comment]
Guys this would enable a whole world of devs to use Tauri -- would be a massive gain considering how the big platforms get more closed by the day
