### ISSUE TITLE
 i128 is not supported

### ISSUE THREAD

**Issue by happysmile12321** [tauri-apps/tauri#6085]
### Describe the bug

In Rust,I define a struct like this:
```rs
struct Foo{
    bar:i128,
}
```

when I invoke from js side to retrive struct from rust side,
rust side function like this:

```rs
fn get_foo() -> Option<Foo>{
   Foo{bar:1}
}
```

then throw this error.

### Platform and versions

Environment
  › OS: Mac OS 13.0.0 X64
  › Node.js: 14.19.0
  › npm: 6.14.16
  › pnpm: 7.13.6
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.68.0-nightly
  › cargo: 1.68.0-nightly
  › Rust toolchain: nightly-aarch64-apple-darwin

**Comment by FabianLars** [comment]
[serde_json](https://github.com/serde-rs/json) does have a arbitrary_precision feature flag we could use for this, but this may have performance implications for smaller numbers so it probably should be opt-in in tauri too 🤔

**Comment by happysmile12321** [comment]
thanks.
