### ISSUE TITLE
More accurate tauri version in `tauri info`

### ISSUE THREAD

**Issue by chippers** [tauri-apps/tauri#610]
**Is your feature request related to a problem? Please describe.**
This is a nice-to-have that I thought of while adding #609. Currently, when using `tauri info` it will read the version for tauri directly from the `Cargo.toml` where it's listed as a dependency. This makes it inconsistent in the following ways.

1. All of the other versions listed in the info include the patch version. This won't happen for tauri if you declare the version for the dependency as `"*"` or `"0.5"` instead of `"0.5.2"`.
2. The version actually used might be a different/newer version than what's in the `Cargo.toml` due to updating the lockfile.

To be clear, I'm talking about the `tauri` entry in the `App` section from `tauri info`.

Ex:

```sh
App
  tauri - 0.5
```

compared to:

```sh
Rust environment
  rustc - 1.43.1
  cargo - 1.43.0
  tauri-bundler - 0.6.0
```

**Describe the solution you'd like**
Pull the version for the `tauri` crate during `tauri info` from `Cargo.lock` instead. Inside the lockfile, packages are listed as an array of tables because there can be multiples of the same package with different versions. After filtering the packages to find `tauri`, we might find that there are actually multiple versions in use. Due to this new possibility that there are multiple versions, here is how I propose that case should be handled.

---

While searching the lockfile we find both `0.5.2` and `0.4.3`. We then check `Cargo.toml` to check the version the user declared to make the output clearer.

`Cargo.toml`
```toml
[dependencies]
tauri = "0.5"
```

`tauri info`
```sh
App
  tauri - 0.5 (0.5.2, 0.4.3)
```

---

The other display behaviors should be the same, as it already handles not finding the version as `unknown`. When only a single package is found, reading the `Cargo.toml` file to find the declared version should not happen as we already know the only version in use.

I'm willing to write the PR for this, but I figured I should get feedback first since this would be a change of behavior from the current implementation.

**Comment by nothingismagick** [comment]
Awesome. I see that @nklayman merged in the PR, so closing this. Thanks for the support @chippers !!! ❤️

**Comment by chippers** [comment]
That was just allowing the shorthand syntax for it.  This issue is about taking the version from the cargo lockfile

**Comment by lucasfernog** [comment]
I think you're right, and this is helpful to triage issues. We would appreciate if you could PR it :)

**Comment by nothingismagick** [comment]
So the solution from @chippers now throws an error `tauri info` if there is no `Cargo.lock` (i.e. `tauri dev` hasn't been run yet).

```
App
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/[redacted]/src-tauri/Cargo.lock'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at readTomlFile (/[redacted]/.nvm/versions/node/v12.14.0/lib/node_modules/tauri/dist/api/info.js:180:29)
    at printAppInfo (/[redacted]/.nvm/versions/node/v12.14.0/lib/node_modules/tauri/dist/api/info.js:187:24)
    at ./src/api/info.ts.module.exports (/[redacted]/.nvm/versions/node/v12.14.0/lib/node_modules/tauri/dist/api/info.js:294:5)
    at Object.<anonymous> (/[redacted]/.nvm/versions/node/v12.14.0/lib/node_modules/tauri/bin/tauri-info.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/[redacted]/src-tauri/Cargo.lock'
}
```
