### ISSUE TITLE
[bug] Wix errors are not actionable

### ISSUE THREAD

**Issue by agersant** [tauri-apps/tauri#6102]
### Describe the bug

Hello!

I am in the process of writing a `wxs` file to add some components to the MSI installer for my app (notably, to cleanup the webview cache directory leftover in `%localappdata%\<app_identifier_from_tauri_conf>` 😔). When executing `cargo tauri build` and the bundling fails, the error output does not provide enough information:

```
    Finished release [optimized + debuginfo] target(s) in 36.97s
        Info Target: x64
     Running candle for "main.wxs"
     Running candle for "C:\\Users\\agersant\\Documents\\GitHub\\tiger\\src-tauri\\installer/cleanup_appdata_dirs.wxs"
       Error failed to bundle project: error running candle.exe: error running candle.exe: `failed to run C:\Users\agersant\AppData\Local\tauri/WixTools\candle.exe`
```

### Reproduction

- Follow instructions under: https://tauri.app/v1/guides/building/windows/#extending-the-installer-with-wix-fragments
- Make some changes to the provided `wxs` file to make it invalid (eg. add a `<Property>` with an `Id` attribute that isn't in `ALL CAPS`).
- Run `cargo tauri build`

### Expected behavior

Possible resolutions:
1. Display the output of `candle.exe` or `light.exe` to show what they complained about
2. Display the full command invocation for `candle.exe` or `light.exe` so users can run the same command directly and see output (and iterate faster)

### Platform and versions

```
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 109.0.1518.52
  › MSVC: 
      - Visual Studio Build Tools 2019
  › Node.js: 19.0.1
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.66.0
  › cargo: 1.66.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.2 (outdated, latest: 1.2.3)
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.3,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: default-src 'self'; img-src 'self' asset: https://asset.localhost
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: Vue.js
  › bundler: Vite

App directory structure
  ├─ .git
  ├─ .github
  ├─ .vscode
  ├─ dist
  ├─ docs
  ├─ node_modules
  ├─ res
  ├─ src
  └─ src-tauri
```

**Comment by FabianLars** [comment]
Try the verbose flag: `cargo tauri build --verbose` it should show the complete wix output then.

**Comment by agersant** [comment]
Thank you, that worked! Follow-up issue incoming 😰
