### ISSUE TITLE
[bug] window.__TAURI_IPC__ is  not a function

### ISSUE THREAD

**Issue by doums** [tauri-apps/tauri#6105]
### Describe the bug

Hi, I try to build my app for android. The compilation goes fine, the app opens in android emulator. But tauri commands seems to no work, they are not called.
In the logs I can see several errors:
```
01-19 11:11:38.340  4558  4558 E Tauri/Console: File: https://tauri.localhost/app.bundle.js - Line 94261 - Msg: Uncaught (in promise) TypeError: window.__TAURI_IPC__ is not a function
```
What is the current state of android support? Does the tauri globas familly `__TAURI_*__` are injected into the web view? Are tauri commands not supported yet?

Should be related to https://github.com/tauri-apps/tauri/issues/6053 where a fix has been merged that potentially fix the issue? If yes, there is a way to pull this fix on my project since there is no release for it yet?

### Platform and versions

Environment
  › OS: Arch Linux Unknown X64
  › Node.js: 16.17.1
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.66.1
  › cargo: 1.66.1
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.1
  › @tauri-apps/api [NPM]: 2.0.0-alpha.0
  › tauri [RUST]: 2.0.0-alpha.2,
  › tauri-build [RUST]: 2.0.0-alpha.0,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  › distDir: ../dist
  › devPath: http://localhost:9000/
  › framework: React
  › bundler: Webpack

App directory structure
  ├─ public
  ├─ src-tauri
  ├─ .storybook
  ├─ node_modules
  ├─ src
  └─ dist

### Stack trace

```shell
01-19 11:11:38.340  4558  4558 E Tauri/Console: File: https://tauri.localhost/app.bundle.js - Line 94261 - Msg: Uncaught (in promise) TypeError: window.__TAURI_IPC__ is 
not a function
01-19 11:11:38.342  4558  4558 E Tauri/Console: File: https://tauri.localhost/app.bundle.js - Line 94261 - Msg: Uncaught (in promise) TypeError: window.__TAURI_IPC__ is 
not a function
01-19 11:11:38.342  4558  4558 E Tauri/Console: File: https://tauri.localhost/app.bundle.js - Line 94261 - Msg: Uncaught (in promise) TypeError: window.__TAURI_IPC__ is 
not a function
01-19 11:11:38.342  4558  4558 E Tauri/Console: File: https://tauri.localhost/app.bundle.js - Line 94261 - Msg: Uncaught (in promise) TypeError: window.__TAURI_IPC__ is 
not a function
01-19 11:11:38.343  4558  4558 E Tauri/Console: File: https://tauri.localhost/app.bundle.js - Line 94261 - Msg: Uncaught (in promise) TypeError: window.__TAURI_IPC__ is 
not a function
01-19 11:11:38.343  4558  4558 E Tauri/Console: File: https://tauri.localhost/app.bundle.js - Line 94261 - Msg: Uncaught (in promise) TypeError: window.__TAURI_IPC__ is 
not a function
```

**Comment by FabianLars** [comment]
> If yes, there is a way to pull this fix on my project since there is no release for it yet?

You can use tauri from git as explained here: <https://tauri.app/v1/guides/faq#how-can-i-use-unpublished-tauri-changes> (use the `next` branch) - only i think using tauri & tauri-build from git should be enough, the released cli should still work.

**Comment by doums** [comment]
Yup, the fix is present in `next` branch, and fix the issue, thanks!
