### ISSUE TITLE
[bug] returning certain errors from a command causes `thread 'tokio-runtime-worker' has overflowed its stack`

### ISSUE THREAD

**Issue by keeganstothert** [tauri-apps/tauri#6108]
### Describe the bug

I noticed this while creating a tokio tcpstream, when it fails to make a connection the app crashes with  `thread 'tokio-runtime-worker' has overflowed its stack`. If i change the command to return nothing instead of `Result<(), Error>` then everything works normally. 

### Reproduction

you can clone this [example repo](https://github.com/keeganstothert/tauri-command-bug-example) to see the issue. Remove the `Result<(), AppError>` return from the command to see it working

### Expected behavior

should be able to bubble up errors all the way through the command.

### Platform and versions

tested on windows 11 with latest tauri version

### Stack trace

```shell
[2023-01-19][16:25:12][mio::poll][TRACE] registering event source with poller: token=Token(0), interests=READABLE | WRITABLE
[2023-01-19][16:25:14][mio::poll][TRACE] deregistering event source from poller
Failed to connect to desktop stream

thread 'tokio-runtime-worker' has overflowed its stack
```

**Comment by keeganstothert** [comment]
I have found no workaround for this issue on release builds. Removing the error only fixes it for dev.

**Comment by FabianLars** [comment]
The issue is the `Display` implementation, or rather its use of `self`. I can't explain the specific because i don't really get it either, but i saw the same issue in other rust projects.

I will update the example in the guide to use `thiserror`s Display implementation which requires all enum variants to have a `#[error()]` message.
Edit: nevermind, the example doesn't use it 😅 

For example your app_error.rs file could look like this then:

```rs
use serde::{ser::Serializer, Serialize};
use std::fmt::{Display, Formatter};
use thiserror::Error;

#[derive(Debug, Error)]
pub enum AppError {
    #[error(transparent)]
    Io(#[from] std::io::Error),
    #[error(transparent)]
    Tauri(#[from] tauri::Error),
    #[error("{0}")]
    Generic(String),
}

impl Serialize for AppError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(self.to_string().as_ref())
    }
}
```
