### ISSUE TITLE
tauri 0.5.2 relies on unreleased `tauri-api` changes

### ISSUE THREAD

**Issue by chippers** [tauri-apps/tauri#611]
**Describe the bug**
tauri `0.5.2` relies on an unreleased version of `tauri-api` (latest `0.5.0`). After the last release of `tauri-api` a new module was added in root as `tauri_api::http`. This change is not published as a release yet, but the published `tauri 0.5.2` assumes this module exists from `tauri-api` causing failures from fresh `tauri init` commands.

**To Reproduce**
`tauri init && tauri dev`
```sh
error[E0432]: unresolved import `tauri_api::http`
 --> /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-0.5.2/src/endpoints/cmd.rs:3:16
  |
3 | use tauri_api::http::HttpRequestOptions;
  |                ^^^^ could not find `http` in `tauri_api`

error[E0432]: unresolved import `tauri_api::http`
 --> /home/chip/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-0.5.2/src/endpoints/http.rs:1:16
  |
1 | use tauri_api::http::{make_request as request, HttpRequestOptions, ResponseType};
  |                ^^^^ could not find `http` in `tauri_api`

error: aborting due to 2 previous errors
```

**Expected behavior**
`tauri` should not be failing to find a non existent module in the current release of `tauri-api`.

**Platform and Versions (please complete the following information):**
```sh
Operating System - Linux(4.15.0-101-generic) - linux/x64

Node.js environment
  Node.js - 12.16.3
  tauri.js - 0.6.2

Rust environment
  rustc - 1.43.1
  cargo - 1.43.0
  tauri-bundler - 0.6.0

Global packages
  NPM - 6.14.4
  yarn - 1.22.4
```

**Additional context**

Anybody looking at this before the issue is resolved, you can use the git version of `tauri` to workaround this.
```toml
[dependencies]
tauri = { git = "https://github.com/tauri-apps/tauri" , version = "0.5"}
```

**Comment by nothingismagick** [comment]
sry - releasing tauri-api v0.5.1 right now
