### ISSUE TITLE
[feat] Leftover data after bundle is uninstalled on Windows

### ISSUE THREAD

**Issue by agersant** [tauri-apps/tauri#6113]
### Describe the bug

When building an `.msi` installer with `cargo tauri build`, installing and uninstalling the app leaves some orphaned data on the user's disk. Specifically, a directory under `%localappdata%\<bundleIdentifier>` remains and is not empty.

### Reproduction

Video demonstration (feel free to skip ahead during the compilation):

https://user-images.githubusercontent.com/817256/213619469-8700fe26-3ea0-45fd-aef2-c35b40901311.mp4

### Expected behavior

Installing and uninstalling a blank `tauri` app is a noop.

### Platform and versions

```
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 109.0.1518.52
  › MSVC:
      - Visual Studio Build Tools 2019
  › Node.js: 19.0.1
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.66.0
  › cargo: 1.66.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.2.2 (outdated, latest: 1.2.3)
```

**Comment by FabianLars** [comment]
I don't think this qualifies as a bug since virtually every app behaves like this. How about we convert this to a feature request, asking for a checkbox in the uninstaller to remove the data?

The question would be if we want to make that extensible and how, for data the dev wrote to disk manually. Or maybe we just delete the paths behind all the app_X apis 🤔

**Comment by agersant** [comment]
> How about we convert this to a feature request, asking for a checkbox in the uninstaller to remove the data?

I would be happy with this solution too!

**Comment by amrbashir** [comment]
This has been a part of tauri for a while now.

**Comment by tadghh** [comment]
> This has been a part of tauri for a while now.

What does this mean? Theres a feature to delete leftover data on uninstall? Im running into this issue atm.

**Comment by amrbashir** [comment]
yes, your user will be prompted to uninstall the app data which is located at `%localappdata%\<bundleIdentifier>`

**Comment by amrbashir** [comment]
this is for NSIS installer only

**Comment by JacopoMadaluni** [comment]
What about .msi?
I have been struggling to clean appdata with wix fragments and it doesn't seem to be any other way?
