### ISSUE TITLE
[bug] System tray icon cause app to crash on Ubuntu linux

### ISSUE THREAD

**Issue by kurdin** [tauri-apps/tauri#6117]
### Describe the bug

I could not find _any_ working combination of icon size / color in config that could work with system tray on linux systems (Ubuntu)

"tauri": {
  "systemTray": {
    "iconPath": "icons/32x32.png",
    "iconAsTemplate": true
 }

I tried 32x32, 64x64, etc. Nothing can be used with  tauri 1.2.4. 
I bet it was working before with tauri 1.1, it has problem with grayscale image but specifying png image with colors worked 
fine, after upgrade to tauri 1.2.4 I could not make it work at all.

I see 2 type of errors using different size icons

1. thread 'main' panicked at 'data.len() must fit the width, height, and row_stride', /home/kurdin/.cargo/registry/src/github.com-1ecc6299db9ec823/gdk-pixbuf-0.15.11/src/pixbuf.rs:52:13

2. thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Parameter(ParameterError { inner: ImageBufferSize { expected: 16384, actual: 4096 } })', /home/kurdin/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.15.8/src/platform_impl/linux/icon.rs:59:40

Window and macos work fine

### Platform and versions

Environment
  › OS: Ubuntu 22.04 X64
  › Node.js: 16.19.0
  › npm: 8.19.3
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.66.1
  › cargo: 1.66.1
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › framework: React
  › bundler: Webpack

App directory structure

  ├─ dist
  ├─ node_modules
  ├─ assets
  ├─ public
  ├─ src-tauri
  └─ src

### Stack trace

```shell
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Parameter(ParameterError { inner: ImageBufferSize { expected: 16384, actual: 4096 } })', /home/kurdin/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.15.8/src/platform_impl/linux/icon.rs:59:40
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
   2: core::result::unwrap_failed
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:1791:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:1113:23
   4: tao::platform_impl::platform::icon::PlatformIcon::write_to_png
             at /home/kurdin/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.15.8/src/platform_impl/linux/icon.rs:59:5
   5: tao::platform_impl::platform::system_tray::SystemTrayBuilder::build
             at /home/kurdin/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.15.8/src/platform_impl/linux/system_tray.rs:48:5
   6: tao::system_tray::SystemTrayBuilder::build
             at /home/kurdin/.cargo/registry/src/github.com-1ecc6299db9ec823/tao-0.15.8/src/system_tray.rs:87:5
   7: tauri_runtime_wry::system_tray::create_tray
             at /home/kurdin/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-runtime-wry-0.12.2/src/system_tray.rs:117:14
   8: <tauri_runtime_wry::Wry<T> as tauri_runtime::Runtime<T>>::system_tray
             at /home/kurdin/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-runtime-wry-0.12.2/src/lib.rs:1973:25
   9: tauri::app::tray::SystemTray::build
             at /home/kurdin/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.2.4/src/app/tray.rs:419:40
  10: tauri::app::Builder<R>::build
             at /home/kurdin/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.2.4/src/app.rs:1618:9
  11: tauri::app::Builder<R>::run
             at /home/kurdin/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.2.4/src/app.rs:1666:5
  12: my_app::main
             at ./src/main.rs:291:3
  13: core::ops::function::FnOnce::call_once
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:251:5
```

**Comment by getneil** [comment]
this is happening to one of my projects too. but not on mac.

**Comment by kurdin** [comment]
@getneil, mac works fine, I have this error on linux. Strangely, I found that default installation of tauri with fresh system tray setup works just fine on linux, no build errors. I copied Cargo.lock and Cargo.toml to my project, along with tauri.conf.json and icons, after that my project still throw same error on build. I don't understand why this is happening.

**Comment by FabianLars** [comment]
Can you try regenerating your icons with the `tauri icon` command? If you don't use that command and want to do it yourself, make sure your icons are width=height (error 1) and RGBA = rgb + transparency (error 2)

If that doesn't help, or if you tried that already, i'd appreciate if you could share your icons so we can try to reproduce it on our end.

**Comment by kurdin** [comment]
@FabianLars thank you for a tip about using `tauri icon` cli. I did not know about that, it does work and it fixed the problem I had. Seems like this is the best and right way to generate tauri icons specially for linux. Thanks again! 

Anyone who has an icons error with tauri, just create your png image file with transparency with big size like 512x512 pixels and convert it to tauri icons with tauri cli:
`# tauri icon /your-project/app-icon-512x512.png -o /your-project/src-tauri/icons`

tauri cli will generate all icons you need for your app in `src-tauri/icons` folder:
``` 
128x128.png
128x128@2x.png
32x32.png
Square107x107Logo.png
Square142x142Logo.png
Square150x150Logo.png
Square284x284Logo.png
Square30x30Logo.png
Square310x310Logo.png
Square44x44Logo.png
Square71x71Logo.png
Square89x89Logo.png
StoreLogo.png
icon.icns
icon.ico
icon.png
```

**Comment by Z3NTL3** [comment]
> [@FabianLars](https://github.com/FabianLars) thank you for a tip about using `tauri icon` cli. I did not know about that, it does work and it fixed the problem I had. Seems like this is the best and right way to generate tauri icons specially for linux. Thanks again!
> 
> Anyone who has an icons error with tauri, just create your png image file with transparency with big size like 512x512 pixels and convert it to tauri icons with tauri cli: `# tauri icon /your-project/app-icon-512x512.png -o /your-project/src-tauri/icons`
> 
> tauri cli will generate all icons you need for your app in `src-tauri/icons` folder:
> 
> ```
> 128x128.png
> 128x128@2x.png
> 32x32.png
> Square107x107Logo.png
> Square142x142Logo.png
> Square150x150Logo.png
> Square284x284Logo.png
> Square30x30Logo.png
> Square310x310Logo.png
> Square44x44Logo.png
> Square71x71Logo.png
> Square89x89Logo.png
> StoreLogo.png
> icon.icns
> icon.ico
> icon.png
> ```

Had the same problem, ran ``tauri icon``, but anything like ``Positioner::Tray*`` crashes, ``Positioner::Center`` doesn't, reproducable by: 
> https://github.com/Z3NTL3/gtranslate-app/blob/main/src-tauri/src/lib.rs#L173

```
~ 
❯ uname -a
Linux simpaix 6.11.0-29-generic #29~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jun 26 14:16:59 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Z3NTL3** [comment]
> > [@FabianLars](https://github.com/FabianLars) thank you for a tip about using `tauri icon` cli. I did not know about that, it does work and it fixed the problem I had. Seems like this is the best and right way to generate tauri icons specially for linux. Thanks again!
> > Anyone who has an icons error with tauri, just create your png image file with transparency with big size like 512x512 pixels and convert it to tauri icons with tauri cli: `# tauri icon /your-project/app-icon-512x512.png -o /your-project/src-tauri/icons`
> > tauri cli will generate all icons you need for your app in `src-tauri/icons` folder:
> > ```
> > 128x128.png
> > 128x128@2x.png
> > 32x32.png
> > Square107x107Logo.png
> > Square142x142Logo.png
> > Square150x150Logo.png
> > Square284x284Logo.png
> > Square30x30Logo.png
> > Square310x310Logo.png
> > Square44x44Logo.png
> > Square71x71Logo.png
> > Square89x89Logo.png
> > StoreLogo.png
> > icon.icns
> > icon.ico
> > icon.png
> > ```
> 
> Had the same problem, ran `tauri icon`, but anything like `Positioner::Tray*` crashes, `Positioner::Center` doesn't, reproducable by:
> 
> > https://github.com/Z3NTL3/gtranslate-app/blob/main/src-tauri/src/lib.rs#L173
> 
> ```
> ~ 
> ❯ uname -a
> Linux simpaix 6.11.0-29-generic #29~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jun 26 14:16:59 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
> ```

@FabianLars soft ping

**Comment by FabianLars** [comment]
Any panic messages?

**Comment by Z3NTL3** [comment]
> Any panic messages?

```rust
if let Some(window) = app.get_webview_window("main") {
                                    window
                                        .as_ref()
                                        .window()
                                        .move_window_constrained(Position::TrayBottomRight); // panics here due to Position::Tray*
                                    window.show();
                                    window.set_focus();
```

```
thread 'main' panicked at /home/z3ntl3/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tauri-plugin-positioner-2.3.0/src/ext.rs:271:17:
Tray position not set
```

If i do something differently than ``Position::Tray*`` then it works like ``Position::Center``

don't know why this panics as tray is setup in my app's setup hook before this even get's delegated

# edit
this actually panics on ubuntu and likely on macos too, on Windows Positioner::Tray does not panic

**Comment by FabianLars** [comment]
i think i don't have time to look into linux issues at the moment, could you open a new issue in the plugins repo please? https://github.com/tauri-apps/plugins-workspace/

**Comment by Z3NTL3** [comment]
> i think i don't have time to look into linux issues at the moment, could you open a new issue in the plugins repo please? https://github.com/tauri-apps/plugins-workspace/

yep, alright thank you!
https://github.com/tauri-apps/plugins-workspace/issues/2927
