### ISSUE TITLE
Minimum Unresizable Window Size[bug] 

### ISSUE THREAD

**Issue by MusaKavak** [tauri-apps/tauri#6125]
### Describe the bug

I'm trying to make a floating bubble over all windows. This bubble should have 60x60 size and have not window decorations. When i start application like that it's ok. But if i set `"resizable": false`, i can't set window's size less than 200x200. I made this on both Ubuntu(KDE Neon) and Windows. On Windows it's working as expected but not on Ubuntu.

### Reproduction

```
"windows": [
      {
        "fullscreen": false,
        "height": 100,
        "resizable": false,
        "title": "app",
        "width": 100,
        "minWidth": 1,
        "minHeight": 1
      }
    ]
```

### Platform and versions

Environment
  › OS: Linux 22.04 X64
  › Node.js: 18.13.0
  › npm: 8.19.3
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.66.1
  › cargo: 1.66.1
  › Rust toolchain: stable-x86_64-unknown-linux-gnu

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › bundler: Vite

App directory structure
  ├─ src-tauri
  ├─ node_modules
  ├─ src
  └─ .vscode

**Comment by FabianLars** [comment]
Tracked in https://github.com/tauri-apps/tao/issues/561. Thanks for the report.
