### ISSUE TITLE
[feat] IPC Headers/Metadata

### ISSUE THREAD

**Issue by utomdht** [tauri-apps/tauri#6127]
### Describe the problem

Hi ! 
I have a use case with an application where multiple "workspaces" can be supported at the same time in multiple windows. 
The workspace id is used on the backend to refine scope of resources from the context.
Currently to be able to access the correct scope of resource in commands, I need the workspace id in every request type, and to refine manually in every route. 
This introduces overhead & boilerplate. In a web application, I would use a custom header and a middleware.

### Describe the solution you'd like

Having a way to pass metadata or headers from the frontend/client in IPC requests would let me define middlewares to transform the global Context and refine it before passing it to the commands

### Additional context

Is this something you plan to implement, or is it maybe possible already in another way ? 
Thanks !

**Comment by FabianLars** [comment]
https://v2.tauri.app/reference/javascript/api/namespacecore/#invokeoptions
