### ISSUE TITLE
Update Error handling crate to thiserror

### ISSUE THREAD

**Issue by wusyong** [tauri-apps/tauri#613]
**Is your feature request related to a problem? Please describe.**
I would like to open a PR, but looks like it's better to file an issue first. As `failure` is already [deprecated](https://github.com/rust-lang-nursery/failure/pull/347), it seems [`error-chain` will be the same](https://github.com/rust-lang-nursery/failure/issues/181) even it hasn't updated the badge to toml file yet. So I think it's better update to a more modern error handling type crate like [`thiserror`](https://crates.io/crates/thiserror) as soon as we have time. Especially thiserror is already v1.0 and its interface should be lighter and intuitive. 

**Describe the solution you'd like**
Replace error-chain with thiserror v1.0.

**Describe alternatives you've considered**
As a crate being binary/executable, maybe it doesn't need to have a well-typed error as long as there's way to retrieve actual error. In this case, we can even use [`anyhow`](https://crates.io/crates/anyhow) which can make error handling even more easier.

**Additional context**

**Comment by nothingismagick** [comment]
@tensor-programming  was discussing moving to `anyhow` and `thiserror` - maybe wait for his feedback before starting a PR.

**Comment by wusyong** [comment]
Looks like `anyhow` + `thiserror` is also a good approach too. We can just return all Result with `anyhow::Result`, while we can still have custom error type when needed without bothering every kind to error types.

**Comment by nothingismagick** [comment]
One thing tho - I was running some `frida-trace` stuff, and I'd like to be able to totally disable ALL error reporting in builds. Thoughts?

**Comment by wusyong** [comment]
Do you mean something like abort on panic? (which will not unwind the error stack)

**Comment by nothingismagick** [comment]
well - its a tradeoff - i don't want to crash if it can be avoided, but i also don't want to give reversers / hackers information that will inform them about what is going on under the hood

**Comment by wusyong** [comment]
Yeah, in that case we could add this to abort on panic in release build. 

```
[profile.release]
panic = "abort"
```

**Comment by nothingismagick** [comment]
agreed - its something definitely for the docs - will create that over there

**Comment by nothingismagick** [comment]
Do you want to start working on the PR @wusyong ?

**Comment by wusyong** [comment]
Sure, I would like to take it.

**Comment by tensor-programming** [comment]
I've started work on my own PR not seeing yours or this issue.   If you want; we can merge the two.

**Comment by wusyong** [comment]
Okay, I think I can leave bundler untouched.

**Comment by tensor-programming** [comment]
Thank you, sorry again.  You did some great work.
