### ISSUE TITLE
[bug] I Cannot add Rounded borders in windows

### ISSUE THREAD

**Issue by GPeaky** [tauri-apps/tauri#6131]
### Describe the bug

I tried to add rounded borders to my app without usign decorations, but i didnt find anything about it. i tried with css but isnt work.

### Platform and versions

Environment
  › OS: Windows 10.0.22623 X64
  › Webview2: 109.0.1518.61
  › MSVC: 
      - Visual Studio Build Tools 2022
  › Node.js: 19.4.0
  › npm: 9.2.0
  › pnpm: 7.25.0
  › yarn: 3.3.1
  › rustup: 1.25.1
  › rustc: 1.68.0-nightly
  › cargo: 1.68.0-nightly
  › Rust toolchain: nightly-x86_64-pc-windows-msvc 

### Additional context

![A5ghfGFj2b](https://user-images.githubusercontent.com/71239629/214015696-ddae0c1d-30bb-44a4-96c9-b1e7a61d15fb.png)

**Comment by FabianLars** [comment]
If you only want rounded borders on Windows 11 (which is when it was introduced to all apps), you can use <https://github.com/tauri-apps/window-shadows/> which adds native shadows and borders, including rounded corners on win 11.

Other community members explored CSS implementations [here](https://github.com/tauri-apps/tauri/discussions/3093) and [here](https://github.com/tauri-apps/tauri/discussions/3219).
If that doesn't help please show some code you tried so we have something to work with.

**Comment by GPeaky** [comment]
It Worked for me!, thanks.

**Comment by xmx-emm** [comment]
Thank you, I'm also looking for this method
