### ISSUE TITLE
[bug] error: could not compile `json-patch`

### ISSUE THREAD

**Issue by dev-itzarun** [tauri-apps/tauri#6134]
### Describe the bug

Tauri `npm run tauri dev` failed

The actual Error : 
error: could not compile `json-patch`

Caused by:
  process didn't exit successfully: `rustc --crate-name json_patch --edition=2018 C:\Users\aruns\.cargo\registry\src\github.com-1ecc6299db9ec823\json-patch-0.2.7\src\lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg "feature=\"default\"" --cfg "feature=\"diff\"" --cfg "feature=\"treediff\"" -C metadata=6afce7137d566ea4 -C extra-filename=-6afce7137d566ea4 --out-dir E:\svelte_projects\my-pc-biller\src-tauri\target\debug\deps -L dependency=E:\svelte_projects\my-pc-biller\src-tauri\target\debug\deps --extern serde=E:\svelte_projects\my-pc-biller\src-tauri\target\debug\deps\libserde-d1c43ff65e7b4972.rmeta --extern serde_json=E:\svelte_projects\my-pc-biller\src-tauri\target\debug\deps\libserde_json-82fa90a823ca3606.rmeta --extern treediff=E:\svelte_projects\my-pc-biller\src-tauri\target\debug\deps\libtreediff-d30ddb8470b9e576.rmeta --cap-lints allow` (exit code: 1263094860)     
warning: build failed, waiting for other jobs to finish...

npm run tauri dev 

![image](https://user-images.githubusercontent.com/109509109/214333344-2f3cbaf3-e44d-438e-8069-74dc2bb87ee1.png)

### Platform and versions

![image](https://user-images.githubusercontent.com/109509109/214333096-6555b88b-4c53-40af-88e7-095b4ee6ed48.png)

**Comment by FabianLars** [comment]
Can you try running `cargo update` inside your src-tauri folder?

Also deleting `src-tauri/target/debug/` sometimes helps.

Other than that it's quite hard to help because the error isn't really helpful 🤔
