### ISSUE TITLE
[feat] Auto updater: Use notifications instead of prompt

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri#6146]
### Describe the problem

The current default prompt is really intrusive, interrupting the users flow and even blocking the main app thread until the prompt has been dismissed. This means in practice apps rarely use the default prompt, having yo reinvent them in html/css/js.

### Describe the solution you'd like

Switch the prompting logic from intrusive, blocking prompts to use system notifications, since they are less intrusive and maintain more end-user control. 

### Alternatives considered

Add system notifications as an option, changing the config value type from `dialog: bool` to `dialog: "prompt" | "notification" | bool` where `true` enables the default dialog mode (could be `"prompt"` for backwards compatibility)

**Comment by amrbashir** [comment]
Closing this since the updater has been moved to its plugin and removed the native dialog in favor of users taking control over how they want to check and present their updates.
