### ISSUE TITLE
Could tauri app run inside browsers? Or could it support Android or IOS?

### ISSUE THREAD

**Issue by jarvisoac** [tauri-apps/tauri#616]
I would prefer it is running inside browsers like electron. Desktop apps are great but there are chances for the big screens of Android or IOS devices.

**Comment by nothingismagick** [comment]
Well, tauri is for apps. And we are planning on making it possible to build for mobile devices. If you want a website, just use a server. :)

**Comment by dumblob** [comment]
>If you want a website, just use a server. :)

I think the motivation of the question was to maintain one code base for all devices - desktop, mobile, **and** web.

Is that possible?

Does it need some shim library on the web (mimicking the Tauri API)?

Does anyone writes & maintains such shim library?

**Comment by nothingismagick** [comment]
2 years ago we didn't have all the answers, and the question was phrased in a very confused manner. Please file a new issue  @dumblob specifically asking for a feature - or start a discussion. Thankyou :)

**Comment by dumblob** [comment]
Done :wink:.
