### ISSUE TITLE
[bug] Window properties are ignored/not working on linux (KDE/Gnome) (X11/Wayland)

### ISSUE THREAD

**Issue by nodgear** [tauri-apps/tauri#6162]
### Describe the bug

Setting `windows[ { ..., visible: false } ]` does nothing on Linux (at least on Gnome/KDE with both wayland and X11 as backend)
Setting `windows[ { ..., decorations: false } ]` works on gnome but is completely ignored on KDE (on wayland only)
The reason behind the decorations being shown is due to tauri running under XWayland

Electron behaves correctly on both.

### Reproduction

1. Goto tauri.conf.json
2. Set any of your windows to `visible: false`
3. Watch it appear anyway

### Expected behavior

Have window hidden

### Platform and versions

Environment
  › OS: Linux Rolling Release X64 (Arch)
  › Node.js: 16.19.0
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.67.0
  › cargo: 1.67.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 
 
 DE's tested:
  ›  Gnome 43 @ Wayland & X11
  ›  KDE 5.26 @ Wayland & X11

### Additional context

My tauri config file:

```json
{
  "build": {
    "beforeDevCommand": "yarn dev",
    "beforeBuildCommand": "yarn build",
    "devPath": "http://localhost:1420",
    "distDir": "../dist",
    "withGlobalTauri": false
  },
  "package": {
    "productName": "anima-desktop",
    "version": "0.0.1"
  },
  "tauri": {
    "allowlist": {
      "all": false,
      "http": {
        "all": true,
        "request": true,
        "scope": ["http://localhost:5000/*"]
      },
      "shell": {
        "all": false,
        "open": true
      }
    },
    "bundle": {
      "active": true,
      "category": "Entertainment",
      "copyright": "",
      "deb": {
        "depends": []
      },
      "externalBin": [
        "proxy/main"
      ],
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "identifier": "com.anima.moe",
      "longDescription": "",
      "macOS": {
        "entitlements": null,
        "exceptionDomain": "",
        "frameworks": [],
        "providerShortName": null,
        "signingIdentity": null
      },
      "resources": [],
      "shortDescription": "",
      "targets": "all",
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "security": {
      "csp": null
    },
    "updater": {
      "active": false,
      "endpoints": [
        "https://api.anima.moe/app/{{target}}/{{current_version}}"
      ],
      "dialog": true,
      "pubkey": ""
    },
    "windows": [
      {
        "label": "main",
        "fullscreen": false,
        "height": 900,
        "width": 1600,
        "minWidth": 1360,
        "minHeight": 720,
        "resizable": true,
        "title": "Λ ＮＩＭ Λ - [あーにま • Alpha]",
        "visible": false,
        "transparent": true
      },
      {
        "width": 1200,
        "height": 650,
        "maxWidth": 1200,
        "maxHeight": 650,
        "minWidth": 920,
        "minHeight": 500,
        "decorations": false,
        "url": "/splashscreen",
        "transparent": true,
        "resizable": true,
        "label": "splashscreen",
        "title": "Λ ＮＩＭ Λ - Login"
      }
    ]
  }
}
```

**Comment by amrbashir** [comment]
Just tested on KDE x11 and both properties work fine.

**Comment by amrbashir** [comment]
Just tested on Gnome and it works too, closing until someone else confirms the same behavior.

**Comment by nodgear** [comment]
> Just tested on KDE x11 and both properties work fine.

Have you tested on Wayland?
> completely ignored on KDE (on wayland only)

**Comment by amrbashir** [comment]
visible is expected to not work on Wayland, it is what it is unfortunately. Wayland doesn't have an API to hide/show the window.

**Comment by nodgear** [comment]
> visible is expected to not work on Wayland, it is what it is unfortunately. Wayland doesn't have an API to hide/show the window.
Understandable, wayland is still on it's way.

What about hiding decorations? is there any API to hide it considering it's running via XWayland

**Comment by amrbashir** [comment]
try using `GDK_BACKEND="wayland"`
