### ISSUE TITLE
`relaunch` doesn't call `beforeDevCommand` on dev mode

### ISSUE THREAD

**Issue by takkuumi** [tauri-apps/tauri#6163]
### Describe the bug

`relaunch` doesn't call `beforeDevCommand` on dev mode

### Platform and versions

  › OS: Mac OS 13.2.0 X64
  › Node.js: 18.13.0
  › npm: 8.19.3
  › pnpm: Not installed!
  › yarn: 3.2.1
  › rustup: 1.25.1
  › rustc: 1.69.0-nightly
  › cargo: 1.69.0-nightly
  › Rust toolchain: nightly-x86_64-apple-darwin

**Comment by amrbashir** [comment]
`beforeDevCommand` is inteded to be ran only once, could you explain a bit why you need it to run before each relaunch?

**Comment by RSS1102** [comment]
He may be able to start the program `pnpm tauri dev` normally after using `relaunch` in dev mode

**Comment by amrbashir** [comment]
closing for lack of information
