### ISSUE TITLE
[bug] Cargo build fails on latest version of next

### ISSUE THREAD

**Issue by myname1111** [tauri-apps/tauri#6176]
### Describe the bug

When I ran cargo run, update, or check I get the following error ```error: failed to select a version for the requirement `rfd = "^0.10"```

### Reproduction

1. Create a new cargo project
2. Run `cargo tauri init`
3. Edit the Cargo.toml to use the next branch
4. Run cargo build

### Expected behavior

My project to compile

### Platform and versions

Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 109.0.1518.70
  › MSVC: 
      - Visual Studio Build Tools 2019
  › Node.js: 16.17.0
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.66.1
  › cargo: 1.66.1
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.1
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: git+https://github.com/tauri-apps/tauri?branch=next#553a81f48cf0819ef06020327113f79995e70c1a (2.0.0-alpha.2),
  › tauri-build [RUST]: git+https://github.com/tauri-apps/tauri?branch=next#553a81f48cf0819ef06020327113f79995e70c1a (2.0.0-alpha.0),
  › tao [RUST]: 0.17.0,
  › wry [RUST]: 0.25.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../frontend/dist
  › devPath: http://localhost/
package.json not found

App directory structure
  ├─ .git
  ├─ common
  ├─ frontend
  ├─ server
  ├─ src
  ├─ src-tauri
  └─ target

### Stack trace

```shell
thread 'main' panicked at 'Unable to parse Cargo.toml, `cargo metadata` exited with an error: warning: skipping duplicate package `api` found at `C:\Users\Aryabima Pratama\.cargo\git\checkouts\tauri-9dcc2f9152472c1a\553a81f\examples\web\core\api`
warning: skipping duplicate package `app` found at `C:\Users\Aryabima Pratama\.cargo\git\checkouts\tauri-9dcc2f9152472c1a\553a81f\tooling\cli\node\test\jest\fixtures\app\src-tauri`
    Updating crates.io index
    Updating git repository `https://github.com/PolyMeilex/rfd`
error: failed to select a version for the requirement `rfd = "^0.10"`
candidate versions found which didn't match: 0.11.0
location searched: Git repository https://github.com/PolyMeilex/rfd
required by package `tauri v2.0.0-alpha.2 (https://github.com/tauri-apps/tauri?branch=next#553a81f4)`
    ... which satisfies git dependency `tauri` (locked to 2.0.0-alpha.2) of package `app v0.1.0 (E:\Rust Projects\flashcards_app\src-tauri)`
', C:\Users\$USER\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-make-0.36.4\src/lib\environment\crateinfo.rs:277:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Additional context

I'm trying to build an android project using mostly rust so I'm using yew for the frontend, and since my app requires a server, actix-web for my backend

**Comment by FabianLars** [comment]
Can you try the `rfd101` branch from #6174 ? (make sure to run `cargo update` after changing it)

**Comment by myname1111** [comment]
I can confirm that it works on that branch
