### ISSUE TITLE
[feat] Need a better fs permission design

### ISSUE THREAD

**Issue by ac009527** [tauri-apps/tauri#6184]
### Describe the problem

If I now need to iterate through the filenames to read the files under $HOME/.notes
I need:
`const files = await fs.readDir('.note',{dir:fs.BaseDirectory.Home})` // That's fine and dandy
`await fs.readTextFile(files[1].path.replace(await path.homeDir(),''),{dir:fs.BaseDirectory.Home}) `// but this is so bad he's hard to simplify

### Describe the solution you'd like

No more suggestions, just thought maybe it would be appropriate to follow the nodejs fs design and not pass option.dir

**Comment by FabianLars** [comment]
the dir option is not required and absolute paths should work too.
