### ISSUE TITLE
[feat]  Updater JSON add property to link to sig file url

### ISSUE THREAD

**Issue by jgunzelman88** [tauri-apps/tauri#6190]
### Describe the problem

I use github for distribution and I staticially serve the update json file.  Currently I have to update the signature manually.  I would like to point to the auto generated signature file in my github release.  

### Describe the solution you'd like

Add an optional field to point to a signature file rather than embed the signature in the json file.

**Comment by FabianLars** [comment]
I'm not one of our security experts but to me this sounds like it would completely defeat the purpose of the signature (verifying that the file downloaded from the CDN was not tampered with on the server, or over the network).

Also it looks like you're using `tauri-action` which can generate the updater json file for you if you use it from git (`tauri-apps/tauri-action@dev` for example).

**Comment by jgunzelman88** [comment]
I would argue it's the same as putting the signature in the update.json. if the CDN is compromised then the also have access to my update.json.  Also the signature is public not secret it would still fail validation unless they sign with the private key.

**Comment by jgunzelman88** [comment]
Also it's not really helpful for the update.json to be in the release artifacts.  Since the endpoint to get assets changes with every release and you can only provide one link to pull the update.json

**Comment by FabianLars** [comment]
> I would argue it's the same as putting the signature in the update.json. if the CDN is compromised then the also have access to my update.json

Well, the json file may not be on the same server or cluster, and may not even be a physical file (with the updater server approach).

> Also it's not really helpful for the update.json to be in the release artifacts. Since the endpoint to get assets changes with every release and you can only provide one link to pull the update.json

You can often just point it to <https://github.com/user/project/releases/latest/download/latest.json>.
Or alternatively you could extend the workflow to automatically commit the file, or create a PR with it at least, or upload it to an existing gist, etc.

**Comment by jgunzelman88** [comment]
> Well, the json file may not be on the same server or cluster, and may not even be a physical file (with the updater server approach).

True But from your own documentation : The signature is the content of the generated .sig file. The signature can be uploaded to GitHub safely or made public if your private key is secure. https://tauri.app/v1/guides/distribution/updater/#bundler-artifacts

> You can often just point it to https://github.com/user/project/releases/latest/download/latest.json.
Or alternatively you could extend the workflow to automatically commit the file, or create a PR with it at least, or upload it to an existing gist, etc.

No you can't the download links do not support latest. Github provides a rest api to get the latest release and it's download link to it's specific version.

**Comment by jgunzelman88** [comment]
I have created a work around for now. But it's still a manual process :/

**Comment by FabianLars** [comment]
> True But from your own documentation : ...

Yeah it says that it's fine that it's public, but we're talking about making sure that it stays the same file/content. i may just be overly cautious/paranoid here idk.

> No you can't the download links do not support latest. Github provides a rest api to get the latest release and it's download link to it's specific version.

https://github.com/poketrax/PokeTrax/releases/latest/download/PokeTrax.app.tar.gz
https://github.com/mantou132/nesbox/releases/latest/download/latest-version.json (that's not generated via tauri-action but still works if you want to try it out real quick without uploading a json file yourself)

**Comment by cage1618** [comment]
how to use updater both msi and nsis？

the static json file only special one type fields
