### ISSUE TITLE
[bug] Window opening incorrect URL in release build

### ISSUE THREAD

**Issue by pieterdd** [tauri-apps/tauri#6195]
### Describe the bug

I have a minimal reproduction case available here:
https://github.com/pieterdd/multiwin-repro

This is what I see when running `yarn tauri dev`:
![image](https://user-images.githubusercontent.com/1407980/216763920-6f08866c-884b-4ca4-b66b-ac0b6074445b.png)

Here is what I see when running `yarn tauri build` and then starting the release build (`src-tauri/target/release/multiwin-repro.exe`):
![image](https://user-images.githubusercontent.com/1407980/216764004-b3cf0768-d47e-46b5-90b8-5ba1492829e2.png)

### Reproduction

1. Check out https://github.com/pieterdd/multiwin-repro
2. Run `yarn`
3. Run `yarn tauri build`
4. Run `src-tauri\target\release\multiwin-repro.exe`

### Expected behavior

Window B should open `b.html` instead of `index.html`.

### Platform and versions

Despite the output below, I'm running Windows 11.

```
Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 109.0.1518.70
  › MSVC:
      - Visual Studio Build Tools 2022
  › Node.js: 18.12.1
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.66.1
  › cargo: 1.66.1
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › bundler: Vite

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ dist
  ├─ node_modules
  ├─ src
  └─ src-tauri
Done in 9.05s.
```

**Comment by FabianLars** [comment]
The issue seems to be that b.html is missing in your dist dir, therefore tauri will fall back to the index file.

If you don't need vite to modify it in any way you can use vite's public folder <https://vitejs.dev/guide/build.html#public-base-path>. If you do need vite to modify it, for example because you're using a J's framework, you could look into vite's multi-page app mode (on the same page as the other one)

**Comment by pieterdd** [comment]
I think I understand where you're coming from. Still, it might be helpful to produce an error during compilation (or at runtime as last resort) when this happens.

As a user of Tauri, I haven't interacted with Vite at all. I'm configuring Tauri in `tauri.conf.json`, which so far has handled everything behind the scenes. I noticed that this includes editing `Cargo.toml` to activate system tray features if I define a system tray icon, for example. So if I configure a new local HTML page as URL, I assume Tauri will reconfigure its internals accordingly too.

In my real app, `b.html` relies on bundling and Svelte, so I'll suppose I'll need to adjust additional config. Is it safe to edit `vite.config.js` directly, or will that conflict with Tauri's internal config management?

**Comment by FabianLars** [comment]
There won't be anz conflict, no. Tauri does not touch your frontend configuration files. Or as i always like to say, "Tauri does not care about your frontend" - as in, you can use whatever stack and configuration you want, Tauri only needs to know it's location (devPath and distDIr), the rest is up to you and your frontend.

This is also why it doesn't verify your distDIr contents, it simply doesn't know how it's supposed to look like with the sheer amount of frontend tech stacks and config options.

**Comment by pieterdd** [comment]
Thank you for sharing the philosophy.

As per [Vite's instructions](https://vitejs.dev/guide/build.html#multi-page-app), I've added a second input for `b.html` and now it's working.

```
    rollupOptions: {
      input: {
        index: resolve(__dirname, 'index.html'),
        b: resolve(__dirname, 'b.html'),
      },
    }
```

For posterity, I've filed https://github.com/tauri-apps/tauri-docs/pull/1101 to amend the documentation.
