### ISSUE TITLE
[bug] Trying to make Steam Overlay work with Tauri

### ISSUE THREAD

**Issue by Elanis** [tauri-apps/tauri#6196]
Hi !

This issue is a follow up to a conversation on [Discord](https://discord.com/channels/616186924390023171/1071444181903491132/1071444181903491132).

I'm trying to make Steam overlay work on a Tauri app, but it doesn't show up. It doesn't show up when user is interacting AND when user is passive (e.g. unlocking an achievement).

This mean the bug is probably because it cannot hook to the program.

Note: every idea tried was:
- In debug mode launched from CLI
- In release mode launched directly from Steam

Here's what [Steamworks Documentation](https://partner.steamgames.com/doc/features/overlay) says about Steam Overlay:
> Your game does not need to do anything special for the overlay to work, it automatically hooks into any game launched from Steam! While in development and running your game in a debugger, the overlay is loaded when you call SteamAPI_Init. As such you'll need to make sure to call SteamAPI_Init prior to initializing the OpenGL/D3D device, otherwise it won't be able to hook the device creation.
> 
> The overlay supports games that use DirectX 7 - 12, OpenGL, Metal, and Vulkan. The overlay will not be active in software-rasterized games.

And from my own experience, I know that browser based game works with Steam overlay (tried with Electron and nw.js).

I tried using [steamworks-rs](https://github.com/Noxime/steamworks-rs) two ways:
```rs
fn main() {
    let (client, _single) = match Client::init() {
        Ok((client, _single)) => (client, _single),
        Err(error) => panic!("Error while connecting to Steam: {:?}", error),
    };

    tauri::Builder::default()
        .manage(client)
        .setup(|app| {
            app.asset_protocol_scope().allow_directory(std::env::current_dir()?, true)?;

            Ok(())
        })
        .invoke_handler(tauri::generate_handler![get_steam_id, get_steam_auth_ticket, get_steam_language])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```
or
```rs
    tauri::Builder::default()
        .setup(|app| {
            app.asset_protocol_scope().allow_directory(std::env::current_dir()?, true)?;

            let (client, _single) = match Client::init() {
                Ok((client, _single)) => (client, _single),
                Err(error) => panic!("Error while connecting to Steam: {:?}", error),
            };

            app.manage(client);

            println!("Setup");

            Ok(())
        })
        .invoke_handler(tauri::generate_handler![get_steam_id, get_steam_auth_ticket, get_steam_language])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
```
But it doesn't work. Note that `Client::init()` calls `SteamAPI_init` under the hood, see [this function in steamworks-rs repo](https://github.com/Noxime/steamworks-rs/blob/3f3abe9660b02f333c25484a15b755e5269cda48/src/lib.rs#L160).

I don't know a lot about Tauri internals or lifecycle, so maybe I missed something. That's why I'm here. Does someone in the team understand what could be my bug ?

I understand that Tauri isn't made for games, but maybe it's a bug from my usage and someone can help me 😄 

Thanks !

### Platform and versions

Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 109.0.1518.70
  › MSVC:
      - Visual Studio Build Tools�2019
  › Node.js: 18.12.1
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.67.0
  › cargo: 1.67.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: build
  › CSP: default-src 'self'; img-src 'self' asset: https://asset.localhost; connect-src http://localhost:9876 ws://localhost:9876
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React
  › bundler: Vite

App directory structure
  ├─ .git
  ├─ .github
  ├─ dist
  ├─ i18n
  ├─ node_modules
  ├─ public
  ├─ src
  ├─ src-tauri
  └─ steam-dll

**Comment by amrbashir** [comment]
Maybe related to https://github.com/tauri-apps/wry/issues/451 but you could try opening the overlay manually using https://partner.steamgames.com/doc/api/ISteamFriends#ActivateGameOverlay just to see if the overlay is attached correctly.

**Comment by Elanis** [comment]
Hi, I tried indeed and it doesn't work. I tried:
- Shift tab
- Triggering overlay from code
- Triggering achievements

None of these ideas shows anything over the game (Overlay or notifications) :/ So, that's why I'm guessing it's really not hooking.

**Comment by amrbashir** [comment]
Ah I think I understand now, if I understand the following correctly,

> As such you'll need to make sure to call SteamAPI_Init prior to initializing the OpenGL/D3D device, otherwise it won't be able to hook the device creation.

then steam injects its overlay into the OpenGL/D3D APIs, however, tauri doesn't use any of these directly and I am not sure how the WebView2 renders tbh since its code is closed-source. 

I will close this as I don't see it as a bug but if you want, open an issue upstream in WebView2 repo, maybe it is worth discussing steam integration with webview2.

**Comment by Elanis** [comment]
Thanks for your feedback, I will try to get informations on WebView2 repo, it's worth trying :)

**Comment by skymen** [comment]
For anyone wondering, here's an interesting article made by the lead developer of Construct about that issue of rendering the Steam Overlay over WebView2
https://www.construct.net/en/blogs/ashleys-blog-2/trying-show-steam-overlay-1861

I don't think there's anything that Tauri can do to fix this. It either needs to be fixed by WebView2 or by Steam

**Comment by CosmoLau** [comment]
What's new on this issue?

**Comment by Elanis** [comment]
Not working yet and I didn't have time to contact Valve or try more things. For the moment, I accepted I wouldn't have a Steam overlay.

**Comment by Armaldio** [comment]
Hey guys :wave: 

I'm exploring this issue again and have posted a new discussion about it if you're interested or have made progress: https://github.com/tauri-apps/tauri/discussions/11944

**Comment by jzade** [comment]
> Hi !
> 
> This issue is a follow up to a conversation on [Discord](https://discord.com/channels/616186924390023171/1071444181903491132/1071444181903491132).
> 
> I'm trying to make Steam overlay work on a Tauri app, but it doesn't show up. It doesn't show up when user is interacting AND when user is passive (e.g. unlocking an achievement).
> 
> This mean the bug is probably because it cannot hook to the program.
> 
> Note: every idea tried was:
> 
> * In debug mode launched from CLI
> * In release mode launched directly from Steam
> 
> Here's what [Steamworks Documentation](https://partner.steamgames.com/doc/features/overlay) says about Steam Overlay:
> 
> > Your game does not need to do anything special for the overlay to work, it automatically hooks into any game launched from Steam! While in development and running your game in a debugger, the overlay is loaded when you call SteamAPI_Init. As such you'll need to make sure to call SteamAPI_Init prior to initializing the OpenGL/D3D device, otherwise it won't be able to hook the device creation.
> > The overlay supports games that use DirectX 7 - 12, OpenGL, Metal, and Vulkan. The overlay will not be active in software-rasterized games.
> 
> And from my own experience, I know that browser based game works with Steam overlay (tried with Electron and nw.js).
> 
> I tried using [steamworks-rs](https://github.com/Noxime/steamworks-rs) two ways:
> 
> fn main() {
>     let (client, _single) = match Client::init() {
>         Ok((client, _single)) => (client, _single),
>         Err(error) => panic!("Error while connecting to Steam: {:?}", error),
>     };
> 
>     tauri::Builder::default()
>         .manage(client)
>         .setup(|app| {
>             app.asset_protocol_scope().allow_directory(std::env::current_dir()?, true)?;
> 
>             Ok(())
>         })
>         .invoke_handler(tauri::generate_handler![get_steam_id, get_steam_auth_ticket, get_steam_language])
>         .run(tauri::generate_context!())
>         .expect("error while running tauri application");
> }
> or
> 
>     tauri::Builder::default()
>         .setup(|app| {
>             app.asset_protocol_scope().allow_directory(std::env::current_dir()?, true)?;
> 
>             let (client, _single) = match Client::init() {
>                 Ok((client, _single)) => (client, _single),
>                 Err(error) => panic!("Error while connecting to Steam: {:?}", error),
>             };
> 
>             app.manage(client);
> 
>             println!("Setup");
> 
>             Ok(())
>         })
>         .invoke_handler(tauri::generate_handler![get_steam_id, get_steam_auth_ticket, get_steam_language])
>         .run(tauri::generate_context!())
>         .expect("error while running tauri application");
> But it doesn't work. Note that `Client::init()` calls `SteamAPI_init` under the hood, see [this function in steamworks-rs repo](https://github.com/Noxime/steamworks-rs/blob/3f3abe9660b02f333c25484a15b755e5269cda48/src/lib.rs#L160).
> 
> I don't know a lot about Tauri internals or lifecycle, so maybe I missed something. That's why I'm here. Does someone in the team understand what could be my bug ?
> 
> I understand that Tauri isn't made for games, but maybe it's a bug from my usage and someone can help me 😄
> 
> Thanks !
> 
> ### Platform and versions
> Environment › OS: Windows 10.0.22621 X64 › Webview2: 109.0.1518.70 › MSVC: - Visual Studio Build Tools�2019 › Node.js: 18.12.1 › npm: 8.19.2 › pnpm: Not installed! › yarn: Not installed! › rustup: 1.25.1 › rustc: 1.67.0 › cargo: 1.67.0 › Rust toolchain: stable-x86_64-pc-windows-msvc
> 
> Packages › @tauri-apps/cli [NPM]: 1.2.3 › @tauri-apps/api [NPM]: 1.2.0 › tauri [RUST]: 1.2.4, › tauri-build [RUST]: 1.2.1, › tao [RUST]: 0.15.8, › wry [RUST]: 0.23.4,
> 
> App › build-type: build › CSP: default-src 'self'; img-src 'self' asset: https://asset.localhost; connect-src http://localhost:9876 ws://localhost:9876 › distDir: ../dist › devPath: http://localhost:1420/ › framework: React › bundler: Vite
> 
> App directory structure ├─ .git ├─ .github ├─ dist ├─ i18n ├─ node_modules ├─ public ├─ src ├─ src-tauri └─ steam-dll



> Hi !
> 
> This issue is a follow up to a conversation on [Discord](https://discord.com/channels/616186924390023171/1071444181903491132/1071444181903491132).
> 
> I'm trying to make Steam overlay work on a Tauri app, but it doesn't show up. It doesn't show up when user is interacting AND when user is passive (e.g. unlocking an achievement).
> 
> This mean the bug is probably because it cannot hook to the program.
> 
> Note: every idea tried was:
> 
> * In debug mode launched from CLI
> * In release mode launched directly from Steam
> 
> Here's what [Steamworks Documentation](https://partner.steamgames.com/doc/features/overlay) says about Steam Overlay:
> 
> > Your game does not need to do anything special for the overlay to work, it automatically hooks into any game launched from Steam! While in development and running your game in a debugger, the overlay is loaded when you call SteamAPI_Init. As such you'll need to make sure to call SteamAPI_Init prior to initializing the OpenGL/D3D device, otherwise it won't be able to hook the device creation.
> > The overlay supports games that use DirectX 7 - 12, OpenGL, Metal, and Vulkan. The overlay will not be active in software-rasterized games.
> 
> And from my own experience, I know that browser based game works with Steam overlay (tried with Electron and nw.js).
> 
> I tried using [steamworks-rs](https://github.com/Noxime/steamworks-rs) two ways:
> 
> fn main() {
>     let (client, _single) = match Client::init() {
>         Ok((client, _single)) => (client, _single),
>         Err(error) => panic!("Error while connecting to Steam: {:?}", error),
>     };
> 
>     tauri::Builder::default()
>         .manage(client)
>         .setup(|app| {
>             app.asset_protocol_scope().allow_directory(std::env::current_dir()?, true)?;
> 
>             Ok(())
>         })
>         .invoke_handler(tauri::generate_handler![get_steam_id, get_steam_auth_ticket, get_steam_language])
>         .run(tauri::generate_context!())
>         .expect("error while running tauri application");
> }
> or
> 
>     tauri::Builder::default()
>         .setup(|app| {
>             app.asset_protocol_scope().allow_directory(std::env::current_dir()?, true)?;
> 
>             let (client, _single) = match Client::init() {
>                 Ok((client, _single)) => (client, _single),
>                 Err(error) => panic!("Error while connecting to Steam: {:?}", error),
>             };
> 
>             app.manage(client);
> 
>             println!("Setup");
> 
>             Ok(())
>         })
>         .invoke_handler(tauri::generate_handler![get_steam_id, get_steam_auth_ticket, get_steam_language])
>         .run(tauri::generate_context!())
>         .expect("error while running tauri application");
> But it doesn't work. Note that `Client::init()` calls `SteamAPI_init` under the hood, see [this function in steamworks-rs repo](https://github.com/Noxime/steamworks-rs/blob/3f3abe9660b02f333c25484a15b755e5269cda48/src/lib.rs#L160).
> 
> I don't know a lot about Tauri internals or lifecycle, so maybe I missed something. That's why I'm here. Does someone in the team understand what could be my bug ?
> 
> I understand that Tauri isn't made for games, but maybe it's a bug from my usage and someone can help me 😄
> 
> Thanks !
> 
> ### Platform and versions
> Environment › OS: Windows 10.0.22621 X64 › Webview2: 109.0.1518.70 › MSVC: - Visual Studio Build Tools�2019 › Node.js: 18.12.1 › npm: 8.19.2 › pnpm: Not installed! › yarn: Not installed! › rustup: 1.25.1 › rustc: 1.67.0 › cargo: 1.67.0 › Rust toolchain: stable-x86_64-pc-windows-msvc
> 
> Packages › @tauri-apps/cli [NPM]: 1.2.3 › @tauri-apps/api [NPM]: 1.2.0 › tauri [RUST]: 1.2.4, › tauri-build [RUST]: 1.2.1, › tao [RUST]: 0.15.8, › wry [RUST]: 0.23.4,
> 
> App › build-type: build › CSP: default-src 'self'; img-src 'self' asset: https://asset.localhost; connect-src http://localhost:9876 ws://localhost:9876 › distDir: ../dist › devPath: http://localhost:1420/ › framework: React › bundler: Vite
> 
> App directory structure ├─ .git ├─ .github ├─ dist ├─ i18n ├─ node_modules ├─ public ├─ src ├─ src-tauri └─ steam-dll

I believe we have made progress on a solution for windows: https://github.com/PSG-Team/tauri-steam-overlay-surface

**Comment by jzade** [comment]
> Hi !
> 
> This issue is a follow up to a conversation on [Discord](https://discord.com/channels/616186924390023171/1071444181903491132/1071444181903491132).
> 
> I'm trying to make Steam overlay work on a Tauri app, but it doesn't show up. It doesn't show up when user is interacting AND when user is passive (e.g. unlocking an achievement).
> 
> This mean the bug is probably because it cannot hook to the program.
> 
> Note: every idea tried was:
> 
> * In debug mode launched from CLI
> * In release mode launched directly from Steam
> 
> Here's what [Steamworks Documentation](https://partner.steamgames.com/doc/features/overlay) says about Steam Overlay:
> 
> > Your game does not need to do anything special for the overlay to work, it automatically hooks into any game launched from Steam! While in development and running your game in a debugger, the overlay is loaded when you call SteamAPI_Init. As such you'll need to make sure to call SteamAPI_Init prior to initializing the OpenGL/D3D device, otherwise it won't be able to hook the device creation.
> > The overlay supports games that use DirectX 7 - 12, OpenGL, Metal, and Vulkan. The overlay will not be active in software-rasterized games.
> 
> And from my own experience, I know that browser based game works with Steam overlay (tried with Electron and nw.js).
> 
> I tried using [steamworks-rs](https://github.com/Noxime/steamworks-rs) two ways:
> 
> fn main() {
>     let (client, _single) = match Client::init() {
>         Ok((client, _single)) => (client, _single),
>         Err(error) => panic!("Error while connecting to Steam: {:?}", error),
>     };
> 
>     tauri::Builder::default()
>         .manage(client)
>         .setup(|app| {
>             app.asset_protocol_scope().allow_directory(std::env::current_dir()?, true)?;
> 
>             Ok(())
>         })
>         .invoke_handler(tauri::generate_handler![get_steam_id, get_steam_auth_ticket, get_steam_language])
>         .run(tauri::generate_context!())
>         .expect("error while running tauri application");
> }
> or
> 
>     tauri::Builder::default()
>         .setup(|app| {
>             app.asset_protocol_scope().allow_directory(std::env::current_dir()?, true)?;
> 
>             let (client, _single) = match Client::init() {
>                 Ok((client, _single)) => (client, _single),
>                 Err(error) => panic!("Error while connecting to Steam: {:?}", error),
>             };
> 
>             app.manage(client);
> 
>             println!("Setup");
> 
>             Ok(())
>         })
>         .invoke_handler(tauri::generate_handler![get_steam_id, get_steam_auth_ticket, get_steam_language])
>         .run(tauri::generate_context!())
>         .expect("error while running tauri application");
> But it doesn't work. Note that `Client::init()` calls `SteamAPI_init` under the hood, see [this function in steamworks-rs repo](https://github.com/Noxime/steamworks-rs/blob/3f3abe9660b02f333c25484a15b755e5269cda48/src/lib.rs#L160).
> 
> I don't know a lot about Tauri internals or lifecycle, so maybe I missed something. That's why I'm here. Does someone in the team understand what could be my bug ?
> 
> I understand that Tauri isn't made for games, but maybe it's a bug from my usage and someone can help me 😄
> 
> Thanks !
> 
> ### Platform and versions
> Environment › OS: Windows 10.0.22621 X64 › Webview2: 109.0.1518.70 › MSVC: - Visual Studio Build Tools�2019 › Node.js: 18.12.1 › npm: 8.19.2 › pnpm: Not installed! › yarn: Not installed! › rustup: 1.25.1 › rustc: 1.67.0 › cargo: 1.67.0 › Rust toolchain: stable-x86_64-pc-windows-msvc
> 
> Packages › @tauri-apps/cli [NPM]: 1.2.3 › @tauri-apps/api [NPM]: 1.2.0 › tauri [RUST]: 1.2.4, › tauri-build [RUST]: 1.2.1, › tao [RUST]: 0.15.8, › wry [RUST]: 0.23.4,
> 
> App › build-type: build › CSP: default-src 'self'; img-src 'self' asset: https://asset.localhost; connect-src http://localhost:9876 ws://localhost:9876 › distDir: ../dist › devPath: http://localhost:1420/ › framework: React › bundler: Vite
> 
> App directory structure ├─ .git ├─ .github ├─ dist ├─ i18n ├─ node_modules ├─ public ├─ src ├─ src-tauri └─ steam-dll

please take a look at this solution as we have this working on win 11: https://github.com/PSG-Team/tauri-steam-overlay-surface?tab=readme-ov-file
