### ISSUE TITLE
[feat] 

### ISSUE THREAD

**Issue by happysmile12321** [tauri-apps/tauri#6210]
### Describe the problem

Mobile starts slow

### Describe the solution you'd like

why not use flutter on mobile platform? Then we can use flutter's ecosystem.
considier on compile time, ts -> dart -> flutter.

**Comment by FabianLars** [comment]
Flutter is not a webview so this is basically impossible. And we can't just transpile ts to dart without loosing all the APIs you expect from a webview/browser.

In case you know these other projects, this is the same as if you'd ask the Ionic or Capacitor maintainers for a flutter backend.
