### ISSUE TITLE
[bug] Incorrect DPI scaling when using non-integer scaling on Linux/X11

### ISSUE THREAD

**Issue by thep0y** [tauri-apps/tauri#6224]
### Describe the bug

Use default environment variables and default tauri configuration:

![image](https://user-images.githubusercontent.com/51874567/217772987-9672f4d3-9515-45c7-b4e7-4b29d6a27a08.png)

After setting `GDK_SCALE=2 GDK_DPI_SCALE=0.5`:

![image](https://user-images.githubusercontent.com/51874567/217774711-4ee530d8-9040-4611-8ef9-2d1548624837.png)

### Reproduction

1. Create a new tauri project
2. Run the project on a HiDPI display(3840x2160) scaled 150%

### Expected behavior

The scaling should be consistent with firefox which also uses GTK.

### Platform and versions

Environment
  › OS: Arch Linux Unknown X64
  › Node.js: 18.14.0
  › npm: 8.19.2
  › pnpm: 7.25.0
  › yarn: Not installed!
  › rustup: Not installed!
  › rustc: 1.67.0
  › cargo: 1.67.0
  › Rust toolchain: 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Vue.js
  › bundler: Vite

App directory structure
  ├─ src
  ├─ .git
  ├─ src-tauri
  ├─ node_modules
  └─ public

### Additional context

```bash
$ neofetch
                   -`                    thepoy@thepoy-arch 
                  .o+`                   ------------------ 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: xxxxxxxxxxxx
               `+oooooo:                 Kernel: 6.1.9-arch1-2 
               -+oooooo+:                Uptime: 3 hours, 43 mins 
             `/:-:++oooo+:               Packages: 981 (pacman) 
            `/++++/+++++++:              Shell: fish 3.6.0 
           `/++++++++++++++:             Resolution: 3840x2160 
          `/+++ooooooooooooo/`           DE: Plasma 5.26.5 
         ./ooosssso++osssssso+`          WM: KWin 
        .oossssso-````/ossssss+`         Theme: [Plasma], Breeze [GTK2/3] 
       -osssssso.      :ssssssso.        Icons: Papirus-Light [Plasma], Papirus-Light [GTK2/3] 
      :osssssss/        osssso+++.       Terminal: vscode 
     /ossssssss/        +ssssooo/-       CPU: AMD Ryzen 7 5800H with Radeon Graphics (16) @ 3.200GHz 
   `/ossssso+/:-        -:/+osssso+-     GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
  `+sso+:-`                 `.-/+oso:    Memory: 11022MiB / 15345MiB
```

**Comment by FabianLars** [comment]
Could you also try the epiphany browser (also known as Gnome Web)? It's a browser based on webkitgtk which we use for the webview on Linux.

**Comment by thep0y** [comment]
The scaling of the epiphany is also incorrect:
![image](https://user-images.githubusercontent.com/51874567/217789013-4df940ad-162b-4142-869e-a8847981445c.png)

**Comment by FabianLars** [comment]
that would suggest to me that it's a webkitgtk issue 🤔

**Comment by amrbashir** [comment]
Unfortunately this is a GTK problem, see https://wiki.archlinux.org/title/HiDPI#Fractional_scaling
> Note: GTK does not and has no plans to support DPI scaling on all elements except fonts. Therefore, fractional scaling on gnome uses oversampling, which means rendering at a higher resolution, then scaling down with integer scaling, and is true for both wayland and xorg sessions. This brings higher GPU and CPU (since GTK is not fully hardware accelerated) usage, more power consumption, and in some cases significantly slower responsiveness, particularly noticeable in xorg. If it's necessary to avoid these problems, consider switching to a Qt based desktop environment.

also see https://gitlab.gnome.org/GNOME/gtk/-/issues/4345

**Comment by thep0y** [comment]
> Unfortunately this is a GTK problem, see https://wiki.archlinux.org/title/HiDPI#Fractional_scaling
>
> also see https://gitlab.gnome.org/GNOME/gtk/-/issues/4345

So, is there any new plan for tauri on linux platform? Like when will servo officially replace webkitgtk?

**Comment by FabianLars** [comment]
> So, is there any new plan for tauri on linux platform?

Not really, no. we know using webkitgtk is not even close to ideal, but there still isn't really a _feasible_ alternative right now.

> Like when will servo officially replace webkitgtk?

That will take a _long_ time. Also it's not supposed to replace it as it probably won't ever have complete feature parity, it's only meant as an alternative.

**Comment by firelizzard18** [comment]
@FabianLars Is QtWebEngine not a feasible alternative?

**Comment by FabianLars** [comment]
> Is QtWebEngine not a feasible alternative?

Not for us, no. https://github.com/tauri-apps/tauri/issues/7477#issuecomment-1646656586

**Comment by elibroftw** [comment]
I think we need to just contribute to webview2 so that it can support linux.

**Comment by FabianLars** [comment]
webview2 is closed source so i don't see how, and since we're talking about microsoft i doubt they'd care about financial contribution either, at least the amount we could come up with. Sadly microsoft doesn't seem to care much about a Linux port yet.

**Comment by elibroftw** [comment]
Ah you're right. What about utilizing the default browser users have installed like Firefox. Is that at all possible via the driver or something?

**Comment by FabianLars** [comment]
I talked a bit about this here: https://github.com/tauri-apps/tauri/discussions/8524#discussioncomment-8013499 - tldr i don't think it's suitable for tauri.

**Comment by 255doesnotexist** [comment]
met this problem on hidpi debian sid too.

**Comment by 0-don** [comment]
having same issue aswell
