### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by 1zun4secondary** [tauri-apps/tauri#6228]
delete

**Comment by FabianLars** [comment]
hmm, one thing i could imagine is that they detected that the page is loaded in a webview 🤔 (which google generally doesn't reallyyy like, at least on desktop).

Do you have an example url we can use to triage this?

**Comment by 1zun4** [comment]
> hmm, one thing i could imagine is that they detected that the page is loaded in a webview 🤔 (which google generally doesn't reallyyy like, at least on desktop).
> 
> Do you have an example url we can use to triage this?

try it here: https://dl.ccbluex.net/download/tauri_test.html

**Comment by 1zun4** [comment]
I have now tested it with WRY directly, this is how it looks:
![image](https://user-images.githubusercontent.com/69533520/218027609-bce259d2-bf0a-49d6-af96-86f5cba88c93.png)
This looks good (only 404 errors - we don't care about those)

Means the issue is with Tauri.

**Comment by amrbashir** [comment]
> try it here: [dl.ccbluex.net/download/tauri_test.html](https://dl.ccbluex.net/download/tauri_test.html)

This url you posted works fine inside a tauri app.

The errors above shows you're trying to use a tauri API in an external URL, however we don't inject tauri APIs in an external URL so the errors make sense.
