### ISSUE TITLE
[bug] `set_icon_as_template` not updating tray icon

### ISSUE THREAD

**Issue by kadiryazici** [tauri-apps/tauri#6240]
### Describe the bug

I have an application that uses system tray icon as template, if this user receives a notification I want to disable icon-as-template to get attention of user.

I call this command but it does not update tray icon.
```rust
#[tauri::command]
pub fn set_icon_template(is_template: bool, app: AppHandle) {
    app.tray_handle().set_icon_as_template(is_template).unwrap();
}
```

For a workaround I currently do this.
```ts
#[tauri::command]
pub fn set_icon_template(is_template: bool, app: AppHandle) {
    app.tray_handle().set_icon_as_template(is_template).unwrap();
    app.tray_handle()
        .set_icon(tauri::Icon::Raw(
            include_bytes!("../icons/tray/icon.png").to_vec(),
        ))
        .unwrap();
}

```

### Reproduction

by default in `tauri.conf.json` set `iconAsTemplate: true`, and then try to update it from commands.

### Expected behavior

It should update tray icon.

### Platform and versions

Environment
  › OS: Mac OS 13.1.0 X64
  › Node.js: 16.18.1
  › npm: 8.19.2
  › pnpm: 7.18.2
  › yarn: 1.22.18
  › rustup: 1.25.1
  › rustc: 1.67.0
  › cargo: 1.67.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Vue.js
  › bundler: Vite

App directory structure
  ├─ dist
  ├─ images
  ├─ node_modules
  ├─ public
  ├─ .github
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  └─ src

**Comment by amrbashir** [comment]
this is the intended behavior actually, it is a bit of a weird design choice but we are stuck with it for v1, we will improve this in v2.
