### ISSUE TITLE
[bug] Windows .exe considered Malware

### ISSUE THREAD

**Issue by mrjackwills** [tauri-apps/tauri#6248]
### Describe the bug

I have just updated by basic tauri application, and upon installing the new version, Windows Security centre suggest that the main .exe now contains `Trojan:Script/Wacatac.H!ml`

### Reproduction

1. Download windows release from [here](https://github.com/mrjackwills/obliqoro/releases/tag/v0.1.0)
2. Install
3. Windows security centre should classify `Obliqoro.exe` as dangerous

### Expected behavior

Tauri application shouldn't set-off antivirus alerts

### Platform and versions

```

Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 109.0.1518.78
  › MSVC: 
      - Visual Studio Build Tools 2022
  › Node.js: 16.17.1
  › npm: 9.2.0
  › pnpm: 7.13.5
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.67.0
  › cargo: 1.67.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:9000/
  › framework: Vue.js
  › bundler: Vite

App directory structure
  ├─ .devcontainer
  ├─ .git
  ├─ .github
  ├─ .vscode
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
  ```

**Comment by FabianLars** [comment]
Duplicate of #2486. Thanks for the report.
