### ISSUE TITLE
`window.tauri` unavailable in <head> when loading assets with no-server

### ISSUE THREAD

**Issue by chippers** [tauri-apps/tauri#625]
**Describe the bug**
When loading assets with the embedded server disabled, mutation observers are injected in the `<body>` and `<head>` watching for new items to load. Because the `tauri.js` script that defines `window.tauri` is loaded in the body, the head is unable to access this object.  This leads to the error: `Unable to get property 'loadAsset' of undefined` for all assets that are attempted to be loaded by the mutation observer in the `<head>`.

**To Reproduce**
1. Have assets to be loaded in the `<head>` (such as stylesheets).
2. Disable embedded server in `tauri.config.json`
3. `yarn tauri build`
4. Check console for the above error message
    * You can also check the generated `index.tauri.html` file to confirm that the mutation observer is referencing `window.tauri` before the script that defines it is injected into the dom

**Expected behavior**
`loadAsset` function in the `<head>` mutation observer should be able to access `window.tauri` and then load the asset properly.

**Platform and Versions (please complete the following information):**
```ps
Operating System - Windows_NT(10.0.18363) - win32/x64

Node.js environment
  Node.js - 12.16.3
  tauri.js - 0.6.2

Rust environment
  rustc - 1.43.1
  cargo - 1.43.0
  tauri-bundler - 0.6.0

Global packages
  NPM - 6.14.4
  yarn - 1.22.4

App directory structure
/.git
/.idea
/dist
/node_modules
/src
/src-tauri

App
  tauri - 0.5
  mode - no-server
  build-type - bundle
  CSP - false
  Windows - Edge
  distDir - ../dist
  devPath - http://localhost:8080
```

**Additional context**
The offending code is this line.  https://github.com/tauri-apps/tauri/blob/4b54cc156496bf7f102785fc631e7ba5ebb80966/cli/tauri.js/src/runner.ts#L287

Changing that to:
```ts
document.head.insertBefore(tauriScript, document.head.firstChild)
```
fixes the issue as it will cause the `tauriScript` to be the first item in the `<head>` allowing other scripts to access `window.tauri`.

I've written this as an issue and not a Pull Request as I'm not familiar with the code base and am unsure if this change is the desired way to go about it. I looked into the history and this became the way to do it after some sort of previous `_INIT_HOOK` way of going about it. Let me know if this change is desired and I'll open a PR.

**Comment by lucasfernog** [comment]
I think you're correct and the script should belong to the head section.
