### ISSUE TITLE
[feat] cargo profile support

### ISSUE THREAD

**Issue by flapili** [tauri-apps/tauri#6255]
### Describe the problem

when we have multiples build variant like dev/stagging/production/beta/alpha/etc... the debug flag is not enough

### Describe the solution you'd like

add an option to the cli like `tauri build --profile foobar`

### Additional context

for now I have to use a custom py script which take a kind of profile, build tauri via subprocess.run then go to `/targets/<triples-target>/release(or debug)/bundle/msi/name-version-arch.zip` to a folder according to the given profile.

**Comment by amrbashir** [comment]
try `tauri build -- --profile foobar`

**Comment by amrbashir** [comment]
Looks like it will conflict with the `--release` that we pass internally, gonna open a PR to fix it

**Comment by bukowa** [comment]
Any chance to get it in `v1`?

**Comment by amrbashir** [comment]
this is already fixed in v1 as well

**Comment by bukowa** [comment]
> this is already fixed in v1 as well

Right it just needs the `--debug` flag to work. Also it has other problems;
``` toml
[profile.testing]
inherits = "dev"
```
```sh
# after removing target dir
$ tauri -- build --debug -- --profile=testing

Finished `testing` profile [unoptimized + debuginfo] target(s) in 49.67s                         
   Error failed to rename `C:\Users\buk\WebstormProjects\ck3oop\target\debug\ck3oop-ui-rs.exe` to
`C:\Users\buk\WebstormProjects\ck3oop\target\debug\ck3oop-ui.exe`: The system cannot find the path specified. (os error 3)
```
Looks like tauri wants to rename something post building but with different profile it just can't?

```toml
[package]
name = "ck3oop-ui-rs"
```

```json
  "package": {
    "productName": "ck3oop-ui",
  },
  ```

**Comment by amrbashir** [comment]
> > this is already fixed in v1 as well
> 
> Right it just needs the `--debug` flag to work. Also it has other problems;

It doesn't need `--debug`, it should work without it

> ```toml
> [profile.testing]
> inherits = "dev"
> ```
> 
> ```shell
> # after removing target dir
> $ tauri -- build --debug -- --profile=testing
> 
> Finished `testing` profile [unoptimized + debuginfo] target(s) in 49.67s                         
>    Error failed to rename `C:\Users\buk\WebstormProjects\ck3oop\target\debug\ck3oop-ui-rs.exe` to
> `C:\Users\buk\WebstormProjects\ck3oop\target\debug\ck3oop-ui.exe`: The system cannot find the path specified. (os error 3)
> ```
> 
> Looks like tauri wants to rename something post building but with different profile it just can't?
> 
> ```toml
> [package]
> name = "ck3oop-ui-rs"
> ```
> 
> ```json
>   "package": {
>     "productName": "ck3oop-ui",
>   },
> ```

It indeed will try to rename your rust binary from `ck3oop-ui-rs` to your product name which is `ck3oop-ui`. I tried with the latest release and it successfully renamed, can you check which tauri cli version are you using? `tauri -V`. Also try `tauri build -- --profile testing` without the `=`

**Comment by bukowa** [comment]
> It indeed will try to rename your rust binary from `ck3oop-ui-rs` to your product name which is `ck3oop-ui`. I tried with the latest release and it successfully renamed, can you check which tauri cli version are you using? `tauri -V`. Also try `tauri build -- --profile testing` without the `=`
```
tauri-cli 1.5.14
```
Oh of course, thank you. It's all about `=` in the arguments.
I guess when they are passed with `--` they aren't properly parsed... my bad.

**Comment by amrbashir** [comment]
I will open a PR to fix this, we should handle that case
