### ISSUE TITLE
[feat] Use JSON5 for json config files

### ISSUE THREAD

**Issue by wesbos** [tauri-apps/tauri#6259]
### Describe the problem

A small but incredibly helpful thing would be to use JSON5 to parse the config file.

I'm debugging some settings right now, and commenting out a line causes the config file to be invalid. 

using JSON5 to parse this file will allow comments, trailing commas, and other JSON niceities. It wont break exisitng JSON, just make it a bit easier to author and document. 

VS Code among other tools already use JSON5. I know there is a Rust crate for it. 

### Describe the solution you'd like

be able to use trailing commas and comment my config file.

**Comment by FabianLars** [comment]
This is already supported. Rename your file to `tauri.conf.json5` and add the `"config-json5"` flag to the tauri and tauri-build feature arrays in Cargo.toml.

**Comment by wesbos** [comment]
Oh awesome, is there a reason to not just parse everything as json5 instead of having to configure it?

**Comment by FabianLars** [comment]
honestly no idea. Maybe to be sure that it didn't break anything (when it was added), or more likely to not add dependencies and compile time if the feature isn't used

**Comment by Prasannajaga** [comment]
@FabianLars  @wesbos 
{
  "allowlist": {
    "shell": {
      "all": true
    }
  }
}

after converting to json5 it the above line is still invalid, any idea ?

**Comment by FabianLars** [comment]
that looks like valid json and json5 but it's v1 syntax, are you trying this in a v2 project maybe?

**Comment by Prasannajaga** [comment]
```
[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.1.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.4.0", features = [] }
tauri-plugin-log = "2.0.0-rc"


```

tauri.conf.json
```
{
  "$schema": "../node_modules/@tauri-apps/cli/config.schema.json",
  "productName": "copy-cat",
  "version": "0.1.0",
  "identifier": "com.copy-cat.org",
  "build": {
    "frontendDist": "../dist",
    "devUrl": "http://localhost:1420",
    "beforeDevCommand": "npm run dev",
    "beforeBuildCommand": "npm run build"
  }, 
  "app": {
    "windows": [
      {
        "title": "copy-cat",
        "decorations": false,
        "transparent": true,  
        "alwaysOnTop": true, 
        "skipTaskbar": true,
        "resizable": true, 
        "fullscreen": false, 
        "visible": false,
        "maximized": false, 
        "width": 400,
        "height": 500, 
        "minWidth": 300,
        "theme":null        
      }
    ],
    "security": {
      "csp": null
    }
  },
  
  "bundle": {
    "active": true,
    "targets": "all",
    "icon": [
      "icons/copy_cat.png",
      "icons/32x32.png",
      "icons/128x128.png",
      "icons/128x128@2x.png",
      "icons/icon.icns",
      "icons/icon.ico"
    ]
  }
}

```

@FabianLars   yes it was 2 ,
