### ISSUE TITLE
On the backend, I can't listen to keyboard event

### ISSUE THREAD

**Issue by yaojiu19** [tauri-apps/tauri#6263]
### Describe the bug

i use [rdev](https://github.com/Narsil/rdev) crate to listen event to keyboard. but when the window is focus, i can't receive event.

```rust
tauri::async_runtime::spawn(async move {
      rdev::listen(move |event| {
          match event.event_type {
              EventType::KeyPress(key) => {
                  println!("KeyPress: {:?}", &key)
              }
              EventType::KeyRelease(key) => {
                  println!("KeyRelease: {:?}", &key)
              }
              _ => ()
          };
      }).unwrap();
});
```

> 

### Reproduction

window  blur or hide:
print "KeyPress" and "KeyRelease"

window focus:
don't print

### Platform and versions

Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 109.0.1518.78
  › Node.js: 16.15.1
  › npm: 8.11.0
  › pnpm: 7.5.1
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.2 (outdated, latest: 1.2.3)
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.2,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

**Comment by FabianLars** [comment]
This needs https://github.com/tauri-apps/tauri/pull/5562 which will be available in tauri 1.3 (or consumable from git directly: https://tauri.app/v1/guides/faq#how-can-i-use-unpublished-tauri-changes)
