### ISSUE TITLE
[bug] thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 216, kind: Uncategorized, message: "该版本的 %1 与你运行的 Windows 版本不兼容。请查看计算机的系统信息，然后联系软件发布者。" }', src\interface\rust\desktop.rs:47:63

### ISSUE THREAD

**Issue by KuanyaLiao** [tauri-apps/tauri#6266]
### Describe the bug

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 216, kind: Uncategorized, message: "该版本的 %1 与你运行的 Windows 版本不兼容。请查看计算机的系统信息，然后联系软件发布者。" }', src\interface\rust\desktop.rs:47:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Reproduction

pnpm tauri dev

### Platform and versions

> chatgpt-desktop@0.0.0 tauri
> tauri "info"

Environment
  › OS: Windows 10.0.19043 X64
  › Webview2: 109.0.1518.78
  › MSVC:
      - Visual Studio 15 ���ɹ��� 2017
  › Node.js: 16.12.0
  › npm: 8.1.0
  › pnpm: 7.13.6
  › yarn: 1.22.18
  › rustup: 1.25.2
  › rustc: 1.67.1
  › cargo: 1.67.1
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React (Next.js)
  › bundler: Webpack

App directory structure
  ├─ .vscode
  ├─ node_modules
  ├─ src
  └─ src-tauri

**Comment by FabianLars** [comment]
This error means that you're using a version of Visual Studio Build Tools that are too old for tauri. You need version 2019 or 2022 (with the C++ workload and Windows 10 SDK selected) <https://tauri.app/v1/guides/getting-started/prerequisites#1-microsoft-visual-studio-c-build-tools>. Version 2017 that you have installed will _not_ work.

**Comment by caigq99** [comment]
The version of Visual Studio Build Tools I am using is 2022, but I still encounter this error.
![1711416132458](https://github.com/tauri-apps/tauri/assets/80808902/0c691735-9040-4458-9bf3-7b56dc43c6e9)
![1711416226805](https://github.com/tauri-apps/tauri/assets/80808902/63a395e7-b735-4d0e-8b39-f2bc377b568f)

**Comment by FabianLars** [comment]
Do you have multiple visual studio installations?

**Comment by caigq99** [comment]
I just delete the target folder and run it again. It's done. Thank you
