### ISSUE TITLE
[bug] tauri build  failed to bundle project: error running candle.exe: error running candle.exe

### ISSUE THREAD

**Issue by zzkkui** [tauri-apps/tauri#6288]
### Describe the bug

![image](https://user-images.githubusercontent.com/24466870/219343540-4d33d0e6-de33-431b-b774-d06e06e77b20.png)

bug in fact，i found candle.exe in my local

![image](https://user-images.githubusercontent.com/24466870/219343962-5daf22fd-0ba3-4f38-9a55-7acf05c61e86.png)

### Platform and versions

![image](https://user-images.githubusercontent.com/24466870/219343040-36688d40-c373-433f-88d4-4fa73f1f285e.png)

**Comment by FabianLars** [comment]
It complains about the `Manufacturer` setting. Can you make sure that `bundle.identifier` in your tauri.conf.json file adheres to https://en.wikipedia.org/wiki/Reverse_domain_name_notation?
Alternatively you could try the `bundle.publisher` setting, which will overwrite the value in `identifier` in this context.

**Comment by zzkkui** [comment]
oh my... 
I set it just now, and then succeeded

**Comment by zzkkui** [comment]
> It complains about the `Manufacturer` setting. Can you make sure that `bundle.identifier` in your tauri.conf.json file adheres to https://en.wikipedia.org/wiki/Reverse_domain_name_notation? Alternatively you could try the `bundle.publisher` setting, which will overwrite the value in `identifier` in this context.

thank you
