### ISSUE TITLE
cargo tauri dev error

### ISSUE THREAD

**Issue by dsegovia90** [tauri-apps/tauri#6295]
Hi, I was currently trying to debug my android build, and ran into this issue. Android or not, now the rust compiler complains about the `tauri::generate_context!()` macro when I try to run `cargo tauri dev`.

```
error[E0063]: missing field `crate_name` in initializer of `PackageInfo`
  --> src/lib.rs:42:12
   |
42 |       .run(tauri::generate_context!())
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `crate_name`
   |
   = note: this error originates in the macro `tauri::generate_context` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0063`.
error: could not compile `grizzlist` due to previous error
```

--- 
versions in Cargo.lock:
name = "tauri"
version = "2.0.0-alpha.2"

name = "tauri-build"
version = "2.0.0-alpha.1"

name = "tauri-codegen"
version = "2.0.0-alpha.0"

name = "tauri-macros"
version = "2.0.0-alpha.0"

name = "tauri-runtime"
version = "0.13.0-alpha.0"

name = "tauri-runtime-wry"
version = "0.13.0-alpha.0"

name = "tauri-utils"
version = "2.0.0-alpha.1"

Thanks in advance for the help.

**Comment by amrbashir** [comment]
please post the output of `tauri info` and the contents of `tauri.conf.json`

**Comment by FabianLars** [comment]
Closing until above requested info was provided. (also try updating your tauri versions)
