### ISSUE TITLE
[feat] Switch from altool to notarytool for macOS notarisation

### ISSUE THREAD

**Issue by bencevans** [tauri-apps/tauri#6300]
### Describe the problem

Apple will discontinue support for `altool` notarization later this year.

### Describe the solution you'd like

Replace with `notarytool`.

### Additional context

Current warning when building and notarizing:

```
Warning: altool has been deprecated for notarization and starting in late 2023 will no longer be supported by the Apple notary service. You should start using notarytool to notarize your software. (-1030)
```

**Comment by FabianLars** [comment]
Duplicate of #4300. Thank you for the report.
