### ISSUE TITLE
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/interface/rust.rs:762:69

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#6304]
Did someone solve it successfully

**Comment by FabianLars** [comment]
This error _should_ mean that you don't have rust installed (the next tauri version will display a more helpful error here) - did you follow this guide? <https://tauri.app/v1/guides/getting-started/prerequisites>

**Comment by ghost** [comment]
> This error _should_ mean that you don't have rust installed (the next tauri version will display a more helpful error here) - did you follow this guide? https://tauri.app/v1/guides/getting-started/prerequisites

Thanks!
