### ISSUE TITLE
Rotating device on android causes crash

### ISSUE THREAD

**Issue by eddycurrently** [tauri-apps/tauri#6307]
Hello all,

I have been using Tauri on android and have come across a problem where it crashes when I rotate the device. I can start the app in either portrait or landscape, but if I rotate from either of those orientations, it completely crashes. I found I could reproduce this with a basic app created with tauri-mobile. If you need more info or a full example, let me know.

Regards

**Comment by amrbashir** [comment]
fixed in https://github.com/tauri-apps/tauri/commit/947eb391ca41cebdb11abd9ffaec642baffbf44a and will be available in the next 2.0-alpha release.
