### ISSUE TITLE
rls is reporting non-existent errors in tauri-generated app

### ISSUE THREAD

**Issue by onsails** [tauri-apps/tauri#631]
**Describe the bug**
After generating an app by `yarn tauri init` and opening it in VSCode or another IDE configured to run checks with rls, ide complains about compilation errors:

![2020-05-31_17-18-15](https://user-images.githubusercontent.com/107261/83354652-cd9d9300-a362-11ea-9d35-45ecf348807a.png)

At the same time this app is successfully built in both dev and production mode using `yarn tauri dev` and `yarn tauri build`.

**To Reproduce**
1. `mkdir app-test && cd app-test && yarn init && yarn add tauri && yarn tauri init`
2. Open project with VSCode
3. Open main.rs
4. View->Toggle problems

**Expected behavior**
No problems detected by IDE when the app is successfully built by the tauri cli.

**Screenshots**

**Platform and Versions (please complete the following information):**

OS: macOS
Node: 12
NPM: 6.14.4
Yarn: 1.19.1
Rustc: 1.43.1

**Additional context**

With rust-analyzer there are other errors:

![2020-05-31_17-00-56](https://user-images.githubusercontent.com/107261/83354700-050c3f80-a363-11ea-8df1-140d0b76b9e8.png)

**Comment by tensor-programming** [comment]
All of these have to do with the environment variables in the code. I've been pursing methods to get rid of them but for now they are unfortunately a part of the code.
