### ISSUE TITLE
[bug] Can't launch app on Android Emulator (Windows, Svelte, swr, pnpm)

### ISSUE THREAD

**Issue by GKosheev** [tauri-apps/tauri#6325]
### Describe the bug

I'm new to Tauri, I've been following the installation guide from [here](https://next--tauri.netlify.app/next/guides/getting-started/prerequisites/windows/) and [here](https://tauri.app/v1/guides/getting-started/setup/vite/).

I've also updated `pnpm` and `cargo` dependencies according to [this](https://tauri.app/blog/2022/12/09/tauri-mobile-alpha/).

I used `pnpm tauri android init` and then `pnpm tauri android dev` to start an app.

It launches the emulator, but it doesn't intsall/launch an actual app.

For some reason it also runs `Running BeforeDevCommand (`pnpm dev`)` and then keeps sending the following message: 

` Warn Waiting for your frontend dev server to start on .....`

Is there anything I'm doing wrong here or do you need any additional information from me to find the reason it doesn't launch the app on android emulator?

### Platform and versions

  › OS: Windows 10.0.22621 X64
  › Webview2: 110.0.1587.49
  › MSVC: 
      - Visual Studio Build Tools 2019
      - Visual Studio Community 2022
      - Visual Studio Community 2022
  › Node.js: 16.17.0
  › npm: 8.0.0
  › pnpm: 7.20.0
  › yarn: 1.22.15
  › rustup: 1.25.2
  › rustc: 1.67.1
  › cargo: 1.67.1
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.2
  › @tauri-apps/api [NPM]: 2.0.0-alpha.0
  › tauri [RUST]: 2.0.0-alpha.3,
  › tauri-build [RUST]: 2.0.0-alpha.1,
  › tao [RUST]: 0.17.0,
  › wry [RUST]: 0.26.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Svelte
  › bundler: Vite

App directory structure
  ├─ .idea
  ├─ .vscode
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri

**Comment by amrbashir** [comment]
You need to enable your dev-server to listen for requests on local network IPs, in your case, vite, so take a look at this https://next--tauri.netlify.app/next/mobile/development/configuration#vite

**Comment by GKosheev** [comment]
@amrbashir, I did that.

The following is my vite.config.ts file:

```typescript
import { defineConfig } from "vite";
import { svelte } from "@sveltejs/vite-plugin-svelte";
import sveltePreprocess from "svelte-preprocess";
import { internalIpV4 } from "internal-ip";

// https://vitejs.dev/config/
export default defineConfig(async () => {
  const host = await internalIpV4();

  /** @type {import('vite').UserConfig} */
  const config = {
    plugins: [
      svelte({
        preprocess: [
          sveltePreprocess({
            typescript: true,
          }),
        ],
      }),
    ],

    // Vite options tailored for Tauri development and only applied in `tauri dev` or `tauri build`
    // prevent vite from obscuring rust errors
    // clearScreen: false,
    // tauri expects a fixed port, fail if that port is not available
    server: {
      host: "0.0.0.0",
      port: 5173,
      strictPort: true,
      hmr: {
        protocol: "ws",
        host,
        port: 5183,
      },
    },
    // to make use of `TAURI_DEBUG` and other env variables
    // https://tauri.studio/v1/api/config#buildconfig.beforedevcommand
    envPrefix: ["VITE_", "TAURI_"],
    // build: {
    //   // Tauri supports es2021
    //   target:
    //     process.env.TAURI_PLATFORM == "windows" ? "chrome105" : "safari13",
    //   // don't minify for debug builds
    //   // minify: !process.env.TAURI_DEBUG ? "esbuild" : false,
    //   // produce sourcemaps for debug builds
    //   sourcemap: !!process.env.TAURI_DEBUG,
    // },
  };
  return config;
});


````

**Comment by amrbashir** [comment]
what about your tauri.conf.json ?

**Comment by amrbashir** [comment]
ah I see you posted `tauri info`, the port in the `devPath` in `tauri.conf.json` is incorrect, it should be `http://localhost:5173`

**Comment by GKosheev** [comment]
@amrbashir, I changed tauri info and then I have the following error, though I installed everything according to [this](https://next--tauri.netlify.app/next/guides/getting-started/prerequisites/windows/)

![image](https://user-images.githubusercontent.com/78924110/220201983-7d6d804f-8125-4c92-aed4-5f925ee4473e.png)

**Comment by amrbashir** [comment]
Make sure to install the android development prerequisites https://next--tauri.netlify.app/next/guides/getting-started/prerequisites/windows#android

**Comment by GKosheev** [comment]
@amrbashir, I've been debugging this app for hours already and was able to at least make this app to be installed on my Android emulator, but it keeps crashing with the following output: 
![image](https://user-images.githubusercontent.com/78924110/220532439-027db956-edde-4b43-9264-712a6a37b187.png)
