### ISSUE TITLE
[bug] `"@tauri-apps/api/http"` issue in MacOS 11

### ISSUE THREAD

**Issue by neil-morrison44** [tauri-apps/tauri#6326]
### Describe the bug

Hi,

A few of my users using MacOS 11 have reported an issue https://github.com/neil-morrison44/pocket-sync/issues/74

I've narrowed it down to being my only usage of `@tauri-apps/api/http` which I added recently here: https://github.com/neil-morrison44/pocket-sync/blob/adf8f46d3e5990b971ab01464b3a06ac34f86038/src/recoil/platforms/selectors.ts#L98 but as I don't have a MacOS 11 instance I can't narrow it down further (sorry)

The google results for the error - `"options.signal must be AbortSignal"` used to just return results showing where that text went into webkit but now they just show that issue.

I'm not doing anything with `AbortSignal` / `signal` in my code - & neither is tuari, at least in this repo... so I suspect it to be an issue with whichever edition of WebKit is in MacOS 11.

### Reproduction

- Use "@tauri-apps/api/http" on MacOS 11 in a way similar to the above code snippet
- Get an error

### Expected behavior

- Don't get an error, like it does on MacOS 12+

### Platform and versions

(mine, not those seeing the error)

Environment
  › OS: Mac OS 13.1.0 X64
  › Node.js: 16.13.0
  › npm: 8.1.0
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.3,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React
  › bundler: Vite

App directory structure
  ├─ readme_images
  ├─ dist
  ├─ target
  ├─ node_modules
  ├─ public
  ├─ .github
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  └─ src

### Stack trace

```shell
options.signal must be AbortSignal
pipeThrough@[native code]
gS@tauri://localhost/assets/index-5fe25fcd.js:3200:1104170
tauri://localhost/assets/index-5fe25fcd.js:3200:1107547
asyncFunctionResume@[native code]
tauri://localhost/assets/index-5fe25fcd.js:3201:1161278
asyncFunctionResume@[native code]
[native code]
promiseReactionJobWithoutPromise@[native code]
```

### Additional context

Since it's probably an (incredibly rare) webkit issue feel free to close this as a known issue if you don't feel like doing a workaround (if that's even possible).

If you want to see it error in the app let me know and I'll send over a small zip with a folder in it that looks enough like the file system expected to run the app

**Comment by FabianLars** [comment]
I honestly don't think this is in any way related to `@tauri-apps/api/http`. All the api does is to call the rust side and return the json response as-is. Maybe something else in your frontend is incompatible with Safari 14 (this is the wkwebview version macos 11 uses)?

**Comment by neil-morrison44** [comment]
Hmm, yeah can’t see how that’d cause it either.

My thought was that `abortSignal` _usually_ gets used with network requests, but it’s entirely possible that something else is using it for a different purpose.

Everywhere else I’ve been able to call using fetch but this was the one place with CORS issues.

I’ll close this and dig in a bit further, there’s some unzipping that also only happens there that could be the culprit…
