### ISSUE TITLE
[docs] Change webkit2gtk package for Arch Installations

### ISSUE THREAD

**Issue by kjell0w** [tauri-apps/tauri#6331]
Hello,

while trying out the v2 Alpha release i ran into the problem regarding Arch Linux System Dependencies. The guide says that for Arch Linux the package `webkit2gtk` must be installed, but it also has to be the package `webkit2gtk-4.1`. Without `webkit2gtk-4.1` installed you get the following error with the build/dev command: `'error: could not find system library 'webkit2gtk-4.1' required by the 'webkit2gtk-sys' crate`

**Comment by FabianLars** [comment]
Duplicate of https://github.com/tauri-apps/tauri-docs/issues/1097. Thanks for the report.
