### ISSUE TITLE
it doesn't work! while I set "background": true on win11

### ISSUE THREAD

**Issue by Perfumere** [tauri-apps/tauri#6335]
### Describe the bug

When I set transparent to true in tauri.conf.json, it does not take effect on the platform.

os： Windows 11 professional edition
os_version： 22H2  （22621.1265）
node: v16.18.1
npm: 8.19.2
rustc: 1.67.1 (d5a82bbd2 2023-02-07)
cargo: 1.67.1 (8ecd4f20a 2023-01-10)

I have done the following：

```
// index.html
html, body {
    background-color: transparent !important;
}
```

```
// tauri.conf.json
{
  "build": {
    "beforeDevCommand": "npm run dev",
    "beforeBuildCommand": "npm run build",
    "devPath": "http://localhost:1420",
    "distDir": "../dist",
    "withGlobalTauri": true
  },
  "package": {
    "productName": "t1",
    "version": "0.0.0"
  },
  "tauri": {
    "allowlist": {
      "all": false,
      "shell": {
        "all": false,
        "open": true
      }
    },
    "bundle": {
      "active": true,
      "category": "DeveloperTool",
      "copyright": "",
      "deb": {
        "depends": []
      },
      "externalBin": [],
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "identifier": "com.tauri.dev",
      "longDescription": "",
      "macOS": {
        "entitlements": null,
        "exceptionDomain": "",
        "frameworks": [],
        "providerShortName": null,
        "signingIdentity": null
      },
      "resources": [],
      "shortDescription": "",
      "targets": "all",
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "security": {
      "csp": null
    },
    "updater": {
      "active": false
    },
    "windows": [
      {
        "fullscreen": false,
        "height": 600,
        "resizable": true,
        "title": "t1",
        "width": 800,
        "transparent": true
      }
    ]
  }
}
```

### Expected behavior

Window transparency

### Platform and versions

Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 110.0.1587.50
  › MSVC: 
      - Visual Studio ���ɹ��� 2022
  › Node.js: 16.18.1
  › npm: 8.19.2
  › pnpm: 7.27.1
  › yarn: Not installed!
  › rustup: 1.25.2
  › rustc: 1.67.1
  › cargo: 1.67.1
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › bundler: Vite

App directory structure
  ├─ .vscode
  ├─ dist
  ├─ node_modules
  ├─ src
  └─ src-tauri

**Comment by Perfumere** [comment]
while i set prop "decorations" to false, it works!

**Comment by TianbinTobin** [comment]
![image](https://user-images.githubusercontent.com/16282973/220569956-9b50ffc7-9732-4226-963f-f1685b465082.png)
while i resize the window: 
![image](https://user-images.githubusercontent.com/16282973/220571102-b7937c01-534b-4148-8209-956fb3a66359.png)

**Comment by FabianLars** [comment]
See https://github.com/tauri-apps/tauri/issues/8632 - this is a windows limitation we don't know how to work around in a nice way.
