### ISSUE TITLE
Panic on window builder build. 

### ISSUE THREAD

**Issue by rdwnsjjd** [tauri-apps/tauri#6344]
I got this error while I'm creating new window in `setup` function of tauri app builder:

```
thread panicked at 'container::get(): get() called before set() for given type' 
```

I'm in Linux.

**Comment by FabianLars** [comment]
Can you show some of your code and the output of `tauri info` please? And preferably the _whole_ error message too.

**Comment by rdwnsjjd** [comment]
I'm sorry I cannot show the code, but I can describe what I try.
I'm coding in cpp and whole of my code is in cpp. but I use tauri for gui and so, I'm trying to make some libraries in rust that provides what I need to make a tauri app in cpp. 
one of the libraries (provides making tauri app) has a primary api named 'run'. this function builds and runs tauri app and will be called from main function of cpp app.
in another rust library, I expose some api's will be used to create window.
this two libraries are separated, but both of them will be linked to cpp program. so window maker library cannot access tauri app handle normally.
I made an static variable in cpp named `TAURI_GLOBA_APP_HANDLE`. this variable in cpp header is accessible from both rust libraries (by calling back and set). 
when tauri app is building, in `setup` method of builder I set that variable in cpp to points to the app handle. so when global handle set, I can use it in window builder for building window.

all things are write. pointers are true. variables will be set truly. but when I trying to build window in another linked library, I will got this error.
all operations will be run as single process.

I will share whole error message and tauri info

**Comment by rdwnsjjd** [comment]
```
Environment
  › OS: Ubuntu 20.04 X64
  › Node.js: 16.17.0
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.66.0-nightly
  › cargo: 1.66.0-nightly
  › Rust toolchain: nightly-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: Not installed!

App
  › framework: React
```

Error:
```
thread '<unnamed>' panicked at 'container::get(): get() called before set() for given type', /home/imd/.cargo/registry/src/github.com-1ecc6299db9ec823/state-0.5.3/src/container.rs:603:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by probablykasper** [comment]
What is `state-0.5.3/src/container.rs`, is that something from Tauri? Could it be that you're accessing Tauri state before setting it? Running with `RUST_BACKTRACE=1` might be helpful to see where this comes from.

If it's not something simple like that, then I think the info you provided unfortunately won't be enough to really be able to debug this. The best option might be to create a minimal reproduction in pure-Rust

**Comment by rdwnsjjd** [comment]
Yes `state-0.5.3/src/container.rs` is used by tauri. I traced by my self and it is used when creating new window. but I don't understand what is usage of it in tauri.

**Comment by amrbashir** [comment]
please make a minimal repro or clear steps to reproduce with snippets if possible and I will reopen the issue, we can't help you without that information.
