### ISSUE TITLE
[feat] Screen Shots

### ISSUE THREAD

**Issue by weifashi** [tauri-apps/tauri#6346]
### Describe the problem

1，How to take Screen Shots，Can you provide apis
2，How to take color，Can you provide apis

### Describe the solution you'd like

1，How to take Screen Shots，Can you provide apis
2，How to take color，Can you provide apis

**Comment by amrbashir** [comment]
Please follow the feature request template and provide the needed info so we can understand the feature request better or how the API usage might look like, or provide a similar API in other frameworks.
