### ISSUE TITLE
[feat] Add support for tvOS

### ISSUE THREAD

**Issue by kellytk** [tauri-apps/tauri#6364]
### Describe the problem

Cannot deploy to Apple TV devices.

### Describe the solution you'd like

Support [tvOS](https://developer.apple.com/tvos/).

**Comment by FabianLars** [comment]
tvOS does not support WKWebView so this is out of scope for now, thanks for the feature request though!
Maybe once the servo-based webview is actually a thing this could be revisited but tbh i don't expect this to work either :/

**Comment by owiofwm2i** [comment]
> tvOS does not support WKWebView so this is out of scope for now, thanks for the feature request though! Maybe once the servo-based webview is actually a thing this could be revisited but tbh i don't expect this to work either :/
I saw now tauri can use tauri-runtime-verso, is it possible to run on tvOS?

**Comment by owiofwm2i** [comment]
> tvOS does not support WKWebView so this is out of scope for now, thanks for the feature request though! Maybe once the servo-based webview is actually a thing this could be revisited but tbh i don't expect this to work either :/

I saw now tauri can use tauri-runtime-verso, is it possible to run on tvOS?

**Comment by FabianLars** [comment]
afaik servo can't be compiled for tvOS and i wouldn't be surprised if using some webengine in your app would make it fail the app store submission (otherwise apple would like just enable webkit).

To not lead anyone on: Don't expect tvOS support in Tauri. If you need to build an app for tvOS, look elsewhere :)
