### ISSUE TITLE
[docs] How to get window from lable?

### ISSUE THREAD

**Issue by zkcrescent** [tauri-apps/tauri#6366]
Is there some method can get window by label in rust ,just like `tauri::Window::get_by_label("label_name")`. I cant find such method in docs.

Thanks for your help.

**Comment by FabianLars** [comment]
There's a `get_window` method on the Manager trait: https://docs.rs/tauri/latest/tauri/trait.Manager.html#method.get_window.
The Manager trait is implemented by `App`, `AppHandle` and `Window` so you need one of these to use the function. For example if you're in a tauri command you can inject them like this https://tauri.app/v1/guides/features/command#accessing-an-apphandle-in-commands

**Comment by zkcrescent** [comment]
thanks! It's helpful for me!
