### ISSUE TITLE
[feat] listen_once

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri#6378]
### Describe the problem

Currently there is no way to listen to an event only once. This forces a whole bunch of annoying workarounds on users and makes code unnecessarily complex. On the Rust side for example, one cannot use `move` and is forced to use copy, clone or RC types. This for example makes the use of `oneshot` channels impossible.

### Describe the solution you'd like

Implement an `listen_once` (Rust) and `listenOnce`(JavaScript) functions everywhere that has `listen` methods. 

The Rust signature would be `listen_once(event: &str, handler: impl FnOnce(Event))` where  the specific type of `Event` depends on the context of where the method is used.

The JavaScript signature would be `listenOnce(event: string, handler: (event) => void)`.

**Comment by FabianLars** [comment]
so ehhh, like `once`? 😅 
https://docs.rs/tauri/latest/tauri/window/struct.Window.html#method.once
https://tauri.app/v1/api/js/event/#once
Or am i missing something here?

**Comment by JonasKruckenberg** [comment]
wait...

**Comment by JonasKruckenberg** [comment]
mhm yes. exactly like `once` 🤦🏻
