### ISSUE TITLE
WebGPU support?

### ISSUE THREAD

**Issue by DolphinIQ** [tauri-apps/tauri#6381]
### Describe the problem

Hello, I love this project!

WebGPU is a new graphics API for complex rendering and compute, using hardware acceleration. Use cases include demanding 3D games and acceleration of scientific calculations. It is meant to supersede WebGL and allows developers to create more advanced applications thanks to new optimizations and features (for example Compute Shaders, which are not available in WebGL2).

Does Tauri allow enabling WebGPU support? According to https://github.com/MicrosoftEdge/WebView2Feedback/issues/2233 WebView2 WebGPU support on Windows is up to date, but I was unable to find any information about how to enable it on a Tauri window/project.

I come from WebGL browser world and WebGPU is currently only accessible through flags. Theoretically I shouldn't have to worry about experimental features, since my app will be running my safe code only. I would love to be able to build next gen desktop graphics applications with Tauri & WebGPU.

### Describe the solution you'd like

I would like to be able to enable experimental features, such as WebGPU. One option would be to allow the user to pass in flags like "enable-unsafe-webgpu".

**Comment by FabianLars** [comment]
The webgpu flag is only available in the non-stable webview2 channels which we currently have no plans to support (the webview bindings crate doesn't support them either fwiw).
Once it is also available in the stable channel you could use the api introduced here <https://github.com/tauri-apps/tauri/pull/5799> (will be part of 1.3) to set the flag.

Note that this would still be Windows-only. The Linux and macOS webviews have no setting to enable flags like these.

**Comment by FabianLars** [comment]
stop, wait! i was wrong, gimme a second 🤣 

Edit: Yeah sorry, if you inject `--enable-unsafe-webgpu` via the above mentioned `additionalBrowserArgs` config it works in the stable channel too:
![grafik](https://user-images.githubusercontent.com/30730186/222217396-ed148916-af32-4915-aac7-20ba3b97ed3c.png)


Still, this is windows only!

**Comment by DolphinIQ** [comment]
Thank you @FabianLars for a great quick answer! That is awesome. Do we know when is Tauri 1.3 coming?

**Comment by FabianLars** [comment]
relatively soon-ish. It's currently in an internal audit, no idea how far that progressed already. My guess would be sometime this month (prob soon after Lucas returns from his vacation 😅 )

**Comment by nothingismagick** [comment]
Would be really great to document this addition.

**Comment by AathifMahir** [comment]
Awesome work!

Will be looking to contribute **Tauri** on Windows Side Pretty soon, Haven't had a chance to look through the source code will look into it in my spare time and let's see how we can improve Tauri on Windows.

**Comment by nischalj10** [comment]
any plans yet of mac/ linux support?

**Comment by FabianLars** [comment]
We have no control over that (as long as we're "stuck" with the OS webviews). Safari added it to their TP version in December so i would expect that it's not that far off. No idea about Linux though.

**Comment by xpluscal** [comment]
Heyhey, any updates on this topic?

**Comment by brandon-xyzw** [comment]
WebGPU works now behind a flag. I haven't used Tauri yet, but would it be safe to assume it's good to use here?

**Comment by FabianLars** [comment]
If you're also talking about macOS, then no. You can't enable feature flags in WKWebView to our knowledge.

**Comment by brandon-xyzw** [comment]
I was able to compile Webkit using [these instructions](https://gist.github.com/slimbuck/ec4500afaec6b2c5368c22a37153826d), and enable WebGPU. It doesn't make sense to me how this isn't possible (not saying it is, I just don't understand).

Regardless, thanks for your quick response

**Comment by FabianLars** [comment]
We're not shipping webkit with the app but isntead rely on the existing system version. So if you tell your users to all do that, or i guess better yet, ship it with your app (obviously increasing the app size by quite a lot) then it's possible of course, it's just not something we support directly.

**Comment by eckertliam** [comment]
So this will not be supported directly by Tauri ever? We just have to wait on vendors?

**Comment by FabianLars** [comment]
> So this will not be supported directly by Tauri ever?

If we're only talking about wkwebview/webkitgtk then that's correct.

**Comment by gavan-x** [comment]
@FabianLars thanks for clarifying for WebGPU across OS we’re better of with electron?

**Comment by FabianLars** [comment]
yes

**Comment by jorgedanisc** [comment]
Hey! I see that WebGPU isn’t planned to be supported on Tauri for macOS — is that still the case with the upcoming [Safari 26](https://developer.apple.com/documentation/safari-release-notes/safari-26-release-notes) (WebKit) update?

**Comment by FabianLars** [comment]
If apple enables webgpu in WKWebView and not just Safari (which is what I expect) it should be available in Tauri automatically, worst case we need to add a one-liner in Wry to enable it if it's opt-in (I assume it'll be opt-out).

Note that in Tauri land this means that only users on macOS 26 and above will have webgpu support on their devices. WKWebView updates are bound to OS updates unlike Safari updates (though I wouldn't be surprised if it's the same in safari for webgpu this time)

**Comment by Michael-Barletta** [comment]
Is there any update to this? Has webgpu been enabled in WKWebview. I still can't seem to enable webGPU on my macOS app. When apple does decide to enable it by default, will I need to update anything or will it just work out of the box?

**Comment by FabianLars** [comment]
It should work out of the box on macos/ios 26+ - just tested https://webkit.org/demos/webgpu/ and it seems to work on my end.

**Comment by Michael-Barletta** [comment]
You're right it does work on a production build. When I was testing with a development build Webgpu would not initialize.
