### ISSUE TITLE
Needs A Command Line Argument ala 'cargo tauri build -fips'

### ISSUE THREAD

**Issue by Daniel-A-Gutierrez** [tauri-apps/tauri#6383]
Hello,

In order to bundle applications to run on machines compliant with the federal information processing standards , wix needs a command line argument '-fips' to be passed to it by tauri.

error

candle.exe : error CNDL0308 : The Federal Information Processing Standard (FIPS) appears to be enabled on this machine. You must either disable FIPS or use FIPS-compliant security algorithms to generate IDs by passing the -fips command line switch or by setting <FipsComliant>true<FipsCompliant> in your .wixproj project.

**Comment by FabianLars** [comment]
Starting with tauri's cli version 1.1 you can set an env var for this:
```
TAURI_FIPS_COMPLIANT="true"
```

I'll add it to <https://tauri.app/v1/guides/building/windows> today, sorry for that.

**Comment by Daniel-A-Gutierrez** [comment]
No problem, thanks for the quick turn response.

**Comment by romach1** [comment]
Asking for help with the same issue. I am attempting to build a Tauri app on a FIPS compliant windows machine. I have the environment variable set: `TAURI_FIPS_COMPLIANT="true"` but I am still getting the same error mentioned above: `candle.exe : error CNDL0308 : The Federal Information Processing Standard (FIPS) appears to be enabled on this machine...`

I ran tauri build with the verbose flag,

`Running [tauri_bundler::bundle::windows::msi::wix] candle for "main.wxs"
     Running [tauri_bundler::bundle::common] Command `C:\Users\j3\AppData\Local\tauri/WixTools\candle.exe  -arch x64 main.wxs -dSourceDir=C:\Users\j3\Documents\Gamma\gamma20240814\gamma\src-tauri\target\release\Gamma.exe`
candle.exe : error CNDL0308 : The Federal Information Processing Standard (FIPS) appears to be enabled on the machine. You must either disable FIPS or use FIPS-compliant security algorithms to generate IDs by passing the -fips command-line switch or by setting <FipsCompliant>true</FipsCompliant> in your .wixproj project.
       Error [tauri_cli_node] failed to bundle project: error running candle.exe`

Looking at the line that shows the candle.exe command options, I don't see a `-fips` command line switch.  So it seems like the tauri build api isn't activating that switch for some reason. When I run `$Env:TAURI_FIPS_COMPLIANT` (in PowerShell) it outputs `true` 

Any thoughts?

Here a copy of the settings in tauri.conf.json:

{
  "$schema": "../node_modules/@tauri-apps/cli/schema.json",
  "build": {
    "beforeBuildCommand": "pnpm run build",
    "beforeDevCommand": "pnpm run dev",
    "devPath": "http://localhost:5173",
    "distDir": "../build"
  },
  "package": {
    "productName": "Gamma",
    "version": "0.1.0"
  },
  "tauri": {
    "allowlist": {
      "all": false,
      "dialog": {
        "all": false,
        "ask": false,
        "confirm": false,
        "message": false,
        "open": true,
        "save": true
      }
    },
    "bundle": {
      "active": true,
      "category": "DeveloperTool",
      "copyright": "",
      "deb": {
        "depends": []
      },
      "externalBin": [],
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "identifier": "com.gamma.dev",
      "longDescription": "",
      "macOS": {
        "entitlements": null,
        "exceptionDomain": "",
        "frameworks": [],
        "providerShortName": null,
        "signingIdentity": null
      },
      "resources": [],
      "shortDescription": "",
      "targets": "all",
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": "",
        "webviewInstallMode": {
          "silent": false,
          "type": "offlineInstaller"
        }
      }
    },
    "security": {
      "csp": null
    },
    "updater": {
      "active": false
    },
    "windows": [
      {
        "fullscreen": false,
        "height": 600,
        "resizable": true,
        "title": "Gamma",
        "width": 800
      }
    ]
  }
}
