### ISSUE TITLE
[feat] make tauri icon support SVGs

### ISSUE THREAD

**Issue by ImUrX** [tauri-apps/tauri#6389]
### Describe the problem

the ``tauri icon`` cli currently uses rasterized images and downscales them.

### Describe the solution you'd like

Using an SVG would be nice, it can be converted to any resolution!

**Comment by fetzsav** [comment]
I've implemented SVG support for the icon tool in the CLI, here is the PR https://github.com/tauri-apps/tauri/pull/6444

**Comment by Cioraz** [comment]
Hey, I would like to work on this issue.
Correct me if I'm wrong, so basically I've got to change the tauri icon in the cli?
