### ISSUE TITLE
[feat] Create select menu allow custom layout outside window

### ISSUE THREAD

**Issue by letrungdo** [tauri-apps/tauri#6392]
### Describe the problem

<img width="161" alt="Screen Shot 2023-03-03 at 17 28 27" src="https://user-images.githubusercontent.com/16357748/222697189-bb1e6a1b-cd6b-4ecc-88f4-1413252794a6.png">
Obscured menu cannot be displayed out of the window

### Describe the solution you'd like

<img width="567" alt="Screen_Shot_2023-03-02_at_23 17 52" src="https://user-images.githubusercontent.com/16357748/222695801-04bcdf45-ed26-4bbc-a142-38214ed21940.png">
I want the menu when clicked to protrude out of the window as shown

### Alternatives considered

The select element work ok but can't style or change icon
https://www.w3schools.com/tags/att_option_selected.asp

**Comment by amrbashir** [comment]
Custom HTML Select elements can't be displayed outside the window, use `<Select>` element for that. There is no way around it.

If you still want to use a custom select menu, then you should reposition the dropdown above the select button if it doesn't have enough space below it.
