### ISSUE TITLE
[bug] Segmentaion fault in `src-tauri` when `cargo tauri dev` is run

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#6402]
### Describe the bug

When running `cargo tauri dev`, the frontend starts and the backend is compiled, but then the program exits with code 0. Running with cargo as package manager, and vanilla frontend ends up with this output:
```
$ cargo tauri dev
        Info Watching /home/user/tauri-app/src-tauri for changes...
   Compiling tauri-app v0.0.0 (/home/user/tauri-app/src-tauri)
    Finished dev [unoptimized + debuginfo] target(s) in 5.75s
```
However, when running `cargo run` in the `src-tauri` dir...
```
$ cargo run
   Compiling tauri-app v0.0.0 (/home/user/tauri-app/src-tauri)
    Finished dev [unoptimized + debuginfo] target(s) in 6.02s
     Running `target/debug/tauri-app`
Segmentation fault (core dumped)
```

### Reproduction

1. Install `create-tauri-app` (`cargo install create-tauri-app`)
2. Create a tauri app with `cargo create-tauri-app` with `Rust` as the frontend language and `Vanilla` as the ui template
3. `cd` into the project
4. Run `cargo tauri dev`
5. See issue

### Expected behavior

The program to start with a window showing the ui

### Platform and versions

Environment
  › OS: Linux 3.18_alpha20230208 X64
  › Node.js: 18.14.2
  › npm: 9.5.1
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.2
  › rustc: 1.67.1
  › cargo: 1.67.1
  › Rust toolchain: stable-x86_64-unknown-linux-musl

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../src
  › devPath: ../src
package.json not found

App directory structure
  ├─ src-tauri
  ├─ .vscode
  └─ src

**Comment by FabianLars** [comment]
Can you tell us a bit more about your Linux system? The info command wasn't able to handle it apparently.
Like, which distro / version. Your kernel version. The version of webkitgtk.

Also, did you try the `*-gnu` toolchain instead of musl?

**Comment by ghost** [comment]
Distro: Alpine Linux edge
Kernel: 6.1.15-0-lts
webkit2gtk: 2.38.5

> Also, did you try the *-gnu toolchain instead of musl?

I do not have a system running gnu linux at hand. If you want I can setup a vm and see how it goes.

**Comment by FabianLars** [comment]
> I do not have a system running gnu linux at hand. If you want I can setup a vm and see how it goes.

Well, we don't need that to see if it works, but if you want to work with tauri it's what you'd have to do for now. I don't think anyone looked into building a tauri app on alpine linux before.

**Comment by ghost** [comment]
After some more testing, this seems to happen no matter what frontend you use. However, this issue only seems to occur if rust is installed via `rustup`. When rust is installed via `apk` (alpine package keeper) there is no such issue and the application is ran as normal.

While this does mitigate the issue, installing rust via `apk` causes issues with libraries such as rustssl as it doesn't recognize `x86_64-alpine-linux-musl`, and also means that rustup cannot be used.

**Comment by naman-crabnebula** [comment]
Hi!

Is there any updates on this issue, since I can not reproduce this bug with the latest Rust and Tauri versions.

**Comment by FabianLars** [comment]
Ah i never saw the last response i think. If this is not an issue if rust is installed via apk then this is not an issue we can work on in Tauri anyway.
