### ISSUE TITLE
[bug] use tauri android dev on  android studio emulator fail

### ISSUE THREAD

**Issue by 799189288** [tauri-apps/tauri#6404]
### Describe the bug

03/06 22:17:47: Launching 'app' on Pixel XL API 33.
The currently selected variant "armDebug" uses split APKs, but none of the 1 split apks are compatible with the current device with ABIs "x86_64".

The packaged Android installation package also displays the installation package resolution failure on the mobile phone.

After several days retry. i give up.

Has anyone ever encountered this situation

### Platform and versions

```text
npm 9.2.0,
node 18.12.1
...
```

**Comment by FabianLars** [comment]
Please fill out the `Platform and versions` section with the _full_ `tauri info` output as required. I will reopen the issue afterwards, thank you.
