### ISSUE TITLE
[bug] Various Troubles Cross-Compiling to Android

### ISSUE THREAD

**Issue by xxgunnery** [tauri-apps/tauri#6405]
### Describe the bug

I have a project I have been successfully compiling on Windows for a desktop application, but when trying to compile to Android it fails. I have followed all steps on the alpha docs several times. It seems that my issues are related to the NDK and how they work compiling with:

1. Reqwest and its cc dependency. I MAY have fixed this by using rustls as instructed by @FabianLars.
2. Diesel with the Postgres feature. It fails when trying to access libpq.

### Reproduction

1. Download the Tauri project on my GitHub
2. Follow all steps for Android app on the alpha docs
3. Run `cargo tauri android init`, and `cargo tauri android dev`

At my current state, the build fails with `note: ld: error: unable to find library -llibpq`

Please note my comments in the additional context section about troubles overriding the .cargo/config.toml file.

### Expected behavior

Since my application builds on Windows and I have followed the steps to compile on Android, it should work.

### Platform and versions

Using Windows...

```text
[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.59"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-alpha.0", features = [] }
cc = { version = "1.0.79", features = ["parallel"] }

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.0.0-alpha.0", features = [] }
chrono = "0.4.23"
sha2 = "0.9.3"
base64-url = "1.4.13"
dotenv = "0.15.0"
hyper = "0.14.13"
reqwest = { version = "0.11.14", default-features = false, features = [
    "rustls-tls",
] }
diesel = { version = "2.0.0", features = [
    "postgres",
    "chrono",
    "uuid",
    "r2d2",
] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
```

### Stack trace

```text
Compiling app v0.1.0 (C:\Users\xxgun\Documents\pdantonio\Rust\tauri\fitbit\src-tauri)
error: linking with `C:/AndroidSDK/ndk/25.0.8775105\toolchains/llvm/prebuilt/windows-x86_64\bin\aarch64-linux-android24-clang.cmd` failed: exit code: 1
  |app:rustBuildArm64Debug
  = note: "C:/AndroidSDK/ndk/25.0.8775105\\toolchains/llvm/prebuilt/windows-x86_64\\bin\\aarch64-linux-android24-clang.cmd"

........ *150 lines worth of other addresses ........

"C:\\Users\\xxgun\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libcompiler_builtins-60bcd280e935af09.rlib" "-Wl,-Bdynamic" "-llibpq" "-landroid" "-ldl" "-llog" "-lgcc" "-ldl" "-lm" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "C:\\Users\\xxgun\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib" "-o" "C:\\Users\\xxgun\\Documents\\pdantonio\\Rust\\tauri\\fitbit\\src-tauri\\target\\aarch64-linux-android\\debug\\deps\\libapp.so" "-Wl,--gc-sections" "-shared" "-Wl,-zrelro,-znow" "-nodefaultlibs" "-landroid" "-llog" "-lOpenSLES"
  = note: ld: error: unable to find library -llibpq
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: could not compile `app` due to previous error
       Error `Failed to run `cargo build`: Command "cargo build --package app --manifest-path C:\\Users\\xxgun\\Documents\\pdantonio\\Rust\\tauri\\fitbit\\src-tauri\\Cargo.toml --target aarch64-linux-android --no-default-features --color always" didn't complete successfully, exiting with code 101.
```

### Additional context

When I run the command `cargo build --package app --manifest-path C:\\Users\\xxgun\\Documents\\pdantonio\\Rust\\tauri\\fitbit\\src-tauri\\Cargo.toml --target aarch64-linux-android --no-default-features --color always`

I get:
 Compiling sha2 v0.9.9
   Compiling diesel v2.0.3
   Compiling app v0.1.0 (C:\Users\xxgun\Documents\pdantonio\Rust\tauri\fitbit\src-tauri)
   Compiling base64-url v1.4.13
   Compiling dotenv v0.15.0
error: linker `cc` not found
  |
  = note: program not found
  
**Also**, I attempted to modify my config.toml file at src-tauri/.cargo/config.toml and noticed that my changes are overwritten when attempting to build again via `cargo tauri android dev`. I was attempting to add lines under one of the targets. I was following a guide here to see if I could fix my problems:  [https://github.com/diesel-rs/diesel/issues/587](https://github.com/diesel-rs/diesel/issues/587)

[target.armv7-linux-androideabi]
linker = 'C:/AndroidSDK/ndk/25.0.8775105\toolchains/llvm/prebuilt/windows-x86_64\bin\armv7a-linux-androideabi24-clang.cmd'
**rustc-link-search = ["C:\Program Files\PostgreSQL\15\lib"]** (added line)
**rustc-link-lib = ["libpq"]** (added line)
rustflags = [
    '-L',
    'C:\Users\xxgun\Documents\pdantonio\Rust\tauri\fitbit\src-tauri/.cargo',
    '-Clink-arg=-landroid',
    '-Clink-arg=-llog',
    '-Clink-arg=-lOpenSLES',
]

I also tried to add a config.coml at my directory C://users/myusername/.cargo/config.toml. I added the whole text as shown above and it did not merge with the config.toml in the src-tauri/.cargo directory.

**Comment by amrbashir** [comment]
Could you give this another try with latest version of NDK and Tauri? It should be solved. Let me know if the issue persists.

**Comment by bpevs** [comment]
Sorry to revive @amrbashir, but I'm having basically this same issue with sqlite, and this is the closest thing I could find to a similar issue.  Besides sqlite vs pg and mac vs windows, this basically matches the issue I'm having.  Was wondering if there was anything specific done to make this llibpq work?

`ld.lld: error: unable to find library -lsqlite3`
NDK: 26.1.10909125
tauri: 2.0.0-alpha.21

**Comment by bpevs** [comment]
Oops!  Seems like this was an unrelated issue.  Sorry about that!  There was a solution already in the discord that I missed:
https://discord.com/channels/616186924390023171/1193577317491036312/1193840512822673498

basically just adding to cargo.toml deps: 
`libsqlite3-sys = { version = ">=0.17.2, <0.28.0", features = ["bundled"] }`
