### ISSUE TITLE
[bug] Android cargo.toml [package.metadata.cargo-android] not load.

### ISSUE THREAD

**Issue by rainbowflesh** [tauri-apps/tauri#6407]
### Describe the bug

The wry template init with android permission config, and I saw [tauri-mobile](https://github.com/tauri-apps/tauri-mobile)/[src](https://github.com/tauri-apps/tauri-mobile/tree/dev/src)/[android](https://github.com/tauri-apps/tauri-mobile/tree/dev/src/android)/config.rs parse the [package.metadata.cargo-android], but [tauri](https://github.com/tauri-apps/tauri/tree/46e6187c89594692b0e245a2ad5ec50de819296b)/[core](https://github.com/tauri-apps/tauri/tree/46e6187c89594692b0e245a2ad5ec50de819296b/core)/[tauri-utils](https://github.com/tauri-apps/tauri/tree/46e6187c89594692b0e245a2ad5ec50de819296b/core/tauri-utils)/[src](https://github.com/tauri-apps/tauri/tree/46e6187c89594692b0e245a2ad5ec50de819296b/core/tauri-utils/src)/config.rs not load cargo.toml after `default()`.

How do I declare the available permissions in the configuration file, directly modifying `AndroidManifest.xml` is not elegant enough.

### Reproduction

1. write or init cargo.toml.
```toml
[package.metadata.cargo-android]
app-activity-name = ".MainActivity"
app-dependencies = [
    "androidx.webkit:webkit:1.4.0",
    "androidx.appcompat:appcompat:1.5.0",
    "com.google.android.material:material:1.6.1",
]
project-dependencies = ["org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"]
app-plugins = ["org.jetbrains.kotlin.android"]
app-permissions = [
    "android.permission.INTERNET",
    "android.permission.ACCESS_FINE_LOCATION",
    "android.permission.ACCESS_COARSE_LOCATION",
    "android.permission.ACCESS_BACKGROUND_LOCATION",
]
app-theme-parent = "Theme.MaterialComponents.DayNight.DarkActionBar"
``` 

3. run `cargo tauri android dev`

### Expected behavior

1. write or init [package.metadata.cargo-android].
2. run `cargo tauri android dev`
4. `AndroidManifest.xml` updated after cargo watch.

### Platform and versions

```text
Environment
  › OS: Ubuntu 22.10 X64
  › Node.js: 16.16.0
  › npm: 9.1.1
  › pnpm: 7.27.1
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.67.1
  › cargo: 1.67.1
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.2
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected character 't' while parsing major version number")', /home/rainbow/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tauri-cli-2.0.0-alpha.2/src/info.rs:566:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  › @tauri-apps/api [NPM]: tauri-apps%
```

**Comment by amrbashir** [comment]
> The wry template init with android permission config, and I saw [tauri-mobile](https://github.com/tauri-apps/tauri-mobile)/[src](https://github.com/tauri-apps/tauri-mobile/tree/dev/src?rgh-link-date=2023-03-07T07%3A36%3A24Z)/[android](https://github.com/tauri-apps/tauri-mobile/tree/dev/src/android?rgh-link-date=2023-03-07T07%3A36%3A24Z)/config.rs parse the [package.metadata.cargo-android], but [tauri](https://github.com/tauri-apps/tauri/tree/46e6187c89594692b0e245a2ad5ec50de819296b)/[core](https://github.com/tauri-apps/tauri/tree/46e6187c89594692b0e245a2ad5ec50de819296b/core)/[tauri-utils](https://github.com/tauri-apps/tauri/tree/46e6187c89594692b0e245a2ad5ec50de819296b/core/tauri-utils)/[src](https://github.com/tauri-apps/tauri/tree/46e6187c89594692b0e245a2ad5ec50de819296b/core/tauri-utils/src)/config.rs not load cargo.toml after `default()`.

Not all features of tauri-mobile are used in tauri, the config in Cargo.toml is not parsed at all.

> How do I declare the available permissions in the configuration file, directly modifying `AndroidManifest.xml` is not elegant enough.

why so? it is the way that is intended to be used and we are working on improving the situation around `tauri android init` so you can add the `gen` folder to your git repo and keep your changes.
