### ISSUE TITLE
[bug] SyntaxError: Unexpected keyword 'import' in webview

### ISSUE THREAD

**Issue by glennmichael123** [tauri-apps/tauri#6412]
### Describe the bug

When I try running `pnpm tauri dev` it's not able to display anything cause of this error.

```javascript
SyntaxError: Unexpected keyword 'import'

promiseReactionJob
```
<img width="802" alt="image" src="https://user-images.githubusercontent.com/29087513/223595385-175c50f9-0132-4c20-8b2f-14e951676859.png">

### Reproduction

1. Run `pnpm tauri dev` using typescript as the script in `index.html`

### Expected behavior

I expected the Tauri web view window to succeed and not have this error

### Platform and versions

```text
› OS: Mac OS 11.5.2 X64
  › Node.js: 18.14.2
  › npm: 9.5.0
  › pnpm: 7.18.1
  › yarn: Not installed!
  › rustup: 1.25.2
  › rustc: 1.67.1
  › cargo: 1.67.1
  › Rust toolchain: stable-x86_64-apple-darwin

```
```


### Stack trace

```text
SyntaxError: Unexpected keyword 'import'

promiseReactionJob
```
```


### Additional context

I'm using vite `4.0.0` and `main.ts` in my `index.html` instead of `main.js`

**Comment by FabianLars** [comment]
Could you also share the problematic code?

Also since you said you _switched_ from main.js to main.ts - is vite configured to handle typescript? Like, did you install TSC and add a tsconfig file etc (probably easier to create a new vite project)

**Comment by glennmichael123** [comment]
@FabianLars I have now identified the problem, it appears importing UnoCSS directly to `main.ts` would cause this bug. I didn't configure UnoCSS properly in `vite.config`

here's the code in question

```js
import 'uno.css'
```

I've now fixed this problem and thank you for taking the time to look into this.
