### ISSUE TITLE
[bug] cargo tauri dev will strip the contents of all <template> tags

### ISSUE THREAD

**Issue by TimMisiak** [tauri-apps/tauri#6418]
### Describe the bug

Any <template> tags are stripped of all content when being used through "cargo tauri dev". Compiling the app normally seems to work fine. This makes it difficult to use web components.

I tested this against the latest in crates.io, which at this time is 1.2.4

### Reproduction

1. Create a new tauri project with create-tauri-app
2. Add a simple <template> tag to the body, suich as this:
```html
  <body>
    <template id="test">
      <div><p>This is a test</p></div>
    </template>
```
3. Run the application with "cargo tauri dev"

Expected: The template shows up in the source.
Actual: The template is present but empty:
```html
  <body>
    <template id="test"></template>
```

You can confirm this by using curl or dev tools to view the source.

### Expected behavior

The template tags should be maintained when being sent to the browser process.

### Platform and versions

```text
Environment
  › OS: Windows 10.0.19045 X64
  › Webview2: 110.0.1587.63
  › MSVC:
      - Visual Studio Professional 2022
  › Node.js: Not installed!
  › npm: Not installed!
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.67.0
  › cargo: 1.67.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../src
  › devPath: ../src
package.json not found

App directory structure
  ├─ .vscode
  ├─ src
  └─ src-tauri
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by FabianLars** [comment]
I think this was fixed in https://github.com/tauri-apps/tauri/pull/6166 which will be part of tauri 1.3
