### ISSUE TITLE
Question: resource load failed in iframe

### ISSUE THREAD

**Issue by maxiloEmmmm** [tauri-apps/tauri#6420]
env: windows

@lucasfernog hello, same question, resource load failed in iframe

![image](https://user-images.githubusercontent.com/16779121/224316738-6a85838e-4e6a-441a-a59c-2d759b621726.png)
![image](https://user-images.githubusercontent.com/16779121/224316586-177f0fed-ad07-4b63-936f-1050f225a9f3.png)
![image](https://user-images.githubusercontent.com/16779121/224317439-d5b44317-3f09-41ec-ae94-83cb082e4cea.png)
note: 
1. `src` is the same for both iframe's
2. if set convertFileSrc() to  `window.location.href` , anything is ok
![image](https://user-images.githubusercontent.com/16779121/224450641-e0502611-81af-4203-9072-50c7cf7ea94e.png)
![image](https://user-images.githubusercontent.com/16779121/224450658-caf2a839-3c3b-4f07-9d29-39ed1f3c25d6.png)

### front
```jsx
render() {
    return <>
        <iframe src={convertFileSrc(this.test, "dic")}/>
    </>
}
```

### end
```rust
.register_uri_scheme_protocol("dic", |ah, req| {
  let data = read("d:\\text.html");
  ResponseBuilder::new().header("Access-Control-Allow-Origin", "https://dic.localhost").body(data.unwrap())
})
```

_Originally posted by @maxiloEmmmm in https://github.com/tauri-apps/tauri/issues/3543#issuecomment-1463744336_

**Comment by kennethnym** [comment]
Are you still having the same issue? What changes did you make to make this work?

**Comment by maxiloEmmmm** [comment]
> Are you still having the same issue? What changes did you make to make this work?

@kennethnym this way doesn't work, feels like some mechanism doesn't take effect in the iframe.

so in another way 
1. use `invoke` to get html content
2. replace `href` or `src` in html content by`convertFileSrc`
3. render by `v-html`

**Comment by wfc66986** [comment]
我现在就是http嵌套web 一直被拒绝访问 有什么办法解决在iframe内嵌时候
