### ISSUE TITLE
[feat] Move the window to the menu bar (macOS)

### ISSUE THREAD

**Issue by CcSimple** [tauri-apps/tauri#6424]
### Describe the problem

Is this function supported? 

### Describe the solution you'd like

I don't know, I need help! Thanks

**Comment by amrbashir** [comment]
see https://tauri.app/v1/guides/features/system-tray

**Comment by CcSimple** [comment]
<img width="426" alt="image" src="https://user-images.githubusercontent.com/24693863/224587474-5b775424-a747-44c1-985f-c9ca0eac856c.png">
Thank you for your reply, but this is what I want.

**Comment by amrbashir** [comment]
Not sure I quite understand, please explain more, and if possible is there any similar apps?

**Comment by CcSimple** [comment]
Thanks!  it's useful for me.

**ns_window.setCollectionBehavior_**


```

let main_window = app.get_window("main").unwrap();

            #[cfg(target_os = "macos")]
            {
                use cocoa::appkit::{NSMainMenuWindowLevel, NSWindow, NSWindowCollectionBehavior};
                use cocoa::base::id;
                let ns_win = main_window.ns_window().unwrap() as id;
                unsafe {
                    ns_win.setLevel_(((NSMainMenuWindowLevel + 1) as u64).try_into().unwrap());
                    ns_win.setCollectionBehavior_(
                        NSWindowCollectionBehavior::NSWindowCollectionBehaviorCanJoinAllSpaces,
                    );
                }
            }

```

**Comment by amrbashir** [comment]
ah you mean `ns_win.setLevel_`, then this is a duplicate of https://github.com/tauri-apps/tauri/issues/4620

**Comment by ayangweb** [comment]
Hi all👋, although this method achieves the desired result, the system input method runs behind the window when typing. Has anyone encountered this problem and solved it please?

issue: https://github.com/EcoPasteHub/EcoPaste/issues/621
