### ISSUE TITLE
[feat] 

### ISSUE THREAD

**Issue by Mohosin78** [tauri-apps/tauri#6429]
### Describe the problem

I want to run an shell Code **./index-linux** on start tauri-app

### Describe the solution you'd like

I want to run an shell Code **./index-linux** on start tauri-app

**Comment by amrbashir** [comment]
the feature request is ambiguous and doesn't have enough information, Please fill out the issue form properly then ping me and I will reopen the issue.

**Comment by Mohosin78** [comment]
I want a method such that when I launch the application I can run a shell command that will start the express server.

**Comment by Morsmalleo** [comment]
> I want a method such that when I launch the application I can run a shell command that will start the express server.

Maybe this might point you in the right direction 

https://tauri.app/v1/api/js/shell/
