### ISSUE TITLE
error Command failed with exit code 3221226356.

### ISSUE THREAD

**Issue by Bigbadboybob** [tauri-apps/tauri#6430]
Hi guys,
I'm getting this error when I invoke a function as a tauri command however, if I invoke the function normally I don't get an error. If I comment out the function body I also don't get an error.
```
$ yarn tauri dev
yarn run v1.22.19
$ tauri dev
     Running BeforeDevCommand (`yarn dev`)
$ vite
...
error Command failed with exit code 3221226356.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
$yarn -v
1.22.19
```

The function creates a new window using the winit crate.
```
#[tauri::command]
fn new_window() {
    println!("new window");
    let event_loop = EventLoop::new();
    let mut window = blockerw::BlockerW::new(&event_loop); //fails here
    let rect = Rect {
        x: 200,
        y: 200,
        width: 300,
        height: 200,
        color: [0x00, 0x00, 0x00, 0xff],
    };
    window.add_block(Box::new(rect));
    window.run(event_loop);
}
```

```
impl BlockerW {
    pub fn new(event_loop: &EventLoop<()>) -> Self {
        //create window
        let window = WindowBuilder::new()
            .with_decorations(false)
            .with_transparent(true)
            .with_maximized(true)
            //.with_fullscreen(Some(winit::window::Fullscreen::Borderless(None)))
            .with_window_level(WindowLevel::AlwaysOnTop)
            .build(event_loop)
            .unwrap(); //fails here
        ...
```

This error does **not** occur on ubuntu 22.04 but occurs on windows 11

**Comment by FabianLars** [comment]
Sorry for the long delay. I _think_ what's happening is that both tao and winit are fighting for the main thread (basically [this](https://togithub.com/rust-windowing/winit/issues/1585#issuecomment-1176247107) which invoked commands run on. Each OS has slightly different requirements which may be why it doesn't crash on ubuntu.

Either way, what's said in the winit issue also applies to tao which is essentially just a winit fork. Therefore i'm going to close this, sorry.
