### ISSUE TITLE
[feat] "New Folder" button not supported in macOS in the FileDialog

### ISSUE THREAD

**Issue by Nacho114** [tauri-apps/tauri#6435]
### Describe the problem

The "New Folder" button is not supported in macOS for the FileDialog. This is working for Windows and Ubuntu with our current implementation. 

This is how the file dialog looks like for our Tauri app in macOS:

![without](https://user-images.githubusercontent.com/17376073/224670070-597648f0-5cd5-407d-9beb-7950b085d94b.png)

This is how it looks like for VS code, note the `New Folder` button on the left

![vsceoe](https://user-images.githubusercontent.com/17376073/224670230-0298f574-fe9e-437b-a187-50683e8dc64e.png)

### Describe the solution you'd like

Enable "New Folder" support for macOS in the FileDialog. To solve this it might suffice to add:

```js
var canCreateDirectories: [Bool](https://developer.apple.com/documentation/swift/bool) { get set }
```

As described in the [apple docs](https://developer.apple.com/documentation/appkit/nssavepanel/1532626-cancreatedirectories).

### Additional context

Had a quick chat with FabianLars on Discord, he found the apple developer docs.

**Comment by FabianLars** [comment]
Sorry that i asked you to open an issue about it, i missed this one: https://github.com/tauri-apps/plugins-workspace/issues/949. Let's keep tracking it over there.
