### ISSUE TITLE
[bug]  After the project is packaged, the cmd window displays when executing the shell.open(url) method.

### ISSUE THREAD

**Issue by EGo14T** [tauri-apps/tauri#6438]
### Describe the bug

After the project is packaged, the cmd window displays when executing the shell.open(url) method. And there is no problem in the development environment.

Screenshots
![bugs](https://user-images.githubusercontent.com/28916447/224700967-ee2e8721-36f3-4e32-8f51-9d501fe1796a.gif)

### Reproduction

1. create a new project, and modify "greet" method
```tsx
async function greet() {
    open("https://www.baidu.com")
    setGreetMsg(await invoke("greet", { name }));
}
```
2. yarn tauri build

### Expected behavior

The cmd window should not appear

### Platform and versions

```text
› OS: Windows 10.0.19044 X64
  › Webview2: 110.0.1587.69
  › MSVC: 
      - Visual Studio Build Tools 2022
  › Node.js: 16.14.0
  › npm: 8.3.1
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.25.2
  › rustc: 1.68.0
  › cargo: 1.68.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc
```

**Comment by amrbashir** [comment]
This is an issue with the upstream crate `open-rs` that we are using, I will open an issue upstream to fix this, thanks for the report.
