### ISSUE TITLE
[bug] unregister globalShortcut F11

### ISSUE THREAD

**Issue by xueweiwujxw** [tauri-apps/tauri#6445]
### Describe the bug

```ts
  React.useEffect(() => {
    isRegistered('F11').then(async (value) => {
      console.log(value)
      await unregister('F11')
      register('F11', async () => {
        await appWindow.setFullscreen(!(await appWindow.isFullscreen()))
      }).then(() => {
      }).catch((err) => { console.error(err) })
    }).catch((err) => { console.error(err) })
    return () => { }
  }, [])
```
This is the code I used to register the F11 shortcut key.
When I ran `yarn tauri dev` for the first time, the value was false, but I could still see the console output of register error.
```log
[Log] false (App.tsx, line 72, x2)
[Error] hotkey already registered: Accelerator { id: Some(AcceleratorId(19131)), mods: (empty), key: F11 }
	(anonymous function) (App.tsx:78)
```
After I reloaded the page, the value became true, but the register error still exists.
```log
[Log] true (App.tsx, line 72, x2)
[Error] hotkey already registered: Accelerator { id: Some(AcceleratorId(19131)), mods: (empty), key: F11 }
	(anonymous function) (App.tsx:78)
```
But strangely, the shortcut key F11 can be used normally until I opened another tauri application that registered the shortcut key in the same way. The first opened application works normally, but the shortcut key of the later opened application is invalid. And when I focus on the later opened application and press F11, it is actually responded by the first opened application.

### Reproduction

1. run `yarn create tauri-app`
2. use the code to register F11 globalShortcut
3. Repeat the above steps to create two tauri applications and open them, then test the F11 shortcut key.

### Expected behavior

Firstly, the console should not output an error because I should have already unregistered F11 before that.
Secondly, the shortcut keys for the two applications should be independent.

### Platform and versions

```text
`yarn tauri info` output:

yarn run v1.22.19
$ tauri info

Environment
  › OS: Ubuntu 20.04 X64
  › Node.js: 16.19.0
  › npm: 8.19.3
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.68.0
  › cargo: 1.68.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React
  › bundler: Vite

App directory structure
  ├─ .git
  ├─ public
  ├─ .vscode
  ├─ dist
  ├─ src
  ├─ node_modules
  ├─ scripts
  └─ src-tauri
Done in 4.39s.
```

**Comment by FabianLars** [comment]
Hmm, i _think_ tauri's globalShortcut API is not what you are looking for to be honest! There can only be a single application registering a specific shortcut with this API because it's _global_. This means that the F11 key will stop working for all other applications, at least as long as your tauri app is open.

To me it sounds like you'd want to use the standard JavaScript key event stuff like `document.addEventListener('keydown', callback)` 🤔

**Comment by amrbashir** [comment]
Some platforms don't allow other apps to unregister globalShortcuts registered by other apps. Also note that `isRegistered` only checks for globalShortcuts registered by the same app, not other apps and for that we may or may not remove `isRegistered` (haven't been discussed yet).
