### ISSUE TITLE
[bug] saveDialog need twice confirm on Deepin Linux distrubution

### ISSUE THREAD

**Issue by Fozei** [tauri-apps/tauri#6447]
### Describe the bug

When use api save from `import {  save } from "@tauri-apps/api/dialog";`  to select a path for saving a file on OS, the first click on confirm button did not work(focus goes to the file name, and add the file ext to the file name auto,but the dialog does not close), you need to click the confirm button once more, and the dialog closed.

When a file already exists on in the target dir, the os ask you to confirm overwrite, click the confirm button, it does not work,you need confirm twice.

The problem comes from tauri or just comes from specific Linux distrubution?

below is my code:
`
save({
        filters: [
          {
            name: "json",
            extensions: ["json"],
          },
        ],
      })
        .then((path) => {
          if (path) {
            // do some thing ...
          }
        })
        .catch((e) => {
          console.log(e);
        });
`

### Reproduction

1. any tauri app on Deepin Linux distrubution 28.0
2. trigger a save dialog to save file
3. click confirm button

### Expected behavior

save a file

### Platform and versions

```text
› OS: Linux 20.8 X64
  › Node.js: 14.16.1
  › npm: 6.14.12
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.2
  › rustc: 1.67.1
  › cargo: 1.67.1
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Vue.js
  › bundler: Vite

App directory structure
  ├─ .git
  ├─ src-tauri
  ├─ node_modules
  ├─ public
  ├─ src
  ├─ .vscode
  └─ dist
```

### Additional context

VUE3 as frontend and vite as package tool

**Comment by amrbashir** [comment]
tested on KDE and Gnome, both work fine, do you experience the issue with other apps? could you try on other desktop environment?

**Comment by Fozei** [comment]
Ok fine,I plan to try it on other desktop environment.

**Comment by amrbashir** [comment]
Also try to use the dialog from other gtk apps on your Deepin environment and see if they have the same problem. And as a last measure, try to use the dialog from a tauri app in a release build.

**Comment by drl990114** [comment]
@amrbashir  I'm not sure if this is a problem, I ran into something similar.

In macos, I defined the saveFile menu, and then triggered the front-end event, but it was triggered twice.

in rust
```
on_menu_event(|event| match event.menu_item_id() {
            "Save" => {
                println!("file_save emit"); //  once
                event.window().emit("file_save", {});
            }
            _ => {}
  })
```

in web (react)
```

  useEffect(() => {
    let unListen
    const init = async () => {
      unListen = await appWindow.listen('file_save', async () => {
        console.log('filesave') // twice
      })
    }

    init()

    return () => {
      console.log('unlisten', unListen)
      if (unListen)
        unListen()
    }
  }, [selectedPath])
```
In the web app, I'm using the react framework, and I'm sure I only listen to the event once. 


## platform and version

macos 13.1 (22C65)

tauri = { version = "1.2.0", features = ["api-all"] }

**Comment by FabianLars** [comment]
@halodong This sounds more like an issue with your event listener to be honest, can you try these 2 variants and see if they behave the same?
```ts
  useEffect(() => {
    let unListen = appWindow.listen('file_save', () => {
      console.log('filesave')
    });

    return () => {
      console.log('unlisten', unListen);
      unListen.then(f => f());
    }
  }, [selectedPath]);
```

```ts
  useEffect(() => {
    let unListen = appWindow.listen('file_save', () => {
      console.log('filesave')
    });

    return () => {
      console.log('unlisten', unListen);
      unListen.then(f => f());
    }
  }, []); // Note the removed dependency here
```

**Comment by drl990114** [comment]
@FabianLars Thank you, I found the reason, it has nothing to do with deps, I saw your code and realized that it is my writing problem, `await` may cause the component to be updated when there is no return value, so it cannot `unlisten` well, thank you very much.

**Comment by Fozei** [comment]
Sorry for misktake, now I confirm this phenomenon is a code error, tauri app works well, so this issue closed.

**Comment by Fozei** [comment]
Sorry for misktake, now I confirm this phenomenon is a code error, tauri app works well, so this issue closed.
