### ISSUE TITLE
Remove divisive terminology from project

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#645]
**Is your feature request related to a problem? Please describe.**
There are several occurrences of potentially divisive words in our projects, which are unfortunately parts of the common parlance in engineering. We have discussed this in the team chat several times, and I am now opening this issue so we can discuss resolution. 

There are three locations where we are aware of this:
- "master" branch (git structure)
- "whitelist" (tauri.conf.json)
- "kamikaze" (docs - pattern)

There may be more that I am overlooking.

**Describe the solution you'd like**
I would like to find other words that we can use in order to be more intentionally inclusive.

### Suggestions
- `master` => `release` (because this is how we are using that branch as a reflection of the code at a particular state)
- `whitelist` => `permitlist` / `denylist` (remove color from quality assertion)
- `kamikaze` =>  `one-timer` (remove glorification of violence / suicide)

**Describe alternatives you've considered**
Doing nothing and ignoring complicity is actually how fascism becomes powerful.

**Additional context**
I think in the global social context of the current protests and endemic societal racism, it is important to consider the words we use - and how they can internally weaponise mental states. Remaining ignorant and doing nothing about this is, in fact, in contrast with our very own Code of Conduct, and something that we should constantly be vigilant about.

Personally, I feel that GitHub and Git itself should reconsider "creating" new repositories with "Master" as the default base branch. @devonzuegel ?

**Comment by awkj** [comment]
why not  delete white and black from color, let the world only corret color rahter colorful color.

**Comment by rajivshah3** [comment]
While I understand the rationale behind renaming these terms, I'm afraid of discrepancies between projects regarding their new terminology. For this reason, I think that `whitelist`/`blacklist` should be renamed to `allowlist`/`denylist`, as proposed for [Pi-Hole](https://discourse.pi-hole.net/t/change-blacklist-and-whitelist-terminology/31657). This has already been done for [Rails](https://github.com/rails/rails/issues/33677) and [GitLab](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/33552).

As a replacement for "kamikaze", I think "lockdown" might be a better name to advertise the high security rating of that pattern.

**Comment by nothingismagick** [comment]
Great suggestions @rajivshah3

**Comment by jbolda** [comment]
Branch terminology has been updated in https://github.com/tauri-apps/tauri/pull/744.

**Comment by lucasfernog** [comment]
@nothingismagick we need to find a good time to rename "whitelist" to "permlist" (breaking change). Maybe right now?

**Comment by nothingismagick** [comment]
Yeah, now is nice and quiet.

**Comment by nothingismagick** [comment]
Thanks everybody.
