### ISSUE TITLE
[bug] `@tauri-apps/api/fs` `readDir` invalid utf-8 sequence of 1 bytes from index 24

### ISSUE THREAD

**Issue by RubenPX** [tauri-apps/tauri#6457]
### Describe the bug

When i execute readDir in tauri, it returns an error that says: `invalid utf-8 sequence of 1 bytes from index 24`

### Reproduction

Run this code:

```ts
import { readDir } from '@tauri-apps/api/fs';

async function getFoldersList(path: string) {
    let dir = (await readDir(path));
    console.log(dir);
}

getFoldersList("./")
```

### Platform and versions

```text
KryptoPX@KPX MINGW64 ~/Desktop/Tauri
$ yarn tauri info
yarn run v1.22.19
$ C:\Users\KryptoPX\Desktop\Tauri\node_modules\.bin\tauri info

Environment
  › OS: Windows 10.0.19045 X64
  › Webview2: 110.0.1587.69
  › MSVC: 
      - Visual Studio Build Tools 2022
  › Node.js: 19.6.0
  › npm: 9.6.1
  › pnpm: 7.27.1
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.68.0
  › cargo: 1.68.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:8080/
  › framework: Svelte
  › bundler: Vite

App directory structure
  ├─ .svelte-kit
  ├─ .vscode
  ├─ build
  ├─ node_modules
  ├─ src
  ├─ src-tauri
  └─ static

Done in 9.27s.
```

### Stack trace

```text
Browser dev tools:

Uncaught (in promise) invalid utf-8 sequence of 1 bytes from index 24
```

### Additional context

![image](https://user-images.githubusercontent.com/23123160/225236284-737eb3f9-f7f6-4347-99e9-f2f40c431147.png)

**Comment by RubenPX** [comment]
Aparently the issea has resolved when i created a new project... If dev require, i can upload a repo with that issue

**Comment by amrbashir** [comment]
yeah please go ahead and make a repro if possible

**Comment by RubenPX** [comment]
Aparently if i delete taget folder in src-tauri it solved... Unfortunately didn't make a copy of target folder

**Comment by RubenPX** [comment]
@amrbashir 
I found the error. It's because in windows path are represented with "\", example: "C:\Users\user\Desktop". String should be represented as "C:\\Users\\user\\Desktop"
