### ISSUE TITLE
fail to get tauri mobile working

### ISSUE THREAD

**Issue by clep64** [tauri-apps/tauri#6458]
New to tauri and rust.
I followed the documentation installing the tauri app but when I run npm run tauri android dev the emulator opens but no app is displayed I get the usual android home page.
When I run npm run tauri android build I get errors.
Output for both commands are listed in the attached file.
Help would be welcome.
Thanks 

[tauri_mobile _error.txt](https://github.com/tauri-apps/tauri-mobile/files/10974380/tauri_mobile._error.txt)

**Comment by nomorechokedboy** [comment]
I suggest you to run `cargo tauri android dev` (remember to install tauri cli on the next branch for cargo) instead of `npm run tauri android dev`. For me, when I used `npm run tauri android dev`, I got stuck just like you, the app won't pop up

**Comment by clep64** [comment]
Thank you for your tip.
I ran cargo tauri android and actually it goes further compiling the app.
Unfortunately now I got error:
error[E0433]: failed to resolve: use of undeclared crate or module `app`
Probably I missed something in the documentation.
More details on the error in the attached file.
[tauri_mobile _error2.txt](https://github.com/tauri-apps/tauri-mobile/files/10978863/tauri_mobile._error2.txt)

**Comment by nomorechokedboy** [comment]
I think that `app` is not your crate name, you should use 
```rs
your_crate_name::AppBuilder::new().run();
```

You can check for your crate name in `Cargo.toml`

**Comment by amrbashir** [comment]
please share your repo so we can investigate further

<sub>moving this issue to the tauri repo as it belongs there</sub>

**Comment by clep64** [comment]
After previous recommendation i set my crate_name and the build went further.
Nevertheless another error took place.
.../eztimobile/src-tauri/gen/android/eztimobile/app/src/main/java/eztimobile/eztimobile/generated/Logger.kt: (84, 14): Unresolved reference: BuildConfig
I pushed  on github repo  clep64/eztimobile
Thanks

**Comment by nomorechokedboy** [comment]
The file Logger.kt generated by Tauri somehow broke because BuildConfig is imported/resolved so maybe you should generate it again I think

**Comment by clep64** [comment]
I deleted the whole gen folder run cargo android dev and it runs.
Thank you so much for your time.
