### ISSUE TITLE
[bug] Double-clicking on a hotkey does not bind global shortcuts

### ISSUE THREAD

**Issue by ayangweb** [tauri-apps/tauri#6459]
### Describe the bug

I want to bind Shift+Shift as a global shortcut, but it reports an error, why is that? Can't it work or is the shi registered in some other way?

My current code is:

```javascript
register('Shift+Shift', () => { /* do something */ })
```

The error message is:

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/75017711/225324735-d3ad080a-92dc-4d72-9583-be21893a32c6.png">

### Platform and versions

```text
Environment
  › OS: Mac OS 12.6.0 X64
  › Node.js: 16.14.1
  › npm: 9.4.1
  › pnpm: 7.27.0
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.67.0
  › cargo: 1.67.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,
```

**Comment by FabianLars** [comment]
As far as i can see in the OS api docs this does not seem to be supported by the hotkey apis. Therefore i'm closing this. Please feel free to reach out if you find resources showing the opposite :)
