### ISSUE TITLE
[bug] webkit2gtk-sys dependency is missing in cargo.toml

### ISSUE THREAD

**Issue by Harshil-Jani** [tauri-apps/tauri#6492]
### Describe the bug

I am trying out on tauri 2.0.0-aplha.3 and while I did `cargo tauri init` in my NextJS application, The automatically generated `Cargo.toml` misses a library call `webkit2gtk-sys`. So, Why don't we include it from first into the Cargo.toml. I would like to make a contribution for doing this. Let me know about this. 

### Platform and versions

```text
Environment
  › OS: Arch Linux Unknown X64
  › Node.js: 19.3.0
  › npm: 9.2.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.66.0
  › cargo: 1.66.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu
```

### Additional context

The `Cargo.toml` is currently generated as shown below
```rust
[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.64"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-alpha.1" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.0.0-alpha.3" }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]

```

But, It throws error on builds due to missing crate dependency. So, I would want the Cargo.toml to include
```webkit2gtk-sys = "0.19.1"```
this as a dependency.

**Comment by FabianLars** [comment]
Hey, could you post the full error here please? webkitgtk-sys is not supposed to be a user-facing dependency so if it really is a generally problem we should fix it in tauri itself, not in the template imo.

**Comment by Harshil-Jani** [comment]
Strange !! I cannot reproduce the error now and it works perfectly well without adding `webkit2gtk-sys = "0.19.1"`. Maybe I might not remember installing some system libs afterwards which made this to work. 

 Sorry for not cross checking again. Thankyou for considering.

**Comment by FabianLars** [comment]
Alright, i'm closing this issue then but please feel free to reach out when the issue does re-occurs.
