### ISSUE TITLE
Make webserver work for windows / edge

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#65]
https://github.com/Boscop/web-view/blob/master/examples/README.md#actix

> Unfortunately if you run this with the EdgeHTML backend (edge feature) it won't work by default due to webview sandbox restrictions.
> In order for this to run on EdgeHTML, you need to run CheckNetIsolation.exe LoopbackExempt -a -n="Microsoft.Win32WebViewHost_cw5n1h2txyewy" from your administrator command prompt only once and everything works.

**Comment by tensor-programming** [comment]
Will have to look into this.  There is no way aside from building a custom PS script to bypass admin, even then it's not very secure.

**Comment by nothingismagick** [comment]
This is a direct citation from the boscop repo. Maybe we should discuss this there too?

**Comment by tensor-programming** [comment]
I saw that.  I can push it back downstream if I find a solution, I do need to look at how and why this happens before I can have a real discussion about it.

**Comment by nothingismagick** [comment]
Wow - that's ugly - but understandable nonetheless.

**Comment by tensor-programming** [comment]
We will find something.  If its only for development then its not as much of an issue.  If its in production then we need to perhaps bundle a small script in the executable and tell the user to run it with admin privileges the first time.

**Comment by tensor-programming** [comment]
With production at least, we can schedule a powershell script to execute from the installer and bundle it into the msi.  Then we just elevate the MSI to admin to execute it prior to executing the actual installation.  As for the dev pipeline, it might just be a good idea to tell the users to run the script in the readme until an alternative can be found.  Or maybe we can just supply a script that they can use.  I've found that you really only need to run the command once and then its active.

**Comment by nothingismagick** [comment]
I think will be closed by the merge of feature/no-server

**Comment by nothingismagick** [comment]
At least it seems so that final bundles will not have this problem.

**Comment by tensor-programming** [comment]
Alright, well lets close this for now; make a note of the command in the documentation and revisit it if it becomes a problem in the future.
