### ISSUE TITLE
[feat] `tauri add` CLI Command

### ISSUE THREAD

**Issue by lorenzolewis** [tauri-apps/tauri#6505]
### Describe the problem

With doubling-down down on a plugin approach (Issue for context: https://github.com/tauri-apps/tauri/pull/6339, RFC coming soon from @lucasfernog) there are going to be more and more packages to deal with in the Tauri ecosystem. A lot (all?) of them will require the user performing the following steps:

1. Add to Cargo
2. Add to Node (if using)
3. Register the plugin in `main.rs` 
4. Then you can begin using the plugin via imports

This is a lot of steps just to start using something like the upcoming `camera` plugin and can cause a lot of friction to the DX of Tauri.

### Describe the solution you'd like

I'd propose adding a command to the Tauri CLI: `tauri add`. The inspiration from this is the way Astro handles their integration ecosystem: https://docs.astro.build/en/guides/integrations-guide/#automatic-integration-setup

`svelte-add` is another example of this: https://github.com/svelte-add/svelte-add

This could allow you to do something like this:

```bash
pnpm tauri add camera
```

That would complete steps 1-3 for your by...
1. Analysing the project (determine if it's only Rust, if there's a node project, if pnpm, etc.)
2. Propose the changes visually with diffs in the terminal for the user to make (such as adding the dependencies, updating `main.rs`, etc.)
3. Applying those changes on the user's confirmation

### Additional context

This can become quite tricky when dealing with different package versions across the Tauri ecosystem. We may need to have a conversation around what versions and compatibility between versions looks like. I may put in an RFC after this week's WG call to begin this discussion. 

### Future considerations

We may want to look at expanding this to handle adding frontend frameworks (Svelte, Vue, etc.) but that is a lot more complicated. I'd take this as a first step and see where we land.

**Comment by denjell-crabnebula** [comment]
`tauri plugin [add|update|remove]` makes more cognitive sense for me.

**Comment by vasfvitor** [comment]
To add plugins `tauri add` is already in place (still missing the write to `lib.rs` automation) so I guess #7696 supersede this issue.

**Comment by amrbashir** [comment]
thanks @vasfvitor
