### ISSUE TITLE
Implement a simple way to make HTTP request on Rust side

### ISSUE THREAD

**Issue by Clutetot** [tauri-apps/tauri#651]
**Is your feature request related to a problem? Please describe.**
Recently I've encountered a situation where I had to explicitly write every value for `HttpRequestOptions`, most of them are set to `None` except `method`, `url`, `response_type` field.
thinking that there's maybe a way that makes this simple, I started looking through the codebase, then I realized that there's no other way to create `HttpRequestOptions` other than what I just did.

<details>
<summary>example code</summary>

```rust
let first_option = HttpRequestOptions {
    method: "get",
    url: api_url.to_string(),
    params: None,
    headers: None,
    body: None,
    follow_redirects: None,
    max_redirections: None,
    connect_timeout: None,
    read_timeout: None,
    timeout: None,
    allow_compression: None,
    body_type: None,
    response_type: Some(ResponseType::Text)
};

let response = make_request(option);
if let Ok(inner_data) = response {
    let image_url = inner_data.get("image_url").to_owned().unwrap_or(String::from("https://example... /some_image.png"));
    let next_option = HttpRequestOptions {
        method: "get",
        url: image_url,
        ....
    }
}
```
</details>

Considering the size of struct this could quickly become a pain if I start using `make_request` everywhere.
I want web API's authentication process and data retrieving to be handled in a separate thread, and I thought it would be nice to have somewhat simple way to make an HTTP request.

**Describe the solution you'd like**
Some way to abbreviate struct initialization, without stripping the flexibility off.
something like
```rust
// implement From trait that takes method and url
impl From<(&'_ str, &'_ str)> for HttpRequestOptions {
    ...
}

// and change make_request function to take impl Trait
fn make_request(options: impl Into<HttpRequestOptions>) -> crate::Result<String> {
    ...
}

// so that now I can call it like this:
let result_one = make_request(("get", "https://some/url/here"));
// or like this
let result_two = make_request(HttpRequestOptions { method: "get".to_string(), url: "https://..." });

// Maybe this is too much
impl From<(&'_ str, &'_ str, Option<HashMap<String, Value>>, Option<HashMap<String, Value>>)> 
for HttpRequestOptions {
}

// I think this is reasonable
impl From<(&'_ str, &'_str, ResponseType)> for HttpRequestOptions {
}
```

**Describe alternatives you've considered**
Implement Builder for `HttpRequestOptions`, and make `new` to take both `method` and `url` field.
```rust
struct HttpRequestBuilder {
    ...
}

impl HttpRequestBuilder {
    fn new(method: String, url: String) -> Self {
        Self {method, url, params: None, headers: None, ...}
    }

    fn params(mut self, new_params: Option<HashMap<String, Value>>) -> Self {
        self.params = new_params;
        self
    }
    ....
}
```

**Additional context**
I'm thinking about making pull request on my own, if that's okay.
English is not my native language, I'm sorry if there's a grammar error that makes it hard to understand.

**Comment by lucasfernog** [comment]
You're totally correct, sorry I didn't think about it when writing the API. If you have the time to PR the builder pattern, that would be lovely. Otherwise let me know and I'll make some time to do it.

**Comment by Clutetot** [comment]
Pull request merged, closing.
