### ISSUE TITLE
Can't bind on 127.0.0.1:1430

### ISSUE THREAD

**Issue by FH0** [tauri-apps/tauri#6511]
### Describe the bug

`error binding to 127.0.0.1:1430: error creating server listener:`

If I replace devPath with an invalid string and then replace it with a valid string then there is no problem.
![录制_2023_03_21_10_37_35_304](https://user-images.githubusercontent.com/32861476/226506741-9f061f46-0964-4248-a9fb-9b80e123597e.gif)

### Platform and versions

```text
Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 111.0.1661.44
  › MSVC: 
      - Visual Studio Community 2022
  › Node.js: 18.15.0
  › npm: 9.5.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.2
  › rustc: 1.68.0
  › cargo: 1.68.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../src
  › devPath: ../src
package.json not found

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ pdf
  ├─ src
  ├─ src-tauri
  └─ target
```

**Comment by FH0** [comment]
https://github.com/tauri-apps/tauri/commit/792d5ebf72eeaf09f4b8e306c6ce0fb2e73c62a3 fixed

**Comment by amrbashir** [comment]
The PR hasn't been merged yet, see https://github.com/tauri-apps/tauri/pull/6514
