### ISSUE TITLE
[docs][bug?] cli module is not documented

### ISSUE THREAD

**Issue by Kiyozz** [tauri-apps/tauri#6515]
```
tauri "1.2.3"
@tauri-apps/api 1.2.0
```

If I want to use

```js
import { getMatches } from '@tauri-apps/api/cli'
```

Tauri says you need to enable the `Cli` module.

```
The `Cli` module is not enabled. You must enable one of its APIs in the allowlist.
```

Like every other module, you enable them in the `tauri.allowlist` property in `tauri.conf.json` file.

Like,

```json
{
  "tauri": {
    "allowlist": {
      "cli": {
        "all": true
      }
    }
  }
}
```

But, Tauri says

```shell
 Error `tauri.conf.json` error on `tauri > allowlist`: Additional properties are not allowed ('cli' was unexpected)
 ```

The only way to use the `Cli` module is to enable **all** APIs by using

```json
{
  "tauri": {
    "allowlist": {
      "all": true
    }
  }
}
```

But I do not want to enable all APIs.

So, Tauri is either missing documentation for the Cli module, or Tauri is missing the allowlist for the Cli module

**Comment by FabianLars** [comment]
The cli feature is really in a weird state right now to be honest (and i think we want to remove it from core in an upcoming major release too iirc). It's really only documented here <https://tauri.app/v1/guides/features/cli> - and it's indeed not configurable via the allowlist but instead by its own config object similar to the system tray feature.

**Comment by Ramon-Wong** [comment]
well interesting and good to know about the status of cli
since I'm stuck with this as well

**Comment by shinebayar-g** [comment]
Uh oh, so `allowlist.all: true` is the only way to parse cli arguments at the moment?
