### ISSUE TITLE
Build release on android not working

### ISSUE THREAD

**Issue by ZeroSkillCoding** [tauri-apps/tauri#6528]
I'm sorry if this is an inappropriate question, but is it possible for now to build a release android .apk? When i use `cargo tauri android dev`, project works fine on emulators.

When I start building the application with the regular command `cargo tauri android build`, it builds it smoothly into .aab and .apk formats, but without a signed certificate. I decided to manually sign it using the command `jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore my-release-key.keystore app-universal-release-unsigned.apk app`. When installing the application on the emulator, it throws an error `The APK failed to install. Error: INSTALL_FAILED_INVALID_APK: Failed to extract native libararies, res=-2` and also doesn't install on other devices. 
![image](https://user-images.githubusercontent.com/99201487/226932851-73063a5a-cbb8-4bca-9718-fe7b4ce97e03.png)

I tried unpacking the .apk from .aab using the command `java -jar "bundletool-all-1.14.0.jar" build-apks --mode="universal" --bundle="app-universal-release.aab" --output="release.apks"`, and now the application installs, but instantly stops working on all devices. Now I want to try creating a new project in Android Studio and follow the instructions from /wry/blob/dev/MOBILE.md and wry/README.md entirely, but I don't quite understand at the end of the repository description how to correctly configure the environment variables that specifically concern WRY and which Kotlin files are needed.

Thank you so much, i would be grateful for any answer and help regarding this matter ❤

**Comment by Meteplus** [comment]
yes,i have the same problem. this problem make me depressed these days, i make the signature with the following command: .\jarsigner.exe -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore C:\Users\saine\myappsig.jks -storepass mypass  C:\Projects\tauri\tauri_mobile\my_first_tauri_mobile\src-tauri\gen\android\my_first_tauri_mobile\app\build\outputs\apk\universal\release\app-universal-release-unsigned.apk test

**Comment by amrbashir** [comment]
Signing the apk while building it according to the guide in this PR https://github.com/tauri-apps/tauri-docs/pull/1189 works fine, although you will be met with https://github.com/tauri-apps/tauri/issues/6560 which I am trying to fix atm.

**Comment by rnakhan** [comment]
Just ran into this. If this is not planned then how do people install locally generated apks on a test device with developer profile (for testing)?

**Comment by rnakhan** [comment]
> Just ran into this. If this is not planned then how do people install locally generated apks on a test device with developer profile (for testing)?

nvm you can build with debug flag 
tauri android build -- --debug --apk
