### ISSUE TITLE
[bug] Mouse disappears when selecting nested html elements in tauri project - Interacts normally

### ISSUE THREAD

**Issue by HarrisonLeece** [tauri-apps/tauri#6533]
### Describe the bug

https://www.youtube.com/watch?v=92qTVTh3FDg

Look at the behavior of the mouse in the above video

### Reproduction

1) Launch Tauri Project
2) Inspect element
3) Drop down a couple of nested element
4) Watch mouse disappear

### Expected behavior

I expect to see the mouse at all times to help click the drop down button in the inspect element console

### Platform and versions

```text
Ubuntu 22.04, pnpm tauri dev and cargo tauri dev affected
```

### Stack trace

```text
N/A
```

**Comment by amrbashir** [comment]
We don't control the rendering unfortunately, especially the inspector. This is something to do with webkit2gtk. I know it is annoying but we can't do anything about it unfortunately.
