### ISSUE TITLE
[feat] 

### ISSUE THREAD

**Issue by ugger0101** [tauri-apps/tauri#6534]
### Describe the problem

I want the program to link to the network through the system proxy, but the corresponding solution is not given in the document, I can only use Axios package to achieve this purpose, and I can't use ```fetch``` to send request by proxy

### Describe the solution you'd like

I hope tauri can add this function, like electron using Session to Manage browser sessions, cookies, cache, proxy settings, etc.
and  I just need to modify or add this program statement ``ses.setProxy(config)``` to enable the program to request by proxy

**Comment by FabianLars** [comment]
Let's track this in https://github.com/tauri-apps/tauri/issues/4263 instead :) Thanks for the request!
