### ISSUE TITLE
[bug] Android version fails on Airplane mode

### ISSUE THREAD

**Issue by Bha-Gu** [tauri-apps/tauri#6564]
### Describe the bug

An app made using tauri + yew compiled to android device with the airplane mode active it gives the Webpage not found message

### Reproduction

1.) Make a tauri + yew app even a template will do (not tested with other front ends)
2.) Compile it for and install it on and android device
3.) Turn the airplane mode on
4.) Try running the app and it throws the following
![Screenshot_20230326132038](https://user-images.githubusercontent.com/67630917/227762612-b92775f5-9208-4fc7-a0af-028773772cd5.png)

### Expected behavior

I expected the airplane mode to make no difference in the functionality of the app
Like this
![Screenshot_20230326131705](https://user-images.githubusercontent.com/67630917/227762648-733f406b-e830-4815-b34e-e453744bd716.png)

### Platform and versions

```text
Environment
  › OS: Fedora 38.0.0 X64
  › Node.js: Not installed!
  › npm: Not installed!
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.2
  › rustc: 1.68.1
  › cargo: 1.68.1
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.4
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 2.0.0-alpha.4,
  › tauri-build [RUST]: 2.0.0-alpha.2,
  › tao [RUST]: 0.18.3,
  › wry [RUST]: 0.27.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
package.json not found

App directory structure
  ├─ .vscode
  ├─ target
  ├─ src
  ├─ dist
  ├─ public
  └─ src-tauri
{From "cargo tauri info"}
Tested on android version 12
```

### Additional context

With the way tauri makes these apps, that being web apps using systems web-view, will it ever be possible to make it work with airplane mode?

**Comment by amrbashir** [comment]
Is this apk built using `tarui android dev` or `tauri android build`?

**Comment by Bha-Gu** [comment]
It did happen through `tauri android dev` and also with 
(`tauri android dev --open` and generating a release build for the apk through android studio as signing the app myself sounded like to many steps) which may be equivalent to `tauri android build`
Also i disabled minify in release mode as that was causing the app to not launch at all. (Guess that should have been its own bug report)

**Comment by Bha-Gu** [comment]
I just checked it is working fine through `tauri android build` after 
`---- getByName("release") {
    isMinifyEnabled = true
---- } ----`
is changed to 

`---- getByName("release") {
    isMinifyEnabled = false
---- } ----`

because with it app just crashed on launch (Sorry, previous point probably should be a different bug report)
but `tauri android dev` and `tauri android dev --open` and using android studio to make signed apk still does not work

**Comment by amrbashir** [comment]
For the webpage not available, that is because `tauri android dev` or `tauri android dev --open` builds the app in dev mode where it makes requests to a local server, if that local server doesn't exist, it will error as seen in the screenshot.

We will make the apk signed through `tauri android build` before tauri@v2 hits stable so thanks for your patience and testing.

As for the crash, can you confirm if it is the crash is the same as https://github.com/tauri-apps/tauri/issues/6560 ? if not, please open another issue.

**Comment by Bha-Gu** [comment]
Yes, the crash seems the same as #6560 
Thank you for everything
