### ISSUE TITLE
[feat] API to clear webview-managed data

### ISSUE THREAD

**Issue by prestomation** [tauri-apps/tauri#6567]
### Describe the problem

My application uses cookies/localStorage on the javascript side for various purposes.

I don't see a clear way to clear all the stuff stored by the Webview engine. I could have the javascript side clear these, but there are things that this side can't clear like disk cache, etc

### Describe the solution you'd like

I want to put a native button like 'Logout' that clears all this data. 

An API on app/app_handle that clears this data might make sense. Maybe it needs to be part of exit or relaunch?

### Alternatives considered

I considered manually deleting some of the path_resolver() directories, but directories like `/Users/pttamkin/Library/HTTPStorage/{pkg}` and `/Users/pttamkin/Library/WebKit/{pkg}` aren't captured here. Also not sure I can delete these while my app is running?

**Comment by unixapple** [comment]
I have this requirement too, for example user may want to switch to user another user to login to my app, and the authentication is done by using webview and authenticated data is stored in the cookie.

It seems we can do this by remove some data in app dir?

**Comment by FabianLars** [comment]
> It seems we can do this by remove some data in app dir?

Yeah you could, but at least on Windows this should only reliable work when there is no webview open, as far as i know at least.

Anyway, in contrast to last time we talked about this API all webviews should now have built-in ways to clear the data so it should be possible now for us to implement this :)

**Comment by unixapple** [comment]
> > It seems we can do this by remove some data in app dir?
> 
> Yeah you could, but at least on Windows this should only reliable work when there is no webview open, as far as i know at least.
> 
> Anyway, in contrast to last time we talked about this API all webviews should now have built-in ways to clear the data so it should be possible now for us to implement this :)

Glad to hear that, it seems the javascript context can't be accessed directly from the tauri WebviewWindow object, if the API is not implemented now, do you know there is some way we can inject a tiny javascript to the webview to do that ? can initialization_script achieve that?

I do not know much above web programming, if there is an API to be released, I can delay a feature depend on this and implement when the API is released, thanks a lot.

**Comment by FabianLars** [comment]
> Glad to hear that, it seems the javascript context can't be accessed directly from the tauri WebviewWindow object, if the API is not implemented now, do you know there is some way we can inject a tiny javascript to the webview to do that ? can initialization_script achieve that?

The API we're talking about here would need to be implemented in Rust (via the webview bindings) so we _could_ add an api for it on the WebviewWindow object too (unless there are security concerns i don't have in mind right now)

**Comment by j67Sv89n** [comment]
Most likely you need to find the paths or folders where the files are stored, check different options for deleting them,
manually or by code, delete them in parts, etc.
```
Option 1: Deleting cache path, C:\Users\<username>\AppData\Roaming\<appname>\Cache, directly:
Option 2: which also clears the same C:\Users\<username>\AppData\Roaming\<appname>\Cache directory
```
You can also use native Rust code, which has access to the file system and deletes files and folders.
Based on the general description, mostly problems arise because You reference or use the cache while the program is running.

**Comment by datner** [comment]
any updates on this?

**Comment by imfunniee** [comment]
hello??

**Comment by FabianLars** [comment]
Hi 👋
