### ISSUE TITLE
[bug] Badge Count issue

### ISSUE THREAD

**Issue by ElectronMB** [tauri-apps/tauri#6571]
### Describe the bug

I am trying to add the badge count in the tauri app but I can't find any documentation regarding this issue.
I want to create a badge icon like the ElectronJS feature ``` app.badgeCount ```.
below is the image I want to create in the tauri platform in macOS and windows.

### Expected behavior

![image](https://user-images.githubusercontent.com/118716238/228142602-31211931-d0a6-441a-bcf0-b921f02819d4.png)

### Platform and versions

```text
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 111.0.1661.54
  › MSVC: 
      - Visual Studio Build Tools 2017
      - Visual Studio Build Tools 2019
  › Node.js: 16.15.1
  › npm: 8.11.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.68.0
  › cargo: 1.68.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../src
  › devPath: ../src

App directory structure
  ├─ .vscode
  ├─ node_modules
  ├─ src
  └─ src-tauri
```

**Comment by FabianLars** [comment]
Let's track this over here https://github.com/tauri-apps/tauri/issues/4489 :)

p.s. there's no built-in api for that, so the possible workarounds are either using platform apis yourself, or by using multiple icons and switching them at runtime (though i don't know if that works for the taskbar icon)
