### ISSUE TITLE
[bug] Listen notification event in windows and MacOS

### ISSUE THREAD

**Issue by ElectronMB** [tauri-apps/tauri#6572]
### Describe the bug

I successfully created the notification using below code in tauri.

import { isPermissionGranted, requestPermission, sendNotification } from '@tauri-apps/api/notification';
let permissionGranted = await isPermissionGranted();
if (!permissionGranted) {
  const permission = await requestPermission();
  permissionGranted = permission === 'granted';
}
if (permissionGranted) {
  sendNotification('Tauri is awesome!');
  sendNotification({ title: 'TAURI', body: 'Tauri is awesome!' });
}

How can handle the window notification event in the tauri platform?
For example, I want to handle the google-chat notification event when someone message me so I can push the notification on that event.

### Expected behavior

I want to show a notification when the chrome event is triggered on macOS and windows platforms.

### Platform and versions

```text
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 111.0.1661.54
  › MSVC: 
      - Visual Studio Build Tools 2017
      - Visual Studio Build Tools 2019
  › Node.js: 16.15.1
  › npm: 8.11.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.68.0
  › cargo: 1.68.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../src
  › devPath: ../src

App directory structure
  ├─ .vscode
  ├─ node_modules
  ├─ src
  └─ src-tauri
```

**Comment by amrbashir** [comment]
I don't think this is possible, you can't just listen to other apps notifications. Even if there is somehow a workaround to do so, It won't be implemented in tauri
