### ISSUE TITLE
[bug] Not receiving chrome window notification when loading external url through Tauri

### ISSUE THREAD

**Issue by web95-moon** [tauri-apps/tauri#6574]
### Describe the bug

Can we listen to chrome browser events?

for example:- if an email is received on Gmail, it sends a push notification to the window.

push notification events are supported with electron-js. below is the code for electron-js for reference only

const clickCallback = () => {
  ipcRenderer.send('notificationClicked')
}

const NativeNotification = window.Notification;

// Note: this must be the good old ES5 function,
// Dont convert this into an ES6 arrow function
const newNotify = function (title: string, options?: NotificationOptions) {
  const instance: Notification = new NativeNotification(title, options);
  instance.addEventListener('click', clickCallback);
  return instance;
}

newNotify.requestPermission = NativeNotification.requestPermission.bind(NativeNotification);

Object.defineProperty(newNotify, 'permission', {
  get: () => NativeNotification.permission,
});

window.Notification = newNotify as any;

so is there any workaround solutions to get the same behavior with Tauri?

i am loading external URL like www.gmail.com using tauri.

### Expected behavior

When I load an external Gmail URL in the Tauri app I am expecting to receive a notification when a new email is received.

### Platform and versions

```text
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 111.0.1661.54
  › MSVC: 
      - Visual Studio Build Tools 2017
      - Visual Studio Build Tools 2019
  › Node.js: 16.15.1
  › npm: 8.11.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.68.0
  › cargo: 1.68.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../src
  › devPath: ../src

App directory structure
  ├─ .vscode
  ├─ node_modules
  ├─ src
  └─ src-tauri
```

**Comment by amrbashir** [comment]
Tauri's APIs are not injected in external URLs, see #5918
