### ISSUE TITLE
[bug] CSS performance on MacOS is bad

### ISSUE THREAD

**Issue by DaAitch** [tauri-apps/tauri#6577]
### Describe the bug

I wanted to test tauri, but CSS performance (on my machine) is very bad and doesn't even come close to browser performance, although I'm not testing sophisticated CSS. Animations seems to have problems.

Check the [Sign-In Example](https://picocss.com/examples/sign-in/) in the browser which performs bad on my machine with tauri, but doesn't have problems in the browser:

- clicking on a "switch slider" performs worse the larger the window is
- the input field border fades color on focus and has very low fps on a large window

Profiling says "composition" takes more than a frame time.

Frames: <img width="200" alt="image" src="https://user-images.githubusercontent.com/1917071/228390421-9c1febae-2a83-4c51-ac89-2f18543c5e96.png">
Events: <img width="200" src="https://user-images.githubusercontent.com/1917071/228390824-4277c4f6-993f-4533-8023-88cb7e48682c.png">

I've also tested everything with tauri v2-alpha, but same.

Anyway, thanks for creating and maintaining tauri.

### Reproduction

1. default tauri/vite/solidjs TS template
2. `npm install @picocss/pico --save`
3. paste [Sign-In Example](https://picocss.com/examples/sign-in/) into `App.tsx` (remove xml comments and make `<input />` self-closing, or it's no valid tsx)
4.  `npm run tauri dev`
5. go fullscreen
6. click on "remember me" switch and compare to the browser version

### Expected behavior

no stuttering for such an animation task

### Platform and versions

```text
Environment
  › OS: Mac OS 12.6.3 X64
  › Node.js: 19.2.0
  › npm: 8.19.3
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.25.2
  › rustc: 1.70.0-nightly
  › cargo: 1.70.0-nightly
  › Rust toolchain: nightly-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: SolidJS
  › bundler: Vite

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .vscode
  └─ src
```

**Comment by FabianLars** [comment]
which browsers did you test it in? Safari? If not, please do test Safari since it's also using WebKit like the WebView.

**Comment by DaAitch** [comment]
wow you're right! Safari is also slow.
I'm happy that this is not a tauri issue and sad that it also uses the same slow component.
I'll will check if there are some Safari issues for the CSS library. It better should, it's quite obvious.

Thank for helping.

**Comment by DaAitch** [comment]
https://github.com/picocss/pico/issues/340

**Comment by DaAitch** [comment]
In case somebody run into the same issue:

- I had problems with MacOS 12.6.3, Safari 15.6.1
- after update they are disappear (MacOS 13.3, Safari 16.4)
