### ISSUE TITLE
[bug] `window.__TAURI_IPC__ is not a function` when not using a dev server

### ISSUE THREAD

**Issue by Berrysoft** [tauri-apps/tauri#6594]
### Describe the bug

I would like to debug on Android without dev server to see how a release build works like. I can see that it gets the right js script from the asset manager, but `__TAURI_IPC__` is not injected.

By the way, the release build of the same app exits abormally just after starts.

### Reproduction

```
npm run build
cargo tauri android dev --feature custom-protocol
```

### Expected behavior

It should work.

### Platform and versions

```text
Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 111.0.1661.54
  › MSVC: 
      - Visual Studio Community 2022
  › Node.js: 18.15.0
  › npm: 9.5.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.2
  › rustc: 1.70.0-nightly
  › cargo: 1.70.0-nightly
  › Rust toolchain: nightly-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.4
  › @tauri-apps/api [NPM]: 2.0.0-alpha.1
  › tauri [RUST]: 2.0.0-alpha.4 (no manifest),
  › tauri-build [RUST]: 2.0.0-alpha.2 (no manifest),
  › tao [RUST]: 0.18.3 (no manifest),
  › wry [RUST]: 0.27.1 (no manifest),

App
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › framework: Vue.js
  › bundler: Vite

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

### Stack trace

```text
03-30 22:55:20.977  9079  9079 W Tauri/Console: File: http://127.0.0.1:37361/assets/index.217dae30.js - Line 1 - Msg: Could not find "window.__TAURI_METADATA__". The "appWindow" value will reference the "main" window label.
03-30 22:55:20.977  9079  9079 W Tauri/Console: Note that this is not an issue if running this frontend on a browser instead of a Tauri window.
03-30 22:55:21.046  9079  9079 E Tauri/Console: File: http://127.0.0.1:37361/assets/index.217dae30.js - Line 1 - Msg: TypeError: window.__TAURI_IPC__ is not a function
03-30 22:55:21.053  9079  9079 E Tauri/Console: File: http://127.0.0.1:37361/assets/index.217dae30.js - Line 1 - Msg: TypeError: window.__TAURI_IPC__ is not a function
```

### Additional context

I redirect the dist url to a custom axum server, and the server searches the files from the asset manager. I'm sure that it resolves the right asset files.

I also tries the same app and build features on Windows, and it works well.

**Comment by amrbashir** [comment]
could try using `tauri android dev --release` instead

**Comment by amrbashir** [comment]
> By the way, the release build of the same app exits abormally just after starts.

this is the same as https://github.com/tauri-apps/tauri/issues/6560 and is being fixed by #6588

**Comment by Berrysoft** [comment]
> could try using `tauri android dev --release` instead

Dev command doesn't accept `--release`

**Comment by amrbashir** [comment]
Oh seems like we didn't add that one for mobile targets yet

**Comment by rherrmannr** [comment]
Got the same problem on Linux.

**Comment by lucasfernog** [comment]
Note that `dev --release` just runs the app with devserver but on Rust's release mode instead. It is NOT the same as the built application.

**Comment by lucasfernog** [comment]
> I redirect the dist url to a custom axum server

You can't really do that until we merge #5918. Then you'll be able to configure your server URLs as allowed remote domain.

**Comment by Berrysoft** [comment]
> Then you'll be able to configure your server URLs as allowed remote domain.

The server is running locally, together with the app itself. I'm sure it works well now.
