### ISSUE TITLE
[bug]  window11 run pnpm tauri dev->   failed to compile `icons/icon.ico` into a Windows Resource file during tauri-build: program not found

### ISSUE THREAD

**Issue by Zourunfa** [tauri-apps/tauri#6595]
### Describe the bug

> [bug]  window11 run pnpm tauri dev->   failed to compile `icons/icon.ico` into a Windows Resource file during tauri-build: program not found

I try to all  #2871 ways . it can not solve this problem

### Reproduction

1. npm create tauri-app@latest
2. pnpm i
3. pnpm tauri dev

### Expected behavior

run the tauri native window

### Platform and versions

```text
S C:\Users\47302\Desktop\rust\tauri-fly>   pnpm tauri dev

> tauri-fly@0.0.0 tauri C:\Users\47302\Desktop\rust\tauri-fly
> tauri "dev"

     Running BeforeDevCommand (`pnpm dev`)

> tauri-fly@0.0.0 dev C:\Users\47302\Desktop\rust\tauri-fly
> vite


  VITE v4.2.1  ready in 546 ms

  ➜  Local:   http://127.0.0.1:1420/
  ➜  Network: use --host to expose
        Info Watching C:\Users\47302\Desktop\rust\tauri-fly\src-tauri for changes...
   Compiling tauri-fly v0.0.0 (C:\Users\47302\Desktop\rust\tauri-fly\src-tauri)
error: failed to run custom build command for `tauri-fly v0.0.0 (C:\Users\47302\Desktop\rust\tauri-fly\src-tauri)`

Caused by:
  process didn't exit successfully: `C:\Users\47302\Desktop\rust\tauri-fly\src-tauri\target\debug\build\tauri-fly-123c633341e481fe\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=desktop
  cargo:rustc-cfg=dev
  package.metadata does not exist
  failed to compile `icons/icon.ico` into a Windows Resource file during tauri-build: program not found
 ELIFECYCLE  Command failed with exit code 4294967295.
 ELIFECYCLE  Command failed with exit code 101.
```

### Additional context

I installed the Windows SDK as follows. Is there a problem
![image](https://user-images.githubusercontent.com/51783403/229006256-4d943ed4-cad7-45b2-9546-d7175f191841.png)

**Comment by FabianLars** [comment]
Can you also add the output of `pnpm tauri info` please?

**Comment by Zourunfa** [comment]
> Can you also add the output of `pnpm tauri info` please?
ok  




`

> tauri-fly@0.0.0 tauri C:\Users\47302\Desktop\rust\tauri-fly
> tauri "info"


Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 111.0.1661.54
  › MSVC: 
  › Node.js: 16.17.0
  › npm: 8.15.0
  › pnpm: 7.27.0
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.68.1
  › cargo: 1.68.1
  › Rust toolchain: stable-x86_64-pc-windows-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected character 't' while parsing major version number")', src\info.rs:566:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

`

**Comment by FabianLars** [comment]
Is using the msvc toolchain instead of gnu an option for you? It tends to work much better on Windows. to switch you just need to make sure the visual studio build tools are installed (https://tauri.app/v1/guides/getting-started/prerequisites#setting-up-windows) and then you can switch by using `rustup default stable-msvc`

**Comment by Zourunfa** [comment]
![image](https://user-images.githubusercontent.com/51783403/229313471-4e1db897-e138-4e10-bb11-2754f8485185.png)
nice  thank you, I will start my first tauri application

> Is using the msvc toolchain instead of gnu an option for you? It tends to work much better on Windows. to switch you just need to make sure the visual studio build tools are installed (https://tauri.app/v1/guides/getting-started/prerequisites#setting-up-windows) and then you can switch by using `rustup default stable-msvc`
