### ISSUE TITLE
Tauri apps dont work on pentiums[bug] 

### ISSUE THREAD

**Issue by Sombra6** [tauri-apps/tauri#6605]
### Describe the bug

I cant install,or run tauri apps on Pentiums and windows 7

### Platform and versions

```text
It isnt something in the compiler.
```

**Comment by FabianLars** [comment]
Did you compile your app for 32bit systems? https://tauri.app/v1/guides/building/windows#building-for-32-bit-or-arm

Did you change the webview install mode to something that's more compatible with windows 7? https://tauri.app/v1/guides/building/windows#embedded-bootstrapper

**Comment by amrbashir** [comment]
Please provide the needed information like steps to reproduce and stack traces or erros. I will reopen the issue once the needed info is provided.
