### ISSUE TITLE
[bug] Window without decorations doesn't resize properly html elements on resize.

### ISSUE THREAD

**Issue by grey4owl** [tauri-apps/tauri#6609]
### Describe the bug

When you start resizing window, the height of the element is not updated and displayed properly as is the case with the browser version..

### Reproduction

1. Set `decorations` to `false` and `resizable` to `true` in `tauri.conf.json`.
2. Create an html element with css `height` property set to `-webkit-fill-available`.
````html
<div style='height: -webkit-fill-available; width: 100px; background: yellow'></div>
````
3. Try to resize window from bottom to top.

 

### Expected behavior

The height of the element should be updated and follow the height of the window.

### Platform and versions

```text
Environment
  › OS: Fedora 38.0.0 X64
  › Node.js: Not installed!
  › npm: Not installed!
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.2
  › rustc: 1.68.2
  › cargo: 1.68.2
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../src
  › devPath: ../src
package.json not found

App directory structure
  ├─ design
  ├─ src-tauri
  └─ src
```

### Additional context

Video about better understanding of the problem: https://youtu.be/Qll4A50aIhA
As you can see in the video, the problem only occurs when you try to resize the window from bottom to top or vice versa and it looks like the problem is somehow with the width of the element? If you constantly update the width of the element you solved the problem so i made a temporary crappy fix in js:

````javascript
var width = 100
window.addEventListener("resize", (event) => {
  let el = document.querySelector("main")
  el.style.width = width + 'vw'
  if (width > 100) {
    width = 100
  } else {
    width +=  0.01
  }
})
````

**Comment by amrbashir** [comment]
I couldn't reproduce this, could you make a minimal repro? Also does it happen only when the devtools are open or even if it is closed?

**Comment by amrbashir** [comment]
closing for this inactivity
