### ISSUE TITLE
[bug] Cannot build on DeckOS(Arch Linux)

### ISSUE THREAD

**Issue by charliemonnone** [tauri-apps/tauri#6611]
### Describe the bug

The prerequisite setup for Arch Linux results in an error on the `cargo create-tauri-app` step. After installing all Linux pre-reqs and running `create-tauri-app`, I was presented with this message:

```
Your system is missing dependencies (or they do not exist in $PATH):
webkit2gtk & rsvg2 │ Visit https://tauri.app/v1/guides/getting-started/prerequisites#setting-up-linux
```

### Reproduction

1. Open terminal
2. Install system dependencies with [pacman](https://tauri.app/v1/guides/getting-started/prerequisites/#1-system-dependencies)
3. Run `cargo install create-tauri-app`

### Expected behavior

The script should finish running without reporting missing dependencies.

### Platform and versions

```text
create-tauri-app version 3.3.0
cargo 1.68.2
rustup 1.25.2 
rustc 1.68.2 (9eb3afe9e 2023-03-27)
```

### Additional context

There weren't any install errors during the system library  installations.

**Comment by FabianLars** [comment]
Did you mean SteamOS for the steam deck? I can't find a DeckOS arch derivative 🤔 

Also, is only create-tauri-app complaining or does `cargo tauri build` also not work?

And lastly, do you have homebrew installed? There are known issues with that, see https://tauri.app/v1/guides/faq#build-conflict-with-homebrew-on-linux

**Comment by charliemonnone** [comment]
Yes, SteamOS, sorry if that wasn't clear. As I understand it, the distro is mostly a modified version of arch(pacman works). I do use linuxbrew and I wasn't aware there is a conflict, so thanks for linking that part of the FAQ, I'll take a look at the proposed solutions.

As for `cargo tauri build`, I actually can't run it due to needing to install `tauri-cli` which fails to install because the linker can't find `stdint.h`. I'd chalk that up to an issue with this particular distro not being intended for development, so I'll close this issue as it seems to be an issue with the platform I'm using and not Tauri.

Thanks for your help!
