### ISSUE TITLE
[feat] JS window menu API

### ISSUE THREAD

**Issue by KaKi87** [tauri-apps/tauri#6617]
### Describe the problem

Window menu can't be set from JS.

### Describe the solution you'd like

A JS window menu API would allow setting window menu from JS.

### Alternatives considered

None

### Additional context

None

---
Thanks

**Comment by TechStudent10** [comment]
Is this being implemented or...

**Comment by KaKi87** [comment]
No, backlog = to-do.

https://en.wikipedia.org/wiki/Product_backlog

**Comment by TechStudent10** [comment]
> No, backlog = to-do.
> 
> https://en.wikipedia.org/wiki/Product_backlog

I didn't see that, I was on mobile. (GitHub doesn't show Project updates on mobile, for whatever reason)

**Comment by danvk** [comment]
Full control of the menu bar from JS would be a great feature to have. I'd like to be able to define the menu bar on the JS side and have it be a native menu for desktop but a DOM element if I'm building for the web. Something like:

```ts
<Menu name="file">
  <MenuItem name="Save As" id="save-as" />
  <MenuSeparator />
  <MenuItem name="Quite" id="quit" />
</Menu>
```

the only missing piece is some way to set menus programmatically in Tauri.

**Comment by amrbashir** [comment]
I don't think we will providing that, we will only provide a programmatic JS menu api (around native menu APIs) that will work only in tauri. A fallback to a JS implementation and DOM elements for web sounds cool but it will probably be an unofficial plugin.

**Comment by danvk** [comment]
@amrbashir we'll certainly be building this ourselves, we just need some way of programmatically setting the menu (either from Rust or JS) to make it possible.

**Comment by KaKi87** [comment]
So, this will only be available in v2 ?

**Comment by amrbashir** [comment]
yeah, only v2, we don't have enough resources to backport it to v1 and probably can't as it includes many breaking changes in the underlying windowing crate (tao)

**Comment by KaKi87** [comment]
I see. Not pointing fingers, but when told that v1 would continue being maintained when v2 development started, I didn't think it meant bugfixes only.

With all the good stuff only being added to v2, it's like v1 already outlived its usefulness and we're waiting again.

**Comment by amrbashir** [comment]
v1 is still maintained and most of new features and bug fixes will be backported if possible without breaking changes, which is not the case for the new menu APIs (Rust and JS)

**Comment by KaKi87** [comment]
Well, I'm unlucky then, because every feature I requested is only planned for v2. :/

**Comment by amrbashir** [comment]
We may have missed on backporting some features, get in touch with us on discord and we can discuss it if you feel some need to be backported
