### ISSUE TITLE
symbol lookup error | undefined symbol | libpthread.so.0

### ISSUE THREAD

**Issue by YasharSL** [tauri-apps/tauri#6624]
### Describe the bug

I have installed Tauri and was trying to use it with Nextjs. I faced this error when running `yarn tauri dev`
```
/home/.../src-tauri/target/debug/myapp: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE
error Command failed with exit code 127.
```

### Reproduction

1. Do all the steps written in the document's getting started section for Next.js
2. Run `yarn tauri dev`

### Expected behavior

See the app in dev mode

### Platform and versions

```text
Environment
  › OS: Ubuntu 22.04 X64
  › Node.js: 16.20.0
  › npm: 8.19.4
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.68.2
  › cargo: 1.68.2
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../out
  › devPath: http://localhost:3000/
  › framework: React (Next.js)
  › bundler: Webpack

App directory structure
  ├─ node_modules
  ├─ public
  ├─ styles
  ├─ src-tauri
  ├─ pages
  └─ .next
```

### Stack trace

```text
➜ yarn tauri dev
yarn run v1.22.19
$ tauri dev
     Running BeforeDevCommand (`npm run dev`)
        Info Watching /home/.../src-tauri for changes...
    Finished dev [unoptimized + debuginfo] target(s) in 0.57s

> myapp@0.1.0 dev
> next dev

/home/.../myapp/src-tauri/target/debug/myapp: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by YasharSL** [comment]
All the above have happened in the VSCode integrated terminal. I tried a separate terminal window and the error didn't show up

**Comment by d2weber** [comment]
I'm also encountering the same error. Seems to be related to VS code being installed via snap. [Here](https://stackoverflow.com/questions/75921414/java-symbol-lookup-error-snap-core20-current-lib-x86-64-linux-gnu-libpthread) a similar error is described. The `unset GTK_PATH` didn't help for me (but the error occurs later and the webview opens showing `WebKit encountered an internal error`).

**Comment by thewh1teagle** [comment]
Please reopen the issue. I experience the same bug in Linux with `wayland` with white window
It happens to me when I execute `cargo tauri dev` from vscode terminal

**Comment by marekchen** [comment]
same problem, run `cargo tarui dev` in vscode terminal.
