### ISSUE TITLE
[feat] expose `wait` and `try_wait` on ``CommandChild``

### ISSUE THREAD

**Issue by ImUrX** [tauri-apps/tauri#6634]
### Describe the problem

I need to wait for a process to finish and the only way to do it is with the methods provided by Rust.

### Describe the solution you'd like

Expose the functions from ``Child`` that let you do this

**Comment by Anujyadavg** [comment]
Hii

**Comment by Anujyadavg** [comment]
Hiii

**Comment by amrbashir** [comment]
So there is `Command::output` on the Rust side and `Command::execute` on the JS side which both will wait until the child is finished, is that not enough?

**Comment by ImUrX** [comment]
yeah thats a way to do it, but `try_wait` would be nice, and then if you have a `try_wait` why wouldnt you have a `wait`

**Comment by grzianod** [comment]
It is not enough for spawned processes that execute binaries that can run undefinitely and must be terminated with user-input (or signal/events such as screen recording tasks). It would be very nice to spawn the process, do something else and when necessary wait for the child process output. @amrbashir

**Comment by VanIseghemThomas** [comment]
+1 for this. I need this to check if a sidecar process unexpectedly closed. In that case the CommandChild object is still present. 
Specifically I'm bumping into a similar situation as @grzianod mentioned where my process is terminated/started on user input.
Being able to run `try_wait` on it would allow me to verify this.

**Comment by FabianLars** [comment]
superseeded by https://github.com/tauri-apps/plugins-workspace/issues/1920
