### ISSUE TITLE
[feat] theme customization for system tray

### ISSUE THREAD

**Issue by haroldallen** [tauri-apps/tauri#6645]
### Describe the problem

When you have a Tauri app that uses the System Tray, when you right click your icon it opens a context menu, if configured to.
This menu is **always light theme, regardless of OS theme** (on Windows 11, at least).
If you look at Electron apps like Discord or Figma, they have a dark theme context menu.

As far as I have seen (I've spent an hour looking), there is no current way to change the colors or theme of the system tray menu for Tauri.

### Describe the solution you'd like

I am not yet familiar with Rust myself, so I cannot propose a code solution.

If it is possible, I would like the option to change background and foreground colors of the system tray, on Windows at least - I imagine other OSs use their system's theme for that.

If that is not possible, I would like the option to switch between dark and light system tray theme, on Windows at least - see above.

If neither is possible, I wonder what workarounds would be possible, like spawning a frameless window where the user clicked with your styled options.

### Alternatives considered

Spawning a frameless window where the user clicked with your styled options - a horrible way to do it as it would be unreliable and very OS-specific.

**Comment by m4heshd** [comment]
I really hope Tauri v2 will have this feature implemented for [`tray-icon`](https://github.com/tauri-apps/tray-icon).

**Comment by amrbashir** [comment]
in v2, On Windows, tray icon menus will have auto dark mode, however it will not be implemented in `tray-icon`, since it needs to be done in the event loop creation of an app, it is implemented and managed by `tao`

if any `tray-icon` users need the dark-mode, you can see the implementation here https://github.com/tauri-apps/tao/blob/6df56c2dd1b0f4695dd40b70f75a22d1ba32c384/src/platform_impl/windows/dark_mode.rs#L63

**Comment by m4heshd** [comment]
@amrbashir Thank you for the clarification. Will https://github.com/tauri-apps/tao/pull/751 land in the next release of Tauri v1?

**Comment by amrbashir** [comment]
unlikely, as it is technically a breaking change so it will be part of v2 only

**Comment by m4heshd** [comment]
@amrbashir Understood. Looking forward to stable v2.

**Comment by ahqsoftwares** [comment]
Any workaround for v1 right now?

**Comment by kurdin** [comment]
@ahqsoftwares  @m4heshd 
As a workaround for v1 I use client system them detection with JS and set correct system tray icon with set_icon tauri command 

client code
```js

  import { useTheme } from 'next-themes'

  useEffect(() => {
    if (systemTheme) {
      invoke('set_icon', { name: 'main', isDark: systemTheme === 'dark' })
    }
  }, [systemTheme])
  ```

rust tauri set_icon command 
```rs
#[tauri::command]
fn set_icon(app_handle: tauri::AppHandle, name: &str, is_dark: bool) {
  match name {
    "notification" => {
      app_handle
        .tray_handle()
        .set_icon(if cfg!(windows) {
          if is_dark {
            tauri::Icon::Raw(include_bytes!("../icons/tray128x128-white-notification.png").to_vec())
          } else {
            tauri::Icon::Raw(include_bytes!("../icons/tray128x128-notification.png").to_vec())
          }
        } else {
          tauri::Icon::Raw(include_bytes!("../icons/tray128x128-notification.png").to_vec())
        })
        .unwrap();
    }
    _ => app_handle
      .tray_handle()
      .set_icon(if cfg!(windows) {
        if is_dark {
          tauri::Icon::Raw(include_bytes!("../icons/tray128x128-white.png").to_vec())
        } else {
          tauri::Icon::Raw(include_bytes!("../icons/tray128x128.png").to_vec())
        }
      } else {
        tauri::Icon::Raw(include_bytes!("../icons/tray128x128.png").to_vec())
      })
      .unwrap(),
  }
}
```

Hope this can help to anyone hitting the same problem on tauri v1
