### ISSUE TITLE
[bug] `tauri::SystemTrayMenuItemHandle`'s `set_selected` do not work under Gnome

### ISSUE THREAD

**Issue by Mr-Spade** [tauri-apps/tauri#6649]
### Describe the bug

I recently developed a cross-platform application using tauri, and I want to use the `set_selected` method of `tauri::SystemTrayMenuItemHandle` to display a checkmark or nothing before the menu item in the system tray. This works fine when used on Windows, but on Ubuntu 22.04, the menu item is never preceded by any icon, regardless of whether a checkmark should appear or not.

I don't know if this is due to some difficulty with gnome's setup for this. But based on my observation of gnome's system menu, I guess this should be possible.

Also, has this problem been fixed in the alpha version of tauri? Since there are many places in my application code that conflict with the update of the alpha version, I did not test the alpha version. I would be very grateful for some information on this issue!

### Platform and versions

```text
Environment
  › OS: Ubuntu 22.04 X64
  › Node.js: 18.15.0
  › npm: 9.5.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.68.2
  › cargo: 1.68.2
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,
```

**Comment by FabianLars** [comment]
Thanks for the report!

See here https://github.com/tauri-apps/tauri/issues/5360#issuecomment-1269760153 for an answer of a maintainer to the same question/bug report.
Afaik this is not yet part of v2 though since we're in the process of moving the tray and menu backend implementations.
