### ISSUE TITLE
[bug] No notification sound on Windows

### ISSUE THREAD

**Issue by Lej77** [tauri-apps/tauri#6652]
### Describe the bug

Notifications on Windows don't make any sound when shown. This is not the default and most other apps do make a sound when showing a notification.

### Reproduction

1. Show a [notification](https://docs.rs/tauri/1.2.4/tauri/api/notification/struct.Notification.html) on windows:
```rust
use tauri::api::notification::Notification;

Notification::new(&app.config().tauri.bundle.identifier)
    .title("New message")
    .body("You've got a new message.")
    .notify(app)
    .expect("failed to show notification");
```

### Expected behavior

A notification is shown and a sound is played.

### Platform and versions

```text
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 111.0.1661.62
  › MSVC: 
      - Visual Studio Community 2022
  › Node.js: 19.7.0
  › npm: 9.5.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.2
  › rustc: 1.68.2
  › cargo: 1.68.2
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
package.json not found

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ dist
  ├─ public
  ├─ src
  └─ src-tauri
```

### Additional context

tauri-apps/plugins-workspace#2144 might be relevant to this issue.

Tauri uses the `notify-rust` crate to handle notifications ([source](https://github.com/tauri-apps/tauri/discussions/6017#discussioncomment-4631129)). Its [`notify_rust::Notification::sound_name`](https://docs.rs/notify-rust/latest/x86_64-pc-windows-msvc/notify_rust/struct.Notification.html#method.sound_name) method allows specifying the sound name. The sound name is [later in its windows implementation](https://github.com/hoodie/notify-rust/blob/09abb2a41f97df4973a195ce971709d27f3de443/src/windows.rs#L8-L11) parsed using [`winrt_notification::Sound::from_str`](https://allenbenz.github.io/winrt-notification/0_5_0/winrt_notification/enum.Sound.html#method.from_str) which is derive using
[`strum::EnumString`](https://docs.rs/strum/0.24.1/strum/derive.EnumString.html). The derive macro's documentation says "Each variant of the enum will match on it’s own name". Which means we need to pass the string "Default" to get the default sound. Finally this enum is converted to the real audio tag in [`winrt_notification::Toast::sound`](https://allenbenz.github.io/winrt-notification/0_5_0/src/winrt_notification/lib.rs.html#243-253).

Note that setting the sound to `None` results in `<audio silent=\"true\" />` being appended to the "toast" xml in the `winrt-notification` crate while specifying the `Default` sound [appends an empty string](https://allenbenz.github.io/winrt-notification/0_5_0/src/winrt_notification/lib.rs.html#246).

Anyway, this all means that the issue can be solved by adding the following code:

```rust
#[cfg(windows)]
{
    notification.sound_name("Default");
}
```

In the [`tauri::api::notification::Notification::show`](https://docs.rs/tauri/1.2.4/src/tauri/api/notification.rs.html#98-137) method.

**Comment by amrbashir** [comment]
Nice finding, we would love to see a PR to fix this. Thanks
