### ISSUE TITLE
[bug] Invalid release JSON

### ISSUE THREAD

**Issue by Bialson** [tauri-apps/tauri#6656]
### Describe the bug

Currently I'm working on startup update mechanism in my Windows tauri app. I've created endpoint in my backend to get latest release from github releases and return JSON Static reposnse with release. My current JSON response looks like:
```json
{
    "version": "v0.6.0",
    "notes": "See the assets to download this version and install.",
    "pub_date": "2023-04-07T13:42:28Z",
    "platforms": {
        "windows-x86_64": {
            "signature":  "Content of app.msi.zip.sig",
            "url": "https://github.com/Bialson/repo/releases/download/v0.6.0/app.msi.zip"
        }
    }
}
```

I also added update mechanism in Rust:
```rust
  .setup(|app| {
    let handle = app.handle();
    tauri::async_runtime::spawn(async move {
      match tauri::updater::builder(handle).check().await {
        Ok(update) => {
          if update.is_update_available() {
            update.download_and_install().await.unwrap();
          }
        }
        Err(e) => {
          println!("failed to get update: {}", e);
        }
      }
    });
    Ok(())
  });
```

Updater content ``tauri.conf.json``:
```json
"updater": {
      "active": true,
      "endpoints": [
        "https://localhost:8080/update"
      ],
      "dialog": false,
      "pubkey": "pub_key",
}
```

The main problem is that Tauri tells, the release JSON is not valid. 
```bash
[2023-04-07][19:24:07][attohttpc][DEBUG] trying to connect to localhost:8080
[2023-04-07][19:24:07][attohttpc][DEBUG] trying to connect to [::1]:8080
[2023-04-07][19:24:07][attohttpc][DEBUG] successfully connected to [::1]:8080, took 1ms
failed to get update: Could not fetch a valid release JSON from the remote
```

Is there way to debug deeper this mechanism to check what's wrong with my JSON response? 

### Platform and versions

```text
yarn run v1.22.19
$ tauri info

Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 111.0.1661.62
  › MSVC: 
  › Node.js: 19.8.1
  › npm: 9.5.1
  › pnpm: 8.1.1
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.68.0
  › cargo: 1.68.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React
  › bundler: Vite

App directory structure
  ├─ .git
  ├─ .github
  ├─ backend
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

**Comment by FabianLars** [comment]
- Did you try printing it with `{:?}` instead of `{}`? That _sometimes_ gives a bit more output.
- Can you try it again after adding the `reqwest-client` feature flag to the tauri dependency in cargo.toml?
- Can you try http://localhost instead of https://localhost (will only work in debug mode)? Even though atto reports it successfully connected i think it may still have issues with the certificate 🤔

**Comment by Bialson** [comment]
> * Did you try printing it with `{:?}` instead of `{}`? That _sometimes_ gives a bit more output.
> * Can you try it again after adding the `reqwest-client` feature flag to the tauri dependency in cargo.toml?
> * Can you try http://localhost instead of https://localhost (will only work in debug mode)? Even though atto reports it successfully connected i think it may still have issues with the certificate 🤔

Thank you for response. After providing http endpoint to updater, Tauri said that endpoints must be https source. I founded that the problem was caused by backend https certificates, they weren't added to system certificates so Tauri cannot resolve untrusted certificate. After adding cert's to system, no problems so far. Also, tested with API deployment on Azure, also no issues.
