### ISSUE TITLE
[bug] dialog open doesnt show files without an extension

### ISSUE THREAD

**Issue by Disservin** [tauri-apps/tauri#6661]
### Describe the bug

First of all this might not be a bug at all though the behaviour is a bit weird.
When using
```js
const result = await open({
  filters: [{ name: "All Files", extensions: ["*", ""] }],
});
```
files without an extension are not shown. I know that the filter in this case doesnt make much sense because you are not filtering out anything but I would suspect it to behave the same as a simple
```js
const result = await open();
```

Question: on Windows i can only show executable files using "exe" as the extension, currently theres no way to achieve the same on posix systems since these lack the file extension, correct?

### Reproduction

```js
const result = await open({
  filters: [{ name: "All Files", extensions: ["*", ""] }],
});
```

### Expected behavior

Same behaviour as

```js
const result = await open();
```

### Platform and versions

```text
POSIX


> fast@0.0.0 tauri
> tauri info


Environment
  › OS: Ubuntu 20.04 X64
  › Node.js: 16.20.0
  › npm: 8.19.4
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.2
  › rustc: 1.68.2
  › cargo: 1.68.2
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › framework: Vue.js
  › bundler: Vite

App directory structure
  ├─ src-tauri
  ├─ .git
  ├─ src
  ├─ node_modules
  └─ public
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by FabianLars** [comment]
> Question: on Windows i can only show executable files using "exe" as the extension, currently theres no way to achieve the same on posix systems since these lack the file extension, correct?

Correct.

About the issue itself, the code of the [crate](https://github.com/PolyMeilex/rfd) we use doesn't seem to work nicely with empty or `*` extensions, but i'm not so sure if the os apis (or gtk in this case) can handle them any better 🤔 
If they do, the crate would need special handling for these, for example here i think https://github.com/PolyMeilex/rfd/blob/master/src/backend/gtk3/file_dialog/dialog_ffi.rs#L53

Edit: Or maybe we should just filter these special cases out in tauri so that rfd doesn't even see them 🤔 Or just document that it doesn't work idk.

**Comment by Disservin** [comment]
Im fine with just documenting it, though maybe it's already clear idk.
Nonetheless a way to only show files without extensions would be much appreciated.

Edit: or preferably only show executables, independent of OS which I imagine to take a bit more effort to implement
