### ISSUE TITLE
[feat] allow `stream media tag` featuring with webkit embeded http.

### ISSUE THREAD

**Issue by www159** [tauri-apps/tauri#6662]
### Describe the problem

I meet some trouble recently when resolve stream media request. for example, if I want to play 'mp4' from my server, there are steps:
1. download the whole 'mp4' from my server at backend.
2. transport the 'mp4' file(streaming or entire file) to frontend.

### Describe the solution you'd like

It may spend less time if allow webkit download stream media data itself.

**Comment by FabianLars** [comment]
Maybe i don't understand the issue, but can't you just set the url of the file in your backend as the `src` of the `audio` element?
