### ISSUE TITLE
[feat] Support for dragging files from Tauri window to filesystem

### ISSUE THREAD

**Issue by jamesWalker55** [tauri-apps/tauri#6664]
### Describe the problem

I'm implementing a file manager application, but I'm not sure if Tauri supports dragging files from the Tauri window to outside the window, e.g. onto File Explorer or the desktop?

I know Tauri currently supports dropping files onto the Tauri window, but I'm looking for the opposite - dropping files from Tauri onto the user system.

### Describe the solution you'd like

Implement dragging and dropping from the Tauri window onto the user system.

**Comment by FabianLars** [comment]
Thanks for the request! This is currently tracked in https://github.com/tauri-apps/tauri/issues/2593 :)
