### ISSUE TITLE
[feat] keep screen on

### ISSUE THREAD

**Issue by cencuansen** [tauri-apps/tauri#6672]
### Describe the problem

how keep android screen on?

### Describe the solution you'd like

I want Android to keep the screen on.

**Comment by FabianLars** [comment]
I feel like we should merge this with https://github.com/tauri-apps/tauri/issues/3697. Thanks for your request :)

**Comment by cencuansen** [comment]
it doesn't work on android.
same like: https://github.com/tauri-apps/tauri/issues/5947

**Comment by FabianLars** [comment]
Just ignore the plugin in that issue. I didn't mean to show you a solution or something, i was merely merging duplicate feature requests - the other one is still unresolved too.
