### ISSUE TITLE
Dialog open speed very slow

### ISSUE THREAD

**Issue by HuakunShen** [tauri-apps/tauri#6675]
### Discussed in https://github.com/tauri-apps/tauri/discussions/6666

<div type='discussions-op-text'>

<sup>Originally posted by **HuakunShen** April  8, 2023</sup>
I am building an app that requires reading file path. 

The tauri [dialog open api](https://tauri.app/v1/api/js/dialog/#open) works but took 2 seconds to open the window, which is unusal comparing to a normal browser.

It doesn't seem to be a problem with the frontend framework. I tried with both nuxt and sveltekit, and both opens slowly.

</div>

**Comment by skurovec** [comment]
I have same problem on macOS, invoked from React. In Safari opening file dialog is fast, in Tauri it takes about 2 seconds.

**Comment by HuakunShen** [comment]
> I have same problem on macOS, invoked from React. In Safari opening file dialog is fast, in Tauri it takes about 2 seconds.

I just tried the same app on ubuntu, it opens quickly. On MacOS it's slow. Haven't experimented on Windows yet.

**Comment by djeikyb** [comment]
I notice that the first time I use a file dialog in macos safari, it's very slow. The next couple uses are a lot faster, and then the dialog opens very fast. Same goes for macos firefox. When I repeatedly open a file dialog in a tauri app on macos, it stays consistently slow. I wonder if the dialog instance is intended to be reused?

**Comment by jeffreybos** [comment]
It seems that if you include a title that the dialog opens a lot faster. 

`open({
        directory: true,
        multiple: false,
        title: "Select a project", 
        defaultPath: await appDataDir(),
      })`

**Comment by HuakunShen** [comment]
> It seems that if you include a title that the dialog opens a lot faster.
> 
> `open({ directory: true, multiple: false, title: "Select a project", defaultPath: await appDataDir(), })`

This works perfectly for me. Thank you!

Not sure if we want to close this issue because this is kind of like a work around.

**Comment by djeikyb** [comment]
I figure an update to a doc somewhere would do the trick of closing! I'm not quite sure where as yet tho

**Comment by FabianLars** [comment]
to be honest i'd much rather have a fix for this than a doc update closing this issue. Worst case we'll just have to add a default title (on top of the doc update)?

**Comment by mcla118800** [comment]
Having the same issue. The title helps but still slow. I am also getting the CATransaction error with the opendialog call was wondering if these issues are related?

https://github.com/tauri-apps/plugins-workspace/issues/2147

**Comment by AskeyNil** [comment]
> It seems that if you include a title that the dialog opens a lot faster.
> 
> `open({ directory: true, multiple: false, title: "Select a project", defaultPath: await appDataDir(), })`

Use this method to fix the problem, but still prompt `+[CATransaction synchronize] called within transaction`

**Comment by jaaronkot** [comment]
> This works perfectly for me. Thank you!

This works perfectly for me. Thank you!
