### ISSUE TITLE
top-level Cargo.toml breaks bundler

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#67]
**Describe the bug**
If you have a `Cargo.toml` file above the `/src-tauri` folder, then bundler fails to copy to the right place. 

**Expected behavior**
The bundler should find the right folder and not bail.

**Screenshots**
```
Compiling tauri v1.0.0 (/[redacted]/ui/node_modules/@tauri-apps/tauri/lib/rust)
   Compiling app v0.1.0 (/[redacted]/ui/src-tauri)
    Finished release [optimized] target(s) in 21.01s
    Bundling app.app
error: Failed to copy binary from "/[redacted]/target/release/app"
  Caused by: "/[redacted]/target/release/app" does not exist
```
```
  copy_binary_to_bundle(&bundle_directory, settings)
    .chain_err(|| format!("Failed to copy binary from {:?}", settings.binary_path()))?;
```
```
let mut path = project_root_dir.join("target");
```

**Platform (please complete the following information):**
OS: MacOS, but probably all.

**Comment by tensor-programming** [comment]
Makes sense, the function was using relative paths as opposed to absolute paths. Will look into it.
