### ISSUE TITLE
[bug] Failed to load images resources code 403

### ISSUE THREAD

**Issue by regisx001** [tauri-apps/tauri#6703]
### Describe the bug

Hi there : 

I am a  beginner at using tauri , but I have a weird issue , that it i can't load images from urls .
i using tauri with sveltekit . the images loaded fine on the browser  but in tauri this issue come out in the dev mode . not the production and this makes the developement too hard .

![1](https://user-images.githubusercontent.com/98271602/231901599-59d97e61-93fd-4a55-bc23-b18efc8ac6dc.png)
![2](https://user-images.githubusercontent.com/98271602/231901598-69df7a30-c132-4df1-b486-1c13cbe7769a.png)
![3](https://user-images.githubusercontent.com/98271602/231901595-3e9fcfb1-51d1-4594-b677-48c20b0906fe.png)

### Reproduction

1.  create new svelte application : `pnpm create svelte`
2. change the adpater to static SSG  : `pnpm add -D @sveltejs/adapter-static@next`
3. init tauri app : `pnpm tauri init`
4. make a div and add a background image from  a URL on the internet 
5. run `pnpm tauri dev`

### Expected behavior

the image do not shows and the response come with code 403 
![1](https://user-images.githubusercontent.com/98271602/231902417-0c660b50-3e53-4b14-b6d1-fe4ded100be0.png)
![2](https://user-images.githubusercontent.com/98271602/231902416-e6f827cb-a708-4338-8698-e8ed5cae6ec4.png)
![3](https://user-images.githubusercontent.com/98271602/231902413-82f45a6b-861c-43cc-ae27-18a372a22fe7.png)

### Platform and versions

```text
Environment
  › OS: Pop!_OS 22.04 X64
  › Node.js: 18.12.1
  › npm: 8.19.2
  › pnpm: 8.2.0
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.68.2
  › cargo: 1.68.2
  › Rust toolchain: stable-x86_64-unknown-linux-gnu
```

**Comment by amrbashir** [comment]
This looks like an issue with the server/website (witanime), it is refusing to the serve the file to a webview probably. You can try another image from a different website (for example one of the screenshots you posted) and you will see that it work.
