### ISSUE TITLE
[bug] Installer creates 2 folders with identical names when installed in the desktop

### ISSUE THREAD

**Issue by jamesWalker55** [tauri-apps/tauri#6709]
### Describe the bug

On Windows, if you set the destination folder of the installer to a folder in the desktop, the installer creates 2 folders with the same name, and each folder separately contains the executable and the uninstaller.

### Reproduction

1. Create a tauri app following the quick start guide.
2. Build the tauri app and run the installer
3. In the installer, set the path to the current user's Desktop folder:
![image](https://user-images.githubusercontent.com/30405220/232168330-26d652cb-a8e2-42ec-a6cb-7e7a0365059d.png)
4. Install the application
5. Two folders with identical names appear in the desktop
![image](https://user-images.githubusercontent.com/30405220/232168411-e2c3bad8-aead-4557-b18f-09665b10e65e.png)

### Expected behavior

The installer doesn't create 2 identical folders on the desktop.

### Platform and versions

```text
> tauri-app@0.0.0 tauri
> tauri info


Environment
  › OS: Windows 10.0.19045 X64
  › Webview2: 112.0.1722.39
  › MSVC:
      - Visual Studio Build Tools 2022
      - Visual Studio Professional 2022
  › Node.js: 19.1.0
  › npm: 8.19.3
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.68.2
  › cargo: 1.68.2
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Vue.js
  › bundler: Vite

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by amrbashir** [comment]
@jamesWalker55 could you right click each folder, select "Properties" and post a screenshot of it here

**Comment by jamesWalker55** [comment]
@amrbashir Here's a screenshot, it seems the folders are in different Desktop folders
![image](https://user-images.githubusercontent.com/30405220/233095627-9b4a108b-555e-4123-be5f-d463703ca2bb.png)

**Comment by amrbashir** [comment]
As I expected, since the msi install is "per-machine", when you choose to install the app on your desktop which is a "user" directory, it will place the uninstaller in a "per-machine" directory which is `C:\Users\Public\Public Desktop`. I am not sure if I should consider this a bug since this is a logical behavior.

I should also note that we will be deprecating WiX and its msi installer and will move to NSIS starting v1.3 and this issue shouldn't exist in NSIS, although I might want to add this behavior as it makes more sense.

cc @lucasfernog @FabianLars

**Comment by jamesWalker55** [comment]
I'm not sure if this is logical behavior, shouldn't it put both the app and the uninstaller in either `Public/Desktop` or `User/Desktop`? When installing in any other location both are put into the same folder as expected. One user tried installing a tauri app on their desktop and was fairly confused by the two "identical" folders.

**Comment by FabianLars** [comment]
while i see where Amr is coming from (and i think he's correct), i agree that this is super awkward because it only happens if the app is installed into the Desktop dir while all other user dirs (like Documents) work fine.

**Comment by amrbashir** [comment]
I couldn't find any way to control this unfortunately and I don't really want to waste much time on it since we plan to deprecate it anyways and installing an app to the desktop is really not recommended.

I won't change NSIS behavior which doesn't have this issue.
