### ISSUE TITLE
[bug] resourceDir() return value has a strange prefix.

### ISSUE THREAD

**Issue by mycatgib** [tauri-apps/tauri#6714]
### Describe the bug

```tsx
import { resourceDir } from "@tauri-apps/api/path";

export default function App() {
  return (
    <>
      <button
        onClick={async () => {
          const result = await resourceDir();
          console.log(result);
        }}
      >
        Click
      </button>
    </>
  );
}
```

screenshot

![capture](https://user-images.githubusercontent.com/124885868/232278117-d4d50beb-a443-4e0a-8837-c34ce02aecc6.PNG)

### Reproduction

[tauri vite guide](https://tauri.app/v1/guides/getting-started/setup/vite)

### Expected behavior

When click button, 

Expected : C:\Users\me\Desktop\study\tauri-test\src-tauri\target\debug\\
Actual : \\\\?\C:\Users\me\Desktop\study\tauri-test\src-tauri\target\debug\

### Platform and versions

```text
Environment
  › OS: Windows 10.0.19045 X64
  › Webview2: 112.0.1722.39
  › MSVC: 
      - Visual Studio Community 2022
  › Node.js: 18.14.2
  › npm: 9.5.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.2
  › rustc: 1.68.2
  › cargo: 1.68.2
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › framework: React
  › bundler: Vite

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

**Comment by amrbashir** [comment]
This is not a bug it is just how paths work on Windows, see https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats . If you are familiar with node, you may think it is strange but Node.js choose to remove the prefix while we didin't but all Tauri APIs should work with this prefix just fine.

We have to keep this behavior for v1 but we will discuss removing it for v2.
