### ISSUE TITLE
[bug] Asynchronous #[tauri_command]s fail to compile with a borrowed value in the function constructor

### ISSUE THREAD

**Issue by IntegralPilot** [tauri-apps/tauri#6733]
### Describe the bug

When compiling async #[tauri_command]s, those with a borrowed value in the constructor such as &str fail to compile with a strange error that doesn't hint at this at all.

I'm not sure if this is how rust is meant to work, but I'm mainly writing this issue to see if 

- This can be fixed, so you can use &str in the constructor of async #[tauri_command]s
- If that's not possible, maybe a better error message, that addresses the issue can be generated (this would have saved me some time 😢 )
- If that's not possible, the [documentation](https://tauri.app/v1/guides/features/command/#async-commands) on the Tauri Website features a note about borrowed values, like &str being banned.

I'm unsure how to fix the error message, but I'm going to see if I can update the docs myself by submitting a PR?

*Edit: I have submitted the PR, which can be found here [https://github.com/tauri-apps/tauri-docs/pull/1214](https://github.com/tauri-apps/tauri-docs/pull/1214)*

### Reproduction

1. Create a new Tauri project, with any frontend, using the stable tauri and stable cargo/rustc.
2. In main.rs place this code:
``` 
#[tauri::command]
async fn test_function(borrowed_value_i_ruin_everything: &str) -> String {
    return format!("HELLO!")
}

fn main() {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![test_function])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
} 
```
3. The program will fail to compile when running `cargo tauri dev`, citing: 
```
error[E0597]: __tauri_message__ does not live long enough 
  --> src\main.rs:1:1
   |
29 | #[tauri::command]
   | ^^^^^^^^^^^^^^^^-
   | |               |
   | |               __tauri_message__ dropped here while still borrowed
   | borrowed value does not live long enough
   | argument requires that __tauri_message__ is borrowed for 'static
   |
  ::: src\main.rs:8:25
   |
9  |         .invoke_handler(tauri::generate_handler![test_function])
   |                         -------------------------------------------------- in this macro invocation
   |
   = note: this error originates in the macro __cmd__http_request which comes from the expansion of the macro tauri::generate_handler`(in Nightly builds, run with -Z macro-backtrace for more info)
```

### Expected behavior

Functions with a borrowed value in the constructor, like &str, compile fine, or maybe a more helpful error message is generated explaining borrowed constructors not being allowed, because the one at current suggests an issue with the Tauri Macro.

### Platform and versions

```text
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 112.0.1722.48
  › MSVC: 
  › Node.js: 16.17.0
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.2.0 (outdated, latest: 1.2.3)
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › framework: React

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

### Stack trace

```
error[E0597]: __tauri_message__ does not live long enough 
  --> src\main.rs:1:1
   |
29 | #[tauri::command]
   | ^^^^^^^^^^^^^^^^-
   | |               |
   | |               __tauri_message__ dropped here while still borrowed
   | borrowed value does not live long enough
   | argument requires that __tauri_message__ is borrowed for 'static
   |
  ::: src\main.rs:8:25
   |
9  |         .invoke_handler(tauri::generate_handler![test_function])
   |                         -------------------------------------------------- in this macro invocation
   |
   = note: this error originates in the macro __cmd__http_request which comes from the expansion of the macro tauri::generate_handler`(in Nightly builds, run with -Z macro-backtrace for more info)
```

### Additional context

Thank you for your time in reviewing this issue.

Also note that in the information section, I ran `cargo tauri info`, but it also outputted information about my NPM Tauri CLI installation, which is outdated as I no longer use it (in favour of the Cargo Tauri CLI, which was used to reproduce this bug).

Additionally, the information section states I don't have Visual Studio installed. This is untrue. I don't have a Visual Studio installed that contains the graphical editor, I have *Visual Studio Build Tools 2022*, enough to correctly compile rust code.

**Comment by IntegralPilot** [comment]
Okay, this is super weird but what happens is that you are not allowed to use values that have a type which starts with a & sign (meaning it is borrowed). I just tried changing it to a String from an &str and this fixes the issue. I'm going update my issue with this new information. 😄

**Comment by IntegralPilot** [comment]
Added pull request at the docs for now, to note how borrowed values are disallowed: [https://github.com/tauri-apps/tauri-docs/pull/1214](https://github.com/tauri-apps/tauri-docs/pull/1214)

**Still to be done**

*I'm not an expert in rust, so am quite unsure about how to do both of these, maybe someone can help? Thank you*

- [x] Fix it so borrowed values are allowed in constructors of async #[tauri:commands] (not sure where to start, a pointer might be helpful). _FIXED: you need to wrap in Result, it just how Rust works_
- [ ] If that's not possible, maybe include a better error message that explains how borrowed values aren't allowed. (again, unsure) _IN PROGRESS: PR #6124 fixes this (not authored by me), would be nice if it got merged_

Thank you!

**Comment by FabianLars** [comment]
Also related to https://github.com/tauri-apps/tauri/issues/2533. And this PR https://github.com/tauri-apps/tauri/pull/6124 will add a more helpful compiler error.

**Comment by IntegralPilot** [comment]
Thanks! Just read up on #2533 and appears issue also effects types without the obvious & symbol, and can be fixed by using a Result. Seems fair enough, so I'm going to tick off Task 1.

It would be soooooo good if #6124 could be merged, would have really saved a lot of time for me today! 😄 

Thanks for your time in investigating this.

**Comment by IntegralPilot** [comment]
Docs PR done! It is located at https://github.com/tauri-apps/tauri-docs/pull/1214

I've been fixing up formatting, pretting markdown, and I think I've created a pretty comprehensive guide about resolving the borrowing issue.

I'm not sure what the GitHub customs are, do I leave this issue open until #6124 gets merged or do I close it now? This PR resolves the issue.

Thanks to FabrianLars for their help.

**Comment by FabianLars** [comment]
> I'm not sure what the GitHub customs are, do I leave this issue open until https://github.com/tauri-apps/tauri/pull/6124 gets merged or do I close it now? This PR resolves the issue.

I'll link this issue in the PR so that it gets closed automatically when merged :)
