### ISSUE TITLE
Is the android version released yet?

### ISSUE THREAD

**Issue by xeoshow** [tauri-apps/tauri#6751]
### Describe the problem

Hello,

Just curious about the android version for tauri is released yet? Thanks a lot.

### Describe the solution you'd like

I would like to develop my android app using tauri, thanks a lot.

**Comment by FabianLars** [comment]
It's still in alpha. If that's enough for you, you can try it out already: https://next--tauri.netlify.app/next/mobile/ but again, it's alpha, so you should expect bugs, missing features, and incomplete docs.
