### ISSUE TITLE
[bug] Windows will be created with a blank space before the content is displayed on Win11

### ISSUE THREAD

**Issue by Pylogmon** [tauri-apps/tauri#6775]
### Describe the bug

When the window appears, there is a few seconds when the window content is blank before the window content is displayed normally. Even if I set `visible` to `false` and then wait for `DOMContentLoaded` before displaying the window, I still have this problem.

### Reproduction

1. pnpm create tauri-app
2. cd tauri-app
3. pnpm install
4. pnpm tauri dev
5. then you can see the window content is blank, then the normal content is displayed after

### Expected behavior

Show the contents of the window directly when it appears without a moment of blankness

### Platform and versions

```text
## pnpm run tauri info

> tauri-app@0.0.0 tauri D:\Dirs\Desktop\tauri-app
> tauri "info"


Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 112.0.1722.48
  › MSVC:
  › Node.js: 19.5.0
  › npm: 9.3.1
  › pnpm: 8.3.1
  › yarn: Not installed!
  › rustup: 1.25.2
  › rustc: 1.67.0
  › cargo: 1.67.0
  › Rust toolchain: stable-x86_64-pc-windows-gnu

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
```

### Additional context

It may seem like a small and insignificant problem, but when users use the software at night, even if the software is set to dark mode, this moment of blankness will make me go blind.

**Comment by FabianLars** [comment]
> Even if I set visible to false and then wait for DOMContentLoaded before displaying the window, I still have this problem.

Maybe DOMContentLoaded is too early and your frontend didn't load yet? This could especially be an issue if you use css-in-js styling. Is there a later point in time to show the window (in React i'd probably suggest an useEffect hook for when the component mounts)

**Comment by Pylogmon** [comment]
> in React i'd probably suggest an useEffect hook for when the component mounts

I tried this, but the problem still exists.

**Comment by Pylogmon** [comment]
Oh，Sorry, I should have recompiled it, it worked a little, But it is only an improvement, there is still a moment of blankness showing up.

**Comment by Pylogmon** [comment]
This is my current approach to multi-window implementation:
```javascript
const windowRouter = {
    "persistent": <Translator />,
    "translator": <Translator />,
    "popclip": <Translator />,
    "config": <Config />,
    "ocr": <Ocr />
}
const rootElement = document.getElementById("root");
        const root = ReactDOM.createRoot(rootElement);
        root.render(
            <React.StrictMode>
                <Provider store={configStore}>
                    <BrowserRouter>
                        {
                            windowRouter[appWindow.label]
                        }
                    </BrowserRouter>
                </Provider>
            </React.StrictMode>
        );
```

**Comment by Pylogmon** [comment]
Compared to the previous large blank has improved a lot, but according to the video, there will still be a moment of blank when the window appears.

https://user-images.githubusercontent.com/59004461/233964749-6b91cfec-fcc1-4f94-a291-359315706df2.mp4

**Comment by amrbashir** [comment]
Unfortunately we can't do much about this, it is just the webview takes some time to render, the only thing we can do is to maybe allow you to set the webview background color to something that matches your HTML background color so the white flash is less visible, see https://github.com/tauri-apps/tauri/issues/1564

**Comment by Pylogmon** [comment]
I found that in my multi-window application, if a window exists, even if this window is hide state, the next new window will not appear white blinking, I hope this information is useful for you.

**Comment by Pylogmon** [comment]
And under Windows, you need to check Maximize Minimize Animation in System - Advanced System Settings - Performance.

**Comment by amrbashir** [comment]
> I found that in my multi-window application, if a window exists, even if this window is hide state, the next new window will not appear white blinking, I hope this information is useful for you.

This probably (just speculating here) is because the web render engine has warmed up when rendered the first window.

Anyways, you can still notice this issues in maybe your browsers or electron-based apps, sometimes it is a white blink and sometimes it is black blink.

**Comment by Pylogmon** [comment]
I don't find such a problem in Linux, if the window is displayed while useeffect, there is no flicker, is this specific to webview2?

**Comment by amrbashir** [comment]
More like a chromium issue which webview2 uses under the hood.

**Comment by fanchenio** [comment]
> 更像是 webview2 在底层使用的 chromium 问题。

Is it possible to refer to electron's did-finish-load
