### ISSUE TITLE
hot update wanted

### ISSUE THREAD

**Issue by xdewx** [tauri-apps/tauri#6778]
### Describe the problem

does tauri support hot updates or not? such as downloading plug-ins from the application market and running them

### Describe the solution you'd like

does tauri support hot updates or not? such as downloading plug-ins from the application market and running them

**Comment by amrbashir** [comment]
It is out of tauri scope how you want to handle your app plugins, but you could use the asset protocol to load scripts on demand. ⚠️ Running arbitrary scripts is **dangerous. BE CAREFULL!!!** ⚠️

here is an example:
```js
let path = "path/to/plugin/script/file.js";
let file = convertFileSrc(path);

const script = document.createElement('script');
script.src = file;
script.async = true;

document.body.appendChild(script);
```

**Comment by xdewx** [comment]
> It is out of tauri scope how you want to handle your app plugins, but you could use the asset protocol to load scripts on demand. ⚠️ Running arbitrary scripts is **dangerous. BE CAREFULL!!!** ⚠️
> 
> here is an example:
> 
> ```js
> let path = "path/to/plugin/script/file.js";
> let file = convertFileSrc(path);
> 
> const script = document.createElement('script');
> script.src = file;
> script.async = true;
> 
> document.body.appendChild(script);
> ```

@amrbashir Hello, I tried with following your advice but I have another question:
1. `pnpm build`, got `dist` (whick includes index.html, index.xxx.css index.xxx.js)
2. create `iframe` at tauri and set `iframe.src=convertFileSrc(path/to/dist)`

the `index.html` at dist is loaded correctly, but `index.html` needs `/index.xxx.js` and `/index.xxx.css` which can't be loaded by `https://asset.localhost/index.xxx.css`

I tried:
1. set base=./ before vite build
2. set base=/path/to/dist before vite build
but they did not work. So, what should I do?

**Comment by amrbashir** [comment]
Please provide a minimal repro and I will take a look

**Comment by xdewx** [comment]
> Please provide a minimal repro and I will take a look

@amrbashir clone [https://github.com/4tst/tauri-plugins](https://github.com/4tst/tauri-plugins) and follow procedures in README.md. thanks

**Comment by amrbashir** [comment]
@xdewx So there is two issues: 
1. Looks like you hit this bug in WebView2 https://github.com/MicrosoftEdge/WebView2Feedback/issues/2341
2. all urls inside the plugin `index.html` have relative url like this one `<link rel="stylesheet" href="/assets/index-dce23ec6.css" />` and the request will be `https://asset.localhost/assets/index-dce23ec6.css` and our asset protocol won't find it because our implementation will see that `/assets/index-dce23ec6.css` is a relative path and will use the current working directory to resolve it. To solve this, you will need to write your own custom protocol that will resolve all requests relative to the plugin directory instead of the current working directory, see https://github.com/tauri-apps/tauri/blob/dev/examples/streaming/main.rs#L40 for a custom protocol example.

**Comment by xdewx** [comment]
> @xdewx So there is two issues:
> 
> 1. Looks like you hit this bug in WebView2 [Requests from content in <iframe> do not raise CoreWebView2OnWebResourceRequested MicrosoftEdge/WebView2Feedback#2341](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2341)
> 2. all urls inside the plugin `index.html` have relative url like this one `<link rel="stylesheet" href="/assets/index-dce23ec6.css" />` and the request will be `https://asset.localhost/assets/index-dce23ec6.css` and our asset protocol won't find it because our implementation will see that `/assets/index-dce23ec6.css` is a relative path and will use the current working directory to resolve it. To solve this, you will need to write your own custom protocol that will resolve all requests relative to the plugin directory instead of the current working directory, see https://github.com/tauri-apps/tauri/blob/dev/examples/streaming/main.rs#L40 for a custom protocol example.

@amrbashir following your advice, I added plugin protocol, but requests from index.html can't be intercepted by tauri. error is:
```
GET https://plugin.localhost/dist/assets/index-64c72709.css net::ERR_CONNECTION_REFUSED
index.html:8 
GET https://plugin.localhost/dist/assets/index-0a6aebaa.js net::ERR_CONNECTION_REFUSED
```

```rust
.register_uri_scheme_protocol("plugin", move |_app, request| {
  let path = request
      .uri()
      .strip_prefix("plugin://localhost/")
      .unwrap()
      .replace("%5C", "/");
  let dir=app_data_dir(tauri::generate_context!().config()).unwrap();
  let paths = [
      dir.to_str().unwrap(),
      "plugins",
      path.as_str(),
  ];
  let file = paths.join("/");
  println!("{} {} {}", request.uri(), String::from(path).as_str(), file);
  
  // default status code
  let mut status_code = 200;
  let mut body = Vec::new();
  if Path::new(&file).exists() {
      let mut content = std::fs::File::open(file)?;
      content.read_to_end(&mut body).unwrap();
  } else {
      status_code = 404;
  }
  
  let mut response = ResponseBuilder::new();
  // mimetype("video/mp4").
  response.status(status_code).body(body)
  })
```

**Comment by amrbashir** [comment]
> following your advice, I added plugin protocol, but requests from index.html can't be intercepted by tauri. error is:

This error is because of the bug in WebView2 I mentioned https://github.com/MicrosoftEdge/WebView2Feedback/issues/2341

**Comment by xdewx** [comment]
> > following your advice, I added plugin protocol, but requests from index.html can't be intercepted by tauri. error is:
> 
> This error is because of the bug in WebView2 I mentioned https://github.com/MicrosoftEdge/WebView2Feedback/issues/2341

I see. Thank u very much.
