### ISSUE TITLE
[lib] block in Cargo.toml not detected when compiling for Android

### ISSUE THREAD

**Issue by luisfi-dev** [tauri-apps/tauri#6787]
Repo: https://github.com/LuisFerLCC/tauri-testbench-public

Running `cargo tauri android dev` from the `unstable` branch (where I previously generated the Android project) throws the following error after compiling:

```
Error Library artifact not found at (project root)/src-tauri/target/aarch64-linux-android/debug/libtauri-testbench.so. Make sure your Cargo.toml file has a [lib] block with `crate-type = ["staticlib", "cdylib", "rlib"]`
```

But my Cargo.toml _does_ have the requested `[lib]` block. I get this error both on Windows and WSL.

**Comment by amrbashir** [comment]
Your project is using older versions, please try recreating the project with updated dependencies and make sure to use the latest CLI.

**Comment by luisfi-dev** [comment]
Updated the Tauri CLI (`cargo install tauri-cli --version "^2.0.0-alpha"`) and all dependencies on both `package.json` and `src-tauri/Cargo.toml`. Still not working. I pushed my changes to the same repo.

**Comment by amrbashir** [comment]
until the next tauri-cli release, you can just add a `name ="whatever-name-you-want"` under `[lib]` block.

**Comment by luisfi-dev** [comment]
> until the next tauri-cli release, you can just add a `name ="whatever-name-you-want"` under `[lib]` block.

Solved! Thanks!
