### ISSUE TITLE
[bug] Cannot create small window (with approximately 100 width or less)

### ISSUE THREAD

**Issue by cpfy** [tauri-apps/tauri#6792]
### Describe the bug

When I specified a smaller window size, the window size generated by tauri was not as expected due to windows native titlebar.

### Reproduction

with following settings in `tauri.conf.json`

```json
"windows": [
      {
        "label": "xxx",
        "width": 20,
        "height": 20,
        "alwaysOnTop": true
      }
]
```
Then I get:

![image](https://user-images.githubusercontent.com/30110832/234290056-1d6841b1-19c1-478b-8a55-98ba9fdee6d0.png)

You can see that the width is much larger than the value I set (20).

### Expected behavior

windows size matches my settings.

### Platform and versions

```text
› OS: Windows 10.0.19044 X64
  › Webview2: 112.0.1722.58
  › MSVC:
  › Node.js: 16.13.0
  › npm: 8.1.3
  › pnpm: 8.3.1
  › rustup: 1.25.2
  › rustc: 1.69.0
  › cargo: 1.69.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc
```

**Comment by amrbashir** [comment]
You can disable the decorations using https://tauri.app/v1/api/config#windowconfig.decorations, otherwise you are stuck with the native title bar which has a fixed size.

**Comment by cpfy** [comment]
Actually, I had set `"decorations": false`, but the problem still exists, the width of the window is always larger than the value I set. The problem is only solved when the window is larger than a certain value (e.g. 150x150)

**window size 20x20**

`"decorations": true`
![image](https://user-images.githubusercontent.com/30110832/234448949-d8829f1f-a6ee-4f2d-9b04-197fb3f853c8.png)

`"decorations": false`
![image](https://user-images.githubusercontent.com/30110832/234448283-6e0b0856-b8b8-4c8a-ba82-a0c605fed3ff.png)

**window size 150x150**

`"decorations": true`
![image](https://user-images.githubusercontent.com/30110832/234451609-2b49c850-6ef8-45d2-9509-7d6f07c6ab9c.png)

`"decorations": false`
![image](https://user-images.githubusercontent.com/30110832/234451875-72c19ebc-25f8-4f8b-8ed9-39da454b4cb0.png)


I guess the decorations setting just hides the borders and bars, but in fact the conflict with native title bar is still there, just as it was when the decorations were displayed

**Comment by amrbashir** [comment]
@cpfy 

Could you tell me what is your use-case, just want to see if you can use the current API?

I found a way to allow smaller window size but it has limitations unfortunately with transparency like this weird border appearing when alt+tabbing into the window

![image](https://user-images.githubusercontent.com/48618675/234665431-62c53616-8638-4afe-84bb-3f543a607f9e.png)

This weird border exists when first creating a 2px window which will apear like this
![image](https://user-images.githubusercontent.com/48618675/234666262-7b5f6c21-4a94-435a-88ba-7bd8f33945c2.png)

and sometimes you'd get something like this 
![image](https://user-images.githubusercontent.com/48618675/234666492-9110470b-daf3-45e8-a04f-572e9bf555ec.png)

**Comment by cpfy** [comment]
@amrbashir

Sorry for the late reply~

I would like to create a floating bubble on the desktop. It can be dragged, clicked to interact, and display specified content. This requirement is more like what was mentioned in issues #4360, #6125. But I have been unable to set the window to a suitable size.

Would you have any suggestions on how to implement this feature? Thank you!

(p.s. the bubble would look like this:

![](https://github.com/zhongyang219/TrafficMonitor/raw/master/Screenshots/en_us/main1.png)

**Comment by amrbashir** [comment]
for your use-case (as shown in your screenshot), I think our minimum size on Windows with `decorations: false` is good enough, as for Linux and #6125, this is a bug with `resizable` option on Linux (especially Gnome Desktop Environment), see https://github.com/tauri-apps/tao/issues/561

**Comment by Neo110** [comment]
i get it ，use winit .
<img width="264" alt="image" src="https://github.com/tauri-apps/tauri/assets/12504669/c513c574-4e4a-4a0c-833f-f3399eefca7f">
