### ISSUE TITLE
Reevaluate updater.rs

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#68]
**Describe the bug**
I noticed that the `updater.rs` seems to be a bad actor - and maybe its just on MacOS, but we really need to look into it and get it back in shape. In order to complete a build I needed to remove that bin (see below).

This is obviously only a stopgap fix - we need to address the underlying issue.

**To Fix**
remove this:
```
[[bin]]
name = "updater"
path = "src/updater.rs"
```
from your `src-tauri/Cargo.toml` file.

**Comment by lucasfernog** [comment]
Also, the updater isn't finished, and we need to take a really good look at it. Maybe put it on the roadmap for next month or Q1 20020.

**Comment by nothingismagick** [comment]
let's put it on Q1-2020

**Comment by tensor-programming** [comment]
I agree, was seeing problem with it from before. From what the code shows, might only work on linux atm.

**Comment by nothingismagick** [comment]
@carbotaniuman - would love it if you could recon with @lucasfernog and @tensor-programming and figure out what we have to do here.

**Comment by lucasfernog** [comment]
#643
