### ISSUE TITLE
[bug] : Module parse failed for loader

### ISSUE THREAD

**Issue by ezno12** [tauri-apps/tauri#6806]
### Describe the bug

I'm working on code base react, node, electron. my objective to migrate the project to tauri. when I work with fs tauri api i faced problem of processing loader.
 
This the bug I had: 
![tauri](https://user-images.githubusercontent.com/39200164/234811949-6248f678-13d0-4b03-944f-a6b6a01a0aa4.PNG)

This ts Config file:
![tsconfig](https://user-images.githubusercontent.com/39200164/234813385-4bcf5c8a-9401-4f22-9c10-6c9c1fef481d.PNG)

This Tauri config file:
![tauri config](https://user-images.githubusercontent.com/39200164/234813439-4da63522-24e0-4401-aeb9-e7e1d53fb534.PNG)

### Reproduction

1. installed all prerequest of tauri
2. Added tauri api package
3. yarn tauri dev
4. add import statement import { BaseDirectory, exists } from "@tauri-apps/api/fs"
5. add code to check image exsits in picture windows folder : await exists("avatar.png", { dir: BaseDirectory.Picture })

### Expected behavior

to return Promise<boolean> as tauri documentation said.

### Platform and versions

```text
Environment
  › OS: Windows 10.0.19045 X64
  › Webview2: 112.0.1722.58
  › MSVC:
      - Visual Studio Build Tools 2022
  › Node.js: 14.18.3
  › npm: 6.14.15
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.69.0
  › cargo: 1.69.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ .git
  ├─ .husky
  ├─ .vscode
  ├─ electron
  ├─ node_modules
  ├─ public
  ├─ scripts
  ├─ src
  └─ src-tauri
```

**Comment by FabianLars** [comment]
Moved to discussion: #6808
