### ISSUE TITLE
[feat] How to Run Tauri's Application in Root Mode

### ISSUE THREAD

**Issue by zzpp515630** [tauri-apps/tauri#6807]
### Describe the problem

Excuse me, if you use the deb package compiled by tauri to run in ubuntu, it can be opened like GParted after installation, and you will be prompted to run with root privileges. Then, enter the password and run the program. Open in non command-line mode.

### Describe the solution you'd like

Requires sudo to run

**Comment by amrbashir** [comment]
Not sure what you want to be honest, could you explain more please? Do you want to forbid using your app unless it is opened using `sudo` from command line?

**Comment by zzpp515630** [comment]
Sorry, I asked the question through translation software, maybe the translation is wrong. . . .
I imagine something like GParted software. Open it under a normal account, it prompts that it needs to run with root privileges, and then enter the root password to run my software. Because my software needs root privileges to access resources

**Comment by zzpp515630** [comment]
For example:pkexec my application。My application requires root access to system resources. Want to start and access through a desktop shortcut. Applied to deb packaging method

**Comment by zzpp515630** [comment]
The current solution is to modify desktop shortcuts, but this is not the final solution。
example：
[Desktop Entry]
Categories=
Comment=.......
Exec=sudo /usr/bin/my-application
Icon=application-icon
Name=application-name
Terminal=true
Type=Application

**Comment by amrbashir** [comment]
- For modifying the desktop file, see https://github.com/tauri-apps/tauri/issues/5176
- For requesting sudo access on demand in the gui, you need to use `pkexec` to open another process of your app that will have root then close the first instance or something similar see https://bbs.archlinux.org/viewtopic.php?pid=999328#p999328
- or request your users to run the app using `sudo`

For more info see https://wiki.archlinux.org/title/Running_GUI_applications_as_root

**Comment by zzpp515630** [comment]
Thanks...

**Comment by cosoc** [comment]
> When developing some applications that require administrator privileges, we need root to run the software in our development environment. This is how I do it

> The purpose is to let the sudo command maintain the current environment variables

 ```shll
sudo -E env PATH=$PATH  yarn run tauri dev
```

**Comment by xueweiwujxw** [comment]
This is my solution
```
[Desktop Entry]
Categories={{{categories}}}
{{#if comment}}
Comment={{{comment}}}
{{/if}}
Exec=pkexec env DISPLAY=$(w | grep $(whoami) | awk '{print $3}') XAUTHORITY=/run/user/$(id -u)/gdm/Xauthority {{{exec}}}
Icon={{{icon}}}
Name={{{name}}}
Terminal=false
Type=Application
```
with tauri.config.json
```json
      "deb": {
        "depends": [],
        "desktopTemplate": "./templates/main.desktop"
      }
```
It works on Ubuntu 20.04

**Comment by xueweiwujxw** [comment]
This is my solution
```
[Desktop Entry]
Categories={{{categories}}}
{{#if comment}}
Comment={{{comment}}}
{{/if}}
Exec=sh -c "pkexec env DISPLAY=$(w | grep $(whoami) | awk '{print $3}') XAUTHORITY=/run/user/$(id -u)/gdm/Xauthority {{{exec}}}"
Icon={{{icon}}}
Name={{{name}}}
Terminal=false
Type=Application
```
with tauri.config.json
```json
      "deb": {
        "depends": [],
        "desktopTemplate": "./templates/main.desktop"
      }
```
It works on Ubuntu 20.04
