### ISSUE TITLE
Fetch API hangs infinitely when fetching APNG images

### ISSUE THREAD

**Issue by Tormak9970** [tauri-apps/tauri#6819]
### Describe the bug

When attempting to fetch an APNG image with proper cors rules, the app hangs after 10-20 seconds.

### Reproduction

Go to [this reproduction](https://github.com/Tormak9970/tauri-app-detch-freeze-reproduction).
Clone repository.
Click the "Test Broken Fetch" button.
A message saying "Starting Problematic Image Download..." will be logged in the debug window.
After a few seconds, the app will hang.

### Expected behavior

For the reproduction, the APNG should be written to `DESKTOP_DIR/app-freeze-download-test.png`, but the request never finishes.

### Platform and versions

```text
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 112.0.1722.64
  › MSVC: 
      - Visual Studio Community 2022
      - Visual Studio Build Tools 2017
      - Visual Studio Build Tools 2019
  › Node.js: 16.16.0
  › npm: 8.19.2
  › pnpm: 7.11.0
  › yarn: Not installed!
  › rustup: 1.25.2
  › rustc: 1.67.0
  › cargo: 1.67.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Svelte
  › bundler: Vite

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

### Stack trace

```text
No errors.
```

**Comment by amrbashir** [comment]
Enable the `reqwest-client` feature flag in `src-tauri/Cargo.toml` and it should work just fine. The default http client `attohttpc` doesn't seem to handle this download correctly. Anyways, in v2, `attohttpc` have been removed and `reqwest` will be the default.

**Comment by FabianLars** [comment]
I'm a bit confused by the thumbsup emoji since i already asked this on [discord](https://discord.com/channels/616186924390023171/1101554156638052382/1102601693335650416). @Tormak9970 can you confirm whether it works for you or not again please? 😅

**Comment by Tormak9970** [comment]
> I'm a bit confused by the thumbsup emoji since i already asked this on [discord](https://discord.com/channels/616186924390023171/1101554156638052382/1102601693335650416). @Tormak9970 can you confirm whether it works for you or not again please? 😅 

Sorry, I realize in hindset that was unclear. Added that bc I'm gonna try that suggestion again in case I messed something up before

**Comment by Tormak9970** [comment]
Retested. @amrbashir's suggestion does not fix the issue. It still causes the app to hang

**Comment by amrbashir** [comment]
I still can't reproduce. 

When using the default http client, it does successfully download the file then hangs afterwards but after using the `reqwest-client`, it doesn't hang and I can download the image multiple times.

**Comment by Tormak9970** [comment]
> I still can't reproduce. 
> 
> When using the default http client, it does successfully download the file then hangs afterwards but after using the `reqwest-client`, it doesn't hang and I can download the image multiple times.

Hmm. I'll check it with the reproductionz been testing with the application I initially ran into the issue with. Even with the reproduction I never got the file to download
