### ISSUE TITLE
[bug] Tauri updater doesn't work after compiling through GitHub actions

### ISSUE THREAD

**Issue by spectraldoy** [tauri-apps/tauri#6821]
### Describe the bug

I am currently trying to set up an updater for my Tauri app. I'm building and releasing my app through GitHub actions, using the https://github.com/tauri-apps/tauri-action. My workflow uses `tauri-apps/tauri-action@dev`. I've been trying to release debug versions, not release versions, so that any bugs that my users find can be more easily debugged.

Using the GitHub action, the `latest.json` file is created. I am using this as the endpoint for my updater. I am also using `dialog: true` in `tauri.conf.json`, i.e., I'm using the out-of-the-box updater dialog provided by Tauri. When I run `tauri dev` locally (I'm using `pnpm`, so `pnpm tauri dev`), or even when I build the app locally, either for release or debug, using `tauri build` (or `pnpm tauri build`), the updater works. The dialog pops up whenever I open the app if a newer version is available as per the `latest.json` file, and the dialog asks me to update the app. I can then update it, and it installs and restarts perfectly, installing the new version of the app.

I also confirmed that I can build the app locally on either windows or macOS machines and have the updater work, but it still doesn't work through GitHub actions.

However, if the app that is compiled and released through GitHub actions does not seem to be able to do this. Even though it's the exact same code, no dialog pops up at all when I open the app downloaded from my GitHub release, which was created with the Tauri action.

Thank you.

### Reproduction

1. Write a Tauri app
2. Configure the Tauri updater
3. Configure GitHub actions to build and release the app to a GitHub release
4. Make sure the Tauri updater has the `latest.json` file from the latest release of your repo as an endpoint
5. Release some version of the app through the GitHub actions workflow that uses `tauri-apps/tauri-action` to build and release the app. Download the app from the GitHub release. 
6. Release a new version of the app (change the version numbers in `package.json`, `src-tauri/tauri.conf.json` and `src-tauri/Cargo.toml` and then run the GitHub actions workflow to publish the app again)
7. Open the version downloaded from step 5 and check if the updater dialog shows up, and if it does, check if it works

### Expected behavior

The Tauri updater should work not just from locally built versions of the app, but from versions built and released through GitHub actions.

### Platform and versions

```text
Note: There is some other issue here where `pnpm tauri info` doesn't work. From reading other issues, I think this might be solved in Tauri 2.0.0, but for Tauri 1.2.3, it doesn't work, and I don't want to potentially break things by installing a newer version of Tauri.

Environment
  › OS: Mac OS 12.6.3 X64
  › Node.js: 18.1.0
  › npm: 8.10.0
  › pnpm: 7.30.3
  › yarn: 1.22.10
  › rustup: 1.25.2
  › rustc: 1.68.0
  › cargo: 1.68.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected character 't' while parsing major version number")', src/info.rs:566:67
stack backtrace:
   0:        0x11e56fbe7 - _napi_register_module_v1
   1:        0x11e0b119a - <unknown>
   2:        0x11e5402ec - _napi_register_module_v1
   3:        0x11e5753ca - _napi_register_module_v1
   4:        0x11e574ff6 - _napi_register_module_v1
   5:        0x11e574ce3 - _napi_register_module_v1
   6:        0x11e575d91 - _napi_register_module_v1
   7:        0x11e575b34 - _napi_register_module_v1
   8:        0x11e575a98 - _napi_register_module_v1
   9:        0x11e575a62 - _napi_register_module_v1
  10:        0x11e99db43 - _napi_register_module_v1
  11:        0x11e99ddc5 - _napi_register_module_v1
  12:        0x11e756897 - _napi_register_module_v1
  13:        0x11e74e5e8 - _napi_register_module_v1
  14:        0x11e8552ae - _napi_register_module_v1
  15:        0x11e85d8f9 - _napi_register_module_v1
  16:        0x11e84f48e - _napi_register_module_v1
  17:        0x11e57918a - _napi_register_module_v1
  18:     0x7ff80a8cc4e1 - __pthread_start
```

**Comment by FabianLars** [comment]
Let's keep the discussion in the tauri-action repo for now :)

thanks for such an extensive report btw!
