### ISSUE TITLE
[feat] support for default system browser

### ISSUE THREAD

**Issue by DanavsSite** [tauri-apps/tauri#6825]
### Describe the problem

when i was building my app i ran into a problem.it was not on my part it just didnt work with my browser.i tried searching for docs for this but found nothing.

### Describe the solution you'd like

a boolean called useSysBrowser should be added to tauri.conf.json or idk

**Comment by FabianLars** [comment]
Tauri can't work, and is not supposed to work, with a normal browser in full capacity.

That said, if you just want to expose your frontend to the browser you can check out https://github.com/tauri-apps/tauri-plugin-localhost/ and if you want some `invoke` calls to also work you may be able to use https://github.com/tauri-apps/tauri-invoke-http/ on top.

Other than that, this is out of scope for Tauri, thank you :)
