### ISSUE TITLE
[bug]: `shell.open` doesn't detach the launched process 

### ISSUE THREAD

**Issue by Uzaaft** [tauri-apps/tauri#6849]
### Describe the problem

First and foremost: This might not be an issue with the API of Tauri, but rather how I used the API. But I've looked at the docs, and can't seem to solve this with the current API being provided, so that's why I'm opening this feature request.

I find the current method, where we use the [shell](https://tauri.app/v1/api/js/shell/) api in Tauri to open files etc lacking in several areas:
1. It has to match against a regex
2. As soon as the program is exited, the children spawned are also closed(reported by a coworker).

### Describe the solution you'd like

I'm proposing creating a new command, under the fs API, where we can open a file with the default System app, instead of the current method that's in the docs, which matches to a [regex pattern](https://tauri.app/v1/api/js/shell/#open). Something with an API like:

```ts
openWithDefault(path: String): Promise<void>
```

With no matching against a regex. We simply use the default system app. 

### Additional context

If the maintainers of Tauri is open to the idea, I'd like to implement it myself to get the practice and experience.

**Comment by amrbashir** [comment]
> It has to match against a regex

You could specify `.*` as the regex to allow everything but that is really **dangerous**:exclamation: and not recommended at all. Be careful to not expose your users system. 

> With no matching against a regex. We simply use the default system app.

The regex is only validating the path/url to be opened not the app to open with.

> As soon as the program is exited, the children spawned are also closed(reported by a coworker).

Yeah this is definitely a bug that needs to be addressed upstream in `open-rs` crate, I will see what I can do

**Comment by amrbashir** [comment]
> If the maintainers of Tauri is open to the idea, I'd like to implement it myself to get the practice and experience.

Please go ahead and get in touch with us on Discord if you need any help or directions.

**Comment by amrbashir** [comment]
@Uzaaft could you post your `tauri info`? As far as I can tell, the launched process is detached on Windows and Unix, what is your OS?

**Comment by amrbashir** [comment]
this will be fixed in the shell plugin for v2
