### ISSUE TITLE
[bug] Spinny-hang when ask to start maximized after upgrading to 1.3

### ISSUE THREAD

**Issue by djeikyb** [tauri-apps/tauri#6851]
### Describe the bug

After updating from 1.2 to 1.3, the app window hangs and the cursor goes spinny. In 1.2, the app window starts just fine, and maximized, according to the config.

I started [a fresh tauri+vue project to reproduce](https://github.com/djeikyb/tauri-maximized-repro) in case I've botched something. I tried to make a commit after each step I took, starting with the `yarn create tauri-app`.

<img width="841" alt="image" src="https://user-images.githubusercontent.com/794743/236066535-1fab9a36-8873-4f43-9ab3-2a1be3c4229b.png">

### Reproduction

I'm on an m1 macbook, macos 13.3.1 (22E261).

Repro repo: https://github.com/djeikyb/tauri-maximized-repro

### Expected behavior

App should start with a maximized window.

### Platform and versions

```text
❯ cargo tauri info

Environment
  › OS: Mac OS 13.3.1 X64
  › Node.js: 16.14.2
  › npm: 8.5.0
  › pnpm: 4.12.1
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.68.2
  › cargo: 1.68.1
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.3.0
  › tauri [RUST]: 1.3.0,
  › tauri-build [RUST]: 1.3.0,
  › tao [RUST]: 0.16.0,
  › wry [RUST]: 0.24.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Vue.js
  › bundler: Vite

App directory structure
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  ├─ .idea
  └─ src
```

### Stack trace

Unfortunately it doesn't crash, just hangs forever.

**Comment by wusyong** [comment]
This is because of https://github.com/tauri-apps/tao/pull/662
We have a lock when retrieving fullscreen transition state.
We'll need to find other way to detect it.
Latest tao also has this issue, and hence tauri v2 also has it.

**Comment by wusyong** [comment]
@amrbashir I think we need to revert the change and reopen https://github.com/tauri-apps/tauri/issues/4519
Defining another field in window delegate isn't ideal and it could create data race.

**Comment by roniemartinez** [comment]
I have the same issue.

![image](https://user-images.githubusercontent.com/2573537/236620801-0628e822-4f2f-423e-ac84-1ea94c3cf960.png)

```
[✔] Environment
    - OS: Mac OS 13.3.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.16.0
    - yarn: 1.22.19
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.1
    - tao [RUST]: 0.16.0
    - @tauri-apps/api [NPM]: 1.3.0
    - @tauri-apps/cli [NPM]: 1.3.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by wusyong** [comment]
I pushed a few patched for dependencies. Could you run `cargo update` and try again?

**Comment by roniemartinez** [comment]
@wusyong Now I am getting a different error which prevents compiling.

```
yarn run v1.22.19
$ tauri dev
     Running BeforeDevCommand (`yarn dev`)
$ vite

  VITE v4.3.4  ready in 1008 ms

  ➜  Local:   http://localhost:1420/
  ➜  Network: use --host to expose
        Info Watching /Users/user/Projects/pulsars/src-tauri for changes...
   Compiling tauri-runtime v0.13.0
   Compiling tauri-build v1.3.0
   Compiling tauri-codegen v1.3.0
   Compiling wry v0.24.2
   Compiling sha2 v0.10.6
   Compiling zip v0.6.4
error[E0583]: file not found for module `web_context`
 --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wry-0.24.2/src/webview/wkwebview/mod.rs:8:1
  |
8 | mod web_context;
  | ^^^^^^^^^^^^^^^^
  |
  = help: to create the module `web_context`, create file "/Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wry-0.24.2/src/webview/wkwebview/web_context.rs" or "/Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wry-0.24.2/src/webview/wkwebview/web_context/mod.rs"

For more information about this error, try `rustc --explain E0583`.
error: could not compile `wry` due to previous error
warning: build failed, waiting for other jobs to finish...

error Command failed with exit code 101.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by wusyong** [comment]
Sorry about that, I just published a patch to fix it. Can you run the step again to test?

**Comment by djeikyb** [comment]
Updates let 1.3 work as expected in both my repro sample and actual app. Thanks!

**Comment by roniemartinez** [comment]
@wusyong It is working. Thank you!
