### ISSUE TITLE
[feat] Add Spanish to the available languages (Windows NSIS)

### ISSUE THREAD

**Issue by luisfi-dev** [tauri-apps/tauri#6852]
### Describe the problem

Spanish is one of the listed languages on https://github.com/kichik/nsis/tree/9465c08046f00ccb6eda985abbdbf52c275c6c4d/Contrib/Language%20files, yet it doesn't seem to be available for the Tauri NSIS bundle. Large-scale applications made with Tauri may need to have Spanish as an available language on the installer.

```
Error failed to bundle project: Language Spanish not implemented. If it is a valid language listed on
<https://github.com/kichik/nsis/tree/9465c08046f00ccb6eda985abbdbf52c275c6c4d/Contrib/Language%20files>, please open a
Tauri feature request
```

### Describe the solution you'd like

Spanish should be added to the list of available languages for the Windows installer. The language files are available on https://github.com/kichik/nsis/tree/9465c08046f00ccb6eda985abbdbf52c275c6c4d/Contrib/Language%20files.

**Comment by FabianLars** [comment]
Sooo, we hoped it would just show incomplete translations instead of straight up failing but okay :/

Also, for a language to be actually supported we need someone from the community that speaks the requested language to translate Tauri specific strings: https://github.com/tauri-apps/tauri/tree/dev/tooling/bundler/src/bundle/windows/templates/nsis-languages

**Comment by luisfi-dev** [comment]
> Also, for a language to be actually supported we need someone from the community that speaks the requested language to translate Tauri specific strings

Well, I speak Spanish (that is precisely why I tried to add it to the languages list). Hopefully I could help translate the strings and submit a PR?

**Comment by FabianLars** [comment]
Yeah, well, that's the idea here (the community adding the translations via PRs). Just create a new file called `Spanish.nsh` and add the translations similar to the other files in that dir :)

Thanks for being interested in doing that btw!

**Comment by luisfi-dev** [comment]
Alright, will do
