### ISSUE TITLE
[bug] Tauri hasn't `window.navigtor.storage.estimate` method.

### ISSUE THREAD

**Issue by YanceyOfficial** [tauri-apps/tauri#6856]
### Describe the bug

Tauri hasn't `window.navigtor.storage.estimate` method, but can find in browser.

### Platform and versions

```text
@tauri-apps/cli [NPM]: 1.2.3 (outdated, latest: 1.3.0)
@tauri-apps/api [NPM]: 1.2.0 (outdated, latest: 1.3.0)
Tauri [RUST]: 1.2.4,
tauri-build [RUST]: 1.2.1,
```

**Comment by FabianLars** [comment]
This API is currently only available in Chromium, which means in Tauri it's only available on Windows. Since you didn't include the whole output of `tauri info` i'll assume you're on Linux or macOS. There's not much we can do other than waiting for Webkit to add this API.

**Comment by YanceyOfficial** [comment]
Thanks, my device is MacOS.
