### ISSUE TITLE
[feat] Upgrade from WiX to NSIS bundle

### ISSUE THREAD

**Issue by FabianLars** [tauri-apps/tauri#6859]
### Describe the problem

I'd like to switch my users that currently use the `.msi` bundle over to the new nsis target, preferably via manual installation _and_ via the updater.

I _think_ it would be better to ignore the old installation path because of the new default perUser install scope -> Of course we need to document this if we decide to to this.

This was also asked a few times on discord already. [One person](https://discord.com/channels/616186924390023171/731495028677148753/1103512731304333382) tried it with the current implementation and reported this:
> in my testing, it correctly updates the app but now there are system-wide registry keys for the msi install and user-local keys for the user install. so now there are two entries in the Windows uninstall panel and uninstalling either will obviously delete the application.

So it sounds like the wix uninstaller isn't executed? which would make sense to me since afaik we didn't really think much about this use case before, right?

### Describe the solution you'd like

See above x)

**Comment by prestomation** [comment]
I'm the 'one person'. I have a repro:


```
cargo install create-tauri-app
cargo create-tauri-app my-tauri-app --template vanilla-ts --manager npm
cd my-tauri-app
npm install
# Change the build id in tauri.conf.json so the bundler will run
cargo tauri build
open src-tauri\target\release\bundle\msi\my-tauri-app_0.0.0_x64_en-US.msi and install
open src-tauri\target\release\bundle\nsis\my-tauri-app_0.0.0_x64-setup.exe and install
```

Now if you go to Add/Remove programs, you will notice the app shows up twice.
Interestingly one of them is reported as being 600kb larger than the other?

Also, in this template app the icons on the homepage don't work in the installed release build

**Comment by amrbashir** [comment]
A PR is up https://github.com/tauri-apps/tauri/pull/6933 , I'd appreciate some testing before merging
