### ISSUE TITLE
Windows build could not run on other machine

### ISSUE THREAD

**Issue by nampdn** [tauri-apps/tauri#686]
**Describe the bug**
Dev machine => Build => .exe => Run Ok.
Another machine => Copy artifacts => Run .exe => Not run.

**To Reproduce**
1. Build => run on `dev` Windows machine => OK!
2. Copy artifact to other Windows machine
3. Run/Install
4. Nothing happened

**Expected behavior**

**Screenshots**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/26531658/84896514-9da8fc00-b093-11ea-92c6-1d0eadc7b5f4.png)

**Platform and Versions (please complete the following information):**

OS:
Node:
NPM:
Yarn:
Rustc:

**Additional context**

**Stack Trace**

**Comment by lucasfernog** [comment]
I found this problem related to the no-server mode. Just to confirm, are you using that mode?

**Comment by nampdn** [comment]
@lucasfernog I'm using no-server mode.

**Comment by lucasfernog** [comment]
@nampdn thanks for the report, your print was very helpful. Fixed in #688.

**Comment by nampdn** [comment]
Cheers!
