### ISSUE TITLE
[bug] Error failed to bundle project: app version major number cannot be greater than 255: app version major number cannot be greater than 255

### ISSUE THREAD

**Issue by liudonghua123** [tauri-apps/tauri#6862]
### Describe the bug

I tried to wrap https://github.com/hoppscotch/hoppscotch as an tauri app, however the version of hoppscotch is `2023.4.1` currently, so I got `Error failed to bundle project: app version major number cannot be greater than 255: app version major number cannot be greater than 255` error when building on windows. This error seems come from wix, is there any way to customization the file version of the app which support version like `2023.4.1`.

### Platform and versions

```text
The tauri version used is 1.2.0.


@liudonghua123 ➜ /workspaces/hoppscotch-app (main) $ npm run tauri info

> tauri
> tauri info


Environment
  › OS: Ubuntu 20.04 X64
  › Node.js: 19.9.0
  › npm: 9.6.3
  › pnpm: 8.4.0
  › yarn: 1.22.19
  › rustup: Not installed!
  › rustc: Not installed!
  › cargo: Not installed!
  › Rust toolchain: 

Packages
  › @tauri-apps/cli [NPM]: 1.2.0
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.0 (no lockfile),
  › tauri-build [RUST]: no manifest (no lockfile),
  › tao [RUST]: no manifest (no lockfile),
  › wry [RUST]: no manifest (no lockfile),

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: ../dist

App directory structure
  ├─ hoppscotch
  ├─ .git
  ├─ node_modules
  ├─ .github
  └─ src-tauri
@liudonghua123 ➜ /workspaces/hoppscotch-app (main) $
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by FabianLars** [comment]
This limit is enforced by WiX but it's actually a limitation of the MSI format itself: https://learn.microsoft.com/en-us/windows/win32/msi/productversion?redirectedfrom=MSDN which means there is nothing we can do.

So you either have to come up with your own version system that gets the first 2 versions below 255, or you can try the new NSIS target we added in [v1.3](https://tauri.app/blog/2023/05/03/tauri-1-3/#nsis) which should support any semver number.

**Comment by liudonghua123** [comment]
Thanks for the expanation, I see now. 😄

**Comment by simonhyll** [comment]
@liudonghua123 Just skip the 20 in 2023 and you'll be good for the next 77 years :D

**Comment by liudonghua123** [comment]
Yes, I have changed the version number, removed prefixed `20`, use `23.4.1` to represent `2023.4.1`. See https://github.com/liudonghua123/hoppscotch-app/releases/tag/23.4.1.

**Comment by CyberQin** [comment]
> @liudonghua123 Just skip the 20 in 2023 and you'll be good for the next 77 years :D

why not year-2000, available for next 232 years :)
