### ISSUE TITLE
[bug] visibilitychange event not working correctly

### ISSUE THREAD

**Issue by maxomatic458** [tauri-apps/tauri#6864]
### Describe the bug

The ``visibilitychange`` event only fires when the tauri app is minimized or maximized.

### Reproduction

in a react project. App.tsx:
```js
    document.addEventListener('visibilitychange', (e) => {
        console.log('visibilitychange', e);
    });
```
then hide the tauri window with another window.

### Expected behavior

this event should also be registered if the tauri window is being obscured by another one (that is exactly what happens in the browser). Example https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

### Platform and versions

```text
Environment
  › OS: Windows 10.0.19045 X64
  › Webview2: 112.0.1722.64
  › MSVC: 
      - Visual Studio Build Tools 2022
  › Node.js: 16.17.1
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.68.0
  › cargo: 1.68.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.3.0
  › tauri [RUST]: 1.2.5,
  › tauri-build [RUST]: 1.3.0,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React

App directory structure
  ├─ .vscode
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

**Comment by amrbashir** [comment]
looks like it is an upstream bug: https://github.com/MicrosoftEdge/WebView2Feedback/issues/2681

**Comment by Legend-Master** [comment]
Is this something we can do?

> In order to manipulate a control's visibility in correlation with the window's state (like when the window is minimized), you would need to handle the StateChanged event of the window and change the control's Visibility property as needed.
> https://github.com/MicrosoftEdge/WebView2Feedback/issues/2681#issuecomment-1586686876

Also according to https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2controller?view=webview2-winrt-1.0.2365.46#isvisible

> Determines whether to show or hide the WebView. If IsVisible is set to false, the WebView is transparent and is not rendered. However, this does not affect the window containing the WebView (the ParentWindow parameter that was passed to [CoreWebView2Environment.CreateCoreWebView2ControllerAsync](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2environment?view=webview2-winrt-1.0.2365.46#createcorewebview2controllerasync)). WebView as a child window does not get window messages when the top window is minimized or restored. For performance reasons, developers should set the IsVisible property of the WebView to false when the app window is minimized and back to true when the app window is restored. The app window does this by handling SIZE_MINIMIZED and SIZE_RESTORED command upon receiving WM_SIZE message. There are CPU and memory benefits when the page is hidden. For instance Chromium has code that throttles activities on the page like animations and some tasks are run less frequently. Similarly, WebView2 will purge some caches to reduce memory usage.

If not, could we provide a polyfill for this?

I don't think `visibilitychange` fires for `window.show` / `window.hide` nor `window.minimize`

And I don't think we can listen for these events easily right now

> https://github.com/tauri-apps/tao/blob/88e1e32901fff8de329ec948b5b858ed05dcde78/src/event.rs#L238-L403

Minimize and restore triggers `Resized` event, maybe we just need to record `set_visibility` and set `IsVisible` on those events
