### ISSUE TITLE
[bug] writeBinaryFile cant write file with size more, than ~50 mb

### ISSUE THREAD

**Issue by MegaSa1nt** [tauri-apps/tauri#6866]
### Describe the bug

I'm trying to write file with 70 mb size and it keeps crashing with "Out of Memory" error (or just crash)
https://youtu.be/ygcYvTq4xBI
It shouldn't close

### Reproduction

1. Get >=50mb file in Uint8Array
2. Try to write it

### Expected behavior

New file

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 112.0.1722.68
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ✔ rustup: 1.25.2 (17db695f1 2023-02-01)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.16.0
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 1.2.4
    - tauri-build [RUST]: 1.2.1
    - wry [RUST]: 0.23.4
    - tao [RUST]: 0.15.8
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.3.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../src
    - devPath: ../src
```

**Comment by DjakaTechnology** [comment]
This is a limitations in current IPC, I encountered same problem and talked with the devs on discord. You need to split into smaller batch, and write incrementally.

I ended up doing this:

following reference: https://github.com/tauri-apps/tauri/issues/585

Flow:
Convert blob to array buffer -> JS ArrayBuffer -> Split to smaller chunk -> Rust append the buffer to a file string -> Repeat untill all chunk is writren

```ts
async function sendArrayBufferToRust(
  path: string,
  arrayBuffer: ArrayBuffer,
  progressCallback?: (progress: number) => void
) {
  const chunkSize = 1024 * 1024 * 10; // 10MB
  const numChunks = Math.ceil(arrayBuffer.byteLength / chunkSize);
  for (let i = 0; i < numChunks; i++) {
    const start = i * chunkSize;
    const end = Math.min(start + chunkSize, arrayBuffer.byteLength);
    const chunk = arrayBuffer.slice(start, end);
    if (!(await runAppendChunkToRust(path, new Uint8Array(chunk)))) {
      console.log("error");
      return false;
    }
    if (progressCallback) {
      const progress = (i + 1) / numChunks;
      progressCallback(progress);
    }
  }
  return true;
```

```rs
#[tauri::command]
fn append_chunk_to_file(path: String, chunk: Vec<u8>) -> Result<(), String> {
    let mut file = OpenOptions::new()
        .create(true)
        .append(true)
        .open(&path)
        .map_err(|e| e.to_string())?;

    file.write_all(&chunk).map_err(|e| e.to_string())?;

    Ok(())
}
```

**Comment by MegaSa1nt** [comment]
Hi @DjakaTechnology !
Thanks for your code, but it gives me this error:
![image](https://user-images.githubusercontent.com/49565695/236350528-537e8411-2b3d-4e61-bb03-f841c6f1b9ef.png)
I modified code a little:
```js
async function sendArrayBufferToRust(path, arrayBuffer) {
  const chunkSize = 1024 * 1024 * 10; 
  const numChunks = Math.ceil(arrayBuffer.byteLength / chunkSize);
  for (let i = 0; i < numChunks; i++) {
    const start = i * chunkSize;
    const end = Math.min(start + chunkSize, arrayBuffer.byteLength);
    const chunk = arrayBuffer.slice(start, end);
    if (!(await window.__TAURI__.tauri.invoke("append_chunk_to_file", {path: path, chunk: new Uint8Array(chunk)}))) {
      console.log("error");
      return false;
    }
  }
  return true;
}
```

**Comment by DjakaTechnology** [comment]
> Hi @DjakaTechnology !
> Thanks for your code, but it gives me this error:
> ![image](https://user-images.githubusercontent.com/49565695/236350528-537e8411-2b3d-4e61-bb03-f841c6f1b9ef.png)
> I modified code a little:
> ```js
> async function sendArrayBufferToRust(path, arrayBuffer) {
>   const chunkSize = 1024 * 1024 * 10; 
>   const numChunks = Math.ceil(arrayBuffer.byteLength / chunkSize);
>   for (let i = 0; i < numChunks; i++) {
>     const start = i * chunkSize;
>     const end = Math.min(start + chunkSize, arrayBuffer.byteLength);
>     const chunk = arrayBuffer.slice(start, end);
>     if (!(await window.__TAURI__.tauri.invoke("append_chunk_to_file", {path: path, chunk: new Uint8Array(chunk)}))) {
>       console.log("error");
>       return false;
>     }
>   }
>   return true;
> }
> ```

Convert uint8array into an array before sending to invoke, do this:

invoke(blanlabla, { foo: Array.from(chunk) }

```ts
if (!(await window.__TAURI__.tauri.invoke("append_chunk_to_file", {path: path, chunk: Array.from(new Uint8Array(chunk))}))) {
      console.log("error");
      return false;
    }
```

**Comment by MegaSa1nt** [comment]
@DjakaTechnology i'm sorry, but it wrote only 10 megabytes (should be 70 mb)
![image](https://user-images.githubusercontent.com/49565695/236370529-e20fe81d-0f4a-49c7-b01d-f4c5441107f6.png)

**Comment by DjakaTechnology** [comment]
> @DjakaTechnology i'm sorry, but it wrote only 10 megabytes
> ![image](https://user-images.githubusercontent.com/49565695/236370529-e20fe81d-0f4a-49c7-b01d-f4c5441107f6.png)
> 

Is the function finished running?

It might take a while since its writing 10MB, then 10MB, then 10MB until all written

**Comment by MegaSa1nt** [comment]
> Is the function finished running?
> 
> It might take a while since its writing 10MB, then 10MB, then 10MB until all written

function 100% finished running
![image](https://user-images.githubusercontent.com/49565695/236371237-3c25a83a-ae74-4dc6-b5fa-9d825401a25f.png)

**Comment by DjakaTechnology** [comment]
> > Is the function finished running?
> > 
> > It might take a while since its writing 10MB, then 10MB, then 10MB until all written
> 
> function 100% finished running
> ![image](https://user-images.githubusercontent.com/49565695/236371237-3c25a83a-ae74-4dc6-b5fa-9d825401a25f.png)
> 

Do you have a small reproducible repo that I can try?

**Comment by MegaSa1nt** [comment]
> Do you have a small reproducible repo that I can try?

1. Get somehow >10mb file to ArrayBuffer [(this is my file)](https://gcs.icu/download/ffmpeg.exe)
2.
```js
async function sendArrayBufferToRust(path, arrayBuffer) {
  const chunkSize = 1024 * 1024 * 10; 
  const numChunks = Math.ceil(arrayBuffer.byteLength / chunkSize);
  for (let i = 0; i < numChunks; i++) {
    const start = i * chunkSize;
    const end = Math.min(start + chunkSize, arrayBuffer.byteLength);
    const chunk = arrayBuffer.slice(start, end);
    if (!(await window.__TAURI__.tauri.invoke("append_chunk_to_file", {path: path, chunk: Array.from(new Uint8Array(chunk))}))) {
      console.log("error");
      return false;
    }
  }
  return true;
}
```

small addition: this function wrote first 10 mb (if i get it right, cuz file starts with MZђ)
![image](https://user-images.githubusercontent.com/49565695/236372458-5777f86b-ae48-4929-88eb-6ece8b9d6a5e.png)

this is how i use this function:
```js
function zipFile(fileData, filename) {
    return new Promise(resolve => {
		plol = filename.split("/");
		pstr = "";
		if(plol[1]) for(i = 0; i < plol.length; i++) {
			if(plol[i] == plol[plol.length-1]) continue;
			if(i > 0) pstr = pstr+"/"+plol[i];
			else pstr = plol[i];
		}
		window.__TAURI__.fs.createDir(pstr, {recursive: true});
		prog.value = l;
		if(l % 10 == 1) document.getElementById("ploaded").innerHTML = l +" файл";
		else if(l % 10 > 1 && l % 10 < 5 && l % 10 != 0) document.getElementById("ploaded").innerHTML = l +" файла";
		else document.getElementById("ploaded").innerHTML = l +" файлов";
		if(fileData.length < 31457280) window.__TAURI__.fs.writeBinaryFile(filename, fileData, {dir: window.__TAURI__.fs.BaseDirectory.Resource}).then(re => {
			window.gc();
			resolve(true);
		}).catch(e =>{resolve(true)});
		else {
			arrayb = fileData.buffer;
			if(sendArrayBufferToRust(filename, arrayb)) resolve(true); // here im using it
		}
    })
}
```

**Comment by MegaSa1nt** [comment]
![image](https://user-images.githubusercontent.com/49565695/236384300-758f7df1-b9a4-486d-887a-55eeeeb3d4b0.png)
Just saw, that it prints 2 errors (on 2 big files)
How can i see this error?
I already tried to run my app with admin rights

**Comment by MegaSa1nt** [comment]
I fixed this with removing "await" from invoke function, thank you very much!

**Comment by Xiaobaishushu25** [comment]
I need ten seconds to transfer a 23mb file using this function, why does it take so long?

**Comment by DjakaTechnology** [comment]
> I need ten seconds to transfer a 23mb file using this function, why does it take so long?

Give up using this method if you want to send large files fast. There's a bottleneck somewhere, I've written about those in the first reply.

Currently, my tauri app starts a local http server and I send large files via http request. It's very fast

**Comment by Xiaobaishushu25** [comment]
> > I need ten seconds to transfer a 23mb file using this function, why does it take so long?
> 
> Give up using this method if you want to send large files fast. There's a bottleneck somewhere, I've written about those in the first reply.
> 
> Currently, my tauri app starts a local http server and I send large files via http request. It's very fast

thank for you advise，i test use http to transfer file,It's really much faster.

**Comment by Pagla-Dasu** [comment]
> > > I need ten seconds to transfer a 23mb file using this function, why does it take so long?
> > 
> > 
> > Give up using this method if you want to send large files fast. There's a bottleneck somewhere, I've written about those in the first reply.
> > Currently, my tauri app starts a local http server and I send large files via http request. It's very fast
> 
> thank for you advise，i test use http to transfer file,It's really much faster.

Hey, @Xiaobaishushu25 , can you provide the block of code, it would be really helpful. Thanks in advance.

**Comment by Xiaobaishushu25** [comment]
> > > > I need ten seconds to transfer a 23mb file using this function, why does it take so long?
> > > 
> > > 
> > > Give up using this method if you want to send large files fast. There's a bottleneck somewhere, I've written about those in the first reply.
> > > Currently, my tauri app starts a local http server and I send large files via http request. It's very fast
> > 
> > 
> > thank for you advise，i test use http to transfer file,It's really much faster.
> 
> Hey, @Xiaobaishushu25 , can you provide the block of code, it would be really helpful. Thanks in advance.

what block of code you want? use http to transfer file?

**Comment by Pagla-Dasu** [comment]
Yeah, that would be great.
A little context; I am converting files using ffmpeg and I need to save the converted file on the local machine. But, the speed is so slow and the app freezes when if the file is too big, it would be great if there would be a solution using HTTP or anything else. Any help is much appreciated.
@Xiaobaishushu25 @DjakaTechnology

**Comment by Xiaobaishushu25** [comment]
> Yeah, that would be great. A little context; I am converting files using ffmpeg and I need to save the converted file on the local machine. But, the speed is so slow and the app freezes when if the file is too big, it would be great if there would be a solution using HTTP or anything else. Any help is much appreciated. @Xiaobaishushu25 @DjakaTechnology

i used [salvo](https://salvo.rs/book/topics/upload-file.html) to enable web services, this is my simple code to transfer file:
```rust
#[handler]
async fn upload(req: &mut Request, res: &mut Response) {
    let path = req.form::<String>("path").await.unwrap();
    let file = req.file("file").await;
    let id = generate_unique_id();
    if let Some(file) = file {
        let id = generate_unique_id();
        // let extension = if let Some(file_name) = file.name(){
        //     file_name.split('.').collect::<Vec<_>>().last().unwrap_or(&"xbss")
        // }else {
        //     "xbss"
        // };
        let extension = file
            .name()
            .and_then(|name: &str| {
                name.split('.')
                    .collect::<Vec<_>>()
                    .last()
                    .map(|str| str.to_string())
            })
            .unwrap_or("xbss".to_string());
        // file.name().and_then(|name|{name.split('.').collect::<Vec<_>>().last()}).unwrap_or(&"xbss");
        let path = Path::new(&path).join(format! {"{id}.{extension}"});
        // let dest = format!("F:\\WorkSpace\\Rust\\RustRover\\paper-enhancement\\src-tauri\\target\\debug\\database\\img\\edit/{}", file.name().unwrap_or("file"));
        // let dest = format!("F:\\WorkSpace\\Rust\\RustRover\\paper-enhancement\\src-tauri\\target\\debug\\database\\img\\edit/{}", file.name().unwrap_or("file"));
        // let info = if let Err(e) = fs::copy(&file.path(), Path::new(&dest)) {
        let info = if let Err(e) = fs::copy(&file.path(), &path) {
            res.status_code(StatusCode::INTERNAL_SERVER_ERROR);
            tracing::info!("file upload failure: {}", e);
            format!("file upload failure: {}", e)
        } else {
            tracing::info!("File uploaded to {:?}", path);
            format!("File uploaded to {:?}", path)
        };
        // res.render(Text::Plain(info));
        res.render(Json(ImagePath(path.to_string_lossy().to_string())))
    } else {
        res.status_code(StatusCode::BAD_REQUEST);
        tracing::error!("file not found in request");
        // res.render(Text::Plain("file not found in request"));
        res.render(Json(ImagePath("file not found in request".to_string())))
    };
}
```
but now i think use [tauriv2](https://beta.tauri.app/guides/) is a good idea, more detail can see https://github.com/tauri-apps/tauri/issues/9322

**Comment by Pagla-Dasu** [comment]
Thank you for this.
