### ISSUE TITLE
[bug] `pnpm tauri android build` Fails to upload after signing

### ISSUE THREAD

**Issue by ZanzyTHEbar** [tauri-apps/tauri#6880]
### Describe the bug

I build my apk (which works in dev) `pnpm tauri android build` - i get a `amd64/debug` and a `universal/release` in the `outputs` directory of the android project. 

The `amd64/debug` - uploads, but does not load with the error on screen `ERR_CONNECITON_REFUSED` - which makes sense, as it's likely looking for the tauri dev server. 

However, `universal/release` - fails to upload to the device with the error:
```bash
Performing Streamed Install
adb: failed to install F:\Github\DroneControl\app\src-tauri\gen\android\drone_control\app\build\outputs\apk\universal\release\app-universal-release-unsigned.apk: Failure [INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2]
```

I have signed it via the `debug.keystore` file using the below command:
```bash
.\jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore C:\Users\zacar\.android\debug.keystore F:\Github\DroneControl\app\src-tauri\gen\android\drone_control\app\build\outputs\apk\universal\release\app-universal-release-unsigned.apk androiddebugkey
```

### Reproduction

https://github.com/ZanzyTHEbar/DroneControl

### Expected behavior

The APK  uploads and run as intended

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 112.0.1722.68
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.68.2 (9eb3afe9e 2023-03-27)
    ✔ Cargo: 1.68.2 (6feb7c9cf 2023-03-26)
    ✔ rustup: 1.25.2 (17db695f1 2023-02-01)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 19.8.1
    - pnpm: 8.4.0
    - yarn: 1.22.19
    - npm: 9.6.4

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.8
    - tauri-build [RUST]: 2.0.0-alpha.4
    - wry [RUST]: 0.27.3
    - tao [RUST]: 0.18.3
    - @tauri-apps/api [NPM]: 2.0.0-alpha.3
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.8

[-] App
    - build-type: bundle
    - CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self' asset: https://asset.localhost media-src stream: https://stream.localhost
    - distDir: ../dist
    - devPath: http://localhost:3000/
    - framework: SolidJS
    - bundler: Vite
```

**Comment by amrbashir** [comment]
Please follow this guide https://next--tauri.netlify.app/next/guides/distribution/sign-android to sign your apk, then build a universal apk which should work on all platforms by calling `pnpm tauri android build` or you can split each target in its own apk by calling `pnpm tauri android build --split-per-abi` and make sure that the device doesn't have an older version installed before installing the new signed version.

**Comment by ZanzyTHEbar** [comment]
issue was caused by my signing process. 

I have signed the APK using the guide I found here: <https://next--tauri.netlify.app/next/guides/distribution/sign-android/>

App uploads correctly now.
