### ISSUE TITLE
[bug] Not work on win 7

### ISSUE THREAD

**Issue by Zipexpo** [tauri-apps/tauri#6884]
### Describe the bug

Despite installing webview2 with "embedBootstrapper" option. The app can't run on Win 7.
1. When the setup (nsis) is running, it always appear the message as "The <<name of appp>> is running. Please kill it", I clicked enter, and the install finished.
2. I check the control panel and confirm that webview2 already install
3. Open the app, and something needs to be shown. To be specific, the app auto close after 1-2 seconds.

In another scenario, install with msi
1. Setup done
2. webview2 installed
3. Open the app and get the bank screen 

### Reproduction

You can use this link to setup on win 7 https://github.com/iDataVisualizationLab/TxDOT/blob/main/dist/TxCRCPME%20Setup%202.9.exe 

### Expected behavior

The app should show in win 7

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 112.0.1722.68
    ✔ MSVC:
        - Visual Studio Build Tools 2017
        - Visual Studio Build Tools 2022
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 16.15.1
    - yarn: 1.22.19
    - npm: 9.3.1

[-] Packages
    - tauri [RUST]: git+https://github.com/tauri-apps/tauri?branch=dev#422b48179856504e980a156500afa8e22c44d357 (1.3.0)
    - tauri-build [RUST]: git+https://github.com/tauri-apps/tauri?branch=dev#422b48179856504e980a156500afa8e22c44d357 (1.3.0)
    - wry [RUST]: 0.24.1
    - tao [RUST]: 0.16.0
    - @tauri-apps/api [NPM]: 1.3.0
    - @tauri-apps/cli [NPM]: 1.3.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by xiaominglee4github** [comment]
I have the same issue. Anybody know how to fix it? thanks

**Comment by FabianLars** [comment]
Can you guys try a debug build via `npm run tauri build -- --debug`? (other package managers don't need the extra `--`) -> Output in `target/debug/`
If that also crashes without any indicators try starting it from inside cmd.exe.

Also try updating tauri and all dependencies via `cargo update`.

p.s. the app linked above crashes for me too, my own apps work fine.

**Comment by SeaIsCoder** [comment]
i meet the same case in window 11, show the bank screen,do you  fix it?
