### ISSUE TITLE
[feat] Display program name + version in start up menu on windows

### ISSUE THREAD

**Issue by Zipexpo** [tauri-apps/tauri#6887]
### Describe the problem

Is it possible to display the Name and version on the start-up without changing the productName?

### Describe the solution you'd like

If my app name is "MyApp" and my version is "1.0.0"
I want the name on the startup to be "MyApp 1.0.0" but the name on the Control panel will still "MyApp"

**Comment by amrbashir** [comment]
What do you mean on the "startup" ?

**Comment by amrbashir** [comment]
Anyways, for WiX Installer, you can specify a custom template, see https://tauri.app/v1/api/config#wixconfig.template
and for NSIS Installer, a PR to add support for custom template is here https://github.com/tauri-apps/tauri/pull/6922
