### ISSUE TITLE
[bug]IPC breaks after using custom protocol

### ISSUE THREAD

**Issue by prestomation** [tauri-apps/tauri#6889]
### Describe the bug

This will be a fun one. 

I'm seeing some very weird bug reports from users of my app.
This is a corporate app with some internal beta users using a Tauri app that is using the new remote IPC feature. 

Our website on a remote origin uses the tauri API to communicate with our tauri app. Unrelated to Tauri, this website also opens some links using a custom protocol registered on the users OS, something like `custom-protocol://`.

The bug reports show that commands stop working after the user uses this custom protocol, where the scope checker thinks the current URL is the previous `custom-protocol://` link even though the current origin is an allowlisted origin.

My bug reports and repro are on Windows.
 
![tauribug](https://user-images.githubusercontent.com/845970/236659722-d0efdbe7-231e-452f-bb5d-70d974f4efb7.PNG)

### Reproduction

I have sort of repro'd this, although I don't have full instructions. The gist of it is:

1. Have a tauri app running on a remote origin that is whitelisted
2. Navigate to a custom protocol. It doesn't even need to be a real one/registered
3. Notice that you get an error and you are still on your intended origin.
4. Now invoke a tauri command and notice you get the IPC error. The URL in the error is the custom-protocol from above.

I've attached a screenshot showing me performing this repro in the dev tools. I understand it's kind of incomplete but I think the description above should be enough to understand what's going on. 

### Expected behavior

I expect tauri commands to continue to work when i'm on my origin and for custom procotols to not break this.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 112.0.1722.68
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.68.0 (2c8cc3432 2023-03-06)
    ✔ Cargo: 1.68.0 (115f34552 2023-02-26)
    ✔ rustup: 1.25.2 (17db695f1 2023-02-01)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.15.0
    - npm: 9.5.0

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.1
    - tao [RUST]: 0.16.0
    - @tauri-apps/api [NPM]: 1.2.0 (outdated, latest: 1.3.0)
    - @tauri-apps/cli [NPM]: 1.3.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by prestomation** [comment]
It looks as if the URL stored on the rust side is being updated on every navigation event, and if that event fails or causes the webview to open an external process, then the URL is not set back to the origin and these two things are out of sync.

**Comment by prestomation** [comment]
I've found a workaround.

This website uses a custom-protocol like `custom-protocol://{command}`. I can treat the command like a domain name and add it to the scope list and things work as expected

**Comment by prestomation** [comment]
I think this is more serious as it does not just apply to remote sites. This will break 'regular' tauri apps if they use any sort of protocol that opens something on the desktop, like mailto:

**Comment by amrbashir** [comment]
I have been trying to reproduce this but no avail, @prestomation could you provide a minimal reproducible example?

**Comment by FabianLars** [comment]
btw, the reason i bumped the prio is because someone on discord had a similar issue: https://discord.com/channels/616186924390023171/731495028677148753/1106295209748349050 There the main website's invoke broke as soon as an iframe was being served via a custom protocol (maybe that's easier to repro idk)

**Comment by prestomation** [comment]
I have repro'd it on windows
1. Create a new app `cargo create-tauri-app my-tauri-app --template vanilla-ts --manager npm`
2. Apply this diff 
```
PS C:\> git diff
diff --git a/index.html b/index.html
index 4504469..684dc70 100644
--- a/index.html
+++ b/index.html
@@ -46,6 +46,7 @@
       <div class="row">
         <div>
           <input id="greet-input" placeholder="Enter a name..." />
+          <button id="protocol-button" type="button">CustomProtocol</button>
           <button id="greet-button" type="button">Greet</button>
         </div>
       </div>
diff --git a/src/main.ts b/src/main.ts
index 638e793..6c52fd3 100644
--- a/src/main.ts
+++ b/src/main.ts
@@ -18,4 +18,7 @@ window.addEventListener("DOMContentLoaded", () => {
   document
     .querySelector("#greet-button")
     ?.addEventListener("click", () => greet());
+  document
+    .querySelector("#protocol-button")
+    ?.addEventListener("click", () => window.location.href = "foobar://foobar");
 });
```
3. npm install + cargo tauri dev to start the app
4. In the app, open dev tools
5. Click our new "CustomProtocol" button and then press 'Greet'
6. Notice the error in the devtools like below

![Capture](https://github.com/tauri-apps/tauri/assets/845970/47e7d4a2-2ed3-4b59-a878-ce08f8a66016)
ps/tauri/assets/845970/b77ed1ea-9739-4634-9869-2ef2020492f8)


I haven't ran this same scenario on mac, but i see the same behavior on mac in my app

**Comment by amrbashir** [comment]
thanks for the repro, I see the issue now.
