### ISSUE TITLE
[bug] create new windows set_transparent is missing

### ISSUE THREAD

**Issue by tufik2** [tauri-apps/tauri#6903]
### Describe the bug

Hi Guys, I have the next code, I don't found a way to set the window transparent in child windows.

So if code is there, but not in documentation, how I could create a new window with transparent option = true? and avoid this white ugly background...
```rust
pub fn CreateWindow(handle: AppHandle) {
	let app = tauri::WindowBuilder::new(
		&handle,
		"systemTray",
		tauri::WindowUrl::App("systemTray.html".into())
	).build().unwrap();
	app.set_decorations(false);
}
```
<img width="860" alt="Screenshot 2023-05-08 at 9 59 43 AM" src="https://user-images.githubusercontent.com/195716/236844218-a0c7ae75-321e-4893-9dbf-9421d5fe7bfd.png">

### Platform and versions

```text
macOS ventura 13.3.1
tauri = { version = "1.3", features = ["api-all", "macos-private-api", "system-tray"] }
```

**Comment by FabianLars** [comment]
afaik transparency can only be enabled on the WindowBuilder (before the window is created), not on the Window, so you're looking for this: https://docs.rs/tauri/latest/tauri/window/struct.WindowBuilder.html#method.transparent
Inserted into your code:
```rs
pub fn CreateWindow(handle: AppHandle) {
	let app = tauri::WindowBuilder::new(
		&handle,
		"systemTray",
		tauri::WindowUrl::App("systemTray.html".into())
	)
          .transparent(true)
          .build().unwrap();
	app.set_decorations(false);
}
```
Note that on macOS you'll have to enable [`macOSPrivateApi`](https://tauri.app/v1/api/config#tauriconfig.macosprivateapi) in tauri.conf.json for this to work.

**Comment by tufik2** [comment]
Thanks for your answer.....  I appreciate the quick answer :)
