### ISSUE TITLE
[feat] Add Korean as available language for NSIS installers

### ISSUE THREAD

**Issue by Raphiiko** [tauri-apps/tauri#6906]
### Describe the problem

In my `tauri.conf.json`, I have Dutch, Japanese and Korean configured as languages under `tauri.bundle.windows.nsis.languages`. However when building the following error shows for each of these languages when they are included, when bundling the installer: 

`Error failed to bundle project: Language (Korean/Japanese/Dutch) not implemented. If it is a valid language listed on <https://github.com/kichik/nsis/tree/9465c08046f00ccb6eda985abbdbf52c275c6c4d/Contrib/Language%20files>, please open a Tauri feature request`
 
The three of these languages are all included in the list at the URL given in the error message.

### Describe the solution you'd like

I would like to see support added for these three languages, as this would allow me to switch to a single multi-language installer.

**Comment by FabianLars** [comment]
In case you speak any of these languages: My comment in https://github.com/tauri-apps/tauri/issues/6852#issuecomment-1534287343 applies here too:
> for a language to be actually supported we need someone from the community that speaks the requested language to translate Tauri specific strings: https://github.com/tauri-apps/tauri/tree/dev/tooling/bundler/src/bundle/windows/templates/nsis-languages

Contributions much appreciated :)

**Comment by Raphiiko** [comment]
I'm afraid Dutch is the only language I can help out with. I've submitted a PR to add support for it in #6907.

**Comment by nathan-fall** [comment]
As a Japanese speaker, I created a Japanese translation. #6940

**Comment by amirHdev** [comment]
I am a Persian speaker and submitted PR : #6965

**Comment by soumt-r** [comment]
This is my first time contributing on such a big project, so I apologize for any mistakes...

I have completed the translation as a Korean speaker and opened a PR : #7010
