### ISSUE TITLE
String value in HttpRequestOptions header field gets escaped incorrectly

### ISSUE THREAD

**Issue by fuzzy-person** [tauri-apps/tauri#691]
**Describe the bug**
when you pass `String` value to  `params` or `header` field in `HttpRequestOptions` it will get escaped and adds `"` to both start and end, and this added `"` will get treated as a part of value by the receiver.

<details>
<summary>==== description with example ====</summary>

```rust
let mut header: HashMap<String, Value> = HashMap::new();
let mut params: HashMap<String, Value> = HashMap::new();

header.insert(String::from("Authorization"), String::from("Bearer AUTHTOKEN").into());
params.insert(String::from("foo"), String::from("bar").into());

let option = HttpRequestOptions {
    method: String::from("get"),
    url: String::from("https://postman-echo.com/get"),
    headers: Some(header),
    params: Some(params),
    ...
    response_type: Some(ResponseType::Text),
};

println!("Result: {}", make_request(option).unwrap());
```

This print produces following result (some detail has been omitted and formatted)
```
{
  "args": { 
    "part": "\"id\"",
    "mine": "true"
  },
  "headers": {
    "host": "postman-echo.com",
    "x-forwarded-proto":"https",
    "x-forwarded-port":"443",
    "x-amzn-trace-id":"Root=1-5eeaf475-955a64323b68e37d4180becd",
    "authorization":"\"Bearer ACCESS_TOKEN.aeab-eearwer\"", 
    ... 
```
value of `authorization` field in `header` object should not have escaped `"`.

</details>

**To Reproduce**
1. Create new Tauri project and open `src-tauri/main.rs`
2. in `main` function, create `HttpRequestOptions` and set `header` to have at least one or more `String` value, and set `url` to any HTTP url that echoes HTTP request (I tested with Postman Echo)
3. call `make_request` with given option and observe the result.

**Expected behavior**
Postman echoes correctly formed header, expected like
```
{
  "args": { "foo": "bar" },
  "header": { .., "authorization": "Bearer  AUTHTOKEN", .. },
  ...
}
```

**Screenshots**

**Platform and Versions (please complete the following information):**

OS: `Linux(5.6.13-arch1-1) - linux/x64`
Node: `14.4.0`
NPM: `6.14.5`
Yarn: `1.22.4`
Rustc: `1.44.0`

**Additional context**
If I understand correctly the `HttpRequestOptions` is shared between JS and Rust which forces any HashMap within this struct to have `HashMap<String, Value>` type.

I also tried to test from js side using `get(url: string, options?: HttpOptions): Promise<any>` and had a bit different behavior, and I'm not quite sure if this is a bug related to this issue, or an entirely different thing, or just simply I'm using it wrong.

English is not my native language, I'm sorry if there is any grammar error that makes it hard to understand.
**Stack Trace**

**Comment by fuzzy-person** [comment]
looks like the cause of this problem is that the `format!("{}", header_value),` in `make_request` produces the _serialized_ string of data.
when `Value::String` gets serialized, it adds `\"` to both start and end.

the most simple workaround for this problem would be just pattern-match the `Value` enum and format every inner value individually, but it means that it will allocate a string for every value but `Value::String` itself (which you can just move out from enum)

**Comment by lucasfernog** [comment]
Seems like I should use `String` instead of `Value` since every header value should be a string anyway. The drawback is that if you send another type, it would result in an API error.

**Comment by lucasfernog** [comment]
Let me know if you guys think otherwise.

Thanks for the issue report and the insight!
