### ISSUE TITLE
[non-critical] println! typo ?

### ISSUE THREAD

**Issue by Megamannen** [tauri-apps/tauri#6912]
Feels like this was a mistake, right? It no longer outputs `out_dir` variable, but lierally `"out_dir"`

https://github.com/tauri-apps/tauri/blame/2659ca1ab4799a5bda65c229c149e98bd01eb1ee/core/tauri-build/src/static_vcruntime.rs#L57

```rust
println!("cargo:rustc-link-search=native={out_dir}");
// vs
println!("cargo:rustc-link-search=native={}", out_dir);
```

**Comment by FabianLars** [comment]
Nope, it's correct. Rust 1.58 added support for that syntax (i always call it implicit format arg but i think that's wrong...).
https://doc.rust-lang.org/std/fmt/index.html

Thank you for the report though!!
