### ISSUE TITLE
[bug] `<input type="file" accept="image/*" />`, non-image files can still be selected.

### ISSUE THREAD

**Issue by YanceyOfficial** [tauri-apps/tauri#6915]
### Describe the bug

Even if I set accept="image/*" on the input file tag, non-image files can still be selected in tauri, while they are not selected in browser.

I'am in MacOS.

### Platform and versions

```text
@tauri-apps/cli [NPM]: 1.2.3 (outdated, latest: 1.3.0)
@tauri-apps/api [NPM]: 1.2.0 (outdated, latest: 1.3.0)
Tauri [RUST]: 1.2.4,
tauri-build [RUST]: 1.2.1,
```

**Comment by FabianLars** [comment]
Can you please add the _whole_ output of `tauri info` as the template required? Or at least tell us your macOS version please.

> while they are not selected in browser.

What kind of browser did you test? Please test it in Safari since that's basically what Tauri's WebView is on macOS.

**Comment by PavelLaptev** [comment]
Has this been fixed? I'm experiencing the same issue.
