### ISSUE TITLE
[feat] Overriding installation path for NSIS installation packages during silent instalation doesn't work

### ISSUE THREAD

**Issue by gribunin** [tauri-apps/tauri#6928]
### Describe the problem

Usually the installation package generated with NSIS allows to pass the installation directory via command line. This is especially important for silent installations. The command line looks like this:
```
installer.exe /S /D=C:\Users\Public\installDir
```
In order the installer to support this parameter the code in the installer must look something like this:
```nsis
${If} $InstDir == "" ; /D not used
    ; custom logic to set installation path
${EndIf}
```
NSIS template in the Tauri codebase (\tooling\bundler\src\bundle\windows\templates\installer.nsi ) doesn't check against if the $InstDir is already set (via command line) and just sets the $InstDir value based on install mode.

### Describe the solution you'd like

I think the NSIS installation template must be modified so that the $InstDir  will be set only if it wasn't set via command line parameter. Something like this:
```nsis
${If} $InstDir == "" ; /D not used
  !if "${INSTALLMODE}" == "perMachine"
    ; Set default install location
    ${If} ${RunningX64}
      !if "${ARCH}" == "x64"
        StrCpy $INSTDIR "$PROGRAMFILES64\${PRODUCTNAME}"
      !else if "${ARCH}" == "arm64"
        StrCpy $INSTDIR "$PROGRAMFILES64\${PRODUCTNAME}"
      !else
        StrCpy $INSTDIR "$PROGRAMFILES\${PRODUCTNAME}"
      !endif
    ${Else}
      StrCpy $INSTDIR "$PROGRAMFILES\${PRODUCTNAME}"
    ${EndIf}
  !else if "${INSTALLMODE}" == "currentUser"
    StrCpy $INSTDIR "$LOCALAPPDATA\${PRODUCTNAME}"
  !endif
!endif
```

**Comment by amrbashir** [comment]
@gribunin thank you for the detailed explanation and fix, a PR is up now #6935, would be appreciated if you can test the fix by installing the CLI from git using `cargo install --git https://github.com/tauri-apps/tauri --branch dev tauri-cli` then use `cargo tauri build` to build the installer.

**Comment by gribunin** [comment]
Yes it works. I just had to fetch the tauri-cli from the "fix/nsis/restore-installation-path" branch (it seems your commit is there):
```
cargo install --git https://github.com/tauri-apps/tauri --branch fix/nsis/restore-installation-path tauri-cli
```
not from the "dev" branch.

**Comment by amrbashir** [comment]
Ah my bad, thanks for testing.
