### ISSUE TITLE
[bug] build on macos when passing in the path as `TAURI_PRIVATE_KEY` does not produce .sig file

### ISSUE THREAD

**Issue by hill** [tauri-apps/tauri#6950]
### Describe the bug

Spent an hour or so working this out - so documenting here:

Attempting to build on macos (Apple M1 Pro on 13.3.1) with `yarn tauri build` produces a `.app.tar.gz` bundle but does **not** produce a `.app.tar.gz.sig` file in `target/release/bundle/macos/`.

This happens when $TAURI_PRIVATE_KEY is set to a path (like "~/.tauri/myapp.key") and not the contents of the key. When I use the contents of the key the build works as expected. 

The [documentation suggests](https://tauri.app/v1/guides/distribution/updater/#signing-updates:~:text=Path%20or%20content%20of%20your%20private%20key) that you can use either path or key when signing:

> `TAURI_PRIVATE_KEY`: Path or content of your private key

The build command exits with a non-zero exit code:
```
    Bundling [tauri_bundler::bundle::updater_bundle] /Users/tomhill/Developer/projects/pgMagic/pgMagic/src-tauri/target/release/bundle/macos/pgMagic.app.tar.gz (/Users/tomhill/Developer/projects/pgMagic/pgMagic/src-tauri/target/release/bundle/macos/pgMagic.app.tar.gz)
    Finished [tauri_bundler::bundle] 3 bundles at:
        /Users/tomhill/Developer/projects/pgMagic/pgMagic/src-tauri/target/release/bundle/macos/pgMagic.app
        /Users/tomhill/Developer/projects/pgMagic/pgMagic/src-tauri/target/release/bundle/dmg/pgMagic_0.1.2_aarch64.dmg
        /Users/tomhill/Developer/projects/pgMagic/pgMagic/src-tauri/target/release/bundle/macos/pgMagic.app.tar.gz (updater)

       Error [tauri_cli_node] Invalid byte 126, offset 0.
error Command failed with exit code 1.
```

### Reproduction

I followed the steps outlines [here](https://tauri.app/v1/guides/distribution/updater) and:
- produced a keypair with `yarn tauri signer generate -w ~/.tauri/[my-app's-name].key`
- updated the pubkey in `tauri.conf.json`
- set the $TAURI_PRIVATE_KEY env var to the string "~/.tauri/[my-app's-name].key" (which is the path, not the contents)
- run `yarn tauri build`

### Expected behavior

$TAURI_PRIVATE_KEY should work with either a path or the contents of the file OR the documentation on this page https://tauri.app/v1/guides/distribution/updater/#signing-updates should be updated.

### Platform and versions

```text
yarn run v1.22.19
$ tauri info

[✔] Environment
    - OS: Mac OS 13.3.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 18.16.0
    - yarn: 1.22.19
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.1
    - @tauri-apps/api [NPM]: 1.3.0
    - @tauri-apps/cli [NPM]: 1.3.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
✨  Done in 9.80s.
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by amrbashir** [comment]
I think the issue is that you set `TAURI_PRIVATE_KEY` path using `~/path/to/file` which will be read as a string `~/path/to/file` and `~` doesn't have a special meaning in Rust like it does in bash/zsh so you need to use `TAURI_PRIVATE_KEY="$HOME/path/to/file"` where bash/zsh will replace `$HOME` in the string before it stores it in `TAURI_PRIVATE_KEY`

**Comment by hill** [comment]
Ah 🤦 - thanks!

**Comment by bryanjuho** [comment]
Though this issue is closed, I've experienced the same issue with a different cause: 

When performing `cat ~/.tauri/myapp.key` and `cat ~/.tauri/myapp.key.pub`, I've copied the trailing `%` symbol that [Mac's zsh prints out](https://unix.stackexchange.com/questions/167582/why-zsh-ends-a-line-with-a-highlighted-percent-symbol) , thought it was part of the key's contents. 

Hope this helps someone.

**Comment by ultamatt** [comment]
@bryanjuho I just made the same error and you've saved me. 

Also: Check the public key signature in your tauri.conf.json file for the ending '%' character!

Thanks! My specific error for those getting here via Kagi is: 

       Error [tauri_cli_node] Invalid byte 37, offset 348.

**Comment by wflixu** [comment]
> Though this issue is closed, I've experienced the same issue with a different cause:
> 
> When performing `cat ~/.tauri/myapp.key` and `cat ~/.tauri/myapp.key.pub`, I've copied the trailing `%` symbol that [Mac's zsh prints out](https://unix.stackexchange.com/questions/167582/why-zsh-ends-a-line-with-a-highlighted-percent-symbol) , thought it was part of the key's contents.
> 
> Hope this helps someone.

Thank you so much! I just put % in pubkey and got a similar error. After removing % from pubkey field, the build was successful.
![Xnip2024-01-06_11-56-08](https://github.com/tauri-apps/tauri/assets/37231473/345b6aad-306e-455f-8ef2-9568724f0040)

**Comment by luis-cicada** [comment]
@bryanjuho you are a war hero man!! 🚀 🎸
