### ISSUE TITLE
[bug] NSIS auto updater passive mode

### ISSUE THREAD

**Issue by snoww** [tauri-apps/tauri#6955]
### Describe the bug

The current NSIS updater requires user interaction to install the update., even with the passive option in the configuration. 
`"windows": {
        "installMode": "passive"
      }`

### Reproduction

- make nsis build
- make update
- open app and get update notification
- install update
- update not passive

### Expected behavior

update is passive with a progress bar like the msi updater

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64        
    ✔ WebView2: 113.0.1774.35
    ✔ MSVC: 
        - Visual Studio Build Tools 2022
        - Visual Studio Build Tools 2019
    ✔ rustc: 1.67.1 (d5a82bbd2 2023-02-07)
    ✔ Cargo: 1.67.1 (8ecd4f20a 2023-01-10)
    ✔ rustup: 1.25.2 (17db695f1 2023-02-01)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.15.0
    - pnpm: 8.3.1
    - yarn: 1.22.10
    - npm: 9.5.0

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.1
    - @tauri-apps/api [NPM]: 1.3.0
    - @tauri-apps/cli [NPM]: 1.3.1

[-] App
    - build-type: bundle
    - CSP: default-src 'self'; img-src 'self' data: asset: https://asset.localhost; style-src 'self' 'unsafe-inline'; font-src 'self' data:
    - distDir: ../build
    - devPath: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

**Comment by snoww** [comment]
Ok, I did some testing. adding the silent argument for the nsis installer manually in the config makes it install silently
```json
"installerArgs": ["/S"]
```
Maybe the updater isn't adding the silent arg correctly, I didn't check.
However, now that it silently installs, the app does not launch automatically after the update, the user must manually open the app again
This can be fixed by using the callback function `.onInstSuccess`, and check if is silent mode, and exec the app
add this to `installer.nsi`:
```
Function .onInstSuccess
  IfSilent silent done
  silent: 
    Exec '"$INSTDIR\${MAINBINARYNAME}.exe"'
  done:
FunctionEnd
```

**Comment by amrbashir** [comment]
`passive` mode is not supported by `NSIS` you need to use `quiet` mode instead, I will be updating the docs and add running the app after it has been updated.

**Comment by FabianLars** [comment]
Shouldn't we make "passive" match "silent" then instead? Kinda weird to have the passive option not being passive (as in no user action required)

Edit: especially considering that it's the default setting.

**Comment by amrbashir** [comment]
`passive` means that there will be GUI but no user interaction is required, while in `silent`, no gui will be shown at all.

**Comment by FabianLars** [comment]
Yes I know that. I just think that we should automatically fallback to the silent option if passive is used (for the nsis target).
To me silent behavior is closer to passive behavior than an installer that requires user interaction is - in the context of the updater of course.

Edit: silent = quiet - dunno which one we use in the config rn

**Comment by amrbashir** [comment]
I might be able to implement `passive` mode on NSIS, just got busy with something else atm, let me reopen and see how it goes.
