### ISSUE TITLE
[feat] Allow indexeddb databases to be stored in the AppImage bundle

### ISSUE THREAD

**Issue by Risto-Stevcev** [tauri-apps/tauri#6993]
### Describe the problem

The indexeddb databases are stored globally on the system (`~/.local/share/<bundle-identifier>/databases/indexeddb/**/*`), rather than in the AppImage bundle itself.

### Describe the solution you'd like

I don't know if this is possible, but it would be nice to have the option to store the indexeddb databases in the AppImage bundle itself, rather than in the `~/.local/share/<bundle-identifier>/databases/indexeddb/**/*` path.

### Alternatives considered

One workaround might be to just open a different database name, maybe as a UUID or something to minimize the possibility of a name clash, but ideally it would all be self-contained rather than global to guarantee that there isn't a namespace clash.

### Additional context

The use cases would be similar to those of sqlite. In my case, I want to be able to write an application (ie: `com.foo`), where the database is in the bundle itself, because the application is supposed to be standalone and used in multiple different contexts on the same machine. 
I'm not sure if this feature request is related to #6992.

**Comment by FabianLars** [comment]
The appimage contents are write only (or at least should be resetted on each app start) so i'd tend to not make this change (i wonder how webkitgtk handles it if the paths we tell it are read-only 🤔 i could kinda imagine that it'd just crash as soon as it tries to write something x) )

Btw, this also applies to sqlite and plain text files for that matter.

> to minimize the possibility of a name clash

Yeah, that's why the bundle _identifier_ should be _unique_ but of course there's always a risk of a clash without a random generator of some kind...

**Comment by Risto-Stevcev** [comment]
I don't this this issue should be closed. Let me explain.

> The appimage contents are write only (or at least should be resetted on each app start) so i'd tend to not make this change (i wonder how webkitgtk handles it if the paths we tell it are read-only thinking i could kinda imagine that it'd just crash as soon as it tries to write something x) )
> Btw, this also applies to sqlite and plain text files for that matter.

That's not quite true. There's portable mode: https://docs.appimage.org/user-guide/portable-mode.html
By allowing an option to keep the indexeddb files in `$CONFIG`/[configDir](https://tauri.app/v1/api/js/path/#configdir) (or `$HOME`/[homeDir](https://tauri.app/v1/api/js/path/#homedir)), you could use the same application on the same system for multiple use cases.

> Yeah, that's why the bundle identifier should be unique but of course there's always a risk of a clash without a random generator of some kind...

It's not the issue with the bundle identifier being unique, it's about being able to use the same application (which would have the same bundle identifier) on the same system (ie linux) for multiple use cases. The state (the indexeddb that's used) is different for the different use cases.

I can workaround the issue if I'm using sqlite by using the portable mode, but I can't do a workaround if I need to use indexeddb (ie for [emscripten](https://emscripten.org/docs/api_reference/Filesystem-API.html#filesystem-api-idbfs)) with portable mode.

**Comment by FabianLars** [comment]
Interesting, didn't know about the portable mode!

That said, since this still just creates a folder _next_ to the appimage, you can change the database location yourself by setting the data_directory when you create the window: <https://docs.rs/tauri/latest/tauri/window/struct.WindowBuilder.html#method.data_directory>. So as far as i can see this would cover this usecase, right?

**Comment by Risto-Stevcev** [comment]
Yes, thank you! that'll do the trick :)

> That said, since this still just creates a folder next to the appimage

That's true, it's a limitation for sure, but I think this could be resolved by something like:

1. Create a "portable" `tauri-app_0.0.0_amd64.AppImage.portable.squashfs` squashfs file that contains the two files: `tauri-app_0.0.0_amd64.AppImage`, and it's empty config folder `tauri-app_0.0.0_amd64.AppImage.config/`.
2. Create a shell script to _run_ a `.AppImage.portable.squashfs` formatted file. The script will:
a. Mount the squashfs filesystem in a hidden directory (ie: `./.appimage`) and run the AppImage inside as a subprocess. It can follow a procedure like [this](https://unix.stackexchange.com/a/679365) in order to make the squashfs read/write.
b. Trap the signals so that once the process is killed, either by an error or by a normal exit, the script will remake the `squashfs` with the written changes.

I think that'll work for any kind of AppImage, not just Tauri apps
