### ISSUE TITLE
WEB API

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#70]
**Describe the bug**
The WEB API does not work, even on external sites served over HTTPS.

**Expected behavior**
In 'secure' contexts such as `file://`, `https://` and `localhost`, we would expect that the web api would be available.

**Platform:**
All

**Additional context**
This is more to do with the web-view library - and probably webviews themselves, but it is a major concern that we need to resolve - or consider building a shimming API that offloads these tasks to the underlying OS.

Thanks to @rihardsgravis for raising the issue.

**Comment by nothingismagick** [comment]
See this: https://github.com/Boscop/web-view/issues/95

**Comment by nklayman** [comment]
Well the good news is the secure context issue is solved with wry, but permissions are automatically denied (at least on Linux). See https://github.com/tauri-apps/wry/issues/81

**Comment by nothingismagick** [comment]
I am closing this for now, as it is technically outside of Tauri's control (and will need to be resolved by wry)
