### ISSUE TITLE
[bug] DOMContentLoaded not triggered in production

### ISSUE THREAD

**Issue by xdewx** [tauri-apps/tauri#7002]
### Describe the bug

DOMContentLoaded not triggered in production

### Reproduction

1. open [https://github.com/4tst/tauri-plugins/tree/bug/DOMContentLoaded](https://github.com/4tst/tauri-plugins/tree/bug/DOMContentLoaded)
2. follow `README.md`

### Platform and versions

```text
windows11 
1.3.0
```

**Comment by FabianLars** [comment]
From my testing with your repo it looks like it _is_ fired but way too early for the console to be attached already so the console.log gets lost. If i sent it to the rust side (after disabling the `windows_subsystem` stuff in main.rs so i could print something to the native terminal) i was able to receive the message just fine.

main.rs file for you to confirm:
```rs
/* #![cfg_attr(
    all(not(debug_assertions), target_os = "windows"),
    windows_subsystem = "windows"
)] */

use tauri::Manager;

#[tauri::command]
fn print(msg: String) -> Result<(), ()> {
    dbg!(msg);
    Ok(())
}

fn main() {
    tauri::Builder::default()
        .setup(|app| {
            #[cfg(debug_assertions)] // only include this code on debug builds
            {
                let window = app.get_window("main").unwrap();
                window.open_devtools();
                // window.close_devtools();
            }
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![print])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```
then in js do `invoke('print', { msg: 'DOMContentLoaded' })` in your DOMContentLoaded event handler.
