### ISSUE TITLE
[bug] tauri-cli 2.0.0-alpha.9 cannot be used

### ISSUE THREAD

**Issue by adminSxs** [tauri-apps/tauri#7003]
### Describe the bug
Os: win10
cargo tauri --version
```
tauri-cli 2.0.0-alpha.9
```

### Platform and versions

```text
cargo tauri info


Error `tauri.conf.json` error on `tauri`: Additional properties are not allowed ('allowlist', 'updater' were unexpected)
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by FabianLars** [comment]
The last alpha version was quite a huge change with many things being moved to the plugins repo. I'd suggest not upgrading just yet tbh.

That said here's an export of our internal wip upgrade guide: https://gist.github.com/FabianLars/676829d4c9ccb0a25133bd7d715a3c28
