### ISSUE TITLE
[bug] transform: scale(1) causes layout changes

### ISSUE THREAD

**Issue by Illyism** [tauri-apps/tauri#7006]

**Comment by FabianLars** [comment]
This should not be something we have any kind of control over. If you try the same in Safari it should behave exactly the same.

Actually, i can see the very same behavior in Firefox too with your reproduction. I (or we) can't help with general css issues/questions here though, so i'll have to close this issue.

Thanks for reaching out nonetheless :)

**Comment by Illyism** [comment]
Fix was to use position: relative in the content above
