### ISSUE TITLE
[feat] Provide @tauri-apps/cli-win32-arm64-msvc NPM package

### ISSUE THREAD

**Issue by NMNMCC** [tauri-apps/tauri#7015]
### Describe the problem

Nowadays I can only manually compile Tauri everytime.

### Describe the solution you'd like

Provide @tauri-apps/cli-win32-arm64-msvc NPM package

**Comment by FabianLars** [comment]
We're waiting for https://github.com/briansmith/ring to release a [new version](https://github.com/briansmith/ring/issues/1551) that can be built on windows+arm.
