### ISSUE TITLE
[bug] Windows snaps to wrong place after navigator.share() opened and dragging starts

### ISSUE THREAD

**Issue by Illyism** [tauri-apps/tauri#7019]
### Describe the bug

https://github.com/tauri-apps/tauri/assets/304283/c003d5dd-deaa-4b04-818f-ae88524632df

### Reproduction

1. Use a `data-tauri-drag-region` region somewhere
2. Add a `<button @click="share">share</button>`
3. Use the `navigator.share` API to open a menu:
```js
async function share() {
    await navigator.share({
        title: "Tauri",
        text: "Hello world!",
        url: "https://example.com",
    })
}
```

4. Start dragging the drag region

### Expected behavior

I'd expect the dragging to behave normally, but it snaps the window away at times depending on where you click in the window.

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.3.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 19.1.0
    - pnpm: 8.5.1
    - yarn: 1.22.19
    - npm: 8.19.3

[-] Packages
    - tauri [RUST]: 1.2.4
    - tauri-build [RUST]: 1.2.1
    - wry [RUST]: 0.23.4
    - tao [RUST]: 0.15.8
    - @tauri-apps/api [NPM]: 1.3.0
    - @tauri-apps/cli [NPM]: 1.3.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

### Additional context

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

**Comment by pewsheen** [comment]
https://github.com/tauri-apps/tao/blob/dc951ae2780a10051e8efb69b6a926b3ea376c89/src/platform_impl/macos/window.rs#L842

It looks like the `[NSApp currentEvent]` will return a private `NSEvent`(0x15, ProcessNotification) with a wrong cursor position(x will always be 0) when closing the share dialog.

I'm not sure if this is the only event that will give us the wrong cursor position. Maybe we can just capture this event and replace it with a dummy click event to perform the drag.

ref: https://github.com/servo/core-foundation-rs/issues/401
