### ISSUE TITLE
[bug] tauri-utils AppImage check fails on NixOS

### ISSUE THREAD

**Issue by leo60228** [tauri-apps/tauri#7046]
### Describe the bug

While attempting to upstream a workaround in NixOS for #4930, I discovered that attempting to run a Tauri-built AppImage on NixOS fails on startup:
```
thread 'main' panicked at '`APPDIR` or `APPIMAGE` environment variable found but this application was not detected as an AppImage; this might be a security issue.', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-utils-1.2.1/src/lib.rs:202:11
```

### Reproduction

```
$ nix-shell -p 'appimage-run.override { extraPkgs = pkgs: [ pkgs.libthai ]; }' --run "appimage-run ./${TAURI_APP}.AppImage"
```

### Expected behavior

The application successfully starts.

### Platform and versions

```text
This AppImage comes from a third party.
```

### Stack trace

```text
thread 'main' panicked at '`APPDIR` or `APPIMAGE` environment variable found but this application was not detected as an AppImage; this might be a security issue.', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-utils-1.2.1/src/lib.rs:202:11
stack backtrace:
   0:     0x55c475f9c26c - <unknown>
   1:     0x55c475e3cd2e - <unknown>
   2:     0x55c475f706b4 - <unknown>
   3:     0x55c475f9d7af - <unknown>
   4:     0x55c475f9d3af - <unknown>
   5:     0x55c475f9e419 - <unknown>
   6:     0x55c475f9dec4 - <unknown>
   7:     0x55c475f9de56 - <unknown>
   8:     0x55c475f9de41 - <unknown>
   9:     0x55c475c3f182 - <unknown>
  10:     0x55c475e01163 - <unknown>
  11:     0x55c475c84816 - <unknown>
  12:     0x55c475e03fa1 - <unknown>
  13:     0x7fce5b43dace - __libc_start_call_main
  14:     0x7fce5b43db89 - __libc_start_main@@GLIBC_2.34
  15:     0x55c475c55b9e - <unknown>
  16:                0x0 - <unknown>
```

### Additional context

This check was introduced to prevent an attacker with control over environment variables from gaining code execution, with the example given in the audit being an attacker with control over the .zshrc. I strongly question whether this is a realistic threat model, especially due to the existence of `LD_PRELOAD` and similar environment variables.

This was also reported in Nixpkgs as https://github.com/NixOS/nixpkgs/issues/200955. The proposed resolution there is spoofing /proc/self/exe. I think this should likely be fixed in Tauri, however.

**Comment by beeb** [comment]
This is also causing me issues with an AppImage on nixOS.
