### ISSUE TITLE
[feat] sync webview theme with window theme on Android

### ISSUE THREAD

**Issue by FlysoftBeta** [tauri-apps/tauri#7052]
### Describe the problem

I am building an android app using tauri, and there is a white screen on start, it looks like the following:
![Screenshot_20230524_230429](https://github.com/tauri-apps/tauri/assets/49718840/e0cab551-e55b-487c-b440-6b1897f43066)
but actually the webpage supports dark mode, after the webview is loaded, the background turns dark.

### Describe the solution you'd like

I would like to make the app theme match with the webpage, not only the background color, but also the action bar's color 
![Screenshot_20230524_231230](https://github.com/tauri-apps/tauri/assets/49718840/cd0219b3-156b-4d83-917d-d98022747421).

### Additional context

A pr with similar functionality, but it's a Windows implementation: https://github.com/tauri-apps/tauri/pull/5874

**Comment by amrbashir** [comment]
you can control the status bar colors and behavior by modifying `gen/android/app/src/main/res/values/themes.xml` and call the needed kotlin code in `gen/android/app/src/main/java/com/tauri/tauri-app/ManiActivity.kt`, see https://stackoverflow.com/questions/29311078/android-completely-transparent-status-bar for more info

**Comment by George3d6** [comment]
@amrbashir it is non obvious (to anyone that isn't already and android application developer that uses Kotlin) what "call the needed kotlin code min MainActivity.kt" means. Would it not be better to have this somewhere in the docs or, at least, provide a complete answer in here as to how to modify the status bar appearance ? It seems like a rather common usecase
