### ISSUE TITLE
[docs] Missing "full filesystem example" using http requests

### ISSUE THREAD

**Issue by erikpa1** [tauri-apps/tauri#7059]
Hi, 

I would like to ask for example documentation update on my use case.

I have hybrid 3D application, created with three js. App is multiplatform Desktop/Web. The app structure is based on "projects" where one folder is one project, with its assets, databases, files (images, videos, point clouds, fbx / glb files,...) One project can have 30 GB. 

The projects can be located anywhere on PC, user has structure like:

```
C:\
  - Program Files\
  - ProjectData\
  
- D:\
  - Documents\
  - Projects\
  - Music\
  - ProjectData\
 
- E:\
  - Videos\
  - Games\
  - ProjectData\
```

Because I use a lot of external libraries, often they works like following

```
new three.FileLoader("/api/path/file.json")
new GltfLoader().load("/api/models/model.gltf")
```

So as you can see, I can work only with file paths synchronously (no async await), some libraries use for example folder + they compute file path like   new PanoramaLoader().load(".api/pano/"), which hide "chunk1.png" "chunk2.png"...

I need to configure tauri, to be able load this files anywhere. No dialog picking, nothing similar, when user,

just when I write    <img src="D:/Work/MyProject/preview.png"/> or new 

GltfLoader().load("D:/Work/MyProject/preview.png") it has to work.

I know tauri has some security standard, but this is basic workflow which app like Autocad, Autodesk, Blender, Unity, Unreal Engine uses, Visual Studio,... uses, and I want use it.

**Comment by FabianLars** [comment]
https://github.com/tauri-apps/tauri/discussions/7122
