### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by MeisterTea** [tauri-apps/tauri#706]
Hi, I am getting a generic error on the bundle process on linux

* rustc 1.44.0
* tauri-bundler is installed system wise
* webkit2gtk is installed
* Archlinux 5.6.15-arch1-1 kernel

```
 DONE  Build complete. The dist_tauri/bundled directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html

 app:spawn Running "cargo tauri-bundler --features embedded-server --release" +0ms

   Compiling app v0.1.0 (/home/chell/Sources/vue/tauri/my-tauri-app/src-tauri)
   Compiling tauri v0.6.0
    Finished release [optimized] target(s) in 7.80s
    Bundling app_0.1.0_amd64.deb
    Bundling "/home/chell/Sources/vue/tauri/my-tauri-app/src-tauri/target/release/bundle/appimage/app.AppImage"
error: Shell Scripting Error:`error running build_appimage.sh`

 app:spawn Command "cargo" failed with exit code: 1 +1ms

 app:tauri (runner) ⚠️  [FAIL] Cargo CLI has failed +0ms

 app:tauri Shutting down tauri process... +2ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nothingismagick** [comment]
This is not likely to be a problem with the vue-cli-plugin. We've been working on appimage, but I thought we had all the bugs ironed out. :(

**Comment by rajivshah3** [comment]
Have you tried installing `squashfs-tools`? It looks like `mksquashfs` is required. I was able to reproduce the error before installing it

**Comment by MeisterTea** [comment]
> Have you tried installing `squashfs-tools`? It looks like `mksquashfs` is required. I was able to reproduce the error before installing it

it does fix the issue, thx
