### ISSUE TITLE
[bug] Qwik: Serviceworker not installed correctly

### ISSUE THREAD

**Issue by qwerty084** [tauri-apps/tauri#7070]
### Describe the bug

After creating a new tauri + qwik app following the official guide and creating a production build with --debug flag, i get the following error in the console:

TypeError: serviceWorker.register() must be called with a script URL whose protocol is either HTTP or HTTPS

After adding SSG mode to qwik, i got the following notice: " You must change the 'origin' url under staticAdapter inside 'vite.config.ts'"
The default value is: "origin: 'https://yoursite.qwik.dev'", i tried setting it to some other urls, but all resulted in the same error after building the app.

What is the correct value for the origin property or did i make any other mistake (im new to qwik...)?

### Reproduction

1. Follow https://tauri.app/v1/guides/getting-started/setup/qwik
2. npm run tauri build -- --debug
3. Start app and check console output

### Expected behavior

The qwik service worker should be installed without errors

### Platform and versions

```text
[✔] Environment
    - OS: Ubuntu 22.04 X64
    ✔ webkit2gtk-4.0: 2.38.6
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.68.0 (2c8cc3432 2023-03-06)
    ✔ Cargo: 1.68.0 (115f34552 2023-02-26)
    ✔ rustup: 1.25.2 (17db695f1 2023-02-01)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 19.8.1
    - npm: 9.6.5

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.3.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:5173/
    - bundler: Vite
```

### Stack trace

```text
TypeError: serviceWorker.register() must be called with a script URL whose protocol is either HTTP or HTTPS
```

**Comment by qwerty084** [comment]
I think setting the origin to 'https://tauri.localhost' should do the job (this is the url from other resources used by the app), but for some reason it doesn't work...
When running npm run preview, to view the app in the browser the service worker is installed without errors.

**Comment by FabianLars** [comment]
> I think setting the origin to 'https://tauri.localhost/' should do the job (this is the url from other resources used by the app), but for some reason it doesn't work...

This is only the origin on Windows. macOS and Linux use `tauri://localhost` and switching to a http protocol is not possible without an actual http server, like with the [localhost plugin](https://github.com/tauri-apps/plugins-workspace/tree/v1/plugins/localhost) (ref https://github.com/tauri-apps/wry/issues/389).

That said, i wonder if this is actually an issue like, what does qwik use the service worker for? Because at least the demo app seems to work completely fine...

> After creating a new tauri + qwik app following the **official** guide

Can't wait for the new docs website where we will make this more clear, but the qwik guide is not really official, but more like a community-provided guide.

**Comment by qwerty084** [comment]
Oh okay, i will try the localhost plugin.

As far as i know qwik uses the service worker to prefetch and cache JavaScript which might be needed soon, so that the network request don’t slow down the app. So using qwik + tauri without a service worker probably isn’t a big issue, since fetching the JavaScript is instant anyway without a preload/cache. But maybe the service worker does more idk.

**Comment by FabianLars** [comment]
Well, there isn't anything we can do i think. So i'll go ahead and close this. At least it's now documented here with a few pointers so, thanks for the report :) (and we can reopen it in case there will be more issues)

**Comment by qwerty084** [comment]
The service worker works with the localhost plugin, when you set the origin to http://localhost. I will do some more testing, if the service worker is required for a tauri application and submit a pr for the docs if necessary.

**Comment by itsyashsahu** [comment]
Hi @qwerty084 ,
I am trying to register the firebase-messaging.js service worker. Could you please explain how did you get this work. 
I have setup the localhost plugin and My service worker is registered but gives the error NotAllowedError : permission denied. 
![image](https://github.com/user-attachments/assets/e66859a5-63ea-4f05-9964-ae0762aecb97)
