### ISSUE TITLE
minWidth has no effect without minHeight in tauri windows config

### ISSUE THREAD

**Issue by Picorims** [tauri-apps/tauri#7075]
### Describe the bug

When configuring the minWidth property in tauri's windows configuration, it does not take effect until a minHeight is defined as well. Here is an example.
![image](https://github.com/tauri-apps/tauri/assets/41078963/155b0a24-3d15-4f7b-b1df-3793f80564e4)

### Reproduction

1. Define minWidth in the windows configuration (making sure minHeight is not set).
2. Obersve the window being resizable beyond the minimum value.
3. Define minHeight in the windows configuration, keeping minWidth untouched.
4. Observe minWidth taking effect and effectively constraining window resizing.

### Expected behavior

The window is constrained to not be resizable beyond the minWidth value, even if the minHeight value is not defined.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 113.0.1774.57
    ✔ MSVC:
        - Visual Studio Community�2019
        - Visual Studio Build Tools 2017
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 16.13.1
    - npm: 9.6.6

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.1
    - @tauri-apps/api [NPM]: 1.3.0
    - @tauri-apps/cli [NPM]: 1.3.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Upstream issue: https://github.com/tauri-apps/tao/issues/138

**Comment by Xyndra** [comment]
same problem here
