### ISSUE TITLE
[bug] path not allowed on the configured scope (at linux)

### ISSUE THREAD

**Issue by xdewx** [tauri-apps/tauri#7076]
### Describe the bug

ok at windows, not at linux

### Reproduction

1. open [https://github.com/4tst/tauri-issues/tree/bug/fs-scopes](https://github.com/4tst/tauri-issues/tree/bug/fs-scopes)
2. follow the `readme.md`

### Platform and versions

```text
1. linux debian
2. tauri 1.2.6
```

**Comment by FabianLars** [comment]
After following the readme instructions the app worked fine for me, no errors... Can you try it again after upgrading the js and rust dependencies to the latest version?

**Comment by xdewx** [comment]
> After following the readme instructions the app worked fine for me, no errors... Can you try it again after upgrading the js and rust dependencies to the latest version?

after upgrading, error still here. did you run tauri under linux and use branch `bug/fs-scopes`
![图片](https://github.com/tauri-apps/tauri/assets/20438962/a13cb4c5-c13c-4744-8ef1-9a7d27a85e12)
![图片](https://github.com/tauri-apps/tauri/assets/20438962/9face92e-b0a0-4eb7-82eb-5b956ebc81b4)

and i found:
1. if appDataDir not exist before, when run pnpm tauri dev, the error happens, but appDataDir is created correctly
2. delete appDataDir after step 1, then refresh the page, then no errors and appDataDir is created
3. refresh again after step2, the error happens again
