### ISSUE TITLE
Icons precisely bootstrap-icons are not displayed in compiled app

### ISSUE THREAD

**Issue by shellking4** [tauri-apps/tauri#7083]
### Describe the bug

I've built an app with tauri using sveltekit.
The app uses bootstrap icons for some menus and the alike.

When I run the app in the browser the icons are displayed...even in build version. But then I build the desktop app and the icons won't show up. I'm kind of lost. I plan on building a mobile app with the project so I'm using the alpha tauri by the way. Don't know if it's that the issue. Where should look at to fix this ?

I'm on ubuntu 20.04. 

### Reproduction

set up an a tauri app with sveltekit or whatever frontend framework, integrate bootstrap-icons and build the app for desktop platforms

### Expected behavior

Icons should show up, behavior should be same as when running in browser

### Platform and versions

```text
Environment
  › OS: Ubuntu 20.04 X64
  › Node.js: 18.12.0
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.67.1
  › cargo: 1.67.1
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.2
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 2.0.0-alpha.9,
  › tauri-build [RUST]: 2.0.0-alpha.5,
  › tao [RUST]: 0.19.1,
  › wry [RUST]: 0.28.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:5173/
  › framework: Svelte
  › bundler: Vite

App directory structure
  ├─ src
  ├─ build
  ├─ node_modules
  ├─ src-tauri
  ├─ static
  └─ .svelte-kit
```

**Comment by FabianLars** [comment]
Did you also test it in epiphany (also known as gnome web)? That's a browser using webkitgtk which is what tauri uses as the webview on Linux.

Also, try a debug build (`npm run tauri build -- --debug` - output in `target/build/`) and check the devtools console and other tabs for any issues. Alternatively to the debug build you can also add the `"devtools"` feature flag to the tauri dependency in Cargo.toml to enable the devtools for release builds (the ones in `target/release/`)

**Comment by shellking4** [comment]
Thank you for your reply @FabianLars. On your advice, I've tested the app in epiphany and the icons are displayed. I'm still in the process of compiling with -- --debug to get more insight on the issue.

**Comment by shellking4** [comment]
Finally I built the app on mobile and icons are properly displayed. Since my main concern is to have a mobile app, I'm already quite well served with this. Don't understand yet why the icons are not displayed on desktop. May be it's some environment specific issue. I doubt it's related to tauri. So I'm closing this issue
