### ISSUE TITLE
[feat] Append mode for writeTextFile

### ISSUE THREAD

**Issue by CKylinMC** [tauri-apps/tauri#7092]
### Describe the problem

For now, `writeTextFile` always overwrite the file contents. If I want to append some content to a file I must read it all and then write back, that painful if the file is big or write too much.

### Describe the solution you'd like

Add an option into second parameter, like `{"mode": "w" /* "a" */}`, default "w" so nothing need to change for existed projects, and if anyone wants to append content into a file, just set `mode` to `a`.

**Comment by FabianLars** [comment]
In case we won't add it via a v1 minor release, the v2 implementation will be tracked here https://github.com/tauri-apps/plugins-workspace/issues/2.

**Comment by CKylinMC** [comment]
@FabianLars Well, thanks!

------

Btw for anyone see this issue and need this feature for now, could use this solution, it works for me:

Add this into main.rs

```rust
use std::fs::OpenOptions;
use std::io::prelude::*;

#[tauri::command]
fn append_text_file(path: String, content: String) {
  let mut file = OpenOptions::new()
      .write(true)
      .append(true)
      .create(true)
      .open(&path)
      .expect("Failed to open file");

  file.write(content.as_bytes()).expect("Failed to write file");
}
```

and modify the main function:
```rust


fn main() {
  tauri::Builder::default()
   /* ... */
    .invoke_handler(tauri::generate_handler![append_text_file]) //add this line
    /* ... */
}
```

when need to call it from JS, do this:

```javascript
import { invoke } from '@tauri-apps/api/tauri';

// simple wrapper function
export function appendToFile(path, content) {
    return invoke('append_text_file', {path,content});
}
```

Just call `appendToFile(path, content)` like calling any other rust function by “invoke API”.
