### ISSUE TITLE
[bug] The "tauri://file-drop" event is not working on the Windows platform.

### ISSUE THREAD

**Issue by cct124** [tauri-apps/tauri#7094]
### Describe the bug

I am writing an image compression software and want to provide the functionality of dragging and dropping files onto the window to compress them. Since the compression program is written in Rust, I need to obtain the file path and cannot use the browser's drag and drop file feature. I am not sure if I am doing something wrong or if this is a bug in Tauri. Can someone help me solve this problem? Thank you.

I have written a demo to showcase the issue I am facing.

![13-52-22](https://github.com/tauri-apps/tauri/assets/47600522/71f8637d-fc40-4ee6-be37-2e018d78fd4e)

App.vue
```vue
<template>
  <div class="app" @dragover="handleDragOver" @drop="handleFileSelect"></div>
</template>

<script setup lang="ts">
import * as event from "@tauri-apps/api/event";

event.listen("tauri://file-drop", (e) => {
  console.log("Tauri event", e);
});

event.listen("tauri://file-drop-hover", (e) => {
  console.log("Tauri event", e);
});

event.listen("tauri://file-drop-cancelled", (e) => {
  console.log("Tauri event", e);
});

// 处理拖放区域的dragover事件
function handleDragOver(event: DragEvent) {
  event.stopPropagation();
  event.preventDefault();
}

// 处理拖放区域的drop事件
function handleFileSelect(event: DragEvent) {
  event.stopPropagation();
  event.preventDefault();
  if (event.dataTransfer) {
    for (const file of event.dataTransfer.files) {
      console.log("Browser event", file.name, file.size, file.type);
    }
  }
}
</script>

<style scoped>
.app {
  width: 100vw;
  height: 100vh;
  background-color: #efefef;
}
</style>
```
tauri.conf.json
```json
{
  "build": {
    "beforeBuildCommand": "npm run build",
    "beforeDevCommand": "npm run dev",
    "devPath": "http://localhost:5173",
    "distDir": "../dist"
  },
  "package": {
    "productName": "tauri-drop-demo",
    "version": "0.1.0"
  },
  "tauri": {
    "allowlist": {
      "all": true
    },
    "bundle": {
      "active": true,
      "category": "DeveloperTool",
      "copyright": "",
      "deb": {
        "depends": []
      },
      "externalBin": [],
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "identifier": "com.tauri.dev",
      "longDescription": "",
      "macOS": {
        "entitlements": null,
        "exceptionDomain": "",
        "frameworks": [],
        "providerShortName": null,
        "signingIdentity": null
      },
      "resources": [],
      "shortDescription": "",
      "targets": "all",
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "security": {
      "csp": null
    },
    "updater": {
      "active": false
    },
    "windows": [
      {
        "fullscreen": false,
        "height": 600,
        "resizable": true,
        "title": "tauri-drop-demo",
        "width": 800,
        "fileDropEnabled": false
      }
    ]
  }
}

```

My English is not good and this is all translated in chatGPT

### Platform and versions

```text
Environment
  › OS: Windows 10.0.19045 X64
  › Webview2: 113.0.1774.57
  › MSVC:
      - Visual Studio ���ɹ��� 2022
  › Node.js: 16.15.1
  › npm: 8.11.0
  › pnpm: 8.2.0
  › yarn: 1.22.15
  › rustup: 1.25.2
  › rustc: 1.68.0
  › cargo: 1.68.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.3.0
  › tauri [RUST]: 1.3.0,
  › tauri-build [RUST]: 1.3.0,
  › tao [RUST]: 0.16.2,
  › wry [RUST]: 0.24.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › framework: Vue.js
  › bundler: Vite

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

**Comment by FabianLars** [comment]
`tauri://file-drop` events only work if you have `fileDropEnabled` enabled, in your tauri.conf.json it's still set to `false`.

**Comment by cct124** [comment]
> `tauri://file-drop` events only work if you have `fileDropEnabled` enabled, in your tauri.conf.json it's still set to `false`.

I have enabled fileDropEnabled, but it doesn't seem to be working. When I drag a file to the window, the cursor changes to a prohibited icon, but releasing the mouse doesn't trigger any events. Did I do something wrong? Thank you.

![17-57-45](https://github.com/tauri-apps/tauri/assets/47600522/67c08145-c163-44a9-8765-bf99d9e271ab)

![image](https://github.com/tauri-apps/tauri/assets/47600522/46a77e35-f56e-4d5f-b469-e67df306e9d2)

**Comment by FabianLars** [comment]
I doubt that this is the issue because these events shouldn't be triggered in the first place after enabling fileDropEnabled but can you try again after commenting out the `event.stopPropagation();` and `event.preventDefault();` lines?

**Comment by cct124** [comment]
> I doubt that this is the issue because these events shouldn't be triggered in the first place after enabling fileDropEnabled but can you try again after commenting out the `event.stopPropagation();` and `event.preventDefault();` lines?

I have removed all the events bound to a div tag, but the behavior is still the same as before.

![18-32-57](https://github.com/tauri-apps/tauri/assets/47600522/90b43030-8a38-426b-95fb-d0ee468ef013)

![image](https://github.com/tauri-apps/tauri/assets/47600522/792ffdbc-2381-42f3-9290-0c4b876dc7da)

I have uploaded my demo code to Github. You can access the following link to view it: https://github.com/cct124/tauri-drop-demo

Thank you.

**Comment by FabianLars** [comment]
Your repo works fine for me: 
![grafik](https://github.com/tauri-apps/tauri/assets/30730186/ef6bc4de-1f48-4ebe-82e3-dfa9ca99c4dd)

**Comment by cct124** [comment]
> Your repo works fine for me: ![grafik](https://user-images.githubusercontent.com/30730186/242252447-ef6bc4de-1f48-4ebe-82e3-dfa9ca99c4dd.png)

It's strange. Could it be related to the platform I'm using?😭

**Comment by cct124** [comment]
> Your repo works fine for me: ![grafik](https://user-images.githubusercontent.com/30730186/242252447-ef6bc4de-1f48-4ebe-82e3-dfa9ca99c4dd.png)

I think I've found the reason. Running the `cargo tauri dev` command in the terminal within `VScode` causes issues where drop events cannot be triggered. However, when running the terminal program separately, Tauri behaves normally. I suspect this may be related to Windows permissions. The problem has been resolved, and I appreciate your help.

![10-44-15](https://github.com/tauri-apps/tauri/assets/47600522/5c82ca87-7c95-4383-a5b1-7c87fb5ea751)

Abnormal startup method.
![image](https://github.com/tauri-apps/tauri/assets/47600522/c11cfcd3-d15c-4362-96e4-544c633bb8e9)

normal
![image](https://github.com/tauri-apps/tauri/assets/47600522/ce9c5604-2198-4357-8716-9028fab9ea5a)

**Comment by davehorner** [comment]
The demo does not compile for me.
```
   Compiling ppv-lite86 v0.2.17
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> C:\Users\dhorner\.cargo\registry\src\index.crates.io-6f17d22bba15001f\proc-macro2-1.0.59\src\lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0635`.
   Compiling windows_x86_64_msvc v0.42.2
error: could not compile `proc-macro2` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
```

tauri://file-drop events do not work on windows.  this ticket should still be open.

**Comment by shipurjan** [comment]
> I think I've found the reason. Running the `cargo tauri dev` command in the terminal within `VScode` causes issues where drop events cannot be triggered. However, when running the terminal program separately, Tauri behaves normally. I suspect this may be related to Windows permissions. The problem has been resolved, and I appreciate your help.

Nice find, I had the similar issue and I probably wouldn't have found it. I ran the demo on Windows 10 and drag-and-drop works when I use Git Bash, but when I use cmd or Git Bash in VSCode it doesn't work.
