### ISSUE TITLE
[bug] Tauri Window is being considered as an input argument when using the tauri::command macro which is causing issues

### ISSUE THREAD

**Issue by Jamzy01** [tauri-apps/tauri#7095]
### Describe the bug

I have a tauri command that takes in the current window, a shared state object and one input in as arguments, performs an action and doesn't return anything. Although the rust compiler shows an error highlighting the _#[tauri::command]_ telling me that
```
error[E0277]: the trait bound `Window: Deserialize<'_>` is not satisfied
   --> src\file_system_location\file_system_watcher\mod.rs:102:1
    |
102 | #[tauri::command]
    | ^^^^^^^^^^^^^^^^^ the trait `Deserialize<'_>` is not implemented for `Window`
...
117 |     tauri_builder.invoke_handler(tauri::generate_handler![watch_path, unwatch_path])
    |                                  -------------------------------------------------- in this macro invocation
    |
    = help: the following other types implement trait `Deserialize<'de>`:
              <&'a [u8] as Deserialize<'de>>
              <&'a serde_json::raw::RawValue as Deserialize<'de>>
              <&'a std::path::Path as Deserialize<'de>>
              <&'a str as Deserialize<'de>>
              <() as Deserialize<'de>>
              <(T0, T1) as Deserialize<'de>>
              <(T0, T1, T2) as Deserialize<'de>>
              <(T0, T1, T2, T3) as Deserialize<'de>>
            and 251 others
    = note: required for `Window` to implement `CommandArg<'_, T>`
    = note: this error originates in the macro `__cmd__watch_path` which comes from the expansion of the macro `tauri::generate_handler` (in Nightly builds, run with -Z macro-backtrace for more info)
```
![image](https://github.com/tauri-apps/tauri/assets/103490514/9eea7b2d-aa72-4a75-8911-e9ae8bf2a1b5)
(screenshot of rust-analyzer info)

### Reproduction

```rs
#[tauri::command]
pub fn unwatch_path(window: Window, state: tauri::State<AppState>, path: FileSystemLocation) {
    state.directory_watcher().unwatch_path(window, &path);
}
```

### Expected behavior

I am not confident on the inner workings of Tauri, although I assume the _window_ and _state_ parameters are not considered "input" parameters such that they are not sent from rust to javascript and vice versa therefore they do not need to implement Serialize, Deserialize etc. This is why I am confused why this wouldn't work, as the compiler complains that Window doesn't implement Deserialize when it shouldn't need to. I expected the above code to compile without error, although it didn't, and I am unsure of exactly why.

### Platform and versions

```text
Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 113.0.1774.57
  › MSVC:
      - Visual Studio Community 2022
  › Node.js: 16.16.0
  › npm: 9.1.3
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.68.0-nightly
  › cargo: 1.68.0-nightly
  › Rust toolchain: nightly-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.2.2 (outdated, latest: 1.3.1)
  › @tauri-apps/api [NPM]: 1.3.0
  › tauri [RUST]: 1.3.0,
  › tauri-build [RUST]: 1.3.0,
  › tao [RUST]: 0.16.2,
  › wry [RUST]: 0.24.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › framework: React
  › bundler: Vite

App directory structure
  ├─ .git
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

### Stack trace

```text
error[E0277]: the trait bound `Window: Deserialize<'_>` is not satisfied
   --> src\file_system_location\file_system_watcher\mod.rs:102:1
    |
102 | #[tauri::command]
    | ^^^^^^^^^^^^^^^^^ the trait `Deserialize<'_>` is not implemented for `Window`
...
117 |     tauri_builder.invoke_handler(tauri::generate_handler![watch_path, unwatch_path])
    |                                  -------------------------------------------------- in this macro invocation
    |
    = help: the following other types implement trait `Deserialize<'de>`:
              <&'a [u8] as Deserialize<'de>>
              <&'a serde_json::raw::RawValue as Deserialize<'de>>
              <&'a std::path::Path as Deserialize<'de>>
              <&'a str as Deserialize<'de>>
              <() as Deserialize<'de>>
              <(T0, T1) as Deserialize<'de>>
              <(T0, T1, T2) as Deserialize<'de>>
              <(T0, T1, T2, T3) as Deserialize<'de>>
            and 251 others
    = note: required for `Window` to implement `CommandArg<'_, T>`
    = note: this error originates in the macro `__cmd__watch_path` which comes from the expansion of the macro `tauri::generate_handler` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Additional context

It is worth mentioning how I am invoking the command handlers in the case that it is relevant

In the file I invoke the handlers like this:
```rs
pub fn invoke_command_handlers<T: Runtime>(tauri_builder: Builder<T>) -> Builder<T> {
    tauri_builder.invoke_handler(tauri::generate_handler![watch_path, unwatch_path])
}
```
_(the watch_path function, which is much like the unwatch_path function yields the same error I previously mentioned for those wondering)_

And then in the parent module named file_system_location I invoke that handler like this:
```rs
pub fn invoke_command_handlers<T: Runtime>(tauri_builder: Builder<T>) -> Builder<T> {
    file_system_watcher::invoke_command_handlers(tauri_builder)
}
```

And then finally in main.rs:
```rs
pub fn invoke_command_handlers<T: Runtime>(tauri_builder: Builder<T>) -> Builder<T> {
    file_system_location::invoke_command_handlers(file_system::invoke_command_handlers(
        tauri_builder,
    ))
}
```

and

```rs
fn main() {
    let mut file_system_watcher = FileSystemWatcher::new();

    invoke_command_handlers(tauri::Builder::default())
        .manage(AppState::default())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

I believe a setup like this makes my project cleaner and easier to use, although it may be what is causing this unexpected error. I have never had a problem with this system up to this point, and not in any of my other projects yet I don't believe it should be ruled out.

**Comment by FabianLars** [comment]
I'm not sure how or if we can fix it in the macro but in the meantime you can change the commands to something like this and it should work again
```rs
#[tauri::command]
pub fn unwatch_path<R: Runtime>(window: Window<R>, state: tauri::State<AppState>, path: FileSystemLocation) {
    state.directory_watcher().unwatch_path(window, &path);
}
```

**Comment by Jamzy01** [comment]
> I'm not sure how or if we can fix it in the macro but in the meantime you can change the commands to something like this and it should work again
> 
> ```rust
> #[tauri::command]
> pub fn unwatch_path<R: Runtime>(window: Window<R>, state: tauri::State<AppState>, path: FileSystemLocation) {
>     state.directory_watcher().unwatch_path(window, &path);
> }
> ```

This solved the issue with the _#[tauri::command]_ although it caused another issue
![image](https://github.com/tauri-apps/tauri/assets/103490514/bd0b4c9e-eaa0-44e0-886f-f232b64842e3)

This is all the unwatch path method is, so I am confused what is going wrong here
![image](https://github.com/tauri-apps/tauri/assets/103490514/cd9c537f-c892-48a8-b817-f53f97a1b140)

**Comment by FabianLars** [comment]
unwatch_path probably needs that R: Runtime stuff too then, _but_ you can also replace it in the command with Wry directly, which would give up the runtime agnostic approach but whatever:
```rs
#[tauri::command]
pub fn unwatch_path(window: Window<tauri::Wry>, state: tauri::State<AppState>, path: FileSystemLocation) {
    state.directory_watcher().unwatch_path(window, &path);
}
```

**Comment by Jamzy01** [comment]
The code snippet you sent me didn't work and returned the first error I got, any chance you could tell me what is actually going on here because I have no idea what the tauri::command attribute macro does.

**Comment by FabianLars** [comment]
Right, that was the solution to a different problem, sorry. How about doing the same stuff on the `invoke_command_handlers` functions instead of the T: Runtime stuff though? I'm not sure if i accurately reproduced your code on my end but i don't get errors with that anymore (and i can remove the R: Runtime and tauri::Wry stuff from the commands themselves again)

> any chance you could tell me what is actually going on here because I have no idea what the tauri::command attribute macro does.

Nope, that's not really my field of expertise. If you are familiar with macros more than i am you may take a look at the tauri-macros crate yourself. i think that's the most relevant entry point: https://github.com/tauri-apps/tauri/blob/dev/core/tauri-macros/src/command/wrapper.rs#L90

**Comment by Jamzy01** [comment]
I have decided to revert to the common command handler invoking design with tauri like this
```rs
.invoke_handler(generate_handler![
    get_local_file_system_directory_contents,
    get_local_file_system_object,
    watch_path,
    unwatch_path
])
```
It appears to have solved all of my previously stated issues, although it is unfortunate to me that I have to scrap my previous setup. I am unsure of what caused this, and I believe that tauri's command invoking may need some design changes but for the meantime I will close this issue as not planned.
