### ISSUE TITLE
[feat] Support HTTP basic auth in tauri-updater

### ISSUE THREAD

**Issue by tnibler** [tauri-apps/tauri#7097]
### Describe the problem

I want to use basic auth for my updater endpoint like this: 

```
"updater": {
  "endpoints": ["https://username:password@example.com/updates.json"]
}
```

One reason to do this is to put a small proxy in front of S3 for instance to avoid having binaries in open buckets that get indexed in public databases.

Currently, the username and password get ignored and the request is sent without them.

### Describe the solution you'd like

Allow using basic auth credentials in updater endpoint URLs.

I'm willing to implement it myself and submit a PR if maintainers want to, but I think reviewing that is more work than the change itself.

**Comment by row248-hola** [comment]
@tnibler I guess you can add `Authorization` header manually via this method https://docs.rs/tauri/latest/tauri/updater/struct.UpdateBuilder.html#method.header

**Comment by tnibler** [comment]
Somehow completely missed that, thank you!
