### ISSUE TITLE
[bug] Windows taskbar is disable when maximize the tauri application window

### ISSUE THREAD

**Issue by rkuzlik** [tauri-apps/tauri#7103]
### Describe the bug

On Windows when you have a window without decorations and it's maximized, the taskbar becomes disabled (clicking on any icon is not work) till unmaximized the window. 

### Reproduction

1. Make sure you are on Windows
3. (Now in your Tauri application) Create a new webview window
4. Remove the decorations
5. Maximise the window
6. try to open another program that pins to the Windows taskbar/ to click on 'Start' etc.

### Expected behavior

The taskbar will be active and responsive

### Platform and versions

```text
Environment
  › OS: Windows 10.0.19045 X64
  › Webview2: 113.0.1774.57
  › MSVC:
      - Visual Studio Professional 2022
  › Node.js: 18.14.0
  › npm: 9.3.1
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.2
  › rustc: 1.67.0
  › cargo: 1.67.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist/apps/locota   
  › devPath: http://localhost:4200/
  › framework: Angular
  › bundler: Webpack

App directory structure
  ├─ .angular
  ├─ .idea
  ├─ .vscode
  ├─ apps
  ├─ dist
  ├─ libs
  ├─ node_modules
  ├─ src-tauri
  ├─ tmp
```

**Comment by AyalaGol** [comment]
I encounter this issue also.
Can you help please?

**Comment by FabianLars** [comment]
I can't seem to reproduce it, can you upgrade to tauri 1.3 (especially the rust crates) and run `cargo update` in the src-tauri dir?

no idea if that actually helps because i can't reproduce it on 1.2 either 🤔

**Comment by rkuzlik** [comment]
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 113.0.1774.57
    ✔ MSVC: Visual Studio Professional 2022
    ✔ rustc: 1.67.0 (fc594f156 2023-01-24)
    ✔ Cargo: 1.67.0 (8ecd4f20a 2023-01-10)
    ✔ rustup: 1.25.2 (17db695f1 2023-02-01)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.14.0
    - npm: 9.3.1

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.3.0
    - @tauri-apps/cli [NPM]: 1.3.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist/apps
    - devPath: http://localhost:4200/
    - framework: Angular
    - bundler: Webpack

Still happening

**Comment by rkuzlik** [comment]
[windowsTaskbarDisable.zip](https://github.com/tauri-apps/tauri/files/11645154/windowsTaskbarDisable.zip)
The bug happens with those 3 configurations together:
` "decorations": false,
        "resizable": false,
        "transparent": true,`
without the `transparent` the Windows taskbar is disappear at all. (appears black area)

**Comment by amrbashir** [comment]
In the upcoming v2, it shouldn't be an issue but in v1, for maximization to work correctly on Windows, you need to make the window resizable. so try:
```js
appWindow.setResizable(true);
appWindow.maximize();
appWindow.setResizable(false);
```
