### ISSUE TITLE
[bug] the open function filters behave incorrectly

### ISSUE THREAD

**Issue by agraellee** [tauri-apps/tauri#7109]
### Describe the bug

`await open({filters: {name: "MyApp", extensions: ["exe"]}})`
It will show all of exe files to me.
and 
`await open({filters: {name: "MyApp.exe", extensions: ["exe"]}})`  also.

If I changed the filter to `await open({filters: {name: "MyApp", extensions: ["MyApp.exe"]}})` or `await open({filters: {name: "MyApp.exe", extensions: ["MyApp.exe"]}})` then will show me nothing.

I saw that if the extensions is MyApp.exe, will show *.MyApp.exe in dialog.

How can I filter them and only show MyApp.exe to the file list?

### Expected behavior

only show MyApp.exe to me.

### Platform and versions

```text
OS: Windows
Tauri version: 1.3
Rust version: 1.69 stable
```

**Comment by FabianLars** [comment]
That's not reallyyy "incorrect". These filters only work with extensions. I don't know if there are any platform limitations at play, but the dialog library we use only supports extensions: https://docs.rs/rfd/latest/rfd/struct.FileDialog.html#method.add_filter

Looking at the windows apis here https://learn.microsoft.com/en-us/dotnet/api/microsoft.win32.filedialog.filter?view=windowsdesktop-8.0 it isn't reallyyy explicit enough about this imo. The closes this is this:
> Each file type must be described by at least one _Extension_.

And all examples only use file extensions so i'd imagine this is a requirement.

Seeing that not even Electron seems to support this i will close this. If you have examples of frameworks where this is possible (or OS api docs) then please feel free to send them here.

Thank you :)
