### ISSUE TITLE
2.0.0-alpha.9 tauri.conf.json the allowlist property is compiling with an error

### ISSUE THREAD

**Issue by yangjungis** [tauri-apps/tauri#7112]
### Describe the bug

2.0.0-alpha.9 tauri.conf.json the allowlist property is compiling with an error

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 113.0.1774.57
    ✔ MSVC:
        - Visual Studio 15 ���ɹ��� 2017
        - Visual Studio ���ɹ��� 2019
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 16.14.0
    - pnpm: 8.5.1
    - npm: 8.3.1

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.9
    - tauri-build [RUST]: 2.0.0-alpha.5
    - wry [RUST]: 0.28.3
    - tao [RUST]: 0.19.1
    - @tauri-apps/api [NPM]: 2.0.0-alpha.4
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.9

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../ui
    - devPath: http://localhost:4173/
    - bundler: Vite

```

### Stack trace

 Error `tauri.conf.json` error on `tauri`: Additional properties are not allowed ('allowlist' was unexpected

### Additional context
tauri.conf.json
```
 "tauri": {
    "allowlist": {
      "all": true
    },
    "bundle": {
      "active": true,
```

**Comment by FabianLars** [comment]
The configs changed in the latest alpha release because we're moving everything to plugins. To be honest i'd suggest to not update just yet and wait for us to catch up with the docs. If you can't wait for it, remove the configs the error complains about and install the plugins you'll need from https://github.com/tauri-apps/plugins-workspace/tree/v2/plugins.

**Comment by trookie2000** [comment]
How do you set tauri2.0.0-alpha back to 1.0?

**Comment by deadash** [comment]
@trookie2000 
```
cargo uninstall tauri-cli
cargo install tauri-cli
```

**Comment by Merovex** [comment]
Around Alpha.20, I ran into a problem tinkering with an upgrade. I did the cargo "reinstall" of tauri-cli, but that led to a conflict with allow list until I ran the following. May need to reinstall the API. :)

`@tauri-apps/cli@latest @tauri-apps/api@latest`

Looking forward to Beta.

**Comment by mitch1009** [comment]
I noticed that if out initialize your tauri app using cargo it generates a different type off config as compared to using any js  package managers.

**Comment by jamalsoueidan** [comment]
"permissions": ["core:default", "shell:allow-open", "http:default"]
 
 http:default is not allowed.

{
  "permissions": [
    {
      "identifier": "http:default",
      "allow": [{ "url": "https://*.tauri.app" }],
      "deny": [{ "url": "https://private.tauri.app" }]
    }
  ]
}

is not allowed!

https://v2.tauri.app/plugin/http-client/
