### ISSUE TITLE
[feat] add Japanese to the nsis language.

### ISSUE THREAD

**Issue by t0m0120** [tauri-apps/tauri#7113]
### Describe the problem

I get the following error when I set japanese to `windows>nsis>language` in tauri.conf.json
```json
  "tauri": {
     ....
      "windows": {
        "nsis": {
          "languages": ["japanese"]
        }
      }
```

build error

```
       Error failed to bundle project: Language japanese not implemented. If it is a valid language listed on <https://github.com/kichik/nsis/tree/9465c08046f00ccb6eda985abbdbf52c275c6c4d/Contrib/Language%20files>, please open a Tauri feature request
```

### Describe the solution you'd like

I would like to see Japanese added to the nsis build.

**Comment by FabianLars** [comment]
Japanese was added into the cli in v1.3.1: https://github.com/tauri-apps/tauri/pull/6940 but it's currently broken with a fix being here: https://github.com/tauri-apps/tauri/pull/7086 - thanks for the request :)

**Comment by t0m0120** [comment]
@FabianLars 
Thanks for the comment.
Is there a way to apply the #7086 modifications on local?

**Comment by FabianLars** [comment]
You'll have to use the CLI from git, here's a small guide showing you how: https://tauri.app/v1/guides/faq#how-can-i-use-unpublished-tauri-changes
