### ISSUE TITLE
Failed to load resource: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by ezewu** [tauri-apps/tauri#7114]
### Describe the bug

Tauri opens the web project on the local hard disk. If the opened project introduces js, it will report an error, Failed to load resource: net::ERR_CONNECTION_REFUSED, how to solve this problem, thank you for your help, I searched for this in Issues The problem seems to be solved by using register_uri_scheme_protocol, but I’m not sure if it can be solved. I don’t know how to rust code, and I didn’t run the code snippets posted by others.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 113.0.1774.57
    ✔ MSVC: Visual Studio Community 2019
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.1.0
    - pnpm: 8.4.0
    - npm: 9.6.4

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.3.0
    - @tauri-apps/cli [NPM]: 1.3.1

[-] App
    - build-type: bundle
    - CSP: default-src 'self'; img-src 'self' asset: https://asset.localhost
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Could you create a reproduction example? I have difficulties following the steps you take to get the issue.

**Comment by ezewu** [comment]
Ok, I will write an example to upload to the warehouse, it may be next Monday, thank you

**Comment by ezewu** [comment]
@FabianLars 
https://github.com/ezewu/appiframe  This is the code repository I use
``` javascript
  imageSrc.value = convertFileSrc("C:\\data\\1.png");
  iframeSrc.value = convertFileSrc("C:\\data\\1\\index.html");
```

When base.js is introduced into index.html, it will report an error

**Comment by amrbashir** [comment]
This is an upstream issue, see https://github.com/MicrosoftEdge/WebView2Feedback/issues/2341 

You're basically using our built-in protocol `asset` but on Windows, iframe requests are not captured, it is a limitation in WebView2.

They added a new API to fix this shortcoming but we can't use it until it is stable.

**Comment by ezewu** [comment]
Thank you for your answer, how to use this new api AddWebResourceRequestedFilter in tauri

**Comment by FabianLars** [comment]
Like Amr said, it can't be used until it lands in a stable SDK, which did not happen yet.

**Comment by ezewu** [comment]
This function is currently completely useless, and it is still under development?

**Comment by FabianLars** [comment]
The new WebView2 api that will allow Tauri to also listen to requests inside iframes and not just in the main window is still under development, yes.
In other words, we have to wait for Microsoft to be able to fix your issue.

**Comment by ezewu** [comment]
@FabianLars @amrbashir  Thank you for the answer, it seems that I will use electron for a while

**Comment by c0ncentus** [comment]
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 120.0.2210.144
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.74.1 (a28077b28 2023-12-04)
    ✔ cargo: 1.74.1 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 21.4.0
    - npm: 7.6.1

[-] Packages
    - tauri [RUST]: 1.5.4
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.9

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../out
    - devPath: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Webpack


I have same issue


Solve issue with this config 
```
      "protocol": {
        "all": true,
        "asset": true,
        "assetScope": ["*"]
      },
```
would be appreciate some indication in the documentation ... #Rip_The_Doc.

**Comment by stackedCG** [comment]
@c0ncentus , may I know where did you add this in the tauri.conf.json?
```
      "protocol": {
        "all": true,
        "asset": true,
        "assetScope": ["*"]
      },
```

**Comment by goodman965** [comment]
@stackedCG
[convertFileSrc](https://v1.tauri.app/v1/api/js/tauri/#convertfilesrc)   works well on windows and pop_os
js

> const {invoke, convertFileSrc} = window.__TAURI__.core;
>...
>image.src = convertFileSrc("filename", 'dyimg');
>...

rs
>...
>        .register_asynchronous_uri_scheme_protocol("dyimg", move |_cts, request, responder|{
>                responder.respond(get_image(request));
>        })

toml
>[features]
>default= ["custom-protocol"]
>custom-protocol= ["tauri/custom-protocol"]`

**Comment by stackedCG** [comment]
@goodman965, for the rs, do you mean src-tauri>build.rs? Where should I put that I noticed there is .register... currently this is what it looks like in my end:

```
fn main() {
    tauri_build::build()
}
```

**Comment by goodman965** [comment]
@stackedCG 
i mean main.rs or lib.rs 

>   tauri::Builder::default()
>       //
>      .invoke_handler(tauri::generate_handler![...])
>       .register_asynchronous_uri_scheme_protocol("dyimg", move |_cts, request, responder|{
>                responder.respond(your_http::Response);
 >       })
>//or
>       .register_uri_scheme_protocol("dyimg", move |_cts, request|{
>                your_http::Response
 >       })
>        .run(tauri::generate_context!())
 >       .expect("error while running tauri application");

**Comment by stackedCG** [comment]
@goodman965 

> tauri::Builder::default()
> //
> .invoke_handler(tauri::generate_handler![...])
> .register_asynchronous_uri_scheme_protocol("dyimg", move |_cts, request, responder|{
> responder.respond(your_http::Response);
> })
> //or
> .register_uri_scheme_protocol("dyimg", move |_cts, request|{
> your_http::Response
> })
> .run(tauri::generate_context!())
> .expect("error while running tauri application");

Can you give me a sample of `your_http::Response`, just to confirm does this workaround work on mobile as well?

Also thank you very much for the help.

**Comment by goodman965** [comment]
@stackedCG
in my case

> tauri::http::Response::builder()
        .status(StatusCode::ACCEPTED)
        .header(CONTENT_TYPE," image/jpg")
        .body({Vec\<u8\> jpeg file bytes}).unwrap()

**Comment by Aniome** [comment]
I solved the problem in another way, in src-tauri/tauri.conf.json:
```
  "app": {
    "security": {
      "csp": {
        "img-src": "'self' asset: http://asset.localhost blob: data:"
      },
      "assetProtocol": {
        "enable": true,
        "scope": ["**"]
      }
    }
  }
```
