### ISSUE TITLE
[bug] Google detect malware

### ISSUE THREAD

**Issue by RFG-G** [tauri-apps/tauri#7117]
### Describe the bug

Build an empty project with `npm create tauri-app@latest `
Upload to VirusTotal and site shows 2 detect by Google and Ikarus.
VT link: https://www.virustotal.com/gui/file/9b83fb731737d6c359616aa7f061f7a345afc5e068845ed2d0050656b87afc84?nocache=1

### Expected behavior

0 detects

### Platform and versions

```text
[✘] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 113.0.1774.57
    ✘ Couldn't detect Visual Studio or Visual Studio Build Tools. Download from https://aka.ms/vs/17/release/vs_BuildTools.exe
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-gnu (default)
    - node: 16.17.1
    - pnpm: 7.5.2
    - yarn: 1.22.19
    - npm: 9.6.4
```

**Comment by FabianLars** [comment]
Just for the sake of it, can you try building it with the msvc toolchain instead of gnu? (install instructions are part of our docs: <https://tauri.app/v1/guides/getting-started/prerequisites#setting-up-windows>)
