### ISSUE TITLE
[bug] I am seeing blank screen on after build.

### ISSUE THREAD

**Issue by kondareddy** [tauri-apps/tauri#7118]
### Describe the bug

I have followed below to integrate tauri onto our angular based application on windows

https://tauri.app/v1/guides/getting-started/setup/integrate/

able to build and run locally but I am seeing blank.

![image](https://github.com/tauri-apps/tauri/assets/1445374/71ff64f6-4f58-48ea-bc62-16966a2ff86f).

If I want to create MSI using another tool - what folder contents I need to use? just .exe file?

![image](https://github.com/tauri-apps/tauri/assets/1445374/5929cea7-5d11-4260-bbae-992aff37b2bf)

### Platform and versions

```text
windows
```

**Comment by kondareddy** [comment]
after changing ""distDir": "../dist" - instead of blank - I am seeing below - don't know why it is trying to load tauri.localhost?
![image](https://github.com/tauri-apps/tauri/assets/1445374/7d86c866-c411-49e9-94bd-58da7840b6b7)

**Comment by FabianLars** [comment]
> If I want to create MSI using another tool - what folder contents I need to use? just .exe file?

Yes. Unless you use the sidecar or resource features, then you gotta bundle them manually too.

> don't know why it is trying to load tauri.localhost?

This is the dummy localhost address tauri serves the frontend files from (it's not an actual localhost _server_).

> after changing ""distDir": "../dist" - instead of blank - I am seeing below

Sounds like your ../dist dir was empty or didn't contain an `index.html` file

**Comment by kondareddy** [comment]
@FabianLars  - Thanks for reply.
We have advanced installer license , which we can integrate in build pipelines as well. Build output of tauri is just single .exe file only?  I need clarity on what are the files we need to include!!

if I use distDir 
as "../dist" can't reach page trying to load tauri.localhost
as "../dist/..web" then blank screen where index.html present

![image](https://github.com/tauri-apps/tauri/assets/1445374/deda199e-970e-4b0c-aa0a-1b825963b468)

**Comment by FabianLars** [comment]
> We have advanced installer license , which we can integrate in build pipelines as well. Build output of tauri is just single .exe file only? I need clarity on what are the files we need to include!!

I can't go into more detail than above since i don't know your project. If you use the [sidecar](https://tauri.app/v1/guides/building/sidecar/) or [resource](https://tauri.app/v1/guides/building/resources) features then you'll have to bundle these files yourself. If you don't use them then you only need the .exe from `target/release/`...

----

`"../dist/..web"` this one sounds correct, it's what we set in create-tauri-app too: https://github.com/tauri-apps/create-tauri-app/blob/dev/packages/cli/fragments/fragment-angular/_cta_manifest_#L8

Can you try a debug build via `npm run tauri build -- --debug` (or `yarn build --debug`) and run the .exe from (`target/debug/`) and check the devtools console (right click on the window -> inspect) for errors please?
Note that `tauri dev` and `tauri build --debug` is _not_ the same.

**Comment by kondareddy** [comment]
@FabianLars  - Thanks , setup related I will explore and figure-out.

we are using self signed certificate attached - which is not recognized by tauri/webview used. how do we fix this issue

![image](https://github.com/tauri-apps/tauri/assets/1445374/2b55a0a4-a86e-4c4e-a381-7e5073402eed)

**Comment by kondareddy** [comment]
@FabianLars  - any update on this please? please redirect to someone who can help on this.

**Comment by FabianLars** [comment]
The relevant people are/were on vacation and have a lot of catching up to do, apologies for the delay.

That said, i didn't see your message before that so i can answer this myself:
> we are using self signed certificate attached - which is not recognized by tauri/webview used. how do we fix this issue

Tauri currently does indeed not support self signed certificates at all right now. Here's a discussion on workarounds: https://github.com/tauri-apps/tauri/issues/4039 (tldr: Use Rust for the requests)

**Comment by kondareddy** [comment]
@FabianLars  - Thanks for reply.
Two solutions discussed in this thread mainly.
1. Catching the error and ignoring,  app.on('certificate-error') - do we have this event on tauri framework?
2. Modifying the framework code to ignore this error - Is this change merged to master - I can use latest version?

**Comment by FabianLars** [comment]
1. No we don't, reason: https://github.com/tauri-apps/tauri/issues/4039#issuecomment-1115930694 and https://github.com/tauri-apps/tauri/issues/4039#issuecomment-1116130793
2. Also no. Note that if we'd add that to Tauri, it would only apply to the http client in `@tauri-apps/api`, not the browser's default fetch. The Rust solutions discussed there were meant as a solution on the user's side (via [tauri commands](https://tauri.app/v1/guides/features/command)), not inside tauri.

**Comment by kondareddy** [comment]
@FabianLars - Ok.  Sorry I have basic doubt now.

I am trying to bundle entire angular build so that app works with-out internet , but I am not sure how it will start running locally and works with - https://localhost:4200/
![image](https://github.com/tauri-apps/tauri/assets/1445374/9aee9c0e-70b4-4571-8dcc-27a91dc6610d)

if I am going simply the DevPath - app works with-out any issues.
![image](https://github.com/tauri-apps/tauri/assets/1445374/d2258940-7c48-453d-aac6-0ff06fc8fc05)

I am missing something - can we please share working sample for angular so that we can experiment and test

**Comment by FabianLars** [comment]
> I am missing something - can we please share working sample for angular so that we can experiment and test

Use https://github.com/tauri-apps/create-tauri-app/ and select its Angular option. I'm not aware of any actual examples/apps using angular.

Edit: To be clear, there are people using angular, i just don't know of any _public_ projects.

**Comment by kondareddy** [comment]
@FabianLars  - I see angular as a supported item in templates list?
![image](https://github.com/tauri-apps/tauri/assets/1445374/45982549-97a8-4ac3-941d-87d9d9b02dd4)

**Comment by FabianLars** [comment]
The readme wasn't updated, here's its prompt:
![grafik](https://github.com/tauri-apps/tauri/assets/30730186/48669ddd-0f5c-48d3-bfb9-03423288711f)

**Comment by kondareddy** [comment]
@FabianLars  - Thanks, we are able to move forward but again we got cross issue? is there a way to change tauri.localhost to match with our URL

![image](https://github.com/tauri-apps/tauri/assets/1445374/e56cb30c-3336-4f56-84c7-d84aacaa4905)

**Comment by amrbashir** [comment]
Not possible, `tauri.localhost` is an internal custom protocol to serve the assets from within the binary.

**Comment by kondareddy** [comment]
@amrbashir - any alternative solution for above please, our web needs to interact with rest endpoints. This should be generic problem with this framework.

**Comment by amrbashir** [comment]
you can use https://tauri.app/v1/api/js/http

**Comment by kondareddy** [comment]
@amrbashir  - sorry , still failing with same exception , am I missing something? FYI identifier also I have give same as my api domain

![image](https://github.com/tauri-apps/tauri/assets/1445374/8e0aa9e9-729b-4345-9631-dc382b3416d5)

**Comment by FabianLars** [comment]
What Amr linked means you also need to use this: https://tauri.app/v1/api/js/http/#functions instead of the browser's built-in `fetch()`/`xmlhttprequest()`. Only this way will make it do the requests on the rust side where it doesn't have the same restrictions.

**Comment by kondareddy** [comment]
@FabianLars @amrbashir We are trying wrap working web as an desktop application with minor UI changes. no other alternative?

This should be generic problem across, who ever is hitting API's from their web?
