### ISSUE TITLE
[bug] `unlisten()` after `onCloseRequested` breaks window closing

### ISSUE THREAD

**Issue by vgskye** [tauri-apps/tauri#7119]
### Describe the bug

When you `unlisten()` to remove a `onCloseRequested` handler, it breaks window closing; the callback doesn't get called as expected, but it doesn't close the window either.

### Reproduction

1. run https://github.com/vgskye/miniature-umbrella
2. click the button
3. wait five seconds
4. try to close the window

### Expected behavior

The window can be closed by window buttons after `unlisten()` is called

### Platform and versions

```text
[⚠] Environment
    - OS: NixOS 22.11.0 X64
    ✔ webkit2gtk-4.0: 2.40.2
    ✔ rsvg2: 2.55.1
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ⚠ rustup: not installed!
      If you have rust installed some other way, we recommend uninstalling it
      then use rustup instead. Visit https://rustup.rs/
    ⚠ Rust toolchain: couldn't be deteceted!
      maybe you don't have rustup installed? if so, Visit https://rustup.rs/
    - node: 18.14.1
    - pnpm: 8.2.0
    - yarn: 3.5.1
    - npm: 9.3.1

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.3.0
    - @tauri-apps/cli [NPM]: 1.3.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - bundler: Vite
```

**Comment by simonhyll** [comment]
I assisted in this issue and confirmed that indeed after running `unlisten()` the normal window close button no longer works and registering a new `onCloseRequested` listener to `appWindow` fixes it. It seems like `unlisten()` prevents the default app closing from functioning.
