### ISSUE TITLE
[bug] cargo tauri dev not working, code: 216

### ISSUE THREAD

**Issue by atfox98** [tauri-apps/tauri#7123]
### Describe the bug

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 216, kind: Uncategorized, message: "This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher." }', C:\Users\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-cli-1.3.1\src\interface\rust\desktop.rs:57:63

### Reproduction

     npm create vite@latest example -- --template svelte
     cd example
     npx svelte-add

The options I choose for svelte-add are `JavaScript`, `PostCSS`, `Yes` to Autoprefixer, `Tailwind CSS`, `No` to forms plugin, `No` to typography plugin, `Yes` to daisyUI, no extra features, no code quality tools, `Nowhere` as a deployment target, `No` example code, and `Yes` to install dependencies.

From here I followed the [getting started guide](https://tauri.app/v1/guides/getting-started/setup/vite) up to `cargo tauri dev`, where I encountered the error.

### Expected behavior

Expected window to open

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 114.0.1823.37
    ✔ MSVC:
        - Visual Studio Enterprise 2022
        - Visual Studio Build Tools 2022
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.16.0
    - npm: 9.6.7

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.3.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

### Stack trace

```text
stack backtrace:
   0:     0x7ff6182cd2c4 - <unknown>
   1:     0x7ff617d46ecb - <unknown>
   2:     0x7ff6182ab9e1 - <unknown>
   3:     0x7ff6182d1d0b - <unknown>
   4:     0x7ff6182d18e8 - <unknown>
   5:     0x7ff6182d14ca - <unknown>
   6:     0x7ff6182d23b6 - <unknown>
   7:     0x7ff6182d22b6 - <unknown>
   8:     0x7ff6182d2209 - <unknown>
   9:     0x7ff6182d21f4 - <unknown>
  10:     0x7ff618855a95 - <unknown>
  11:     0x7ff618855e66 - <unknown>
  12:     0x7ff6184b3765 - <unknown>
  13:     0x7ff6184b27cb - <unknown>
  14:     0x7ff6184d2ee6 - <unknown>
  15:     0x7ff6182c905c - <unknown>
  16:     0x7ffa4af126ad - BaseThreadInitThunk
  17:     0x7ffa4bbea9f8 - RtlUserThreadStart
```

### Additional context

I have all the [prerequisites from the website](https://tauri.app/v1/guides/getting-started/prerequisites/), I even tried adding a few to get things to work.

![image](https://github.com/tauri-apps/tauri/assets/30678712/730baed5-4d36-4fed-9e2e-6c1fa6012e3a)
![image](https://github.com/tauri-apps/tauri/assets/30678712/c2c77491-a075-4190-b09b-6836f574560b)

The output of `rustc --version` is `rustc 1.70.0 (90c541806 2023-05-31)`

**Comment by FabianLars** [comment]
Super confusing. Every time we saw this error so far was caused by the use of Visual Studio 2017 or below instead of 2019/2022.

Did you recently uninstall older versions of VS?

Also it could be that the terminal session only recognizes tools installed in your VS Enterprise installation and not the VS Build Tools one. So maybe the Enterprise installation has really old tools, or missing tools? Btw, you can install the Win11 SDK and MSVC v143 in the Enterprise installation and can remove the Build Tools installation again if you only installed it for Tauri.

**Comment by atfox98** [comment]
I did recently uninstall VS Enterprise 2017 to upgrade to 2022. To try to rule everything out, I completely uninstalled everything in the VS installer. After restarting the output of `cargo tauri info` was:

[✘] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 114.0.1823.37
    ✘ Couldn't detect Visual Studio or Visual Studio Build Tools. Download from https://aka.ms/vs/17/release/vs_BuildTools.exe
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.16.0
    - npm: 9.6.7

I then installed just MSVC v143 and the Windows 10 SDK (10.0.19041.0, same one highlighted on the prereqs page).`cargo tauri info` came back with:

[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 114.0.1823.37
    ✔ MSVC: Visual Studio Enterprise 2022
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.16.0
    - npm: 9.6.7

Same error as before: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 216, kind: Uncategorized, message: "This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher." }', C:\Users\Austin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-cli-1.3.1\src\interface\rust\desktop.rs:57:63

Any suggestions? What tools are being called? I can use `which` on the terminal to see if there are any other installations that are causing problems.

**Comment by FabianLars** [comment]
> What tools are being called?

The 216 comes from calling `cargo build` so i'm not sure what it or the webview related dependencies do tbh. (should be this one likely https://github.com/wravery/webview2-rs)

I'm honestly a bit out of ideas here, maybe try reinstalling/repairing the webview2 installation 😅

**Comment by atfox98** [comment]
I tried making a project with `cargo create-tauri-app` and everything worked out fine. I think it might have been a problem with svelte-add, although I'm not 100% sure. Going ahead and closing. Thank you for your help
