### ISSUE TITLE
[bug] Using external remote URL as devPath and distDir in Windows 10 returns `TLS is disabled, activate one of the tls- features`

### ISSUE THREAD

**Issue by luucasrb** [tauri-apps/tauri#7124]
### Describe the bug

Running Tauri with a remote URL in Windows 10 returns an empty window with the message: `tauri.localhost refused to connect`.

In the Rust process, I get:

```
request url https://my-private-ip.aws.com:1445/, original path /, decoded /
Failed to request https://my-private-ip.aws.com:1445/ TLS is disabled, activate one of the tls- features
```

The same result with both `yarn tauri dev` and `yarn tauri build` commands. But, when using Ubuntu/Linux version I'm not able to reproduce the error, my app is loaded and it works properly.

### Reproduction

1. Run a remote application and host it anywhere with a signed certificate.
2. In the `tauri.conf.json` set both `devPath` and `distDir` with the URL.
3. Create a simple `label = "main"` window.
4. Try to open it in a Windows 10 setup.
5. Both `yarn tauri dev` and `yarn tauri build` returns `tauri.localhost refused to connect`.
6. Both errors are followed by the log `TLS is disabled, activate one of the tls- features`.

### Expected behavior

To open the application that is running in the remote url `https://my-private-ip.aws.com:1445/`.

### Platform and versions

```text
Environment
  › OS: Windows 10.0.17763 X64
  › Webview2: 113.0.1774.57
  › MSVC:
  › Node.js: 18.12.1
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.66.0
  › cargo: 1.66.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.1
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 2.0.0-alpha.1,
  › tauri-build [RUST]: 2.0.0-alpha.0,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: https://my-private-ip.aws.com:1445/
  › devPath: https://my-private-ip.aws.com:1445/

App directory structure
  ├─ .git
  ├─ docs
  ├─ node_modules
  ├─ src-tauri
  └─ templates
```

### Stack trace

```
request url https://my-private-ip.aws.com:1445/, original path /, decoded /
Failed to request https://my-private-ip.aws.com:1445/ TLS is disabled, activate one of the tls- features
```

### Additional context

- My address `https://my-private-ip.aws.com:1445/` is running a Vue App, with a valid and signed SSL certificate.
- When I set `"url": "https://my-private-ip.aws.com:1445/"` in the `tauri` > `windows` config and remove the `devPath`, It opens the URL. However, my app is able to open with `multiwindow`, and I cannot use this url hardcoded. So it lead me to another set of errors.
- My Windows 10 TLS 1.2 feature is enabled in the Internet Options.
- Already tried: https://github.com/tauri-apps/tauri/issues/6882#issuecomment-1537191495 this solution. But it doesn't work.

**Comment by FabianLars** [comment]
Thanks for the report!

Can you try upgrading the tauri rust crates a few versions? (Be careful about updating to _latest_ though as there were many breaking changes in the config in alpha.9)

**Comment by luucasrb** [comment]
Working on it. Can you please let the issue open for some time? it seems that every new version that I upgrade makes me to setup a complete new environment to reach the dependencies needs.

**Comment by FabianLars** [comment]
> Can you please let the issue open for some time?

Sure

> it seems that every new version that I upgrade makes me to setup a complete new environment to reach the dependencies needs.

You'll be in for a ride for the alpha.9 upgrade then, where almost all apis where moved into separate plugins 😅 But yes, the alpha versions contain many many breaking changes which is (one of the reasons) why we didn't recommend it for production apps yet.

**Comment by luucasrb** [comment]
Ok upgrading the versions solves the problem. For future references, had to:

- Provisioning a new Windows 10 with fresh installation;
- ` "@tauri-apps/cli": "2.0.0-alpha.9"` in the package.json;
- `tauri-build = { version = "=2.0.0-alpha.5", features = [] }` in the Cargo.toml;
- `tauri = { version = "=2.0.0-alpha.9", features = ["system-tray"] }` also in the Cargo.toml;
- Running `cargo update` and `yarn`;

Also had to remove some config from `tauri.config` and refactor some Rust code. 

Thanks @FabianLars.
