### ISSUE TITLE
[feat/bug] Can't run piped commands

### ISSUE THREAD

**Issue by Explosion-Scratch** [tauri-apps/tauri#7126]
### Describe the problem

I'm building an app where I need to run `fd [stuff] | fzf` and I can't do that via tauri.

### Describe the solution you'd like

Allowing commands to pipe to one another, or having a stdin validator as well, that way people could make two commands, wait for the first one then pass it as stdin to the second thing

**Comment by FabianLars** [comment]
Thanks for the request!

pipe operators are specific to sh shells which aren't necessarily used in commands. Did you try using bash as the command binary?
Something like (untested):
```ts
const cmd = new Command('bash', ["-c", '"fd [stuff] | fzf"']);
```

Otherwise the flow you described in the `solution you'd like` section should already be possible via the child.write() function 🤔

**Comment by Explosion-Scratch** [comment]
Let me try that! I feel stupid now! I'll close this if it works =)

**Comment by Explosion-Scratch** [comment]
I'm getting `[Log] command stderr: "/bin/bash: /bin/bash: cannot execute binary file` (@tauri-apps_api_shell.js, line 42)'. This happens when simply running ```new Command('bash', ["bash", "-c", `echo 'test'`])```

**Comment by FabianLars** [comment]
and if you remove the duplicate `bash` from the argument array? because now your command looks like this in the terminal
```sh
bash bash -c echo 'test'
```
Looking at that it may need the quotes around the command you pass into -c (`echo test` in this case)

**Comment by Explosion-Scratch** [comment]
Thanks so much for your help! It's working now =)
