### ISSUE TITLE
[bug] can't get the updater status

### ISSUE THREAD

**Issue by xdewx** [tauri-apps/tauri#7128]
### Describe the bug

how to get the status of emit('tauri://update')? onUpdaterEvent seems not work.
I found that the dialog will show when there is a new version available, but nothing happens when not.

1. if there exists a newer version, dialog will show
2. if currentVersion.json not exist, nothing happens. In fact, `Promise.reject` expected
3. if cuurentVersion.json exists but version in it  not greater than currentVersion, nothing happens. In fact, `Promise.reject` expected

### Platform and versions

```text
windows
tauri 1.3.0
```

**Comment by FabianLars** [comment]
Thanks for the report! Could you share a reproduction example we can take a look at? 🙏

**Comment by xdewx** [comment]
> Thanks for the report! Could you share a reproduction example we can take a look at? 🙏

the reproduction example completely follows [https://tauri.app/zh-cn/v1/guides/distribution/updater](https://tauri.app/zh-cn/v1/guides/distribution/updater). because need a public ip, so it's not easy to give a real example.

Maybe we can analyze the logic of `@tauri-apps/api/updater` directly and make sure it can handle the following cases:
1. when `currentVersion.json` is missing
2. when version in `currentVersion.json` is not greater than currentVersion
3. when the format of `currentVersion.json` is invalid
4. when network error
5. when domain is behinds of cloudflare

**Comment by FabianLars** [comment]
Most of that should be reported by onUpdaterEvent, but only if you trigger it via `emit('tauri://update')` since the inbuilt check from the default dialog runs too early for it to be registered (on app start).

Since it doesn't report anything for you, you can also try the rust counterpart as a sanity check:
```rs
let app = tauri::Builder::default().build(tauri::generate_context!()).expect("error building tauri app");

app.run(|_app_handle, event| {
  if let RunEvent::Updater(updater_event) = event {
    dbg!(updater_event);
  }
});
```

**Comment by xdewx** [comment]
> Most of that should be reported by onUpdaterEvent, but only if you trigger it via emit('tauri://update') since the inbuilt check from the default dialog runs too early for it to be registered (on app start).

but, if i invoke `checkUpdate & onUpdaterEvent`  manually again, will i receive the events in my `onUpdaterEvent`?
In my testing, it failed.

**Comment by FabianLars** [comment]
For visibility, the testing we did on Discord so far showed that, if we use the [server approach](https://tauri.app/v1/guides/distribution/updater#dynamic-update-server) works, but the [static json approach](https://tauri.app/v1/guides/distribution/updater#static-json-file) never resolves the `checkUpdate` promise

**Comment by FabianLars** [comment]
Okay so i forgot that the events are limited if you enable the default dialog, because tauri still logs most of the events.

I'm a bit unsure what the best approach is tbh:
- Just emit UpdaterEvent::AlreadyUpToDate here https://github.com/tauri-apps/tauri/blob/dev/core/tauri/src/updater/mod.rs#L427
- completely remove the events switch and always emit them no matter the dialog setting
- just wait for v2 where the dialog option doesn't exist anymore.

Currently lean towards 1&2 but idk...

**Comment by xdewx** [comment]
![image](https://github.com/tauri-apps/tauri/assets/20438962/473d04bf-1b16-4653-958a-e063ba2eae5c)
In my opinion, I think a call to checkUpdate should respond regardless of whether the dialog switch is present. The dialog switch only controls whether a call is automatically completed and related events are emitted during system initialization. The rest of the scenario api just needs to live up to its name.

And by the way, it seems that updater can only upgrade step by step, it would be better if there is a `latest.json`, that is:
1. first check latest.json,if exists, upgrade any current version to the latest version
2. if not exist latest.json, check currentVersion.json

if only check currentVersion, the developer have to keep all version.json updated when there is a new version.

**Comment by amrbashir** [comment]
@FabianLars just patch the current implementation for it to barely work. v2 will have a better implementation and straight-forward JS API.
