### ISSUE TITLE
[bug] Http request always return 400

### ISSUE THREAD

**Issue by wenghongtian** [tauri-apps/tauri#7131]
### Describe the bug

When I make a http request, it always return 400.
<img width="662" alt="image" src="https://github.com/tauri-apps/tauri/assets/132538473/b4e7403d-cd29-486a-adc8-121f9b0905f7">
![image](https://github.com/tauri-apps/tauri/assets/132538473/b42262b5-975b-41b4-a40e-af593351abca)
<img width="621" alt="image" src="https://github.com/tauri-apps/tauri/assets/132538473/c53d203a-0dff-45e3-bb5e-4fa559f8f2a5">

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 11.4.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.65.0 (897e37553 2022-11-02)
    ✔ Cargo: 1.65.0 (4bc8f24d3 2022-10-20)
    ✔ rustup: 1.25.1 (bb60b1e89 2022-07-12)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 16.14.0
    - pnpm: 8.5.0
    - yarn: 1.22.18
    - npm: 8.3.1




[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.3.0
    - @tauri-apps/cli [NPM]: 1.3.1

[-] App
    - build-type: bundle
    - CSP: 
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Works fine for me with the same code:
![grafik](https://github.com/tauri-apps/tauri/assets/30730186/36f0f067-2c0d-4fe5-bfcd-f84f2f983135)

Are you using a proxy that may block the request?

**Comment by wenghongtian** [comment]
I have close my proxy, but I still got 400.

**Comment by wenghongtian** [comment]
When I restart my computure, it work fine.
