### ISSUE TITLE
[bug] React packaged by Tauri can not access server APIs on windows

### ISSUE THREAD

**Issue by yuanming-cienet** [tauri-apps/tauri#7140]
### Describe the bug

I have packaged the exist React project by using Tauri. But it can't access the server APIs (Http, not https yet) after doing this.
It works well on mac. And It works well when run 'npm run tauri dev' on windows.
But when i run `npm run tauri build` and then install the `.exe` generated. It failed to access the server APIs. Anybody know what happened about this? thanks

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22000 X64
    ✔ WebView2: 114.0.1823.37
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-pc-windows-msvc (default)
    - node: 18.16.0
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.3.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../build
    - devPath: http://127.0.0.1:3000/
    - framework: React
```

**Comment by FabianLars** [comment]
This is the main tracking issue: <https://github.com/tauri-apps/tauri/issues/3007>. The only workarounds right now are to either do the requests in rust (tauri's http apis count too), or use the localhost plugin.
We're also investigating adding a setting to use a `http` origin in production (without the localhost plugin).
