### ISSUE TITLE
[bug] invoke broken on android dev

### ISSUE THREAD

**Issue by jhutchins** [tauri-apps/tauri#7176]
### Describe the bug

As of this commit a50f24b2bd93864cacd9047b6fcd152f71a38c45 calling invoke from the web browser no longer works while running the application in an android emulator using `cargo tauri android dev`.

My target is android, I'm running on MacOS and my front end is built using Sycamore.

I used `git bisect` to determine when the next branch first broke for me and determined that it was the merge commit that I mentioned. There's not an issue with the desktop application in dev mode, just the android one. I haven't tracked down where the issue was coming from, but figured I would write up the issue now in case someone has a quick idea on what the issue could be and where to look before I have a chance to finish running down this bug.

### Reproduction

This can be easily reproduced with the sample app with a mobile dev environment already setup.

```bash
sh <(curl https://create.tauri.app/sh) --alpha --mobile --manager cargo --template sycamore test
cd test
cargo tauri android init
tee -a Cargo.toml <<EOF
[patch.crates-io]
tauri = { git = "https://github.com/tauri-apps/tauri.git", branch = "next" }
EOF
cargo tauri android dev
```

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 12.6.3 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 19.9.0
    - pnpm: 7.27.0
    - yarn: 1.22.19
    - npm: 9.6.3

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.9
    - tauri-build [RUST]: no manifest (2.0.0-alpha.5, 2.0.0-alpha.5)
    - wry [RUST]: 0.28.3
    - tao [RUST]: 0.19.1
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.9

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
```

**Comment by jhutchins** [comment]
Turns out this is also easily reproducible with the vanilla javascript template. It looks like this is probably the critical error.

```
Uncaught (in promise) Scope not defined for window `main` and URL `https://tauri.localhost/`. See https://tauri.app/v1/api/config/#securityconfig.dangerousremotedomainipcaccess and https://docs.rs/tauri/1/tauri/scope/struct.IpcScope.html#method.configure_remote_access
```

**Comment by jhutchins** [comment]
You can apparently work around this issue by adding this config as a work around.
```
"security": {
  ...
  "dangerousRemoteDomainIpcAccess": [
    {
      "domain": "tauri.localhost",
      "windows": ["main"]
    }
  ]
},
```

**Comment by amrbashir** [comment]
@jhutchins should be fixed now, let me know if the issue persists

**Comment by jhutchins** [comment]
This appears to be resolved. Thanks!
