### ISSUE TITLE
[docs] tauri:Window wrong number of type arguments: expected 1, found 0 [E0107]

### ISSUE THREAD

**Issue by prongbang** [tauri-apps/tauri#7179]
Document 
https://tauri.app/v1/guides/features/events#window-specific-events-1

Error: tauri-1.3.0

<img width="957" alt="image" src="https://github.com/tauri-apps/tauri/assets/6635954/b0ddab1b-44b3-412f-a090-8bbeea222883">

how to use?

**Comment by FabianLars** [comment]
This is just the intellij-rust not fully covering the rust compiler. If you run `tauri dev` (or any other command that builds the rust part) it should still work fine. Also, intellij's auto-correct should be fairly accurate here, right? (didn't try it in a while).
Anyway, i think we should not document this as long as it's only the intellij rust plugin having this problem and not other ides/editors too (i'm aware of intellij's high-ish usage but still) - thanks for the report though ❤️ 

P.S. if the auto-correct is not good, it should look like this:
```rs
#[tauri::command]
fn init_process<R: tauri::Runtime>(window: Window<R>) {}
```

**Comment by prongbang** [comment]
Thank you ❤️
