### ISSUE TITLE
Is it possible to manually download building dependencies?

### ISSUE THREAD

**Issue by Ucag** [tauri-apps/tauri#718]
Platform:
win10 x86

My building process always pending on wix package downloading and finally result in an os error 10060.
I've checked the network, it works fine because I can manually download the wix package in my brwoser.
Is there any way to place my manually downloaded dependencies?
I've tried set global proxies or cargo proxies, both didn't work.

**Comment by lucasfernog** [comment]
Right now we always download the build deps, but we should improve that.

**Comment by zicklag** [comment]
I've got an issue with this too because it seems that it isn't downloading Wix through my HTTP proxy.

**Comment by nothingismagick** [comment]
I believe that @tensor-programming is going to be removing WIX entirely before we go to beta. If the issue arises again, please feel free to reopen.
