### ISSUE TITLE
[bug] tauri build not create updater files

### ISSUE THREAD

**Issue by Rivka-Shaked** [tauri-apps/tauri#7181]
### Describe the bug

I followed the updater instruction in - https://tauri.app/v1/guides/distribution/updater/ 
in tauri.conf.json changed bundle.targets to "updater" 
and when I run tauri build got this:

   **Compiling updaterwork v0.0.0 (C:\Users\rivka.shaked\Downloads\UPDATERWORK\src-tauri)
    Finished release [optimized] target(s) in 20.56s
    Finished 1 bundle at:

        Info 0 updater archives at:**

no file created in \target\release\bundle

### Reproduction

[UPDATERWORK.zip](https://github.com/tauri-apps/tauri/files/11721499/UPDATERWORK.zip)

### Expected behavior

Updater package will be created with zip and sig file

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 114.0.1823.43
    ✔ MSVC: Visual Studio Professional 2022
    ✔ rustc: 1.67.1 (d5a82bbd2 2023-02-07)
    ✔ Cargo: 1.67.1 (8ecd4f20a 2023-01-10)
    ✔ rustup: 1.25.2 (17db695f1 2023-02-01)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.14.0
    - npm: 9.3.1

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.3.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../src
    - devPath: ../src
```

**Comment by FabianLars** [comment]
So i'm not 100% sure what the intended behavior is but you'll have to add the bundle types the updater artifacts are based on, so app for macos, appimage for linux and msi or nsis for windows
