### ISSUE TITLE
[feat] Fixed dialog::message in macos window center

### ISSUE THREAD

**Issue by wyhaya** [tauri-apps/tauri#7182]
### Describe the problem

On macos, `dialog::message` always appears in the center of the `screen`, not in the center of the `window`.

![Preview](https://github.com/tauri-apps/tauri/assets/23690145/6091c0a4-43fe-4db7-a1c4-03aa1633ce00)

### Describe the solution you'd like

Fixed in the center of the window.

![Preview](https://github.com/tauri-apps/tauri/assets/23690145/553193b5-e982-4d86-8bd5-30f28284bc6e)

### Alternatives considered

I noticed that Tauri uses `rfd` crate, and uses `rfd::MessageDialog`, which doesn't seem to hold the dialog in the center of the window.

Consider using the asynchronous version of `rfd::AsyncMessageDialog` which should solve this problem.

### Additional context

```js
import { save, ask, message, open } from "@tauri-apps/api/dialog";
```

`save` and `ask` appear in the center of the window, `message` and `open` appear in the center of the screen.

**Comment by pewsheen** [comment]
It seems the `parent` window is used in the async version only.

Maybe we could let non-Linux target use `AsyncMessageDialog` just like it did in `FileDialog`?

https://github.com/tauri-apps/tauri/blob/d75c1b829bd96d9e3a672bcc79120597d5ada4a0/core/tauri/src/api/dialog.rs#L70-L75
