### ISSUE TITLE
[bug] Updater fails when using an NSIS installer requiring administrator access

### ISSUE THREAD

**Issue by Raphiiko** [tauri-apps/tauri#7184]
### Describe the bug

When I try to have my Tauri application update itself to a new version, it fails when the new version is bundled with an NSIS installer that has installMode `both`. 

What happens is that the update is started, it waits a bit (I'm imagining it's downloading the installer), and eventually quits the old version without launching the new one. No installer for the update shows. When the application is started again, it's still the old version and no update was installed.

When I run the old version of my application with `tauri dev` and I attempt to update from there, I get an error:

```
thread 'tokio-runtime-worker' panicked at 'installer failed to start: Os { code: 740, kind: Uncategorized, message: "The requested operation requires elevation." }', C:\Users\Raph.cargo\git\checkouts\tauri-9dcc2f9152472c1a\076e1a8\core\tauri\src\updater\core.rs:722:10
```

The issue gets resolved when I run my application as administrator, before trying to update.

### Reproduction

1. Set up a Tauri app and update your tauri.conf.json:
  a. Enable the updater functionality
  b. Set the version to 1.0.0
  c. Set the install mode for the NSIS installer to `both` or `perMachine` (Both require elevation)
2. Build a first version 
3. Build a second version with a higher version number (1.1.0)
4. Make the second version available as an update
5. Run the first version and attempt to update to the second version.

Notice how step 5 fails unless you run the first version as administrator.

### Expected behavior

When an outdated version of the application is run without elevation, I would expect the user to be given a UAC prompt when the NSIS installer for the update is run, should it require elevation. 

### Platform and versions

(This is on the latest versions of the `dev` branch)

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 114.0.1823.43
    ✔ MSVC: 
        - Visual Studio Build Tools 2019
        - Visual Studio Build Tools 2022
        - Visual Studio Community 2022
    ✔ rustc: 1.67.0 (fc594f156 2023-01-24)
    ✔ Cargo: 1.67.0 (8ecd4f20a 2023-01-10)
    ✔ rustup: 1.25.1 (bb60b1e89 2022-07-12)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.13.0
    - yarn: 1.22.19
    - npm: 8.19.3

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.1
    - tao [RUST]: git+https://github.com/tauri-apps/tao?branch=v0.16#ed6aab6b1226e56683798732ad01bf3f4658097e (0.16.0)
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.3.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist/oyasumivr
    - devPath: http://localhost:4200/
    - framework: Angular
    - bundler: Webpack
```
### Stack trace

```text
thread 'tokio-runtime-worker' panicked at 'installer failed to start: Os { code: 740, kind: Uncategorized, message: "The requested operation requires elevation." }', C:\Users\Raph.cargo\git\checkouts\tauri-9dcc2f9152472c1a\076e1a8\core\tauri\src\updater\core.rs:722:10
```

**Comment by jetli** [comment]
same here, and after updater is installed, two versions of the same app co-exist, one is controlled by NSIS and the other is controlled by msi.

**Comment by jetli** [comment]
and another question,  I don't see any updater files(.zip/.zip.sig) for NSIS in target/release/bundle. so MSI and NSIS share the same updater assets which are .msi.zip/.msi.zip.sig?

**Comment by FabianLars** [comment]
No, there should be `target/release/bundle/nsis/appname_ver_arch.nsis.zip/.sig` files

**Comment by jetli** [comment]
thanks, but I only have an xxx-setup.exe file there,  something wrong? I do have .zip/.sig files in msi dir.

**Comment by FabianLars** [comment]
idk it still works fine for me - just tested it for the message above because i couldn't remember the file names. Maybe you disabled the updater and the updater bundles you're seeing are from prior builds?

**Comment by jetli** [comment]
@FabianLars  thanks, I see, if I specify "targets": ["msi", "app", "dmg", "updater", "nsis"], in targets, then an updater is created for msi but no updater is created for nsis, if don't specify targets, then updater is created for both msi and nsis, I don't know if this is a bug or feature.

**Comment by FabianLars** [comment]
that's a bug, can you open a new issue for this please?

**Comment by jetli** [comment]
https://github.com/tauri-apps/tauri/issues/7349

**Comment by amrbashir** [comment]
closing, this issue is already fixed and will be available in the next release
