### ISSUE TITLE
[bug] Enumerate hidden directories on linux

### ISSUE THREAD

**Issue by podhorsky-ksj** [tauri-apps/tauri#7190]
### Describe the bug

Hi, I'm using in my code
```
readDir(path, { dir: BaseDirectory.Home, recursive: false });
```
from module "fs" and there is impossible to specify all subdirectories in "allowlist" -> "scope"

"**" can browse non-hidden directories like  
```
"$HOME/**/*.*"
```
, but not hidden directories. 
".**" is not accepted by tauri. And print error:
```
thread 'main' panicked at 'error while running tauri application: GlobPattern(PatternError { pos: 10, msg: "recursive wildcards must form a single path component" })', src/main.rs:52:10
```

I think all the hidden, non-hidden directories can be allowed by e.g.: 
```
$ echo {.**,**}/{.**,**}/{.*,*}
```

I haven't found a way, how to do this. I need to find all files across all the directories.

### Reproduction

In description. You can try search e.g. directory with .git directory

### Expected behavior

Enumerate hidden directories.

### Platform and versions

```text
$ npm run tauri info
 syncdirs@0.0.0 tauri
> tauri info


[✘] Environment
    - OS: Fedora 38.0.0 X64
    ✔ webkit2gtk-4.0: 2.40.2
    ✘ rsvg2: not installed
      Visit https://tauri.app/v1/guides/getting-started/prerequisites to learn more about tauri prerequisites
    ✔ rustc: 1.70.0 (90c541806 2023-05-31) (Fedora 1.70.0-1.fc38)
    ✔ Cargo: 1.70.0
    ⚠ rustup: not installed!
      If you have rust installed some other way, we recommend uninstalling it
      then use rustup instead. Visit https://rustup.rs/
    ⚠ Rust toolchain: couldn't be deteceted!
      maybe you don't have rustup installed? if so, Visit https://rustup.rs/
    - node: 18.16.0
    - yarn: 1.22.19
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 1.2.4
    - tauri-build [RUST]: 1.2.1
    - wry [RUST]: 0.23.4
    - tao [RUST]: 0.15.8
    - @tauri-apps/api [NPM]: 1.3.0
    - @tauri-apps/cli [NPM]: 1.3.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
npm notice 
npm notice New minor version of npm available! 9.5.1 -> 9.7.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.7.1
npm notice Run npm install -g npm@9.7.1 to update!
npm notice
```
```


### Stack trace

_No response_

### Additional context

I'm doing my own synchonization file manager and I need sync all the files. Not skip some of them because of this issue.

**Comment by amrbashir** [comment]
In the next release, there will be an option to specify `require_literal_leading_dot` so you will be able to do this:
```rs
"scope": {
	"allow": ["$HOME/**"],
	"require_literal_leading_dot": false,
}
```

**Comment by podhorsky-ksj** [comment]
Sorry, which version it will be? I can't find a commit. I have done upgrade of the project and nothing changed

Also, I didn't understand the construction:
```
"scope": {
	"allow": ["$HOME/**"],
	"require_literal_leading_dot": false,
}
```

Does it mean this will work for my purposes?
```
"scope": {
	"allow": [
          "$HOME/**/.*",
          "$HOME/**/*"],
	"require_literal_leading_dot": true,
}
```

or this?
```
"scope": {
	"allow": [
          "$HOME/{.**,**}/{.**,**}/{.*,*}"
        ],
	"require_literal_leading_dot": true,
}

```

I need to get access for every subfolder in directory, regardless they are hidden (with . prefix) or not.

**Comment by amrbashir** [comment]
This is available in `1.4` and this should be enough for your usage:
```json
"scope": {
	"allow": ["$HOME/**"],
	"require_literal_leading_dot": false,
}
```

**Comment by podhorsky-ksj** [comment]
Hmm, I'm not sure, if it is working properly, like it is supposed to.

with $HOME/** it doesn't work.

/home/ksj/ is $HOME

```
[Log] path not allowed on the configured scope: /home/ksj/TRASH/syncdirs/.git
[Log] path not allowed on the configured scope: /home/ksj/TRASH/syncdirs/src-tauri/target/debug/.fingerprint
...
```

But I have found out, this seems to be working:

```
        "scope": {
          "allow": [
          "$HOME/**",
          "$HOME/**/*.*",
          "$HOME/**/*.*/**"
        ],
        "require_literal_leading_dot": false
        }
```

**Comment by amrbashir** [comment]
This works fine for me
```json
"scope": {
	"allow": ["$HOME/**"],
	"require_literal_leading_dot": false,
}
```

if still having issues, please make a minimal repro

**Comment by podhorsky-ksj** [comment]
Like I have shown in previous comment. With your code it fail in reading hidden subdirectories. Have you tried something like me? so, the git repo or project (with hidden directories) and not in $HOME directory, but lower?

**Comment by amrbashir** [comment]
I did try it with `recursive: true` and `recursive: false` and both worked as expected, tested by reading `$HOME/.local` directory which had this directory structure:
```
$HOME/
  |_.local/
  	|_ bin
  	|_ share
  	|_ .hidden_dir
  		|_ .hidden_file

```

**Comment by podhorsky-ksj** [comment]
that's interesting.

I tried your code again, and it is the same:
```
[Log] path not allowed on the configured scope: /home/ksj/syncdirs/.git
```

The command which returns these errors is:
```
readDir(path, { dir: BaseDirectory.Home, recursive: false });
```

I tried to remove dir: BaseDirectory.Home and set recursive to true, but it has the same result.
It is strange, that it works for you and not for me.

I can use my functional config, but it will be better to have shorter code and make this working.
I have no idea, where can be the issue. The tests are similar...

**Comment by amrbashir** [comment]
That's why I need you to make a minimal repro that doesn't work for you, along with the directory structure you're trying to read

**Comment by podhorsky-ksj** [comment]
Ok, there:
[syncdirs.zip](https://github.com/tauri-apps/tauri/files/11938431/syncdirs.zip)


I have hardcoded to code /home/ksj/syncdirs, so change it to place where you extract the directory.  /home/ksj is $HOME

just run "yarn && yarn tauri run" and open console window.

**Comment by amrbashir** [comment]
Please don't upload an archive of a project, instead make a public repository and upload the code there.

**Comment by podhorsky-ksj** [comment]
It is not whole project. I removed a lot of code. The short code, where we are looking for issue is just in App.tsx. Everything else is just default configuration or unused. Except the tauri config a package.json.
I put it it there, if you want to check the configuration.

I will put my code in some public repository in future, when i will check the init version is working properly. 

But make a repository for just one file of code? Which cannot be used for anything else than check the issue and then will be deleted/made obsolete? I don't like it much...

**Comment by amrbashir** [comment]
> But make a repository for just one file of code? Which cannot be used for anything else than check the issue and then will be deleted/made obsolete? I don't like it much...

That is pretty much what a minimal reproduction repo means, you can use a different account to host it or any other GitHub alternative. Archived files could be dangerous to download for me as a maintainer and anyone who happens to pass by this issue.


And I would recommend reading theses resourse: 
- https://stackoverflow.com/help/minimal-reproducible-example
- [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by podhorsky-ksj** [comment]
Ok, next time i will upload only app.tsx. it is only file you need. It is up to you if you want to use anything else:-). 

I just wanted to create working solution for you to speed it up, when you asked for minimal reproducible solution. This code exactly reproduces the same issue i have.

So, are there any error in app.tsx, which explains the issue?

**Comment by amrbashir** [comment]
> Ok, next time i will upload only app.tsx. it is only file you need. It is up to you if you want to use anything else:-).

I don't need only `app.tsx`, I need a fully working project but contains the minimalist code to reproduce the issue, that I can run without needing much setup which would allow me to investigate the issue faster. 

> I just wanted to create working solution for you to speed it up, when you asked for minimal reproducible solution. This code exactly reproduces the same issue i have.
> So, are there any error in app.tsx, which explains the issue?

I haven't used the archive you posted so I don't know what is the exact issue yet, I am waiting on a public repo. No offense but anonymous archives could be dangerous to open.

**Comment by podhorsky-ksj** [comment]
For me zip package and some repo link is similarly dangerous. But ok.
There you have it in repo https://github.com/podhorsky-ksj/tauri-fs-bug

**Comment by amrbashir** [comment]
> For me zip package and some repo link is similarly dangerous. But ok.

Not really, one could be investigated and ensured is safe before downloading, and one could run arbitrary code when even opened in a zip viewer before extraction.

**Comment by amrbashir** [comment]
found the issue and it is my bad, sorry about that, the config should be: 
```json
"scope": {
	"allow": ["$HOME/**"],
	"requireLiteralLeadingDot": false,
}
```

notice the camelCase

**Comment by podhorsky-ksj** [comment]
confirm, with this config it is now ok.
Are you going to put this to fs documentation? https://tauri.app/v1/api/js/fs/

**Comment by amrbashir** [comment]
it is documented here https://tauri.app/v1/api/config#fsallowlistscope.requireliteralleadingdot

**Comment by amrbashir** [comment]
you shouldn't rely on the config option in the JS module documentations because they are written manually and can get out-of-sync, while the config documentation is auto-generated and will always be updated with new releases.

**Comment by iSuslov** [comment]
Hey @amrbashir, how this can be configured for Tauri 2.0? Doc is really confusing: https://v2.tauri.app/references/config/#fsscope
fs plugin seems to not have "requireLiteralLeadingDot" key in capabilities settings.

**Comment by amrbashir** [comment]
@iSuslov  in v2, the option is moved to the plugins config
```json
{
  ..
  "plugins": {
    "fs": {
      "requireLiteralLeadingDot": false
    },
    ..
  },
  ..
}
```
