### ISSUE TITLE
[bug] MouseUp Event Occurs Before MouseDown in macOS when using Tap-to-Click within input fields

### ISSUE THREAD

**Issue by qinluhe** [tauri-apps/tauri#7219]
### Describe the bug

When using the Tap-to-Click feature on macOS, the MouseUp event occurs before the MouseDown event within input fields.

https://github.com/tauri-apps/tauri/assets/108015703/9250445a-e56c-4732-b4ba-e726e29d7d6c

PS: Only reproduces when Tap-to-Click is activated and used, not if normal click it down is used

### Example
[git@github.com:qinluhe/tauri-app-demo.git](https://github.com/qinluhe/tauri-app-demo)

### Reproduction

1. Open the application and navigate to an input field.
2. Enable Tap-to-Click functionality in the macOS settings.
3. Use Tap to Click to click the input box multiple times
4. Notice that the MouseUp event happens before the MouseDown event.

### Expected behavior

The expected behavior is for the MouseUp event to occur after the MouseDown event when using Tap-to-Click in macOS.

### Platform and versions

```text


[✔] Environment
    - OS: Mac OS 13.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.70.0-nightly (db0cbc48d 2023-03-26)
    ✔ Cargo: 1.70.0-nightly (15d090969 2023-03-21)
    ✔ rustup: 1.25.2 (17db695f1 2023-02-01)
    ✔ Rust toolchain: nightly-aarch64-apple-darwin (default)
    - node: 18.16.0
    - pnpm: 8.5.0
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1421/
    - framework: React
    - bundler: Vite

```

**Comment by pewsheen** [comment]
Hmm... I followed AppFlowy's [tauri-setup](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/tauri-setup), and the `mouseup` does emit after `mousedown`

Do you know if this happens in other Tauri app examples?

**Comment by qinluhe** [comment]
> Hmm... I followed AppFlowy's [tauri-setup](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/tauri-setup), and the `mouseup` does emit after `mousedown`
> 
> Do you know if this happens in other Tauri app examples?

Thanks for your reply.
Only reproduces when Tap-to-Click is activated and used, not if normal click it down is used.
Use Tap to Click to click the input box multiple times.
This is a Tauri app example: [git@github.com:qinluhe/tauri-app-demo.git](https://github.com/qinluhe/tauri-app-demo)

**Comment by qinluhe** [comment]
This bug also occurs in Safari, so it can be closed

**Comment by pewsheen** [comment]
Thanks for your testing!

Just for a record that the event is emitted in the correct order in my macOS 13.4 and 14 devices.

**Comment by qinluhe** [comment]
> Thanks for your testing!
> 
> Just for a record that the event is emitted in the correct order in my macOS 13.4 and 14 devices.

Maybe I should upgrade my system too, mine is 13.2.1

**Comment by qinluhe** [comment]
> Thanks for your testing!
> 
> Just for a record that the event is emitted in the correct order in my macOS 13.4 and 14 devices.

Frustratingly, when I upgraded to 13.4.1, this problem persists
But I think I can use some very hack solutions to solve the problems caused by this bug.
Although such a solution is disconcerting

**Comment by egoist** [comment]
this also happened to me when i'm using Japanese - Romaji and some Chinese Input Methods, here's the related webkit bug report:

 https://bugs.webkit.org/show_bug.cgi?id=219670#c32
