### ISSUE TITLE
use `resources` config, can not bundle empty directory [bug] 

### ISSUE THREAD

**Issue by largezhou** [tauri-apps/tauri#7221]
### Describe the bug

use `resources` config, can not bundle empty directory

### Reproduction

![image](https://github.com/tauri-apps/tauri/assets/13796692/dd351753-cb9a-4c6e-a00c-042e2c1f6fe5)
![image](https://github.com/tauri-apps/tauri/assets/13796692/2d0ca9fc-8a8f-4bfe-95ee-f979ddb29ead)

### Platform and versions

```text
[✘] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 114.0.1823.43
    ✘ Couldn't detect Visual Studio or Visual Studio Build Tools. Download from https://aka.ms/vs/17/release/vs_BuildTools.exe
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.12.1
    - pnpm: 8.6.2
    - yarn: 1.22.19
    - npm: 8.19.2

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.1
    - @tauri-apps/api [NPM]: 1.3.0 (outdated, latest: 1.4.0)
    - @tauri-apps/cli [NPM]: 1.3.1 (outdated, latest: 1.4.0)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:5173/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by redpanzer1** [comment]
I Will fixed

**Comment by amrbashir** [comment]
It doesn't make any sense to bundle an empty directory. If you feel like you have a valid use-case for it, please let me know what it is and I will re-open.

**Comment by largezhou** [comment]
> It doesn't make any sense to bundle an empty directory. If you feel like you have a valid use-case for it, please let me know what it is and I will re-open.

I am working on an integrated development environment for PHP + Nginx on the Windows platform. When packaging, it will include both PHP and Nginx. Within Nginx, there are a few empty directories that are necessary; without them, Nginx will throw an error upon startup.

**Comment by amrbashir** [comment]
Sounds more like Nginx doesn't have enough permissions to create these directories, where do you install your app?

**Comment by largezhou** [comment]
> Sounds more like Nginx doesn't have enough permissions to create these directories, where do you install your app?

![image](https://github.com/tauri-apps/tauri/assets/13796692/1e9cc511-4f93-4f51-989c-07f9e5c4084b)

The error message indicates that nginx did not attempt to create the logs directory. Instead, it directly created the logs/error.log file. Moreover, I executed the command as an administrator, so there shouldn't be any permission issues.

**Comment by amrbashir** [comment]
cc @lucasfernog , is bundling empty directory something we want to do?

**Comment by amrbashir** [comment]
@largezhou for now, a temporary solution, you can just simply add a dummy file in the empty directory and it should bundle it.
