### ISSUE TITLE
[feat] Expose with_navigation_handler hook via app's Builder

### ISSUE THREAD

**Issue by fudanchii** [tauri-apps/tauri#7222]
### Describe the problem

wry have this `with_navigation_handler` exposed via `WebviewBuilder` which, in Tauri, being encapsulated as part of `PendingWindow` configuration. Unfortunately, since `PendingWindow` mainly reads from config, there's no straightforward mechanism to inject this navigation handler to Webview.

### Describe the solution you'd like

I would like to propose to expose an API as part of Tauri::app::Builder to inject navigation handler to Webview, 

e.g.

```rust
    tauri::Builder::default()
        .navigation_handler("main_window", |url: &str| -> bool { url.starts_with("https://my.tauri.app") })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
```

Since `PendingWindow` stored as a `Vec` here, I proposed to use label to match the window and store this as `HashMap<String, Box<dyn Fn(Url) -> bool + Send>>`, this will then applied at `build` invocation, iterating through the `PendingWindow`, assign each `navigation_handler` by its label.

### Alternatives considered

I don't have alternatives right now, comments and more suggestions are welcome.

### Additional context

`navigation_handler` may be used to block the Webview from navigating to certain or any unruled URLs, this is useful in the case when we use Tauri to act as a sandbox platform for existing web app and we want to prevent user from navigating outside the app through existing links in the app's content.

I'm willing to implement this, but would like to know if other think this is sound or not.

**Comment by FabianLars** [comment]
Does [on_navigation](https://docs.rs/tauri/latest/tauri/window/struct.WindowBuilder.html#method.on_navigation) added in 1.3 work for you? Or is the issue with that, that you can't configure the window in tauri.conf.json anymore?

**Comment by fudanchii** [comment]
@FabianLars Yes it works, it's a bit awkward since I have to empty window config in tauri.conf.json, but I can live with it. Thank you!
