### ISSUE TITLE
[bug] no reading of external Url in build in expo/tauri project

### ISSUE THREAD

**Issue by sweatben** [tauri-apps/tauri#7225]
### Describe the bug

Hello everyone, 

Tauri is a great tool but could you help me? I don't know if it's a bug or a tauri configuration problem on my part.

When I read the problems, I tried a lot of things with no result. 

In my Tauri/expo project, I can't play audio from an external url once I've built it, whereas in dev mode there's no problem.

Thanks in advance for your help.
![Sans titre](https://github.com/tauri-apps/tauri/assets/49415544/5fd9b096-3c6b-4046-8821-9ddb70fa0277)

### Reproduction

repo for reproduction

https://github.com/sweatben/tauri_expo-av_test

### Expected behavior

Once build play audio via expo-av for an external url

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 114.0.1823.43
    ✔ MSVC:
        - Visual Studio Build Tools�2019
        - Visual Studio Community 2022
    ✔ rustc: 1.67.0 (fc594f156 2023-01-24)
    ✔ Cargo: 1.67.0 (8ecd4f20a 2023-01-10)
    ✔ rustup: 1.25.2 (17db695f1 2023-02-01)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.14.0
    - yarn: 1.22.19
    - npm: 9.7.1

[-] Packages
    - tauri [RUST]: 1.4.0
    - tauri-build [RUST]: 1.4.0   
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../build
    - devPath: http://localhost:19006/
    - framework: React
    - bundler: Webpack
```

**Comment by FabianLars** [comment]
i'm not completely sure if that changes the result, but i had to change distDir to ../web-build and use `npx expo export:web` (because `npm run build-web` told me too) and the audio worked fine for me.
Does changing these things change the build output? If so, what are the exact reproduction steps i should take with your repro?

**Comment by sweatben** [comment]
ok, for this 'issue' I've redone a clean project where indeed you need ```npx expo export:web```, change distDir and change identifier (not valid).

I should have tested it before because during my other tests I did ```npm audit fix``` in view of the errors. It's certainly audit fix that was breaking the links of my dependencies.

audio work for me too, I'm sorry for the inconvenience

In any case, thank you very much for your responsiveness!

I really appreciate tauri thank you for your work and involvement.

**Comment by sweatben** [comment]
not a bug, it's an setup error on my part

**Comment by sweatben** [comment]
Hello.  I restarted a clean main project, I still can't play the audio, but I found the error, does not seem to cause ``npm audit fix``, it's just that my resources are ``http`` and not ``https``.
I tried, as the doc says, to add : 
```
{
  "tauri": {
    "allowlist": {
      "http": {
        "all": true, // enable all http APIs
        "request": true // enable HTTP request API
      }
    }
  }
}
```
and/or add scope without success

**Comment by FabianLars** [comment]
the http scope is only applied to tauri's [http client](https://tauri.app/v1/api/js/http), nothing else.

So i guess you're hitting this: https://github.com/tauri-apps/tauri/issues/3007 - there are a few workarounds in there but the most common one is probably the [localhost plugin](https://github.com/tauri-apps/plugins-workspace/tree/v1/plugins/localhost) unless you can make your resource use https.
