### ISSUE TITLE
[bug] @tauri-apps/api/event listen type

### ISSUE THREAD

**Issue by Massimiliano-solutiontech** [tauri-apps/tauri#7244]
### Describe the bug

In TypeScript when using the `listen<T>((event))` the type of `event.payload` is not longer inferred from `T` but is `any`

![Screenshot 2023-06-17 alle 21 39 20](https://github.com/tauri-apps/tauri/assets/75322363/6b373d01-265b-4276-b0fb-49cd960300a9)

### Expected behavior

`event.payload` is `T`

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.3.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 18.12.1
    - npm: 8.19.2

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.1
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Rollup
```

**Comment by lucasfernog** [comment]
I can't really reproduce. Are you sure `@tauri-apps/api` is installed (did you run `npm install`)? Can you share an example repo we can use to see it?

**Comment by Massimiliano-solutiontech** [comment]
I tried deleting `node_modules` and reinstall all by doing `npm i` and the issue is gone, I really don't know what happened
