### ISSUE TITLE
[bug] The Open button is missing when opening with Control-Click on MacOS

### ISSUE THREAD

**Issue by APerson4f** [tauri-apps/tauri#7249]
### Describe the bug

Previously, when you opened a .app with Control-Click, the window "Can't be opened because it is from an unidentified developer" would open and the app could be opened.
Now the Open button is gone.

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.4.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.71.0-nightly (4a59ba4d5 2023-05-12)
    ✔ Cargo: 1.71.0-nightly (13413c64f 2023-05-10)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: nightly-x86_64-apple-darwin (default)
    - node: 18.16.0
    - yarn: 1.22.19
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 1.4.0
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by startup-stack-sculptor** [comment]
Well, one way to get around the issue is 

> Open the "Security & Privacy" settings in your macOS system preferences. Under the "General" tab, ensure that the "Allow apps downloaded from:" option is set to "App Store and identified developers."

**Comment by APerson4f** [comment]
The "Allow apps downloaded from:" option is set to "App Store and identified developers." but the button still does not appear when you first open it

**Comment by APerson4f** [comment]
The problem only with tauri and it appeared after the macOS upgrade to 13.4
