### ISSUE TITLE
[bug] onThemeChanged listener async doesn't work.

### ISSUE THREAD

**Issue by billyjacoby** [tauri-apps/tauri#7262]
### Describe the bug

Using the code linked in [the docs](https://tauri.app/v1/api/js/window/#onthemechanged) doesn't work as expected. The `onThemeChanged` function will only return a callable function if `awaited`, however calling it asynchronously stops the listener from being called. 

I worry that not calling the unlisten function could lead to un expected results. 

### Reproduction

Doesn't work:
```typescript
  React.useEffect(() => {
    (async () => {
      // TODO: the docs say this should be awaited, but when it is it stops working
      //? https://tauri.app/v1/api/js/window/#onthemechanged
      const unlisten = await appWindow.onThemeChanged(({ payload: theme }) => {
        setSystemTheme(theme);
      });

      return unlisten();
    })();
  }, []);
```

This fires the event but then `unlisten` can't be called on unmount:
```typescript
  React.useEffect(() => {
    (async () => {
      // TODO: the docs say this should be awaited, but when it is it stops working
      //? https://tauri.app/v1/api/js/window/#onthemechanged
      appWindow.onThemeChanged(({ payload: theme }) => {
        // setSystemTheme(theme);
      });
      if (
        isDarkMode ||
        (!('theme' in localStorage) &&
          window.matchMedia('(prefers-color-scheme: dark)').matches)
      ) {
        document.documentElement.classList.add('dark');
      } else {
        document.documentElement.classList.remove('dark');
      }
    })();
  }, [isDarkMode, systemTheme]);
```

### Expected behavior

Either `onThemeChanged` returns the proper unlistening function when not called asynchronously, or the `onThemeChanged` calls the callback when called asynchronously.

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.5.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 18.16.0
    - yarn: 3.5.0
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 1.4.0
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
```

**Comment by amrbashir** [comment]
I couldn't reproduce, please make a minimal reproduction

**Comment by billyjacoby** [comment]
Sure thing, repo can be found here:

https://github.com/billyjacoby/tauri-on-theme-change

**Comment by amrbashir** [comment]
Ah I should've noticed earlier, you are immediately calling `unlisten` afterwards in this line
```ts
      return unlisten();
```
so the listener gets removed immediately. Now I am no react developer but it should be like this:
```ts
  React.useEffect(() => {
  	let unlisten;
    appWindow.onThemeChanged(({ payload: theme }) => {
        setSystemTheme(theme);
   	}).then(u => unlisten = u);
   	return () => {
   		unlisten && unlisten()
   	}
  }, []);
```

**Comment by billyjacoby** [comment]
🤦🏼 I'm seeing a race condition in my app, but I don't think it's related to this. Thanks for the clarity!
