### ISSUE TITLE
能够提供隐藏关闭，最大最小窗口按钮支持圆角的功能？

### ISSUE THREAD

**Issue by Neo110** [tauri-apps/tauri#7265]
### Describe the problem

能够提供隐藏关闭，最大最小窗口按钮支持圆角的功能？

### Describe the solution you'd like

能够提供隐藏关闭，最大最小窗口按钮支持圆角的功能？

**Comment by simonhyll** [comment]
Google translate:
> Able to provide hidden close, maximum and minimum window buttons support the function of rounded corners
Is it possible to provide the function of hiding and closing, the maximum and minimum window buttons supporting rounded corners?

**Comment by FabianLars** [comment]
If you mean the native window controls then it will only work on platforms that already have rounded corners with the native window decorations (macos, linux(?) and windows 11). Win7 - Win10 can only have rounded corners via css (there are no OS apis we can use as far as i know) which means you'll lose the _native_ window controls meaning you'd have to simulate them in html/js similar to https://tauri.app/v1/guides/features/window-customization/
