### ISSUE TITLE
[feat] Configurable Proxy For The Http API

### ISSUE THREAD

**Issue by obrhaberer** [tauri-apps/tauri#7267]
### Describe the problem

I would appriciate if the HttpOptions would include a proxy property like the browser fetch api. Alternatively one could define a proxy for the tauri client.

### Describe the solution you'd like

Implement a new property for HttpOptions for tauris fetch api. So the rust backend would use this proxy for the http-call.

### Alternatives considered

mplement a new property for ClientOptions. So the rust backend would use this proxy for every http-call.

### Additional context

Currently there is no easy way to configure a proxy for the http api calls inside tauri. Sometimes a configurable proxy is mendetory within enterprise rulesets.

**Comment by FabianLars** [comment]
Thanks for the request! We're already tracking it here: https://github.com/tauri-apps/tauri/issues/6467
