### ISSUE TITLE
Bundled msi files failed to run on Win7 Enterprise

### ISSUE THREAD

**Issue by jwenjian** [tauri-apps/tauri#727]
**Describe the bug**
After installed the tauri bundled app on Win7 Interprise, error happened:

Entry Point Not Found:

> The procedure entry point CoIncrementMTAUsage could not be located in the dynamic link library ole32.dll

**To Reproduce**
1. Download [LuckyYou_1.0.0.msi]()
2. Install it on Win7 Enterprise
3. Open the installed app

**Expected behavior**
The app runs normally after install

**Screenshots**

![Snipaste_2020-06-30_15-06-50](https://user-images.githubusercontent.com/25657798/86094855-a661ef00-bae3-11ea-9a2a-89a7a8fdbc84.png)

**Platform and Versions (please complete the following information):**

OS: Win 7 Enterprise

**Additional context**
Microsoft defender reports the msi file as a harmful app, and I click "Keep anyway"

**Stack Trace**
No.

**Comment by nothingismagick** [comment]
When an operating system reaches EOL (i.e. the manufacturer is no longer providing security updates), it is hard for us to justify spending time making sure that Tauri works. Win7 / WinXP / MacOS < 10.10 are not things that we will be able to prioritise.

I understand how this can be frustrating, but WebView on windows is such a painfully moving target I am really not sure how we could do this.

**Comment by nightshadecf** [comment]
I believe this can be fixed.
It is fixed with itchio app. 
Please take a look, thank you.

https://github.com/itchio/husk/blob/bacfc9507b186285c54ca79182d20f4fc893f3d3/src/windows/runtime.rs

**Comment by SOVLOOKUP** [comment]
I hope tauri can support win7. It's very important to me.

Many government agency customers still use win7.

and now webview2 support win7 too.

**Comment by uixdimi** [comment]
Bump, this happens on the latest v2

**Comment by xinyii** [comment]
After tauri v1 removed the notification feature, this error disappeared.

**Comment by ithustle** [comment]
> I believe this can be fixed. It is fixed with itchio app. Please take a look, thank you.
> 
> https://github.com/itchio/husk/blob/bacfc9507b186285c54ca79182d20f4fc893f3d3/src/windows/runtime.rs

Hi, @nightshadecf. Could you, please, explain how to solve using this?
