### ISSUE TITLE
[bug] <base target="_blank"> doesn't open external links in the browser

### ISSUE THREAD

**Issue by neongreen** [tauri-apps/tauri#7285]
### Describe the bug

If Tauri sees a link with `target="_blank"`, it opens it in the browser as opposed to the Tauri window (with shell-open enabled).

It's possible to add `<base target="_blank">` inside `<head>` to force this behavior for all links. However, Tauri doesn't respect this. Clicking on external links with `<base target="_blank">` enabled just does nothing at all.

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.4.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 16.18.0
    - pnpm: 7.0.1
    - yarn: 1.22.19
    - npm: 8.19.2

[-] Packages
    - tauri [RUST]: 1.2.4
    - tauri-build [RUST]: 1.2.1
    - wry [RUST]: 0.23.4
    - tao [RUST]: 0.15.8
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../web-tauri
    - devPath: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Webpack
```

**Comment by langonginc** [comment]
I have the same problem. I use it as `<xxx onclick={() => window.open('https://github.com', '_blank')}>`. 

(I can run it normally on Windows computer, but not working on macOS)

**Comment by kaikaibenkai** [comment]
+1. It has the effect of looking like another WebView window rather than an external browser.
![image](https://github.com/tauri-apps/tauri/assets/99722991/7daa95b2-7f2a-4df3-9aef-9e1e396776e3)
