### ISSUE TITLE
[bug] 'select' tag menu has a 'Times New Roman' font instead of the native one

### ISSUE THREAD

**Issue by akinsella** [tauri-apps/tauri#7286]
### Describe the bug

The 'select' tag menu does not have the native font family which is replaced by a 'Times New Roman' one.
This issue appeared some days/weeks ago, but cannot tell when exactly. 

Could it be related to some system update as the warning message seems to suggest a different way to configure font (which might be a new default/better way to configure font ?)

Here are screenshots showing up the issue:

<img width="352" alt="Screenshot-20230624-111337@2x" src="https://github.com/tauri-apps/tauri/assets/322456/c270008e-77f4-4ae2-af2f-a2921eccfef7">
<img width="354" alt="Screenshot-20230624-111325@2x" src="https://github.com/tauri-apps/tauri/assets/322456/1ddcc3dd-231a-4224-a3bd-26b82e12003b">

And, here is the message that I get in the console:
<img width="1191" alt="Screenshot-20230624-113210@2x" src="https://github.com/tauri-apps/tauri/assets/322456/ca40d44f-ac62-4668-bc61-bdb55c57596e">

### Reproduction

I use a default select tag styled by DaisyUI 3.1.6 and Tauri v1.4.0 on MacOS Ventura 13.4 (Mac Silicon m1).
This should be reproducible on this configuration even thought I did not try to build a dedicated app to reproduce specifically the issue.

Here is the code used to create the select tag with react (+react-hook-form):

```
                <select
                    {...register("format", { required: true })}
                    className="select select-primary w-full notranslate"
                    disabled={loading ? true : undefined}
                >
                    <option disabled>Format</option>
                    <option value="avif">AVIF</option>
                    <option value="bmp">BMP</option>
                    <option value="gif">GIF</option>
                    <option value="ico">ICO</option>
                    <option value="jpeg">JPEG</option>
                    <option value="png">PNG</option>
                    <option value="tiff">TIFF</option>
                    <option value="webp">WEBP</option>
                </select>
```

### Expected behavior

Should create a select tag with a menu that have the native font.

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.4.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.3.0
    - yarn: 1.22.19
    - npm: 9.6.7

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.1
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: default-src 'self'; img-src 'self' asset: https://asset.localhost data:; media-src 'self' asset: https://asset.localhost;
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
npm notice 
npm notice New minor version of npm available! 9.6.7 -> 9.7.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.7.2
npm notice Run npm install -g npm@9.7.2 to update!
npm notice
```

**Comment by pewsheen** [comment]
It also happens in DaisyUI's component doc https://daisyui.com/components/select/

After some tries, I think this might be a CSS issue that DaisyUI is using `font-weight: 600` and `AppleSystemUIFont` doesn't have the weight, so it fallback to `Times New Roman`.

You can try applying `font-weight: 400` on `<select>` and see if the `font-family` is correct.

**Comment by akinsella** [comment]
This is amazing @pewsheen ! Thank you so much for your help and finding the cause of the problem. The `font-weight: 400` change actually works perfectly. This is a bit frustrating to see that `font-weight: 600` does not make it on Safari as it works perfectly fine on Chrome but having a `font-weight: 400` is way better than having a `Times New Roman` font that is very different from the rest of the UI 😁
