### ISSUE TITLE
[docs] Add Node.js as a prerequisite

### ISSUE THREAD

**Issue by loic-sharma** [tauri-apps/tauri#7288]
The Windows prerequisite page does not mention Node.js: https://tauri.app/v1/guides/getting-started/prerequisites

Installing Tauri without Node.js results in the following warning:

```
PS C:\Users\WDAGUtilityAccount> irm https://create.tauri.app/ps | iex
info: downloading create-tauri-app
...

Template created!

Your system is missing dependencies (or they do not exist in $PATH):
╭──────────┬─────────────────────────────────────────────────────────╮
│ Node.js  │ Visit https://nodejs.org/en/                            │
╰──────────┴─────────────────────────────────────────────────────────╯

Make sure you have installed the prerequisites for your OS: https://tauri.app/v1/guides/getting-started/prerequisites, then run:
  cd tauri-app
  pnpm install
  pnpm tauri dev
```

**Comment by amrbashir** [comment]
Node.js is not a prerequisite for tauri itself, but you probably chose a package manager or a template that requires Node.js so you need to install it before you can use that template.

**Comment by amrbashir** [comment]
Node.js is not a prerequisite for tauri itself, but you probably chose a package manager or a template that requires Node.js so you need to install it before you can use that template.
