### ISSUE TITLE
Detected as a virus by MCAfee

### ISSUE THREAD

**Issue by lorypelli** [tauri-apps/tauri#7292]
### Describe the bug

While installing with `cargo install tauri-cli` it was detected as a virus and blocked. You should fix this

### Platform and versions

```text
Rust 1.70.0
```

**Comment by FabianLars** [comment]
Honestly, there is not much we can do. Many anti-virus programs can't handle compiled programming languages, after all they do stuff that you normally don't wanna see programs doing. In the case of rust it's creating multiple executables and executing them.

Probably the best bet is to report false positives to mcaffee which we can't do ourselves.

p.s. for issues like this please include logs or any kind of info so it's easier to search and depending on the issue potentially solvable in case of more widely known causes.
