### ISSUE TITLE
Unexpected Notification Dialog When Attempting to Open Dialog in Full or Minimized Mode [bug] 

### ISSUE THREAD

**Issue by Mohmn** [tauri-apps/tauri#7294]
### Describe the bug

When trying to open a dialog in response to an event, an unusual notification pops up stating "{appname} is ready". The peculiar part is that this notification only appears when the application is either in full mode or minimized mode
![Screenshot from 2023-06-25 23-46-05](https://github.com/tauri-apps/tauri/assets/37132584/30db39f8-81b7-4680-ab3e-62eb4d0be1f9)

### Expected behavior

When the user triggers the event to open a dialog, the dialog box should open  without any unexpected notifications.

### Platform and versions

```text
[✔] Environment
    - OS: Ubuntu 20.04 X64
    ✔ webkit2gtk-4.0: 2.38.6
    ✔ rsvg2: 2.48.9
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 20.0.0
    - npm: 9.6.4

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by amrbashir** [comment]
Could you share a minimal repro?

**Comment by FabianLars** [comment]
I get that notification for soooo many apps recently. I feel like a recent gnome update made this 10 times worse and idk if we can really prevent this on tauri's side... There are even gnome extensions that can completely disable it for all apps because it annoys that many people 😅

**Comment by Mohmn** [comment]
> Could you share a minimal repro?

the actual repo where the problem occurs i can't share that one, 
i wasn't able it reproduce it in the minimal repo

**Comment by Mohmn** [comment]
> I get that notification for soooo many apps recently. I feel like a recent gnome update made this 10 times worse and idk if we can really prevent this on tauri's side... There are even gnome extensions that can completely disable it for all apps because it annoys that many people 😅

ah thanks for the info , will try to tackle the problem from the genome percipective
