### ISSUE TITLE
[feat] expose download_url in UpdateResponse

### ISSUE THREAD

**Issue by vangork** [tauri-apps/tauri#7297]
### Describe the problem

In some poor network connectivity conditions, [download_and_install](https://docs.rs/tauri/latest/tauri/updater/struct.UpdateResponse.html#method.download_and_install) would last for too long and even get stuck.

### Describe the solution you'd like

I would like to expose a way to redirect the download request to the browser to enable other download tool to accelerate & breakpoint resume so that the user would download & install manually.
In this case, please expose `download_url` in UpdateResponse, that will make it possible.

**Comment by amrbashir** [comment]
This will be available in the plugin updater for v2 see https://github.com/tauri-apps/plugins-workspace/pull/431/files, which will expose the `download_url` and will have a `update.download()` to download the updater package and `update.install(bytes)` where `bytes` is the updater package downloaded by `update.download()` or one that the user has downloaded and the app reads it from disk
