### ISSUE TITLE
[feat] Updater download and install separate 

### ISSUE THREAD

**Issue by ppbl** [tauri-apps/tauri#7300]
### Describe the problem

On windows, The updater will automatically restart after downloading

### Describe the solution you'd like

On windows, Updater can be downloaded and installed separately like macos

This way, I can silently download in the background after the user starts the application, and then prompt the user to update after the download is completed
After the download is completed, there are two ways to successfully update: 
1. Calling the `relaunch` method
2. Close the program and reopen it next time

**Comment by amrbashir** [comment]
This will be added to the Rust API in v2 here https://github.com/tauri-apps/plugins-workspace/pull/431
