### ISSUE TITLE
[bug] JS API Cannot resize window if the window is being dragged

### ISSUE THREAD

**Issue by veykos** [tauri-apps/tauri#7303]
### Describe the bug

I'm opening this issue as recommended in this Discord topic: [Tauri Discord](https://discord.com/channels/616186924390023171/1120330441161969674)

We noticed an interesting issue regarding the usage of setSize to change the window size of our app. We are using different window sizes to resize our app depending on the screen shown. We noticed that if the window is being dragged at the same moment setSize is being used the window will not change it's size, no error will be thrown, and the window will stay the same size as it was before causing clipping issues (our HTML body changes, but it's clipped because the window is not the proper size).

### Reproduction

[Minimal reproduction repo](https://github.com/veykos/tauri-minimal-repro)

To run the minimal reproduction install the dependencies (only Tauri and Mithril): run in the directory ``` npm i ```
And then start the app with: ```npm run dev```

The way to reproduce the bug is: 
Click the "RESIZE" button, this will trigger a 2 second timeout after which a setSize with random width and height will be initiated
Quickly start dragging the window from the title bar in whatever direction but don't stop or drop the window during these seconds before setSize goes through.
You'll see the width and height we wanted to set displayed in a div element together with the current window's innerSize after the resizing should go through
If done properly, the required width and height won't be applied to the window, and the window will be kept at the old width and height.

To check how it should work, just click "RESIZE" and wait 3 seconds, the window will resize and the required and current width and height will match. 
We managed to reproduce the issue both on Windows and Linux with this small reproduction repo.

### Expected behavior

The window is resized, and no content clips outл

### Platform and versions

```text
> MINIMAL REPRO@0.1.0 tauri
> tauri info


[⚠] Environment
    - OS: Manjaro 22.1.3 X64
    ✔ webkit2gtk-4.0: 2.40.1
    ✔ rsvg2: 2.56.0
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16) (Arch Linux rust 1:1.69.0-2)
    ✔ Cargo: 1.69.0
    ⚠ rustup: not installed!
      If you have rust installed some other way, we recommend uninstalling it
      then use rustup instead. Visit https://rustup.rs/
    ⚠ Rust toolchain: couldn't be detected!
      Maybe you don't have rustup installed? if so, Visit https://rustup.rs/
    - node: 18.15.0
    - yarn: 1.22.19
    - npm: 9.4.2

[-] Packages
    - tauri [RUST]: 1.2.4
    - tauri-build [RUST]: 1.2.1
    - wry [RUST]: 0.23.4
    - tao [RUST]: 0.15.8
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist/bundle
    - devPath: http://localhost:8000/
    - bundler: Webpack
```

**Comment by amrbashir** [comment]
Calling `setSize` while the window is moving or being resized by cursor can lead to undefined behaviors for users so instead

> and the window will stay the same size as it was before causing clipping issues (our HTML body changes, but it's clipped because the window is not the proper size).

I think this is a bad UX imo (but I ain't no UX expert so take it with a grain of salt), instead you should set a minimum window size and use a responsive layout.
