### ISSUE TITLE
[bug] Cannot drag window with hiddenTitle and titleBarStyle Overlay

### ISSUE THREAD

**Issue by iUnstable0** [tauri-apps/tauri#7304]
### Describe the bug

I cannot drag the window while its focused, but if i unfocus and drag the window no the topbar (which is invisible) i can drag the window

https://github.com/tauri-apps/tauri/assets/46888825/14cb6fb1-497f-402f-8b9b-d309c4b460df

I didn't use decorations: true because it doesn't make my app rounded

### Reproduction

https://github.com/iUnstable0/script-ware-m

the repository of my source code

clone the repository, cd into the repository, run `pnpm i` then `cargo tauri dev`
that app rn also download files to your system so either make sure you're on macos or just edit the file and comment out the downloading part or just disable the splashscreen in tauri.conf file

### Expected behavior

I expect it to drag when i drag on the custom titlebar 

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.16.0
    - pnpm: 8.6.5
    - yarn: 1.22.19
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../out
    - devPath: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Webpack
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by FabianLars** [comment]
You'll have to apply the `data-tauri-drag-region` attribute to the titlebar (or its innermost element as it must be applied to the actual click target which you can find via something like `document.addEventListener("click", console.log);`

**Comment by iUnstable0** [comment]
@FabianLars Thank you so much, i added the click even listener and it showed the main container instead of the titlebar so i set titlebar zIndex to 2 and now it's working thanks!
