### ISSUE TITLE
[bug] nsis uninstall delete menushort error when use perMachine mode

### ISSUE THREAD

**Issue by thetbw** [tauri-apps/tauri#7315]
### Describe the bug

The nsis uninstaller, when uninstalling, deleted the wrong shortcut, causing the file to not exist and causing an error.
When you update your app, the installer received exit code 2, indicating that it cannot be uninstalled

### Reproduction

Use nsis, the mode is perMachine, after installation and then uninstall, you will find that the shortcut is still there

### Expected behavior

Shortcuts should be removed after uninstall

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 114.0.1823.58
    ✔ MSVC:
        - Visual Studio 15 ���ɹ��� 2017
        - Visual Studio ���ɹ��� 2019
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 14.18.0
```

### Additional context

I found some reasons for this bug
see this doc https://nsis.sourceforge.io/Shortcuts_removal_fails_on_Windows_Vista
and
in file https://github.com/tauri-apps/tauri/blob/dev/tooling/bundler/src/bundle/windows/templates/installer.nsi
line 350
```nsi
!if "${INSTALLMODE}" == "currentUser"
    SetShellVarContext current
!else if "${INSTALLMODE}" == "perMachine"
    SetShellVarContext all
!endif
```
but on line 632,the uninstall Section ,no this logic

I fixed this in my own code, but I don't know how to make it better, so here your go

**Comment by thetbw** [comment]
I got something wrong

`When you update your app, the installer received exit code 2, indicating that it cannot be uninstalled` ，He is not caused by not deleting shortcuts

is because nsi line 259
```nsi
${IfThen} ${Errors} ${|} StrCpy $0 2 ${|} ; ExecWait failed, set fake exit code
```

This is also a problem, I don't know how to solve it, so I deleted the above line of code, I don't want the user to execute normally and see the error

**Comment by jetli** [comment]
same here.

**Comment by amrbashir** [comment]
fix in https://github.com/tauri-apps/tauri/pull/7342 , and will be available in the next release once merged
