### ISSUE TITLE
[bug] windows NSIS uninstaller issue with tauri-cli 1.4.0

### ISSUE THREAD

**Issue by YichenZhou113** [tauri-apps/tauri#7317]
### Describe the bug

Seems that with the latest tauri-cli 1.4.0, the NSIS generated `.exe` installer on windows will have issue when trying to uninstall the existing application. 
Though the uninstall was actually completed and successful, it will still pop up a window and say "Unable to uninstall".
<img width="300" alt="Screenshot 2023-06-28 at 12 17 28 PM" src="https://github.com/tauri-apps/tauri/assets/40067411/1b923c04-53f0-4401-b7dc-9ccdf270edfb">
Switching back to tauri-cli 1.3.0 will fix the issue.

### Expected behavior

The pop-up window saying "Unable to intall!!" should not happen, since the uninstall was actually successful.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19044 X64
    ✔ WebView2: 114.0.1823.58
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.16.0
    - npm: 9.5.1   

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.3.0 (outdated, latest: 1.4.0)
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: default-src 'self'; font-src data:; img-src data:
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by jetli** [comment]
same here

**Comment by amrbashir** [comment]
@jetli please refrain from commenting "plus one", "+1" or "same here"...etc, it only generates noise for the maintainers and everyone subscribing to these issues without providing any useful information, instead just add a reaction to the issue body.
