### ISSUE TITLE
[bug] Tauri remembers file not found and than cache it

### ISSUE THREAD

**Issue by erikpa1** [tauri-apps/tauri#7321]
### Describe the bug

Hi, I'm using `convertFileSrc`  to read 3d model in GLB format on my disc. I have enabled whole disc for tauri http api, no restrictions, i can use fetch() for any file on disc I want.

The problem is, when I first time try to access file, it is not there (yeah maybe something I can change on my side, but I want it that way, I have some default mechanism if something bad happen) 

But when I put file on place where it should be, Tauri still throws 404 not found, even file is there. After app restart (or ctrl + r), there is no problem. When I change 3D model, I always get the same model (probably cache).

I have tried oldschool `<img/> `trick  `    src=`/mypath/image.png?random=${Math.random()}`` To prevent cache, but in this way tauri totally cant find the file.

![image](https://github.com/tauri-apps/tauri/assets/19526670/dfeb7403-ef71-4a70-9a75-36c63e893613)

### Reproduction

Probably use convertFileSrc and fetch some file,...

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 114.0.1823.58
    ✔ MSVC: Visual Studio Enterprise 2019
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 16.14.2
    - pnpm: 8.3.1
    - yarn: 1.22.19
    - npm: 8.5.0
```

**Comment by amrbashir** [comment]
Could you please make a minimal repro that I can use?

**Comment by erikpa1** [comment]
@amrbashir thanks for your time, will try it as soon as posible

**Comment by erikpa1** [comment]
@amrbashir 

Hi, you can find simple repo below  for repro  just run `pnpm install ` and  `pnpm tauri dev` it should turn on on first run. When you press copy the file ToBeCopied.jpg is created to name Target.jpg. But when refresh is there file is not changed, but when you press refresh and image is changed and than back, its working.

Also in //TODO is code part which should work too.

`https://github.com/erikpa1/TauriBugRepro`

![image](https://github.com/tauri-apps/tauri/assets/19526670/ec4b0803-ff98-4d47-b02a-1751e17ffe27)

Not sure who to blame for this error, webview or tauri.  Because viewing different file with same path is webview problem itself (beause of cache), to make this use cases working there is trick:

`/api/myfile.json?random=0.55` - but this use case tauri don't support because it can't show file with query params e

**Comment by amrbashir** [comment]
I couldn't reproduce the issue, maybe I missed a step or something so I'd suggest you make me a list of exact steps to do.

Anyhow, `tauri` does allow specifying query params in the URL but you're doing it wrong and maybe we should showcase an example for this somewhere, you need to be doing
```jsx
<img src={`${convertFileSrc('D:\\path\\to\\file')}?random=0.55`} />
```
because `converFileSrc` calls `encodeURIComponent` which will encode some characters (like `?`) in order to preserve the file name correctly if it contains one of these characters.

**Comment by erikpa1** [comment]
@amrbashir  when you hit `copy` button image appeared ??? Without refresh ?

![image](https://github.com/tauri-apps/tauri/assets/19526670/e071ee64-9434-4484-bfbf-7766aed3a038)

But anyway, your `${convertFileSrc('D:\\path\\to\\file')}?random=0.55` worked. Stupid me, I was thinking about it, but stupid me added random, after **MY** normalization function, not tauri convertFileSrc :D :D  

Thanks for your time and help.
