### ISSUE TITLE
Text next to application icon

### ISSUE THREAD

**Issue by Jarrodsz** [tauri-apps/tauri#7324]
### Describe the problem

currently its not possible to show an text like temperature beside the icon of an tray which is breaking issue for my app i want to build.

See image of proposed solution.

Possible with swift on osx anyway

![image](https://github.com/tauri-apps/tauri/assets/90145421/655e4874-4901-440d-84e3-c883d8745a0f)

### Describe the solution you'd like

be able for the tray to support text like temperature that can be updated from time to time also

### Alternatives considered

moving back to electron :(
or going for swift route and build 2 codebases 
both ugh

**Comment by amrbashir** [comment]
This is already supported, but only on macOS, use `SystemTray::with_title`
