### ISSUE TITLE
[bug] Taskbar Overlay Issue on Windows 11 with Transparency and Fullscreen Configuration

### ISSUE THREAD

**Issue by 0Ky** [tauri-apps/tauri#7328]
### Describe the bug

I'm facing an issue related to the UI on `Windows 11` when working with a fresh new Tauri project. When the window configuration is set to both `transparent` and `fullscreen`. The taskbar is seemingly sent behind other opened windows, or it appears as if other windows are brought to the foreground and overlay the taskbar. This occurs despite having certain window elements placed behind the taskbar.

### Reproduction

1. Create a new Tauri project on `Windows 11` using the command `npm create tauri-app@latest`.
2. Modify the `tauri.conf.json` file to add `"transparent": true` and `"fullscreen": true` to the Window configuration.
3. Update `src/styles.css` to make the `background-color: transparent`.
4. Make sure there are some window elements positioned behind the taskbar (Paint or Notepad) for visual verification. 
5. Run the Tauri application `npm run tauri dev`.
    

### Expected behavior

The taskbar should maintain its normal position above all other windows, even when the Tauri application is set to be transparent and fullscreen.

### Platform and versions

```ruby
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 114.0.1823.58
    ✔ MSVC: 
        - Visual Studio Build Tools 2022
        - Visual Studio Community 2022
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.16.0
    - yarn: 1.22.19
    - npm: 9.6.7

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../src
    - devPath: ../src
```

### Additional context

Here is a video demonstration: Once the Tauri application is running, the taskbar seems to be sent behind the other opened windows, or these windows are moved into the foreground, overlaying the taskbar.

https://github.com/tauri-apps/tauri/assets/16103757/68b24708-e170-4fc4-bb87-9fab58622903

**Comment by 0Ky** [comment]
Here is another demo, where I start a non-fullscreen window with the same height/width as my monitor, but I move the position by 20 pixels to the right. When the transparent window (_striped background_) appears I resize it, so that it covers the 20 pixel gap I created, which will then cause the same overlay issue:

https://github.com/tauri-apps/tauri/assets/16103757/6fa0171e-89d2-44c7-885e-42de0c435f8d

This is the Window configuration I used:

```json
"windows": [
  {
    "decorations": false,
    "transparent": true,
    "fullscreen": false,
    "alwaysOnTop": true,
    "visible": true,
    "focus": true,
    "skipTaskbar": true,
    "resizable": true,
    "title": "taskbar-bug",
    "width": 2560,
    "height": 1440,
    "x": 20.0,
    "y": 0.0
  }
]
```

I've also noticed that if I change the `x` and `y` value in the Window configuration to 0 and then set the `LogicalPosition` in the frontend to move 1 pixel to the right, then the overlay issue will not appear despite the window being the same size as my display.

```js
await appWindow.setPosition(new LogicalPosition(1, 0));
```

**Comment by amrbashir** [comment]
This is the intended behavior of the underlying Windows API, from [msdn docs](https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist2-markfullscreenwindow): 
> Setting the value of fFullscreen to TRUE, the Shell treats this window as a full-screen window, and the taskbar is moved to the bottom of the z-order when this window is active

**Comment by 0Ky** [comment]
@amrbashir In my previous post https://github.com/tauri-apps/tauri/issues/7328#issuecomment-1619012632, I've provided a separate demo that illustrates the same problem when `fullscreen` is set to `false`.

**Comment by amrbashir** [comment]
I guess I should've included the full remark section: 
> Setting the value of fFullscreen to TRUE, the Shell treats this window as a full-screen window, and the taskbar is moved to the bottom of the z-order when this window is active. Setting the value of fFullscreen to FALSE removes the full-screen marking, but does not cause the Shell to treat the window as though it were definitely not full-screen. With a FALSE fFullscreen value, the Shell depends on its automatic detection facility to specify how the window should be treated, possibly still flagging the window as full-screen.

Even if the `fullscreen` is set to `false`, The Windows Shell will try to auto-detect if this Windows is a fullscreen window (in your case, when it is resized and covers the whole screen), it will mark it as a fullscreen window which will move the taskbar to the bottom of the z-order

**Comment by 0Ky** [comment]
The Windows Shell is automatically classifying the application as fullscreen, even though it is not explicitly set to be. This can result in the taskbar being rendered behind other open windows. As it was mentioned previously, this is due to the Shell's automatic detection system, which flags a window as fullscreen if it's resized to occupy the entire screen, even if the `fullscreen` Window option is set to `false`.

We can use the `SetPropW()` function from the Windows API before showing the window. This will signal to the Shell that the window should not be treated as a fullscreen window. As a result, the Shell won't adjust the taskbar's z-order (the order of overlapping windows along the z-axis, which determines which windows appear in front of others), ensuring that the taskbar maintains its position.

```rust
use windows::Win32::UI::WindowsAndMessaging::SetPropW;
use windows::Win32::Foundation::HANDLE;
use windows::core::PCWSTR;
use wchar::wchz;

let window = app_handle.get_window("main").unwrap();
let handle = HANDLE(true as isize);
let mut name: Vec<u16> = wchz!("NonRudeHWND").to_vec();
unsafe {
    SetPropW(window.hwnd().unwrap(), PCWSTR(name.as_mut_ptr()), handle)
};
window.show();
```

I would like to have this feature implemented, so that it can be set in the Window configuration, through tauri.conf.json, JS API or the Window in Rust, which would resolve this issue.

**Comment by amrbashir** [comment]
This is a rare use-case and I don't think we should be adding an API for it. We will consider if more users ask for it.
