### ISSUE TITLE
[feat] removeFocus method

### ISSUE THREAD

**Issue by fax1ty** [tauri-apps/tauri#7331]
### Describe the problem

Currently, Tauri does not provide a built-in method or action to remove focus from the window.

### Describe the solution you'd like

`setFocus(false)` or `removeFocus()`

**Comment by amrbashir** [comment]
I don't think we will ever provide a way to do this, the underlying OS doesn't provide such methods, and it doesn't quite make a lot of sense to me, like where does the focus go afterwards? the window before that? but what if there is no other windows available, does it keep focus?

**Comment by Neo110** [comment]
I need yet ,

**Comment by Eennou** [comment]
After creating a shortcut to hide/show my hud, I noticed that my hud gets focus when I use .show(), so I think it's useful, I need to set focus back to last app.
