### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by lfcod** [tauri-apps/tauri#7347]
### Describe the bug

pnpm tauri build
 Error Unable to find your web assets, did you forget to build your web app? Your distDir is set to ""../dist"".
Integrated into the project, cannot generate dist directory after building

### Platform and versions

```text
mac os
```

**Comment by FabianLars** [comment]
Could you share the project with us?

Also, does this error only show in your IDE/code editor or also when you do `tauri dev` & `tauri build` ?

Also please include the full output of the `tauri info` command in `Platform and versions` as asked for in the issue template :)

**Comment by lfcod** [comment]
npm run app:build

> app:build
> yarn tauri build

yarn run v1.22.19
$ /Users/lf/Documents/gpt/gptdidi/node_modules/.bin/tauri build
     Running beforeBuildCommand `yarn build`
$ next build
[Next] build mode standalone
- info Creating an optimized production build  
- info Compiled successfully

./app/utils/localStorage.js
61:1  Warning: Assign object to a variable before exporting as module default  import/no-anonymous-default-export

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
- info Linting and checking validity of types  
- info Collecting page data  
[    ] - info Generating static pages (0/3)[Lang] failed to detect user lang.
[Lang] failed to detect user lang.
[=   ] - info Generating static pages (2/3)
  DEVCTO  https://lanmeidao.com 

- info Generating static pages (3/3)
- info Finalizing page optimization  

Route (app)                                Size     First Load JS
┌ ○ /                                      155 kB          233 kB
├ ℇ /api/config                            0 B                0 B
└ ℇ /api/openai/[...path]                  0 B                0 B
+ First Load JS shared by all              78.6 kB
  ├ chunks/2443530c-9cc51f969103915a.js    50.5 kB
  ├ chunks/8139-c2224fd8befc74b3.js        24.8 kB
  ├ chunks/main-app-54df68be2a530fbb.js    224 B
  └ chunks/webpack-4a5474ba0018d92b.js     3.02 kB

Route (pages)                              Size     First Load JS
─ ○ /404                                   182 B          89.6 kB
+ First Load JS shared by all              89.4 kB
  ├ chunks/main-4b98ce350163940c.js        86.2 kB
  ├ chunks/pages/_app-6b94368279a02b5e.js  196 B
  └ chunks/webpack-4a5474ba0018d92b.js     3.02 kB

ℇ  (Streaming)  server-side renders with streaming (uses React 18 SSR streaming or Server Components)
○  (Static)     automatically rendered as static HTML (uses no initial props)

       Error Unable to find your web assets, did you forget to build your web app? Your distDir is set to ""../dist"".
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by lfcod** [comment]
What do I need to do? Haven't I encountered the same problem before

**Comment by amrbashir** [comment]
looks like you have a misconfigured tauri.conf.json, please upload your project to a repo or a minimal repro of it so we can help you further.

**Comment by lfcod** [comment]
{
  "$schema": "../node_modules/@tauri-apps/cli/schema.json",
  "build": {
    "beforeBuildCommand": "npm run build",
    "beforeDevCommand": "npm run dev",
    "devPath": "http://localhost:3000",
    "distDir": "../out"
  },
  "package": {
    "productName": "chatgpt-desk",
    "version": "0.1.0"
  },
  "tauri": {
    "allowlist": {
      "all": false
    },
    "bundle": {
      "active": true,
      "category": "DeveloperTool",
      "copyright": "",
      "deb": {
        "depends": []
      },
      "externalBin": [],
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "identifier": "com.tauri.build",
      "longDescription": "",
      "macOS": {
        "entitlements": null,
        "exceptionDomain": "",
        "frameworks": [],
        "providerShortName": null,
        "signingIdentity": null
      },
      "resources": [],
      "shortDescription": "",
      "targets": "all",
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "security": {
      "csp": null
    },
    "updater": {
      "active": false
    },
    "windows": [
      {
        "fullscreen": false,
        "height": 600,
        "resizable": true,
        "title": "chatgpt-desk",
        "width": 800
      }
    ]
  }
}

**Comment by amrbashir** [comment]
please share the full project in a public repo

**Comment by lfcod** [comment]
https://github.com/lfcod/gptdidi

**Comment by amrbashir** [comment]
The repo is not public, I can't view or clone it

**Comment by lfcod** [comment]
https://github.com/lfcod/gptdi

**Comment by amrbashir** [comment]
As expected, you have a misconfigured app, you have a Next.js app which is an SSR framework that needs Node.js to run on the server, but in the case of a tauri app where there is no Node.js runtime, you will need to make a static version of your app using `next export`, I'd suggest using this [tauri-nextjs-template](https://github.com/kvnxiao/tauri-nextjs-template) which is already configured to do so.

**Comment by lfcod** [comment]
不能仅通过修改配置完成转化么，如果使用tauri-nextjs-template工作量会比较大，他们是如何做到的呢，这个项目https://github.com/Yidadaa/ChatGPT-Next-Web

**Comment by lfcod** [comment]
Can't we just complete the transformation by modifying the configuration? If we use the tauri nextjs template, the workload will be relatively high. How did they achieve this https://github.com/Yidadaa/ChatGPT-Next-Web
