### ISSUE TITLE
[bug] createObjectURL not accessible in new WebviewWindow

### ISSUE THREAD

**Issue by hobbestherat** [tauri-apps/tauri#7363]
### Describe the bug

I try to open a new WebviewWindow with a blob containing a generated pdf in order to print it. The WebviewWindow opens in black (turning white when clicked) with no content (and in the debug view no network requests). 
To exclude pdf as the problem I created tiny example with text/html that works on a regular web browser with window.open. The tiny example shows the same behaviour. Opening the debug console on the new WebviewWindow shows no errors, but it looks as if it only opened a blank page without even trying to load the blob url.

When I try to load the generated URL in the console of the new WebviewWindow 
(e.g. let x = await fetch('http://127.0.0.1:1430/31b1eb0c-cfe4-4172-b281-020bb10fee06'); )
I get " Origin null is not allowed by Access-Control-Allow-Origin. Status code: 200" but this error is not in the console or network tab when the window opens.

### Reproduction

Try opening a window from Javascript with a Blob that contains the content of the page:  

let htmlFile = new Blob([new TextEncoder().encode('<html>test</html>')], {type: 'text/html'});
let htmlUrl = URL.createObjectURL(htmlFile); 
let w = new WebviewWindow('window0', {'url': htmlUrl, 'title':'Test'});

### Expected behavior

Opens a window with the text "test".

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.4.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.2.0
    - npm: 9.7.1

[-] Packages
    - tauri [RUST]: 1.2.3
    - tauri-build [RUST]: 1.2.1
    - wry [RUST]: 0.23.4
    - tao [RUST]: 0.15.8
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
    - distDir: ../dist
    - devPath: ../dist
```

**Comment by merabtenei** [comment]
Any update on this one ?
Edit:
@hobbestherat 
As a workaround for displaying PDF on new window, I had to point the webview url to a new page I created in my app let's say `/pdfview?url=blob:http://localhost:5173/51817bbc-0094-48b2-9d8e-71c59a215c46` which gets the blob url as parameter and displays an `<iframe src={url} ... />` which worked pretty well. But i wonder why webview window can't directly display a blob url. That would be more convenient.
