### ISSUE TITLE
[bug] WebView Fixed Runtime not found in development

### ISSUE THREAD

**Issue by carlocorradini** [tauri-apps/tauri#7373]
### Describe the bug

I need to develop an application for Windows that ships with a fixed version of the WebView2 runtime.
I followed the instructions provided in the [docs](https://tauri.app/v1/guides/building/windows#fixed-version): downloaded the latest version, unzipped it, and updated the tauri.conf.json file accordingly.
The production application (generated with `npm run tauri build`) works flawlessly.
However, **in development (`npm run tauri dev`) the application crashes during bootstrap due to the following error:**
```sh
thread 'main' panicked at 'error while running application: Runtime(CreateWebview(WebView2Error(WindowsError(Error { code: 0x80070002, message: The system cannot find the file specified. }))))'
```
This is really strange. It looks like, during development, Tauri is unable to find the correct directory (maybe a working directory issue?) where the runtime is located.
If I change the configuration to not use a Fixed runtime, the application starts without any problem.

### Reproduction

https://github.com/carlocorradini/tauri-webview

### Expected behavior

Tauri should find the WebView runtime and start without any error.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 114.0.1823.67
    ✔ MSVC:
        - Visual Studio Build Tools 2019
        - Visual Studio Community 2022
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.16.0
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 1.4.0 (no manifest)
    - tauri-build [RUST]: 1.4.0 (no manifest)
    - wry [RUST]: 0.24.3 (no manifest)
    - tao [RUST]: 0.16.2 (no manifest)
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../build
    - devPath: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

### Additional context

Maybe: Windows only related

**Comment by jeffshadap** [comment]
Same here

**Comment by FabianLars** [comment]
Hmm, i'm having trouble reproducing this issue. What i tried:
1) create-tauri-app then follow the docs. No matter if i have evergreen installed or not, the webview starts fine.
2) Your reproduction repo you linked. No matter if i have evergreen installed or not, the webview starts fine.

fwiw here's the tauri info output from your repro repo:
```
[✘] Environment
    - OS: Windows 10.0.19045 X64
    ✘ Webview2: not installed!
      Visit https://developer.microsoft.com/en-us/microsoft-edge/webview2/
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.16.0
    - pnpm: 8.6.7
    - yarn: 1.22.19
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - bundler: Vite
```

Gonna try on a new windows installation later.

**Comment by carlocorradini** [comment]
Mmm strange.
The problem only arises in development when the Runtime is Fixed (and downloaded).
Note that in my Windows (dev machine) the Runtime is installed. It may cause some conflicts?

**Comment by FabianLars** [comment]
> Note that in my Windows (dev machine) the Runtime is installed. It may cause some conflicts?

That's what i meant with evergreen. I tried it with the runtime being installed and uninstalled and both worked 🤔

**Comment by carlocorradini** [comment]
The strange thing is that every other type of WebView2 works as a charm when developing. But with the fixed version it panics :/

**Comment by carlocorradini** [comment]
@jeffshadap Can you try the example repo with your setup?
Does it work or still panic?

**Comment by FabianLars** [comment]
> Gonna try on a new windows installation later.

well, good news i guess. Your repro crashes for me too after re-installing Windows.

**Comment by carlocorradini** [comment]
""Good News"" 😰😂

**Comment by FabianLars** [comment]
^ Fixed in the next release: https://github.com/tauri-apps/tauri/pull/7419 (forgot that merging into v1 branch doesn't close issues anymore without manually linking them)

**Comment by carlocorradini** [comment]
Awesome thanks 😎
