### ISSUE TITLE
[bug] fs `readDir` fails for `BaseDirectory.Home` root with "Access is denied. (os error 5)", even as Admin

### ISSUE THREAD

**Issue by Wombosvideo** [tauri-apps/tauri#7379]
### Describe the bug

**What doesn't work:**
Using `readDir('', { dir: BaseDirectory.Home, recursive: true })` on Windows throws  
`path: <homeDirPath>: Access is denied. (os error 5)`.

**What this means:**
This suggests that the user does not have access to `<homeDirPath>` which can not be the case, since using `recursive: false` succeeds.

**Possible cause:**  
The error is thrown because the user doesn't have access to some subdirectory of `<homeDirPath>` and trying to read that directory failed.

**Why this needs fixing:**  
- The error doesn't tell which directory failed; it always uses the `<homeDirPath>`. This makes debugging impossible.
- There is no way to obtain the entries that _didn't_ fail. This makes a `readDir` invocation useless.

### Reproduction

```js
import { readDir, BaseDirectory } from '@tauri-apps/api/fs';

async function test() {
  // Empty string as dir parameter
  await readDir('', { dir: BaseDirectory.Home, recursive: true }); // Throws "path: <homeDirPath>: Access is denied. (os error 5)"
  // Dot as dir parameter
  await readDir('.', { dir: BaseDirectory.Home, recursive: true }); // Throws "path: <homeDirPath>.: Access is denied. (os error 5)"
}

await test();
```

### Expected behavior

- Only throw an error if the root directory of `readDir(rootDir, { recursive: true })` can not be read
- When throwing an error, use the path of the directory that _actually_ failed instead of the root directory
- Include the problematic subdirectory in the result but set `subdirectory.children = [];` (`'empty'`)
- Exclude the problematic subdirectory from the result (`'exclude'`)
- For backward compatibility, add `errors?: 'throw' | 'empty' | 'exclude'` to type `FsDirOptions` (defaulting to `'throw'`)

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 114.0.1823.67
    ✔ MSVC:
        - Visual Studio Build Tools 2022
        - Visual Studio Community 2022
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.4.0
    - npm: 9.7.2

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../build
    - devPath: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

### Stack trace

```text
Uncaught (in promise) path: <homeDirPath>: Access is denied. (os error 5)
```

**Comment by Wombosvideo** [comment]
### Workaround
Instead of using `readDir` directly, use `_readDir` from below.

```js
/**
 * List directory files.
 * @param {string} dir
 * @param {(import("@tauri-apps/api/fs").FsDirOptions & {errors?: "throw" | "empty" | "exclude"}) | undefined} options
 * @returns {Promise<import("@tauri-apps/api/fs").FileEntry[] | null>}
 */
const _readDir = async (dir, options = undefined) => {
  const errors = options?.errors || 'throw';
  const recursive = options?.recursive;
  let entries, match, children;
  try {
    entries = await readDir(dir, options ? {...options, recursive: false} : {recursive: false});
  } catch (e) {
    if (typeof e === 'string' && (match = /path: (.+): (.+) \(os error (\d)+\)/.exec(e)))
      e = `path: ${dir.includes('\\') || dir.includes('/') ? dir : match[1]}: ${match[2]} (os error ${match[3]})`;
    if (errors === 'throw')
      throw e;
    console.warn(e);
    return errors === 'empty' ? [] : null;
  }
  if (!recursive)
    return entries;
  for (let i = 0; i < entries.length; i++) {
    const entry = entries[i];
    if (Array.isArray(entry.children)) {
      if (children = await _readDir(entry.path, options))
        entry.children = children;
      else if (errors === 'exclude')
        entries.splice(i--, 1);
    }
  }
  return entries;
};
```

**Usage examples with `readDir`:** -- You probably don't want this  
```js
// Throws "path: <homeDirPath>: Access is denied. (os error 5)"
await readDir('', { dir: BaseDirectory.Home, recursive: true });
```

**Usage examples with `_readDir`:**  
```js
// Throws "path: <failedDirPath>: Access is denied. (os error 5)"
await _readDir('', { dir: BaseDirectory.Home, recursive: true });
await _readDir('', { dir: BaseDirectory.Home, recursive: true, errors: "throw" });

// Returns a FileEntry[]. Failed paths will be included but children is an empty array
await _readDir('', { dir: BaseDirectory.Home, recursive: true, errors: "empty" }); // Returns a FileEntry[]

// Returns a FileEntry[] or null if access to the root directory is denied
await _readDir('', { dir: BaseDirectory.Home, recursive: true, errors: "exclude" });
```

***

2023-07-10: Fixed `"exclude"` mode:
```diff
  if (!recursive)
    return entries;
-  for (let [i, entry] of entries.entries()) {
+  for (let i = 0; i < entries.length; i++) {
+  const entry = entries[i];
    if (Array.isArray(entry.children)) {
      if (children = await _readDir(entry.path, options))
        entry.children = children;
      else if (errors === 'exclude')
-        entries.splice(i, 1);
+       entries.splice(i--, 1);
    }
```

**Comment by Wombosvideo** [comment]
Code updated to fix `"exclude"` mode. Previously, if an error occured and an entry was excluded, the next entry was skipped because the index of all the next entries was reduced by one during the `splice` operation and thus the next entry got the same index as the current entry.

**Comment by lucasfernog** [comment]
Ignoring errors is dangerous and shouldn't be done by the framework, maybe by the application depending on the use case. We should have better error information though.

For instance this is the error message from Node.js for a recursive directory read: `Error: EACCES: permission denied, scandir '/home/lucas/Downloads/x/b'`.

Also be careful reading the home directory recursively, it might have millions of files :)

**Comment by Wombosvideo** [comment]
I use recursively reading the home directory in a user-invoked search for a directory with a very specific naming scheme and manually selecting said folder is still the prefered option.

I understand the risks of recursively reading directories with potentially millions of files which is why I second your opinion. As a user-invoked feature the user experience benefit of not having to look for the directory manually outweighs the possible resource and time consumptions a recursive `readDir` might have in my opinion.
