### ISSUE TITLE
Error: 'The system cannot find the file specified' when upload file to backend by Tauti http lib

### ISSUE THREAD

**Issue by AyalaGol** [tauri-apps/tauri#7390]
### Describe the bug

Hi, 

I'm trying to send a form request to my backend and I want to transfer a zip file with that request.
I'm using @tauri-apps/api/http + FormData in the body.
the form data contains zip file , in this way:
`const zip = new JSZip();
const logsFolder = zip.folder('logs');
const content = await zip.generateAsync({ type: 'blob' });
const formData = new FormData();
formData.append('file', content, 'info.zip');`

but when I send the request , I get this error each time:
Error: 'The system cannot find the file specified' 

What could be the issue?

### Expected behavior

the file is uploaded to backend correctly.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 114.0.1823.67
    ✔ MSVC: Visual Studio Enterprise 2022
    ✔ rustc: 1.67.0 (fc594f156 2023-01-24)
    ✔ Cargo: 1.67.0 (8ecd4f20a 2023-01-10)
    ✔ rustup: 1.25.2 (17db695f1 2023-02-01)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 14.18.3
    - npm: 6.14.15
```

**Comment by amrbashir** [comment]
Until the next release which will add `Body.formAsync` which will respect the entries of `Blob` (or its subclasses like `File`) you will need to use `Bod.form` with a normal Object instead of `FormData`

**Comment by AyalaGol** [comment]
@amrbashir and what should be the type of the method parameter in the API backend side? 
currently it is `@RequestBody MultipartFile zipFile`
If I change the value I send to an object instead of FormData - the type of the request value in the backend should also be changed?

**Comment by amrbashir** [comment]
it will be like this
```ts
const body = Body.form({
  file: {
    file: zipContent, // array of bytes
    mime: 'image/jpeg', // mime type
    fileName: 'image.jpg' // optional file name
  }
});
```

see https://tauri.app/v1/api/js/http#form for more info
