### ISSUE TITLE
[bug] relaunch application after installUpdate - the args are lose

### ISSUE THREAD

**Issue by rkuzlik** [tauri-apps/tauri#7402]
### Describe the bug

relaunch application after installUpdate - the args are lose

### Reproduction

Declare cli args in tauri.conf.json
Open the application with args (e.g via Windows: cmd.exe /k AppName arg1 arg2)
Do relaunch - the args appear.
Do installUpdate and then relaunch - the args lose.

### Expected behavior

The args to stay after install updates

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 114.0.1823.67
    ✔ MSVC: Visual Studio Professional 2022
    ✔ rustc: 1.67.0 (fc594f156 2023-01-24)
    ✔ Cargo: 1.67.0 (8ecd4f20a 2023-01-10)
    ✔ rustup: 1.25.2 (17db695f1 2023-02-01)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.14.0
    - npm: 9.3.1

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0   
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.3.0
    - @tauri-apps/cli [NPM]: 1.3.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist/apps/locota
    - devPath: http://localhost:4200/
    - framework: Angular
    - bundler: Webpack
```

**Comment by AyalaGol** [comment]
@FabianLars  Can you take a look on this issue please?
it it relevant for me also.
when I open Tauri with args and then auto-update is executed - the original args are missed..

**Comment by rkuzlik** [comment]
Any uppdate on this issue? or some workaround for temp solution?
