### ISSUE TITLE
[bug] fails to recomplile after saving rust code on tauri 1.4

### ISSUE THREAD

**Issue by Dosx001** [tauri-apps/tauri#7406]
### Describe the bug

When running the dev server, it fails to recompile changes made in src-tauri. Only 1.4 seems infected.

### Reproduction

```bash
pnpm create tauri-app test --template solid-ts --manager pnpm
cd test
pnpm i
pnpm tauri dev
```
```bash
cd test/src-tauri/src
echo "// hi" >> main.rs
```

### Expected behavior

Recompile when changes are made in src-tauri.

### Platform and versions

```text
[⚠] Environment
    - OS: Arch Linux Unknown X64
    ✔ webkit2gtk-4.0: 2.40.3
    ✔ rsvg2: 2.56.2
    ✔ rustc: 1.70.0 (90c541806 2023-05-31) (Arch Linux rust 1:1.70.0-1)
    ✔ Cargo: 1.70.0
    ⚠ rustup: not installed!
      If you have rust installed some other way, we recommend uninstalling it
      then use rustup instead. Visit https://rustup.rs/
    ⚠ Rust toolchain: couldn't be detected!
      Maybe you don't have rustup installed? if so, Visit https://rustup.rs/
    - node: 20.3.1
    - pnpm: 8.6.6
    - yarn: 1.22.19
    - npm: 8.19.2

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: SolidJS
    - bundler: Vite
```

**Comment by amrbashir** [comment]
Works fine for me, is by chance the `test` project is gitignored by a `.gitignore` file in one of the parent directory? we had a similar report before.

**Comment by Dosx001** [comment]
@amrbashir I did not edit the `.gitignore`. I just gave the project a random name e.g. `test`. This also happens on my personal project when I upgrade to 1.4.

**Comment by Dosx001** [comment]
@amrbashir hmm I tested it rn with a new and personal project everything seems good. Maybe I need to update a system dependence???

**Comment by amrbashir** [comment]
I don't think so, if it happens again, let me know
