### ISSUE TITLE
[bug] NSIS installer does not clean up /redist/MicrosoftEdgeWebview2setup.exe after install and uninstall.

### ISSUE THREAD

**Issue by jetli** [tauri-apps/tauri#7409]
### Describe the bug

webviewInstallMode is silent=true and type=embedBootstrapper. If user does not have webview2 runtime, NSIS installer will add a dir and file: /redist/MicrosoftEdgeWebview2setup.exe to installation directory, but after installation, this dir is not cleaned up. and when user uninstall the app, this dir is not cleaned up again, leaving /redist/MicrosoftEdgeWebview2setup.exe there.

### Expected behavior

NSIS installer should clean up /redist/MicrosoftEdgeWebview2setup.exe after installation.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 114.0.1823.67
    ✔ MSVC:
        - Visual Studio Community 2019
        - Visual Studio 生成工具 2022
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 16.18.0
    - yarn: 3.2.4
    - npm: 8.19.2

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
```

**Comment by FabianLars** [comment]
Thanks for the report.

When we fix this we may want to consider writing that file to a well-known temp dir instead of the installdir if possible too imo.

**Comment by jetli** [comment]
yes, a temp dir is a great idea.
