### ISSUE TITLE
[feat] Provide an API to configure windows before they are created

### ISSUE THREAD

**Issue by minoism** [tauri-apps/tauri#7420]
### Describe the problem

The current execution timing of `setup` method is too late. When the app is reopened, the window will first appears in the center and then quickly move to the previously saved position (via https://github.com/tauri-apps/plugins-workspace/tree/v2/plugins/window-state). This means that people will see flickering behavior when opening the app.

In addition, in most cases, I personally prefer to conditionally create windows using Rust, rather than changing them again in `setup` after they have been created. So, having an API to configure windows before they are created would be great :)

### Describe the solution you'd like

Perhaps something like `prepare`?

**Comment by FabianLars** [comment]
I think the first point can be solved in the plugin (or rather in the plugin-consuming app i guess) by always spawning the window hidden and showing them after setting size/pos etc. - not perfect though i guess...

> In addition, in most cases, I personally prefer to conditionally create windows using Rust, rather than changing them again in setup after they have been created. So, having an API to configure windows before they are created would be great :)

Sounds like https://docs.rs/tauri/latest/tauri/window/struct.WindowBuilder.html to me. Is it missing something you need?

**Comment by minoism** [comment]
> Sounds like [docs.rs/tauri/latest/tauri/window/struct.WindowBuilder.html](https://docs.rs/tauri/latest/tauri/window/struct.WindowBuilder.html) to me.

You're right, but I'm a bit concerned if creating the main window in `setup` might be too late? I see that the window defined in `tauri.conf` is created before this, so I'm just a bit uneasy. Can I completely replace registering the window in configuration file by using this way?

> I think the first point can be solved in the plugin (or rather in the plugin-consuming app i guess) by always spawning the window hidden and showing them after setting size/pos etc. - not perfect though i guess...

~~😱 It sounds a bit hacky...~~
However, I believe this issue can be better resolved if I can completely replace registering the window in the configuration file by creating the window with `WindowBuilder`. (implement my own plugin)

**Comment by FabianLars** [comment]
>  Can I completely replace registering the window in configuration file by using this way?

Yes.

> You're right, but I'm a bit concerned if creating the main window in setup might be too late? I see that the window defined in tauri.conf is created before this, so I'm just a bit uneasy

Well, the internal setup hook run right before the user's setup hook so basically you can interpret it as running at the same time imo (if that'd be technically possible).

>  It sounds a bit hacky...

Yep, sure does. But at the same time this is often recommended in general so that the js is already loaded (at least partially) before the window shows 🤷

**Comment by minoism** [comment]
@FabianLars Ah, I remember why I didn't consider `WindowBuilder` in the first place, since the <https://github.com/tauri-apps/wry/issues/583> issue exists, how should I use it in `setup`?

**Comment by FabianLars** [comment]
583 does not apply to the setup hook. But even if it would, you could use `tauri::async_runtime::spawn` to work around the issue.

**Comment by minoism** [comment]
Amazing!
