### ISSUE TITLE
[bug] Code Signing Ineffective for Windows

### ISSUE THREAD

**Issue by cosi-conda** [tauri-apps/tauri#7424]
### Describe the bug

I have signed my application with github actions using the documented steps precisely:
https://tauri.app/v1/guides/distribution/sign-windows#bonus-sign-your-application-with-github-actions

When I download the application (msi), it still warns that the application may be harmful, despite having an EV cert, which was signed before 6/1/23.

I have ignored any steps before this section, since I assumed they were not relevant to the github action approach, just for context:
https://tauri.app/v1/guides/distribution/sign-windows#bonus-sign-your-application-with-github-actions

### Reproduction

1. Go through github action signing steps
2. Download the MSI and try to install the application
3. See this pop up appear when trying to install the application:

![image](https://github.com/tauri-apps/tauri/assets/118936674/3dd23c7b-1be3-4173-8e0d-b17c95c0a251)

### Expected behavior

I expect the application not to generate a warning message that it may be harmful to my computer.

### Platform and versions

```text
I'm testing this with a Windows VM, using the output from a Github action and deploying the bundle somewhere. 

This is my local project output though just for context (I'm not doing this locally):


Environment
  › OS: Mac OS 12.3.0 X64
  › Node.js: 18.12.1
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.1,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.6,
  › wry [RUST]: 0.22.5,

App
  › framework: React
  › bundler: Vite

App directory structure
  ├─ ui
  ├─ tauri
  ├─ node_modules
  ├─ tests
  ├─ .github
  ├─ .git
```

### Additional context

The github action completes successfully and builds the app. I'm not sure where to look to get the warning to go away.
![image](https://github.com/tauri-apps/tauri/assets/118936674/3dd23c7b-1be3-4173-8e0d-b17c95c0a251)

**Comment by FabianLars** [comment]
I think something's getting mixed up here. Our guide does not, and never did, apply to EV certificates since they always required hardware tokens. Only OV certificates were without tokens before last month but OV certificates do **not** give your app instant "trust" to get rid of warnings like these.

**Comment by cosi-conda** [comment]
> I think something's getting mixed up here. Our guide does not, and never did, apply to EV certificates since they always required hardware tokens. Only OV certificates were without tokens before last month but OV certificates do **not** give your app instant "trust" to get rid of warnings like these.

Thank you for your reply. It did not say explicitly that EV certs were not supported [there](https://tauri.app/v1/guides/distribution/sign-windows/#bonus-sign-your-application-with-github-actions), so I did not realize the intended support. Thank you for letting me know.
