### ISSUE TITLE
[bug] Fails to recognize a folder as tauri module, if the folder is added in .gitignore

### ISSUE THREAD

**Issue by pkh1979** [tauri-apps/tauri#7427]
### Describe the bug

If the tauri app module name is added as part of the .gitignore and run "yarn tauri dev" from root folder, following error message is thrown.

thread 'main' panicked at 'Couldn't recognize the current folder as a Tauri project. It must contain a tauri.conf.json, tauri.conf.json5 or Tauri.toml file in any subfolder.', C:\Users\user.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-cli-1.1.1\src\helpers\app_paths.rs:79:5 note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

Folder structure:

│── package.json
│── public
│   ╰── index.html
│── src
│   │── App.css
│   │── App.jsx
│   │── index.css
│   ╰── index.js
╰── tauriapp1
    │── Cargo.toml
    │── build.rs
    │── icons
    │── src
    ╰── tauri.conf.json

At the same time, if the the entry is removed from .gitignore, the projects builds just fine.

### Platform and versions

```text
Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 114.0.1823.82
  › MSVC:
      - Visual Studio Build Tools 2022
      - Visual Studio Community 2022
      - Visual Studio Build Tools 2017
  › Node.js: 16.14.0
  › npm: 9.8.0
  › pnpm: Not installed!
  › yarn: 1.22.5
  › rustup: 1.26.0
  › rustc: 1.69.0
  › cargo: 1.69.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.4.0
  › tauri [RUST]: 1.4.1,
  › tauri-build [RUST]: 1.4.0,
  › tao [RUST]: 0.16.2,
  › wry [RUST]: 0.24.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: React
  › bundler: Webpack
```

**Comment by FabianLars** [comment]
Thanks for the report but i highly doubt we'll "fix" this as it's pretty much intentional. Not applying ignore files caused bigger issues than this in the past.
It should be possible to gitignore the folder contents as long as the folder itself is not ignored 🤔
