### ISSUE TITLE
[docs]: sh: tauri: command not found

### ISSUE THREAD

**Issue by tofighi** [tauri-apps/tauri#7430]
On MacOS M1, before running `npm run tauri dev` for the development version or `npm run tauri build`, you should run `yarn add -D @tauri-apps/cli && yarn install` to avoid `sh: tauri: command not found`

**Comment by FabianLars** [comment]
Hey, thanks for the request.

In what context (or: "Where") would you expect this information? It's already part of all the getting started guides so i'm not sure where else we should add it.

**Comment by Celestialdevz** [comment]
I tried that but didn't work so insert do this:


`npm install` then `. "$HOME/.cargo/env"` finally `npm run tauri dev`
