### ISSUE TITLE
Open app with administrator privileges

### ISSUE THREAD

**Issue by ugo-studio** [tauri-apps/tauri#7431]
### Describe the problem

I want my app to be able to open with administrator privileges by default

### Describe the solution you'd like

Optional flag in tauri.conf.json file to set whether the application should run as administrator by default or not

### Additional context

When the user opens the app (not the installer), I want Window's UAC prompt to be shown to grant administrator privileges

**Comment by FabianLars** [comment]
You can do so by modifying the executable's manifest file with tauri-build options (in your build.rs file), see <https://docs.rs/tauri-build/latest/tauri_build/struct.WindowsAttributes.html#example>. iirc last time this was requested we did not want to add an explicit api for that, therefore closing this issue, thanks.
