### ISSUE TITLE
how to make transparent  windows?

### ISSUE THREAD

**Issue by Neo110** [tauri-apps/tauri#7433]
how to make transparent windows?

**Comment by pewsheen** [comment]
For pure transparency, you can set [`windows > transparent` in tauri.conf.json to true](https://tauri.app/v1/api/config/#windowconfig.transparent)

If you want some cool features like the blur or vibrancy effect, try using this -> [window-vibrancy](https://github.com/tauri-apps/window-vibrancy/tree/dev)

**Comment by Neo110** [comment]
> For pure transparency, you can set [`windows > transparent` in tauri.conf.json to true](https://tauri.app/v1/api/config/#windowconfig.transparent)
> 
> If you want some cool features like the blur or vibrancy effect, try using this -> [window-vibrancy](https://github.com/tauri-apps/window-vibrancy/tree/dev)

i not need .json file ，i want use api .

**Comment by FabianLars** [comment]
Rust: https://docs.rs/tauri/latest/tauri/window/struct.WindowBuilder.html#method.transparent
JS: https://tauri.app/v1/api/js/window/#transparent
