### ISSUE TITLE
How to change the Origin and Referer

### ISSUE THREAD

**Issue by vanminhquangtri** [tauri-apps/tauri#7442]
This is an old question. But as I see the answer in the past is NOT able to custom the origin & refeferer by tauri config so I wonder at this moment is there any solution. I want to change the origin & referer of http request from http://localhost (on dev mode), and https://tauri.localhost (product mode) to https://my.custom.domain in both dev mode and production mode. My purpose is to bypass the error CORS when calling api.

My app is Vue 3 + @tauri-apps/api 1.4.0. I am using axios to handle http request.

I am new to Tauri so I don't have any idea at this moment. Is there any idea to do this by tauri config. Thank you

**Comment by FabianLars** [comment]
> But as I see the answer in the past is NOT able to custom the origin & refeferer by tauri config

Still the same answer. You've probably seen my writeup here: https://github.com/tauri-apps/tauri/discussions/4912#discussioncomment-3406282 and the part about macos & linux won't change until we have a different webview (which we won't have anytime soon).

> My purpose is to bypass the error CORS when calling api.

Can you use tauri's http api instead? I'd say bypassing cors is one of the main intentions behind it: https://tauri.app/v1/api/js/http

**Comment by vanminhquangtri** [comment]
@FabianLars 
In production build, is it possile to change the domain https://tauri.localhost to https://my.custom.domain?
Thanks

**Comment by FabianLars** [comment]
Technically? Yes, but ofc only on Windows and it would require changes in wry and tauri. Also your frontend would lose the secure context status without the`.localhost` suffix in case anything in your app needs that.
So since it's windows only too the workaround in the discussion linked above may be the better choice.

**Comment by vanminhquangtri** [comment]
Hi @FabianLars 
When apply the code from https://github.com/tauri-apps/tauri/discussions/4912#discussioncomment-3406282, I get many error.

I am quite new to this so Can you please give me a full code for this. Below is my code.

![image](https://github.com/tauri-apps/tauri/assets/70369658/94e421c8-54c9-4aee-a7d2-b708d466d619)


```
// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

// Learn more about Tauri commands at https://tauri.app/v1/guides/features/command
#[tauri::command]
fn greet(name: &str) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

fn main() {
    tauri::Builder::default()
      .plugin(PluginBuilder::default().build())
      .setup(|app| {
        #[cfg(debug_assertions)]
        app.get_window("main").unwrap().open_devtools();
  
        WindowBuilder::new(app, "main", WindowUrl::App("index.html".into()))
          .on_web_resource_request(|req, resp| {
            resp.headers_mut().insert(
              "Origin",
              "https://example.com/".try_into().unwrap(),
            );
          })
          .build()?;
        Ok(())
      })
      .run(tauri::generate_context!())
      .expect("failed to run app");
  }
```

**Comment by FabianLars** [comment]
Ignore the code the OP posted with the `on_web_resource_request` stuff. All that is not compatible with my code. My code below will still miss the imports of the webview2-com and windows crates but as you can see in the error you posted, cargo will tell you what to do. Just add the imports below the import in included for `tauri::Manager`. -> If you use rust-analyzer (or intellij-rust if you use a jetbrains ide) then that will also be able to import that stuff for you.

```rs
// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use tauri::Manager; // <- import

fn main() {
    tauri::Builder::default()
        .setup(|app| {
            let win = app.get_window("main").unwrap();
            win.with_webview(|webview| unsafe {
                let core = webview.controller().CoreWebView2().unwrap();
                let mut _token = EventRegistrationToken::default();
                // You'd probably use CONTEXT_WEBSOCKET or whatever fits, see https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2webresourcecontext?view=webview2-dotnet-1.0.1293.44
                // Also use a fitting glob filter, so that it doesn't trigger for all requests, see https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.1293.44#addwebresourcerequestedfilter
                core.AddWebResourceRequestedFilter("*", COREWEBVIEW2_WEB_RESOURCE_CONTEXT_ALL);
                core.add_WebResourceRequested(
                    WebResourceRequestedEventHandler::create(Box::new(move |webview, args| {
                        if let Some(args) = args {
                            let request: ICoreWebView2WebResourceRequest = args.Request().unwrap(); // manual type to make Rust-Analyzer show the types
                            request
                                .Headers()
                                .unwrap()
                                .SetHeader("Origin", "my-origin")
                                .unwrap();
                        }
                        Ok(())
                    })),
                    &mut _token,
                );
            });
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("failed to run app");
}
```

**Comment by vanminhquangtri** [comment]
Hi @FabianLars ,
I tried many way but still get many error not found in this scope // use of undeclared type. Can you please give me the documation how to implement this? Sorry I am quite new to Rust and this scope. While I need to complete the app in tight time so I ask for many thing from you.

![image](https://github.com/tauri-apps/tauri/assets/70369658/f81ab4b8-3698-4019-9cd8-f4494b16912c)

**Comment by pewsheen** [comment]
Those are Windows-related crates, you can try adding these crates to your `Cargo.toml` and let rust-analyzer or sort of tools help you import the correct modules.
```
webview2-com="0.19"
windows = "0.39.0"
```
I don't know if the version matches other dependencies, so if you see the version matched error while compiling, you need to figure out which version you should use from those messages.

**Comment by FabianLars** [comment]
the pluginbuilder error was my bad, i copied your code without reading through all of it, removed that part of the example.

**Comment by vanminhquangtri** [comment]
@FabianLars 
I tried by the error happen, I would be much grate if you can give full code of file main.rs with import part
