### ISSUE TITLE
[feat] support for pkg

### ISSUE THREAD

**Issue by Moon1102** [tauri-apps/tauri#7443]
### Describe the problem

I think `pkg` is more guided than `dmg`, and most of the time the user just needs to click the continue button to finish the installation.

### Describe the solution you'd like

So I made a `pkg` that can be successfully installed based on the logic of the current `dmg` implementation. 

code 👉🏻 https://github.com/Moon1102/tauri/commit/6f596291aeb57a8975d3df090889cce00592fbba  &   [README](https://github.com/Moon1102/tauri/blob/dev/README_PKG.md)

I think the implementation is too rudimentary though, I'm not going to submit the PR, but want to share the idea with the official developers , maybe the developers will support it in a future release.

**Comment by FabianLars** [comment]
Cross-linking the general macos distribution issue since pkg was talked about over there briefly: https://github.com/tauri-apps/tauri/issues/4415

**Comment by Moon1102** [comment]
Learned a little more and thanks for the pointers :)
