### ISSUE TITLE
The button fullscreen of Video element is hidden in Mac OS

### ISSUE THREAD

**Issue by vanminhquangtri** [tauri-apps/tauri#7453]
Hi Brothers,

I am using @tauri-apps/api version 1.4.0 + Vue 3. My App contain some video element.
I don't know why the button fullscreen is hidden in Tauri App. While in Safari it is shown as normal.
This only happen in Mac Os. My OS is Monterey version 12.6.7.

If I use the method webkitEnterFullscreen() it will give error: **InvalidStateError: The object is in an invalid state.** 
It is just a simple video:

```
<video style="width: 100%; height: 400px" muted controls playsinline>
        <source
          src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4"
          type="video/mp4"
        />
        Your browser does not support the video tag.
</video>
```

This is in Tauri App, no fullscreen button:
![Screen Shot 2023-07-19 at 10 10 07](https://github.com/tauri-apps/tauri/assets/70369658/b8f4ca06-241b-41f4-b3a9-af16551a5ba6)

While this is in Safari, it has full screen button (at the top left corner):
![Screen Shot 2023-07-19 at 10 11 28](https://github.com/tauri-apps/tauri/assets/70369658/d85311d8-4804-442b-8b4a-c27bde736c41)

I would be grateful for any advice how to make the button fullscreen show as normal as I don't know why it happens. Thank you Brothers.

**Comment by pewsheen** [comment]
You'll need to configure these setting to `true` in `tauri.conf.json` to allow fullscreen mode
- ~[setfullscreen](https://tauri.app/v1/api/config/#windowallowlistconfig.setfullscreen)~
- [macOSPrivateApi](https://tauri.app/v1/api/config/#tauriconfig.macosprivateapi)

```json
{
  ...
  "tauri": {
    "macOSPrivateApi": true
  }
}
```

Update: Sorry, you don't need to set `setfullscreen`, just need `macOSPrivateApi`

**Comment by vanminhquangtri** [comment]
Thank @pewsheen , it works now.
