### ISSUE TITLE
[feat] How can I detect sleep mode in windows using rust?

### ISSUE THREAD

**Issue by forchello** [tauri-apps/tauri#7466]
### Describe the problem

The problem is rerender of all web application after pc sleep. So, it will be nice, if we had the opportunity of checking the battery status ( example ) to determine if the computer was in sleep mode

### Describe the solution you'd like

We need [analog of this](https://www.electronjs.org/docs/latest/api/power-monitor) in Tauri.

**Comment by LouneCode** [comment]
Here You go:

```
use sys_info::{PowerStatus, SystemExt};

fn main() {
    let power_status = PowerStatus::new().unwrap();
    if power_status.is_sleeping() {
        println!("The system is in sleep mode.");
    } else {
        println!("The system is not in sleep mode.");
    }
}
```

or 

```
use winapi::um::winbase::GetSystemPowerStatus;
use winapi::um::winnt::SYSTEM_POWER_STATUS;

fn main() {
    let mut status = SYSTEM_POWER_STATUS::default();
    unsafe { GetSystemPowerStatus(&mut status) };
    if status.BatteryFlag & 0x80 != 0 {
        println!("The system is in sleep mode.");
    } else {
        println!("The system is not in sleep mode.");
    }
}
```
--
Cheers

**Comment by FabianLars** [comment]
Closing in favor of #8968 which has a more general wording and the rust part was more or less answered already.
