### ISSUE TITLE
[docs] How do you set tauri2.0.0-alpha back to 1.0

### ISSUE THREAD

**Issue by trookie2000** [tauri-apps/tauri#7467]
How do you set tauri2.0.0-alpha back to 1.0

**Comment by amrbashir** [comment]
Just change the versions of the tauri pqckages in your project `package.json` and `src-tauri/Cargo.toml`

**Comment by trookie2000** [comment]
> Just change the versions of the tauri pqckages in your project `package.json` and `src-tauri/Cargo.toml`

But it still doesn't work after I change it.This is my cargo.toml

[build-dependencies]
tauri-build = { version = "1.2.0", features = [] }

[dependencies]
tauri = { version = "1.4.0", features = ["fs-all", "http-all", "shell-open", "system-tray"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = {version = "0.11",features = ["json"] }
tokio = {version = "1",  features = ["full"] }
diesel = {version = "2.0.3", features = ["sqlite"] }
xml-rs = { version = "0.8.4"}

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

**Comment by trookie2000** [comment]
> Just change the versions of the tauri pqckages in your project `package.json` and `src-tauri/Cargo.toml`

Just change the versions of the tauri pqckages in your project package.json and src-tauri/Cargo.toml

But it still doesn't work after I change it.This is my cargo.toml

[build-dependencies]
tauri-build = { version = "1.2.0", features = [] }

[dependencies]
tauri = { version = "1.4.0", features = ["fs-all", "http-all", "shell-open", "system-tray"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = {version = "0.11",features = ["json"] }
tokio = {version = "1", features = ["full"] }
diesel = {version = "2.0.3", features = ["sqlite"] }
xml-rs = { version = "0.8.4"}

[features]
custom-protocol = ["tauri/custom-protocol"]
