### ISSUE TITLE
[bug] How to return Tauri 2.0-alpha to version 1.0

### ISSUE THREAD

**Issue by trookie2000** [tauri-apps/tauri#7471]
### Describe the bug

How to return Tauri 2.0-alpha to version 1.0, now there is an error：  Error `tauri.conf.json` error on `tauri`: Additional properties are not allowed ('allowlist', 'updater' were unexpected)，This error caused it to not run, and the official website documentation did not revert to the original version of the tutorial

### Platform and versions

```text
cargo tauri info


Error `tauri.conf.json` error on `tauri`: Additional properties are not allowed ('allowlist', 'updater' were unexpected)
```

**Comment by amrbashir** [comment]
See https://github.com/tauri-apps/tauri/issues/7467 and please don't create multiple issues.
