### ISSUE TITLE
[bug] build release with offlineInstaller failed, download MicrosoftEdgeWebView2RuntimeInstallerX64.exe got 404.

### ISSUE THREAD

**Issue by alexsunday** [tauri-apps/tauri#7472]
### Describe the bug

date: 2023/07/21
link: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/aa5fd9b3-dc11-4cbc-8343-a50f57b311e1/MicrosoftEdgeWebView2RuntimeInstallerX64.exe

![图片](https://github.com/tauri-apps/tauri/assets/1531092/f091d5fc-6234-4a4a-ae70-6989eb2ee6fd)

![图片](https://github.com/tauri-apps/tauri/assets/1531092/9c93f7df-cc6d-4dab-b15d-9a2f3335968b)

```text
yarn run v1.22.19
$ tauri info

[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 114.0.1823.67
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.16.1
    - yarn: 1.22.19
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
Done in 11.32s.
```

**Comment by FabianLars** [comment]
That link still works fine on my end. Are you using some kind of proxy maybe?

**Comment by alexsunday** [comment]
> 

Yes, It's ok now, Maybe It's my network problem... sorry, close it.

**Comment by WingHEX** [comment]
same build fail in github action. please reopen this issue @alexsunday 
![image](https://github.com/tauri-apps/tauri/assets/2047729/33e61f62-92e3-4ce6-8b0d-d575bc9b8542)


Proposed to add a configuration option to control offline installation of package??
`
{
"type": "offlineInstaller", 
"path":"./MicrosoftEdgeWebView2RuntimeInstallerX64.exe"    //Proposed to add this option to add office installer from local
}
`

**Comment by jsshizhan** [comment]
same issue

**Comment by Lxy909** [comment]
Hello, why am I still making this error

**Comment by Lxy909** [comment]
Hello, why am I still making this error

**Comment by bramvanneerven** [comment]
I have the same issue in Azure Pipelines.

![image](https://github.com/tauri-apps/tauri/assets/35584266/e96e60b5-4329-4963-8f17-bbe8a4e97e0d)

**Comment by 277584579** [comment]
> same issue

How did solve you it
