### ISSUE TITLE
[feat] chromium instead of webkit

### ISSUE THREAD

**Issue by 7flash** [tauri-apps/tauri#7477]
### Describe the problem

Performance slow

### Describe the solution you'd like

Chromium

### Alternatives considered

WebKit newer versions

### Additional context

https://github.com/tauri-apps/tauri/issues/5761

**Comment by FabianLars** [comment]
Thanks for the request. There are no short term plans. Long term we're likely looking into cef (and maybe webview2 if Microsoft ever ports it to Linux). qtwebengine is completely off the table rn: <https://github.com/tauri-apps/tauri/issues/4554> - that issue also mentions servo which we're also interested in but it will probablyyy be pretty nieche.

**Comment by nyabinary** [comment]
Servo is back in active development so maybe there something there?

**Comment by 7flash** [comment]
Chromium (left) vs tauri webkit (right) performance comparison in linux

https://github.com/tauri-apps/tauri/assets/4569866/ab38e1ac-16a7-4456-9dbd-ee0ce29a112a

**Comment by nyabinary** [comment]
> Chromium (left) vs tauri webkit (right) performance comparison in linux
> simplescreenrecorder-2023-08-06_15.06.35.mp4

Yikes, still hoping for Servo eventually. I mean Servo can run cookie clicker now! (thats something)

**Comment by 7flash** [comment]
have migrated my app to https://github.com/webui-dev/webui which injects my app into user machine browser and implements a protocol which allows my app running in user browser to communicate with my app deno backend, perhaps similar approach can be adopted for tauri

**Comment by 7flash** [comment]
> https://github.com/webui-dev/webui

and it works with tauri bundler, here example https://github.com/7flash/galaxy-desktop-app/blob/main/build.ts

**Comment by sabitm** [comment]
Recent HN post about [webui](https://news.ycombinator.com/item?id=38830673) brings me here. It would be very cool if tauri also support these approach!

**Comment by 7flash** [comment]
> Recent HN post about [webui](https://news.ycombinator.com/item?id=38830673) brings me here. It would be very cool if tauri also support these approach!

You can achieve similar results by spawning Chrome instance directly from Deno server like demonstrated here: https://github.com/galaxydo/deno-chrome-app
