### ISSUE TITLE
[feat] How to disable or enable an item of the context menu with js/ts or rust?

### ISSUE THREAD

**Issue by Aostas** [tauri-apps/tauri#7478]
### Describe the problem

How to disable or enable an item of the context menu with js/ts or rust?

### Describe the solution you'd like

I would like to disable or enable an item of the context menu with js/ts api to prevent unexpected operations by users.

**Comment by pewsheen** [comment]
If you're talking about the system tray's context menu, from the rust side, you can access the [`tray_handle`](https://docs.rs/tauri/1.4.1/tauri/struct.App.html#method.tray_handle) first, and [get the item's handler](https://docs.rs/tauri/1.4.1/tauri/struct.SystemTrayHandle.html#method.try_get_item) that you want to disable, and then you can call the handler's [`set_enabled`](https://docs.rs/tauri/1.4.1/tauri/struct.SystemTrayMenuItemHandle.html#method.set_enabled) to `false` to disable the item.

**Comment by Aostas** [comment]
> If you're talking about the system tray's context menu, from the rust side, you can access the [`tray_handle`](https://docs.rs/tauri/1.4.1/tauri/struct.App.html#method.tray_handle) first, and [get the item's handler](https://docs.rs/tauri/1.4.1/tauri/struct.SystemTrayHandle.html#method.try_get_item) that you want to disable, and then you can call the handler's [`set_enabled`](https://docs.rs/tauri/1.4.1/tauri/struct.SystemTrayMenuItemHandle.html#method.set_enabled) to `false` to disable the item.

I am talking about the Window Menu. 
I figured out how to set the item to disable by default.
```rust
Menu::new().add_item(CustomMenuItem::new("project_save", "Save").disabled())
```
but I can't find how to get the window menu's item handler and update the enable state.
I jsut found the `update_item` function in `impl TrayHandle for MockTrayHandler`

**Comment by pewsheen** [comment]
Maybe try this [Updating menu items](https://tauri.app/v1/guides/features/menu#updating-menu-items)

You can get `menu_handle` by calling `window.menu_handle()`, then get the menu item from the `menu_handle`.

So in your case, you can do this
```rust
let menu_handle = window.menu_handle();
let menu_item_save = menu_handle.get_item("project_save");
menu_item_save.set_enabled(false);
```

**Comment by Aostas** [comment]
> Maybe try this [Updating menu items](https://tauri.app/v1/guides/features/menu#updating-menu-items)
> 
> You can get `menu_handle` by calling `window.menu_handle()`, then get the menu item from the `menu_handle`.
> 
> So in your case, you can do this
> 
> ```rust
> let menu_handle = window.menu_handle();
> let menu_item_save = menu_handle.get_item("project_save");
> menu_item_save.set_enabled(false);
> ```

Ah, how could I miss this section...

I want to use it in the command to control the menu state from the frontend.
My solution is to pass it to the command function as a managed state.
```rust
struct TauriManagedState{
    pub menu_handle: std::sync::Mutex<MenuHandle>,
}
```

```rust
#[tauri::command]
fn set_menu_enabled(state: tauri::State<'_, TauriManagedState>, id: &str, enabled: bool) {
    let menu_handle = state.menu_handle.lock().unwrap();
    menu_handle.get_item(id).set_enabled(enabled).unwrap();
}
```

```rust
    tauri::Builder::default()
        .menu(menu)
        .setup(|app| {
            let menu_handle = app.get_window("main").unwrap().menu_handle();
            let tauri_managed_state = TauriManagedState {
                menu_handle: std::sync::Mutex::new(menu_handle),
            };
            app.manage(tauri_managed_state);
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![greet, set_menu_enabled])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
```
Is it the best solution?

**Comment by pewsheen** [comment]
It depends on how you design your program 😆 

Personally, I would access the [`window`](https://tauri.app/v1/guides/features/command#accessing-the-window-in-commands) or [`app_handle`](https://tauri.app/v1/guides/features/command#accessing-an-apphandle-in-commands) from the command parameters first, and call the `window.menu_handle()`. Still, it is just my coding style that I don't use global variables and Mutex if I can access the object somehow.

### Reference
- [Accessing the Window in Commands](https://tauri.app/v1/guides/features/command#accessing-the-window-in-commands) 
- [Accessing an AppHandle in Commands](https://tauri.app/v1/guides/features/command#accessing-an-apphandle-in-commands)

**Comment by Aostas** [comment]
> It depends on how you design your program 😆
> 
> Personally, I would access the [`window`](https://tauri.app/v1/guides/features/command#accessing-the-window-in-commands) or [`app_handle`](https://tauri.app/v1/guides/features/command#accessing-an-apphandle-in-commands) from the command parameters first, and call the `window.menu_handle()`. Still, it is just my coding style that I don't use global variables and Mutex if I can access the object somehow.
> 
> ### Reference
> * [Accessing the Window in Commands](https://tauri.app/v1/guides/features/command#accessing-the-window-in-commands)
> * [Accessing an AppHandle in Commands](https://tauri.app/v1/guides/features/command#accessing-an-apphandle-in-commands)

Oh, I forgot tha I can use the `window` in command function directly.
The method above is what I use to pass the variable defined in main() to command function, instead of using a global variable.
