### ISSUE TITLE
Scale factor setting is incorrect [bug] 

### ISSUE THREAD

**Issue by Sarehn** [tauri-apps/tauri#7484]
### EDIT

After further research, I now understand that the Scale Factor property is tied to a Windows setting. Though I've noticed that Chrome and other browsers remain unaffected from changes made to that specific variable, hence I wrongly assumed this to be a bug

### Describe the bug

I've set the starting .container class to cover the whole screen (1920x1080), as such I've set the tauri.conf.json to that size as well
![image](https://github.com/tauri-apps/tauri/assets/121760157/c4b7ae48-7a35-434f-bea7-80d8aff6da13)

Opening the localhost on chrome displays the webpage correctly:
![image](https://github.com/tauri-apps/tauri/assets/121760157/5e3978fd-1d9e-48b7-9435-da395d3ac43c)

Yet the Tauri application scales everything up by 1.25 (Multiplying the container size by *0.8 does indeed revert the scale changes, yet it shouldn't be necessary):
![image](https://github.com/tauri-apps/tauri/assets/121760157/36b888ea-caa1-4dff-891a-189f26f107b8)

### Reproduction

```
.container {
  margin: 0;
  padding: 0;
  width: 1920px;
  height: 1080px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  text-align: center;
}

```
```
<div className="container">
      <h1>Welcome to Tauri!</h1>

      <div className="row">
        <a href="https://vitejs.dev" target="_blank">
          <img src="/vite.svg" className="logo vite" alt="Vite logo" />
        </a>
        <a href="https://tauri.app" target="_blank">
          <img src="/tauri.svg" className="logo tauri" alt="Tauri logo" />
        </a>
        <a href="https://reactjs.org" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>

      <p>Click on the Tauri, Vite, and React logos to learn more.</p>

      <form
        className="row"
        onSubmit={(e) => {
          e.preventDefault();
          print();
        }}
      >
        <input
          id="greet-input"
          onChange={(e) => setName(e.currentTarget.value)}
          placeholder="Enter a name..."
        />
        <button type="submit">Greet</button>
      </form>

      <p>{greetMsg}</p>
    </div>
```

### Expected behavior

I expected the scale factor to be 1, and render the page in the same way it would on chrome (which is not the case)

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19044 X64
    ✔ WebView2: 115.0.1901.183
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.71.0 (8ede3aae2 2023-07-12)
    ✔ Cargo: 1.71.0 (cfd3bbd8f 2023-06-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.17.0
    - yarn: 1.22.19
    - npm: 9.6.7

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by elibroftw** [comment]
```rust
#[cfg(target_os = "linux")]
fn webkit_hidpi_workaround() {
  // See: https://github.com/spacedriveapp/spacedrive/issues/1512#issuecomment-1758550164
  std::env::set_var("WEBKIT_DISABLE_DMABUF_RENDERER", "1");
}

fn main_prelude() {
  #[cfg(target_os = "linux")]
  webkit_hidpi_workaround();
}

fn main() {
  main_prelude();
// ...
}
```

**Comment by AtiaDjaber** [comment]
`use tauri::Manager;

fn main() {
    tauri::Builder::default()
        .plugin(tauri_plugin_printer::init())
        .setup(|app| {
            let main_window = app.get_window("main").unwrap();
            main_window.with_webview(|webview| {
                #[cfg(windows)]
                unsafe {
                    // see https://docs.rs/webview2-com/0.19.1/webview2_com/Microsoft/Web/WebView2/Win32/struct.ICoreWebView2Controller.html
                    webview.controller().SetZoomFactor(0.9).unwrap();
                }
            });
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}`

worked for me

**Comment by Borber** [comment]
Encountered this problem again

**Comment by JorgeLPascual** [comment]
I am also encountering this problem with Tauri (Rust) 2.9.4
