### ISSUE TITLE
[feat] dangerousRemoteDomainIpcAccess: improved security

### ISSUE THREAD

**Issue by doroved** [tauri-apps/tauri#7489]
### Describe the problem

Using **dangerousRemoteDomainIpcAccess** is unsafe when using external urls that we don't own.

### Describe the solution you'd like

Give the ability to specify a list of allowed **\_\_TAURI\_\_** methods. In my opinion it is enough to be able to send only the event from this window:
```js
window.__TAURI__.event.emit('tauri', 'onelove')
```
By doing so, we close access to all important api methods that can be used by an attacker.
In this case, the hacker can manipulate only events, but for this he needs to know their names and this feature is not as critical as access to other more serious api methods.

**Example**
```json
"security": {
    "dangerousRemoteDomainIpcAccess": [
        { "domain": "tauri.app", "windows": ["tauri"], "apiMethods": ["event"] }
    ]
}
```
**Result**

<img width="356" alt="image" src="https://github.com/tauri-apps/tauri/assets/30116541/aeaead7d-35cf-4822-a87b-387016ba6f29">

Or maybe it would be easier to implement a separate ability to send events from a window with an external url without having to create a method whitelisting system?

**Comment by FabianLars** [comment]
This is essentially solved in v2 already by the move to plugins i mentioned on Discord. All the current modules from that screenshot were moved to their own respective plugin so you can't enable all of them with one setting but instead allow each plugin on its own. So taking your event example it looks like this
```json
"security": {
    "dangerousRemoteDomainIpcAccess": [
        { "domain": "tauri.app", "windows": ["tauri"], "plugins": ["event"] }
    ]
}
```

I will leave this issue open in case we want to change something in v1 too (if not another team member will just close it)

**Comment by doroved** [comment]
> 

Super, I'm very excited about this feature. First of all, I want to protect myself as a developer so that user data is as secure as possible.

**Comment by lucasfernog** [comment]
We're designing configuration options to enhance such security. Good idea!

**Comment by matthiasg** [comment]
I am confused by dangerousRemoteDomainIpcAccess though. Why not allow a list of subdomains ? We host our customers on secure subdomains, having to compile a new client for each customer is really annoying and does not make us safer. 

We do not even need much, sending events could work I believe. 

Is there any likelihood this blocker will be removed from subdomains ?
