### ISSUE TITLE
[feat] Update Tauri version

### ISSUE THREAD

**Issue by idan72** [tauri-apps/tauri#7492]
### Describe the problem

Hi,

 

We have Tauri Application that I have automated tests to check it.
We have different branch that we want to check (Prod, Master, RC, private branches, feature  branches).

We want to work with the auto-update feature.

In tauri.conf.json we set the updater endpoint from where to look for update but I need to install the application from different location.

 

Can we control this endpoint dynamaclly ?
It come up that we need to create about 8 different MSI that have different updater endpoint

 

Also another problem while running automation is that I try to make silent install using msiexec but due to security issues it works also when run as Administrator so I cant do it from my code.
Do you have solution for that ?

 

Thanks 
Idan  

### Describe the solution you'd like

I would like to get solution on how it should work

**Comment by amrbashir** [comment]
I will consider this as duplicate of https://github.com/tauri-apps/tauri/issues/7422 and thus will be closed by https://github.com/tauri-apps/tauri/pull/7432 which has a new API to configure the endpoints at runtime instead of only through the configuration.

**Comment by AyalaGol** [comment]
@amrbashir If I understand correctly the solution you suggest is relevant only for a dynamic update server and not using a static JSON file?

**Comment by amrbashir** [comment]
for both, you will be able to specify the `endpoints` (where to look for an update, be it a server url or just a json file). So you can manually check for an update against the alpha Prod branch for example, then in another test, check for an update against the RC branch, and so on

**Comment by AyalaGol** [comment]
Can you write please a code example of the PR you mentioned? thanks!
in addition, I see the code was not merged yet to master.
when does it plan to be merged?

thanks!

**Comment by amrbashir** [comment]
> Can you write please a code example of the PR you mentioned?

```rs

tauri::Builder::default()
  .setup(|app| {
  	tauri::async_runtime::spawn(async {
  	  let updater = app.updater();
	  let update = update.endpoints(&["your prod/staging/feature update url"]).check().await.unwrap();
  	});
    Ok(())
  })
  .run(tauri::generate_context!())
  .expect("error while running tauri application");

```

> in addition, I see the code was not merged yet to master. when does it plan to be merged?

Hard to say but hopefully it will be available as part of 1.5 release.

**Comment by AyalaGol** [comment]
I want to check the match environment: "your prod/staging/feature update url"
by parameter that I get from outside, 
for example - I want to run the tauri application in dev& build mode and pass each time another parameter that indicates which endpoint I need.
how can I do it?
examples will be appreciated :)

**Comment by amrbashir** [comment]
```rs
tauri::Builder::default()
  .setup(|app| {
  	tauri::async_runtime::spawn(async {
  	  let updater = app.updater();
	  let update = update.endpoints(&[std::env::var("UPDATE_URL")]).check().await.unwrap();
  	});
    Ok(())
  })
  .run(tauri::generate_context!())
  .expect("error while running tauri application");
```
and so you'd run your app like this:
```
UPDATE_URL="https://your.update/url" cargo tauri run
```
or you could build a small UI where you can input the URL and then do the check in a tauri command.

**Comment by AyalaGol** [comment]
thanks!

if I want to change the updtae_url when I run the application EXE, 
for example running in bash : tauriApp.exe https://your.update/url
how can I get this param in main.rs file?

**Comment by amrbashir** [comment]
use https://doc.rust-lang.org/stable/std/env/fn.args.html
