### ISSUE TITLE
onChange event doesn't fire on <Textarea> [bug] 

### ISSUE THREAD

**Issue by turiguiliano88** [tauri-apps/tauri#7493]
### Describe the bug

**Solidjs + Mac OS:**
onChange event doesn't seem to be detected on <textarea></textarea>.
onInput event does however work fine.
onChange event on <input type="text" /> also work fine.

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.71.0 (8ede3aae2 2023-07-12)
    ✔ Cargo: 1.71.0 (cfd3bbd8f 2023-06-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 18.16.0
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: SolidJS
    - bundler: Vite
```

**Comment by pewsheen** [comment]
The `<textarea>` emits a `change` event normally on my side.
Could you explain more about your issue? Like providing the code or a minimum repo to reproduce the issue, and what is your expected behavior?

Just note that the `change` event will fire only when you lose focus on the <textarea>.

**Comment by turiguiliano88** [comment]
You are correct. The onChange event works when I lose focus on <textarea>. My mistake!
