### ISSUE TITLE
[feat] On Windows, allow to customize the name of window class used

### ISSUE THREAD

**Issue by geraudloup** [tauri-apps/tauri#7498]
### Describe the problem

Currently, on Windows, all app windows created by tauri have the same class named "Window Class", it would be neet to allow for customization of the Windows' window class name. 

One use case: some windows custom hotkey managers leverage window class names to select windows...

### Describe the solution you'd like

I would like to add a WindowConfig option called `window_classname`. Default should still be "Window Class" : it would be a non-breaking change :)

### Alternatives considered

No alternative, unless simply dumping those tools and find one using other characteristics of windows...

### Additional context

I have patched it on my side and want to contribute it to the upstream project.
It does depend on a new feature on Tao / winit side. Here are the correponding PRs:
- winit : https://github.com/rust-windowing/winit/pull/2978 
  Status : All 55 checks passed, waiting for merge
- tao : https://github.com/tauri-apps/tao/pull/770
  Status : waiting for merge

**Comment by fredemmott** [comment]
>  Default should still be "Window Class" 

Strongly disagree; I was going to file a separate issue, but as someone who doesn't use Tauri or Rust, the mandatory template is oppressive.

I make an app that interacts with windows from any app or framework; when I see "Window Class" in logs/issues, it tells me nothing - a window class of "Window Class" is meaningless in the context of the win32 `GetClassName()` function, or multiple win32 apps more broadly.

If you want a fixed window class string is necessary, perhaps "Tauri Window"?

If you're happy with a non-fixed default, something like "<appname> Window - Tauri" would be better?
