### ISSUE TITLE
[bug] "Command failed with exit code 4294967295" and "Command failed with exit code 3221225781"

### ISSUE THREAD

**Issue by JQiue** [tauri-apps/tauri#7499]
### Describe the bug

An error occurred the first time the tauri project was created
![image](https://github.com/tauri-apps/tauri/assets/45145407/acf25d60-4799-4678-851f-6431c8cd3f2e)

### Reproduction

I did the following steps:
1. `pnpm create tauri-app`
2. `cd .\tauri-app\`
3. `pnpm i`
4. `pnpm tauri dev`

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 115.0.1901.183
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.71.0 (8ede3aae2 2023-07-12)
    ✔ Cargo: 1.71.0 (cfd3bbd8f 2023-06-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.16.0
    - pnpm: 8.6.2
    - yarn: 1.22.19
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by FabianLars** [comment]
`4294967295` is just your frontend dying so shouldn't matter here. 

`3221225781` typically means that there are some libraries missing though i don't think i ever saw that with the default CTA template 🤔 

Can you cd into the src-tauri dir and run `cargo run` and see if that throws the same error?

If it does, maybe try re-installing vcredist https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022 (don't forget the system restart).

**Comment by JQiue** [comment]
This is the error I get when I execute 'cargo run'

![image](https://github.com/tauri-apps/tauri/assets/45145407/b9cdbc84-2c69-43dd-9e0c-c4e04b8892d4)

**Comment by JQiue** [comment]
I tried to install 'vcredist' and it worked out, thanks
