### ISSUE TITLE
Icon generation does not accept `--icon` - only `--i`

### ISSUE THREAD

**Issue by parker-codes** [tauri-apps/tauri#750]
If I run the command `yarn tauri --icon /mnt/c/Users/googlemac/Downloads/icon.png --compression optipng`, I get the error `Source image for tauricon not found`. I'm guessing this is because it's not recognizing that I'm specifying the path.

I then changed it to the shorthand and it worked: `yarn tauri icon --i /mnt/c/Users/googlemac/Downloads/icon.png --c optipng`

Operating System - Linux(4.19.84-microsoft-standard) - linux/x64

Node.js environment
  Node.js - 14.3.0
  tauri.js - 0.8.0

Rust environment
  rustc - 1.45.0-nightly
  cargo - 1.45.0-nightly  tauri-bundler - 0.8.0

Global packages          NPM - 6.14.5
  yarn - 1.22.4        
App directory structure
/.git        
/dist        
/node_modules
/src
/src-tauri
/static

App
  tauri.rs - 0.7.0
  mode - no-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'  Windows - MSHTML
  distDir - ../dist
  devPath - http://127.0.0.1:5000

**Comment by parker-codes** [comment]
In [tauri-icon.js](https://github.com/tauri-apps/tauri/blob/7845ec0e7ae09f9e054b16a0db67b42aaf84322a/cli/tauri.js/bin/tauri-icon.js#L19), the aliases seem to be incorrect.

The CLI args are:

```
Options
    --help, -h          Displays this message
    --log, l            Logging [boolean]
    --icon, i           Source icon (png, 1240x1240 with transparency)
    --target, t         Target folder (default: 'src-tauri/icons')
    --compression, c    Compression type [pngquant|optipng|zopfli]
```

If we change:

```js
const argv = parseArgs(process.argv.slice(2), {
  alias: {
    h: 'help',
    l: 'log',
    c: 'config',
    s: 'source',
    t: 'target'
  },
  boolean: ['h', 'l']
})
```

to:

```js
const argv = parseArgs(process.argv.slice(2), {
  alias: {
    h: 'help',
    l: 'log',
    i: 'icon',
    t: 'target',
    c: 'compression'
  },
  boolean: ['h', 'l']
})
```

would that be correct?

**Comment by lucasfernog** [comment]
Thanks for the report, sorry it took so long to evaluate.
