### ISSUE TITLE
[feat] On Windows, allow to customize the name of window class used v1.x

### ISSUE THREAD

**Issue by geraudloup** [tauri-apps/tauri#7500]
### Describe the problem

Currently, on Windows, all app windows created by tauri have the same class named "Window Class", it would be neet to allow for customization of the Windows' window class name.

One use case: some windows custom hotkey managers leverage window class names to select windows...

### Describe the solution you'd like

I would like to add a WindowConfig option called `window_classname`. Default should still be "Window Class" : it would be a non-breaking change :)

### Alternatives considered

No alternative, unless simply dumping those tools and find one using other characteristics of windows...

### Additional context

I have patched it on my side and want to contribute it to the upstream project.
It does depend on a new feature on Tao / winit side. Here are the correponding PRs:
- winit : https://github.com/rust-windowing/winit/pull/2978 
  Status : All 55 checks passed, waiting for merge
- tao : https://github.com/tauri-apps/tao/pull/770
  Status : waiting for merge

This issue is a mirror of #7498 but dedicate to the version 1 of Tauri.

**Comment by amrbashir** [comment]
No need to open multiple issues, if the feature lands in 1.x, it will be merged to 2.0 as well
