### ISSUE TITLE
[bug] "allowlist" added to tauri.config throws error 

### ISSUE THREAD

**Issue by snoop244** [tauri-apps/tauri#7501]
### Describe the bug

When I copy the allowlist example from the fs section of the javascript api docs into my project and try to run it, I get: ```Error `tauri.conf.json` error on `tauri`: Additional properties are not allowed ('allowlist' was unexpected)
```
I copied two allowlist objects from your docs and both produced the same error. Both were placed in the "tauri" section.


### Reproduction

Here is the "tauri" section that will cause the error.
```
"tauri": {
    "allowlist": {
      "fs": {
        "all": true, 
        "readFile": true,
        "writeFile": true,
        "readDir": true,
        "copyFile": true,
        "createDir": true,
        "removeDir": true,
        "removeFile": true,
        "renameFile": true,
        "exists": true
      }
    },
    "bundle": {
      "active": true,
      "targets": "all",
      "identifier": "com.tauri.dev",
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ]
    },
    "security": {
      "csp": null
    },
    "windows": [
      {
        "fullscreen": false,
        "resizable": true,
        "title": "Koriographer",
        "width": 1400,
        "height": 1200,
        "theme": "Light"
      }
    ]
  },
```

### Expected behavior

I expect the project to compile and run. Ultimately, I exptect to use the fs api to acess files.

### Platform and versions

```text
[✔] Environment
    - OS: Manjaro 23.0.0 X64
    ✔ webkit2gtk-4.1: 2.40.3
    ✔ rsvg2: 2.56.2
    ✔ rustc: 1.73.0-nightly (39f42ad9e 2023-07-19)
    ✔ Cargo: 1.73.0-nightly (1b1555676 2023-07-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: nightly-x86_64-unknown-linux-gnu (default)
    - node: 20.4.0
    - yarn: 1.22.19
    - npm: 9.8.0

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.10
    - tauri-build [RUST]: 2.0.0-alpha.6
    - wry [RUST]: 0.28.3
    - tao [RUST]: 0.19.1
    - @tauri-apps/api [NPM]: 2.0.0-alpha.5
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.10

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

### Stack trace

```text
yarn run v1.22.19
$ tauri dev
       Error `tauri.conf.json` error on `tauri`: Additional properties are not allowed ('allowlist' was unexpected)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 1
```

**Comment by amrbashir** [comment]
You are using 2.0.0-alpha which doesn't have the allowlist there anymore, the allowlist has been moved to plugins, see https://github.com/tauri-apps/plugins-workspace/tree/v2/plugins

**Comment by snoop244** [comment]
Ok, but I selected the Alpha 2 dropdown on the Tauri site expecting those docs. Not complaining as I know you guys are busy. Just an FYI.

Just to confirm: there is no "allowlist", correct? I tried the plugin with the readDir() function. It finds the path but I get "Error: forbidden path". I tried adding the allowlist back in after adding the plugin, and the application simply failed to compile with no specific error reported in CLion.

**Comment by snoop244** [comment]
Solved this. The example in the fs repo V2 doesn't mention that I need to add a scope entry to the "plugins" object in tauri.conf.json. I did find reference to it in the source. I suggest adding that to the readme in the fs V2 repo.

**Comment by amrbashir** [comment]
Alpha docs are still in the works so it is expected for now, thanks for your feedback.

**Comment by markfswe** [comment]
For anyone here wondering how to do it, here is an example:

```
	"plugins": {
		"fs": {
			"scope": {
				"allow": [
					"$AUDIO",
					"$AUDIO/*"
				]
			}
		}
	}
```

https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/fs/src/config.rs

**Comment by jamalsoueidan** [comment]
"permissions": ["core:default", "shell:allow-open", "http:default"]
 
 http:default is not allowed.

{
  "permissions": [
    {
      "identifier": "http:default",
      "allow": [{ "url": "https://*.tauri.app" }],
      "deny": [{ "url": "https://private.tauri.app" }]
    }
  ]
}

is not allowed!

https://v2.tauri.app/plugin/http-client/

**Comment by FabianLars** [comment]
i think this should mean that you don't have the plugin installed at all. @jamalsoueidan Can you post the output of the `tauri info` command please?

**Comment by Prasannajaga** [comment]
> Solved this. The example in the fs repo V2 doesn't mention that I need to add a scope entry to the "plugins" object in tauri.conf.json. I did find reference to it in the source. I suggest adding that to the readme in the fs V2 repo.

Hey @snoop244 , would appreciate if you share the code , I was stuck at this for  a while now.

**Comment by Please-just-dont** [comment]
How am I supposed to modify the allowlist? The only docs I can find tell me to do it the old way and that doesn't work anymore.

**Comment by FabianLars** [comment]
there's no allowlist in v2. it was replaced with a capability based permission system. Each plugin docs should contain a section about their permissions but the general gist is explained here https://v2.tauri.app/security/capabilities/
