### ISSUE TITLE
[bug] how to pack dlls in a folder

### ISSUE THREAD

**Issue by superchow** [tauri-apps/tauri#7505]
### Describe the bug

I have some dlls, I know it work if dlls in `src-tauri`, eg `src-tauri/test.dll`, but folder (`src-tauri/dlls/test.dll`) can't be found

### Platform and versions

```text
all platforms
```

### Stack trace

```text
note: LINK: fatal error LNK1181 cannot open input file 'test.lib'
```

**Comment by FabianLars** [comment]
This should solve this: https://github.com/tauri-apps/tauri/pull/5950. It will be part of the upcoming v1.5 release.
