### ISSUE TITLE
[feat]  Add an event to listen for file downloads 

### ISSUE THREAD

**Issue by LetFree** [tauri-apps/tauri#7516]
### Describe the problem

 I want to wait for the download to complete and use the system software to automatically open the file 

### Describe the solution you'd like

just like [electron will-download](https://www.electronjs.org/zh/docs/latest/api/download-item) listens for events

**Comment by FabianLars** [comment]
Thanks for the request! This is part of https://github.com/tauri-apps/tauri/issues/4633, so let's track it over there :)
