### ISSUE TITLE
[bug] Windows do not respect "focus" property

### ISSUE THREAD

**Issue by Jackson0ne** [tauri-apps/tauri#7519]
### Describe the bug

Hi all,

First off, just wanted to say that I'm really enjoying using Tauri and have had great feedback from users so far!

I seem to be having an issue with focus behaviour on all windows on the Windows platform. I've noticed it in quite a few different scenarios, and my app's users are also seeing the same behaviour, so thought I would report it!

It seems that because the default focus of all windows is set to `true`, this will always either override a `"focus"` setting of `false` in newly created windows at runtime, or will be just be ignored.

Additionally, I've found through testing that the focus state of new windows appears to be linked to the initial focus state of the main window, which can be seen in the linked reproduction.

However, I've noticed caveats to this behaviour - if running `npm run tauri dev` from Command Prompt and unfocusing the console window before the app starts, the app window will follow the focus state of the Command Prompt window - i.e. if it is unfocused before starting, the main app window will be unfocused too. Conversely, if the Command Prompt window is focused, the main window will then be focused.

This causes an issue for my app in particular. I have a background process that triggers new "notification" windows to be spawned on an event, and these windows are meant to overlay a currently running game. But upon spawning, will take focus away from the game to focus themselves, which is obviously not intended behaviour, as these "notification" windows should never be intended to focus in the first place with `"focus": false` set in the Window Options.

I believe a fair workaround to this issue would be to reset the default focus state of all windows to be `false` instead of `true`, as windows have methods to focus themselves (via `setFocus`), but no methods to unfocus them from what I have seen (although I'm happy to be wrong if there is!). If this is not possible, a method to unfocus the window before spawning would be massively beneficial, or to incorporate the `focusable` property from Electron as a new Window Option, which specifies that the spawned window may never take focus if set to `false`.

### Reproduction

I've created a [reproduction](https://github.com/Jackson0ne/tauri-focus-bug/tree/main) that demonstrates at least some of these issues.

If the first window is initially unfocused before the second window appears, the second window's focus property will be reported as `false` in the DevTools Console. But if the first window **is** focused when the second window is spawned, its focus will then be reported as `true`.

### Expected behavior

The `"focus"` property in both `tauri.conf.json` and via window creation in Rust and JS will be followed and applied independently to any other window's focus state.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 115.0.1901.183
    ✔ MSVC:
        - Visual Studio Community 2017
        - Visual Studio Community 2019
    ✔ rustc: 1.66.1 (90743e729 2023-01-10)
    ✔ Cargo: 1.66.1 (ad779e08b 2023-01-10)
    ✔ rustup: 1.25.1 (bb60b1e89 2022-07-12)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 14.18.1
    - npm: 6.14.15

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../src
    - devPath: ../src
```

**Comment by muwoo** [comment]
@amrbashir I created the window by using `focused(false)`, and it behaves normally on Windows. Every time my message notification window appears, it does not automatically focus. However, `focused(false)` does not work on MacOS. Is this a problem with my usage?

**Comment by amrbashir** [comment]
it is unsupported on macOS, at least the webview portion of the window. I don't know much about macOS so can't help there.

**Comment by muwoo** [comment]
Oh, that's it, thank you for your reply

**Comment by alberteddu** [comment]
Hello — I am also having some trouble with this. Does this mean that there are no plans to support `focus` in MacOS? I could help with the implementation (although I am not sure if I able to), but it could be that it is simply impossible on MacOS.

**Comment by Arvmor** [comment]
Encountering the same issue, on MacOS it doesn’t respect the `focus(false)`

and upon a new window getting launched, the **Main** window gets refocused!

any workarounds?
