### ISSUE TITLE
Eval does not run at reload[bug] 

### ISSUE THREAD

**Issue by NoelJacob** [tauri-apps/tauri#7524]
### Describe the bug

Eval only runs when the `tauri dev` launches with a compiling time of few seconds after showing as Building. When I close it and recompile again, it doesn't run the eval script. The second compile takes only few milliseconds. For my app the eval string is supplied when I call app.run() via IPC. It has this same behaviour when I statically keep a `console.log("test")` as eval string.

### Platform and versions

```text
[✔] Environment
    - OS: Garuda Linux Soaring X64
    ✔ webkit2gtk-4.0: 2.40.4
    ✔ rsvg2: 2.56.3
    ✔ rustc: 1.73.0-nightly (31395ec38 2023-07-24)
    ✔ Cargo: 1.73.0-nightly (1b1555676 2023-07-18)
    ✔ rustup: 1.26.0 (2023-05-04)
    ✔ Rust toolchain: nightly-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.16.0
    - yarn: 1.22.19

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../src
    - devPath: ../src
    - bundler: Webpack
```

**Comment by amrbashir** [comment]
Could you please provide a repro?
