### ISSUE TITLE
[bug] 在window11 上什么都不显示，就一个大白框

### ISSUE THREAD

**Issue by SeaIsCoder** [tauri-apps/tauri#7526]
### Describe the bug

![image](https://github.com/tauri-apps/tauri/assets/16337003/8a98b73b-1509-4a5f-821c-123a1d6bb703)
![image](https://github.com/tauri-apps/tauri/assets/16337003/2c597044-673d-47b9-98a7-c6eb0d930484)

`cargo install create-tauri-app --locked

cargo create-tauri-app

cd appss

cargo tauri dev`

### Platform and versions

```text
D:\works\rustWorks\appss>cargo tauri info
WARNING: no lock files found, defaulting to npm

[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 115.0.1901.188
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.71.0 (8ede3aae2 2023-07-12)
    ✔ Cargo: 1.71.0 (cfd3bbd8f 2023-06-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 16.14.2
    - yarn: 1.22.18
    - npm: 9.6.7
```

**Comment by thy486** [comment]
1. 请提供最小可复现案例
2. [你需要仔细阅读这篇文章](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**Comment by SeaIsCoder** [comment]
@thy486 
 我是按照 [Quick Start](https://tauri.app/v1/guides/getting-started/setup/)
 用的 cargo 和 yarn 的 两种方式， 并未写其他的代码，都尝试了，都是能出来窗口，
但是窗口中未显示内容，仅仅是白框。
我有两台笔记本，其中一台是windows10的能正常显示内容，
在 windows 11的那台笔记本上， http://localhost:1420 在浏览器上能正常显示内容，
但是在 `cargo tauri dev` 或者 `yarn tauri dev` 下都是空白的窗口界面。

**Comment by l1xnan** [comment]
Try modifying the registry:
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\WebView2]
"RendererCodeIntegrityEnabled"=dword:00000000

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge]
"RendererCodeIntegrityEnabled"=dword:00000000
```
Refer to: https://github.com/l1xnan/jupyterlab-desktop/blob/main/src-tauri/src/main.rs#L43C1-L78C1

**Comment by SeaIsCoder** [comment]
@l1xnan sorry, not working, not find the Edge in "\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft"
![image](https://github.com/tauri-apps/tauri/assets/16337003/2ae66b4b-a8d7-41ae-ad26-18a446ef5b90)

**Comment by SeaIsCoder** [comment]
the code is 
```
// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

// Learn more about Tauri commands at https://tauri.app/v1/guides/features/command
#[tauri::command]
fn greet(name: &str) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

fn main() {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```
![image](https://github.com/tauri-apps/tauri/assets/16337003/c99d437b-a290-4d5d-a36c-e396ef0a8c58)


 just show blank , and  the close button not work yet.

**Comment by l1xnan** [comment]
> @l1xnan sorry, not working, not find the Edge in "\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft" !

The registry key does not exist by default. You need to manually add it

**Comment by SeaIsCoder** [comment]
@l1xnan   after i add the registry keys, it still show blank .
i try  Compatibility mode，it works 
![image](https://github.com/tauri-apps/tauri/assets/16337003/2a495c02-daeb-4a95-b0c9-c6f4a5a7512e)

**Comment by SeaIsCoder** [comment]
but one more question, when i code and rtauri dev in windows 11,it still show blank,  how to do ?

**Comment by tangramor** [comment]
> @l1xnan after i add the registry keys, it still show blank . i try Compatibility mode，it works ![image](https://private-user-images.githubusercontent.com/16337003/257710545-2a495c02-daeb-4a95-b0c9-c6f4a5a7512e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MDYzNTcsIm5iZiI6MTcwNjYwNjA1NywicGF0aCI6Ii8xNjMzNzAwMy8yNTc3MTA1NDUtMmE0OTVjMDItZGFlYi00YTk1LWIwYzktYzZmNGE1YTc1MTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA5MTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5MTg3OWMwNTVlNDNjZjFkOGI1YjljYWY5YjlkMWVjYjg0ZDAxNDFkNWU2ZWE3ZjU0NTk2Yzk2YmE3NjdlYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f1LTqYZ1O5s0kLoIqn4XsNvd9jRTgAESXw999NhHLD4)

The Compatibility mode is the only work solution for me. 

I met the blank page problem with the simplest tauri example on Windows 10, and I searched for many solutions, only this reply saved my time... Thanks!

**Comment by VCCICCV** [comment]
I encountered the same issue while using ​​Bun + Svelte + TypeScript​​. I'm developing on ​​Ubuntu 24.04.2 LTS​​ and followed the steps on ​​https://v1.tauri.app/v1/guides/getting-started/setup/

​​ to create the application. Initially, it worked fine, but today:

    ​​The web version​​ displays styles but fails to test inputs.
    ​​The desktop version​​ shows a blank white window.

I haven’t modified the code, and it seems like a ​​network proxy issue​​. However, even after disabling the proxy, it still doesn’t work properly.

![Image](https://github.com/user-attachments/assets/324e7190-4ae9-4188-8aa0-f01232d02073)

![Image](https://github.com/user-attachments/assets/c4fbd3df-0b2b-4670-8a36-22b854d3cb02)

**Comment by Chen-jiashen** [comment]
同样的问题，白屏+ 关闭无反应。
尝试了添加注册表和兼容模式，都不起作用。
gpt ai 分析说可能和我的显卡太老有关，公司电脑为了双屏办公，买了一个亮机卡，很老。

**Comment by sincerely-hello-world** [comment]
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble
``` 

- vue+vite 新建的tauri项目,使用的pnpm包管理器。


我也遇到了的tauri应用启动后白屏的现象。
最初，我通过简单直接的reload应用界面即可正常显示，但这很影响开发体验。



- 然后，我排查了下控制台，发现是svg图标资源问题，修改一下即可正常显示。
<img width="1244" height="1157" alt="Image" src="https://github.com/user-attachments/assets/14f2f1b1-f7dd-4614-b607-42306ab11fbc" />

1. 把 /public/vite.svg 和 /public/tauri.svg 复制到  /src/assets/
2. 修改 App.vue的资源路径
```
  <a href="https://vite.dev" target="_blank">
    <img src="./assets/vite.svg" class="logo vite" alt="Vite logo" />
  </a>
  <a href="https://tauri.app" target="_blank">
    <img src="./assets/tauri.svg" class="logo tauri" alt="Tauri logo" />
  </a>
```
3. 然后等待应用重载，正常启动并显示：

<img width="1339" height="1074" alt="Image" src="https://github.com/user-attachments/assets/c0589700-a7e8-4c65-b381-da799d9bba6d" />
