### ISSUE TITLE
iframe video error 

### ISSUE THREAD

**Issue by alexou2** [tauri-apps/tauri#7527]
### Describe the bug

when I try to link an iframe in tauri, i will get error Code: 10263 In firefox(with localhost:1430), the video will play.

### Reproduction

insert this line in an html file
<iframe src="https://gotaku1.com/streaming.php?id=MjA5MjA2&title=Ao+no+Orchestra+Episode+17" allowfullscreen="true" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe>

### Expected behavior

the video should offer the option to play 

### Platform and versions

```text
[✔] Environment
    - OS: Ubuntu 23.04 X64
    ✔ webkit2gtk-4.0: 2.40.1
    ✔ rsvg2: 2.54.5
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.13.0
    - npm: 9.2.0

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../src
    - devPath: ../src
```

### Additional context

I saw other issues like mine, but I couldn't find how they fixed it

**Comment by YotamOfri** [comment]
how do you get the id of each anime like here MjA5MjA2? i searched the web for every api and didn't find any

**Comment by alexou2** [comment]
i just inspeted the iframe and got the url of the video. the website i scraped is https://gogoanimehd.to/
