### ISSUE TITLE
[bug] Invoking tauri command got error `Scope not defined for window ` using version v2.0.0-alpha.10

### ISSUE THREAD

**Issue by mtfcd** [tauri-apps/tauri#7531]
### Describe the bug

Using version v2.0.0-alpha.10. Invoking tauri command got error: 
```
Uncaught (in promise) Scope not defined for window `main` and URL `https://tauri.localhost/`. See https://tauri.app/v1/api/config/#securityconfig.dangerousremotedomainipcaccess and https://docs.rs/tauri/1/tauri/scope/struct.IpcScope.html#method.configure_remote_access
```
This error only occur on windows and when installed using `tauri build`, both `tauri build` and `tauri build --debug`. No error in `tauri dev` or `tauri dev --release`. On linux there is no error either `dev` or `build`. 

if add `dangerousRemoteDomainIpcAccess` config in tauri.conf.json. every thing is ok. but on linux this is not needed.

### Reproduction

just follow the quick start guide, and update dependencies to 2.0.0-alpha:

1. cargo create-tauri-app
✔ Project name · test_invoke
✔ Choose which language to use for your frontend · TypeScript / JavaScript - (pnpm, yarn, npm)
✔ Choose your package manager · pnpm
✔ Choose your UI template · React - (https://reactjs.org/)
✔ Choose your UI flavor · TypeScript

2. cargo add tauri@2.0.0-alpha.10
3. cargo add tauri-build@2.0.0-alpha.6 --build
4. cargo install tauri-cli --version "^2.0.0-alpha"
5. pnpm update @tauri-apps/cli@next @tauri-apps/api@next
6. run `cargo tauri build`, get error "'allowlist' was unexpected", so remove allowlist from tauri.conf.json. 
7. change bundle identifier.
8. cargo tauri build --debug
10. run `target\debug\test_invoke.exe
11. open devtools
12. click `greet` button, got the error.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 115.0.1901.188
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.71.0 (8ede3aae2 2023-07-12)
    ✔ Cargo: 1.71.0 (cfd3bbd8f 2023-06-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.16.0
    - pnpm: 8.6.6
    - yarn: 1.22.19
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.10
    - tauri-build [RUST]: 2.0.0-alpha.6
    - wry [RUST]: 0.28.3
    - tao [RUST]: 0.19.1
    - @tauri-apps/api [NPM]: 2.0.0-alpha.5
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.10

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by henit-chobisa** [comment]
hey @mtfcd, can I see your tauri.conf.json, I had the same problem and I resolved it.

**Comment by mtfcd** [comment]
@henit-chobisa this is my config:
```
{
  "build": {
    "beforeDevCommand": "pnpm dev",
    "beforeBuildCommand": "pnpm build",
    "devPath": "http://localhost:1420",
    "distDir": "../dist",
    "withGlobalTauri": false
  },
  "package": {
    "productName": "test_invoke",
    "version": "0.0.0"
  },
  "tauri": {
    "bundle": {
      "active": true,
      "targets": "all",
      "identifier": "cc.mtfcd.test-invoke",
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ]
    },
    "security": {
      "csp": null
    },
    "windows": [
      {
        "fullscreen": false,
        "resizable": true,
        "title": "test_invoke",
        "width": 800,
        "height": 600
      }
    ]
  }
}
```

**Comment by mtfcd** [comment]
I found this bug is gone in branch `dev`. I don't know if it's fixed or not.

**Comment by amrbashir** [comment]
I will go ahead and close this then, I think it was indeed solved in the dev branch. let me know if you still face the issue.

**Comment by jiajianlu-crypto** [comment]
@amrbashir 
how to add 'dangerousRemoteDomainIpcAccess' config ? when i add this config and build, i alway get this error:
```rust
 Error `tauri.conf.json` error on `tauri > security`: Additional properties are not allowed ('dangerousRemoteDomainIpcAccess' was unexpected)
```

but according the doc, the dangerousRemoteDomainIpcAccess proerties is under the secrity field.  by the way, my tauri-build version is 1.4.0

**Comment by FabianLars** [comment]
@jiajianlu-crypto That error comes from the cli so make sure that your tauri cli is also on 1.4

**Comment by Stancobridge** [comment]
Am facing this issue currently, how can one resolve it
`Scoped command binaries/main not found`
