### ISSUE TITLE
[bug] resize causes content to disappear

### ISSUE THREAD

**Issue by jonathanforhan** [tauri-apps/tauri#7537]
### Describe the bug

on resize of tauri app the app goes blank filled with the webview background.

https://github.com/tauri-apps/tauri/assets/99012095/972ea04b-04a0-49d5-9acc-e0cecf864d05

### Reproduction

Pop-OS 22.04
X11
KDE plasma-desktop
nvidia drivers
kernel 6.2.6-76060206-generic

> yarn create tauri-app

resize application and the graphics will glitch

### Expected behavior

smooth transition, no flashing of the default webview background

### Platform and versions

```text
> foobar@0.0.0 tauri
> tauri info


[✔] Environment
- OS: Pop!_OS 22.04 X64
✔ webkit2gtk-4.0: 2.40.4
✔ rsvg2: 2.52.5
✔ rustc: 1.70.0 (90c541806 2023-05-31)
✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
- node: 20.3.1
- yarn: 1.22.19
- npm: 9.7.2

[-] Packages
- tauri [RUST]: 1.4.1
- tauri-build [RUST]: 1.4.0
- wry [RUST]: 0.24.3
- tao [RUST]: 0.16.2
- @tauri-apps/api [NPM]: 1.4.0
- @tauri-apps/cli [NPM]: 1.4.0

[-] App
- build-type: bundle
- CSP: unset
- distDir: ../dist
- devPath: http://localhost:1420/
- bundler: Vite
```

### Stack trace

```text
no error, no logs either consoles, nothing unusual in journalctl
```

**Comment by jonathanforhan** [comment]
electron apps such as vscode and spotify do not exhibit this behavior

**Comment by FabianLars** [comment]
This should be mostly out of our control and just webkit being webkit again. Can you try running it with the `WEBKIT_DISABLE_COMPOSITING_MODE=1` env var set?
