### ISSUE TITLE
[bug] Numpad keys cannot be bind with globalShortcut key

### ISSUE THREAD

**Issue by ddemile** [tauri-apps/tauri#7543]
### Describe the bug

When i try to register a globalShortcut including for example Numpad1 or 1 it's not working, i have this error:
`Uncaught (in promise) Unable to register accelerator (unknown VKCode for this char).`

### Reproduction

Try to register a shortcut including a numpad key (example: Ctrl+Numpad1)

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 115.0.1901.188
    ✔ MSVC:
        - Visual Studio Build Tools 2017
        - Visual Studio Community 2022
    ✔ rustc: 1.71.0 (8ede3aae2 2023-07-12)
    ✔ Cargo: 1.71.0 (cfd3bbd8f 2023-06-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.12.1
    - npm: 8.19.2
```

**Comment by amrbashir** [comment]
Closing as this should be fixed in v2 with the `global-shortcut` plugin
