### ISSUE TITLE
On first load, invoke function from client side doesn't work properly

### ISSUE THREAD

**Issue by Vrajs16** [tauri-apps/tauri#7546]
### Describe the bug

I am using Svelte and Tauri.  The following example works and get the data correctly
```svelte
<script>
let data = [];

async function get_some_data_from_db() {
     invoke("get_some_data_from_db").then((db_data) => {
      data = db_data;
    });
}
</script>

<button on:click={get_some_data_from_db}>
    Get Data
</button>
 
<pre>
    {JSON.stringify(data, null, 4)}
</pre>
 ```
However when I make it so that it runs this function on mount, it doesn't get the data on the first load when I run `cargo tauri dev`.

```svelte
<script>
let data = [];

onMount(() => {
 invoke("get_some_data_from_db").then((db_data) => {
      data = db_data;
    });
});

</script>
 
<pre>
    {JSON.stringify(data, null, 4)}
</pre>
 ```

 I have to manually refresh the application (by right clicking) and then it works which is really strange.
 Am I missing something?

### Reproduction

The above code

### Expected behavior

It should load on the first load when running cargo tauri dev

### Platform and versions

```text
Environment
    - OS: Mac OS 13.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.73.0-nightly (db7ff98a7 2023-07-31)
    ✔ Cargo: 1.73.0-nightly (c91a693e7 2023-07-31)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: nightly-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.16.0
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

### Stack trace

```text
None
```

### Additional context

None

**Comment by amrbashir** [comment]
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) and fill the appropriate information fields to reopen the issue. Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

Also look for any errors in the webview dev tools.
