### ISSUE TITLE
[bug] How to link dylib files?

### ISSUE THREAD

**Issue by superchow** [tauri-apps/tauri#7547]
### Describe the bug

`#[link(name = "Mylib" )]` works on the Windows, but Mac failed🚬

I try code in `build.rs`

``` rust
let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
println!("cargo:rustc-link-search=native={}", manifest_dir.display());
println!("cargo:rustc-link-lib=Mylib");
```

but also not work.

```
dyld[29363]: Library not loaded: @rpath/libMylib.dylib
  Referenced from: <987AFB97-031F-3387-A7C3-047E9989602C> /Users/admir/Desktop/Code/rust-desktop-demo/src-tauri/target/debug/tauri-ts-demo
  Reason: tried: '/System/Volumes/Preboot/Cryptexes/OS@rpath/libSampleBlueTooth.dylib' (no such file), '/usr/local/lib/libMylib.dylib' (no such file), '/usr/lib/libMylib.dylib' (no such file, not in dyld cache)
```

How Can i link libMylib.dylib success?

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.71.0 (8ede3aae2 2023-07-12)
    ✔ Cargo: 1.71.0 (cfd3bbd8f 2023-06-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.5.0
    - yarn: 1.22.19
    - npm: 9.8.0

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: default-src 'self'; img-src *; media-src *
    - distDir: ../build
    - devPath: http://localhost:3000/
    - framework: React
```

### Stack trace

```text
dyld[29363]: Library not loaded: @rpath/libMylib.dylib
  Referenced from: <987AFB97-031F-3387-A7C3-047E9989602C> /Users/admir/Desktop/Code/rust-desktop-demo/src-tauri/target/debug/tauri-ts-demo
  Reason: tried: '/System/Volumes/Preboot/Cryptexes/OS@rpath/libSampleBlueTooth.dylib' (no such file), '/usr/local/lib/libMylib.dylib' (no such file), '/usr/lib/libMylib.dylib' (no such file, not in dyld cache)
```

**Comment by amrbashir** [comment]
This seems like a general rust issue, and not specific to tauri so I will close this for now.

If you feel like it is indeed something with tauri, like it works with a normal, please let me know and provide a minimal repro.

**Comment by thewh1teagle** [comment]
I experience the same issue,
I need to add ffmpeg dylib(s) to tauri app. 
I added them from himebrew and update the executable 
and I can see that the dmg file has that and ldd shows that it gets them from relative path.
but I got the same error.

**Comment by leovandriel** [comment]
Had similar issue linking python for use in PyO3:

```
dyld[68631]: Library not loaded: @rpath/libpython3.10.dylib
  Referenced from: <19D37237-638A-8272-D4C8-8922F78C4401> /Users/name/project/src-tauri/target/debug/App
  Reason: no LC_RPATH's found
```

Was able to fix this by referencing the dylib in `tauri.conf.json` under `tauri.macOS.frameworks`:

```json
{
  "tauri": {
    "macOS": {
      "frameworks": [
        "../assets/libpython3.10.dylib"
      ]
    }
  }
}
```

credits: https://github.com/tauri-apps/tauri/issues/4615

**Comment by iskng** [comment]
> Had similar issue linking python for use in PyO3:
> 
> ```
> dyld[68631]: Library not loaded: @rpath/libpython3.10.dylib
>   Referenced from: <19D37237-638A-8272-D4C8-8922F78C4401> /Users/name/project/src-tauri/target/debug/App
>   Reason: no LC_RPATH's found
> ```
> 
> Was able to fix this by referencing the dylib in `tauri.conf.json` under `tauri.macOS.frameworks`:
> 
> ```json
> {
>   "tauri": {
>     "macOS": {
>       "frameworks": [
>         "../assets/libpython3.10.dylib"
>       ]
>     }
>   }
> }
> ```
> 
> credits: #4615

@leovandriel Do you mind describing your pyo3 setup?
Did you bundle external packages into the app framework also or do you recreate an environment on the target machine?

**Comment by ppoliani** [comment]
> > Had similar issue linking python for use in PyO3:
> > ```
> > dyld[68631]: Library not loaded: @rpath/libpython3.10.dylib
> >   Referenced from: <19D37237-638A-8272-D4C8-8922F78C4401> /Users/name/project/src-tauri/target/debug/App
> >   Reason: no LC_RPATH's found
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Was able to fix this by referencing the dylib in `tauri.conf.json` under `tauri.macOS.frameworks`:
> > ```json
> > {
> >   "tauri": {
> >     "macOS": {
> >       "frameworks": [
> >         "../assets/libpython3.10.dylib"
> >       ]
> >     }
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > credits: #4615
> 
> @leovandriel Do you mind describing your pyo3 setup? Did you bundle external packages into the app framework also or do you recreate an environment on the target machine?

@leovandriel could you help us with this?

**Comment by ivnsch** [comment]
Where do I add this / is this up to date? If I add it to `tauri.conf.json` under root, it complains:

> Property tauri is not allowed.

```
{
  "$schema": "https://schema.tauri.app/config/2",
  // ...
  "tauri": {
    "macOS": {
      "frameworks": [
        "../assets/libpython3.10.dylib"
      ]
    }
  }

}
```

**Comment by FabianLars** [comment]
replace "tauri" with "bundle"
