### ISSUE TITLE
[bug] What is the use of the eight tokio-runtime-worker started with tauri?

### ISSUE THREAD

**Issue by zhouyangtingwen** [tauri-apps/tauri#7548]
### Describe the bug

![image](https://github.com/tauri-apps/tauri/assets/130919942/5bab5338-2d7c-4964-ba97-c2e19297e729)

R2d2-worker is the thread that my program starts, but what are the eight `tokio-runtime-worker` responsible for? 
I've tried most tauri app, and they all have these eight `tokio-runtime-worker`.

### Platform and versions

```text
$ tauri info

[✔] Environment
    - OS: Mac OS 12.3.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.68.2 (9eb3afe9e 2023-03-27)
    ✔ Cargo: 1.68.2 (6feb7c9cf 2023-03-26)
    ✔ rustup: 1.25.2 (fae52a197 2023-02-01)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 14.18.0
    - yarn: 1.22.19
    - npm: 6.14.15

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: default-src 'self'; img-src 'self' asset: *; script-src 'self' asset: https://asset.localhost; style-src 'unsafe-inline'  asset: *; media-src *;
    - distDir: ../dist
    - devPath: http://localhost:5173/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Tokio's default runtime create worker threads equal to the amount of cpu cores.
Tokio is used as tauri's general async runtime, most noticibly for async [commands](https://tauri.app/v1/guides/features/command#async-commands) and the [async_runtime module](https://docs.rs/tauri/latest/tauri/async_runtime/) but it's also used for some predefined apis and internal stuff.
