### ISSUE TITLE
[bug] Splashscreen and main windows are visible in the final msi build for Win11

### ISSUE THREAD

**Issue by MassivDash** [tauri-apps/tauri#7556]
### Describe the bug

During development ```cargo tauri dev``` the official example for splashscreen works as expected on all platforms, however the windows 11 final msi builds shows both the main and splashscreen,  seems to be not respecting the visble rule mentioned in #5583, i also tried to cargo update mentioned in the issue but with no success. 

project code: https://github.com/MassivDash/S3_Manager 

I am unable to test behavior on windows 10, so the problem could be only related to Win11, all other final builds are consistent with dev env

### Reproduction

- create a fresh svelte project 
- add splashscreen accroding to docs https://tauri.app/v1/guides/features/splashscreen/ 
- build the project on win11
- Observe 2 screen showed at once  

### Expected behavior

That the splashscreen development behavior will be conistest with the final build

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 115.0.1901.188
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.71.0 (8ede3aae2 2023-07-12)
    ✔ Cargo: 1.71.0 (cfd3bbd8f 2023-06-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.17.0
    - npm: 9.6.7

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:3000/
    - framework: Svelte
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Can you try again after re-ordering the windows in tauri.conf.json so that the splashscreen is first? If that doesn't work, try using a 100ms setTimeout for the close_splashscreen invoke call just to check if it's a timing issue, which is my guess rn since the app starts way faster in release mode compared to dev.

**Comment by MassivDash** [comment]
Changing the sequence of windows have corrected the problem. Thanks  for the tip. 

I will close the issue, by the way the splash screen docs do imply adding the the splash after the main window.

**Comment by seongs1024** [comment]
The `splashscreen.html` file seems to be missing while building the installer.
Found that if the url of the splashscreen in `tauri.conf.json` is changed to some web url, like `https://www.google.com`, the window can visible.

**Comment by seongs1024** [comment]
Solve it by following [the document](https://tauri.app/v1/guides/features/splashscreen#setup), if `splashscreen.html` is in the workspace root, need to configure `disDir` like so
```json
  "build": {
    ...
    "distDir": [
      "../dist",
      "../splashscreen.html"
    ]
  },
```
