### ISSUE TITLE
[bug] NSIS quiet update do not restart the app

### ISSUE THREAD

**Issue by Alexandre789010** [tauri-apps/tauri#7560]
### Describe the bug

Hi,

The application does not restart after being updated quietly, I used the NSIS installer.

```json
"updater": {
      "active": true,
      "endpoints": [
        "xxx/sdsshupdater/{{target}}/{{arch}}/{{current_version}}"
      ],
      "dialog": false,
      "pubkey": "xxx",
      "windows": {
        "installMode": "quiet"
      }
    },
```

When I restart the app (manually) after the update - the new version version is there and has been successfully installed.

Thanks for all your work!

### Expected behavior

The application should restart after the update.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 115.0.1901.188
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.71.0 (8ede3aae2 2023-07-12)
    ✔ Cargo: 1.71.0 (cfd3bbd8f 2023-06-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.16.1
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.3.0 (outdated, latest: 1.4.0)
    - @tauri-apps/cli [NPM]: 1.3.1 (outdated, latest: 1.4.0)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Can you update the cli (`@tauri-apps/cli`) to 1.4, re-build the app and try again please?

**Comment by Alexandre789010** [comment]
Hi @FabianLars,

I updated to 1.4, unfortunately still the same output

**Comment by FabianLars** [comment]
You may have to rebuild both, the old and new versions with that tauri version for it to work, did you do that?

I'm a bit out of ideas tbh since it's working fine on my end. So if that doesn't help i _think_ i'll need a minimal reproduction or wait and see if someone else can help :/

**Comment by amrbashir** [comment]
Closing as this issue went stale with no more info, please reach out to us with more info if you still have the same issue.
