### ISSUE TITLE
[bug] bundler fails to unzip nsis installer libs for windows on macos

### ISSUE THREAD

**Issue by pashokitsme** [tauri-apps/tauri#7563]
### Describe the bug

tauri-cli fails to download & unzip NSIS installer libraries on macos.
Everything is alright if `~/Library/Caches/tauri/NSIS` directory with libs is on place.

```
 Downloading https://github.com/tauri-apps/binary-releases/releases/download/nsis-plugins-v0/NSIS-ApplicationID.zip
        Info extracting NSIS ApplicationID plugin
       Error failed to bundle project: `unsupported Zip archive: Compression method not supported`
```

### Reproduction

1. Minimal Tauri app (by `cargo tauri init`) or any else
2. Be sure there is no NSIS directory in `~/Library/Caches/tauri/`
3. Build app for `x86_64-pc-windows-msvc` target (`cargo tauri build --target x86_64-pc-windows-msvc`)
4. .exe will be built successfully; bundle fail

### Expected behavior

Bundle with nsis installer

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.71.0 (8ede3aae2 2023-07-12)
    ✔ Cargo: 1.71.0 (cfd3bbd8f 2023-06-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.5.0
    - npm: 9.8.0

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.10
    - tauri-build [RUST]: 2.0.0-alpha.6
    - wry [RUST]: 0.28.3
    - tao [RUST]: 0.19.1
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.10
```

### Stack trace

```text
No. Build log, crates compiling omitted:

        Finished release [optimized] target(s) in 1m 13s
        Warn Cross-platform compilation is experimental and does not support all features. Please use a matching host system for full compatibility.
        Warn ignoring msi
        Info Verifying NSIS package
 Downloading https://github.com/tauri-apps/binary-releases/releases/download/nsis-plugins-v0/NSIS-ApplicationID.zip
        Info extracting NSIS ApplicationID plugin
       Error failed to bundle project: `unsupported Zip archive: Compression method not supported`
```

### Additional context

I _guess_ it happens at:

1. [This](https://github.com/tauri-apps/tauri/blob/dev/tooling/bundler/src/bundle/windows/nsis.rs#L72) condition is satisfied - no nsis folder in `~/Library/Caches/tauri`
2. Download archive, try to extract and fail [here](https://github.com/tauri-apps/tauri/blob/dev/tooling/bundler/src/bundle/windows/util.rs#L111)

**Comment by FabianLars** [comment]
Thanks for the report, this was fixed here: https://github.com/tauri-apps/tauri/pull/7296 but not released yet so if you wanna use that you'll either have to use the [cli from git](https://tauri.app/v1/guides/faq#how-can-i-use-unpublished-tauri-changes) or download and unzip the archives [manually](https://github.com/tauri-apps/tauri/issues/7338#issuecomment-1663167373)
