### ISSUE TITLE
[feat] Can wix be replaced?

### ISSUE THREAD

**Issue by pan2za** [tauri-apps/tauri#7570]
### Describe the problem

Wix for windows installer is almost a big huge monster which made me very very  unhappy.
(1) use wix to install for the old style windows (e.g win7 ), need webview2.109 to be installed offline.
(2) use wix to install with other app ( vc_redist bundle) is almost impossible mission.

### Describe the solution you'd like

Remove wix from tauri installer
or
Get a substitute.
wix is a disaster for me.

**Comment by FabianLars** [comment]
There's already a NSIS based installer. We're not happy with WiX either so it's mostly in maintenance mode right now, not seeing any features. But we can't remove it since it's still basically a requirement for many corporate environments...

**Comment by pan2za** [comment]
OK.
Currently my solution is:
1) use wix to package tauri bundle
2) use nsis to package tauri bundle AND vc_redist!
OH!MY!
