### ISSUE TITLE
[bug] Encoded text cannot have a 6-bit remainder

### ISSUE THREAD

**Issue by psyycker** [tauri-apps/tauri#7575]
### Describe the bug

Ran the command `tauri signer generate` and got the following result:

```
> tauri signer generate

Please enter a password to protect the secret key.
Password: 
<empty>
Password (one more time): 
<empty>
Deriving a key from the password in order to encrypt the secret key... done

Your secret key was generated successfully - Keep it secret!
dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5T0RqR0FuaDE5T2h6UTBMQWkrQXJ6MllITDdxNWhYb0pOS1pPTU10aEk1SUFBQkFBQUFBQUFBQUFBQUlBQUFBQVNkaW1mK0Q2ZkxlMnhUa042VzhmODlMVlAxWm9MSXZyT2QvaVlqSStJVXVLZEs2dmdrWE9kTEFLTHhxNkVxWGVkL0NZVE1yaVJrVnBSL1ltTzA5ZC9Yc0RGRGI1YWwyZjhSN1FOUW5vbmk3UmtZdEJkdHVsU3JMenVkZXF1aTlxK3loWlhRTVloUzA9Cg==


Your public key was generated successfully:
dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IDRBNEQ2QUQ4OEJGQzUzNDkKUldSSlUveUwyR3BOU2dmTVB5bmw1K24rWWVCS0ZUMXlUNXlMaEhKZnpPY29ERnR3Q3VrWTVhamwK

Add the public key in your tauri.conf.json
---------------------------


Environment variables used to sign:
`TAURI_PRIVATE_KEY`  Path or String of your private key
`TAURI_KEY_PASSWORD`  Your private key password (optional)

ATTENTION: If you lose your private key OR password, you'll not be able to sign your update package and updates will not work.
---------------------------
```

Then copied the private key from the terminal and exported it.
Updated the public key as well.

But still getting the error: `Error Encoded text cannot have a 6-bit remainder.`

I've done the same operation 2 or 3 times, tried different ways to copying including using the command:
`npm run tauri signer generate -- -w ~/.tauri/myapp.key`

Then used ` cat ~/.tauri/prbuddy.key | pbcopy` to copy the key the way it is in the file but it doesn't work...

Weird thing to notice is that if I use the path of the private key instead, it works, but I need to store it as a secret on github action so this is not a viable solution

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.66.0 (69f9c33d7 2022-12-12)
    ✔ Cargo: 1.66.0 (d65d197ad 2022-11-15)
    ✔ rustup: 1.25.1 (bb60b1e89 2022-07-12)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 19.7.0
    - yarn: 1.22.19
    - npm: 9.7.2

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by psyycker** [comment]
Closing as this is not a bug but a misunderstanding from my side. I was putting the path of the public key instead of its content. The confusion was because unlike the TAURI_PRIVATE_KEY which can be a path or the content itself, the public key is only the content.

**Comment by ankitvermaAT** [comment]
@psyycker can you please help me out because I am having the same issue
while I had put environment variable value TAURI_PRIVATE_KEY and public key in tauri.config.json 
still getting the same error, Please help to fix this?

**Comment by ankitvermaAT** [comment]
Now I am getting another error during updater (**Verify signature error: UnexpectedKeyId**) if you have any idea about this error kindly suggest I am following below steps..

1. run : npm run tauri signer generate

2. Got public and private keys

3. Put public key in tauri.config.json (pubkey) node

4. Put private key in env file

5. run : npm run tauri build

6. Got update build (myapp_1.0.2_x64_en-US.msi.zip) and .mis.zip.sig files
Upload .mis.zip on server and update signature value in server json which is inside (.mis.zip.sig)

Now I have my old version build i.e. 1.0.1 run this app and got that error (**Verify signature error: UnexpectedKeyId**)

I had used below packages:

"dependencies": {
"@tauri-apps/api": "^1.5.2",
"axios": "^1.6.7",
"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-router-dom": "^6.22.1"
},
"devDependencies": {
"@tauri-apps/cli": "^1.5.8",
"@types/react": "^18.2.15",
"@types/react-dom": "^18.2.7",
"@vitejs/plugin-react": "^4.2.1",
"typescript": "^5.0.2",
"vite": "^5.0.0"
}
