### ISSUE TITLE
Install the app under /companyName/appName

### ISSUE THREAD

**Issue by AyalaGol** [tauri-apps/tauri#7603]
### Describe the bug

Hi, 

I want to install the tauri app in the program file folder under companyName/{appName}.
(by default it is installed under programFile/appName)
I tried to give a custom template of Wix and change there the INSTALLDIR without succeed.

what is the best way to do it?
any answer and example will be appreciated!

@FabianLars Can you take a look please?

![image](https://github.com/tauri-apps/tauri/assets/89450011/c56a430d-7069-4b9e-b396-982044723557)

thanks

### Platform and versions

```text
Version.
```

**Comment by FabianLars** [comment]
I didn't try it but changing this: https://github.com/tauri-apps/tauri/blob/964d81ff01a076516d323546c169b2ba8156e55a/tooling/bundler/src/bundle/windows/templates/main.wxs#L102 should actually be enough (from `{{product_name}}` to `{{manufacturer}}/{{product_name}}` or a hardcoded value). Again, didn't try it but i think that should be it.

Also, i'd love this to be configurable in tauri, also for the nsis bundle, in case of the latter maybe even `Programs/Manufacturer/Prodoct` if installed in `AppData/Local`

**Comment by AyalaGol** [comment]
This is what I do:
clone this file [tauri/tooling/bundler/src/bundle/windows/templates/main.wxs](https://github.com/tauri-apps/tauri/blob/964d81ff01a076516d323546c169b2ba8156e55a/tooling/bundler/src/bundle/windows/templates/main.wxs#L102) 
into my code, and in tauri.conf.json - point to this file from windows.wix.template.
I did the change you wrote - but get an exception when running tauri build:
   Error failed to bundle project: error running candle.exe.

**Comment by FabianLars** [comment]
can you run it with the --verbose flag like `yarn tauri build --verbose` or `npm run tauri build -- --verbose` (npm needs an extra `--`) so we see what's wrong?

**Comment by AyalaGol** [comment]
Sure, 
this is the issue:
error CNDL0027 : The Directory/@Name attribute's value, 'aa/bb', is not a valid long nam
e because it contains illegal characters.  Legal long names contain no more than 260 characters and must contain at least one non-period character.  Any character except for the follow
 may be used: \ ? | > < : / * ".

**Comment by AyalaGol** [comment]
Wix not like the slash in the name property:
![image](https://github.com/tauri-apps/tauri/assets/89450011/b4780480-adb9-4122-b9c8-b02038112015)

**Comment by AyalaGol** [comment]
but anyway it looked that this is not the correct property to change.
I change the name property to be `Name="{{manufacturer}}-{{product_name}}"`
and then the build succeeded, 
but , so strange - when I run the MSI file, I don't see my change in the destination folder dialog.
it show the original product name , without the manufacturer.

**Comment by apalacean-panaya** [comment]
For anyone who had the issue that the file destination doesn't change you have to remove these lines from main.wxs:

 
        <Property Id="INSTALLDIR">
            <RegistrySearch Id="PrevInstallDirReg" Root="HKCU" Key="Software\\{{manufacturer}}\\{{product_name}}" Name="InstallDir" Type="raw"/>
        </Property>
        
And also you have to add a new directory for the manufacturer:
```
         <Directory Id="FOLDERDIR" Name="{{manufacturer}}">
                    <Directory Id="INSTALLDIR" Name="{{product_name}}"/>
          </Directory>
```

**Comment by amrbashir** [comment]
Closing in favor of #7853
