### ISSUE TITLE
[bug] Crash on: Failed to unregister class Chrome_WidgetWin_0. Error = 0

### ISSUE THREAD

**Issue by pingvin12** [tauri-apps/tauri#7606]
### Describe the bug

Running a project with Tauri::state crashes with this error:
` [0814/131138.483:ERROR:window_impl.cc(119)] Failed to unregister class Chrome_WidgetWin_0. Error = 0`
The project I am using it in is [this](https://github.com/pingvin12/1Pass).

At the moment I am storing a connection pool inside tauri state, which non-deterministically crashes the project on start.

### Reproduction

1. Clone the [repository ](https://github.com/pingvin12/1Pass)
2. Set up the necessary configurations.
3. Run the project with the provided instructions.

### Expected behavior

The project should run without any crashes or errors related to Tauri::state and the connection pool.

### Platform and versions

```text
npm run tauri info

> onepass@0.1.0 tauri
> tauri info


[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 115.0.1901.203
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 19.6.0
    - yarn: 1.22.19
    - npm: 9.4.0

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../out
    - devPath: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Webpack
```

### Additional context

 It's important to note that this issue is not consistently reproducible, which suggests that the crash might be related to certain timing or resource allocation conditions.

**Comment by FabianLars** [comment]
Before looking at your project just a note: This error can be completely ignored. It's something chromium internal (we've seen the same error with normal browsers too) and it's not the _cause_ of the crash but a consequence of it.
Is this really the only console output you get?

**Comment by pingvin12** [comment]
`warning: the following packages contain code that will be rejected by a future version of Rust: nom v4.2.3`
This is the only console output I have that might be relevant.

**Comment by FabianLars** [comment]
Alrighty, i can't really get your project running on my machine, the other error you posted also doesn't matter so either there is no error, or there's _something_ hiding it (though that _should_ also hide the chrome error i guess).

One thing i'd suggest to try is to remove the `.manage()` call on the build and refactor your setup hook to something like this (typed on github so idk if it compiles):
```rs
.setup(|app| {
    let db_new_pool = Database::new_pool().unwrap();

    app.manage(AppState { db_manager: Mutex::new(Some(db_new_pool)) } );

    Ok(())
})
```
If that changes nothing, maybe pull that out of the setup hook in front of the builder
```rs
let db_new_pool = Database::new_pool().unwrap();
tauri::Builder::default()
    .manage(AppState { db_manager: Mutex::new(Some(db_new_pool)) })
    ...
```
Maybe that at least gives us an error idk, i still doubt this is the State's fault tbh.

If all that doesn't help i'd really appreciate a _minimal_ reproduction example though i'd imagine that this will be difficult to reproduce.

**Comment by pingvin12** [comment]
Tried both of these with no luck, I'll think I'll start from scratch. Thank you.

**Comment by stereobooster** [comment]
Also getting this error https://github.com/stereobooster/cyto-snap/actions/runs/6423527323/job/17442216245. Need to see if I can get more details

**Comment by jkelleyrtp** [comment]
We're getting this issue in our CI on Dioxus. Only happens on windows

https://github.com/DioxusLabs/dioxus/actions/runs/7433556917/job/20227277367?pr=1787

It would be nice if we could trap the error and not fail

**Comment by FabianLars** [comment]
Is it possible in that test to try closing the window manually before exiting? 

Also, i'd be really surprised if this actually caused the workflow to fail. iirc it doesn't even print to stderr but as a normal log to stdout, and it has a different error code than the reported 70 (0 which actually should mean success) 🤔 On the other hand, it's windows and chromium so it really shouldn't surprise me lol

**Comment by dededec** [comment]
Was a solution or cause for this found? I am having the same problem in windows, only that in my case it seems to be caused when invoking a tauri command that calls ffmpeg-next crate. My colleagues are not encountering it, and our configuration is the same :(

**Comment by FlippingBinary** [comment]
I know this is an old issue, but it came up in my search when I was trying to track down the source of the same error message. I'm writing this comment to anyone else who stumbles on it like I did. 

In my case, it was just a nuisance message that appeared when closing my app. Excluding the leading timestamp, the message was `ERROR:ui\gfx\win\window_impl.cc:124] Failed to unregister class Chrome_WidgetWin_0. Error = 1412`. Fixing it was as easy as explicitly closing the window before calling exit.

Here's an example:

```rust
if let Some(window) = app_handle.get_webview_window("main") {
    if let Err(err) = window.close() {
        log::warn!("Tried and failed to close the window before exiting: {}", err);
    }
}
app_handle.exit(0);
```

**Comment by rmorse** [comment]
I had to use `window.destroy()` instead of `window.close()`

**Comment by Legend-Master** [comment]
Seems like an error from https://source.chromium.org/chromium/chromium/src/+/main:ui/gfx/win/window_impl.cc;drc=6977efa0c1fe30e0dc2c44e4beccd8376340d3f6;l=119 when the app process (the one tauri runs on) exits, whether it's exiting from main or through `std::process::exit(0)`

There's an old issue (marked Obsolete) about it https://issues.chromium.org/issues/40720563
