### ISSUE TITLE
Tauri Frontend Sending Incorrect Encoding Info to Backend [bug] 

### ISSUE THREAD

**Issue by pingvin12** [tauri-apps/tauri#7607]
### Describe the bug

When communicating between the Tauri frontend and the backend, I observed an issue where the frontend seems to be sending extra encoding information along with the data. For instance, instead of sending just the string "fe," it appears to be transmitting a longer sequence: "fe\xab\xab\xab\xab\xab\xab\xab\xab\xab\xab\xab\xab\xab\xab\xab\xab\xee\xfe\xee\xfe\xee\xfe\xee\xfe\xee\xfe\xee\xfe\xee\xfe."

### Reproduction

1.     Set up the provided [repository](https://github.com/pingvin12/1Pass).
2.     Start the project with the provided info.
3.     Observe the transmitted data on the backend.

### Expected behavior

The frontend should transmit only the intended data without any additional or unexpected encoding information.

### Platform and versions

```text
npm run tauri info

> onepass@0.1.0 tauri
> tauri info


[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 115.0.1901.203
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 19.6.0
    - yarn: 1.22.19
    - npm: 9.4.0

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../out
    - devPath: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Webpack
```

### Additional context

This behavior is consistent across multiple communication attempts. It's important to note that the data appears to be inappropriately extended with these extra encoding bytes.

**Comment by FabianLars** [comment]
As said in the other issue, i can't seem to get your project running, so do you think you can create a minimal reproduction example for this? tbh i don't think this is actually an issue with tauri so i'd imagine working on that could already show you the issue 🤔

**Comment by pingvin12** [comment]
It appears that reproducing this issue is challenging, and it seems to be much more of an issue with diesel than tauri, making it less relevant. Considering the circumstances, I'm leaning towards a rebuild from scratch. Anyway, Thank you for reaching out.
