### ISSUE TITLE
[docs] 应用自启动

### ISSUE THREAD

**Issue by SKY-PiaoYiZhe** [tauri-apps/tauri#7608]
系统：window10
如何添加window系统的自启动，在登录后自动启动应用。
How to add a self start for the window system and automatically start the application after logging in.

**Comment by FabianLars** [comment]
We have a plugin for that: https://github.com/tauri-apps/plugins-workspace/tree/v1/plugins/autostart - the readme instructions really cover everything it offers since it's a fairly small plugin but we'll integrate it into the docs as soon as we can.
