### ISSUE TITLE
[bug] Info.plist modification in `out` dir causes Cargo to rebuild every time

### ISSUE THREAD

**Issue by irh** [tauri-apps/tauri#7614]
### Describe the bug

On macOS, every time I run `tauri dev` Cargo has to rebuild the application even when no source files have been touched. 

Running `cargo build -v` shows that the `target/debug/build/[my-app]/out/Info.plist` file has changed since the last build, requiring a rebuild of the app.

This happens with my 1.4-based app, but also on the latest `dev` with the `helloworld` example.

### Reproduction

- On macOS, in the Tauri repo, run `cargo run --example helloworld`
- Close the app, and run `cargo build --example -v`
- Observe that Cargo classifies the `Info.plist` file as `Dirty`, causing a recompilation of the main app binary.

### Expected behavior

If no source files have been touched, then it would be great if Cargo wouldn't have to recompile the app.

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.5.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.71.0 (8ede3aae2 2023-07-12)
    ✔ Cargo: 1.71.0 (cfd3bbd8f 2023-06-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 16.15.0
    - pnpm: 8.6.11
    - yarn: 1.22.19
    - npm: 8.10.0

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.1
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../build
    - devPath: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

**Comment by olexiyb** [comment]
I tracked down to invalid logic in https://github.com/tauri-apps/tauri/blob/1a984a41e7207c616e03b8032431c21176af6379/core/tauri-codegen/src/context.rs
```
let format =
        time::format_description::parse("[year][month][day].[hour][minute][second]").unwrap();
      if let Ok(build_number) = time::OffsetDateTime::now_utc().format(&format) {
        plist.insert("CFBundleVersion".into(), build_number.into());
      }
```
According to https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion
```
This key is a machine-readable string composed of one to three period-separated integers, such as 10.14.1. The string can only contain numeric characters (0-9) and periods.
...
You can include more integers but the system ignores them.
```
 I believe this field should just have the version from `tauri.conf.json`
