### ISSUE TITLE
[bug] [TAURI] Couldn't find callback id xxx in window

### ISSUE THREAD

**Issue by letrungdo** [tauri-apps/tauri#7617]
### Describe the bug

Error message appears in the console.
`[TAURI] Couldn't find callback id 3189022244 in window. This happens when the app is reloaded while Rust is running an asynchronous operation.`
When an error occurs, sometimes listeners (import { listen } from "@tauri-apps/api/event") will lose connection and can't listen anymore.

### Reproduction

Press Ctrl + R or right click and select reload option

### Platform and versions

```text
- OS: Mac OS 13.5.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.67.0 (fc594f156 2023-01-24)
    ✔ Cargo: 1.67.0 (8ecd4f20a 2023-01-10)
    ✔ rustup: 1.25.1 (bb60b1e89 2022-07-12)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.13.0
    - pnpm: 7.15.0
    - yarn: 1.22.19
    - npm: 8.19.3
```

**Comment by MichaelTendoSsemwanga** [comment]
I'm facing this while using 
https://github.com/tauri-apps/tauri-plugin-websocket
and Svelte
I have tried to ensure websocket is disconnected in 
- Svelte's onDestroy, 
- in callback return in onMount

I can't get rid of it

**Comment by juanibiapina** [comment]
I think I'm facing a similar issue while registering a global shortcut.

**Comment by rtmotiondev** [comment]
I think I'm facing the same issue. #9613

**Comment by rtmotiondev** [comment]
@letrungdo Why did you mark this issue as completed? What have you done to solve the problem?
