### ISSUE TITLE
Sveltekit cannot prerender pages with actions

### ISSUE THREAD

**Issue by denisdpc** [tauri-apps/tauri#7628]
### Describe the bug

Using SvelteKit I received the the error message: "Error: Cannot prerender pages with actions" when I tried to use form actions. This problem can be reproduced using the code bellow for "src/+page.svelte" and "src/+page.server.js":

**+page.svelte**
```
<script>
  export let form;
</script>

<form method="POST">
  <input name="email"/>
  <button type="submit">Submit</button>
</form>

{ form?.success }
```

**+page.server.js**
```
export const actions = {
    default: async ({ request }) => {
      const formData = await request.formData();
      const email = formData.get('email');
      return { success: true };
    },
  };
```

### Platform and versions

```text
[✔] Environment
    - OS: Fedora 37.0.0 X64
    ✔ webkit2gtk-4.0: 2.40.3
    ✔ rsvg2: 2.54.5
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.16.1
    - yarn: 1.22.19
    - npm: 8.13.1

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.3.1 (outdated, latest: 1.4.0)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../build
    - devPath: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

**Comment by FabianLars** [comment]
server actions require a sveltekit server at runtime and can't be prerendered, so it's not a bug but an expected error. There's really nothing we can do here on the tauri side. You'll either have to stop using apis that require a server (like actions), or bundle a nodejs binary that'd host your frontend on the user's system (the latter is obviously not recommended unless absolutely necessary).
