### ISSUE TITLE
[docs] works-with-clojurescript

### ISSUE THREAD

**Issue by kwrooijen** [tauri-apps/tauri#763]
There are a few `works-with-*` topics, one that's missing is Clojurescript (specifically https://github.com/kwrooijen/tauri-cljs).
Would be nice to include it as well.

![image](https://user-images.githubusercontent.com/629436/86936886-e017a300-c13e-11ea-8553-61d076f23a56.png)

**Comment by nothingismagick** [comment]
thanks for the headsup!
