### ISSUE TITLE
[bug] NSIS cannot be installed: xxx is running! Click OK to kill it

### ISSUE THREAD

**Issue by wyhaya** [tauri-apps/tauri#7637]
### Describe the bug

![123](https://github.com/tauri-apps/tauri/assets/23690145/c7b20b75-748f-44e8-90d6-dacb96f6fe9f)

### Reproduction

1. Open any tauri app project.
2. Rename `tauri.conf.json -> package -> productName` to `hello`.
3. Build Tauri app (nsis).
4. Rename `src-tauri\target\release\bundle\nsis\hello_0.0.0_×64-setup.exe` to `hello.exe`.
5. Open `hello.exe`, You will see this error.

### Expected behavior

Installs fine no matter what the filename is

### Platform and versions

```text
All are up to date.
```

### Additional context

This error occurs whenever `tauri.conf.json -> package -> productName` is the same as `productName`.exe

**Comment by amrbashir** [comment]
Should be fixed in the next release.
