### ISSUE TITLE
[bug] Cannot open file using right click open with

### ISSUE THREAD

**Issue by hasen6** [tauri-apps/tauri#7655]
### Describe the bug

I just created a brand new tauri app to read comics and it can open a cbz comic by clicking a button to 'choose file', selecting the file and opening it, but if I right click on the file in the finder and select 'open with' and choose my app then it tries to open but fails with error: 'cannot open file in comic book archive format'. Very odd since evidently it can open cbz files and in fact it's the exact same file that I'm opening with each method.

I added this line to the main.rs to check the file name passed was correct and it was:

`println!("process.argv: {:?}", std::env::args().collect::<Vec<String>>());`

This is the entire app.jsx code at the moment and is the only file modified beyond the default project:

```
import { useState } from "react";
import JSZip from "jszip";
import "./App.css";

function App() {
  const [images, setImages] = useState([]);
  const [currentPage, setCurrentPage] = useState(0);

  async function handleFileChange(event) {
    const file = event.target.files[0];
    if (file) {
      const zip = new JSZip();
      const contents = await zip.loadAsync(file);
      const imageFiles = Object.values(contents.files).filter((file) =>
        /\.(png|jpe?g|gif)$/i.test(file.name)
      );
      const images = await Promise.all(
        imageFiles.map(async (file) => {
          const blob = await file.async("blob");
          return URL.createObjectURL(blob);
        })
      );
      setImages(images);
    }
  }

  function handleKeyDown(event) {
    if (event.key === "ArrowLeft") {
      setCurrentPage((page) => Math.max(0, page - 1));
    } else if (event.key === "ArrowRight") {
      setCurrentPage((page) => Math.min(images.length - 1, page + 1));
    }
  }

  return (
    <div className="container" tabIndex={0} onKeyDown={handleKeyDown}>
      <h1>Comic Reader</h1>
      <input type="file" onChange={handleFileChange} />
      {images.length > 0 && <img src={images[currentPage]} alt="Comic Page" />}
    </div>
  );
}

export default App;
```

### Reproduction

1. click choose file button
2. select cbz comic
3. opens no problem

1. find cbz file in finder
2. right click and select 'open with' and select this app
3. comic fails to open with error 'cannot open file in comic book archive format'

### Expected behavior

It should open the file no problem with either method since it clearly can actually open the file.

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 12.6.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.71.1 (eb26296b5 2023-08-03)
    ✔ Cargo: 1.71.1 (7f1d04c00 2023-07-29)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 18.17.1
    - pnpm: 8.6.12
    - npm: 9.6.7

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by amrbashir** [comment]
I think macOS needs to be informed somehow that the application supports this file and so I will close this since file association will be available in v2.
