### ISSUE TITLE
[bug] IPC doesn't work in ^2.0.0-alpha.11

### ISSUE THREAD

**Issue by bpevs** [tauri-apps/tauri#7656]
### Describe the bug

Per [Discord chat](https://discord.com/channels/616186924390023171/1141037549549256835)...

After upgrading from `next` to ^2.0.0-alpha.11, all IPC calls starting responding to client as 400 on macOS and Android:

<img width="615" alt="Screenshot 2023-08-19 at 21 35 28" src="https://github.com/tauri-apps/tauri/assets/8182843/ce318e22-e580-4425-bed3-e96a643672ec">

This is also happening on dev branch. I referenced a local copy of tauri, and did a git bisect, and it looks like this is first commit where this error occurs:
https://github.com/tauri-apps/tauri/commit/fbeb5b9185baeda19e865228179e3e44c165f1d9

### Reproduction

made a branch here:
https://github.com/bpevs/tauri_deno_mobile_sample/tree/ipc-error-repro

You can ignore references to Deno in this branch; I committed the built files and modified the references, so it should work as a vanilla js project without a build step.

More detailed readme in that file explains repro steps, but basically, adding any invoke/ipc call or the like should throw the pictured error.  For example:

```ts
import { arch } from '@tauri-apps/api/os';
(function() {
  const archName = await arch(); // expect 400
})()
```

### Expected behavior

For the example repo, I expect the `invoke` to run, and replace the shown text with a greeting.  It does not show a greeting when running tauri off of the dev branch, because the invoke fails and responds with the pictured 400 error.

The linked repo DOES work correctly when running off the `next` branch, or when locally referencing the last good commit: 85efd0ae436e0a2556f20c53a7a0a49ef7a1d31b

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.4.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.11
    - tauri-build [RUST]: 2.0.0-alpha.8
    - wry [RUST]: 0.31.1
    - tao [RUST]: 0.22.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.11

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../src-www
    - devPath: ../src-www
```

**Comment by nikoPLP** [comment]
From my experience, this happens when you are still using the older version of the JS packages.
Can you check that your frontend uses 
`"@tauri-apps/api": "2.0.0-alpha.6"`
and that any plugin you use is also to their latest published version?

**Comment by bpevs** [comment]
yuuuuuuup that's what it was 🫣
 I didn't specify version (intending to be "latest"), but forgot that would be latest stable, not latest alpha.  

Thanks for the tip!
