### ISSUE TITLE
[bug] Routing doesn't work in release build with Nuxt

### ISSUE THREAD

**Issue by MidKnightXI** [tauri-apps/tauri#7661]
### Describe the bug

I'm trying to use a release build I made with tauri. Everything compiles properly BUT routing doesn't work whereas in development mode it's working just fine.

### Reproduction

- Create an app with tauri and nuxt 3 and use many pages to test routing
- Try to build your app as release build
- Fail to use routing

### Expected behavior

Routing should work in dev and release build

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.5.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.71.1 (eb26296b5 2023-08-03)
    ✔ Cargo: 1.71.1 (7f1d04c00 2023-07-29)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.5.1
    - yarn: 1.22.19
    - npm: 9.8.1

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../.output/public
    - devPath: http://localhost:3000/
    - framework: React
    - bundler: Vite
```

**Comment by simonhyll** [comment]
Are you sure you're using `Nuxt` and not `Next.js`? Because `framework: React` and `bundler: Vite` suggests it's not Nuxt.

Routing works with both Nuxt and Next in both development and production mode. There must be something misconfigured in your frontend.

**Comment by MidKnightXI** [comment]
Yes I'm using Nuxt I was also confused why it was displaying react
