### ISSUE TITLE
[docs] `WINDOW_CREATED` not works while `tauri://created` works as expected, what's difference between them?

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [tauri-apps/tauri#7663]
I found the `TauriEvent.WINDOW_CREATED` enum at the [event document](https://tauri.app/zh-cn/v1/api/js/event#event.TauriEvent.WINDOW_CREATED), but it not works when I used it to listen the new window created.
While at the [window document](https://tauri.app/zh-cn/v1/api/js/window/#window-events), it shows  to use `tauri://created` directly to listen the window created, I tried it works as expected, so what's difference between them?
In addition, the document shows we should use `tauri://error` to listen the window create failed, it seems no such event in the `TauriEvent` enum.

**Comment by amrbashir** [comment]
So `tauri://created` is fired when the window is created on the JS side, so you can know when you can be sure the window is created and can safely use the window methods, same for `tauri://error` and it is only fired on the window.

`TauriEvent.WINDOW_CREATED` however is a global event that is fired whenever a new window is created, not sure how did you use it and why it not works for you, so please do provide a reproduction or something.

**Comment by zhengxiaoyao0716** [comment]
> So `tauri://created` is fired when the window is created on the JS side, so you can know when you can be sure the window is created and can safely use the window methods, same for `tauri://error` and it is only fired on the window.
> 
> `TauriEvent.WINDOW_CREATED` however is a global event that is fired whenever a new window is created, not sure how did you use it and why it not works for you, so please do provide a reproduction or something.

Thanks, I didn't realize that `WINDOW_CREATED` is a global event, the docs didn't indicate this, so I tried listening to it on the newly created window object, which should be why `WINDOW_CREATED` not worked.

**Comment by amrbashir** [comment]
Yeah we need to enhance the doocs around this, thanks for your feedback.
