### ISSUE TITLE
[bug] `minimize` would trigger the `onMoved` and `onResized` events while `maximized` not.

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [tauri-apps/tauri#7664]
### Describe the bug

I used `onMoved` and `onResize` event to listen the window size change on the JS-side.
When the window minimized, both the `onMoved` and `onResized` events would be triggered, while the `maximize` would not.

### Reproduction

It's probably not a deep problem, and I would be happy to provide an example if it's really needed.

### Expected behavior

The `minimize` and the `maximize` operation should behave the same, and since we have no specialized events such as `onMinimized` and `onMaximized`, I think they should both trigger the `onResize` event.

### Platform and versions

```text
PS E:\MyProject\Game\TSBM> pnpm tauri info  

[✔] Environment
    - OS: Windows 10.0.23526 X64
    ✔ WebView2: 115.0.1901.203
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.71.1 (eb26296b5 2023-08-03)
    ✔ Cargo: 1.71.1 (7f1d04c00 2023-07-29)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.12.1
    - pnpm: 7.19.0
    - npm: 8.19.2

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:5173/
    - framework: React
    - bundler: Vite
```

### Additional context

Hey I think the `tauri info` is awesome, is there any
 way to use it in application? This will benefit all downstream tauri developers and users!

**Comment by amrbashir** [comment]
Could you provide an example? like are you using the native maximize button or a customized one? How/When are you listening to the event.

**Comment by zhengxiaoyao0716** [comment]
native maximize button.

``` typescript
    const handler = async () => {
      if (await appWindow.isMinimized()) {
          ...
      }
      if (await appWindow.isMaximized()) {
          ...
      }
    }
    await appWindow.onMoved(handler)
    await appWindow.onResized(handler)
```

**Comment by amrbashir** [comment]
The above snippet works fine on my Windows, please provide a minimal repro if you still face the issue.

**Comment by zhengxiaoyao0716** [comment]
I'm sorry that I tried again and found it worked, this may be a misunderstanding.
