### ISSUE TITLE
[bug] visible config doesn't work

### ISSUE THREAD

**Issue by thewh1teagle** [tauri-apps/tauri#7669]
### Describe the bug

I created app using `tauri` with `react`
to avoid the initial white blank screen, I set the app to `visible: false` in `tauri.ocnfig.json`
and in react I `invoke` command which open the window and set it to `visible`

The issue is that although I set `visible` to false in the config file, 
the window it still open for few moments and then closing when the app starts.

You can see the whole repo [here](https://github.com/thewh1teagle/happy)
[tauri.config.json](https://github.com/thewh1teagle/happy/blob/main/rust/src-tauri/tauri.conf.json#L44)
[main.rs](https://github.com/thewh1teagle/happy/blob/main/rust/src-tauri/src/main.rs)

### Reproduction

Download the latest release from [here](https://github.com/thewh1teagle/happy/releases/tag/1.0.2)
Open the app and you will see that it opens laggy when it starts, because it opens for half a second and immediately close, before it should open at all.

### Expected behavior

The app should not open at all when I set `visible` to false in the config, and it will open only after I tell it to open from `react` using `invoke`

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 115.0.1901.203
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.71.0 (8ede3aae2 2023-07-12)
    ✔ Cargo: 1.71.0 (cfd3bbd8f 2023-06-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.17.1
    - npm: 9.6.7

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Additional context

By the way, currenly I set `decorations` to `false` so at least it doesn't opens with the `topbar` so it's less noticeable

**Comment by gknapp** [comment]
I'm also see a 'tao window' appear, despite setting `.visible(false)`:

```rust
    .setup(|app| {
      #[cfg(debug_assertions)]
      {
        app.get_window("main").unwrap().open_devtools();
      }

      let hidden = tauri::WindowBuilder::new(
        app, "hidden", tauri::WindowUrl::App("hidden.html".into())
      )
      .visible(false)
      .build()?;
      // hidden.open_devtools();

      Ok(())
    })
```

**Comment by thewh1teagle** [comment]
I solved it. 
the real problem is - if you choose `hidden: true` along with `maximized: true` on `window` config in `config.tauri.json`,
the window isn't hidden in the startup of the application because of the `minimized` option ,
I solved it by removing the `minimized` from the config, and manually send command from frontend when the app starts to maximize the window and make it visible.

**Comment by gknapp** [comment]
I commented out my .setup() code and added this config section for a second window. What did I do wrong here? I've getting a panic on build.

```json
    "windows": [
      {
        "fullscreen": false,
        "height": 600,
        "resizable": true,
        "title": "main",
        "width": 800
      },
      {
        "fullscreen": false,
        "height": 200,
        "resizable": false,
        "title": "hidden",
        "visible": false,
        "width": 800
      }
    ]
```

I also tried setting other attributes on the window before commenting out my `.setup()` code, adding `.maximized(true)` and `.decorations(false)`. I noticed the window flashed to maximized before being restore to 800 x 600, not sure if that means something is running after `.build()?;` and overriding attributes set in code beforehand.

**Comment by thewh1teagle** [comment]
@gabcoh 
Just use my existing solution
See here:
https://github.com/thewh1teagle/happy/blob/main/rust/src-tauri/src/main.rs#L26

https://github.com/thewh1teagle/happy/blob/main/rust/src-tauri/tauri.conf.json

https://github.com/thewh1teagle/happy/blob/main/rust/src/App.tsx#L45

**Comment by gknapp** [comment]
Thanks for linking your source. My app requires a second hidden window, I'll try triggering the window creation from the JS side via invoking a command fn as you have done.

**Comment by thewh1teagle** [comment]
@gknapp 
This will solve you two problems:
- Flashing window when starting
- White screen when starting until the frontend loads

**Comment by gknapp** [comment]
I believe that's worked, I'm still confirming as when `.visible(false)`, dev tools are not opened for the second window. I'm about to send an IPC message from the hidden to the main and verify.

I thought I'd add that I have this tauri plugin in my .toml config that is probably interfering with window attributes on start-up:
`tauri-plugin-window-state`

**Update:** went with a web worker instead of a separate window in the end, to offload some heavier processing.

**Comment by HKalbasi** [comment]
I'm hitting a similar problem in dioxus, in which `wry::webview::WebViewBuilder::with_visible` seems to have no effect. Here is the full code from dioxus:
```Rust
pub fn build(
    cfg: &mut Config,
    event_loop: &EventLoopWindowTarget<UserWindowEvent>,
    proxy: EventLoopProxy<UserWindowEvent>,
) -> (WebView, WebContext) {
    let builder = cfg.window.clone();
    let window = builder.build(event_loop).unwrap();
    let file_handler = cfg.file_drop_handler.take();
    let custom_head = cfg.custom_head.clone();
    let index_file = cfg.custom_index.clone();
    let root_name = cfg.root_name.clone();

    // We assume that if the icon is None in cfg, then the user just didnt set it
    if cfg.window.window.window_icon.is_none() {
        window.set_window_icon(Some(
            tao::window::Icon::from_rgba(
                include_bytes!("./assets/default_icon.bin").to_vec(),
                460,
                460,
            )
            .expect("image parse failed"),
        ));
    }

    let mut web_context = WebContext::new(cfg.data_dir.clone());

    let mut webview = WebViewBuilder::new(window)
        .unwrap()
        .with_transparent(cfg.window.window.transparent)
        .with_url("dioxus://index.html/")
        .unwrap()
        .with_ipc_handler(move |window: &Window, payload: String| {
            // defer the event to the main thread
            if let Ok(message) = serde_json::from_str(&payload) {
                _ = proxy.send_event(UserWindowEvent(EventData::Ipc(message), window.id()));
            }
        })
        .with_custom_protocol(String::from("dioxus"), move |r| {
            protocol::desktop_handler(r, custom_head.clone(), index_file.clone(), &root_name)
        })
        .with_file_drop_handler(move |window, evet| {
            file_handler
                .as_ref()
                .map(|handler| handler(window, evet))
                .unwrap_or_default()
        })
        .with_web_context(&mut web_context);

    #[cfg(windows)]
    {
        // Windows has a platform specific settings to disable the browser shortcut keys
        use wry::webview::WebViewBuilderExtWindows;
        webview = webview.with_browser_accelerator_keys(false);
    }

    if let Some(color) = cfg.background_color {
        webview = webview.with_background_color(color);
    }

    // These are commented out because wry is currently broken in wry
    // let mut web_context = WebContext::new(cfg.data_dir.clone());
    // .with_web_context(&mut web_context);

    for (name, handler) in cfg.protocols.drain(..) {
        webview = webview.with_custom_protocol(name, handler)
    }

    if cfg.disable_context_menu {
        // in release mode, we don't want to show the dev tool or reload menus
        webview = webview.with_initialization_script(
            r#"
                        if (document.addEventListener) {
                        document.addEventListener('contextmenu', function(e) {
                            e.preventDefault();
                        }, false);
                        } else {
                        document.attachEvent('oncontextmenu', function() {
                            window.event.returnValue = false;
                        });
                        }
                    "#,
        )
    } else {
        // in debug, we are okay with the reload menu showing and dev tool
        webview = webview.with_devtools(true);
    }

    (webview.with_visible(false).build().unwrap(), web_context)
                      // ^^^^ this doesn't do anything
}
```

**Comment by amrbashir** [comment]
@HKalbasi that should be fixed in the next release of wry

**Comment by amrbashir** [comment]
This should be fixed by now, let me know if the issue still exists

**Comment by mitkury** [comment]
Turns out, if the tauri-plugin-window-state plugin (v0.1.1) is present, it opens a hidden window.

**Comment by cck190891** [comment]
I encountered the same issue. When using `tauri-plugin-window-state = "2.0.0-rc"`, it causes the default hidden window to be opened. In the `.window-state.json`, I can see that it is set to `"visible": true`.
