### ISSUE TITLE
[bug] tauri@next not starting out-of-the-box

### ISSUE THREAD

**Issue by dtanzer** [tauri-apps/tauri#7670]
### Describe the bug

When I create a new tauri project with `npm create tauri-app@next` and then want to start the app, it does not start because it cannot connect to port 7000:

```
  ➜  Local:   http://localhost:1420/
  ➜  Network: use --host to expose
        Warn Waiting for your frontend dev server to start on http://localhost:7000/...
```

When I change the line

```
    "devPath": "http://localhost:7000",
```

in `src-tauri/tauri.conf.json` to:

```
    "devPath": "http://localhost:1420",
```

the app starts.

### Reproduction

* Create a new tauri 2.0 project with `npm create tauri-app@next`
* Select "npm" and "react-ts"
* Run the app with `npm run tauri dev`

...Or check out the repository [dtanzer/tauri-reproduction-example](https://github.com/dtanzer/tauri-reproduction-example) at commit [a26762e03747b2e4a7775fb37d0c035e51f2ae1b](https://github.com/dtanzer/tauri-reproduction-example/commit/a26762e03747b2e4a7775fb37d0c035e51f2ae1b) and run `npm run tauri dev` there.

### Expected behavior

The app should start out-of-the-box, with the configuration provided by the CLI.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 115.0.1901.203
    ✔ MSVC: Visual Studio Build Tools 2017
    ✔ rustc: 1.71.0 (8ede3aae2 2023-07-12)
    ✔ Cargo: 1.71.0 (cfd3bbd8f 2023-06-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.5.0
    - npm: 9.8.0

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by dtanzer** [comment]
Also: This is a fresh project I created with `npm create tauri-app@next`, but it still has the tauri-1.0 dependencies. Is this expected?

**Comment by FabianLars** [comment]
CTA currently has no maintained @next version. I think you're looking for @latest with the --alpha flag if you want to try v2
