### ISSUE TITLE
[bug] tauri dev  to launch the project white window and black window 

### ISSUE THREAD

**Issue by 1942847253** [tauri-apps/tauri#7672]
### Describe the bug

I used tauri dev to launch the project, and when the app launched it only showed a white window, which changed to a black window when I clicked full screen

### Expected behavior

I created this demo, but I couldn't run it with the official document

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22000 X64
    ✔ WebView2: 115.0.1901.203
    ✔ MSVC: Visual Studio ���ɹ��� 2022
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 16.15.1
    - pnpm: 8.6.1
    - yarn: 1.22.19
    - npm: 8.11.0

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.3.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by 1942847253** [comment]
![image](https://github.com/tauri-apps/tauri/assets/78800719/68997454-f007-4ada-942b-249e19e79695)
![image](https://github.com/tauri-apps/tauri/assets/78800719/9dff44ed-c5f7-4051-88b3-10ee6a7bb193)
![image](https://github.com/tauri-apps/tauri/assets/78800719/c0452ef8-96eb-45a7-8441-8288f791c429)

**Comment by amrbashir** [comment]
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) and fill the appropriate information fields to reopen the issue. Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by Ryu2u** [comment]
i have the same problem,when i run the app, it only show the white screen and when i resize the window it shows the black screen,close button don't work

**Comment by amrbashir** [comment]
Make sure to update the webview2 runtime in your system and use latest tauri versions, if still doesn't work please provide a minimal repro

**Comment by Mapotato-Ma** [comment]
@Ryu2u Hello, have your problem solved? Can you explain how to solve it?

**Comment by Ryu2u** [comment]
> @Ryu2u Hello, have your problem solved? Can you explain how to solve it?

if you use windows，Change the compatibility of the exe program to Windows 8.

**Comment by Mapotato-Ma** [comment]
> > [@Ryu2u](https://github.com/Ryu2u) Hello, have your problem solved? Can you explain how to solve it?
> 
> if you use windows，Change the compatibility of the exe program to Windows 8.

The problem did resolve after I changed it, but does it have to be changed this way? Can it be solved by project configuration?

**Comment by Ryu2u** [comment]
> > > [@Ryu2u](https://github.com/Ryu2u) Hello, have your problem solved? Can you explain how to solve it?
> > 
> > if you use windows，Change the compatibility of the exe program to Windows 8.
> 
> The problem did resolve after I changed it, but does it have to be changed this way? Can it be solved by project configuration?

Maybe you could modify the compatibility of WebView2 to Windows 8.

**Comment by Mapotato-Ma** [comment]
> > > > [@Ryu2u](https://github.com/Ryu2u) Hello, have your problem solved? Can you explain how to solve it?
> > > 
> > > 
> > > if you use windows，Change the compatibility of the exe program to Windows 8.
> > 
> > 
> > The problem did resolve after I changed it, but does it have to be changed this way? Can it be solved by project configuration?
> 
> Maybe you could modify the compatibility of WebView2 to Windows 8.

要装什么插件吗？还是说在哪个地方有配置，官网找半天也没找到哈哈哈

**Comment by Ryu2u** [comment]
> > > > > [@Ryu2u](https://github.com/Ryu2u) Hello, have your problem solved? Can you explain how to solve it?
> > > > 
> > > > 
> > > > if you use windows，Change the compatibility of the exe program to Windows 8.
> > > 
> > > 
> > > The problem did resolve after I changed it, but does it have to be changed this way? Can it be solved by project configuration?
> > 
> > Maybe you could modify the compatibility of WebView2 to Windows 8.
> 
> 要装什么插件吗？还是说在哪个地方有配置，官网找半天也没找到哈哈哈

不知道啊，改兼容性还是我试出来的

**Comment by Mapotato-Ma** [comment]
> > > > > > [@Ryu2u](https://github.com/Ryu2u) Hello, have your problem solved? Can you explain how to solve it?
> > > > > 
> > > > > 
> > > > > if you use windows，Change the compatibility of the exe program to Windows 8.
> > > > 
> > > > 
> > > > The problem did resolve after I changed it, but does it have to be changed this way? Can it be solved by project configuration?
> > > 
> > > 
> > > Maybe you could modify the compatibility of WebView2 to Windows 8.
> > 
> > 
> > 要装什么插件吗？还是说在哪个地方有配置，官网找半天也没找到哈哈哈
> 
> 不知道啊，改兼容性还是我试出来的

牛的，这也太坑了。。。
