### ISSUE TITLE
Not able to auto-update Tauri app[bug] 

### ISSUE THREAD

**Issue by sagarpadia17** [tauri-apps/tauri#7680]
### Describe the bug

Hello while making tauri auto update I am generating signature key when i am decoding it it is giving the same name of the as i am putting in the github but still when i try to update it it gives invalid signature error can anyone tell me what should i do with that.

### Platform and versions

```text
OS: Windows 10.0.19045 X64
    ✔ WebView2: 115.0.1901.200
    ✔ MSVC: Visual Studio Build Tools 2019
    ✔ rustc: 1.71.1 (eb26296b5 2023-08-03)
    ✔ Cargo: 1.71.1 (7f1d04c00 2023-07-29)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 16.18.0
    - yarn: 1.22.19
    - npm: 9.8.1

Packages
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0
```

**Comment by FabianLars** [comment]
Are you still facing this issue? I saw that you updated your app repo a few times since you created this issue. If yes, could you share the update config of your tauri.conf.json file? Maybe that error is more of a false positive 🤔

**Comment by sagarpadia7** [comment]
> Are you still facing this issue? I saw that you updated your app repo a few times since you created this issue. If yes, could you share the update config of your tauri.conf.json file? Maybe that error is more of a false positive 🤔

I got the solution for that as i when i was trying to get that signature from the github it was taking as blob but then i change it to raw then i get the solution for that

**Comment by sagarpadia17** [comment]
I got it. It was in the problem of URL of the updater.json but it was showing invalid signature so i was trying to change signature but nothing was happening. In URL I was not taking the raw part of URL thats why it was showing error btw Thanks for the reply:)

> Are you still facing this issue? I saw that you updated your app repo a few times since you created this issue. If yes, could you share the update config of your tauri.conf.json file? Maybe that error is more of a false positive 🤔
