### ISSUE TITLE
[bug] Tauri spawn multiple windows without such demand while fire process from Python

### ISSUE THREAD

**Issue by kotekpsotek** [tauri-apps/tauri#7681]
### Describe the bug

In advance: Thanks for put you into my issue ❤️

# Description

I'm using **tauri** with **py3** crate to execute python code. Python code usage is to perform some tasks using for this Process class from multiprocessing module which behave is spawning new processes. The problem is about that processes spawned from python are recogniezed by tauri as it's own WebView processes (In my opinion after read text: https://tauri.app/v1/references/architecture/process-model/#the-core-process) what cause to spawn multiple subsequent tauri windows (in infinite loop model where each spawned by Python process is treat as tauri new window) what cause to corrupt application usage and finally in some cases to crash tauri app (after spawn multiple window like 10-15). I tired to initialized Python from: ``.setup`` and ``.on_page_load`` **tauri application Builder methods** the difference exists but isn't what i need. 

## Difference between python code ignite places:
To describe differences between two  methods in my use-case: 
1.  ``.setup`` - cause spawn ``white/empty/without GUI`` tauri windows. In most cases windows window manager will say 'This application doesn't respond' (with attached action to pick pop-up) but in thiner instance is possible to receive from <b>windows defender AV</b> speech saying ___'This application is Malware'___. Also after some period of time one window will geting his own GUI, other windows won't be closed, 
2. ``.on_page_load`` - cause spawn tauri windows (less then in ``.setup``, in same time) mostly with loaded GUI, main window is marked as '(not responding)', after some time loaded window GUI changes to whole Black, amount of loading windows increaeses in time,

**Consistence between above methods occur**: In both cases tauri is still spawning multiple windows without any control (infinite loop -> each window initialize same python code so other process). 

## Summary
**To recap**: I need spawn process by python which will be not treat as tauri window.

### Reproduction

py.py
```py
from multiprocessing import Process


def task():
  print("Task performed!")

if __name__ == "__main__":
    print("Executing...")
    p = Process(target=task)
    p.start()
    p.join()
    print(p)
```

Add to Cargo.toml **[dependencies]**

```toml
pyo3 = { version = "0.19.2", features = ["auto-initialize"] }
```

main.rs

```rs
use tauri::*;
use pyo3::{types::PyModule, Python};

fn python() {
    Python::with_gil(|py| {
        let code = include_str!("path to your localmachine py.py file with code located up"); // Loading python code as &str
        let p_mod = PyModule::from_code(py, code, "file.py", "__main__")
          .unwrap();
    })
}

fn main() {
    tauri::Builder::default()
        .setup(|_| {
             // Uncomment below for .setup example
             // python();
             Ok(())
        })
        .on_page_load(|w, plp| {
           // Uncomment below for .on_page_load example
           // python();
        })
        .run(tauri::generate_context!())
        .unwrap();

}
```

### Expected behavior

Spawn process/processes (multiple when it's required) using Python without spawn a lot of unreasonable tauri windows in any form

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10._ X64
    ✔ WebView2: 114._
    ✔ MSVC: 
        - Visual Studio Build Tools 2022
        - Visual Studio _
    ✔ rustc: 1.67.0 (fc594f156 2023-01-24)
    ✔ Cargo: 1.67.0 (8ecd4f20a 2023-01-10)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.6.0
    - npm: 9.6.3

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    ...
```

### Stack trace

```text
In cli nothing special without prinitng from python code
```

**Comment by EleniAnagnos** [comment]
What is with an actual state?

**Comment by JonasKruckenberg** [comment]
What you're experiencing is caused by the fact that you embedded the python runtime: When you call `Process.start()` is spawns a copy of your current executable. Importantly, since you embedded Python into Tauri that whole thing is now your *executable* meaning that `Process.start()` now not only starts a new instance of the Python runtime but also of your Tauri app, hence the duplicated Windows. 

There are many ways to solve this, but all boil down to adding some sort of mechanism to the start of your program that can detect when it's **not the first instance** and then skip the Tauri initialisation. Feel free to take a look at the [`single-instance` plugin](https://github.com/tauri-apps/plugins-workspace/tree/v1/plugins/single-instance) depending on your exact use case this might be helpful to you.
