### ISSUE TITLE
How to use three.js to load .glb 3D model in Electron?

### ISSUE THREAD

**Issue by PublicWorld** [tauri-apps/tauri#7688]
### Describe the problem

I would like to know if I can load the glb 3D model file in the Tauri app?

For example, using [three.js](https://github.com/mrdoob/three.js) to load **.glb** files, if possible, can you provide a demo, because I have tried but failed, always showing a black background.

3D model url(.glb):
- https://threejs.org/examples/models/gltf/RobotExpressive/RobotExpressive.glb

how to load 3D models guide:
- https://threejs.org/docs/index.html#manual/en/introduction/Loading-3D-models

### Describe the solution you'd like

As stated above, thanks!

**Comment by FabianLars** [comment]
Did you see <https://github.com/erikpa1/tauri_threejs/blob/main/src/World.jsx> via https://github.com/tauri-apps/tauri/discussions/5045? It loads a jpg as a texture but it should work the same for your use case. The important part here is <https://tauri.app/v1/api/js/tauri/#convertfilesrc> to get the file from the file system into the webview.

**Comment by alindas** [comment]
electron？this is tauri LOL
