### ISSUE TITLE
[feat] How do I disable the default event for Alt press?

### ISSUE THREAD

**Issue by Arxoto** [tauri-apps/tauri#7689]
### Describe the problem

How do I disable the default event for Alt press?
I want to register the global shortcut "Alt+Space" to show or hide my window.
```
    register('Alt+Space', async () => {
        const mainWindow = WebviewWindow.getByLabel('main');
        if (!mainWindow) {
            return;
        }
        if (await mainWindow.isVisible()) {
            mainWindow.hide();
        } else {
            mainWindow.show();
            mainWindow.setFocus();
        }
    });
```

The shortcut alt+space will open the window menu, too. see [#547](https://github.com/tauri-apps/tao/issues/547)

When I press alt+space, it will able to successfully open the window. But it will open the window menu if I press spacebar again (no pressing Alt).

I think it's about the Alt event. In Windows, it will focus on the menu bar every time pressing alt. Maybe it's still seen as being held down in window?

I do not know how to circumvent the problem, hope there's a way to disable the Alt events : )

### Describe the solution you'd like

Add an option to the configuration file "tauri.conf.json" to disable the Alt events.
```
  "tauri": {
    "keyEvent": {
      "disableAltEvents": true,
    },
  }
```

**Comment by amrbashir** [comment]
The above code works perfectly fine on my Windows machine, please provide a minimal repro if you still face an issue.

**Comment by HuakunShen** [comment]
@amrbashir 
I am trying to let user enter a key combination hotkey, user pressed Alt + Space. Window menu appears instead.
Is there any way to prevent this menu from appearing?
