### ISSUE TITLE
[bug] can not disable webview2 mouse gesture use additionalBrowserArgs

### ISSUE THREAD

**Issue by Aostas** [tauri-apps/tauri#7692]
### Describe the bug

Microsoft updated webview2 to version 116.0.1938.54 that enable right mouse gesture featrue by default. here is the issue about this: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3737.
According to that issue, it can be disabled by additional browser arguments:
`--disable-features=msEdgeMouseGestureSupported,msEdgeMouseGestureDefaultEnabled --enable-features=kEdgeMouseGestureDisabledInCN`.
I add these args to `additionalBrowserArgs`,but not work.
![image](https://github.com/tauri-apps/tauri/assets/31911231/4a9f2778-2d7a-449a-8105-27965c043040)

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 116.0.1938.54
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.68.2 (9eb3afe9e 2023-03-27)
    ✔ Cargo: 1.68.2 (6feb7c9cf 2023-03-26)
    ✔ rustup: 1.25.2 (17db695f1 2023-02-01)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.15.0
    - yarn: 1.22.19
    - npm: 9.5.0

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1421/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by amrbashir** [comment]
It looks like it will be disabled by default next week, so there is nothing we can do. Also if the flag doesn't work when provided in `additionalBrowserArgs` it is not our issue, so maybe report it to WebView2.

**Comment by Aostas** [comment]
Yes, these args can not work on Edge browser too.
I have reported it to WebView2.
