### ISSUE TITLE
[bug] double tap on data-tauri-drag-region doesn't work

### ISSUE THREAD

**Issue by Isolus** [tauri-apps/tauri#7694]
### Describe the bug

At least on macOS double tapping data-tauri-drag-region doesn't do anything. Double click does maximize/unmaximize.

### Reproduction

Create an app with a data-tauri-drag-region element and double tap on it.

### Expected behavior

Double tapping should do the same as double clicking.

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.71.1 (eb26296b5 2023-08-03)
    ✔ Cargo: 1.71.1 (7f1d04c00 2023-07-29)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 16.17.0
    - npm: 8.15.0

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Additional context

It doesn't work because of this check: https://github.com/tauri-apps/tauri/blob/1.x/core/tauri/scripts/core.js#L137
`e.buttons` is 0 in case of tapping.

**Comment by amrbashir** [comment]
by tapping, do you mean touch screen?

**Comment by Isolus** [comment]
No, I mean the integrated Trackpad/Touchpad on MacBooks. It has a "Tap to Click" mode that is supposed to treat click and tap equally.

**Comment by kurdin** [comment]
@Isolus I don't see any issues with double clicking on `data-tauri-drag-region`  on Mac OSX tried both trackpad and a mouse. Works fine.

**Comment by amrbashir** [comment]
@pewsheen or @dklassic could you test this on your macOS?

**Comment by pewsheen** [comment]
> @pewsheen or @dklassic could you test this on your macOS?

When clicking, `e.buttons` is always `1`. But with "Tap to click", `e.buttons` is sometimes  `0` and sometimes `1`, and `e.button` will always be `0`.

**Comment by Isolus** [comment]
> @Isolus I don't see any issues with double clicking on `data-tauri-drag-region` on Mac OSX tried both trackpad and a mouse. Works fine.

Do you mean double tapping (with Tap to click) or clicking on the Trackpad?

And I'm not sure if this is releveant, I have the problem on a M2 Mac. (I have no idea if this could be the same problem, but some tap command were not working on JetBrains IDEs on M1/M2 Macs because Apple changed some things related to tapping on them, but not on Intel Macs running the same OS version.)

**Comment by amrbashir** [comment]
> > @pewsheen or @dklassic could you test this on your macOS?
> 
> When clicking, `e.buttons` is always `1`. But with "Tap to click", `e.buttons` is sometimes `0` and sometimes `1`, and `e.button` will always be `0`.

Thanks for testing, maybe we should be using `e.button` instead then

**Comment by kurdin** [comment]
@amrbashir I agree that better to use `e.button` to detect left/right click event

https://codepen.io/kurdin/pen/wvRWYXb

**Comment by pewsheen** [comment]
@amrbashir Yeah, I can make a PR later. Should we backport this to Tauri-1.4?

We should note that the behavior will be slightly changed to accept multiple keys clicked with the LEFT button (MOUSE4 + LEFT will also trigger the maximum action), but I think this is fine.

**Comment by amrbashir** [comment]
@pewsheen yeah, it should be merged in `1.x` branch first, then it will be merged against `dev` later.

> We should note that the behavior will be slightly changed to accept multiple keys clicked with the LEFT button (MOUSE4 + LEFT will also trigger the maximum action), but I think this is fine.

Yeah this should be fine as long the `LEFT` click is the first to happen.
