### ISSUE TITLE
[feat] 2.0: Add plugin to lib.rs with `tauri plugin add`

### ISSUE THREAD

**Issue by lorenzolewis** [tauri-apps/tauri#7696]
### Describe the problem

`tauri plugin add` updates `package.json` and `Cargo.toml` from what I understand, but there's one more friction point for non-Rust devs: adding the plugin initialiser to the builder in `lib.rs`. `tauri plugin add` should do this as part of it's logic

### Describe the solution you'd like

Example flow for notification plugin:
1. ✅ User runs `tauri plugin add notification`
2. ✅ Add dependency to `package.json` and `Cargo.toml` (I believe this is already done today)
3. 🆕 Add plugin initialiser to `lib.rs` on the Tauri app builder (not done today)
4. ❓(optional) Prompt the user with "these are the changes to the files that are going to be made, ready to accept them?" or similar (check out the astro add CLI for how they do that)

### Additional context

- Discussion in the docs repo: https://github.com/tauri-apps/tauri-docs/pull/1379#discussion_r1306059745
- Astro add command: https://docs.astro.build/en/guides/integrations-guide/solid-js/#astro-add-command
- Keep in mind these two ideas:
  - users who never touch Rust (and have the default Tauri rust project), how do we use this to make Tauri more approachable?
  - Plugins are a much larger story in 2.0 than they were in 1.0, any DX improvements we can do that touch them are a huge win

**Comment by lorenzolewis** [comment]
@amrbashir we talked about this briefly on Discord a while back, do you think this is something we'd be able to get in (and if so would you be the one able to work on it)? I think this is a pretty crucial piece of DX improvement we can get in prior to 2.0

**Comment by amrbashir** [comment]
It is definitely on my radar but not super urgent atm and could be added at any time later if we couldn't get it before 2.0-beta.

**Comment by lorenzolewis** [comment]
As long as we can try to slot it before 2.0 stable then that's fine to me. Thanks!
