### ISSUE TITLE
[bug] Any imports on a clean project fail

### ISSUE THREAD

**Issue by Pipsquexk** [tauri-apps/tauri#7698]
### Describe the bug

Exactly as the title says, I create a new project, go into the main.js file and switch out

`const { invoke } = window.__TAURI__.tauri;`

for

`import { invoke } from "@tauri-apps/api/tauri";`

This same behavior occurs with any other attempts at using import as well.

I have tried providing a relative path, to be met an error like this:
`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.`

### Reproduction

Create a new vanilla, npm, javascript frontend project
Switch `const { invoke } = window.__TAURI__.tauri;` for `import { invoke } from "@tauri-apps/api/tauri";` in main,js

### Expected behavior

Imports @tauri-apps/api/tauri without issue

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 115.0.1901.203
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.71.1 (eb26296b5 2023-08-03)
    ✔ Cargo: 1.71.1 (7f1d04c00 2023-07-29)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 16.14.0
    - npm: 8.3.1

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../src
    - devPath: ../src
```

### Stack trace

```text
Uncaught TypeError: Failed to resolve module specifier "@tauri-apps/api/tauri". Relative references must start with either "/", "./", or "../".

In the inspector/DevTools console
```

**Comment by FabianLars** [comment]
Thanks for reaching out :)

The issue is that if you want to use npm packages you realistically won't get around frontend bundlers like vite or webpack. The vanilla javascript is the only template that doesn't include it (mainly for devs that don't want anything nodejs in their app). You could however choose the vanilla **typescript** template instead, which comes with vite (you can still use javascript in that project).

**Comment by Pipsquexk** [comment]
Thank you!
