### ISSUE TITLE
[bug] can not use await in  ts file  on mac

### ISSUE THREAD

**Issue by lsl52640** [tauri-apps/tauri#7708]
### Describe the bug

<img width="750" alt="image" src="https://github.com/tauri-apps/tauri/assets/88765548/382d5a54-d184-4af3-8aa7-4b3851f9e144">

import { appConfigDir } from "@tauri-apps/api/path";
import { Store } from "tauri-plugin-store-api";

const path = await appConfigDir();
const configDb = new Store(path);

### Platform and versions

```text
Environment
  › OS: Mac OS 11.7.4 X64
  › Node.js: 18.16.1
  › npm: 9.5.1
  › pnpm: 7.9.5
  › yarn: 1.15.2
  › rustup: 1.24.3
  › rustc: 1.66.1
  › cargo: 1.66.1
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.2.2 (outdated, latest: 1.4.0)
  › @tauri-apps/api [NPM]: 1.2.0 (outdated, latest: 1.4.0)
  › tauri [RUST]: 1.2.3,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Vue.js
  › bundler: Webpack
```

### Stack trace

```text
SyntaxError: Unexpected identifier 'appConfigDir'. Expected ';' after variable declaration.
parseModule
[native code]
asyncFunctionResume
[native code]
promiseReactionJobWithoutPromise
promiseReactionJob
```

**Comment by amrbashir** [comment]
You need to call await inside an async function or use `.then` on the promise returned from `appConfigDir`. 

Since this question is not related to tauri, I will go ahead and close this.

**Comment by lsl52640** [comment]
> You need to call await inside an async function or use `.then` on the promise returned from `appConfigDir`.
> 
> Since this question is not related to tauri, I will go ahead and close this.

Why can I run it on Windows11?

**Comment by FabianLars** [comment]
Because chromium supports top level awaits but the [webkit version](https://tauri.app/v1/references/webview-versions/#macos--ios) of the webview in your macos version doesn't. Your version equals ~Safari14 while top level await was added in Safari15, see here for example https://caniuse.com/?search=top%20level%20await
