### ISSUE TITLE
cli should be object

### ISSUE THREAD

**Issue by anlek** [tauri-apps/tauri#771]
**Describe the bug**
When running `yarn tauri dev`, I get this error:
```bash
yarn run v1.22.4
$ /Users/andrew/code/tauri-apps/test-app/node_modules/.bin/tauri dev
[tauri]: running dev
 ERROR: tauri.conf.json > tauri > cli should be object +0ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
**To Reproduce**
1. Started a new folder
2. ran `yarn init`
3. ran `yarn tauri init`
4. ran `yarn tauri dev`

**Expected behavior**
A dev server should start running

**Screenshots**

**Platform and Versions (please complete the following information):**

Operating System - Darwin(19.5.0) - darwin/x64

Node.js environment
  Node.js - 14.5.0
  tauri.js - 0.8.2

Rust environment
  rustc - 1.44.1
  cargo - 1.44.1
  tauri-bundler - 0.8.2

Global packages
  NPM - 6.14.5
  yarn - 1.22.4

App directory structure
/node_modules
/src-tauri

App
  tauri.rs - 0.7 (no lockfile)
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  Windows - Edge
  distDir - ../dist
  devPath - http://localhost:4000

**Additional context**
I used *asdf* to install rust on my system.

**Comment by lucasfernog** [comment]
What's your tauri.conf.json contents?

**Comment by anlek** [comment]
```json
{
  "build": {
    "distDir": "../dist",
    "devPath": "http://localhost:4000",
    "beforeDevCommand": "",
    "beforeBuildCommand": ""
  },
  "ctx": {},
  "tauri": {
    "cli": null,
    "embeddedServer": {
      "active": true
    },
    "bundle": {
      "active": true,
      "targets": "all",
      "identifier": "com.tauri.dev",
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "resources": [],
      "externalBin": [],
      "copyright": "",
      "category": "DeveloperTool",
      "shortDescription": "",
      "longDescription": "",
      "deb": {
        "depends": [],
        "useBootstrapper": false
      },
      "osx": {
        "frameworks": [],
        "minimumSystemVersion": "",
        "useBootstrapper": false
      },
      "exceptionDomain": ""
    },
    "whitelist": {
      "all": true
    },
    "window": {
      "title": "Tauri App",
      "width": 800,
      "height": 600,
      "resizable": true,
      "fullscreen": false
    },
    "security": {
      "csp": "default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'"
    },
    "edge": {
      "active": true
    },
    "inliner": {
      "active": true
    }
  }
}
```

**Comment by lucasfernog** [comment]
Can you just remove the "cli" key instead of setting it to null? Our validator currently doesn't support null values.

**Comment by anlek** [comment]
That seems to have worked, though once the "App" opened, the logs said this:
```
    Finished dev [unoptimized + debuginfo] target(s) in 1m 01s
     Running `target/debug/app`
Error: connect ECONNREFUSED 127.0.0.1:4000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 4000
}
```

Not sure if it's related...

**Comment by lucasfernog** [comment]
Did you start your dev server before running tauri dev?

**Comment by anlek** [comment]
I thought `yarn tauri dev` was me starting my dev server...

**Comment by anlek** [comment]
I might be misunderstanding what should exist at localhost:4000... I think I'm confused on Tauri's role is in an app. However, my original bug has been fixed, so I'm going to close this ticket.

**Comment by lucasfernog** [comment]
Can you join our Discord server so we can talk and get this sorted? I'm always checking what's going on there. Thank you!

**Comment by fraserxu** [comment]
Ran into the same issue. Thought it was because port conflict and tried to change different port.

Turns out the order is:

1. start a local server something like `http-server .` on a `port` e.g. `7000`
2. change the `tauri` config `devPath` to use the same `port`
 
It's not a bug but can be confusing for absolute beginners like me just to try it out.
