### ISSUE TITLE
[feat] Add rpath for Frameworks on MacOS

### ISSUE THREAD

**Issue by tr3ysmith** [tauri-apps/tauri#7710]
### Describe the problem

When adding frameworks for MacOS in the tauri.conf.json, the rpath is not automatically set during the build process

### Describe the solution you'd like

I would like for Tauri to automatically apply the rpath to the executable if needed:

```rust
println!("cargo:rustc-link-arg=-Wl,-rpath,@executable_path/../Frameworks");
```

**Comment by Brendonovich** [comment]
Seems like this also closes #7480. Symlinks in the `Frameworks` folder weren't being preserved but using this PR they are.
