### ISSUE TITLE
[bug] in MacOs, replace all "Uint8Array.from(xxx)” to “new Uint8Array(xxx)”

### ISSUE THREAD

**Issue by marikv** [tauri-apps/tauri#7715]
### Describe the bug

fs not working in MacOs. before build or dev, you must to replace all "Uint8Array.from(xxx)" to "new Uint8Array(xxx)" in node_modules directory

### Platform and versions

```text
MacOs
```

**Comment by amrbashir** [comment]
Please provide more info, and if there is any error messages you see in terminal or in devtools, please post them here as well. and also a reproduction is very much appreciated.

I will temporarily close this issue for lack of information.
