### ISSUE TITLE
[feat] Allow Windows system tray menu open on mouse/trackpad left click

### ISSUE THREAD

**Issue by kurdin** [tauri-apps/tauri#7719]
### Describe the problem

On Windows, if I want to access (show) system tray menu, I need to click the right mouse/trackpad click (show menu) then left click to select menu item. This is ok by default if you don't need to access the menu too often but if have important functionality in the menu items, like dynamically generated menu items, it would be nice to have an option to allow users to show system tray menu and select items with the same mouse/trackpad button, `left click` for all actions, on all platforms. Currently on Mac and Linux you can use left click to open system tray menu and select items. Only Windows required to use the right click.

### Describe the solution you'd like

I would like to have an option to allow create a system tray menu on Windows with option to show the menu on left click, instead of standard action on right click. Maybe just add support for `SystemTray::with_menu_on_left_click` on Windows platform.

https://github.com/tauri-apps/tauri/commit/63011ca84e7a22c8c0d8bd1c1be6592140f93ff2#diff-6d57b6afece9589b880315885f1cce9b4e645c00428b503bb2720424b6bdea34

**Comment by Levminer** [comment]
@amrbashir This got implemented in `tray-icon v0.19.1` which the latest tauri version 2.1.1 uses. But it still says this is only implemented on macOS: https://github.com/tauri-apps/tauri/blob/f2814ed5384e3e29dc76343d43cb6e3cc68fe942/crates/tauri/src/tray/mod.rs#L552

**Comment by amrbashir** [comment]
@Levminer thanks, I have opened a PR for this.
