### ISSUE TITLE
[feat] setting window

### ISSUE THREAD

**Issue by Jarrodsz** [tauri-apps/tauri#7724]
### Describe the problem

Need a pref window with tabbed ui
It just finish the expierience.
Hard to replicate in react which i did it still feels not native enough

### Describe the solution you'd like

Build a custom window like 
https://github.com/sindresorhus/Settings

If possible at all

### Alternatives considered

Using react for the content in the window mimic the ui
Not good enough

### Additional context

Would like to onow of this is possible at all

**Comment by amrbashir** [comment]
This is outside the scope of tauri, and better suited to be a community project.
