### ISSUE TITLE
[bug] Scope not defined for window `local` and URL `file:///D:/code/rust/robot/src/setting.html`

### ISSUE THREAD

**Issue by trookie2000** [tauri-apps/tauri#7739]
### Describe the bug

I added a new window (setting.html) to the menu bar of the tauri program, and in this control, opening developer mode gives an Error: Scope not defined for window `local` and URL `file:///D:/code/rust/robot/src/setting.html`. See  https://tauri.app/v1/api/config/#securityconfig.dangerousremotedomainipcaccess and  https://docs.rs/tauri/1/tauri/scope/struct.IpcScope.html#method.configure_remote_access.

This is my code in the main.rs program, where setting corresponds to the label. How can I change it to avoid this error

"setting" =&gt;  {

let app = event.window().app_handle();

let _local_window = tauri::WindowBuilder::new(

&app,

"local",

tauri::WindowUrl::App("D:/code/rust/robot/src/setting.html".into())

).build();

}

### Reproduction

No response

### Expected behavior

No response

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 115.0.1901.203
    ✔ MSVC:
        - Visual Studio Build Tools 2022
        - Visual Studio Community 2019
    ✔ rustc: 1.71.1 (eb26296b5 2023-08-03)
    ✔ Cargo: 1.71.1 (7f1d04c00 2023-07-29)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.17.1
    - npm: 9.8.1

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - bundler: Vite
```

### Stack trace

```text
No response
```

**Comment by amrbashir** [comment]
Using a local path is not supported, If I assume right, I think you have this structure:
```
src/
  |_ index.html
  |_ setting.html
src-tauri/
```
and in this case, you need to just use `tauri::WindowUrl::App("setting.html".into())`

**Comment by trookie2000** [comment]
> Using a local path is not supported, If I assume right, I think you have this structure:
> 
> ```
> src/
>   |_ index.html
>   |_ setting.html
> src-tauri/
> ```
> 
> and in this case, you need to just use `tauri::WindowUrl::App("setting.html".into())`
According to your revised, an error is

tauri::WindowUrl::App("src/setting.html".into())

expected `()`, found `WindowUrl`



Change the code to:

"setting" =&gt;  {

tauri::WindowUrl::App("src/setting.html".into())

}

My project structure is as follows

src/

|_ setting.html

src-tauri/

|_ main.rs

**Comment by trookie2000** [comment]
I forgot to mention that setting.html is a window in the menu bar of the click program, and my main program code

`tauri::Builder::default()
.menu(menu)
.on_menu_event(|event| {

match event.menu_item_id() {

"setting" => {

tauri::WindowUrl::App("setting.html".into())
}`

**Comment by amrbashir** [comment]
```rs
tauri::Builder::default()
	.menu(menu)
	.on_menu_event(|event| {
		match event.menu_item_id() {
			"setting" => {
				let _local_window = tauri::WindowBuilder::new(
					&app,
					"local",
					tauri::WindowUrl::App("setting.html".into())

				).build();

			}
		}
	}
```

**Comment by trookie2000** [comment]
Thans！！
