### ISSUE TITLE
[feat] Clipboard support for RTF (rich text format), HTML and Image

### ISSUE THREAD

**Issue by HuakunShen** [tauri-apps/tauri#7750]
### Describe the problem

Tauri clipboard API only supports `writeText()` and `readText()`.

It would be nice to also have HTML and RTF support like Electron.

https://www.electronjs.org/docs/latest/api/clipboard#clipboardreadrtftype

![image](https://github.com/tauri-apps/tauri/assets/33727687/becde1af-e534-4c74-8ea8-43279f2818a8)

### Describe the solution you'd like

The solution should be just like Electron.

### Alternatives considered

[arboard](https://crates.io/crates/arboard) is a rust crate that supports image read and write. I built [tauri-plugin-clipboard](https://github.com/CrossCopy/tauri-plugin-clipboard) on top of it that supports clipboard image, but not RTF or HTML.

I tried to see how Electron achieves it. 

It seems like the methods all come from this file https://github.com/electron/electron/blob/main/shell/common/api/electron_api_clipboard.cc

However, this file don't contain the implementation of those functions, but a wrapper.

I could not find the dependency files like `scoped_clipboard_writer.h` or `clipboard_format_type.h` in their repo.

Not good at C++, but I will look into this.

**Comment by r4v5** [comment]
> It seems like the methods all come from this file https://github.com/electron/electron/blob/main/shell/common/api/electron_api_clipboard.cc
> However, this file don't contain the implementation of those functions, but a wrapper.
> I could not find the dependency files like scoped_clipboard_writer.h or clipboard_format_type.h in their repo.

That's from Chromium sources, in `ui/base/clipboard/` ([here](https://chromium.googlesource.com/chromium/src/+/refs/tags/116.0.5845.183/ui/base/clipboard/)). Note that Electron may additionally apply a patch to the Chromium sources for scoped_clipboard_writer specifically to enable "raw write" functionality, based on searching their repo for the string `scoped_clipboard_writer`, but I am not familiar enough with either electron nor chromium to verify that easily.

**Comment by HuakunShen** [comment]
Update: [tauri-plugin-clipboard](https://github.com/CrossCopy/tauri-plugin-clipboard) now supports text, image, file, html, RTF and watching.

**Comment by amrbashir** [comment]
Closing as the official clipboard plugin for v2 now supports html and image

**Comment by thiagovianav** [comment]
why does just plain text works for mobile tho? i was using the other plugin but it was just for desktop.

I'm just curious btw, I ain't yet a Rust guy

**Comment by dhimmel** [comment]
Just to make sure I'm understanding this correctly, the latest tuari version v2.9.3 does not support reading or writing to:

1. Rich Text Format (RTF) in a cross-platform compatible way
2. any arbitrary / system-specific format

**Comment by FabianLars** [comment]
assuming the web clipboard api doesn't support that correct. mostly blocked by https://github.com/1Password/arboard/issues/11 (for rtf in particular we could switch to clipboard-rs i guess).
