### ISSUE TITLE
[bug] macOS Code Signing Error

### ISSUE THREAD

**Issue by ruoxiaomo** [tauri-apps/tauri#7758]
### Describe the bug

I did the work according to [https://tauri.app/v1/guides/distribution/sign-macos](https://tauri.app/v1/guides/distribution/sign-macos), but when I was building the application, I was prompted: 
``
Team is not yet configured for notarization. 
Please contact Developer Programs Support at developer.apple.com under the topic Development and Technical / Other Development or Technical Questions.
``

What am I missing? And my Apple developer account is my Apple account. Will this affect the result?
My Mac is MacMini, M2

### Platform and versions

```text
yarn run v1.22.19
$ tauri info

[✔] Environment
    - OS: Mac OS 13.5.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.71.1 (eb26296b5 2023-08-03)
    ✔ Cargo: 1.71.1 (7f1d04c00 2023-07-29)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 18.17.0
    - yarn: 1.22.19
    - npm: 9.6.7

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: default-src 'self'; img-src 'self' asset: *; script-src 'self' asset: https://asset.localhost; style-src 'unsafe-inline'  asset: *; media-src *;
    - distDir: ../dist
    - devPath: http://localhost:5173/
    - framework: Vue.js
    - bundler: Vite
✨  Done in 4.70s.
```

**Comment by oopses** [comment]
https://developer.apple.com/forums/thread/118465
https://iosre.com/t/macos-app%E5%85%AC%E8%AF%81%E9%97%AE%E9%A2%98/20185
公证的这个问题已经有很多人提了，官方一直未给出明确的答案已经解决方案，时不时会抽风一下

**Comment by lyager** [comment]
Did you set the APPLE_TEAM_ID variable? If so, it might be something that needs to be set up at Apple.
