### ISSUE TITLE
dependency deprecation: request

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#776]
**Describe the bug**
@tauri-apps/tauri-inliner > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

**To Reproduce**
1. `yarn add tauri`

**Expected behavior**
No deprecations

**Comment by lucasfernog** [comment]
I'm going to close this one because the JS CLI is being rewritten in Rust, so the current inliner won't be used anymore.
