### ISSUE TITLE
ERROR: tauri.conf.json > tauri > embeddedServer has unknown property port +0ms

### ISSUE THREAD

**Issue by thienpow** [tauri-apps/tauri#778]
try configure
```json
"embeddedServer": {
  "active": true,
  "port": "3000"
}
```
yarn tauri dev or yarn tauri build would throw the error:
ERROR: tauri.conf.json > tauri > embeddedServer has unknown property port +0ms

**Comment by lucasfernog** [comment]
Closed by #782 and #784
