### ISSUE TITLE
Unable to loop through files in a directory

### ISSUE THREAD

**Issue by Anderneku** [tauri-apps/tauri#7781]
I am currently looking for a way to loop through files and folders in a directory recursively but am unable to do so. I tried looking at the docs for how to do that and I thought that using 'readDir' in the fs module might be a good idea. I tried copy/pasting the code from the docs:
```javascript
import { readDir, BaseDirectory } from '@tauri-apps/api/fs';
// Reads the `$APPDATA/users` directory recursively
const entries = await readDir('users', { dir: BaseDirectory.AppData, recursive: true });

function processEntries(entries) {
  for (const entry of entries) {
    console.log(`Entry: ${entry.path}`);
    if (entry.children) {
      processEntries(entry.children)
    }
  }
}
```
 But found that it didn't work and it was giving me some strange errors. I decided to try writing some logic of my own but it was only giving me the names of the directories in the directory passed in and wasn't giving me the files, subfolders, etc:

```javascript
async function ting(){
        const list = await readDir("Compressed", {dir: BaseDirectory.Download});
        console.log(list);
    }

```
Is there any way I could accomplish this?
Also I could accomplish this quite easily with the node js fs module. Is there a way to include node js modules in tauri?

**Comment by percy507** [comment]
You can use [`walkdir`](https://crates.io/crates/walkdir/) crate and write yourself backend command. This is what I do.

**Comment by FabianLars** [comment]
Could you tell us a bit more about the errors (maybe the full error messages)? Your first code example looks alright to me on first glance. - Whoops, just noticed that it's the code from our docs, i sure hope that it's not broken 😅 

Was it maybe about the scope configs? That would be explained here: https://tauri.app/v1/api/js/fs/#security

> I decided to try writing some logic of my own but it was only giving me the names of the directories in the directory passed in and wasn't giving me the files, subfolders, etc:

That's weird, readDir should always include files and dirs 🤔 

> Is there a way to include node js modules in tauri?

Nope, there is no nodejs runtime in a tauri app so you can't use its apis.

**Comment by Anderneku** [comment]
By the way I'm using Sveltekit with Tauri

Anyways, running the first code doesn't even run and I get this error:

> ```js
> import { readDir, BaseDirectory } from '@tauri-apps/api/fs';
> // Reads the `$APPDATA/users` directory recursively
> const entries = await readDir('users', { dir: BaseDirectory.AppData, recursive: true });
> 
> function processEntries(entries) {
>   for (const entry of entries) {
>     console.log(`Entry: ${entry.path}`);
>     if (entry.children) {
>       processEntries(entry.children)
>     }
>   }
> }
> ```

![image](https://github.com/tauri-apps/tauri/assets/68037779/6be7d4d4-d006-45c2-98f3-a4d83f4f9a6e)

It tells me I can't use the await keyword. This is how I implemented it in Svelte:


So I rearrange the code like this:

![image](https://github.com/tauri-apps/tauri/assets/68037779/2580d23d-b5a6-45db-a91e-343112e19313)

And it now works!!!
It gives the correct output:

![image](https://github.com/tauri-apps/tauri/assets/68037779/93546a8d-066a-48ed-bb07-6a22715c43e4)

I don't mean to be tooting my own horn, but I feel like the example in the docs should be updated

**Comment by Anderneku** [comment]
Any thoughts?

> You can use [`walkdir`](https://crates.io/crates/walkdir/) crate and write yourself backend command. This is what I do.

I'll still try that walkdir, though I'm not that familiar with Rust as I only know the basic functionality

**Comment by Anderneku** [comment]
Or rather than a recursive function, something like this can be achieved:

![image](https://github.com/tauri-apps/tauri/assets/68037779/bbc92174-aeb4-4eda-9a0b-09a38b0c7980)

I don't know

**Comment by amrbashir** [comment]
The documentation is correct, you were just using await in a non-async function and the documentation kinda expects the users to be aware of async/await and Promises.

**Comment by amrbashir** [comment]
If you have any suggestion to improve it, please let me or better open a PR. We appreciate your feedback.
