### ISSUE TITLE
[bug] Failed to load resource: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by fanchenio** [tauri-apps/tauri#7784]
### Describe the bug

Upgrading from v1 to v2, error reported.
Failed to load resource: net::ERR_CONNECTION_REFUSED
Uncaught (in promise) TypeError: Failed to fetch
May I ask how is this going?

![image](https://github.com/tauri-apps/tauri/assets/88647148/074034b0-95f4-4fec-9a8f-860d24c1be9a)
![image](https://github.com/tauri-apps/tauri/assets/88647148/f18809b8-0fa3-463a-ab5c-ccea9fe1430f)
![image](https://github.com/tauri-apps/tauri/assets/88647148/d2efd862-8657-42da-9ab0-c390473bd525)

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 116.0.1938.69
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.17.1
    - pnpm: 8.6.9
    - yarn: 1.22.19
    - npm: 8.7.0

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.12
    - tauri-build [RUST]: 2.0.0-alpha.8
    - wry [RUST]: 0.32.0
    - tao [RUST]: 0.22.2
    - @tauri-apps/api [NPM]: 2.0.0-alpha.6
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.12

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by pewsheen** [comment]
This should be fixed in https://github.com/tauri-apps/tauri/pull/7779
