### ISSUE TITLE
[feat] 希望tauri能支持播放m3u8视频

### ISSUE THREAD

**Issue by javamiller** [tauri-apps/tauri#7786]
### Describe the problem

我打算做一个桌面程序，目的是做一个视频网站，用户可以点播视频，因为考虑到爬虫等技术能很轻松爬取mp4视频，所以我考虑使用m3u8，目的是阻止非法用户爬取我的视频售卖，保护我的劳动成果，对应前端的组件是**hls.js**。
但是我调研的时候发现tauri前后端交互使用的是invoke的方法，而hls组件是通过http请求来接收m3u8和ts文件播放，所以估计invoke这类的方法不能用来播放m3u8视频。
希望能够得到专业人士的回应，如果tauri能做到m3u8视频播放功能，将会给我带来很大的便利，谢谢。

### Describe the solution you'd like

我并没有很好的解决方案，期望能有更厉害的人来解决tauri播放m3u8视频。

**Comment by FabianLars** [comment]
So the translator mostly spit out gibberish so i'm not sure i understood your question completely. Either way, i can't give you a ready-to-use solution/example but i know that there are a few devs that use the [asset protocol](https://tauri.app/v1/api/js/tauri/#convertfilesrc) (or completely [custom](https://docs.rs/tauri/latest/tauri/struct.Builder.html#method.register_uri_scheme_protocol) protocols) with hls.js

**Comment by 34205037** [comment]
看起来你的需求和tauri无关，在tauri中不是可以继续使用http请求吗？

**Comment by javamiller** [comment]
> So the translator mostly spit out gibberish so i'm not sure i understood your question completely. Either way, i can't give you a ready-to-use solution/example but i know that there are a few devs that use the [asset protocol](https://tauri.app/v1/api/js/tauri/#convertfilesrc) (or completely [custom](https://docs.rs/tauri/latest/tauri/struct.Builder.html#method.register_uri_scheme_protocol) protocols) with hls.js

Ok, thank you for your reply. I will continue to learn more about the details of **hls.js**

**Comment by javamiller** [comment]
> 看起来你的需求和tauri无关，在tauri中不是可以继续使用http请求吗？

好，谢谢了，是我想的太复杂了，因为我刚开始了解相关的东西，谢谢你的回复

**Comment by javamiller** [comment]
The problem has nothing to do with tauri itself
