### ISSUE TITLE
Null value set for "cli" in default template

### ISSUE THREAD

**Issue by anselanza** [tauri-apps/tauri#779]
**Describe the bug**
As a new user of Tauri, there was no indication that I had to make changes to the tauri.conf.json in order to avoid errors on first use.

**To Reproduce**
1. Install all dependencies as per docs
1. Add tauri as depedency to project as per docs
1. Initialise using `yarn tauri init` as per docs
1. Run `yarn tauri dev`
1. You get the following error: 
```
yarn run v1.22.4

[tauri]: running dev
 ERROR: tauri.conf.json > tauri > cli should be object +0ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**
I would expect at least a blank app window to open, no errors.

**Platform and Versions (please complete the following information):**
```
[tauri]: running info

Operating System - Darwin(19.4.0) - darwin/x64

Node.js environment
  Node.js - 12.16.1
  tauri.js - 0.8.2

Rust environment
  rustc - 1.44.1
  cargo - 1.44.1
  tauri-bundler - 0.8.3

Global packages
  NPM - 6.14.5
  yarn - 1.22.4

App directory structure
/.git
/node_modules
/src-tauri

App
  tauri.rs - 0.7.1
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  Windows - Edge
  distDir - ../dist
  devPath - http://localhost:3000
✨  Done in 1.88s.
```

**Workaround**
I needed to edit the automatically-generated `tauri.conf.js` file and delete the line 
```
"cli": null,
```
No more errors; can proceed with development.

This is either a bug in the init script (creating a config file with an invalid value for "cli") or needs to be documented properly for first-time users.

**Comment by nothingismagick** [comment]
thanks - i just reported this in #777
