### ISSUE TITLE
MSHTML Engine does not support Promise so boilerplate throws error

### ISSUE THREAD

**Issue by obany** [tauri-apps/tauri#780]
**Describe the bug**
On the windows platform if you switch to the MSHTML engine and then start the app it throws a script error, this is because the boilerplate code for Tauri `promisified` uses `new Promise` and the MSHTML engine does not support promises.

**To Reproduce**

Using windows platform.
Update `tauri.config.json` with

```js
"edge": {
      "active": false
    }
```

Start the application.

**Expected behavior**
The application should start with no errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/5030334/87022796-e6edf680-c1ce-11ea-947b-a9ad0b0f27d7.png)

**Platform and Versions (please complete the following information):**
OS: Windows 10 x64
Node: 12.4.1
NPM: 6.14.5
Yarn: 1.22.4
Rustc: 1.44.1

**Comment by lucasfernog** [comment]
I'm closing it since MSHTML support is dropped on webview/webview :( no need to worry about it right now.
