### ISSUE TITLE
openEluer linux打包为什么pnpm build后少了bundle文件 

### ISSUE THREAD

**Issue by wfc66986** [tauri-apps/tauri#7806]
### Describe the bug

openEluer 为什么pnpm build后少了bundle文件 
![1](https://github.com/tauri-apps/tauri/assets/54029486/69e315ba-4d66-4225-a2cc-ac766107f984)
![2](https://github.com/tauri-apps/tauri/assets/54029486/54d1bc5c-07b1-4cfe-a521-cf6bcf4cc29d)

### Platform and versions

```text
openEluer 为什么pnpm build后少了bundle文件
```

**Comment by wfc66986** [comment]
不用了 解决了。

**Comment by amrbashir** [comment]
As the error message says, you need to have one of these two libs installed `libappindicator` or `libayatana-appindicator`
