### ISSUE TITLE
How can i access plugin from vanila(pure javascript)

### ISSUE THREAD

**Issue by kingsanu** [tauri-apps/tauri#7807]
### Describe the bug

I'm not using NPM so i don't have option like follwing

import {printers, print_file, jobs, job, restart_job, pause_job, resume_job, remove_job} from "tauri-plugin-printer";

but i've option like following
 var { isPermissionGranted, requestPermission, sendNotification  } = window.__TAURI__.notification;
      
so how can i access that tauri-plugin-printer in my javascript?

### Platform and versions

```text
latest
```

**Comment by amrbashir** [comment]
As I explained in another issue, please use the issue tracker for bug and feature requests related to tauri, not to ask for help, if you need help please join our discord, or ask in the disucssions tab.

**Comment by amrbashir** [comment]
> but i've option like following
> var { isPermissionGranted, requestPermission, sendNotification } = window.TAURI.notification;
> 
> so how can i access that tauri-plugin-printer in my javascript?

Reach out to the plugin author to provide a global object or use a cdn service to serve you the npm package.
