### ISSUE TITLE
Unable to start dev mode on windows

### ISSUE THREAD

**Issue by obany** [tauri-apps/tauri#781]
Creating a very simple boilerplate with a single `index.html` will not start in dev mode on my windows machine. However a packaged version will run successfully.

**To Reproduce**
Reproduction repo here: https://github.com/obany/tauri-test
Run `npx tauri dev`
The application shows a blank page, and any interaction with the window frame causes the app to exit with.
```
Running `target\debug\app.exe`
error: process didn't exit successfully: `target\debug\app.exe` (exit code: 0xc000041d)

 app:spawn Command "cargo" failed with exit code: 3221226525 +1ms 
```

**Expected behavior**
The app should start and show the index page,

**Screenshots**
Dev version shows
![image](https://user-images.githubusercontent.com/5030334/87025369-34b82e00-c1d2-11ea-9b2a-a217b094ba7e.png)

Packaged version shows
![image](https://user-images.githubusercontent.com/5030334/87024940-a9d73380-c1d1-11ea-8ef9-4fc6da74c29a.png)

**Platform and Versions (please complete the following information):**

OS: Windows 10 x64
Node: 12.4.1
NPM: 6.14.5
Yarn: 1.22.4
Rustc: 1.44.1
Chromium Build: 85.0.552.1 (Official build) dev (64-bit)

**Additional context**
Even changing the `devPath` to `http://localhost:4000` and serving the page results in the same issue.

**Comment by lucasfernog** [comment]
Couldn't reproduce this one. Can you try again or maybe download the Edge DevTools from the Windows Store and see if there's any console errors?

**Comment by obany** [comment]
To be honest I don't think it is even getting as far as creating the webview, the devtools shows no instances to connect to (running the packaged build does show an instance to connect to).

I walked through the issue with @nothingismagick in chat but we couldn't fix the problem. 

I can also run the same repo on another machine without problem.
 
The version of Microsoft EdgeHTML is 18.19041 if that is of any help to narrow down the issue.

**Comment by thienpow** [comment]
currently you need to execute your project dev process first manually and wait until it is listening on a port... then only do yarn tauri dev

i face the same problem with svelte+sapper+webpack project... the sapper dev is always slower to be ready than the tauri dev, so i need to remove beforeDevCommand and manually wait for the sapper dev to be ready, then only type the tauri dev

**Comment by lucasfernog** [comment]
Did you face the same issue with tauri.js v0.9.0? @thienpow tauri should now wait for the devServer to be reachable.

**Comment by thienpow** [comment]
<img width="670" alt="Screenshot 2020-07-11 at 11 43 13 AM" src="https://user-images.githubusercontent.com/9796623/87215711-bc857000-c36b-11ea-90dd-bc8f50e811f2.png">

yes, after updated to 0.9, it is working good, can set back beforeDevCommand again.

**Comment by obany** [comment]
I tried it both with a local dev server, and with direct access to the dist files (as suggested by nothingismagick), neither worked.

Also tried updating to the latest versions, no improvement.

I still think something is failing when it tries to instantiate the webview, but not sure how I can debug this.

**Comment by nothingismagick** [comment]
is there any chance you could try on this machine using WSL @obany ?

**Comment by nothingismagick** [comment]
Because really, it won't matter what dev environment you use, we just released this workflow so you can cross-compile:

https://github.com/tauri-apps/tauri-action

**Comment by lucasfernog** [comment]
Can you give us your "npx tauri info" after updating? If build works then dev should work too.

**Comment by obany** [comment]
Just settings up the WSL now.

Current info on regular windows

```
Operating System - Windows_NT(10.0.19041) - win32/x64

Node.js environment
  Node.js - 12.14.1
  tauri.js - 0.9.0 

Rust environment   
  rustc - 1.44.1
  cargo - 1.44.1
  tauri-bundler - 0.8.2

Global packages
  NPM - 6.14.6
  yarn - 1.22.4

App directory structure
/dist
/node_modules
/src-tauri

App
  tauri.rs - 0.7.4
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  Windows - Edge
  distDir - ../dist
  devPath - http://localhost:4000
```

**Comment by lucasfernog** [comment]
Can you try updating tauri.js to 0.9.1 and tauri.rs to 0.7.5? Probably won't help but just in case.

**Comment by obany** [comment]
Updated to latest, no dice.

```
Operating System - Windows_NT(10.0.19041) - win32/x64
Microsoft Edge - 44.19041.1.0_neutral__8wekyb3d8bbwe

Node.js environment
  Node.js - 12.14.1
  tauri.js - 0.9.1

Rust environment
  rustc - 1.44.1
  cargo - 1.44.1
  tauri-bundler - 0.8.2

Global packages
  NPM - 6.14.6
  yarn - 1.22.4

App directory structure
/.git
/.history
/dist
/node_modules
/src-tauri

App
  tauri.rs - 0.7.5
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  Windows - Edge
  distDir - ../dist
  devPath - http://localhost:4000
```

But WSL running from exactly the same folder works, so config is correct.
![image](https://user-images.githubusercontent.com/5030334/87322110-ecc43e80-c524-11ea-9245-b4d7f4ac3dd0.png)

**Comment by nothingismagick** [comment]
Well, at least you've got a dev environment you can work with. That's a huge relief.

**Comment by obany** [comment]
Not really, the app takes 2 mins to start each time and the webtools load and then crash the xserver :( So not really an option for debugging.

**Comment by lucasfernog** [comment]
Can you test using `yarn` instead of `npx`? We're finding some REALLY weird issues with `npx`.

**Comment by obany** [comment]
Tried both, still no luck, is there any way to get more verbose logging when the webview is created ?

**Comment by obany** [comment]
As I guessed it looks like the webview is at fault, I created a test https://github.com/obany/tauri-webview-test using just the original https://github.com/Boscop/web-view and that fails in the same way.

Edge mode fails, MSHTML works - so it is likely this issue https://github.com/Boscop/web-view/issues/96 and more specifically https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/50

**Comment by nothingismagick** [comment]
https://github.com/Boscop/web-view/issues/96#issuecomment-568881215

(Are you running as administrator?)

**Comment by obany** [comment]
Indeed that is the case, I was running from a Powershell shell in VSCode, which wasn't admin as far as I knew, but obviously it is.

Running below snippet returns True.
```
$user = [Security.Principal.WindowsIdentity]::GetCurrent();
(New-Object Security.Principal.WindowsPrincipal $user).IsInRole([Security.Principal.WindowsBuiltinRole]::Administrator)  
```

Where as a separate powershell instance returns False.

So finally up and running and able to connect with DevTools 🎉 

I would suggest and addendum to the docs, maybe with that PowerShell snippet to test.

Now if only I could use WebView2 with Edge Chromium support, so I don't have to worry so much about browser quirks 😉

**Comment by nothingismagick** [comment]
Wow, we are definitely so far into the weeds here. And WTF why is VS Code running with administrator rights? That's something that everyone should know about.

**Comment by lucasfernog** [comment]
"tauri info" should show that info then.

**Comment by RahulDas-dev** [comment]
Hi @lucasfernog ,
I face the same issue with and without admin rights.

![image](https://user-images.githubusercontent.com/32712591/104312338-79fc4600-54fc-11eb-9362-314eaf596f91.png)

----

*Kindly check the tauri info*
```

> example1@1.0.0 tauri D:\RUST\tauri\Tauri_Typescript_Template
> tauri "info"

[tauri]: running info

Operating System - Windows_NT(6.1.7601) - win32/ia32

Node.js environment
  Node.js - 12.19.1
  tauri.js - 0.13.0 (outdated, latest: 0.14.0)

Rust environment
  rustc - 1.49.0
  cargo - 1.49.0
  tauri-bundler - 0.9.4

Global packages
  NPM - 6.14.8
  yarn - 1.22.5

App directory structure
/.git
/dist
/node_modules
/src-tauri
/src-ui

App
  tauri.rs - 0.10.0 (outdated, latest: 0.11.0)
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist
  devPath - http://localhost:4000 
```
----

*Kindly Check tauri.conf.json*

```
{
  "build": {
    "distDir": "../dist",
    "devPath": "http://localhost:4000",
    "beforeBuildCommand": ""
  },
  "ctx": {},
  "tauri": {
    "embeddedServer": {
      "active": true
    },
    "bundle": {
      "active": true,
      "targets": "all",
      "identifier": "com.tauri.dev",
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "resources": [],
      "externalBin": [],
      "copyright": "",
      "category": "DeveloperTool",
      "shortDescription": "",
      "longDescription": "",
      "deb": {
        "depends": [],
        "useBootstrapper": false
      },
      "osx": {
        "frameworks": [],
        "minimumSystemVersion": "",
        "useBootstrapper": false
      },
      "exceptionDomain": ""
    },
    "allowlist": {
      "all": true
    },
    "window": {
      "title": "Tauri App",
      "width": 800,
      "height": 600,
      "resizable": true,
      "fullscreen": false
    },
    "security": {
      "csp": "default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'"
    },
    "inliner": {
      "active": true
    }
  }
}
```
[ here is the Git Repo](https://github.com/ParoRahul/Tauri_Typescript_Template)

**Comment by lucasfernog** [comment]
Seems like that's a different issue.
