### ISSUE TITLE
application donot run 

### ISSUE THREAD

**Issue by dhrubrawat66** [tauri-apps/tauri#7810]
### Describe the bug

i create the tauri app with leptos template.
then when i try to run app following bug appear.
![Screenshot 2023-09-11 204405](https://github.com/tauri-apps/tauri/assets/85351405/a9b93336-055b-45fb-9c45-d86cf3097e54)
my tauri.conf.json file as below
![second](https://github.com/tauri-apps/tauri/assets/85351405/e177fe3e-8750-4798-b011-f817d76d85c1)
please help to this problem.

### Platform and versions

```text
os is window 11
tauri-cli 2.0.0-alpha.13
```

**Comment by amrbashir** [comment]
how did you create the project? looks like you want to use the stable version but have the alpha version of the CLI, so you need to install the stable version of the CLI by doing `cargo install tauri-cli`

**Comment by dhrubrawat66** [comment]
> how did you create the project? looks like you want to use the stable version but have the alpha version of the CLI, so you need to install the stable version of the CLI by doing `cargo install tauri-cli`

thank you.
