### ISSUE TITLE
[bug] The Application "vibook" can't be opened. 

### ISSUE THREAD

**Issue by randiekas** [tauri-apps/tauri#7819]
### Describe the bug

![image](https://github.com/tauri-apps/tauri/assets/5701058/c70849dd-75b7-4b52-9665-a89bd3400e93)

I would like to report an issue I am experiencing with my own app "vibook" application. The application runs smoothly on my laptop without any problems. However, when I try to install it on another laptop, I receive the following error message:

Error Message: The Application "vibook" can't be opened.

I have tried several steps, such as uninstalling and reinstalling the application, but this error message continues to appear. I have also ensured that the other laptop meets the necessary specifications and runs a compatible operating system.

I would appreciate assistance in resolving this issue so that I can use the "vibook" application effectively on the other laptop. Thank you!

yarn tauri info:

![image](https://github.com/tauri-apps/tauri/assets/5701058/6341a986-4108-4250-9c87-aa958d5af43b)

### Reproduction

1. open vibook.dmg
2. move vibook to application folder
3. then got error when open the app 

### Platform and versions

```text
tauri info

[✔] Environment
    - OS: Mac OS 12.6.3 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.71.0 (8ede3aae2 2023-07-12)
    ✔ Cargo: 1.71.0 (cfd3bbd8f 2023-06-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 16.18.1
    - yarn: 1.22.19
    - npm: 8.19.2

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
✨  Done in 14.17s.
```

**Comment by JonasKruckenberg** [comment]
Closing in favor or the [discussion](https://github.com/tauri-apps/tauri/discussions/7817)

I suspect this is not an issue with Tauri, but if it turns out it is we can reopen this issue
