### ISSUE TITLE
How to config Android Permissions.

### ISSUE THREAD

**Issue by xiatian12345** [tauri-apps/tauri#7820]
### Describe the bug

This may not a tauri bug!but it confused me a lot of time!

1. I use the tauri + svelte + WebSocket to develop my application
2. The application work fine when developing both mac and android
3. But when i build the signed android apk,it can not connect my websocket server side
4. I suggest it may related to `Android Permission`
5. I add the '<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />' config to src-tauri/gen/android/app/src/main/AndroidManifest.xml and build the new apk
6. Still cannot connect the network

### Reproduction

Android app can not connect the network!

### Expected behavior

websocket can connect the my server

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.72.0 (5680fa18f 2023-08-23)
    ✔ Cargo: 1.72.0 (103a7ff2e 2023-08-15)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 16.16.0
    - pnpm: 8.7.4
    - yarn: 1.22.4
    - npm: 6.14.18

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.13
    - tauri-build [RUST]: 2.0.0-alpha.8
    - wry [RUST]: 0.32.0
    - tao [RUST]: 0.22.2
    - @tauri-apps/api [NPM]: 2.0.0-alpha.1
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.13

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

**Comment by xiatian12345** [comment]
I found may be i should use the plugin of websocket [https://github.com/tauri-apps/plugins-workspace/tree/v2/plugins/websocket](url),but:

1. the plugin of websocket interfaces is big difference to browser native interfaces
2. such as native websocket has 'open , close ,error ,message' events,the puligin of websocket is not support

I am not sure my guess is correct,what should i do next?

**Comment by xiatian12345** [comment]
I also found the plugin of websocket is not support android [https://github.com/tauri-apps/plugins-workspace](url)
So i'm so confused that don't no do what next!

**Comment by xiatian12345** [comment]
i solved it

**Comment by dharanish-v** [comment]
@xiatian12345 how did you solve it ?

**Comment by Konstantin-Dudersky** [comment]
If you're using unsecured HTTP or WS, android blocks. Open access in release mode:

`src-tauri/gen/android/app/build.gradle.kts`

```
android {
    defaultConfig {
        manifestPlaceholders["usesCleartextTraffic"] = "true"
    }
}
```
