### ISSUE TITLE
[bug] webview not found: invalid label or it was closed

### ISSUE THREAD

**Issue by xdewx** [tauri-apps/tauri#7827]
### Describe the bug

in dev mod, after page reload, `getAll` in main window can't find the children windows created before

### Reproduction

1. create child window
2. `ctrl+r` refresh main window
3. `getAll` in main window again
int step 3, `getAll` will not return child window 

### Platform and versions

```text
win 11
```

**Comment by amrbashir** [comment]
duplicate of #5380
