### ISSUE TITLE
[bug] two problems of menus on tauri v2

### ISSUE THREAD

**Issue by percy507** [tauri-apps/tauri#7828]
### Describe the bug

1. **There are three native menus failed to apply custom text.**

    Source code: [click here](https://github.com/percy507/test-tauri-v2/blob/22d67e24ff49cf7a070993c96a01e5d65179a176/src-tauri/src/menu.rs#L18-L35)

<img width="324" alt="image" src="https://github.com/tauri-apps/tauri/assets/18365078/d4457013-e578-4c07-a396-c229912600fb">

2. I change different window's menu bar by listening `WindowEvent::Focused` in `on_window_event`. But re-focus window will make app crashed.

    Source code: [click here](https://github.com/percy507/test-tauri-v2/blob/22d67e24ff49cf7a070993c96a01e5d65179a176/src-tauri/src/main.rs#L17-L25)

```bash
2023-09-13 20:23:15.272 tauri-app[18787:10077111] *** Assertion failure in -[NSMenu dealloc], NSMenu.m:409
thread 'main' panicked at 'Uncaught exception <NSException: 0x12c3aaea0>', /Users/m2/.cargo/registry/src/index.crates.io-6f17d22bba15001f/muda-0.8.7/src/platform_impl/macos/mod.rs:57:25
```

### Reproduction

https://github.com/percy507/test-tauri-v2

### Platform and versions

```text
tauri "info"

[✔] Environment
    - OS: Mac OS 13.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.72.0 (5680fa18f 2023-08-23)
    ✔ Cargo: 1.72.0 (103a7ff2e 2023-08-15)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 16.10.0
    - pnpm: 7.9.5
    - yarn: 1.22.19
    - npm: 7.24.0

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.12
    - tauri-build [RUST]: 2.0.0-alpha.8
    - wry [RUST]: 0.32.0
    - tao [RUST]: 0.22.2
    - @tauri-apps/api [NPM]: 2.0.0-alpha.6
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.12

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by pewsheen** [comment]
Thanks for reporting!

The first one I'm not sure if those texts are controlled by the system. I'll try some ways to find out.
The second problem could be another `autorelease` issue :\

**Comment by pewsheen** [comment]
The first problem is a weird behavior of the macOS that we can't set the title for some system-defined actions. 

This also happened to the electron ([ref](https://github.com/electron/electron/blob/706653d5e4d06922f75aa5621533a16fc34d3a77/shell/browser/ui/cocoa/electron_menu_controller.mm#L62)) and they wrapped it with another custom action to avoid that.

I also found that if we are using [`attributedTitle`](https://developer.apple.com/documentation/appkit/nsmenuitem/1514860-attributedtitle?language=objc) then the title will be changed to what we provide, but I'm not sure what would be the side-effect.

@amrbashir How do you think?

**Comment by amrbashir** [comment]
@pewsheen lets use a custom selector then like electron.

**Comment by pewsheen** [comment]
> @pewsheen lets use a custom selector then like electron.

I just know why macOS is controlling these items 🥲 

Redo and undo are controlled by the window's `NSUndoManager`. Those items' titles are localized by the system and changed depending on the step's action name, like "Typing", "Delete", or "Copy" and become "Undo Typing / Delete / Copy". Also, the item's enabled state is controlled by the UndoManager as well. The undo/redo buttons are enabled or disabled corresponding to the action state registered in the UndoManager.

`toggleFullScreen` has similar behavior. When the window is entered full-screen mode, the title will be changed to "Exit Full Screen".

If we want to wrap these methods, each time we set a new title for the menu item we need to create a subclass of `NSUndoManager` and override the title methods, and then replace the window's UndoManager with this new one.

**Comment by amrbashir** [comment]
I'd say go with what you feel best and then we can discuss your approach in the PR other than speculating here.

**Comment by percy507** [comment]
The first bug seems have been fixed. (Test on tauri `2.0.0-alpha.20`)

The second bug I open a new issue. https://github.com/tauri-apps/tauri/issues/8465
