### ISSUE TITLE
[bug] Build Script Triggers Norton Antivirus

### ISSUE THREAD

**Issue by chris-tietgen** [tauri-apps/tauri#7829]
### Describe the bug

Every time I create a NEW Tauri project and run either of the following commands it triggers my Norton Antivirus (see below).

`npm run tauri dev`

`npm run tauri build`

![image](https://github.com/tauri-apps/tauri/assets/23318158/d7b3c27c-3ced-4c89-8aa4-499cbf9f05bb)

This seems to only happen once per project for DEV and BUILD.

Is there a way I can prevent this because every time it pops up multiple Norton AV warning messages. The path to the EXE has a hashed folder name, so I can't add an exclusion for the EXE globally using that path.

### Reproduction

- I used both the Vanilla JS and SvelteKit "Get Started" projects and ran into this issue.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 116.0.1938.76
    ✔ MSVC: Visual Studio Professional 2022
    ✔ rustc: 1.72.0 (5680fa18f 2023-08-23)
    ✔ Cargo: 1.72.0 (103a7ff2e 2023-08-15)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.17.1
    - npm: 10.0.0

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../src
    - devPath: ../src
    - bundler: Vite
```

**Comment by amrbashir** [comment]
This is just a false positive. Build scripts are just rust files that are compiled on your system and ran by Cargo before compiling a dependency.

**Comment by chris-tietgen** [comment]
Yeah, I get that it's a false positive. I just don't want to close 2-4 Norton popups when I build new projects.

**Comment by amrbashir** [comment]
Unfortunately that's out of our hands, you need to configure norton to ignore your dev directory or something.
