### ISSUE TITLE
[feat] Expose Always on Bottom

### ISSUE THREAD

**Issue by KingRainbow44** [tauri-apps/tauri#7847]
### Describe the problem

I'm making an underlay application where I want it to be always on the user's desktop.

### Describe the solution you'd like

I want the [always_on_bottom](https://docs.rs/tauri-runtime-wry/latest/tauri_runtime_wry/struct.Window.html#method.set_always_on_bottom) `wry` method to be exposed to Tauri.

**Comment by FabianLars** [comment]
(re-opening in case others would like to see this added)

**Comment by Cioraz** [comment]
Hey, I would like to work on this issue.
Correct me if im wrong, but basically you want to add a feature to always keep the application on the users desktop?
