### ISSUE TITLE
[feat] auto decompose response

### ISSUE THREAD

**Issue by lianjindata** [tauri-apps/tauri#7852]
### Describe the problem

When server responses a file like test.json.gz, ResponseType.JSON can't decode it. A former version(before June) works, but I can't figure it out.

### Describe the solution you'd like

Auto decompose response file.

**Comment by amrbashir** [comment]
Could you please provide more info about the problem and a reproducible example, also `tauri info` ouput and if possible which version used to work for you.

**Comment by lianjindata** [comment]
``` js
// this is the origin code that used to work
import { ResponseType, Body, fetch } from '@tauri-apps/api/http';

async function test() {
  const url = 'http://127.0.0.1/test.json'  // server will response precompressed gzip version of the file.
  const response = await fetch(url, {
    method: 'GET',
    timeout: 30,
    responseType: ResponseType.JSON,
  });
  return response.data;
}
```

``` js
// now I have to add some parse code to make it works
import { ResponseType, Body, fetch } from '@tauri-apps/api/http';

async function test() {
  const url = 'http://127.0.0.1/test.json' // server will response precompressed gzip version of the file.
  const response = await fetch(url, {
    method: 'GET',
    timeout: 30,
    responseType: ResponseType.Binary,
    headers: { 'Accept-Encoding': 'gzip' },
  });

  const data = JSON.parse(inflate(response.data, { to: 'string' }));
  return data;
}
```

```
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 117.0.2045.36
    ✔ MSVC: Visual Studio Community 2019
    ✔ rustc: 1.72.0 (5680fa18f 2023-08-23)
    ✔ Cargo: 1.72.0 (103a7ff2e 2023-08-15)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.14.2
    - yarn: 1.22.19
    - npm: 9.6.2

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist/spa
    - devPath: http://localhost:9000/
    - framework: Vue.js (Quasar)
    - bundler: Vite
Done in 7.87s.
```

The version of tauri is about 1.3 when it worked. After I upgrade to current version, it doesn't work, and degradation doesn't work also.

**Comment by FabianLars** [comment]
Can you add this to the dependencies section in `src-tauri/Cargo.toml` and try again?
```toml
reqwest = { version = "0.11", features = ["brotli", "gzip", "deflate"] }
```

Edit: Actually, after re-reading your message i'm not sure if that will change anything if it works after you add Accept-Encoding 🤔

**Comment by lianjindata** [comment]
> Can you add this to the dependencies section in `src-tauri/Cargo.toml` and try again?
> 
> ```toml
> reqwest = { version = "0.11", features = ["brotli", "gzip", "deflate"] }
> ```
> 
> Edit: Actually, after re-reading your message i'm not sure if that will change anything if it works after you add Accept-Encoding 🤔

Thanks, it works.
