### ISSUE TITLE
Changing Submenu Titles During Runtime

### ISSUE THREAD

**Issue by FrankLaterza** [tauri-apps/tauri#7854]
### Describe the problem

Menu titles are easy to change with the menu handle, but submenu titles aren't changeable using the menu handle.

### Describe the solution you'd like

Menu titles are hashed and stored allowing the menu handle to change the title names during runtime. An implementation of this for submenus titles would be a helpful feature. This may require including an ID when creating new submenus.

### Alternatives considered

It is also possible to create your own menu in the front end, but the idea of a standardized menu system for all platforms is a worthy feature.

**Comment by amrbashir** [comment]
This will be available in v2, for v1, you'll need to re-create the submenu.
