### ISSUE TITLE
[bug] tauri-driver and edgedriver 117 lead to Selenium error "only ASCIIZ protocol mode is supported"

### ISSUE THREAD

**Issue by Nickog13** [tauri-apps/tauri#7865]
### Describe the bug

Hi All,

I am getting an error with the Tauri Selenium test example and also with another Selenium + Tauri project.
I have run the Tauri Selenium example project successfully with edgedriver version 112, 114, 115. with the corresponding edge version installed.
Now with edgedriver 117 (current stable version) the setup throws this error "_WebDriverError: unknown error: only ASCIIZ protocol mode is supported_".

I have already checked this edgedriver version with Selenium and the usual edge browser instead of a Tauri application as application - no issue.
So I believe there might be something wrong with the tauri-driver in combination with the edgedriver version.
Can someone check and take a look whether the Tauri Selenium example still works with the latest stable edgedriver version (117) or if there is indeed a bug in tauri-driver?

And please let me know if I should provide further information.

Best regards
Nick

### Reproduction

1. Fetch Selenium Tauri sample project from the tauri page or from here [(https://github.com/chippers/hello_tauri)](https://github.com/chippers/hello_tauri)
2. Build application to be tested, e.g. cargo build --release
3. In .\webdriver\selenium\test\test.js I replaced the 'localhost' in the _usingServer()_ call with '127.0.0.1'
4. For the tauri-driver spawn call I also added the parameter ['--native-driver', 'msedgedriver.exe'] (edgedriver 117 version)
5. Run test (yarn test)

### Expected behavior

Application is started successfully and the tests are executed

### Platform and versions

```text
tauri-driver version 0.1.2
```

### Stack trace

```text
WebDriverError: unknown error: only ASCIIZ protocol mode is supported
    at Object.throwDecodedError (C:\Users\10052173\Desktop\hello_tauri-main\webdriver\node_modules\selenium-webdriver\lib\error.js:517:15)
    at parseHttpResponse (C:\Users\10052173\Desktop\hello_tauri-main\webdriver\node_modules\selenium-webdriver\lib\http.js:642:13)
    at Executor.execute (C:\Users\10052173\Desktop\hello_tauri-main\webdriver\node_modules\selenium-webdriver\lib\http.js:568:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by aleenadavy90** [comment]
encountered same error with edge browser & driver version 117

**Comment by Nickog13** [comment]
Issue is fixed with EdgeDriver version >120. There was an issue in edgedriver
[https://github.com/MicrosoftEdge/EdgeWebDriver/issues/116](https://github.com/MicrosoftEdge/EdgeWebDriver/issues/116)
