### ISSUE TITLE
[bug] how to use path  require('path')

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [tauri-apps/tauri#7883]
### Describe the bug

I am using a library called Cesium in Node.js, which uses require('path'). However, Tauri does not have __dirname or the path module. What should I do?

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 117.0.2045.31
    ✔ MSVC: Visual Studio ���ɹ��� 2022
    ✔ rustc: 1.71.1 (eb26296b5 2023-08-03)
    ✔ Cargo: 1.71.1 (7f1d04c00 2023-07-29)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.16.1
    - pnpm: 8.6.9
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by amrbashir** [comment]
Tauri doesn't have a Node.js runtime and so `__dirname` and node's `path` module are not available. Think of tauri as another browser environment, if it works in the browser it should work in tauri.

quickly looking over cesium pacakge.json they seem to be providing a CJS and ESM imports, so if you're using `require("cesium")`, I'd suggest trying to change that to `import cesium from "cesium"`
