### ISSUE TITLE
[bug] error: linker `lld` not found

### ISSUE THREAD

**Issue by mikaljo** [tauri-apps/tauri#7885]
### Describe the bug

After installing Tauri as instructed in the Getting Started guide and installing `tauri-cli` with cargo,  running `cargo tauri build` outputs:
```
   Compiling proc-macro2 v1.0.67
   Compiling unicode-ident v1.0.12
error: linker `lld` not found
  |
  = note: program not found

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that Visual Studio 2017 or later, or Build Tools for Visual Studio were installed with the Visual C++ option.

note: VS Code is a different product, and is not sufficient.

   Compiling cfg-if v1.0.0
error: could not compile `proc-macro2` (build script) due to previous error
warning: build failed, waiting for other jobs to finish...
```
Visual Studio 2022 and the Build Tools for Visual Studio are installed. Using the Developer Command Prompt gives the same output, even though `link.exe` is clearly available. Reinstalling or rebooting doesn't fix the issue.

### Reproduction

1. Install Tauri on Windows.
2. Ensure Visual Studio and Build Tools are installed correctly.
3. Run `cargo tauri build`.

### Expected behavior

Tauri finds the build tools and continues building.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 117.0.2045.31
    ✔ MSVC:
        - Visual Studio Build Tools 2022
        - Visual Studio Community 2022
    ✔ rustc: 1.72.1 (d5c2e9c34 2023-09-13)
    ✔ Cargo: 1.72.1 (103a7ff2e 2023-08-15)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../ui
    - devPath: ../ui
```

**Comment by FabianLars** [comment]
My first guess would be that only the build tools _or_ vs community is in scope of the terminal with the c++ payload just being installed in the other one, could you check that?
To be clear, you don't need VS _and_ the build tools, you can use either one since both have the necessary components available.

**Comment by mikaljo** [comment]
I've uninstalled both, reinstalled only the build tools, and rebooted, but get the same error. After removing Rust and every Rust related directory/tool I could find, and reinstalling Rust, it works. I assume this is a problem with Rust rather than Tauri.

**Comment by Prasannajaga** [comment]
@mikaljo  how did u solved it , getting the same error
