### ISSUE TITLE
[bug] What size should the icon use? 1024x1024px or  1240x1240px?

### ISSUE THREAD

**Issue by jeffy5** [tauri-apps/tauri#7886]
### Describe the bug

As the [official document](https://tauri.app/v1/guides/features/icons#command-usage) demonstrate, which print the icon size is 1024x1024px. 

But I found that is 1240x1240px when I run the command in my computer.

 And I found the [source code](https://github.com/tauri-apps/tauri/blob/deea9436261f651188e0bc86104779bf30029c32/tooling/cli/src/icon.rs#L48C12-L48C26) is also 1240px, and there is a TODO marks "Confirm 1240px"

### Reproduction

Run command `npm run tauri icon -h` in terminal.

### Expected behavior

Documentation should be consistent with the actual cli execution prompts, otherwise it will confuse users.

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.71.0 (8ede3aae2 2023-07-12)
    ✔ Cargo: 1.71.0 (cfd3bbd8f 2023-06-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 16.20.1
    - pnpm: 7.14.1
    - yarn: 1.22.17
    - npm: 8.19.4

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../out
    - devPath: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Webpack
```

**Comment by FabianLars** [comment]
1024 is correct. 1240 was a typo in the old implementation of the icon command which I copied over into the new implementation because we weren't sure if it was a typo back then.

So the documentation is correct, just gonna update the code comment :)

Thanks for bringing this to our attention!

**Comment by jeffy5** [comment]
I got it, thanks for your answer.
