### ISSUE TITLE
[docs] zh-CN getting-started description Error!

### ISSUE THREAD

**Issue by Mt-Youya** [tauri-apps/tauri#7887]
![image](https://github.com/tauri-apps/tauri/assets/57708498/03493b0d-938f-42f7-8e50-dc5f6011ead5)
" 它为原生 HTML/CSS/JavaScript 及如 React、Svelte 和 Yew 一类的框架提供了脚手架模板。"  should be " 它为原生 HTML/CSS/JavaScript 及如 React、Svelte 和 Vue 一类的框架提供了脚手架模板。"

**Comment by Mt-Youya** [comment]
Yew  ==> Vue ?

**Comment by FabianLars** [comment]
That's indeed intentional and is also present on the other language pages. Yew is a rust-based frontend framework.

Thanks for reaching out though!!
