### ISSUE TITLE
[bug] when modify svelte file and save it , tauri log duplicate,old svelte file is cached and be run!

### ISSUE THREAD

**Issue by xiatian12345** [tauri-apps/tauri#7889]
### Describe the bug

when modify the ChatRoute.svelte file and save it , tauri log duplicate, and old svelte file is cached and be run!

09-22 20:56:59.066 25989 25989 I Tauri/Console: File: http://tauri.localhost/src/routes/ChatRoute.svelte - Line 269 - Msg: kkk onBlur
09-22 20:56:59.067 25989 25989 I Tauri/Console: File: http://tauri.localhost/src/routes/ChatRoute.svelte - Line 245 - Msg: Android keyboard exit2
09-22 20:56:59.068 25989 25989 I Tauri/Console: File: http://tauri.localhost/src/routes/ChatRoute.svelte?t=1695386546100 - Line 269 - Msg: kkk onBlur
09-22 20:56:59.068 25989 25989 I Tauri/Console: File: http://tauri.localhost/src/routes/ChatRoute.svelte?t=1695386546100 - Line 245 - Msg: Android keyboard exit2
09-22 20:56:59.068 25989 25989 I Tauri/Console: File: http://tauri.localhost/src/routes/ChatRoute.svelte?t=1695386570693 - Line 269 - Msg: kkk onBlur
09-22 20:56:59.068 25989 25989 I Tauri/Console: File: http://tauri.localhost/src/routes/ChatRoute.svelte?t=1695386570693 - Line 245 - Msg: Android keyboard exit2
09-22 20:56:59.068 25989 25989 I Tauri/Console: File: http://tauri.localhost/src/routes/ChatRoute.svelte?t=1695387039174 - Line 269 - Msg: input onBlur
09-22 20:56:59.069 25989 25989 I Tauri/Console: File: http://tauri.localhost/src/routes/ChatRoute.svelte?t=1695387039174 - Line 245 - Msg: Android keyboard exit1
09-22 20:56:59.069 25989 25989 I Tauri/Console: File: http://tauri.localhost/src/routes/ChatRoute.svelte?t=1695387399206 - Line 269 - Msg: input onBlur
09-22 20:56:59.069 25989 25989 I Tauri/Console: File: http://tauri.localhost/src/routes/ChatRoute.svelte?t=1695387399206 - Line 245 - Msg: Android keyboard exit1
09-22 20:56:59.069 25989 25989 I Tauri/Console: File: http://tauri.localhost/src/routes/ChatRoute.svelte?t=1695387400735 - Line 269 - Msg: input onBlur
09-22 20:56:59.069 25989 25989 I Tauri/Console: File: http://tauri.localhost/src/routes/ChatRoute.svelte?t=1695387400735 - Line 245 - Msg: Android keyboard exit1

### Expected behavior

the old cached file should not be loaded and only the newest file can be loaded!!!

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.72.0 (5680fa18f 2023-08-23)
    ✔ Cargo: 1.72.0 (103a7ff2e 2023-08-15)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 16.16.0
    - pnpm: 8.7.4
    - yarn: 1.22.4
    - npm: 6.14.18

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.14
    - tauri-build [RUST]: 2.0.0-alpha.8
    - wry [RUST]: 0.33.0
    - tao [RUST]: 0.22.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.14

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

**Comment by amrbashir** [comment]
We should probably avoid caching in the dev server proxy on Android
