### ISSUE TITLE
[bug] Opening a new window via the anchor tag results in ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by ryoha000** [tauri-apps/tauri#7893]
### Describe the bug

When an anchor tag in the app is opened as a new window, e.g. by middle mouse click, it goes to connect to https://tauri.localhost/ and the connection is refused.
This bug only occurs after a production build. (Probably because we build a local server during development.)

### Reproduction

repository as the minimum configuration for reproduction.
after `npm create tauri-app@latest`, I just reflected the contents of [this commit](https://github.com/ryoha000/tauri-reproduce-refused-connection/commit/989f40bbc87354ec568c05c9bd6a8ef59cfd0851)
The production build artifacts are placed in releases.

https://github.com/ryoha000/tauri-reproduce-refused-connection

### Expected behavior

The application opens.

### Platform and versions

```text
> tauri-reproduce-refused-connection@0.0.0 tauri
> tauri info


[✔] Environment
    - OS: Windows 10.0.22000 X64
    ✔ WebView2: 117.0.2045.36
    ✔ MSVC:
        - Visual Studio Build Tools 2019
        - Visual Studio Build Tools 2022
        - Visual Studio Community 2019
        - Visual Studio Community 2022
    ✔ rustc: 1.72.1 (d5c2e9c34 2023-09-13)
    ✔ Cargo: 1.72.1 (103a7ff2e 2023-08-15)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.15.0
    - pnpm: 7.29.1
    - yarn: 1.22.19
    - npm: 9.2.0

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by lucasfernog** [comment]
`Open link in a new window` shouldn't even be visible tbh.. your app URL is only accessible INSIDE your app, and when you click "open link in a new window" it'll try to open that URL in the browser... I'd recommend using a button instead of a link in this case (seems like there's no way to disable it).

**Comment by lucasfernog** [comment]
alternatively we'd need to implement https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.2592.51#add_newwindowrequested

(which is available for latest wry, but not backported to v1)
