### ISSUE TITLE
[bug] JS API -- Specifying a path with spaces using new Command() causes the path to be terminated early.

### ISSUE THREAD

**Issue by wearrrrr** [tauri-apps/tauri#7914]
### Describe the bug

I am trying to reference the path `C:\Users\wearr\AppData\Roaming\dev.wearr.9launcher\bin\x64\Release SDL2\dosbox-x.exe` using new Command(), however when the command is executed with the spawn() method, it will try and reference C:\Users\wearr\AppData\Roaming\dev.wearr.9launcher\bin\x64\Release as the path to run. Specifically here is the code I am using to replicate this bug. 
```
let command = new Command("cmd", ["/C", `${await path.appDataDir() + 'bin\\x64\\Release SDL2\\dosbox-x.exe'}`, "-set", "machine=pc98", "-c", `IMGMOUNT A: ${gamePath}`, "-c", "A:", "-c", "game", "-nopromptfolder"])
command?.on('error', error => console.error(`command error: "${error}"`));
command?.stdout.on('data', line => console.log(`command stdout: "${line}"`));
command?.stderr.on('data', line => console.log(`command stderr: "${line}"`));
const child = await command?.spawn();
```

### Reproduction

```
let command = new Command("cmd" ["/C", <PATH WITH SPACES IN IT>]);
command.spawn();
```

### Expected behavior

The program is run despite the path having spaces in it

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19044 X64
    ✔ WebView2: 117.0.2045.43
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.72.1 (d5c2e9c34 2023-09-13)
    ✔ Cargo: 1.72.1 (103a7ff2e 2023-08-15)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.16.0
    - yarn: 1.22.19
    - npm: 9.8.1

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - bundler: Vite
```

### Stack trace

```text
N/A (Error has no stack trace)
```

### Additional context

I haven't confirmed, but this likely isn't an issue with the rust side of Tauri, it seems to either be down to how shell.Command determines if a path has ended or not.

**Comment by wearrrrr** [comment]
I updated the rust side of tauri just to confirm, because I noticed it was outdated, however that did not fix the issue. If it helps at all, here is my console output 
![image](https://github.com/tauri-apps/tauri/assets/99224452/a911c77e-d0bb-477c-b165-daf8f60ce866)

and here is the new tauri info after updating. 

```
[✔] Environment
    - OS: Windows 10.0.19044 X64
    ✔ WebView2: 117.0.2045.43
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.72.1 (d5c2e9c34 2023-09-13)
    ✔ Cargo: 1.72.1 (103a7ff2e 2023-08-15)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.16.0
    - yarn: 1.22.19
    - npm: 9.8.1

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - bundler: Vite
```

**Comment by wearrrrr** [comment]
In the latest versions of tauri, this is still a very prevalent bug!! It causes a ton of issues especially when trying to reference something from C:\Program Files\, and it will just try and execute from C:\Program and fail.

**Comment by FabianLars** [comment]
Did you try wrapping the path (or the whole argument you input into `/C`) in `""`? Your current code translates to this cli command
`cmd.exe /C C:\Program Files\abc` which wouldn't work if you write it by hand in the terminal either, it needs to be more like this: `cmd.exe /C "C:\Program Files\abc"`

**Comment by wearrrrr** [comment]
I didn't in the reproduction code, but I remember it not working when I did that either, Ill try again in a couple minutes!

**Comment by wearrrrr** [comment]
Seems to work now in the newer versions of tauri, issue seems good to close! :)
