### ISSUE TITLE
[bug] Update infinite loop in Windows

### ISSUE THREAD

**Issue by qlaffont** [tauri-apps/tauri#7916]
### Describe the bug

When I release a new version of my application some of my Windows users have an issue where updating app :
- When they start the process of update, they install the new version but the modal is still open after install telling to update the app !
- The previous version is not uninstalled (1.1.6 was before / 1.1.7 was the newest)

![image](https://github.com/tauri-apps/tauri/assets/10044790/cea219c7-0f56-4847-b937-529cf6de1914)

### Reproduction

- You have the code here : https://github.com/qlaffont/lestudio-app
- Download release version to 1.1.6
- Launch it
- Accept update
- Infinite update bug

### Expected behavior

Install the update once

### Platform and versions

```text
It's a production env who use a prod release. So I can't execute this command.

But this is what I have on my dev setup:
➜  lestudio-app git:(master) pnpm tauri info    

[✔] Environment
    - OS: Pop!_OS 22.04 X64
    ✔ webkit2gtk-4.0: 2.40.5
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.72.0 (5680fa18f 2023-08-23)
    ✔ Cargo: 1.72.0 (103a7ff2e 2023-08-15)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 18.15.0
    - pnpm: 7.24.3
    - yarn: 1.22.19
    - npm: 10.1.0

[-] Packages
    - tauri [RUST]: 1.4.0
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.1
    - tao [RUST]: 0.16.0
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
    - distDir: Injected by vite-plugin-tauri
    - devPath: 127.0.0.1:5173
    - framework: SolidJS
    - bundler: Vite
```

### Stack trace

```text
None in console
```

### Additional context

I have a VM if needed who host a Windows 11 with the production release who have the issue

**Comment by qlaffont** [comment]
Maybe it's due to single instance plugin ?

**Comment by FabianLars** [comment]
Did you maybe mix up setup.exe and the msi ? Your latest.json points to the msi installer so if you installed 1.1.6 via setup.exe then it won't work as expected.

**Comment by qlaffont** [comment]
No at all I have used the exe

**Comment by qlaffont** [comment]
the latest.json is generate by tauri action. Maybe a bug from it ?

**Comment by qlaffont** [comment]
Yes it seems that installed with msi file it's working I will inform all of them. Maybe remove on tauri action exe if it can issue some bugs with updater ?

**Comment by FabianLars** [comment]
> Maybe remove on tauri action exe if it can issue some bugs with updater ?

We're not aware of any general bugs as long as you don't use both formats at the same time. (upgrading from msi to exe should work though, may need v1.5 for the latest bug fixes)

You can also tell the action to prefer nsis (setup.exe) for latest.json: <https://github.com/tauri-apps/tauri-action/#build-options>. This will also be the default for tauri v2.
