### ISSUE TITLE
Multipart upload to AWS S3 via Tauri HTTP API is challenging (and may not be possible with Blobs?)

### ISSUE THREAD

**Issue by MGough** [tauri-apps/tauri#7922]
Tauri v1.4 with `"http-multipart"` and `"reqwest-client"` enabled.

Trying to use Tauri's HTTP API for uploading a file to S3 has a few challenges. This isn't S3 specific though, it's just an example of the issue.

### Body.form() item ordering
When sending multipart form data to S3, AWS requires that the `file` key is the last element in the HTTP request body ([See AWS Docs](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html) - 'When constructing your request, make sure that the file field is the last field in the form.').

When using the browser `FormData` this is fine, as in modern javascript the order of insertion is maintained, so you just add the `file` key last:
```ts
  Object.keys(fieldsFromS3).forEach((key) => {
    formData.append(key, fieldsFromS3[key]);
  });

  if (file || fileName) {
    formData.append("file", file, fileName);
  }
```

However when using `Body.form({ ...fieldsFromS3, file })` it appears the order is not maintained, nor specifiable. [Looks like the rust side is just using a HashMap which doesn't maintain the ordering](https://github.com/tauri-apps/tauri/blob/c001a91d15fa363dad2a231cfe06d77e82b6460d/core/tauri/src/api/http.rs#L255)

The first time I ran this it was fine, however subsuquent attempts I realised (with help of a MITM proxy) that it was shuffling the form key order.

This may seem minor particularly as `FormData()` can handle it fine, and _could_ just be a documentation issue, however...

### FormData throws 'no such file or directory' error
So trying to avoid the use of `Body.form` and sticking to the general approach of using the browser built in.

The challenge here is that code like this has an undesirable side effect:
```ts
  const fileName = "myBlob";
  const someDataToUpload = new Blob(["some data"]);
  const formData = new FormData();

  Object.keys(uploadFields).forEach((key) => {
    formData.append(key, uploadFields[key]);
  });

  formData.append("file", someDataToUpload, fileName);

   const s3Result = await fetch(uploadUrl, {
     method: "POST",
     body: Body.form(formData),
     headers: {
        "content-type": "multipart/form-data",
     },
   });
```
However something strange happens with `fileName`. It doesn't refer to an actual file, as we're using a `Blob`, but unless `myBlob` is in the `fs` scope:
```
      "fs": {
        "scope": ["myBlob"]
       }
```
Then an error will occur due to it not being in scope (`Unhandled Promise Rejection: path not allowed on the configured scope: myBlob`). However adding it to scope doesn't fix the issue, as it then throws an error as the file or directory does not exist (`Unhandled Promise Rejection: No such file or directory (os error 2)`). 

It seems like the tauri side is trying to do some inspection on this file path assuming that it is a real file rather than just a filename being provided to S3.

I appreciate there are ways to do this using the native browser fetch, and the only real benefit to the tauri fetch here may be CORS (or in some cases handling of native system proxies), so this may not be particularly high priority. But it is a bit of an undocumented rabbit hole where things don't work as you'd expect.

**Comment by moranbw** [comment]
The AWS Rust SDK is stable now, might be more reliable to just use that in a Rust Command? https://github.com/awslabs/aws-sdk-rust/blob/main/examples/examples/s3/src/bin/s3-multipart-upload.rs

**Comment by drdevelop** [comment]
I have the same problem, hope it will be solved as soon as possible @zeenix @damien @zuckschwerdt

**Comment by FabianLars** [comment]
@drdevelop please do not ping ranom people

**Comment by FabianLars** [comment]
For the first issue (key order), could you try the `fix/http-body-order` branch please? ([guide](https://tauri.app/v1/guides/faq#how-can-i-use-unpublished-tauri-changes) - only the tauri core crate is needed)

**Comment by FabianLars** [comment]
About the second error, does it work if you manually convert the Blob to `number[]` ?

**Comment by asadahimeka** [comment]
> For the first issue (key order), could you try the `fix/http-body-order` branch please? ([guide](https://tauri.app/v1/guides/faq#how-can-i-use-unpublished-tauri-changes) - only the tauri core crate is needed)

It works for me. Thank you for your fix.
![2024-1-9 22-41-29](https://github.com/tauri-apps/tauri/assets/31837214/dd5ae492-e88c-4ffb-8c9d-6e0d36bc95da)
