### ISSUE TITLE
[bug] NSIS updater not working out of the box 

### ISSUE THREAD

**Issue by makinori** [tauri-apps/tauri#7931]
### Describe the bug

I set up the updater for nsis with all the default settings. When launching, I get the notification for an update, pressing yes, a cmd terminal window appears and then the entire program closes.

I've tried using msi instead and the problem disappeared. I'm also making appimage builds and that's working fine too. I don't know how to get any debug info why it's failing. I've tried different physical machines too all on windows 11. 

https://github.com/tauri-apps/tauri/assets/8362329/6baeb760-07b2-441c-9db5-d4eaf29b2f41

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 117.0.2045.43
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.72.1 (d5c2e9c34 2023-09-13)
    ✔ Cargo: 1.72.1 (103a7ff2e 2023-08-15)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.18.0
    - yarn: 1.22.19
    - npm: 9.8.1

[-] Packages
    - tauri [RUST]: 1.5.0
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.3
    - tauri-cli [RUST]: not installed!
    - @tauri-apps/api [NPM]: 1.5.0
    - @tauri-apps/cli [NPM]: 1.5.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Hey 👋 Did you try it with debug builds (`tauri build --debug`) for both versions? If you then change your main function to something like this, it _may_ give you some more info.
```rs
tauri::Builder::default()
  .build(tauri::generate_context!()) // build instead of run
  .expect("error while building application")
  .run(|_, e| match e {
    tauri::RunEvent::Updater(event) => { dbg!(event); },
      _ => (),
  });
```

Maybe you have to start the exe from inside a terminal so the spawned console doesn't close when it's restarting.

Edit: And if that doesn't help, a minimal reproduction may be nice (or your repo if it's public). I just tried it again in my own app and didn't see any issues.

**Comment by makinori** [comment]
@FabianLars Thank you so much for the quick response. I haven't had the chance to learn Rust much yet so I wasn't too sure about modifying main.rs.

I figured out the issue! I had a space character in `package.productName` in `tauri.conf.json`. This wasn't an issue with AppImage but it is with nsis. I also think it's not an issue with msi.

Thank you again~ I'd send a pr if I knew more Rust. Perhaps the docs could be updated, however I think I did use spaces in names with electron in the past, so I'm not sure if its intended or not.

**Comment by amrbashir** [comment]
@makidrone what tipped you off about `package.productName` did you see any errors? this is a bug and needs to be fixed

**Comment by makinori** [comment]
ah yeah it is an issue. the desktop shortcut and entry in installed applications uses product name, and they should be capitalized without dashes. here's the error. filename starts with `Mechanyx Coil`

![Screenshot from 2023-10-04 13-52-11](https://github.com/tauri-apps/tauri/assets/8362329/2afd5524-10a7-4d75-a13b-a0d11cb88533)

i suppose i could change the setup filename and release json in the meantime. seems to just be related to opening the setup

**Comment by amrbashir** [comment]
Thank you that is very helpful, I see where the issue is, will open a PR soon.

**Comment by amrbashir** [comment]
Oh @FabianLars already made a PR 🚀
