### ISSUE TITLE
[bug] window is not defined when using 'convertFileSrc' in unit test

### ISSUE THREAD

**Issue by jclaessens97** [tauri-apps/tauri#7935]
### Describe the bug

I can't find anything about it in the changelog, but starting from tauri v1.5.0, I get `ReferenceError: window is not defined` when using `convertFileSrc` in a unit test. 

### Reproduction

1) Create unit test - I used vitest
2) Call function from my own code that contains `convertFileSrc` and test is inside the unit test

### Expected behavior

I would expect that this still works as it did `v1.3.0` and `v1.4.0`

### Platform and versions

```text
pnpm tauri info

[✔] Environment
    - OS: Mac OS 14.0.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.72.1 (d5c2e9c34 2023-09-13)
    ✔ Cargo: 1.72.1 (103a7ff2e 2023-08-15)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 18.16.0
    - pnpm: 8.8.0
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.1
    - tauri-cli [RUST]: not installed!
    - @tauri-apps/api [NPM]: 1.5.0
    - @tauri-apps/cli [NPM]: 1.5.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../.output/public
    - devPath: http://localhost:8081/
    - framework: Vue.js (Nuxt)
    - bundler: Vite
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by amrbashir** [comment]
Seems like a regression but are you using the `mocks` module?

**Comment by jclaessens97** [comment]
I'm not using the `mocks` module no.

Edit: @amrbashir , I tried running `mockWindows` inside my vitest, and it also gives the same `ReferenceError: window is not defined` but then inside the `mockWindows` function.

**Comment by jclaessens97** [comment]
I compared `tauri-v1.4.0` and `tauri-v1.5.0` tags and noticed the following:

<img width="1706" alt="image" src="https://github.com/tauri-apps/tauri/assets/10177148/d86c9ebb-3c9e-4447-ace4-e48b182b4392">

<img width="1709" alt="image" src="https://github.com/tauri-apps/tauri/assets/10177148/e79599e6-4ede-4569-a0cc-5647e8db7d0d">

**Comment by amrbashir** [comment]
alright, so for unit testing, you need to use the mocks module, I will update the `mocks` module to properly mock the `window.__TAURI__.convertFileSrc`

**Comment by jclaessens97** [comment]
I looked at the `mocks` module, but I don't immediately see how I should use it to mock the `convertSrcUrl`, or did you mean that you will add a new function to do so?

**Comment by amrbashir** [comment]
yeah, we need to add mock for it in the npm pacakge.

**Comment by amrbashir** [comment]
btw, you can include this mock in your tests until the next release
```js
function mockConvertFileSrc(
  osName: string,
  windowsProtocolScheme = 'https'
) {
  window.__TAURI__.convertFileSrc = function (filePath, protocol = 'asset') {
    const path = encodeURIComponent(filePath)
    return osName === 'windows'
      ? `${windowsProtocolScheme}://${protocol}.localhost/${path}`
      : `${protocol}://localhost/${path}`
  }
}
```

**Comment by jclaessens97** [comment]
I also had to add ` window.__TAURI__ = window.__TAURI__ || {};` before assigning `convertFileSrc` like so:

```typescript
function mockConvertFileSrc(
  osName: string,
  windowsProtocolScheme = 'https',
) {
  window.__TAURI__ = window.__TAURI__ || {};
  window.__TAURI__.convertFileSrc = function (filePath, protocol = 'asset') {
    const path = encodeURIComponent(filePath);
    return osName === 'windows'
      ? `${windowsProtocolScheme}://${protocol}.localhost/${path}`
      : `${protocol}://localhost/${path}`;
  };
}
```

And then for my test environment (I use vitest), I also had to configure it to use `jsdom` instead of the default:

```typescript
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'jsdom',
  },
});
```

I just added this for completeness when other people are also try to look up something simular 😄 


Thanks, @amrbashir!
