### ISSUE TITLE
Sveltekit testing, android fetch not working.

### ISSUE THREAD

**Issue by nas-me** [tauri-apps/tauri#7947]
**Is your feature request related to a problem?

Unable to fetch data with android.

Data is fetched in ios if the codes live in a .svelte file.

Note that fetching data from a graphql api works fine in desktop mode for codes in .server file (the main project is a ssr pwa configured to work as a spa with adapter static / ssr disabled and prerender on)

**Describe the solution you'd like**

Behave like the desktop app to have the same base for multiplatform dev.

.server.ts files contain actions that works on desktop

**Describe alternatives you've considered**

**Would you want to assign yourself to implement this feature?**
- [ ] Yes
- [ ] No

**Additional context**

**Comment by amrbashir** [comment]
Please provide a minimal reproducible repo, also try building for release to see if it is just an issue with development mode.

**Comment by nas-me** [comment]
Thanks for the reply, awesome project.

I will test with the release as you suggested and share the result.

Note that ios (dev) fetch from the graphql api only when codes live on a .svelte file unlike the desktop who work like a charm with .server.ts (adapter-static)
