### ISSUE TITLE
[bug] Cannot connect to remote mqtt broker

### ISSUE THREAD

**Issue by St4niuu** [tauri-apps/tauri#7954]
### Describe the bug

Hi!
I'm creating a desktop app that will provide data for MQTT broker and I'm trying to connect with the broker using the MQTT.js library. Unfortunately, there is strange behaviour from my tauri environment. I had been reading a lot about it throughout Internet but didn't come across any actual solution. The problem is, when I try to connect to mqqt broker I provider an object like this:
`const broker = mqtt.connect({
        host: 'xxxxxxxxxxxxxxxxxxxxxx.s1.eu.hivemq.cloud',
	port: 8883,
	protocol: 'mqtts',
	username: 'user',
	password: 'secret',
})`

From nodejs environment, there is no problem in such configuration. The problem starts to occur while I'm trying to connect like this through tauri. I tried to modify "dangerousRemoteDomainIpcAccess" in config, to be honest I don't even know it is meant for it, but I tried at least, didn't work.

In console in application appears the following error: **WebSocket connection to 'wss://localhost:8883/mqtt' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED**

It seems like rust and tauri change the url that is being used to the localhost, not allowing external addresses. With fetch everything works fine, when I try the mqqt/ws protocol it occurs. Any suggestions?

Thanks a lot in advance!

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 117.0.2045.47
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.72.1 (d5c2e9c34 2023-09-13)
    ✔ Cargo: 1.72.1 (103a7ff2e 2023-08-15)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.15.0
    - npm: 9.7.1

[-] Packages
    - tauri [RUST]: 1.5.1
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.4
    - tauri-cli [RUST]: not installed!
    - @tauri-apps/api [NPM]: 1.5.0
    - @tauri-apps/cli [NPM]: 1.5.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by AClon314** [comment]
### Describe the bug
https://discord.com/channels/616186924390023171/1228369933071814706
the app's hmr is ok on windows, but on android, annoying auto refresh is still reproducible in clean init, I have to turn down hot reload by `hmr:false`

### Reproduction
I do a clean init `pnpm create tauri --beta` (use vue), then `pnpm tauri android init`, `pnpm tauri android dev`

### Expected behavior
enable `hmr` on mobile while refresh the webpage only when it needs.

### Platform and versions
```
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 120.0.2210.91
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.77.2 (25ef9e3d8 2024-04-09)
    ✔ cargo: 1.77.2 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.11.1
    - pnpm: 8.15.6
    - npm: 10.2.4
    - bun: 1.0.30

[-] Packages
    - tauri [RUST]: 2.0.0-beta.14
    - tauri-build [RUST]: 2.0.0-beta.11
    - wry [RUST]: 0.39.0
    - tao [RUST]: 0.27.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.7
    - @tauri-apps/cli [NPM]: 2.0.0-beta.12

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

### Stack trace
- in the `pnpm tauri android dev` console, I see the following error spamming:
```markdown
04-12 15:19:29.626  9990  9990 I Tauri/Console: File: http://tauri.localhost/@vite/client - Line 524 - Msg: [vite] server connection lost. polling for restart...
9990  9990 I Tauri/Console: File: http://tauri.localhost/@vite/client - Line 524 - Msg: [vite] server connection lost. polling for restart...
9990  9990 I Tauri/Console: File: http://tauri.localhost/@vite/client - Line 524 - Msg: [vite] server connection lost. polling for restart...
9990  9990 I Tauri/Console: File: http://tauri.localhost/@vite/client - Line 524 - Msg: [vite] server connection lost. polling for restart...
9990  9990 I Tauri/Console: File: http://tauri.localhost/@vite/client - Line 524 - Msg: [vite] server connection lost. polling for restart...
```
```markdown
> tauri-app@0.0.0 tauri D:\Documents\Code\rust\tauri-app
> tauri "android" "dev"

    Info Detected connected device: Pixel_3a_API_34_extension_level_7_x86_64 (sdk_gphone64_x86_64) with target "x86_64-linux-android"
    Info Using 198.18.0.1 to access the development server.
    Running BeforeDevCommand (`pnpm dev`)

> tauri-app@0.0.0 dev D:\Documents\Code\rust\tauri-app
> vite


  VITE v5.2.8  ready in 1389 ms

  ➜  Local:   http://localhost:1420/
  ➜  Network: http://198.18.0.1:1420/
  ➜  Network: http://172.29.240.1:1420/
  ➜  Network: http://172.17.16.1:1420/
  ➜  Network: http://192.168.31.103:1420/
```

- in the browser console, I see the following error:
```markdown
WebSocket connection to 'ws://tauri.localhost:1421/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
[vite] server connection lost. polling for restart...
client.ts:327 

GET http://tauri.localhost:1421/ 400 (Bad Request)
已导航到http://tauri.localhost/
```

### Additional context
It seems happening after I upgrade npm packages, rust crates, and rust itself by `rustup`.
I've tried `git reset` to the early commit, but still reproducible. maybe the config has `>=version` `^version` etc,  so previous's is different from now's downloaded version.

**Comment by AClon314** [comment]
Mine solved: clash vpn proxy conflict to websocket, turn down TUN mode
