### ISSUE TITLE
[feat] Ability to get MenuItemHandle to Submenu

### ISSUE THREAD

**Issue by dwosk** [tauri-apps/tauri#7959]
### Describe the problem

Our app allows end users to change the application display language. When this setting is changed the application needs to retranslate "in place" without requiring a restart. It's easy enough to retranslate the UI running in the web view, but we are having trouble retranslating the native application menu items - specifically anything created as a `Submenu`.

For example, take a menu created via the following:
```rust
fn build_menu() -> Menu {
    let mut menu = Menu::new();

    let troubleshooting_menu = Menu::new().add_item(CustomMenuItem::new("logs", "Show Logs"));
    let submenu = Submenu::new("Troubleshooting", troubleshooting_menu);

    menu = menu.add_submenu(submenu);
    menu
}
```

We can get a `MenuItemHandle` to the `Show Logs` menu item and retranslate fine, but not to the `Troubleshooting` submenu item.

For example, this does not work:
```rust
    let main_window = app_handle.get_window("main").unwrap();
    let menu_handle = main_window.menu_handle();

    // This doesn't work:
    // if let Some(menu_item) = menu_handle.try_get_item(&"Troubleshooting") {
    //     _ = menu_item.set_title("Probleemoplossen");
    // }
```

This is reproducible with the latest Tauri:
```
> tauri info


[✔] Environment
    - OS: Mac OS 14.0.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.71.1 (eb26296b5 2023-08-03)
    ✔ Cargo: 1.71.1 (7f1d04c00 2023-07-29)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 18.17.1
    - npm: 9.6.7

[-] Packages
    - tauri [RUST]: 1.5.1
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.4
    - tauri-cli [RUST]: not installed!
    - @tauri-apps/api [NPM]: 1.5.0
    - @tauri-apps/cli [NPM]: 1.5.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite

```

### Describe the solution you'd like

We would like a way to get a `MenuItemHandle` to submenus so that we can retranslate them via `set_title()`.

Ideally, when a submenu is created, we could specify an id that can be be used later on when calling `get_item()` or `try_get_item()`.

**Comment by amrbashir** [comment]
Tauri v2.0-alpha contains an improved Menu APIs that lets you manipulate the menu/submenu and its items as you wish, there is no plans on porting it back to tauri v1.
