### ISSUE TITLE
npx tauri dev run error

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#797]
thread 'main' panicked at 'Failed to build webview: invalid utf-8 sequence of 1 bytes from index 2', 

.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-0.7.3\src\app.rs:21:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by lucasfernog** [comment]
Closed by #798 
Thanks for the report, we'll publish it soon.

To use the fix right now, run:
`cargo install --git https://github.com/tauri-apps/tauri/ --branch dev tauri-bundler`

and change `tauri = { version = "..." }` to `tauri = { git = "https://github.com/tauri-apps/tauri/", branch = "dev" }` on your app's Cargo.toml
