### ISSUE TITLE
[bug] `convertFileSrc` does not behave as expected on windows

### ISSUE THREAD

**Issue by drl990114** [tauri-apps/tauri#7970]
### Describe the bug

The following code can be accessed on Mac without additional processing, but on Windows, I have to do some processing before it can be accessed.

By the way, tauri info didn't detect my dependency "@tauri-apps/api": "^2.0.0-alpha.8".

### Reproduction

```js
import { tauri } from '@tauri-apps/api'
import { join } from '@tauri-apps/api/path'

const url1 = await join(dirPath, url);  // "C:\Users\xxx\Desktop\line test\imgs\img.png"
const url2 = url1.replaceAll('\\', '/').split("C:/")[1] // "Users/xxx/Desktop/line test/imgs/img.png"

tauri.convertFileSrc(url1) // in windows get http code 400, Bad Request, in macOS, it can be requested normally
tauri.convertFileSrc(url2) // this is work on windowsOS
```

### Expected behavior

It is expected that resource requests can be made to the original path normally.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 117.0.2045.47
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ Cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-pc-windows-msvc (default)
    - node: 20.8.0
    - yarn: 3.6.1
    - npm: 10.1.0

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.14
    - tauri-build [RUST]: 2.0.0-alpha.8
    - wry [RUST]: 0.33.0
    - tao [RUST]: 0.22.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.14

[-] App
    - build-type: bundle
    - CSP: default-src 'self'; img-src 'self' asset: https://asset.localhost
    - distDir: ../dist
    - devPath: http://localhost:3000/
    - framework: React
    - bundler: Vite
```

### Additional context

My own system is macos. The above tests and behaviors appear on a windows virtual machine. Will this have any impact?

**Comment by amrbashir** [comment]
This is working fine on my Windows, please check if you have `assetProtocol` enabled and the scope is configured properly https://tauri.app/v1/api/config#protocolallowlistconfig.asset. If still doesn't work please provide a minimal repro.

**Comment by amrbashir** [comment]
Also your tauri alpha version is behind, it should be `2.0.0-alpha.15` which I think had a fix for this problem.

**Comment by drl990114** [comment]
Yes, it is ok in `2.0.0-alpha.15`, thank you!!
