### ISSUE TITLE
[feat] Add the ability to open files directly from file manager

### ISSUE THREAD

**Issue by cleamoon** [tauri-apps/tauri#7979]
### Describe the problem

I am trying to write an simple image viewer with Tauri and it could be nice to be able to open the image file directly from file manager instead of always using the open dialog. 

### Describe the solution you'd like

Maybe it should be able to add the configuration about which kind of file types can be open directly and add a simple api to get their locations.

### Additional context

When I try to open an image file on Mac, I got the following error: `The document “image.png” could not be opened. Riko cannot open files in the “PNG image” format.`. I am not really sure whether this is something wrong with my cnofiguration or Tauri does not support this kind of operation. If it is a problem with the configuration, maybe it can be clarified in the Tauri document?

**Comment by amrbashir** [comment]
This is added in v2-alpha, it is called file association and it will only show your app in `Open file with` menu, the file path is then passed to your application as CLI argument that you will need to handle. Documentation will be available once v2 is stable.
