### ISSUE TITLE
[docs] menu item doesn't show up on MacOS

### ISSUE THREAD

**Issue by czheo** [tauri-apps/tauri#7981]
### Describe the bug

``` rust
let menu = Menu::new().add_item(CustomMenuItem::new("hide", "Hide"));
tauri::Builder::default()
  .menu(menu)
  ...
```
I added a item to the menu like above but it doesn't show up anywhere

### Reproduction

Reproduced in https://github.com/czheo/tauri_bug
This is created based on the app template created by `sh <(curl https://create.tauri.app/sh)`.
With only this change: https://github.com/czheo/tauri_bug/commit/23171865aedffdfb38ccee13123d9d1ec5896eb7

### Expected behavior

There should be "Hide" button/menu item shown somewhere on the menu bar.

### Platform and versions

```text
$ cargo tauri info
WARNING: no lock files found, defaulting to npm

[✔] Environment
    - OS: Mac OS 12.6.9 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ Cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 19.8.1
    - pnpm: 8.8.0
    - yarn: 3.4.1
    - npm: 9.6.2

[-] Packages
    - tauri [RUST]: 1.5.1
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.4
    - tauri-cli [RUST]: 1.5.1
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.5.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../src
    - devPath: ../src
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by amrbashir** [comment]
on macOS, you can't add a menu item directly to the `Menu`, you can only add submenus. Looks like this is a documentation mistake so I will open a PR to fix that.

**Comment by czheo** [comment]
@amrbashir thanks for looking into this. 
If `add_item` were to be supported on MacOS, it makes most sense to me the item would be added under the dropdown of the app name.
If not support, how can I add an item under that dropdown then?

For example, I expect the tauri_bug menu will expand with some menu item, however there's no associated dropdown.
![image](https://github.com/tauri-apps/tauri/assets/1692400/2f3a0993-cc8b-4ad4-8b8c-29132b1c4124)
I want something like in chrome, where the app name "Chrome" has its own dropdown, and "File", "Edit" and etc are other submenus.
![image](https://github.com/tauri-apps/tauri/assets/1692400/7ddeab7a-20cd-40ff-90a5-63352de4d4f6)

**Comment by FabianLars** [comment]
It should take the first subitem automatically, maybe the submenu needs the app name as it's name but i don't think so. For reference here's the implementation of os_menu() which also fills that first menu: https://docs.rs/tauri-runtime/0.14.1/src/tauri_runtime/menu.rs.html#245

**Comment by czheo** [comment]
@FabianLars 
> It should take the first subitem automatically

Yes, that's my expectation. But It doesn't do so now, as my code example shows in: https://github.com/czheo/tauri_bug

> maybe the submenu needs the app name as it's name but i don't think so.

I tested creating a submenu with the app name and it creates a different submenu next to the default one:
![image](https://github.com/tauri-apps/tauri/assets/1692400/30b0199d-19fc-4a38-9046-157a8cd62c50)

**Comment by FabianLars** [comment]
weird, it works for me:
<img width="1176" alt="Bildschirmfoto 2023-10-10 um 10 59 05" src="https://github.com/tauri-apps/tauri/assets/30730186/079350f4-16be-42bd-bad5-671a6ab8d956">

Also picking up your comment from the PR:
> I don't see a reason add_item shouldn't be supported in MacOS. My expectation is described as in https://github.com/tauri-apps/tauri/issues/7981#issuecomment-1752458454

The reason why this doesn't make sense is mostly due to cross-platform consistency. On Windows and Linux the "parent" items in the menu bar can be basically buttons and don't need submenus to provide functionality. iirc on macOS only submenu items trigger events the app can handle.

**Comment by czheo** [comment]
@FabianLars It seems behavior is different by OS version. I guess you are on MacOS 13. It's also weird your title shows nowhere. How are you supposed to create a menu next to the "react" menu then?

**Comment by FabianLars** [comment]
> I guess you are on MacOS 13

I am, yes. But it used to work on 10.15 last time i used my VM too, can test again today or next week 🤔 What version are you on?

> It's also weird your title shows nowhere. 

Weird yes, but expected because the first menu item is set by macos reading the app name.

> How are you supposed to create a menu next to the "react" menu then?

By adding another submenu to the main menu. Each submenu (on the main menu) will be displayed on the menu bar.

**Comment by czheo** [comment]
@FabianLars I see what you mean. I'm on `OS: Mac OS 12.6.9 X64`. I think my machine is different from the behavior you explained. (I have first menu auto populated by the OS being empty, with all submenus added after it)

**Comment by czheo** [comment]
> The reason why this doesn't make sense is mostly due to cross-platform consistency. On Windows and Linux the "parent" items in the menu bar can be basically buttons and don't need submenus to provide functionality. iirc on macOS only submenu items trigger events the app can handle.

Will it make more sense that `add_item` on MacOs adds item to the default menu shown with app name that's populated by the OS automatically? (That was my original expectation)

**Comment by FabianLars** [comment]
_To me_ it wouldn't make more sense than the current approach, no.
In my mind the first Menu is the menu bar itself, and each submenu is a new menubutton on that bar, i think it'd me even more confusing if the first menu isn't a submenu while the others are, especially if we think about cross-platform code.

**Comment by czheo** [comment]
@FabianLars From a tauri user's perspective,
1. The first menu on MacOS is in bold, which indicates it's different from other sub menu buttons. Without calling `add_submenu`, it is already there. It is confusing that the first `add_submenu` call touches something already exists, instead of adding a new one.
2.The current submenu implementation will ignore the first title as you said, which is an ugly corner case that creates confusion, just like what happened to me. Even if documented explicitly, it's a pain for new developers to find it.
3. When user call `add_item`, it does nothing. We need to search the doc to find out that it is not supported in Mac.

I feel the lib interface will much simpler, with `add_item` to the default menu (first menu), and `add_submenu` appending more menus behind the default.

> if we think about cross-platform code

I don't have a perspective from a tauri maintainer. But I feel we should prioritize user friendliness if possible.

**Comment by czheo** [comment]
> if we think about cross-platform code

Double thinking this claim. I think it makes sense to me that having similar behaviors on different platforms can have benefit. Cross-platform app builders need not have different code on different platforms.
