### ISSUE TITLE
[bug] tauri v2 mica effect glitch

### ISSUE THREAD

**Issue by reyamir** [tauri-apps/tauri#7984]
### Describe the bug

"mica" effect on windows 11 cause text rendering glitch (both light and dark mode)

https://github.com/tauri-apps/tauri/assets/123083837/72da6082-b44a-4436-b6cc-9d10cd942aab

On this video, I didn't set any background on sidebar, using `bg-transparent`, only main content have white background

If I set background (`bg-white` or `bg-black`) for sidebar, there are no issues

### Reproduction

Enable "mica" in windowEffects
```
{
       ....
        "transparent": true,
        "windowEffects": {
          "effects": ["mica"]
        }
}
```

### Expected behavior

No glitch

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 117.0.2045.60
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ Cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.5.1
    - pnpm: 8.7.0
    - npm: 9.8.0

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.14
    - tauri-build [RUST]: 2.0.0-alpha.8
    - wry [RUST]: 0.33.0
    - tao [RUST]: 0.22.2
    - @tauri-apps/api [NPM]: 2.0.0-alpha.8
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.14

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:3000/
    - framework: React
    - bundler: Vite
```

### Stack trace

```text
None
```

### Additional context

None

**Comment by amrbashir** [comment]
This is out of our hands unfortunately, the mica effect is rendered by Windows itself. If there is any glitches, and we also don't control the render of the webview.

**Comment by reyamir** [comment]
I don't know why, but set "micaLight" and "micaDark" will solve this issue, lol
```
"windowEffects": {
          "effects": ["micaLight", "micaDark"]
}
```

windows is really mess, I'm f**king hate it
