### ISSUE TITLE
[feat] http proxy for nsis bundler

### ISSUE THREAD

**Issue by CaiJingLong** [tauri-apps/tauri#7985]
### Describe the problem

I want to build a windows app on macOS, I try to use the [cross-compile](https://tauri.app/v1/guides/building/cross-platform/#experimental-build-windows-apps-on-linux-and-macos) methods to build.

After build, the build progress will download some files to "Verifying NSIS package".

But I can't download the files from github, because I need use http_proxy/https_proxy to visit github.

### Describe the solution you'd like

I think need to read system proxy or rust http proxy config or environment.

https://github.com/tauri-apps/tauri/blob/713f84db2b5bf17e4217053a229f9c11cbb22c74/tooling/bundler/src/bundle/windows/util.rs#L28-L34

I'm not familiar with the rust and don't know how to modify it.

**Comment by CaiJingLong** [comment]
Same problem when I compile nsis on windows device.

**Comment by CaiJingLong** [comment]
I can open a PR to fix this if needed.

**Comment by FabianLars** [comment]
Sure, PRs are always appreciated!

**Comment by CaiJingLong** [comment]
I open #8008 to handle the issue.
