### ISSUE TITLE
[bug] nsis_tauri_util.dll Symantec security risk detected

### ISSUE THREAD

**Issue by Pil0tXia** [tauri-apps/tauri#7995]
### Describe the bug

![image](https://github.com/tauri-apps/tauri/assets/41445332/45ba61e3-b9b9-48a9-82b6-21fce66673d6)

### Reproduction

![image](https://github.com/pot-app/pot-desktop/assets/41445332/7047a065-ef86-453d-9b3b-aaab502bafe5)

Happens when @tauri-apps/api upgrades to 1.5.0 from 1.4.0 in this commit https://github.com/pot-app/pot-desktop/commit/6cb9bdb5abec747cde32e022cb72ebdec1308af3.

### Platform and versions

```text
Win11 Pro 22621.2283
https://github.com/pot-app/pot-desktop 2.6.2
"@tauri-apps/api": "^1.5.0"
```

**Comment by hjmallon** [comment]
This happens in Crowdstrike Falcon too (see https://www.virustotal.com/gui/file/0eed48313a7f904d7cc1977b70000ab3f11f18cadc8e6a69b807d288ca71f9db/detection)

**Comment by FabianLars** [comment]
I don't think there's anything that we can do on our side. The only change in that file is that we now statically compile the vc runtime but that's required for the installer to actually work on all systems :/

So if those companies have similar websites like Microsoft where you can submit it for manual-ish analysis (in case of false positives) it would be great if you can reach out to them :)
(that's the MS site i mean: https://www.microsoft.com/en-us/wdsi/filesubmission
