### ISSUE TITLE
[feat] Expose task bar progress bar api from tao

### ISSUE THREAD

**Issue by ahqsoftwares** [tauri-apps/tauri#7999]
Expose https://docs.rs/tao/latest/x86_64-apple-darwin/tao/window/struct.Window.html#method.set_progress_bar into tauri 1.x

**Comment by pewsheen** [comment]
I remember this was implemented on the `tao:dev` branch. Should we back port to `1.x`? @amrbashir

**Comment by amrbashir** [comment]
No need to backport, should only be for 2.x

**Comment by trishanu-init** [comment]
@ahqsoftwares I am willing to work on this issue if it's up for grabs

**Comment by ahqsoftwares** [comment]
> @ahqsoftwares I am willing to work on this issue if it's up for grabs

You may but according to @amrbashir 's post, theres no need to backport

**Comment by amrbashir** [comment]
@trishanu-init thanks for your offering, unfortunately @pewsheen has already opened a PR and it will not be backported to v1.
