### ISSUE TITLE
[docs] update readme

### ISSUE THREAD

**Issue by Chanchal-D** [tauri-apps/tauri#8003]
the existing readme doesn't contain the prerequisites and should be interactive and brief, in order to look attractive

**Comment by dalvishruti14** [comment]
I would like to work on this issue. Kindly assign it to me.

**Comment by JonasKruckenberg** [comment]
While I agree we should revisit the readme and clean things up here and there, the prerequisites and setup required  to develop apps using Tauri is more involved than what we can fit into a simple readme.
A lot of work has gone into the getting started guides on [our website](https://tauri.app) and people should use that.
