### ISSUE TITLE
[bug] `invoke` isn't being rendered in docs

### ISSUE THREAD

**Issue by lorenzolewis** [tauri-apps/tauri#8014]
### Describe the bug

Because of this line: https://github.com/tauri-apps/tauri/blob/46dcb94110ac16d0d4328fa149bb86975b658f59/tooling/api/src/index.ts#L20

The `invoke` function is not being rendered in the docs in https://beta.tauri.app/2/reference/js/core/ nor in https://beta.tauri.app/2/reference/js/core/namespacetauri/. Since it is re-exported in `index.ts` then the docs generator is respecting the `@ignore` option.

### Platform and versions

```text
N/A
```

### Additional context

If we want this to render on https://beta.tauri.app/2/reference/js/core/ then we just need to remove the `@ignore` above. If we want it on https://beta.tauri.app/2/reference/js/core/namespacetauri/ then I believe we need to remove the re-export (although I'm not sure of any additional implications of doing this.

**Comment by amrbashir** [comment]
This re-export is being removed in #7942

**Comment by lorenzolewis** [comment]
Sounds good, thanks!
