### ISSUE TITLE
Controling the webview2/chromium on Tauri

### ISSUE THREAD

**Issue by rmkdev3** [tauri-apps/tauri#8016]
### Describe the problem

We are looking to moving to an Electron alternative and we have a requirement where we need to control the chromium version of our app. 

### Describe the solution you'd like

Tauri is looking to be our pick for a replacement, and we want to see if there is a way to control the webview2 or chromium version with Tauri or if it is a feature that can be added.  If this is a feature that can be added we would prefer that we can run a specific chromium version with the Tauri framework.

**Comment by FabianLars** [comment]
Hi 👋 So you can't control the version of the system wide webview2 installation but you can include a standalone runtime with the version of your choice as described here: https://tauri.app/v1/guides/building/windows#fixed-version. Obviously this will increase the bundle size by a lot but i assume this doesn't matter for your app if you want to control the chromium version.
