### ISSUE TITLE
[bug] [v2] Cli outputs wrong "You must enable" code when plugin name have dash

### ISSUE THREAD

**Issue by vasfvitor** [tauri-apps/tauri#8017]
### Describe the bug

"You must enable the plugin in your Rust code:" says:
`tauri::Builder::default().plugin(tauri_plugin_clipboard-manager::init())`

cli output:
![image](https://github.com/tauri-apps/tauri/assets/61759797/b4fe8919-af69-45e8-9c8b-7b8fab63d4e8)

code preview:
![image](https://github.com/tauri-apps/tauri/assets/61759797/f65724ae-18a2-4bc8-8ba3-0512674f2508)

### Reproduction

New project with `cargo create-tauri-app --alpha -m cargo -t leptos -y`

`cargo tauri add clipboard-manager`
or
`cargo tauri add single-instance`

### Expected behavior

Suggestion should be:
`tauri::Builder::default().plugin(tauri_plugin_clipboard_manager::init())`

notice `clipboard_manager` with `_` vs `-`

![image](https://github.com/tauri-apps/tauri/assets/61759797/628fe0a5-3f9f-4087-a8ae-2c63074d6a7f)

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 117.0.2045.60
    ✔ MSVC:
        - Ferramentas de Build do Visual Studio 2019
        - Visual Studio Community 2022
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ Cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.17.0
    - pnpm: 8.8.0
    - yarn: 1.22.19
    - npm: 9.8.1

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.15
    - tauri-build [RUST]: 2.0.0-alpha.9
    - wry [RUST]: 0.33.1
    - tao [RUST]: 0.22.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.15

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
```

### Additional context

At tauri-docs it's ok. I believe it's only affects cli.

This bug should arise at any plugin that has dash in it's name. As clipboard-manager, single-instance, barcode-scanner...

plugin single-instance:
![image](https://github.com/tauri-apps/tauri/assets/61759797/2a979dc2-31d7-4f65-9a15-4958aa450876)

**Comment by furqanindikar** [comment]
Assign me
