### ISSUE TITLE
Tauri windows build lag issue with WebGL.

### ISSUE THREAD

**Issue by deepushajia** [tauri-apps/tauri#8020]
### Describe the bug

I am using WebGL in my tauri app on top of reactJS. Things are working smoothly on dev window, but when I run the app from the build, I am noticing considerable drop in performance on the webgl rendering, mostly lag. What could be the issue considering the webview2 used to render is same in both dev and build right?

### Expected behavior

Almost similar performance on dev and build.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 117.0.2045.60
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ Cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.18.1
    - npm: 9.8.1

[-] Packages
    - tauri [RUST]: 1.5.1
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.4
    - tauri-cli [RUST]: not installed!
    - @tauri-apps/api [NPM]: 1.5.0
    - @tauri-apps/cli [NPM]: 1.5.1 (outdated, latest: 1.5.2)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../build
    - devPath: http://localhost:3000/
    - framework: React
```

**Comment by FabianLars** [comment]
Yeah, the rendering is the same. The only difference i can think of is that files are loaded differently. In dev it's your dev server and in build mode it's tauri itself serving those. I don't _think_ that matters but it's the only thing that comes to mind.
Could you maybe create a minimal reproduction example so we can check it out too?

**Comment by Jon2066** [comment]
same problem, any progress?

**Comment by markforster** [comment]
i'm seeing the same issue


```
[✔] Environment
    - OS: macOS 26.2 (Build 25C56) arm64, MacBook Pro 14" (Apple M5, 24 GB)
    ✔ WebView: WKWebView (Safari 26.2 on macOS 26.2)
    ✔ rustc: 1.93.0 (254b59607 2026-01-19)
    ✔ Cargo: 1.93.0 (083ac5135 2025-12-15)
    ✔ rustup: 1.28.2 (e4f3ad6f8 2025-04-28)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 22.5.1
    - npm: 10.8.2

[-] Packages
    - tauri [RUST]: 2.9.5
    - tauri-build [RUST]: 2.5.3
    - wry [RUST]: 0.53.5
    - tao [RUST]: 0.34.5
    - tauri-cli [RUST]: not installed
    - @tauri-apps/api [NPM]: 2.9.1
    - @tauri-apps/cli [NPM]: 2.9.6

[-] App
    - build-type: bundle (bundle.active = true)
    - CSP: unset (null)
    - distDir: ../out
    - devPath: none (devUrl is null)
    - framework: Next.js 14 (React 18)
```

I’m not sure if this is relevant, but I’ve noticed the 3D view runs buttery smoothl when the same static files are opened directly in a browser or served over HTTP. The slowdown only seems to happen once it’s wrapped in Tauri and ran as an app.

I don’t know the internals of how the embedded browser works, but I wonder if there could be some difference in how graphics acceleration or rendering is handled in that environment. It feels less like an issue with the 3D code itself and more like something specific to the wrapper?

**Comment by FabianLars** [comment]
which browser did you test? since you're on macos only safari would be a good comparison to confirm your browser vs wrapper theory since the webview we use is basically safari.
