### ISSUE TITLE
Apps

### ISSUE THREAD

**Issue by ProstarManuel** [tauri-apps/tauri#803]

**Comment by nothingismagick** [comment]
This is arguably the greatest issue ever created in the history of software development. There are potentially many like it, but this one is ours. 

# :heart: :heart: :heart: :heart:

**Comment by ProstarManuel** [comment]
Please sorry. I Didn't mean to send any issue concerning your scripts. I'm new on github and I wanted to add your script installation to my favorites.. Please sorry 🙏 

Sent from Yahoo Mail on Android 
 
  On Fri, Jul 10, 2020 at 3:42 PM, nothingismagick<notifications@github.com> wrote:   


This is arguably the greatest issue ever created in the history of software development. There are potentially many like it, but this one is ours.

 ❤️ ❤️ ❤️ ❤️

**Comment by nothingismagick** [comment]
Possible related to:
https://github.com/Z4nzu/hackingtool/issues/21

**Comment by nothingismagick** [comment]
you can simply click the :star:

![image](https://user-images.githubusercontent.com/35242872/87172961-5a7a2b80-c2d5-11ea-95fb-df0bc821e082.png)

**Comment by Z4nzu** [comment]
Thank you so much for your love ❤️ I'll always try to improve it for hackers 😊🤩

**Comment by nothingismagick** [comment]
@Z4nzu - you are a legend. Keep it up!!!!!!! (And stop back in if you ever want to consider making a binary with tauri ;)

**Comment by Z4nzu** [comment]
> @Z4nzu - you are a legend. Keep it up!!!!!!! (And stop back in if you ever want to consider making a binary with tauri ;)

Thank you I'll sure make in touch with you 😊🤩
