### ISSUE TITLE
[bug] MP3 cannot play problem

### ISSUE THREAD

**Issue by ytwp** [tauri-apps/tauri#8052]
### Describe the bug

The development environment can play MP3 files returned by 206 Partial Content
Formal packaging cannot play MP3 returned by 206 Partial Content

Test link: https://tts.iciba.com/output/EN_Female1/b/5b/ccdf9c335f3d8990fbea7bd15e3c3.mp3

### Platform and versions

```text
Both 1.5.4 and 1.4.0 cannot be played
```

**Comment by FabianLars** [comment]
Can you create a debug build via `npm run tauri build -- --debug` (only npm needs the extra `--`) and check the devtools for errors?

Also, please include the whole output of the `tauri info` as required in the template comment.

Lastly, with "formal packaging" do you mean the mp3 is included as a normal file inside the bundle or do you still load a remote url?
