### ISSUE TITLE
[feat] v2 - Move bundle configs into respective platform objects.

### ISSUE THREAD

**Issue by FabianLars** [tauri-apps/tauri#8055]
### Describe the problem

Currently the config is a bit of a mess, we have deb and appimage configs at the root but also a windows config that contains the nsis and wix configs.

### Describe the solution you'd like

Move appimage and deb into a linux config. Something similar will probably need to happen on macos with the open dmg PR and potentially upcoming formats (pkg?).

I can work on this myself (unless a community member _wants_ to work on this :) ) but wanted to discuss this here first, so don't take this issue as a "Please fix this for me" thing 😅

P.S. i am aware that cargo-package doesn't have OS configs but tauri's config covers way more stuff (other than bundler related things) so imo a bit more structure would be valuable, especially since not every user may know each bundle name so maybeee this clears it up a bit for a few people 🤷 

### Alternatives considered

pulling out wix, nsis, etc into the root or just leaving it as is. The first one is too messy and the second one looks too much like an "accident" (for the lack of a better word)

### Additional context

imo this should happen after the rpm and dmg prs so that the community members don't have to deal with it, _unless_ we think we can't get those PR in tauri in time for the audit, then we should change it asap and let the PRs deal with the change.

PRs that would be affected:
rpm https://github.com/tauri-apps/tauri/pull/5202 (adds new configs but at the root like deb)
dmg https://github.com/tauri-apps/tauri/pull/7964 (adds new configs but at the root like deb)
snap https://github.com/tauri-apps/tauri/pull/6532 (this one doesn't have configs yet)
pacman https://github.com/tauri-apps/tauri/pull/4301 (this one doesn't have configs yet)

**Comment by olivierlemasle** [comment]
A big yes to this proposal!

When writing #5202 (rpm support), this inconsistency between configuration for OSes (Windows, Mac) and package types (Deb, AppImage) also struck me.

Furthermore, AppImage packaging uses Debian files, and depends as such of Deb configuration:

https://github.com/tauri-apps/tauri/blob/c90ee65dbfe8842e37dfc3d8b737a58e6d5b6ac7/tooling/bundler/src/bundle/linux/appimage.rs#L32-L34

E.g. `desktopTemplate` in `DebConfig` is actually used by Deb and AppImage. For RPM, in my PR, I duplicated it in `RpmConfig`. But I think having it in a `LinuxConfig` would be better.

For `RpmConfig`, I also duplicated `files` and `depends` from `DebConfig`, and these settings _**could**_ be set at the OS platform level (in a new `LinuxConfig`). However, it might be necessary to differentiate the dependencies for each OS. But it's a difference by Linux Distribution (e.g. `libjson-c-dev` for Debian, `libjson-c-devel` for Fedora), not really by packaging type (deb vs rpm).
