### ISSUE TITLE
[bug] On `dev`, `window.__TAURI__.invoke` not defined but used in examples

### ISSUE THREAD

**Issue by olivierlemasle** [tauri-apps/tauri#8073]
### Describe the bug

On `dev` branch, the Tauri examples use `window.__TAURI__.invoke`:

https://github.com/tauri-apps/tauri/blob/c6c59cf2373258b626b00a26f4de4331765dd487/examples/commands/index.html#L18-L19

However, these examples fail with:

```
[Error] TypeError: window.__TAURI__
          .invoke is not a function. (In 'window.__TAURI__
          .invoke(commandName, args)', 'window.__TAURI__
          .invoke' is undefined)
```

`window.__TAURI__` is defined (`withGlobalTauri` is `true`), but it has no function named `invoke`.

### Reproduction

On `dev` branch:

```
cargo run --example commands
```

Click on any button.

Other examples, such as `streaming`, have the same issue.

### Expected behavior

`window.__TAURI__.invoke` should be defined, or the examples should be updated if needed.

### Platform and versions

```text
[✔] Environment
    - OS: Fedora 38.0.0 X64
    ✔ webkit2gtk-4.1: 2.42.1
    ✔ rsvg2: 2.56.3
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ Cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.18.0
    - pnpm: 8.8.0
    - yarn: 1.22.19
    - npm: 9.8.1

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.10
    - tauri-build [RUST]: 2.0.0-alpha.6
    - wry [RUST]: 0.30.0
    - tao [RUST]: 0.21.0
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.16

[-] App
    - build-type: bundle
    - CSP: default-src 'self'
    - distDir: ["../index.html"]
    - devPath: ["../index.html"]
```

**Comment by olivierlemasle** [comment]
This is also causes issues:
- with default app generated with create-tauri-app, when using **Vanilla** UI template:
  To reproduce:
  ```
  cargo create-tauri-app --alpha --template vanilla --manager cargo -y test-invoke
  cd test-invoke
  cargo tauri dev
  ```
- with **benchmarks**:
    That's the cause of the CI issue on #8045.
    E.g. for the `helloworld` benchmark, [`window.__TAURI__.invoke('app_loaded_successfully')`](https://github.com/tauri-apps/tauri/blob/c6c59cf2373258b626b00a26f4de4331765dd487/tooling/bench/tests/helloworld/public/index.html#L13) fails, so the app does not quit, which leads the benchmark to run forever.

**Comment by amrbashir** [comment]
Forgot I have to update CTA alpha templates , thanks for the reminder

Edit: actually will need to wait for the plugins to be published.

**Comment by amrbashir** [comment]
`window.__TAURI__.invoke` has been removed btw, it should now be `window.__TAURI__.primitives.invoke`

**Comment by olivierlemasle** [comment]
Thank you @amrbashir, I overlooked that change in the Changelog.
I've created PR #8077 to fix the examples, and I updated the benchmarks in #8045.

**Comment by dravenk** [comment]
I have the same problem with this issue; Fixed the problem I encountered after changing this line
Change this line ` ["window", "__TAURI__", "invoke"])] `  to ` ["window", "__TAURI__", "core"])]`
```
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = ["window", "__TAURI__", "core"])]
    async fn invoke(cmd: &str, args: JsValue) -> JsValue;
}
```
