### ISSUE TITLE
[bug] api/dialog/dialogOpen parameter defaultPath does not work on Windows with slash separators

### ISSUE THREAD

**Issue by qu1ck** [tauri-apps/tauri#8074]
### Describe the bug

When calling dialogOpen, defaultPath parameter is supposed to specify which folder will be opened initially.
On windows it works only if backslash is used as path separator, if a forward slash is used then the parameter is ignored.

I realize this is likely a limitation of winapi but it looks like something that is very easy to fix in rust side of the api. Yes, it can be worked around in javascript side but I think Tauri should take care of it since this is both undocumented and not obvious to rootcause when troubleshooting.

### Reproduction

This works

```
dialogOpen({
  title: "Select directory",
  defaultPath: "D:\tmp",
  directory: true,
}
```

This does not
```
dialogOpen({
  title: "Select directory",
  defaultPath: "D:/tmp",
  directory: true,
}
```
and will open the last used directory or current working directory

### Expected behavior

dialogOpen should work with both "\\" and "/" on windows

### Platform and versions

```text
Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 118.0.2088.46
    ✘ Couldn't detect any Visual Studio or VS Build Tools instance with MSVC and SDK components. Download from https://aka.ms/vs/17/release/vs_BuildTools.exe
    ✔ rustc: 1.71.0 (8ede3aae2 2023-07-12)
    ✔ Cargo: 1.71.0 (cfd3bbd8f 2023-06-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 16.14.2
    - pnpm: 8.6.2
    - npm: 8.5.0

[-] Packages
    - tauri [RUST]: 1.4.0
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0 (outdated, latest: 1.5.1)
    - @tauri-apps/cli [NPM]: 1.4.0 (outdated, latest: 1.5.5)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:8080/
    - framework: React
    - bundler: Webpack
```

**Comment by nehaal10** [comment]
can you assign this bug to me.

**Comment by qu1ck** [comment]
Any update here? This should be a very easy fix.

**Comment by qu1ck** [comment]
Thanks for the fix, can it be backported to v1?

**Comment by FabianLars** [comment]
That already happened. just waiting for the next v1 patch
