### ISSUE TITLE
[feat] Sign .dylib files inside the Frameworks

### ISSUE THREAD

**Issue by morajabi** [tauri-apps/tauri#8075]
### Describe the problem

We embed FFMpeg framework inside the app. In tauri v1.5 and latest v2 alpha Tauri signs the frameworks and sidebar binaries. But it does not sign the sign-able files (eg. .dylib) inside the Framework. This results in notarization to fail if the included binaries are signed using a different signature.

### Describe the solution you'd like

I would like Tauri CLI to sign all files that need to be signed in its build steps to ensure there's no mistake. 

### Alternatives considered

We're currently running a pre-build step and signing the dylibs. Same in other Tauri apps like Spacedrive and Recut. But this might result in using two different developer IDs thus failing the notarization or resulting in a crash on startup. 

### Additional context

Context:
https://discord.com/channels/616186924390023171/986184094050316358/1165228387334373387

**Comment by therealpurplemana** [comment]
Did you find any solution to this?
