### ISSUE TITLE
tauri-shared-memory 如何读写共享内存数据

### ISSUE THREAD

**Issue by wfc66986** [tauri-apps/tauri#8083]
### Describe the bug

tauri-shared-memory 如何读写共享内存数据找不到相关文件信息

### Reproduction

tauri-shared-memory 如何读写共享内存数据找不到相关文件信息

### Platform and versions

```text
tauri-shared-memory 如何读写共享内存数据找不到相关文件信息
```

**Comment by FabianLars** [comment]
I recently answered this in the wry repo: https://github.com/tauri-apps/wry/issues/1035#issuecomment-1762779578 - tldr: It's not possible yet but something we'd love to see.
