### ISSUE TITLE
tauri 如何实现共享内存IPC 有什么提供方法吗

### ISSUE THREAD

**Issue by wfc66986** [tauri-apps/tauri#8087]
### Describe the bug

tauri 如何实现共享内存IPC 有什么提供方法吗

### Reproduction

tauri 如何实现共享内存IPC 有什么提供方法吗

### Expected behavior

tauri 如何实现共享内存IPC 有什么提供方法吗

### Platform and versions

```text
tauri 如何实现共享内存IPC 有什么提供方法吗
```

**Comment by FabianLars** [comment]
Duplicate of https://github.com/tauri-apps/tauri/issues/8083, please don't spam.
