### ISSUE TITLE
[feat] How to Dynamically Load Plugins

### ISSUE THREAD

**Issue by seho-dev** [tauri-apps/tauri#8090]
### Describe the problem

Like RayCast, you can do third-party or trusted sources to pull plugin packages, load the plugin content when the software runs, and enjoy the plugin features and interfaces without restarting the application

### Describe the solution you'd like

Not quite sure how this is implemented in the current version of Tauri

**Comment by amrbashir** [comment]
Plugins in tauri is loaded at compile-time, what you want is not simple as that and is out of tauri's scope.

If you need your plugins to be written in JavaScript only, you can just create a script element and use `convertFileSrc` to set the script src to your plugin path, this will use the built-in `asset` protocol but you can use this API https://docs.rs/tauri/latest/tauri/struct.Builder.html#method.register_uri_scheme_protocol to create your own protocol that would be responsible to loading the plugins.

If you want them to write it in Rust, then things get a bit more difficult, feel free to reach out on discord and I'd be happy to discuss it but it is out of tauri's scope so I will close this issue.

**Comment by seho-dev** [comment]
Ok, I'll be discussing it with you in discord

**Comment by ahqsoftwares** [comment]
Basically rust is compiled and not interpreted. This means that dynamic libraries in rust will be complex and will rely on unsafe code.
And yes, feel free to reach out on discord to discuss about dynamic link libraries that your runtime plugins can use

**Comment by flapili** [comment]
Hi, another solution could be using web assembly, but that is not simple for sure

**Comment by HuakunShen** [comment]
I am currently working on a raycast-like project https://github.com/kunkunsh/kunkun
I am using iframe, web worker, deno to load extensions written in js. 
Also made a video https://youtu.be/HfQb38s8VjY
