### ISSUE TITLE
[bug] The ‘ owner_window’ method is not expected in Windows and macos

### ISSUE THREAD

**Issue by Pixel-Eric** [tauri-apps/tauri#8091]
### Describe the bug

This is my code on macOS.
![截屏2023-10-24 23 02 34](https://github.com/tauri-apps/tauri/assets/97173501/b6160574-89c3-4d51-a3f2-a5d6919d223e)
This is my code on window.
![3305b394e3f4094aba63bcb8cbe8e16f](https://github.com/tauri-apps/tauri/assets/97173501/35e85caf-7a2f-4aa7-8456-0bfe7e624da1)
I was migrating my tauri code to develop on macos and found that the "cargo build" command told me "method not found in 'WindowBuilder".
Although I know this is due to different structures between platforms, I wish Tauri would provide a fake method on macos, otherwise it would give me a headache, thank you.

### Expected behavior

Provide an identical method, even if it is fake.

### Platform and versions

```text
MacOS Sonoma and Tauri 1.5.2
```

**Comment by amrbashir** [comment]
`.owner_window` is only available on Windows so you need to guard it like this:

```rs

let mut builder = WindowBuilder::new(&app, "window", url::WindowUrl::default());

#[cfg(target_os = "windows)]
{
	builder = builder.owner_window();
}
builder.build();
```
for macOS you could use `.parent_window()` which is kinda similar and you also need to guard it as well.
