### ISSUE TITLE
[feat] displayName for package

### ISSUE THREAD

**Issue by moranbw** [tauri-apps/tauri#8109]
### Describe the problem

This is probably nitpicking, but I am looking to have two separate "names" for my Tauri application.  Right now, I understand that in `tauri.conf.json` I can define `package` -> `productName`.  This is what is used to name installers, exe's, log files (if using the [plugin](https://github.com/tauri-apps/plugins-workspace/tree/v1/plugins/log)), etc.  

But it also is what is used for the "user-facing" display name, for example what it is called in the Start Menu on Windows.  So for `my-app`, if I want the user to have a "user-friendly" name to search for, I need to set `productName` to `My App`.  But then the underlying executable is called `My App.exe`, which just kind of irks me lol.  I think it should be `my-app.exe`.  It just seems more professional, and more in line with what I see in other apps I have installed on my system.

### Describe the solution you'd like

Keep `productName` as the default way of naming your app.  But add an option in `package` called `displayName`, which determines the "user-facing" name of the application, while keeping file-system friendly `productName` for .exe's, etc.

### Alternatives considered

I am thinking that this would be an app manifest thing on Windows.  Not sure about Linux and Mac.

**Comment by NXTaar** [comment]
Hope it will be implemented. Have the same problem here for a Windows app

**Comment by eythaann** [comment]
x3, waiting for this feature.

**Comment by mariotaku** [comment]
Hi, I have created a PR to this issue, please try and let me know if it works for you!

**Comment by hengkx** [comment]
Is there any progress? I really need this function

**Comment by FabianLars** [comment]
The PR is linked right above your comment -> https://github.com/tauri-apps/tauri/pull/9375
We can't backport that exact solution to v1 though because it's a breaking change.

**Comment by amrbashir** [comment]
Just a note that we have decided to add `mainBinaryName` option in https://github.com/tauri-apps/tauri/pull/10977 to control the main binary name, this makes `productName` essentially the displayName (which is what it was supposed to) and the new option for main binary name only.
