### ISSUE TITLE
[bug] The setting "dangerousRemoteDomainIpcAccess" does not work.

### ISSUE THREAD

**Issue by gusxodnjs** [tauri-apps/tauri#8121]
### Describe the bug

I created a new window, loaded a remote page.  then to send events to the backend using `Window.__TAURI__.event.emit()`.
However, the following error occurred and the "dangerous RemoteDomainIpcAccess" setting was added, but it is still the same.

- error
![image](https://github.com/tauri-apps/tauri/assets/27146546/e50af958-bf0f-4fd3-8a1b-6b312da1316a)

- tauri-conf.json
```json
"security": {
      "csp": null,
      "dangerousDisableAssetCspModification": true,
      "dangerousRemoteDomainIpcAccess": [
        {
          "domain": "https://www.google.com/",
          "windows": [
            "origin",
            "main",
            "result"
          ],
          "plugins": ["event"]
        }
      ]
    },
```

### Reproduction

-

### Expected behavior

No error occurred

### Platform and versions

```text
$ tauri info

[✔] Environment
    - OS: Mac OS 13.5.2 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.72.1 (d5c2e9c34 2023-09-13)
    ✔ Cargo: 1.72.1 (103a7ff2e 2023-08-15)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 18.16.0
    - pnpm: 8.6.10
    - yarn: 1.22.19
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.16
    - tauri-build [RUST]: 2.0.0-alpha.10
    - wry [RUST]: 0.33.1
    - tao [RUST]: 0.22.3
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.16

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Additional context
Is the only way to receive events with tauri in the remote domain the only way to add them to the `dangerousRemoteDomainIpcAccess` setting? What should I do if I cannot specify a domain?
Electron can receive events on any site using`contextbridge` and `ipcRender`. How do I implement the same functionality in Tauri?

I am interested in Tauri and am considering it to be introduced into our project.
Please reply.

**Comment by FabianLars** [comment]
Hi 👋 

Can you try setting the domain as just `"www.google.com"` or `"google.com"` please?

**Comment by gusxodnjs** [comment]
@FabianLars 
It was fixed by modifying it to `www.google.com`. Thank you.

Please check the rest of the inquiries as well.

**Comment by FabianLars** [comment]
> Is the only way to receive events with tauri in the remote domain the only way to add them to the dangerousRemoteDomainIpcAccess setting?

Yes.

> What should I do if I cannot specify a domain?

You can define it at runtime in Rust: https://docs.rs/tauri/latest/tauri/scope/ipc/struct.Scope.html.

> Electron can receive events on any site usingcontextbridge and ipcRender. How do I implement the same functionality in Tauri?

With the "official" apis, not at all, the closest thing with tauri's apis is changing the scope at runtime on demand as said above. Alternatives like spinning up a seperate webserver probably doesn't work with every site if they configured a CSP or something (you can always inject code into websites no matter the ipc scope, either via the initialization_script setting or `window.eval()` (the rust api, not the js one nobody should use).
