### ISSUE TITLE
[bug] Is tauri working in dll or not?

### ISSUE THREAD

**Issue by MCapricorns** [tauri-apps/tauri#8122]
### Describe the problem

I change  Cargo.toml
 [lib]
crate-type= ["dylib"]
path="src/main.rs"

i change main.rs   Main function to DllMain
 run cargo tauri build
finally, i get a xx.dll  
and i use x64dbg to load this dll. dll workd fine,but don't show tauri's windows.

### Describe the solution you'd like

i wanna use tauri in dll
is my wrong or currently version, tauri can't run in dll

**Comment by FabianLars** [comment]
Did you see the dll example in this repository? https://github.com/tauri-apps/tauri/tree/1.x/examples/tauri-dynamic-lib/src-tauri - i talked about it with another community member a few weeks ago and it was still working for them. Maybe you can spot the difference between it and your project :)

Also, afaik you actually have to call the exposed function, just loading the dll itself isn't enough (maybe i misunderstood what you tried though).

**Comment by MCapricorns** [comment]
> Did you see the dll example in this repository? https://github.com/tauri-apps/tauri/tree/1.x/examples/tauri-dynamic-lib/src-tauri - i talked about it with another community member a few weeks ago and it was still working for them. Maybe you can spot the difference between it and your project :)
> 
> Also, afaik you actually have to call the exposed function, just loading the dll itself isn't enough (maybe i misunderstood what you tried though).

Sorry ,i didn't see the all of example. this is for me... sorry again.
this issues is end.
