### ISSUE TITLE
[bug] windows 11 show nothing,is empty

### ISSUE THREAD

**Issue by SeaIsCoder** [tauri-apps/tauri#8126]
### Describe the bug

1.windows 11 show nothing,is empty.
2. just quick start example ,use cargo
[https://tauri.app/v1/guides/debugging/application#opening-devtools-programmatically](url)

![image](https://github.com/tauri-apps/tauri/assets/16337003/fd3db6f9-3d6b-4764-87a0-8862a8a3db7c)

### Reproduction

1.
	rustup toolchain install stable-x86_64-pc-windows-gnu
2.
	rustup default stable-x86_64-pc-windows-gnu
3.
      cargo install tauri-cli
4.
    rustup target add wasm32-unknown-unknown
5. 
    rustup default stable-msvc	
6.
    cargo create-tauri-app
7. 
    cargo tauri dev 
9. 
   show nothing,jush blank window.  

### Platform and versions

```text
D:\works\rustWorks\pcys>cargo tauri info
WARNING: no lock files found, defaulting to npm

[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 118.0.2088.69
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 16.20.2
    - yarn: 1.22.18
    - npm: 9.6.7

[-] Packages
    - tauri [RUST]: 1.5.2
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.5
    - tauri-cli [RUST]: 1.5.6
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 1.5.6

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
```

**Comment by amrbashir** [comment]
Can you try reinstalling webview2?

**Comment by xiaguangbo** [comment]
@amrbashir 
OS："Linux debian 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux".
This is also the case, but it can be displayed when you open the IP with a browser

**Comment by SeaIsCoder** [comment]
reinstalling webview2,still not work,but in window11 sanbox, it work well。
i found ,one less thread in window11 than window11 sanbox.
