### ISSUE TITLE
[bug] Missing style after packaging

### ISSUE THREAD

**Issue by teash1rt** [tauri-apps/tauri#8127]
### Describe the bug

I‘m building a project with `vue3+vite+less+tauri`. Here is my repo [teashirtt/lulu](https://github.com/teashirtt/lulu)

The styles is normal when running `pnpm tauri dev`. But after running `pnpm tauri build` the apps lost its styles.

I checked the Developer Tools, and found that the `head` tag of the HTML structure did not include any styles in the Vue component, I think Styles don't get bundled

I checked this similar issue [[bug] Styles don't get bundled #3427](https://github.com/tauri-apps/tauri/issues/3427), and I set `csp: null` in `tauri.conf.json`  but it did not work

with `pnpm tauri dev`

- view
![Snipaste_2023-10-29_00-53-39](https://github.com/tauri-apps/tauri/assets/95997368/cecf0274-e11a-4a92-bdeb-fa98162a1dd0)

- head tag
![dev-head](https://github.com/tauri-apps/tauri/assets/95997368/b7be97a4-dc2e-4596-b16a-0549588328f7)

with `pnpm tauri build`

- view
![build](https://github.com/tauri-apps/tauri/assets/95997368/3a290862-a7ed-4207-8bce-fd47ca7801d2)

- head tag
![build-head](https://github.com/tauri-apps/tauri/assets/95997368/9c29e2c4-cf0b-45af-b1e7-64f83a6928e8)

`tauri.config.json`
```json
{
    "build": {
        "beforeDevCommand": "pnpm dev",
        "beforeBuildCommand": "pnpm build",
        "devPath": "http://localhost:1420",
        "distDir": "../dist",
        "withGlobalTauri": false
    },
    "package": {
        "productName": "lulu",
        "version": "0.0.0"
    },
    "tauri": {
        "allowlist": {
            "all": true,
            "shell": {
                "all": false,
                "open": true
            }
        },
        "bundle": {
            "active": true,
            "targets": "all",
            "identifier": "com.tauri.build",
            "icon": [
                "icons/32x32.png",
                "icons/128x128.png",
                "icons/128x128@2x.png",
                "icons/icon.icns",
                "icons/icon.ico"
            ]
        },
        "security": {
            "csp": null
        },
        "windows": [
            {
                "fullscreen": false,
                "resizable": true,
                "title": "lulu",
                "width": 1300,
                "minWidth": 700,
                "height": 800,
                "minHeight": 400,
                "center": true,
                "decorations": false,
                "fileDropEnabled": false
            }
        ]
    }
}
```

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 118.0.2088.69
    ✔ MSVC: Visual Studio ���ɹ��� 2022
    ✔ rustc: 1.72.0 (5680fa18f 2023-08-23)
    ✔ Cargo: 1.72.0 (103a7ff2e 2023-08-15)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 16.16.0
    - pnpm: 8.7.1
    - yarn: 1.22.19
    - npm: 9.8.0

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0 (outdated, latest: 1.5.1)
    - @tauri-apps/cli [NPM]: 1.4.0 (outdated, latest: 1.5.6)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Hmm, that's an interesting one. I didn't find a solution yet but wanted to share 2 things before heading off for today:
1) tauri bundles all assets into the binary as expected, including the css.
2) I can see the same issue when i change `distDir` to `http://localhost:4173`, and then run `pnpm preview` before opening the built app. Opening that same url in Edge, which is effectively the same as the Windows webview however works completely fine...
3) The index.html file (in distDir) contains an import for the index.css statement, edge and firefox also show that, but in webview2/tauri it's gone (another css import is still there so it's not stripping all css imports)
4) Instead of the index.css it adds a stylesheet import for a single theme, which the other browsers don't do.

I know this doesn't really help but i really need to go to sleep now. I hope someone else spots something i'm missing...

**Comment by teash1rt** [comment]
I tried to fix this problem but I failed.
I builded some of other tauri+vue3 github projects, and didn't found losing style problem like this, so it must be something wrong with my project(maybe config?)

**Comment by vasfvitor** [comment]
before:
  <img width="50%" src="https://github.com/tauri-apps/tauri/assets/61759797/dbdd5a6e-e72f-493a-a289-4ca34d847644">

Thanks to @FabianLars mentioning "single theme" I went and look to the code and removed the logic that handles theme (about 5 lines) and it worked, finally I pinned down to line 43 on `src/App.vue `(have to remove the import on line 27 too)

remove these:
`27 import { changeTheme } from './utils/changeTheme'`
`43 changeTheme(settingsStore.settings!.display.md_code_theme)`

  <img width="50%" src="https://github.com/tauri-apps/tauri/assets/61759797/01a1f0e8-4c8a-4edc-9659-fa21d8296880">

So, not sure how this solves the issue, but it's a lead. I'll do some experiments on the `changeTheme.ts` file

edit: As it is, the selector on `const oldLink` is too broad, consider this or an improved version:

 `const oldLink = head.querySelector('link[rel="stylesheet"][href*="theme"]');`

Keep in mind that "theme" is referering to the path /theme in the css href.

**Comment by teash1rt** [comment]
@vasfvitor that really helps! thank u!
I see what going on with this problem.
in my `changeTheme.ts`:

```ts
export const changeTheme = (theme: CodeTheme) => {
    const head = document.head
    const oldLink = head.querySelector('link[rel="stylesheet"]')
    if (oldLink) {
        head.removeChild(oldLink)
    }
    const newLink = document.createElement('link')
    newLink.setAttribute('type', 'text/css')
    newLink.setAttribute('rel', 'stylesheet')
    newLink.setAttribute('href', `themes/${theme}.css`)
    head.appendChild(newLink)
}
```
I try to use this function to change my project style theme, when I run `pnpm tauri dev`, it's normal because there is only one element in head tag satisfied this condition:

```ts
const oldLink = head.querySelector('link[rel="stylesheet"]')
```
- with `pnpm run dev` there is only one `rel="stylesheet"`
![issues1](https://github.com/tauri-apps/tauri/assets/95997368/513e4681-6ca7-411b-a42d-eb64ee702d6e)

then I commented out all the content inside this function, and  run `pnpm tauri build` to see the content in head tag and found different content in head tag. I think that's  because @FabianLars mentioned this "Instead of the index.css it adds a stylesheet import for a single theme, which the other browsers don't do." thing.

- with `pnpm run build` there are three `rel="stylesheet"`
![issues2](https://github.com/tauri-apps/tauri/assets/95997368/6c0b3222-06a8-4c6a-8d73-09e148be8ac0)

So after building, when I use `changeTheme`  function it will delete other styles that it shouldn't have deleted.

I have solved this problem by:
```ts
// bug version
const oldLink = head.querySelector('link[rel="stylesheet"]')

// correct version
const oldLink = head.querySelector('link[rel="stylesheet"][href*="themes"]')
```
It will uniquely match the label I want.

**Comment by kingwingfly** [comment]
Sorry to put some content not so related to this issue.

Just for whom may search with `tauri + react router lost style/css after packaging` here: 
```
import { Links } from "react-router";

<head>
  <meta charSet="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <Links /> // <-- importand
</head>
```
You may need add `Links` here, or it doesn't add <link ...stylesheet> related tag.
