### ISSUE TITLE
[bug] Discord invite not working

### ISSUE THREAD

**Issue by simula-r** [tauri-apps/tauri#8132]
### Describe the bug

The links to the Discord Server are invalid.

Both from the website and here on Github

### Reproduction

Go to website footer links and here

### Expected behavior

Link brings you to a valid discord server invite

### Platform and versions

```text
n/a
```

**Comment by FabianLars** [comment]
They still work fine on my devices🤔(we're talking about this one right? https://discord.com/invite/tauri - That's the only one i can find)

**Comment by simula-r** [comment]
Yes, this is what I see
<img width="1512" alt="image" src="https://github.com/tauri-apps/tauri/assets/18093452/3f2c8062-128b-4792-8194-3f95940e2ce1">

**Comment by simula-r** [comment]
But joining from the discord app and typing the url works! 🤔

**Comment by FabianLars** [comment]
I don't think there's anything we can do (i'd prefer not to switch out the link until more people hit this issue). Therefore i'm closing this and hope it resolves itself :/ Thanks for the report nonetheless.

**Comment by snowmead** [comment]
I have this error as well.
