### ISSUE TITLE
[bug][v2] Problem with transparent background when migrating

### ISSUE THREAD

**Issue by caiocinel** [tauri-apps/tauri#8133]
### Describe the bug

I recently decided to migrate a project I made for testing to version v2 and found a problem with transparent windows, in which they only become truly transparent if their size is redefined, like:

The window is defined as "800x600" in tauri.conf.json, but in setup its size is reset to "1280x800", so only the remaining size is transparent, as in the photo below:

![image](https://github.com/tauri-apps/tauri/assets/60858720/8fe18b43-8570-4446-878d-288be121c689)

I managed to get around the problem by setting the window size to zero, and then resetting it to the originally desired value, as below:
```

let window = app.get_window("main").unwrap();        

window.set_size(Size::Logical(tauri::LogicalSize { width: 0.0, height: 0.0})).unwrap();
    
window.set_size(Size::Logical(tauri::LogicalSize { width: 1280.0, height: 800.0})).unwrap();
    
``` 
![image](https://github.com/tauri-apps/tauri/assets/60858720/62cfa8e9-8cb0-4aba-8614-783c515e3d4f)

### Reproduction

create a project using create-tauri-app and set "transparent" property to "true" in tauri.conf.json

### Expected behavior

The window background becoming completely transparent as below:
![image](https://github.com/tauri-apps/tauri/assets/60858720/8f78bc4d-451e-49af-90f4-9601da7d2f7f)

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 118.0.2088.69
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.74.0-nightly (7b4d9e155 2023-09-28)
    ✔ cargo: 1.74.0-nightly (e6aabe8b3 2023-09-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: nightly-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.6.1
    - npm: 9.8.1

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.17
    - tauri-build [RUST]: 2.0.0-alpha.11
    - wry [RUST]: 0.34.2
    - tao [RUST]: 0.23.0
    - tauri-cli [RUST]: 2.0.0-alpha.17
    - @tauri-apps/api [NPM]: 1.5.1
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.17

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../build
    - devPath: http://localhost:9000/
    - framework: Svelte
    - bundler: Vite
```

### Stack trace

```text
not aplicable
```

### Additional context

Before the migration, my project was in version 1.4

**Comment by FabianLars** [comment]
Hi 👋 Can you disable `shadows` for the window? They are enabled by default in v2 but cause the same issue the "normal" decorations do with transparent backgrounds (the thing you're seeing).

If you want to keep those shadows, you can just add them back once the window was created, it just can't be created with them.

**Comment by caiocinel** [comment]
> Hi 👋 Can you disable `shadows` for the window? They are enabled by default in v2 but cause the same issue the "normal" decorations do with transparent backgrounds (the thing you're seeing).
> 
> If you want to keep those shadows, you can just add them back once the window was created, it just can't be created with them.

Keeps the same
https://github.com/Ziguiriguidum/Store/blob/main/src-tauri/src/main.rs

**Comment by FabianLars** [comment]
your repository is private

**Comment by caiocinel** [comment]
> your repository is private

I made the repository public

**Comment by FabianLars** [comment]
Okay sorry, i should have been more specific. In v2, the window-shadows crate is now part of tauri _and_ enabled by default. So what i'm asking you to do is to add `"shadow": false` in the window config here: https://github.com/Ziguiriguidum/Store/blob/main/src-tauri/tauri.conf.json#L57.
You can still enable it at runtime like you did before (though you can use [`window.set_shadow`](https://docs.rs/tauri/2.0.0-alpha.17/tauri/window/struct.Window.html#method.set_shadow) instead of the crate).

**Comment by caiocinel** [comment]
> Okay sorry, i should have been more specific. In v2, the window-shadows crate is now part of tauri _and_ enabled by default. So what i'm asking you to do is to add `"shadow": false` in the window config here: https://github.com/Ziguiriguidum/Store/blob/main/src-tauri/tauri.conf.json#L57. You can still enable it at runtime like you did before (though you can use [`window.set_shadow`](https://docs.rs/tauri/2.0.0-alpha.17/tauri/window/struct.Window.html#method.set_shadow) instead of the crate).

"Window" property is not recognized
Error `tauri.conf.json` error on `tauri > windows > 0`: Additional properties are not allowed ('shadow' was unexpected)

**Comment by FabianLars** [comment]
Your package.json and it's lockfile still list 1.5 for the tauri API and cli, can you update them to v2 too and try again?

**Comment by caiocinel** [comment]
> Your package.json and it's lockfile still list 1.5 for the tauri API and cli, can you update them to v2 too and try again?

Oh, I didn't realize, thank you. The issue was resolved by disabling the "shadow" property in tauri.conf.json. I was having a caching problem, I ran "cargo clean" and the problem with the property not existing was resolved. Thanks for your help :)
