### ISSUE TITLE
[bug] v2 - Can't create new window in windowsos

### ISSUE THREAD

**Issue by drl990114** [tauri-apps/tauri#8143]
Context: i has @tauri-apps/api : "^2.0.0-alpha.8", and that the above problem did not occur in v1.

```rs
	// This works fine when I first call in tauri setup

    let mut main_win = WindowBuilder::new(&app, "markflowy", WindowUrl::App("index.html".into()))
        .title("markflowy")
        .resizable(true)
        .fullscreen(false)
        .inner_size(1200.0, 800.0)
        .min_inner_size(400.0, 400.0);
```

In js: 
```js
import { Window } from '@tauri-apps/plugin-window';

const appWindow = new Window('theUniqueLabel', {
		 url: './setting',
 });

// When the window is opened for the second time, it cannot be opened normally whether in rs or js.
```

error info :
failed to create webview: WebView2 error: WindowsError(Error { code: HRESULT(0x8007139F), message: "组或资源的状态不是执行请求操作的正确状态。" })

In rust

```rs
	// The second call will cause an error， The window has a white screen and cannot be closed

    let mut main_win = WindowBuilder::new(&app, "markflowy", WindowUrl::App("index.html".into()))
        .title("markflowy setting")
        .resizable(true)
        .fullscreen(false)
        .inner_size(1200.0, 800.0)
        .min_inner_size(400.0, 400.0);
```

<img width="1009" alt="image" src="https://github.com/tauri-apps/plugins-workspace/assets/48054715/8fac2f27-ff3f-4193-be48-487a3d5e5492">

[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 117.0.2045.60
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ Cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-pc-windows-msvc (default)
    - node: 20.8.0
    - yarn: 3.6.1
    - npm: 10.1.0

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.15
    - tauri-build [RUST]: 2.0.0-alpha.9
    - wry [RUST]: 0.33.0
    - tao [RUST]: 0.22.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.14

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:3000/
    - framework: React

**Comment by amrbashir** [comment]
Seems like this has been fixed on webview2 side, see https://github.com/tauri-apps/tauri/issues/8196#issuecomment-1897674662

Please update your webview2 version and try again.
