### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by jackiealex** [tauri-apps/tauri#8155]
### Describe the bug

use tauri-app v2.0 to create project

run ```pnpm run tauri dev```

then error occurred

### Reproduction
run ```pnpm run tauri dev```, because  @tauri-apps/api of 2.0.0-alpha.11 removed tauri files

### Platform and versions

```text
@tauri-apps/api: 2.0.0-alpha.17

[2.0.0-alpha.11](https://www.npmjs.com/package/@tauri-apps/api/v/2.0.0-alpha.11)

```

### Stack trace

```text

[vite] Internal server error: Missing "./tauri" specifier in "@tauri-apps/api" package

```

### Additional context

<img width="787" alt="image" src="https://github.com/tauri-apps/tauri/assets/1441842/d0aa190f-421d-4562-9d36-6e532f320de0">

-

**Comment by Noxdor** [comment]
I am running into the same issue following the guide on https://next--tauri.netlify.app/next/mobile/

**Comment by FabianLars** [comment]
The templates are being updated here: https://github.com/tauri-apps/create-tauri-app/pull/513

To fix it in your own projects, rename the `tauri` module to `primitives`, for example `import {invoke} from "@tauri-apps/api/primitives"`

**Comment by Noxdor** [comment]
Awesome, this worked like a charm! A couple of issues I ran into during my test, that you guys are probably aware of, I just wanted to share them anyway for the chance you're not:
1. Updating the UI doesn't update the app yet, so if I say change the function `greet` to print something else to the console, I will get the hmr message in my terminal from Vite, but the change is not reflected in the app on my phone until I fully restart the process with `pnpm tauri android dev`.
2. Android studio starts every time I run the process, even when I don't pass `--open` to `pnpm tauri android dev`, which I thought I shouldn't have to?
3. Once the process crashes for any reason, my terminal becomes unusable, I can't exit it, I can't type new commands, I have to fully kill it.

Besides that, this looks soooo promising and already works so great! The fact that I can run this already on my phone without real issues is just amazing, can't wait for beta and stable :rocket:

**Comment by FabianLars** [comment]
1. Yeah, i noticed that too. I _think_ it used to work though so ig we broke something.
2. i don't see this on my end and this is the first time i hear this, i wonder what's happening 🤔 
3. I had a similar problem back when we still checked for the cli version. I guess that wasn't the only thing that could cause this issue :/

Anyway, thanks for these pointers!
