### ISSUE TITLE
[feat] continually raising `tauri://file-drop-hover` event and providing current cursor position

### ISSUE THREAD

**Issue by MagicCrazyMan** [tauri-apps/tauri#8156]
### Describe the problem

i am working on an app which is available to highlight some specified html elements while dragging & dropping files (and i need the absolute file path). But i found that `tauri://file-drop-hover` event only happens once when moving file from outside into inside of the window, and did not raise again while moving inside the winodow, Is it possible to continually raise`tauri://file-drop-hover` and tell me the newly cursor position?

BTW: I need the absolute path of the dropped file, it is not a solution to disable `fileDropEnabled` since the chromium native drag & drop feature does not giving me that. or maybe there is some other solution?

### Describe the solution you'd like

continually raising `tauri://file-drop-hover` and providing current cursor position

**Comment by jaydevelopsstuff** [comment]
Any updates on this? Reactive drag hovering is only possible if this is implemented somehow and `tauri://file-drop-hover` is essentially useless without this, even with the position provided in Tauri 2.0.

**Comment by hut36** [comment]
+1

**Comment by denjell-crabnebula** [comment]
Have you seen https://github.com/crabnebula-dev/drag-rs

**Comment by jaydevelopsstuff** [comment]
> Have you seen https://github.com/crabnebula-dev/drag-rs

@denjell-crabnebula I'm not sure that repo pertains to this. This is an issue with Tauri 2.0 (1.0 drop event doesn't even have cursor pos iirc) and to my most recent knowledge, drag-rs only supports 1.x and is only for initiating a drag, not handling dragover or drop events.

**Comment by jaydevelopsstuff** [comment]
@amrbashir I see that Wry has had the necessary changes made, any progress on the Tauri side of things?

**Comment by amrbashir** [comment]
being worked on in https://github.com/tauri-apps/tauri/pull/9100
