### ISSUE TITLE
[bug] [alpha.17] [windows] completely broken if config.package.version is None

### ISSUE THREAD

**Issue by kris-ava** [tauri-apps/tauri#8164]
### Describe the bug

In case of no `version` field in the config, the whole app never loads on Windows. According to the docs this field can be set to None in which case it should default to whatever is present in `package.json`

### Reproduction

Run `npm create tauri-app@latest --alpha`.
Remove `version: "0.0.0"` from tauri.conf.json (and the preceeding comma)
Run `tauri dev`

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.20348 X64
    ✔ WebView2: 118.0.2088.76
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.72.0 (5680fa18f 2023-08-23)
    ✔ cargo: 1.72.0 (103a7ff2e 2023-08-15)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.13.0
    - yarn: 1.22.19
    - npm: 8.19.3

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.17
    - tauri-build [RUST]: 2.0.0-alpha.11
    - wry [RUST]: 0.34.2
    - tao [RUST]: 0.23.0
    - @tauri-apps/api [NPM]: 2.0.0-alpha.11
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.17

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - bundler: Vite
```

**Comment by FabianLars** [comment]
> According to the docs this field can be set to None in which case it should default to whatever is present in package.json

If it's not set it will default to the value in Cargo.toml. To make it use the value in package.json you need to set the version field to a path to said package.json file.

**Comment by kris-ava** [comment]
The current behavior is that instead of it being set to the value in
Cargo.toml, the app never loads on windows. Sorry for the confusion.

**Comment by FabianLars** [comment]
right yeah, i got that. I didn't address the actual issue in my comment but opened a [PR](https://github.com/tauri-apps/tauri/pull/8168) instead - there was no confusion on my side, just wanted to clear up that package.json fallback behavior while i was here :)

p.s. thanks for the report btw!
