### ISSUE TITLE
[bug]  2.0.0-alpha.4 error Error `tauri.conf.json` error on `tauri`: Additional properties are not allowed ('allowlist', 'updater' were unexpected)

### ISSUE THREAD

**Issue by aibihub** [tauri-apps/tauri#8167]
### Describe the bug

The version I am using is 2.0.0-alpha.4. When I created mobile applications for android and ios【 yarn tauri android init
  yarn tauri ios init】I got an error.
     tauri android init
       Error `tauri.conf.json` error on `tauri`: Additional properties are not allowed ('allowlist', 'updater' were unexpected)
         tauri ios init
       Error `tauri.conf.json` error on `tauri`: Additional properties are not allowed ('allowlist', 'updater' were unexpected)

### Platform and versions

```text
pm run tauri info

> mm@0.0.0 tauri
> tauri info

       Error `tauri.conf.json` error on `tauri`: Additional properties are not allowed ('allowlist', 'updater' were unexpected)
```

**Comment by FabianLars** [comment]
Hi, we have a wip migrate guide here: https://beta.tauri.app/guides/upgrade-migrate/from-tauri-1/#tauri-configuration - also alpha.4 isn't really supported anymore so i'd suggest to upgrade all packages to their latest version.
Furthermore, if your app is still pretty new, i'd suggest to re-run `yarn create tauri app --alpha` to have a ready to use project.
