### ISSUE TITLE
ReadableStream for CLI

### ISSUE THREAD

**Issue by thienpow** [tauri-apps/tauri#818]
it would be good to be able to get ReadableStream from CLI function call.

```javascript
let streamResult[]

let res = await process.execute("ipfs", ["add", `${file.path}`])
let reader = res.progress.getReader()  //not necessary be named as "progress", maybe "status"
while (true) {
  const {done, value} = await reader.read();
  if (done) {
     break;
  }
  
  .... then, push the value chunk to streamResult[]
 }
```

some vital data of a status like after calling to "ipfs daemon" is needed, currently it won't even return a single line of result, because it stay running, so the call never come back, it only comeback when it is terminated or crashed... actually this could be listed as bug, bcos the Rust code stay waiting there forever for the daemon.

**Comment by lucasfernog** [comment]
Closed by #1408. Check out https://tauri.studio/en/docs/api/js/modules/shell
