### ISSUE TITLE
[bug] OIDC Flow doesnt work for prod

### ISSUE THREAD

**Issue by michaelholstdev** [tauri-apps/tauri#8181]
### Describe the bug

We use a keycloak for access management and the flow is working fine in development mode. But when I build a production version, it tooks pretty long to redirect to keycloak and on the keycloak page itself I cant press the submit button. This happens just in the production build and it does not throw any errors.

### Expected behavior

OIDC flow is working as expected, the submit button can be pressed and will redirect.

### Platform and versions

```text
Environment
    - OS: Mac OS 13.5.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.71.1 (eb26296b5 2023-08-03)
    ✔ cargo: 1.71.1 (7f1d04c00 2023-07-29)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 18.12.1
    - yarn: 3.3.1
    - npm: 9.4.2

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.17
    - tauri-build [RUST]: 2.0.0-alpha.11
    - wry [RUST]: 0.34.2
    - tao [RUST]: 0.23.0
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.17

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:3000/
    - framework: React
    - bundler: Webpack

Also tried the latest stable release, same behaviour.
```

**Comment by mrmandarin2002** [comment]
^^ I'm having the exact same issue. For some strange reason, if I have my local dev server running alongside with the production native app, redirects within the native app work no problem.

**Comment by FabianLars** [comment]
if you create a debug build via `tauri build --debug` (if you use npm it's `npm run tauri build -- --debug`), output in `target/debug/`, does the devtools console report anything noteworthy?

I assume whatever endpoint you're hitting doesn't like the custom scheme url (`tauri://...`)

**Comment by dhan2325** [comment]
I've had a similar issue, where I am able to log in if I have a single local dev server running alongside it and manually pass in a redirect uri that points to my localhost dev server. I tried enabling the webview console and built it with the debug option, I didn't see anything that I thought was noteworthy in the build logs. When redirecting to the localhost server, I get the following error:
```
Unhandled Promise Rejection: Scope not defined for window `main` and URL `...' (edited) 
```

**Comment by michaelholstdev** [comment]
Ive solved the problem for me, I need to add the tauri protocol and web origin in keycloak:

added `tauri://*` to `valid redirect urls` 
added `tauri://localhost` to `web origins`

Afterwards everything worked.
