### ISSUE TITLE
[bug] An error occurred after executing the (cargo tauri build/npm run tauri build) bundler

### ISSUE THREAD

**Issue by trookie2000** [tauri-apps/tauri#8184]
### Describe the bug

![image](https://github.com/tauri-apps/tauri/assets/109945614/5306d01a-a5a2-4ed9-93f3-626eac961520)
This is my directory structure:
![image](https://github.com/tauri-apps/tauri/assets/109945614/8000b7f4-82d2-47d9-8709-f9502bf32a2b)

### Expected behavior

App Publishing successfully

### Platform and versions

```text
{
  "build": {
    "beforeDevCommand": "npm run dev",
    "beforeBuildCommand": "npm run build",
    "devPath": "../src",
    "distDir": "../dist",
    "withGlobalTauri": true
  },
  "package": {
    "productName": "discoRobot",
    "version": "0.0.0"
  },
  "tauri": {
    "allowlist": {
      "all": false,
      "shell": {
        "all": false,
        "open": true
      },
      "http": {
        "all": true, 
        "request": true 
      },
      "fs": {
        "all": true, 
        "readFile": true,
        "writeFile": true,
        "readDir": true,
        "copyFile": true,
        "createDir": true,
        "removeDir": true,
        "removeFile": true,
        "renameFile": true,
        "exists": true,
        "scope": []
      }
    },
    "bundle": {
      "active": true,
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "identifier": "com.tauri.build",
      "targets": "all"
    },
    "security": {
      "dangerousRemoteDomainIpcAccess": [
        {
          "scheme": "src/setting.html",
          "domain":"src/setting.html",
          "windows": ["my-app-name"]
        }
    ],
      "dangerousDisableAssetCspModification":true,
      "csp":null,
      "freezePrototype": true
     
    },
   
    "updater": {
      "active": false
    },
    "windows": [
      {
        "fullscreen": false,
        "resizable": true,
        "title": "求求了!一次跑通不出bug!",
        "width": 1000,
        
        "height": 700,
        "center":true,
        "decorations": true
      }
     
    ], 
    "systemTray": {
      "iconPath": "icons/icon.png",
      "iconAsTemplate": true
    }
  }
}
```

### Stack trace

```text
no response
```

**Comment by FabianLars** [comment]
Vite typically expects the index.html file to be next to the package.json and _not_ in the src/ directory. Can you try that?

If that doesn't help, please try to provide a minimal reproduction repo, or at least you vite config (btw, this is a frontend issue, nothing tauri specific so far - if you run `npm run build` it should give you the same error)

**Comment by trookie2000** [comment]
This is my vite config
![image](https://github.com/tauri-apps/tauri/assets/109945614/adda5bb9-f07c-4160-a677-39c7cb96ffa9)


I tried to put index.html from src in the root directory (in the same level as package.json) and got an error:
![image](https://github.com/tauri-apps/tauri/assets/109945614/f3a0a63d-e31e-43ca-86c7-3d5940d47ed1)


Is it because some of the paths in the tauri config are not set correctly？

**Comment by FabianLars** [comment]
> Is it because some of the paths in the tauri config are not set correctly？

No, as i said, this has nothing to do with Tauri. This error happens before Tauri does anything. If you move the index.html file back to the root you'll also have to update the imports in that file to include the `src/` prefix.

On a similar topic, your additional html files will likely _not_ end up in the `dist` dir where they have to be for tauri to pick them up. If they don't import any npm packages i think it would be fine to move them in a `public/` dir (again next to package.json), otherwise you may have to look at this: https://vitejs.dev/guide/build.html#multi-page-app

**Comment by trookie2000** [comment]
> > Is it because some of the paths in the tauri config are not set correctly？
> 
> No, as i said, this has nothing to do with Tauri. This error happens before Tauri does anything. If you move the index.html file back to the root you'll also have to update the imports in that file to include the `src/` prefix.
> 
> On a similar topic, your additional html files will likely _not_ end up in the `dist` dir where they have to be for tauri to pick them up. If they don't import any npm packages i think it would be fine to move them in a `public/` dir (again next to package.json), otherwise you may have to look at this: https://vitejs.dev/guide/build.html#multi-page-app

Thank you very much!
