### ISSUE TITLE
Completely disabling security

### ISSUE THREAD

**Issue by nullchinchilla** [tauri-apps/tauri#820]
I have a fairly large Electron app that extensively AJAXes out to the open Internet, and uses webSecurity=false. It seems like with Tauri the app is sandboxed and cannot access the network except through Tauri's rudimentary `http` API.

Is there any way of completely disabling security? I like Tauri's smallness but don't want the sandboxing for the moment.

**Comment by lucasfernog** [comment]
Actually you can access the network, did you make some test and had an issue trying to do it?

**Comment by nothingismagick** [comment]
You can relax the CSP in `tauri.conf.json`, which will let your HTML do all the terrible things in the universe.

**Comment by nothingismagick** [comment]
The purpose of the `http` API is to provide a more secure method for the app to communicate outwards from within that secure zone. It is not rudimentary, it has a small footprint on purpose.

**Comment by nullchinchilla** [comment]
I put `default-src * 'unsafe-inline' 'unsafe-eval'; script-src * 'unsafe-inline' 'unsafe-eval'; connect-src * 'unsafe-inline'; img-src * data: blob: 'unsafe-inline'; frame-src *; style-src * 'unsafe-inline'` in my CSP, but I'm still getting 

```
ERROR XMLHttpRequest cannot load ... due to access control checks.
ERROR Origin http://localhost:3001 is not allowed by Access-Control-Allow-Origin.
```

**Comment by nothingismagick** [comment]
Can you try with `"csp": ""` ?

**Comment by nullchinchilla** [comment]
Yes, that worked.
