### ISSUE TITLE
[bug]  parameters transfer problem between frontend and rust .

### ISSUE THREAD

**Issue by oulaoba** [tauri-apps/tauri#8201]
### Describe the bug

frontend code 

```  javascript

async function rust_function(){
    await invoke("rust_function", { parameter_one: "parma_one" })
}

```

rust code 
``` rust
#[tauri::command]
async fn rust_function(parameter_one: String) -> String {
    format!("hello {}", parameter_one)
}
```

When i using this code call rust function, tauri tells me **[Error] Unhandled Promise Rejection: invalid args `parameterOne` for command `rust_function`: command rust_function missing required key parameterOne** .

![1](https://github.com/tauri-apps/tauri/assets/34548001/5d45c182-5ad3-4a16-b2de-8d2cb27f68fe)

The naming convention for rust parameters is to use underscores for word splitting , when i follow this rule .  the problem appear .

### Expected behavior

Is there any way we can disable this conversion through configuration ?

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 14.1.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.75.0-nightly (9d83ac217 2023-10-31)
    ✔ cargo: 1.75.0-nightly (b4d18d4bd 2023-10-31)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: nightly-x86_64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.14.0
    - yarn: 1.22.19
    - npm: 9.6.1

[-] Packages
    - tauri-cli [RUST]: 1.5.6
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 1.5.6
```

**Comment by FabianLars** [comment]
> Is there any way we can disable this conversion through configuration ?

Yes:
```rs
#[tauri::command(rename_all = "snake_case")] // <- This will force it to be parameter_one on the javascript side instead of parameterOne
async fn rust_function(parameter_one: String) -> String {
    format!("hello {}", parameter_one)
}
```

**Comment by oulaoba** [comment]
> > Is there any way we can disable this conversion through configuration ?
> 
> Yes:
> 
> ```rust
> #[tauri::command(rename_all = "snake_case")] // <- This will force it to be parameter_one on the javascript side instead of parameterOne
> async fn rust_function(parameter_one: String) -> String {
>     format!("hello {}", parameter_one)
> }
> ```

tks , i'm sorry about this issues , because I started writing code without carefully reading the documentation

**Comment by FabianLars** [comment]
No worries, that's on us. The rename_all config is a bit hidden in our docs :/
