### ISSUE TITLE
Aws-sdk error in release mode[bug] 

### ISSUE THREAD

**Issue by martonszabolcs** [tauri-apps/tauri#8217]
### Describe the bug

I use aws-sdk v2.1452.0 and it works well in dev mode, but when I build the app I get this message:

TypeError: undefined is not a constructor (evaluating 'new AcceptorStateMachine2()')

### Reproduction

yarn add aws-sdk
yarn tauri build
open app

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 14.0.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 21.0.0
    - pnpm: 8.10.2
    - yarn: 1.22.19
    - npm: 10.2.0

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.5.1
    - @tauri-apps/cli [NPM]: 1.5.6

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Can you create a build via `yarn tauri build --debug` and then start the app from target/debug/ ? It should be similar to the release build but with the devtools enabled so you can check the devtools console for errors.

**Comment by martonszabolcs** [comment]
Yes, I've checked it on build --debug and i get this blank screen and error:
<img width="807" alt="Képernyőfotó 2023-11-13 - 11 05 59" src="https://github.com/tauri-apps/tauri/assets/23526515/bb347cf9-9d39-49f9-8131-af2f86f52f9b">

**Comment by FabianLars** [comment]
Oh right, how else could you write the error message in the issue itself, sorry bout that 😅

**Comment by FabianLars** [comment]
As said on Discord, this doesn't seem to be a tauri specific issue so let's close this issue (this doesn't mean we can't write here anymore, it just signalizes that it's not tracked for tauri) and i'd recommend to reach out to the aws or vite communities, i'm sure they will be more helpful than us (i didn't see a single (open source) tauri app that used aws-sdk yet for example).
