### ISSUE TITLE
[bug] can't drag and drop files when app is launched with administrator privileges

### ISSUE THREAD

**Issue by alindas** [tauri-apps/tauri#8218]
### Describe the bug

i set 'fileDropEnabled' to true, but still can't drag and drop files. gui show not allow icon, and can not trigger the 'tauri://file-drop', 'tauri://file-drop-hover' events.

### Platform and versions

```text
tauri: 1.4.0
platform: windows
nodejs: 16.18.2
```

**Comment by alindas** [comment]
i have see something，my app runup need Administrator privileges，so when i try to drop normal file，it cant tragger 'file-drop' event。but when i try to drop some app files with administrator privileges, it works!

so anyone can show me how to Reduce the permissions for app operations? Specifically，i use the cli to create tauri-demo-app，it can be runup in normal permission，but my tauri app need administrator to show the gui!

**Comment by eythaann** [comment]
This is still unsolved, lol. I has the same issue now I can't allow drag and drop on my app that needs admin rights. (I'm using v2)

**Comment by thep0y** [comment]
It's really wierd, the Tauri app that was installed could normally drag and drop files a few days ago. There haven't been any updates to the app itself, nor does it seem like the system has been updated, but suddenly today it can no longer drag and drop files. Also, the installed app doesn't require administrator privileges.

**Comment by amrbashir** [comment]
This is an issue(? more like intended, idk) in Windows itself. You can reproduce the same behavior with Notepad. Run Notepad as administrator and then try dragging into it and notice it is prohibited as well.

also see https://superuser.com/questions/59051/drag-and-drop-file-into-application-under-run-as-administrator
