### ISSUE TITLE
[feat] How to get the method outside the absolute path of the file

### ISSUE THREAD

**Issue by alindas** [tauri-apps/tauri#8222]
### Describe the problem

Is there any other way to get the absolute path to the file than to select the form of the file through the dialog?

After I disabled tauri dragging, I can only get the File file with h5 drag, is there a way to get the local absolute path of the file?

i can't use tauri dragging, because my app use Administrator privileges in windows, that it can't Drag and drop files into the app

### Describe the solution you'd like

Use other methods to obtain the absolute path of the file

### Alternatives considered

The backend uses the File file directly, but this requires a lot of changes

**Comment by amrbashir** [comment]
You can use `resolve` to resolve a path relative to a `BaseDriectory` https://tauri.app/v1/api/js/path#resolve
