### ISSUE TITLE
[feat]  A new function to the fs api to read file meta data 

### ISSUE THREAD

**Issue by codad5** [tauri-apps/tauri#8239]
### Describe the problem

This is a request to be able to read file meta data using typescript or javascript from the frontend , without having to write my own custom script 

### Describe the solution you'd like

something like this 
```js 
import {readMetaData, exists ] from "@tauri-apps/api/fs";

if(await exists('avatar.png', { dir: BaseDirectory.AppData })) 
{
const metaData = await readMetaData('avatar.png', { dir: BaseDirectory.AppData })
 console.log({
   created: metaData.created , 
  lastModified: metaData.lastModifed , 
  ...others
 })
}

```

**Comment by FabianLars** [comment]
The fs-extra plugin has this: https://github.com/tauri-apps/plugins-workspace/tree/v1/plugins/fs-extra

For v2 we merged it into the fs plugin.

It _could_ be backported to v1 of course but for now there's the plugin above for those who don't want to write it themselves :)

**Comment by codad5** [comment]
Ok thanks , that would do
