### ISSUE TITLE
Render WebView on Top of Native GPU Rendered Content [feat] 

### ISSUE THREAD

**Issue by igagen** [tauri-apps/tauri#8246]
It would be pretty amazing if we could use the power of native GPU frameworks (Vulkan, DirectX, OpenGL, Metal, etc.) to render content with a WebView based UI on top (all in the same window).

While I realize we can use WebGL to achieve this, it's much more limited and often slower than native GPU frameworks. This would be another really nice win over Electron if it was supported and would be the best of both worlds in terms of the power of a native app with the ease of development for UI interfaces that the web gives us.

This would be pretty nice for games to render the game content using the native GPU and render UI with a web based approach.

**Comment by FabianLars** [comment]
This is more or less actively being worked on, for example: https://github.com/tauri-apps/tauri/issues/3662#issuecomment-1807219070
(Also, I'm 90% sure there already is some kind of tracking issue in this repo but I can't find it on my phone)

**Comment by murat-encord** [comment]
Is there a simple example? Or when an example becomes available can someone share a link here please.

**Comment by jtoy** [comment]
+1

**Comment by amrbashir** [comment]
v2 beta has `unstable` cargo feature, when enabled, will allow you to create a window and multiple webviews as children, so you can render OpenGL (or similar) on the window and place a webview on top of it. This however has limitation on X11 (see https://github.com/tauri-apps/tauri/issues/9220)

Here is an example: https://github.com/FabianLars/tauri-v2-wgpu
