### ISSUE TITLE
[feat]  add "Tauri/2.0" to original User Agent from web view which will be useful to decide whether the page is running on Tauri Environment

### ISSUE THREAD

**Issue by jyc5120** [tauri-apps/tauri#8247]
### Describe the problem

Now we could use the windows.userAgent to set custom userAgent from tauri.config.json.
but it will overwrite the original information. the original information is useful to get OS, devices, browser name.
now we have to change the config for every different platform.

### Describe the solution you'd like

Somewhere in webview component could be easy to add a Extra Information like Tauri/2.0 to user agent.

**Comment by amrbashir** [comment]
you can just check if `window.__TAURI__` is defined in v1, probably in v2, we will add an explicit const like `window.isTauri`

**Comment by daveycodez** [comment]
@amrbashir need this for server side checks.
