### ISSUE TITLE
[bug] Terminal pops up on certain windows versions for installer

### ISSUE THREAD

**Issue by YoHanGLoot** [tauri-apps/tauri#8261]
### Describe the bug

The installer seems to open up the terminal during on certain windows versions (including win 10 and 11)

### Reproduction

Just run the updater on certain windows 10, 11 versions and the terminal will pop up

### Expected behavior

The terminal does not pop up

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 119.0.2151.72
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.17.0
    - yarn: 1.22.19
    - npm: 9.6.7

[-] Packages
    - tauri [RUST]: 1.5.2
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.1
    - @tauri-apps/cli [NPM]: 1.5.6

[-] App
    - build-type: bundle
    - CSP: default-src *; media-src 'self' asset: https://asset.localhost; font-src *; img-src: *;
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by YoHanGLoot** [comment]
This has been a discussion at the discord server, but no solution was found except some kind of bug with powershell and flags from what I remember

**Comment by FabianLars** [comment]
upstream tracking issue: https://github.com/microsoft/terminal/issues/12464

**Comment by ahqsoftwares** [comment]
There's a window creation flags that can be applied on windows that hides the terminal window

**Comment by amrbashir** [comment]
This is no longer an issue in v2 for NSIS and .msi installers and for NSIS in v1.

However I will keep this open because in v1, we still use powershell to launch .msi installer.
