### ISSUE TITLE
[feat] "open" and "save" dialog i18n

### ISSUE THREAD

**Issue by czf0613** [tauri-apps/tauri#8266]
### Describe the problem

We are using "open" and "save" dialog to show a dialog.

On Linux platform, the "cancel", "open", "save" button does not use the correct language as the system use.
For example, I am using Debian 12 with Chinese Simplified, but the dialog shows in English (look at the red circle).
![dialog](https://github.com/tauri-apps/tauri/assets/46845934/8cdf20e5-25c7-46d8-bb1d-014b9374bc01)

### Describe the solution you'd like

Is it possible to change the language automatically? For example, the button text will shows "cancel" when the system is using "en", and shows "取消" when the system uses "zh"?

**Comment by czf0613** [comment]
This is a bug in “rfd” crate, I have already contributed the bug fix to the rfd’s repository.
Please check out version 0.14.0 of rfd, and this problem will be solved.

**Comment by amrbashir** [comment]
Thanks @czf0613, we can't update to 0.14 in tauri v1 unfortunately.

I will close this issue since dialogs have been moved to its own plugin in `plugins-workspace` repo and we are in the middle of updating to rfd 0.14.
