### ISSUE TITLE
WindowsBuilder doesn't work from #[tauri::command]

### ISSUE THREAD

**Issue by Randommist** [tauri-apps/tauri#8286]
This behavior is observed only in Windows. When I create a window using WindowsBuilder from #[tauri::command] a blank window with no content appears. However, if you use the js api WebviewWindow, then everything works fine.

![Безымянный](https://github.com/tauri-apps/tauri/assets/70176501/fb749c3f-175e-4489-b6d4-c30e7ff219fe)

```
#[tauri::command]
fn run(app_handle: tauri::AppHandle) {
    let _ = WindowBuilder::new(
        &app_handle,
        "test".to_string(),
        WindowUrl::External("https://google.com".parse().unwrap())
    )
    .title("Test")
    .build()
    .unwrap();
}

```

I want to clarify once again that if you use WindowBuilder when creating windows in fn main(), then everything works fine

### Platform and versions

```text
windows 10
```

**Comment by FabianLars** [comment]
This is a known issue:
![grafik](https://github.com/tauri-apps/tauri/assets/30730186/0fdc18d6-a8a5-4d72-9646-22e242dc1465)

I wonder if there are docs.rs styling things we can use to make that more obvious, it's really easy to overlook 🤔 

p.s. the solution is to change your command from `fn` to `async fn`
