### ISSUE TITLE
[bug] Usage of Tauri with Next.js + App Router breaks React.js lifecycle hook calls in Tauri prod output

### ISSUE THREAD

**Issue by JesseKoldewijn** [tauri-apps/tauri#8300]
### Describe the bug

Usage of useEffect (w/ or without an inner timeout/interval/invoke call) broken in production build output of tauri app when using Next.js 13+ w/ app router. App itself works just as expected in dev and prod (in browser, aside from the invoke call due to this being a tauri specific function)

### Reproduction

Init a new tauri app within a Next.js 13+ application and call a command invoke within a timeout inside of a useEffect in your initial page. For some reason (as far as I've noticed) any timeouts/inteval calls in the client side either don't get triggered or only get triggered after a app refresh (window reload). This behavior only happens in a prod build, not in a prod build in browser or dev mode in the tauri window.

### Expected behavior

What I would expect is that a production build in tauri wouldn't alternate in any core functionalities of frontend frameworks (like react). So for instance, I would expect a useEffect to just get fired in a production build of a tauri app. 

### Platform and versions

```text
[✔] Environment
    - OS: Arch Linux TEMPLATE_VERSION_ID X64
    ✔ webkit2gtk-4.0: 2.42.1
    ✔ rsvg2: 2.57.0
    ✔ rustc: 1.75.0-nightly (df871fbf0 2023-10-24)
    ✔ cargo: 1.75.0-nightly (d2f6a0485 2023-10-20)
    ✔ rustup: 1.26.0 (2023-05-04)
    ✔ Rust toolchain: nightly-x86_64-unknown-linux-gnu (default)
    - node: 18.17.1
    - pnpm: 8.11.0
    - yarn: 1.22.21
    - npm: 10.2.4
    - bun: 1.0.7

[-] Packages
    - tauri [RUST]: 1.5.2
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.1
    - @tauri-apps/cli [NPM]: 1.5.6

[-] App
    - build-type: bundle
    - CSP: default-src * 'self' data: tauri://*, https://app.graphite.dev
    - distDir: ../out
    - devPath: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Webpack
```

### Additional context

Github repo which can be used for reproduction as well: https://github.com/GlitchTech-Developments/GraphiteDesktop 

Repo isn't doing anything too fancy, just opening a new window with a remote url if a fetch succeeds after a timeout.

As a bit of extra context, I both build and test the production output locally on windows + linux but also cross-build using a github action. Both outputs behave the same.

**Comment by JesseKoldewijn** [comment]
I do have to mention, that this is indeed my first issue on the tauri repo. But I'm familiar with issue handling from the web dev side + also a contributor on the Next.js repo. Just as a headsup + background. Thanks to anybody that might be able to help me with this issue or point me to the right direction 😄

**Comment by FabianLars** [comment]
Hmm, this sounds like a CSP issue to me (the csp is not applied in tauri dev). Can you try a debug build via `tauri build --debug` (output in target/debug/ !) and check the devtools console for errors?

**Comment by Furizaa** [comment]
The app router of Next doesn't work well with `output: "export"`. Even if it would work with the pages you've got, once you add dynamic pages it breaks completely due to this bug in Next: https://github.com/vercel/next.js/issues/54393
I just migrated everything back to the page router because of this.

**Comment by JesseKoldewijn** [comment]
> The app router of Next doesn't work well with `output: "export"`. Even if it would work with the pages you've got, once you add dynamic pages it breaks completely due to this bug in Next: [vercel/next.js#54393](https://github.com/vercel/next.js/issues/54393) I just migrated everything back to the page router because of this.

Yeah known about that issue tbh but since it doesn't create any issues in this specific project I'll just keep it on the app router for now.

**Comment by JesseKoldewijn** [comment]
> Hmm, this sounds like a CSP issue to me (the csp is not applied in tauri dev). Can you try a debug build via `tauri build --debug` (output in target/debug/ !) and check the devtools console for errors?

Thanks for the suggestion man! seems I had a typo in the csp string that made the whole csp string invalid which triggered this odd behavior.

**Comment by JesseKoldewijn** [comment]
Closing issue since it's not a bug on Tauri's end. Behavior was created by having a typo in the security.csp config entry.
