### ISSUE TITLE
[bug] Cursor does not update on mouse down when clicking near the left or top of the window

### ISSUE THREAD

**Issue by RandomEngy** [tauri-apps/tauri#8301]
### Describe the bug

It appears that near the left and top of the window, if you click on an item and update the element's `cursor` property in the `pointerdown` handler, that change is not honored. It will continue to have the old cursor until the mouse is released.

The behavior is normal if you click on the same element, but near the middle of the window.

This works in browsers.

### Reproduction

https://github.com/RandomEngy/TauriCursorUpdateRepro

Click on the left side of the text. The cursor does not update on mouse down.

### Expected behavior

The cursor should update to 'move' on mouse down.

### Platform and versions

```text
yarn run v1.22.19
$ tauri info

[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 119.0.2151.72
    ✔ MSVC:
        - Visual Studio Build Tools 2017
        - Visual Studio Build Tools 2019
        - Visual Studio Build Tools 2022
        - Visual Studio Community 2022
    ✔ rustc: 1.74.0 (79e9716c9 2023-11-13)
    ✔ cargo: 1.74.0 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.12.1
    - yarn: 1.22.19
    - npm: 7.17.0

[-] Packages
    - tauri [RUST]: 1.5.2
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.6
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.1
    - @tauri-apps/cli [NPM]: 1.5.6

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - bundler: Vite
```

**Comment by amrbashir** [comment]
This is definitely a weird issue but I think it is an issue in the Webview2 and we can't fix it on our end unfortunately.

**Comment by RandomEngy** [comment]
Thanks, logged to https://github.com/MicrosoftEdge/WebView2Feedback/issues/4209
