### ISSUE TITLE
[bug] Frontend reloads on wake after sleep in Windows 11

### ISSUE THREAD

**Issue by ottosson** [tauri-apps/tauri#8304]
### Describe the bug

When I put my computer to sleep and wake it up again all state has been lost on the frontend of my Tauri application. The page seems to be reloaded. The state is till available for the "backend" of my application.

### Reproduction

On windows 11, start your Tauri app, then put the computer to sleep, then wake it up again. State on frontend is lost.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 119.0.2151.72
    ✔ MSVC:
        - Visual Studio Build Tools 2019
        - Visual Studio Professional 2022
    ✔ rustc: 1.74.0 (79e9716c9 2023-11-13)
    ✔ cargo: 1.74.0 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.8.1
    - npm: 10.2.0
```

**Comment by GregorGT** [comment]
Same behavior on our build: https://github.com/GregorGT/RuNo/
(Adding the comment to stay updated)

**Comment by ottosson** [comment]
This is still an issue for me.

Is this a WebView2 or a Tauri related issue?
This feels like it should be a much more common issue for people. Can't be just me and @GregorGT.

**Comment by ahqsoftwares** [comment]
@ottosson Sadly it is a chromium bug.
Basically I've tried at 3 browsers (brave, edge, firefox) and tauri

Brave, edge and tauri (windows) does reload the page
Firefox doesn't

That's my findings, lemme open source the code I've used

**Comment by ahqsoftwares** [comment]
Here's the repo https://github.com/ahqsoftwares/tauri-webview-reload-test

**Comment by ahqsoftwares** [comment]
Conversation: https://discord.com/channels/616186924390023171/731495028677148753/1246008474039619596

It apparently does not happen in production

**Comment by ottosson** [comment]
If it is a Chromium bug shouldn't Electron be affected? I haven't experienced it there.

**Comment by GregorGT** [comment]
The bug is not a damper for production. I stumbled on that as well @ahqsoftwares.
I am going to unsubscribe.... as this is not really a bug. It only happens in dev.

**Comment by ottosson** [comment]
Yup, same for me. A bit annoying but not as bad as I first feared.

**Comment by ahqsoftwares** [comment]
@ottosson soooo, I guess this issue is more/less resolved? Cuz it doesn't happen in prod

**Comment by ottosson** [comment]
> @ottosson soooo, I guess this issue is more/less resolved? Cuz it doesn't happen in prod

Ok I'll drop this for now 😉
Thanks for helping shed some light on the situation @ahqsoftwares

**Comment by bloor** [comment]
Thank god ! I was about to do some 2days custom code to "fix" the issue.
Also, weirdly enough, for me the dev is "fixed" if prod runs in parallel. It behaves as prod.
I believe it's because of HMR (hot reload) feature. That's what fks things up on wake/sleep.
