### ISSUE TITLE
[bug] [macOS] Tauri drag handler should wait for mouse up after double-click-to-maximize

### ISSUE THREAD

**Issue by lewisfm** [tauri-apps/tauri#8306]
### Describe the bug

After a drag area (titlebar) is double clicked on macOS, Tauri does not wait for the user to release their mouse before maximizing.

https://github.com/tauri-apps/tauri/assets/75394401/3c2104ef-3f02-4e59-880d-ae43ba6a6ad3

### Reproduction

With Tailwind:
```html
<div class="absolute top-0 left-0 right-0 h-10 bg-red-500" data-tauri-drag-region></div>
```

### Expected behavior

After double clicking, maximization is delayed until the mouse button is released. If the mouse button is moved before being released, the maximization is aborted.

https://github.com/tauri-apps/tauri/assets/75394401/5b8c836e-8e69-43bc-a2f0-59cfc80f5ca0

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 14.0.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.74.0 (79e9716c9 2023-11-13)
    ✔ cargo: 1.74.0 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.8.0
    - pnpm: 8.10.5
    - yarn: 1.22.21
    - npm: 10.1.0
    - bun: 1.0.6

[-] Packages
    - tauri [RUST]: 1.5.2
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.6
    - tao [RUST]: 0.16.5
    - tauri-cli [RUST]: 1.5.6
    - @tauri-apps/api [NPM]: 1.5.1
    - @tauri-apps/cli [NPM]: 1.5.6

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

### Additional context

The current behavior is expected on Windows. I haven't tested on any Linux distros.

**Comment by pewsheen** [comment]
The behavior is also the same as the GTK.

I think a workaround now might be called maximize and drag by yourself via IPC. Just copy the code from https://github.com/tauri-apps/tauri/blob/b3e53e7243311a2659b7569dddc20c56ac9f9d8e/core/tauri/scripts/core.js#L146-L167 and do some modifications to let dragging remains on `mousedown` but maximize when `mouseup`

example:
```js
let single_click_timer: number = -1;
document.addEventListener('mousedown', (e) => {
  if (e.target.hasAttribute('data-customized-titlebar') && e.button === 0) {
    e.preventDefault();
    e.stopImmediatePropagation();
    if (e.detail === 1) {
      single_click_timer = setTimeout(() => {
        window.__TAURI_INVOKE__('tauri', {
          __tauriModule: 'Window',
          message: {
            cmd: 'manage',
            data: {
              cmd: {
                type: 'startDragging',
              },
            },
          },
        });
      }, 150);
    } else {
      clearTimeout(single_click_timer);
    }
  }
});
document.addEventListener('mouseup', (e) => {
  if (
    e.target.hasAttribute('data-customized-titlebar') &&
    e.button === 0 &&
    e.detail === 2
  ) {
    e.preventDefault();
    e.stopImmediatePropagation();
    window.__TAURI_INVOKE__('tauri', {
      __tauriModule: 'Window',
      message: {
        cmd: 'manage',
        data: {
          cmd: {
            type: '__toggleMaximize',
          },
        },
      },
    });
  }
});
  ````

**Comment by amrbashir** [comment]
@pewsheen @doinkythederp Can you check if https://github.com/tauri-apps/tauri/pull/8312 matches the behavior of macOS?

**Comment by lewisfm** [comment]
> @pewsheen @doinkythederp Can you check if #8312 matches the behavior of macOS?

https://github.com/tauri-apps/tauri/assets/75394401/d05ac067-e699-4d0f-b82a-1d5c834cd997

@amrbashir I just tested out #8312! I noticed a few issues while I was comparing the differences. The new behavior appears to prevent any dragging/movement of the titlebar whatsoever! (Demonstrated at start of video.) Also, if the mouse button is moved before being released, the maximization is only aborted if it leaves the drag area, which is not the expected behavior. (Demonstrated at end of video.)

**Comment by amrbashir** [comment]
The `drag` bug should be fixed now (was just a typo), as for the maximization, I was not sure if the maximization should cancel only if it leaves the drag element of if it simply moves, what is the native behavior?

**Comment by lewisfm** [comment]
> I was not sure if the maximization should cancel only if it leaves the drag element of if it simply moves

I believe it's when it moves at all.

https://github.com/tauri-apps/tauri/assets/75394401/fd40f89c-b88f-49bf-9af6-0b2dc9dd5a4c

**Comment by amrbashir** [comment]
Should be good now, please test and let me know

**Comment by pewsheen** [comment]
> Should be good now, please test and let me know

It works perfectly
