### ISSUE TITLE
[bug] audio recording via getUserMedia permission error

### ISSUE THREAD

**Issue by egoist** [tauri-apps/tauri#8314]
### Describe the bug

**This is only an issue in production build and when the app is notarized.**

It throws error when I call `mediaDevices.getUserMedia({audio: true})`:

```
The request is not allowed by the user agent or the platform in the current context
```

<img width="500" src="https://github.com/tauri-apps/tauri/assets/8784712/98e995e1-a24a-4ca4-83ff-98ca8dbdaaa0" alt="bug">

### Reproduction

here's the repo I created using create-tauri-app: https://github.com/egoist-bot/tauri-audio-bug 

here's the changes: https://github.com/egoist-bot/tauri-audio-bug/commit/b580280c151259111e3c5bf67d324a2cd2a8e2c6 i already added `plist.info` and it still doesn't work

see `build.mjs` to configure all the env variables needed for the build, then run `node build.mjs`

### Expected behavior

should start recording audio

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 14.1.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 18.16.0
    - pnpm: 8.10.0
    - yarn: 1.22.19
    - npm: 9.5.1
    - bun: 1.0.11

[-] Packages
    - tauri [RUST]: 1.5.2
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.6
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.1
    - @tauri-apps/cli [NPM]: 1.5.6

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Can you rename the plist file to an upper case i ? like `Info.plist`

I'm not sure if that's really relevant but i've only ever seen it with an upper case i so it's worth a try imo.

**Comment by egoist** [comment]
@FabianLars I realized that but `Info.plist` still doesn't work

I also checked the plist file in the bundled app and it has everything included

**Comment by denjell-crabnebula** [comment]
Another Tauri app (with confirmed microphone use in prod) just uses this in the `Info.plist`:
```
	<key>NSMicrophoneUsageDescription</key>
	<string>Some reasoning</string>
```

they do not have these:
```
    <key>com.apple.security.device.microphone</key>
    <true/>
    <key>com.apple.security.device.audio-input</key>
    <true/>
```

**Comment by denjell-crabnebula** [comment]
I also noticed some mismatch on your tauri info (latest alpha cli is `2.0.0-alpha.18`) but then you seem to be using 1.5.x for core and build etc...

**Comment by egoist** [comment]
> I also noticed some mismatch on your tauri info (latest alpha cli is `2.0.0-alpha.18`) but then you seem to be using 1.5.x for core and build etc...

Just updated that, I had tauri-cli install via cargo but this project is using locally installed tauri-cli via npm, I uninstalled the cargo version and it still doesn't work.

**Comment by FabianLars** [comment]
Can you run `tccutil reset Microphone com.demo` (btw, i recommend adding a third component to that bundle-id) and try again?
If that doesn't work, maybe try the same but with `sudo` 🤔 
Lastly, change the bundle identifier (basically a hard reset)

**Comment by egoist** [comment]
> Another Tauri app (with confirmed microphone use in prod)

@denjell-crabnebula can I try that app to see if it's some settings in my OS causing this? I couldn't find a tauri app that uses microphone 😅

**Comment by egoist** [comment]
> Can you run `tccutil reset Microphone com.demo` (btw, i recommend adding a third component to that bundle-id) and try again? If that doesn't work, maybe try the same but with `sudo` 🤔 Lastly, change the bundle identifier (basically a hard reset)

that doesn't work either

**Comment by FabianLars** [comment]
Last idea, can you try moving the sandbox properties into a seperate entitlements file like this one? https://github.com/tauri-apps/tauri/blob/1.x/examples/updater/entitlements.plist (needs to be added to tauri.conf here https://github.com/tauri-apps/tauri/blob/1.x/examples/updater/src-tauri/tauri.conf.json#L36

**Comment by FabianLars** [comment]
> can I try that app to see if it's some settings in my OS causing this? I couldn't find a tauri app that uses microphone 😅

it's closed source so idk what exactly it does, but https://noor.to/ uses tauri

**Comment by denjell-crabnebula** [comment]
Another is here: https://www.meetsteno.com/ (closed source and paid)

**Comment by denjell-crabnebula** [comment]
Did you try removing these keys?

```
    <key>com.apple.security.device.microphone</key>
    <true/>
    <key>com.apple.security.device.audio-input</key>
    <true/>
```

**Comment by egoist** [comment]
> @Fabian-Lars: Last idea, can you try moving the sandbox properties into a seperate entitlements file like this one? [`1.x`/examples/updater/entitlements.plist](https://github.com/tauri-apps/tauri/blob/1.x/examples/updater/entitlements.plist?rgh-link-date=2023-11-28T13%3A26%3A13Z) (needs to be added to tauri.conf here [`1.x`/examples/updater/src-tauri/tauri.conf.json#L36](https://github.com/tauri-apps/tauri/blob/1.x/examples/updater/src-tauri/tauri.conf.json?rgh-link-date=2023-11-28T13%3A26%3A13Z#L36)

@Fabian-Lars you are the legend, that's what it took to make it work

<img src="https://github.com/tauri-apps/tauri/assets/8784712/7379df88-94ae-420c-bb64-40b82aad3129" width="300" alt="preview">

**Comment by egoist** [comment]
Just move these into a separate plist:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.device.microphone</key>
    <true/>
    <key>com.apple.security.device.audio-input</key>
    <true/>
  </dict>
</plist>
```

and add it to tauri.conf.json:

```
"macOS": {
      "entitlements": "./entitlements.plist"
 }
```

**Comment by egoist** [comment]
> Did you try removing these keys?
> 
> ```
>     <key>com.apple.security.device.microphone</key>
>     <true/>
>     <key>com.apple.security.device.audio-input</key>
>     <true/>
> ```

I think these are required for sandboxed app

Anyways it's fixed using the solution from @FabianLars , thanks for the help 🫡

**Comment by chudongvip** [comment]
> > 您是否尝试过删除这些键？
> > ```
> >     <key>com.apple.security.device.microphone</key>
> >     <true/>
> >     <key>com.apple.security.device.audio-input</key>
> >     <true/>
> > ```
> 
> 我认为这些对于沙盒应用程序是必需的
> 
> 无论如何，它已使用以下解决方案修复@FabianLars，谢谢你的帮助🫡

更新一下上面你的 Demo 吧，我使用的是 macOS ，安装你们说的还是跑不了

**Comment by kamalkech** [comment]
is that for desktop or mobile, i am looking for desktop solution

**Comment by FabianLars** [comment]
desktop, more specifically macOS

**Comment by kamalkech** [comment]
@FabianLars what about windows and linux ? i try to check official tauri docs but no answers there

**Comment by pierd** [comment]
Just stumbled upon this thread and after a long time I realised that you need both the entitlements file *and* `Info.plist` for example (both in `src-tauri`):
- `Entitlements.plist`:
    ```
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
      <dict>
        <key>com.apple.security.device.microphone</key>
        <true/>
        <key>com.apple.security.device.audio-input</key>
        <true/>
      </dict>
    </plist>
    ```
- `Info.plist`:
    ```
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
      <dict>
        <key>NSMicrophoneUsageDescription</key>
        <string>Your reasons here.</string>
      </dict>
    </plist>
    ```
and you need `"Entitlements.plist"` in `bundle->macOS->entitlements` in your `tauri.conf.json` (as described [here](https://v1.tauri.app/v1/guides/building/macos/)).

**Comment by kamalkech** [comment]
@pierd i had do the same and it working on mac, as we can build one code on tauri should add permissions for win and linux

**Comment by therealpurplemana** [comment]
In case someone is running into camera permissions and runs into this, putting this into my Entitlements.plist solved the issue in release build:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.automation.apple-events</key><true/>
    <key>com.apple.security.device.camera</key><true/>
  </dict>
</plist>
```
