### ISSUE TITLE
[feat] Windows Virtual Desktop

### ISSUE THREAD

**Issue by mrzhjyw** [tauri-apps/tauri#8317]
### Describe the problem

Switched to a new desktop, unable to bring the Tauri application over.

### Describe the solution you'd like

_

**Comment by amrbashir** [comment]
That is needed to be done manually by the user.

**Comment by amrbashir** [comment]
That is needed to be done manually by the user.

**Comment by amrbashir** [comment]
Anyways, your issue lacks enough information so I will close this for now but feel free to ping me with more info if you feel I missed something

**Comment by mrzhjyw** [comment]
I've actually written a floating window, and I hope it can be displayed on all virtual desktops. @amrbashir

**Comment by amrbashir** [comment]
I see, are you using `skipTaskbar: true` ? it should work when you enable that option.

**Comment by mrzhjyw** [comment]
I'm sorry, I forgot that. I'm sorry to disturb you.
