### ISSUE TITLE
[feat] Improve error message with invalid target for `build`

### ISSUE THREAD

**Issue by bicarlsen** [tauri-apps/tauri#8319]
### Describe the problem

In [`tauri::tooling::cli::interface::rust::Rust::env`](https://github.com/tauri-apps/tauri/blob/f78e5e4d4ae3f054c1b78e44332eb65715ea81c2/tooling/cli/src/interface/rust.rs#L232) when getting the target triple, each component is `unwrap`ed causing the build to fail with an `unwrap called on None` error if the target triple is incorrect e.g. `aarch64_apple_darwin` instead of `aarch64-apple-darwin` (underscore instead of hyphen). 

### Describe the solution you'd like

To clarify the issue the components could be `expect`ed with a message like "invalid target triple".

**Comment by zacharyftw** [comment]
@FabianLars i would like to work on this issue

**Comment by FabianLars** [comment]
Cool, much appreciated!

**Comment by zacharyftw** [comment]
@FabianLars https://github.com/tauri-apps/tauri/pull/8321

**Comment by swathi917** [comment]
@FabianLars is this still an open issue? The PR linked above has been merged

**Comment by amrbashir** [comment]
Thanks @swathi917, this has been solved
