### ISSUE TITLE
[bug] `yarn tauri migrate` doesn't work for me, i need some help

### ISSUE THREAD

**Issue by lopo12123** [tauri-apps/tauri#8320]
### Describe the bug

I'm migrating my tauri project to v2.
I saw that the documentation for v2 says there is automatic migration, but I encountered some problems

I upgraded `@tauri-apps/cli` to `2.0.0-alpha.17`. When I ran it for the first time, it prompted me that `allowlist` is not allowed in the configuration file. Then I temporarily commented the relevant fields and ran it again. At this time, it prompted There is no `migrate` command

![image](https://github.com/tauri-apps/tauri/assets/59609929/a088b9b6-87ef-4678-b066-96c17a2b37cf)
![image](https://github.com/tauri-apps/tauri/assets/59609929/a8ce1955-833c-4c9c-b3f4-16b52a79d4ad)

### Reproduction

Create a v1 project, enable the config-json5 feature and simply set fields like width, height and fullscreen, then update @tauri-apps/cli to v2 and run yarn tauri migrate

### Expected behavior

Hope it will migrate my project to v2

### Platform and versions

```text
Ah this! `yarn tauri info` also failed. Am I missing a step? But when I run yarn tauri --version, it does show that it is v2.

Here is some simple information

windows 10
rustc 1.74.0 (79e9716c9 2023-11-13)
rustup 1.26.0 (5af9b9484 2023-04-05)
node v18.16.1
yarn 3.6.4
```

### Additional context

I'm not quite sure what steps I'm missing, hope someone can help me, thanks

**Comment by amrbashir** [comment]
I could not reproduce the issue, please provide a minimal repro.

**Comment by lopo12123** [comment]
to reproduce: https://github.com/lopo12123/8320

By the way, there is an error in the documentation

![OPZ)$ J UF@A(GIE1~_QX5Q](https://github.com/tauri-apps/tauri/assets/59609929/a29b4c53-26dc-41d1-a32a-1e8e4bf827f1)
![)_7$T @9C5}CH~Q OO_9 U](https://github.com/tauri-apps/tauri/assets/59609929/bc229d07-d9f6-4f69-b7e8-5526f21c82c9)

**Comment by amrbashir** [comment]
I see, I will open a PR to fix the documentation, thanks
