### ISSUE TITLE
[bug] how to add system tray

### ISSUE THREAD

**Issue by kitty-eu-org** [tauri-apps/tauri#8331]
### Describe the bug

I set up the system tray according to the method of v1, and I can report an error. I saw that v2 seems to use the tray-icon feature to implement the system tray, but I don't know how to write a system tray. Can you give me a minimum example that can run?

### Platform and versions

```text
[build-dependencies]
tauri-build = { version = "2.0.0-alpha", features = [] }

[dependencies]
tauri = { version = "2.0.0-alpha", features = ["tray-icon"] }
tauri-plugin-window = "2.0.0-alpha"
tauri-plugin-shell = "2.0.0-alpha"
```

### Additional context

this is my run code:
```
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
  // TrayIconBuilder::new()
    tauri::Builder::default()
        .manage(AppState {
            db: Default::default(),
        })
        .setup(setup)
        .plugin(tauri_plugin_window::init())
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(tauri::generate_handler![greet])
        .invoke_handler(tauri::generate_handler![start_hy])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

```
I don't know how to use tray-icon， please help me, thanks.

**Comment by kotekpsotek** [comment]
You can do your as here

```rust
// src/main.rs
use tauri::{CustomMenuItem, SystemTray, SystemTrayMenu};

fn main() {
  let tray_menu = SystemTrayMenu::new(); // insert the menu items here
  let system_tray = SystemTray::new()
    .with_menu(tray_menu);
  tauri::Builder::default()
    .system_tray(system_tray)
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
```

Everything coupled with interesting you topic is avaiable on [tauri documentation](https://tauri.app/v1/guides/features/system-tray/)

**Comment by kitty-eu-org** [comment]
> ```rust
> .system_tray(system_tray)
> ```

I think you misunderstood me. The version I am using is not v1, but v2. When I use tray like v1, I get an error:
```
error[E0432]: unresolved imports `tauri::CustomMenuItem`, `tauri::SystemTray`, `tauri::SystemTrayMenu`
 --> src/lib.rs:9:13
  |
9 | use tauri::{CustomMenuItem, SystemTray, SystemTrayMenu};
  |             ^^^^^^^^^^^^^^  ^^^^^^^^^^  ^^^^^^^^^^^^^^ no `SystemTrayMenu` in the root
  |             |               |
  |             |               no `SystemTray` in the root
  |             no `CustomMenuItem` in the root
```

**Comment by FabianLars** [comment]
The v2 apis where renamed a bit: https://docs.rs/tauri/2.0.0-alpha.18/tauri/tray/index.html - the migration guide should be up to date i think: https://beta.tauri.app/guides/upgrade-migrate/from-tauri-1/#migrate-to-tray-icon-module

**Comment by jdegger** [comment]
@FabianLars Whenever I add the code to test with the v2 tray code it simply seems to ignore it and it gives me that `let tray` is unused implying that something is missing in the setup. 

https://gist.github.com/jdegger/aeea3dc369359775d426dd636fae9220

I also have a main fn which is not in the migration guide. 

Things are probably getting mixed up on my end but so far I have only followed al the migration guides and this is the result. Any clue where I went wrong?

**Comment by FabianLars** [comment]
If you don't need the tray handle you can just remove the `let tray =` part because `.build(app)` is what actually registers it to the app.

Rust doesn't know what build() does in this context, it's just complaining about the unused let binding.

Edit: to be clear, I don't see anything actually wrong with your code but I'm only on my phone rn

**Comment by jdegger** [comment]
Thanks for the quick reply, I will keep on debugging then. Whenever I remove the tray+menu icon altogether it does not change anything. The menu is not registered as well.

Thanks again and no worries

**Comment by jdegger** [comment]
Not sure why, but I was not able to get it working without binding it to the `main` id as configured in my tray config in tauri.conf.json.

My code is as follows now which seems to work:

# Note: This was not the solution, scroll down!
```rs
#[cfg_attr(mobile, tauri::mobile_entry_point)]

use tauri::{
  Manager,
  tray::{ClickType, TrayIconBuilder},
};

fn main() {

  tauri::Builder::default()
      .setup(|app| {
        let _tray = TrayIconBuilder::<_>::with_id("main")
            .on_tray_icon_event(|tray, event| {
                if event.click_type == ClickType::Left {
                    let app = tray.app_handle();

                    #[cfg(not(target_os = "macos"))] {
                      if let Some(webview_window) = app.get_webview_window("main") {
                        let _ = webview_window.show();
                        let _ = webview_window.set_focus();
                      }
                    }

                    #[cfg(target_os = "macos")] {
                      tauri::AppHandle::show(&app.app_handle()).unwrap();
                    }
                    
                }
            })
            .build(app)?;

        Ok(())
    })
    .on_window_event(|window, event| match event {
      tauri::WindowEvent::CloseRequested { api, .. } => {
        #[cfg(not(target_os = "macos"))] {
          window.hide().unwrap();
        }

        #[cfg(target_os = "macos")] {
          tauri::AppHandle::hide(&window.app_handle()).unwrap();
        }
        api.prevent_close();
      }
      _ => {}
    })
    .run(tauri::generate_context!())
    .expect("error while running tauri application");

}
```

In this example I have removed the menu and menu items as this was not working (also not when I removed the left click event on the tray icon). I do not really care for the menu so in my case it doesn't matter but it still interesting as to why it does not work.

For now I'm good though, this might help somebody else but it should also be taken with a grain of salt because at this point I do not really have a clue why it works. 🤷

**Comment by FabianLars** [comment]
(still only on my phone so won't be able to do more than giving hints)

I think this is just a documentation issue. In v1 you had to configure the icon in tauri.conf.json and then the menu in rust.
In v2 this is also still possible but the tauri.conf.json entry is optional and if you use trayiconbuilder (with an id other than main) it will create a new separate tray icon which will _not_ have the icon configured in tauri.conf.json, you will have to use the builder's icon setter instead.

If you prefer setting the icon in tauri.conf then you can get a handle to the tray via app.tray().get_by_id("main") which has methods to set the menu (iirc). I would expect that using the builder on the same Id as configured in the conf would cause an error similar to duplicate window labels so I'm surprised your code works.

**Comment by jdegger** [comment]
Took me a while to figure this one out but I think I got there in the end. The `app.tray()` method does not seem to be exposed or I might be missing a feature flag?

This is what I ended up with:

1. I removed the `tauri.conf.json` entry for the tray icon altogether 
2. I enabled the feature `image-png` in `tauri.conf.json` in the tauri dependency

This is my code:

```rs
#[cfg_attr(mobile, tauri::mobile_entry_point)]

use tauri::{
  Manager,
  image::Image,
  tray::{ClickType, TrayIconBuilder},
};


fn main() {

  tauri::Builder::default()
      .setup(|app| {

        let _tray = TrayIconBuilder::new()
          .icon(Image::from_path("./icons/icon.png")?)
          .on_tray_icon_event(|tray, event| {
              if event.click_type == ClickType::Left {
                  let app = tray.app_handle();

                  #[cfg(not(target_os = "macos"))] {
                    if let Some(webview_window) = app.get_webview_window("main") {
                      let _ = webview_window.show();
                      let _ = webview_window.set_focus();
                    }
                  }

                  #[cfg(target_os = "macos")] {
                    tauri::AppHandle::show(&app.app_handle()).unwrap();
                  }
                  
              }
          })
          .build(app)?;

        Ok(())
    })
    .on_window_event(|window, event| match event {
      tauri::WindowEvent::CloseRequested { api, .. } => {
        #[cfg(not(target_os = "macos"))] {
          window.hide().unwrap();
        }

        #[cfg(target_os = "macos")] {
          tauri::AppHandle::hide(&window.app_handle()).unwrap();
        }
        api.prevent_close();
      }
      _ => {}
    })
    .run(tauri::generate_context!())
    .expect("error while running tauri application");

}
```

This seems to be working as intended. In my first tests I think it was working but it did not have an icon and hence was invisible. Thanks for the points @FabianLars.

**Comment by jdegger** [comment]
@FabianLars As an additional pointer for the docs, this is what I found difficult to understand as a newbie in rust and tauri:

1. had no clue I had to enable the feature flag to allow `from_path` and couldn't figure out why this method was not available. I found in the Rust docs that it needed the flag and that worked. I now also see this in the code: `#[cfg(any(feature = "image-ico", feature = "image-png"))]` which makes it quite obvious once you know
2. The migration docs for the tray do not show a main fn which is confusing
3. The migration docs to not add an icon, which was the hard part to figure out

**Comment by FabianLars** [comment]
Thanks for the feedback!

**Comment by chenka** [comment]
If someone struck with `from_path` error. You can update `Cargo.toml` to this:
```
[dependencies]
tauri = { version = "2.0.0-beta", features = [
    'tray-icon',
    'image-ico',
    'image-png',
] }
```

**Comment by nwehrhan** [comment]
@jdegger and @chenka thanks for the help! This should really be in the docs... Not adding the icon in the example is really confusing since it doesn't show up in the system tray unless the image is there.

**Comment by NetOpWibby** [comment]
> The v2 apis where renamed a bit: https://docs.rs/tauri/2.0.0-alpha.18/tauri/tray/index.html - the migration guide should be up to date i think: https://beta.tauri.app/guides/upgrade-migrate/from-tauri-1/#migrate-to-tray-icon-module

For future searchers, the updated link is: https://beta.tauri.app/start/migrate/from-tauri-1/#migrate-to-tray-icon-module
