### ISSUE TITLE
[bug] Wrong configuration file used when cross-compiling 

### ISSUE THREAD

**Issue by Xtr126** [tauri-apps/tauri#8332]
### Describe the bug

When cross-compiling from Linux to Windows, `tauri.linux.conf.json` is used instead of `tauri.windows.conf.json`.

### Reproduction

Cross-compiling Windows application on Linux following https://tauri.app/v1/guides/building/cross-platform/#experimental-build-windows-apps-on-linux-and-macos 

### Platform and versions

```text
[✔] Environment
    - OS: Arch Linux Unknown X64
    ✔ webkit2gtk-4.0: 2.42.1
    ✔ rsvg2: 2.57.0
    ✔ rustc: 1.71.0 (8ede3aae2 2023-07-12)
    ✔ cargo: 1.71.0 (cfd3bbd8f 2023-06-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 21.1.0
    - pnpm: 8.11.0

[-] Packages
    - tauri [RUST]: 1.5.3
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.6
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.1
    - @tauri-apps/cli [NPM]: 1.5.6

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - bundler: Vite
```

**Comment by Xtr126** [comment]
Closing as I can use `--config src-tauri/tauri.windows.conf.json` in the build command as a workaround.

**Comment by FabianLars** [comment]
It's still a bug we should fix imo :)

**Comment by FabianLars** [comment]
On second thought, nevermind. This would be a pretty large change, and since v2 is already fixed (it was required for mobile) i'll agree that v1 users should stick with the workaround for the time being.
