### ISSUE TITLE
[feat] Embedded WebView2Loader. DLL file

### ISSUE THREAD

**Issue by silent-rain** [tauri-apps/tauri#8336]
### Describe the problem

When cross compiling Windows software in wsl2, it relies on the 'WebView2Loader. dl' library, but this library is detached from the exe executable file, which is not very user-friendly in terms of experience

### Describe the solution you'd like

Customizable packaging of the 'WebView2Loader. DLL' library into an exe executable file

**Comment by FabianLars** [comment]
This is one of the reasons why we recommend the msvc target even when cross compiling: https://tauri.app/v1/guides/building/cross-platform#experimental-build-windows-apps-on-linux-and-macos. I know it's super annoying to set up, but in this context you will have a smaller executable, _and_ the loader will be statically linked into it.
With the gnu target this is _not_ possible and always require the .dll _next to_ the executable. That said, the .msi and setup.exe installers should include that (if they don't, please reach out again as that'd be a bug). We can't include that into the application executable itself though.

**Comment by Sofahamster** [comment]
> This is one of the reasons why we recommend the msvc target even when cross compiling

Recommending the MSVC target isn't always feasible in corporate environments: most companies aren't eligible for Visual Studio Community, and the Build Tools require a paid Visual Studio license that procurement/compliance/whatever may not approve for whatever reason. The detached WebView2Loader.dll degrades the user experience, is there really no way to avoid linking to the DLL? I'm sure there's ways to package it. PyInstaller manages to pack an entire python ecosystem into one executable.

**Comment by FabianLars** [comment]
PyInstaller works by extracting the app into a temp dir which also comes with a few problems. Since we don't directly support portable builds, self-extracting exes are currently out of scope as well but there was some windows installer framework that also had a self-extract mode but i can't remember its name 🤔 Also: https://github.com/MicrosoftEdge/WebView2Feedback/issues/4321
