### ISSUE TITLE
[bug]  In the Windows operating system, unable to take screenshots of applications.

### ISSUE THREAD

**Issue by xiang7970** [tauri-apps/tauri#8345]
### Describe the bug

 In the Windows operating system, I am unable to take screenshots of applications. Whether I use a screenshot tool or the built-in print screen key, as soon as I trigger the screenshot, the application disappears.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 119.0.2151.97
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ cargo: 1.73.0 (9c4383fb5 2023-08-26)
```

**Comment by amrbashir** [comment]
Can you please provide the full `tauri info` information? also are you using `contentProtected: true` in your tauri config or through `window.setContentProtected`?

**Comment by xiang7970** [comment]
> Can you please provide the full `tauri info` information? also are you using `contentProtected: true` in your tauri config or through `window.setContentProtected`?

Yes, I used `content_protected: false` and now it's ready
