### ISSUE TITLE
Does not create a window when using the `CLI`

### ISSUE THREAD

**Issue by thep0y** [tauri-apps/tauri#8358]
I want to write a program that does not create a window when using the `CLI`. Can you please guide me on how to achieve this?

The window should only be omitted when using the `CLI` in the terminal. Clicking on the program's icon should open the window as usual.

The example code in the documentation does not meet my requirements: https://tauri.app/v1/guides/features/cli/.

My approach is as follows; I'm not sure if it's correct or if there is a better implementation.

```rust
tauri::Builder::default().setup(|app| {
    match app.get_cli_matches() {
        Ok(matches) => {
            for arg in matches.args.values() {
                // Execute different commands based on arg.value
                tauri::async_runtime::spawn(async move {
                    let r = do().await.unwrap();
                    println!("{:?}", r);
                });
            }
          
            // Exit the app after executing all commands
            app.app_handle().exit(0);
        }
        Err(e) => {
            println!("{}", e);
        }
    }
    Ok(())
})
```

**Comment by FabianLars** [comment]
If we're using the code you posted as a base, i'd recommend to remove the window config from tauri.conf.json and use https://docs.rs/tauri/latest/tauri/window/struct.WindowBuilder.html in rust to create the window on demand instead.

Alternatively, if you think closing and re-opening the window will happen frequently you could create the window hidden (in conf.json `visible: false` and show()/hide() it on demand but this will consume more resources (memory usage etc)
