### ISSUE TITLE
expose random HTTP port number to both JS and Rust

### ISSUE THREAD

**Issue by futurist** [tauri-apps/tauri#836]
**Is your feature request related to a problem? Please describe.**

When need to communicate between different processes, the HTTP port is very important way, and simpler than IPC.

**Describe the solution you'd like**

Expose `port` to **api**, and user can save it/pass it to other process for communication.

**Comment by lucasfernog** [comment]
You can parse the `port` on JS using `window.location.href`. I agree that it should be visible on Rust though.

**Comment by nklayman** [comment]
We will be removing the embedded-server mode in favor of a custom protocol soon. With a custom protocol, there won't be a port number, so I'll close this issue as it will soon be invalid.
