### ISSUE TITLE
[feat] bundle files only for specific platform

### ISSUE THREAD

**Issue by zhangsan946** [tauri-apps/tauri#8360]
### Describe the problem

I am developing a proxy application for all the platforms(Windows, Linux, MacOS). By default on Linux, MacOS, it supports TUN/TAP interface in kernal, while On Windows, it has to integrate addition TUN driver such as https://www.wintun.net/.
Tauri currently dosen't support to bundle externalbin & resources only for target platform.

### Describe the solution you'd like

To support bundle externalbin(dlls) only for specific platform.

**Comment by FabianLars** [comment]
Hi! This is already possible, you can have platform specific merge configs as explained here https://tauri.app/v1/api/config#platform-specific-configuration

These configs don't have to be complete configs, just what you want to overwrite on the main configs.
