### ISSUE TITLE
[bug] Default Vite dev server setup is watching src-tauri

### ISSUE THREAD

**Issue by RandomEngy** [tauri-apps/tauri#8362]
### Describe the bug

I profiled a 45-second dev startup for my Tauri/Vite project: https://engy.us/misc/vite-profile-0.cpuprofile . Almost all of the time was spent in `_handleDir()` setting up file watchers in the `src-tauri` folder, mostly on files in `/target/release` and `/target/debug/`.

My understanding of the chain here is that Vite is supposed to watch `src`, then rebuild and populate `dist`. And Tauri is watching/building from `dist`. So Vite shouldn't need to be watching `src-tauri`.

I put this in vite.config.js:

```
  server: {
    watch: {
      ignored: ['**/src-tauri/**'],
    },
  },
```

This cut the dev startup time from 45 seconds to less than a second. And everything still seems to work. Vite's `_handleDir()` is no longer called on anything in `src-tauri`, but changes to JS and Rust code are still picked up and trigger reloads.

Should this Vite server watch exclusion be included by default with `create tauri-app`?

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 119.0.2151.97
    ✔ MSVC:
        - Visual Studio Build Tools 2022
        - Visual Studio Community 2022
    ✔ rustc: 1.74.0 (79e9716c9 2023-11-13)
    ✔ cargo: 1.74.0 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.12.1
    - pnpm: 8.11.0
    - npm: 7.17.0

[-] Packages
    - tauri [RUST]: 1.5.2
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.6
    - tao [RUST]: 0.16.5
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 1.5.7

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:5173/
    - bundler: Rollup
```

**Comment by FabianLars** [comment]
Nice catch! I guess that's the drawback of a custom target dir, i just never noticed 😅 

> Should this Vite server watch exclusion be included by default with create tauri-app?

imo yes.

**Comment by Raicuparta** [comment]
In case anyone else ends up here: The current solution of `**/src-tauri/**` obviously means any folder with that name will be ignored, independently of where it is in your project. Since this setting only seems to be inspecting absolute paths (or if it's trying relative paths, I'm not sure what they're relative to), my solution was this:
```ts
{ ignored: [`${process.cwd()}/src-tauri/**`] }
```
This way you can be sure you won't accidentally ignore some future folder with the same name.
