### ISSUE TITLE
[feature request] add window management

### ISSUE THREAD

**Issue by futurist** [tauri-apps/tauri#837]
**Describe the solution you'd like**
It's nice to have window management functions like `hide`, `show`, `maximize` etc. current tauri window.

And customize the look of the window, maybe can reference some [Electronjs Windiow API](https://www.electronjs.org/docs/api/browser-window) does?

**Comment by lucasfernog** [comment]
That will be addressed once we have the new bindings to webview/webview (right now we use a fork, Boscop/web-view).

**Comment by ken0x0a** [comment]
@lucasfernog Does webview_official also have a plan to support [MenuBar](https://support.apple.com/guide/mac-help/menu-bar-mchlp1446/mac)?

I confirmed `hide`, `hide others` `Full Screen`, `Copy`, `Paste`, `Select All`  & ... works fine after registering those items on MenuBar on macOS.

**Comment by nothingismagick** [comment]
I think that this original question is going to be resolved with our next release.
