### ISSUE TITLE
[feat] Updater on Mac works in /Applications

### ISSUE THREAD

**Issue by krzykro2** [tauri-apps/tauri#8372]
### Describe the problem

/Applications/ is the standard directory for apps on MacOS. However writing to it requires admin privileges.
The updater replaces the running binary, but it runs with user privileges, so if the current user does not have write privileges to the binary that they are running - the updater will fail.

### Describe the solution you'd like

SUDO_ASKPASS could be used to provide a simple dialog window for the user to give admin privileges during the update process on Mac.

```
-A          Normally, if sudo requires a password, it will read it from the current terminal.  If the -A (askpass) option is specified, a (possibly
            graphical) helper program is executed to read the user's password and output the password to the standard output.  If the SUDO_ASKPASS
            environment variable is set, it specifies the path to the helper program.  Otherwise, the value specified by the askpass option in
            sudoers(5) is used
```

SUDO_ASKPASS can be an osascript to create a very simple dialog window with password input.

Osascript example: osascript -e 'Tell application "System Events" to display dialog "Enter the network password:" with hidden answer default answer ""' -e 'text returned of result' 2>/dev/null

It could also use javascript and be built based on:
https://developer.apple.com/library/archive/documentation/LanguagesUtilities/Conceptual/MacAutomationScriptingGuide/DisplayDialogsandAlerts.html

**Comment by FabianLars** [comment]
closing in favor of https://github.com/tauri-apps/tauri/issues/8104
