### ISSUE TITLE
Tauri App doesn't run after successful installation (Windows 10 NSIS)

### ISSUE THREAD

**Issue by Ingenious-c0der** [tauri-apps/tauri#8373]
### Describe the bug

So I built my tauri application using npm run tauri build and then it created the target folder and release as expected. The app.exe file in the release folder works perfectly fine, also when I try to install the application using NSIS installer in release/bundle/nsis the application is installed successfully and the shortcut to the app is created too. But the application doesn't open up or there is no trace of it opening up anywhere in the task manager too. 

### Expected behavior

The application should run & open as intended on the Windows platform after successful installation with NSIS. 

### Platform and versions

```text
> RustyVault@0.0.0 tauri
> tauri info


[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 120.0.2210.61
    ✔ MSVC:
        - Visual Studio Build Tools 2019
        - Visual Studio Community 2019
    ✔ rustc: 1.65.0 (897e37553 2022-11-02)
    ✔ Cargo: 1.65.0 (4bc8f24d3 2022-10-20)
    ✔ rustup: 1.25.1 (bb60b1e89 2022-07-12)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.16.1
    - npm: 8.4.1

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0 (outdated, latest: 1.5.2)
    - @tauri-apps/cli [NPM]: 1.4.0 (outdated, latest: 1.5.7)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React (Next.js)
    - bundler: Webpack
```

**Comment by amrbashir** [comment]
Without a reproduction or logs or anything, we can't really help, so please provide a reproduction. Also try building with `tauri build --debug` and see if you can get any errors or logs.

**Comment by Ingenious-c0der** [comment]
It was solved!

**Comment by SabbirMurad** [comment]
I ran into the same problem, Can you please describe how the issue was solved?

**Comment by Ingenious-c0der** [comment]
It was an issue with the application code itself. To debug this you can check the error logs which the app.exe (installed) generates when it is run using cmd. (not the shortcut lnk file but the actual exe)
