### ISSUE TITLE
[bug] Unable to pass arguments to application when using command `cargo tauri dev`

### ISSUE THREAD

**Issue by Tnze** [tauri-apps/tauri#8382]
### Describe the bug

Following this guide: <https://tauri.app/v1/guides/features/cli>
I configured the app to accept arguments when start up.

```json
    "cli": {
      "description": "A tauri cli test app",
      "longDescription": "",
      "beforeHelp": "",
      "afterHelp": "",
      "args": [
        {
          "name": "file",
          "index": 1,
          "takesValue": true
        }
      ],
      "subcommands": {
        "subcommand-name": {}
      }
    },
```

And according to this command help message:
```
> cargo tauri dev -h   
Tauri dev

Usage: cargo tauri dev [OPTIONS] [ARGS]...

Arguments:
  [ARGS]...  Command line arguments passed to the runner. Arguments after `--` are passed to the application

...
```

We should able to passed command arguments to the application like this `cargo tauri dev -- ./file`.
But actually the command exits with a wired error:
```
 ELIFECYCLE  Command failed with exit code 4294967295.
```
![image](https://github.com/tauri-apps/tauri/assets/19628575/4bae45c4-2677-43ac-ba2d-a5a5caa44ebc)

### Reproduction

https://github.com/Tnze/cli-test

### Expected behavior

The `cargo tauri dev -- ` command can pass the cmd arguments to application, not exit.

### Platform and versions

```text
> cargo tauri info

[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 120.0.2210.61
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.76.0-nightly (06e02d5b2 2023-12-09)
    ✔ cargo: 1.76.0-nightly (978722961 2023-12-06)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: nightly-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.17.1
    - pnpm: 8.12.0
    - yarn: 1.22.19
    - npm: 8.3.0

[-] Packages
    - tauri [RUST]: 1.5.3
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.6
    - tao [RUST]: 0.16.5
    - tauri-cli [RUST]: 1.5.7
    - @tauri-apps/api [NPM]: 1.5.2
    - @tauri-apps/cli [NPM]: 1.5.7

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - bundler: Vite
```

### Stack trace

```text
> cargo tauri dev -- .\README.md
     Running BeforeDevCommand (`pnpm dev`)

> cli-test@0.0.0 dev F:\tauri\cli-test
> vite


  VITE v4.5.1  ready in 232 ms

  ➜  Local:   http://localhost:1420/
  ➜  Network: use --host to expose
error: unexpected argument '.\README.md' found

Usage: cargo build [OPTIONS]

For more information, try '--help'.
        Info Watching F:\tauri\cli-test\src-tauri for changes...
 ELIFECYCLE  Command failed with exit code 4294967295.
```

**Comment by Tnze** [comment]
By executing command `cargo tauri dev -- --help`. I can see the `--help` actually passed to the `cargo build` command, not the application:
![image](https://github.com/tauri-apps/tauri/assets/19628575/27e304f6-0026-4ce3-918b-7bb9d7e7a7fc)

**Comment by amrbashir** [comment]
yeah, you need an extra `--` so `cargo tauri dev -- -- ` because the first `--` will make arguments passed to the cargo command that is used under the hood by tauri and the second `--` will be for your application.

**Comment by Tnze** [comment]
You are right. But then we should fix the help message of tauri-cli command. @amrbashir

**Comment by amrbashir** [comment]
I don't think we can reliably detect if you meant to pass to your application or to cargo.

**Comment by Tnze** [comment]
@amrbashir I mean we should tell the user who is executing `cargo tauri dev -h` that they should use one ` -- ` for cargo build and use two ` -- ` for application. In the tauri-cli help message.

Currently it says "Arguments after `--` are passed to the application", which is incorrect. Arguments after the second `--` are did pass to the application.

**Comment by amrbashir** [comment]
Ah I see, will open a PR to fix that

**Comment by Tnze** [comment]
@amrbashir Hi, I just found that `pnpm tauri dev -- -- xxxx` doesn't work. Only `cargo tauri dev` support pass arguments after the second `--` to the application. I think we should reopen this issue?

Both of my `pnpm tauri -V` and `cargo tauri -V` reports its version is v1.5.8 .

**Comment by FabianLars** [comment]
`pnpm tauri dev -- -- xxxx` works for me the same as `cargo tauri dev -- -- xxxx`, but i don't use tauri's cli feature, only rust std stuff though i doubt this makes a difference here 🤔

**Comment by Tnze** [comment]
@FabianLars @amrbashir I have recorded a video to proof this issue. It's size exceed the limit of Github.
So I upload it here: <https://b23.tv/oXDJbSQ> and here <https://youtu.be/_Seps9VYfK0>

**Comment by FabianLars** [comment]
Hmm, to me it looks like pnpm consumes the first `--` like npm does but they stopped doing that with pnpm v7 🤔 

What does your package.json script section look like?

**Comment by Tnze** [comment]
> What does your package.json script section look like?

I push my code used in the video here right now: <https://github.com/Tnze/cli-test>

**Comment by Tnze** [comment]
> Hmm, to me it looks like pnpm consumes the first `--` like npm does but they stopped doing that with pnpm v7 🤔

You are right, three `--` work. @amrbashir Should we update the helping message again? In my opinion it's not so well that rely on the unstable `--`. Something like `--application-arguments="-arg1 -arg2"` will be more reliable.

**Comment by FabianLars** [comment]
Hmm, i wonder what's going on. I tried your project and thought that maybe it's a pnpm version issue (i was on 8.11.0, you on 8.12.0) but i tested 8.11.0 8.12.0 and 8.12.1 and all of them worked 🤔

**Comment by amrbashir** [comment]
> > Hmm, to me it looks like pnpm consumes the first `--` like npm does but they stopped doing that with pnpm v7 🤔
> 
> You are right, three `--` work. @amrbashir Should we update the helping message again? In my opinion it's not so well that rely on the unstable `--`. Something like `--application-arguments="-arg1 -arg2"` will be more reliable.

This is something related to which package manager you're using and so I don't think we should include in the Tauri CLI documentation, however we could mention it in the CLI guide on tauri.app docs.
