### ISSUE TITLE
[bug] Window does not always restore previous dimensions when exiting fullscreen mode

### ISSUE THREAD

**Issue by wanooknox** [tauri-apps/tauri#8383]
### Describe the bug

When entering and exiting fullscreen mode on windows, using the js 'window' api, Tauri does not always recall the previous window location or dimensions. Instead the window is scaled to fill the whole screen (butted right up against the edges of the monitor and passing under the taskbar).

It is noteworthy that if you enter fullscreen from a maximized window and then exit fullscreen, the window correctly returns to it's previous maximized state. However, if you enter fullscreen from a non-maximized (or 'unmaximized') window, this bug will sometimes occur.

Before entering Fullscreen:
![image](https://github.com/tauri-apps/tauri/assets/466876/997936da-dad4-46c9-814c-5906be5ba6d5)

In Fullscreen:
![image](https://github.com/tauri-apps/tauri/assets/466876/a1e8c6ef-ba94-4852-b8af-01fe6d80456a)

After exiting Fullscreen:
![image](https://github.com/tauri-apps/tauri/assets/466876/194ebee4-f136-42f8-9586-051c0cbe436c)

### Reproduction

The repro project includes a page with buttons to enter and exit fullscreen mode, as well as an F11 keyboard shortcut to trigger fullscreen as well. 

~~The bug does not occur on every attempt, so it make take a few tries to trigger it. It may be related to speed of repetition, I have more success with the keyboard shortcut. If I learn how to cause this more consistently, I will update with better steps.~~
Update: Minutes after I submitted this I discovered that the bug always occurs if you call `appWindow.setFullscreen(true);` when already in fullscreen mode. If this is called twice before calling `appWindow.setFullscreen(false);` that causes the previous dimensions of the window to be lost.

Perhaps it isn't correctly short circuiting the true call when fullscreen is already active?

https://github.com/siliconcosmos/tauri-fullscreen-repro

### Expected behavior

When exiting Fullscreen mode, the previous window dimensions should be recalled and restored.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 120.0.2210.61
    ✔ MSVC: Visual Studio Build Tools 2019
    ✔ rustc: 1.74.1 (a28077b28 2023-12-04)
    ✔ cargo: 1.74.1 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.17.0
    - npm: 9.8.1

[-] Packages
    - tauri [RUST]: 1.5.3
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.6
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.1 (outdated, latest: 1.5.2)
    - @tauri-apps/cli [NPM]: 1.5.7

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:4200/
    - framework: Angular
    - bundler: Webpack
```

### Additional context

As an additional aside, it looks like v1.5.2 of @tauri-apps/api is missing the typescript definitions, so it doesn't work correctly with an angular project. I had to explicitly downgrade to v1.5.1 to generate the reproduction repo.

**Comment by amrbashir** [comment]
A fix will be available in the next release.

**Comment by wanooknox** [comment]
That's awesome! Thanks! I've already worked around it in my app, but I look forward to it hitting the stable build 😊
