### ISSUE TITLE
[bug]  run dev, get a lots of error about serde-1.0.193

### ISSUE THREAD

**Issue by cieldon32** [tauri-apps/tauri#8385]
### Describe the bug

cannot find function, tuple struct or tuple variant `Err` in this scope
    --> /Users/natsugei/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.193/src/lib.rs:287:32
Err(err) => return Err(err),
     |                                  ^^^ help: a local variable with a similar name exists: `err`

the error in serde-1.0.193

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 14.0.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.74.0 (79e9716c9 2023-11-13) (Homebrew)
    ✔ cargo: 1.74.0
    ✔ rustup: 1.26.0 (2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 21.4.0
    - pnpm: 8.9.0
    - npm: 10.2.4
 

[build-dependencies]
tauri-build = { version = "2.0.0-alpha.12", features = [] }

[dependencies]
tauri = { version = "2.0.0-alpha.18", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri-plugin-shell = "2.0.0-alpha.4"
compiler_builtins = "0.1.104"
```

**Comment by amrbashir** [comment]
try using `cargo clean` and `cargo update` inside `src-tauri`

**Comment by cieldon32** [comment]
> try using `cargo clean` and `cargo update` inside `src-tauri`

I had tried, and then the error change to once_cell-1.19.0
cannot find function, tuple struct or tuple variant `Ok` in this scope
   --> /Users/natsugei/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/race.rs:236:39
    |
236 |         match self.get_or_try_init(|| Ok::<&'a T, Void>(f())) {
    |                                       ^^ not found in this scope

**Comment by cieldon32** [comment]
> try using `cargo clean` and `cargo update` inside `src-tauri`

after more try, the error is:
   Compiling parking_lot_core v0.9.9
error[E0463]: can't find crate for `core`
  |
  = note: the `aarch64-apple-ios-sim` target may not be installed
  = help: consider downloading the target with `rustup target add aarch64-apple-ios-sim`

error[E0463]: can't find crate for `compiler_builtins`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `cfg-if` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
       Error [tauri_cli] Failed to run `cargo build`: command ["cargo", "build", "--package", "task", "--manifest-path", "/Users/natsugei/task/task/src-tauri/Cargo.toml", "--target", "aarch64-apple-ios-sim", "--features", "tauri/rustls-tls", "--lib", "--no-default-features"] exited with code 101
Command PhaseScriptExecution failed with a nonzero exit code

note: Run script build phase 'Build Rust Code' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'task_iOS' from project 'task')
** BUILD FAILED **



 rustup show
Default host: aarch64-apple-darwin
rustup home:  /Users/natsugei/.rustup

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
aarch64-apple-ios
aarch64-apple-ios-sim
x86_64-apple-ios

active toolchain
----------------

stable-aarch64-apple-darwin (default)
rustc 1.73.0 (cc66ad468 2023-10-03)

**Comment by amrbashir** [comment]
how about just deleting the `src-tauri/target` directory all together then?

**Comment by cieldon32** [comment]
> how about just deleting the `src-tauri/target` directory all together then?

not work

**Comment by amrbashir** [comment]
I am out of ideas, tbh try cleaning `~/.rustup` or reinstalling rust through rustup again

**Comment by cieldon32** [comment]
> I am out of ideas, tbh try cleaning `~/.rustup` or reinstalling rust through rustup again

Could you tell how to do with the error Eo463.
rustc --explain E0463

A plugin/crate was declared but cannot be found.

Erroneous code example:

#![feature(plugin)]
#![plugin(cookie_monster)] // error: can't find crate for `cookie_monster`
extern crate cake_is_a_lie; // error: can't find crate for `cake_is_a_lie`

You need to link your code to the relevant crate in order to be able to use it (through Cargo or the -L option of rustc example). Plugins
are crates as well, and you link to them the same way.

Common causes
*   The crate is not present at all. If using Cargo, add it to [dependencies] in Cargo.toml.
*   The crate is present, but under a different name. If using Cargo, look for package =  under [dependencies] in Cargo.toml.

Common causes for missing std or core
*   You are cross-compiling for a target which doesn't have std prepackaged. Consider one of the
    following: + Adding a pre-compiled version of std with rustup target add + Building std from source with cargo build -Z build-std +
    Using #![no_std] at the crate root, so you won't need std in the first place.
*   You are developing the compiler itself and haven't built libstd from source. You can usually build it with x.py build library/std. More
    information about x.py is available in the rustc-dev-guide.
(END)


about that, I don't know how to do.
I had tried: cargo add crate , fail: the crate `crate` could not be found in registry index.
so, about "The crate is not present at all. If using Cargo, add it to [dependencies] in Cargo.toml. " add what? I can't understand.

**Comment by cieldon32** [comment]
run create tauri-app --alpha, use new version to create repo

**Comment by b5** [comment]
The issue is homebrew, which can't be invoked from xcode. run `brew remove rust`, then follow the directions for installing rust from the [install page](https://www.rust-lang.org/tools/install)
