### ISSUE TITLE
AssetResolver behavior is inconsistent between dev and production

### ISSUE THREAD

**Issue by palant** [tauri-apps/tauri#8411]
### Describe the problem

It took me quite a while to figure out how `AssetResolver` is used because it seems to produce no result. Only after studying the source code I realized that this behavior is specific to dev mode because there are no embedded assets there. Production builds show the expected behavior however.

### Describe the solution you'd like

I ended up implementing a fallback: if `AssetResolver` doesn’t work, implement the same functionality by listing files in `config.dist_dir`. I’d expect this fallback to be part of `AssetResolver` itself, so that it delivers consistent results both in dev and production mode.

### Alternatives considered

At the very least, this footgun and the proposed fallback need to be documented. As things are right now, there isn’t a word in the documentation mentioning this issue.

### Additional context

I’m using Tauri 1.5.3. However, judging by the source code the problem hasn’t been addressed in Tauri 2.0 either.

**Comment by aDifferentJT** [comment]
Thank you so much for this, I've been banging my head against this for a while, this definitely needs to be fixed, or at least documented
