### ISSUE TITLE
[bug] plugin function not found, cannot call nsis_tauri_utils::FindProcessCurrentUser

### ISSUE THREAD

**Issue by cage1618** [tauri-apps/tauri#8412]
### Describe the bug

Error in macro CheckIfAppIsRunning on macroline 2
Error in script src-tauri\target\debug\nsis\x64\installer.nsi on line 533 -- aborting creation process
  Error failed to bundle project : `系统找不到指定的文件` (os error 2)

### Reproduction

upgrade @tauri-apps/cli to 1.5.8 from 1.5.7

### Platform and versions

```text
$ npm run tauri info
> tauri info


[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 120.0.2210.61
    ✔ MSVC:
        - Visual Studio Community 2022
        - Visual Studio 生成工具 2019
    ✔ rustc: 1.72.0 (5680fa18f 2023-08-23)
    ✔ cargo: 1.72.0 (103a7ff2e 2023-08-15)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.19.0
    - pnpm: 8.12.1
    - yarn: 1.22.19
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.5.2
    - @tauri-apps/cli [NPM]: 1.5.8

[-] App
```

**Comment by JonasSeifried** [comment]
Got the same. Going down from `"@tauri-apps/cli": "^1.5.8"` to `"@tauri-apps/cli": "1.5.7"` fixes it.

**Comment by chirok11** [comment]
Same for me, 1.5.8 cli is broken.

**Comment by origin-coding** [comment]
Same for me.

**Comment by FabianLars** [comment]
The cli was supposed to update it itself :/ if you delete the `AppData/Local/tauri` folder it will redownload the updated files (you need 1.5.8 to download the correct ones). After that it should work fine again.

**Comment by origin-coding** [comment]
I don't think so, though.
I checked the error message, like the image below:
![屏幕截图 2023-12-19 010636](https://github.com/tauri-apps/tauri/assets/52844714/72d8badf-a1e4-4fcc-be5a-cfe1c9e4f3a6)
It says that in macro CheckIfAppIsRunning, line 2, which looks like this:
![屏幕截图 2023-12-19 010818](https://github.com/tauri-apps/tauri/assets/52844714/c514360b-8db3-4108-a3ff-e5fe8b2aae0d)
Obviously it uses a function called `FindProcessCurrentUser` in **nsis_tauri_utils**

Then I check the tauri-bundler codes, in this line: [get_and_extract_nsis](https://github.com/tauri-apps/tauri/blob/dev/tooling/bundler/src/bundle/windows/nsis.rs#L84), which downloads the nsis_tauri_utils.dll and puts it into the folder, and the URL is this: [NSIS_TAURI_UTILS](https://github.com/tauri-apps/tauri/blob/dev/tooling/bundler/src/bundle/windows/nsis.rs#L40). It now downloads the version 0.2.1.

So I then checked the [nsis-tauri-utils](https://github.com/tauri-apps/nsis-tauri-utils) repository, and found the function `FindProcessCurrentUser` in **crates/nsis-process/src/lib.rs**.

I checked the commit history of this file, as shown in picture below:
![屏幕截图 2023-12-19 011730](https://github.com/tauri-apps/tauri/assets/52844714/4dfd832f-2ad8-4696-8131-038b70597c8e)
The `FindProcessCurrentUser` function was newly added 5 days ago, and it only exists in version 0.2.2.
![屏幕截图 2023-12-19 011750](https://github.com/tauri-apps/tauri/assets/52844714/af358ecc-3706-4294-8d14-ec04cf39bf04)


Maybe you need to have a double check on your [Tauri NSIS bundler file.](https://github.com/tauri-apps/tauri/blob/dev/tooling/bundler/src/bundle/windows/nsis.rs).

**Comment by origin-coding** [comment]
The new download link should be:
https://github.com/tauri-apps/nsis-tauri-utils/releases/download/nsis_tauri_utils-v0.2.2/nsis_tauri_utils.dll

**Comment by FabianLars** [comment]
You're looking at the wrong branch. `dev` is for v2, The correct branch in this context is 1.x where this is correct: https://github.com/tauri-apps/tauri/blob/1.x/tooling/bundler/src/bundle/windows/nsis.rs#L40

**Comment by origin-coding** [comment]
> You're looking at the wrong branch. `dev` is for v2, The correct branch in this context is 1.x where this is correct: https://github.com/tauri-apps/tauri/blob/1.x/tooling/bundler/src/bundle/windows/nsis.rs#L40

That's it, sorry.

**Comment by thewh1teagle** [comment]
Happend to me in v2 too.
Fixed by deleting `%localappdata%\tauri`
