### ISSUE TITLE
[bug] run ios dev, get  E0463

### ISSUE THREAD

**Issue by cieldon32** [tauri-apps/tauri#8414]
### Describe the bug

**error[E0463]: can't find crate for `core`
  |
  = note: the `aarch64-apple-ios-sim` target may not be installed
  = help: consider downloading the target with `rustup target add aarch64-apple-ios-sim`**

and the explain is :
Common causes for missing std or core
*   You are cross-compiling for a target which doesn't have std prepackaged. Consider one of the
    following: + Adding a pre-compiled version of std with rustup target add + Building std from source with cargo build -Z build-std +
    Using #![no_std] at the crate root, so you won't need std in the first place.
*   You are developing the compiler itself and haven't built libstd from source. You can usually build it with x.py build library/std. More
    information about x.py is available in the rustc-dev-guide.

how to do? I can't understand.

**error[E0463]: can't find crate for `compiler_builtins`**
I had add the crate, but the error wasn't fixed.

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 14.0.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.74.0 (79e9716c9 2023-11-13) (Homebrew)
    ✔ Cargo: 1.74.0
    ✔ rustup: 1.26.0 (2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 21.4.0
    - pnpm: 8.9.0
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.18
    - tauri-build [RUST]: 2.0.0-alpha.12
    - wry [RUST]: 0.34.2
    - tao [RUST]: 0.23.0
    - @tauri-apps/api [NPM]: 2.0.0-alpha.12
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.15

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Did you run these steps? https://beta.tauri.app/guides/prerequisites/#ios (in particular `rustup target add aarch64-apple-ios x86_64-apple-ios aarch64-apple-ios-sim` )

tauri info says you installed rust itself via homebrew so this may not work. I'm not really familiar with that so i'd recommend to check the package's docs on adding new targets (i hope they have that). In general though i'd recommend to remove homebrew's rust and use rustup to manage your rust installation.

**Comment by cieldon32** [comment]
> Did you run these steps? https://beta.tauri.app/guides/prerequisites/#ios (in particular `rustup target add aarch64-apple-ios x86_64-apple-ios aarch64-apple-ios-sim` )
> 
> tauri info says you installed rust itself via homebrew so this may not work. I'm not really familiar with that so i'd recommend to check the package's docs on adding new targets (i hope they have that). In general though i'd recommend to remove homebrew's rust and use rustup to manage your rust installation.

rustup target list
aarch64-apple-darwin (installed)
aarch64-apple-ios (installed)
aarch64-apple-ios-sim (installed)
x86_64-apple-ios (installed)

**Comment by FabianLars** [comment]
yeah but that doesn't matter if it doesn't use the toolchain installed via rust. If `tauri info` says it's a homebrew version (via the `(Homebrew)` suffix), it will use that version of rust to compile the app and i assume this installation does not have the targets.

**Comment by cieldon32** [comment]
> yeah but that doesn't matter if it doesn't use the toolchain installed via rust. If `tauri info` says it's a homebrew version (via the `(Homebrew)` suffix), it will use that version of rust to compile the app and i assume this installation does not have the targets.

Thanks, you are right, because the "Homebrew"

**Comment by jswhisperer** [comment]
```
Downloaded openssl-probe v0.1.5
Downloaded openssl-sys v0.9.103
 Downloaded openssl v0.10.66
Downloaded linux-raw-sys v0.4.14
Downloaded 4 crates (2.2 MB) in 1.01s (largest was `linux-raw-sys` at 1.8 MB)
   Compiling serde v1.0.209
   Compiling libc v0.2.158
   Compiling ppv-lite86 v0.2.20
   Compiling serde_spanned v0.6.7
   Compiling toml_datetime v0.6.3
   Compiling cfg-if v1.0.0
   Compiling serde_json v1.0.127
   Compiling once_cell v1.19.0
   Compiling darling v0.20.10
   Compiling semver v1.0.23
error[E0463]: can't find crate for `core`
  |
  = note: the `aarch64-linux-android` target may not be installed
  = help: consider downloading the target with `rustup target add aarch64-linux-android`

error[E0463]: can't find crate for `std`
  |
  = note: the `aarch64-linux-android` target may not be installed
  = help: consider downloading the target with `rustup target add aarch64-linux-android
```
.... 
<details>
  <summary>the rest output and then tauri info</summary>
```
error: could not compile `once_cell` (lib) due to 1 previous error

Caused by:
  process didn't exit successfully: `rustc --crate-name once_cell --edition=2021 /Users/carflow/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=90 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="alloc"' --cfg 'feature="default"' --cfg 'feature="race"' --cfg 'feature="std"' --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values("alloc", "atomic-polyfill", "critical-section", "default", "parking_lot", "portable-atomic", "race", "std", "unstable"))' -C metadata=d45b4835ae69b829 -C extra-filename=-d45b4835ae69b829 --out-dir /Users/carflow/Sites/tauri3/vnc-vue-rust/src-tauri/target/aarch64-linux-android/release/deps --target aarch64-linux-android -C strip=debuginfo -L dependency=/Users/carflow/Sites/tauri3/vnc-vue-rust/src-tauri/target/aarch64-linux-android/release/deps -L dependency=/Users/carflow/Sites/tauri3/vnc-vue-rust/src-tauri/target/release/deps --cap-lints allow` (signal: 5, SIGTRAP: trace/breakpoint trap)
warning: build failed, waiting for other jobs to finish...
error: could not compile `cfg-if` (lib) due to 1 previous error

Caused by:
  process didn't exit successfully: `rustc --crate-name cfg_if --edition=2018 /Users/carflow/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cfg-if-1.0.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=90 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values("compiler_builtins", "core", "rustc-dep-of-std"))' -C metadata=6a28a5bc1a7480e1 -C extra-filename=-6a28a5bc1a7480e1 --out-dir /Users/carflow/Sites/tauri3/vnc-vue-rust/src-tauri/target/aarch64-linux-android/release/deps --target aarch64-linux-android -C strip=debuginfo -L dependency=/Users/carflow/Sites/tauri3/vnc-vue-rust/src-tauri/target/aarch64-linux-android/release/deps -L dependency=/Users/carflow/Sites/tauri3/vnc-vue-rust/src-tauri/target/release/deps --cap-lints allow` (signal: 5, SIGTRAP: trace/breakpoint trap)
    Error failed to build app: failed to build app
```

```
[✔] Environment
    - OS: Mac OS 14.3.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06) (Homebrew)
    ✔ cargo: 1.80.1
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 22.6.0
    - pnpm: 9.7.1
    - yarn: 1.22.22
    - npm: 10.8.2

[-] Packages
    - tauri [RUST]: 2.0.0-rc.6
    - tauri-build [RUST]: 2.0.0-rc.6
    - wry [RUST]: 0.42.0
    - tao [RUST]: 0.29.1
    - tauri-cli [RUST]: 2.0.0-rc.7
    - @tauri-apps/api [NPM]: 2.0.0-rc.3
    - @tauri-apps/cli [NPM]: 2.0.0-rc.7

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite

[-] iOS
    - Developer Teams:
 ```

</details>
  


![Screenshot 2024-08-24 at 10 13 53 pm](https://github.com/user-attachments/assets/fcbc1b53-62f1-458c-99dc-6a730832d378)

![Screenshot 2024-08-24 at 10 20 44 pm](https://github.com/user-attachments/assets/78efe695-ae9f-4857-89b2-ed7811fd6fb2)

**Comment by AlloryDante** [comment]
> ```
> Downloaded openssl-probe v0.1.5
> Downloaded openssl-sys v0.9.103
>  Downloaded openssl v0.10.66
> Downloaded linux-raw-sys v0.4.14
> Downloaded 4 crates (2.2 MB) in 1.01s (largest was `linux-raw-sys` at 1.8 MB)
>    Compiling serde v1.0.209
>    Compiling libc v0.2.158
>    Compiling ppv-lite86 v0.2.20
>    Compiling serde_spanned v0.6.7
>    Compiling toml_datetime v0.6.3
>    Compiling cfg-if v1.0.0
>    Compiling serde_json v1.0.127
>    Compiling once_cell v1.19.0
>    Compiling darling v0.20.10
>    Compiling semver v1.0.23
> error[E0463]: can't find crate for `core`
>   |
>   = note: the `aarch64-linux-android` target may not be installed
>   = help: consider downloading the target with `rustup target add aarch64-linux-android`
> 
> error[E0463]: can't find crate for `std`
>   |
>   = note: the `aarch64-linux-android` target may not be installed
>   = help: consider downloading the target with `rustup target add aarch64-linux-android
> ```
> 
> ....
> 
> the rest output and then tauri info

Got the same error. Did u manage to fix it?

**Comment by jswhisperer** [comment]
Don't remember but apart from scaffolding a new app, I would try deleting "targets" folder,

Can also delete node_modules / package.lock, cargo.lock and try reintalling

**Comment by AnsonCar** [comment]
> yeah but that doesn't matter if it doesn't use the toolchain installed via rust. If `tauri info` says it's a homebrew version (via the `(Homebrew)` suffix), it will use that version of rust to compile the app and i assume this installation does not have the targets.

Thanks, I tried to build the Tauri app but I always get this error because of "Homebrew"
