### ISSUE TITLE
[bug] quick start running tauri on mac causes weird bug

### ISSUE THREAD

**Issue by Uzay-G** [tauri-apps/tauri#8421]
### Describe the bug

I am having this bug on my M2 Mac running a basic tauri app from create-tauri-app, where the tauri app opens and displays for a sec but then my focused window on my computer changes and i can't see the app. For example, whenever i click on the tauri popup it will just move my focus to the window on the right im my window manager, so I can't interact with the app anymore.

https://github.com/tauri-apps/tauri/assets/52892257/7dc5a52b-79b6-44eb-9f02-4b5b3b3aaa70

See screen recording.

### Platform and versions

```text
I am on an M2 using the yabai window manager, and don't understand what's going on. Installed tauri from create-tauri-app.
```

**Comment by FabianLars** [comment]
I doubt anyone in the team knows anything about yabai to be honest. Could you also reach out to them? I can't think of anything weird we're doing in Tauri that would cause this other then the connection between 2 windows (terminal + tauri window) but that's not a tauri specific thing to do either so idk 🤔
