### ISSUE TITLE
[bug] Typescript: Could not find a declaration file for module "@tauri-apps/api/xxx"

### ISSUE THREAD

**Issue by origin-coding** [tauri-apps/tauri#8427]
### Describe the bug

I updated my tauri-apps dependency, and I now can't build successfully.
It tells me that Typescript could not find corresponding declaration file for all my tauri apis.
When I added "type" to the path, it works, like the image below:
![屏幕截图 2023-12-18 151911](https://github.com/tauri-apps/tauri/assets/52844714/8006e25b-38e3-4ec8-85ea-114d6e9498ea)

Here are my dependencies:
```json
  "dependencies": {
    "@tauri-apps/api": "^1.5.2",
    "@vueuse/core": "^10.7.0",
    "@vueuse/integrations": "^10.7.0",
    "@web-types/vuetify": "^2.0.15-1",
    "change-case": "^5.3.0",
    "crypto-js": "^4.2.0",
    "dayjs": "^1.11.10",
    "fuse.js": "^7.0.0",
    "ip-address": "^9.0.5",
    "monaco-editor": "^0.45.0",
    "pinia": "^2.1.7",
    "prettier": "3.1.1",
    "qrcode": "^1.5.3",
    "roboto-fontface": "^0.10.0",
    "tauri-plugin-store-api": "https://github.com/tauri-apps/tauri-plugin-store#v1",
    "terser": "^5.26.0",
    "ua-parser-js": "^1.0.37",
    "uuid": "^9.0.1",
    "vue": "^3.3.12",
    "vue-i18n": "9.8.0",
    "vue-router": "4.2.5",
    "vuetify": "^3.4.7",
    "webfontloader": "^1.6.28"
  },
```
and my tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": false,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "lib": ["ESNext", "DOM", "DOM.Iterable", "ScriptHost"],
    "skipLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    },
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "build/**/*.ts"
  ],
  "references": [{ "path": "./tsconfig.node.json" }],
  "exclude": ["node_modules"]
}

```

Is is because of an mismatch version in my dependencies? Or should I downgrade it? Or shold I add "type" to everywhere I use a tauri api?

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 120.0.2210.77
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.8.0
    - yarn: 1.22.19
    - npm: 10.1.0

[-] Packages
    - tauri [RUST]: 1.5.3
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.6
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.2
    - @tauri-apps/cli [NPM]: 1.5.8

[-] App
```

**Comment by origin-coding** [comment]
I made a mistake, I should change "type" to "types", that was a typo.

**Comment by origin-coding** [comment]
Another error occured when I added "types" to "tauri-apps/api/types/shell":
[commonjs--resolver] Missing "./types/shell" specifier in "@tauri-apps/api" package
Image as below:
![屏幕截图 2023-12-18 153939](https://github.com/tauri-apps/tauri/assets/52844714/abeba587-d762-457b-a012-43ddaf149e47)

**Comment by origin-coding** [comment]
In tauri-apps/api version 1.5.1, the directory looks like this:
![屏幕截图 2023-12-18 154424](https://github.com/tauri-apps/tauri/assets/52844714/af0dc34a-4ae2-4526-a802-fceefd63e1cb)
You can see that type definitions are placed in the same folder with source files.
And this is what it looks like when using version 1.5.2:
![屏幕截图 2023-12-18 154619](https://github.com/tauri-apps/tauri/assets/52844714/601b635f-de6b-4f24-9750-0a31514a9857)
You can see that type definitions are placed in a separate folder.
Mostly it's because of this.

**Comment by origin-coding** [comment]
This error can be fixed by downgrading @tauri-apps/api to version 1.5.1.

**Comment by origin-coding** [comment]
For version 1.5.2, it can be fixed in this way(using clipboard as an example):
```typescript
import { clipboard } from "@tauri-apps/api/types";

await clipboard.writeText("Hello, world!");
```
But the documentation is still not updated, so should I use this way?

**Comment by origin-coding** [comment]
Note that this also works: 
```typescript
import { clipboard } from "tauri-apps/api";
```

**Comment by wuhao-igno** [comment]
I suggest altering the `tsconfig.json` setting from `"moduleResolution": "Node"` to `"moduleResolution": "bundler"`. This modification resolved the issue for me.

**Comment by amrbashir** [comment]
This is fixed and will be available in the next release.
