### ISSUE TITLE
[bug] tauri-apps runs abnormally under window7 32-bit

### ISSUE THREAD

**Issue by BenJChen** [tauri-apps/tauri#8429]
### Describe the bug

tauri.conf.json:
```
  "webviewInstallMode": {
      "type": "fixedRuntime",
      "path": "./Microsoft.WebView2.FixedVersionRuntime.119.0.2151.97.x86"
  }
```

tauri build --target i686-pc-windows-msvc

But when I installed it on win10 system, the app could run normally. But when I run it on win7 32-bit system, I get the prompt：The entry point of the SetProcessMitigationPolicy procedure is not found in the dynamic link library KERNEL32.dll.I can see that the app is open, but it is blank

![ec41b484aa6cc92a61753a08216f7b8f-107109](https://github.com/tauri-apps/tauri/assets/15866873/1d37af01-f515-4e67-baeb-3bde97e3d36b)

### Expected behavior

How to package a system that is compatible with win7 32-bit system and run it smoothly

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.17134 X64
    ✔ WebView2: 120.0.2210.77
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.74.1 (a28077b28 2023-12-04)
    ✔ cargo: 1.74.1 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 16.14.2
    - yarn: 1.22.19
    - npm: 8.5.0

[-] Packages
    - tauri [RUST]: 1.5.3
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.6
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.2
    - @tauri-apps/cli [NPM]: 1.5.8

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Try using a webview2 version that's v109 _or older_. v109 is the last one that supports windows 7.

**Comment by BenJChen** [comment]
> 尝试使用 v109 的 webview2 版本_或更早版本_。 v109是最后一个支持windows 7的版本。



> Try using a webview2 version that's v109 _or older_. v109 is the last one that supports windows 7.

It is indeed a problem with webview2 version and has been solved
