### ISSUE TITLE
[bug] The CloseRequestedEvent cannot prevent the closing of a dynamically created window.

### ISSUE THREAD

**Issue by rowty000** [tauri-apps/tauri#8435]
### Describe the bug

I created a new `WebviewWindow (B)` at runtime within an existing `WebviewWindow (A)` and set up a listener for the `CloseRequestedEvent` of the new webview, intending to execute certain actions before it closes. However, despite calling `preventDefault()`, it doesn't seem to work. Here is my code:
```
<template>
  <div class="container">
    <p>NewWindow</p>
    <el-button @click="createNewWindow">Create</el-button>
  </div>
</template>
<script setup lang="ts">
import { WebviewWindow } from "@tauri-apps/api/window";
const createNewWindow = async () => {
  const webview = new WebviewWindow("media-login-window", {
    url: "https://google.com",
  });
  webview.once("tauri://created", function () {
    // webview window successfully created
    console.log("tauri created");
  });
  webview.once("tauri://error", function (e) {
    console.log("window create error", e);
    // an error occurred during webview window creation
  });

  await webview.onCloseRequested(async (event) => {
    console.log("tauri close-requested", event);
    event.preventDefault();
    // i want do something here, but the new webview closed.
  });
};
</script>
```
While debugging the source code, I found that in the `on_window_event` function, the window instance for checking `has_js_listener` is the newly created `WebviewWindow(B)`. However, the window instance used for registering the event listener is the already existing `WebviewWindow(A)`. Is this a bug, or is there an issue with my usage?
![image](https://github.com/tauri-apps/tauri/assets/7974582/fc5da14d-fa26-4bf4-82cf-715cdbbc8c2e)
![image](https://github.com/tauri-apps/tauri/assets/7974582/5fd63335-983b-4772-ad32-fc7577ef2aec)

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22000 X64
    ✔ WebView2: 114.0.1823.51
    ✔ MSVC: Visual Studio ���ɹ��� 2019
    ✔ rustc: 1.74.1 (a28077b28 2023-12-04)
    ✔ cargo: 1.74.1 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.9.0
    - yarn: 1.22.19
    - npm: 10.1.0

[-] Packages
    - tauri [RUST]: 1.5.3
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.6
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.2
    - @tauri-apps/cli [NPM]: 1.5.7 (outdated, latest: 1.5.8)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by amrbashir** [comment]
> Is this a bug, or is there an issue with my usage?

It is definitely a bug (or rather a use-case we didn't take into account). It might be hard to fix this issue for 1.x without breaking the event system and the crate dependencies, so I will fix it for v2 only instead

For v1, I guess your only option will be to prevent close either through Rust or by evaluating the following script using Rust on the new window or embedding it in the new window
```js
appWindow.onCloseRequested(async (event) => {
    event.preventDefault();
})
```

**Comment by achamas-playco** [comment]
I'm using tauri 1.x and could not get the close request event to fire, so I found a work around:

Add this to your javascript side (mac):

```js
 window.addEventListener('keydown', (e) => {
    if (e.key === 'q' && e.metaKey) {
      e.preventDefault();
      // do some pre-closing stuff...
    }
  });
```

Works on the main window, should work on the dynamically created ones. The browser is good at interrupting keys if you let it.

**Comment by thiagovianav** [comment]
> I'm using tauri 1.x and could not get the close request event to fire, so I found a work around:
> 
> Add this to your javascript side (mac):
> 
>  window.addEventListener('keydown', (e) => {
>     if (e.key === 'q' && e.metaKey) {
>       e.preventDefault();
>       // do some pre-closing stuff...
>     }
>   });
> 
> Works on the main window, should work on the dynamically created ones. The browser is good at interrupting keys if you let it.

if you started using v2, you can do it simpler

```
window.onCloseRequested((e) => {
      e.preventDefault();
      // do what u want, in my case i hide the window instead of closing
      // window.hide();
});
