### ISSUE TITLE
[bug]  small texts, button

### ISSUE THREAD

**Issue by AdribMahmud101** [tauri-apps/tauri#8437]
### Describe the bug

   My tauri app is as expected in the browser window but in tauri dev window the components [texts, buttons] of my app get smaller
![2023-12-19_05-49](https://github.com/tauri-apps/tauri/assets/118984529/0c88e8de-db15-41c6-bc46-d35b5a6ad841)
![2023-12-19_05-51](https://github.com/tauri-apps/tauri/assets/118984529/ca5d5822-2f43-4cd2-b337-3c7344947062)

### Expected behavior

  The web view and tauri dev view should be similiar

### Full `tauri info` output

```text
[✔] Environment
    - OS: Linux Rolling Release X64
    ✔ webkit2gtk-4.0: 2.42.4
    ✔ rsvg2: 2.57.1
    ✔ rustc: 1.74.1 (a28077b28 2023-12-04)
    ✔ cargo: 1.74.1 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.10.0
    - npm: 10.2.5

[-] Packages
    - tauri [RUST]: 1.5.3
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.6
    - tao [RUST]: 0.16.5
    - tauri-cli [RUST]: 1.5.8
    - @tauri-apps/api [NPM]: 1.5.2
    - @tauri-apps/cli [NPM]: 1.5.8

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../build
    - devPath: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Can you test it in epiphany (also known as "Gnome Web")? It's a browser based on webkitgtk which is what's used as tauri's webview on Linux.

**Comment by AdribMahmud101** [comment]
> Can you test it in epiphany (also known as "Gnome Web")? It's a browser based on webkitgtk which is what's used as tauri's webview on Linux.

Yes, the same issue with eniphay. So it's webkitgtk who's causing this. Can you tell me kindly how to fix this issue ?

**Comment by FabianLars** [comment]
No idea, there's no one-fits-all approach. The first (and only) thing i always recommend is using a css reset (many css frameworks have something built-in, if not there's https://necolas.github.io/normalize.css/ for example). But other than that i don't have any ideas , but you're not the first one with this problem :/

Closing this since it's not a tauri issue but feel free to keep discussing this.
