### ISSUE TITLE
[bug] OUT_DIR env var is not set, do you have a build script? 

### ISSUE THREAD

**Issue by hellomsg** [tauri-apps/tauri#8442]
### Describe the bug

```rust
fn main() {
  tauri::Builder::default()
      .invoke_handler(tauri::generate_handler![greet])
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
```

### Full `tauri info` output

```text
Macro expansion:
    compile_error!("OUT_DIR env var is not set, do you have a build script?" )
`generate_context` on docs.rs
```

**Comment by FabianLars** [comment]
Well, do you have a build script? If you used create-tauri-app or tauri init it should have created a `build.rs` file in the src-tauri folder with this content:
```rs
fn main() {
  tauri_build::build();
}
```

**Comment by ggslayer** [comment]
same problem on win10 and v2.0 alpha, and I have the build script:  build.rs

**Comment by FabianLars** [comment]
Can you upload your app to github? Or try a fresh app create via create-tauri-app and compare that with your own app if it works?

**Comment by BitsAndDroids** [comment]
I encountered the same behavior on win11 and tried to create a new app as @FabianLars suggested using the create-Tauri command. The error is also present in the new project. There is a build.rs file present in both of my projects. Besides the error message in my IDE, the build/app functions as expected. If you still need an example app, https://github.com/BitsAndDroids/FlightConnector-Rust
I've iterated over my env vars, and the OUT_DIR is (as expected) not present.
![image](https://github.com/tauri-apps/tauri/assets/77780263/e9999cb4-b804-4517-a647-8682ccf73f11)

I've added a pr with a possible fix
https://github.com/tauri-apps/tauri/pull/8562

**Comment by FabianLars** [comment]
> Besides the error message in my IDE, the build/app functions as expected.

So, are both of you encountering it just in an jetbrains ide? Because if so i'd assume they'll fix it in the next update. Or i really hope so because i'm not a fan of the PR tbh since it's really not our responsibility to set it (otherwise cargo build and rust-analyzer would fail too).

**Comment by BitsAndDroids** [comment]
I'm trying another IDE, but I believe you found the culprit. I've just checked VSCode and the "bug" is gone. At least I've learned how to sign a pr from this. Will close the PR.

**Comment by BitsAndDroids** [comment]
I'm not sure if this is even relevant, but in VSCode, the out_dir isn't set as well. But there isn't an error message displayed. So under the hood the behavior is the same but Jetbrains displayed the error while VSCode doesn't
![image](https://github.com/tauri-apps/tauri/assets/77780263/125672a4-6528-4b99-af3a-68ad1de9c6fe)

**Comment by wonkyDD** [comment]
@BitsAndDroids  Same here. It just only shows error sign in intellij. vscode is fine.

**Comment by bravit** [comment]
Hi folks, we'll see what we can do on the RustRover's side: https://youtrack.jetbrains.com/issue/RUST-13238/Suspicious-macro-expansion-results-in-Tauri-apps

**Comment by Junhuan-Peng** [comment]
I meet the same problem in RustRover, I fix this by delete` target`  folder in the project root

**Comment by FabianLars** [comment]
Closing as the RustRover version that fixes this issue should be available now :)

**Comment by jswhisperer** [comment]
same with rust analyser think deleting targets worked

**Comment by shufl9dka** [comment]
Still having the issue on Ubuntu (24.04) with VS Code (1.94.4). Any suggestions please?

**Comment by ZeeshanAhmadKhalil** [comment]
Restarting the VS code fixed the issue for me

**Comment by wyhinton** [comment]
With `rust-analyzer 0.3.2527` and VS Code `1.101.2` I'm still getting this error. Restarting didn't help. 

<details>
<summary>Error Message </summary>

```shell
error[E0061]: this function takes 2 arguments but 1 argument was supplied
   --> C:\Users\Primary User\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tauri-build-2.0.4\src\acl.rs:409:3
    |
409 |   tauri_utils::plugin::save_global_api_scripts_paths(out_dir);
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^--------- argument #2 of type `std::option::Option<PathBuf>` is missing
    |
note: function defined here
   --> C:\Users\Primary User\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tauri-utils-2.5.0\src\plugin.rs:37:10
    |
37  |   pub fn save_global_api_scripts_paths(out_dir: &Path, mut tauri_global_scripts: Option<PathBuf>) {
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: provide the argument
    |
409 |   tauri_utils::plugin::save_global_api_scripts_paths(out_dir, /* std::option::Option<PathBuf> */);
    |                                                             ++++++++++++++++++++++++++++++++++++

error[E0308]: mismatched types
   --> C:\Users\Primary User\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tauri-build-2.0.4\src\lib.rs:475:51
    |
475 |     tauri_utils::config::parse::read_from(target, env::current_dir().unwrap())?;
    |     -------------------------------------         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&Path`, found `PathBuf`
    |     |
    |     arguments to this function are incorrect
    |
note: function defined here
   --> C:\Users\Primary User\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tauri-utils-2.5.0\src\config\parse.rs:180:8
    |
180 | pub fn read_from(target: Target, root_dir: &Path) -> Result<(Value, Vec<PathBuf>), ConfigError> {
    |        ^^^^^^^^^
help: consider borrowing here
    |
475 |     tauri_utils::config::parse::read_from(target, &env::current_dir().unwrap())?;
    |                                                   +

error[E0308]: mismatched types
   --> C:\Users\Primary User\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tauri-build-2.0.4\src\lib.rs:476:10
    |
476 |   if let Some(merged_config_path) = merged_config_path {
    |          ^^^^^^^^^^^^^^^^^^^^^^^^   ------------------ this expression has type `Vec<PathBuf>`
    |          |
    |          expected `Vec<PathBuf>`, found `Option<_>`
    |
    = note: expected struct `Vec<PathBuf>`
                 found enum `std::option::Option<_>`

error[E0061]: this function takes 3 arguments but 2 arguments were supplied
   --> C:\Users\Primary User\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tauri-build-2.0.4\src\lib.rs:544:26
    |
544 |       ResourcePaths::new(external_binaries(paths, &target_triple).as_slice(), true),
    |                          ^^^^^^^^^^^^^^^^^----------------------- argument #3 of type `&tauri_utils::platform::Target` is missing
    |
note: function defined here
   --> C:\Users\Primary User\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tauri-utils-2.5.0\src\resources.rs:46:8
    |
46  | pub fn external_binaries(
    |        ^^^^^^^^^^^^^^^^^
help: provide the argument
    |
544 |       ResourcePaths::new(external_binaries(paths, &target_triple, /* &tauri_utils::platform::Target */).as_slice(), true),
    |                     
```
</details>
               

<details>
<summary>Cargo.toml</summary>

```yaml
[package]
name = "tauri-v2-sveltekit-template"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "tauri_v2_sveltekit_template_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.3.0", features = [] }

[dependencies]
tauri = { version = "2.6.2", features = [] }
tauri-plugin-shell = "2.3.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2.0.12"
rodio = "0.20.1"
tokio = "1.46.1"
tauri-plugin-log = "2"


```

</details>

**Comment by Krulknul** [comment]
> Restarting the VS code fixed the issue for me

Same. Thought it was gonna be a doozy, but this was one of those rare occasions when "reload window" doesn't do the trick

**Comment by Krulknul** [comment]
> > Restarting the VS code fixed the issue for me
> 
> Same. Thought it was gonna be a doozy, but this was one of those rare occasions when "reload window" doesn't do the trick

No, I was too quick. Waited a bit and the warning is back

**Comment by Y2KForever** [comment]
I also ran into this recently. Happened after i ran `cargo clean`.

Tauri info:
```
[✔] Environment
    - OS: Mac OS 14.4.1 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.87.0 (17067e9ac 2025-05-09)
    ✔ cargo: 1.87.0 (99624be96 2025-05-06)
    ✔ rustup: 1.28.2 (e4f3ad6f8 2025-04-28)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (overridden by environment variable RUSTUP_TOOLCHAIN)
    - node: 20.11.0
    - yarn: 1.22.22
    - npm: 10.2.4

[-] Packages
    - tauri 🦀: 2.7.0
    - tauri-build 🦀: 2.3.1
    - wry 🦀: 0.52.1
    - tao 🦀: 0.34.0
    - tauri-cli 🦀: 2.7.1

[-] Plugins
    - tauri-plugin-positioner 🦀: 2.3.0
    - tauri-plugin-opener 🦀: 2.2.3, (outdated, latest: 2.4.0)

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
```

`rust-analyzer: 0.3.2577`
`vs code: 1.103.0 `

**Comment by Haprog** [comment]
I just ran into this on VS Code in Windows 11, but just running the `Developer: Reload Window` command from the VS Code command palette got rid of the error.

**Comment by stevenstonie** [comment]
> I just ran into this on VS Code in Windows 11, but just running the `Developer: Reload Window` command from the VS Code command palette got rid of the error.

well a reload window usually fixes a lot of bugs in either vscode or its extensions. good to know tho, nice

**Comment by zhouyi207** [comment]
when I delete the src-tauri/capabilities/default.json some unuseful properties Its ok

```json
{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "default",
  "description": "Capability for the main window",
  "windows": ["main"],
  "permissions": [
    "core:default",
    "opener:default",
    "bug or something?" // ==> delete this

  ]
}
```
