### ISSUE TITLE
Unable to  get data in exe 

### ISSUE THREAD

**Issue by abhijitpatil181171** [tauri-apps/tauri#8444]
### Describe the bug

i am having react application in which i am using node backend which is deployed on ec2.when i make build of react application using tauri and run exe no data is coming from backen (unable to connect with backend).how to solve this issue.  i have did all true in allowlist
 "tauri": {
    "allowlist": {
      "all": true
    }, still unable to connect with backend but when i run tauri locally it is running and connecting with backend successfully

### Expected behavior

it should connect with node backend when i make build and run exe

### Full `tauri info` output

```text
"tauri": {
    "allowlist": {
      "all": true
    },
```

**Comment by FabianLars** [comment]
Can you try a debug build via `yarn tauri build --debug` or `npm run tauri build -- --debug` (npm needs an extra --)? The binary will be in target/debug/ and will have the devtools console (right click on the window -> inspect) so you can check it for any errors.

If that doesn't help please show a bit of your code so we can see what you're trying. Also please provide the full output of the `tauri info` command as the issue template asked you too.

Btw, the allowlist only applies to apis from `@tauri-apps/api` (or `window.__TAURI__`), if you use the browser default http apis it won't have an effect.

**Comment by abhijitpatil181171** [comment]
main.3273e74f.js:2  Mixed Content: The page at 'https://tauri.localhost/user-dashboard' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://13.200.236.145:5000/profiles/'. This request has been blocked; the content must be served over HTTPS.
getting this error when insepct exe
  "security": {
      "csp": "default-src blob: data: filesystem: ws: http:'unsafe-eval' 'unsafe-inline' 'self' http://13.200.236.145:5000; img-src: 'self'"
    },
    my backend is on http so i want to run tauri over http not https

**Comment by FabianLars** [comment]
https://tauri.app/v1/api/config/#securityconfig.dangeroususehttpscheme
