### ISSUE TITLE
[bug] windows shortcut icon not be replaced

### ISSUE THREAD

**Issue by Stormpass** [tauri-apps/tauri#8453]
### Describe the bug

1. i replace the icons follow the step : https://tauri.app/v1/guides/features/icons/
2. the new icons was created successfully
3. i encounter the app version and run `npm run tauri build`  and the new installer was build success
4. i install the app successfully
5. the shortcut icon not be replaced
6. when i right click shortcut and view the detail, i found that detail windows show the new icon
7.
![image](https://github.com/tauri-apps/tauri/assets/31079748/3c740b2e-13e8-4fb6-a5e7-ba7283b855a3)
8. i try to uninstall app and reinstall app, reboot my computer and the problem was still here

tell me how to fix this? thank you

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 120.0.2210.77
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.14.0
    - yarn: 1.22.15
    - npm: 9.3.1

[-] Packages
    - tauri [RUST]: 1.5.2
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.1 (outdated, latest: 1.5.3)
    - @tauri-apps/cli [NPM]: 1.5.6 (outdated, latest: 1.5.9)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by Stormpass** [comment]
I cleared the windows thumbnails and this problem no longer occurs, if this is a problem with my computer, please close this Issue
Open the Start menu, find Windows Administrative Tools → Disk Cleanup → C Disk → Check "Thumbnails" → OK.

**Comment by amrbashir** [comment]
Windows caches thumbnails and icons and it might take some time for the new icon to be updated in the cache.
