### ISSUE TITLE
White window

### ISSUE THREAD

**Issue by awtGerry** [tauri-apps/tauri#8462]
### Describe the bug

A couple of days ago the app was running without any problems, yesterday I tried to run the app with `pnpm tauri dev` and it opened with a full white window without anything in it (web view in localhost:1420 shows the front-end of the app fine).

### Full `tauri info` output

```text
[✘] Environment
    - OS: NixOS 23.11.0 X64
    ✔ webkit2gtk-4.0: 2.42.2
    ✘ rsvg2: not installed
      Visit https://tauri.app/v1/guides/getting-started/prerequisites to learn more about tauri prerequisites
    ✔ rustc: 1.74.1 (a28077b28 2023-12-04)
    ✔ cargo: 1.74.1 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (1980-01-01)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 18.18.2
    - pnpm: 8.10.2
    - npm: 9.8.1

[-] Packages
    - tauri [RUST]: 1.5.4
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.9

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Stack trace

```text
Finished dev [unoptimized + debuginfo] target(s) in 7.27s
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1054x1058: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1054x1058: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1054x1058: Permission denied
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1918x1058: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1918x1058: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1918x1058: Permission denied
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1
```

### Additional context

I update my system recently and with it the latest NVIDIA drivers for 470xx (The card is a GTX 660). Tested in other computers and it run without this problem.

**Comment by FabianLars** [comment]
Please try again after setting the `WEBKIT_DISABLE_DMABUF_RENDERER=1` env var. This seems to be related to the known problems webkitgtk 2.42 has with nvidia drivers unfortunately :/

**Comment by awtGerry** [comment]
Yes that seems to fix it for now, thank you!

**Comment by Dhruv7201** [comment]
got same error by running below command in terminal it got fixed

`WEBKIT_DISABLE_DMABUF_RENDERER=1`

**Comment by nobane** [comment]
I ran into this issue trying use webkit2gtk on arch linux (with an nvidia card) and I was able to fix it **without** setting `WEBKIT_DISABLE_DMABUF_RENDERER=1`.

Here is how I fixed it:


1. Check if you have modesetting enabled via

        cat /sys/module/nvidia_drm/parameters/modeset

2. If you see printed `N` then you need to enable it with

        echo options nvidia_drm modeset=1 | sudo tee /etc/modprobe.d/nvidia_drm.conf

3. Restart your computer

**Comment by an-Iceberg** [comment]
Just in case someone finds themselves in the same situation as me:

The solution from @nobane didn't work for me.

Setting the environment variable did.

You can set it by appending `WEBKIT_DISABLE_DMABUF_RENDERER=1` to the end of `etc/profile`.

[This is where i found that out](https://wiki.archlinux.org/title/NVIDIA#Vertical_sync_using_TwinView)

**Comment by OlegSadJktu** [comment]
thx, i was fixing this problem with soundux
