### ISSUE TITLE
[feat] Can specifies the target directory in `bundle.resources` when embedding additional files

### ISSUE THREAD

**Issue by capvor** [tauri-apps/tauri#8481]
### Describe the problem

My application depend on a closed source dynamic link library. 
So, I should copy it into exe folder when developing and bundle.

I found the guide [Embedding Additional Files](https://tauri.app/v1/guides/building/resources), configures as following:
```
    "bundle": {
      ...
      "resources": [
        "foo-sys/foo/win/foo.dll"
      ]
```
the foo.dll will be copy to `target_dir/foo-sys/foo/win/`.

but i expect it to be copied into `target_dir/`.

### Describe the solution you'd like

```
    "bundle": {
      ...
      "resources": [
        {"from": "foo-sys/foo/win/foo.dll", to: "./"}
      ]
```

**Comment by amrbashir** [comment]
you can already do this like this:
```json
    "bundle": {
      ...
      "resources": {
        "foo-sys/foo/win/foo.dll":  "./"
      }
```

where you use an object for `resources` instead of an array
