### ISSUE TITLE
[bug] "process.env.TAURI_ENV_PLATFORM" is undefined by command "pnpm tauri ios dev"

### ISSUE THREAD

**Issue by guobaorou-man** [tauri-apps/tauri#8484]
### Describe the bug

Command "pnpm tauri ios dev" can't get the process.env.TAURI_ENV_PLATFORM correctly.
Command "pnpm tauri android dev" works.

![vite](https://github.com/tauri-apps/tauri/assets/51397030/86a3a9e6-5190-451b-946b-8fb6b4623353)
vite.config.ts

![print ios](https://github.com/tauri-apps/tauri/assets/51397030/3904846c-fadb-4bdb-8cfd-ddd19741147e)
terminal print for ios

![print android](https://github.com/tauri-apps/tauri/assets/51397030/766dd4f4-2ba5-4fd7-b695-8d06ecb003d7)
terminal print for android

Did I got something wrong?

### Full `tauri info` output

```text
> tauri "info"


[✔] Environment
    - OS: Mac OS 14.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.74.1 (a28077b28 2023-12-04)
    ✔ cargo: 1.74.1 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 17.9.1
    - pnpm: 8.9.2
    - npm: 8.11.0

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.20
    - tauri-build [RUST]: 2.0.0-alpha.13
    - wry [RUST]: 0.35.1
    - tao [RUST]: 0.24.0
    - @tauri-apps/api [NPM]: 2.0.0-alpha.13
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.20

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite

[-] iOS
    - Developer Teams: ** * (ID: *******)
```

**Comment by amrbashir** [comment]
Should be fixed in latest release
