### ISSUE TITLE
[bug] setContentProtected  does not work for new link with target as _tauri or _blank

### ISSUE THREAD

**Issue by sheshadri** [tauri-apps/tauri#8488]
### Describe the bug

setContentProtected set to true does not work when clicked on a new link with target as _tauri or _blank

### New WebviewWindow

`const webview = new WebviewWindow('student', {
    url: 'https://google.com'
  });
webview.setContentProtected(true);
`
### Default appWindow

appWindow.setContentProtected(true);

### setting it in tauri.conf.json

 "windows": [
      {
        "fullscreen": false,
        "resizable": true,
        "title": "New App",
        "width": 800,
        "height": 600,
        "contentProtected": true
      }
    ]

### Expected behavior

Taking Screenshots should also be disabled in new child window / tab

### Full `tauri info` output

```text
> tauri info


[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 120.0.2210.91
    ✔ MSVC:
        - Visual Studio Build Tools 2019
        - Visual Studio Build Tools 2022
    ✔ rustc: 1.74.1 (a28077b28 2023-12-04)
    ✔ cargo: 1.74.1 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.8.0
    - pnpm: 8.9.0
    - yarn: 1.22.21
    - npm: 9.6.7

[-] Packages
    - tauri [RUST]: 1.5.3
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.6
    - tao [RUST]: 0.16.5
    - tauri-cli [RUST]: 1.5.9
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.9

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:3001/
    - bundler: Vite
```

### Additional context

Tried getting all windows using getALL() but the new window/tab doesn't register at all.

**Comment by amrbashir** [comment]
Window creation is async and needs to wait for it to be created before you can use methods on it
```js
  let webview = new WebviewWindow("student", { url: "https://google.com" });
  webview.once("tauri://created", function () {
    webview.setContentProtected(true);
  });
```

**Comment by sheshadri** [comment]
Sorry to reopen, tried the below code also.

`const webview = new WebviewWindow('test', {
    url: 'https://google.com'
  });
  
  webview.once('tauri://created', function () {
    webview.center()
    webview.setTitle("New App")
    webview.setContentProtected(true);
});`

**Comment by amrbashir** [comment]
Please make a repro that I can test because it works fine using the snippet I posted.

**Comment by sheshadri** [comment]
Sure will do so, it works fine for the first window, if you open a new tab or new window( ctrl click or right click open url in new tab), setContentProtected fails for the newly opened window/tab.

**Comment by amrbashir** [comment]
I see, unfortunately, that is intended (or rather the default behavior of Webview2) "ctrl click" opens a new tauri window that doesn't necessarily follow the `contentProtection` value of the window that triggered it.

You will need to inject a script into your window that catches `click` on this links and manually open new tauri windows.

**Comment by sheshadri** [comment]
Okay will try that, currently I have disabled ctrl + click and right click context menu. Will update if the above method works out.

Thanks!
