### ISSUE TITLE
Question:  Copy/Paste To/From Clipboard

### ISSUE THREAD

**Issue by dfirence** [tauri-apps/tauri#849]
Hello 

Similar to Electron that has APIs to Copy/Paste and Context Menus, does Tauri have clipboard support?

**Comment by lucasfernog** [comment]
Not yet, but we'll have it when the new bindings are used, #846
Context menus might take a while though, it needs support on webview/webview or our custom window management, #837

**Comment by dfirence** [comment]
Thanks Lucas@, would you therefore agree that for copy/paste clipboard, I should implement in front-end, like if I use Angular then implement as much as it can there?

**Comment by lucasfernog** [comment]
Yeah so the only issue I see is that the support on Windows is incomplete: https://github.com/webview/webview/pull/405

Maybe we should ship our own implementation? what do you think @nothingismagick

**Comment by nothingismagick** [comment]
Well, the thing I think our clipboard should do under all circumstances is have a purging method. I mean, after this whole iOS scandal and the general insecurity of the clipboard, I'd like to have a secure paste pattern that allows the dev to control the paste buffer. I'm thinking of chainable things like `paste.toText` which sanitizes html, `paste.thenPurge` which clears the clipboard.

**Comment by nothingismagick** [comment]
The new WRY system does allow for copy & paste on macos. Closing as resolved

**Comment by ghost** [comment]
good to know this works! maybe update the home page too since it's still marked as planned

**Comment by u2m4c6** [comment]
So is the clipboard now supported on all operating systems? Definitely update the home page!!! I almost decided to stop my investigation into using Tauri until I found this issue through Google!

**Comment by Janaka-Steph** [comment]
Still not working for me on MacOS, tauri 1.0.0-beta.8

**Comment by FabianLars** [comment]
@Janaka-Steph on macOS you need a window menu to support copy/past (and more), did you add one?
If not, here's an example: https://github.com/probablykasper/mr-tagger/blob/master/src-tauri/src/main.rs#L28-L78

**Comment by Janaka-Steph** [comment]
> @Janaka-Steph on macOS you need a window menu to support copy/past (and more), did you add one?
> If not, here's an example: https://github.com/probablykasper/mr-tagger/blob/master/src-tauri/src/main.rs#L28-L78

No I don't have a menu. Why is it related? :/

**Comment by FabianLars** [comment]
Well, that's just how things work on macOS (not tauri specific) 🤷
