### ISSUE TITLE
[bug] After tuari project dependency is installed, running `pnpm tauri dev` cannot run,

### ISSUE THREAD

**Issue by muyaCode** [tauri-apps/tauri#8509]
### Describe the bug

After tuari project dependency is installed, running `pnpm tauri dev` cannot run,
report: thread '<unnamed>' panicked at src\interface\rust.rs:451:79: called `Option::unwrap()` on a `None` value stack backtrace: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace. * The terminal will be reused by the task, press any key to close.

### Expected behavior

Can operate normally

### Full `tauri info` output

```text
thread '<unnamed>' panicked at src\interface\rust.rs:451:79: called `Option::unwrap()` on a `None` value stack backtrace: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace. * The terminal will be reused by the task, press any key to close.
```

**Comment by muyaCode** [comment]
Yes, it is dependent on @tauri-apps/cli version 1.5.9 error, version 1.5.8 and earlier versions do not have this error

**Comment by FabianLars** [comment]
Hi, could you share a minimal reproduction (or your project itself)? If not, at least your project structure (folders) and whether you use a cargo workspace (and its config)

**Comment by muyaCode** [comment]
@FabianLars Error of official API module @tauri-apps/cli version 1.5.9, version 1.5.8 does not have this error, I am due to the old project to upgrade @tauri-apps/cli dependent version to 1.5.9 error. My project technology stack is: vue3.4.3+typescript5.3.3+vite5.0.10

**Comment by FabianLars** [comment]
Yes, and it makes sense that it's a new error in 1.5.9 because the line reported in your first error indeed changed in the last release. But i don't see what actually triggered it. For that i need to know your app's rust project setup because i can't reproduce it on my machine.

So yeah, my questions from my first answer (about your folder structure and cargo configs) still has to be answered. Also, what OS are you using?

**Comment by muyaCode** [comment]
@FabianLars 
[tool.zip](https://github.com/tauri-apps/tauri/files/13805083/tool.zip)
This is a minimal reproduction of my project,I deleted a lot of code and kept the parts that reported errors.
I have used two computers to run, both of which are exactly the same error as I mentioned above. The two computers' systems are windows10 Professional Edition and windows11 Home edition respectively, and the pnpm is used for the dependent installation, and the Node version is 20.9.0

**Comment by muyaCode** [comment]
@FabianLars   Please ignore the minimum project code given to me, I think I have found the problem: I created the project in a folder with [], such as' pnpm create tauri-app 'in the [Tauri] folder, and upgraded the dependency @tauri-apps/cli version to 1.5.9. So there's this error problem. I tried version 1.5.8 before version did not have this problem

**Comment by FabianLars** [comment]
Okay thanks. Can you try this and see if it works for you again?
```
cargo install tauri-cli --git https://github.com/tauri-apps/tauri --branch fix-watch-workspace --debug
cargo tauri dev
```
This will install the tauri cli from the branch where i tried to fix your issue (alongside another one).

**Comment by muyaCode** [comment]
Thanks, I installed the fixed version according to the command you gave, and running 'cargo tauri dev' is fine

**Comment by FabianLars** [comment]
Thank you for testing it :)
