### ISSUE TITLE
[bug]: image load error 

### ISSUE THREAD

**Issue by drl990114** [tauri-apps/tauri#8516]
### Describe the bug

i want to load a https image, However, there are certain security restrictions when loading this image. I currently suspect that there are certain requirements for the domain name of the source website.

img url: https://i2.kknews.cc/SIG=1of3siu/5qr00060rss39243533.jpg

Because the current performance is like this：

- mac build: image load success
- mac dev: image load error
- windows build: image load error
- windows dev: image load error

One of the main differences between them is the origin.

in windows build, server url is 'http://tauri.localhost': 
<img width="438" alt="image" src="https://github.com/tauri-apps/tauri/assets/48054715/1bbdeb6c-8b6f-46ad-af01-bf59a8163dab">

in mac build, server origin is "tauri://localhost":
<img width="376" alt="image" src="https://github.com/tauri-apps/tauri/assets/48054715/b871cad1-4339-452f-8d45-9e7d03f7b411">

I haven't found any of the existing functions that can solve my problem, so I want to ask for help, hoping that this problem can be solved, such as supporting the address of a custom service.

Reproduction repo: https://github.com/drl990114/tauri-issue

### Reproduction

Reproduction repo: https://github.com/drl990114/tauri-issue

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 120.0.2210.91
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-pc-windows-msvc (default)
    - node: 20.8.0
    - pnpm: 8.10.0
    - yarn: 3.6.1
    - npm: 10.1.0

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.19
    - tauri-build [RUST]: 2.0.0-alpha.12
    - wry [RUST]: 0.35.1
    - tao [RUST]: 0.24.0
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.18

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:3000/
    - framework: React
    - bundler: Rollup
```

**Comment by FabianLars** [comment]
Could you also try `tauri build` on windows with tauri v1? In v1 it used `https://` instead of `http://`. If that also doesn't work (or if you need to use v2 before we can add an option for https) you'll have to use tauri's http module or rust to request the image which ignored cors (and allows you to set a custom origin if that's required).
But yeah, this is a server-side configuration issue and we can't disable the webview's security mechanism, therefore i have to close this issue.

**Comment by drl990114** [comment]
<img width="798" alt="image" src="https://github.com/tauri-apps/tauri/assets/48054715/473ff745-ee4d-432f-a4a1-de67b77e52b1">

@FabianLars `https` still doesn't work, is there any other way to make it work if it can't support changing the server url?

**Comment by FabianLars** [comment]
Yes, see my comment above:
> you'll have to use tauri's http module or rust to request the image which ignores cors (and allows you to set a custom origin if that's required).

The first part talks about https://tauri.app/v1/api/js/http#fetch (note that this is _not_ the browser native fetch!), the second part about https://docs.rs/reqwest/ for example. You'll request the image as binary data and then show it in the image manually for example like this https://stackoverflow.com/a/14918390

This is the only way i can think of where you can get around server side limitations.

**Comment by drl990114** [comment]
Thank you for your patient answer. I didn't fully understand the meaning of the original answer at the time. 

> The first part talks about [tauri.app/v1/api/js/http#fetch](https://tauri.app/v1/api/js/http#fetch) (note that this is not the browser native fetch!), the second part about [docs.rs/reqwest](https://docs.rs/reqwest/) for example. You'll request the image as binary data and then show it in the image manually for example like this [stackoverflow.com/a/14918390](https://stackoverflow.com/a/14918390)

I will try these methods.

**Comment by drl990114** [comment]
It's working, thank you!
