### ISSUE TITLE
Memory Leak in renderer process when regularly emitting events from Rust -> js

### ISSUE THREAD

**Issue by simon-wh** [tauri-apps/tauri#852]
**Describe the bug**
I've been able to replicate this issue both on Linux and Windows (Edge backend). The app I'm writing will emit an update to the renderer process using `tauri::event::emit` with updated data and I have single `listen` call on the javascript to receive the events. Over time the memory usage will slowly go up, the more events per second, the quicker it increases. I attempted mitigation by forcing updates at 15Hz rather than the 100Hz it was before but that just delays the issue. I started on Linux and couldn't determine the source of all the added memory due to lack of memory profiling tools. However, when I tried it on Windows and noticed the same behaviour, I was able to somewhat find the root of the issue using the Edge dev tools.

**To Reproduce**
1. Repeatedly emit events from Rust -> Js
2. Watch memory creep up

(If needed I can try whip up a basic app to demo the issue)

**Expected behavior**
Not have all my ram eaten

**Screenshots**
Below is the heap diff after letting the memory creep up for a bit. A substantial amount of the heap diff are these functions & the related strings and scope closures
![image](https://user-images.githubusercontent.com/10797576/87856238-b8ca8e00-c915-11ea-9183-4cb72a347b2a.png)
Below is the source of where all these new functions were created. (Notice how `once` is false)
![image](https://user-images.githubusercontent.com/10797576/87856423-fa0f6d80-c916-11ea-8f70-9f70a80237b0.png)

Below is the function call up the call stack where this function originates from
![image](https://user-images.githubusercontent.com/10797576/87856236-aea88f80-c915-11ea-9ea3-124899eee87a.png)

From what I can tell, every time an event is emitted it makes another call back to validate the salt. Each one of these creates a function handler for getting the response, but the `once` property is not being set correctly so the function handler never gets deleted after the function has been used to get the response for the salt validation

I believe [here](https://github.com/tauri-apps/tauri/blob/cd5b401707d709bf8212b0a4c34623f902ae40f9/cli/tauri.js/api-src/tauri.ts#L54), `true` needs to be passed to the `transformCallback` function so they get properly cleaned up. I imagine that this issue effects every promisified call that happens, so this is quite severe.

**Platform and Versions (please complete the following information):**
~~Operating System - Linux(5.4.51-1-lts) - linux/x64~~

~~Node.js environment
  Node.js - 13.8.0
  tauri.js - 0.9.1~~

~~Rust environment
  rustc - 1.45.0-nightly
  cargo - 1.45.0-nightly
  tauri-bundler - 0.8.5~~

~~Global packages
  NPM - 6.13.6
  yarn - 1.22.4~~

~~App
  tauri.rs - 0.7.5
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  Windows - Edge
  distDir - ../build
  devPath - http://localhost:3000~~
I realised after posting that above isn't super relevant, given that this is my Linux env not the Windows env that I'm referencing. However, I don't think it's super relevant anyway given the nature of this issue

**Comment by nothingismagick** [comment]
Thanks for the report @simon-wh - your triage will make it easy to track down.

**Comment by lucasfernog** [comment]
Thank you for reporting and pretty much fixing it for us :D

**Comment by nothingismagick** [comment]
@lucasfernog and I just agreed this is the issue of the year. You just won a limited edition `beta tauri` tshirt. Get in contact on discord, and we'll send you one when beta lands.

**Comment by simon-wh** [comment]
Oh wow! Thank you! :smile: I'll get in touch

**Comment by DennisZhangOiler** [comment]
Hi I am still encounting this problem by sending huge uint8 array from rust side to js side, the memory increase rapidly and got OOM after a while.

**Comment by DennisZhangOiler** [comment]
FYI it's on linux Ubuntu/Debian, I can provide a basic reproduciable repo if needed.
