### ISSUE TITLE
[bug] How to use RegisterDragDrop on windows with tauri?

### ISSUE THREAD

**Issue by Jamzy01** [tauri-apps/tauri#8532]
### Describe the bug

Currently, I'm trying to implement my own file drag drop system for my app, since the inbuilt tauri one doesn't include any [drop effect](DROPEFFECT) data. Calling [RegisterDragDrop](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Ole/fn.RegisterDragDrop.html) at the moment though is clearly working, just not as expected.

### Reproduction

If I drag a file over the title bar of the window, then it works and events are picked up, but if I drag it over the actual content of the window, no events are received.

### Expected behavior

What I expected would happen is that file dragging would work for both the title bar and actual content of the window.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 120.0.2210.91
    ✔ MSVC:
        - Visual Studio Build Tools 2019
        - Visual Studio Community 2022
    ✔ rustc: 1.76.0-nightly (37b2813a7 2023-11-24)
    ✔ cargo: 1.76.0-nightly (71cd3a926 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: nightly-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 21.5.0
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 1.5.2
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.5
    - tao [RUST]: 0.16.2
    - tauri-cli [RUST]: 1.5.6
    - @tauri-apps/api [NPM]: 1.3.0 (outdated, latest: 1.5.3)
    - @tauri-apps/cli [NPM]: 1.5.6 (outdated, latest: 1.5.9)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:5173/
    - framework: React
    - bundler: Vite
```

### Additional context

I'm only guessing, but I'm not sure if webview2 does something weird like overlaying it's own window on the window created by tauri. It seems according to [this page](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/windowed-vs-visual-hosting?tabs=dotnetcsharp), that webview2 hosts can use a windowed or visual hosting approach, and I don't really understand it, but I assume tauri uses the visual approach, otherwise my file drag and drop should work fine.

I am also calling `.disable_file_drop_handler()` on the window builder, and running the code below to disable inbuilt file drop handlers from both tauri and webview2 to ensure no interference with my app's custom implementation.

```rs
window
  .with_webview(|webview| {
      let controller: ICoreWebView2Controller4 = std::mem::transmute(
          webview.controller()
      );
  
      controller
          .SetAllowExternalDrop(false)
          .expect("Failed to set allow external drop");
  })
  .expect("Failed to remove inbuilt webview2 drag drop handler");
```

**Comment by FabianLars** [comment]
Did you compare your own work with tauri's implementation <https://github.com/tauri-apps/wry/blob/dev/src/webview2/file_drop.rs>?

> but I assume tauri uses the visual approach, otherwise my file drag and drop should work fine.

Tauri uses the windowed approach which is why tauri's file drop handler conflicts with html5 drag and drop, see https://github.com/tauri-apps/wry/issues/904 and the linked issues in there.

**Comment by amrbashir** [comment]
Nothing we can do unfortunately, webview2 is a windowed control so you also need to register drag-n-drop on it as well.
