### ISSUE TITLE
[bug] Run AppImage: GLib-GIO-ERROR Settings schema error

### ISSUE THREAD

**Issue by wyhaya** [tauri-apps/tauri#8541]
### Describe the bug

Unable to run Tauri-built AppImage on newer systems.

### Error
```bash
# From: ubuntu:20.04 build, Run in: Fedora 39
./Example.AppImage

(tauri-hello:137661): GLib-GIO-ERROR **: 21:05:50.925: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
# Process exit
```

You must do this to run properly
```bash
GDK_BACKEND=x11 ./Example.AppImage
```

---
If we build AppImage from `ubuntu:latest` it works perfectly fine, But to make sure it works on older systems, it makes sense for us to build it in `ubuntu:20.04`.

### Reproduction

1. Build any Tauri App in Docker `ubuntu:20.04`
2. Run the output .AppImage on `Fedora 39` or `Ubuntu 23`.

You will see the following error:
```bash
(tauri-hello:137661): GLib-GIO-ERROR **: 21:05:50.925: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
# Process exit
```

### Expected behavior

Can open the app normally

### Full `tauri info` output

```text
[✔] Environment
    - OS: Ubuntu 20.4.0 X64
    ✔ webkit2gtk-4.0: 2.38.6
    ✔ rsvg2: 2.48.9
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 20.10.0
    - pnpm: 8.14.0
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 1.5.4
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.5
    - tauri-cli [RUST]: 1.5.9
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 1.5.9

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../src
    - devPath: ../src
```

### Additional context

Related issues:
https://github.com/StarlaneStudios/Surrealist/issues/162

Other:
I try [Spacedrive](https://www.spacedrive.com/), which also seems to be built in `ubuntu:20.04`, but it works fine.

https://github.com/spacedriveapp/spacedrive/blob/8d9e6dbf39adc9b42bb6a12ff8938039d8732326/.github/workflows/release.yml#L29C19-L29C31

**Comment by FabianLars** [comment]
Sad, i [reverted](https://github.com/tauri-apps/linuxdeploy-plugin-gtk/commit/b5eb8d05b4c0ed40107fe2158c5d8527f94568ef) the appimage bundler change to add back the `GDK_BACKEND=x11` env var to all appaimages again.
It looked like it may not be needed anymore but sadly i was wrong. At least we know the exact error now, or one of them.

Thanks for the report.

P.S. No new tauri cli version is required but you may have to delete `~/.cache/tauri` to force a redownload of the script (should happen without deleting it too but just in case it doesn't)

**Comment by Twig6943** [comment]
Any updates on this? Wayland is actively improving these days and tauri seems to be better than electron

**Comment by FabianLars** [comment]
No. And nobody in the team will look into it. At this point we hope that the broader gtk/appimage community will figure it out (I doubt it though).

My recommendation would be to not rely on appimages (for tauri apps) if possible and rather use something like flatpaks.
