### ISSUE TITLE
[feat] Add ability to get the app version from Rust side

### ISSUE THREAD

**Issue by aleksey-hoffman** [tauri-apps/tauri#8556]
### Describe the problem

Right now you cannot get the app version from the Rust side, even though it exposes the API for the frontend.

It would be nice if Tauri exposed all the basic info usually needed for apps. At least the app version

### Describe the solution you'd like

```rust
use tauri::{PackageInfo};

fn print_app_version() {
    let version = PackageInfo::get_version();
    println!("App Version: {:?}", version);
}
```

**Comment by FabianLars** [comment]
You need access to an instance of App, AppHandle or Window (f.e. from the setup hook, or inside [tauri commands](https://tauri.app/v1/guides/features/command/#accessing-an-apphandle-in-commands)) and then you can get it via `app.package_info().version`. This should be the same as the js api.

**Comment by aleksey-hoffman** [comment]
@FabianLars thanks for the info mate, would be great to have this info in the docs
