### ISSUE TITLE
unable to invoke node js binary in sidecar 

### ISSUE THREAD

**Issue by abhijitpatil181171** [tauri-apps/tauri#8564]
### Describe the bug

I have backend in node with sqlite . i have created binary of node using pkg but when i use this binary as sidecar and invoked in main.rs then i am getting error as shown img
![image](https://github.com/tauri-apps/tauri/assets/142501301/2dbbf01c-a853-4f12-9549-c9d6f153d21c)

### Expected behavior

main.rust should run backend binary so that my frontend can access backend api

### Full `tauri info` output

```text
{
  "$schema": "../node_modules/@tauri-apps/cli/schema.json",
  "build": {
    "beforeBuildCommand": "npm run build",
    "beforeDevCommand": "npm run start",
    "devPath": "http://localhost:3000",
    "distDir": "../build"
  },
  "package": {
    "productName": "web-application",
    "version": "0.1.0"
  },
  "tauri": {
    "allowlist": {
      "all": true,
      "shell": {
        "sidecar": true,
        "scope": [
          {
            "name": "D:\\Test-Json\\node-sqlite-backend\\server-win",
            "sidecar": true
          }
        ]
      }
    },

    "bundle": {
      "active": true,
      "category": "DeveloperTool",
      "copyright": "",
      "deb": {
        "depends": []
      },
      "externalBin": ["D:\\Test-Json\\node-sqlite-backend\\server-win"],
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "identifier": "com.yourdomain.yourapp",
      "longDescription": "",
      "macOS": {
        "entitlements": null,
        "exceptionDomain": "",
        "frameworks": [],
        "providerShortName": null,
        "signingIdentity": null
      },
      "resources": [],
      "shortDescription": "",
      "targets": "all",
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "security": {
      "dangerousDisableAssetCspModification": false,
      "dangerousRemoteDomainIpcAccess": [],
      "dangerousUseHttpScheme": true,
      "freezePrototype": false
    },
    "updater": {
      "active": false
    },
    "windows": [
      {
        "fullscreen": false,
        "height": 800,
        "resizable": true,
        "title": "USER ENTRY",
        "width": 920
      }
    ]
  }
}
this is my tauri.config.json
```

### Additional context

![image](https://github.com/tauri-apps/tauri/assets/142501301/44a300a5-5aa6-421a-b11d-0f71da21130a)

**Comment by FabianLars** [comment]
Can you try adding one of those to your package.json file to make pkg include the sqlite files?

The generic one (probably won't work):
```json
"pkg": {
    "assets": ["node_modules/sqlite3/lib/bindings"]
}
```
The specific one (may be different per OS, or package manager, but this is what it looked like for me on windows):
```json
"pkg": {
    "assets": ["node_modules/sqlite3/build/Release/node_sqlite3.node"]
}
```

**Comment by abhijitpatil181171** [comment]
i have added "pkg": {
    "assets": ["node_modules/sqlite3/build/Release/node_sqlite3.node"]
}
in my backend code but if you closely look at file path in terminal it is looking for sqlite it is starting my C:/..... but my backend project is in D directory and tauri and backend is in samedirectory  i have attached image of same

![image](https://github.com/tauri-apps/tauri/assets/142501301/9b2e9fc8-90ca-4333-9621-33ffc9157055)

**Comment by abhijitpatil181171** [comment]
yes it is solved i have to copy node_modules/sqlite3/build/Release/node_sqlite3.node along with binary
