### ISSUE TITLE
backend exe still running in background 

### ISSUE THREAD

**Issue by abhijitpatil181171** [tauri-apps/tauri#8572]
### Describe the bug

i have added node backend exe as sidecar .when build and run tauri exe backend is connecting with frontend and its just working fine but when i close exe backend still running in background thats why when i open exe it is starting backend again on same port so it is getting issue. i have added my main.rs code below

### Expected behavior

backend exe process should be kill when we close tauri exe

### Full `tauri info` output

```text
this is my main.rs code
use tauri::{
    api::process::{Command, CommandEvent},
    Manager,
  };

  fn main() {
    tauri::Builder::default()
    .setup(|app| {
    let window = app.get_window("main").unwrap();
    tauri::async_runtime::spawn(async move {
      // `new_sidecar()` expects just filename, NOT whole path like JavaScript
      let (mut rx, mut child) = Command::new_sidecar("node-sqlite-backend")
      .expect("failed to create `my-sidecar` binary command")
      .spawn()
      .expect("Failed to spawn sidecar");

      while let Some(event) = rx.recv().await {
        if let CommandEvent::Stdout(line) = event {
          println!("Stdout: {}", line);
          window
            .emit("message", Some(format!("'{}'", line)))
            .expect("failed to emit event");
          // write to stdin
          child.write("message from Rust\n".as_bytes()).unwrap();
        }
      }
    });
      Ok(())
    })
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
  }
```

**Comment by FabianLars** [comment]
1) Please add the output of `tauri info` as required by the issue template.
2) How exactly are you closing the app? Clicking on the `x`/close button of the native window controls? Or via app.exit()?
3) As a starting point, if your sidecar spawns multiple processes, you may have to do something like this https://github.com/tauri-apps/tauri/discussions/3273#discussioncomment-3429376

**Comment by abhijitpatil181171** [comment]
working thank you
