### ISSUE TITLE
please add child window support for linux platform [feat] 

### ISSUE THREAD

**Issue by ggslayer** [tauri-apps/tauri#8587]
### Describe the problem

Hi, In current 2.0 alpha, mac and windows have child window feature, which is important for my app,  but in linux, there is no the chlid window support,  please add it, thanks.

### Describe the solution you'd like

Add child window feature for linux

**Comment by amrbashir** [comment]
Can you explain your use-case of child windows? just want to know if the available GTK APIs match your needs

**Comment by FabianLars** [comment]
Just a bit more context, i asked them to open this issue because it looked like tao already has an api for this (that transient_for thingy) which we just didn't expose yet. Was this incorrect? Also, are there other gtk apis besides that one like on windows which has multiple too?

**Comment by amrbashir** [comment]
I am thinking about maybe providing a single `.parent` child (while keeping the platform-specifc ones as well) similar to electron's parent property so knowing about the use-case will make it more clearer what direction we should head into.

**Comment by ggslayer** [comment]
Hi, in the tauri 2.0 source tree, there is a example called "parent-window", some code in that like this:
```
#[command]
async fn create_child_window(id: String, window: Window) {
  let child = WindowBuilder::new(&window, id, WindowUrl::default())
    .title("Child")
    .inner_size(400.0, 300.0);

  #[cfg(target_os = "macos")]
  let child = child.parent_window(window.ns_window().unwrap());
  #[cfg(windows)]
  let child = child.parent_window(window.hwnd().unwrap());

  child.build().unwrap();
}
```

Here have  macos and windows support, but no linux, I searched the source code of tauri, in linux impl, no parent_window method indeedly.  I think what I want is the equivalent of here's parent_window method.

with the child-parent relation, I want the child window have importent features:
1. the "child window"'s position is fixed in it's parent, can't move everywhere, unless I reset the position.
2. child window not show in system's taskbar

as discussed here: https://github.com/tauri-apps/tauri/discussions/8574

thank you @amrbashir
