### ISSUE TITLE
how to hide backend exe sidecar terminal

### ISSUE THREAD

**Issue by abhijitpatil181171** [tauri-apps/tauri#8591]
### Describe the bug

i am opening my backend exe as sidecar . when i run tauri app backend exe is running but how to run it silently so that termial will be always hide it will run in background

### Expected behavior

sidecar terminal should run silently.it should not be visible to user

### Full `tauri info` output

```text
this is my code my main.rs code to run exe as sidecar 
use tauri::{
  api::process::{Command, CommandEvent},
  Manager,
};

fn main() {
  tauri::Builder::default()
  .setup(|app| {
  let window = app.get_window("main").unwrap();
  tauri::async_runtime::spawn(async move {
    // `new_sidecar()` expects just filename, NOT whole path like JavaScript
    let (mut rx, mut child) = Command::new_sidecar("node-sqlite-backend")
    .expect("failed to create `my-sidecar` binary command")
    .spawn()
    .expect("Failed to spawn sidecar");

    

    while let Some(event) = rx.recv().await {
      if let CommandEvent::Stdout(line) = event {
        println!("Stdout: {}", line);
        window
          .emit("message", Some(format!("'{}'", line)))
          .expect("failed to emit event");
        // write to stdin
        child.write("message from Rust\n".as_bytes()).unwrap();
      }
    }
  });
    Ok(())
  })
  .run(tauri::generate_context!())
  .expect("error while running tauri application");
}
```

**Comment by FabianLars** [comment]
Hi, please include the full output of the `tauri info` command as required by the issue template.

If you're on windows, tauri does hide the terminal by default (it uses the `CREATE_NO_WINDOW` flag) so if it still shows up it, as far as i know, should mean that the sidecar itself did something like calling `AttachConsole()` itself which means it has to be fixed in the sidecar code.

**Comment by abhijitpatil181171** [comment]
thank you its working
