### ISSUE TITLE
error: linking with `cc` failed

### ISSUE THREAD

**Issue by mateusfg7** [tauri-apps/tauri#8594]
### Discussed in https://github.com/tauri-apps/tauri/discussions/8573

<div type='discussions-op-text'>

<sup>Originally posted by **mateusfg7** January  9, 2024</sup>
I just start a new project using this guide: https://tauri.app/v1/guides/getting-started/setup/sveltekit#create-the-frontend.

Setup all steps from this guide but when I try to run `pnpm tauri dev` I got this error:

https://gist.github.com/mateusfg7/e69c4db96d7fd3ed32a092f63c1487da

**Package Manager**: PNPM 8.8.0
**Rust**: rustc 1.75.0 (82e1608df 2023-12-21)
**Svelte**: 5.0.0-next31
**Typescript**: 5.3.3
**SO**: Manjaro Linux x86_64
**Kernel**: 6.1.64-1-MANJARO
**DE**: GNOME 45.1

I got the same error when trying to start the app from `pnpm create tauri-app` generated app.

**Svelte**: 4.2.8

The error persist with a React app generated with `pnpm create tauri-app`.

Looks like the error is related with a missing lib.</div>

**Comment by vonPB** [comment]
@mateusfg7 did you follow the [Prerequisites](https://tauri.app/v1/guides/getting-started/prerequisites#setting-up-linux)?

**Comment by naman-crabnebula** [comment]
Hi @mateusfg7 ,

It is working fine here, on Arch Linux. Maybe using `Svelte: 5.0.0-next31` might be issue. 

I assume that you have default `rustup` installed and `pnpm` installed from pacman itself.

Anyways, I recorded a video. Have a look

https://www.youtube.com/watch?v=hes91tVFQVQ

And Don't use experimental stuff.

If you still have any issue at any point in video, please feel free to reach out.

**Comment by mateusfg7** [comment]
Hi @naman-crabnebula,

As mentioned, I've tried it with **Svelte 4.2.8** (_last stable release as of today_), and with **React**. The error persists in both frameworks.

I followed the entire step-by-step instructions described here: https://tauri.app/v1/guides/getting-started/setup/sveltekit. With the same steps as in the video, the error persists.

My **pnpm** was installed using the command `npm i -g pnpm`, which in turn comes from the [asdf-node](https://github.com/asdf-vm/asdf-nodejs) plugin:

```console
➜ where pnpm  
/home/mateusfg7/.asdf/shims/pnpm

➜ pnpm --version
8.8.0

➜ node --version
v20.5.0

➜ rustup --version
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.75.0 (82e1608df 2023-12-21)`

➜ where rustup                                             
/home/mateusfg7/.cargo/bin/rustup
/usr/bin/rustup
```

The **rustup** was installed using this command:
```console
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```
From the [rust install guide](https://www.rust-lang.org/tools/install)

**Comment by naman-crabnebula** [comment]
> note: /usr/bin/ld: warning: libicui18n.so.74, needed by /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib/libwebkit2gtk-4.0.so, not found (try using -rpath or -rpath-link)

You did install [Tauri Prerequisites](https://tauri.app/v1/guides/getting-started/prerequisites) , right?

If not, run 

```
sudo pacman -Syu
sudo pacman -S --needed \
    webkit2gtk \
    base-devel \
    curl \
    wget \
    file \
    openssl \
    appmenu-gtk-module \
    gtk3 \
    libappindicator-gtk3 \
    librsvg \
    libvips
```

**Comment by mateusfg7** [comment]
A simple upgrade with `sudo pacman -Syu` solved my problem 😅

Thanks!

**Comment by naman-crabnebula** [comment]
Glad to hear that.

Have a good day!
