### ISSUE TITLE
[feat] Set updater headers via JavaScript bindings

### ISSUE THREAD

**Issue by leonbeon** [tauri-apps/tauri#8597]
### Describe the problem

I'm using the updater feature to update my app. Since the endpoint is protected by HTTP Basic Auth, I followed some suggestions (e.g. #3896, #4619) to set my required headeres in the rust main function. My code for that looks like this, mostly adapted from the [rust docs](https://docs.rs/tauri/latest/tauri/updater/struct.UpdateBuilder.html#examples-2):

```rust
fn main() {
    tauri::Builder::default()
        .setup(|app| {
            let handle = app.handle();

            tauri::async_runtime::spawn(async move {
                match handle
                    .updater()
                    .header("Authorization", "Basic [...]")
                    .await
                {
                    Ok(update) => {
                        let _ = update.download_and_install().await;
                    }
                    Err(e) => {
                        println!("Error: {}", e)
                    }
                }
            });

            Ok(())
        })
        .plugin(tauri_plugin_store::Builder::default().build())
        .plugin(tauri_plugin_persisted_scope::init())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

This is working great -- the header gehts applied not only to the endpoint defined in the updater config (the one that fetches the remote json), but also to the url specified in that json for the update bundle itself (I host it on the same server).

The problem is that with this code, the prompt to update is skipped completely and the app just updates automatically. The documentation [provides a way to show a custom prompt](https://tauri.app/v1/guides/distribution/updater/#custom-dialog), but the JavaScript bindings don't expose this added HTTP header functionality. It may be possible via Rust, but I'm not familiar enough with it. I also want to the user be able to manually trigger an update check, so there would have to be some way to call the updater via JavasScript (with headers).

### Describe the solution you'd like

Ideally there would either be
- a way for JavaScript bindings to add headers to update requests, e.g. updating `checkUpdate()` to take HTTP headers
or
- documentation on how to write an update function in Rust that is not only running on start up and how to trigger that function from JavaScript. I know that the documentation links to the [rust docs](https://docs.rs/tauri/latest/tauri/updater/index.html) for this, but I think a short snippet on how to actually achieve this would benefit everyone who doesn't know Rust greatly. In that case, this would be more of a docs enhancement request, I guess.

### Alternatives considered

- Removing auth from the http endpoint (really don't want to do this)

**Comment by amrbashir** [comment]
Unfortunately, due to the way `checkUpdate` was implemented in 1.x version, there is no way to pass options to the updater without too much refactors or breaking changes.

In v2, with the updater plugin, there is no automatic update dialog but you get more control over the updating process and you can still show a native dialog if you wish, which is fairly simple.

A workaround for your use-case in 1.x, would be to spawn a native dialog similar to how we do it internally:

```rs

tauri::Builder::default()
        .setup(|app| {
            let handle = app.handle();

            tauri::async_runtime::spawn(async move {
                match handle
                    .updater()
                    .header("Authorization", "Basic [...]")
                    .unwrap()
                    .check()
                    .await
                {
                    Ok(update) => {
                        use tauri::api::dialog::blocking::ask;

                        let maybe_main_window = handle.get_window("main");

                        let app_name = &handle.package_info().name;

                        let should_install = ask(
                            maybe_main_window.as_ref(),
                            format!(r#"A new version of {app_name} is available! "#),
                            format!(r#"{app_name} {latest_version } is now available -- you have {current_version}.

                        Would you like to install it now?

                        Release Notes:
                        {body}"#,
                                body = update.body().map(|b| b.as_str()).unwrap_or_default(),
                                latest_version = update.latest_version(),
                                current_version=  update.current_version()
                            ),
                        );

                        if should_install {
                            let _ = update.download_and_install().await;
                        }
                    }
                    Err(e) => {
                        println!("Error: {}", e)
                    }
                }
            });

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
```

**Comment by leonbeon** [comment]
It works great, thanks! However (at least on MacOS, I have yet to test in on Windows) it seems to update regardless of selecting yes or no, but maybe that is because of my implementation.

Also, for anyone else reading this, I had to add `use tauri::Manager;` to the start of the file.

**Comment by amrbashir** [comment]
> it seems to update regardless of selecting yes or no

might be a bug in our APIs, can you check the return value of `ask()`

**Comment by leonbeon** [comment]
It was my fault, I had a debug call to `if (shouldUpate) await installUpdate();` from the JS side on start up. Not too sure how that worked, since calling the same function manually doesn't trigger an update. But it correctly denies the update now when you click "No". Thanks!
