### ISSUE TITLE
linux  executable resources does not exist

### ISSUE THREAD

**Issue by qwe104** [tauri-apps/tauri#8603]
### Describe the bug

tauri correctly configures resources in linux environment and uses compiled executable file after packaging, which indicates that resources does not exist and the resources obtained by running with compiled deb package is normal.

### Full `tauri info` output

```text
Environment
    - OS: Ubuntu 20.04 X64
    ✔ webkit2gtk-4.0: 2.38.6
    ✔ rsvg2: 2.48.9
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ Cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 18.16.0
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 1.5.1
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.4
    - @tauri-apps/api [NPM]: 1.3.0 (outdated, latest: 1.5.3)
    - @tauri-apps/cli [NPM]: 1.3.0 (outdated, latest: 1.5.9)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1440/
    - framework: Vue.js
    - bundler: Rollup
```

**Comment by FabianLars** [comment]
Do you mean the actual executable binary in `target/release/` ? Because tauri's resources feature only works with bundles/installer like .deb .appimage .rpm (v2) since they are _not_ inside the binary itself.

If that's not what you mean, please try to explain it some more and maybe show some errors you're seeing :)

**Comment by qwe104** [comment]
> Do you mean the actual executable binary in `target/release/` ? Because tauri's resources feature only works with bundles/installer like .deb .appimage .rpm (v2) since they are _not_ inside the binary itself.
> 
> If that's not what you mean, please try to explain it some more and maybe show some errors you're seeing :)

Thank you for your reply. I now have a shell script, is there a way to use an executable that can also be called through the shell api  (https://tauri.app/v1/api/js/shell) provided by js

**Comment by FabianLars** [comment]
I think you can just use `sh` as the command binary and the shell script as an argument

**Comment by qwe104** [comment]
> I think you can just use `sh` as the command binary and the shell script as an argument
Thank you for your reply. I tried using your suggestion, but it gave me an error. The shell script is at the same level as tauri.config.json
![20240117104001](https://github.com/tauri-apps/tauri/assets/23718186/effadc3b-06cd-4dcd-ae65-1d94116710cb)

**Comment by qwe104** [comment]
![_20240117104015.png…]()

**Comment by qwe104** [comment]
![20240117104015](https://github.com/tauri-apps/tauri/assets/23718186/6dd9eed8-b826-4beb-b1ff-ca7f7edc1282)

**Comment by FabianLars** [comment]
Yeah, you'll need to provide an absolute path then. The current working dir (the location `./` resolves to) is not the same as the script location.

If you are using the plain binary, and not the deb or appimage with the resource featuer you'll also have to include it inside the binary somehow for example via https://doc.rust-lang.org/std/macro.include_str.html / https://doc.rust-lang.org/core/macro.include_bytes.html Then you can write it to disk before you need it.
