### ISSUE TITLE
[feat] ANSI ESC Codes support

### ISSUE THREAD

**Issue by realtica** [tauri-apps/tauri#8605]
### Describe the problem

Currently the Webview do not support ANSI ESC Codes:
![image](https://github.com/tauri-apps/tauri/assets/852446/08a6f87f-a220-4ac0-92c3-520756bcdd61)

### Describe the solution you'd like

How can enable it?

**Comment by FabianLars** [comment]
This is not something we have any control over. Browsers simply do not support asci and afaik there is no work being done in the browser engines to enable it.
Years back there were projects like https://github.com/atdt/escapes.js/ but i don't know of anything that's still maintained.
