### ISSUE TITLE
increasing tauri app when add backend binary as sidecar

### ISSUE THREAD

**Issue by abhijitpatil181171** [tauri-apps/tauri#8614]
### Describe the bug

when i add backend node binary as sidecar it is taking binary size as it is in installer .resulting when i install the app its size is increasing.is there any way to reduce this increased size.

### Expected behavior

app size should not be increased

### Full `tauri info` output

```text
{
  "$schema": "../node_modules/@tauri-apps/cli/schema.json",
  "build": {
    "beforeBuildCommand": "npm run build",
    "beforeDevCommand": "cross-env BROWSER=none npm run start",
    "devPath": "http://localhost:3000",
    "distDir": "../build"
  },
  "package": {
    "productName": "json-test",
    "version": "0.1.0"
  },
  "tauri": {
    "allowlist": {
      "all": false,
      "shell": {
        "sidecar": true,
        "scope": [{ "name": "bin", "sidecar": true }]
      }
    },
    "bundle": {
      "active": true,
      "category": "DeveloperTool",
      "copyright": "",
      "deb": {
        "depends": []
      },
      "externalBin": ["bin/node-sqlite-backend"],
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "identifier": "xyz.com",
      "longDescription": "",
      "macOS": {
        "entitlements": null,
        "exceptionDomain": "",
        "frameworks": [],
        "providerShortName": null,
        "signingIdentity": null
      },
      "resources": { "bin/node_sqlite3.node": "./" },
      "shortDescription": "",
      "targets": "all",
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "security": {
      "dangerousDisableAssetCspModification": false,
      "dangerousRemoteDomainIpcAccess": [],
      "dangerousUseHttpScheme": true,
      "freezePrototype": false
    },
    "updater": {
      "active": false
    },
    "windows": [
      {
        "fullscreen": false,
        "height": 600,
        "resizable": true,
        "title": "json-test",
        "width": 800
      }
    ]
  }
}

```

**Comment by naman-crabnebula** [comment]
Hi @abhijitpatil181171 ,

1. It is not a bug, it is intended behaviour. Binary are already compiled files, as the name suggests. Hence, its size can not be reduced. ( unless you compress it )
2. Why are you using sidecar? It should be added as a dependency instead. Sidecars have a lot of downsides, for example, you will have difficulty updating them. And as you mentioned above, they might have huge size.

Also, is your previous issue https://github.com/tauri-apps/tauri/issues/8564 solved?

**Comment by abhijitpatil181171** [comment]
i have to run that backend binary when we start our app thats why i am adding it as sidecar and also how should we add as dependancy and run it

**Comment by amrbashir** [comment]
As explained by @naman-crabnebula, this is expected behavior when you embed a sidecar like `node` which is around `48mb` if not bigger.

@abhijitpatil181171 we appreciate your issues, but lately I have noticed most of your issues are not actually bugs or feature requests, so please use discussions if you need help with something and keep issues strictly to bugs/features. You could also join our discord to get help from us directly and the community.

**Comment by abhijitpatil181171** [comment]
okay thank you i will surely use discord
