### ISSUE TITLE
Error failed to bundle project: error running candle.exe

### ISSUE THREAD

**Issue by ManucherKM** [tauri-apps/tauri#8625]
### Describe the bug

Hello. I recently started learning Tauri and ran into a problem. I created a project with "npm create tauri-app@latest" , but for some unknown reason Tauri does not build the project. Here are the logs:

   ```
Compiling tauri-app v0.0.0 (C:\Users\xxx\Desktop\test\src-tauri)
    Finished release [optimized] target(s) in 10.36s
        Info Target: x64
     Running candle for "main.wxs"
       Error failed to bundle project: error running candle.exe
```

### Reproduction

GitHub: https://github.com/ManucherKM/tauribuilderror

### Expected behavior

Tauri is building the project.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 120.0.2210.133
    ✔ MSVC: 
        - Visual Studio Build Tools 2022
        - Visual Studio Community 2022
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.11.0
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 1.5.4
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.6
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.9

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Hi, could you please re-run the build command with the verbose flag and post the new logs?
```
npm run tauri build -- --verbose
```

**Comment by FabianLars** [comment]
ah actually no need, i think WiX doesn't like your productName https://github.com/ManucherKM/tauribuilderror/blob/master/src-tauri/tauri.conf.json#L9 - try an actual name instead of a simple dot.

**Comment by ManucherKM** [comment]
Thank you, it worked for me. It looks like I was trying to name the project according to the directory name by specifying a point when creating the Tauri project, but Tauri didn't understand it.
