### ISSUE TITLE
A window with decorations can't be transparent initially until resized

### ISSUE THREAD

**Issue by ThisSeanZhang** [tauri-apps/tauri#8632]
**Describe the bug**
Create *transparent window* in win10,start app background still white, But maximize the window extra part can transparent .
When resize cover the white space，Area becomes transparent.

**To Reproduce**

**Expected behavior**

**Screenshots**

![transparent](https://user-images.githubusercontent.com/46880100/118687018-23e73880-b837-11eb-8520-4375f9448b5c.gif)

**Platform and Versions (please complete the following information):**

Operating System - Windows, version 10.0.19042 X64
Webview2 - 90.0.818.62

Node.js environment
  Node.js - 14.17.0
  @tauri-apps/cli - 1.0.0-beta.1
  @tauri-apps/api - 1.0.0-beta.1

Global packages
  npm - 6.14.13
  yarn - 1.22.10

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
  /.git
  /node_modules
  /public
  /src
  /src-tauri

App
  tauri.rs - 1.0.0-beta.1
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' img-src: 'self'
  distDir - Set automatically by Vue CLI plugin
  devPath - Set automatically by Vue CLI plugin
  framework - Vue.js (Vue CLI)
  bundler - Webpack

**Additional context**

**Stack Trace**

**Comment by amrbashir** [comment]
I poked around and found out: 
- Transparent on electron only works when used in a frameless window, Regular windows cannot be transparent, probably they are using the same api as us.
- We could draw to the window like glutin [transparent](https://github.com/rust-windowing/glutin/blob/cfda993f2700e2cd002160d4f14a3af0ecaae3fb/glutin_examples/examples/transparent.rs) example but with decorations on.

TBH, I am tempted to close this issue and recommend to always use transparent with decorations off but I will keep this open for now.

**Comment by Ripwords** [comment]
Just found a workaround, set your decorations to false in tauri.conf, then when your app is loaded use the Javascript API to reset it to true. Worked for me

**Comment by amrbashir** [comment]
With the newly added [`with_undecorated_shadow`](https://docs.rs/tao/latest/i686-pc-windows-msvc/tao/window/struct.WindowBuilder.html#method.with_undecorated_shadow) for Windows and is planned to be active by default in tauri v2, this bug will also affect undecorated window as well. 

If you still want the shadows with undecorated, the same workaround will work, i.e. start your window undecorated without shadow then enable the shadows back again after the window has been created.

**Comment by realLevTheDev** [comment]
Adding to this issue because I am not sure if this is documented anywhere. Maybe I am doing something incorrectly. 

When I have:

"windows": [
      {
        "title": "test",
        "transparent": true,
        "decorations": false,
        "maximized": true,
        "fullscreen": false,
        "alwaysOnTop": true,
        "skipTaskbar": false
      }
    ]

The window will load maximized but it will not be transparent until you toggle maximize on and off. If you "maximized": false it will work but you have to use JavaScript to maximize it so there is a delay and the window does not truly open maximized.

**Comment by ThisSeanZhang** [comment]
🎉🎉🎉 Thanks You ! ! !
