### ISSUE TITLE
[docs] Tauri command should not have parameter that contains an underscore

### ISSUE THREAD

**Issue by prisme60** [tauri-apps/tauri#8660]
I lost one day to finally understand that **parameters of Tauri Command** should not contain an underscore inside the name.

I think you should explain this constraint (or fix the problem if it is a bug ?).

I am using Tauri (Rust) + Leptos (Rust).

# NOT WORKING with underscore inside the name parameter

## src/
```rust
#[derive(Serialize, Deserialize)]
struct TxDataArgs<'a> {
    tx_data: &'a [u8], // <---- parameter WITH underscore
}

//...

#[component]
pub fn App() -> impl IntoView {
    let (tx_data, set_tx_data) = create_signal(None::<Vec::<u8>>);
    let (tx_data_msg, set_tx_data_msg) = create_signal(String::new());

    let submit_tx_data = move |ev: SubmitEvent| {
        ev.prevent_default();
        spawn_local(async move {
            let tx_data = tx_data.get_untracked();
            if tx_data.is_none() {
                return;
            }

            let args = to_value(&TxDataArgs { tx_data: tx_data.as_ref().unwrap() }).expect("Not valid TxDataArgs");
            log!("args={:?}", &args);
            // Learn more about Tauri commands at https://tauri.app/v1/guides/features/command
            let new_msg = invoke("txdata_cmd", args).await.as_string().expect("Invoke problem on txdata command");
            log!("Invoke done");
            set_tx_data_msg.set(new_msg);
        });
    };
 // View declaration
}
```

## src-tauri/
```rust
#[tauri::command]
fn txdata_cmd(tx_data: Vec<u8>) -> String {
    info!("Call txdata = {:?}", &tx_data);
    if tx_data.len() > 0 {
        format!("tx_data={:?}", &tx_data)
    } else {
        format!("tx_data=X")
    }
}
```
As you can see on the following picture, the javascript serialisation to JSON is OK. I can see the parameter with the underscore, but invoke is failing.
![image](https://github.com/tauri-apps/tauri/assets/1153403/c243ff88-b7da-4f96-ae90-5cd7ba2ac71e)

# OK without the underscore in the name parameter

## src/
```rust
#[derive(Serialize, Deserialize)]
struct TxDataArgs<'a> {
    txdata: &'a [u8], // <---- parameter WITHOUT underscore
}

//...

#[component]
pub fn App() -> impl IntoView {
    let (tx_data, set_tx_data) = create_signal(None::<Vec::<u8>>);
    let (tx_data_msg, set_tx_data_msg) = create_signal(String::new());

    let submit_tx_data = move |ev: SubmitEvent| {
        ev.prevent_default();
        spawn_local(async move {
            let tx_data = tx_data.get_untracked();
            if tx_data.is_none() {
                return;
            }

            let args = to_value(&TxDataArgs { txdata: tx_data.as_ref().unwrap() }).expect("Not valid TxDataArgs");
            log!("args={:?}", &args);
            // Learn more about Tauri commands at https://tauri.app/v1/guides/features/command
            let new_msg = invoke("txdata_cmd", args).await.as_string().expect("Invoke problem on txdata command");
            log!("Invoke done");
            set_tx_data_msg.set(new_msg);
        });
    };
 // View declaration
}
```

## src-tauri/
```rust
#[tauri::command]
fn txdata_cmd(txdata: Vec<u8>) -> String {
    info!("Call txdata = {:?}", &txdata);
    if txdata.len() > 0 {
        format!("tx_data={:?}", &txdata)
    } else {
        format!("tx_data=X")
    }
}
```

As you can see on the following picture, the javascript serialisation to JSON is OK. I can see the parameter WITHOUT the underscore, and NOW invoke is OK.
![image](https://github.com/tauri-apps/tauri/assets/1153403/48b4a407-59cd-434d-a5cc-a3c446f0e8dd)

**Comment by FabianLars** [comment]
It's not as prominently documented as it should (and will be in the new docs) but it's mentioned here: https://tauri.app/v1/guides/features/command#passing-arguments
![grafik](https://github.com/tauri-apps/tauri/assets/30730186/41f344d8-2752-4f4c-9ed4-11b787017db8)
This still applies for wasm/rust frontend frameworks, though then it probably makes sense to disable the conversion by changing `#[tauri::command]` to ``#[tauri::command(rename_all = "snake_case")]`

**Comment by prisme60** [comment]
Sorry, I'm not English native (I am French). It seems that I skip this sentence, when I read the documentation.

> Arguments should be passed as a JSON object with camelCase keys:

At first view, "should" sounds like an advice, but in fact it is mandatory if we don't use the `rename_all` directive.

I reread the whole paragraph and I feel like an idiot (RTFM).
Thank you for your fast answer to my issue.

**Comment by FabianLars** [comment]
Yeah, you're right. This is totally our fault and i agree that the docs are poorly worded here. We try our best to address issues like these in the new docs (coming with tauri v2).
