### ISSUE TITLE
Tauri Overwriting Fluent UI Dialog Component [bug] 

### ISSUE THREAD

**Issue by anandhuremanan** [tauri-apps/tauri#8695]
### Describe the bug

Hello,

I'm using the [Fluent UI](https://react.fluentui.dev/?path=/docs/components-dialog--default) dialog component in my project. When I added the component, Tauri complained about not allowing listing the dialog, so I added it to the allow list. However, the rendered dialog appeared weird and only shows a text `called`. 

![image](https://github.com/tauri-apps/tauri/assets/48993261/9e09e02c-4a07-4859-8608-3ec9a78107dc)
_Figure Rendered Dialog_

My Code:

1. Triggering the Dialog

```
<DialogTrigger disableButtonEnhancement>
              <Button onClick={handleDelete}>
                <Icon path={mdiDelete} size={0.8} />
                Delete
              </Button>
</DialogTrigger>
```

2.  Dialog

```
<Dialog>
        <DialogSurface>
          <DialogBody>
            <DialogTitle>Dialog title</DialogTitle>
            <DialogContent>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam
              exercitationem cumque repellendus eaque est dolor eius expedita
              nulla ullam? Tenetur reprehenderit aut voluptatum impedit
              voluptates in natus iure cumque eaque?
            </DialogContent>
            <DialogActions>
              <DialogTrigger disableButtonEnhancement>
                <Button appearance="secondary">Close</Button>
              </DialogTrigger>
              <Button appearance="primary">Do Something</Button>
            </DialogActions>
          </DialogBody>
        </DialogSurface>
</Dialog>
```

3. Added dialog in `allowlist` otherwise the component won't render

```
"dialog": {
        "all": true
      },
```

Fluent UI React Components v9.46.1

### Reproduction

This can be reproduced by adding Fluent UI Dialog In Tauri App.

### Expected behavior

Should render the dialog box from [Fluent UI Dialog](https://react.fluentui.dev/?path=/docs/components-dialog--default)

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 120.0.2210.144
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.72.0-nightly (36fb58e43 2023-06-26)
    ✔ cargo: 1.72.0-nightly (03bc66b55 2023-06-23)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: nightly-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.18.0
    - pnpm: 8.12.1
    - yarn: 1.22.21
    - npm: 9.8.1

[-] Packages
    - tauri [RUST]: 1.5.4      
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.6
    - tauri-cli [RUST]: 1.5.9
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.9

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../out
    - devPath: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Webpack
```

**Comment by FabianLars** [comment]
I don't see why/how it would call tauri's dialog api here. Seems like Fluent UI Dialog is a fully html/js solution that doesn't interact with the os dialog apis. Could you try to upload a (full) minmal reproduction project to github for us?

**Comment by ananduremanan** [comment]
> I don't see why/how it would call tauri's dialog api here. Seems like Fluent UI Dialog is a fully html/js solution that doesn't interact with the os dialog apis. Could you try to upload a (full) minmal reproduction project to github for us?

Sure, here is a [Link]( https://github.com/ananduremanan/win-app-noteapp) to a test app I've made..

**Comment by anandhuremanan** [comment]
Sorry, it was my mistake!! I added an alert in the function which causes this. Thanks For Your Reply..
