### ISSUE TITLE
[bug] `alwaysOnTop` issue with linux and fullscreen apps

### ISSUE THREAD

**Issue by Hacksore** [tauri-apps/tauri#8700]
### Describe the bug

A user reported that Overlayed would not stay on top of borderless windowed/fullscreen apps.

### Reproduction

1. checkout `git clone https://github.com/Hacksore/always-ontop-linux.git`
2. `pnpm i`
3. `pnpm tauri dev`
4. Open an application that's borderless windowed/fullscreen

### Expected behavior

The app should always remain on top.

### Full `tauri info` output

```text
✘] Environment
    - OS: Ubuntu 22.04 X64
    ✔ webkit2gtk-4.0: 2.42.4
    ✘ rsvg2: not installed - **Note** - *Says not installed*
      Visit https://tauri.app/v1/guides/getting-started/prerequisites to learn more about tauri prerequisites
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 16.14.2
    - pnpm: 8.15.0
    - npm: 8.5.0

[-] Packages
    - tauri [RUST]: 1.5.4
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.7
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.9

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Additional context

Video below of the issue from the users linux system. Also the users env info:
- Distribution Ubuntu: 22.04 LTS
- Desktop Environment Version: Unity 7

https://github.com/tauri-apps/tauri/assets/996134/764df3ae-65c7-4a89-b95c-68c7c708b180

**Comment by naman-crabnebula** [comment]
Hi @Hacksore ,

I can't reproduce this issue on the latest cinnamon. I am using Arch Linux and my system info is

> Kernel: 6.7.2-zen1-2-zen arch: x86_64 bits: 64 compiler: gcc v: 13.2.1
> Desktop: Cinnamon v: 6.0.4 tk: GTK v: 3.24.41 wm: muffin vt: 7 dm: LightDM

I tested it on steam as well as google chrome. I am also attaching a video.

https://github.com/tauri-apps/tauri/assets/155433377/d1e79e3b-a33d-4d8e-af3b-4bddf9168f95

This is most likely due to outdated desktop environment/window manager/unity thing. Can you please share exact system info? ( inxi -Fxxxza would be appreciated )

**Comment by Hacksore** [comment]
@naman-crabnebula what happens if you launch a game in either native full screen or borderless windowed fullscreen?

Since I don't run linux I'm really not much help here 🤣.

**Comment by naman-crabnebula** [comment]
Hi @Hacksore , sorry for the late response. Actually, I don't play much games currently, so I had to download CS2 ( 40GB+ ) for this test.

And yeah, there is no issue with CS2 as well.

I am attaching the video for reference.

https://github.com/tauri-apps/tauri/assets/155433377/e78ff6f0-7b38-4bfe-b15c-1634810f6316

**Comment by Hacksore** [comment]
@naman-crabnebula yeah I guess it must be a unity issue, maybe it needs to be raised there instead?

**Comment by naman-crabnebula** [comment]
Yeah, and maybe ask the user to first test non-tauri apps with unity as well. Most probably, this issue will occur with them as well.

Thank You

**Comment by Hacksore** [comment]
Closing for now as a Ubuntu Unity issue, if more insight is found will raise a new issue.
