### ISSUE TITLE
[bug] path not allowed on the configured scope

### ISSUE THREAD

**Issue by czf0613** [tauri-apps/tauri#8701]
### Describe the bug

I am trying to read a binary file in js, using the fs module
I have already configured the path, which is ~/.OD/**
![2](https://github.com/tauri-apps/tauri/assets/46845934/e54c9f9f-b063-401b-aa8b-3de7c28b2e90)

But it shows an error while reading file inside this directory:
![1](https://github.com/tauri-apps/tauri/assets/46845934/98f3c0eb-e71a-4aa3-8b00-e572e0f51cec)

It does not allow me to read the file at ~/.OD/.tmpfs/00.bin, but this file is actually inside this configured scope? What's wrong with my configuration? It there a bug in fs module?

### Full `tauri info` output

```text
[✔] Environment
    - OS: Debian 12 X64
    ✔ webkit2gtk-4.0: 2.42.4
    ✔ rsvg2: 2.54.7
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 18.18.0
    - yarn: 1.22.21
    - npm: 9.8.1

[-] Packages
    - tauri [RUST]: 1.5.4
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.1
    - @tauri-apps/cli [NPM]: 1.5.6

[-] App
    - build-type: bundle
    - CSP: default-src 'self'; img-src 'self' asset: https://asset.localhost
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Try playing with this config: https://tauri.app/v1/api/config/#fsallowlistscope.requireliteralleadingdot looks like .tmpfs hits that

**Comment by czf0613** [comment]
You're right. Thanks a million
