### ISSUE TITLE
[feat] Allow using the js fetch api to load the asset url

### ISSUE THREAD

**Issue by czf0613** [tauri-apps/tauri#8702]
### Describe the problem

I am using a canvas lib to draw some RAW images. But this lib uses the js fetch API to load the URL to my RAW file.
I have tried the `convertFileSrc` method to convert my file url to the asset url. But it does not work at all.

![3](https://github.com/tauri-apps/tauri/assets/46845934/2bffafe5-2bbc-4cf6-92bd-06afdde28127)

I have add the file directory into the assetScope so this problem is not caused by the permissions.
![2](https://github.com/tauri-apps/tauri/assets/46845934/518c5a8e-a304-424c-9f34-bc8d172a1c68)

### Describe the solution you'd like

I guess that adding a Cors header in the asset url handler may works.
I hope that I can use the fetch API in js directly because a lot of third party libraries uses the `fetch` function to load url resources. 

### Additional context

[✔] Environment
    - OS: Debian 12 X64
    ✔ webkit2gtk-4.0: 2.42.4
    ✔ rsvg2: 2.54.7
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 18.18.0
    - yarn: 1.22.21
    - npm: 9.8.1

[-] Packages
    - tauri [RUST]: 1.5.4
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.1
    - @tauri-apps/cli [NPM]: 1.5.6

[-] App
    - build-type: bundle
    - CSP: default-src 'self' asset: https://asset.localhost; img-src 'self' asset: https://asset.localhost
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite

**Comment by FabianLars** [comment]
can you try adding the `linux-protocol-headers` flag to the tauri dependency in cargo.toml?

**Comment by czf0613** [comment]
Nice, it works.
Is there an extra work to make it compatible with Windows and macOS?

**Comment by FabianLars** [comment]
nope, they should work out of the box.
