### ISSUE TITLE
How to build a macOS app on windows 11

### ISSUE THREAD

**Issue by xrui94** [tauri-apps/tauri#8728]
### Describe the problem

I have a computer running Windows 11 that can package and build MSI and exe programs, but I don't know how to build and package a program that can run on MacOS. THere is my configuration:
```json
{
  "build": {
    "beforeDevCommand": "pnpm dev",
    "beforeBuildCommand": "pnpm build",
    "devPath": "http://localhost:1420",
    "distDir": "../dist"
  },
  "package": {
    "productName": "docViewer",
    "version": "0.0.0"
  },
  "tauri": {
    "allowlist": {
      "all": false,
      "shell": {
        "all": false,
        "open": true
      }
    },
    "bundle": {
      "active": true,
      "targets": ["msi", "aarch64-apple-darwin"],
      "identifier": "com.tauri.build",
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ]
    },
    "security": {
      "csp": null
    },
    "windows": [
      {
        "fullscreen": false,
        "resizable": true,
        "title": "myApp",
        "width": 800,
        "height": 600
      }
    ]
  }
}
```

### Describe the solution you'd like

I want to build .app or .dmp executable。

**Comment by FabianLars** [comment]
This is currently not supported and unlikely to be added in the near future (apple makes this intentionally hard 😠).

Generally though (whether or not cross platform compilation support exists) we recommend setting up CI/CD (in this case you need CI with native macos runners), first and foremost GitHub Actions which is free for open source projects. We have a few examples here https://tauri.app/v1/guides/building/cross-platform#tauri-github-action and here https://github.com/tauri-apps/tauri-action/

**Comment by xrui94** [comment]
I got it, Thank you!
