### ISSUE TITLE
[bug] infinite update with nsis on windows

### ISSUE THREAD

**Issue by thewh1teagle** [tauri-apps/tauri#8753]
### Describe the bug

I made simple repo with [guides/distribution/updater](https://tauri.app/v1/guides/distribution/updater)
And it works for `MacOS` - it asks for new update and update,
However, for windows (`nsis`) it opens dialog and asks for new update and I confirm it
and it doesn't really update the program so it opens again and asks again (and the version doesn't change I display it in main window)
[github.com/thewh1teagle/tauri-auto-updater](https://github.com/thewh1teagle/tauri-auto-updater)

### Reproduction

Download [releases/download/v0.0.3/tauri-auto-updater_0.0.3_x64-setup.exe](https://github.com/thewh1teagle/tauri-auto-updater/releases/download/v0.0.3/tauri-auto-updater_0.0.3_x64-setup.exe)
Then install and confirm the update to see the infinite update dialog 

### Expected behavior

It should update to version v0.0.4 (if I install manually it update)

### Full `tauri info` output

```console
WARNING: no lock files found, defaulting to npm

[✔] Environment
    - OS: Mac OS 14.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.19.0
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 1.5.4
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.7
    - tauri-cli [RUST]: 1.5.9
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 1.5.9

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../src
    - devPath: ../src
```

### Additional context

Everything available at [github.com/thewh1teagle/tauri-auto-updater](https://github.com/thewh1teagle/tauri-auto-updater)

**Comment by FabianLars** [comment]
The reason is that your latest.json file points to the .msi installer, not the setup.exe. They don't work interchangibly so i'd recommend to decide on one bundle type (msi or nsis) and disable the other.

**Comment by itaifish** [comment]
Why does the `latest.json` not include the link for the setup.exe?

**Comment by itaifish** [comment]
> Why does the `latest.json` not include the link for the setup.exe?

Sorry, I figured out the problem. The tauri action will only build either the MSI **OR** the NSIS:

https://github.com/tauri-apps/tauri-action/blob/dev/action.yml#L43

You gotta choose which in the settings and then only distribute that bundle
