### ISSUE TITLE
More features should be enabled during CI clippy + test

### ISSUE THREAD

**Issue by chippers** [tauri-apps/tauri#876]
**Describe the bug**
Not all possible features are enabled for crates when running `cargo clippy` or `cargo check` in the CI. We should probably enable every possible feature that is not mutually exclusive during these CI checks.

**To Reproduce**
1. Go to #850
2. See first commit that passed CI tests 974053652ce8827f748bf2a015c1238ecbebf274
3. Locally run `cargo test --workspace --exclude tauri --all-targets -all-features` (note the `--all-features`)
5. See fix in the next commit af3cf4bdbc83989ebdc02cb536ffa06c917c03c2 which passes the previous command successfully

**Expected behavior**
CI should have shown an error for step 3.

**Additional context**
We already do something similar in the clippy check here:
https://github.com/tauri-apps/tauri/blob/61fbf6837d33a38c2bf914cbd56d3284d18457d0/.github/workflows/core-lint-fmt.yml#L45
That matrix should probably remove the all-api feature and add that and `cli` feature and split the build steps into 2 parts.  1 to build each crate with mutually exclusive features (only `tauri` for now) and the 2 part testing everything else.  Basically just add another step for all crates excluding `tauri` and change the first one to only `tauri` using the matrix for the mutually exclusive features. See an example of this (in a shell script) at:
https://github.com/tauri-apps/tauri/blob/2bb6548722a1fb708ac90d9334f85773770a7268/.scripts/cargo-check.sh

We can do something similar in the test ci file, by adding another matrix for the mutually exclusive features:
https://github.com/tauri-apps/tauri/blob/61fbf6837d33a38c2bf914cbd56d3284d18457d0/.github/workflows/test-core.yml#L16-L22

This would end up testing the 2nd step of the crates without mutually exclusive features multiple times in the now 6x jobs, but is the simplest change.  We could also split the jobs for `tauri` and non mutually exclusive crates to reduce redundant checks.

I can take a look at PRing this, but not until tonight as I am busy today

**Comment by chippers** [comment]
See #874 for the scripts used to inspire this change in CI

**Comment by lucasfernog** [comment]
I'm closing this since we're not facing any issues with this anymore. Let me know if you still think we should do something :)
