### ISSUE TITLE
[bug][2.0.0-beta.0] PluginInitialization("http", "invalid type: map, expected unit")

### ISSUE THREAD

**Issue by ppbl** [tauri-apps/tauri#8769]
### Describe the bug

```json
"plugins": {
    "http": {
      "scope": [
        "http://localhost:3000/*"
      ]
    }
  }
```
Error reported after adding scope configuration to http plugin

### Expected behavior

no error

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.3.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.11.0
    - pnpm: 8.14.1
    - yarn: 1.22.21
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.2
    - tauri-build [RUST]: 2.0.0-beta.1
    - wry [RUST]: 0.35.2
    - tao [RUST]: 0.25.0
    - tauri-cli [RUST]: 2.0.0-beta.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.0
    - @tauri-apps/cli [NPM]: 2.0.0-beta.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:5173/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment]
cross linking the plugin issue: https://github.com/tauri-apps/plugins-workspace/issues/928#issuecomment-1925719547

> The old allowlist and scope configs were replaced with a permissions system: https://beta.tauri.app/guides/upgrade-migrate/from-tauri-1/#migrate-permissions. Please read through it and get back to us if you have further questions.

**Comment by savissimo** [comment]
> cross linking the plugin issue: [tauri-apps/plugins-workspace#928 (comment)](https://github.com/tauri-apps/plugins-workspace/issues/928#issuecomment-1925719547)
> 
> > The old allowlist and scope configs were replaced with a permissions system: https://beta.tauri.app/guides/upgrade-migrate/from-tauri-1/#migrate-permissions. Please read through it and get back to us if you have further questions.

The link is dead.

**Comment by FabianLars** [comment]
https://tauri.app/start/migrate/from-tauri-1/#migrate-permissions
