### ISSUE TITLE
[feat] Optional Sidecars

### ISSUE THREAD

**Issue by kareemmahlees** [tauri-apps/tauri#8821]
### Describe the problem

It's somewhat annoying that every time I want to run the `dev` or `build` command I have first to build my sidecar + do all the renaming to include the `TARGET_TRIPLE` suffix and extension stuff.

### Describe the solution you'd like

I would like to have an option in `tauri.conf.json` that tells tauri that this sidecar is optional, and the developer should handle the situations where the sidecar is `Some` or `None`.

### Additional context

I am currently developing [TableX](https://github.com/kareemmahlees/tablex) which uses [MetaX](https://github.com/kareemmahlees/meta-x) "written in go" as a sidecar.

The process is as follows:
- I have to first build the go application and produce a binary.
- I have to suffix the binary with the `TARGET_TRIPLE` and the extension.
- Then I run `tauri dev` to start the app.

But, what if I don't want to touch MetaX ( because it is already a separate repo but included in TableX as a submodule ), it would be nice to build the app without the sidecar because if I want to contribute to MetaX I should just head to it's repo right!

This also doesn't stop here, it forced me to update the workflows to setup go and build the application and so on, which seems useless to me because I want to test that _TableX_ is compiling fine, not _MetaX_.

**Comment by amrbashir** [comment]
Why do you need to rebuild your sidecar every time your do `tauri dev`? you should only build it once and forget about until you make changes to the sidecar itself and then you build it again. If that's a frequent task, you may want to automate it using a script or something that can be run using `beforeDevCommand` or `beforeBuildCommand` option in `tauri.conf.json`

If you really want optional, then:
- You can remove the sidecar from your `tauri.conf.json`
- create a `tauri.conf.sidecar.json` (name doesn't matter) and fill it with
  ```json
  {
  	"tauri": {
  	  "bundle": {
      "externalBin": ["path/to/your/sidecar"]
    },
  	}
  }
  ```
- you can then run `tauri dev` and it won't include your sidecar
- whenever you want to include the sidecar, then pass `--config tauri.conf.sidecar.json` to `tauri dev` or `tauri build`

**Comment by kareemmahlees** [comment]
For anyone who stumbles upon this, I had warnings from `rust-analyzer`, after adding another config file, telling me that the `features` in `Cargo.toml` don't match the features enabled in the allow list.

The solution is to make the features in `Cargo.toml` match those in the allow list of `tauri.conf.json`, _even_  if it's missing some features from the other config files, when you run `tauri dev` or `tauri build` with the `--config` option it seems to resolve the extra features.
