### ISSUE TITLE
[bug] Tauri v2 Tray menu does not open without 2nd menu....

### ISSUE THREAD

**Issue by TukanDev** [tauri-apps/tauri#8825]
### Describe the bug

Init Tray in .setup() of tauri builder or however you construct it. Tray icon will show but everytime you click on it you would get this in the console `LIBDBUSMENU-GLIB-WARNING **: 21:23:25.945: About to Show called on an item wihtout submenus.  We're ignoring it.`

### Reproduction

Follow [https://github.com/tauri-apps/tauri/blob/dev/examples/api/src-tauri/src/tray.rs](https://github.com/tauri-apps/tauri/blob/dev/examples/api/src-tauri/src/tray.rs)
1. Strip "switch-menu" case from match in the on_menu_event
2. Strip everything related to menu_2 variable
3. Make sure you have only "toggle" and "quit" case (you can keep anything else not related to menu_2 i am just listing how i came to the bug)
4. attempt to open a tray by clicking on the icon 

### Expected behavior

Menu should open but it does not as described above.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Arch Linux Unknown X64
    ✔ webkit2gtk-4.1: 2.42.4
    ✔ rsvg2: 2.57.1
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 20.10.0
    - npm: 10.3.0

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.21
    - tauri-build [RUST]: 2.0.0-alpha.14
    - wry [RUST]: 0.35.2
    - tao [RUST]: 0.24.1
    - tauri-cli [RUST]: 2.0.0-alpha.21
    - @tauri-apps/api [NPM]: 2.0.0-alpha.14
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.21

[-] App
    - build-type: bundle
    - CSP: default-src 'self'; img-src 'self' https://* asset: https://asset.localhost tauri://localhost; media-src https://* asset: https://asset.localhost tauri://localhost; style-src-elem https://* asset: https://asset.localhost tauri://localhost; script-src-elem https://* asset: https://asset.localhost tauri://localhost;
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Stack trace

```text
LIBDBUSMENU-GLIB-WARNING **: 21:23:25.945: About to Show called on an item wihtout submenus.  We're ignoring it.
```

### Additional context

I did not test this on beta releases or on windows builds but i would assume same issue would occur on windows builds, i do not have windows pc so i can not verify nor a mac besides making a vm if needed... However i had found a demo example of this (now deleted repo) where it used alpha.21 and it did not need to have 2 menus initialized when i tested its tauri dev build it worked fine, even after copying exact code into my codebase it did not work without 2nd menu.
I have opened support thread on discord and after determining it was needing a 2nd menu and agreeing it was weird behavior i was asked to make an issue.
Thread link: [https://discord.com/channels/616186924390023171/1198002663300812971](https://discord.com/channels/616186924390023171/1198002663300812971)

**Comment by amrbashir** [comment]
I couldn't reproduce at all, could you please share a minimal repro?

**Comment by TukanDev** [comment]
> I couldn't reproduce at all, could you please share a minimal repro?

I hereby can confirm that it fully works in 2.0.0-beta.2 build without needing this weird behavior. I do not know what happened at all with this but my implementation works without this now....
As discord thread states suggestion was to add a 2nd menu and that fixed it, even if i confirmed it should work without this with a now deleted demo repo from some person...
Very weird behavior, guess we can close this then???

**Comment by amrbashir** [comment]
Thanks for testing again.
