### ISSUE TITLE
Just want to know: How to Download image in tauri app to my local machine

### ISSUE THREAD

**Issue by devhimanshuhc** [tauri-apps/tauri#8835]
Hello everyone, I'm currently working on a project where I'm rendering images in the frontend fetched from the backend as image links.  How to download these images onto my local machine. Could anyone provide guidance or suggest a solution for achieving this?

**Comment by vonPB** [comment]
Is there anything specific about images or the format, or are you just generally asking how to store files? 
There are function to interact with the filesystem from the js api listed over here https://tauri.app/v1/api/js/fs#writebinaryfile.
If you want to store them via rust, you can use std::fs to interact with the local computers files.
