### ISSUE TITLE
[bug] IOS can't find crate for 'core'

### ISSUE THREAD

**Issue by Kai-Toyata** [tauri-apps/tauri#8841]
### Describe the bug

I have built a blank Tauri project and I am trying to run `npm run tauri ios dev` and it fails to build due to "can't find crate for 'core'". I have all the prerequisites installed and prerequisite commands run (refer to reproductions).

Running `tauri dev` works fine. I cannot try it for Android sorry.

### Reproduction

Have Homebrew installed and cocoapods and rust  installed from brew.

`rustup target add aarch64-apple-ios x86_64-apple-ios aarch64-apple-ios-sim`

`npm create tauri-app@latest -- --alpha`

Choose typescript, npm, Angular, and yes to mobile development

cd into the folder

`npm i`

`npm run tauri ios init`

`npm run tauri ios dev`

Then choose any simulator

### Expected behavior

The simulator should launch with the app running.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.1.2 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21) (Homebrew)
    ✔ cargo: 1.75.0
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.10.0
    - npm: 10.2.3
    - bun: 1.0.18

[-] Packages
    - tauri [RUST]: 2.0.0-beta.2
    - tauri-build [RUST]: 2.0.0-beta.1
    - wry [RUST]: 0.35.2
    - tao [RUST]: 0.25.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.0
    - @tauri-apps/cli [NPM]: 2.0.0-beta.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist/goal-tracker/browser
    - devUrl: http://localhost:1420/
    - framework: Angular
    - bundler: Webpack

[-] iOS
    - Developer Teams: REDACTED
```

### Stack trace

```text
error[E0463]: can't find crate for `core`
  |
  = note: the `aarch64-apple-ios-sim` target may not be installed
  = help: consider downloading the target with `rustup target add aarch64-apple-ios-sim`

error[E0463]: can't find crate for `compiler_builtins`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `cfg-if` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
       Error [tauri_cli_node] Failed to run `cargo build`: command ["cargo", "build", "--package", "REDACTED", "--manifest-path", "REDACTED/src-tauri/Cargo.toml", "--target", "aarch64-apple-ios-sim", "--features", "tauri/rustls-tls", "--lib", "--no-default-features"] exited with code 101
Command PhaseScriptExecution failed with a nonzero exit code

note: Run script build phase 'Build Rust Code' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'REDACTED' from project 'REDACTED')
** BUILD FAILED **
```

**Comment by FabianLars** [comment]
You say you have rust installed from brew, I assume you mean actually rust and not rustup? Because that will install another toolchain that will conflict with the one installed via rustup which means the target add command did nothing.

You either have to look into how to add targets to the brew toolchain (idk how) or what I'd recommend, uninstall the brew toolchain and solely rely on rustup.

**Comment by Kai-Toyata** [comment]
> You say you have rust installed from brew, I assume you mean actually rust and not rustup? Because that will install another toolchain that will conflict with the one installed via rustup which means the target add command did nothing.
> 
> You either have to look into how to add targets to the brew toolchain (idk how) or what I'd recommend, uninstall the brew toolchain and solely rely on rustup.

Yes this was the issue. I uninstalled rust through brew `rust uninstall brew` and then that fixed the issue. Thank you for your help. I hope this issue thread helps someone else.
