### ISSUE TITLE
[bug] Failed to bundle project if "productName" contains a dot

### ISSUE THREAD

**Issue by Andrew-web-coder** [tauri-apps/tauri#8848]
### Describe the bug

I want to name my app "My cool app 2.0", but, if I edit `tauri.conf.json` and for "package"/"productName" use "My cool app 2.0", it fails with this error message:

`Error failed to bundle project: error running light.exe`

If I use name without a dot, for example, "My cool app 2", then it works fine.

### Full `tauri info` output

```text
`Error failed to bundle project: error running light.exe`
```

**Comment by hengkx** [comment]
contains to chinese.same error
