### ISSUE TITLE
[bug] Sveltekit + Tauri v2 beta automatically closing without any errors

### ISSUE THREAD

**Issue by Maxensimon** [tauri-apps/tauri#8849]
### Describe the bug

When I'm developping my Sveltekit + Tauri app and updating a component that's trigger the Vite reload. Tauri just close randomly without any errors, warning or any text. 

### Reproduction

Generate a Sveltekit + Tauri beta project. (First Sveltekit then Tauri, not from create-tauri-app)
Create a svelte component.
Update it multiples times to trigger the Vite reload each time
Watch Tauri closing after two or three attempts.

### Expected behavior

The app should not close at any point.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 121.0.2277.106
    ✔ MSVC:
        - Visual Studio Build Tools�2019
        - Visual Studio Community 2022
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.10.0
    - npm: 10.2.5
    - bun: 1.0.18

[-] Packages
    - tauri [RUST]: 2.0.0-beta.2
    - tauri-build [RUST]: 2.0.0-beta.1
    - wry [RUST]: 0.35.2
    - tao [RUST]: 0.25.0
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-beta.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

**Comment by Maxensimon** [comment]
Seems to be a mouse event. When I'm hovering a button, the cursor change rapidly between the base cursor and pointer cursor and after 5-10 secondes my app just close.

**Comment by amrbashir** [comment]
Should be fixed by https://github.com/tauri-apps/tauri/pull/8790 then
