### ISSUE TITLE
[bug] v2-shell unknown field `scope`

### ISSUE THREAD

**Issue by NoahCodeGG** [tauri-apps/tauri#8855]
### Describe the bug

![CleanShot 2024-02-14 at 10 05 50@2x](https://github.com/tauri-apps/tauri/assets/51156988/85a11b8a-38a2-43c7-ad54-2c9f6f09cff3)
![CleanShot 2024-02-14 at 10 07 59@2x](https://github.com/tauri-apps/tauri/assets/51156988/ffdec900-f368-4b16-8092-6a12ab666a2d)

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.3.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.11.0
    - pnpm: 8.15.2
    - yarn: 1.22.21
    - npm: 10.2.4
    - bun: 1.0.26

[-] Packages
    - tauri [RUST]: 2.0.0-beta.2
    - tauri-build [RUST]: 2.0.0-beta.1
    - wry [RUST]: 0.35.2
    - tao [RUST]: 0.25.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.0
    - @tauri-apps/cli [NPM]: 2.0.0-beta.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: SolidJS
    - bundler: Vite
```

**Comment by amrbashir** [comment]
Allowlist and scopes have been refactored and a new system have been implemented, here is an example of the new scope in use https://github.com/tauri-apps/plugins-workspace/blob/53c0e898608b2fe96d20e417905674ca41d8a089/examples/api/src-tauri/capabilities/base.json#L33-L42
