### ISSUE TITLE
[bug] tauri.localhost refused the connection.

### ISSUE THREAD

**Issue by 0x72616661656C** [tauri-apps/tauri#8867]
### Describe the bug

When I finish building my program in [Next.js](https://nextjs.org/) using Tauri and try to open it, the error appears: **tauri.localhost refused the connection.**
![image](https://github.com/tauri-apps/tauri/assets/119011110/6c4baab2-3d08-4c6a-9424-df3458681507)

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 121.0.2277.112
    ✔ MSVC: Ferramentas de Build do Visual Studio 2022
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.11.0
    - pnpm: 8.15.0
    - yarn: 1.22.21
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 1.5.4
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.7
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.9

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist/
    - devPath: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Webpack
```

**Comment by FabianLars** [comment]
This typically means you didn't follow this: https://tauri.app/v1/guides/getting-started/setup/next-js#nextjs-static-exports - nextjs only works in tauri with a static export because there's no nodejs runtime in tauri apps.

**Comment by 0x72616661656C** [comment]
Do you know of another tool that has a nodejs runtime where I can make my application?

**Comment by FabianLars** [comment]
Other than Electron no. I've not looked into this for quite a looong time.

Alternatively you could include nodejs as a sidecar in a tauri app https://tauri.app/v1/guides/building/sidecar (node example linked at the bottom). Not really straight forward but i've seen people do that 🤷
