### ISSUE TITLE
[bug] Window focus event conflicts with SystemTrayEvent::LeftClick event on windows os

### ISSUE THREAD

**Issue by rp1231** [tauri-apps/tauri#8869]
### Describe the bug

Window focus event conflicts with SystemTrayEvent::LeftClick event on windows os

https://github.com/tauri-apps/tauri/assets/47380919/48a71a73-7e0a-4a99-a7d8-61a06fd403ea

### Reproduction

Create a tray app that shows a window on click and hides the window on losing focus on windows os.

Code Used:
```rust
.on_system_tray_event(|app, event| {
    match event {
        SystemTrayEvent::LeftClick {
            position: _,
            size: _,
            ..
        } => {
            let window = app.get_window("main").unwrap();
            let new_title = if window.is_visible().unwrap() {
                window.hide().unwrap();
                "Show"
            } else {
                window.show().unwrap();
                window.set_focus().unwrap();
                "Hide"
            };
            app.tray_handle()
                .get_item("toggle")
                .set_title(new_title)
                .unwrap();
        }
        _ => {}
    }
})
.on_window_event(|event| {
    if let tauri::WindowEvent::Focused(focused) = event.event() {
        // hide window whenever it loses focus
        if !*focused {
            if let Err(err) = event.window().hide() {
                eprintln!("Error hiding window: {:?}", err);
            }
            // Update tray item title to "Show"
            event
                .window()
                .app_handle()
                .tray_handle()
                .get_item("toggle")
                .set_title("Show")
                .unwrap();
        }
    }
})
```

### Expected behavior

Clicking the first time on the tray icon should show the window and clicking a second time should hide the window.

### Full `tauri info` output

```text
WARNING: no lock files found, defaulting to npm

[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 121.0.2277.112
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 21.6.1
    - pnpm: 8.12.1
    - yarn: 1.22.19
    - npm: 10.2.1

[-] Packages
    - tauri [RUST]: 1.5.4
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: git+https://github.com/tauri-apps/tao?branch=v0.16#3aa1200c976c050b07a703d6620afc3f3c4c88fe (0.16.5)
    - tauri-cli [RUST]: 1.5.9
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 1.5.9

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: ../dist
```

### Additional context

As seen in the video, the window appears on mouse up when It is hidden and the tray icon is clicked.
And when the window is already visible, the mouse down hides the window and mouse up brings it back up.
So If the mouse up event could be ignored when the window is visible maybe this problem could be solved.

**Comment by rp1231** [comment]
@FabianLars

**Comment by rp1231** [comment]
SystemTray:LeftClick on windows os triggers only on mouse up.
The mouse down is reserved for moving the tray icons around.
(Vs MacOS where AFAIK you have to hold down the command key plus click to move the tray icons)
Which is why the conflict happens in this particular scenario
The mouse down makes the window lose focus and the mouse up sends the trigger again.

Any way a solution for this could be implemented into tauri itself?

**Comment by rp1231** [comment]
Maybe the solution can be that the SystemTrayEvent::LeftClick on windows "prevent defaults" the mouse down event so that the window focus is not lost and only resgisters the mouse up event.

**Comment by amrbashir** [comment]
Sorry for the late response.

What you're experiencing the expected behavior. When your window has focus, then you click on the tray icon, it loses focus and the tray icon itself gains that focus, causing that to send a `focused: false` event to your window and your logic to hide it will run, but shortly after the tray click finishes and sends an tray event where you have logic to show the window. 

We can't fix this on our side, I recommend setting a timeout in a state and checking if that timer has elapsed enough so the next click event from tray doesn't take effect.
