### ISSUE TITLE
[bug] `tauri add store` adds wrong initialization code

### ISSUE THREAD

**Issue by vasfvitor** [tauri-apps/tauri#8880]
### Describe the bug

When running `yarn tauri add store` it register the plugin with:
`.plugin(tauri_plugin_store::Builder::new().build())` 
instead of:
`.plugin(tauri_plugin_store::Builder::default().build())`

### Reproduction

In a Tauri v2 beta project run:
`cargo tauri add store`

### Expected behavior

`tauri add store` adds correct initialization code

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 121.0.2277.112
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.11.0
    - yarn: 3.1.1
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.2
    - tauri-build [RUST]: 2.0.0-beta.1
    - wry [RUST]: 0.35.2
    - tao [RUST]: 0.25.0
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-beta.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:5173/
    - framework: React (Next.js)
    - bundler: Vite
```

### Additional context

A few other plugins have different patterns from `Builder::new().build()` and `init()` thus might be subjected to the current issue.

Some plugins also requires additional setup params inside the `build()` function, to name: stronghold-plugin.

**Comment by amrbashir** [comment]
I have opened a PR to fix these plugins https://github.com/tauri-apps/plugins-workspace/pull/968 instead of fixing the CLI, not sure what to do about stronghold yet.
