### ISSUE TITLE
[bug] The packaged application displays the message "There is a problem with this page"

### ISSUE THREAD

**Issue by drdevelop** [tauri-apps/tauri#8882]
### Describe the bug

The packaged application displays the message "There is a problem with this page"
![image](https://github.com/tauri-apps/tauri/assets/39514265/487b1fb1-6dcf-4e22-8f37-8dc6eb3768d6)

### Reproduction

Occasionally

### Expected behavior

Show normal page

### Full `tauri info` output

```text
no
```

**Comment by amrbashir** [comment]
Please provide a reproduction and `tauri info`
