### ISSUE TITLE
Add start script to package.json [feat] 

### ISSUE THREAD

**Issue by zaynekomichi** [tauri-apps/tauri#8883]
### Describe the problem

Having to write npm run tauri dev every time I need to run application gets tiresome, not to mention you cannnot start the application on the click of a button in any selected ide. I ended up creating custom script to run the project on click on all my projects

### Describe the solution you'd like

Add start script to  packagejson, allowing this allows application to be started on click of a run button under npm scripts or setting up on other IDE's this is how package.json scripts object will look will look

```
"scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview",
    "tauri": "tauri",
    "start": "tauri dev"
  },
```

![image](https://github.com/tauri-apps/tauri/assets/54587124/e81189b2-3a77-4a50-885c-49f49193761a)

**Comment by amrbashir** [comment]
I think we decided not to do that by default for two reasons:
- keep the npm scripts from your frontend as is for web-only development
- avoiding adding scripts for `tauri dev` and `tauri build` which will mean in the future, we will add scripts for `tauri ios build`, `tauri ios dev`, `tauri android dev`, `tauri android build`...etc

Also adding a npm script is a relatively easy task so it is better left to the user to add the scripts they need.

I will close this issue for now but if more people request it, we will reconsider.

**Comment by zaynekomichi** [comment]
True i get for point #2!
