### ISSUE TITLE
[docs] dead link to .changes/readme.md in pull request template

### ISSUE THREAD

**Issue by anatawa12** [tauri-apps/tauri#8904]
In pullrequest template

> 3. If this change requires a new version, then add a change file in `.changes` directory with the appropriate bump, see https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md

However, https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md is not exists

**Comment by anatawa12** [comment]
I found the document exists on the 1.x branch

**Comment by amrbashir** [comment]
Seems to have been removed by accident in https://github.com/tauri-apps/tauri/commit/88a1dd17c3fe49002446c1b4e8ec10f1bd482878, thanks for reporting
