### ISSUE TITLE
Not allowed to load local resource

### ISSUE THREAD

**Issue by songjiachao** [tauri-apps/tauri#8917]
### Describe the bug

![image](https://github.com/tauri-apps/tauri/assets/70792885/1737307d-fadf-41a3-8352-98940f155240)

I want to read image from homeDIr（file:///Users/11091628/.funapp/appIcons/Fun.app.png）

it return error "Not allowed to load local resource: file:///Users/11091628/.funapp/appIcons/Fun.app.png"

I have set fs config in capabilities
<img width="896" alt="image" src="https://github.com/tauri-apps/tauri/assets/70792885/f06cd4ef-5dd6-4e69-85c1-2b7a0dd91a34">

  {
      "identifier": "fs:allow-read",
      "allow": [{ "path": "$HOME/**" }]
    },

or 
  {
      "identifier": "fs:scope",
      "allow": [{ "path": "$HOME/**" }]
    },

Both doesn't work

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.9.0
    - pnpm: 8.15.3
    - yarn: 1.22.19
    - npm: 10.1.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.2
    - tauri-build [RUST]: no manifest (2.0.0-beta.1, 2.0.0-beta.1)
    - wry [RUST]: 0.35.2
    - tao [RUST]: 0.25.0
    - tauri-cli [RUST]: 2.0.0-beta.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.0
    - @tauri-apps/cli [NPM]: 2.0.0-beta.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://127.0.0.1:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by amrbashir** [comment]
`file://` protocol is not supported, instead you need to use `convertFileSrc` from `@tauri-apps/api` NPM package and you need to configure `app > security > asset_protocol` in tauri.conf.json
