### ISSUE TITLE
`tauri dev` is incredibly slow

### ISSUE THREAD

**Issue by seaglade** [tauri-apps/tauri#8920]
### Describe the bug

When running `tauri dev` the app takes *minutes* to launch, and a single change to a file forces it to start over, seemingly from scratch. This happens when running `yarn tauri dev` in the unchanged result of `yarn create tauri-app`. Around 300 rust libraries seem to be getting compiled every time a change is made.

### Reproduction

```sh
yarn create tauri-app # Fill out the form and let it create the project
cd <app-directory>
yarn
yarn tauri dev
```

### Expected behavior

Interface loads quickly and refreshes quickly when files are changed.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 121.0.2277.128
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.74.1 (a28077b28 2023-12-04)
    ✔ cargo: 1.74.1 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 21.6.1
    - pnpm: 8.15.3
    - yarn: 1.22.19
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 1.6.0
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.7
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.10

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by seaglade** [comment]
Huh, if the change is made to the UI the interface reloads instantly. It's only backend changes that take so long. That makes a bit more sense but is still problematic.

**Comment by seaglade** [comment]
Running `tauri build` and then `tauri dev` seems to have fixed the issue. I'm guessing the `dev` command does something differently that causes it to rebuild everything every single time. Regardless, I hope that this can be documented somewhere and/or fixed.

**Comment by amrbashir** [comment]
This is something related to Rust and its incremental compilation, it shouldn't recompile your dependencies unless necessary. Anyways, there is nothing we can do since this seems like a Rust issue.

**Comment by kon72** [comment]
If you are using rust-analyzer on VS Code, try using separate target directory for rust-analyzer and tauri.

`.vscode/settings.json`:

```.vscode/settings.json
{
  "rust-analyzer.server.extraEnv": {
    "CARGO_TARGET_DIR": "${workspaceFolder}/src-tauri/target/analyzer"
  },
  "rust-analyzer.cargo.targetDir": "${workspaceFolder}/src-tauri/target/analyzer"
}
```

ref: https://github.com/rust-lang/rust-analyzer/issues/4616

**Comment by guillaume-mueller** [comment]
> This is something related to Rust and its incremental compilation, it shouldn't recompile your dependencies unless necessary. Anyways, there is nothing we can do since this seems like a Rust issue.

Sorry but this is a very bad way of replying, especially when the solution you offer is not the only one.

I just discovered this project without any opinion on its use of Rust (I've not intended to use it for such an application while being a Rust enthusiast) and the instant blocker thing I encountered is the compilation time of a few minutes with the basic start project template.

Saying "there is nothing we can do since this seems like a AB issue" when you decided to use AB is worrying regarding your capacity to overcome obstacles you put yourself in your route.

I really hope the "it shouldn't recompile your dependencies unless necessary" is a one-for-all solution to the issue, but the existence of this issue makes me doubt.

**Comment by rxliuli** [comment]
I encountered the same problem. On the M2 Max, every time I modify the Rust code, it blocks and compiles for more than 30 seconds. I don't know why the created template project has issues, but obviously, this is problematic.

https://github.com/user-attachments/assets/d3102f72-a3ce-4a83-a67b-b73c94355902

**Comment by FabianLars** [comment]
@rxliuli yours sounds more like this https://github.com/tauri-apps/tauri/issues/11577 (has a workaround inside)

**Comment by rxliuli** [comment]
> [@rxliuli](https://github.com/rxliuli) yours sounds more like this [#11577](https://github.com/tauri-apps/tauri/issues/11577) (has a workaround inside)

Yes, I know this temporary workaround. But I don't understand why it wasn't done correctly in the template project directly, and instead you have to manually modify the configuration to fix such an obvious problem.
