### ISSUE TITLE
[feat] Tauri2.0 Mobile

### ISSUE THREAD

**Issue by qwe104** [tauri-apps/tauri#8927]
### Describe the problem

When will Tauri2.0 Mobile be released?

### Describe the solution you'd like

I am currently working on an Android project, but as a non-native Android developer, I would like to explore tauri2.0 Mobile. However, since it is not yet available, I have some concerns about its usage. Our project requires a few features:
 1) obtaining the list of available Wi-Fi networks
 2) transmitting the Wi-Fi password via Bluetooth for network provisioning.
 Would such functionality require a tauri plugin in java?

**Comment by FabianLars** [comment]
> When will Tauri2.0 Mobile be released?

When it's ready and audited :) My guess is early Q2.

> Would such functionality require a tauri plugin in java?

Likely yes. Tauri does not expose explicit apis for this. I also doubt that there are rust crates for this but wouldn't rule it out either. If there's none you'll have to use kotlin/java, yes. Either as a plugin or directly in the android studio project of your tauri app.
