### ISSUE TITLE
[bug] [NSIS] License agreement screen cannot be omitted

### ISSUE THREAD

**Issue by podarcis** [tauri-apps/tauri#8944]
### Describe the bug

There seems to be a change from v2-alpha to v2-beta in the NSIS bundler that causes the license agreement screen to be shown (with empty license text field) even if there's no `license` or `licenseFile` file set or set to `null` in [BundleConfig](https://beta.tauri.app/references/v2/config/#bundleconfig). I don't see any configurable option in [NsisConfig](https://beta.tauri.app/references/v2/config/#nsisconfig) either.

In our case we don't want to show the End-user license agreement (EULA) screen as it's a German software product and showing the user the agreement after he bought the product has no legal effect, see [Endbenutzer-Lizenzvertrag](https://de.wikipedia.org/wiki/Endbenutzer-Lizenzvertrag).

Translated quote:
> License terms that are only made available to the buyer after purchase (for example **during installation** or as a printed insert in the packaging) are ineffective for the buyer.

### Reproduction

Create a new Tauri v2-beta app and configure a NSIS bundle to be built. Execute the resulting NSIS installer and advance to second screen. License agreement screen is shown with empty license text.

### Expected behavior

If no license and/or license file is set, don't show the license agreement screen. Or give an option in NsisConfig to omit the screen explicitly.

### Full `tauri info` output

```text
$ yarn tauri info
yarn run v1.22.21
$ tauri info

[✔] Environment
    - OS: Windows 10.0.17763 X64
    ✔ WebView2: 121.0.2277.128
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-i686-pc-windows-msvc (default)
    - node: 20.10.0
    - pnpm: 8.15.2
    - yarn: 1.22.21
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 2.0.0-beta.2
    - tauri-build [RUST]: 2.0.0-beta.1
    - wry [RUST]: 0.35.2
    - tao [RUST]: 0.25.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.2
    - @tauri-apps/cli [NPM]: 2.0.0-beta.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
Done in 10.53s.
```

**Comment by podarcis** [comment]
Unfortunately I can't confirm this is fixed and the license screen is still shown empty for NSIS and the build process outputs:
```
     Running makensis.exe to produce C:\foobar\src-tauri\target\i686-pc-windows-msvc\release\bundle\nsis\Foobar1.0.0_x86-setup.exe
warning 7050: LicenseData: empty license file "C:\foobar\src-tauri\target\i686-pc-windows-msvc\release\com.example.foobar-license"
 (macro:MUI_PAGEDECLARATION_LICENSE:17)
```

I tried both config `bundle.license` and `bundle.licenseFile` either unset or set to `null`.

Any idea? 

---

```
$ yarn tauri info
yarn run v1.22.21
$ tauri info

[✔] Environment
    - OS: Windows 10.0.19044 X64
    ✔ WebView2: 122.0.2365.80
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-i686-pc-windows-msvc (default)
    - node: 20.10.0
    - pnpm: 8.15.4
    - yarn: 1.22.21
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 2.0.0-beta.10
    - tauri-build [RUST]: 2.0.0-beta.8
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.4
    - @tauri-apps/cli [NPM]: 2.0.0-beta.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
Done in 13.18s.
```

**Comment by FabianLars** [comment]
did you delete the target/release dir before trying? Maybe this is still the old file and tauri doesn't remove it itself.

**Comment by podarcis** [comment]
> did you delete the target/release dir before trying? Maybe this is still the old file and tauri doesn't remove it itself.

Yes, I did that too in my test.

**Comment by FabianLars** [comment]
ah, your `@tauri-apps/cli` version is still pretty old. Try upgrading that to beta.8

**Comment by podarcis** [comment]
Oh, thanks for that hint! My package.lock was already at beta.7 but my build script missed to run yarn install. I can confirm it's working with beta.8.
