### ISSUE TITLE
Inject LocalStorage and SessionStorage WebAPI Replacements ( Maybe a Plugin? )

### ISSUE THREAD

**Issue by zicklag** [tauri-apps/tauri#896]
**Is your feature request related to a problem? Please describe.**
I am wanting to create a desktop application for at least two web apps, [Juju Lens](https://github.com/katharostech/juju-lens) and [Cyber Chef](https://github.com/gchq/CyberChef/issues/1074) and both use the `window.localStorage` APIs to persist user preferences. While the localStorage APIs technically "work" in webview, when the server is run on a different localhost port every time webview treats it like a different domain with different LocalStorage, therefore the data is not accessible to the app after closing and restarting it.

**Describe the solution you'd like**
I would like Tauri to replace the LocalStorage API with a wrapper for Tauri commands that will persist the storage in a JSON file in the user's `~/.local/share` directory ( or equivalent ), somehow indexed by the `tauri.bundle.identifier` from the `tauri.conf.json` file.

**Describe alternatives you've considered**
- I think that this could be implemented as a Tauri plugin, but as it is rather core web functionality it seems to make sense that it should work out-of-the-box and be built-in to Tauri core ( or whatever crate it needs to be in, I haven't verified yet ).
- Another possible implementation strategy would be to somehow cause the `tauri.bundle.identifier` to resolve to `localhost:[port that tauri started on]` so that the domain could be the same across starts of the application, but I don't think that this is anywhere near possible with the current webview API ( I'm not experienced with webview, but I did look into it a little bit ).

**Additional context**
I need this for my Juju Lens application and I will probably start work right away on a Tauri plugin, but if you guys decide you would like it in Tauri core, I can start development inside Tauri core instead of a separate crate.

**Comment by zicklag** [comment]
Unfortunately it looks like browsers to not allow overwriting the `window.localStorage` global like we currently do the `window.Notification` global. At least not in the tests that I've done in Firefox and Webview. :confused: That's unfortunate unless someone knows some way around this.

Without being able to patch `window.localStorage` users would have to manually create a shim for their app that will use one or the other based on build arguments or the presence of `window.__TAURI_INVOKE_HANDLER__`.

That's not horrible. At least it's not *hard* to do, it just would have been nice if it was automatically supported. In the case that we can't automatically support it, maybe it would be a good idea to have this as an opt-in plugin for Tauri instead of building it in with the rest of the Tauri API.

**Comment by chippers** [comment]
semi-related to this issue, `window.localStorage` is disabled on local pages on Edge.  (i.e. with `no-server`).  No idea if webkit2gtk or safari behaves the same way

**Comment by zicklag** [comment]
I realized a really easy way around the not being able to override `window.localStorage`. All we have to do is hook into the webview close event and then dump out all of the data in `localStorage` to a file when the view closes. Session storage would just work fine because it doesn't outlive the session anyway, duh :man_facepalming: :slightly_smiling_face:. 

---

> semi-related to this issue, window.localStorage is disabled on local pages on Edge. (i.e. with no-server). No idea if webkit2gtk or safari behaves the same way

I think that's a reasonable limitation. It seems like `no-server` is only useful for very small frontends anyway. When I tried to run my Quasar app with `no-server` on Linux it too 100% of one of my CPU cores for like 5 minutes before the window even showed up, and it still had to load longer after that so I didn't wait for it.

I'm not sure if that is a bug, or just a limitation.

---

On second thought, we could just make a Tauri API for local storage that would always be usable even if you are in `no-server` mode **and** we use the technique where we dump the browsers `localStorage` to a file when it closes. You would only want to use one at a time so Tauri could pick the one to use based on the server mode selected.

We could also test to see if a browser in `no-server` mode would allow you to set `window.localStorage` because it isn't already set? I don't think that would work, but it's worth a try.

**Comment by nothingismagick** [comment]
> I'm not sure if that is a bug, or just a limitation.
regarding 5 minutes - that's def a bug. quasar no-server should work instantly.

should probably regularly update the store instead of just on close, because there may be events like out-of-battery where there is no time to write to the store.

**Comment by zicklag** [comment]
For the "persist when closed" technique for `LocalStorage`, the issue I see so far is that you could have different apps that, when run on the same port, will use the same local storage because the port is random. Even if the app's data was restored by Tauri every time the app started up, if we don't clear the `LocalStorage` as well it would still be able to read the keys from the other app's storage. I think this is a mild security risk, but even if it wasn't a security risk it could still be a very confusing thing if a Tauri app ever happened to run on the same port as another app that the user was hosting on localhost, for development probably.

The Tauri app could end up overwriting any keys that have the same name.

Maybe it *would* be better to just have a Tauri-specific API, and we provide small shim utility that will dynamically select which one to use so that it can be used in browser and Tauri without changes.

> regarding 5 minutes - that's def a bug. quasar no-server should work instantly.

Oh, cool! That's good. :) I'll open another issue for that then.

**Comment by nothingismagick** [comment]
well - we've discussed that internally, and think that an app should have a specific ID within the `~/.my-app` folder, so that you don't get that kind of overlap. but it is always a security risk when you put data in userspace. I've seen this a number of times in the wild with electron, and its very much concerning to me.

**Comment by zicklag** [comment]
Well I've created a basic `TaruiLocalStorage` plugin for use with my app [here](https://github.com/katharostech/juju-lens/blob/a472e0b7872b8be593e8da9b6b985a6cbc8e068e/src-tauri/src/local_storage_plugin.rs#L1).

Right now it could be more efficient because it synchronously opens, reads, and writes the storage file for every `setKey` request. Later I could spawn a thread to manage writing the file and then just send a non-blocking message over the channel to flush the data whenever it changes.

I'm not sure if this is something that we would want built-in to Tauri or not, but this works pretty well for me so far.

**Comment by clockler** [comment]
`window.localStorage` isn't super protected - it has an undefined setter, but you can get around it using `Object.defineProperty(window, "localStorage", { value: replacement })` rather than assigning directly to inject a JS shim. If localStorage is replaced with something implementing the same interface as part of the webview bootstrapping process, then it should transparently allow use of the same interface in Tauri and the browser. Just have the Tauri storage write out to a directory in [`tauri_api::path::data_dir()`](https://docs.rs/tauri-api/0.7.3/tauri_api/path/fn.data_dir.html) when a key is set - so `C:\Users\{username}\AppData\Roaming\my-tauri-app\` or OS equivalent.

**Comment by zicklag** [comment]
Yes! That works! That is *much* nicer. In that case I think it would make sense to build it into Tauri as a standard so that all apps will support it transparently. My custom `localStorage` doesn't perfectly match the behaviour of the browsers `localStorage`, but it should work for most cases.

@nothingismagick would you be interested in a PR that adds this to Tauri as a built-in component?

**Comment by zicklag** [comment]
I updated my local storage implementation to a point where I think it'd be ready for inclusion into Tauri. You can see it here:

https://github.com/katharostech/juju-lens/blob/649b01292d39c2649a2e3843452321a9d0e4f9ca/src-tauri/src/local_storage_plugin.rs#L1

It is now a drop-in replacement for the browsers local storage and should be transparent for, I'm guessing, almost all applications.

If there's interest I can submit a PR.

**Comment by nothingismagick** [comment]
sorry for not getting back to you sooner @zicklag. In the core team we discussed this last night, and came to the conclusion that this is such an important feature that it should be inside of core instead of merely a plugin. Making it an option (on by default?) within the `tauri.conf.json`. Thankyou so much for working through this issue!

**Comment by zicklag** [comment]
No problem. :smiley: 

If I get some spare time I'll try out a PR for including it in core, but if anybody wants to get to it first feel free to beat me to it.

**Comment by lucasfernog** [comment]
This is not a problem anymore since we use the custom protocol in production instead of a localhost server with a random port.

**Comment by wll8** [comment]
Which release implements this feature? Although this issue is closed, it is not associated with the corresponding commit.

@lucasfernog
