### ISSUE TITLE
[bug] "dialog.open not allowed. Permissions associated with this command: dialog:allow-open"

### ISSUE THREAD

**Issue by seongs1024** [tauri-apps/tauri#8967]
### Describe the bug

As follow [the beta document](https://beta.tauri.app/features/dialog/),
```
cargo tauri add dialog
```
run the command to open file dialog 

but got this error
```
"dialog.open not allowed. Permissions associated with this command: dialog:allow-open"
```

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 121.0.2277.128
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.18.2
    - pnpm: 8.9.2
    - npm: 9.8.1

[-] Packages
    - tauri [RUST]: 2.0.0-beta.6
    - tauri-build [RUST]: 2.0.0-beta.4
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.0
    - tauri-cli [RUST]: 2.0.0-beta.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.3
    - @tauri-apps/cli [NPM]: 2.0.0-beta.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: SolidJS
    - bundler: Vite
```

**Comment by seongs1024** [comment]
Solved with [access control list](https://beta.tauri.app/references/v2/acl/#capabilities)

## How to
1. make `capabilities` directory in `src-tauri`: `mkdir -p src-tauri/capabilities`
2. make `{any_name}.json` file for setting capabilities: `touch src-tauri/capabilities/dialog.json`
3. paste below in the file
```
{
    "$schema": "./schemas/desktop-schema.json",
    "identifier": "main-capability",
    "description": "Capability for the main window",
    "windows": ["main"],
    "permissions": [
        "path:default",
        "event:default",
        "window:default",
        "app:default",
        "resources:default",
        "menu:default",
        "tray:default",
        "window:allow-set-title",
        "dialog:allow-open"
    ]
}
```
4. rerun `{package} tauri dev`: `cargo tauri dev`

**Comment by OpoOpo** [comment]
Same problem here, the proposed solution did not help

**Comment by lkxe** [comment]
> Same problem here, the proposed solution did not help

I just tested the solution and it lead to an error. To solve this you have to add
`"dialog:allow-save"`
to the permissions, so it looks like this:

```json
{
  "$schema": "./schemas/desktop-schema.json",
  "identifier": "main-capability",
  "description": "Capability for the main window",
  "windows": ["main"],
  "permissions": [
    "path:default",
    "event:default",
    "window:default",
    "app:default",
    "resources:default",
    "menu:default",
    "tray:default",
    "window:allow-set-title",
    "dialog:allow-open",
    "dialog:allow-save"
  ]
}

**Comment by rafatiburciorst** [comment]
> > Same problem here, the proposed solution did not help
> 
> I just tested the solution and it lead to an error. To solve this you have to add `"dialog:allow-save"` to the permissions, so it looks like this:
> 
> ```json
> {
>   "$schema": "./schemas/desktop-schema.json",
>   "identifier": "main-capability",
>   "description": "Capability for the main window",
>   "windows": ["main"],
>   "permissions": [
>     "path:default",
>     "event:default",
>     "window:default",
>     "app:default",
>     "resources:default",
>     "menu:default",
>     "tray:default",
>     "window:allow-set-title",
>     "dialog:allow-open",
>     "dialog:allow-save"
>   ]
> }
> ```

it works for me, I just had to create a new file capabilities/main.json, i'm using Tauri 2.0

**Comment by felri** [comment]
not working for me:

`Value is not accepted. Valid values: "app:default", "app:allow-app-hide", "app:allow-app-show", "app:allow-name", "app:allow-tauri-version", "app:allow-version", "app:deny-app-hide", "app:deny-app-show", "app:deny-name", "app:deny-tauri-version", "app:deny-version", "event:default", "event:allow-emit", "event:allow-emit-to", "event:allow-listen", "event:allow-unlisten", "event:deny-emit", "event:deny-emit-to", "event:deny-listen", "event:deny-unlisten", "image:default", "image:allow-from-bytes", "image:allow-from-path", "image:allow-new", "image:allow-rgba", "image:allow-size", "image:deny-from-bytes", "image:deny-from-path", "image:deny-new", "image:deny-rgba", "image:deny-size", "menu:default", "menu:allow-append", "menu:allow-create-default", "menu:allow-get", "menu:allow-insert", "menu:allow-is-checked", "menu:allow-is-enabled", "menu:allow-items", "menu:allow-new", "menu:allow-popup", "menu:allow-prepend", "menu:allow-remove", "menu:allow-remove-at", "menu:allow-set-accelerator", "menu:allow-set-as-app-menu", "menu:allow-set-as-help-menu-for-nsapp", "menu:allow-set-as-window-menu", "menu:allow-set-as-windows-menu-for-nsapp", "menu:allow-set-checked", "menu:allow-set-enabled", "menu:allow-set-icon", "menu:allow-set-text", "menu:allow-text", "menu:deny-append", "menu:deny-create-default", "menu:deny-get", "menu:deny-insert", "menu:deny-is-checked", "menu:deny-is-enabled", "menu:deny-items", "menu:deny-new", "menu:deny-popup", "menu:deny-prepend", "menu:deny-remove", "menu:deny-remove-at", "menu:deny-set-accelerator", "menu:deny-set-as-app-menu", "menu:deny-set-as-help-menu-for-nsapp", "menu:deny-set-as-window-menu", "menu:deny-set-as-windows-menu-for-nsapp", "menu:deny-set-checked", "menu:deny-set-enabled", "menu:deny-set-icon", "menu:deny-set-text", "menu:deny-text", "path:default", "path:allow-basename", "path:allow-dirname", "path:allow-extname", "path:allow-is-absolute", "path:allow-join", "path:allow-normalize", "path:allow-resolve", "path:allow-resolve-directory", "path:deny-basename", "path:deny-dirname", "path:deny-extname", "path:deny-is-absolute", "path:deny-join", "path:deny-normalize", "path:deny-resolve", "path:deny-resolve-directory", "resources:default", "resources:allow-close", "resources:deny-close", "shell:default", "shell:allow-execute", "shell:allow-kill", "shell:allow-open", "shell:allow-stdin-write", "shell:deny-execute", "shell:deny-kill", "shell:deny-open", "shell:deny-stdin-write", "tray:default", "tray:allow-get-by-id", "tray:allow-new", "tray:allow-remove-by-id", "tray:allow-set-icon", "tray:allow-set-icon-as-template", "tray:allow-set-menu", "tray:allow-set-show-menu-on-left-click", "tray:allow-set-temp-dir-path", "tray:allow-set-title", "tray:allow-set-tooltip", "tray:allow-set-visible", "tray:deny-get-by-id", "tray:deny-new", "tray:deny-remove-by-id", "tray:deny-set-icon", "tray:deny-set-icon-as-template", "tray:deny-set-menu", "tray:deny-set-show-menu-on-left-click", "tray:deny-set-temp-dir-path", "tray:deny-set-title", "tray:deny-set-tooltip", "tray:deny-set-visible", "webview:default", "webview:allow-create-webview", "webview:allow-create-webview-window", "webview:allow-internal-toggle-devtools", "webview:allow-print", "webview:allow-reparent", "webview:allow-set-webview-focus", "webview:allow-set-webview-position", "webview:allow-set-webview-size", "webview:allow-webview-close", "webview:allow-webview-position", "webview:allow-webview-size", "webview:deny-create-webview", "webview:deny-create-webview-window", "webview:deny-internal-toggle-devtools", "webview:deny-print", "webview:deny-reparent", "webview:deny-set-webview-focus", "webview:deny-set-webview-position", "webview:deny-set-webview-size", "webview:deny-webview-close", "webview:deny-webview-position", "webview:deny-webview-size", "window:default", "window:allow-available-monitors", "window:allow-center", "window:allow-close", "window:allow-create", "window:allow-current-monitor", "window:allow-destroy", "window:allow-hide", "window:allow-inner-position", "window:allow-inner-size", "window:allow-internal-toggle-maximize", "window:allow-is-closable", "window:allow-is-decorated", "window:allow-is-focused", "window:allow-is-fullscreen", "window:allow-is-maximizable", "window:allow-is-maximized", "window:allow-is-minimizable", "window:allow-is-minimized", "window:allow-is-resizable", "window:allow-is-visible", "window:allow-maximize", "window:allow-minimize", "window:allow-outer-position", "window:allow-outer-size", "window:allow-primary-monitor", "window:allow-request-user-attention", "window:allow-scale-factor", "window:allow-set-always-on-bottom", "window:allow-set-always-on-top", "window:allow-set-closable", "window:allow-set-content-protected", "window:allow-set-cursor-grab", "window:allow-set-cursor-icon", "window:allow-set-cursor-position", "window:allow-set-cursor-visible", "window:allow-set-decorations", "window:allow-set-effects", "window:allow-set-focus", "window:allow-set-fullscreen", "window:allow-set-icon", "window:allow-set-ignore-cursor-events", "window:allow-set-max-size", "window:allow-set-maximizable", "window:allow-set-min-size", "window:allow-set-minimizable", "window:allow-set-position", "window:allow-set-progress-bar", "window:allow-set-resizable", "window:allow-set-shadow", "window:allow-set-size", "window:allow-set-skip-taskbar", "window:allow-set-title", "window:allow-set-visible-on-all-workspaces", "window:allow-show", "window:allow-start-dragging", "window:allow-theme", "window:allow-title", "window:allow-toggle-maximize", "window:allow-unmaximize", "window:allow-unminimize", "window:deny-available-monitors", "window:deny-center", "window:deny-close", "window:deny-create", "window:deny-current-monitor", "window:deny-destroy", "window:deny-hide", "window:deny-inner-position", "window:deny-inner-size", "window:deny-internal-toggle-maximize", "window:deny-is-closable", "window:deny-is-decorated", "window:deny-is-focused", "window:deny-is-fullscreen", "window:deny-is-maximizable", "window:deny-is-maximized", "window:deny-is-minimizable", "window:deny-is-minimized", "window:deny-is-resizable", "window:deny-is-visible", "window:deny-maximize", "window:deny-minimize", "window:deny-outer-position", "window:deny-outer-size", "window:deny-primary-monitor", "window:deny-request-user-attention", "window:deny-scale-factor", "window:deny-set-always-on-bottom", "window:deny-set-always-on-top", "window:deny-set-closable", "window:deny-set-content-protected", "window:deny-set-cursor-grab", "window:deny-set-cursor-icon", "window:deny-set-cursor-position", "window:deny-set-cursor-visible", "window:deny-set-decorations", "window:deny-set-effects", "window:deny-set-focus", "window:deny-set-fullscreen", "window:deny-set-icon", "window:deny-set-ignore-cursor-events", "window:deny-set-max-size", "window:deny-set-maximizable", "window:deny-set-min-size", "window:deny-set-minimizable", "window:deny-set-position", "window:deny-set-progress-bar", "window:deny-set-resizable", "window:deny-set-shadow", "window:deny-set-size", "window:deny-set-skip-taskbar", "window:deny-set-title", "window:deny-set-visible-on-all-workspaces", "window:deny-show", "window:deny-start-dragging", "window:deny-theme", "window:deny-title", "window:deny-toggle-maximize", "window:deny-unmaximize", "window:deny-unminimize".`

**Comment by chungle1504-bosch** [comment]
This one works for me: 
```
{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "default",
  "description": "enables the default permissions",
  "windows": [
    "main"
  ],
  "permissions": [
    "core:default",
    "core:app:default",
    "core:event:default",
    "core:window:default",
    "core:resources:default",
    "core:menu:default",
    "core:tray:default",
    "core:path:default",
    "dialog:allow-open",
    "dialog:allow-message"
  ]
}
```

**Comment by FelixSelter** [comment]
The bare minimum needed  to save is

src-tauri/capabilities/dialog.json
```json
{
    "identifier": "default",
    "windows": [
        "main"
    ],
    "permissions": [
        "dialog:default",
        "dialog:allow-save"
    ]
}
```
