### ISSUE TITLE
How To Remove The Developer Menu

### ISSUE THREAD

**Issue by Dhawal-1** [tauri-apps/tauri#8974]
### Describe the problem

Is there any way to remove the default right click menu.
![image](https://github.com/tauri-apps/tauri/assets/135719284/4e2dbac3-dd05-4502-ac73-d307151cb5fb)

### Describe the solution you'd like

I like to have a configuration Tauris config file.

**Comment by Borber** [comment]
if you use vite

```js
        if (!import.meta.env.DEV) {
            document.oncontextmenu = (event) => {
                event.preventDefault()
            }
        }
```

Put this in your front-end code, it will cancel this menu

Sample code:

https://github.com/Borber/Tran/blob/master/src/App.tsx#L39-L43

**Comment by amrbashir** [comment]
you need to listen to 'contextmenu' event in JS and disable it.

**Comment by nomandhoni-cs** [comment]
@Borber Thanks man, It worked

**Comment by ManifoldWanderer** [comment]
> if you use vite
> 
>         if (!import.meta.env.DEV) {
>             document.oncontextmenu = (event) => {
>                 event.preventDefault()
>             }
>         }
> Put this in your front-end code, it will cancel this menu
> 
> Sample code:
> 
> https://github.com/Borber/Tran/blob/master/src/App.tsx#L39-L43

@Borber Can you disable the menu only in the release build without using Vite?
