### ISSUE TITLE
[feat] Add bunjs support 

### ISSUE THREAD

**Issue by Manuelito-Code** [tauri-apps/tauri#8976]
### Describe the problem

it would be awesome if you can use bun instead of nodejs, it may be faster and easier for the developer.

### Describe the solution you'd like

add the bun cli to start a new project.

**Comment by amrbashir** [comment]
We are not using Node.js at all, so we can't replace it with bun.

Tauri uses Rust as a backend and normal JS in the browser in the frontend, with plans to support different languages for the backend, see #4670.

You can however use bun as of now as a package manager for your frontend project.

**Comment by Manuelito-Code** [comment]
okay thank you for claring it!
