### ISSUE TITLE
[feat] enhance `.plugin()` inside the app `Builder`

### ISSUE THREAD

**Issue by p1mo** [tauri-apps/tauri#8978]
### Describe the problem

Sometimes when we use plugins they are available on desktop and not on mobile and viceversa. Then we get non working features or build errors.

### Describe the solution you'd like

i already have a solution for this problem and i'd like to share it.

example code can be seen in this gist: https://gist.github.com/p1mo/f37745df20d294e93ed42e03073e8277

and have a idea to add this to tauri.

First i found a good place for it and its here: https://github.com/tauri-apps/tauri/blob/dev/core/tauri/src/app.rs#L1755

For new users i would like to split the gist in two parts.

1. `.plugin_desktop()` and `.plugin_mobile()` will be added without an cfg feature. So when new users use a plugin thats mobile only they could use `.plugin_mobile()` and the same for desktop. For cross plugins like desktop and mobile they can still use `.plugin()`.

2. all other os plugin wrappers like `.plugin_windows()`, `.plugin_linux()`, etc .. i would add it with a cfg flag called `os-plugins` so new users don't get confused or overwhelmed from all these .plugin_...

so overall the user would have `.plugin()`, `.plugin_desktop()` and `.plugin_mobile()` without an cfg flag and with the flag they would get all other wrappers too.

### Alternatives considered

hmm... copy & paste the gist into their projects.

### Additional context

i think this feature would make the development with tauri a lot better ...

**Comment by p1mo** [comment]
Changes can be seen here in the forked repo: https://github.com/tauri-apps/tauri/compare/dev...p1mo:tauri:dev

**Comment by amrbashir** [comment]
Sounds good from a first glance, lets discuss more when you open a PR
