### ISSUE TITLE
[docs] Add the #works-with-solidjs

### ISSUE THREAD

**Issue by vld-b** [tauri-apps/tauri#8985]
I've combined Tauri and [SolidJS](https://www.solidjs.com) to make a desktop video player. Though my app isn't the best example of such harmony, please consider adding this tag.

**Comment by FabianLars** [comment]
thanks for the suggestion, i added it. Though imho we should remove all those tags, they feel a bit useless to me. They don't work as actual github topics since only tauri uses them, and it's also not an excessive list of frameworks that work with tauri either.
