### ISSUE TITLE
[bug] Cannot update app with an error Network error: Download request failed with status: 404 Not Found

### ISSUE THREAD

**Issue by oukunan** [tauri-apps/tauri#8987]
### Describe the bug

I'm attempting to configure the updater for its correct functioning. I now receive this dialog whenever a new update becomes available. However, there is nothing that happens when I click the blue button after that.

<img width="362" alt="Screenshot 2567-02-26 at 23 07 31" src="https://github.com/tauri-apps/tauri/assets/16300114/abda7185-7b13-4015-a54e-aad89d2a2c57">

Also got an error from the update status event

``"Network error: Download request failed with status: 404 Not Found" ERROR"``

My updater look like this

```json
    "updater": {
      "active": true,
      "dialog": true,
      "endpoints": [
        "https://gist.githubusercontent.com/futurouz/8475f3c268f85ec7f735b8c4b723b48b/raw"
      ],
      "pubkey": "dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IDdDNzgzODJFNDI3NkUwRTUKUldUbDRIWkNMamg0ZkV0dXZNSUI1ZTM4MmNobEZ5VGd6c0hDZnZhKzUwT3BMcHlMRFIvcHNINHgK"
    }

```

### Expected behavior

I expect the new version to be downloaded and installed, and for the app to restart.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.0.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.74.0 (79e9716c9 2023-11-13)
    ✔ cargo: 1.74.0 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 16.15.1
    - pnpm: 8.11.0
    - yarn: 1.22.17
    - npm: 9.6.1

[-] Packages
    - tauri [RUST]: 1.5.3
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.6
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.7 (outdated, latest: 1.5.10)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by amrbashir** [comment]
That is because the URL you have in the JSON returned by your updater endpoint doesn't point to anything, and it gives 404.
