### ISSUE TITLE
Desktop failed to exec

### ISSUE THREAD

**Issue by jswhisperer** [tauri-apps/tauri#899]
**Describe the bug**
after building the .deb is malformed with a whitespace error.
app.deb > data.tar.gz > /usr/share/applications/app.desktop
```
[Desktop Entry]
Encoding=UTF-8
Categories=Development;Exec=tauri-app-2
Icon=tauri-app-2
Name=tauri-app-2
Terminal=false
Type=Application
Version=0.1.0
```

**To Reproduce**
yarn Tauri build
on Ubuntu 20.04

**Expected behavior**

**Screenshots**
![Screenshot from 2020-07-27 08-43-37](https://user-images.githubusercontent.com/1177690/88543457-fac69480-cfe5-11ea-97b2-1c1209e7adc8.png)

**Platform and Versions (please complete the following information):**

```
❯ yarn tauri info
yarn run v1.22.4
$ tauri info
[tauri]: running info

Operating System - Linux(5.4.0-40-generic) - linux/x64

Node.js environment
  Node.js - 14.0.0
  tauri.js - 0.11.0

Rust environment
  rustc - 1.45.0
  cargo - 1.45.0
  tauri-bundler - 0.9.1

Global packages
  NPM - 6.14.4
  yarn - 1.22.4

App directory structure
/dist
/node_modules
/src-tauri

App
  tauri.rs - 0.9.0
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist
  devPath - http://localhost:4000
Done in 6.81s.
```

**Additional context**

**Stack Trace**

**Comment by nothingismagick** [comment]
Yeah, it's a newline that seems to be missing - and the semicolon is just wrong.

Thanks für filing the issue
