### ISSUE TITLE
How to port Tauri to other system platforms?

### ISSUE THREAD

**Issue by 1595901624** [tauri-apps/tauri#9016]
### Describe the problem

How to port Tauri to other system platforms？I would like to port Tauri to HarmonyOS. Are there any official porting documents available?

### Describe the solution you'd like

porting documents

**Comment by amrbashir** [comment]
Unfortunately not, but you could take a look at https://github.com/tauri-apps/wry/tree/dev/src/android

**Comment by FabianLars** [comment]
I'll close this as a duplicate of #7287 - If there are even other platforms there should imo each get their own issue,
