### ISSUE TITLE
[bug] Tauri Updater with private Github repository

### ISSUE THREAD

**Issue by oukunan** [tauri-apps/tauri#9020]
### Describe the bug

Continue from https://github.com/tauri-apps/tauri/issues/8987

Is it possible that Tauri will be able to download the new update from the _**private GitHub**_ repository? and how?

### Expected behavior

Expect to able to update the new version of the application from the **_private GitHub_** repository without error 404

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.0.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.74.0 (79e9716c9 2023-11-13)
    ✔ cargo: 1.74.0 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 16.15.1
    - pnpm: 8.11.0
    - yarn: 1.22.17
    - npm: 9.6.1

[-] Packages
    - tauri [RUST]: 1.5.3
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.6
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.7 (outdated, latest: 1.5.10)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by amrbashir** [comment]
it can't, you have to make the updater endpoint public or maybe setting a `Authorization` header with your token using https://docs.rs/tauri/latest/tauri/updater/struct.UpdateBuilder.html#method.header so github would provide content to the updater.
