### ISSUE TITLE
[bug] cargo install tauri-cli fails due to log 0.4.21 update

### ISSUE THREAD

**Issue by FabianLars** [tauri-apps/tauri#9026]
### Describe the bug

there was a new `log` patch release a few hours ago which removed the Value.to_str api. Compare https://docs.rs/log/0.4.21/log/kv/struct.Value.html with https://docs.rs/log/0.4.20/log/kv/struct.Value.html which results in an error like this one
```
error[E0599]: no method named `to_str` found for struct `log::kv::Value` in the current scope
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-cli-1.5.10/src/lib.rs:132:29
    |
132 |         let action = action.to_str().unwrap();
    |                             ^^^^^^ help: there is a method with a similar name: `to_cow_str`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `tauri-cli` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `tauri-cli v1.5.10`, intermediate artifacts can be found at `/tmp/cargo-installFdAUrt`.
```
(from https://discord.com/channels/616186924390023171/1212539466548510740)

I guess that's what we get for using an unstable feature flag 😅 

Is it possible to remove the unstable api usage somehow? Alternatively, we can just lock `log` to 0.4.20 in the cli of course 🤷 

### Full `tauri info` output

```text
i'm on my phone right now :)
```

**Comment by jfbette** [comment]
Same on my side

**Comment by technusm1** [comment]
same here, tried installing on Ubuntu 22.04. any tips for temporary fixes?

**Comment by FabianLars** [comment]
`cargon install tauri-cli --locked` still works (it's about the --locked flag. It forces cargo to use the version specified in the lockfile, which is still an older version)

**Comment by dravenk** [comment]
I can install it after adding the `--lock`  parameter.
```bash
cargo install tauri-cli --version "^2.0.0-beta" --locked
```
macOS M2: 14.2.1

**Comment by ashokspeelyaal** [comment]
Same here.   And I am able to install after adding the `--lock` parameter

`cargo install tauri-cli --version 2.0.0-beta.6 --locked`

**Comment by bartekc7** [comment]
Not work on Windows
error[E0599]: no method named `to_str` found for struct `log::kv::Value` in the current scope
   --> ......\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-cli-2.0.0-beta.6\src\lib.rs:209:29

**Comment by davidclevenger** [comment]
Why is Tauri using an unstable feature flag in production? I'm new and can't even spin up the default app.

**Comment by amrbashir** [comment]
@davidclevenger sorry for the inconvenience, this has been fixed for the next release, for now just add `--locked` flag.
