### ISSUE TITLE
[bug] Encoding bug in the liscense page of nsis

### ISSUE THREAD

**Issue by Yuxiza** [tauri-apps/tauri#9031]
### Describe the bug

I'm in system language Chinese. When adding liscence file to the nsis intaller, I'm having an encoding issue in the liscense page.
This looks like an encoding conversion issue between `gbk` and `utf-8`.
![53f3b2e5a07aad1c6a0695ccd95448c3](https://github.com/tauri-apps/tauri/assets/87649577/9620c963-ab77-4d54-8628-1f547d70d69c)
Thank you for your attention.

### Reproduction

* Set the system language to Chinese (I have not test English or otherwise yet)
* Add some Utf-8 characters in the license file
* bundle and run

### Expected behavior

Display utf-8 characters correctly

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 122.0.2365.52
    ✔ MSVC: Visual Studio 生成工具 2022
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.11.1
    - pnpm: 8.15.4
    - yarn: 1.22.19
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.8
    - tauri-build [RUST]: 2.0.0-beta.6
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.1
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-beta.6

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../prosit
    - devUrl: http://localhost:3001/
    - bundler: Vite
```

**Comment by laozl** [comment]
使用带bom的utf-8格式就行了.
![微信截图_20240612170745](https://github.com/tauri-apps/tauri/assets/43659166/c8d52ff2-7340-4747-ba3c-4e3869abf061)

**Comment by blizzardzheng** [comment]
how to use it in mac, like not work by only boom
