### ISSUE TITLE
[bug] [macOS] Emit works on 2.0.0-beta.4 but breaks in 2.0.0-beta.8

### ISSUE THREAD

**Issue by venkr** [tauri-apps/tauri#9052]
### Describe the bug

We're unable to listen to receive `emit` events in built apps from a Webview beyond 2.0.0-beta.4. Specifically, we've got a working project with the following dependencies in the `.lock`:
tauri: `2.0.0-beta.4`
"tauri-build": `2.0.-beta.3`

A change that runs `cargo update`, and does the relevant `capabilities.json` change (moving `local` & `remote` into `context`) makes this no longer work on the following version:
tauri: `2.0.0-beta.8`
"tauri-build": `2.0.-beta.6`

The event is being sent to `Any` and listened globally via JS, via `emit` and `listen`. This is all re: macOS.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 13.5.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.10.0
    - pnpm: 8.11.0
    - yarn: 1.22.19
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 2.0.0-beta.4
    - tauri-build [RUST]: 2.0.0-beta.3
    - wry [RUST]: 0.36.0
    - tao [RUST]: 0.26.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.0
    - @tauri-apps/cli [NPM]: 2.0.0-beta.3

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: http://localhost:5173/
    - devUrl: http://localhost:5173/
    - framework: React
    - bundler: Vite
```

**Comment by martpie** [comment]
I have faced this issue today as well and solved it using `import { listen } from '@tauri-apps/api/event';`.

But indeed, `getCurrent().listen(...)` seems to not be working.

**Comment by venkr** [comment]
> I have faced this issue today as well and solved it using `import { listen } from '@tauri-apps/api/event';`.
> 
> But indeed, `getCurrent().listen(...)` seems to not be working.

Interesting - we've always used `import { listen, UnlistenFn } from '@tauri-apps/api/event'` +  ` await listen()`
So it looks like what worked for you somehow still broke for us 🤔

**Comment by amrbashir** [comment]
could you share a minimal repro?

**Comment by venkr** [comment]
I'm no longer able to repro this in Tauri 2.0.0-beta.11
