### ISSUE TITLE
[feat] Can the fs provide an isDirectory method?

### ISSUE THREAD

**Issue by s3xysteak** [tauri-apps/tauri#9061]
### Describe the problem

I am using v1. Can the `fs` provide an `isDirectory` method?
```ts
declare async funtion isDirectory(path: string): Promise<boolean>
```

### Describe the solution you'd like

I have implemented a rust method myself to solve the problem temporarily.
```rs
fn is_directory(path: &str) -> Result<bool, String> {
    if let Ok(metadata) = fs::metadata(path) {
        Ok(metadata.is_dir())
    } else {
        Err("is_directory throw a error. Invalid path or cannot find path.".to_string())
    }
}
```
```ts
export async function isDirectory(path: string) {
  const res = await invoke('is_directory', { path })
  return res as boolean | string
}
```
Can you provide a official function `isDirectory` ? Thank you !

**Comment by FabianLars** [comment]
I'm not sure whether we'll add this function specifically but either way in v2 there's a js api to get the metadata, including the isDir property (https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/fs/guest-js/index.ts#L88) and v1 has the fs-extra plugin doing the same though maybe we should merge that into core since it does nothing else than that...

**Comment by amrbashir** [comment]
> maybe we should merge that into core since it does nothing else than that...

the v2 API or v1? and any reason not to recommend using the plugins?

**Comment by s3xysteak** [comment]
To the best of my knowledge, fs-extra is based on Node.js, but in Tauri, access to the os paths is done through Rust. Would this work? I hope that after building, my Tauri app can also access os paths.

**Comment by amrbashir** [comment]
sorry for the confusion we have an `fs-extra` plugin for tauri that is not the same as the Node.js pacakge, you can find it here https://github.com/tauri-apps/plugins-workspace/tree/v1/plugins/fs-extra

**Comment by amrbashir** [comment]
and in v2, we have moved the fs APIs into its own plugins, that can be found here https://github.com/tauri-apps/plugins-workspace/tree/v2/plugins/fs

**Comment by s3xysteak** [comment]
Thank you! That looks great!
