### ISSUE TITLE
[bug] tauri-build build script always rebuild, again

### ISSUE THREAD

**Issue by CrendKing** [tauri-apps/tauri#9062]
### Describe the bug

A while ago, I reported https://github.com/tauri-apps/tauri/issues/8721, that `cargo build` always rebuilds even nothing changes, which is caused by an unconditional `cargo:rerun-if-changed`. After it been fixed, everything worked fine for a while, until the recent beta versions, where the issue happens again. I have no easy suspicion as to where it comes from this time, but since the biggest change in beta is the capability system, it could be a lead.

### Reproduction

1. Create an example app with `pnpm create tauri-app --beta`
2. `cd ./src-tauri`
3. `cargo build`
4. After it successfully builds, `cargo build` again

### Expected behavior

The final executable should not be rebuilt. Instead, I always see a `Building [=======================> ] 360/361: tauri-app(bin)` line.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 122.0.2365.66
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.11.1
    - pnpm: 8.15.4
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.8
    - tauri-build [RUST]: 2.0.0-beta.6
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.1
    - tauri-cli [RUST]: 2.0.0-beta.5
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-beta.6

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

**Comment by altunenes** [comment]
I have same problem, started today. 

```
tauri-build = { version = "2.0.0-rc.2", features = [] }
tauri = { version = "2.0.0-rc.2", features = ["protocol-asset"] }
tauri-plugin-log = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
tauri-plugin-dialog = "=2.0.0-rc.0"
tauri-plugin-http = "2.0.0-rc"
http-range = "0.1.5"
tauri-plugin-os = "=2.0.0-rc.0"
tauri-plugin-fs = "2.0.0-rc.0"
tauri-plugin-process = "2.0.0-rc.0"
tauri-plugin-shell = "2.0.0-rc.0"
```


```
[✔] Environment
    
OS: Windows 10.0.22631 X64
  ✔ WebView2: 127.0.2651.105
  ✔ MSVC:
Visual Studio Build Tools 2019
Visual Studio Community 2022
✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
✔ cargo: 1.80.1 (376290515 2024-07-16)
✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
node: 20.16.0
npm: 10.8.2
[-] Packages
    
tauri [RUST]: 2.0.0-rc.2
tauri-build [RUST]: 2.0.0-rc.2
wry [RUST]: 0.41.0
tao [RUST]: 0.28.1
tauri-cli [RUST]: 2.0.0-rc.3
@tauri-apps/api [NPM]: 2.0.0-rc.0
@tauri-apps/cli [NPM]: 2.0.0-rc.0
[-] App
    
build-type: bundle
CSP: unset
frontendDist: ../dist
devUrl: http://localhost:1420/
framework: React (Next.js)
bundler: Webpack
```

**Comment by altunenes** [comment]
> I have same problem, started today.
> 
> ```
> tauri-build = { version = "2.0.0-rc.2", features = [] }
> tauri = { version = "2.0.0-rc.2", features = ["protocol-asset"] }
> tauri-plugin-log = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
> tauri-plugin-dialog = "=2.0.0-rc.0"
> tauri-plugin-http = "2.0.0-rc"
> http-range = "0.1.5"
> tauri-plugin-os = "=2.0.0-rc.0"
> tauri-plugin-fs = "2.0.0-rc.0"
> tauri-plugin-process = "2.0.0-rc.0"
> tauri-plugin-shell = "2.0.0-rc.0"
> ```
> 
> ```
> [✔] Environment
>     
> OS: Windows 10.0.22631 X64
>   ✔ WebView2: 127.0.2651.105
>   ✔ MSVC:
> Visual Studio Build Tools 2019
> Visual Studio Community 2022
> ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
> ✔ cargo: 1.80.1 (376290515 2024-07-16)
> ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
> ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
> node: 20.16.0
> npm: 10.8.2
> [-] Packages
>     
> tauri [RUST]: 2.0.0-rc.2
> tauri-build [RUST]: 2.0.0-rc.2
> wry [RUST]: 0.41.0
> tao [RUST]: 0.28.1
> tauri-cli [RUST]: 2.0.0-rc.3
> @tauri-apps/api [NPM]: 2.0.0-rc.0
> @tauri-apps/cli [NPM]: 2.0.0-rc.0
> [-] App
>     
> build-type: bundle
> CSP: unset
> frontendDist: ../dist
> devUrl: http://localhost:1420/
> framework: React (Next.js)
> bundler: Webpack
> ```

fixed on here:
https://discord.com/channels/616186924390023171/1275163919492841503
