### ISSUE TITLE
no method named `get_window` found for mutable reference `&mut tauri::App` in the current scope

### ISSUE THREAD

**Issue by NoahCodeGG** [tauri-apps/tauri#9080]
### Describe the bug

this is my code:
```rust
// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use tauri_plugin_log::{Target, TargetKind};
use tauri::Manager;

fn main() {
  tauri::Builder::default()
    .setup(|app| {
      #[cfg(debug_assertions)]
      {
        let window = app.get_window("main").unwrap();
        window.open_devtools();
      }
      Ok(())
    })
    .plugin(tauri_plugin_fs::init())
    .plugin(tauri_plugin_os::init())
    .plugin(tauri_plugin_persisted_scope::init())
    .plugin(tauri_plugin_shell::init())
    .plugin(tauri_plugin_store::Builder::default().build())
    .plugin(tauri_plugin_websocket::init())
    .plugin(tauri_plugin_log::Builder::new().targets([
      Target::new(TargetKind::Stdout),
      Target::new(TargetKind::LogDir { file_name: None }),
      Target::new(TargetKind::Webview),
    ]).build())
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}

```
![CleanShot 2024-03-05 at 11 51 46@2x](https://github.com/tauri-apps/tauri/assets/51156988/c2658ea7-c0ad-404d-87c3-16799fb38add)

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.3.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 21.6.2
    - pnpm: 8.15.4
    - yarn: 1.22.21
    - npm: 10.2.4
    - bun: 1.0.30

[-] Packages
    - tauri [RUST]: 2.0.0-beta.8
    - tauri-build [RUST]: 2.0.0-beta.6
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.3
    - @tauri-apps/cli [NPM]: 2.0.0-beta.6

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: SolidJS
    - bundler: Vite
```

**Comment by FabianLars** [comment]
In v2 it's called `get_webview_window()` now :)

**Comment by Xiaobaishushu25** [comment]
> In v2 it's called `get_webview_window()` now :)

hello，i find use https://docs.rs/tauri-plugin-window-state/2.0.0-beta.6/tauri_plugin_window_state/index.html must use `Window` type,but `get_webview_window()` return type is `WebviewWindow`, and any method in `WebviewWindow` to get `Window` must enable `unstable` feature,but there is some problem https://github.com/tauri-apps/tauri/issues/9634, Is there any solution?

**Comment by FabianLars** [comment]
Hmm, that's an issue with the plugin then. It should be implemented to WebviewWindow too... Could you open an issue in the plugins-workspace repo about this? (i'm out of office right now)

**Comment by tcout** [comment]
> ### Describe the bug
> this is my code:
> 
> ```rust
> // Prevents additional console window on Windows in release, DO NOT REMOVE!!
> #![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]
> 
> use tauri_plugin_log::{Target, TargetKind};
> use tauri::Manager;
> 
> fn main() {
>   tauri::Builder::default()
>     .setup(|app| {
>       #[cfg(debug_assertions)]
>       {
>         let window = app.get_window("main").unwrap();
>         window.open_devtools();
>       }


try
` if let Some(window) = app.app_handle().get_webview_window("main") {
                            window.open_devtools();
}`

**Comment by davidhooey** [comment]
Is the documentation example in `2.8.2` incorrect? https://docs.rs/tauri/2.8.2/tauri/struct.Builder.html#method.setup. It states to use

```rust
use tauri::Manager;
tauri::Builder::default()
  .setup(|app| {
    let main_window = app.get_window("main").unwrap();
    main_window.set_title("Tauri!")?;
    Ok(())
  });
```

**Comment by FabianLars** [comment]
it's not completely incorrect since get_window still exists as part of the `unstable` feature but it's indeed meant to use `get_webview_window` there, yes.
