### ISSUE TITLE
[bug] Install tauri-cli failed

### ISSUE THREAD

**Issue by trookie2000** [tauri-apps/tauri#9098]
### Describe the bug

I installed it in a virtual machine with 8 gigabytes of RAM(Windows 10)
"cargo install tauri-cli --locked" also doesn't work.
![af57aec9d28a1a22e64f374ad77b961](https://github.com/tauri-apps/tauri/assets/109945614/e5b1dd14-3341-48eb-8a54-42afeaa78dd3)

![c9dc321004bcec92eabc2e19fc2665d](https://github.com/tauri-apps/tauri/assets/109945614/44489f78-8793-45b2-8906-6c7552529a7e)
![c41ed9e3a85e2bc19d2cb1c2d35f45e](https://github.com/tauri-apps/tauri/assets/109945614/c1348b59-c94d-483d-87f2-9a6703faae7f)

### Reproduction

cargo install tauri-cli --locked

### Full `tauri info` output

```text
Unable to install
```

**Comment by FabianLars** [comment]
As far as i know, the `ring` crate can only be compiled with the msvc toolchain on windows ([ref](https://github.com/briansmith/ring/blob/main/BUILDING.md)) while you're using the gnu toolchain.

Is it possible for you to switch toolchains? If you used rustup to install rustup it can be done via `rustup default stable-msvc` but it requires you to follow this part of the guide: https://tauri.app/v1/guides/getting-started/prerequisites#1-microsoft-visual-studio-c-build-tools.

If not then, assuming i interpreted ring's docs correctly, you'll have to get tauri's cli via other means, like using the npm package, using [cargo-binstall](https://github.com/cargo-bins/cargo-binstall), or just downloading the exe from [here](https://github.com/tauri-apps/tauri/releases/tag/tauri-cli-v1.5.10) into a folder that's part of the $PATH env.

**Comment by trookie2000** [comment]
After following the instructions> https://tauri.app/v1/guides/getting-started/prerequisites#1-microsoft-visual-studio-c-build-tools, reinstall，An error has occurred.
![cb5d6caacee75e91bc5ef059e317de6](https://github.com/tauri-apps/tauri/assets/109945614/63be67a1-eceb-4bc8-9be5-bd364a6a66e5)
![1e4ccbcb1284e4d2004fab4c556fa99](https://github.com/tauri-apps/tauri/assets/109945614/fe56af6e-5280-417b-a13d-f468d97d4a61)
![09d12accd3b63a7562cbf604e5b3c30](https://github.com/tauri-apps/tauri/assets/109945614/a8c207d6-996d-4ed7-9db8-eded39c71f2e)

**Comment by FabianLars** [comment]
Can you post the output of `rustup show` please? It's still using the gnu toolchain in your screenshots.

**Comment by trookie2000** [comment]
Problem resolved

**Comment by trookie2000** [comment]
Thanks~

**Comment by MrDebugger** [comment]
yo bro, how do you solve it. 
You should be posting the solution not just saying PROBLEM SOLVED

🤦
