### ISSUE TITLE
Wrong open and save dialogs promise resolve type

### ISSUE THREAD

**Issue by olegshilov** [tauri-apps/tauri#910]
Hello. I have a guess that the wrong type is being used here.
https://github.com/tauri-apps/tauri/blob/660a2d87d6acf0abf6be70c01e6402cb5aba96c7/cli/tauri.js/api-src/dialog.ts#L22 and here https://github.com/tauri-apps/tauri/blob/660a2d87d6acf0abf6be70c01e6402cb5aba96c7/cli/tauri.js/api-src/dialog.ts#L41
And i think promise must resolves to `string` not `String`.
I can create a PR if my opinion is correct.

**Comment by Laegel** [comment]
Hey @olegshilov ! You're right, it should be `string`. PR is welcome. :)
