### ISSUE TITLE
-bash: awk: No such file or directory when running a setup command from WSL 2 Setup

### ISSUE THREAD

**Issue by johncaling40** [tauri-apps/tauri#911]
**Describe the bug**
When i run `export DISPLAY=$(/etc/resolv.conf < awk '/nameserver/ {print $2}'):0` from [https://tauri.studio/en/docs/get-started/setup-linux#wsl-version-2](this) setup page, I get `-bash: awk: No such file or directory`. 

**To Reproduce**
1. Install Ubuntu in WSL 2. 
2. Follow all the commands on [https://tauri.studio/en/docs/getting-started/setup-linu](Linux setup page) until you get error at WSL 2 export command

**Expected behavior**
You will get error `-bash: awk: No such file or directory`. 
**Screenshots**
![Screenshot (867)](https://user-images.githubusercontent.com/68033547/89082893-5b92fb80-d35d-11ea-9d78-1791130d24ec.png)

**Platform and Versions (please complete the following information):**

OS: Windows 10 2004 and WSL 2
Node: 14.7.0
NPM: 6.14.7
Yarn: 1.22.4
Rustc: 1.45.1

**Additional context**

**Stack Trace**
`-bash: awk: No such file or directory`

**Comment by chippers** [comment]
looks like `awk` isn't installed.  can you check the output of `which -a awk`

**Comment by johncaling40** [comment]
The output is
`/usr/bin/awk`
`/bin/awk`

**Comment by chippers** [comment]
does the `/etc/resolv.conf` file exist?

**Comment by johncaling40** [comment]
yes it does

**Comment by chippers** [comment]
I don't have WSL2 so I can't really test on my own right now.  Maybe I will check it out

**Comment by johncaling40** [comment]
Ok.. thanks

**Comment by nothingismagick** [comment]
I am closing this as not really relevant to tauri, also it is very (more than six months old) stale.

**Comment by tensor-programming** [comment]
Without awk you can run this command `cat /etc/resolv.conf | grep nameserver` and then that will give you something along these lines: `nameserver 172.xx.xx.xx`.  Get that Address and then just `export DISPLAY=172.xx.xx.xx:0`.  Really though you should get `awk`, its useful for almost everything. 

You can also try using `sed` instead, something like this: `export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | sed 's/.* //g'):0`.

Edit: now that I actually look at it, the problem isn't that you don't have `awk` its that command which is mangled and wrong.  The bash command doesn't know how to run properly that way so it causes an error.  This is the one I always use: `export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0`  That said, there are tons of variations on the WSL2 export command.  I've corrected the docs to reflect this problem.
