### ISSUE TITLE
[feat] How to disable window minimization animation

### ISSUE THREAD

**Issue by alindas** [tauri-apps/tauri#9110]
### Describe the problem

How to disable the transition effect of a window that is similar to converging to the taskbar during the minimization process? When minimizing, simply hide the window directly

### Describe the solution you'd like

disable window minimization animation

**Comment by FabianLars** [comment]
Copy pasting my answer from discord:
> This can currently only be set globally on the user's system itself.

> The way to make this work sounds a bit risky too: https://stackoverflow.com/a/6087214. Especially if we look at the docs of SW_SHOWMINIMIZED and compare it with SW_MINIMIZE (what we currently use). It seems to have different activation behavior which will probably be weird for the user (if it behaves as documented).

> Do you know of any gui framework that has an api for this?

**Comment by amrbashir** [comment]
[stackoverflow.com/a/6087214](https://stackoverflow.com/a/6087214) seems like a good solution, we shouldn't include this in tauri though.
