### ISSUE TITLE
[bug] Route mapping error for tauri multi-window

### ISSUE THREAD

**Issue by trookie2000** [tauri-apps/tauri#9118]
### Describe the bug

This is my project directory
![7e189d8c353d8ff37dafea6f01bd8b9](https://github.com/tauri-apps/tauri/assets/109945614/a5bbbe4e-41b1-4475-9044-f6ea6eafdfaf)
Where RemotePanel.vue is the page
![3f82341093701f3c26beb783db3f24b](https://github.com/tauri-apps/tauri/assets/109945614/4bc8cd27-220e-4f25-ba8b-7d107758b31c)
screenOne.vue is the page I want to map through the route
Create the multiwindow code, main.ts code and router.js code as follows
![5b9b6ced8ef49ff6ed961e92fc56c7a](https://github.com/tauri-apps/tauri/assets/109945614/8c0f8700-18e4-40ca-8c4a-187abc5d73a2)
![08f0c31b0eca558619900560a36962c](https://github.com/tauri-apps/tauri/assets/109945614/43760cc8-7266-4f8e-a460-bed38ecc12a8)
![ba2613842e982272b4493171fe7339c](https://github.com/tauri-apps/tauri/assets/109945614/026e3a3a-8f45-4eb6-8f9c-f95c199b62d7)
But now when I click the button, the new window that appears is still the remotePanel.vue page. How do I change my code

### Reproduction

**Remotepanel.vue:**
const remoteDesktop = async () => {
  if (!data.receiverAccount.id || !data.receiverAccount.password) {
    alert("请输入ID和密码");
    return;
  }
  const webview = new WebviewWindow('theUniqueLabel', {
    url: '#/screenOne.vue',
  })

  webview.once('tauri://created', function () {

  })
  webview.once('tauri://error', function (e) {

  })
  **main.ts:**
  import { createApp } from 'vue'
import './style.css'
import App from './App.vue'
import router from './router'
const app = createApp(App)
app.use(router);
app.mount('#app')
**router.js:**
import { createRouter, createWebHashHistory} from 'vue-router';
import screenOne from './components/screenOne.vue';

const routes = [
  // {
  //   path: '/remote-panel',
  //   component: RemotePanel,
  // },
  {
    path: '/screenOne',
    component: screenOne, 
  },
  // 其他路由规则
];

const router = createRouter({
  history: createWebHashHistory(),
  routes,
});

export default router;

### Expected behavior

The screenOne.vue page can be displayed when the blue button is clicked
![e83ba33268045334637726903189289](https://github.com/tauri-apps/tauri/assets/109945614/994a0c3b-9e1a-4129-a50b-6ab22a76ba75)

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 122.0.2365.66
    ✔ MSVC: 
        - Visual Studio Community 2022
        - Visual Studio ���ɹ��� 2022
    ✔ rustc: 1.72.0 (5680fa18f 2023-08-23)
    ✔ cargo: 1.72.0 (103a7ff2e 2023-08-15)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 16.19.1
    - pnpm: 8.6.9
    - yarn: 1.22.19
    - npm: 8.19.3

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - tauri-cli [RUST]: 1.5.10
    - @tauri-apps/api [NPM]: 1.4.0 (outdated, latest: 1.5.3)
    - @tauri-apps/cli [NPM]: 1.5.10

[-] App
    - build-type: bundle
    - CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
    - distDir: ../dist
    - devPath: http://localhost:5173/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by amrbashir** [comment]
I believe you need to specify the url without `.vue` so `new WebvieWindow('unique', { url: '#/screenOne'})`

**Comment by nongyehong** [comment]
I had a similar problem，Take a look at this discussion #9381，The above one doesn't have the correct url set, but mine didn't even create the window

**Comment by iamhw** [comment]
I meet a same problem, and I solved it by following method:
Use `createWebHistory`, Not `createWebHashHistory`
```
  const webview = new WebviewWindow('test', {
    //url: '/#/test',
    url: '/test',
  })
```
