### ISSUE TITLE
[feat] I'm dynamically creating a system tray menu by loading a bundled resource (json).

### ISSUE THREAD

**Issue by PlumpMath** [tauri-apps/tauri#9129]
### Describe the problem

I'm dynamically creating a system tray menu by loading a bundled resource (json). The issue is, as per the method described on [Tauri's resource guide](https://tauri.app/v1/guides/building/resources/), I can't insert something like app.state::<TrayMenuConfig>dynamic_menus into .system_tray(SystemTray::new().with_menu(...)) because .system_tray does not have access to the app data. 

### Describe the solution you'd like

While accessing app.state for json data is permitted elsewhere in the application, it's not allowed in the context of system_tray. 

### Alternatives considered

The code provided is a rough example, and the current workaround involves placing the json file under the non-bundled Tauri app executable. 

### Additional context

I would like to dynamically create the system tray menu without having to place a json file under the executable after bundling.

**Comment by PlumpMath** [comment]
current code.

I also use the tray_json items within .on_system_tray_event.

If I create it with app.state, access to resources gets locked in the setup() part, leaving me no way to access it in .system_tray and .on_system_tray_event.

```
fn main() {
    let tray_json = read_tray_json(); // read json

    // hardcode menu
    let about = CustomMenuItem::new("about".to_string(), "About");
    let hide = CustomMenuItem::new("hide".to_string(), "hide main window");
    let show = CustomMenuItem::new("show".to_string(), "show main window");

    let mut tray_menu = SystemTrayMenu::new()
        .add_item(about)
        .add_native_item(SystemTrayMenuItem::Separator)
        .add_item(hide)
        .add_item(show)
        .add_native_item(SystemTrayMenuItem::Separator);

    // dynamically add menus from json
    for (_, item) in tray_json.menu.iter().enumerate() {
        let menu_item = CustomMenuItem::new(item.name.clone(), item.name.clone());
        tray_menu = tray_menu.add_item(menu_item);
    }

	// hardcode menu
    let quit = CustomMenuItem::new("quit".to_string(), "quit App");

    tray_menu = tray_menu
        .add_native_item(SystemTrayMenuItem::Separator) // separator
        .add_item(quit);


    tauri::Builder::default()
        .system_tray(SystemTray::new().with_menu(tray_menu))

```

**Comment by FabianLars** [comment]
This is supported in v2 (you can register the tray in the setup hook there) but the implementation is vastly different so i don't think we can backport this to v1
