### ISSUE TITLE
Separate Dev and Release Content Security Policies

### ISSUE THREAD

**Issue by zicklag** [tauri-apps/tauri#913]
**Is your feature request related to a problem? Please describe.**
When working on my app with `yarn tauri dev` I need my app to be able to do things like make websocket connections to localhost in order to access the dev server, but when I release the app, I don't need it to be able to do these things. The issue is that there isn't a way to specify different `csp` values for when I'm running `yarn tauri dev` and when I run `yarn tauri build`.

**Describe the solution you'd like**
It would be nice to be able to define a `devCsp` ( maybe a different name ) in my `tauri.conf.json` file that would be used only when running in development mode. ( Differentiating based on debug or release build could also be good enough )

**Describe alternatives you've considered**
Another possibility is for Tauri to automatically add the rules to allow anything to localhost in dev mode, but I think that would be too magical and misleading to the user. It is better to let them be explicit about the permissions for both modes.

**Additional context**
Right now just for the convenience I'm tempted just to leave the csp more lenient and allow localhost connections in my production app so I don't have to keep changing it back and forth during dev, but that isn't good! This is indirectly having a security impact by making it more convenient to be insecure. 😱

**Comment by lucasfernog** [comment]
CSP won't be applied on dev server usage for now (it's too tricky to make a proxy using a custom protocol since it doesn't have headers support). Also, you can define the csp as a meta tag on your own instead of relying on tauri.conf.json > tauri > security > csp.
