### ISSUE TITLE
[feat] option to skip updater even if it's active in configuration

### ISSUE THREAD

**Issue by anatawa12** [tauri-apps/tauri#9134]
### Describe the problem

I use `tauri-apps/tauri-action` to build my tauri app as a ci.
I started to configure auto update for my app and I pushed to github and ci fails with `Error A public key has been found, but no private key. Make sure to set `TAURI_PRIVATE_KEY` environment variable.`.
In the CI, It's intended to not create signature file.

### Describe the solution you'd like

I want some command-line or environment variable option to disable updater bundle

### Alternatives considered

edit tauri configuration but `active` key in tauri configuration file is shared between multiple keys so it requires complicated to edit tauri.toml correctly so I don't want to this.

**Comment by FabianLars** [comment]
This is fixed in v2 where the env var itself will be the trigger.

In v1 you can do `args: -c "{"tauri": {"updater": {"active": false}}}"` to disable the updater in your workflow. (or `tauri build -c "{"tauri": {"updater": {"active": false}}}"` for local use or workflows without tauri-action).

**Comment by jknight** [comment]
> This is fixed in v2 where the env var itself will be the trigger.

Meaning no value for `TAURI_PRIVATE_KEY` will automatically (in v2) make it so active is false ?

**Comment by FabianLars** [comment]
ah shit i didn't have this in mind anymore when https://github.com/tauri-apps/tauri/issues/9883 was worked on. With this we're back to the v1 behavior but with
```yml
args: -c '{"bundle": { "createUpdaterArtifacts": false }}'
```

**Comment by jknight** [comment]
is that the v2 equivalent of active: true/false?

________________________________

**Comment by FabianLars** [comment]
more or less, yes. This tells the bundler (cli) not to create the .sig files etc but it keeps the updater logic itself still enabled (due to its split into a plugin)

**Comment by jeffkni** [comment]
Ok so the answer to the question in this issue, how to 

> "skip updater even if it's active in configuration" 

the official answer is 

1. "Active in the configuration" is no longer a setting in v2 (was: `plugins.updater.active: [true/false]`)
2. Instead, set `bundle.createUpdaterArtifacts` to false either as an arg or in the conf.json file 

Correct ?

**Comment by FabianLars** [comment]
if `skip updater` means `disable the generation of .sig files and archives` (which is what throws the env var error) then yes, correct.
