### ISSUE TITLE
[bug] window overflowing monitor

### ISSUE THREAD

**Issue by thewh1teagle** [tauri-apps/tauri#9140]
### Describe the bug

![image](https://github.com/tauri-apps/tauri/assets/61390950/d0271915-9586-46e4-8fbe-b0d64082fcb0)

```rust
	let window_builder = tauri::WindowBuilder
		::new(app, config::MAIN_WINDOW_LABEL)
		.inner_size(width, height) // 1440.0 x 990.0
		.min_inner_size(config::MIN_WINDOW_WIDTH, config::MIN_WINDOW_HEIGHT) // 250.0 x 250.0
		.decorations(cfg!(target_os = "macos"))
		.center()
		.shadow(true)
		.visible(true)
		.focused(true)
		.resizable(true)
		.title("title");
```

### Reproduction

Not sure. maybe try to set the window to be bigger than monitor?

### Expected behavior

Window should never overflowing monitor size

### Full `tauri info` output

```text
npx tauri info

[✔️] Environment
    - OS: Windows 10.0.22631 X64
    ✔️ WebView2: 122.0.2365.80
    ✔️ MSVC: Visual Studio Community 2022
    ✔️ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔️ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔️ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔️ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.17.1
    - npm: 9.6.7

[-] Packages
    - tauri [RUST]: git+https://github.com/thewh1teagle/tauri?branch=app#830885f45f96169830435a26a06bca724b73450e (2.0.0-beta.6)
    - tauri-build [RUST]: git+https://github.com/thewh1teagle/tauri?branch=app#830885f45f96169830435a26a06bca724b73450e (2.0.0-beta.4)
    - wry [RUST]: git+https://github.com/thewh1teagle/wry?branch=app#784a8556cf8868019ed50a299f1581225f0b0a06 (0.37.0)
    - tao [RUST]: 0.26.0
    - tauri-cli [RUST]: 1.5.9
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-beta.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../src
```

### Additional context

Resizing window on windows is very hard, you need to strive to find the exact point where you can drag and resize the window (left / right / top / bottom)

PC model: Xiaomi redmibook 14 amd ryzen 5 (14-inch FHD Screen with 1920x1080 Resolution)
Display settings has scale to 150%. on 100% scale it's ok.
I think that the problem is that scale_factor doesn't calculated into the size of tauri when creating the window,
because scale factor should handle window scaling

**Comment by amrbashir** [comment]
> ### Expected behavior
> Window should never overflowing monitor size

This is allowed on Windows, and not a bug imo, it is just the native platform behavior.
