### ISSUE TITLE
[bug] [2.0] Wrong `$schema` in `src-tauri/capabilities/main.json`

### ISSUE THREAD

**Issue by Wombosvideo** [tauri-apps/tauri#9143]
### Describe the bug

`src-tauri/capabilities/main.json` gets initialized with a wrong value for `$schema`:
```json
{
  "$schema": "./schemas/desktop-schema.json",
  ...
}
```

### Reproduction

```bash
pnpm create tauri-app --beta
```
```
✔ Project name · test
✔ Choose which language to use for your frontend · TypeScript / JavaScript - (pnpm, yarn, npm, bun)
✔ Choose your package manager · pnpm
✔ Choose your UI template · Svelte - (https://svelte.dev/)
✔ Choose your UI flavor · TypeScript
✔ Would you like to setup the project for mobile as well? · no
```

### Expected behavior

`src-tauri/capabilities/main.json` gets initialized with the right value for `$schema`:
```json
{
  "$schema": "../gen/schemas/desktop-schema.json",
  ...
}
```

### Full `tauri info` output

```text
[✔] Environment
    - OS: Ubuntu 22.04 X64
    ✔ webkit2gtk-4.1: 2.42.5
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.75.0-nightly (1c05d50c8 2023-10-21)
    ✔ cargo: 1.75.0-nightly (8eb8acbb1 2023-10-17)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: nightly-x86_64-unknown-linux-gnu (default)
    - node: 21.7.1
    - pnpm: 8.15.4
    - npm: 10.5.0
    - bun: 1.0.7

[-] Packages
    - tauri [RUST]: 2.0.0-beta.10
    - tauri-build [RUST]: 2.0.0-beta.8
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.4
    - @tauri-apps/cli [NPM]: 2.0.0-beta.8

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

**Comment by StringKe** [comment]
Another example of `... /gen/schemas/desktop-schema.json`, `capabilities` is a mandatory parameter in this json schema, and `capabilities` is not included in the default template provided.

![CleanShot 2024-03-14 at 11 20 26@2x](https://github.com/tauri-apps/tauri/assets/31089228/1528a5fc-21b3-41db-b899-657ab6049a92)
![CleanShot 2024-03-14 at 11 20 44@2x](https://github.com/tauri-apps/tauri/assets/31089228/0534e8bb-3ef4-40fb-99e4-d6d17e1327d3)

**Comment by FabianLars** [comment]
The capabilities field is not required. It's only required if the file resembles that enum variant (enum = the entries of the anyOf array). The default template uses the first variant with the `A single capability file` description.

**Comment by StringKe** [comment]
Understand, in the jetbrains ide family of products there is always a hint that `capabilities` is required, I will give feedback to jetbrains
