### ISSUE TITLE
[bug] plugin http is not work

### ISSUE THREAD

**Issue by GuoJikun** [tauri-apps/tauri#9160]
### Describe the bug

plugin http is not work when i configure it.

tauri.config.json
```json
"plugins": {
    "http": {
      "scope": []
    }
  },
```

![image](https://github.com/tauri-apps/tauri/assets/21582741/60f3d925-1c79-4838-863d-f1c25e4a4764)
![image](https://github.com/tauri-apps/tauri/assets/21582741/830cc871-cd67-4f94-a599-e2dfa3768220)

### Reproduction

1. add plugin http
2. add config
3. pnpm tauri dev

tauri.config.json
```json
"plugins": {
    "http": {
      "scope": []
    }
  },
```

### Expected behavior

The program works.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22635 X64
    ✔ WebView2: 122.0.2365.80
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.16.0
    - pnpm: 8.6.12
    - yarn: 1.22.19
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 2.0.0-beta.11
    - tauri-build [RUST]: 2.0.0-beta.9
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.1
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-beta.9

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by FabianLars** [comment]
https://github.com/tauri-apps/tauri/issues/8769

**Comment by GuoJikun** [comment]
What I want to say is that the documentation on the official website is incorrect and the http plugin needs to be removed or changed.
