### ISSUE TITLE
WebviewWindow opens and immediately closes on Windows.

### ISSUE THREAD

**Issue by Zack-Xb** [tauri-apps/tauri#9176]
### Describe the bug

In our codebase we use `WebviewWindow` to open Wallet Connect windows that the user can use to approve or reject request by external decentralised applications, for example a transaction request. On Mac and Linux this works fine but on Windows this seems very unreliable and I have tried multiple different methods, even coding it again in rust using `WebviewWindowBuilder` and invoking that. This seems to open like a flash in fact the `tauri://created` listener fires but then it immediately closes. This at very rare moments works which I don't understand yet as I tried this on 3 different Windows devices and they all the same OS version.

As for the code this is one of the scenarios in use [here](https://github.com/AvailX/avail-wallet/blob/update-tauri-beta.6/src/services/wallet-connect/WalletConnectManager.ts#L111) in the `onSessionProposal` funciton.

Note: I know there is no `tauri://error` listener and I did add and try it, but it did not log anything. 

Is there anyway this can be overcome as our app is blocked from going on Windows by this.
 

### Reproduction

If you have a tauri app functional on windows with latest tauri version try using WebviewWindow, opening and destroying and see if this performs consistently well.

### Expected behavior

Webview windows to open normally and be closed/destroyed when invoked by user.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 122.0.2365.80
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.11.1
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.11
    - tauri-build [RUST]: 2.0.0-beta.9
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.0
    - tauri-cli [RUST]: 2.0.0-beta.9
    - @tauri-apps/api [NPM]: 2.0.0-beta.5
    - @tauri-apps/cli [NPM]: 2.0.0-beta.9

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ..\dist\
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Additional context

https://discord.com/channels/616186924390023171/1217389307648544838

**Comment by wvq** [comment]
I also have these problem

**Comment by FabianLars** [comment]
A bit of an update, this issue is basically already fixed, we just need to release a new version of wry and use that in tauri (if you wanna test it, try the `wry-git` tauri branch). This however is blocked on https://github.com/tauri-apps/tauri/issues/9199
