### ISSUE TITLE
Allow registering an app as a file handler

### ISSUE THREAD

**Issue by ehhc** [tauri-apps/tauri#918]
Hey there,
i want to develope a simple editor with tauri. Currently i'm wondering how i can react on fileOpenEvents (resp. whether there are even such things..). In Electron i could do the following:
`ipcRenderer.on('open-file', (e, url) => this.openFile(url));` 

Can you tell me what the corresponding tauri way is? 
Thanks in advance

**Comment by ghost** [comment]
did u mean file/directory selection dialog？

**Comment by ehhc** [comment]
No... Imagen i've created my app (it's named 'myCoolApp'). Then i want to right click on a file on my desktop an select 'open with' -> myCoolApp. In that case, somehow the app (after started by the operation system) has to know what to do (in my case open the correct file). With electron you can register the above mentioned open-file-event-handler and react on the open action (by opening the file). 
I want to do that with a tauri app

**Comment by ghost** [comment]
maybe not support yet #544

**Comment by ghost** [comment]
hope this can help you @ehhc 
1. add this in setup:
![image](https://user-images.githubusercontent.com/37654563/89122849-697f8280-d4fd-11ea-810d-8c8d7b637ec6.png)
2. select 'open with' -> my-app
![image](https://user-images.githubusercontent.com/37654563/89122922-ed396f00-d4fd-11ea-845c-b77e2f7d7fcb.png)
3. app will get args
![image](https://user-images.githubusercontent.com/37654563/89122931-fc202180-d4fd-11ea-9024-5004716f5be3.png)

**Comment by nklayman** [comment]
I've updated the title to what I think more closely resembles your problem. If that does't seem accurate to you, let me know.

**Comment by WilliamVenner** [comment]
For Windows, you can do this in the installer. My project has this functionality; here are the relevant blocks of code:

https://github.com/WilliamVenner/gmpublisher/blob/master/src-tauri/msi/msi.wxs#L60-L80

https://github.com/WilliamVenner/gmpublisher/blob/master/src-tauri/msi/msi.wxs#L43-L47

https://github.com/WilliamVenner/gmpublisher/blob/master/src-tauri/tauri.conf.json#L42-L46

Good luck!!

**Comment by jolic** [comment]
> #544

Could you please paste some code how to use this?

**Comment by jolic** [comment]
> hope this can help you @ehhc
> 
> 1. add this in setup:
>    [image]
> 2. select 'open with' -> my-app
>    [image]
> 3. app will get args
>    [image]

Could you please paste some code to see how it could be implemented?

**Comment by JonasKruckenberg** [comment]
> Could you please paste some code to see how it could be implemented?

First of all, this is an old repo (2y), so many things about Tauri have changed in the meantime but the last comment before yours already has code snippets that show exactly how this can be archived. There is nothing new to add here.

**Comment by ehhc** [comment]
@JonasKruckenberg i opend this issue some time ago. So -- at least for me -- it's not relevant anymore. I understand that it still might be relevant for others, but with the solution given by the comment of @WilliamVenner (https://github.com/tauri-apps/tauri/issues/918#issuecomment-840815713) it might be a good idea to close this issue. Should i do it? Or do you contributors want to do it (I'm not sure whether that matters for the githube issue workflow/statistics/whatever)..

**Comment by JonasKruckenberg** [comment]
If this issue is solved for you then feel free to close this issue. One can always create a new issue after all.

**Comment by erguotou520** [comment]
I have the same demand for append `right click to open with` function to my Tauri app.
