### ISSUE TITLE
[bug] wrong window size on multiwindow

### ISSUE THREAD

**Issue by thewh1teagle** [tauri-apps/tauri#9202]
### Describe the bug

I use tauri latest ([ea068c](https://github.com/tauri-apps/tauri/tree/ea0242db4aa6c127d2bb4a2e275000ba47c9e68c))
with multiwebview.
When creating a second window using WindowBuilder and adding webview as child with `auto_resize()`
 the webview doesn't resize when I resize the window,
Also when I attaching event handler to the window itself on resize event I check window.inner_size and it remains the same.

### Reproduction

Create second window with WindowBuilder and add webview as child with auto resize (unstable feature should be enabled)

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 18.19.0
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: git+https://github.com/thewh1teagle/tauri?branch=app-dev#be54cf15f7243c62d615cdc717890017b68e5208 (2.0.0-beta.11)
    - tauri-build [RUST]: no manifest (2.0.0-beta.9, 2.0.0-beta.9)
    - wry [RUST]: git+https://github.com/thewh1teagle/wry?branch=app-dev#4e61fbc733bd6aa685eb3b3148f453e6f441ebc9 (0.37.0)
    - tao [RUST]: 0.26.1
    - tauri-cli [RUST]: 1.5.9
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-beta.9

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../src
```

**Comment by amrbashir** [comment]
I believe fixed in https://github.com/tauri-apps/tauri/pull/9276
