### ISSUE TITLE
[docs] Where is the enum for the recycle bin path under BaseDirectory in the fs module?

### ISSUE THREAD

**Issue by BaxSTAR17** [tauri-apps/tauri#9208]
Currently, I want my app to clean my recycle bin but apparantly removeFile and removeDir doesnt seem to accept a string value for the path but it accepts the BaseDirectory enums in the fs module, Is there one for the Recycle Bin?

**Comment by FabianLars** [comment]
This is seems to be quite complicated to do if we're talking about cross-platform support. Maybe it's better to implement it as a completely seperate tauri plugin using a crate like https://github.com/Byron/trash-rs 🤔 (look at its source code to see why i said it's complicated)

**Comment by amrbashir** [comment]
I think the best way here is to use `trash-rs` crate directly.
