### ISSUE TITLE
[bug] set_closable does not work as expected on macos

### ISSUE THREAD

**Issue by sebhernandezr** [tauri-apps/tauri#9210]
### Describe the bug

`Current tauri version: tauri = { version = "2.0.0-beta.11", features = ["unstable"] }`

I am trying to disable all window buttons/actions of my app (close, miximize, and minimize) when I trigger a command.

This is how I am inicializing the app:

```
tauri::Builder::default()
    .invoke_handler(tauri::generate_handler![
        commands::collection::block,
    ])
    .setup(|app| {
        let width = 1024.;
        let height = 768.;

        let window = WindowBuilder::new(app, "main")
            .inner_size(width, height)
            .build()?;

        let _webview = window.add_child(
            WebviewBuilder::new("main1", tauri::WebviewUrl::App("index.html".into()))
                .auto_resize(),
            LogicalPosition::new(0., 0.),
            LogicalSize::new(width, height),
        )?;

        Ok(())
    })
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
```

And this is how the block command looks like:

```
#[tauri::command]
pub fn block(window: Window) {
    window.set_minimizable(false).unwrap();
    window.set_maximizable(false).unwrap();
    window.set_closable(false).unwrap();
}
```

For some reason, when I set close, miximize, and minimize to false, they don't behave as expected. The three of them don't set to false at the same time. Looks like it depends on the order I call the set methods:
- If I call `set_closable` last, the minimize is vivible.
![image](https://github.com/tauri-apps/tauri/assets/46209454/2e454494-48ad-4e2e-8b0b-abb7572633e3)

- If I call `set_closable` first, the close is vivible.
![image](https://github.com/tauri-apps/tauri/assets/46209454/d31d02ae-d0dd-43dd-ae3d-52d294e361c8)

---

The workaround was to add the closable property when creating the `window`:

```
        let window = WindowBuilder::new(app, "main")
            .inner_size(width, height)
            .closable(false)
            .build()?;
```

And removing the `set_closable` in the command:

```
#[tauri::command]
pub fn block(window: Window) {
    window.set_minimizable(false).unwrap();
    window.set_maximizable(false).unwrap();
}
```

It works this way, however, this is now what I need. I want to call the three setters from the command, and don't set `closable(false)` in the main window during creation.
![image](https://github.com/tauri-apps/tauri/assets/46209454/d93abb00-a2d4-4385-8811-ff11169d7f12)

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.3.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 18.19.1
    - pnpm: 8.15.4
    - npm: 10.5.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.11
    - tauri-build [RUST]: 2.0.0-beta.9
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.1
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-beta.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../../dist/apps/exam-web
    - devUrl: http://localhost:3000/
    - framework: React
    - bundler: Vite
```

**Comment by songjiachao** [comment]
same problem

**Comment by pronebird** [comment]
Turning off all of the options still makes it possible to close or minimize window:

```
"maximizable": false,
"minimizable": false,
"closable": false,
```
