### ISSUE TITLE
[bug] [beta] WindowResized event broken on Mac

### ISSUE THREAD

**Issue by krzykro2** [tauri-apps/tauri#9236]
### Describe the bug

`tauri::WindowEvent::Resized` received through the main run event loop on MacOS never returns the correct size of the window, and instead returns the original size the window was created with.

This is a fairly new regression, not present in the latest alpha versions (I observed it only today when I was upgrading my library dependencies)

### Reproduction

`npm run create-tauri-app --beta`

Replace the `main` function with:

```
fn main() {
    let app = tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(tauri::generate_handler![greet])
        .build(tauri::generate_context!())
        .expect("error while running tauri application");
    app.run(|app_handle, event| {
        match event {
            tauri::RunEvent::WindowEvent { event, .. } => {
                match event {
                    tauri::WindowEvent::Resized(new_size) => {
                        println!("Resized to: {:?}", new_size);
                    },
                    _ => {},
                }
            },
            _ => {},
        }
    });
}
```

### Expected behavior

While resizing the window I should see the console logs of new sizes of the window.

Instead I see this:
![Screenshot from 2024-03-20 12-50-29](https://github.com/tauri-apps/tauri/assets/6817875/180fc5e2-2005-4cdd-8fa0-b86d7364f9ac)

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.3.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (2023-04-05)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 16.20.2
    - yarn: 1.22.19
    - npm: 8.19.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.12
    - tauri-build [RUST]: 2.0.0-beta.10
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.6
    - @tauri-apps/cli [NPM]: 2.0.0-beta.10

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - bundler: Vite
```

### Additional context

Not reproducible on Linux or Windows (where the event is fired with correct data)

**Comment by pewsheen** [comment]
https://github.com/tauri-apps/tauri/blob/7898b601d14ed62053dd24011fabadf31ec1af45/core/tauri-runtime-wry/src/lib.rs#L3913-L3919

Remove `has_children` in line 3918 seems to fix the issue, but I'm not sure what story behinds it 👀 
cc @lucasfernog

**Comment by FabianLars** [comment]
This would break Window.inner_size it for multiwebview windows. I was happy when I found this at first until I realized this...
But still the problem seems to be how we overwrite or inject the WebView/s into the NSView because in tao itself it seems to interact correctly with the NSView (even though its implementation is a bit weird comparing to what others do but maybe that's again because of the WebViews)

**Comment by lucasfernog** [comment]
I'll try fixing this, there's probably a better way to check for multiwebview setups.

**Comment by lucasfernog** [comment]
I feel the check is just wrong, `has_children && webviews.len() == 1` is supposed to mean `is webview window?` but it isn't AFAIK.

**Comment by clouds56** [comment]
Should we keep `webviews.len() > 0` or `!webviews.is_empty()`? I create a new window without webview, it would crash when resizing.
