### ISSUE TITLE
Proposes add in fe. tauri.conf.json min-height and min-width window App

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#924]
**Is your feature request related to a problem? Please describe.**
* Probably it's not a problem, but maybe prevent the crash in future rendering in window app.

**Describe the solution you'd like**
Add min-height and min-width for window parametr in tauri.conf.json

**Additional context**
```json
"window": {
      "title": "app-test1",
      "min-width": "",
      "min-height": "",
      "width": 800,
      "height": 600,
      "resizable": true,
      "fullscreen": false
```

**Comment by nklayman** [comment]
This is added in the dev branch, and will available in the next release.
