### ISSUE TITLE
[feat] 

### ISSUE THREAD

**Issue by yuyao-tal** [tauri-apps/tauri#9247]
### Describe the problem

There is no "SystemTrayHandle" for tauri 2, but it exits in tauri 1. 

### Describe the solution you'd like

Can handle the system tray after app build.

**Comment by FabianLars** [comment]
This is now called [TrayIcon](https://docs.rs/tauri/2.0.0-beta/tauri/tray/struct.TrayIcon.html) and you can get an instance of it for your existing tray via https://docs.rs/tauri/2.0.0-beta/tauri/struct.AppHandle.html#method.tray_by_id

**Comment by Jeffmagma** [comment]
how do you know the id of the tray?

**Comment by FabianLars** [comment]
if you create the tray in rust or js you can create it with `with_id()` (rust) or `options.id` in `new()` (js). If you create it via tauri.conf.json you can also configure the `id` field and if not it will default to `main` (only in the config version, the other apis use random ids)
