### ISSUE TITLE
[Solution]Deb app install but don't open in window correctly or not at all.

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#925]
**Describe the bug**
Created Deb Packages with `yarn tauri build` don't open in linux desktop After install in app-center. Appimage work no problem.

**Platform and Versions (please complete the following information):**

```bash
yarn run v1.22.4
[tauri]: running info

Operating System - Linux(5.4.0-42-generic) - linux/x64

Node.js environment
  Node.js - 14.6.0
  tauri.js - 0.11.1

Rust environment
  rustc - 1.45.0
  cargo - 1.45.0
  tauri-bundler - 0.9.1

Global packages
  NPM - 6.14.6
  yarn - 1.22.4

App
  tauri.rs - 0.9.1
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../build
  devPath - http://localhost:3000
Done in 3.53s.
```

**Solution**
Add to the tauri.conf.json bundle default parameters shortDescription and longDescription fe.

```json
"bundle": {
      "shortDescription": "Tauri App",
      "longDescription": "Tauri app with rust",
```

**Comment by nklayman** [comment]
This bug does not appear to be present any more. If you can still reproduce it, please let me know and I'll reopen this issue.
