### ISSUE TITLE
[feat] build : able to use x86_64-pc-windows-gnu NOT msvc in win11?

### ISSUE THREAD

**Issue by gowy222** [tauri-apps/tauri#9251]
### Describe the problem

Because there is a custom bin related to Go, I hope to use 'x86_64-pc-windows-gnu' consistently.
and Microsoft Visual Studio C++ requires 6 GB of disk space, and the download speed is particularly slow! It doesn't make sense for fast development.

rustup toolchain install x86_64-pc-windows-gnu
rustup toolchain install x86_64-pc-windows-gnu
rustup override set x86_64-pc-windows-gnu
rustup target list
then:
`pnpm tauri build --target x86_64-pc-windows-gnu`
not work at the end stage!

### Describe the solution you'd like

During the 'pnpm create tauri-app' stage, can freely choose to use GNU or MSVC

**Comment by FabianLars** [comment]
you will have to install binutils in mingw but that should be the only requirement iirc, then it should work. If not, please post the error you're seeing.
