### ISSUE TITLE
[bug] window center doesn't consider taskbar position and size

### ISSUE THREAD

**Issue by Legend-Master** [tauri-apps/tauri#9259]
### Describe the bug

Window center doesn't consider task bar position and size

![image](https://github.com/tauri-apps/tauri/assets/68118705/10ba4082-aaec-4f55-aad6-b72760bb6b12)

### Expected behavior

![image](https://github.com/tauri-apps/tauri/assets/68118705/46302ee3-dca1-4d7b-a89a-272178cb3951)

### Full `tauri info` output

```text
Hello world example at current head (7898b601d14ed62053dd24011fabadf31ec1af45)
```

**Comment by amrbashir** [comment]
While this is possible on Windows, Linux is not guaranteed to provide that information and macOS doesn't seem to provide that info at all, so I am leaning towards just leaving this behavior as it should be consistent across platforms.

**Comment by Legend-Master** [comment]
Is it? I think you can do this with Electron (they're using Chromium's implementation I think)

And also [availHeight](https://developer.mozilla.org/en-US/docs/Web/API/Screen/availHeight) is supported on all major browsers years ago

**Comment by amrbashir** [comment]
> I think you can do this with Electron (they're using Chromium's implementation I think)

The only thing I found is that they were calling [`center`](https://developer.apple.com/documentation/appkit/nswindow/1419090-center?language=objc) method on `NSWindow` which we don't call and instead position it manually based on the screen size.

I guess we could just call this method on linux and do manual centering using the workarea of the monitor on Linux and Windows.


> And also [availHeight](https://developer.mozilla.org/en-US/docs/Web/API/Screen/availHeight) is supported on all major browsers years ago

I guess there is a way but I can't find it

**Comment by Legend-Master** [comment]
> The only thing I found is that they were calling [center](https://developer.apple.com/documentation/appkit/nswindow/1419090-center?language=objc) method on NSWindow which we don't call and instead position it manually based on the screen size.

I think [this call](https://github.com/electron/electron/blob/main/shell/browser/native_window_views.cc#L1073) is calling the [Chromium implementation](https://source.chromium.org/chromium/chromium/src/+/main:ui/views/widget/native_widget_aura.cc;drc=8034ad1c8afaabee6720773137fe2976f5e05018;l=459)

> I guess there is a way but I can't find it

I have a debug build of Chromium on my computer right now, I can try to attach a debugger and figure out how they did it, but guess that'll take some time, Chromium's code base is HUGE

Starting point: https://source.chromium.org/chromium/chromium/src/+/main:ui/display/screen.h;l=118;drc=9910d3be894c8f142c977ba1023f30a656bc13fc;bpv=1;bpt=1

**Comment by Legend-Master** [comment]
I think the MacOS API is this one: https://developer.apple.com/documentation/appkit/nsscreen/1388369-visibleframe, found in https://source.chromium.org/chromium/chromium/src/+/main:ui/display/mac/screen_mac.mm;drc=9910d3be894c8f142c977ba1023f30a656bc13fc;l=96

Windows:

> https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-enumdisplaymonitors
> https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmonitorinfow
> https://source.chromium.org/chromium/chromium/src/+/main:ui/display/win/screen_win.cc;drc=9910d3be894c8f142c977ba1023f30a656bc13fc;l=462

The Linux one is tricky though, so many implementations 🤣

![image](https://github.com/tauri-apps/tauri/assets/68118705/307733bb-b75b-4b2f-b392-da247fc84ec5)

**Comment by Legend-Master** [comment]
Maybe we should put `window.center` in `tao`?
