### ISSUE TITLE
vite env  varible doesn't useable

### ISSUE THREAD

**Issue by Zourunfa** [tauri-apps/tauri#9260]
### Describe the bug

i want to use vite env variable when i pnpm dev,but console.log process.env.VITE_BASE_API is undefined

![image](https://github.com/tauri-apps/tauri/assets/51783403/655e96eb-f1f4-41d9-be8a-be735d8e0ce6)

### Expected behavior

console.log   process.env.VITE_BASE_API  is    http://127.0.0.1

### Full `tauri info` output

```text
PS D:\open-source-code\guitar-assits> pnpm dev

> guitar-assits@0.0.0 dev D:\open-source-code\guitar-assits
> vite --mode development

undefined ---process.env
build.terserOptions is specified but build.minify is not set to use Terser. Note Vite now defaults to use esbuild for minification. If you still prefer Terser, set build.minify to "terser".

  VITE v4.4.11  ready in 755 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
```

**Comment by 18o** [comment]
you need restart the tauri dev server after modify `.env` file , hot reload function won't reload the `.env` file.

**Comment by Zourunfa** [comment]
> you need restart the tauri dev server after modify `.env` file , hot reload function won't reload the `.env` file.

I restart ,but not get
![image](https://github.com/tauri-apps/tauri/assets/51783403/726f4c2b-6dd4-42fa-a88e-21a2fdf2d6e9)

**Comment by pewsheen** [comment]
I think this is not related to Tauri but how you using Vite

I found this article may help you fixing the issue [How can I use Vite env variables in vite.config.js?](https://stackoverflow.com/q/66389043)

**Comment by Zourunfa** [comment]
yes,thanks!
