### ISSUE TITLE
[bug] libsoup-3.0-dev is missing from deps on Linux

### ISSUE THREAD

**Issue by pronebird** [tauri-apps/tauri#9275]
### Describe the bug

Hi,

After a lot of issues with CI, I figured that `libsoup-3.0-dev` should be listed as a dependency on https://beta.tauri.app/guides/prerequisites/#linux.

This helped to fix my debian 12 CI installation

### Full `tauri info` output

```text
N/A
```

**Comment by FabianLars** [comment]
Do you still have some of those errors on hand? Libsoup is a direct dependency of webkitgtk so it's generally not required to list it manually.

**Comment by pronebird** [comment]
> Do you still have some of those errors on hand? Libsoup is a direct dependency of webkitgtk so it's generally not required to list it manually.

Yes. This is what we had in our gitlab CI yml file:

> apt update && apt install -yqq protobuf-compiler build-essential git curl wget file libssl-dev libayatana-appindicator3-dev librsvg2-dev nodejs

This is the error that came out:

```
The following warnings were emitted during compilation:
warning: soup3-sys@0.5.0: 
error: failed to run custom build command for `soup3-sys v0.5.0`
Caused by:
  process didn't exit successfully: `/builds/xxx/zzz/target/debug/build/soup3-sys-9f003424d49fdf89/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=LIBSOUP_3.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:warning=
  pkg-config exited with status code 1
  > PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags libsoup-3.0 libsoup-3.0 >= 3.0
  The system library `libsoup-3.0` required by crate `soup3-sys` was not found.
  The file `libsoup-3.0.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
  The PKG_CONFIG_PATH environment variable is not set.
  HINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `libsoup-3.0.pc`.
warning: build failed, waiting for other jobs to finish...
```

**Comment by pronebird** [comment]
> Do you still have some of those errors on hand? Libsoup is a direct dependency of webkitgtk so it's generally not required to list it manually.

Let me double check that. I think I have spotted that the soup was still missing even with webkitgtk installed. I'll get back to you.

**Comment by pronebird** [comment]
@FabianLars it seems that I messed something up and you're right, soup is indeed not needed.

**Comment by pronebird** [comment]
I think I forgot to include `libwebkit2gtk-dev`, this is why the soup was missing. Nevermind.
