### ISSUE TITLE
[feat] When files are found in the installation directory, the installation should be terminated.

### ISSUE THREAD

**Issue by keiko233** [tauri-apps/tauri#9277]
### Describe the problem

In the current NSIS setup, installation is allowed in any user-selected directory. During uninstallation, all files in the current path are removed. If there are additional files present in the selected path, non-program files will also be deleted incidentally.

### Describe the solution you'd like

We can address this issue during installation by checking if the user-selected path contains existing files, thus preventing potential issues during uninstallation.

### Alternatives considered

Perhaps there are alternative and more effective implementations, such as recording the program's files in the registry or exploring other solutions.

### Additional context

I have written a sample code here. If allowed, I would like to initiate a pull request.
here https://github.com/keiko233/tauri/commit/460519ee696bb125876574ac4e10893771855aee
![image](https://github.com/tauri-apps/tauri/assets/76520798/50851bb9-b7d1-46ec-94eb-41102c067784)

associated Links:
https://github.com/LibNyanpasu/clash-nyanpasu/commit/78b18dec1a3b620749607a80078845c6ec7a4c99
https://github.com/LibNyanpasu/clash-nyanpasu/issues/657

**Comment by FabianLars** [comment]
If this is just about the uninstallation we can fix this as i described [here](https://github.com/tauri-apps/tauri/pull/9105#issuecomment-1985348870) instead.

In general i think allowing users to install the app into a not-empty folder is fine but maybe a dialog asking whether they're sure would be nice? 🤔 @amrbashir

**Comment by amrbashir** [comment]
An Ok/Cancel dialog should be fine here

**Comment by amrbashir** [comment]
@keiko233 if you want, please go ahead and open a PR to add a dialog to add an Ok/Cancel dialog

**Comment by keiko233** [comment]
> @keiko233 if you want, please go ahead and open a PR to add a dialog to add an Ok/Cancel dialog

Maybe my problem has been solved. 
https://github.com/tauri-apps/tauri/pull/9282
I will close this issue.

**Comment by linguofeng** [comment]
<img width="431" alt="image" src="https://github.com/tauri-apps/tauri/assets/460328/9800a739-e92f-44f3-bad5-f1448ce04524">

Maybe that makes more sense, rather than having them mixed together 😅
