### ISSUE TITLE
API

### ISSUE THREAD

**Issue by a937983423** [tauri-apps/tauri#9300]
### Describe the bug

    Finished dev [unoptimized + debuginfo] target(s) in 31.27s

** (ai:176907): WARNING **: 15:37:53.779: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.

### Full `tauri info` output

```text
[debian@debian-PC truri]$ cargo tauri info

[✔] Environment
    - OS: EndeavourOS Rolling Release X64
    ✔ webkit2gtk-4.1: 2.44.0
    ✔ rsvg2: 2.58.0
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 21.7.1
    - pnpm: 8.15.2
    - yarn: 1.22.22
    - npm: 10.5.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.13
    - tauri-build [RUST]: 2.0.0-beta.10
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.2
    - tauri-cli [RUST]: 2.0.0-beta.11
    - @tauri-apps/api [NPM]: 2.0.0-beta.5
    - @tauri-apps/cli [NPM]: 2.0.0-beta.11

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
```

**Comment by a937983423** [comment]
Hello development team, may I ask if we can expect Wayland support in version 2.0 for our Linux distribution?

**Comment by FabianLars** [comment]
> webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.

The documentation sadly does not state whether the setting actually did something before 2.44 - i'll try to find some maintainer discussion about this. Thanks for the report!

> Hello development team, may I ask if we can expect Wayland support in version 2.0 for our Linux distribution?

Wayland is supported in both v1 and v2. Only the AppImage distribution format forces X11/XWayland due to gtk crashes like [this one](https://github.com/tauri-apps/tauri/issues/8541) :/

**Comment by oluijks** [comment]
I also have this 'issue' tho it doensn't seem to hurt running and building the app

Setting one of these vars didn't do anything for me

```
WEBKIT_DISABLE_COMPOSITING_MODE=1
WEBKIT_DISABLE_DMABUF_RENDERER=1
```

```
> cargo tauri info       

[✔] Environment
    - OS: Arch Linux Unknown X64
    ✔ webkit2gtk-4.0: 2.44.3
    ✔ rsvg2: 2.58.3
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.16.0
    - pnpm: 9.7.1
    - npm: 10.8.1
    - bun: 1.1.22

[-] Packages
    - tauri [RUST]: 1.7.1
    - tauri-build [RUST]: 1.5.3
    - wry [RUST]: 0.24.10
    - tao [RUST]: 0.16.9
    - tauri-cli [RUST]: 1.6.0
    - @tauri-apps/api [NPM]: 1.6.0
    - @tauri-apps/cli [NPM]: 1.6.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../build
    - devPath: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```
