### ISSUE TITLE
[bug]  v2: Cannot recreate a window

### ISSUE THREAD

**Issue by pronebird** [tauri-apps/tauri#9307]
### Describe the bug

Hi,

I am trying to re-create the main window from a click on tray icon and it seems that it works, but I get the blank window and it seems that the web view doesn't load `index.html`. Is there something I missed or is it a bug? I followed the docs on Tauri v2 beta.

This is my code that runs each time I click the tray icon:

```rs
let win = app_handle
      .get_window("main")
      .map(|win| Ok(win))
      .unwrap_or_else(|| {
          let main_win_config = app_handle.config().app.windows.get(0).unwrap().clone();
          tauri::window::WindowBuilder::from_config(app_handle, &main_win_config)?.build()
      })?;
win.set_position(/* .. */)?;
win.set_focus()?;
```

My `tauri.conf.json` contains the following relevant configuration fields for windows:

```
"app": {
  "windows": [
      {
        "title": "My app",
        "width": 800,
        "height": 600,
      }
    ],
    "security": {
      "csp": null
    }
}
```

### Full `tauri info` output

```text
xx
```

**Comment by amrbashir** [comment]
Seems like you're using tauri v2, and in this case, you're using `WindowBuilder` which will create a window without a webview so either use `WebviewBuilder` to create a webview and add it to the window or use `WebviewWindowBuilder` instead.
