### ISSUE TITLE
[docs] how to enable HTTP requests configuration in Tauri v2.0?

### ISSUE THREAD

**Issue by liliang-cn** [tauri-apps/tauri#9308]
<img width="861" alt="image" src="https://github.com/tauri-apps/tauri/assets/20553741/4b4277d3-447f-4c7a-a7f1-487766441cf8">

but no "dangerousUseHttpScheme" in v2.

**Comment by FabianLars** [comment]
This setting changed the origin of your website from `https://tauri.localhost/` to `http://tauri.localhost` on windows (in v1). In v2 this is now the default, currently without a way to change it back to https.
