### ISSUE TITLE
[feat] Is is possible to control which screen the app window will display on?

### ISSUE THREAD

**Issue by czf0613** [tauri-apps/tauri#9314]
### Describe the problem

I am developing a linux application for a cash register. It has two screens, one will be used to display information to customer, and the other one is designed for the cashier.
I set up two windows in my app to show, but the problem is, these two windows didn't show on different screens as I expected.

### Describe the solution you'd like

Is there any solution to control which screen the app window will display on? I known that it will be difficult since window management is quite different on Windows, macOS and Linux.
If there's no official solution in tauri, please tell me the way to fix it on Linux, that's enough for me. Thanks a million.

**Comment by amrbashir** [comment]
You can go with one of these solutions:
1. create the window programmatically in Rust and use [`available_monitors`](https://docs.rs/tauri/latest/tauri/window/struct.Window.html#method.available_monitors) to determine where to position the window
2. create the window in tauri.conf.json but re-position it inside `.setup()` hook, you will also need to use [`available_monitors`](https://docs.rs/tauri/latest/tauri/window/struct.Window.html#method.available_monitors) to determine where to position the window
3. You can use `tauri-plugin-window-state` and in the first time you open your app, position the window manually as you like and subsequent opens will restore your windows automatically.

**Comment by czf0613** [comment]
Thanks
