### ISSUE TITLE
[docs] About Tauri2.0 document defects

### ISSUE THREAD

**Issue by lindongchen** [tauri-apps/tauri#9321]
[Tauri2.0]
The overall feeling of the document is that it is a lot outdated,
The API and plugins are very obvious,
Of course, these are not the most urgent,
You can find the correct definition through the source code.

However, some configurations pose significant obstacles in development,
For example, **capabilities/main.json**
There are many functions that must be unlocked through **permissions** configuration,
Especially the structure of **allow** is not explicitly stated
Eg:
**{
"Identifier": "http: allow match",
"Allow":[“ http://127.0.0.1: */*]
},**
Hope it can be announced as soon as possible

**Comment by lindongchen** [comment]
Another question
[peimissons]
os:allow-hostname

[lib.rs]
.plugin(tauri_plugin_os::init())

[usage]
 import { hostname } from '@tauri-apps/plugin-os';
 const hostname = await hostname();

[error]
**Unhandled Promise Rejection: ReferenceError: Cannot access uninitialized variable.**

I have tried '@tauri-apps/plugin-os' other commands and they are available, only the **hostname** reported an error

**Comment by amrbashir** [comment]
We are aware of the documentation lacking for v2 and we will definitely be working on it before releasing v2 stable.

**Comment by amrbashir** [comment]
> Another question [peimissons] os:allow-hostname
> 
> [lib.rs] .plugin(tauri_plugin_os::init())
> 
> [usage] import { hostname } from '@tauri-apps/plugin-os'; const hostname = await hostname();
> 
> [error] **Unhandled Promise Rejection: ReferenceError: Cannot access uninitialized variable.**
> 
> I have tried '@tauri-apps/plugin-os' other commands and they are available, only the **hostname** reported an error

try this instead
```ts
import { hostname } from '@tauri-apps/plugin-os';
const host = await hostname();
```
