### ISSUE TITLE
Is there a way to detect running inside Tauri?

### ISSUE THREAD

**Issue by rnons** [tauri-apps/tauri#933]
**Is your feature request related to a problem? Please describe.**
I want my app to work in both normal browsers and Tauri. When running inside Tauri, I use Tauri's HTTP api. When running inside normal browsers, I use a proxy server to work around CORS. So I need a mechanism to detect if I'm running inside Tauri.

**Describe the solution you'd like**
A possible solution is including `Tauri` in the `navigator.userAgent`. 
What's better is providing an API, for example `import { isTauriOn } from 'tauri/api/tauri'`, so that the implementation detail is hidden from a user and a user doesn't need to rely on UA string.

Edit: It's also good to allow user overriding UA string in `Cargo.toml` or somewhere.

**Comment by zicklag** [comment]
I'm doing the same thing with my web application and a super easy way to detect running inside of Tauri is just to do:

```js
const isTauri = !!window.__TAURI_INVOKE_HANDLER__;
```

Maybe there could be a nicer API around it, but that works nicely.

**Comment by nklayman** [comment]
`!!window.__TAURI__` works as well and is a bit shorter. I think this is a plenty good indicator for determining if you are running inside Tauri, so I'm closing this issue.
