### ISSUE TITLE
[bug] System tray icon gets blurry on Windows after changing system UI scaling

### ISSUE THREAD

**Issue by Legend-Master** [tauri-apps/tauri#9335]
### Describe the bug

System tray icon gets blurry on Windows after changing system UI scaling

### Reproduction

Go to settings and change system UI scaling to 175% and change it back to 100%, you can do it multiple times to make the icon even more blurry

### Expected behavior

Not blurry

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 123.0.2420.65
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.10.0
    - pnpm: 8.15.4
    - npm: 10.5.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.13
    - tauri-build [RUST]: 2.0.0-beta.10
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.2
    - @tauri-apps/api [NPM]: 2.0.0-beta.6
    - @tauri-apps/cli [NPM]: 2.0.0-beta.11

[-] App
    - build-type: bundle
    - CSP: connect-src ipc: http://ipc.localhost ws: localhost:* 127.0.0.1:*
    - frontendDist: ../dist
    - devUrl: http://localhost:3000/
    - framework: SolidJS
    - bundler: Vite
```

**Comment by amrbashir** [comment]
This doesn't seem like a bug at all but rather the icon size is not optimal, I am using a 32x32 icon and here is how it looks:
1. 100% scaling

	![image](https://github.com/tauri-apps/tauri/assets/48618675/5e977f72-3f04-4cdb-bb50-8b5c6a5f4ad3)
	
2. 175% scaling
  
	![image](https://github.com/tauri-apps/tauri/assets/48618675/9bf70c4c-6f28-48b4-aae2-dc38e8122219)


I also included 3 icons of electron apps that I use and they are more blurry than the icon I used

**Comment by Legend-Master** [comment]
I mean it's blurry after you switch back from 175% to 100%, here's a screen shots for comparison

Initial state

![image](https://github.com/tauri-apps/tauri/assets/68118705/6ab996c6-b180-4d62-818b-28931a9c45e7)

After going back and forward a few times

![image](https://github.com/tauri-apps/tauri/assets/68118705/6e61e532-3dc6-45f3-9c62-7a49220342ca)

**Comment by amrbashir** [comment]
I can reproduce now, seems like it happens when there is at least one Window open, and works fine if no windows are open at all. Seems like changing the display scaling makes the window unresponsive (@Legend-Master can you confirm this too?) and it somehow affects the tray icon.

**Comment by Legend-Master** [comment]
My window is fine though, I can interact with it just fine after changing the scaling

**Comment by amrbashir** [comment]
That's weird, I will investigate later. I should also mention although I get a slightly blurier (or rather more pixelated) icon than the original, it is not the same as what your image shows. This is a tough one to debug.

**Comment by Legend-Master** [comment]
I did maybe 4-5 times, and the icon used was https://github.com/tauri-apps/tauri/blob/dev/examples/.icons/icon.ico

**Comment by amrbashir** [comment]
I was using https://github.com/tauri-apps/tauri/blob/dev/examples/.icons/32x32.png can you see how this one behaves?

**Comment by Legend-Master** [comment]
I'll give it a try now

**Comment by Legend-Master** [comment]
https://github.com/tauri-apps/tauri/blob/dev/examples/.icons/32x32.png after 3 times: ![image](https://github.com/tauri-apps/tauri/assets/68118705/26e46b99-1da3-4d19-be63-12b62fd31af4)

I'm on Window 10 by the way

**Comment by amrbashir** [comment]
I guess the blurriness are not consistent across machines or rather across Windows versions as I am using Windows 11.
