### ISSUE TITLE
[Feature] Resurrect MSHTML Backend

### ISSUE THREAD

**Issue by zicklag** [tauri-apps/tauri#934]
**Is your feature request related to a problem? Please describe.**
I want to produce Windows executables for my Tauri application but I have two issues with the current state of windows support:

- I can't cross-compile for Windows from Linux ( more rationale behind that here: https://github.com/webview/webview_rust/issues/48 )
- Windows support seems sketchy and potentially requires extra dlls manually installed or otherwise necessitates an MSI. I would like to have just one exe. ( some extra reference [here](https://github.com/jwenjian/lucky-you/releases/tag/v1.1.1). A big warning needed to say, watch out if you are on Windows! )

**Describe the solution you'd like**
I would like to build my Tauri application using the MSHTML backend like you used to be able to do with the older version of webview and the boscop Rust bindings.

**Describe alternatives you've considered**
For now I'll probably just go with using GitHub actions to compile the MSI's for Tauri, but I've been reluctant because when I copied the Tauri GitHub Action template for my repo, the first build ( which took 24+ minutes ) turned out a file that windows said wasn't an executable file. I could try to troubleshoot and fix it, but the issue is that with builds taking so long and with no Windows machine on which to build my app, troubleshooting is going to take a lot of time and will be frustrating.

**Additional context**
I was thinking about trying to port the MSHTML code from the old version of Webview to the new version, but I don't know C and there's quite a bit of code for how little I know about it so that probably wouldn't go well. I also considered trying to make a drop-in replacement for `webview_official` that just uses bosscop's `web-view` in the backend, but they have different APIs so I don't think that would go particularly well either.

**Comment by zicklag** [comment]
Being that I was unfortunately unable to compile my application with IE 11 support ( 😕) that means this isn't as high priority to me personally anymore.

**Comment by nklayman** [comment]
We have decided that future versions of Tauri will exclusively use [WebView2](https://developer.microsoft.com/en-us/microsoft-edge/webview2/), which supports windows 7-10, so I'll close this. Unfortunately, cross-compilation will not be available for the near future.

**Comment by zicklag** [comment]
Yay, that's awesome! :tada:
