### ISSUE TITLE
[feat] Is there any way to detect url changing in webview on Tauri app?

### ISSUE THREAD

**Issue by gusxodnjs** [tauri-apps/tauri#9340]
### Describe the problem

Can I detect an event in rust or js environment where url in webview changes?
I am using the latest version of tauri.
thanks.

### Describe the solution you'd like

Support event when url in window changes
https://tauri.app/v1/api/js/event

**Comment by FabianLars** [comment]
Does <https://docs.rs/tauri/latest/tauri/window/struct.WindowBuilder.html#method.on_navigation> work for you? As its name suggests it requires navigation intent so a non-navigation change of the `#` part will probably not trigger it.

There does not seem to be a more extensive webview api we could use here.

To detect href changes that don't navigate, something like this may work <https://stackoverflow.com/a/46428962> (this one in particular is basically just polling but a bit more fancy)
