### ISSUE TITLE
tauri v2 uses https://asset.localhost net::ERR_CONNECTION_REFUSED[bug] 

### ISSUE THREAD

**Issue by heiyehk** [tauri-apps/tauri#9359]
### Describe the bug

I got this error while using https://asset.localhost in tauri v2.

```
GET https://asset.localhost/D:/xxx.jpg net::ERR_CONNECTION_REFUSED
```
But it is displayed normally in v1.

Is this a bug? Or are there other ways to handle it?

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 123.0.2420.65
    ✔ MSVC: Visual Studio Enterprise 2022
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.9.0
    - pnpm: 8.15.4
    - yarn: 1.22.22
    - npm: 10.1.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.13
    - tauri-build [RUST]: 2.0.0-beta.10
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.6
    - @tauri-apps/cli [NPM]: 2.0.0-beta.10

[-] App
    - build-type: bundle
    - CSP: default-src 'self'; script-src 'self' 'unsafe-eval' 'sha256-f2aYrerT20WDJlPe3kdN3JfQlyKoRxP33xkWfDbeO9I=' 'sha256-GFebPxKzs1UkFRCbyMaykyYD7rGVWnt1zk1m6r+ZTWQ=' 'sha256-iUqSk0LHeoYfdwsQNbveDMYkU7Tq/OmyauSlE3snBuc='; style-src 'self' 'unsafe-inline'; connect-src ipc.localhost localhost ws:; img-src http: https: data: asset: https://asset.localhost
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by FabianLars** [comment]
In v2 it's http now (instead of https) (i'd recommend using convertFileSrc so that you don't have to worry about that, or platform differences). Can you try that? If that also doesn't work, please share your scope config.

**Comment by heiyehk** [comment]
@FabianLars I tried `convertFileSrc`, but it didn't work, still `net::ERR_CONNECTION_REFUSED`. I didn't do any other configuration except `scp`.

**Comment by FabianLars** [comment]
That shouldn't have been enough for v1 either. In v1 there was a scope config on allowlist.
In v2, the asset scope is the only thing that still has a traditional scope (i hope we can move that into the ACL too before stable), but it was moved next to the csp config in app.security: https://github.com/tauri-apps/tauri/blob/dev/examples/api/src-tauri/tauri.conf.json#L30-L36

**Comment by heiyehk** [comment]
@FabianLars I did it, thank you very much! I think it is caused by not turning on `assetProtocol`.
