### ISSUE TITLE
[bug] Exception in opening DevTools using hotkeys

### ISSUE THREAD

**Issue by fu050409** [tauri-apps/tauri#9383]
### Describe the bug

This issue occurs when I use the `Ctrl`+`Shift`+`I` hotkey, this exception doesn't appear when I don't use hotkeys.

I found a similiar issue in https://github.com/tauri-apps/tauri/issues/8771, it described a issue that the permission name is mismatch, but it looks like an correct name is provided by my devtools.
```
Failed to load resource: the server responded with a status of 400 (Bad Request)
```
on `http://ipc.localhost/plugin%3Awebview%7Cinternal_toggle_devtools`.

```
Uncaught (in promise) webview.internal_toggle_devtools not allowed. Permissions associated with this command: webview:allow-internal-toggle-devtools, webview:default
```
on `VM33:263`.

### Expected behavior

It should be a clean console, this exception seems unnecessary because even with the error occured, my DevTools still started up normally.

### Full `tauri info` output

```text
PS D:\Projects\Moonstone> cargo tauri info         

[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 123.0.2420.65
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.77.0 (aedd173a2 2024-03-17)
    ✔ cargo: 1.77.0 (3fe68eabf 2024-02-29)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 21.6.1
    - pnpm: 8.15.5
    - npm: 10.2.4
    - bun: 1.0.31

[-] Packages
    - tauri [RUST]: 2.0.0-beta.14
    - tauri-build [RUST]: 2.0.0-beta.11
    - wry [RUST]: 0.39.0
    - tao [RUST]: 0.27.0
    - tauri-cli [RUST]: 2.0.0-beta.9
    - @tauri-apps/api [NPM]: 2.0.0-beta.7
    - @tauri-apps/cli [NPM]: 2.0.0-beta.9

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by nongyehong** [comment]
V2 use acl to manage these permissions, maybe you can be in "capabilities/migrated json defined in {permissions: [" webview: allow - internal - toggle - devtools"]}

**Comment by fu050409** [comment]
> V2 use acl to manage these permissions, maybe you can be in "capabilities/migrated json defined in {permissions: [" webview: allow - internal - toggle - devtools"]}

Thanks a lot, this worked :)

Should I add permissions manually eveny time when a new plugin added?

**Comment by FabianLars** [comment]
yep, that's the idea (similar to v1's allowlist). But internal commands like these should typically be part of the :default permission.
