### ISSUE TITLE
[bug] onwheel doesn't work

### ISSUE THREAD

**Issue by wuhuawei1996** [tauri-apps/tauri#9391]
### Describe the bug

The version of Tauri I am using is >=2.0.0-beta. I found that on a laptop touchpad, scrolling with two fingers in opposite directions does not trigger the wheel event; however, it does trigger the event when scrolling in the same direction. I think this might be a bug, since the wheel event is triggered on Edge and Chrome when scrolling with two fingers in opposite directions.

https://github.com/tauri-apps/tauri/assets/22124730/aa901a18-23e5-448f-aec4-bef5a0a89d9b

### Expected behavior

I hope that the wheel event will be triggered when scrolling with two fingers in opposite directions.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 123.0.2420.65
    ✔ MSVC: Visual Studio Build Tools 2019
    ✔ rustc: 1.77.1 (7cf61ebde 2024-03-27)
    ✔ cargo: 1.77.1 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.17.1
    - pnpm: 8.15.4
    - npm: 10.5.1

[-] Packages
    - tauri [RUST]: 2.0.0-beta.14
    - tauri-build [RUST]: 2.0.0-beta.11
    - wry [RUST]: 0.39.0
    - tao [RUST]: 0.27.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.7
    - @tauri-apps/cli [NPM]: 2.0.0-beta.12

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by amrbashir** [comment]
From your video there is two gestures you're doing:
1. `two fingers in same direction`: which is probably configured in your OS to scroll in that direction and translates to `onwheel` event
2. `two fingers in opposite direction` also called `pinch out zoom`: which is probably configured in your OS to zoom out but I don't think there is a native Web event for this gesture, I'd look into using a library like this one https://www.npmjs.com/package/pinch-zoom-js
