### ISSUE TITLE
[bug] v2 A white screen appears when calling show()

### ISSUE THREAD

**Issue by Borber** [tauri-apps/tauri#9393]
### Describe the bug

When I updated to the latest v2 version dependency, I found that when my application called show(), an inevitable white screen appeared.

new dependencies: https://github.com/Borber/Tran

https://github.com/tauri-apps/tauri/assets/30563826/d5b619bc-5da0-46b7-b927-875ebaf9d443

old dependencies: https://github.com/Borber/Tran/tree/old_dependence

https://github.com/tauri-apps/tauri/assets/30563826/641d0fac-f9d9-47ad-949c-a319c3b8efc2

Their code is exactly the same, but the dependency versions are different

### Reproduction

Compile the two codes from different branches above

### Expected behavior

Don’t show a white screen

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19044 X64
    ✔ WebView2: 123.0.2420.65
    ✔ MSVC: Visual Studio 生成工具 2022
    ✔ rustc: 1.79.0-nightly (88c2f4f5f 2024-04-02)
    ✔ cargo: 1.79.0-nightly (a59aba136 2024-03-28)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: nightly-x86_64-pc-windows-msvc (default)
    - node: 20.11.0
    - pnpm: 8.15.6
    - yarn: 1.22.22
    - npm: 10.5.1

[-] Packages
    - tauri [RUST]: 2.0.0-beta.13
    - tauri-build [RUST]: 2.0.0-beta.10
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.2
    - @tauri-apps/api [NPM]: 2.0.0-beta.7
    - @tauri-apps/cli [NPM]: 2.0.0-beta.12

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:5046/
    - framework: SolidJS
    - bundler: Vite
```

### Additional context

Other dependencies basically have nothing to do with windows, so I can only think that it is a bug introduced when Tauri was updated.

**Comment by wuhuawei1996** [comment]
Yeah, I find this bug, too.

**Comment by amrbashir** [comment]
probably a regression introduced in https://github.com/tauri-apps/tauri/pull/9246
