### ISSUE TITLE
[docs] update tauri for next js route app

### ISSUE THREAD

**Issue by FajarFE** [tauri-apps/tauri#9405]
Hello, could you please update Tauri for the Next.js route app? I encountered several errors when setting it up manually, such as Tauri not being related to Cargo.toml and others.

**Comment by FabianLars** [comment]
Can you expand on that a bit?

Do you mean you use nextjs' `pages/` folder instead (or in addition to) the `app/` folder?

Were you aware of our nextjs setup guide? https://tauri.app/v1/guides/getting-started/setup/next-js

**Comment by FajarFE** [comment]
Yes, I have already done so, but when I use the dialog feature in Tauri beta v2, there is an error in Cargo because the version in tauri.toml does not match version 1.4 with cargo.toml because in npm run tauri init has not been updated.
