### ISSUE TITLE
[docs] Providing additional files on macOS

### ISSUE THREAD

**Issue by pronebird** [tauri-apps/tauri#9406]
Hi,

I am trying to bundle a few binaries  built alongside into the `target/release`, this is my configuration:

```
{
  // ... redacted
  "bundle": {
    "macOS": {
      "files": {
        "Resources/binary-a": "../../target/release/binary-a",
        "Resources/binary-b`: "../../target/release/binary-b"
      },
      "minimumSystemVersion": "10.13"
    }
  }
}
```

Please clarify in documentation how to provide a relative path because I don't understand what working directory is being used.

Related PR: https://github.com/tauri-apps/tauri/pull/7798

**Comment by FabianLars** [comment]
All configs should always be relative to the path of the tauri.conf.json file.

**Comment by pronebird** [comment]
Thanks for a quick reply. Somehow that assumption didn't hold for me, maybe I had a typo? Nonetheless, after updating to beta.14 and double checking everything it finally worked.
