### ISSUE TITLE
[feat] Remove UNC prefix from paths returned in public apis

### ISSUE THREAD

**Issue by FabianLars** [tauri-apps/tauri#9407]
### Describe the problem

Currently our APIs (most of them moved to plugins i guess) still return UNC paths on Windows. For those unaware, those paths start with `\\?\`.

Most ecosystems seem to have problems with that, this includes the js frontend but also a multitude of sidecars. We've also already received reports about things built into Windows not being able to handle those.

### Describe the solution you'd like

use dunce everywhere to safely remove the prefix. I doubt that this will cause any issues but even if, it'd be still less than the unc paths cause lol

### Alternatives considered

do nothing and keep blaming the other languages' ecosystems for not being able to handle unc paths.

**Comment by amrbashir** [comment]
you had a typo there

**Comment by amrbashir** [comment]
Do you have a list of APIs that are affected by this? preferably we should leave the Rust APIs as is and only use `dunce` on values returned to JS

**Comment by FabianLars** [comment]
Nope, no list, though i hope we simply return PathBuf's everywhere so it should be easy to spot. I can go through all plugins no problemo, just wanted to have this tracked :)

**Comment by amrbashir** [comment]
yeah we definitely need to get a list ASAP and work on fixing them before v2 stable

**Comment by FabianLars** [comment]
weren't that many apis after all. Either it changed compared to v1 or the complains i received were always about the same 2 apis 😂
