### ISSUE TITLE
Is building on aarch64 supported?

### ISSUE THREAD

**Issue by thomasmarkiewicz** [tauri-apps/tauri#941]
I am running into an "Architecture Error" while trying to build a simple React Tauri app on Librem 5 (aarch64).  Setting up of all tooling up to this point worked, but I get an error when running the final build.  Does tauri support running on aarch64?

```
purism@l5:~/Projects/body-sculpting$ ls build
asset-manifest.json  index.html        logo192.png  manifest.json                                          robots.txt         static
favicon.ico          index.tauri.html  logo512.png  precache-manifest.553920da7ce8f02f32618a0ae2e7f37f.js  service-worker.js
purism@l5:~/Projects/body-sculpting$ yarn tauri build
yarn run v1.22.4
$ tauri build
[tauri]: running build
 app:spawn Running "cargo tauri-bundler --features embedded-server --release" +0ms

error: Architecture Error: `Unable to determine target-architecture`

 app:spawn Command "cargo" failed with exit code: 1 +15ms

 app:tauri (runner) ⚠️  [FAIL] Cargo CLI has failed +8ms

 app:tauri Shutting down tauri process... +21ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
purism@l5:~/Projects/body-sculpting$ 

```

**Comment by nothingismagick** [comment]
this is something that we expected to happen, but we will have to update the bundler to properly detect it.

can you paste the results of `yarn tauri info`?

**Comment by thomasmarkiewicz** [comment]
```
Linux l5 5.7.0-1-librem5 #1 SMP PREEMPT Tue Aug 11 14:37:38 UTC 2020 aarch64

The programs included with the PureOS system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

PureOS comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Aug 19 09:05:43 2020 from 192.168.1.47
purism@l5:~$ cd Projects/body-sculpting/
purism@l5:~/Projects/body-sculpting$ yarn tauri info
yarn run v1.22.4
$ tauri info
[tauri]: running info

Operating System - Linux(5.7.0-1-librem5) - linux/arm64

Node.js environment
  Node.js - 14.8.0
  tauri.js - 0.11.1

Rust environment
  rustc - 1.45.2
  cargo - 1.45.1
  tauri-bundler - 0.9.1

Global packages
  NPM - 6.14.7
  yarn - 1.22.4

App directory structure
/build
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 0.9.1
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../build
  devPath - http://localhost:3000
Done in 20.52s.
purism@l5:~/Projects/body-sculpting$ 

```

**Comment by jmaygarden** [comment]
I am also having this issue. Is there a workaround?

```
Operating System - Linux(4.9.140-tegra) - linux/arm64

Node.js environment
  Node.js - 14.13.0
  tauri.js - 0.12.0

Rust environment
  rustc - 1.46.0
  cargo - 1.46.0
  tauri-bundler - 0.9.3

Global packages
  NPM - 6.14.8
  yarn - 1.22.10

App directory structure
/.git
/.vscode
/dist
/node_modules
/src
/src-tauri

App
  tauri.rs - 0.9.2
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist
  devPath - http://localhost:3000/
```

**Comment by jmaygarden** [comment]
Is this feature branch a viable alternative?

[feat(tauri) add `cross` support #491](https://github.com/tauri-apps/tauri/pull/491)

It looks very straight-forward. Is there a reason that it hasn't been merged other than developer time?

**Comment by jbolda** [comment]
I believe @lucasfernog was dealing with code signing on Mac first which kind of stalled, but don't quote me on that 😊

**Comment by nothingismagick** [comment]
This is an important issue, for sure, and would need to be addressed inside of our bundler. I think it is really a matter of our detection of the platform. We have been discussing using cross for armhf (rpi), so i think we should definitely spend some time on making sure that our workflow is also able to cross compile for Librem.

**Comment by vinicentus** [comment]
Is there any update on this? I see that #1664 has been merged.
I would also need aarch64 support for a project...

**Comment by nothingismagick** [comment]
Yes, we have a dedicated discord channel for this topic, where we are working on getting this all to work on RPi.

**Comment by nothingismagick** [comment]
https://discord.com/channels/616186924390023171/837614826900946954/839127214875869185

**Comment by nothingismagick** [comment]
<img width="857" alt="image" src="https://user-images.githubusercontent.com/35242872/117638004-b1b18c80-b182-11eb-9102-42bcde6056a1.png">

**Comment by damien-monni** [comment]
> https://discord.com/channels/616186924390023171/837614826900946954/839127214875869185

Does this discord channel still exist? I can't open it.

I am trying to make Tauri works on a Raspberry Pi 3 B+ but I can't make it works.
Should I be able to make Tauri work on a Raspberry Pi?

**Comment by MariusVB** [comment]
Trying to make Tauri work on Raspberry Pi 4 B. Also not working.
Getting this error code when installing the Rust tauri-cli through npm:
![image](https://user-images.githubusercontent.com/24921111/146553118-6d765508-c32b-4c75-abf7-23bb4640fd58.png)

And getting this when installing directly through cargo:
![image](https://user-images.githubusercontent.com/24921111/146553067-04fb4b7f-0dba-4b9e-9311-470111a1655a.png)

**Comment by FabianLars** [comment]
@MariusVB 
Tracking issue for the first one: #2421
solution for the second one: #3050 (`cargo install tauri-cli --git https://github.com/tauri-apps/tauri`)

**Comment by FabianLars** [comment]
@damien-monni The channel (and message) does still exist (#arm-platform), but linking discord messages externally sometimes doesn't want to work for everyone (especially if you're not logged in or not a server member)

**Comment by MariusVB** [comment]
@FabianLars that was fast! Thank you lots. Trying the cargo install right now.

**Comment by ncpleslie** [comment]
Was there any update to this?

I was able to build successfully using [this project](https://github.com/zxcv1884/tauri-arm). It utilizes a docker container. 

After attempting to install the `deb` file, it produces this error

![image](https://user-images.githubusercontent.com/33884283/169929394-8122e3ed-ee92-4cd5-b8d5-447175be0fde.png)
