### ISSUE TITLE
Cross-platform project creation

### ISSUE THREAD

**Issue by mehmedaltug** [tauri-apps/tauri#9417]
### Describe the problem

After searching web for cross-compilation i learned that it is in fact not possible "yet" because some libraries or something are platform dependent. so i though i could port my project to another platform if i could create my project for a specific platform, but i couldnt find anything about it. 

is there a feature like that or i have to create the project in a VM? i'm on linux and i'm trying to compile/port it to windows.

### Describe the solution you'd like

maybe an option to create tauri project for another platform, better yet a true cross-compilation.

**Comment by FabianLars** [comment]
Tauris projects (configurations etc) are cross platform by default, no matter on which platform you created them.

You just have to use VMs or CI with native runners like GitHub to compile them for the respective platform.

**Comment by mehmedaltug** [comment]
Oh silly me. Thank you, after searching further i found out how to compile it using github releases. Sorry for taking your time
