### ISSUE TITLE
[bug] File drag and drop configuration seems broken in v2

### ISSUE THREAD

**Issue by noxan** [tauri-apps/tauri#9421]
### Describe the bug

I can't find a way to disable file drop events on the window with tauri v2 beta. This is to handle file drop events within the web view.

When upgrading my app from v1 to v2 (beta.14) I get the following issue:
```
unknown field `fileDropEnabled`, expected one of `label`, `url`, `user-agent`, `userAgent`, `drag-drop-enabled`, `dragDropEnabled`, `center`, `x`, `y`, `width`, `height`, `min-width`, `minWidth`, `min-height`, `minHeight`, `max-width`, `maxWidth`, `max-height`, `maxHeight`, `resizable`, `maximizable`, `minimizable`, `closable`, `title`, `fullscreen`, `focus`, `transparent`, `maximized`, `visible`, `decorations`, `always-on-bottom`, `alwaysOnBottom`, `always-on-top`, `alwaysOnTop`, `visible-on-all-workspaces`, `visibleOnAllWorkspaces`, `content-protected`, `contentProtected`, `skip-taskbar`, `skipTaskbar`, `theme`, `title-bar-style`, `titleBarStyle`, `hidden-title`, `hiddenTitle`, `accept-first-mouse`, `acceptFirstMouse`, `tabbing-identifier`, `tabbingIdentifier`, `additional-browser-args`, `additionalBrowserArgs`, `shadow`, `window-effects`, `windowEffects`, `incognito`, `parent`, `proxyUrl` 
```

After some searching, I found the hint in [discord](https://discord.com/channels/616186924390023171/731495028677148753/1225672663683432458) (nowhere in the changelogs), that it had been renamed to `dragDropEnabled`, but this results in:
```
Error `tauri.conf.json` error on `app > windows > 0`: Additional properties are not allowed ('dragDropEnabled' was unexpected) 
```

### Reproduction

Removing the `fileDropEnabled` (and respective `dragDropEnabled`) makes the app compile again, but file drop events do not reach the webview.

You can test it with https://github.com/noxan/katalog (not a minimal example, but where I encounter the issue)

### Full `tauri info` output

```text
Error `tauri.conf.json` error on `app > windows > 0`: Additional properties are not allowed ('dragDropEnabled' was unexpected)
ELIFECYCLE  Command failed with exit code 1.```
```

**Comment by FabianLars** [comment]
Try updating `@tauri-apps/cli` to beta.12 (it's on beta.4 in your project)

**Comment by noxan** [comment]
@FabianLars many thanks, i've tested endless variations of tauri versions in cargo... but totally forgot the npm versions, my oversight.

Got it working. Does it make sense to add some documentation or changelog? Happy to help to so others don't stumble across the same issue :)

**Comment by FabianLars** [comment]
Sure, if you have a good location for this info in mind we'd appreciate a PR :)
