### ISSUE TITLE
[bug] Issue with configuring

### ISSUE THREAD

**Issue by skateboard** [tauri-apps/tauri#9425]
### Describe the bug

There seems to be a issue with configuring that i cant seem to find a fix for, when i use "devPath" in the tauri.conf.json under the build json object, i get his error

this issue happens when i use `cargo tauri dev`

"unknown field `devPath`, expected one of `runner`, `dev-url`, `devUrl`, `frontend-dist`, `frontendDist`, `before-dev-command`, `beforeDevCommand`, `before-build-command`, `beforeBuildCommand`, `before-bundle-command`, `beforeBundleCommand`, `features`
  found an unknown configuration field. This usually means that you are using a CLI version that is newer than `tauri-build` and is incompatible. Please try updating the Rust crates by running `cargo update` in the Tauri app folder.`"

but if i use "devUrl" instead i get this error

` Error 'tauri.conf.json' error on 'build': Additional properties are not allowed ('devUrl' was unexpected)`

I even tried to use cargo update, but it did nothing to solve the problem, so i am very confused on what i am supposed to be doing?

### Full `tauri info` output

```text
[✘] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 123.0.2420.81
    ✘ Couldn't detect any Visual Studio or VS Build Tools instance with MSVC and SDK components. Download from https://aka.ms/vs/17/release/vs_BuildTools.exe
    ✔ rustc: 1.77.1 (7cf61ebde 2024-03-27)
    ✔ cargo: 1.77.1 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.11.1
    - yarn: 1.22.22
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.14
    - tauri-build [RUST]: 2.0.0-beta.11
    - wry [RUST]: 0.39.0
    - tao [RUST]: 0.27.0
    - tauri-cli [RUST]: 1.5.11
    - @tauri-apps/api [NPM]: 2.0.0-beta.4
    - @tauri-apps/cli [NPM]: 1.5.11

[-] App
    - build-type: build
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Webpack
```

### Stack trace

```text
Running BeforeDevCommand (`npm run dev`)

> project1@0.1.0 dev
> next dev

   ▲ Next.js 14.1.4
   - Local:        http://localhost:3000

        Info Watching C:\Users\a\Desktop\projects\project1\src-tauri for changes...
   Compiling app v0.1.0 (C:\Users\a\Desktop\projects\project1\src-tauri)
   Compiling solana-client v1.18.10
error: failed to run custom build command for `app v0.1.0 (C:\Users\a\Desktop\projects\project1\src-tauri)`

Caused by:
  process didn't exit successfully: `C:\Users\a\Desktop\projects\project1\src-tauri\target\debug\build\app-d8fbcf461ce5af45\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=desktop
  unknown field `devPath`, expected one of `runner`, `dev-url`, `devUrl`, `frontend-dist`, `frontendDist`, `before-dev-command`, `beforeDevCommand`, `before-build-command`, `beforeBuildCommand`, `before-bundle-command`, `beforeBundleCommand`, `features`
  found an unknown configuration field. This usually means that you are using a CLI version that is newer than `tauri-build` and is incompatible. Please try updating the Rust crates by running `cargo update` in the Tauri app folder.
warning: build failed, waiting for other jobs to finish...
 ✓ Ready in 1867ms===================> ] 812/814:
```

**Comment by FabianLars** [comment]
Your tauri cli version is still on v1. Update that to v2-beta too and it should work.

**Comment by Blatman** [comment]
Just for anyone else getting this as I did the problem appears to be with the docs at the moment - if @latest is used without the -- --beta then the V1 CLI will be installed, new installs/create are easier but upgrades are too easy at the moment to get mixed versions. Also at the moment it is not clear as to what NPM installs are required or are just alternative ways of doing stuff. At the moment I find that to do a dot upgrade of the beta I need to start fresh and copy over files, etc.
