### ISSUE TITLE
[feat] Does Tauri support static resources(html/css/images/fonts) hot update？

### ISSUE THREAD

**Issue by mopduan** [tauri-apps/tauri#9438]
### Describe the problem

I want to use static resource hot update to make better user experience when there is a need for update.

### Describe the solution you'd like

Look forward to your reply.

**Comment by FabianLars** [comment]
Currently this is not supported, but we've recently worked on some building blocks for it like https://github.com/tauri-apps/tauri/pull/9141

Also, potentially related to https://github.com/tauri-apps/tauri/issues/5302

**Comment by mopduan** [comment]
> Currently this is not supported, but we've recently worked on some building blocks for it like #9141
> 
> Also, potentially related to #5302

Get it. Thanks!
