### ISSUE TITLE
Tauri Drag and Drop Events Not Firing on Windows [bug] 

### ISSUE THREAD

**Issue by selastingeorge** [tauri-apps/tauri#9448]
### Describe the bug

The following Tauri events do not fire on Windows:
```
tauri://file-drop-hover
tauri://file-drop-cancelled
tauri://file-drop
```

I also set `dragDropEnabled` to `true` but still it does not fire.
Here is a demo project : [https://github.com/selastingeorge/Tauri-File-Drop](https://github.com/selastingeorge/Tauri-File-Drop)

### Reproduction

Create a new tauri app and set `dragDropEnabled`  to true in tauri.config.json.
add following code to the script file:

```
    import { listen } from '@tauri-apps/api/event'
    listen('tauri://file-drop', event => {
      console.log(event)
    })
    listen('tauri://file-drop-hover', event => {
      console.log(event)
    })
    listen('tauri://file-drop-cancelled', event => {
      console.log(event)
    })
```

### Expected behavior

The console should print the event object.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 123.0.2420.65
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.77.0 (aedd173a2 2024-03-17)
    ✔ cargo: 1.77.0 (3fe68eabf 2024-02-29)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.11.0
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.14
    - tauri-build [RUST]: 2.0.0-beta.11
    - wry [RUST]: 0.39.0
    - tao [RUST]: 0.27.0
    - tauri-cli [RUST]: 2.0.0-beta.12
    - @tauri-apps/api [NPM]: 2.0.0-beta.7
    - @tauri-apps/cli [NPM]: 2.0.0-beta.12

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist/filedrop/browser
    - devUrl: http://localhost:1420/
    - framework: Angular
    - bundler: Webpack
```

**Comment by FabianLars** [comment]
The events were renamed to
```
tauri://drag
tauri://drop
tauri://drop-over
tauri://drag-cancelled
```
Please bear with us while we're working on the docs...

**Comment by bicarlsen** [comment]
Just a heads up, it appears the [names have changed](https://github.com/tauri-apps/tauri/blob/005e4a96490919c52ed7fb54d0926a2eab75cc1a/tooling/api/src/event.ts#L49) again in `2.0.0-rc.0`.

**Comment by niraj-khatiwada** [comment]
Got this bug today weirdly on Windows only, works fine on Mac & Linux. Looks like the events label changed again. To avoid such issues in future, I recommend using the Tauri event enum directly instead of using the event label.
```
import { event } from "@tauri-apps/api";
...
dragAndDropListenerRef.current.drag = await event.listen(
  event.TauriEvent.DRAG_ENTER, // Use this instead of "tauri://drag"
  () => {
    setDragAndDropState("dragging");
  },
);
...

```
