### ISSUE TITLE
compile ok,and run error on win7

### ISSUE THREAD

**Issue by miaomiao1992** [tauri-apps/tauri#9462]
### Describe the bug

16bits software is not compatible 

win7-x86-msvc
web view runtime 109
msvc 2015

![IMG_4796](https://github.com/tauri-apps/tauri/assets/59018630/e6738626-9460-44ad-a7cd-0d8ff6e6834c)
![IMG_4795](https://github.com/tauri-apps/tauri/assets/59018630/fd9b8da8-13c7-4250-a040-7b10a1fa2b6e)
![IMG_4794](https://github.com/tauri-apps/tauri/assets/59018630/6f25cb1b-ac70-469a-9720-3d8454db948a)
![IMG_4793](https://github.com/tauri-apps/tauri/assets/59018630/1d104a8a-d6d1-48cb-8a32-757e3c86d133)
![IMG_4797](https://github.com/tauri-apps/tauri/assets/59018630/3623e607-1c91-4e5b-b03f-1b160898f373)

### Expected behavior

can run normally

### Full `tauri info` output

```text
done in 126s

please see the photos
```

**Comment by amrbashir** [comment]
you don't seem to have Visual Studio Build tools installed, please follow https://tauri.app/v1/guides/getting-started/prerequisites#setting-up-windows

**Comment by miaomiao1992** [comment]
> you don't seem to have Visual Studio Build tools installed, please follow https://tauri.app/v1/guides/getting-started/prerequisites#setting-up-windows

this is not my personal computer. i cannot change to win10 and msvc2022 because of some special reasons.

**Comment by amrbashir** [comment]
you can't develop tauri apps without installing msvc build tools, you can try using msvc 2019 (maybe 2017 could work as well but can't be sure)

**Comment by FabianLars** [comment]
2017 doesn't work, it must be 2019 or 2022 for Tauri. Visual Studio 2019 should work on Windows 7 as long as the windows 7 installation is fully up to date. 2022 iirc does not work on win7

**Comment by FabianLars** [comment]
That said, we don't really test (or officially support) _building_ on windows 7. I only test if compiled tauri apps run on windows 7 (not often though).
