### ISSUE TITLE
[bug] Issue with Resizing Window on Windows 11 at Non-100% Display Scale

### ISSUE THREAD

**Issue by eed-cn** [tauri-apps/tauri#9464]
### Describe the bug

When `decorations=false` and `resizable=true` are set for the `webview_window`, when the display scale is not equal to 100%, the right and bottom edges of the window cannot be dragged to resize the window. It works normally when the scale is 100%.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22635 X64
    ✔ WebView2: 123.0.2420.65
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.77.1 (7cf61ebde 2024-03-27)
    ✔ cargo: 1.77.1 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.9.0
    - pnpm: 8.15.7
    - yarn: 1.22.21
    - npm: 10.1.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.14
    - tauri-build [RUST]: 2.0.0-beta.11
    - wry [RUST]: 0.39.0
    - tao [RUST]: 0.27.0
    - tauri-cli [RUST]: 2.0.0-alpha.4
    - @tauri-apps/api [NPM]: 2.0.0-beta.7
    - @tauri-apps/cli [NPM]: 2.0.0-beta.12

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - bundler: Vite
```

**Comment by tejonaco** [comment]
I also encountered this bug, I made a workaround dividing width and height by my monitor scale, but I think that will be a problem when distributing the program.

**Comment by eed-cn** [comment]
@tejonaco  
The latest version(tauri [RUST]: 2.0.0-beta.24) doesn't have this problem anymore.

**Comment by tejonaco** [comment]
> @tejonaco  
> The latest version(tauri [RUST]: 2.0.0-beta.24) doesn't have this problem anymore.
>  
Good news, thanks!
