### ISSUE TITLE
[bug] during the uninstallation of the application,  `Delete the application data`  exhibits abnormal behavior

### ISSUE THREAD

**Issue by l1xnan** [tauri-apps/tauri#9475]
### Describe the bug

I mistakenly installed the program in the `D:\Program Files` directory. When I attempt to uninstall the program and select to `Delete the application data`, it results in the deletion of all files under the `D:\Program Files`, even those unrelated to the application data. See https://github.com/l1xnan/duckling/issues/128
![image](https://github.com/tauri-apps/tauri/assets/6105390/5de4bc29-689e-4294-a63b-4f48d411297e)

From the user's perspective, they mistakenly chose the `D:\Program Files` folder during installation. Later, when they wanted to uninstall and reinstall the program, they didn't realize, nor were they warned, that this would cause serious issues.

Such behavior can easily lead to loss of user data. Are there any methods to mitigate this problem?

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 123.0.2420.97
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.77.0 (aedd173a2 2024-03-17)
    ✔ cargo: 1.77.0 (3fe68eabf 2024-02-29)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.9.0
    - pnpm: 8.15.4
    - yarn: 1.22.19
    - npm: 10.2.0
    - bun: 1.1.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.14
    - tauri-build [RUST]: 2.0.0-beta.11
    - wry [RUST]: 0.39.0
    - tao [RUST]: 0.27.0
    - tauri-cli [RUST]: 2.0.0-alpha.17
    - @tauri-apps/api [NPM]: 2.0.0-beta.6
    - @tauri-apps/cli [NPM]: 2.0.0-beta.11

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:5173/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment]
I fixed this for v1 [here](https://github.com/tauri-apps/tauri/pull/9282). I'll check if i can merge the v1 branch into the v2 one or if i have to port it over manually. Thanks for the report.

**Comment by FabianLars** [comment]
https://github.com/tauri-apps/tauri/pull/9479
