### ISSUE TITLE
[bug] multiwebview does not use provided user agent string

### ISSUE THREAD

**Issue by micahflee** [tauri-apps/tauri#9492]
### Describe the bug

In `tauri.conf.json` you can set a user agent string using the [WindowConfig.userAgent](https://tauri.app/v1/api/config/#windowconfig.useragent). This sets it for the main window, but when you're using multiwebview, it doesn't update the user agent string for the child webviews. Those remain the default.

### Reproduction

Here's my reproduction repo: https://github.com/micahflee/tauri-useragent-bug

I set the user agent string to "this is a custom user agent string" [here](https://github.com/micahflee/tauri-useragent-bug/blob/main/src-tauri/tauri.conf.json#L15):

```json
{
  "productName": "tauri-useragent-bug",
  "version": "0.0.0",
  "identifier": "com.tauri.dev",
  "build": {
    "frontendDist": "../src"
  },
  "app": {
    "withGlobalTauri": true,
    "windows": [
      {
        "title": "tauri-useragent-bug",
        "width": 800,
        "height": 600,
        "userAgent": "this is a custom user agent string"
      }
    ],
--snip--
```

The HTML displays the user agent string it sees [here](https://github.com/micahflee/tauri-useragent-bug/blob/main/src/index.html#L17):

```js
document.getElementById("user-agent").innerText = navigator.userAgent;
```

I set up a new child webview [here](https://github.com/micahflee/tauri-useragent-bug/blob/main/src-tauri/src/main.rs#L7-L21) and have it load the URL https://www.whatsmyua.info/:

```rs
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use tauri::{LogicalPosition, LogicalSize, Manager, WebviewUrl};

fn main() {
    tauri::Builder::default()
        .setup(|app| {
            let width = 800.;
            let height = 600.;
            let window = app.get_window("main").unwrap();
            let _ = window.add_child(
                tauri::webview::WebviewBuilder::new(
                    "main3",
                    WebviewUrl::External("https://www.whatsmyua.info/".parse().unwrap()),
                )
                .auto_resize(),
                LogicalPosition::new(0., height / 2.),
                LogicalSize::new(width, height / 2.),
            )?;
            Ok(())
        })
        .plugin(tauri_plugin_shell::init())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

Here's what it looks like:

<img width="800" alt="Screenshot 2024-04-17 at 6 42 49 PM" src="https://github.com/tauri-apps/tauri/assets/156128/95d06cf0-238d-49dc-afe0-ca4dfee2f1b1">

As you can see, in the main app webview the user agent string is set to "this is a custom user agent string", but in the child webview the user agent string is Tauri's default, which is "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)".

### Expected behavior

Child webviews should use the user agent string defined in `tauri.conf.json`, just like the main web app does.

Better yet, you should be able to set the user agent string on a per-webview basis. However, that's more like a small feature request.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.77.2 (25ef9e3d8 2024-04-09)
    ✔ cargo: 1.77.2 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 18.18.2
    - pnpm: 8.15.7
    - yarn: 1.22.21
    - npm: 10.4.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.15
    - tauri-build [RUST]: 2.0.0-beta.12
    - wry [RUST]: 0.39.1
    - tao [RUST]: 0.27.0
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-beta.13

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../src
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by amrbashir** [comment]
you need to call https://docs.rs/tauri/2.0.0-beta.15/tauri/webview/struct.WebviewBuilder.html#method.user_agent when creating the child
