### ISSUE TITLE
[bug] [v2] Can not open the dev console

### ISSUE THREAD

**Issue by Itzenev** [tauri-apps/tauri#9500]
### Describe the bug

It was working fine until today. I cannot open the dev console now, also the context menu is lacking the inspect option. I am on 2.0 latest beta. 

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 123.0.2420.97
    ✔ MSVC:
        - Visual Studio Build Tools 2019
        - Visual Studio Community 2022
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 21.6.0
    - pnpm: 8.15.5
    - yarn: 1.22.21
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.15
    - tauri-build [RUST]: 2.0.0-beta.12
    - wry [RUST]: 0.39.1
    - tao [RUST]: 0.27.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.7
    - @tauri-apps/cli [NPM]: 2.0.0-beta.12

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Are we talking about `tauri dev` or `tauri build` ? Are you using the --release (dev) or --debug (build) flags?

**Comment by Itzenev** [comment]
We found the problem.
I am starting with `tauri dev`. But recently we added an updater. I was working on a branch, and my version was lower than the latest. It seems the updater kills the app and starts it again. In release mode. And I don't have the console.
