### ISSUE TITLE
[bug] failed to select a version for the requirement `hyper-rustls`

### ISSUE THREAD

**Issue by lihe6666** [tauri-apps/tauri#9506]
### Describe the bug

error: failed to select a version for the requirement `hyper-rustls = "^0.26.0"`
candidate versions found which didn't match: 0.24.2, 0.24.1, 0.24.0, ...
location searched: crates.io index

<img width="808" alt="image" src="https://github.com/tauri-apps/tauri/assets/2598007/5c7b72d9-4b27-4bf6-b4de-1084be63d8b8">

### Reproduction

1. pnpm create tauri-app --beta
2. Project name `app` 
3. Choose which language to use for your frontend · TypeScript / JavaScript - (pnpm, yarn, npm, bun)
4. Choose your package manager · pnpm
5. Choose your UI template · Svelte - (https://svelte.dev/)
6. Choose your UI flavor · TypeScript
7. Would you like to setup the project for mobile as well? · yes
8. cd app && pnpm install 
9. pnpm tauri android init
10. pnpm tauri android dev

### Expected behavior

startup app at phone.

### Full `tauri info` output

```text
> tauri "info"


[✔] Environment
    - OS: Mac OS 13.4.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.77.2 (25ef9e3d8 2024-04-09)
    ✔ cargo: 1.77.2 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 18.19.0
    - pnpm: 9.0.4
    - npm: 10.5.2

[-] Packages
    - tauri [RUST]: 2.0.0-beta.15
    - tauri-build [RUST]: 2.0.0-beta.12
    - wry [RUST]: 0.39.1
    - tao [RUST]: 0.27.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.8
    - @tauri-apps/cli [NPM]: 2.0.0-beta.13

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

### Additional context

➜  app pnpm tauri android dev

> app@0.0.0 tauri /Users/developer/Projects/Tauri/app
> tauri "android" "dev"

    Info Detected connected device: 21091116AC with target "aarch64-linux-android"
    Info Using 192.168.2.54 to access the development server.
    Running BeforeDevCommand (`pnpm dev`)

> app@0.0.0 dev /Users/developer/Projects/Tauri/app
> vite

    Warn Waiting for your frontend dev server to start on http://192.168.2.54:1420/...
Forced re-optimization of dependencies

  VITE v5.2.9  ready in 1797 ms

  ➜  Local:   http://localhost:1420/
  ➜  Network: http://192.168.2.54:1420/
    Info detected host target triple "x86_64-apple-darwin"
    Updating crates.io index
   Compiling proc-macro2 v1.0.81
   Compiling unicode-ident v1.0.12
   Compiling libc v0.2.153
   Compiling cfg-if v1.0.0
   Compiling serde v1.0.198
   Compiling siphasher v0.3.11
   Compiling syn v1.0.109
   Compiling ppv-lite86 v0.2.17
   Compiling autocfg v1.2.0
   Compiling getrandom v0.1.16
   Compiling phf_shared v0.10.0
   Compiling phf_shared v0.8.0
   Compiling lock_api v0.4.11
   Compiling parking_lot_core v0.9.9
   Compiling hashbrown v0.14.3
   Compiling equivalent v1.0.1
   Compiling indexmap v2.2.6
   Compiling proc-macro-hack v0.5.20+deprecated
   Compiling thiserror v1.0.58
   Compiling quote v1.0.36
   Compiling syn v2.0.60
   Compiling winnow v0.5.40
   Compiling convert_case v0.4.0
   Compiling once_cell v1.19.0
   Compiling fnv v1.0.7
   Compiling getrandom v0.2.14
   Compiling itoa v1.0.11
   Compiling rand_core v0.6.4
   Compiling rand_core v0.5.1
   Compiling ident_case v1.0.1
   Compiling serde_json v1.0.116
   Compiling strsim v0.10.0
   Compiling rand_chacha v0.3.1
   Compiling rand_pcg v0.2.1
   Compiling rand_chacha v0.2.2
   Compiling rand v0.8.5
   Compiling rand v0.7.3
   Compiling smallvec v1.13.2
   Compiling ryu v1.0.17
   Compiling memchr v2.7.2
   Compiling phf_shared v0.11.2
   Compiling typenum v1.17.0
   Compiling phf_generator v0.8.0
   Compiling phf_generator v0.10.0
   Compiling string_cache_codegen v0.5.2
   Compiling phf_codegen v0.10.0
   Compiling phf_codegen v0.8.0
   Compiling phf_generator v0.11.2
   Compiling selectors v0.22.0
   Compiling byteorder v1.5.0
   Compiling tinyvec_macros v0.1.1
   Compiling new_debug_unreachable v1.0.6
   Compiling scopeguard v1.2.0
   Compiling version_check v0.9.4
   Compiling semver v1.0.22
   Compiling tinyvec v1.6.0
   Compiling markup5ever v0.11.0
   Compiling generic-array v0.14.7
   Compiling precomputed-hash v0.1.1
   Compiling mac v0.1.1
   Compiling parking_lot v0.12.1
   Compiling futf v0.1.5
   Compiling indexmap v1.9.3
   Compiling percent-encoding v2.3.1
   Compiling dtoa v1.0.9
   Compiling unicode-bidi v0.3.15
   Compiling log v0.4.21
   Compiling bitflags v1.3.2
   Compiling darling_core v0.20.8
   Compiling utf-8 v0.7.6
   Compiling unicode-normalization v0.1.23
   Compiling tendril v0.4.3
   Compiling serde_derive_internals v0.26.0
   Compiling dtoa-short v0.3.4
   Compiling idna v0.5.0
   Compiling form_urlencoded v1.2.1
   Compiling aho-corasick v1.1.3
   Compiling phf v0.10.1
   Compiling regex-syntax v0.8.3
   Compiling unic-common v0.9.0
   Compiling nodrop v0.1.14
   Compiling hashbrown v0.12.3
   Compiling stable_deref_trait v1.2.0
   Compiling matches v0.1.10
   Compiling unic-char-range v0.9.0
   Compiling alloc-no-stdlib v2.0.4
   Compiling camino v1.1.6
   Compiling itoa v0.4.8
   Compiling alloc-stdlib v0.2.2
   Compiling unic-char-property v0.9.0
   Compiling servo_arc v0.1.1
   Compiling unic-ucd-version v0.9.0
   Compiling fxhash v0.2.1
   Compiling uuid v1.8.0
   Compiling thin-slice v0.1.1
   Compiling schemars v0.8.16
   Compiling base64 v0.21.7
   Compiling cfb v0.7.3
   Compiling unic-ucd-ident v0.9.0
   Compiling brotli-decompressor v2.5.1
   Compiling same-file v1.0.6
   Compiling regex-automata v0.4.6
   Compiling anyhow v1.0.82
   Compiling dyn-clone v1.0.17
   Compiling brotli v3.5.0
   Compiling infer v0.15.0
   Compiling walkdir v2.5.0
   Compiling dunce v1.0.4
   Compiling glob v0.3.1
   Compiling serde_derive v1.0.198
   Compiling thiserror-impl v1.0.58
   Compiling cssparser-macros v0.6.1
   Compiling darling_macro v0.20.8
   Compiling cssparser v0.27.2
   Compiling phf_macros v0.8.0
   Compiling html5ever v0.26.0
   Compiling derive_more v0.99.17
   Compiling darling v0.20.8
   Compiling serde_with_macros v3.7.0
   Compiling phf_macros v0.11.2
   Compiling phf v0.8.0
   Compiling ctor v0.2.8
   Compiling schemars_derive v0.8.16
   Compiling regex v1.10.4
   Compiling phf v0.11.2
   Compiling powerfmt v0.2.0
   Compiling pin-project-lite v0.2.14
   Compiling deranged v0.3.11
   Compiling cc v1.0.94
   Compiling num-conv v0.1.0
   Compiling futures-core v0.3.30
   Compiling time-core v0.1.2
   Compiling time v0.3.36
   Compiling quick-xml v0.31.0
   Compiling dirs-sys-next v0.1.2
   Compiling slab v0.4.9
   Compiling line-wrap v0.2.0
   Compiling jni-sys v0.3.0
   Compiling simd-adler32 v0.3.7
   Compiling crc32fast v1.4.0
   Compiling heck v0.4.1
   Compiling serde_spanned v0.6.5
   Compiling toml_datetime v0.6.3
   Compiling bytes v1.6.0
   Compiling string_cache v0.8.7
   Compiling toml_edit v0.19.15
   Compiling toml_edit v0.20.2
   Compiling url v2.5.0
   Compiling cargo-platform v0.1.8
   Compiling treediff v4.0.3
   Compiling json-patch v1.2.0
   Compiling cargo_metadata v0.18.1
   Compiling swift-rs v1.0.6
   Compiling kuchikiki v0.8.2
   Compiling toml v0.8.2
   Compiling urlpattern v0.2.0
   Compiling serde_with v3.7.0
   Compiling http v1.1.0
   Compiling rustc_version v0.4.0
   Compiling embed-resource v2.4.2
   Compiling toml v0.7.8
   Compiling cargo_toml v0.17.2
   Compiling tauri-winres v0.1.1
   Compiling proc-macro-crate v1.3.1
   Compiling tauri-utils v2.0.0-beta.12
   Compiling plist v1.6.1
   Compiling dirs-next v2.0.0
   Compiling socket2 v0.5.6
   Compiling mio v0.8.11
   Compiling num_cpus v1.16.0
   Compiling crossbeam-utils v0.8.19
   Compiling adler v1.0.2
   Compiling miniz_oxide v0.7.2
   Compiling tokio v1.37.0
   Compiling num_enum_derive v0.5.11
   Compiling combine v4.6.7
   Compiling futures-macro v0.3.30
   Compiling tauri-build v2.0.0-beta.12
   Compiling tracing-core v0.1.32
   Compiling futures-task v0.3.30
   Compiling cesu8 v1.1.0
   Compiling httparse v1.8.0
   Compiling pin-utils v0.1.0
   Compiling futures-util v0.3.30
   Compiling jni v0.21.1
   Compiling tracing v0.1.40
   Compiling num_enum v0.5.11
   Compiling flate2 v1.0.28
   Compiling crypto-common v0.1.6
   Compiling block-buffer v0.10.4
   Compiling http-body v1.0.0
   Compiling dpi v0.1.1
   Compiling fdeflate v0.3.4
   Compiling ndk-sys v0.4.1+23.1.7779620
   Compiling pin-project-internal v1.1.5
   Compiling raw-window-handle v0.6.0
   Compiling try-lock v0.2.5
   Compiling raw-window-handle v0.5.2
   Compiling want v0.3.1
   Compiling ndk v0.7.0
   Compiling png v0.17.13
   Compiling crossbeam-channel v0.5.12
   Compiling pin-project v1.1.5
   Compiling digest v0.10.7
   Compiling futures-channel v0.3.30
   Compiling tao-macros v0.1.2
   Compiling cpufeatures v0.2.12
   Compiling ndk-context v0.1.1
   Compiling wry v0.39.1
   Compiling tauri-runtime v2.0.0-beta.12
   Compiling tower-layer v0.3.2
   Compiling tower-service v0.3.2
   Compiling tower v0.4.13
   Compiling sha2 v0.10.8
   Compiling hyper v1.3.1
   Compiling ico v0.3.0
   Compiling tauri-plugin v2.0.0-beta.12
   Compiling instant v0.1.12
   Compiling futures-sink v0.3.30
   Compiling tauri-runtime-wry v2.0.0-beta.12
   Compiling lazy_static v1.4.0
   Compiling base64 v0.22.0
   Compiling tauri-codegen v2.0.0-beta.12
   Compiling hyper-util v0.1.3
   Compiling tao v0.27.0
   Compiling tokio-util v0.7.10
   Compiling http-body-util v0.1.1
   Compiling serde_urlencoded v0.7.1
   Compiling serialize-to-javascript-impl v0.1.1
   Compiling is-docker v0.2.0
   Compiling sync_wrapper v0.1.2
   Compiling ipnet v2.9.0
   Compiling mime v0.3.17
   Compiling reqwest v0.12.3
   Compiling serialize-to-javascript v0.1.1
   Compiling is-wsl v0.4.0
   Compiling serde_repr v0.1.19
   Compiling tauri v2.0.0-beta.15
   Compiling tauri-plugin-shell v2.0.0-beta.3
   Compiling state v0.6.0
   Compiling pathdiff v0.2.1
   Compiling open v5.1.2
   Compiling app v0.0.0 (/Users/developer/Projects/Tauri/app/src-tauri)
   Compiling encoding_rs v0.8.34
   Compiling os_pipe v1.1.5
   Compiling shared_child v1.0.0
   Compiling tauri-macros v2.0.0-beta.12
    Finished dev [unoptimized + debuginfo] target(s) in 2m 42s
    Info symlinking lib "/Users/developer/Projects/Tauri/app/src-tauri/target/aarch64-linux-android/debug/libapp_lib.so" in jniLibs dir "/Users/developer/Projects/Tauri/app/src-tauri/gen/android/app/src/main/jniLibs/arm64-v8a"
    Info "/Users/developer/Projects/Tauri/app/src-tauri/target/aarch64-linux-android/debug/libapp_lib.so" requires shared lib "libandroid.so"
    Info "/Users/developer/Projects/Tauri/app/src-tauri/target/aarch64-linux-android/debug/libapp_lib.so" requires shared lib "libdl.so"
    Info "/Users/developer/Projects/Tauri/app/src-tauri/target/aarch64-linux-android/debug/libapp_lib.so" requires shared lib "liblog.so"
    Info "/Users/developer/Projects/Tauri/app/src-tauri/target/aarch64-linux-android/debug/libapp_lib.so" requires shared lib "libm.so"
    Info "/Users/developer/Projects/Tauri/app/src-tauri/target/aarch64-linux-android/debug/libapp_lib.so" requires shared lib "libc.so"
    Info symlink at "/Users/developer/Projects/Tauri/app/src-tauri/gen/android/app/src/main/jniLibs/arm64-v8a/libapp_lib.so" points to "/Users/developer/Projects/Tauri/app/src-tauri/target/aarch64-linux-android/debug/libapp_lib.so"

> app@0.0.0 tauri /Users/developer/Projects/Tauri/app
> tauri "android" "android-studio-script" "--target" "aarch64"

<=======------> 54% EXECUTING [8s]
    Updating crates.io indexG [11s]
error: failed to select a version for the requirement `hyper-rustls = "^0.26.0"`
candidate versions found which didn't match: 0.24.2, 0.24.1, 0.24.0, ...
location searched: crates.io index
required by package `reqwest v0.12.3`
    ... which satisfies dependency `reqwest = "^0.12"` (locked to 0.12.3) of package `tauri v2.0.0-beta.15`
    ... which satisfies dependency `tauri = "^2.0.0-beta"` (locked to 2.0.0-beta.15) of package `app v0.0.0 (/Users/developer/Projects/Tauri/app/src-tauri)`
if you are looking for the prerelease package it needs to be specified explicitly
    hyper-rustls = { version = "0.19.0-alpha.3" }
perhaps a crate was updated and forgotten to be re-vendored?
    Error `Failed to run `cargo build`: command ["cargo", "build", "--package", "app", "--manifest-path", "/Users/developer/Projects/Tauri/app/src-tauri/Cargo.toml", "--target", "aarch64-linux-android", "--features", "tauri/rustls-tls", "--lib", "--no-default-features"] exited with code 101
 ELIFECYCLE  Command failed with exit code 1.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:rustBuildArm64Debug'.
> Process 'command 'pnpm'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 12s
    Error Failed to assemble APK: command ["/Users/developer/Projects/Tauri/app/src-tauri/gen/android/gradlew", "--project-dir", "/Users/developer/Projects/Tauri/app/src-tauri/gen/android"] exited with code 1
 ELIFECYCLE  Command failed with exit code 1.

**Comment by FabianLars** [comment]
Can you delete the `~/.cargo/registry` folder (and maybe the src-tauri/target/ folder) and try again please?

**Comment by lihe6666** [comment]
Problem solved, thank you. @FabianLars
