### ISSUE TITLE
[bug] `error sending request for url (http://192.168.0.x:1420/)` on iOS 

### ISSUE THREAD

**Issue by kalepail** [tauri-apps/tauri#9509]
### Describe the bug

Whenever I build an app for iOS and run it on a physical device I cannot get the view to load. Using `dev` works alright but `build` never loads. I always get `error sending request for url (http://192.168.0.x:1420/)`

### Reproduction

I'm just using all the vanilla templates from https://beta.tauri.app/guides/create/#using-create-tauri-app. I've specifically tried bun and pnpm for svelte and basic JS.

### Expected behavior

The built app should load on device.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.77.2 (25ef9e3d8 2024-04-09)
    ✔ cargo: 1.77.2 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.12.2
    - pnpm: 9.0.2
    - yarn: 1.22.22
    - npm: 10.5.0
    - bun: 1.1.2

[-] Packages
    - tauri [RUST]: 2.0.0-beta.15
    - tauri-build [RUST]: 2.0.0-beta.12
    - wry [RUST]: 0.39.1
    - tao [RUST]: 0.27.0
    - tauri-cli [RUST]: 2.0.0-alpha.14
    - @tauri-apps/api [NPM]: 2.0.0-beta.8
    - @tauri-apps/cli [NPM]: 2.0.0-beta.13

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - bundler: Vite

[-] iOS
    - Developer Teams: <REDACTED>
```

### Additional context

There's some Discord conversation about this here:
https://discord.com/channels/616186924390023171/1227758916872441856
And here:
https://discord.com/channels/616186924390023171/1230704798488072282/1230718571080974336

**Comment by heliam1** [comment]
I'm getting the same for building for physical Android on Windows

```
pnpm tauri info

[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 123.0.2420.97
    ✔ MSVC: 
        - Visual Studio Build Tools 2017
        - Visual Studio Community 2019
    ✔ rustc: 1.77.2 (25ef9e3d8 2024-04-09)
    ✔ cargo: 1.77.2 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.12.1
    - pnpm: 8.7.4
    - yarn: 1.22.10
    - npm: 8.19.2
    - bun: 1.1.3

[-] Packages
    - tauri [RUST]: 2.0.0-beta.15
    - tauri-build [RUST]: 2.0.0-beta.12
    - wry [RUST]: 0.39.1
    - tao [RUST]: 0.27.0
    - cargo-tauri [RUST]: 1.0.0-beta.7
    - @tauri-apps/api [NPM]: 2.0.0-beta.8
    - @tauri-apps/cli [NPM]: 2.0.0-beta.13

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: SolidJS
    - bundler: Vite
```

**Comment by heliam1** [comment]
I thought I was getting a similar issue for android dev from windows machine
But it was caused by being connected to a VPN 🤦

**Comment by santiagomed** [comment]
Getting this same issue. Specifically, this is my output
```
Apr 19 22:26:32 tauri-moondream[39298] <Notice>: [hyper_util::client::legacy::pool] checkout waiting for idle connection: ("http", 192.0.0.2:1420)
Apr 19 22:26:32 tauri-moondream[39298] <Notice>: [reqwest::connect] starting new connection: http://192.0.0.2:1420/
Apr 19 22:26:32 tauri-moondream[39298] <Notice>: [hyper_util::client::legacy::connect::http] Http::connect; scheme=Some("http"), host=Some("192.0.0.2"), port=Some(Port(1420))
Apr 19 22:26:32 tauri-moondream[39298] <Notice>: [hyper_util::client::legacy::connect::http] connecting to 192.0.0.2:1420
Apr 19 22:26:32 tauri-moondream[39298] <Notice>: [hyper_util::client::legacy::connect::http] connect error for 192.0.0.2:1420: ConnectError("tcp connect error", Os { code: 4, kind: Interrupted, message: "Interrupted system call" })
Apr 19 22:26:32 tauri-moondream[39298] <Notice>: [hyper_util::client::legacy::pool] checkout dropped for ("http", 192.0.0.2:1420)
```

Edit: My issue is with `tauri ios dev`

**Comment by heliam1** [comment]
I ended up seeing similar issues on iOS, and in my case the issue was not having ios device and development machine on the same correctly configured network

https://discord.com/channels/616186924390023171/1227758916872441856/1233199411681689621

**Comment by FelipeEmos** [comment]
I'm getting the same error on my Android device, but it also happens with the `tauri dev` command.

Does anyone know why these requests are happening via WiFi?
The best UX would be to have the same thing as CapacitorJS... where everything happens through the USB cable.

I don't know about iOS, but Android has this very neat thing called `adb reverse` that can forward any network calls made to a port to the ADB connection. For example:
```
adb reverce tcp:3000 tcp:3000
```
Makes it so when you access your phone's `localhost:3000` you'll be actually accessing your Laptop's `localhost:3000`

React Native uses that technique and we could probably use that in Tauri too... removing the need for these devices to share a common connection ( like Wifi ). Maybe iOS has a similar thing too

**Comment by songjiachao** [comment]
same error

**Comment by songjiachao** [comment]
I resolve this problem by change  devUrl:"http://localhost:1420"  to http://0.0.0.0:1420  or your PC  ip in tauri.conf.json.
<img width="1307" alt="image" src="https://github.com/tauri-apps/tauri/assets/70792885/fbb5d7b6-01c4-4c54-a549-1afbc8bf1630">

**Comment by pakchoidora** [comment]
Same error, open dev app got "error sending request url"

[✔] Environment
    - OS: Mac OS 14.2.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.14.0
    - npm: 10.7.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.24
    - tauri-build [RUST]: 2.0.0-beta.19
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.15
    - @tauri-apps/cli [NPM]: 2.0.0-beta.22

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://0.0.0.0:1420/
    - framework: Svelte
    - bundler: Vite

[-] iOS
    - Developer Teams: Pakchoi Doragon (ID: xxx)

tauri ios build works fine, but not `tauri ios dev`

**Comment by winjeysong** [comment]
I have the same problem with `tauri ios dev`...



Changing `devUrl` NOT works for me.
> I resolve this problem by change devUrl:"http://localhost:1420" to http://0.0.0.0:1420 or your PC ip in tauri.conf.json. <img alt="image" width="1307" src="https://private-user-images.githubusercontent.com/70792885/346848597-fbb5d7b6-01c4-4c54-a549-1afbc8bf1630.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjI0ODYsIm5iZiI6MTcyMTEyMjE4NiwicGF0aCI6Ii83MDc5Mjg4NS8zNDY4NDg1OTctZmJiNWQ3YjYtMDFjNC00YzU0LWE1NDktMWFmYmM4YmYxNjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA5Mjk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1OTUzNjNlMDRhMThkMDE4YmM4MDc2NTU1NmU2M2FmNmUzYjdlMzIzMjY5YWRjZDBhMjJkYTIwNjYzNjZhODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Syg4xngEK6v--5E8iliBGt1Yv-V20kRvKo_A6XYnECs">

**Comment by tomzio** [comment]
same problem with `tauri ios dev`

**tauri info**

[✔] Environment
    - OS: Mac OS 12.6.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 20.11.0
    - pnpm: 9.5.0
    - yarn: 1.22.21
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.24
    - tauri-build [RUST]: 2.0.0-beta.19
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.15
    - @tauri-apps/cli [NPM]: 2.0.0-beta.22

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://0.0.0.0:1420/
    - framework: React
    - bundler: Vite

[-] iOS
    - Developer Teams:  <REDACTED>

**Comment by kapios010** [comment]
Same error with `tauri android dev` with changed devUrl

[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 126.0.2592.113
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.80.0 (051478957 2024-07-21)
    ✔ cargo: 1.80.0 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 21.5.0
    - pnpm: 9.6.0
    - yarn: 1.22.19
    - npm: 10.8.1

[-] Packages
    - tauri [RUST]: 2.0.0-rc.0
    - tauri-build [RUST]: 2.0.0-rc.0
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 2.0.0-rc.0
    - @tauri-apps/cli [NPM]: 2.0.0-rc.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://0.0.0.0:1420/
    - framework: Svelte
    - bundler: Vite

**Comment by kapios010** [comment]
Is debugging over usb/wireless even supported or do I need to have an android emulator ready?

**Comment by tweidinger** [comment]
Can you please retry with `-rc.2` and confirm it is still an issue?
We changed default behavior on the release candidate and we support emulator and usb connection.

iOS requires the ip of the tun device as mentioned in the blogpost https://v2.tauri.app/blog/tauri-2-0-0-release-candidate/#development-server-for-mobile but Android should work without modification.

**Comment by kapios010** [comment]
Connection over USB on android still returns the same error on this setup even in a new project made using `pnpm create tauri-app --rc`:

[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 126.0.2592.113
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.80.0 (051478957 2024-07-21)
    ✔ cargo: 1.80.0 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 22.6.0
    - pnpm: 9.6.0
    - npm: 10.8.1

[-] Packages
    - tauri [RUST]: 2.0.0-rc.1
    - tauri-build [RUST]: 2.0.0-rc.1
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 2.0.0-rc.0
    - @tauri-apps/cli [NPM]: 2.0.0-rc.2

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
    
    Changing devUrl by itself does not work.

**Comment by kapios010** [comment]
When I run `tauri android dev`, vite doesn't host the page on the network, rather only locally.
![image](https://github.com/user-attachments/assets/8ea41b5f-b517-4b3b-ac37-58edcf56b786)

And because in Vite config `server.host` is set to false only if `process.env.TAURI_DEV_HOST` returns as undefined, the outcome would suggest that it does, in fact return undefined. (that, as well as the `@ts-expect-error` comment above the `const host = process.env.TAURI_DEV_HOST;`)

Could that be related to this issue?

**Comment by ruby-ist** [comment]
I am getting the same error when I run `tauri android dev`

[✔] Environment
    - OS: Mac OS 14.0.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.11.0
    - yarn: 1.22.11
    - npm: 10.2.4
    - bun: 1.1.8

[-] Packages
    - tauri [RUST]: 2.0.0-rc.1
    - tauri-build [RUST]: 2.0.0-rc.1
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 2.0.0-rc.2
    - @tauri-apps/api [NPM]: 2.0.0-beta.14
    - @tauri-apps/cli [NPM]: 2.0.0-rc.2

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:3000/
    - framework: Vue.js (Nuxt)
    - bundler: Webpack
    
 One correction info is that I am pretty sure I am using `vite` which comes default with `Nuxt`. But it is showing the bundler as `webpack`.
 
 In my case, I can get it to work by changing the devUrl from `localhost` to my actual network IP.

**Comment by refer5h** [comment]
I succeeded in solving the problem, and the method was very simple. Change 'beforeDevCommand' in 'tauri.config.json' to 'pnpm dev --host' to make web content accessible on the LAN. Then change the IP in 'devUrl' to the developer's computer, so that the mobile phone can get web resources from the computer.
我成功地解决了这个问题，方法很简单。需要将`tauri.config.json`中的`beforeDevCommand`改为`pnpm dev --host`使得网页内容可以在局域网中访问。再将devUrl中的IP改为开发者电脑的，使得手机可以从电脑端获取网页资源。
![屏幕截图 2024-08-11 224619](https://github.com/user-attachments/assets/4a9e9607-321c-410e-b320-0efcda62f3c0)

**Comment by lucasfernog** [comment]
Looks like the port forwarding is failing for some reason. Investigating atm.

**Comment by lucasfernog** [comment]
I see the port forwarding can fail if there's more than one device connected. Let's see if there's a way to fix it.

**Comment by winjeysong** [comment]
> Can you please retry with `-rc.2` and confirm it is still an issue? We changed default behavior on the release candidate and we support emulator and usb connection.
> 
> iOS requires the ip of the tun device as mentioned in the blogpost https://v2.tauri.app/blog/tauri-2-0-0-release-candidate/#development-server-for-mobile but Android should work without modification.

Now, running `tauri ios dev` successfully on connected iOS device, thank you.

**Comment by kapios010** [comment]
Still getting the same issue in the same way on android with -rc.3
```
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 127.0.2651.105
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.80.0 (051478957 2024-07-21)
    ✔ cargo: 1.80.0 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 22.6.0
    - pnpm: 9.6.0
    - npm: 10.8.1

[-] Packages
    - tauri [RUST]: 2.0.0-rc.3
    - tauri-build [RUST]: 2.0.0-rc.3
    - wry [RUST]: 0.42.0
    - tao [RUST]: 0.29.0
    - @tauri-apps/api [NPM]: 2.0.0-rc.2
    - @tauri-apps/cli [NPM]: 2.0.0-rc.4

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```
    
It also detects my device as two
    
![image](https://github.com/user-attachments/assets/992c7c3f-cc33-408c-9c3b-eac5ea1ae9c1)

Connection fails on either option chosen

**Comment by jljorgenson18** [comment]
I'm also getting this error, but I am not sure if its because I'm using https locally for a self signed cert or not. I am running Vite locally for my dev url and using the --host option to open up the network. I can hit the url with Safari directly but I need to accept the cert first. I don't see anything in the logs related to certs or https so it seems like a network issue.

I'm on 2.0.0-rc.7

**Comment by tweidinger** [comment]
>  https locally for a self signed cert

Sounds maybe unrelated, as these need to be added to the system CA store as webviews (not browsers) just block insecure connection by default (afaik).

**Comment by jljorgenson18** [comment]
@tweidinger I think the issue is in Tauri still but I'm not sure. I was able to install the right certs and get everything trust on the simulator but Tauri just can't pick it over https. I confirmed the connection can be made just fine over http at the same port. I think there may be a setting needed for webviews to handle https as well but I am not sure which flags are needed.

**Comment by MirazMac** [comment]
Edit: Solved by setting the host manually in `vite.config.js`. Also had to Allow the ports `1420`, `1421` in Windows Firewall.

Facing the same issue. Tried on both android emulator and a real device.

```shell
[✔] Environment
    - OS: Windows 10.0.19045 x86_64 (X64)
    ✔ WebView2: 128.0.2739.67
    ✔ MSVC: Visual Studio Build Tools 2019
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.14.0
    - npm: 9.4.1

[-] Packages
    - tauri 🦀: 2.0.0-rc.10
    - tauri-build 🦀: 2.0.0-rc.9
    - wry 🦀: 0.43.1
    - tao 🦀: 0.30.0
    - @tauri-apps/api : 2.0.0-rc.4
    - @tauri-apps/cli : 2.0.0-rc.12

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-shell : 2.0.0-rc.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite

**Comment by LazeKer** [comment]
I personnaly solved it, on windows 11, by using the local address `127.0.0.1` 

(Angular project)
package.json
```json
{
...
  "scripts": {
    "dev": "ng serve --host=127.0.0.1",
  }
...
}
```

tauri.config.json
```json
{
...
  "build": {
    "devUrl": "http://127.0.0.1:4200",
    "beforeDevCommand": "yarn dev",
  }
...
}
```

`tauri android dev`

**Comment by pierrejoye** [comment]
Just in case someone went through this, as of today's latest RC release, it can still happen (windows 11), using npm, this makes it works (it exposes through all interfaces, like 0.0.0.0 would do, not sure why it does not here):

```json
 "build": {
    "beforeDevCommand": "npm run dev -- --host",
    "devUrl": "http://127.0.0.1:1420",
    "beforeBuildCommand": "npm run build",
    "frontendDist": "../dist"
  },
```

**Comment by yunxpeng** [comment]
Same issue with me. Just restart your computer, or try closing your VPN and then restarting it. I fixed it by restarting my computer.

**Comment by Tshameless** [comment]
guys,i change vite.config.ts and tauri.config.json，then slove this problem,just try it.
![image](https://github.com/user-attachments/assets/478ff842-1660-439c-9066-2625b7ba2eb4)
![image](https://github.com/user-attachments/assets/d896fabd-b60d-42a4-a1ec-72168199e1d3)

**Comment by drumnicorn** [comment]
Just delete /node_modules, /gen and /target and rebuild, worked for me!

**Comment by jerry-lllman** [comment]
Its work for me  

"build": {
    "beforeDevCommand": "pnpm dev --host",
    "devUrl": "http://<your host>",
    "beforeBuildCommand": "pnpm build",
    "frontendDist": "../dist"
  },
<img width="481" alt="image" src="https://github.com/user-attachments/assets/4a9967a1-93c3-4cc0-b01c-0b3c18c85063">

**Comment by samuelhh** [comment]
add --host in package.json
![20241030110659](https://github.com/user-attachments/assets/99019483-a73d-4d3d-b792-51f0c25ab922)

![20241030110714](https://github.com/user-attachments/assets/5a2777a1-b3bb-4c42-9064-604d8fe5321e)

**Comment by drumnicorn** [comment]
Using `--host 0.0.0.0` is even better

**Comment by PleahMaCaka** [comment]
In my case, the Wi-Fi extender was causing this problem. Everything worked fine after shutting it down.

**Comment by leofaraf** [comment]
windows 11, helped same:
"devUrl": "http://127.0.0.1:1420"

> I personnaly solved it, on windows 11, by using the local address `127.0.0.1`
> 
> (Angular project) package.json
> 
> ```json
> {
> ...
>   "scripts": {
>     "dev": "ng serve --host=127.0.0.1",
>   }
> ...
> }
> ```
> 
> tauri.config.json
> 
> ```json
> {
> ...
>   "build": {
>     "devUrl": "http://127.0.0.1:4200",
>     "beforeDevCommand": "yarn dev",
>   }
> ...
> }
> ```
> 
> `tauri android dev`

**Comment by hydra1983** [comment]
Still encountering the same error on iOS devices.

Here is the output of the `tauri info` command:
```bash
pnpm tauri info                                                                                                                                                                                                 ─╯

[✔] Environment
    - OS: Mac OS 15.2.0 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.85.0 (4d91de4e4 2025-02-17)
    ✔ cargo: 1.85.0 (d73d2caf9 2024-12-31)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.14.0
    - pnpm: 10.4.1
    - npm: 10.7.0

[-] Packages
    - tauri 🦀: 2.2.5
    - tauri-build 🦀: 2.0.5
    - wry 🦀: 0.48.1
    - tao 🦀: 0.31.1
    - @tauri-apps/api : 2.2.0
    - @tauri-apps/cli : 2.2.7

[-] Plugins
    - tauri-plugin-opener 🦀: 2.2.5
    - @tauri-apps/plugin-opener : 2.2.5

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Webpack

[-] iOS
    - Developer Teams: XX (ID: XXXXXXXXX)
```

The issue was resolved by adding the following configuration to `tauri.conf.json`

```json
"plugins": {
    "@tauri-apps/plugin-http": {
      "proxy": {
        "all": {
          "url": "http://192.168.0.102:1420"
        }
      }
    }
  }
```

Could someone please provide a network topology diagram illustrating the development server and the real/simulator devices?

Additional Note: The app runs correctly in the iOS simulator without the plugin configuration.

**Comment by hydra1983** [comment]
following [Development Server for Mobile](https://v2.tauri.app/blog/tauri-2-0-0-release-candidate/#development-server-for-mobile)

```bash
export TAURI_DEV_HOST=0.0.0.0
```

```
pnpm tauri ios dev --force-ip-prompt
```

```
Detected connected device: xxxxxxx (iPhone16,2) with target "aarch64-apple-ios"
✔ Failed to detect external IP, What IP should we use to access your development server? · xxxx:4977:e98f::2
    Info Using xxxx:4977:e98f::2 to access the development server.
    Info Replacing devUrl host with xxxx:4977:e98f::2. If your frontend is not listening on that address, try configuring your development server to use the `TAURI_DEV_HOST` environment variable or 0.0.0.0 as host.
    Running BeforeDevCommand (`pnpm dev`)

> joblist@0.1.0 dev /Users/xxx/workspace/xxx/scm/gitlab/xxx-dev/xxx-mono/apps/appxxx
> vite


  VITE v6.1.1  ready in 130 ms

  ➜  Network: http://[xxxx:4977:e98f::2]:1420/
    Warn Waiting for your frontend dev server to start on http://[xxxx:4977:e98f::2]:1420/...
    Warn Waiting for your frontend dev server to start on http://[xxxx:4977:e98f::2]:1420/...
```

I have iOS device connected to my mac.

Please provide a sample in the above article or provide another doc to introduce the new mechanism, thank you.

**Comment by bordumb** [comment]
I'm seeing the same thing 

It would be great if this configuration was handled with some sensible defaults when initializing the project + good error handling

**Comment by Xmagnum2** [comment]
On Android, I had commented out the 
```
<uses-permission android:name="android.permission.INTERNET" />
```
in the AndroidManifest.xml, and when I restored it, everything worked.

**Comment by KRTirtho** [comment]
For them who are setting `npm dev --host` yet still getting the error, allow `1420` or the port in `vite.config.ts` for inbound and outbound traffic through your system's firewall.

As I am using `ufw`, thus a simple `sudo ufw allow 1420` saved (did not!) me 4 hours of useless workarounds!
