### ISSUE TITLE
[bug] TypeError: undefined is not an object (evaluating 'window.__TAURI_INTERNALS__.invoke')

### ISSUE THREAD

**Issue by shandyz** [tauri-apps/tauri#9513]
### TypeError: undefined is not an object (evaluating 'window.__TAURI_INTERNALS__.invoke')

Couldn't connect to Database. Error appears when trying to load Database, database is in basedir. Could somebody help me?
Thanks in advance.

```
async function load_db() {
    // try {
      const dbExists = await exists('test.db', { dir: BaseDirectory.AppData });
      const baseDir = await appDataDir();
    console.log('Base directory:', baseDir);
      console.log("dbExists - ", dbExists);
      const db2 =  Database.get('sqlite:test.db');
      console.log("db2 - ", db2);
// error here
      const db = await Database.load('sqlite:test.db');
      console.log("db - ", db);
      const result = await db.select("SELECT privkey FROM accs");
      console.log("sql result - ", result);
      await db.close();
      // setsqldata(result);
    // } catch (error) {
    //   console.error("Error executing SQL query:", error);
    // }
  }
```
<img width="1436" alt="Screenshot 2024-04-19 at 22 26 05" src="https://github.com/tauri-apps/tauri/assets/44035407/342964a4-4c89-4fe1-9487-c5f2a21a1dbc">

### Reproduction

> async function load_db() {
    // try {
      const dbExists = await exists('test.db', { dir: BaseDirectory.AppData });
      const baseDir = await appDataDir();
    console.log('Base directory:', baseDir);
      console.log("dbExists - ", dbExists);
      const db2 =  Database.get('sqlite:test.db');
      console.log("db2 - ", db2);
    //error here
      const db = await Database.load('sqlite:test.db');
      console.log("db - ", db);
      const result = await db.select("SELECT privkey FROM accs");
      console.log("sql result - ", result);
      await db.close();
      // setsqldata(result);
    // } catch (error) {
    //   console.error("Error executing SQL query:", error);
    // }
  }

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.4.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 21.4.0
    - pnpm: 8.15.0
    - yarn: 1.22.19
    - npm: 10.5.1

[-] Packages
    - tauri [RUST]: 1.6.1
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.8
    - tauri-cli [RUST]: 1.5.9
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.11

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../out
    - devPath: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Webpack
```

**Comment by FabianLars** [comment]
This error means that a library or plugin (in this case the sql plugin) is for v2 while you're using tauri v1. Try removing the npm package and then follow these steps carefully: https://github.com/tauri-apps/plugins-workspace/tree/v1/plugins/sql#install
