### ISSUE TITLE
Draggable component fly away on linux with svelte

### ISSUE THREAD

**Issue by noahfraiture** [tauri-apps/tauri#9522]
### Describe the bug

Hello,

When I make a draggable box with svelte it flies away when I try to move it. It perfectly works on my web browser, but when I make a small move when trying to move the box on linux, it go straight down right very fast, no matter the direction of my mouse.

### Reproduction

On Linux, make a draggable component following this [resources](https://svelte.dev/repl/7d674cc78a3a44beb2c5a9381c7eb1a9?version=4.2.15)
```
<script>
	export let left = 100;
	export let top = 100;

	let moving = false;

	function onMouseDown() {
		moving = true;
	}

	function onMouseMove(e) {
		if (moving) {
			left += e.movementX;
			top += e.movementY;
		}
	}

	function onMouseUp() {
		moving = false;
	}

	// 	$: console.log(moving);
</script>

<section on:mousedown={onMouseDown} style="left: {left}px; top: {top}px;" class="draggable">
	<slot></slot>
</section>

<svelte:window on:mouseup={onMouseUp} on:mousemove={onMouseMove} />

<style>
	.draggable {
		user-select: none;
		cursor: move;
		border: solid 2px gray;
		position: absolute;
	}
</style>
```
```
<script>
	import Position from '../lib/Position.svelte';
	import Box from '../lib/Box.svelte';
</script>

<h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>

<h1>Welcome to SvelteKit</h1>
<Position />
<Box>
	<h1>Box</h1>
</Box>
```

As you can see I tried an alternative way with a rust function to get the mouse position my the crates I've been using don't work properly.

### Expected behavior

The box should be draggable like in the browser behavior

### Full `tauri info` output

```text
[✔] Environment
    - OS: EndeavourOS Rolling Release X64
    ✔ webkit2gtk-4.0: 2.44.1
    ✔ rsvg2: 2.58.0
    ✔ rustc: 1.77.1 (7cf61ebde 2024-03-27)
    ✔ cargo: 1.77.1 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (2024-03-12)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 21.7.2
    - yarn: 1.22.22
    - npm: 10.5.2
    - bun: 1.0.30

[-] Packages
    - tauri [RUST]: 1.6.1
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.8
    - tauri-cli [RUST]: 1.5.11
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.11

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../build
    - devPath: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

### Additional context

Also, often when I start my the application, the box isn't a box but a simple header. If I update it for instance by changing the thickness of the box, it will become a box.
If you have alternatives, I'm happy with it

**Comment by FlippingBinary** [comment]
Hmm. This works on Windows, but not Linux. The `movementX` and `movementY` appear to be equivalent to `screenX` and `screenY` in my testing in Manjaro Linux (not sure if it's a coincidence that we're both using Arch distros). This explains why the position shoots off. It's not giving you the movement distance you expect. To work around the problem, you could keep track of the last reported position of `clientY`, `pageY`, `offsetY`, or `screenY` along with the corresponding `X` value and use the difference to adjust the `left` and `top` variables of your moveable box accordingly.

**Comment by FlippingBinary** [comment]
Also, this is a duplicate issue: https://github.com/tauri-apps/tauri/issues/5063

**Comment by noahfraiture** [comment]
Thank you indeed I didn't find this issue
