### ISSUE TITLE
Must move the window to get new rust result 

### ISSUE THREAD

**Issue by noahfraiture** [tauri-apps/tauri#9523]
### Describe the bug

Hello, I made a recent PR https://github.com/tauri-apps/tauri/issues/9522 about making a draggable box. This is a PR for another try to have this draggable box. This time via rust. I'm using svelte and I'm on linux. Here's my code :
```html
<script>
	import { invoke } from '@tauri-apps/api/tauri';

	let position = [0, 0];

	async function update() {
		position = await invoke('mouse_position', {});
	}
</script>

<div>
	<button on:click={update}>Update</button>
	<p>{position}</p>
</div>
```
```rs
use mouse_position::mouse_position::Mouse;

#[tauri::command]
fn mouse_position() -> [i32; 2] {
  let position = Mouse::get_mouse_position();

  match position {
    Mouse::Position { x, y } => {
      println!("{}, {}", x, y);
      [x, y]
    }
    Mouse::Error => [0; 2],
  }
}
```
As you can see I simply get the mouse position and display in it the terminal and in the webapp. The issue is the following : I have to move the window to get new results. If I move my mouse and click on the button, I will get the same results over and over even I move the mouse. I must move the window (even if it's to put it at the exact same position) to get new results on next click. 

### Reproduction

Make a rust function that get the mouse position, and a button in svelte that call this function, and see that the result don't change when you click multiple times on the button

### Expected behavior

The result must be different every time I click on the button if the mouse isn't on the same position

### Full `tauri info` output

```text
[✔] Environment
    - OS: EndeavourOS Rolling Release X64
    ✔ webkit2gtk-4.0: 2.44.1
    ✔ rsvg2: 2.58.0
    ✔ rustc: 1.77.1 (7cf61ebde 2024-03-27)
    ✔ cargo: 1.77.1 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (2024-03-12)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 21.7.2
    - yarn: 1.22.22
    - npm: 10.5.2
    - bun: 1.0.30

[-] Packages
    - tauri [RUST]: 1.6.1
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.8
    - tauri-cli [RUST]: 1.5.11
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.11

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../build
    - devPath: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

### Additional context

I tried with different function, like a simple random number generator, and this works perfectly, there's no need to move the window

**Comment by amrbashir** [comment]
if you don't move the window, then the button stays in the same place, and if the button stays in the same place, then you will get the same result. 

anyways, the crate used to get mouse position is not a crate of ours and so this is out of our scope.

**Comment by noahfraiture** [comment]
No, I'm taking the mouse position, not the button position

**Comment by amrbashir** [comment]
yes, but you only update it when you click the button, and if the button position hasn't changed then the place you click it is the same and so the mouse position will be the same.

If you want to get the mouse position in real-time, try making a loop and update the position each second or something.

**Comment by noahfraiture** [comment]
The button is large enough. I also try that
