### ISSUE TITLE
 Error: cargo install tauri-cli --version "^2.0.0-beta"

### ISSUE THREAD

**Issue by songjiachao** [tauri-apps/tauri#9567]
### Describe the bug

 Error: cargo install tauri-cli --version "^2.0.0-beta"

Compiling common-path v1.0.0
error[E0308]: mismatched types
   --> C:\Users\11091628\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-cli-2.0.0-beta.14\src\helpers\flock.rs:343:28
    |
343 |       let ret = UnlockFile(file.as_raw_handle(), 0, 0, !0, !0);
    |                 ---------- ^^^^^^^^^^^^^^^^^^^^ expected `winapi::ctypes::c_void`, found `std::ffi::c_void`
    |                 |
    |                 arguments to this function are incorrect
    |
    = note: `std::ffi::c_void` and `winapi::ctypes::c_void` have similar names, but are actually distinct types
note: `std::ffi::c_void` is defined in crate `core`
   --> C:\Users\11091628\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\ffi\mod.rs:173:1
    |
173 | pub enum c_void {
    | ^^^^^^^^^^^^^^^
note: `winapi::ctypes::c_void` is defined in crate `winapi`
   --> C:\Users\11091628\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winapi-0.3.9\src\lib.rs:38:5
    |
38  |     pub enum c_void {}
    |     ^^^^^^^^^^^^^^^
note: function defined here
   --> C:\Users\11091628\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winapi-0.3.9\src\um\fileapi.rs:519:12
    |
519 |     pub fn UnlockFile(
    |            ^^^^^^^^^^

error[E0308]: mismatched types
   --> C:\Users\11091628\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-cli-2.0.0-beta.14\src\helpers\flock.rs:355:28
    |
355 |       let ret = LockFileEx(file.as_raw_handle(), flags, 0, !0, !0, &mut overlapped);
    |                 ---------- ^^^^^^^^^^^^^^^^^^^^ expected `winapi::ctypes::c_void`, found `std::ffi::c_void`
    |                 |
    |                 arguments to this function are incorrect
    |
    = note: `std::ffi::c_void` and `winapi::ctypes::c_void` have similar names, but are actually distinct types
note: `std::ffi::c_void` is defined in crate `core`
   --> C:\Users\11091628\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\ffi\mod.rs:173:1
    |
173 | pub enum c_void {
    | ^^^^^^^^^^^^^^^
note: `winapi::ctypes::c_void` is defined in crate `winapi`
   --> C:\Users\11091628\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winapi-0.3.9\src\lib.rs:38:5
    |
38  |     pub enum c_void {}
    |     ^^^^^^^^^^^^^^^
note: function defined here
   --> C:\Users\11091628\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winapi-0.3.9\src\um\fileapi.rs:440:12
    |
440 |     pub fn LockFileEx(
    |            ^^^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `tauri-cli` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `tauri-cli v2.0.0-beta.14`, intermediate artifacts can be found at `C:\Users\11091628\AppData\Local\Temp\cargo-installHbGCgj`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
PS C:\Users\11091628>

### Full `tauri info` output

```text
PS C:\Users\11091628> cargo tauri info
error: no such command: `tauri`

        Did you mean `miri`?

        View all installed commands with `cargo --list`
        Find a package to install `tauri` with `cargo search cargo-tauri`
PS C:\Users\11091628>
```

![屏幕截图 2024-04-25 154526](https://github.com/tauri-apps/tauri/assets/70792885/fb60d044-d70b-46e2-9df5-167f25b1084d)

**Comment by FabianLars** [comment]
can you check if `cargo install tauri-cli --version "^2.0.0-beta" --locked` works? (It's about the --locked flag)

**Comment by songjiachao** [comment]
it worked, thank you very much.
