### ISSUE TITLE
[bug] Can't play blob audio - browser says "NotSupportedError: The operation is not supported."

### ISSUE THREAD

**Issue by oddpxl** [tauri-apps/tauri#9573]
### Describe the bug

Trying to play() an audio blob - makes the browser go "NotSupportedError: The operation is not supported."

( correct blob and mime type - it works outside Tauri )

### Reproduction

const audioUrl = URL.createObjectURL(audioBlob);
currentAudio = new Audio(audioUrl);
currentAudio.play();

### Expected behavior

The audio should play.

### Full `tauri info` output

```text
> tauri "info"
[✔] Environment
    - OS: Mac OS 14.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.77.1 (7cf61ebde 2024-03-27)
    ✔ cargo: 1.77.1 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 21.7.1
    - pnpm: 8.15.5
    - npm: 10.5.1

[-] Packages
    - tauri [RUST]: 2.0.0-beta.14
    - tauri-build [RUST]: 2.0.0-beta.11
    - wry [RUST]: 0.39.0
    - tao [RUST]: 0.27.0
    - tauri-cli [RUST]: 1.5.11
    - @tauri-apps/api [NPM]: 2.0.0-beta.7
    - @tauri-apps/cli [NPM]: 2.0.0-beta.12

[-] App
    - build-type: build
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: SolidJS
    - bundler: Vite
    
```

**Comment by FabianLars** [comment]
Please include the output of the `tauri info` command as required by the issue template. Things like these are almost always platform dependent.

**Comment by oddpxl** [comment]
@FabianLars Now added - sorry, I'm new to Tauri and didn't know about the Info command...now I do...thank you ! :)

..also now double checking I'm getting a valid blob from the API I'm hitting ( all other data received seem fine )

**Comment by FabianLars** [comment]
Do you know which Audio codec the blob has? blobs support should be the same as "normal" files, so it _should_ mean that webkit doesn't support it yet (did you test it in safari?)

**Comment by oddpxl** [comment]
@FabianLars I saved the blob to a file and gave it to https://google.github.io/magika/  - turns out the API is sending me a wav !! and not an MP4 ( as the API claims ) - changed the mime type to audio/wav - lo and behold - audio playing.

So turns out Tauri works fine - and we can close this ticket - sorry for the confusion !!

( safari is horrible at error messages )

**Comment by FabianLars** [comment]
Cool, glad it's working now! And yes, safari is indeed horrible at error messages, but tbh chromium isn't _that_ much better, it tends to throw cors errors in the funniest and most unrelated contexts.

**Comment by oddpxl** [comment]
All to keep us on our toes haha
Don't want to know how many hours lost until I checked the integrity that blob...   ..but hey upside is - I found Magika.

Have a great weekend Fabian ! :)

**Comment by FabianLars** [comment]
Thanks, you too!
