### ISSUE TITLE
Workers of type: module are not working as expected on Mac

### ISSUE THREAD

**Issue by aleph1** [tauri-apps/tauri#9579]
### Describe the bug

When instantiating a Worker with a type of “module”, the Worker is actually created as a “classic” Worker.

### Reproduction

[I have created a barebones example here: https://github.com/aleph1/tauri-worker-module](https://github.com/aleph1/tauri-worker-module).

When opening [src/index.html](https://github.com/aleph1/tauri-worker-module/blob/main/src/index.html) in Safari 15.3 on macOS 11.6.3 the Worker loads as a module and the code works as expected.

When executing `npm run tauri dev` the worker loads in classic mode and throws an error based on expecting `import` to be a function, versus allowing import { variableName } from 'module.js' fomat. Inspect the page and see the console for the error (SyntaxError: Unexpected token '{'. import call expects exactly one argument.).

### Expected behavior

The Worker should load as a module.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 11.6.3 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04) (Homebrew)
    ✔ cargo: 1.76.0
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 16.17.1
    - yarn: 3.1.1
    - npm: 8.15.0

[-] Packages
    - tauri [RUST]: 1.6.2
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.8
    - tao [RUST]: 0.16.9
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 1.5.12

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../src
    - devPath: ../src
```

### Additional context

Tauri with error:
<img width="912" alt="tauri-error" src="https://github.com/tauri-apps/tauri/assets/485722/8af46f10-c031-474a-968f-3c74c294ae9c">

Browser with no error:
<img width="1120" alt="browser-no-error" src="https://github.com/tauri-apps/tauri/assets/485722/7f945679-7372-4fac-8cb9-06cb56b49bd9">

**Comment by FabianLars** [comment]
The webview on macos 11 is equivalent to safari 14 but support for modules in workers was added in safari 15 -> macos 12 webview. Nothing we can do here as long as we use wkwebview.

**Comment by aleph1** [comment]
Understood, thank you!
