### ISSUE TITLE
[feat][v2] automatically rebuild webview-dist 

### ISSUE THREAD

**Issue by pronebird** [tauri-apps/tauri#9580]
### Describe the problem

Hi,

It seems that each time we change `webview-src/index.ts` we have to run `npm run build` manually to rebuild the `webview-dist/index.d.ts`.

### Describe the solution you'd like

It would be great if `tauri_plugin::Builder::new(COMMANDS).build()` could automatically run `npm run build` when `webview-src/*.ts` contents change.

### Alternatives considered

Modify `build.rs` and run `npm run build` manually, i.e:

```rs
const COMMANDS: &[&str] = &[ .. ];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();

    println!("cargo:rerun-if-changed=webview-src");
    std::process::Command::new("npm")
        .arg("run")
        .arg("build")
        .spawn()
        .unwrap();
}
```

**Comment by amrbashir** [comment]
I don't think we should add this because plugin authors could choose 1 of infinite number of ways to build their plugin frontend code. The alternative way should be used or manually build when you need.
