### ISSUE TITLE
[bug] Existing CFBundleDocumentTypes break the app for builds that exist outside the app store

### ISSUE THREAD

**Issue by jessfraz** [tauri-apps/tauri#9587]
### Describe the bug

So I declare in our src-tauri a custom Info.plist https://github.com/KittyCAD/modeling-app/pull/2263/files#diff-8d404d6f9439bbe1fa6b53fe13ad91614422479c67614eef823659ca2cd6dc31 as seen here.

Now in this PR I added the `CFBundleDocumentTypes` key. And since adding that key (I can confirm its that key and not others just thru deleting it entirely) the app no longer will open with `tauri dev` or `tauri build` on their own. HOWEVER, and this is the weird part if I do the whole song and dance and get the build up to the app store in the right state it DOES run.

Now the weird thing is, y'all use this key on your own anyways: https://github.com/tauri-apps/tauri/blob/6d5a396ae92c03f1a89eaa13d5226381bced6ec6/tooling/bundler/src/bundle/macos/app.rs#L241

### Reproduction

https://github.com/KittyCAD/modeling-app/pull/2263

Sorry while this is not a minimal reproduction it is a reproduction.

### Expected behavior

I would expect the app to still open with these keys. Or at least throw an error.

### Full `tauri info` output

```text
$ /Users/macinatormax/kittycad/modeling-app/node_modules/.bin/tauri info

[✔] Environment
    - OS: Mac OS 14.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.77.0 (aedd173a2 2024-03-17)
    ✔ cargo: 1.77.0 (3fe68eabf 2024-02-29)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 21.7.1
    - yarn: 1.22.22
    - npm: 10.5.0
    - bun: 1.0.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.16
    - tauri-build [RUST]: 2.0.0-beta.13
    - wry [RUST]: 0.39.3
    - tao [RUST]: 0.27.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.8
    - @tauri-apps/cli [NPM]: 2.0.0-beta.13

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:3000/
    - framework: React
    - bundler: Vite
✨  Done in 4.61s.
```
```


### Stack trace

```text
there is no trace
```

### Additional context

happy to help debug in any way

**Comment by pewsheen** [comment]
The given `NSDocumentClass` seemed to be invalid. Perhaps it's `NSDocument` or maybe remove the arrtibute?

**Comment by jessfraz** [comment]
that was it! thank you!
