### ISSUE TITLE
[bug] `always_on_bottom` fails to set window to bottom when created on Windows

### ISSUE THREAD

**Issue by Charlie-XIAO** [tauri-apps/tauri#9597]
### Describe the bug

Transferred from [Discord](https://discordapp.com/channels/616186924390023171/1233865878232367225).

On Windows, *always on bottom* fails to set the window to bottom when it is initially created. Afterwards it works fine. Alternatively if one further sets `.visible(false)` then show it later, it will be automatically on the bottom but there is sometimes a flickering.

### Reproduction

Create an app with `create-tauri-app` and change `src-tauri/src/main.rs` to:

```rust
use tauri::{Builder, WebviewUrl, WebviewWindowBuilder};

fn main() {
    Builder::default()
        .setup(|app| {
            WebviewWindowBuilder::new(app, "main", WebviewUrl::App("index.html".into()))
                .always_on_bottom(true)
                .build()?;
            Ok(())
        })
        .run(tauri::generate_context!())
        .unwrap();
}
```

With the above the window is not initially on bottom. Then try

```rust
use tauri::{Builder, WebviewUrl, WebviewWindowBuilder};

fn main() {
    Builder::default()
        .setup(|app| {
            let webview = WebviewWindowBuilder::new(app, "main", WebviewUrl::App("index.html".into()))
                .always_on_bottom(true)
                .visible(false)
                .build()?;
            webview.show()?;
            Ok(())
        })
        .run(tauri::generate_context!())
        .unwrap();
}
```

This will set the window initially to the bottom, but sometimes there is a flickering.

### Expected behavior

`.always_on_bottom(true)` should initially set the window to bottom, without using the trick.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 123.0.2420.97
    ✔ MSVC: Visual Studio 生成工具 2022
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.10.0
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 2.0.0-beta.16
    - tauri-build [RUST]: 2.0.0-beta.13
    - wry [RUST]: 0.39.3
    - tao [RUST]: 0.27.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.9
    - @tauri-apps/cli [NPM]: 2.0.0-beta.13

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by amrbashir** [comment]
you need to pair it with `.focused(false)` otherwise the window will be created with focus and will be placed on top until it loses focus

**Comment by Charlie-XIAO** [comment]
Thanks! That indeed works, but the window still flickers upon creation. Does that have a solution?

**Comment by amrbashir** [comment]
Not sure what flicker you mean, can you show a video?

**Comment by Charlie-XIAO** [comment]
Sorry my screen recording software can only capture one app so I have to use my phone:

https://github.com/tauri-apps/tauri/assets/108576690/c76ef12d-0d86-4616-8458-5ab730421cf2

**Comment by Charlie-XIAO** [comment]
Sorry @amrbashir, `.focused(false)` does solve the issue in the snippet above. I've just narrowed down my app and found that to reproduce the "flickering" problem we further need to set `.maximized(true)`. Note that `.focused(false)` further causes problems when we call `.set_ignore_cursor_events(true/false)`. Please try the following:

```rust
fn main() {
    tauri::Builder::default()
        .setup(|app| {
            let main = WebviewWindowBuilder::new(app, "main", WebviewUrl::App("index.html".into()))
                .maximized(true) // causes the flickering
                .always_on_bottom(true)
                .focused(false)
                .build()?;
            sleep(Duration::from_secs(2));
            main.set_ignore_cursor_events(true)?; // some unexpected motions
            sleep(Duration::from_secs(2));
            main.set_ignore_cursor_events(false)?; // same as above
            Ok(())
        })
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

Please let me know if you cannot reproduce.
