### ISSUE TITLE
[bug] Couldn't find callback id x in window. This happens when the app is reloaded while Rust is running an asynchronous operation

### ISSUE THREAD

**Issue by rtmotiondev** [tauri-apps/tauri#9613]
### Describe the bug

When using tauri-plugin-websocket-api and triggering a window reload, I get a constant stream of messages like "[Warning] [TAURI] Couldn't find callback id 1632071350 in window. This happens when the app is reloaded while Rust is running an asynchronous operation.". 

If I disable the websocket I get no messages. I tried listening to beforeunload but that doesn't seem to fire.

### Expected behavior

No warnings

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.77.2 (25ef9e3d8 2024-04-09)
    ✔ cargo: 1.77.2 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.11.0
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 1.6.2
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.8
    - @tauri-apps/api [NPM]: 1.5.4
    - @tauri-apps/cli [NPM]: 1.5.12

[-] App
    - build-type: bundle
    - CSP: default-src 'self'; script-src 'self'; connect-src 'self' server.relativemotion.app dev.server.relativemotion.app ws:; img-src https://* data:; frame-src *; child-src 'self'; font-src 'self'; style-src-elem 'self'; style-src 'self'; object-src 'none'; upgrade-insecure-requests;
    - distDir: ../src
    - devPath: ../src
    - bundler: Webpack
```

**Comment by rtmotiondev** [comment]
The solution is:

`window.addEventListener('unload', function (e) {})`

It would be nice if it was documented in tauri. Unsure if it's cross platform but it works in macos.

**Comment by WofWca** [comment]
Related:
- https://github.com/tauri-apps/plugins-workspace/issues/1507
- https://github.com/tauri-apps/tauri/issues/10266
