### ISSUE TITLE
[bug] terminal output missing in release build on Windows 10

### ISSUE THREAD

**Issue by happybeing** [tauri-apps/tauri#9622]
### Describe the bug

I'm getting different behaviour using dev and release builds of my app on Windows 10, but the same (expected) behaviour in both on Ubuntu.

My Tauri app has two modes, command line and GUI window. So if you give the command certain options on the command line it does one thing (e.g.` awe --help` prints command usage) but if you don't give it any parameters (or pass certain options / parameters) it opens an GUI window that interacts with the user. On Ubuntu this has always worked as expected in dev and release builds.

Using `cargo tauri dev` things work as expected on Windows 10. [EDIT: and then while filing this issue, `cargo tauri dev -- -- --help` stopped producing terminal output too, although nothing has been changed in my project (see under final 'EDIT' below).]

With the release build, if I run the app with parameters that invoke the window, it works *almost* as expected 🥳 

**First problem:** The window opens and looks good, but the terminal prompt returns immediately rather than waiting for me to close the Window.  

**Second problem:** if I provide CLI parameters or options (e.g. `awe --help`) that should cause some output to the terminal, nothing is printed to the terminal (e.g. from Rust `println!()` statements or `clap`, nor any errors). All I see is the next command prompt. This makes debugging it difficult too!

So for a release build it appears that neither `clap` CLI processing, nor my use of `println!()` produce output on Windows 10. If I do the same things but using `cargo tauri dev` the terminal output appears as expected, and the terminal prompt doesn't appear until I close the GUI window. 

I'm using tauri-cli 1.5.12.

### Not High Priority for me
At this stage this is only a demo and Windows support is not vital, and I plan to move to Tauri v2 soon. So I am posting this issue without expecting much to happen, more for information than anything or in case there's an obvious solution I didn't find. But once I switch to Tauri v2 I'll return and update this.

### EDIT:
Before posting I ran `cargo tauri dev -- -- --help` and it has stopped producing any output to the terminal. I've had no problems for several go's at this, but now it gives no output. So I wonder if there's a silent resource issue somewhere. I've no clue why that changed. I haven't changed anything in the code - all I've been doing is filing this issue and running the commands I've been reporting above to check their behaviour.

Also, `cargo tauri info` hung at the line with `npm` version until I hit Ctrl-C to copy and then the rest appeared. I haven't used Windows for years so no idea what these quirks might be about. 🤷‍♂️ 

### Reproduction

I'll come back if Tauri v2 has the same issue.

### Expected behavior

Release build running `awe --help` should print app usage, just as for `cargo tauri dev -- -- --help`. 

EDIT: both have now stopped producing output to the terminal. 🤦‍♂️ 

### Full `tauri info` output

```text
> cargo tauri info

[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 124.0.2478.67
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.77.2 (25ef9e3d8 2024-04-09)
    ✔ cargo: 1.77.2 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 22.0.0
    - npm: 10.5.1

[-] Packages
    - tauri [RUST]: 1.6.1
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.8
    - tauri-cli [RUST]: 1.5.12
    - @tauri-apps/api [NPM]: 1.5.3 (outdated, latest: 1.5.4)
    - @tauri-apps/cli [NPM]: 1.5.12

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../build
    - devPath: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

**Comment by amrbashir** [comment]
See https://github.com/tauri-apps/tauri/issues/8305#issuecomment-1826871949
