### ISSUE TITLE
[bug][v2] dragDropEnabled: false does not work on macOS

### ISSUE THREAD

**Issue by pronebird** [tauri-apps/tauri#9644]
### Describe the bug

`dragDropEnabled: false` in tauri.config.json inside of window configuration has no effect on macOS.   Is there any way to stop things from being dropped onto the app?

### Reproduction

Fire tauri app `npm run tauri dev` and drag some file on window. The window renders the dragged file. 😨 Then I hit backspace key to go back and the app crashes 😢 

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.79.0-nightly (0d8b3346a 2024-04-14)
    ✔ cargo: 1.79.0-nightly (48eca1b16 2024-04-12)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: nightly-x86_64-apple-darwin (default)
    - node: 21.7.1
    - npm: 10.5.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.17 (no manifest)
    - tauri-build [RUST]: 2.0.0-beta.13 (no manifest)
    - wry [RUST]: 0.39.3 (no manifest)
    - tao [RUST]: 0.27.1 (no manifest)
    - @tauri-apps/api [NPM]: 2.0.0-beta.11
    - @tauri-apps/cli [NPM]: 2.0.0-beta.15

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
```

**Comment by FabianLars** [comment]
fileDropEnabled only disables tauri's "extra" file drop handler. If it's disabled then the browser native drag and drop apis/events still work and you'll need to listen to those drop events and call prevent_default (unless there's another way to do that, whatever works in a normal browser).
