### ISSUE TITLE
[docs] How to load image resource in v2

### ISSUE THREAD

**Issue by Arman19941113** [tauri-apps/tauri#9667]
we can use `convertFileSrc` to load local resources in v1

```jsx
function App() {
  const filepath = '/Users/arman/Downloads/test/sony.JPG'
  const url = convertFileSrc(filepath)

  return (
    <img src={url} alt="" />
  )
}
```

but `allowlist.protocol.asset` is not supported in v2

So this approach caused the issue

> Failed to load resource: unsupported URL

And I didn't find any approach to fix it
#7112

**Comment by Arman19941113** [comment]
The doc still recommends this unsupported configuration.

<img width="1079" alt="image" src="https://github.com/tauri-apps/tauri/assets/35905177/88a4d7f1-58a1-406f-bfa5-d9d54b74c8a6">

**Comment by FabianLars** [comment]
It's `app.security.assetProtocol` now. I hope we can move that into the capabilities to the other scopes but for now it's there.

**Comment by Arman19941113** [comment]
> It's `app.security.assetProtocol` now. I hope we can move that into the capabilities to the other scopes but for now it's there.

Thanks! It's helpful~

**Comment by AlpineVibrations** [comment]
> It's `app.security.assetProtocol` now. I hope we can move that into the capabilities to the other scopes but for now it's there.

this was helpful. thank you
