### ISSUE TITLE
When building a Tauri application using Windows 10 Enterprise Edition, it cannot run on Windows 7.[bug] 

### ISSUE THREAD

**Issue by muwoo** [tauri-apps/tauri#9692]
### Describe the bug

1. use Windows 10 Enterprise Edition
2. `yarn create tauri-app`
3.  `yarn install && yarn tauri build -t i686-pc-windows-msvc`
4. Install the application on Windows 7 using the built Windows installation package, and then launch the application.
5. Error: The Application was unable to start correctly (0xc0000005)

![image](https://github.com/tauri-apps/tauri/assets/21073039/b61e3b5f-d7c4-4e64-be40-09435b29b1ee)

### Full `tauri info` output

```text
$ tauri info

[✔] Environment
    - OS: Windows 10.0.19044 X64
    ✔ WebView2: 124.0.2478.80
    ✔ MSVC: Visual Studio ���ɹ��� 2022
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.12.2
    - yarn: 1.22.22
    - npm: 10.5.0

[-] Packages
    - tauri [RUST]: 1.6.3
    - tauri-build [RUST]: 1.5.2
    - wry [RUST]: 0.24.8
    - tao [RUST]: 0.16.9
    - @tauri-apps/api [NPM]: 1.5.4
    - @tauri-apps/cli [NPM]: 1.5.13

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
Done in 27.27s.
```

**Comment by FabianLars** [comment]
Can you try downgrading rust to 1.77.2? Asking because of <https://blog.rust-lang.org/2024/05/02/Rust-1.78.0.html#compatibility-notes>

**Comment by muwoo** [comment]
@FabianLars Thank you very much for your prompt response, the issue has been perfectly resolved. Thanks again!
