### ISSUE TITLE
[bug] Signature decoding error

### ISSUE THREAD

**Issue by sawsoh** [tauri-apps/tauri#9715]
### Describe the bug

I've follow everything on the updaters doc and yet stuck at the very final parts, yes I've look answer but still the answer is not really helping. Anyone experience this and able to guide me step by step? I even regenerate the key and still no idea what went wrong

### Expected behavior

Update works

### Full `tauri info` output

```text
Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 124.0.2478.80
    ✔ MSVC:
        - Visual Studio Build Tools 2019
        - Visual Studio Build Tools 2022
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.12.2
    - npm: 10.5.0

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0 (outdated, latest: 1.5.4)
    - @tauri-apps/cli [NPM]: 1.5.9 (outdated, latest: 1.5.13)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist/v-frame
    - devPath: http://localhost:1420/
    - framework: Angular
    - bundler: Webpack
```

### Additional context

Tauri are able to detect new updates, but it just failed at some point.

updater json
{
  "version": "1.1.3",
  "pub_date": "2024-05-09T12:29:53+01:00",
  "notes": "Updater Modifications",
  "platforms": {
    "windows-x86_64": {
      "signature": "https://v-sing-malaysia-picture.s3.ap-southeast-1.amazonaws.com/v_frame/v-frame_1.1.2_x64_en-US.msi.zip.sig",
      "url": "https://v-sing-malaysia-picture.s3.ap-southeast-1.amazonaws.com/v_frame/v-frame_1.1.2_x64_en-US.msi.zip"
    }
  }
}

tauri.conf.json
"updater":{
      "active" : true,
      "endpoints":[
        "https://v-sing-malaysia-picture.s3.ap-southeast-1.amazonaws.com/v_frame/updater.json"
      ],
      "dialog":true,
      "pubkey":"dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IDRBM0U4Mjk2NDUzQTZDNEMKUldSTWJEcEZsb0krU3JONHNPZk02MnRXS1ZHWTJOK2FmWUYvVkZQaG8xODlOSWd0OThsOGpPUlkK",
      "windows": {
        "installMode": "passive"
      }
    }

**Comment by amrbashir** [comment]
your `updater.json` includes the signature as a URL to the signature file but it expects the contents of the signature file not a URL to it.

**Comment by sawsoh** [comment]
> your `updater.json` includes the signature as a URL to the signature file but it expects the contents of the signature file not a URL to it.

Thx but how do I actually can get the content, or how the updater.json should looks like 😵

**Comment by amrbashir** [comment]
it should look like this, notice the signature field is set to the contents of the `.sig` file not a URL to it
```json
{
  "version": "1.1.3",
  "pub_date": "2024-05-09T12:29:53+01:00",
  "notes": "Updater Modifications",
  "platforms": {
    "windows-x86_64": {
      "signature": "dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVSTWJEcEZsb0krU3JUUGxXdGxxT0dNVmJUMTF5Z1ZrWjdTZmR5VmVWd0huVG42SzVOa0w2VytFODVrelVUNSs4aUhUa0VFQ2xOd0gwbEVEZ2wyQlRycVJYZ1pQRTJoMkFZPQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzE1MjQ2MDI1CWZpbGU6di1mcmFtZV8xLjEuMl94NjRfZW4tVVMubXNpLnppcApNQyszaTdvcmsvc1BueVVxaUJLeUJ2ZDI0THBmM0ZEek50aW8wNHJQcVptK3hTeE91QTFCM1hzVXpaVkNRVlZ1alZlUmxyeTRmdnM4V0VDMndYR1pEUT09Cg==",
      "url": "https://v-sing-malaysia-picture.s3.ap-southeast-1.amazonaws.com/v_frame/v-frame_1.1.2_x64_en-US.msi.zip"
    }
  }
}
```

**Comment by sawsoh** [comment]
> it should look like this, notice the signature field is set to the contents of the `.sig` file not a URL to it
> 
> ```json
> {
>   "version": "1.1.3",
>   "pub_date": "2024-05-09T12:29:53+01:00",
>   "notes": "Updater Modifications",
>   "platforms": {
>     "windows-x86_64": {
>       "signature": "dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVSTWJEcEZsb0krU3JUUGxXdGxxT0dNVmJUMTF5Z1ZrWjdTZmR5VmVWd0huVG42SzVOa0w2VytFODVrelVUNSs4aUhUa0VFQ2xOd0gwbEVEZ2wyQlRycVJYZ1pQRTJoMkFZPQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzE1MjQ2MDI1CWZpbGU6di1mcmFtZV8xLjEuMl94NjRfZW4tVVMubXNpLnppcApNQyszaTdvcmsvc1BueVVxaUJLeUJ2ZDI0THBmM0ZEek50aW8wNHJQcVptK3hTeE91QTFCM1hzVXpaVkNRVlZ1alZlUmxyeTRmdnM4V0VDMndYR1pEUT09Cg==",
>       "url": "https://v-sing-malaysia-picture.s3.ap-southeast-1.amazonaws.com/v_frame/v-frame_1.1.2_x64_en-US.msi.zip"
>     }
>   }
> }
> ```

Thx so much for correcting me on the path, instead of just enter URL, I have to open the sig file and paste the content inside. Maybe I was confused by the doc
