### ISSUE TITLE
[bug] v2 Updating dependencies causes size exceptions

### ISSUE THREAD

**Issue by Borber** [tauri-apps/tauri#9716]
### Describe the bug

When I upgraded to the latest dependencies, the rendering of the interface itself became larger and became 125% of the original, which is the dpi set by my system.

### Reproduction

old lock: 
[Cargo.txt](https://github.com/tauri-apps/tauri/files/15261707/Cargo.txt)

normal:
![image](https://github.com/tauri-apps/tauri/assets/30563826/4e9a3be1-3c74-4629-b8b8-12252a8e0870)

After upgrade:

[Cargo_new.txt](https://github.com/tauri-apps/tauri/files/15261764/Cargo_new.txt)

![image](https://github.com/tauri-apps/tauri/assets/30563826/9cd2bb1a-1b92-4f10-ad0f-a719eb8bebbb)

In fact, judging from the devtool, their values ​​are normal, but if you measure them directly, you will find that they are 125% of original.

### Expected behavior

correct size

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19044 X64
    ✔ WebView2: 124.0.2478.80
    ✔ MSVC: Visual Studio 生成工具 2022
    ✔ rustc: 1.80.0-nightly (f705de596 2024-04-30)
    ✔ cargo: 1.80.0-nightly (b60a15551 2024-04-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)       
    ✔ Rust toolchain: nightly-x86_64-pc-windows-msvc (default)
    - node: 20.11.0
    - pnpm: 9.1.0
    - yarn: 1.22.22
    - npm: 10.5.2
    - bun: 1.1.6

[-] Packages
    - tauri [RUST]: 2.0.0-beta.18
    - tauri-build [RUST]: 2.0.0-beta.14
    - wry [RUST]: 0.39.4
    - tao [RUST]: 0.27.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.11
    - @tauri-apps/cli [NPM]: 2.0.0-beta.15

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: SolidJS
    - bundler: Vite
```

**Comment by amrbashir** [comment]
please provide a reproduction

**Comment by Borber** [comment]
> please provide a reproduction

Wait a few minutes, I'll get ready

**Comment by Borber** [comment]
> please provide a reproduction

see this: 

https://github.com/Borber/tauri-reproduction/tree/master/9716/old

![image](https://github.com/tauri-apps/tauri/assets/30563826/eabb4d5b-91ce-4938-b89a-0149f78472ec)

https://github.com/Borber/tauri-reproduction/tree/master/9716/new

![image](https://github.com/tauri-apps/tauri/assets/30563826/ec63991c-17b0-43ce-9284-00b18779eb49)


Only the dependencies are different


1. The size of new is 125% of old
2. press esc to exit the program
3. It will appear on windows, but there seems to be no problem on macos.

**Comment by Borber** [comment]
@amrbashir Did I provide enough information?

**Comment by amrbashir** [comment]
yeah, thanks I will open a PR with a fix soon

**Comment by amrbashir** [comment]
can you try https://github.com/tauri-apps/wry/pull/1254 and see if it fixes the issue for you as well?

Add the following to your `Cargo.toml`
```
[patch.crates-io]
wry = { git = "https://github.com/tauri-apps/wry", branch = "fix/windows/resize-to-parent-physical" }
```

then run `cargo update -p wry` inside `src-tauri`

**Comment by Borber** [comment]
> can you try [tauri-apps/wry#1254](https://github.com/tauri-apps/wry/pull/1254) and see if it fixes the issue for you as well?
> 
> Add the following to your `Cargo.toml`
> 
> ```
> [patch.crates-io]
> wry = { git = "https://github.com/tauri-apps/wry", branch = "fix/windows/resize-to-parent-physical" }
> ```
> 
> then run `cargo update -p wry` inside `src-tauri`

Yes, it's fixed.  perfect.

**Comment by amrbashir** [comment]
fix has been released, run `cargo update -p wry` in `src-tauri`
