### ISSUE TITLE
[feat] Cargo command for bundler with non-tauri support

### ISSUE THREAD

**Issue by cornmonger** [tauri-apps/tauri#9727]
### Describe the problem

Tauri's bundler library (forked from cargo-bundle) might be the most up-to-date and well-maintained cross-compilation bundling solution in the Rust ecosystem right now.

The package's [documentation](https://github.com/tauri-apps/tauri/blob/dev/tooling/bundler) notes that the **tauri-bundler** library is intended to work with non-tauri applications. I think that's great, especially because it's obvious that a decent amount of work has gone into improving it.

The Rust ecosystem has solid options with *cargo-deb* and *cargo-generate-rpm*, on the Linux front. However, based on activity (or lack thereof), bundling for Windows and macOS are not so future-proof right now.

### Describe the solution you'd like

Would it be possible to get a cargo command that re-uses this library to bundle based off of a non-tauri project's `Cargo.toml`? Similar to how cargo-generate-rpm and cargo-deb do it? This project appears to have eclipsed **cargo-bundle** in support.

I think the community would benefit from corralling all of the effort to bundle into one well-kept project, like this. It just needs a cargo tool.

### Alternatives considered

Combinations of *cargo-deb*, *cargo-generate-rpm*, *cargo-wix*, *cargo-bundle*.

**Comment by amrbashir** [comment]
While `tauri-bundler` in theory works with non-tauri applications, it is only available as a library and not as a CLI, we may change that in the future but we currently don't have the capacity at the moment (ofc contributions are always welcome).

I would also mention https://github.com/crabnebula-dev/cargo-packager which is a port of tauri-bundler to be standalone and more generalized for Rust and non-Rust projects, and `tauri-bundler` may use it under the hood in the future.

**Comment by cornmonger** [comment]
>I would also mention https://github.com/crabnebula-dev/cargo-packager which is a port of tauri-bundler to be standalone and more generalized for Rust and non-Rust projects, and tauri-bundler may use it under the hood in the future.

That looks promising! Thanks for the quick response. Unsurprisingly, you guys are already on top of it. Closing the ticket.
