### ISSUE TITLE
[bug] Tauri build frontend coming empty when using a a web assembly library.

### ISSUE THREAD

**Issue by deepushajia** [tauri-apps/tauri#9745]
### Describe the bug

Major points:

* Issue is coming only during build. It works fine on dev.
* I have hosted the react build folder independently and it works fine.
* I have also hosted the react build folder on my linux webkit browser. There also it is wokring fine.

### Reproduction

This is the error I am getting only on build through tauri.

![Screenshot from 2024-05-11 13-25-54](https://github.com/tauri-apps/tauri/assets/12277348/36335d18-f628-4431-8032-3c8461fcd5f0)

### Expected behavior

Working normally, consistent across all systems.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Ubuntu 20.04 X64
    ✔ webkit2gtk-4.0: 2.38.6
    ✔ rsvg2: 2.48.9
    ✔ rustc: 1.77.1 (7cf61ebde 2024-03-27)
    ✔ Cargo: 1.77.1 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 20.9.0
    - npm: 10.1.0

[-] Packages
    - tauri [RUST]: 1.6.1
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.8
    - tauri-cli [RUST]: not installed!
    - @tauri-apps/api [NPM]: 1.5.0 (outdated, latest: 1.5.5)
    - @tauri-apps/cli [NPM]: 1.5.1 (outdated, latest: 1.5.13)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../build
    - devPath: http://localhost:3001/
    - framework: React
```

### Stack trace

```text
Nil
```

### Additional context

Nil

**Comment by deepushajia** [comment]
I found out the root cause, it is that the response headers from tauri server for loading built wasm files lack MIME type spec. This is present on dev runs. Need help with this.

**Comment by deepushajia** [comment]
or How to modify get hands on these response headers by ourselves? Tauri is using WRY right, any way I can get hands on how WRY delivers the react build files?

**Comment by FabianLars** [comment]
This is the mime parsing logic: https://github.com/tauri-apps/tauri/blob/1.x/core/tauri-utils/src/mime_type.rs#L84 but that's not the issue, see https://github.com/tauri-apps/tauri/issues/5749#issuecomment-1337904435 - Maybe try adding the `"linux-protocol-headers"` feature flag to the tauri dependency in Cargo.toml and see if works then, if not i'm afraid this will be `wontfix` for v1.

**Comment by deepushajia** [comment]
Thanks, that will be enough motivation to upgrade to v2.
