### ISSUE TITLE
[bug] The build results on the Mac platform are confusing. The aarch64.dmg file cannot be launched on Macs with Intel, M1, and M2 chips, while the x64.dmg file can be successfully launched on Intel, M1, and M2. 

### ISSUE THREAD

**Issue by heneyin** [tauri-apps/tauri#9748]
### Describe the bug

I am using tauri-action to build the product. https://github.com/tauri-apps/tauri-action

The build results on the Mac platform are confusing. The aarch64.dmg file cannot be launched on Macs with Intel, M1, and M2 chips, while the x64.dmg file can be successfully launched on Intel, M1, and M2. 

![image](https://github.com/tauri-apps/tauri/assets/17850697/bcd5baed-304f-43a8-9b41-c0150defdaf7)

### Reproduction

the reproduction result:
https://github.com/heneyin/tauri-demo/releases

github workflow: 
https://github.com/heneyin/tauri-demo/blob/main/.github/workflows/publish.yml

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 13.5.2 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.72.1 (d5c2e9c34 2023-09-13)
    ✔ cargo: 1.72.1 (103a7ff2e 2023-08-15)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 18.17.1
    - pnpm: 8.15.8
    - yarn: 1.22.19
    - npm: 9.6.7

[-] Packages
    - tauri [RUST]: 1.6.5
    - tauri-build [RUST]: 1.5.2
    - wry [RUST]: 0.24.9
    - tao [RUST]: 0.16.9
    - @tauri-apps/api [NPM]: 1.5.5
    - @tauri-apps/cli [NPM]: 1.5.11

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by FabianLars** [comment]
macos is simply stricter about arm apps and now requires them to be signed. Until Apple fixes this, you can make arm apps behave like x86 apps by signing them with an empty certificate, to do this in tauri, add `"signingIdentity": "-"` to your tauri.conf.json file (inside `tauri.bundle.macOS`).

This is kinda tracked here https://github.com/tauri-apps/tauri/issues/8763
