### ISSUE TITLE
Blank screen + "webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing" on logs

### ISSUE THREAD

**Issue by dezoito** [tauri-apps/tauri#9750]
### Describe the bug

All of a sudden the application will just display a blank screen and the following warning on the logs:
```
webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
```
On the console, I can tell that the app is performing an initial API call successfully.

I did look at #9300, but I'm not sure if they were experiencing the same issue.

### Reproduction

I assume the only way to reproduce is to clone https://github.com/dezoito/ollama-grid-search into a Ubuntu 20.04 machine and trying to run it from there.

### Expected behavior

The window should display the application as expected, or at least an error message stating why it can't be rendered

### Full `tauri info` output

```text
[✔] Environment
    - OS: Linux Mint 21.1 X64
    ✔ webkit2gtk-4.0: 2.44.0
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 18.19.1
    - yarn: 1.22.22
    - npm: 10.2.4
    - bun: 1.0.2

[-] Packages
    - tauri [RUST]: 1.6.5
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.7
    - @tauri-apps/api [NPM]: 1.5.5
    - @tauri-apps/cli [NPM]: 1.5.13

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Stack trace

```text
Finished dev [unoptimized + debuginfo] target(s) in 20.37s

** (ollama-grid-search:29842): WARNING **: 10:55:42.496: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
Fetching models from http://localhost
Fetching ollama version from http://localhost:11434/api/version
[src/commands.rs:55] &response = Response {
    url: Url {
        scheme: "http",
        cannot_be_a_base: false,
        username: "",
        password: None,
        host: Some(
            Domain(
                "localhost",
            ),
        ),
        port: Some(
            11434,
        ),
        path: "/api/version",
        query: None,
        fragment: None,
    },
    status: 200,
    headers: {
        "content-type": "application/json; charset=utf-8",
        "date": "Sat, 11 May 2024 13:55:44 GMT",
        "content-length": "20",
    },
}
```

**Comment by FabianLars** [comment]
The warning message has _nothing_ to do with the blank screen.

Can you try running it with the `WEBKIT_DISABLE_COMPOSITING_MODE=1` or `WEBKIT_DISABLE_DMABUF_RENDERER` env vars? This sounds like a "normal" problem with webkitgtk :/

**Comment by dezoito** [comment]
@FabianLars , your a genius!

`WEBKIT_DISABLE_COMPOSITING_MODE=1` did the trick.

I know nothing about webkit and presumed the warning had something to do with the issue because it's not present in a different Linux machine where it works.

If you have the time, would you mind briefly commenting on how that fixes the problem?

Thank you.

**Comment by 0xsimulacra** [comment]
WEBKIT_DISABLE_COMPOSITING_MODE=1 seems to do the trick for me. 

After a freshly intiated project using tauri+solidJs on OpenSuse Tumbleweed. I was getting a blank screen (dark) from the app and message "eglExportDMABUFImageMESA failed" on the command line.

**Comment by zararashigal** [comment]
Still not fixed.

**Comment by zararashigal** [comment]
> WEBKIT_DISABLE_COMPOSITING_MODE=1 seems to do the trick fopr me.
> 
> After a freshly intiated project using tauri+solidJs on OpenSuse Tumbleweed. I was getting a blank screen (dark) from the app and message "eglExportDMABUFImageMESA failed" on the command line.

This is correct, can confirm! Thank you for the help! And also WEBKIT_DISABLE_DMABUF_RENDERER=1

**Comment by Twikzer** [comment]
> > WEBKIT_DISABLE_COMPOSITING_MODE=1 seems to do the trick fopr me.
> > After a freshly intiated project using tauri+solidJs on OpenSuse Tumbleweed. I was getting a blank screen (dark) from the app and message "eglExportDMABUFImageMESA failed" on the command line.
> 
> This is correct, can confirm! Thank you for the help! And also WEBKIT_DISABLE_DMABUF_RENDERER=1

thank you!! i used for another unrelated program (wifiman desktop, from unifi) that only provide a .deb and i had installed on arch
