### ISSUE TITLE
[bug] Calling the convertFileSrc method with an error  -----  window.__TAURI__.convertFileSrc is not a function

### ISSUE THREAD

**Issue by zhyit** [tauri-apps/tauri#9764]
### Describe the bug

evn:  vite+@tauri-apps/api^1.5.1+@tauri-apps/cli^1.5.5
config: 
![image](https://github.com/tauri-apps/tauri/assets/43231863/e04a9a63-65d4-43e7-b130-e641c4fba7b1)
error:
![image](https://github.com/tauri-apps/tauri/assets/43231863/0885e194-0983-4410-965a-997d900b38b7)
console:
“window._ _TAURI_ _”：
![image](https://github.com/tauri-apps/tauri/assets/43231863/a6a8879d-d15c-4209-9e74-04a7a2d16248)

### Full `tauri info` output

```text
] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 120.0.2210.61
    ✔ MSVC: Visual Studio ���ɹ��� 2022
    ✔ rustc: 1.71.0 (8ede3aae2 2023-07-12)
    ✔ cargo: 1.71.0 (cfd3bbd8f 2023-06-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.14.2
    - pnpm: 8.15.7
    - npm: 8.3.0

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.5.5
    - @tauri-apps/cli [NPM]: 1.5.13

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by FabianLars** [comment]
Assuming you have `withGlobalTauri` enabled, it's `window.__TAURI__.tauri.convertFileSrc`, not `window.__TAURI__.convertFileSrc`

**Comment by zhyit** [comment]
> Assuming you have `withGlobalTauri` enabled, it's `window.__TAURI__.tauri.convertFileSrc`, not `window.__TAURI__.convertFileSrc`

withGlobalTauri is not enabled
![image](https://github.com/tauri-apps/tauri/assets/43231863/64bb9c40-6baf-4d9f-bc4e-4a3f0f9f568f)

**Comment by FabianLars** [comment]
Then the apis on `window.__TAURI__` won't be available. This is what `withGlobalTauri` controls. With it disabled you have to use the `@tauri-apps/api` npm package instead. (in this case `import { convertFileSrc } from "@tauri-apps/api/tauri";` )

**Comment by zhyit** [comment]
> > Assuming you have `withGlobalTauri` enabled, it's `window.__TAURI__.tauri.convertFileSrc`, not `window.__TAURI__.convertFileSrc`
> 
> withGlobalTauri is not enabled ![image](https://private-user-images.githubusercontent.com/43231863/329992914-64bb9c40-6baf-4d9f-bc4e-4a3f0f9f568f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTE5NjYsIm5iZiI6MTcxNTU5MTY2NiwicGF0aCI6Ii80MzIzMTg2My8zMjk5OTI5MTQtNjRiYjljNDAtNmJhZi00ZDlmLWJjNGUtNGEzZjBmOWY1NjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA5MTQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2MGY3MWI1NDAxMGU3ZDUwMzIxNjJmNjE1NmY1YmM1ZGQ0NWI1ZTVkZTViZjU0ZGI5ZGU4ZjJlN2Y4YWJkZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jbGtoEARC_aOoZP0OC-CWZpK_1R7es_MXyYn016vmjM)

yes, i used
![image](https://github.com/tauri-apps/tauri/assets/43231863/f30c4d7a-9ed3-4f4e-89e5-00f471fbecfb)
but the console displayed this error
![image](https://github.com/tauri-apps/tauri/assets/43231863/ab66da2e-9926-4a14-8bfc-dcbb20f5731b)

**Comment by FabianLars** [comment]
`withGlobalTauri: false` -> Apis in `window.__TAURI__` are **disabled**.
`withGlobalTauri: true` -> Apis in `window.__TAURI__` are **enabled**.

But again, even if you enable it, it is `window.__TAURI__.tauri.convertFileSrc` (you're missing `tauri`).

**Comment by zhyit** [comment]
> `withGlobalTauri: false` -> Apis in `window.__TAURI__` are **disabled**. `withGlobalTauri: true` -> Apis in `window.__TAURI__` are **enabled**.
> 
> But again, even if you enable it, it is `window.__TAURI__.tauri.convertFileSrc` (you're missing `tauri`).

Attempted to open and close both, but still prompted this error after calling the convertFileSrc(@tauri-apps/api/tauri) method
