### ISSUE TITLE
[feat] Can developers decide whether to use native or embedded Webviews

### ISSUE THREAD

**Issue by solid-component** [tauri-apps/tauri#9773]
### Describe the problem

Sometimes dealing with compatibility is troublesome, can you decide whether to embed Chromium or safari webview according to the configuration, like electron embed Chromium

### Describe the solution you'd like

Developers can configure whether to embed Chromium or safari on demand

**Comment by amrbashir** [comment]
We only support using native webviews through https://github.com/tauri-apps/wry atm, supporting an embedded chromium or another renderer is a tremendous amount of work that we don't have, but hopefully in the future we can use [Servo](https://github.com/servo/servo) as an alternative renderer (probably with an embedded option as well).


For now, only Webview2 (chromium) can be embedded on Windows though `webviewInstallMode: "fixedRuntime"` see https://tauri.app/v1/api/config#windowsconfig.webviewinstallmode and on Linux, you can use the generated AppImage which embeds the webkit2gtk webview as well.
