### ISSUE TITLE
[feat]  Bundler to include pdb file as a resource in windows builds

### ISSUE THREAD

**Issue by dam5h** [tauri-apps/tauri#9780]
### Describe the problem

I am making a windows bundler and I would like to include the pdb file, but this file is not available until after the build.

The `copy_resources` function happens early before this file is available and will early exit from the build process.

There are a couple PR's that will help with this as pointed out on [discord](https://discord.com/channels/616186924390023171/1239972274040340533/1239972274040340533):

> This one probably would help too but less automatic than 2 ig https://github.com/tauri-apps/tauri/pull/9734
And this would break 2 https://github.com/tauri-apps/tauri/pull/9710

### Describe the solution you'd like

I would like to allow post build resources in the resources bundle configuration, ie files that don't exist yet.

### Alternatives considered

I could write my own nsis template, which I may end up doing, but this is overkill for such a simple matter it seems.

### Additional context

I use the following in my `.cargo/config.toml` file to have rustc make a local pdb file.

```
[target.x86_64-pc-windows-msvc]
# By default, the executable embeds absolute path to PDB.
# But that would mean a path on a build machine.
# Instead, we supply a relative path (just the name of the PDB file,
# because we assume it's in the current directory).
rustflags = ["-C", "link-args=/PDBALTPATH:%_PDB%"]
```

**Comment by amrbashir** [comment]
> I could write my own nsis template, which I may end up doing, but this is overkill for such a simple matter it seems.

Soon you won't need to write a full nsis template, after this PR https://github.com/tauri-apps/tauri/pull/9731, just a hook file is enough

**Comment by lucasfernog** [comment]
Is this closed now?

**Comment by amrbashir** [comment]
I would consider this closed tbh since users can just use the new hooks to include their needed files. If more people requesting adding the `pdb` files, we will reconsider.

**Comment by eythaann** [comment]
x2, I need pdb file to get the backtrace of bugs/erros on production, btw I already has my own nsis template, so I will just add it there but having a feature or config to include it directly on tauri.config would be nice.

```log
[2024-10-09][13:49:05][seelen_ui][ERROR] Error while setting up: Custom: "JUST TESTING PROPAGATION ERRORS"
    4: seelen_ui::system::declare_system_events_handlers
        at: "C:\Users\dlmqc\source\repos\seelen\seelen-ui\src\background\system\mod.rs:48"
    5: seelen_ui::seelen::Seelen::start
        at: "C:\Users\dlmqc\source\repos\seelen\seelen-ui\src\background\seelen.rs:195"
    6: seelen_ui::setup
        at: "C:\Users\dlmqc\source\repos\seelen\seelen-ui\src\background\main.rs:135"
    7: seelen_ui::main::closure$0
        at: "C:\Users\dlmqc\source\repos\seelen\seelen-ui\src\background\main.rs:224"
    27: seelen_ui::main
        at: "C:\Users\dlmqc\source\repos\seelen\seelen-ui\src\background\main.rs:237"
```

**Comment by eythaann** [comment]
+1, at least for debug build these are useful for backtracking on errors.
