### ISSUE TITLE
[feat] Backport rpm packaging to v1.x branch

### ISSUE THREAD

**Issue by hjmallon** [tauri-apps/tauri#9801]
### Describe the problem

RPM packaging would be really useful for deploying to CentOS / RHEL / Rocky / etc machines, however Tauri v2 doesn't support CentOS due to libsoup3 and libwebkit-4.1 requirements.

### Describe the solution you'd like

Could we backport the RPM bundling to the v1.x branch?

**Comment by FabianLars** [comment]
> Could we backport the RPM bundling to the v1.x branch?

"We" as-in us tauri maintainers? No, we don't have time for that tbh. "We" as-in the community? Sure! We still try to review v1 PRs. I can't give any 100% guarantees for larger features though.

**Comment by hjmallon** [comment]
I would be very happy to backport it, but I guess I would need a maintainer who was interested in reviewing it / thought it was a good idea. My previous backport PR hasn't seen much progress (https://github.com/tauri-apps/tauri/pull/8334).

**Comment by FabianLars** [comment]
> My previous backport PR hasn't seen much progress (https://github.com/tauri-apps/tauri/pull/8334).

hmm, that may have been my bad :/ Still not used to being in a position where it's alright for me to merge feature prs in this repo 🙃

**Comment by hjmallon** [comment]
Here is my backport. It appears to be working for me https://github.com/tauri-apps/tauri/pull/9809

**Comment by FabianLars** [comment]
I'm on the road over the weekend so I'll take a look Monday or Tuesday, thanks.

It may be delayed a bit because I want to investigate why CI freezes for 10 minutes when building the rpm.
