### ISSUE TITLE
[question] Doesn't Tauri need the system's permission when running background?

### ISSUE THREAD

**Issue by gusxodnjs** [tauri-apps/tauri#9802]
### Describe the problem

I understand that when I run the app in the background on Tauri, I just run `api.prevent_exit()` to work. (https://tauri.app/v1/guides/features/system-tray#preventing-the-app-from-closing)

I thought there would be a pop-up for permission while implementing this guide, but it wasn't.

Ordinary apps get pop-up windows that acquire the system's authority to operate in the background, how are we working through this?
![image](https://github.com/tauri-apps/tauri/assets/27146546/8c3d2b14-e406-4f0a-b53f-1db345d47a71)

Thank you.

### Describe the solution you'd like

-

**Comment by FabianLars** [comment]
I didn't research this yet but my assumption is that either this permission is only relevant when you use some specific background apis while we're simply not exiting the app, or it's similar to other apis (like screen recording) where the permissions don't actually prevent anything and rely on the app devs to adhere to them, at least if distributed outside the app store.

Edit: Yeah, the screenshot really sound like separate background items/services and not just keeping the main app running but idk
