### ISSUE TITLE
[feature] Would a Chrome Backend Be Useful for Tauri?

### ISSUE THREAD

**Issue by zicklag** [tauri-apps/tauri#981]
**Is your feature request related to a problem? Please describe.**
So, it seems that windows support in Tauri is somewhat broken at the moment. I am unable to get the GitHub action to build an MSI ( https://github.com/tauri-apps/tauri-action/issues/43 ), I am unable to cross-compile it ( https://github.com/webview/webview_rust/issues/48 ), and I am unable to build it inside of a windows VM ( I run into this issue: https://github.com/tauri-apps/tauri/issues/812 ). And I'm not the only one with projects like [Lucky You](https://github.com/jwenjian/lucky-you/releases/tag/v1.1.1) unable to get Windows support working consistently.

I'm not saying this to bash on Tauri. I *love* Tauri, but I can't for the life of me figure out how to build my app for windows. I understand that this is under development and I'm not saying that you should have gotten it done by now. What I want to do is find some interim solution that will work so I can release my app until the windows support with Edge is finally nailed down.

**Describe the solution you'd like**
Right now I just need essentially any way to run a Tauri app on Windows, most likely one that doesn't require using EdgeHTML or the new Edge Chromium. I'm currently trying to get a Tauri backend based on Chrome to work by using the Chrome DevTools protocol to remote control a chrome browser. I've implemented everything in the Webview API except the functions which return a raw window ( which is impossible with this model ) and the `webview_bind` ( which I've almost gotten working, I think ).

**Describe alternatives you've considered**
I've thought about trying to comiple Webview for Windows maybe using WebviewQT. I don't know how easy that would be.

**Additional context**
Anyway, I just wanted to share my dilemma and share my work at an interim solution. If anybody has any other ideas I'd appreciate it! I'll be posting my progress here as things happen.

**Comment by zicklag** [comment]
I have been able to get the [Tauri GitHub Action](https://github.com/tauri-apps/tauri-action/) to work now, which mostly fixes my issue. That said I did make some good progress actually setting up Chrome using the dev tools API as a Tauri backend, but I never finished. Does anybody else see a purpose in having chrome devtools as a Tauri backend or not really?

**Comment by martonlanga** [comment]
I'm on Mac and would prefer the Chrome devtools over Safari's. Is this Windows only, or would it work on other platforms as well?

**Comment by zicklag** [comment]
It would work all desktop platforms. I didn't think about the dev tools being a helping factor. For the dev tools you could even develop using the chrome adapter and then deploy without it so that you keep the small binary size of Tauri apps and such.

**Comment by nklayman** [comment]
We've moved to a new bindings package called [wry](https://github.com/tauri-apps/wry), developed in-house specially for Tauri. It will be available in the next release, which should fix all of your windows-related issues.

In addition, we've updated Tauri core to support multiple bindings packages. This means you could create a binding for chrome over the devtools protocol, and the user could choose to use that instead of wry. This would be totally awesome, especially for development as it would compile much faster and give you chrome devtools. [Here is the file](https://github.com/tauri-apps/tauri/blob/dev/tauri/src/webview/wry.rs) that implements the wry backend. In theory, you just need to recreate those interfaces using the chrome devtools protocol and it will just work, no other tinkering with tauri core required. Let me know if you want to work on this and/or if you have any more questions, I'd love to help :).

**Comment by zicklag** [comment]
> We've moved to a new bindings package called wry, developed in-house specially for Tauri. It will be available in the next release, which should fix all of your windows-related issues.

That would be _awesome_. :star_struck: It would be so nice to have an ( almost ) fully Rust webview library!

> Here is the file that implements the wry backend. In theory, you just need to recreate those interfaces using the chrome devtools protocol and it will just work, no other tinkering with tauri core required. Let me know if you want to work on this and/or if you have any more questions, I'd love to help :).

Vey cool. I'm not sure if I'll ever get back to this, but if I do I'll let you know. :+1:

**Comment by nothingismagick** [comment]
Ok, cool. I am going to close this then - feel free to reopen if you find the time / issues arise.
