### ISSUE TITLE
[bug] `cargo create-tauri-app --beta` doesn't generate any capabilities

### ISSUE THREAD

**Issue by stijnfrishert** [tauri-apps/tauri#9814]
### Describe the bug

Running `cargo create-tauri-app --beta` with `3.13.17` doesn't generate a capabilities folder/file. These are the settings I've used:

1. `cargo create-tauri-app --beta`
2. Project name: _temp_
3. Frontend language: _Typescript / Javascript_
4. Package manager: _pnpm_
5. UI Template: _React_
6. UI flavor: _Typescript_
7. Setup for mobile? _Yes_
8. `cd temp`
9. `pnpm install`

These are the contents of the resulting temp folder:

<img width="247" alt="image" src="https://github.com/tauri-apps/tauri/assets/7056711/63e1e026-bf86-4fad-bde7-92e8aec70c24">

Issue create by request over in https://github.com/tauri-apps/tauri/discussions/9810#discussioncomment-9480344

### Expected behavior

Apparently a capabilities folder should be created with a default file in it

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.12.2
    - pnpm: 9.0.6
    - npm: 10.5.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta (no lockfile)
    - tauri-build [RUST]: no manifest (no lockfile)
    - wry [RUST]: no manifest (no lockfile)
    - tao [RUST]: no manifest (no lockfile)
    - tauri-cli [RUST]: 2.0.0-beta.17
    - @tauri-apps/api [NPM]: 2.0.0-beta.11
    - @tauri-apps/cli [NPM]: 2.0.0-beta.17

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by cfping** [comment]
Are you able to perform the initialization with the 'cargo tuari android init' or 'cargo tuari ios init' commands?

**Comment by stijnfrishert** [comment]
I can run `cargo tauri ios init` (and just did), but that only created `gen/apple`, no capabilities or permissions.

Can't run android, because I don't have the SDK installed currently.

**Comment by amrbashir** [comment]
A new version is released to fix this

**Comment by stijnfrishert** [comment]
Yes, works now, and generates a default.json.

Thank you for fixing this :) Puts me one step closer to solving https://github.com/tauri-apps/tauri/discussions/9810.
