### ISSUE TITLE
cli `tauri icon` error: Source image for tauricon not found

### ISSUE THREAD

**Issue by jeeinn** [tauri-apps/tauri#982]
**Describe the bug**
cli `tauri icon` error: Source image for tauricon not found

**To Reproduce**
```
npm run tauri icon /Users/x/Pictures/tauri-md.png
```

**Expected behavior**
Generate all ICONS

**Screenshots**

**Platform and Versions (please complete the following information):**

Operating System - Darwin(20.0.0) - darwin/x64

Node.js environment
  Node.js - 12.17.0
  tauri.js - 0.11.1

Rust environment
  rustc - 1.45.2
  cargo - 1.45.1
  tauri-bundler - 0.9.1

Global packages
  NPM - 6.14.8
  yarn - Not installed

**Additional context**

**Stack Trace**

```
[tauri]: running icon
 app:spawn [ERROR] Source image for tauricon not found +0ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tauri-markdown@0.1.0 tauri: `tauri "icon" "/Users/x/Pictures/tauri-md.png"`
npm ERR! Exit status 1
```

**Comment by nothingismagick** [comment]
I am closing this as just plain outdated. Please reopen if it still happens.

**Comment by lucasfernog** [comment]
FYI the issue here is that the `tauri icon` correct signature is `tauri icon --icon /path/to/icon.png`. Maybe i'll change it to accept the positional argument instead, as this is a common mistake.
