### ISSUE TITLE
[bug] android dev - "Waiting for your frontend dev server to start on..."

### ISSUE THREAD

**Issue by happybeing** [tauri-apps/tauri#9824]
### Describe the bug

I've been working on a Tauri v1 project, and then decided to try v2 beta, so I also created a Tauri v2 project and had the hello world example working there (showing the 'greet' UI). 

I then made a copy of my Tauri v1 project and have migrated it to v2 beta and have it working for desktop. 

I then decided to try the `cargo tauri android dev` on the migrated project. I had some issues with it complaining about the app identifier because it contains '-' but eventually cleared those by deleting src-tauri/gen and re-doing cargo tauri android init.

Now, when I do cargo tauri android dev, I get a strange result. Firstly, the emulator starts as normal, but shows the 'greet' example, not my app. And in the console I get the following:

```
VITE v5.2.6  ready in 722 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
    Warn Waiting for your frontend dev server to start on http://192.168.43.141:5173/...
    Warn Waiting for your frontend dev server to start on http://192.168.43.141:5173/...
    Warn Waiting for your frontend dev server to start on http://192.168.43.141:5173/...
    Warn Waiting for your frontend dev server to start on http://192.168.43.141:5173/...
    Warn Waiting for your frontend dev server to start on http://192.168.43.141:5173/...
    Warn Waiting for your frontend dev server to start on http://192.168.43.141:5173/...
    Warn Waiting for your frontend dev server to start on http://192.168.43.141:5173/...
```

I don't understand why it is showing the 'greet' example. http://192.168.43.141:5173/ is kindof correct in that this is the local IP of my machine, but I would expect it to us 'localhost'. But anyway, why is the dev server not starting?

I have my app working on desktop, and it feels like I'm very close to having it working on android, but I'm not sure what is going on here. I haven't done android development before so not sure what might cause this.

### Expected behavior

My app loads into the Android emulator.

### Full `tauri info` output

```text
cargo tauri info

[✔] Environment
    - OS: Ubuntu 24.4.0 X64
    ✔ webkit2gtk-4.1: 2.44.0
    ✔ rsvg2: 2.58.0
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 22.1.0
    - yarn: 1.22.5
    - npm: 10.7.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.19
    - tauri-build [RUST]: 2.0.0-beta.15
    - wry [RUST]: 0.39.5
    - tao [RUST]: 0.28.0
    - tauri-cli [RUST]: 2.0.0-beta.12
    - @tauri-apps/api [NPM]: 2.0.0-beta.11
    - @tauri-apps/cli [NPM]: 2.0.0-beta.12

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

**Comment by amrbashir** [comment]
From the logs, it seems that Vite is only started on localhost and not on internal IPs, and that's why mobile dev server can't be found. You need something like this https://github.com/tauri-apps/create-tauri-app/blob/2e35db4af381a7955bd56fef8ad27ecc76b16151/templates/template-svelte/vite.config.js.lte#L19-L26 

> that this is the local IP of my machine, but I would expect it to us 'localhost'.

localhost is local to your computer which is different from the localhost of the android device, so it won't be accessible, this is why you need to expose your vite dev server on internal IPs so the android device can use on of these IPs to connect.

I know the documentation is lacking on this atm but will be available on https://beta.tauri.app/start/frontend-configuration/vite/ before v2 hits stable.

**Comment by happybeing** [comment]
@amrbashir Thanks for the hints. 

There seem to be things used there that aren't in place with my installation. Firstly the `{% if mobile %}` seem to be conditionals for a pre-processor, but cause errors, so I removed them and just left the mobile settings in that section which now looks like this:

```
	server: {
		port: 1420,
		strictPort: true,
		host: "0.0.0.0",
		hmr: {
			protocol: "ws",
			host: await internalIpV4(),
			port: 1421,
		},
		watch: {
			// 3. tell vite to ignore watching `src-tauri`
			ignored: ["**/src-tauri/**"],
		},
	},
```
That gets a little further but `vite` complains that `internalIpV4 is not defined` so the server start fails.

I think this issue is due to migration from Tauri v1 because looking in a clean Tauri v2 app the vite.config.js is indeed like the one you suggested, whereas my migrated v1 app just loads the svelte plugin.

So I guess there are a few things missing in the migrated project:
- something that will handle `{% if mobile %}`  in the vite.config.js
- whatever provides `interalIpV4`

And possibly some other things. Can you suggest the further migration steps that might solve the above?

I can't find an issue that covers this for migration so perhaps it should be re-opened or referenced in a new issue?

**Comment by amrbashir** [comment]
> * something that will handle `{% if mobile %}`  in the vite.config.js

you can ignore that, it is a template pre-processor in create-tauri-app, the snippet you showed above is correct

> * whatever provides `interalIpV4`

You will just need to install `internal-ip` npm package, make sure to use `7.0.0` as later versions had problems.

Then you can import it `import { interalIpV4 } from "internal-ip"`

**Comment by happybeing** [comment]
> you can ignore that, it is a template pre-processor in create-tauri-app, the snippet you showed above is correct

I want to build for non-mobile too, so if I hard-code for mobile that won't work. I'd like to migrate my v1 app fully to v2 beta, and some steps are incomplete. So while your suggestions may fix the Android problem I assume they will break my desktop builds.

**Comment by amrbashir** [comment]
I see, you can just copy this vite config which handles both desktop and mobile

```js
import { defineConfig } from "vite";
import { svelte } from "@sveltejs/vite-plugin-svelte";
import { internalIpV4 } from "internal-ip";

// @ts-expect-error process is a nodejs global
const mobile = !!/android|ios/.exec(process.env.TAURI_ENV_PLATFORM);

// https://vitejs.dev/config/
export default defineConfig(async () => ({
  plugins: [svelte()],

  // Vite options tailored for Tauri development and only applied in `tauri dev` or `tauri build`
  //
  // 1. prevent vite from obscuring rust errors
  clearScreen: false,
  // 2. tauri expects a fixed port, fail if that port is not available
  server: {
    port: 1420,
    strictPort: true,
    host: mobile ? "0.0.0.0" : false,
    hmr: mobile
      ? {
          protocol: "ws",
          host: await internalIpV4(),
          port: 1421,
        }
      : undefined,
    watch: {
      // 3. tell vite to ignore watching `src-tauri`
      ignored: ["**/src-tauri/**"],
    },
  },
}));

```

**Comment by happybeing** [comment]
Thanks for your help with this but I'm still getting the same error having pasted the above as it is in to vite.config.json:
```
VITE v5.2.6  ready in 424 ms

  ➜  Local:   http://localhost:1420/
  ➜  Network: http://192.168.43.141:1420/
    Warn Waiting for your frontend dev server to start on http://192.168.43.141:5173/...
    Warn Waiting for your frontend dev server to start on http://192.168.43.141:5173/...
    Warn Waiting for your frontend dev server to start on http://192.168.43.141:5173/...
    Warn Waiting for your frontend dev server to start on http://192.168.43.141:5173/...
```

**Comment by amrbashir** [comment]
the above vite example uses port `1420` while your tauri.conf.json has `5173`, just change one of them

**Comment by Super1Windcloud** [comment]
port    problem

**Comment by Smankusors** [comment]
hmm I wonder why on physical devices we can't use localhost/127.0.0.1?

I saw that if we are using emulator, the CLI will automatically "adb reverse", but not the case if we are using physical device.

Why is that?

(My dev PC and my phone are connected to the different networks)

**Comment by frederickbeaulieu** [comment]
@amrbashir 

I have 
```
  ➜  Local:   http://localhost:1420/
  ➜  Network: http://10.10.90.204:1420/
  ➜  Network: http://198.19.254.2:1420/
        Warn Waiting for your frontend dev server to start on http://10.10.90.204:1420/...
        Warn Waiting for your frontend dev server to start on http://10.10.90.204:1420/...
```


with 
tauri.config.json : 

	"build": {
		"beforeDevCommand": "pnpm dev",
		"devUrl": "http://localhost:1420",
		"beforeBuildCommand": "pnpm build",
		"frontendDist": "../build"
	},

vite.config.js : 

```
// https://github.com/tauri-apps/create-tauri-app/blob/2e35db4af381a7955bd56fef8ad27ecc76b16151/templates/template-svelte-ts/vite.config.ts.lte
import { sveltekit } from "@sveltejs/kit/vite";
import { defineConfig } from "vite";
import { internalIpV4 } from "internal-ip";

// @ts-expect-error process is a nodejs global
const mobile = !!/android|ios/.exec(process.env.TAURI_ENV_PLATFORM);

export default defineConfig(async () => ({
  plugins: [sveltekit()], // Keep SvelteKit plugin, not svelte()

  clearScreen: false,
  server: {
    port: 1420,
    strictPort: true,
    host: mobile ? "0.0.0.0" : false,
    hmr: mobile
      ? {
          protocol: "ws",
          host: await internalIpV4(),
          port: 1421,
        }
      : undefined,
    watch: {
      ignored: ["**/src-tauri/**"],
    },
  },
}));
```


The app is working on localhost from my laptop. 
My phone can reach the app using http://10.10.90.204:1420/ in the browser.



I can get the app to load on my phone with : 

`  pnpm tauri android dev --host 0.0.0.0
`

But when the app opens i get a blank page with : " error sending request " 
(might be in relation to https://github.com/tauri-apps/tauri/pull/11185 judging by your comment about vite ? )

**Comment by frederickbeaulieu** [comment]
updated everything: 

`> tauri info


[✔] Environment
    - OS: Mac OS 26.0.0 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ Xcode: 26.0
    ✔ rustc: 1.89.0 (29483883e 2025-08-04)
    ✔ cargo: 1.89.0 (c24e10642 2025-06-23)
    ✔ rustup: 1.28.2 (e4f3ad6f8 2025-04-28)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 24.8.0
    - pnpm: 10.17.0
    - yarn: 1.22.22
    - npm: 11.6.0

[-] Packages
    - tauri 🦀: 2.8.5
    - tauri-build 🦀: 2.4.1
    - wry 🦀: 0.53.3
    - tao 🦀: 0.34.3
    - tauri-cli 🦀: 2.8.4
    - @tauri-apps/api : 2.8.0
    - @tauri-apps/cli : 2.8.4

[-] Plugins
    - tauri-plugin-dialog 🦀: 2.4.0
    - @tauri-apps/plugin-dialog : 2.4.0
    - tauri-plugin-haptics 🦀: 2.3.0
    - @tauri-apps/plugin-haptics : 2.3.0
    - tauri-plugin-fs 🦀: 2.4.2
    - @tauri-apps/plugin-fs : not installed!
    - tauri-plugin-opener 🦀: 2.5.0
    - @tauri-apps/plugin-opener : 2.5.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite

[-] iOS
    - Developer Teams: None`

Now i get: 

`Failed to request http://0.0.0.0:1420/: error sending request for url (http://0.0.0.0:1420/)`

**Comment by frederickbeaulieu** [comment]
Got it working with : 

`  pnpm tauri android dev --host 127.0.0.1
`
