### ISSUE TITLE
[feat] How can i find out the cause when app crashed?

### ISSUE THREAD

**Issue by drdevelop** [tauri-apps/tauri#9826]
### Describe the problem

When app crashed，i don't know what should i do.

### Describe the solution you'd like

Maybe there is any log file in my computer for view? If it is there, please tell me where's it

**Comment by amrbashir** [comment]
This depends on your application code, but here is a few things to maybe try to get some info:
- Setup a panic hook in Rust: https://doc.rust-lang.org/std/panic/fn.set_hook.html
- Setup tauri-plugin-log: https://github.com/tauri-apps/plugins-workspace/tree/v1/plugins/log
