### ISSUE TITLE
[docs] How does tauri v2 drag and drop a file to get the address, any examples?

### ISSUE THREAD

**Issue by Esword618** [tauri-apps/tauri#9830]
How does tauri v2 drag and drop a file to get the address, any examples?

**Comment by amrbashir** [comment]
Checkout https://beta.tauri.app/references/javascript/api/namespacewebviewwindow/#ondragdropevent

**Comment by MattTheCuber** [comment]
Updated link: https://tauri.app/reference/javascript/api/namespacewebviewwindow/#ondragdropevent
