### ISSUE TITLE
[bug] application launched from perMachine or both nsis installer still have admin privilege (elevated)

### ISSUE THREAD

**Issue by anatawa12** [tauri-apps/tauri#9835]
### Describe the bug

application launched from perMachine or both nsis installer still have admin privilege (elevated).

It's not good to have admin privilege and some process (like Unity) denies launching admin privilege.

### Reproduction

1. install some tauri app with nsis installer
2. launch the app from nsis installer
3. the launched app process is elevated

### Expected behavior

the app launched from installer should not elevated.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 124.0.2478.97
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.11.1
    - npm: 10.2.4

    - CSP: unset
    - distDir: out
    - devPath: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Webpack
```

### Additional context

as far as i search, this method seems to work but I didn't test yet https://stackoverflow.com/questions/11169431/how-to-start-a-new-process-without-administrator-privileges-from-a-process-with

Downstream issue: vrc-get/vrc-get#1020

**Comment by Legend-Master** [comment]
Having the same problem, I'll take a look
