### ISSUE TITLE
[feat] move updater bundle target to a separate field

### ISSUE THREAD

**Issue by Legend-Master** [tauri-apps/tauri#9839]
### Describe the problem

About updater configs, I think updater is not really a "target" anymore

### Describe the solution you'd like

I would suggest we change our config files a bit, removing updater from bundle targets, instead making it a separate field, like:

`updater: true | false | "legacyZipped"`

- `true`: only generates/reuses non-zipped installers/updaters
- `legacyZipped`: keep the v1 behavior

**Comment by amrbashir** [comment]
I think that makes sense but will need an equivalent `--updater` CLI flag.
