### ISSUE TITLE
[bug] Webpack error  on blank tauri project with nextJS 

### ISSUE THREAD

**Issue by zC4sTr0** [tauri-apps/tauri#9844]
### Describe the bug

Using latest version of rust, nextjs and npm

I'm constantly getting this warn on a blank project using tauri:

![image](https://github.com/tauri-apps/tauri/assets/38432614/7b47250b-e05d-407d-9d7e-4250dfdd5414)

Seems like webpack-related. Tried to use next.config.js instead of mjs but didn't work: The error still outputs on console.

### Reproduction

Follow the [documentation](https://tauri.app/v1/guides/getting-started/setup/next-js) and start a blank tauri project using nextJS just as I did.

After installing all packages, start the project using `cargo tauri dev`

### Expected behavior

Shouldn't output errors at console

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 124.0.2478.97
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.13.1
    - npm: 10.8.0
    - bun: 1.1.8

[-] Packages
    - tauri [RUST]: 1.6.6
    - tauri-build [RUST]: 1.5.2
    - wry [RUST]: 0.24.10
    - tao [RUST]: 0.16.9
    - tauri-cli [RUST]: 1.5.14
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 1.5.14

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../out
    - devPath: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Webpack
```

### Stack trace

```text
No stack strace of errors were displayed
```

### Additional context

Found many issues on next.js about that but seems like it's fixed for almost all of them.
Additionally, when I start a blank nextJS project here, the error doesnt shows up.

**Comment by FabianLars** [comment]
Does it actually cause any issues? Like a blank screen or anything not loading correctly?

Either way, there's really nothing we can do here since we aren't nextjs maintainers. Therefore i'll have to close this but at least we have it tracked now :)
