### ISSUE TITLE
[feat] Integrate skia for UI processing on mobile/desktop apps in tauri 2.0

### ISSUE THREAD

**Issue by architectureman** [tauri-apps/tauri#9848]
### Describe the problem

Integrate skia like react native skia will make Tauri competitive with Flutter on mobile/desktop app 

### Describe the solution you'd like

I like Tauri v2, but I want Tauri team can think about Skia like react native Skia. Pleaszzzzzzz!

**Comment by amrbashir** [comment]
This is a huge undertaking, and we don't currently have the effort to implement it.

**Comment by FabianLars** [comment]
For what it's worth, chromium (tauri on windows) uses it already and webkit (tauri on Linux and macOS) is working on it.

I don't ever see us writing our own renderer abstraction tbh so I personally would go a step further and close this issue 🤔

**Comment by niraj-khatiwada** [comment]
If you want to use Skia, you can use Canvaskit WASM in React Native desktop itself. Furthermore, Skia has too many issues specially in IOS (see Flutter's issue tab). I don't think Tauri needs this at all. I think we can close this issue.
