### ISSUE TITLE
Can Tauri load remote content? 

### ISSUE THREAD

**Issue by retorquere** [tauri-apps/tauri#986]
I'm curious whether Tauri could be used to slap a launcher around a website or pwa so that I can have eg a Gmail "app". For this I'd need to load such an app either directly from an url, or stick it in an iframe. Would that be expected to work?

**Comment by nklayman** [comment]
You can use `webview.eval` to change to location to a remote url in `main.rs`, like this:
```rust
tauri::AppBuilder::new()
        .invoke_handler(|webview, arg| {
            ...
        })
        .setup(|webview, _| webview.eval("window.location.replace('https://google.com')"))
        .build()
        .run();
```

@lucasfernog is there a better way that I'm not aware of or is this good?

**Comment by retorquere** [comment]
I'm new to Tauri -- is the `...` supposed to do something specific? If I omit the `invoke_handler` call I just get a blank window when I run `npx tauri dev`.

**Comment by nuthinking** [comment]
@retorquere did you find a solution?

**Comment by retorquere** [comment]
no

**Comment by nuthinking** [comment]
@nklayman Why was this issue closed?

**Comment by amrbashir** [comment]
@retorquere @nuthinking 
as @nklayman said it is possible to navigate to a remote site inside your tauri app, whether you provide an `invoke_handler` or not. Not sure why you got a blank window. 

I've tested this now with a new tauri project and here is my `main.rs` content: 
```rust
#![cfg_attr(
  all(not(debug_assertions), target_os = "windows"),
  windows_subsystem = "windows"
)]

mod cmd;

fn main() {
  tauri::AppBuilder::new()
    .setup(|webview, _| webview.eval("window.location.replace('https://google.com')"))
    .build()
    .run();
}
```

**Comment by retorquere** [comment]
I've just gone through the "getting started" steps, replaced the main.rs with the above, and I'm getting a white square with just the three macos windows buttons (red, yellow, green).

**Comment by nklayman** [comment]
That's odd. Maybe try leaving the default `invoke_handler` stuff and just adding the `.setup`.

**Comment by lucasfernog** [comment]
Can you see if there's any errors on your console @retorquere ?

**Comment by retorquere** [comment]
Sorry for going offline for so long -- I've re-done all the "getting started" steps, now at `npm run tauri dev`, and that ends with

```
   Compiling attohttpc v0.16.3
    Finished dev [unoptimized + debuginfo] target(s) in 1m 26s
     Running `target/debug/webtauri`
 app:tauri (runner) Connection refused to http://localhost:4000. Did you start your dev server? Usually that's done with a `dev` or `serve` NPM script. +1m
```

that's before adding  the setup line, with `main.rs` just the default

```
#![cfg_attr(
  all(not(debug_assertions), target_os = "windows"),
  windows_subsystem = "windows"
)]

mod cmd;

fn main() {
  tauri::AppBuilder::new()
    .invoke_handler(|_webview, arg| {
      use cmd::Cmd::*;
      match serde_json::from_str(arg) {
        Err(e) => {
          Err(e.to_string())
        }
        Ok(command) => {
          match command {
            // definitions for your custom commands from Cmd here
            MyCustomCommand { argument } => {
              //  your command code
              println!("{}", argument);
            }
          }
          Ok(())
        }
      }
    })
    .build()
    .run();
}
```

**Comment by nklayman** [comment]
That's because it has to connect to something before changing the url to the remote location. You can just create a blank `index.html` that says "loading" or something and point Tauri at it. That should take care of the issue you are getting and allow you to change to a remote url through the `setup` function.

**Comment by retorquere** [comment]
I have created a `dist` directory parallel to the `src-tauri` directory (which is where the `distDir` points to) and created a file `index.html` in it, but I'm getting the same error.

**Comment by nklayman** [comment]
What is in your `tauri.conf.json`?

**Comment by retorquere** [comment]
```
{
  "build": {
    "distDir": "../dist",
    "devPath": "http://localhost:4000",
    "beforeDevCommand": "",
    "beforeBuildCommand": ""
  },
  "ctx": {},
  "tauri": {
    "embeddedServer": {
      "active": true
    },
    "bundle": {
      "active": true,
      "targets": "all",
      "identifier": "com.tauri.dev",
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "resources": [],
      "externalBin": [],
      "copyright": "",
      "category": "DeveloperTool",
      "shortDescription": "",
      "longDescription": "",
      "deb": {
        "depends": [],
        "useBootstrapper": false
      },
      "osx": {
        "frameworks": [],
        "minimumSystemVersion": "",
        "useBootstrapper": false
      },
      "exceptionDomain": ""
    },
    "allowlist": {
      "all": true
    },
    "window": {
      "title": "Web Tauri",
      "width": 800,
      "height": 600,
      "resizable": true,
      "fullscreen": false
    },
    "security": {
      "csp": "default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'"
    },
    "inliner": {
      "active": true
    }
  }
}
```

**Comment by nklayman** [comment]
Your dev path is set to `http://localhost:4000`, so Tauri will try to connect to it. Try changing it to `../dist` so that it uses the folder instead of the url.

**Comment by retorquere** [comment]
That worked -- the conf file was just what I ended up with following the getting started guide.

I've tried replacing it with `https://gmail.com` but that keeps reloading, but -- page loading works.

**Comment by vanowm** [comment]
And if one needs manipulate remote content can it be done via typescript rather than rust?

**Comment by FabianLars** [comment]
@vanowm Well, it's not impossible, but you still need some rust to inject it. Your best bet is probably using `window.eval()` to add a script tag which imports your js file (or inline it directly, that works too). Of course you need to transpile typescript to javascript first, just like always.
As always my obligatory warning that by manipulating remote content you most likely breach some kind of TOS.

Also to be honest (speaking of my experiences only), if something like this is actually needed then it will pretty much always result in a bad end-user experience, but that's just my 2 cents :shrug:

**Comment by elibroftw** [comment]
> @retorquere @nuthinking as @nklayman said it is possible to navigate to a remote site inside your tauri app, whether you provide an `invoke_handler` or not. Not sure why you got a blank window.
> 
> I've tested this now with a new tauri project and here is my `main.rs` content:
> 
> ```rust
> #![cfg_attr(
>   all(not(debug_assertions), target_os = "windows"),
>   windows_subsystem = "windows"
> )]
> 
> mod cmd;
> 
> fn main() {
>   tauri::AppBuilder::new()
>     .setup(|webview, _| webview.eval("window.location.replace('https://google.com')"))
>     .build()
>     .run();
> }
> ```

Would be helpful if you updated this answer to work with the latest version? Thanks.

**Comment by FabianLars** [comment]
```rs
#![cfg_attr(
  all(not(debug_assertions), target_os = "windows"),
  windows_subsystem = "windows"
)]

use tauri::Manager;

fn main() {
  tauri::Builder::new()
    .setup(|app| {
      let window = app.get_window("main").unwrap();
      window.eval("window.location.replace('https://google.com')")
      Ok(())
    })
    .run(tauri::generate_context!())
    .expect("error running tauri app");
}
```

**Comment by elibroftw** [comment]
The way I did it was add the javascript code in `index.html` since JS was used anyways. Do you think there's no difference?

**Comment by FabianLars** [comment]
should be the same

**Comment by liby** [comment]
> Your best bet is probably using `window.eval()` to add a script tag which imports your js file (or inline it directly, that works too). Of course you need to transpile typescript to javascript first, just like always.

Hi, @FabianLars,  I've had some difficulties with this.

My idea is to load the remote page via the [WindowConfig.url](https://tauri.app/v1/api/config/#windowconfig.url) and inject some JavaScript code beforehand(change some styles).


<details> <summary>tauri.conf.json</summary>

```
{
  "package": {
    "productName": "Demo",
    "version": "0.1.0"
  },
  "build": {
    "devPath": "../dist",
    "distDir": "../dist",
    "beforeBuildCommand": "",
    "beforeDevCommand": "",
    "withGlobalTauri": true
  },
  "tauri": {
    "allowlist": {
      "all": true
    },
    "bundle": {
      "active": true,
      "category": "DeveloperTool",
      "copyright": "",
      "deb": {
        "depends": []
      },
      "externalBin": [],
      "longDescription": "",
      "macOS": {
        "entitlements": null,
        "exceptionDomain": "",
        "frameworks": [],
        "providerShortName": null,
        "signingIdentity": null
      },
      "resources": [],
      "shortDescription": "",
      "targets": "all",
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "security": {
      "csp": null
    },
    "updater": {
      "active": false
    },
    "windows": [
      {
        "url": "https://hoppscotch.io/",
        "fullscreen": false,
        "height": 728,
        "resizable": true,
        "width": 1200,
        "decorations": false,
        "transparent": true
      }
    ],
    "macOSPrivateApi": true
  }
}
```
</details>


I was going to use `window.eval` to do this after referring to the suggestions in some existing issues, but I found that it didn't work, It looks like the timing is not right.

Can you give me a best practice? Thank you and have a great day.

<details> <summary>main.rs</summary>

```
    tauri::Builder::default()
        .menu(menu_bar)
        .setup(|app| {
            let window = app.get_window("main").unwrap();

		    // not running
            window
                .eval("console.log(\"Hello, World!\");")
                .expect("TODO: panic message");
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
```
</details>

**Comment by FabianLars** [comment]
It likely does run fine, but just too early for your frontend to notice. for example if you wrap that eval call in a loop in a thread (so that it doesn't block the setup hook) it should start printing after a few iterations.

Since you're using rust already you could consider spawning the window in rust too which gives you access to https://docs.rs/tauri/latest/tauri/window/struct.WindowBuilder.html#method.initialization_script - probably also runs too early for a simple console.log though

**Comment by liby** [comment]
> Since you're using rust already you could consider spawning the window in rust too which gives you access to [docs.rs/tauri/latest/tauri/window/struct.WindowBuilder.html#method.initialization_script](https://docs.rs/tauri/latest/tauri/window/struct.WindowBuilder.html#method.initialization_script) - probably also runs too early for a simple console.log though

Looking at the example, this is to create a new window. But I only want to inject js code on the main window, am I misunderstanding.

```
    tauri::Builder::default()
        .setup(|app| {
            let window = tauri::WindowBuilder::new(app, "label", tauri::WindowUrl::default())
                .initialization_script(INIT_SCRIPT)
                .build()?;
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application")
```

**Comment by FabianLars** [comment]
> am I misunderstanding.

Yes a little bit. I was just giving you an alternative since you're using Rust anyway. It's not really relevant to your issue i guess so just ignore it,

**Comment by liby** [comment]
> Yes a little bit. I was just giving you an alternative since you're using Rust anyway. It's not really relevant to your issue i guess so just ignore it,

Oh, well. Although it did not solve my problem, but thank you for the alternative.

Let me think again.

**Comment by Redbeardjunior** [comment]
> ```rust
> "
> ```

sadly not working for me

**Comment by ddx95** [comment]
Hello everyone.
I have used the eval method to load a local server into a tauri app but I can't get to invoke my commands. I'm getting the "window.__TAURI_IPC__ is not a function" a function ever whenever withGlobalTauri is true or false. I'm currently looking at the tauri-invoke-http lib to resolve my problem. Is there another way to use tauri commands into a remote app loaded into a tauri window ?

**Comment by FabianLars** [comment]
You could wait for this PR https://github.com/tauri-apps/tauri/pull/5918

**Comment by pelasgus** [comment]
Using this config:
```
// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use tauri::Manager;

fn main() {
    tauri::Builder::default()
    .setup(|app| {
        let window = app.get_window("main").unwrap();
        window.eval("window.location.replace('https://google.com')");
        Ok(())
      })
      .run(tauri::generate_context!())
      .expect("error running tauri app");
}
```
How can I specify a specific user agent for the website to be loaded?

**Comment by FabianLars** [comment]
@tsimouris The user agent can currently only be set when the window is being created, in this case you can set it in tauri.conf.json: <https://tauri.app/v1/api/config/#windowconfig.useragent>. In case you end up creating the window in rust the WindowBuilder has a [user_agent method](https://tauri.app/v1/api/config/#windowconfig.useragent) too.

**Comment by pelasgus** [comment]
@FabianLars Under what section in the `tauri.conf.json`? excuse my ignorance, first brush with rust

**Comment by FabianLars** [comment]
In the window config, should look something like this:

![grafik](https://user-images.githubusercontent.com/30730186/231548667-eaf73e90-8905-4bbf-bd03-eb589aafe1e1.png)

**Comment by tsimouris** [comment]
@FabianLars 
```
Error `tauri.conf.json` error on `tauri > windows > 0`: Additional properties are not allowed ('user_agent' was unexpected)
```

**Comment by pelasgus** [comment]
@FabianLars thanks a lot for the help mate, was spelling it `user_agent` instead of `userAgent`
