### ISSUE TITLE
[bug] Failed to set the http scope of plugins

### ISSUE THREAD

**Issue by DWHengr** [tauri-apps/tauri#9866]
### Describe the bug

My tauri.conf.json file is as follows:
```
{
  "productName": "linyu-client",
  "version": "0.0.1",
  "identifier": "com.cershy",
  "build": {
    "beforeDevCommand": "npm run dev",
    "devUrl": "http://localhost:1420",
    "beforeBuildCommand": "npm run build",
    "frontendDist": "../dist"
  },
  "app": {
    "windows": [
      {
        "title": "linyu-client",
        "label": "login",
        "width": 360,
        "height": 510,
        "center": true,
        "transparent": true,
        "decorations": false,
        "fullscreen": false,
        "resizable": false,
        "shadow": false
      }
    ],
    "security": {
      "csp": null
    },
    "trayIcon": {
      "iconPath": "icons/icon.png",
      "iconAsTemplate": true
    }
  },
  "bundle": {
    "active": true,
    "targets": "all",
    "icon": [
      "icons/32x32.png",
      "icons/128x128.png",
      "icons/128x128@2x.png",
      "icons/icon.icns",
      "icons/icon.ico"
    ]
  },
  "plugins": {
    "http": {
      "scope": ["http://my.api.host/*"]
    }
  }
}

```

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 118.0.2088.76
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 16.20.0
    - yarn: 1.22.22
    - npm: 8.19.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.20
    - tauri-build [RUST]: 2.0.0-beta.16
    - wry [RUST]: 0.40.0
    - tao [RUST]: 0.28.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.12
    - @tauri-apps/cli [NPM]: 2.0.0-beta.18

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Stack trace

```text
error while running tauri application: PluginInitialization("http", "Error deserializing 'plugins.http' within your Tauri configuration: invalid type: map, expected unit")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by duanshuiliu** [comment]
![企业微信截图_17166271751713](https://github.com/tauri-apps/tauri/assets/17021690/117b1f71-0cb1-4882-bf56-9a200a00c105) 

use this config.  Below is myself:

path: project\src-tauri\capabilities\default.json
{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "default",
  "description": "Capability for the main window",
  "windows": ["main"],
  "permissions": [
    "path:default",
    "event:default",
    "window:default",
    "app:default",
    "image:default",
    "resources:default",
    "menu:default",
    "tray:default",
    "shell:allow-open",
    "window:allow-start-dragging",
    "window:allow-close",
    "window:allow-minimize",
    "window:allow-is-maximized",
    "window:allow-maximize",
    "window:allow-toggle-maximize",
    "window:allow-unmaximize",
    "window:allow-set-size",
    "window:allow-center",
    "window:allow-set-always-on-top",
    "window:allow-set-skip-taskbar",
    "window:allow-request-user-attention",
    "http:allow-fetch",
    {
      "identifier": "http:default",
      "allow": [
        { "url": "http://localhost:8088/*" },
      ]
    }
  ]
}

**Comment by duanshuiliu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by joebnb** [comment]
maybe should update docs https://v2.tauri.app/reference/javascript/http/ im also follow it into trap

**Comment by joebnb** [comment]
<img width="1057" alt="image" src="https://github.com/tauri-apps/tauri/assets/1646883/507c91eb-fe20-428e-abb9-0b78315fda41">

<img width="670" alt="image" src="https://github.com/tauri-apps/tauri/assets/1646883/d70204fb-8982-44ba-8099-2aba134c0186">

here also opposite docs in vscode tauri plugin, it's accept all,but actual behavior not as it‘s shows

**Comment by FabianLars** [comment]
"Allows all fetch operations" is indeed poorly worded. It means that the functions themselves are available, but this does not disable the scope mechanism.
