### ISSUE TITLE
[bug] There are problems with LogicalPosition and PhysicalPosition in v2

### ISSUE THREAD

**Issue by DWHengr** [tauri-apps/tauri#9868]
### Describe the bug

The display is normal in version v1. Then migrate to v2, in **on_tray_icon_event (| tray, In the event |)** method, it was found that there was an issue with obtaining location information through **event. position**. It seems that v2 needs to be converted to a logical position again.

v1:
![image](https://github.com/tauri-apps/tauri/assets/55067857/8e7b0a2f-a0ff-42e3-ad5f-9a06288aab69)

v2:
![image](https://github.com/tauri-apps/tauri/assets/55067857/a8d8148a-c56d-4622-b346-f0d8a2e138d8)

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 118.0.2088.76
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 16.20.0
    - yarn: 1.22.22
    - npm: 8.19.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.20
    - tauri-build [RUST]: 2.0.0-beta.16
    - wry [RUST]: 0.40.0
    - tao [RUST]: 0.28.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.12
    - @tauri-apps/cli [NPM]: 2.0.0-beta.18

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by amrbashir** [comment]
should be fixed by https://[github.com/tauri-apps/tray-icon/pull/164](https://github.com/tauri-apps/tray-icon/pull/164)
