### ISSUE TITLE
[feat] an option to not create a start menu folder for nsis installer

### ISSUE THREAD

**Issue by Legend-Master** [tauri-apps/tauri#9880]
### Describe the problem

We currently use nsis's built-in start menu shortcut folder picker and put the shortcut in that folder, and most of the times, user will just spam next and resulting `app/app.exe` in the start menu, it's pretty weird to put a single shortcut inside of a folder for me

And also, I don't think most end users understand what shortcut menu is and that page is always a source of confusion (I didn't know what that is after using Windows for 10 years before I started really learning those things myself at least)

### Describe the solution you'd like

Add an option to skip that picker page and just put the shortcut in the start menu without the folder, to be honest, I think it should even be the default

### Alternatives considered

Doing it manually with custom template

### Additional context

A simple comparison (not produced by tauri's nsis installer, just as a visual reference)

![image](https://github.com/tauri-apps/tauri/assets/68118705/90576fed-663d-4ca4-ad6d-1dbafce78bbb)
![image](https://github.com/tauri-apps/tauri/assets/68118705/ab9e56e2-9cdc-4756-9bb8-84b8312b7363)

**Comment by FabianLars** [comment]
> I think it should even be the default

Agreed.

**Comment by amrbashir** [comment]
The reason I went with that, is because on newer Win11 (and maybe newer versions of Win10) automatically detects that it only has one shortcut and will display it without a folder, what is your OS version?

**Comment by Legend-Master** [comment]
I'm on latest Windows 10 19045.4412, to be honest, I'm more about the confusion around it, most people understand desktop shortcuts but not start menu shortcuts, especially it shows you a list of folders and let you pick one...

**Comment by amrbashir** [comment]
I guess we can remove the directory and just keep the shortcut.

I think the idea was if a user has multiple apps from the same publisher, they are grouped under one directory, like Riot Games, install their games shortcuts under one directory called `Riot Games`.

![image](https://github.com/tauri-apps/tauri/assets/48618675/d2ec6e8e-fdbb-48d1-8766-05b3defa8e6b)

Anyways, I have no preference here, I am fine with both.

**Comment by Legend-Master** [comment]
> I think the idea was if a user has multiple apps from the same publisher, they are grouped under one directory

Yeah, but I think we currently use the product name as that folder name?

> Anyways, I have no preference here, I am fine with both.

Cool, I'll make a PR then

I think NSIS did this because you might want to put more shortcuts in that folder, but in our case, we don't
