### ISSUE TITLE
[bug] There is an issue with the window dragging size in the v2 version.

### ISSUE THREAD

**Issue by DWHengr** [tauri-apps/tauri#9881]
### Describe the bug

The window is set with **decorations: false** attribute. The top and left sides are displayed normally, but the right and bottom edges are not.

https://github.com/tauri-apps/tauri/assets/55067857/1ea9cb9a-973a-4213-bbd8-215a08646ff9

And there are also some issues with the response when dragging and changing the window on the top and left sides. Sometimes when my mouse goes out, the window remains unchanged, which is normal in v1 version.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 118.0.2088.76
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 16.20.0
    - yarn: 1.22.22
    - npm: 8.19.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.20
    - tauri-build [RUST]: 2.0.0-beta.16
    - wry [RUST]: 0.40.0
    - tao [RUST]: 0.28.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.12
    - @tauri-apps/cli [NPM]: 2.0.0-beta.18

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by wuxiemian** [comment]
@amrbashir I hope the fix for this bug can be released as soon as possible, as it also significantly affects the experience of my project.
