### ISSUE TITLE
[feat] Is it possible to add a window rounded corner configuration option to the tuari:windows configuration of the tuari.conf.json file?

### ISSUE THREAD

**Issue by lcqh2635** [tauri-apps/tauri#9886]
### Describe the problem

Is it possible to add a window rounded corner configuration option to the tuari:windows configuration of the tuari.conf.json file?

### Describe the solution you'd like

Is it possible to add a window rounded corner configuration option to the tuari:windows configuration of the tuari.conf.json file?

### Alternatives considered

Is it possible to add a window rounded corner configuration option to the tuari:windows configuration of the tuari.conf.json file?

**Comment by amrbashir** [comment]
Closing this issue as you clearly didn't take the time to even consider making a proper issue and just copy/pasted. Please make a proper issue and include which OS are you targeting with this option.
