### ISSUE TITLE
[bug] `tauri migrate` mis resolves globalShortcut & clipboard npm modules

### ISSUE THREAD

**Issue by kareemmahlees** [tauri-apps/tauri#9905]
### Describe the bug

While running `pnpm tauri migrate` on my Tauri v1 codebase, I noticed that the CLI replaced `@tauri-apps/api/globalShortcut` with `@tauri-apps/plugin-globalShortcut`, which should be `@tauri-apps/plugin-global-shortcut`.
Same thing for `@tauri-apps/api/clipboard`, expected `@tauri-apps/plugin-clipboard-manager`, found `@tauri-apps/plugin-clipboard`

### Reproduction

- Create a new _V1_ Tauri project.
- Use `@tauri-apps/api/globalShortcut` and/or `@tauri-apps/api/clipboard` modules.
- Run the `tauri migrate` command on the codebase.

### Expected behavior

Expected the CLI to resolve to the correct module names.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 125.0.2535.67
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.9.0
    - pnpm: 9.0.4
    - npm: 10.1.0
    - bun: 1.1.1

[-] Packages
    - tauri [RUST]: 2.0.0-beta.19 (no manifest)
    - tauri-build [RUST]: 2.0.0-beta.16 (no manifest)
    - wry [RUST]: 0.40.0 (no manifest)
    - tao [RUST]: 0.28.0 (no manifest)
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-beta.18

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:5173/
    - framework: React
    - bundler: Vite
```

### Additional context

I actually found the issue in [here](https://github.com/tauri-apps/tauri/blob/594e3e29390b0019ca5893c4287c18135b2fef48/tooling/cli/src/migrate/frontend.rs#L61).
Also, I am whiling to work on this myself.

**Comment by amrbashir** [comment]
thanks @kareemmahlees , feel free to open a PR if you wish
