### ISSUE TITLE
[bug] Is tauri compiled on windows static links?

### ISSUE THREAD

**Issue by dong0926** [tauri-apps/tauri#9918]
### Describe the bug

image 1
![img_v3_02bc_64f41e34-6894-4f0d-84ca-1fba6c2e1adg](https://github.com/tauri-apps/tauri/assets/126487814/69bdf71b-40ff-48b0-b775-8b53da9da4a9)

When installing on windows 7, the error box shown in Figure 1 appears. But the file will still output normally.
My WebView Winstallmode is embedBootstrapper.

image 2
![img_v3_02bc_061c359a-ce52-4606-8e52-1ce3ec7c538g](https://github.com/tauri-apps/tauri/assets/126487814/4733fcf4-a2b5-4999-9c70-b086e5f79b68)
The error box shown in Figure 2 is displayed when running on windows 7.
Does using "tauri build" default to a static link build?
I use "cargo rustc --release --target=i686-pc-windows-msvc -- -Ctarget-feature=+crt-static" when building other rust applications.
But "tauri build" doesn't seem to support "-- Ctarget-feature=+crt-static".

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 125.0.2535.67
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.74.0 (79e9716c9 2023-11-13)
    ✔ cargo: 1.74.0 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.17.1
    - pnpm: 8.7.0
    - yarn: 1.22.19
    - npm: 9.6.7

[-] Packages
    - tauri [RUST]: 1.6.5
    - tauri-build [RUST]: 1.5.2
    - wry [RUST]: 0.24.9
    - tao [RUST]: 0.16.9
    - @tauri-apps/api [NPM]: 1.5.5 (outdated, latest: 1.5.6)
    - @tauri-apps/cli [NPM]: 1.5.14

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: ../dist
    - framework: React
    - bundler: Vite
```

**Comment by amrbashir** [comment]
Can you try setting `STATIC_VCRUNTIME` env var to `true` before building?

**Comment by dong0926** [comment]
@amrbashir 
I have tried.Same as before setting.I guess STATIC VCRUNTIME defaults to true.

**Comment by amrbashir** [comment]
Can you translate the text in the dialogs?

**Comment by dong0926** [comment]
The procedure entry point EventSetInformation could not be located in the dynamic link library advapi32.dll.

@amrbashir

**Comment by dong0926** [comment]
@amrbashir 
[https://github.com/tauri-apps/tauri/issues/5163](url)
[https://github.com/tauri-apps/tauri/issues/727](url)
I found some of the same problems.
But none of them solved the problem on the product side. As a C-terminal product, there is no way to make users actively compatible. Look forward to a better solution.

**Comment by ahqsoftwares** [comment]
@dong0926 Is your windows 7 fully up to date?

**Comment by ahqsoftwares** [comment]
use something like legacy update to confirm that

**Comment by dong0926** [comment]
Yeah, not up to date.
Can you consider compatibility with it.

**Comment by ahqsoftwares** [comment]
> Yeah, not up to date. Can you consider compatibility with it.

If it is not up to date, we can't really do anything. The advapi32.dll must have the functions that tauri needs, also rust has moved windows 7 and 8.1 into 3rd tier targets, so really we have no way

**Comment by dong0926** [comment]
Ok, I see.
