### ISSUE TITLE
Windows: yarn tauri:build produces error because of wrong icons path

### ISSUE THREAD

**Issue by ho-ho-ho** [tauri-apps/tauri#992]
**Describe the bug**
When trying to `yarn tauri:build`, the following error is displayed:
```
 app:spawn Running "cargo tauri-bundler --features embedded-server --release" +0ms

   Compiling tauri v0.9.2
   Compiling tauritest v0.1.0 (D:\dev\tauritest\src-tauri)
    Finished release [optimized] target(s) in 15.06s
info: Target: x64
error: Path Error:`Path "D:\dev\tauritest\icons" does not exist or you don't have access!`

 app:spawn Command "cargo" failed with exit code: 1 +0ms

 app:tauri (runner) ⚠️  [FAIL] Cargo CLI has failed +0ms

 app:tauri Shutting down tauri process... +1ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
The problem is that it looks in `D:\dev\tauritest\icons` instead of `D:\dev\tauritest\src-tauri\icons`.

**To Reproduce**
1. create a fresh vue project: `vue create tauritest`
2. add tauri to the project: `vue add tauri`
3. `yarn tauri:build`

**Expected behavior**
Building a package (msi I suppose)

**Platform and Versions (please complete the following information):**
Operating System - Windows_NT(10.0.19041) - win32/x64
Microsoft Edge - 44.19041.423.0_neutral__8wekyb3d8bbwe

Node.js environment
  Node.js - 12.18.3
  tauri.js - 0.11.1 (outdated, latest: 0.12.0)

Rust environment
  rustc - 1.45.2
  cargo - 1.45.1
  tauri-bundler - 0.9.2

Global packages
  NPM - 6.14.6
  yarn - 1.22.4

**Additional context**
`yarn tauri:serve` works fine and I also tried all of this on a linux machine, there `yarn tauri:build` also worked fine. So I guess it's a windows problem only, probably with the tauri-bundler.

**Comment by ho-ho-ho** [comment]
I just tried it with installing tauri manually and not with `vue-cli-plugin-tauri` (since that is outdated) to get version 0.12.0. It works!

So I guess the problem was already fixed, but since the vue plugin wasn't updated you always get the old version of tauri (even `yarn upgrade tauri --latest` didn't do anythting).

**Comment by jbolda** [comment]
The vue plugin has been updated 🎉
