### ISSUE TITLE
[bug] Codesigning .dmg bundles strips configured dmg background

### ISSUE THREAD

**Issue by macjuul** [tauri-apps/tauri#9920]
### Describe the bug

It appears that after CodeSigning my Tauri 2 app, the custom background configured using the new background property in the tauri.conf.json is stripped out. I believe this applies to all customisations made to the dmg bundle.

### Reproduction

- Build an app locally on MacOS. The resulting .dmg correctly has a background
- Build an app with code signing enabled, the .dmg will now no longer have a background, and icons placed in the top left

Note that I have only tested this on GitHub CI

### Expected behavior

The dmg customisation should persist after code signing. It would be a real shame if this new functionality is rendered useless because of this issue

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.5.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.77.1 (7cf61ebde 2024-03-27)
    ✔ cargo: 1.77.1 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.12.2
    - pnpm: 9.0.6
    - npm: 10.5.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.18
    - tauri-build [RUST]: 2.0.0-beta.14
    - wry [RUST]: 0.39.3
    - tao [RUST]: 0.27.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.11
    - @tauri-apps/cli [NPM]: 2.0.0-beta.16

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Additional context

The application is built and signed using GitHub Actions

**Comment by FabianLars** [comment]
> Note that I have only tested this on GitHub CI

I assume that this is actually the issue and not code signing, see https://github.com/tauri-apps/tauri-action/issues/740 - please try the workaround mentioned there. If that doesn't help i'll re-open this issue.
