### ISSUE TITLE
[feat] add a macro to help using image as tray icon from rust api directly

### ISSUE THREAD

**Issue by Legend-Master** [tauri-apps/tauri#9947]
### Describe the problem

Currently to use an image (png or ico) in system tray, you need to enable `image-png` or `image-ico` feature which embeds image crate to the final app, and to not do that, you need to either transform your image to raw format or create it through config file

### Describe the solution you'd like

Add a macro to do this, like what we had for config files

**Comment by amrbashir** [comment]
I like the idea, I don't generally appreciate including `image` crate in the final app. Do you have an example of how the API should look like?

**Comment by Legend-Master** [comment]
Maybe something like `tray_icon_image!("../icons/tray_icon.png")`?

**Comment by amrbashir** [comment]
I see, I thought it involved more tray related code but I guess now that I understand the intention, this could be more than just for tray so I'd suggest just calling it `image!()` so it can be used also with windows and menus

**Comment by Legend-Master** [comment]
Makes sense, and since those images are fairly small, it should be better than shipping the image crate (32 x 32 x 4 is around 4 KB), I think we need to also improve the docs a little bit, I thought it's going to just embed the image but it actually is raw pixels, and the image I was using is like 256 x 256, it's just 4 KB for a png, but raw pixels are quite big, should probably be more clear about what it's doing
