### ISSUE TITLE
Make it easy to configure the app's homepage for Windows installers

### ISSUE THREAD

**Issue by sschuberth** [tauri-apps/tauri#9949]
### Discussed in https://github.com/tauri-apps/tauri/discussions/9943

<div type='discussions-op-text'>

<sup>Originally posted by **sschuberth** June  2, 2024</sup>
Hi there, is it currently possible to specify an app's homepage as part of installer metadata? Looking at https://tauri.app/v1/api/config/#windowsconfig and https://tauri.app/v1/api/config/#wixconfig it does not seem it's possible. I'm specifically looking for doing that for MSI, so that the app's homepage shows up in Windows' uninstall dialog.</div>

The goal would be to make configuring the app's homepage easy and independent of the installer backend used (MSI or NSIS) without the user needing to deals with implementation-specific concepts [like WiX fragments](https://tauri.app/v1/guides/building/windows/#customizing-the-wix-installer-template).

**Comment by amrbashir** [comment]
I am not sure where is this `homepage` will be rendered, can you show an example?

**Comment by sschuberth** [comment]
Unfortunately, Windows' built-in "Add or remove programs" control panel indeed does not seem to show the "About URL" by default (and I couldn't make it to), but third-party uninstallers like [UninstallView](https://www.nirsoft.net/utils/uninstall_view.html) do, along with a bunch of more metadata:

![image](https://github.com/tauri-apps/tauri/assets/349154/beae1405-da18-4fd9-bc02-e64dfbd8e736)

**Comment by sschuberth** [comment]
Thanks a lot @amrbashir for addressing this so quickly!
