### ISSUE TITLE
Javascript API: File stats

### ISSUE THREAD

**Issue by Miaourt** [tauri-apps/tauri#996]
Current Tauri's Javascript API lack functions allowing to retrieve stats about files, it would be a nice feature to have something like Node.js' :
https://nodejs.org/api/fs.html#fs_class_fs_stats
```JS
Stats {
  dev: 2114,
  ino: 48064969,
  mode: 33188,
  nlink: 1,
  uid: 85,
  gid: 100,
  rdev: 0,
  size: 527,
  blksize: 4096,
  blocks: 8,
  atimeMs: 1318289051000.1,
  mtimeMs: 1318289051000.1,
  ctimeMs: 1318289051000.1,
  birthtimeMs: 1318289051000.1,
  atime: Mon, 10 Oct 2011 23:24:11 GMT,
  mtime: Mon, 10 Oct 2011 23:24:11 GMT,
  ctime: Mon, 10 Oct 2011 23:24:11 GMT,
  birthtime: Mon, 10 Oct 2011 23:24:11 GMT }
```
```JS
BigIntStats {
  dev: 2114n,
  ino: 48064969n,
  mode: 33188n,
  nlink: 1n,
  uid: 85n,
  gid: 100n,
  rdev: 0n,
  size: 527n,
  blksize: 4096n,
  blocks: 8n,
  atimeMs: 1318289051000n,
  mtimeMs: 1318289051000n,
  ctimeMs: 1318289051000n,
  birthtimeMs: 1318289051000n,
  atimeNs: 1318289051000000000n,
  mtimeNs: 1318289051000000000n,
  ctimeNs: 1318289051000000000n,
  birthtimeNs: 1318289051000000000n,
  atime: Mon, 10 Oct 2011 23:24:11 GMT,
  mtime: Mon, 10 Oct 2011 23:24:11 GMT,
  ctime: Mon, 10 Oct 2011 23:24:11 GMT,
  birthtime: Mon, 10 Oct 2011 23:24:11 GMT }
```

**Comment by bRRRITSCOLD** [comment]
Also found a need for this today, would be nice.

**Comment by nothingismagick** [comment]
well, this will be different on different systems, and to be honest, its so niche that I think it would be better served as a Tauri plugin than directly inside core.

**Comment by atheros** [comment]
> well, this will be different on different systems, and to be honest, its so niche that I think it would be better served as a Tauri plugin than directly inside core.

It's not niche. Good practice demand you do a stat() call on any file or directory before working on it. This allows you to make sure, you are working on a file or directory, and supply a correct, user friendly message to the user.

Another use case is you want to validate file size before processing it.

Anyway, I do need that functionality, so here is my quick and dirty solution to the problem (tested on linux, however according to the docs, should work elsewhere too):

main.rs part:
```rust
#![cfg_attr(
  all(not(debug_assertions), target_os = "windows"),
  windows_subsystem = "windows"
)]

#[tauri::command]
fn filestat(filename: &str) -> Result<String, String> {
    use std::fs;
    use std::time::{UNIX_EPOCH};
    use std::fmt::{format};

    let metadata = fs::metadata(filename)
        .expect("Failed to stat file");
    let time = metadata.modified()
        .expect("Failed to get mtime");
    let millis = time.duration_since(UNIX_EPOCH)
        .expect("Failed to calculate mtime")
        .as_millis();

    let u64millis = u64::try_from(millis).expect("Integer to large");

    let is_file = if metadata.is_file() { "true" } else { "false" };
    let is_dir = if metadata.is_dir() { "true" } else { "false" };
    let size = metadata.len();

    return Ok(
        format!("{{\"mtime\":{},\"isFile\":{},\"isDir\":{},\"size\":{}}}", u64millis, is_file, is_dir, size)
    )
}

fn main() {
  tauri::Builder::default()
    .invoke_handler(tauri::generate_handler![filestat])
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
```

And typescript part:
```typescript
import {invoke} from '@tauri-apps/api';

export interface TauriFileStat {
    // Timestamp of last modification (UNIX epoch time, in milliseconds, just how JS likes it)
    mtime: number;
    /* Is this a directory. */
    isDir: boolean;
    /* Is this a regular file. */
    isFile: boolean;
    /* File size in bytes. */
    size: number;
}

export function tauriFileStat(filename: string): Promise<TauriFileStat> {
    return invoke('filestat', { filename }).then((x) => {
        return JSON.parse(x as string) as TauriFileStat;
    });
}
```

I hope this helps. IMHO this should probably handle 99% of use cases.

Neutralino is a similar framework, and it does provide stats in it's filesystem module exposed in webview (https://neutralino.js.org/docs/api/filesystem#filesystemgetstatspath).

**Comment by nothingismagick** [comment]
We have written advanced fs interface as an official plugin here. I think we cover pretty much all the possibilities here.

https://github.com/tauri-apps/tauri-plugin-fs-extra/blob/dev/src/lib.rs

**Comment by FabianLars** [comment]
And the new js api for v2 #5136 (if we will merge it like it is rn), will include this too :)

**Comment by stephanbogner** [comment]
Thanks @nothingismagick and @FabianLars! The plugin is already working well, but having this directly in the JS API sounds even better :heart:
