### ISSUE TITLE
[bug] assert_ipc_response (Rust tests for icp commands) are broken on 1.6.7

### ISSUE THREAD

**Issue by ospfranco** [tauri-apps/tauri#9960]
Hi, I'm trying to write tests for some of the Rust commands that are made available to JS. I was using the function provided by `tauri::test::assert_ipc_response` according to [this SO answer](https://stackoverflow.com/questions/77524788/writing-tests-for-tauri-commands-how-to-access-and-manage-state-in-test-environ):

```rust
fn create_app<R: tauri::Runtime>(mut builder: tauri::Builder<R>) -> tauri::App<R> {
    builder
        .setup(|app| {Ok(())})
        .invoke_handler(tauri::generate_handler![greet])
        .build(tauri::generate_context!())
        .expect("failed to build app")
}


#[cfg(test)]
mod tests {
    use tauri::Manager;
    #[test]
    fn something() {
        let data = r#"{"name": "the test"}"#;
        let app = super::create_app(tauri::test::mock_builder());
        let window = app.get_window("main").unwrap();
        tauri::test::assert_ipc_response(
            &window,
            tauri::InvokePayload {
                cmd: "greet".into(),
                tauri_module: None,
                callback: tauri::api::ipc::CallbackFn(0),
                error: tauri::api::ipc::CallbackFn(1),
                inner: serde_json::from_str(data).unwrap(),
            },
            Ok("Hello, the test! You've been greeted from Rust!"),
        );
    }
}
```

However, it seems there has been a recent update to the [Tauri runtime](https://github.com/advisories/GHSA-57fm-592m-34r7) where an `invoke_key` is now required. So now the `tauri::InvokePayload` now requires it and it fails if a matching value to the internal key is not provided:

```
received ipc message without a __TAURI_INVOKE_KEY__
thread 'nebula::api::tests::should_return_0_with_no_loaded_models' panicked at /Users/osp/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-1.6.7/src/test/mod.rs:318:38:
called `Result::unwrap()` on an `Err` value: InvokeKey
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

How is one supposed to write tests for the exposed Rust code? There is no documentation on how to achieve this.

Edit: This [PR](https://github.com/tauri-apps/tauri/commit/d950ac1239817d17324c035e5c4769ee71fc197d) added reference to invoke_key everywhere, but there is no way to retrieve it in a test context.

**Comment by lucasfernog** [comment]
We fixed this issue on v2 but didn't apply the same fix for v1, and it wasn't catch by CI because we applied this patch on a GitHub private fork from an advisory, which doesn't run CI tests by default. A fix will be deployed today.

**Comment by lucasfernog** [comment]
fix available on 1.6.8, you now must add `invoke_key: Some(tauri::test::INVOKE_KEY.into()),` to your payload

**Comment by ospfranco** [comment]
Thank you!

**Comment by ospfranco** [comment]
Also, what about docs, is this the correct way to write tests for the JS commands?

**Comment by ospfranco** [comment]
The way issues are closed and then never looked at again is frustrating. In any case, somebody stumbles upon this issue I've done a small write-up on how to write tests for JS commands:

https://ospfranco.com/writting-tests-for-tauri-rust-commands/

**Comment by DM1122** [comment]
Any idea how this translates to Tauri V2?
