### ISSUE TITLE
[feat] v2: Frameworks aren't being picked up for iOS builds

### ISSUE THREAD

**Issue by stijnfrishert** [tauri-apps/tauri#9962]
### Describe the bug

I'm using a Rust crate that depends on [coreaudio-rs](https://crates.io/crates/coreaudio-rs). For this work work on macOS/iOS, I need to link against the CoreAudio framework.

I'm building for iOS (using the v2 beta) and the linker tells me it's missing core audio symbols.

I've tried setting `bundle > iOS > frameworks` to `[ "CoreAudio" ]` in `tauri.conf.json`, but I get an error that the `"frameworks"` property is not allowed.

I've also tried setting the same on `bundle > macOS > frameworks`, but that doesn't help. Neither do I see `--framework CoreAudio` show up in the linker command.

### Expected behavior

I would expect `bundle > iOS > framework` to be valid and insert the frameworks into the linker command

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.5.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 20.12.2
    - pnpm: 9.1.2
    - npm: 10.5.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.20
    - tauri-build [RUST]: 2.0.0-beta.16
    - wry [RUST]: 0.40.0
    - tao [RUST]: 0.28.0
    - tauri-cli [RUST]: 2.0.0-beta.17
    - @tauri-apps/api [NPM]: 2.0.0-beta.12
    - @tauri-apps/cli [NPM]: 2.0.0-beta.18

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by stijnfrishert** [comment]
@FabianLars I'm yet unfamiliar with the Tauri internals, but if you could point me in the right direction I'm willing to try my hand at a PR :)

**Comment by pewsheen** [comment]
I haven't tried it on the release build, but for the dev build, I think the easiest way to embed the framework now is using `pnpm tauri ios open` to open the project in Xcode and add the framework from it.

**Comment by stijnfrishert** [comment]
Thanks, @pewsheen, didn't know that was possible, so I learned something. 😄

Decided to go the PR route and learn something about Tauri's internals. Hopefully someone will pick up the PR soon and help me with some remaining questions. :)

**Comment by lucasfernog** [comment]
I've got "coreaudio" to at least compile using these frameworks:
```
"iOS": {
      "frameworks": [
        "AudioToolbox",
        "CoreAudio",
        "OpenAL",
      ]
    }
```
though I didn't manage to make their Rust example work (seems like it's crashing, maybe it's missing some delegate code like they have in their iOS example)

**Comment by IT-ess** [comment]
Hello !
Any news about a doc section for embedding frameworks into apps ? I want to use `tauri-plugin-nfc` on my iOS app, but I struggle with the whole dynamic framework libraries and embedding thing. 

Thanks for all the work !

**Comment by stijnfrishert** [comment]
From the way I've used it, it's quite easy: any of the Apple frameworks you use need to be listed under `bundle/ios/frameworks` in your Tauri config file, and will be picked up by the build system.

Note that you have to rerun `tauri ios init` to get this to work, and iirc I even had to throw away the `gen/apple` folder a couple of times for changes to get picked up.

As to which frameworks are required for the `tauri-plugin-nfc` plugin are required for it to work, I have no idea, but that should be figure-outable.

**Comment by IT-ess** [comment]
The thing is that the framework I need, `CoreNFC` is a dynamic framework. And I face a lot of issues to [embed this framework into my bundle, as this is required for dynamic frameworks](https://stackoverflow.com/questions/57687170/do-not-embed-embed-sign-embed-without-signing-what-are-they-what-th)
If I find any solution I will open a documentation PR.
