### ISSUE TITLE
[bug] [v2] drag and drop unable to locate in MacOS

### ISSUE THREAD

**Issue by drl990114** [tauri-apps/tauri#9966]
### Describe the bug

There are replication steps in readme, and I suspect there may be similar issues on other platforms (Windows, Linux).

I'm not sure if this historical issue is caused by the same issue, https://github.com/tauri-apps/tauri/issues/6695

### Reproduction

Reproduction repo: https://github.com/drl990114/tauri-issue

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.5.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.12.2
    - pnpm: 9.0.4
    - yarn: 1.22.19
    - npm: 10.5.0
    - bun: 1.1.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.22
    - tauri-build [RUST]: 2.0.0-beta.17
    - wry [RUST]: 0.40.1
    - tao [RUST]: 0.28.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.13
    - @tauri-apps/cli [NPM]: 2.0.0-beta.20

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by jerefrer** [comment]
[Another issue](https://github.com/ShipBit/wingman-ai/issues/161) mentions a fix for this on Tauri 1.x, specifying that you should add `"fileDropEnabled": false"` within `app.windows` in `tauri.config.json`

However on Tauri 2.x the option has been renamed `dragDropEnabled`, and I can tell it just fixed the issue for me in my 2.0 project. Here's what I have in my `tauri.config.json`:
```json
  "app": {
    "windows": [
      {
        "title": "Tibetan Translator",
        "width": 1280,
        "height": 1024,
        "resizable": true,
        "fullscreen": false,
        "dragDropEnabled": false
      }
    ],
```

**Comment by drl990114** [comment]
Thanks for the guidance. I set `drag_and_drop(false)` in the beta.14 version, and it does work. I will explore the new version later.

But does this mean that the drag event of webview and the drag event of tauri cannot be used at the same time? (I will try it after updating to the latest version)

**Comment by FabianLars** [comment]
Yes, but that's always been the case and is sadly expected behavior.
