### ISSUE TITLE
Javascript API: FS events

### ISSUE THREAD

**Issue by Miaourt** [tauri-apps/tauri#997]
I would like to monitor folders / files for changes, an reflect those changes in my applications.

Node.js have nice functions to watch over files and directory changes, which is impossible in Tauri's current Javascript API.
https://nodejs.org/api/fs.html#fs_class_fs_fswatcher

Node.js' way of doing is returning an object emitting event on changes, something like that for Tauri would be a nice addition.

There is also the same stuff for file's stats, which would be appreciated in the same time :
https://nodejs.org/api/fs.html#fs_class_fs_statwatcher
But likely would depends on #996

**Comment by lucasfernog** [comment]
Following the explanation on #996, I believe this should be a community plugin, specially since it's a niche use case and brings additional dependencies.
