### ISSUE TITLE
[bug] Can not get user mediaDevice on macOS

### ISSUE THREAD

**Issue by chudongvip** [tauri-apps/tauri#9980]
### Describe the bug

I want to implement the functionality of opening the camera on macOS. I have browsed through many issues and also tried adding the `Info.plist` file, but I still cannot get it to work. Finally, I found the [API Example](https://github.com/tauri-apps/tauri/tree/dev/examples/api) in the official example, but I still encounter the error shown in the image.

![WechatIMG64](https://github.com/tauri-apps/tauri/assets/31001856/fef9870d-be1e-4c96-8cfd-814878de5e3c)

> My computer is not a Linux system, and it supports WebRTC, so what could be the reason for this issue?

### Reproduction

https://github.com/tauri-apps/tauri/tree/dev/examples/api

### Expected behavior

use the WebRTC API to access the camera on my macOS system

### Full `tauri info` output

```text
> api@1.0.0 tauri /Users/chudong/Downloads/tauri-dev/examples/api
> node ../../tooling/cli/node/tauri.js "info"


[✔] Environment
    - OS: Mac OS 10.15.7 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 16.18.1
    - pnpm: 8.2.0
    - yarn: 1.22.4
    - npm: 8.19.2

[-] Packages
    - tauri [RUST]: 2.0.0-beta.22
    - tauri-build [RUST]: 2.0.0-beta.17
    - wry [RUST]: 0.40.0
    - tao [RUST]: 0.28.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.13
    - @tauri-apps/cli [NPM]: 2.0.0-beta.20

[-] App
    - build-type: bundle
    - CSP: connect-src ipc: http://ipc.localhost; font-src https://fonts.gstatic.com; img-src 'self' asset: http://asset.localhost blob: data:; default-src 'self' customprotocol: asset:; style-src 'unsafe-inline' 'self' https://fonts.googleapis.com
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

**Comment by FabianLars** [comment]
iirc the min macos version for usermedia support in wkwebview (the webview we use) is macos 11 (the example works fine for me on 14)
