### ISSUE TITLE
[bug] rollback to tauri beta.18 from 22, webview build error

### ISSUE THREAD

**Issue by skydig** [tauri-apps/tauri#9986]
### Describe the bug

error[E0308]: mismatched types
2df342d903acd47\tauri-2.0.0-beta.18\src\webvie
   |
1077 |   pub fn url(&self) -> Url {
   |                        --- expected `url::Url` because of return type
1078 |     self.webview.dispatcher.url().unwrap()
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Url`, found `String`

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 125.0.2535.79
    ✔ MSVC:
        - Visual Studio Enterprise 2017
        - Visual Studio Enterprise 2019
    ✔ rustc: 1.79.0-nightly (a07f3eb43 2024-04-11)
    ✔ cargo: 1.79.0-nightly (74fd5bc73 2024-04-10)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: nightly-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.12.2
    - npm: 10.5.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.18
    - tauri-build [RUST]: 2.0.0-beta.17
    - wry [RUST]: 0.40.1
    - tao [RUST]: 0.28.0
    - tauri-cli [RUST]: 2.0.0-beta.20
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-beta.20

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
```

**Comment by FabianLars** [comment]
in v2 beta we only support the latest versions. To not leave you empty handed, try adding `tauri-utils` (and maybe tauri-runtime and tauri-runtime-wry) as direct dependencies of your app with older versions.

What's the reason you're downgrading to beta.18? Are there any bugs in 19-22?

**Comment by skydig** [comment]
@FabianLars .
use 22, I can not spawn sidecar, I run cargo tauri build to generate package and manually change exe directory and exe name, tauri window report out of memory, but can spawn exe after refresh page.
use beta.16 sidecar can work. so I want to rollback tauri beta version to 1X.
thanks.

**Comment by skydig** [comment]
@FabianLars 
after install the package and I change 
meilisearch-windows-amd64.exe.exe to meilisearch-windows-amd64.exe-x86_64-pc-windows-msvc.exe
tauri can run but crash with blank screen.
meilisearch-windows-amd64.exe-x86_64-pc-windows-msvc.exe is too big?(100M)

![图片](https://github.com/tauri-apps/tauri/assets/27293515/a6ff6280-18ff-4e7e-984b-4aa85f671738)

**Comment by FabianLars** [comment]
the executable size shouldn't matter

**Comment by skydig** [comment]
@FabianLars 
oh,
same code, I have ever success to spawn without crash. I just run cargo update, I don't know which module affects:(

**Comment by skydig** [comment]
@FabianLars 
I switch to std::process::Command temp...

I think "out of memory" reason may be following code？

 let (mut rx, mut _child) = sidecar_command
            .spawn()
            .expect("Failed to spawn meili");
         let window = app.get_webview_window("main").unwrap();
            tauri::async_runtime::spawn(async move {
            // read events such as stdout
            while let Some(event) = rx.recv().await {
                if let CommandEvent::Stdout(line) = event {
                    window
                    .emit("message", Some(format!("'{:?}'", line)))
                    .expect("failed to emit event");
                // write to stdin
                //child.write("message from Rust\n".as_bytes()).unwrap();
                println!("{:?}",format!("'{:?}'", line));
                }
            }

so guess, latest sidecar main issue may be the "-x86_64-pc-windows-msvc" is stripped with .exe.exe when package and dev debug.

thanks!
