### ISSUE TITLE
[bug] “npm run tauri dev” trips on ampersands in the location path, at least on Windows.

### ISSUE THREAD

**Issue by lil-greasy** [tauri-apps/tauri#9988]
### Describe the bug

I’m just getting started with Tauri (and Node, for that matter), so I may be making some incorrect assumptions about how the commands operate.

But if I’m in my project directory in PowerShell (which is something like “`C:\Users\myname\OneDrive - Oregon Health & Science University\Documents\dev\app app`”) and I enter “`npm run tauri dev`”, I get the following error:

    'Science' is not recognized as an internal or external command,
    operable program or batch file.
    node:internal/modules/cjs/loader:1147
      throw err;
      ^

If I move my project directory outside the directory with the ampersand in the name, the command runs as expected.

### Reproduction

1. Create a Tauri project in a directory with an ampersand somewhere in the path.
2. Within the project directory, run “`npm run tauri dev`”.

### Expected behavior

My project should run in dev mode.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 125.0.2535.85
    ✔ MSVC:
        - Visual Studio Build Tools 2019
        - Visual Studio Build Tools 2022
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.10.0
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 1.6.8
    - tauri-build [RUST]: 1.5.2
    - wry [RUST]: 0.24.10
    - tao [RUST]: 0.16.9
    - tauri-cli [RUST]: 1.5.8
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 1.5.14

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../src
    - devPath: ../src
```

**Comment by amrbashir** [comment]
This is not an issue with our CLI but rather in `npm` CLI itself
